### ISSUE TITLE
The Performance of v0.2.0 is 20X slower than v0.1.12

### ISSUE THREAD

**Issue by ivorytwoer** [pytorch/pytorch#2351]
Hi, i use pytroch to train  all-cnn model on cifar-10 by [Entropy-SGD](https://github.com/ucla-vision/entropy-sgd/tree/master/python). 

The log of v0.1.12_2 is 
Train: [ 1] 0.9442 33.32% [13.62s]
Train: [ 2] 0.8139 28.38% [14.39s]
Train: [ 3] 0.7006 24.22% [13.76s]
Train: [ 4] 0.6254 21.68% [13.71s]
Train: [ 5] 0.5720 19.96% [13.63s]

and the log of v0.2.0_1 is
Train: [ 1] 0.2238 7.84% [294.03s]
Train: [ 2] 0.1349 4.66% [291.71s]
Train: [ 3] 0.0950 3.26% [291.67s]
Train: [ 4] 0.0715 2.41% [290.50s]
Train: [ 5] 0.0558 1.89% [295.84s]

All code is same but the only difference is the version of pytroch. Why the performance of the two has the gap?

P.S. Can you re-generate the pip resource for v.0.1.12 ?

**Comment by pavanky** [comment]
The v0.2.0_1 seems to be converging faster. Are you using the same batch size?

**Comment by ivorytwoer** [comment]
@pavanky Yes, all the params are the same. The convergence with epoch number seems faster by v0.2.0_1, but with time is much slower. The whole traing process is intolerable. I will ask the author of [Entropy-SGD](https://github.com/ucla-vision/entropy-sgd/tree/master/python) for more details. Thank you very much!

**Comment by pratikac** [comment]
@ivorytwoer, I cannot recreate your numbers. With pytorch v0.2, GTX 1080 and default arguments for allcnn at https://github.com/ucla-vision/entropy-sgd (just run `python train.py -m allcnn`), I get
```
Train: [ 0] 0.6071 21.35% [438.25s]
Test: [ 0] 0.3610 12.4470%
``` 
which is close to the numbers with v0.1.12. (i) Can you try to remove v0.1.12 and reinstall it again, and (ii) your numbers look off, after the 1st epoch, the training and validation errors with Entropy-SGD for allcnn on CIFAR-10 should be about 20% and 12%, respectively.

**Comment by ivorytwoer** [comment]
@pratikac 
Thank you for your reply.

Running `python train.py -m allcnn --gamma=1e-4 --scoping=1e-3 --noise=1e-4 -B 200 -L 20` with pytorch v0.2.0 on a Titan X (Pascal), I get results like:
```
Train: [ 0] 0.6048 21.14% [298.86s]
Test: [ 0] 0.3562 12.1964%

Train: [ 1] 0.2279 7.80% [294.37s]
Train: [ 2] 0.1307 4.56% [293.68s]
Train: [ 3] 0.0896 3.09% [298.54s]
Train: [ 4] 0.0684 2.33% [293.65s]
Train: [ 5] 0.0558 1.88% [297.58s]
Test: [ 5] 0.3631 9.5353%

Train: [ 6] 0.0445 1.46% [294.67s]
Train: [ 7] 0.0395 1.34% [298.33s]
Train: [ 8] 0.0348 1.12% [295.30s]
Train: [ 9] 0.0310 1.07% [293.53s]
Train: [10] 0.0289 0.96% [291.89s]
Test: [10] 0.4058 9.6966%
```
However, before I upgraded pytorch, result of running the same command was like:
```
Train: [ 0] 1.3807 48.86% [14.19s]
Test: [ 0] 0.9708 33.8474%

Train: [ 1] 0.9442 33.32% [13.62s]
Train: [ 2] 0.8139 28.38% [14.39s]
Train: [ 3] 0.7006 24.22% [13.76s]
Train: [ 4] 0.6254 21.68% [13.71s]
Train: [ 5] 0.5720 19.96% [13.63s]
Test: [ 5] 0.5057 17.4680%

Train: [ 6] 0.5326 18.45% [13.66s]
Train: [ 7] 0.4979 17.38% [13.45s]
Train: [ 8] 0.4722 16.39% [13.73s]
Train: [ 9] 0.4371 15.04% [13.58s]
Train: [10] 0.4100 14.21% [13.96s]
Test: [10] 0.4053 13.7587%
```
I cann't find .whl file from [pytorch.org](http://pytorch.org/), so I will reinstall v0.1.12 from source and then try to run this command again.

**Comment by pratikac** [comment]
I suspect there is something else in your code unrelated to pytorch versions because 14 secs to perform L=20 epochs on allcnn with cifar-10 does not look right :)

**Comment by ivorytwoer** [comment]
@pratikac Yeah! I think that I forgot to add the option `-L 20` and then got this result. Thank you for  locating the problem! Also thank @pavanky for your help :)
Sorry for disturbing you both and I'm really sorry about my carelessness.
