### ISSUE TITLE
Add nn.functional.interpolate slow down backward process more than 10 times

### ISSUE THREAD

**Issue by xwang-icsi** [pytorch/pytorch#23531]
## 🐛 Bug

It seems like that the time cost for backpropagation with F.interpolate layer is very high, not sure how to fix it. In my experiments, I added around 10 AdaptiaveAvgPooling and F.interpolate layer combination in ResNet50 for parameter-free decode and encode, my codes was slowed down for more than 4 times. I checked the code, the AdaptiaveAvgPooling layer works fine, but interpolate layer seems to slow down the code a lot during backpropagation. The toy experiment to reproduce is attached below. First one is for vanilla 2-layer model without interpolate layer, time cost is around 0.009s. Second one is for 2-layer model with interpolate layer, time cost is around 0.07s. 

I also calculate the time cost for forwarding interpolate layer only, time cost is very small, around 8e-5s/iter. Therefore, the time cost was mainly from backward process. However, nn.functional.interpolate is parameter free operator, there shouldn't be that much difference.

Tried Pytorch1.1 with cuda9.0 and Pytorch0.4.1 with cuda8.0, got similar results.

##################################################
2-layer model without interpolate layer:
```python
    import torch
    import time
    import numpy as np
    import torch.nn.functional as F

    dtype = torch.float
    device = torch.device("cuda:0")

    N, D_in, H, D_out = 256, 1000, 16, 10

    x = torch.randn(N, 32, 32, D_in, device=device, dtype=dtype)
    y = torch.randn(N*32*32, D_out, device=device, dtype=dtype)

    w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
    w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

    learning_rate = 1e-10
    torch.cuda.synchronize()
    start = time.time()
    for t in range(500):
        x_ = x.view(N, D_in, 32, 32).view(N*32*32, D_in)
        # x_ = F.interpolate(x_, size=(32, 32)).view(N*32*32, D_in)
        y_pred = x_.mm(w1).clamp(min=0).mm(w2)

        loss = (y_pred - y).pow(2).sum()
        print(t, loss.item())

        loss.backward()

        with torch.no_grad():
            w1 -= learning_rate * w1.grad
            w2 -= learning_rate * w2.grad

            # Manually zero the gradients after updating weights
            w1.grad.zero_()
            w2.grad.zero_()
    end = time.time()
    print((end-start)/500)
```
Time cost: 0.009s/iter

##################################################
2-layer model with interpolate layer:

```python
    import torch
    import time
    import numpy as np
    import torch.nn.functional as F

    dtype = torch.float
    device = torch.device("cuda:0")

    N, D_in, H, D_out = 256, 1000, 16, 10

    x = torch.randn(N, 16, 16, D_in, device=device, dtype=dtype)
    y = torch.randn(N*32*32, D_out, device=device, dtype=dtype)

    w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
    w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

    learning_rate = 1e-10
    torch.cuda.synchronize()
    start = time.time()
    for t in range(500):
        x_ = x.view(N, D_in, 16, 16)
        x_ = F.interpolate(x_, size=(32, 32)).view(N*32*32, D_in)
        y_pred = x_.mm(w1).clamp(min=0).mm(w2)

        loss = (y_pred - y).pow(2).sum()
        print(t, loss.item())

        loss.backward()

        with torch.no_grad():
            w1 -= learning_rate * w1.grad
            w2 -= learning_rate * w2.grad

            # Manually zero the gradients after updating weights
            w1.grad.zero_()
            w2.grad.zero_()
    end = time.time()
    print((end-start)/500)
```

Time cost: 0.07s/iter

**Comment by VitalyFedyunin** [comment]
Please add `torch.cuda.synchronize()` before `end = time.time()` as it might change test results.

**Comment by xwang-icsi** [comment]
Thanks for your reply. Updated my code. Performance is still the same. Still about 10 times slower.

**Comment by fmassa** [comment]
What's your pytorch version? There was an update on the backward functions for interpolate after the 1.1 release

**Comment by xwang-icsi** [comment]
My Pytorch version is 1.1.0

**Comment by fmassa** [comment]
Can you try updating it to a nightly release?

**Comment by xwang-icsi** [comment]
Hi, thank you so much, after updating to nightly version, time cost for 2-layer model with interpolate is about 0.013s/iter and 2-layer model without interpolate is 0.009s/iter. Much better now.
