### ISSUE TITLE
CUDA_VISIBLE_DEVICES setting unavailble after called torch.cuda.is_available function

### ISSUE THREAD

**Issue by ygliang2009** [pytorch/pytorch#23544]
When i indicate cuda number directly by using os['CUDA_VISIBLE_DEVICES'] = cudaIndex, i found the function is unavailable. The program consistently use cuda index 0 by default. after a long time debug, i suspect the sentence " use_cuda = torch.cuda.is_available()" make everything losing efficacy. When i reverse both of them, then it works. 

python version: 2.7.16
torch version:1.1.0
linux version:centos 7.6.1810

**Comment by SsnL** [comment]
The env var only has effect before pytorch access cuda. In general you should better use a device object or `torch.cuda.set_device`. If you really want to use this env var, put it at the top before everything or just set it on command line.

**Comment by ygliang2009** [comment]
thanks a lot
