### ISSUE TITLE
Not able to install after building successfully from source

### ISSUE THREAD

**Issue by vyi** [pytorch/pytorch#23554]
## ❓ Questions and Help

On Ubuntu 16.04 with python 3.5.2 and gcc-5.4.0 
I have successfully built **pytorch v1.1.0** with cmake and also did `sudo make install`

Then I tried to run 
`python3 -c "import torch"`  
`python -c "import torch"`   
neither worked!  

Next I tried to install it from the `setup.py` file present in the main directory:  
`sudo python3 setup.py install` 

but that also fails complaining following 
```

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/torch/csrc/stub.o -L/home/vivek/Documents/Compiled/pytorch/pytorch/torch/lib -L/usr/local/cuda/lib64 -lshm -ltorch_python -o build/lib.linux-x86_64-2.7/torch/_C.so -Wl,--no-as-needed /home/vivek/Documents/Compiled/pytorch/pytorch/torch/lib/libcaffe2_gpu.so -Wl,--as-needed -Wl,-rpath,$ORIGIN/lib
/usr/bin/ld: cannot find -lshm
/usr/bin/ld: cannot find -ltorch_python
```
How do I get those libraries `shm` and `torch_python`? Should those be built when I did `make -j4` to build from source? Is there some path issue?

Please help!

**Comment by soumith** [comment]
follow our readme. from what you've done, we see that you haven't.

**Comment by vyi** [comment]
@soumith I don't want to install Anaconda on my system. Is that the only way to get pytorch working? by installing Anaconda?

**Comment by soumith** [comment]
you **can** get pytorch working without anaconda, we just dont offer support for it, so you're on your own.

**Comment by vyi** [comment]
@soumith Thats great.

**Comment by cjolivier01** [comment]
I followed readme, used conda, et. Still get this error. The libs it's looking for are in build/lib but for some reason, it can;t find them when it links. Done so many clean builds, all day.

**Comment by leonardo0lyj** [comment]
> I followed readme, used conda, etc. Still get this error. The libs it's looking for are in build/lib but for some reason, it can;t find them when it links. Done so many clean builds, all day.
> v1.3.0, but I saw it with latest version as well before.

Same here. Have you resolved it? Really appreciated,

**Comment by Dr-Noob** [comment]
As @vyi suspected, this seems to be a path issue. I solved it by just doing symlinks to the right location. In my case, it was looking for the libs at `/home/user/pytorch/torch/lib`, while they were actually at `/home/user/pytorch/INSTALL/home/user/pytorch/torch/lib`. So I just had to to:

```
cd /home/user/pytorch/torch/lib
ln -s /home/user/pytorch/INSTALL/home/user/pytorch/torch/lib/*.so .
```
