### ISSUE TITLE
torch.nn.Upsample undeterministic behavior

### ISSUE THREAD

**Issue by ShangxuanWu** [pytorch/pytorch#23571]
## 📚 Documentation

`torch.nn.Upsample()` shares the same undeterministic backward issue with `torch.nn.functional.upsample()`, which could not be easily turned off using CuDNN flag. But in the documentation, we didn't state that. Can we add the documentation for `torch.nn.Upsample()`?

**Comment by ailzhang** [comment]
@ShangxuanWu Can you provide a minimal repro? Thanks!
