### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by thinhnggia** [pytorch/pytorch#23589]
So I have tried the script in the issue **ValueError: only one element tensors can be converted to Python scalars #22674** with the newest Pytorch Version, but it seems doesn't work. Do you have any idea about this

The configuration im using:
Pytorch version: 1.1.0
Python version:3.7.3
torchvision: 0.3.0

**Comment by vishwakftw** [comment]
Please install the nightly build, and not the latest release.

**Comment by VitalyFedyunin** [comment]
Closing as answered. Feel free to reopen if you have any followup.
