### ISSUE TITLE
Purpose of 'debug' folder in JIT archive

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#23582]
## 🐛 Bug

In Pytorch 1.2.0, a new 'debug' folder with a fairly large pickled file has come in to existence.
I have a 3MB model and this debug folder seems to take up an extra 1MB making it a 4MB model for no specific purpose.

Worse, deleting the folder means the model fails to load.
As a workaround I created an empty file in the folder and it successfully loads and runs as a 3MB model again.

## To Reproduce

1. Save a traced jit module in pytorch 1.2.0-dev
2. Attempt to delete the created 'debug' folder
3. Fails to read model
4. Create an empty 'debug/model.pkl' file.
5. Model successfully loads

## Expected behavior

No debug folder unless requested or an ability to ask for it to be removed (release mode?).

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0-dev
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: Titan V
 - Any other relevant information:

**Comment by soumith** [comment]
@driazati @suo can we make saving debug info enabled by default but give users the option to not save it?

**Comment by suo** [comment]
@jamesr66a, 1MB for source location info seems like a lot, are we not properly memoizing source strings?

We can make it an option to save without it, @soumith do you consider this a blocker for 1.2?

**Comment by soumith** [comment]
@suo not a blocker but would be great to have if it's something quick to do

**Comment by suo** [comment]
@xsacha To answer the question "what is the `debug` folder for?": it stores information that maps locations in Torchscript's serialized format to locations in the original source (your model as you wrote it). This is used to give better error information if your loaded model throws.

**Comment by jamesr66a** [comment]
@suo we do correctly memoize source ranges. The likely issue is that tracing dumps a full Python stack trace in the Source struct (whereas script only instantiates one Source per compiled source object), and so every expression gets a big Source object attached to it. I considered disabling collecting these stack traces, but decided to err on the side of usability.

Adding a flag to export should be possible, but last time I tried doing that I got yelled at

**Comment by xsacha** [comment]
@suo thanks, that makes sense I guess. Will there be any issues when throwing if the pkl file is empty at that stage? Like, will it crash instead of throwing?

I also have a 5MB model that has 2MB debug folder (making it 7MB combined). It seems to be a substantial increase.

**Comment by apaszke** [comment]
It would be reasonable to make the `debug` part optional i.e. have an option to exclude it while exporting, and accept the case where it's missing in case someone has deleted it themselves.

**Comment by xsacha** [comment]
I found the issue is much worse on smaller models such as this 256KB model (BlazeFace), which becomes 1.7MB!

[blaze.zip](https://github.com/pytorch/pytorch/files/3454881/blaze.zip)

**Comment by suo** [comment]
That is indeed really bad! Do you have the original source for the model so we can try to optimize the space a little bit? In the meantime, we'll look into making debug stuff optional.

**Comment by xsacha** [comment]
Source repository: https://github.com/tkat0/PyTorch_BlazeFace

**Comment by resistor** [comment]
I just made https://github.com/pytorch/pytorch/pull/23659 to compress debug symbols.

In quick testing, this reduces the symbols on BlazeFace from 1.4MB to 44KB.

**Comment by resistor** [comment]
Note that I haven't tested it a lot yet and am not recommending pulling it into the release.

**Comment by suo** [comment]
@xsacha: If you would like to make your existing models slimmer, here is a script that will take a model and compress the debug info:

```
import os
import tempfile
import zipfile


def compress_debug(zipname):
    # find debug thing
    with zipfile.ZipFile(zipname, 'r') as orig:
        for name in orig.namelist():
            if "debug" in name:
                debug_filename = name
                data = orig.read(name)

    # generate a temp file
    tmpfd, tmpname = tempfile.mkstemp(dir=os.path.dirname(zipname))
    os.close(tmpfd)

    # create a temp copy of the archive without debug info
    with zipfile.ZipFile(zipname, 'r') as zin:
        with zipfile.ZipFile(tmpname, 'w') as zout:
            for item in zin.infolist():
                if item.filename != debug_filename:
                    zout.writestr(item, zin.read(item.filename))

    # replace with the temp archive
    os.remove(zipname)
    os.rename(tmpname, zipname)

    # now add debug info with compression
    with zipfile.ZipFile(zipname, mode='a', compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(debug_filename, data)


compress_debug("blaze.zip")
```

**Comment by resistor** [comment]
Looks like miniz's compressor isn't quite as good as macOS's built-in zip and only gets the debug info down to 281KB rather than 44KB.  I'll see if there are other flags to twiddle.

**Comment by xsacha** [comment]
Thanks for the work on this! :)

**Comment by apaszke** [comment]
44KB of debug for 256KB model still is a significant portion, so I think we should make the debug info optional.

**Comment by resistor** [comment]
@apaszke There's still substantial room for improvement here.  Just compressing the model source and the model.json takes another 60KB off of the total serialized size.  And there's definitely room to improve the debug info format both by making the information itself less verbose and make it more readily compressible.

**Comment by resistor** [comment]
@apaszke Here are some updated baselines:

FaceBlaze w/o debug compression:  1790762 bytes (as downloaded)

I then loaded the model and re-exported it with my compression patches:
FaceBlaze w/ debug compression: 397026 bytes
FaceBlaze w/ debug & model compression: 326451 bytes (https://github.com/pytorch/pytorch/pull/23723)

In the latter two versions, I used `zipinfo -v` to inspect the archive. I see that `debug/blaze.pkl` occupies 19540 compressed bytes in the archive.  This *should* be an upper bound on further savings from eliminating debug info.

Just for reference, if I use my system zip compressor, I get a total archive size of 286451 bytes.  The delta appears to come from compressing tensors and from removing alignment padding.

**Comment by resistor** [comment]
I just noticed that the *uncompressed* size of the debug info is not constant through a re-export cycle.  I'm seeing an uncompressed size of 1418719 bytes in the original and only 280902 after a re-export.  Are we dropping some information along the way?  That would negate my methodology above.

cc @jamesr66a

**Comment by xsacha** [comment]
Instead of compressing individual component of the JIT archive in special ways, why isn't the entire archive compressed in something better than a standard ZIP?

**Comment by resistor** [comment]
> Instead of compressing individual component of the JIT archive in special ways, why isn't the entire archive compressed in something better than a standard ZIP?

There's nothing "special" going on - we just weren't actually using the builtin compression features of the ZIP format until now.

To be clear, we use ZIP over alternative formats because it fits our needs best on several axes:
* There was a micro implementation that could be pulled into PyTorch without introducing a new external dependency or depending on Python functionality.
* It is easily inspected and modified with available tools on every widespread platform, including Windows.
* It can support mmap'able tensors via the combination of:
* * It supports fast table-of-contents lookups without having to decompress the archive first.
* * It supports both compressed and uncompressed members within the same archive.
* * It allows arbitrary member alignment within the file.

Overall, ZIP offered both great simplicity and desirable functionality compared with other formats.  If you want to sacrifice that maximum compression ratio, it shouldn't be too hard to write a wrapper that takes in an alternative format, decompresses it, and recompresses it before handing it to PyTorch.  For example, you could probably use the builtin facilities in Python to implement a `.tar.xz` to `.zip` convert at model load time: https://docs.python.org/3/library/archiving.html

What was going on here was that, we had always marked all members of a serialized model as uncompressed within the ZIP.  We want this behavior for tensors (to make them mmap'able), but having it for all other members was simply an oversight.

**Comment by xsacha** [comment]
Thanks, that clears it up.

**Comment by eellison** [comment]
I think the purpose and size of the `debug` folder have been addressed so I'm closing. Please re-open if you think otherwise, or maybe create a separate issue to request an optional debug folder.
