### ISSUE TITLE
Bug1: /home/zhulijun/pytorch/c10/macros/Macros.h:21:37: fatal error: c10/macros/cmake_macros.h: No such file or directory

### ISSUE THREAD

**Issue by Peterisfar** [pytorch/pytorch#23593]
![image](https://user-images.githubusercontent.com/31852119/62210193-21032580-b3ce-11e9-9fe4-7879fdf4efde.png)

why so many bugs???

**Comment by VitalyFedyunin** [comment]
Hello! Could you please provide more details such as:
1) Command line used to build project.
2) Looks like you are trying to create custom operator/extension, am I correct?
