### ISSUE TITLE
torch.CharTensor / torch.cuda.CharTensor lack some math functions

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#2359]
`.abs()` is an example; as of https://github.com/pytorch/pytorch/pull/2357 `.neg()` is an example as well.

**Comment by gchanan** [comment]
look at ByteTensors as well; seems reasonable that abs would be defined there (as a no-op), but maybe not neg.

**Comment by fmassa** [comment]
I think this can be closed with #2357 an #2358

**Comment by fmassa** [comment]
Maybe not yet, as only `neg` was implemented. Are there still functions missing?
