### ISSUE TITLE
Loading the Linux-trained Torch model on Windows?

### ISSUE THREAD

**Issue by mesut92** [pytorch/pytorch#23595]
## ❓ Questions and Help

Hi,

Can i load same model on linux and windows?  I trained a model on python with jit.ScriptModule. I loaded it with C++ in Linux? Now, I want to load it on Windows, but it gives debug error during loading model.

Envs:
Windows 10
Torch 1.1.0 (Pytorch and Libtorch same version(Debug) )
compiler: Microsoft Visual Studio 2017 MSVC

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply. 

Also please attache debug error, so people can identify issue.
