### ISSUE TITLE
One Compatibility issue in THCReduce.cuh

### ISSUE THREAD

**Issue by lld533** [pytorch/pytorch#2360]
Hi,
Would you please explicitly convert the first input argument into LONG in [Line318, THCReduce.cuh](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCReduce.cuh#L318) in the following way?
`THC_getGridFromTiles(THCCeilDiv((long)outElements, (long)block.x), grid);`

As I'm trying to compile pytorch-0.2.0 on Windows with CUDA 8.0, everything goes smooth for a long time till I'm blocked here with an error; it says no template could be fitted for this function call with 2 args. I guess nvcc for windows fail to implement an implicit conversion. Much thanks!

**Comment by apaszke** [comment]
This should work after merging the Windows PRs.
