### ISSUE TITLE
[jit] string.split only splits on newlines

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#23616]
It should split on any whitespace, right now it just splits on `' '`

```python
def fn(x):
    # type: (str)
    return x.split()

s = "a b\nc\td"
print(fn(s))
print(torch.jit.script(fn)(s))
```
outputs

```
['a', 'b', 'c', 'd']
['a', 'b\nc\td']
```

cc @suo

**Comment by bwasti** [comment]
Fix here:
https://github.com/pytorch/pytorch/pull/23669

**Comment by eellison** [comment]
Closed with https://github.com/pytorch/pytorch/pull/23669
