### ISSUE TITLE
Installation with non-root access

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#23649]
When I run `python setup.py install` it need root access to install the final package. How can I install that in user home (I mean user packages for pip)?

**Comment by calincru** [comment]
Have you tried `python setup.py install --user`?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by mahmoodn** [comment]
Sorry for the delay. Thank you. --user fixed that.
