### ISSUE TITLE
Back propagation trough slicing with list breaks

### ISSUE THREAD

**Issue by joh4n** [pytorch/pytorch#23653]
## 🐛 Bug

Back propagating trough a slice operation twice results in broadcasting issue in the second back propagating, when the slicing was done using a list.

## To Reproduce

1.  Run the code below
## broken
```python
slize = [1, 2, 3, 4]
x = torch.randn(10, requires_grad=True)
y = x[slize]
y.sum().backward()
# breaks second time calling backward
y.sum().backward() # rasises RuntimeErroe
```

## works
```python
x = torch.randn(10, requires_grad=True)
y = x[1:4]
y.sum().backward()
y.sum().backward()
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Manjaro Linux
GCC version: (GCC) 8.3.0
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.1.0
[conda] Could not collect

x

**Comment by mrshenli** [comment]
I confirm that I can reproduce the error, but I am not sure if this is indeed a bug, because slicing creates a new tensor, while `x[1:4]` just creates a view. In the first case, after running backward without `retain_graph=True`, the edge from `y` to `x` is discarded, and hence the second backward does not go through. However, in the second case, `y` is a view of `x` and shares the same storage, so it seems fine? @gchanan 

The error message was:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/shenli/pytorch/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/users/shenli/pytorch/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by SsnL** [comment]
I don't think this is a bug. You are backproping twice through the x->y graph.

The difference in x->y is that the first version does a copy where the the second does a view. The copy relies on a buffer kept alive to to backprop while the second doesn't need one. So backproping the first version twice will error, as buffers are freed at backproping.

In generally you should only backprop multiple times with `retain_graph=True`, as said in the error message.
