### ISSUE TITLE
Official and nightly wheel structure plan

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#23656]
In the PyTorch 1.2, we are going to change how we deliver wheels to our users, to help provide a better user experience beyond having to provide an official wheel URL on pytorch.org/

## Constraints

* We support multiple platforms (Linux, OS X, Windows) and versions of Python (2.7, 3.5, 3.6, 3.7)
* We have multiple variants of our wheels; for example, PyTorch 1.1 CPU-only versus CUDA 9.2 versus CUDA 10.1. It is up to the user to specify what variant they want.
* We have downstream domain libraries which depend on a specific version and variant of the wheel. For example, torchvision-cu100 requires torch-cu100, and will not work with a cu92 build of torch. If you install a specific variant of a downstream domain library, we should ensure that the upstream correct torch library gets installed.
* It is easier to have a single, unchanging command to install the latest PyTorch nightly, than a command which has to be updated every time we make an update.
* Local version identifiers (e.g., the cpu in 0.1.0+cpu) can only be selected in a version constraint in pip if you specify an exact version constraint (e.g., ==0.1.0+cpu) or you specify no constraint at all; wildcards are not supported (e.g., `==*+cpu` or `==*` do NOT match local versions). Source: https://www.python.org/dev/peps/pep-0440/#version-matching
* Channels (added using the -f flag to pip) are additive: once you include a channel, all of the packages advertised in that channel are considered for selection.
* It is more elegant to ask a user to pip install torch_vision==0.1.0+cpu than it is to ask them to install a wheel URL directly. This is because, with a version constraint, pip automatically handles select the correct Python version and operating system; a wheel URL must be constructed exactly correctly.
* You cannot setup a link that redirects to a wheel URL based on a parameter; pip requires the URL you pass it to have the correct filename. Source: https://github.com/pypa/pip/issues/6821#issuecomment-517276509
* Some users want to access old nightlies programmatically; they desire a stable URL format
    * When we started adding local version to labels, this broke the stable URL format.
* It is not so easy to change the version of preexisting wheels; it is not a matter of renaming the files, because the filename must reflect the actual name of the wheel in question
* Putting wheels in a same folder or different folder doesn’t matter; the important thing is having an index file which indexes over all wheels

## The plan

* **Add local version identifiers to all of our alternative wheel configurations for official release.** Instead of torch-1.1.0, we will have torch-1.2.0+cpu. This change has already landed in nightlies and the PyTorch 1.2 release will adopt this naming convention. The local version identifier will be omitted for the default configuration (CUDA 10.1, for the upcoming release).
* **Add local version identifiers to our nightly wheels, omitting it for the default version.** Although this will turn out to not be strictly necessary (per our other plans), we will adopt this for consistency with official release. When we change default CUDA configuration, the nightly wheels will be the first to see changes in local version identifier.
* **Add a single unified index for official releases.** This index will live at https://download.pytorch.org/whl/torch_stable.html
    * Default configuration continues to be uploaded to PyPI, so `pip install torch` works
    * For alternate configurations, you write: `pip install torch==1.2.0+cpu -f `[`https://download.pytorch.org/whl/torch_stable.html`](https://download.pytorch.org/whl/torch_stable.html)
* **Continue to populate separate indices for alternative wheel configurations.** The utility of these indices will be to conveniently install the latest version of a package. These indexes will continue to live in, e.g., [https://download.pytorch.org/whl/cpu/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html) and [https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html](https://download.pytorch.org/whl/torch_stable.html)
    * To install the latest version of the package under some configuration, you say `pip install torch -f `[`https://download.pytorch.org/whl/cpu/torch_stable.html`](https://download.pytorch.org/whl/torch_stable.html)
* **Put domain API libraries in same indices as torch release.** If a domain API library contains CUDA code, we directly put it in cu100, etc. folder, and it is included in the top-level index and the cu100 index. If a domain API library is ABI compatible with all CUDA/CPU releases because it is CPU only (e.g., torchaudio), we put it in the *top-level* folder, and it is included in ALL indexes (including subdirectories).
* **(Low priority) Provide a non-pip compliant HTTP endpoint to download the wheel for some date and configuration.** We do not officially support accessing nightly package wheels directly; that is the point of the package indexes ingested by pip. However, sometimes, it is convenient to request a wheel without using pip. This HTTP endpoint will let you conveniently do so.
    * Example possible URL: https://download.pytorch.org/whl_redirect?date=20190801&config=cpu&abi=cp36&platform=macosx_10_6_x86_64
    * Suggested implementation strategy: read in the full package index, search for the package that matches the requested configuration and 301 redirect to it.
    * It’s not altogether clear what the best place to put this endpoint would be

## Things that don’t work

* **Status quo.** We ask users to install specific wheel URL for their pip release, which is not elegant. Nightly format is works pretty well: we ask the user to add our channel (one channel per CUDA configuration) and they can install a package by name and get the latest version.
* **Put all the nightlies in a single index.** There is no way to ask for the cu90 latest nightly.
* **Setup a special “redirector” URL which redirects you to the latest nightly under some configuration for pip.** Redirection doesn’t work with pip. It might be useful for other users though.
* **Setup up a JSON index which advertises the latest version available for a package.** This is not elegant because the command to install a nightly changes every day (unless you do some sort of two-hop process where you download the JSON first, and then parlay that into the actual URL you install.

## Other things

* Torch nightlies should declare a dependency on numpy; right now the install instructions work around this but it should be easy to package it properly in the first place.

cc @soumith @VivekPanyam

**Comment by ezyang** [comment]
UPDATE: We're also planning to rename the `torch_nightly` wheels to `torch`, in order to ensure that you never have two copies of torch installed in the same environment.

**Comment by ezyang** [comment]
All done now!

**Comment by alsrgv** [comment]
@ezyang, it would be really nice if `pip install torch==1.2.0 -f https://download.pytorch.org/whl/torch_stable.html` was resolved to https://download.pytorch.org/whl/cu100/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl (or other cu100 file), but for some reason, it gets resolved to https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp27-cp27mu-manylinux1_x86_64.whl.

Because of that, if you want cu100 version, you have to omit `-f https://download.pytorch.org/whl/torch_stable.html` which makes build scripts much more complicated.

**Comment by ezyang** [comment]
@alsrgv Use `pip install torch==1.2.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html`

```
$ pp pip install torch==1.2.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html
Looking in links: https://download.pytorch.org/whl/cu100/torch_stable.html                              
Collecting torch==1.2.0
  Downloading https://files.pythonhosted.org/packages/05/65/5248be50c55ab7429dd5c11f5e2f9f5865606b80e854ca63139ad1a584f2/torch-1.2.0-cp37-cp37m-manylinux1_x86_64.whl (748.9MB)
```

Actually, I thought your command is supposed to work, because https://www.python.org/dev/peps/pep-0440/#version-matching implies that local versions are supposed to be excluded, but I confirmed on pip 19.1.1 it does not. That is quite strange.

**Comment by soumith** [comment]
local version identifiers are excluded.

If one does `pip install torch==1.2.0+cpu` then it will pick that wheel.
What is not supported (and pypi devs were clear about it) is that `torch==1.2.0 -f` wont magically use the `-f` server, it actually prefers the stable upstream pypi server.

It was the origin of the issue https://github.com/pytorch/pytorch/issues/19990 which I filed based on what I found out.

**Comment by ezyang** [comment]
@soumith This is not what I observed empirically though:

```
$ pip install torch==1.2.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html                                    
Collecting torch==1.2.0
  Downloading https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp37-cp37m-manylinux1_x86_64.whl (663.1MB)
```

**Comment by ezyang** [comment]
Apparently, I (and others) have misread the spec here: https://github.com/pypa/pip/issues/4632

**Comment by ezyang** [comment]
Per https://github.com/pypa/pip/issues/6333 you can get the correct wheel if you use three equals signs:

```
pip install torch===1.2.0 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by peterjc123** [comment]
@ezyang Looks like this is still not fixed for Windows.
