### ISSUE TITLE
 The expanded size of the tensor (13) must match the existing size (12) at non-singleton dimension 1.  Target sizes: [3, 13].  Tensor sizes: [12]

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/pytorch#23652]
``` 
The expanded size of the tensor (13) must match the existing size (12) at non-singleton dimension 1.  Target sizes: [3, 13].  Tensor sizes: [12]
```
I'm getting this error when using Facebook LASER Pytorch bi-LSTM model (https://github.com/facebookresearch/LASER). According to a number of issues in different frameworks

- Pytorch Yolo: https://github.com/marvis/pytorch-yolo2/issues/84

it seems to be a Pytorch error, that is the one discussed here:
https://discuss.pytorch.org/t/embeddings-index-out-of-range-error/12582
https://stackoverflow.com/questions/56010551/pytorch-embedding-index-out-of-range

Pytorch version: 1.0.0

Unfortunately, we cannot reproduce this problem systematically, so it's not easy to understand the exact conditions when it happens: if we run with same input after the error, it may work.

**Comment by mrshenli** [comment]
Hi @loretoparisi, can you post a traceback of this error?

CC @zou3519

**Comment by zou3519** [comment]
> it seems to be a Pytorch error, that is the one discussed here:
https://discuss.pytorch.org/t/embeddings-index-out-of-range-error/12582
https://stackoverflow.com/questions/56010551/pytorch-embedding-index-out-of-range

Both of those cases look like user error to me. 

> Unfortunately, we cannot reproduce this problem systematically, so it's not easy to understand the exact conditions when it happens: if we run with same input after the error, it may work.

The error is suggesting that something is performing binary operations with tensors whose size do not match. A traceback and/or repro would be really helpful here.

**Comment by loretoparisi** [comment]
@zou3519 please wait we will try to provide more context / traceback cc @simonefrancia

**Comment by loretoparisi** [comment]
@zou3519 just to be sure, could you help be the get the right traceback from the Error. I'm not sure which kind of python error object is this. Thank you.

**Comment by gchanan** [comment]
I'm going to close this because it's not actionable:
1) there's no reproduction
2) the specific error check in question is correct
3) it's very likely a problem with a downstream library

**Comment by loretoparisi** [comment]
@gchanan I can reproduce this error systematically. I'm running FB [LASER](https://github.com/facebookresearch/LASER) model. It happens at the very first pre-trained model inference, after loading. The second inference does not show this error.
