### ISSUE TITLE
Event based DataLoader

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#23662]
## Motivation

Typically, in Deep Learning, the training process revolves around running consecutive epochs with a training and development dataset. Today for each new epoch, the DataLoader needs to be restarted and data loading is momentarily paused. 

This, in our experience, causes a non-trivial amount of overhead.

## Pitch

The proposed feature would be for a data loader object that is continuous. It's always loading data for the current epoch or the next epoch. The user of the `DataLoader` is notified of a transition via some event or flag change.

Here is some example sudo code of this experience:
```python
data_loader = DataLoader(datasets={'train_dataset': train_dataset,
                                   'validation_dataset': validation_dataset}, 
                         batch_sizes={'train_dataset': 256,
                                      'validation_dataset': 1024},
                         repeat=True)

while training:
    while data_loader.dataset == 'train_dataset':
        batch = next(data_loader)
        predictions = nn.Model(batch)
        nn.Loss(predictions).backward()
    
    while data_loader.dataset == 'validation_dataset':
        batch = next(data_loader)
        predictions = nn.Model(batch)
        evaluate(predictions)
```

This `DataLoader` design means the `DataLoader` would never need to restart; furthermore, it would always be preloading the next batch of data.

**Comment by SsnL** [comment]
This raises a good point about this momentary pause. The solution I had in mind is to introduce a way to reuse data loader workers. Do you think that it will satisfy your needs, or do you think that it is not sufficient?

**Comment by PetrochukM** [comment]
@SsnL I read the discussion on reusing data loader workers. I think the time it takes to start a worker on Linux should be fairly trivial. However, the time it takes for the first batch to be ready is not trivial. 

I think this proposal would solve both the worker reuse issue and the time to the first batch.

**Comment by apaszke** [comment]
@PetrochukM this is not all that difficult to implement in user code if you instantiate the iterators earlier. Consider this:
```python
train_loader = DataLoader(...)
valid_loader = DataLoader(...)

# DataLoaders only start the loading when you take their iterators
train_iter = iter(train_loader)
valid_iter = None
while True:
  for batch in train_iter:
    if near_end_of_training():
      valid_iter = iter(valid_loader)

  for batch in valid_iter:
    if near_end_of_validation():
      train_iter = iter(train_loader)

```

**Comment by PetrochukM** [comment]
@apaszke For sure, it's something that I plan to do. I'll have a cleaner hack with samplers; however, I see this idea is being more helpful to the community.

**Comment by PetrochukM** [comment]
Another idea would be to add more work to an existing data loader, I updated my original comment.

**Comment by PetrochukM** [comment]
For example, it took me up to 2 minutes to load the first batch of size 256. It takes 30 seconds to load without any workers. With the same number of workers as the number of CPUs, it takes 2 minutes to load. 

This is a significant amount of time!

**Comment by PetrochukM** [comment]
@apaszke I took a stab at implementing something that'd work: https://github.com/pytorch/pytorch/issues/15849#issuecomment-518126031

**Comment by PetrochukM** [comment]
I used the above approach to train, I think it is a good approach. I had no issues with it. I don't think the above feature request is necessary anymore.
