### ISSUE TITLE
Mention future package dependency for python 2.7 in documentation

### ISSUE THREAD

**Issue by vincentqb** [pytorch/pytorch#23670]
The future package should be mentioned in the list of dependencies for building from source with python 2.7 on https://pytorch.org/get-started/locally/

## Environment

PyTorch version: 1.2.0a0+722e5b1
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0a0+722e5b1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl_fft                   1.0.12           py27ha843d7b_0
[conda] mkl_random                1.0.2            py27hd81dba3_0
[conda] torch                     1.2.0a0+722e5b1          pypi_0    pypi

**Comment by rmcavoy** [comment]
This should probably just be phrased as suggestion for fixing the generic install documentation as it is known future is needed since it is in the requirements.txt file.
