### ISSUE TITLE
Calculate the derivative of a node with respect to an input image

### ISSUE THREAD

**Issue by BBAUniversity** [pytorch/pytorch#2369]
I would like to calculate the derivative of any node in respect of image input to implement visualization methods using PyTorch.

Any suggestions ?

**Comment by jekbradbury** [comment]
If you make the input image a `Variable` with `requires_grad=True` you will get that derivative in `image.grad` after calling `.backward(grad_output)` on the node.

**Comment by BBAUniversity** [comment]
Thanks for your response, I will test it. How I can alculate this derivative of internal node or classe node and not the cost function ?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for such questions.
