### ISSUE TITLE
Versions of TorchScript

### ISSUE THREAD

**Issue by NeilWangziyu** [pytorch/pytorch#23714]
## ❓ Questions and Help
I use Pytroch nightly build to generate a TorchScript, and meanwhile, I use Stable version to generate TorchScript with same code. 

However, I found the content of the TorchScript is not same.

So my question is that is there are any difference versions of TorchScript and libtorch? Can I use an old version of libtorch to read the TorchScript generate from newer version of python code?

**Comment by driazati** [comment]
We've made some breaking serialization changes between versions (those will be detailed in the 1.2 release notes soon). We try to maintain backwards compatibility between versions, but we don't make any guarantees about forward compatibility at this point.

**Comment by NeilWangziyu** [comment]
Thanks a lot.
May I ask when 1.2 will be released, Is there any schedule?

**Comment by driazati** [comment]
No official schedule as of yet, but probably within the next few weeks
