### ISSUE TITLE
Documentation for Tensor.record_stream()

### ISSUE THREAD

**Issue by sublee** [pytorch/pytorch#23729]
## 📚 Documentation

PyTorch doesn't seem to disagree to use multiple CUDA streams. It provides several useful APIs, such as `torch.cuda.current_stream()` and `torch.cuda.Event`, to control streams at the application level.

But multiple streams on the same GPU may cause memory corruption. It's related to `CUDACachingAllocator`.

> Allocations are associated with a stream. Once freed, blocks can be re-allocated on the same stream, ...

The allocator records the stream in which a block was allocated for a tensor to detect when it can be safely freed. But the tensor can be accessed in another stream. In this case, the block might be reallocated before the access has finished. For example, let's assume we allocated a tensor at the default stream, and another stream copies the tensor. In this case, a block of the tensor might be reallocated for a new tensor at the default stream.

It seems that memory corruption can be prevented by `Tensor.record_stream()` effectively. If I understood correctly, this API makes the allocator detect the time when the blocks can be freed safely. But `Tensor.record_stream()` is not documented yet. So we shouldn't use it at the application level.

I suggest making `Tensor.record_stream()` as a public API. It would be very useful to develop multi-stream applications with less unpredictable bugs.

**Comment by ezyang** [comment]
@colesbury: Our stream semantics is that all uses need to be ordered, and allocation/deallocations count as uses. So if you free in one stream and then allocate on another stream, you need to synchronize. This differs from normal CUDA API, where frees implicitly synchronize.

It seems fine to make this part of the public API and document it, but there are other ways you can go about solving this problem. Certainly the fact that we differ from the CUDA API should be documented, however.

**Comment by sublee** [comment]
Hi @ezyang, thanks for the hint.

It could be better to explain the detail of my case to discuss an alternative approach.

I'm trying to optimize the overall performance of pipeline parallelism by overlapping copy and computation on the same GPU. Specifically, while `GPU[i]` is copying a tensor to `GPU[i+1]`, I want to make `GPU[i]` start the next task. To achieve it, I introduced a separate stream only for copy. If I synchronize the computation stream to the copy stream, I think it cannot be possible to overlap copy and computation.

This code snippet shows how I use a separate stream to overlap copy and computation on the same GPU:

```python
import torch

# We will use GPU-0 and GPU-1.
torch.cuda.synchronize(0)
torch.cuda.synchronize(1)

to_copy = torch.ones(100, device=0)
to_calc = torch.rand(100, device=0)

# Introduce a separate stream for copy and synchronize to the default stream.
# The copy will be started when "to_copy" is ready.
copy_stream = torch.cuda.Stream(0)
copy_stream.wait_stream(torch.cuda.default_stream(0))

with torch.cuda.stream(copy_stream):
    # Both the copy and computation on "to_calc" will start at the same time.
    # But the copy will be finished later.
    torch.cuda._sleep(100000000)
    copied = to_copy.to(1)

    # Uncomment this line to fix the corruption.
    # to_copy.record_stream(copy_stream)

    # Free "to_copy". Then without record_stream(), "to_calc * 100" will reuse
    # blocks in "to_copy".
    del to_copy

# Here's any computation which allocates some new tensors on the default stream.
to_calc * 100

# It should print 100. But it might be about 5000.
print(copied.sum().item())
```

If you agree that only `Tensor.record_stream()` can save me from this case, I'm willing to submit a PR with the documentation of `record_stream()`.

**Comment by ezyang** [comment]
I am not too sure. Maybe @colesbury can tell.

**Comment by colesbury** [comment]
@sublee Tensor.record_stream can simplify this sort of use-case and we'll happily accept a PR documenting the method.

The timeline (with record_stream commented out) looks like:

```
GPU 1 default    :  [allocate copied]                                   + ->                         + -> [copied.sum()] -> [delete copied]
GPU 0 copy_stream:                                                  +-> + -> [copied.copy_(to_copy)] + ->
GPU 0 default    :  [allocate to_copy] -> [fill to_copy with ones] -+-> [delete to_copy] -> [to_calc * 100] ->
```

The `+` denote synchronization and the `->` denote sequential ordering within a stream. There are three synchronizations (ignoring the torch.cuda.synchronize calls at the beginning). The copy_stream.wait_stream is the first. The inter-GPU copy `to_copy.to(1)` does a synchronization before and after between copy_stream (on GPU 0) and the current stream on GPU 1 (which is GPU 1's default stream in this case)

Note that there is no synchronization preventing the deletion of to_copy from happening before the use. (Also deletions always "occur" in the allocation stream regardless of the current stream).

You can fix this with:

```python
import torch

# We will use GPU-0 and GPU-1.
torch.cuda.synchronize(0)
torch.cuda.synchronize(1)

to_copy = torch.ones(100, device=0)
to_calc = torch.rand(100, device=0)

# Introduce a separate stream for copy and synchronize to the default stream.
# The copy will be started when "to_copy" is ready.
default_stream = torch.cuda.default_stream(0)
copy_stream = torch.cuda.Stream(0)
copy_stream.wait_stream(default_stream)

with torch.cuda.stream(copy_stream):
    # Both the copy and computation on "to_calc" will start at the same time.
    # But the copy will be finished later.
    torch.cuda._sleep(100000000)
    copied = to_copy.to(1)

# Here's any computation which allocates some new tensors on the default stream.
to_calc * 100

# Free "to_copy".
default_stream.wait_stream(copy_stream)
del to_copy

to_calc * 200

print(copied.sum().item())
```

Now the timeline looks like:

```
GPU 1 default    :  [allocate copied]                                   + ->                         + -> [copied.sum()] -> [delete copied]
GPU 0 copy_stream:                                                  +-> + -> [copied.copy_(to_copy)] + ->
GPU 0 default    :  [allocate to_copy] -> [fill to_copy with ones] -+-> [to_calc * 100] ->           + -> [del to_copy] -> [to_cal * 200]
```

**Comment by sublee** [comment]
@colesbury Thanks for your great explanation.

Now I understood there's another way to fix the corruption in my case. But it would be very complicated to implement for me. Because my objective requires an elaborated control flow over Python code and an autograd graph. The asynchronous memory management cannot be integrated into it with an elegant way.

As you pointed out, `record_stream()` would be the simplest solution. I'll write a documentation for it and submit a PR soon.

**Comment by sublee** [comment]
The PR for documentation has just been merged.

**Comment by thuzhf** [comment]
Hi @colesbury, I find if I add a line `copied.sum().item()` after `copied = to_copy.to(1)`, then @sublee's original code will work without uncommenting `to_copy.record_stream(copy_stream)`. Do you have idea why this is happening?
