### ISSUE TITLE
Axes don't match error while trying to enumerate data loader

### ISSUE THREAD

**Issue by svabhishek29** [pytorch/pytorch#2373]
Hi, I was trying to run the vnet implementation in pytorch
(https://github.com/mattmacy/vnet.pytorch) and after normalising the scans with 512, 512, 500, 0.7 for x_max, y_max, z_max, voxspacing, when I call the train function on the line where the for loop is enumerating through the data loader I get a axes don't match array error. I am not understand how to fix this. Any help would be really helpful. I am a newbie in machine learning

Thanks
Abhishek

**Comment by soumith** [comment]
can you give the full error? It's hard to understand from your description on what is not matching

**Comment by soumith** [comment]
actually, this is surely a userland issue. please post in https://discuss.pytorch.org for further help.
