### ISSUE TITLE
Optimizer incorrect typing annotation

### ISSUE THREAD

**Issue by utikeev** [pytorch/pytorch#23731]
## 🐛 Bug

`torch.optim.optimizer.pyi` contains:
```python
from typing import Iterable, Union, Callable, Optional
from .. import Tensor

_params_t = Union[Iterable[Tensor], dict]

class Optimizer:
    def __init__(self, params: _params_t) -> None: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state_dict: dict) -> None: ...
    def zero_grad(self) -> None: ...
    def step(self, closure: Optional[Callable[[], float]]=...) -> None: ...
    def add_param_group(self, param_group: dict) -> None: ...
```

This interface lacks:
* init parameter `defaults: Optional[dict]`
* class fields
* * `defaults`
* * `state`
* * `param_groups`

## To Reproduce

1. Make a class which inherits `Optimizer`:
```python
class MyOptimizer(Optimizer):
    def __init__(self, params: List[torch.Tensor]):
        defaults = dict(lr=0.01)
        super(MyOptimizer, self).__init__(params, defaults)

    def f(self):
        print(self.state)
        print(self.defaults)
        print(self.param_groups)
```
2. Check it with mypy
3. Receive `error: Too many arguments for "__init__" of "Optimizer"`
4. PyCharm highlights all lines in method `f` as `Unresolved attribute` 

## Expected behavior

Should lint without error. Fields should resolve.

## Environment

 - PyTorch Version (e.g., 1.0): 1.1.0
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: one
 - Any other relevant information: None

**Comment by vincentqb** [comment]
Thanks for reporting this! Would you be able to submit a pull request for this?

**Comment by zerogerc** [comment]
@vincentqb there are actually a lot of bugs with typing, `Optimizer` is just an example. Should I create separate issue for each class or just submit PRs?

**Comment by vincentqb** [comment]
> @vincentqb there are actually a lot of bugs with typing, `Optimizer` is just an example. Should I create separate issue for each class or just submit PRs?

PRs are very useful for this :)

**Comment by rgommers** [comment]
The PRs linked above fix most of the problem, there was one small issue left, an attribute named `defaults` was named `default` in the stub. gh-38067 will close this.
