### ISSUE TITLE
Jetson TX2 crashes when running simple nn on GPU using libtorch

### ISSUE THREAD

**Issue by Pyrojambo** [pytorch/pytorch#23733]
## 🐛 Bug

Trying to follow the [PyTorch C++ frontend tutorial](https://pytorch.org/tutorials/advanced/cpp_frontend.html), but attempting to train the DCGAN causes the NVidia Jetson TX2 to completely crash and switch off. I am moving as much as possible to the GPU using `to(device)` and I think this may be a part of the issue as if I run the tutorial with only a subsection of the training on the CPU it does not crash, whereas it will crash on the GPU.

subsection of training loop:

```
device = torch::kCUDA;
...
  for (int64_t epoch = 1; epoch <= 1; ++epoch) {
        int64_t batch_index = 0;
        int batches_per_epoch = 938;
        for (data::Example<>& batch : *data_loader) {
            // Train discriminator with real images
            discriminator->zero_grad();
            Tensor real_images = batch.data.to(device);
            Tensor real_labels = torch::empty(batch.data.size(0)).uniform_(0.8, 1.0).to(device);
            Tensor real_output = discriminator->forward(real_images);
            Tensor d_loss_real = binary_cross_entropy(real_output, real_labels).to(device);
            d_loss_real.backward();
            ++batch_index;
        }
  }
```

## Environment

 - PyTorch Version 1.1.0
 - Ubuntu 16.04
 - Installed from source
 - Followed dusty_nv's suggestions from [this page](https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano/)
 - CUDA/cuDNN version: 9.0/7.1.5

**Comment by vincentqb** [comment]
Thanks for reporting this! Have you run into this issue on a newer version of CUDA?

**Comment by Pyrojambo** [comment]
I am currently updating the jetson so will try again with the newer version in the next day or so

**Comment by Pyrojambo** [comment]
I updated the Jetson and the same code now runs without any errors or issues.

**New environment:**
- PyTorch v1.1.0
- Ubuntu 18.04
- Installed from source by same method as above
- CUDA/cuDNN version: 10.0.326/7.5.0.56

**Comment by Pyrojambo** [comment]
So I had to downgrade the Jetson TX2 from Jetpack 4.2.1 to 4.2 in order to work with the Aetina ACE-N310 carrier board and I got the same error as before. The CUDA version is now 10.0.166 and cuDNN is 7.3.1 so I do not know if the error occurs because of the changes to the kernel by Aetina or by the older versions of CUDA and cuDNN.

To clarify, the error did not occur on:
- Jetson TX2 on official TX2 development board with Jetpack 4.2.1 (CUDA/cuDNN version: 10.0.326/7.5.0.56)

The error did occur on:
- Jetson TX2 on Aetina ACE-N310 carrier board with Jetpack 3.3 (CUDA/cuDNN version: 9.0/7.1.5)
- Jetson TX2 on Aetina ACE-N310 carrier board with Jetpack 4.2 (CUDA/cuDNN version: 10.0.166/7.3.1)

**Comment by Pyrojambo** [comment]
Ok so we worked out what the issue was: it was a hardware issue. We were using a different power supply than the one provided with the carrier board, which we think allowed it to draw too much current. Switching to the provided power supply solved the issue
