### ISSUE TITLE
Dedicated channel for PyTorch nightlies; no more munging package names

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#23742]
Today, we store both nightlies and stable releases on the channel `pytorch`. This means that you can accidentally install both at the same time, e.g., see #12031

Our new plan is to unify the package names (no more `pytorch-nightly` package), and instead upload nightly packages to another channel, https://anaconda.org/pytorch-nightly This means that if you decide to switch to nightlies, your old version of pytorch will automatically get removed.

It may take some time for pytorch nightlies to move to this channel; we will be trialing this out with torchaudio/torchvision nightlies.

cc @peterjc123 @soumith

**Comment by peterjc123** [comment]
@ezyang I'm okay with this. But we will then need to build some noarch packages in the new channel, too.

**Comment by peterjc123** [comment]
@ezyang Related code regarding Windows: https://github.com/pytorch/builder/blob/master/windows/internal/upload.bat#L82
cc @soumith for the anaconda account

**Comment by ezyang** [comment]
@peterjc123 I added you to the pytorch-nightly account

**Comment by peterjc123** [comment]
@ezyang Thanks. Please tell me if you want to switch the channel to the new one. I can also make a PR first if you want.

**Comment by ezyang** [comment]
Making a PR sounds good. Right now I'm waiting for #23752 to actually work before making the cut.

**Comment by ezyang** [comment]
We've hit one barrier here: we might not be able to get the same paid plan on `pytorch-nightly` that we have on `pytorch`. If that's the case, we'll have to figure something else out (either undo this change, or host our own Anaconda channel.)

**Comment by ezyang** [comment]
Everything is all shipped over.
