### ISSUE TITLE
Torch.Quantization: functions for determining supported modules/functionals/methods for quantized tensors

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#23750]
Quantization support is being added to pytorch via quantized modules and support for quantized operations to tensor methods. It is hard for a user to find out what is exactly supported.  Having utility functions that provide a list of supported modules/methods would be great

Example:
`torch.quantization.list_quantized_modules()`
returns [torch.nn.quantized.Conv2d ...]
`torch.quantization.list_quantized_methods()`
returns [torch.max, torch.min ...]
`torch.quantization.list_quantized_functionals()`
returns supported functionals on quantized tensors

**Comment by soumith** [comment]
wouldn't it be sufficient (and pythonic) for the user to do:

`dir(torch.nn.quantized)` and other equivalents?

**Comment by raghuramank100** [comment]
That works for nn.quantized. The issue is for torch. methods (like min/max etc), where we want to know what works for quantized tensors. 
We also have certain functionals (nn.functional) that support quantized tensors, but there is no way for the user to find out. One option is to have a alias that maps nn.functional to nn.quantized.functional so that users have a easy way to discover what is upported.

**Comment by soumith** [comment]
you can do `dir(x)` where `x` is a `QTensor`. This works as expected.

**Comment by raghuramank100** [comment]
Sounds good, I will mark this issue as closed.
