### ISSUE TITLE
Add Type Promotion for Bool types

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#23758]
## 🚀 Feature

Type promotion for ``Bool`` type when operated with other types (especially for ``Byte``).

## Motivation

The``Bool`` type has been introduced into pytorch type system, but currently they are not compatible with other types. However, before ``Bool`` becomes an independent type, many people use ``Byte`` as ``Bool``. It would cause many problems if ``Byte`` and ``Boool`` are not incompatible, which is currently the case.

## Pitch
Before type promotion, many people write something like:
```
a = torch.tensor([1], dtype=torch.uint8)
b = torch.tensor([1.0]) # whatever, does not matter
c = a & ( b < 2.0)
```
It works when comparison returns ``Byte`` type, but causes error when comparison returns ``Bool`` type:
`Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'`

## Additional context

My pytorch version (self-built) : ``acc5ced``

cc @izdeby

**Comment by vadimkantorov** [comment]
It's also convenient to be able to do `(some_int64_tensor - other_int64_tensor).mean()`, this kind of computation is frequent in accuracy metrics calculation. Currently one should explicitly cast to float() before doing mean(): `RuntimeError: Can only calculate the mean of floating types. Got Bool instead.`

**Comment by mruberry** [comment]
We now support type promotion for bool types.
