### ISSUE TITLE
 torch.nn.parallel.data_parallel crashes machine and has a weakref bug

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#23760]
## 🐛 Bug

For some reason, this happened:

```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f4b13e53158>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

## To Reproduce

```
import torch


class Model(torch.nn.Module):

    def forward(self, a):
        return a


device = torch.device('cuda')
model = Model()
model.to(device)
a = torch.randint(0, 255, (256, 900, 2), device=device)
print('`torch.nn.parallel.data_parallel`')
torch.nn.parallel.data_parallel(module=model, inputs=(a,))
```

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.9 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.15.1
[pip3] torch==1.1.0
[conda] Could not collect

**Comment by PetrochukM** [comment]
On Ubuntu 19.04 with an upgraded PyTorch version and Python version the machine just crashes with the same script.

# Environment
Collecting environment information...
PyTorch version: 1.2.0.dev20190722
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 19.04
GCC version: (Ubuntu 8.3.0-6ubuntu1) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] pytorch-nlp==0.4.1
[pip3] torch-nightly==1.2.0.dev20190722
[conda] Could not collect

**Comment by PetrochukM** [comment]
On Ubuntu 18.04 with PyTorch 1.1 this script does not error.

**Comment by pbelevich** [comment]
It's a python bug, not pytorch bug. Maybe [this one](https://bugs.python.org/issue29519). Please try newer python version.

**Comment by PetrochukM** [comment]
- By newer Python version do you mean 3.8? The Python version attempted above was 3.7. 
- Is the machine crashing also related to that Python bug? The bug does not mention the machine crashing.
- This issue affects "Creating a PyTorch Deep Learning VM" that is on the pytorch.org homepage; therefore, I feel like this issue deserves more attention.

**Comment by soumith** [comment]
wonder if we can workaround it, as we are continuing to support 3.5, 3.6, 3.7 for a bit (3.8 hasn't even been released)

**Comment by ezyang** [comment]
@gchanan comments that the mentioned Python bug is related to multiprocessing, which doesn't seem to be the case here

**Comment by pietern** [comment]
@PetrochukM I tried to repro with latest nightly but wasn't able to. This is with Python 3.6.5 from Conda.

Can you share a bigger stack trace? Or is the snippet you posted earlier the only thing you see.

**Comment by PetrochukM** [comment]
@pietern That's the only thing I saw. This is dependent on the OS that's being used. Make sure you are either running on `Debian GNU/Linux 9.9 (stretch)` or `Ubuntu 19.04`.
