### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'tuple' in torch.nn.Upsample

### ISSUE THREAD

**Issue by AlexandrosFerles** [pytorch/pytorch#23767]
## To Reproduce

```python
import torch
upsampling = torch.nn.Upsample(scale_factor=(1, 2, 2), mode='trilinear') # or any mode you like
```
 - PyTorch Version : 1.1.0
 - OS: Ubuntu 18.04
 - Pip install
 - Python version: 3.5.2

## Additional context

Issue is being claimed to be fixed in [20523](https://github.com/pytorch/pytorch/issues/20523) and [18308](https://github.com/pytorch/pytorch/issues/18308) but still exists.

**Comment by SsnL** [comment]
it's fixed on master, and will be in the upcoming release.
