### ISSUE TITLE
Senmentation falut

### ISSUE THREAD

**Issue by Peterisfar** [pytorch/pytorch#23774]
## 🐛 Bug
when i use this(see image) to test, there has a error.
![image](https://user-images.githubusercontent.com/31852119/62434652-bd7d4d00-b76b-11e9-9335-59cd56c3530e.png)

and pytorch is   "torch        1.0.0a0+db5d313" 

ps： it also happens when i test densepose to train, but torch is ok when i test data.

**Comment by SsnL** [comment]
fixed already at https://github.com/pytorch/pytorch/issues/20322

basically your index is out of range
