### ISSUE TITLE
[binaries] conda and wheel packages should not ship tests

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#23776]
Currently, unpacking a conda tar.bz2 nightly file shows that we are shipping several test binaries, probably because of a cmake misconfiguration. We should not be shipping these -- in fact we should not be `INSTALL`ing these files in relevant cmake.

Relevant folders / files being shipped (reported sizes are uncompressed):
- site-packages/torch/test (88.4MiB)
- site-packages/caffe2/python/operator_test (2.9MiB)
- site-packages/torch/bin/test_api (5.7 MiB)
- site-packages/torch/bin/protoc (4.1 MiB)
- site-packages/torch/bin/test_jit (2.1 MiB)

**Comment by soumith** [comment]
verified that this also affects wheels. brings down the compressed wheel size from 706MB to 676MB after removing these files / folders and re-compressing.

**Comment by gchanan** [comment]
shall we close this?

**Comment by soumith** [comment]
yes, thanks.

**Comment by peterjc123** [comment]
This is not done in Windows builds.
