### ISSUE TITLE
conda installs CPU only version of pytorch-nightly during new package uploads (CPU and win64 are uploaded first)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#23778]
My machine has GPU, but by default conda wants to install a CPU only version.

I'm using the command recommended at pytorch.org:
```
conda install pytorch-nightly cudatoolkit=10.0 -c pytorch

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /miniconda

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch-nightly


The following NEW packages will be INSTALLED:

  cpu-only           pytorch/linux-64::cpu-only-1.0-0
  pytorch-nightly    pytorch/linux-64::pytorch-nightly-1.2.0.dev20190805+cpu-py3.7_cpu_0

```

**Comment by vadimkantorov** [comment]
It seems I tried to install at an unfortunate exact moment when the new packages are being uploaded :)  So only CPU-only new package is available.

**Comment by calincru** [comment]
Not sure if it's related, but does anyone know why the [CPU nightly build for Linux](https://anaconda.org/pytorch/pytorch-nightly-cpu) has **not** been updated in almost one week?  (The latest one is from 31st of July.)

**Comment by vadimkantorov** [comment]
(as a side note, there are CPU-only nightlies here: https://anaconda.org/pytorch/pytorch-nightly/files - exactly they caused my mis-install :) )

**Comment by ezyang** [comment]
We recently made a change to packaging of CPU nightlies to put them in `pytorch-nightly` rather than `pytorch-nightly-cpu`. But it looks like the feature selection scheme we're using is insufficient.

**Comment by ezyang** [comment]
It seems that we forgot to actually put `feature` field in the nightly meta.yaml.

**Comment by vadimkantorov** [comment]
@ezyang Do you know if conda supports explicitly requesting the CUDA/CPU feature? Even if it can be done implicitly, it wouldn't hurt to have it in the recommended install command, users will better understand what's happening.

**Comment by ezyang** [comment]
Yes, you're supposed to request the feature using `conda install cpu-only -c pytorch`. Conda isn't supposed to drag in a feature automatically as part of dependency resolution; this might also be because I messed up and declared a dependency on the feature package which maybe I'm not supposed to do? I need to read the docs some more and do some testing.

Apologies about the broken nightlies; if I can't figure out how to fix it today I'll revert all the changes. (There's other trouble too: the new `pytorch-nightly` channel isn't going to have enough disk space...)

**Comment by calincru** [comment]
@ezyang Any updates?  I've been waiting for the nightly release for CPU/Linux-64 for a week now.

**Comment by ezyang** [comment]
@calincru The new nightly channel at https://anaconda.org/pytorch-nightly/pytorch should be fully operational. Please let me know if things don't work.

FYI the cpu-only package was renamed to cpuonly.

**Comment by ezyang** [comment]
We did a bit of testing in 1.2.0 release today and I think everything is good.
