### ISSUE TITLE
Torch hub does not check dependencies before importing attributes

### ISSUE THREAD

**Issue by willprice** [pytorch/pytorch#23781]
## To Reproduce

Ensure `tqdm` is not installed in your environment, verify that `python -c 'import tqdm'` **raises an exception.**

```python
import torch
torch.hub.load('willprice/pytorch-hub-bug', 'entry_point')
```
([repo here](https://github.com/willprice/pytorch-hub-bug))
This errors with 

```
Using cache found in /home/will/.cache/torch/hub/willprice_pytorch-hub-bug_master
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/usr/lib/python3.7/site-packages/torch/hub.py", line 70, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/will/.cache/torch/hub/willprice_pytorch-hub-bug_master/hubconf.py", line 3, in <module>
    from entry import entry_point
  File "/home/will/.cache/torch/hub/willprice_pytorch-hub-bug_master/entry.py", line 1, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

## Expected behavior
I'd expect `torch` to raise an exception saying a dependency isn't installed, rather than an `ImportError`.

I would expect `torch.hub.load` to check `dependencies` in `hubconf.py` before executing `hubconf.py` and actually loading in the entrypoints. It's not clear from examples of `hubconf.py` that to avoid this behaviour you'd have to wrap all your entrypoints in functions that import the dependencies within the function body and not at the top level. This is a pain as it involves adding a wrapper for every entrypoint and duplicating all the docstrings.

## Suggested fix

Rather than evaluating the module, it'd make more sense to pull out the AST node corresponding to the `dependencies` variable and evaluate that only, perform the dependency check and only then import the full module. It might be that people have complicated `hubconf.py` files that prevent this from happening. In that case things get a bit more tricky and it might make sense to fallback on the current implementation as at least the user still gets ImportError exceptions that are *useful* if not the most user friendly.

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Arch Linux
GCC version: (GCC) 9.1.0
CMake version: version 3.15.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.1.168
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.4
[pip3] pytorch-ignite==0.1.2
[pip3] torch==1.1.0
[pip3] torchaudio==0.2
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.2.1
[pip3] torchviz==0.0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py36ha843d7b_0
[conda] mkl_random                1.0.2            py36hd81dba3_0
[conda] pytorch-cpu               1.1.0               py3.6_cpu_0    pytorch
[conda] torchvision-cpu           0.3.0             py36_cuNone_1    pytorch
```

**Comment by ailzhang** [comment]
Hi @willprice, sorry for the late reply! The issue was indeed documented here https://github.com/pytorch/pytorch/blob/master/torch/hub.py#L235, and I left it there since python error message is clear enough that user need to install that module as dependency. 
As you said in the suggested fix, it has some tricky part even if we try to handle it. I might prefer to leave it as it is as usually importing a module means it's required. 
I'll close this issue for now, please feel free to reopen if there're use cases that `RuntimeError` is preferred over `ImportError`. Thanks!
