### ISSUE TITLE
Error message for wrong weight_decay type in optimizer is not clear

### ISSUE THREAD

**Issue by cdancette** [pytorch/pytorch#23785]
## 🐛 Bug

The error message when feeding a string instead of a float for the weight_decay parameter of Adam and Amadax (and maybe others) is not clear: 

    File "optimizers/lr_scheduler.py", line 124, in step
      self.optimizer.step()
    File "miniconda3/envs/murel/lib/python3.7/site-packages/torch/optim/adam.py", line 90, in step
      grad.add_(group['weight_decay'], p.data)
    TypeError: add_() takes 1 positional argument but 2 were given

Something like  `weight_decay: expected type float, got string` would be easier to debug.

## To Reproduce

Feed a string instead of a float for the weight_decay parameter of an optimizer (I tried Adam, and Adamax).

## Environment

pytorch 1.1

**Comment by pbelevich** [comment]
The documentation clearly states that weight_decay must be float, not a string
