### ISSUE TITLE
[Doc] Tensor.add_() includes an optional multiplication 

### ISSUE THREAD

**Issue by madsbk** [pytorch/pytorch#23786]
## 📚 Documentation
The documentation of [`Tensor.add_()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.add_) says that it is an in-place version of `add()`, which in turn refer to [`torch.add()`](https://pytorch.org/docs/stable/torch.html#torch.add). However, at no place does it say that the result is scaled by an optional second argument.
That is `a.add_(10,b)` equals `a += 10 * b` where `a` and `b` are tensors.

**Comment by SsnL** [comment]
https://pytorch.org/docs/stable/torch.html#torch.add has two variants, one of which does what you described.

**Comment by pbelevich** [comment]
I close this issue based on @SsnL answer. @madsbk feel free to reopen it if you disagree.
