### ISSUE TITLE
when i convert model to onnx, I got this "RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int"

### ISSUE THREAD

**Issue by guijiyang** [pytorch/pytorch#23783]
`image_input=torch.randn(10, 3, 512, 512).to(device)
style_id=[random.randint(0,27)]
dummy_input = (image_input, style_id)

torch.onnx.export(model,
                  dummy_input,
                  'stylebank.onnx',
                  verbose=True,
                  input_names=input_names,
                  output_names=output_names)`
what can i do?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
