### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#23795]
Redux of #2. At some point, we should drop Python 2 support. Python 2 is EOL'ed (2020), [surveys](https://www.jetbrains.com/research/python-developers-survey-2018/) suggest that Python 2 usage is approaching single digits in the near future (if this has not happened already).

In my opinion, two major features in Python 3 which would greatly benefit PyTorch:
* Native type hint syntax
* Async/await

Possible timelines:
* Stop supporting Python 2 immediately after 1.2 release (this is unlikely to happen)
* Stop supporting Python 2 in PyTorch at the same time Python 2 is EOL'ed (beginning of 2020)
* Continue to support Python 2 for some indefinite period of time after 2020 EOL, until we see that Python 2 usage has dropped sufficiently for us to drop it

**Comment by SsnL** [comment]
also `concurrent.futures` maybe useful for data loading.

**Comment by hugovk** [comment]
https://python3statement.org shows projects which have pledged to drop Python 2 support in or before 2020.

[This](https://hugovk.github.io/drop-python/2.7/) shows popular projects which have already dropped Python 2 in their current releases, like NumPy, pandas, pytest, scipy, scikit-learn and matplotlib.

Here's how a couple of those planned it:

* https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html
* https://docs.pytest.org/en/latest/py27-py34-deprecation.html

**Comment by Balandat** [comment]
Strongly support doing this sooner rather than later.

We have (shameless plug!) a 100% native py3-typed codebase for BoTorch (https://github.com/pytorch/botorch), which greatly improves dev efficiency in the long term.

async/await would be great, too. Also, `enum, `NamedTuple`, and dataclasses to make things more elegant overall. 

And, of course, any new features to be added in the future....

**Comment by soumith** [comment]
our official previous stance was (3), i.e.:

> Continue to support Python 2 for some indefinite period of time after 2020 EOL, until we see that Python 2 usage has dropped sufficiently for us to drop it

I don't see a better pragmatic stance. Are we going to drop Python2 support under the rug of people using it?

**Comment by hugovk** [comment]
> ... until we see that Python 2 usage has dropped sufficiently for us to drop it

What sort of threshold did you have in mind?

**Comment by ezyang** [comment]
My secret hope is that when EOL happens there won't actually be anyone we care about using Python 2 and we can drop it :) (thereby making plan 3 and plan 2 equivalent)

**Comment by zhangguanheng66** [comment]
The domain libraries have to make same decision as the core library. @cpuhrsch @vincentqb @fmassa

**Comment by vincentqb** [comment]
Option 3 is risky since there is no clear end of support, and there would always be one user that would be surprised by the drop of python 2. I'd like to drop as soon as possible, but I understand we need to warn users ahead of time, as @soumith mentioned.

I'd vote for option 2: stop supporting python 2 for versions on or after January 1st 2020. That time is not a surprise for anyone so we wouldn't be pulling the rug under anyone.

Do we have a commitment about how long we support previous version of pytorch?

**Comment by soumith** [comment]
our previously determined hand-waved threshold was 10%. If we have < 10% of downloads from Python-2 users, we drop support.

**Comment by hugovk** [comment]
Here's the pip installs for pytorch from PyPI for July 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 3        |  89.58% |    31,860 |
| 2        |   8.11% |     2,885 |
| null     |   2.30% |       819 |
| Total    |         |    35,564 |

Source: `pip install -U pypistats && pypistats python_major pytorch --last-month`

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  40.25% |    14,315 |
| 3.7      |  40.08% |    14,254 |
| 3.5      |   8.83% |     3,142 |
| 2.7      |   8.10% |     2,881 |
| null     |   2.30% |       819 |
| 3.4      |   0.38% |       135 |
| 3.8      |   0.03% |        11 |
| 2.6      |   0.01% |         4 |
| 3.9      |   0.01% |         2 |
| 3.3      |   0.00% |         1 |
| Total    |         |    35,564 |

Source: `pip install -U pypistats && pypistats python_minor pytorch --last-month`

**Comment by fmassa** [comment]
@zhangguanheng66 my take on this: domain libraries should support Python2 for as long as PyTorch support Python2

**Comment by vincentqb** [comment]
> @zhangguanheng66 my take on this: domain libraries should support Python2 for as long as PyTorch support Python2

I second that.

**Comment by zhangguanheng66** [comment]
@fmassa @vincentqb I just check the download for torchtext. There are slightly more than 10% download from python2 so I guess we should continue the support for now.

**Comment by hugovk** [comment]
pip installs for torchtext from PyPI for July 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 3        |  89.27% |    22,056 |
| 2        |  10.11% |     2,498 |
| null     |   0.62% |       152 |
| Total    |         |    24,706 |

Source: `pypistats python_major torchtext --last-month`

For August so far:

| category | percent | downloads |
|----------|--------:|----------:|
| 3        |  90.17% |    10,076 |
| 2        |   9.09% |     1,016 |
| null     |   0.73% |        82 |
| Total    |         |    11,174 |

Source: `pypistats python_major torchtext --last-month`

**Comment by ezyang** [comment]
Well, if 10% is the bar, looks like we're on track to drop support in 2020 :)

**Comment by VitalyFedyunin** [comment]
Most of the team members vote for "Stop supporting Python 2 in PyTorch at the same time Python 2 is EOL'ed (beginning of 2020)"

**Comment by vincentqb** [comment]
Python 2.7 EOL: [January 1st, 2020](https://github.com/python/devguide/pull/344)

**Comment by pritamdamania87** [comment]
It seems like the consensus here is to drop support in 2020, if so should we communicate this more widely to users? We could also add some warning messages when you `import torch` using Python2, that Python2 support will be dropped in 2020.

**Comment by Balandat** [comment]
Communicating would be good, I don't think we need to worry too much about warning that py2 support will be dropped - after all python itself is dropping support...

**Comment by hugovk** [comment]
Some ideas:
* Put it on the README
* Pin this issue
* Post in the forums, Slack and newsletter
* Sign https://python3statement.org

**Comment by soumith** [comment]
Based on the conclusion of this thread, I've sent a PR to sign python3 statement at: https://github.com/python3statement/python3statement.github.io/pull/264

**Comment by soumith** [comment]
posted on the forums and slack.

**Comment by tacaswell** [comment]
Apologies for crashing in from the :peanuts: gallery.

One thing that is important to note in these discussions is that I have never seen anyone propose to pull down the existing py2 artifacts so python2 users can continue at the status quo forever.  The question is will py2 users be able to get the _latest_ version of pytorch.

I suspect pypi numbers are going to over-estimate your py2 usage as CI of down-stream projects can provide a significant load (this is particularly true for Matplotlib).

While you are thinking about policy around dropping support for Python versions, I suggest you have a look at https://numpy.org/neps/nep-0029-deprecation_policy.html .

**Comment by soumith** [comment]
> The question is will py2 users be able to get the latest version of pytorch.

Not the latest, but the last version that is released before Py2 support is gone. So if 1.4 is released in December 2019, it'll be available for Py2 users for as long as we host binaries.

**Comment by hugovk** [comment]
Yep, and using `python_requires` in `setup.py` will help pip only install the supported library version for the user's running Python.

**Comment by zou3519** [comment]
Something else that dropping Python 2 would help us do is to change our default division behavior that currently follows Python 2.

In Python 2, `5/ 3` gives 1, but in Python 3, `5 / 3` gives 1.666. Integer Tensor division currently follows the Python 2 semantics but as we move off of Python 2 it makes more sense for it to follow Python 3 semantics. https://github.com/pytorch/pytorch/issues/5411

**Comment by awcchungster** [comment]
Since PyTorch we're right around the holidays, and 1.4 is not out yet, should we expect a Jan 1.4 release without Py2 support?

**Comment by ezyang** [comment]
No, 1.4 is going to support Python 2, because we branch cut before the Python 2 EOL

**Comment by xuhdev** [comment]
Just to confirm: New code on the master branch won't support Python 2 anymore, right?

**Comment by soumith** [comment]
correct

**Comment by Balandat** [comment]
I assume we're shebanging it then? I.e. add `#!/usr/bin/env python3` to new code.

**Comment by gchanan** [comment]
Just to clarify:
There are still some internal FB usages of python 2, and our tests still run python 2, so new code on master (as of now) needs to support python 2.  Hopefully that will go away soon, and we are not guaranteeing that PyTorch 1.5 supports Python 2.

@Balandat by "we're" do you mean the PyTorch project?  I don't really see why we need to shebang library code (standalone scripts like the test runner, okay), but maybe I'm missing something.

**Comment by Balandat** [comment]
@gchanan Shebanging mostly for signaling purposes. To the user for one, but more importantly to linters so they know how to lint (and not suggest stuff like `from future` imports etc.).

**Comment by ezyang** [comment]
@Balandat Actually we can cut everything over to Python 3 linting in Facebook without having to shebang everything; we just need to replace the `.python2` in the top level directory with `.python3`

**Comment by ezyang** [comment]
We're here!!
