### ISSUE TITLE
max_pool2d_with_indices_cuda and max_pool2d_with_indices_backward_cuda should have channel last optimized kernels.

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#23815]
max_pool2d_with_indices_cuda and max_pool2d_with_indices_backward_cuda should have channel last optimized kernels ( for https://github.com/pytorch/pytorch/pull/24872 )

**Comment by ifedan** [comment]
https://github.com/pytorch/pytorch/pull/24872
