### ISSUE TITLE
Weird result for inplace operation for a tensor with itself

### ISSUE THREAD

**Issue by poltronSuperstar** [pytorch/pytorch#23812]
While [7494](https://github.com/pytorch/pytorch/issues/7484) and [906](https://github.com/pytorch/pytorch/issues/906) both describe behaviors that might surprise, it seems to be the ones expected.

However this really looks like a bug to me, if not, I'm really curious of an explanation:

```
>>> import torch
>>> a = torch.arange(20)
>>> a[1:].sub(a[:-1]) # Achieve the same thing as numpy.diff
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
>>> a[1:].sub_(a[:-1])
tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  8,  1,  1,  1,  1,  1,  1,  1, 16,  2, 17])
```

**Comment by SsnL** [comment]
Likely a race among threads. You are reading and writing into the same locations, and the op is not pointwise. As there is no guard against this behavior currently implemented in PyTorch, this could happen.

**Comment by poltronSuperstar** [comment]
My guess was along those lines. Trivial to avoid once figured out but I can easily imagine loosing hours because of this behavior. IMHO this should at least raise a warning.

**Comment by pbelevich** [comment]
duplicate of #8212

**Comment by poltronSuperstar** [comment]
Indeed, I missed it, sorry about that.
