### ISSUE TITLE
pytorch cannot be installed under Windows 10 if Python 3.7 was installed from Microsoft Store

### ISSUE THREAD

**Issue by JonasHeidelberg** [pytorch/pytorch#23823]
## Issue description

pytorch 1.1.0 cannot be installed under Windows 10 if Python 3.7 was installed from Microsoft Store.

The reason is a combination of
a) long Python installation path used by Microsoft Store installer
b) long filename path used within pytorch for collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip
c) by default, Windows 10 still refuses paths longer than 256 characters

## Code example

`pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-win_amd64.whl`
fails with an error message:

> `ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\[username]\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'`

The error is caused by the 256 character limit on Windows paths. With a file and pathname so long, no matter how short <username> is the path is 257 characters or longer.

## System Info
PyTorch version: 1.1.0
OS: Microsoft Windows 10 Pro, Version 1903 
Python version: 3.7

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0

**Comment by JonasHeidelberg** [comment]
I am not the first or only one to have this problem, see https://www.reddit.com/r/pytorch/comments/c6cllq/issue_installing_pytorch/ .
A workaround is to tell Windows to accept long paths. However, this requires people to search for the error message online and find this. A more convenient solution implementable in pytorch could be to simply rename the collect_and_distribute_fpn_rpn_proposals_op_test.py file to something shorter? I know this only reduces the problem a little, since users with long usernames can still run into such a problem. 

A more clean solution would be to have whichever tool fails to unpack that file throw a more meaningful error. Just some thoughts...

**Comment by iofu728** [comment]
This problem also occurs in my Windows OS 18965.1005.

**Comment by peterjc123** [comment]
Upstream issue: https://bugs.python.org/issue18199
They rejected the idea to add the prefix "\\?\" to the path to extend the MAX_PATH to 65536. So you'll need to get in the registry route.

**Comment by JonasHeidelberg** [comment]
Okay, so for anyone else looking for the workaround: In the Windows Registry, within HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem you have to set LongPathsEnabled to 1 and reboot.

**Comment by verdelyi** [comment]
Actually I didn't even have to reboot (Version 1909 build 18363.1082)

**Comment by angrypop** [comment]
The registry works and a reboot is not necessary.
Btw, I found an alternate solution: change your Windows user name to 1 single character, which makes the path length exactly 256 chars

**Comment by Waffle1434** [comment]
Issue is still present
