### ISSUE TITLE
Problem with pip installation on Ubuntu 14.04 

### ISSUE THREAD

**Issue by saeedizadi** [pytorch/pytorch#2382]
Hi, 
The newset version of pytorch is not working with wheel and pip on ubuntu 14.04 and cuda 7.5. The following error occurs:

torch-0.2.0.post1-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.

Thanks
-Saeed

**Comment by CDLuminate** [comment]
Are you installing with python2 pip? Installing the whl package with a wrong pip may produce the same error message.

```
pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by killeent** [comment]
Although installation is likely not going to work on ubuntu without the `LD_PRELOAD` workaround (see #2314), you may want to try the other of the two links provided on pytorch.org, i.e.:

pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl

**Comment by prajjwal1** [comment]
Install pytorch thorugh pip3
``
sudo pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl 
``
I tried this one as installation through pip was giving me errors. I am using Ubuntu 16.04 LTS.
Installation through pip3 works perfectly. You'll will have to run it as root
>Collecting torch==0.2.0.post1 from http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl
  Downloading http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl (340.4MB)
    100% |████████████████████████████████| 340.4MB 3.4MB/s 
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from torch==0.2.0.post1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.5/dist-packages (from torch==0.2.0.post1)
Installing collected packages: torch
Successfully installed torch-0.2.0.post1

**Comment by prajjwal1** [comment]
Similarly with torchvision use this
``
$ sudo pip3 install torchvision
``
Output:
>Collecting torchvision
  Downloading torchvision-0.1.9-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 517kB/s 
Requirement already satisfied: six in ./.local/lib/python3.5/site-packages (from torchvision)
Requirement already satisfied: numpy in ./.local/lib/python3.5/site-packages (from torchvision)
Requirement already satisfied: torch in /usr/local/lib/python3.5/dist-packages (from torchvision)
Requirement already satisfied: pillow in /usr/local/lib/python3.5/dist-packages (from torchvision)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.5/dist-packages (from torch->torchvision)
Requirement already satisfied: olefile in /usr/local/lib/python3.5/dist-packages (from pillow->torchvision)
Installing collected packages: torchvision
Successfully installed torchvision-0.1.9

**Comment by saeedizadi** [comment]
The problem still exists. 
pip --version 
pip 8.1.2

CUDA 8 available. on centOS

**Comment by saeedizadi** [comment]
BTW, i'm on centos. Does it make difference?

**Comment by ZmeiGorynych** [comment]
Failed for me on Ubuntu 16.04 using pip3 as suggested above: 
```
(pytorch) udacity@ip-172-31-40-130:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
(...)
(pytorch) udacity@ip-172-31-40-130:~$ sudo /home/carnd/anaconda3/bin/pip3 install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
The directory '/home/carnd/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/carnd/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
(pytorch) udacity@ip-172-31-40-130:~$
```
Install worked using conda however,
`conda install pytorch torchvision cuda80 -c soumith`

**Comment by gchanan** [comment]
Closing this issue as it is sufficiently outdated.
