### ISSUE TITLE
explicit logical operators

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#23836]
We should have logical operators equivalent to NumPy:

https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_and.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_or.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_xor.html

Most critical are `logical_not` and `logical_xor`, because are current error messages for bool are strange because we only have bitwise_not (which sort of implies our bools are 1-bit, but that's not correct).  For example:

```
>>> np.array(True) - np.array(False)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

>>> -np.array(False)
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

>>> torch.tensor(True) - torch.tensor(False)
RuntimeError: Subtraction, the `-` operator, with two bool tensors is not supported. Use the `^` operator instead.

>>> -torch.tensor(False)
RuntimeError: Negation, the `-` operator, on a bool tensor is not supported. 
                        If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead."
```

**Comment by gchanan** [comment]
@xuhdev I put you in the assignee field based on your comments in https://github.com/pytorch/pytorch/pull/23621.

When do you think you can get to `logical_not` and `logical_xor`?  I'd preferably like to get them into the release, so if it's not going to be tomorrow LMK and I'll have someone over here do it.

**Comment by xuhdev** [comment]
I should be able to do it before end of tomorrow

**Comment by gchanan** [comment]
punting out of 1.2.
