### ISSUE TITLE
Tensor for argument #2 is on CPU, but expected it to be on GPU

### ISSUE THREAD

**Issue by CharlesWu123** [pytorch/pytorch#23853]
![Screenshot from 2019-08-06 10-03-44](https://user-images.githubusercontent.com/38948322/62506174-27f8c080-b832-11e9-8852-c95f19bc910b.png)

I know this is because some parameters are not caused by the GPU, I also checked my code and found no problems. I can't find any answer to this question online.I hope someone who has the same problem can help give a suggestion.

 - PyTorch Version (1.1.0):
 - OS (Linux, CentOS):
 - How you installed PyTorch (pip):
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0
 - GPU models and configuration: Tesla P100

**Comment by syborg91** [comment]
Expected a `.cuda` variant but instead got cpu. Try adding `.cuda()` with the tensor passed in the 2nd argument.

**Comment by CharlesWu123** [comment]
I have tried it, so I will report another error.

![Screenshot from 2019-08-05 19-27-19](https://user-images.githubusercontent.com/38948322/62513763-b3cd1580-b84f-11e9-9b7c-0574480deb30.png)

**Comment by ailzhang** [comment]
@CharlesWu123  I'd recommend using pdb to figure out which tensor is on the wrong device. 
Btw forum is a better place for questions, if you are reporting a bug, please feel free to reopen with a reproducible script. Thanks!

**Comment by imkhoa99** [comment]
> @CharlesWu123 I'd recommend using pdb to figure out which tensor is on the wrong device.
> Btw forum is a better place for questions, if you are reporting a bug, please feel free to reopen with a reproducible script. Thanks!

I tried to look for information on how to use pdb to figure out which tensor is on the wrong device, but I could not find relevant information. Could you help me where should I look into?
