### ISSUE TITLE
error using EmbeddingBag in 2D, got RuntimeError: expected a Variable argument, but got torch.LongTensor. 

### ISSUE THREAD

**Issue by nesciemus** [pytorch/pytorch#2385]
my code:
embedding_sum = nn.EmbeddingBag(10, 3, mode='sum')
input = autograd.Variable(torch.LongTensor([[1,2,4,5],[4,3,2,9]]))
embedding_sum(input)

my version is '0.2.0_1'
did I do sth wrong?

**Comment by ajfisch** [comment]
I think that this should be wrapped in a Variable: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/sparse.py#L201

**Comment by soumith** [comment]
@ajfisch you're right. can you send a PR to fix this, I'll merge.

**Comment by shawnjhenry** [comment]
Wrapping that tensor in a variable isn't sufficient to fix the problem.  I tried that and get the error: 

```
  File "//anaconda/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 212, in forward
    )(self.weight, input, offsets)
  File "//anaconda/lib/python3.6/site-packages/torch/nn/_functions/thnn/sparse.py", line 147, in forward
    assert indices.dim() == 1
AssertionError
```

**Comment by soumith** [comment]
@shawnjhenry yes, additionally you need `input = input.view(-1)`. PR#2429 fixes this in master. thanks @ajfisch !
