### ISSUE TITLE
exception: C10::Error at memory location

### ISSUE THREAD

**Issue by WeiChihChern** [pytorch/pytorch#23868]
## 🐛 Bug

After training an simple model successfully using libtorch C++ and saved as a .pt file.   Loading the model and trying to test the model with an input tensor gave me c10 error.

## To Reproduce

1. Used `torch::save() `to save a trained model
1. Used OpenCV 4.0.1 to load an image, resize it, convert it to tensor using `torch::from_blob`
1. Create my model object `ConvNet model(image.channels(), image.rows, image.cols);` then using `torch::load(model, save_model.pt)` to load the saved model. Loading model and tensor on either gpu or cpu is fine, but when forward the tensor, it gave me error during the first convolution in my model's forward process.

** I found out the problem happened after calling the first convolution process in my model's forward process.  Wondering could it be due to the difference between tensor's dimension? I didn't expend another dimension during training process, but according to what i see here seems like we will expend another dimension, then feed in to the model. 

**Update: I used a docker container which includes both built from source libtorch and opencv, which doesn't gave me the error in Windows.  Also, how come the built from source libtorch in ubuntu gave me detailed error information than in Windows.  Did I accidentally built libtorch as debug?

How I prepare input data for training:
```
torch::data::Example<> get(size_t index) override {

    string  file_location = std::get<0>(csv_[index]);
    int64_t label         = std::get<1>(csv_[index]);

    // Load image with OpenCV.
    cv::Mat img = cv::imread(file_location, (channels==3) ? 1 : 0);
    CV_Assert(!img.empty());
    resize(img, img, Size(image_col, image_row));

    torch::Tensor img_tensor = torch::from_blob(img.data, {img.rows, img.cols, 
    img.channels()},torch::kByte);
    img_tensor   = ((img_tensor.to(kFloat)) / 255);
    img_tensor   = img_tensor.permute({2, 0, 1}); // convert to CxHxW

    torch::Tensor label_tensor = torch::full({1}, label);
    label_tensor = label_tensor.to(kInt64);

    return {img_tensor, label_tensor};
}
```

How I trying to test my model:
```
void method2(cv::Mat &image, const string& model_loc) {
	torch::Tensor img_tensor = torch::from_blob(image.data, { 1, image.rows, image.cols, 3 }, torch::kByte);
	cout << "from blob ended\n";
	img_tensor = img_tensor.permute({ 0, 3, 1, 2 });
	img_tensor = img_tensor.toType(torch::kFloat);
	img_tensor = img_tensor.div(255).to(at::kCPU);
	cout << "method2: tensor to gpu\n";

	ConvNet model(image.channels(), image.rows, image.cols);
	model->to(at::kCPU);
	torch::load(model, model_loc);
	cout << "method2: model to gpu\n";

	model(img_tensor);
	cout << "method2: ended\n";
}
```

How my model were defined:

```
struct ConvNetImpl : public torch::nn::Module 
{
    ConvNetImpl(int64_t channels, int height, int width) : 
	  conv1(torch::nn::Conv2dOptions(channels, 6, 3).stride(1)),
          conv2(torch::nn::Conv2dOptions(6, 27, 3).stride(1)),
          n(GetConvOutput(channels, height, width)),
          fc1(n, 32),
          fc2(32, 2) /*number of output classes*/ 
	{
        register_module("conv1", conv1);
        register_module("conv2", conv2);
        register_module("lin1", fc1);
        register_module("lin2", fc2);
    };

    // Implement the forward method.
    torch::Tensor forward(torch::Tensor x) 
	{
	cout << "1\n";
        x = torch::relu(torch::max_pool2d(conv1(x), 2));  /* Where the c10 error happened according to the couts*/
	cout << "2\n";
        x = torch::relu(torch::max_pool2d(conv2(x), 2));
	printf("tesor size = %d", x.numel());
	cout << "b4 flatten\n";
        x = x.view({-1, n}); // Flatten.
	cout << "aft flatten\n";
        x = torch::relu(fc1(x));
	x = torch::dropout(x, 0.2, is_training());
	x = torch::log_softmax(fc2(x), 1/*dim*/);
        return x;
    };

    // Get number of elements of output.
    int64_t GetConvOutput(int64_t channels, int64_t height, int64_t width) 
	{
        torch::Tensor x = torch::zeros({1, channels, height, width});
        x = torch::max_pool2d(conv1(x), 2);
        x = torch::max_pool2d(conv2(x), 2);

		int size = x.numel();
		cout << "Flatten neuron size: " << size << "\n";
		return size;
    }

    torch::nn::Conv2d conv1, conv2;
    int64_t n;
    torch::nn::Linear fc1, fc2;
	torch::nn::Dropout dropout1;
};

TORCH_MODULE(ConvNet);
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: 
CMake version: version 3.15.0-rc3

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 431.70
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

**Comment by WeiChihChern** [comment]
incorrect saving method were performed on my python end.  Loading on libtorch has no problem now on prebuilt release libtorch 1.2

**Comment by bigbigbigball** [comment]
> @yf225 incorrect saving method were performed on my python end. Loading in libtorch has no problem now on prebuilt release libtorch 1.2.
I got a similar problem, enviroment libtorch 1.6 cpu version ,window 10 VS2017, Loading the model and trying to test the model (model.forward) give me the C10::Error at memory location ,How can I solve this problem? THANK YOU!

**Comment by ZhangHongYang-zhy** [comment]
> > @yf225 incorrect saving method were performed on my python end. Loading in libtorch has no problem now on prebuilt release libtorch 1.2.
> > I got a similar problem, enviroment libtorch 1.6 cpu version ,window 10 VS2017, Loading the model and trying to test the model (model.forward) give me the C10::Error at memory location ,How can I solve this problem? THANK YOU!

I have the same problem，also want to know the specific resolution details.THANKS!

**Comment by saldanhag** [comment]
I have the same problem, can i have the specifics of the resolution pliz
