### ISSUE TITLE
Improved error reporting for torch.quantization.convert()

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#23875]
Currently, torch.quantization.convert() calls swap_module() which reports an error when a module is not converted. This message does not say which module in the model is failing, it only reports the module type (i.e conv2d). This is hard to localize as a network may have 100s of convs. Request is to report the name of the module that is failing conversion.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jerryzh168** [comment]
cc @z-a-f can you add this error message
