### ISSUE TITLE
Likely missing super(...).__init__(...) call in torch.nn._intrinsic.modules.fused.ConvBnReLU2d

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#23870]
All other stub classes there have a super() call to delegate the work to nn.Sequential except this one: 
https://github.com/pytorch/pytorch/blob/master/torch/nn/_intrinsic/modules/fused.py#L23

Also this probably means that this ConvBnReLU2d is not on any test path

**Comment by jerryzh168** [comment]
will fix

**Comment by vadimkantorov** [comment]
The fix in https://github.com/pytorch/pytorch/pull/23753 was merged a few days ago
