### ISSUE TITLE
interfaces of many schedulers in lr_scheduler.py are missing in lr_scheduler.pyi

### ISSUE THREAD

**Issue by maaft** [pytorch/pytorch#23876]
## 🐛 Bug

Most interfaces of schedulers defined in lr_scheduler.py are missing in lr_scheduler.pyi. This makes importing them impossible in 1.1.

**Comment by ezyang** [comment]
Err, not impossible to import, just not typechecked, no? (We will happily accept patches that add the missing LR schedulers.)

**Comment by tczhangzhi** [comment]
I checked the lr_scheduler.pyi file and only found the missing type checking for two classes. I have submitted a PR #23934 . If you find other files in which there is a missing type check, I am willing to help.

**Comment by maaft** [comment]
> Err, not impossible to import, just not typechecked, no? (We will happily accept patches that add the missing LR schedulers.)

Yep, you're absolutely right. I never ran the code and just relied on PyCharms typechecked imports instead which were showing an error. Issue closed, sorry again.
