### ISSUE TITLE
Quantized conv2d: Numerics do not match expected output

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#23874]
quantized conv2d outputs do not match expected output. This can be reproduced by using the following test input (to be added later today). The error is not with the quantization of weights/packing or quantization of activations. It is also not a LSB mismatch. This is currently blocking work on measuring accuracy of quantized models.

Repro:
 To be added

**Comment by raghuramank100** [comment]
Repro test case has been generated by logging vectors for conv2d module within resnext 101.

**Comment by jerryzh168** [comment]
this is resolved? we discovered it's because of an observer bug

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/issues/23838

**Comment by raghuramank100** [comment]
No, its not. The issue is how the bias is quantized. The bias is quantized based on the output_scale*wt_scale, which is incorrect. The problem is that we do not have the input scale known at model conversion. For eager mode, the input tensor scale can change from run to run and we are proposing handling that by quantizing the bias with 2^16 * output_scale. This will require changes to the requantization method within FBGEMM

**Comment by hongzhen1** [comment]
Hi, @jerryzh168 @raghuramank100, @jgong5 . we also find this correctness issue  for bias quantization. how about  keep bias as float32 in from_float() and do one time quantize in forward function to keep better accuracy. we have one complete PR for this, including modification for qconv, qlinear and nniq(conv_relu/linear_relu), but seems conflict with your modification.

**Comment by raghuramank100** [comment]
This is not solved in the release 1.3 code. We keep bias in float32 and quantize it for every forward call in eager mode. We can cache the quantized value as a later optimization. Does this address your concern @hongzhen1

**Comment by hongzhen1** [comment]
@raghuramank100 LGTM, thanks
