### ISSUE TITLE
how can i find the 0.12.post2 wheel file for fresh installation?

### ISSUE THREAD

**Issue by galactica147** [pytorch/pytorch#2387]
Anyone knows how to find a previous version wheel file for a fresh installation. I tried the latest 0.20 but it didn't work with my code, i.e., setting CUDA_VISIBLE_DEVICES in the code seems not work any more, because all jobs are cluttered on GPU 0 instead of specified ones. 

Please advise 1). how to find the previous wheel file 2). alternatively how to change the GPU ID settings to make parallel jobs work. 

Thanks!

**Comment by killeent** [comment]
@galactica147 can you be more specific about the error you are encountering on v0.2.0?

**Comment by galactica147** [comment]
so somewhere in the code, I have: 

`os.environ['CUDA_VISIBLE_DEVICES'] = gpu_id
`
previously with 0.1.12, to run parallel jobs I passed one GPU ID to each job, and this worked fine. 
However, after upgrading to 0.2.0 without changing code, all parallel jobs are on GPU 0, no matter which GPU ID i was trying to assign each job to. 

I didn't check if the final results are correct, but this GPU behavior is not what I wanted. 
Any clue what was going on?

**Comment by killeent** [comment]
cc @ngimel are you aware of any changes here?

**Comment by ngimel** [comment]
No, and in any case driver would not change with the new pytorch version, and runtime libraries that are distributed with pytorch are the same between 0.1.12 and 0.2.0

**Comment by galactica147** [comment]
can someone provide me with the link to the previous version's wheel file? thanks!

**Comment by albanD** [comment]
@galactica147 changing the environment variable from within python may not work if the cuda runtime is initialized before you change it, or if you change it in a scope that won't be seen by the cuda driver.
You should change `CUDA_VISIBLE_DEVICES` before launching your script to be sure, or use `torch.cuda.set_device(dev_id)` from within your python script.
