### ISSUE TITLE
nn.quantized.conv2d module does not register _scale and _zeropoint as buffers.

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#23881]
https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/conv.py#L90 and setter/getter methods are not consistent.

**Comment by jerryzh168** [comment]
we decided to remove `_scale`, we can remove the `@property` otherwise this code is going to be repeated for all quantized modules.

**Comment by jerryzh168** [comment]
@zafartahirov the task should be remove @property for scale and zero_point

**Comment by dskhudia** [comment]
@jerryzh168 Is https://github.com/pytorch/pytorch/pull/23991 good enough or did you mean to remove _scale/_zero_points names altogether along with setter/getter?
