### ISSUE TITLE
sparse.mm(S, D) with autograd

### ISSUE THREAD

**Issue by killeent** [pytorch/pytorch#2389]
```
x = torch.sparse.FloatTensor(5, 5)
y = torch.FloatTensor(5, 5)

torch.mm(x, y) # works

xx = torch.autograd.Variable(x)
xy = torch.autograd.Variable(y)

torch.mm(x, y) # fails
```

Error Message:

```
Traceback (most recent call last):
  File "sparse_dense_mm.py", line 22, in <module>
    AX = torch.mm(A, X) # This doesn't work
  File "/home/killeent/github/pytorch/torch/autograd/variable.py", line 580, in mm
    return Addmm.apply(output, self, matrix, 0, 1, True)
  File "/home/killeent/github/pytorch/torch/autograd/_functions/blas.py", line 26, in forward
    matrix1, matrix2, out=output)
TypeError: Type torch.sparse.FloatTensor doesn't implement stateless method addmm
```

I'm not sure what the correct semantics are for dense/sparse, so I may be wrong about this being something we should support. If so, feel free to close :)

cc @vincentqb

**Comment by YiruS** [comment]
Hi I have the same question. Does PyTorch currently support autograd on sparse variables?

**Comment by apaszke** [comment]
It does, but only for certain ops, which right now only include Embedding IIRC. It'd be good to add support for all of them

**Comment by soumith** [comment]
i looked into this, this goes much deeper. We dont do any sparse tests in test_autograd.py. If any sparse ops work within autograd except for nn.Embedding, i think they're working only accidentally.

**Comment by jdily** [comment]
Hi, I just want to test out some of the sparse function, so I tried to run the example @killeent provide.
```
x = torch.sparse.FloatTensor(5, 5)
y = torch.FloatTensor(5, 5)

torch.mm(x, y) # works

xx = torch.autograd.Variable(x)
xy = torch.autograd.Variable(y)
print(type(x), type(xx))

torch.mm(xx, xy) # I think here we want to check if backward things  
```

And I got the following error message:
` RuntimeError: Expected object of type Variable[Sparsetorch.FloatTensor] but found type Variable[torch.FloatTensor] for argument #1 'mat2' `

it seems like some relevant functions are added, however, expect the second argument as sparse as well??
(my version is 0.2.0+5de7f9e)
Not sure if I did something wrong about it.
Thx in advance for this!

**Comment by apaszke** [comment]
cc: @zou3519 it seems that the error message PR gives weird results with sparse tensors

**Comment by jdily** [comment]
Hi, I think probably I didn't describe my problem clear..
Actually I am curious about if torch.mm takes two sparse matrices as arguments?
I am looking for function that do sparse x dense -> sparse on Variables.

thx!

**Comment by apaszke** [comment]
@jdily yeah sorry. You did describe it very clearly, but it's just not implemented at the moment. I only noticed that there's this additional bug which I mentioned.

**Comment by jdily** [comment]
@apaszke No problem. I am just thinking if it is implemented, because as discussed in 
https://discuss.pytorch.org/t/does-pytorch-support-autograd-on-sparse-matrix/6156
it looks like there should be a PR about it?
If so, where can I find it?

Meanwhile, I found out some interesting results about this feature.
Let's take a look at the example above, 
```
x = torch.sparse.FloatTensor(5, 5)
y = torch.FloatTensor(5, 5)
xx = torch.autograd.Variable(x)
xy = torch.autograd.Variable(y)
print(type(x), type(xx))
torch.mm(xx, xy) # I think here we want to check if backward things  
```
it will give us ` RuntimeError: Expected object of type Variable[Sparsetorch.FloatTensor] but found type Variable[torch.FloatTensor]  for argument #1 'mat2' `.
If I understand correctly,  it seems to me that it ask me to change the type of mat2 from `Variable[torch.FloatTensor]` to `Variable[Sparsetorch.FloatTensor]`, i.e. from dense to sparse.
So I change the type of `y` into sparse so the next test:
```
x = torch.sparse.FloatTensor(5, 5)
y = torch.sparse.FloatTensor(5, 5)
xx = torch.autograd.Variable(x)
xy = torch.autograd.Variable(y)
print(type(x), type(xx))
torch.mm(xx, xy) 
```
and this time I got 
```
Traceback (most recent call last):
  File "/home/ichao/project/deep_dci/code/sparse_util.py", line 64, in <module>
    torch.mm(xx, xy)
RuntimeError: mm is not implemented for type torch.sparse.FloatTensor
```
So I am a bit confused about does it even support sparse x sparse ?? 

thx for the help. :)

**Comment by SsnL** [comment]
@jdily Not many operations support sparse tensors currently. (Sparse embeddings work fine in most cases though.) IIRC, dense x sparse works, but I will have to double check tomorrow.

**Comment by SsnL** [comment]
Sorry for the delay. I just checked and sparse x dense works on tensors but not on variables as indicated in the issue text. And sparse x sparse indeed is not supported at the moment.

**Comment by emited** [comment]
What is the current status of this issue?

**Comment by debnil** [comment]
Bumping the above, does autograd work on sparse variables now?

**Comment by apaszke** [comment]
The embedding is guaranteed to work, but many ops still don't support it

**Comment by ortasa** [comment]
I wanted to know if there is an estimated date when there would be support on "sparse ops with autograd"?
Thanks, 
Ortal

**Comment by SsnL** [comment]
@ortasa I'm not sure. The main use case of sparse ops is embedding, which is already fully supported. Since there are many other very crucial tasks, extending autograd to other sparse ops is also quite important, but is not the top of our priorities.

**Comment by flyaway1217** [comment]
I am wondering what is the current status of this issue? 
It is really hard to write code when Pytorch does not support autograd on sparse matrix. It would be very nice if we can use sparse matrix just like dense matrix.

**Comment by lakehanne** [comment]
Also, `sparse` matrix-vector`, `matrix-matrix` and `dot` operations are not available as of yet on `0.3.0.` version.

**Comment by CountingClouds** [comment]
Autograd support for sparse matrices is essential for working in highly sparse and computationally costly learning domains such as when dealing with 2D and 3D point clouds (ie 2D and 3D conv nets operating on sparse data), among other important applications.  Support for it will be extremely useful, and critical in choice of deep learning framework for these applications.  I would like to add my voice of support to the other requests for this capability as well.

**Comment by ShayanPersonal** [comment]
I also need autograd support for sparse tensors. I'd prefer not to switch to Tensorflow, but this is a dealbreaker.

**Comment by benvcutilli** [comment]
I'd like sparse autograd support as well. It is hard to build custom, non-standard layers without them while wanting to maintain the built-in parallelism and speed of the aforementioned operations. Otherwise, I'd be writing slow, looping code, or I would have to use dense tensors which wastes both compute and memory, or I'd have to write some sort of extension, which can be a very big pain if I am just trying out new ideas that may not actually work well or at all.

**Comment by soumith** [comment]
We recently did a full audit of the state of sparse, and have a detailed note here: https://github.com/pytorch/pytorch/issues/9674

We will start focusing more on sparse, and get the autograd coverage it badly needs.

**Comment by santient** [comment]
Does anyone have suggestions for workarounds?

**Comment by mortonjt** [comment]
@santient , there is a sparse version of `mm` in the docs : https://pytorch.org/docs/stable/sparse.html#torch.sparse.mm

I've gotten the example in the docs to work, but unfortunately, there appears to be quite a few edge cases left.

**Comment by AHolliday** [comment]
As of pytorch 1.7.0, `sparse.mm(S, D)` still does not work if the sparse matrix requires gradients with autograd.  I'm starting a graph neural network project in pytorch, but have run into this limitation - I'm dealing with very large sparse matrices, so the speedups from using sparse mm are several orders of magnitude.  But without being able to compute gradients through it, I can't use certain algorithms.

**Comment by shashank-srikant** [comment]
I second that message by @AHolliday :arrow_up: 
I'm running into a similar problem, and would greatly appreciate enabling gradients with autograd for sparse matrix ops.

**Comment by IvanYashchuk** [comment]
There is a [`torch.sparse.mm`](https://pytorch.org/docs/stable/generated/torch.sparse.mm.html) function that supports autograd for sparse COO tensors. `torch.sparse.mm` should be preferred over `torch.mm` for autograd operations with sparse COO tensors. 
The motivation for a separate function is to have sparse gradients, which we can't have with `torch.mm` at the moment as we aim at operator behavior equivalence for dense and sparse inputs for the regular `torch.` namespace.

**Comment by rob-kwiec** [comment]
Hi! When using`torch.sparse.mm` the backward step is quite slow. Have I done something wrong?
`from time import time
import torch
import numpy as np

def test_sparse_speed(a1, a2, b2, density_A, density_B):
    b1 = a2
    nnz_A = int(density_A * a1 * a2)
    nnz_B = int(density_B * b1 * b2)
    
    print(f'Matrix A shape: [{a1}, {a2}], nonzero entries: {nnz_A}')
    print(f'Matrix B shape: [{b1}, {b2}], nonzero entries: {nnz_B}\n')
    
    # create first matrix
    indexA = np.array([np.random.randint(0, a1, (nnz_A, )), np.random.randint(0, a2, (nnz_A, ))])
    valueA = torch.ones(nnz_A, requires_grad=True)
    A = torch.sparse_coo_tensor(
        indexA,
        valueA,
        size=[a1, a2],
    )

    # create second matrix
    indexB = np.array([np.random.randint(0, b1, (nnz_B, )), np.random.randint(0, b2, (nnz_B, ))])
    valueB = torch.ones(nnz_B, requires_grad=True)
    B = torch.sparse_coo_tensor(
        indexB,
        valueB,
        size=[b1, b2],
    )
    
    start = time()
    y = torch.sparse.mm(A, B)
    print(f'Multiplication time: {time()-start} seconds')
    
    loss = y.coalesce().values().sum()
    
    start = time()
    loss.backward()
    print(f'Backward time: {time()-start} seconds')
    return A, B

A, B = test_sparse_speed(a1=100, a2=10**5, b2=10**4, density_A=0.005, density_B=0.0002)`
--->
`Matrix A shape: [100, 100000], nonzero entries: 50000
Matrix B shape: [100000, 10000], nonzero entries: 200000

Multiplication time: 0.03313016891479492 seconds
Backward time: 28.99043607711792 seconds`

**Comment by IvanYashchuk** [comment]
Hey @rob-kwiec! Thank you for reporting the problem, there's nothing wrong with your code snippet. 

`.backward()` uses `sparse_sparse_matmul_backward` that may be slow:
https://github.com/pytorch/pytorch/blob/40b80aa49011849d916f71d9ba3ad6026cbfb662/torch/csrc/autograd/FunctionsManual.cpp#L861-L891
I will open an issue about it.
