### ISSUE TITLE
Memory leak when using itertools.cycle

### ISSUE THREAD

**Issue by rmrao** [pytorch/pytorch#23900]
## 🐛 Bug

I seem to be getting a memory leak when trying to create an infinite dataset via `itertools.cycle`. This issue was reported in #3356 a couple years ago, but I can still reproduce it. I've included a very simple script that reproduces this behavior.

## To Reproduce

```python
from torch.utils.data import Dataset
import itertools
import numpy as np
import resource

def print_memusage():
    memuse = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    print(f'Usage: {memuse / 1e6:0.3f} GB')

class TestDataset(Dataset):
    def __getitem__(self, index):
        return np.arange(1000 * 1000, dtype='u8')
    def __len__(self):
        return 1000000

dataset = TestDataset()
infinite_iterator = itertools.cycle(dataset)

if True:  # change to False to run infinite iterator
    print('Normal Dataset')
    for _ in zip(range(20), dataset):
        print_memusage()
else:
    print('Infinite Iterator')
    for _ in zip(range(20), infinite_iterator):
        print_memusage()
```

## Expected behavior

I would expect to see constant memory usage, with maybe a small increase in the beginning as python may not garbage collect arrays immediately. This is true for the normal dataset iterator - there is a small memory increase at the beginning before memory usage stabilizes at `Usage: 0.185 GB`. If I instead run the infinite iterator, memory usage keeps increasing. I've cut it off here at 20 iterations, so it only gets to `Usage: 0.310 GB`. If I let it keep running it will eventually use all the memory on my machine.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch

**Comment by rmrao** [comment]
Ok upon further investigation it seems that `itertools.cycle` attempts to save all outputs in order to re-cycle through them. Replacing it with something like this:

```python
def cycle(iterable):
    iterator = iter(iterable)
    while True:
        try:
            yield next(iterator)
        except StopIteration:
            iterator = iter(iterable)
```

solves the issue. Is there a canonical way of creating an infinite iterator in pytorch? It is unfortunate that `itertools.cycle` is implemented in this way, although I suppose it makes sense in the average case where the amount of data is very low.

I will close this issue since it's not a pytorch issue.

**Comment by urimerhav** [comment]
Just came to say I hit on the same issue 3 years later. Yes, it's not a pytorch issue, but the reason we all hit on this issue is the lack of native support for "repeat=True" for `DataLoader` class. Might be a good idea to add that feature and save future grief for other developers.

**Comment by vishaal27** [comment]
5 years later, this still does the trick. I was cycling through a webdataset loader, and my jobs were getting killed due to OOM, and turns out `itertools.cycle` was the pesky cause. With the fix implemented above, everything works smoothly!

**Comment by Juphex** [comment]
> 5 years later, this still does the trick. I was cycling through a webdataset loader, and my jobs were getting killed due to OOM, and turns out `itertools.cycle` was the pesky cause. With the fix implemented above, everything works smoothly!

Same for me, this was so annoying to find out. Probably, there will be people that will fall for it.

**Comment by Kevin-Miao** [comment]
I just wanted to comment on here that after hours of debugging I have stumbled upon this thread. 🫠

**Comment by ranck626** [comment]
'itertools.cycle' is such an attractive method for bargaining data loaders of different sizes! 
However, it will make a memory leak....
