### ISSUE TITLE
[JIT] Keep track of the origin Function for Node

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#23918]
## 🚀 Feature
Keep track of the origin Function for Node which is preserved through inlining and other transformations.

## Motivation

Currently after inlining we have a one function and it's impossible to tell which Function/Module a node came from. The information is crucial for quantization as we want to be able to control quantization parameters per module: i.e. we might want to quantize only nodes from a specific submodule.

## Alternatives

The requested feature is similar to `Scope` that exists already. The problem with `Scope` is that it just stores names of the functions (rather than the functions themselves) and only works in tracing. Ideally, this would replace `Scope` in tracing too.

**Comment by eellison** [comment]
I think you implemented this correct ? Closing, if I am wrong please re-open.
