### ISSUE TITLE
Quantized Linear does not work for bias=False 

### ISSUE THREAD

**Issue by llyfacebook** [pytorch/pytorch#23929]
## 🐛 Bug
When there is no bias, the from_float method should take into account the mod.bias is None.

https://github.com/pytorch/pytorch/blob/3fa2df7c9a8b050264dc4a93422db1f217cf4589/torch/nn/quantized/modules/linear.py#L173
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jerryzh168** [comment]
will add a fix

**Comment by jerryzh168** [comment]
should be fixed in https://github.com/pytorch/pytorch/pull/24046
