### ISSUE TITLE
Support the inplace Relu fusion in quantization flow

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#23924]
## 🚀 Feature

When we try to fuse the Conv, and relu, it seems only non-inplace Relu is supported
## Motivation
A lot of models are using the in-place relu

**Comment by jerryzh168** [comment]
is inplace relu, inplace convrelu supported right now? @zafartahirov @dskhudia

**Comment by zafartahirov** [comment]
Inplace relu is landed #23704

**Comment by zafartahirov** [comment]
The inplace is brought back: #24374
