### ISSUE TITLE
Documentation 🐛 w.r.t. weighting loss fncs

### ISSUE THREAD

**Issue by mjdietzx** [pytorch/pytorch#2392]
In `nn.loss.py` class `weight` is specified as type `Tensor`.
https://github.com/pytorch/pytorch/blob/cd5275e79f41e8d461ce7ccde7c0201fcced7e24/torch/nn/modules/loss.py#L99-L100

If a `Tensor` is passed as `weight` it is ignored though (think this changed in 0.2.0). Should be of type `Variable` as correctly documented deeper in implementation:
https://github.com/pytorch/pytorch/blob/cd5275e79f41e8d461ce7ccde7c0201fcced7e24/torch/nn/functional.py#L656-L657

**Comment by vishwakftw** [comment]
This is taken care of in the master branch

https://github.com/pytorch/pytorch/blob/fec3d4a079b082ec6d56ab93f31cdb0a228d09fc/torch/nn/functional.py#L1118-L1119
