### ISSUE TITLE
depth wise very very very slow when tested in pb(onnx to tensorflow pb) 

### ISSUE THREAD

**Issue by beyondli** [pytorch/pytorch#23937]
I trans  pth to pb,and  test depth wise performance of path and pb model, found that  in pth depth wise is very fast, bu pb is very very flow(10x slow),what can I do to get same speed of path model in pb? 
thanks!

env:
torch 1.0
python 3.6
tensorflow 1.12

**Comment by soumith** [comment]
open the issue on TF
