### ISSUE TITLE
How can I use PyTorch with AMD Vega64 on Windows 10

### ISSUE THREAD

**Issue by SlimRG** [pytorch/pytorch#23933]
So, I have AMD Vega64 and Windows 10.
How can I run PyTorch with GPU Support?

**Comment by SlimRG** [comment]
Exept Linux SubSystem

**Comment by peterjc123** [comment]
No, it is not possible in WSL due to https://github.com/microsoft/WSL/issues/829. For the Windows native support, I haven't tried so I can't tell you more details. But the answer is very likely to be no because by simply googling 'rocm windows', you can see that rocm is not supporting Windows.

**Comment by SlimRG** [comment]
Yes, RoCm DOESN'T support windows, BUT amdgpu has windows libraries for machine learning

**Comment by SlimRG** [comment]
@peterjc123 why I can't use WSL 2? Second version has full Linux kernel...

**Comment by peterjc123** [comment]
> @peterjc123 why I can't use WSL 2? Second version has full Linux kernel...

https://devblogs.microsoft.com/commandline/wsl-2-post-build-faq/

**Comment by peterjc123** [comment]
> Yes, RoCm DOESN'T support windows, BUT amdgpu has windows libraries for machine learning
Could you please give some examples?

**Comment by SlimRG** [comment]
@peterjc123 thanks

**Comment by SlimRG** [comment]
@peterjc123 I'm about WinML and fork TensorFlow

**Comment by xcom169** [comment]
There is HIP support on Windows
