### ISSUE TITLE
Jupyter kernel dies when importing torch

### ISSUE THREAD

**Issue by kvrd18** [pytorch/pytorch#2393]
Hi,

My Jupyter/IPython notebook with a python3 kernel crashes when I'm trying to import torch. Didn't face this issue before the 0.2 release. Any idea why?

**Comment by kvrd18** [comment]
Closing this issue as it's a Jupyter error. Nothing to do with PyTorch.

**Comment by VincentMatthys** [comment]
Hello,

how did you solve it ?

**Comment by kvrd18** [comment]
@VincentMatthys the latest release does not have this problem.
