### ISSUE TITLE
The Observer insertion should skip the empty nn.Sequential module

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#23931]
## 🐛 Bug
binary,link-tree/torch/quantization/observer.py", line 36, in forward
>     self.min_val = torch.min(torch.min(x), self.min_val)
> TypeError: min(): argument 'input' (position 1) must be Tensor, not NoneType

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by llyfacebook** [comment]
@jerryzh168 It should be okay to add the nn.Sequential to the DEFAULT_SKIP_LIST. Right?
`DEFAULT_SKIP_LIST = [nn.Identity, nn.MaxPool2d, nn.Sequential]`

**Comment by jerryzh168** [comment]
fixed now
