### ISSUE TITLE
Fused Conv2d/Batchnorm Op is not implemented for post training quantization flow

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#23932]
## 🚀 Feature

When we fuse the conv2d and its followed batchnorm, we need the quantized operator support in PyTorch quantization flow.

## Motivation
We want to fuse convolution and batch norm to improve the quantization accuracy.

**Comment by jerryzh168** [comment]
what do you mean? fused conv2d and batchnorm is just conv2d in post training flow. and we also have qat fused convbn implemented as well.

**Comment by jianyuh** [comment]
@dskhudia : could you take a look? I thought for the Resnexrt101, the batchnorm is already fused with Conv2d by changing the scale and bias during the requantization process? Correct me if I am wrong.

**Comment by llyfacebook** [comment]
> what do you mean? fused conv2d and batchnorm is just conv2d in post training flow. and we also have qat fused convbn implemented as well.

Yes, it is fused into conv2d. However, there is still error out for 

`"RuntimeError: No function is registered for schema aten::native_batch_norm(Tensor input, Tensor? weight, Tensor? bias, Tensor? running_mean, Tensor? running_var, bool training, float momentum, float eps) -> (Tensor, Tensor, Tensor) on backend QuantizedCPU"`


 ```
        (conv): Conv2d(
            (conv2d): ConvBn2d(
              (0): Conv2d(
                184, 1104, kernel_size=(1, 1), stride=(1, 1), bias=False
                (observer): Observer()
              )
              (1): BatchNorm2d(
                1104, eps=1e-05, momentum=0.003, affine=True, track_running_stats=True
                (observer): Observer()
              )
            )
```

**Comment by jerryzh168** [comment]
should we close this?
