### ISSUE TITLE
forward_packed operator in LSTM not supported by jit scriptmodule

### ISSUE THREAD

**Issue by jiqiujia** [pytorch/pytorch#23930]
## To Reproduce
1. I use pytorch stable 1.1.0 on win10
2. Steps to reproduce the behavior:
```python
import torch
import torch.nn as nn

print(torch.__version__)


class test(torch.jit.ScriptModule):

    def __init__(self, rnn_dims=512):
        super().__init__()
        self.rnn = nn.LSTM(input_size=rnn_dims, hidden_size=rnn_dims, batch_first=True)

    @torch.jit.script_method
    def forward(self, x):
        # h1 = (torch.zeros(1, 1, 512), torch.zeros(1, 1, 512))
        out, h1 = self.rnn(x, torch.zeros(1, 1, 512))

        return h1


net = test()

output = net(torch.randn(1, 1, 512))

print(output.shape)
```
3. error message
```
Traceback (most recent call last):
  File "E:/dlprojects/DeepSegment/serving/test.py", line 22, in <module>
    net = test()
  File "F:\anaconda3\lib\site-packages\torch\jit\__init__.py", line 1047, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "F:\anaconda3\lib\site-packages\torch\jit\__init__.py", line 1012, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
Could not find any matching overloads

for operator forward_packed(ClassType<$Module> self, (Tensor, Tensor, Tensor?, Tensor?) input, (Tensor, Tensor)? hx=<default>) -> ((Tensor, Tensor, Tensor?, Tensor?), (Tensor, Tensor)):
expected a value of type (Tensor, Tensor, Tensor?, Tensor?) for argument 'input' but found Tensor
@torch.jit.script_method
def forward(self, x):
    # h1 = (torch.zeros(1, 1, 512), torch.zeros(1, 1, 512))
    out, h1 = self.rnn(x, torch.zeros(1, 1, 512))
                       ~ <--- HERE

    return h1

for operator forward_tensor(ClassType<$Module> self, Tensor input, (Tensor, Tensor)? hx=<default>) -> (Tensor, (Tensor, Tensor)):
expected a value of type (Tensor, Tensor)? for argument 'hx' but found Tensor
@torch.jit.script_method
def forward(self, x):
    # h1 = (torch.zeros(1, 1, 512), torch.zeros(1, 1, 512))
    out, h1 = self.rnn(x, torch.zeros(1, 1, 512))
                          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE

    return h1
:
@torch.jit.script_method
def forward(self, x):
    # h1 = (torch.zeros(1, 1, 512), torch.zeros(1, 1, 512))
    out, h1 = self.rnn(x, torch.zeros(1, 1, 512))
              ~~~~~~~~ <--- HERE

    return h1
```
## Expected behavior
Expect to generate Torch Script.

## Environment
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 专业版
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.4.0
CMake version: version 3.11.3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] msgpack-numpy==0.4.1
[pip3] numpy==1.15.3
[pip3] numpydoc==0.7.0
[pip3] pytorch-pretrained-bert==0.6.1
[pip3] torch==1.1.0
[pip3] torchtext==0.4.0
[pip3] torchvision==0.2.2
[conda] bert-pytorch              0.0.1a4                   <pip>
[conda] mkl                       2018.0.1             h2108138_4    defaults
[conda] mkl-service               1.1.2            py36h57e144c_4    defaults
[conda] pytorch-cpu               1.1.0               py3.6_cpu_1    pytorch
[conda] pytorch-pretrained-bert   0.6.1                     <pip>
[conda] torch                     0.4.0                     <pip>
[conda] torchtext                 0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision-cpu           0.2.2                      py_3    pytorch

**Comment by ailzhang** [comment]
cc: @wanchaol @eellison

**Comment by driazati** [comment]
I think this is expected for your example, the hidden state is supposed to be of `Optional[Tuple[Tensor, Tensor]]` instead of just `Tensor`. Your example fails in eager mode as well

```
RuntimeError: Expected hidden[0] size (1, 1, 512), got (1, 512)
```

Your example runs fine if you use `h1` for the hidden state instead. Closing since this looks like user error, feel free to re-open if you are still running into errors.
