### ISSUE TITLE
We should run clang-tidy on all of master

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#23946]
## 🐛 Bug

Over in https://github.com/pytorch/pytorch/pull/23942 clang-tidy was failing due to existing issues in one of the files I modified.  But the error isn't actually represented anywhere except for the original PR, because we run clang-tidy as a diff.

This means we have "time-bomb" clang-tidy failures which you only run into when you are modifying a file that happens to have an error.

CC @ezyang.

**Comment by eellison** [comment]
Having the same issue editing `jit/script/init.cpp` cc @suo

**Comment by driazati** [comment]
The `-line-filter` option on clang tidy should at least limit it to issues on code that was changed in the PR, but it looks like despite being correctly configured it doesn't actually work

```
clang-tidy -p build \
-config {"Checks": " -* ,bugprone-* ,-bugprone-forward-declaration-namespace ,-bugprone-macro-parentheses ,cppcoreguidelines-* ,-cppcoreguidelines-interfaces-global-init ,-cppcoreguidelines-owning-memory ,-cppcoreguidelines-pro-bounds-array-to-pointer-decay ,-cppcoreguidelines-pro-bounds-constant-array-index ,-cppcoreguidelines-pro-bounds-pointer-arithmetic ,-cppcoreguidelines-pro-type-cstyle-cast ,-cppcoreguidelines-pro-type-reinterpret-cast ,-cppcoreguidelines-pro-type-static-cast-downcast ,-cppcoreguidelines-pro-type-union-access ,-cppcoreguidelines-pro-type-vararg ,-cppcoreguidelines-special-member-functions ,hicpp-exception-baseclass ,hicpp-avoid-goto ,modernize-* ,-modernize-return-braced-init-list ,-modernize-use-auto ,-modernize-use-default-member-init ,-modernize-use-using ,performance-* ,-performance-noexcept-move-constructor ", "WarningsAsErrors": "*", "HeaderFilterRegex": "torch/csrc/.*", "AnalyzeTemporaryDtors": false, "CheckOptions": null} \
-line-filter [{"name": "torch/csrc/TypeInfo.cpp", "lines": [[87, 93], [149, 150], [161, 162]]}, {"name": "torch/csrc/autograd/python_variable_indexing.cpp", "lines": [[178, 179]]}, {"name": "torch/csrc/jit/fuser/codegen.cpp", "lines": [[107, 108]]}, {"name": "torch/csrc/jit/passes/shape_analysis.cpp", "lines": [[42, 43]]}, {"name": "torch/csrc/jit/register_prim_ops.cpp", "lines": [[89, 90]]}, {"name": "torch/csrc/utils/python_arg_parser.cpp", "lines": [[159, 160]]}] \
torch/csrc/TypeInfo.cpp torch/csrc/autograd/python_variable_indexing.cpp torch/csrc/jit/fuser/codegen.cpp torch/csrc/jit/passes/shape_analysis.cpp torch/csrc/jit/register_prim_ops.cpp torch/csrc/utils/python_arg_parser.cpp
```

**Comment by nairbv** [comment]
It's also easier to feel confident that the rules clang-tidy is imposing make sense if they pass on master. I have a PR that fails clang-tidy if I don't use a const reference for an `optional<ScalarType>`, and I'm not really sure if that's a valid complaint.

**Comment by suo** [comment]
https://github.com/pytorch/pytorch/issues/23946 should fix the issue where clang-tidy is showing errors for things that weren't touched by you
