### ISSUE TITLE
Conv2D (FP32) and Quantized Conv2D benchmarking on CPUs

### ISSUE THREAD

**Issue by dskhudia** [pytorch/pytorch#23944]
We want a side-by-side comparison of Conv2D and QConv2D performance.

**Comment by jamesr66a** [comment]
Is this completed?

**Comment by z-a-f** [comment]
I think this is implemented here: `benchmarks/operator_benchmark/pt/qconv_test.py`

**Comment by vkuzo** [comment]
this is done, closing
