### ISSUE TITLE
Multiprocessing 

### ISSUE THREAD

**Issue by mjchen611** [pytorch/pytorch#2394]
Hi, I use the Pytorch on Windows, but I found a problem, when I use multiprocessing(cuda), I put all the codes in a file, it's no problem. When some arguments  transfered by another difined file( or class in other file) ,it always has the problem:    
       ForkingPickler(file, protocol).dump(obj)
       BrokenPipeError: [Errno 32] Broken pipeAnd 

I found it's because some problems about Python multiprocessing on Windows, so can you give me some suggestions about this problem?

Thank you so much.

**Comment by apaszke** [comment]
We don't officially support Windows. Our multiprocessing code is very POSIX-specific

**Comment by apurvapatkeshwar** [comment]
On a Windows machine, you may need to wrap your multiprocessing code inside:
`if __name__ == '__main__'`
