### ISSUE TITLE
[torch.distributed][RPC]  An RPC callee could crash on `RpcAgent::join()`, if the caller terminates with unresolved future.

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#23948]
## 🐛 Bug

This is a followup for #23228 

## To Reproduce

1. A peer sends out an async RPC without waiting for the response.
1. Every peer join.

## Expected behavior

No peer process crashes

## Reason

This error happens because when a callee is sending out a response (pulled from it's send queue) to the caller, the caller has already terminated it's recvLoop thread and destructed itself.

The condition to terminate the recvLoop thread on rank[i] is that rank[i-1] sends , while peers of ranks other than rank[i] and rank[i - 1] could still has pending requests to send out to rank[i].

![image](https://user-images.githubusercontent.com/7608630/62644298-a458d580-b8fe-11e9-9dd4-7273ca0b138f.png)

# Solution

## 1. This should work

1. ProcessGroupAgent::join, needs to have all futures resolved before sending out termination message. i.e. put the first barrier in ProcessGroupAgent::join after waiting for all futures resolved.

1. recvLoop thread terminates only if it has received termination messages from all peers.

## 2. Maybe work

call a second barrier before ::join() returns.

It's actually better, because if a user doesn't wait on the unresolved future, it means leaving them unresolved doesn't matter. But the system could log a warning to remind users about it.

I have tried out this solution. I will lead to a deadlock, as described in, https://github.com/pytorch/pytorch/issues/23975.

![image](https://user-images.githubusercontent.com/7608630/62644970-2f869b00-b900-11e9-8ea9-ac7fa95ca3d8.png)

## Error message

```Bash
terminate called after throwing an instance of 'gloo::IoException'
  what():  [gloo/transport/tcp/pair.cc:572] Connection closed by peer [2401:db00:30:503a:face:0:75:0]:38334
terminate called after throwing an instance of 'gloo::IoException'
  what():  [gloo/transport/tcp/pair.cc:572] Connection closed by peer [2401:db00:30:503a:face:0:75:0]:30850
terminate called after throwing an instance of 'gloo::IoException'
  what():  [gloo/transport/tcp/pair.cc:572] Connection closed by peer [2401:db00:30:503a:face:0:75:0]:21379
ERROR

======================================================================
ERROR: test_rpc_no_op (caffe2.torch.fb.modelparallel.prototype.pytorch.tests.test_rpc.TestRPC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/modelparallel/prototype/pytorch/tests/test_rpc#binary,link-tree/caffe2/torch/fb/modelparal
lel/prototype/pytorch/tests/test_rpc.py", line 210, in test_rpc_no_op
    TestRPC.launch_rpc_test(app_rpc_no_op)
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/modelparallel/prototype/pytorch/tests/test_rpc#binary,link-tree/caffe2/torch/fb/modelparal
lel/prototype/pytorch/tests/test_rpc.py", line 206, in launch_rpc_test
    exit_on_worker_done="w:1",
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/modelparallel/prototype/pytorch/tests/test_rpc#binary,link-tree/caffe2/torch/fb/modelparal
lel/prototype/pytorch/rpc.py", line 1301, in rpc_main
    nprocs=len(worker_names),
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/modelparallel/prototype/pytorch/tests/test_rpc#binary,link-tree/torch/multiprocessing/spaw
n.py", line 171, in spawn
    while not spawn_context.join():
  File "/data/users/shihaoxu/fbsource/fbcode/buck-out/dev/gen/caffe2/torch/fb/modelparallel/prototype/pytorch/tests/test_rpc#binary,link-tree/torch/multiprocessing/spaw
n.py", line 107, in join
    (error_index, name)
Exception: process 3 terminated with signal SIGABRT
```

# Caveat

The problem is solvable, but it's hard to add a test case for it, because the problem only manifests in a certain execution order.

Keep this issue open until we found a concurrency testing framework/approach, which can reproduce any desired deterministic execution order.

Reference, to a Python time simulation (stepping) framework. [SimPy](https://simpy.readthedocs.io/en/latest/).

This issue could emerge again when implementing other communication backend other than ProcessGroup.

**Comment by xush6528** [comment]
@mrshenli

**Comment by mrshenli** [comment]
> The condition to terminate the recvLoop thread on rank[i] is that rank[i-1] sends , while peers of ranks other than rank[i] and rank[i - 1] could still has pending requests to send out to rank[i].

I think it might be because we mark the send queue as empty [too soon](https://github.com/pytorch/pytorch/blob/919024f9ba32be66ca664dcdd3a720870ebf12c3/torch/csrc/distributed/rpc/ProcessGroupAgent.cpp#L164). Otherwise, the shutdown should always arrive after that message, as there is a barrier in the middle, no? If that is the case, #23968 might also help, as it only sets `complete_` to true after running the task. 

CC @pritamdamania87 @satgera we had a discussion early today on whether the sync/join needs to be done by the application or the rpc implementation, but no conclusion yet.

**Comment by xush6528** [comment]
@mrshenli sorry, I don't follow. Can you re-phrase a little?

If you are saying now we are marking the send queue as empty too soon, when should be a good time to mark the last message as having been popped from the queue?


I will follow #23968 to see what's the major change there, and see that it will impact this.

**Comment by mrshenli** [comment]
Sorry about the hand-waving comments. Let me clarify.

> If you are saying "now we are marking the send queue as empty too soon", when should be a good time to mark the last send work as having been popped out from the queue and having been sent out? After the actually pg_->send() happens?

Yes, when we notify on [`workConsumeCV_` in the `sendLoop`](https://github.com/pytorch/pytorch/blob/919024f9ba32be66ca664dcdd3a720870ebf12c3/torch/csrc/distributed/rpc/ProcessGroupAgent.cpp#L167), the send is not really done yet. And the [second barrier in sync](https://github.com/pytorch/pytorch/blob/919024f9ba32be66ca664dcdd3a720870ebf12c3/torch/csrc/distributed/rpc/ProcessGroupAgent.cpp#L116) and finish before the last send. Say this happens on A, and the last send message is to C. It is possible that C receives shutdown message from B before the last send message from A. (I think this is one example of the situation you mentioned above)

I agree with your fix and I think it should work. Another option could be similar to [`ThreadPool`](https://github.com/pytorch/pytorch/blob/82aecfad6a0a1d7790f7e96157033bcc576d346e/c10/core/thread_pool.cpp#L122)'s solution, which uses a dedicated `complete_` cv.

> If so, I don't think anything changes for the scenario represented by the first diagram.
>
> After passing the barrier, the send thread on an RPC callee could still send an RPC response back to the caller, while the caller has already received TERMINATION message from it's neighbor and destructed.

Yes, I totally agree with your assessment and fix. I am just trying to inspect to see what else needs to be fixed.

**Comment by xush6528** [comment]
Not urgent
