### ISSUE TITLE
C++ error: Severity	Code	binary '!': no operator found which takes a left-hand operand of type 'at::Tensor' (or there is no acceptable conversion)	

### ISSUE THREAD

**Issue by liukuanlk** [pytorch/pytorch#23976]
## 🐛 Bug

When I tired to use "equals" function in "c10::ArrayRef"(Win 10,  Visual Studio C++ Professional 2017 Version 15.9.14 ), I cannot even build the code.  They error messages are as following,

> 1. Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2678	binary '!': no operator found which takes a left-hand operand of type 'at::Tensor' (or there is no acceptable conversion)	PyTorchBug	c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xutility	3084	
> 2. Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2088	'!': illegal for class	PyTorchBug	c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xutility	3084

	

![image](https://user-images.githubusercontent.com/22803967/62658096-ea7d5b80-b935-11e9-98a3-0f8c82b773d5.png)

It says 

> binary '!': no operator found which takes a left-hand operand of type 'at::Tensor' (or there is no acceptable conversion)

It should work coz the "equals" function is well defined in "ArrayRef.h"

Also, the error message does not direct me to a header file in PyTorch. 

Is there any possible workaround to use this "equals" function? Thank you very much!

## To Reproduce

1. Copy and paste the following code into visual studio (change the path)

```
#include <iostream>
#include "C:\Users\kuanliu\Desktop\PT\libtorch-win-shared-with-deps-latest\libtorch\include\torch\csrc\autograd\generated/variable_factories.h"


int myfoo() {
	c10::ArrayRef<at::Tensor> const *A;
	c10::ArrayRef<at::Tensor> const *B;
        bool test = A->equals(*B);
	return 0;
}

int main()
{
	std::cout << "Hello World!\n";
}
```

2. Add "additional include directories" and "additional dependencies"
3. Build

## Expected behavior

It should work coz the "equals" function is well defined in "ArrayRef.h"

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.1
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): Windows LibTorch C++
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:  Visual Studio C++ Professional 2017 Version 15.9.14

**Comment by ezyang** [comment]
Thanks for the bug report. The problem is probably something like, doing an equality test on tensor will result in a tensor, and tensors cannot be negated with the `!` operator. So use of `equals` on ArrayRef here is not supported; you'll need to do something else.

**Comment by liukuanlk** [comment]
Thanks for reply! Is there any possible workaround for this issue?

**Comment by ezyang** [comment]
Well, you have to decide exactly what it is you want to do. If I gave you just two tensors, how do you want to check if they're equal? `x == y` gives you another tensor, remember. Do you want to just check that all the elements are close? (allclose)? Do they need to be exactly the same?

If you post this question in the forums you can get some more guidance.

**Comment by liukuanlk** [comment]
Sorry I did not get your point. Why `x == y` gives you another tensor, remember?

In this webpage, line #159-162
https://github.com/pytorch/pytorch/blob/master/c10/util/ArrayRef.h
```
  /// equals - Check for element-wise equality.
  constexpr bool equals(ArrayRef RHS) const {
    return Length == RHS.Length && std::equal(begin(), end(), RHS.begin());
  }
```
Does it mean the returned value is boolean?

**Comment by ezyang** [comment]
```
Tensor x, y; // suppose I have two C++ tensors
Tensor z = x == y; // if I compare them for equality, I get a tensor, not bool
```

This matches the behavior in Python.
