### ISSUE TITLE
[quantization] copy_kernel_cast not implemented for QUInt8

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#23986]
JIT Trace checking seems to invoke `copy_kernel_cast` on the outputs, and thus fails since this op is not implemented for QUInt8:

```
======================================================================
ERROR: test_linear_api (__main__.ModuleAPITest)
test API functionality for nn.quantized.linear and nn._intrinsic.quantized.linear_relu
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_nn_quantized.py", line 39, in test_linear_api
    batch_size=st.integers(1, 5),
  File "/home/jamesreed/miniconda3/lib/python3.6/site-packages/hypothesis/core.py", line 1024, in wrapped_test
    raise the_error_hypothesis_found
  File "test/test_nn_quantized.py", line 119, in test_linear_api
    self.checkScriptable(qlinear, list(zip([X_q], [Z_ref])))
  File "/home/jamesreed/pytorch/test/common_quantization.py", line 127, in checkScriptable
    traced = torch.jit.trace(orig_mod, calib_data[0][0])
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 771, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 913, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "/home/jamesreed/pytorch/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 634, in _check_trace
    if compare_outputs(traced_outs, fn_outs, 'Python function'):
  File "/home/jamesreed/pytorch/torch/jit/__init__.py", line 621, in compare_outputs
    torch.testing.assert_allclose(orig.double(), ref.double(), rtol=check_tolerance,
RuntimeError: "copy_kernel_cast" not implemented for 'QUInt8'
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jamesr66a** [comment]
@zrphercule I know you mentioned you were looking into this. Did you make any progress?

**Comment by zrphercule** [comment]
> @zrphercule I know you mentioned you were looking into this. Did you make any progress?

yeah I looked into this problem last week in order to support glow<=>pytorch intermediate result. However, since we are now focusing on making the model running, we would like to do it later.

**Comment by jerryzh168** [comment]
is this casting from double to quint8? I don't think we will support that

**Comment by jerryzh168** [comment]
@supriyar is this supported?

**Comment by supriyar** [comment]
> @supriyar is this supported?

Looks like we are checking this in the test now 
https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantized_nn_mods.py#L322.
And I believe `copy_kernel` is supported for qint types.

**Comment by jerryzh168** [comment]
check_trace is still False here: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_quantization.py#L139

**Comment by supriyar** [comment]
Enabled it here - https://github.com/pytorch/pytorch/pull/36740
