### ISSUE TITLE
[docs] Update and momentum formulas in SGD docs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#23982]
A proposal: add `_t` and `_{t+1}` (or `_{t-1}`) indices in appropriate places. It will be clearer what's happening and more aligned to the formulas typically used in optimization papers.

Currently: `v=ρ∗v+g`

Proposed: `v_{t+1}=ρ∗v_{t}+g_{t+1}`

https://pytorch.org/docs/master/optim.html?highlight=sgd#torch.optim.SGD

**Comment by Chillee** [comment]
IMO, this is a no brainer. I'll put up a PR.

**Comment by vadimkantorov** [comment]
Awesome, thanks :)
Same for `p=p−lr∗v`, and the second formula block.

**Comment by vadimkantorov** [comment]
rho in this formula is momentum value which is scalar in PyTorch as far as I understand. so rho needs not have the subscript.

**Comment by Chillee** [comment]
Oh whups, in my quick skim I mistook the rho and the p for the same letter 😅

**Comment by vadimkantorov** [comment]
Also would be nice to rename them, rho and p are a bit confusing @SsnL

**Comment by Chillee** [comment]
`mu` is the standard choice instead of `rho`, I believe.
