### ISSUE TITLE
TorchScript doesn't recognize `tuple` constructor

### ISSUE THREAD

**Issue by dzhulgakov** [pytorch/pytorch#24000]
## 🐛 Bug

TorchScript doesn't recognize `tuple(x, y)` as a native construct and instead resolve it to a python function. This leads to very non-intuitive error messages.

## To Reproduce

Minimal example:
```
@torch.jit.script
def bar(x, y):
    f = tuple(x,y)
    return f

print(bar.code)

def bar(x: Tensor,
    y: Tensor) -> Tensor:
  return ^tuple()(x, y)
#        ^^^^^^^ notice the python ref
```

This leads to wrong error messages in bigger programs:

```
@torch.jit.script
def foo(x: Tuple[Tensor, Tensor]):
    return x[0] + x[1]

@torch.jit.script
def bar(x, y):
    f = tuple(x,y)
    return foo(f)

RuntimeError: 

foo((Tensor, Tensor) x) -> (Tensor):
Expected a value of type 'Tuple[Tensor, Tensor]' for argument 'x' but instead found type 'Tensor'.
:
at <ipython-input-17-39cc7241a270>:11:12
@torch.jit.script
def bar(x, y):
    f = tuple(x,y)
    return foo(f)
           ~~~ <--- HERE

'bar' is being compiled since it was called from 'bar'
at <ipython-input-17-39cc7241a270>:6:21
@torch.jit.script
def foo(x: Tuple[Tensor, Tensor]):
    return x[0] + x[1]
                    ~ <--- HERE

'bar' is being compiled since it was called from 'foo'
at <ipython-input-13-606b6197e73d>:6:21
@torch.jit.script
def foo(x: Tuple[Tensor, Tensor]):
    return x[0] + x[1]
                    ~ <--- HERE
```

Btw, the error message `'bar' is being compiled since it was called from 'foo'` seems to be off too

## Expected behavior

`tuple(x,y)` should be just equivalent to `(x,y)`

`list((x,y))` works fine btw.

**Comment by eellison** [comment]
`tuple(x, y)` throws an error in python. `tuple` only takes in one argument  and calls `__iter__` on it. There aren't many inputs which are iterable and where we can statically type the length of the output tuple. We should have a better error message, though.
