### ISSUE TITLE
How to convert pytorch model(faster-rcnn) to onnx?

### ISSUE THREAD

**Issue by waynebianxx** [pytorch/pytorch#24009]
## ❓ Questions and Help

I trained a faster-rcnn model use the project: jwyang/faster-rcnn.pytorch
[https://github.com/jwyang/faster-rcnn.pytorch](url)
I want convert the model to onnx, this is my code:
`          torch_out=torch.onnx.export(fasterRCNN,\
            (im_data,im_info,gt_boxes,num_boxes),\ 
               "onnx_model_name.onnx",\
                 export_params=True,\
                   opset_version=10,\
                     do_constant_folding=True,\
                       input_names=['input'],\
                         output_names=['output'])`
I get this error:
File "/home/user/anaconda3/envs/mypytorch-env/lib/python3.7/site-packages/torch/jit/__init__.py", line 297, in forward
    out_vars, _ = _flatten(out)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int
Terminated

Who ever encountered this problem? 
Please help me. Thank you very much.

**Comment by ajaysg** [comment]
yes this is the problem with input format. all your input parameters like `im_data,im_info,gt_boxes,num_boxes` should be torch tensors and you should pass them as tuples inside torch.onnx.export function, which you have done correctly. Please make sure all the parameters are torch tensors

**Comment by zubairahmed-ai** [comment]
@ajaysg 
> yes this is the problem with input format. all your input parameters like `im_data,im_info,gt_boxes,num_boxes` should be torch tensors and you should pass them as tuples inside torch.onnx.export function, which you have done correctly. Please make sure all the parameters are torch tensors

Do you know whats wrong with below code, I'm getting same error as @waynebianxx

`dlab = models.segmentation.deeplabv3_resnet101(pretrained=1).eval()`
`dummy_input = torch.randn(10, 3, 450, 450) `
`torch.onnx.export(dlab, dummy_input, "dlab.onnx", verbose=True)`

**Comment by hovhanns** [comment]
Hi, I'm getting the following error, during converting _torchvision.models.detection.fasterrcnn_resnet50_fpn_ model to ONNX.
 
`RuntimeError: Failed to export an ONNX attribute 'onnx::Sub', since it's not constant, please try to make things (e.g., kernel size) static if possible`
Any ideas about how to solve this?

Here is the code:
```
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
dummpy_input = torch.randn(1, 3, 800, 1333)
torch.onnx.export(model, dummpy_input, "FasterRCNN.onnx", verbose=True, input_names=['image_in'],
                  output_names = ['image_out'])
```

**Comment by gloomyfish1998** [comment]
i can convert to faster rcnn with below scripts:
device = torch.device('cpu')
dummy_input = torch.randn((1, 3, 600, 600), device=device)
# model = torch.load("./age_gender_model.pt")
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()
output = model(dummy_input)
model.to(device)
torch.onnx.export(model, dummy_input, "faster_rcnn.onnx", do_constant_folding=True, output_names={"output"}, opset_version = 11)

but could not invoke by opencv dnn / tensorRT at all ,

**Comment by Bob-AFei** [comment]
> Hi, I'm getting the following error, during converting _torchvision.models.detection.fasterrcnn_resnet50_fpn_ model to ONNX.
> 
> `RuntimeError: Failed to export an ONNX attribute 'onnx::Sub', since it's not constant, please try to make things (e.g., kernel size) static if possible`
> Any ideas about how to solve this?
> 
> Here is the code:
> 
> ```
> model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
> dummpy_input = torch.randn(1, 3, 800, 1333)
> torch.onnx.export(model, dummpy_input, "FasterRCNN.onnx", verbose=True, input_names=['image_in'],
>                   output_names = ['image_out'])
> ```

I saved this model into a local "pth" file, then read the local file, the ONNX parser could work

**Comment by garymm** [comment]
Instructions from @ajaysg-zz should resolve original issue. Due to lack of response from @waynebianxx closing. Please open a new issue with clear repro instructions if needed.
