### ISSUE TITLE
Refactor CircleCI config for version 2.1

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#24025]
CircleCI config 2.1 (https://circleci.com/docs/2.0/reusing-config/) has parametrized builds and commands, which should reduce the script generation we have to.

Things we can refactor using 2.1:

* `setup_linux_system_environment`, `should_run_job`, `setup_ci_environment`, `macos_brew_update`, `binary_checkout`, `binary_populate_env`, `binary_install_miniconda`, `binary_macos_brew_update`,  can become "commands" instead of yaml fragments

* Job specifications like `pytorch_linux_trusty_py2_7_9_build` can turn `BUILD_ENVIRONMENT` and `DOCKER_IMAGE` into parameters. These parameters can be fed in from workflow site, instead of having to define a separate job per configuration

Essentially, instead of having to generate the matrix of combinations twice, we only need to generate it once, in workflows. Based on experience in https://github.com/pytorch/vision/blob/master/.circleci/config.yml.in I think a full-fledged suite of Python scripts for generating configs is unnecessary: making the input config.yml.in a jinja2 template should be sufficient (I don't personally think we get all that much utility from having the yaml file split into separate parts, but you can do that if you want to, with jinja).

CC @kostmo

**Comment by kostmo** [comment]
Agreed, much of the current complexity could be dropped.

Some of that complexity had originated from making sure that the generated version matched the hand-written version almost exactly, so that we had full confidence that nothing was lost in the cutover.

**Comment by huydhn** [comment]
Closing this as this is not relevant anymore and PyTorch has migrated off CircleCI
