### ISSUE TITLE
triu not implemented for Bool

### ISSUE THREAD

**Issue by calincru** [pytorch/pytorch#24035]
I'm getting the error [title] with the latest nightly build.  I was doing

```python
torch.ones(n, m, dtype=torch.uint8).triu_() 
```
to get an upper-triangular mask, but now I'm getting a deprecation warning about using tensors other than booleans in `torch.masked_scatter`, so I changed the above to

```python
torch.ones(n, m, dtype=torch.bool).triu_()
```
which now fails with `RuntimeError: "triu" not implemented for 'Bool'`.  Is this known and/or WIP?

**Comment by maxwell-aladago** [comment]
Version **1.1.0.post2** gives a runtime error of  *triu__ not supported on CPUType for Bool* but works fine for dtype=torch.uint8.
