### ISSUE TITLE
Add a batch callback in dataloaders

### ISSUE THREAD

**Issue by cannon** [pytorch/pytorch#24034]
## 🚀 Feature
Add a user defined callback function that runs before each batch in the dataloader worker (torch/utils/data/_utils/worker.py)

## Motivation

We are trying to train multi-scale models, where images of different size are input into a CNN. Within dataset.__getitem__, we do our random crop augmentation and then currently we scale all images to the same size so they can be collated into the 4D batch tensor. To do multi scale training we need to scale the images to different sizes but of course all the images within a batch need to be the same size to stack, so we want to select a different image size between each batch.

## Pitch

Implement this, or an alternative

## Alternatives

A good alternative would be to allow sampling from a dataset object by sending it a sequences of indices that make up a batch all at the same time, rather than one index at a time. By sending one index at a time, the dataset object doesn't know when the next batch begins. If the dataset object knew which indices belonged to the same batch, it could handle this internally.

## Additional context

Our current workaround is to create batches that are always the same size, and then use functional.upsample to randomly resize the batch from within the model. This is a poor solution because it requires scaling the image twice - once to build the batch (which is necessary because the raw images are different sizes), and then again in the model. Scaling the image twice blurs it more/loses more detail than scaling only once.

**Comment by SsnL** [comment]
> allow sampling from a dataset object by sending it a sequences of indices that make up a batch all at the same time, rather than one index at a time. 

This is already allowed if you pass a `batch_sampler` to the data loader.

**Comment by cannon** [comment]
I'm pretty sure that it still calls _getitem_ with each index individually when you do that, though.

**Comment by SsnL** [comment]
Oh I see what you mean. 

You can also just pass that as the regular `sampler`, implement the logic in your dataset as
```
def __getitem__(self, batched_indices):
  # returns a list of batch samples
``` 
and disable auto-batching via `batch_size=None` (see https://pytorch.org/docs/stable/data.html#disable-automatic-batching).

**Comment by cannon** [comment]
It looks like we could get the batch callback just by defining a custom batch sampler that does what we want. We ended up creating a SizedSample class that has an index plus the desired image size for the batch, and passed those to dataset.__getitem__ for each batch member individually. Thanks
