### ISSUE TITLE
Advanced Indexing issues

### ISSUE THREAD

**Issue by arunmallya** [pytorch/pytorch#2404]
There seem to be issues with corner cases where `data[:, mask, ...]` or `data[mask, ...]` fails if `data` is 2 or 1 dimensional resp. In other words, an unnecessary trailing `...` causes failures, while it doesn't in numpy.

MWE is here: https://gist.github.com/arunmallya/23457765e37faf8932da9276e2b449a8

**Comment by killeent** [comment]
Someone assign this to me and I can fix this.

**Comment by blythed** [comment]
```data[:, mask, :]``` fails for me regardless of the dimensionality. Or am the only one with this problem?

**Comment by soumith** [comment]
addressed by https://github.com/pytorch/pytorch/pull/2589
