### ISSUE TITLE
ByteTensor/boolean indexing difference between torch/numpy

### ISSUE THREAD

**Issue by arunmallya** [pytorch/pytorch#2405]
The behavior of torch and numpy for ByteTensor/boolean indexing is different. Not sure if intended behavior.

MWE: https://gist.github.com/arunmallya/073d44d7e9a3bc925444d1e247c1e8da

**Comment by lucabergamini** [comment]
I think it should work the same as indexing with a LongTensor, which works for the above cases in the same way numpy does.
In fact the workaround I use in these cases is to employ ```torch.nonzero``` to convert the ByteTensor in a LongTensor to index the tensor as I expect.

**Comment by zou3519** [comment]
This has been fixed somewhere down the line:
```

In [1]: import torch
   ...:
   ...: A = torch.rand(4, 4)
   ...: An = A.numpy()
   ...:
   ...: idx = torch.ByteTensor([1, 0, 0, 1])
   ...: idxn = [True, False, False, True]
   ...:

In [2]: # Numpy indexing.
   ...: print('numpy')
   ...: print(An[idxn].shape)
   ...: print(An[:, idxn].shape)
   ...:
numpy
(2, 4)
(4, 2)

In [3]: # Torch indexing.
   ...: print('torch')
   ...: print(A[idx].size())
   ...: print(A[:, idx].size())
   ...:
torch
torch.Size([2, 4])
torch.Size([4, 2])
```
