### ISSUE TITLE
[quant][graph mode] convert float function aten function calls to quantized function calls

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24064]
## 🚀 Feature
For example:
    * dequant → conv → quant  -----> qconv
    * dequant → conv → bn → quant ----> qconvbn

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by raghuramank100** [comment]
This step also involves operator fusion, i.e we replace  q-> dq -> conv->relu->q->dq with q->qconvrelu->dq
