### ISSUE TITLE
[quant] Layout transform

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24066]
## 🚀 Feature
Eliminate [permute → contiguous → permute → contiguous] pattern

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by raghuramank100** [comment]
Useful even in the case of eager mode can be run as an optimization pass after eager mode quantization.

**Comment by z-a-f** [comment]
I am removing the 1.3 tag and adding the quantization one

**Comment by jerryzh168** [comment]
not needed anymore since we moved layout transformation inside the ops.
