### ISSUE TITLE
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by longcw** [pytorch/pytorch#2406]
The following code caused an error `RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 2)` in v0.2.0 while it worked well in v0.1.2. Is this a dimension bug in v0.2.0?
```python
torch.max(score_maps.view(n, n_scales, -1), 2) # score_map.size() = [n, n_scales, h, w]
```

**Comment by longcw** [comment]
It was caused by `squeeze(2)`. `torch.max` in v0.2.0 has the default parameter `keepdim=False`.

**Comment by attaullah** [comment]
for me it worked by adding **keepdim=True** argument to torch function call. Hope it may help anyone else having this kind of issue.
