### ISSUE TITLE
[quant] Graph mode quant - skip inserting observers for certain patterns

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24061]
## 🚀 Feature
Skip inserting observer for certain patterns like convbn, convbnrelu, convrelu (we need to make sure backend has these implementations) + quantizable ops list

**Comment by raghuramank100** [comment]
This is backend specific pass that gets called before the first step of graph mode quantization. Two APIs are needed:
1. getQuantizationPatterns(): List of patterns of float operators (conv->relu) (conv)  in order of precedence.
2. Check for patterns and insert observers only for matched pattern.

**Comment by jerryzh168** [comment]
this is done
