### ISSUE TITLE
Unable to use MKLDNN with an installation of full MKL

### ISSUE THREAD

**Issue by nehaljwani** [pytorch/pytorch#24070]
## 🐛 Bug

On setting `MKLDNN_THREADING=OMP:INTEL` and having a full installation of MKL (including intel-openmp), the CMake configure stage still fails with:
```
CMake Error at third_party/ideep/mkl-dnn/cmake/OpenMP.cmake:67 (message):
  Intel OpenMP runtime could not be found.  Please either use OpenMP runtime
  that comes with the compiler (via -DMKLDNN_THREADING={OMP,OMP:COMP}), or
  install Intel MKL / Intel MKL-ML (e.g.  scripts/prepare_mkl.sh)
```

This happens because `cmake/Modules/FindMKL.cmake` doesn't set `HAVE_MKL` to true.

**Comment by XiaobingSuper** [comment]
https://github.com/pytorch/pytorch/pull/22910 can solve this problem, you can try it. Thanks

**Comment by rgommers** [comment]
gh-22910 was merged, and I confirmed that building against Intel OpenMP with `MKLDNN_THREADING=OMP:INTEL` works as expected. So closing.
