### ISSUE TITLE
ATen ParallelOpenMP thread_num decision questions

### ISSUE THREAD

**Issue by linziyi96** [pytorch/pytorch#24080]
We have noticed some differences in calculating the num_threads to spawn in different ATen Parallel backends, which, as far as we have observed, may lead to degraded performance of OpenMP backend under some circumstances.

In the OpenMP version:
https://github.com/pytorch/pytorch/blob/e327df396564f937d17b5f28e2529229260c65bf/aten/src/ATen/ParallelOpenMP.h#L28
The logic seems to be: either do not parallel at all (if num < grain_size), or spawn as many as omp_get_max_threads() threads.

In other backends, e.g. Native:
https://github.com/pytorch/pytorch/blob/e327df396564f937d17b5f28e2529229260c65bf/aten/src/ATen/ParallelNative.h#L41-L44
The logic is likely something as: min(get_num_threads(), num / grain_size).

We noticed this problem because after upgrading our PyTorch (>= 1.1.0 in our experince), the DataLoader, with pin_memory=True, is saturating our 36C/72T cpus even with some very small datasets (CIFAR10, resize=32, batch_size=40) and with num_threads=1, however, with no significant training speed boost. Further investigation shows that the copy operation to the pinned memory behaves very differently between two releases. After looking at the code we conjecture that this is due to the overhead that OMP tries to spawn an unecessarily large number of threads for small CPU Tensors.

We installed both PyTorch from conda so we are not absolutely certain about the build options. However we provide some code snippets that may possibly reveal the aformentioned problem:

1. Simple comparisons on copy operation:

``` python
from sys import argv
import torch
print(torch.__version__)
from tqdm import tqdm

N = int(argv[1])

a, b = [torch.randn([N]) for _ in (0, 1)]
for _, i in tqdm(enumerate(range(1000000))):
  b.copy_(a)
```

``` bash
time python test.py 32767
```

> 1.1.0
> 1000000it [00:12, 83148.11it/s]
> 
> real    0m12.866s
> user    0m12.686s
> sys     0m0.154s

``` bash
time python test.py 32768
```

> 1.1.0
> 1000000it [00:07, 128799.44it/s]
> 
> real    0m8.696s
> user    4m43.088s
> sys     0m0.432s

``` bash
time OMP_NUM_THREADS=4 python test.py 32768
```

> 1.1.0
> 1000000it [00:08, 123182.80it/s]
> 
> real    0m9.168s
> user    0m33.244s
> sys     0m0.194s

``` bash
time python test.py 32768 # pytorch 1.0.1
```

> 1.0.1.post2
> 1000000it [00:53, 18525.88it/s]
> 
> real    0m55.207s
> user    0m54.584s
> sys     0m0.182s

``` bash
time python test.py 10000000 # pytorch 1.0.1, reduced iter number to 1000 to avoid insane running time
```

> 1.0.1.post2
> 1000it [00:18, 54.57it/s]
> 
> real    0m19.421s
> user    0m19.192s
> sys     0m0.195s

It shows that the cpu usage of copying a 32768-sized Tensor drastically increase to approx. 3600% compared to approx. 100% for a 32767-sized Tensor. Although there was indeed some performance gain, it is only comparable to that when OMP_NUM_THREADS is limited to 4.
In 1.0.1, there is no such problem for a much larger Tensor (of size 10M), although the performance was worse than 1.1.0 given the same size.

2. Data Loading test
``` python
from sys import argv
from tqdm import tqdm
import torch
from torch.utils.data import Dataset, DataLoader

class Dummy(Dataset):

  def __len__(self):
    return 1000000

  def __getitem__(self, idx):
    return torch.zeros([3, 32, 32])

loader = DataLoader(Dummy(), num_workers=int(argv[1]), pin_memory=int(argv[2]), batch_size=int(argv[3]))
loader = iter(loader)
next(loader)
print(torch.__version__)
for _, im in tqdm(enumerate(loader)):
  pass
```

``` bash
time python test2.py 1 1 11
```

> 1.1.0
> 90909it [02:01, 748.58it/s]
> 
> real    2m7.478s
> user    22m20.561s
> sys     121m57.231s

``` bash
time python test2.py 1 0 11
```

> 1.1.0
> 90909it [00:47, 1894.42it/s]
> 
> real    0m49.030s
> user    1m5.537s
> sys     0m24.925s
> 

``` bash
time python test2.py 1 1 10
```

> 1.1.0
> 99999it [01:09, 1439.45it/s]
> 
> real    1m14.376s
> user    1m37.910s
> sys     0m39.113s

``` bash
time OMP_NUM_THREADS=1 python test2.py 1 1 11
```

> 1.1.0
> 90909it [00:58, 1551.88it/s]
> 
> real    1m3.575s
> user    1m26.514s
> sys     0m34.365s

We could observe that: 1) Dataloader with pin_memory=True and num_workers=1 leads to approx. 7200% cpu usage, and most time is in sys, and real speed is slower; 2) operations that avoid the multi-threaded copy (disable pin_memory, reduce batch_size or set 
 OMP_NUM_THREADS) could reduce the cpu usage, indicating that the problem is very possibly related to the copy operation.

However we have not yet submitted any PR for this, because we are not sure e.g. whether this is some side-effect of more important 'features', or whether the team is planning for a refactoring of the relevant code, etc. If it does need a fix, we are happy to provide one.

**Comment by ezyang** [comment]
cc @ilia-cher

**Comment by ilia-cher** [comment]
Unless you build PT from the source with specific build options, PT uses OpenMP by default, so the difference between Native and OpenMP backends should not apply to you.

**Comment by ezyang** [comment]
@ilia-cher This still seems like a problem, though? (Just that the bug is elsewhere)

**Comment by ilia-cher** [comment]
@ezyang, I'll take a closer look but we did not change the logic ``#pragma omp parallel if (!omp_in_parallel() && ((end - begin) >= grain_size))`` for OpenMP

**Comment by linziyi96** [comment]
I'm sorry the description is kind of overwhelming... Trying to be clear:

1) The direct problem is that DataLoader with pin_memory=True in 1.1.0 is using all cpu cores at 100%. That interferes with the other programs on the same machine. But when the program is consuming small batches (CIFAR10, 40 * 3 * 32 * 32) at moderate speed (~20 batch / second). I assume loading such data does not need 72 cores running at full speed ...

btw if I run the dataloader alone (no other process and no other computation in the same program), the new (1.1.0) still runs slower than the old (1.0.1). (600 b/s vs 900 b/s on 40 * 3 *32 * 32, 30 b/s vs 40 b/s on 40 * 3 * 224 * 224)

2) As for the different behaviors of copy operations, I further noticed that although 1.0.1 is shipped with OMP, but it looks like the copy operator is not triggering OMP for some reasons. For the operators that use OMP in 1.0.1, the sudden increase of cpu usage w.r.t input size could still be observerd (e.g. matmul, the threshold is between 50 * 50 and 60 * 60).

So AFAIK this is indeed not caused by the change of `#pragma omp parallel if (!omp_in_parallel() && ((end - begin) >= grain_size))`, but with the copy operator itself

Finally some questions / discussions about the fix:

1) For the DataLoader problem, do you think we need to fix the DataLoader itself or the copy operator, i.e. should we implement a 'lightweight' copy specifically for DataLoader moving data to pin_memory (a little slower is ok but do not use too much cpu), or shall we optimize the copy operator itself (I'm not an expert but I suppose it doesn't need all cores running to make full use of memory bandwidth)?

2) In a more general consideration, a gradual increase of num_threads based on input size (instead of either 1 or all) may still benefit in some systems with many cpu cores.

**Comment by peterbell10** [comment]
There was a significant change to the copy kernel between `1.0.1` and `1.1.0`. This happened in commit 465799fab36e81e4aba6bf4d3c1fcd03a3a10f57 which moves it over to using `TensorIterator`. 

It seems that prior to this change, the copy operation was not actually distributed across threads. With pytorch 1.0.1 installed from `conda` I only ever see one thread light up for `b.copy_(a)`, even when far above the grain size. So it would seem the performance regression is caused by a bug fix.

>In a more general consideration, will a gradual increase of num_threads based on input size (instead of either 1 or all) still benefit in some systems with many cpu cores? (as what's done in the Native backend)

I think this is a the best solution, it's even in agreement with the comment on `GRAIN_SIZE`:
>no parallel algorithm (such as parallel_reduce) should split work into smaller than GRAIN_SIZE chunks.

**Comment by soumith** [comment]
reopening because the PR was reverted. Context is in the original PR
