### ISSUE TITLE
RuntimeError: "eye" not implemented for 'Bool' when on CPU

### ISSUE THREAD

**Issue by santient** [pytorch/pytorch#24088]
## 🐛 Bug
torch.eye doesn't work for dtype torch.bool when the device is CPU, but it does work on GPU. 

## To Reproduce
>>> torch.eye(5, dtype=torch.bool, device=torch.device("cpu"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "eye" not implemented for 'Bool'

>>> torch.eye(5, dtype=torch.bool, device=torch.device("cuda"))
tensor([[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]], device='cuda:0')

## Expected behavior
I was expecting torch.eye for bool to be implemented for both CPU and CUDA. Maybe there are other torch functions with this issue as well?

## Environment
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 430.40
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] Could not collect

 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 1060 (6GB)

## Additional context
I can workaround on CPU for now by casting to torch.bool after calling torch.eye.

**Comment by Balandat** [comment]
This would be nice to get fixed, given the changes to the bool mask behavior. 

@sdaulton
