### ISSUE TITLE
Should treat CPU as one of the CUDA device?

### ISSUE THREAD

**Issue by xuancong84** [pytorch/pytorch#2408]
Currently, torch.cuda.set_device(-1) performs no operation.
To be more systematic, I think it would be more convenient to treat cpu as one of the cuda devices, so that after executing torch.cuda.set_device(-1), Tensor.cuda() will transfer the data into CPU memory.

Otherwise, every time we need to call object.data.new().zero_() in order to allocate an object in the same device. This is because the object can be in any GPU memory or CPU memory, but the function calls are different between GPU and CPU.

**Comment by soumith** [comment]
this is an explicit choice that we made in the library. The performance characteristics on the CPU and the GPU are wildly different, and transfers are even more bottlenecky. Our worry is that making the API more magical will make the performance magically degrading.

**Comment by xuancong84** [comment]
I am not convinced that making this change will degrade performance dramatically. I hope you can give me an example to convince me.
The data transfer speed among CPU and GPUs varies depends on how fast the hardware technology evolves. Everyone knows that data transfer between CPU and GPUs is costly, but when someone do call function in this way, `torch.cuda.set_device(-1)`, we assume he knows what he is doing.

**Comment by apaszke** [comment]
Having `.cuda()` transfer data to CPU would be extremely misleading. I think it might be worth to have a `to_current_device()` method at some point (perhaps after closer integration with AMD hw) with CPU being one of the devices, but not right now.

**Comment by xuancong84** [comment]
Exactly, should use Tensor.to_current_device()  instead.
And allow torch.cuda.set_device() to take tensor object as argument, so that you can set device to that tensor object. But if that tensor object is in CPU memory, then you encounter the same problem.

Then you need to do something as torch.device.set_device().

I am not sure what you guys are thinking. But it is obviously that the original design was not very elegant. And you cannot easily **create a tensor object in a device that is the same device as a given tensor object.**

**Comment by apaszke** [comment]
That's not true. You can do `tensor.new(constructor_args)` to create a new tensor on the same device as `tensor`
