### ISSUE TITLE
Provide API for jit::scripr::Module inspection

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#24091]
## 🚀 Feature
Currently jit::scripr::Module objects are used to represent models, containing methods, parameters/ attributes/etc, but there is no easy way to traverse this structure in C++.

## Motivation

This feature would be useful for people trying to operate on JIT IR, to add a new pass or model transformation.

**Comment by ZolotukhinM** [comment]
cc @suo

**Comment by suo** [comment]
Not sure I understand—why is `get_method`, `find_method`, and similar not enough?

**Comment by ZolotukhinM** [comment]
It's kind of enough but not very convenient. For instance, `get_parameters` returns a `slot_list`. I doubt an external user who wants to inspect their module would find it obvious how to actually use this method. `get_parameter`/`find_parameter` doesn't help much if you for some reason don't know the name of parameter (I consciously switched from methods to parameters in this example as I think it's easier to not know them).

And just to be clear, this feature is not about rewriting the whole class or something like this, it's about making its API more user-friendly. Ultimately it might mean just documenting it better.

**Comment by ZolotukhinM** [comment]
I think with addition of `torch::jit::script::Module::dump()` it became better:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/module.h#L207-L210
