### ISSUE TITLE
Add Transformer-XL module to torch.nn

### ISSUE THREAD

**Issue by santient** [pytorch/pytorch#24094]
## 🚀 Feature
A module implementing Transformer-XL, as in the paper [Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context](https://arxiv.org/pdf/1901.02860.pdf)

## Motivation
Transformer-XL can overcome the fixed-length limitation in vanilla Transformers, making them more useful in tasks such as NLP.

**Comment by soumith** [comment]
we are not going to add more variants of Transformer in PyTorch -- atleast not yet.
Things like Transformer-XL and ResNet are in their domain-specific libraries.
Open an issue for this feature-request in https://github.com/pytorch/text

**Comment by Evpok** [comment]
Honestly it is a better idea to use https://github.com/huggingface/pytorch-transformers for now. The API is quite nice, they support loading pretrained tf models and the speed at which they add new variants is frightening (usually less than two days after a paper hits the arXiv)
