### ISSUE TITLE
pytorch forced to use cuda 10 after new update

### ISSUE THREAD

**Issue by mgriffin-c-cs** [pytorch/pytorch#24093]
## 🐛 Bug
When installing pytorch with conda in a new environment, it always installs compiled with the cuda version 10 and cudatoolkit=10.0. Whether I conda install pytorch 1.2, 1.1, 1.0.1, or 1.0 with cuda90 it always tries to install the cuda 10 version of the package as well as cudatoolkit=10.0. This is via the pytorch conda channel. My machine has an older driver version that can't easily be upgraded. I also tried pip installing from https://download.pytorch.org/whl/cu90/stable and it still insists on using cuda 10.

## To Reproduce
conda create --name test_env python=3.6
conda activate test_env
conda install pytorch=1.1 cuda90 -c pytorch
conda list

In python when you run torch.version.cuda it also lists cuda 10.

The following NEW packages will be INSTALLED:

    blas:           1.0-mkl
    cffi:           1.12.3-py36h2e261b9_0
    cuda90:         1.0-h6433d27_0                        pytorch
    cudatoolkit:    10.0.130-0
    intel-openmp:   2019.4-243
    libgfortran-ng: 7.3.0-hdf63c60_0
    mkl:            2019.4-243
    mkl_fft:        1.0.12-py36ha843d7b_0
    mkl_random:     1.0.2-py36hd81dba3_0
    ninja:          1.9.0-py36hfd86e86_0
    numpy:          1.16.4-py36h7e9f1db_0
    numpy-base:     1.16.4-py36hde5b4d6_0
    pycparser:      2.19-py36_0
    pytorch:        1.1.0-py3.6_cuda10.0.130_cudnn7.5.1_0 pytorch

Proceed ([y]/n)? n

## Expected behavior

Should be able to select the cuda version.

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 390.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by soumith** [comment]
the relevant command for pytorch 1.1 was `conda install pytorch=1.1 cudatoolkit=9.0 -c pytorch`

**Comment by soumith** [comment]
I need to update the "Old Versions" page.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch.github.io/commit/98f41eab2df3bfa0fccbfedebccaa5d624f13767
