### ISSUE TITLE
Save and load model

### ISSUE THREAD

**Issue by mjchen611** [pytorch/pytorch#2409]
I have trained a model, I want save it and then reload it and use it to produce the output for new image.

I have found the function  : torch.model('path') ,but when I reload it it always have problem.

Can anyone give me  some suggestions or a simple example?

Thank you so much.

**Comment by alykhantejani** [comment]
Hi @mjchen611 you can find information on the recommended way of saving models [here](http://pytorch.org/docs/master/notes/serialization.html#recommend-saving-models)

tl;dr
```python
torch.save(the_model.state_dict(), PATH)
```

then later:
```python
the_model = TheModelClass(*args, **kwargs)
the_model.load_state_dict(torch.load(PATH))
```
