### ISSUE TITLE
Behavior of "return NotImplemented" in __contains__ of class Tensor

### ISSUE THREAD

**Issue by CielAl** [pytorch/pytorch#24112]
## 🐛 Bug

The method `__contains__` of class Tensor returns the NotImplemented instead of raising one, which is confusing because the consequently, the boolean statement of [var in tensor] will be True if "var" is not numbers.Number or Tensor. 

## To Reproduce

`2 in torch.LongTensor([0,5,2,1,2])` is True
## Expected behavior
An exception should be raised
## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 411.31
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.3.0
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zou3519** [comment]
I can reproduce this with `"foo" in torch.LongTensor([0,5,2,1,2])`. We should fix this.

**Comment by tczhangzhi** [comment]
I guess the result of bool(NotImplemented) is mistaken for False. And here are some pieces of advice to fix it.

**Comment by gchanan** [comment]
the guidance for comparisons is to return, not throw; but I guess it doesn't apply here.  See e.g.:
https://stackoverflow.com/questions/878943/why-return-notimplemented-instead-of-raising-notimplementederror

**Comment by zou3519** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/24156 thanks to @tczhangzhi
