### ISSUE TITLE
Feature: tensor.disk()

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#24119]
## 🚀 Feature

Proposed abstraction:
```python
tensor = torch.Tensor([1, 2, 3])

# Similar to `.cpu()` and `.gpu()` include a disk specific tensor.
disk_tensor = tensor.disk('tensor.pt')

# Get the tensor shape quickly via something like `np.lib.format._read_array_header`.
disk_tensor.shape[1]

# Get the tensor `dtype` that's cached somewhere for fast access.
disk_tensor.dtype

# Delete the disk tensor off of disk.
disk_tensor.unlink()

# Move automatically from disk to a particular device. 
gpu_tensor = disk_tensor.to(torch.device('gpu:1')) 
```

## Motivation

Within our work, it's been useful to create an `OnDiskTensor` abstraction. The abstraction handles getting the shape quickly. It also allows our code to be invariant to the dataset's storage (i.e. the dataset could be defined in memory or disk). Finally, significantly simplifies the process of data loading.

**Comment by tczhangzhi** [comment]
Maybe you need `torch.save(tensor)`.

**Comment by PetrochukM** [comment]
@tczhangzhi Thanks for your commentary. That is not what I am looking for. 

Fast `shape` and `dtype` reads for on-disk tensors are far more important for me. Those parameters help to decide which tensors should be loaded by the `DataLoader` before they are loaded.

**Comment by soumith** [comment]
@PetrochukM we do support mmaped Tensors, I think that's what you are looking for.

```
x = torch.IntTensor(torch.IntStorage.from_file('file.bin', size=100))
```

References:
- https://discuss.pytorch.org/t/memory-mapped-tensor/8954/3
- https://pytorch.org/docs/master/storage.html?highlight=from_file#torch.FloatStorage.from_file

**Comment by pietern** [comment]
A tensor always has a dtype and a shape when initialized. If you need to read those before instantiating it, I'd use some other mechanism. Perhaps some kind of on disk dict that gives you the dtype, the shape, and a path to a file you can mmap per @soumith's instructions?

**Comment by PetrochukM** [comment]
@soumith Thanks for the suggestion. I didn't know about that. 

I wonder if there could be a lighter-weight interface for the above. I think that there is some work in this area already: https://github.com/pytorch/pytorch/issues/24915
