### ISSUE TITLE
libtorch 1.2.0 binaries are wrong version

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#24120]
Reported by @junjihashimoto. 

https://pytorch.org/ points to the nightly/ folder. But no binaries seem to exist in the non-nightly folder...

cc @ezyang @gchanan @soumith @yf225

**Comment by xuhdev** [comment]
This is for libtorch

**Comment by jerry73204** [comment]
The official link points to a 1.3.0-dev build. Change the link to find 1.2.0.
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.zip

It is for those who are hurry for binaries. I'm not sure if this link can be regarded as stable release.

**Comment by ezyang** [comment]
So, the set of binary URLs which we seem to have right now, are:

* https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.2.0.zip
* https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.2.0.zip
* https://download.pytorch.org/libtorch/cu100/cu100/libtorch-shared-without-deps-1.2.0.zip
* https://download.pytorch.org/libtorch/cu92/libtorch-shared-with-deps-1.2.0+cu92.zip
* https://download.pytorch.org/libtorch/cu92/libtorch-shared-without-deps-1.2.0+cu92.zip

We're missing a lot of other entries matrix. It looks like I will need to do a proper binary build for these.

**Comment by VivekPanyam** [comment]
@ezyang Do you have an estimate for when the rest of the builds should be ready?

**Comment by ezyang** [comment]
^- @yf225

**Comment by yf225** [comment]
This is the full list of download links:
Linux CPU:
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-static-without-deps-1.2.0.zip

Linux CUDA 9.2:
https://download.pytorch.org/libtorch/cu92/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-static-without-deps-1.2.0.zip

Linux CUDA 10.0:
https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-static-without-deps-1.2.0.zip

macOS CPU:
https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.2.0.zip

**Comment by VivekPanyam** [comment]
Thanks!

**Comment by LaurentMazare** [comment]
Thanks @yf225 !

**Comment by jerry73204** [comment]
The link on pytorch.org is still incorrect. Please make corresponding changes. Thanks.

**Comment by junjihashimoto** [comment]
I am trying to use the binary of https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.2.0.zip.
It does not include `ATen/quantized/Quantizer.h`.
Is this right?
I can not find any instances of `struct Quantizer`.

**Comment by yf225** [comment]
@junjihashimoto If I understand correctly, this is expected. cc. @gchanan @soumith

**Comment by yf225** [comment]
@junjihashimoto Quantizer is not released as part of 1.2, as it still needs improvement.

**Comment by junjihashimoto** [comment]
It is OK. Thx!

**Comment by yf225** [comment]
@jerry73204 Links on pytorch.org are fixed as well.

**Comment by jerry73204** [comment]
Thanks!

**Comment by junjihashimoto** [comment]
Congratulations on the release of 1.3.
The title remains stable1.2.

**Comment by ezyang** [comment]
@junjihashimoto should be fixed now I think
