### ISSUE TITLE
ONNX model zoo MaskRCNN model inference failure

### ISSUE THREAD

**Issue by pkhigh** [pytorch/pytorch#24149]
## 🐛 Bug

UserWarning: This version of onnx-caffe2 targets ONNX operator set version 9, but the model we are trying to import uses version 10.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.
  warnings.warn("This version of onnx-caffe2 targets ONNX operator set version {}, but the model we are trying to import uses version {}.  We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.".format(cls._known_opset_version, imp.version))

ONNX FATAL: Don't know how to translate op Resize
ONNX FATAL: Don't know how to translate op NonMaxSuppression
ONNX FATAL: Don't know how to translate op RoiAlign
RuntimeError: ONNX conversion failed

Caffe2 is not able to support most of the operations of object detection.

## To Reproduce

import onnx
import caffe2.python.onnx.backend
import os
import glob
import numpy as np
from onnx import numpy_helper

#model paths
model = onnx.load('mask_rcnn_R_50_FPN_1x.onnx')
test_data_dir = 'test_data_set_0'
#Prepare the backend
rep = caffe2.python.onnx.backend.prepare(model)

## Expected behavior
model should have been loaded without any error

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==0.3.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py36_cu100    pytorch

# additional information

I build onnx from source.
current version is : 1.5.0

**Comment by VolodymyrAhafonov** [comment]
Any updates?

**Comment by fmassa** [comment]
ONNX support for maskrcnn models in torchvision is being worked on, and will be supported in the coming months.

Cc @lara-hdr

**Comment by mathpopo** [comment]
ONNX FATAL: Don't know how to translate op Resize
ONNX FATAL: Don't know how to translate op NonMaxSuppression
Traceback (most recent call last):
  File "/home/Desktop/maskrcnn-benchmark-onnx_stage-gpu/demo/test_onnx.py", line 6, in <module>
    prepared_backend = caffe2.python.onnx.backend.prepare(model)
  File "/home/anaconda3/envs/pytorch1.2gpu/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 712, in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
  File "/home/anaconda3/envs/pytorch1.2gpu/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 910, in _onnx_model_to_caffe2_net
    raise RuntimeError('ONNX conversion failed')
RuntimeError: ONNX conversion failed

**Comment by Li-chunming** [comment]
You can use the onnxruntime to do inference

**Comment by garymm** [comment]
You could try converting the model from opset 10 to opset 9 using [the ONNX version converter](https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md).

If that doesn't work, Caffe2 is no longer being worked on, and it seems like opset 10 support was never added, so you should try a different ONNX implementation e.g. ONNX Runtime or another listed here: <https://onnx.ai/supported-tools.html>
