### ISSUE TITLE
Unable to install 1.2

### ISSUE THREAD

**Issue by ZhuBaohe** [pytorch/pytorch#24141]
Whether using pip or conda, I still get 1.1  by  the official installation command.

![a](https://user-images.githubusercontent.com/35796307/62816025-bbdccc00-bb53-11e9-9941-ec31665fa591.jpg)

**Comment by peterjc123** [comment]
The windows binaries are not uploaded yet. Sorry for the delay.

**Comment by peterjc123** [comment]
If you need them immediately, then you can find them [here](https://dev.azure.com/peterjc123/_git/pytorch_builder/branches).

**Comment by peterjc123** [comment]
@soumith

**Comment by crazy-winds** [comment]
I downloaded a WHL of a different size each time, and the installation also reported an error

**Comment by crazy-winds** [comment]
I managed to install pytorch1.2, but I got torchvision times wrong

**Comment by Jonas1312** [comment]
torchvision 4.0 wheel not available on windows (yet)

**Comment by crazy-winds** [comment]
Which means it doesn't matter if I have pytorch1.2

**Comment by peterjc123** [comment]
`torchvision` won't be able to compile before these binaries are uploaded.

**Comment by FilipAndersson245** [comment]
Pytorch 1.2 just went live on conda for Windows

**Comment by Jonas1312** [comment]
here also https://download.pytorch.org/whl/cu100/torch-1.2.0-cp37-cp37m-win_amd64.whl

**Comment by stonebig** [comment]
when can we expect a torch-1.2.0-cp38-cp38m-win_amd64.whl ?

**Comment by FilipAndersson245** [comment]
Anyone knows when we can expect torchvision 0.4? (for Windows)

**Comment by Nikronic** [comment]
still unavailable on `pip`.

**Comment by peterjc123** [comment]
@stonebig  Not this time, maybe you can expect a `torch-1.3.0-cp38-cp38m-win_amd64.whl`.
@FilipAndersson245 It depends on how long we can figure out the build scripts. Hopefully, I could do it today.
@Nikronic It is available, but we didn't update the commands in the wizard. You could try something mentioned in @Jonas1312 's post.

**Comment by peterjc123** [comment]
Conda 
```bash
conda install pytorch cpuonly -c pytorch
conda install pytorch cudatoolkit=9.2 -c pytorch -c numba
conda install pytorch cudatoolkit=10.0 -c pytorch
```

Wheels
CPU
https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp35-cp35m-win_amd64.whl
https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-win_amd64.whl
https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp37-cp37m-win_amd64.whl

CUDA 9.2
https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp35-cp35m-win_amd64.whl
https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp36-cp36m-win_amd64.whl
https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp37-cp37m-win_amd64.whl

CUDA 10.0
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp35-cp35m-win_amd64.whl
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-win_amd64.whl
https://download.pytorch.org/whl/cu100/torch-1.2.0-cp37-cp37m-win_amd64.whl

**Comment by crazy-winds** [comment]
Pytorch1.2 and torchvision0.3 cannot be used together.


Traceback (most recent call last):
  File "E:/Program Files/Game/a.py", line 2, in <module>
    import torchvision
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "E:\ANACONDA\envs\PyTorch\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: 找不到指定的模块。

**Comment by peterjc123** [comment]
@crazy-winds Yes, I'm building torchvision. You'll have to wait until torchvision 0.4.0 is ready.

**Comment by peterjc123** [comment]
Torchvision binaries are uploaded [here](https://dev.azure.com/peterjc123/_git/pytorch_builder/branches). 
We will close this issue after they are uploaded to the official channel.

**Comment by stonebig** [comment]
can't see cpu torch-1.2 for windows, is it coming too ?

**Comment by peterjc123** [comment]
@stonebig It's uploaded, but the commands are not updated. We will have to wait.

**Comment by stonebig** [comment]
ok

**Comment by peterjc123** [comment]
Refer to this [post](https://github.com/pytorch/pytorch/issues/24141#issuecomment-520191101) if you want to try them out quickly.

**Comment by crazy-winds** [comment]
> Torchvision 0.4.0 binaries are uploaded [here](https://dev.azure.com/peterjc123/_git/pytorch_builder/branches).
> We will close this issue after they are uploaded to the official channel.

Thank you. I've solved it now.
Where do I start with the pytorch, I don't know much about the official website, for example, where do engine and utils come from.

**Comment by peterjc123** [comment]
All Windows commands should now be live and working.
