### ISSUE TITLE
Nightly installation shows `__version__ = '1.2.0'`

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#24152]
By following the instructions at https://pytorch.org/get-started/locally/  (Nightly, Linux, Pip, Python 3.7, 9.2), a PyTorch instance with `__version__ = '1.2.0'` is installed. But from its available features, it should be 1.2.0.

    pip install torch -f https://download.pytorch.org/whl/nightly/cu92/torch.html

**Comment by ezyang** [comment]
@jerryzh168 wrong distributions; the distributions label refers to torch.distributions (our probability distributions module!)

**Comment by xuhdev** [comment]
Can we close this issue now if it is fixed?
