### ISSUE TITLE
Implement torch.uniform

### ISSUE THREAD

**Issue by renesax14** [pytorch/pytorch#24162]
## 🚀 Feature
sample uniform vectors

## Motivation

Have a out of the box uniform samples

## Pitch

`x = torch.uniform(a,b)`

## code

```

def uniform(a,b):
'''
If U is a random variable uniformly distributed on [0, 1], then (r1 - r2) * U + r2 is uniformly distributed on [r1, r2].
'''

u = (r1 - r2) * torch.rand(a, b) + r2
u = torch.FloatTensor(a, b).uniform_(r1, r2)
return u

```

**Comment by andyljones** [comment]
I think this already exists?

```python
a = torch.tensor([0., 10.])
b = torch.tensor([1., 11.])
torch.distributions.Uniform(a, b).sample()
>>> tensor([ 0.8583, 10.0226])
```

**Comment by jerryzh168** [comment]
Looks like it's resolved, I'm going to close the issue, feel free if you have more questions. @renesax14

**Comment by brando90** [comment]
> I think this already exists?
> 
> ```python
> a = torch.tensor([0., 10.])
> b = torch.tensor([1., 11.])
> torch.distributions.Uniform(a, b).sample()
> >>> tensor([ 0.8583, 10.0226])
> ```

This example is confusing me. What does uniform do when receiving tensors of size larger than 1x1 mean? Whats the behavior when they are greater than 1 dimension?

I saw the docs but they weren't helpful nor any example or discussion of the case you provides is given: https://pytorch.org/docs/stable/distributions.html#torch.distributions.uniform.Uniform

What I want is to replicate this numpy code:

```
xn = np.random.uniform(low=-1, high=1, size=(num_samples,Din))

```

**Comment by brando90** [comment]
> Looks like it's resolved, I'm going to close the issue, feel free if you have more questions. @renesax14

What is the point of creating a sampler object first btw?

**Comment by andyljones** [comment]
```
>>> import torch
>>> num_samples = 5
>>> Din = 3
>>> torch.distributions.Uniform(-1, +1).sample((num_samples, Din))
tensor([[ 0.4093,  0.0140, -0.0089],
        [ 0.0855,  0.6572, -0.1319],
        [ 0.8631, -0.9668,  0.1203],
        [ 0.7118,  0.8804,  0.9936],
        [-0.4022,  0.4623, -0.4967]])
```

I think the hangup is that you're thinking of the uniform distribution as occuring on an interval, when torch thinks of it as occuring on an interval/rectange/cuboid/etc. `low` gives one corner of the volume, `high` gives the other, `sample_shape` says how many samples you want from the volume. Output dims are `(*sample_shape, dim_of_params)`.

**Comment by brando90** [comment]
> ```
> >>> import torch
> >>> num_samples = 5
> >>> Din = 3
> >>> torch.distributions.Uniform(-1, +1).sample((num_samples, Din))
> tensor([[ 0.4093,  0.0140, -0.0089],
>         [ 0.0855,  0.6572, -0.1319],
>         [ 0.8631, -0.9668,  0.1203],
>         [ 0.7118,  0.8804,  0.9936],
>         [-0.4022,  0.4623, -0.4967]])
> ```
> 
> I think the hangup is that you're thinking of the uniform distribution as occuring on an interval, when torch thinks of it as occuring on an interval/rectange/cuboid/etc. `low` gives one corner of the volume, `high` gives the other, `sample_shape` says how many samples you want from the volume. Output dims are `(*sample_shape, dim_of_params)`.

Fabulous! You are right. I get it now. Thanks! :D 

Btw, what is the use of creating a sampler? What is the disadvantage of (always) doing:

```
r2 = torch.torch.distributions.Uniform(low=lb, high=ub).sample((num_samples,Din))
```

**Comment by brando90** [comment]
> Those are equivalent, use whatever syntax you prefer.
> 
> As to why there's a class at all rather than just a function, there's a link at the top of the distributions docs page [to a giant pile of design philosophy](https://arxiv.org/abs/1711.10604). TL;DR it's so you can transform/compose/cache/etc distributions.

Oh interesting.

Just to make sure I understand an interesting use case. One can generate these samplers and differentiate through them? (somehow)

That sounds very interesting.

**Comment by brando90** [comment]
> ## 🚀 Feature
> sample uniform vectors
> 
> ## Motivation
> Have a out of the box uniform samples
> 
> ## Pitch
> `x = torch.uniform(a,b)`
> 
> ## code
> ```
> 
> def uniform(a,b):
> '''
> If U is a random variable uniformly distributed on [0, 1], then (r1 - r2) * U + r2 is uniformly distributed on [r1, r2].
> '''
> 
> u = (r1 - r2) * torch.rand(a, b) + r2
> u = torch.FloatTensor(a, b).uniform_(r1, r2)
> return u
> ```

hope this solves this issue: https://stackoverflow.com/questions/44328530/how-to-get-a-uniform-distribution-in-a-range-r1-r2-in-pytorch/62919760#62919760
