### ISSUE TITLE
Transformer model seems not supported in TorchScript?

### ISSUE THREAD

**Issue by jotline** [pytorch/pytorch#24173]
## 🐛 Bug
```python
Python builtin <built-in function hasattr> is currently not supported in Torchscript:
at /home/chejin/anaconda3/envs/pytorch-gpu/lib/python3.6/site-packages/torch/nn/modules/activation.py:759:12
        - key_padding_mask: :math:`(N, S)`, ByteTensor, where N is the batch size, S is the source sequence length.
        - attn_mask: :math:`(L, S)` where L is the target sequence length, S is the source sequence length.

        - Outputs:
        - attn_output: :math:`(L, N, E)` where L is the target sequence length, N is the batch size,
          E is the embedding dimension.
        - attn_output_weights: :math:`(N, L, S)` where N is the batch size,
          L is the target sequence length, S is the source sequence length.
        """
        if hasattr(self, '_qkv_same_embed_dim') and self._qkv_same_embed_dim is False:
           ~~~~~~~ <--- HERE
            return F.multi_head_attention_forward(
                query, key, value, self.embed_dim, self.num_heads,
                self.in_proj_weight, self.in_proj_bias,
                self.bias_k, self.bias_v, self.add_zero_attn,
                self.dropout, self.out_proj.weight, self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask, need_weights=need_weights,
                attn_mask=attn_mask, use_separate_proj_weight=True,
                q_proj_weight=self.q_proj_weight, k_proj_weight=self.k_proj_weight,'__module__.__torch__.torch.nn.modules.activation.MultiheadAttention.forward' is being compiled since it was called from '__modul
e__.__torch__.torch.nn.modules.transformer.TransformerEncoderLayer.forward'
```
## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torchtext==0.3.1
[conda] _tflow_select             2.3.0                       mkl    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] cuda100                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243    defaults
[conda] mkl_fft                   1.0.12           py36ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py36hd81dba3_0    defaults
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] tensorflow                1.14.0          mkl_py36h2526735_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] tensorflow-base           1.14.0          mkl_py36h7ce6ba3_0    defaults

**Comment by eellison** [comment]
@driazati the `nn.functional` function is supported in torchscript but looks like this never got tests for the module added
