### ISSUE TITLE
Pip install error in python 3.7 on Debian

### ISSUE THREAD

**Issue by OriolAbril** [pytorch/pytorch#24179]
## 🐛 Bug

Installation of pytorch cpu-only fails in python 3.7.

## To Reproduce

I tried to install pytorch following the instructions on the website:

    pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

And got the error:

    ERROR: Could not find a version that satisfies the requirement torch==1.2.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
    ERROR: No matching distribution found for torch==1.2.0+cpu

I tried to use the linux wheel directly:

    pip install https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp37-cp37m-manylinux1_x86_64.whl

and got:

    ERROR: torch-1.2.0+cpu-cp37-cp37m-manylinux1_x86_64.whl is not a supported wheel on this platform.

I have also tried installing other versions of pytorch with the same luck. I have repeated the same steps changing the pytorch version to 1.1.0 and 1.0.1 (and updating the wheels to the corresponding name in https://download.pytorch.org/whl/torch_stable.html).

## Expected behavior

Pytorch is installed.

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0 (and others)
 - OS (e.g., Linux): debian
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.7.4
 - CUDA/cuDNN version: -
 - GPU models and configuration: -
 - Any other relevant information:

```
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
```

## Additional context

I don't think this is relevant, but I am working inside a docker container. Installation with conda works.

**Comment by ezyang** [comment]
I ran this on Python 3.7.3 and it worked:

```
pip install --no-cache-dir torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.2.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp37-cp37m-manylinux1_x86_64.whl (103.9MB)
     |████████████████████████████████| 103.9MB 98.9MB/s 
Collecting torchvision==0.4.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.4.0%2Bcpu-cp37-cp37m-manylinux1_x86_64.whl (12.2MB)
     |████████████████████████████████| 12.2MB 18.0MB/s 
Requirement already satisfied: numpy in /data/users/ezyang/miniconda3/envs/scratch2/lib/python3.7/site-packages (from torch==1.2.0+cpu) (1.16.4)
Requirement already satisfied: pillow>=4.1.1 in /data/users/ezyang/miniconda3/envs/scratch2/lib/python3.7/site-packages (from torchvision==0.4.0+cpu) (6.1.0)
Requirement already satisfied: six in /data/users/ezyang/miniconda3/envs/scratch2/lib/python3.7/site-packages (from torchvision==0.4.0+cpu) (1.12.0)
Installing collected packages: torch, torchvision
Successfully installed torch-1.2.0+cpu torchvision-0.4.0+cpu
(scratch2) [ezyang@devgpu005.ash6 ~/Dev/pytorch-tmp] pip --version
pip 19.1.1 from /data/users/ezyang/miniconda3/envs/scratch2/lib/python3.7/site-packages/pip (python 3.7)
```

If you could share the Docker image you're using that would be helpful. Are you 32-bit by any chance?

**Comment by ezyang** [comment]
alternately, could you run

```
python -c "from wheel import pep425tags;print(pep425tags.get_supported())"
```

and tell us what the output is?

**Comment by OriolAbril** [comment]
I am on a 64-bit.

The output of this last command is:

```
[('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64'), ('cp37', 'abi3', 'linux_x86_64'), 
('cp37', 'none', 'linux_x86_64'), ('cp36', 'abi3', 'linux_x86_64'), 
('cp35', 'abi3', 'linux_x86_64'), ('cp34', 'abi3', 'linux_x86_64'), 
('cp33', 'abi3', 'linux_x86_64'), ('cp32', 'abi3', 'linux_x86_64'),
('cp37', 'none', 'any'), ('cp3', 'none', 'any'), ('cp36', 'none', 'any'), 
('cp35', 'none', 'any'), ('cp34', 'none', 'any'), ('cp33', 'none', 'any'), 
('cp32', 'none', 'any'), ('cp31', 'none', 'any'), ('cp30', 'none', 'any'), 
('py3', 'none', 'linux_x86_64'), ('py37', 'none', 'any'), ('py3', 'none', 'any'), 
('py36', 'none', 'any'), ('py35', 'none', 'any'), ('py34', 'none', 'any'), 
('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), 
('py30', 'none', 'any')]
```

**Comment by OriolAbril** [comment]
Also, if it helps, I am using pip 19.1.1, setuptools 41.0.1 and wheel 0.33.4. 

Also, I emphasize that I have installed with conda and used pytorch in this same docker, same machine, same everything without any problem. Otherwise I would have though I was missing a requirement or something like this instead of this being a bug.

**Comment by ezyang** [comment]
There is something wrong with your Python distribution. `('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')` is the tag which should let you select our wheel, but for whatever reason there is a macro that is not expanded. Maybe there is a way to force pip to install a wheel anyway; if there is, that will probably work as a workaround. You'll need to report a bug to whatever your upstream distributor is to make pip installs work; any other packages that depend on cp37 ABI will also not be working on your system.

**Comment by ezyang** [comment]
The likely upstream issue is https://github.com/ContinuumIO/anaconda-issues/issues/11195

**Comment by OriolAbril** [comment]
Thanks a lot!

**Comment by alexwennerberg** [comment]
I'm also encountering this issue on python 3.8.0 using this base image: https://github.com/docker-library/python/blob/0b1fb9529c79ea85b8c80ff3dd85a32a935b0346/3.8/buster/slim/Dockerfile
