### ISSUE TITLE
Error caffe2.python when tried importing SummaryWriter from torch.utils.tensorboard

### ISSUE THREAD

**Issue by nobodykid** [pytorch/pytorch#24175]
## 🐛 Bug

I'm currently having a problem whenever I tried importing `SummaryWriter` in my Python script. 

## To Reproduce

I'm currently using the Data Science VM provided by Azure to run the Python. I used clean new env in Anaconda for installing Pytorch and all library dependencies (and also tb-nightly as instructed in [here](https://pytorch.org/docs/stable/tensorboard.html)).

I tried to inspect if my code could use the Tensorboard using simple line of codes like
```
import torch
from torch.utils.tensorboard import SummaryWriter
```
But I got this warning, and then critical message here

![image](https://user-images.githubusercontent.com/12664445/62860613-de750d80-bd2a-11e9-86bf-7c00bfa2add5.png)

## Expected behavior

As far as I know, everything should be good if I followed the instruction correctly. I also tried to reproduce the error in my local Windows PC. But no errors showed up

## Environment
 - PyTorch Version : 1.2.0
 - OS : Linux 16.04
 - How you installed PyTorch : conda
 - Python version: Python 3.6
 - CUDA/cuDNN version : CUDA 10 / cudnn 7.4
 - GPU models and configuration: 2 Tesla K80
 - Any other relevant information: This problem occurs on a VM machine deployed in Azure

**Comment by lanpa** [comment]
Can you try only `import caffe2` and see the result? Thanks

**Comment by nobodykid** [comment]
I didn't get any errors importing caffe. The error only appeared when I start importing SummaryWriter from `torch.utils.tensorboard`

![image](https://user-images.githubusercontent.com/12664445/62911421-8253cd00-bdae-11e9-8f84-2b346821acd9.png)

**Comment by pietern** [comment]
Do you perhaps have an older version of caffe2 installed globally? The path /opt/caffe2 makes me think there is something else installed on your machine that is interfering with your PyTorch installation.

**Comment by soumith** [comment]
Also reported here: https://github.com/pytorch/pytorch/issues/15618#issuecomment-521027519

@lanpa @orionr we should not be importing `caffe2.python` in `torch.utils.tensorboard`, was this an oversight? Please fix this dependency asap so that nightlies are fixed.

**Comment by orionr** [comment]
The multiple Caffe2 versions wasn't expected here, but we shouldn't import caffe2 unless we need to within `torch.utils.tensorboard`. A PR put up to that effect.

**Comment by AlejandroTL** [comment]
Hello,

I'm facing same error here. I do not work with `caffe2` but it is needed for the function `add_scalars`, how should I fix this? I do not have `caffe2` installed, of course. 
```
tensorboard               2.11.0             pyhd8ed1ab_0    conda-forge
torch                     1.13.1                   pypi_0    pypi
```

**Comment by tungts1101** [comment]
I am facing the same issue. However, when I tried to install `caffe2` separately, I got this error `ModuleNotFoundError: No module named 'tools.setup_helpers'`.

**Comment by tungts1101** [comment]
In the source code of tensorboard, some parts import caffe2 as dependencies. Please remove or notify the wrong errors with `add_scalar` method.
