### ISSUE TITLE
Pytorch 1.2.0 RuntimeError: code is too big

### ISSUE THREAD

**Issue by ahmed-fau** [pytorch/pytorch#24174]
Hi,

I am using the latest stable version of Pytorch (1.2.0) to train and test a model. For testing, I map the trained model to the CPU and run there. However, I get the following error:

`RuntimeError: code is too big`

Could anybody let me know what is the main reason for such an error or at least what is the meaning of it? Unfortunately, I could not diagnose the problem based on this limited error message.

This issue only happens when I run on the CPU, with GPU everything is fine. I was thinking it is a RAM issue. However, this error occurs on a workstation of 64 Giga RAM (hp workstation Z4 G4 xeon w-2123) and it disappears when I run on a normal computer of 8 Giga RAM (intel core i7).  

Many thanks in advance

**Comment by ezyang** [comment]
This error comes from MKL DNN. @gujinghui or someone else, could you please take a look?

**Comment by ahmed-fau** [comment]
Thanks a lot for replying. Do you have a reason why this happens on a workstation's CPU (hp workstation z4 g4 xeon w-2123) whereas it does not occur for normal CPU (e.g. intel core i7)?
Is there any hack to go around?

Best

**Comment by vpirogov** [comment]
@ahmed-fau,

The key different between these two processors is that the workstation has Intel AVX-512 support, while "the normal computer" does not. Could you please collect logs with `MKLDNN_VERBOSE=1`?

**Comment by ahmed-fau** [comment]
@vpirogov is this done by running my script from cmd with `MKLDNN_VERBOSE=1`?
e.g.: `python3 my_model.py MKLDNN_VERBOSE=1`

**Comment by ahmed-fau** [comment]
@vpirogov  OK, I tried the following from the command line:
`export MKLDNN_VERBOSE=1
python3 my_model.py`

And got the following: 

`mkldnn_verbose,info,Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20),Intel(R) Advanced Vector Extensions 512 (Intel(R) AVX-512) with AVX512BW, AVX512VL, and AVX512DQ extensions
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_oihw out:f32_Ohwi16o,num:1,16x1x1x32,0.00292969
mkldnn_verbose,exec,convolution,jit:avx512_common,forward_training,fsrc:nchw fwei:Ohwi16o fbia:undef fdst:nChw16c,alg:convolution_direct,mb1_ic1oc16_ih1oh1kh1sh1dh0ph0_iw16030ow8000kw32sw2dw0pw0,0.232178
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nChw16c out:f32_nchw,num:1,1x16x1x8000,0.26001
Traceback (most recent call last):
  File "my_model.py", line 200, in <module>
    o= g(z)
  File "/home/amm-er/ahd/anaconda3/envs/amustenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "my_model.py", line 158, in forward
    enc2= self.enc2(self.pad2(enc1_out))
  File "/my_home/anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/my_home/my_model.py", line 72, in forward
    return self.module.forward(*args)
  File "/my_home/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 200, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: code is too big`

**Comment by vpirogov** [comment]
@ahmed-fau,

Thank you for the data. It looks like the error is thrown before verbose output is printed in this case. Would you be able to extract convolution shapes from the model?

**Comment by ahmed-fau** [comment]
Actually, this error is thrown at different locations of the code. It is not a specific line of the model implementation which causes this error. When I repeat running, I got the same error message at different lines. They are 1D convolutional layers without special implementation detail.

**Comment by vpirogov** [comment]
Thanks, this helps. After fiddling with the list of shapes I can reproduce it now with [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn), Intel MKL-DNN's comprehensive performance and validation suite.

**Comment by vpirogov** [comment]
Resolved in https://github.com/intel/mkl-dnn/commit/ddaf3cc23128678259b1716a961c51c320d11caa. We will release v0.20.2 shortly that includes this fix.

**Comment by ahmed-fau** [comment]
@vpirogov Cool, thanks!
Could you also share how to update this library when you release the new version?

**Comment by vpirogov** [comment]
The fix is released in [Intel MKL-DNN v0.20.2](https://github.com/intel/mkl-dnn/releases/tag/v0.20.2). 

@gujinghui, jgong5, could you please help with instruction on building Pytorch with updated Intel MKL-DNN?

**Comment by XiaobingSuper** [comment]
@ahmed-fau , we will pull a new patch to upgrade MKL-DNN. Locally, you can use the new version MKL-DNN by runnng: 
`cd pytorch/third_party/ideep/mkl-dnn/ && git pull && git checkout v0.20.2` 
and then build pytorch normlly, please tell me if you still face this problem and you can post your script which I can reproduce it. Thanks!

**Comment by ahmed-fau** [comment]
@XiaobingSuper  thanks! I tried to use the commands you have provides but actually the `git pull` command did not work. Alternatively, I have tried to directly download the source code of [v0.20.0](https://github.com/intel/mkl-dnn/releases/tag/v0.20.2), uninstall the torch library I got it via conda and instead rebuild Pytorch from the source using `setup.py` (with keeping all configuration flags untouched. After the installation completed, I got the following error when I tried `import torch `:
`python: symbol lookup error: /my_home/myenv/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: _Z11libshm_initPKc`

**Comment by XiaobingSuper** [comment]
@ahmed-fau, sorry, it is my mistake, the command should be: `cd pytorch/third_party/ideep/mkl-dnn/ && git checkout master && git pull && git checkout v0.20.2`.
I can't see this problem, do you run `python setup.py clean` before you rebuild the source code? or you can create a new conda env to install pytorch. Thanks!

**Comment by ahmed-fau** [comment]
@XiaobingSuper  No, I didn't run `python setup.py clean` because I uninstalled pytorch from the `conda uninstall` utility. Is there a way to keep pytorch of conda and only checkout mkl-dnn and rebuild? I mean: don't build Pytorch from source as it is unstable and I need to work with version 1.2.

**Comment by ahmed-fau** [comment]
@XiaobingSuper here is the output from the last command you've provided:

`git checkout master && git pull && git checkout v0.20.2
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
error: pathspec 'v0.20.2' did not match any file(s) known to git.`

**Comment by XiaobingSuper** [comment]
Do you in third_party/ideep/mkl-dnn/  directory first, please see my log:

```
(pytorch-test) [xiaobinz@mlt-skx047 pytorch-offical]$ cd third_party/ideep/mkl-dnn/ && git checkout master && git pull && git checkout v0.20.2
Checking out files: 100% (1279/1279), done.
Previous HEAD position was 7de7e5d... bumped version to v0.18.1
Switched to branch 'master'
Already up-to-date.
Note: checking out 'v0.20.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 735eb7b... build: bumped version to v0.20.2
```

**Comment by XiaobingSuper** [comment]
> @XiaobingSuper No, I didn't run `python setup.py clean` because I uninstalled pytorch from the `conda uninstall` utility. Is there a way to keep pytorch of conda and only checkout mkl-dnn and rebuild? I mean: don't build Pytorch from source as it is unstable and I need to work with version 1.2.

I am confused, do you install pytorch by : `conda install pytorch torchvision cpuonly -c pytorch`  ?

**Comment by ahmed-fau** [comment]
> I am confused, do you install pytorch by : `conda install pytorch torchvision cpuonly -c pytorch` ?
 Firstly, yes. I installed torch via this conda command. After you have told me to checkout and rebuild pytorch, I found this is possible by running `setup.py` which is building from the source. That's why I uninstalled the conda version (torch 1.2 the stable one) and checked out the source code version (1.3 the unstable one).

My question is: would it be possible to keep torch 1.2 of conda but just updated to adapt with you mkl-dnn newer version?

Sorry for this confusion

**Comment by ahmed-fau** [comment]
> Do you in third_party/ideep/mkl-dnn/ directory first, please see my log:
> 
> ```
> (pytorch-test) [xiaobinz@mlt-skx047 pytorch-offical]$ cd third_party/ideep/mkl-dnn/ && git checkout master && git pull && git checkout v0.20.2
> Checking out files: 100% (1279/1279), done.
> Previous HEAD position was 7de7e5d... bumped version to v0.18.1
> Switched to branch 'master'
> Already up-to-date.
> Note: checking out 'v0.20.2'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b new_branch_name
> 
> HEAD is now at 735eb7b... build: bumped version to v0.20.2
> ```

I have repeated everything and now I got the same log as you have. Shall I run `python setup.py clean --all / install`? this will install torch of version 1.3 which I don't use. Is it possible to apply the updates of mkl-dnn to torch 1.2 I have got with conda?

**Comment by XiaobingSuper** [comment]
@ahmed-fau , I don't think there a method which just build mkldnn new version. If you want pytorch 1.2.0, you can also build it from source:
1.  `pip uninstall torch`
2.  
```
cd pytorch && git checkout v1.2.0 && git submodule sync && 
git submodule update --init --recursive && cd third_party/ideep/mkl-dnn/ && git checkout master && git pull && git checkout v0.20.2
```
3.  `python setup.py clean && python setup.py install`

So you can use torch-1.2.0 satble version which is same as conda installed.

**Comment by ahmed-fau** [comment]
@XiaobingSuper  Hi,

I tried what you have described and the build process seems to work until it got stuck in building caffe due to a `permission denied` issue. Could you please let me know how to build for only my user id on Linux? I am also searching how to do that but still didn't get a possible answer. (i.e. run `setup.py` for building on my userspace only).

Best

**Comment by XiaobingSuper** [comment]
@ahmed-fau , you can also use pip to install pytorch:
`USE_NINJA=1 CFLAGS="-O0 -g" CXXFLAGS="-O0 -g"  pip install --user -v -e .`, if it is not work, can you post you build log which I can see the build failed reason? Thanks. please note I make some change in https://github.com/pytorch/pytorch/issues/24174#issuecomment-522643170

**Comment by ahmed-fau** [comment]
Thanks. The solution was to use `python setup.py build` before `python setup.py install`. Now pytorch 1.2.0 is being installed. I will check `import mkl; print(mkl.__version__)` to verify version `0.20.2` is what has been installed. The remaining thing now is to install a `cudatoolkit` of version `10.0` as I use an RTX GPU. Will report you asap.

**Comment by ahmed-fau** [comment]
@XiaobingSuper the build process continued until:
```[ 58%] Building CXX object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp.o```

then it has thrown the following error log:

```In file included from /home/amm-er/ahd/pytorch/third_party/ideep/include/ideep.hpp:43:0,  
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/MKLDNNCommon.h:7,  
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/BinaryOps.cpp:43:  
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp: In instantiation of ‘void ideep::param::init(const ideep::param::descriptor&) [with alloc = at::native::AllocForMKLDNN; computation_t = ideep::sum]’:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:1144:9:   required from ‘static void ideep::sum::compute(const scale_t&, const std::vector<ideep::tensor, std::allocator<ideep::tensor> >&, ideep::tensor&) [with alloc = at::native::AllocForMKLDNN; bool web_opt = false; ideep::scale_t = std::vector<float, std::allocator<float> >]’
/home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/BinaryOps.cpp:58:56:   required from here
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp:623:56: error: no matching function for call to ‘at::native::AllocForMKLDNN::malloc(size_t)’
     buffer_.reset(alloc::template malloc<computation_t>(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
         adesc.get_size()), alloc::template free<computation_t>);
         ~~~~~~~~~~~~~~~~~                               
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp: In instantiation of ‘void ideep::param::init(const ideep::param::descriptor&) [with alloc = at::native::AllocForMKLDNN; computation_t = ideep::eltwise_binary]’:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:6037:9:   required from ‘static void ideep::eltwise_binary::compute(ideep::eltwise_binary::eltwise_binary_op, ideep::tensor&, ideep::tensor&, ideep::tensor&) [with alloc = at::native::AllocForMKLDNN]’
/home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/BinaryOps.cpp:96:63:   required from here
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp:623:56: error: no matching function for call to ‘at::native::AllocForMKLDNN::malloc(size_t)’
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp: In instantiation of ‘void ideep::param::init(const ideep::param::descriptor&) [with alloc = at::native::AllocForMKLDNN; computation_t = ideep::eltwise_forward]’:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:4052:7:   required from ‘static void ideep::eltwise_forward::compute(ideep::key_t&, const ideep::tensor&, ideep::tensor&, ideep::algorithm, ideep::prop_kind, float, float) [with alloc = at::native::AllocForMKLDNN; bool web_opt = false; ideep::key_t = std::__cxx11::basic_string<char>; ideep::algorithm = mkldnn::algorithm; ideep::prop_kind = mkldnn::prop_kind]’
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:4100:28:   required from ‘static void ideep::eltwise_forward::compute(const ideep::tensor&, ideep::tensor&, ideep::algorithm, ideep::prop_kind, float, float) [with alloc = at::native::AllocForMKLDNN; bool web_opt = false; ideep::algorithm = mkldnn::algorithm; ideep::prop_kind = mkldnn::prop_kind]’
/home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/BinaryOps.cpp:88:78:   required from here
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp:623:56: error: no matching function for call to ‘at::native::AllocForMKLDNN::malloc(size_t)’
caffe2/CMakeFiles/torch.dir/build.make:2339: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/BinaryOps.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/BinaryOps.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/amm-er/ahd/pytorch/third_party/ideep/include/ideep.hpp:43:0,
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/MKLDNNCommon.h:7,
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/Conv.cpp:38:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp: In instantiation of ‘void ideep::param::init(const ideep::param::descriptor&) [with alloc = at::native::AllocForMKLDNN; computation_t = ideep::convolution_forward]’:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:1929:7:   required from ‘static void ideep::convolution_forward::compute_impl(ideep::key_t&, const ideep::tensor&, const ideep::tensor&, const ideep::tensor&, const dims&, ideep::tensor&, const dims&, const dims&, const dims&, const dims&, const scale_t&, const scale_t&, const scale_t&, const ideep::descriptor_group::attr_t&, Ts&& ...) [with alloc = at::native::AllocForMKLDNN; bool with_bias = true; Ts = {mkldnn::algorithm&, mkldnn::prop_kind&, mkldnn::padding_kind&}; ideep::key_t = std::__cxx11::basic_string<char>; ideep::param::dims = std::vector<int>; ideep::scale_t = std::vector<float, std::allocator<float> >]’
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:2053:32:   required from ‘static void ideep::convolution_forward::compute(ideep::key_t&, const ideep::tensor&, const ideep::tensor&, const ideep::tensor&, const dims&, ideep::tensor&, const dims&, const dims&, const dims&, const dims&, int, const scale_t&, const scale_t&, const scale_t&, const ideep::descriptor_group::attr_t&, ideep::algorithm, ideep::prop_kind, ideep::padding_kind) [with alloc = at::native::AllocForMKLDNN; ideep::key_t = std::__cxx11::basic_string<char>; ideep::param::dims = std::vector<int>; ideep::scale_t = std::vector<float, std::allocator<float> >; ideep::algorithm = mkldnn::algorithm; ideep::prop_kind = mkldnn::prop_kind; ideep::padding_kind = mkldnn::padding_kind]’
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:2089:19:   required from ‘static void ideep::convolution_forward::compute(const ideep::tensor&, const ideep::tensor&, const ideep::tensor&, const dims&, ideep::tensor&, const dims&, const dims&, const dims&, const dims&, int, const scale_t&, const scale_t&, const scale_t&, const ideep::descriptor_group::attr_t&, ideep::algorithm, ideep::prop_kind, ideep::padding_kind) [with alloc = at::native::AllocForMKLDNN; ideep::param::dims = std::vector<int>; ideep::scale_t = std::vector<float, std::allocator<float> >; ideep::algorithm = mkldnn::algorithm; ideep::prop_kind = mkldnn::prop_kind; ideep::padding_kind = mkldnn::padding_kind]’
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/computations.hpp:2121:19:   required from ‘static void ideep::convolution_forward::compute(const ideep::tensor&, const ideep::tensor&, const ideep::tensor&, const dims&, ideep::tensor&, const dims&, const dims&, const dims&, const dims&, int, const ideep::descriptor_group::attr_t&, ideep::algorithm, ideep::prop_kind, ideep::padding_kind) [with alloc = at::native::AllocForMKLDNN; ideep::param::dims = std::vector<int>; ideep::algorithm = mkldnn::algorithm; ideep::prop_kind = mkldnn::prop_kind; ideep::padding_kind = mkldnn::padding_kind]’
/home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/Conv.cpp:102:34:   required from here
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp:623:56: error: no matching function for call to ‘at::native::AllocForMKLDNN::malloc(size_t)’
     buffer_.reset(alloc::template malloc<computation_t>(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
         adesc.get_size()), alloc::template free<computation_t>);
         ~~~~~~~~~~~~~~~~~                               
caffe2/CMakeFiles/torch.dir/build.make:2352: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/Conv.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/Conv.cpp.o] Error 1
In file included from /home/amm-er/ahd/pytorch/third_party/ideep/include/ideep.hpp:43:0,
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/MKLDNNCommon.h:7,
                 from /home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp:4:
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp: In instantiation of ‘void ideep::param::init(const ideep::param::descriptor&) [with alloc = at::native::AllocForMKLDNN; computation_t = ideep::computation]’:
/home/amm-er/ahd/pytorch/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp:69:35:   required from here
/home/amm-er/ahd/pytorch/third_party/ideep/include/ideep/tensor.hpp:623:56: error: no matching function for call to ‘at::native::AllocForMKLDNN::malloc(size_t)’
     buffer_.reset(alloc::template malloc<computation_t>(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
         adesc.get_size()), alloc::template free<computation_t>);
         ~~~~~~~~~~~~~~~~~                               
caffe2/CMakeFiles/torch.dir/build.make:2404: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp.o] Error 1
CMakeFiles/Makefile2:3903: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 756, in <module>
    build_deps()
  File "setup.py", line 325, in build_deps
    cmake=cmake)
  File "/home/amm-er/ahd/pytorch/tools/build_pytorch_libs.py", line 64, in build_caffe2
    cmake.build(my_env)
  File "/home/amm-er/ahd/pytorch/tools/setup_helpers/cmake.py", line 321, in build
    self.run(build_args, my_env)
  File "/home/amm-er/ahd/pytorch/tools/setup_helpers/cmake.py", line 133, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/amm-er/ahd/anaconda3/envs/amustexp/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.```

**Comment by XiaobingSuper** [comment]
@ahmed-fau , I am so sorry, there some mistake in https://github.com/pytorch/pytorch/issues/24174#issuecomment-522643170, I update it. Thanks!

**Comment by ahmed-fau** [comment]
@XiaobingSuper  now it works :)
The library has been installed successfully and also the bug is gone, thanks so much for this great effort.

Before I close the issue, could you please let me know how to install cudatoolkit version 10? because pytorch is installed without cuda. I tried to export the environment variable `USE_CUDN=1` to `python setup.py install` but it didn't work. Also, for your information, the environment variable `USE_MKLDNN` is set to `0` in the `setup.py` file. Is this OK?

Best

**Comment by XiaobingSuper** [comment]
@ahmed-fau ,  you can try this command: `conda install cudatoolkit=10 -c pytorch`,  USE_CUDA and USE_MKLDNN  are falgs which can control whether cuda and mkldnn  be built in setup step, if you want to disable MKLDNN, you can use `USE_MKLDNN=0 python setup.py install`. Thanks!

**Comment by ahmed-fau** [comment]
> conda install cudatoolkit=10 -c pytorch
Isn't applying this command will lead to installing pytorch with the old mkl which is buggy?

**Comment by XiaobingSuper** [comment]
Do you run this command before setup: `conda install -c pytorch magma-cuda90 # or [magma-cuda92 | magma-cuda100 ] depending on your cuda version`

**Comment by ahmed-fau** [comment]
I tried it before setup. Now I have the toolkit installed but it seems that torch still not enabled with cuda as `torch.cuda.is_available()` returns `False`

**Comment by XiaobingSuper** [comment]
@ahmed-fau , Can you use `whereis cuda` see which cuda is used, and also see the cuda version whether correspond with your command used in setup: `conda install -c pytorch magma-cuda90 # or [magma-cuda92 | magma-cuda100 ] depending on your cuda version`?

**Comment by ahmed-fau** [comment]
@XiaobingSuper  from `conda list`, I can see `cudatoolkit               10.1.168                      0    anaconda` to be installed. The only thing is to make the torch library aware of this. Shall I apply `python setup.py build` to rebuild in the presence of cuda?

**Comment by XiaobingSuper** [comment]
I also test using conda install cudatoolkit 10, but the build step always find the system cuda(9.0), so we should find a method to make pytorch build using the cuda installed by conda.

**Comment by ahmed-fau** [comment]
OK, I think the best then is to use two virtual environments: one with pytorch installed by conda with cudatoolkit (then the mkl bug will exist), and another one with pytorch installed from the source without cuda enabled. Will keep this temporary solution until installing torch by conda includes also the mkl bugfix.

Thanks again for this complete support. I will close the issue now.

Best regards

**Comment by XiaobingSuper** [comment]
@ahmed-fau , thanks, we are now have a PR https://github.com/pytorch/pytorch/pull/22910 to sovle this problem.
`
