### ISSUE TITLE
Unable to restore c++ SGD optimizer state completely if dampening != 0

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#24192]
There’s a private parameter in the SGD optimizer, sgd.h:

```
private:
  // Counts how often `step()` is called, for dampening.
  size_t iteration_{0};
```
in sgd.cpp:
```    if (options.momentum_ != 0) {
      const auto dampening = iteration_ == 0 ? 1 : 1 - options.dampening_;
      auto& momentum = buffer_at(momentum_buffers, i);
      momentum = (options.momentum_ * momentum) + (dampening * update);
```
I don’t see how to restore the state of a previously run SGD optimizer
with out access to get/set member: _iteration__
restoring the buffers will still result in the dampening factor being 1,
as though the optimizer is being run for the first time.
(it looks like the iteration count could also just be a flag indicating whether the optimizer has run once or not)

cc @ezyang @gchanan @zou3519

**Comment by pietern** [comment]
Thanks for reporting. This is an issue indeed. Without restoring the iteration counter the optimizer won't use dampening on the first step after instantiating it.

**Comment by yf225** [comment]
Yes we need to fix it.
