### ISSUE TITLE
Memory leak in `torch.tensor`

### ISSUE THREAD

**Issue by valtron** [pytorch/pytorch#24200]
## 🐛 Bug

Calling `torch.tensor` on a Python `list` of `np.float32` objects leaks memory.

## To Reproduce

```
import numpy as np
import torch

def mem():
	import os, psutil
	return psutil.Process(os.getpid()).memory_info().rss // 1024

a = np.zeros(10000, dtype = np.float32) # <-- 1. dtype is important
a = list(a) # <-- 2. has to be a python list

mem_base = mem()
for _ in range(10):
	torch.tensor(a) # <-- 3. must not pass `dtype=torch.float32` here
	print(mem() - mem_base)

# output on my machine:
# 1416
# 2884
# 3940
# 4996
# 6316
# 7372
# 8428
# 9484
# 10804
# 11860
```

## Expected behavior

The number being printed (memory usage) should be more or less constant.

## Environment

 - PyTorch Version: 1.0.0, 1.1.0, 1.2.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.8

## Additional context

On pytorch==0.4.1, `torch.tensor(a)` throws:
```
RuntimeError: Could not infer dtype of numpy.float32
```

Also, this might be the underlying bug in [#17499](https://github.com/pytorch/pytorch/issues/17499).

### How this shows up in real code

This shows up in real code if you have a 1d array in a dataset:

```
class Dataset:
    def __init__(self, X, y):
        self.X = x; self.y = y
    
    def __getitem__(self, i):
        return self.X[i], self.y[i] # <-- self.y[i] is a np.float32
    
    def __len__(self):
        return self.X.shape[0]
```

`self.y[i]` is a `np.float32`, and in 1.2.0, a batch of these get wrapped in a `list` by `_MapDatasetFetcher`, and `default_collate` calls `torch.as_tensor` on it.

**Comment by pietern** [comment]
Many thanks for reporting this issue and providing with a script to reproduce.

I can confirm this reproduces for me as well. I've found that this does not reproduce when the NumPy dtype is `float64` (the native Python float type). 

```
$ python ./repro.py
       <class 'numpy.float16'>: leaks: 15692
       <class 'numpy.float32'>: leaks: 15576
       <class 'numpy.float64'>: leaks: 0
       <class 'numpy.float64'>: leaks: 0
       <class 'numpy.float16'>: leaks: 15840
       <class 'numpy.float32'>: leaks: 15576
       <class 'numpy.float64'>: leaks: 0
          <class 'numpy.int8'>: leaks: 15576
         <class 'numpy.int16'>: leaks: 15576
         <class 'numpy.int32'>: leaks: 15576
         <class 'numpy.int64'>: leaks: 15576
         <class 'numpy.int64'>: leaks: 15576
         <class 'numpy.int64'>: leaks: 15576
          <class 'numpy.int8'>: leaks: 15576
         <class 'numpy.int16'>: leaks: 15840
         <class 'numpy.int32'>: leaks: 15840
         <class 'numpy.int64'>: leaks: 15576
```

**Comment by SsnL** [comment]
found the cause. will submit a pr soon.
