### ISSUE TITLE
Problem with pip installation on Ubuntu 

### ISSUE THREAD

**Issue by prajjwal1** [pytorch/pytorch#2420]
I referred to the Pytorch Documentation to install it. To install it though pip with usage of Python 3.6 following command is given, but it doesn't work
``
$ pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl 
pip install torchvision
``
Output for the following command is:
>torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.

But I managed to install pytorch through 
``
$sudo pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl 
``
For torchvision:
``
$ sudo pip3 install torchvision
``
Installation requires usage of root privileges and pip3. Referred instructions should be changed on getting started section of [doucmentation](http://pytorch.org/) .

**Comment by albanD** [comment]
Hi,

If you have both python 2 and 3 on the machine, then yes pip3 should be used but that depends on your local configuration.
Root privilege is not required if your environment is properly setup, either by having your user in the `staff` group that pip uses, installing the package locally for the user with the `--user` flag or by using a virtualenv for your project.

**Comment by shabazbpatel** [comment]
Using Docker is a good solution to have a reproducible environment. You can install docker from [here](https://docs.docker.com/engine/installation/).  You can use the [Dockerfile](https://github.com/pytorch/pytorch/blob/master/Dockerfile). You can also try using [datmo](https://datmo.com) in order setup environment and track machine learning projects for making models reproducible.

**Comment by prajjwal1** [comment]
I have default configuration for my environment on Ubuntu 16.04 .

**Comment by soumith** [comment]
this is expected behavior. if you have your `pip` configured to python 2.7 (which you can check with `pip --version`), you have to use `pip install` for python 2.7. If you want to install packages for python 3, then i guess `pip3` makes sense in your case.
