### ISSUE TITLE
Promote the quantization scheme to Affine in the quantize addition

### ISSUE THREAD

**Issue by zafartahirov** [pytorch/pytorch#24215]
## 🚀 Feature
#23956 and #23971 prohibit the mixing of different quantization schemes. Need to add support for qscheme promotion: If binary operation is performed on two different qschemes, we promote them to affine, unless both zero_points=0. In that case we can promote the result to symmetric scheme.

**Comment by raghuramank100** [comment]
We do not want to do this. quantization scheme of affine/symmetric will be distinguished only in the observer. Add should always see tensors with scale./zero point and work accordingly.

**Comment by raghuramank100** [comment]
cc @zafartahirov @jerryzh168
