### ISSUE TITLE
[quantization] Need kernels for broadcasting ops

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#24210]
## 🚀 Feature
Need to support broadcasting for the quantized operations.
Currently only quantized `add` needs support for broadcasting

**Comment by raghuramank100** [comment]
Can you add more details (specific examples) or close this issue @z-a-f ?

**Comment by z-a-f** [comment]
We needed a scalar add and scalar multiply. They are landed as #25622, #25545, #24447, #24873, #25080. Closing it now, as there is no current need for other broadcasting ops
