### ISSUE TITLE
Add support for parallel sampling

### ISSUE THREAD

**Issue by hyren** [pytorch/pytorch#24222]
## 🚀 Feature
Support parallel sampling for torch.distributions.

## Motivation
In some cases, I have multiple gamma distributions with different parameters, and I aim to sample from each. I wonder whether I could make it parallel. Now I am doing an explicit loop, which takes time. Gamma is only for an example.

## Pitch
Maybe design a class DistributionParallel, and we could sample from multiple different distributions in parallel. 

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by pietern** [comment]
Can you motivate this with performance measurements? For example, how many samples do you take, how long does this take, and what is the opportunity for parallelization.

**Comment by SsnL** [comment]
I think with most distributions supporting batching, this may not be a big issue. I've talked with @hyren offline, and his use case can be solved by using batched gamma parameter. :) 

In general, this is not restricted to distributions specifically, but launching computations in parallel on CUDA streams. We don't have any examples and custom CUDA streams are known to not work in all use cases (see e.g. https://github.com/pytorch/pytorch/issues/21589 https://github.com/pytorch/pytorch/issues/21821). It would be awesome to provide easy stream parallel computing wrappers someday.

**Comment by fritzo** [comment]
As @Ssnl says, distributions already support batched sampling, e.g.
```py
gammas = dist.Gamma(torch.tensor([0.5, 1.0]),
                    torch.tensor([1.0, 2.0]))
x = gammas.sample()
assert x.shape == (2,)
```
