### ISSUE TITLE
Where is nn.Transformer for pytorch 1.2.0 on win10? 

### ISSUE THREAD

**Issue by shuaishuaij** [pytorch/pytorch#24220]
## ❓ Questions and Help
I ran the installing code "pip3 install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html" and installed torch 1.2.0.

Yet, I can't find the Transformers in nn module, where are they?    platform: WIN10 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
Python version is not mentioned in the post so all the packages for all python versions are checked. However, they all have `transformer.py` in `torch/nn/modules`. So it is likely not the problem on our side. Maybe you have installed it into a different environment. You may type in the following command to check.
```cmd
where pip3
where python
```

**Comment by shuaishuaij** [comment]
> Python version is not mentioned in the post so all the packages for all python versions are checked. However, they all have `transformer.py` in `torch/nn/modules`. So it is likely not the problem on our side. Maybe you have installed it into a different environment. You may type in the following command to check.
> 
> ```batchfile
> where pip3
> where python
> ```

Ok, problem solved thx! It seems I made a silly mistake. The transformer does exist in torch.nn.module. I was trying to load it by "import torch.nn.transformer" as it is written in the Blog and it should be like "import torch.nn.modules.transformer". Thanks for helping!

**Comment by deipss** [comment]
> > Python version is not mentioned in the post so all the packages for all python versions are checked. However, they all have `transformer.py` in `torch/nn/modules`. So it is likely not the problem on our side. Maybe you have installed it into a different environment. You may type in the following command to check.
> > ```batchfile
> > where pip3
> > where python
> > ```
> 
> Ok, problem solved thx! It seems I made a silly mistake. The transformer does exist in torch.nn.module. I was trying to load it by "import torch.nn.transformer" as it is written in the Blog and it should be like "import torch.nn.modules.transformer". Thanks for helping!

However !!!
I used 
`from torch.nn.modules import TransformerEncoder, TransformerEncoderLayer' to import them,   but it is not work. and the versions as follows:
'
python                    3.6.4                h6538335_1    defaults
pytorch                   1.2.0               py3.6_cpu_1  [cpuonly]
torchtext                 0.4.0              pyhb384e40_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
'
So, what should I do ,thx.

**Comment by peterjc123** [comment]
Well, just like what said before, I've checked all the packages, so it is not a problem at our side. Please check locally for the following things:
1. Please be sure you get the package from our side. `conda install -c pytorch pytorch cpuonly`
2. Please be sure you choose one consistent python environment from CMD and from PyCharm. (Configuration for PyCharm) Unluckily, I don't use PyCharm, so there is nothing more I can tell.

**Comment by deipss** [comment]
> Well, just like what I said before, I've checked all the packages, so it is not a problem at our side. Please check locally for the following things:
> 
> 1. Please be sure you get the package from our side. `conda install -c pytorch pytorch cpuonly`
> 2. Please be sure you choose one consistent python environment from CMD and from PyCharm. (Configuration for PyCharm) Unluckily, I don't use PyCharm, so there is nothing more I can tell.

By any means,thx. actually,I  am not use ``` conda install -c pytorch pytorch cpuonly ```, since there are some limitation in network speed. 
what I chose is a third-part image from Tsinghua University. I think I should to contact them for this problem.
Thanks again.
