### ISSUE TITLE
fbgemm_conv needs to be registered as aten function

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24221]
## 🚀 Feature
We need this for graph mode.

**Comment by jerryzh168** [comment]
Also, for prepack functions

And for linear as well

**Comment by jerryzh168** [comment]
please ask @zafartahirov if you have any questions, he has did similar thing for qrelu I believe.

**Comment by jianyuh** [comment]
@zafartahirov : could you show us the example for qrelu?

@jerryzh168 : If I understand this issue correctly, previously we have fbgemm_linear/fbgemm_conv registered as a c10 op. Now instead we want to register them as ATen op (specifically in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml). Correct me if I am wrong.

**Comment by jerryzh168** [comment]
@ZolotukhinM I just checked, looks like we can't call c10 ops directly, since there is no c10 namespace here: https://bddppq.github.io/codebrowser/pytorch/pytorch/aten/src/ATen/core/interned_strings.h.html#_ZN3c106SymbolC1Ev

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/pull/22316

**Comment by jerryzh168** [comment]
Looks like we can just call them in jit, then we don't need this. sorry for the confusion.

**Comment by jerryzh168** [comment]
We are planning to use c10 namespace for quantized ops since quantized ops don't require backward and since we are moving towards using c10 op registration.
cc @jianyuh @dskhudia @zafartahirov @raghuramank100
