### ISSUE TITLE
Question about inlining auto-diff subgraph in JIT

### ISSUE THREAD

**Issue by CaoZhongZ** [pytorch/pytorch#24226]
The backward of JIT is still rely on imperative forward to accumulate gradient calculation process on variables. However there is a pass trying to create and inline auto-diff subgraphs with certain criteria. Is it possible that in the future, PyTorch JIT will inline all auto-diff subgraphs into forward one and form a complete context?

**Comment by jgong5** [comment]
@Jianhui-Li
