### ISSUE TITLE
ONNX export failed: _NewEmptyTensorOp

### ISSUE THREAD

**Issue by WonderAndMaps** [pytorch/pytorch#24233]
## ❓ Questions and Help

Hi, I was trying to convert a mask rcnn model (maskrcnn-benchmark) to onnx model. I encountered this error
```
RuntimeError: ONNX export failed: Couldn't export Python operator _NewEmptyTensorOp
```
I think that is some class defined in that repo 
https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/misc.py#L18
Anyone has any solutions?

**Comment by jinfagang** [comment]
@WonderAndMaps  I encountered same error. did u solve it?

**Comment by WonderAndMaps** [comment]
@jinfagang It's caused by not detecting anything in that sample image. You may want to pass an real image with possible detections in it while exporting.

**Comment by WonderAndMaps** [comment]
@jinfagang It's caused by not detecting anything in the sample image provided while exporting. You may want to pass a real image with possible detections in it.

**Comment by garymm** [comment]
Seems @WonderAndMaps resolved this issue by using a different input, so closing.
