### ISSUE TITLE
Differentiation error in Autograd example

### ISSUE THREAD

**Issue by rahulbhadani** [pytorch/pytorch#24230]
## 🐛 Bug

In the tutorial:

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#gradients

![https://i.ibb.co/mJVGJ4Z/Screenshot-from-2019-08-12-22-49-53.png](https://i.ibb.co/mJVGJ4Z/Screenshot-from-2019-08-12-22-49-53.png)

it is 
$$
o = 3(x_i + 2)^2
$$

with 
$\cfrac{\delta o }{\delta x_i} = \cfrac{3}{2}(x_i + 2)$

However correct differentiation should be:

$\cfrac{\delta o }{\delta x_i} = 6(x+2)$

Apparently, the answer 4.5 follows the wrong differentiation result and hence raises the question about the validity of AUTOGRAD feature in PyTorch.

**Comment by vishwakftw** [comment]
I believe you missed the 1/4 factor in front of the summation. Hence, 6/4 = 3/2 is correct.

**Comment by rahulbhadani** [comment]
o  = 1/4 (sum z_i ). So factor of 1/4 won’t get cancelled?

**Comment by rahulbhadani** [comment]
I think i got it. I was summing first and then differentiating. So I see where my understanding in this case was different!
