### ISSUE TITLE
[RPC] Split RPC API for sync and async to have explicit return types

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#24247]
As pointed out by @aazzolini in #23569, instead of using an `async_call` arg to distinguish sync and async RPC, we should split it into different sync and async APIs, so that we can have explicit return type hints.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by rohan-varma** [comment]
@mrshenli Would this just involve splitting the `rpc` function in `rpc.py` to 2 functions such as `rpc_sync` and `rpc_async`?

**Comment by mrshenli** [comment]
@rohan-varma Yes, that's correct. We would like to have those functions have a fixed return type so that they can be called in TorchScript function.

**Comment by rohan-varma** [comment]
Addressed by #26570.
