### ISSUE TITLE
Improve indexing type error message

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#2424]
Example:
```
>>> torch.randn(3,3)[(1,torch.LongTensor([2]))]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: indexing a tensor with an object of type torch.LongTensor. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
```

This error message is difficult to parse.  I think there are two main issues:
1) The type of the indexing object is reported as torch.LongTensor, but it's a tuple including a torch.LongTensor (this makes "the only argument" later confusing -- torch.LongTensor was reported as the only argument).

2) It's not clear what "as the only argument" binds to; should it be:
a) and ( (torch.LongTensor or torch.ByteTensor) as the only argument.) 
b) and torch.LongTensor or ( torch.ByteTensor as the only argument).

**Comment by killeent** [comment]
Also to me.

**Comment by killeent** [comment]
Note that this isn't an issue with the error message generated from advanced indexing, but rather basic indexing.
