### ISSUE TITLE
CPU is at 100% even if training is on GPU

### ISSUE THREAD

**Issue by AravindChandradoss** [pytorch/pytorch#24244]
## ❓ Questions and Help
Is there any way to restrict the CPU usage? Even if the training is on GPU, the usage of CPU is always 100% (all 8 cores)
 
![Screenshot from 2019-08-13 12-06-05](https://user-images.githubusercontent.com/43117278/62960238-40378500-bdc8-11e9-95d2-f04f22396a27.png)

![Screenshot from 2019-08-13 12-07-09](https://user-images.githubusercontent.com/43117278/62960239-40378500-bdc8-11e9-8687-404872ffdc92.png)

I tried 
```
torch.get_num_threads()
torch.set_num_threads(1)

```
But still all 8 cores are working at 100%. 

The main issues is that the system is randomly rebooting. I suspect it is because of overheating of the cores. I need to know whether are there any other commands to limit CPU usage. 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by heiner** [comment]
Not sure what code you are running but try setting `OMP_NUM_THREADS=1` as an environment variable.

**Comment by AravindChandradoss** [comment]
@heiner No... I tried. Still, it is using all the CPUs. 
Any other methods?

**Comment by SsnL** [comment]
It could be multithreading/processing (e.g., data loader workers), or other libraries you use. `set_num_threads` restricts all CPU kernels and only CPU kernels. Unless you can provide a small self-contained script, it is difficult to help you.

**Comment by AravindChandradoss** [comment]
It was due to DataLoader parameters only. Long back, I changed those default parameter and forgot to change it back. `num_worker` 

Thanks.
