### ISSUE TITLE
[RPC] Python UDF and Builtin Ops should serialize to the same message layout

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#24252]
As pointed out by @zdevito in #23569, instead of serializing the entire Python UDF RPC into a byte vector, it should stay consistent in the message layout with Builtin Ops where tensors are stored in a separate tensor table. This design avoids serializing everything all at once, and makes it possible to introduce streaming serialization in the future.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by xush6528** [comment]
When implementing other RpcAgent sub class, I found message.type is not used. Because other serialization framework has its own way of specifying. And don't need to go through the heavy torch.serialize/deserialize utility.

**Comment by mrshenli** [comment]
Hey @xush6528 can you sync with @zhaojuanmao on the plan for this issue? We might need to postpone this work until we have a working version of distributed autograd.

**Comment by pritamdamania87** [comment]
@zhaojuanmao We can close this out right?

**Comment by mrshenli** [comment]
It's #26314 I think
