### ISSUE TITLE
Large ending index in Slice operator when exporting to ONNX model

### ISSUE THREAD

**Issue by lsy323** [pytorch/pytorch#24251]
When exporting a PyTorch model to ONNX, if the model has the range indices selection operator (e.g. x[2:]) and didn't specify the ending index. The "end" attribute in the exported Slice operator will be an extremely large number. This happens with PyTorch 1.0 1.1 and 1.2. However, in 0.4, there isn't such a case. I wonder if this behavior is intended?

e.g. the model is like this:
```
class testMod(nn.Module):
    def forward(self, x):
        return x[2:]

model = testMod()
x = torch.rand(10)
torch.onnx.export(model, x, "slice.onnx", verbose=True, input_names=["input"], output_names=["output"], opset_version = 10)
```

The exported Slice op is:
`%output : Float(8) = onnx::Slice[axes=[0], ends=[**9223372036854775807**], starts=[2]](%input), scope: testMod`

If using v0.4 to export, the ending index could be inferred:
`%output : Float(8) = onnx::Slice[axes=[0], ends=[**10**], starts=[2]](%input), scope: testMod`

Many Thanks

**Comment by BowenBao** [comment]
Hi @lsy323, yes this is expected. In v0.4, the inferred value `10` will not work if the input tensor has a different shape at runtime.

From ONNX spec for slice operator.

> ... For slicing to the end of a dimension with unknown size, it is recommended to pass in INT_MAX. ...

**Comment by lsy323** [comment]
Hi @BowenBao,

Thanks for the explanation!

**Comment by LLNLanLeN** [comment]
@BowenBao hi, sorry to ping you again even though the issue has been resolved a while ago, but can you help me understand why the input would have different shape at runtime?

**Comment by lsy323** [comment]
> @BowenBao hi, sorry to ping you again even though the issue has been resolved a while ago, but can you help me understand why the input would have different shape at runtime?

Hi @LLNLanLeN , using the simple model above as an example. 
The shape of the input x can be different at runtime. e.g. its length can be 10, 20, 30... And the forward function always returns elements starting from the third one to the last one.

Hope this is helpful

**Comment by LLNLanLeN** [comment]
> > @BowenBao hi, sorry to ping you again even though the issue has been resolved a while ago, but can you help me understand why the input would have different shape at runtime?
> 
> Hi @LLNLanLeN , using the simple model above as an example.
> The shape of the input x can be different at runtime. e.g. its length can be 10, 20, 30... And the forward function always returns elements starting from the third one to the last one.
> 
> Hope this is helpful

I see, so batch size could be the reason why it's effected as well? For example, when training you'd use batch, but when doing inference, we set batch to 1.

**Comment by lsy323** [comment]
> > > @BowenBao hi, sorry to ping you again even though the issue has been resolved a while ago, but can you help me understand why the input would have different shape at runtime?
> > 
> > 
> > Hi @LLNLanLeN , using the simple model above as an example.
> > The shape of the input x can be different at runtime. e.g. its length can be 10, 20, 30... And the forward function always returns elements starting from the third one to the last one.
> > Hope this is helpful
> 
> I see, so batch size could be the reason why it's effected as well? For example, when training you'd use batch, but when doing inference, we set batch to 1.

Yes, I believe this could be one of the many scenarios.
