### ISSUE TITLE
gloo subtree has submodule, which causes submodule init to fail

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#2426]
Steps to reproduce:
1. Clone PyTorch repo
2. Run `git submodule init`

Expected result: Works

Actual result: 

```
fatal: No url found for submodule path 'torch/lib/gloo/third-party/googletest' in .gitmodules
```

I wrote up about the issue here: https://stackoverflow.com/questions/45422693/how-to-use-git-repo-with-submodule-nested-in-subtree

One "easy" way to fix this is to copy the .gitmodules to the top level of the repo and modify the paths so the are correct. If people are ok with this I can PR it.

**Comment by apaszke** [comment]
Do we have to do this? All submodules that Gloo has are optional dependencies that we don't use

**Comment by ezyang** [comment]
It's very jarring for users (@prigoyal ran into this) when they git clone and their implicit submodule update fails (this can be turned on in gitconfig)

**Comment by ashr59** [comment]
@soumith @apaszke  Hi, I didn't get the solution. When I clone Pytorch, the gloo folder remains empty. 
Should I clone [it](https://github.com/facebookincubator/gloo/tree/0c9766691d77eb54c5a3293bc29621a82424fabb) separately?

**Comment by fmassa** [comment]
@ashr59 I think you need to do `git submodule update --init` according to https://github.com/pytorch/pytorch/issues/2553#issuecomment-326066034

**Comment by ashr59** [comment]
@fmassa ok, thanks.

**Comment by soumith** [comment]
added instructions in the README now: https://github.com/pytorch/pytorch/blob/master/README.md#get-the-pytorch-source
