### ISSUE TITLE
torch.empty() seems to produce random values

### ISSUE THREAD

**Issue by thepian** [pytorch/pytorch#24263]
## 🐛 Bug

Playing around with torch 1.2.0 seems to output the wrong tensor when calling empty(5,3)

## To Reproduce

```
>>> import torch
>>> x = torch.empty(5, 3)
>>> print(x)
tensor([[1.8361e+25, 1.4603e-19, 1.6795e+08],
        [4.7423e+30, 4.7393e+30, 9.5461e-01],
        [4.4377e+27, 1.7975e+19, 4.6894e+27],
        [7.9463e+08, 3.2604e-12, 1.7743e+28],
        [2.0535e-19, 5.9682e-02, 7.0374e+22]])
```
## Expected behavior

```
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
```

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.14.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.2.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.0
[conda] Could not collect

**Comment by ezyang** [comment]
That's intended. Use `torch.zeros()` if you want zeros.

**Comment by thepian** [comment]
Then the blitz tutorial is wrong https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

**Comment by soumith** [comment]
the blitz tutorial's output is unfortunate. the randomly initialized memory had all zeros (and that happens with memory -- memory can have any bits, but quite often has bits that point to all zeros).

**Comment by thepian** [comment]
Perhaps that could be a note in the tutorial
