### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: unspecified launch failure

### ISSUE THREAD

**Issue by kernelizd** [pytorch/pytorch#24287]
## 🐛 Bug

Training goes noramlly, and suddenly, at random time, this error shows up. 
Only happens when I run two models on same GPU. 

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.
 - GPU models and configuration: TitanRTX
 - Any other relevant information:

**Comment by zhangguanheng66** [comment]
Can you provided script so we could reproduce the bug? Do you mean training two models simultaneously on the same GPU?

**Comment by kernelizd** [comment]
Hi. Thanks for response. Actually, after a clearn reboot, everything is fine now.
