### ISSUE TITLE
MinMax Observer should return tensor of scale and tensor of zero_point?

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#24304]
## 🐛 Bug
Right now it returns a tensor of [scale, zero_point], I think maybe we should just return the values directly, or two Tensors?
https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L65

**Comment by zafartahirov** [comment]
I think we should have some container data structure for the quantization parameters. I'm just thinking in the future we might want to calibrate the data type, and maybe min/max, etc.

**Comment by jerryzh168** [comment]
that is quantizer, we can change that after quantizer is exposed in python frontend.

**Comment by jianyuh** [comment]
Link this issue with https://github.com/pytorch/pytorch/pull/24339.

**Comment by jerryzh168** [comment]
fixed
