### ISSUE TITLE
Is pytorch 1.2 compatible with cudatoolkit 9.0？

### ISSUE THREAD

**Issue by RomanShen** [pytorch/pytorch#24301]
## ❓ Questions
Hello, I’m trying to upgrade to pytorch 1.2. I’ve found that official guidance seems to need cudatoolkit version to be 9.2 or higher. Is it possible to use pytorch 1.2 with cudatoolkit 9.0? Thanks for any help!

**Comment by ezyang** [comment]
CUDA 9.2 is not binary compatible with CUDA 9.0, and probably won't work. You will need to build from source if you want a build against 9.0.
