### ISSUE TITLE
libtorch debug version build in windows linking torch-NOTFOUND.obj problem

### ISSUE THREAD

**Issue by NeilWangziyu** [pytorch/pytorch#24305]
## 🐛 Bug

Hi, 

I download the libtorch windows debug version and want to build libtorch in VS.

However, when linking each libraries, in bash shows it will link to those libraries
```bash
TORCH_LIBRARIES=torch;torch_library;C:/Users/t-ziw/source/repos/cmf_toolkit/installed/libtorch/lib/c10.lib
```
for the second library:torch_library, it will shows in VS as torch-NOTFOUND.obj. 

```bash
LINK : fatal error LNK1104: cannot open file 'torch-NOTFOUND.obj' [C:\Users\t-ziw\source\repos\cmf_toolkit\libcmftk\bui
ld\cmftk.vcxproj]
```
The other two library can be found, except for the torch_library

And when I switch to the Release Version of Libtorch 1.2.0, it works OKAY. 

I traced the CMake files, the problem is in libtorch\share\cmake\Caffe2

```bash
caffe2_interface_library(torch torch_library)
set(Caffe2_MAIN_LIBS torch_library)
```

In fact I dont really understand that Caffe2_MAIN_LIBS is called torch_library.  but the bug is in windows debug version linking that library

## To Reproduce

1. Download libtorch CPU version windows
2. cmake --build . 

## Expected behavior

just build success

## Environment

 - PyTorch Version (e.g., 1.0): 1.2 stable release
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): cmake --build .
 - Python version:3.7
 - CUDA/cuDNN version:None
 - GPU models and configuration:
 - Any other relevant information:
gcc version 8.2.0
Visual Studio 2019

**Comment by peterjc123** [comment]
Could you please show me your `CMakeLists.txt`? And what command did you call to configure the project?

**Comment by Hayden2018** [comment]
I also have this LNK1104 problem but was unable to resolve by using libtorch stable 1.2.0 (Win10 cuda 10)   Cmakelists.txt as follow

`cmake_minimum_required(VERSION 3.0)

project(HelloTorch)
find_package(Torch REQUIRED)

add_executable(HelloTorch main.cpp)
target_link_libraries(HelloTorch "${TORCH_LIBRARIES}")
set_property(TARGET HelloTorch PROPERTY CXX_STANDARD 11)`

**Comment by NeilWangziyu** [comment]
@peterjc123 

Download the libtorch
```bash
ExternalProject_Add(libtorch
    URL ${LIBTORCH_URL}
    SOURCE_DIR "${LIBTORCH_INSTALL_DIR}"
    BUILD_IN_SOURCE true
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ${CMAKE_COMMAND} -E remove_directory "test"
    # effective on Windows
        COMMAND ${CMAKE_COMMAND} -E remove "lib/libgtest.a lib/libgtest_main.a"
    # Effective on Linux, but have not test yet
    INSTALL_COMMAND ""
    TEST_COMMAND "")

# if windows, download a debug version for vs. this must happen after release version
# otherwise, release version will be deleted.
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    ExternalProject_Add(libtorch_debug
        DEPENDS libtorch
        URL "https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-${LIBTORCH_VERSION}.zip"
        SOURCE_DIR "${LIBTORCH_INSTALL_DIR}/debug"
        BUILD_IN_SOURCE true
        CONFIGURE_COMMAND ""
        BUILD_COMMAND ${CMAKE_COMMAND} -E remove_directory "test"
              COMMAND ${CMAKE_COMMAND} -E remove_directory $<$<CONFIG:Release>:lib>
        INSTALL_COMMAND ""
        TEST_COMMAND "")
endif()
```

link libtorch to my project
```bash
target_link_libraries(cmftk PRIVATE ${TORCH_LIBRARIES})
    add_custom_command(
        TARGET cmftk POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_directory
                ${CMAKE_CURRENT_SOURCE_DIR}/../installed/libtorch/$<$<CONFIG:Debug>:debug>/lib
                $<TARGET_FILE_DIR:cmftk>/lib)
```

**Comment by NeilWangziyu** [comment]
I found that the problem is on my CMakelist. In the previous version libtorch debug version and libtorch release version can be build using same CMakeList.

And in Release 1.2.0, debug and release version relay on different lib, so it makes the difference

**Comment by aaost** [comment]
@NeilWangziyu How did you fix this? I am seeing the same thing with the latest release (torch-NOTFOUND is being used in Debug configuration in VS). The official binary release provides 2 separate archives for release and debug builds but both define the same targets (torch). You can't really call `find_package(Torch)` with two different directories since it caches vars.

**Comment by NeilWangziyu** [comment]
@aaost Hi, in fact I have not fixed it. I just keep all my code in debug version in order to prevent the problem happends

**Comment by leoluopy** [comment]
@aaost  @NeilWangziyu  I meet the same problem and found that you can download the debug version of libtorch in the official web site

**Comment by eusoubrasileiro** [comment]
@leoluopy  I am using the debug version and having the same error when `cmake blablabla -build=Debug -A x64 ..`

**Comment by NingAnMe** [comment]
if using the debug version, while you cmake, please use "`cmake --build . --config Debug`" instead of "`cmake --build . --config Release`"

**Comment by carlsummer** [comment]
I slove it,
you can see libtorch-demo/example-app at main · carlsummer/libtorch-demo · GitHub,
set(CMAKE_BUILD_TYPE “Release”)

-DCMAKE_PREFIX_PATH=path\to\opencv\build\x64\vc14\lib;path\to\libtorch -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 14 Win64"

**Comment by ziyuang** [comment]
> I slove it,
> you can see libtorch-demo/example-app at main · carlsummer/libtorch-demo · GitHub,
> set(CMAKE_BUILD_TYPE “Release”)
> 
> -DCMAKE_PREFIX_PATH=path\to\opencv\build\x64\vc14\lib;path\to\libtorch -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 14 Win64"

This is about building with type release isn't it? How about building with type debug?
