### ISSUE TITLE
Trying to get pytorch working for the first time

### ISSUE THREAD

**Issue by robert604** [pytorch/pytorch#2430]
I am using a freshly installed Ubuntu mate 16.04 on a machine with two gpu's.  One is connected to the monitor (gtx 610) while the other is for use with neural networks (gtx 1060).
I used the "software and updates" app to install ver 384.59 and then ver 378.13 of the nvidia driver, but in both cases I wasn't able to get a pytorch script working properly.
I have anaconda installed with which I have installed spyder as the ide for python 3.6.
Here's the output from the "nvidia-smi" command:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.13                 Driver Version: 378.13                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 610      Off  | 0000:03:00.0     N/A |                  N/A |
| 40%   47C    P8    N/A /  N/A |    299MiB /   959MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 0000:04:00.0     Off |                  N/A |
| 40%   39C    P8     6W / 120W |     11MiB /  6072MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

I have not installed cuda manually on this setup. After installing pytorch through anaconda I tried out the simple script below:
import torch
a = torch.randn(10).cuda()
print(a)
print(a + 2)

The program just hangs indefinitely, and it appears that one of my cpu cores is busy.
After some research on the internet I changed the script to:
import torch
torch.cuda.set_device(1)
a = torch.randn(10).cuda()
print(a)
print(a + 2)

Now I get a different error, here's the traceback:
Traceback (most recent call last):

  File "<ipython-input-1-2739f6cb979a>", line 1, in <module>
    runfile('/home/robert/Downloads/Data/pytorch/pytorch1.py', wdir='/home/robert/Downloads/Data/pytorch')

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/robert/Downloads/Data/pytorch/pytorch1.py", line 13, in <module>
    print(a + 2)

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/torch/tensor.py", line 267, in __add__
    return self.add(other)

RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/libtorch-gpu_1493845455319/work/pytorch-0.1.12/torch/lib/THC/generic/THCTensorMathPairwise.cu:21

I'd also like to mention that I have used this machine with cuda for deep learning before using keras and have not made any hardware changes.  I was having problems reinstalling cuda after doing an update of the operating system so I thought I'd try out pytorch.

Any help would be greatly appreciated.

**Comment by ngimel** [comment]
Looks like you've installed pytorch woth cuda 7.5, and it is trying to jit the code for you 1080 card. When you set device to 1, you are running on 610, which has compute capability 3.0 and most likely not supported. Try installing cuda 8 version of pytorch (conda install pytorch torchvision cuda80 -c soumith)

**Comment by robert604** [comment]
I uninstalled "pytorch-gpu" from the anaconda gui and installed cuda 8 through the terminal with:
conda install pytorch torchvision cuda80 -c soumith

Now running the script gives an error at the import statement:
Traceback (most recent call last):

  File "<ipython-input-1-2739f6cb979a>", line 1, in <module>
    runfile('/home/robert/Downloads/Data/pytorch/pytorch1.py', wdir='/home/robert/Downloads/Data/pytorch')

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/robert/Downloads/Data/pytorch/pytorch1.py", line 9, in <module>
    import torch

  File "/home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *

ImportError: /home/robert/anaconda3/envs/alpha/lib/python3.6/site-packages/torch/lib/libTHD.so.1: undefined symbol: _ZN4thpp8THTensorIiEC1EP13THLongStorageS3_

**Comment by soumith** [comment]
@robert604 also please do `conda uninstall libtorch`. That should fix it.

**Comment by robert604** [comment]
In case this is useful to someone else experiencing the same problem.  I managed to get it working by creating a new environment in anaconda using python 3.5 instead of python 3.6.  Thanks to everyone that tried to help.
