### ISSUE TITLE
Linking Pytorch C++FrontEnd with Qt 5.12.2  MSVC2017 64bit

### ISSUE THREAD

**Issue by zirid** [pytorch/pytorch#24308]
## Issue description

Linking Pytorch c++ fronted (Prebuilt gpu version)  with  VS2017 works fine (conformance mode = no).  
I am trying to link with Qt but get errors.

Thank you in advance. 

## Code example

`#include <torch/torch.h>
`

**.pro file** 
`INCLUDEPATH+="C:\DeepLib\libtorch\include"
INCLUDEPATH+= "C:\DeepLib\libtorch\include\torch\csrc\api\include"

LIBS+= "C:\DeepLib\libtorch\lib\torch.lib"
LIBS+= "C:\DeepLib\libtorch\lib\c10.lib"
LIBS+= "C:\DeepLib\libtorch\lib\c10_cuda.lib"
LIBS+= "C:\DeepLib\libtorch\lib\caffe2_nvrtc.lib"
LIBS+= "C:\DeepLib\libtorch\lib\cpuinfo.lib"
LIBS+= "C:\DeepLib\libtorch\lib\libprotobuf.lib"
LIBS+= "C:\DeepLib\libtorch\lib\libprotobuf-lite.lib"
LIBS+= "C:\DeepLib\libtorch\lib\libprotoc.lib"
LIBS+= "C:\DeepLib\libtorch\lib\caffe2_module_test_dynamic.lib"
LIBS+= "C:\DeepLib\libtorch\lib\caffe2_detectron_ops_gpu.lib"`

**Tried flags** 

`QMAKE_CXXFLAGS -= /permissive-
CONFIG += no_keywords
QMAKE_CXXFLAGS += -DGLIBCXX_USE_CXX11_ABI=0`

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(268): error C2061: syntax error: identifier 'IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(268): error C2238: unexpected token(s) preceding ';'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(272): error C2988: unrecognizable template declaration/definition
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(272): error C2059: syntax error: 'return'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(272): error C2653: 'Tag': is not a class or namespace name
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(272): error C2238: unexpected token(s) preceding ';'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(273): error C2146: syntax error: missing ';' before identifier 'toGenericDict'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(273): error C2270: 'toGenericDict': modifiers not allowed on nonmember functions
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(56): error C2653: 'Tag': is not a class or namespace name
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(56): error C2065: 'None': undeclared identifier
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(56): error C2614: 'c10::IValue': illegal member initialization: 'payload' is not a base or member
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(56): error C2614: 'c10::IValue': illegal member initialization: 'tag' is not a base or member
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(56): error C2614: 'c10::IValue': illegal member initialization: 'is_intrusive_ptr' is not a base or member
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(57): error C2039: 'payload': is not a member of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(55): note: see declaration of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(57): error C2039: 'tag': is not a member of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(55): note: see declaration of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(57): error C2039: 'is_intrusive_ptr': is not a member of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(55): note: see declaration of 'c10::IValue'
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(59): error C2065: 'is_intrusive_ptr': undeclared identifier
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(60): error C2065: 'payload': undeclared identifier
..\..\..\..\DeepLib\libtorch\include\ATen/core/ivalue.h(60): fatal error C1903: unable to recover from previous error(s); stopping compilation
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.

- PyTorch C++ FrontEnd
- Prbuilt GPU version
- Build command you used (if compiling from source):
- OS: Win 10
- PyTorch version: latest
- Python version:
- CUDA/cuDNN version: CUDA 10 - cudnn64_7
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: Qt 5.12.2  - MSVC2017  64 bit

**Comment by zirid** [comment]
Until now the only workaround i found is (using Qt inside VS2017)  :

After Using "Qt Visual Studio Tools" and setting the project  in VS 2017 with "language conformance NO"

I had to do :

#undef slots
#include <torch/torch.h>
#define slots Q_SLOTS


(Still not working with Qt creator/Qmake)

**Comment by ncrawfo** [comment]
I had some success with Qt creator/Qmake. In addition to what you did with undefining slots, there also seems to be a problem related to doxygen comments in the middle of the template definitions in ivalue.h.  If I change near line 264 in ivalue.h from

  template<class T>
  /// \cond DOXYGEN_CANNOT_HANDLE_CONSTRUCTORS_WITH_MACROS_SO_EXCLUDE_THIS_LINE_FROM_DOXYGEN
  C10_DEPRECATED_MESSAGE("IValues based on std::vector<T> are potentially slow and deprecated. Please use c10::List<T> instead.")
  /// \endcond
  IValue(std::vector<T> v);

to

  template<class T>
  IValue(std::vector<T> v);

(and similar near line 279)
there is no longer a compiler error.

**Comment by zirid** [comment]
Yes i tried your suggestion and it works using Qmake now. 
Thank you.

**Comment by giaxxi** [comment]
> Yes i tried your suggestion and it works using Qmake now.
> Thank you.

I'm having the exact same issue and tried the solution which seems have solved:
```
template
IValue(std::vector v);
```
But then I'm getting different errors.

Maybe you can share some tips?

**Comment by MartinSamouiller** [comment]
Hi, 

I did the tricks explain above, and it seems to working fine. 
To sum up:

Go to ivalue.h, and remove the doxygen comment lines:
```
template<class Key, class Value>
  /// \cond DOXYGEN_CANNOT_HANDLE_CONSTRUCTORS_WITH_MACROS_SO_EXCLUDE_THIS_LINE_FROM_DOXYGEN
  C10_DEPRECATED_MESSAGE("IValues based on std::unordered_map<K, V> are slow and deprecated. Please use c10::Dict<K, V> instead.")
  /// \endcond
  IValue(std::unordered_map<Key, Value> v);
```

it should become:

```
  template<class Key, class Value>
  IValue(std::unordered_map<Key, Value> v);
```

---------------------------------------------------------------------------------

Add the lines below to the .h :
```
#undef slots
#include "torch/script.h"
#define slots Q_SLOTS
```

---------------------------------------------------------------------------------

Define a slot like that:
```
public Q_SLOTS :
    void on_pushButton_pressed();
```


And it should work fine. 
I used Visual 2017, Qt 5.11.3, and Pytorch 1.4 -> QtCreator

However I still have some issues with Qt and cmake... only qmake works fine.

**Comment by robosina** [comment]
I have had this issue too, I just clear doxygen lines and everything solved(Visual Studio 2017)

**Comment by wufang6459** [comment]
I did what @MartinSamouiller suggested and everything solved as well.

**Comment by Pikachuxxxx** [comment]
> #undef slots
> #include <torch/torch.h>
> #define slots Q_SLOTS

Well just doing this solved for me thanks @zirid

**Comment by YingGwan** [comment]
#undef slots
#include <torch/torch.h>
#define slots Q_SLOTS 


Many thanks for your help!
It works for Visual Studio 2019 + LibTorch 1.11.0.
