### ISSUE TITLE
[JIT] torch.jit.script should not error out with "No forward method was defined on Module" if there are other exported methods

### ISSUE THREAD

**Issue by reuben** [pytorch/pytorch#24314]
## 🐛 Bug

In this function: https://github.com/pytorch/pytorch/blob/cb4a6327a399ace4d7ec392b33d179729b31d8d8/torch/jit/_recursive.py#L100-L125

An error is thrown if the `forward` method is not defined, but I don't see why that's necessary if the module has other exported methods. The check should probably be if the final methods list is empty and there's no exported methods to convert.

## To Reproduce

1.
```python
$ python -c "
import torch

class Foo(torch.nn.Module):
    @torch.jit.export
    def inference(self, x):
        return x

mod = torch.jit.script(Foo())
print(mod.inference(torch.ones(1)))"
```

Gives this error:
```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "[...]/lib/python3.7/site-packages/torch/jit/__init__.py", line 1162, in script
    return _convert_to_script_module(obj)
  File "[...]/lib/python3.7/site-packages/torch/jit/__init__.py", line 1796, in _convert_to_script_module
    raise RuntimeError("No forward method was defined on {}".format(mod))
RuntimeError: No forward method was defined on Foo()
```

## Expected behavior

It should just work. Considering that I can just define a dummy forward method and add `@torch.jit.ignore` to it and it works fine, I don't see why this error is thrown.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.15.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] torch==1.2.0
[conda] Could not collect

cc @suo

**Comment by wanchaol** [comment]
the entry point of a `torch.nn.Module` is the `forward` method, without it you could not call the initialized module with corresponding inputs, see https://pytorch.org/docs/stable/nn.html#torch.nn.Module.forward, so if you only export all other methods but not forward (or with `ignore` annotation), TorchScript will compile those methods but will still call the `forward` in python as entry point, which means your program will contain python/torchscript mixed representations. If you don't define `forward` in `nn.Module`, this is a mis-use of `nn.Module` as the document implies. In this case, you will want to use torchscript class type (python custom classes) as documented here https://pytorch.org/docs/stable/jit.html#user-defined-types

**Comment by reuben** [comment]
Hm. So if I want to export some methods but not forward, I should make sure forward is empty to avoid mixed Python/TorchScript in the final model?

TorchScript class types aren't enough for my use case, because they require the entire class to be TorchScript compatible rather than just the exported methods.

**Comment by reuben** [comment]
Specifically, here's a better example for what I'm trying to do:

```python
class Foo(torch.nn.Module):
    def __init__(self, inner_module, trace_inputs, some_option=1.0, some_other=None, **kwargs):
        self.inner = torch.jit.trace_inputs(inner_module, trace_inputs)
        self.some_config = some_option
        self.register_buffer('_my_fancy_buffer', self.method_that_uses_librosa_or_scipy_or_whatever())

    @torch.jit.export
    def inference(self, inputs):
        inner_outputs = self.inner(inputs)
        return self.do_some_postprocessing_using_fancy_buffer(inner_outputs)
```

I can then call `torch.jit.trace` on `Foo` and get the best of both worlds. I can use any third-party library I wish in the constructor for example, as well as have Python code that is not supported by TorchScript in `__init__` as well as in `method_that_uses_librosa_or_scipy_or_whatever`, but as long as `inference` is valid TorchScript I can export this model.

@wanchaol In this case, if I annotate `Foo` with `@torch.jit.script`, I get errors in methods that aren't actually called after the constructor. Is there some alternative construct I can use in this case? To be clear, defining an empty forward method is a good enough workaround for now, but maybe I'm missing something simple.

**Comment by eellison** [comment]
This has been fixed, the repro no longer errors.
