### ISSUE TITLE
Exporting to onnx causes unwanted nodes in graph if using x.size()

### ISSUE THREAD

**Issue by bpinaya** [pytorch/pytorch#24316]
## 🐛 Bug

Hi there, in pytorch `1.2.0a0+8554416` built from source I'm encountering a very weird behavior while exporting to onnx, creating unwanted nodes in the exported onnx file.

## To Reproduce

This is a sample snippet to reproduce behavior you can have a network like this:
```python
import torch
from torch import nn


class _CBNReLU(nn.Module):
    """Convolution plus Batchnorm and Relu"""

    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=0, bias=False):
        super(_CBNReLU, self).__init__()
        self.conv = nn.Sequential(nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding, bias=bias),
                                  nn.BatchNorm2d(out_channels), nn.ReLU(True))

    def forward(self, x):
        return self.conv(x)

class SIMPLENET(nn.Module):

    def __init__(self, num_classes=20):
        super(SIMPLENET, self).__init__()
        self.ds_conv0 = _CBNReLU(3, 32, 3, 2)

    def forward(self, x):
        # size = x.size()[2:]
        x = self.ds_conv0(x)
        x = nn.functional.interpolate(x, size=(512, 512), mode='bilinear', align_corners=False)

        return x
```
That exports ok to onnx, visualizing the result using [netron](https://github.com/lutzroeder/netron) we have:
![image](https://user-images.githubusercontent.com/2473733/63008256-894c0f80-be82-11e9-9352-93b872c53781.png)

But notice that I've used `size=(512,512)` instead of the size of the actual input, if I use `size = x.size()[2:]` in that interpolate (or anywhere) the generated onnx graph looks like this:
![image](https://user-images.githubusercontent.com/2473733/63008456-f364b480-be82-11e9-83cc-f9286d43bc90.png)

A bunch of `Gather`, `Slice`, `Cast`, `Unsqueeze` nodes are generated which lead to a `Concat` that I'm never using, I know that there were some issues using dynamic sizes when exporting to onnx but it's the first time I've seen this extra nodes being generated.

Everything would be ok since they don't seem to lead anywhere but there are a lot of new generated issues when trying to export this onnx graph to tools like TensorRT, where those Gathers fail because of dimensions.

My fix for now was to use statically defined dimensions, but I'm putting the issue here so if anyone comes through something similar there is some reference. Also, what would be the best way to obtain sizes during training then?

## Expected behavior

No extra nodes being generated when exporting to onnx while using `size = x.size()[2:]` or `size()` inside forward.

## Environment

```
Collecting environment information...
PyTorch version: 1.2.0a0+8554416
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 430.40
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0a0+8554416
[pip] torchvision==0.5.0a0+8635be9
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] torch                     1.2.0a0+8554416          pypi_0    pypi

```

## Additional context

Didn't see this on 1.0.1 if I recall correctly.

**Comment by leminhhiep20691** [comment]
File: System/data/app/com.duy.c.cpp.compiler-PwBeGx6b4K3LiQfaBi5HeQ==/lib/arm/libnative-loader.so
MD5: 4d:f7:5f:1b:30:81:29:5c:0e:6e:a2:29:04:7a:65:96
SHA1: 17:6f:d3:6c:b0:f5:85:03:ae:08:16:c3:a3:83:9b:b5:45:08:d4:32
SHA256: 87:7b:b7:07:52:b5:fb:e7:14:de:03:90:11:6a:76:b7:2b:10:43:e2:8b:52:1e:3d:cd:ac:fe:be:22:58:ca:04

**Comment by bpinaya** [comment]
Going in a more in depth look it seems to be an issue of `x = nn.functional.interpolate`, since if I use something like:
```python
low = nn.functional.interpolate(x, scale_factor=4, mode='bilinear', align_corners=False)
```
I encounter the same issue, extra unwanted nodes in graph, only by passing the size directly I was able to export it without the clutter.

**Comment by leminhhiep20691** [comment]
https://github.com/pytorch/pytorch/issues/24316#issuecomment-521214022

**Comment by zhangguanheng66** [comment]
@houseroad any thoughts?

**Comment by BowenBao** [comment]
@bpinaya Hi, I just tried your example(`size = x.size()[2:]`) with pytorch `1.3.0a0+5ec1c29` built from source, it seems the model exported fine.

![image](https://user-images.githubusercontent.com/9376104/63075584-132dc400-bee7-11e9-8681-a9c110798b6e.png)

Despite the pytorch version difference, could you check loading the model in https://lutzroeder.github.io/netron/, or update your netron to latest version? it might be possible that it is outdated, and rendering the graph incorretly.

**Comment by bpinaya** [comment]
Hi @BowenBao, I don't think it's the netron version since even if I print the model in pytorch I could see those layers, I'll try with `1.3.0a0+5ec1c29` latter today.

**Comment by BowenBao** [comment]
@bpinaya - have you tried the above netron link, and it still shows unused `concat`?

**Comment by bpinaya** [comment]
Hi @BowenBao , sorry for the delay I was a bit busy at work, using the link you provided https://lutzroeder.github.io/netron/ I see the same as you:
![image](https://user-images.githubusercontent.com/2473733/63359532-346e3480-c36d-11e9-8d1b-71ee17b568be.png)

If I just print the network I get:
```
SIMPLENET(
  (ds_conv0): _CBNReLU(
    (conv): Sequential(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
    )
  )
)

```
And when exporting with verbose enabled I can see the exported network as:
```
graph(%input : Float(1, 3, 512, 512),
      %ds_conv0.conv.0.weight : Float(32, 3, 3, 3),
      %ds_conv0.conv.1.weight : Float(32),
      %ds_conv0.conv.1.bias : Float(32),
      %ds_conv0.conv.1.running_mean : Float(32),
      %ds_conv0.conv.1.running_var : Float(32),
      %ds_conv0.conv.1.num_batches_tracked : Long()):
  %7 : Long() = onnx::Constant[value={2}](), scope: SIMPLENET
  %8 : Tensor = onnx::Shape(%input), scope: SIMPLENET
  %9 : Long() = onnx::Gather[axis=0](%8, %7), scope: SIMPLENET # /home/bpinaya/Documents/kobiRepos/kobi_ai/models/simplenet.py:23:0
  %10 : Long() = onnx::Constant[value={3}](), scope: SIMPLENET
  %11 : Tensor = onnx::Shape(%input), scope: SIMPLENET
  %12 : Long() = onnx::Gather[axis=0](%11, %10), scope: SIMPLENET # /home/bpinaya/Documents/kobiRepos/kobi_ai/models/simplenet.py:23:0
  %13 : Float(1, 32, 255, 255) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%input, %ds_conv0.conv.0.weight), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/Conv2d[0] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/modules/conv.py:340:0
  %14 : Float(1, 32, 255, 255) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%13, %ds_conv0.conv.1.weight, %ds_conv0.conv.1.bias, %ds_conv0.conv.1.running_mean, %ds_conv0.conv.1.running_var), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/BatchNorm2d[1] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:1656:0
  %15 : Float(1, 32, 255, 255) = onnx::Relu(%14), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/ReLU[2] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:911:0
  %16 : Tensor = onnx::Unsqueeze[axes=[0]](%9)
  %17 : Tensor = onnx::Unsqueeze[axes=[0]](%12)
  %18 : Tensor = onnx::Concat[axis=0](%16, %17)
  %19 : Tensor = onnx::Constant[value= 1  1 [ Variable[CPUFloatType]{2} ]](), scope: SIMPLENET
  %20 : Tensor = onnx::Cast[to=1](%18), scope: SIMPLENET
  %21 : Tensor = onnx::Shape(%15), scope: SIMPLENET
  %22 : Tensor = onnx::Slice[axes=[0], ends=[4], starts=[2]](%21), scope: SIMPLENET
  %23 : Tensor = onnx::Cast[to=1](%22), scope: SIMPLENET
  %24 : Tensor = onnx::Div(%20, %23), scope: SIMPLENET
  %25 : Tensor = onnx::Concat[axis=0](%19, %24), scope: SIMPLENET
  %output : Float(1, 32, 512, 512) = onnx::Upsample[mode="linear"](%15, %25), scope: SIMPLENET # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:2503:0
  return (%output)

```
So you see those unsqueeze and cast nodes are already there, it's not an issue of netron itself.

But the thing is that the network is much simpler, if I use a `size=(512,512)` instead of a `layersize = x.size()[2:]` and then `size=layersize` 
I get this output of onnx with verbose:
```
graph(%input : Float(1, 3, 512, 512),
      %ds_conv0.conv.0.weight : Float(32, 3, 3, 3),
      %ds_conv0.conv.1.weight : Float(32),
      %ds_conv0.conv.1.bias : Float(32),
      %ds_conv0.conv.1.running_mean : Float(32),
      %ds_conv0.conv.1.running_var : Float(32),
      %ds_conv0.conv.1.num_batches_tracked : Long()):
  %7 : Float(1, 32, 255, 255) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%input, %ds_conv0.conv.0.weight), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/Conv2d[0] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/modules/conv.py:340:0
  %8 : Float(1, 32, 255, 255) = onnx::BatchNormalization[epsilon=1e-05, momentum=0.9](%7, %ds_conv0.conv.1.weight, %ds_conv0.conv.1.bias, %ds_conv0.conv.1.running_mean, %ds_conv0.conv.1.running_var), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/BatchNorm2d[1] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:1656:0
  %9 : Float(1, 32, 255, 255) = onnx::Relu(%8), scope: SIMPLENET/_CBNReLU[ds_conv0]/Sequential[conv]/ReLU[2] # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:911:0
  %10 : Tensor = onnx::Constant[value= 1.0000  1.0000  2.0078  2.0078 [ Variable[CPUFloatType]{4} ]](), scope: SIMPLENET
  %output : Float(1, 32, 512, 512) = onnx::Upsample[mode="linear"](%9, %10), scope: SIMPLENET # /home/bpinaya/anaconda3/envs/pytorch-twelve/lib/python3.7/site-packages/torch/nn/functional.py:2503:0
  return (%output)


```

I get this network on netron:
![image](https://user-images.githubusercontent.com/2473733/63359964-e443a200-c36d-11e9-9a9b-33d64b09839e.png)

Which should be the expected output, in the meanwhile I'm just writing the dimensions of the layers by hand instead of getting them with x.size()[2:]

Those nodes become an issue when exporting an onxx file to trt for example, because of unsupported layers and so.

**Comment by BowenBao** [comment]
Hi @bpinaya, thank you for your detailed response.

The graph with `unsqueeze` and `concat` is in fact expected. Note that the value of `x.size()[2:]` could be dynamic. So the exported ONNX graph has no choice but to construct this `shape`, `concat` routine.

**Comment by bpinaya** [comment]
Well that makes sense, I guess I'll just keep the sizes static since those nodes are not exporting in tensorrt. Thanks for your input!
