### ISSUE TITLE
Does openvino MKLDNN support 2 CPUs (ex: xeon 6148 x 2)

### ISSUE THREAD

**Issue by fatalfeel** [pytorch/pytorch#24312]
https://www.asus.com/us/Commercial-Servers-Workstations/WS-C621E-SAGE/He...
https://software.intel.com/en-us/articles/intel-and-facebook-collaborate...

If I use 2 xeon 6148 cpus in 2 socket  of one mainboard (asus WS C621E)

Question: 2 cpus are faster than 1 cpu?

**Comment by soumith** [comment]
please ask on MKLDNN repo

**Comment by vpirogov** [comment]
Answered in https://github.com/intel/mkl-dnn/issues/534
