### ISSUE TITLE
When I apply tensor.cpu(), it spent 3 seconds !  Why is it so slow???

### ISSUE THREAD

**Issue by XuejianJia** [pytorch/pytorch#24318]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
`output = model(img.unsqueeze(0)) # output.size() = [135, 240]
density_map = output.data.cpu().numpy() # cost 3 seconds` 

Here is my code:
```
            time_start = time.time()
            img = transform(Image.fromarray(image).convert('RGB')).cuda() # 0.05s
            time_end = time.time()
            print("time1: {}".format(time_end - time_start))

            time_start = time.time()
            output = model(img.unsqueeze(0)) # 0.002s
            time_end = time.time()
            print("time2: {}".format(time_end - time_start))
            
            time_start = time.time()
            torch.cuda.synchronize()
            density_map = output.data.cpu().numpy() # 3s!!!
            time_end = time.time()
            print("time3: {}".format(time_end - time_start))
```

**Comment by vadimkantorov** [comment]
For faithful measuring, please use `torch.cuda.synchronize()` before the CPU call. GPU computation is asynchrounous in many cases, and likely you are just waiting for the model to run through (especially if your batch size is large)

**Comment by XuejianJia** [comment]
> For faithful measuring, please use `torch.cuda.synchronize()` before the CPU call. GPU computation is asynchrounous in many cases, and likely you are just waiting for the model to run through (especially if your batch size is large)

I used `torch.cuda.synchronize()` before the CPU call, but it doesn't work.
And my batch size is 1.
I just convert a tensor from `cuda` to `cpu`(use `tensor.cpu()`), this tensor is the output of my model, this tensor's size is [135, 240], it's not really big, but it cost 3 seconds(not including the model's inference time).
Do you have any other Suggestions? Thank you very much!

**Comment by SsnL** [comment]
It is because of the synchronization @vadimkantorov mentioned. There are likely unfinished kernel at the point of calling `.cpu()` so in fact the total amount of time taken to copy to CPU is less than 3s. Just do `torch.cuda.synchronize()` before measuring times and you will see the true time taken.

**Comment by XuejianJia** [comment]
> It is because of the synchronization @vadimkantorov mentioned. There are likely unfinished kernels at the point of calling `.cpu()` so in fact the total amount of time taken to copy to CPU is less than 3s. Just do `torch.cuda.synchronize()` before measuring times and you will see the true time taken.

Thank you all. Just like you said, the true time is 0.0001s.
Is there any way to speed up the unfinished kernels?
My real needs are to display these tensors(produced by CNN) in real time.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
