### ISSUE TITLE
[Question] Who can tell me where is the windows version torch in PYPI? It just like missing.

### ISSUE THREAD

**Issue by xiaohuihuichao** [pytorch/pytorch#24310]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
Yes, it is not hosted on PyPI. Do you have specific reasons to have it on PyPI? Actually, we can only store packages with only one spec on it, which will be cuda 10.0 if we do that. cc @soumith

**Comment by henribru** [comment]
My reason for wanting Windows wheels on PyPI is that I use both Windows and Linux and dependency management tools like Pipenv and Poetry do a bad job of letting you fetch packages from different locations depending on the platform. Juggling multiple requirements files gets annoying.

**Comment by soumith** [comment]
in the past, we didn't upload Windows binaries due to PyPI because of worry of binary size, both current and future. PyPI has binary limits, and we were worried that with the windows binary we would exceed them.
But recently @peterjc123 and I discussed this, we might push windows binaries to PyPI from 1.4 onwards.

**Comment by sinoroc** [comment]
Has the position on publishing Windows _wheels_ to _PyPI_ been reconsidered?

I believe it is a known fact already: the size limits on _PyPI_ can be modified or removed on a case by case basis. See the [PyPI topic on "How do I get a file size limit exemption or increase for my project?"](https://pypi.org/help/#file-size-limit).

**Comment by peterjc123** [comment]
@sinoroc Please see our latest discussion in https://github.com/pytorch/vision/issues/1774.
