### ISSUE TITLE
Autocomplete cannot find nn.Module methods

### ISSUE THREAD

**Issue by njellinas** [pytorch/pytorch#24326]
## 🐛 Bug

When I implement a class that inherits nn.Module, the autocomplete of PyCharm does not find the reference of a custom method. For example in the code below PyCharm shows a warning: Cannot find reference 'random_method' in '(input: (Any, ...), kwargs: dict) -> Any'

## To Reproduce

1. Provided code sample

```python
import torch
import torch.nn as nn


class CustomModule(nn.Module):
    def __init__(self, dims):
        super(CustomModule, self).__init__()
        self.dims = dims

    def forward(self, x):
        return x + torch.randn_like(x)

    def random_method(self):
        return torch.randn(self.dims)


if __name__ == '__main__':
    dnn = CustomModule(100)
    out = dnn.random_method()
    print(out)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): Ubuntu 18.04.02
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zhangguanheng66** [comment]
Cannot reproduce the warning. The script works fine (I test on the master branch).

**Comment by njellinas** [comment]
The script works fine eventually, but in PyCharm, when you write the line where you call the `random_method` method, it shows a linter warning. It cannot identify it as a class method

**Comment by ZaydH** [comment]
FWIW, I also get this error on the code provided by @njellinas.  Below is a screen shot:

![image](https://user-images.githubusercontent.com/6292018/63424358-192e1400-c3c3-11e9-9e96-99b9b591e647.png)

**Comment by ZaydH** [comment]
I believe this issue may be related to PyCharm and not `torch` however.  I get the same linter warnings on even the `Module`'s base methods.  I added the line `dnn.forward(torch.rand((10,10)))` to your example and still get the warning.  See below.

![image](https://user-images.githubusercontent.com/6292018/63425135-bccbf400-c3c4-11e9-94bc-15a34856d3ab.png)

I will file a bug with JetBrains and see if they respond.

**Comment by njellinas** [comment]
In pytorch version 1.0.1 it does not show this however.

**Comment by ZaydH** [comment]
@njellinas Good point.  I only saw these errors after upgrading to `torch` 1.2.0.  I submitted a [JetBrains case](https://youtrack.jetbrains.com/issue/PY-37601).  We'll see if they bounce  it back here.

**Comment by ZaydH** [comment]
@njellinas Another weird issue with `torch` ver. 1.2 in PyCharm is around the `Module`'s `cuda` method.  In versions of `torch` before 1.2, the `device` field could be empty, i.e.,  call `self.cuda()`. Now in `torch` 1.2, it reports the warning:

`Parameter 'device' unfilled`

This may or may not be related.  Depending on feedback, I may open another case for that.

**Comment by njellinas** [comment]
I have not used VSCode in a while. But as for the cuda issue that you mentioned, I guess it is because you shouldn't use this method anymore, but instead the `.to(device)`

**Comment by Vichoko** [comment]
In a custom module you can fix it adding the following method:
```
    def __call__(self, *input, **kwargs) -> typing.Any:
        return super().__call__(*input, **kwargs)
```

The problem is in pytorch modules like `nn.ModuleList `doesn't pick up append.

**Comment by njellinas** [comment]
Your solution worked, but it's sad that you have to do this for every model class that you write :P

**Comment by CielAl** [comment]
It works!!!
May I have a little bit more about the details of what causes the issue? :)


> The problem is in PyTorch modules like `nn.ModuleList `doesn't pick up the append method showing the same warning.
