### ISSUE TITLE
Build system cannot find MKL libraries

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#24334]
## 🐛 Bug

I'm trying to install PyTorch with MKL as the BLAS/LAPACK provider, but it fails to find the library and does not specify how to tell it where the library is located.

## To Reproduce

```console
$ python -s setup.py --no-user-cfg build
...
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - guide - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel_lp64 - mkl_core - pthread - m]
--   Library mkl_intel_lp64: not found
-- Checking for [mkl_intel - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
CMake Error at cmake/Modules/FindMKL.cmake:370 (MESSAGE):
  MKL library not found.  Please specify library location
```

## Expected behavior

Since I specify `BLAS=MKL` and explicitly set `LIBRARY_PATH` and `LD_LIBRARY_PATH` to the directories containing the libraries, I expect it to pick up MKL, or at least tell me which environment variable I can set to help locate it.

## Environment

[spack-build-env.txt](https://github.com/pytorch/pytorch/files/3502294/spack-build-env.txt)

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): macOS 10.14.6
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.7.4
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A

**Comment by adamjstewart** [comment]
P.S. I see that a lot of CMake configure options do not have corresponding environment variables outlined in `setup.py`. If I'm trying to get the most control over the build, is it recommended that I installs with `cmake` instead of `python setup.py build`? It seems like `python setup.py build` just calls `cmake` for the actual installation.

**Comment by zhangguanheng66** [comment]
Have you installed the dependencies (a.k.a mkl)?

**Comment by adamjstewart** [comment]
Yes, I installed MKL on the system and set `LIBRARY_PATH` and `LD_LIBRARY_PATH` to `/opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/lib:/usr/lib`.
```console
$ ls /opt/intel/compilers_and_libraries_2019.4.233/mac/mkl/lib
libmkl_avx.dylib          libmkl_core.a             libmkl_intel_lp64.dylib   libmkl_mc.dylib           libmkl_tbb_thread.a       libmkl_vml_mc.dylib
libmkl_avx2.dylib         libmkl_core.dylib         libmkl_intel_thread.a     libmkl_mc3.dylib          libmkl_tbb_thread.dylib   libmkl_vml_mc2.dylib
libmkl_avx512.dylib       libmkl_intel_ilp64.a      libmkl_intel_thread.dylib libmkl_rt.dylib           libmkl_vml_avx.dylib      libmkl_vml_mc3.dylib
libmkl_blas95_ilp64.a     libmkl_intel_ilp64.dylib  libmkl_lapack95_ilp64.a   libmkl_sequential.a       libmkl_vml_avx2.dylib     locale
libmkl_blas95_lp64.a      libmkl_intel_lp64.a       libmkl_lapack95_lp64.a    libmkl_sequential.dylib   libmkl_vml_avx512.dylib
```

**Comment by xkszltl** [comment]
Do you have symlink /opt/intel/mkl to /opt/intel/compilers_and_libraries/mac/mkl on mac?
On linux it's created by intel installer automatically.
Here's the related code: https://github.com/pytorch/pytorch/blob/59094c409ea552001d0f5356df9fdb0086ccee12/cmake/Modules/FindMKL.cmake#L122
I think it doesn't know how to dig deeper automatically.

If not, try creating that manually.
It could probably be a work-around.

**Comment by adamjstewart** [comment]
I do have that symlink:
```console
$ ls -l /opt/intel/mkl
lrwxr-xr-x  1 root  wheel    33B Jul 29 16:48 /opt/intel/mkl -> ./compilers_and_libraries/mac/mkl
```

**Comment by adamjstewart** [comment]
For the record, this bug still occurs in the latest 1.3.0 release. Any updates on how to resolve this?

**Comment by soumith** [comment]
@adamjstewart here's a simple workaround: `export CMAKE_PREFIX_PATH="/opt/intel/compilers_and_libraries_2019.4.233/mac/mkl:$PATH"`

**Comment by adamjstewart** [comment]
@soumith it worked, thanks! 

I'm fine with closing this issue, although we should probably:

1. Add your `CMAKE_PREFIX_PATH` suggestion to the `Please specify library location` error message, and/or
2. Come up with a more robust way of locating the library.

**Comment by adamjstewart** [comment]
@soumith unfortunately I ran into this issue again, this time on Linux. I have Intel MKL installed in `/home/ec2-user/spack/opt/spack/linux-amzn2-broadwell/gcc-7.3.1/intel-mkl-2019.5.281-lt6clgk2ttcvwq7h6luxwlykmhk6mbmi` using the [Spack](https://spack.io) package manager. I'm adding the `mkl` subdirectory of this directory to my `CMAKE_PREFIX_PATH` like you suggested. The issue is that unlike on macOS, Intel doesn't place the libraries in `mkl/lib`, it places them in `mkl/lib/intel64`:
```console
$ ls mkl/lib/intel64
libmkl_avx2.so                  libmkl_blacs_openmpi_lp64.a   libmkl_core.a         libmkl_intel_ilp64.so    libmkl_pgi_thread.so       libmkl_vml_avx2.so
libmkl_avx512_mic.so            libmkl_blacs_openmpi_lp64.so  libmkl_core.so        libmkl_intel_lp64.a      libmkl_rt.so               libmkl_vml_avx512_mic.so
libmkl_avx512.so                libmkl_blacs_sgimpt_ilp64.a   libmkl_def.so         libmkl_intel_lp64.so     libmkl_scalapack_ilp64.a   libmkl_vml_avx512.so
libmkl_avx.so                   libmkl_blacs_sgimpt_ilp64.so  libmkl_gf_ilp64.a     libmkl_intel_thread.a    libmkl_scalapack_ilp64.so  libmkl_vml_avx.so
libmkl_blacs_intelmpi_ilp64.a   libmkl_blacs_sgimpt_lp64.a    libmkl_gf_ilp64.so    libmkl_intel_thread.so   libmkl_scalapack_lp64.a    libmkl_vml_cmpt.so
libmkl_blacs_intelmpi_ilp64.so  libmkl_blacs_sgimpt_lp64.so   libmkl_gf_lp64.a      libmkl_lapack95_ilp64.a  libmkl_scalapack_lp64.so   libmkl_vml_def.so
libmkl_blacs_intelmpi_lp64.a    libmkl_blas95_ilp64.a         libmkl_gf_lp64.so     libmkl_lapack95_lp64.a   libmkl_sequential.a        libmkl_vml_mc2.so
libmkl_blacs_intelmpi_lp64.so   libmkl_blas95_lp64.a          libmkl_gnu_thread.a   libmkl_mc3.so            libmkl_sequential.so       libmkl_vml_mc3.so
libmkl_blacs_openmpi_ilp64.a    libmkl_cdft_core.a            libmkl_gnu_thread.so  libmkl_mc.so             libmkl_tbb_thread.a        libmkl_vml_mc.so
libmkl_blacs_openmpi_ilp64.so   libmkl_cdft_core.so           libmkl_intel_ilp64.a  libmkl_pgi_thread.a      libmkl_tbb_thread.so       locale
```
If I set `CMAKE_PREFIX_PATH` to the `mkl/lib/intel64` subdirectory, CMake finds the libraries but not the headers. Is there any other way we could hack CMake so that I can just tell it what directory to find the MKL libraries in?

**Comment by xkszltl** [comment]
symlink?

**Comment by adamjstewart** [comment]
I can manually add more symlinks, but the Intel library locations keep changing with every release. Package managers like Spack should ideally also support external packages, where we have no control over the installation layout and can't add symlinks. We generally avoid hacking things too much to retain support for external packages.

Ideally CMake would have an option like `-DMKL_LIBRARY_DIRS:PATH=/path/to/mkl/lib/intel64` or `-DMKL_LIBRARIES:PATH=/path/to/libmkl_avx2.so;libmkl_cdft_core.so;...`. This would allow a clear way to override the automatic search that fails.

**Comment by adamjstewart** [comment]
For the record, adding symlinks does work as a workaround, although I would love to see a less hacky solution.

**Comment by adamjstewart** [comment]
For anyone else who runs into this problem, setting `CMAKE_LIBRARY_PATH` to `<prefix>/mkl/intel64/lib` solved the problem for me on Linux.

**Comment by mahmoodn** [comment]
I also had the problem that MKL is missing by installer. Even setting INTEL_MKL_DIR in bash won't solve this. It seems that the `/opt/intel` is hard codded [here](https://github.com/pytorch/pytorch/blob/59094c409ea552001d0f5356df9fdb0086ccee12/cmake/Modules/FindMKL.cmake#L33).

I think this is a bug. I manually set my own path there and then MKL was fine.

**Comment by vmiheer** [comment]
@adamjstewart, can https://github.com/pytorch/pytorch/issues/24334#issuecomment-568368908 be fixed by modifying FindMKL.cmake?
Why was this issue closed?
