### ISSUE TITLE
Build fails on FreeBSD with the unclear cause, see the attached log

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#24346]
https://people.freebsd.org/~yuri/py-pytorch-error.log

**Comment by zhangguanheng66** [comment]
Have you install all the dependencies?

**Comment by yurivict** [comment]
> Have you install all the dependencies?


I think so. Does something look like it is missing?
It passes the configure stage that detects dependencies.

**Comment by yurivict** [comment]
This command fails:
```
$ cd /usr/ports/science/py-pytorch/work/.build/sleef/src/libm && /usr/ports/science/py-pytorch/work/.build/sleef/bin/mkalias
Usage : /usr/ports/science/py-pytorch/work/.build/sleef/bin/mkalias <vector width> <vector FP type> <vector int type> <mangled ISA> <extension>
```

It looks like the required arguments weren't supplied.

**Comment by soumith** [comment]
@umanwizard was interested in helping out on FreeBSD builds in his own time

**Comment by yurivict** [comment]
At this point I am stuck with the ```mkalias``` command from ```sleef``` failing because it is called without arguments, see above.

**Comment by umanwizard** [comment]
I have gotten past this step on my home machine. As you can see from https://sleef.org/ , sleef only builds on FreeBSD starting with version 3.3.1.

If you don't want to wholesale upgrade the version, there are (IIRC) two commits that need to be cherry-picked from the master Sleef repo into PyTorch's third_party/sleef . I can let you know which ones later tonight.

**Comment by yurivict** [comment]
Now I've succeeded building. -)

Thanks!

**Comment by yurivict** [comment]
> If you don't want to wholesale upgrade the version, there are (IIRC) two commits that need to be cherry-picked from the master Sleef repo into PyTorch's third_party/sleef . I can let you know which ones later tonight.

FreeBSD has a package for sleef-3.4.0. How can I just use this package instead of the bundled version?

**Comment by umanwizard** [comment]
@soumith Do you know how to get the build system to use an external Sleef? (Asking this to you as it's not really specific to FreeBSD).

**Comment by soumith** [comment]
@umanwizard needs some cmake refactoring. Cant do this out of the box without some patches afaik.

**Comment by umanwizard** [comment]
@yurivict BTW just to set expectations correctly in case you spend significant time working on this: CUDA does not support FreeBSD, so unless that is someday implemented, PyTorch will be limited to CPU on FreeBSD even if you do get it working.

**Comment by yurivict** [comment]
> PyTorch will be limited to CPU on FreeBSD

I know this, thanks.

**Comment by rajhlinux** [comment]
I get this error on FreeBSD 13.1:

```
cmake \
-D BUILD_SHARED_LIBS=ON \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D PYTHON_EXECUTABLE:PATH=`which python3` \
-D CMAKE_INSTALL_PREFIX:PATH=/usr/home/user/pytorch/build/install ..
```

```
In file included from /usr/include/xlocale.h:37:
/usr/local/include/fmt/locale.h:3:2: warning: fmt/locale.h is deprecated, include fmt/format.h or fmt/xchar.h instead [-W#warnings]
#warning fmt/locale.h is deprecated, include fmt/format.h or fmt/xchar.h instead
```
