### ISSUE TITLE
cdist allocates a huge amount of memory in the bachward pass (pytorch 1.2.0)

### ISSUE THREAD

**Issue by aalibey** [pytorch/pytorch#24345]
## 🐛 Bug

I was using cdist in pytorch 1.1.0, the backward pass worked perfectly. Now with the new version that supports batching (1.2.0) It shows a CUDA out of memory error ! 

It tried to allocate hundreds of GiB of memory, depending the size of the vector. For me It was cdist(emb, emb), with emb of size (196,16000).

## Environment

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): Arch Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10
 - GPU models and configuration: Titan Xp
 - Any other relevant information:

cc @ngimel

**Comment by soumith** [comment]
cc: @gchanan to re-route to whoever fixed cdist

**Comment by gchanan** [comment]
CC @ifedan, who I know has a different patch out for this.

**Comment by ranahanocka** [comment]
Confirming this issue is also happening for me (cuda 10, python 3.6, Ubuntu). 
Is there a work around / patch?

**Comment by aalibey** [comment]
> Confirming this issue is also happening for me (cuda 10, python 3.6, Ubuntu).
> Is there a work around / patch?

cdist is coded in C++, and I think it has to be re-coded in C++ in order to work as before. I don't see any turnaround for now, I came back to pytorch 1.1.0 so that I can use cdist.
Even pdist has the same problem, since I tried to python-code cdist using pdist.

**Comment by LucaMoschella** [comment]
I also have this issue.

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Manjaro Linux
GCC version: (GCC) 9.1.0
CMake version: version 3.15.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 430.26
cuDNN version: /usr/lib/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.2.0
[pip3] torch-cluster==1.4.2
[pip3] torch-geometric==1.3.0
[pip3] torch-scatter==1.3.1
[pip3] torch-sparse==0.4.0
[pip3] torch-spline-conv==1.1.0
[pip3] torchvision==0.4.0
[conda] Could not collect
```

**Comment by mberr** [comment]
A (non-optimized) workaround that I am currently using:

for L2:
```python
def cdist2(x, y):
    # |x_i - y_j|_2^2 = <x_i - y_j, x_i - y_j> = <x_i, x_i> + <y_j, y_j> - 2*<x_i, y_j>
    x_sq_norm = x.pow(2).sum(dim=-1)
    y_sq_norm = y.pow(2).sum(dim=-1)
    x_dot_y = x @ y.t()
    sq_dist = x_sq_norm.unsqueeze(dim=1) + y_sq_norm.unsqueeze(dim=0) - 2*x_dot_y
    # For numerical issues
    sq_dist.clamp_(min=0.0)
    return torch.sqrt(sq_dist)
```

for L1
```python
class L1CDist(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x1, x2):
        ctx.save_for_backward(x1, x2)

        # cdist.forward does not have the memory problem
        return torch.cdist(x1, x2, p=1)

    @staticmethod
    def backward(ctx, grad_dist):
        # This is a pattern that is very convenient - at the top of backward
        # unpack saved_tensors and initialize all gradients w.r.t. inputs to
        # None. Thanks to the fact that additional trailing Nones are
        # ignored, the return statement is simple even when the function has
        # optional inputs.
        grad_x1 = grad_x2 = None

        # Retrieve saved values
        x1, x2 = ctx.saved_tensors
        dims = x1.shape[1]

        # These needs_input_grad checks are optional and there only to
        # improve efficiency. If you want to make your code simpler, you can
        # skip them. Returning gradients for inputs that don't require it is
        # not an error.
        if ctx.needs_input_grad[0]:
            grad_x1 = torch.empty_like(x1)
        if ctx.needs_input_grad[1]:
            grad_x2 = torch.empty_like(x2)

        if any(ctx.needs_input_grad):
            for i in range(dims):
                #: sign: shape: (n1, n2)
                sign = torch.sign(x1[:, None, i] - x2[None, :, i])
                if ctx.needs_input_grad[0]:
                    grad_x1[:, i] = torch.sum(grad_dist * sign, dim=1)
                if ctx.needs_input_grad[1]:
                    grad_x2[:, i] = -torch.sum(grad_dist * sign, dim=0)

        return grad_x1, grad_x2

cdist1 = L1CDist.apply
```

**Comment by jasam-sheja** [comment]
I'm facing the same problem as @LucaMoschella (After reducing the #samples, no error rises): 
```python
RuntimeError: CUDA error: invalid configuration argument.
```
 However, I'm using the batched version of cdist, which is available on version 1.3, so I modified the workaround of @mberr to support batching (still not-optimized):
```python
def cdist2(x, y):
    # |x_i - y_j|_2^2 = <x_i - y_j, x_i - y_j> = <x_i, x_i> + <y_j, y_j> - 2*<x_i, y_j>
    x_sq_norm = x.pow(2).sum(dim=-1, keepdim=True)
    y_sq_norm = y.pow(2).sum(dim=-1)
    x_dot_y = x @ y.transpose(-1,-2)
    sq_dist = x_sq_norm + y_sq_norm.unsqueeze(dim=-2) - 2*x_dot_y
    # For numerical issues
    sq_dist.clamp_(min=0.0)
    return torch.sqrt(sq_dist)
```

## Reproduce

```python
import torch


def test(b,n,m):
    '''
    b: batch size
    n: number of samples
    m: number of dimensions
    '''
    torch.cuda.empty_cache()
    x = torch.rand(b,n,m, device='cuda', requires_grad=True)
    y = torch.cdist(x,x)
    torch.cuda.empty_cache()
    print(' forward memory', torch.cuda.memory_cached()/2**20)
    y.sum().backward()
    print('backward memory', torch.cuda.memory_cached()/2**20)
    del x,y
```
`test(2**6, 2**6, 2**14)` causes `RuntimeError: CUDA out of memory`
`test(2**8, 2**6, 2**6)` causes `RuntimeError: CUDA error: invalid configuration argument`
`test(2**6, 2**8, 2**6)` causes `RuntimeError: CUDA error: invalid configuration argument`

I don't know what to make of these tests! Anyway, by trying different batch sizes, #samples, #dims, it seems to me that `CUDA out of memory` only occurs when #dims is big; otherwise, it's `CUDA error: invalid configuration argument` when either of batch sizes or #samples is big. 

## Environment
```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Quadro RTX 6000
GPU 1: Quadro RTX 6000
GPU 2: Quadro RTX 6000
GPU 3: Quadro RTX 6000

Nvidia driver version: 418.87.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0with
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch```

**Comment by ngimel** [comment]
This is fixed for 2-norm, re-open if other norms are needed.

**Comment by mberr** [comment]
Hi @ngimel,

I am still interested in 1-norm, since the workaround from https://github.com/pytorch/pytorch/issues/24345#issuecomment-533024557 is rather slow due to using Python loops (around `0.8` seconds for input of shape `(10_000, 100)`). I can provide additional measurements if needed.

As another remark: When using the native backward computation, the memory requirement seems to be exactly equal to the size of `x[:, None, :] - x[None, :, :]`, so the backward computation seems to re-create the full tensor of differences (which is not done in the forward pass).

**Comment by RuABraun** [comment]
@ngimel I am also interested!
