### ISSUE TITLE
Bugs in torch.std and torch.var

### ISSUE THREAD

**Issue by yunjey** [pytorch/pytorch#2436]
Torch Tensor (or FloatTensor) returns wrong values of `std` and `var`.
Below is sample code.

```python
import numpy as np
import torch

# torch tensor
x = torch.Tensor([[1, 2, 3, 4], 
                 [5, 6, 7, 10]])

print(x.std())      # 2.9154759474226504 
print(x.var())      # 8.5

# numpy tensor containing same values
y = np.array([[1, 2, 3, 4],
              [5, 6, 7, 10]])

print(y.std())      #4.75
print(y.var())     #7.4375
```

Which part of the code should I look to fix a bug?

**Comment by apaszke** [comment]
It's correct. PyTorch uses Bessel's correction by default, which causes the difference. `y.std(ddof=1)` and `y.var(ddof=1)` will give you the same results.
