### ISSUE TITLE
regarding hierarchy

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#24372]
## 🚀 Feature

currently the hierarchy looks like

torch.nn.modules.module.Module

this seems a bit weird, is it possible to make this look simpler,
for example, just 

torch.nn.modules

or

torch.nn.module

another example of such hierarchy

torch.nn.modules.activation.torch

torch inside torch?

is it possible to make this hierarchy a bit more minimalist, so same names are not repeated multiple times, and even similar names do not appear multiple times within the hierarchy, so modules then module then Module, would become just modules, or just module, and so on?

**Comment by zou3519** [comment]
I'm not sure I understand the request. `Module` lives at `torch.nn.Module`. How are you discovering these hierarchies?

**Comment by soumith** [comment]
I think you are talking about an autocomplete in some editor, and how activation.py has an `import torch` or that `module.py` which implements nn.Module is in `torch/nn/modules/module.py`.

I think this is fine. There is some other issue that we are tracking to make all imports to be absolute, and that will probably help your cause.
I'm closing this issue as non-actionable or wontfix

**Comment by vainaijr** [comment]
@zou3519, I discovered through auto autocomplete in google colab, it gives me these options, like torch inside torch.
