### ISSUE TITLE
Incorrect LibTorch download links on pytorch.org

### ISSUE THREAD

**Issue by mdlockyer** [pytorch/pytorch#24382]
It seems that the LibTorch download links on the PyTorch website are wrong for both Linux and Mac. When selecting Stable(1.2) the provided link points to nightly builds; specifically nightly latest, which will currently download a 1.3 dev build.

### Example download configuration:
![Screen Shot 2019-08-14 at 9 00 17 PM](https://user-images.githubusercontent.com/30844227/63067898-bc1ff300-bed6-11e9-9d9f-4b072342da3b.png)

### Contents of build-version file:
`1.3.0.dev20190814+cpu`

cc @ezyang @gchanan

**Comment by zou3519** [comment]
cc @brianjo @yf225.

I can repro this. We should fix it if that is not the correct link.

**Comment by yf225** [comment]
Related: https://github.com/pytorch/pytorch/issues/24120#issuecomment-520507067. I am building the missing libtorch v1.2.0 binaries and will have all them uploaded as soon as possible.

**Comment by soumith** [comment]
I'm fixing the nightly kinks

**Comment by soumith** [comment]
*links

**Comment by yf225** [comment]
@mdlockyer This is the full list of download links:
Linux CPU:
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-static-without-deps-1.2.0.zip

Linux CUDA 9.2:
https://download.pytorch.org/libtorch/cu92/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu92/libtorch-static-without-deps-1.2.0.zip

Linux CUDA 10.0:
https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-shared-without-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-static-with-deps-1.2.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-static-without-deps-1.2.0.zip

macOS CPU:
https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.2.0.zip

**Comment by ezyang** [comment]
@yf225 Can you make sure the website links get updated?
