### ISSUE TITLE
Pytorch Rollback Failure

### ISSUE THREAD

**Issue by robertson809** [pytorch/pytorch#24406]
## 🐛 Pyrotch Rollback Failure

When trying to install pytorch version 0.1.2, the install fails because of an error in setup.py

## To Reproduce

1. pip install torch=0.1.2

Gives output

Collecting torch==0.1.2
  Using cached https://files.pythonhosted.org/packages/c0/66/2a0696bdac7ed0a99b65f6d8a5da7bc2583835ea04cac058bcd982cbb9ef/torch-0.1.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-75pat8ja/torch/setup.py", line 12, in <module>
        from tools.setup_helpers.env import check_env_flag
    ModuleNotFoundError: No module named 'tools.setup_helpers'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-75pat8ja/torch/

**Comment by soumith** [comment]
we only started uploading working `pip` packages starting 0.4.0 or so. the `0.1.2` that you are getting is a source distribution that probably dont build. We cant delete them off pip if that's the outcome that make sense.

**Comment by robertson809** [comment]
So is there any way for me to get the 0.1.2 pytorch code?

**Comment by colesbury** [comment]
Yeah, the source is still on GitHub in the v0.1.2 branch: (`git clone https://github.com/pytorch/pytorch.git -b v0.1.2`)

https://github.com/pytorch/pytorch/tree/v0.1.2

I don't think any of the PyTorch devs have built 0.1.2 in a long time, so building it may be an adventure. You may need an older version of Python (3.5 or 2.7 should work) and CUDA if you want GPU support (CUDA 7.5 should work).
