### ISSUE TITLE
torch.cholesky throws CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by calincru** [pytorch/pytorch#24403]
## 🐛 Bug

`torch.cholesly` raises [title error] when called with a batch size greater than `(1 << 19) - 8`.

I noticed this behaviour before (see https://github.com/pytorch/pytorch/issues/22843) but now I realized that even though this is a CUDA limitation, it could be implemented with a for loop over the maximum permissible batch size.

I'm doing something like this for now, but I'm not a PyTorch expert and I'm thinking that it can be made even faster.

```python
def cholesky(x, *args, **kwargs):
    shape = x.shape
    batch_size = np.prod(shape[:-2])
    cuda_batch_size = (1 << 19) - 8

    if batch_size <= cuda_batch_size:
        return torch.cholesky(x, *args, **kwargs)

    x = x.view(-1, shape[-1], shape[-1])
    acc = torch.empty_like(x)
    for i in range(0, batch_size, cuda_batch_size):
        indices = torch.arange(
                i,
                min(batch_size, i + cuda_batch_size),
                device=x.device,
                dtype=torch.int64)
        acc[indices] = torch.cholesky(x[indices], *args, **kwargs)

    return acc.view(shape)
```

## To Reproduce

```python
torch.cholesky(torch.eye(2, device='cuda').expand((1 << 19) - 7, -1, -1))
```

## Environment

PyTorch 1.2.0, CUDA 10

cc @vishwakftw

**Comment by vishwakftw** [comment]
This is a MAGMA bug. Please see https://github.com/pytorch/pytorch/issues/22843#issuecomment-511313633

We already perform a looping for solve methods, so it shouldn’t be hard to do for cholesky and other functions too.

I’ll send a PR by evening for this.

**Comment by calincru** [comment]
@vishwakftw Right, sorry, I forgot about that comment of yours.
