### ISSUE TITLE
model deployment ：Multiple serial models，using 3Dconv？？

### ISSUE THREAD

**Issue by abbyQu** [pytorch/pytorch#24452]
## ❓ Questions and Help

I have about 4 to 10 models to execute serially，every model is 3D-convolutional model，I have tried TensorRT,but TensorRT only support 2 D conv,
what else can I try?

The needs are: stable and fast

**Comment by jeffreyksmithjr** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
