### ISSUE TITLE
Migrate `_min` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24525]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by mrshenli** [comment]
self-assigned to reserve for onboarding.

**Comment by mrshenli** [comment]
un-assign myself. This is no longer reserved for bootcamp. Please feel free to grab it if you are interested.
