### ISSUE TITLE
Migrate `_cat` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24520]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
I'm bumping the priority of this as it is the ONLY remaining function in TH that uses TensorList.

**Comment by gchanan** [comment]
@Baranowski have you made progress on this?  We have a diff that depends on this (adding padding), so there is some coordination effort here.

**Comment by Baranowski** [comment]
@gchanan Yes, I'm working on this and debugging my implementation now. But since I'm new to the project, I will be relatively slow with it.

**Comment by Baranowski** [comment]
FYI status update: My implementation now passes all the tests but I'm seeing a massive performance regression so I'm going to debug that.

**Comment by Baranowski** [comment]
@gchanan, any preference about implementing it from scratch with TensorIterator vs. keeping as much of the TH code unchanged as possible? @nikitaved suggested I should do the former. Also, cc @ngimel  as per his suggestion.

**Comment by ngimel** [comment]
While in general I favor reusing TensorIterator whenever possible, cuda implementation of cat seems like a very tricky case for it. The approach taken by cpu porting of cat to use TensorIterator cannot be directly reused in cuda (it would result in launching as many kernels as there are tensors, and that kills performance), and existing cat kernels are clever and flexible, reasonably efficiently handling the tensors of wildly differing sizes. So my recommendation here would be to reuse THC kernels. For benchmarks, I'd suggest 2 main usecases: catting large number (100-1000) of 1d tensors of very different sizes, this is typically encountered when flattening parameters of the model, and catting relatively small number (5-50) of similarly sized tensors across different dimensions.
