### ISSUE TITLE
Migrate `addmm` and `addmm_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24534]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by zasdfgbnm** [comment]
Self assigning this for a fix of #29984

cc: @csarofeen @ptrblck for visibility

**Comment by VitalyFedyunin** [comment]
Unassigning due to priority

**Comment by Baranowski** [comment]
Other TH operators depend on `addmm`. Namely: `addmv`, `addr` and `addbmm`. @VitalyFedyunin, how do you suggest I deal with that? A couple possibilities I can think of:

1. migrate `addmm` to ATen but leave the old TH implementation (without dispatching `addmm` to it) until all those ops are migrated.
2. have those TH operators internally use the new ATen `addmm` (not sure if that's possible and whether there might be performance hit)

**Comment by zasdfgbnm** [comment]
There is already a PR migrating addmv and mv to ATen:
https://github.com/pytorch/pytorch/pull/30898

**Comment by ezyang** [comment]
@Baranowski Yes, it's likely that the cluster of the matrix multiply / BLAS operations are most conveniently done all in one go. Check on prior work first.

**Comment by Baranowski** [comment]
Thank you for linking the PR, zasdfgbnm, and for writing it in the first place. I will wait until it's merged, otherwise one of use will get in the other's way. Besides, basing my patch on your changes will save me a lot of mental work.

**Comment by VitalyFedyunin** [comment]
It is merged

**Comment by anjali411** [comment]
@Baranowski are you working on this?

**Comment by Baranowski** [comment]
I was just about to resume.

**Comment by Baranowski** [comment]
I have ported `addmm` but `addbmm` and `addr` depend on it, so I suggest I will move those to ATen in the same PR.

**Comment by VitalyFedyunin** [comment]
SGTM
