### ISSUE TITLE
Migrate `eig` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24553]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry

**Comment by anjali411** [comment]
making it hi priority because `torch.eig` is a useful op for audio community (e.g., ESPnet) and needs to be supported for complex tensors.
