### ISSUE TITLE
Migrate `fmod` and `fmod_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24565]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Marking high priority as these exercise zero_dim_dispatch_when_scalar

**Comment by ezyang** [comment]
An alternative is to just move the codegen into the implementation (which is a shorter thing to do).

**Comment by Baranowski** [comment]
@ezyang, is this still high priority even though it doesn't use zero_dim_dispatch_when_scalar?

**Comment by ezyang** [comment]
I guess not.
