### ISSUE TITLE
Migrate `fill_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24563]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by xuhdev** [comment]
Is this already in https://github.com/pytorch/pytorch/blob/gh/xuhdev/46/orig/aten/src/ATen/native/cuda/FillKernel.cu ?

**Comment by VitalyFedyunin** [comment]
It is
