### ISSUE TITLE
Migrate `index_select` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24578]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by anjali411** [comment]
making hi pri because index_select is used in a few backwards functions including `prod_safe_zeros_backward` and the TH functions don't support complex dtypes

**Comment by anjali411** [comment]
@Baranowski do you have any update on this issue?

**Comment by Baranowski** [comment]
@anjali411 no, sorry, my other issues are taking more time than I expected. Unassigning myself for now.
