### ISSUE TITLE
Incompatibility between torch.sum on Tensor and cuda.FloatTensor

### ISSUE THREAD

**Issue by blythed** [pytorch/pytorch#2457]
When I sum over a dimension of a Tensor, the dimension of the output is the 
same whereas with a cuda Tensor the dimension is reduced by one. 

Shouldn't these outputs agree?

E.g. 
>>> torch.sum(x) # x torch.FloatTensor
torch.FloatTensor of size 1x2x512

>>> torch.sum(y) # y torch.cuda.FloatTensor
torch.cuda.FloatTensor of size 2x512 (GPU 0)

**Comment by gchanan** [comment]
can you show code?  Your example isn't correct as torch.sum(x) over a tensor is going to return a scalar, not a tensor.

**Comment by blythed** [comment]
Sorry my bad, I think it was a problem my side
