### ISSUE TITLE
Input type (Byte) and weight type (Float) should be the same

### ISSUE THREAD

**Issue by DakshMiglani** [pytorch/pytorch#2458]
I was following the mnist guide but this shit doesn't want to work, just giving me headaches.

I'm actually importing the data from a numpy array using the from_numpy function.

I Keep Getting this error RuntimeError: Input type (Byte) and weight type (Float) should be the same

**Comment by alykhantejani** [comment]
Hi @DakshMiglani is it [this example](https://github.com/pytorch/examples/blob/master/mnist/main.py) that you are running? If so, can you provide the line number that causes this error?

**Comment by soumith** [comment]
your input is a ByteTensor. Call `.float()` on it.
