### ISSUE TITLE
Migrate `mm` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24596]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by zasdfgbnm** [comment]
Self assigning this for a fix of #29984

cc: @csarofeen @ptrblck for visibility

**Comment by VitalyFedyunin** [comment]
Hi-Pri because we need it to add complex numbers support.
Unassign due to priority.

**Comment by kurtamohler** [comment]
I have a branch that ports mm to ATen: https://github.com/pytorch/pytorch/compare/master...kurtamohler:port-mm-cuda?expand=1

However, performance decreased in some cases, so I'm looking into that before creating a PR.

**Comment by kurtamohler** [comment]
Also, should I add complex support to this, or will that be a different issue?

**Comment by ezyang** [comment]
complex mm can be a separate issue.

**Comment by rgommers** [comment]
Done in gh-34891, closing.
