### ISSUE TITLE
Migrate `nll_loss_forward` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24610]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by thomasjpfan** [comment]
@esqu1 Would you be okay with me working on this migration so we can push https://github.com/pytorch/pytorch/issues/59765 forward?

**Comment by esqu1** [comment]
@thomasjpfan sure, feel free to reassign
