### ISSUE TITLE
Migrate `remainder` and `remainder_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24615]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Marking high priority as these exercise zero_dim_dispatch_when_scalar

**Comment by ezyang** [comment]
An alternative is to just move the codegen into the implementation (which is a shorter thing to do).

**Comment by kurtamohler** [comment]
The performance of this ATen port compared with the previous TH implementation is below. I'm getting a little bit better performance in all cases.


dtype | num_elements | th time | aten time | gpu_aten_speedup
-- | -- | -- | -- | --
torch.float32 | 1000000 | 0.0000588 | 0.0000466 | 1.261802575
torch.float32 | 10000000 | 0.0000608 | 0.0000474 | 1.282700422
torch.float32 | 100000000 | 0.000063 | 0.0000456 | 1.381578947
torch.float64 | 1000000 | 0.0000572 | 0.0000482 | 1.186721992
torch.float64 | 10000000 | 0.0000566 | 0.0000476 | 1.18907563
torch.float64 | 100000000 | 0.0000608 | 0.000048 | 1.266666667
torch.int32 | 1000000 | 0.0000556 | 0.0000462 | 1.203463203
torch.int32 | 10000000 | 0.0000566 | 0.0000472 | 1.199152542
torch.int32 | 100000000 | 0.0000546 | 0.0000456 | 1.197368421
torch.int64 | 1000000 | 0.0000566 | 0.0000472 | 1.199152542
torch.int64 | 10000000 | 0.0000584 | 0.0000468 | 1.247863248
torch.int64 | 100000000 | 0.0000564 | 0.0000474 | 1.189873418
