### ISSUE TITLE
Migrate `scatter_add_` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24622]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by nikitaved** [comment]
Assigning myself because of getting involved in porting to CPU.

**Comment by nikitaved** [comment]
I am currently working on it, and I see that `gpuAtomicAdd` does not support complex types. Is there a chance that `gpuAtomicAdd` will be extended?

**Comment by VitalyFedyunin** [comment]
> I am currently working on it, and I see that `gpuAtomicAdd` does not support complex types. Is there a chance that `gpuAtomicAdd` will be extended?

CC @anjali411 who is complex numbers support expert

**Comment by anjali411** [comment]
@nikitaved it eventually needs to be done since a lot of nn layer functions use it, but there's non ongoing work for it rn. would you like to work on it?

**Comment by nikitaved** [comment]
@anjali411 , thank you! Yeah, I could have a look.

**Comment by rgommers** [comment]
Just a scope question here: is complex support required for migrating `scatter_add_` (maybe because the TH version supports complex already)? If not, I would suggest to keep adding complex support separate.

**Comment by nikitaved** [comment]
The kernel of scatter_add dispatches over complex numbers already, so, yes, it should work with complex numbers as well.
There are three possible solutions: 1. to either use the hack I already introduced in the port for scatter_add, or 2. Make `gpuAtomicAdd` support complex number. 3. Remove complex dispatch in the scatter/gather kernel.

I believe that solution #2 is the best. What do you think?

**Comment by anjali411** [comment]
@nikitaved I think we should use the hack you used in your PR and add `gpuAtomicAdd` for complex later

**Comment by nikitaved** [comment]
Closing. Done in [38262](https://github.com/pytorch/pytorch/pull/38262).
