### ISSUE TITLE
 ImportError: No module named torchvision.transforms vision

### ISSUE THREAD

**Issue by ahmedmazari-dhatim** [pytorch/pytorch#2463]
Hello,
l have installed pytorch as follow :

```
git clone https://github.com/pytorch/pytorch.git && cd pytorch/
python setup.py install
```

It have been installed successfully.
these commands works :

```
import torch
from torch.utils.data import Dataset
from torch.utils.data import sampler
```

However :

`import torchvision.transforms as transforms`

gives me back the following error :

`ImportError: No module named torchvision.transforms`

What’s missing ?

THANK YOU

**Comment by gchanan** [comment]
did you install torchvision? https://github.com/pytorch/vision

**Comment by ahmedmazari-dhatim** [comment]
It s not included in pytorch installation ?

**Comment by fmassa** [comment]
No, you need to install it separately.

**Comment by ahmedmazari-dhatim** [comment]
It s not included in pytorch installation ?
