### ISSUE TITLE
Migrate `softplus` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24633]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by rohan-varma** [comment]
Is anyone currently working on this? If not, I'd be happy to pick it up to learn more about our operator libraries. cc @VitalyFedyunin

**Comment by rohan-varma** [comment]
(Removed my comment inquiring about working on this since @XiaobingSuper is working on this)
