### ISSUE TITLE
Migrate `topk` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24648]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by nikitaved** [comment]
It looks like TopK is not very efficient for CUDA. I could try to port it using more specialized algorithms, rather than simple sorting. And resolve [16762](https://github.com/pytorch/pytorch/issues/16762) along the way.
