### ISSUE TITLE
Migrate `_cat` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24667]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by gottbrath** [comment]
@jianhui-li to follow up on this.

**Comment by mingfeima** [comment]
@VitalyFedyunin please refer to #30806

**Comment by ezyang** [comment]
I'm bumping the priority of this as it is the ONLY remaining function in TH that uses TensorList.
