### ISSUE TITLE
Why I get CUDA error when I alter weight decay?

### ISSUE THREAD

**Issue by yxchng** [pytorch/pytorch#2468]
![screenshot from 2017-08-17 12-27-05](https://user-images.githubusercontent.com/10518587/29398267-33f8cc94-8356-11e7-8f9b-ad1e79400106.png)

It only works for a specific value of weight decay which is 5e-4. What can possibly be the reason? How does weight decay affect CUDA?

**Comment by soumith** [comment]
the targets you are giving to criterion is larger than the number of classes you have. Hence there is an out-of-bounds memory access happening. This is unrelated to your weight decay change. Check that your dataset `targets` are all between `0` and `n-1` where `n` is the number of classes in your output layer.
