### ISSUE TITLE
Migrate `eig` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24693]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry

**Comment by anjali411** [comment]
making it hi priority because `torch.eig` is a useful op for audio community (e.g., ESPnet) and needs to be supported for complex tensors.

**Comment by heitorschueroff** [comment]
@kurtamohler Have you started working on this issue? I was going to work on issue https://github.com/pytorch/pytorch/issues/40916 but it's better if this is done while porting the code as was the case with symeig in here https://github.com/pytorch/pytorch/pull/21858.

**Comment by kurtamohler** [comment]
@heitorschueroff, yes I have started working on it. But the CUDA and CPU versions are decoupled in TH already, it shouldn't be too much of a hassle to have these as separate PRs, right? The only thing is, whichever PR gets merged last should remove the `eig` entry from `aten/src/ATen/Declarations.cwrap`.
