### ISSUE TITLE
Migrate `equal` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24697]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by SplitInfinity** [comment]
I'd like to work on this. How do I assign it to myself?

**Comment by VitalyFedyunin** [comment]
There is menu for in in the top-right of the issue

**Comment by SplitInfinity** [comment]
Maybe I don't have the necessary permissions or something but the link to assign to myself is not there for me. Could someone assign this to me please?
