### ISSUE TITLE
Migrate `fmod` and `fmod_` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24701]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Marking high priority as these exercise zero_dim_dispatch_when_scalar

**Comment by ezyang** [comment]
An alternative is to just move the codegen into the implementation (which is a shorter thing to do).

**Comment by peterbell10** [comment]
@VitalyFedyunin can you say why this was reopened? Did I miss something in #33592?

**Comment by peterbell10** [comment]
I think this was reopened because of a reverted PR https://github.com/pytorch/pytorch/pull/24405#issuecomment-607460590. However, that only reverted the CUDA implementation so closing.
