### ISSUE TITLE
Migrate `mm` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24730]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by zasdfgbnm** [comment]
Self assigning this for a fix of #29984

cc: @csarofeen @ptrblck for visibility

**Comment by VitalyFedyunin** [comment]
#34891
