### ISSUE TITLE
Migrate `scatter_add_` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24758]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by zasdfgbnm** [comment]
I am self-assigning this, because I need it to be ported to ATen before implementing broadcasting.

**Comment by nikitaved** [comment]
@zasdfgbnm , hi! Do you work on this? If not, may I assign myself? I would like to fix [27614](https://github.com/pytorch/pytorch/issues/27614).

**Comment by zasdfgbnm** [comment]
Not right now and feel free to reassign it to yourself. But be aware of https://github.com/pytorch/pytorch/pull/24858 so that we don't do duplicate work.

Also I have some abandoned PRs related to scatter/gather, my original plan was to wait for https://github.com/pytorch/pytorch/pull/24858 get merged and then rewrite them, but if you would love to take it over, feel free to do that:
https://github.com/pytorch/pytorch/pull/23578
https://github.com/pytorch/pytorch/pull/23510
https://github.com/pytorch/pytorch/pull/23479
https://github.com/pytorch/pytorch/pull/24954

**Comment by nikitaved** [comment]
@zasdfgbnm , thank you! Awesome that you work on gather, will use it as a template for my ports =) Just a quick question, do you make sure that the shape of the output is the same as the shape of the index, as it is in the legacy code?

**Comment by zasdfgbnm** [comment]
@nikitaved Yes, that one is just porting, there is no change in semantics.

**Comment by nikitaved** [comment]
@zasdfgbnm , sorry, one more question. In your PRs you mention broadcasting. Could you please elaborate on this with probably some use cases? Just for the future reference...

**Comment by zasdfgbnm** [comment]
@nikitaved Sure, no problem. Do I need to answer something for now? Feel free to talk to me when you need it, and thanks for working on this! I personally have been wanting this feature for a while and don't have much time to work on it!

**Comment by nikitaved** [comment]
@zasdfgbnm , no, all good for now. Thank you! I will probably need your help. Can I ping you on PyTorch slack?

**Comment by zasdfgbnm** [comment]
@nikitaved Sure, no problem, my id is also @zasdfgbnm there

**Comment by nikitaved** [comment]
@VitalyFedyunin, I would like to work on this one, but I am not super familiar with the internals yet. The porting procedure seems straightforward, but I would like to ask whether there is a functionality to improve over simple loops? Maybe there is a way to restructure inputs in such a way that it is possible to implement the method as a point-wise operation? Thank you!

**Comment by zasdfgbnm** [comment]
@nikitaved It is possible to use `TensorIterator`, see https://github.com/pytorch/pytorch/pull/24954. This is a PR that I am not working on right now, you can take it over.
