### ISSUE TITLE
Migrate `scatter` and `scatter_` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24757]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519

**Comment by zasdfgbnm** [comment]
I am self-assigning this, because I need it to be ported to ATen before implementing broadcasting.

**Comment by ezyang** [comment]
Marking high priority as these exercise `zero_dim_dispatch_when_scalar`

**Comment by nikitaved** [comment]
@ezyang, does it mean that the `scatter` version with `Scalar` as source should be deleted as well?
