### ISSUE TITLE
Migrate `set_` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24759]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by VitalyFedyunin** [comment]
Hi-Pri because of complex numbers support

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/34331

**Comment by peterbell10** [comment]
Completed in #34403
