### ISSUE TITLE
Migrate `std` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24771]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by mfuntowicz** [comment]
I'll take this one

**Comment by VitalyFedyunin** [comment]
This one currently dispatched as `_std` might be worth checking difference between existing Aten and old TH versions.

**Comment by VitalyFedyunin** [comment]
Ok, so picture is (same for `std` and `var`) aten's `var` calls to `_var` when dims are not specified. Then `_var` calls to the th code `(var_single)`. 

So - we have aten version for per-dim `std` and `var`, we have no optimized version when dims is not specified ( and doing `torch.var(x.reshape(-1),0)` is 5 times slower ).
