### ISSUE TITLE
Migrate `topk` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24778]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by fmassa** [comment]
I believe this has already been ported, see https://github.com/pytorch/pytorch/blob/76716f6c0644f66e5984ab6686ca19f3702039a8/aten/src/ATen/native/Sorting.cpp#L193

**Comment by VitalyFedyunin** [comment]
Super, so we need to check if we can nuke https://github.com/pytorch/pytorch/blob/52b4221bfa61b3d5e0f7157feb4ddb3a77d36015/aten/src/TH/generic/THTensorMoreMath.cpp#L763
