### ISSUE TITLE
Migrate `take` from the TH to Aten (CPU)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24772]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by mrshenli** [comment]
If no one is working on this, I would like to reserve this for bootcamp.

**Comment by mrshenli** [comment]
closed by #45283
