### ISSUE TITLE
Making torch.hub.load less verbose

### ISSUE THREAD

**Issue by faroit** [pytorch/pytorch#24791]
## 🚀 Feature

Introduce a `verbose=False` flag for `torch.hub.load`

## Motivation

When running inference using torch hub models on multiple files, it becomes a bit too verbose when always being confronted with the message

`Using cache found in ...`

this is produced by https://github.com/pytorch/pytorch/blob/0a12ff7c5b59cbd47dc865603e45178903f6dfa8/torch/hub.py#L156

## Pitch

`torch.hub.load(..., verbose=False)` should suppress the prints (and possibly also the loading progress bars)

cc @ailzhang

**Comment by ailzhang** [comment]
Yea it should be easy. I can send a patch before 1.3 release.

**Comment by faroit** [comment]
I thought about it a bit more, it should probably just supress the cache message but should show the progress bar on first load.

**Comment by adriel** [comment]
Did this ever go live?
I'm on torch 2.0.0 and am getting `Using cache found in /Users/adriel/.cache/torch/hub/ultralytics_yolov5_master` echo time this is run.

```
 model = torch.hub.load('ultralytics/yolov5', 'custom',
                           path=r'./best.pt', _verbose=False)
```
