### ISSUE TITLE
ATen headers are not copied in lib/include/ATen/*.h

### ISSUE THREAD

**Issue by DavidGrangier** [pytorch/pytorch#2479]
Would changing setup.py so that

```
--- a/setup.py
+++ b/setup.py
@@ -490,6 +490,8 @@ setup(name="torch", version=version,
           'lib/torch_shm_manager',
           'lib/*.h',
           'lib/include/TH/*.h', 'lib/include/TH/generic/*.h',
-          'lib/include/THC/*.h', 'lib/include/THC/generic/*.h']},
+          'lib/include/THC/*.h', 'lib/include/THC/generic/*.h',
+          'lib/include/ATen/*.h',
+          ]},
       install_requires=['pyyaml', 'numpy'],
       )
```

Solve the issue?

**Comment by killeent** [comment]
@DavidGrangier is there a particular issue you are running into?

**Comment by DavidGrangier** [comment]
I am switching my own modules from TH to ATen and my build rules work under the assumption that ATen headers are accessible. I thought that the transition from TH to ATen would preserve these assumption.

**Comment by ezyang** [comment]
CC @zdevito

**Comment by zdevito** [comment]
If we install the TH headers, why don't we install the ATen headers. Is there any harm?

**Comment by soumith** [comment]
no harm. we should include ATen headers too.

**Comment by zdevito** [comment]
#2506 fixed this, it can be closed.
