### ISSUE TITLE
numpy like tensor.all and tensor.any

### ISSUE THREAD

**Issue by tomsal** [pytorch/pytorch#2481]
Hi all!

As mentioned in issue https://github.com/pytorch/pytorch/issues/2228, it would be nice to have functions close to the numpy API. Currently, logic functions like [np.all](https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html) and [np.any](https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html) are still missing. Of course, workarounds can be easily achieved, but having such a function would increase readability.

A simple implementation could consist of using boolean_tensor.min() != 0 and boolean_tensor.max() == 1.

**Comment by vadimkantorov** [comment]
As a note, `any` and `all` exist on ByteTensors, but do not appear in online documentation.

**Comment by tomsal** [comment]
I didn't know. Thanks!
