### ISSUE TITLE
Can't install latest CPU stable with pip (windows)

### ISSUE THREAD

**Issue by jvesely** [pytorch/pytorch#24825]
## 🐛 Bug

There's no direct way to install latest stable pytorch+cpu on windows.
The website recommends:
`pip3 install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html`.
The above command requires specific numeric version and there's no way to specify 'latest stable'.

## To Reproduce

1. Try to install the latest stable CPU variant without knowing the exact version number

## Environment
Windows. the rest doesn't matter

## Additional context

It'd be nice if there was a list of +cpu versions usable by pip similar to `torch_stable.html`. Something like:
`https://download.pytorch.org/whl/cpu/torch_stable.html`
or
`https://download.pytorch.org/whl/torch_cpu_stable.html`.
It'd be useful for other variants too.

cc @peterjc123

**Comment by peterjc123** [comment]
cc @ezyang

**Comment by peterjc123** [comment]
We have links for one configuration, too.
So you can actually do the following to get the cpu package without knowing the version.
```bash
pip install -f https://download.pytorch.org/whl/torch_stable.html torch torchvision
```

**Comment by jvesely** [comment]
Right, I'm not sure how I missed it.
Thanks!
