### ISSUE TITLE
cublas runtime error : resource allocation failed at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/THCGeneral.cpp:228

### ISSUE THREAD

**Issue by hadaev8** [pytorch/pytorch#24838]
## 🐛 Bug
Incomprehensible message when used improperly embedding.

## To Reproduce
I have this error then tried to feed number 3 to embedding with 3 indexes.

## Expected behavior
Reasonable error message.

## Environment
docker pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel

**Comment by cpuhrsch** [comment]
Hello @hadaev8 - as detailed in the Issue template, could you please provide more information about your environment to help us reproduce this error?

Also, maybe you ran out of memory?

**Comment by hadaev8** [comment]
It happens if I pass to embedding layer integer greater then num_embeddings.
My env is fresh docker image.

**Comment by AssassinTee** [comment]
I had the same error message and ran out of cuda memory. I just fixed it by splitting one huge operation in multiple small ones.
