### ISSUE TITLE
Improve torch.autograd.Function documentation

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#2483]
http://pytorch.org/docs/master/autograd.html#torch.autograd.Function

It's missing:

- an example of how to define a function
- the signature of forward and backward
- backward says "All arguments are tensors". I don't think this is true anymore

It also has information that's not relevant to the API, such as "almost all of it was moved to our C backend"

**Comment by lantiga** [comment]
I'm looking at this. What attributes do we want to retain in the documentation?
Correct me if I'm wrong, but some of them are there for backward compatibility: `num_inputs`, `num_outputs`, `needs_input_grad` (it's now in ctx).

`requires_grad` is still good. Should we also add `dirty_tensors`, `shared_pairs` and `non_differentiable`, that are set by the `make_...` functions?
