### ISSUE TITLE
Advanced Indexing with LongTensor Variable

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2484]
```
import torch
x = torch.autograd.Variable(torch.randn(3, 4))
y = torch.autograd.Variable(torch.LongTensor([1,2]))
print x[y] # works
print x[:, y.data] # works
print x[:, y] # fails
```

error:

> File "/share/data/vision-greg/rluo/local/anaconda/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 16, in forward
>     result = i.index(ctx.index)
> IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors

I tried index_select, gather, both accept both Variable and Tensor; feel like it could be improved.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/2590
