### ISSUE TITLE
Can pytorch 1.2 support cuda 9.0?

### ISSUE THREAD

**Issue by anoidgit** [pytorch/pytorch#24842]
## ❓ Can pytorch 1.2 support cuda 9.0?

I try to install pytorch 1.2.0 with anaconda, but found that `torch.cuda.is_available()` always returns False. Turns out our server environment can only support CUDA 9.0, but I do not have administrator right to upgrade the nvidia driver.
Give that pytorch 1.2.0 introduced Bool type, and I have already updated my code for corresponding change of API, I do not want to undo this efforts.
Will pytorch 1.2.0 support CUDA 9.0 backend in the future?

cc @ezyang

**Comment by peterjc123** [comment]
It is supported, but we won't provide the binaries. You'll have to build it by yourself.

**Comment by ezyang** [comment]
That's right, please compile from source.

**Comment by chg0901** [comment]
> It is supported, but we won't provide the binaries. You'll have to build it by yourself.

Could you please tell us that if pytorch1.3 support cuda 9.0?
If so, could you please show me how to build it by myself?
 Is there any tutorials about this?

**Comment by peterjc123** [comment]
I answered your question [here](https://discuss.pytorch.org/t/can-pytorch1-0-0-in-win10-with-cuda9-0-use-tensorboard/65747). Please don't post things in various closed issues. Thank you.
