### ISSUE TITLE
Normal distribution replaces unitialised parameters

### ISSUE THREAD

**Issue by pawni** [pytorch/pytorch#24846]
## 🐛 Bug

When I create a Normal distribution with uninitialised parameters and initialise them before use they stay fixed. I'm not sure whether this it expected but I found it to be odd and took me some time to catch the difference in initialisations (because this then also lead to samples that were `inf`).

## To Reproduce

```
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import torch.distributions as dist
import math

mean = Parameter(torch.Tensor(1, 2))
log_std = Parameter(torch.Tensor(1, 2))

n = dist.Normal(mean, torch.exp(log_std))

nn.init.kaiming_uniform_(mean, a=math.sqrt(5))
nn.init.normal_(log_std, -5)

print(n.scale)
```
returns
`tensor([[1., 1.]], grad_fn=<ExpBackward>)`
## Expected behavior

When initialising the parameters before creating the distribution the scale is correct:
```
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import torch.distributions as dist
import math

mean = Parameter(torch.Tensor(1, 2))
log_std = Parameter(torch.Tensor(1, 2))

nn.init.kaiming_uniform_(mean, a=math.sqrt(5))
nn.init.normal_(log_std, -5)

n = dist.Normal(mean, torch.exp(log_std))

print(n.scale)
```
returns:
`tensor([[0.0444, 0.0060]], grad_fn=<ExpBackward>)`

## Environment

Collecting environment information...
PyTorch version: 1.1.0.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.15.1
[pip3] numpydoc==0.8.0
[pip3] torch==1.1.0.post2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.0                      118
[conda] mkl-service               1.1.2            py37h6b9c3cc_5
[conda] mkl_fft                   1.0.4            py37h5d10147_1
[conda] mkl_random                1.0.1            py37h5d10147_1
[conda] torch                     1.1.0.post2               <pip>

## Additional context
N/A

**Comment by cpuhrsch** [comment]
Don't use `torch.Tensor` to create Tensors. Please use `torch.tensor` instead. After that update, please reconsider the behavior of the program.

**Comment by pawni** [comment]
Well, when using torch.empty instead it gives the same behaviour. When using torch.tensor it also shows this:
```
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import torch.distributions as dist
import math

mean = Parameter(torch.tensor(np.zeros((1, 2)), dtype=torch.float32))
log_std = Parameter(torch.tensor(np.zeros((1, 2)), dtype=torch.float32))

n = dist.Normal(mean, torch.exp(log_std))

nn.init.kaiming_uniform_(mean, a=math.sqrt(5))
nn.init.normal_(log_std, -5)

print(n.scale)
```
returns:
`tensor([[1., 1.]], grad_fn=<ExpBackward>)`

But it seems to be a different issue as it generally fails when changing the value afterwards:
```
import torch
import torch.nn as nn
from torch.nn.parameter import Parameter
import torch.distributions as dist
import math

mean = Parameter(torch.Tensor(1, 2))
log_std = Parameter(torch.Tensor(1, 2))

nn.init.kaiming_uniform_(mean, a=math.sqrt(5))
nn.init.normal_(log_std, -5)

n = dist.Normal(mean, torch.exp(log_std))

print('Before reinit:')
print(torch.exp(log_std))
print(n.scale)
print(mean)
print(n.loc)

nn.init.normal_(mean, 5)
nn.init.normal_(log_std, 5)

print('After reinit:')
print(torch.exp(log_std))
print(n.scale)
print(mean)
print(n.loc)
```
returns:
```
Before reinit:
tensor([[0.0033, 0.0018]], grad_fn=<ExpBackward>)
tensor([[0.0033, 0.0018]], grad_fn=<ExpBackward>)
Parameter containing:
tensor([[ 0.4239, -0.4349]], requires_grad=True)
Parameter containing:
tensor([[ 0.4239, -0.4349]], requires_grad=True)
After reinit:
tensor([[464.2554,  52.3712]], grad_fn=<ExpBackward>)
tensor([[0.0033, 0.0018]], grad_fn=<ExpBackward>)
Parameter containing:
tensor([[5.0901, 4.4388]], requires_grad=True)
Parameter containing:
tensor([[5.0901, 4.4388]], requires_grad=True)
```

Does the distribution create a copy of its parameters if the passed value isn't a nn.Parameter or something? Or is it do to with how the computational graph is built?

**Comment by andreaskoepf** [comment]
If you pass `log_std` through the function `torch.exp()` a new tensor (btw no `Parameter` object) is created to store the result. This object is passed to the ctor of the `Normal` class and assigned to the `scale` member.

Changing the original `log_std` tensor has no effect on the result that was returned by `torch.exp()`. You could use the inplace version `torch.exp_()` (with underscore) but then the name `log_std` was probably not ideal ;-)...

**Comment by fritzo** [comment]
See ##31009 Distributions are not mutable `nn.Module`s; rather they are immutable purely functional flyweight objects that bundle together multiple purely functional methods (`.log_prob()`, `.rsample()`, `.entropy()`).
