### ISSUE TITLE
Bad error message when concatting different type Tensor(Variable)

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2485]
```
import torch
x = torch.randn(3,4)
y = torch.randn(3,4).double()
z = torch.cat([x,y], 0)
```

> TypeError: cat received an invalid combination of arguments - got (list, int), but expected one of:
>  * (sequence[torch.FloatTensor] seq)
>  * (sequence[torch.FloatTensor] seq, int dim)
>       didn't match because some of the arguments have invalid types: (list, int)

```
x = torch.autograd.Variable(x)
y = torch.autograd.Variable(y)
z = torch.cat([x,y], 0)
```
> TypeError: cat received an invalid combination of arguments - got (tuple, int), but expected one of:
>  * (sequence[torch.FloatTensor] seq)
>  * (sequence[torch.FloatTensor] seq, int dim)
>       didn't match because some of the arguments have invalid types: (tuple, int)

The error message is providing nothing, even misleading information.

Found other error messages when trying to do computation on two different type tensors are also bad.

**Comment by cedias** [comment]
FYI, the same misleading message happens when trying to concat a Variable with a Tensor.

> TypeError: cat received an invalid combination of arguments - got (list), but expected one of:
>  * (sequence[torch.cuda.FloatTensor] seq)
>       didn't match because some of the arguments have invalid types: (list)
>  * (sequence[torch.cuda.FloatTensor] seq, int dim)
>

**Comment by zou3519** [comment]
After the Variable/tensor merge (that has occurred on master), Variables and tensors are now the same thing so this bug has gone away.
