### ISSUE TITLE
Let new and existing backends easily register for testing

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#24851]
## 🚀 Feature

A new test structure that:

- allows backends to specify which tests (and which variants of those tests) should be run when testing them
- lets backends specify which (other) backend to compare against (where applicable)
- lets new backends quickly register themselves for testing

For example, a backend like XLA  should be able to register itself for a suite of backend-generic tests simply, a backend like CUDA should be able to mark some test inputs, like bfloat16, as unsuitable, and an FPGA backend might list some generic tests as unsuitable because they use unsupported ops.

Users should be able to request that tests be run for a specific backend and compared to another. E.g. "run the CUDA tests and compare outputs with the CPU backend." Ideally users can also specify input data types, too, like "run only the bfloat16 XLA tests." 

## Motivation

Historically PyTorch has only seriously supported CPU and CUDA (plus HIPMasqueradingasCUDA) backends. We want to support a variety of backends, however, and providing them a simple mechanism to hook into PyTorch's existing test infrastructure will be immensely helpful in ensuring they correctly implement PyTorch's interface. Giving backend developers more control over the tests they run should also improve their speed of development.

## Pitch

See feature. I'll create an initial proposal for us to review and post it back to this issue.

## Alternatives

We need to let new backends test their implementation of the PyTorch interface, the only question is how much work we do to support this. This issue is to discuss possible improvements. 

@ailzhang @VitalyFedyunin @izdeby 
@dlibenzi 
@csarofeen

cc @ezyang @gchanan

**Comment by VitalyFedyunin** [comment]
Just curious, what are we trying to archive with comparison tests? By my experience it is better (and sufficient) to write proper correctness test and to allow execution by any device.

**Comment by mruberry** [comment]
I was thinking of functions like https://github.com/pytorch/pytorch/blob/012526dd6bf677fd029e9c27ecb49e401b210d2f/test/test_cuda.py#L627 where we use the CPU as a gold standard for CUDA.

**Comment by VitalyFedyunin** [comment]
As soon as we declare this approach as precision testing only, I'm fine with it. But it never should be the single way we test per device operators.

**Comment by mruberry** [comment]
I agree with you completely.

**Comment by gchanan** [comment]
By backends, do you mean devices?  Backend has so many meanings I struggle to understand what it means.

>> lets new backends quickly register themselves for testing

Absolutely agree, I believe @ailzhang, @VitalyFedyunin and maybe others are already working on these?

>> allows backends to specify which tests (and which variants of those tests) should be run when testing them

I'm not sure, can you explain how this would work?  Why can't they just invoke the tests they want to run?

>> lets backends specify which (other) backend to compare against (where applicable)

I'm not really sure why backends can't use our existing mechanisms (once you can easily register yourself for testing).  Either we already wrote the test in this manner, in which case plugging in the device is sufficient, or we didn't (and the backend writer wants such a test).  But they can just do something like:

```
@for_all_registered_devices
def my_device_operator_test(self, device):
   # optionally skip if device is CPU
   cpu_output = torch.operator(torch.randn(...))
   my_device_output = torch.operator(torch.randn(..., device=device))
   self.assertIsClose(cpu_output, my_device_output)
```

and this is totally flexible and doesn't require additional mechanism over what we already absolutely need (the ability to register your device type for testing).

**Comment by mruberry** [comment]
> By backends, do you mean devices?

@ailzhang Points out that we probably mean "PyTorch device," but not a "physical device." 

I meant "backend" as software implementing PyTorch's interface on one or more devices. 

> I believe @ailzhang, @VitalyFedyunin and maybe others are already working on these?

@ailzhang was planning to shepherd this issue but we thought it'd be a good way for me to help with Pytorch+XLA. 

> I'm not sure, can you explain how this would work? Why can't they just invoke the tests they want to run?

Letting backends invoke the tests they want would work, too, it's just an opt-in vs opt-out model. We could even support both. When someone adds a new generic (multiple-backend) test, do you expect backends to run that test successfully or do you want them to have to opt-in before running it? I thought we'd prefer an opt-out model where they have to explicitly exclude some tests.

> I'm not really sure why backends can't use our existing mechanisms...

Let's try to reuse as much as possible! Maybe more detail here should wait for the proposal?

**Comment by gchanan** [comment]
> @ailzhang Points out that we probably mean "PyTorch device," but not a "physical device."

right, "PyTorch device" or "PyTorch device type" seems like the right thing.

> I meant "backend" as software implementing PyTorch's interface on one or more devices.

right, I'm just pointing out that when someone says "PyTorch backend" I don't know what they mean.

> Letting backends invoke the tests they want would work, too, it's just an opt-in vs opt-out model. We could even support both. When someone adds a new generic (multiple-backend) test, do you expect backends to run that test successfully or do you want them to have to opt-in before running it? I thought we'd prefer an opt-out model where they have to explicitly exclude some tests.

I don't really know the workflow that's being proposed.  I think it would help if there was a high-level proposal like:
```
# third-party calls some plug into test API
# third-party invokes "python run_test
```
or something like that.

**Comment by mruberry** [comment]
> I don't really know the workflow that's being proposed.

Right. I'll post a proposed solution to the issue tomorrow.

**Comment by mruberry** [comment]
(Written with @ailzhang)

"High-level" proposal (additional details forthcoming), is to let the following be a maximally expressive command:

`pytorch/test: python test_nn.py cuda -base cpu`

This command:

- Runs the tests specified in test_nn.py with the "cuda backend"
- It excludes tests that the "cuda backend" has stop listed
- It excludes comparison/precision tests that the cpu has stop listed
- It compares the results of the "cuda backend" to those of the "cpu backend"

And this UX has the following caveats/options:

- If `python test_nn.py` is run then Pytorch will run a series of test commands on test_nn.py, like `python test_nn.py cpu` and `python test_nn.py cuda` covering all applicable test backends.
- If the option -base is not specified it is assumed to be cpu.
- If the tested implementation and the implementation to compare with are the same then comparison/precision tests may not be run.

To implement this UX each test backend will have a file, like test_cuda.py, that contains:

- An initialization function
- A function for converting tensors to the appropriate type (e.g. `.cuda()`)
- Functions for querying which tests should not be run, which dtypes can be handled, and what tests should override a user-specified precision hint
- (Optionally) Tests and test plans

This will allow users to invoke all tests for a backend by running test_<backend>.py, and run specific tests by either doing `python test_<X>.py <backend>` or `python test_<backend>.py TestBackend.<test>` .

A drawback of this approach is that test backends must explicitly exclude tests they cannot run. If operator coverage is spotty then new tests are likely to break those backends. In the future it may be preferable for the test infrastructure to catch classes of errors, like not implemented errors, and report tests where they occur as expected failures.

In the future it's also interesting to consider adding more control over datatypes and precision.

**Comment by ezyang** [comment]
@mruberry @ailzhang A few quick thoughts:

1. You seem to be advocating for a non-standard command line interface to the Python test script. However, in Python, a test is not just a command that you can run; tests are arranged in a conventional way so that other test runners can use them; e.g., if a Python test suite is written in the normal way, I can run `pytest` and that will run all my tests. If I want to, e.g., generate xml test results, the most convenient way to make this happen is to use one of these test runners. (This doesn't entirely work for the PyTorch test suite, because some tests need to be run several times under different environment settings; but I view that as a bug, not a feature.) So for me, there is a pretty high bar for breaking the standard convention here: we had better be getting something good, and there is no other way we could have gotten it.

2. It would be helpful if we could see some example code of what tests look like in this framework

**Comment by mruberry** [comment]
@ezyang You're right and we want to enable that functionality while enabling the following two scenarios:

1. You can run all the tests related to a backend. (You can test CUDA, XLA, MKLDNN,...)
2. You can run all tests related to a topic area on every applicable backend. (You can test jit functionality on CPU, HIP, ...)

I think we can have our cake and eat it, too, and I agree the next step is looking at sample code.

**Comment by gchanan** [comment]
>> Runs the tests specified in test_nn.py with the "cuda backend"

Ok, if we don't refer to it as a backend :).  If this proposal isn't about testing different device types, I'd **really** want to define what it covers.

>> It excludes tests that the "cuda backend" has stop listed

How would this look in practice?  I was imagining this command would just run all the tests we have annotated with the per-device runner with cuda.  If "stopListed" is an annotation or the test just raises SkipTest if the device is cuda, that seems fine.

>> It excludes comparison/precision tests that the cpu has stop listed

I'm not sure what this means.  As I mentioned above, I don't see why comparison/precision tests need to be different structurally from other (per-device) tests.

>> It compares the results of the "cuda backend" to those of the "cpu backend"

As above, I'm still not sure why I would want to structure my test as a "precision test" instead of just any other per-device test.  Now, we may want to support centralizing and overriding our precisions, but I don't see why we need a new test structure.

>> If python test_nn.py is run then Pytorch will run a series of test commands on test_nn.py, like python test_nn.py cpu and python test_nn.py cuda covering all applicable test backends.

Why don't we just structure our per-device tests with an annotation and if you run it without magic flags it does what it currently does, which is to run with the available devices.

>> If the option -base is not specified it is assumed to be cpu.

Why would we want the base not to be CPU?

>> To implement this UX each test backend will have a file, like test_cuda.py, that contains:
>> An initialization function
>> A function for converting tensors to the appropriate type (e.g. .cuda())

Why is this testing specific?  Doesn't the device need to "just work", in the same way that cuda "just works"; users don't need to run any magic to get cuda to work.  Also, the function should just be `to(device_type)`.

>> Functions for querying which tests should not be run

Why can't you just run whatever you want to run, with pytest or whatever other tool you want to use?

**Comment by mruberry** [comment]
> Ok, if we don't refer to it as a backend :). If this proposal isn't about testing different device types, I'd really want to define what it covers.

Let's just call them "device types."

> I was imagining this command would just run all the tests we have annotated with the per-device runner with cuda

Our proposal is that tests are never annotated with device-type-specific information. That is, all the tests in a file like "nn_common.py" will have no notion of any device type. Otherwise if someone writes a new device type, like TVM:GPU, they would have to modify "nn_common.py." This is equivalent effort (for them) as updating a list of tests to exclude in their own "test_tvm_gpu.py" and means that the test files won't be littered with annotations and that third-party repos won't have to maintain their own versions of the core tests. Having the device type provide the exclusions also allows the exclusions to be dynamic. The cuda device type tests, for example, may want to exclude (or set precisions, or dtypes) differently based on detected hardware. 

Maybe we should wait to look at the code for how this is implemented?

> I'm not sure what this means. As I mentioned above, I don't see why comparison/precision tests need to be different structurally from other (per-device) tests.

If they're not their own (conceptual) category and you allow arbitrary device type - device type comparisons then you need to exclude tests in either of the device types' stop lists. Otherwise you would get test errors that are expected by the user but not the test framework. If we define the CPU device type as THE standard (per below) then we don't need to make a distinction between these tests.

> Why don't we just structure our per-device tests with an annotation and if you run it without magic flags it does what it currently does, which is to run with the available devices.

Our proposal suggests this change, which is not what our tests currently do. The proposal doesn't suggesting using an annotation (see above), however. 

> Why would we want the base not to be CPU?

This would be pretty reasonable. It suggests that Torch:CPU is THE standard/correct implementation of the PyTorch API, which seems fine to me. There are some fringe scenarios where this may not be ideal, like if TVM:CPU and TVM:GPU want to compare their implementations to each other, but they don't seem very important or near term. This would simply remove the -base option from the proposal and require that all "comparison/precision" tests be able to run on Torch:CPU or be placed into the device-type-specific tests.

> Why is this testing specific? Doesn't the device need to "just work", in the same way that cuda "just works"; users don't need to run any magic to get cuda to work. Also, the function should just be to(device_type).

The conversion function should be simple, yes. I don't think it's worth trying to mandate/infer its form, however. What would the rule be? You have to create a file called "device_type_cuda.py" and then your conversion function must be `.to("cuda<X>")`? I think that would break on the current PyTorch+XLA integration.

> Why can't you just run whatever you want to run, with pytest or whatever other tool you want to use?

So in this proposal there are tests. The tests are device-type-agnostic. Those tests may have operators that a device-type doesn't support. Running those tests on that device type doesn't make sense (expected failure). We don't have a mechanism, however, for reporting the expected failure. So this proposal suggests that those tests be marked as expected_failures / skipped by another mechanism. 

This would not be strictly necessary if the only way to test a device type were via a "device_type.py" entrypoint, but the proposal is that we support the scenario of "run all tests relevant to this device type" and "run all these tests on every available device type." So to avoid a bunch of false positive errors I think it'd be nice to skip / expected fail the set of tests a device type can't handle.

**Comment by ezyang** [comment]
(For the record: I didn't read any of the convo above. Waiting for the example code :)

**Comment by mruberry** [comment]
See #25967, the PR to address this.

**Comment by mruberry** [comment]
XLA is now hooked into PyTorch's Python tests, closing this issue.
