### ISSUE TITLE
[Windows] Including Windows.h before LibTorch headers causes compilation errors

### ISSUE THREAD

**Issue by HapeMask** [pytorch/pytorch#24862]
## 🐛 Bug

If Windows.h (and possibly other Windows-specific headers) is included prior to LibTorch headers, the program will fail to compile. In one specific case (not Windows.h but some unknown include), adding `#undef UNICODE` before including `torch/torch.h` was enough to fix the problem but this is not true in all cases.

## To Reproduce

Try to compile this:

```
#include <Windows.h>

#include <torch/torch.h>

int main() {
  return 0;
}
```

If Windows.h is included first, there are many errors:

https://gist.github.com/HapeMask/27160e678a7ad679981c227a97641c8c

Also here: https://github.com/pytorch/pytorch/blob/d7c6debc14aa722d8002a19462c38b3b659dbec0/torch/csrc/jit/pickler.h#L37

UNICODE is already defined. Adding `#undef UNICODE` prior to this enum fixes that specific issue.

## Environment

 - PyTorch Version (e.g., 1.0): tested 1.1, 1.2, latest master (cf57f73c1)
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.7
 - CUDA/cuDNN version: 10/7.6
 - GPU models and configuration: RTX 2080

cc @peterjc123

**Comment by cpuhrsch** [comment]
Hello @HapeMask,

Could you include the errors as well? :)

**Comment by HapeMask** [comment]
> Hello @HapeMask,
> 
> Could you include the errors as well? :)

Oops sorry, attached them in a gist.

**Comment by peterjc123** [comment]
I tested the following code on my local machine. Looks like `Windows.h` doesn't expose the macro `UNICODE`.
```cpp
#include <Windows.h>

#ifdef UNICODE
#error "OMG"
#endif
```

**Comment by HapeMask** [comment]
You can ignore the UNICODE part, I mistakenly thought it was part of Windows.h but is coming from somewhere else like you said. The other errors in the gist I linked are real though and unrelated to the UNICODE business.

**Comment by peterjc123** [comment]
If `UNICODE` isn't introduced by `Windows.h`, then I don't think it is a general issue. And as you said, `#undef UNICODE` solves the issue and that's it.

**Comment by HapeMask** [comment]
@peterjc123 I apologize for making things muddy by including the UNICODE example but please see the linked gist. Those compile errors are entirely unrelated to UNICODE and occur simply by trying to compile the example code I gave.

The UNICODE issue can be worked around on our end so in that sense it’s fine to leave this closed I suppose, but I just wanted to make it clear that there are real compile errors that occur merely by including Windows.h first.

**Comment by peterjc123** [comment]
I tried and this issue occurred, but it can be easily resolved if you define `NOMINMAX` before including `Windows.h`.
