### ISSUE TITLE
Dictionary in C++

### ISSUE THREAD

**Issue by zhangguanheng66** [pytorch/pytorch#24869]
## 🚀 Feature
Implement a dictionary ops in C++

## Motivation

The dictionary ops will replace the current vocab class in torchtext (or serve as a new class for the same purpose). It could also be applied for transforming audio script. I think a dictionary ops in pytorch core library makes it easier to maintain.

## Pitch

Some baselines should be included:
+ findWord()
+ addWord()
+ count_nwords()
+ count_ntokens()
+ count_nlables()
+ getWord()
+ readFromSequence()
+ readFromFile()

**Comment by soumith** [comment]
why exactly is this filed against `pytorch/pytorch` instead of `pytorch/text`?

**Comment by zhangguanheng66** [comment]
@soumith since the dictionary with hashing trick could also be applied for audio script, I think torchaudio could also use it. But if only text people want it, I will file it in `pytorch/text`.

**Comment by gchanan** [comment]
I feel like this issue is missing a bunch of context -- what's the "hashing trick" and how would the vocab-class be a general purpose solution or just something for torchaudio and torchtext to share?
