### ISSUE TITLE
Issue with maxInt in utils.py

### ISSUE THREAD

**Issue by egold7308** [pytorch/pytorch#24880]
utils.py, line 130

Currently says `csv.field_size_limit(sys.maxsize)`

This causes an overflow on my machine. I think it should be `csv.field_size_limit(maxInt)` which uses the `maxInt` determined a couple lines up. Changing this value got it to work for me.

**Comment by gchanan** [comment]
I cannot find this line of code (perhaps it is from an old version of pytorch).  If you are so included, please reopen this issue and link the line of code on github.

**Comment by sevenguin** [comment]
it's in torch/text, not torch/torch
