### ISSUE TITLE
SobolEngine should use random seed by default when scrambling

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#24881]
Currently, the following behavior is deterministic:

```
SobolEngine(dim=d, scramble=True).draw(k)
```

To achieve random scrambling, you need to do 

```
SobolEngine(dim=d, scramble=True, seed=random.randint(0, 100)).draw(k)
```

This behavior is inconsistent with that of other random number generation in torch. E.g., `torch.rand(d)` will generate different numbers in each call, unless the seed is fixed manually.

I believe the `SobolEngine` behavior should be consistent with this, otherwise this is a pretty big gotcha. This behavior is because if no seed is given to `SobolEngine`, it uses `torch.Generator()` to generate the random numbers for scrambling. My suggestion is to use a random seed if `seed=None` in the `SobolEngine` constructor.

If this sounds reasonable, I'll put up a two line PR.

**Comment by Balandat** [comment]
@vishwakftw

**Comment by vishwakftw** [comment]
@Balandat sounds very reasonable. I actually hadn't thought of this at the time. I would be vary of the tests, because they assume the above behavior.

**Comment by Balandat** [comment]
yeah I could have thought of that myself as well at the time when reviewing the PR...

**Comment by vishwakftw** [comment]
Closing since the fix has been merged.
