### ISSUE TITLE
PyTorch + flask won't work with num_processes > 1

### ISSUE THREAD

**Issue by humzaiqbal** [pytorch/pytorch#24894]
## 🐛 Bug

When I run PyTorch in a flask app with the number of processes set to 4 my model won't calculate anything. Some previous googling told me this was because PyTorch is already parallelized and running multiple processes on top ruins that. I tried setting `torch.num_threads()` to be 1 and I tried setting `OMP_NUM_THREADS=1` as an environment variable but neither of these worked.

## To Reproduce

```
from flask import Flask
import torch
import torch.nn as nn 
app = Flask()
app.run(port=8000, processes=4)


class SimpleLinearModel(nn.Module):
    def __init__(self):
          super(SimpleLinearModel, self).__init__()
          self.linear_layer = nn.Linear(2500, 300)
    
    def forward(x):
         return self.linear_layer(x)

model = SimpleLinearModel()
model(torch.randn(1, 2500))
```
## Environment

 - PyTorch Version (e.g., 1.0): 1.2 
 - OS (e.g., Linux): MacOSX
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.7.1
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A

**Comment by peterjc123** [comment]
No, it's not the reason here. `app.run` serves your Flask application and later lines won't get executed. If you want to make responses from HTTP requests to Flask, you should add functions with routing rules ahead of that line.

**Comment by peterjc123** [comment]
You could know more about routing [here](https://flask.palletsprojects.com/en/1.0.x/quickstart/#a-minimal-application).

**Comment by humzaiqbal** [comment]
Apologies, in my actual codebase I do have an `app.route` in my actual code which is how the model is actually being run, I didn't include that in the above snippet as I didn't think it was needed to diagnose the issue. My actual code looks more like 

```
from flask import Flask
import torch
import torch.nn as nn 
app = Flask()
app.run(port=8000, processes=4)

class SimpleLinearModel(nn.Module):
    def __init__(self):
          super(SimpleLinearModel, self).__init__()
          self.linear_layer = nn.Linear(2500, 300)
    
    def forward(x):
         return self.linear_layer(x)


@app.route("/run_model", methods=['POST'])
def run_model():
      model = SimpleLinearModel()
      model(torch.randn(1, 2500))

 ```
The bottom line is still the same though, when `num_processes` is 1 then my code works fine but anything more than that causes problems. Apologies again.

**Comment by peterjc123** [comment]
> The bottom line is still the same though, when `num_processes` is 1 then my code works fine but anything more than that causes problems. Apologies again.

I'm still confused. What do you mean that it didn't work? What just doesn't work? Any error messages does it throw?

**Comment by nistarlwc** [comment]
Excuse me, is there a solution for this problem?
