### ISSUE TITLE
Export torch.cat to ONNX with Dynamic shape does not work on GPU

### ISSUE THREAD

**Issue by liangt** [pytorch/pytorch#24899]
## 🐛 Bug

After I export my PyTorch model to ONNX model with dynamic shape, I use caffe2 as backend to run the exported model. **Everything is fine** when I run it on CPU, but when I run it on GPU, I get a RuntimeError as following:

> [enforce fail at concat_split_op.h:291] dim == dim_j. 512 vs 34. Expect dimension = 512 got 34 at axis = 2 for input: 1. The input tensors can only have different dimensions when arg 'add_axis' = 0 and along the axis = 1 <[3, 256, 512, 0]> vs <[3, 512, 34, 34]>.

I try it with onnxruntime and I also get a RuntimeError as following:

> Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : Non-zero status code returned while running Node:  Status Message: 

After some simple analyze, I think it is caused by torch.cat and it may related to the limilation of **[ShapeInference](https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md)**. 

## To Reproduce

As my model is big, I just change to some simple example code to reproduce the problem.

    class TestCat(nn.Module):

        def __init__(self):
            super().__init__()
            self.upsample = nn.Upsample(scale_factor=2)

        def forward(self, x, y):
            y = y * 2
            x = self.upsample(x)
            res = torch.cat([x, y], 1)
        
            return res

Export model to ONNX model:

    m = TestCat().cuda()
    x = torch.zeros(1, 3, 112, 112).cuda()
    y = torch.zeros(1, 3, 224, 224).cuda()
    input_names = ['x', 'y']
    output_names = ['res']
    dynamic_axes = {'x': {0: 'batch'}, 'y': {0: 'batch'}, 'res': {0: 'batch'}}

    torch.onnx.export(m, (x, y), "cat_test.onnx", verbose=True,
                  input_names=input_names,
                  output_names=output_names,
                  dynamic_axes=dynamic_axes)

Run it by caffe2 and you will see the error mentioned before:

    model = onnx.load("cat_test.onnx")
    rep = backend.prepare(model, device="CUDA:0")

    x = np.random.random((1, 3, 112, 112)).astype(np.float32)
    y = np.random.random((1, 3, 224, 224)).astype(np.float32)
    res = rep.run([x, y])
    print(res)

When you run it on CPU, everything is fine.

    model = onnx.load("cat_test.onnx")
    rep = backend.prepare(model, device="CPU")

    x = np.random.random((1, 3, 112, 112)).astype(np.float32)
    y = np.random.random((1, 3, 224, 224)).astype(np.float32)
    res = rep.run([x, y])
    print(res)

PS: Surprisingly, when run this simple example with onnxruntime, I do not get the error which occurs when I run my big model.

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.17.0
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0

**Comment by liangt** [comment]
I find another operation also has the same problem, everything is fine when I run on CPU, but it fails when I run GPU.

> RuntimeError: [enforce fail at elementwise_ops_utils.cc:56] A_dim == B_dim || A_dim == 1 || B_dim == 1. 
Error from operator: 
input: "1836" input: "1891" output: "1892" name: "" type: "Add" device_option { device_type: 1 device_id: 0 }

I also test it with onnxruntime, everything goes well. So, I think there may be some problems needed to be located and fixed in caffe2 working with dynamic shape ONNX export.

**Comment by ninkin** [comment]
I've got same problem while running converted onnx model on GPU

> RuntimeError: [enforce fail at elementwise_ops_utils.cc:56] A_dim == B_dim || A_dim == 1 || B_dim == 1. 
Error from operator: 
input: "34" input: "53" output: "54" name: "" type: "Sub" device_option { device_type: 1 device_id: 0 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b 

I converted above onnx model to caffe2 model using convert-onnx-to-caffe2 but still got same problem. It works without any problems on CPU.
however I'm not sure about dynamic_axes.  I got same error regardless of dynamic axes.

**Comment by liuqibj** [comment]
right met the same issue

**Comment by crocodoyle** [comment]
I have the same problem trying to run a Detectron2 Mask-RCNN model

**Comment by williamfzc** [comment]
> I have the same problem trying to run a Detectron2 Mask-RCNN model on CPU

same here with same target.

**Comment by mipa9833** [comment]
@crocodoyle  @williamfzc  Have you solved this?

**Comment by crocodoyle** [comment]
No, I am trying to deploy a smaller model with tflite now

**Comment by williamfzc** [comment]
No, I have to deploy the origin detectron2 model now.

**Comment by nassarofficial** [comment]
Same problem
