### ISSUE TITLE
Indexing numpy with torch.tensor (uint8) don't behave as expected 

### ISSUE THREAD

**Issue by Mathieu-Seurin** [pytorch/pytorch#24901]
## 🐛 Bug

When trying to index a numpy array with a tensor (uint8), sometimes the result can be very from what is expected.

## To Reproduce

```
import numpy as np
import torch

a = torch.FloatTensor([ 0.6, -2, -0.2,  0.9])
b = np.zeros(4)

print(a > 0)
# tensor([1, 0, 0, 1], dtype=torch.uint8)
# This is fine and works as expected

# But, it fails here
b[a > 0] = 1
# b should be [1, 0, 0, 1]
print("Actual result : b = ", b)
#"Actual result :  b = array([1., 1., 0., 0.])"

# This works as intended
b = np.zeros(4)
b[a.numpy() > 0] = 1
print("b = ", b)
#"b = array([1., 0, 0., 1.])"
```

## Expected behavior

Indexing a numpy with a tensor should act the same way as indexing a numpy array with another array. Maybe i'm missing something.

## Environment

Machine 1 : 

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14
GCC version: Could not collect
CMake version: version 3.15.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

Machine 2 : 

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 390.116
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.1.0
[pip3] torch-rl==1.0.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

**Comment by liyz15** [comment]
Try 1.2.0, comparison operations return torch.bool now.

**Comment by Mathieu-Seurin** [comment]
Indeed, it works on 1.2.0.
Thanks !
