### ISSUE TITLE
A lot of deprecation warnings in tests

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#24918]
Several test suites, for example test_indexing, throw deprecation warnings like this: 
`UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.`

**Comment by anshulpaigwar** [comment]
I am facing a similar issue after I upgraded to pytorch 1.2.0

**Comment by izdeby** [comment]
@anshulpaigwar, just FYI, this is intentional. You should update your code and get rid of these warnings as in the next release they will turn into errors once we drop support for uint8 masks and related.

**Comment by creotiv** [comment]
it would be good if it will show where this error happen

**Comment by Papibarozza** [comment]
I fixed this warning by changing objects of type `ByteTensor` to `BoolTensor` instead. This was the source of the warnings for me.
