### ISSUE TITLE
dimension issue of max function 

### ISSUE THREAD

**Issue by LiyuanLucasLiu** [pytorch/pytorch#2494]
I noticed something weird. Maybe it's a bug.

```
import torch as t
tmp = t.LongTensor([2,3]).view(1,-1)
tm, _ = tmp.max(0, keepdim=False)
print(tm)
```
would print
```
2 3
[torch.LongTensor of size 1 * 2]
```

while it seems to me, the output should be ```of size 2``` instead of ```of size 1 * 2``` (since the keepdim is set to False)

**Comment by ruotianluo** [comment]
#2317
