### ISSUE TITLE
change Mask_RCNN backbone 

### ISSUE THREAD

**Issue by ehsanzare** [pytorch/pytorch#24957]
Do we have a guide/example of changing the backbone of provided mask_rcnn in pytorch (e.g. Mask R-CNN ResNet-50 FPN) with other standard classification backbones (e.g. MobineNet, etc)?

cc @SsnL

**Comment by andreaskoepf** [comment]
Please consider using [discuss.pytorch.org](https://discuss.pytorch.org/) for such questions.

**Comment by sergiomena** [comment]
did you find a solution? I have the same problem
