### ISSUE TITLE
Merge python RemoteException with C++ MessageType::EXCEPTION

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#24959]
## 🚀 Feature

As discussed in https://github.com/pytorch/pytorch/pull/24138#issuecomment-522776197, currently RemoteException only shows Python callee side stack trace.

We would like to have caller side Python stack trace as well.

## Solution

In order to know the caller side stack trace,
I think one solution is, on invoking an RPC, the caller side saves the stack trace of itself together with the request future, if the response is an exception, the caller side pulls out the stack trace on itself and concatenate with the other stack trace on the callee side.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by jfc4050** [comment]
one thing that makes this hard is `processRequestBlocking` returns a `Message` of type `MessageType::PYTHON_RET` regardless of whether or not an exception was thrown in the python code. 

This makes it tough for `ProcessGroupAgent` to know whether or not to prepend a caller side stack trace to the response payload, beyond doing a string search for `RemoteException` in the payload which seems hacky and fragile. 

It looks like returning `MessageType::PYTHON_RET` for exceptions in python land and `MessageType::EXCEPTION` for exceptions in C++ land was a conscious design decision, so maybe  can start by making a new message type `MessageType::PYTHON_EXC` and use it for exceptions in python code?

**Comment by zhaojuanmao** [comment]
had second thought, I think we can just simply throw RemoteException on server side with concatenated stack trace message, then python exception can be captured as MessageType::EXCEPTION as well on server side in C++ land. This EXCEPTION message will be passed to client side and handled in the same way as C++ exceptions. 

will put a PR later on

**Comment by rohan-varma** [comment]
@zhaojuanmao I think this is resolved now, as we throw `RemoteException` on the server side now? if so, could you close it out?
