### ISSUE TITLE
In Sparse Adam, initialize state['exp_avg']  and state['exp_avg_sq'] during optimizer initialization, not after step

### ISSUE THREAD

**Issue by Santosh-Gupta** [pytorch/pytorch#24958]
## 🚀 Feature
In the Sparse Adam optimizer, [ https://github.com/pytorch/pytorch/blob/master/torch/optim/sparse_adam.py ]

The 'exp_avg' and 'exp_avg_sq' are only initialized after the first step is taken. And then after each step, there is a check of if the state hasn't been initialized. Compare this to adagrad https://github.com/pytorch/pytorch/blob/master/torch/optim/adagrad.py ], where 'sum' is initialized when the optimizer is initialized. Is there any reason for this? 

## Motivation

For those doing manipulations of 'exp_avg' and 'exp_avg_sq', the code would be clearer if they didn't have to run the first step before coding the manipulators. 

Also, unless I am missing something, the code would seem more cleaner if the state was initialized during the optimizer init, instead of checking if it's been initiated already during each step, though there's probably no performance reduction in the way it's currently coded. 

## Pitch

Move 

```
	                    state['step'] = 0
                    # Exponential moving average of gradient values
                    state['exp_avg'] = torch.zeros_like(p.data)
                    # Exponential moving average of squared gradient values
                    state['exp_avg_sq'] = torch.zeros_like(p.data)
```
to the  __init__ method. 

## Additional context

Here's a full code sample

```
def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8):
        if not 0.0 < lr:
            raise ValueError("Invalid learning rate: {}".format(lr))
        if not 0.0 < eps:
            raise ValueError("Invalid epsilon value: {}".format(eps))
        if not 0.0 <= betas[0] < 1.0:
            raise ValueError("Invalid beta parameter at index 0: {}".format(betas[0]))
        if not 0.0 <= betas[1] < 1.0:
            raise ValueError("Invalid beta parameter at index 1: {}".format(betas[1]))
        defaults = dict(lr=lr, betas=betas, eps=eps)
        super(SparseAdam, self).__init__(params, defaults)

	for group in self.param_groups:
            for p in group['params']:
                state = self.state[p]
                state['exp_avg'] = torch.zeros_like(p.data)
                    # Exponential moving average of squared gradient values
                state['exp_avg_sq'] = torch.zeros_like(p.data)

    def step(self, closure=None):
        """Performs a single optimization step.
        Arguments:
            closure (callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            loss = closure()

        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None:
                    continue
                grad = p.grad.data
                if not grad.is_sparse:
                    raise RuntimeError('SparseAdam does not support dense gradients, please consider Adam instead')

                state['step'] += 1

                grad = grad.coalesce()  # the update is non-linear so indices must be unique
                grad_indices = grad._indices()
                grad_values = grad._values()
                size = grad.size()

```

If there is agreement on this, I already created a pull request, here 

https://github.com/pytorch/pytorch/pull/24960

cc @vincentqb

**Comment by zhangguanheng66** [comment]
@SsnL How do you feel the proposed?

**Comment by SsnL** [comment]
This is BC breaking in the way that currently you can construct the optimizer before moving the optimized tensors returned by the iterable (e.g., `net.parameters()` and `net.to('cuda')`), and the patch breaks it.

I know that we explicitly mentioned in doc that optimizers should always be constructed after moving parameters to different device/dtype. But I don't think that we should introduce BC breaking behavior just for a minor inconsistency with some other optimizers.

**Comment by Santosh-Gupta** [comment]
@SsnL should it be the adagrad optimizer's code that should be changed then?
