### ISSUE TITLE
torch.qscheme should be pickle-able

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#24966]
Attempting to save a model with torch.save(), without using a state_dict leads to the following error:

5 torch.save(myModel,'/data/users/raghuraman/logs/quantized_resnext.pt')
      6 
      7 # Script and serialize Does not work with mode@opt

/mnt/xarfuse/uid-172846/aaeaca24-ns-4026531840/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol)
    222         >>> torch.save(x, buffer)
    223     """
--> 224     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    225 
    226 

/mnt/xarfuse/uid-172846/aaeaca24-ns-4026531840/torch/serialization.py in _with_file_like(f, mode, body)
    147         f = open(f, mode)
    148     try:
--> 149         return body(f)
    150     finally:
    151         if new_fd:

/mnt/xarfuse/uid-172846/aaeaca24-ns-4026531840/torch/serialization.py in <lambda>(f)
    222         >>> torch.save(x, buffer)
    223     """
--> 224     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    225 
    226 

/mnt/xarfuse/uid-172846/aaeaca24-ns-4026531840/torch/serialization.py in _save(obj, f, pickle_module, pickle_protocol)
    294     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    295     pickler.persistent_id = persistent_id
--> 296     pickler.dump(obj)
    297 
    298     serialized_storage_keys = sorted(serialized_storages.keys())

TypeError: can't pickle torch.qscheme objects

**Comment by SsnL** [comment]
`torch.qscheme` should probably be pickle-able. But please save the state_dict instead.

**Comment by jerryzh168** [comment]
fixed by https://github.com/pytorch/pytorch/pull/24969
