### ISSUE TITLE
Make queue_callback() work properly with reentrant backward

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#24965]
Currently, `final_callbacks_` of an autograd engine is a vector shared by all backward passes on this engine.  The autograd engine [clears](https://github.com/pytorch/pytorch/blob/936632b120aafd2d12233c1096d9000fe9554b77/torch/csrc/autograd/engine.cpp#L666) final callbacks at the beginning of the backward call. With reentrant backward calls, the final callback enqueued by the original backward call will be cleared by the reentrant ones (learnt from @pritamdamania87). I was a little surprised on this API behavior as I queued a callback but it never fires. Would it be better if we attach these final callbacks to each graph task? For example, we could use a thread local stack to hold the current graph task, and then push and pop accordingly similar to what we did for `current_depth`. Thoughts?

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
Yes, this sounds wrong to me. A fix would be appreciated.
