### ISSUE TITLE
cuda() Method Warning in PyCharm

### ISSUE THREAD

**Issue by ZaydH** [pytorch/pytorch#24962]
## To Reproduce

Problem only happens with `torch` ver. 1.2.0.  It did not happened before that build.  

Simple code snippet:

```
import torch.nn as nn

x = nn.Linear(10, 10)
x.cuda()
```

On the line `x.cuda()`, PyCharm returns the linter warning: `Parameter 'device' unfilled'.  See screenshot below.

![image](https://user-images.githubusercontent.com/6292018/63429862-1980dc00-c3d0-11e9-9008-e470b32316be.png)

## Expected behavior

No linter error occurs on this line.

## Environment

- PyTorch version: 1.2.0
- Is debug build: No
- CUDA used to build PyTorch: None

- OS: Mac OSX 10.14.6
- GCC version: Could not collect
- CMake version: version 3.13.2

Python version: 3.7
- Is CUDA available: No
- CUDA runtime version: No CUDA
- GPU models and configuration: No CUDA
- Nvidia driver version: No CUDA
- cuDNN version: No CUDA

Versions of relevant libraries:
- [pip3] msgpack-numpy==0.4.3.2
- [pip3] numpy==1.16.4
- [pip3] torch==1.2.0
- [pip3] torchfile==0.1.0
- [pip3] torchnet==0.0.4
- [pip3] torchtext==0.3.1
- [pip3] torchvision==0.4.0
- [conda] Could not collect

### PyCharm Info

* PyCharm 2019.2.1 RC (Professional Edition)
* Build #PY-192.6262.38, built on August 15, 2019
* Runtime version: 11.0.3+12-b304.39 x86_64
* VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.14.6
* GC: ParNew, ConcurrentMarkSweep
* Memory: 1933M
* Cores: 8
* Registry: debugger.watches.in.variables=false
* Non-Bundled Plugins: 

**Note**: I saw this issue before upgrading the latest PyCharm release candidate.  I switched to the RC to see if it would address the problem.

## Additional context

It seems the error is in [this line](https://github.com/pytorch/pytorch/blob/1b8efd3d92768965ccd3f6bd94378a3effdac8cb/torch/nn/modules/module.pyi.in#L32):

`def cuda(self: T, device: Union[int, device]) -> T: ...`

in file `torch/nn/modules/module.pyi`.

I believe the correct line should be:

`def cuda(self: T, device: Optional[Union[int, device]] = ...) -> T: ...`

since the default value is `None` in the [module.py](https://github.com/pytorch/pytorch/blob/1b8efd3d92768965ccd3f6bd94378a3effdac8cb/torch/nn/modules/module.py#L297).

**Comment by ZaydH** [comment]
If surrounding the type in `Optional` is acceptable to you as a solution, I can submit a PR.

**Comment by zhangguanheng66** [comment]
@VitalyFedyunin Will you accept the fix?

**Comment by ZaydH** [comment]
@VitalyFedyunin I issued a PR for this.  If you are disagree, feel free to reject or propose an alternative

**Comment by ZaydH** [comment]
Closed based on PR #25018
