### ISSUE TITLE
sccache version in OSS CI is too old

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#24982]
The `sccache` used in OSS CI is based on https://github.com/yf225/sccache, which is outdated (circa. mid-2018) and missing some important fixes on upstream (e.g. https://github.com/mozilla/sccache/issues/248). The correct steps to fix this would involve:

- [ ] Pull upstream changes into https://github.com/yf225/sccache, and build our own copy.
- [ ] Upstream our patch for NVCC support to official repo.
- [ ] Upstream our patch for HCC support to official repo.
- [ ] Build new `sccache` using upstream master (or a release that has our patches), and then use the new binary in our OSS CI.

cc. @gchanan @ezyang @peterjc123 

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by ezyang** [comment]
We should build our own copy with our patches in the meantime while waiting for the patches to upstream

**Comment by peterjc123** [comment]
@yf225 Any plan to rebuild the sccache?

**Comment by yf225** [comment]
@peterjc123 Yes I am planning to rebuild it. Is there anything I should watch out for regarding Windows build?

**Comment by peterjc123** [comment]
@yf225 Nope, I guess the build [guide](https://github.com/mozilla/sccache#windows) in the official repo should be enough.

**Comment by ezyang** [comment]
I'm bumping priority so we don't miss this. In https://github.com/pytorch/pytorch/issues/36381 @peterjc123  has updated sccache to master in a PR and deployed it to Windows, so we have a lot of the stuff we need already done.

**Comment by ezyang** [comment]
@peterjc123: @yf225 is transitioning to another team in FB, so we should probably also transfer the repository to somewhere shared. I guess we can maintain a fork of sccache in the pytorch org, assuming we can't just upstream all of our relevant patches. @soumith what do you think?

**Comment by ezyang** [comment]
peterjc123's pr is https://github.com/yf225/sccache/pull/2

**Comment by soumith** [comment]
@ezyang yes, let's fork and maintain

**Comment by soumith** [comment]
forked from mozilla/sccache: https://github.com/pytorch/sccache

**Comment by mattip** [comment]
Currently sccache is installed 
- in the docker image via `docker/caffe2/jenkins/common/install_ccache.sh` which downloads https://s3.amazonaws.com/ossci-linux/sccache
- windows via `.jenkins/pytorch/win-test-helpers/installation-helpers/install_sccache.bat` which downloads `https://s3.amazonaws.com/ossci-windows/sccache{,-cl}.exe` or s3://ossci-windows/sccache{,-cl}.exe
- in macos via `.circleci/verbatim-sources/caffe2-job-specs.yml` or `.circleci/verbatim-sources/job-specs-custom.yml` which both download https://s3.amazonaws.com/ossci-macos/sccache.

Is there documentation how to update those binaries or to which commit in https://github.com/pytorch/sccache they correspond?

**Comment by peterjc123** [comment]
@mattip The update is currently done manually.

**Comment by peterjc123** [comment]
> which commit in https://github.com/pytorch/sccache they correspond?

Sorry, I didn't see this question. The Windows one correspond to the latest commit in pytorch/sccache and the other two points to the commit in yf225/sccache.

**Comment by ngimel** [comment]
Closing due to age
