### ISSUE TITLE
Segmentation Fault on the latest pytorch with cuda 10.1

### ISSUE THREAD

**Issue by Magnetar99** [pytorch/pytorch#24983]
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffc36857d8 in ?? () from /usr/local/cuda/lib64/libcudart.so.10.1
(gdb) where
#0  0x00007fffc36857d8 in ?? () from /usr/local/cuda/lib64/libcudart.so.10.1
#1  0x00007fffc368bb01 in ?? () from /usr/local/cuda/lib64/libcudart.so.10.1
#2  0x00007fffc367e98e in ?? () from /usr/local/cuda/lib64/libcudart.so.10.1
#3  0x00007fffc367f006 in ?? () from /usr/local/cuda/lib64/libcudart.so.10.1
#4  0x00007fffcab3f797 in __cudaUnregisterBinaryUtil () from /home/gautam/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so
#5  0x00007ffff7deb42c in __run_exit_handlers (status=0, listp=0x7ffff7f8b718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#6  0x00007ffff7deb55a in __GI_exit (status=<optimized out>) at exit.c:139
#7  0x00007ffff7dcb0a2 in __libc_start_main (main=0x55555564aed0 <main>, argc=2, argv=0x7fffffffe308, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2f8) at ../csu/libc-start.c:342
#8  0x0000555555734122 in _start () at ../sysdeps/x86_64/elf/start.S:103

**Comment by zhangguanheng66** [comment]
Can you send us some scripts to reproduce the error?

**Comment by soumith** [comment]
please reopen the issue once you have a way for us to reproduce the issue
