### ISSUE TITLE
Memory leak in high order derivative? (pytorch 0.2)

### ISSUE THREAD

**Issue by LIU-Xuanqing** [pytorch/pytorch#2498]
Not sure if this implementation is efficient, but when calculating Hessian-vector product in a loop, it terminates because of out of memory after ~30 iterations (Titan X), here is my implementation:

```Python
     net = VGG() # could be other model
     loss_f = nn.NLLLoss()
     net.cuda()
     loss_f.cuda()
     data = dst.CIFAR10("~/cifar10-py", download=True, train=True, transform=tfs.Compose(
                                                                   [ tfs.ToTensor(),
                                                                     tfs.Normalize((.5, .5, .5), (.5, .5, .5)) ]))
     dataloader = DataLoader(data, batch_size=opt.batchSize, shuffle=True, num_workers=2)
     v = []
     for i, p in enumerate(net.parameters()):
         v.append(Variable(torch.FloatTensor(p.data.size()).normal_(0, 1).cuda(), requires_grad=False))
     for img, label in dataloader:
         img = img.cuda()
         label = label.cuda()
         input = Variable(img, requires_grad=True)
         target = Variable(label)
         output = net(input)
         loss = loss_f(output, target)
         grad_params = torch.autograd.grad(loss, net.parameters(), create_graph=True)
         inner_prod = 0.0
         for vi, grad in zip(v, grad_params):
             inner_prod += torch.sum(grad * vi)
         Hv = torch.autograd.grad(inner_prod, net.parameters(), create_graph=True)
```

Basically, it first calculates loss, then gradient of weight. Do an inner product with v, then takes gradient of weight again. Similar code works good on Theano.

Here is the traceback:

THCudaCheck FAIL file=xxx/pytorch-0.2.0/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "./main.py", line 50, in <module>
    Hv = torch.autograd.grad(inner_prod, grad_params, create_graph=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 153, in grad
    inputs, only_inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/thnn/batchnorm_double_backwards.py", line 70, in batchnorm_double_backwards_fn
    gI_2t = (gOinmu_sum * sigma2_eps_neg_3_2).div_(M) * (ggI_sum.div(M) - ggI)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 820, in __sub__
    return self.sub(other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 332, in sub
    return self._sub(other, False)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 326, in _sub
    return Sub.apply(self, other, inplace)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/basic_ops.py", line 34, in forward
    return a.sub(b)
RuntimeError: cuda runtime error (2) : out of memory at xxx/pytorch-0.2.0/torch/lib/THC/generic/THCStorage.cu:66

**Comment by LIU-Xuanqing** [comment]
I've found a similar topic in #2287 . Which should be fixed in #2328 and #2326 
But I think this issue is different, if I comment out 
`Hv = torch.autograd.grad(inner_prod, net.parameters(), create_graph=True)` 
then it won't leak.

**Comment by gchanan** [comment]
Can you try building trunk and running your test to see if it still leaks?

**Comment by TatjanaCh** [comment]
Hi. I also get the same error. 
I've a loop and the used gpu memory adds up after each iteration when I use torch.autograd.grad + backward, and eventually I get 'out of memory' error. 
If I comment out, it stays constant.
Even if I do everything in a function, the memory remains allocated after it.

For example in the code for WGAN+GP:
    interp_alpha.resize_(batch_size, 1)
    interp_alpha.uniform_()

    interp_points = Variable((interp_alpha.expand_as(vinput.data)*vinput.data +
                              (1-interp_alpha.expand_as(vinput.data))*vinput2.data), requires_grad=True)
    errD_interp_vec = netD(interp_points)
    errD_gradient, = torch.autograd.grad(errD_interp_vec.sum(), interp_points, create_graph=True)

    lip_est = (errD_gradient**2).view(batch_size, -1).sum(1)**0.5
    lip_loss = opt.penalty_weight*(clip_fn(1.0-lip_est)**2).mean(0).view(1)

    lip_loss.backward()

Here if I don't backward lip_loss, there's no memory leak
Any idea? Thanks a lot!

**Comment by TatjanaCh** [comment]
Please find bellow a minimal example:


`from __future__ import print_function
import sys
import argparse
import os
import random
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.optim as optim
import torch.utils.data
# import torchvision.datasets as dset
# import torchvision.transforms as transforms
# import torchvision.utils as vutils
from torch.autograd import Variable

try:
    import gpustat
except ImportError:
    raise ImportError("pip install gpustat")


def show_memusage(device=1):
    gpu_stats = gpustat.GPUStatCollection.new_query()
    item = gpu_stats.jsonify()["gpus"][device]
    print(pclr.blue + 'Used/total: ' + "{}/{}".format(item["memory.used"], item["memory.total"]) + pclr.endc)
    # print("{}/{}".format(item["memory.used"], item["memory.total"]))


class pclr:
    blue = '\033[94m'
    green = '\033[92m'
    warn = '\033[93m'
    endc = '\033[0m'
    bold = '\033[1m'


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
###############################################################

def run_exp():
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    if opt.use_grad_loss:
        print(pclr.warn + 'using grad loss...' + pclr.endc)

    class _netG(nn.Module):
        def __init__(self, ngpu):
            super(_netG, self).__init__()
            self.ngpu = ngpu
            self.main = nn.Sequential(
                nn.ConvTranspose2d(     nz, ngf * 8, 4, 1, 0, bias=False),
                nn.BatchNorm2d(ngf * 8),
                nn.ReLU(True),
                # state size. (ngf*8) x 4 x 4
                nn.ConvTranspose2d(ngf * 8, ngf * 4, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ngf * 4),
                nn.ReLU(True),
                nn.ConvTranspose2d(ngf * 4, ngf * 2, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ngf * 2),
                nn.ReLU(True),
                # state size. (ngf*2) x 16 x 16
                nn.ConvTranspose2d(ngf * 2,     ngf, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ngf),        # T:removed
                nn.ReLU(True),
                # state size. (ngf) x 32 x 32
                nn.ConvTranspose2d(    ngf,      nc, 4, 2, 1, bias=False),
                nn.Tanh()
            )

        def forward(self, input):
            return self.main(input)

    class _netD(nn.Module):
        def __init__(self, ngpu):
            super(_netD, self).__init__()
            self.ngpu = ngpu
            self.main = nn.Sequential(
                # input is (nc) x 64 x 64
                nn.Conv2d(nc, ndf, 4, 2, 1, bias=False),
                nn.LeakyReLU(0.2, inplace=True),
                # state size. (ndf) x 32 x 32
                nn.Conv2d(ndf, ndf * 2, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ndf * 2),
                nn.LeakyReLU(0.2, inplace=True),
                # state size. (ndf*2) x 16 x 16
                nn.Conv2d(ndf * 2, ndf * 4, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ndf * 4),
                nn.LeakyReLU(0.2, inplace=True),
                # state size. (ndf*4) x 8 x 8
                nn.Conv2d(ndf * 4, ndf * 8, 4, 2, 1, bias=False),
                nn.BatchNorm2d(ndf * 8),
                nn.LeakyReLU(0.2, inplace=True),
                # state size. (ndf*8) x 4 x 4
                nn.Conv2d(ndf * 8, 1, 4, 1, 0, bias=False),
                nn.Sigmoid()
            )

        def forward(self, input):
            output = self.main(input)
            return output.view(-1, 1)

    netG = _netG(ngpu)

    netD = _netD(ngpu)

    if opt.cuda:
        netD.cuda()
        netG.cuda()

    if opt.adam:
        optimizerD = optim.Adam(netD.parameters(), lr=opt.lrD, betas=(opt.beta1, 0.999))
        optimizerG = optim.Adam(netG.parameters(), lr=opt.lrG, betas=(opt.beta1, 0.999))
    else:
        optimizerD = optim.RMSprop(netD.parameters(), lr=opt.lrD)
        optimizerG = optim.RMSprop(netG.parameters(), lr=opt.lrG)

    ################################################################################################

    input = dtype(opt.batchSize, 3, opt.imageSize, opt.imageSize)
    input2 = dtype(opt.batchSize,  nz, 1, 1)
    interp_alpha = dtype(opt.batchSize, 1)
    noise = dtype(opt.batchSize,  nz, 1, 1)
    one = dtype([1])
    mone = one * -1

    for epoch in range(1):
    # for epoch in range(opt.niter):

        vinput = Variable(input, requires_grad=False)
        vinput2 = Variable(input2)
        vnoise = Variable(noise)

        # data_iter = iter(dataloader)
        i = 0
        # while i < len(dataloader):
        while i < opt.Diters:   # sanity check

            ############################
            # (1) Update D network
            ###########################
            for p in netD.parameters():  # reset requires_grad
                p.requires_grad = True  # they are set to False below in netG update

            for ditr in range(opt.Diters): # Diters is 5
                print('Diter: %d/%d' % (ditr, opt.Diters))
                if opt.cuda:
                    show_memusage()
                # if not opt.use_grad_loss:
                #     # clamp parameters to a cube
                #     for p in netD.parameters():
                #         p.data.clamp_(opt.clamp_lower, opt.clamp_upper)

                # data = data_iter.next()
                i += 1

                # train with real
                # real_cpu, _ = data
                netD.zero_grad()
                # batch_size = real_cpu.size(0)
                batch_size = opt.batchSize
                # vinput.data.resize_(real_cpu.size()).copy_(real_cpu)
                vinput.data.uniform_(0, 1)

                errD_real_vec = netD(vinput)
                errD_real = errD_real_vec.mean(0).view(1)
                errD_real.backward(one, retain_graph=opt.use_grad_loss)

                # train with fake
                vnoise.data.resize_(batch_size, nz, 1, 1)
                vnoise.data.normal_(0, 1)
                fake = netG(vnoise)
                vinput2.data.resize_(fake.data.size()).copy_(fake.data)
                errD_fake_vec = netD(vinput2)
                errD_fake = errD_fake_vec.mean(0).view(1)
                errD_fake.backward(mone, retain_graph=opt.use_grad_loss)

                if opt.use_grad_loss:

                    interp_alpha.resize_(batch_size, 1)
                    interp_alpha.uniform_()

                    interp_points = Variable((interp_alpha.expand_as(vinput.data)*vinput.data +
                                              (1-interp_alpha.expand_as(vinput.data))*vinput2.data), requires_grad=True)
                    errD_interp_vec = netD(interp_points)
                    errD_gradient = torch.autograd.grad(errD_interp_vec.sum(), interp_points, create_graph=True)[0]


                    lip_est = (errD_gradient**2).view(batch_size, -1).sum(1)**0.5
                    lip_loss = opt.penalty_weight * ((1.0 - lip_est) ** 2).mean(0).view(1)

                    # # or even simpler stuff
                    # lip_loss = errD_gradient.view(batch_size, -1).sum(1).mean(0).view(1) #- mone
                    # lip_loss.backward()

                    lip_loss.backward()
                    print('grad-loss: %f' % lip_loss.data[0])

                optimizerD.step()

            ############################
            # (2) Update G network
            ###########################
            for p in netD.parameters():
                p.requires_grad = False  # to avoid computation
            netG.zero_grad()
            vnoise.data.resize_(opt.batchSize, nz, 1, 1)
            vnoise.data.normal_(0, 1)
            fake = netG(vnoise)
            errG = netD(fake)
            errG = errG.mean(0).view(1)
            errG.backward(one)
            optimizerG.step()


################################################################################################
# Main
################################################################################################
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # parser.add_argument('--dataset', help='cifar10 | lsun | imagenet | folder | lfw ')
    # parser.add_argument('--dataroot', help='path to dataset')
    parser.add_argument('--workers', type=int, help='number of data loading workers', default=0)
    parser.add_argument('--batchSize', type=int, default=64, help='input batch size')
    parser.add_argument('--imageSize', type=int, default=64, help='the height / width of the input image to network')
    parser.add_argument('--nz', type=int, default=100, help='size of the latent z vector')
    parser.add_argument('--ngf', type=int, default=64)
    parser.add_argument('--ndf', type=int, default=64)
    parser.add_argument('--niter', type=int, default=25, help='number of epochs to train for')
    parser.add_argument('--ngpu', type=int, default=1, help='number of GPUs to use')
    parser.add_argument('--netG', default='', help="path to netG (to continue training)")
    parser.add_argument('--netD', default='', help="path to netD (to continue training)")
    parser.add_argument('--manualSeed', type=int, default=1, help='seed, default %(default)s')
    parser.add_argument('--lrD', type=float, default=0.00005, help='default: %(default)s')
    parser.add_argument('--lrG', type=float, default=0.00005, help='default: %(default)s')
    parser.add_argument('--beta1', type=float, default=0.5, help='beta1 for adam, '
                                                                 'default: %(default)s')
    parser.add_argument('--cuda', action='store_true', help='enable gpu, default: %(default)s')
    parser.add_argument('--adam', action='store_true', help='use adam, default is rmsprop')
    parser.add_argument('--clamp_lower', type=float, default=-0.01, help='default: %(default)s')
    parser.add_argument('--clamp_upper', type=float, default=0.01, help='default: %(default)s')
    parser.add_argument('--Diters', type=int, default=5, help='number of D iters per each G iter,'
                                                              'default: %(default)s')
    parser.add_argument('--use_grad_loss', action='store_true', help='default: %(default)s')
    parser.add_argument('--penalty_weight', default=10.0, type=float,
                        help='penalty weight term lambda, default: %(default)s')
    opt = parser.parse_args()
    print(opt)

    if opt.cuda:
        torch.cuda.manual_seed(opt.manualSeed)
        dtype = torch.cuda.FloatTensor
        cudnn.benchmark = True
    else:
        dtype = torch.FloatTensor

    print("Random Seed: ", opt.manualSeed)
    random.seed(opt.manualSeed)
    torch.manual_seed(opt.manualSeed)

    if torch.cuda.is_available() and not opt.cuda:
        print("WARNING: You have a CUDA device, so you should probably run with --cuda")

    ngpu = int(opt.ngpu)
    nz = int(opt.nz)
    ngf = int(opt.ngf)
    ndf = int(opt.ndf)
    nc = 3

    for _ in range(10):
        run_exp()
        if opt.cuda:
            print(pclr.green + 'gpu-mem-usage after f-n call' + pclr.endc)
            show_memusage()
            print()
`


output snippets:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using grad loss...
Diter: 0/5
Used/total: 5531/12189
grad-loss: 4.669958
Diter: 1/5
Used/total: 5531/12189
grad-loss: 2.748320
Diter: 2/5
Used/total: 5547/12189
grad-loss: 3.942063
Diter: 3/5
Used/total: 5669/12189
grad-loss: 3.353087
Diter: 4/5
Used/total: 5669/12189
grad-loss: 1.932555
gpu-mem-usage after f-n call
Used/total: 5743/12189

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using grad loss...
Diter: 0/5
Used/total: 5743/12189
grad-loss: 4.207576
Diter: 1/5
Used/total: 5743/12189
grad-loss: 2.759463
Diter: 2/5
Used/total: 5759/12189
grad-loss: 1.509981
Diter: 3/5
Used/total: 5881/12189
grad-loss: 1.153147
Diter: 4/5
Used/total: 5881/12189
grad-loss: 1.564567
gpu-mem-usage after f-n call
Used/total: 5897/12189

###################################################
# second case 
###################################################


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Diter: 0/5
Used/total: 3601/12189
Diter: 1/5
Used/total: 3601/12189
Diter: 2/5
Used/total: 3601/12189
Diter: 3/5
Used/total: 3601/12189
Diter: 4/5
Used/total: 3601/12189
gpu-mem-usage after f-n call
Used/total: 3601/12189

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Diter: 0/5
Used/total: 3601/12189
Diter: 1/5
Used/total: 3601/12189
Diter: 2/5
Used/total: 3601/12189
Diter: 3/5
Used/total: 3601/12189
Diter: 4/5
Used/total: 3601/12189
gpu-mem-usage after f-n call
Used/total: 3601/12189


please run it with: python sanity-check.py --cuda [--use_grad_loss]
To monitor the gpu mem usage please adjust argument 'device' of show_memusage.

Am I missing some sort of detach_?
What I am surprised is that after the function call when using '--use_grad_loss' the memory adds up, as the first output snippet shows in the lines after 'gpu-mem-usage after f-n call'. In the second snippet where grad is not used, the used gpu memory stays constant.

Please note that I tried totally different experiments with different arguments of autograd.grad (for eg. specifying inputs, outputs, grad_outputs) and in my case I observed the same thing. 
As soon as I have larger model the memory leak appears. 
If I use simple MLPs I don't get this (or at least I should wait longer to notice).
Thanks a lot!

**Comment by LIU-Xuanqing** [comment]
I close this issue because [wgan-gp](https://github.com/caogang/wgan-gp) uses high order grad without memory problem.

**Comment by LIU-Xuanqing** [comment]
@gchanan As far as I know, this issue is related with BatchNorm layer. If I remove all those layers then memory usage is constant.

**Comment by gchanan** [comment]
@LIU-Xuanqing did you try installing from source as I mentioned above?

**Comment by LIU-Xuanqing** [comment]
@gchanan Aha... I used the wrong source from: https://github.com/pytorch/pytorch/releases/tag/v0.2.0

It works using master branch, thanks!

**Comment by chao1224** [comment]
Hi Xuanqing, @xuanqing94 

I'm also working on second-order derivative. Can you help with two questions here?
1. It seems like the hessian output has the same dimension as weight parameters right? Since all of the gradients are accumulated w.r.t. the target tensor.
2. When calculating the inner product, `inner_prod += torch.sum(grad * vi)` , the `vi` is under the normal distribution, curious why the normal distribution? I was wondering if we can try `inner_prod += torch.sum(grad)`

Thank you in advance.

**Comment by xuanqing94** [comment]
@chao1224 Hi, 
1. Hessian has dimension dxd where d is dimension of weight, I'm calculating Hessian-vector product, which has d.
2. vi can be any d-dim vector, I use normal distribution just for testing. if you use torch.sum(grad) then it is a special case: vi=torch.ones(d)

**Comment by chao1224** [comment]
Thanks for answering @xuanqing94 
And it would make much more sense if we set `vi = \epsilon` right?
