### ISSUE TITLE
How to use manually installed third_party libraries, instead of recursive third_party?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#25003]
Some of the packages **have been manually installed** on the system. How to build **everything** based on existing packages, instead of the **recursively checked out** third_party libraries?

For instance: **pybind11** ???

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
