### ISSUE TITLE
Build pytorch from source: third_party package ERRORs...

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#25002]
Hi, all:

Trying to build Pytorch via cmake, but failed with the following ERROR messages:

```
CMake Error at third_party/QNNPACK/CMakeLists.txt:326 (ADD_SUBDIRECTORY):
   The source directory

     ....../pytorch/third_party/psimd

   does not contain a CMakeLists.txt file.



 CMake Error at third_party/QNNPACK/CMakeLists.txt:336 (ADD_SUBDIRECTORY):
   The source directory

     ....../pytorch/third_party/FP16

   does not contain a CMakeLists.txt file.



 CMake Error at cmake/External/nnpack.cmake:68 (add_subdirectory):
   The source directory

     ....../pytorch/third_party/NNPACK

   does not contain a CMakeLists.txt file.
 Call Stack (most recent call first):
   cmake/Dependencies.cmake:279 (include)
   CMakeLists.txt:305 (include)



 CMake Error at cmake/External/nnpack.cmake:73 (set_property):
   set_property could not find TARGET nnpack.  Perhaps it has not yet been
   created.
 Call Stack (most recent call first):
   cmake/Dependencies.cmake:279 (include)
   CMakeLists.txt:305 (include)
```

However, I do have

```
....../pytorch/third_party/QNNPACK
longervision-GT72-6QE% ls
bench  cmake  CMakeLists.txt  CODE_OF_CONDUCT.md  configure.py  confu.yaml  CONTRIBUTING.md  deps  include  jni  LICENSE  README.md  scripts  src  test
```

Any suggestions please?

**Comment by peterjc123** [comment]
Please try `git submodule update --init --recursive`.

**Comment by ifedan** [comment]
Try the solution preposed by @peterjc123. For now, I will close this issue, but feel encouraged to reopen this issue, if this does not apply.

**Comment by ZhiyaoZhou** [comment]
i met the same problem during compiling pytorch locally. But i tried retyping the code "git submodule update --init --recursive" according to @peterjc123 , but the terminal didn't print anything, and it still didn't work.
Until i solved the problem by doing this: 
(my error occured is "could not find .../pytorch/third_party/QNNPACK/CMakeLists.txt") I searched the QNNPACK in google, and found it's a package of Pytorch, and i runned "git clone https://github.com/pytorch/QNNPACK.git" under directory /pytorch/third_party, and it did work!
