### ISSUE TITLE
Error in THC while building from Master

### ISSUE THREAD

**Issue by priyankamandikal** [pytorch/pytorch#2500]
> -- Build files have been written to: /home/ram/pytorch/torch/lib/build/THNN
Scanning dependencies of target THNN
[ 50%] Building C object CMakeFiles/THNN.dir/init.c.o
[100%] Linking C shared library libTHNN.so
[100%] Built target THNN
Install the project...
-- Install configuration: "Release"
-- Installing: /home/ram/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1
-- Installing: /home/ram/pytorch/torch/lib/tmp_install/lib/libTHNN.so
-- Set runtime path of "/home/ram/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1" to ""
-- Installing: /home/ram/pytorch/torch/lib/tmp_install/include/THNN/THNN.h
-- Installing: /home/ram/pytorch/torch/lib/tmp_install/include/THNN/generic/THNN.h
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /home/ram/anaconda2/bin/cc
-- Check for working C compiler: /home/ram/anaconda2/bin/cc -- works
-- Detecting C compiler ABI info
-- Checking if C linker supports --verbose
-- Checking if C linker supports --verbose - yes
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/ram/anaconda2/bin/c++
-- Check for working CXX compiler: /home/ram/anaconda2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Checking if CXX linker supports --verbose
-- Checking if CXX linker supports --verbose - yes
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Removing -DNDEBUG from compile flags
-- TH_LIBRARIES: /home/ram/pytorch/torch/lib/tmp_install/lib/libTH.so.1
-- Found CUDA: /usr/local/cuda-7.5 (found suitable version "7.5", minimum required is "5.5") 
-- Checking prototype magma_get_sgeqrf_nb for MAGMA_V2 - True
-- Compiling with MAGMA support
-- MAGMA INCLUDE DIRECTORIES: /home/ram/anaconda2/include
-- MAGMA LIBRARIES: /home/ram/anaconda2/lib/libmagma.a
-- MAGMA V2 check: 1
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;5.2+PTX
-- got cuda version 7.5
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS:  -DTH_INDEX_BASE=0 -I/home/ram/pytorch/torch/lib/tmp_install/include   -I/home/ram/pytorch/torch/lib/tmp_install/include/TH -I/home/ram/pytorch/torch/lib/tmp_install/include/THC   -I/home/ram/pytorch/torch/lib/tmp_install/include/THS -I/home/ram/pytorch/torch/lib/tmp_install/include/THCS   -I/home/ram/pytorch/torch/lib/tmp_install/include/THPP -I/home/ram/pytorch/torch/lib/tmp_install/include/THNN   -I/home/ram/pytorch/torch/lib/tmp_install/include/THCUNN;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_52,code=compute_52;-DCUDA_HAS_FP16=1
-- THC_SO_VERSION: 1
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ATEN_LIBRARIES
    NO_CUDA
    THCS_LIBRARIES
    THCUNN_LIBRARIES
    THCUNN_SO_VERSION
    THC_LIBRARIES
    THD_SO_VERSION
    THNN_LIBRARIES
    THNN_SO_VERSION
    THPP_LIBRARIES
    THS_LIBRARIES
    TH_SO_VERSION

> -- Build files have been written to: /home/ram/pytorch/torch/lib/build/THC
> [  1%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
> [  4%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
> [  4%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
> [  4%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
> [  6%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
> [  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
> [  8%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
> [  9%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
> [ 10%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
> [ 12%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
> [ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
> [ 14%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
> Segmentation fault
> CMake Error at THC_generated_THCSleep.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCSleep.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> Segmentation fault
> CMake Error at THC_generated_THCBlas.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensor.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensorMathBlas.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathBlas.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensorMathMagma.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathMagma.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCHalf.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensorMath2.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath2.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCStorage.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
> Segmentation fault
> CMake Error at THC_generated_THCTensorMath.cu.o.cmake:267 (message):
>   Error generating file
>   /home/ram/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o
> 
> 
> make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
> make[1]: *** [CMakeFiles/THC.dir/all] Error 2
> make: *** [all] Error 2

**Comment by vishwakftw** [comment]
Closing as this is outdated.
