### ISSUE TITLE
torch.max() inconsistent behaviour with NaNs

### ISSUE THREAD

**Issue by danielcrane** [pytorch/pytorch#25016]
## 🐛 Bug

When using `torch.max()` between two tensors where one tensor contains nans, the result varies depending upon the order of input into `torch.max()`.

## To Reproduce

```
import torch
x = torch.ones(3)
y = torch.ones(3) * torch.tensor(float('nan'))

print(f'torch.max(x, y) : {torch.max(x, y)}')
print(f'torch.max(y, x) : {torch.max(y, x)}')
```
Returns:
```
torch.max(x, y) : tensor([nan, nan, nan])
torch.max(y, x) : tensor([1., 1., 1.])
```

## Expected behavior

I'd expect the output to be consistent in both cases.
i.e. `torch.max(x, y) = torch.max(y, x)` in all cases.

My personal preference would be as in the above case of `torch.max(y,x) = [1,1,1]`, but the most important part is that it should be consistent.

**Comment by andreaskoepf** [comment]
The problem is that all comparisons with `nan` always return `False` - `even float('nan') == float('nan')`. For `max` the `nan` case is not specially handled. It is simply does `a < b ? b : a` (or in Python `b if a < b else a`).

btw this behavior seems to be consistent with standard Python:

```
>>> a = 1
>>> b = float('nan')
>>> print(max(a, b))
1
>>> print(max(b, a))
nan
```

**Comment by andreaskoepf** [comment]
Behavior of other libs:

[numpy.maximum()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html): "If one of the elements being compared is a NaN, then that element is returned. (..) The net effect is that NaNs are propagated."

[cuda fmax()](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1g6e7516db46be25c33fb26e203287f2a3): " Treats NaN arguments as missing data. If one argument is a NaN and the other is legitimate numeric value, the numeric value is chosen."

I personally would prefer the numpy behavior and in general that min, max, sum and mean would be [symmetric](https://en.wikipedia.org/wiki/Symmetric_function) functions.

(To use NaNs as missing values to ignore during `max()` one could replace them manually using `y[y!=y] = float('-inf')`.)

**Comment by andreaskoepf** [comment]
For tensors itself NaNs are already propagated, see
https://github.com/pytorch/pytorch/blob/789f4ad87b0f57c94798e228fa48dd664dcddadf/aten/src/TH/generic/THTensorMoreMath.cpp#L164-L170

```
a = torch.tensor([float('nan'), 1])
b = torch.tensor([1, float('nan')])
a.max()
b.max()
```

```
>>> a = torch.tensor([float('nan'), 1])
>>> b = torch.tensor([1, float('nan')])
>>> a.max()
tensor(nan)
>>> b.max()
tensor(nan)
```
The element-wise functions should replicate this.

**Comment by andreaskoepf** [comment]
Source refs to relvant element-wise functions:

CPU: https://github.com/pytorch/pytorch/blob/789f4ad87b0f57c94798e228fa48dd664dcddadf/aten/src/TH/generic/THTensorMoreMath.cpp#L305-L327

CUDA: https://github.com/pytorch/pytorch/blob/789f4ad87b0f57c94798e228fa48dd664dcddadf/aten/src/THC/generic/THCTensorMathPointwise.cu#L111-L177

and:
https://github.com/pytorch/pytorch/blob/789f4ad87b0f57c94798e228fa48dd664dcddadf/aten/src/THC/THCTensorMathPointwise.cuh#L343-L393

ref #24728 and #24594 (max TH->ATen) since the it affects `Tensor max(const Tensor & other) const;`.

**Comment by danielcrane** [comment]
> I personally would prefer the numpy behavior and in general that min, max, sum and mean would be [symmetric](https://en.wikipedia.org/wiki/Symmetric_function) functions.

I totally agree with the sentiment that they should be symmetric, from a mathematical perspective it feels really odd for a max function to be asymmetric, and in this specific case it could cause indeterminism in parallel code where processing order isn't guaranteed.

**Comment by xuhdev** [comment]
#27185 was reverted, now reopen this issue

**Comment by xuhdev** [comment]
Gotta reopen this again -- #30851 intentionally skipped fixing this issue
