### ISSUE TITLE
wrong results of torch.argsort()

### ISSUE THREAD

**Issue by ZacBi** [pytorch/pytorch#25013]
## To Reproduce

```python
>>> a = torch.randn((3, 4))
>>> a
tensor([[ 0.6673, -1.6090, -0.9818, -0.5651],
        [ 0.5259,  0.9284,  1.7999,  1.4490],
        [ 0.8087,  1.3849, -0.7312,  0.7918]])
>>> torch.argsort(a)
tensor([[1, 2, 3, 0],
        [0, 1, 3, 2],
        [2, 3, 0, 1]])
```

## Expected behavior
torch.argsort(a) sholud be:
```python
tensor([[3, 0, 1, 2],
        [0, 1, 3, 2],
        [2, 3, 0, 1]])
```

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 430.40
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] pytorch-transformers==1.0.0
[conda] mkl                       2019.4                      243    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.4.0                py36_cu100    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

**Comment by andreaskoepf** [comment]
The argsort output seems to be correct.

Please check the docs of [argsort](https://pytorch.org/docs/stable/torch.html?highlight=argsort#torch.argsort): "Returns the indices that sort a tensor along a given dimension in ascending order by value"

```
>>> order = a.argsort()
>>> a = torch.randn(3,3)
>>> b = a.argsort()
>>> a[0][b[0]]
tensor([-1.1886, -1.0116, -0.7388])
>>> a[1][b[1]]
tensor([-1.7961,  0.0980,  2.3254])
```

**Comment by andreaskoepf** [comment]
Maybe there is a simpler way, but to get order of elements you could scatter the column-indices, something like:

```
a = torch.tensor([[ 0.6673, -1.6090, -0.9818, -0.5651],
    [ 0.5259,  0.9284,  1.7999,  1.4490],
    [ 0.8087,  1.3849, -0.7312,  0.7918]])
b = a.argsort()
d = torch.arange(4).repeat(3,1)
b.clone().scatter_(1, b, d)
```

```
tensor([[3, 0, 1, 2],
        [0, 1, 3, 2],
        [2, 3, 0, 1]])
```

**Comment by ZacBi** [comment]
> The argsort output seems to be correct.
> 
> Please check the docs of [argsort](https://pytorch.org/docs/stable/torch.html?highlight=argsort#torch.argsort): "Returns the indices that sort a tensor along a given dimension in ascending order by value"
> 
> ```
> >>> order = a.argsort()
> >>> a = torch.randn(3,3)
> >>> b = a.argsort()
> >>> a[0][b[0]]
> tensor([-1.1886, -1.0116, -0.7388])
> >>> a[1][b[1]]
> tensor([-1.7961,  0.0980,  2.3254])
> ```

Sorry I misunderstand the doc of torch.argsort(), I thought the element of tensor returned should be its order along the given dimension.
