### ISSUE TITLE
 Cannot generate a safe runtime search path for target torch because files in some  directories may conflict with libraries in implicit directories

### ISSUE THREAD

**Issue by marcoippolito** [pytorch/pytorch#25015]
In Ubuntu 18.04.02 Desktop I'm trying to install pytorch from source:

    marco@marco-U36SG:~$ git clone --recursive https://github.com/pytorch/pytorch
    Cloning into 'pytorch'...
    remote: Enumerating objects: 35, done.
    remote: Counting objects: 100% (35/35), done.

    marco@marco-U36SG:~/pytorch$ git submodule sync
    marco@marco-U36SG:~/pytorch$ git submodule sync
    Synchronizing submodule url for 'third_party/FP16'
    Synchronizing submodule url for 'third_party/FXdiv'

When installing :

    Cannot generate a safe runtime search path for target torch because files in some 
    directories may conflict with libraries in implicit directories

I attached here the complete logging file: 
[pytorchInstallationUbuntuDesktopIssue.txt](https://github.com/pytorch/pytorch/files/3528919/pytorchInstallationUbuntuDesktopIssue.txt)

    marco@marco-U36SG:~$ conda -V
    conda 4.7.11

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by ifedan** [comment]
Please try git submodule update --init --recursive.

**Comment by ifedan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by marcoippolito** [comment]
Thanks Igor @ifedan for the suggestion. 
Unfortunately after applying git submodule update --init --recursive the problem remains:
I attach the file with the full-log: 
[pytorchInstallationIssueUbuntu18.04DesktopFullLog.txt](https://github.com/pytorch/pytorch/files/3533166/pytorchInstallationIssueUbuntu18.04DesktopFullLog.txt)

Looking forward to your kind help.
Marco

**Comment by marcoippolito** [comment]
@ifedan  on 23rd of August I also asked for help in discuss pytorch: https://discuss.pytorch.org/t/building-cxx-object-third-party-ideep-mkl-dnn-src-cmakefiles-mkldnn-dir-cpu-cpu-barrier-cpp-o-ninja-build-stopped-subcommand-failed/54112 but got no answer
