### ISSUE TITLE
Very high CPU utilization with pin_memory=True and num_workers > 0

### ISSUE THREAD

**Issue by rwightman** [pytorch/pytorch#25010]
## 🐛 Bug
There seems to be an issue with CPU utilization when using a DataLoader with pin_memory=True and num_workers > 0. 

I revisited some old code that had `pin_memory=True` and two workers that weren't doing all that much. It pinned all of my CPU cores at or near 100%, with 40-50% of the usage in the kernel.  I've had performance issues with pinned memory in the past, but never to this level. Indeed, I cannot reproduce the issue going back to some older environments with 0.4 or 1.0.1. But on 3 machines w/ PyTorch 1.1 and 1.2 I can easily reproduce by running the MNIST main.py from the current examples master.

If I set either num_workers=0 or pin_memory=False the issue goes away and I'm left with the expected one core and change of usage for MNIST (or two cores and change for my original case). 

## To Reproduce

1. Run `main.py` from the MNIST example on master pytorch/examples repository.

## Expected behavior

For MNIST, with 1 worker I expect roughly 1 core's worth of CPU utilization plus some overhead. It consumes 50-100% of all cores on systems with 8-14 physical (16-28 logical) cores. A large % of the CPU usage is in the kernel, appears to be spinning/yielding, possibly due to contention. 

## Environment

I've reproduced on 3 machines.

 - PyTorch Version (e.g., 1.0): 1.1 and 1.2 (no issue on an older 1.0.1 and 0.4.1 environment on one of the machines)
 - OS (e.g., Linux): two Ubuntu 18.04 machines, one Ubuntu 16.04 machine
 - How you installed PyTorch (`conda`, `pip`, source): All conda installs
 - Python version: 3.7.3 and 3.6.8
 - CUDA/cuDNN version: Cuda 10 and CUDNN 7.5.1 and 7.6.2
 - GPU models and configuration: dual Titan RTX one one machine, dual Titan Xp and 1080Ti on other two
 - Any other relevant information:

## Additional context
I've seen at least one very likely, and other potential threads in discussion forum that are likely this issue. 

This one has an htop screenshot from me, and another user:
https://discuss.pytorch.org/t/cpu-usage-extremely-high/52172/5

cc @SsnL

**Comment by rwightman** [comment]
I ran quick kernel trace and observed very different behaviours when pin_memory=True vs False with 1 worker in both cases.

For the `pin_memory=True` case, the Python processes spend a lot of time rapidly repeating a pattern where they get scheduled then quickly yield, they do this across all of the CPU cores, see below. In the case where `pin_memory=False` each PID gets a much longer slice of time in the trace before switching to another one (as you'd hope). 

```
          python-30542 [015] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30531 [002] d... 711388.846101: schedule <-sys_sched_yield
          python-30543 [010] d... 711388.846101: schedule <-sys_sched_yield
          python-30529 [003] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30539 [007] d... 711388.846101: update_min_vruntime <-update_curr
          python-30538 [008] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30537 [004] d... 711388.846101: pick_next_entity <-pick_next_task_fair
          python-30534 [012] d... 711388.846101: update_min_vruntime <-update_curr
          python-30535 [005] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30536 [013] d... 711388.846101: check_cfs_rq_runtime <-pick_next_task_fair
          python-30540 [009] d... 711388.846101: update_rq_clock <-__schedule
          python-30542 [015] d... 711388.846101: __calc_delta <-update_curr
          python-30531 [002] d... 711388.846101: rcu_note_context_switch <-__schedule
          python-30543 [010] d... 711388.846101: rcu_note_context_switch <-__schedule
          python-30529 [003] d... 711388.846101: update_min_vruntime <-update_curr
          python-30539 [007] d... 711388.846101: check_cfs_rq_runtime <-pick_next_task_fair
          python-30538 [008] d... 711388.846101: __calc_delta <-update_curr
          python-30537 [004] d... 711388.846101: clear_buddies <-pick_next_entity
          python-30534 [012] d... 711388.846101: cpuacct_charge <-update_curr
          python-30535 [005] d... 711388.846101: __calc_delta <-update_curr
          python-30536 [013] d... 711388.846101: pick_next_entity <-pick_next_task_fair
          python-30529 [003] d... 711388.846101: cpuacct_charge <-update_curr
          python-30542 [015] d... 711388.846101: update_min_vruntime <-update_curr
          python-30531 [002] d... 711388.846101: _raw_spin_lock <-__schedule
          python-30543 [010] d... 711388.846101: _raw_spin_lock <-__schedule
          python-30540 [009] d... 711388.846101: pick_next_task_fair <-__schedule
          python-30539 [007] d... 711388.846101: pick_next_entity <-pick_next_task_fair
          python-30538 [008] d... 711388.846101: update_min_vruntime <-update_curr
          python-30537 [004] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30534 [012] d... 711388.846101: check_cfs_rq_runtime <-pick_next_task_fair
          python-30535 [005] d... 711388.846101: update_min_vruntime <-update_curr
          python-30536 [013] d... 711388.846101: clear_buddies <-pick_next_entity
          python-30529 [003] d... 711388.846101: check_cfs_rq_runtime <-pick_next_task_fair
          python-30542 [015] d... 711388.846101: check_cfs_rq_runtime <-pick_next_task_fair
          python-30531 [002] d... 711388.846101: update_rq_clock <-__schedule
          python-30543 [010] d... 711388.846101: update_rq_clock <-__schedule
          python-30540 [009] d... 711388.846101: update_curr <-pick_next_task_fair
          python-30533 [006] .... 711388.846101: sys_sched_yield <-entry_SYSCALL_64_fastpath
          python-30539 [007] d... 711388.846101: clear_buddies <-pick_next_entity
          python-30538 [008] d... 711388.846102: check_cfs_rq_runtime <-pick_next_task_fair
          python-30537 [004] d... 711388.846102: update_min_vruntime <-update_curr
          python-30534 [012] d... 711388.846102: pick_next_entity <-pick_next_task_fair
          python-30535 [005] d... 711388.846102: check_cfs_rq_runtime <-pick_next_task_fair
          python-30529 [003] d... 711388.846102: pick_next_entity <-pick_next_task_fair
          python-30542 [015] d... 711388.846102: pick_next_entity <-pick_next_task_fair
          python-30540 [009] d... 711388.846102: __calc_delta <-update_curr
          python-30533 [006] d... 711388.846102: _raw_spin_lock <-sys_sched_yield
          python-30531 [002] d... 711388.846102: pick_next_task_fair <-__schedule
          python-30538 [008] d... 711388.846102: pick_next_entity <-pick_next_task_fair
          python-30543 [010] d... 711388.846102: pick_next_task_fair <-__schedule
          python-30539 [007] d... 711388.846102: update_curr <-pick_next_task_fair
          python-30537 [004] d... 711388.846102: cpuacct_charge <-update_curr
          python-30534 [012] d... 711388.846102: clear_buddies <-pick_next_entity
          python-30529 [003] d... 711388.846102: clear_buddies <-pick_next_entity
          python-30535 [005] d... 711388.846102: pick_next_entity <-pick_next_task_fair
          python-30542 [015] d... 711388.846102: clear_buddies <-pick_next_entity
          python-30540 [009] d... 711388.846102: update_min_vruntime <-update_curr
          python-30533 [006] d... 711388.846102: yield_task_fair <-sys_sched_yield
          python-30531 [002] d... 711388.846102: update_curr <-pick_next_task_fair
          python-30538 [008] d... 711388.846102: clear_buddies <-pick_next_entity
          python-30539 [007] d... 711388.846102: update_min_vruntime <-update_curr
          python-30543 [010] d... 711388.846102: update_curr <-pick_next_task_fair
          python-30537 [004] d... 711388.846102: check_cfs_rq_runtime <-pick_next_task_fair
          python-30535 [005] d... 711388.846102: clear_buddies <-pick_next_entity
          python-30542 [015] d... 711388.846102: update_curr <-pick_next_task_fair
          python-30540 [009] d... 711388.846102: check_cfs_rq_runtime <-pick_next_task_fair
          python-30533 [006] d... 711388.846102: schedule <-sys_sched_yield
          python-30531 [002] d... 711388.846102: __calc_delta <-update_curr
```

**Comment by SsnL** [comment]
I propose to `torch.set_num_threads(1)` in memory pinning thread, just like what we do for the workers.

**Comment by rwightman** [comment]
@ssnl The workers are separate processes, pin_memory a thread. Doesn't set_num_threads impact the whole process?  To not impact the parallalization threads of the rest of the process you'd have to restrict the pin memory loop to non parallalized ops no?

**Comment by SsnL** [comment]
The setting is thread local.

**Comment by rwightman** [comment]
Cool, I tried the change locally on two envs, setting the num_threads at the beginning of _pin_memory_loop. It fixed the massive CPU use in both cases. I haven't tried it with any more meaningful workloads besides the MNIST demo yet.

**Comment by colesbury** [comment]
@SsnL so is this because the pinned memory copy is parallelized in 1.2 (and wasn't prior?)

**Comment by SsnL** [comment]
@colesbury I think this is because of the `copy_` indeed. But I am not sure if it was not parallelized before 1.2.

**Comment by rwightman** [comment]
@colesbury @SsnL I flipped through my environments and ran the MNIST example in each. I repro'd in 1.1 and 1.2, could not repro in 1.0.x or 0.4 as mentioned.
