### ISSUE TITLE
torch.nn.ReLU forced inplace=True

### ISSUE THREAD

**Issue by hjalmarlucius** [pytorch/pytorch#25028]
## 🐛 Bug

`torch.nn.ReLU.__init__` rejects `inplace=True/False` parameter.

## To Reproduce

`act = torch.nn.ReLU(10, inplace=False)`

yields:
`TypeError: __init__() got multiple values for argument 'inplace'`

## Environment

Running pytorch 1.2.0 on Ubuntu Linux 18.04 and CUDA 10, installed via conda.

cc @SsnL

**Comment by ifedan** [comment]
Based on docs https://pytorch.org/docs/stable/nn.html?highlight=relu#torch.nn.ReLU it supports only one argument 'inplace'.
