### ISSUE TITLE
Could PyTorch edit the elements of the neural network layer?

### ISSUE THREAD

**Issue by dengshanseation** [pytorch/pytorch#25090]
Hi, could PyTorch construct a network that is all artificial? That is, it's not the invoking nn.linear() and so on, may be the network with the layers are all artificial? (may define the layers with a Class)
I've searched the documents of PyTorch, but I've not gotten an idea.
Looking forward for your help. Thanks.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by dengshanseation** [comment]
> please use https://discuss.pytorch.org for questions

Thanks.
