### ISSUE TITLE
CI warnings for quantization tests

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#25096]
A lot of warnings like the following are triggered by the quantization tests:
```
Aug 23 03:42:17 /var/lib/jenkins/.local/lib/python3.6/site-packages/hypothesis/extra/numpy.py:147: HypothesisDeprecationWarning: Generated array element -1.3191335874537915e-19 from one_of(floats(min_value=0.0, max_value=1.5069810385055557e-19), floats(min_value=0.0, max_value=1.5069810385055557e-19).map(neg)) cannot be represented as dtype dtype('float32') - instead it becomes -1.3191336e-19 (type <class 'numpy.float32'>).  Consider using a more precise strategy, for example passing the `width` argument to `floats()`, as this will be an error in a future version.
Aug 23 03:42:17   since="2019-07-28",
```

It makes the log too long and difficult to nagivate.

E.g. log: https://circleci.com/gh/pytorch/pytorch/2554740?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jamesr66a** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/26853

Please let me know if you see any remaining warnings
