### ISSUE TITLE
[feature req. for torch.inverse] optional return for indicating that whether input is not invertable or not.

### ISSUE THREAD

**Issue by 7starsea** [pytorch/pytorch#25095]
## 🚀 Feature

```
torch.inverse(input) -> (output, indicator)
dimension of input: (*, n, n),
dimension of (output, indicator): (*, n, n), (*,)
```
output is the inverse of input, and indicator indicate whether the input is invertable or not.
If (some of) the input is not invertable, do not incur a RuntimeError.

## Motivation
torch.inverse will incur a RuntimeError when (some of) input is not invertable. If we want to invert a batch of matrices, a single singular matrix will ruin the whole inverting task.

## Additional context

cc @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @SsnL

**Comment by vishwakftw** [comment]
In CPU, this should be possible since we execute getrf / getri sequentially.

I'm not sure about CUDA, because both getrf and getri call batched kernels.

**Comment by 7starsea** [comment]
Thanks for your response. I then guess we need to dive into the cuda kernel of getrf and getri.
