### ISSUE TITLE
Source build again takes default CUDNN over custom specified.

### ISSUE THREAD

**Issue by igrekun** [pytorch/pytorch#2510]
Currently setup.py script appends -I/usr/local/cuda before custom CUDNN_LIB_DIR and more importantly, CUDNN_INCLUDE_DIR.

This causes pytorch to use default cudnn if there is one in /usr/local/cuda.

Simply swapping `if WITH_CUDNN:` block to go before `if WITH_CUDA:` block in setup.py solves this issue.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/2947
