### ISSUE TITLE
MultiheadAttention / transformer with batch first 

### ISSUE THREAD

**Issue by d5555** [pytorch/pytorch#25100]
Is it possible to add option batch_first = True for MultiheadAttention and  transformer modules like it is done for RNN  ? 
Batch  x Sequence x Embedding
I find it more understandable and intuitive when batch_first is true

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by malmaud** [comment]
@izdeby This seems like a reasonable feature request to me, and AFAIK feature requests are fair game for github issues.

**Comment by venkatasg** [comment]
I think this should definitely be an option, since batch_first is an option with other modules.

**Comment by albanD** [comment]
Closing as duplicate of https://github.com/pytorch/pytorch/issues/43112
We can continue the discussion there !
