### ISSUE TITLE
[RFC] Add new python modules in `torch.nn.quantized` for mobile.

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#25120]
## 🚀 Feature
Request to add python modules for executing quantized models on mobile.
@ljk53 @dreiss 
 
## Motivation
Currently we don't have a way to execute quantized pytorch models on mobile. Mobile has different operator backends for quantized ops (QNNPACK) compared to server side (FBGEMM). This proposal outlines an approach similar to FBGEMM to add support for new mobile specific modules in `torch.nn.quantized` namespace.

## Pitch

In order to execute quantized models on mobile, we can take two approaches - 
* Eager mode + TorchScript - Do calibration in eager mode and collect quantization statistics on FP32 model. Create quantized model which replaces FP32 ops with quantized ops. Call torch.jit.script on the quantized model.
* Graph mode - Quantization pass in graph mode will insert quant, dequant nodes and perform the calibration. Finally it will replace the fp32 ops with the corresponding quantized backend ops. This will generate a torchscript that we can execute on mobile.

Sample change to add a new module -
```
class QNNPackLinear(torch.nn.Module):
   
    _FLOAT_MODULE = nn.Linear

    def __init__(self, in_features, out_features):
        super(QNNPackLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features

        qweight = torch._empty_affine_quantized(
            [out_features, in_features], scale=1, zero_point=0,
            dtype=torch.quint8)
        qbias = torch._empty_affine_quantized(
            [out_features], scale=1, zero_point=0, dtype=torch.qint32)

        #self.register_buffer('out_scale', torch.Tensor([1]))
        #self.register_buffer('out_zero_point', torch.Tensor([0]))
        self.out_scale = 1.0
        self.out_zero_point = 0
        self.set_weight_bias(qweight, qbias)
        self.bias = qbias

    def forward(self, x):
        Y_q = torch.ops.quantized.qnnpack_linear_op(
            x, self._packed_weight,
            self.out_scale,
            self.out_zero_point)
        return Y_q

    @torch.jit.export
    def __getstate__(self):
        return (
            self.in_features,
            self.out_features,
            self.bias,
            self._orig_weight,
            self.out_scale,
            self.out_zero_point
        )

    @torch.jit.export
    def __setstate__(self, state):
        # type: (Tuple[int, int, torch.Tensor, torch.Tensor, float, int]) -> None
        self.in_features = state[0]
        self.out_features = state[1]
        self.bias = state[2]
        self.set_weight_bias(state[3], state[2])
        self.out_scale = state[4]
        self.out_zero_point = state[5]

    def weight(self):
        return self._orig_weight

    def set_weight_bias(self, weight, bias):
        self._orig_weight = weight
        self.bias = bias
        self._packed_weight = torch.ops.quantized.qnnpack_linear_prepack(weight, bias)
```

## Alternatives

Use the graph mode execution to add a quantization pass specific for mobile. This pass will replace the FP32 ops with the quantized counterparts based on the backend. 
Using this approach will mean that we won't be able to support eager mode + torchscript approach to run models on mobile.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by dzhulgakov** [comment]
It seems that the only discrepancy is that fbgemm packs weights separately from biases while qnnpack packs them in one buffer (https://github.com/pytorch/QNNPACK/blob/16fa9b2969f81fa49d1c47454b64a697e467b002/src/qnnpack/pack.h#L27).

Ideally, we'd get to identical API for fbgemm and qnnpack and just have "quantized" APIs ready. One way to do it is to just pack bias inside the same datastructure in fbgemm case. "Weight" for fbgemm is already a magical data structure with additional information, we might as well stick bias into it directly: https://github.com/pytorch/pytorch/blob/bc83ed10fafe3b135658c8a73a52ebbf30430131/aten/src/ATen/native/quantized/cpu/fbgemm_utils.h#L16

Then in either case you'd have a single function `quantized::linear_prepack(Tensor W, Tensor? b) -> Tensor W_prepack`.

Alternative would be to change QNNPACK kernels to keep weight and bias separately (as it probably don't matter that much), but it might be a bit more involved (cc @ajtulloch)

@jamesr66a @dskhudia - do you think changing fbgemm bindings to bundle weight and bias together to match the API is a good idea?

**Comment by soumith** [comment]
to second what Dmytro said, we shouldn't be adding a new `Module` per backend. At runtime, for a particular module, one needs to be able to switch which backend we use.

For example, We dont have nn.Conv2d and nn.CuDNNConv2d, we only have nn.Conv2d, which at runtime will switch to CuDNN or MKLDNN or ATen depending on where things are run.

**Comment by raghuramank100** [comment]
Closing, nn.quantized serves both server and mobile backends
