### ISSUE TITLE
Get rid of null Variables

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#2513]
Currently, when a user passes in None where a Variable is represented, this is represented C++ level as a nullptr Variable shared pointer. This is irritating and adds a lot of extra checks / special cases where we shouldn't need them. A better strategy is to represented these as Variables, whose tensor data are an undefined tensor.

CC @apaszke

**Comment by colesbury** [comment]
That doesn't sound right. Null pointers should be pulled up to the top of the data structure, not pushed lower.
