### ISSUE TITLE
C++ FrontEnd model.forward() crash when loading model with torch::jit::script::Module model = read_model(model_path);

### ISSUE THREAD

**Issue by zirid** [pytorch/pytorch#25142]
## 🐛 Bug

auto outputs = model.forward(inputs).toTensor(); crashes  when loading  the model with  torch::jit::script::Module model = read_model(model_path);

Checked versions : Prebuilt Libtorch C++ stable 1.2 & nightly both CPU and cuda versions.

## To Reproduce

1. Build simple  cnn using torch::nn::SequentialImpl  ( at this point  model.forward (sometensor) works fine). 
2. Save The model using `torch::save(network, "SomePath\\model.pt");` 
3. Load the model using : ` torch::jit::script::Module model = read_model(model_path);`

(tried also `model = torch::jit::load(model_path);` )
4. Run inference with 

 `std::vector<torch::jit::IValue> inputs;
  inputs.push_back(Sometensor);
  torch::Tensor output = model.forward(inputs).toTensor();` 

## Expected behavior

Load model from file and run inference or return error code. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):  Prebuilt Libtorch C++ stable 1.2 & nightly both CPU and cuda versions.
 - OS (e.g., Linux):    Windows 10
 - How you installed PyTorch (`conda`, `pip`, source):  Prebuilt stable Libtorch 1.2
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @suo

**Comment by ShahriarSS** [comment]
I don't think that ```torch::jit``` should be involved here. Saving and loading a network is as simple as ```torch::save(network, "<path>");``` and ```torch::load(network, "<path>");```

**Comment by xsacha** [comment]
Sounds like you saved the model as pickle and then try to load as jit. It should throw C10::Error complaining about being unable find zip archive as JIT models are saved as a zip file.

**Comment by zirid** [comment]
Hi , @ShahriarSS @xsacha 
Thank you for your quick reply. 
I ended up using  torch::save/torch::load without using jit as you mentioned.
