### ISSUE TITLE
undefined symbol in master

### ISSUE THREAD

**Issue by delijati** [pytorch/pytorch#2514]
When compiling the current master i got a ` undefined symbol` error. I have to compile it by my own as i use a older nvidia card.

Command:
```
ln -s /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib64/
CC=/usr/bin/gcc-4.9 LD_LIBRARY_PATH=torch:/usr/lib/x86_64-linux-gnu/ TORCH_CUDA_ARCH_LIST="2.0 3.0 3.5 5.2 6.0 6.1+PTX" ../env3/bin/python setup.py bdist_wheel
```

Error:
```
Traceback (most recent call last):
  File "train_mnist.py", line 3, in <module>
    import torch
  File "/opt/develop/privat/zuff/env3/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /opt/develop/privat/zuff/env3/lib/python3.5/site-packages/torch/lib/libTHD.so.1: undefined symbol: _ZN4gloo13EnforceNotMetC1EPKciS2_RKSs
```

**Comment by delijati** [comment]
Still getting this error in current master

**Comment by soumith** [comment]
you can compile with `NO_DISTRIBUTED=1 python setup.py install` to avoid this. This might be a consequence of gloo not compiling for pre-3.x cards.

**Comment by delijati** [comment]
Ahh thanks i will try `NO_DISTRIBUTED=1`

**Comment by delijati** [comment]
at least a different error: 
`ImportError: /opt/develop/privat/zuff/env3/lib/python3.5/site-packages/torch/lib/libATen.so.1: undefined symbol: THNN_CudaVolumetricAveragePooling_updateOutput`

**Comment by soumith** [comment]
python setup.py clean;

doing that first should fix this error

**Comment by delijati** [comment]
Thanks for your help it works now
