### ISSUE TITLE
Cannot script modules with conditional module arguments

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#25154]
## Modules with conditional modules  are not scriptable.

When modules are created with arguments that allow for optional modules, i.e a particular module can either exist or be None based on the arguments, scripting does not work when the submodule is None. This is a pattern that is used in torchvision to create resnet models.

The problem is that currently torchscript supports optional Tensor types but not a module type as an argument at: https://pytorch.org/docs/master/jit.html#torchscript-language-reference.

## To Reproduce
```
import torch
import torch.nn as nn

class Bottleneck(nn.Module):

    def __init__(self,  downsample=None):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 1)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.relu(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
  
        return out
```
```
scripted_model = torch.jit.script(Bottleneck(nn.Conv2d(3, 32, 1))) # works
scripted_model = torch.jit.script(Bottleneck()) # Does not work
```
Error message:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-5ae783852af8> in <module>
      1 scripted_model = torch.jit.script(Bottleneck(nn.Conv2d(3, 32, 1)))
----> 2 scripted_model = torch.jit.script(Bottleneck())

/data/users/raghuraman/fbsource/fbcode/buck-out/opt/gen/bento/kernels/bento_kernel_pytorch#link-tree/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1158 
   1159     if isinstance(obj, torch.nn.Module):
-> 1160         return torch.jit.torch.jit._recursive.recursive_script(obj)
   1161 
   1162     qualified_name = _qualified_name(obj)

/data/users/raghuraman/fbsource/fbcode/buck-out/opt/gen/bento/kernels/bento_kernel_pytorch#link-tree/torch/jit/_recursive.py in recursive_script(mod, exclude_methods)
    165     filtered_methods = filter(ignore_overloaded, methods)
    166     stubs = list(map(make_stub, filtered_methods))
--> 167     return copy_to_script_module(mod, overload_stubs + stubs)
    168 
    169 

/data/users/raghuraman/fbsource/fbcode/buck-out/opt/gen/bento/kernels/bento_kernel_pytorch#link-tree/torch/jit/_recursive.py in copy_to_script_module(original, stubs)
     87             setattr(script_module, name, item)
     88 
---> 89     torch.jit._create_methods_from_stubs(script_module, stubs)
     90 
     91     # Now that methods have been compiled, take methods that have been compiled

/data/users/raghuraman/fbsource/fbcode/buck-out/opt/gen/bento/kernels/bento_kernel_pytorch#link-tree/torch/jit/__init__.py in _create_methods_from_stubs(self, stubs)
   1366     rcbs = [m.resolution_callback for m in stubs]
   1367     defaults = [get_default_args(m.original_method) for m in stubs]
-> 1368     self._c._create_methods(self, defs, rcbs, defaults)
   1369 
   1370 # For each user-defined class that subclasses ScriptModule this meta-class,

RuntimeError: 
module has no attribute 'downsample':
at <ipython-input-18-ac9b92db0b71>:19:11
    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.relu(out)

        if self.downsample is not None:
           ~~~~~~~~~~~~~~~ <--- HERE
            identity = self.downsample(x)

        out += identity
  
        return out
```

cc @suo

**Comment by jamesr66a** [comment]
This is getting fixed in torchvision once francisco gets back

**Comment by frischzenger** [comment]
def conv_bn(inp, oup, stride, kernel_size=3, padding=1):
    return nn.Sequential(
        nn.Conv2d(inp, oup, kernel_size, stride, padding, bias=False),
        nn.BatchNorm2d(oup),
        nn.ReLU(inplace=True)
    )


def depth_conv2d(inp, oup, kernel=1, stride=1, pad=0):
    return nn.Sequential(
        nn.Conv2d(inp, inp, kernel_size = kernel, stride = stride, padding=pad, groups=inp),
        nn.ReLU(inplace=True),
        nn.Conv2d(inp, oup, kernel_size=1)
    )


def conv_dw(inp, oup, stride, kernel_size=5, padding=2):
    return nn.Sequential(
        nn.Conv2d(inp, inp, kernel_size, stride, padding, groups=inp, bias=False),
        nn.BatchNorm2d(inp),
        nn.ReLU(inplace=True),
        nn.Conv2d(inp, oup, kernel_size=1, stride=1, padding=0, bias=False),
        nn.BatchNorm2d(oup)
    )


def conv_pw(inp, oup, stride, kernel_size=5, padding=2):
    return nn.Sequential(
        nn.Conv2d(inp, inp, kernel_size, stride, padding, bias=False),
        nn.BatchNorm2d(inp),
        nn.ReLU(inplace=True),
        nn.Conv2d(inp, oup, kernel_size=1, stride=1, padding=0, bias=False),
        nn.BatchNorm2d(oup)
    )


class BlazeBlock(nn.Module):
    def __init__(self, inp, oup, double_oup=None, stride=1, kernel_size=5):
        super(BlazeBlock, self).__init__()
        assert stride in [1, 2] 
        self.stride = stride
        self.inp = inp 
        self.use_pooling = self.stride != 1
        self.shortcut_oup = double_oup or oup
        self.actvation = nn.ReLU(inplace=True)

        if double_oup == None: 
            
            self.conv = nn.Sequential( 
                    conv_dw(inp, oup, stride, kernel_size)
                )
        else:
            self.conv = nn.Sequential(
                    conv_dw(inp, oup, stride, kernel_size),
                    nn.ReLU(inplace=True),
                    conv_pw(oup, double_oup, 1, kernel_size),
                    nn.ReLU(inplace=True)
                )
        
        if self.use_pooling:
            self.shortcut = nn.Sequential(
                nn.MaxPool2d(kernel_size=stride, stride=stride),
                nn.Conv2d(in_channels=inp, out_channels=self.shortcut_oup, kernel_size=1, stride=1),
                nn.BatchNorm2d(self.shortcut_oup),
                nn.ReLU(inplace=True)
            ) 


    def forward(self,x):

        h = self.conv(x)

        if self.use_pooling:
            x = self.shortcut(x)

        z = h + x
        # print(z.size())
        return self.actvation(h + x)
================================================================================
RuntimeError: 
module has no attribute 'shortcut':
at <ipython-input-18-ac9b92db0b71>:19:11
        def forward(self,x):

        h = self.conv(x)

        if self.use_pooling:
           ~~~~~~~~~~~~~~~ <--- HERE
            x = self.shortcut(x)

        z = h + x
        # print(z.size())
        return self.actvation(h + x)
================================================================================
torch1.8.0
torchvision0.9.0

**Comment by frischzenger** [comment]
when use torch.jit.save(model, model_path) meet this error, how to fix it?
