### ISSUE TITLE
libonnx.a not found

### ISSUE THREAD

**Issue by khrlimam** [pytorch/pytorch#25159]
I'm trying to build pytorch for android. When I do follow all the steps written here https://github.com/cedrickchee/pytorch-android, it successfully compiled then I copy all the jnis and cpps libs. When I run `./gradlew assembleDebug` to actually run the project I got an error that saying I have no libcaffe2.a but I red that libcaffe2.a has ben replaced with libtorch.a then I replace the libcaffe2.a on app/CMakesLists.txt with libtorch.a. I then rerun the `gradlew assembleDebug` but now I'm getting new error that saying I got no libonnx.a on my jniLibs folder. I checked and its true, seems like when I compile the pytorch android it didn't successfully generate the libonnx.a for me. How do I get the right libonnx.a file?

Thanks for the help.

**Comment by khrlimam** [comment]
> @khrlimam have you tried building libtorch.so with -DBUILD_SHARED_LIBS=ON? This way you should only need libc10.so and libtorch.so in the install folder.
> And we are still working on libtorch for mobile - the mobile dev flow will be improved.

Great to hear that @ljk53!

I will try as you suggested. Thanks

**Comment by khrlimam** [comment]
Unfortunately I got given error after building android with `-DBUILD_SHARED_LIBS=ON` options

```
../third_party/protobuf/src/google/protobuf/stubs/common.cc:142: error: undefined reference to '__android_log_write'
../third_party/protobuf/src/google/protobuf/stubs/common.cc:150: error: undefined reference to '__android_log_write'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by khrlimam** [comment]
@ljk53 I got the error when I run `pytorch/scripts/build_android.sh -DBUILD_SHARED_LIBS=ON`. I red that issue and tried to export those variables, but unfortunately the error still exists.

**Comment by garymm** [comment]
Given the release of [PyTorch Mobile](https://pytorch.org/mobile/home/) and the age of this issue I'm guessing this is obsolete. Please comment here if this is still a problem.
