### ISSUE TITLE
model.train() will make Class DistributedDataParallel into NoneType

### ISSUE THREAD

**Issue by yangsenius** [pytorch/pytorch#25160]
## To Reproduce

1. `print(model.__class__.__name__) # DistributedDataParallel`
2. `model = model.train()`
3. `print(model.__class__.__name__) # NoneType`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.43
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.0
[pip] numpydoc==0.8.0
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+9232c4a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.2.0           py3.7_cuda9.2.148_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                 py37_cu92    pytorch

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pietern** [comment]
Nice catch, this is indeed not what is supposed to happen.

It won't return a new instance though. Like `nn.Module` it will just return `self`.

**Comment by yangsenius** [comment]
Yes.  `model.train()` will be ok.
`model = model.train()`  was my "pytorch habit".
