### ISSUE TITLE
Add torch.backends.mkldnn.enabled

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25186]
It should be possible to disable mkldnn at runtime using this flag, in analogy to torch.backends.cudnn.enabled.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by gujinghui** [comment]
@ezyang 
Sure. We're following.

**Comment by colesbury** [comment]
This appears to be fixed in #25459 by @jiayisunx
