### ISSUE TITLE
Making more video tutorials available

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#25225]
## 🚀 Feature

5-10 minute long simulations before beginning of every tutorial in PyTorch docs.

## Motivation

just like this simulation
https://www.youtube.com/watch?v=u7x8RXwLKcA
and
https://www.youtube.com/watch?v=auRPXMMHJzc
more simulations before tutorials

**Comment by vainaijr** [comment]
I see YouTube channel for tensorflow, google has channels for every kind of developer, same thing for Python, we have PyCon, PyData, conferences, for cpp, we have CppCon, so I think more videos to PyTorch official channel related to tutorials, tricks, hacks, apps would be good.

**Comment by soumith** [comment]
Thanks for the feedback. We have just started a PyTorch youtube channel, and we are also adding more videos directly into tutorials, headed by @jlin27 @SethHWeidman and others.
