### ISSUE TITLE
Working build script for actual rocm version

### ISSUE THREAD

**Issue by mijosch** [pytorch/pytorch#25232]
## 🚀 Feature
i want to have a build script that works with rocm2.7 on a fresh installed ubuntu, the newer the version the better

## Motivation
at the moment i havent found no way to get pytorch compiled even inside the official docker container. I want to have an easy way to use pytorch with radeon cards. Best would be if the script installs all dependencys needed, also the right rocm version for the build.

## Pitch
clone the repository and run a build script, done.

## Alternatives
a working description at least

## Additional context
none

**Comment by mijosch** [comment]
some news here?

**Comment by jeffdaily** [comment]
Try the following in a fresh ubuntu 20.04 docker environment, for example.  Installs latest available ROCm and PyTorch tip of tree.

```
docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --network=host --ipc=host --shm-size=32g --group-add video
# or if you're just developing and not concerned, you can substitute device and security with --privileged
docker run -it --privileged --network=host --ipc=host --shm-size=32g --group-add video ubuntu:20.04
```

Inside docker:

```
apt update
apt install wget build-essential git cmake gpg-agent kmod python3 python3-pip python3-opencv python 
wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ xenial main' | tee /etc/apt/sources.list.d/rocm.list
apt update
apt install rocm-dev rocm-utils rocm-libs rccl
cd ~
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python3 tools/amd_build/build_amd.py
USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 MAX_JOBS=$(nproc) python3 setup.py install --user
```

You can skip the step of building pytorch yourself and install a nightly wheel, but keep the ROCm package install steps for now.

```
# wheel support added in ROCm 3.7. Pick the corresponding ROCm version in the URL.
pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/rocm3.9/torch_nightly.html
```
