### ISSUE TITLE
problem with mkldnn and march=native

### ISSUE THREAD

**Issue by branfosj** [pytorch/pytorch#25242]
## 🐛 Bug

The mkldnn multiplication goes wrong when compiled with `-march=native` and the tensors are sufficiently large (>=1024 items) on both Haswell and Cascadelake architecture CPUs.

## To Reproduce

1. Build PyTorch with `-march=native`
1. Run the test case below. This test case is a simplification of https://github.com/pytorch/pytorch/blob/v1.2.0/test/test_mkldnn.py#L227 (`common_utils.py` and `expecttest.py` are as per the v1.2.0 branch).

```python
import torch
import unittest
from common_utils import TestCase

class TestMkldnn(TestCase):
    def test_mul(self):
        size = 1024
        x = torch.randn(size, dtype=torch.float32)
        mx = x.to_mkldnn()
        self.assertEqual((x * x), (mx * mx).to_dense())

if __name__ == '__main__':
    unittest.main()
```

Failure is:
```
======================================================================
FAIL: test_mul (__main__.TestMkldnn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mul.py", line 13, in test_mul
    self.assertEqual((x * y), (mx * my).to_dense())
  File "/rds/bear-apps/devel/2019a/branfosj-eb-4/src/easybuild-easyconfigs/easybuild/easyconfigs/p/PyTorch/common_utils.py", line 676, in assertEqual
    assertTensorsEqual(x, y)
  File "/rds/bear-apps/devel/2019a/branfosj-eb-4/src/easybuild-easyconfigs/easybuild/easyconfigs/p/PyTorch/common_utils.py", line 656, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(6.6931e+34, dtype=torch.float32) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```

Further testing:
1. The test case passes if `size = 1023`
1. It is adding `-march=native` that causes the problem - removing that from the CFLAGS / CXXFLAGS and all is fine.
1. Adding debug printing of `x`, `mx`, `x * x`, `mx * mx`, and `(mx * mx).to_dense()` shows clearly that the problem occurs at the `mx * mx` stage:

```
tensor([-0.1117, -0.4966,  0.1631,  ..., -1.6426, -1.0094, -0.3527],
       dtype=torch.float32)
tensor([-0.1117, -0.4966,  0.1631,  ..., -1.6426, -1.0094, -0.3527],
       dtype=torch.float32, layout=torch._mkldnn)
tensor([0.0125, 0.2466, 0.0266,  ..., 2.6983, 1.0190, 0.1244],
       dtype=torch.float32)
tensor([-2.5416e-29,  1.5521e-41, -2.5416e-29,  ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00], dtype=torch.float32, layout=torch._mkldnn)
tensor([-2.5416e-29,  1.5521e-41, -2.5416e-29,  ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00], dtype=torch.float32)
```

## Expected behavior

That the multiplication should be done correctly.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 8.2.0
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.2.0
[conda] Could not collect

PyTorch built from source
Build command: PYTORCH_BUILD_VERSION=1.2.0 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_GLOO_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON  /rds/bear-apps/devel/2019a/branfosj-eb-4/EL7/EL7-haswell/software/Python/3.7.2-GCCcore-8.2.0/bin/python setup.py build
CFLAGS and CXXFLAGS are set to -O2 -ftree-vectorize -march=native -fno-math-errno

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by gujinghui** [comment]
Thanks for report. We're following this.

**Comment by XiaobingSuper** [comment]
We solved it and will pull a request to it. Thanks!

**Comment by soumith** [comment]
@Jianhui-Li okay that's great. will this be in the next submodule update?

**Comment by XiaobingSuper** [comment]
@soumith , yes, we will update ideep soon.

**Comment by XiaobingSuper** [comment]
@branfosj, we solve this problem in #25757,  thanks!

**Comment by XiaobingSuper** [comment]
@branfosj, #25757 has been merged,  you can try it. Thanks!

**Comment by gchanan** [comment]
@pbelevich is going to verify this is fixed for the release.

**Comment by pbelevich** [comment]
I built pytorch master with `LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_GFLAGS=ON USE_GLOG=ON CFLAGS="-O2 -ftree-vectorize -march=native -fno-math-errno" CXXFLAGS="-O2 -ftree-vectorize -march=native -fno-math-errno" BUILD_TEST=0 python setup.py develop` and 
```def test_mul(self):
        size = 1024
        x = torch.randn(size, dtype=torch.float32)
        mx = x.to_mkldnn()
        self.assertEqual((x * x), (mx * mx).to_dense())``` run successfully
