### ISSUE TITLE
[ONNX] [jit] ONNX export for ScriptModule including for loop and mixed types cannot be loaded in onnxruntime

### ISSUE THREAD

**Issue by julioasotodv** [pytorch/pytorch#25251]
## 🐛 Bug

It looks like if we want to export a ScriptModule to onnx and the module includes both:

1. A for loop
2. More than one tensor data type (eg. float and long)

The exported ONNX file cannot be loaded with the ONNX runtime.

## To Reproduce

```python
import torch

class DummyModule(torch.nn.Module):
    def __init__(self):
        super(DummyModule, self).__init__()
        
    def forward(self, x, y):
        for i in range(y.size(0)):
            x = x + i
        return x

# Instantiation and scripting
model_scripted = torch.jit.script(DummyModule())
dummy_input_one = torch.Tensor([1,2,3]).float()
dummy_input_two = torch.Tensor([4,5,6]).long()

# Check if the forward pass works:
output = model_scripted(dummy_input_one, dummy_input_two)
print(output)

# Export to onnx:
torch.onnx.export(model_scripted, 
                  (dummy_input_one, dummy_input_two), 
                  'loop.onnx', 
                  verbose=True,
                  input_names=['input_data', 'input_data_2'], 
                  example_outputs=output
                 )

# Load the model in onnx runtime:
import onnxruntime as rt

sess = rt.InferenceSession("loop.onnx")
```

The last line fails with:
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-145-2a18677141bc> in <module>
      1 import numpy as np
      2 import onnxruntime as rt
----> 3 sess = rt.InferenceSession("loop.onnx")
      4 
      5 input_ = sess.get_inputs()[0].name

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options)
     27 
     28         if isinstance(path_or_bytes, str):
---> 29             self._sess.load_model(path_or_bytes)
     30         elif isinstance(path_or_bytes, bytes):
     31             self._sess.read_bytes(path_or_bytes)

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from loop.onnx failed:[TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int64) in node ().
```

It turns out that this only occurs if the module uses more than one tensor data type. For instance: if everything inside the module (including arguments received by the forward pass) were `torch.long`, the exported onnx file is read just fine.

This means that in the example above, if we change the definition of `dummy_input_one` to:
```
dummy_input_one = torch.Tensor([1,2,3]).long()
```

Everything works as expected.

## Expected behavior

The ONNX exporter should allow `for` loops and mixed tensor types.

## Environment

Pytorch `1.2.0` (Mac and Linux)

## Additional context
A fix on this issue could allow iterating over `torch.float` tensors, which is essential for some architectures (such as custom attention modules).

cc @suo

**Comment by julioasotodv** [comment]
@sidazhang It does: the `onnx::Loop` operation exists. Take a look at https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting; the example listed there shows the usage.

**Comment by dashesy** [comment]
If it is exported already to ONNX, you should open an issue [here](https://github.com/Microsoft/onnxruntime/issues).

**Comment by julioasotodv** [comment]
@dashesy I'm not sure about that... I believe that the ONNX export is incorrect, and therefore causing the issue; as I cannot load it with Caffe2 either...

```python
import onnx
import caffe2.python.onnx.backend as backend

model = onnx.load('loop.onnx')

model_runtime = backend.prepare(model)
```
Fails with:
```python
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-6-301709621567> in <module>
      4 model = onnx.load('loop.onnx')
      5 
----> 6 model_runtime = backend.prepare(model)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/caffe2/python/onnx/backend.py in prepare(cls, model, device, raw_values_dict, **kwargs)
    690         '''
    691         if not kwargs.pop('no_check_UNSAFE', False):
--> 692             super(Caffe2Backend, cls).prepare(model, device, **kwargs)
    693         opset_version = None
    694         for imp in model.opset_import:

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/onnx/backend/base.py in prepare(cls, model, device, **kwargs)
     72                 ):  # type: (...) -> Optional[BackendRep]
     73         # TODO Remove Optional from return type
---> 74         onnx.checker.check_model(model)
     75         return None
     76 

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/onnx/checker.py in check_model(model)
     84         C.check_model_path(model)
     85     else:
---> 86         C.check_model(model.SerializeToString())
     87 
     88 

ValidationError: Field 'shape' of type is required but missing.

==> Context: Bad node spec: input: "5" input: "6" input: "input_data" output: "7" op_type: "Loop" attribute { name: "body" g { node { input: "x.6" input: "i.1" output: "11" op_type: "Add" } node { input: "2" output: "12" op_type: "Cast" attribute { name: "to" i: 9 type: INT } } name: "torch-jit-export1" input { name: "i.1" type { tensor_type { elem_type: 7 shape { } } } } input { name: "cond" type { tensor_type { elem_type: 9 } } } input { name: "x.6" } output { name: "12" } output { name: "11" } } type: GRAPH }
```

So I believe that the jit is exporting a malformed ONNX model file.

**Comment by julioasotodv** [comment]
Ok it turns out that the ONNX runtime raises the exception given that the operation:

```python
x = x + i
```
Where `x` is a float32 tensor and `i` is an int64 (long) tensor is valid in Pytorch (and apparently TorchScript), but it isn't in ONNX; where the `onnx:Add` operation has to be between two tensors of the exact same datatype.

I'm not sure whether an exception should be raised in the `export()` function in order to be able to spot these kind of issues prior to exporting to ONNX.

**Comment by bpstark** [comment]
This should not raise an exception on export, instead this should be handled in the same manner that adding a tensor of 2 different types is handled when not inside a loop. The issue here is that when inside a loop, the scripting graph strips away some of the type information. As such the ONNX implicit type cast checker is unable to recognize that there should be an implicit cast occurring since the types are of Tensor rather than FloatTensor or IntTensor. This issue with the scripting graph generation is a known issue, and is something we would like to address (though there is no definitive timeline as of now to do so). Once the scripting graph is able to maintain type information, the loop Add should be handled in the same way as any other Add in which the detector will throw a warning when it detects an implicit cast, and use the type of the first tensor to cast the second tensor.

**Comment by julioasotodv** [comment]
@bpstark thank you for the detailed answer!

**Comment by garymm** [comment]
This is working with PyTorch 1.10 and ONNX Runtime 1.10.
