### ISSUE TITLE
How to preserve backward grad_fn after distributed 'all_gather' operations

### ISSUE THREAD

**Issue by JoyHuYY1412** [pytorch/pytorch#25284]
I am trying to implement model parallelism in a distributed data parallel setting.

Let’s say I have a tensor output in each process and a number of operations have been performed on it (in each process independently). The tensor has a .grad_fn attached to it. Now I want to perform an all_gather to create a list [tensor_1, tensor_2...tensor_n]. But all the tensors in the list will lose the grad_fn property. 

My expectation is to be able to backward() using concated tensor list in each process i through tensor_i.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
