### ISSUE TITLE
Fatal error: TH/TH.h: No such file or directory when compiling from source

### ISSUE THREAD

**Issue by gsp2014** [pytorch/pytorch#2528]
I write "-e git://github.com/pytorch/pytorch.git#egg=pytorch" in pytorch_requirment.txt, and install pytorch as follows and get fatal error:

[xxx]$ pip install -r pytorch_requirment.txt 
Obtaining pytorch from git+git://github.com/pytorch/pytorch.git#egg=pytorch (from -r pytorch_requirment.txt (line 1))
  Updating ./src/pytorch clone
  Running setup.py (path:/home/xxx/src/pytorch/setup.py) egg_info for package pytorch produced metadata for project name torch. Fix your #egg=pytorch fragments.
Requirement already satisfied: pyyaml in ./anaconda2/lib/python2.7/site-packages (from torch->-r pytorch_requirment.txt (line 1))
Requirement already satisfied: numpy in ./anaconda2/lib/python2.7/site-packages (from torch->-r pytorch_requirment.txt (line 1))
Installing collected packages: torch
  Found existing installation: torch 0.2.0.post1
    Uninstalling torch-0.2.0.post1:
      Successfully uninstalled torch-0.2.0.post1
  Running setup.py develop for torch
    Complete output from command /home/xxx/anaconda2/bin/python -c "import setuptools, tokenize;__file__='/home/xxx/src/pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    -- Building version 0.2.0+5d09fcd
    running egg_info
    writing requirements to torch.egg-info/requires.txt
    writing torch.egg-info/PKG-INFO
    writing top-level names to torch.egg-info/top_level.txt
    writing dependency_links to torch.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'torch.egg-info/SOURCES.txt'
    writing manifest file 'torch.egg-info/SOURCES.txt'
    running build_ext
    -- Building with NumPy bindings
    -- Not using cuDNN
    -- Not using CUDA
    -- Not using NCCL
    -- Building with distributed package
    building 'torch._C' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/PtrWrapper.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/PtrWrapper.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/Generator.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/Generator.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/Exceptions.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/Exceptions.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/DynamicTypes.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/DynamicTypes.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/utils.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/utils.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/utils/object_ptr.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/utils/object_ptr.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/autograd/init.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/autograd/init.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/allocators.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/allocators.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    In file included from torch/csrc/Exceptions.cpp:3:0:
    torch/csrc/THP.h:6:19: fatal error: TH/TH.h: No such file or directory
     #include <TH/TH.h>
                       ^
    compilation terminated.
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/xxx/src/pytorch -I/home/xxx/src/pytorch/torch/csrc -I/home/xxx/src/pytorch/torch/lib/tmp_install/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/TH -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THPP -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THNN -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/ATen -I/home/xxx/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/xxx/src/pytorch/torch/lib/tmp_install/include/THD -I/home/xxx/anaconda2/include/python2.7 -c torch/csrc/autograd/function.cpp -o build/temp.linux-x86_64-2.7/torch/csrc/autograd/function.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -DWITH_NUMPY -DWITH_DISTRIBUTED
    error: command 'gcc' failed with exit status 1
    In file included from torch/csrc/autograd/init.cpp:3:0:
    /home/xxx/src/pytorch/torch/csrc/THP.h:6:19: fatal error: TH/TH.h: No such file or directory
     #include <TH/TH.h>
                       ^
    compilation terminated.
    torch/csrc/Generator.cpp:5:19: fatal error: TH/TH.h: No such file or directory
     #include <TH/TH.h>
                       ^
    compilation terminated.
    In file included from torch/csrc/DynamicTypes.cpp:1:0:
    torch/csrc/DynamicTypes.h:8:23: fatal error: ATen/ATen.h: No such file or directory
     #include <ATen/ATen.h>
                           ^
    compilation terminated.
    Exception in thread Thread-7 (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/home/xxx/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      File "/home/xxx/anaconda2/lib/python2.7/threading.py", line 754, in run
      File "/home/xxx/anaconda2/lib/python2.7/multiprocessing/pool.py", line 108, in worker
    <type 'exceptions.TypeError'>: 'NoneType' object is not callable
    In file included from torch/csrc/utils.cpp:8:0:
    torch/csrc/THP.h:6:19: fatal error: TH/TH.h: No such file or directory
     #include <TH/TH.h>
                       ^
    compilation terminated.
    In file included from torch/csrc/allocators.cpp:3:0:
    torch/csrc/THP.h:6:19: fatal error: TH/TH.h: No such file or directory
     #include <TH/TH.h>
                       ^
    compilation terminated.
    In file included from torch/csrc/autograd/function.cpp:1:0:
    torch/csrc/autograd/function.h:12:23: fatal error: ATen/ATen.h: No such file or directory
     #include <ATen/ATen.h>
                           ^
    compilation terminated.
    
    ----------------------------------------
  Rolling back uninstall of torch
Command "/home/xxx/anaconda2/bin/python -c "import setuptools, tokenize;__file__='/home/xxx/src/pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/xxx/src/pytorch/

**Comment by soumith** [comment]
> I write "-e git://github.com/pytorch/pytorch.git#egg=pytorch" in pytorch_requirment.txt, and install pytorch as follows and get fatal error:


We have not given such instructions anywhere. If you want to install from source, follow:
https://github.com/pytorch/pytorch#from-source

**Comment by gsp2014** [comment]
I followed the instructions "install from source", but it didn't work. So I turn to install with git, as described above. The errors when installed from source are as follows:

`[xxx pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297]$ python setup.py install
fatal: Not a git repository
running install
running build_deps
Traceback (most recent call last):
File "setup.py", line 494, in 
install_requires=['pyyaml', 'numpy'],
File "/home/xxx/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 203, in run
self.run_command('build_deps')
File "/home/xxx/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 91, in run
from tools.nnwrap import generate_wrappers as generate_nn_wrappers
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/nnwrap/init.py", line 1, in 
from .generate_wrappers import generate_wrappers, wrap_function, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/nnwrap/generate_wrappers.py", line 4, in 
from ..cwrap import cwrap
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/init.py", line 1, in 
from .cwrap import cwrap
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/cwrap.py", line 5, in 
from .plugins import ArgcountChecker, OptionalArguments, ArgumentReferences, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/plugins/init.py", line 425, in 
from .OptionalArguments import OptionalArguments
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/plugins/OptionalArguments.py", line 5, in 
from ...shared import cwrap_common
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/shared/init.py", line 2, in 
from .cwrap_common import set_declaration_defaults, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/shared/cwrap_common.py", line 1
../../torch/lib/ATen/common_with_cwrap.py
^
SyntaxError: invalid syntax`

I also follow http://pytorch.org/ to install from binaries via Conda or pip wheels and all fail. Can you give me some advice? Thank you very much.

**Comment by gsp2014** [comment]
I followed the instructions "install from source", but it didn't work. So I turn to install with git, as described above. The errors when installed from source are as follows:

[xxx pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297]$ python setup.py install
fatal: Not a git repository
running install
running build_deps
Traceback (most recent call last):
File "setup.py", line 494, in 
install_requires=['pyyaml', 'numpy'],
File "/home/xxx/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 203, in run
self.run_command('build_deps')
File "/home/xxx/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
self.distribution.run_command(command)
File "/home/xxx/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 91, in run
from tools.nnwrap import generate_wrappers as generate_nn_wrappers
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/nnwrap/init.py", line 1, in 
from .generate_wrappers import generate_wrappers, wrap_function, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/nnwrap/generate_wrappers.py", line 4, in 
from ..cwrap import cwrap
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/init.py", line 1, in 
from .cwrap import cwrap
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/cwrap.py", line 5, in 
from .plugins import ArgcountChecker, OptionalArguments, ArgumentReferences, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/plugins/init.py", line 425, in 
from .OptionalArguments import OptionalArguments
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/cwrap/plugins/OptionalArguments.py", line 5, in 
from ...shared import cwrap_common
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/shared/init.py", line 2, in 
from .cwrap_common import set_declaration_defaults, 
File "/home/xxx/python_libpack/pytorch-1199e3d4964ca5b167517c127094d66d5b1b4297/tools/shared/cwrap_common.py", line 1
../../torch/lib/ATen/common_with_cwrap.py
^
SyntaxError: invalid syntax

I also follow http://pytorch.org/ to install from binaries via Conda or pip wheels and all fail. Can you give me some advice? Thank you very much.

**Comment by ArEsKay3** [comment]
You need to clone with symlinks. Try adding -c core.symlinks=true to your git clone command.
