### ISSUE TITLE
[C++] `modulelist.h` include is missing in `modules.h`

### ISSUE THREAD

**Issue by chenzhekl** [pytorch/pytorch#25293]
## To Reproduce

`modulelist.h` include is missing in `modules.h`, which makes `ModuleList` inaccessible through `torch/torch.h`

## Environment

 - PyTorch Version (e.g., 1.0): Nightly
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): 
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment]
cc: @yf225

**Comment by ShahriarSS** [comment]
@soumith I'll fix this.
