### ISSUE TITLE
Critical problem in Torch.add function

### ISSUE THREAD

**Issue by hamidfarhid** [pytorch/pytorch#2529]
We have found critical issue in torch.add(x,y) function. It seems broadcasting feature does not work well for special case:

>>import torch
>>x = torch.Tensor(1, 16, 32, 64, 64)
>>y = torch.Tensor(16, 1, 32 ,64 ,64)
>>z = torch.add(x,y)

The size of z should be [1, 16, 32, 64, 64] but it is [16, 16, 32, 64, 64]? WHY?
Whatever number instead of 1 works well? Any idea?

**Comment by soumith** [comment]
Hamid,

please read about the semantics of broadcasting. This is correct behavior.
http://pytorch.org/docs/master/notes/broadcasting.html

**Comment by hamidfarhid** [comment]
@soumith Thank you, Soumith. But in this special case, how can I get [1, 16, 32, 64, 64] as output size?

**Comment by gchanan** [comment]
you have to define how you want those leading dimensions to be added, but one way to get that output size would be to do something like:
```
x+y.squeeze(1)
```

**Comment by hamidfarhid** [comment]
@gchanan Thank you :)
