### ISSUE TITLE
C++ API - Can't copy tensor or model to GPU 

### ISSUE THREAD

**Issue by DerHaddy** [pytorch/pytorch#25298]
Hi all,

i recently built PyTorch in Visual Studio 2017 C++. I have installed CUDA 10.0 and cudNN v7.6.2. At the building process there were no problem. Now i am defining my device type:

```
torch::DeviceType device_type;
if (torch::cuda::is_available()) {
    std::cout << "CUDA available! Training on GPU." << std::endl;
    device_type = torch::kCUDA;
   } else {
   std::cout << "Training on CPU." << std::endl;
   device_type = torch::kCPU;
}

```
This works and my device_type is set to torch::kCUDA.

Now i want to copy a Tensor to the device:

```
torch::Device device(device_type);
Tensor a = torch::rand({ 1,5 });
a.to(device);
```

Then I get following Error:

Unhandled exception at 0x00007FF854E3A388 in AlexNet.exe: Microsoft C++ exception: c10::Error at memory location 0x00000066FBCFD780.

It appears at TensorMethods.h at: line (246-249)

```
inline Tensor & Tensor::copy_(const Tensor & src, bool non_blocking) {
    static auto table = globalATenDispatch().getOpTable("aten::copy_(Tensor(a!) self, Tensor src, bool non_blocking=False) -> Tensor(a!)");
    return table->getOp<Tensor & (Tensor &, const Tensor &, bool)>(tensorTypeIdToBackend(type_id()), is_variable())(*this, src, non_blocking);
}
```
On CPU everything works fine.

Can someone help me or tell what's the issue?

Thanks

cc @peterjc123

**Comment by soumith** [comment]
cc: @yf225 @peterjc123

**Comment by peterjc123** [comment]
Yes, this is actually a known issue and you could use the following code as a workground.
```
Tensor a = torch::rand({ 1,5 }, at::kCUDA);
```
If you want to help us with solving the problem, could you please build it in the debug configuration (including PyTorch/LibTorch) and post the stacktrace here?

**Comment by peterjc123** [comment]
> It appears at TensorMethods.h at: line (246-249)
> 
> ```
> inline Tensor & Tensor::copy_(const Tensor & src, bool non_blocking) {
>     static auto table = globalATenDispatch().getOpTable("aten::copy_(Tensor(a!) self, Tensor src, bool non_blocking=False) -> Tensor(a!)");
>     return table->getOp<Tensor & (Tensor &, const Tensor &, bool)>(tensorTypeIdToBackend(type_id()), is_variable())(*this, src, non_blocking);
> }
> ```

Well, this seems to be another initialization problem just like https://github.com/pytorch/pytorch/issues/22681.
