### ISSUE TITLE
libtorch(c++) Adam and RMSProp optimizer memory leaks in CUDA 

### ISSUE THREAD

**Issue by beichen2012** [pytorch/pytorch#25303]
## 🐛 Bug

libtorch(c++) Adam and RMSProp optimizer memory leaks in CUDA 

## To Reproduce
libtorch1.2, cuda10,win10, vs2015, win64
please refer to the test code:  https://github.com/beichen2012/pytorchAdamMemLeak
open gpu-z to inspect the GPU Memory...

## Expected behavior

1、there will be no memory leaks in CPU
2、 the leaks num is : 2M every time...

## Environment
【I use libtorch c++ download from the official-website, below is the python environment】
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Home China
GCC version: Could not collect
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.0.102
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 431.60
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      203  
[conda] mkl_fft                   1.0.12           py37h14836fe_0  
[conda] mkl_random                1.0.2            py37h343c172_0  
[conda] pytorch                   1.2.0           py3.7_cuda100_cudnn7_1    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch

cc @ezyang @gchanan @zou3519 @peterjc123

**Comment by soumith** [comment]
cc: @yf225 you should take a look

**Comment by yf225** [comment]
I wasn't able to reproduce this with libtorch 1.2 + Ubuntu 16.04 + CUDA 9.2. (The peak GPU memory usage stays at 515MiB.)

@peterjc123 Could you check if this is a Windows-specific problem?

**Comment by peterjc123** [comment]
Could not reproduce locally on Windows either. The GPU memory won't exceed 409M (6%).

**Comment by beichen2012** [comment]
> Could not reproduce locally on Windows either. The GPU memory usage won't exceed 409M (6%).

It should be wait a moment,
just 1 or 2 minutes;
the gpu memory would be rise。
I have tested in win10 and win7。

**Comment by peterjc123** [comment]
I'm already running it for more than 10 mins.

**Comment by peterjc123** [comment]
Would you please try building it with CUDA 10.0 and VS 2017 14.11 installed?

**Comment by beichen2012** [comment]
![image](https://user-images.githubusercontent.com/10824490/63995757-359d1f80-cb2c-11e9-919f-2b7b9365350e.png)

**Comment by peterjc123** [comment]
I know, but without reproducing it on my own machine, how can I know what's wrong there.

**Comment by beichen2012** [comment]
> Would you please try building it with CUDA 10.0 and VS 2017 14.11 installed?

Was the binaries provided by the official website compiled with vs2017 ?

**Comment by peterjc123** [comment]
Yes, we use VS 2017 14.11 toolset. And from your log, it seems that you don't have CUDA 10.0 installed.

**Comment by peterjc123** [comment]
![image](https://user-images.githubusercontent.com/9998726/63996516-79912400-cb2e-11e9-8904-f0ca4d3d0716.png)

**Comment by beichen2012** [comment]
> Yes, we use VS 2017 14.11 toolset. And from your log, it seems that you don't have CUDA 10.0 installed.

yes, CUDA9.0 is installed。 but the binaries will link to the downloaded cuda libs with is cuda10.0

OK, I will download the vs2017 14.11 and test again.

**Comment by beichen2012** [comment]
> Yes, we use VS 2017 14.11 toolset. And from your log, it seems that you don't have CUDA 10.0 installed.

thanks a lot.

**Comment by beichen2012** [comment]
emmm, I have installed vs2017 14.11 ,but the leaks is still there. .. 
![image](https://user-images.githubusercontent.com/10824490/63999507-30dd6900-cb36-11e9-81f6-73e0b96566b4.png)

**Comment by peterjc123** [comment]
So you are using the debug configuration? I didn't see that from your post.

**Comment by beichen2012** [comment]
> So you are using the debug configuration? I didn't see that from your post.

both debug and release. leaks the same .

**Comment by peterjc123** [comment]
Still can't reproduce on my side. The debug build actually crashes here. Did you copy all the DLLs of LibTorch to where your executable locates?

**Comment by beichen2012** [comment]
> Still can't reproduce on my side. The debug build actually crashes here. Did you copy all the DLLs of LibTorch to where your executable locates?

yes .... But, actually, I set the environmet:
the exe will first searching the libtorch's dlls
![image](https://user-images.githubusercontent.com/10824490/64001738-0fcb4700-cb3b-11e9-81ec-f4cba0ea0fe1.png)

**Comment by peterjc123** [comment]
Would you please run the executable generated by me for a longer time? (e.g. 10 mins - 20 mins)
The executable is here: [train_pytorch.zip](https://github.com/pytorch/pytorch/files/3563454/train_pytorch.zip)

**Comment by peterjc123** [comment]
It that problem doesn't appear anymore, then it may be related to https://github.com/pytorch/pytorch/issues/25535. Please set Windows SDK version to 8.1 and make sure toolset 14.11 is selected. (v141 doesn't necessarily mean 14.11, it actually mean 14.1X). More details could be found in https://github.com/peterjc123/pytorch-scripts/issues/23 and https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/.

**Comment by beichen2012** [comment]
> Would you please run the executable generated by me for a longer time? (e.g. 10 mins - 20 mins)
> The executable is here: [train_pytorch.zip](https://github.com/pytorch/pytorch/files/3563454/train_pytorch.zip)

my pytorch was downloaded from website(version: cuda10, pytorch1.2). and your train_pytorch.exe is different with the libriaries:
![image](https://user-images.githubusercontent.com/10824490/64084124-acb7fb00-cd5a-11e9-8b09-199028dbe4e6.png)

**Comment by beichen2012** [comment]
> It that problem doesn't occur anymore, then it may be related to #25535. Please set Windows SDK version to 8.1 and make sure toolset 14.11 is selected. (v141 doesn't necessarily mean 14.11, it actually mean 14.1X). More details could be found in [peterjc123/pytorch-scripts#23](https://github.com/peterjc123/pytorch-scripts/issues/23) and https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/.

I had changed the sdk verison to 8.1, but nothing changed....
![image](https://user-images.githubusercontent.com/10824490/64084166-146e4600-cd5b-11e9-8049-ada631009828.png)

**Comment by peterjc123** [comment]
That's weird. I downloaded them from pytorch.org, following the path of `Stable, Windows, LibTorch, C++, 10.0`. Could you please check the `build_hash` file in the LibTorch folder, which should be `8554416a199c4cec01c60c7015d8301d2bb39b64`?

**Comment by peterjc123** [comment]
About your second post:
Please read the **following** carefully.
v141 doesn't necessarily mean 14.11, it actually only means that you are using VS 2017. More details could be found in peterjc123/pytorch-scripts#23 and https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/.

**Comment by beichen2012** [comment]
> That's weird. I downloaded them from pytorch.org, following the path of `Stable, Windows, LibTorch, C++, 10.0`. Could you please check the `build_hash` file in the LibTorch folder, which should be `8554416a199c4cec01c60c7015d8301d2bb39b64`? The md5 checksum of `libtorch.zip` could be calculated through `certutil -hashfile filename MD5`, which should be `bb f2 2e f1 48 62 d8 9d 2f 06 95 47 da 2f 09 91`. Are you sure it selected the `torch.dll` in the expected folder in Dependency Walker?

the content of file build_hash is diffence.
My content is: 
`142c973f4179e768164cd578951489e89021b29c
`
I download the libtorch(pytorch1.2 stable cuda10, c++) in 2019-08-21 and the  torch.dll timestamp is:
![image](https://user-images.githubusercontent.com/10824490/64088803-c450ad00-cd75-11e9-8475-c4c2a1815a9a.png)

I will re-download the library from official-website and have a try.

**Comment by beichen2012** [comment]
@peterjc123 Thanks a lot. it turns out that libtorch's build hash was not equal...

the problem solved by:
1, bought a new computer 
2, installed cuda10 and cudnn7.6.2;
3, downloaded libtorch from official website and  check build_hash to be the same; 

but in debug mode , a new question occurs....
same to : https://github.com/pytorch/pytorch/issues/22681#issuecomment-527179141
