### ISSUE TITLE
add instructions to install older versions

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#2531]
Adding a note on the PyTorch page and the README on installing past versions would be useful, especially given the pip/conda/different OS complications

**Comment by greydanus** [comment]
Temporary/hacky workaround: to access previous wheels (ie PyTorch 0.12.1), use internet archive and look at the july source html of the pytorch.org website:

view-source:https://web.archive.org/web/20170716143645/http://pytorch.org/

**Comment by soumith** [comment]
now there's a link to older versions on http://pytorch.org

**Comment by pietrofusco** [comment]
Hi everyone,
I was wondering if there's a way to download older (0.4.1 for example) pytorch using git from cmd in Windows 7.

Thanks in advance
Pietro
