### ISSUE TITLE
torch.Tensor([True]) returns different result than torch.tensor([True])

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#25316]
**Actual**:
```
>>> torch.tensor([True])
tensor([1.])
```

**Expected**:
```
>>> torch.tensor([True])
tensor([True])
```

**Comment by andreaskoepf** [comment]
@izdeby in your example you used the lower-case `torch.tensor()` method. This does already now produce a `BoolTensor`.

If you write `torch.Tensor([True])` or `torch.Tensor([1])` ... it will invoke the ctor of the default tensor type ( (by default `FloatTensor`) in both cases even though a list of boolean or an integer values is passed. The default tensor type can be set by `torch.set_default_tensor_type()`. To explicitly select the type you can use the corresponding tensor class, e.g. `torch.BoolTensor([True])`.

Only the `torch.tensor()` (lower case 't') factory method that does tensor-type deduction.

**Comment by soumith** [comment]
@andreaskoepf for all intents, `torch.Tensor` is considered a legacy constructor.

@izdeby are you going to fix this, or is it meant to go to a general queue? if you plan to fix it, assign yourself.

**Comment by andreaskoepf** [comment]
(@izdeby sry, I was not aware to respond to a core dev, I am still catching up...)

I looked at [legacy_tensor_ctor()](https://github.com/pytorch/pytorch/blob/91db62a8bb80675df7c652096d5050cae0e27a3e/torch/csrc/utils/tensor_new.cpp#L415) and [tensor_ctor()](https://github.com/pytorch/pytorch/blob/91db62a8bb80675df7c652096d5050cae0e27a3e/torch/csrc/utils/tensor_new.cpp#L557). I am not convinced that there is a need for a fix and type-inference should be added to the legacy Tensor ctors, e.g. for me it would feel strange if this would result in `isinstance(torch.BoolTensor([1.23]), torch.FloatTensor) == True` or `isinstance(torch.Tensor([True]), torch.Tensor) == false`.

Do you guys see a benefit that would arise from enabling type-inference in the legacy-ctors? Especially if their use is strictly discouraged anyway - why change them?

**Comment by izdeby** [comment]
Closing as fixed.

**Comment by izdeby** [comment]
> Do you guys see a benefit that would arise from enabling type-inference in the legacy-ctors? Especially if their use is strictly discouraged anyway - why change them?

I dont think we gonna do it for now.
