### ISSUE TITLE
polygamma undocumented

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#25347]
## 📚 Documentation

polygamma appears undocumented

```
>>> import torch
>>> torch.polygamma
<built-in method polygamma of type object at 0x7f3dc98fc8a0>
>>> help(torch.polygamma)
Help on built-in function polygamma:

polygamma(...)
```

Yes [the docs](https://pytorch.org/docs/master/search.html?q=polygamma&check_keywords=yes&area=default) don't seem to mention it.

It's also not in our [docs file](https://github.com/pytorch/pytorch/blob/687aa781dfafca0e182560806cc0437007911493/torch/_tensor_docs.py).

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by soumith** [comment]
original PR that added them was https://github.com/pytorch/pytorch/pull/4399

cc: @jlin27 to see if you are interested in helping fix this

**Comment by mbalayil** [comment]
I would like to work on this issue.
