### ISSUE TITLE
Improving "Extending Pytorch" note

### ISSUE THREAD

**Issue by czhu95** [pytorch/pytorch#2536]
http://pytorch.org/docs/master/notes/extending.html#extending-torch-autograd

In the definition of `Linear.backward()`, which is an example of implementing Linear Function, there are several `self.needs_input_grad` where `self` should have been `ctx`, as `backward` is implemented as a `@staticmethod`.

**Comment by soumith** [comment]
thanks for pointing this out. fixed via https://github.com/pytorch/pytorch/commit/b079469af00d908666d2daefe88548d9c41cb4ff
