### ISSUE TITLE
[ONNX] export torch.jit.script with List[List[int]] input

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25362]
## 🐛 Bug

ONNX cannot export a jit script with List input

## To Reproduce

I have a jit script that accepts some lists

```python
@torch.jit.script
def smt_pred(confs, child, group_offsets,
             threshold, obj,
             height, width, b, a):
    # type: (List[Tensor],List[List[List[int]]],List[int],Tensor,Tensor,int,int,int,int) -> Tuple[Tensor,Tensor,Tensor]

```

When exporting it to ONNX I get the error:

> RuntimeError: Tracer cannot get value trace for type GenericList. The below value could not be materialized as a constant:                                                                                                                                                      > [[[1], [2], [3], [], [], [], [4], [5], [], [] ...

## Expected behavior

Export an use `Loop` and `if` constructs from ONNX

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

It seems `List[Tensor]` is fine but not `List[List[int]]`. Is there any documentation about supported types for ONNX export of torchscript modules?

cc @suo

**Comment by dashesy** [comment]
It seems even though `List[Tensor]` inputs do have a `prim::ListConstruct` support, I cannot index them and thus cannot use the inputs (resulting in `__getitem__` throwing)

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to `torch.onnx.export` and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
