### ISSUE TITLE
Pytorch memory allocation

### ISSUE THREAD

**Issue by MAhmad-nn** [pytorch/pytorch#25379]
How the size in CudaCachingAllocator.cpp  gets calculated?

**Comment by VitalyFedyunin** [comment]
https://github.com/pytorch/pytorch/blob/25d1496d581dcc3e2c0e15c38b5f19455800971f/c10/cuda/CUDACachingAllocator.cpp#L459

**Comment by MAhmad-nn** [comment]
https://github.com/pytorch/pytorch/blob/25d1496d581dcc3e2c0e15c38b5f19455800971f/c10/cuda/CUDACachingAllocator.cpp#L626

Thanks for replying but I want to know about the 'size' , from where it is getting calculated.As I am not able to backtrace it. The function which you told me is using that pre calculated size.

**Comment by VitalyFedyunin** [comment]
size is the tensor size in bytes, which is number of elements multiplied by element size

**Comment by MAhmad-nn** [comment]
Thanks , but I would like to know where they are doing that in sources.
