### ISSUE TITLE
[jit] windows libtorch module cannot be used concurrently

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#25385]
## 🐛 Bug

When loading a torch::jit::script::Module, it seems it is never possible to use the same module in different threads at the same time.

Workarounds I have tried:
`model.to(torch::kCUDA, deviceIndex);`

This has to be called inside the thread where forward is used otherwise I get an error about model being on the wrong device. If I call it in the right thread, I get a CUDA internal error.

```
auto newModel = model.clone();
newModel.to(torch::kCUDA, deviceIndex);
```

Exact same problem. Despite apparently doing a deep copy, it does not like running at the same time as the original model.

`auto newModel = torch::jit::load(modelFile, {torch::kCUDA, deviceIndex});`

This works perfectly fine. I can run both models at the same time.

## To Reproduce

Run the model separately in a thread per device/config.

## Expected behavior

Model clone should create an entirely new model just like torch::jit::load.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.0-pre
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): nightly
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 10/7.5
 - GPU models and configuration: RTX 2060
 - Any other relevant information:

cc @suo @peterjc123

**Comment by iremyux** [comment]
Hi @xsacha , I've tried to reproduce the bug with Python version 3.11.6 and libtorch version 2.0.1.
I've created a simple program with 2 threads and loaded the same model like this : 
`torch::jit::script::Module model = torch::jit::load("model.pt");`
The issue appears to no longer exist. Can you please provide more details, maybe a script to reproduce & debug, if you are still experiencing this problem?

**Comment by xsacha** [comment]
From your description, it sounds like you ran torch::jit::load twice, which was the workaround.

The aim is to use a single loaded module (to reduce load time) rather than do a full load per thread.
So, the bug is that a single module (from torch::jit::load) cannot be used across threads.

**Comment by iremyux** [comment]
Sorry for misunderstanding, yes I did what you explained.
So I modified the code to load the module once and let 2 workers use that single model and the result was the same. It worked fine again, giving the same results.
