### ISSUE TITLE
In  torch::jit::script::Module module = torch::jit::load("xxx.pt"), How to release module?

### ISSUE THREAD

**Issue by ToBigboss** [pytorch/pytorch#25383]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @suo

**Comment by ToBigboss** [comment]
![image](https://user-images.githubusercontent.com/40013733/63927836-18f7dd80-ca81-11e9-8fde-bd2d9ae16fd0.png)

**Comment by ToBigboss** [comment]
![](https://user-images.githubusercontent.com/40013733/63927836-18f7dd80-ca81-11e9-8fde-bd2d9ae16fd0.png)

Whether module needs to be released,   and how to release it.

**Comment by driazati** [comment]
`torch::jit::script::Module` is a value type, you do not need to explicitly release it
