### ISSUE TITLE
Feature Request:🚀 MISH Activation Function

### ISSUE THREAD

**Issue by shbm** [pytorch/pytorch#25395]
https://arxiv.org/ftp/arxiv/papers/1908/1908.08681.pdf
𝑓(𝑥) = 𝑥 ⋅ 𝑡𝑎𝑛ℎ(𝑠𝑜𝑓𝑡𝑝𝑙𝑢𝑠(𝑥)) = 𝑥 ⋅ 𝑡𝑎𝑛ℎ(ln(1 + 𝑒𝑥))

Using this Non-Monotonic Neural Activation Function, the author has shown the best Test Top-1 Accuracy on CIFAR-10 and CIFAR-100

Fast.ai students have also beaten the 5 epoch ImageWoof leaderboard score using the same activation.
https://forums.fast.ai/t/how-we-beat-the-5-epoch-imagewoof-leaderboard-score-some-new-techniques-to-consider/53453

**Comment by VitalyFedyunin** [comment]
cc @soumith

**Comment by soumith** [comment]
Answered here: https://github.com/pytorch/pytorch/issues/25584
