### ISSUE TITLE
torch::RegisterOperators is undocumented

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25396]
I searched for all occurrences of RegisterOperators and there are no occurrences of this string in docs.

**Comment by VitalyFedyunin** [comment]
cc @goldsborough if I'm not mistaken he introduced this functionality

**Comment by Chillee** [comment]
Isn't this the new operator registration API that @smessmer introduced?

**Comment by smessmer** [comment]
The basic functionality is documented [here](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html) but we don't have documentation for the more advanced use cases yet
