### ISSUE TITLE
pack weight and bias to the same struct for fbgemm quantized conv and linear ops

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#25401]
Current FBGEMM implementation packs the weights into a struct for efficient implementation of the actual conv.  However, the bias is not packed and kept as a seperate parameter.

QNNPACK implementation for mobile requires that the bias be packed into a single struct. For unifying API, FBGEMM API for conv and linear needs to pack both weights and biases.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jamesr66a** [comment]
This is completed, correct?
