### ISSUE TITLE
Cannot import torch in python3 but works in python2

### ISSUE THREAD

**Issue by ai559031** [pytorch/pytorch#25407]
I am using Mac and jupyter notebook(anaconda).

From the PyTorch website, I've tried to install PyTorch by:

`conda install pytorch torchvision -c pytorch`

and

` pip3 install torch torchvision`

When I import torch in jupyter notebook, the error shows:

`ModuleNotFoundError: No module named 'torch'`

However, in the terminal, if I enter python3 environment by:` $ python3`, then `import torch`, there is no error.

Then I tried: conda list pytorch in the terminal, and found:

```
# Name                    Version                   Build  Channel
pytorch                   1.2.0                   py2.7_0    pytorch
```
So I finally notice in the jupyter notebook, if I use python2 and import torch, there would be no error. But I don't know how to install pytorch in python3 environment? I've already followed the PyTorch website` pip3 install torch torchvision,` but it still not works.

**Comment by VitalyFedyunin** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by alexbarnadas** [comment]
@VitalyFedyunin Shouldn't have you said that in a private message and erase the issue? At least you could've posted a link with the answer... What's the point in maintaining this issue closed? I need answers! Not people telling other people with questions to go somewhere else to make their questions. Stop making me lose my time please.

**Comment by rachhele** [comment]
@alexbarnadas Hi! Did you manage to solve this issue? 🙂 I cannot find any solution.

**Comment by rachhele** [comment]
I solved the problem by running the following:
`python3 -m pip`
Which returned me:
`/usr/local/opt/python@3.9/bin/python3.9 -m pip <command> [options]`
Thus, I installed torch by running:
`/usr/local/opt/python@3.9/bin/python3.9 -m pip install torch`

I hope that this will work for you as well 🙂
