### ISSUE TITLE
Incorrect output from a `ScriptModule` using a dictionary

### ISSUE THREAD

**Issue by VivekPanyam** [pytorch/pytorch#25443]
## 🐛 Bug

In a `ScriptModule`, modifying a tensor and returning it as part of a dictionary undoes the modification.

## To Reproduce

```python
import torch

class SomeModel(torch.jit.ScriptModule):
    def __init__(self):
        super(SomeModel, self).__init__()

    @torch.jit.script_method
    def forward(self):
        # type: () -> Dict[str, torch.Tensor]

        # Zeros
        out = torch.zeros(5)

        # Set the value of an element
        out[2] = 5

        # Wrap the tensor in a dict and return
        return {
            "output": out # Changing this to `out.clone()` fixes it
        }

if __name__ == '__main__':
    model = SomeModel()

    # tensor([0., 0., 0., 0., 0.])
    print model()['output']
```

## Expected behavior

The output should be `tensor([0., 0., 5., 0., 0.])`.

Any of the following changes cause the model to return the correct output:
- Switching `out` to `out.clone()` in the dictionary
- Returning the tensor directly (without a dictionary)
- Switching to `torch.nn.Module`

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Debian GNU/Linux 10 (buster)
GCC version: (Debian 8.3.0-6) 8.3.0
CMake version: Could not collect

Python version: 2.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] torch==1.2.0
[conda] Could not collect

cc @suo

**Comment by sukuya** [comment]
Issue reproducible even for Python3.6 with CUDA10.1 and PyTorch 1.3.0.dev20190828

**Comment by suo** [comment]
Thanks for the report, and sorry for the inconvenience. This was fixed by https://github.com/pytorch/pytorch/pull/25425, which landed today in master. I confirm the repro prints:
```
tensor([0., 0., 5., 0., 0.])
```
for me.

**Comment by sukuya** [comment]
Yeah, it works now.
