### ISSUE TITLE
Linux CUDA9.0 Failed to Download .whl file with Corresponding url

### ISSUE THREAD

**Issue by tso-si** [pytorch/pytorch#25448]
I want to install pytorch in Linux with CUDA90. However, I found that the url provided by pytorch.org is a blank page and thus I have no access to download .whl file. The url is below:
https://download.pytorch.org/whl/cu90/torch_stable.html

**Comment by SsnL** [comment]
You don't need to go to the webpage. Just run the pip command.

**Comment by tso-si** [comment]
> You don't need to go to the webpage. Just run the pip command.

**Comment by tso-si** [comment]
> You don't need to go to the webpage. Just run the pip command.

Thank you for your reply. Problem solved.
