### ISSUE TITLE
graphic capacity exception when load same model twice in python use mutilthreading 

### ISSUE THREAD

**Issue by jesen8** [pytorch/pytorch#25452]
## To Reproduce
when i first to load the rnn model once, use `nvidia-smi` tool can watch current python thread used 611M capacity and inference one image only need about 0.2s , but when i load the same model twice by mutilthreading because i want to start two threads to save time,and i find it's only use 663M, and both inference one image need about 0.5s. I don't understand why the speed is so slow and why is the graphics card occupied twice?

below is loading once
![image](https://user-images.githubusercontent.com/33971685/63994516-6dee2f00-cb27-11e9-80cc-c55b9054a49e.png)

below is loading twice into two object
![image](https://user-images.githubusercontent.com/33971685/63994539-83635900-cb27-11e9-96c8-5402c405134e.png)

## Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): torch-1.0.0-cp36-cp36m-linux_x86_64.whl
 - Build command you used (if compiling from source):
 - Python version: 3.6.4
 - CUDA/cuDNN version: cuda 10.0, cudnn 7.4.1.5
 - GPU models and configuration:
 - Any other relevant information:

can you help me ? thanks,please,

**Comment by yf225** [comment]
My understanding is that PyTorch CUDA program uses the entire GPU by default, so running two programs in parallel won't necessarily increase the throughput.

cc. @mrshenli Do you know what's a good way to get numbers on GPU utilization?

**Comment by mrshenli** [comment]
I agree with @yf225's comments. 

IIUC, there will be one CUDA context per **process**, which might consume ~500MB GPU memory. When using two threads, they will share the same context, and hence the total GPU memory consumption will not be doubled. 

As there is only one GPU, the two threads will share that GPU, and also compete for the Global Interpreter Lock.

Regarding profiling tool, [nvprof](https://devblogs.nvidia.com/cuda-pro-tip-nvprof-your-handy-universal-gpu-profiler/) can help. It will show you a chronologically view of when the GPU is busy.

**Comment by jesen8** [comment]
yes,i agree with you, @mrshenli , @yf225 ,but in my situation,i don't want that the two threads share the same context  on same GPU , so,is threre any solution for me? does mutilprocess is ok?

**Comment by mrshenli** [comment]
@jesen8 Yes, multi-process would create a new context per process, checkout [this](https://pytorch.org/docs/stable/notes/multiprocessing.html).

If you prefer multi-threads, you can try use different streams in different threads, checkout [this](https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams). This could help to overlap device <-> host communication with GPU computation.
