### ISSUE TITLE
type annotation for torch.nn.functional is missing

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#25454]
It was missing for me but I fix it locally by adding the following line

```from . import functional as functional```

to the following file

https://github.com/pytorch/pytorch/blob/master/torch/nn/__init__.pyi

cc @ezyang

**Comment by ezyang** [comment]
@yaroslavvb Thank you! Can you open a PR for this?

**Comment by yaroslavvb** [comment]
https://github.com/pytorch/pytorch/pull/25456 
TIL this kind of PR can be done through github in-browser editor
