### ISSUE TITLE
multinomial function defaults different for Tensor and Variable

### ISSUE THREAD

**Issue by cpdurham** [pytorch/pytorch#2546]
Hi,

'num_samples' in multinomial for Variable defaults to 1 and 'num_samples' multinomial for Tensor requires an argument. Threw me off for a bit. I'm not sure if this has to be the case for some architectural reason. Making it known just in case.

Thanks!

**Comment by zou3519** [comment]
As of Pytorch 0.4 Variables and Tensors are the same thing (and num_samples does not default to anything, [it has to be provided](https://pytorch.org/docs/master/torch.html?highlight=multinomial#torch.multinomial))
