### ISSUE TITLE
Build instructions clarification

### ISSUE THREAD

**Issue by hxtk** [pytorch/pytorch#25464]
## Issue description

[The instructions on the "Start Locally" page](https://pytorch.org/get-started/locally/#linux-from-source) seem to indicate Cuda 8.0 is supported here:

```sh
# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 # or magma-cuda90 if CUDA 9
```

However, when I run the commands specified, I get the following output from `python setup.py install`:

```
-- Caffe2: CUDA detected: 8.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
CMake Error at cmake/public/cuda.cmake:42 (message):
  PyTorch requires CUDA 9.0 and above.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:808 (include)
  CMakeLists.txt:311 (include)
```

Unless I am missing something, it appears the documentation has fallen out of sync with the latest build. I would love to be told I am wrong and have simply missed a step somewhere, but if Cuda 8.0 is truly no longer supported then, in my opinion, the instructions should be updated to reflect that.

## System Info

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Tesla C2075
Nvidia driver version: 390.87
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[conda] blas                      1.0                         mkl  
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0
```

Additional note: [The instructions for installing the build for 8.0](https://pytorch.org/get-started/locally/#cuda-8x) work on my system, but I am unable to move things into GPU and receive a warning that my GPU is not supported. I suspect this is because my card does not support CuDNN and the default installation for Cuda 8.0 uses CuDNN.

**Comment by yf225** [comment]
Yes I think we should update the instructions to reflect that we don't support CUDA 8.0 anymore.

**Comment by xsacha** [comment]
Yes, CUDNN requires a card with CUDA compute 3.0. you could turn off CUDNN but if you want to use anything serious, just get a newer card. A supported one can be found for under $50.
