### ISSUE TITLE
MultiLabelMarginLoss doc string mistake?

### ISSUE THREAD

**Issue by lambda-ai** [pytorch/pytorch#2547]
The docstring for MultiLabelMarginLoss says:

> where i == 0 to x.size(0), j == 0 to y.size(0), y[j] != 0, and i != y[j] for all i and j.

I got weird results padding the label tensor with zeroes, and looking at the torch source:
https://github.com/torch/nn/blob/cd13dead56a74a0fdb3522ba42f12c36a75ba9b0/lib/THNN/generic/MultiLabelMarginCriterion.c#L56
it looks like it should be y[j] >= 0

**Comment by soumith** [comment]
fixed via #2683
