### ISSUE TITLE
Install old version pytorch

### ISSUE THREAD

**Issue by tsuttaket2** [pytorch/pytorch#25479]
## ❓ Help

I am looking for ways to install **pytorch 0.3.1.post2** as it is the version that the paper I read implemented with. However looking through the https://pytorch.org/get-started/previous-versions/ I cannot find such version.

Can you please suggest me how to install such version

Thanks

cc @ezyang

**Comment by yf225** [comment]
Currently we only provide v0.3.1 binaries for CPU on Linux and macOS: https://download.pytorch.org/whl/torch_stable.html. Please consider building PyTorch v0.3.1 from source https://github.com/pytorch/pytorch/tree/v0.3.1, or running the script with newer versions of PyTorch and let us know what errors you encounter.

**Comment by tsuttaket2** [comment]
Thank you
