### ISSUE TITLE
Multiple statically linked instances of libtorch in the same process

### ISSUE THREAD

**Issue by pirros** [pytorch/pytorch#25489]
I have the following scenario:

- I have build static library libtorch.a
- Module A (libA.so) links to libtorch.a and loads a jit script
- Module B (libB.so) also links to libtorch.a and loads another jit script
- Main process dynamically loads modules A and B.

When only one of A or B is linked, everything is fine and the module is working as expected. However, when both A and B are loaded then the modules are not functioning correctly.

Is there any limitation in libtorch that prevents the above scenario?

**Comment by yf225** [comment]
@pirros Can you share with us the error you saw and the code to reproduce it? I believe this scenario should work.

**Comment by xsacha** [comment]
Does the issue only happen with CUDA models? Are the models running at the same time?

**Comment by pirros** [comment]
I didn't post any details in case this was a known issue, here are some:
I have compiled pytorch from version **77c08aa** with the following options:
`-DUSE_OPENMP=OFF -DMKL_THREADING=SEQ -DBLAS=MKL -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_MKLDNN=OFF -DBUILD_SHARED_LIBS=OFF -DUSE_DISTRIBUTED=OFF -DGLIBCXX_USE_CXX11_ABI=0`

An exception is thrown when the second module tries to load the jit model (the first module executes the same code without any issue).
The snippet for loading the model:
```
torch::jit::script::Module model;

try {
	model = torch::jit::load(model_pth);                                      
}                                                                
catch (const c10::Error& e) {                                                                       
	std::cerr<<"c10::Error"<<std::endl;                                              
	std::cerr<<e.what()<<std::endl;            
}
```
The exception caught:
```
c10::Error
Unsupported TypeMeta in ATen: float (please report this error) (typeMetaToScalarType at /home/ubuntu/pytorch/c10/core/ScalarType.h:139)
```

**Comment by pirros** [comment]
This might be specific to the GCC version I'm using (5.4.0). I will investigate this a bit further ...

**Comment by pirros** [comment]
I compiled with GCC 7.4.0 and got the same error.

**Comment by pirros** [comment]
I solved the issue using [version scripts](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html), to hide all symbols apart from the one exported by my modules. 
Thanks
