### ISSUE TITLE
Pytorch version conflict on Colab

### ISSUE THREAD

**Issue by SonaPi** [pytorch/pytorch#25487]
I tried to run PyTorch transfer learning codes on Colab for my project. The codes need Pytorch 0.3.1 and torchvision 0.2.0. I have uninstalled the current version of PyTorch and try to install the needed version via:
!pip3 install torch==0.3.1 torchvision==0.2.0 -f https://download.pytorch.org/whl/torch_stable.html

however, the Cuda did not install. I have searched for several days to find the solution, but unfortunately, I did not get anything useful. Would somebody please help me with that? Thank you so much in advance.

**Comment by ZaydH** [comment]
You may get better responses if you post on the [Pytorch forums](https://discuss.pytorch.org/).

**Comment by SonaPi** [comment]
I've posted on Pytorch too, but I did not get any response.

**Comment by yf225** [comment]
Unfortunately we don't provide CUDA binaries for PyTorch v0.3.1 anymore (we've already had 6 releases since then). The oldest version we currently support is v0.4.1 for CUDA 9.2, or you can build PyTorch v0.3.1 from source (https://github.com/pytorch/pytorch/tree/v0.3.1) if version upgrade is not an option.

**Comment by SonaPi** [comment]
Thank you very much for your reply. 
Would you please tell me how can I install pytorch==0.3.1 torchvision==0.2.0 on windows?

**Comment by ezyang** [comment]
You'll have to build it from source. If you have some preexisting codes, it's probably best to try running them on a Linux system. Esp since you originally said you wanted to run on colab...
