### ISSUE TITLE
[jit] torch.jit.script range() input type raises isInt() when used with int tensor values

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25498]
## 🐛 Bug

I have a `Tensor[int]` passed to `torch.jit.script` when I do

## To Reproduce

Run this script:

```python
@torch.jit.script
def smt_pred(confs, child, child_sizes, group_offsets,
             threshold, obj,
             height, width, b, a):
    # type: (List[Tensor],List[Tensor],List[Tensor],List[int],Tensor,Tensor,int,int,int,int) -> Tuple[Tensor,Tensor,Tensor]
    size = child_sizes[0][1]
    ch = child[0][1]
    for sg in range(size):
        pass
 
```

```text

>RuntimeError: isInt() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/core/ivalue.h:187, please report a bug to PyTorch.                                                                                                                                                       > The above operation failed in interpreter, with the following stack trace:
> for sg in range(size):
> ~~~~~~~~~~~~~~~~~~~~~~...  <--- HERE
```

Even if I change it to 

```python
for sg in range(size.int()):
    pass
```

I get the same assertion about `isInt`

## Expected behavior

`range()` to accept input from a tensor of int

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

I am going to replace that with a while loop and see if that succeeds 

cc @suo

**Comment by driazati** [comment]
Your example works for me on master (after removing the return type ` -> Tuple[Tensor,Tensor,Tensor]`), could you try the nightly PyTorch package?

**Comment by dashesy** [comment]
Is there a way to try it with pip? then I could install it in a virtualenv and try. Or do I need to build it?

**Comment by driazati** [comment]
You can find more info on https://pytorch.org/ with the Quick Start selector (change it to "Preview (Nightly)" at the top), but this should work for your env:

```bash
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html
```

**Comment by dashesy** [comment]
Yes this seems to be fixed in nightly, I close this and re-open if needed
