### ISSUE TITLE
clang-tidy job merges with master which can lead to hard to understand errors

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25492]
All of the Azure jobs appear to run on `/merge` rather than the real commit, so they line up with ROCm behavior but not the rest of the behavior. Ordinarily I'd say this was bad... but it actually was good: in #24937 @pearu had a diff which would have caused a `GEN_TO_SOURCE` failure after merging with master, but the merge-with-master caught it. Except... it was really confusing and hard to tell what was going on, because the error referred to code that literally could not be found in the real copy. There should be some way to make it clearer what's going on here.

cc @ezyang

**Comment by pietern** [comment]
We don't do any automated clang-format today, right? Do you mean clang-tidy?

**Comment by ezyang** [comment]
Yes you're right

**Comment by huydhn** [comment]
Closing this issue as this is not relevant anymore, we now have clang-tidy running as part of lintrunner
