### ISSUE TITLE
`pad_packed_sequence` outdated documentation

### ISSUE THREAD

**Issue by cai-lw** [pytorch/pytorch#25497]
## 📚 Documentation

The documentation for `pad_packed_sequence` says "Batch elements will be ordered decreasingly by their length.", but that's not true if the packed sequence is created with `enforce_sorted=False`. (It was true before the introduction of `enforce_sorted=False`)

Rather, another statement in the documentation "It is an inverse operation to pack_padded_sequence()" is true - the returned tensor is in the same order as it was before being packed.

To fix this, simply remove the sentence "Batch elements will be ordered decreasingly by their length.".

cc @zou3519

**Comment by jbschlosser** [comment]
Closed as addressed in master docs.
