### ISSUE TITLE
[ONNX] export torch.zeros() inside torch.jit.script

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25501]
## 🐛 Bug

Error message is vague as to specify what input exactly is `prim::Constant`. I know `confs` is not constant, it is a list of tensors that are not constant, but `child` is constant `List` of `Tensors`.
While for `child` I may be able to use a list of `int`s instead, I have no option about `confs` because that is the only way to pass more than one tensor to `torch.jit.script` (a fixed number of tensors but I do not want to hard-code them because they could change for different models, and it is a large number). 

## To Reproduce

When trying to export

```python
@torch.jit.script
def smt_pred(confs, child, child_sizes, group_offsets,
             threshold, obj,
             height, width, b, a):
    # type: (List[Tensor],List[Tensor],List[Tensor],List[int],Tensor,Tensor,int,int,int,int) -> Tuple[Tensor,Tensor,Tensor]
```

I get the error 

>  RuntimeError: Unexpected node type: prim::Constant

## Expected behavior

1. Export `List[Tensor]` whether constant or not
2. Specify which input has issue, better error message

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Issue is only with ONNX export, TorchScript is fine

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by dashesy** [comment]
I added some debugging in `utils.py` it seems I get that error when I do this

```python
    pred_idx = torch.zeros(height, width).int()
    pred_conf = torch.zeros(height, width)
    mask_obj = torch.zeros(height, width)
```

So I cannot create tensors in the script and export to ONNX?

It also means just passing `op_name` to `op_fn` function could have provided me with the culprit causing the issue and have a better error message.

**Comment by dashesy** [comment]
I moved the `torch.zeros` to outside the `torch.jit.script` and now it can proceed, halting on another issue. Please include `op_name` in the error message.

**Comment by garymm** [comment]
@dashesy the code to repro seems incomplete. Could you please provide a self-contained repro case?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
