### ISSUE TITLE
[ONNX] Exception when export Loop from torch.jit.script

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25508]
## 🐛 Bug

Please support for-loop with `range`

## To Reproduce

Inside a `torch.jit.script`

```python

    for h in range(height):
        for w in range(width):
            while len(p_stack):

```

```text
--> 588                 new_node = new_op_outputs[0].node() if n.outputsSize() > 1 else new_op_outputs.node()
    589                 for b in n.blocks():
    590                     new_block = new_node.addBlock()

AttributeError: 'tuple' object has no attribute 'node'
```

I printed `new_op_outputs` and it is `()` it is empty

## Expected behavior

To export Loop, or give better error message. Which loop? I have for-loop and while-loop

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Torch script works, but ONNX does not export

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by dashesy** [comment]
By printing the `inputs` I found that this is the for-loop. ONNX does not support for-loop with `range` in torch script it seems. I changed that to while loop.

**Comment by dashesy** [comment]
It also seems the exported module (with while loop) is not correct!

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
