### ISSUE TITLE
[ONNX] Support list operators (len/pop/append) in torch.jit.script

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25510]
## 🐛 Bug

`len` does not work for lists. It seems we can create lists but cannot use `len`

## To Reproduce

Inside a torch.jit.script

```python
p_stack = [0]
while len(p_stack):
    a = p_stack.pop()
```

```text
     90     global _registry
---> 91     return _registry[(domain, version)][opname]

KeyError: u'len'
```
## Expected behavior

Support `len`

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

I am going to keep track of the list length separately as workaround, but have to see if `pop`/`append` is supported

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by dashesy** [comment]
`pop` and `append` are not supported either

**Comment by dashesy** [comment]
Even though I seems I can pass `List[Tensor]` but I cannot get the individual tensors in it:

```text
     90     global _registry
---> 91     return _registry[(domain, version)][opname]

KeyError: u'__getitem_'
```

This is the list input
> (1543 defined in (%1543 : Tensor[] = prim::ListConstruct(%786, %791, %796, %801, %806, %811


Lack of support for `List[Tensor]` is very limiting, even if other values are not supported, this is the only way to overcome lack of `*args` arguments in jit script

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
