### ISSUE TITLE
[RPC] ProcessGroupAgent::enqueueSend and ProcessGroupAgent::enqueueRecv should handle exceptions appropriately

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#25516]
The above mentioned methods don't handle exceptions correctly in the lambda functions run in the threadpool. The exceptions are swallowed by the threadpool and the RPC ends up blocking forever since the future is never satisfied. For `enqueueRecv` we should have a try-catch block around it and return MessageType::Exception. For `enqueuSend`, we can pass the future into the lambda, have a try-catch block, catch an exception and mark the future completed with MessageType::Exception.

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
Another example of why this is needed:

With the changes I added in https://github.com/pytorch/pytorch/pull/31381, a runtime error was being raised in `future->markCompleted` and the program would just hang, which made it a lot harder to debug. Catching the exception in `ProcessGroupAgent::enqueueRecv` would have raised the issue faster, and  could improve the debugging experience.

**Comment by pritamdamania87** [comment]
Looks like we have handled enqueueSend correctly, but still need to address enqueueRecv?

**Comment by rohan-varma** [comment]
@pritamdamania87, @jjlilley had a diff out for this: https://github.com/pytorch/pytorch/pull/31299. I think it's currently blocked on us reaching agreement about testing the change.

**Comment by rohan-varma** [comment]
This is now fixed
