### ISSUE TITLE
mismatched error message for conv2d

### ISSUE THREAD

**Issue by skywalkerytx** [pytorch/pytorch#2552]
## sample code:
    import numpy as np
    import torch as th

    a = th.DoubleTensor(np.random.uniform(size=(502,1,64,100)))
    c = th.autograd.Variable(a).double()
    conv1 = th.nn.Conv2d(in_channels=1,
                             out_channels=123,
                             kernel_size=(2,100),
                             stride=(1,1)
                         )
    b = conv1(c)
    print(b)

And the error message:

    File "/home/nova/PycharmProjects/playground/convex.py", line 12, in <module>
    b = conv1(c)
    File "/usr/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
    File "/usr/lib64/python3.6/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
    File "/usr/lib64/python3.6/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
    RuntimeError: expected Double tensor (got Float tensor)

## how did I fix this:

    c = th.autograd.Variable(a).float()

version of pytorch:

`import torch`
`torch.__version__`
`'0.2.0_1'`

installed through pip, whl was downloaded from pytorch.org

**Comment by vadimkantorov** [comment]
If you want to use `double` inputs, you need to instruct the module to use `double` weights and biases. You can do this by calling `double()` method on your model like this:
`conv1 = th.nn.Conv2d(in_channels=1, out_channels=123, kernel_size=(2,100), stride=(1,1)).double()`
