### ISSUE TITLE
[RPC] ProcessGroupAgent should clean up futures on failures/timeouts

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#25531]
ProcessGroupAgent keeps a map of `futures_` for pending RPCs. In case the destination worker hangs/fails for some reason, these futures will never be marked as complete. We should have some sort of clean up mechanism for these futures where after a timeout, futures which have not been fulfilled are marked completed with an exception indicating they timed out.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by rohan-varma** [comment]
@pritamdamania87, could we do this by attaching a default timeout to each `FutureMessage` object, and periodically poll the map of `futures_` to check if they have timed out, and if so, mark them with an exception?

**Comment by pritamdamania87** [comment]
I think as part of initializing RPC, we should be able to specify a timeout for all RPCs. If this timeout is not specified, we can go with a default that we specify in code. But, yes in general we should have timeout and check for futures that haven't finished in the given timeout window.

**Comment by pietern** [comment]
@rohan-varma @pritamdamania87 I think this can be closed since #29601 and #28392 are merged?

**Comment by rohan-varma** [comment]
Yep, this is now implemented.
