### ISSUE TITLE
[Proposal] Pin Windows SDK and MSVC compiler versions in LibTorch

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#25535]
## Background

According to https://gitlab.kitware.com/cmake/cmake/issues/16202#note_140528, we should always pin windows sdk version and the msvc compiler version when possible. Due to our limited infra and staffing, it is impossible to test every combination of MSVC compiler version and Windows SDK. So the solution is to pin these versions on default and check them during configuration. We can provide flags for users to bypass those checks, but then it's the user's responsibility to ensure that they are working.

Actually, I guess this one is the possible root cause of most LibTorch issues on Windows. We tested them and they passed in CI. This is confirmed to fix some issues like https://github.com/pytorch/pytorch/issues/15757#issuecomment-523074278

## Work to do

- [ ] Raise an error when the user is trying to compile with an unsupported version of the MSVC compiler or Windows SDK or even CUDA
- [ ] Explain that when something goes wrong with the use of different versions of libraries, we won't look into them in high priority
- [ ] Provide a flag for users to skip the version check

## Benefit

Higher quality for LibTorch
More focused on some more important things

## Limitation

Users may need to do more work in environment configuration.

cc @peterjc123 @ezyang @soumith @yf225

**Comment by ezyang** [comment]
SGTM. Let's do it.

**Comment by alinpahontu2912** [comment]
Hey @peterjc123 , could you provide an update on this issue? It looks like [these lines](https://github.com/pytorch/pytorch/blob/c4bf4005d1eafc755f0cdd2379ade0bc3bb3902c/tools/setup_helpers/cmake.py#L145-L151) and this section of the [documentation](https://github.com/pytorch/pytorch/blob/c4bf4005d1eafc755f0cdd2379ade0bc3bb3902c/README.md?plain=1#L313) might have already addressed it.
