### ISSUE TITLE
[RPC] Support send to self in ProcessGroupAgent

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#25532]
Currently RPCs using `ProcessGroupAgent` always go through Gloo, which does not support sending message to self yet. `ProcessGroupAgent` should bypass Gloo if destination is self by directly enqueuing a task into the thread pool.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pritamdamania87** [comment]
What is the use case for this? Is this mostly for testing/debugging purposes?

**Comment by mrshenli** [comment]
@pritamdamania87 Yes, testing/debugging is one use case. Another use case would be creating an `OwnerRRef` as the return value of a local UDF execution, and share the RRef with others. Without `dist.remote` call to self, it has to wait until the UDF finishes and then wrap it with an RRef.

**Comment by pritamdamania87** [comment]
> Another use case would be creating an OwnerRRef as the return value of a local UDF execution, and share the RRef with others. Without dist.remote call to self, it has to wait until the UDF finishes and then wrap it with an RRef.

We shouldn't use `dist.remote` for this, we should just have another API which creates an OwnerRRef locally which the node can share with others.

**Comment by mrshenli** [comment]
> We shouldn't use dist.remote for this, we should just have another API which creates an OwnerRRef locally which the node can share with others.

What about `dist.local`? I think there are two use cases here:

1. If the value is ready, and we could support something like `dist.rref(data)` which returns an `OwnerRRef`.
2. If the value needs to be acquired after running some function, we could provide a new API like `dist.local` (if the name `dist.remote` does not make sense here). The `dist.local` API could insert the task into the same thread pool of the RpcAgent implementation.

**Comment by pritamdamania87** [comment]
> The dist.local API could insert the task into the same thread pool of the RpcAgent implementation.

This would work although it isn't clean since this RRef doesn't have anything to do with RpcAgent. We would have to introduce an asynchronous task execution framework (with its own threadpool) where we can submit these tasks and get futures. Also, each RpcAgent has its own threadpool. One way might be that we have a common threadpool across all RpcAgents where they submit tasks to be executed (basically RequestCallback.processMessage). This common threadpool then can be used for local RRefs as well.

**Comment by mrshenli** [comment]
This is supported now.
