### ISSUE TITLE
Enabling multi-stream per-thread default stream

### ISSUE THREAD

**Issue by Arjunbala** [pytorch/pytorch#25540]
## Issue description
I am trying to use CUDA streams to concurrently execute kernels on different streams (Ref: https://devblogs.nvidia.com/gpu-pro-tip-cuda-7-streams-simplify-concurrency/). Using Nvidia Visual Profiler, I am able to see the kernels launched on their respective streams but they are getting serialized with respect to the default stream(legacy streams behavior). Upon further analysis, this looks to me to be due to the fact the CUDA code needs to be compiled with the --default-stream per-thread in order to avoid this legacy streams behavior. Can you help me with how to configure PyTorch to use this compilation option?

## Code example
    import torch

    def main():
      a = torch.rand(32, 4096, device="cuda:0")
      b = torch.rand(4096, 1024, device="cuda:0")
      c = torch.rand(1024, 10, device="cuda:0")
      d = torch.rand(1024, 512, device="cuda:0")

      s1 = torch.cuda.Stream()
      # wait for sync
      torch.cuda.synchronize()

      # multiply them
      intermediate_output = torch.mm(a,b)
      torch.cuda.synchronize()

      # Now 2 more muls in parallel
      io1 = torch.mm(intermediate_output,c)
      with torch.cuda.stream(s1):
         io2 = torch.mm(intermediate_output,d)
      io3 = torch.mm(intermediate_output,d)
      io4 = torch.mm(intermediate_output,c)

    if __name__ == "__main__":
      main()

In the above code, I expect to see the multiplication that results in io2 be executed concurrent to those multiplications resulting in io1,io3,io4. However, they get falsely serialized and I wish to avoid this for performance reasons.

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 4.8.5-4ubuntu8) 4.8.5
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Tesla P100-PCIE-12GB
Nvidia driver version: 390.129
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==0.4.1
[pip] torchscope==0.1.0
[pip] torchvision==0.2.1
[pip] torchviz==0.0.1
[conda] blas                      1.0                         mkl  
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py36h7b6447c_0  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   0.4.1           py36_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
[conda] torchscope                0.1.0                    pypi_0    pypi
[conda] torchvision               0.2.1                    py36_0  
[conda] torchviz                  0.0.1                    pypi_0    pypi

**Comment by ngimel** [comment]
Additional streams are created in pytorch with cudaStreamNonBlocking attribute, so they don't serialize with respect to the default stream. There are other reasons you won't see overlap in the execution - e.g. if the kernels are too small, the launch overhead (both cuda and CPU overhead introduced by pytorch) will prevent overlap. Alternatively, if each of the kernels is large enough to use all the GPU resources, the second one won't launch until the first one is done.

**Comment by Arjunbala** [comment]
I am not sure if any of those factors are at play. When I write the same program using CUDA, I am able to see the kernels execute concurrently (as visible in Nvidia Visual Profiler)

**Comment by qinhaihong-red** [comment]
@Arjunbala Hi, I met the same problem in LibTorch. Have you found the solution ?

**Comment by leonardo0lyj** [comment]
Same here. https://github.com/pytorch/pytorch/issues/48279

**Comment by rahulgaur104** [comment]
I am trying to run multiple models on a single GPU concurrently using `torch.cuda.Stream()` but can't get the required speedup. I have followed the instructions given [here](https://pytorch.org/docs/stable/notes/cuda.html) for asynchronous execution but to no avail.
