### ISSUE TITLE
Confusion about torch.Tensor

### ISSUE THREAD

**Issue by CappuccinoMocha** [pytorch/pytorch#25546]
First I define a torch Tensor, then I inspect it in Pycharm Debug Window, a odd problem occurs.
![image](https://user-images.githubusercontent.com/50699884/64088346-936f7880-cd73-11e9-89d5-ccea6710c09b.png)
it seems that I can have endless t.T.T.T... , and they have the same value and structure, the same as t.data.data.data, could anyone give me an explansion.
![image](https://user-images.githubusercontent.com/50699884/64088429-fcef8700-cd73-11e9-9f64-094d89e7079e.png)

**Comment by robert780612** [comment]
You are right.
"T" means transpose, so you can have endless transpose operations.

**Comment by pbelevich** [comment]
@robert780612 thank you for the explanation. I'm closing the issue, @CappuccinoMocha feel free to reopen if you have any questions.
