### ISSUE TITLE
The math formula of "kaiming_uniform_" and "kaiming_normal_" are not general enough.

### ISSUE THREAD

**Issue by robert780612** [pytorch/pytorch#25549]
## 📚 Documentation
Hi everyone,
I found that the math formulas of "torch.nn.init.kaiming_uniform_" and "torch.nn.init.kaiming_normal_" are not general enough.
The complete formula for "kaiming_uniform_" should be 

> \text{bound} = \text{gain} * \sqrt{\frac{3}{\text{fan}}}
> where gain is gottn from "calculate_gain"

Am I right?

https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_uniform_
https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_normal_

**Comment by vincentqb** [comment]
Fixed with #25638
