### ISSUE TITLE
ones_like and zero_like do not handle different GPU

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#2554]
```python
x = torch.cuda.FloatTensor(3, 3, device=1)
torch.ones_like(x)
```

```
RuntimeError: arguments are located on different GPUs
```

I'm not sure if `ones_like` should place the result on the current device or on the source's device, but it shouldn't trigger this error.

**Comment by colesbury** [comment]
cc @alykhantejani @apaszke

**Comment by alykhantejani** [comment]
@colesbury for some reason I asserted that both the input and return tensors have to be on the same GPU, which is wrong. Will send a fix today.

**Comment by fmassa** [comment]
This has been merged into master. I think it can be closed?
