### ISSUE TITLE
transforms.Resize(()) 

### ISSUE THREAD

**Issue by machine52vision** [pytorch/pytorch#25577]
## 🐛 Bug
transforms.Resize(()) is based python image library(PIL)，But PIL's resize and opencv's resize results are inconsistent,Experiments show that there are bugs in resize of PIL.

**Comment by pbelevich** [comment]
@machine52vision please provide more information about the issue and steps to reproduce

**Comment by soumith** [comment]
please reopen issue at https://github.com/pytorch/vision
