### ISSUE TITLE
 NVIDIA driver's version  is not match.

### ISSUE THREAD

**Issue by dyl0101** [pytorch/pytorch#25581]
### 
NVIDIA driver's version:384.130
cuda version:10.0
python:3.6
The following error occurred while running the program：
AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

So I want to know how to do next?

**Comment by pbelevich** [comment]
This error message is misleading, because 9000 is actually CUDA version 9.0 which is detected on your system(maybe it's installed after CUDA 10.0?). I suggest you to uninstall/reinstall CUDA to have only one version on your system or to download PyTorch compiled with CUDA 9.0

**Comment by pbelevich** [comment]
I created [an issue](https://github.com/pytorch/pytorch/issues/25590) to fix the error message, but I don't see any other problems in this behavior, that's why I'm closing this issue. Feel free to reopen it if you have any questions.

**Comment by pbelevich** [comment]
After discussion in #25590 I'd suggest to update graphic card driver as well, because 384.130 seems 1.5 year old

**Comment by ailzhang** [comment]
Yea I think the current error message is clear that it suggested `Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.` Closing the issue for now, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Comment by dyl0101** [comment]
I tried to install a new version of the graphics driver yesterday.But when I trained my program, I made the following new mistakes:
RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/aten/src/THC/THCGeneral.cpp:50
Besides, my tensorflow-based program can't run on GPU.
