### ISSUE TITLE
automatic transition to 'cuda' if available

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#25587]
## 🚀 Feature

transfer tensor to GPU, if available without having to do `to('cuda')`
## Motivation

Errors such as -

RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

RuntimeError: Expected object of backend CPU but got backend CUDA

**Comment by pbelevich** [comment]
The system works as designed, we don't move tensors between devices implicitly. It's a breaking compatibility changes so we are not going to do this.
