### ISSUE TITLE
Replace "NVIDIA driver" with "CUDA Toolkit" in _check_driver() error messages

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#25590]
[_check_driver()](https://github.com/pytorch/pytorch/blob/b22adeb0074f57c501422a6f44c5e0ad6f1c4adb/torch/cuda/__init__.py#L90) uses a term "NVIDIA driver" instead of "CUDA" and confuses users. 

NVIDIA driver is obviously NVIDIA video card driver, which has versions like 384.130
CUDA Toolkit has versions like 9.0 and represented as 9000 in int values.

The error message confuses users:
> The NVIDIA driver on your system is too old (found version 9000).
> Please update your GPU driver by downloading and installing a new
> version from the URL: http://www.nvidia.com/Download/index.aspx
> Alternatively, go to: https://pytorch.org to install
> a PyTorch version that has been compiled with your version
> of the CUDA driver.

And should be changed to
> CUDA Toolkit on your system is too old (found version 9000).
> Please update CUDA Toolkit by downloading and installing a new
> version from the URL: https://developer.nvidia.com/cuda-downloads
> Alternatively, go to: https://pytorch.org to install
> a PyTorch version that has been compiled with your version
> of CUDA Toolkit.

_check_driver() uses [cudaDriverGetVersion](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html) underneath and according to the documentation it returns CUDA version(surprise!)

Initially reported in #25581

**Comment by soumith** [comment]
it doesn't return the CUDA version. It returns "Returns the latest version of CUDA supported by the driver.".

If you have CUDA10 installed, but driver that only supports CUDA9, it will return `9000`

**Comment by pbelevich** [comment]
@soumith thanks for the explanation
