### ISSUE TITLE
Speed difference in .backward() between pytorch versions 

### ISSUE THREAD

**Issue by lukashermann** [pytorch/pytorch#2560]
Hi, I recently **upgraded to pytorch 0.2.0 from 0.1.12** and noticed that it drastically slowed down an a3c implementation I tested. I investigated what could be the problem and found out that the **.backward()** pass took **10 times longer** in the new pytorch. I wrote a little test program to reproduce the speed difference:

```python
import time
import torch
import numpy
import torch.nn as nn

d = 100
td = 0
for i in range (500):
    a = torch.randn(1,d)
    a_vb = torch.autograd.Variable(a,requires_grad=True)
    for i in range(100):
        fc1 = nn.Linear(d,d)
        a_vb = fc1(a_vb)
    b_vb = a_vb.norm()
    t1 = time.time()
    b_vb.backward()
    t2 = time.time()
    td+= t2-t1
print("time: ", td)
```

I set up two virtual environments (Python 2.7.6) which are identical except the pytorch version.
Pytorch was installed via pip.

```
certifi==2017.7.27.1
chardet==3.0.4
gym==0.9.2
idna==2.6
mujoco-py==0.5.7
numpy==1.13.1
olefile==0.44
Pillow==4.2.1
pyglet==1.2.4
PyOpenGL==3.1.0
PyYAML==3.12
requests==2.18.4
six==1.10.0
torch==0.1.12.post2 (OR RESPECTIVELY torch==0.2.0.post3)
torchvision==0.1.9
urllib3==1.22
```

I ran it on Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-38-generic x86_64) with an Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

the environment with pytorch **0.2.0** took **10.44** sec, while the environment with pytorch **0.1.12** only took **2.64** seconds. Not as much as in the a3c algorithm, but still a weird circumstance. Does anyone know why this could be the case?

The a3c implementation I tested was https://github.com/ShangtongZhang/DeepRL with a3c pendulum.

**Comment by soumith** [comment]
We think we know where we've introduced performance regressions in 0.2.0. 
We're working on a series of fixes that'll help get back to original speed.
Also see: https://github.com/pytorch/pytorch/issues/2518
The first fix that went in is: https://github.com/pytorch/pytorch/pull/2556

cc: @gchanan

lastly, thanks a ton for reporting!

**Comment by lukashermann** [comment]
Ok thank you for the quick answer, I pulled the newest pytorch version and built it from source with anaconda, but it didnt help, this time it even took **12** seconds. But I will just wait for the next fixes and then test it again.

**Comment by soumith** [comment]
yes, we're in the phase of identifying the issues and will start to issue more fixes starting this week.

**Comment by Oktai15** [comment]
Hm, I got other results with code above, but interesting too. I run 10 experiments and it took very different time: 
0.1.12 version -- from *2.11* to *2.72* seconds
1.0 version -- from *2.26* to *3.12* seconds

I don't know it is usual variance, @soumith?

Machine:
Ubuntu 16.04.4 LTS
AMD Ryzen Threadripper 1920X 12-Core Processor

cc: @lukashermann

**Comment by gchanan** [comment]
tracking "high priority" in master issue https://github.com/pytorch/pytorch/issues/20367.

**Comment by gchanan** [comment]
prefer tracking in the master issue.
