### ISSUE TITLE
[ONNX] Exception when exporting jit script with `.max()` in the body

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25603]
## 🐛 Bug

```python
/usr/local/lib/python2.7/dist-packages/torch/onnx/symbolic_opset9.py in try_mask_to_index(index)
   1740     def try_mask_to_index(index):
   1741         print('baha {} {}'.format(index, type(index)))
-> 1742         if not index.node().mustBeNone() and index.type().scalarType() == "Byte":
   1743             warnings.warn("Exporting aten::index operator with indices of type Byte. "
   1744                           "Only 1-D indices are supported. In any other case, "

RuntimeError: r INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/core/jit_type.h:152, please report a bug to PyTorch.  (expect at /pytorch/aten/src/ATen/core/jit_type.h:152)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fed5ab71273 in /usr/local/lib/python2.7/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x494130 (0x7fed5b456130 in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x1d548c (0x7fed5b19748c in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch_python.so)
frame #3: PyEval_EvalFrameEx + 0x9446 (0x4c5326 in /usr/bin/python)
frame #4: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
frame #5: PyEval_EvalFrameEx + 0x6076 (0x4c1f56 in /usr/bin/python)
frame #6: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
frame #7: /usr/bin/python() [0x4d57a3]
frame #8: PyObject_Call + 0x3e (0x4a587e in /usr/bin/python)
frame #9: PyEval_EvalFrameEx + 0x263e (0x4be51e in /usr/bin/python)
frame #10: PyEval_EvalCodeEx + 0x306 (0x4b9b66 in /usr/bin/python)
```

## To Reproduce

Include this in a jit script
```python
@torch.jit.script
def smt_pred(confs, child, offsets)
    maxval, argmax = confs.max(0)
   idx = child[argmax + offsets[0]]
```

The indexing results in exception

## Expected behavior

No exception, support indexing in `torch.jit.script` when ONNX export

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

The torch script works fine

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
