### ISSUE TITLE
Move QNNPACK micro kernels under ATen

### ISSUE THREAD

**Issue by AshkanAliabadi** [pytorch/pytorch#25621]
## 🚀 Feature

Move QNNPACK micro kernels under ATen.

## Motivation

The initial motivation for this move was born out of an observation in a performance study that revealed Lenet and XRayMobileV3 could benefit from caching qnnpack_create calls.  In caffe2 the cached state is stored as part of the qnnp_operator handle, but in PyTorch we currently create this handle for each operator invocation.   To minimize the performance penalty of doing so, the plan is to factor out as much of this computation to a setup phase, yet defer to runtime the absolute minimum set of computation that was also a design-time computation in Caffe2, but now must be made run-time in PyTorch due to its design.

QNNPACK is currently used both by Caffe2 and PyTorch, and while this modification benefits PyTorch in that it allows use of QNNPACK more optimally, it introduces complexity into the version used by Caffe 2.  Hence the consensus was to move QNNPACK to PyTorch repository with the general long-term goal of seamlessly integrating it into ATen.

## Pitch

Move QNNPACK to PyTorch/master with the long-term goal of seamlessly integrating it with ATen.  This includes:

- Integrating QNNPACK's build system into PyTorch.
- Integrating QNNPACK's test suite with PyTorch's CI.
- Stripping down the library to the bare minimum by removing code unused in PyTorch.
- Moving towards a C++ implementation.
- Reworking the API to be more functional.
- Exploring other micro kernel implementations.

## Alternatives

Fork the QNNPACK repository and add a second QNNPACK submodule for PyTorch's use only.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by vkuzo** [comment]
@AshkanAliabadi , seems like we went with the fork.  Should we keep this open or ok to close?
