### ISSUE TITLE
DataParallel error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#25636]
I use `DataParallel` that device_ids is [1, 2], but only gpu 1 is used.
```
# gpu_ids: [1, 2]
model.cuda(gpu_ids[0])
model = torch.nn.DataParallel(model, device_ids=gpu_ids)
```

**Comment by as754770178** [comment]
In test, I set batch_size=1. I forget to revert.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
