### ISSUE TITLE
OSX conda install, error on compiled API version

### ISSUE THREAD

**Issue by stsievert** [pytorch/pytorch#2564]
Happened right after I tried to install via conda on OSX.

``` python
↪  conda install pytorch torchvision -c soumith
[...]
# All requested packages already installed.
# packages in environment at /Users/scott/anaconda:
#
pytorch                   0.2.0                py36_4cu75    soumith
torchvision               0.1.9                    py36_1    soumith
↪  python
[...]
>>> import torch
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/anaconda/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/anaconda/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ValueError: module functions cannot set METH_CLASS or METH_STATIC
>>> import numpy as np
>>> np.__version__
'1.12.1'
```

**Comment by killeent** [comment]
@stsievert can you update your version of numpy?

**Comment by stsievert** [comment]
Huh, updating to numpy 1.13.1 worked. Wasn't aware my numpy wasn't current. The conda recipe should be modified to reflect this?

**Comment by dougalsutherland** [comment]
This is definitely a bug in [the conda recipe](https://github.com/pytorch/builder/blob/master/conda/pytorch-0.2.0/build.sh). The best solution would probably be to build with an old numpy, since numpy's ABI is forward-compatible: e.g. `requirements/build` has `numpy 1.9.*`, `requirements/run` has `numpy >=1.9`.

**Comment by soumith** [comment]
this is a good idea. I didn't know numpy's ABI is forward-compatible. The next round of recipes, I'll build with an old enough numpy.

**Comment by dougalsutherland** [comment]
Yeah, this is the strategy conda-forge has shifted to lately: https://github.com/conda-forge/conda-forge.github.io/pull/415, https://github.com/conda-forge/conda-forge.github.io/pull/433. I think Continuum is going to keep versions of 1.9 in defaults for this reason, though I don't think they're quite there yet: https://github.com/conda-forge/conda-forge.github.io/pull/433#issuecomment-325727956.

**Comment by soumith** [comment]
tracked in https://github.com/pytorch/pytorch/issues/3649 and enforcing this, closing this issue.
