### ISSUE TITLE
Number of prefetch in DataLoader

### ISSUE THREAD

**Issue by hiroaki-santo** [pytorch/pytorch#25643]
I can see that ``DataLoader`` prefetch ``2 * num_workers`` data in:

https://github.com/pytorch/pytorch/blob/4fe857187c8ccdb911667f3bd3c4fbd5b228c286/torch/utils/data/dataloader.py#L708

https://github.com/pytorch/pytorch/blob/791347642b637ca5769998f5d95f597cb8f81d18/torch/utils/data/dataloader.py#L824

Is there any reason to limit this number?

**Comment by soumith** [comment]
it is because making this larger means you eat a lot of memory. Caching 2 mini-batches upfront seemed sufficient as a default.

**Comment by hiroaki-santo** [comment]
You say "as a default", but it is hardcoded and I feel it is not easy to just change it by inheritance. Especially, do we need the assertion?
But anyway, if the limitation is only from the size of memory, I can change the size.
Thank you.

**Comment by elmirador** [comment]
TBH make the prefetch size tied to the number of workers is very inconvenient, especially in this hardcoded way.
For instance, while training something video-related, I might need both RGB and optical flow across multiple frames as the network input. The I/O overhead is huge and I'd like to use multiple workers to hide it.
But, since the prefetch size is directly tied into the number of workers, and it happened that I only have 32 or 64GB of RAM, I can only use like 20 workers and that cannot hide the overhead completely, otherwise, I got the OOM error.

**Comment by fzyzcjy** [comment]
+1 For that... In my case each batch takes 1GB memory. So `batch_size=64` and `num_workers=32` will lead to about 64GB of memory...

**Comment by jprellberg** [comment]
+1 Please consider making the number of prefetched batches user-configurable!

**Comment by dniku** [comment]
Here is a quick and dirty workaround for making prefetch size configurable. Note that it does not support prefetch size smaller than the default `2 * num_workers`.

```python
from torch.utils.data import DataLoader
from torch.utils.data.dataloader import _SingleProcessDataLoaderIter, _MultiProcessingDataLoaderIter


class DataLoaderWithPrefetch(DataLoader):
    def __init__(self, *args, prefetch_size=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.prefetch_size = prefetch_size if prefetch_size is not None else 2 * kwargs.get('num_workers', 0)

    def __iter__(self):
        if self.num_workers == 0:
            return _SingleProcessDataLoaderIter(self)
        else:
            return _MultiProcessingDataLoaderIterWithPrefetch(self)


class _MultiProcessingDataLoaderIterWithPrefetch(_MultiProcessingDataLoaderIter):
    def __init__(self, loader):
        self.prefetch_size = loader.prefetch_size

        super().__init__(loader)

        # Prefetch more items than the default 2 * self._num_workers
        assert self.prefetch_size >= 2 * self._num_workers
        for _ in range(loader.prefetch_size - 2 * self._num_workers):
            self._try_put_index()

    def _try_put_index(self):
        assert self._tasks_outstanding < self.prefetch_size
        try:
            index = self._next_index()
        except StopIteration:
            return
        for _ in range(self._num_workers):  # find the next active worker, if any
            worker_queue_idx = next(self._worker_queue_idx_cycle)
            if self._workers_status[worker_queue_idx]:
                break
        else:
            # not found (i.e., didn't break)
            return

        self._index_queues[worker_queue_idx].put((self._send_idx, index))
        self._task_info[self._send_idx] = (worker_queue_idx,)
        self._tasks_outstanding += 1
        self._send_idx += 1

```

**Comment by thuzhf** [comment]
@soumith Whether does DataLoader support always prefech data up to `2 * num_workers` (or some other number like 10)? I mean whenenver `self._tasks_outstanding < 2 * self._num_workers`, the DataLoader will automatically prefetch data. In this way, when users call next(DataLoader), the user will get data immediately and don't need to wait.
