### ISSUE TITLE
unspecified launch failure

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#2567]
I keep having this error during the training using recent pytorch version. It was okay before.
Code:
```python
        result = comm.reduce_add(inputs)
        results = []
        for i in range(len(inputs)):
            results.append(result.cuda(i))
```
Error:
```bash
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (4) : unspecified launch failure at /home/ubuntu/pytorch/torch/lib/THC/THCTensorCopy.cu:85
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (4) : unspecified launch failure at /home/ubuntu/pytorch/torch/lib/THC/generic/THCStorage.c:182
```

**Comment by apaszke** [comment]
We can't reproduce the issue unless you give us the exact configurations of sizes/devices you're using. Please feel free to reopen the issue once you create it

**Comment by nogod1995** [comment]
Hi, @zhanghang1989 , Have you solved this problem? I have the same bug with you, hope for help. Thank you!

**Comment by zhanghang1989** [comment]
It is working okay for me in master branch.

**Comment by nlothian** [comment]
Just leaving a note to say this happened for me in a notebook after I suspended and restarted a computer (Ubuntu 16.04). Restarting Jupyter was sufficient to fix it for me.

**Comment by imkzh** [comment]
Don't know what caused this, but it seems that `nvidia-smi -r` may help (this command will reset all your CUDA devices).

**Comment by MarkAlive** [comment]
> Don't know what caused this, but it seems that `nvidia-smi -r` may help (this command will reset all your CUDA devices).

This is not a "friendly" commond. My machine turned to jammed after input it.

**Comment by ArturoDeza** [comment]
> > Don't know what caused this, but it seems that `nvidia-smi -r` may help (this command will reset all your CUDA devices).
> 
> This is not a "friendly" commond. My machine turned to jammed after input it.

This might have happened because your display system is directly connected to one of the graphics cards. This might only work well if you have a separate integrated graphics card that is used for rendering outputs on the screen.
