### ISSUE TITLE
JIT tracing class wrapped variable fails

### ISSUE THREAD

**Issue by Godricly** [pytorch/pytorch#25682]
## 🐛 Bug
If a tensor is wrapped in class, the tracing fails.
## To Reproduce
Run the script.
## Demo code
```python
import torch

class Module1(torch.jit.ScriptModule):
    def __init__(self):
        super(Module1, self).__init__()

    @torch.jit.script_method
    def forward(self, x, value:int):
        return x + value

@torch.jit.script
class Wrapper(object):
    def __init__(self, value):
        self.value = value

class Module2(torch.jit.ScriptModule):
    def __init__(self):
        super(Module2, self).__init__()

    @torch.jit.script_method
    def forward(self, x: Wrapper, value:int):
        return x.value + value


# from demo_class import make_module1
class Module3(torch.nn.Module):
    def __init__(self):
        super(Module3, self).__init__()
        self.module1 = Module1()
        self.module2 = Module2()

    def forward(self, x):
        #  tmp = self.module1(x,3)
        x_wrapped = Wrapper(x)
        tmp = self.module2(x_wrapped,3)
        y = tmp+1
        return y


if __name__ == "__main__":
    module = Module3()
    print(module)
    dummy = torch.zeros(1,3,200,200)
    torch.jit.trace(module, dummy)
```
## Expected behavior
```bash
Module3(
  (module1): Module1()
  (module2): Module2()
)
# ...

    result = self.forward(*input, **kwargs)
RuntimeError: Tried to trace <__torch__.Wrapper object at 0x371a810> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.
```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
Collecting environment information...
PyTorch version: 1.3.0.dev20190902
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.0
[pip3] torch==1.3.0.dev20190902
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

cc @suo

**Comment by Godricly** [comment]
Is there any update for this one?

**Comment by wanchaol** [comment]
Hi I took a look at this. Basically tracing only allows the input/output being Tensors or Tuple of Tensors, and all intermediate results will be turned into tensors, we don't actually allow torchscript class to be in the middle of tracing because tracer won't able to understand on how to turn a class to a tensor. That's why your program fails. 

To workaround, scripting are fully compatible with Torchscript classes, so you can put the initialization of torchscript class into ScriptModule, writing it as following and it will works properly:
```python
import torch

class Module1(torch.jit.ScriptModule):
    def __init__(self):
        super(Module1, self).__init__()

    @torch.jit.script_method
    def forward(self, x, value:int):
        return x + value

@torch.jit.script
class Wrapper(object):
    def __init__(self, value):
        self.value = value

class Module2(torch.jit.ScriptModule):
    def __init__(self):
        super(Module2, self).__init__()

    @torch.jit.script_method
    def forward(self, x, value:int):
        x_wrapped = Wrapper(x)
        return x_wrapped.value + value


# from demo_class import make_module1
class Module3(torch.nn.Module):
    def __init__(self):
        super(Module3, self).__init__()
        self.module1 = Module1()
        self.module2 = Module2()

    def forward(self, x):
        #  tmp = self.module1(x,3)
        tmp = self.module2(x, 3)
        y = tmp+1
        return y


if __name__ == "__main__":
    module = Module3()
    print(module)
    dummy = torch.zeros(1,3,200,200)
    torch.jit.trace(module, dummy)
```

**Comment by wanchaol** [comment]
I am going to close this issue but feel free to re-open it if you think this is not enough for your use case :)
