### ISSUE TITLE
Torch 1.1.0.post2 doesn’t contain “manylinux” wheel files. Who can push them?

### ISSUE THREAD

**Issue by lapolonio** [pytorch/pytorch#25688]
## 🐛 Bug

According to https://pypi.org/project/torch/1.1.0.post2/#files
The manylinux versions don't exist for the different python versions.

## To Reproduce

1. Compare:
https://pypi.org/project/torch/1.1.0/#files
https://pypi.org/project/torch/1.1.0.post2/#files

## Expected behavior

The manylinux versions will exist for 1.1.0.post2

**Comment by soumith** [comment]
post2 was only released for osx, as a build number bump (because we botched the build number 1 binaries on OSX). one should just have the constraint `1.1.0` and pypi will resolve it to either 1.1.0 or 1.1.0.post2 appropriately
