### ISSUE TITLE
Remove test_potrf.py

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#2568]
Added in https://github.com/pytorch/pytorch/pull/2386. Should be part of `test_autograd.py`

**Comment by fmassa** [comment]
Quoting @jmxpearson in #2386:
> Unfortunately, the framework in test_autograd fails for the Function subclass because the outputs of Potrf are not independent, so the Jacobian calculation isn't correct. I implemented a different set of tests based on Murray's [here](https://github.com/imurray/chol-rev/blob/master/python/chol_rev_demo.py)

**Comment by apaszke** [comment]
That's fine, but the test should have its own method in `TestAutograd`, not a separate file

**Comment by zou3519** [comment]
test_potrf.py was removed via #3856
