### ISSUE TITLE
Missing pip install wheels from the PyTorch official website

### ISSUE THREAD

**Issue by HobbitLong** [pytorch/pytorch#25684]
## 📚 Documentation

I am not sure this should be named as doc issue, but I cannot find better.

The installation website https://pytorch.org/get-started/previous-versions/ points us to CUDA8.0 and CUDA9.0 wheels for pip install. But it's empty there:
https://download.pytorch.org/whl/cu80/torch_stable.html
https://download.pytorch.org/whl/cu90/torch_stable.html

**Comment by zzhuolun** [comment]
You can use command line to download the wheels:

to see the content of the URL
`$ curl https://download.pytorch.org/whl/cu90/torch_stable.html`

e.g. download torch-1.1.0-cp36-cp36m-linux_x86_64.whl 
`wget https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-linux_x86_64.whl`

**Comment by HobbitLong** [comment]
Thanks @zzhuolun. Solved!
