### ISSUE TITLE
No type hints on nn.Identity

### ISSUE THREAD

**Issue by eduidl** [pytorch/pytorch#25694]
## 🐛 Bug

Mypy fails on simple calls on `nn.Identity`

## To Reproduce

1. `pipenv --python 3.6`
1. `pipenv shell`
1. `pip install torch==1.2.0 mypy==0.720`
1. `mypy --strict test.py`

```
# test.py
from torch.nn import Identity # ng
from torch.nn import Linear # ok
```
This yields:

```
test.py:1: error: Module 'torch.nn' has no attribute 'Identity'
```

## Expected behavior

Type check should pass like `from torch.nn import Linear`.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.1
[pip3] torch==1.2.0
[conda] Could not collect
```

## Cause

I found description about `Identity` in https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/__init__.pyi.in#L20 is lacking.
Should be:

```diff
-from .linear import Bilinear as Bilinear, Linear as Linear
+from .linear import Bilinear as Bilinear, Linear as Linear, Identity as Identity
```

cc @ezyang

**Comment by ezyang** [comment]
@eduidl Thank you. Do you mind opening a PR with that diff? Tag me as reviewer.
