### ISSUE TITLE
PyTorch C++ API as a static lib: how to compile ?

### ISSUE THREAD

**Issue by VitaMusic** [pytorch/pytorch#25699]
## ❓ Questions and Help

this questions is linked to the bug described in the issue https://github.com/pytorch/pytorch/issues/25698

I'd like to have instructions on how to compile PyTorch C++ API (libtorch project) as a statical library to link with my C++ projects :

- for Linux, Windows and MacOS
- with the last Intel compilers if possible
- mode with and witout GPU support (CPU vs GPU),  with the last drivers and controling GPU cart 'compute capabilities' support, to be able to execute the code on old Kepler cards
- debug and release (advanced optimization and vectorization) modes

thanks for your help and assistance !

**Comment by jinfagang** [comment]
Better using dynamic lib.

**Comment by VitaMusic** [comment]
Why?

чт, 5 Сен 2019 г., 13:23 JinTian <notifications@github.com>:

**Comment by soumith** [comment]
libtorch has download links on pytorch.org that look like this:

```
https://download.pytorch.org/libtorch/cu100/libtorch-cxx11-abi-shared-with-deps-1.2.0.zip
```

You can replaced "shared" with "static" and get URLs like this:

```
https://download.pytorch.org/libtorch/cu100/libtorch-cxx11-abi-static-with-deps-1.2.0.zip
```

They exist, we generate them. I just dont remember if they work properly, but they do pass some smoke tests.

**Comment by VitaMusic** [comment]
are they generated with intel compilers ?
if you had the compilation instructions and tests I'd like to rebuild with Intel from the source.

**Comment by soumith** [comment]
not with intel compiler.

The documentation is a bit sparse, but to build libtorch static libs this is what we do: https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L131-L143

**Comment by VitaMusic** [comment]
under windows did you do VS project maybe ?

**Comment by soumith** [comment]
we do have windows build scripts: https://github.com/pytorch/builder/tree/master/windows

However, I dont think we have built static libs on Windows. cc: @peterjc123 to confirm.

**Comment by peterjc123** [comment]
No static libs for Windows.

**Comment by VitaMusic** [comment]
you did not do, or it is not possible to do with this scripts ?

**Comment by peterjc123** [comment]
@VitaMusic I didn't do it because of the time limit for the nightly builds.

**Comment by gemfield** [comment]
@soumith With pytorch1.6, though I download with static library url: https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-static-with-deps-1.6.0.zip, the libtorch file name is still libtorch.so and libtorch_cuda.so, didn't see libtorch.a or any similar stuff.

**Comment by soumith** [comment]
@seemethere can you check on this, maybe we've regressed?

**Comment by seemethere** [comment]
Interestingly enough, it appears as though we haven't regressed, we just never had a `libtorch.a` in our `static` zip archives:

Script used to test:
```bash
#!/usr/bin/env bash

set -eou pipefail

echo "Checking existense of 'libtorch.a'"

for version in "1.2.0" "1.3.1" "1.4.0" "1.5.1" "1.6.0"; do
    filename="libtorch-cxx11-abi-static-with-deps-${version}%2Bcu92.zip"
    if ! curl -fsSL -O "https://download.pytorch.org/libtorch/cu92/${filename}"; then
        echo "https://download.pytorch.org/libtorch/cu92/${filename}" not found
        exit 1
    fi
    if ! unzip -l "${filename}" | rev | cut -d' ' -f1 | rev | grep 'libtorch.a$' >/dev/null 2>/dev/null; then
        echo -n '- '
    else
        echo -n '+ '
    fi
    echo "${filename}"
    rm -f "${filename}"
done
```

Results:
```
❯ bash check_libtorch_static.sh
Checking existense of 'libtorch.a'
- libtorch-cxx11-abi-static-with-deps-1.2.0%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.3.1%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.4.0%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.5.1%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.6.0%2Bcu92.zip
```

**Comment by QuantScientist** [comment]
Hello, I am the author of https://github.com/QuantScientist/TorchRayLib and I am also interested in testing the statically linked libraries on Windows. Thanks.

**Comment by gemfield** [comment]
I have built the 1.6 & 1.7 static libtorch library and put here:
https://github.com/CivilNet/libtorch/releases/download/v1.7.0/libtorch_cuda_1.6.0.tar.gz
https://github.com/CivilNet/libtorch/releases/download/v1.7.0/libtorch_cuda_1.7.0.tar.gz

Usage: https://github.com/DeepVAC/libdeepvac/blob/master/CMakeLists.txt

**Comment by xiazh18** [comment]
> are they generated with intel compilers ? if you had the compilation instructions and tests I'd like to rebuild with Intel from the source.

Hey, do you successfully generated with intel compilers? I meet the same problem. My programs are compiled with Intel, but libtorch in pytorch.org is compiled with GNU.

**Comment by jamespinkerton** [comment]
@powderluv it looks like 2.0.1 doesn't have a libtorch.a anymore?

**Comment by jamespinkerton** [comment]
@soumith any place to add libtorch.a back into the releases? It's not there when I checked in pytorch 2.0.1.

**Comment by anthonyalayo** [comment]
I also checked and didn't see it there. Is it difficult to add back?

**Comment by MaxMalmer** [comment]
I agree that this would be useful. Are there any instructions otherwise to compile it statically yourself?

**Comment by anqin** [comment]
agree. we need the static libs

**Comment by kirillmeisser** [comment]
Hi everyone, has this been addressed? As of today there still seems to be no instructions on how to compile it statically and libtorch.a is still missing in the official download link. Cheers!
