### ISSUE TITLE
toDense is misdocumented as a method on sparse tensors

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25706]
https://pytorch.org/docs/stable/sparse.html#torch.sparse.FloatTensor.toDense

It's not toDense, it's `to_dense`

**Comment by Nikronic** [comment]
Hi,
Only this file needs to be changed, right?
https://github.com/pytorch/pytorch/blob/master/docs/source/sparse.rst

@ezyang

**Comment by ezyang** [comment]
@Nikronic Yes, that would be a good start! Further follow up would be to figure out why doc building isn't failing us for referring to a non-existent method.

**Comment by Nikronic** [comment]
PR #25832 approved. 
@ezyang should we create a new issue as you said that why doc building did not fail or track within this one?
Thank you

**Comment by ezyang** [comment]
@Nikronic new issue please! thanks!
