### ISSUE TITLE
backward_hook triggered despite RemovableHandle.remove()

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#25723]
```
import torch
import torch.nn as nn

layer = nn.Linear(1, 1)
model = nn.Sequential(layer)
handle = layer.register_backward_hook(lambda *args: print("hook called"))
output = model(torch.ones(1))
handle.remove()
output.backward()
```

This prints `hook called`.

cc @ezyang @SsnL @albanD @zou3519

**Comment by ezyang** [comment]
Note: if you remove the handle before invoking the model all is fine:

```
import torch
import torch.nn as nn

layer = nn.Linear(1, 1)
model = nn.Sequential(layer)
handle = layer.register_backward_hook(lambda *args: print("hook called"))
handle.remove()
output = model(torch.ones(1))
output.backward()
```

**Comment by ezyang** [comment]
cc @apaszke

**Comment by albanD** [comment]
Hi,

I think this is expected behavior I think. You cannot change the nn.Module's hooks after the graph has been created.

**Comment by yaroslavvb** [comment]
Unfortunately hooks on Tensors don't give the values needed to implement 
https://github.com/pytorch/pytorch/issues/7786

You you need backward and forward values for each layer.

This feels like module-specific concept rather than tensor-specific because there's shared computation for different parameters in a layer. For instance, computing Hessian for weight and bias parameters in a layer need [the same preprocessing](https://github.com/cybertronai/autograd-hacks/blob/master/autograd_hacks.py#L207) on captured backward values

**Comment by albanD** [comment]
I agree that a module backward hook would looks better for your use case, but at the moment we recommend not to use them.
It's not as clean, but you can use a forward hook on the module to do two things: get the forward values and add a Tensor hook on the output.

**Comment by yaroslavvb** [comment]
Thanks, indeed this seems to do the trick

```
import torch
import torch.nn as nn


def tensor_hook_adder(module, input, output):
    def tensor_backwards(grad):
        setattr(module, 'backprops', grad)
    output.register_hook(tensor_backwards)

layer = nn.Linear(2, 2, bias=False)
layer.weight.data.copy_(2*torch.eye(2))
model = layer
layer.register_forward_hook(tensor_hook_adder)

output = model(torch.tensor([1.,2]))
loss = output[0]**2+2*output[1]**2
loss.backward()
assert torch.allclose(layer.backprops, torch.tensor([4, 16.]))
```

**Comment by yaroslavvb** [comment]
Here's another situation I have to deal with. There are various statistics that can be extracted from backward values, and the choice doesn't have to be known until backwards call.

1. Ideal module hooks API would look like this
```
    handle = layer.register_backward_hook(print_hessian_stats)
    tensor.backwards(retain_graph=True)
    handle.remove()

    handle = layer.register_backward_hook(print_gradient_covariance_stats)
    tensor.backwards(retain_graph=True)
    handle.remove()
```

2. Using Tensor hooks API, I can register a "master hook" in the beginning, and customize its behavior before each backwards call

```
def master_hook_adder(module, input, output):
    def tensor_backwards(grad):
        global global_backward_hook
        global_backward_hook(module, grad)

global_backward_hook = print_hessian_stats
tensor.backwards(retain_graph=True)

global_backward_hook=print_gradient_covariance_stats
tensor.backward(retain_graph=True)

global_backward_hook = NoOp
```

It looks to have similar complexity, but imagine extending this to work with multiple models, and or multiple Python threads. The module hook approach should work for multiple models unmodified, and for multiple threads as long as `layer` variable uses thread-local storage. For the tensor hook approach, it's not clear where to move the `global_backward_hook` setting.

**Comment by ezyang** [comment]
@yaroslavvb Do you want to open a new feature request issue for this?

**Comment by yaroslavvb** [comment]
There's actually an issue for this already -- https://github.com/pytorch/pytorch/issues/598

**Comment by yaroslavvb** [comment]
BTW, I found this pattern useful to get tensor hooks to automatically remove themselves after execution -- this enables PyTorch to reclaim any tensors referenced in hook body. IE, example below will release activations for the layer as soon as hook computation is done

```
norms = [torch.zeros(n).to(device)]
handles = []

def compute_norms(layer, A, output):
    idx = len(handles)
    def tensor_backwards(B):
        norms[0]+=(A*A).sum(dim=1)*(B*B).sum(dim=1)
        handles[idx].remove()
    handles.append(output.register_hook(tensor_backwards))
```

https://colab.research.google.com/drive/1EwUPkxaFSwQbk_y4Cl_mvT3L4p4hb1kS

**Comment by slerman12** [comment]
I don't understand any of this, but is it safe to comment out this line:

`assert model == 0, "not working, remove this after fix to https://github.com/pytorch/pytorch/issues/25723"`

**Comment by albanD** [comment]
It depends where this line is haha
Also there is not fix for this as this is the expected behavior :)
