### ISSUE TITLE
backward(retain_graph=) kwarg is missing __init__.pyi

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#25736]
My IDE gets confused on `output.backward(retain_graph=True)`
Because `torch/__init__.pyi` (PyTorch 1.2) has the following, `retain_graph` kwarg is missing

```
    def backward(self, gradient: Optional[Tensor]=None, keep_graph: _bool=False, create_graph: _bool=False) -> None: ...
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @jlin27 @mruberry

**Comment by albanD** [comment]
This was fixed by moving the typing inline.
