### ISSUE TITLE
[NGC Container]Runtime Error - Nvidia Nsight System 

### ISSUE THREAD

**Issue by SrivastavaKshitij** [pytorch/pytorch#25764]
## 🐛 Bug

I am getting the following error when I am trying to profile my pytorch code using `nv-nsight-cu-cli` command. 

```
root@e9c86b1eb7da:/workspace/work# nv-nsight-cu-cli python standard_benchmark_pth/infer_pth.py --load standard_benchmark_pth/resnet50_jit.pt --iter 100
Namespace(batch_size=1, fp16=False, gpu=0, iter=100, load='standard_benchmark_pth/resnet50_jit.pt', model=None, trace=False)
Loading traced model...
==PROF== Connected to process 643
Cuda DNN version= 7602
Current GPU id, GPU count= 0 1
Cuda compute capability= (7, 5)
Cuda device name= GeForce RTX 2080
Warm up ...
==PROF== Profiling "computeOffsetsKernel" - 1: 0%....50%....100% - 47 passes
==PROF== Profiling "volta_scudnn_128x64_relu_medi..." - 2: 0%....50%....100% - 48 passes
Traceback (most recent call last):
  File "standard_benchmark_pth/infer_pth.py", line 144, in <module>
    timings = timeGraph(model, input_t, args.iter)
  File "standard_benchmark_pth/infer_pth.py", line 24, in timeGraph
    features = model(input_t)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
The above operation failed in interpreter, with the following stack trace:

==PROF== Disconnected from process 643
==ERROR== The application returned an error code (1)
```

## To Reproduce

I can only use containers on my machine. Nvidia ngc container for pytorch doesnt have nsight installed. So, I used tensorflow ngc container (19.06_py3), installed pytorch inside the container (`pip3 install torch torchvision`) and took a snapshot of that container using `docker commit <container id> <image name>`

## Environment

NGC Container
```
Ubuntu 16.04
Note: 19.06-py3 contains Python 3.5.
NVIDIA CUDA 10.1.168 including cuBLAS 10.2.0.168
NVIDIA cuDNN 7.6.0
NVIDIA NCCL 2.4.7 (optimized for NVLink™ )
Horovod 0.16.2
OpenMPI 3.1.3
TensorBoard 1.13.1+nv
MLNX_OFED 3.4
OpenSeq2Seq at commit 27346d1
TensorRT 5.1.5
DALI 0.10.0 Beta
DLProf 19.06
Nsight Compute 10.1.168
Nsight Systems 2019.3.1.94
Pytorch 1.2.0
```
There is another issue similar to this one #24891 . However, I am not sure how relevant that is given the environments are different. 

Is there a way to fix it or maybe create a pytorch ngc container with nv-nsight installed in it ?

**Comment by soumith** [comment]
cc: @ptrblck

**Comment by ptrblck** [comment]
Hi @SrivastavaKshitij,

I just tested our `nvcr.io/nvidia/pytorch:19.06-py3` container and was able to use `nv-nsight-cu-cli` inside to profile a dummy script:
```python
# test.py
import torch

x = torch.randn(1, 2, 3, 4,device='cuda')
y = torch.randn(1, 2, 3, 4, device='cuda')

torch.cuda.synchronize()
torch.cuda.nvtx.range_push('calc')
z = x + y
torch.cuda.nvtx.range_pop()
print(z)
```
```
# profiling
root@939db497a662:/workspace/src# nv-nsight-cu-cli -o temp.profile  python test.py
==PROF== Connected to process 1031
==PROF== Profiling "generate_normal" - 1: 0%....50%....100% - 48 passes
==PROF== Profiling "generate_normal" - 2: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 3: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply3" - 4: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 5: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 6: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply3" - 7: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 8: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply3" - 9: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelReduceAll" - 10: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 11: 0%....50%....100% - 48 passes
==PROF== Profiling "_kernel_agent" - 12: 0%....50%....100% - 48 passes
==PROF== Profiling "_kernel_agent" - 13: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply3" - 14: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 15: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 16: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelReduceAll" - 17: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 18: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelReduceAll" - 19: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 20: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 21: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply3" - 22: 0%....50%....100% - 48 passes
==PROF== Profiling "" - 23: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 24: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 25: 0%....50%....100% - 48 passes
==PROF== Profiling "kernelPointwiseApply2" - 26: 0%....50%....100% - 48 passes
tensor([[[[-0.5762, -1.1294,  0.8577,  0.6781],
          [ 1.6918,  0.5137, -0.7114,  2.6875],
          [-0.0121,  2.7715,  1.3594,  1.4439]],

         [[ 1.0207, -3.4489,  0.6463,  0.5692],
          [-0.9320,  0.3777, -0.3052, -0.1968],
          [-1.5982, -0.7636,  1.3363, -0.6381]]]], device='cuda:0')
==PROF== Disconnected from process 1031
==PROF== Report: temp.profile.nsight-cuprof-report
```

Could you recheck the container again?

**Comment by SrivastavaKshitij** [comment]
@ptrblck : Thanks. `nvcr.io/nvidia/pytorch:19.06-py3` does have nsight, however, it's not mentioned in the [release notes](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_19-06.html#rel_19-06)

I also checked latest pytorch ngc container  `nvcr.io/nvidia/pytorch:19.08-py3` and it does not contain nsight it. 

Do we know if all the future releases will have `nsight` in them ?

**Comment by ptrblck** [comment]
You are right. I just tested a few containers and it seems to be missing in `19.08`.
Let me ask our build team, what happened.

**Comment by ptrblck** [comment]
It looks like it's still installed, but a different location was used in `19.08`, sorry for the confusion :confused: 
We'll fix it for `19.10`. 

Meanwhile you can use `/opt/nvidia/nsight-compute/2019.4.0/nv-nsight-cu-cli` in `19.08`.

**Comment by SrivastavaKshitij** [comment]
No problem. thanks for the clarification. :-) May I suggest updating release notes to include nsight systems. Initially I looked at the release notes and assumed nsight is not a part of pytorch ngc containers.

**Comment by ptrblck** [comment]
Sure, that's another good idea!
Thanks :)

**Comment by RobotGF** [comment]
> ## 🐛 Bug
> I am getting the following error when I am trying to profile my pytorch code using `nv-nsight-cu-cli` command.
> 
> ```
> root@e9c86b1eb7da:/workspace/work# nv-nsight-cu-cli python standard_benchmark_pth/infer_pth.py --load standard_benchmark_pth/resnet50_jit.pt --iter 100
> Namespace(batch_size=1, fp16=False, gpu=0, iter=100, load='standard_benchmark_pth/resnet50_jit.pt', model=None, trace=False)
> Loading traced model...
> ==PROF== Connected to process 643
> Cuda DNN version= 7602
> Current GPU id, GPU count= 0 1
> Cuda compute capability= (7, 5)
> Cuda device name= GeForce RTX 2080
> Warm up ...
> ==PROF== Profiling "computeOffsetsKernel" - 1: 0%....50%....100% - 47 passes
> ==PROF== Profiling "volta_scudnn_128x64_relu_medi..." - 2: 0%....50%....100% - 48 passes
> Traceback (most recent call last):
>   File "standard_benchmark_pth/infer_pth.py", line 144, in <module>
>     timings = timeGraph(model, input_t, args.iter)
>   File "standard_benchmark_pth/infer_pth.py", line 24, in timeGraph
>     features = model(input_t)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
> RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
> The above operation failed in interpreter, with the following stack trace:
> 
> ==PROF== Disconnected from process 643
> ==ERROR== The application returned an error code (1)
> ```
> 
> ## To Reproduce
> I can only use containers on my machine. Nvidia ngc container for pytorch doesnt have nsight installed. So, I used tensorflow ngc container (19.06_py3), installed pytorch inside the container (`pip3 install torch torchvision`) and took a snapshot of that container using `docker commit <container id> <image name>`
> 
> ## Environment
> NGC Container
> 
> ```
> Ubuntu 16.04
> Note: 19.06-py3 contains Python 3.5.
> NVIDIA CUDA 10.1.168 including cuBLAS 10.2.0.168
> NVIDIA cuDNN 7.6.0
> NVIDIA NCCL 2.4.7 (optimized for NVLink™ )
> Horovod 0.16.2
> OpenMPI 3.1.3
> TensorBoard 1.13.1+nv
> MLNX_OFED 3.4
> OpenSeq2Seq at commit 27346d1
> TensorRT 5.1.5
> DALI 0.10.0 Beta
> DLProf 19.06
> Nsight Compute 10.1.168
> Nsight Systems 2019.3.1.94
> Pytorch 1.2.0
> ```
> 
> There is another issue similar to this one #24891 . However, I am not sure how relevant that is given the environments are different.
> 
> Is there a way to fix it or maybe create a pytorch ngc container with nv-nsight installed in it ?

Does DLProf support Pytorch in NGC？ I pulled 19.06 but didn't find DLProf
