### ISSUE TITLE
Fix potential infinite loop in TCP store connect function

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#25769]
## 🐛 Bug

The `connect` function in c10d (used by the TCP store) may end up retrying infinitely if in every connection attempt it gets either a ECONNREFUSED or ECONNRESET.

See https://github.com/pytorch/pytorch/pull/25707#discussion_r321751249

## Expected behavior

It should never run longer than the timeout argument that is already passed.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by rohan-varma** [comment]
Fixed in #26364
