### ISSUE TITLE
Can't load the tensor image to the GPU devices.

### ISSUE THREAD

**Issue by crystalwan** [pytorch/pytorch#25761]
## ❓ Questions and Help

the code is :

- image=cv::imread("test.jpg");
- tensor_image = torch::from_blob(image.data,{1,height, width,3},torch::kFloat32);
- tensor_image.to(at::kCUDA);
-  cout<<tensor_image<<endl;

But the tensor_image is still in CPU,why?

**Comment by Nikronic** [comment]
I do not about C++, but `.to` function is not inplace which means you have to assign it to the referenced variable, like this : 
```C++
tensor_image = tensor_image.to(at::kCUDA)
```

**Comment by madieraRRC** [comment]
tensor-image/.io-patch-1

**Comment by crystalwan** [comment]
df

> I do not about C++, but `.to` function is not inplace which means you have to assign it to the referenced variable, like this :
> 
> ```c++
> tensor_image = tensor_image.to(at::kCUDA)
> ```


it works as this , thanks
