### ISSUE TITLE
how to get cube-root of a negative?

### ISSUE THREAD

**Issue by qianlinjun** [pytorch/pytorch#25766]
hello, I want to know how to get cube-root of a negative？
for example (-8)^(1/3) = -2
however, torch.pow(-8, 1/3) get Nan.

**Comment by peterjc123** [comment]
(-8)^(1/3) apparently doesn't equal to -2, but - 8^(1/3) does. Our behavior is consistent with other libraries like NumPy.
```py
>>> import numpy as np
>>> np.power(-8, 1.0/3)
nan
```

**Comment by henrique** [comment]
could we reopen this?
```
>>> np.cbrt(-8)
-2.0
```
cpp, and caffe2 have a function for it https://github.com/pytorch/pytorch/blob/v1.8.1/caffe2/utils/math/elementwise.cc#L231-L234
thanks

**Comment by crowsonkb** [comment]
Do this:

```python
def odd_pow(input, exponent):
    return input.sign() * input.abs().pow(exponent)
```
