### ISSUE TITLE
/pytorch/third_party/ideep/include/ideep/utils.hpp:15:21: fatal error: mkl_vsl.h: No such file or directory

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#25760]
I already runs:

```
export USE_MKLDNN=0
```

But still got this error....

```
/pytorch/third_party/ideep/include/ideep/utils.hpp:15:21: fatal error: mkl_vsl.h: No such file or directory
```

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by peterjc123** [comment]
Please try this one. 
```bash
python setup.py install --cmake
```

**Comment by jinfagang** [comment]
Just wonder why `--cmake`?

BTW, if I want enable onnx python what else can I do except I change CMakeLists.txt inside `thirdparty/onnx`?

**Comment by peterjc123** [comment]
> Just wonder why `--cmake`?

If you don't specify `--cmake`, the configuration step will be skipped. So `USE_MKLDNN` will keep its previous value.

> BTW, if I want enable onnx python what else can I do except I change CMakeLists.txt inside `thirdparty/onnx`?

There is no way. We don't use ONNX python during the build.

**Comment by jinfagang** [comment]
Then why pytorch installed from pip can `from torch import onnx`? How did u guys build?

I previously deleted `build` dir, and try `export USE_MKLDNN=0`, and then build again. Still got this MKL error

**Comment by peterjc123** [comment]
> Then why pytorch installed from pip can from torch import onnx? How did u guys build?

What does `torch.onnx` has to do with ONNX python? We could just use ONNX C++.

> I previously deleted build dir, and try export USE_MKLDNN=0, and then build again. Still got this MKL error

Full log during configuration, please.

**Comment by jinfagang** [comment]
Oh, the full story is that I build pytorch from source and I can not call something like:
```
import torch.onnx.symbolic_helper as sym_help
```

it says does not have a symbolic_helper in torch.onnx, then I realize that I can not even have torch.onnx when build from source. This is happened when I try maskrcnn-benchmark.

```
demo/pytorch_export_patch.py
```

**Comment by ezyang** [comment]
What is the contents of `pip list` and `conda list`

**Comment by jinfagang** [comment]
```
torch                         1.1.0                  
torchvision                   0.4.0a0+d31eafa   
```

**Comment by XiaobingSuper** [comment]
@jinfagang, Can you try build the latest source [code](https://github.com/pytorch/pytorch/blob/master) (latest code is verison 1.3), I rember there has a build bug when disable MKLDNN build for old pytorch version.

**Comment by jinfagang** [comment]
this torch is my previous installed from pip, now I have 1.3 already... this is the master branch for now:

```

```

**Comment by ezyang** [comment]
You've got a stale copy of torch in your environment. `pip uninstall torch` and try building again...

**Comment by Abbyyan** [comment]
I've got the same error. Does this has been solved please?
