### ISSUE TITLE
why the torch::cat crashed 

### ISSUE THREAD

**Issue by lbc3402785** [pytorch/pytorch#25774]
## To Reproduce

    torch::Tensor t1=torch::rand({2,2});
    torch::Tensor t2=torch::rand({2,2});

     
    std::cout<<torch::cat({t1,t2},1);<<std::endl;

## Environment

Please copy and paste the output from our
[win10 libtorch1.0](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peterjc123** [comment]
Please ensure the DLLs are copied to the path of the generated executable.

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/issues/25457#issuecomment-527177504
