### ISSUE TITLE
gradients / values nonsenically becoming nan

### ISSUE THREAD

**Issue by dougalsutherland** [pytorch/pytorch#2577]
https://gist.github.com/dougalsutherland/83432508d796377bd7b8371fa3b52c4a has a test file and a data file where the gradients (and, strangely, the parameter values too) eventually become `nan` for seemingly no reason; similar behavior on GPU or not. Expected output:

```
0/0: 33028.4140625
0/1: 29880.9160156
0/2: 32534.9492188
0/3: 31306.3242188
0/4: 32576.6816406
0/5: 34216.7734375
0/6: 28895.5039062
0/7: 34759.0078125
1/0: 32968.1289062
1/1: 30035.6972656
Traceback (most recent call last):
  File "./model.py", line 63, in <module>
    raise ValueError("Bad values for " + bads)
ValueError: Bad values for gen, gen_grad, latent, latent_grad
```

This happens when the loss is `torch.norm(a - b, p=1)`, but doesn't seem to happen with `torch.nn.functional.l1_loss`.

I wasn't able to reproduce the behavior in a couple tries with random data, hence the data file too.

This is still not doing exactly what I mentioned on Slack yesterday (`invalid pointer`, `corrupted unsorted chunks`, etc), but I wasn't able to reproduce that with a smaller dataset / model yet, and might be related to this problem, who knows.

**Comment by dougalsutherland** [comment]
Looking into it a little more, it seems to possibly be a problem with my assumptions about what pytorch does with indexing, without looking into the docs about that at all. Need to run now, but will investigate more tomorrow and report back.

**Comment by dougalsutherland** [comment]
Okay, yes, this was related to the parameters growing very large, because my intended step where I project them back wasn't working. Now that I'm doing that properly, this no longer happens, and this minimized version is uninteresting. Will see if it totally fixes the big version (other than #2563)....

**Comment by dougalsutherland** [comment]
(Big model still breaks immediately. Will try to track down further tomorrow.)

**Comment by JianboTang** [comment]
I also encounter this problem and have nothing to do with it
