### ISSUE TITLE
[ONNX] Support exporting bitwise_not from PyTorch

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#25805]
## 🐛 Bug

`bitwise_not` not supported for bool tensors

## To Reproduce

```python
a = b > c
na = ~a

...

---> 91     return _registry[(domain, version)][opname]
KeyError: u'bitwise_not
```

## Expected behavior

Support bitwise not operation same as other ops

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

Additional context
## Additional context

Workaround is to use 

```python
a = b > c
na = a == 0
```

But it is not very pretty

**Comment by dashesy** [comment]
```python
a = b > c
na = a == 0
```

will export but is wrong onnx because onnx cannot compare 0 to boolean.

This is the workaround

```python
a = b > c
na = a == torch.as_tensor(False)
```

Perhaps exporter should do this?

**Comment by dashesy** [comment]
I noticed `<=` is added to the graph as "Greater" + "Not", so "Not" should already be fine is the input is of `Bool` type?
No need to bitwise_not for Bool type, can use "Not"

**Comment by dashesy** [comment]
@neginraoof I added a PR (above) for this simple case, would appreciate if you look. I will add some test cases if you think this is fine.

**Comment by discharged-spider** [comment]
Maybe we should also support tensor.logical_not() operation, today a.logical_not() wouldn't export to ONNX and (~a) would, which is not consistent.
