### ISSUE TITLE
[jit] String default args get printed as ascii values

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#25804]
e.g. passing the wrong types to `interpolate`
```python
@torch.jit.script
def bad_error(x):
    return torch.nn.functional.interpolate(x, 'bad')
```
```
  aten::__interpolate(Tensor input, int? size=None, float[]? scale_factor=None, str
 mode='\156\145\141\162\145\163\164', bool? align_corners=None) -> (Tensor):       
  Expected a value of type 'Optional[int]' for argument 'size' but instead found ty
pe 'Tensor'.                                                                       
```

cc @suo

**Comment by Krovatkin** [comment]
Since nobody picked this one up yet, I'd like a friend of mine (@free25zer) to work on this issue as a way to get involved in open source.

**Comment by PyExtreme** [comment]
Hi @Krovatkin , I am interested to contribute to PyTorch. Can I please take up this issue?

**Comment by Krovatkin** [comment]
@PyExtreme we already have a fix for this issue, just need to push a PR for it 😢 I hope you haven't started on this yet?

**Comment by v0dro** [comment]
If this is fixed can you close this issue?
