### ISSUE TITLE
type_as() to have better error message when fed with Variable

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#2582]
Currently it makes a strange error message:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    torch.eye(2).type_as(v)
  File ".../site-packages/torch/tensor.py", line 31, in type_as
    return self.type(tensor.type())
TypeError: type() takes exactly 2 arguments (1 given)
```

Example:
```python
import torch

v = torch.autograd.Variable(torch.zeros(2))
torch.eye(2).type_as(v)
```

A crazy idea may be to have `type_as` create a `Variable` (this may be a non-verbose way to convert results of torch.* tensor creating functions to Variable). Otherwise, a nicer error message would be good.

**Comment by SsnL** [comment]
Planning to take on this one. Can we just do a nicer error message @soumith ? If so, should I do the same for `expand_as` and `view_as`? Although those technically work with variable currently.

**Comment by vadimkantorov** [comment]
Should `type_as` be able to ingest the the tensor type from the variable's tensor?

My original case was to creating an identity matrix variable on the same device as another variable's contents, so that later I can do operations on them. `Variable(torch.eye(4).type_as(v))` seems nicer compared to `Variable(torch.eye(4).type_as(v.data))` (especially if `v` holds a `torch.cuda.ByteTensor`)

**Comment by SsnL** [comment]
I think what you proposed would be good @vadimkantorov . It also maintains parity with `expand_as` and `view_as`.

**Comment by SsnL** [comment]
Let's wait until @apaszke unifies the tensor and variable to do this, for reasons discussed in #3003

**Comment by vadimkantorov** [comment]
irrelevant since the merge of tensor and variable
