### ISSUE TITLE
Possible misreference to torch.t() in torch instead of highlighting attribute 't'

### ISSUE THREAD

**Issue by Nikronic** [pytorch/pytorch#25834]
## 📚 Documentation

Hi,

In the [source doc of torch.set_default_tensor_type(t)](https://pytorch.org/docs/stable/_modules/torch.html#set_default_tensor_type), the argument `t` defined using `:attr:` tag but in the [compiled doc of torch.set_default_tensor_type(t)](https://pytorch.org/docs/stable/torch.html#torch.set_default_tensor_type), the `t` argument in the description, refers to [torch.t()](https://pytorch.org/docs/stable/torch.html#torch.t) (transpose) function inaccurately.
I think the source doc is right but I have no idea how the `attr` tag is refering to `func`.

**Comment by ezyang** [comment]
According to https://stackoverflow.com/questions/11168178/how-do-i-reference-a-documented-python-function-parameter-using-sphinx-markup there is no way to reference an argument and we should just use \`\`t\`\` Happy to review a patch if you want to put one up.

**Comment by Nikronic** [comment]
Yes, of course.
