### ISSUE TITLE
Add c++ api support for new_zeros and new_empty.

### ISSUE THREAD

**Issue by npuichigo** [pytorch/pytorch#25831]
Something like torch::Tensor::new_zeros is useful when using with libtorch's c++ frontend.

But now there's only an api for python.
```c++
Tensor new_zeros(c10::TensorTypeId type_id, at::ScalarType scalar_type, PyObject* args, PyObject* kwargs)
```

cc @yf225

**Comment by chenzhekl** [comment]
There are equivalent functions in the C++ frontend already: [`torch::zeros`](https://pytorch.org/cppdocs/api/function_namespacetorch_1a746e0424e2489c4fbc21d090855f3114.html#exhale-function-namespacetorch-1a746e0424e2489c4fbc21d090855f3114). Similar functions like `torch::empty` and `torch::ones` are also available.

**Comment by npuichigo** [comment]
@chenzhekl It seems that with new_zeros, it's feasible to create a new tensor with layout and device same as another tensor.

Or maybe you mean that we can simply do like this?
```c++
auto input = torch.randn({1, 10});
auto new_tensor = torch.zeros({3, 4}, input.options());
```

**Comment by chenzhekl** [comment]
@npuichigo Oh, sorry, I misunderstood your needs. Probably [`torch::zeros_like`](https://pytorch.org/cppdocs/api/function_namespacetorch_1a29ac146b0f7a266c7a29ea3bca27334d.html#exhale-function-namespacetorch-1a29ac146b0f7a266c7a29ea3bca27334d) is what you need. The documentation for the C++ entry point is empty, though. According to the [Python doc](https://pytorch.org/cppdocs/api/function_namespacetorch_1a29ac146b0f7a266c7a29ea3bca27334d.html#exhale-function-namespacetorch-1a29ac146b0f7a266c7a29ea3bca27334d), it does what you need.

**Comment by npuichigo** [comment]
@chenzhekl Thanks for your reply. Sometimes we want to create a new tensor only with the same device and layout but with different shape, like tensor.new_zeros in [python doc](https://pytorch.org/docs/stable/tensors.html?highlight=new_zeros#torch.Tensor.new_zeros).

Does it suitable to create the tensor like what I described above? Namely, pass the options to the factory method of creating the new tensor.

**Comment by chenzhekl** [comment]
@npuichigo My bad... I think your code works. 

Though I have never used `new_zeros` in my code, I agree that aligning the C++ interface with the Python one is desirable.

**Comment by ezyang** [comment]
I've fixed a few of these, and the rest should just be mechanical. Previous fix PRs: https://github.com/pytorch/pytorch/pull/25475 https://github.com/pytorch/pytorch/pull/25583

It might be a little time before I get around to doing the rest: if someone wants to pick them up, go for it!

**Comment by yf225** [comment]
@npuichigo Would you be interested in adding `new_zeros` to C++ API, following https://github.com/pytorch/pytorch/pull/25475 and https://github.com/pytorch/pytorch/pull/25583 ? Thanks!

**Comment by ezyang** [comment]
@v0dro reassigned to you! This is definitely a good starter bug. Assign me as reviewer on your diffs.

**Comment by v0dro** [comment]
Sure thank you very much. I'll get started and let you know.

**Comment by rgommers** [comment]
`new_zeros` was done in gh-26511, `new_empty` was already done, so closing
