### ISSUE TITLE
master branch build gloo error

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#25846]
```
pytorch/torch/lib/c10d/ProcessGroupGloo.cpp:340:29: error: ‘gloo::transport::tcp’ has not been declared
   return ::gloo::transport::tcp::CreateDevice(attr);
pytorch/torch/lib/c10d/ProcessGroupGloo.cpp:340:47: error: ‘attr’ was not declared in this scope
   return ::gloo::transport::tcp::CreateDevice(attr);

```

Command:

```
python3 setup.py build --cmake
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pietern** [comment]
Can you provide more details as listed in the template?

For example, what OS, platform, PyTorch commit, etc, etc.

Thanks.

**Comment by pietern** [comment]
Also, did you check out a fresh copy of the repository or are you using an existing checkout?

If it's an existing checkout, can you confirm that the submodules have been updated?

**Comment by jinfagang** [comment]
I am totally confused now.

I am running this command:

```
USE_MKLDNN=0 USE_DISTRIBUTED=0 USE_C10D_GLOO=0 sudo python3 setup.py install --cmake
```

It throws out mkl not found error which I am already disabled it, and this gloo errro which I also disable.

It seems that, these variables does not have any effect????

**Comment by pietern** [comment]
I don't know about the MKL error (I suppose you filed #25849 for this).

The flag `USE_C10D_GLOO` is an internal one and you don't need to use it. If you don't want to build with distributed, setting `USE_DISTRIBUTED=0` is enough. If you are re-using a build directory from a previous commit, it is possible that the cached CMake variables are causing issues. Try removing the `build/` directory in the top level and retry (or run `git clean -fdx`, but beware that this nukes ALL local modifications to the repository and removes untracked files).

**Comment by jinfagang** [comment]
@pietern  Thanks for reply.

I have done rm -r build before every build.

```
10685  sudo rm -r build
10686  USE_MKLDNN=0 USE_DISTRIBUTED=0 USE_C10D_GLOO=0 sudo python3 setup.py install --cmake

```

It keeps give me mkl not found error. I am very confusing... Does there related file to this? I donn't really know how `setup.py` work. It seems every time I run `python3 setup.py install` it will build from scratch rather than resume building. It's very slow and cost a lot of time to test there commands.

However I can not disable mkl in the end.........even I tested several ways to disable it

**Comment by pietern** [comment]
@jinfagang So you're no longer seeing the Gloo build error? If so, we can close this issue and use #25849 for figuring out what's up with the MKL detection, to keep the issues properly separated.

**Comment by jinfagang** [comment]
@pietern  No..... it first got mkl error then gloo..... now I got mkl, this step can not pass and I can not move further to the gloo error......

**Comment by pietern** [comment]
Can you try running against a fresh checkout?

A similar issue was reported in #25851 and that was resolved with a clean checkout.

**Comment by jinfagang** [comment]
The problem is `sudo` incase anyone got this issue, pls using `sudo -E`
