### ISSUE TITLE
[cppdocs] the docs of class Tensor is missing

### ISSUE THREAD

**Issue by jimages** [pytorch/pytorch#25845]
## 📚 Documentation

After the 1.2 version of pytorch release, the torch::Tensor docs(original url:https://pytorch.org/cppdocs/api/classat_1_1_tensor.html) is missing. it does provide much helpful information about class torch::Tensor. 

It was there. (https://github.com/pytorch/cppdocs/blob/59620f68901b1e5f6bc2fa30c9ecbe8d0d86a1c4/api/classat_1_1_tensor.html) but in the latest commit, the file is absent.

It is really helpful for c++ development. Could you recovery it?

cc @ezyang @gchanan @zou3519 @yf225

**Comment by soumith** [comment]
cc: @yf225
