### ISSUE TITLE
Build Error : gloo::transport::tcp has not been declared

### ISSUE THREAD

**Issue by weixingsun** [pytorch/pytorch#25851]
## Issue description
I followed the instruction of Readme, but error keep poping up on latest master git 
../torch/lib/c10d/ProcessGroupGloo.cpp:340:29: error: ‘gloo::transport::tcp’ has not been declared
   return ::gloo::transport::tcp::CreateDevice(attr);
                             ^~~
../torch/lib/c10d/ProcessGroupGloo.cpp:308:29: error: ‘gloo::transport::tcp’ has not been declared
   return ::gloo::transport::tcp::CreateDevice(attr);

../torch/lib/c10d/ProcessGroupGloo.cpp:340:47: error: ‘attr’ was not declared in this scope
   return ::gloo::transport::tcp::CreateDevice(attr);
                             ^~~
../torch/lib/c10d/ProcessGroupGloo.cpp: In static member function ‘static std::shared_ptr<gloo::transport::Device> c10d::ProcessGroupGloo::createDeviceForHostname(const string&)’:
../torch/lib/c10d/ProcessGroupGloo.cpp:324:22: error: ‘gloo::transport::tcp’ has not been declared
   ::gloo::transport::tcp::attr attr;
                      ^~~
../torch/lib/c10d/ProcessGroupGloo.cpp:335:5: error: ‘attr’ was not declared in this scope
     attr.hostname = buffer.data();

../torch/lib/c10d/ProcessGroupGloo.cpp:39:2: error: #error "Expected the tcp transport to be available on Linux."
 #error "Expected the tcp transport to be available on Linux."
  ^~~~~
../torch/lib/c10d/ProcessGroupGloo.cpp: In static member function ‘static std::shared_ptr<gloo::transport::Device> c10d::ProcessGroupGloo::createDeviceForInterface(const string&)’:
../torch/lib/c10d/ProcessGroupGloo.cpp:306:22: error: ‘gloo::transport::tcp’ has not been declared
   ::gloo::transport::tcp::attr attr;
                      ^~~
../torch/lib/c10d/ProcessGroupGloo.cpp:307:3: error: ‘attr’ was not declared in this scope
   attr.iface = interface;
   ^~~~

## System Info

- PyTorch or Caffe2: pytorch
- Build command you used (if compiling from source): python setup.py build
- OS: Ubuntu 18.04
- PyTorch version: 1.3.0-master
- Python version:  3.7.3
- CUDA/cuDNN version: 9.1
- GPU models and configuration: p100
- GCC version (if compiling from source):  7.3.0
- CMake version: 3.14.0
- Versions of any other relevant libraries:
[pip3] numpy==1.16.4
[pip3] numpydoc==0.9.1
[pip3] torch==1.2.0
[pip3] torchaudio==0.3.0
[pip3] torchprof==0.3.1
[pip3] torchtext==0.4.0
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torchaudio                0.3.0                    pypi_0    pypi
[conda] torchprof                 0.3.1                    pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

I compiled 2 weeks ago, but failed now, so this should be something wrong with new codes
Thanks for advices!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pietern** [comment]
Thanks for the report. Did you build from scratch or re-ran a build with an existing build directory?

It is possible that left-over cached CMake variables from a previous build tainted the new one.

**Comment by weixingsun** [comment]
Thanks for looking into it, I just use following and:
git pull
rm -rf build
python setup.py build

**Comment by pietern** [comment]
Are your submodules up to date? 

To check, you can run `git status`. To update, you can run `git submodule update --init --recursive`.

**Comment by weixingsun** [comment]
@pietern thanks for your advices, I re-git the whole repo and it solved my problem, looks like there is something old files making this problem.

**Comment by pietern** [comment]
@weihuangxu Thanks for the update! Glad you got it sorted out.
