### ISSUE TITLE
TORCH_WARN must not take out GIL (should buffer warnings)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25859]
At the moment, we have an attractively named `TORCH_WARN` macro which you can use to report warnings from C++. What if I told you... that using this function could cause your code to take out a lock and all sorts of performance nastiness like that? Well, that's exactly what this macro does, because it calls a custom warning handler that, in the case of our Python extension, calls into Python code to file a Python warning. This is bad bad bad, for both performance reasons, and also because it could cause a deadlock (as to file a Python warning, we must acquire the GIL).

A better strategy is our Python handler must buffer warnings, and then when we (normally) return back to Python and acquire the GIL, actually report the warnings. The correct place to add this logic is probably where we also handle catching C++ exceptions and converting them into Python exceptions.

**Comment by colesbury** [comment]
I'm pretty ambivalent about this proposed change. I'm concerned that this will make the warnings less useful: if something fails in between the TORCH_WARN and the "normal" return, the warning won't be printed.

The potential performance pitfalls can be handled with a std::call_once, like we do [here](https://github.com/pytorch/pytorch/blob/d1496183f59b59928ac7003503591560716f21c5/aten/src/THC/THCBlas.cu#L205-L207). We shouldn't be spamming warnings for a good user experience anyways.

I don't see how warnings pose a deadlock issue that we wouldn't encounter anyways. The hazard appears to be that Python may acquire C++ land locks while still holding the GIL. This is unsafe regardless of TORCH_WARN. We have Tensor [destructors](https://github.com/pytorch/pytorch/blob/849c32f8e97af9f95e57b59d0db0aca6feced2d7/torch/csrc/utils/tensor_numpy.cpp#L167-L176) that acquire the GIL and it's hard to limit when/where those destructors may run.

**Comment by ezyang** [comment]
> if something fails in between the TORCH_WARN and the "normal" return, the warning won't be printed.

My thinking is that exception handling code that translates exceptions between C++ and Python would always flush warnings, even if there is an error. But it's true that if we segfault all warnings will be lost.

I could also be convinced that the warn macro should be warn once by default everyone in C++.

**Comment by colesbury** [comment]
> My thinking is that exception handling code that translates exceptions between C++ and Python would always flush warnings, even if there is an error.

Oh, that makes sense. That makes me feel much better about the approach.

**Comment by ezyang** [comment]
The PR that initially prompted this bug is #25319

**Comment by gchanan** [comment]
@albanD should this be closed?

**Comment by albanD** [comment]
Yes, the PR has been merged.
