### ISSUE TITLE
windows libtorch socket

### ISSUE THREAD

**Issue by zhjw0927** [pytorch/pytorch#25852]
My current state is under windoes, use libtorch and use network programming-socket.
But, I find that <WINSOCK2.H> conflicts with <torch/script.h>.
I am helpless now, who has good advice?
Thanks!

cc @yf225 @peterjc123

**Comment by pietern** [comment]
What is the conflict? Can you elaborate?

**Comment by zhjw0927** [comment]
Simply to say, error occurred in OperatorOptions.h.
vs smart reminder: 
Grammatical errors:"="                 OperatorOptions.h
constexpr function"c10::tostring" do not generate constant expressions

**Comment by zhjw0927** [comment]
Cpp only has the following statement：
#include<torch/script.h>
#include<WINSOCK2.H>
#pragma comment(lib,"WS2_32.lib")
int main()
{
    return 0;
}
Error occurred.
Hope to receive your reply， thank you!

**Comment by pietern** [comment]
I'm not a Windows dev, so we'll have to wait for @yf225 or @peterjc123 to chime in :)

**Comment by zhjw0927** [comment]
Yes，Thank you for attention！

**Comment by zhjw0927** [comment]
Where can download previous version of libtorch?

**Comment by peterjc123** [comment]
I cannot reproduce this issue with the steps in https://github.com/pytorch/pytorch/issues/25698#issuecomment-528747700. Maybe you need some add some macro definitions, like `NOMINMAX`.

**Comment by zhjw0927** [comment]
Thank you for solution very much.  
Success is because that  before cmake, <torch/script.h> and <WINSOCK2.H> were written  on cpp, right?

My previous practice was to specify the path of libtorch only in cmake, first complete the part of libtorch, and then add network programming, so it caused an error.

**Comment by peterjc123** [comment]
I don't think it has anything to do with the source file. I guess that you created the project manually by specifying include dirs and libs, but without using find_package(Torch), that's why some macros are not defined, which caused the conflict.
