### ISSUE TITLE
RuntimeError the size of the tensor don"t match

### ISSUE THREAD

**Issue by zakarianamikaz** [pytorch/pytorch#25853]
rand_embedding_tensor[word_dict[line[0]]] = torch.FloatTensor(vector)
RuntimeError: The expanded size of the tensor (300) must match the existing size (100) at non-singleton dimension 0.  Target sizes: [300].  Tensor sizes: [100]

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
