### ISSUE TITLE
Conflict description of JIT in master

### ISSUE THREAD

**Issue by Godricly** [pytorch/pytorch#25856]
## 📚 Documentation
The demo code in [Attribute](https://pytorch.org/docs/master/jit.html#attributes) and [FAQ](https://pytorch.org/docs/master/jit.html#frequently-asked-questions) question No. 2.
```
Q: How do I store attributes on a ScriptModule?
```
Both defines a int variable as int type. The FAQ one claims it as a compiling error.

cc @suo

**Comment by Chillee** [comment]
This is left over from the recursive scripting API change. @driazati

**Comment by suo** [comment]
Thanks for the report! @Chillee is right, the docs should be updated. Passing to @driazati

**Comment by Godricly** [comment]
Can I close this now?
