### ISSUE TITLE
a few hub improvements

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#25865]
- create a dummy repo and migrate `pytorch/pytorch` CI to use it instead of `pytorch/vision`.
- allow zipped checkpoint. 
cc: @fmassa @soumith 

cc @ailzhang

**Comment by pietern** [comment]
In #25930 I added a line to install pillow to make a hub test pass that imports torchvision.

Making a note here to remove that once these fixes land and the hub tests supposedly no longer transitively take a dependency on the `PIL` module.

https://github.com/pytorch/pytorch/pull/25930/files#diff-f50e65de2e1df486abf5cf0fc13f345dR23
