### ISSUE TITLE
cuda_empty_cache() cause device-side assert triggered error

### ISSUE THREAD

**Issue by guochengqian** [pytorch/pytorch#25873]
## To Reproduce
```
    del neg_adj
    if x.is_cuda:
        torch.cuda.empty_cache()
```
show error:
```
    torch.cuda.empty_cache()
  File "/home/qiang/anaconda3/envs/pointsr/lib/python3.7/site-packages/torch/cuda/__init__.py", line 426, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
```

## Environment
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN Xp

Nvidia driver version: 430.09
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[pip] torch-cluster==1.4.2
[pip] torch-geometric==1.3.0
[pip] torch-scatter==1.3.0
[pip] torch-sparse==0.4.0
[pip] torch-spline-conv==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] faiss-cpu                 1.5.3            py37h6bb024c_0    pytorch
[conda] faiss-gpu                 1.5.3            py37h32c130d_0    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] torch-cluster             1.4.2                    pypi_0    pypi
[conda] torch-geometric           1.3.0                    pypi_0    pypi
[conda] torch-scatter             1.3.0                    pypi_0    pypi
[conda] torch-sparse              0.4.0                    pypi_0    pypi
[conda] torch-spline-conv         1.1.0                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

This error did not appear in my training. When i was in testing, it appeared. But the memory did not exceed. Any advice?

**Comment by soumith** [comment]
this is because a previous device-side assert was triggered, and empty_cache is just synchronizing.
If you want exact location of the device assert, you can run with the environment variable `CUDA_LAUNCH_BLOCKING=1` set
