### ISSUE TITLE
mkl and gloo not able to disable

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#25901]
```
 USE_MKLDNN=0 USE_DISTRIBUTED=0 sudo python3 setup.py install --cmake

```

Output:

```
[  1%] Built target gloo
[  2%] Built target libprotobuf-lite
[  4%] Built target fbgemm_generic
[  4%] Built target asmjit
[  4%] Built target pthreadpool
[  7%] Built target libprotobuf
Scanning dependencies of target c10
[  7%] Built target ATEN_CPU_FILES_GEN_TARGET
[  7%] Built target mkalias
[  7%] Built target foxi_loader
[  7%] Built target caffe2_nvrtc
[  7%] Built target common
[  7%] Generating python/layers/split.py
[  7%] Built target mkrename
[  7%] Built target ATEN_CUDA_FILES_GEN_TARGET
[  7%] Built target mkdisp
[  7%] Built target mkrename_gnuabi
[ 20%] Built target arraymap
[ 29%] Built target mkldnn

```

I have no idea what is the right way to disable them.....................................

**Comment by ptrblck** [comment]
Cross post from forum: https://discuss.pytorch.org/t/pytorch-build-from-source-help/55600/2?u=ptrblck

@albanD's answer:
> I think the problem is that you use sudo. When you do this, it switch the environment to the root one, and so the env variable you define inline are not used.
In general, you don’t want to use sudo when you install pytorch. If you use linux, you can setup your rights to be in the staff group to be able to do global install without sudo. Or you can do a per-user install by adding a --user to the install command.

**Comment by jinfagang** [comment]
Problem solved. Big god found the root reason by a glimpse
