### ISSUE TITLE
Feature request: logsumexp

### ISSUE THREAD

**Issue by rdipietro** [pytorch/pytorch#2591]
The numerically stable version of `logsumexp` is simple but often useful. Thoughts on including this in PyTorch?

My thought is that it'd follow a call signature(s) that's similar to that of `sum`, but `logsumexp` wouldn't have the `out` keyword, and it'd also use the NumPy-consistent `keepdims` keyword instead of `sum`'s `keepdim` keyword. So

```
def logsumexp(inputs, dim=None, keepdims=False):
    ...
```

**Comment by dasguptar** [comment]
Just a couple of questions, might be extremely naive:
- Is this supposed to be differentiable? As in, if it is only going to be used in the `forward()` pass, then is a library function needed? I cannot think of a scenario where I might want to call `backward()` on this, so I'm asking if that is a concern.
- Why `keepdims` instead of `keepdim`? Let's keep the notation consistent across PyTorch!

**Comment by rdipietro** [comment]
Yes it should be differentiable :). Many use cases exist, one being mixture density networks.

I'm all for consistency. My best guess is that PyTorch accidentally used keepdim, but that they will strive for numpy consistency in the future. Same happened with TensorFlow. So my thought is that any new functionality should meet this goal in advance.

**Comment by gchanan** [comment]
We used keepdim because reduction functions in pytorch only support a single dimension.  There are plans/patches to change that, after which keepdims would be more appropriate.

**Comment by alshedivat** [comment]
Assuming that `log_softmax` is numerically stable, here is a one-line workaround:
```python
import torch.nn.functional as F

def logsumexp(inputs, dim=None, keepdim=False):
    return (inputs - F.log_softmax(inputs)).mean(dim, keepdim=keepdim)
```
Perhaps not very efficient for large sums, but it delegates everything to `log_softmax` as well as replicates its behavior (#1020). Having a native implementation down the line would nice though.

**Comment by jwvdm** [comment]
Here is an implementation that we wrote, which supports both variable and tensor inputs:
```
def log_sum_exp(value, dim=None, keepdim=False):
    """Numerically stable implementation of the operation

    value.exp().sum(dim, keepdim).log()
    """
    # TODO: torch.max(value, dim=None) threw an error at time of writing
    if dim is not None:
        m, _ = torch.max(value, dim=dim, keepdim=True)
        value0 = value - m
        if keepdim is False:
            m = m.squeeze(dim)
        return m + torch.log(torch.sum(torch.exp(value0),
                                       dim=dim, keepdim=keepdim))
    else:
        m = torch.max(value)
        sum_exp = torch.sum(torch.exp(value - m))
        if isinstance(sum_exp, Number):
            return m + math.log(sum_exp)
        else:
            return m + torch.log(sum_exp)
```
I agree that an implementation in C would be very helpful!

**Comment by MaigoAkisame** [comment]
I'm looking for this function as well. I'm implementing the CTC loss, and need to add lots of log probabilities.

**Comment by davidbau** [comment]
+1.  Additionally I have a situation where I need row-wise logsumexp on a sparse matrix (treating unstored entries as if they are -inf rather than zero).  I can't find any way to construct this to be done efficiently on the GPU.

**Comment by rdipietro** [comment]
Throwing my version here too. Not sure if there are any tradeoffs with the version above, though the name is consistent with scipy's `logsumexp`, it's a bit shorter, and `dim=None` works.

```
def logsumexp(inputs, dim=None, keepdim=False):
    """Numerically stable logsumexp.

    Args:
        inputs: A Variable with any shape.
        dim: An integer.
        keepdim: A boolean.

    Returns:
        Equivalent of log(sum(exp(inputs), dim=dim, keepdim=keepdim)).
    """
    # For a 1-D array x (any array along a single dimension),
    # log sum exp(x) = s + log sum exp(x - s)
    # with s = max(x) being a common choice.
    if dim is None:
        inputs = inputs.view(-1)
        dim = 0
    s, _ = torch.max(inputs, dim=dim, keepdim=True)
    outputs = s + (inputs - s).exp().sum(dim=dim, keepdim=True).log()
    if not keepdim:
        outputs = outputs.squeeze(dim)
    return outputs
```

**Comment by sytrus-in-github** [comment]
Yet another version that handles `inf` and `-inf` cases properly so that no `nan` appears. Requires `torch.where` from nightly build or work-around for version 0.3:
```python
# https://github.com/pytorch/pytorch/issues/2591
import torch

def logsumexp(x, dim=None, keepdim=False):
    if dim is None:
        x, dim = x.view(-1), 0
    xm, _ = torch.max(x, dim, keepdim=True)
    x = torch.where(
        (xm == float('inf')) | (xm == float('-inf')), 
        xm,
        xm + torch.log(torch.sum(torch.exp(x - xm), dim, keepdim=True)))
    return x if keepdim else x.squeeze(dim)
```
A possible `torch.where` work-around for version 0.3 which does not handle broadcasting:
```python
def where(cond, xt, xf):
    ret = torch.zeros_like(xt)
    ret[cond] = xt[cond]
    ret[cond ^ 1] = xf[cond ^ 1]
    return ret
```

**Comment by samuela** [comment]
Where is this at now? It seems like there are two competing implementations: torch.logsumexp and torch.distributions.utils.log_sum_exp but I can't find documentation for either of them.

Relevant: https://github.com/pytorch/pytorch/issues/8426

**Comment by samuela** [comment]
@soumith Oh awesome, thank you! Perhaps I was looking at docs for an older version.

**Comment by iiSeymour** [comment]
When trying to export a model that uses `torch.logsumexp` with `torch.onnx.export` the follow error is thrown *(pytorch 1.1.0)* -
> RuntimeError: ONNX export failed: Couldn't export operator aten::logsumexp

**Comment by MaigoAkisame** [comment]
@iiSeymour I have the same problem, and I had to write my own version of logsumexp for onnx.

**Comment by iiSeymour** [comment]
@MaigoAkisame if I write my own or use @rdipietro version I end up with `ATen` op in the graph such as  `onnx::ATen[dim=1, keepdim=1, operator="max"]` and the following warning:

> Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.

**Comment by MaigoAkisame** [comment]
@iiSeymour I get the same warning, but the resulting model seems to work fine.

**Comment by iiSeymour** [comment]
Under which runtimes/frameworks do you run inference on the export model?

**Comment by MaigoAkisame** [comment]
@iiSeymour This may be FB internal -- I take the onnx model and convert it to logfiledb format, then load it with a class called PredictorWsCached and run prediction.

**Comment by iiSeymour** [comment]
Should `torch.logsumexp` export to a `ReduceLogSumExp` node or a graph with `Max`, `Log`, `Exp`, `Sum`, `Squeeze`?

**Comment by MaigoAkisame** [comment]
@iiSeymour I don't know about this level of detail...

**Comment by iiSeymour** [comment]
So `torch.{max,min}(input, dim, keepdim)` has been fixed @lara-hdr here https://github.com/pytorch/pytorch/pull/19689, any ideas about `torch.logsumexp`?

**Comment by iiSeymour** [comment]
Okay so I think `logsumexp` is as simple as https://github.com/pytorch/pytorch/pull/22306.
