### ISSUE TITLE
Real-time performance issue about tensor.cpu()

### ISSUE THREAD

**Issue by cyfwry** [pytorch/pytorch#25915]
I have encountered difficulties in implementing a project that requires real-time performance. The entire network (composed of pre-processing (CPU) and post-processing (CPU) and model (GPU)) is not fast enough. After checking, I found:

1. The tensor.cpu() in post-processing consumes a lot of time (for the same tensor, the tensor.cuda() in the pre-processing uses 1ms, and the tensor.cpu() in the post-processing uses 20+ms) .

2. After the model, the first tensor.cpu() or tensor.cuda() will be very slow (20+ms), and then tensor.cpu() or tensor.cuda() will be very fast (1ms).

I am very curious about what did tensor.cpu() do and why did it take so long? Any suggestions can reduce the time of this step, or use other faster methods to retrieve data from the tensor?
My CPU is i7-9700k and the GPU is 2080 Ti.

**Comment by SsnL** [comment]
CUDA ops are generally async, i.e., each op you do gets pushed on to a queue that the GPU sequentially execute. So the time measurements could be misleading. And `.cpu()` is a synchronization point, i.e., it blocks until that queue is cleared.

**Comment by cyfwry** [comment]
I also found that the CPU is used up in the test. Does this mean that there is no other way to achieve real-time performance besides improving the performance of the CPU by add an another CPU?

In addition, I found an interesting phenomenon. When I import threading class to enable two threads to process two images at the same time, it is about 10% faster than continuously processing two images without multithreading, but using more threads won't make it faster. And in all cases the CPU resources are exhausted, which is not consistent with my understanding. Is this normal?

**Comment by cyfwry** [comment]
> CUDA ops are generally async, i.e., each op you do gets pushed on to a queue that the GPU sequentially execute. So the time measurements could be misleading. And `.cpu()` is a synchronization point, i.e., it blocks until that queue is cleared.

I also found that the CPU is used up in the test. Does this mean that there is no other way to achieve real-time performance besides improving the performance of the CPU by add an another CPU?

In addition, I found an interesting phenomenon. When I import threading class to enable two threads to process two images at the same time, it is about 10% faster than continuously processing two images without multithreading, but using more threads won't make it faster. And in all cases the CPU resources are exhausted, which is not consistent with my understanding. Is this normal?

**Comment by fmassa** [comment]
If you are measuring CUDA times, you need to add `torch.cuda.synchronize()` before the timing to more accurately measure the times, as pointed out by @SsnL.

We use GitHub issues to track bugs and feature requests.
Questions like this are more suited to the discussion forums http://discuss.pytorch.org
