### ISSUE TITLE
test_invalid_names is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#25912]
passed: https://circleci.com/gh/pytorch/pytorch/2714822?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

failed: https://circleci.com/gh/pytorch/pytorch/2721901?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
Sep 10 09:30:49 test_invalid_names (__main__.RpcTest) ... ERROR:root:Caught exception: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [172.17.0.2]:8356, exiting process with exit code: 10
Sep 10 09:30:49 FAIL
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by ezyang** [comment]
It's still flaky

https://circleci.com/gh/pytorch/pytorch/2766842?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mrshenli** [comment]
@ezyang this test should have been disabled on master, e.g.:

https://circleci.com/gh/pytorch/pytorch/2773025?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pietern** [comment]
Fixed in #28376.

**Comment by rohan-varma** [comment]
Reopening this issue since the test is flaky again.

**Comment by rohan-varma** [comment]
This should be re-fixed in https://github.com/pytorch/pytorch/pull/30620
