### ISSUE TITLE
Native function returning argument autograd hazard

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25927]
For benchmarking purposes, sometimes we make little native functions which don't do any tensor allocations:

```
Tensor _const5(const Tensor& self, const Tensor& second, const Tensor& third, const Tensor& fourth, const Tensor& fifth) {  return self;
}
```

This results in the following Variable code being generated:

```
  auto tmp = ([&]() {
    at::AutoNonVariableTypeMode non_var_type_mode(true);
    return at::_const5(self_, second_, third_, fourth_, fifth_);
  })();
  auto result = as_variable(std::move(tmp));
  if (grad_fn) {
      set_history(flatten_tensor_args( result ), grad_fn);
  }
```

The hazard is that if `grad_fn` is the same Tensor as `self`, we will mutate the input argument (bad bad).

User-defined autograd functions have an explicit check for when output aliases with input, but for native functions we just assume that people have written them correctly. This might not be a good assumption.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @yf225

**Comment by albanD** [comment]
@ezyang Do you mean tests similar to these ones: https://github.com/pytorch/pytorch/pull/16305 ?

**Comment by ezyang** [comment]
No, I think most of the time the functions I'm referring to never get checked in

**Comment by albanD** [comment]
Do you have a link where such functions are created? Where they are codegened?

Tests similar to the ones I linked would be added to **all** the codegened functions. So should be added to this as well.

**Comment by ezyang** [comment]
The workflow I'm thinking of is literally:

1. I want to benchmark a dispatcher change on a trivial function (no contents) with five arguments
2. I write `_const5` and add it to `native_functions.yaml`
3. I run my microbenchmark on this

If we added a `DEBUG` test similar to @yf225's change, that would certainly be a way to solve this problem.

**Comment by gchanan** [comment]
Probably the easiest thing to check is:
- For in place, we return the same tensor (we already do this in https://github.com/pytorch/pytorch/pull/16305/files)
- For view ops, we retain the same StorageImpl (add this)
- For non-view ops (and ops that don't explicitly modify the Storage, e.g. set_), check that the use_count of the output is 1.
