### ISSUE TITLE
Keyword argument of function torch.load() 'map_location' is ignored.

### ISSUE THREAD

**Issue by MarcoCBA** [pytorch/pytorch#25925]
Im currently working with FasterRCNN.
I trained the model inside an instance with GPU.
Then serialized it with:

`state_dict = pickle.dumps(model.state_dict())`

When I try to load it on a instance without a GPU device by using:

`device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')`
`st = torch.load(path, map_location=device)`

The following error pops up:

>  Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

This is the traceback (im using the lastest version of PyTorch):

---------------------------------------------------------------------------------------------------
RuntimeError                              
Traceback (most recent call last)
<ipython-input-47-59d6e42aeb2d> in <module>
----> 1 load(path + '/model')

<ipython-input-46-d882a9f87151> in load(path)
     15     model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
     16     device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
---> 17     st = torch.load(path, map_location=device)
     18     model.load_state_dict(st)
     19     model.to(device)

/usr/local/lib/python3.5/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    384         f = f.open('rb')
    385     try:
--> 386         return _load(f, map_location, pickle_module, **pickle_load_args)
    387     finally:
    388         if new_fd:

/usr/local/lib/python3.5/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    561             f.seek(0)
    562 
--> 563     magic_number = pickle_module.load(f, **pickle_load_args)
    564     if magic_number != MAGIC_NUMBER:
    565         raise RuntimeError("Invalid magic number; corrupt file?")

/usr/local/lib/python3.5/site-packages/torch/storage.py in _load_from_bytes(b)
    132 
    133 def _load_from_bytes(b):
--> 134     return torch.load(io.BytesIO(b))
    135 
    136 

/usr/local/lib/python3.5/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    384         f = f.open('rb')
    385     try:
--> 386         return _load(f, map_location, pickle_module, **pickle_load_args)
    387     finally:
    388         if new_fd:

/usr/local/lib/python3.5/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    571     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    572     unpickler.persistent_load = persistent_load
--> 573     result = unpickler.load()
    574 
    575     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

/usr/local/lib/python3.5/site-packages/torch/serialization.py in persistent_load(saved_id)
    534                 obj = data_type(size)
    535                 obj._torch_load_uninitialized = True
--> 536                 deserialized_objects[root_key] = restore_location(obj, location)
    537             storage = deserialized_objects[root_key]
    538             if view_metadata is not None:

/usr/local/lib/python3.5/site-packages/torch/serialization.py in default_restore_location(storage, location)
    117 def default_restore_location(storage, location):
    118     for _, _, fn in _package_registry:
--> 119         result = fn(storage, location)
    120         if result is not None:
    121             return result

/usr/local/lib/python3.5/site-packages/torch/serialization.py in _cuda_deserialize(obj, location)
     93 def _cuda_deserialize(obj, location):
     94     if location.startswith('cuda'):
---> 95         device = validate_cuda_device(location)
     96         if getattr(obj, "_torch_load_uninitialized", False):
     97             storage_type = getattr(torch.cuda, type(obj).__name__)

/usr/local/lib/python3.5/site-packages/torch/serialization.py in validate_cuda_device(location)
     77 
     78     if not torch.cuda.is_available():
---> 79         raise RuntimeError('Attempting to deserialize object on a CUDA '
     80                            'device but torch.cuda.is_available() is False. '
     81                            'If you are running on a CPU-only machine, '

**Comment by daikiclimate** [comment]
@MarcoCBA 
Hi. I have same issue.
How did you solve it?
Thanks

**Comment by MarcoCBA** [comment]
I was serializing the model with pickle directly instead of saving the model with "torch.save(state_dict)"
