### ISSUE TITLE
Request for distribute trainng example

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#2594]
Hi everyone
     Pytorch supports distribute trainning, but there is still no distribute trainning example, I searched the internet and found no related example. Will someone share this example? thansk.

**Comment by fmassa** [comment]
ImageNet example has support for distributed training, see https://github.com/pytorch/examples/tree/master/imagenet

**Comment by gmyofustc** [comment]
@fmassa this really helps me, thanks a lot
