### ISSUE TITLE
module.apply() might fail  in some cases

### ISSUE THREAD

**Issue by skrish13** [pytorch/pytorch#2595]
Won't [this](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L163) fail for cases where there are Sequential modules inside Sequential modules according to the behaviour of `.children()` as explained [here](https://discuss.pytorch.org/t/module-children-vs-module-modules/4551/4).

If so, should I change it to `self.modules()` and open a PR?

**Comment by ruotianluo** [comment]
Apply is executed recursively.

**Comment by skrish13** [comment]
oops, didnt realize children would return but just wont go into the sub module
