### ISSUE TITLE
Torch binary has bad hash file

### ISSUE THREAD

**Issue by ity** [pytorch/pytorch#2596]
wheel files contain hashes of all of their contents. we have started strictly checking these in our builds. torch is failing with a bad hash for file  'torch/lib/libTHCS.so.1'. So it looks like the distribution wheel torch-0.2.0.**post3**-cp27-cp27mu-linux_x86_64.whl does not contain the right hash. I have also checked torch-0.2.0.**post1**-cp27-cp27mu-linux_x86_64.whl and it has the same issue. 

Are you able to re-publish the corrected wheel?

```
   Dumping requirement: PythonRequirement(torch==0.2.0.post3)
                     Dumping requirement: PythonRequirement(numpy==1.13.1)
                     Dumping distribution: .../PyYAML-3.12-cp27-cp27m-macosx_10_4_x86_64.whl
                     Dumping distribution: .../torch-0.2.0.post3-cp27-none-macosx_10_7_x86_64.whl
                     Dumping distribution: .../numpy-1.13.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
                     Dumping distribution: .../PyYAML-3.12-cp27-none-linux_x86_64.whl
                     Dumping distribution: .../torch-0.2.0.post3-cp27-cp27mu-linux_x86_64.whl
               Waiting for background workers to finish.
13:52:22 00:42   [complete]
               FAILURE
Exception caught: (<class 'wheel.install.BadWheelFile'>)

Exception message: Bad hash for file 'torch/lib/libTHCS.so.1'
```

**Comment by soumith** [comment]
i can fix this and republish. what tool are you using to check for this requirement (and do you by any chance know where these hashes are located in the wheel).

The reason there are bad hashes is because once the wheel is generated, i repair it further manually.

**Comment by kwlzn** [comment]
here's a minimal repro using the manylinux docker image + the `wheel` cli tool:

```
[omerta ~]$ docker run --rm -i -t quay.io/pypa/manylinux1_x86_64 /bin/sh -i
sh-3.2# wget -q http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl
sh-3.2# /opt/python/cp27-cp27mu/bin/wheel install torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl --force
Traceback (most recent call last):
  File "/opt/python/cp27-cp27mu/bin/wheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/site-packages/wheel/tool/__init__.py", line 356, in main
    args.func(args)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/site-packages/wheel/tool/__init__.py", line 299, in install_f
    args.wheel_dirs, args.force, args.list_files)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/site-packages/wheel/tool/__init__.py", line 221, in install
    wf.install(force=force)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/site-packages/wheel/install.py", line 351, in install
    shutil.copyfileobj(source, destination)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/zipfile.py", line 692, in read1
    self._update_crc(data, eof=eof)
  File "/opt/_internal/cpython-2.7.13-ucs4/lib/python2.7/site-packages/wheel/install.py", line 463, in _update_crc
    raise BadWheelFile("Bad hash for file %r" % ef.name)
wheel.install.BadWheelFile: Bad hash for file 'torch/lib/libTHC.so.1'
```

it would seem someone/something is modifying the wheel after construction without updating it's hash records.

**Comment by soumith** [comment]
thanks for the repro. this should be sufficient for me to fix the hashes.

**Comment by kwlzn** [comment]
and afaik, wheel hashes are stored in the dist-info dirs `RECORD` file:

```
sh-3.2# unzip -p torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl torch-0.2.0.post3.dist-info/RECORD | grep torch/lib/libTHC.so.1
torch/lib/libTHC.so.1,sha256=bV7nnfy_NgT67MGE_b4t4iWR285M1kVBpL6F-u4quiU,271135764
```

thanks!

**Comment by kwlzn** [comment]
and in case folks are wondering why this has never come up in the past with `pip`: https://github.com/pypa/pip/issues/4705

**Comment by ity** [comment]
@soumith any update on this? I am blocked on this to do an internal upgrade at twitter. please let me know if I can help with anything. thanks

**Comment by alykhantejani** [comment]
@soumith I *think* this should be quite simple to fix with some bash magic in the build script. 

The issue is that we (pytorch) run `patchelf` on `libTHS` etc. and then re-zip up the wheel, which makes the hashes for these files invalid. 

All we would need to do is edit the lines of the libraries we touch in `RECORD` with the new hash which can be generated by 

```bash
openssl dgst -sha256 -binary torch/lib/libTHNN.1.dylib | openssl base64
```
However this still has trailing `=` signs (which the [PEP standard](https://www.python.org/dev/peps/pep-0427/#the-dist-info-directory) says should be removed

**Comment by soumith** [comment]
I'll fix the records tonight. didn't realize this was an immediate blocker.

**Comment by alykhantejani** [comment]
@soumith I've sent a [PR ](https://github.com/pytorch/builder/pull/6) to `builder` which should fix this (by regenerating the `RECORD` file). Not sure if this also needs to be done for the OSX wheel.

**Comment by soumith** [comment]
the binaries have been reuploaded with the correct hashes in RECORD. They pass the install with the `wheel` utility.

**Comment by kwlzn** [comment]
thanks!

**Comment by ity** [comment]
@soumith @alykhantejani  thanks for working on this!
