### ISSUE TITLE
Error when using `quantized_linear_per_channel` inside `aten/src/Aten/native/quantized/cpu`

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#25962]
## 🐛 Bug

Calling the `quantize_linear_per_channel` function results in the following error - 
```
RuntimeError: Expected object of type Variable but found type CPUFloatType for argument #1 'scales' (checked_cast_variable at caffe2/torch/csrc/autograd/VariableTypeManual.cpp:38)
```
## To Reproduce

1. Replace `quantized_linear_per_channel_cpu` with `quantized_linear_per_channel` in qconv.cpp. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv.cpp#L145
2. Run `python test/test_quantized_nn_mods.py test_conv_api` 

## Expected behavior

It looks like quantize_linear_per_channel dispatches to VariableType dispatcher, which expects the input tensor to be a Variable. 

The error suggests that we are missing a at::AutoNonVariableTypeMode thread-local guard somewhere in the call path of QLinearInt8 operator(). cc @jerryzh168 @jianyuh @dzhulgakov @yf225 

cc @jerryzh168 @dskhudia 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by raghuramank100** [comment]
Closing this issue as we cannot repro this error anymore and the code has been rewritten significantly from the time this issue was raised
