### ISSUE TITLE
Slicing behaviour in torch

### ISSUE THREAD

**Issue by sachinruk** [pytorch/pytorch#25983]
## To Reproduce

```
x = torch.randn(5, 3, 2)
first = x[:,:1,:1]
print(first.mean())
x[...,:1] = x[...,:1] - first
print(first.mean())
```
outputs: 
```
tensor(-0.0770)
tensor(0.)
```
Whereas if I do
```
x = torch.randn(5, 3)
first = x[:,:1]
print(first.mean())
x = x - first
print(first.mean())
```
outputs:
```
tensor(0.5736)
tensor(0.5736)
```
To summarise, in the first block, first is being reassigned the first column of x when we subtract `first` from `x`. However, in the second example, a copy is being created, hence the mean is exactly the same.

## Expected behaviour
I would have thought that even in the first block a copy is created when assigning to the variable `first` instead of being passed by reference. If this is the intended behaviour I do apologise but does feel slightly inconsistent?

## Environment

- PyTorch version: 1.1.0
- Is debug build: No
- CUDA used to build PyTorch: None

- OS: Mac OSX 10.14.5
- GCC version: Could not collect
- CMake version: version 3.12.4

- Python version: 3.6
- Is CUDA available: No
- CUDA runtime version: No CUDA
- GPU models and configuration: No CUDA
- Nvidia driver version: No CUDA
- cuDNN version: No CUDA

Versions of relevant libraries:
- [pip3] msgpack-numpy==0.4.3.2
- [pip3] numpy==1.16.4
- [pip3] torch==1.1.0
- [pip3] torchvision==0.3.0
- [conda] blas                      1.0                         mkl
- [conda] mkl                       2019.4                      233
- [conda] mkl-service               2.0.2            py36h1de35cc_0
- [conda] mkl_fft                   1.0.12           py36h5e564d8_0
- [conda] mkl_random                1.0.2            py36h27c97d8_0
- [conda] pytorch                   1.1.0                   py3.6_0    pytorch
- [conda] torchvision               0.3.0             py36_cuNone_1    pytorch

**Comment by ngimel** [comment]
In both cases `first` is a view into `x` tensor and thus shares data with `x`. However, in the second case you reassign `x` in `x=x-first`, thus original `x` is never modified, and first retains the data that was in  `x` originally. If you did this operation by modifying x inplace (e.g. `x.sub_(first)` or, as in the first case, `x[...,:1] = x[...,:1] - first`), the result would also be 0. Does this make sense?

**Comment by fmassa** [comment]
Closing as comment from @ngimel , as this is expected behavior.
