### ISSUE TITLE
inplace fill for indexed tensor doesn't work

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2599]
import torch
x=torch.randn(4)
x[[1,3]].fill_(100) #not changing x
x[[1,3]]begs #works

Is this behavior expected?

**Comment by apaszke** [comment]
It is. Advanced indexing always returns tensors that don't share storage with the source. The only exception is assignment that involves advanced indexing. `x[[1,3]].fill_(1000)` is a chain of two independent operations, while `x[[1, 3]] = 1000` calls `x.__setitem__([1, 3], 1000)`, so it is performed "atomically"
