### ISSUE TITLE
"Unexpected bus error" with 100s of GB of /dev/shm space available

### ISSUE THREAD

**Issue by anands-repo** [pytorch/pytorch#26009]
I am using pytorch 1.1.0 in a docker container with --ipc=host, so I have /dev/shm space of 254GB. My training script runs for two epochs (went through the complete set of training and validation data twice) and at the start of the third epoch, crashed with the error "ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)." I also had a shell script running in parallel which would poll /dev/shm's size every second. The script didn't detect /dev/shm usage of more than 1GB at any point in time (the memory system would need speeds upwards of 250GB/s or more to escape the script's detection, which is not possible as of today).

Has anyone else noticed such issues before? From what I can tell from multiple runs, this failure happens randomly.

cc @SsnL

**Comment by fmassa** [comment]
I have had this problem recently as well, but it was not deterministic and re-running the training worked fine the next time.

Maybe @SsnL has better ideas of what might have happened

**Comment by anands-repo** [comment]
Agreed. It is not deterministic. Also this error was not encountered with version pytorch 0.4.1.

**Comment by anands-repo** [comment]
Update: My current understanding is that this has nothing to do with pytorch. I noticed that the volume mounted in the docker container (containing the training data) becomes unavailable for a few seconds, and the files in the directory give a "stale file handle" error during that interval. This leads to bus error in the workers. Closing the issue.
