### ISSUE TITLE
Torch.nonzero() leads to crash in PyTorch 1.2

### ISSUE THREAD

**Issue by bwang-delft** [pytorch/pytorch#26038]
The code snippet works fine in 1.1 but causes an error in 1.2:
> p = F.softmax(x, dim=1)
> m = y != self.ignore_index
> t = F.one_hot((y * m.byte()).long(), num_classes=self.num_classes).byte().permute(0,3,1,2)
> i = (p * (t * m.unsqueeze(1).byte()).float()).sum((0,2,3))
> u = ((p + t.float()) * m.unsqueeze(1).float()).sum((0,2,3)) - i
> v = u.nonzero()
> return -((i[v] / u[v]).mean()).log()

I get the error message below:

> RuntimeError: range.second - range.first == t.size() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/autograd/generated/Functions.cpp:55, please report a bug to PyTorch. inconsistent range for TensorList output

I had to remove the usage of nonzero() like below to make the code work:
> p = F.softmax(x, dim=1)
> m = y != self.ignore_index
> t = F.one_hot((y * m.byte()).long(), num_classes=self.num_classes).byte().permute(0,3,1,2)
> i = (p * (t * m.unsqueeze(1).byte()).float()).sum((0,2,3))
> u = ((p + t.float()) * m.unsqueeze(1).float()).sum((0,2,3)) - i
> return -((i / u).mean()).log() 

I have two questions:
(1) Why does the runtime error happen in 1.2 but not in 1.1?
(2) By not using nonzero to prevent division by zero I have numeric instability in theory. However, in really the number that comes out from a softmax operation should not reach zero because the input can't really reach negative infinity right?

cc @ezyang @gchanan @zou3519 @SsnL @albanD

**Comment by fmassa** [comment]
@bwang-delft can you write a self-contained example (with dummy input tensors) that reproduce the behavior?
Without it it is very hard to trace back where the problem comes from.

**Comment by bwang-delft** [comment]
Below is a self-contained example:

    
    import torch
    import torch.nn as nn
    import torch.nn.functional as F

    def loss_func(p, y, ignore_index=255, num_classes=19):
         p = F.softmax(x, dim=1)
         m = y != ignore_index
         t = F.one_hot((y * m.byte()).long(), num_classes=num_classes).byte().permute(0,3,1,2)
         i = (p * (t * m.unsqueeze(1).byte()).float()).sum((0,2,3))
         u = ((p + t.float()) * m.unsqueeze(1).float()).sum((0,2,3)) - i
         v = u.nonzero()
         return -((i[v] / u[v]).mean()).log()

    x = torch.rand(1,19,1024,2048, requires_grad=True).to(‘cuda’).float()
    y = torch.randint(0, 18, (1,1024,2048)).to(‘cuda’).byte()
    y[0][0][0] = 255

    loss = loss_func(x, y)
    loss.backward()

**Comment by VitalyFedyunin** [comment]
Between 1.1.0 and master something was changes in `nonzero` and it now requires grad (it should not). It need to be disabled.
