### ISSUE TITLE
Kernel/Driver panic with DataParallel

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pytorch/pytorch#2603]
Hello,

I ran into a problem today. When running a certain model with DataParallel the machine constantly crash. When I run without DataParallel I get an OOM error. I know it's my fault that I tried to allocate too much memory and I found where my problem was but I think crashing the machine should be avoided. What can of information can I give you so you could track down the problem and generate an error message instead of a reboot.

**Comment by GuillaumeLeclerc** [comment]
Even after reducing the memory needed. It still crash the machine with DataParallel and is fine without. I have no clue what is happening. `dmesg` and journalctl shows nothing that capture my attention

**Comment by apaszke** [comment]
What do you mean by "crashing the machine"? Do you mean that it just reboots?

**Comment by GuillaumeLeclerc** [comment]
Exactly

**Comment by fmassa** [comment]
Did you check to see if your machine was overheating?

**Comment by GuillaumeLeclerc** [comment]
It was not overheating and it crashed at the first epoch of the training.

**Comment by GuillaumeLeclerc** [comment]
The problem was power supply related. Using DataParallel introduced a correlation between the two GPU usage and spikes in power consumption just shut down the machine.
