### ISSUE TITLE
[jit] Bool list isn't being created in python -> script conversion

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#26036]
We should probably just delete `BoolList` entirely since it's not used

```python
@torch.jit.script
def fn(x: List[bool]):
    x.clear()

fn([True, False])
```

```
RuntimeError: isBoolList() INTERNAL ASSERT FAILED at ../aten/src/ATen/core/ivalue_inl.h:551, please report a bug to PyTorch. Expected BoolList but got GenericList
The above operation failed in interpreter, with the following stack trace:
at <string>:3:4
def bool_list(x):
    # type: (List[bool])
    x.clear()
    ~~~~~~~ <--- HERE
```

cc @suo

**Comment by eellison** [comment]
Running into this too..

**Comment by eellison** [comment]
> We should probably just delete `BoolList` entirely since it's not used
> 
> ```python
> @torch.jit.script
> def fn(x: List[bool]):
>     x.clear()
> 
> fn([True, False])
> ```
> 
> ```
> RuntimeError: isBoolList() INTERNAL ASSERT FAILED at ../aten/src/ATen/core/ivalue_inl.h:551, please report a bug to PyTorch. Expected BoolList but got GenericList
> The above operation failed in interpreter, with the following stack trace:
> at <string>:3:4
> def bool_list(x):
>     # type: (List[bool])
>     x.clear()
>     ~~~~~~~ <--- HERE
> ```
> 
> cc @suo

This is just not binded in `pybind_utils`
