### ISSUE TITLE
[ONNX] Attach a random name to nodes

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26035]
## 🐛 Bug

Please set a random name to all the nodes, for debugging, when opening in netron

## To Reproduce

Get an error like

> Error: Type 'tensor(bool)' of input parameter (253) of operator (Gather) in node () is invali

## Expected behavior

To have a pointer to see which node has issue

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

This script helps to add thsoe names manually, thanks to @hariharans29 

```python
model = onnx.load("file.onnx")
graph = model.graph
nodes = graph.node

count = 0
for node in nodes:
    if not node.name:
        node.name = "rand_node_name_" + str(count)
        count = count + 1
```

**Comment by spandantiwari** [comment]
This has been added in https://github.com/pytorch/pytorch/pull/27342.
