### ISSUE TITLE
TorchScript doesn't handle submodule being None

### ISSUE THREAD

**Issue by dzhulgakov** [pytorch/pytorch#26067]
## 🐛 Bug

If one of the submodules is None, TorchScript doesn't recognize it as an attribute, unless explicitly specified in `__constants__` lists.

Obviously, if it's just a plain attribute, it might be necessary to additionally annotate it. But it doesn't work even if explicit `add_module` call is made.

## To Reproduce

```python
class MyModule(torch.nn.Module):
    # __constants__ = ['sub'] # adding just this line works
    def __init__(self, sub):
        super(MyModule, self).__init__()
        # either of the following lines fails
        self.add_module('sub', sub)
        # or
        self.sub = sub
    
    def forward(self, x):
        x = x.relu()
        if self.sub is not None:
            x = self.sub(x)
        return x+1

m1 = MyModule(torch.nn.ReLU())
m2 = MyModule(None)
print(m1(torch.rand(5)))
print(m2(torch.rand(5)))
print(torch.jit.script(m1).code) # succeeds
print(torch.jit.script(m2).code) # fails
```
Error:
```
RuntimeError: 
module has no attribute 'sub':
at <ipython-input-33-82f6eee81215>:12:11
    def forward(self, x):
        x = x.relu()
        if self.sub is not None:
           ~~~~~~~~ <--- HERE
            x = self.sub(x)
        return x+1
```

## Additional context

It's a pretty common pattern, e.g. in TorchVision: https://github.com/pytorch/vision/blob/a129b6b86a75f2d1fc80055f2cd0fae63efc0d2d/torchvision/models/resnet.py#L110

cc @suo

**Comment by dzhulgakov** [comment]
Looks like it's a known issue actually - https://github.com/pytorch/vision/pull/1270 cc @eellison

**Comment by dzhulgakov** [comment]
Thanks! We should update torchvision once this lands (cc @raghuramank100 )

**Comment by suo** [comment]
This is fixed in a number of ways (nonetype refinement now works, optional modules are "allowed" in the script frontend, etc.)
