### ISSUE TITLE
DataLoader workers fail to die

### ISSUE THREAD

**Issue by MicaelCarvalho** [pytorch/pytorch#26072]
## 🐛 Bug

_Disclaimer: This bug is hard to reproduce; I am running experiments in a cluster which is, at the moment, experiencing heavy usage [it uses slurm for job management], and I need to run multiple experiments in parallel for this to happen once or twice. It started happening randomly without any upgrade in the libraries or Python version._

The main symptom of this is that `for i, batch in enumerate(data_loader)` randomly freezes forever at the end of an epoch. Sending a SIGINT to the process reveals the stack is blocked [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L906).

Further investigation revealed that [this line](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L860) is being executed, but the worker never detects the kill signal, and the procedures inside [this line](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/worker.py#L163) are never reached.

Manually calling `w.terminate()` works, but this is a hack. My best guess at the moment is that the signal from `q.put(None)` [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L860) gets lost for some reason, and this is code from multiprocessing.Queue, not particularly PyTorch.

## To Reproduce

- Launch experiment with multiple threads on the DataLoader in an environment that is under heavy usage.

Hard to reproduce.

## Expected behavior

Expect it not to freeze, workers should just die.

## Environment

PyTorch version: 1.2.0+cu92
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 396.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] numpydoc==0.7.0
[pip3] torch==1.2.0+cu92
[pip3] torchvision==0.4.0+cu92
[conda] mkl                       2018.0.0             hb491cac_4
[conda] mkl-service               1.1.2            py36h17a0993_4
[conda] torch                     1.2.0+cu92               pypi_0    pypi
[conda] torchvision               0.4.0+cu92               pypi_0    pypi

## Considered solutions

There are a few solutions we could consider to this problem:
1. Modify [this code](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L906) to:
```
w.join(15.0) # timeout in 15s
if w.is_alive():
    w.terminate()
```
Drawback: defeats PyTorch control of the threads, and also doesn't execute the destroying procedures of the thread (closing queues etc). Can be manually fixed by adding the closing procedures here, but it duplicates code and creates extra complexity.
Pros: It works.

2. Modify [this code](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L906) to:
```
while True:
    self._workers[wid].join(15.0) # timeout in 15s
    if self._workers[wid].is_alive():
        self._workers_status[wid] = True
        self._shutdown_worker(wid)
    else:
        break
```
Pros: This would keep PyTorch control over the threads, and use the underlying system to kill the thread.
Drawback: Does not work. Signal simply never reaches the thread at all.

## Approaches

I tried putting a lot of debugging messages on `_shutdown_workers`, `_shutdown_worker`, and `_worker_loop`. I could not detect why this signal was being lost. The only visible effect is that the `None` never gets to the thread, and putting the print statements on these functions apparently changes their behaviour and the bug starts happening in the middle of the epoch too, instead of only at the beginning.

cc @SsnL

**Comment by wandering007** [comment]
It seems I am also faced with the same issue in PyTorch 1.4.0. It is really hard to figure out the reason...

**Comment by SsnL** [comment]
Thanks for reporting and the investigation!  Could you let me know
+ the exact DataLoader options
+ whether the epoch finishes, or was jumped out, say, via a `break`.

**Comment by SsnL** [comment]
I tried to reproduce with a dummy dataset and uncovered another problem. While it seems unrelated with your case, you could try the fix here and see if it helps: https://github.com/pytorch/pytorch/pull/33721

**Comment by wandering007** [comment]
@SsnL Thanks! I've tried the fix but it didn't help. I can provide the traceback information when I manually stop the process:

```
Traceback (most recent call last):
  File "imagenet_demo.py", line 286, in <module>
    for j, (data1, data2) in enumerate(tqdm(dataloader)):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 830, in _next_data
    self._shutdown_workers()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 942, in _shutdown_workers
    w.join()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
```
I'll try to get more debug information. Thanks!

**Comment by MicaelCarvalho** [comment]
I finished that project a while ago and haven't touched that code again. I also don't have access to the same cluster anymore; and haven't re-detected the problem ever since. All the investigation I did back then is reported in the thread, unfortunately I don't have any new data to share.
