### ISSUE TITLE
Remove use of Variable wrapper in test files?

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#26071]
## Issue description

Tensors and Variables have been the same thing since PyTorch 0.4, but I came across many test files that wrap `Tensors` in `Variable`s. One such example is the code in `test/test_nn.py`. It seems like it would be useful to get rid of these calls so that the old patterns aren't followed when writing new tests, and the tests can stay up to date. At the very least the tests would better reflect current Pytorch patterns.

If there's agreement about this I'll submit a PR removing these wrapper calls, starting with `test_nn.py`.

**Comment by soumith** [comment]
go for it!
