### ISSUE TITLE
[ONNX] Export boolean indexing using where instead of Gather

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26103]
## 🐛 Bug

Boolean indexing is not supported in ONNX and the [exported models are invalid](https://github.com/microsoft/onnxruntime/issues/1807), as suggested by ONNX instead of Gather [use where to export to onnx](https://github.com/onnx/onnx/issues/2302)

## To Reproduce

```python
idx = b > 0.5
c = d[idx]
```

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Workaround is to avoid boolean indexing and use `where` and `nonzero`, but if boolean indexing is already used using `Gather` is incorrect. Another solution is for `Gather` to accept boolean indexing.

**Comment by neginraoof** [comment]
Another workaround is to use: c = torch.masked_select(d, b.gt(0.5))
This is the PR for masked_select: https://github.com/pytorch/pytorch/pull/25949/files

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
