### ISSUE TITLE
DataParallel only can backwards when gpu id starts from 0

### ISSUE THREAD

**Issue by shuten-douji** [pytorch/pytorch#2610]
I'm trying to use dataparallel in multi-gpu, but get trouble in backward if I set the device_ids to [5, 6] other than [0, 1].Here's the code:

`
    import torch
    import torch.nn as nn
    from torch.autograd import Variable

    class select(nn.Module):
        def __init__(self):
            super(select, self).__init__()
            self.conv = nn.Conv2d(1, 1, kernel_size=1)

        def forward(self, x):
            print x
            return self.conv(x)

    model = select().cuda(5)
    c = nn.L1Loss().cuda(5)
    model = nn.DataParallel(model, device_ids=[5, 6])
    x = Variable(torch.Tensor(torch.randn(2, 1, 3, 3)))
    output = model(x)
    y = c(output, x.cuda(5, async=True))
    print y
    y.backward()
`

The error information is:

Variable containing:
(0 ,0 ,.,.) = 
  0.0397 -0.7899  0.0385
 -0.2171 -0.5417 -0.2214
  0.1241  0.0371 -0.0182
[torch.cuda.FloatTensor of size 1x1x3x3 (GPU 5)]
Variable containing:
(0 ,0 ,.,.) = 
  0.5447 -0.9738  0.4060
 -1.8595 -0.1073  0.2626
 -1.5308 -0.8662  0.4490
[torch.cuda.FloatTensor of size 1x1x3x3 (GPU 6)]

Variable containing:
 1.1432
[torch.cuda.FloatTensor of size 1 (GPU 5)]

Traceback (most recent call last):
  File "/home/sby/workspace/Cnn3d/test/test_dataparallel.py", line 21, in <module>
    y.backward()
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 25, in backward
    return comm.reduce_add_coalesced(grad_outputs, self.input_device)
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 122, in reduce_add_coalesced
    result = reduce_add(flattened, destination)
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/cuda/comm.py", line 92, in reduce_add
    nccl.reduce(inputs, outputs, root=destination)
  File "/home/sby/anaconda2/lib/python2.7/site-packages/torch/cuda/nccl.py", line 161, in reduce
    assert(root >= 0 and root < len(inputs))
AssertionError

Process finished with exit code 1

But the code runs well if it is like:
`
    import torch
    import torch.nn as nn
    from torch.autograd import Variable

    class select(nn.Module):
        def __init__(self):
            super(select, self).__init__()
            self.conv = nn.Conv2d(1, 1, kernel_size=1)

        def forward(self, x):
            print x
            return self.conv(x)

    model = select().cuda(0)
    c = nn.L1Loss().cuda(0)
    model = nn.DataParallel(model, device_ids=[0, 1])
    x = Variable(torch.Tensor(torch.randn(2, 1, 3, 3)))
    output = model(x)
    y = c(output, x.cuda(0, async=True))
    print y
    y.backward()
`

**Comment by allenye0119** [comment]
You can run your script with `CUDA_VISIBLE_DEVICES=5,6 python your_script.py` or set the environment variable in the script by `os.environ['CUDA_VISIBLE_DEVICES'] = '5,6'` to map GPU 5, 6 to device_ids 0, 1, respectively.

**Comment by shuten-douji** [comment]
thanks for the solution. I'll close this issue
