### ISSUE TITLE
 lstm module with None in input on CUDA segfaults.

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#26107]
This segfaults but works in CPU. 

```
import torch
import torch.nn as nn
import pdb


device='cuda'
m = nn.LSTM(3, 4, bidirectional=True, num_layers=2).to(device)
a = torch.rand(5, 3).to(device)
b = torch.tensor([1, 1, 1, 1, 1], device=device)
input = nn.utils.rnn.PackedSequence(a, b)

out = m(input, None)

print(out)
```
This is a testcase from our test suite but only ran on CPU, it's similar to https://github.com/pytorch/xla/issues/927 but I've confirmed they fail for different reasons. In CUDA it's segfaulting in `_cudnn_rnn`. 
cc: @gchanan 

cc @ezyang @gchanan @zou3519

**Comment by gchanan** [comment]
is this a result of the data_ptr issue?

**Comment by zou3519** [comment]
Probably not. The data_ptr issue is that we are accessing `batch_sizes` with `data_ptr`. `batch_sizes` only gets used when the input is PackedSequence. In this example, we're not using PackedSequence.

**Comment by ailzhang** [comment]
This is related to the issue, because in the example `b` should have been a CPU tensor. 
We could close this issue as it's currently guarded by the device assert in python side now.  :D

**Comment by zou3519** [comment]
Oh, sorry, I read the repro completely wrong, there is a PackedSequence and it's being created with a CUDA tensor. Thank you for fact checking me, @ailzhang! If we're confident that the above example doesn't segfault without PackedSequence, then we should close this.
