### ISSUE TITLE
nn.ConvTranspose2d use 49x more memory on a V100 than on a 2080Ti

### ISSUE THREAD

**Issue by MatthieuBizien** [pytorch/pytorch#26112]
## 🐛 Bug

When computing the forward pass of ConvTranspose2d with many input and output channels, the memory used by Pytorch with a V100 skyrocket. 
 
## To Reproduce

```
import torch
x = torch.ones((32, 2048, 8, 8), device="cuda:0")
conv = torch.nn.ConvTranspose2d(2048, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
conv = conv.to(x.device)
print("after forward",torch.cuda.max_memory_allocated()/2**20, "Mo")
```

## Expected behavior

- On a GTX 2080 Ti, the script above use 96.002MiB of GPU RAM
- On a V100, the script above use **4.676GiB** of GPU RAM

## Environment

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 410.48
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

## Additional context

If we use less channels, like `x=torch.ones((32, 64, 128, 128))` or `x=torch.ones((1024, 64, 8, 8))`, the memory used by the V100 and by the 2080Ti is the same.

**Comment by fmassa** [comment]
This is probably related to CUDNN picking a different algorithm on the V100, which is much more memory hungry.

@csarofeen is this expected?

**Comment by MatthieuBizien** [comment]
It looks like that. With CudNN logging:
- On 2080 Ti: http://paste.ubuntu.com/p/YsQhsfkKP7/
- On V100: http://paste.ubuntu.com/p/498CZTKzg9/

Main difference:
- Line 151 on 2080 Ti: `i!     algo: type=cudnnConvolutionBwdDataAlgo_t; val=CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 (0);`
- Line 151 on V100: `i!     algo: type=cudnnConvolutionBwdDataAlgo_t; val=CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING (3);`

`cudnn.benchmark` doesn't seems to have an impact.

**Comment by ptrblck** [comment]
I tried to reproduce this issue on V100 PCIE 16GB GPUs for different PyTorch, CUDA and cudnn versions:

```
PyTorch built from source, CUDA10.1.243, cudnn 7604

after forward 80.001953125 MB

cudnn.benchmark = True
after forward 80.001953125 MB

====================================

PyTorch 1.3.0, CUDA10.1.168, cudnn 7603

after forward 80.001953125 MB

cudnn.benchmark = True
after forward 80.001953125 MB

====================================

PyTorch 1.2.0 CUDA10.0.130, cudnn 7602

after forward 80.001953125 MB

cudnn.benchmark = True
after forward 80.001953125 MB
```

I'll try to run the repro with a V100 SXM2 next.

**Comment by ptrblck** [comment]
Memory usage for V100 SXM2 (32GB):

```
PyTorch build from source, CUDA10.2.89, cudnn 7605

after forward 80.001953125MB

cudnn.benchmark = True
after forward 80.001953125MB

====================================

PyTorch nightly binaries 1.4.0dev20191202, CUDA10.1.243, cudnn 7603

after forward 80.001953125MB

cudnn.benchmark = True
after forward 80.001953125MB

====================================

PyTorch 1.2.0, CUDA10.0130, cudnn 7602

after forward 80.001953125MB

cudnn.benchmark = True
after forward 80.001953125MB
```

Unfortunately I cannot reproduce this issue, although I'm using the same binaries.
@MatthieuBizien do you still see this issue in the latest release?

**Comment by MatthieuBizien** [comment]
I see that you have a more recent CUDA version. I will try to update it, and check if the issue is still there.

**Comment by ptrblck** [comment]
@MatthieuBizien Did you have a chance to reproduce this issue?

**Comment by MatthieuBizien** [comment]
I seems so, even on 1.2. I just updated the NVidia driver version since September. Closing this issue, thanks!
