### ISSUE TITLE
Exclude generated source docs from Google

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26123]
Googling for `pytorch "adaptive_max_pool2d"` (quotes are important) gives https://pytorch.org/docs/stable/_modules/torch/nn/modules/pooling.html as the first result. The source code module results are not useful and we should exclude them from search results.

cc @ezyang

**Comment by vadimkantorov** [comment]
Excluding results already in google index is not easy unfortunately: https://github.com/pytorch/pytorch/issues/3428#issuecomment-480573073

Probably adding the meta noindex tag for some time is best (so that google can revisit these pages), and then after some time modify the robots.txt appropriately.

**Comment by vadimkantorov** [comment]
Also, should "master" docs be searchable in Google? Currently they are.

**Comment by vadimkantorov** [comment]
After searching the example in the issue I found this: 
```
pytorch.cn › docs › master › _modules › torch › onnx
import functools import types import torch._C as _C TensorProtoDataType = _C._onnx.TensorProtoDataType OperatorExportTypes = _C._onnx.
```
pytorch.cn is a super strange site btw: since it considers 0.4.1 as the latest stable version

Anyway even if not for this strange site, https://pytorch.org/robots.txt does not seem to have master docs disallowed

Also, should something be done to ensure version docs are added to robots.txt automatically when a new version is out? e.g. it currently misses 1.10 and 1.2.0, so they are searchable along with stable (and master).

**Comment by ezyang** [comment]
Yes, there should be a bit of improvement in workflow here...

**Comment by zou3519** [comment]
Adding an entry to robots.txt for "docs/stable/_modules" should do the trick, I'll push a change later this week. We should also not forget to update robots.txt for all of our past releases of pytorch...

**Comment by zou3519** [comment]
> Also, should something be done to ensure version docs are added to robots.txt automatically when a new version is out? e.g. it currently misses 1.10 and 1.2.0, so they are searchable along with stable (and master).

Yes, we should add this. Right now there is very little automation in our docs release process but that would be good to have.

> Excluding results already in google index is not easy unfortunately: #3428 (comment)
>
> Probably adding the meta noindex tag for some time is best (so that google can revisit these pages), and then after some time modify the robots.txt appropriately.

I'm not sure how to modify Sphinx to have it emit a meta noindex. @vadimkantorov does this still apply? I noticed that when googling for the thing linked in the comment, it doesn't appear anymore, so it looks like google does re-building of their index once in a while.

Do you know if just using the content removal tool would be sufficient? https://support.google.com/websearch/answer/6349986?hl=en

**Comment by zou3519** [comment]
According to https://developers.google.com/search/reference/robots_meta_tag and https://support.google.com/webmasters/answer/93710?hl=en , the right way to do this is to add meta noindex tags to the webpages. Adding something to robots.txt isn't sufficient, although it has worked for us in the past.

So the problem becomes:
1) figure out how to teach sphinx to add these tags to just the module source code pages
2) figure out an easy way to add the tags to older versions of pytorch.

**Comment by vadimkantorov** [comment]
@zou3519 I have no extra insight about this issue :/ i just once googled the Google-provided instructions (also linked them above), i think they are the same ones as you found

**Comment by vadimkantorov** [comment]
My findings are in https://github.com/pytorch/pytorch/issues/3428#issuecomment-480573073

**Comment by zou3519** [comment]
I realized that we don't have to change sphinx to do this, we can post-process the docs after we build them and before we push to the website to include the meta noindex.

All of the generated source docs fall under _modules (i.e., pytorch.org/docs/stable/_modules). To fix this particular issue (exclude generated source docs from google), I'm going to do the following:
- Manually add the meta noindex to the stable/_modules docs
- Change our doc build script to insert meta noindex to all generated html pages under _modules. In the future, when we use the doc build script to create new "stable" docs or new "master" docs, the meta noindex gets inserted by the script.

**Comment by Evpok** [comment]
Conversely, though I agree that they shouldn't appear in search engines, I do find reading the source useful, so it would be nice to have [source] links in the docs.

**Comment by zou3519** [comment]
> Conversely, though I agree that they shouldn't appear in search engines, I do find reading the source useful, so it would be nice to have [source] links in the docs.

We're keeping the [source] links in the docs but removing the source file pages from search engines.

**Comment by zou3519** [comment]
It worked!

![image](https://user-images.githubusercontent.com/5652049/71847664-776e4180-309b-11ea-85d6-c9836d673247.png)

Thanks @vadimkantorov for your help.

**Comment by zou3519** [comment]
We should probably exclude the master docs from google, but I'm not sure

**Comment by vadimkantorov** [comment]
Just googled and got module source code in the second hit:
![image](https://user-images.githubusercontent.com/1041752/73492794-b5683800-43b1-11ea-9a11-304b3f5ab8ea.png)
as noted by @josherich in https://github.com/pytorch/pytorch/issues/32838

@zou3519 let's reopen this issue?

**Comment by zou3519** [comment]
Oh, I think the problem is that I didn't cherry-pick my changes to the 1.4.0 branch...

Thanks for reporting @vadimkantorov.

**Comment by zou3519** [comment]
Seems fixed now:
![image](https://user-images.githubusercontent.com/5652049/76348999-97122800-62df-11ea-8807-78afb3c47cbe.png)
