### ISSUE TITLE
[ONNX] support index_fill

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26138]
## 🐛 Bug

The [docs](https://pytorch.org/docs/stable/onnx.html#supported-operators) mention `index_fill` support but I get error

## To Reproduce

```python
     90     global _registry
---> 91     return _registry[(domain, version)][opname]

KeyError: u'index_fill'
```

## Expected behavior

Support `index_fill`

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Maybe workaround with `where`

**Comment by neginraoof** [comment]
This is the PR to address this: https://github.com/pytorch/pytorch/pull/23052

**Comment by neginraoof** [comment]
@dashesy could you please close this if fixed?

**Comment by dashesy** [comment]
not yet in nightly it seems, will try later

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
