### ISSUE TITLE
RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /home/gpu/dev/rt/pytorch/torch/lib/THC/generic/THCStorage.cu:66

### ISSUE THREAD

**Issue by ghost** [pytorch/pytorch#2614]
This happens very frequently whenever I stop training on Jupyter. 
Of course, the exception is deceptive since I can use the CUDA device OUTSIDE PyTorch without any issues even after this error happens. 

Stack trace:
```
RuntimeErrorTraceback (most recent call last)
<ipython-input-19-56b1ce2851dc> in <module>()
     14 if use_cuda:
     15     lgr.info ("Using the GPU")
---> 16     net.cuda()
     17     loss_func.cuda()
     18 #     cudnn.benchmark = True

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in cuda(self, device_id)
    145                 copied to that device
    146         """
--> 147         return self._apply(lambda t: t.cuda(device_id))
    148 
    149     def cpu(self, device_id=None):

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in _apply(self, fn)
    116     def _apply(self, fn):
    117         for module in self.children():
--> 118             module._apply(fn)
    119 
    120         for param in self._parameters.values():

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in _apply(self, fn)
    122                 # Variables stored in modules are graph leaves, and we don't
    123                 # want to create copy nodes, so we have to unpack the data.
--> 124                 param.data = fn(param.data)
    125                 if param._grad is not None:
    126                     param._grad.data = fn(param._grad.data)

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in <lambda>(t)
    145                 copied to that device
    146         """
--> 147         return self._apply(lambda t: t.cuda(device_id))
    148 
    149     def cpu(self, device_id=None):

/usr/local/lib/python2.7/dist-packages/torch/_utils.pyc in _cuda(self, device, async)
     63         else:
     64             new_type = getattr(torch.cuda, self.__class__.__name__)
---> 65             return new_type(self.size()).copy_(self, async)
     66 
     67 

/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.pyc in _lazy_new(cls, *args, **kwargs)
    267     # We need this method only for lazy init, so we can remove it
    268     del _CudaBase.__new__
--> 269     return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
    270 
    271 
```

cc @ngimel

**Comment by herleeyandi** [comment]
I also face the same problem.

**Comment by QuantScientist** [comment]
I did the following:
Upgraded to CUDNN6
```
FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
```
See my docker file here:
https://github.com/QuantScientist/Deep-Learning-Boot-Camp/blob/master/docker/Dockerfile.gpu3

In addition, on the HOST machine I upgraded the NVIDIA drivers, See the script here:
https://github.com/QuantScientist/Deep-Learning-Boot-Camp/blob/master/docker/deps_nvidia_docker.sh

**Comment by hvasbath** [comment]
I have the same issue, however I have upgraded already to cuDNN7 and CUDA9, maybe they are too new?

**Comment by aymenx17** [comment]
same problem with cuda9

**Comment by lifengjin** [comment]
I am also getting this error. My program is in python but I first use CUDA C (thrust and cusp) to do some stuff first and then use pytorch to do some other stuff. My observation is:
1. If the pytorch model is a CNN, then the error goes away. If I use a GRU then I'd see this error.
2. If the model is small then the error goes away even if the model is a GRU.
3. The error occurs only if I transfer the pytorch model to GPU, otherwise it is fine.
4. There is only 1 GPU on the server, so it is not a multi-GPU problem.
#4293 In this thread they mention using arrayfire as well. I wonder if it is because the same process uses multiple ways to access the GPU?

**Comment by yf225** [comment]
@QuantScientist @herleeyandi @hvasbath @aymenx17 @lifengjin Would you like to check if this problem still occur in PyTorch 1.4?
