### ISSUE TITLE
Ambiguous docstring in NegativeBinomial distribution

### ISSUE THREAD

**Issue by kyleengel** [pytorch/pytorch#26151]
## 📚 Documentation

The [documentation for the negative binomial distribution](https://pytorch.org/docs/stable/_modules/torch/distributions/negative_binomial.html) is ambiguous. 

The wording implies that PyTorch's negative binomial distribution describes the total number of trials before a set number of failures occurs. Really, it describes the total number of *successful* trials before a set number of failures occurs. 

Since negative binomial distributions can be parameterized a bunch of different ways ([see Wikipedia](https://en.wikipedia.org/wiki/Negative_binomial_distribution#Alternative_formulations)), I think PyTorch's docs should be more explicit. Also, PyTorch's negative binomial parameterization is different than [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.nbinom.html) and also different than Wikipedia, so being extra clear can't hurt.

I made #25923 to clarify the docstring and describe what PyTorch's implementation is doing. 

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by alicanb** [comment]
closed via #25923
