### ISSUE TITLE
Why does pytorch need the sentences in a minibatch to be sorted?

### ISSUE THREAD

**Issue by tjppires** [pytorch/pytorch#2615]
Hi!

I am writing a system for APE (automatic post editing), and so I get as input a source (src) sentence and a machine translation (mt) sentence.

As I am using pad_packed_sequences, I have to sort the inputs in decreasing order. However, the src and mt sentences can have different lengths, and sorting them both may cause the sentences the src and mt sentences to be misaligned.

I can obviously sort both and then realign them after feeding them through the encoder, but I really do not see the point of this unnecessary work. Why does pytorch not accept the sentences as I give them? After all, it is given the lenghts of the sentences.

Thanks.

**Comment by allenye0119** [comment]
You can find the answer in [this post](https://discuss.pytorch.org/t/why-lengths-should-be-given-in-sorted-order-in-pack-padded-sequence/3540).
Also, I think this kind of question is better be asked at https://discuss.pytorch.org.
