### ISSUE TITLE
c10 dispatcher data composition diagram is hard to understand

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26171]
For a while I had been having problems finding where things live in the c10 dispatcher. So I decided to sit down and trace out the data composition diagram to understand the data model of the dispatcher. Here's what I got, when reading the state of the tree after #23668.

```
// KernelFunction.h

using KernelFunction = void(Stack*, KernelCache* cache);

// DispatchTable.h

struct DispatchTableEntry {
  KernelFunction* kernel_func;  // can be nullptr, not all kernels have this
  /*not-nullable*/ KernelCacheCreatorFunction cache_creator_func;
  void* unboxed_kernel_func; // can be nullptr, not all kernels have this
};

class impl::KernelTable {
 ska::flat_hash_map<TensorTypeId, DispatchTableEntry> map_;
}

class DispatchTable {
  detail::KernelTable_ kernels_;
  c10::optional<DispatchTableEntry> catchall_kernel_;
  DispatchStrategy dispatch_strategy_;
  std::string operator_name_;
}

// OperatorEntry.h

class OpKernel {
  KernelFunction* kernel_;
  std::unique_ptr<c10::KernelCache> cache_;
  void* unboxed_kernel_;
}

class impl::OperatorEntry {
  FunctionSchema schema_;
  LeftRight<DispatchTable> dispatchTable_;
  c10::either<
    ska::flat_hash_map<TensorTypeId, std::list<DispatchTableEntry>>, // dispatched kernels
    std::list<DispatchTableEntry> // catch-all kernels
  > kernels_;
  std::list<void*> unboxedAutogradKernels_; // ???
  std::atomic<void*> currentUnboxedAutogradKernel_; // ???
  OperatorOptions options_;
  std::mutex kernelsMutex_; // protects kernels_
  std::mutex unboxedAutogradKernelsMutex_; // protects unboxedAutogradKernels_
}

// operator_name.h

struct OperatorName final {
  std::string name;
  std::string overload_name;
};

// Dispatcher.h

// Morally this is just map<OperatorName, OperatorEntry>

struct OperatorDef {
  impl::OperatorEntry op;
  size_t refcount;
};

class OperatorHandle {
  std::list<Dispatcher::OperatorDef>::iterator operatorIterator_;
}

class Dispatcher {
  std::list<OperatorDef> operators_;
  LeftRight<ska::flat_hash_map<OperatorName, OperatorHandle>> operatorLookupTable_;
  std::unique_ptr<detail::RegistrationListenerList> listeners_;
  std::mutex mutex_;
}
```

I have a number of questions:

* The naming is terrible. What does a "KernelTable" contain? DispatchTableEntries, of course!
* There are two kernel tables, of some sort: there is a `kernels_` member in `OperatorEntry`, and another `kernels_` in `DispatchTable`. This is pretty weird; why do we need the field in two places?
* Do we still need registration listeners? I never understood their motivation
* Do we really need to be able to register an OperatorDef to multiple OperatorNames? I can't think of a legitimate use case for this functionality.
* Should OperatorName really be a pair of `std::string`? What about a schema string?
* After VariableTensorId was added, we can get rid of `unboxedAutogradKernels_` and friends, right?
* Why are there multiple mutexes in `OperatorEntry`?
* I've previously argued that we shouldn't call the kernel cache a "cache"; it's the data associated with the closure. Following on with that, there's no reason for `kernel_cache` to be a `unique_ptr` if we're just going to use it to store function pointers, right?

cc @smessmer @dzhulgakov

**Comment by smessmer** [comment]
> * The naming is terrible. What does a "KernelTable" contain? DispatchTableEntries, of course!

Let's rename things

> * There are two kernel tables, of some sort: there is a `kernels_` member in `OperatorEntry`, and another `kernels_` in `DispatchTable`. This is pretty weird; why do we need the field in two places?

`OperatorEntry::kernels_` is the source of truth and contains all registered kernels for that operator. You can have multiple kernels for the same dispatch key in there, for example when you're in a Jupyter Notebook and re-execute a cell or when you're loading a library that wants to overwrite some of the CPU kernels, say for better performance. There's a quite long comment in that file with more details.
But even though there can be multiple kernels with the same dispatch key, there can always only be one active. This is the most recently registered one. `DispatchTable::kernels_` stores only the active kernels, and can have a faster lookup time by not having to store the others.

> * Do we still need registration listeners? I never understood their motivation

They're used to register c10 operators with JIT

> * Do we really need to be able to register an OperatorDef to multiple OperatorNames? I can't think of a legitimate use case for this functionality.

Not sure what you mean. An OperatorDef stores exactly one OperatorEntry with exactly one OperatorName.

> * Should OperatorName really be a pair of `std::string`? What about a schema string?

Some places use the full function schema, but for many other places it's enough to know function name + overload name. That's what `OperatorName` is for. It is for example used to look up operators by name when you're loading a model into the lite interpreter.

> * After VariableTensorId was added, we can get rid of `unboxedAutogradKernels_` and friends, right?
> * Why are there multiple mutexes in `OperatorEntry`?

There's currently a PR out fixing both of these, see https://github.com/pytorch/pytorch/pull/26130

> * I've previously argued that we shouldn't call the kernel cache a "cache"; it's the data associated with the closure. Following on with that, there's no reason for `kernel_cache` to be a `unique_ptr` if we're just going to use it to store function pointers, right?

We should rename it. It was renamed to cache because we thought that's how we're going to use it but we didn't use it as a cache. It is more of a "kernel config" now. It does need to be a unique_ptr because it's polymorphic but needs to be owned. Note that it's polymorphic but not virtual, this part is mostly for perf reasons.

**Comment by ezyang** [comment]
Thanks for the responses! In particular, thank you for reminding about Jupyter notebook load/unloading.

> You can have multiple kernels for the same dispatch key in there, for example when you're in a Jupyter Notebook and re-execute a cell or when you're loading a library that wants to overwrite some of the CPU kernels, say for better performance. There's a quite long comment in that file with more details.

Thank you, I went and read the comment. I think the reason this all feels over-engineered to me is that Python (our primary use case for loading/unloading modules) doesn't really know how to unload modules (https://bugs.python.org/issue34309). So it seems extremely premature to design a system where operators unload on static variable destruction, when the most important use-case for unloading (Python) will never trigger this codepath.

If you assume that modules never unload, things are a lot simpler, right? Because you can just directly overwrite operators when they get reregistered, you don't have to keep the old ones around, and you can just leak the operators until process exit time.

> Not sure what you mean. An OperatorDef stores exactly one OperatorEntry with exactly one OperatorName.

I was referring to the fact that we store an iterator:

```
class OperatorHandle {
  std::list<Dispatcher::OperatorDef>::iterator operatorIterator_;
}
```

But I guess, you are telling me that it is not actually valid to go next/prev here?

> Some places use the full function schema, but for many other places it's enough to know function name + overload name. That's what OperatorName is for. It is for example used to look up operators by name when you're loading a model into the lite interpreter.

What are the constraints here? The primary constraint I am aware of here is binary size on mobile. But I'm not convinced that function name + over load is much of an improvement here... is it? Are there other constraints?

**Comment by smessmer** [comment]
Most of these concerns should be fixed now in a recent series of PRs. Most notably https://github.com/pytorch/pytorch/pull/26337, https://github.com/pytorch/pytorch/pull/28314 and https://github.com/pytorch/pytorch/pull/28186.
