### ISSUE TITLE
[ONNX] bool comparison with 0,1 should export False,True constants

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26189]
## 🐛 Bug

Should be able to compare boolean to 0,1 and exporter maybe should then use Fale,True as constants. But [comparing bool to 0 results in error](https://github.com/pytorch/pytorch/issues/25805)

## To Reproduce

```python
a = b > c
na = a == 0
```

## Expected behavior

export 0 as False constant to be valid ONNX

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Work around is:

```python
a = b > c
na = a == torch.as_tensor(False)
```

**Comment by neginraoof** [comment]
PR for fix: https://github.com/pytorch/pytorch/pull/26292

**Comment by neginraoof** [comment]
@dashesy this should be fixed. Could you please try and close this issue if possible?

**Comment by dashesy** [comment]
This is fixed in the nightly, thanks
