### ISSUE TITLE
GPU memory leakage in try-except statement

### ISSUE THREAD

**Issue by KiddoZhu** [pytorch/pytorch#26188]
## 🐛 Bug

GPU memory can't be released when using a try-except statement for CUDA out of memory.

## To Reproduce

```
import gc
import numpy as np
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self, *embeddings):
        super(MyModel, self).__init__()
        self.embeddings = nn.ModuleList()
        for embedding in embeddings:
            embedding = torch.as_tensor(embedding)
            embedding = nn.Embedding.from_pretrained(embedding, freeze=True)
            self.embeddings.append(embedding)

device = "cuda"
embeddings = [np.zeros((5000000, 1000))] * 3
model = MyModel(*embeddings)

try:
    model = model.to(device)
except RuntimeError: # CUDA out of memory
    print("GPU memory overflow. Use CPU instead.")
    del model
    gc.collect()
    torch.cuda.empty_cache()
```

## Expected behavior

When `MyModel` is a single layer like `torch.nn.Linear`, the code releases most GPU memory and results in about 900MB in nvidia-smi.

When `MyModel` is a custom model like the above module list, no GPU memory is released and it results in about 10GB in nvidia-smi.

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.6.1810 (Core)
GCC version: (GCC) 7.3.0
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[pip] torchbiggraph==1.dev1
[pip] torchvision==0.3.0
[conda] mkl                       2019.4                      243
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] torchbiggraph             1.dev1                    <pip>
[conda] torchvision               0.3.0           py37_cu10.0.130_1    pytorch

**Comment by SsnL** [comment]
This is not memory leakage. When a method of an object raises, the python stack trace contains a reference to the object, rendering your `del model` useless.

```py
In [13]: import weakref
    ...: import gc
    ...:
    ...: class O:
    ...:     def err(self):
    ...:         raise RuntimeError()
    ...:
    ...: e = O()
    ...:
    ...: we = weakref.ref(e)
    ...:
    ...: try:
    ...:     e.err()
    ...: except RuntimeError:
    ...:     del e
    ...:     gc.collect()
    ...:     print(we())
    ...:
    ...: gc.collect()
    ...: print(we())
<__main__.O object at 0x10540d048>
None


```

If you move the `del`, `gc.collect` and `empty_cache` outside the except clause, you are fine.
