### ISSUE TITLE
[ONNX] scatter support for broadcast

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26191]
## 🐛 Bug

Scatter `src` is not broadcasted

> RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Node: rand_node_name_266 Status Message: Indices and updates must have the same rank

## To Reproduce

```python
a = torch.as_tensor([-0.2, 1.0, 2.3])
b = a + 1
idx = torch.nonzero(a> 0).view(-1)
b.scatter_(0, idx, 0)
```

## Expected behavior

scatter `src` should be broadcasted

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Am not sure if this is ORT or exporter or ONNX issue!

**Comment by rgommers** [comment]
`scatter_` does not broadcast. This is not an ONNX issue; I'm updating the documentation to mention that gather/scatter functions don't broadcast.
