### ISSUE TITLE
legacyTypeId is clobbering checked_tensor_unwrap checks

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#26206]
I was investigating the comment chain over in https://github.com/pytorch/pytorch/pull/25595#discussion_r322455893, and ran into a bug.

To reproduce, you need to get rid of multiple dispatch for multinomial and call it, e.g.:
```
torch.multinomial(torch.rand(2,3, device='cuda'), 5, True, out=torch.randn(2,3, device='cuda').long())
```

You'll get an error like:
```
Unrecognized tensor type ID: VariableTypeId
```

what's happening here is we are trying to pass a variable to a method that only accepts tensors, and this is already checked with a reasonable error message:
https://github.com/pytorch/pytorch/blob/16605ef2ebbc1fca3b2d5292591a4c72d42df34c/aten/src/ATen/Utils.h#L74-L77

but the first call of `tensorTypeIdToBackend(impl::dispatchTypeId(expr.type_set())` bails before we get there.

**Comment by ezyang** [comment]
I'll look into this.
