### ISSUE TITLE
[torchscript] Support requires_grad_ op in TorchScript

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#26212]
## 🚀 Feature
The ability to set the `requires_grad` attribute a tensor in TorchScript.

## Motivation

We are looking to use TorchScript to JIT compile a large algorithm. A part of the algorithm requires computing the gradient of  a certain callable w.r.t. parameters computed within the function being scripted. It is not possible or desirable to set `requires_grad_` at the outset because we only need to record the gradients at a very specific part of the larger algorithm.

e.g.
```python
@torch.jit.script
def scriptfn(t):
    t.requires_grad_(True)
    t_sq = t ** 2
    grads = torch.autograd.grad([t_sq], [t])
    t.requires_grad_(False)
    return grads


u = torch.tensor(2.)
print(scriptfn(u))
```

currently errors out with the master branch:

```
Traceback (most recent call last):
  File "/Users/npradhan/workspace/pyro_dev/pyro/examples/pytorch_hackathon/example.py", line 49, in <module>
    @torch.jit.script
  File "/Users/npradhan/miniconda3/envs/pytorch-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 1211, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Unknown builtin op: aten::requires_grad_.
Could not find any similar ops to aten::requires_grad_. This op may not exist or may not be currently supported in TorchScript.
:
at /Users/npradhan/workspace/pyro_dev/pyro/examples/pytorch_hackathon/example.py:51:4
@torch.jit.script
def scriptfn(t):
    t.requires_grad_(True)
    ~~~~~~~~~~~~~~~~ <--- HERE
    t_sq = t ** 2
    grads = torch.autograd.grad([t_sq], [t])
    t.requires_grad_(False)
    return grads
```

## Pitch

Expose the `requires_grad_` method for Tensors in TorchScript so as to enable usage patterns like above. cc. @zdevito, @bwasti who mentioned that this is already being worked on, but I couldn't find the relevant PR.

cc @suo

**Comment by suo** [comment]
This works now!
