### ISSUE TITLE
Does PyTorch 1.2 support autograd for multiplication of a sparse tensor by a dense tensor?

### ISSUE THREAD

**Issue by XinliYu** [pytorch/pytorch#26234]
Just simple question, does PyTorch 1.2 support autograd on sparse multiplication or not yet, like sparse times dense? I see there are some open issues tracking the support for sparse tensors, like

https://github.com/pytorch/pytorch/issues/2389
https://github.com/pytorch/pytorch/issues/3158
https://github.com/pytorch/pytorch/issues/8853

But I get lost after reading all these.

**Comment by mruberry** [comment]
Do you mean like this?

https://pytorch.org/docs/stable/sparse.html#torch.sparse.mm

**Comment by rgommers** [comment]
There are docs on this and question is answered, so closing.
