### ISSUE TITLE
error when installing from source

### ISSUE THREAD

**Issue by kuyun-zhangyang** [pytorch/pytorch#2626]
Hello,
     I am trying to install the pytorch from source with anaconda(14.04.1-Ubuntu，cuda7.5,cudnnv5,gcc4.8.5). During installation process I am getting these errors.

[ 23%] Built target nccl_external
[ 76%] Built target gloo
[ 79%] Building NVCC (Device) object gloo/CMakeFiles/gloo_cuda.dir/nccl/gloo_cuda_generated_nccl.cu.o
[ 82%] Building NVCC (Device) object gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda.cu.o
[ 85%] Building NVCC (Device) object gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda_private.cu.o
/home/zhangyang/code/pytorch/torch/lib/gloo/gloo/common/linux.h:26:26: error: ‘__T0’ was not declared in this scope
 const auto kPCIClass3D = PCIClassMatch{0x030200, 0xffff00};
                          ^
/home/zhangyang/code/pytorch/torch/lib/gloo/gloo/common/linux.h:29:31: error: ‘__T0’ was not declared in this scope
 const auto kPCIClassNetwork = PCIClassMatch{0x020000, 0xff0000};
                               ^
CMake Error at gloo_cuda_generated_cuda_private.cu.o.cmake:263 (message):
  Error generating file

**Comment by fmassa** [comment]
There was a change in how we use `submodules`/`subtrees` with gloo.
Did you try cloning as explained in the docs https://github.com/pytorch/pytorch#get-the-pytorch-source with the `--recursive` flag?
Another solution is discussed in https://github.com/pytorch/pytorch/issues/2553#issuecomment-326066034

**Comment by kuyun-zhangyang** [comment]
@fmassa ，thanks for your reply。I'm sure cloning source with --recursive flag。And #2553 is not as my error。How can i try to compile gloo in other ways?

**Comment by varunagrawal** [comment]
Try deleting the `torch/lib/tmp_install` and the `torch/lib/build` directories. There seem to be some lingering dependencies.

**Comment by kuyun-zhangyang** [comment]
@varunagrawal ，thanks for your reply。It  does not work when deleting the build directory, but i success to install latest pytorch in another centos system. I guess maybe some conflicts  happened  on my ubuntu.

**Comment by nathantsoi** [comment]
same problem here, ubuntu 16.04, cuda 7.5, gcc 5.4.0, cudnn v6.0.

worked fine w/o gloo via:

```
NO_DISTRIBUTED=1 python setup.py install
```

**Comment by soumith** [comment]
the bug report https://devtalk.nvidia.com/default/topic/856954/bug-nvcc-and-gcc-4-9-3-get-into-conflict-over-unnamed-type-template-parameters/ points to the fact that it's an nvcc 7.5 bug with compilers after gcc 4.8 (or whatever 7.5 officially supports).

**Comment by fliman** [comment]
I'm using gcc (GCC) 4.8.5, also having this problem. Any solution?

**Comment by mruberry** [comment]
Closing due to age and lack of updates. If this is still an issue please comment/reopen!
