### ISSUE TITLE
pytorch inference fp16 or int8

### ISSUE THREAD

**Issue by JensenHJS** [pytorch/pytorch#26274]
A layer is a tensor of type fp32.  I try to use .half() to change it to fp16. It works. But when I use layer=layer.type(torch.int8) , it raise an error "runtimeError: getCudnnDataType() not supported for Char" .  And I search this error in the internet. It denotes "The Module.forward () method was called and this error occurred while calculating Conv2d. The input to the network must be of type Float or Double or half tenant and must be encapsulated in Variable." So I want to know how to change a fp32 type layer to int8. Looking forward to your reply

**Comment by soumith** [comment]
we dont support int8 inference in GPU (or CPU)
