### ISSUE TITLE
Conv3D on CPU segfaults

### ISSUE THREAD

**Issue by dchansen** [pytorch/pytorch#2627]
Running the code
```import torch
from torch import nn
from torch.autograd import Variable
v = Variable(torch.randn(1, 16, 128, 128, 128), volatile=True)
model = nn.Conv3d(16,16,5)
model(v)
```

Results in a segfault. Running the same code on the GPU works flawlessly. 
[Output from gdb](https://gist.github.com/dchansen/6c616b73e65a68c027efa29082e777a1)

`torch.__version__ = '0.2.0_1'`
The issue was originally raised [here](https://discuss.pytorch.org/t/segmentation-fault-for-sequential-and-conv3d-on-cpu/6353), but I've encountered the same bug independently.

**Comment by soumith** [comment]
i'm looking into this.

**Comment by soumith** [comment]
i fixed this in master. we're cutting a new release this week and the fix will be in the release. thanks a lot for reporting.

**Comment by dchansen** [comment]
That was fast. Thank you!
