### ISSUE TITLE
torch::Tensor img_tensor_const = torch::autograd::make_variable(img_tensor, false);

### ISSUE THREAD

**Issue by boyob** [pytorch/pytorch#26275]
this line arouse this issure:
--------------------------------------------------------------------
terminate called after throwing an instance of 'c10::Error'
  what():  Must not create a new variable from a variable, use its .tensor_data() (make_variable at /usr/lib/libtorch/include/torch/csrc/autograd/variable.h:526)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f5d0bd5e18a in /usr/lib/libtorch/lib/libc10.so)
frame #1: torch::autograd::make_variable(at::Tensor, bool, bool) + 0x10c (0x563286f56bfd in ./main)
frame #2: main + 0x42a (0x563286f51eda in ./main)
frame #3: __libc_start_main + 0xe7 (0x7f5d083c0b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: _start + 0x2a (0x563286f5039a in ./main)

**Comment by cpuhrsch** [comment]
Could add a bit more detail to reproduce this issue?

**Comment by boyob** [comment]
> reproduce

**Comment by willianLee** [comment]
is there any method for this problem?

**Comment by willianLee** [comment]
> Could add a bit more detail to reproduce this issue?

terminate called after throwing an instance of 'c10::Error'
  what():  Must not create a new variable from a variable, use its .tensor_data() (make_variable at /home/software/libtorch/include/torch/csrc/autograd/variable.h:526)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f1505619273 in /home/software/libtorch/lib/libc10.so)
frame #1: torch::autograd::make_variable(at::Tensor, bool, bool) + 0xe4 (0x4addd7 in ./libtorch-yolov3-master)
frame #2: main + 0x576 (0x4a8a1a in ./libtorch-yolov3-master)
frame #3: __libc_start_main + 0xf0 (0x7f14ff472830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: _start + 0x29 (0x4a72f9 in ./libtorch-yolov3-master)

Aborted (core dumped)

**Comment by cumtchenchang** [comment]
@willianLee @boyob  Can you tell me how to solve this problem?

**Comment by willianLee** [comment]
时间过去有点久了 我忘了是什么导致这个错误了，但大都是编译文件和代码语法的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chang Chen(陈常)"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 上午9:56
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;""<1739298785@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] torch::Tensor img_tensor_const = torch::autograd::make_variable(img_tensor, false); (#26275)




@willianLee @boyob  Can you tell me how to solve this problem?
