### ISSUE TITLE
Speed up PyTorch autograd by moving functions to C++/ATen

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#2630]
Currently, calling methods on Variable objects is much slower than calling the same methods on Tensor objects. The problem is exacerbated because many of the Variable autograd functions hold on to the GIL for most of the call. At the same time, it's hard to write autograd functions in C++ because we don't have a full C++ Variable API.

We should speed up autograd by moving nearly all the Variable method implementations to C++ and use ATen to provide a fully differentiable API.

1. Implement a `Variable` `at::Type` object which provides differentiable implementations of ATen tensor functions.  This means you can write C++ code on `at::Tensor` that supports automatic differentiation.
2. Implement the derivatives for `at::Tensor` functions using a simple yaml file.
3. Generate bindings to `at::Tensor` functions on `_C._VariableBase` in a similar way to how we generate `TensorMethods.cpp`

At least for now, the `Variable` `at::Type` object will live in PyTorch instead of ATen because it depends on PyTorch's C++ autograd API.  It'll be generated using a Python script (similar to [gen.py](https://github.com/zdevito/ATen/blob/master/src/ATen/gen.py)) that uses Declarations.yaml from ATen and the derivatives YAML file.

The derivatives YAML file will also live in PyTorch. For each differentiable ATen function, we'll specify the derivative formula for each input.  For example, here's the entry for `addbmm`:

```yaml
- name: addbmm(Scalar beta=1, Tensor self, Scalar alpha=1, Tensor mat1, Tensor mat2)
  self: grad * alpha
  mat1: grad.bmm(mat2.transpose(1, 2)) * beta
  mat2: mat1.transpose(1, 2).bmm(grad) * beta
```

Functions that can't be concisely expressed in a single line can be added to a separate file and called from the derivatives YAML:

```yaml
- name: prod(Tensor self, int32_t dim, bool keepdim=False)
  self: prod_backward(self.sizes(), dim, keepdim)
```

Functions from THNN will be bound separately, since they follow a different pattern. We will probably want to move the second derivative definitions to C++ once the other steps are complete.

**Comment by gchanan** [comment]
what's the plan for double backwards?  It seems like this should work fine, but the derivative formulas get pretty complicated.  Will I be able to specify an external function definition?

**Comment by colesbury** [comment]
@gchanan, Yes, we'll be able to specify external functions. I've updated the description.

**Comment by apaszke** [comment]
We've started working on it, and there's no discussion going on, so I'm closing this
