### ISSUE TITLE
navigation for PyTorch Quantization

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#26308]
Here is how I was thinking we would organize the quantization documentation .. primarily so that the quantization stuff all ends up together but is navigable from places like "nn" where some of the functions end up. 

First, here is what the early preview looks like .. as a baseline
![what it looks like now](https://user-images.githubusercontent.com/45861273/64991361-96478e80-d886-11e9-9b36-ee5ecd02f74d.png)

Then here is how I would change that page (mostly the navigation)
![MOck up 1](https://user-images.githubusercontent.com/45861273/64991381-a19aba00-d886-11e9-905f-50430af9d223.png)

Then here is how I would add a section to the .nn section linking back to the quantization doc. 

![In other places where the code lives like nn](https://user-images.githubusercontent.com/45861273/64991407-a9f2f500-d886-11e9-96e3-4a00998279f3.png)

cc @ezyang

**Comment by jlin27** [comment]
Feature 1 - Consolidating Quant Docs

![image](https://user-images.githubusercontent.com/8042156/65808100-ff60b900-e146-11e9-8d8a-713a35cb5ad3.png)

Some things to consider:
- Basically the L1 headers are the "module" names and L2 are "class" names with some exceptions. See below.
- Request for extra review for the names under torch.nn.quantized cause it has some irregularly nested files 
- I can also nest everything one layer in so it collapses even further
- Let me know if you'd like the L1 header names changed

**Comment by jlin27** [comment]
Feature 2 - Link to Quantization from torch.nn

We can do this, but I think we'll need to wait until the url for the Quantization page is finalized (the site is deployed) before we can add it in. Let me double-check

**Comment by gottbrath** [comment]
this is done. Thanks @jlin27!
