### ISSUE TITLE
Use camelCase naming convention in distributed model parallel code.

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#26317]
Based on our C++ coding conventions we should use `camelCase` instead of `lower_case` for functions, local variables, member variables etc.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by mrshenli** [comment]
Closing as I believe this is already so in master
