### ISSUE TITLE
torch.Tensor reverse operators (__rmul__) should return NotImplemented for unsupported types

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#26333]
Currently if the the argument of `__rmatmul__` is not a Tensor, PyTorch throws `*** TypeError: matmul(): argument 'other' (position 1) must be Tensor, not Vec`

Python data model asks that it return `NotImplemented` in such case. This allows interpreter to dispatch op to the proper implementation.
(ie see https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations)

Current behavior makes it hard to implement custom types. IE
```
class FactoredMatrix:
  def __init__(self, mat):
    self.mat = mat
  def __matmul__(self, other):
    return 0
  def __rmatmul__(self, other):
    return 1
x = torch.ones((2,2))
print(FactoredMatrix(x) @ x)  # works
print(x @ FactoredMatrix(x))  # fails
```

cc @ezyang @gchanan @zou3519

**Comment by gchanan** [comment]
I don't think this can be considered complete, as noted in https://github.com/pytorch/pytorch/pull/26507.

Namely:
1) That PR doesn't cover operators that are not explicitly bound
2) It doesn't seem like we should be returning NotImplemented for in-place ops.

**Comment by peterbell10** [comment]
> 1. That PR doesn't cover operators that are not explicitly bound

I'd missed those. I can see that and, or, xor, lshift and rshift are in `native_functions.yaml`; are there any others hidden elsewhere, e.g. I can't see `__eq__` anywhere. @gchanan could you point me towards the code generator for `native_functions.yaml`?

> 2. It doesn't seem like we should be returning NotImplemented for in-place ops.

Can you expand on this? The [python docs] state:
> `NotImplemented`
>     Special value which should be returned by the binary special methods (e.g. `__eq__()`, `__lt__()`, `__add__()`, `__rsub__()`, etc.) to indicate that the operation is not implemented with respect to the other type; **may be returned by the in-place binary special methods (e.g. `__imul__()`, `__iand__()`, etc.)** for the same purpose.


[python docs]: https://docs.python.org/3.7/library/constants.html#NotImplemented

**Comment by gchanan** [comment]
> Can you expand on this? The python docs state:

Ah, good looking out.  I guess I wasn't sure how another type would understand how to do in-place ops on the type, but that isn't really true.

**Comment by gchanan** [comment]
> could you point me towards the code generator for native_functions.yaml?

I think the relevant code is here:
https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_python_functions.py

Essentially you want to look at the generated version of python_variable_methods.
