### ISSUE TITLE
libtorch cmake  lib

### ISSUE THREAD

**Issue by zhjw0927** [pytorch/pytorch#26343]
# I want to generate a static library file that calls libtorch， but report errors:
“torch/script.h”: No such file or dire
# My CMakeLists.txt is:
cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(detector )
set( CMAKE_CXX_FLAGS "-std=c++11" )
find_package(Torch REQUIRED)
include_directories( ${Torch_INCLUDE_DIRS} )
include_directories(D:\\libtorch\\include\\torch)
message(STATUS "Pytorch status:")
message(STATUS "    libraries: ${TORCH_LIBRARIES}")
message(STATUS "    include_dirs: ${Torch_INCLUDE_DIRS}")
add_library(detector src/detector.cpp)
# Run the following command:
cmake -DCMAKE_PREFIX_PATH=D:\libtorch ..
In the output information, {Torch_INCLUDE_DIRS} is None.
cmake --build .
report error: “torch/script.h”: No such file or dire

Is my cmake file wrong? 
Hope get your help, thanks!

cc @peterjc123

**Comment by zhjw0927** [comment]
Generating a static library file that calls opencv, cmake can find where is OpenCV_INCLUDE_DIRS.
So, can generating *.lib, why can't find location of Torch_INCLUDE_DIRS？
I'm confused...

**Comment by peterjc123** [comment]
The reason is that CMake is case-sensitive, so it should be `TORCH_INCLUDE_DIRS`, not `Torch_INCLUDE_DIRS`. Actually, you don't have to specify the include dirs manually, just take a look at the example [here](https://github.com/pytorch/examples/blob/master/cpp/mnist/CMakeLists.txt).

**Comment by peterjc123** [comment]
You said you need a static library, then you should build the static version of LibTorch on your own. The precompiled one is dynamic runtime (DLL).
