### ISSUE TITLE
Input-cell-attention for LSTM

### ISSUE THREAD

**Issue by ayaabdelsalam91** [pytorch/pytorch#26341]
## 🚀 Feature
Input-cell-attention for LSTM

## Motivation
Recent efforts to improve the interpretability of deep neural networks use saliency to characterize the importance of input features in predictions made by models. However, RNN saliency vanishes over time, biasing detection of salient features only to later time steps and are, therefore, incapable of reliably detecting important features at arbitrary time intervals. 

## Pitch

To address this vanishing saliency problem, we propose a novel RNN cell structure (input-cell-attention), which can extend any RNN cell architecture. At each time step, instead of only looking at the current input vector, input-cell-attention uses a fixed-size matrix embedding, each row of the matrix attending to different inputs from current or previous time steps.  
Our proposed mechanism has been accepted as a paper in NeurIPs 2019.

## Additional context

![cellAttentionLstm-6](https://user-images.githubusercontent.com/9405315/65023407-c16ec400-d900-11e9-99ac-598c6eb419e8.png)

LSTM with input-cell-attention, at time t matrix X<sub>t</sub>=[x<sub>0</sub>,x<sub>1</sub> ,...,x<sub>t</sub> ] is passed to an attention mechanism; the output  A<sub>t</sub> is multiplied with X<sub>t</sub> to produce  M<sub>t</sub> (i.e  M<sub>t</sub>=A<sub>t</sub>X<sub>t</sub>). Matrix M<sub>t</sub> is now the input to LSTM cell (M<sub>t</sub> has dimension r x N, where r is the attention parameter and N is the number of inputs).

cc @zou3519

**Comment by cpuhrsch** [comment]
Aside from adding this feature for its benefits, are there other reasons you want to see it merged into core PyTorch (as opposed to living out of tree in a research repo)?

**Comment by ayaabdelsalam91** [comment]
I think it’s a small enough piece of code that having a separate py package for it is overkill, it would also make it a lot easier to use and accessible for users within pyTorch

**Comment by cpuhrsch** [comment]
@ayaabdelsalam91 - Usually we don't add code to the core of PyTorch that is very new or non-standard even if doesn't take a lot of code, because it increases the API surface and complexity. The same applies here.

**Comment by Kaixhin** [comment]
If you would like to contribute this then https://github.com/pytorch/contrib would be a good place to do so.

**Comment by soumith** [comment]
closing based on discussion above
