### ISSUE TITLE
LayerNorm instance as parameter to TransformerEncoderLayer and TransformerDecoderLayer

### ISSUE THREAD

**Issue by Mrpatekful** [pytorch/pytorch#26342]
## 🚀 Feature

My request is regarding the new nn.Transformer modules, more precisely the [TransformerEncoderLayer](https://github.com/pytorch/pytorch/blob/2dac67386128b4023f25dad6a8456aaf3029b7a8/torch/nn/modules/transformer.py#L235) and `TransformerEncoderLayer`. My problem is that the layer normalization is not customizeable in these modules, contrary to `TransformerEncoder` and `TransformerDecoder` where it is passed as a parameter.

## Motivation

This feature would be useful if I would like to use a different layer normalization layer like [FusedLayerNorm](https://github.com/NVIDIA/apex/blob/3ae89c754d945e407a6674aa2006d5a0e35d540e/apex/normalization/fused_layer_norm.py#L70) from NVIDIA/apex.

## Pitch

A simple `layer_norm_builder_fn` passed as a parameter to Transformer*Layer __init__.

```python
class TransformerEncoderLayer(Module):

    def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1, activation="relu", layer_norm_builder_fn=None):
        super(TransformerEncoderLayer, self).__init__()
        self.self_attn = MultiheadAttention(d_model, nhead, dropout=dropout)
        # Implementation of Feedforward model
        self.linear1 = Linear(d_model, dim_feedforward)
        self.dropout = Dropout(dropout)
        self.linear2 = Linear(dim_feedforward, d_model)

        self.norm1 = LayerNorm(d_model) if layer_norm_builder_fn is None else layer_norm_builder_fn()
        self.norm2 = LayerNorm(d_model) if layer_norm_builder_fn is None else layer_norm_builder_fn()
        self.dropout1 = Dropout(dropout)
        self.dropout2 = Dropout(dropout)

        self.activation = _get_activation_fn(activation)

def main():
    d_model = 512
    layer_norm_builder = lambda: FusedLayerNorm(d_model)
    encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=8, layer_norm_builder_fn=layer_norm_builder)
    
```

cc @ezyang @gchanan @zou3519

**Comment by cpuhrsch** [comment]
Hello @Mrpatekful, in general it is not easy to add a lot of flags or many options to something well-defined and orthogonal. We intend to keep the API surface small, so that we can make sure it is fast and correct.

The code you wrote up is using MultiheadAttention as a building block and uses the other pieces to build up the version of the TransformerEncoderLayer you desire. MultiheadAttention here seems like a reasonable layer of abstraction for us to provide, because it makes it easier for you to do this research, but it'd be questionable to add to the generic module, because it makes it more complicated and difficult to maintain.

If however TransformerEncoder and TransformerDecoder already support this flag, the Layers should probably too, but maybe not via a generic, hard-to-optimize lambda.

**Comment by Mrpatekful** [comment]
The above code is copied from the original `TransformerEncoderLayer` with the extension of `layer_norm_builder_fn` parameter to the init function. `TransformerEncoder` supports this behavior by having a `norm` parameter for the `LayerNorm` instance. The reason I have proposed the lambda function solution contrary to simply using a simple `norm` parameter as in `TransformerEncoder` is that this module uses 2 normalization layers, so `norm1` and `norm2` has to be passed, which might be too verbose. Another solution is to clone the `norm` parameter like this:

```python
class TransformerEncoderLayer(Module):

    def __init__(self, d_model, nhead, dim_feedforward=2048, dropout=0.1, activation="relu", norm=None):
        super(TransformerEncoderLayer, self).__init__()
        
        ...

        self.norm1 = LayerNorm(d_model) if norm is None else norm
        self.norm2 = LayerNorm(d_model) if norm is None else copy.deepcopy(norm)

        ...
```

**Comment by zhangguanheng66** [comment]
In this case, we prefer some custom `TransformerEncoderLayer` / `TransformerDecoderLayer` fed to `TransformerEncoder` / `TransformerDecoder`.

As @cpuhrsch mentioned, we hope to maintain the API simple and small.
