### ISSUE TITLE
RPC ThreadPool threads could be eaten up and cause deadlock on too many nested RPC calls.

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#26362]
## 🐛 Bug

In the RRef protocol RFC, #23110, there is an implicit requirement that the RPC component (Now checked-in as RPCAgent) needs to support nested RPC calls, meaning that a RPC call could initiate another RPC call before it returns.

As a result, in the work queue of the ThreadPool, a work in the front could depends on the work in the back.

@pietern suggested that 
> There should be some kind of detector for this condition, otherwise people will spend time debugging hangs for the wrong reasons. I see 2 ways forward: 1) a stack depth counter tacked onto every call (easy, throw error if stack depth > some threshold that is <= number of threads in the agent), 2) disallow nested calls and make everything async first.

But the depth does not matter that much. 
It is nesting matters.
a bunch of 2-level nested calls in the work queue could also deplete all threads.

For example, 
1' is the inner call of an outer call 1,
2' is the inner call of an outer call 2,
3' is the inner call of an outer call 3,
3' is the inner call of an outer call 3,

| Taken by worker threads | Queued works     |
|-------------------------|------------------|
| {1, 2, 3, 4,}           | [1', 2', 3', 4'] |

This way, it takes up 8 slots in the ThreadPool work queue, but 4 threads are available.

## Proposal

I think the right way to fix there is an inner RPC called inside a scope of an outer RPC. 

the outer RPC saves the state and yield the thread.

Just like coroutine does on "await".

@mrshenli argued that

> not sure how this would work with TorchScript function

## To Reproduce

Reproduced in #24036

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by xush6528** [comment]
@pietern @mrshenli @zhaojuanmao

**Comment by mrshenli** [comment]
> Just like coroutine does on "await".

@xush6528 I agree with you, and have just synced with @zhaojuanmao on this as well. We need a way to allow users to implement async UDFs, but I am not sure what would be the best API for that.

**Comment by rohan-varma** [comment]
@mrshenli @xush6528 Is this issue still relevant and can we reproduce it? 

It seems like it's also about supporting async UDFs - should we retitle the issue to indicate that?

**Comment by xush6528** [comment]
@rohan-varma I think we can still eat up all threads now.

**Comment by mrshenli** [comment]
Async UDF is available now, closing this issue.

API: https://pytorch.org/docs/master/rpc.html#torch.distributed.rpc.functions.async_execution
Tutorial: https://pytorch.org/tutorials/intermediate/rpc_async_execution.html
