### ISSUE TITLE
Remove sync() and join() from RpcAgent interface.

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#26377]
sync() and join() interfaces in RpcAgent imply collective communication. Although, for torch.rpc() we would like this interface to only support point to point communication.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by pietern** [comment]
Even for point to point, it can be used to drain pending calls.

**Comment by pritamdamania87** [comment]
Probably `join` makes sense to drain all pending calls on the current node, although we shouldn't have `sync` since it implies collective communication.

**Comment by pietern** [comment]
Draining the current node isn't enough to assume the system can be terminated.

Also see #26984.

**Comment by pritamdamania87** [comment]
We had a discussion offline about this and we feel its best to move this logic outside of RPC agent. The proposal is:

1. RpcAgent provides a `shutdown(timeout)` interface, that users can call to wait for all RPCs send by this node to finish with a timeout. Probably rename `join` to this. 
2. We provide a `torch.distributed.sync_workers()` API which acts as a barrier when called on all processes. We can use this to have proper termination in case we don't have a master process. If we have a master process, we don't even need this.

In general the RpcAgent interface shouldn't have anything to do with termination detection, it should be done at a higher level by the application using the `sync_workers` API mentioned above.

**Comment by pietern** [comment]
I'm curious why you think it doesn't belong in the agent. The agent is effectively the message broker and therefore knows if there are still messages in flight, or to be received. Doing this outside the RPC agent means you'll have to add some API to grab these message counters and do exactly what's done in the termination detection code today.

Also, I'm not what `sync_workers` should do, if it's not the same drain as `join` minus the termination.

**Comment by pritamdamania87** [comment]
I think it doesn't belong in the RPC layer since the RPC layer should only support point to point communication. If we provide a `sync` API in the RPC layer, this implies collective communication and this is not something that every RPC backend can support easily. 

> The agent is effectively the message broker and therefore knows if there are still messages in flight, or to be received. Doing this outside the RPC agent means you'll have to add some API to grab these message counters and do exactly what's done in the termination detection code today.

This is where the application would deal with this rather than us dealing with this. The application would receive a bunch of futures for all messages in flight. If the application wants proper termination, they should wait on all the futures and then call `sync_workers`. If the application doesn't wait on the future, all bets are off and we don't provide any guarantees around waiting for the message in flight.

> Also, I'm not what sync_workers should do, if it's not the same drain as join minus the termination.

You are right, `sync_workers` is not something new, it's just a barrier across all the processes. The only difference is that this API is not in the RPC layer. My overall suggestion is that the RPC layer shouldn't worry about termination and just provide simple APIs that the application can use to properly terminate themselves.

**Comment by pritamdamania87** [comment]
@mrshenli @xush6528 Can we close this since its kind of a dup of https://github.com/pytorch/pytorch/issues/27647?

**Comment by mrshenli** [comment]
Sure
