### ISSUE TITLE
DistributedDataParallel : GPU0 occupied much more memory  

### ISSUE THREAD

**Issue by YoungDav** [pytorch/pytorch#26385]
setting follow https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py
I find GPU0 has much process (Dataloader of all rank), so it is easy OOM.
![WXWorkCapture_15687700016916](https://user-images.githubusercontent.com/24801393/65096153-9070bb00-d9f6-11e9-9ed2-57f9b4b360c3.png)
![企业微信截图_20190918093121](https://user-images.githubusercontent.com/24801393/65096320-1d1b7900-d9f7-11e9-9727-c9c7bc83e672.png)
anyone solve this problem? thanks

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

Do not tag people

**Comment by pietern** [comment]
@soumith FWIW it's the bot that tagged everyone, because the other bot tagged it as `distributed`.

**Comment by soumith** [comment]
oh lol, bots fighting!
