### ISSUE TITLE
pytorch inference fp16

### ISSUE THREAD

**Issue by JensenHJS** [pytorch/pytorch#26386]
The model is trained with fp32. I try to use .half() to change  layers and inputs to fp16. Actually，it indeed accelerate the inference. But its acceleration effect is far away from twice  of fp32. My platform is nvidia tx2. Its compute capability is 6.2. It supports fp16 very well. So what I want to ask is whether fp16 cannot be twice as fast as fp32 in pytorch. Looking for your reply.Thank you.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
