### ISSUE TITLE
torch cuda bug

### ISSUE THREAD

**Issue by Kunlun-Zhu** [pytorch/pytorch#26397]
🐛 Bug
With a CUDA 10.1 and RTX GPU.
When I try even the most simpliest code like
nums = torch.randn(2,2).cuda(), it show the above error
And torch.cuda.is_available() is True.
Any idea?

**Comment by izdeby** [comment]
Hi, @Kunlun-Zhu, can you update the description with the 
- pytorch version you are using
- error message

Until then i will have to close the issue, please reopen once you provide the details.
