### ISSUE TITLE
test_naughty_anomaly_access xfail aborts test suite

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#26404]
## 🐛 Bug

Running the tests for autograd consistently gives a segfault on both Manjaro and Arch Linux at the end of the test suite run.

EDIT: at first I thought this was due to the single xfailed test in `test_autograd.py`, but that's not the case. Even when all tests are all passed or skipped, the test suite doesn't exit cleanly.

## To Reproduce

```
$ python test/run_test.py
...
----------------------------------------------------------------------
Ran 1017 tests in 153.972s

OK (skipped=6, expected failures=1)
Traceback (most recent call last):
  File "test/run_test.py", line 441, in <module>
    main()
  File "test/run_test.py", line 433, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed! Received signal: SIGSEGV
```
The above is annoying, because it ends the whole test suite run rather than continuing with the next test file.

Other ways to see the same thing:
```
$ pytest test/test_autograd.py -v
...
test/test_autograd.py::TestAutograd::test_naughty_anomaly_access XFAIL [ 57%]
...
====== 1010 passed, 6 skipped, 1 xfailed, 12 warnings in 156.44 seconds ======
Segmentation fault (core dumped)
```

Or, for current master with the `expectedFailure` decorator changed to `skip`: `python test/run_test.py`

```
----------------------------------------------------------------------
Ran 1017 tests in 155.519s

OK (skipped=7)
Traceback (most recent call last):
  File "test/run_test.py", line 441, in <module>
    main()
  File "test/run_test.py", line 433, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed! Received signal: SIGSEGV
```

```
$ python test/test_autograd.py
...
----------------------------------------------------------------------
Ran 1017 tests in 154.388s

OK (skipped=7)
Segmentation fault (core dumped)
```
## Expected behavior

Tests should exit cleanly

## Environment

```
$ python torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 1.3.0a0+f2e9622
Is debug build: No
CUDA used to build PyTorch: 10.1.168

OS: Manjaro Linux
GCC version: (GCC) 8.3.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 430.14
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.3.0a0+f2e9622
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.0                         1    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] torch                     1.3.0a0+f2e9622           dev_0    <develop>
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
@rgommers I'm fine with deleting/disabling the test. It's testing a use case that really shouldn't ever show up in real practice. However, the function of the test *is* to show that we don't segfault in this case.

Can you easily get a backtrace of the segfault?

**Comment by rgommers** [comment]
This happened when building with conda compilers only, and after updating my conda env and system cuda, glibc et al., I can't reproduce this anymore (because the build with conda compilers fails earlier due to an unrelated issue). I've switched back to system gcc 9.1. So I'll close this, if I can reproduce later I will reopen with a backtrace.
