### ISSUE TITLE
Fuse operators inside of the (CPU) glu operator. 

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#26418]
Current implementation does sequential `sigmoid_out` and `mul_`. We can get better performance by fusing this operations together.

**Comment by f2013519** [comment]
I'll take this up. Is it mostly about adding a at::parallel_for?

**Comment by VitalyFedyunin** [comment]
This can be done after #26410 landed, and will require writing new ternary loop which does sigmoid and mul in one loop.

**Comment by f2013519** [comment]
Sure, I'll wait for that. I've used pytorch before, but I'm new to the codebase.

 Can you pls. sketch out roughly how to go about adding this support, like which API's to use, which files may need to updated, or a PR that does something similar?

Thanks!

**Comment by gchanan** [comment]
I'm actually going to take this because I want an end-to-end change to benchmark.
