### ISSUE TITLE
We should decide if hypothesis is required or not

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#26429]
If I read the following code, I would expect that hypothesis is not required:
https://github.com/pytorch/pytorch/blob/a561660241defbfa5448222ce6e1816bcacf1178/test/common_utils.py#L419-L428

but then if I run `python test/test_nn.py` I hard fail because of:
https://github.com/pytorch/pytorch/blob/52d999e17345594403a38af4909703f1944e28ef/test/test_nn.py#L42

At least on my conda install (python 3.6), installing hypothesis requires python 3.7, which is a pretty bad user experience.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by dzhulgakov** [comment]
In general having hypothesis is pretty nice for exhaustive testing (if it's used right). So it'd be nice to figure out a way to always install it for dev environments (it obviously is not needed for actual pytorch).

For conda - can you install it from `pip` instead?

**Comment by zafartahirov** [comment]
I think it's a must to have it on CI's, but I don't think the users need it. We can change it in the `test_nn.py` the same way it is in the `common_utils.py`. What do you say?

**Comment by z-a-f** [comment]
Bump @gchanan @dzhulgakov

**Comment by gchanan** [comment]
> We can change it in the test_nn.py the same way it is in the common_utils.py. What do you say?

sgtm.
