### ISSUE TITLE
Exception in autograd profiler total_average() calculation

### ISSUE THREAD

**Issue by kossnick** [pytorch/pytorch#26433]
(Directed to post here from https://discuss.pytorch.org/t/autograd-profiler-total-average-calculation-exception/56214.)

I had written a layer on top of the autograd profiler to collect more custom ranges of times, and with the upgrade to Pytorch 1.2 my usage is no longer working.

When a designated timing range begins, I have the following snippet (among a longer block in my codebase):
```
records = torch.autograd._disable_profiler()
events_average = EventList(parse_cpu_trace(records)).total_average()
cpu_time = events_average.cpu_time_total / 1000
cuda_time = events_average.cuda_time_total / 1000
```

When it runs, the `.total_average()` call in pytorch, at [this line](https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py#L184) (total_stat += evt) crashes with the Exception: TypeError: unsupported operand type(s) for +=: 'FunctionEventAvg' and 'FunctionEvent'. I noticed FunctionEventAvg doesn’t have a __add__ override, but [used to](https://github.com/pytorch/pytorch/blob/8c3a94eaf2ee8cf5100cbb1252e9f56e871b24ee/torch/autograd/profiler.py#L413). Seems like it changed with [this commit](https://github.com/pytorch/pytorch/commit/864cfbc2162a874fd67b50414205483cb9ac6b5d).

I modified the source to change `+=` to `.add` and it seems to work now. Should `FunctionEventAvg` have an `__iadd__` method like it used to? Or should the `+=` be changed to `.add`? Am I using it wrong?

Thanks!

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
Unfortunately Alexander Sidorov doesn't work on PyTorch anymore. I think there is not a good reason to not have the `__iadd__` overload, and would be happy to review a patch that added it back (implemented by calling `add`, I suppose.)

**Comment by kozzles** [comment]
PR opened at https://github.com/pytorch/pytorch/pull/27498. Thanks!

**Comment by albanD** [comment]
Associated PR has been merged.
