### ISSUE TITLE
Is there any plan for privacy-preserving interface or implementation in the future?

### ISSUE THREAD

**Issue by ssdyue** [pytorch/pytorch#26449]
## 🚀 Feature

Differential privacy or homomorphic encryption, or other privacy-preserving methods

## Motivation

Some ethical and privacy concerns has attracted public attention, and it is Increasingly important. Such as the General Data Protection Regulation (GDPR).

**Comment by soumith** [comment]
https://github.com/OpenMined/PySyft is one option.
Some other packages related to this will be announced soon.

In core pytorch, we haven't had need to add anything directly, even if they are released they will be separate packages.
