### ISSUE TITLE
Tensor.Scatter_ misleading error message

### ISSUE THREAD

**Issue by siarez** [pytorch/pytorch#2646]
```
>>> torch.zeros(3, 4).scatter_(0, torch.LongTensor([[2, 2, 2],[1, 1,1],[0, 0,0]]), torch.arange(1,13).resize_(3, 4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected tensor [3 x 4], src [3 x 4] and index [3 x 3] to have the same size in dimension 0 at /Users/soumith/miniconda2/conda-bld/pytorch_1502000975045/work/torch/lib/TH/generic/THTensorMath.c:470
```
src and index do in fact have the same size in dimension 0 (both are 3). They should have the same size in dimension 1.
This works fine:
`torch.zeros(3, 4).scatter_(0, torch.LongTensor([[2, 2, 2, 2],[1, 1,1,1],[0, 0,0,0]]), torch.arange(1,13).resize_(3, 4))`

**Comment by beantowel** [comment]
Definitily right! The `scatter_` is supposed to scatter `src` via `index`, so in ALL dimension the Tensors should have the same size EXCEPT for the `dim`! The error message was misleading, hope for a quick fix.

**Comment by mruberry** [comment]
This works for me on nightly. Closing due to age - do you still encounter an error here? Please comment/reopen if so!
