### ISSUE TITLE
Pytorch 1.2 on Red Hat Enterprise Linux 6.4 gives 'GLIBC_2.14' not found

### ISSUE THREAD

**Issue by CA4GitHub** [pytorch/pytorch#26467]
## 🐛 Bug

Description:
On a server running Red Hat Enterprise Linux (RHEL) Workstaion release 6.4 (Santiago), I used conda 4.5.12 to install pytorch using the following command:
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

The python version installed is 3.7.4.

When I open a python interpreter, I try to import pytorch via the command:
import pytorch

However, I get the following error:

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/programs/advanced_data_analytics/CMAP/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /programs/advanced_data_analytics/CMAP/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libshm.so)

## To Reproduce
Command line steps to reproduce the behavior On RHEL 6.4:

1. conda create --name pytorch
2. conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
3. conda activate pytorch
4. python
5. import pytorch

cc @ezyang

**Comment by ezyang** [comment]
Your glibc is too old to run our binary build of PyTorch. You will need to build PyTorch from source. Sorry.
