### ISSUE TITLE
Error when loading an "empty" state_dict of torch.optim.Adam

### ISSUE THREAD

**Issue by Cadene** [pytorch/pytorch#2647]
Hello,

I know it is not a common use case, but I encounter an issue after having loaded the state_dict of Adam if the `step` method of the optimizer has not been executed.

However it works well with SGD.

You need to run this code twice (first time to save the state_dict) to reproduce the error.

```python
import os
import torch
import torch.nn as nn

BUG = True
optim_name = 'Adam' # works with SGD

model = nn.Linear(2,1)
optimizer = torch.optim.__dict__[optim_name](model.parameters(), 1e-4)
state_dict = optimizer.state_dict()
path_state = 'state_dict_{}.pth'.format(optim_name)

if not os.path.isfile(path_state):
    torch.save(state_dict, path_state)
else:
    if BUG:
        optimizer.load_state_dict(torch.load(path_state))
    loss = model(torch.autograd.Variable(torch.randn(1,2)))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```

```
Traceback (most recent call last):
  File "optimizer.py", line 21, in <module>
    optimizer.step()
  File "/home/cadene/anaconda3/lib/python3.5/site-packages/torch/optim/adam.py", line 46, in step
    state = self.state[p]
KeyError: Parameter containing:
-0.0645  0.1660
[torch.FloatTensor of size 1x2]
```

I solved the problem with a little hack:

```python
...
state_dict = torch.load(path_state)
if len(state_dict['state']) != 0:
    optimizer.load_state_dict(state_dict
...
```

**Comment by Connor323** [comment]
Hi @Cadene, I also meet the same problem. When I save the state_dict of Adam optim, it is empty in the 'state' entry; so when I retrain the model, it always throws a keyerror. I'm wondering is this a bug in pytorch itself?

**Comment by greaber** [comment]
@randxie , I am currently using the workaround provided by @Cadene, which works fine, but I was thinking it could be good to properly resolve this issue.  I am still confused about why it arises, unfortunately, and therefore also on how it should be fixed.  (But at least there is a very small amount of code involved, so it should not be hard to figure out.)  Do you understand what is going on?  Any chance your recent PR #2796 addressing issue #1488 might fix this problem as well?

**Comment by mruberry** [comment]
Closing due to age and the script running successfully for me on nightly. Please reopen comment if this is still an issue!
