### ISSUE TITLE
[ONNX] support scater_add with dynamic tensor shapes

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#26472]
## 🐛 Bug

I was getting this error

> RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:341 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 \|\| axis == largest was false. Attempting to  broadcast an axis by a dimension other than 1. 0 by 6

An could not figure out where `6` was coming from. `6` is `shape[0]` of an intermediate tensor when `torch.onnx.export` was called, but it is dynamic.

`scatter_add` creates a constant with a fixed size:

```python
@parse_args('v', 'i', 'v', 'v')
def scatter_add(g, self, dim, index, src):
    if self.type().kind() != "CompleteTensorType":
        return _unimplemented("scatter_add", "input size not accessible")
    dtype = self.type().scalarType()
    dtype = sym_help.scalar_type_to_onnx.index(sym_help.cast_pytorch_to_onnx[dtype])
    dims = self.type().sizes()
    to_add = torch.zeros(dims)
    to_add = g.op("Constant", value_t=to_add)
    to_add = scatter(g, to_add, dim, index, src)
    return add(g, self, to_add)
```

## To Reproduce

Use scatter_add along with a dynamic tensor input

```python
    cond = input_x < 0
    idx = torch.nonzero(cond).view(-1)  # idx is dynamic shape
    w = torch.scatter_add(w, 0, idx, input_x[idx])  # w[idx] += input_x[idx]
    input_x = torch.where(cond, zero, input_x)  # input_x[idx] = 0
```

## Expected behavior

`scatter_add` should not assume fixed tensor sizes

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

Workaround is to avoid `scatter_add` and use `where`

Used this workaround:

```python
w = torch.scatter(w, 0, idx, w[idx] + input_x[idx])  # w[idx] += input_x[idx]
```

**Comment by mrshenli** [comment]
cc @houseroad

**Comment by leimao** [comment]
I am getting the exactly error from my ONNX model. I am having difficulty locating it to my PyTorch code. I don't have `scatter_add`. Is `where` an suspicious place to look at?

**Comment by dashesy** [comment]
@leimao [add node names](https://github.com/pytorch/pytorch/issues/26035):

```python
onnx_model = onnx.load(onnxfile)

graph = onnx_model.graph
nodes = graph.node

# for debugging
count = 0
for node in nodes:
    if not node.name:
        node.name = "__" + node.op_type + "_" + str(count)
        count = count + 1
onnx.save(onnx_model, onnxfile)
```

Then see which opt it is (search in NetRon)

**Comment by ShunChengWu** [comment]
facing the same issue. The workaround doesn't work with two-dimensional indices.
Is it possible to add the support of dynamic tensor shapes?

**Comment by shubhambhokare1** [comment]
Hi @dashesy ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
