### ISSUE TITLE
How to keep the same Dropout mask for different batches

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#2649]
Suppose we have 2 minibatch (each with 10 data point). When turning on the dropout for forward pass of first minibatch, the dropout mask with dimension 10 is generated. What if we want to use the same mask for the second batch of data ?

**Comment by soumith** [comment]
answered here: https://discuss.pytorch.org/t/how-to-fix-the-dropout-mask-for-different-batch/7119
