### ISSUE TITLE
How to convert to older version of pytorch v0.1.12?

### ISSUE THREAD

**Issue by DabiaoMa** [pytorch/pytorch#2650]
As a new user of pytorch, I first installed the latest version v0.2. While it seems like the latest is not fully compatible with version 0.1.12.

So how can I switch between the two versions?

**Comment by soumith** [comment]
`conda install pytorch=0.1.12 cuda80 -c soumith`
We'll update the docs soon to give links to older versions.

**Comment by soumith** [comment]
closing in favor of #2689
