### ISSUE TITLE
PyTorch "previous versions" install instructions are confusing

### ISSUE THREAD

**Issue by dhruvsus** [pytorch/pytorch#26510]
## ❓ Questions and Help
I'm trying to download pytorch to run on my university machines that have CUDA 9. The link at:
https://download.pytorch.org/whl/cu90/torch_stable.html however, doesn't seem to work.

cc @ezyang @gchanan @zou3519

**Comment by colesbury** [comment]
Yeah, this isn't good. You can view the links by choosing "view source" as a workaround.

The instructions on https://pytorch.org/get-started/previous-versions/ are also confusing. The URLs should be links -- you shouldn't have to copy-paste them.

**Comment by colesbury** [comment]
Also @pravitc reports access denied errors in https://github.com/pytorch/pytorch/issues/26542

**Comment by ezyang** [comment]
I regenerated the index html to render without view-source.

**Comment by ezyang** [comment]
For reference, the command I ran was:

```
CUDA_VERSIONS=cu90 AWS_ACCESS_KEY_ID=redacted AWS_SECRET_ACCESS_KEY=redacted HTML_NAME=torch_stable.html PIP_UPLOAD_FOLDER= cron/update_s3_htmls.sh
```

in https://github.com/pytorch/builder

**Comment by pravitc** [comment]
@ezyang the issue pointed out by @colesbury is not fixed yet. The links to older versions on https://pytorch.org/get-started/previous-versions/ are not updated. So if someone tries to open those links still produce the access denied error. This will lead any other user to raise a new issue.
