### ISSUE TITLE
get wrong version of cuda

### ISSUE THREAD

**Issue by txdat** [pytorch/pytorch#2651]
pytorch got wrong cuda version (only get 7.5 while cuda 8.0 installed), not work with compute_61, stop while compiling THC module. anyone has solution? thanks!

-- Found gcc >=5 and CUDA <= 7.5, adding workaround C++ flags
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 6.1
-- got cuda version 7.5
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by soumith** [comment]
maybe you have some conflicting versions of CUDA in your install? does /usr/local/cuda/lib64/ have any CUDA 7.5 libs lying around?

**Comment by txdat** [comment]
thank you. i installed cuda 7.5 alongside with 8.0
