### ISSUE TITLE
from torch._C import * ModuleNotFoundError: No module named 'torch._C'

### ISSUE THREAD

**Issue by gauravgoenka** [pytorch/pytorch#26526]
## 🐛 Bug

I have manually installed torch .whl from pypi.
unzipped it and got three folders 
1. torch
2. caffe2
3. torch-1.2.0.dist-info

![image](https://user-images.githubusercontent.com/30654421/65300364-ccd81e80-db90-11e9-8d1c-3a86c3b4ba60.png)

now i am in my python and tried importing torch and getting the bellow error
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Gaurav\pytorch-master\torch\__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

**Comment by peterjc123** [comment]
Please do that in a different location. The correct way to import with installing it is listed below.
```cmd
cd D:\
set PYTHONPATH=D:\Gaurav\pytorch-master
python -c "import torch"
```

**Comment by gauravgoenka** [comment]
> Please do that in a different location. The correct way is listed below.
> 
> ```batchfile
> cd D:\
> :: Suppose your dir to the unzipped whl is `D:\Gaurav\pytorch-master`
> :: If you installed it, please ignore this line.
> set PYTHONPATH=D:\Gaurav\pytorch-master 
> python -c "import torch"
> ```
> 
> P.S. If you have a script called `torch.py`, please rename it before calling `import torch`.

I tried the above solution

(base) D:\Gaurav\pytorch-master>cd ..

(base) D:\Gaurav>set PYTHONPATH=D:\Gaurav\pytorch-master

(base) D:\Gaurav>python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Gaurav\pytorch-master\torch\__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

But still getting the same error.

**Comment by gauravgoenka** [comment]
Is it got to do with some library or dependencies that i need to install?


    import torch
  File "D:\Anaconda3_32\lib\torch\__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

**Comment by peterjc123** [comment]
Wait, are you using Python 32-bit? Please use 64-bit Python instead.

**Comment by gauravgoenka** [comment]
Even after updating to 64 bit python i am still getting the same error:


Case 1: When i am using the torch package that i unzipped from : https://pypi.org/project/torch/#files

(base) D:\Gaurav>python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3_64\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

case 2: when i downloaded pytorch from :https://github.com/pytorch/pytorch#installation
(base) D:\Gaurav>cd pytorch-master
(base) D:\Gaurav\pytorch-master>python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Gaurav\pytorch-master\torch\__init__.py", line 81, in <module>
    from torch._C import *
ModuleNotFoundError: No module named 'torch._C'

**Comment by peterjc123** [comment]
We didn't host the Windows package on PyPI. You can refer to the build steps on https://pytprch.org. If you don't want to install, then just cancel the download process using ctrl+c and you'll find it in the log.

**Comment by peterjc123** [comment]
There should be a file like `_C.cp36-win_amd64.pyd` in the unzipped directory. Just check the following several things:
1. Don't do `import torch` inside the unzipped dir.
2. Don't do `import torch` inside the root dir of the git repo.
2. Don't write a script `torch.py` under the current dir.

**Comment by gauravgoenka** [comment]
Thank you :)
Really appreciate your help.

I guess i was not unzipping the correct torch whl file.

After downloading the correct windows torch whl file i was able to resolve the issue,

I downloaded the "cu100/torch-1.2.0-cp37-cp37m-win_amd64.whl"
from https://download.pytorch.org/whl/torch_stable.html

**Comment by zubairahmed-ai** [comment]
Confirmed I had higher version of these installed on Windows 10 for CUDA 9.2 and got same error but after installing `torch-1.3.0+cu92-cp36-cp36m-win_amd64.whl` and `torchvision-0.4.1+cu92-cp36-cp36m-win_amd64.whl` from Torch Stable as pointed by @gauravgoenka it worked for me
