### ISSUE TITLE
pytorch1.2 block numpy array's multipy???

### ISSUE THREAD

**Issue by zzzkk2009** [pytorch/pytorch#26530]
### pytorch1.2 slows numpy array's multipy???

```
import numpy as np
import torch

print(torch.__version__)
image_numpy_t = np.random.random_sample((3, 652, 652))
print(111)
image_numpy_t = image_numpy_t * 254.0
print(image_numpy_t)
```

when i run this code in torch 1.2, it will block at "image_numpy_t = image_numpy_t * 254.0" this line, but when i comment "import torch" or use torch0.4, rerun this code can get image_numpy_t correct value.

**Comment by colesbury** [comment]
There isn't enough information here to help with the issue. Please provide at least the basic information in the issue template (and re-open the issue).
