### ISSUE TITLE
`torch.zeros` produces error: `RuntimeError: cuda runtime error (30)`

### ISSUE THREAD

**Issue by ThisIsIsaac** [pytorch/pytorch#26532]
## 🐛 Bug

error when creating tensor on GPU

## To Reproduce

```python
>>> import torch
>>> zero_tensor = torch.zeros(1, device="cuda")
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/isaac/.virtualenvs/cityflow/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB

Nvidia driver version: 418.87.00
cuDNN version: /usr/local/cuda-10.0/lib64/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.0.0
[conda] Could not collect

## Additional context

Pytorch used to work just fine, but it suddenly doesn't work even without any update.

**Comment by colesbury** [comment]
Please follow up if you figure out what's wrong. The "cuda runtime error (30)" is a generic error; it doesn't give much information. Check `nvidia-smi` etc; restart your computer; re-install CUDA drivers; etc.

**Comment by ThisIsIsaac** [comment]
I get `torch.cuda.is_available() == False`.

**Comment by ThisIsIsaac** [comment]
Rebooting the server fixed the problem.
