### ISSUE TITLE
about div by zero

### ISSUE THREAD

**Issue by Lmy0217** [pytorch/pytorch#26538]
## 🐛 Bug
The situation about div by zero is more complex.

## To Reproduce
```
0/torch.tensor(0)
tensor(-9223372036854775808)

1/torch.tensor(0)
tensor(-9223372036854775808)

0./torch.tensor(0)
tensor(-9223372036854775808)

1./torch.tensor(0)
tensor(-9223372036854775808)

torch.tensor(0)/0
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(1)/0
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(0.)/0
tensor(nan)

torch.tensor(1.)/0
tensor(inf)

torch.tensor(0)/torch.tensor(0)
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(1)/torch.tensor(0)
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(0.)/torch.tensor(0)
tensor(nan)

torch.tensor(1.)/torch.tensor(0)
tensor(inf)


0/torch.tensor(0.)
tensor(nan)

1/torch.tensor(0.)
tensor(inf)

0./torch.tensor(0.)
tensor(nan)

1./torch.tensor(0.)
tensor(inf)

torch.tensor(0)/0.
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(1)/0.
Process finished with exit code -1073741676 (0xC0000094)

torch.tensor(0.)/0.
tensor(nan)

torch.tensor(1.)/0.
tensor(inf)

torch.tensor(0)/torch.tensor(0.)
tensor(nan)

torch.tensor(1)/torch.tensor(0.)
tensor(inf)

torch.tensor(0.)/torch.tensor(0.)
tensor(nan)

torch.tensor(1.)/torch.tensor(0.)
tensor(inf)
 ```

## Environment
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: version 3.12.0-rc3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 419.35
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.4.3
[pip3] numpy==1.17.0
[pip3] torch==1.2.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchstat==0.0.7
[pip3] torchvision==0.4.0
[conda] Could not collect

**Comment by colesbury** [comment]
Let's track the segmentation fault in https://github.com/pytorch/pytorch/issues/327.

The `0/torch.tensor(0)` is a new one... that's interesting
