### ISSUE TITLE
F.conv_transpose2d inside Function doesn't use Cudnn

### ISSUE THREAD

**Issue by MatthieuBizien** [pytorch/pytorch#26537]
## 🐛 Bug

When I define a custom `torch.autograd.Function` that call `torch.nn.functional.conv_transpose2d`, Cudnn is not called.

## To Reproduce

1. Enable Cudnn logging with `export CUDNN_LOGINFO_DBG=1; export CUDNN_LOGDEST_DBG=/tmp/cudnn/log`
1. Define and call a custom Function that call `F.conv_transpose2d`
1. Check the logs: they are empty

Example:
```
import torch
from torch.nn import functional as F
from torch.autograd import Function
class FunctionConvTranspose2d_(Function):
    @staticmethod
    def forward(ctx, input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1):
        return F.conv_transpose2d(input, weight, bias, stride, padding, dilation, groups)
x = torch.rand((1, 8, 32, 32)).cuda().requires_grad_()
weight = torch.rand(8, 8, 8, 1).cuda().requires_grad_()
bias = torch.rand(8).cuda().requires_grad_()
FunctionConvTranspose2d_.apply(x, weight, bias, 2)
```

## Expected behavior

Cudnn should be called. If we replace `FunctionConvTranspose2d_.apply` by `F.conv_transpose2d`, the logs are not empty.

## Environment

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.17.1
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

## Additional context

`F.conv2d` works correctly inside a `Function`.

Code and demo at https://gist.github.com/MfatthieuBizien/97b86866e1dfb40872306c58544366e4/revisions 

## Additional questions

1. Is there a workaround?
2. What performance impact can I expect?
3. If I want to patch that, where should I look?

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by colesbury** [comment]
The order of your arguments to conv_transpose2d is wrong:

You have:

```
input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
```

The docs list:

```
input, weight, bias=None, stride=1, padding=0, output_padding=0, groups=1, dilation=1
```

https://pytorch.org/docs/stable/nn.functional.html#conv-transpose2d

So you're setting output_padding, which probably disabled cuDNN and also is probably not what you want.

If this isn't the case, please re-open the issue.
