### ISSUE TITLE
Access denied when downloading older version 

### ISSUE THREAD

**Issue by pravitc** [pytorch/pytorch#26542]
Hi,

For my project I need to install older version (0.4.1) of the PyTorch. But when I try to access the site ( https://download.pytorch.org/whl/cu90/torch_stable.html # CUDA 9.0 build ) to download whl for the older version I encountered an access denied error (as shown in the image below). Is there any way to fix this? Thanks.

![image](https://user-images.githubusercontent.com/39347062/65338316-3294cc80-dbca-11e9-85fc-f9d00296cd31.png)

**Comment by colesbury** [comment]
Thanks for reporting this. Tracking this issue in https://github.com/pytorch/pytorch/issues/26542

**Comment by ziyuang** [comment]
This happens for libtorch 1.8.2 LTS: https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-1.8.2%2Bcu111.zip

**Comment by quantumxt** [comment]
Hi there, am encountering an Access denied issue too while trying to install 1.8 LTS: https://download.pytorch.org/whl/lts/1.8/cu111

**Comment by joshdebelec** [comment]
Still happening :( 

CPU is fine, CUDA is not... 

![image](https://github.com/pytorch/pytorch/assets/20903421/f16a8b7c-2e74-498a-a2a1-e7d712708cf5)
