### ISSUE TITLE
`ATen/Functions.h` does not exist after calling `scripts/build_android.sh`

### ISSUE THREAD

**Issue by RuABraun** [pytorch/pytorch#26540]
## 🐛 Bug

Trying to compile pytorch for android, calling `scripts/build_android.sh` for that. Afterwards when trying to use the libraries (torch, c10 etc) via the header `torch/script.h` inside an app I'm getting an error:

    aten/src/ATen/ATen.h:12:10: fatal error: 'ATen/Functions.h' file not found

And indeed, using `find` to search for `Functions.h` only results in:

    ./tools/autograd/templates/Functions.h
    ./aten/src/ATen/templates/Functions.h

Remember this is *after* calling `scripts/build_android.sh` (so I would have hoped to find it somewhere under `build_android/install`).

It is requested because `torch/script.h` calls `torch/csrc/api/include/torch/types.h` calls `torch/csrc/api/include/torch/types.h` which calls `ATen/ATen.h` which has a line `#include <ATen/Functions.h>`.

## To Reproduce

1. git clone etc.
2. scripts/build_android.sh
From here it should already be clear that `ATen/Functions.h` does not exist but is required. To actually get an error:
3. Try and build app in AndroidStudio with `torch/script.h` and relevant libraries linked.

## Expected behavior

I expect `ATen/Functions.h` to exist after calling `scripts/build_android.sh`.

## Environment

```
PyTorch version: 1.3.0a0+f433ee1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GT 1030
GPU 2: GeForce GTX 1080 Ti

Nvidia driver version: 418.87.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.1
[pip3] torch==1.3.0a0+f433ee1
[pip3] torchvision==0.3.0a0+250bac8
[conda] Could not collect

```

**Comment by colesbury** [comment]
`Functions.h` is a generated file (from the template). It looks 

I'm not familiar with scripts/build_android. @ljk53, are you familiar with the Android build process?

**Comment by RuABraun** [comment]
Any updates?

**Comment by ljk53** [comment]
@RuABraun build_android.sh was originally created to build caffe2 library instead of pytorch library. We are working on making it build pytorch. You can experiment it with:
```
export BUILD_PYTORCH_MOBILE=1
scripts/build_android.sh
```
We will add detailed docs / tutorials about pytorch mobile soon.

**Comment by RuABraun** [comment]
I get another problem now. Progress!
