### ISSUE TITLE
Build failure (sleef.h not found) in some hard-to-understand situations

### ISSUE THREAD

**Issue by mratsim** [pytorch/pytorch#26555]
## 🐛 Bug

I installed pybind11 v2.3.0 systemwide (for fastText). PyTorch build system detects it, use it but then build fails.

## To Reproduce

Install pybind11 v2.3.0 system wide (distro used, Arch linux with the [following build script
](https://github.com/mratsim/Arch-Data-Science/blob/2739b1aa5bd1c955d15e9f8fd67087931bf623af/frameworks/python-pytorch-magma-mkldnn-cudnn-git/PKGBUILD#L38-L112)
The build will fail with sleef visibility issue:
```
[ 83%] Building CXX object caffe2/CMakeFiles/thread_init_test.dir/__/aten/src/ATen/test/thread_init_test.cpp.o
[ 83%] Building CXX object caffe2/CMakeFiles/cuda_tensor_interop_test.dir/__/aten/src/ATen/test/cuda_tensor_interop_test.cpp.o
[ 83%] Building CXX object caffe2/CMakeFiles/tensor_iterator_test.dir/__/aten/src/ATen/test/tensor_iterator_test.cpp.o
[ 83%] Building CXX object caffe2/CMakeFiles/native_test.dir/__/aten/src/ATen/test/native_test.cpp.o
[ 83%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state.cc.o
[ 83%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state.cc.o
In file included from /pkg/makepkg/buildpkg/python-pytorch-magma-mkldnn-cudnn-git/src/pytorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /pkg/makepkg/buildpkg/python-pytorch-magma-mkldnn-cudnn-git/src/pytorch/aten/src/ATen/native/cpu/Loops.h:34,
                 from /pkg/makepkg/buildpkg/python-pytorch-magma-mkldnn-cudnn-git/src/pytorch/aten/src/ATen/test/tensor_iterator_test.cpp:6:
/pkg/makepkg/buildpkg/python-pytorch-magma-mkldnn-cudnn-git/src/pytorch/aten/src/ATen/cpu/vec256/vec256_float.h:6:10: fatal error: sleef.h: No such file or directory
 #include <sleef.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [caffe2/CMakeFiles/tensor_iterator_test.dir/build.make:63: caffe2/CMakeFiles/tensor_iterator_test.dir/__/aten/src/ATen/test/tensor_iterator_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3877: caffe2/CMakeFiles/tensor_iterator_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state.dir/python/pybind_state_dlpack.cc.o
[ 83%] Linking CXX executable ../bin/fatal_signal_asan_no_sig_test
[ 83%] Built target fatal_signal_asan_no_sig_test
```

Rebuilding the same commit (4444b91141) without systemwide Pybind11 works

## Expected behavior

Successful build

## Environment

 - PyTorch Version (e.g., 1.0): source
 - OS (e.g., Linux): Arch
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): https://github.com/mratsim/Arch-Data-Science/blob/2739b1aa5bd1c955d15e9f8fd67087931bf623af/frameworks/python-pytorch-magma-mkldnn-cudnn-git/PKGBUILD#L38-L112
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by colesbury** [comment]
The error message doesn't look like it it's related to pybind11. The failure is in tensor_iterator_test.cpp, which does not use pybind11.

If you've checked out PyTorch from source, make sure you've got all the submodules up-to-date:
`git submodule sync --recursive` `git submodule update --init --recursive`. Also check `git status` for local changes. If all else fails, try a clean check out.

**Comment by mratsim** [comment]
The error is:

```
/pkg/makepkg/buildpkg/python-pytorch-magma-mkldnn-cudnn-git/src/pytorch/aten/src/ATen/cpu/vec256/vec256_float.h:6:10: fatal error: sleef.h: No such file or directory
 #include <sleef.h>
          ^~~~~~~~~
```

I'm not too sure of what's going on either but it seems like the sleef.h file is autogenerated. COuld it be that the generation order of this sleef.h is impacted by the presence or absence of system pybind11?

**Comment by jamesr66a** [comment]
I've seeen this occur when I pass AVX flags like `-mavx2` as CFLAGS to the PyTorch build. I think there are some issues in the CMake files that cause sleef to not be included in such a situation. I don't see anything from your build script that might suggest that's what's happening, though

**Comment by jamesr66a** [comment]
Ah! ` export USE_NATIVE_ARCH=ON`. That's gotta be the trigger. Does your build succeed without that?

**Comment by mratsim** [comment]
Unfortunately even with `export USE_NATIVE_ARCH=OFF` it still failed.
This was after a clean checkout.

New tentative script with changes:
- no USE_NATIVE_ARCH
- BUILD_CAFFE2_OPS (didn't realize those were necessary for MKLDNN)
- USE_GFLAGS and USE_GLOG to ensure command-line flags are in the configuration recommended by the build system

rebuilding without system pybind and with third_party/pybind after those changes unfortunately fails as well. Renaming as pybind is not the core issue.

**Comment by mratsim** [comment]
> I've seeen this occur when I pass AVX flags like `-mavx2` as CFLAGS to the PyTorch build. I think there are some issues in the CMake files that cause sleef to not be included in such a situation. I don't see anything from your build script that might suggest that's what's happening, though

It seems like mavx2 is appended regardless of the USE_NATIVE_ARCH=ON:

https://github.com/pytorch/pytorch/blob/aa7852346772ddf10b0caf589d106ab96fc44955/cmake/Codegen.cmake#L102-L120

Looking into my build folder after failure I do have `./build/include/sleef.h` so it probably can be solved with a cmake include, but it should be set by the following code: https://github.com/pytorch/pytorch/blob/aa7852346772ddf10b0caf589d106ab96fc44955/aten/src/ATen/CMakeLists.txt#L222-L258

**Comment by mratsim** [comment]
Seems like duplicate of #26403 (USE_NATIVE_ARCH as well). Will reconfirm in a clean slate repo

Note that BUILD_TESTS=OFF allow the build to succeed, but due to #26597, PyTorch cannot be used at all.

**Comment by mratsim** [comment]
USE_NATIVE_ARCH=OFF and MKLDNN_USE_NATIVE_ARCH=OFF were not enough.

In the end I removed the offending test from the build script with:
```
sed -i 's#^  ${CMAKE_CURRENT_SOURCE_DIR}/tensor_iterator_test.cpp##g' aten/src/ATen/test/CMakeLists.txt
```

Link to working build: https://github.com/mratsim/Arch-Data-Science/blob/48b4ad3b868acffb2eee47dfc6dcfe22e76a9cb7/frameworks/python-pytorch-magma-mkldnn-cudnn-git/PKGBUILD#L54-L56

Several past experiments can be seen in the history of that file.

**Comment by MaeThird** [comment]
there is a `sleef.h` file in `torch/include` but the actually needed one is generated during compiling and lies in `build/include`.So add one line as `include_directories(${CMAKE_CURRENT_SOURCE_DIR}/../include/)` to the `aten/CMakeLists.txt`.It's work although ugly.

**Comment by smartnet-club** [comment]
To fix, add to [caffe2/CMakeLists.txt](https://github.com/pytorch/pytorch/blob/50d82f51223726725317919d429a02979d9bc39c/caffe2/CMakeLists.txt#L1155) after line 1155

`target_include_directories(${test_name} PRIVATE $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>)`

**Comment by jjdredd** [comment]
@smartnet-club Thanks, that helped!

**Comment by AmericanEnglish** [comment]
> 
> 
> To fix, add to [caffe2/CMakeLists.txt](https://github.com/pytorch/pytorch/blob/50d82f51223726725317919d429a02979d9bc39c/caffe2/CMakeLists.txt#L1155) after line 1155
> 
> `target_include_directories(${test_name} PRIVATE $<BUILD_INTERFACE:${CMAKE_BINARY_DIR}/include>)`

I would like to second this idea. This fixed the build error for me as well. It definitely seems to be a problem using MKLDNN even at commit 2de4f245c6b1e1c294a8b2a9d7f916d43380af4b the issue persists but the suggested fix works.

**Comment by aluo-x** [comment]
Also encountering this error. Bumping for visibility.

**Comment by rahulunair** [comment]
Also facing this issue when using `-march=skylake-avx512` to build pytorch

**Comment by aluo-x** [comment]
@ezyang Could a fix based on [pull request #35359](https://github.com/pytorch/pytorch/pull/35359) be merged? Looks like it needs a rebase, but the original author abandoned it. 

The provided fix resolves it for me with setting mtune native & march native.

**Comment by ezyang** [comment]
Sure thing

**Comment by heroxbd** [comment]
> @ezyang Could a fix based on [pull request #35359](https://github.com/pytorch/pytorch/pull/35359) be merged? Looks like it needs a rebase, but the original author abandoned it.
> 
> The provided fix resolves it for me with setting mtune native & march native.

According to the [Gentoo patch](https://github.com/gentoo/sci/blob/master/sci-libs/pytorch/files/pytorch-1.4.0-sleef.patch), https://github.com/pytorch/pytorch/pull/35359 solves this issue.

**Comment by ezyang** [comment]
looks like we gucci

**Comment by heroxbd** [comment]
> looks like we gucci

Thanks Edward.

**Comment by gemfield** [comment]
sleef.h comes from the build for pytorch/third_party/sleef, also make sure the configure& build for sleef is successful.
e.g. In the cmake output, you should see something like below:
```bash
-- Configuring build for SLEEF-v3.6.0
```
