### ISSUE TITLE
[Feature request] detach (fix?) a nn.module

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2655]
Suppose, we have a siamese network.
```
out1 = net(in1)
out2 = net(in2)
```

However, we want the gradient of parameters in `net` only affected by the first branch (note that suppose we still want the gradient of `in1` and `in2`),
then what we should do here is:
```
out1 = net(in1)
for p in net.parameters(): p.requires_grad=False
out2 =net(in2)
for p in net.parameters(): p.requires_grad=True
fn(out1, out2).backward()
```

So, can we have a `detach` function for nn.module:

So, when we don't want to update a net, we can do:
`net.detach_()`
(Here, detach_() just set all the parameters requires_grad to be False)

If we want to do the example I mention above, we could do:
```
out1 = net(in1)
out2 = net.detach()(in2)
fn(out1, out2).backward()
```
(here, detach() is a clone of the input network but with all parameters requires_grad to be False)

(I give the name detach because it's essentially detach the module Parameters)

**Comment by apaszke** [comment]
Can't you do this?

```python
out1 = net(in1)
out2 = net(in2).detach()
fn(out1, out2).backward()
```

**Comment by ruotianluo** [comment]
Suppose in1 is output of some other network and I want the gradient of that network.

**Comment by ruotianluo** [comment]
Any suggestions?

**Comment by apaszke** [comment]
I think cloning networks would be prohibitively expensive. Is having a loop over parameters really such a bit problem? You can always implement a helper function:

```python
def set_requires_grad(module, val):
    for p in module.parameters():
        p.requires_grad = val

out1 = net(in1)
set_requires_grad(net, False)
out2 = net(in2)
set_requires_grad(net, True)
fn(out1, out2).backward()
```

**Comment by yikang-li** [comment]
> I think cloning networks would be prohibitively expensive. Is having a loop over parameters really such a bit problem? You can always implement a helper function:
> 
> ```python
> def set_requires_grad(module, val):
>     for p in module.parameters():
>         p.requires_grad = val
> 
> out1 = net(in1)
> set_requires_grad(net, False)
> out2 = net(in2)
> set_requires_grad(net, True)
> fn(out1, out2).backward()
> ```

That seems a great idea. But, when used with ''DataParallel'', an error appears:
'''
RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().
'''

**Comment by wandering007** [comment]
@yikang-li Yes, I am also faced with the same problem. Really hope that a function like model.detach() can be realized.

**Comment by mrshenli** [comment]
@yikang-li @wandering007

Do you have an example to reproduce the error?

**Comment by wandering007** [comment]
@mrshenli Sorry for the later reply. I think the above example is my case. I guess that the parameters on other gpus are copied from the parameters on gpu 0 and they are no longer leaf variables.

**Comment by mrshenli** [comment]
@wandering007 Thanks. May I know why you need to set `requires_grad` on individual replicas returned by `DataParallel.replicate()` instead of directly setting it through the `DataParallel` model. The code below works for me. 

```python
dp = nn.DataParallel(net)
out1 = dp(in1)
set_requires_grad(dp, False)
out2 = dp(in2)
set_requires_grad(dp, True)
fn(out1, out2).backward()
```

**Comment by mruberry** [comment]
Closing due to age and lack of response. Please reopen/comment if this is still an issue!
