### ISSUE TITLE
Support matmul for scalar tensors

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#26552]
There's a natural way to extend matmul to vector and scalar quantities. Currently the scalar version is not supported

```
matrix = torch.ones((1, 1))
vector = torch.ones((1))
scalar = torch.ones(())

vector @ matrix  # works
vector @ vector # works
vector @ scalar  # RuntimeError: both arguments to matmul need to be at least 1D, but they are 1D and 0D
```

The reason is that this would make user code a bit simper. IE consider the following matrix expression `Y=X Z` with matrices `X, Y, Z`

Sometimes X is reduced by summing up the rows, or summing up the columns or both, but the formula is unaffected because there's an unambiguous way to interpret it.

Pytorch reductions reduce rank by default. Current implementation means `X @ Z` still works as expected after applying one reduction to X, but needs special handling if we apply 2 reductions.

**Comment by colesbury** [comment]
This behavior is inherited from NumPy. Maybe someone from Quansight Labs can gives some context about this choice? Or cross-post on NumPy's Github?

**Comment by yaroslavvb** [comment]
Filed https://github.com/numpy/numpy/issues/14559

**Comment by yaroslavvb** [comment]
The reason for this treatment is given in PEP 465 -- https://www.python.org/dev/peps/pep-0465/#semantics

It allowed special treatment for rank-1 tensors because "practicality beats purity", but choose not to extend to rank-0 tensors because there's already a * operator which works for this case, so the case for practicality is not as strong.

It seems unlikely to change in numpy, and this doesn't seem like a strong-enough reason to deviate from numpy compatibility, so will close this issue.

Something like https://github.com/pytorch/pytorch/issues/26566 would allow a workaround for users without creating backward compatibility issues.
