### ISSUE TITLE
BUILD_TEST=OFF does not work (Undefined symbol _ZN5torch3jit10testFusionEv)

### ISSUE THREAD

**Issue by mratsim** [pytorch/pytorch#26597]
## 🐛 Bug

BUILD_TEST=OFF does not work, afterwards `import torch` will error with undefined symbol _ZN5torch3jit10testFusionEv

## To Reproduce

Build from source with BUILD_TEST=OFF, for example[ this script](https://github.com/mratsim/Arch-Data-Science/blob/caf742dcd235564715b6d015ebee719c87f40608/frameworks/python-pytorch-magma-mkldnn-cudnn-git/PKGBUILD#L56).

## Expected behavior

`import torch` does not error out

## Environment

 - PyTorch Version (e.g., 1.0): source - aa787523
 - OS (e.g., Linux): Linux

## Additional context

cc @ezyang @gchanan @zou3519 @suo

**Comment by jamesr66a** [comment]
@eellison can you take a look at this one? I see you split up the tests there ~6 mo ago

**Comment by soumith** [comment]
marking this as high pri because BUILD_TEST=OFF is needed for binary builds.

**Comment by suo** [comment]
looking

**Comment by suo** [comment]
Does not repro from a clean build of:
```
BUILD_CAFFE2_OPS=OFF BUILD_TEST=OFF python setup.py develop
```

**Comment by suo** [comment]
@soumith do you know how those version hashes are calculated? `git show aa787523` is not finding anything

**Comment by mratsim** [comment]
Seems I shortened the version too much, here you go: https://github.com/pytorch/pytorch/tree/aa78523467

**Comment by suo** [comment]
Thanks! I'll try the same command above with that rev

**Comment by suo** [comment]
hmm…the same command (`BUILD_CAFFE2_OPS=OFF BUILD_TEST=OFF python setup.py develop`) works for me…

**Comment by mratsim** [comment]
I'm thinking I have some _GLIBCXX_USE_CXX11_ABI.

Investigating (I have CXX11 ABI issue when recompiling OpenCV from source at the moment)

**Comment by suo** [comment]
As there hasn't been too much movement lately and I can't repro the issue, I'm going to close this out to help with our issue tracking. Feel free to comment or reopen if you'd like to follow up!

**Comment by aluo-x** [comment]
Also encountering this error, [see here](https://github.com/pytorch/pytorch/issues/34431#issuecomment-596145998).

**Comment by aluo-x** [comment]
Tagging @suo.
