### ISSUE TITLE
namespace Reduction is not wrapped in torch namespace (C++ API)

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#26606]
## 🐛 Bug

Hi. namespace ```Reduction``` in ```pytorch/aten/src/ATen/core/Reduction.h``` is not wrapped in any namespace. Is this intentional? This can result in namespace and enum conflicts with other projects. I think that it should live inside ```torch``` namespace.

**Comment by VitalyFedyunin** [comment]
Should be folded into `at` namespace. Feel free to submit PR fixing it.

**Comment by divyanshsinghvi** [comment]
Hi, 
I would like to work on this issue. I am a bit inexperienced. Could someone confirm that the changes for this issue will be : 
1) Encapsulating `Reduction` namespace by namespace `at`
2) Prefixing `at::` wherever `Reduction::` is used.

**Comment by ShahriarSS** [comment]
@divyanshsinghvi yes that's it.

**Comment by divyanshsinghvi** [comment]
My pull request #27422 was unable to pass this test  `pytorch_xla_linux_xenial_py3_6_clang7_build`
I could see the console output showing error in `tensor_ops.cpp` but I am unable to find the file in the repository. Could someone give me a pointer to where should I look to debug it?

**Comment by divyanshsinghvi** [comment]
I think we can close this issue now. @ShahriarSS
