### ISSUE TITLE
How to script a model using c++ extension? I met this error

### ISSUE THREAD

**Issue by hahahaprince** [pytorch/pytorch#26630]
## ❓ How to script a model using c++ extension? I met this error
```
RuntimeError: 
Could not export Python function call '_DCNv2'. Remove calls to Python functions before export. Did you forget add @script or @script_method annotation? If this is a nn.ModuleList
```

**Comment by xsacha** [comment]
Don't think it's related to C++.
It's saying your forward calls a Python function so it isn't fully scriptable. Do you have this DCNv2 function?

**Comment by andreaskoepf** [comment]
@hahahaprince Please use the forum for questions - https://discuss.pytorch.org/
