### ISSUE TITLE
BC check test was failing on Friday and Saturday

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26645]
cc @ezyang @gchanan @zou3519 @houseroad @dzhulgakov 

The BC test has been failing two out of four days it was introduced. This is too much noise: also, the fact that it ratchets every day means that it is easy to miss failures that are introduced on the weekend.

Here is an "internal" function which we shouldn't make any BC guarantees on. We need a way to filter these out (I think all `s_` prefixed functions are internal) https://circleci.com/gh/pytorch/pytorch/2877176?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

```
Sep 21 06:51:53 Can NOT find backward compatible schemas after changes for schema aten::s_native_addmm(Tensor self, Tensor mat1, Tensor mat2, *, Scalar beta=1, Scalar alpha=1) -> (Tensor) from the following candidates:
Sep 21 06:51:53 [
Sep 21 06:51:53 
Sep 21 06:51:53 ]
```

This is a quantized BC breaking change. I think this one is also an internal implementation detail. https://circleci.com/gh/pytorch/pytorch/2882497?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

```
Sep 22 05:10:51 processing existing schema:  quantized::qnnpack_relu(Tensor input) -> (Tensor)
Sep 22 05:10:51 Can NOT find backward compatible schemas after changes for schema quantized::qnnpack_relu(Tensor input) -> (Tensor) from the following candidates:
Sep 22 05:10:51 [
Sep 22 05:10:51 
Sep 22 05:10:51 ]
```

Another quantized BC-breaking change I saw in a PR. This one seems legitimate (except for the fact that quantized isn't released yet.)

```
Sep 21 19:57:04 processing existing schema:  aten::quantize_linear_per_channel(Tensor self, Tensor scales, Tensor zero_points, int[] axis, int dtype) -> (Tensor)
Sep 21 19:57:04 Can NOT find backward compatible schemas after changes for schema aten::quantize_linear_per_channel(Tensor self, Tensor scales, Tensor zero_points, int[] axis, int dtype) -> (Tensor) from the following candidates:
Sep 21 19:57:04 [
Sep 21 19:57:04 
Sep 21 19:57:04 ]
```

I also note that in every case, the candidate list has always been empty.

Some asks:

* The script needs to give more clear guidance about what appropriate resolutions for each of these cases are
* We need some formal oncall-style responsibility for ensuring that BC-breaking changes are addressed, esp. when they fail on weekends

**Comment by dzhulgakov** [comment]
So the failures aren't fully noise, it means the test is working. What is missing it seems is an ability to say "hey, changing these functions are fine".

For quantization and other features under development, it feels we want a whitelist saying that changing some functions is fine. We can even introduce a "due date" in the whitelist so that people don't forget to remove items from there.

For `s_native_addmm` - it's a legit failure imho. Once it's flagged on PR the expected behavior for author I'd say is to check that this function is never produced by JIT and add it to the whitelist.

@houseroad - it seems the whitelist mechanism is in order indeed

@zdevito - is there any principled way to figure out which native functions would never appear in JIT IR serialized programs? For tracing we can look only at the ones that generate tracing wrapper, but for scripting I guess today there's nothing preventing someone to write `s_native_addmm` explicitly or some other call accidentally desugaring into it?

**Comment by ezyang** [comment]
Another thing I'm concerned about is whether or not the script picks up ALL bc-breaking changes, or bails out on the first one. If it bails out on the first one then after master is broken you will miss any further breaking changes.

**Comment by houseroad** [comment]
@dzhulgakov yes, whitelist should be added.

@ezyang yes, I am changing it to fail after iterating over all existing schemas.

**Comment by ezyang** [comment]
Failing again today: https://circleci.com/gh/pytorch/pytorch/2911203?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by ezyang** [comment]
Failing again today: https://app.circleci.com/jobs/github/pytorch/pytorch/3029141

```
Oct 01 23:35:10 processing existing schema:  _c10_experimental::Add(Tensor _0, Tensor _1, Tensor _2, bool _3, int _4) -> ()
Oct 01 23:35:10 Can NOT find backward compatible schemas after changes for schema _c10_experimental::Add(Tensor _0, Tensor _1, Tensor _2, bool _3, int _4) -> () from the following candidates:
Oct 01 23:35:10 [
Oct 01 23:35:10 
Oct 01 23:35:10 ]
Oct 01 23:35:10 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not.
```

**Comment by gchanan** [comment]
> For s_native_addmm - it's a legit failure imho. Once it's flagged on PR the expected behavior for author I'd say is to check that this function is never produced by JIT and add it to the whitelist.

ya we need a principled way of dealing with this -- a whitelist is going to end up horribly out of date.

**Comment by houseroad** [comment]
I think we should ask who delete this op to add it to the whiltelist at least to avoid breaking ci.

All whitelist has an expiration date so far. We can clean it up periodically.

**Comment by ezyang** [comment]
@houseroad OK, so you want to make breaking this test a revertable offense? We can certainly do that.

**Comment by z-a-f** [comment]
I was looking for solutions for an error I started getting, and stumbled upon this issue. I am getting this:

```
Nov 05 23:33:25 Can NOT find backward compatible schemas after changes for schema quantized::relu6(Tensor qx) -> (Tensor) from the following candidates:
Nov 05 23:33:25 [
Nov 05 23:33:25 quantized::relu6(Tensor qx, bool inplace) -> (Tensor)
Nov 05 23:33:25 ]
Nov 05 23:33:25 The PR is introducing backward incompatible changes to the operator library. Please contact PyTorch team to confirm whether this change is wanted or not
```

The change that is introducing it: #29245

**Comment by ezyang** [comment]
@z-a-f In your case, it looks like you added a non-optional `inplace` parameter which is not BC compatible with the old definition. Did you mean to give it a default argument?

**Comment by z-a-f** [comment]
> @z-a-f In your case, it looks like you added a non-optional `inplace` parameter which is not BC compatible with the old definition. Did you mean to give it a default argument?

Actually, I didn't want it to have a default argument. But if it fixes the BC, I'll just make it optional

**Comment by gchanan** [comment]
The non-quantized version has the default, so this should, right?

`torch.nn.functional.relu6(input, inplace=False)`

**Comment by z-a-f** [comment]
Can this be closed now?
