### ISSUE TITLE
[RFC] Drop Windows CUDA 9.2 support

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26646]
@peterjc123 and I propose that we drop CUDA 9.2 binary build support for Windows, meaning that we only provide CUDA 10.1 binaries for Windows. Here is our reasoning:

* We strongly prefer to have a single CI provider on which we build all binaries. At the moment, CircleCI is that provider; however, it only supports a single Visual Studio version, that is too new for CUDA 9.2. To run CUDA 9.2 builds on CircleCI, we would have to install both CUDA 9.2 (they provide CUDA 10.1) but also an older version of MSVC which is compatible with CUDA 9.2.
* To workaround this for CUDA 9.2 builds today, we currently do these builds on Azure. However, the agents provided by Microsoft to build nightlies are facing problems, and the release of GitHub Actions has tied up most of the resources available to resolve these problems.

We will not drop from-source support for CUDA 9.2; users are always welcome to build from source if they need this configuration. However, building from source on Windows is quite painful, and @peterjc123 is concerned for LibTorch users, where we rely on the user's environment (as opposed to packaging CUDA for them).

If you are a Windows CUDA 9.2 user that would be unduly affected by this change, please comment on this issue. Thank you!

cc @ezyang @peterjc123

**Comment by ezyang** [comment]
cc @soumith

**Comment by peterjc123** [comment]
Some more points:
1. The download count of CUDA 9.2 packages on Windows is low, which is only near 5k~6k, which is only nearly 10% of that for CUDA 10.0.
2. The nightlies for CUDA 9.2 on Windows never worked, but no issues could be found.

**Comment by soumith** [comment]
only a single Windows CUDA version seems good to me.
Greenlight from my side!

**Comment by peterjc123** [comment]
Well, looks like Microsoft has fixed the agents and the upload issue is fixed. I don't think we need to do this in a hurry now.

**Comment by kit1980** [comment]
Closing as CUDA 9 is gone.
