### ISSUE TITLE
Compile error related THLongStorage

### ISSUE THREAD

**Issue by jinserk** [pytorch/pytorch#2665]
I'm using Ubuntu 17.10 beta with GCC 7.2, pyenv python 3.6.2. I've got a installation error like this:

https://gist.github.com/colesbury/82a526b8d3ecb46aaf8988c0e0a0043d

I've inserted ```#include <functional>``` in ```torch/csrc/jit/ir.h``` to eliminate some errors related to ```std::function```. This modification wasn't required on the machine with GCC 4.8.5

**Comment by soumith** [comment]
today i checked master against GCC 7.2, I pushed the `#include <functional>` fix, and it compiled fine. The TH/THC windows patches might have fixed your issues.
