### ISSUE TITLE
Where did 1.2.0 go on the website?

### ISSUE THREAD

**Issue by BramVanroy** [pytorch/pytorch#26664]
## 🐛 Bug

Trying to download torch 1.2.0 on Linux, but installation fails because 'no matching distribution was found for `torch==1.2.0+cu92`. At first I thought this was related to https://github.com/pytorch/pytorch/issues/26646 and that all of a sudden CUDA 9.2 support was dropped, also for Linux, but upon closer inspection of [the download page](https://download.pytorch.org/whl/torch_stable.html) it seems that 1.2.0 isn't there anymore, for any platform.

Some version issues going on? A failing server, falling back to a backup? Or something else, perhaps.

**Comment by neerajprad** [comment]
We are facing the same issue and this is breaking our CI. cc. @fritzo

**Comment by soumith** [comment]
This is fixed now, I manually fixed them.
I have to see why they were overwritten with a previous version.

**Comment by BramVanroy** [comment]
> This is fixed now, I manually fixed them.
> I have to see why they were overwritten with a previous version.

Thanks. Pip installation works fine now again as well.
