### ISSUE TITLE
function signature doesn't match docstring

### ISSUE THREAD

**Issue by chasezheng** [pytorch/pytorch#2667]
https://github.com/pytorch/pytorch/blob/459cc5a346e25200eca1b921729d10363fac2b1b/torch/autograd/variable.py#L128

**Comment by alykhantejani** [comment]
hmm yeah this looks a bit wrong - will send a PR with doc changes

**Comment by alykhantejani** [comment]
Hi @chasezheng, 

I've submitted a PR with the doc change, although note `retain_variables` is not in the docstring as it has been deprecated and you should use `retain_graph` instead. See [here](https://github.com/pytorch/pytorch/blob/master/torch/autograd/__init__.py#L92) for deprecation warning.
