### ISSUE TITLE
Adding an attribute as a buffer should throw in error

### ISSUE THREAD

**Issue by srush** [pytorch/pytorch#2670]
We had a bug in OpenNMT where we first created an attribute `self.mask` and then tried to add `mask` as a buffer. This behavior will cause `self.mask` to exist, but not be cast with `.cuda`. We think this behavior is counter-intuitive, and it should throw an error. 

@jianyuzhan

**Comment by apaszke** [comment]
I believe this has been fixed in #2108. Can you please confirm this?

**Comment by srush** [comment]
Cool, thanks!
