### ISSUE TITLE
TransformerEncoderLayer: keyword argument 'activation'

### ISSUE THREAD

**Issue by HongyanJiao** [pytorch/pytorch#26701]
code:
import torch.nn as nn
encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8,activation='gelu')
bug:
TypeError: __init__() got an unexpected keyword argument 'activation'

![1569290665](https://user-images.githubusercontent.com/44488820/65475671-efc94200-deb2-11e9-9cdf-674b2ac6cf48.jpg)

**Comment by andreaskoepf** [comment]
You are probably using an old version of PyTorch. The `activation` parameter was recently added (26 days ago), see https://github.com/pytorch/pytorch/commit/0cc92de447962ea9fdcaacb2f4101190f1d5cd8c#diff-c5db6ae353758a64f3e73dd758728cb7 and is not part of PyTorch 1.2.

You might try to install `pytorch-nightly`, see https://pytorch.org/get-started/locally/
