### ISSUE TITLE
Missing cutorch.getMemoryUsage?

### ISSUE THREAD

**Issue by 0wu** [pytorch/pytorch#2671]
There is cutorch.getMemoryUsage() in Torch7 https://github.com/torch/cutorch
But there is no similar function in PyTorch to get Cuda memory utilization information. However, the low-level cuda C API is still there. https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCGeneral.c#L883
Is there any reason it is not brought up to python API level?

Searched PyTorch forum and found similar question -- https://discuss.pytorch.org/t/access-gpu-memory-usage-in-pytorch/3192

**Comment by Stonesjtu** [comment]
You may google `py-nvml`. I actually want a memory usage table for every Tensors in `Pytorch`, including intermediate tensors created by framework.

**Comment by ruotianluo** [comment]
Make a pull request?. Reference: https://github.com/pytorch/pytorch/pull/2540

**Comment by ir413** [comment]
See [`memory_allocated`](https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L368) and [`max_memory_allocated`](https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L389) added in #4511
