### ISSUE TITLE
provide traced model graph syntax spec

### ISSUE THREAD

**Issue by joe8086** [pytorch/pytorch#26715]
## 🚀 Feature
Provide pytorch traced model graph syntax specification.

## Motivation
We plan to deploy pytorch on our inference platform.
So far the only path is pytorch --> onnx --> target platform.
But this path may break in sometimes.
We want to parse pytorch traced model to target platform directly.
We can see traced model have it's syntax, tokens define, but there's no document can refer.
Like this graph output:
graph(%x : Tensor) {
  %5 : bool = prim::Constant[value=1]()
  %1 : int = prim::Constant[value=0]()
  %result.1 : Tensor = aten::select(%x, %1, %1)
  %4 : int = aten::size(%x, %1)
  %result : Tensor = prim::Loop(%4, %5, %result.1)
    block0(%i : int, %7 : Tensor) {
      %10 : Tensor = aten::select(%x, %1, %i)
      %result.2 : Tensor = aten::mul(%7, %10)
      -> (%5, %result.2)
    }
  return (%result);
}

The tokens, the built-in functions the syntax, without a clear document we can't build a correct parser which support all torch-traced model.

Thanks
8086

cc @suo

**Comment by suo** [comment]
Hi! We do not provide a specification for the IR syntax because we do not guarantee that the string representation is stable. Therefore, it's not a good idea to base your deployment strategy on it.

As an alternative, consider using `torch.jit.save` and `torch.jit.load` to serialize your pytorch model. We *do* provide backwards compat and stability guarantees for that format.

**Comment by joe8086** [comment]
@suo

**Comment by joe8086** [comment]
@suo @VitalyFedyunin 

Thanks for your declare.

For the IR it's in flatten model, it will easy for user to parse it.
Can pytorch team can provide different stable release version torch IR syntax?

And
torch.jit.save and load will return ScriptModule.
But also there are less document to describe ScriptModule detail.
Include interface, build-in operations, operation syntax, syntax of scriptmodule.
Can pytorch team can provide detail describe of scriptmodule?

Thanks
8086

**Comment by joe8086** [comment]
No replay, close it.
