### ISSUE TITLE
How to use RandomSampler?

### ISSUE THREAD

**Issue by sp2823** [pytorch/pytorch#26717]
## 🐛 Bug

class RandomSampler in torch/utils/data/sampler.py

def __iter__(self):
        n = len(self.data_source)
        if self.replacement:
            return iter(torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64).tolist())
        return iter(torch.randperm(n).tolist())

problem:
`return iter(torch.randperm(n).tolist())`

If you want to get a random int number in [0,n) when `__iter__(self)` is called, you only need to use `random.randint(0, n-1)`.  This code `return iter(torch.randperm(n).tolist())` uses much resource but only generates a random number when called.

I think in this function you want to generate a list like `torch.randperm(n)` and return the next number when called. Furthermore, we should shuffle the list again when we reach the end of the list. To implement this idea, we can modify the code like this:
- add
`self.iter = iter(torch.randperm(len(self.data_source)).tolist())` in `__init__(self, ...)`
- add
`def __next__(self):`
`try:`
`return next(self.iter)`
`except StopIteration:`
`self.iter = iter(torch.randperm(len(self.data_source)).tolist())`
`return next(self.iter)`
- add
`return self` in  `__iter__(self)`

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
