### ISSUE TITLE
bug of RandomSampler

### ISSUE THREAD

**Issue by sp2823** [pytorch/pytorch#26724]
## 🐛 Bug

class RandomSampler in torch/utils/data/sampler.py

`def __iter__(self):`
`n = len(self.data_source)`
`if self.replacement:`
`return iter(torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64).tolist())`
`return iter(torch.randperm(n).tolist())`

problem code:
`return iter(torch.randperm(n).tolist())`

If you want to get a random int number in [0,n) when `__iter__(self)` is called, you only need to use `random.randint(0, n-1)`. This code return `iter(torch.randperm(n).tolist())` uses much resource but only generates a random number when called.

I think in this function you want to generate a list like `torch.randperm(n)` and return the next number when called. Furthermore, we should shuffle the list again when we reach the end of the list. To implement this idea, we can modify the code like this:
- add code
`self.iter = iter(torch.randperm(len(self.data_source)).tolist())` in `__init__(self, ...)`
- add function
`def __next__(self):`
`try:`
`return next(self.iter)`
`except StopIteration:`
`self.iter = iter(torch.randperm(len(self.data_source)).tolist())`
`return next(self.iter)`
- add code
`return self` in `__iter__(self)`

**Comment by VitalyFedyunin** [comment]
We don't want to shuffle again as we want iterator to return specific number of elements. Current implementation with torch.randperm(n).tolist() allows us to return random and **non repeating** numbers. If you have better (performance/memory-wise) solution, feel free to submit PR.

**Comment by sp2823** [comment]
> Current implementation with torch.randperm(n).tolist() allows us to return random and non repeating numbers. 

Are you sure?
When this function is called, a new list is created and the first element is returned, and then this list and its iterator are released.
The sequence you generated is **repeating numbers**!

A simple example I generated using your code (n=5):
1
1
3
2
1

**Comment by VitalyFedyunin** [comment]
```python
class Sampler:
	def __iter__(self):
		print('init list')
		return iter(list(range(10)))

for x in Sampler():
	print(x)
```

Initialize list once. You probably doing something wrong. Can you show code snippet?
