### ISSUE TITLE
[jit] `dict()` with kwargs doesn't work

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#26747]
```python
dict(a=2, b=3, c=4)
```

cc @suo

**Comment by eellison** [comment]
this is blocked by support of `**kwargs` ... which i'm not sure we want to add yet. alternatives here is:

`{a: 2, b: 3, c: 4}`

**Comment by eellison** [comment]
No one actually asked for this and we decided to not support it for now, so closing. Comment on this issue if this is a problem for you.
