### ISSUE TITLE
[jit] Tensor `.tolist()` is not bound in TorchScript

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#26752]
in script 
```python
>>> a = torch.randn(2, 2)
>>> a.tolist()
```

cc @suo

**Comment by eellison** [comment]
This isn't possible, because we need to type the resulting list, and `tolist()` returns an arbitrarily nested list

**Comment by lamhoangtung** [comment]
So are there anything like `a.to1Dlist() or a.tolist(INTEGER_LITERAL) or a.toList(List[List[int]])` supported yet ?

**Comment by eellison** [comment]
Yea, it's `a : List[List[int]] = a.tolist()`
