### ISSUE TITLE
Crash on assigning cuda tensor to bool-indexed cpu tensor

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#26780]
## 🐛 Bug

Assigning a cuda tensor to a cpu tensor indexed by a boolean index results in crash (jupyter kernel, unit test).

## To Reproduce

```
import torch

# this works fine
A = torch.zeros(1, device="cuda")
A[[True]] = torch.ones(1)

# this works fine 
A = torch.zeros(1, device="cuda")
A[[True]] = torch.ones(1, device="cuda")

# this crashes
A = torch.zeros(1)
A[[True]] = torch.ones(1, device="cuda")

# this works fine
A = torch.zeros(1)
A[0] = torch.ones(1, device="cuda")
```

## Expected behavior

The crashing assignment `A[[True]] =  torch.ones(1, device="cuda")` should either work, or at least raise an informative error and not crash. 

## Environment

This is on FB infra (Linux, torch master, tested on both P100 and M40 GPUs).

## Additional context

FB internal repro: D17564982

cc @ezyang @gchanan @zou3519

**Comment by Balandat** [comment]
@qingfeng10

**Comment by yf225** [comment]
@Balandat I wasn't able to reproduce this using command line. Do you mind sharing me the link to the jupyter notebook?

**Comment by pbelevich** [comment]
What does `A[[True]]` mean? What is expected behavior?

**Comment by pbelevich** [comment]
I tested on master and it fails even on much simpler scenario:
```
import torch
A = torch.zeros(1, device="cuda")
A[[True]] = torch.ones(1)
print(A)
```
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /private/home/pbelevich/local/pytorch/aten/src/THC/THCReduceAll.cuh:327

**Comment by zou3519** [comment]
This seems like a common use case so I am adding it for triage review to discuss how hi-pri it is.

**Comment by vincentqb** [comment]
CC @izdeby

**Comment by vincentqb** [comment]
This is not release blocking.

**Comment by gchanan** [comment]
this looks like it was the type promotion bug.
