### ISSUE TITLE
Fix libTHD's dependies to correctly link against _C.so

### ISSUE THREAD

**Issue by Pavel-Akapian** [pytorch/pytorch#2680]
Hello!
I am trying to install the PyTorch from source with conda (Ubuntu 16.04.4，CUDA 8.0, cudnn 5.1.10, Python 3.5.2 :: Anaconda 4.2.0 64-bit). When I import (py)torch in Python 2.7.13 environment, I'm getting errors:

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/anaconda2/envs/onnx_env/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /usr/local/share/anaconda2/envs/onnx_env/lib/python2.7/site-packages/torch/_C.so: undefined symbol: _ZN3MPI8Datatype4FreeEv

**Comment by elanmart** [comment]
@soumith , do you have any idea why this happens? I've pulled the newest torch version today and I'm getting the same error. Interestingly, even when I checkout to `v0.2.0`, I still can't import torch.

@Pavel-Akapian 
As a workaround, you can do 
`LD_PRELOAD=/usr/lib/libmpi_cxx.so python`, it should help.

**Comment by Pavel-Akapian** [comment]
@elanmart Thanks! This workaround helps.

**Comment by t-vi** [comment]
This apparently happens because openmpi is pulled in by some dependency, but not linked into the main module .so.
What I did was to resolve this was to add openmpi to main_libraries around here:
https://github.com/pytorch/pytorch/blob/master/setup.py#L424

I'm not sure what the correct way is to infer which library is needed, though.

Best regards

Thomas

**Comment by rasoolfa** [comment]
I thought at first this is an issue with docker. Posted here: https://discuss.pytorch.org/t/docker-problem-with-the-latest-source-and-conda/7292
But, yeah, the explanations here clarify that it is problem with source installation not docker per se.

**Comment by kevinlu1211** [comment]
Is this issue related to the error I am getting?

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kevinlu/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen(/Users/kevinlu/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 10): Symbol not found: _ompi_mpi_char
  Referenced from: /Users/kevinlu/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/kevinlu/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so
```

I've tried the workaround though it doesn't work :(

**Comment by elPistolero** [comment]
Adding `mpi_cxx` to `main_libraries` [here](https://github.com/pytorch/pytorch/blob/4fec5f658b65f8ffa15d2fc4da6566fa2f9cb2fb/setup.py#L421) as @t-vi suggested worked for me:
```python
    main_libraries += ['cudart', 'nvToolsExt', 'nvrtc', 'cuda', 'mpi_cxx']
```

I had to call `python setup.py clean` first and then rebuild.

**Comment by soumith** [comment]
i'll be sending a patch to fix this issue today. sorry for the delay.

**Comment by kevinlu1211** [comment]
@soumith Thanks!
@elPistolero I tried the fix but now I'm having an error building here is my pastebin[https://pastebin.com/smPTpUyk](url)

**Comment by elPistolero** [comment]
@kevinlu1211 I'm not familiar with MacOS but it looks like one of the following is the problem:

1. openmpi is not installed on your machine
2. openmpi is not in your library path
3. mpi_cxx is called something else on MacOS (on my machine there is a file called libmpi_cxx.so)
