### ISSUE TITLE
Push based nightlies

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26817]
Our currently nightly structure is triggered by a cron job in CircleCI. The problem with cron triggered jobs is they don't have access to CircleCI context (see https://ideas.circleci.com/ideas/CCI-I-981), which means we can't legitimately access credentials to upload.

The proposed new structure is we maintain a "nightly" branch. This branch is fast-forwarded to master by a cron job run in FB infrastructure, using the SSH key of a role account that is authorized to access the context in question. We delete the cron job otherwise, and instead the nightly jobs with uploads are tied to a specific branch.

A nice property of this is we can manually retrigger a nightly whenever we want, by pushing to this branch.

cc @ezyang @soumith @mingbowan @kostmo

**Comment by soumith** [comment]
sounds fantastic. let's do it!

**Comment by pietern** [comment]
This is excellent.
