### ISSUE TITLE
UtilsNMSTest.GPUEqualsCPURotatedCorrectnessTest is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26811]
```
Sep 24 19:19:01 [ RUN      ] UtilsNMSTest.GPUEqualsCPURotatedCorrectnessTest
Sep 24 19:19:01 /var/lib/jenkins/workspace/caffe2/operators/generate_proposals_op_util_nms_gpu_test.cc:695: Failure
Sep 24 19:19:01 Expected equality of these values:
Sep 24 19:19:01   keep.size()
Sep 24 19:19:01     Which is: 1657
Sep 24 19:19:01   gpu_keep.size()
Sep 24 19:19:01     Which is: 1656
Sep 24 19:19:01 [  FAILED  ] UtilsNMSTest.GPUEqualsCPURotatedCorrectnessTest (779 ms)
```

https://circleci.com/gh/pytorch/pytorch/2918819?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
Still happening: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/44785//console.

#29346 is a dupe of this.

**Comment by mruberry** [comment]
@hugovbraun fyi. Do you have any context on this test?

**Comment by hugovbraun** [comment]
I only wrote the Upright version of this operator/test, so not sure what's in this one
