### ISSUE TITLE
Update docs for arithmetic operation type promotion

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#26825]
`torch.add` looks like the following on master.
![image](https://user-images.githubusercontent.com/5652049/65623521-fda3c380-df95-11e9-8c8e-7ad9868af9b7.png)

If I am understanding type promotion correctly, we can now add arbitrarily-typed scalars to arbitrarily-typed tensors, so the docs are now incorrect.

cc @nairbv

**Comment by nairbv** [comment]
https://github.com/pytorch/pytorch/pull/25114

**Comment by nairbv** [comment]
this was fixed by https://github.com/pytorch/pytorch/pull/25114
