### ISSUE TITLE
The clamp function is running incorrectly

### ISSUE THREAD

**Issue by chenzhaomin123** [pytorch/pytorch#2688]
`a = torch.ones(4,1)`
`a = a.clamp(0,1-1e-8)`
`print a`

Output:
` 1`
 `1`
 `1`
 `1`
`[torch.FloatTensor of size 4x1]`

The clamp function cannot work correctly when the second parameter is greatly closed with one number in 'a'.

**Comment by fmassa** [comment]
This is expected, and happens because `1-1e-8` can not be represented exactly in float precision (which is the default precision in pytorch).
For example, see
```python
print(torch.FloatTensor([1-1e-8])[0])
print(torch.DoubleTensor([1-1e-8])[0])
```
yields
```
1.0
0.99999999
```

The same thing happens in numpy:
```python
a = np.array([1.], dtype=np.float32)
b = np.clip(a, a_min=0, a_max=1-1e-8)
print(b)
> array([ 1.], dtype=float32)
```
