### ISSUE TITLE
in TracedModel how to get model parameter like convolution stride info.

### ISSUE THREAD

**Issue by joe8086** [pytorch/pytorch#26880]
## ❓ Questions and Help

I use traced_model._modules[‘conv1’] to access conv module.
But how can I find ‘stride’ info in tracedModel object?
Is there any document to describe tracedModel API and structure?

Thanks,
8086

**Comment by vincentqb** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
