### ISSUE TITLE
caffe2 cannot infer onnx model exported from pytorch

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/pytorch#26887]
## 🐛 Bug

convert to onnx and then use caffe2 to run inference, there are errors when there is FPN structure in the model.

## To Reproduce

1. run the following code

```python
import onnx
import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.nn import Conv2d
from torch.nn import BatchNorm2d
import caffe2.python.onnx.backend as backend


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        self.conv1 = Conv2d(3,
                            64,
                            kernel_size=7,
                            stride=2,
                            padding=3,
                            bias=False)
        self.maxpool = nn.MaxPool2d(kernel_size=3,
                                    stride=2,
                                    padding=1,
                                    dilation=1,
                                    ceil_mode=False)
        self.layer1 = Conv2d(64,
                            256,
                            kernel_size=3,
                            stride=1,
                            padding=1,
                            bias=False)
        self.layer2 = Conv2d(256,
                            512,
                            kernel_size=3,
                            stride=2,
                            padding=1,
                            bias=False)
        self.layer3 = Conv2d(512,
                            1024,
                            kernel_size=3,
                            stride=2,
                            padding=1,
                            bias=False)
        self.layer4 = Conv2d(1024,
                            2048,
                            kernel_size=3,
                            stride=2,
                            padding=1,
                            bias=False)
        self.inner32 = nn.Conv2d(2048, 256, 1, padding=0, stride=1)
        self.inner16 = nn.Conv2d(1024, 256, 1, padding=0, stride=1)
        self.outer16 = nn.Conv2d(256, 256, 3, padding=1, stride=1)

    def forward(self, x):
        x = self.conv1(x)
        x = self.maxpool(x)
        feat4 = self.layer1(x)
        feat8 = self.layer2(feat4)
        feat16 = self.layer3(feat8)
        feat32 = self.layer4(feat16)

        feat32 = self.inner32(feat32)
        feat16 = self.inner16(feat16)
        _, _, H, W = feat16.size()
        feat32 = F.interpolate(feat32, (H, W), mode='nearest')
        feat16 = feat16 + feat32
        return feat4, feat8, feat16, feat32



if __name__ == "__main__":
    resnet = Net()
    dummy_input = torch.randn(1, 3, 224, 224)
    oname = 'resnet50.onnx'
    torch.onnx.export(resnet, dummy_input, oname, verbose=True)

    model = onnx.load(oname)
    img = (cv2.resize(cv2.imread('./000000000139.jpg'), (224, 224)) / 255. - 0.45 ) / 0.225
    img = img.transpose(2, 0, 1)[np.newaxis, :, :, :].astype(np.float32)
    rep = backend.prepare(model, device="CUDA:0")
    outputs = rep.run(img)

```

## Environment
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 418.74
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py36h7b6447c_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py36_cu100    pytorch

**Comment by Godricly** [comment]
I tried server backends to inference FPN network. Only the onnxruntime works. You can try that one.

**Comment by CoinCheung** [comment]
@Godricly Yes, onnxruntime works, but only when the backend is cpu or cuda. It seems that when the backend is tensorrt, there would still be errors. My problem now is that onnxruntime seems to infer models slower than pytorch, which would make the onnx approach to be less meaningful.

**Comment by Godricly** [comment]
Well, I know your pain. I need to deploy a object detection model using C++ interface. So I can't use pytorch. I compiled onnxruntime with different backends too. The MKL backend has issue with its graph optimazation.

**Comment by CoinCheung** [comment]
Any updates?

**Comment by garymm** [comment]
Caffe2 is no longer being developed so this is unlikely to get fixed.
