### ISSUE TITLE
[jit] internal error on range(<float>)

### ISSUE THREAD

**Issue by tamas-the-sorcerer** [pytorch/pytorch#26885]
## 🐛 Bug

the issue is probably that jit cannot create a graph without any tensors. 
and the error message it gives is kinda useless. 

i got
```
In [24]: f(8)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-7ea01d955afc> in <module>
----> 1 f(8)
RuntimeError: isInt() INTERNAL ASSERT FAILED at /tmp/pip-req-build-58y_cjjl/aten/src/ATen/core/ivalue.h:187, please report a bug to PyTorch. 
The above operation failed in interpreter, with the following stack trace:
...  <--- HERE
```

after running
```
@torch.jit.script 
def f(bits): 
    # type: (int) -> int 
    i = 0 
    for _ in range(2**bits): 
         i = i + 1 
    return i 
```

and then calling
```
f(8)
```

torch version 1.2.0

cc @ezyang @gchanan @zou3519 @suo

**Comment by suo** [comment]
Thanks for the report! This is indeed a bug, which stems from two strange behaviors:
1. `2**bits` returns a float
2. `range` statement over floats causes an internal error (which is why the stack trace you're seeing is so useless).

@eellison, do you mind taking a look at this?

**Comment by suo** [comment]
Further, it appears that `int(2**bits)` does not correctly perform a cast to int

**Comment by eellison** [comment]
> Further, it appears that `int(2**bits)` does not correctly perform a cast to int

This isn't an issue with the cast, it's an issue with the pow op. If the input type is an int then a cast isn't inserted.
