### ISSUE TITLE
torch.onnx export Resize layer wrong

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#26888]
The torch.onnx export resize layer generates onnx model Resize layer but without scales params:

```
[8] Assertion failed: scales_weights.shape.nbDims == 1
```

It generates Resize node like this:

```
node: 479, op_type: Resize | input: ['452', '479'], output: ['480']
input: "452"
input: "479"
output: "480"
name: "479"
op_type: "Resize"
attribute {
  name: "mode"
  s: "nearest"
  type: STRING
}
```

Without scales params, this is not supported by onnx-tensorrt...

**Comment by vincentqb** [comment]
Could you provide an example of what you are trying to do?

**Comment by jinfagang** [comment]
@vincentqb  Oh, yes. I am trying converting maskrcnn.onnx to TensorRT. Previously tensorrt does not support dynamic input or dynamic in axis=0 (such as different image has different boxes in object detection). Now Tensorrt 6.0 released and all these dimension supported.

But when converting the model to trt engine using onnx-tensorrt, it claims  Resize layer has no scales params.

So I don't know whether this is related to `torch.onnx` when export, or onnx-tensorrt it self, but definitely they are not compatible. So better community have a look at the exported way compatible to TensorRT style or not.

**Comment by vincentqb** [comment]
CC @houseroad for ONNX

**Comment by garymm** [comment]
@jinfagang please provide repro code for everything up to and including the call to `torch.onnx.export` and explain the expected vs observed output.
Thanks

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
