### ISSUE TITLE
onnx export: einsum not supported

### ISSUE THREAD

**Issue by lukasheinrich** [pytorch/pytorch#26893]
## 🐛 Bug

Exporting models which use `einsum` in their `forward()` method does not work

## To Reproduce

This is a minimal example:
```
import torch
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()

    def forward(self, inputs):
        return torch.einsum('i->i',inputs)

model = MyModel()
torch.onnx.export(
    model,
    torch.randn(1),
    "pyhf.onnx",
    verbose=True,
    input_names=['input'],
    output_names=['output']
)
```

which gives 

```
RuntimeError: Unsupported prim::Constant kind: `s`. Send a bug report.
```

## Expected behavior

I would expect this export to work

## Environment

Mac OS X 

```
pip freeze|grep torch
torch==1.2.0
```

cc @matthewfeickert @kratsg

**Comment by vincentqb** [comment]
CC @houseroad

**Comment by neginraoof** [comment]
I'm looking into adding the Einsum operator in ONNX: https://github.com/onnx/onnx/pull/2504
Will update this once we have the operator ready.

**Comment by ShakedDovrat** [comment]
@neginraoof Any update on this?

**Comment by spandantiwari** [comment]
@ShakedDovrat - support for EinSum in ONNX exporter has been added. (https://github.com/pytorch/pytorch/pull/32716)

**Comment by ShakedDovrat** [comment]
@spandantiwari in which version? I still get this error in pytorch==1.4.0

**Comment by spandantiwari** [comment]
This is in PyTorch master only. It is expected to be released with the next release. You can try it out using one of PyTorch nightly builds from pytorch.org.

**Comment by ShakedDovrat** [comment]
Thank you. I've downloaded the current nightly build from pytorch.org and I still get the same error.
I have installed:
torch==1.5.0.dev20200218
torchvision==0.6.0.dev20200219
What else can I try?

**Comment by spandantiwari** [comment]
@ShakedDovrat - this is the PR (https://github.com/pytorch/pytorch/pull/32716) adding support for Einsum in ONNX export. So I expect this to be supported. 
Can you please add an argument in your export API call: `opset_version=12`.
This is needed because Einsum is part of ONNX Opset 12 (to be released soon) and not previous opsets.

**Comment by ShakedDovrat** [comment]
Thank you for your help.
I've added the `opset_version=12` argument and now get this error:
```
Traceback (most recent call last):
  File "temp.py", line 9, in <module>
    torch.onnx.export(model, dummy_input, output_model_path, verbose=True, input_names=['input'], output_names=['output'], opset_version=12)
  File "lib\site-packages\torch\onnx\__init__.py", line 158, in export
    custom_opsets, enable_onnx_checker)
  File "lib\site-packages\torch\onnx\utils.py", line 68, in export
    custom_opsets=custom_opsets, enable_onnx_checker=enable_onnx_checker)
  File "lib\site-packages\torch\onnx\utils.py", line 469, in _export
    fixed_batch_size=fixed_batch_size)
  File "lib\site-packages\torch\onnx\utils.py", line 338, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "lib\site-packages\torch\onnx\utils.py", line 153, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "lib\site-packages\torch\onnx\__init__.py", line 189, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "lib\site-packages\torch\onnx\utils.py", line 717, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "lib\site-packages\torch\onnx\symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "lib\site-packages\torch\onnx\symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "lib\site-packages\torch\onnx\symbolic_helper.py", line 81, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
```
Googling it suggests it's a bug that was already fixed, so I'm guessing opset version 12 is just not stable yet.

**Comment by feifeibear** [comment]
Hi, I also tried to modify opset version. It dose not work. Actually, on RTX2060, the program is stuck on the execution of the following code. I have to kill the process.
`
torch.onnx.export(model=model,
                              args=(input_ids, ),
                              f=outf,
                              input_names=['input'],
                              output_names=['output'],
                              dynamic_axes={
                                  'input': [0, 1],
                                  'output': [0, 1]
                              },
                             opset_version=12)
`

**Comment by HadiEsna** [comment]
Hi, any updates on this?
I'm getting this error when trying to export my model
