### ISSUE TITLE
add documentation / links for old binaries

### ISSUE THREAD

**Issue by hehefan** [pytorch/pytorch#2689]
Where is the pip2.7 whl link for pytorch 0.1.12?

**Comment by fmassa** [comment]
Related to https://github.com/pytorch/pytorch/issues/2650 , but for pip.

**Comment by alykhantejani** [comment]
http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl

**Comment by hehefan** [comment]
Thank you @alykhantejani and @fmassa so much!!!

**Comment by colesbury** [comment]
Thanks @zou3519 !

**Comment by colesbury** [comment]
Links are at http://pytorch.org/previous-versions/
