### ISSUE TITLE
missing docstrings in torch.nn.intrinsic fused functions

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#26899]
This issue drifted a bit. What was finally fixed was the missing set of docs for the fused functions in torch.nn.intrinsic 

original description: 
The doc for ConvBn2d is missing. I see it in the rst file and I can get the docstring with a print on the class's __doc__ attribute in pytorch. 

<img width="1725" alt="missing-function-ConvBn2d" src="https://user-images.githubusercontent.com/45861273/65708330-30f05c00-e043-11e9-9502-a35464191e19.png">

**Comment by vincentqb** [comment]
Can you point us to the file that is missing in the [pytorch docs folder](https://github.com/pytorch/pytorch/tree/master/docs/source)?

**Comment by gottbrath** [comment]
ok now it is working, but sadly I don't know why. :(

<img width="1645" alt="Screen Shot 2019-09-27 at 1 15 18 PM" src="https://user-images.githubusercontent.com/45861273/65799496-1b556200-e129-11e9-859b-4b51405dfef1.png">

**Comment by gottbrath** [comment]
sorry, I am working off of a patch from Jessica that adds rst files for the quantization functions. I realize this makes it hard for other folks to chime in and help. :)

**Comment by gottbrath** [comment]
ok .. reviewing these issues again. this one still seems to be open. When i look at the docs on stable I see: 
<img width="1002" alt="Screen Shot 2019-10-22 at 3 53 32 PM" src="https://user-images.githubusercontent.com/45861273/67341272-2612d500-f4e4-11e9-8ef3-0b8f44990841.png">

for the nn.instrinsic versions of these functions. 

but for the QAT versions I see:

<img width="1091" alt="Screen Shot 2019-10-22 at 3 54 13 PM" src="https://user-images.githubusercontent.com/45861273/67341321-4773c100-f4e4-11e9-853d-d86d97608731.png">


when I look at the files in 

https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/modules/fused.py

I don't see any docstrings.. so I think in this case we just forgot.

**Comment by gottbrath** [comment]
docstrings were missing. Sat with Raghu to work out what to write.

**Comment by gottbrath** [comment]
![pt-i26899-fixed](https://user-images.githubusercontent.com/45861273/69390802-6f8e4580-0c85-11ea-97af-9859e8184ec6.png)

**Comment by gottbrath** [comment]
landed on master
