### ISSUE TITLE
Provide tracedModel.graph IR specific for released stable pytorch

### ISSUE THREAD

**Issue by joe8086** [pytorch/pytorch#26961]
## 🚀 Feature
pytorch tracedModel graph IR is flatten, but no specific about the IR detail like key-words, tokens, syntax, build-in functions.

We plan to deploy pytorch to target platform, 
Did some research on tracedModel, and scriptModel, it's hard to access it detail.
And also it have less document on tracedModel and scriptModel.
Use tracedModel.graph IR is a good choice, we already have one implement for 1.0.0, but there's no official document to describe IR syntax， our implement may break at some torch model.

I suggest Pytorch can provide IR specific for already stable release pytorch like 1.0.0 , 1.1.0 and 1.2.0.
Because the graph IR is flatten, it is more easy for us to understand the model than the nest structure tracedModel.

If also provide tracedModel and scriptModel API, structure document, that's welcome.

Thanks,
8086

cc @suo

**Comment by ailzhang** [comment]
Hi @joe8086  is https://github.com/pytorch/pytorch/wiki/PyTorch-IR helpful?

**Comment by joe8086** [comment]
Hi @ailzhang 

Thanks, it looks OK for me. It give me a more clear doc to understand the IR detail.
