### ISSUE TITLE
How can I implement the function of tf.unsorted_segment_sum in Pytorch?

### ISSUE THREAD

**Issue by Brownchen** [pytorch/pytorch#26960]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by pbelevich** [comment]
We appreciate your interest in PyTorch. Please use https://discuss.pytorch.org/ for such questions.
