### ISSUE TITLE
Uniform random generator generates too many zeros compared to NumPy

### ISSUE THREAD

**Issue by freud14** [pytorch/pytorch#26973]
## 🐛 Bug

While looking at issue #26971, I wondered if torch's uniform number generators was generating too many zeros since it generates in average more than 5 zeros per 10^8 generations according to the following:
```python
sum((torch.rand(100000000) <= 0.).sum().float() for i in range(20)) / 20
```
On GPU, it generates in average around 3 zeros per 10^8 generators:
```python
sum((torch.rand(100000000, device=torch.device('cuda')) <= 0.).sum().float() for i in range(20)) / 20
```
If you do the same test with NumPy, you will see that it never generates zeros:
```python
sum((np.random.rand(100000000).astype('float32') <= 0.).sum() for i in range(20)) / 20
```
(if you try with `'float16'` instead of `'float32'`, you will see that it generates some zeros)
Thus, I think that PyTorch's generator might be biased towards zero and this may hide other biases that I'm not aware.

## To Reproduce

See above.

## Expected behavior

In my opinion, the behavior should be similar to NumPy's unless NumPy has a bug instead.

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GT 1030

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.1
[pip3] numpy==1.16.2
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl-service               1.1.2            py36he904b0f_5  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torch                     1.1.0                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi

**Comment by pbelevich** [comment]
@freud14 sounds reasonable, we will take a look

**Comment by ngimel** [comment]
Results are amazingly as expected, given the way uniform distribution is generated in torch. Cuda produces approx 2^-25 rate of zeroes (that would come out to 3 per 10^8) https://github.com/pytorch/pytorch/blob/766767652ae0bcd35e5ea4c79fc13eed9a8929b0/aten/src/ATen/native/cuda/Distributions.cu#L435-L442, and cpu approx 2^-24 rate of zeros (6 per 10^8) https://github.com/pytorch/pytorch/blob/766767652ae0bcd35e5ea4c79fc13eed9a8929b0/aten/src/ATen/core/DistributionsHelper.h#L72-L96. There are legacy and convenience reasons for what we did, see discussion in https://github.com/pytorch/pytorch/issues/16706. From these results it looks like numpy is generating all representable floats in [0,1) range with a corresponding probability (which is pretty expensive) or uses divide by 2^32 approach. We can consider switching to divice by 2^32 approach but it needs discussion.

**Comment by freud14** [comment]
Alright, I guess this thread is a duplicate of #16706. However, it seems that a possible workaround would be to generates doubles and converting them into float as in my NumPy code:
```python
sum((torch.rand(100000000, dtype=torch.double).float() <= 0.).sum().float() for i in range(20)) / 20
```
However, I don't know if that still produces uniform numbers given the downcasting.
