### ISSUE TITLE
RpcTest.test_nested_rpc is flaky

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#26986]
```
Sep 27 17:57:58 ======================================================================
Sep 27 17:57:58 FAIL: test_nested_rpc (__main__.RpcTest)
Sep 27 17:57:58 ----------------------------------------------------------------------
Sep 27 17:57:58 Traceback (most recent call last):
Sep 27 17:57:58   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 107, in wrapper
Sep 27 17:57:58     self._join_processes(fn)
Sep 27 17:57:58   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 163, in _join_processes
Sep 27 17:57:58     self._check_return_codes(elapsed_time)
Sep 27 17:57:58   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 183, in _check_return_codes
Sep 27 17:57:58     self.assertEqual(p.exitcode, first_process.exitcode)
Sep 27 17:57:58   File "/var/lib/jenkins/workspace/test/common_utils.py", line 729, in assertEqual
Sep 27 17:57:58     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Sep 27 17:57:58 AssertionError: 21 not less than or equal to 1e-05 : 
Sep 27 17:57:58 
Sep 27 17:57:58 ----------------------------------------------------------------------
Sep 27 17:57:58 Ran 29 tests in 76.625s
Sep 27 17:57:58 
Sep 27 17:57:58 FAILED (failures=1, skipped=1)
Sep 27 17:57:58 Traceback (most recent call last):
Sep 27 17:57:58   File "test/run_test.py", line 440, in <module>
Sep 27 17:57:58     main()
Sep 27 17:57:58   File "test/run_test.py", line 432, in main
Sep 27 17:57:58     raise RuntimeError(message)
Sep 27 17:57:58 RuntimeError: test_rpc failed!
Sep 27 17:57:58 + cleanup
Sep 27 17:57:58 + retcode=1
Sep 27 17:57:58 + set +x
```
on https://circleci.com/gh/pytorch/pytorch/2979759?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
This is still happening: 

https://circleci.com/gh/pytorch/pytorch/3508541?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

Nov 07 06:26:05 ======================================================================
Nov 07 06:26:05 ERROR: test_nested_rpc (__main__.RpcTestWithFork)
Nov 07 06:26:05 ----------------------------------------------------------------------
Nov 07 06:26:05 Traceback (most recent call last):
Nov 07 06:26:05   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 130, in wrapper
Nov 07 06:26:05     self._join_processes(fn)
Nov 07 06:26:05   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 211, in _join_processes
Nov 07 06:26:05     self._check_return_codes(elapsed_time)
Nov 07 06:26:05   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 230, in _check_return_codes
Nov 07 06:26:05     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Nov 07 06:26:05 RuntimeError: Process 1 terminated or timed out after 300.568505525589 seconds
Nov 07 06:26:05 
Nov 07 06:26:05 ----------------------------------------------------------------------
Nov 07 06:26:05 Ran 53 tests in 308.721s
Nov 07 06:26:05 
Nov 07 06:26:05 FAILED (errors=1, skipped=5)
Nov 07 06:26:05 Traceback (most recent call last):
Nov 07 06:26:05   File "test/run_test.py", line 454, in <module>
Nov 07 06:26:05     main()
Nov 07 06:26:05   File "test/run_test.py", line 446, in main
Nov 07 06:26:05     raise RuntimeError(message)
Nov 07 06:26:05 RuntimeError: test_rpc_fork failed!
Nov 07 06:26:05 + cleanup
Nov 07 06:26:05 + retcode=1
Nov 07 06:26:05 + set +x
Nov 07 06:26:05 =================== sccache compilation log ===================
Nov 07 06:26:05 ERROR:sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/tmp/torch_extensions/test_compilation_error_formatting/main.cpp: In function \'int main()\':\n/tmp/torch_extensions/test_compilation_error_formatting/main.cpp:2:23: error: expected \';\' before \'}\' token\n int main() { return 0 }\n                       ^\n" }

**Comment by mruberry** [comment]
@mrshenli  @aazzolini

**Comment by mruberry** [comment]
Closing, as this no longer appears to be happening.
