### ISSUE TITLE
Use functools.wraps in distributed decorators

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#26999]
## 🚀 Feature

Users of our module may want to use introspection to better understand/quickly get information out of our code. Right now, if they do something like this:
```
import torch.distributed as d
d.rpc.__doc__
d.rpc.__name__
help(d.rpc)
```
the returned info is not helpful. We could use `functools.wraps` to preserve the documentation we already have on these public APIs to ensure that the decorators don't cause these functions to lose docs. 

## Motivation

This feature will make it easier for users to inspect our API. This is already used quite a bit in the codebase as well.

## Additional context

I frequently use `help(func_name)` in the terminal instead of pulling up docs online, since it's faster, which is why I got the idea for this feature.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini

**Comment by pietern** [comment]
Thanks for creating the issue, @rohan-varma. Pro tip: you can include "Closes #26999" or "Fixes #26999" in the summary of your PR to automatically close the issue when it is merged.
