### ISSUE TITLE
torch.fmod fails with dist.rpc

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#27013]
## To Reproduce

```
    def test_fmod_error(self):
        t1 = torch.rand((3, 3))
        t2 = torch.rand(1)
        dist.rpc('worker{}'.format(self.rank + 1), torch.fmod,
            args=(t1, t2))
```

Error:

```
> RuntimeError: Missing cases in toIValue for type: Scalar! File a bug report. (toIValue at caffe2/torch/csrc/jit/pybind_utils.h:506)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
@pritamdamania87 @mrshenli I ran the test here and it looks like `torch.fmod` is supported and there's no error in the IValue conversion code. I'm not sure what PR fixed this though, I think it might have been fixed as a byproduct of a JIT PR. I think we can close this out?
