### ISSUE TITLE
Implement derivative for torch.lstsq

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#27036]
## 🚀 Feature
Implement derivative for [`torch.lstsq`](https://pytorch.org/docs/stable/torch.html?highlight=lstsq#torch.lstsq). Backward pass currently raises `RuntimeError: the derivative for 'lstsq' is not implemented`.

cc @vishwakftw @SsnL @jianyuh

**Comment by Hippogriff** [comment]
I implemented the least squares using QR factorization that seems to be most stable. For under-determined system, I am using a lambda penalty for regularization. lamb ~ 0.01 works fine and gives results similar to numpy least square implementation.

```
import torch


class LeastSquares:
    def __init__(self):
        pass
    
    def lstq(self, A, Y, lamb=0.0):
        """
        Differentiable least square
        :param A: m x n
        :param Y: n x 1
        """
        # Assuming A to be full column rank
        cols = A.shape[1]
        print (torch.matrix_rank(A))
        if cols == torch.matrix_rank(A):
            q, r = torch.qr(A)
            x = torch.inverse(r) @ q.T @ Y
        else:
            A_dash = A.permute(1, 0) @ A + lamb * torch.eye(cols)
            Y_dash = A.permute(1, 0) @ Y
            x = self.lstq(A_dash, Y_dash)
        return x

A = torch.tensor([[1., 1, 1],
                      [2, 3, 3],
                      [3, 5, 5],
                      [4, 2, 2],
                      [5, 4.0, 4]])
B = torch.tensor([[-10.],
                      [ 12.0],
                      [ 14],
                      [ 16],
                      [ 18]])
A.requires_grad = True
ls = LeastSquares()
x = ls.lstq(A, B, 0.010)
print (x)
l = torch.mean(x)
l.backward()
```

**Comment by juliusbierk** [comment]
For the `m > n` case here's a slightly slower version which allows calculation of gradients...

```
AT = A.t()
b = A @ input
ATA = A @ AT
coeffs, _ = torch.solve(b[:, None], ATA)
```

**Comment by jramapuram** [comment]
Any official support for this? Tensorflow has had support for this since 1.x

**Comment by rlucas7** [comment]
@jramapuram I've opened a PR #42216 that would obviate the need for approximation methods for over determined cases. 

Provided there is concensus that pytorch will implement the backwards method for `lstsq` and if the PyTorch devs are willing to merge that ( #42216 ) PR (after reviews etc), then I could start the work on implementing this one next.

**Comment by nikitaved** [comment]
As a workaround instead of calling to `lstsq` you could just use `x.pinverse() @  b` which should work with autograd. One more bonus: it does support batching. We are currently working on implementing a better version such as `torch.linalg.lstsq` https://github.com/pytorch/pytorch/pull/49093 , however I am not sure there is a way to efficiently implement backward in all cases.
Why? Some configurations of `torch.linalg.lstsq` call to LAPACK routines which run SVD under the hood but do not materialize the full SVD to the user, and we need this SVD decomposition for the backward, or the QR decomposition for that matter...

**Comment by agadetsky** [comment]
@carlosgmartin @nikitaved  Also you can use https://github.com/cvxgrp/cvxpylayers to get solution differentiable with respect to problem parameters (A, B matrices in this case).

**Comment by TobiasJacob** [comment]
Please add this feature

**Comment by Lezcano** [comment]
This is now supported in `linalg.lstsq`.

**Comment by soloice** [comment]
@Lezcano Is this true? I'm using torch 1.10.0+cu113, but calling `torch.linalg.lstsq()` in my model gives me "NotImplementedError: the derivative for 'linalg_lstsq' is not implemented."

**Comment by Lezcano** [comment]
Could you try in master?  This might be implemented in 1.11 even, though not sure

**Comment by soloice** [comment]
Unfortunately , I'm using a computing cluster instead of my personal computer.  So torch 1.11 or master is not available for me, at least in the short run.

**Comment by Lezcano** [comment]
As most libraries, we don't backport features. The only thing that occurs to me that you could do is to have a look at the code of the derivative in FunctionsManual.cpp and implement it yourself on the Python frontend (there is a tutorial on how to do this out there). Now, this is not a trivial task given the complexity of this operation, but it's the only solution that comes to mind if you're restricted to 1.10 for now

**Comment by SsnL** [comment]
For older versions, one can do a custom autograd op.

**Comment by soloice** [comment]
`The only thing that occurs to me that you could do is to have a look at the code of the derivative in FunctionsManual.cpp and implement it yourself on the Python frontend`
I guess so. And this is what I'm going to do.

But it would be great if someone can confirm which version of pytorch introduces the `lstsq` derivative feature. Also, I'm wondering if there's a good explanation on why "`lstsq.solution` has a `grad_fn=<LinalgLstsqBackward0>`, but backward pass still fails."

**Comment by miguelgondu** [comment]
I tried this in `torch == 1.11.0` and it still complains. Here's an example:

```python
    # A 3x2 matrix, full rank.
    basis = torch.Tensor([[1, 0, 0], [0, 1, 0]]).T

    # Building some vectors in the span of its column space
    original_coeffs = torch.randn((100, 2))
    some_vectors = (
        original_coeffs[:, 0].unsqueeze(1) * basis[:, 0]
        + original_coeffs[:, 1].unsqueeze(1) * basis[:, 1]
    )

    # Batching the basis for lstsq.
    all_bases = np.repeat(basis.unsqueeze(0), len(some_vectors), axis=0)
    all_bases.requires_grad = True

    # Getting what should be equal to high_dim
    new_coeffs = torch.linalg.lstsq(all_bases, some_vectors).solution

    # Indeed, they're all equal...
    print(original_coeffs == new_coeffs)

    # ...but the backwards pass breaks. Complains about matrix shapes.
    new_coeffs.mean().backward()
```

I get a `RuntimeError` that says:
```
mat1 and mat2 shapes cannot be multiplied (100x2 and 3x100)
```

The solution proposed by @Hippogriff still works (provided you change it for batch-sized QR transformations in this particular example).

Thanks for the hard work, @Lezcano. I see you're (maybe) already addressing this in https://github.com/pytorch/pytorch/issues/77225.

**Comment by Lezcano** [comment]
I think 77225 addresses this, yep
