### ISSUE TITLE
cannot torch.jit.trace on ARM 32 bit (Raspbian)

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#27040]
## 🐛 Bug

The JIT tracer doesn't seem to work on ARM 32 bit.

## To Reproduce

1. Compile PyTorch on 32 bit Raspbian Buster (needs LDFLAGS="-latomic").
1. Trace a function. e.g.

```
def mul2(x):
     return x*2
torch.jit.trace(mul2, torch.randn(5))
```
gives
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-6756eca5e991> in <module>()
----> 1 torch.jit.trace(mul2, torch.randn(5))

/usr/local/lib/python3.7/dist-packages/torch/jit/__init__.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, _force_outplace, _module_class, _compilation_unit)
    866     traced = torch._C._create_function_from_trace(name, func, example_inputs,
    867                                                   var_lookup_fn,
--> 868                                                   _force_outplace)
    869 
    870     # Check the trace against new traces created from user-specified inputs

RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.
```

## Expected behavior

Working tracing.

## Environment

 - Masterish PyTorch
 - OS: Raspbian (ARMv7l, so 32 bit) on a Pi 4
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `LDFLAGS="-latomic" python3 setup.py bdist_wheel`
 - Python version: 3.7

## Additional context

Script works, autograd works.

cc @suo

**Comment by jamesr66a** [comment]
Hi @t-vi, since this is not an officially supported platform, we likely won't have bandwidth to fix this. We'd be happy to accept patches to fix it, though :)

The intuition is this is probably something to do with the way we hash tensors for value tracking in tracing, and that not working for 32 bit pointers or something

**Comment by t-vi** [comment]
Fair enough. I must admit that it's not really a top priority for me, either, I just wanted to put it out so anyone else stumbling into this can see it.

**Comment by suo** [comment]
Going to close this issue out as it's likely a wontfix for us, and closing it simplifies our issue tracking. If anyone wants this, feel free to comment and/or reopen and we'll take another look!
