### ISSUE TITLE
RuntimeError: inverse: MAGMA library not found in compilation. Please rebuild with MAGMA.

### ISSUE THREAD

**Issue by Sunweijun333** [pytorch/pytorch#27053]
I compiled torch1.0.1 on tx2. But I made a mistake in batch inverse, saying that the magam library is missing. How to solve this problem, thank you for your reply

**Comment by ailzhang** [comment]
Can you try install dependencies following https://github.com/pytorch/pytorch#install-dependencies? If it doesn't work, feel free to reopen with a detailed repro. Thanks

**Comment by Vic2901** [comment]
Hi, do you fix this problem now?

**Comment by colesbury** [comment]
@Vic2901 if you need LAPACK on GPU make sure you install magma:

See the line about magma here:
https://github.com/pytorch/pytorch#install-dependencies

**Comment by Vic2901** [comment]
@colesbury Hi bro, I am not familiar with the LAPACK, could you tell me what it is? The error occurred in the training of my model, I use a inverse function to op a torch GPU tensor which is a 3d tensor and it equivalently contains a batch of square matrix. If I handle it by copying to CPU, it is fine, but a same error comes up in the next operation which is about a multivariate Gaussian distribution creation. It is involved the output of that inverse function. I have no idea what the library MAGMA is and its functionality. Thx:)

**Comment by colesbury** [comment]
@Vic2901 LAPACK is the standard library for linear algebra routines (including things like inverse). MAGMA is an implementation of the LAPACK functions for GPUs (so things like GPU matrix inverse). Without MAGMA, you'll get an error when trying to run linear algebra functions on GPU tensors.

If you install PyTorch via Conda on Linux (instructions [here](https://pytorch.org/)), it should automatically install MAGMA. But if you build PyTorch from source, you'll need to install MAGMA separately.

If you continue to have problems, please file a new issue, including the details of how you installed PyTorch as well as the error you've encountered.

**Comment by Vic2901** [comment]
@colesbury Thx man, it is really helpful. I am not pretty sure how the Pytorch got installed before, because it was installed by others. But if I install Pytorch via pip, that error get fixed. I have just seen to install the dependency via conda instead of pip with the instructions. Is there any difference between the both of Pytorch installations?
