### ISSUE TITLE
CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/soumith/linux-64/pytorch-0.2.0-py35hb1547bd_4cu80.tar.bz2>

### ISSUE THREAD

**Issue by Fzz123** [pytorch/pytorch#2705]
(py35) user@user-ASUS:~$ conda install pytorch torchvision cuda80 -c soumith
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/user/anaconda2/envs/py35:

The following NEW packages will be INSTALLED:

    cffi:        1.10.0-py35_0            https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    cuda80:      1.0-0                    soumith                                                        
    mkl:         2017.0.3-0               https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free        
    pycparser:   2.18-py35_0              https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    pytorch:     0.2.0-py35hb1547bd_4cu80 soumith                                                         [cuda80]
    torchvision: 0.1.9-py35h72e4c6f_1     soumith                                                        

Proceed ([y]/n)? y

pytorch-0.2.0- 100% |################################| Time: 0:06:51   1.10 MB/s
pytorch-0.2.0- 100% |################################| Time: 0:02:03   3.67 MB/s
pytorch-0.2.0- 100% |################################| Time: 0:05:53   1.28 MB/s

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/soumith/linux-64/pytorch-0.2.0-py35hb1547bd_4cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/soumith/linux-64/pytorch-0.2.0-py35hb1547bd_4cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/soumith/linux-64/pytorch-0.2.0-py35hb1547bd_4cu80.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

Today I've tried many times, but every time error occurs in the same step. 
 for helping me to solve this problem!

**Comment by soumith** [comment]
hmmm, could you try the `pip` based install (see instructions on pytorch.org ). Maybe conda.anaconda.org is blocked in your network.
Since there is not much we can do at pytorch end, i am closing the issue.

**Comment by IvyGongoogle** [comment]
as @soumith said, you can use `pip install`

**Comment by seyeeet** [comment]
@soumith how can I check to see if conda.anaconda.org is block or not?
