### ISSUE TITLE
Comparison op support for named tensors

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27077]
## 🐛 Bug

Named tensors are not supported with comparison ops. In particular, we should add support for the following:
- torch.eq, torch.ne, torch.lt, torch.le, torch.ge, torch.gt
- torch.isnan, torch.isinf (implementations only rely on comparison ops iirc).

## To Reproduce

```
x = torch.randn(3, 3, names=('N', 'C'))
y = torch.randn(3, 3, names=('N', 'C'))
x == y

RuntimeError: eq is not yet supported with named tensors. Please drop names via `tensor = tensor.rename(
None)`, call the op with an unnamed tensor, and set names on the result of the operation.
```

## Implementation

TensorIterator performs name inference already. In addition, all of our comparison ops are currently implemented with TensorIterator. To turn on this support, we should annotate the operators in native_functions.yaml with `supports_named_tensor = True`: 
https://github.com/pytorch/pytorch/blob/b16358b2519e19d0235e08d389317214de938e7c/aten/src/ATen/native/native_functions.yaml#L4632-L4638
That should be all that is necessary to turn on named tensor support.

Finally, we should add some tests to https://github.com/pytorch/pytorch/blob/73347e0ae558428078c3e842e3a27634c34bccf1/test/test_namedtensor.py#L607-L696 . The tests don't have to be a part of `test_binary_ops` and can be simple checks that the operators and all their variants (out-of-place, out=, in-place) do indeed propagate names.

**Comment by izdeby** [comment]
fixed in https://github.com/pytorch/pytorch/pull/27162
