### ISSUE TITLE
How to share a submodule but not copying its parameters in the computing graph?

### ISSUE THREAD

**Issue by ukaneverin** [pytorch/pytorch#27070]
Hi,

I am trying to feed a list of input images to a model that incorporates a number of the same submodule. The model is like following:

```
class SubModule(nn.Module):
	def __init__(self):
		super(SubModule, self).__init__()
		self.embedding = nn.Linear(1000,20)

	def forward(self, input):
		return self.embedding(input)

class Model(nn.Module):
	def __init__(self, subnet, n):
		super(Model, self).__init__()
		self.subnet = subnet
		self.fc = nn.Linear(n*20, 2)
		self.n = n

	def forward(self, x_list):
		# x_list is a list of n input images
		out = []
		for i in range(self.n):
			h = self.subnet(x_list[i]) # h: shape[batch_size, feature_length(20)]
			out.append(h.unsqueeze_(1))

		out = torch.cat(out, dim=1) #out: shape[batch_size, n, feature_length(20)]
		out = out.view(out.shape[0], -1)
		out = self.fc(out)
		return out

subnet = SubModule()
m = Model(subnet, 12)
```

Both "subnet" and "m" will be trained by back propagation at some point. I found that "m" actually creates n copies of "subnet". I want the parameters of "subnet" to be shared during training; i.e. every input image is fed through the same submodule. However, I don't want to create a computing graph forwarding multiple submodules at the same time, especially when n is large. Is there anyway to do so? Is there something similar to how RNN's are handled in pytorch for my case?

**Comment by smilesun** [comment]
@ukaneverin, how do you know it makes n copies of subnet?
