### ISSUE TITLE
JIT pickler should support both little endian and big endian systems

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#27083]
## 🚀 Feature

JIT pickler should support both little endian and big endian systems

## Motivation

Most major OSS projects try to support both little endian and big endian systems. As an example, it looks like Tensorflow added support for this in https://github.com/tensorflow/tensorflow/pull/28490. If we don't implement this, we could run into issues in the future when a model is saved on a big endian machine and then is loaded on a little endian machine or vice-versa.

## Additional context

Looking at some of the pickler code it doesn't look like we support big-endian (https://github.com/pytorch/pytorch/blob/7fc06ea5414ba222ae168b9240513aa61489fa2c/torch/csrc/jit/pickler.h#L187)

cc @suo @zdevito

**Comment by suo** [comment]
@pritamdamania87 are there big endian systems that we are trying to target in the near term? I ask because it will help us prioritize this vs. other things we want to do.

**Comment by driazati** [comment]
Endianness is also part of the pickle format itself and should be handled on loading / saving (the binary output from a big endian or little endian system should be the same), so if there are issues with endianness in the pickler that should be considered a bug in our implementation

**Comment by pritamdamania87** [comment]
@suo Not as far as I know. I just noticed this while reading the code and thought I should open an issue to track this.

**Comment by suo** [comment]
Going to close this out as it's likely a wontfix for us and closing the issue simplifies our issue tracking. Feel free to comment/reopen!
