### ISSUE TITLE
[Contributor Welcome] Implement C++ API version of torch.nn.functional.pdist

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#27082]
## Context 

We would like to add `torch::nn::functional::pdist` to the C++ API, so that C++ users can easily find the equivalent of Python API `torch.nn.functional.pdist`.

## Steps

* Add `torch::nn::functional::pdist(...)` in  `torch/csrc/api/include/torch/nn/functional/distance.h` (add this file if it doesn’t exist). The function should have the following signature:

```cpp
namespace torch {
namespace nn {
namespace functional {

inline Tensor pdist(
    const Tensor& input,
    int64_t p = 2) {
  ...
}

} // namespace functional
} // namespace nn
} // namespace torch
```

* Add test for `torch::nn::functional::pdist(...)` in test/cpp/api/functional.cpp. It can just check whether the function output is as expected for some simple cases.

## Helpful Resources

There are quite a few PRs for adding new functionals / new modules for the C++ API (the list of PRs is in https://github.com/pytorch/pytorch/issues/25883), which can serve as great references. Also please ping @yf225 on this issue if you encounter any problems.

## How do I claim this feature request?

Please comment in this issue if you are interested in working on it.

cc @yf225

**Comment by jon-tow** [comment]
@yf225 I'd like to tackle this issue! May I suggest  we place `pdist` in the 
`../torch/nn/functional/distance.h` file along with the other distance functionals?

**Comment by yf225** [comment]
@jon-tow Thanks a lot for taking on it! And you are right that it should live in `../torch/nn/functional/distance.h` - apparently I was not in the right state of mind when writing this up.. 😄
