### ISSUE TITLE
Improve default cut-off for pinverse

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#27095]
PyTorch seems to use a default cut-off of `10e-15` for pinverse
https://github.com/pytorch/pytorch/blob/3ad1bbe16a3c1d6bb9566f09229afd63022a82df/aten/src/ATen/core/TensorBody.h#L622

Since it uses SVD, it should probably use the same cutoff as scipy uses for their SVD-based inverse `pinv2` and `pinvh` which is `max(M,N)*sigma_max*eps`, see https://github.com/scipy/scipy/pull/10067

(found this as the cause of a discrepancy of my pytorch vs scipy calculation)

**Comment by SsnL** [comment]
I think it is so to match numpy https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html

**Comment by yaroslavvb** [comment]
Good point. Not sure this is bad enough to have another numpy API exception so will close for now
