### ISSUE TITLE
More informative gradcheck return codes

### ISSUE THREAD

**Issue by mys007** [pytorch/pytorch#2710]
Hi, 

I find the current return value of `gradcheck` in case of failure rather uninformative (`False`). This makes it hard to debug the problematic Function of interest.
I propose to return more information: the reason for failure (gradient mismatch, size mismatch, non-reentrance, backward doesn't multiply by grad_output) and error magnitude. What would be the best way? Perhaps returning a `namedtuple` in addition to `False` when requested so by a new argument `details=False`?

Piggybacked issue: Isn't the reentrance check at https://github.com/pytorch/pytorch/blob/master/torch/autograd/gradcheck.py#L118 too strict (equality to zero), especially in the case of Functions with some GPU non-determinism? Shouldn't it be sufficient to check against `atol` and `rtol`?

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by gchanan** [comment]
These sound like good ideas.

**Comment by albanD** [comment]
The error messages are now much more verbose and should contain all the information you need.
Let us know if you want more to be added.

For the tolerance, the whole point of the reentrant check is to make sure we get a deterministic behavior that is exact.
For the few ops that need it, you can now pass the `nondet_tol` argument to raise that threshold.
