### ISSUE TITLE
Improve the way RPC unit tests are skipped for windows

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#27129]
##  Feature / Bug
We don't support c10d in Windows. Therefore, It might be useful to add an `@unittest.skipIf` decorator to the relevant test class in `test/test_rpc.py`. This would be another failsafe in addition to the current guard in `test/test_rpc.py`. I have a couple of suggestions on how we could do this:
```
from common_utils import IS_WINDOWS
...
@unittest.skipIf(IS_WINDOWS, 'c10d not supported on windows')
```

or 
```
@unittest.skipIf(not dist.is_available())
```

(which is basically what we do now, but a little cleaner perhaps)

While we're at it, it might be better to refactor the module so that the imports are checked in the following way:

```
try:
    import [imports here]
except ImportError as e:
    unittest.skip('c10d not supported on windows')

... # proceed with normal test file
```

This way, incorrect imports can't mess up tests, since they are caught. This seems to be a bit more idiomatic than the current setup, and it makes it more obvious to the reader under which circumstances we skip the tests. Finally, this reduces the risk of running the auto-linter messing things up, so that we can work towards making our code lint-compliant.

Curious as to what people think about this.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @peterjc123

**Comment by pritamdamania87** [comment]
I think `@unittest.skipIf(not dist.is_available())` would be much cleaner and we should probably add it to the test class rather than functions. Regarding the try-catch, why do we need that in the test file? The imports don't throw at the moment.

**Comment by rohan-varma** [comment]
@pritamdamania87 I was thinking of that for lint compliance. Right now, if you look at some of the test files, the reason we have the imports after the `torch.distributed.is_available()` check is because those imports would throw if distributed wasn't available. If we ran the auto-linter on the code, however, the imports would be moved incorrectly. 

If we want our code to eventually be lint compliant, we might want to try-catch the imports so we can run the linter, and make it more explicit to future readers as to why the imports are that way.

**Comment by zhaojuanmao** [comment]
RPC and distributed autograd tests are skipped for windows and ROCM in run_test.py file now

**Comment by pritamdamania87** [comment]
@rohan-varma Sounds good! Probably best to send a PR and we can have a more detailed discussion there.

**Comment by rohan-varma** [comment]
per @zhaojuanmao's comment, a few PRs have landed over the last couple of days that have improved the state of things. For example, there's no more `import` statements after `torch.distributed.is_available()`, as we are skipping tests using a blacklist in `run_test.py`. It looks like this issue can be closed.
