### ISSUE TITLE
Nondeterminism in ROCm RNNs

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27139]
## 🐛 Bug

In this commit https://github.com/pytorch/pytorch/pull/26791/commits/2c83237d2fddded85774c9ac07e267985b2fe62f the sizes used in test_rnn_retain_variables were increased x10. This caused the corresponding ROCm build to fail (https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py2-clang7-rocmdeb-ubuntu16.04-test1/2418/console). 

Are ROCm RNNs nondeterministic?

## To Reproduce

See commit. test_rnn_retain_variables needs its sizes increased by 10x.

## Expected behavior

Test passes.

cc @zou3519 @gottbrath @ngimel

**Comment by gottbrath** [comment]
thanks for filing!

**Comment by gottbrath** [comment]
This issue is FBA-130 in the AMD jira system.

**Comment by jeffdaily** [comment]
FBA-130 has been closed.  Closing this, too.
