### ISSUE TITLE
refactor nn._intrinsic to nn.intrinsic 

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27152]
Per our discussion in the Quantization team meeting, please refactor the nn._intrinsic to remove the leading underscore. 

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by gottbrath** [comment]
@dzhulgakov @raghuramank100  for visibility

**Comment by jianyuh** [comment]
https://github.com/pytorch/pytorch/pull/27194

**Comment by jianyuh** [comment]
Closing as the PR has been merged.
