### ISSUE TITLE
Build pytorch from source in osx

### ISSUE THREAD

**Issue by aaronbyun** [pytorch/pytorch#2715]
I just installed pytorch from the source code and below code is still return False

torch.cuda.is_available()

What should I do to fix that to work?

**Comment by CDLuminate** [comment]
Is your nvidia driver working correctly? try `nvidia-smi` to figure it out.

**Comment by soumith** [comment]
also, do you have an NVIDIA GPU :)

**Comment by zlmoment** [comment]
I've installed Pytorch from source on Mac OS successfully. You can take a look at my tutorial: https://zhaoyu.li/post/install-pytorch-on-mac-with-nvidia-gpu/

**Comment by soumith** [comment]
i'm closing the issue from non-information. Feel free to follow-up with us at https://discuss.pytorch.org
