### ISSUE TITLE
add "pytorch_linux_xenial_py3_5_test" into CI tests

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#27168]
## 🚀 Feature
"pytorch_linux_xenial_py3_5_test" ran on master, not in CI continuous tests for each PR, request to add "pytorch_linux_xenial_py3_5_test" into CI continuous tests for each PR as well

## Motivation
PR https://github.com/pytorch/pytorch/pull/25656 passed all CI tests, but broke master test run in "pytorch_linux_xenial_py3_5_test" that did not run for our PR. if the tests are covered in our PR CI tests, we can catch issues earlier instead of breaking master tests

cc @ezyang

**Comment by zhaojuanmao** [comment]
cc @mrshenli @pritamdamania @pietern @rohan-varma

**Comment by pietern** [comment]
This is done to decrease the load on the CI and still get relatively high test signal on PRs.

You can trigger more builds to run by adding the tag `[test all]` to your commit message.

**Comment by pietern** [comment]
Also cc @ezyang @kostmo

**Comment by ezyang** [comment]
Can you help me understand a little more what happened with the test failures here? As @pietern said, we don't run all tests on PRs because for the vast majority of PRs, errors will be caught in other configurations. Sometimes, we can adjust the set of configs run on PRs to cover your case (without increasing the number of builds); that would be my preferred resolution. Was this a Python 3.5 specific problem here?

**Comment by zhaojuanmao** [comment]
@ezyang yes, this is a Python 3.5 specific problem. Yesterday I landed a diff that passed all CI tests for the PR but broke master Python 3.5 tests. then I checked CI tests in my PR did not have "pytorch_linux_xenial_py3_5_test", so I did not find the issue earlier before landing the diff. 

What I'm saying is that if  PR CI tests do not align with master tests, then it is possible a PR could break master, right? like us...

**Comment by ezyang** [comment]
Yes, absolutely. So the question is, how likely are you to cause a Python 3.5 only problem? I agree with you the chance is nonzero: we've had a handful of other cases where people introduced 3.5 only incompatibility. But it is very rare. And so the cost of the rare occurrence has to be weighed against running the test on every PR, where it contributes no useful signal.

Once you do discover things have broken on master, the steps should be:

1. Revert
2. Work on your PR with the test in question explicitly enabled. I don't think `[test all]` currently enables 3.5 but I can make this so. #27293

**Comment by pritamdamania87** [comment]
@ezyang What were the issues we saw when we ran all tests on all PRs? I feel we should strive for this setup since its easier for developers to ensure their changes don't break master and as a result we have better developer productivity. I've run into this issue multiple times where CI on my PR is green, but it fails on master. This hurts productivity for everyone since we end up breaking master.

If CI load is a problem, can't we just ask for more capacity from CircleCI? I understand we are planning to have the ability to manually trigger all tests, but until we have that can we enable all tests on PRs?

**Comment by ezyang** [comment]
> What were the issues we saw when we ran all tests on all PRs?

Context is https://fb.workplace.com/groups/ToffeeInternal/permalink/433039560607863/ (fb-only sorry)

I posted my analysis publicly also in this PR https://github.com/pytorch/pytorch/pull/20775

The short answer is it doesn't have much to do with capacity: rather, it has to do with reducing flakiness. Here's some text I wrote in the original RFC:

> Neither actually (though the money savings is nice): running less jobs means we are less impacted by flakiness. Suppose your goal is to reduce the probability that any given run of the CI fails due to flakiness. This requires every build to be non-flaky. Suppose that your CI is 99% reliable on a per job basis. If you run 100 jobs per PR, you have a 63% chance of failure due to flakiness. If you halve the number of jobs you run, you now only have a 40% chance of failure.
>
> To get a comparable win by reducing underlying flakiness, you would have to go from 99% reliable to 99.5% reliable: you have to cut flakiness in half! Both approaches are worth pursuing, but the claim (backed from data) is that reducing the number of CI jobs is low risk (because they are highly correlated). We can reevaluate when we see commits make it to master that break non-PR builds.

To be clear, we might have gotten the default set wrong. But the solution to that is not to turn all builds back on; it is to collect data (as I did in my initial analysis) and then propose adjustments to the default set based on that data. There was an attempt to collect cases where people broke master (but PR was green) at https://fb.workplace.com/groups/1274980366011614/permalink/1279634782212839/ but I think most people don't know to send feedback when this happens, so we probably need some automatic mechanism to collect this info.

**Comment by pritamdamania87** [comment]
Thanks for providing additional context. If the goal is to reduce flakiness, I feel the right thing to do is to spend time analyzing why the builds are flaky and fixing them. I feel reducing the number of CI jobs to combat flakiness is just a way of hiding the problem. You will still have have to deal with flakiness for master only tests. If you run more CI jobs, it would actually be easier to flag which builds are flaky (with more data) and prioritize fixing those or disabling them if they don't provide enough value. I don't think we should have two sets of builds at all (we shouldn't have a default set that we tweak for PRs), whatever we run on PRs should be the same thing we run for master. If we decide to disable a CI job for PRs, it should be disabled in the CI run on master and vice-versa.

> Also, if you break a master only test, this doesn't actually affect developer productivity, because they won't see failures on their PRs

I agree in general it probably won't affect most developers, but it might actually break the workflow for some developers that have a similar environment as the broken CI builds. Although, it definitely does hurt productivity of the author of the PR. The author needs to resubmit the PR, resolve merge conflicts again if something else was checked in and wait for another full CI run (which can be pretty long) before they can land.

**Comment by ezyang** [comment]
> I feel the right thing to do is to spend time analyzing why the builds are flaky and fixing them. I feel reducing the number of CI jobs to combat flakiness is just a way of hiding the problem.

The two approaches are complimentary: I don't think reducing the number of builds we run as hiding the problem.

The trouble with flakiness is that you can't just "fix a bunch of flaky tests and then call it a day". People are continuously adding new tests; you need a way to detect and deal with flaky tests as they get committed. Even if you fix it today, tomorrow things might be flaky again (indeed, my lived experience as someone who reviews a *lot* of CI builds is every day is something different.) Reduction of the number of tests you run is durable: we don't add new contbuilds that frequently, and so the payoff you get from having reduced the number of builds by 50% keeps paying off.

> Although, it definitely does hurt productivity of the author of the PR. The author needs to resubmit the PR, resolve merge conflicts again if something else was checked in and wait for another full CI run (which can be pretty long) before they can land.

Yes. Of course it is better to find out about these failures before you land to master. We're talking tradeoffs here, not absolutes. But we have plenty of tools to reduce the cost of your diff not being on master: e.g., stack diff development: so you don't have to block waiting for your earlier diff to land.

**Comment by pietern** [comment]
@zhaojuanmao @pritamdamania87 Does this warrant more discussion or do you think we can close this? Having a more systemic way to deal with this would be preferable over cherry picking configurations that have broken in the past, but what that approach would be, I don't know.

**Comment by zhaojuanmao** [comment]
closing this, @ezyang helped added py35 tests to CI now

**Comment by pietern** [comment]
@zhaojuanmao Can you point to the commit/PR that added py35 to CI?

**Comment by zhaojuanmao** [comment]
I'm not sure which PR added py35 to CI, but I checked that py35 tests ran in my recent PRs even I did not specify [test all]. for example, there is active PR https://github.com/pytorch/pytorch/pull/28485, you can see that py35 build is running

**Comment by pietern** [comment]
@zhaojuanmao This is not the case. If you click on those builds, you see they are getting skipped.

They show up in the check list because they have to be triggered before we can check if they should be skipped. Unfortunately there is no custom GitHub status for _skipped_ that I know of...

**Comment by zhaojuanmao** [comment]
@pietern I see!  did not realize builds and tests could be skipped in check list. 

but since Edward added PY35 to [test all] list in #27293, i think it is also fine to close this PR for now.
