### ISSUE TITLE
tensor.align_to doesn't need the tensor to be fully named

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27174]
Explanation. In the following code:
```
x = torch.randn(2, 3, 5, 7)
x.refine_names(..., 'D')
x.align_to('D', ...)
```
it is unambiguous how to actually rearrange the dimensions (the output should have size (7, 2, 3, 5) because the `...` in `align_to` means "the unmentioned dimensions of `x` in the order that they appear in `x`.

However, if we run the above right now, we get
```
RuntimeError: align_to: All input dims must be named, got tensor with dims: (None, None, None, No
ne). Please use `tensor.refine_names(*names)` to add names to unnamed dims
```

It's inconvenient to name tensors with a lot of dimensions and having the above work would be nice.

**Comment by stante** [comment]
I think this issue can be closed because https://github.com/pytorch/pytorch/pull/27308 was merged.

**Comment by zou3519** [comment]
Thanks for the catch @stante, that PR did indeed fix this. I am closing this issue.
