### ISSUE TITLE
ONNX export fails for Pooling modules with kernel_size as tuple

### ISSUE THREAD

**Issue by lantiga** [pytorch/pytorch#2717]
When exporting a model like 
```
model = nn.Sequential(
    nn.Conv2d(1, n1, kernel_size=3, stride=1, padding=1),
    nn.Tanh(),
    nn.MaxPool2d(kernel_size=(1, 2))
```
to ONNX, export fails with
```
TypeError: is_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: unicode, arg1: List[int]) -> torch._C.Node

Invoked with: %32 : UNKNOWN_TYPE = MaxPool(%31), uses = [];
, 'kernel_shape', [(1, 2), (1, 2)]
```

The error doesn't show up when passing `kernel_size` as a scalar.

This commit https://github.com/pytorch/pytorch/commit/3b5a5a6f9caaf0e545331bb8d15750c6acbb5e1b
is responsible, we need to manage both cases, scalar or tuple. And probably check that this is taken care of in other modules.

@soumith I can take care of this.

**Comment by ezyang** [comment]
That diagnosis sounds spot on. Thank you!
