### ISSUE TITLE
torch.full is inconsistent with np.full

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27171]
## 🐛 Bug
https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html

Numpy does type inference on `full` but pytorch does not.

## To reproduce

```
import torch
import numpy as np
print(torch.full((10, 1), 5).dtype)
print(np.full((10, 1), 5).dtype)
```
Gives:
```
torch.float32
int64
```
cc @ezyang @SsnL @gchanan

**Comment by gchanan** [comment]
Yep, we don't do type inference on full, but we probably should.

**Comment by SsnL** [comment]
This would be a major BC breaking change btw.

**Comment by gchanan** [comment]
eh, we did the same thing for `arange` and no one complained :).

Plus if you have type promotion things just work.

**Comment by mruberry** [comment]
This was fixed by https://github.com/pytorch/pytorch/pull/41912.
