### ISSUE TITLE
Rpc spawn test segfault on PY35

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#27182]
## 🐛 Bug

Rpc spawn test segfault on PY35

For python3.5, it looks like the child processes are segfaulting:
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005643db47fcd4 in code_dealloc ()
[Current thread is 1 (Thread 0x7f00a7986740 (LWP 2496293))]
(gdb) bt
#0  0x00005643db47fcd4 in code_dealloc ()
#1  0x00005643db480538 in func_dealloc ()
#2  0x00007f009ca8112f in torch::distributed::rpc::PythonRpcHandler::~PythonRpcHandler() () from /data/users/pritam/pytorch/torch/lib/libtorch_python.so
#3  0x00007f00a71ccb69 in __run_exit_handlers () from /lib64/libc.so.6
#4  0x00007f00a71ccbb7 in exit () from /lib64/libc.so.6
#5  0x00005643db51e4d1 in Py_Exit ()
#6  0x00005643db51e5b8 in handle_system_exit ()
#7  0x00005643db51e622 in PyErr_PrintEx ()
#8  0x00005643db52e806 in PyRun_SimpleStringFlags ()
#9  0x00005643db52f679 in Py_Main ()
#10 0x00005643db3f9571 in main ()

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma

**Comment by zhaojuanmao** [comment]
cc @mrshenli @pritamdamania @xush6528 @aazzolini

**Comment by zhaojuanmao** [comment]
python 3.6 is fine, but crashed on python 3.5, needs to debug it

**Comment by xush6528** [comment]
@zhaojuanmao Can we only test it on py3.6?

**Comment by zhaojuanmao** [comment]
@xush6528 after your diff we will only test it on py3.6, some master tests run on py3.5 and all spawn tests failed there, it would be good to know why it crashed though.  also if we only support >py3.6, we need to add it to documentation
