### ISSUE TITLE
ONNX and grid_sample layer

### ISSUE THREAD

**Issue by greatkoara** [pytorch/pytorch#27212]
## 🚀 Feature

Add support for conversion of `grid_sample` layer into ONNX.

## Motivation

It could be really hard to perform geometric deformations on image such as object stretch or horizontal flip with convolutional layers, especially using relatively small models.

[Spatial Transformer Networks tutorial by PyTorch](https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html) as one more instance of motivation for proposed feature.

## Pitch

PyTorch supports `grid_sample` layer. It would be great to have an ability to convert models with this layer in ONNX for further usage.

## Additional context

Minimal code:

```python
import torch

import torch.nn.functional as F


class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()

    def forward(self, x, m):
        return F.grid_sample(x, m)


x = torch.rand(1, 1, 10, 10)
m = torch.Tensor([[[1, 0, 0], [0, 1, 0]]])
m = F.affine_grid(m, x.size()).type_as(x)

model = MyModel()

torch.onnx.export(
    model,
    (x, m),
    "grid_sample.onnx",
    verbose=True,
    input_names=['input', 'grid'],
    output_names=['output']
)
```

[Reference](https://github.com/onnx/onnx/issues/2383) to my issue in ONNX repository to add spatial transformer operator.

**Comment by aar0npham** [comment]
@greatkoara have you figured out a way to support `grid_sample` when converting to ONNX yet?

**Comment by likedan** [comment]
Has this been added?

**Comment by ahangchen** [comment]
+1

**Comment by fpreiswerk** [comment]
+1

**Comment by buqing2009** [comment]
+1

**Comment by tairen99** [comment]
+1

**Comment by CosmicHunter** [comment]
Is there any update on how to convert the model that contains  an aTen operator grid_sampler?

**Comment by pustar** [comment]
+1

**Comment by GordonDongZHAO** [comment]
+1

**Comment by AlexanderSerbul** [comment]
+1

**Comment by PkuRainBow** [comment]
+1

**Comment by JeeKangaroo** [comment]
+1

**Comment by yingsiq** [comment]
+1

**Comment by yangfh2004** [comment]
+1

**Comment by huihuiustc** [comment]
+1

**Comment by MaybeS** [comment]
+1

**Comment by andriyrizhiy** [comment]
+1

**Comment by NewCoderQ** [comment]
+1

**Comment by tovacinni** [comment]
+1

**Comment by RunningLeon** [comment]
Do we have any suggestion to this issue? THX.

**Comment by tangyanf** [comment]
It's been a year, no one has dealt with this problem yet？

**Comment by ofeknesher2** [comment]
+1

**Comment by PVSemk** [comment]
+1

**Comment by bastianmorath** [comment]
+1

**Comment by ChaceYoung** [comment]
+1

**Comment by adahbingee** [comment]
+1

**Comment by SmallHedgehog** [comment]
> +1

**Comment by OrkhanHI** [comment]
any updates on this issue??

**Comment by gxd1994** [comment]
+1

**Comment by OrkhanHI** [comment]
Soon is 2021, so far nobody from 2019 fixed the **grid sample** conversion issue

**Comment by OrkhanHI** [comment]
I have written Python code for `grid_sample` with zero-padding and can pass align_corners argument as well. 
```
https://github.com/OrkhanHI/pytorch_grid_sample_python/blob/main/pytorch_grid_sample_python.md
```

**Comment by mpottinger** [comment]
> I have written Python code for `grid_sample` with zero-padding and can pass align_corners argument as well.
> 
> ```
> https://github.com/OrkhanHI/pytorch_grid_sample_python/blob/main/pytorch_grid_sample_python.md
> ```

Wow, only posted just minutes ago, while I am struggling trying to get this model converted to onnx. I'll try this out, thanks!

**Comment by OrkhanHI** [comment]
> > I have written Python code for `grid_sample` with zero-padding and can pass align_corners argument as well.
> > ```
> > https://github.com/OrkhanHI/pytorch_grid_sample_python/blob/main/pytorch_grid_sample_python.md
> > ```
> 
> Wow, only posted just minutes ago, while I am struggling trying to get this model converted to onnx. I'll try this out, thanks!

I am trying to convert also, just replaced this function with `torch.nn.functional.grid_sample`. Somehow, RAM is getting full while checking `ind_missing_ops_onnx_export`
```
import torch.onnx.utils as utils
utils._find_missing_ops_onnx_export(model, input, "test.onnx", verbose=True)
```

**Comment by mpottinger** [comment]
Yeah unfortunately it seems to just be freezing for me. CPU usage is at 100% and it looks like it's stuck while converting.

**Comment by mpottinger** [comment]
> > > I have written Python code for `grid_sample` with zero-padding and can pass align_corners argument as well.
> > > ```
> > > https://github.com/OrkhanHI/pytorch_grid_sample_python/blob/main/pytorch_grid_sample_python.md
> > > ```
> > 
> > 
> > Wow, only posted just minutes ago, while I am struggling trying to get this model converted to onnx. I'll try this out, thanks!
> 
> I am trying to convert also, just replaced this function with `torch.nn.functional.grid_sample`. Somehow, RAM is getting full while checking `find_missing_ops_onnx_export`
> 
> ```
> import torch.onnx.utils as utils
> utils._find_missing_ops_onnx_export(model, input, "test.onnx", verbose=True)
> ```

In the debugger it is looping in bilinear_interpolate_torch_2D. I am not yet a Pytorch expert but I am assuming these kinds of operations are very slow in pure Python code.

**Comment by OrkhanHI** [comment]
> > > > I have written Python code for `grid_sample` with zero-padding and can pass align_corners argument as well.
> > > > ```
> > > > https://github.com/OrkhanHI/pytorch_grid_sample_python/blob/main/pytorch_grid_sample_python.md
> > > > ```
> > > 
> > > 
> > > Wow, only posted just minutes ago, while I am struggling trying to get this model converted to onnx. I'll try this out, thanks!
> > 
> > 
> > I am trying to convert also, just replaced this function with `torch.nn.functional.grid_sample`. Somehow, RAM is getting full while checking `find_missing_ops_onnx_export`
> > ```
> > import torch.onnx.utils as utils
> > utils._find_missing_ops_onnx_export(model, input, "test.onnx", verbose=True)
> > ```
> 
> In the debugger it is looping in bilinear_interpolate_torch_2D. I am not yet a Pytorch expert but I am assuming these kinds of operations are very slow in pure Python code.

Their C implementation includes `#pragma omp parallel for private(n, h, w, c)` before looping. Seems like they run it in parallel, so it is faster.

**Comment by mpottinger** [comment]
> Their C implementation includes `#pragma omp parallel for private(n, h, w, c)` before looping. Seems like they run it in parallel, so it is faster.

I am currently trying to modify incorporate your code as torchscript. I'm making some progress, it looks like there is hope for it to work that way, but it is difficult because it is my first time dealing with torchscript. I'm having difficulty getting all the type annotations right.

**Comment by mpottinger** [comment]
Nope, unfortunately still slow in torchscript. I at least got it to start compiling without errors, but then when the compile errors are gone it just goes into the same very long loop. Unfortunately it looks like we will need help from an onnx implementation. 

Looks like for now I will be deploying this module using Python on Android. (Chaquopy or Termux)

Not sure if my below torchscript conversion is all correct, but it is still the same speed. :(

@torch.jit.script
def grid_sampler_unnormalize(coord: int, side: int) -> int:
    return ((coord + 1) * side - 1) // 2

@torch.jit.script
def grid_sampler_compute_source_index(coord: int, size: int) -> int:
    coord = grid_sampler_unnormalize(coord, size)
    return coord

@torch.jit.script
def safe_get(image: torch.Tensor, n: int, c: int, x: int, y: int, H: int, W: int) -> torch.Tensor:
    value = torch.tensor([0])
    if 0 <= x < W and 0 <= y < H:
        value = image[n, c, y, x]
    return value

@torch.jit.script
def bilinear_interpolate_torch_2D(image: torch.Tensor, grid: torch.Tensor) -> torch.Tensor:
    '''
         input shape = [N, C, H, W]
         grid_shape  = [N, H, W, 2]

         output shape = [N, C, H, W]
    '''
    N, C, H, W = image.shape
    grid_H = grid.shape[1]
    grid_W = grid.shape[2]

    output_tensor = torch.zeros_like(image)
    for n in range(N):
        for w in range(grid_W):
            for h in range(grid_H):
                # get corresponding grid x and y
                x = int(grid[n, h, w, 1])
                y = int(grid[n, h, w, 0])

                # Unnormalize with align_corners condition
                ix = grid_sampler_compute_source_index(x, W)
                iy = grid_sampler_compute_source_index(y, H)

                x0 = torch.floor(ix)
                x1 = x0 + 1

                y0 = torch.floor(iy)
                y1 = y0 + 1

                # Get W matrix before I matrix, as I matrix requires Channel information
                wa: float = (float(x1) - float(ix)) * (float(y1) - float(iy))
                wb: float = (float(x1) - float(ix)) * (float(iy) - float(y0))
                wc: float = (float(ix) - float(x0)) * (float(y1) - float(iy))
                wd: float = (float(ix) - float(x0)) * (float(iy) - float(y0))

                # Get values of the image by provided x0,y0,x1,y1 by channel
                for c in range(C):
                    # image, n, c, x, y, H, W
                    Ia: torch.Tensor = safe_get(image, n, c, y0, x0, H, W)
                    Ib: torch.Tensor = safe_get(image, n, c, y1, x0, H, W)
                    Ic: torch.Tensor = safe_get(image, n, c, y0, x1, H, W)
                    Id: torch.Tensor = safe_get(image, n, c, y1, x1, H, W)
                    out_ch_val: torch.Tensor = torch.t((torch.t(Ia) * wa)) + torch.t(torch.t(Ib) * wb) + torch.t(torch.t(Ic) * wc) + torch.t(torch.t(Id) * wd)
                    if out_ch_val.shape == output_tensor.shape:
                        output_tensor[n, c, h, w] = out_ch_val
    return output_tensor

**Comment by OrkhanHI** [comment]
I have used `pymp` library to make it run with multiple threads, it kinda speed up the loop operation, but when I am trying to convert it still using all my RAM :(

**Comment by mpottinger** [comment]
> I have used `pymp` library to make it run with multiple threads, it kinda speed up the loop operation, but when I am trying to convert it still using all my RAM :(
> ![RAM_usage](https://user-images.githubusercontent.com/46919226/103503354-f5238380-4e8e-11eb-9543-f6d645975d88.png)

Can Numba be used in Pytorch models? I have seen huge speedups with other tasks using that.

I have given up though, I was successfully able to convert my model to work with Pytorch Mobile. At least there is more than one option. Not ideal because they don't have GPU acceleration yet, but good enough when onnx doesn't work.

**Comment by OrkhanHI** [comment]
To be honest, I havent used Numba. Can you convert directly to Pytorch Mobile without converting the model to ONNX?

**Comment by mpottinger** [comment]
> To be honest, I havent used Numba. Can you convert directly to Pytorch Mobile without converting the model to ONNX?

Numba is simple, it is just pure python code with a function decorator on top, and then your code works at C speed. However it is finicky about using objects. It only works with Numpy arrays, and ints, floats, etc. 

Yes Pytorch Mobile went suprisingly smooth for this particular model. I have another one that only converts with onnx but doesn't work with Pytorch mobile. They are two separate processes, so at least if one doesn't work, try the other.

**Comment by OrkhanHI** [comment]
Could you please share the code of model conversion to `Pytorch Mobile`?

**Comment by budaLi** [comment]
Under constant attention......

**Comment by mpottinger** [comment]
> Could you please share the code of model conversion to `Pytorch Mobile`?
# load your original model and run:

Sure, it was surprisingly simple and straightforward. input, but I just modified the model forward() code to have default values. I haven't figured out quantization though, that seems more complicated.

from torch.utils.mobile_optimizer import optimize_for_mobile

model.eval()

# create dummy inputs for your model, this model takes two images.
input_image1 = torch.randn(1, 3, 256, 320)
input_image2 =  torch.randn(1, 3, 256, 320)

#export to Pytorch mobile
traced_script_module = torch.jit.trace(model, (input_image1, input_image2))
torchscript_model_optimized = optimize_for_mobile(traced_script_module)
torch.jit.save(torchscript_model_optimized, "model_mobile.pt")

# later, load your mobile model for inference:
model = torch.jit.load("model_mobile.pt")

**Comment by ahangchen** [comment]
One workaround: https://github.com/TrojanXu/onnxparser-trt-plugin-sample

confirmed on xavier nx, torch 1.6.0, tensorRT7.1.3.4, onnx1.6.0
### How it works

Currently, to get torch-onnx-tensorrt working with custom op, you have to

- Let torch/onnx recoganize and export the custom op that not in standard opset, here we choose opset10. Thus we need to hack into symbolic_opset10.py. This is now done within the test_plugin_result.py script by manully register op into opset10 along with setting enable_onnx_checker=False during onnx export.
- Let onnxparser understand how to translate the custom op exists in onnx file to TensorRT layers including plugins. Thus we need to hack into builtin_op_importers.cpp
- Instead of hacking into onnxparser's source code, from TensorRT7.1, we support using onnxgraphsurgeon to modify the onnx model and replace the unknown node GridSampler with TRT_PluginV2 node, filled with corresponding buffer, refer to function modify_onnx().
- Let TensorRT know there's a new custom op named GridSampler. Here we implemented it as a plugin. Addtionally, since onnxparser only works with full dimension mode, we have to implement the trt plugin using IPluginV2DynamicExt introduced in TRT6.
- Dynamic shape can be used if you export onnx model using dynamic_axes as illustrated in test_plugin_result.py. This will be processed in onnx-tensorrt module and then addInput is called using -1 as dummpy input dim. About how to build engine and context for dynamic shape, please refer to test_plugin_result.py.

**Comment by SystemErrorWang** [comment]
+1
this issue has been there for a long time, really looking forward to a solution.

**Comment by lihaoxiang1989** [comment]
+1

**Comment by mrljwlm** [comment]
+1

**Comment by jybae-creator** [comment]
Help!!
[pytorch custom integer sampling kernel](https://stackoverflow.com/questions/66633854/pytorch-custom-integer-sampling-kernel-grid-sample)

**Comment by tejal567** [comment]
Please address this issue, much needed feature! @soumith

**Comment by dd1ge** [comment]
Please address this issue, help!!!

**Comment by octavianoos** [comment]
please solve this issue asap

**Comment by Monteiro4** [comment]
+1

**Comment by zhengshunkai** [comment]
+1

**Comment by tommy19970714** [comment]
+1

**Comment by dawei03896** [comment]
please solve this issue asap

**Comment by RunningLeon** [comment]
@dawei03896 @Monteiro4 Hi all, could take a look at mmcv if you want to export to ONNX with `grid_sampler` op:
https://github.com/open-mmlab/mmcv/blob/master/docs/onnxruntime_custom_ops.md#grid_sampler

**Comment by zhoumenghan** [comment]
> @dawei03896 @Monteiro4 Hi all, could take a look at mmcv if you want to export to ONNX with `grid_sampler` op:
> https://github.com/open-mmlab/mmcv/blob/master/docs/onnxruntime_custom_ops.md#grid_sampler

hi, The link you gave is invalid. Can you give a correct link address? please ~~~

**Comment by RunningLeon** [comment]
@zhoumenghan https://github.com/open-mmlab/mmcv/blob/master/docs/deployment/onnxruntime_custom_ops.md#grid_sampler

**Comment by AnnonymousRacoon** [comment]
+1

**Comment by msollami-sf** [comment]
+1

**Comment by skaldesh** [comment]
+1

**Comment by domef** [comment]
+1

**Comment by timiil** [comment]
+1 very need here :)

**Comment by dzy130120** [comment]
please solve this issue. 
+1

**Comment by nkzyj** [comment]
+1 It's a useful operation

**Comment by zgj-gutou** [comment]
+1
I cried，please.....

**Comment by Tchaikovic** [comment]
+1

**Comment by sanchitvohra** [comment]
+1

**Comment by avostryakov** [comment]
this command will be added in onnx 1.11. So, it can be added in pytorch onnx export after it. +1

**Comment by jucic** [comment]
> this command will be added in onnx 1.11. So, it can be added in pytorch onnx export after it. +1
thanks for your information, how long does it take? I need this feature badly

**Comment by jucic** [comment]
+10086

**Comment by avostryakov** [comment]
> this command will be added in onnx 1.11. So, it can be added in pytorch onnx export after it. +1
> thanks for your information, how long does it take? I need this feature badly

I know that in onnx it will be added in November 2021. I don't know when it can be added in pytorch if any

**Comment by styler00dollar** [comment]
The solution from above which mentions replacing `F.grid_sample` with `bilinear_grid_sample` from `mmcv` seems to work, but this is not a valid solution, because their implementation [**is only for CPU**](https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/docs/en/deployment/onnxruntime_op.md). It won't work if you attempt to use GPU. Inference with CPU is simply too slow.

![grid](https://user-images.githubusercontent.com/51405565/147003254-c4688b24-f3e0-40c8-ac7d-1234bc820f1c.png)

It seems like it got added [in onnx](https://github.com/onnx/onnx/issues/2383) now, but still waiting for PyTorch.

**Comment by Tengxu-Sun** [comment]
> 

Yeah, CPU is too slow.

**Comment by Tengxu-Sun** [comment]
> The solution from above which mentions replacing `F.grid_sample` with `bilinear_grid_sample` from `mmcv` seems to work, but this is not a valid solution, because their implementation [**is only for CPU**](https://github.com/open-mmlab/mmcv/blob/e4b5348ebf407f0886bc11caa7ca74d2fbf693ac/docs/en/deployment/onnxruntime_op.md). It won't work if you attempt to use GPU. Inference with CPU is simply too slow.
> 
> ![grid](https://user-images.githubusercontent.com/51405565/147003254-c4688b24-f3e0-40c8-ac7d-1234bc820f1c.png)
> 
> It seems like it got added [in onnx](https://github.com/onnx/onnx/issues/2383) now, but still waiting for PyTorch.

Yeah, CPU is too slow.

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1516412>
We hope to support this in torch.onnx.export after ONNX Runtime supports the op, which should hopefully happen in 1.11.

**Comment by imneonizer** [comment]
I hope this gets added sooner

**Comment by svarjo** [comment]
+1

**Comment by ykk648** [comment]
any update now?

**Comment by daigo0927** [comment]
Latest ONNX opset16 seems to support GridSample by https://github.com/onnx/onnx/blob/main/docs/Changelog.md#GridSample-16.
I think we are waiting PyTorch for relate the `F.grid_sample` with GridSample of ONNX 🤔

**Comment by lightsalt2011** [comment]
onnx 1.11 has include this grid_sample  op, but pytorch's onnx max op version is 14 still, how to update onnx manully ?

**Comment by daigo0927** [comment]
FYI: Microsoft offers contrib GridSample ops. We can register the contrib GridSample operation as a counterpart of `F.grid_sample` like below:

```python
from torch.onnx import register_custom_op_symbolic
import torch.onnx.symbolic_helper as sym_help

def grid_sampler(g, input, grid, mode, padding_mode, align_corners):
        # mode
        #   'bilinear'      : onnx::Constant[value={0}]
        #   'nearest'       : onnx::Constant[value={1}]
        #   'bicubic'       : onnx::Constant[value={2}]
        # padding_mode
        #   'zeros'         : onnx::Constant[value={0}]
        #   'border'        : onnx::Constant[value={1}]
        #   'reflection'    : onnx::Constant[value={2}]
        mode = sym_help._maybe_get_const(mode, "i")
        padding_mode = sym_help._maybe_get_const(padding_mode, "i")
        mode_str = ['bilinear', 'nearest', 'bicubic'][mode]
        padding_mode_str = ['zeros', 'border', 'reflection'][padding_mode]
        align_corners = int(sym_help._maybe_get_const(align_corners, "b"))

        return g.op("com.microsoft::GridSample", input, grid,
                    mode_s=mode_str,
                    padding_mode_s=padding_mode_str,
                    align_corners_i=align_corners)
    
register_custom_op_symbolic('::grid_sampler', grid_sampler, 1)
```

This is officially used in [onnxruntime](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/pytorch_export_contrib_ops.py) and I have check with my [gist](https://gist.github.com/daigo0927/8c8b3005cffb61983e80ceab6c1f2274).

**Comment by rr-yuki** [comment]
How about shape inference? I'm a beginner in onnx but I'm getting an error that seems to be complaining about the lack of it.

**Comment by germanjke** [comment]
hey! I have this problem in `torch.onnx.export`, I guess ONNX solved this problem, but `torch.onnx` not updated yet?

**Comment by imneonizer** [comment]
> hey! I have this problem in `torch.onnx.export`, I guess ONNX solved this problem, but `torch.onnx` not updated yet?

Exactly!

**Comment by HuangPengGui** [comment]
my torch version is 1.9.1
RuntimeError: Exporting the operator grid_sampler to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
