### ISSUE TITLE
LINK : fatal error LNK1102: out of memory (Windows CUDA CI) LNK

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#27215]
I've noticed this quite a few times, so I finally decided to file an issue about it.

A lot of py2-cuda9.0-cudnn7-windows-build are failing with 

```
23:54:12 caffe2\CMakeFiles\torch.dir\__\torch\csrc\cuda\comm.cpp.obj "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cudart_static.lib" lib\cpuinfo.lib lib\foxi_loader.lib lib\cpuinfo.lib lib\c10_cuda.lib "C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cudart_static.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cudart_static.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cusparse.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\curand.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\curand.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cudnn.lib" -WHOLEARCHIVE:C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/lib/caffe2_protos.lib lib\clog.lib -WHOLEARCHIVE:C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/lib/onnx.lib lib\onnx_proto.lib lib\libprotobuf.lib -WHOLEARCHIVE:C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/lib/Caffe2_perfkernels_avx.lib -WHOLEARCHIVE:C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/lib/Caffe2_perfkernels_avx2.lib -WHOLEARCHIVE:C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/lib/Caffe2_perfkernels_avx512.lib lib\c10.lib "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cudart_static.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cufft.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64\cublas.lib" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib 
23:54:12    Creating library lib\torch.lib and object lib\torch.exp
23:54:12 LINK : fatal error LNK1102: out of memory
23:54:12 ninja: build stopped: subcommand failed.
```

https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-build/70519/console

I haven't seen this happen to PyTorch builds for some reason though

cc @ezyang @gchanan @zou3519 @jerryzh168 @peterjc123

**Comment by peterjc123** [comment]
Oh, this problem is finally coming, which I thought should happen after merging Caffe2 and PyTorch. Since there is a hard limit on the size of the generated library, and this limit won't be removed in the near future at the MSVC side, the solution is to split the new torch library. We will need further discussion on this because it is unwise to simply revert the merge process.

> I haven't seen this happen to PyTorch builds for some reason though

Because Caffe2 builds contain more things, like `detectron` and so on.

**Comment by ezyang** [comment]
Oof!

> Since there is a hard limit on the size of the generated library

Just to clarify for my sake: you're talking about a different limit than the exposed symbols limit, right?

**Comment by peterjc123** [comment]
Yes, it failed due to an internal limit that I didn't know clearly.

**Comment by dzhulgakov** [comment]
Do we know how to measure what exact limit it is (size of library?). We could see how much BUILD_CAFFE2_OPS=0 saves us. It'd be fairly easy to separate the op registrations to the separate library.

**Comment by ezyang** [comment]
@dzhulgakov To clarify, this is specifically the Caffe2 windows build, NOT the PyTorch build. So you can't just turn off the Caffe2 ops ;)

**Comment by elnazsn1988** [comment]
I am facing the same issue https://github.com/pytorch/pytorch/issues/27840 , am I correct in understanding from above that this is a memory limit issue and not regarding configurations?

**Comment by ezyang** [comment]
Yes I think so

**Comment by ezyang** [comment]
I was reviewing our library structure and maybe one way to alleviate this problem is to actually split `libtorch.so` into `libtorch.so` and `libtorch_cuda.so`. I had thought we had this split, but actually we don't.

**Comment by ezyang** [comment]
As of https://github.com/pytorch/pytorch/pull/28251 this is now affecting PyTorch Windows builds

**Comment by peterjc123** [comment]
Can we get the actual memory usage during the linking stage? How much memory do we have on the build machine?

**Comment by ezyang** [comment]
We're running Windows on c5.2xlarge which is 16G. I don't know how much memory we're using at link time; if there's some way to run the equivalent of top continuously as we're linking we can check.
