### ISSUE TITLE
Upsampling is not implemented for 1D (temporal) inputs

### ISSUE THREAD

**Issue by ikostrikov** [pytorch/pytorch#2723]
Hi! 

Upsampling is available for 2D and 3D inputs but not available for 1D data.
http://pytorch.org/docs/master/nn.html?highlight=upsample#torch.nn.Upsample

It's still possible to upsample in a hacky way but it would be better to have a native implementation.

Thanks!

**Comment by lantiga** [comment]
I'll take this one

**Comment by lantiga** [comment]
Branch almost ready here: https://github.com/lantiga/pytorch/tree/upsample_1d

The CPU version works and tests pass.

I still have an issue on Cuda that I'm trying to sort out: it builds correctly but then when I `import torch` from Python I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/src/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/ubuntu/src/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so.1: undefined symbol: THNN_CudaDoubleTemporalUpSamplingLinear_updateGradInput
```
although the symbol seems defined in `libTHCUNN.so.1`.

**Comment by soumith** [comment]
i think i know this.

```
pip uninstall torch
pip uninstall torch
python setup.py clean
python setup.py build develop
```

**Comment by lantiga** [comment]
Thank you @soumith, this solved it. I still have to fix a few failing Cuda tests and we're ready to go.

**Comment by lantiga** [comment]
Good, I just fixed the remaining tests and filed a PR.

**Comment by soumith** [comment]
fixed via #2846

**Comment by lincolnBush** [comment]
Hi, 

It seems that the current version does not support it.

**Comment by fmassa** [comment]
@lincolnBush it is present in master. You need to compile it from source to get it.
