### ISSUE TITLE
Trigamma is not callable or documented

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27230]
## 🐛 Bug

PyTorch has a trigamma kernel (see https://github.com/pytorch/pytorch/search?q=trigamma&unscoped_q=trigamma) with some dispatch logic, but it's not callable and it's not documented.

Seems like we should either make it callable or delete it.

**Comment by zou3519** [comment]
It is intentional that it isn't callable or documented. Polygamma calls it: https://github.com/pytorch/pytorch/blob/082f195ac9ec7e2ee9b1d25329b357cb2cedd6f3/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp#L175-L181; we have no `trigamma` function.

**Comment by mruberry** [comment]
Sounds good. I'll remove the test for it.
