### ISSUE TITLE
nn.Linear() output is NaN for large matrix multiplication?

### ISSUE THREAD

**Issue by hojaeklee** [pytorch/pytorch#27240]
## 🐛 Bug

I have a simple 2-layer NN (fc-relu-fc) that takes a large number of features (30,754). It throws a value error `ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`, and upon inspection, I noticed that the matrix multiplication by the first layer results in all `nan`. 

## To Reproduce

```
import torch
import torch.nn

x = torch.randn(128, 30754)
fc1 = nn.Linear(30754, 512)
y = fc1(x)

"""
OUTPUT:
y is a tensor of shape (128, 512) that is filled with nan:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<AddmmBackward>)
"""

fc2 = nn.Linear(30754, 1)
z = fc2(x) # z is a (128, 1) real-valued vector
```

The model can run if I change the batch size from 128 to 1. When I set the batch size to 4, the model can run a single iteration/batch, but the gradient explodes afterwards. 

The real data is scaled and normalized to have approximately zero-mean and unit variance, and ranges from approximately -2 to 10. 

## Environment
```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.6.1810 (Core) 
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.14.3
[pip] numpydoc==0.8.0
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0
```

**Comment by andreaskoepf** [comment]
I could not directly reproduce the `nan` effect. I tried with PyTorch 1.2 and a current 1.3 build, both cpu & gpu.


```
import torch
import torch.nn as nn
x = torch.randn(128, 30754)
fc1 = nn.Linear(30754, 512)
y = fc1(x)
```

```
import torch
import torch.nn as nn
x = torch.randn(128, 30754, device='cuda')
fc1 = nn.Linear(30754, 512).cuda()
y = fc1(x)
```

**Comment by hojaeklee** [comment]
Although I could not figure out what the issue was (I tried a smaller multiplication of matrices and got results that had very large values), I did resolve my problem when I switched the environment in my school's high performance computer. I'm sorry this does not shed any more light on the problem itself.

Please feel free to close this issue.

**Comment by hojaeklee** [comment]
Hi @smandava98 , sorry I do not remember which pytorch.numpy versions resolved the issue. Nowadays I use PyTorch version >2 and haven't ran into this problem since.
