### ISSUE TITLE
random_ and uniform_ in Random sampling section of documentation

### ISSUE THREAD

**Issue by aszlam** [pytorch/pytorch#2725]
These are documented in the torch.Tensor section 

http://pytorch.org/docs/master/tensors.html

but it would probably be good to have a pointer in the Random Sampling section of the documentation 

http://pytorch.org/docs/master/torch.html#random-sampling

**Comment by soumith** [comment]
fixed via http://pytorch.org/docs/master/torch.html#in-place-random-sampling
