### ISSUE TITLE
EMNIST Dataset URL Problem

### ISSUE THREAD

**Issue by mhgh2hadi** [pytorch/pytorch#27264]
## 🐛 Bug

It seems that the EMNIST dataset url from which the torchvision downloads the data has a problem. Could you please fix it?

## To Reproduce

import torchvision.datasets as dtset
dtset.EMNIST(root='./emnist/', train=True, split='byclass', download=True)

## Expected behavior

0it [00:00, ?it/s]Downloading and extracting zip archive
Downloading https://cloudstor.aarnet.edu.au/plus/index.php/s/54h3OuGJhFLwAlQ/download to ./emnist/EMNIST/raw/emnist.zip

0it [00:00, ?it/s]Failed download. Trying https -> http instead. Downloading http://cloudstor.aarnet.edu.au/plus/index.php/s/54h3OuGJhFLwAlQ/download to ./emnist/EMNIST/raw/emnist.zip
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/utils.py in download_url(url, root, filename, md5)
     83                 url, fpath,
---> 84                 reporthook=gen_bar_updater()
     85             )

24 frames
HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

HTTPError                                 Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 503: Service Unavailable

**Comment by SsnL** [comment]
discussed and addressed in https://github.com/pytorch/vision/issues/1296
