### ISSUE TITLE
CI builds sometimes hang in or just after running test_dataloader

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27278]
## 🐛 Bug

In the last 115 runs on Master, py2-clang7-rocmdeb-ubuntu16.04-test2 failed 5 times with a timeout during or just after test_dataloader. This is a failure rate of 4.3%. All failures of this build on Master are due to this issue. 

Since critical test suites like test_torch are run after test_dataloader, this suggests ~1/23 PRs need to retest to validate they work properly with ROCm. Put another way, if each of 70 CI builds had the same failure rate then a PR would have less than a 5% chance to see a green CI.

cc @ezyang @gchanan @zou3519 @SsnL

**Comment by mruberry** [comment]
cc @gottbrath 

I recommend disabling test_dataloader on ROCm until this issue is resolved.

**Comment by mruberry** [comment]
Not a ROCm specific issue!

See https://circleci.com/gh/pytorch/pytorch/3062034?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, which hit the same issue on pytorch_namedtensor_linux_xenial_cuda9_cudnn7_py2_test

The extent of this issue requires further review.

**Comment by mruberry** [comment]
Removing "triaged" label per discussion @gottbrath. The issue appears to be in PyTorch, not ROCm, increasing its severity.

**Comment by pietern** [comment]
@mruberry Do you know which exact test this is? The test output is line-buffered, so we only get to see the previous test in the log output...

**Comment by mruberry** [comment]
It does not happen consistently at any point. In fact, many of the hangs happen after test_dataloader runs and reports success. This suggests it's a hang on dataloader shutdown.

**Comment by SsnL** [comment]
For a quick “fix”, I will accept a PR that adds a reasonable timeout for
test_dataloader in run_test.py.

**Comment by SsnL** [comment]
Hmm if run_test.py kills the subprocess after 30min, it won’t hang the
entire build, right?

**Comment by mruberry** [comment]
What subprocess?

**Comment by SsnL** [comment]
The test suite entry point run_test.py sequentially run each test file (eg
test_dataloader.py) in subprocesses and wait for them.

Adding a timeout won’t mark the build as successful, but at least will
unblock tests afterwards and won’t occupy resource indefinitely.

**Comment by mruberry** [comment]
Oh I see. Yes we could set a process-level timeout, or just set it for test_dataloader, in run_test.py. I'd prefer we just fix the underlying issue, however.

**Comment by SsnL** [comment]
We should definitely fix the underlying issue. It is a pretty hard issue
too. At least last time I looked into it for days and I couldn’t figure out
why.

**Comment by gchanan** [comment]
@SsnL thoughts on turning off the test?

**Comment by gchanan** [comment]
Or just running on master?

**Comment by gchanan** [comment]
We should at least do something, whether that is fixing, turning it off on PRs, or turning it off overall.

**Comment by SsnL** [comment]
@gchanan I think we should identify which test is causing the trouble and temporarily switch it off. Turing entire `test_dataloader.py` off seems an overkill.

**Comment by mruberry** [comment]
A more recent test_dataloader hang that might help diagnose:

https://circleci.com/gh/pytorch/pytorch/3194293?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by mruberry** [comment]
Also: 

https://circleci.com/gh/pytorch/pytorch/3193447?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

Which hung in test_dataloader (didn't error out).

**Comment by mruberry** [comment]
Another one:

https://circleci.com/gh/pytorch/pytorch/3191123?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

Could this be a Python2 issue? If so it will fix itself soon.

**Comment by mruberry** [comment]
Maybe not, here's a Python3 test_dataloader error:

https://circleci.com/gh/pytorch/pytorch/3179983?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

**Comment by zou3519** [comment]
From @mruberry's logs, it looks like the following tests have issues:

Flaky:
test_multi_drop
test_random_seed
test_proper_exit

Hangs and causes the entire test to time-out:
test_iterable_style_dataset

**Comment by mruberry** [comment]
Another one: https://circleci.com/gh/pytorch/pytorch/3479695?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This occurs after test_invalid_ctor_args_combinations

**Comment by mruberry** [comment]
Still frequently happening (especially on py2):

https://circleci.com/gh/pytorch/pytorch/3492372?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mruberry** [comment]
New version of the issue: 

Nov 06 21:13:16 ======================================================================
Nov 06 21:13:16 FAIL: test_proper_exit (__main__.TestDataLoader)
Nov 06 21:13:16 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
Nov 06 21:13:16 ----------------------------------------------------------------------
Nov 06 21:13:16 Traceback (most recent call last):
Nov 06 21:13:16   File "/var/lib/jenkins/workspace/test/common_utils.py", line 224, in wrapper
Nov 06 21:13:16     fn(*args, **kwargs)
Nov 06 21:13:16   File "test_dataloader.py", line 1429, in test_proper_exit
Nov 06 21:13:16     fail(fail_reason + ', and had no exception')
Nov 06 21:13:16   File "test_dataloader.py", line 1418, in fail
Nov 06 21:13:16     self.fail(err_msg)
Nov 06 21:13:16 AssertionError: test_proper_exit with is_iterable_dataset=True, use_workers=True, pin_memory=False, hold_iter_reference=True, exit_method=None: loader process did not terminate, and had no exception
Nov 06 21:13:16 Loader info:
Nov 06 21:13:16 	{'status': 'sleeping', 'cpu_times': pcputimes(user=0.01, system=0.0, children_user=0.0, children_system=0.0), 'name': 'python', 'num_ctx_switches': pctxsw(voluntary=171, involuntary=2), 'pid': 28421, 'memory_full_info': pfullmem(rss=60891136, vms=839495680, shared=9629696, text=4096, lib=0, data=187211776, dirty=0, uss=2686976, pss=21700608, swap=0), 'io_counters': pio(read_count=150, write_count=93, read_bytes=0, write_bytes=0, read_chars=7502, write_chars=2007), 'threads': [pthread(id=28421, user_time=0.0, system_time=0.0), pthread(id=28424, user_time=0.0, system_time=0.0), pthread(id=28425, user_time=0.0, system_time=0.0)], 'ionice': pionice(ioclass=0, value=4), 'open_files': [], 'nice': 0}
Nov 06 21:13:16 Worker(s) info:
Nov 06 21:13:16 	Worker 0:
Nov 06 21:13:16 		{'status': 'zombie', 'cpu_times': pcputimes(user=0.0, system=0.01, children_user=0.0, children_system=0.0), 'name': 'python', 'num_ctx_switches': pctxsw(voluntary=53, involuntary=0), 'pid': 28422, 'memory_full_info': pfullmem(rss=0, vms=0, shared=0, text=0, lib=0, data=0, dirty=0, uss=0, pss=0, swap=0), 'io_counters': None, 'threads': [pthread(id=28422, user_time=0.0, system_time=0.0)], 'ionice': pionice(ioclass=0, value=4), 'open_files': None, 'nice': 0}
Nov 06 21:13:16 	Worker 1:
Nov 06 21:13:16 		{'status': 'sleeping', 'cpu_times': pcputimes(user=0.0, system=0.0, children_user=0.0, children_system=0.0), 'name': 'python', 'num_ctx_switches': pctxsw(voluntary=34, involuntary=1), 'pid': 28423, 'memory_full_info': pfullmem(rss=64311296, vms=839753728, shared=12824576, text=4096, lib=0, data=187473920, dirty=0, uss=3792896, pss=23459840, swap=0), 'io_counters': pio(read_count=118, write_count=40, read_bytes=0, write_bytes=4096, read_chars=96360, write_chars=2382), 'threads': [pthread(id=28423, user_time=0.0, system_time=0.0), pthread(id=28427, user_time=0.0, system_time=0.0), pthread(id=28429, user_time=0.0, system_time=0.0)], 'ionice': pionice(ioclass=0, value=4), 'open_files': [], 'nice': 0}
Nov 06 21:13:16 
Nov 06 21:13:16 ----------------------------------------------------------------------
Nov 06 21:13:16 Ran 61 tests in 83.459s
Nov 06 21:13:16 
Nov 06 21:13:16 FAILED (failures=1, skipped=7)
Nov 06 21:13:16 Traceback (most recent call last):
Nov 06 21:13:16   File "test/run_test.py", line 454, in <module>
Nov 06 21:13:16     main()
Nov 06 21:13:16   File "test/run_test.py", line 446, in main
Nov 06 21:13:16     raise RuntimeError(message)
Nov 06 21:13:16 RuntimeError: test_dataloader failed!
Nov 06 21:13:16 + cleanup
Nov 06 21:13:16 + retcode=1
Nov 06 21:13:16 + set +x
Nov 06 21:13:16 =================== sccache compilation log ===================
Nov 06 21:13:16 ERROR:sccache::server: Compilation failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "/tmp/torch_extensions/test_compilation_error_formatting/main.cpp: In function \'int main()\':\n/tmp/torch_extensions/test_compilation_error_formatting/main.cpp:2:23: error: expected \';\' before \'}\' token\n int main() { return 0 }\n                       ^\n" }
Nov 06 21:13:16 

see https://circleci.com/gh/pytorch/pytorch/3499290?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pietern** [comment]
Another example: https://circleci.com/gh/pytorch/pytorch/3526421

```
Nov 08 08:04:41 test_invalid_assign_after_init (__main__.TestDataLoader) ... ok
Nov 08 08:04:41 test_invalid_ctor_args_combinations (__main__.TestDataLoader) ... ok
Too long with no output (exceeded 1h30m0s)
```

**Comment by pietern** [comment]
Another example of a hang: https://circleci.com/gh/pytorch/pytorch/3669403

**Comment by mruberry** [comment]
Closing this as it no longer appears to be happening.
