### ISSUE TITLE
I want install the pytorch from source, but encountered a compile error. Can anyone help me?

### ISSUE THREAD

**Issue by cdzhan** [pytorch/pytorch#27281]
### My steps of installation:
1. export USE_CUDA=0
2. sudo conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing
3. sudo git clone --recursive https://github.com/pytorch/pytorch
4. cd pytorch
5. sudo pip install -r requirements.txt
6. sudo git submodule sync
7. sudo git submodule update --init --recursive
8. export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
9. sudo python setup.py install
### The output of compilation:
[pytorch_compile_error.txt](https://github.com/pytorch/pytorch/files/3685435/pytorch_compile_error.txt)

### Environment
`Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.4

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0`
### The Segmentation fault not always happened in the same place.
[pytorch_compile_error2.txt](https://github.com/pytorch/pytorch/files/3686399/pytorch_compile_error2.txt)

**Comment by andreaskoepf** [comment]
The segfault "not always happened in the same place" is suspect. Just an idea: Could you check you RAM with memtest86+?

**Comment by cdzhan** [comment]
> The segfault "not always happened in the same place" is suspect. Just an idea: Could you check your RAM with memtest86+?

@andreaskoepf Maybe it is more likely the limitation of the stack size？
`ulimit -a`
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7823
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
**stack size              (kbytes, -s) 8192**
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7823
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
