### ISSUE TITLE
after i have successfully installed pytorch , it seems i can only execute  *.py script  in the pytorch-master  dir

### ISSUE THREAD

**Issue by visonpon** [pytorch/pytorch#2729]
after i have successfully installed pytorch , it seems i can only execute  *.py script  in the pytroch-master  directory, anyone know why?
 eg, if i create a folder in the pytorch-master ,and cd to this subfolder  to execute script , it always report error, but when i copy this script to the pytorch-master, everything is ok.

**Comment by visonpon** [comment]
For example , when i  execute script:
`print(models.densenet121)`
 in the pytorch-master(eg: */pytorch-master) , it will output layer name normally.
but if i execute this script in a subfolder of pytorch-master(eg: */pytorch/densenet/) ,i got  error like this:
```
models.densenet121
AttributeError:creator
```

**Comment by soumith** [comment]
i dont know what you are doing, i dont think you're having a good understanding of python imports. please give the exact script that you're running and the full error you see.

**Comment by visonpon** [comment]
```
import torchvision.models as models
model =model1.densenet121()
print(model)
```
i dont think the scripts have some error,since i just change its folder and encounter the problem. if all the *.py scripts have to be placed in the pytorch-master , it's not convenient.
thanks for your  reply~

**Comment by soumith** [comment]
and what's the FULL error?

**Comment by alykhantejani** [comment]
@visonpon did you run `python setup.py install` as it sounds like your `PYTHONPATH` isn't set correctly

**Comment by nishnik** [comment]
@visonpon I think you should add your pytorch directory to `PYTHONPATH`, adding this to `~/.bashrc` should work:

`export PYTHONPATH="${PYTHONPATH}:/pytorchpath"`

**Comment by visonpon** [comment]
@alykhantejani @nishnik, i have add my pytorchpath(home/*/pytorch-master) to ~/.bashrc and /etc/profile, but i also encounter the same error.
 @soumith ,the full error is like this:
```
Traceback (most recent call last):
  File "/home/*/pytorch-master/densenet_hourglass/inter_loss.py", line 7, in <module>
    model = models.densenet121()
  File "build/bdist.linux-x86_64/egg/torchvision/models/densenet.py", line 25, in densenet121
  File "build/bdist.linux-x86_64/egg/torchvision/models/densenet.py", line 128, in __init__
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 233, in __init__
    False, _pair(0), groups, bias)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 32, in __init__
    out_channels, in_channels // groups, *kernel_size))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 252, in __setattr__
    self.register_parameter(name, value)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 95, in register_parameter
    elif param.creator:
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 63, in __getattr__
    raise AttributeError(name)
AttributeError: creator
```
thanks~

**Comment by soumith** [comment]
you need to first move your `densenet_hourglass` folder and  your files away from the `pytorch-master` folder, just put them somewhere else. The `pytorch-master` folder has a folder called `torch` which is conflicting with the `torch` installed on your system.
