### ISSUE TITLE
_pointwise_loss appears to be dead code

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#27311]
[_pointwise_loss](https://github.com/pytorch/pytorch/blob/d396c7332a852c55f00062b20f49d21b8a1a6d77/torch/nn/functional.py#L2117) appears [to be dead code](https://github.com/pytorch/pytorch/search?q=_pointwise_loss&unscoped_q=_pointwise_loss).

**Comment by jerryzh168** [comment]
cc @SsnL do you know if we can remove this?

**Comment by SsnL** [comment]
sure

**Comment by mruberry** [comment]
This appears to have been removed.
