### ISSUE TITLE
from torch._C import * ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Fzz123** [pytorch/pytorch#2731]
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
>>> import numpy
>>> numpy.__version__
'1.11.3'
>>> numpy.__path__
['/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/numpy']
>>> 
(py35) user@user-ASUS:~/anaconda2/envs/py35/lib/python3.5/site-packages/torch$ pip install numpy --upgrade
Requirement already up-to-date: numpy in /home/user/anaconda2/envs/py35/lib/python3.5/site-packages
(py35) user@user-ASUS:~/anaconda2/envs/py35/lib/python3.5/site-packages/torch$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
>>> import numpy
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ValueError: module functions cannot set METH_CLASS or METH_STATIC

So how can I fix this error? I'm looking forward to your answer!  I am deeply grateful for your help.

**Comment by Fzz123** [comment]
pip install numpy -I 
has worked for me, I'll close the issue. But I don't know why does pip install numpy --upgrade not work.
(py35) user@user-ASUS:~$ pip install numpy -I  
Collecting numpy
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.13.1
(py35) user@user-ASUS:~$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>

**Comment by yinyu-newbie** [comment]
Thank you! @Fzz123 . You solution also worked on me.
I met the error on macOS 10.12.6, Anaconda python 3.6.1

**Comment by youkaichao** [comment]
this also works on me. I met the error on Ubuntu 14.04.5 LTS, Anaconda python 3.5.2

**Comment by bragilee** [comment]
Thank you! @Fzz123 
This world for me. It occurred on my macOS with pip package.

**Comment by taineleau** [comment]
This also works for me!! Thanks!!

**Comment by bfarzin** [comment]
For me, also worked.  Ubuntu 14.04.1  python 2.7, pip install

**Comment by lxtGH** [comment]
Thanks you ! It works for me for the macOS with pip

**Comment by fjcamillo** [comment]
Thank You! Also worked for me.

Working on
- `Ubuntu 16.04.03 LTS`
- `Anaconda Environment 3.6.3`
- with `numpy 1.13.3`

**Comment by Primus-zhao** [comment]
Thank You! Worked for me too!

    Ubuntu 16.04.03 LTS
    Normal pip install
    with numpy 1.13.3

**Comment by prisar** [comment]
thank you! It worked for me also🙂

**Comment by huanhuanxuxu** [comment]
haha worked for me 2

ubuntu 16.04 LTS
conda install
with numpy 1.13.3

**Comment by Highstars1** [comment]
I have updated my numpy version to 1.13.3 but this issue just showed up forever. And I've been stuck at this for an entire day... Any help will be appreciated! 

Mac 10.13.1
pip3 install 
with numpy 1.13.3

**Comment by youkaichao** [comment]
maybe you can try reinstall numpy

2017-12-04 19:44 GMT+08:00 Highstars1 <notifications@github.com>:

**Comment by mizadyya** [comment]
If you had problems with upgrading numpy, please see [here](https://mail.scipy.org/pipermail/numpy-discussion/2012-August/063608.html).

**Comment by brando90** [comment]
I also ran into this problem. Could it have been caused by installing keras tensorflow and pytorch all in the same env?

**Comment by QuenceyTang** [comment]
what about windows?

**Comment by SizeLee** [comment]
It also work for me, but what does parameter "-I" means? Anyone can tell me?

**Comment by greed2411** [comment]
@Fzz123 you just saved my life.

**Comment by uuvv** [comment]
Thank you! @Fzz123
This works for me. But why it works? Anyone can explain that?

**Comment by tomatopuree** [comment]
```
      4 import dlib
----> 5 import torch
      6 import torch.nn as nn
      7 from enum import Enum

~/.local/lib/python3.6/site-packages/torch/__init__.py in <module>()
     78     pass
     79 
---> 80 from torch._C import *
     81 
     82 __all__ += [name for name in dir(_C)

ValueError: module functions cannot set METH_CLASS or METH_STATIC
```

As can be observed, I have the same error, although I've ran:

`pip install numpy -I`

numpy seems to be at 1.15.1 now. I'm also running python 3.6.5.

The fix that led to the closing of this issue does not seem to fix this problem as of this moment, can we reopen this issue?

**Comment by piemart** [comment]
I am experiencing the same issue with python 3.7 and numpy 1.15.1.
 
`C:\Users\pierr>python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pierr\AppData\Roaming\Python\Python37-64\lib\site-packages\torch\__init__.py", line 80, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import`

`pip install numpy -I` doesn't do the trick. 
Should I use a different version of numpy with Torch?

**Comment by codemarsyu** [comment]
I met with this issue again with Python 3.6 and Numpy=1.16.1

**Comment by dumitrescustefan** [comment]
I have the same problem with Python 3.5 and Numpy 1.16.1

**Comment by gccome** [comment]
pip install -U numpy
this works for me

**Comment by dumitrescustefan** [comment]
I was actually able to solve this by running _sudo pip uninstall numpy_ as well as _pip uninstall numpy_ and then reinstalling with -U. 
Thing was that I had to run 3 times in a row the uninstall numpy to progressively remove older versions until there was no numpy left. Only then did I install and it worked. Thanks!

**Comment by dankal444** [comment]
Followed dumitrescustefan instruction, with small changes:
- `sudo pip uninstall numpy` did nothing, 
- I had to do `pip uninstall numpy` **twice**. After uninstalling once it turned out I have one more version of numpy. 
- then, as suggested, I did `pip install numpy -U` and pytorch imports without error

**Comment by Deeplearning20** [comment]
> I met with this issue again with Python 3.6 and Numpy=1.16.1

@codemarsyu   hello， can  you  sovle the  problem ? i have the error ‘ from torch._C import *
ImportError: numpy.core.multiarray failed to import’,       with   Python 3.6 and Numpy=1.16.1

**Comment by MingChaoXu** [comment]
> Followed dumitrescustefan instruction, with small changes:
> 
> * `sudo pip uninstall numpy` did nothing,
> * I had to do `pip uninstall numpy` **twice**. After uninstalling once it turned out I have one more version of numpy.
> * then, as suggested, I did `pip install numpy -U` and pytorch imports without error

i find this problem too, but i uninstall several times, i think it's because i install too many versions of numpy

**Comment by Zhang-haotian** [comment]
> I was actually able to solve this by running _sudo pip uninstall numpy_ as well as _pip uninstall numpy_ and then reinstalling with -U.
> Thing was that I had to run 3 times in a row the uninstall numpy to progressively remove older versions until there was no numpy left. Only then did I install and it worked. Thanks!

Thanks for you suggestion! I use python 3.6 cudatoolkit 9.0 pytorch 1.0

**Comment by JacobAtExp4531** [comment]
for me this was because multiple numpy versions where installed in the same enviornment so uninstalling them all and reinstalling numpy solved my problem

**Comment by zjwzcn07** [comment]
Repeat the following actions n times
**pip uninstall numpy**
then
pip install numpy -I

**Comment by jiachangliu** [comment]
Here is the procedure which gave me the problem:
1. Create a virtual environment using conda.
2. Install pytorch via conda.

Here is the twist to procedure I did to fix the problem:
1. Create a virtual environment using conda.
2. Install numpy via conda.
3. Install pytorch via conda.

I suppose I have to first install numpy. Otherwise there will be some problem.

**Comment by taral1313** [comment]
Thanks, I tried uninstalling and installing anaconda, cuda, pytorch 2, 3 times and finally these small solution solved my problem.

**Comment by cippo1987** [comment]
Still have the issues after removing and reinstall numpy.
I still do not get how people like python.Anyway:
```bash
$ conda info

     active environment : pytorch
    active env location : /home/user/.pyenv/versions/anaconda3-2020.07/envs/pytorch
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : 
          conda version : 4.9.0
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/user/.pyenv/versions/anaconda3-2020.07  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/.pyenv/versions/anaconda3-2020.07/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/.pyenv/versions/anaconda3-2020.07/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.3 Linux/5.4.0-7642-generic pop/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by yuanmingchen** [comment]
> Repeat the following actions n times
> **pip uninstall numpy**
> then
> pip install numpy -I

谢谢，我的也是多次卸载才行，居然同时安装了多个版本

**Comment by matt3o** [comment]
For everyone debugging this error: It might also be due to using wrongly named files. I created a file called `random.py` which has led to this error. For more information see this link: https://stackoverflow.com/q/65698402/3771575
When unsure try to `import numpy.core.multiarray`  and look into the output of the error which then pops up.

**Comment by huanglianghua** [comment]
FYI, I created a file named ``copy.py``.
After renaming the file, the problem was gone.

As @matt3o said, creating a file called ``random.py`` also causes the problem.

**Comment by KoapT** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，会在阅读之后尽快给您回复。
