### ISSUE TITLE
Need to add image for the quantization formula to the quantization doc

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27317]
![image-from-design-doc](https://user-images.githubusercontent.com/45861273/66162193-ba270600-e5e2-11e9-835f-354f5aac7934.png)

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jlin27** [comment]
Is there an image that's ready to add?

**Comment by gottbrath** [comment]
yes. 

https://raw.githubusercontent.com/wiki/pytorch/pytorch/images/math-quantizer-equation.png

i can see that link in safari but not chrome for some reason. Let me know if you have trouble accessing it. 

I got it from 

https://github.com/pytorch/pytorch/wiki/torch_quantization_design_proposal

**Comment by gottbrath** [comment]
![math-quantizer-equation](https://user-images.githubusercontent.com/45861273/66473059-6170c680-ea43-11e9-8844-c11dc0f0a8bf.png)

**Comment by gottbrath** [comment]
I am working on this. I think I see how to add the image.

**Comment by gottbrath** [comment]
yes .. working!

**Comment by gottbrath** [comment]
<img width="815" alt="fix-for-forumula" src="https://user-images.githubusercontent.com/45861273/66475751-ced32600-ea48-11e9-9c8c-3033a176f07e.png">

**Comment by gottbrath** [comment]
https://github.com/pytorch/pytorch/commit/b800134b332e1716dcd35ca9c9ef3615939d15d0
