### ISSUE TITLE
test_qconv is segfaulting on macos

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#27326]
```
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 1x1 kernel and 2x1 subsampling: width subsampling is greater than kernel width; subsampling should be performed before the convolution
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1x2 subsampling: height subsampling is greater than kernel height; subsampling should be performed before the convolution
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 2+2 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 2+2 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1x2 subsampling: height subsampling is greater than kernel height; subsampling should be performed before the convolution
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 2+2 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 2+2 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1+1 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1+1 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1+1 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 6x1 kernel and 1+1 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 1x1 kernel and 1+1 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 1x1 kernel and 1+1 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 1x1 kernel and 1+1 height padding: input top padding is greater or equal to kernel height
Oct 03 12:26:00 Note (QNNPACK): inefficiency in convolution with 1x1 kernel and 1+1 height padding: input bottom padding is greater or equal to kernel height
Oct 03 12:26:00 Traceback (most recent call last):
Oct 03 12:26:00   File "test/run_test.py", line 458, in <module>
Oct 03 12:26:00     main()
Oct 03 12:26:00   File "test/run_test.py", line 450, in main
Oct 03 12:26:00     raise RuntimeError(message)
Oct 03 12:26:00 RuntimeError: test_quantized failed! Received signal: SIGSEGV
```

https://app.circleci.com/jobs/github/pytorch/pytorch/3055211

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
@supriyar can you take a look

**Comment by supriyar** [comment]
I'm unable to repro this locally - the test passes. Looking at https://ezyang.github.io/pytorch-ci-hud/build/pytorch-master, I don't see any failures in pytorch_macos_10_13_py3_test as well. 
Latest log shows test_qconv passing https://circleci.com/gh/pytorch/pytorch/3090581?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

@ezyang anything I'm missing here?

**Comment by ezyang** [comment]
In person, we decided to not look into this unless it happened again

**Comment by raghuramank100** [comment]
Closing this issue as we are not looking at this.

**Comment by supriyar** [comment]
@ezyang do you have a log where it fails?
 cc @jianyuh

**Comment by ezyang** [comment]
Unfortunately I reran the job which destroyed the log. But the log is very uninformative; it's running qconv and then it segfaults. As a first step, can we make sure test_qconv is being run under ASAN? Can we also try running it under UBSAN?

**Comment by ezyang** [comment]
Occurrence: https://app.circleci.com/jobs/github/pytorch/pytorch/3421437

**Comment by mruberry** [comment]
This is continuing to happen: https://circleci.com/gh/pytorch/pytorch/3462992?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

avx2 or newer.'
Nov 04 16:31:14 test_avg_pool2d (__main__.TestQNNPackOps) ... ok
Nov 04 16:31:14 test_mean (__main__.TestQNNPackOps) ... ok
Nov 04 16:31:16 test_qnnpack_add (__main__.TestQNNPackOps) ... ok
Nov 04 16:31:17 test_qnnpack_maxpool2d (__main__.TestQNNPackOps) ... ok
Nov 04 16:31:17 test_qnnpack_relu (__main__.TestQNNPackOps) ... ok
Nov 04 16:31:17 test_qconv (__main__.TestQuantizedConv) ... Traceback (most recent call last):
Nov 04 16:31:17   File "test/run_test.py", line 454, in <module>
Nov 04 16:31:17     main()
Nov 04 16:31:17   File "test/run_test.py", line 446, in main
Nov 04 16:31:17     raise RuntimeError(message)
Nov 04 16:31:17 RuntimeError: test_quantized failed! Received signal: SIGSEGV

Updating labels per new triage process.

**Comment by mruberry** [comment]
@raghuramank100, should we disable this test on MacOS until the flakiness is addressed?

**Comment by supriyar** [comment]
Filed #29176 to temporarily disable on MacOS

**Comment by pietern** [comment]
Another example: https://circleci.com/gh/pytorch/pytorch/3460008

**Comment by mruberry** [comment]
See also #29326, another Mac quantization failure.

**Comment by z-a-f** [comment]
I am disabling the tests locally, but still cannot repro. Can anyone confirm?

**Comment by supriyar** [comment]
Closing this since it is a known problem that MacOS High Sierra does not support quantized backends. We've disabled these tests on macos for now.
