### ISSUE TITLE
Tweak Java API before 1.3 release

### ISSUE THREAD

**Issue by dreiss** [pytorch/pytorch#27350]
## 🚀 Feature
Tweak Java API before 1.3 release

## Motivation
We can update this later, but it's easier to do it now.

## Module

https://dreiss.github.io/pytorch/android/pytorch_android/javadoc-out/org/pytorch/Module.html

## IValue

https://dreiss.github.io/pytorch/android/pytorch_android/javadoc-out/org/pytorch/IValue.html

### Proposed change: consolidate factory methods.

These are currently named by the types the construct: bool, float64, etc.  I propose consolidating these into:

- `IValue.from` for bool, double64, long64, string, tensor
- `IValue.listFrom` for boolList, doubleList, longList, tensorList
- `IValue.tupleFrom`
- `IValue.dictLongKeyFrom`
- `IValue.dictStringKeyFrom`
- `IValue.optionalNull`

Benefits:
- Fewer method names to remember.
- Feels more "torchy" to me.

Drawbacks:
- Unnecessary unverloading can cause confusion.
- Some method names get longer (like "tupleFrom").

Alternatives:
- Could keep "tupleFrom" named "tuple".  Same for distLongKeyFrom.
- optionalNull could be replaced by `IValue.from()`.
- `listFrom` could be replaced by more overloads of `from`, but I think it would be confusing, especially if we continued to allow varargs (`IValue.from(1, 2)` suddenly becomes a different type if you remove the second arg).
- Unfortunately, I don't think it is possible to unify dictLongKey and dictStringKey while keeping type safety.

### Proposed non-change: getters.

These are currently `getBool`, `getTensor`, etc.  The C++ API uses "toBool", "toTensor", etc.

Benefits:
- Getters are a very strong convention in Java.
- Kotlin allows these to be written as `myValue.tensor`, which is convenient.

Drawbacks:
- Divergence from C++ API.

## Tensor

https://dreiss.github.io/pytorch/android/pytorch_android/javadoc-out/org/pytorch/Tensor.html

### Proposed change: Consolidate factory methods.

These are `newFloat32Tensor(shape, data)`, `newInt64Tensor(shape, data)`.  I propose consolidating all of these *except* for uint into `Tensor.fromBlob(data, shape)`

Benefits:
- Matches C++ API.

Drawbacks:
- The current API matches numpy.ndarray, which puts shape before data.
- Unnecessary overloading can cause confusion.

Alternatives:
- Just leave it as-is?

### Proposed change: UInt8 factory method

Java doesn't have unsigned types, so we can't use overloading to distinguish int8 from uint8.  I propose creating `Tensor.fromBlobUnsigned` for uint8.

Benefits:
- Pretty simple.

Drawbacks:
- Doesn't match the C++ API, specifies the dtype as a last parameter.  (TBH, I think this is a minor deficiency in the C++ API, which could infer the dtype from the pointer type.)

Alternatives:
- Specify dtype as third argument?

### Proposed non-change: data accessors

These are `t.getDataAsFloatArray()`, etc.  They're verbose, but they all have to have distinct names because of the distinct return types.  In C++, this would be `t.data_ptr<float>()`, but that's not possible in Java.

I can't think of anything obviously better.  The "Array" in the name is because we might expose another format later (like java.nio.Buffer).

Alternatives:
- We could use overloading like `float[] f = t.dataPtr((float)0)`, which matches the C++ API more closely, but is just gross.

### Proposed change: dtypes

Let's make these these an enum instead of ints.

Benefits:
Better type safety.

Drawbacks:
Slightly larger code (though I think ProGuard and Redex can eliminate this).

### Proposed change: shape

This is currently a mutable array.  Let's change it to a method that returns a fresh copy.

Benefits:
Don't need to worry about people mutating it.

Drawbacks:
Slight runtime overhead.

**Comment by suo** [comment]
> Proposed change: consolidate factory methods.

I like! Seems closer to the existing API.

> Proposed non-change: getters.

I don't like :(. They're not really "getters" in the Java sense, right? Like, for a given IValue, you can only call one of those methods without erroring. When I see `getX` I assume it's basically a data field on a struct and I'm more or less directly retrieving it. `IValue::toX` is more "perform a checked cast of me to type X".

**Comment by gchanan** [comment]
>> These are newFloat32Tensor(shape, data), newInt64Tensor(shape, data). I propose consolidating all of these except for uint into Tensor.fromBlob(data, shape)

sounds good...is camel-case so ubiquitous in java that `from_blob` isn't kosher?  That's what the actual C++ API is, right?  Finally, I never actually understood why we don't just call these `tensor` instead of `torch.tensor`.

>>> Doesn't match the C++ API, specifies the dtype as a last parameter. (TBH, I think this is a minor deficiency in the C++ API, which could infer the dtype from the pointer type.)

I'm not sure what from_blob does, but at least in the python API (`torch.tensor`)if you pass a different dtype it will do the conversion for you into the correct dtype.  So you get dtype inference unless you explicitly ask not to.

>>> t.getDataAsFloatArray()

My only nit with this is that `data` meant "get the underlying Tensor wrapped by a Variable".  Thus the confusion in the C++ API about data-vs-data_ptr.  I'm not sure how to solve it here though, I agree the alternative is gross.

>>> Proposed change: shape

In C++ this is an (const?) ArrayRef.  Is something like that even possible in java?

**Comment by dreiss** [comment]
Yeah, camel case is universal in Java.  There are immutable Lists in Java (which involve more overhead), but arrays are always mutable.

**Comment by dreiss** [comment]
> I don't like :(. They're not really "getters" in the Java sense, right? Like, for a given IValue, you can only call one of those methods without erroring. When I see `getX` I assume it's basically a data field on a struct and I'm more or less directly retrieving it. `IValue::toX` is more "perform a checked cast of me to type X".

Hrm.  One issue with this is that `getString` would be renamed `toString`, which is the method that would be called to print an IValue, which is probably not what we want.  What would you prefer?  Change the others to `toTensor`, but make this one `toStringValue`?  `toStr`?  Something else?

**Comment by dreiss** [comment]
We did this.
