### ISSUE TITLE
Python tests use torch.Doubletensor as their default tensor type

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27355]
## 🐛 Bug

https://github.com/pytorch/pytorch/blob/f5df46ce397335c43cb15457e3828a1a66cbbfa9/test/common_utils.py#L45

This is the source of considerable confusion since PyTorch's default tensor type is FloatTensor. While making tests generic I have even seem some tests run, convert their inputs to double, and run again. See test_polygamma and test_digamma in #26762. These tests even noted they were testing float behavior explicitly! Worse, when I updated them to run in both float and double the float version of the test failed.

I propose we don't set the default tensor type in common_utils.py to avoid this confusion. This will almost certainly require fixing many tests that relied on this behavior, intentionally or otherwise. 

cc @ezyang

**Comment by SsnL** [comment]
note that for gradcheck double is basically required. maybe we can have some functionality that automatically handles it in our test code?

**Comment by mruberry** [comment]
Yep. Actually many tests require double precision and are relying on this setting today. However, other tests think they're running in float and are actually running in double. 

Eliminating this line should also eliminate the confusion, but the tests will need to be updated to continue working. If many tests require double precision then they'll need a clearer mechanism to get it.

**Comment by yaroslavvb** [comment]
Drive-by-comment -- `torch.set_default_tensor_type` is an enemy of tests. I've been bitten by this before where my tests would run in either float32 or float64 depending on the order of test execution. One idea is to have a function decorator which would change default tensor type in the function.

```
@with_default_dtype(torch.float64)
def mytest(...):
```

For this to work with multi-threading, default tensor type has to be a thread-local variable.

**Comment by mruberry** [comment]
There actually is an existing decorator, @default_tensor_type, defined in some test files (see https://github.com/pytorch/pytorch/blob/a3ef0251fb3dfd85e3f4c874fcf004188eb509fd/test/test_jit.py#L90), but it's better if you can use the @dtypes decorator (https://github.com/pytorch/pytorch/blob/a3ef0251fb3dfd85e3f4c874fcf004188eb509fd/test/common_device_type.py#L287). The latter instantiates a variant of your test for each dtype you list, in addition to giving you precise control over dtypes. It's also thread safe. 

@dtypes does require you write your test generically, however. A non-generic version of it may be interesting, too.

**Comment by mruberry** [comment]
#27444 addresses most of this issue.
