### ISSUE TITLE
[docs] save_for_backward docs missing

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#27365]
There are no docs for `ctx.save_for_backward`. No found links have docs for `save_for_backward` itself: https://pytorch.org/docs/master/search.html?q=save_for_backward&check_keywords=yes&area=default

It would be good if these new docs mentioned that it has no effect in no_grad mode and does not needlessly hold onto tensors: https://discuss.pytorch.org/t/save-for-backward-in-no-grad-mode/57316

Probably `saved_tensors` is not formally documented either.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by pietern** [comment]
Thanks for reporting.

Would you be interested in putting up a PR to fix this?

**Comment by vadimkantorov** [comment]
I'm not really an autograd mechanics expert, sorry :(

**Comment by ezyang** [comment]
Docs live at https://pytorch.org/docs/stable/notes/extending.html#extending-torch-autograd there do not appear to be any reference docs however

**Comment by albanD** [comment]
We are definitely a page where to show the docs for the methods we make available to `ctx.` (save_for_backward, mark_dirty and mark_non_differentiable) when creating a custom Function.
These docs are already written [here](https://github.com/pytorch/pytorch/blob/593bb145ceea548478f83fd820de44b95d375108/torch/autograd/function.py#L10-L59) and just need to be linked on some page and linked to from the extending torch autograd page @ezyang  linked.

**Comment by prasunanand** [comment]
Fix: https://github.com/pytorch/pytorch/pull/28643
