### ISSUE TITLE
[ONNX export] UpSample with scale_factor should map to UpSample op with scale 

### ISSUE THREAD

**Issue by bhushan23** [pytorch/pytorch#27376]
## 🚀 Feature
As of ONNX Operator version 9, UpSample gets map to either
  1. Output size is provided: Scale is computed by `output_size / input_size` and fed to ONNX op
  2. Scale is provided: `(get_shape(input) * scale) / input_size` is fed to ONNX op

Looks like, symbolic function for Upsample does not take Scale as input https://github.com/pytorch/pytorch/blob/50b3f9d815efceac58f41041dee4b355fb33b92c/torch/onnx/symbolic_opset9.py#L719 

Also, scale factor is being multiplied to input shape and it's added before UpSample symbolic function. 
## Motivation

Simplified ONNX graph when `scale_factor` is provided to UpSample

## Pitch
Optimal export would generate scale in both cases and avoid multiple op generation as done today. 
Proposed solution
`symbolic_function` for `UpSample` takes `scale_factor` as a parameter and creates Constant node with known scales

## Alternatives
``output_size` is constant due to known multiplier and shape of input and hence, `symbolic function` of `Upsample` remains unchanged but, since output is known, `scale` is inserted instead of expanded set of ops

## Additional context
Following PyTorch code snippet demonstrates two different ONNX Upsample generated due to use of `scale_factor` and `size`

```
import torch
import torch.nn as nn

class TestModel(nn.Module):
    def forward(self, x):
        return torch.nn.functional.interpolate(x, mode='nearest', scale_factor=2)

model = TestModel()
dummy_input = torch.randn(5,100,100)
torch.onnx.export(model, dummy_input, "pytorch_upsample_scale.onnx")


class TestModel2(nn.Module):
    def forward(self, x):
        return torch.nn.functional.interpolate(x, mode='nearest', size=200)

model = TestModel2()
torch.onnx.export(model, dummy_input, "pytorch_upsample_size.onnx")

```

Attaching ONNX graph and images for reference

<img width="390" alt="UpSample_Scale" src="https://user-images.githubusercontent.com/1794273/66227414-ff564100-e691-11e9-9e73-c40bad2cb32b.png">
<img width="390" alt="UpSample_Output_Size" src="https://user-images.githubusercontent.com/1794273/66227433-07ae7c00-e692-11e9-8f8d-180fc2a7cdcf.png">

Attaching zip with PyTorch source and generated ONNX model
[PyTorch_Source_And_Generated_ONNX.zip](https://github.com/pytorch/pytorch/files/3691641/PyTorch_Source_And_Generated_ONNX.zip)

**Comment by dashesy** [comment]
If the input shape is dynamic, the scale will not be constant. If the op accepts output size instead of scales, that would be also great.

**Comment by bhushan23** [comment]
@dashesy I am referring to case when `input shape` and `scale` both are known, at that point, we can indeed create UpSample with known `scale`

I think, we can do this for dynamic shape as well, ONNX UpSample Op version - 9 takes scale as a input and if we know scale we can definitely pass it by creating it as a const. Not to mention, we don't need to compute output size since input was also of dynamic shape

**Comment by cepera-ang** [comment]
I think that current behavior is a bug. The change introduced here https://github.com/pytorch/pytorch/pull/18875 causes inclusion of unnecessary ops into the onnx graph and **also** prevents export of upsampling to opset 7 and 8. 

In the PR above there is vague mention in comment about "not baking the constant" as motivation to return tensor without any discussion why it is important (at least I couldn't find one) and it is unclear to me how skipping this check and always returning scalar scales will work and affect everything. 

It needs more testing, however, preliminary checks show that without #18875 Upsample is exporting nice in test case above and also works with opset 7 and 8 and has no errors about aten::upsample_bilinear2d (like here https://github.com/pytorch/pytorch/issues/22906)

**Comment by mathmanu** [comment]
Please fix this. When we create Upsampling with a scale factor, we expect it to export onnx with that scale factor. 
If I instead call functional.interpolate() with size as tuple of ints, then the exported onnx graph has scale factor. 
How strange - when I provide scale factor, it exports a complicated graph - but when I call with size tuple of ints, scale factor is exported!

**Comment by JulienMaille** [comment]
Any update on that issue?

**Comment by tensorbuffer** [comment]
I am also stuck on this issue, I want the exported onnx graph to contain one simple upsample node, not the current gather/multiply/divide/concat nodes, which is too complicated.
I tried with a small graph, which only had one upsample node. If I pass in size then I got simple onnx upsample node. If I pass in scale factors then it's the complicated one.
However when I tried a complicated graph that's used for object segmentation, even if I pass in size as I did in the simple graph, I still got the complicated node structure in the onnx exported. Not sure why?
I think this issue topic says it all: UpSample with scale_factor should map to UpSample op with scale. I don't know why there's need for such a complicated node structure?

**Comment by tensorbuffer** [comment]
Ok I figured out. I can work around this problem by providing fixed sizes. I was having problem because there's another upsample op in another file that I missed...

**Comment by JulienMaille** [comment]
@tensorbuffer this kind of trick?
```python
if self.training:
    x = F.interpolate(x, scale_factor=2, mode="nearest")
else:
    # hack in order to generate a simpler onnx
    x = F.interpolate(x, size=[int(2 * x.shape[2]), int(2 * x.shape[3])], mode='nearest')
```

**Comment by XiaoLaoDi** [comment]
@JulienMaille @mathmanu Hi guys, how did you solve the problem ? Same problem need your help.

**Comment by mathmanu** [comment]
You can pass the argument recompute_scale_factor=False to interpolate() function

This was added in pytorch 1.5 - but I thought this was made default in pytorch 1.6 (am I wrong or are you using a version lower than 1.6?).

**Comment by XiaoLaoDi** [comment]
@mathmanu thanks very much. But after set the  recompute_scale_factor=False to interpolate() function the torch.nn.export() onnx model seems nothing changed.

**Comment by XiaoLaoDi** [comment]
![test1](https://user-images.githubusercontent.com/20012774/127107552-e7be7eac-71bd-4d7c-9b48-af4147366958.png)
![test2](https://user-images.githubusercontent.com/20012774/127107561-b9d10c3b-e392-4b8b-9297-0f9976996fec.png)
![test3](https://user-images.githubusercontent.com/20012774/127107569-3b39cd12-6af5-4555-8fb2-169580b0e70a.png)

**Comment by XiaoLaoDi** [comment]
@mathmanu optset_option=7 is Ok to me, thanks !

**Comment by JulienMaille** [comment]
In you pic `scales <4>` means the structure is a 1 dimension array of size 4, It does't mean the scalar value equals 4.

**Comment by XiaoLaoDi** [comment]
@JulienMaille Ok, thank you very much

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1563545>

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features. We are glad some workarounds were discussed in this issue :)

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by JulienMaille** [comment]
@thiagocrepaldi I gave it a quick try :
```bash
  File "D:\Dev\DLTrainingPython\venv\Lib\site-packages\torch\onnx\_internal\fx\dynamo_graph_extractor.py", line 213, in generate_fx
    graph_module, graph_guard = torch._dynamo.export(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\DLTrainingPython\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 1233, in inner
    check_if_dynamo_supported()
  File "D:\Dev\DLTrainingPython\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 702, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
```

Is the new `dynamo_export` supposed to work on Windows?
