### ISSUE TITLE
Make current observers scriptable

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#27380]
Right now graph mode need the observers to be scriptable, we might support non-scriptable observers in the future but that task does not have a very high priority, therefore we would like to make the current observers scriptable to unblock experimentations in graph mode.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by dzhulgakov** [comment]
what would it take to support non-scriptable observers? my understanding is that it's not much - we even had a working prototype with Nishant some time back. The benefit is that we'd do the right thing and allow more flexibility.

actually, I think we can just do the trick with @torch.jit.ignore wrapper and we're done:

```python
@torch.jit.ignore
def foo():
  # arbitrary stuff
  import pickle
  print(pickle.loads(pickle.dumps({'1'})))

def bar(x):
  foo()
  return x+1

m = torch.jit.script(bar)
print(m.code)
print(m.graph)
m(torch.rand(5))
```

```
def bar(x: Tensor) -> Tensor:
  _0 = ^foo()()
  return torch.add(x, 1, 1)

graph(%x.1 : Tensor):
  %3 : int = prim::Constant[value=1]() # <ipython-input-7-3acafe54539a>:9:12
  %1 : None = ^foo()() # <ipython-input-7-3acafe54539a>:8:3
  %5 : Tensor = aten::add(%x.1, %3, %3) # <ipython-input-7-3acafe54539a>:9:10
  return (%5)

{'1'}
tensor([1.3869, 1.5020, 1.1394, 1.8531, 1.1464])
```

**Comment by jerryzh168** [comment]
Not sure how hard it is to make non-scriptable observers work but I'll try

**Comment by jerryzh168** [comment]
do you mean use `torch.jit.ignore` to ignore the non-scriptable part of observer?

**Comment by raghuramank100** [comment]
I agree, we should support arbitrary code in observers and not require scripting. Have you verified if this approach works for histogram observers?

**Comment by jerryzh168** [comment]
It should work with recent changes to JIT, I'll try again soon

**Comment by jerryzh168** [comment]
To be precise, we are still trying to make the observer scriptable, it's just we achieve it by ignoring non-scriptable functions.

**Comment by supriyar** [comment]
@jerryzh168 is this still a valid issue? I think most observers are scriptable now and can be used in graph mode.

**Comment by jerryzh168** [comment]
This is resolved.
