### ISSUE TITLE
Use local static pointers instead of local static objects for model parallel singletons

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#27412]
We use a lot of singletons in model parallel code and they are initialized as follows:

```
Bar foo() {
 static Bar bar;
 return bar;
}
```

As per https://isocpp.org/wiki/faq/ctors#construct-on-first-use-v2, this is not safe and we should use static raw pointers instead.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
The current method with static objects automatically provides thread safety by the standard, at least for C++11 and above, so we may lose thread safety if we move to raw pointers. Also, if we do this will we need to make sure that the resources are freed at the end of the program?

**Comment by pietern** [comment]
@rohan-varma Isn't the problem here that the constructor might not finish before another thread uses the statically initialized object? If so, this implies some kind of locking for not only static initialization but also use. I couldn't find anything that suggests this in the standard link that @pritamdamania87 included.

An alternative here is the use of `call_once` of course.

**Comment by pritamdamania87** [comment]
The proposal was to do this instead:

```
Bar& foo() {
 static Bar* bar = new Bar();
 return *bar;
}
```

As per https://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables, we have this:
```
If multiple threads attempt to initialize the same static local variable concurrently, the initialization occurs exactly once (similar behavior can be obtained for arbitrary functions with std::call_once).
```

As per my understanding this should be thread-safe for static pointers as well. 

> Also, if we do this will we need to make sure that the resources are freed at the end of the program?

We don't need to do this since the OS will free the resources.

@pietern @rohan-varma I'd suggest reading https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use (sorry should've linked this earlier) and then https://isocpp.org/wiki/faq/ctors#construct-on-first-use-v2. The suggestion there is to use static raw pointers instead of static objects. The first link introduces the static initialization order problem and suggests using static pointers. The second link suggestions why we shouldn't use static local objects.
