### ISSUE TITLE
torch.js

### ISSUE THREAD

**Issue by bionicles** [pytorch/pytorch#27426]
## 🚀 Feature
javascript API to train and deploy models

## Motivation

AI for react / react native / web apps / node APIs

## Pitch

Just imagine you could make interactive AI instead of toy / research experiments

## Alternatives

Tensorflow. You could train your own model and try to deploy it with onnx or something...but then you can’t train it in the browser, so you’d better make a good guess about how that model should work, and you’d better have the money to pay for compute. 

## Additional context

Leverage external resources: let users train the website AI, while they’re running it.

Also: async

**Comment by pietern** [comment]
I'm not aware of any plans to do this.

**Comment by gchanan** [comment]
We don't have any current plans to do this.

**Comment by soumith** [comment]
i'll close the issue until we actually have plans to do it

**Comment by Ierezell** [comment]
Any news about some node bindings (from libtorch) or anyway to integrate it with web stuff ?
