### ISSUE TITLE
formatting issue towards the end of the workflow section

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27432]
<img width="1475" alt="escape-character-end-of-workflows" src="https://user-images.githubusercontent.com/45861273/66262462-8fc97a00-e795-11e9-962d-48075ab8a07c.png">

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by gottbrath** [comment]
same thing occurs in the next section. 

<img width="777" alt="same-farther-down" src="https://user-images.githubusercontent.com/45861273/66262480-d919c980-e795-11e9-8a9a-3feafa3a3c0b.png">

**Comment by gottbrath** [comment]
I have a fix for this. 

<img width="919" alt="post-fix-image-A" src="https://user-images.githubusercontent.com/45861273/66273158-4d03b280-e826-11e9-852c-c3f4fcfb9943.png">

**Comment by jlin27** [comment]
@gottbrath - Just double-checking that you've got it fixed now? Looks good from the latest commits:
![image](https://user-images.githubusercontent.com/8042156/66335385-cadfc080-e8ef-11e9-8900-324582cb01cb.png)

**Comment by gottbrath** [comment]
yea .. fixed.
