### ISSUE TITLE
image_gradients: 'Tensor' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by SaraAlthubaiti** [pytorch/pytorch#27438]
Hi all,

While I'm trying to feed my tensor to `image_gradients`, this error arises:

`AttributeError: 'Tensor' object has no attribute 'get_shape'`

The reason is that within `image_gradients` implementation; they call `get_shape` in which it doesn't exist for a tensor!

The type of this tensor is: `torch.cuda.floattensor`

And its size: `torch.Size([2, 1, 128, 128])`

It seems that `image_gradients` function is for TensorFlow, so; is there any equivalent function in PyTorch that can do the same?

Any help will be much appreciated.

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
