### ISSUE TITLE
the reference to the quantization nn modules needs a little more description. 

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27430]
reviewing the draft quantization documentation. 

https://htmlpreview.github.io/?https://raw.githubusercontent.com/gottbrath/pytorch/temp-review-quant-doc/docs/review-doc/html/nn.html#quantized-functions

here is what this looks like now. I think it needs a little more textual context. 

<img width="1475" alt="torch nn-quantization-section-needs-text" src="https://user-images.githubusercontent.com/45861273/66262401-a66ed180-e793-11e9-9677-f87d70f2828f.png">

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jlin27** [comment]
Add some prose in this PR. Feel free to modify: https://github.com/gottbrath/pytorch/pull/10

**Comment by gottbrath** [comment]
looks great.

**Comment by z-a-f** [comment]
I'm removing the 1.3 tag.

Can we close this issue now? I don't see the PR that resolves this

**Comment by gottbrath** [comment]
Yea, looks good in the final doc! Closing.

**Comment by gottbrath** [comment]
The PR that fixed this specific issue was https://github.com/pytorch/pytorch/pull/27850
