### ISSUE TITLE
the list has inconsistent indentation. 

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27431]
<img width="1475" alt="formatting-in-operation-coverage" src="https://user-images.githubusercontent.com/45861273/66262438-ba670300-e794-11e9-9ff3-7f37800bc8ca.png">

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by jlin27** [comment]
Looks corrected now:
![image](https://user-images.githubusercontent.com/8042156/66335650-4f324380-e8f0-11e9-8e1b-326356d0d50e.png)

**Comment by gottbrath** [comment]
thanks yes looks good in the preview to me.

**Comment by gottbrath** [comment]
still looks good in the final doc. Closing.
