### ISSUE TITLE
README.md Grammar and Punctuation Fixes

### ISSUE THREAD

**Issue by xtrp** [pytorch/pytorch#27443]
## 📚 Documentation

Spotted quite a few grammar and punctuation issues while reading the main README.md file, would like to fix as my first contribution to Pytorch.

A few of these issues include:

 - L148: "They **requires** JetPack 4.2 and above and are maintained by @dusty-nv
"
- L127 "There is no wrapper code that needs to be written." — fix "No wrapper code needs to be written."

And more.

**Comment by iam-abbas** [comment]
May I work on this?

**Comment by pietern** [comment]
Thanks for reporting. If you spot more issue in the future, you can fork the PyTorch repository and easily edit the README file from the browser, and submit a pull request. Then we can merge that much more easily compared to reporting them in an issue and having someone submit a PR separately.
