### ISSUE TITLE
Can not update nn.ModuleDict/nn.ParameterDict with another same type dictionary.

### ISSUE THREAD

**Issue by wangwwno1** [pytorch/pytorch#27441]
## 🐛 Bug

Can not update a `ModuleDict` with another `ModuleDict`.
**Update: `ParameterDict` has similiar issue, fixed in the latest PR.**

## To Reproduce

1. Running the example code below:
```
import torch
from collections import OrderedDict
model_callbacks = torch.nn.ModuleDict(OrderedDict(
    lin_a=torch.nn.Linear(20, 5),
    lin_b=torch.nn.Linear(20, 10)
))
another_callbacks = torch.nn.ModuleDict()
another_callbacks.update(model_callbacks)
```
At the last line, a `Value Error` will raise:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "home/user/anaconda3/envs/py37-th120/lib/python3.7/site-packages/torch/nn/modules/container.py", line 331, in update
    "; 2 is required")
ValueError: ModuleDict update sequence element #0 has length 5; 2 is required

## Expected behavior

Update `ModuleDict` with `ModuleDict.items()` will work.
```
another_callbacks.update(model_callbacks.items())
another_callbacks
ModuleDict(
  (lin_a): Linear(in_features=20, out_features=5, bias=True)
  (lin_b): Linear(in_features=20, out_features=10, bias=True)
)
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.1 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] _pytorch_select           0.2                       gpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.0.14           py37ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py37hd6b4f25_0    defaults
[conda] pytorch                   1.2.0           cuda100py37h938c94c_0    defaults
[conda] torchvision               0.4.0           cuda100py37hecfc37a_0    defaults

## Additional context
Here are some code from the source of `torch\nn\modules\container.py` For some unknown reason, the condition `isinstance(modules, container_abcs.Mapping)` will alway be `False`.
Perhap a reshape into a "if……elif……else" structure would be better?
```
class ModuleDict(Module):
    def update(self, modules):
        # Some Code
        if isinstance(modules, container_abcs.Mapping): 
            # This condition will never be True if modules is nn.ModuleDict
            if isinstance(modules, (OrderedDict, ModuleDict)):
                for key, module in modules.items():
                    self[key] = module
            else:
                for key, module in sorted(modules.items()):
                    self[key] = module
        else:
            for j, m in enumerate(modules):
                if not isinstance(m, container_abcs.Iterable):
                    raise TypeError("ModuleDict update sequence element "
                                    "#" + str(j) + " should be Iterable; is" +
                                    type(m).__name__)
                if not len(m) == 2:  # Raise ValueError
                    raise ValueError("ModuleDict update sequence element "
                                     "#" + str(j) + " has length " + str(len(m)) +
                                     "; 2 is required")
                self[m[0]] = m[1]

        # Other Code
```

**Comment by pietern** [comment]
Thanks for reporting the issue. It looks like this should work out of the box indeed.

Would you be willing to submit a PR to fix this?

**Comment by wangwwno1** [comment]
> Thanks for reporting the issue. It looks like this should work out of the box indeed.
> 
> Would you be willing to submit a PR to fix this?

[Pull Request](https://github.com/pytorch/pytorch/pull/27541) submitted.

**Comment by wangwwno1** [comment]
Look like I wrongly changed the code in ParameterDict (not ModuleDict) because they have similiar structure.
Running the same test, find out that ParameterDict has similiar bug.
Both issue are fixed in this PR.

**Comment by wangwwno1** [comment]
Closed as this issue is resolved.
