### ISSUE TITLE
I installed pytorch 1.2.0 and torchtext 0.4.0 on my win10, but it is nothing in my notebook

### ISSUE THREAD

**Issue by deipss** [pytorch/pytorch#27447]
## ❓ Questions and Help
I used conda to install pytorch and torchtext,and the versions as follows after ran ``` conda list ```:
```
python                    3.6.4                h6538335_1    defaults
pytorch                   1.2.0               py3.6_cpu_1  [cpuonly]
torchtext                 0.4.0              pyhb384e40_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
```
meanwhile,I used 
```  from torch.nn.modules import TransformerEncoder, TransformerEncoderLayer  ```' to import them,   but it is not work in my pycharm, then I using global search to search them and it is nothing in here. 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by JamesTrick** [comment]
HI @deipss - to be sure have you have set your Project Interpreter correctly in PyCharm? Steps are [here](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html). Let me know if you continue to have issues, it doesn't yet sound like a bug with PyTorch.

**Comment by deipss** [comment]
> HI @deipss - This sounds like an environment error more than anything. To be sure have you have set your Project Interpreter correctly in PyCharm? Steps are [here](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html). Let me know if you continue to have issues.

I am sure that there are not any problem in PyCharm, and I can use PyCharm to run my codes in the courcse of nature. 
Actually what I mean is that I installed pytorch 1.2.0 but I cannot use Transformer of which, And now, I guess the true problem is my installed package or installed image.

**Comment by pietern** [comment]
This is a question for the forums and not an issue with PyTorch itself.

**Comment by deipss** [comment]
It is OK, I can user Transformer class and its subclass such as Transformer EncoderLayer.
