### ISSUE TITLE
formatting issue in dynamic quantization function

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27450]
<img width="798" alt="formatting-issue-either-or" src="https://user-images.githubusercontent.com/45861273/66273196-95bb6b80-e826-11e9-8cd8-8fcb2a2759dd.png">

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jlin27** [comment]
Can you elaborate on what needs to be done here?

**Comment by gottbrath** [comment]
See where it says "Either: * A dictionary ... " and then there is a big whitespace and then "* A set of types..." 

Looking at the source docstring I think the bullet point beginning "A dictionary..." and the bullet "A set of ..." are supposed to be two options that are parallel to one another. Can we get them to render the same? 

I am kinda guessing just adding a newline before A dictionary might do it. I'll try that but if that doesn't work then I might need more help.

**Comment by raghuramank100** [comment]
@gottbrath : Can we close this issue?

**Comment by gottbrath** [comment]
I am still planning on fixing this .. low priority though.

**Comment by gottbrath** [comment]
someone fixed this in the meantime.
