### ISSUE TITLE
Issues with ConvReLU2d  and LinearReLU doc issues

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27451]
<img width="794" alt="convrelu2d-nits" src="https://user-images.githubusercontent.com/45861273/66273545-b46f3180-e829-11e9-8204-8babdf30f1bd.png">

I have two concerns here;

#1 -- highlighted with two squares on the image -- it seems like when we say we use the same args as another function we should have a link to the documentation on the other function. 

#2 -- highlighted with ovals on the image -- in the docstring this is written as "same as ..." but in the doc it takes the first word and puts it in parenthesis after the rest.  Not sure why that is happening. 

If I am reading the gitjhub correctly @dskhudia  is the author of this bit of the code. Perhaps he can help. 

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by gottbrath** [comment]
@jlin27  can you help us with the linking issue (#1 above)?

@dskhudia can you focus on the "same as X" becoming "as X (same)" issue?

**Comment by dskhudia** [comment]
It looks like the following to me:

![Screen Shot 2019-10-07 at 1 24 51 PM](https://user-images.githubusercontent.com/37562707/66346038-20bf6300-e906-11e9-8d68-a3947be7e2a2.png)

**Comment by jlin27** [comment]
For #1 - need to add the :class: tag before the class name in the docs. Looks like it's missing in these places from branch v1.3.0 in the pytorch/pytorch repo:

- torch.nn.instrinsic.qat.modules
     - ConvBnReLU2d: https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/qat/modules/conv_fused.py#L186
- torch.nn.qat.modules
     - Conv2d:https://github.com/pytorch/pytorch/blob/master/torch/nn/qat/modules/conv.py#L14

**Comment by jlin27** [comment]
For #2 - I think it's because Sphinx is expecting one of it's standard docstring formats, so the original doc string will need to use either the :return: or :rtype: options to describe any values returned by the code:
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

@dskhudia - I think Chris had found that in torch.nn.instrinsic.**quantized**.modules  rather than the torch.nn.instrinsic.**qat**.modules

**Comment by gottbrath** [comment]
@daya .. I think we are looking at different parts of the doc. In your screenshot you show torch.nn.intrinsic.qat.modules.ConvReLU2d() where I am showing torch.nn.intrinsic.quantized.modules.LinearReLU() 

I see the same thing you do on the qat modules. I'm still seeing oddness on the quantized modules.

**Comment by gottbrath** [comment]
just realized that Jessica made this point 2 days ago. Do we have a fix for this?

**Comment by gottbrath** [comment]
ok.. I think I found a fix

It is a little hokey but I think it is worth doing if we can. I use the ..note:: to basically override the default behavior.

**Comment by raghuramank100** [comment]
@gottbrath : Can we close this issue?

**Comment by gottbrath** [comment]
I still see the "same as" issue here. 

<img width="1078" alt="Screen Shot 2019-10-22 at 3 18 23 PM" src="https://user-images.githubusercontent.com/45861273/67339052-41c7ac80-f4df-11e9-9dfd-579199ae41b4.png">


note that this is only on the nn.intrinsic version of these functions. About a page up there is a very similar function where it renders correctly.

**Comment by gottbrath** [comment]
ok .. this is strange. I can still see this error in the stable doc & the master doc on pytorch.org (master says 1.4.0a0+188d0a9) but on my local build this appears fixed.

**Comment by gottbrath** [comment]
![pt-i27451-master-vs-my-local](https://user-images.githubusercontent.com/45861273/69385207-73b16780-0c73-11ea-8955-d778edbe7464.png)


my local is on the left, master is on the right.

**Comment by gottbrath** [comment]
this was also happening with ConvReLU3d (see image above).

**Comment by gottbrath** [comment]
landed on master
