### ISSUE TITLE
How to extract middle layer features

### ISSUE THREAD

**Issue by tryerrorman** [pytorch/pytorch#2748]
We know in tensorflow, if we want to get the middle layer features, we use the command
``` python
sess.run(model[layer_name])
```
So I wonder if there similar command **to extract middle layer feature** in the pytorch?

For now, I get the middle layer through change the return of the net
```python
class NN()
    .......
    def forward(x)
        layer1 = conv(x)
        output = conv(layer1)
        ....
        output = fc(output)
        return layer1, output
```
But this way is not convenient if there a long list of layers features to output.

**Comment by soumith** [comment]
pytorch is built around programs, not graphs. copying/modifying a forward function and returning the particular layer you want is the right way to do things. If you want to return a middle layer more conveniently, write your model `forward` to take a `name` string as well, and return that `name` layer.

**Comment by JoseReyLopez** [comment]
but then the trained model weights can't be used, right?
