### ISSUE TITLE
Jacobian-vector equation in autograd_tutorial font size is too small

### ISSUE THREAD

**Issue by Paritoshyadav** [pytorch/pytorch#27482]
In tutorial https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html
under Gradients

![jac](https://user-images.githubusercontent.com/20665510/66342644-88f26100-e967-11e9-9e34-3811148d5ca4.PNG)

cc @ezyang

**Comment by ezyang** [comment]
Here's what it looks like for me:

![image](https://user-images.githubusercontent.com/13564/66406423-6f214000-e9a0-11e9-9084-e6b93cfebae2.png)

What is your browser?

**Comment by Paritoshyadav** [comment]
Chrome and firefox

**Comment by Paritoshyadav** [comment]
OK, I try this and this solves my problem:
I found out that PyTorch tutorials are using MathJax library for the equation
So, I change the setting of Mathjax 
Math render -> preview HTML instead of HTML-CSS
and it works out great

![equation](https://user-images.githubusercontent.com/20665510/66436487-cb3da000-ea44-11e9-911a-32b3e37e5145.PNG)

**Comment by ezyang** [comment]
OK, I'll close this then?
