### ISSUE TITLE
ONNX Padding Issue

### ISSUE THREAD

**Issue by colincsl** [pytorch/pytorch#2752]
It looks like there is an issue converting pyTorch models with Reflection (or Replication) padding. If you try using torch.onnx.export with ReflectionPad2d you get an error like the one below.

I think the issue is similar to https://github.com/pytorch/pytorch/pull/2742. In that case there was an issue because pooling parameters could be specified as scalars or tuples and thus they weren't being converted correctly. The same thing applies for padding. I'm not sure which file to look through to fix this. 

```
Error occured while handling:
%81 : Float(3, 32, 1026, 1), %82 : Handle = ^ReflectionPad2d(0, 0, 1, 1)(%79), uses = [[%83.i0], []];

Exported graph so far:
graph(%1 : Float(44, 128, 1, 1)
      %2 : Float(44)
      %3 : Float(128, 32, 3, 1)
      %4 : Float(128)
      %5 : Float(128, 32, 5, 1)
      %6 : Float(128)

....

      %79 : Float(3, 32, 1024, 1)) {
  return ();
}

Traceback (most recent call last):
  File "convert_to_caffe2.py", line 66, in <module>
    torch_out = torch.onnx.export(torch_model, x, "test.onnx", verbose=True)
  File "/home/clea/anaconda3/lib/python3.6/site-packages/torch/onnx.py", line 37, in export
    _export(model, args, f, export_params, kwargs, verbose)
  File "/home/clea/anaconda3/lib/python3.6/site-packages/torch/onnx.py", line 51, in _export
    proto = trace.export(list(model.state_dict().values()), verbose)
  File "/home/clea/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py", line 133, in symbolic
    return symbolic_fn(*args, **kwargs)
TypeError: 'NoneType' object is not callable

```

**Comment by colincsl** [comment]
fyi. Someone made the same issue on the Onnx github page. It is being looked into. 

https://github.com/onnx/onnx/issues/21

**Comment by houseroad** [comment]
https://github.com/pytorch/pytorch/pull/3048
https://github.com/pytorch/pytorch/pull/2962
The support is implemented. :-) We can close this issue now.

@ezyang @soumith
