### ISSUE TITLE
at::NoGradGuard no_grad

### ISSUE THREAD

**Issue by miaomi1994** [pytorch/pytorch#27526]
when I use at::NoGradGuard no_grad,it gets error like this:

![image](https://user-images.githubusercontent.com/29307135/66380183-7882ca80-e9e9-11e9-980e-7c78a3cdef41.png)
If I don't use it,the code works fine.I don't know the reason.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by pietern** [comment]
Please fill out the bug report template with version information, environment, etc.

**Comment by soumith** [comment]
please post the details we asked for and reopen issue
