### ISSUE TITLE
Raspberry Pi Zero W build fails

### ISSUE THREAD

**Issue by baqwas** [pytorch/pytorch#27539]
After installing the prerequisites (and setting the following environment variables):

```
export NO_CUDA=1
export NO_DISTRIBUTED=1
export NO_MKLDNN=1 
export NO_NNPACK=1
export NO_QNNPACK=1
```

I could not complete the build with the following command:

`make -VERBOSE=1`

The tail of the error messages is:

```
/home/pi/projects/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_4d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccPqf5ia.s: Assembler messages:
/tmp/ccPqf5ia.s:605: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/ccPqf5ia.s:855: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
...
/tmp/ccPqf5ia.s:2206: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/ccPqf5ia.s:2530: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
make[2]: *** [confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/build.make:76: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o] Error 1
make[2]: Leaving directory '/home/pi/projects/pytorch/build'
make[1]: *** [CMakeFiles/Makefile2:517: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/all] Error 2
make[1]: Leaving directory '/home/pi/projects/pytorch/build'
make: *** [Makefile:141: all] Error 2
pi@raspbari3:~/projects/pytorch/build $ 
```

The platform summary is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
$ uname -a
Linux raspbari3 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
$
```

I understand that trying to install **pytorch** on RPi0W detracts but I'm willing to be an able-bodied tester since I have quite a few Raspberry Pi Zero W boards where I need **pytorch** to work. The RPi0 boards have many other packages (for vision/image/ML) working and I was hoping to install **pytorch** too. Any help will be sincerely appreciated.

Kind regards.

**Comment by JVTEAM** [comment]
Also having a fail during compiling...

[ 12%] Building C object confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o
In file included from /home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/src/threadpool-pthreads.c:35:
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_1d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_2d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_3d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/pytorch_install/pytorch/build/confu-srcs/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]
  pthreadpool_function_4d_tiled_t function,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/cc3nCuOW.s: Assembler messages:
/tmp/cc3nCuOW.s:605: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:855: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:948: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1068: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1147: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1321: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1486: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1684: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:1924: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:2206: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
/tmp/cc3nCuOW.s:2530: Error: immediate expression requires a # prefix -- `orr r3,0x1000000'
make[2]: *** [confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/build.make:76: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/src/threadpool-pthreads.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:517: confu-deps/pthreadpool/CMakeFiles/pthreadpool.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/home/pi/pytorch_install/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/pytorch_install/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/pi/pytorch_install/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '1']' returned non-zero exit status 2.
pi@raspberrypi:~/

**Comment by pietern** [comment]
What is the most recent version where this worked?

It looks like the inline assembly in the threadpool isn't compatible with the compiler.

@ilia-cher Do you know anything about this?

**Comment by JVTEAM** [comment]
> What is the most recent version where this worked?
> 
> It looks like the inline assembly in the threadpool isn't compatible with the compiler.
> 
> @ilia-cher Do you know anything about this?

It was working with these instructions

https://medium.com/hardware-interfacing/how-to-install-pytorch-v4-0-on-raspberry-pi-3b-odroids-and-other-arm-based-devices-91d62f2933c7

and this fix...
https://github.com/pytorch/pytorch/issues/22564

Which is to run the command:
git submodule update --remote third_party/protobuf

**Comment by Maratyszcza** [comment]
Maratyszcza/pthreadpool@158098ac36d257bedd7d9c02d7276eb8b2077881 should fix it.

**Comment by baqwas** [comment]
After receiving the above replies, ran the following:

```
git submodule update --remote third_party/protobuf
python3 setup.py build
```

The tail end of the ensuing output is listed below:

```
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/zip_writer.cc.o
[  8%] Linking CXX static library ../../../lib/libprotoc.a
[  8%] Built target libprotoc
Scanning dependencies of target protoc
[  8%] Building CXX object third_party/protobuf/cmake/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o
[  9%] Linking CXX executable ../../../bin/protoc
/usr/bin/ld: ../../../lib/libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x24): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [third_party/protobuf/cmake/CMakeFiles/protoc.dir/build.make:87: bin/protoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: third_party/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/home/pi/projects/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/pi/projects/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/pi/projects/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '1']' returned non-zero exit status 2.
```

The issue has not gone away for me. Sorry, the messages are beyond my expertise. The compiler is gcc 8.3.0 (Raspbian 8.3.0-6+rpi1)

Thanks again for the guidance. Kind regards.

**Comment by pietern** [comment]
@baqwas This looks like the same issue as #22564 to me.

**Comment by gchanan** [comment]
going to close this as a duplicate; if you disagree, please reopen.
