### ISSUE TITLE
Build from source does not support cuda 9.0

### ISSUE THREAD

**Issue by rkaplan** [pytorch/pytorch#2755]
Building from source on Ubuntu 16.04 using the instructions in the README fails when cuda 9.0 is installed. I would assume it has to do with the magma-cuda package not being updated for 9.0. When can we expect 9.0 support?

**Comment by ngimel** [comment]
What is the error message you are getting? You can compile pytorch without magma support, but to avoid compilation errors you need to install nccl-dev package, so that pytorch does not try to compile its own nccl.

**Comment by rwightman** [comment]
I wasn't able to build for cuda 9 + cudnn 7 out of the box (c8f824cd)

Installing nccl-dev package from the latest nvidia nccl2 deb doesn't work.

The only way I got the build going was to grab the latest nccl1 (deprecated) from github that includes the cuda 9 half fix, and copy that overtop of the nccl folder in the pytorch source tree.

**Comment by ngimel** [comment]
Currently master is broken and does not allow using deb-installed nccl (see #2877 and #2853)

**Comment by soumith** [comment]
CUDA9 + source should work now. we have contbuilds for this and they're passing.

**Comment by vickylance** [comment]
@soumith Is there any instructions on how to build from source for CUDA 9.0 with cnDNN 7.0? If not can you tell how to do in a few steps? That would be useful.

**Comment by rkaplan** [comment]
@vickylance Here's a blog post with instructions: https://tspankaj.com/2017/08/12/cuda-9-and-cudnn-7-with-pytorch/

Not sure if the NCCL workaround mentioned in that post is still necessary.

**Comment by csarofeen** [comment]
That blog post is out of date. Installing pytorch from source with CUDA 9.0 and cuDNN 7.0 should just work. NCCL workaround is no longer necessary. 

To get NCCL2 you can follow the dockerfile https://github.com/pytorch/pytorch/blob/master/Dockerfile

abridged version:
echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list
sudo apt-get update && sudo apt-get install -y libnccl2=2.0.5-3+cuda9.0  libnccl-dev=2.0.5-3+cuda9.0

**Comment by vickylance** [comment]
@csarofeen I am using Ubuntu 17.10 not sure 1604 will work in my machine

**Comment by csarofeen** [comment]
Please see https://github.com/pytorch/pytorch/issues/3546

**Comment by tgirgin23** [comment]
Just tried 0.4.0 (with CUDA 9) on a p3 instance on AWS without any issues! Seeing a performance increase of 1.7x with the V100 compared to the EVGA 1080ti FTW3.

Just a quick question: is there anything that needs to be done by myself to make the code more compliant with CUDA 9.0 or is everything processed by pytorch?

**Comment by soumith** [comment]
@tgirgin23 everything is processed by pytorch

**Comment by snowzjy** [comment]
I tried,but setup failed. Please see #3828

**Comment by sdmonov** [comment]
I think this is same like #3807

**Comment by shihenw** [comment]
@tgirgin23 I also compiled pytorch from source with CUDA 9.0 + CUDNN 7 and V100, but suffered from a slow start issue (the GPU starts very slow in the first time). Did you run into similar problem?

My pytorch is 0.3.0 though. I tried the most recent version but still the same.

**Comment by tgirgin23** [comment]
@shihenw I did not have that issue at all. It worked out of the box for me.
The one time that I had a problem with the V100 was because I had upgraded to the wrong NVIDIA driver. Make sure you have a supported driver (seems that for the V100, **384.81** should be your driver version if you are up to date) http://www.nvidia.com/download/driverResults.aspx/124729/en-us

**Comment by shihenw** [comment]
@tgirgin23, so did you do anything special when building and installing it? I was simply "sudo python setup.py install``. And do you mind share exact version (git hash) of your 0.4.0 that worked? Thanks.

**Comment by vsahil** [comment]
When I tried to use nn.dataparallel with my model, it crashed with the following trace : 
```File "/home/ubuntu/program_quantization/src/core.py", line 31, in sampled_result
    return f(x) if callable(f) else model(x)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```

My Pytorch version is 0.4 and Cuda version is 9.0. Can you please help me. Also, there is no error when I don't use nn.dataparallel. The number of my GPU's is 4 and batch size is 64.
