### ISSUE TITLE
Windows nightly build errors

### ISSUE THREAD

**Issue by spiovesan** [pytorch/pytorch#27568]
## 🐛 Bug

There are build errors with https://download.pytorch.org/libtorch/nightly/cu100/libtorch-win-shared-with-deps-latest.zip
1. Unicode build
2. compile issue

1. Set Unicode carachter set in the project settings: you have an error .\libtorch\include\torch\csrc\jit\pickler.h line 34 with 
`UNICODE` = 'V',

2. In \libtorch\include\c10\util\llvmMathExtras.h
```
inline int64_t minIntN(int64_t N) {
   assert(N > 0 && N <= 64 && "integer width out of range");

   return -(UINT64_C(1)<<(N-1));
 }
```
does not compile, should be changed in 
```
 inline int64_t minIntN(int64_t N) {
   assert(N > 0 && N <= 64 && "integer width out of range");
   int64_t n = (UINT64_C(1) << (N - 1));
   return -n;
 }
```

cc @peterjc123

**Comment by peterjc123** [comment]
What about using `static_cast`?

**Comment by peterjc123** [comment]
I just realized that it's just the same issue with https://github.com/pytorch/pytorch/pull/15499#issuecomment-450038494.

**Comment by IlyaOvodov** [comment]
You fixed error No.4.
But what about No.3: Set Unicode carachter set in the project settings: you have an error .\libtorch\include\torch\csrc\jit\pickler.h line 34 with
UNICODE = 'V',
? 
This issue shouldn't be closed.

**Comment by peterjc123** [comment]
Thanks for pointing out. Actually for no.3, the workground is obvious. Just define another macro to save the value of `UNICODE`, unset it, include the torch headers and then restore the value. However, I couldn't figure out an elegant solution without changing the name of that variable to avoid the conflict between the macro and the variable. Any ideas, @ezyang?

**Comment by IlyaOvodov** [comment]
@peterjc123, I can't guess it is elegant :) but I can propose solution to do it inside pickler.h:
```
#ifdef UNICODE // https://github.com/pytorch/pytorch/issues/27568
#define UNICODE_TMP UNICODE
#undef UNICODE
#endif
enum class PickleOpCode : char { 
...
}
#ifdef UNICODE_TMP
#define UNICODE UNICODE_TMP
#undef UNICODE_TMP
#endif
```
Because workaround to do the same in outer code is really obvious (I did fix it this way), but only after you've found the source of the error, and still seems even less elegant :)
An idea to change the name of the variable also seems not bad.

**Comment by ezyang** [comment]
Yes, let's rename the macro. Send in a PR and assign me as reviewer.

**Comment by peterjc123** [comment]
I'm fixing it with #28782.
