### ISSUE TITLE
DataLoader raises an exception when exit()ing

### ISSUE THREAD

**Issue by francoisfleuret** [pytorch/pytorch#2757]
This piece of code

```python
import torch, torchvision

transform =  torchvision.transforms.ToTensor()
train_set = torchvision.datasets.CIFAR10(root = './', train = True, download = True, transform = transform)
train_loader = torch.utils.data.DataLoader(train_set, batch_size = 100, num_workers = 2)

data_iter = iter(train_loader)

exit(0)
```

generates [often, non-deterministically]

```
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f5b3f117908>>
Traceback (most recent call last):
  File "/home/fleuret/misc/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 241, in __del__
  File "/home/fleuret/misc/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 237, in _shutdown_workers
  File "/home/fleuret/misc/anaconda3/lib/python3.5/multiprocessing/queues.py", line 349, in put
  File "/home/fleuret/misc/anaconda3/lib/python3.5/multiprocessing/reduction.py", line 49, in dumps
TypeError: 'NoneType' object is not callable

```

**Comment by soumith** [comment]
i'm not able to reproduce this. can anyone else in @pytorch/fbcore  repro this?

**Comment by jwpalermo28** [comment]
I am also unable to reproduce.

**Comment by francoisfleuret** [comment]
I see the bug randomly for ~ half of the runs.

Is there any information I can dump to help?

**Comment by soumith** [comment]
if you you could produce this in a Debian docker image, that'd be easily reproducible on my side and i can look further.

You can run docker with debian/jessie with the command:

```
docker run -it --ipc=host --rm -v $(pwd):/remote debian:jessie bash
```

The current working directory is mounted at `/remote`.

Let me know if you can reproduce it in that environment, with the commands you ran in that environment.

**Comment by francoisfleuret** [comment]
I will try the docker test if I find the time, but note that I was not able to reproduce the bug with another install of pytorch in a VM with python 3.6.0 ...

**Comment by colesbury** [comment]
I suspect this is because the destructor is being called after Python starts unloading modules. The error messages points to [reductions.py:49](https://github.com/python/cpython/blob/3.5/Lib/multiprocessing/reduction.py#L49): The `NoneType` object refers to the `io` module.

There's not much we can do about this. Errors in destructors are ignored (note the "Exception ignored in..." message). To avoid this, wrap your code in a `def main()`. That way the objects will be destructed when the `main()` function exits.
