### ISSUE TITLE
Cosine distance

### ISSUE THREAD

**Issue by nishnik** [pytorch/pytorch#2758]
Hey can I work on [this](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/distance.py#L72)

I am thinking to do the same as `CosineSimilarity` but in method `forward`:

```
return (1 -  F.cosine_similarity(x1, x2, self.dim, self.eps))
```

**Comment by fmassa** [comment]
Do we need a new class for cosine distance given that we already have cosine similarity?

**Comment by nishnik** [comment]
There was a `TODO`, so I considered it.
Will hold until your call.

**Comment by fmassa** [comment]
I think this TODO is reminiscent from before we added `CosineSimilarity`. Indeed, in lua-torch, we have a `CosineDistance` function that is actually performing the cosine similarity.
I think we can remove the TODO.

**Comment by nishnik** [comment]
Okay!
I would make a PR for that.
What about [Euclidean Distance](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/distance.py#L73) ?

**Comment by fmassa** [comment]
I think it meant to write a module like [`Euclidean.lua` from lua torch](https://github.com/torch/nn/blob/master/Euclidean.lua), which also learns some centroids as part of the module. I'm not sure how widespread is the use-case of such a module, but if @soumith is OK that could be added.

Also, note that for simple distance computations we already have `F.pairwise_distance`.

**Comment by soumith** [comment]
neither that or Euclidean are needed. We could probably remove the TODO there (i'll do it now).

If you are looking to work on something, have a look at https://github.com/pytorch/pytorch/projects/5 and pick something from the nn / torch / autograd category.
