### ISSUE TITLE
wrong output dimension for onnx conv layer parse with "SAME_UPPER" padding

### ISSUE THREAD

**Issue by vera121** [pytorch/pytorch#27602]
## 🐛 Bug

When I try to use pytorch/caffe2 as backend to run onnx model, I found the result for conv layer with "SAME_UPPER" padding is wrong. The output shape is not correct as expected.

## To Reproduce
Model is downloaded from onnx model zoo: [tiny_yolov2](https://onnxzoo.blob.core.windows.net/models/opset_8/tiny_yolov2/tiny_yolov2.tar.gz)

1. install pytorch and onnx
2. run the model
```
import numpy as np
import onnx
import caffe2.python.onnx.backend

batch = 1
channel = 3
image_h = 416
image_w = 416
img = np.random.random_sample([batch, channel, image_h, image_w]).astype(np.float32)

onnx_model = "tiny_yolov2/model.onnx"
model = onnx.load(onnx_model)

backend = caffe2.python.onnx.backend.prepare(model)
outputs = backend.run([img])

blobs = backend.workspace.Blobs()
caffe2_data = {k: backend.workspace.FetchBlob(k) for k in blobs}

layer_data = caffe2_data["convolution2d_1_output"]
print(layer_data.shape)
```

The output is (1, 16, 414, 414).
However, according to the correct logic, the output shape should be (1, 16, 416, 416) for this conv layer, as the layer's attribute **auto_pad** is set to "SAME_UPPER".
Ref: ONNX Op definition for [Conv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv)

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.9.3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 390.25
cuDNN version: /usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py36_cu100    pytorch

**Comment by haifenghan** [comment]
onnxruntime and onnx's shape inference give the result:  (1, 16, 416, 416)

**Comment by garymm** [comment]
Caffe2 is no longer being developed so this is unlikely to be fixed.
