### ISSUE TITLE
notebook not found

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#27604]
## 📚 Documentation

SEQUENCE-TO-SEQUENCE MODELING WITH NN.TRANSFORMER AND TORCHTEXT
google colab notebook not found
https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/transformer_tutorial.ipynb

also error when running the code in colab
![Screenshot (27)](https://user-images.githubusercontent.com/43755000/66479951-83685880-ead8-11e9-95b8-485932a68cdf.png)
![Screenshot (28)](https://user-images.githubusercontent.com/43755000/66479952-83685880-ead8-11e9-95b4-129a71180c16.png)

cc @ezyang

**Comment by zou3519** [comment]
I think this should go into the pytorch/tutorial repo.

**Comment by vainaijr** [comment]
ok, I raised issue in pytorch/tutorial.
