### ISSUE TITLE
Free Memory after CUDA out of memory error

### ISSUE THREAD

**Issue by thequilo** [pytorch/pytorch#27600]
## 🐛 Bug

Sometimes, PyTorch does not free memory after a CUDA out of memory exception.

## To Reproduce

Consider the following function:
```python
import torch

def oom():
    try:
        x = torch.randn(100, 10000, device=1)
        for i in range(100):
            l = torch.nn.Linear(10000, 10000)
            l.to(1)
            x = l(x)
    except RuntimeError as e:
        print(e)
        print('at iteration', i)
```

Executing it one time gives the expected out of memory error after some iterations:
```python
>>> oom()
CUDA out of memory. Tried to allocate 381.50 MiB (GPU 1; 7.92 GiB total capacity; 7.16 GiB already allocated; 231.00 MiB free; 452.50 KiB cached)
at iteration 19
```

Executing a second time gives a OOM error immediately after the first iteration, which means that the memory consumed by the scoped variables in x is still occupied (which is a little weird):

```python
>>> oom()
CUDA out of memory. Tried to allocate 381.50 MiB (GPU 1; 7.92 GiB total capacity; 7.16 GiB already allocated; 231.00 MiB free; 452.50 KiB cached)
at iteration 0
```

Calling `gc.collect()` now sometimes (!!) leads to freeing the memory and sometimes it doesn't. 

## Expected behavior

I expected a consistent behavior that frees the memory after the OOM exception occurred or at least after `gc.collect()` gets called.

## Environment

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux release 7.3.1611 (Core) 
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080

Nvidia driver version: 387.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] pytorch-wpe==0.0.0
[pip] torch==1.0.0
[pip] torch-complex==0.0.1
[conda] blas                      1.0                         mkl  
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch
[conda] pytorch-wpe               0.0.0                    pypi_0    pypi
[conda] torch-complex             0.0.1                    pypi_0    

## Additional context

I stumbled upon this because I tried to fallback to CPU for computation of a single batch after a OOM error. I noticed that after the computation on the CPU, still the GPU memory was blocked sometimes and caused all following batches to be computed on the CPU as well.

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
I think it is useful to be able to recover well from an OOM.

**Comment by gchanan** [comment]
Maybe related to https://github.com/pytorch/pytorch/issues/18853.

**Comment by albanD** [comment]
I cannot reproduce this locally:
```
In [1]: oom()
CUDA out of memory. Tried to allocate 382.00 MiB (GPU 1; 15.90 GiB total capacity; 15.08 GiB already allocated; 285.56 MiB free; 16.64 MiB cached)
at iteration 40

In [2]: oom()
CUDA out of memory. Tried to allocate 382.00 MiB (GPU 1; 15.90 GiB total capacity; 15.08 GiB already allocated; 285.56 MiB free; 16.64 MiB cached)
at iteration 40
```

Not sure what happens in your case.
Could you check what happens if you call `torch.cuda.empty_cache()` between the two calls of `oom()`. You must call this in the command line and **not** in the oom() function itself.

**Comment by thequilo** [comment]
> I cannot reproduce this locally

I kind of expected this. I noticed that, in a notebook, it happens more frequently if the exception is not handled within the function but by the notebook environment. The modified function

```python
import torch

def oom(raise_=False):
    try:
        x = torch.randn(100, 10000, device=1)
        for i in range(100):
            l = torch.nn.Linear(10000, 10000)
            l.to(1)
            x = l(x)
    except RuntimeError as e:
        print(e)
        print('at iteration', i)
        if raise_:
            raise
```
called two times with 
```python
oom(True)
```
almost always causes the error in my environment.

> Could you check what happens if you call torch.cuda.empty_cache() between the two calls of oom(). You must call this in the command line and not in the oom() function itself.

Yes, it frees a few MB of memory from the GPU (visible in `nvidia-smi`), but the remaining few GBs still remain on the GPU. Following calls of `oom()` still result in instant failure during the first iteration. The only way I can reliably free the memory is by restarting the notebook / python command line.

Can this be related to the PyTorch and CUDA versions I'm using? I am limited to CUDA 9, so I sticked to PyTorch 1.0.0 instead of the newest version.

**Comment by thequilo** [comment]
Also, calling `oom` in `except` does the same thing:

```python
try:
    oom(True)
except:
    oom()
```
produces (every time I tested it):
```
CUDA out of memory. Tried to allocate 381.50 MiB (GPU 1; 7.92 GiB total capacity; 7.16 GiB already allocated; 238.94 MiB free; 452.50 KiB cached)
at iteration 19
CUDA out of memory. Tried to allocate 381.50 MiB (GPU 1; 7.92 GiB total capacity; 7.16 GiB already allocated; 234.94 MiB free; 452.50 KiB cached)
at iteration 0
```
Even with `gc.collect()` and/or `torch.cuda.empty_cache()` before the second call of `oom`.

**Comment by thequilo** [comment]
Just tested it with PyTorch 1.3 compiled for CUDA 9.0 and have the same issue

**Comment by thequilo** [comment]
I just noticed that the last example does not clean up the exception in the except block. This should work (and it indeed does work in a totally different environment...), but not for me:

```python
try:
    oom(True)
except Exception as e:
    del e
    oom()
```

**Comment by albanD** [comment]
Hi,

> Also, calling oom in except does the same thing:

This is expected as the exception holds on to the frame where the error was raised. Which holds onto all the Tensors on the GPU and so they cannot be freed yet as you could access them.
This is why collect or empty_cache have no effect.

> I noticed that, in a notebook, it happens more frequently if the exception is not handled within the function but by the notebook environment.

I would except that as well as the notebook has the tendency to hold onto the last error for a while and so the same problem as above can happen.


So I think this is expected behavior, you just need to be aware that the python error holds onto all the local variables of the stack trace. And so as long as you hold onto the exception, the memory cannot be freed.

**Comment by ZisIsNotZis** [comment]
For `jupyter`, one way to recover automatically is to catch the exception, save all things necessary, and run

```python
from IPython.display import Javascript
display(Javascript('Jupyter.notebook.restart_run_all({"confirm":false})'))
```

**Comment by auroua** [comment]
I am using two `gpus`  training two different models in two different threads. I encountered the same problem. I can successfully free memory on  `gpu:0` but can not free memory on 'gpu:1'.
This is the code used for free memory.

```
    while True:
        flag = False
        if model_stat:
            model_stat.zero_grad()
            model_stat.to('cpu')
            del model_stat
        gc.collect()
        with torch.cuda.device(device):
            torch.cuda.empty_cache()

        model_stat = copy.deepcopy(model)
        try:
            output = input_construce(input_size, batch_size + 1, device)
            model_stat(**output)
        except Exception as e:
            if 'CUDA out of memory' in str(e):
                batch_size //= 2
            else:
                raise e
            logger.error(f'CUDA out of memory batch_size changed from {2*batch_size} to {batch_size}')
            flag = True
            del e
        if not flag:
            break
```

**Comment by albanD** [comment]
Hi,

This is hard to know for sure.
You can check this other issue for more details: https://github.com/pytorch/pytorch/issues/18853

**Comment by auroua** [comment]
I think my error is caused by Nvidia driver.After upgrade the driver from 418.43 to 440, the error disappear.

**Comment by Srinath320** [comment]
Hi, getting the below error while training

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by albertz** [comment]
Is it possible that you (or something) has accessed `tb_frame.f_locals` for any of the frames of the traceback? In that case, you might hit this CPython bug: https://github.com/python/cpython/issues/113939

In that case, it is tricky to free the references to any Torch tensors on the exception stack. You should call `traceback.clear_frames(exc.__traceback__)` (in any case a good idea to call this!), and then access `f_locals` again, which potentially cleans up a previous copy of the locals (due to https://github.com/python/cpython/issues/113939), i.e. sth like this:
```python
while tb:
    try:
        tb.tb_frame.clear()
    except RuntimeError:
        pass
    else:
        # Using this code triggers that the ref actually goes out of scope, otherwise it does not!
        # https://github.com/python/cpython/issues/113939
        tb.tb_frame.f_locals  # noqa
    tb = tb.tb_next
```
