### ISSUE TITLE
Libtorch Inference  Batch Input

### ISSUE THREAD

**Issue by zhjw0927** [pytorch/pytorch#27601]
![image](https://user-images.githubusercontent.com/42128459/66465726-f57a7680-eab3-11e9-91f6-92840c57e70f.png)

The above is the data preprocessing stage. The batch input to the model is one.
Now, I want to set batch to four, because will process four channels of video at the same time.
How should I do ? Hope get your help. Thank you !

cc @yf225

**Comment by zou3519** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. We use the issue tracker for bugs and feature requests. Please kindly feel encouraged to reopen this issue, if this does not apply.
