### ISSUE TITLE
Refactor part of qat.ConvBn as an aten op

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#27625]
We want to refactor this part of code into a separate aten function in order to better support graph mode quantization for qat, because we don't want recognize the whole pattern in the graph when we insert FakeQuant ops: 
https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/qat/modules/conv_fused.py#L94-L106
https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/qat/modules/conv_fused.py#L116-L135

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by vkuzo** [comment]
closing, this is outdated
