### ISSUE TITLE
Not possible to use different key/value dimensionalities in nn.MultiheadAttention

### ISSUE THREAD

**Issue by stangelid** [pytorch/pytorch#27623]
## 🐛 Bug

The [nn.MultiheadAttention constructor](https://pytorch.org/docs/stable/nn.html#torch.nn.MultiheadAttention) allows using _key_ and/or _value_ dimensionalities which are different from `embed_dim`, using the `kdim` and `vdim` positional arguments. However, when setting either `kdim` or `vdim` to a non-`None` value, [this assertion in `F.multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/v1.2.0/torch/nn/functional.py#L3103) unnecessarily blocks execution.

## To Reproduce

```python
import torch
import torch.nn as nn

batch_size = 5
seq_len = 10
embed_dim = 24
value_dim = 12
num_heads = 1

query = torch.randn(seq_len, batch_size, embed_dim)
key = torch.randn(seq_len, batch_size, embed_dim)
value = torch.randn(seq_len, batch_size, value_dim)

mha = nn.MultiheadAttention(embed_dim, num_heads, vdim=value_dim)
attn_out, attn_out_weights = mha(query, key, value)
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/inf.ed.ac.uk/user/s/sangelid/venv/pytorch_36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/afs/inf.ed.ac.uk/user/s/sangelid/venv/pytorch_36/lib64/python3.6/site-packages/torch/nn/modules/activation.py", line 769, in forward
    v_proj_weight=self.v_proj_weight)
  File "/afs/inf.ed.ac.uk/user/s/sangelid/venv/pytorch_36/lib64/python3.6/site-packages/torch/nn/functional.py", line 3103, in multi_head_attention_forward
    assert key.size() == value.size()
AssertionError
```

## Expected behavior

The above snippet should run without an AssertionError. The problematic assertion must only be checked if `kdim is None and vdim is None`, i.e., if `self._qkv_same_embed_dim is True`. The `forward()` function correctly checks the value of `self._qkv_same_embed_dim`, and calls `F.multi_head_attention_forward` with the appropriate arguments, including `use_separate_proj_weight=True` and separate query, key, and value projection weights. 

So, in `F.multi_head_attention_forward`, this assertion should only be checked if `use_separate_proj_weight is False`.

## Environment

PyTorch version: 1.2.0 (but problem remains in master too).

**Comment by zou3519** [comment]
cc @zhangguanheng66

**Comment by iamlockelightning** [comment]
Keep watching

**Comment by zhangguanheng66** [comment]
@iamlockelightning @stangelid Though we allow `key` and `value` to have different value from `embed_dim`, we still require `key` and `value` to have same size. You should set `kdim` and `vdim` to the same value. Probably, I should have an error check there.

Do you see a case that `key` and `value` have different size?

**Comment by ffuuugor** [comment]
It's unclear what's the reason of having kdim and vdim as separate parameters, while they are always enforced to be the same

**Comment by stangelid** [comment]
> Do you see a case that `key` and `value` have different size?

In the context of the vanilla Transformer, the key and value will always be of equal size.

However, I can easily imagine a senario where you would use the multi-head attention mechanism to assign attention weights to an arbitrary set of value vectors, whose size is different from the keys and/or queries.

**Comment by IsmailAlaouiAbdellaoui** [comment]
I am working on the exact same problem. I would like to have an output dimension that is different from the input embedding dimension ( just like an LSTM does ). According to the original paper, the variable that sets the dimension of the output is the value vector ( and thus its dimension ).

**Comment by zhangguanheng66** [comment]
We have a PR https://github.com/pytorch/text/pull/720 on MultiheadAttention building blocks. With them, you should be able to test different variants on your side.

**Comment by roderickObrist** [comment]
I am currently in a scenario where my keys and values are of different dimensions, from what I can see, commenting out that assertion makes everything work perfectly

**Comment by zhangguanheng66** [comment]
> I am currently in a scenario where my keys and values are of different dimensions:
> 
> I want the weights of my values to be dependant on positional information, but I do not want positional information to be passed through to the following layers.
> 
> From what I can see, commenting out that assertion makes everything work perfectly

Do you think the MHA container in https://github.com/pytorch/text/pull/720 works as a solution?

You are right that the current MHA requires k-dim and v-dim to be same. I can remove the assert.

**Comment by roderickObrist** [comment]
While I would love to try it out (performance gains and all). I don't know where to find any documentation on installation or implementation.

I was going to wait until it was merged and public and give it a go in my spare time.

Also I have removed the assert in my own code, so no need to rush for me, but I do think that the assert makes the code worse than better

**Comment by zhangguanheng66** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/39402
