### ISSUE TITLE
Remove observer in qat modules

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#27622]
I think it's better to remove `self.observer` call in forward function of qat module: https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/qat/modules/conv_fused.py#L218
I think we should use add_observer_(https://github.com/pytorch/pytorch/blob/master/torch/quantization/quantize.py#L150) to keep things more consistent. This means we should split add_observer_ out of prepare and call it after the `prepare_qat` function

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by raghuramank100** [comment]
This approach will work for activations, but not for weights. Are you suggesting doing this only for the activations?

**Comment by jerryzh168** [comment]
@raghuramank100 yes, only for activations.

**Comment by vkuzo** [comment]
closing outdated issue, please reopen if this is still relevant
