### ISSUE TITLE
Can't import saved pytorch model

### ISSUE THREAD

**Issue by ankanch** [pytorch/pytorch#2762]
I have trained a model ,and I saved it by `torch.save(cnn4mnist, 'cnn4mnist.pt')`.
But when I trying to load this model from the 'cnn4mnist.pt' file via this code `
model = torch.load('cnn4mnist.pt')`. An error occured as below:

```
Traceback (most recent call last):
  File "predict.py", line 11, in <module>
    model = torch.load('cnn4mnist.pt')
  File "C:\Users\kanch\Anaconda3\lib\site-packages\torch\serialization.py", line 231, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\kanch\Anaconda3\lib\site-packages\torch\serialization.py", line 379, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'CNN4MNIST' on <module '__main__' from 'predict.py'>
```

Don't really know what does this means.

**Comment by fmassa** [comment]
When did you install PyTorch? Was it very recently?
This might be a bug introduced in https://github.com/pytorch/pytorch/pull/2760

**Comment by ankanch** [comment]
@fmassa  I installed it in one week via conda.
 Sorry for the inconvenience, I have resolved it . It's my problem.
I resolved it by adding the class definition code to the this script.
But I think it not in the logical that we import a model we have to also add the code of it's class destinations.

**Comment by fmassa** [comment]
If I understand correctly, this is the way python and pickle works, you need to have the class definition visible/importable when unpickling a file that contains an object.

**Comment by fmassa** [comment]
I think this issue can be closed

**Comment by ankanch** [comment]
@fmassa  Can this be changed in the future? When we export a model, can we export class definition as well?

**Comment by fmassa** [comment]
@ankanch not sure we will tackle that. One way of exporting both the parameters and the architecture would be to export to ONNX, but that would make modifying the model difficult.

**Comment by Zahra-Kadkhodaie** [comment]
@ankanch I have the same issue, but don't know how I can resolve it. How can I add the class definition to my script? Thanks

**Comment by rajarsheem** [comment]
If declaring the class definition is necessary before loading when the full model graph was saved via torch.save(model, ...), then why wouldn't I just save the model state_dict torch.save(model.state_dict(), ...) ? How the former is different (or beneficial) than the latter ?

**Comment by gky1993** [comment]
I have the same problem!!! I use torch.save(model,...) to save the model but can not load the model with torch.load()??? I load models successfully before , why can't I now ?

**Comment by gky1993** [comment]
@Zahra-Kadkhodaie how do you add the definition?

**Comment by IssamLaradji** [comment]
It could be because it was corrupted and wasn't saved properly

**Comment by iGuaZi** [comment]
> @fmassa I installed it in one week via conda.
> Sorry for the inconvenience, I have resolved it . It's my problem.
> I resolved it by adding the class definition code to the this script.
> But I think it not in the logical that we import a model we have to also add the code of it's class destinations.

I also met this problem. what do you mean by "adding the class definition code to this script"? could you please be a little more specific??

**Comment by ankanch** [comment]
@iGuaZi  就是把你那个模型的类定义加到要加载那个模型的代码里面去.

**Comment by kuaitoukid** [comment]
> @iGuaZi 就是把你那个模型的类定义加到要加载那个模型的代码里面去.

简单粗暴的中文回复2333

**Comment by AlvinLXS** [comment]
直接将定义网络结构的类放进代码中就可以了

**Comment by ChenWentai** [comment]
> 直接将定义网络结构的类放进代码中就可以了

Put the code of the model class definition(e.g. `class Model(nn.Module):`) before your `torch.load(model_name)`

**Comment by McQueen64** [comment]
I hava the same problem!! and I sovled it by definiting the model class before <torch.load()>, and I also found that <def __init__(self)> can not be given, but the <def forward(self, input)> function must be definited

**Comment by McQueen64** [comment]
I have the same problem!! and I sovled it by definiting the model class before """torch.load()""", and I also found that """def __init__(self)""" can not be given, but the """def forward(self, input)""" function must be definited

**Comment by McQueen64** [comment]
I have the same problem!! and I have resolved it by defining the model class before `torch.load()`, and I also found that `def __init__(self)` can not be given, but the `def forward(self, input)` function must be defined

**Comment by MAR1990** [comment]
> I have the same problem!! and I have resolved it by defining the model class before `torch.load()`, and I also found that `def __init__(self)` can not be given, but the `def forward(self, input)` function must be defined

Can You please elaborate this, I am also facing same issue

**Comment by yarkable** [comment]
> 
> 
> @iGuaZi 就是把你那个模型的类定义加到要加载那个模型的代码里面去.

hardcore

**Comment by sriatz** [comment]
> @iGuaZi 就是把你那个模型的类定义加到要加载那个模型的代码里面去.
还是不太懂，我已经加了model = ResNet34() 然后用 model = torch.load(args.weights) 加模型的定义应该就是这个意思吧？ 结果还是报这个错。。。

**Comment by ykk136** [comment]
> > @iGuaZi 就是把你那个模型的类定义加到要加载那个模型的代码里面去.
> > 还是不太懂，我已经加了model = ResNet34() 然后用 model = torch.load(args.weights) 加模型的定义应该就是这个意思吧？ 结果还是报这个错。。。

When you train a model under a fixed environment, such as the structure of the project directory, you must load the trained model under the same environment, especially the Class structure declared before you start training.
