### ISSUE TITLE
[feature request] Vec256 power le vsx support

### ISSUE THREAD

**Issue by quickwritereader** [pytorch/pytorch#27678]
I would like to add vsx support to aten Vec256 for power le platform.
The work is still in progress. I open this issue to discuss this topic as I saw Vec256 is kept modified.
For now 
I am simulating  256bit using 2 128 bit vector variables.
For supporting vsx inside pytorch 
-cmake for vsx detection
-pytorch modifications for handling power  
-Vector codes for Vec256<float>, Vec256<double>, Vec256<int16_t>, Vec256< int32_t>, Vec256< int64_t> ,Vec256<qint>

I keep those Vec256 changes isolated from PyTorch for testing purposes and it was not fully incorporated and ready to ship. As there are not any benchtests I just looked at generated codes. Under gcc8 -Ofast compiler-generated assemblies were quite good. 

For now, for me, the main obstacle is the way to implement trigonometric, other mathematical functions. Firstly, I went with avx_mathfun and translated its codes into vsx:
-all avx_mathfun sin,cos,exp.log was implemented inside Vec256<float> 
-I also implemented pow, sin, cosh and other functions.

Pytorch team is using sleef library for some functions. I checked sleef library and they have support for 128bit vsx functions. I could either translate those into simulated 256bit or I could use [cephes implementations](http://www.netlib.org/cephes/) as it was done with avx_mathfun.

I am planning to add vsx support as separate headers like vec256_*_vsx.h.

I also think that we could add test cases for Vec256 using either google test or catch. I only used the later.
Any guidance on this topic is appreciated. I want that my changes fit both ibm and pytorch team.

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel @mruberry

**Comment by cpuhrsch** [comment]
cc @VitalyFedyunin

**Comment by cpuhrsch** [comment]
@quickwritereader - are you sure that auto-vectorization isn't enough?

**Comment by cpuhrsch** [comment]
I'm marking this as follow up for the triage review so the wider topic of powerpc support can be discussed.

**Comment by quickwritereader** [comment]
With perfect compilers it is. But At this current state I think it could vectorize  only  basic operations. I was told by IBM team about  this. I started to work on this hoping to be rewarded bounty if it fits both teams requirements.

**Comment by gchanan** [comment]
@cpuhrsch why is this marked both "triaged" and "triage review"?

**Comment by gchanan** [comment]
Removing "triaged" because this wasn't triaged.

**Comment by ezyang** [comment]
@gchanan I think it's fine if the triager adds triaged, saves us from having to add the label in the triage meeting

**Comment by ezyang** [comment]
@cpuhrsch my *impression* is that we don't have any concrete POWER plans in our mid-term roadmap. Accepting a patch like this may be quite involved because we would need to work out how to test VSX in CI; we are already having trouble with higher priority AVX512 (which our CI doesn't support) and I think the situation here is even worse. (@VitalyFedyunin, @ngimel, do you have any more information?)

**Comment by quickwritereader** [comment]
@edelsohn

**Comment by edelsohn** [comment]
IBM provides public Power development systems through
[OSUOSL Powerd development hosting](https://osuosl.org/services/powerdev/request_hosting/). I can sponsor VMs to run the ci.pytorch.org Jenkins instance for Power.

PyTorch libATen already includes some support for Power VSX and the architecture-specific support in libATen is well isolated for each architecture.  IBM and @quickwritereader solely are asking that PyTorch include the Power VSX optimizations in the appropriate architecture-specific optimization directory that we wish to contribute to expand the number of machine learning system architectures optimized for PyTorch.

**Comment by ezyang** [comment]
> I can sponsor VMs to run the ci.pytorch.org Jenkins instance for Power.

Just a quick note: we're deprecating the Jenkins instance. But byob may still be possible as we need this to work for amd

**Comment by gchanan** [comment]
@VitalyFedyunin will provide an answer.

**Comment by quickwritereader** [comment]
I'd like to resume working on this in the coming weeks and open pull request so that we could discuss based on modifications.

**Comment by quickwritereader** [comment]
I see Pytorch team added support for complex types too. So I think I have to add it before moving to full trigonometric, hyperbolic function support.
As I am keeping my vector codes outside of PyTorch, I recently added my latest codes which still should be improved and tested. 
Before continuing I would like to know if that's enough for Vsx switch. Please, check this branch
especially these files:

[my vsx branch commit](https://github.com/quickwritereader/pytorch/commit/d5f0fce0da861bcf39fa34aaa4a389b54d712920)
cmake/Modules/FindVSX.cmake
cmake/Codegen.cmake
cmake/Dependencies.cmake
 aten/src/ATen/native/DispatchStub.cpp
aten/src/ATen/native/DispatchStub.h

**Comment by edelsohn** [comment]
Whose opinion are you asking with regard to the VSX switch.  Anything is a good start.  This is a process. We want everything supported, but it's not fair to move the milestone with each new feature added to libATen.

**Comment by quickwritereader** [comment]
Mr @edelsohn I was about the CMake additions and DispatchStub,  not the VSX support itself.

**Comment by edelsohn** [comment]
It looks like at least part of the `FindVSX.cmake` code is probing the hardware configuration. I don't see a similar test for AVX. One should be able to build the code without hardware support on the build system.  It seems that the test only should probe the toolchain capabilities.

**Comment by quickwritereader** [comment]
I added it in case there is a need. Right now it just outputs message. Maybe I should look for cpuinfo itself As in the actual code they are using cpuinfo cpuinfo_has_... calls.  I made a VSX default.
[DispatchStub](https://github.com/quickwritereader/pytorch/blob/d5f0fce0da861bcf39fa34aaa4a389b54d712920/aten/src/ATen/native/DispatchStub.cpp)

**Comment by quickwritereader** [comment]
@edelsohn 
What do you think of using one-time vector constants and generated masks inside inline functions? First ones most times are added as static variables. But I think even this way inside loops GCC could code motion them as loop invariants. Is it a safe assumption?
const __vf coscof_p0 = vec_splats(2.443315711809948E-005f); //const may be unnecessary
const __vib mask_1st = (__vib){g0, g1, g2, g3}; //generated masks

**Comment by edelsohn** [comment]
I think that it's better to write code that the compiler should optimize instead of hand micro-optimizing code for a particular instance of the compiler. If the compiler doesn't optimize it efficiently, we can report a missed optimization for the compilers.

**Comment by VitalyFedyunin** [comment]
@edelsohn in our case we observing situation when it is better to hand-write vectorized code instead of leaving it up to compiler

@quickwritereader can you please clarify 'pytorch modifications for handling power' part? As ideally we would live to isolate all 'hardware' specific code to cmake files and Vec256 implementation. 

In general I have nothing against modifying cmake files to accommodate power compilation, but having one more copy of vec256 'kernels' will increase maintenance burden. So my main question is: did you had chance to compare compiler optimized code for power VS manually vectorized code via vec256?

**Comment by quickwritereader** [comment]
Hi Vitaly. I changed these files to add power Vec256 by following AVX,AVX2 additions
 [vsx branch](https://github.com/quickwritereader/pytorch/commit/d5f0fce0da861bcf39fa34aaa4a389b54d712920) 
cmake/Modules/FindVSX.cmake
cmake/Codegen.cmake
cmake/Dependencies.cmake
aten/src/ATen/native/DispatchStub.cpp
aten/src/ATen/native/DispatchStub.h

Frankly, I did not test compiler auto-vectorization.  As far as I know, manual vector codes are still the best option to help compilers.  
And also power le VSX SIMD support was requested by Mr @edelsohn. He is IBM team expert on this field and the one who initiates such tasks.
I understand maintenance concerns in future. As to make maintenance a little easier I think we could add good test cases for Vec256 types and compile-test it using different options (Base, AVX,VSX ,etc). I 
If it passes we could make that available. This way I believe we can address any problems that could happen because of future compilers or systems.

**Comment by edelsohn** [comment]
@VitalyFedyunin The question was not about hand-optimized kernels.  Abdel has written hand-optimized kernels for OpenBLAS.  The question is whether he could assume that the compiler would hoist loop invariant constants.

PyTorch and libATen are Open Source software.  They already contains some support for Power Altivec.  IBM is sponsoring Abdel to update and enhance the support for the newer design of libATen.  libATen provides a well-defined section for architecture-specific optimizations.  Power systems are available for Open Source developers and CI systems. Power systems now are available through Travis CI.  I hope that the PyTorch community wants the framework to be as widely adopted as possible.  IBM is trying to contribute enhancements consistent with its design of PyTorch to improve the performance of it on IBM Power systems targeted at AI/ML workloads.

**Comment by ceseo** [comment]
cc @ceseo

**Comment by quickwritereader** [comment]
#15676

**Comment by quickwritereader** [comment]
#41541 
I added initial support. I reported all problems and changes in the pull request

**Comment by quickwritereader** [comment]
Guys, I would like to know your opinions about my Pr so that I could fix it or make it suitable. I need this bounty
thanks

**Comment by abebeos** [comment]
@ team: status?

**Comment by quickwritereader** [comment]
@abebeos
I was busy for a month because of local problems. I'm going to refresh my PR with the latest master. and also address Sleef asan case hoping it will be accepted, finally

**Comment by abebeos** [comment]
Thanks for the update. Just asking, some bounties seem to be stalled since months. Good luck!

**Comment by quickwritereader** [comment]
@edelsohn
the initial vectorization support for ppc64le  was added. I'm closing the issue
