### ISSUE TITLE
 'collections.OrderedDict' object has no attribute 'fc'

### ISSUE THREAD

**Issue by micklexqg** [pytorch/pytorch#2767]
hello, everyone！
I am a pytorch newer. I try to load a pre-trained model:

```
 model_ft = torch.load("resnet34-333f7ec4.pth")  
 num_ftrs = model_ft.fc.in_features
```

but it occured an error:

 'collections.OrderedDict' object has no attribute 'fc'

how to load a pre-trained model?(without load_url method, the pretrained model is in current path)
any help appreciated!

**Comment by fmassa** [comment]
For your specific case, you need to set the `state_dict` of your model with the parameters that were saved, see [here](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L104) for one example.

Also, we use github issues for bugs and feature requests. Questions are better suited for the forums https://discuss.pytorch.org/

**Comment by micklexqg** [comment]
@fmassa , thank you!

**Comment by rchavezj** [comment]
How where I able to do this for saving?
