### ISSUE TITLE
Operation - and torch.min work differently?

### ISSUE THREAD

**Issue by jtlee90** [pytorch/pytorch#27674]
## To Reproduce

1. make tensor A shape of (3,)
2. make tensor B shape of (4, 1)
3. compare (A-B) and torch.min(A, B)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): Linux Ubuntu 18.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: CUDA 10.0 / cuDNN 7
 - GPU models and configuration: TITAN xp, Driver Version 430.26
 - Any other relevant information:

## Additional context

```
>>> t_rand                      
tensor([0.2345, 0.3456, 0.4567])
>>> t_ones                      
tensor([1., 1., 1., 1.])        

>>> t_rand - t_ones                  
tensor([[-0.7655, -0.6544, -0.5433], 
        [-0.7655, -0.6544, -0.5433], 
        [-0.7655, -0.6544, -0.5433], 
        [-0.7655, -0.6544, -0.5433]])
>>> torch.min(t_rand, t_ones)        
tensor([[0.2345, 0.3456, 0.4567],    
        [0.2345, 0.3456, 0.4567],    
        [0.2345, 0.3456, 0.4567],    
        [0.2345, 0.3456, 0.4567]])   
```
Is this intended behavior?

but add work same as I expected
```
>>> t_rand + t_ones                
tensor([[1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567]]) 
>>> torch.add(t_rand, t_ones)      
tensor([[1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567],  
        [1.2345, 1.3456, 1.4567]]) 
```

**Comment by t-vi** [comment]
`min` is `minimum`, not `minus`. `sub` is to `-` as `add` is to `+`.
