### ISSUE TITLE
an abnormal output of matmul when batchsize==matrix_size

### ISSUE THREAD

**Issue by formyfamily** [pytorch/pytorch#27686]
Hi, 

I was trying to use torch.matmul function to calculate two mini-batched matrix's product, i.e AxB, where A and B are both tensors with shape (batch_size, 3, 3).  However, when I adjusted the batch size to 3, the output of this function became totally different, and seems the function was taking the first two dimensions of B as the matrix size. Is this result plausible? I'm not very sure because when feeding a batched data to a network, I would assume that the results be consistent for all possible batch_size. 

Your answer will be much appreciated.

**Comment by cpuhrsch** [comment]
Hello @formyfamily,

Thank you for flagging this. Could you please add a script to reproduce this issue and follow the guidelines around filing a bug as detailed when creating an issue?

**Comment by formyfamily** [comment]
Hi, 

It turn out to be my mistake. The matmul is alright and there're other mistakes in my code. I'm sincerely sorry for the trouble.

**Comment by cpuhrsch** [comment]
@formyfamily No worries! However, next time please keep in mind to use the issue template.
