### ISSUE TITLE
1>E:\software\libtorch\include\torch/csrc/utils/variadic.h(195): error C2951: 模板 声明只能在全局、命名空间或类范围内使用

### ISSUE THREAD

**Issue by liushuan** [pytorch/pytorch#27680]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by liushuan** [comment]
torch::nn::Sequential model(torch::nn::Linear(2, 3));

**Comment by liushuan** [comment]
os  windows10 
libtorch 1.2

**Comment by peterjc123** [comment]
There are a couple of questions about your issue:
1. Why do you copy Chinese text to the topic? It's fine for me because I know Chinese, but it's not true for all the developers here. You need to translate it into English.
2. Why don't you fill in the form? Is there any trouble there?
3. Where is your code? What do you mean by simply copying `torch::nn::Sequential model(torch::nn::Linear(2, 3));` here?
4. Moreover, could you please tell me what compiler you are using and how you are constructing your project?

**Comment by peterjc123** [comment]
Please use VS 2017 instead.

**Comment by liushuan** [comment]
when I use Visual Studio 2017

when the code include :
#include <torch/torch.h>
this programe will compile fail.
error is:
1>e:\software\libtorch\include\torch\csrc\api\include\torch\data\detail\queue.h(78): error C2872: “std”: Ambiguous notation

**Comment by liushuan** [comment]
when I use Visual Studio 2017

when the code include :
#include <torch/torch.h&gt;
this programe will compile fail.
error is:
1&gt;e:\software\libtorch\include\torch\csrc\api\include\torch\data\detail\queue.h(78): error C2872: “std”: Ambiguous notation



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peterjc123"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 下午3:14
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"."<547691062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] 1&gt;E:\software\libtorch\include\torch/csrc/utils/variadic.h(195): error C2951: 模板 声明只能在全局、命名空间或类范围内使用 (#27680)




There are a couple of questions about your issue:
  
Why do you copy Chinese text to the topic? It's fine for me because I know Chinese, but it's not true for all the developers here. You need to translate it into English.
 
Why don't you fill in the form? Is there any trouble there?
 
Where is your code? What do you mean by simply copying torch::nn::Sequential model(torch::nn::Linear(2, 3)); here?
 
Moreover, could you please tell me what compiler you are using and how you are constructing your project?

**Comment by peterjc123** [comment]
Please add `::` before the usage of `std` in the corresponding line.

**Comment by liushuan** [comment]
when i use this code will error.
------------------------------------------------
#include <torch/torch.h&gt;
#include<iostream&gt;
int main() {
	system("pause");
	return 0;
}



------------------------------------------------
and this code is normal
---------
#include<iostream&gt;
int main() {
	system("pause");
	return 0;
}

---------




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peterjc123"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 下午4:49
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"."<547691062@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] 1&gt;E:\software\libtorch\include\torch/csrc/utils/variadic.h(195): error C2951: 模板 声明只能在全局、命名空间或类范围内使用 (#27680)




Please add :: before the usage of std in the corresponding line.

**Comment by peterjc123** [comment]
I know, have you tried my suggestion? That is to open `e:\software\libtorch\include\torch\csrc\api\include\torch\data\detail\queue.h`, replace `std` with `::std` in line 78.

**Comment by liushuan** [comment]
There are many similar mistakes

**Comment by peterjc123** [comment]
@liushuan Just fix them one by one.

**Comment by liushuan** [comment]
Have you used this method before?

**Comment by peterjc123** [comment]
@liushuan Isn't this one simply the duplicate of https://github.com/pytorch/pytorch/issues/18607 and https://github.com/pytorch/pytorch/pull/17863?

**Comment by liushuan** [comment]
thanks, I will try again.

**Comment by liushuan** [comment]
this problem be solve with this method.
I tested on different configurations and found that problem can be solved by change the conformance mode property to No. You can find that option in C/C++->Language. That's a new feature in vs2017 and 2019.

**Comment by sh0416** [comment]
@liushuan Where can I found "C/C++->Language"? Do you use "Visual Studio 2017", not "Visual Studio 2017 Build tool"?

**Comment by peterjc123** [comment]
@sh0416 If you use "Visual Studio 2017 Build tool", please remove '/permissive-' from the argument list in the compiler command line.

**Comment by sh0416** [comment]
@peterjc123 Thanks for fast reply, I tried to extend my C++ code to python code using `torch.utils.cpp_extension`. So, I just use "python setup.py install". What do I do in this case?

**Comment by peterjc123** [comment]
Could you please open a new issue with the full log and the commands you entered?

**Comment by sh0416** [comment]
@peterjc123 For now, I use "Visual Studio 2015 Build tool". I tried it with "Visual Studio 2017 Build tool" and open a new issue if the problem remains.

**Comment by sh0416** [comment]
@peterjc123 I reinstall all compilation tools. I install "Visual Studio 2019" and "CUDA 10.1". Now, that error doesn't occur, but other errors emerge. After searching the solution, I found https://github.com/facebookresearch/detectron2/issues/9#issuecomment-549013090 and it works for me.
The problem was about `constexpr`, which needs to be fixed in the compile time. I just changed it to `const`, which has weaker constraint, and it works. :)
If you think it cause some bugs, please let me know. Thanks.
