### ISSUE TITLE
[functional] torch.unique not implemented for booleans

### ISSUE THREAD

**Issue by frgfm** [pytorch/pytorch#27691]
## 🐛 Bug

The `torch.unique` function is not implemented for `torch.bool` dtype.

## To Reproduce

```
import torch
u1 = torch.unique(torch.rand(3,3), sorted=False)
u2 = torch.unique((10 * torch.rand(3,3)).round().to(dtype=torch.int), sorted=False)
u3 = torch.unique(torch.rand(3,3).round().to(dtype=torch.bool), sorted=False)
```
which produces
```
RuntimeError: "unique" not implemented for 'Bool'
```

## Expected behavior

I understand the switch from `torch.uint8` to `torch.bool` is fairly recent and that  `torch.unique` does not seem very useful on booleans, but the feature is very useful when specifying the `dim` argument (`torch.unique` on boolean sequences for instance).

## Environment

 - PyTorch Version: 1.2.0
 - OS: Ubuntu 18.04.3 LTS
 - How you installed PyTorch: `conda`
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 10.1.168 (cuDNN 7.6.2)
 - GPU models and configuration: GeForce GTX 1050 (driver: 430.50)

cc @ezyang @gchanan @zou3519 @izdeby

**Comment by cpuhrsch** [comment]
I'm flagging this as high priority because it is a regression in feature coverage when migrating from uint8 to bool tensors.

**Comment by ezyang** [comment]
cc @izdeby

**Comment by izdeby** [comment]
Fixed
