### ISSUE TITLE
Add javasphinx to docs/requirements.txt

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27705]
There were some other pip packages that I needed to install that I don't remember right now.

Furthermore, the docs require the following that we should document somewhere:
- global installation from katex

cc @ezyang @gchanan @zou3519

**Comment by cpuhrsch** [comment]
I'm flagging this high priority since it can block users from being able to use PyTorch.

**Comment by zou3519** [comment]
It only blocks devs from building the documentation. It shouldn't affect regular users of pytorch.

**Comment by cpuhrsch** [comment]
Ok, then I'm removing the high priority tag.

**Comment by Ir1d** [comment]
@zou3519 after installing javasphinx and katex (globally), I managed to generate pleasing builds.

![image](https://user-images.githubusercontent.com/10709657/66622372-e7466a80-ec19-11e9-9f61-826c9715ce78.png)

**Comment by rgommers** [comment]
`javasphinx` is present in `docs/requirements.txt`, and how to install `katex` globally or separate is explained in `CONTRIBUTING.md`, so closing. For further doc build issues, see gh-32703.
