### ISSUE TITLE
Don't require CUDA to build docs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27706]
Right now, we require a CUDA installation of pytorch to build docs. I think this is necessary for the following reasons:

- Some of our operators are "turned off" in a CPU-only build
- torch.distributed is "turned off" in a CPU-only build.

It would be nice to refactor the code such that all docstrings and APIs are available in a CPU-only build and error out gracefully instead of having those APIs be completely missing.

This would speed up documentation building time; we wouldn't have to wait for a full CUDA build of pytorch.

cc @ezyang

**Comment by cpuhrsch** [comment]
@zou3519 this seems like a low priority issues unless you rebuild documentation very frequently, which I assume most users don't.

**Comment by zou3519** [comment]
Users don't build documentation very frequently. However, our master docs are built continuously on commits to master. It would be good for better engineering and avoid flakiness for the master doc push to NOT depend on our CUDA build, which times out from time to time. I would not characterize this as low priority.

**Comment by zou3519** [comment]
This was an incorrect diagnosis so I'm opening a new issue with a better one.
