### ISSUE TITLE
The problem about EmbeddingBag module

### ISSUE THREAD

**Issue by GeekTemo** [pytorch/pytorch#2771]
Code as below:

import torch
import torch.nn as nn
from torch.autograd import Variable

embedding_sum = nn.EmbeddingBag(10, 3, mode='sum')
x = Variable(torch.LongTensor([[1,2,4,5],[4,3,2,9]]))
embedding_sum(x)

raised an   RuntimeError: expected a Variable argument, but got torch.LongTensor。
Pytorch  Version: 0.2.0.post1

**Comment by soumith** [comment]
This was fixed in master and will be part of the next release.
