### ISSUE TITLE
native functions: int arg does not accept np.int64

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#27714]
```py
In [1]: import torch

In [3]: import numpy as np

In [9]: x = torch.randn(100)

In [11]: x.narrow(0, 0, np.array(3, dtype=np.int64).sum())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-9e6bc07f0d80> in <module>
----> 1 x.narrow(0, 0, np.array(3, dtype=np.int64).sum())

TypeError: narrow(): argument 'length' (position 3) must be int, not numpy.int64

In [4]: torch.randn(np.array(3))  # notice IntArray parses these fine
Out[4]: tensor([-1.1104, -0.0871,  1.2771])

In [5]: torch.randn((np.array(3),))  # notice IntArray parses these fine
Out[5]: tensor([-0.5826, -0.1124, -0.4657])

In [6]: torch.randn(size=(np.array(3),))  # notice IntArray parses these fine
Out[6]: tensor([-0.9595, -0.6848, -0.6971])

In [7]: torch.randn(size=(np.array(3, dtype=np.int64),))  # notice IntArray parses these fine
Out[7]: tensor([-1.1161,  1.4269,  1.5838])

````

cc @ezyang @gchanan @zou3519

**Comment by cpuhrsch** [comment]
Is this an error due to recent changes or a feature request?

**Comment by SsnL** [comment]
@cpuhrsch More like a bug report. It is inconsistent. I'm not sure if it works before though...

**Comment by cpuhrsch** [comment]
I'm marking this high priority and for triage review in case it's expected to case further issues down the road and because I don't have a good overview of the community here.

**Comment by ezyang** [comment]
The suggested change seems reasonable to do, but I'm not sure I would mark it as high priority (seems pretty niche)

**Comment by SsnL** [comment]
The root cause is that parsing `intlist` uses `THPUtils_unpackIndex` (which uses `PyNumber_Index`) while parsing an int uses `THPUtils_unpackLong` (which uses `PyNumber_Long`). I don't have enough knowledge on when to use one vs the other, and googling doesn't help much.

**Comment by gchanan** [comment]
Removing "triaged" because this wasn't triaged.

**Comment by gchanan** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/27754 for better handling of numpy scalars.

I'd also probably not make it high priority, but it's a reasonable request, and it doesn't have complicated issues like https://github.com/pytorch/pytorch/issues/27754 does.

**Comment by zou3519** [comment]
@nairbv I remember you had a PR that allows accepting np.ints as ints in python arg parser. Did that fix this issue?

**Comment by nairbv** [comment]
> @nairbv I remember you had a PR that allows accepting np.ints as ints in python arg parser. Did that fix this issue?

Yes as far as I can tell this seems to be fixed by:
https://github.com/pytorch/pytorch/pull/30486

```
>>> x=torch.randn(100)
>>> x.narrow(0, 0, np.array(3, dtype=np.int64).sum())
tensor([0.3604, 0.8545, 1.5196])
```

**Comment by mruberry** [comment]
Confirmed this passes on master.
