### ISSUE TITLE
Tensorboard documentation in Pytorch 1.3.0 is bare, incomplete.

### ISSUE THREAD

**Issue by Dudly01** [pytorch/pytorch#27717]
The tensorboard documentation for the 1.3.0 release of Pytorch does only contain the "Introductory" part, thus no class or function descriptions are there.

[1.3.0 docs with only introduction](https://pytorch.org/docs/stable/tensorboard.html)
[1.2.0 docs with class and function details](https://pytorch.org/docs/1.2.0/tensorboard.html#)

**Comment by jlin27** [comment]
PR Fix: https://github.com/pytorch/pytorch.github.io/pull/281

**Comment by cpuhrsch** [comment]
Given that the associated PRs are merged I assume this issue to be resolved. Please reopen if this is not the case.
