### ISSUE TITLE
[ONNX] torch.arange with non-integer input

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#27718]
## 🐛 Bug

`torch.arange` accepts non-integer values as input, but exported ONNX model is invalid in ORT

> InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /mnt/output/gr/VehicleModel/deploy/vehicle.onnx failed:This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (280) of operator (ConstantOfShape) in node (__ConstantOfShape_52)  is invalid.

## To Reproduce

Export a module that has this:

```python
In [9]: torch.arange(torch.as_tensor(3).float())
Out[9]: tensor([0., 1., 2.])
```

## Expected behavior

The [ConstantOfShape](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConstantOfShape) node does not specify if input must be integer, but it is valid in PyTorch and result is a floating point array

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] mictorch==0.0.1
[pip] numpy==1.16.4
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] Could not collect

## Additional context

This happens in PyTorch nightly as well

**Comment by garymm** [comment]
@dashesy is this still an issue on the latest PyTorch nightly? If so could you please provide complete repro code that includes the call to torch.onnx.export and everything before it?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
