### ISSUE TITLE
quantizationed model cannot inference with cuda?

### ISSUE THREAD

**Issue by dongfangduoshou123** [pytorch/pytorch#27729]
I see the pytorch1.3 is now available, quantization is added, greate! but as the description：
 '""This currently experimental feature includes support for post-training quantization, dynamic quantization, and quantization-aware training. It leverages the FBGEMM and QNNPACK state-of-the-art quantized kernel back ends, for x86 and ARM CPUs, respectively, which are integrated with PyTorch and now share a common API.
"""

means the quantizationed model can only use the FBGEMM and QNNPACK(cpu backends) and cannot deploy the quantizationed model with cuda backend?
means now all the pytorch's  quantization ops are created just for cpus like arm and x86?

Thank you!

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by gchanan** [comment]
CC @jamesr66a @raghuramank100 

this seems worth at least documenting clearly.

**Comment by jerryzh168** [comment]
That is correct, we don't support cuda currently.

**Comment by dzhulgakov** [comment]
Yes, in 1.3 quantized operations are implemented on cpu only (targeting cpu inference cases). We are looking into cudnn bindings too. The fake quantization in quantization award training supports cuda. We will clarify it in the docs.

@dongfangduoshou123 - just curious about your use case of gpu inference - what type of model you’re looking into and what current solution you’re using today for it.

**Comment by gottbrath** [comment]
yea, we can get a doc change in for this.

**Comment by dongfangduoshou123** [comment]
Because the TensorRT can run the quantized model (8bit 16bit) with cuda cudnn to speed up model, so i think pytorch  should also be possible to do so.

**Comment by gottbrath** [comment]
Thanks @dzhulgakov !

**Comment by anuar12** [comment]
@dzhulgakov 
For example I am using 3D Resnet from torchvision and want to deploy in Xavier. Currently trying with TensorRT but TensorRT is extremely badly documented, has non-intuitive API and has some bugs.

**Comment by gemfield** [comment]
Still not support CUDA on PyTorch 1.7...

**Comment by Force1ess** [comment]
Still not support CUDA on PyTorch 1.10..
Seems like they've already forgot this

**Comment by jerryzh168** [comment]
We do have some prototype with FX Graph Mode Quantization here: https://github.com/pytorch/pytorch/blob/master/torch/fx/experimental/fx2trt/example/quantized_resnet_test.py

**Comment by jonahclarsen** [comment]
Hi there,

I would like to also request this feature, and also ask if there might be another way of solving my problem.

I am making a neural style transfer program in Libtorch that requires CUDA for adequate acceleration. However, it uses VGG-19, which makes the program use about 2-5x more VRAM than is possible within my intended hardware constraints.

If I could use int8 (or better yet, int4), reducing VRAM usage by 4-8x, I could easily have enough VRAM for the program, but as it is, this seems to be an insurmountable hurdle.

If it is a fairly reasonable prospect to add CUDA-accelerated int8/4 quantization, and I could have some support along the way, I might be willing to contribute to adding those features.

Thanks for all your great work on Pytorch!
