### ISSUE TITLE
TypeError: Type torch.LongTensor doesn't implement stateless method mean

### ISSUE THREAD

**Issue by priyankamandikal** [pytorch/pytorch#2772]
```
x = torch.LongTensor(10).random_(10)
x = torch.autograd.Variable(x)
y = torch.mean(x)
```

Error message:
TypeError: Type torch.LongTensor doesn't implement stateless method mean

**Comment by soumith** [comment]
We dont implement `mean` for LongTensor.
You can do: `y=torch.mean(x.float())`

**Comment by Raza25** [comment]
@soumith **_th_round_out is not implemented for type torch.cuda.LongTensor.**
I get this error while trying to quantize my model weigths.
