### ISSUE TITLE
Try torch.nn.quantized.functional.conv2d failed

### ISSUE THREAD

**Issue by Linkeyboard** [pytorch/pytorch#27739]
### Please note that this issue tracker is not a help form and this issue will be closed.

As mentioned in title, I drop the code from documentation of pytorch1.3 and then failed.

RuntimeError: quantized::conv_prepack() Expected a value of type 'List[int]' for argument '_2' but instead found type 'tuple'.

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by gchanan** [comment]
It would be helpful if you listed the code you copied exactly.

**Comment by Linkeyboard** [comment]
I installed pytorch1.3 by conda on linux, cuda10.1. And I tried code from documentation as below.
------------------------------------------------------------------------------------------------------------
from torch.nn.quantized import functional as qF
filters = torch.randn(8, 4, 3, 3, dtype=torch.float)
inputs = torch.randn(1, 4, 5, 5, dtype=torch.float)
bias = torch.randn(4, dtype=torch.float)

scale, zero_point = 1.0, 0
dtype = torch.quint8

q_filters = torch.quantize_per_tensor(filters, scale, zero_point, dtype)
q_inputs = torch.quantize_per_tensor(inputs, scale, zero_point, dtype)
qF.conv2d(q_inputs, q_filters, bias, scale, zero_point, padding=1)
------------------------------------------------------------------------------------------------------------
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: conv2d() got multiple values for argument 'padding'**

Then I changed the last line, and get the other error. 

qF.conv2d(q_inputs, q_filters, bias, scale, zero_point)

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/backup/anaconda3/envs/pytorch1.3/lib/python3.7/site-packages/torch/nn/quantized/functional.py", line 115, in conv2d
    weight, bias, stride, padding, dilation, groups)
RuntimeError: quantized::conv_prepack() Expected a value of type 'List[int]' for argument '_2' but instead found type 'tuple'.
Position: 2
Value: (1.0, 1.0)
Declaration: quantized::conv_prepack(Tensor _0, Tensor? _1, int[] _2, int[] _3, int[] _4, int _5) -> (Tensor _0)**

**Comment by Linkeyboard** [comment]
Finally, it works and thanks for your help!
```
qF.conv2d(q_inputs, q_filters, bias)
```
What's more, the data type of convolutional kernals seems to be quint8, and data type of intput tensor is qint8.
