### ISSUE TITLE
[docs] reorder docs for torch.optim.lr_scheduler.CyclicLR

### ISSUE THREAD

**Issue by Ir1d** [pytorch/pytorch#27730]
## 📚 Documentation

Here: https://pytorch.org/docs/master/optim.html?highlight=cycliclr#torch.optim.lr_scheduler.CyclicLR

![image](https://user-images.githubusercontent.com/10709657/66622721-5f616000-ec1b-11e9-81b2-f0a6b999ee24.png)

the three built-in policies can be illustrated in the Parameter section.

cc @vincentqb

**Comment by vincentqb** [comment]
Similar issue for OneCycle, see [here](https://pytorch.org/docs/master/optim.html#torch.optim.lr_scheduler.OneCycleLR).

**Comment by vincentqb** [comment]
Fixed in #28026
