### ISSUE TITLE
Wrong type in DataLoader interface?

### ISSUE THREAD

**Issue by SteiMi** [pytorch/pytorch#27737]
## 🐛 Bug

There is a problem with the DataLoader class when using type checking with mypy. The documentation says that the arguments `sampler` and `batch_sampler` are optional. However, when I set the argument `sampler=None` mypy reports the error `No overload variant of "DataLoader" matches argument types "TensorDataset", "None"`.

## To Reproduce

Check the following code with mypy:

```
loader = DataLoader(           
            dataset=my_cool_dataset,
            sampler=None
        )
```

This results in the error `No overload variant of "DataLoader" matches argument types "TensorDataset", "None"` (if `my_cool_dataset` is of type "TensorDataset", of course).

## Expected behavior

No error.

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] pytorch-ignite==0.2.0
[pip3] pytorch-lightning==0.5.2.1
[pip3] torch==1.3.0
[pip3] torchvision==0.4.0
[pip3] mypy==0.730
[conda] Could not collect

## Additional context

I believe that there is a mistake in the DataLoader interface. `dataloader.pyi` specifies that the arguments `sampler` and `batch_sampler` have to be of type `Sampler`. It should probably be something like `Optional[Sampler]` or am I wrong?

cc @SsnL @ezyang

**Comment by ezyang** [comment]
@SteiMi That seems reasonable to me. Can you submit a PR?
