### ISSUE TITLE
How to load a saved a model then keep training it?

### ISSUE THREAD

**Issue by ankanch** [pytorch/pytorch#2773]
I have saved my model via `torch.save(cnn4mnist, 'cnn4mnist.pt')`, and load it by `model = torch.load('cnn4mnist.pt')`. Now I want to keep training it . There for I write code like this ::

```
model = torch.load('cnn4mnist.pt')
criterion = nn.MSELoss()
optimizer = optim.SGD(model, lr=0.01)
print(model)
batch_size = 300
cross_vaild = 0.2

epoches = 5
for i in range(epoches):
......
```

The error `TypeError: 'CNN4MNIST' object is not iterable` occured. And I find it was caused by this line `optimizer = optim.SGD(model, lr=0.01)`, my question is how do I get the optimizer of the trained model, or how can I assign a new optimizer to `model`?

**Comment by soumith** [comment]
you simply create a new optimizer.

Also questions like these are better for https://discuss.pytorch.org

**Comment by ankanch** [comment]
I found I haven't use `model.parameters()`.
