### ISSUE TITLE
Tensorboard empty graph

### ISSUE THREAD

**Issue by michaelyyq** [pytorch/pytorch#27736]
## 🐛 Bug

Tensorboard cann't normally show the model graph but images and scalars are normal. 

## To Reproduce

1. I tried the official example about fashionmnist in VISUALIZING MODELS, DATA, AND TRAINING WITH TENSORBOARD. I got empty model graph though the scalars and images was normal.
2. Then I referred to #25599 to deal with the problem, but got empty graph either.
3. After that, I tried Tensorboard official example about mnist,  got normal graph.

## Environment

 - PyTorch 1.2.0:
 - Torchvision 0.4.0a0:
 - Ubuntu16.04:
 - Titan RTX Driver 418.56:
 - CUDA 10.0.130:
 - cuDNN 7.5.1:
 - Tensorboard 2.0.0:
 - Tensorflow 2.0.0-alpha0:

**Comment by jameslahm** [comment]
Please visit #24157
You could install and use pytorch-ngihtly, then it works.

**Comment by albanD** [comment]
Closing given @jameslahm  answer.
