### ISSUE TITLE
The equal function for THCudaBlas_Sgemm in Aten

### ISSUE THREAD

**Issue by shen1994** [pytorch/pytorch#27734]
What is the equal function for THCudaBlas_Sgemm in Aten???Could someone tell me???Thanks~~~

THCudaBlas_Sgemm(state, ‘n’, ‘n’, n, m, k, 1.0f,
THCudaTensor_data(state, columns), n,
THCudaTensor_data(state, weight), k, 1.0f,
THCudaTensor_data(state, output_n), n);

**Comment by gchanan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions.
