### ISSUE TITLE
Named Tensor test_big_tensor_repr requires default dtype to be set

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27753]
## 🐛 Bug

test_big_tensor_repr in test_namedtensor.py seems to required the default tensor dtype to be set to work properly.

When this setting is removed the string is not formatted as expected. 

## To Reproduce

Run the test without setting the default dtype. 

cc @ezyang @gchanan @zou3519

**Comment by gchanan** [comment]
@zou3519 can you take a look?

**Comment by zou3519** [comment]
When one does not set the default dtype, the tensor prints without scientific notation, pushing the names attribute to the new line. I don't know why this is, but the fix is easy.

The test is checking that the tensor repr has `names`, so one approach is to strip all whitespace from the string.

**Comment by gchanan** [comment]
That's weird, I thought the default should only change whether the dtype is printed, not whether it prints in scientific notation or not.  Can you figure out why that is?

**Comment by zou3519** [comment]
> That's weird, I thought the default should only change whether the dtype is printed, not whether it prints in scientific notation or not. Can you figure out why that is?

I think we mis-diagnosed the situation. Changing the default dtype doesn't directly change whether or not a tensor is printed in scientific notation, but it does indirectly affect it. 

Here's how. Depending on the dtype (float vs double), the tensor is generated with different random values. Our printing code prints a tensor with scientific notation or not depending on the values of the tensor. 

I've been able to generate (by setting the manual seed) double tensors that printed in scientific notation and double tensors that do not print in scientific notation.
