### ISSUE TITLE
Easier DDP deadlock detection 

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#27757]
A common (most common) failure mode of DDP is workers deadlocking because of they are out of sync. It would be helpful to have an easier way to troubleshoot this.

IE, recent request 
https://discuss.pytorch.org/t/best-way-to-debug-distributeddataparallel-code/57962

@pietern mentioned something like this is in the works, so opening this issue for bigger visibility

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mrshenli** [comment]
#22071 was the original issue to track the progress
