### ISSUE TITLE
Nvidia cuda documentation link renders wrong

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27769]
Some of our docs link to "CUDA documentation" render incorrectly:

![image](https://user-images.githubusercontent.com/5652049/66680833-414d2d00-ec26-11e9-8347-5da72167ccb5.png)

cc @ezyang @gchanan @zou3519

**Comment by gchanan** [comment]
Seems high priority given it's super easy to fix.

**Comment by zou3519** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/27782
