### ISSUE TITLE
Warnings in the docs build should be errors in CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27765]
I've seen a multitude of warnings in the docs build that reflected incorrect formatting and/or broken docs in the docs build. We should enforce a "no-warnings-allowed" situation for the docs.

cc @ezyang @zou3519

**Comment by gchanan** [comment]
Sounds like a good idea.

**Comment by rgommers** [comment]
Since gh-38011 (duplicate) has the info on the exact Sphinx flags needed, I'll close this issue as a duplicate.
