### ISSUE TITLE
Wait for shutdown message future and check errors in ProcessGroupAgent

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#27777]
## 🚀 Enhancement
Currently, when a future for sending a shutdown message to a process is created in `ProcessGroupAgent`, the message is sent and the future is immediately marked as completed. This means that if there were errors with shutting down on the other process, there is no retry or alerting about this error. We should probably wait for this future and check for errors, and possibly retry or at least make the user aware of the error.

See the discussion on https://github.com/pytorch/pytorch/pull/26336 for more context.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by xush6528** [comment]
I can see the importance of this proposal is avoid hanging at end of training, which would waste great amount of hardware resources.

**Comment by rohan-varma** [comment]
We no longer have a shutdown message so this is irrelevant, it was removed in https://github.com/pytorch/pytorch/pull/30330 in favor for being able to do a local shutdown.
