### ISSUE TITLE
torch.remainder method returning bogus output

### ISSUE THREAD

**Issue by siarez** [pytorch/pytorch#2777]
Is this normal?
```
>>> input1 = torch.LongTensor([[-2, -3], [4, 1]])
>>> divisor = 2
>>> print(torch.remainder(input1, torch.LongTensor(divisor)))

-2.0000e+00 -3.4588e+18
 4.0000e+00 -3.4588e+18
[torch.LongTensor of size 2x2]
```
Also each time you run the command, you get a different result in the second column. Looks like a memory issue.
I'm not sure, but this could be related to #1653

**Comment by albanD** [comment]
I think you meant to use `torch.LongTensor([divisor])`.
With what you did, it creates a tensor of size 2 with unitialized content. Hence giving weird outputs.
