### ISSUE TITLE
torch.random.cuda documentation missing

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27778]
We are missing documentation for:
- cuda.get_rng_state_all
- cuda.set_rng_state_all
- cuda.manual_seed_all
- cuda.seed_all

In torch.random: https://pytorch.org/docs/master/random.html

**Comment by gchanan** [comment]
These aren't used enough to be high priority IMO.

**Comment by ShawnZhong** [comment]
Not sure if anything has changed since this issue, but they seem to exist on https://pytorch.org/docs/master/cuda.html#random-number-generator

**Comment by zou3519** [comment]
We probably added it somewhere down the line. Thanks for the catch, @ShawnZhong.
