### ISSUE TITLE
[quantization] QNNPACK Engine for Dynamic Quantization

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#27793]
We should support QNNPACK for dynamic quantization.

- [ ] RNN classes
- [ ] RNNCell classes
- [ ] Linear

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by raghuramank100** [comment]
Can we list the use-cases where this is needed to help prioritize this work?

**Comment by jamesr66a** [comment]
@supriyar this is a fairly old issue relating to dynamic quant on qnnpack, feel free to close if the work is done

**Comment by supriyar** [comment]
Yeah we do support dynamic quantization on mobile now using qnnpack backend. PR 32479 and 32757 added this.
