### ISSUE TITLE
About async_op = True in all_reduce

### ISSUE THREAD

**Issue by meiluzhu** [pytorch/pytorch#27806]
## ❓ Questions and Help
Questions: How to understand the case about all_reduce with async_op = True?

Here, I know the mode is synchronous if async_op is set to False, that means the worker can continue to run until it receives the gradients from all other workers. But if async_op is True, that means the mode is asynchronous. I cannot understand the asynchronous mode in ring all_reduce. I also didn't find any related information on the internet.
If the worker can continue to run even though it dose not receive the gradients from all other workers, how to guarantee the parameters of all workers are same?

**Comment by gchanan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
