### ISSUE TITLE
The build short_perf_test_gpu is broken on master

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#27817]
## 🐛 Bug

Per title.

Context:

- The break can first be seen at #27635.
- This build was broken by a different issue before #27635. This commit https://github.com/pytorch/pytorch/commit/38a3eabd3eaab37bfda4b84910b318fa3685afd4 is the first to show that issue. Relevant CircleCI: https://circleci.com/gh/pytorch/pytorch/3149226?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console.
- CircleCI output for #27635: https://circleci.com/gh/pytorch/pytorch/3151751?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console
- CircleCI output the last time this build passed: https://circleci.com/gh/pytorch/pytorch/3148592?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console
- None of the PRs from when the build was broken (by the other issue) to when this issue appears obviously relevant (to me, at least). 
- The dependencies changed between the last successful run and the current break (PyTorch 1.2->1.3, CUDA toolkit version, etc.). 
- The other three diffs accepted between when the test was broken by the network issue, and when the actual build break appears in #27635: https://github.com/pytorch/pytorch/commit/829a5c858459277fdbcc507b66d9b0a916457bb1, https://github.com/pytorch/pytorch/commit/9bc8fb8dfdcec945bae7b23dff6c3742f02e648f, https://github.com/pytorch/pytorch/commit/e8087a3060fddbe283735279516e61dd98e5a207

cc @ezyang @gchanan @zou3519

**Comment by yf225** [comment]
It should be fixed by https://github.com/pytorch/pytorch/pull/27797.
