### ISSUE TITLE
DistributedDataParallel consumes much more gpu memory

### ISSUE THREAD

**Issue by turboxin** [pytorch/pytorch#27810]
Would DistributedDataParallel wrapper cost much GPU memory? In my case, the model cost around 7300MB when loaded into a GPU. However, when wrapped in DistributedDataParallel and run in the distributed mode, it costs 22000MB GPU momery.
Is it caused by the DistributedDataParallel wrapper? Are there any methods to save memory usage? Thanks!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by gchanan** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
