### ISSUE TITLE
How to hide latency on libtorch by multithreads? A problem about double stream pipelines execution.

### ISSUE THREAD

**Issue by xiaoLiuxiaoLiuxiaoLiu** [pytorch/pytorch#27827]
Hello, I want to hide latency between data_loader and inference. I simply apply it by OpenMP with a simple double stream pipelines execution. However, the code "auto t=model->forward({Tensor.to(kCUDA)}.toTensor()" don't support multithreads(OpenMP). 

Is there any solution?

My idea is just like Fig. 6 on this website: https://software.intel.com/en-us/articles/heterogeneous-computing-pipelining

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
