### ISSUE TITLE
IterableDataset should be added into dataset.pyi

### ISSUE THREAD

**Issue by Rb-Liu** [pytorch/pytorch#27820]
## 🐛 Bug
trying to import `IterableDataset` in `torch.utils.data.dataset` creates an error in PyCharm. look at the following picture:
![图片](https://user-images.githubusercontent.com/44257865/66712058-9c6b5500-edc9-11e9-9492-64c416939e7b.png)

It says that `cannot find reference in dataset.pyi`, where in `dataset.pyi`, we can see that:
![图片](https://user-images.githubusercontent.com/44257865/66712088-f9670b00-edc9-11e9-9ad4-417bc791c207.png)

It's obviously that there is no `IterableDataset` but only its super class `Dataset` exists.
I believe it should be added.

## To Reproduce

1. Open PyCharm
2. Write `from torch.utils.data.dataset import IterableDataset`
3. Error

## Expected behavior

No unresolved reference hinted.

## Environment
```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Arch Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.15.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 435.21
cuDNN version: /usr/lib/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0a0
[conda] Could not collect
```

## Additional context

cc @SsnL @ezyang

**Comment by SsnL** [comment]
Thanks for reporting! Would you mind submitting a PR to fix this?

**Comment by DuckSoft** [comment]
Pull request submitted! Would you mind have a look at #27966?
@SsnL

**Comment by Legend94rz** [comment]
Still have this problem.
`from .dataset import IterableDataset as IterableDataset` also need to be added into `torch\utils\data\__init__.pyi`

**Comment by DuckSoft** [comment]
ACK. I'll try opening up another pull request to solve this.

**Comment by DuckSoft** [comment]
Pull request opened. Awaiting to be merged.

**Comment by Legend94rz** [comment]
Wait a minute...
There still are some similar problems: `ChainDataset`, `get_worker_info` and `_DatasetKind`.
Just now, I have checked the difference between `torch\utils\data\__init__.pyi` and `torch\utils\data\__init__.py`. These three:  `ChainDataset`, `get_worker_info` and `_DatasetKind` are imported in `__init__.py`, but not in `__init__.pyi`.  
Are they should also be added into  `__init__.pyi`?
@DuckSoft

**Comment by DuckSoft** [comment]
Maybe we need an official answer, then. I am confused.

**Comment by DuckSoft** [comment]
> Wait a minute...
> There still are some similar problems: `ChainDataset`, `get_worker_info` and `_DatasetKind`.
> Just now, I have checked the difference between `torch\utils\data\__init__.pyi` and `torch\utils\data\__init__.py`. These three: `ChainDataset`, `get_worker_info` and `_DatasetKind` are imported in `__init__.py`, but not in `__init__.pyi`.
> Should they also be added into `__init__.pyi`?
> @DuckSoft

We got the official answers! I will put `ChainDataset`, `get_worker_info` in!

**Comment by zhangruiskyline** [comment]
Hi, I am using the pytorch-nightly in our requirements.txt, but still have same issue `IterableDataset should be added into dataset.pyi`, can I know what is correct pytorch version I need to have this PR?

**Comment by k998** [comment]
I am getting this error. Pytorch version 1.9

cannot import name 'IterableDataset' from 'torch.utils.data' (/home/ubuntu/miniconda3/envs/fastai/lib/python3.7/site-packages/torch/utils/data/__init__.py)
