### ISSUE TITLE
a rename_file optional argument for torch.hub.load_state_dict_from_url

### ISSUE THREAD

**Issue by svenkreiss** [pytorch/pytorch#27830]
## 🚀 Feature
Add an optional keyword argument `rename_file=None` to specify the downloaded file's name.

## Motivation

My university's file hosting provider switch.ch allows for public download urls, but their path always ends with `.../download` making the name of all my model files just `download` which is a conflict.

## Pitch

Avoid file name clashes for model downloads.

## Alternatives

* Google drive does not support unauthenticated public urls.
* Support for distributed file sharing systems (IPFS, ...) more difficult.
* I currently monkey patch the function. The only line changed is `filename = os.path.basename(parts.path) if rename_file is None else rename_file`.

cc @ailzhang @SsnL

**Comment by soumith** [comment]
I remember @ailzhang added Google Drive support (but it looks reverted) at some point, and that's achievable.

**Comment by ailzhang** [comment]
@svenkreiss Is https://pytorch.org/docs/master/hub.html#torch.hub.download_url_to_file good for your case? 
In that API we allow renaming and you can directly `torch.load('<renamed_file>')` right after it which is essentially `load_state_dict_from_url`. 

I personally feel it's more clear than adding a kwarg to `load_state_dict_from_url` as it gives more control. But feel free to let me know if that doesn't solve your problem.

**Comment by ailzhang** [comment]
@soumith Hmm I haven't tried adding Google Drive yet, but yea it's achievable with some tweaks (to avoid adding additional dependency for PyTorch). 
I'm not sure how useful it'll be tho. If users would like `torch.hub.download_url_to_file` and `torch.hub.load_state_dict_from_url ` to handle Google drive url, maybe thumb-up this comment?

**Comment by soumith** [comment]
kinda agree with ailing here

**Comment by svenkreiss** [comment]
Thank you all for looking into this. Very much appreciated.

@ailzhang I can use `download_url_to_file` followed by `torch.load`, but that is not all I need. `load_state_dict_from_url` also determines the checkpoint directory and makes sure it exists. Effectively, I need to make my own `load_state_dict_from_url`. I am fine putting a custom `load_state_dict_from_url` in [openpifpaf](https://github.com/vita-epfl/openpifpaf). 

Btw, this is the url to my checkpoint: https://drive.switch.ch/index.php/s/SveBDXZBvVyl8cX/download

With respect to Google Drive: I am not sure, but it might rate limit the downloads to my continuous tests. It downloads the models fairly often, which is why I am looking for a cheaper solution.

**Comment by ailzhang** [comment]
@svenkreiss yea I agree that a slightly customized `load_state_dict_from_url` might work better for your case. Btw for the checkpoint directory, I wonder whether it helps if we have a public API to expose the hub dir? Similar to `torch.hub.set_dir()` but the getter version of it. Let me know if that helps. :D 
Btw for the checkpoint downloading, since yours is pretty small ~30MB, making it a release attachment of a github release could save you from the google drive api calls and rate limiting. 
From doc: 
"If less than 2GB, it’s recommended to attach it to a project release and use the url from the release. " you can find an example here https://github.com/ailzhang/torchhub_example/releases. ;)

**Comment by svenkreiss** [comment]
@ailzhang Thank you! I did not know about Github's release assets and their lenient file size policy. I publish a few more backbones for OpenPifPaf, so it's not just one 30MB file, but also 230MB, etc but none is larger than 2GB. For me, that is the best solution:
<img width="828" alt="Screen Shot 2019-10-17 at 08 55 22" src="https://user-images.githubusercontent.com/2775078/66985069-4f82c980-f0bc-11e9-90f3-b66c46f3d9a6.png">

Regarding the exposure of the `hub.set_dir()`, I do not think that would have helped me. All the files from this other cloud service are called "download" and I want to be able to handle multiple models (multiple backbones) simultaneously.

For me, the issue is solved, so I am closing it. Thanks for all your work for PyTorch!
