### ISSUE TITLE
Install from source on Centos7 doesn't work

### ISSUE THREAD

**Issue by ryul99** [pytorch/pytorch#27833]
## To Reproduce

1. `conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing` and `conda install -c pytorch magma-cuda`
1. `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
1. `python setup.py install`

Error message
```
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/all_gather.dep] Error 1
make[2]: *** Waiting for unfinished jobs....
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/all_reduce.dep] Error 1
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/broadcast.dep] Error 1
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/reduce.dep] Error 1
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/reduce_scatter.dep] Error 1
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/functions.dep] Error 1
make[2]: Leaving directory `/home/minds/ryul99/pytorch/third_party/nccl/nccl/src/collectives/device'
make[1]: *** [/home/minds/ryul99/pytorch/build/nccl/obj/collectives/device/colldevice.a] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/minds/ryul99/pytorch/third_party/nccl/nccl/src'
make: *** [src.build] Error 2
[69/3311] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_message.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 759, in <module>
    build_deps()
  File "setup.py", line 311, in build_deps
    cmake=cmake)
  File "/home/minds/ryul99/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/home/minds/ryul99/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/home/minds/ryul99/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/minds/anaconda3/envs/waveglow-test-build/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.
```

## Expected behavior
Being Installed

## Environment
```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB

Nvidia driver version: 418.87.00
cuDNN version: /usr/local/cuda-10.0/lib64/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.17.2
[conda] blas                      1.0                         mkl  
[conda] magma-cuda100             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0
```
## Additional context

my PATH contains `/usr/local/cuda-10.0/bin:/usr/local/cuda/bin` and my LD_LIBRARY_PATH contains `/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib:/usr/local/cuda/lib64:/usr/local/cuda-10.0/lib64:`
I think there is some problem with loading cuda_runtime.h which is existing in `/usr/local/cuda-10.0/include`
I have no idea that this is a bug or my fault...

**Comment by vincentqb** [comment]
Have you tried the following?
* `python setup.py clean --all` before compiling
* creating a new conda environment to compile in, using `conda create -n pytorch python=3.6` and `conda activate pytorch`
* compiling without CUDA: `NO_CUDA=1 python setup.py install`
* making sure you are on the lastest master commit

**Comment by ryul99** [comment]
I tried the following:
1. `python setup.py clean --all`
1. creating a new conda env with python 3.6
1. `conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing` and `conda install -c pytorch magma-cuda100`
1. `git pull` , `git submodule sync` and `git submodule update --init --recursive`
1. `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
1. `python setup.py install`

but I have the same problem.. :(

`NO_CUDA=1 python setup.py install` works for me but I want my PyTorch build supports CUDA.
Which does `NO_CUDA=1` option mean, only compiling doesn't use CUDA(Built PyTorch supports CUDA) or compiling doesn't use CUDA neither does the result of the build(Built PyTorch doesn't support CUDA)?

**Comment by ryul99** [comment]
I face another problem but I solved this problem with adding `export CPLUS_INCLUDE_PATH=/usr/local/cuda-10.0/include:$CPLUS_INCLUDE_PATH C_INCLUDE_PATH=/usr/local/cuda-10.0/include:$C_INCLUDE_PATH` to .bashrc

**Comment by albanD** [comment]
You want to make sure that CUDA is properly detected in the first phase of the compilation. Otherwise, make sure it will be found with `CUDA_HOME` or by adding a simlink from `/usr/local/cuda` to your current version.

**Comment by ryul99** [comment]
My sever have `CUDA_HOME` and simlink from `/usr/local/cuda` properly. I solve this issue by adding this code snippet to bashrc.
```
export CPLUS_INCLUDE_PATH=/usr/local/cuda-10.0/include:$CPLUS_INCLUDE_PATH C_INCLUDE_PATH=/usr/local/cuda-10.0/include:$C_INCLUDE_PATH
export LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64:/usr/local/cuda-10.0/lib:/usr/local/cuda-10.0/lib64:$LIBRARY_PATH
```
Also I set shell variable `USE_NINJA=OFF`.(`export USE_NINJA=OFF` on command line)(ref: https://github.com/pytorch/pytorch/issues/13061)
I could build PyTorch in Ubuntu server without these setting. I think there is some difference between Ubuntu gcc and Centos gcc.
