### ISSUE TITLE
Fix type hints for named tensor

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27846]
## 🐛 Bug

Named tensors are currently excluded from the type hints test: https://github.com/pytorch/pytorch/blob/73521a03168e7ab792d76266d980b060cb60c69f/test/test_type_hints.py#L66-L71. At a high level, the type hints test (1) pulls all named tensor documentation examples and (2) runs mypy on them. Those currently fail for me locally.

## To Reproduce

Delete the named tensor APIs from the blacklist. Run `python test/test_type_hints.py`. See test failures.

## Expected behavior

Named tensors should work with type hints.

cc @zou3519 @ezyang

**Comment by physicsrob** [comment]
This should be closed, I think.

**Comment by zou3519** [comment]
Closed by https://github.com/pytorch/pytorch/pull/36890, thanks @physicsrob!
