### ISSUE TITLE
Incorrect named tensor example

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#27848]
https://pytorch.org/docs/stable/named_tensor.html#explicit-alignment-by-names

```
scale = torch.randn(num_channels, names='C')
```
should be `scale = torch.randn(num_channels, names=['C'])`

cc @zou3519

**Comment by zou3519** [comment]
Fixed by @standbyme  in #27828 (thank you!)

**Comment by standbyme** [comment]
: )
