### ISSUE TITLE
Location of _VF.gru implementation.

### ISSUE THREAD

**Issue by manikanthr5** [pytorch/pytorch#27845]
## _VF.gru implementation Location

I am currently working on a project which needs me to model GRU Cell hidden cell state after every time step to include someway to include the time difference between the input sequences. I went through the code and found [_VF.gru](https://github.com/pytorch/pytorch/blob/19df7e7e84c1328a0661c267835e1c922a6d90f7/torch/nn/modules/rnn.py#L690) call very confusing. I found the [gru_cell](https://github.com/pytorch/pytorch/blob/19df7e7e84c1328a0661c267835e1c922a6d90f7/benchmarks/fastrnns/cells.py#L96) implementation but didn't find where it is being called. So I would like to request, if someone could help me understand how _VF works and where can I find the _VF.gru implementation code. 

Thank you.

**Comment by soumith** [comment]
it's somewhere deep in this file: https://github.com/pytorch/pytorch/blob/90ffab6e3713a40f47f4c9d3d3b16d56e83f97c4/aten/src/ATen/native/RNN.cpp#L956

_VF.py routes in a complicated way to our aten:: C++ implementations of the said operators.

**Comment by yipliu** [comment]
Hi @manikanthr5, do you know what function _VF has on earth?

**Comment by GRfade** [comment]
> 它在这个文件的某个深处：
> 
> https://github.com/pytorch/pytorch/blob/90ffab6e3713a40f47f4c9d3d3b16d56e83f97c4/aten/src/ATen/native/RNN.cpp#L956
> 
> _VF.py 以一种复杂的方式路由到我们的 aten:: 上述运算符的 C++ 实现。

我在本地的pytorch没有找到该文件，请问该文件在本地的哪个地方*（只找到.h文件）

**Comment by tahseen52** [comment]
> it's somewhere deep in this file:
> 
> https://github.com/pytorch/pytorch/blob/90ffab6e3713a40f47f4c9d3d3b16d56e83f97c4/aten/src/ATen/native/RNN.cpp#L956
> 
> _VF.py routes in a complicated way to our aten:: C++ implementations of the said operators.

i am working on a similar project, where i need to change the Activation Function Of NewGate in GRU cell, i changed the struct GRUCell in aten/src/ATen/native/RNN.cpp, but on testing i observed that it was only working on CPU not CUDA, then i inserted the print statements in the function inside the struct one in an if-statement where it was checking either the input.is_cuda() is true, and one outside of that if. On CPU, the print was being executed but on CUDA, i didn't get any output from print statements. So can you please tell me where is the exact CUDA implementation of GRU Cell located ?
