### ISSUE TITLE
Model with interpolate or pixel_shuffle produces invalid ONNX output

### ISSUE THREAD

**Issue by oliver-batchelor** [pytorch/pytorch#27841]
## 🐛 Bug

The model below when exported by pytorch doesn't pass the onnx validation. Replacing interpolate with pixel shuffle also causes the same issue. Pytorch 1.3, onnx 1.6

```
Traceback (most recent call last):
  File "test.py", line 59, in <module>
    onnx.checker.check_model(model)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/onnx/checker.py", line 94, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec: input: "input" output: "1" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "value" f: 0 type: FLOAT }

```

## To Reproduce
```

from torch import nn
import torch.nn.functional as F
import onnx
import torch
import torch.onnx

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):

        x = F.avg_pool2d(input, 2, ceil_mode=True)  
        upscaled = F.interpolate(x, scale_factor=2)
        return  torch.cat([input, upscaled], dim=1)

model = MyModel()

dummy = torch.ones((1, 64, 50, 50))
out = model(dummy)
torch.onnx.export(model,               # model being run
                  dummy,                         # model input (or a tuple for multiple inputs)
                  "model.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,  # wether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input':{0:'batch'}})


model = onnx.load("model.onnx")
onnx.checker.check_model(model)
onnx.helper.printable_graph(model.graph)

```

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 418.87.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] pytorch-tools==0.1
[pip] pytorchcv==0.0.50
[pip] torch==1.3.0
[pip] torch2trt==0.0.1
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-tools             0.1                       dev_0    <develop>
[conda] pytorchcv                 0.0.50                   pypi_0    pypi
[conda] torch2trt                 0.0.1                    pypi_0    pypi
[conda] torchvision               0.4.1                py37_cu100    pytorch

**Comment by saulzar** [comment]
This simpler net gives the same error, apparently.

```
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        x = F.avg_pool2d(input, 2)
        y = F.avg_pool2d(input, 2)
        return x + y
```

**Comment by saulzar** [comment]
Seems like this is an onnx issue which has been fixed but not released yet.
https://github.com/onnx/onnx/issues/1655

**Comment by saulzar** [comment]
Still has the same behaviour with latest github onnx, not convinced it's the same problem.

**Comment by saulzar** [comment]
Even this doesn't work:

`model = nn.AvgPool2d(2)`

onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

`==> Context: Bad node spec: input: "input" output: "1" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "value" f: 0 type: FLOAT }`

**Comment by saulzar** [comment]
This only seems to happen with opset_version=11

**Comment by rainker89** [comment]
found the same err on opest_version=11

**Comment by aviaisr** [comment]
I think I have the same issue. 

I exported a pytorch model to onnx, then I loaded the onnx, called "prepare" (from onnx_tf.backend) in order to later export the model to pb.

I see that the model is not passing the validation check done by the onnx checker:

 File "C:/CP/DL_REPOSITORIES/pytorch-onnx-tensorflow-pb/avia_convertPyTorchToOnnx.py", line 32, in run
    tf_rep = prepare(model_onnx, opset_version=10)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 53, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx\backend\base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx\checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec: input: "708" output: "715" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "value" f: 0 type: FLOAT }

Working with 
pytorch version 1.3.1 and onnx version 1.6.0

**Comment by cong235** [comment]
@aviaisr Try to use pytorch 1.2 and onnx 1.5

**Comment by garymm** [comment]
Original code reported by @oliver-batchelor works on PyTorch 1.10.0.
