### ISSUE TITLE
segmentation fault on large SVD in CUDA

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#2790]
failure case:

```
import torch

x = torch.zeros(300, 100001).cuda();
u, s, v = torch.svd(x, some=True);
print(u);
```

Context: https://discuss.pytorch.org/t/segmentation-fault-for-svd-implementation-in-gpu-for-large-matrices/7557/4

**Comment by zou3519** [comment]
Looking into this. I think it's an integer overflow somewhere
