### ISSUE TITLE
RRefs can leak when joining workers

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#27928]
## 🐛 Bug / Enhancement

In distributed training, if `rpc.join_rpc()` is called when the locally created rrefs are not garbage collected, this can result in leakage errors. See the example script below to reproduce.

## To Reproduce
1. Run the following script
```
import os
import time
from datetime import timedelta
import torch
import torch.distributed as dist
from torch.multiprocessing import Process
import torch.distributed.rpc as rpc

def run(rank, size):
    if rank == 1:
        rref1, rref2 = rpc.remote("worker0", torch.add, args=(torch.ones(2,2),1)), rpc.remote("worker0", torch.add, args=(torch.zeros(2,2), 3))
        x = rref1.to_here() + rref2.to_here()
        print(x)
    rpc.join_rpc() # comment this and uncomment in init_process to remove error

def init_process(rank, size, fn, backend='gloo'):
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29509'
    dist.init_process_group(backend, rank=rank, world_size=size, timeout=timedelta(seconds=12))
    rpc.init_model_parallel("worker{}".format(rank))
    fn(rank, size)
   #  rpc.join_rpc()

if __name__ == "__main__":
    size = 2
    processes = []
    for rank in range(size):
        p = Process(target=init_process, args=(rank, size, run))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()
```

Results in the error:
```
RuntimeError: Leaking RRef GloballyUniqueId(1, 1) with fork Id GloballyUniqueId(1, 0)
Leaking RRef GloballyUniqueId(1, 3) with fork Id GloballyUniqueId(1, 2)
 (checkRRefLeaks at ../torch/csrc/distributed/rpc/rref_context.cpp:48)
```

## Expected behavior

Open for discussion, but I don't think we should have a user error here. The script above can be fixed by running `join_rpc()` after the rrefs are garbage collected (such as in the parent function), but this does not seem robust. In particular, there are no real guarantees (AFAIK) of when exactly the garbage collection will happen and the user can use `gc` to modify this. Should we provide a way for the user to say they are done using the rref?

A few ideas are: stop holding the remote ref once `to_here` is called (this makes sense to me, since the user now has the value locally), or use a context manager that wraps `init_model_parallel` and `join_rpc` to garbage collect everything that is needed.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mrshenli** [comment]
Yes, it will get tricker if there are circular dependencies (#27096). Is it OK that after join (everyone agrees to terminate), all owners clear their RRefs? 

cc @aazzolini @xush6528

**Comment by pritamdamania87** [comment]
@mrshenli Why do we need to explicitly destroy the RRefContext? Wouldn't the singleton automatically be garbage collected when the program exits?

**Comment by rohan-varma** [comment]
@mrshenli Can we close this considering we can ignore leak detection and instead print a warning? Or leave it open until we come up with a solution for the underlying issue?

**Comment by mrshenli** [comment]
@rohan-varma  I think we can close this now, as it is an expected behavior without `ignore_leak`. As a more fundamental solution, @xush6528 started tackling this in #31893 by nuking user UserRRefs by tracking them in RRefContext
