### ISSUE TITLE
Some of the quantized functions lack documentation

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#27938]
## 📚 Documentation

For example: https://pytorch.org/docs/stable/quantization.html#torch-nn-quantized-functional

![Screen Shot 2019-10-14 at 2 34 10 PM](https://user-images.githubusercontent.com/4216323/66784641-ec145400-ee8f-11e9-8404-3717bad82df8.png)

This also includes #27849

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by gottbrath** [comment]
Zafar, I think I see what to do for this. Do you mind if I take a stab?

**Comment by gottbrath** [comment]
also .. curious why the test that is supposed to measure doc coverage didn't catch this omission.

**Comment by z-a-f** [comment]
Removed myself

**Comment by gottbrath** [comment]
working on this again today.

**Comment by gottbrath** [comment]
I have a fix for the actual bug. I have created a separate issue for the testing omission and have self assigned that.

**Comment by gottbrath** [comment]
![pt-i27938-more-gaps](https://user-images.githubusercontent.com/45861273/69389383-b62d7100-0c80-11ea-87bf-6d3b376eb84a.png)

looks like there are a few more missing: slice, ReLU and ReLU_

**Comment by gottbrath** [comment]
![pt-i27938-fixed](https://user-images.githubusercontent.com/45861273/69391820-cd705c80-0c88-11ea-85f3-dfa31ea08337.png)


fixed these last few as well.

**Comment by gottbrath** [comment]
landed on master
