### ISSUE TITLE
Cholesky Error for positive definite matrix

### ISSUE THREAD

**Issue by nazanint** [pytorch/pytorch#27944]
## 🐛 Bug

All eigenvalues of the tensor below is positive but we still get a cholesky error:

a = tensor([[ 2.0409e-01,  1.5395e-01,  7.7433e-02,  1.9877e-02, -3.3970e-03,
         -5.2508e-03, -1.8392e-03,  3.6019e-05,  2.3410e-04, -2.0681e-05,
         -1.8481e-04, -2.5390e-04, -2.8913e-04, -2.7244e-04, -1.8783e-04,
         -7.9907e-05, -8.9461e-06,  9.9558e-06,  2.9799e-06, -3.9881e-06],
        [ 1.5395e-01,  1.7431e-01,  1.3897e-01,  7.3620e-02,  2.0601e-02,
         -2.3384e-03, -4.9653e-03, -2.0447e-03, -2.3743e-04,  8.5844e-05,
         -5.7856e-05, -1.7992e-04, -2.1048e-04, -1.7147e-04, -9.4763e-05,
         -2.0365e-05,  2.2208e-05,  3.0575e-05,  2.1444e-05,  1.0530e-05],
        [ 7.7432e-02,  1.3897e-01,  1.6680e-01,  1.3712e-01,  7.4065e-02,
          2.1136e-02, -2.3331e-03, -5.2997e-03, -2.3951e-03, -4.6132e-04,
         -6.5253e-05, -2.1579e-04, -3.3798e-04, -3.2708e-04, -2.4216e-04,
         -1.4449e-04, -6.7183e-05, -2.0918e-05, -6.7753e-07,  4.5134e-06],
        [ 1.9865e-02,  7.3599e-02,  1.3711e-01,  1.6647e-01,  1.3740e-01,
          7.4248e-02,  2.0991e-02, -2.6565e-03, -5.5567e-03, -2.5107e-03,
         -5.2632e-04, -1.4475e-04, -2.8568e-04, -3.7808e-04, -3.5446e-04,
         -2.6274e-04, -1.4573e-04, -4.8609e-05,  1.5383e-06,  1.2457e-05],
        [-3.4235e-03,  2.0559e-02,  7.4051e-02,  1.3742e-01,  1.6667e-01,
          1.3740e-01,  7.4015e-02,  2.0716e-02, -2.7752e-03, -5.5358e-03,
         -2.4957e-03, -5.8090e-04, -2.3744e-04, -3.8597e-04, -4.5821e-04,
         -3.7077e-04, -2.0463e-04, -5.8087e-05,  1.7243e-05,  3.0526e-05],
        [-5.2723e-03, -2.3519e-03,  2.1201e-02,  7.4373e-02,  1.3751e-01,
          1.6653e-01,  1.3711e-01,  7.3856e-02,  2.0853e-02, -2.4545e-03,
         -5.2446e-03, -2.3245e-03, -5.1926e-04, -2.5819e-04, -4.2973e-04,
         -4.4495e-04, -2.8258e-04, -1.0114e-04,  1.2336e-06,  2.6831e-05],
        [-1.8071e-03, -4.8599e-03, -2.0758e-03,  2.1332e-02,  7.4314e-02,
          1.3726e-01,  1.6630e-01,  1.3722e-01,  7.4389e-02,  2.1564e-02,
         -1.8478e-03, -4.8593e-03, -2.1563e-03, -5.0614e-04, -2.7962e-04,
         -3.7248e-04, -2.9979e-04, -1.2944e-04, -8.3191e-06,  2.9864e-05],
        [ 1.6122e-04, -1.7730e-03, -4.8191e-03, -2.1007e-03,  2.1173e-02,
          7.4103e-02,  1.3728e-01,  1.6678e-01,  1.3807e-01,  7.5265e-02,
          2.2227e-02, -1.4579e-03, -4.7218e-03, -2.1941e-03, -5.6678e-04,
         -2.3098e-04, -2.1055e-04, -1.2078e-04, -1.5579e-05,  3.1188e-05],
        [ 4.3878e-04,  1.3426e-04, -1.8028e-03, -4.9219e-03, -2.2757e-03,
          2.1101e-02,  7.4381e-02,  1.3794e-01,  1.6755e-01,  1.3866e-01,
          7.5606e-02,  2.2359e-02, -1.5284e-03, -4.9213e-03, -2.3361e-03,
         -5.0832e-04, -3.9903e-06,  3.7498e-05,  3.3931e-05,  3.3802e-05],
        [ 2.1321e-04,  4.3376e-04,  7.6728e-05, -1.9552e-03, -5.0943e-03,
         -2.2638e-03,  2.1418e-02,  7.4832e-02,  1.3822e-01,  1.6760e-01,
          1.3859e-01,  7.5453e-02,  2.2022e-02, -1.9711e-03, -5.2025e-03,
         -2.2856e-03, -2.1351e-04,  3.1417e-04,  2.2606e-04,  8.3026e-05],
        [ 5.4825e-05,  2.0558e-04,  3.3863e-04, -1.2352e-04, -2.1604e-03,
         -5.1484e-03, -2.1752e-03,  2.1422e-02,  7.4615e-02,  1.3794e-01,
          1.6740e-01,  1.3832e-01,  7.4898e-02,  2.1350e-02, -2.3749e-03,
         -5.1695e-03, -1.9825e-03,  8.8732e-05,  4.6714e-04,  2.4341e-04],
        [ 1.1634e-05,  2.6059e-05,  8.5153e-05,  1.2060e-04, -3.6648e-04,
         -2.3579e-03, -5.3639e-03, -2.5267e-03,  2.1018e-02,  7.4393e-02,
          1.3787e-01,  1.6712e-01,  1.3764e-01,  7.4154e-02,  2.0976e-02,
         -2.3124e-03, -4.9241e-03, -1.7961e-03,  1.4904e-04,  4.5556e-04],
        [ 8.7360e-06, -2.6875e-05, -8.0557e-05, -9.5953e-05, -1.1387e-04,
         -6.5548e-04, -2.7400e-03, -5.7942e-03, -2.7954e-03,  2.1049e-02,
          7.4485e-02,  1.3762e-01,  1.6651e-01,  1.3710e-01,  7.4004e-02,
          2.1101e-02, -2.1938e-03, -4.9228e-03, -1.8460e-03,  1.3211e-04],
        [ 6.7673e-06, -2.0570e-05, -9.2745e-05, -1.9542e-04, -2.7634e-04,
         -3.8425e-04, -9.9448e-04, -3.0011e-03, -5.7793e-03, -2.5158e-03,
          2.1276e-02,  7.4375e-02,  1.3730e-01,  1.6635e-01,  1.3722e-01,
          7.4157e-02,  2.1081e-02, -2.3419e-03, -5.0522e-03, -1.8983e-03],
        [ 2.3338e-06, -6.1210e-06, -4.9437e-05, -1.5306e-04, -3.0856e-04,
         -4.4658e-04, -5.4203e-04, -9.8171e-04, -2.7021e-03, -5.3016e-03,
         -2.1470e-03,  2.1372e-02,  7.4348e-02,  1.3739e-01,  1.6654e-01,
          1.3731e-01,  7.4050e-02,  2.0869e-02, -2.5971e-03, -5.3984e-03],
        [ 2.9377e-07,  1.8234e-06, -1.4780e-05, -7.7742e-05, -2.0627e-04,
         -3.6217e-04, -4.1839e-04, -3.1445e-04, -5.1330e-04, -2.1277e-03,
         -4.8574e-03, -1.9536e-03,  2.1411e-02,  7.4388e-02,  1.3744e-01,
          1.6652e-01,  1.3718e-01,  7.3814e-02,  2.0375e-02, -3.5302e-03],
        [ 1.3459e-06,  5.0370e-06,  1.1999e-06, -2.4900e-05, -8.7991e-05,
         -1.8228e-04, -2.4041e-04, -1.3166e-04,  1.3862e-04, -1.4484e-05,
         -1.7712e-03, -4.7481e-03, -2.0293e-03,  2.1287e-02,  7.4278e-02,
          1.3733e-01,  1.6640e-01,  1.3704e-01,  7.3534e-02,  1.9811e-02],
        [ 2.8462e-06,  5.8879e-06,  6.0719e-06, -4.0789e-07, -1.6568e-05,
         -4.3963e-05, -6.8210e-05, -2.8441e-05,  1.6407e-04,  4.3055e-04,
          1.4781e-04, -1.7988e-03, -4.9007e-03, -2.1984e-03,  2.1118e-02,
          7.4050e-02,  1.3716e-01,  1.6685e-01,  1.3899e-01,  7.7423e-02],
        [ 2.9190e-06,  4.8015e-06,  5.3531e-06,  4.9424e-06,  6.3847e-06,
          1.0953e-05,  1.6470e-05,  2.9986e-05,  9.0384e-05,  2.5301e-04,
          4.3306e-04,  6.4163e-05, -1.8973e-03, -4.9809e-03, -2.4064e-03,
          2.0591e-02,  7.3682e-02,  1.3905e-01,  1.7435e-01,  1.5396e-01],
        [ 1.8518e-06,  2.6703e-06,  2.5384e-06,  2.1957e-06,  4.8702e-06,
          1.3878e-05,  2.7513e-05,  3.7570e-05,  4.1314e-05,  7.0201e-05,
          1.9520e-04,  3.7839e-04,  7.5187e-05, -1.8795e-03, -5.2965e-03,
         -3.3952e-03,  1.9921e-02,  7.7483e-02,  1.5398e-01,  2.0410e-01]])
## To Reproduce

1. try printing: torch.eig(a), to see they're all positive
2. try torch.cholesky(a) and it'd be negative.

## Expected behavior

Cholesky of a positive definite matrix shouldn't run into an error.

## Environment

Please copy and paste the output from our
Happens in latest pytorch

**Comment by vishwakftw** [comment]
Hi @nazanint, `torch.cholesky` requires that the matrix is symmetric, and it seems that the matrix that you have provided isn't.

**Comment by gtamba** [comment]
@vishwakftw , (a - a.T) does give a matrix that is almost zero, I believe the real issue here is the condition number of the tensor provided is really high which makes it unstable for numeric computation 

`print(np.linalg.cond(a.numpy()))`  => 517008.34 which is really high

**Comment by vishwakftw** [comment]
@gtamba we require an exact equality. I got:
```
>>> torch.allclose(a, a.T)
False
```

**Comment by vishwakftw** [comment]
FYI, Cholesky algorithms work independent of condition number, as long as the input is symmetric and positive definite.

**Comment by gtamba** [comment]
@vishwakftw : thanks for confirming that, just for my curiosity, where could I find the source of .cholesky() ? 
```
RuntimeError: cholesky_cpu: U(9,9) is zero, singular U.
```

@nazanint: I don't know if conditioning numbers carry over in operations, but maybe a poor conditioning number of the input that was supposed to generate a symmetric matrix caused this loss of precision. (since you expected it to be positive-definite)
