### ISSUE TITLE
'torch.onnx' do not support ' torch.where' , 'torch.nonzero' and 'torch.masked_selected' operators?

### ISSUE THREAD

**Issue by wangguojun2018** [pytorch/pytorch#27959]
## 🐛 Bug

the 'torch.masked_select' are used in my model, when I convert to onnx with 'torch.onnx.export' the error is
```
KeyError: 'masked_select'
```
when I use 'torch.where' to replace 'torch.masked_select', the error is
```
TypeError: where() missing 2 required positional arguments: 'self' and 'other' (occurred when translating where)
```
when I use 'torch.nonzero' to replace 'torch.masked_select', the error is
```
KeyError: 'nonzero_numpy'
```
But, I see 'torch.nonzero' and 'torch.where' are support in [official documentaments](https://pytorch.org/docs/stable/onnx.html)
## To Reproduce

1.run the following source code to reproduce the behavior
```
import torch
# import onnx
import torch.onnx
import torch.nn as nn
import torch.nn.functional as F

class mymodel(nn.Module):
    def __init__(self,
                 in_channels,
                 out_channels,
                 use_norm=True,):

        super().__init__()
        self.name = 'PFNLayer'
        # self.units = out_channels
        # self.batchnorm1d=nn.BatchNorm1d(eps=1e-3,momentum=0.01)
        self.linear = nn.Linear(in_channels, out_channels)
        self.norm = nn.BatchNorm1d(out_channels,eps=1e-3,momentum=0.01)

    def forward(self, inputs):
        if inputs.shape[0]>65000:
            inputs1,inputs2,inputs3=torch.chunk(inputs,3,dim=0)
            x1=self.linear(inputs1)
            x2 = self.linear(inputs2)
            x3 = self.linear(inputs3)
            x=torch.cat([x1,x2,x3],dim=0)
        else:
            x=self.linear(inputs)
        x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
                                                               1).contiguous()
        x = F.relu(x)

        x_max = torch.max(x, dim=1, keepdim=True)[0]

        x_repeat = x_max.repeat(1, inputs.shape[1], 1)
        x_concatenated = torch.cat([x, x_repeat], dim=2)
        # masked=x_concatenated>5
        idx=torch.where(x_concatenated>5)[0]
        # idx=torch.nonzero(x_concatenated>5,as_tuple=True)[0]
        x_concatenated=x_concatenated[idx]
        # x_concatenated=x_concatenated.masked_select(masked)
        return x_concatenated



if __name__=="__main__":
    inputs=torch.randn((5000,100,30),dtype=torch.float)
    net=mymodel(30,9)
    torch.onnx.export(net,(inputs,),'onnx_test',verbose=True)
```

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX
GPU 4: TITAN RTX
GPU 5: TITAN RTX
GPU 6: TITAN RTX
GPU 7: TITAN RTX

Nvidia driver version: 410.93
cuDNN version: /usr/local/cuda-10.0/lib64/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2019.4                      243    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.0.2            py36h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.14           py36ha843d7b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.0.2            py36hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.3.0           py3.6_cuda10.0.130_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.4.1                py36_cu100    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

**Comment by hchong-ml** [comment]
Any updates on this? Facing the same issue.

**Comment by neonrights** [comment]
Same, I get the same `KeyError` when trying to use torch.nonzero

**Comment by rivergold** [comment]
I meet the same problem, upgrading PyTorch to 1.7.1 and using ONNX with opset_version=11 solve this error.

**Comment by garymm** [comment]
Code from originaly issue by @wangguojun2018 works as expected on PyTorch 1.10.0.
