### ISSUE TITLE
torch.det incorrectly handles 0x0 matrix

### ISSUE THREAD

**Issue by surgan12** [pytorch/pytorch#27973]
According to [https://math.stackexchange.com/questions/1913141/is-the-0x0-matrix-zero-times-zero-matrix-a-well-defined-concept](url), the determinant of the zero space should be 1 wheras current **det** implementation errors on the empty matrix.

**Comment by DuckSoft** [comment]
```python
import numpy as np
import torch

a = np.ndarray((0,0))
assert(np.linalg.det(a) == 1.0)
b = torch.from_numpy(a)
assert(b.det() == 1.0)
assert(torch.det(b) == 1.0)
```

Tested with no error on Arch Linux, `pytorch` version `1.2.0-3`.
Could you please provide with us the code that will repeat the problem?

**Comment by surgan12** [comment]
@DuckSoft , oh yeah my bad, just made some errors on shape broadcast.
Thanks
