### ISSUE TITLE
Inconsistent handling of 0-sized dims in `distributions.categorical` between CPU and GPU

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#27983]
## 🐛 Bug

`Categorical` refuses to sample from logit/probability tensor which has a 0-sized dimension if it is on gpu but does not refuse that when the tensor is on cpu (returning, as expected, a 0-sized sample tensor).

## To Reproduce

```python
import torch
from torch.distributions.categorical import Categorical

dev = torch.device('cuda')
logits = torch.randn(2, 0, 4, 5, device=dev)
dist = Categorical(logits=logits)
sample = dist.sample()
print(sample.shape)
```

will result in

```
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    sample = dist.sample()
  File "/cvlabdata2/home/tyszkiew/miniconda3/envs/hardnet_pytorch/lib/python3.7/site-packages/torch/distributions/categorical.py", line 107, in sample
    sample_2d = torch.multinomial(probs_2d, 1, True)
RuntimeError: invalid argument 2: prob_dist must be 1 or 2 dim at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/generic/THCTensorRandom.cu:44
```

## Expected behavior
I see that this is a corner case, but if we change to `dev = torch.device('cpu')` we get 
```
torch.Size([2, 0, 4])
```
which I see as more reasonable.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 415.25
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by zou3519** [comment]
Inconsistency is bad; it would be good for both code paths (CPU/CUDA) to have the same zero-sized-dim tensor support.

**Comment by neerajprad** [comment]
I am not able to replicate this on pytorch 1.3, and both versions give identical (arguably non-sensical) results. That said, I don't think the behavior of 0 sized dims is well-defined at least for pytorch 1.3, so this seems like a more basic pytorch issue regarding how 0 sized dims should behave. 

e.g. **pytorch 1.3**

```python
>>> torch.rand(2, 0, 4, 5)
tensor([], size=(2, 0, 4, 5))  # Empty tensor of size (2, 0, 4, 5)

>>> torch.rand(2, 0, 4, 5).reshape(-1, 5)
tensor([], size=(0, 5))  # Empty tensor of size (0, 5) 
```

**Comment by gchanan** [comment]
I tested this and it seems to have been fixed; both CPU and CUDA behave the same way wrt to Categorical.

@neerajprad: I don't see what is not well-defined, the behavior you show seems totally sensible (i.e. I would expect `reshape(-1, 5)` to flatten (i.e. multiply) every dimension expect for the 5, which is exactly what it does.

**Comment by neerajprad** [comment]
@gchanan - This is probably the intended behavior, and my confusion simply stems from not fully understanding the reasons for supporting 0-sized dimensions in tensors. e.g. `rand(2, 0, 10)` will give an empty tensor of size `(2, 0, 10)` which can be reshaped into anything e.g. `(-1, 2)`. To be clear, this is well-defined as you say if we consider that all these tensors have size 0 that can be reshaped into anything provided that one of the elements has `size=0`. I initially thought that `0` was intended to support pytorch scalars, but that's not the case (the correct shape to pass into tensor constructors is the empty size `()` not size 0 for scalars).
