### ISSUE TITLE
Feature Request: Normalization via uncentered standard deviation

### ISSUE THREAD

**Issue by ejoebstl** [pytorch/pytorch#2798]
Hello, 

I'm currently trying to reproduce the results given in [this paper](https://redes.unb.br/lasp/files/events/ICASSP2014/papers/p215-zhang.pdf). 

The authors propose a normalization by uncentered standard deviation, which I will therefore implement on top of pytorch:

![codecogseqn](https://user-images.githubusercontent.com/1852126/30640698-32eca1c2-9e04-11e7-9ded-2fe577e88ac2.gif)

I would like to contribute this as UncenteredStandardDeviationNorm in 1d, 2d, 3d versions to pytorch. 

Please feel free to leave feedback. Maybe we can find a less clunky name too, since the authors don't give one in their paper.

**Comment by apaszke** [comment]
Has this layer been used in any important models since it was published?

**Comment by albanD** [comment]
Feel free to re-open this issue if this has been significantly used in the research community since then with references to these use cases.
