### ISSUE TITLE
cuda.model() takes too much time to load on PyTorch 1.3

### ISSUE THREAD

**Issue by jaiabhayk** [pytorch/pytorch#27982]
## 🐛 Bug

cuda.model() take too much time to load
## To Reproduce

Running a simple script like this gives me the following results:

import torch
from datetime import datetime

for i in range(10):
    x = torch.randn(3, 4)
    t1 = datetime.now()
    x.cuda()
    print(i, datetime.now() - t1)

0 0:08:25.137066
1 0:00:00.000090
2 0:00:00.000042
3 0:00:00.000047
4 0:00:00.000038
5 0:00:00.000037
6 0:00:00.000035
7 0:00:00.000035
8 0:00:00.000046
9 0:00:00.000036

Before this for python 1.2 it was working fine, for comparison i paste those numbers and working environment as well==>
0 0:00:03.097851
1 0:00:00.000058
2 0:00:00.000029
3 0:00:00.000034
4 0:00:00.000027
5 0:00:00.000026
6 0:00:00.000025
7 0:00:00.000025
8 0:00:00.000024
9 0:00:00.000025

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 430.40
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.4.0                py36_cu100    pytorch

## Environment
bash-4.2$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 430.40
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] numpydoc==0.8.0
[pip3] torch==1.3.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.1a0+d94043a
[conda] Could not collect

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by zou3519** [comment]
What is your CUDA runtime version?

**Comment by jaiabhayk** [comment]
No separate CUDA runtime version, I am just using the one which is packaged with pytorch installation.

**Comment by jaiabhayk** [comment]
Used the following command to install==>

conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

**Comment by zou3519** [comment]
This is the same as https://github.com/pytorch/pytorch/issues/27738 and https://github.com/pytorch/pytorch/issues/27807. Uninstalling and reinstalling PyTorch from Anaconda will fix it. Please reopen this issue if that does not help.
