### ISSUE TITLE
Support multi-type operations where reasonable

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#28]
E.g. it would be nice if this worked:

```
a = torch.IntTensor(10)
b = torch.LongTensor(10)
a.eq(b)
```

Same with add, subtract, etc.

**Comment by fmassa** [comment]
@soumith this issue was accidentally closed I believe

**Comment by ezyang** [comment]
This still does not work

**Comment by gchanan** [comment]
This works now after type promotion.
