### ISSUE TITLE
is it right that we only have "default mapping" for prepare_qat()

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#28015]
Just want to check that we are doing the right thing with the mapping parameter in prepare, convert(), and prepare_qat(). They all have a "mapping" argument. In earlier versions of the code we had a default mapping for all three. Right now only prepare_qat shows that mapping. Just want to check that this is correct. 

Note: Obviously using the default of None looks better in the doc ( the alternative is a really long argument listing)  but that shouldn't be the deciding factor.

<img width="1102" alt="default-mappin" src="https://user-images.githubusercontent.com/45861273/66854768-d148ea80-ef36-11e9-9eb9-67e1cb28e156.png">

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by gottbrath** [comment]
This is a low priority thing. Just a question.

**Comment by z-a-f** [comment]
Thisshould not look like that in the docs. I will assign it to myself, will send a PR later today
