### ISSUE TITLE
Error then try to modify dropout value RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by hadaev8** [pytorch/pytorch#28017]
Code for reproduce:
https://colab.research.google.com/drive/1YjqlhWjjTQffANSGvOKT3yfFgIO1NxEp
Related thread:
https://discuss.pytorch.org/t/how-to-increase-dropout-rate-during-training/58107/10

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by zou3519** [comment]
Could you run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py?

Furthermore, it would be great if you could isolate the example more.

**Comment by zou3519** [comment]
I suspect that everything is working OK in autograd and that this may be a user error, but it's hard to tell what is going on right now.

**Comment by hadaev8** [comment]
Reduced example, it work fine if i use activation with inplace = false
Also it work if i replace x += residual by x = x + residual
I have this error on 1.3 too.

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.2.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.4.0
[conda] Could not collect
```

**Comment by albanD** [comment]
Hi,

This is expected behavior:
If some value is needed to compute gradients and you modify it inplace, then you get an error (gradients cannot be computed anymore).
You just have to remove the inplace operation to remove the error.

**Comment by vadimkantorov** [comment]
I also stumbled on this here: https://discuss.pytorch.org/t/relu-dropout-inplace/13467/9

Basically PyTorch currently doesn't work very well when two inplace operations are chained (even when it's mathematically correct). As a workaround, you can create your own autograd function that will handle forward and backward.

**Comment by hadaev8** [comment]
How can i use not inplace tanh?

**Comment by vadimkantorov** [comment]
The problem is that you have two inplace ops chained: inplace tanh and then inplace adding of the reisdual

**Comment by vadimkantorov** [comment]
You can keep one or the other. If you want to keep both, you need to do it in the style of invertible modules and make an autograd function yourself: I have an example of inplace batchnorm + inplace residual adding + inplace leaky_relu in https://github.com/pytorch/pytorch/issues/26288#issuecomment-539251421

**Comment by hadaev8** [comment]
Thanks
