### ISSUE TITLE
different input size

### ISSUE THREAD

**Issue by weigq** [pytorch/pytorch#2802]
I have a network, whose inputs are 2 tensors, like:
```python 
def forward(self, inp, rgb):
     #  
    return model
```
the `inp` and `rgb` have different size(both 4D)
while I run `model.forward(x1, x1)`, it went wrong:
```bash

    if input is not None and input.dim() != 4:
AttributeError: 'list' object has no attribute 'dim'

``` 
is that the input of module must have be one argument?
thx

**Comment by soumith** [comment]
followed up with you here: https://discuss.pytorch.org/t/input-tensors-with-different-size/7632/2
