### ISSUE TITLE
unexpected behavior when resize shape include 0s.

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#2806]
The resizes interpret size by stopping at the first 0, which leads to some unexpected results:
```
>>> torch.ones(1,0)

 1
[torch.FloatTensor of size 1]

>>> torch.ones(1,0,3)

 1
[torch.FloatTensor of size 1]

>>> torch.ones(0,3)
[torch.FloatTensor with no dimension]
```

Given that we want to add 0-dimensional scalars (https://github.com/pytorch/pytorch/issues/1433), it would be nice to clean this up.  I propose that including a 0 in a size (besides the 1-element case) should be an error.  That way, in the case of success, the resulting size is always the requested size.

**Comment by soumith** [comment]
having 0 in the size should be an error. this proposal is fine with me, go ahead.

**Comment by fmassa** [comment]
Note that this seems to be inconsistent with what numpy does:
```python
print(np.ones((0,2)))
> array([], shape=(0, 2), dtype=float64)
```

**Comment by fmassa** [comment]
One argument in favour of tensors with shape containing 0s is that some operations (like `cat`) could work on empty tensors without special handling on the user side.
for example
```python
torch.cat([torch.rand(3, 4), torch.rand(0, 4), torch.rand(2, 4)])
```
but supporting such behavior might require some significant changes in TH and THC...

**Comment by gchanan** [comment]
@fmassa right, my thought was just to support size "(0,)" for now, we can consider adding arbitrary 0 dimensions later if it's warranted.

**Comment by gchanan** [comment]
This has been completed.
