### ISSUE TITLE
How can I run Caffe2 model on Android using GPU

### ISSUE THREAD

**Issue by gimgane** [pytorch/pytorch#28064]
Hello,
Based on [this project](https://github.com/cedrickchee/pytorch-android), I am trying to test some Caffe2 models on Android GPU.
But I couldn't find any sample code or documents that explains how to.
Did anyone succeed to test on Android GPU?

**Comment by soumith** [comment]
we do not support the caffe2 frontend at the moment unfortunately

**Comment by gimgane** [comment]
I am sorry to reply late.
But AFAIK [Caffe2 has been merged into PyTorch](https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html) since 2018.


> we do not support the caffe2 frontend at the moment unfortunately


Do you mean Caffe2 is no longer maintained by PyTorch?
But [Caffe2's Github repository is closed](https://github.com/facebookarchive/caffe2), then where could I get help with Caffe2 usage?
