### ISSUE TITLE
Pytorch1.3 can't be compiled successfully with Python3.8.0

### ISSUE THREAD

**Issue by eric-mu** [pytorch/pytorch#28060]
When use Python3.8.0, it's impossible to compile Pytorch1.3 directly. Wish that could be repaired later and thanks a lot!

cc @ezyang @gchanan @zou3519

**Comment by eric-mu** [comment]
My system is a docker container of Ubuntu18.04.
I just clone the source repository and run "python setup.py install" or "make -j48". It will give a compile error like this:
```
/home/xxx/driver/pytorch/torch/csrc/Layout.cpp:69:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
caffe2/torch/CMakeFiles/torch_python.dir/build.make:350: recipe for target 'caffe2/torch/CMakeFiles/torch_python.dir/csrc/Layout.cpp.o' failed
make[2]: *** [caffe2/torch/CMakeFiles/torch_python.dir/csrc/Layout.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/xxx/driver/pytorch/torch/csrc/Dtype.cpp:98:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
[ 96%] Linking CXX executable ../../../bin/TCPStoreTest
/home/xxx/driver/pytorch/torch/csrc/Device.cpp:218:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
/home/xxx/driver/pytorch/torch/csrc/TypeInfo.cpp:229:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
 ^
/home/xxx/driver/pytorch/torch/csrc/TypeInfo.cpp:279:1: error: cannot convert ‘std::nullptr_t’ to ‘Py_ssize_t {aka long int}’ in initialization
 };
```
I guess it's because of the init phase for nullptr, so I modify all `nullptr /* tp_print */` to `0 /* tp_print*/`, and it does work! I don't know this is the right way to fix, but anyway, I can use pytorch1.3 with Python3.8 now:)

**Comment by vishwakftw** [comment]
This is a relevant issue: https://bugzilla.redhat.com/show_bug.cgi?id=1718837 and the quick fix is to replace `nullptr /* tp_print */` with `0 /* tp_vectorcall_offset */`.

**Comment by ezyang** [comment]
We also need to setup Python 3.8 CI. Also see https://github.com/pytorch/pytorch/issues/23490 on subinterpreter support

**Comment by jamesohortle** [comment]
@eric-mu Could you please let me know the relevant files and lines that you changed?
I have changed `./torch/csrc/TypeInfo.cpp: lines 200, 250`.

I can see `Layout.cpp` and `Device.cpp` in your error output --- should I change those files too?

(BTW: I'm on mac, using Clang.)

**Comment by colesbury** [comment]
This would not have broken if it weren't for the large-scale "fix" of linter related issues in https://github.com/pytorch/pytorch/pull/14515, which replaced `NULL` with `nullptr`.
