### ISSUE TITLE
run quantization on GPU

### ISSUE THREAD

**Issue by yongchaoding** [pytorch/pytorch#28069]
## 🚀 Feature

net.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')
net = torch.quantization.QuantWrapper(net)
fuse_list = ['module.conv1', 'module.bn']
net = torch.quantization.fuse_modules(net, fuse_list)
net = torch.quantization.quantize(net, calibration, trainloader)

If i do net.to('cuda'), The error is showed as below. So I want to know if I can just run function quantize_per_channel or quantize_per_tensor in CPU. and it will lead the quantize_qat function very slow in CPU

RuntimeError: No function is registered for schema aten::quantize_per_channel(Tensor self, Tensor scales, Tensor zero_points, int axis, ScalarType dtype) -> Tensor on tensor type CUDATensorId; available functions are CPUTensorId, VariableTensorId

**Comment by z-a-f** [comment]
CUDA quantization is not yet supported. We will update the documentation to make it more clear
