### ISSUE TITLE
PyTorch1.3 cannot find kernel to dispatch when runing a Quantization Model

### ISSUE THREAD

**Issue by vippeterhou** [pytorch/pytorch#28070]
## ❓ PyTorch1.3 cannot find kernel to dispatch when running a Quantization Model
When I tried to quantize mobilenet_v2, I followed the [tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html). I'm sure I have done `layer fusion`, `set quant config`, `calibration`, `model conversion`, and finally I got the quantized model with a smaller size. However, an error occurs when I tried to run this quantized model:
``` python
input = torch.randn([1, 3, 224, 224], dtype=torch.float)
out = quant_model(input)
```

```bash
RuntimeError: Didn't find kernel to dispatch to for operator 'quantized::conv2d_relu'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch keys are: [QuantizedCPUTensorId] (lookup_ at /pytorch/aten/src/ATen/core/dispatch/DispatchTable.h:249)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fdaafe91813 in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1b46361 (0x7fda56bdc361 in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x3e420a8 (0x7fda58ed80a8 in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x4fd81c (0x7fdab502981c in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x4cc184 (0x7fdab4ff8184 in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x210534 (0x7fdab4d3c534 in /home/peter/envs/pt13/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: python() [0x50682c]
<omitting python frames>
frame #8: python() [0x596285]
frame #11: python() [0x504232]
frame #12: python() [0x5966f8]
frame #13: python() [0x54d4ee]
frame #15: python() [0x5067b0]
frame #17: python() [0x596285]
frame #20: python() [0x504232]
frame #21: python() [0x5966f8]
frame #22: python() [0x54d4ee]
frame #24: python() [0x5067b0]
frame #26: python() [0x596285]
frame #29: python() [0x504232]
frame #30: python() [0x5966f8]
frame #31: python() [0x54d4ee]
frame #33: python() [0x5067b0]
frame #35: python() [0x596285]
frame #38: python() [0x504232]
frame #39: python() [0x5966f8]
frame #40: python() [0x54d4ee]
frame #42: python() [0x5067b0]
frame #44: python() [0x5058a4]
frame #45: python() [0x5066f0]
frame #47: python() [0x596285]
frame #48: python() [0x548e73]
frame #49: python() [0x53c229]
frame #51: python() [0x5067b0]
frame #53: python() [0x504232]
frame #55: python() [0x647fa2]
frame #60: __libc_start_main + 0xf0 (0x7fdab97bc830 in /lib/x86_64-linux-gnu/libc.so.6
```
Is there anyone who may help me? Thanks a lot!!!  :blue_heart:

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by z-a-f** [comment]
You need to quantize the input before pushing it into a quantized model:

```python
input = torch.randn([1, 3, 224, 224], dtype=torch.float)
input = torch.quantize_per_tensor(input, scale=1e-3, zero_point=0, dtype=torch.qint32)  # This is just an example
out = quant_model(input)
```

The quantization parameters are just an example here

**Comment by z-a-f** [comment]
@raghuramank100 I think we might need to add a note about that somewhere

**Comment by vippeterhou** [comment]
It works. Thanks!
(For whom it may concern: The input data type should be `torch.quint8` in my case.)

**Comment by z-a-f** [comment]
> It works. Thanks!
> (For whom it may concern: The input data type should be `torch.quint8` in my case.)

For the unsigned types, it makes more sense to set the `zero_point` to some non-zero value. For example, you can set it to 128 for 8-bit quantization. That way you will have symmetrical coverage for positive and negative input values. Ideally, you want to set the zero point to something that depends on the input statistics (check out the Observers in the [docs](https://pytorch.org/docs/master/quantization.html#torch-quantization)

**Comment by Naresh1318** [comment]
@z-a-f The forward function under the MobileNetV2 class seem to have `x = self.quant(x)`. Shouldn't this quantize its input automatically?

**Comment by vippeterhou** [comment]
@Naresh1318 
Yes, you are right. 
I missed this point at the very beginning.

Finally, the following code solved my problem.
```python 
def __init__(self):
    ...
    self.quant = QuantStub() # Quantize stub module, before calibration, this is same as an observer, it will be swapped as nnq.Quantize in convert.
    ...
def forward(self, x):
    x = self.quant(x)
    ...
```
Similarly, use `DeQuantStub` in the same way.

**Comment by aakash2602** [comment]
Please add this note or update the example!
