### ISSUE TITLE
Question about torch.squeeze and torch.cat

### ISSUE THREAD

**Issue by hamidfarhid** [pytorch/pytorch#2807]
Hi All,
x is a tensor with 5 dimensions. For a reason, I need to keep the vector of the tensors in a list and then concatenate the list of tensors to get the final result. I expected that the x and y should be the same at the end but they are a little bit different. Is there any reason for that?
  
 `y=[]`
 `
for i in range(len(x)):
       y.append(x[i,:,:,:,:].unsqueeze(0))
`
`y = torch.cat([*y])`

**Comment by chenzhekl** [comment]
I am unable to reproduce your issue on both GPU and CPU. Here is my code for testing:

```python
import torch

x = torch.randn(2, 3, 4, 5, 6)
y = []

for i in range(len(x)):
    y.append(x[i, :, :, :, :].unsqueeze(0))
    
(x - torch.cat([*y])).sum()
```

Output: `0.0`
