### ISSUE TITLE
Feature Request: More general learning-rate scheduling

### ISSUE THREAD

**Issue by rdipietro** [pytorch/pytorch#2809]
Hi,

I recently learned of `torch.optim.lr_scheduler`.

First a comment: Despite how common it is to tweak learning rates during training, this package isn't easy to find. Would it be worth importing in `torch.optim.__init__.py` so that (for example) `torch.optim.<tab>` in most IDEs would make this common behavior more visible?

Feature request: `LambdaLR` currently has strange behavior: it accepts a function `f(step)` which returns a learning-rate multiplicative factor as a function of `step`. Given the name `LambdaLR`, it seems that it should instead accept a function `f(step)` which simply computes the learning rate itself as a function of `step`. Thoughts?

Or, if a bug-inducing change like that is too much, maybe we should just introduce `NonMultiplicativeLambdaLR` or `GeneralLambdaLR` instead?

**Comment by dteoh** [comment]
I'm a python noob and was going crazy trying to use this "module".

```
AttributeError: module 'torch.optim' has no attribute 'lr_scheduler'
```

Finally got it working by using:

```
from torch.optim import lr_scheduler
```

**Comment by Jiaming-Liu** [comment]
It seems that I mistakenly forgot to pull `__init__.py`. Sorry about that.
To talk about LambdaLR, I believe that it is reasonable -- it is a common practice to use different base_lr for different params and meanwhile to apply the same scheduler. In this case, only one f is required.
