### ISSUE TITLE
Ghost memory usage when start cuda

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#28113]
## 🐛 Bug

There is some memory usage shown in the nvidia-smi but not in torch.cuda when torch starts to use cuda. The amount of this usage differs on different machines.

## To Reproduce

```
import torch
torch.cuda.synchronize()
import os; print(os.popen('nvidia-smi').read())
print(torch.cuda.memory_allocated())
```

## Expected behavior

The nvidia-smi will show an increase in memory usage, while the torch.cuda says it's using 0 memory.

The nvidia-smi shows from 200+mb to 700+mb.

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.9.4
CMake version: version 2.8.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla K40c
GPU 1: Tesla K40c

Nvidia driver version: 418.43
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.10
/usr/local/cuda-7.5/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] pytorch                   1.3.0           py2.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchtext                 0.3.1                    pypi_0    pypi
[conda] torchvision               0.4.1                py27_cu101    pytorch

**Comment by SsnL** [comment]
That is the size of the CUDA context. It happens for every CUDA program, not just PyTorch.

**Comment by ruotianluo** [comment]
Is the size of cuda context normal, a few megabytes?

**Comment by ruotianluo** [comment]
I found answers in other issues. Thanks.
