### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ati6868** [pytorch/pytorch#28111]
Hi ... when i am running this code:
https://github.com/Hananel-Hazan/bindsnet/blob/master/examples/mnist/reservoir.py

I get this error:

`AssertionError: Torch not compiled with CUDA enabled`

I have not installed cuda and i don't want to do that
How can i run this code on CPU
I will appreciate if anyone give me a help on this

**Comment by soumith** [comment]
you should ask those code authors. that code requires cuda
