### ISSUE TITLE
torch.arange type

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#2812]
`torch.arange` has a different behavior than `np.arange`
`torch.arange(0, 10)` returns a FloatTensor, but shouldn't it be a LongTensor?
Also, `torch.arange(10)`, which I would expect to behave like `torch.arange(0, 10)`, fails, and returns:

```
TypeError: torch.arange received an invalid combination of arguments - got (float), but expected one of:
 * (float start, float end)
 * (float start, float end, float step)
```

`np.arange` can also take float as input, and in that case will return a float array instead of a int64 array. Could we have something similar in pytorch? If inputs are int, return a LongTensor, if they are float, return a FloatTensor?

**Comment by fmassa** [comment]
Currently, the only way to return `long` tensors from `arange` is by using the following constructor
```python
idx = torch.arange(0, 10, out=torch.LongTensor())
```
But this is indeed annoying, and will hopefully be fixed when https://github.com/pytorch/pytorch/issues/1433#issuecomment-330336116 is implemented

**Comment by gchanan** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/7016.
