### ISSUE TITLE
torck.zeros_like() does not work

### ISSUE THREAD

**Issue by Sushobhan04** [pytorch/pytorch#2813]
a = torch.LongTensor(10)
b = torch.zeros_like(a)

it throws AttributeError: 'module' object has no attribute 'zeros_like'

pytorch documentation says it is a valid function http://pytorch.org/docs/master/torch.html#torch.zeros_like

**Comment by fmassa** [comment]
`zeros_like` was recently added in pytorch, and is only present in master, and not in the available releases yet.
You can change the documentation to use a specific release by clicking in the numbers just below the pytorch logo, which leads you to this page http://pytorch.org/docs/versions.html

**Comment by Sushobhan04** [comment]
I was able to use torch.zeros(a.size()) as an alternative. Thanks for the info about documentation.

**Comment by shekhovt** [comment]
@Sushobhan04 
torch.zeros(a.size()) is not using the same storage as a itslef (cpu/ device #). 
I am using this workaround:
a.new(a.size()).zero_()
Or when needing a different tensor type, say long, this one:
a.new().long().new(a.size()).zero_()
This is kind of a strange way to create tensors, not suggested by docs, but actually quite convenient
