### ISSUE TITLE
.jenkins/caffe2/build.sh is failing to run

### ISSUE THREAD

**Issue by pramenku** [pytorch/pytorch#28137]
https://github.com/pytorch/pytorch/blob/master/.jenkins/caffe2/build.sh Line:9

sudo yum install -y centos-release-scl command is throwing error

++ dirname .jenkins/caffe2/build.sh

+ source .jenkins/caffe2/common.sh

++ set -ex

++++ dirname .jenkins/caffe2/common.sh

+++ cd .jenkins/caffe2

+++ pwd

++ LOCAL_DIR=/root/caffe2/.jenkins/caffe2

+++ cd /root/caffe2/.jenkins/caffe2/../..

+++ pwd

++ ROOT_DIR=/root/caffe2

++ TEST_DIR=/root/caffe2/caffe2_tests

++ gtest_reports_dir=/root/caffe2/caffe2_tests/cpp

++ pytest_reports_dir=/root/caffe2/caffe2_tests/python

+++ which python

++ PYTHON=/usr/bin/python

++ [[ py3.6-devtoolset7-rocmrpm-centos7.5 =~ py((2|3)\.?[0-9]?\.?[0-9]?) ]]

+++ which python3.6

++ PYTHON=/usr/bin/python3.6

++ INSTALL_PREFIX=/usr/local/caffe2

++ mkdir -p /root/caffe2/caffe2_tests/cpp

++ mkdir -p /root/caffe2/caffe2_tests/python

++ mkdir -p /usr/local/caffe2

+ [[ py3.6-devtoolset7-rocmrpm-centos7.5 == *centos7* ]]

+ sudo yum install -y centos-release-scl

  File "/usr/bin/yum", line 30

    except KeyboardInterrupt, e:

                            ^

SyntaxError: invalid syntax

The command '/bin/sh -c .jenkins/${FRAME_NAME}/build.sh' returned a non-zero code: 1

[ caffe2 build is NOT successful ]

cc @ezyang

**Comment by smessmer** [comment]
Thanks for reporting. Can you give more information on how and where you're running this exactly?

**Comment by pramenku** [comment]
Thanks.
I found the problem

yum install is not working after command "update-alternatives --install /usr/bin/python python /usr/bin/python3.6 2"

Not sure why this command impacting, yum command.
