### ISSUE TITLE
atomic_ops_test.py::TestAtomicOps::test_atomic_ops intermittently segfaults in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#28179]
## 🐛 Bug

See https://circleci.com/gh/pytorch/pytorch/3237590?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console, where the dump occurs around test_atomic_ops. See also https://circleci.com/gh/pytorch/pytorch/3224131?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console which shows the same.

See https://circleci.com/gh/pytorch/pytorch/3234331?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console, where the dump occurs in testInputOrder. 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
See also: https://circleci.com/gh/pytorch/pytorch/3248435?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link. testInputOrder again.

**Comment by mruberry** [comment]
See also: https://circleci.com/gh/pytorch/pytorch/3243424?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link. test_atomic_ops again.

**Comment by smessmer** [comment]
We would accept a PR fixing this

**Comment by mruberry** [comment]
Updating labels per last oncall review.

**Comment by colesbury** [comment]
@ezyang suggests one issue per crash and letting the test authors know when they're disabled

**Comment by mruberry** [comment]
These tests are now disabled. Unfortunately it's not clear who would be interested in fixing them (if anyone).

**Comment by mruberry** [comment]
Changing title of this issue to track test_atomic_ops:

Oct 16 23:25:03 ../.local/lib/python3.5/site-packages/caffe2/python/operator_test/assert_test.py::TestAssert::test_assert PASSED [ 77%]
Oct 16 23:25:04 ../.local/lib/python3.5/site-packages/caffe2/python/operator_test/atomic_ops_test.py::TestAtomicOps::test_atomic_ops PASSED [ 77%]./.jenkins/caffe2/test.sh: line 120:  2616 Aborted                 (core dumped) "$PYTHON" -m pytest -x -v --disable-warnings --junit-xml="$pytest_reports_dir/result.xml" --ignore "$caffe2_pypath/python/test/executor_test.py" --ignore "$caffe2_pypath/python/operator_test/matmul_op_test.py" --ignore "$caffe2_pypath/python/operator_test/pack_ops_test.py" --ignore "$caffe2_pypath/python/mkl/mkl_sbn_speed_test.py" ${rocm_ignore_test[@]} "$caffe2_pypath/python" "${EXTRA_TESTS[@]}"
Exited with code 134

testInputOrder is tracked by #9064.

**Comment by mruberry** [comment]
Removing high priority label.

**Comment by mruberry** [comment]
Closing due to age and this no longer occurring.
