### ISSUE TITLE
ROCm CI can fail test_sync_params_with_buffers

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#28178]
## 🐛 Bug

See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/1741//console, which shows the failure. 

cc @ezyang

**Comment by mruberry** [comment]
fyi @gottbrath

**Comment by smessmer** [comment]
cc @bddppq

**Comment by bddppq** [comment]
this has been disabled in https://github.com/pytorch/pytorch/commit/0b243e9c4c94bc611f99df02a15fac9b332e5432
