### ISSUE TITLE
ROCm CI can timeout in blobs_queue_db_test.py::BlobsQueueDBTest::test_create_blobs_queue_db_tensor.

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#28177]
## 🐛 Bug

See https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/41068//console where it timed out in blobs_queue_db_test.py::BlobsQueueDBTest::test_create_blobs_queue_db_tensor.

See also https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-devtoolset7-rocmrpm-centos7.5-test/40962//console where it timed out in the same test.

cc @ezyang

**Comment by mruberry** [comment]
fyi @gottbrath

**Comment by smessmer** [comment]
cc @bddppq

**Comment by bddppq** [comment]
Disabling in https://github.com/pytorch/pytorch/pull/28268
