### ISSUE TITLE
After I update the pytorch version from 1.0 to 1.2 and cuda.is_available return FALSE

### ISSUE THREAD

**Issue by Zhizh1** [pytorch/pytorch#28195]
when i use pytorch1.0 and enter the following commands：
>>> import torch
>>> import torchvision
>>> print(torch.__version__)
1.0.0.dev20190102
>>> print(torchvision.__version__)
0.2.1
>>> torch.cuda.is_available()
True
>>> print(torch.version.cuda)
9.0.176
>>> exit()
# cat /usr/local/cuda/version.txt 
CUDA Version 9.0.176
after i update pythorch to version1.2,and enter the following commands:
print(torch.__version__)
1.2.0
>>> print(torchvision.__version__)
0.4.0
>>> torch.cuda.is_available()
False
>>> print(torch.version.cuda)
10.0.130
>>> exit()
# cat /usr/local/cuda/version.txt 
CUDA Version 9.0.176

when i run my program，the msg is that my Nvidia version is too old.
Should i update my cuda version and nvidia driver version simultaneously？or Is there any other solution?

**Comment by shijianjian** [comment]
You may need to update CUDA to make it work. It happens to me when I upgraded from 1.2 to 1.3 that I need CUDA 10.1 than CUDA 10.

**Comment by Zhizh1** [comment]
If i update my cuda version and then i need to upgrade the nvidia driver.This may affect other people's processes and want to see if there is any other solution first

**Comment by soumith** [comment]
just update your nvidia driver and this should be sufficient.

**Comment by soumith** [comment]
if the 10.1 build is seeing insufficient driver version, you can try installing the pytorch cuda 9.2 version (check commands on pytorch.org ) and see if that works
