### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by sjzryf** [pytorch/pytorch#28209]
python3.6 train.py -save res
Save File Exists, OverWrite? <CTL-C> for no
Loading Data from  data/preprocessed.train.tsv
building vocab
done
Sorting training data by len
ds sizes:	11880	26156	684	1000	Vocab sizes:
src 6343
ent 53343
nerd 8
rel 17
out 11738
graph
cuda:0
epoch  0 lr 0.1
Training	2
/home/ryf/桌面/GraphWriter-master/models/last_graph.py:75: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  ngraph = torch.tensor(vgraph.repeat(N,1).view(N,N,-1),requires_grad=False)
/home/ryf/桌面/GraphWriter-master/models/newmodel.py:62: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cx = torch.tensor(hx)
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main(args)
  File "train.py", line 113, in main
    train(m,o,ds,args)
  File "train.py", line 32, in train
    p,z,planlogits = m(b)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ryf/桌面/GraphWriter-master/models/newmodel.py", line 92, in forward
    o = self.out(l)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 210.00 MiB (GPU 0; 2.95 GiB total capacity; 2.42 GiB already allocated; 47.19 MiB free; 28.46 MiB cached)

**Comment by vippeterhou** [comment]
I think you should use `watch nvidia-smi` to monitor the GPU usage.

**Comment by DuckSoft** [comment]
Have a check at `nvidia-smi`. There should be a list of all programs eating your CUDA memory.
Kill the programs that you won't need and restart your own program.

THIS IS NOT A PYTORCH PROBLEM.

**Comment by smessmer** [comment]
Closing this for now. Feel free to reopen if you confirmed it's actually a PyTorch issue.
