### ISSUE TITLE
`default_qconfig` doesn't exist as an attribute, so it is better to label it as ``default_qconfig``

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#28234]
## 📚 Documentation

`default_qconfig` doesn't exist as an attribute, so it is better to label it as ``default_qconfig``
![image](https://user-images.githubusercontent.com/5652049/66953340-5235de00-f02c-11e9-92c5-6719ccca7ff3.png)

_Originally posted by @zou3519 in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDMzNTY3NTE3Mw==/comments/review_comment_

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jerryzh168** [comment]
what do you mean?

**Comment by z-a-f** [comment]
> what do you mean?

In the documentation we use `` :attr:`~torch.quantization.default_qconfig` ``, which is supposed to create a link to the documentation on that attribute. The problem is that `default_qconfig` is not an attribute (just a global variable), and the documentation will fail to create a link.

Instead we should use ``` ``default_qconfig`` ```

**Comment by jerryzh168** [comment]
@z-a-f is this fixed now?

**Comment by z-a-f** [comment]
Closing as resolved
