### ISSUE TITLE
cannot initialize torch.distributed with mpi backend

### ISSUE THREAD

**Issue by ybzhou** [pytorch/pytorch#2823]
I installed pytorch from source with mpi support, however when trying to initialize
```
torch.distributed.init_process_group(backend='mpi', init_methods='file:///filelocation', world_size=2)
```
it always return immediately and if you run `torch.distributed.get_world_size()` the returned value is 1.

**Comment by soumith** [comment]
for the mpi backend, i believe the world_size is set via `mpirun` utility, not as part of `init_process_group`

**Comment by soumith** [comment]
for example: `mpiexec -n 3 python foo.py` will make world_size be 3

**Comment by apaszke** [comment]
I just checked and MPI backend seems to work fine for me. Please reopen the issue once you'll have a more complete script that we could use to reproduce your problems.

**Comment by CharlesxrWu** [comment]
I use MPI as the backend to run my pytorch program, I meet the same problem as the first answer, the world_size is just 1. Then I use  the code
mpirun --hostfile hostfile -n 2 python Alex_PS_MPI.py

and revised the init line which is similar with pytorch distributed_test.py file. However, it cannot work.


os.environ['MASTER_ADDR'] = '172.31.7.117'
os.environ['MASTER_PORT'] = '23456'

    dist.init_process_group(init_method='env://', backend='mpi')
    group = dist.new_group([i for i in range(dist.get_world_size())])

**Comment by apaszke** [comment]
What kind of error are you getting?

**Comment by CharlesxrWu** [comment]
No output. It can work wit TCP or GLoo backend.

**Comment by CharlesxrWu** [comment]
Can u add an official multi-node distributed example in document?

**Comment by rabeehk** [comment]
Hi, I am having the same issue, I am trying to test DistributedDataParallelCPU on a simple example,
Here is the file(test.py) I wrote:
``
import torch.distributed as dist
import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F

parser = argparse.ArgumentParser()
parser.add_argument('--local_rank', default=0, type=int)
args = parser.parse_args()
dist.init_process_group(backend="mpi", init_method="env://",
                       world_size = int(os.environ["WORLD_SIZE"]), rank=args.local_rank)

## Model.
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
       x = F.relu(self.conv1(x))
       return F.relu(self.conv2(x))

model = Model() 
net = torch.nn.parallel.DistributedDataParallelCPU(model)
``
and I call the file as below:

python -m torch.distributed.launch  --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=6006  test.py 

I got the error that 
RuntimeError: the MPI backend is not available; try to recompile the THD package with MPI support at /opt/conda/conda-bld/pytorch_1532581333611/work/torch/lib/THD/process_group/General.cpp:17

Thanks for your assistance

**Comment by saareliad** [comment]
This issue is still relevant and should be re-opened:
The only way MPI can be initialized is with with mpiexec/mpirun.
This does not allow to use combination of multiprocessing (for cuda-IPC) and MPI,
because for multiprocessing we need to spawn and for MPI we need to call mpiexec.
