### ISSUE TITLE
Master process finishes and leave workers hanging when master and worker has different gpu numbers

### ISSUE THREAD

**Issue by matthewygf** [pytorch/pytorch#28257]
## 🐛 Bug
In a scenario where:
* World_size = 4
* { N1: 1 GPU, N2: 1 GPU, N3: 2 GPU } 
Using distbackend=NCCL and distmethod=TCP on pytorch 1.2 

- running epochs up to 5, using distributed Sampler and distributed data parallel
the rank0 process on N1 finishes before N3 and leaves rank2,3 in N3 hanging.

## To Reproduce

https://github.com/matthewygf/torch_interference

On Node 1
NVIDIA_VISIBLE_DEVICES=0
`python image_classifier.py --model=googlenet --run_name=blahblah --dataset_dir=/mnt/data --dataset=cifar10 --ckpt_dir=/mnt/ckpt --batch_size=128 --discover_gpus --world_size=4 --dist_backend=nccl --dist_method=tcp://googlenetxv-machine1-master-0.googlenetxv-machine2:2222 --rank=0`

On Node 2
NVIDIA_VISIBLE_DEVICES=0
`python image_classifier.py --model=googlenet --run_name=blahblah --dataset_dir=/mnt/data --dataset=cifar10 --ckpt_dir=/mnt/ckpt --batch_size=128 --discover_gpus --world_size=4 --dist_backend=nccl --dist_method=tcp://googlenetxv-machine1-master-0.googlenetxv-machine2:2222 --rank=1`

On Node 3
NVIDIA_VISIBLE_DEVICES=0,1
`git clone https://github.com/matthewygf/torch_interference.git && cd torch_interference && python image_classifier.py --model=googlenet --run_name=blahblah --dataset_dir=/mnt/data --dataset=cifar10 --ckpt_dir=/mnt/ckpt --batch_size=128 --discover_gpus --world_size=4 --dist_backend=nccl --dist_method=tcp://googlenetxv-machine1-master-0.googlenetxv-machine2:2222 --rank=2`

## Expected behavior

Should finish all together on epoch 5.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.2
 - OS (e.g., Linux): ubuntu Disco
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version: CUDA 10.1
 - GPU models and configuration: RTX 2080
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pritamdamania87** [comment]
IIUC, this line might be the problem: https://github.com/matthewygf/torch_interference/blob/master/image_classifier.py#L248. In Distributed Data Parallel, each worker needs to process exactly the same number of batches. Looking at your code it seems like the two processes on N3 are processing more number of batches and hence N1 finishes first and N3 is left hanging.

**Comment by zhaojuanmao** [comment]
@pritamdamania87 do we have check to throw error if number of batches are not equal btw processes?

**Comment by matthewygf** [comment]
@pritamdamania87 apologies for my messy code, i think you are right, will test it out !

**Comment by pritamdamania87** [comment]
@zhaojuanmao I don't think we have something like this. Do you have any ideas around how we can do this though? The processes are running independently from each other so I don't think that they are aware of how many batches each one has processed.
