### ISSUE TITLE
Adding a .fit() method to nn.Module

### ISSUE THREAD

**Issue by saattrupdan** [pytorch/pytorch#28278]
[from [https://discuss.pytorch.org/t/training-a-model-via-a-train-method/58567](https://discuss.pytorch.org/t/training-a-model-via-a-train-method/58567)]

## 🚀 Feature
Add a .fit() method to nn.Module, which trains the model using the parameters given.

## Motivation
Writing out a full training loop every time I'm testing a model is frustrating, if I'm simply using the same standard template each time.

## Pitch
Either add the .fit() method to nn.Module directly, or create an extension of nn.Module which contains it. The method should be as general as possible, and the focus should be ease of use, with reasonable defaults. I'd like to be able to write something like

```
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        (...)

    def forward(self, x):
        (...)

model = Model()
model.fit(traindata, valdata, criterion = 'mse', epochs = 5)
```

## Alternatives
An alternative could be a train function which inputs the model along with all the relevant parameters, but it feels like the training belongs more to the internals of the model, which would also allow it to store its own training logs internally, if that's desired.

**Comment by pietern** [comment]
I doubt we'll end up doing something like this. The sheer amount of configurables for a function like that (both at the beginning, and the new ones it will solicit) makes me think it'll always be easier and more flexible to write a function that does exactly what you want.

**Comment by soumith** [comment]
Please have a look at http://github.com/pytorch/ignite or https://skorch.readthedocs.io/en/stable/ or https://github.com/williamFalcon/pytorch-lightning which give you roughly what you are looking for. Based on what pietern said, we're unlikely to do this in core.
