### ISSUE TITLE
Can not load model

### ISSUE THREAD

**Issue by Norfo** [pytorch/pytorch#28276]
## 🐛 Bug

Hello every one!

I use pytorch for GCN-slam (https://github.com/jiexiong2016/GCNv2_SLAM 3). I have a problem when I try to load model by torch::jit::load(). I constantly get this error:

```
type_ != nullptr INTERNAL ASSERT FAILED at C:\w\1\s\tmp_conda_3.6_171155\conda\conda-bld\pytorch_1570813991702\work\torch/csrc/jit/ir.h:165, please report a bug to PyTorch. (type at C:\w\1\s\tmp_conda_3.6_171155\conda\conda-bld\pytorch_1570813991702\work\torch/csrc/jit/ir.h:165)
(no backtrace available)
```

I use win10, torch 1.3.0a0+b728ffa, cuda v10.1, Visual Studio 2017.

## To Reproduce

1. Download any model from https://github.com/jiexiong2016/GCNv2_SLAM/tree/master/GCN2 (for example gcn2_640x480.pt) or https://drive.google.com/file/d/1MJMroL5-tl0b9__-OiCfxFP9K6X8kvTT/view
2. Use this code to catch loading error:

```cpp
try 
{
    torch::jit::load("path/to/GCN2 model/gcn2.pt"); //Insert here downloaded model location
    std::cout << "Model loaded!" << std::endl;
}
catch (const c10::Error& e) 
{
    auto m = e.what();
    std::cerr << m;
}
```

## Expected behavior

I expect that the model should load without any troubles.

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 426.00
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.0
[pip] torchvision==0.4.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-include               2019.4                      245
[conda] mkl-service               2.3.0            py36hb782905_0
[conda] mkl_fft                   1.0.14           py36h14836fe_0
[conda] mkl_random                1.1.0            py36h675688f_0
[conda] pytorch                   1.3.0           py3.6_cuda101_cudnn7_0    pytorch
[conda] torch                     1.3.0a0+b728ffa          pypi_0    pypi
[conda] torchvision               0.4.1                py36_cu101    pytorch

I will appreciate if someone can help me.

cc @suo

**Comment by jerryzh168** [comment]
This might be a problem with the model itself, does it work in the original repo?

**Comment by driazati** [comment]
I tried your model (`gcn2_640x480.pt`), I'm running into a different error (both in Python `torch.jit.load` and C++ `torch::load`) on master (on Linux).

For
```python
import torch
torch.jit.load('gcn2_640x480.pt')
```

I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/davidriazati/dev/pytorch/torch/jit/__init__.py", line 239, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::grid_sampler(Tensor input, Tensor grid, int interpolation_mode, int padding_mode, bool align_corners) -> (Tensor):
  Argument align_corners not provided.

The original call is:
at code/gcn2_480x640.py:67:22
  _25 = torch.slice(vu, 0, 0, 9223372036854775807, 1)
  _26 = torch.select(_25, 1, 0)
  _27 = torch.slice(vu, 0, 0, 9223372036854775807, 1)
  _28 = torch.select(_27, 1, 1)
  _29 = torch.to(_26, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  _30 = torch.to(_28, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  _31 = torch.unsqueeze(torch.index(CONSTANTS.c1, [_29, _30]), 1)
  ref_points = torch.cat([_24, _31], 1)
  grid = torch.view(ref_points, [1, 1, -1, 2])
  _32 = torch.squeeze(torch.grid_sampler(input, grid, 0, 0))
                      ~~~~~~~~~~~~~~~~~~ <--- HERE
  desc_1 = torch.t(_32)
  desc_2 = torch.to(torch.gt(desc_1, 0), 6, False, False)
  _33 = ops.prim.NumToTensor(torch.size(desc_2, 0))
  desc_3 = torch.view(desc_2, [int(_33), 32, 8])
  desc_4 = torch.mul(desc_3, CONSTANTS.c2)
  desc = torch.sum(desc_4, [2], False)
  _34 = (_17, torch.to(desc, 0, False, False))
  return _34
```

Unzipping the `gcn2_640x480.pt` file and fixing that line in `./gcn2_480x640/code/gcn2_480x640.py` to be `_32 = torch.squeeze(torch.grid_sampler(input, grid, 0, 0, False))` makes the model load successfully, but that seems like a bug on our part (either the operator was changed or is not being serialized correctly). Could you try to load it using the nightly libtorch package? And does it load correctly in Python (via `torch.jit.load`)?

**Comment by Norfo** [comment]
Thank you very much! After making changes to the model, loading is carried out correctly both on the side of python and c ++. Unfortunately, I did not have time to check using the nightly package. I will try to do this soon.

I currently have an error using the ```forward()``` method of this model. 
```
The above operation failed in interpreter, with the following stack trace:
at code/gcn2_480x640.py:43:8
  _6 = torch.unsqueeze(torch.select(_5, 1, 0), 1)
  _7 = torch.to(_6, 6, False, False)
  _8 = torch.slice(vu_1, 0, 0, 9223372036854775807, 1)
  _9 = torch.select(_8, 1, 0)
  _10 = torch.slice(vu_1, 0, 0, 9223372036854775807, 1)
  _11 = torch.select(_10, 1, 1)
  _12 = torch.to(_9, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  _13 = torch.to(_11, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  _14 = torch.unsqueeze(torch.index(det, [_12, _13]), 1)
  pts = torch.cat([_4, _7, _14], 1)
        ~~~~~~~~~ <--- HERE
  _15 = torch.slice(pts, 0, 0, 9223372036854775807, 1)
  input_20 = torch.neg(torch.select(_15, 1, 2))
  _16, inds_1 = torch.sort(input_20, -1, False)
  inds_2 = torch.to(inds_1, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  _17 = torch.index(pts, [inds_2])
  inds = torch.to(inds_2, dtype=4, layout=0, device=torch.device("cuda:0"), non_blocking=False, copy=False)
  vu = torch.index(vu_1, [inds])
  _18 = torch.slice(vu, 0, 0, 9223372036854775807, 1)
  _19 = torch.select(_18, 1, 0)
```
Of course, I understand that it will be quite difficult to figure this out without the necessary initial data. But could you briefly analyze this model for potential errors? I can provide the c ++ code I am using and the input if you need it. I will also notify the author of the model about this error, maybe he can help me.

**Comment by Norfo** [comment]
I returned to this problem and here is what I managed to find out. I deduced the dimensions of the tensors that are used in the concatenation operation and got the following:
```
[11601, 1]
[11601, 1]
[11601, 1]
```
As can be seen, tensors have the same dimension, therefore, there can be no errors associated with different dimensions.
Can you tell me which way I can still look in order to get closer to solving this problem?

**Comment by Norfo** [comment]
I solved my problem with copying all pytorch dlls into the folder with my project. Thanks!
