### ISSUE TITLE
torch.jit.ignore messes with buffer device placement

### ISSUE THREAD

**Issue by nlgranger** [pytorch/pytorch#28280]
## To Reproduce

Run this minimal example

```python
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('a', torch.zeros(10))
        
    def forward(self, inputs):
        return self.non_scriptable(inputs)
    
    @torch.jit.ignore
    def non_scriptable(self, inputs):
        print(self.a.device)
        return inputs * self.a


# Not scripted: normal behaviour
m = Model()
m = m.to('cuda')
m(torch.zeros(10).to('cuda'))

# Scripted: fails
m = Model()
m = torch.jit.script(m)
m = m.to('cuda')
print(m.a.device)  # prints cuda
m(torch.zeros(10).to('cuda'))  # fails because m.a is on cpu inside non_scriptable
```

Outputs:
```
cuda:0
cuda:0
cpu

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-49-a9cb0d104a1f> in <module>
     23 m = m.to('cuda')
     24 print(m.a.device)  # prints cuda
---> 25 m(torch.zeros(10).to('cuda'))  # fails because m.a is on cpu inside non_scriptable

~/.conda/envs/MTMSF/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543             result = self._slow_forward(*input, **kwargs)
    544         else:
--> 545             result = self.forward(*input, **kwargs)
    546         for hook in self._forward_hooks.values():
    547             hook_result = hook(self, input, result)

RuntimeError: RuntimeError: expected device cuda:0 but got device cpu
```

## Expected behavior

Scripted and non-scripted versions have identical behaviour.

## Environment

PyTorch version: 1.3.0.dev20190917
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX TITAN Black
GPU 1: GeForce GTX TITAN Black

Nvidia driver version: 418.40.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.5.0
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] torch==1.3.0.dev20190917
[pip] torchvision==0.5.0a0+e8b830f
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.3.0.dev20190917 py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20190917      py37_cu100    pytorch-nightly

cc @suo

**Comment by wanchaol** [comment]
@driazati can you take a look on this?

**Comment by dzhulgakov** [comment]
It's not related to buffers behavior but instead general issue with the wrong `self` instance being passed in (the original non-scripted module on cpu in your example).

Methods marked with @torch.jit.ignore stay as python methods when TorchScripted and get copied to the RecursiveScriptModule instance. However, it looks like they retain `self` pointing to the original instance of the non-scripted module.

It's broken only on python side, if the ignored method is called from scripted method, the correct instance is passed in.

## Simpler reproduction

Sample program demonstrating why this behavior is confusing:

```
class Bar(torch.nn.Module):
    def __init__(self):
        super(Bar, self).__init__()
        self.x : int = 0
    
    @torch.jit.export
    def set(self, x : int):
        self.x = x
    
    @torch.jit.export
    def print(self):
        print('normal:', self.x)
        self.ignored_print()
    
    @torch.jit.ignore
    def ignored_print(self):
        print('ignore:', self.x)

b = Bar()
b.set(123)
sb = torch.jit.script(b)
sb.print()
sb.ignored_print()
print('====')
sb.set(456)
sb.print()
sb.ignored_print()
```

produces

```
normal: 123
ignore: 123
ignore: 123
====
normal: 456
ignore: 456
ignore: 123
```

Note that in the last line the wrong value of self.x is picked up while in the second to last - the correct one (as the call to `ignored_print` happens from torchscripted `print`).

cc @driazati
