### ISSUE TITLE
NCCLUtils.hpp does not compile with libc++

### ISSUE THREAD

**Issue by haowu80s** [pytorch/pytorch#28288]
## 🐛 Bug

`NCCLUtils.hpp` does not compile with clang and libc++. 

The following line makes a shared pointer of `NCCLComm`, whose destructor may throw exceptions.
 
https://github.com/pytorch/pytorch/blob/3629974c1e78b5dbd6286c4b33a5adffe2d68407/torch/lib/c10d/NCCLUtils.hpp#L55

This violates the standard.
> C++14 (N3797) [util.smartptr.shared.const] Requires: p shall be convertible to T*. Y shall be a complete type. The expression delete p shall be well formed, shall have well defined behavior, and shall not throw exceptions.

The issue is similar to the ones reported in https://github.com/capnproto/capnproto/issues/553 and https://github.com/dmlc/tvm/issues/2730.

Changing it to `auto comm = std::shared_ptr<NCCLComm>(new NCCLComm());` makes the code compile. This is the fix applied to the TVM issue (https://github.com/dmlc/tvm/pull/2731). But it's still undefined behavior when the destructor throws. 

## To Reproduce

Compile with `clang++` and `-stdlib=libc++`.

## Expected behavior

Code should compile with clang and libc++.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
Thanks for reporting.

Do you know whether this is clang specific or libc++ specific? CI is fine and we do compile with clang there, so I wonder what triggers this.

**Comment by haowu80s** [comment]
> Thanks for reporting.
> 
> Do you know whether this is clang specific or libc++ specific? CI is fine and we do compile with clang there, so I wonder what triggers this.

This is specific to `libc++`. Is there clang + libc++ build in your CI?

**Comment by pietern** [comment]
I'm not sure if we test explicitly with `libc++`, but per this issue, I highly doubt it :)

Looking at the related TVM issue this should be fixable by making the destructor `noexcept(true)`.

**Comment by pietern** [comment]
@haowu80s Can you give it a try with master? PR #29118 should fix this and was just merged.
