### ISSUE TITLE
Torch ONNX export broken for RandomUniform and RandomUniformLike

### ISSUE THREAD

**Issue by rajeevsrao** [pytorch/pytorch#28306]
## 🐛 Bug

`torch.onnx.export` reports issues in exporting models with `torch.rand` and `torch.rand_like`.

## To Reproduce

Enable Case 2 or Case 4 and run the example below:

```python
import torch
import torch.nn as nn

print(torch.__version__)

class test(torch.nn.Module):

    def __init__(self, vocab_size=10, rnn_dims=512):
        super().__init__()

    def forward(self, x):
        # CASE 1) RandomNormalLike - Works
        # mask = torch.randn_like(x).to(torch.float32)

        # CASE 2) RandomUniformLike - Broken
        # mask = torch.rand_like(x).to(torch.float32)

        # CASE 3) RandomNormal - Broken
        # mask = torch.randn(x.size()).to(torch.float32)

        # CASE 4) RandomUniform - Broken
        mask = torch.rand(x.size()).to(torch.float32)

        return mask


# PyTorch model
model = test()

input = torch.ones((1,256)).to(torch.float32).cuda()
output = model(input)
torch.onnx.export(model,
                  input,
                  'test_rand.onnx',
                  example_outputs=output)
```

Errors reported by the torch.onnx exporter:

Case 2:
```
UserWarning: ONNX export failed on ATen operator rand_like because torch.onnx.symbolic_opset9.rand_like does not exist
```

Cases 3 & 4:
```
TypeError: i_(): incompatible function arguments. The following argument types are supported: 1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node
```

## Expected behavior

ONNX RandomUniform export must by supported by torch and onnx model must be generated for all cases in the example script.

## Environment

 - PyTorch Version: 3.6
 - OS (e.g., Linux): Ubuntu 18.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): NA
 - Python version: 3.6
 - CUDA/cuDNN version: cuda 10.1 / cudnn 7.6.3
 - GPU models and configuration: 
GPU 0: GeForce GTX 1070 Ti
GPU 1: TITAN V
 - Any other relevant information:
[pip] torch==1.3.0
[pip] torchvision==0.4.1

## Additional context

NA

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
This PR will take care of case 2: https://github.com/pytorch/pytorch/pull/28470
But for cases 3 and 4, shape attribute of onnx random ops should be a constant, so current spec does not allow for exporting torch.rand(x.size())

**Comment by rajeevsrao** [comment]
@neginraoof since the change was backed out, can you please resubmit? Thanks.

**Comment by neginraoof** [comment]
This fix is merged: https://github.com/pytorch/pytorch/pull/29354

**Comment by rajeevsrao** [comment]
Thanks - didn't notice the second MR. Will confirm and close the issue.

**Comment by garymm** [comment]
Cases 1-4 all seem to work on PyTorch 1.10.0.
