### ISSUE TITLE
RRef.to_here() and local_value() should return future instead of blocking

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#28302]
`RRef.to_here()` and `RRef.local_value()` will block until the value is retrieved. However, there are use cases where the application might want to fetch values of multiple RRefs, where returning a future can help to overlap communication delays. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by xush6528** [comment]
#27943 and #28025 should close this? @mrshenli
