### ISSUE TITLE
[quantization] fix the seed for hypothesis in CI

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#28323]
Currently the hypothesis is semi-random on CI. We need to fix the seed to something constant.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by dskhudia** [comment]
Wouldn't that result in less coverage? Currently every run of hypothesis in CI tries some random examples from search space. If random seed is fixed, it will try the same examples. Wouldn't it?

**Comment by jerryzh168** [comment]
They are derandomized I think, as long as you import TestCase in common_utils.py

**Comment by z-a-f** [comment]
> Wouldn't that result in less coverage? Currently every run of hypothesis in CI tries some random examples from search space. If random seed is fixed, it will try the same examples. Wouldn't it?

My idea is that we run a fixed seed on CI in order ot make it deterministic, but locally we force it to run with a different seed every time. Ideas?
