### ISSUE TITLE
CUDA unavailable when pytorch 1.3.0.  installed with cudatoolkit 10.1

### ISSUE THREAD

**Issue by tharindu-mathew** [pytorch/pytorch#28321]
## 🐛 Bug

torch.cuda.is_available returns false

## To Reproduce

simply install pytorch conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

## Expected behavior

cuda being available

## Environment
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 410.104
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] intel-numpy==1.15.1
[pip3] numpy==1.15.1
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch

## Additional context

**Comment by peterjc123** [comment]
Please update your GPU driver to at least 418.39 for CUDA 10.1.

**Comment by pietern** [comment]
@tharindu-mathew Did updating the driver fix your issue?

**Comment by tharindu-mathew** [comment]
I'm unable to do that, right now. I downgraded to use cuda 10.  Closing the issue.

**Comment by eugene-kharitonov** [comment]
For those coming from google, like me, downgrading to cuda 10 is done like that: 
```
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
```

**Comment by vinhkhuc** [comment]
I got the same issue with Pytorch 1.3.1 + CUDA 10.0. Finally, I got it resolved with:
```
pip install torch==1.3.1+cu100 torchvision==0.4.2+cu100 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by ineventhorizon** [comment]
> I got the same issue with Pytorch 1.3.1 + CUDA 10.0. Finally, I got it resolved with:
> 
> ```
> pip install torch==1.3.1+cu100 torchvision==0.4.2+cu100 -f https://download.pytorch.org/whl/torch_stable.html
> ```

Thanks for your help. It worked for me.

**Comment by SimZhou** [comment]
Hey guys, I just got this issue solved as well, however by: 

`pip install torch==1.3.1+cu92 torchvision==0.4.2+cu92 -f https://download.pytorch.org/whl/torch_stable.html`

**My environment** is:
Windows 10
Geforce MX150
display driver 441.66 
nvidia cuda toolkit 10.1 (manually installed before installing pytorch)

while I got cuda.is_available() False with pytorch+cuda10.1

**Comment by darthbhyrava** [comment]
@SimZhou you have used `cu92` as a flag, which is for CUDA 9.2.
For CUDA 10.1, as instructed on the official page, simple use `$ pip install torch torchvision` without any flags.

**Comment by SimZhou** [comment]
> @SimZhou you have used `cu92` as a flag, which is for CUDA 9.2.
> For CUDA 10.1, as instructed on the official page, simple use `$ pip install torch torchvision` without any flags.

I couldn't get cuda10.1 working for some unknown reasons following the instructions on official page, and that's why I am here.  

And as well for unknown reasons, I managed to get it working by installing `torch==1.3.1+cu92 torchvision==0.4.2+cu92`, even if I got CUDA 10.1 pre-installed already in my PC. So I guess pytorch doesn't need cuda pre-installation, and even if you have that, they are still seperated.

**Comment by albertotono** [comment]
running 

`pip install torch==1.3.1+cu92 torchvision==0.4.2+cu92 -f https://download.pytorch.org/whl/torch_stable.html`

gave me this error, 

```
ERROR: Could not find a version that satisfies the requirement torch==1.3.1+cu100 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.4.0+cpu, 1.4.0+cu100, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.6.0+cu92)
ERROR: No matching distribution found for torch==1.3.1+cu100
```

**Comment by albertotono** [comment]
Ok, I needed to install python 3.6 first.
