### ISSUE TITLE
Copy from torch.QInt8Storage to torch.QInt8Storage isn't implemented

### ISSUE THREAD

**Issue by yuli-future-dreamer** [pytorch/pytorch#28328]
## 🐛 Bug

I want a deepcopy of a quantized model. However, when I am applying copy.deepcopy() to a quantized model, it returns to me "copy from torch.QInt8Storage to torch.QInt8Storage isn't implemented". What should I do?

## To Reproduce

1. Quantize a model follow the quantization tutorial. (model fuse + prepare + calibrate + convert)
2. apply copy.deepcopy() function to the quantized model

##Error message
Traceback (most recent call last):
  File "cm_and_ip_matrix.py", line 208, in plot_impact_matrix
    params_with_fault = copy.deepcopy(benign_params)
  File "/user/local/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/user/local/anaconda3/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/user/local/anaconda3/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/user/local/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 33, in __deepcopy__
    new_storage = self.storage().__deepcopy__(memo)
  File "/user/local/anaconda3/lib/python3.6/site-packages/torch/storage.py", line 28, in __deepcopy__
    new_storage = self.clone()
  File "/user/local/anaconda3/lib/python3.6/site-packages/torch/storage.py", line 44, in clone
    return type(self)(self.size()).copy_(self)
RuntimeError: copy from torch.QInt8Storage to torch.QInt8Storage isn't implemented

## Expected behavior

Return a completely new model.

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 14.04.6 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.3.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] numpydoc==0.8.0
[pip3] torch==1.3.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.4.1a0+d94043a
[conda] _tflow_select             2.3.0                       mkl    anaconda
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.3                      199    anaconda
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0    anaconda
[conda] mkl_random                1.0.2            py36hd81dba3_0    anaconda
[conda] pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.4.1                  py36_cpu  [cpuonly]  pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by raghuramank100** [comment]
This looks like a high-priority issue. @lly-zero-one : Can you flag it as such?.

**Comment by jerryzh168** [comment]
https://github.com/pytorch/pytorch/pull/28612

**Comment by jerryzh168** [comment]
should be working now, please check again. Feel free to reopen the issue if it still doesn't work.
