### ISSUE TITLE
Passing 'pretrained' parameter to torch.hub.load raises error

### ISSUE THREAD

**Issue by sipan17** [pytorch/pytorch#28332]
## 🐛 Bug

Tried to load FB released pre-trained model on Instagram on PyTorch Hub. It works without passing the 'pretrained' parameter. But if the parameter is passed it raises error. I think this will cause inconsistency with loading of other models.

## To Reproduce

model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x8d_wsl', pretrained=True)

TypeError: _resnext() got multiple values for argument 'pretrained'
## Expected behavior
Load the architecture with random weights if the 'pretrained' parameter is False, and with the pretrained weights if it is True.

**Comment by SsnL** [comment]
The error is due to their `hubconf`. See 
https://github.com/facebookresearch/WSL-Images/blob/c4dac640995f66db893410d6d4356d49a9d3dcc0/hubconf.py#L22-L39

You should open an issue in their repo. This repo is about pytorch core code.
