### ISSUE TITLE
None buffer doesn't get set by load_state_dict

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#28340]
## 🐛 Bug
A module might declare a buffer of unknown size in its init function by using:
```py
self.register_buffer('name', None)
```
The buffer might later contain a valid tensor. Saving this (now non-None) buffer with `state_dict()` works but loading this state dict to a newly instantiated module (where the buffer is currently None) with `load_state_dict()` fails as the buffer is unexpected.

## To Reproduce

1. Define a module with an empty buffer in the init function.
2. Set the buffer to something valid (e.g., in `forward`).
3. Call `state_dict()`
4. Instantiated a second instance of the module
5. call `load_state_dict()` on the second module

## Expected behavior

`load_state_dict()` replaces the currently None buffer with the non-None saved buffer from the state_dict.

## Environment
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.4.3
[pip] numpy==1.17.2
[pip] pytorch-pretrained-bert==0.6.2
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] torch                     1.0.1.post2              pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi

**Comment by pietern** [comment]
@twoertwein Are you interested in submitting a fix for this?

**Comment by twoertwein** [comment]
I can work on a fix :)

I just noticed that this might be a duplicate of issue https://github.com/pytorch/pytorch/issues/8104

To fix the issue, `load_state_dict` would need to get a list of all buffers (including None-buffers). If we make `named_buffers` aware of None buffers, they would also be saved in the `state_dict` which might not be a good idea, see https://github.com/pytorch/pytorch/issues/8104#issuecomment-395381167

I could Imagine an additional keyword argument for `named_buffers` to also return None-buffers (False by default; `state_dict` will not see them) but `load_state_dict` will request all buffers. If `load_state_dict` has no saved tensors for a currently None buffer, it should probably not throw an error?

**Comment by pietern** [comment]
Looking at the issue you link and discussion in linked issue, this turns out to be trickier than I expected...

You could opt to simply pass `strict=False` to `load_state_dict` and call it a day.

**Comment by twoertwein** [comment]
I currently use `strict=False` to avoid the error message and then load the unexpected keys myself. It works, but it feels like there should be a more elegant solution, after all the None-buffer was registered. I'm closing this issue in favour of https://github.com/pytorch/pytorch/issues/8104.
