### ISSUE TITLE
Error for quantize_dynamic(resnet18) + torch.jit.trace + ios-demo-app/PyTorchDemo

### ISSUE THREAD

**Issue by mirth** [pytorch/pytorch#28346]
## 🐛 Bug

I'm getting an error while loading quantized resnet18 on iphone with [ios-demo-app/PyTorchDemo](https://github.com/pytorch/ios-demo-app/tree/master/PyTorchDemo).

```
2019-10-20 16:33:20.005883+0300 PyTorchDemo[592:88998] false CHECK FAILED at /Users/distiller/project/aten/src/ATen/native/quantized/cpu/qlinear_dynamic.cpp
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/torchvision/models/resnet/___torch_mangle_59.py:288:8
    input49 = torch._convolution(input48, weight35, None, [1, 1], [1, 1], [1, 1], False, [0, 0], 1, False, False, True)
    input50 = torch.batch_norm(input49, weight36, bias17, running_mean17, running_var17, False, 0.10000000000000001, 1.0000000000000001e-05, True)
    input51 = torch.relu_(input50)
    input52 = torch._convolution(input51, weight37, None, [1, 1], [1, 1], [1, 1], False, [0, 0], 1, False, False, True)
    out6 = torch.batch_norm(input52, weight38, bias18, running_mean18, running_var18, False, 0.10000000000000001, 1.0000000000000001e-05, True)
    input53 = torch.add_(out6, input48, alpha=1)
    input54 = torch.relu_(input53)
    x = torch.adaptive_avg_pool2d(input54, [1, 1])
    x0 = torch.flatten(x, 1, -1)
    Y = ops.quantized.linear_dynamic(x0, _35)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return torch.to(Y, 6, False, False)
Compiled from code /Users/tolik/anaconda3/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/linear.py(42): forward
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(525): _slow_forward
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(539): __call__
/Users/tolik/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py(208): forward
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(525): _slow_forward
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(539): __call__
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(997): trace_module
/Users/tolik/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(858): trace
repro.py(17): <module>
```

## To Reproduce
Convert the model with:
```
import torch
from torchvision.models import resnet18

model = resnet18()
model.eval()
example = torch.rand(1, 3, 224, 224)

traced_script_module = torch.jit.trace(model, example)
traced_script_module.save('/tmp/resnet18_float32.pt')


model = resnet18()
model.eval()
example = torch.rand(1, 3, 224, 224)

model = torch.quantization.quantize_dynamic(model, dtype=torch.qint8)
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save('/tmp/resnet18_qint8.pt')
```

Run the [ios-demo-app/PyTorchDemo](https://github.com/pytorch/ios-demo-app/tree/master/PyTorchDemo) with `resnet18_qint8.pt`. Get the stacktrace above.
Here is the forked demo with coverted models: [mirth/ios-demo-app](https://github.com/mirth/ios-demo-app)

## Expected behavior
For default image demo with `mobilenet_quantized.pt` i'm getting ~50ms per frame on iPhone 6s.
For `resnet18_float32.pt` on same iPhone i'm getting ~250ms per frame.
For `resnet18_qint8.pt` i'm getting an error with stacktrace above.
I'm expecting no error.

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] mkl                       2018.0.0             hc285769_4
[conda] mkl-service               1.1.2            py36h7ea6df4_4
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

cc @suo @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by lly-zero-one** [comment]
Could you take a look? @jamesr66a

**Comment by supriyar** [comment]
quantize_dynamic is now supported on mobile, so this should work now.
