### ISSUE TITLE
arange sometimes changes dimensionality of output tensor

### ISSUE THREAD

**Issue by leopd** [pytorch/pytorch#28347]
## 🐛 Bug

Using `torch.arange` with an `out=` target Tensor object, it will sometimes change the dimensionality of the target Tensor.  I'm creating a (1,N) tensor, and sometimes calling `arange` changes it to a (N+1) vector.  Same on cuda or cpu.

## To Reproduce

```python
import torch
  
for N in range(45,100):
    print(f"Trying {N}...")
    line = torch.zeros(size=(1,N))
    print(f"  Before arange shape is {line.shape}")
    assert len(line.shape) == 2
    torch.arange(-1, 1, 2/N, dtype=torch.float32, out=line)
    print(f"  After arange shape is {line.shape}")
    assert len(line.shape) == 2
```

This will output:
```
Trying 45...
  Before arange shape is torch.Size([1, 45])
  After arange shape is torch.Size([1, 45])
Trying 46...
  Before arange shape is torch.Size([1, 46])
  After arange shape is torch.Size([1, 46])
Trying 47...
  Before arange shape is torch.Size([1, 47])
  After arange shape is torch.Size([1, 47])
Trying 48...
  Before arange shape is torch.Size([1, 48])
  After arange shape is torch.Size([1, 48])
Trying 49...
  Before arange shape is torch.Size([1, 49])
  After arange shape is torch.Size([50])
Traceback (most recent call last):
  File "shapebug.py", line 10, in <module>
    assert len(line.shape) == 2
AssertionError
```

## Expected behavior

`torch.arange` should not change the shape of the target Tensor.

## Environment

PyTorch 1.3, Ubuntu 18.04LTS, py 3.6.9 under Anaconda.  In detail (from `collect_env.py`):

```
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 1070 with Max-Q Design
Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] facenet-pytorch==0.3.1
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] facenet-pytorch           0.3.1                    pypi_0    pypi
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu100    pytorch
```

## Additional context

I started doing it this way (out= Tensor) because I wanted to make sure the whole thing to happen on GPU, and that was the first thing I figured out.  I see another way to do this now -- `line=torch.arange(device='cuda')` which works.  But this seems like a bug.

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by pietern** [comment]
Thanks for the report. Does this always happen at `N=50`?

**Comment by prasunanand** [comment]
This also happens at `N=98, 103, 107, 196`. I can work on a fix.

**Comment by gchanan** [comment]
The description of the issue isn't quite right.

This happens when the computed number of elements of the output doesn't match the number of elements of the input.  In the cases you found, that happens because floating point math isn't exact.

Try it in python3:
```
>>> math.ceil((1 - -1)/(2/49))
50
```

The behavior for `arange(..., out=)` is to resize the input to the computed shape (which is always 1-dimensional) when the number of elements doesn't match.

This behaves differently from most torch functions in that is "friendlier" in that it will accept a shape that gets the number of elements correct instead of the exact shape.

But when you  combine these things, the behavior is surprising.

There are a number of things we can do:
1) Always return a 1-d shape
2) Try to retain the dimensionality of the input (note: this is not possible in general, but we could do things like support shapes of the form `(1, ..., 1, x, 1, ..., 1)` where `x != 0`.
3) Give a hard error on resize.

**Comment by gchanan** [comment]
Also, at a minimum, we should document the behavior of arange -- it behaves differently than other functions but isn't documented as such.

**Comment by gchanan** [comment]
A short term improvement would be to warn if the output tensor has more than 0 elements but not the correct number of elements.

**Comment by leopd** [comment]
Yeah, the curse of being friendly is the surprises when the system is helpful in unexpected ways.  It's always a trade-off.

A warning certainly would have saved me a chunk of debugging.  But IMHO a hard error on re-size makes sense, because when I supply something to out= I expect the same thing to come back more or less.  But y'all know much better than I do how to make it consistent with the rest of the system, which is probably the most important thing.

Thanks!

**Comment by leopd** [comment]
(Sorry didn't mean to close - mouse slipped.)

**Comment by prasunanand** [comment]
I am working on a PR.

**Comment by gchanan** [comment]
@prasunanand I laid out a number of options -- which are you taking?

**Comment by prasunanand** [comment]
I would like to go with "Give a hard error on resize."

**Comment by gchanan** [comment]
high priority to at least warn.
