### ISSUE TITLE
Quantisation of object detection models.

### ISSUE THREAD

**Issue by vikashranjan** [pytorch/pytorch#28357]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Any examples to quantise object detection models ?

I get the following error when I follow the quantization tutorial for a Faster-RCNN model.

```RuntimeError: Didn't find kernel to dispatch to for operator 'quantized::conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch keys are: [QuantizedCPUTensorId] (lookup_ at /pytorch/aten/src/ATen/core/dispatch/DispatchTable.h:249)```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by lly-zero-one** [comment]
It seems you passed the normal Tensor to quantized kernel. Could you check whether you add quant for the input tensor?

**Comment by vikashranjan** [comment]
I used the following to quantise input tensor 
```
scale, zero_point, dtype = 1.0, 2, torch.qint8
quantize_tensor = torch.nn.quantized.Quantize(scale, zero_point, dtype)
input_tensor=quantize_tensor(input_tensor)

```
I now get the following error.

```RuntimeError: No function is registered for schema aten::empty.memory_format(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, MemoryFormat? memory_format=None) -> Tensor on tensor type QuantizedCPUTensorId; available functions are CPUTensorId, CUDATensorId, MkldnnCPUTensorId, SparseCPUTensorId, SparseCUDATensorId, VariableTensorId```

It will be helpful if there is any sample code to apply quantisation to TORCHVISION object detection models.

**Comment by raghuramank100** [comment]
We are working on adding support for torchvision classification models and PRs: https://github.com/pytorch/vision/pull/1471 and https://github.com/pytorch/vision/pull/1503 will add this support.

**Comment by vikashranjan** [comment]
Thanks, @raghuramank100

**Comment by aminsabetsarvestani** [comment]
Hi, I was wondering if you manage to implement the quantized Faster RCNN ? I'm getting the same error as schema aten::empty.memory_format(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, MemoryFormat? memory_format=None) -> Tensor on tensor type QuantizedCPUTensorId; available functions are CPUTensorId, CUDATensorId, MkldnnCPUTensorId, SparseCPUTensorId, SparseCUDATensorId, VariableTensorId
