### ISSUE TITLE
output of torch.autograd.grad

### ISSUE THREAD

**Issue by harkiratbehl** [pytorch/pytorch#28362]
## 📚 Documentation

What is the return value of torch.autograd.grad function? The common way is to just use it like this:
gradients = torch.autograd.grad(loss, model.parameters())

which is fine. But I have also seen people using this:
(gradients,) = torch.autograd.grad(loss, model.parameters())

I just want to know the exact return values of the grad function.

**Comment by albanD** [comment]
Hi,

Pleas use the forum: https://discuss.pytorch.org/ to ask questions.

For your particular question, the doc [here](https://pytorch.org/docs/stable/autograd.html#torch.autograd.grad) should give you all the informations. Basically the same thing as the inputs.
