### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/maxcpucount:8']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by sagarpant1** [pytorch/pytorch#28369]
[build.log](https://github.com/pytorch/pytorch/files/3751883/build.log)

When compiling the PyTorch from Github, after I execute

python setup.py install

after a few minutes, the following problem occurs:

subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/maxcpucount:8']' returned non-zero exit status 1.

I have also added logs which should help in better debugging of the issue.
I am trying to compile PyTorch using clang by setting both CC and CXX variables.

Does anyone have any idea about this? Any help would be appreciated.

Also, I found a similar issue on Github (https://github.com/pytorch/pytorch/issues/20420) but the errors were different. It was because of "Host compiler targets unsupported OS" but my attached logs don't mention anything like it.

cc @peterjc123

**Comment by peterjc123** [comment]
The actual error is 
```
E:\Repos\pytorch\aten\src\ATen/core/ATenDispatch.h(234): error C3520: 'value': parameter pack must be expanded in this context (compiling source file E:\Repos\pytorch\aten\src\ATen\ParallelOpenMP.cpp) [E:\Repos\pytorch\build\caffe2\torch.vcxproj]
  E:\Repos\pytorch\build\aten\src\ATen/core/TensorMethods.h(65): note: see reference to function template instantiation 'Result at::ATenOpTable::callUnboxed<void,const at::Tensor&,const at::Tensor&,bool,bool>(const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
          with
          [
              Result=void
          ] (compiling source file E:\Repos\pytorch\aten\src\ATen\ParallelOpenMP.cpp)
  SparseTensorImpl.cpp
  TensorGeometry.cpp
E:\Repos\pytorch\aten\src\ATen/core/ATenDispatch.h(235): error C2440: 'default argument': cannot convert from 'nullptr' to 'enable_if<_Test,_Ty>::type' [E:\Repos\pytorch\build\caffe2\torch.vcxproj]
          with
          [
              _Ty=std::nullptr_t
          ] (compiling source file E:\Repos\pytorch\aten\src\ATen\ParallelOpenMP.cpp)
  E:\Repos\pytorch\aten\src\ATen/core/ATenDispatch.h(235): note: 'enable_if<_Test,_Ty>::type' may be a value type at runtime: consider using 'enable_if<_Test,_Ty>::type()' instead
          with
          [
              _Ty=std::nullptr_t
          ] (compiling source file E:\Repos\pytorch\aten\src\ATen\ParallelOpenMP.cpp)
```
We saw the similar error report at the pytorch/vision side, and finally solved that by using the native toolchain of VS 2017/2019. Would you please tell me a bit more about your MSVC environment?

**Comment by sagarpant1** [comment]
I am using Visual Studio 16 2019 Enterprise edition

**Comment by peterjc123** [comment]
I don't think clang is used here because the message style in the log is still the MSVC one. Anyway, you can update VS 2019 to a newer version, which may solve this problem.

**Comment by peterjc123** [comment]
Modifying the variable CC and CXX is only available if you have ninja installed. Please try `pip install ninja` first and make sure you do `python setup.py install --cmake` to wipe out the cache file in CMake.

**Comment by sagarpant1** [comment]
Thanks a lot @peterjc123 
I'll follow your resolution steps and get back to you with whatever the outcome is.

**Comment by phalexo** [comment]
My build runs for a while and then fails, g++ is 5.5., cuda 10.1, Ubuntu 14.04 with Xenial kernel 4.4.0 generic.

[3108/3369] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/autograd/generated/python_torch_functions.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/developer/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/developer/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/home/developer/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.

**Comment by peterjc123** [comment]
Would you please open a new issue and post the full log there?

**Comment by peterjc123** [comment]
The original issue https://github.com/pytorch/pytorch/issues/28369#issuecomment-544793834 is resolved.
