### ISSUE TITLE
Execution of traced function results in unexpected modification of an argument

### ISSUE THREAD

**Issue by IlyaOvodov** [pytorch/pytorch#28360]
## 🐛 Bug
Execution of traced function results in unexpected modification of an argument

## To Reproduce
```
def func(x):
    s = 0
    s += x
    s += x
    return s
x = torch.ones(2,2)
func = torch.jit.trace(func, x)
print('x',x) # tensor([[1., 1.], [1., 1.]]) as expected
_ = func(x)
print('x',x) # tensor([[2., 2.], [2., 2.]])  surprisingly x have changed while it shouldn't!
```

## Expected behavior
argument shouldn't change

## Environment

Collecting environment information...
PyTorch version: 1.3.0a0+de394b6
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Њ ©Єа®б®дв Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 411.31
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] pytorch-ignite==0.2.0
[pip3] pytorch-toolbelt==0.2.1
[pip3] segmentation-models-pytorch==0.0.2
[pip3] torch==1.3.0a0+de394b6
[pip3] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] cuda92                    1.0                           0    pytorch
[conda] mkl                       2019.0                    <pip>
[conda] mkl                       2019.0                      118  
[conda] mkl-include               2019.0                    <pip>
[conda] mkl-include               2019.0                      118  
[conda] mkl_fft                   1.0.6            py36hdbbee80_0  
[conda] mkl_random                1.0.1            py36h9258bd6_0  
[conda] pytorch-ignite            0.2.0                     <pip>
[conda] pytorch-toolbelt          0.2.1                     <pip>
[conda] segmentation-models-pytorch 0.0.2                     <pip>
[conda] torch                     1.3.0a0+de394b6           <pip>
[conda] torchvision               0.4.0                     <pip>
[conda] torchvision               0.4.1a0+d94043a           <pip>

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by suo** [comment]
Thanks for the report! This looks like a serious bug in an optimization pass, I will investigate today.

**Comment by suo** [comment]
One of our peephole optimizations assumes Tensor `x` + scalar 0 can be replaced with just `x`. This is of course not true if there is a reference to `x` living anywhere in the graph (since the `add` operator will not create a copy as it should). I will put up a fix when I get a sec today, sorry for what I presume was an annoying bug.

**Comment by suo** [comment]
re-assigning to @Krovatkin as he is going to look into this
