### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by ashishpatel26** [pytorch/pytorch#28363]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-eb42ca6e4af3> in <module>
----> 1 import torch

~\.conda\envs\py3\lib\site-packages\torch\__init__.py in <module>
     79 del _dl_flags
     80 
---> 81 from torch._C import *
     82 
     83 __all__ += [name for name in dir(_C)

ImportError: DLL load failed: The specified module could not be found.

cc @peterjc123

**Comment by peterjc123** [comment]
Please post more info here about your environment. Otherwise, the issue will be closed.
