### ISSUE TITLE
`at::parallel_for` does not propagate thread-local variables to child threads in embedding_renorm_

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#28370]
See repro below:

```python
import torch

def run(val):
    print("Running :", val)
    weights = torch.rand(100, 64, requires_grad=True)
    inp = torch.rand(val).mul(100).long()
    with torch.no_grad():
        torch.embedding_renorm_(weights, inp, 1.0, 2)
    print("This should be None: ", weights.grad_fn)

run(1000)
run(1001)
```
Outputs:
```
Running : 1000
This should be None:  None
Running : 1001
This should be None:  <CopySlices object at 0x7f02faa5e7a8>
```

Current supposition is that multi-threaded operations and thread local NoGradGuard could be problematic.

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL @albanD @gqchen @VitalyFedyunin @ngimel @mruberry

**Comment by albanD** [comment]
## Identification of the current problem
So the problem is that `parallel_for` does not propagate thread local states into the thread pool it uses.
The problematic states here are the `GradMode::enabled` and wether or not to unwrap variables during dispatch.
Indeed, in the original function, we work with Tensors and GradMode is disabled. While in some of the worker threads, we now work with Variables and with GradMode enabled.

But after a quick look, others could be leading to unexpected behavior as well like
- `in_parallel_region_` used to check whether we are already in a parallel region, worker threads could actually re-spawn more threads in some cases?
- many jit stuff
- cuda current streams

## Main question

Is `parallel_for` supposed to be usable with Tensors. And so running operations on Tensors in each worker thread should do the same thing?
Or is `parallel_for` supposed to work only with pointers of raw data: Tensors should be unpacked before and only pointers should be passed to it?

## Proposed answer

After discussion, the main point is that making `parallel_for` work with Tensor operations is actually a big feature.
So for now we can fix this function to remove the use of Tensors and add a comment with `parallel_for` to let the user know that they should unpack all Tensors before doing operations.
We can open a new feature request for support of Tensors in `parallel_for`.

Any thoughts @ifedan @ngimel @VitalyFedyunin @ezyang  ?

**Comment by gchanan** [comment]
> After discussion, the main point is that making parallel_for work with Tensor operations is actually a big feature.

This statement is a bit ambiguous to me.  By big feature, do you mean "a lot of work" or "an important feature"?

**Comment by albanD** [comment]
@gchanan sorry, I meant "a lot of work". Updated above.
In particular, it would require for it to work and be sustainable to have a common way of using thread_local across the code base. Both to ensure that this actually works in all corner cases and that when new thread_local variables are added, this does not break.

**Comment by gchanan** [comment]
This analysis looks correct -- I'd file an issue about collecting the thread_locals across the code base to support that kind of thing.
