### ISSUE TITLE
Per-TensorTypeId fallthrough opt-in

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#28386]
@mcarilli shares with me a use case that is not handled well by the current dispatcher. He would like to provide a toggleable AMP mode that, when turned on, results in specific functions calling an AMP implementation, rather than the usual VariableType implementation. While this can be implemented using boxed fallback (#26368) it is a bit awkward, because the implementor has to write a giant if statement inside their single generic function to match out specific function cases. Instead, it would be nice if they could just override the handful of functions they want, and then fall through to the next TensorTypeId in the dispatch line.

So, our specific proposal is this:

* TensorTypeId can opt into "fallback" dispatch. We maintain a set of tensor type ids with this behavior.
* In ATenDispatch, before the `reportError` test, we add a new condition. If the tensor type id is in the fallback dispatch set, we disable the selected tensor type id (in TLS) and redispatch.

This wasn't in the original dispatch proposal, so I want to get feedback on it first.

An alternative is to used the boxed fallback dispatch to implement this passthrough behavior, but it feels like such a heavy hammer for this nail. I think it should just be supported internally.

cc @smessmer @zdevito @gchanan @bwasti

**Comment by bwasti** [comment]
I'm not really sure the implementation details here.  Using `registerOp` for normal overrides and then `registerFallbackBoxedOp` to strip the TensorTypeId from the typeset and re-dispatch seems like a really easy thing to pull of with the current API.  I don't understand where the if-statement comes in.

**Comment by smessmer** [comment]
- call it "fallthrough" dispatch instead of "fallback" dispatch, I think we have too many things we're calling "fallback" right now.
- This will degrade perf for ops going through fallthrough dispatch but not for ops that find a kernel before fallthrough.
- How are you planning to support AMP with this? Will there be an AMPTensorId that has fallthrough enabled? Does this mean all our tensors will have AMPTensorId set, i.e. all will suffer the perf degradation?

**Comment by ezyang** [comment]
> Using registerOp for normal overrides and then registerFallbackBoxedOp to strip the TensorTypeId from the typeset and re-dispatch seems like a really easy thing to pull of with the current API. I don't understand where the if-statement comes in.

Yeah, there are a few reasons why I don't want to recommend @mcarilli use fallback boxed op here:
* It's a pointless slowdown for his use case. He doesn't actually need or want dispatch to go through the boxed path, but using the boxed fallback will go through a lot of pointless boxing, and call to JIT, and then unboxing to get back out again. (Also there's the really slow Operator lookup, although that could be fixed.)
* To add insult to injury, boxed fallback doesn't even support all operations (because the templates don't understand all argument types).

> This will degrade perf for ops going through fallthrough dispatch but not for ops that find a kernel before fallthrough.

Yes, it only degrades perf for people using fallthrough. As there are no current uses of fallthrough, it only degrades perf for, e.g. AMP

> How are you planning to support AMP with this? Will there be an AMPTensorId that has fallthrough enabled? Does this mean all our tensors will have AMPTensorId set, i.e. all will suffer the perf degradation?

Yes and no. AMPTensorId is a mode tensor id (btw, another reason why TensorId is a terrible name), so it will get set in TLS when you turn on AMP and that's how it will show up everywhere.

**Comment by bwasti** [comment]
> It's a pointless slowdown for his use case.

How much of a slowdown?  Is this unavoidable & consequential?

> boxed fallback doesn't even support all operations

Seems unrelated.

**I support the idea of registering an easy fallback.** However, since this proposal implies some implementation details, I'd like to also clarify that I believe this should be built on top of the current APIs first.  I think we should avoid adding yet another special set of IDs that are handled differently until we know that this class of ID is common and should get its own fast path.

**Comment by ezyang** [comment]
> Seems unrelated.

I mean, in the very short term, it has an immediate impact for the usability of AMP. As long as boxed fallback doesn't support inplace operations, an AMP implementation that uses boxed fallback will choke if you call an inplace operation inside of the AMP-ified region. An AMP implementation that uses fallthrough as described in the proposal above will support all operations immediately out of the box.

> How much of a slowdown? Is this unavoidable & consequential?

I mean, you're the one who knows best, having done benchmarking on lazy tensor :) However, I don't want to stress the performance argument too much; the argument is more from a first principles, "don't write code that does useless work." The useless work in this case is taking unboxed inputs, converting them into boxed representation, invoking the JIT on the boxed inputs, and then unboxing them again when we get out. The conversion here is completely avoidable.

**Comment by ezyang** [comment]
Obsoleted bby https://github.com/pytorch/pytorch/issues/29548
