### ISSUE TITLE
Enable applying min, max, argmin, argmax over nonzero dims of tensor containing dims of size 0

### ISSUE THREAD

**Issue by LeonhardFeiner** [pytorch/pytorch#28380]
## 🚀 Feature
Applying `tensor.min(dim)`, `tensor.max(dim)`, `tensor.argmin(dim)`, `tensor.argmax(dim)` causes an error when any dimension of the tensor is of size 0. 
```
>>> torch.zeros((2,0)).max(0)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```
In my opinion this error should only be thrown, if the `dim` is associated to a dimension which is of size 0. 

## Motivation

The current behavior is inconsistent with numpy and requires unnecessary case handling for empty tensors.
```
>>> np.zeros((2,0)).max(0)
array([], dtype=float64)
```
## Pitch

Return empty tensors instead of raising an exception.

```
>>> torch.zeros((2,0)).max(0)
torch.return_types.max(
values=tensor([]),
indices=tensor([], dtype=torch.int64))
```

**Comment by pietern** [comment]
@LeonhardFeiner Are you interested in submitting a PR for this?

**Comment by oguzserbetci** [comment]
I would like to try submitting a PR, but I can't even figure out where I should look at. I'd appriciate if someone can point me to the related code.

**Comment by oguzserbetci** [comment]
#35062 #34907 There is already an effort to fix this for max and min. I will try to understand the changes and port it to argmin and argmax.

**Comment by heitorschueroff** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/52565
