### ISSUE TITLE
torch.cuda.Tensor.bernoulli() missing

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#2838]
```python
import torch
torch.Tensor([0.5]).bernoulli() # works
torch.Tensor([0.5]).cuda().bernoulli() # fails:
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# AttributeError: 'torch.cuda.FloatTensor' object has no attribute 'bernoulli'
```

This used to work before I updated to the master (my previous version was before Variable / ATen big change).

**Comment by soumith** [comment]
hmm, this looks like it was a bug introduced as part of some kind of definition cleanup.
Maybe https://github.com/pytorch/pytorch/pull/2578
cc: @killeent

**Comment by killeent** [comment]
@soumith bisected this correctly. I am working on a fix, requires changing the cwrap code a little bit.
