### ISSUE TITLE
Where did the GPU memory go

### ISSUE THREAD

**Issue by ebarsoum** [pytorch/pytorch#28394]
Hi Guys,

I am trying to understand the overhead of GPU allocation. I run the below 2 code snip-it on Titan V GPU with PyTorch 1.3.

First code use PyTorch to allocate a small tensor, here what I get:

Before: used GPU Memory: 0.9375 MB
Max memory cached: 2.0 MB
After: used GPU Memory: 1008.1875 MB

The actual memory cache in PyTorch allocator is pretty small, but the overall CUDA allocation is around 1 GB.

Second code use PyCuda to allocate a similar tensor, here what I get:

Before: used GPU Memory: 0.9375 MB
After: used GPU Memory: 320.1875 MB

In the second repro, CUDA overhead is 320MB. 

I would expect that CUDA overhead will be similar in both cases. Are those results expected? (The value of the overhead depend on the GPU)

Here PyTorch repro:
```python
import torch
import numpy as np
from pynvml.smi import nvidia_smi

nvsmi = nvidia_smi.getInstance()

def getGPUMemoryUsage(gpu_index=0):
    return nvsmi.DeviceQuery("memory.used")["gpu"][gpu_index]['fb_memory_usage']['used']

gpu_index = 0
device = torch.device('cuda:0')

print("Before: used GPU Memory: {} MB".format(getGPUMemoryUsage(gpu_index)))

torch_tensor = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float32)).to(device)

print("Max memory cached: {} MB".format(torch.cuda.max_memory_cached() / (1024*1024)))
print("After: used GPU Memory: {} MB".format(getGPUMemoryUsage(gpu_index)))
```

Here PyCuda repro:
```python
import numpy as np
from pynvml.smi import nvidia_smi
import pycuda.gpuarray as ga
import pycuda.driver as cuda

nvsmi = nvidia_smi.getInstance()

def getGPUMemoryUsage(gpu_index=0):
    return nvsmi.DeviceQuery("memory.used")["gpu"][gpu_index]['fb_memory_usage']['used']

gpu_index = 0

print("Before: used GPU Memory: {} MB".format(getGPUMemoryUsage(gpu_index)))

cuda.init()
context = cuda.Device(gpu_index).make_context()

tensor_gpu = ga.to_gpu(np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float32))

print("After: used GPU Memory: {} MB".format(getGPUMemoryUsage(gpu_index)))
context.pop()
```

**Comment by soumith** [comment]
yes, you are not taking into account  the pytorch, cudnn, nccl GPU kernels being loaded into GPU memory in the former case(PyCuda doesn't have any kernels loaded).

**Comment by ebarsoum** [comment]
Thanks @soumith , I didn't expect that the delta is that large.
