### ISSUE TITLE
[Quantization] (Error): No function is registered for schema aten

### ISSUE THREAD

**Issue by jiacheng1gujiaxin** [pytorch/pytorch#28404]
## ❓ Questions and Help
    I tried to quantizate my own shuffle model through 'STATIC QUANTIZATION WITH EAGER MODE IN PYTORCH'.
    But when it comes to forward propagation, the time to assess model losses, I failed:

    ```
RuntimeError: No function is registered for schema aten::native_batch_norm(Tensor input, Tensor? weight, Tensor? bias, Tensor? running_mean, Tensor? running_var, bool training, float momentum, float eps) -> (Tensor, Tensor, Tensor) on tensor type QuantizedCPUTensorId; available functions are CPUTensorId, CUDATensorId, MkldnnCPUTensorId, VariableTensorId
The above operation failed in interpreter, with the following stack trace:
at code/__torch__/shuff_slim/___torch_mangle_297.py:316:13
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by aa12356jm** [comment]
me too

**Comment by raghavsonavane** [comment]
Currently, the support for modules is experimental and includes only Conv2d, Linear, ReLU, MaxPool2d. Details for which is given here: https://github.com/pytorch/pytorch/wiki/torch_quantization_design_proposal
That means, you need to either convert your native modules to supported modules or fuse onto these modules.

**Comment by jerryzh168** [comment]
Yeah, please fuse batchnorm, see tutorial: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html

**Comment by jerryzh168** [comment]
I'm going to close this for now, feel free to reopen if the issue persists

**Comment by jiacheng1gujiaxin** [comment]
> me too

you can  fuse the batchnorm or merge it with conv manually

**Comment by raghavgurbaxani** [comment]
@jiacheng1gujiaxin  merge it manually ? how ?

**Comment by raghavgurbaxani** [comment]
@jerryzh168  I am still stuck on this issue, could you please help ? 
I have already put in the Qstub and Destub blocks, but I am stuck on the layer fusion part. 

I am trying to use the model here -
https://github.com/clovaai/CRAFT-pytorch/blob/master/craft.py

**Comment by liwei46** [comment]
@jerryzh168 Hello, does the fusion, support batch norm before convolution? Thanks.

**Comment by ChaoLi977** [comment]
How to merge batch_norm layer with conv layer?
