### ISSUE TITLE
Caffe2: how can I get channels in some positions during ResNet

### ISSUE THREAD

**Issue by banshee1** [pytorch/pytorch#28416]
I am doing a project with caffe2, python2. Now I have a problem and don't know what to do.

I am running ResNet50 with I3D.

Here is what I am trying to do:
    the feature map out from res2 is (2,256,16,64,64) with respect to (batch, channels, temp, width,height)
 I want to get the channels of one position to form a feature vector. For example, with coordinate (0,32,34), I need to get the channel vector at position(32,34), batch 0, i.e. (0,256,16,32,34). With 10 such coordinate tuples I will have 10 (256,16,1,1) feature maps.

   Is there anyone who can help me figure this out? Plz help me !

**Comment by banshee1** [comment]
Is there anyone who can help me? plzzzz!

**Comment by soumith** [comment]
The caffe2 frontend is unsupported now and will slowly be deprecated. Hence, we're not looking to add code or answer questions on this module unless critical.
