### ISSUE TITLE
The docstring for torch.addcdiv can't be correct

### ISSUE THREAD

**Issue by ngoldbaum** [pytorch/pytorch#28430]
## 📚 Documentation

Currently the signature of `torch.addcdiv` is documented to be:

```
addcdiv(input, value=1, tensor1, tensor2, out=None) -> Tensor
```

See e.g. https://pytorch.org/docs/stable/torch.html#torch.addcdiv

This can't be correct because it has positional arguments following keyword arguments, which is invalid in Python.

When I intentionally pass an invalid number of arguments, I get:

```
In [10]: torch.addcdiv(t, 0.1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-38c653649e23> in <module>
----> 1 torch.addcdiv(t, 0.1)

TypeError: addcdiv() received an invalid combination of arguments - got (Tensor, float), but expected (Tensor input, Tensor tensor1, Tensor tensor2, Number value, Tensor out)
```

So I guess `value` *is* optional and it should be moved to the end of the argument list.  However, I wanted to double check before putting in a PR with the fix since that means that the doctest in the docstring for `addcdiv` is incorrect.

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL

**Comment by ngoldbaum** [comment]
addcmul has the same problem: https://pytorch.org/docs/stable/torch.html#torch.addcmul

**Comment by fmassa** [comment]
The docstring is actually (partially) correct.

The `value` is the second argument, but only in the case where the second argument is not a tensor.

```python
In [32]: a = torch.ones(3); b = torch.ones(3) * 2; c = torch.ones(3) * 3

# do not pass optional "value"
In [38]: torch.addcdiv(a, b, c)
Out[38]: tensor([1.6667, 1.6667, 1.6667])

# pass optional "value", but by position
In [39]: torch.addcdiv(a, 3, b, c)
Out[39]: tensor([3., 3., 3.])

# can also pass "value" by keyword
In [40]: torch.addcdiv(a, b, c, value=3)
Out[40]: tensor([3., 3., 3.])
```

This unfortunate behavior is legacy from Lua-Torch, where named arguments did not exist, so we needed to have a way to make a difference between different overloads of the function.

Changing this behavior is unfortunately a BC-breaking change, but I think it would probably be worth considering, given how confusing it is (and how it makes our parser more complicated)

@gchanan for thoughts

**Comment by ngoldbaum** [comment]
Ah, thank you! That make more sense. It's definitely a little surprising for a Python module to behave that way.

I also noticed that ranint_like is also listed has having a positional argument (`high`) after a keyword argument (`low=0`): https://pytorch.org/docs/stable/torch.html#torch.randint_like.

For context, I'm going through the whole torch API right now to support work on `__torch_function__` and noticing some of these oddball cases :)

**Comment by gchanan** [comment]
IMO we should:
1) document the signature as `addcdiv(input, tensor1, tensor2, *, value=1, out=None) -> Tensor`

2) actually deprecate (print a deprecated warning) for the overloads to addcdiv, addcmul).

**Comment by gchanan** [comment]
high priority to at least get the deprecation in.

**Comment by gchanan** [comment]
@peterbell10 someone over here is going to take this.

**Comment by peterbell10** [comment]
Really, I already have the code for the deprecation warnings in place. I just have some weird test failures that I hadn't worked out yet. https://github.com/pytorch/pytorch/compare/master...peterbell10:warn_deprecations

**Comment by gchanan** [comment]
ok, assigning it back to you.  Thanks for the update.
