### ISSUE TITLE
image_resize

### ISSUE THREAD

**Issue by weigq** [pytorch/pytorch#2845]
Is there any plan to add image resize function like `tf.resize.resize_images()` or `cv.imresize()`?
at present, I achieve it by: convert the `tensors` to `ndarray`, then use `scipy.misc.imresize()` to resize and convert back.

**Comment by chenzhekl** [comment]
There is [`torchvision.transforms.Scale`](http://pytorch.org/docs/master/torchvision/transforms.html#torchvision.transforms.Scale) in torchvision.

**Comment by weigq** [comment]
thx
