### ISSUE TITLE
at::Tensor::data() is deprecated but no other way is suggested for cpp extensions

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#28472]
## 🐛 Bug

Even the official [docs for cpp extensions](https://pytorch.org/tutorials/advanced/cpp_extension.html) use `gates.data<scalar_t>()` but I get deprecation warning.

## To Reproduce

>  warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]                                                                                                                               /home/ehazar/miniconda3/envs/py3_night/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:312:1: note: declared here                                                                                                                                                 T * data() const {

## Expected behavior

Provide a non-deprecated way for cpp extensions. Similarly, no alternative to `AT_CHECK`/`AT_ASSERTM` nor `torch::jit::RegisterOperators()` is provided for cpp extensions.

## Environment

Collecting environment information...
PyTorch version: 1.4.0.dev20191018
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.40.04
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.4.0.dev20191018
[pip] torchvision==0.5.0a0+155c504
[conda] Could not collect

cc @yf225

**Comment by shiyemin** [comment]
I use .data_ptr to replace .data. There is no warning then. But i am not sure whether this is the suggedted api.

**Comment by fmassa** [comment]
As @shiyemin mentioned, `.data_ptr<scalar_t>()` is the recommended approach now.
For `AT_CHECK`, use `TORCH_CHECK`.
For `torch::jit::RegisterOperators()`, use `torch::RegisterOperators()`

**Comment by malfet** [comment]
This has been implemented by https://github.com/pytorch/pytorch/pull/25319
```
 warning: ‘T* at::Tensor::data() const [with T = c10::complex<float>]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]

```
