### ISSUE TITLE
Behavior of __setattr__ and __getattr__ not consistent

### ISSUE THREAD

**Issue by ddkang** [pytorch/pytorch#2848]
__setattr__ will fall back and set the attribute of non-PyTorch attributes if it is not a parameter, etc.: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L341

__getattr__ does not fall back: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L296

**Comment by chenzhekl** [comment]
Why do we want to set a new attribute when trying to fetch a non-existent one?  It is more of a bug in the code, I think.

**Comment by alykhantejani** [comment]
I don't think this is a bug, `__getattr__` is called when an attribute lookup has not found the attribute in the usual places (i.e. it is not an instance attribute nor is it found in the class tree for self). For example, this works fine:

```
import torch
from torch import nn
mod = nn.Module()
mod.val = 5
print(mod.val)
>>>5
getattr(mod, 'val')
>>>5
```

**Comment by apaszke** [comment]
As @alykhantejani noted this is not a bug.
