### ISSUE TITLE
Didn't find kernel to dispatch to for operator 'quantized::conv2d'

### ISSUE THREAD

**Issue by thiyagu145** [pytorch/pytorch#28483]
## 🐛 Bug

model(x) failing for models with layers QuantizedConv2d and QuantizedReLU 

## Error: 
```
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/quantized/modules/conv.py", line 133, in forward
    self.scale, self.zero_point)
RuntimeError: Didn't find kernel to dispatch to for operator 'quantized::conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch 
keys are: [QuantizedCPUTensorId] (lookup_ at /opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/ATen/core/dispatch/DispatchTable.h:249)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f7de64e8687 in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-pac
kages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x17a58a1 (0x7f7d96fe28a1 in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x3aa15e8 (0x7f7d992de5e8 in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x50061c (0x7f7de79b061c in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x4cdde4 (0x7f7de797dde4 in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x206506 (0x7f7de76b6506 in /home/thiyagu/miniconda3/envs/deeptagger/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```
## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 430.40
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.4.2
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl    conda-forge
[conda] libblas                   3.8.0                    10_mkl    conda-forge
[conda] libcblas                  3.8.0                    10_mkl    conda-forge
[conda] liblapack                 3.8.0                    10_mkl    conda-forge
[conda] liblapacke                3.8.0                    10_mkl    conda-forge
[conda] mkl                       2019.4                      243  
[conda] mkl_fft                   1.0.13           py37h516909a_1    conda-forge
[conda] mkl_random                1.0.4            py37hf2d7682_0    conda-forge
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] tensorflow-base           1.13.1          mkl_py37h7ce6ba3_0  
[conda] torchvision               0.4.1                py37_cu101    pytorch

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by jamesr66a** [comment]
Hi @thiyagu145, the error message you've encountered says that you're trying to run the quantized Conv2d operator, but you're passing in an unquantized tensor.

Please take a look for where we use `QuantStub` in the [tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#model-architecture) and [workflow documentation](https://pytorch.org/docs/stable/quantization.html#quantization-workflows). Once this is present and the values are passed through them, the issue should be solved

**Comment by raghavgurbaxani** [comment]
@thiyagu145  were you able to solve this issue ? I am stuck on the same problem

**Comment by raghavgurbaxani** [comment]
@jamesr66a 

I am trying static quantization of vgg_16_bn


import torch
from torchvision.models import vgg16_bn
model = vgg16_bn()
model.eval()
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save('vgg16_bn_float32.pt')
model.qconfig = torch.quantization.default_qconfig
torch.quantization.prepare(model, inplace=True)
quantized=torch.quantization.convert(model, inplace=True)
example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(quantized, example)
traced_script_module.save('vgg16_bn_qint8.pth')


but I get the same error, any tips ?

**Comment by z-a-f** [comment]
> but I get the same error, any tips ?

There are multiple issues with this code. The working version of the code is below

1. You need to disable the "inplace" flag in all the ReLU's. This is my bad, sent a PR to fix that: #28710 
2. Before `prepare` you must create a list of the modules you would like to fuse. Unfortunately, this is a manual process, and you have to tell the system which parts of your model are about to be fused. I provided a function to that, but it might not be usable for other models.
3. You have to quantize your tensors before pushing them into the quantized modules.
4. The tracing currently requires `check_trace=False` as stated by @jamesr66a #23986 

Your code will work if you do the following:

```python
import torch
from torchvision.models import vgg16_bn

def uninplace(model):
    """Sets all `inplace` values to False"""
    if hasattr(model, 'inplace'):
        model.inplace = False
    if not model.children():
        return
    for child in model.children():
        uninplace(child)

def prep_for_fusion(model, parent_name):
    """Fuses all conv+bn+relu, conv+bn, and conv+relu"""
    if not model.children():
        return []
    result = []
    candidate = []
    for name, child in model.named_children():
        new_name = parent_name + '.' + name
        if new_name[0] == '.':
            new_name = new_name[1:]
        if type(child) == torch.nn.Sequential:
            candidate = []
            result.extend(prep_for_fusion(child, new_name))
        else:
            if len(candidate) == 0 and type(child) == torch.nn.Conv2d:
                candidate = [new_name]
            elif len(candidate) == 1 and type(child) == torch.nn.ReLU:
                candidate.append(new_name)
                result.append(candidate)
                candidate = []
            elif len(candidate) == 1 and type(child) == torch.nn.BatchNorm2d:
                candidate.append(new_name)
            elif len(candidate) == 2:
                if type(child) == torch.nn.ReLU:
                    candidate.append(new_name)
                result.append(candidate)
                candidate = []
    return result

model = vgg16_bn()
model.eval()

example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save('vgg16_bn_float32.pt')

uninplace(model)  # This is a hack!
modules_to_fuse = prep_for_fusion(model, '')

model.qconfig = torch.quantization.default_qconfig
fused_model = torch.quantization.fuse_modules(model, modules_to_fuse)

torch.quantization.prepare(fused_model, inplace=True)
quantized = torch.quantization.convert(fused_model, inplace=False)

q_example = torch.quantize_per_tensor(example, scale=1e-3, zero_point=128,
                                      dtype=torch.quint8)


traced_script_module = torch.jit.trace(quantized, q_example, check_trace=False)
traced_script_module.save('vgg16_bn_qint8.pth')

```

**Comment by raghavgurbaxani** [comment]
@z-a-f  
Thank you so much for your feedback, the following works for VGG16, but doesn't work for other models such as resnet18, resnet 50,etc. 

I am particularly using this for a network that uses VGG as a base network

Could you provide a generic implementation for layer fusion part ? 

Thanks  a lot :)

**Comment by z-a-f** [comment]
> @z-a-f
> Thank you so much for your feedback, the following works for VGG16, but doesn't work for other models such as resnet18, resnet 50,etc.
> 
> I am particularly using this for a network that uses VGG as a base network
> 
> Could you provide a generic implementation for layer fusion part ?
> 
> Thanks a lot :)

Unfortunately, this is a manual process -- you need to tell the system which parts to fuse. You can traverse the model recursively, and create a list of "fusable" layers. You can take the code below as inspiration, but in the end of the day, it all depends on the model.

```python
COMPLEX_MODULES = (nn.Sequential,)  # Add any "recursable" modules in here

def prep_for_fusion(model, parent_name=''):
  """Fuses all conv+bn+relu, conv+bn, and conv+relu"""
  if not model.children():
    return []
  result = []
  candidate = []
  for name, child in model.named_children():
    new_name = parent_name + '.' + name
    if new_name[0] == '.':
      new_name = new_name[1:]
    if type(child) in COMPLEX_MODULES:
      candidate = []
      result.extend(prep_for_fusion(child, new_name))
    else:
      if type(child) not in (nn.Conv2d, nn.BatchNorm2d, nn.ReLU):
        # Not fusable layer found, check if candidate exists, and drop it
        if len(candidate) > 1:
          result.append(candidate)
        candidate = []
        continue
      if len(candidate) == 0 and type(child) == nn.Conv2d:
        # No candidates, so starting a new one
        candidate = [new_name]
      elif len(candidate) > 0 and type(child) == nn.ReLU:
        # There is a candidate, and we are done
        candidate.append(new_name)
        result.append(candidate)
        candidate = []
      elif len(candidate) > 0 and type(child) == nn.BatchNorm2d:
        # So far Conv + Bn found, waiting for ReLU?
        candidate.append(new_name)
  return result

modules_to_fuse = prep_for_fusion(model)
```

This is just a 5 minute draft (not tested). But I think if you put any composite modules in the `COMPLEX_MODULES` list, it might work. For example, if you are using ResNet from `torchvision` you might want to have the following in the list:

```python
COMPLEX_MODULES = (nn.Sequential, torchvision.models.resnet.BasicBlock, torchvision.models.resnet.Bottleneck)
```

Good luck!

**Comment by z-a-f** [comment]
Closing this issue, as the original question was answered --
