### ISSUE TITLE
TorchScript gives a confusing error message for a protobuf as module attribute

### ISSUE THREAD

**Issue by dreiss** [pytorch/pytorch#28491]
## 🐛 Bug

When using torch.jit.script with a module that has an attribute of type google.protobuf.pyext._message.RepeatedScalarContainer (where tuple or list is expected), it generates the error "module has no attribute '{attr_name}':", which is inaccurate.

## To Reproduce

https://nbviewer.jupyter.org/gist/dreiss/584fb8be601889d7d611c13b1e9bf96c

## Expected behavior

Error message should say that the attribute exists but is of an unrecognized type.

## Environment

Google Colab,
Collecting environment information...
PyTorch version: 1.3.0+cu100
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.3.0+cu100
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.4.1+cu100
[conda] Could not collect

cc @suo

**Comment by ailzhang** [comment]
Oh hmmm my guess is torch.jit.script didn't understand this type so it didn't copy it over. @driazati Do you know whether it's possible we give a better error message in this case?

**Comment by driazati** [comment]
This should be fixed on master 
```python
class X(object):
    pass

class Y(X):
    pass

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.y = Y()

    def forward(self):
        return self.y
```

outputs this (which could use some more detail but is accurate)

```
Module 'M' has no attribute 'y' (This attribute exists on the Python module, but we failed to convert Python type: 'Y' to a TorchScript type.):
```

**Comment by dreiss** [comment]
Awesome!
