### ISSUE TITLE
How does execute() in MKL-DNN call functions 'jit_*'

### ISSUE THREAD

**Issue by myuanqing** [pytorch/pytorch#28490]
## ❓ Questions and Help

I am tracing the calling process of torch.nn.Conv2d.
Here, I am into the file third_party/ideep/mkl-dnn/src/cpu/cpu_engine.cpp. 
![cpu_engine](https://user-images.githubusercontent.com/40328758/67356072-9de80a80-f58b-11e9-8967-9715fdfac630.png)
What confuses me is that what is the next step. It seems that convolution has something to do with jit_avx2, but I cannot figure out how.

cc @suo

**Comment by vpirogov** [comment]
Here's [relevant discussion](https://github.com/intel/mkl-dnn/issues/576) on DNNL Github.

**Comment by ailzhang** [comment]
This `jit_*` seems to be the MKLDNN functions so I agree that https://github.com/intel/mkl-dnn/issues/576 is a better place for discussion. 
I'm going to close this issue for now, but feel free to reopen if I'm wrong.
