### ISSUE TITLE
Libtorch calls CUDA and reports an error.

### ISSUE THREAD

**Issue by huang229** [pytorch/pytorch#28498]
The calling code is as follows:
#include <torch/script.h>
torch::randn({ 3, 4 }, torch::dtype(torch::kFloat32).device(torch::kCUDA, 1).requires_grad(true));
The code runs here and reports an error：
  Device exchangeDevice(Device d) const override {
    return impl_->exchangeDevice(d);
  }
c10::Error，In memory location 0X000000400433F670
How can I solve this problem?

**Comment by albanD** [comment]
Hi,

Please use the forum https://discuss.pytorch.org/ to ask for questions.

We keep github issues for known bugs or feature requests.
