### ISSUE TITLE
register_buffers with None does something strange

### ISSUE THREAD

**Issue by ddkang** [pytorch/pytorch#2851]
I may be misinterpreting the intended purpose of register_buffers, but either way I think the behavior is inconsistent here:
https://pastebin.com/GTa8AZEW
https://pastebin.com/mM7BVw22

In both cases, I register a buffer as `None`. In one case, I attempt to update it via direct assignment, and in another by __setattr__. In both cases, `b.indexes` prints `None` but  `b.__getattr__('indexes')` prints the correct tensor. In both cases `assert self.indexes == self.__getattr__('indexes')` fails.

**Comment by chenzhekl** [comment]
1. `__setattr__(self, attr)` is a convention method for the syntax `obj[attr]`. Unlike Javascript, `obj.a` and `obj[a]` are completely different. 
2. In Python, objects are passed by reference by default. Thus using `None` as buffer has no meaning.
3. [`register_buffer`](http://pytorch.org/docs/master/nn.html#torch.nn.Module.register_buffer) accepts a `Tensor` as the second argument.

**Comment by ddkang** [comment]
In that case I am extremely confused why `__setattr__` and `__getattr__` are implemented in PyTorch's module at all: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L283

**Comment by chenzhekl** [comment]
Just for convenience. See [discussion](
https://github.com/chainer/chainer/issues/1970) in Chainer for reference.
