### ISSUE TITLE
[quantization] Dispatch key error message is confusing to users

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#28518]
For example: https://github.com/pytorch/pytorch/issues/28483

User encounters the following inscrutable error message:

```
RuntimeError: Didn't find kernel to dispatch to for operator 'quantized::conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch 
keys are: [QuantizedCPUTensorId] (lookup_ at /opt/conda/conda-bld/pytorch_1570910687650/work/aten/src/ATen/core/dispatch/DispatchTable.h:249)
```

We should figure out a way to print a more friendly error message, such as:

```
Tried to run quantized::conv2d, but the input was not quantized! Please ensure you have QuantStub during model conversion, or you explicitly call  one of quantize_per_tensor, quantize_per_channel
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100

**Comment by z-a-f** [comment]
On it!

**Comment by z-a-f** [comment]
As per discussion with @smessmer the landed solution creates a dependency from dispatch onto quant and back. Instead of having a specialized message for the quantization, we need to have a more generic message.
