### ISSUE TITLE
Scripting module with type annotations and torch.jit.ignore fails

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#28537]
## 🐛 Bug

This bug was reported internally (https://fb.workplace.com/groups/329222650990087/permalink/513552499223767/).

Appears to be an issue with how we're scripting Modules with method and type annotations. 

@suo, @zdevito 

## To Reproduce

```python
import torch
from typing import Dict, Optional

class TMP(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,
                in_batch: Dict[str, Optional[torch.Tensor]]) -> torch.Tensor:
        self.dropout_modality(in_batch)
        return torch.tensor(1)

    @torch.jit.ignore
    def dropout_modality(self,
                         in_batch: Dict[str, Optional[torch.Tensor]]) -> Dict[str, Optional[torch.Tensor]]:
        return in_batch

tmp_script = torch.jit.script(TMP())
```
```
RuntimeError: 

(ClassType<TMP> self, Tensor 0, Dict(str, Tensor?) 1) -> (Dict(str, Tensor?) 0):
Expected a value of type 'Tensor' for argument '0' but instead found type 'Dict[str, Optional[Tensor]]'.
:
at jit.py:10:8
    def forward(self,
                in_batch: Dict[str, Optional[torch.Tensor]]) -> torch.Tensor:
        self.dropout_modality(in_batch)
        ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return torch.tensor(1)

```

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by driazati** [comment]
This seems to be an issue with the Python frontend type parser, using a comment-style mypy type works correctly:
```python
    @torch.jit.ignore
    def dropout_modality(self, in_batch):
        # type: (Dict[str, Optional[torch.Tensor]]) -> Dict[str, Optional[torch.Tensor]]
        return in_batch
```

**Comment by snie2012** [comment]
@driazati Thanks for the tip, but it still gives me the following error:

```
(ClassType<DeepSetFusion> self, Dict(str, Tensor?) 0) -> (Dict(str, Tensor?) 0):
Expected a value of type 'Dict[str, Optional[Tensor]]' for argument '0' but instead found type 'Dict[str, Tensor]'.
```

Any suggestions?

**Comment by snie2012** [comment]
@driazati Never mind, figured it out. It's in my user code.

**Comment by suo** [comment]
@driazati do we have any progress on root causing the issue with the py3-style parser?

**Comment by snie2012** [comment]
Any updates on this issue?

**Comment by driazati** [comment]
It's still open and wasn't a super high priority so the plan was to wait until we drop Python 2 support in January then fix our Python op usage (there are several other issues / ergonomic problems with how it's implemented now), but that could change. Are you still running into an issue that you can't work around?

**Comment by snie2012** [comment]
Hi @driazati, thanks for your reply. The workround worked for me. Just curious about the progress.

**Comment by eellison** [comment]
This was fixed by https://github.com/pytorch/pytorch/pull/29300
