### ISSUE TITLE
Conversion to .bfloat16() makes require_grad False

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#28548]
```
x = torch.randn(2,2, requires_grad=True)
x.requires_grad
```
True

```
y = x.half()
y.requires_grad
```
True

```
z = x.bfloat16()
z.requires_grad
```
False

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL @albanD @gqchen

**Comment by zhangguanheng66** [comment]
Mark as high priority because of the unexpected behavior of bfloat16()

**Comment by SsnL** [comment]
@t-vi Would https://github.com/pytorch/pytorch/pull/28279 happen to fix this too?

**Comment by t-vi** [comment]
Yes. Adam says I should add complex. Would doing so and adding a comment to is complex that it means cont be acceptable to you?

**Comment by SsnL** [comment]
@t-vi I don't really have a strong opinion. I am fine with both merging that PR as-is or update it to include complex. The ideal change IMO, which is beyond the scope of that PR, is to fix `isFloatingPoint` to include complex floating point types, and fix the call sites. But I don't think we need to worry about that for your PR.

**Comment by t-vi** [comment]
OK thanks. I'll push adding complex and a comment later today.

**Comment by gchanan** [comment]
I'd personally make two different PRs.  I'm not sure what exactly the right API to check is for the later and the bfloat16 fix is important enough in its own right.

**Comment by t-vi** [comment]
@gchanan: Yeah well, I'd certainly not complain if the PR was merged as is. It leaves complex alone and does bfloat16 right.

**Comment by izdeby** [comment]
Fixed via https://github.com/pytorch/pytorch/pull/28279
