### ISSUE TITLE
import torch failed.

### ISSUE THREAD

**Issue by tiankai** [pytorch/pytorch#28573]
### Below is my local progress.

C:\Users\t****k>pip3 install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch===1.3.0
  Downloading https://download.pytorch.org/whl/cu101/torch-1.3.0-cp36-cp36m-win_amd64.whl (550.0MB)
     |████████████████████████████████| 550.0MB 19kB/s
Collecting torchvision===0.4.1
  Downloading https://files.pythonhosted.org/packages/bb/30/6c586561c222b75c13af18beba34e1018150fff8e3cb179d91efe0d2017a/torchvision-0.4.1-cp36-cp36m-win_amd64.whl (964kB)
     |████████████████████████████████| 972kB 344kB/s
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/55/7a/f32b39164262765b069b0fe3ec5d4b47580c9c60f7bd3588b58ba8e93a4c/numpy-1.17.3-cp36-cp36m-win_amd64.whl (12.7MB)
     |████████████████████████████████| 12.7MB 469kB/s
Requirement already satisfied: six in c:\users\tiank\appdata\local\programs\python\python36\lib\site-packages (from torchvision===0.4.1) (1.12.0)
Collecting pillow>=4.1.1
  Downloading https://files.pythonhosted.org/packages/2c/ee/289ddb9884665aba9ad10d88c4edf867b87bcb93e3acbeeac41d30d87865/Pillow-6.2.1-cp36-cp36m-win_amd64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 1.1MB/s
Installing collected packages: numpy, torch, pillow, torchvision
Successfully installed numpy-1.17.3 pillow-6.2.1 torch-1.3.0 torchvision-0.4.1

### Then I type python command came into shell to test torch.  >>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tiank\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
### But I tried, import numpy, it worked.

**Comment by tiankai** [comment]
I'm so sorry for that the problem was caused by my mistake choose options when I try to install via a url proposed by official site docs.
I forgot my local machine has no graphic device on it. So I should select '**CUDA => None**'
### Now it worked!

**Comment by soufianemns** [comment]
@tiankai i have exact same error but ..when did you select CUDA=None ..during the installation or after..can you provide some details ..because i'm new at this!
