### ISSUE TITLE
caffe2-pytorch/caffe2/onnx/helper.h:13:9: error: ‘::ONNX_NAMESPACE’ has not been declared

### ISSUE THREAD

**Issue by rilesdg3** [pytorch/pytorch#28579]
I am using caffe2 version .8 c++ api and ONNX version 1.6 on Ubuntu 16 and I am trying to convert a .onnx model to caffe2

I have tried including all sorts of headers files from ONNX but that did not seem to work.
I changed ::ONNX_NAMESPACE:: to ::onnx_c2:: and that seemed to fix this issue but then it brought up another issue of incompatible ir.version

thank you

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by rilesdg3** [comment]
Does any one have any thoughts on this issue? 

thank you

**Comment by garymm** [comment]
Caffe2 is no longer being developed so this is unlikely to be fixed or get attention.
