### ISSUE TITLE
torch.mm seems to be broken. It doesn't enforce the dimensionality of out tensor

### ISSUE THREAD

**Issue by prasunanand** [pytorch/pytorch#28576]
## 🐛

`torch.mm` seems to be broken. It doesn't enforce the dimensionality of out tensor. Is it okay to allow resizing for out Tensors for Torch APIs ?

## To Reproduce

```
import torch
ta = torch.rand(2,2)
tb = torch.rand(2,2)
tc = torch.rand(3,1)
torch.mm(ta,tb,out=tc)
print(" tc =\n", tc)
​
import numpy as np
na = np.random.rand(2,2)
nb = np.random.rand(2,2)
nc = np.random.rand(3,1)
np.dot(na,nb, out=nc)
print(" nc =\n", nc)
```

### Output
```
 tc =
 tensor([[0.5370, 0.8979],
        [0.5145, 0.8827]])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-443ab3f3a3a4> in <module>
     10 nb = np.random.rand(2,2)
     11 nc = np.random.rand(3,1)
---> 12 np.dot(na,nb, out=nc)
     13 print(" nc =\n", nc)

<__array_function__ internals> in dot(*args, **kwargs)

ValueError: output array has wrong dimensions
```
## Additional context

https://github.com/pytorch/pytorch/issues/28347

cc: @rgommers 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by zhangguanheng66** [comment]
Mark as high priority. It's supposed to work.

**Comment by prasunanand** [comment]
I am working on a PR. Other APIs that allow resize as well should give a hard error on resize.

**Comment by gchanan** [comment]
I'd be careful here.  This is the behavior of the majority of torch functions, and there are proposal for better semantics, see e.g. https://github.com/pytorch/pytorch/issues/8989.

**Comment by gchanan** [comment]
So I don't think this specific issue is high priority.

And we'd need to get general agreement on the semantics before pursuing a fix.

**Comment by albanD** [comment]
The semantic of `out=` is definitely that it will resize if needed.
The point of this api is to be able to reuse existing Tensors as buffers to reduce memory usage if needed.

@gchanan might have more experience about the latest function, but **all** the ones coming from torch7 will resize the `out=` argument.

**Comment by rgommers** [comment]
This looks like a bug (at least for anyone used to NumPy semantics), but it is designed behavior and not specific to `mm`. So this bug report is probably not all that useful - how about closing this, closing gh-5272 as well, and updating gh-8989 with a complete description of the potential issues and use it as the one tracking issue for `out=` behavior?

**Comment by albanD** [comment]
Hi,

yes the other issues already discuss the limitations of the `out=` keyword.
Unfortunately anything beyond adding warnings in the dangerous cases would be breaking changes and can be tricky to roll out.
Feel free to post in these issues if you have ideas about how to improve the API while limiting breaking current code that uses it.
