### ISSUE TITLE
EXTENDING PYTORCH::Extending torch.autograd have something wrong with output dimension setting to 1

### ISSUE THREAD

**Issue by CodingMyLife** [pytorch/pytorch#28583]
## 📚 Documentation
[https://pytorch.org/docs/stable/notes/extending.html](url)
following this tutorial, when i change this code:
`from torch.autograd import gradcheck
input = (torch.randn(20,20,dtype=torch.double,requires_grad=True), torch.randn(30,20,dtype=torch.double,requires_grad=True))
test = gradcheck(linear, input, eps=1e-6, atol=1e-4)
print(test)`
to 
`from torch.autograd import gradcheck
input = (torch.randn(20,3,dtype=torch.double,requires_grad=True), torch.randn(1,3,dtype=torch.double,requires_grad=True),torch.randn(1,dtype=torch.double,requires_grad=True))
test = gradcheck(linear, input, eps=1e-6, atol=1e-4)
print(test)`
this means setting input dims 3, output dims 1, with bias. i get this runtime errrors:
`RuntimeError: Function LinearFunctionBackward returned an invalid gradient at index 2 - got [] but expected shape compatible with [1]`
i have no idea to fix this... thanks

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by CodingMyLife** [comment]
enviroment:: pytorch 1.2.x

**Comment by zhangguanheng66** [comment]
Have you tried with pytorch 1.3 and above?

**Comment by CodingMyLife** [comment]
@zhangguanheng66 thanks for your reply..there is nothing about the version..But at:
`class LinearFunction(torch.autograd.Function) ` 
at: `@backwards` function.
change        
`if bias is not None and ctx.needs_input_grad[2]:
            grad_bias = grad_output.sum(0).squeeze(0)` 
to
`if bias is not None and ctx.needs_input_grad[2]:
            grad_bias = grad_output.sum(0).unsqueeze(0)` 
or to 
`if bias is not None and ctx.needs_input_grad[2]:
            grad_bias = grad_output.t().mm(torch.ones(len(myinput),1))  # i think this is more sensible !`
it seems all work well...this really takes me much time.

**Comment by albanD** [comment]
Thanks for the report, I sent a PR to fix this.
This confusion has been introduced in 1.2 when 0-dim Tensors were introduced.
