### ISSUE TITLE
Cuda check

### ISSUE THREAD

**Issue by anandhperumal** [pytorch/pytorch#28600]
## To Reproduce

1. model.to(device) or nn.DataParallel(model) moves the model to the GPU but is there a way to check if the particular device is already in use by any other process. 
The actual problem is when some else is training something on the server I don't want my program to disturb their process and my program to fail so that I can allocate some other resource.

```

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux): Linux, Windows
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:10.1

**Comment by albanD** [comment]
Hi,

We use github issue for bug report only. Please use the forum https://discuss.pytorch.org/ to ask questions.
