### ISSUE TITLE
nn.AvgPoolxd raises error for too small input.

### ISSUE THREAD

**Issue by spott** [pytorch/pytorch#28625]
## 🐛 Bug

`nn.AvgPool1d` and `nn.AvgPool2d` (and presumably others) will raise an error when the input shape is less than the kernel size.  This is a change in behavior from version 1.1 where it would just act like the identity function.

## To Reproduce

```
import torch
import torch.nn as nn
x = torch.randn(1,2048,1)
avpool = nn.AvgPool1d(2)
y = avpool(x)
print(y.shape)
```

in v1.1: `torch.Size([1, 2048, 1])`
in v1.3: `RuntimeError: Given input size: (2048x1x1). Calculated output size: (2048x1x0). Output size is too small`

## Expected behavior

The result from 1.1.

**Comment by gchanan** [comment]
This is a bug fix, see: https://github.com/pytorch/pytorch/issues/26610
