### ISSUE TITLE
argmax for half datatype.

### ISSUE THREAD

**Issue by lcskrishna** [pytorch/pytorch#28623]
## 🐛 Bug

In pytorch version 1.2.0, argmax is supported for half datatype.
However, in the current version, it generates a runtime error that argmax_cuda is not supported for half.
## To Reproduce

Version : 1.2.0a0+eddebaf
```
>>> import torch
>>> torch.__version__
'1.2.0a0+eddebaf'
>>> a = torch.randn(1,1,2,2).cuda().half()
>>> print(a)
tensor([[[[ 2.3008,  0.9243],
          [-0.2551, -0.0803]]]], device='cuda:0', dtype=torch.float16)
>>> a.argmax()
tensor(0, device='cuda:0')

```
Where as with the current versions, 
```
>>> import torch
>>> torch.__version__
'1.4.0a0+bc69744'
>>> a = torch.randn(1,1,2,2).cuda().half()
>>> print(a)
tensor([[[[-1.3799,  0.4214],
          [ 0.5303,  0.2732]]]], device='cuda:0', dtype=torch.float16)
>>> a.argmax()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "argmax_cuda" not implemented for 'Half'

```
I have seen that there were some changes done in this PR #26181
So, is there a way to run argmax with fp16?

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by gchanan** [comment]
This bug was introduced in 1.3.

**Comment by gchanan** [comment]
I don't believe there is anyway to run argmax on half currently.  Your options are to run `max` and take the second return value or convert to-and-from `float`.

**Comment by PiotrDabrowskey** [comment]
I have exactly the same problem with pytorch 1.3.0.

**Comment by lcskrishna** [comment]
CC : @iotamudelta

**Comment by LLNLanLeN** [comment]
hi, I'm still seeing this issue, I'm wondering have this been resolved?

**Comment by soumith** [comment]
has been resolved on master, so you'll have to install a preview / nightly build for it.

**Comment by LLNLanLeN** [comment]
@soumith Thank you for response, I just want to ask few question about nightly build as I'm still very new to using anaconda and many times before when I install the nightly build using conda on the following link:

https://anaconda.org/pytorch/pytorch-nightly

I would overwritten my current pytorch version. I'm wondering what is the best way to install nightly build and if you can point me to a thread that have a discussion about this, that'd be helpful. Thank you for much

**Comment by soumith** [comment]
look at pytorch.org and in the commands table, use the "Preview" button.

**Comment by LLNLanLeN** [comment]
@soumith awesome, thank you.

**Comment by pmeier** [comment]
Just encountered this on a fresh install from source

```python
import torch

print(torch.__version__)
torch.max(torch.tensor(1.0, dtype=torch.half))
```

```
1.6.0a0+3d199aa
RuntimeError: "max_all" not implemented for 'Half'
```

Shall I open a new issue?

**Comment by ezyang** [comment]
Yes, please do.
