### ISSUE TITLE
Set CUDA device is expensive operation

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#28639]
## 🐛 Bug

Calling cudart::cudaApiSetDevice appears to be a very expensive operation. However, as my system has only a single GPU, it is unnecessary to call it at all.

Tested on Windows.

![image](https://user-images.githubusercontent.com/61218/67546817-99188780-f740-11e9-9566-792c5eab40e4.png)

## To Reproduce

1. Run models with benchmarking turned on
2. Profile the application

## Expected behavior

Set device should not even be called on a single GPU device because device 0 will always be used anyway.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux): Windows x64 MSVC 2019
 - How you installed PyTorch (`conda`, `pip`, source): prebuilt off website
 - Build command you used (if compiling from source): N/A
 - Python version: N/A
 - CUDA/cuDNN version: 10.1/7.6
 - GPU models and configuration: GTX 2060
 - Any other relevant information:

cc @VitalyFedyunin @ngimel @mruberry

**Comment by gchanan** [comment]
This has always been shown to be a profiling artifact, see e.g. https://github.com/pytorch/pytorch/issues/18048.

What I think we'd need to see is actual, runnable benchmarking that demonstrates it's a real issue (you can see how to make the calls no-ops in the linked issues).

**Comment by xsacha** [comment]
Thanks
