### ISSUE TITLE
compiling from source error on rhel 7.2

### ISSUE THREAD

**Issue by VitaMusic** [pytorch/pytorch#28645]
## 🐛 Bug

error during compilation from source, see stdout/stderr in attachment for details

File "/opt/anaconda3/envs/pytorch/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)

[pytorch_install_stdout.txt](https://github.com/pytorch/pytorch/files/3771015/pytorch_install_stdout.txt)
[pytorch_install_stderr.txt](https://github.com/pytorch/pytorch/files/3771016/pytorch_install_stderr.txt)

### dependencies (install as root)
conda create --name pytorch
conda activate pytorch
conda install -c intel python=3.6.9 # choosing -c intel or standard does not influence the error
conda install -c intel numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing
#conda install -c pytorch magma-cuda101 # for cuda 10.1 version not used as CUDA 10.1 sdk already installed (presence or absence do not influence the current error in any case)
conda deactivate

### config source (as user)
conda activate pytorch
cd install
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install

## Expected behavior

success compilation of pytorch

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.2 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 418.87.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] mkl                       2019.5                intel_281    intel
[conda] mkl-include               2019.5                intel_281    intel
[conda] mkl-service               2.3.0                    py36_0    intel
[conda] mkl_fft                   1.0.14           py36ha68da19_1    intel
[conda] mkl_random                1.0.4            py36ha68da19_2    intel

## Additional context

it is possible to switch between CUDA toolkit versions 10.0 vs 10.1 , but it does not influence the error

**Comment by Marco-MP** [comment]
Hi,
in pytorch_install_stdout.txt Line 1135:

>  #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."

Did you try a newer GCC Version already?

**Comment by VitaMusic** [comment]
non thank you for point it out. I did not see this message
is it possible to use intel c++ instead of gcc ?
if yes how to configure the compilation with intel ?

> in pytorch_install_stdout.txt Line 1135:
>
> #error "You're trying to build PyTorch with a too old version of GCC. We
> need GCC 5 or later."
>
> Did you try a newer GCC Version already?
>

**Comment by gchanan** [comment]
Closing because this isn't supported and the error message is clear.

For questions, you can use the forums: https://discuss.pytorch.org/.
