### ISSUE TITLE
error with detect_anomaly and SparseTensor

### ISSUE THREAD

**Issue by serhii-havrylov** [pytorch/pytorch#28649]
When using the code snippet bellow, I get this error: `RuntimeError: No function is registered for schema aten::ne(Tensor self, Tensor other) -> Tensor on backend SparseCUDA`

```python
import torch
from torch import autograd


with autograd.detect_anomaly():
    idxs = torch.tensor([[0, 2, 3], [1, 1, 2], [2, 1, 4], [3, 5, 1]], device=0)
    values = torch.tensor([1.0, 2.0, 3.0, 4.0], device=0, requires_grad=True)

    sparse_tensor = torch.sparse_coo_tensor(indices=idxs.t(), values=values, size=(4, 6, 5))
    dense_tensor = torch.sparse.sum(sparse_tensor, dim=2).to_dense()

    dense_tensor.sum().backward()
```

PyTorch version is 1.2.0

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL @albanD @gqchen

**Comment by gchanan** [comment]
I was able to reproduce this on 1.3 and can verify that it is a result of `detect_anomaly`.

The error message indicates that it's because `ne` isn't implemented for sparse tensors -- we probably just need to make the anomaly detector smarter to just check the values or something in this case.

**Comment by albanD** [comment]
Does that just boils down to implementing `.ne` for sparse Tensors?

**Comment by gchanan** [comment]
That would be one way to solve, but I'm not sure we need it?  Is detect_anomaly just checking if there are any NaNs/infs?  Where you could just look at the values.

**Comment by albanD** [comment]
It is only looking for `NaNs`.
Indeed, checking the Tensor of values will work for sparse Tensors.

**Comment by SsnL** [comment]
@albanD I haven't read the anomaly detection code, but both `isnan` and `any` should be trivial to implement for sparse tensors.

**Comment by albanD** [comment]
`isnan()` did not exist back when anomaly mode was added. But yes adding `isnan` and `any` is better than `ne` and `any`.
