### ISSUE TITLE
GPU Memory Leak when using lambdas in nn.Modules

### ISSUE THREAD

**Issue by Tieftaucher** [pytorch/pytorch#28647]
## 🐛 Bug

First of all thank you for this awesome library. I found one issue, you are maybe interested in:

When using a lambda, that references to the object itself in the constructor of a class, the object will not be deleted from GPU Memory (ever).

When having something like that:
```class NetWithLambda(nn.Module):
    def __init__(self):
        super(VanillaVariationalAutoencoderArchitecture, self).__init__():
        .....
        self.wired = ["nice object", "totally nice object"]

        self.someLambda = lambda x: ( self.wired )    
```
and you put it on the GPU via
`net = net.cuda()`
and then recreate the net and send it to cuda again, the GPU Memory usages will be higher every time. Even when you delete the object with del and empty the cache, it will still be there. 

## To Reproduce

Minimal Example:
```
import torch.nn as nn
import torch

class SomeNet(nn.Module):

    def __init__(self):
        super(SomeNet, self).__init__()

        #generates some memory usage (to see the problem):
        self.memoryUser = nn.Sequential(
            nn.Linear(10000, 256),
            nn.Linear(256, 200)
        )
        self.compare = ["nice object", "totally nice object"]
        self.wired = ["nice object", "totally nice object"]

        self.someLambda = lambda x: ( self.wired )

    def forward(self, x):
        return x
```
This has the behaviour:
```
>>> a = SomeNet()  #no python process in GPU
>>> import sys
>>> sys.getrefcount(a) #This shows 3 because the lambda context contains one reference to the object
3 
>>> sys.getrefcount(a.wired)
2
>>> sys.getrefcount(a.compare)
2
>>> a = a.cuda() #after this GPU Memory usage of python is 570 MiB
>>> sys.getrefcount(a)
3
>>> sys.getrefcount(a.wired)
2
>>> a = SomeNet()
>>> a = a.cuda() #after this GPU Memory usage of python is 610 MiB
>>> sys.getrefcount(a.wired)
2
>>> torch.cuda.empty_cache() #after this GPU Memory usage of python is still 610 MiB
>>> del a
>>> torch.cuda.empty_cache() #after this GPU Memory usage of python is still 610 MiB
```
also:
```
print('reference there?')
torch.cuda.empty_cache()
for obj in gc.get_objects():
    if isinstance(obj, SomeNet):
        print('yes!')
```
will show you that there is still a reference to the object.

When you make the same experience with the following class:
```
import torch.nn as nn
import torch

class SomeNet(nn.Module):

    def __init__(self):
        super(SomeNet, self).__init__()

        #generates some memory usage (to see the problem):
        self.memoryUser = nn.Sequential(
            nn.Linear(10000, 256),
            nn.Linear(256, 200)
        )
        self.compare = ["nice object", "totally nice object"]
        self.wired = ["nice object", "totally nice object"]

    def noLambda(self, x):
        return self.wired

    def forward(self, x):
        return x
```
Everything will work as expected.

I think this is a bug in pytorch, not in the python gc, because:
When you generate the two objects without super nn.Modules and without using cuda, then you can delete both of them without having references left.

## Expected behavior

Even as it is maybe not the best style, to return class attributes in lambdas, it should not result in a memory leak.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 980 Ti
Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

**Comment by albanD** [comment]
Hi,

Thanks for posting.
I changed a bit your code snippet to show the problem:
```python
import torch
import torch.nn as nn
import sys
import gc

ref_counter = "Some weird string"
base_rc = sys.getrefcount(ref_counter)
def print_rc():
    print(sys.getrefcount(ref_counter)-base_rc)

class SomeNet(nn.Module):

    def __init__(self, smth=None):
        super(SomeNet, self).__init__()
        self.smth = smth
        #generates some memory usage (to see the problem):
        self.memoryUser = nn.Sequential(
            nn.Linear(10000, 256),
            nn.Linear(256, 200)
        )
        self.compare = ["nice object", "totally nice object"]
        self.wired = ["nice object", "totally nice object"]

        self.someLambda = lambda x: ( self.wired )

    def forward(self, x):
        return x

print("Our refcounter to track when our module dies")
print_rc()
o = SomeNet(ref_counter)
print("Our module owns one ref")
print_rc()
del o
print("It did not go away after del?")
print_rc()
gc.collect()
print("What if we run the gc to collect ref cycles?")
print_rc()
print("Victory !")
```

Few things:
- You create a ref cycle so you need to wait for python gc to run (which happens very rarely unless there is memory pressure)
- The cuda memory is cached, so it is expected not to be freed when the object is deleted. You can use `torch.cuda.empty_cache()` to force release this memory but in any actual scenario, I would advise against as it may slow down your program.
- When checking ref counts, I usually avoid the repl as it has a tendency to hang to the last results, last printed objects or last error sometimes and that can make refcounts weird.

Feel free to open this issue again if I missed something and there is a problem !

**Comment by Tieftaucher** [comment]
Thank you for the fast reply and for the hints. 
You are right, when using gc.collect() and empty_cache the gpu memory is freed. So, I guess there is no bug.
