### ISSUE TITLE
DataParallel doesn't replicate module's member variables

### ISSUE THREAD

**Issue by blackyang** [pytorch/pytorch#2864]
It seems that DataParallel doesn't replicate a module's member variables, is this intended?

See the following code for an example. We'll see different outputs depending on ``data_parallel``.
```
import torch
import torch.nn as nn
from torch.autograd import Variable

class Simple(nn.Module):
    '''A simple example'''

    def __init__(self):
        super(Simple, self).__init__()
        self.counter = 0

    def forward(self, x):
        print(self.counter)
        self.counter += 1
        print(self.counter)
        return x

if __name__ == '__main__':
    x = Variable(torch.randn(10, 10))
    net = Simple()
    data_parallel = False  # True
    if data_parallel:
        net = torch.nn.DataParallel(net)
    net = net.cuda()
    for i in range(10):
        print('iteration: {}'.format(i))
        y = net(x)
```

**Comment by weigq** [comment]
can not get what you mean

**Comment by blackyang** [comment]
@weigq please run the code provided and see the different results when setting ``data_parallel`` to True or False

**Comment by SsnL** [comment]
You can register `counter` as a buffer. Then PyTorch can take care of it.

`self.register_buffer('counter', torch.zeros(1))`

**Comment by blackyang** [comment]
@SsnL thanks, that's what I need!
