### ISSUE TITLE
Python crashes after repeatedly calling `refine_names` to get named tensors

### ISSUE THREAD

**Issue by j-luo93** [pytorch/pytorch#28646]
## 🐛 Bug

Python crashes after repeatedly calling `refine_names` to get named tensors. 

## To Reproduce

Python will crash with
```
import torch
while True:
    x = torch.randn(10)
    x = x.refine_names('batch')
```
If `x` is only created once, then it runs fine:
```
import torch
x = torch.randn(10)
while True:
    x = x.refine_names('batch')
```
However, removing rebinding `x` triggers the crashes again:
```
import torch
x = torch.randn(10)
while True:
    x.refine_names('batch')
```
Also, the issue seems to be related to `refine_names` only, since declaring names in `torch.randn` works fine:
```
import torch
while True:
    x = torch.randn(10, names=['batch'])
```

## Expected behavior
Should not crash.

## Environment

 - PyTorch Version (e.g., 1.3):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.3
 - CUDA/cuDNN version: both cpu and cuda-10.0 versions are tested
 - GPU models and configuration: 
 - Any other relevant information:

## Additional context
I encountered this issue when I was extensively using named tensors. After a lot of digging, I think it might be related to this Python issue [link](https://bugs.python.org/issue36880). If you check the refcount for `None`, it will decrease every time `refine_names` is called for a new tensor until Python crashes.

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by gchanan** [comment]
This looks serious, we should fix it.

**Comment by zou3519** [comment]
I can reproduce this on master. I will look into this.

**Comment by zou3519** [comment]
I think the bug is that we're not incrementing Py_None when returning it as a part of `tensor.names`. See https://stackoverflow.com/questions/15287590/why-should-py-increfpy-none-be-required-before-returning-py-none-in-c for details.

I'll attempt to submit a bugfix soon. Thank you for the detailed report, @j-luo93

**Comment by j-luo93** [comment]
Thanks for the quick response! Is there any workaround that I can use right now?

**Comment by j-luo93** [comment]
nvm, I just manually increase refcount for None after each refine_names call, based on this https://stackoverflow.com/questions/17732816/is-there-any-way-to-manually-decrease-the-reference-count-of-an-object-in-python.
