### ISSUE TITLE
Error Exporting Quantized model to ONNX

### ISSUE THREAD

**Issue by hossein1387** [pytorch/pytorch#28705]
## 🐛 Bug

I am using Pytorch 1.3 with quantization feature. 
After the model is quantized, you can no longer export it to ONNX. I used the exact same code provided in Quantization tutorial to quantize Mobilenet2 model but failed to export the quantized model to onnx.
## To Reproduce

1. Follow instruction from step1-3 Quantization tutorial: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html
2. Finish step 3 and do quantization part (first part) of step 4. 
3. Use torch.onnx.export to export model to onnx.

```

  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'quantize_per_tensor'
File "/export/tmp/hemmat/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
```

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 3.13.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 396.37
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.14.5
[pip] torch==0.4.0
[pip] torchvision==0.2.1
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] medicaltorch              0.2                      pypi_0    pypi
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by z-a-f** [comment]
We currently don't support ONNX for the quantized kernels.

**Comment by zealerww** [comment]
Any plan to support that?

**Comment by zif520** [comment]
Any plan to support that?

**Comment by ggeor84** [comment]
Also waiting for this

**Comment by ggeor84** [comment]
any news on this?

**Comment by addisonklinke** [comment]
Same here. Quantizing a PyTorch model is not much use to me if I cannot export to ONNX for production use (with ONNX Runtime)
