### ISSUE TITLE
torch.max has extra dimensions on a slice with size 1

### ISSUE THREAD

**Issue by lopuhin** [pytorch/pytorch#2870]
```
>>> x = torch.zeros((32, 10, 10))
>>> y = x[:, 2:4, 3:5]
>>> torch.max(y, dim=1, keepdim=False)[0].size()
torch.Size([32, 2])   # correct
>>> y = x[:, 2:3, 3:4]
>>> torch.max(y, dim=1, keepdim=False)[0].size()
torch.Size([32, 1, 1])  # wrong
```
The size reported at the end should be ``(32, 1)``, but is ``(32, 1, 1)``. Using ``torch==0.2.0.post3`` both on CPU and GPU.

**Comment by gchanan** [comment]
should be fixed by this: https://github.com/pytorch/pytorch/pull/2318

**Comment by lopuhin** [comment]
Thanks @gchanan , will re-open if I find any issues with this in master!
