### ISSUE TITLE
[type promotion] torch.exp does not work on integral types

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#28703]
`torch.exp(torch.tensor(3))` - RuntimeError: exp_vml_cpu not implemented for 'Long'

I guess other real-input scalar functions like sin, cos etc also don't work for Long types, but could work  by using a default float type

(follow up on https://github.com/pytorch/pytorch/issues/14190#issuecomment-546473334 @gchanan  )

**Comment by zhangguanheng66** [comment]
@nairbv

**Comment by nairbv** [comment]
This might need some discussion, it's possible we won't want to support this case.

Typically for unary ops, the dtype of the input tensor is the same as the dtype of the output tensor. E.g. in `result=torch.exp(input)`, `input.dtype==result.dtype`. We wouldn't want to preserve that if we support `torch.exp(long_tensor)`.

To support this kind of input conversion, we'd need to decide on a mapping like maybe short->half, int->float, long->double.

Int to float can lose precision, and unsigned types could lose more. It could then be confusing to call `torch.exp(short_tensor)` and get an error saying something like "exp not implemented for half on cpu."

@gchanan any thoughts?

**Comment by gchanan** [comment]
I think we definitely want to support this.  NumPy already has this, although I'm not sure precisely what algorithm they use for determining the output dtype.

**Comment by nairbv** [comment]
I haven't found docs for it yet, but empirically this is the np behavior:
```
>>> np.exp(np.ones(5, dtype=np.int8)).dtype
dtype('float16')
>>> np.exp(np.ones(5, dtype=np.int16)).dtype
dtype('float32')
>>> np.exp(np.ones(5, dtype=np.int32)).dtype
dtype('float64')
>>> np.exp(np.ones(5, dtype=np.int64)).dtype
dtype('float64')
>>> np.exp(np.ones(5, dtype=np.bool)).dtype
dtype('float16')
```

**Comment by mruberry** [comment]
This is subsumed by https://github.com/pytorch/pytorch/issues/36571.
