### ISSUE TITLE
Improve error message in nn.MultiheadAttention

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#28719]
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py#L688 says
`assert self.head_dim * num_heads == self.embed_dim, "embed_dim must be divisible by num_heads"`. Given that MultiheadAttention is used within TransformerEncoderLayer, this error message does not say much, since it was not the user who directly passed in these bad values. It would be better if it used sth like `f"embed_dim={embed_dim} must be divisible by num_heads={num_heads}"`

**Comment by zhangguanheng66** [comment]
For `TransformerEncoderLayer`, yes but not necessary. A lot of people apply `nn.MultiheadAttention` and pass the values above directly.

**Comment by vadimkantorov** [comment]
Many error messages do print out the offending values (e.g. when shapes are compared etc), I think it only helps the user.

**Comment by vadimkantorov** [comment]
Fix incoming in https://github.com/pytorch/pytorch/pull/34711
