### ISSUE TITLE
Enhance autograd profiler to support detailed profiling of RPC, RRef and distributed autograd

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#28734]
## Motivation

In a distributed system is very useful to have detailed profiling information across multiple different layers of the system to easily determine which components might be taking up most of the CPU time. We should enhance the autograd profiler to provide a detailed view into RPC calls, RRef calls and various operations that distributed autograd/optimizer execute under the hood.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
This work has been landed and is now a stable feature a part of PyTorch 1.8, so closing this out.
