### ISSUE TITLE
GELU should work with fp16

### ISSUE THREAD

**Issue by calclavia** [pytorch/pytorch#28738]
## 🚀 Feature

When using `nn.Transformer` with FP16, this error will occur when using GPU:
RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'

## Motivation

GELU FP16 support will speed up training.

## Alternatives

Temporarily use RELU activation, which makes it harder to replicate models such as BERT.

**Comment by zhangguanheng66** [comment]
@BIT-silence

**Comment by BIT-silence** [comment]
https://github.com/pytorch/pytorch/pull/28944 should fix that and also add torch.nn.GELU as the module version.

**Comment by jinfagang** [comment]
Still got on pytorch1.11:

```
torch/nn/functional.py", line 1666, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: "GeluKernelImpl" not implemented for 'Half'

```
