### ISSUE TITLE
[JIT] `iterator expression` is expected to accept `Tensor`

### ISSUE THREAD

**Issue by standbyme** [pytorch/pytorch#28739]
- PyTorch 1.3.0
- Python 3.6.9
- CUDA 10.1

```python
import torch


@torch.jit.script
def foo(input: torch.Tensor):
    return [m for m in input]


if __name__ == '__main__':
    print(foo(torch.ones(2, 3)))
```
Now, this code will output
```
iterator expression is expected to be a list, iterable, or range, found value of type 'Tensor'
```
However, this feature is useful for the framework lacks the function which is able to do the follow work:

Convert
```
Tensor([
    [1, 2, 3]
    [4, 5, 6]
])
```
To
```
[
    Tensor([1, 2, 3])
    Tensor([4, 5, 6])
]
```

Thanks!

cc @suo

**Comment by suo** [comment]
Thanks for the report. @eellison is this fixed in the nightly? I think you had a PR for this right?

**Comment by eellison** [comment]
I have a PR for this but it's not landed yet. This is a dup of https://github.com/pytorch/pytorch/issues/27255, closing.

**Comment by standbyme** [comment]
Thanks~
