### ISSUE TITLE
Fails on FreeBSD: ImportError: /usr/local/lib/libtorch.so: Undefined symbol "cpuinfo_isa"

### ISSUE THREAD

**Issue by yurivict** [pytorch/pytorch#28749]
```
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import torch 
  File "/usr/local/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /usr/local/lib/libtorch.so: Undefined symbol "cpuinfo_isa"
```

FreeBSD 12.
Got this in an attempt to create a FreeBSD port. The port builds and installs, but fails with this error.

https://people.freebsd.org/~yuri/py-pytorch.shar

**Comment by yurivict** [comment]
I solved this by replacing AMD64 -> amd64 in one cmake file.

**Comment by myfreeweb** [comment]
cpuinfo's CMakeFile also now requires adding `FreeBSD` to `ELSEIF(NOT CMAKE_SYSTEM_NAME MATCHES "^(Windows|CYGWIN|MSYS|Darwin|Linux|Android)$")`, otherwise `SET(CPUINFO_SUPPORTED_PLATFORM FALSE)` and the x86 file won't be compiled in
