### ISSUE TITLE
RTX 2080Ti on pytorch

### ISSUE THREAD

**Issue by Limingxing00** [pytorch/pytorch#28752]
# device
RTX 2080Ti  
pytorch 0.4.1_cuda9.2_cudnn7.1.4

# question
RTX 2080Ti  cannot run with pytorch 0.4.1_cuda9.2_cudnn7.1.4? I find I can run my device on cuda10, but now I want to reproduce the work of others which is cuda9.2.  
I don't know how to solve this contradiction now, please help me, thank you.

**Comment by SsnL** [comment]
CUDA 9 does not support RTX cards so there is nothing we can do.
