### ISSUE TITLE
expected a Variable argument, but got tuple

### ISSUE THREAD

**Issue by micklexqg** [pytorch/pytorch#2876]
I  am fine-tuning inception v3, but get error: 
expected a Variable argument, but got tuple.
my code is based on imagnet/main.py .
I only changed the output number for now:
model = models.inception_v3(pretrained=True)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 200)  
but there are no any errors when finetune resnet34(or resnet18) with the same code.
so, how to finetune inception v3?

**Comment by soumith** [comment]
use https://discuss.pytorch.org for questions. your issue is definitely a user-error and not a pytorch bug. thank you.
