### ISSUE TITLE
How to use torch.quantization.get_observer_dict(mod, target_dict, prefix='')

### ISSUE THREAD

**Issue by vippeterhou** [pytorch/pytorch#28776]
## ❓ How to use torch.quantization.get_observer_dict(mod, target_dict, prefix='') to get the observer dict

Can you provide an example for this usage? Thanks a lot!

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
