### ISSUE TITLE
[feature request] Whether or not any planning to support mips64 arch environments

### ISSUE THREAD

**Issue by uddmorningsun** [pytorch/pytorch#28775]
## 🚀 Feature
pytorch can be compiled in `mips64` arch successfully, and then utilize related API to develop :+1: 

## Motivation
I'm working on compiling pytorch in mips64 arch, but it doesn't work

```
(pytorch-venv) [root@lx-app-1 build]# git branch
* v1.3.0

(pytorch-venv) [root@lx-app-1 build]# cmake -DUSE_DISTRIBUTED=OFF -DBLAS=ATLAS -DAtlas_BLAS_LIBRARY=/usr/lib64/atlas/ -DAtlas_CBLAS_INCLUDE_DIR=/usr/include/atlas-mips64el-base/ -DAtlas_CBLAS_LIBRARY=/usr/lib64/atlas/USE_MPI=OFF -DUSE_FBGEMM=OFF -DCMAKE_SYSTEM_PROCESSOR=mips64  -DUSE_PYTORCH_QNNPACK=OFF -DBUILD_TEST=ON -DUSE_NNPACK=OFF -DUSE_QNNPACK=OFF -DUSE_NUMA=OFF  -DBUILD_CAFFE2_MOBILE=OFF  -DBUILD_BINARY=ON -DUSE_OPENCV=ON -DUSE_CUDA=OFF -DCMAKE_BUILD_TYPE=Release ..
(pytorch-venv) [root@lx-app-1 build]# make -j $(nproc)
... ...
CMake Warning at third_party/cpuinfo/CMakeLists.txt:71 (MESSAGE):
  Target processor architecture "mips64" is not supported in cpuinfo.
  cpuinfo will compile, but cpuinfo_initialize() will always fail.
... ...

... ...
[  6%] Generating contrib/playground/resnetdemo/override_no_test_model_no_checkpoint.py
[  6%] Building C object sleef/src/libm/CMakeFiles/sleefpurecfma_scalar.dir/sleefsimdsp.c.o
[  6%] Building C object sleef/src/libm/CMakeFiles/sleefdetpurec_scalar.dir/sleefsimddp.c.o
[  6%] Building C object sleef/src/libm/CMakeFiles/sleefpurec_scalar.dir/sleefsimdsp.c.o
[  6%] Building C object sleef/src/libm/CMakeFiles/sleefdetpurecfma_scalar.dir/sleefsimdsp.c.o
[  6%] Built target c10
[  6%] Building C object sleef/src/libm/CMakeFiles/sleefdetpurecfma_scalar.dir/sleefsimddp.c.o
[  6%] Generating contrib/playground/resnetdemo/rendezvous_filestore.py
In file included from /home/yancy/pytorch/third_party/sleef/src/libm/sleefsimdsp.c:187:0:
/home/yancy/pytorch/third_party/sleef/src/arch/helperpurec_scalar.h:56:2: error: #error FP_FAST_FMA or FP_FAST_FMAF not defined
 #error FP_FAST_FMA or FP_FAST_FMAF not defined
... ...
```
I have tried add `-I /home/yancy/pytorch/third_party/sleef/src/arch/` in `build/CMakeCache.txt` and `make rebuild_cache`, same error happened.

## Pitch
pytorch can be compiled in `mips64` arch

## Alternatives
1) When I see warning info in `cmake ...` for `third_party/cpuinfo`, I plan to fake match rule in `third_party/cpuinfo/CMakeLists.txt`, for example:
```
... ...
-ELSEIF(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|AMD64|x86(_64)?|armv[5-8].*|aarch64)$")
+ELSEIF(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|AMD64|x86(_64)?|armv[5-8].*|aarch64|mips64|mips64el)$")
... ...
```
The ultimate result will also failed since `cpuinfo` . So, whether or not `cpuinfo` support `mips64` arch, too? Thanks!

**Comment by uddmorningsun** [comment]
After investigating and learning, I add MIPS arch define in `aten/src/TH/vector/simd.h`, `third_party/sleef/src/arch/helperpurec_scalar.h` with `debian:stretch` docker image. Finally, it does work!
```
root@mips64:~/pytorch# ls -lh dist/torch-1.4.0a0+f067088-cp37-cp37m-linux_mips64.whl 
-rw-r--r-- 1 root root 25M Mar  8 05:35 dist/torch-1.4.0a0+f067088-cp37-cp37m-linux_mips64.whl

root@mips64:/# python -c "from distutils.util import get_platform; import torch; print('pytorch is ok in {}'.format(get_platform()))"
pytorch is ok in linux-mips64

>>> import torch
>>> x = torch.empty(5, 3)
>>> print(x)
Error in cpuinfo: processor architecture is not supported in cpuinfo
tensor([[-1.1392e+28,  3.5733e-43, -1.1392e+28],
        [ 3.5733e-43, -6.6617e+27,  3.5733e-43],
        [-6.6571e+27,  3.5733e-43, -6.6598e+27],
        [ 3.5733e-43, -6.6571e+27,  3.5733e-43],
        [-6.6598e+27,  3.5733e-43, -6.6572e+27]])
```

Since machine resources isn't enough, so only `pytest test_autograd.py`, test display is ok:https://user-images.githubusercontent.com/19144683/76158082-df4d1100-614c-11ea-9394-d9e02c9b4089.png

Following https://github.com/pytorch/builder/blob/master/check_binary.sh:
```
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
# expected result, not support MKL
>>> torch.backends.mkl.is_available()
False

root@mips64:/tmp/venv# install_root="/tmp/venv/lib/python3.7/site-packages/torch"
root@mips64:/tmp/venv# g++ example-app.cpp -I$install_root/include -I$install_root/include/torch/csrc/api/include -L$install_root/lib -ltorch -std=gnu++14 -o example-app -lc10 -Wl,--no-as-needed -Wl,-R$install_root/lib 
root@mips64:/tmp/venv# ./example-app 
Warning: Simple test passed! (main at example-app.cpp:4)
```

@zhangguanheng66 I don't know about pytorch realization process, related smock testing passed. About above error, any impact on usage later? Thanks!

**Comment by uddmorningsun** [comment]
I will close because of no any response, and see: https://github.com/uddmorningsun/mips-applications-in-python/tree/master/pytorch

**Comment by nmanhong** [comment]
@uddmorningsun
你编译成功了？

**Comment by uddmorningsun** [comment]
@nmanhong 
是的，二进制 wheel 包见 https://github.com/uddmorningsun/mips-applications-in-python/releases  细节信息参考 README.md 和 相应的 CHANGELOG.md

Yes, binary wheel packages see https://github.com/uddmorningsun/mips-applications-in-python/releases Details refer to README.md or CHANGELOG.md

**Comment by kroryan** [comment]
> @nmanhong 是的，二进制 wheel 包见 https://github.com/uddmorningsun/mips-applications-in-python/releases 细节信息参考 README.md 和 相应的 CHANGELOG.md
> 
> Yes, binary wheel packages see https://github.com/uddmorningsun/mips-applications-in-python/releases Details refer to README.md or CHANGELOG.md

hello, how can i install it to be able to install torch? thanks for it
