### ISSUE TITLE
andoroid  quantization  model (mobilenetv2) first forward  very slow?  but second forward  faster why how to fix it

### ISSUE THREAD

**Issue by hexiangquan** [pytorch/pytorch#28778]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
This is possibly due to two reasons: 
1. Spending time in re-quantization of bias based on the input scale. 
2. Converting weights from int8 to uint8. 
On mobile, we use QNNPACK which currently expects bias to be quantized and only supports uint8 weights. Relevant code is here - https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv.cpp#L349

We recommend running some warmup runs to avoid this slowdown. Is that possible in your use case?

**Comment by hexiangquan** [comment]
we cannot use  warmup . is that possiable to save uint8 weigths.when first infer?

**Comment by soumith** [comment]
I'm closing this because it's a question and has to be pointed to https:/discuss.pytorch.org
But because the discussion has started, feel free to continue the discussion.

**Comment by supriyar** [comment]
This should be called only once - during the first call to `forward`. Is that what you mean by first infer? For each subsequent call since input scale doesn't change we don't update weights.

**Comment by hexiangquan** [comment]
yes .just first infer take about 8 on my Android test device. later infer is fast.  发自我的华为手机-------- 原始邮件 --------主题：Re: [pytorch/pytorch] andoroid  quantization  model (mobilenetv2) first forward  very slow?  but second forward  faster why how to fix it (#28778)发件人：supriyar 收件人：pytorch/pytorch 抄送：x_He ,Author This should be called only once - during the first call to forward. Is that what you mean by first infer? For each subsequent call since input scale doesn't change we don't update weights.

**Comment by hexiangquan** [comment]
i do a face liveness sdk.  do it only once when app start. but quantization model first infer so slow .i do not know how to fix it发自我的华为手机-------- 原始邮件 --------主题：Re: [pytorch/pytorch] andoroid  quantization  model (mobilenetv2) first forward  very slow?  but second forward  faster why how to fix it (#28778)发件人：supriyar 收件人：pytorch/pytorch 抄送：x_He ,Author This should be called only once - during the first call to forward. Is that what you mean by first infer? For each subsequent call since input scale doesn't change we don't update weights.
