### ISSUE TITLE
Website gives incorrect install command for cudatoolkit version

### ISSUE THREAD

**Issue by Multihuntr** [pytorch/pytorch#28825]
## 📚 Documentation

According to the [getting started page](https://pytorch.org/get-started/previous-versions/), I should install older versions of pytorch with commands like `conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit==10.0 -c pytorch`

However, I get:

```
$ conda search cudatoolkit
Loading channels: done
# Name                       Version           Build  Channel             
cudatoolkit                      9.0      h13b8566_0  pkgs/main           
cudatoolkit                      9.2               0  pkgs/main           
cudatoolkit                 10.0.130               0  pkgs/main           
cudatoolkit                 10.1.168               0  pkgs/main
```

Resulting in this error message if I use the command exactly as written on the website.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit==10.0
```

But this command works fine: `conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit==10.0.* -c pytorch`

So, depending on how you want to view it, either the command on the website is incorrect, or the cudatoolkit versions aren't tagged correctly. But I suppose you don't have control of the latter.

I am sorry if this is the incorrect place to raise this. I couldn't find anywhere else to report it.

**Comment by peterjc123** [comment]
Oh yes, you should use one `=` instead of two. cc @soumith for fixing the commands in the quick start page.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch.github.io/commit/0838ba1fbf4e02dbd73c0071f571bb4ed5f4143a
