### ISSUE TITLE
why tensor.sum() not equals sum(tensor) 

### ISSUE THREAD

**Issue by zym1119** [pytorch/pytorch#28826]
## ❓ Questions and Help

I met this error when calculating histogram of a tensor, and the histogram is calculated by torch.histc()

whatever, the hist is of type torch.Tensor.

and the following thing happened

```python
>>> import torch
>>> hist = torch.load('hist.pth')
>>> hist.sum()
tensor(21956292.)
>>> sum(hist)
tensor(21956260.)
>>> sum(hist[2:]) + sum(hist[:2])
tensor(21956264.)
>>> hist[2:].sum() + hist[:2].sum()
tensor(21956296.)
```

so why these values are not the same?
is it a bug or something went wrong?

the tensor can  be found at
https://github.com/zym1119/a-hist/blob/master/hist.pth

**Comment by soumith** [comment]
floating point error. this is expected.

some more context: https://stackoverflow.com/questions/2100490/floating-point-inaccuracy-examples
