### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'load'

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#28835]
When I run `test/onnx/test_utility_funs.py` locally I get an error:

```
======================================================================
ERROR: test_strip_doc_string (__main__.TestUtilityFuns)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/onnx/test_utility_funs.py", line 226, in test_strip_doc_string
    self.assertTrue(is_model_stripped(io.BytesIO()))
  File "test/onnx/test_utility_funs.py", line 220, in is_model_stripped
    model = onnx.load(io.BytesIO(f.getvalue()))
AttributeError: module 'onnx' has no attribute 'load'

======================================================================
ERROR: test_strip_doc_string (__main__.TestUtilityFuns_opset10)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/onnx/test_utility_funs.py", line 226, in test_strip_doc_string
    self.assertTrue(is_model_stripped(io.BytesIO()))
  File "test/onnx/test_utility_funs.py", line 220, in is_model_stripped
    model = onnx.load(io.BytesIO(f.getvalue()))
AttributeError: module 'onnx' has no attribute 'load'

----------------------------------------------------------------------
```

I can fix it by running `pip install onnx`. But the error message here is unexpected; if onnx wasn't installed, why did I get an error that it imported successfully and just doesn't have any attributes?

When I print `onnx.__file__` I get `None`. My best guess is that we are accidentally picking up `test/onnx` folder as a namespace.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Just add some context (i.e., not exactly the answer to the question) - to the best of my knowledge, `onnx `is not installed as a dependency of PyTorch. It is only a test dependency.

**Comment by nolifenameless** [comment]
this error here is caused by the module 'onnx'（before pip install onnx) which can avoid python import inspection, I try to recur this situation but still got nothing. @ezyang would you like provide info about this situation? that would be very helpful
IMO,  add some context to decide which tests (different scenarios or dependencies) should run may be a choice.

**Comment by ezyang** [comment]
This issue is pretty old so I'm happy to just assume it's been silently fixed since then.

**Comment by Manoj-Borkar** [comment]
I am still getting the same error with onnx.load. Is it resolved?? If yes, could someone pls point me in the right direction

**Comment by saadnajib** [comment]
I had the same problem fixed it in a way that, I had my python file name "onnx.py" same name as the library I was importing, changing the name of my python file from "onnx.py" to "converting_to_onnx.py" solved the issue.

**Comment by dron-dronych** [comment]
for those curious on why this happens is because when you run a py file named "onnx.py" it first adds that directory to your python search path. It then searched for a name to import and the first one it encounters is your directory with YOUR onnx.py. This behavior should be avoided as it adds unexpected behavior to the python import mechanism.

**Comment by kingydw** [comment]
> I had the same problem fixed it in a way that, I had my python file name "onnx.py" same name as the library I was importing, changing the name of my python file from "onnx.py" to "converting_to_onnx.py" solved the issue.

I jumped into this trap too...😂
