### ISSUE TITLE
Dataset link for "Static Quantization for Eager mode in PyTorch" tutorial

### ISSUE THREAD

**Issue by vikashranjan** [pytorch/pytorch#28844]
## ❓ Questions and Help

There is no download link for the dataset mentioned in section 3 in the tutorial for static quantization.

I am trying out the experimental feature for static quantization and need to download the dataset to run the tutorial.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
cc @raghuramank100

**Comment by raghuramank100** [comment]
@SethHWeidman  will be updating the tutorial shortly with clearer instructions
