### ISSUE TITLE
Get rid of torch::save and torch::load in ProcessGroupAgent

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#28849]
`ProcessGroupAgent` uses `torch::save` and `torch::load` to serde messages. It internally creates a zip archive, which can be expensive. Switching to jit::pickle could help to reduce the overhead. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pritamdamania87** [comment]
@mrshenli I believe we can close this after @jjlilley's latest PRs?

**Comment by mrshenli** [comment]
closed by #29785
