### ISSUE TITLE
installing error using pip

### ISSUE THREAD

**Issue by apdomran** [pytorch/pytorch#28840]
I'm trying to install torch and torchvision using python 3.7 and pip, I tried many ways to install torch packages and every way ends with the same error which I don't understand

`Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Requirement already satisfied: pyyaml in c:\users\apdo\appdata\local\programs\python\python37-32\lib\site-packages (from torch) (5.1.2)
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\apdo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Apdo\\AppData\\Local\\Temp\\pip-install-jtgfpdxm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Apdo\\AppData\\Local\\Temp\\pip-install-jtgfpdxm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Apdo\AppData\Local\Temp\pip-record-fe4824qz\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Apdo\AppData\Local\Temp\pip-install-jtgfpdxm\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Apdo\AppData\Local\Temp\pip-install-jtgfpdxm\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Apdo\AppData\Local\Temp\pip-install-jtgfpdxm\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\apdo\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Apdo\AppData\Local\Temp\pip-install-jtgfpdxm\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\apdo\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Apdo\\AppData\\Local\\Temp\\pip-install-jtgfpdxm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Apdo\\AppData\\Local\\Temp\\pip-install-jtgfpdxm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Apdo\AppData\Local\Temp\pip-record-fe4824qz\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by peterjc123** [comment]
Well, it is yet another case that you try to install PyTorch with 32-bit Python on Windows. Please use Python x64 instead.

**Comment by apdomran** [comment]
I reinstalled Python x64 and I still got the same error ?!!

**Comment by apdomran** [comment]
> Well, it is yet another case that you try to install PyTorch with 32-bit Python on Windows. Please use Python x64 instead.

I reinstalled Python x64 and I still got the same error ?!!

**Comment by peterjc123** [comment]
Do you have multiple python installations? What command did you use to install PyTorch?

**Comment by apdomran** [comment]
I have only Python 3.8 x64
I tried ``` pip install torch ``` , ``` pip install pytorch ``` and ``` pip install torchvision ```
