### ISSUE TITLE
How to build caffe2 with ONNX opset version greater than 9?

### ISSUE THREAD

**Issue by zetyquickly** [pytorch/pytorch#28868]
## ❓ Questions and Help

Hello,
I've currently worked with freshly merged feature pytorch/vision#1401 and won't able to find a way to make Caffe2 work with ONNX operation set 10?

Is there a way to build a Caffe2 from source with this opset?

**Comment by izdeby** [comment]
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
