### ISSUE TITLE
test_trainer_ps in dist_autograd_test is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#28874]
failed: https://circleci.com/gh/pytorch/pytorch/3403921?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

passed: https://circleci.com/gh/pytorch/pytorch/3404073?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mrshenli** [comment]
It's this the line below either never returned or crashed:

https://github.com/pytorch/pytorch/blob/41e42c34d65f7dce5f526cdb059e860bbe4d0f36/test/dist_autograd_test.py#L111

**Comment by rohan-varma** [comment]
After looking at recent test results it seems that this is fixed, so closing this out.
