### ISSUE TITLE
Finalize RPC API behavior for CUDA tensors

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#28881]
All tests in `rpc_test.py` and `dist_autograd_test.py` focus on CPU tensors. Nothing prevents us from supporting CUDA tensors, but we need to be clear about what promise we provide on the API. For example, 

1. If a user function returns a CUDA tensor, calling that function through RPC should still return a CPU tensor, or should we try to load that tensor onto the corresponding GPU?
2. When calling RPC with a CUDA tensor as argument, does the callee always get a CPU tensor, or should we try to load it to the corresponding GPU?

I would vote for always return CPU tensor to caller and always pass CPU tensor to callee. If applications would like to work on CUDA tensors, they may do that explicitly in user code.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by rohan-varma** [comment]
It seems like it would be a bit unintuitive if the caller calls RPC with a GPU tensor, and the callee receives a CPU one. We should clearly document if we decide to do this.

**Comment by pritamdamania87** [comment]
There are a couple of options here:

1. For GPU tensors, always implicitly copy the tensor to CPU memory before sending it over the wire. The user code running the python UDF would always receive CPU tensors as arguments and the return value on the caller side is always a CPU tensor.
2. RPC API throws an exception that it doesn't support sending GPU tensors over the wire.

For now, I feel 2. is a better option. This way we ask the user to explicitly copy a GPU tensor to CPU before they can send it over the wire with RPC. With 1. there is some implicit magic happening under the hood and it might not be a great user experience (even if we document this well). There is obviously a performance issue with 2., but for now I feel it's better to expect an explicit copy from the user and we can think about optimizing these as part of the TensorPipe effort.
