### ISSUE TITLE
New Windows Pytorch version throttles OpenMP

### ISSUE THREAD

**Issue by aviolov** [pytorch/pytorch#2888]
We are using the experimental windows version of pytorch
https://github.com/pytorch/pytorch/issues/494
https://github.com/peterjc123/pytorch
via the anaconda package  pytorch.version == 0.2.1, on windows 10, python 3.6

We experience that after importing torch, unrelated code (xgboost in our case), suddenly cannot fully utilize OpenMP. Here is a basic example showing some naive OPenMP code that suddenly gets 'throttled' to only one core after `import torch` is called
https://gist.github.com/aviolov/f3f836a2954fa63100ce02891eeb7bf7

We also did not / do not experience this issue if we downgrade to 
>> conda install -c peterjc123 pytorch=0.1.12

The exact call that does this is loading the _C library in torch 
torch::__init__.py:
40: from torch._C import *

I can't determine which of the exact .dll loaded is responsible.

**Comment by peterjc123** [comment]
I think this is a dependency issue. The latest version(1.13.1) of numpy is used during compilation. However, if you use xgboost, the numpy version should be downgraded to 1.12.1. In order to solve this issue, you should compile either xgboost or pytorch on your own using the same numpy version.

**Comment by peterjc123** [comment]
If that doesn't help with that issue, you may see something from #975 and #1227. It's not a Windows-specific problem.

**Comment by aviolov** [comment]
Explicitly setting 
`torch.set_num_threads(6)`
would fix the issue

**Comment by aviolov** [comment]
Also I don't think it has anything to do with xgboost per-se, b/c we can recreate the issue without any xgboost references. E.g. in torch.__init__.py:line 40 just after from torch._C import *, calling get_num_threads() returns 1

**Comment by peterjc123** [comment]
I can't reproduce this. Since when I call get_num_threads() after importing torch, it returns 8.

**Comment by aviolov** [comment]
Thanks. I also can't reproduce it on Linux (after importing torch it returns 4). But the throttling happens on all our windows machines at work.

**Comment by peterjc123** [comment]
#6416 is on this.
