### ISSUE TITLE
I can not use multiple gpu because of my data type is easydict

### ISSUE THREAD

**Issue by tianlanli** [pytorch/pytorch#28880]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
```
        if isinstance(obj, dict) and len(obj) > 0:
            return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
```
this is from torch/nn/parallel/scatter_gather.py function def scatter_map(obj)
if my type(obj) is easydict then can not map obj.items() to easydict, but if the type is dict, then ok.
I want to use the type of easydict ,how can i do?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by tianlanli** [comment]
> please use https://discuss.pytorch.org for questions
```
    if isinstance(obj, dict) and len(obj) > 0:
        return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
```
can you tell my why map type(obj) rather than map dict :

```
    if isinstance(obj, dict) and len(obj) > 0:
        return list(map(dict, zip(*map(scatter_map, obj.items()))))
```
