### ISSUE TITLE
C++ `torch::tensor` by default gives a double tensor, which is different from Python `torch.tensor` behavior

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#28902]
Example:
In C++:
```cpp
torch::tensor({1., 2., 3.}).dtype() -> double
```

In Python:
```python
>>> torch.tensor([1., 2., 3.]).dtype
torch.float32
```

cc @yf225

**Comment by maxwillzq** [comment]
It is because C++ does implicit conversion from {1., 2., 3.} to double type.  
If we force input is float, it will give your float tensor.

For example:
```c++
    auto t = torch::tensor({float(1.), float(2.), float(3.)});
    std::cout <<"data type is " << t.dtype().name() <<std::endl;
```
it will print "float" data type

**Comment by yf225** [comment]
@maxwillzq Thanks for the investigation! This should already be fixed by https://github.com/pytorch/pytorch/pull/29632.
