### ISSUE TITLE
test_backward_autograd_engine_error  is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#28928]
Failed test: https://circleci.com/gh/pytorch/pytorch/3412165?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by zhaojuanmao** [comment]
Oct 30 21:46:27 test_backward_autograd_engine_error (__main__.DistAutogradTestWithFork) ... python: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Oct 30 21:46:27 terminate called after throwing an instance of 'gloo::IoException'
Oct 30 21:46:27   what():  [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [172.17.0.2]:13231: Connection reset by peer
Oct 30 21:49:47 ERROR

**Comment by pritamdamania87** [comment]
@mrshenli Is there a way to lookup all failures for a particular test?

**Comment by pritamdamania87** [comment]
I haven't been able to repro this failure so far. I tried running the test 200 times on the docker container for the failed run but haven't seen any failures yet.

**Comment by mrshenli** [comment]
> Is there a way to lookup all failures for a particular test?

@pritamdamania87 I am not aware. 
cc @ezyang

**Comment by mrshenli** [comment]
If you click into the dr.ci, and then click patterns, it will show the number of occurrences of the same failures in that PR.

**Comment by pritamdamania87** [comment]
> If you click into the dr.ci, and then click patterns, it will show the number of occurrences of the same failures in that PR.

I see, although I was hoping to see all failures for this test in master. Looks like there is no way to do this currently.

I'm not sure if this failure is related to the test or pytorch in general. Can we try re-enabling this test since I can't seem to find a way to reproduce this issue?

**Comment by pritamdamania87** [comment]
Looks like I figured out the problem with this test. We're running into the issue described here: https://github.com/pytorch/pytorch/issues/26922. The autograd engine on one node hits an error and then we try to clean up the autograd context on other nodes while they are still using the autograd context. Will send a PR to fix this soon.
