### ISSUE TITLE
ONNX error converting torch.mean

### ISSUE THREAD

**Issue by JimnyCricket** [pytorch/pytorch#2892]
I've been working to convert some models using sentence embeddings via ONNX and have run into the following error while running `torch.onnx._export`: 
`RuntimeError: PythonOp doesn't define symbolic Mean`

I also had this error when trying to implement my own "mean" operation using add and divide.

**Comment by ezyang** [comment]
ReduceMean is in https://github.com/onnx/onnx/blob/master/docs/Operators.md so this should be doable without Caffe2 adjustments (though maybe onnx-caffe2 will need to be clued in)

**Comment by houseroad** [comment]
I will take a look at this. :-)
