### ISSUE TITLE
test_py_built_in rpc test is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#28932]
## 🐛 Bug

`test_py_built_in` rpc spawn test is flaky, see failure: https://app.circleci.com/jobs/github/pytorch/pytorch/3409933

We should probably disable this test while we investigate.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mrshenli** [comment]
Yes, let's disable it for now. It seems something in RPC core become flaky recently. This one and #28920 should not be affected by the recent changes on RRef.

**Comment by zhaojuanmao** [comment]
Oct 30 13:55:04 test_py_built_in (__main__.RpcTestWithSpawn) ... libc++abi.dylib: terminating with uncaught exception of type c10::Error: Need to initialize distributed autograd using torch.distributed.autograd.init() (getInstance at ../torch/csrc/distributed/autograd/context/dist_autograd_container.cpp:57)
Oct 30 13:55:04 frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x11690fdd7 in libc10.dylib)
Oct 30 13:55:04 frame #1: torch::distributed::autograd::DistAutogradContainer::getInstance() + 500 (0x1131693a4 in libtorch.dylib)
Oct 30 13:55:04 frame #2: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 37 (0x113183565 in libtorch.dylib)
Oct 30 13:55:04 frame #3: std::__1::__function::__func<std::__1::__bind<torch::distributed::rpc::ProcessGroupAgent::enqueueRecv(torch::distributed::rpc::RecvWork)::$_2, torch::distributed::rpc::RecvWork>, std::__1::allocator<std::__1::__bind<torch::distributed::rpc::ProcessGroupAgent::enqueueRecv(torch::distributed::rpc::RecvWork)::$_2, torch::distributed::rpc::RecvWork> >, void ()>::operator()() + 1132 (0x10f733d8c in libtorch_python.dylib)
Oct 30 13:55:04 frame #4: c10::ThreadPool::main_loop(unsigned long) + 527 (0x11690b1df in libc10.dylib)
Oct 30 13:55:04 frame #5: std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, c10::ThreadPool::ThreadPool(int, int, std::__1::function<void ()>)::$_0> >(void*, void*) + 67 (0x11690b6f3 in libc10.dylib)
Oct 30 13:55:04 frame #6: _pthread_body + 180 (0x7fff8ff1993b in libsystem_pthread.dylib)
Oct 30 13:55:04 frame #7: _pthread_body + 0 (0x7fff8ff19887 in libsystem_pthread.dylib)
Oct 30 13:55:04 frame #8: thread_start + 13 (0x7fff8ff1908d in libsystem_pthread.dylib)

**Comment by zhaojuanmao** [comment]
distributed autograd is not initialized for this test

**Comment by rohan-varma** [comment]
@zhaojuanmao @mrshenli I'm not sure how the code path indicated by the above error trace can be executed, since this test doesn't use dist autograd. Is it possible that this could be caused by recent changes to how python UDFs are handled?

**Comment by zhaojuanmao** [comment]
talked with @pritamdamania, he mentioned the dist autograd initialization may need barrier. it is possibly one process send rpc to another process, but another process has not finish autograd initialization yet

**Comment by pritamdamania87** [comment]
> talked with @pritamdamania, he mentioned the dist autograd initialization may need barrier. it is possibly one process send rpc to another process, but another process has not finish autograd initialization yet

I think our initialization overall might need some barrier. Since one node might finish RPC initialization and call an RPC on another node which hasn't initialized RPC yet and this would result in the RPC call failing.

**Comment by mrshenli** [comment]
closed by #29069
