### ISSUE TITLE
RuntimeError: Didn't find engine for operation quantized::conv_prepack NoQEngine

### ISSUE THREAD

**Issue by vellano** [pytorch/pytorch#28945]
I build pytorch 1.3 on Arm A53 from source, and run the tutorial code static_quantization_tutorial, it produce the error:

holo@ark:~/hlh/tutorials/advanced_source$ python static_quantization_tutorial.py 
/usr/local/lib/python3.6/dist-packages/torchvision-0.5.0a0+1e857d9-py3.6-linux-aarch64.egg/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available

 Inverted Residual Block: Before fusion 

 Sequential(
  (0): ConvBNReLU(
    (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
    (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
  )
  (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
  (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

 Inverted Residual Block: After fusion

 Sequential(
  (0): ConvBNReLU(
    (0): ConvReLU2d(
      (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32)
      (1): ReLU()
    )
    (1): Identity()
    (2): Identity()
  )
  (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1))
  (2): Identity()
)
Size of baseline model
Size (MB): 13.98006
..........Evaluation accuracy on 300 images, 78.00
QConfig(activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True), weight=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric))
Post Training Quantization Prepare: Inserting Observers

 Inverted Residual Block:After observer insertion 

 Sequential(
  (0): ConvBNReLU(
    (0): ConvReLU2d(
      (0): Conv2d(
        32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32
        (observer): MinMaxObserver(min_val=None, max_val=None)
      )
      (1): ReLU(
        (observer): MinMaxObserver(min_val=None, max_val=None)
      )
    )
    (1): Identity()
    (2): Identity()
  )
  (1): Conv2d(
    32, 16, kernel_size=(1, 1), stride=(1, 1)
    (observer): MinMaxObserver(min_val=None, max_val=None)
  )
  (2): Identity()
)
..........Post Training Quantization: Calibration done
Traceback (most recent call last):
  File "static_quantization_tutorial.py", line 434, in <module>
    **torch.quantization.convert(myModel, inplace=True)**
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 292, in convert
    convert(mod, mapping, inplace=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 292, in convert
    convert(mod, mapping, inplace=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 293, in convert
    reassign[name] = swap_module(mod, mapping)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 315, in swap_module
    new_mod = mapping[type(mod)].from_float(mod)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py", line 47, in from_float
    return super(ConvReLU2d, cls).from_float(mod)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/modules/conv.py", line 245, in from_float
    mod.bias is not None, mod.padding_mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py", line 25, in __init__
    groups=groups, bias=bias, padding_mode=padding_mode)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/modules/conv.py", line 88, in __init__
    self.set_weight_bias(qweight, bias_float)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/modules/conv.py", line 111, in set_weight_bias
    w, b, self.stride, self.padding, self.dilation, self.groups)
**RuntimeError: Didn't find engine for operation quantized::conv_prepack NoQEngine (operator() at /home/holo/hlh/pytorch/aten/src/ATen/native/quantized/cpu/qconv_prepack.cpp:264)**
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x78 (0x7f7ba836a8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xbd3620 (0x7f7c67e620 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0xbd3c00 (0x7f7c67ec00 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x19caf8c (0x7f7d475f8c in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x2385318 (0x7f7de30318 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x507528 (0x7f7f583528 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x4d3060 (0x7f7f54f060 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x220824 (0x7f7f29c824 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #9: python() [0x528738]
frame #11: python() [0x527208]
frame #12: python() [0x52883c]
frame #14: python() [0x52823c]
frame #15: python() [0x528650]
frame #17: python() [0x52823c]
frame #22: python() [0x4b7e74]
frame #23: python() [0x4b1ef0]
frame #25: python() [0x52842c]
frame #27: python() [0x527208]
frame #28: python() [0x52883c]
frame #30: python() [0x52823c]
frame #31: python() [0x528650]
frame #33: python() [0x527208]
frame #34: python() [0x52883c]
frame #36: python() [0x52823c]
frame #37: python() [0x528650]
frame #39: python() [0x52823c]
frame #40: python() [0x528650]
frame #42: python() [0x52823c]
frame #43: python() [0x528650]
frame #45: python() [0x52823c]
frame #51: __libc_start_main + 0xe0 (0x7f860d56e0 in /lib/aarch64-linux-gnu/libc.so.6)
frame #52: python() [0x420dcc]

**The nearby code:
# Calibrate first
print('Post Training Quantization Prepare: Inserting Observers')
print('\n Inverted Residual Block:After observer insertion \n\n', myModel.features[1].conv)

# Calibrate with the training set
evaluate(myModel, criterion, data_loader, neval_batches=num_calibration_batches)
print('Post Training Quantization: Calibration done')

# Convert to quantized model
torch.quantization.convert(myModel, inplace=True)
print('Post Training Quantization: Convert done')
print('\n Inverted Residual Block: After fusion and quantization, note fused modules: \n\n',myModel.features[1].conv)

print("Size of model after quantization")
print_size_of_model(myModel)**

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake .. && make -j4
 - Python version: 3.6.8
 - CUDA/cuDNN version: no
 - GPU models and configuration: no
 - Any other relevant information: no

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
Is fbgemm enabled? 
cc @jianyuh @dskhudia

**Comment by dzhulgakov** [comment]
@supriyar - would ARM be detected as mobile build or not? (so that we build qnnpack)

FBGEMM-baked quantized kernels work only on x86. We have ARM implementations with QNNPACK but we might be picking those only on mobile build right now (that support is more experimental).

@vellano - what is your system? is it embedded one?

**Comment by supriyar** [comment]
QNNPACK should be built by default if the USE_PYTORCH_QNNPACK flag is set (which is set to true by default). However if the platform is not one of Android, iOS, Linux, and macOS then we set this to OFF as qnnpack is unsupported. The build should emit a warning. https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L323

Accessing `Context::supportedQEngines()` will give a list of supported quantized engines on the target system.

**Comment by vellano** [comment]
> @supriyar - would ARM be detected as mobile build or not? (so that we build qnnpack)
> 
> FBGEMM-baked quantized kernels work only on x86. We have ARM implementations with QNNPACK but we might be picking those only on mobile build right now (that support is more experimental).
> 
> @vellano - what is your system? is it embedded one?
Thanks for the reply ~
yes，i build it on nxp s32v soc. The OS is ubantu 18.04.

**Comment by vellano** [comment]
> QNNPACK should be built by default if the USE_PYTORCH_QNNPACK flag is set (which is set to true by default). However if the platform is not one of Android, iOS, Linux, and macOS then we set this to OFF as qnnpack is unsupported. The build should emit a warning. https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L323
> 
> Accessing `Context::supportedQEngines()` will give a list of supported quantized engines on the target system.


Thanks for the reply ~
I checked USE_PYTORCH_QNNPACK, it is on and qnnpack is build.

**Comment by supriyar** [comment]
> > QNNPACK should be built by default if the USE_PYTORCH_QNNPACK flag is set (which is set to true by default). However if the platform is not one of Android, iOS, Linux, and macOS then we set this to OFF as qnnpack is unsupported. The build should emit a warning. https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L323
> > Accessing `Context::supportedQEngines()` will give a list of supported quantized engines on the target system.
> 
> Thanks for the reply ~
> I checked USE_PYTORCH_QNNPACK, it is on and qnnpack is build.

In that case, can you try setting the following before calling torch.jit.load on your model?
```
if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
    at::globalContext().setQEngine(at::QEngine::QNNPACK);
  }
```
By default we don't set qnnpack as default engine if it is built. In the current setup it needs to be explicitly specified by the user if they want to use it.

**Comment by vellano** [comment]
> > > QNNPACK should be built by default if the USE_PYTORCH_QNNPACK flag is set (which is set to true by default). However if the platform is not one of Android, iOS, Linux, and macOS then we set this to OFF as qnnpack is unsupported. The build should emit a warning. https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L323
> > > Accessing `Context::supportedQEngines()` will give a list of supported quantized engines on the target system.
> > 
> > 
> > Thanks for the reply ~
> > I checked USE_PYTORCH_QNNPACK, it is on and qnnpack is build.
> 
> In that case, can you try setting the following before calling torch.jit.load on your model?
> 
> ```
> auto qengines = at::globalContext().supportedQEngines();
>   if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
>     at::globalContext().setQEngine(at::QEngine::QNNPACK);
>   }
> ```
> 
> By default we don't set qnnpack as default engine if it is built. In the current setup it needs to be explicitly specified by the user if they want to use it.

Thanks for the reply ~
I add the code above, and the problom is fixed, thanks~~

**Comment by YuantianGao** [comment]
Hello, vellano, I have a same issue with you @vellano. And I want to ask how did you add these code below in python? 
```
auto qengines = at::globalContext().supportedQEngines();
  if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
    at::globalContext().setQEngine(at::QEngine::QNNPACK);
  }

```

**Comment by pkarimib** [comment]
Hello @vellano, I have the same question as @YuantianGao. Thanks

**Comment by HSunshine99** [comment]
> 

你好，我想问下怎么检查USE_PYTORCH_QNNPACK标志呢，感谢你的帮助
