### ISSUE TITLE
Move misc. RPC arguments to an Options structure

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#28940]
## 🚀 Enhancement
There are a couple of different rpc options when we initialize model parallel right now, such as number of send/recv threads and the timeout for RPCs. It is likely that this list will grow, so it would be good to consolidate this into an options class `RpcOptions`. This can be implemented in `rpc_agent.h` since the arguments should be applicable for all rpc agents.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
IMO we shouldn't do this before it becomes extreme, because you could make the same argument for every other constructor with 3 or more arguments. Also, we have the luxury of kwargs.

**Comment by rohan-varma** [comment]
@xush6528 addressed this issue, we now have an `RpcAgentOptions` struct.
