### ISSUE TITLE
Add torch.nn.GELU as the module for GELU activation

### ISSUE THREAD

**Issue by BIT-silence** [pytorch/pytorch#28947]
## 🚀 Feature

Add torch.nn.GELU as the module for GELU activation.

## Motivation

Currently we have a torch.nn.functional.gelu op but no corresponding module like we do for the other activations (e.g. nn.ReLU()).

**Comment by PrachiPrakash** [comment]
can I work on this task  looks good for a starter

**Comment by BIT-silence** [comment]
> can I work on this task looks good for a starter

I'm sorry that we have already prepared https://github.com/pytorch/pytorch/pull/28944 to fix this as fast as possible. Maybe next time.
