### ISSUE TITLE
Is the bias quantized when torch.quantization.convert()?

### ISSUE THREAD

**Issue by zyl19930813** [pytorch/pytorch#28952]
## 🚀 Feature

When I use the torch.quantization.convert() and print the bias, I find the bias has no scale. 
## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by gemfield** [comment]
bias is not quantized during convert() API, however, it will be quantized to int32 during inference. You can have a look at aten/src/ATen/native/quantized/cpu/qconv.cpp and https://zhuanlan.zhihu.com/p/299108528
