### ISSUE TITLE
A question about static_quantization_tutorial

### ISSUE THREAD

**Issue by ArsenLuca** [pytorch/pytorch#28951]
When I run the code about static post-training quant in https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html,
a warning rises that 
**"/home/arsen/anaconda3/lib/python3.7/site-packages/torch/quantization/observer.py:592: UserWarning: must run observer before calling calculate_qparams.                                    Returning default scale and zero point 
  Returning default scale and zero point "**

Are there any problems?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by sahajgarg** [comment]
There are no problems with this. Not all of the inverted residual modules have a residual connection (res_connect), so when quantization occurs, those modules have never been used and consequently use the default scale/zero_point. The quantized model does not use these connections either, so it doesn't matter.

**Comment by srohit0** [comment]
It's an exception in Pytorch 1.4, not a warning. 

> /usr/local/lib/python3.6/dist-packages/torch/quantization/observer.py in calculate_qparams(self)
>      44         n_levels = 255.0
>      45         if self.max_val is None or self.min_val is None:
> ---> 46             raise Exception('must run observer before calling calculate_qparams!')
>      47         max_val, min_val = self.max_val.item(), self.min_val.item()
>      48         if max_val == min_val:
> 
> **Exception: must run observer before calling calculate_qparams!**
