### ISSUE TITLE
test_backward_node_failure is flaky

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#28976]
## 🐛 Bug

Using sleep to simulate syncronization is flaky.

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pritamdamania87** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/28824
