### ISSUE TITLE
[jit] support self._modules in TorchScript

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#28998]
```
import torch

import torch.nn as nn

class DesiredModel(nn.Module):
    __constants__ = ['m_names']
    def __init__(self):
        super().__init__()
        m_names = []
        for i in range(3):
            self.add_module(str(i), nn.ReLU())
            m_names.append(str(i))
        self.m_names = m_names

    def forward(self, x):
        o = []
        for m in self._modules.values():
            o.append(m(x))
        return torch.cat(o, 1)

scripted = torch.jit.script(DesiredModel())
```

now throws:

```
RuntimeError: 
Module 'DesiredModel' has no attribute '_modules' :
at :17:17
    def forward(self, x):
        o = []
        for m in self._modules.values():
                 ~~~~~~~~~~~~~ <--- HERE
            o.append(m(x))
        return torch.cat(o, 1)
```

cc @suo

**Comment by driazati** [comment]
`_modules` itself shouldn't be exposed, but the accessor methods (e.g. `modules()`, `named_children()`, `named_modules()`, `children()` should be

**Comment by wanchaol** [comment]
> `_modules` itself shouldn't be exposed, but the accessor methods (e.g. `modules()`, `named_children()`, `named_modules()`, `children()` should be

most of these are iterators unfortunately.. Maybe we should override them in ScriptModule and return list instead.

**Comment by eellison** [comment]
> `_modules` itself shouldn't be exposed, but the accessor methods (e.g. `modules()`, `named_children()`, `named_modules()`, `children()` should be

Why not support it ? It should be 1-1 correspondence.

**Comment by chenbohua3** [comment]
@eellison is there any plans to support `named_buffers` and `named_parameters`?

**Comment by eellison** [comment]
@chenbohua3 mind opening an issue ?

**Comment by chenbohua3** [comment]
@eellison of course
