### ISSUE TITLE
BN layer buffers does not update when the model is deeply copied

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/pytorch#29015]
## 🐛 Bug
Just run this example code: 

```python
import copy
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import torchvision

from apex import amp


net = torchvision.models.resnet18()
net.cuda()
optim = torch.optim.SGD(net.parameters(), lr=1e-3,)
net, optim = amp.initialize(net, optim, opt_level="O0")

net = copy.deepcopy(net)
net.train()

bn_modules = (
    nn.BatchNorm1d,
    nn.BatchNorm2d,
    nn.BatchNorm3d,
    nn.SyncBatchNorm,
)
bn_layers = [
    m
    for m in net.modules()
    if m.training and isinstance(m, bn_modules)
]

print(bn_layers[0].running_mean[:3])
inten = torch.randn(32, 3, 224, 224).cuda()
out = net(inten)
print(bn_layers[0].running_mean[:3])
inten = torch.randn(32, 3, 224, 224).cuda()
out = net(inten)
print(bn_layers[0].running_mean[:3])
```
Run the above code I found that the running mean value does not get updated, unless I comment the line of `net = copy.deepcopy(net)`.

## Environment
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4
GPU 6: Tesla T4
GPU 7: Tesla T4

Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

**Comment by colesbury** [comment]
I'm not sure what you're trying to do, but:

a) This seems specific to using apex. You should report bugs to NVIDIA/apex repo
b) You're copying the net, but the optimizer still has references to the original net so that's not going to work
