### ISSUE TITLE
Speed slows down after model quantization

### ISSUE THREAD

**Issue by jiacheng1gujiaxin** [pytorch/pytorch#29024]
my model is based on E-inception,after quantized  , i found it forward slower,
the original model run on CPU cost 200ms and 20ms on GPU , but the quantized model cost 290ms,

is it caused by the operation of layers concatenate?? 

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by colesbury** [comment]
@jiacheng1gujiaxin I don't think there's enough information here to give an answer to why your model is slower. Please re-open the issue with sufficient code to reproduce the issue (for example, the model definition).

Maybe @jerryzh168 (cc'd; or anyone else working on quantization) knows something generally about why models may be slower after quantization?

**Comment by DuYangGitHub** [comment]
have you ever solved this problem?

**Comment by jerryzh168** [comment]
We need more information for this, can you post your original and annotated model?

Sent from my iPhone

On Nov 27, 2019, at 03:56, Du Yang <notifications@github.com> wrote:

﻿

have you ever solved this problem?
