### ISSUE TITLE
why conda install python3.6.7 for pytorch ???

### ISSUE THREAD

**Issue by isaac-you** [pytorch/pytorch#29020]
Hello

According to https://pytorch.org/  
I use the code :

```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
to install pytorch in my ubuntu system 

but when I use ipython to start python and import torch then  report : 
```
ModuleNotFoundError: No module named 'pytorch'
```

And when I use python in the terminal to start python , then it is ok 

So, when use the code to install pytorch  it is automatically install python3.6.7 for pytorch  
but anaconda is under python3.6.5  then cannot import torch 

How can I fix the problem 
Thank you.

**Comment by colesbury** [comment]
The module name is "torch": use `import torch` (not import pytorch)

If you use the Anaconda (miniconda3) Python 3.7 installer it will use Python 3.7:
https://docs.conda.io/en/latest/miniconda.html

**Comment by isaac-you** [comment]
···
ModuleNotFoundError: No module named 'torch'
···

anaconda default python version is python3.6.5 
but 
```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
automatically installed a new python3.6.7  to support pytorch.

**Comment by isaac-you** [comment]
```
isaac@AIServer01:~$ source activate pytorch12
(pytorch12) isaac@AIServer01:~$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-eb42ca6e4af3> in <module>()
----> 1 import torch

ModuleNotFoundError: No module named 'torch'

```

```
(pytorch12) isaac@AIServer01:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.3.0'
>>> 

```

so the ipython from anaconda cannot use pytorch  and python can
