### ISSUE TITLE
_load_from_state_dict in Observers should check if key is in state_dict 

### ISSUE THREAD

**Issue by jafermarq** [pytorch/pytorch#29032]
If a model uses observers (for quantisation) and then this model is saved and used to initialise another model, if this second model has additional observers, `_load_from_state_dict` will raise a `key error` since it currently doesn't check if the key is present in the `state_dict`. I think this check should be enforced if `strict = False`

## To Reproduce

1. Define two models where the second has an additional `torch.quantization.Observer`
1. Save the first model
1. Load the first model and use it to initialise the second model.

### A Concrete example

```python

import torch
import torch.nn as nn


class modelA(nn.Module):
    def __init__(self):
        super(modelA, self).__init__()

        self.observer = torch.quantization.MinMaxObserver()

    def forward(self, input):
        self.observer(input)

class modelB(modelA):
    def __init__(self):
        super(modelB, self).__init__()

        self.observer_ = torch.quantization.MinMaxObserver()


if __name__ == '__main__':

    # model A
    a = modelA()

    # do something
    input = torch.randn(32)
    a(input)

    # save a
    torch.save(a.state_dict(), "a.pt")

    # define model B
    b = modelB()
    target_model_dict = b.state_dict()

    # Now we want to initilize all params in B with those from A.
    # Here I follow the steps as in https://discuss.pytorch.org/t/how-to-load-part-of-pre-trained-model/1113/3

    # 0. loading pre-trained dict
    source_dict = torch.load("a.pt")

    # 1. filter out unnecessary keys
    source_dict = {k: v for k, v in source_dict.items() if k in target_model_dict}

    # 2. overwrite entries in the existing state dict
    target_model_dict.update(source_dict) 

    # 3. load the new state dict
    not_found = b.load_state_dict(source_dict, strict=False) # <-- will crash

    print(not_found)

```

In `load_from_state_dict` it attempts to directly `.pop()` from the inputed `state_dict` (i.e. that from the first model). And, because it doesn't contain `observer_` it will trigger an error as:

```
  File "{...}/miniconda3/envs/Pytorch1.3/lib/python3.7/site-packages/torch/quantization/observer.py", line 238, in _load_from_state_dict
    self.min_val = state_dict.pop(prefix + 'min_val')
KeyError: 'observer_.min_val'
```

## Expected behavior

Simply checking if the desired key/val to `.pop()` is in `state_dict` will solve this issue. I think this should be the default if `strict = False`.

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.11.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.3.0                   py3.7_0    pytorch
[conda] torchvision               0.4.1                  py37_cpu    pytorch

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
this was fixed, so closing
