### ISSUE TITLE
register_forward_hooks (and register_backward_hooks) support for TorchScript.

### ISSUE THREAD

**Issue by pichuang1984** [pytorch/pytorch#29037]
## 🚀 Feature
register_forward_hooks (and register_backward_hooks) supported in TorchScript.

## Motivation

A lot of times we inherent a model or get the model from some other developers and wish to trace the model quickly to understand its flop and memory requirement based on an input size. We used to be able to do that by adding a hook (through register_forward_hooks) but not anymore with the latest pytorch detectron2 repo.

## Pitch

Adding register_forward_hook (and register_backward_hook) for ScriptModules

## Alternatives

Can not think of any alternative at the moment.

## Additional context

N/A

cc @suo @gmagogsfm

**Comment by suo** [comment]
Thanks for the feature request! We plan to implement hooks in the near future, but I don't have an exact timeline yet. I'll update this issue with more information when we have it

**Comment by eellison** [comment]
PR https://github.com/pytorch/pytorch/pull/36183

**Comment by Lilyjjo** [comment]
ScriptModule forward hooks and pre-hooks were added by PR #49544. Backward tensor hooks are still not supported in JIT, but if there's still a desire feel free to open a new issue for them!

**Comment by davidbau** [comment]
Puzzled.  Even after integrating PR #49544, I get `register_forward_hook is not supported on ScriptModules` - is this the same problem or a different issue?

```~/.conda/envs/cpenv/lib/python3.8/site-packages/torch/jit/_script.py in fail(self, *args, **kwargs)
    726     def _make_fail(name):
    727         def fail(self, *args, **kwargs):
--> 728             raise RuntimeError(name + " is not supported on ScriptModules")
    729 
    730         return fail

RuntimeError: register_forward_hook is not supported on ScriptModules```

**Comment by Lilyjjo** [comment]
@davidbau The support we added requires that the hooks be added to the ScriptModules before scripting for forward_hooks and forward_pre_hooks. We decided against the route of allowing hooks to be added post scripting because it introduced negative performance implications
