### ISSUE TITLE
Broken links on https://pytorch.org/docs/stable/tensors.html

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#29043]
## 📚 Documentation

The Tensor documentation page has broken links to torchtext, torchaudio, and C++ API. These broken links do not appear on the main documentation page.

https://pytorch.org/docs/stable/tensors.html

<img width="435" alt="Screen Shot 2019-11-01 at 1 23 03 PM" src="https://user-images.githubusercontent.com/655866/68043204-1f861980-fcab-11e9-9327-8f05b4b350b9.png">

**Comment by Jaisu-1** [comment]
Can I try my hand on this?

**Comment by Jaisu-1** [comment]
Hello, @colesbury I'd like to be assigned this issue.

**Comment by colesbury** [comment]
Thanks you for volunteering to fix it @Jaisu-1, but this appears to be fixed with the current docs.
