### ISSUE TITLE
Feature request: `torch.utils.tensor_wrapper/tensor_unwrapper` for convert to Variable, send to GPU etc. 

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#2904]
This is to confirm if such a function worth a PR ?

**Comment by soumith** [comment]
what is the purpose of this? From the title i still dont understand what this feature / API looks like.

**Comment by zuoxingdong** [comment]
@soumith 
It might make the code cleaner. 

e.g. 

```
a = torch.FloatTensor([1, 2, 3])
if torch.cuda.is_available():
    a = Variable(a).cuda()
else:
    a = Variable(a)
b = f(a)
if torch.cuda.is_available():
    print(b.grad.cpu().numpy())
else:
    print(b.grad.numpy())
```

can be replaced by 
```
a = torch.FloatTensor([1, 2, 3])
b = f(utils.tensor_wrapper(a, to_Variable=True, to_GPU=True))
print(utils.tensor_unwrapper(b.grad, to_Numpy=True, to_CPU=True))
```

Another convenience might be automatic switch between CPU/GPU mode without changing every line which contains .cpu() or cuda(). 

Or maybe not :) ?

**Comment by soumith** [comment]
i dont think this is something we'd like.
We are also slowly getting rid of the Variable abstraction, see the proposal in https://github.com/pytorch/pytorch/issues/2630#issue-255359536
