### ISSUE TITLE
Windows build in virtual environment problem

### ISSUE THREAD

**Issue by traits** [pytorch/pytorch#29058]
## To Reproduce

1. Create a virtual environment on Windows 10 and build pytorch from sources

## Environment

- Base Python installation (WinPython, portable): `V:/bin/scripting/python/3.7.4`
- Dedicated virtual environment: `V:/bin/scripting/python/v/pytorch`

From pytorch's setup.py configuration summary:
```
--   BUILD_PYTHON          : True                                                    
--     Python version      : 3.7.4                                                   
--     Python executable   : V:/bin/scripting/python/v/pytorch/Scripts/python.exe    
--     Pythonlibs version  : 3.7.4                                                   
--     Python library      : V:/bin/scripting/python/v/pytorch/libs/python37.lib     
--     Python includes     : V:/bin/scripting/python/3.7.4/python-3.7.4.amd64/include
--     Python site-packages: Lib/site-packages                                       
```
Error, immediately following:
```
cmake --build . --target install --config Release -- -j 8
ninja: error: 'V:/bin/scripting/python/v/pytorch/libs/python37.lib'', needed by 'caffe2/python/caffe2_pybind11_state.cp37-win_amd64.pyd', missing and no known rule to make it
```

The error output is quite straightforward, because python37.lib will not be copied to `V:/bin/scripting/python/v/pytorch/libs`, while creating the virtual environment with venv (this is different to - for example - virtual environments, created with conda).

## Additional context

The problem seems to be related to the following virtualenv behavior:

[virtualenv bug-tracker](https://github.com/pypa/virtualenv/issues/1182)
[possible solution](https://github.com/pypa/virtualenv/issues/1182#issuecomment-476278700)

cc @peterjc123

**Comment by VitalyFedyunin** [comment]
Have you tried building with `python setup.py install` following https://github.com/pytorch/pytorch#install-pytorch instructions?

**Comment by traits** [comment]
Yes, of course. I build pytorch regularly from a specific conda environment  and even from a standard WinPython-based 'installation' (portable). As I said, only virtual environments, generated with venv show this behavior (cf. 'Additional context'). I think, the following lines in pytorchs setup.py are responsible:
```
if IS_WINDOWS:
    cmake_python_library = "{}/libs/python{}.lib".format(
        distutils.sysconfig.get_config_var("prefix"),
        distutils.sysconfig.get_config_var("VERSION")) 
```
For this, check again the provided links. There is simply no python37.lib to expect in the virtual environments 'libs/' sub-directory

**Comment by peterjc123** [comment]
Is there some method we can use to get the path of the base environment?

**Comment by peterjc123** [comment]
Well, by reading the code at https://github.com/python/cpython/blob/56698d57691af2272f695f8c17c835ed99545cde/Lib/distutils/sysconfig.py, looks like we can use `sys.base_prefix` to get that value.
