### ISSUE TITLE
How can I install it on Windows?

### ISSUE THREAD

**Issue by BroadDong** [pytorch/pytorch#2908]
Could I install it on Windows? Please tell the method. Thanks very much.

**Comment by soumith** [comment]
yes. see https://github.com/pytorch/pytorch/issues/494

**Comment by BroadDong** [comment]
@soumith  Which is the latest version？I think the method should be  clarified.

**Comment by soumith** [comment]
https://github.com/pytorch/pytorch/issues/494#issuecomment-322096506
