### ISSUE TITLE
a trivial question in torch.nn.init._calculate_fan_in_and_fan_out

### ISSUE THREAD

**Issue by seanywang0408** [pytorch/pytorch#29089]
## 📚 Documentation

In the below source code in the documentation, 
```
def _calculate_fan_in_and_fan_out(tensor):
    dimensions = tensor.dim()
    if dimensions < 2:
        raise ValueError("Fan in and fan out can not be computed for tensor with fewer than 2 dimensions")

    if dimensions == 2:  # Linear
        fan_in = tensor.size(1)
        fan_out = tensor.size(0)
    else:
        num_input_fmaps = tensor.size(1)
        num_output_fmaps = tensor.size(0)
        receptive_field_size = 1
        if tensor.dim() > 2:
            receptive_field_size = tensor[0][0].numel()
        fan_in = num_input_fmaps * receptive_field_size
        fan_out = num_output_fmaps * receptive_field_size

    return fan_in, fan_out
```
I thought the condition ``` if tensor.dim()>2``` is of no use and the ```receptive_field_size``` could be set to tensor[0][0].numel() directly. Is there any magical effect of it which I did not noticed?

**Comment by vishwakftw** [comment]
Yes, I think you are right, since the else block is active if `dimensions == 2`.

**Comment by VitalyFedyunin** [comment]
Nice catch! Feel free to submit PR fixing this issue.

**Comment by rodrigoberriel** [comment]
@vishwakftw this one is probably no longer valid and can be closed, as https://github.com/pytorch/pytorch/pull/29370 was merged a while ago

**Comment by thomasjpfan** [comment]
Closing because https://github.com/pytorch/pytorch/pull/29370 resolved this and was merged.
