### ISSUE TITLE
initializedContextIds_ field in DistEngine grows without bound

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#29083]
## 🐛 Bug

`initializedContextIds_` field in DistEngine grows without bound

## Expected behavior

We should cleanup entries for this map as autograd context ids are cleaned up. Or we should have a field in `DistAutogradContext` instead.

## Additional context

https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/autograd/engine/dist_engine.h#L86

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pietern** [comment]
@pritamdamania87 The "high priority" label means it goes to triage review (i.e. is the right person working on this issue right now). I doubt that was your intention here.

@ezyang Is there a better label for per-(module|topic|queue) prioritization?

**Comment by ezyang** [comment]
There's a few options I guess.
1. We can update the bot to only add triage review for issues labeled high priority that aren't already tagged with some other domain
2. We can keep the current behavior and adjust the core/frontend triage review to only consider issues labeled with triage review without a domain label
3. We can make another label per domain for their high priority stuff

TBH (2) seems the easiest.

**Comment by pietern** [comment]
Thanks, @ezyang. I agree, (2) is easiest and doesn't require everyone using a new label.

**Comment by VitalyFedyunin** [comment]
I think we forget to remove it from triage queue
