### ISSUE TITLE
[BUG] error for source code of submodule "android/libs/fbjni"

### ISSUE THREAD

**Issue by ygwangthu** [pytorch/pytorch#29109]
there is a commit error for the submodule fbjni, please check!
I guess that somebody might forget to (or wrongly) set the commit: e109650ca03e3db54ab973c14d10f176b6436c48

The error information is

git.exe submodule update --init
error: Server does not allow request for unadvertised object e109650ca03e3db54ab973c14d10f176b6436c48
Fetched in submodule path 'android/libs/fbjni', but it did not contain e109650ca03e3db54ab973c14d10f176b6436c48.

**Comment by soumith** [comment]
`git submodule sync` will fix it for you i think

**Comment by ygwangthu** [comment]
thanks!
