### ISSUE TITLE
There may be a bug on BoolTensor of PyTorch 1.3

### ISSUE THREAD

**Issue by shuaihuaiyi** [pytorch/pytorch#29106]
## 🐛 Bug

`BoolTensor.eq(1)` seems to be not working properly.

## To Reproduce

![TIM截图20191104130514](https://user-images.githubusercontent.com/14048129/68100619-e8f70b80-ff03-11e9-96bf-083b609cae55.png)

Change the script to `a[:,0].contiguous().eq(1)` can temporarily solve this problem.

## Expected behavior

The result should be all True, or at least the same for different runs.

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.10.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080

Nvidia driver version: 418.39
cuDNN version: /usr/local/cuda-10.1/lib64/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchtext==0.3.1
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

**Comment by obilaniu** [comment]
This resembles a manifestation of #28747 , yes a critical bug but solved in master and PyTorch 1.3.1 is due out soon.

**Comment by VitalyFedyunin** [comment]
Please retest with nightly build. As it seems to be fixed in 1.3.1 and nightly.

**Comment by VitalyFedyunin** [comment]
I will close it for now, feel free to reopen if you still facing this issue.
