### ISSUE TITLE
TestCuda.test_copy_non_blocking is flaky on ROCm

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#29119]
```
21:14:00 ======================================================================
21:14:00 FAIL: test_copy_non_blocking (__main__.TestCuda)
21:14:00 ----------------------------------------------------------------------
21:14:00 Traceback (most recent call last):
21:14:00   File "/var/lib/jenkins/workspace/test/common_utils.py", line 562, in wrapper
21:14:00     method(*args, **kwargs)
21:14:00   File "test_cuda.py", line 459, in test_copy_non_blocking
21:14:00     _test_copy_non_blocking(x, y)
21:14:00   File "test_cuda.py", line 448, in _test_copy_non_blocking
21:14:00     self.assertFalse(event.query())
21:14:00 AssertionError: True is not false
21:14:00 
21:14:00 ----------------------------------------------------------------------
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/4722/console

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by gottbrath** [comment]
@serhaty @bddppq  -- can either of you look at this?

**Comment by gottbrath** [comment]
created FBA-142

https://ontrack.amd.com/browse/FBA-142

**Comment by ramcherukuri** [comment]
Hi When you say this is flaky can you please explain like does it happen ones in ten tries. Is this issue specific to only on ubuntu or can be reproduced on another distro like CentOS? Can you run CUDA tests itself and help me without put.

export HIP_PRINT_ENV=1
export HIP_DB=0xff
/usr/bin/python3.6 test/run_test.py --verbose --bring-to-front cuda 2>&1 | tee hip_debug.log

**Comment by ezyang** [comment]
It means that the test intermittently fails on our CI. We're not sure about the failure rate; @kostmo could get you setup with this information. It looks like there's only one report of the problem on the Ubuntu configuration, so try reproducing in that environment.

I have not reproduced this locally yet. Is it acceptable to run the commands you gave on every CI? If so, we can instrument the CI with it so that we can catch the next occurrence.

**Comment by ramcherukuri** [comment]
>> Is it acceptable to run the commands you gave on every CI?
I believe so, but please mind that the log file generated will be a few 100's of MB.

I am also not able to reproduce the issue locally.

**Comment by ezyang** [comment]
OK, in that case, maybe let's put this issue on pause until we get more reproductions.

**Comment by jeffdaily** [comment]
Related JIRA was closed.  Unable to reproduce.
