### ISSUE TITLE
PyTorch+Windows: is parallelization over multiple GPUs now possible?

### ISSUE THREAD

**Issue by daidedou** [pytorch/pytorch#29130]
Hi,

I am planning to add a new GPU on my computer. Using Pytorch on Windows, I wonder if it will be possible for me to use parallelism.

In 2017 it wasn't possible: https://github.com/pytorch/pytorch/issues/4391
Has it changed? Will I have to switch to Linux? And is there a guide of how to install Pytorch for DataParallelism?

**Comment by rohan-varma** [comment]
Hi, please use the pytorch forums for questions (https://discuss.pytorch.org/). Thanks!
