### ISSUE TITLE
RpcTestWithFork.test_stress_light_rpc is flaky

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29150]
Nov 04 20:51:32 test_stress_heavy_rpc (__main__.RpcTestWithFork) ... Rank 0 finished testing heavy_rpc 20 times in 1.3649165630340576 seconds.
Nov 04 20:51:32 Rank 2 finished testing heavy_rpc 20 times in 1.364267349243164 seconds.
Nov 04 20:51:32 Rank 1 finished testing heavy_rpc 20 times in 1.367553949356079 seconds.
Nov 04 20:51:32 Rank 3 finished testing heavy_rpc 20 times in 1.3732781410217285 seconds.
Nov 04 20:51:32 ok
Nov 04 20:51:33 test_stress_light_rpc (__main__.RpcTestWithFork) ... terminate called after throwing an instance of 'c10::Error'
Nov 04 20:51:33 terminate called recursively
Nov 04 20:56:33 ERROR
Nov 04 20:56:34 test_sync_rpc (__main__.RpcTestWithFork) ... ok
Nov 04 20:56:34 test_worker_id (__main__.RpcTestWithFork) ... ok
Nov 04 20:56:34 
Nov 04 20:56:34 ======================================================================
Nov 04 20:56:34 ERROR: test_stress_light_rpc (__main__.RpcTestWithFork)
Nov 04 20:56:34 ----------------------------------------------------------------------
Nov 04 20:56:34 Traceback (most recent call last):
Nov 04 20:56:34   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 130, in wrapper
Nov 04 20:56:34     self._join_processes(fn)
Nov 04 20:56:34   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 211, in _join_processes
Nov 04 20:56:34     self._check_return_codes(elapsed_time)
Nov 04 20:56:34   File "/var/lib/jenkins/workspace/test/common_distributed.py", line 230, in _check_return_codes
Nov 04 20:56:34     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Nov 04 20:56:34 RuntimeError: Process 0 terminated or timed out after 300.01643323898315 seconds
Nov 04 20:56:34 
Nov 04 20:56:34 ----------------------------------------------------------------------
Nov 04 20:56:34 Ran 51 tests in 323.278s
Nov 04 20:56:34 
Nov 04 20:56:34 FAILED (errors=1, skipped=1)
Nov 04 20:56:34 Traceback (most recent call last):
Nov 04 20:56:34   File "test/run_test.py", line 454, in <module>
Nov 04 20:56:34     main()
Nov 04 20:56:34   File "test/run_test.py", line 446, in main
Nov 04 20:56:34     raise RuntimeError(message)
Nov 04 20:56:34 RuntimeError: test_rpc_fork failed!
Nov 04 20:56:34 + cleanup
Nov 04 20:56:34 + retcode=1
Nov 04 20:56:34 + set +x

See https://circleci.com/gh/pytorch/pytorch/3456673?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console.

This is happening on ASAN, has at least one more flaky RPC issue: #29117.

@mrshenli do you have an idea of who should take a look at this issue?

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mrshenli** [comment]
closed by #29827
