### ISSUE TITLE
Windows CI build is flaky: cannot delete workspace... because it is being used by another process

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29151]
21:32:11 Started by upstream project "pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-trigger" build number 85221
21:32:11 originally caused by:
21:32:11  Started by upstream project "pytorch-master" build number 12502
21:32:11  originally caused by:
21:32:11   Started by GitHub push by facebook-github-bot
21:32:11 [EnvInject] - Loading node environment variables.
21:32:11 Building remotely on worker-win-c5.2xlarge-i-0529c2cf555aab7e0-7ad9f7f9 (swarm cpu windows ami-0db182e2449b40aa0) in workspace C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build
21:32:11 [WS-CLEANUP] Deleting project workspace...
21:32:17 ERROR: [WS-CLEANUP] Cannot delete workspace: C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build -> C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build_ws-cleanup_1572903137175: The process cannot access the file because it is being used by another process.
21:32:17 
21:32:17 ERROR: Cannot delete workspace: C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build -> C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build_ws-cleanup_1572903137175: The process cannot access the file because it is being used by another process.
21:32:17 
21:32:17 Sending email to pietern@fb.com willfeng@fb.com englund@fb.com.
21:32:18 Email sent.
21:32:18 [BFA] Scanning build for known causes...
21:32:18 [BFA] No failure causes found
21:32:18 [BFA] Done. 0s
21:32:18 Finished: FAILURE

See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/84905//console. 

@ezyang 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by ezyang** [comment]
The plan on record is @mingbowan will move these CI jobs to CircleCI and then we kill the Jenkins job.

**Comment by mruberry** [comment]
Another instance (fyi):

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/85501//console

**Comment by mingbowan** [comment]
moved Windows build to CirlceCI, https://github.com/pytorch/pytorch/pull/28677 and https://github.com/pytorch/pytorch/pull/30897
