### ISSUE TITLE
uncoalesced add(dense, sparse) missing sparse values for torch.int16 on cuda

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#29153]
## 🐛 Bug

When adding (or calling to_dense()) on uncoalesced sparse tensors of dtype int16, values seem to be lost.

## To Reproduce
```
In [23]: sparse=torch.sparse_coo_tensor(indices=torch.tensor([[0,0],[1,1]]), values=torch.tensor([5, 6], dtype=torch.int16), size=(2,2), device='cuda', dtype=torch.int16 )

In [24]: sparse
Out[24]:
tensor(indices=tensor([[0, 0],
                       [1, 1]]),
       values=tensor([5, 6]),
       device='cuda:0', size=(2, 2), nnz=2, dtype=torch.int16,
       layout=torch.sparse_coo)

In [25]: sparse.coalesce()
Out[25]:
tensor(indices=tensor([[0],
                       [1]]),
       values=tensor([11]),
       device='cuda:0', size=(2, 2), nnz=1, dtype=torch.int16,
       layout=torch.sparse_coo)

In [26]: sparse.to_dense()
Out[26]:
tensor([[0, 0],
        [0, 0]], device='cuda:0', dtype=torch.int16)

In [27]: sparse.coalesce().to_dense()
Out[27]:
tensor([[ 0, 11],
        [ 0,  0]], device='cuda:0', dtype=torch.int16)

In [30]: torch.add(torch.zeros([2,2],dtype=torch.int16, device='cuda'), sparse)
Out[30]:
tensor([[0, 0],
        [0, 0]], device='cuda:0', dtype=torch.int16)
```

Wasn't able to repro on CPU or with any other dtype.

## Expected behavior

in above code, expecting  `tensor([[ 0, 11],  [ 0,  0]], device='cuda:0', dtype=torch.int16)`. 
`sparse.coalesce().to_dense()` should equal `sparse.to_dense()` or raise an error. I believe to_dense is impacted because it's calling add.

## Environment

from master on devgpu

cc @ezyang @gchanan @zou3519 @jerryzh168 @ngimel @vincentqb

**Comment by nairbv** [comment]
I'm not familiar with atomicCAS but it seems this is caused by an issue in THCATomics.cuh (in the implementation of struct AtomicAddIntegerImpl<T, 2> ). 

Changing this gives correct results for the above test:
```
static inline  __device__ void atomicAdd(int16_t *address, int16_t val) {
  *address = (*address + val);
  //AtomicAddIntegerImpl<int16_t, sizeof(int16_t)>()(address, val);
}
```
though that's probably not the correct fix.

**Comment by gchanan** [comment]
does this reproduce on other dtypes?

**Comment by nairbv** [comment]
> does this reproduce on other dtypes?

not that I could find, but adding tests for all dtypes:
https://github.com/pytorch/pytorch/pull/29231

**Comment by nairbv** [comment]
> > does this reproduce on other dtypes?
> 
> not that I could find, but adding tests for all dtypes:
> #29231

uint8 was also affected. there were a couple of issues with the existing code.
