### ISSUE TITLE
Gradle build is flaky: "could not get resource"

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29159]
Nov 04 22:22:52 Welcome to Gradle 4.10.3!
Nov 04 22:22:52 
Nov 04 22:22:52 Here are the highlights of this release:
Nov 04 22:22:52  - Incremental Java compilation by default
Nov 04 22:22:52  - Periodic Gradle caches cleanup
Nov 04 22:22:52  - Gradle Kotlin DSL 1.0-RC6
Nov 04 22:22:52  - Nested included builds
Nov 04 22:22:52  - SNAPSHOT plugin versions in the `plugins {}` block
Nov 04 22:22:52 
Nov 04 22:22:52 For more details see https://docs.gradle.org/4.10.3/release-notes.html
Nov 04 22:22:52 
Nov 04 22:22:52 Starting a Gradle Daemon (subsequent builds will be faster)
Nov 04 22:23:22 
Nov 04 22:23:22 FAILURE: Build failed with an exception.
Nov 04 22:23:22 
Nov 04 22:23:22 * What went wrong:
Nov 04 22:23:22 A problem occurred configuring project ':app'.
Nov 04 22:23:22 > Could not resolve all artifacts for configuration ':app:classpath'.
Nov 04 22:23:22    > Could not download builder.jar (com.android.tools.build:builder:3.3.2)
Nov 04 22:23:22       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar'.
Nov 04 22:23:22          > Connection reset
Nov 04 22:23:22 
Nov 04 22:23:22 * Try:
Nov 04 22:23:22 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Nov 04 22:23:22 
Nov 04 22:23:22 * Get more help at https://help.gradle.org
Nov 04 22:23:22 

https://circleci.com/gh/pytorch/pytorch/3460858?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

@dreiss, maybe we need to add a retry for this download, or host a more reliable mirror? 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
See also https://circleci.com/gh/pytorch/pytorch/3464073?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

**Comment by IvanKobzarev** [comment]
Working on it.
Current plan: fetch gradle dependencies in docker container 
https://github.com/pietern/pytorch-dockerfiles/pull/38

**Comment by mruberry** [comment]
fyi, a not uncommon occurence:

https://circleci.com/gh/pytorch/pytorch/3502079?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mruberry** [comment]
Now one of our most common failures:

https://app.circleci.com/jobs/github/pytorch/pytorch/3512429

Nov 07 18:19:10 FAILURE: Build failed with an exception.
Nov 07 18:19:10 
Nov 07 18:19:10 * What went wrong:
Nov 07 18:19:10 Could not resolve all files for configuration ':fbjni:lintClassPath'.
Nov 07 18:19:10 > Could not download lint.jar (com.android.tools.lint:lint:26.3.2)
Nov 07 18:19:10    > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/26.3.2/lint-26.3.2.jar'.
Nov 07 18:19:10       > Connection reset
Nov 07 18:19:10 > Could not download lint-checks.jar (com.android.tools.lint:lint-checks:26.3.2)
Nov 07 18:19:10    > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/26.3.2/lint-checks-26.3.2.jar'.
Nov 07 18:19:10       > Connection reset

**Comment by mruberry** [comment]
4 of the last 9 master builds failed to download these resources and failed.

**Comment by IvanKobzarev** [comment]
https://github.com/pytorch/pytorch/pull/29738 is landed which reenabled gradle builds on CI. So far works fine :) I will keep monitoring of it.
