### ISSUE TITLE
Conda gateway timeout in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29168]
Nov 05 01:09:12 ++ PATH=/opt/conda/bin:/opt/conda/envs/testenv/bin:/opt/conda/condabin:/opt/conda/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Nov 05 01:09:12 ++ export PATH
Nov 05 01:09:12 ++ /opt/conda/bin/conda install -y cpuonly -c pytorch
Nov 05 01:10:18 Collecting package metadata (current_repodata.json): ...working... failed
Nov 05 01:10:18 
Nov 05 01:10:18 CondaHTTPError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/pytorch/noarch/repodata.json>
Nov 05 01:10:18 Elapsed: 00:59.248626
Nov 05 01:10:18 CF-RAY: 530af10c4a2d3808-ATL
Nov 05 01:10:18 
Nov 05 01:10:18 A remote server error occurred when trying to retrieve this URL.
Nov 05 01:10:18 
Nov 05 01:10:18 A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
Nov 05 01:10:18 fulfill a valid request.  The problem may be spurious, and will resolve itself if you
Nov 05 01:10:18 try your request again.  If the problem persists, consider notifying the maintainer
Nov 05 01:10:18 of the remote server.
Nov 05 01:10:18 
Nov 05 01:10:18 
Exited with code 1

https://circleci.com/gh/pytorch/pytorch/3464019?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@ezyang 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by mruberry** [comment]
See also: https://circleci.com/gh/pytorch/pytorch/3482144?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by zou3519** [comment]
We can probably change the timeout or the retry settings for conda: https://docs.conda.io/projects/conda/en/latest/configuration.html

**Comment by mruberry** [comment]
Another instance:

https://circleci.com/gh/pytorch/pytorch/3505557?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mruberry** [comment]
Closing due to age.
