### ISSUE TITLE
InstanceNorm will be converted to syncBN

### ISSUE THREAD

**Issue by vchzls** [pytorch/pytorch#29187]
## To Reproduce

When I convert BN to syncBN, the InstanceNorm will become to syncBN

```
if isinstance(module, torch.nn.modules.batchnorm._BatchNorm):
```
should be
```
if isinstance(module, torch.nn.modules.batchnorm._BatchNorm) and not isinstance(module, torch.nn.modules.instancenorm._InstanceNorm):
```

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl_fft                   1.0.12           py37ha843d7b_0    defaults
[conda] mkl_random                1.0.2            py37hd81dba3_0    defaults
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.4.1                py37_cu101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by vadimkantorov** [comment]
probably there also exists a same problem with GroupNorm and maybe LayerNorm

**Comment by yf225** [comment]
@vadimkantorov Curious why would GroupNorm and LayerNorm have the same problem? They don't seem to subclass from _BatchNorm.

**Comment by yf225** [comment]
To reproduce the original issue:
```python
>>> module = torch.nn.Sequential(
...            torch.nn.BatchNorm1d(100),
...            torch.nn.InstanceNorm1d(100),
...          ).cuda()
>>> 
>>> sync_bn_module = torch.nn.SyncBatchNorm.convert_sync_batchnorm(module)
>>> print(sync_bn_module)
Sequential(
  (0): SyncBatchNorm(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (1): SyncBatchNorm(100, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
)
```
The `InstanceNorm1d` module is being converted to `SyncBatchNorm`, which seems wrong.

**Comment by vadimkantorov** [comment]
@yf225 Sorry, I mixed it up with C++ code where at some point LayerNorm called the batch_norm functions...
