### ISSUE TITLE
test_py_rref_args_user_share rpc test is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#29212]
## 🐛 Bug

The test_py_rref_args_user_share test in `rpc_test.py` is flaky. See failure here: https://app.circleci.com/jobs/github/pytorch/pytorch/3463855. This is again part of the RPC test timeouts issue we've been seeing an increase in lately.

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by mrshenli** [comment]
closed by #29069
