### ISSUE TITLE
Cannot export onnx graph with bilinear upsampling corner align True

### ISSUE THREAD

**Issue by LLNLanLeN** [pytorch/pytorch#29229]
## 🐛 Bug

I'm trying to export a small models that only contains a single operation which is bilinear upsampling with corner_Aligned = True. But I'm getting the following error:

`RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d`

## To Reproduce

This is the snippet of my code:

```
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

class Net(nn.Module):
    def __init__(self, operation, scale_factor = 1):
        super(Net, self).__init__()
        self.scale_factor = scale_factor

    def forward(self, x):
        x = F.interpolate(x, scale_factor=2, mode="bilinear", align_corners = True)

        return x

def main():
    operation = "bilinear_upsampling"
    scale_factor = 2
    test_case = "1"

    # check if Cuda is available
    cuda_available = torch.cuda.is_available()
    device = torch.device("cuda" if cuda_available else "cpu")

    # load model to GPU
    model = Net(operation = operation,
                scale_factor = scale_factor).to(device)

    # dummy prediction
    dummyInput = Variable(torch.rand(1, 4, 8, 8))

    # change model to eval mode
    model.eval()

    # model prediction. Need to zero out any gradient because it is not needed when doing prediction
    with torch.no_grad():
        dummyOutput = model(dummyInput)

    torch.onnx.export(model,
                      dummyInput,
                      '/Users/phiar/Desktop/test_onnx_' + operation + '_' + test_case + '.onnx',
                      verbose = True,
                      input_names = ['test_onnx_' + operation + '_' + test_case + '_input'],
                      output_names = ['test_onnx_' + operation + '_' + test_case + '_output'])

if __name__ == "__main__":
    main()
```

Simply run the code above (Make sure to change `/Users/lanle/Desktop` to your local DIR)

## Environment

 - PyTorch Version : 1.4.0.dev20191103 (pytorch-nightly)
 - OS: MacOS
 - How you installed PyTorch (`conda`, `pip`, source): I use the instruction on `pytorch.org` for MacOS CPU: `conda install pytorch torchvision -c pytorch-nightly`
 - Python version: 3.7.5
 - CUDA/cuDNN version: N/A since I'm only using pytorch CPU
 - Torchvision version: 0.5.0.dev20191104 (pytorch-nightly)

## Note:
I'm able to export the model if I set `aligned_corner` to `False`

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by lara-hdr** [comment]
You are exporting the model to opset 9 (default), for which align_corner=True is not supported. align_corner support was added in opset 11; you can export the model to opset 11 by specifying it in the export api ( torch.onnx.export(..., opset_version=11)).

**Comment by LLNLanLeN** [comment]
@lara-hdr OMG, thank you so much, I got it to export now. I couldn't find this argument in the pytorch documentation so I was struggling to understand why I couldn't export, even though in onnx github repo, they said it has been fixed. Thank you

**Comment by glenn-jocher** [comment]
@lara-hdr @LLNLanLeN this solution is incomplete I believe, because the provided answer will export from pytorch, but will fail to pass the ONNX checker. See https://github.com/pytorch/pytorch/issues/30681

Error message:
```bash
torch version 1.4.0.dev20191127
onnx version 1.5.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/iD/upsample_error_reproduce.py", line 28, in <module>
    onnx.checker.check_model(oml)
  File "/Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Resize_23) has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "input" input: "20" input: "20" input: "23" output: "24" name: "Resize_23" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }
```

## To Reproduce

```python
# conda install pytorch torchvision -c pytorch-nightly
# conda install -c conda-forge onnx
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # fails
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # fails
        x = F.interpolate(x, scale_factor=2)  # fails
        return x


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
onnx.checker.check_model(oml)
```

**Comment by Owen-Liuyuxuan** [comment]
> You are exporting the model to opset 9 (default), for which align_corner=True is not supported. align_corner support was added in opset 11; you can export the model to opset 11 by specifying it in the export api ( torch.onnx.export(..., opset_version=11)).

Thank you for your answer. This is year 2023. I still need to explicitly set the opset_version argument in torch.onnx.export to get bilinear upsample exported.
