### ISSUE TITLE
Torch from sourc and Torchvision from pip

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#29241]
I have been confused with `torch` and `torchvision`.
Although I have installed PyTorch 1.4 from source using `python setup.py install --user`, when I run a code which uses `torchvision` as below

```
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.optim as optim
import torch.utils.data
import torchvision.datasets as dset
import torchvision.transforms as transforms
import torchvision.utils as vutils
```
I get the following error

```
ImportError: No module named torchvision.datasets
```

So, I decide to install vision using `pip install --user torchvision`. Now, I see that `torch 1.3` is installed along with `torchvision`.

How can I have torchvision and torch 1.4 then?

**Comment by soumith** [comment]
`pip install --user --no-dependencies torchvision`
