### ISSUE TITLE
Bug with Advanced Indexing on GPU variables

### ISSUE THREAD

**Issue by adambielski** [pytorch/pytorch#2925]
Simple example: Let's try advanced indexing with object convertible to LongTensor on CPU

```python
import torch
from torch.autograd import Variable
import numpy as np

print(torch.__version__) #0.2.0_3

x = torch.randn(5, 4, 3)
indices = np.array([[0],[1],[2]], dtype=np.int64)
print(x[indices]) # working perfectly 
#-0.2339
#[torch.FloatTensor of size 1]
```

The same on GPU Variable:

```python
xx = x.cuda()
print(xx[indices])
# IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors

xx = x.cuda()
print(xx[torch.LongTensor(indices)])
# TypeError: indexing a tensor with an object of type torch.LongTensor. The only supported types are integers, slices, numpy scalars and torch.cuda.LongTensor or torch.cuda.ByteTensor as the only argument.
```

OK, it should work with cuda.LongTensor, let's convert:

```python
indices_tensor_cuda = torch.LongTensor(indices).cuda()
print(xx[indices_tensor_cuda])
# RuntimeError: invalid argument 3: expecting vector of indices at /pytorch/torch/lib/THC/generic/THCTensorIndex.cu:405
```

I found a workaround that works
```python
print(xx[indices.tolist()])
```

But it's inconsistent with behavior on CPU Variables and counter-intuitive to the provided messages.

**Comment by killeent** [comment]
So a couple of things - on PyTorch master (version `0.2.0+6216031`), indexing `xx` with `indices` succeeds.

The other thing is that when you convert the Tensor to the `cuda.LongTensor` you are triggering a different type of indexing (`index_select`) which leads to the failure case you see, because you are passing a `3x1` matrix to `index_select` instead of a vector.

**Comment by adambielski** [comment]
@killeent Thanks for the answer, it explains a lot. Good to know it's fixed for GPU in the master version.
And you are right, the problem with converting to LongTensor is not related to GPU. The problem is then with the error message (unless it's fixed in master, can't check now), saying that "IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors" - apparently, the indexing objects **cannot** be a LongTensor.

**Comment by killeent** [comment]
@adambielski The error message is reasonable - it talks about expecting a vector:

```
Index is supposed to be a vector
```

**Comment by soumith** [comment]
error message improved in https://github.com/pytorch/pytorch/pull/2974
