### ISSUE TITLE
dataloader issue python3.6

### ISSUE THREAD

**Issue by ntuyt** [pytorch/pytorch#2926]
RuntimeError: Traceback (most recent call last):
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 109, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 89, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/storage.py", line 113, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to write to file </torch_476_615100490> at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/THAllocator.c:27

**Comment by apaszke** [comment]
You probably run out of shared memory.

**Comment by cxxgtxy** [comment]
I meet with the same problem. And it's not caused by memory

**Comment by oneTaken** [comment]
I meet with the same problem, and I change the `num_wrokers` from `num_wrokers=15` to `num_wrokers=0`. It helps on my situation.

**Comment by JiamingSuen** [comment]
I met the same problem with pytorch docker image provided by NVIDIA, by setting `--ipc=host` in the container starting script the problem is solved.

**Comment by aannhh** [comment]
Reduce the number of multiprocessing processes solved this for me. 
Using 16 workers for loading data in my 16 cores machine caused this error. I just reduced number of workers to 10 then the problem is gone.

**Comment by 666xiaohei666** [comment]
add these in front of my code solve my ploblem hope can help you.
'''
import sys
import torch
from torch.utils.data import dataloader
from torch.multiprocessing import reductions
from multiprocessing.reduction import ForkingPickler

default_collate_func = dataloader.default_collate


def default_collate_override(batch):
  dataloader._use_shared_memory = False
  return default_collate_func(batch)

setattr(dataloader, 'default_collate', default_collate_override)

for t in torch._storage_classes:
  if sys.version_info[0] == 2:
    if t in ForkingPickler.dispatch:
        del ForkingPickler.dispatch[t]
  else:
    if t in ForkingPickler._extra_reducers:
        del ForkingPickler._extra_reducers[t]
'''

**Comment by huckl3b3rry87** [comment]
@JiamingSuen 's solution worked for me as well with Docker

**Comment by brando90** [comment]
> Reduce the number of multiprocessing processes solved this for me.
> Using 16 workers for loading data in my 16 cores machine caused this error. I just reduced number of workers to 10 then the problem is gone.

why does reducing the number of workers solve this issue?
