### ISSUE TITLE
[ONNX] Cannot export BatchNorm1d

### ISSUE THREAD

**Issue by yingjianling** [pytorch/pytorch#29271]
## 🐛 Bug

We cannot export a module which contains a BatchNorm1d layer with 2D input.
```
Traceback (most recent call last):
  File "export_model.py", line 96, in <module>
    main(args)
  File "export_model.py", line 59, in main
    opset_version=9)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 619, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 124, in wrapper
    return fn(g, *args)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 869, in batch_norm
    'torch.' + input.type().scalarType() + 'Tensor')
TypeError: can only concatenate str (not "NoneType") to str (occurred when translating batch_norm)
```
## To Reproduce

1.Run the following script:
```
import torch
class test_module(torch.nn.Module):
    def __init__(self):
        super(test_module, self).__init__()
        self.bn = torch.nn.BatchNorm1d(256, affine=False)
    def forward(self, x):
        B,N,D = x.shape
        x = x.view(-1, D)
        x = self.bn(x)
        x = x.view(B,N,D)
        return x
        
dummy_x= torch.randn(8,40,256)
net = test_module()
torch.onnx.export(net, (dummy_x), 
                "tmp.onnx", 
                input_names=['input'], 
                output_names=['preds'],
                verbose=True,
                opset_version=9)
```

## Expected behavior
no error reported

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 430.14
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by AlirezaAlizadeh** [comment]
We encountered the same problem as well. The export works when we set the `affine=True`.

**Comment by neginraoof** [comment]
Thanks.
This is a bug in batch_norm export.
I'm going to look into it.

**Comment by neginraoof** [comment]
Fix PR: https://github.com/pytorch/pytorch/pull/29458

**Comment by PistonY** [comment]
@neginraoof Does this fix in Pytorch 1.3?

**Comment by spandantiwari** [comment]
@PistonY - no, the fix is in master only. You can get it by installing the PyTorch nightly build.

**Comment by dingkwang** [comment]
It is batchnorm1d or batchnorm2d? batchnorm1d Still don't support yet.
