### ISSUE TITLE
"no mudule named torch". But intalled pytorch 1.3.0 with conda in Ubuntu 18.04.02 Server Edition

### ISSUE THREAD

**Issue by marcoippolito** [pytorch/pytorch#29283]
Hi all,
installed pytorch with conda :

    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch/examples$ conda install  
    pytorch torchvision cpuonly -c pytorch
    Collecting package metadata (current_repodata.json): done
    Solving environment: done

    # All requested packages already installed.

I updated conda:

    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch/examples$ conda update 
    conda
    Collecting package metadata (current_repodata.json): done
    Solving environment: done

    # All requested packages already installed.

Installed mkl=2019 :   

    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch/examples$ conda install  
    mkl=2019
    Collecting package metadata (current_repodata.json): done
    Solving environment: done

    # All requested packages already installed.

    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch/examples$ conda list | grep 
    torch
    cpuonly                   1.0                           0    pytorch
    facenet-pytorch           0.1.0                    pypi_0    pypi
    pytorch                   1.3.0               py3.7_cpu_0  [cpuonly]  pytorch
    torchfile                 0.1.0                    pypi_0    pypi
    torchvision               0.4.1                  py37_cpu  [cpuonly]  pytorch

But it still says "no module torch" :  

    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch/examples$ python3
    Python 3.8.0 (default, Oct 30 2019, 16:20:23) 
    [GCC 7.4.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'torch'
    >>> 

Ubuntu 18.04.02 Server Edition

How to solve the problem?
Marco

**Comment by peterjc123** [comment]
You have two python environments: 
1. Conda with Python 3.7 (Inferred from code snippet 3)
2. Virtualenv with Python 3.8 (Inferred from code snippet 4)
As you can see from code snippet 1, torch is successfully installed into the first python environment. But from code snippet 4, it implies that torch is not installed in the second python environment. So the solution is to deactivate the second environment through `deactivate`, or to reactivate the first environment by calling `conda activate`.

**Comment by marcoippolito** [comment]
@peterjc123  I tried to re-activate conda environment : 

    (3.8.0/envs/my_virtual_env-3.8.0) (base) marco@pc:~/facenet_pytorch$ conda activate
    (base) (3.8.0/envs/my_virtual_env-3.8.0) marco@pc:~/facenet_pytorch$ python3
    Python 3.8.0 (default, Oct 30 2019, 16:20:23) 
    [GCC 7.4.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'torch'
    >>> 

I discovered that this problem "no module named 'torch' " appears only for python 3.8.0 version
If I remove in facenet_pytorch the pyenv specification, thus removing .python-version file , python 3.7.3 imports torch module :  

    (base) marco@pc:~/facenet_pytorch$ python3
    Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    >>>

**Comment by soumith** [comment]
pytorch doesn't provide a python 3.8 binary yet. that is planned for v1.4.0

**Comment by soumith** [comment]
please use python 3.7 or earlier.
