### ISSUE TITLE
Using tensor cores

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#29293]
I would like to know if I build PyTorch on SM_70 or SM_75, will it automatically use tensor cores or I have to explicitly specify something during the compilation or before run.
Any comment?

**Comment by mruberry** [comment]
You will automatically use them when performing operations that make use of tensor cores.

**Comment by mahmoodn** [comment]
Is there any special API in PyTorch for that? Where should I look for using those operations?

**Comment by mruberry** [comment]
There is not a special API and, unfortunately, the cases where tensor cores are enabled are not very easy to describe. NVIDIA has some performance guides for Tensor Cores that can be useful references: https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9926-tensor-core-performance-the-ultimate-guide.pdf

Essentially operations that internally perform GEMMs can use Tensor Cores on fp16 inputs when those inputs' sizes meet special criteria.

**Comment by mahmoodn** [comment]
Thanks.
