### ISSUE TITLE
Jenkins CI builds sometimes fail in CI with FATAL: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29295]
See https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-build/85398//console

17:38:52 Started by upstream project "pytorch-builds/pytorch-win-ws2016-cuda9-cudnn7-py3-trigger" build number 85714
17:38:52 originally caused by:
17:38:52  Started by upstream project "pytorch-master" build number 12581
17:38:52  originally caused by:
17:38:52   Started by GitHub push by facebook-github-bot
17:38:52 [EnvInject] - Loading node environment variables.
17:38:52 Building remotely on worker-win-c5.2xlarge-i-0ef54dcaadff19f7f-eeb596e6 (swarm cpu windows ami-0db182e2449b40aa0) in workspace C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build
17:38:52 [WS-CLEANUP] Deleting project workspace...
17:38:54 [WS-CLEANUP] Done
17:38:54 No credentials specified
17:38:54 Cloning the remote Git repository
17:38:54 Using shallow clone
17:38:54 shallow clone depth 70
17:38:54 Cloning repository https://github.com/pytorch/pytorch.git
17:38:54  > git init C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-build # timeout=10
17:38:54 Fetching upstream changes from https://github.com/pytorch/pytorch.git
17:38:54  > git --version # timeout=10
17:38:54  > git fetch --tags --force --progress https://github.com/pytorch/pytorch.git +refs/heads/*:refs/remotes/origin/* --depth=70
17:39:18  > git config remote.origin.url https://github.com/pytorch/pytorch.git # timeout=10
17:39:18  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
17:39:18  > git config remote.origin.url https://github.com/pytorch/pytorch.git # timeout=10
17:39:18 Fetching upstream changes from https://github.com/pytorch/pytorch.git
17:39:18  > git fetch --tags --force --progress https://github.com/pytorch/pytorch.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* --depth=70
17:46:48 FATAL: java.nio.channels.ClosedChannelException
17:46:48 java.nio.channels.ClosedChannelException
17:46:48 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 100.24.68.90/100.24.68.90:49220
17:46:48 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
17:46:48 		at hudson.remoting.Request.call(Request.java:202)
17:46:48 		at hudson.remoting.Channel.call(Channel.java:954)
17:46:48 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
17:46:48 		at sun.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
17:46:48 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:46:48 		at java.lang.reflect.Method.invoke(Method.java:498)
17:46:48 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
17:46:48 		at com.sun.proxy.$Proxy87.execute(Unknown Source)
17:46:48 		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:892)
17:46:48 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
17:46:48 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
17:46:48 		at hudson.scm.SCM.checkout(SCM.java:504)
17:46:48 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
17:46:48 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
17:46:48 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
17:46:48 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
17:46:48 		at hudson.model.Run.execute(Run.java:1810)
17:46:48 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:46:48 		at hudson.model.ResourceController.execute(ResourceController.java:97)
17:46:48 		at hudson.model.Executor.run(Executor.java:429)
17:46:48 Caused: hudson.remoting.RequestAbortedException
17:46:48 	at hudson.remoting.Request.abort(Request.java:340)
17:46:48 	at hudson.remoting.Channel.terminate(Channel.java:1038)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
17:46:48 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
17:46:48 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
17:46:48 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
17:46:48 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
17:46:48 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
17:46:48 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
17:46:48 	at hudson.remoting.Channel.close(Channel.java:1450)
17:46:48 	at hudson.remoting.Channel.close(Channel.java:1403)
17:46:48 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:821)
17:46:48 	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
17:46:48 	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:737)
17:46:48 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
17:46:48 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
17:46:48 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17:46:48 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:46:48 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:46:48 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:46:48 	at java.lang.Thread.run(Thread.java:748)
17:46:48 Sending email to pietern@fb.com willfeng@fb.com englund@fb.com.

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by ezyang** [comment]
As far as I can tell this is Jenkins flakiness; the plan on record is when we move Windows to CircleCI this will go away.

**Comment by mruberry** [comment]
Yep; seems like Jenkins. Also happens on ROCm:  

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-build/7114//console

**Comment by mingbowan** [comment]
windows build/test moved to CircleCI: https://github.com/pytorch/pytorch/pull/28677 and https://github.com/pytorch/pytorch/pull/30897
