### ISSUE TITLE
CUDA Build failure of BinaryOpsKernel.cu caused by isnan()

### ISSUE THREAD

**Issue by dylanbespalko** [pytorch/pytorch#29291]
## 🐛 Bug

Building on CUDA appears to fail when building BinaryOpsKernel.cu.
There several nearby warnings that suggest isnan() is not supported on the device memory.

## To Reproduce

1. Clone pytorch and checkout master branch.
2. Build on machine with CUDA enabled.
2a. I am using the following build config:
```bash
DEBUG=0 USE_DISTRIBUTED=0 USE_MKLDNN=0 USE_CUDA=1 BUILD_TEST=0 USE_FBGEMM=0 USE_NNPACK=0 USE_QNNPACK=0 USE_NINJA=0 CUDA_DEVICE_DEBUG=0 BUILD_CAFFE2_OPS=0 USE_CUDNN=0 INTERN_DISABLE_AUTOGRAD=0 python setup.py develop
```
3. The following error should occur.

``` bash
[ 61%] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UnaryOpsKernel.cu.o
[ 61%] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Unique.cu.o
/home/deepwave/repos/pytorch/c10/util/BFloat16.h(48): warning: calling a __host__ function("__builtin_isnan") from a __host__ __device__ function("c10::detail::round_to_nearest_even") is not allowed

gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMake Error at torch_generated_BinaryOpsKernel.cu.o.Release.cmake:281 (message):
  Error generating file
  /home/deepwave/repos/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/./torch_generated_BinaryOpsKernel.cu.o

caffe2/CMakeFiles/torch.dir/build.make:763: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_BinaryOpsKernel.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_BinaryOpsKernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/deepwave/repos/pytorch/c10/util/BFloat16.h(48): warning: calling a __host__ function("__builtin_isnan") from a __host__ __device__ function("c10::detail::round_to_nearest_even") is not allowed
```

## Environment

Collecting environment information...
PyTorch version: N/A (from source)
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu/Linaro 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 9.0.252
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/aarch64-linux-gnu/libcudnn.so.7.1.5

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch-cpu-strided-complex==0.0.0
[pip] torch-cuda-strided-complex==0.0.0
[conda] torch-cpu-strided-complex 0.0.0                     <pip>
[conda] torch-cuda-strided-complex 0.0.0                     <pip>

**Comment by yf225** [comment]
IIUC the warnings shouldn't cause the internal compiler error - it is more likely because the compiler is out of memory. Could you try passing a number smaller than # of your CPU cores to `MAX_JOBS=` and use it as a flag when running `python setup.py develop`?

**Comment by dylanbespalko** [comment]
@yf225,

Reducing the `MAX_JOBS=` fixed my problem. Thanks.
