### ISSUE TITLE
cannot import name 'nn' from 'torch' (unknown location)

### ISSUE THREAD

**Issue by marcoippolito** [pytorch/pytorch#29305]
Ubuntu 18.04.02 Server Edition

    (base) marco@pc:~/pytorchDLHandsOn/2.ASimpleNeuralNetwork$ python3
    Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    >>> from torch import nn
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'nn' from 'torch' (unknown location)
    >>> 
    KeyboardInterrupt
    >>> 

This is what I have installed via conda:

    (base) marco@pc:~/pytorchDLHandsOn/2.ASimpleNeuralNetwork$ conda list | grep torch
    cpuonly                   1.0                           0    pytorch
    facenet-pytorch           0.1.0                    pypi_0    pypi
    torchfile                 0.1.0                    pypi_0    pypi

How to solve the problem?
Marco

**Comment by erip** [comment]
`import torch.nn as nn`

**Comment by soumith** [comment]
the conda list says that you don't have pytorch installed. install pytorch and try again

**Comment by marcoippolito** [comment]
@soumith Thank you. You are right!! May be during my trials I uninstalled the previous installation
I thought that cpuonly                   1.0                           0    pytorch mean "pytorch installed"

    conda install pytorch torchvision cpuonly -c pytorch
    Collecting package metadata (current_repodata.json): done
    Solving environment: done

    ## Package Plan ##

      environment location: /home/marco/anaconda3

      added / updated specs:
        - cpuonly
        - pytorch
        - torchvision

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        openssl-1.1.1d             |       h516909a_0         2.1 MB  conda-forge
        ------------------------------------------------------------
                                               Total:         2.1 MB

    The following NEW packages will be INSTALLED:

      pytorch            pytorch/linux-64::pytorch-1.3.0-py3.7_cpu_0
      torchvision        pytorch/linux-64::torchvision-0.4.1-py37_cpu

    The following packages will be UPDATED:

      openssl                                 1.1.1c-h516909a_0 --> 1.1.1d-h516909a_0

    Proceed ([y]/n)? y

    Downloading and Extracting Packages
    openssl-1.1.1d       | 2.1 MB    |    
    ########################################################################    
    ########################################################################    
    ##### | 100% 
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done

    (base) marco@pc:~/pytorchDLHandsOn/2.ASimpleNeuralNetwork$ conda list | grep torch
    cpuonly                   1.0                           0    pytorch
    facenet-pytorch           0.1.0                    pypi_0    pypi
    pytorch                   1.3.0               py3.7_cpu_0  [cpuonly]  pytorch  // <--------------
    torchfile                 0.1.0                    pypi_0    pypi
    torchvision               0.4.1                  py37_cpu  [cpuonly]  pytorch

    (base) marco@pc:~/pytorchDLHandsOn/2.ASimpleNeuralNetwork$ python3
    Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import torch
    >>> from torch import nn
    >>>

**Comment by Atul-770** [comment]
I have install the torch library with cuda and  I am still getting this error -> "ImportError: cannot import name 'nn' from 'torch.nn' (D:\Neural Network\llm\cuda\Lib\site-packages\torch\nn\__init__.py)" 
code is -> from torch.nn import nn
but i did not install torchvision is it import for nn to work
