### ISSUE TITLE
Quadro m2000 not able to get pytorch working with gpu 

### ISSUE THREAD

**Issue by abdoelsayed2016** [pytorch/pytorch#29301]
why PyTorch working in CPU not GPU?
code 
print(torch.device("cuda:0" if torch.cuda.is_available() else "cpu"))
output : cpu

System info 
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Quadro M2000
Nvidia driver version: 391.74
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] numpydoc==0.9.1
[pip] torch==1.3.0
[pip] torchvision==0.4.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.14           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] pytorch                   1.3.0           py3.7_cuda92_cudnn7_0    pytorch
[conda] torch                     1.3.1                    pypi_0    pypi
[conda] torchvision               0.4.1                 py37_cu92    pytorch

**Comment by mruberry** [comment]
This question is probably more appropriate to the PyTorch forums, and you could search there for an answer, too:  https://discuss.pytorch.org/.

As best I can tell your graphics card uses the Maxwell architecture (compute capability 5.0) and default PyTorch installs no longer support that compute capability. On the forum you'll see options for how to acquire or build a version of PyTorch that will work on Maxwell GPUs.

**Comment by yf225** [comment]
Closing because this question is more suitable for the PyTorch forum.

**Comment by soumith** [comment]
> As best I can tell your graphics card uses the Maxwell architecture (compute capability 5.0) and default PyTorch installs no longer support that compute capability.

This detail was wrong. PyTorch default installs and binaries do support 5.0.
