### ISSUE TITLE
TestQNNPackOps.test_avg_pool2d is flaky on MacOS CI test builds

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29326]
See https://circleci.com/gh/pytorch/pytorch/3493230?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link:

Nov 06 12:07:54 ======================================================================
Nov 06 12:07:54 ERROR: test_avg_pool2d (__main__.TestQNNPackOps)
Nov 06 12:07:54 ----------------------------------------------------------------------
Nov 06 12:07:54 Traceback (most recent call last):
Nov 06 12:07:54   File "test_quantized.py", line 1823, in test_avg_pool2d
Nov 06 12:07:54     channels=st.sampled_from([2, 4, 5, 8, 16, 32]),
Nov 06 12:07:54   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 994, in wrapped_test
Nov 06 12:07:54     raise the_error_hypothesis_found
Nov 06 12:07:54   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 953, in wrapped_test
Nov 06 12:07:54     state.run()
Nov 06 12:07:54   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 689, in run
Nov 06 12:07:54     info.__expected_traceback,
Nov 06 12:07:54   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 585, in execute
Nov 06 12:07:54     % (test.__name__, text_repr[0])
Nov 06 12:07:54   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/hypothesis/core.py", line 744, in __flaky
Nov 06 12:07:54     raise Flaky(message)
Nov 06 12:07:54 hypothesis.errors.Flaky: Hypothesis test_avg_pool2d(self=<__main__.TestQNNPackOps testMethod=test_avg_pool2d>, batch_size=1, channels=2, height=4, width=4, kernel=2, stride=1, padding=1, scale=0.2, zero_point=0) produces unreliable results: Falsified on the first call but did not on a subsequent one
Nov 06 12:07:54 
Nov 06 12:07:54 ----------------------------------------------------------------------
Nov 06 12:07:54 Ran 34 tests in 35.159s
Nov 06 12:07:54 
Nov 06 12:07:54 FAILED (errors=2, skipped=2)
Nov 06 12:07:54 Traceback (most recent call last):
Nov 06 12:07:54   File "test/run_test.py", line 454, in <module>
Nov 06 12:07:54     main()
Nov 06 12:07:54   File "test/run_test.py", line 446, in main
Nov 06 12:07:54     raise RuntimeError(message)
Nov 06 12:07:54 RuntimeError: test_quantized failed!
Nov 06 12:07:54 + cleanup
Nov 06 12:07:54 + retcode=1
Nov 06 12:07:54 + set +x
Exited with code 1

See also #27326 for another quantization failure on MacOS. 

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
I'll temporarily disable these tests on MacOS.

**Comment by jerryzh168** [comment]
@z-a-f could you take a look

**Comment by gottbrath** [comment]
In review in the quantization meeting we thought that Supriya might be the right person for this.

**Comment by z-a-f** [comment]
Cannot repro

**Comment by supriyar** [comment]
Closing as no repro
