### ISSUE TITLE
RuntimeError: Didn't find engine for operation quantized::conv_prepack NoQEngine

### ISSUE THREAD

**Issue by cygnus77** [pytorch/pytorch#29327]
## 🐛 Bug

Running [quantization tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html) on Windows 10 x64 errors out in **torch.quantization.convert** step with the following:
**RuntimeError: Didn't find engine for operation quantized::conv_prepack NoQEngine**

This issue is similar to [28945](https://github.com/pytorch/pytorch/issues/28945) but happens on Windows x64, on PyTorch installed via Conda.

## To Reproduce

1. Install PyTorch 1.3.0 from conda:
       conda install pytorch torchvision cpuonly -c pytorch

2.  Run code from [quantization tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html)

## Expected behavior
Tutorial should work

## Environment

 - PyTorch Version: 1.3.0
 - OS: Windows 10 Pro
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: None
 - GPU models and configuration: None

[info.txt](https://github.com/pytorch/pytorch/files/3816736/info.txt)

## Additional context
- Tutorial works fine on Mac, CentOS
- Model torch.jit.save'd on Mac/Linux does not load on Windows. torch.jit.load throws the same NoQEngine error.

cc @peterjc123 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by dzhulgakov** [comment]
cc @supriyar @dskhudia @jamesr66a 

There are two libraries we're currently using for quantized operations: fbgemm and qnnpack. Fbgemm today doesn't support window build: https://github.com/pytorch/FBGEMM/issues/150 . Would be nice if someone gave it a try.

For qnnpack - we disable it by default on non-mobile builds:
https://github.com/pytorch/pytorch/blob/0ae0c9788edf4ee31c3c48b906bb9a65b871bd03/aten/src/ATen/Context.cpp#L119-L121

Afaik, the performance is not that great for qnnpack on x86 cpus and there were some other stability issues. @supriyar - do you know if it's better to reenable it?

As a temp workaround - try setting `torch.backends.quantized.engine = 'qnnpack'` to see whether it works. It's not an official workaround - just something to try.

**Comment by Flipajs** [comment]
> cc @supriyar @dskhudia @jamesr66a 
> As a temp workaround - try setting `torch.backends.quantized.engine = 'qnnpack'` to see whether it works. It's not an official workaround - just something to try.

I had the same issue on raspberrypi 4. I've tried your temp workaround and it works. Thank you very much!

**Comment by peterjc123** [comment]
I tried to fix FBGEMM build on Windows with https://github.com/pytorch/FBGEMM/pull/238 and was blocked by the difficulty to rewrite the assembly code for Windows.

**Comment by peterjc123** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/33250.

**Comment by YuantianGao** [comment]
I have a similar problem, and this is my code error:

```
UserWarning: must run observer before calling calculate_qparams. Returning default scale and zero point
Returning default scale and zero point "
Traceback (most recent call last):
File “mobile_test.py”, line 122, in
data_loader,bn_list[0],net_config,device=‘cuda:0’))
File “mobile_test.py”, line 55, in prepare_subnet
torch.quantization.convert(subnet, inplace=True)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 473, in convert
convert_custom_config_dict=convert_custom_config_dict)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 508, in _convert
custom_module_class_mapping)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 508, in _convert
custom_module_class_mapping)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 508, in _convert
custom_module_class_mapping)
[Previous line repeated 3 more times]
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 509, in _convert
reassign[name] = swap_module(mod, mapping, custom_module_class_mapping)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/quantization/quantize.py”, line 534, in swap_module
new_mod = mapping[type(mod)].from_float(mod)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py”, line 97, in from_float
return super(ConvReLU2d, cls).from_float(mod)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 418, in from_float
return _ConvNd.from_float(cls, mod)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 220, in from_float
return cls.get_qconv(mod, activation_post_process, weight_post_process)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 191, in get_qconv
mod.bias is not None, mod.padding_mode)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py”, line 74, in init
padding_mode=padding_mode)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 376, in init
False, _pair(0), groups, bias, padding_mode)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 74, in _init
self.set_weight_bias(qweight, bias_float)
File “/home/yuantian/.local/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py”, line 384, in set_weight_bias
w, b, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Didn’t find engine for operation quantized::conv2d_prepack NoQEngine
```

I try to print the code

`torch.backends.quantized.supported_engines`
But the result is [None]
And my system is ubuntu

My code is below:
`#quantize model
subnet.qconfig = torch.quantization.get_default_qconfig('qnnpack')
torch.quantization.prepare(subnet, inplace=True)
# Calibrate
print(torch.backends.quantized.supported_engines)
torch.quantization.convert(subnet, inplace=True)
#optimize
script_subnet = torch.jit.script(model)
script_subnet_optimized = optimize_for_model(script_model)`

**Comment by maheshs11** [comment]
> > cc @supriyar @dskhudia @jamesr66a
> > As a temp workaround - try setting `torch.backends.quantized.engine = 'qnnpack'` to see whether it works. It's not an official workaround - just something to try.
> 
> I had the same issue on Raspberrypi 4. I tried your temp workaround and it works. Thank you very much!

not working for me !
can you share your code?

**Comment by pi-null-mezon** [comment]
Have faced same issue when try to load model on old machine without AVX  instructions set (AMD Phenom(tm) II N850, Ubuntu 18.04, libtorch 1.11.0). My question is, how to build libtorch.so with QNNPACK enabled? Or, maybe I can find binaries with enabled QNNPACK somwhere?

**Comment by jerryzh168** [comment]
qnnpack build is enabled by default I think: https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L264-L265 could you check the output of cmake file to see if this flag is enabled or not when you build?

**Comment by pi-null-mezon** [comment]
I can not check CMakeLists.txt, because I did not build my release, just downlodeded it from https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.11.0%2Bcpu.zip

**Comment by Dhiaeddine-Oussayed** [comment]
Anyone solved this issue ?

**Comment by pbanavara** [comment]
Folks, Facing the same issue on Mac M1. Environment details

Python 3.10.1
Pytorch 1.12.1

Exception trace below
`
(pytorch) pbanavara@MacBook-Air-2 SpeechRecognition % python create_wav2vec2.py
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Removing weight_norm from ConvolutionalPositionalEmbedding
Traceback (most recent call last):
  File "/Users/pbanavara/dev/ios-demo-app/SpeechRecognition/create_wav2vec2.py", line 55, in <module>
    quantized_model = torch.quantization.quantize_dynamic(
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 434, in quantize_dynamic
    convert(model, mapping, inplace=True)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 519, in convert
    _convert(
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 557, in _convert
    _convert(mod, mapping, True,  # inplace
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 557, in _convert
    _convert(mod, mapping, True,  # inplace
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 557, in _convert
    _convert(mod, mapping, True,  # inplace
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 559, in _convert
    reassign[name] = swap_module(mod, mapping, custom_module_class_mapping)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/ao/quantization/quantize.py", line 592, in swap_module
    new_mod = qmod.from_float(mod)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/nn/quantized/dynamic/modules/linear.py", line 110, in from_float
    qlinear = cls(mod.in_features, mod.out_features, dtype=dtype)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/nn/quantized/dynamic/modules/linear.py", line 34, in __init__
    super(Linear, self).__init__(in_features, out_features, bias_, dtype=dtype)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/nn/quantized/modules/linear.py", line 144, in __init__
    self._packed_params = LinearPackedParams(dtype)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/nn/quantized/modules/linear.py", line 22, in __init__
    self.set_weight_bias(wq, None)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/nn/quantized/modules/linear.py", line 27, in set_weight_bias
    self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
  File "/Users/pbanavara/miniforge3/envs/pytorch/lib/python3.10/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Didn't find engine for operation quantized::linear_prepack NoQEngine
`

**Comment by RazeBerry** [comment]
Same problem here. It is brand new to me as well! Didn't have it before then
