### ISSUE TITLE
Multiprocess data loader crash/hang in v1.3

### ISSUE THREAD

**Issue by pdwilson12** [pytorch/pytorch#29325]
## 🐛 Bug

When I use a data loader with num_workers > 0, each worker crashes trying to get the shared-storage file name. The code works with num_workers=0 and under pytorch v1.2 in both single and multi-process modes.

## To Reproduce

Run this code with pytorch 1.2 and 1.3:

    #! /usr/bin/env python

    import torch
    import math

    # Dataset code copied from torch.utils.data.IterableDataset example:
    #    https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset
    class MyIterableDataset(torch.utils.data.IterableDataset):
        def __init__(self, start, end):
            super(MyIterableDataset).__init__()
            assert end > start, "this example code only works with end >= start"
            self.start = start
            self.end = end

        def __iter__(self):
            worker_info = torch.utils.data.get_worker_info()
            if worker_info is None:  # single-process data loading, return the full iterator
                iter_start = self.start
                iter_end = self.end
            else:  # in a worker process
                # split workload
                per_worker = int(math.ceil((self.end - self.start) / float(worker_info.num_workers)))
                worker_id = worker_info.id
                iter_start = self.start + worker_id * per_worker
                iter_end = min(iter_start + per_worker, self.end)
            print(f'start = {iter_start}; end = {iter_end}')
            return iter(range(iter_start, iter_end))
        

    ds = MyIterableDataset(1,1000)

    print("Dump first batch of single-process data loader")
    dl1 = torch.utils.data.DataLoader(ds, num_workers=0, batch_size=6)

    v1 = iter(dl1)
    print(f'   Iterator: {v1}')
    v2 = next(v1)
    print(v2)

    print("\nDump first batch of multi-process data loader")
    dl2 = torch.utils.data.DataLoader(ds, num_workers=2, batch_size=6)

    v1 = iter(dl2)
    print(f'   Iterator: {v1}')
    v2 = next(v1)
    print(v2)

## Expected behavior

Under pytorch 1.2, I get these results as expected:

    Dump first batch of single-process data loader
    start = 1; end = 1000
       Iterator: <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x105d89898>
    tensor([1, 2, 3, 4, 5, 6])

    Dump first batch of multi-process data loader
       Iterator: <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x11ce180b8>
    start = 1; end = 501
    start = 501; end = 1000
    tensor([1, 2, 3, 4, 5, 6])

Under pytorch 1.3, I get these results (showing just one traceback, though) and the process hangs waiting for data to be returned from the workers:

    Dump first batch of single-process data loader
    start = 1; end = 1000
       Iterator: <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x1091478d0>
    tensor([1, 2, 3, 4, 5, 6])

    Dump first batch of multi-process data loader
       Iterator: <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x115578e10>
    start = 1; end = 501
    start = 501; end = 1000
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
        obj = _ForkingPickler.dumps(obj)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
        cls(buf, protocol).dump(obj)
      File "/Users/pdw/Documents/Projects/ML/arches/env/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
        metadata = storage._share_filename_()
    RuntimeError: error executing torch_shm_manager at "/Users/pdw/Documents/Projects/ML/arches/env/lib/python3.6/site-packages/torch/bin/torch_shm_manager" at ../torch/lib/libshm/core.cpp:99

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.1
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.3.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

Have also hit the hang running on a Linux machine.

cc @SsnL

**Comment by pdwilson12** [comment]
Correct regarding Linux.  I am not seeing a crash on Linux. Instead I'm seeing a 10+ performance slowdown in my larger app and hit the crasher on macOS while diagnosing. These may or may not be related.

**Comment by soumith** [comment]
cc: @ssnl @pritamdamania

**Comment by SsnL** [comment]
This is pretty weird considering that basically nothing changed in libshm or data loader from 1.2 to 1.3... The only dataloader change was to remove an arg check.

**Comment by soumith** [comment]
oh oh, I know the issue. This was a packaging issue that was fixed via https://github.com/pytorch/builder/commit/2ac74c1d5669ad2c32b873461970d33cc4b5c93c

1.3.0.post2 or 1.3.1 both have the fix, so @pdwilson12 please upgrade.

**Comment by pdwilson12** [comment]
Confirmed fix in 1.3.1.

**Comment by TortoiseHam** [comment]
I had this same issue with python 3.7, macOS 10.15, Pytorch 1.3.1. Manually issuing the command `pip install https://github.com/matthew-brett/delocate/archive/master.zip` as suggested in the link from Soumith fixed it.
