### ISSUE TITLE
[jit] `torch.isfinite` is broken

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#29340]
```python
def fn(x):
    print(torch.isfinite(x))


s = torch.jit.script(fn)
fn(torch.randn(2, 2))
s(torch.randn(2, 2))
```

results in 

```
tensor([[True, True],
        [True, True]])
graph(%x.1 : Tensor):
  %4 : None = prim::Constant() # ../test.py:14:0
  %2 : float = prim::ImplicitTensorToNum(%x.1) # ../test.py:15:10
  %3 : bool = aten::isfinite(%2) # ../test.py:15:10
   = prim::Print(%3) # ../test.py:15:4
  return (%4)                                                                                                                                   
Traceback (most recent call last):
  File "../test.py", line 21, in <module>
    s(torch.randn(2, 2))
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument
The above operation failed in interpreter, with the following stack trace:
at ../test.py:15:10
def fn(x):
    print(torch.isfinite(x))
          ~~~~~~~~~~~~~~ <--- HERE
```

It crashes at runtime and the signature is wrong since the actual op is not bound in, it's instead done here
https://github.com/pytorch/pytorch/blob/0d9dc469cc44037d5931f1aa8abfae644f133f75/torch/csrc/jit/register_prim_ops.cpp#L2941
```


cc @suo

**Comment by eellison** [comment]
This is an example of a general source of bugs in TorchScript, which is that if you register an operator that should be overloaded with both Scalar and Tensor for an argument for only the Scalar case it will lead to bad implicit casting and a runtime error. The fix is to just expose the op that has a Tensor input. 

See also: https://github.com/pytorch/pytorch/issues/27512

https://github.com/pytorch/pytorch/issues/20664

**Comment by zetyquickly** [comment]
> This is an example of a general source of bugs in TorchScript, which is that if you register an operator that should be overloaded with both Scalar and Tensor for an argument for only the Scalar case it will lead to bad implicit casting and a runtime error. The fix is to just expose the op that has a Tensor input.
> 
> See also: #27512
> 
> #20664

Thanks a lot for your reply,
Does expose means to copypaste code of function or that means to specify input types to a function call?

**Comment by eellison** [comment]
Hmm actually, looks like we're not correctly resolving `torch.isfinite` to torch.functional.isfinite. 

A workaround is to call `torch.functional.isfinite(x)`

**Comment by zetyquickly** [comment]
> Hmm actually, looks like we're not correctly resolving `torch.isfinite` to torch.functional.isfinite.
> 
> A workaround is to call `torch.functional.isfinite(x)`

I've tried F.isfinite(x) returns 'bool' while scripting and Tensor in Python

```
Variable 'bool_tensor' is annotated with type Tensor but is being assigned to a value of type bool:
at box_regression.py:84:8
        """
            deltas (Tensor): some tensor
        """
        bool_tensor : torch.Tensor = torch.functional.isfinite(deltas)
        ~~~~~~~~~~~ <--- HERE
```

**Comment by eellison** [comment]
Hmm, actually you're right, all of the functions in `torch/functional.py` aren't working in JIT unless they are a 1-1 mapping with the C++ functions. Also those only defined in `torch/tensor.py` don't work...

**Comment by zetyquickly** [comment]
> Hmm, actually you're right, all of the functions in `torch/functional.py` aren't working in JIT unless they are a 1-1 mapping with the C++ functions. Also those only defined in `torch/tensor.py` don't work...

How can we solve it, what type of changes could we propose to repository?

**Comment by eellison** [comment]
FYI: https://github.com/pytorch/pytorch/pull/28918/

**Comment by eellison** [comment]
This should be fixed now.
