### ISSUE TITLE
Caffe2 ONNX CI's TestCaffe2BackendEmbed_opset9.test_randn_like is flaky

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29348]
Nov 07 00:55:14 test/onnx/test_pytorch_onnx_caffe2.py::TestCaffe2BackendEmbed_opset9::test_randn PASSED [ 14%]
Nov 07 00:55:15 test/onnx/test_pytorch_onnx_caffe2.py::TestCaffe2BackendEmbed_opset9::test_randn_like /var/lib/jenkins/workspace/scripts/onnx/test.sh: line 55: 17708 Segmentation fault      (core dumped) pytest "${args[@]}" -k 'not (TestOperators and test_full_like) and not (TestOperators and test_zeros_like) and not (TestOperators and test_ones_like) and not (TestModels and test_vgg16) and not (TestModels and test_vgg16_bn) and not (TestModels and test_vgg19) and not (TestModels and test_vgg19_bn)' --ignore "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py" --ignore "$top_dir/test/onnx/test_custom_ops.py" --ignore "$top_dir/test/onnx/test_models_onnxruntime.py" "${test_paths[@]}"
Exited with code 139

https://circleci.com/gh/pytorch/pytorch/3504741?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

Possibly related to #29344? @houseroad, any idea? 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by houseroad** [comment]
I have reverted the intrusive PR.  @neginraoof will further investigate the root cause and resubmit the PR.

**Comment by neginraoof** [comment]
Thanks @houseroad. There was a PR to fix outplace jit tracing for *_like operators (https://github.com/pytorch/pytorch/pull/28839) that modified the arguments for *_like ops. I updated the PR.

**Comment by houseroad** [comment]
Fixed
