### ISSUE TITLE
ONNX CI's test.sh is flaky and can segfault

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29344]
Nov 07 00:33:55   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 286 in __call__
Nov 07 00:33:55   File "/usr/local/lib/python3.6/dist-packages/_pytest/config/__init__.py", line 90 in main
Nov 07 00:33:55   File "/usr/local/bin/pytest", line 11 in <module>
Nov 07 00:33:55 /var/lib/jenkins/workspace/scripts/onnx/test.sh: line 55:   474 Segmentation fault      (core dumped) pytest "${args[@]}" -k 'not (TestOperators and test_full_like) and not (TestOperators and test_zeros_like) and not (TestOperators and test_ones_like) and not (TestModels and test_vgg16) and not (TestModels and test_vgg16_bn) and not (TestModels and test_vgg19) and not (TestModels and test_vgg19_bn)' --ignore "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py" --ignore "$top_dir/test/onnx/test_custom_ops.py" --ignore "$top_dir/test/onnx/test_models_onnxruntime.py" "${test_paths[@]}"
Exited with code 139

https://circleci.com/gh/pytorch/pytorch/3504322?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@houseroad, have you seen this before? 

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by houseroad** [comment]
Yes, this is caused by #29348

**Comment by houseroad** [comment]
Fixed
