### ISSUE TITLE
__array__ and __array_wrap__

### ISSUE THREAD

**Issue by kohr-h** [pytorch/pytorch#2935]
To improve Numpy interoperability, torch tensors could implement the array interface in a quite simple manner:
```python
def __array__(self, dtype=None):
    if dtype is None:
        return self.cpu().numpy()
    else:
        return self.cpu().numpy().astype(dtype, copy=False)


def __array_wrap__(self, array):
    if array.ndim == 0:
        if array.dtype.kind == 'b':
            return bool(array)
        elif array.dtype.kind in ('i', 'u'):
            return int(array)
        elif array.dtype.kind == 'f':
            return float(array)
        elif array.dtype.kind == 'c':
            return complex(array)
        else:
            raise RuntimeError
    else:
        if array.dtype == bool:
            # Workaround, torch has no built-in bool tensor
            cls = torch.ByteTensor
            array = array.astype('uint8')
        else:
            cls = _tensor_cls(array.dtype, use_cuda=self.is_cuda)
        return cls(array)


def _tensor_cls(dtype, use_cuda):
    mapping = {
        np.dtype('float16'): 'Half',
        np.dtype('float32'): 'Float',
        np.dtype('float64'): 'Double',
        np.dtype('int8'): 'Char',
        np.dtype('int16'): 'Short',
        np.dtype('int32'): 'Int',
        np.dtype('int64'): 'Long',
        np.dtype('uint8'): 'Byte',
    }
    try:
        name = mapping[np.dtype(dtype)]
    except KeyError:
        raise ValueError('dtype {} not supported'.format(dtype))
    if use_cuda:
        return getattr(torch.cuda, name)
    else:
        return getattr(torch, name)
```
It would enable simple things like `numpy.asarray` to turn tensors into Numpy arrays, and with that make basically all of Numpy applicable to torch tensors (with some restrictions). Is something like that of interest?

**Comment by apaszke** [comment]
Yes that looks great! Note that it's much simpler to use `torch.from_numpy`, which will create a Tensor of appropriate type for you

**Comment by kohr-h** [comment]
Alright, I'll make a PR then.

> Note that it's much simpler to use torch.from_numpy, which will create a Tensor of appropriate type for you

You're right, I don't know why I overlooked this.

Regarding placement, my suggestion is to define the generic methods like above in `torch/__init__.py` and then just set the attribute in each class.
**Question1** regarding `HalfTensor`: it doesn't implement `numpy()` so this code will crash with that tensor class. Should we let it crash or rather leave the attribute off the class? An argument for the former is that if it's left out, `numpy.asarray` will still silently work but yield a (largely useless) `object` array with 1 element (the tensor).
**Question2** regarding bools: Okay to use `ByteTensor`? Again, the alternative is to just let it crash.

**Comment by apaszke** [comment]
1. We coud add a `numpy()` for half as well
2. Yes, that's fine
