### ISSUE TITLE
cuSPARSE handle is not thread-safe

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#29352]
From what I observe when working on https://github.com/pytorch/pytorch/pull/29233, cusparse handle is managed the same way as cublas handle, therefore not thread-safe.

https://github.com/pytorch/pytorch/pull/29233 makes the handle pool mechanism which was originally used for cudnn generic, so it would also be able to use to manage cusparse handle. We should migrate the management of cusparse handle to that approach.

See also: https://github.com/pytorch/pytorch/issues/6962

cc: @mcarilli @ngimel @mruberry

**Comment by mruberry** [comment]
Thanks for thinking of cleaning this up, too!
