### ISSUE TITLE
import torch   error

### ISSUE THREAD

**Issue by dengxuexiang** [pytorch/pytorch#29368]
(deng_py36) zengxw@bdlk-SYS-4028GR-TR:~/python_work/AlphaPose$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/zengxw/.conda/envs/deng_py36/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THManagedSharedAllocator

I installed pytorch version 0.4.0. What should I do

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your particular question, please make sure that you don't have multiple pytorch installs and then install the latest pytorch version.
