### ISSUE TITLE
Indexing with dtype torch.uint8

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#29365]
When I run the reinforcement learning [example](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html), I see a lot of warning message like 
```
/home/mahmood/pytorch/aten/src/ATen/native/IndexingUtils.h:20: 
UserWarning: indexing with dtype torch.uint8 is now deprecated, please 
use a dtype torch.bool instead.
  " please use a dtype torch.bool instead.");
```
That line is the code only prints the message. Where should I fix then?

**Comment by mahmoodn** [comment]
Is it enough to only modify `dtype` in this function?
```
non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
                                          batch.next_state)), device=device, dtype=torch.bool)
```

**Comment by albanD** [comment]
Hi,

Please use the forum to ask questions: https://discuss.pytorch.org/

For your question, yes that should work. Make sure it removes the warning properly.

**Comment by luxiaojuntokyo** [comment]
> Is it enough to only modify `dtype` in this function?
> 
> ```
> non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
>                                           batch.next_state)), device=device, dtype=torch.bool)
> ```

Yes, this answer solved my same problem.
