### ISSUE TITLE
TestNN.test_CTCLoss_1d_target_cuda is flaky in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29380]
CI build: pytorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_test

Nov 07 16:05:57 ======================================================================
Nov 07 16:05:57 FAIL: test_CTCLoss_1d_target_cuda_double (__main__.TestNN)
Nov 07 16:05:57 ----------------------------------------------------------------------
Nov 07 16:05:57 Traceback (most recent call last):
Nov 07 16:05:57   File "/var/lib/jenkins/workspace/test/common_utils.py", line 562, in wrapper
Nov 07 16:05:57     method(*args, **kwargs)
Nov 07 16:05:57   File "/var/lib/jenkins/workspace/test/common_utils.py", line 562, in wrapper
Nov 07 16:05:57     method(*args, **kwargs)
Nov 07 16:05:57   File "/var/lib/jenkins/workspace/test/common_utils.py", line 446, in __exit__
Nov 07 16:05:57     self.name, after - before, i))
Nov 07 16:05:57   File "/var/lib/jenkins/workspace/test/common_utils.py", line 767, in assertEqual
Nov 07 16:05:57     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Nov 07 16:05:57 AssertionError: 36864 not less than or equal to 1e-05 : __main__.TestNN.test_CTCLoss_1d_target_cuda_double leaked 36864 bytes CUDA memory on device 0
Nov 07 16:05:57 
Nov 07 16:05:57 ----------------------------------------------------------------------
Nov 07 16:05:57 Ran 1526 tests in 635.937s

https://app.circleci.com/jobs/github/pytorch/pytorch/3510589

cc @ezyang @gchanan @zou3519 @jerryzh168 @ngimel

**Comment by mruberry** [comment]
Per review with @ngimel, issue is not specific to test_CTCLoss_1d_target_cuda, and there is likely a rare issue with how a CUDA memory allocator reports memory usage (not a regression). We'll continue to watch for issues like this.

**Comment by mruberry** [comment]
This did happen again: 

https://app.circleci.com/jobs/github/pytorch/pytorch/3602021

**Comment by ezyang** [comment]
cc @t-vi

**Comment by ezyang** [comment]
Would be good to figure out if this is cudnn ctcloss or our cuda ctcloss

**Comment by mruberry** [comment]
Closing because this is no longer occurring.
