### ISSUE TITLE
pip install torch error 

### ISSUE THREAD

**Issue by jeffersonmike** [pytorch/pytorch#29395]
## 🐛 Bug

I just submitted a report using Python 3.8 which is not supported. Now using 3.7.5 but having issues as well. 

I am trying to install torch via pip and return the below error. Very new to this. If there is more info I can provide, let me know.

Installing collected packages: pytorch
Running setup.py install for pytorch ... error
ERROR: Command errored out with exit status 1:

OS: Windows 10
pip
Build command: pip install torch
Python version: 3.7.5
## To Reproduce

C:\Users\jeffe>pip install torch
Collecting torch
  Using cached https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz
Requirement already satisfied: pyyaml in c:\users\jeffe\appdata\local\programs\python\python37\lib\site-packages (from torch) (5.1.2)
Installing collected packages: torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jeffe\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-r6fu5tcc\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-r6fu5tcc\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-_cdbg_4b\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\jeffe\AppData\Local\Temp\pip-install-r6fu5tcc\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-r6fu5tcc\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-r6fu5tcc\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\jeffe\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\jeffe\AppData\Local\Temp\pip-install-r6fu5tcc\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jeffe\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-r6fu5tcc\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-r6fu5tcc\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-_cdbg_4b\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by peterjc123** [comment]
`pip install torch` is not supported on Windows. Please try the commands on http://pytorch.org.

**Comment by shrenik49** [comment]
http://pytorch.org.  same error is shown on laptop it is resolved by using http://pytorch.org.

**Comment by BramVanroy** [comment]
@peterjc123  What is the reason for this, I wonder? Why can't pip figure out which system variables to use to install the right version?

**Comment by peterjc123** [comment]
@BramVanroy Historically, we don't upload them to PyPI because the Windows wheels are too large. But we are planning to publish CPU packages instead recently. (maybe starting with 1.7.1)
 

> Why can't pip figure out which system variables to use to install the right version?

I don't know what you are referring to `system variable` here. Actually, `pip` is very limited for os version detection. For example, it can only if you are using `win32` or `win64`. So, it is impossible to publish a Windows 10 only package.

**Comment by BramVanroy** [comment]
Yeah, my bad, I was thinking about setup.py where detecting the specific Windows version should not be too hard (e.g. `sys.getwindowsversion()`) but I have to admit that I do not know how `pip` does version detection and stuff like that.
