### ISSUE TITLE
in-place operation error thrown after mutation instead of before

### ISSUE THREAD

**Issue by willwhitney** [pytorch/pytorch#2940]
When you call an in-place op on a leaf Variable that requires grad, pytorch throws an error. However, it first mutates that variable.

Does this break the graph? It seems like the variable shouldn't get mutated.

```
>>> a
Variable containing:
 0.6285  0.0864  0.0217  0.8061  0.9542
 0.9619  0.9678  0.9665  0.6608  0.9865
 0.7041  0.5659  0.0866  0.2487  0.9058
 0.3969  0.8566  0.4314  0.0243  0.3414
 0.5087  0.7177  0.2486  0.9656  0.4393
[torch.FloatTensor of size 5x5]

>>> a.add_(noise)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willw/anaconda/lib/python3.5/site-packages/torch/autograd/variable.py", line 322, in add_
    return self._add(other, True)
  File "/Users/willw/anaconda/lib/python3.5/site-packages/torch/autograd/variable.py", line 313, in _add
    return Add.apply(self, other, inplace)
RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.
>>> a
Variable containing:
 0.5088  0.0052 -0.2603 -0.9549  1.1598
 1.3255  1.3079  1.7067  1.8954 -0.5464
 0.0219 -1.0987  0.2794  0.4004 -0.0731
-0.5973 -0.2672  0.9868 -1.1371  1.6382
 1.0826  0.7228 -1.6244  2.4482 -0.5585
[torch.FloatTensor of size 5x5]
```

Found on pytorch 0.2.0.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by apaszke** [comment]
It's always been like this, and I don't think we can do anything about it easily (maybe apart from adding a note that this has already happened in the error message). The problem is that a Function declares that it modified something when it's running, so we only see it afterwards.

**Comment by willwhitney** [comment]
I see. I think it would be good for the error message to tell you that - could save someone else a confusing few minutes.

**Comment by apaszke** [comment]
I agree. We'll fix that

**Comment by colesbury** [comment]
This is fixed for functions implemented through ATen (like `add_`), but not functions implemented in Python (like `__setitem__`).

@apaszke, why can't `mark_dirty` throw an exception if the argument shouldn't be modified?

**Comment by apaszke** [comment]
It can, but it would work differently than all other methods and would have to be moved to C. Also, we would need to go over all of our functions and make sure it is called before the tensors are actually mutated. But yes, as long as we do it this way it should actually be possible to raise errors before mutation

**Comment by mruberry** [comment]
@albanD Is this still an issue?

**Comment by albanD** [comment]
Yes this has been fixed !
