### ISSUE TITLE
How to inference with nn.TransformerDecoder layer

### ISSUE THREAD

**Issue by xdwang0726** [pytorch/pytorch#29422]
I am using customized Transformer with nn.TransformerDecoder layer . It seem like nn.TransformerDecoder layer doesn't support inference process(generation/testing), like sending token id one by one with fixed memory generated from nn.TransformerEncoder layer. I am wondering is there a tutorial that I can refer to as I didn't find a tutorial in the official documents. Thank  you in advance for your help!

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions

**Comment by soumith** [comment]
you can also refer to https://github.com/pytorch/examples/tree/master/word_language_model if that helps, it has a generate.py

cc: @zhangguanheng66

**Comment by xdwang0726** [comment]
> you can also refer to https://github.com/pytorch/examples/tree/master/word_language_model if that helps, it has a generate.py
> 
> cc: @zhangguanheng66

Thank you for your reply! I found that the tutorials you refered only contains nn.TransformerEncoder, and I am actually have troubles in nn.TransformerDecoder. Is it possible to release a tutorial model which uses both encoder and decoder? Thank you!

**Comment by zhangguanheng66** [comment]
For the actual applications of `nn.Module`, you should ask the questions in https://discuss.pytorch.org
