### ISSUE TITLE
How to know which whl version can be selected?

### ISSUE THREAD

**Issue by moyans** [pytorch/pytorch#29434]
@svenstaro @eklitzke @jfsantos I wan't use pip install torch with cuda10, i know use bash like this: 
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
when i choose python vision is cp37, It will be reported wrong: 
ERROR: torch-1.1.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
so i want know which whl version can be selected?

cc @ezyang

**Comment by svenstaro** [comment]
Why highlight me? I'm the Arch maintainer. However, you're apparently not using Pacman to install this.

**Comment by moyans** [comment]
> Why highlight me? I'm the Arch maintainer. However, you're apparently not using Pacman to install this.

Just my careless，I'm sorry to disturb you，but my environment can only use pip instal

**Comment by jameslahm** [comment]
@moyans why not just 
> pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

if you don't use cuda

**Comment by moyans** [comment]
> @moyans why not just
> 
> > pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
> 
> if you don't use cuda

Thank you, I get it。

https://download.pytorch.org/whl/torch_stable.html
https://download.pytorch.org/whl/cu90/torch_stable.html
https://download.pytorch.org/whl/cu80/torch_stable.html
