### ISSUE TITLE
C++ API: Is there a timeline of the major breaking changes to the backend?

### ISSUE THREAD

**Issue by marcoippolito** [pytorch/pytorch#29445]
We read from the documentation https://pytorch.org/cppdocs/  "At the moment, the C++ API should be considered “experimental”; we may make major breaking changes to the backend in order to improve the API, or in service of providing the Python interface to PyTorch, which is our most stable and best supported interface."

So, being interested in developing and deploying pytorch models in C++, I would like to know if there is a timeline of the major breaking changes.

Marco

**Comment by albanD** [comment]
This is a cross post with the forum: https://discuss.pytorch.org/t/c-api-is-there-a-timeline-of-the-major-breaking-changes-to-the-backend/60384

We use github issues only for features and bugs, so we will answer in the forum.

**Comment by marcoippolito** [comment]
Ok. Eager to your kind answer in the forum
