### ISSUE TITLE
Stride() function is not documented as it is defined in source code.

### ISSUE THREAD

**Issue by Ujjwal-9** [pytorch/pytorch#2946]
check the definition [here](https://github.com/pytorch/pytorch/blob/312e0ce3ba1fa74854a1fc82aa1b7c24baeb4006/torch/lib/TH/generic/THTensor.c#L28)

**Comment by fmassa** [comment]
Would you like to try to add an entry for the docs for it?
I think you need to add entries in [this file](https://github.com/pytorch/pytorch/blob/master/docs/source/tensors.rst) (just below `size` for example) and  in [this file, following the doc for size](https://github.com/pytorch/pytorch/blob/master/torch/_tensor_docs.py#L1378-L1388), and that should be all I think.
You can compile the docs locally with [`make html` in the docs folder](https://github.com/pytorch/pytorch/tree/master/docs)

**Comment by Ujjwal-9** [comment]
Sure I will do it.
