### ISSUE TITLE
Tensor operations with exponents less than 1 return nan's

### ISSUE THREAD

**Issue by C-Weed28** [pytorch/pytorch#29518]
## ❓ Questions and Help
torch.pow() returns nan when its given the exponent argument between ranges -1 and 1

a = torch.randn(1,3)
a

>> tensor([[-1.7871, -0.5375, -0.1164]])

torch.pow(a, 2)      #or a**2

>> tensor([[3.1938, 0.2889, 0.0136]])

torch.pow(a,0.5)     #or a**0.5

>> tensor([[nan, nan, nan]])
expect result:

tensor([[-1.3368, -0.7331, -0.3412]])
Edit: turns out that ** works the same way as well. a**2 does the same thing with the tensor as torch.pow(a,2). a**0.5 returns nan's like torch.pow does.

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by C-Weed28** [comment]
My bad, you can't square root negative numbers

**Comment by YuxinZhaozyx** [comment]
```
>>> torch.pow(torch.tensor([-8.0]), 1/3)
tensor([nan])
```

`torch.pow()` doesn't work for a negative number when its given the exponent argument 1/3.
