### ISSUE TITLE
Downloading MNIST is flaky in CI

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#29515]
build: pytorch_linux_xenial_py2_7_test
see: https://app.circleci.com/jobs/github/pytorch/pytorch/3547692

```
Nov 09 23:41:32     self.timeout, self.source_address)
Nov 09 23:41:32   File "/opt/python/2.7/lib/python2.7/socket.py", line 557, in create_connection
Nov 09 23:41:32     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
Nov 09 23:41:32 IOError: [Errno socket error] [Errno -5] No address associated with hostname
Nov 09 23:41:32 + cleanup
Nov 09 23:41:32 + retcode=1
Nov 09 23:41:32 + set +x
```

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @jerryzh168

**Comment by kurtamohler** [comment]
Should we add a retry for this download? We could attempt to download 3 times, and then throw the error.

**Comment by mruberry** [comment]
Closing because this is no longer occurring.
