### ISSUE TITLE
multi_head_attention_forward give individual mask for each src

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/pytorch#29520]
## 🚀 Feature

in F.multi_head_attention_forward function. The attn_mask is 2D. Is it possible to make it 3D with the first dim equals to the batch size? So, each src can have its unique mask.
## Motivation
I want to set the mask for each src respectively.

## Alternatives

For now. We should copy and rewrite the multi_head_attention_forward function. I can submit a PR if this feature is accept.

**Comment by ngimel** [comment]
cc @zhangguanheng66

**Comment by zhangguanheng66** [comment]
A similar PR https://github.com/pytorch/pytorch/pull/25359

**Comment by zhangguanheng66** [comment]
some changes could be made [here](https://github.com/pytorch/pytorch/blob/77bb41c96553756dea5e350ad02383bc5f00b7ab/torch/nn/functional.py#L3364). However, in general, I don't want to change the API which introduce a BC breaking.
