### ISSUE TITLE
Add simple tutorial for model parallel training

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#29537]
## 📚 Documentation

For our 1.4 RC, we should have a simple hello-world style tutorial that shows users how to use the model parallel/rpc APIs for simple multi-machine/ParameterServer training. The examples can be simple and concise such as the ones given in https://github.com/pytorch/pytorch/issues/23110, but should have a detailed walkthrough explaining the concepts and APIs used.

cc @ezyang @gchanan @zou3519 @jerryzh168 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by gqchen** [comment]
I would suggest we take a look at @aazzolini's internal version of "very_simple.py" as starting point. It is a great example of how module parallel and distributed data parallel work together. It is simple enough that we can put complete code of a simplified version in the tutorial.

**Comment by rohan-varma** [comment]
There are also examples in @mrshenli's recent PR: https://github.com/pytorch/pytorch/pull/29543/f

**Comment by aazzolini** [comment]
@zzzwen is currently working on migrating those internal examples (including very_simple.py) to the pytorch OSS RPC. We could re-use those too possibly.

**Comment by rohan-varma** [comment]
@mrshenli is currently working on this - https://github.com/pytorch/tutorials/pull/807/files

**Comment by meetshah1995** [comment]
@aazzolini Any chance the `very_simple.py` can be shared? It'd be superful useful.

I'm also trying to get the RPC based model parallel work with DDP. Is there a way simple to way to make these work together other than writing different execute methods and spawning them based on global + local rank?

@mrshenli's RL and RNN tutorial only show how to model parallel with RPC, but an example showing how to tie that with DDP would be awesome.

**Comment by rohan-varma** [comment]
cc @zhaojuanmao who is working on DDP + RPC.

**Comment by meetshah1995** [comment]
Just checking in to see if there are any updates on this. Having distributed model parallel support for Pytorch would be super awesome!

**Comment by rohan-varma** [comment]
@meetshah1995 Thanks for checking in! Other than the tutorial that @mrshenli added and is available here: https://pytorch.org/tutorials/intermediate/rpc_tutorial.html, I'm also working on a tutorial that demonstrates the parameter-serving training strategy (https://github.com/pytorch/examples/pull/705/files).

Regarding getting DDP and RPC to work together, this may be something that we want to work on in the near future, but are still very much in the early stages of planning. We will share more details via a GH issue about plans for this in the future.

**Comment by rohan-varma** [comment]
We've added tutorials at https://github.com/pytorch/tutorials/blob/master/intermediate_source/rpc_tutorial.rst and https://github.com/pytorch/tutorials/blob/master/intermediate_source/rpc_param_server_tutorial.rst
