### ISSUE TITLE
Installing nightly torch and torchvision shows error

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#29530]
## 🐛 Bug

Installing nightly builds of `torch` and `torchvision` shows `ERROR: torchvision 0.5.0.dev20191110 has requirement torch==1.4.0.dev20191109, but you'll have torch 1.4.0.dev20191110 which is incompatible.`.

## To Reproduce

```
~: python3 -m pip install --pre torch torchvision -f 
https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```
```
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.4.0.dev20191110-cp37-none-macosx_10_7_x86_64.whl (81.0MB)
     |████████████████████████████████| 81.0MB 934kB/s 
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/torchvision-0.5.0.dev20191110-cp37-cp37m-macosx_10_7_x86_64.whl (371kB)
     |████████████████████████████████| 378kB 754kB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from torchvision) (1.11.0)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.7/site-packages (from torchvision) (6.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from torchvision) (1.16.4)
ERROR: torchvision 0.5.0.dev20191110 has requirement torch==1.4.0.dev20191109, but you'll have torch 1.4.0.dev20191110 which is incompatible.
Installing collected packages: torch, torchvision
Successfully installed torch-1.4.0.dev20191110 torchvision-0.5.0.dev20191110
```

## Environment

PyTorch version: 1.4.0.dev20191110
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.1
GCC version: Could not collect
CMake version: version 3.15.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] pytorch-transformers==1.0.0
[pip3] torch==1.4.0.dev20191110
[pip3] torchvision==0.5.0.dev20191110
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by ezyang** [comment]
Confirmed this reproduces. I wonder why pip's dependency solver isn't excluding the newer version of torch when this happens.

**Comment by ezyang** [comment]
It does the right thing if you only specify `torchvision` and not `torchvision torch`

**Comment by ezyang** [comment]
So it looks like the problem is in the window where we have uploaded `torch` nightlies for a date, but not `torchvision` nightlies, the `pip install` command doesn't work. This is because it looks like when you say `pip install torch torchvision`, pip takes this to mean "install the latest version of torch and latest version of torchvision"; which are not compatible. This has been exacerbated by recent rearrangement of nightly schedules which means that torchvision is persistently behind the torch nightly.

We can fix the exacerbating factor by rearranging the nightly build schedule so that torchvision nightlies only build after the torch nightlies are out. But there will still be a window of time when this pair of commands will not work. I tried a few variations of the pip install command but the only way I could get to be smart about torch version selection was to just eliminate it from the command line entirely. This is a bit vexing.

cc @fmassa @mingbowan

**Comment by ezyang** [comment]
I've changed the nightly times so that torchvision/torchaudio build after s3 html update, and then we do another s3 html update at 6am pst.

**Comment by zou3519** [comment]
> So it looks like the problem is in the window where we have uploaded `torch` nightlies for a date, but not `torchvision` nightlies, the `pip install` command doesn't work

Why can't we withhold uploading the `torch` nightlies until the `torchvision` nightlies are done, and then upload both? Do we not do this because we don't want to block the `torch` nightlies on `torchvision` nightly failures?

**Comment by soumith** [comment]
i think your fix is right Edward. indeed the failure case was that torchvision was depeeending on the previous day's pytorch

**Comment by ezyang** [comment]
@zou3519 there is a silly problem which prevents this: torchvision has to see torch in s3 htmls for its build to work.

But I am kind of thinking if we have a separate torch only channel that might be good enough to fix things once and for all. And then, as you say, only update the combined channel if everything passed.

**Comment by ezyang** [comment]
@soumith Sure, but we've only alleviated the symptoms: there's still a period of time when torch torchvision is not installable, using this command. That is a bit irritating to me.

**Comment by soumith** [comment]
@ezyang how about they are uploaded to a staging `nightly-staging.html`, and they actually go live to `nightly` as a `pre-smoketest` job?

**Comment by ezyang** [comment]
Yes, but we still have to make a call about whether or not to publish the latest torch nightly anyway if torchvision fails.
