### ISSUE TITLE
Rename parameter negative_slope of LeakyReLU

### ISSUE THREAD

**Issue by redw0lf** [pytorch/pytorch#29542]
## 📚 Documentation

The wording of the parameter is quite confusing. The slope in the LeakyReLu is not negative. Hence naming the parameter `negative_slope` might suggest that we are looking at a negative slope (f(x) = -ax), which needs to be negative in case we want a positive slope. 

Naming the parameter `slope` and explaining that it only applies for negative x might help to solve the issue and helps for a better understanding of the parameter.

See: https://pytorch.org/docs/stable/nn.html#leakyrelu

**Comment by Evpok** [comment]
That would break a lot of backward compatibility for dubious gains, honestly I don't see this happening.

**Comment by ngimel** [comment]
Agree with @evpok, renaming parameter is going to break backward compatibility. There is a documentation bug here, however, documentation should be saying `-negative_slope * x`. We'll be happy to accept documentation PR.

**Comment by redw0lf** [comment]
The formulas in the documentation and code are correct and they do not need to be changed. 

The term `negative_slope` can be misleading. As a negative slope is a line that descends, decreasing it's value with larger x. In the case of a LeakyReLu, it is a positive slope, as the value increases with x. 
The misleading parameter name here is `negative_slope` as it can be interpreted that in fact a  LeakyReLu uses a negative slope, which is not what it does.

**Comment by ngimel** [comment]
You are right, the docs are correct, my bad. Closing since there clearly is not enough benefit here to break backward compatibility.
