### ISSUE TITLE
requires_grad=False in nn.Embedding?

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#29555]
why does this give an error?

A:
```
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.embedding_to_learn = nn.Embedding(10, 5, requires_grad=True)
    self.embedding_to_not_learn = nn.Embedding(10, 5, requires_grad=False)
```
If I want to not learn some embeddings, then I have to do,

B:
```
class Net(nn.Module):
  def __init__(self):
    super().__init__()
    self.embedding_to_learn = nn.Embedding(10, 5)
    self.embedding_to_not_learn = nn.Embedding(10, 5)

model = Net()
model.embedding_to_not_learn.requires_grad_(requires_grad=False)
```
what is wrong with A, should it be made valid?

**Comment by albanD** [comment]
Hi,

`self.embedding_to_not_learn = nn.Embedding(10, 5).requires_grad_(False)` is the way to go to do this.

General `nn.Module` do not take any arguments as input. So adding this argument for all `nn.Module`s would be impossible as subclasses never pass arguments to the parent constructor.
