### ISSUE TITLE
Warning when compiling on ppc64le

### ISSUE THREAD

**Issue by dmarnerides** [pytorch/pytorch#2955]
I get this warning when I try to compile on a Power8 system (CUDA 8, cudnn 7)
```
THCNumerics.cuh(38): warning: integer conversion resulted in a change of sign
```

I generally get paranoid when integers change sign. On the other hand, compilers are really good at separating errors from warnings. Should I ignore this?

**Comment by ngimel** [comment]
Sounds like it is related to char signedness on POWER 8. This might be a related topic https://www.ibm.com/developerworks/community/forums/html/topic?id=77fa700b-c213-428c-af16-bddc7f887505

**Comment by dmarnerides** [comment]
I found the line responsible line
```
static inline __host__ __device__ char max() { return CHAR_MAX; }
```
https://github.com/torch/cutorch/blob/5e9d86cb982a6048d3077aeb0e0cee19847b4c08/lib/THC/THCNumerics.cuh#L38

It is (relatively) harmless I would say.

**Comment by soumith** [comment]
i closed the issue as you said it's relatively harmless. regardless if you think there's a fix for PPC64, let me know and we can commit it.
