### ISSUE TITLE
Remove thin Python wrapper in RPC module to avoid performance loss, also put docstring into rpc/init.cpp C++ Python bindings 

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#29628]
as titled.

Performance concern, mentioned in https://github.com/pytorch/pytorch/pull/28926#issuecomment-548811359

Docstring declaration point, mentioned in https://github.com/pytorch/pytorch/pull/28926#issuecomment-550107312

Ask for moving docstring for `RpcAgent.get_timeout()`, from https://github.com/pytorch/pytorch/pull/29341#discussion_r344977185

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
This was taken care of in a variety of PRs, we currently,don't have any calls in our python API that simply wrap PyBind calls now (one example is https://github.com/pytorch/pytorch/pull/33174). Closing this out
