### ISSUE TITLE
THAssert(THCTensor_(checkGPU)(state, 3, self_, src1, src2));

### ISSUE THREAD

**Issue by yangpc615** [pytorch/pytorch#29630]
`RuntimeError: Assertion `THCTensor_(checkGPU)(state, 3, self_, src1, src2)' failed.  at /pytorch/aten/src/THC/generic/THCTensorMathPointwise.cu:14`

The error was thrown in my loss. Before it, I ensure my output tensor and label located at GPU1. 

What is the cause of this problem?

What is function of  THAssert(THCTensor_(checkGPU)？

pytorch version： 1.3.0
cuda：10.1

**Comment by ngimel** [comment]
This function checks that all the tensors are on the same GPU. Note that function signature implies there are 3 tensors, not the 2 that you mention.
Can you please provide a script that would reproduce the error?

**Comment by yangpc615** [comment]
Thank you, I have solved this problem.

**Comment by Haruo195** [comment]
> Thank you, I have solved this problem.

@yangpc615 Hi, could you please tell us how did you solved that problem?
