### ISSUE TITLE
DeQuantStub still has an observer (and a qconfig)

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#29646]
## 🐛 Bug

The `DeQuantStub` is in the `_EXCLUDE_QCONFIG_PROPAGATE_LIST` (in the `default_mapppings.py`), but the qconfig still propagates to that module. This causes the observer to record the min/max at dequantization -- but those numbers are never used. This might have performance implications (think Histogram observers).

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
should be fixed now
