### ISSUE TITLE
Old package version in setup.py for v1.3.1

### ISSUE THREAD

**Issue by ShadowTemplate** [pytorch/pytorch#29643]
Hi all!
I would like to report that [v1.3.1 setup.py](https://github.com/pytorch/pytorch/blob/v1.3.1/setup.py#L260) incorrectly points to version **1.3.0a0**.
This is small mistake and it is easy to workaround, so I don't really expect you to push a fix. However, this is not the first time this error occurs (e.g. [1.0.0a0 for 1.0.1](https://github.com/pytorch/pytorch/blob/v1.0.1/setup.py#L215)). The reason I am creating this issue is just to raise awareness on some possible flaws in your release procedure.

Thank you very much for your attention and your work.
Have a great day.

cc @ezyang

**Comment by soumith** [comment]
we usually control the version name with env variable `TORCH_PACKAGE_NAME` in our binary build environments.

**Comment by soumith** [comment]
we'll try to proactively fix it, but since the v1.3.1 release is already tagged, i will refrain from changing the tag.

**Comment by ShadowTemplate** [comment]
Ok! Thank you very much for your response.
Have a great day.
