### ISSUE TITLE
Calibration observer should be allowed to run on GPU

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#29648]
## 🐛 Bug

Calibration of the quantized model requires the observers to walk through the training data in floating point mode. This could be done on GPU. However, the obserrver's `min`/`max` computation does not respect the device setting. Specifically,

```python
min_val = torch.min(torch.min(x), min_val)
```

requires that both `x` and `min_val` be on the same device, but calling `cuda()` on thte oobserver doesn't set the `min_val` device.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
This works now, closing:

```
import torch
obs = torch.quantization.MinMaxObserver().cuda()
for i in range(10):
    data = torch.randn(1, 1, 16, 16).cuda()
    obs(data)
```
