### ISSUE TITLE
[JIT] test_traced_module never runs its trace

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#2965]
It is missing `nderivs=0` so it never runs and silently passes. When I fix it, I then get:

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_jit.py", line 174, in test_traced_module
    out2 = lstm(input, (hx, cx))
  File "/data/users/zdevito/pytorch/torch/nn/modules/module.py", line 259, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/users/zdevito/pytorch/torch/jit.py", line 361, in __new_forward
    closure = ktrace.maybe_closure()
  File "/data/users/zdevito/pytorch/torch/jit.py", line 439, in maybe_closure
    if self.closure is not None:
RuntimeError: unrecognized NodeKind: Tanh

```

**Comment by ezyang** [comment]
Tanh is implemented in one of the commits in https://github.com/pytorch/pytorch/pull/2966

The `nderivs` business is awkward and I wish we had a better answer for it.

**Comment by zdevito** [comment]
For the tests at least, we should add an "assert this is going through the jit", because as you saw in the fixes, a lot of stuff was able to rot because the tests were masking it.

**Comment by apaszke** [comment]
That's what `has_trace_for` is. We can add it in every test

**Comment by ezyang** [comment]
It's still pretty easy to forget though :/

**Comment by apaszke** [comment]
We have `self.assertCompiled` now, so closing this.
