### ISSUE TITLE
Python 2.7 compatibility: AttributeError: 'unicode' object has no attribute 'is_sparse'

### ISSUE THREAD

**Issue by mitar** [pytorch/pytorch#2967]
The following fails:

```python
torch.from_numpy(np.array([1,2,3])).type(u'torch.DoubleTensor')
```

```
  File ".../torch/_utils.py", line 33, in _type
    if new_type.is_sparse:
AttributeError: 'unicode' object has no attribute 'is_sparse'
```

The reason why all strings are unicode is because I am using `from __future__ import unicode_literals`.

**Comment by albanD** [comment]
Hi,

The problem commes from [here](https://github.com/pytorch/pytorch/blob/5f864ca4d2cab5874e0b6779dc22f6de3a91c3e2/torch/_utils.py#L22) where we check only str and not unicode. @soumith not sure how this should be fixed, should `unicode` be added to `basestring` in `_six.py` ?

In the meantime, you can use `torch.from_numpy(np.array([1,2,3])).type(torch.DoubleTensor)` as type also accept the type directly, it does not have to be in a string.

**Comment by apaszke** [comment]
Yes, we should use basestring. However, I'd really recommend using `torch.DoubleTensor` directly. It's going to be faster, because it goes around the string parsing (otherwise, we have to get our hands on the tensor ourselves and this involves a bit of work).

**Comment by mitar** [comment]
Thanks for the workaround. I will use that.

**Comment by zou3519** [comment]
We're dropping support for Python 2.7 soon so this issue can be closed then.

**Comment by mruberry** [comment]
We no longer support Python 2. Closing this issue.
