### ISSUE TITLE
Add compiled CUDA version in torch.version

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#2969]
It might be good to have the CUDA version that was used to compile pytorch included somewhere accessible via Python, without the need to have CUDA installed in the machine.

Currently, I believe there is no way to find which CUDA version was used to compile pytorch, and we need to rely on a runtime error that [requires CUDA to run](https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L55) to know if the wheel is compatible.

I propose to add [a `cuda` flag in `torch.version`](https://github.com/pytorch/pytorch/blob/master/setup.py#L172) that returns the CUDA version used to compile PyTorch.

What do you think?

**Comment by apaszke** [comment]
Makes sense. Let's do it

**Comment by fmassa** [comment]
Awesome. I'll send a PR

**Comment by tstandley** [comment]
How does one check it?

**Comment by soumith** [comment]
print(torch.version.cuda)

**Comment by tstandley** [comment]
Thanks!

**Comment by zubinpahuja** [comment]
It doesn't work anymore?
