### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

### ISSUE THREAD

**Issue by forsener** [pytorch/pytorch#29711]
## 🐛 Bug

Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

## To Reproduce

1. c++ code running on a pytorch pt model 
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by mruberry** [comment]
I'm sorry, but without more information it's unclear what's going. It seems like your environment isn't configured properly. 

If you can provide your environment information, following the instructions above, as well as provide a snippet of code that reproduces your issue, plus a description of how you built PyTorch, then please reopen this issue.

**Comment by mruberry** [comment]
(You may also want to ask on the PyTorch forums at https://discuss.pytorch.org/ how to setup PyTorch for your needs.)

**Comment by forsener** [comment]
@mruberry never mind
