### ISSUE TITLE
Failed to convert quantized mobilenet to onnx

### ISSUE THREAD

**Issue by alohali** [pytorch/pytorch#29724]
use pytorch 1.3 and quant mobilenet successfully to int8
but I could not export it to onnx with errors:

```
QConfig(activation=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, reduce_range=True), weight=functools.partial(<class 'torch.quantization.observer.MinMaxObserver'>, dtype=torch.qint8, qscheme=torch.per_tensor_symmetric))
.ONNXint8
/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py:617: UserWarning: ONNX export failed on ATen operator quantize_per_tensor because torch.onnx.symbolic_opset9.quantize_per_tensor does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "static_quant.py", line 457, in <module>
    torch.onnx.export(myModel, dummy_input, "mv1quant.onnx")
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/alohali/.local/lib/python3.5/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'quantize_per_tensor'
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vincentqb** [comment]
Could you please copy and paste the output from our environment collection script?
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by alohali** [comment]
> /
@vincentqb 
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.2

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: GeForce RTX 2070

Nvidia driver version: 430.40
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1
[conda] Could not collect

**Comment by alohali** [comment]
@vincentqb any suggestions?

**Comment by vincentqb** [comment]
Thoughts @houseroad ?

**Comment by lara-hdr** [comment]
@alohali this PR enables tests for torchvision ONNX exports. Mobilenet (and quantized mobilenet) is exporting and the mobilenet test is passing https://github.com/pytorch/pytorch/pull/30121/files#diff-92f53f0d2694170082f0ad81bfc05604R196. 
You could try exporting like in this test. if it is still failing could you share the code you are using to export the model?

**Comment by lara-hdr** [comment]
@alohali my bad, I realized the "quantized" parameter defaults to False. I was able to reproduce the error when I set it to True. I'm looking into it.

**Comment by Merical** [comment]
@alohali Hi~ Working on the same issue here. Any Update?
Thanks.

**Comment by tensorbuffer** [comment]
@lara-hdr any update?

**Comment by jerryzh168** [comment]
cc @supriyar

**Comment by alohali** [comment]
> @alohali Hi~ Working on the same issue here. Any Update?
> Thanks.

hi  @Merical have not solved it.. waiting for update

**Comment by alohali** [comment]
> @alohali my bad, I realized the "quantized" parameter defaults to False. I was able to reproduce the error when I set it to True. I'm looking into it.

hi @lara-hdr , are you still woking on it? Have you figure out some way to solve it ?or in plan ?
@supriyar

**Comment by supriyar** [comment]
We currently have a flow to convert quantized operators from PyTorch to Caffe2 through ONNX. However this uses a caffe2 specific representation in ONNX as defined in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_caffe2.py

The regular pytorch -> onnx -> caffe2 conversion should work if the operators are supported. You will need to use `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK for the conversion`. For example -
```
def test_quantized_convert(self):
        torch.backends.quantized.engine = "qnnpack"
        module_quant = torch.jit.load("/home/pytorch/model_quantized.pt")
        x_numpy = np.random.random((2, 3, 8, 8)).astype("float32")
        X = torch.from_numpy(x_numpy)
        module_quant.eval()
        output = module_quant(X)
        torch.set_default_tensor_type(torch.FloatTensor)
        input_names = ["x"]
        f = io.BytesIO()
        torch.onnx.export(module_quant, (X), f, verbose=False, example_outputs=output, input_names=input_names, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=9)
        f.seek(0)
        onnx_model = onnx.load(f)
        sample_inputs = (
            x_numpy,
        )
        caffe_res = c2.run_model(onnx_model, dict(zip(input_names, sample_inputs)))[0]
        np.testing.assert_almost_equal(output.numpy(), caffe_res, decimal=3)
```

It currently supports a limited set of operators as defined in above file.

**Comment by reuvenperetz** [comment]
Hi,
I've tried @supriyar code when trying to convert the quantized version of mobilenetV2 (the one in torchvision) and I get the following error:

RuntimeError: isTensor() INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/core/ivalue_inl.h:90, please report a bug to PyTorch. Expected Tensor but got Int (toTensor at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/core/ivalue_inl.h:90)

Does anyone know why I get this message?
Thanks!

**Comment by linjieyangsc** [comment]
Hi, @supriyar @alohali. Is there any solid plan to support quantized model conversion to onnx? As far as I know TensorRT now supports inference with int8 arithmetics on some NVDIIA GPUs, and to convert pytorch model to tensorRT we have to go through onnx for now. It will be a great benefit if we can convert quantized pytorch models to onnx. Thanks!

**Comment by jerryzh168** [comment]
@linjieyangsc I think we might want to support that through graph mode quantization. cc @raghuramank100

**Comment by mhajiaghayi** [comment]
Hi @jerryzh168  and @supriyar 
I was also trying to convert a BERT dynamically quantized model to onnx but i got the following error. 

''ONNX export failed on quantized operator quantized::linear_dynamic because torch.onnx.symbolic_opset9.linear_dynamic does not exist.'' 
it seems ''dynamic quanitized'' linear operation in onnx:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#dynamicquantizelinear 
but i can't find the corresponding operator in 
torch/csrc/autograd/generated/VariableType.h to create a symbol function. It would be great to have a onnx support.

I also tried ''operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK'' for the conversion but that didn't help.

**Comment by codeislife99** [comment]
Hi, just bumping up this thread. I really need this feature as well. Please support this !

**Comment by supriyar** [comment]
@mhajiaghayi and @codeislife99 we currently do not plan to support dynamically quantized model through the onnx conversion flow. The only supported path through ONNX is to produce caffe2 quantized models as mentioned in https://github.com/pytorch/pytorch/issues/29724#issuecomment-575291115.

What is your final use-case or backend that you want to run on? If you plan to use this on TensorRT then graph-mode quantization has plans to support this flow.

**Comment by codeislife99** [comment]
HI @supriyar , my model will be run on mobile devices, so I wish to convert my Pytorch model --> ONNX --> TF --> TFLite.

**Comment by jerryzh168** [comment]
> HI @supriyar , my model will be run on mobile devices, so I wish to convert my Pytorch model --> ONNX --> TF --> TFLite.

PyTorch mobile is going to support running pytorch model on mobile devices natively. The onnx path is low pri for us.

**Comment by codeislife99** [comment]
I see what you are saying here. However, PyTorch mobile doesn't have the functionalities and all the advantages of TFLite yet from a product perspective and this is something that I have discussed with the PyTorch mobile team-members directly over Slack.

**Comment by pranav-prakash** [comment]
>What is your final use-case or backend that you want to run on? If you plan to use this on TensorRT then graph-mode quantization has plans to support this flow.

Another +1 for quantized onnx model export. Currently it does not seem there is *any* means of producing a quantized model aside from the post-training quantization scripts in the onnxruntime repo provided by Microsoft. While the set of official onnx quantized operators is limited (just QLinearConv and QLinearMatmul last I checked), adding support for at least these two along with the flexibility to define additional quantized operators (like e.g. a QLinearAdd) would make it easy to both run models out-of-the-box on onnxruntime as well as interop with various other frameworks that can consume onnx protos.

**Comment by neelakanth** [comment]
+1 for quantized model export onnx.

**Comment by neelakanth** [comment]
> We currently have a flow to convert quantized operators from PyTorch to Caffe2 through ONNX. However this uses a caffe2 specific representation in ONNX as defined in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_caffe2.py
> 
> The regular pytorch -> onnx -> caffe2 conversion should work if the operators are supported. You will need to use `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK for the conversion`. For example -
> 
> ```
> def test_quantized_convert(self):
>         torch.backends.quantized.engine = "qnnpack"
>         module_quant = torch.jit.load("/home/pytorch/model_quantized.pt")
>         x_numpy = np.random.random((2, 3, 8, 8)).astype("float32")
>         X = torch.from_numpy(x_numpy)
>         module_quant.eval()
>         output = module_quant(X)
>         torch.set_default_tensor_type(torch.FloatTensor)
>         input_names = ["x"]
>         f = io.BytesIO()
>         torch.onnx.export(module_quant, (X), f, verbose=False, example_outputs=output, input_names=input_names, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=9)
>         f.seek(0)
>         onnx_model = onnx.load(f)
>         sample_inputs = (
>             x_numpy,
>         )
>         caffe_res = c2.run_model(onnx_model, dict(zip(input_names, sample_inputs)))[0]
>         np.testing.assert_almost_equal(output.numpy(), caffe_res, decimal=3)
> ```
> 
> It currently supports a limited set of operators as defined in above file.

@supriyar I tried this method for resnet18 quant model (models.quantization.resnet18(pretrained=True, quantize=True))
and I am getting below error
RuntimeError: self.qscheme() == at::kPerTensorAffine INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022030672/work/aten/src/ATen/native/quantized/QTensor.cpp:162, please report a bug to PyTorch. clone for quantized Tensor only works for PerTensorAffine scheme right now

**Comment by supriyar** [comment]
@neelakanth at this point we have not tested this approach with many models and its usage is only limited to converting the model for caffe2 (though onnx). 
We're in the process of discussing the plan to support converting quantized pytorch operators to ONNX, but it is a much wider effort as currently ONNX runtime does not have full support for quantized operators. Once we have a plan this thread will be updated.

**Comment by pranav-prakash** [comment]
It's worth noting that onnxruntime has support for `contrib_ops` where the community can add operators that aren't officially part of the onnx spec yet. For instance, it appears `QLinearAdd` and some other arithmetic on quantized types is already defined (although the implementation for these seem to be missing). This might be one approach to at least get started and hopefully solve the chicken/egg issue of onnx community support.

**Comment by FzuGsr** [comment]
+1 for quantized model export onnx.

**Comment by daydayfun** [comment]
+1 for quantized model export onnx.

**Comment by hukv1990** [comment]
+1 for quantized model export onnx.

**Comment by hukv1990** [comment]
+1 for quantized model export onnx.
