### ISSUE TITLE
World After Load

### ISSUE THREAD

**Issue by myuanqing** [pytorch/pytorch#29725]
Hi. I'm a beginner and coming to ask for some help. I load a model into C ++ file and I attempt to read the weights in this model from the initialized torch::jit::script::Module, which is supposed to be a Tensor. However, I just don't know how. Is there any api to get the weights?

**Comment by vincentqb** [comment]
Please note that this issue tracker is not a help form and this issue will be closed. We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our [discussion forum](https://discuss.pytorch.org/).
