### ISSUE TITLE
Spammed by "Run failed" notifications as former contributor

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#29737]
In the past hour, I've started getting spammed with emails that look like this

```
Run failed for master (03d021d)

Repository: pytorch/pytorch
Workflow:
Duration: 0 seconds
Finished: 2019-11-13 18:10:17 UTC
```

I'm a former pytorch contributor, but these have nothing to do with me. How can I turn off these notifications?

cc @ezyang

**Comment by ailzhang** [comment]
Hi! if you go to `Setting` and `Notifications`, and uncheck all for `Github Actions` section, it should stop sending you emails.

**Comment by anderspapitto** [comment]
thanks @ailzhang , that will fix it for now. In the future I might want to turn these notifications back on for other repositories I'm actively contributing to, and unfortunately that setting is global. Can you also remove me from the pytorch-repo-specific list of who gets those notifications?

**Comment by ailzhang** [comment]
FYI @suo has a PR to fix it https://github.com/pytorch/pytorch/pull/29740. 
cc: @soumith might be able to help remove you from the pytorch repo?

**Comment by houseroad** [comment]
The fix has been landed. Feel free to turn the notifications back on. @anderspapitto

**Comment by vincentqb** [comment]
The issue seems to have been fixed, so I will close this issue. Please feel free to re-open if this is not the case.

**Comment by anderspapitto** [comment]
thanks all
