### ISSUE TITLE
How to add PyTorch to requirements.txt

### ISSUE THREAD

**Issue by econti** [pytorch/pytorch#29745]
I'm trying to include PyTorch in a requirements.txt file to be installed in a Docker container, but can't seem to get it to work. I've tried adding the following with no luck:

```
torch==1.3.1
> ERROR: Could not find a version that satisfies the requirement torch==1.3.1 (from -r /requirements/./base.txt (line 28))
```

```
torch==1.2.0+cpu
> Could not find a version that satisfies the requirement torch==1.2.0+cpu (from -r /requirements/./base.txt (line 28)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
```

How do you add PyTorch to requirements.txt?

**Comment by willwilliams** [comment]
Does this work?

`--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.2.0+cpu`

**Comment by econti** [comment]
Looks like this works:

```
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.3.1+cpu
```

Thanks for the help!

**Comment by oak-tree** [comment]
how do you add `torch` to `setup.py` as a requirement with `find-links`? Note that links_requierments has been deprecated from `pip`
