### ISSUE TITLE
CuDNN batchnorm has batch size limit for eval with channel

### ISSUE THREAD

**Issue by colinfang** [pytorch/pytorch#29744]
```
torch.backends.cudnn.version()
# 7603
torch.version.cuda
# 10.1.243
# pytorch version 1.3
```

```python
x = torch.rand(70000, 1, 2).cuda()

bn = nn.BatchNorm1d(1)
bn.cuda()
bn.eval()

xbn = bn(x)
xbn.size()

# RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

The above works if the batch size is 60000, or it is in training mode, or the input is 2d (no channel) instead of 3d.

#2917 might be related

cc @ngimel

**Comment by vincentqb** [comment]
Have you tried running your code with `.contiguous()` as in #2917? Have you tried running the same code as #2917?

```
import torch
import torch.nn as nn
from torch.autograd import Variable

torch.backends.cudnn.enabled=True
x = Variable(torch.rand(140000,1).contiguous()).cuda()

print (torch.backends.cudnn.version())

bn = nn.BatchNorm1d(1)
bn.cuda()

xbn = bn(x)
xbn.size()
```

For completeness, please copy and paste the output from our environment collection script:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ngimel** [comment]
cc: @csarofeen @ptrblck

**Comment by colinfang** [comment]
Code in #2917 runs well for me.

Switching to `x = torch.rand(70000, 1, 2).contiguous().cuda()` still triggers the same error.

```
python collect_env.py

Collecting environment information...
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN Xp
GPU 2: TITAN X (Pascal)
GPU 3: TITAN Xp

Nvidia driver version: 418.67
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.3

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch
```

I also have conda installed cudatoolkit with version   10.1.243  
BTW the cuDNN version is wrong above, I think pytorch binary comes with statically linked cudnn.

```
torch.backends.cudnn.version()
# 7603
```

**Comment by ngimel** [comment]
@csarofeen, @ptrblck can you please look up conditions under which cudnn can be used (in training/activation, in spatial/per_activation modes) and change the conditions in the pytorch code accordingly, so that it transparently falls to native implementation where cudnn can't be used?

**Comment by divyanshj16** [comment]
I can help in this issue, if someone points me where to look at?

**Comment by ptrblck** [comment]
@ngimel I've pushed an initial commit with updated size limitations and tested it with cudnn 7.6.5.32.
Based on the minimal CUDA version of 9.0, I assume the minimal cudnn version would be 7.1.4?

If that's the case, we might also update the cudnn version check in [line 472](https://github.com/ptrblck/pytorch/commit/4c5f048e7ad6242171512294a110bfc33abe2a77#diff-334eb235b4eb8d228fe544dbe506e3c7R472) and I'll retest it with older versions.

**Comment by colinfang** [comment]
@ptrblck  How did you come up with such magic numbers for the limits? Are they listed in cudnn manual or something?

**Comment by ngimel** [comment]
@ptrblck That's ok, binaries are built with cudnn 7.6, there's no need to specifically test older versions.
