### ISSUE TITLE
Different Dropout Result on CPU and GPU with Manual Seed 

### ISSUE THREAD

**Issue by Disiok** [pytorch/pytorch#2976]
While verifying the correctness of my model, I noticed that dropout performs differently on CPU and GPU even with a manual seed set (the same on CPU and GPU). 

Is this expected behaviour? Is there a way to make the results more deterministic?

**Comment by ngimel** [comment]
It is expected, CPU and GPU are using different RNG, so even with the same seed the generated sequences will be different.

**Comment by apaszke** [comment]
This is expected. A given manual seed gives you deterministic results within a single device. It would be too expensive to add a restriction that all devices should use the same PRNG.

**Comment by ezyang** [comment]
Making all CUDA devices and CPU devices use the same RNG state would certainly be expensive, but hypothetically, couldn't we reverse engineer the CUDA RNG algorithm and implement it bit-for-bit equivalently on CPU? Not saying we are going to, but this doesn't seem expensive, perf-wise.

**Comment by soumith** [comment]
@ezyang and then we have to maintain a reverse-engineering patch particular to each CUDA major version.

**Comment by soumith** [comment]
@ezyang and then we have to maintain a reverse-engineering patch particular to each CUDA major version.

**Comment by ezyang** [comment]
...which is why we shouldn't do it :)

**Comment by ngimel** [comment]
You don't have to reverse-engineer it, device side generation is header-only, so look in curand*h headers. But I agree, it does not seem worth doing.
