### ISSUE TITLE
No EmbeddingBag Functional

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#2979]
Hi,

It would be nice to have an EmbeddingBag functional implementation.

Thanks,
Shawn

**Comment by elanmart** [comment]
Hi @apaszke, 
I wanted to add this feature. I've also converted the `EmbeddingBag` to new style func:
https://github.com/elanmart/pytorch/pull/1 

I've moved the logic from `EmbeddingBag.forward` to `functional.embedding_bag`, is this OK? Can I create a similar PR in the `pytorch` repo?

**Comment by apaszke** [comment]
Sure, sounds good!
