### ISSUE TITLE
Model Loading issue in android

### ISSUE THREAD

**Issue by mohitranawat** [pytorch/pytorch#29806]
My model contains nn.Functional.interpolate layer and it is converted properly to .pt model using jit.
But Loading same model in android giving issues.
This is happening in case of interpolate layer only
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.0
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by supriyar** [comment]
Dupe of https://discuss.pytorch.org/t/model-loading-issue-in-android/60990.
@mohitranawat do you have a small repro that we can try out on our end to diagnose the problem better?

**Comment by mohitranawat** [comment]
hey @supriyar  do you want model and jit trace side repro or for android side also?

**Comment by supriyar** [comment]
Just the model should suffice. We can try loading it on mobile and running to see what the issue might be. cc @xta0

**Comment by mohitranawat** [comment]
@supriyar you can find the model here -
https://drive.google.com/file/d/1Ux_-Llp1bAALYyIsKYHC77qr5V370KMl/view?usp=sharing

**Comment by supriyar** [comment]
Hi @mohitranawat, I wasn't able to repro this error

Ran it using the cpp test script 
```
scripts/build_mobile.sh -DBUILD_BINARY=ON -DCMAKE_BUILD_TYPE=Debug

./build_mobile/bin/speed_benchmark_torch --model ~/Downloads/dummy_model.pt --input_dims "1,3,224,224" --input_type "float"
```
Runs fine without any errors.

Can you try this with pytorch build from source? One known issue is https://github.com/pytorch/pytorch/pull/30067 so you can patch it in your build.

**Comment by mohitranawat** [comment]
Hi @supriyar  I am getting this error while loading the model in android studio java.
The patch you shared is not relevant to me or I don't know where to patch it as it is in java.

**Comment by IvanKobzarev** [comment]
Hello @mohitranawat,
Mentioned patch was merged yesterday in master and it is included in our nightly android builds. To use them:
```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    ...
    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'
    ...
}
```
If you used nightlies, you might need gradle key `--refresh-dependencies` to be sure that it will not use cached version.

To check that the patch is included, 1.4.0 nightlies version should be >= 45
the latest nightly url:
https://oss.sonatype.org/service/local/repositories/snapshots/content/org/pytorch/pytorch_android/1.4.0-SNAPSHOT/pytorch_android-1.4.0-20191120.095738-45.aar

I checked your model manually with them - it works for me

**Comment by mohitranawat** [comment]
Thanks @IvanKobzarev it worked. 
Initially I was also doing same thing but that url is not working and build was not happening.

**Comment by cpluspluser** [comment]
hi @IvanKobzarev , I am getting this error while I use your method.
Can you help me ?

`2020-12-04 23:54:27.561 21305-21305/com.example.hc.digitalgesturerecognition E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.hc.digitalgesturerecognition, PID: 21305
    com.facebook.jni.CppException: open file failed, file path: file:///android_asset/Ves230_DCL_CPU.pt (FileAdapter at /var/lib/jenkins/workspace/caffe2/serialize/file_adapter.cc:11)
    (no backtrace available)
        at org.pytorch.NativePeer.initHybrid(Native Method)
        at org.pytorch.NativePeer.<init>(NativePeer.java:18)
        at org.pytorch.Module.load(Module.java:23)
        at com.example.hc.digitalgesturerecognition.CameraActivity$2.onImageAvailable(CameraActivity.java:266)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)`
