### ISSUE TITLE
Use non-system cuda path

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#29801]
How can I specify non-system cuda path for pytorch installation?
I mean a path other than /usr/local/cuda.

**Comment by ailzhang** [comment]
@mahmoodn I assume you are building from source right? 
Try setting `CUDA_HOME` env?

**Comment by ailzhang** [comment]
Since this is more like a question instead of bug report, I'm closing it via my answer above. Please feel free to post a follow up question in forum if that doesn't work for you. Thanks!

**Comment by mahmoodn** [comment]
Thanks. I asked that in forum but didn't get any reply.
