### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by paffell** [pytorch/pytorch#2985]
Hi,

I have built the Docker image successfully, but when I want to run a script, it crashes on import torch command. Here is the error:
`  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *`  
`  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
`
Can anyone help me with this?

**Comment by soumith** [comment]
you are trying to run a script that needs CUDA, but you dont seem to have the NVIDIA driver installed on your docker image. If you want to use docker + GPUs, you should use nvidia-docker and start from one of NVIDIA's base image.

**Comment by paffell** [comment]
Thanks for a very fast reply. I used this docker: nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04, which is used in the docker here so I assumed that I do not need to do anything else

**Comment by soumith** [comment]
you can use that, but you have to run the image with `nvidia-docker` command
