### ISSUE TITLE
Scatter is not Differentiable twice Error

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#2986]
I put forward this issue in the forum [link](https://discuss.pytorch.org/t/scatter-not-differentiable-twice/6354). Could someone suggest/help rectify/explain what could the problem be here?

In summary, `Scatter is not Differentiable twice` is an error that pops up when I use `.backward()`. More importantly, the error occurs only when `nn.parallel.DataParallel` is used.

**Comment by gchanan** [comment]
I replied on the forum.

**Comment by rafaelvalle** [comment]
@vishwakftw  did this fix your error?

**Comment by vishwakftw** [comment]
I didn't compile PyTorch from source. I just took their word for it.
