### ISSUE TITLE
Assignment of tensors in the c++ API does not work as expected

### ISSUE THREAD

**Issue by dbergh** [pytorch/pytorch#29895]
## 🐛 Bug
The following short program does not compile.

    #include "torch/torch.h"

    int main() {
        torch::Tensor tensor = torch::ones({2, 2});
        tensor.fill_(0); // OK
        tensor = 0; // Gives compile error
    }

## Expected behavior

I would expect both the expressions 'tensor.fill_(0)' and 'tensor = 0' to compile and that they would yield the same result.

Looking at the source code 'aten/src/ATen/TensorOperators.h' the selected assignment operator is defined as follows:

    inline Tensor & Tensor::operator=(Scalar v) && {
        return fill_(v);
    }

That is, it is only defined for rvalues on the lhs of the assignment. I do not understand the rationale behind this restriction.

## Environment

```
 - PyTorch Version: 1.3.1
 - OS: Linux
 - How you installed PyTorch:  https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.3.1.zip
 - Build command you used: cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch .. && make
```
I am building the sample program using the instructions in the [c++ api guide](https://pytorch.org/cppdocs/installing.html)

cc @yf225

**Comment by zou3519** [comment]
In python, 
```
foo = torch.tensor(12)
foo = 0
```
foo isn't a tensor anymore at the second call. Because of that, I'm not sure that the c++ API should have this behavior.

**Comment by yf225** [comment]
For the reason that @zou3519 detailed above, C++ API should not have this behavior, and we should use `tensor.fill_(0);` if we want to fill `tensor` with 0.
