### ISSUE TITLE
No module named fb

### ISSUE THREAD

**Issue by Dorozhko-Anton** [pytorch/pytorch#29896]
## To Reproduce

1. Just import 
```
from caffe2.quantization.server import utils as dnnlowp_utils
```

Error:
```
python3.7/site-packages/caffe2/quantization/server/utils.py in <module>
      7 import numpy as np
      8 from caffe2.python import core, utils
----> 9 from caffe2.python.fb import hardcode_scale_zp
     10 
     11 

ModuleNotFoundError: No module named 'caffe2.python.fb'
```

## Expected behavior

import succeeds

## Environment

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.10.1) 8.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch

**Comment by soumith** [comment]
it's been like this for a year. the caffe2 frontend is not supported, and going away. I am not entirely sure how long we'll even keep it exposed in master.

I'm closing this as a `wontfix`.
