### ISSUE TITLE
The second parameter "tgt" of Transformer in its function forward:

### ISSUE THREAD

**Issue by FANTASTPATR** [pytorch/pytorch#29969]
I'm not very sure that what is the parameter "tgt" means.
The document says it is the sequence of decoder. However, I have a question that since I have the sequence to decoder, thus I have the result of decoder, why do I have to use transformer for inferencing?
For example, I have a seq2seq task that translate "I love you" from English to Franch "Je t'aime", what is the parameter of "tgt"? 
Looking forward answering. Thanks!

**Comment by ngimel** [comment]
Please don't duplicate questions from forums here, and please ask questions on forums only. https://discuss.pytorch.org/t/the-second-parameter-tgt-of-transformer-in-its-function-forward/61195
