### ISSUE TITLE
Illegal instruction : 4

### ISSUE THREAD

**Issue by Tj85710** [pytorch/pytorch#29967]
## 🐛 Bug

Unable to run pytorch on an iMac 27 mid-2010 Intel Core i7.

## To Reproduce

[(base) iMac27:~ xxxxxx$ conda install --update-all pytorch torchvision -c pytorch

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/xxxxxx/miniconda3

  added / updated specs:
    - pytorch
    - torchvision

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.13.2                |   py37hb5b8e2f_0         218 KB
    pip-19.3.1                 |           py37_0         1.9 MB
    python-3.7.5               |       h359304d_0        18.1 MB
    ------------------------------------------------------------
                                           Total:        20.2 MB

The following NEW packages will be INSTALLED:

  pip                pkgs/main/osx-64::pip-19.3.1-py37_0
  wheel              pkgs/main/osx-64::wheel-0.33.6-py37_0

The following packages will be UPDATED:

  cffi                                1.13.1-py37hb5b8e2f_0 --> 1.13.2-py37hb5b8e2f_0
  python                                   3.7.3-h359304d_0 --> 3.7.5-h359304d_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
cffi-1.13.2          | 218 KB    | ##################################### | 100% 
pip-19.3.1           | 1.9 MB    | ##################################### | 100% 
python-3.7.5         | 18.1 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) iMac27:~ xxxxxx$ python3
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
**Illegal instruction: 4**

## Expected behavior
I want to play with torch...

## Environment

(base) iMac27:miniconda3 thierry$ python3 PyTorchGetEnv.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.8.1

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.3.1                   py3.7_0    pytorch
[conda] torchvision               0.4.2                  py37_cpu    pytorch
(base) iMac27:miniconda3 thierry$ 

## Additional context

Please, note that I had to remove the "import torch" instruction in your script to allow it to run properly. With this import, I get the "Illegal Instruction : 4" message as we could expect.

Remark : Does PyTorch use the Intel AVX instruction set ? If yes, this may be the cause of this error because my processor does not support them, too old...

Best regards, 

Thierry

**Comment by alessandro893** [comment]
Same problem (mac pro 5,1), how to disable AVX?

**Comment by ezyang** [comment]
I think this is the same problem as #27627. Can you please try a nightly and see if it resolves the problem?

**Comment by Tj85710** [comment]
YESSSSSS !!
Thanks a lot.

Here it is :

(base) iMac27:miniconda3 xxxxxx$ **conda install --update-all pytorch-nightly torchvision -c pytorch**
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/xxxxxx/miniconda3

  added / updated specs:
    - pytorch-nightly
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    **pytorch-nightly-1.0.0.dev20190328**|          py3.7_0        45.3 MB  pytorch
    tqdm-4.38.0                |             py_0          51 KB
    ------------------------------------------------------------
                                           Total:        45.4 MB

The following NEW packages will be INSTALLED:

  pytorch-nightly    pytorch/osx-64::pytorch-nightly-1.0.0.dev20190328-py3.7_0

The following packages will be UPDATED:

  tqdm                                          4.36.1-py_0 --> 4.38.0-py_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
pytorch-nightly-1.0. | 45.3 MB   | #################################################################################### | 100% 
tqdm-4.38.0          | 51 KB     | #################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) iMac27:miniconda3 xxxxxx$ python3
Python 3.7.5 (default, Oct 25 2019, 10:52:18) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 
(base) iMac27:miniconda3 xxxxxx$

**Comment by absentio** [comment]
I sitll get the same error even installing pytorch-nightly. Any solution?
