### ISSUE TITLE
Using PyTorch 0.5.0 with torchvision

### ISSUE THREAD

**Issue by gauravjain14** [pytorch/pytorch#29976]
I have been trying to get PyTorch 0.5 working with Torchvision. I know its pretty old but that's what I am supposed to work with due to using GPGPUSim. The torchvision version I have is 0.4.2.

When I try to do import torchvision, I get the following error:

File "/usr/local/lib/python3.5/site-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet

Is there a way to get around the version mismatch issue?

**Comment by ezyang** [comment]
It sounds like torchvision is using features of PyTorch that didn't exist in 0.5. You'll have to rewrite the relevant portions to use backward compatible bits. We won't be able to provide assistance.
