### ISSUE TITLE
Static Quantization: Get Error "RuntimeError: didn't find kernel to dispatch to for operator 'quantized:: conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch keys are [quantizedCPUTensorId](look up_at /pytorch/aten/src/ATen/core/dispatch/DispatchTable.h:249)"

### ISSUE THREAD

**Issue by YanZhiyuan0918** [pytorch/pytorch#29989]
## Problem Description

I want to do "Post-training static quantization" for my model. Steps to reproduce the behavior:

1. First, I run the demo on the official website, and it works well. The demo is on:
[https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html](url)
2. Second, I want to do static_quantization for my own model, just like the demo. The code I use are:
`myModel = load_model().to('CPU')`
`myModel.eval()`
`myModel.qconfig = torch.quantization.default`
`torch.quantization.prepare(myModel, inplace=True)`
`torch.quantization.convert(myModel, inplace=True)`

Then, I meet error here:
`RuntimeError: didn't find kernel to dispatch to for operator 'quantized:: conv2d'. Tried to look up kernel for dispatch key 'CPUTensorId'. Registered dispatch keys are [quantizedCPUTensorId](look up_at /pytorch/aten/src/ATen/core/dispatch/DispatchTable.h:249)`

## Expected behavior
Expected to understand the cause of the error and solve it.

## Environment
 - PyTorch Version: torch-1.3.1+cu100  torchvision-0.4.2+cu100
 - Linux
 - How you installed PyTorch (`pip`)
 - Anaconda  Python 3.5.2
 - CUDA/cuDNN version: cuda 10.0
 - GPU models and configuration: Nnidia 2080Ti

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by raghuramank100** [comment]
@YanZhiyuan0918 : It looks like you may not have inserted QuantStub() and DeQuantStub() at appropriate locations in your model. This is because the model is quantized, but the input tensor is not. 

Also, going forward, please post related questions to pytorch forums.  Closing this issue for now.
