### ISSUE TITLE
pytorch onnx exporter created an invalid model

### ISSUE THREAD

**Issue by aviaisr** [pytorch/pytorch#29993]
I exported a trained PyTorch model to onnx and the file was created but the model seems to be invalid. When I loaded the model and checked it I get the following validation error:

_onnx.checker.check_model(model_onnx)
File "C:\ProgramData\Anaconda3\lib\site-packages\onnx\checker.py", line 91, in check_model
C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec: input: "707" output: "714" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "value" f: 0 type: FLOAT }_

* I used these commands:
 torch.onnx.export(model, args=dummy_input, f=onnxFileName, training=False, opset_version=11)
model_onnx = onnx.load(onnxFileName)
onnx.checker.check_model(model_onnx)

It is possible that PyTorch exporter is doing the wrong thing.

I'm using PyTorch version 1.3.1.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by BowenBao** [comment]
@aviaisr Thanks for reporting this. There has been a PR fixing this issue (pad opset 11) that went in after the 1.3.1 release. https://github.com/pytorch/pytorch/pull/28225. Please try with PyTorch nightly to see if the issue is still there. Thanks.

**Comment by zhouzq-thu** [comment]
@BowenBao 

Same issue when setting `opset_version=11` with the latest PyTorch version and maybe add the following code to the `test` function:

```python
import torch
import torch.nn as nn
import onnx

path = 'converted.onnx'
dummy_input = torch.zeros((1, 3, 32, 32))
zp = nn.ZeroPad2d((0, 1, 0, 1))
torch.onnx.export(zp, dummy_input, path,
                  input_names=['input'], 
                  output_names=['output'],
                  opset_version=11,
                  verbose=False)
# check model
onnx_model = onnx.load(path)
onnx.checker.check_model(onnx_model)
```

The code above will produce the error:

```
Traceback (most recent call last):
  File "/media/zhouzq/Fast SSD/zhouzq_objdet/Darktorch/lab.py", line 17, in <module>
    onnx.checker.check_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 3 not in range [min=1, max=1].

==> Context: Bad node spec: input: "input" input: "22" input: "23" output: "output" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING }
```

## Environment

PyTorch version: 1.4.0a0+7495c25
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.15.5

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 430.50
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.4.0a0+7495c25
[pip3] torchsummary==1.5.1
[conda] Could not collect

**Comment by zhouzq-thu** [comment]
@BowenBao @lara-hdr @neginraoof 
After I update ONNX to 1.6.0, it's OK now, but does a single `ZeroPad2d` layer need so many ops? :)
Maybe it is good to add a feature that we can decide to export a static or dynamic ONNX model.

![converted](https://user-images.githubusercontent.com/9458157/69235150-b881c380-0bcb-11ea-84be-1925153b235e.png)

**Comment by aviaisr** [comment]
Thanks! It worked with pytorch-nightly, version 1.4.0.dev20191118!

**Comment by neginraoof** [comment]
@zhouzq-thu There's a difference between PyTorch and ONNX spec for pad. For PyTorch, pad tensor is in the following order: [dim_n_begin, dim_n_end, dim_n-1_begin, dim_n-1_end, ..., dim_m_begin, dim_m_end]
But the ONNX order is: [dim_0_begin, dim_1_begin, ... , dim_0_end, ..., dim_n_end]
Hence we have this subgraph to reshape the tensor.

**Comment by zhouzq-thu** [comment]
@neginraoof However, in most situations, the pad tensor is static, we can just reshape and permute it in numpy, not in the graph.

**Comment by manojbhatD** [comment]
Is there a way to avoid "Shape" in Zeropad2d? The onnx runtime onnxjs doesnt support Shape, so would it be okay to Change to Reshape somehow? Any idea of a solution?
Anyone please comment.
