### ISSUE TITLE
Pytorch1.3 for Android: Failed to transform artifact 'pytorch_android.aar' to match attributes

### ISSUE THREAD

**Issue by Joyako** [pytorch/pytorch#29990]
### I use  the '1.4.0-SNAPSHOT' and 'Pytorch-1.3.0',  my project  is OK in the first few week. But now I build my project when it can not sucess , I have not changed my project at all.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by xta0** [comment]
cc @IvanKobzarev

**Comment by IvanKobzarev** [comment]
Hello @Joyako ,

I checked our demo HelloWorldApp with the latest snapshots versions and it works:

```
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }

dependencies {
    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'
}
```

Before commit https://github.com/pytorch/pytorch/commit/8e3486de81d848e5c9a375134b3b14998ac36654 (which was landed today) we had a problem that our nightly builds included debug symbols and were quite big. 
I guess that this might be the reason of this gradle failure.

What is also suspicious that in error message you have 'to match attributes {artifactType=jar}.' while our artefact type is `aar`
Please check that you do not specify `aritfactType=jar` in gradle deps like `implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT@jar`, it should be:

    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'


If the failure does not disappear - please attach gradle output with `--debug --stacktrace` arguments

**Comment by Joyako** [comment]
Hello @IvanKobzarev I use 'implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'' and 'implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'' to my project, it can  normal compile, but in runtime , it is crash in Module.load() function, but it is  work use this way in first few week,  thanks any way.

**Comment by IvanKobzarev** [comment]
@Joyako 
What is the full error message you get?

Just guessing:
As you use nightly builds - you get the latest version of libtorch with all the changes of jit, serialization etc. So you need to regenerate your torchscript pt files (trace/script) to be aligned with the latest nightlies. (to install pytorch nightly from python for example and rerun python scripts that generate your models)
That might explain that it worked for you sometime, but after breaking changes in nightlies it will start failing with not-regenerated pt files.

**Comment by Joyako** [comment]
Hello @IvanKobzarev, my problem has solved , thanks a lot.As your said I update pytorch nightly from python and regenerate my torchscript pt, my project is running normally.Thanks again.
