### ISSUE TITLE
torch.HalfTensor object has no attribute sub_

### ISSUE THREAD

**Issue by ddkang** [pytorch/pytorch#2999]
Running the following code crashes with the following error:

```
import torch

t = torch.zeros(2, 2)
h = t.half()
h.sub_(h)
```

```
Traceback (most recent call last):
  File "pytorch_bug.py", line 5, in <module>
    h.sub_(h)
AttributeError: 'torch.HalfTensor' object has no attribute 'sub_'
```

**Comment by apaszke** [comment]
This is expected. We don't support math on CPU half tensors, because it's extremely slow. See e.g. [this comment by @fmassa](https://github.com/pytorch/pytorch/issues/2968#issuecomment-334470467). wontfix.

**Comment by ddkang** [comment]
This issue is the reason we would like CPU half tensor math support https://github.com/pytorch/pytorch/issues/2968 but happy to continue the discussion in that thread
