### ISSUE TITLE
[jit] Values of constants can't be accessed

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#30019]
Constant values are inlined in the graph without names, so they can't be accessed after compilation. This is a problem since a lot of `nn.Module`s are scripted using constants instead of attributes, so users have no way of accessing these values once they have scripted a module. 

```python
class M(nn.Module):
    __constants__ = ['my_const']
    def __init__(self):
        super().__init__()
        self.my_const = 2

    def forward(self, x):
        return x + self.my_const


sm = torch.jit.script(M())

# AttributeError: 'RecursiveScriptModule' object has no attribute 'my_const'
print(sm.my_const)
```

An easy fix would be to delete all the `__constants__` arrays in `torch/nn` so everything would be made into an attribute.

cc @suo

**Comment by suo** [comment]
@jerryzh168 is currently working on this

**Comment by jerryzh168** [comment]
Should be fixed now, can you try again?

**Comment by suo** [comment]
Let's close this out. @driazati won't mind :)

**Comment by alextrekov3307** [comment]
`AttributeError: 'RecursiveScriptModule' object has no attribute 'weight'`

How do you access the weights of a scripted model?
