### ISSUE TITLE
Remove `.api` from RPC API signature

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#30014]
The `remote`/`rpc_sync`/`rpc_async` APIs are listed as `torch.distributed.rpc.api.*` in our doc. The `.api` segment should not appear there.

![Screen Shot 2019-11-18 at 12 22 31 PM](https://user-images.githubusercontent.com/16999635/69074832-224c7280-09fe-11ea-9fa8-72ffc568ac60.png)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pritamdamania87** [comment]
Closing this since I believe #30160 resolves this (https://pytorch.org/docs/master/rpc.html#torch.distributed.rpc.remote)
