### ISSUE TITLE
Trying to do advanced indexing using a Variable causes a hang

### ISSUE THREAD

**Issue by futurulus** [pytorch/pytorch#3001]
**Minimal test case:**

    import torch
    x = torch.autograd.Variable(torch.FloatTensor([[0.1, 0.2], [0.3, 0.4]]))
    idx = torch.autograd.Variable(torch.LongTensor([1, 0]))
    print(x[idx, :])

**Expected output:**

Either:

    Variable containing:
     0.3000  0.4000
     0.1000  0.2000
    [torch.FloatTensor of size 2x2]

(the above is what is printed if I replace the last line with `print(x[idx])`)

...or an immediate exception traceback informing me that advanced indices must be a `Tensor` and not a `Variable`.

**Actual output:**

The program initially hangs. *After* I interrupt the program with ^C, the following exception is displayed:

    Traceback (most recent call last):
      File "loop.py", line 5, in <module>
        print(x[idx, :])
      File "/home/.../lib/python3.5/site-packages/torch/autograd/variable.py", line 76, in __getitem__
        return Index.apply(self, key)
      File "/home/.../lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 16, in forward
        result = i.index(ctx.index)
    IndexError: When performing advanced indexing the indexing objects must be LongTensors or convertible to LongTensors

**More details:**

From some digging around in pdb, it looked like [`Variable.__getitem__`](https://github.com/pytorch/pytorch/blob/master/torch/autograd/variable.py#L78) was tail-calling itself via C code. While I couldn't identify the full stack, it looks like it eventually made its way to [this attempt to convert the `Variable` index to a `LongTensor`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/Tensor.cpp#L785). Sure enough, this also hangs:

    torch.LongTensor(idx)

Perhaps the `LongTensor` constructor is trying to treat the `Variable` as a iterable, and getting stuck because iterating through a `Variable` returns a sequence of `Variables`? (Happy to dig further, if someone can point me to the logic for initializing a `LongTensor`.)

Python 3.5.2, GCC 5.4.0 on Linux, `torch.__version__` = '0.2.0_3', no CUDA

**Comment by futurulus** [comment]
Ah, it works on `master` for me too. Awesome.

This:

    torch.LongTensor(idx)

still spins for a while but eventually comes back with

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: already counted a million dimensions in a given sequence. Most likely your items are also sequences and there's no way to infer how many dimension should the tensor have

It seems natural to me that a Tensor constructor should know to reach into `.data` if it sees a Variable, but perhaps there are good reasons for it not to. In any case, there's an easy workaround (just use `idx.data` instead of `idx`) and a googlable error message.

Thanks for the quick reply!

**Comment by killeent** [comment]
@futurulus - just to be clear, you are talking about trying to create a `LongTensor` from `idx` which is a `LongTensor` wrapped in a `Variable`?

**Comment by futurulus** [comment]
Yes, exactly.

More realistically, I might not know whether `idx` is a list, numpy array, `LongTensor`, or `Variable`, but I need to create a `LongTensor` from it regardless. `torch.LongTensor(idx)` seems like an idiomatic way to do that, but currently if I expect the input might be a `Variable`, I need a special case.

**Comment by killeent** [comment]
@futurulus I see. With #2633 coming in the future I think it doesn't merit adding some special workaround for now, given that handling it in your code should be easy enough. However, we should not have a hang when passing unexpected inputs to the `LongTensor` constructor. I will take a look.

**Comment by soumith** [comment]
fixed via #3163
