### ISSUE TITLE
Cannot call rpc.init_rpc two distinct times.

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#30057]
## 🐛 Bug

After calling `rpc.init_rpc` and then `rpc.join_rpc`, if the user tries to re-initialize RPC, then they get the following error:

https://gist.github.com/rohan-varma/e6c3fa16a6bc3d838755a7408a0a603f

It seems that the `DistAutogradContainer` is not destroyed, and thus there is an attempt to initialize it twice.

## To Reproduce

Run the following script:
https://gist.github.com/rohan-varma/72ea94d98480afa9e2e79067bcfecb9b

## Expected behavior

The user should be able to `init_rpc` more than once, or we should explicitly warn against this.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pritamdamania87** [comment]
Is there a valid use-case for calling `init_rpc` more than once? I think it should be reasonable to expect that the user should call init_rpc only once and then join_rpc once.
