### ISSUE TITLE
 Pytorch 1.3 cuda 10 driver 410.48 not available

### ISSUE THREAD

**Issue by lk1983823** [pytorch/pytorch#30071]
I have cuda 10 and driver version 410.48 installed followed the instruction of Nividia with a .deb installation. When I use torch 1.2, it can detect my gpu, however, torch 1.3 fails. Can any one help?
Thanks!
```
import torch
torch.cuda.is_available()
false
```

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): Linux  Ubuntu16.04 kernel 4.4.0.98 
 - How you installed PyTorch (`conda`, `pip`, source): pip install 
 - Build command you used (if compiling from source): no
 - Python version: 3.6.7
 - CUDA/cuDNN version: cuda 10 /  cudnn 7.6.0
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ngimel

**Comment by zhirihuixin** [comment]
I have the same question, please help, thanks!

```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp
GPU 4: TITAN Xp
GPU 5: TITAN Xp
GPU 6: TITAN Xp
GPU 7: TITAN Xp

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect
```

**Comment by zhirihuixin** [comment]
python3.5 and pytorch1.1 is OK
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp
GPU 4: TITAN Xp
GPU 5: TITAN Xp
GPU 6: TITAN Xp
GPU 7: TITAN Xp

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect
```

**Comment by ngimel** [comment]
@zhirihuixin Please refer to table 1 here, for cuda 10.1 (which is cuda version used to build pytorch 1.3, according to your output, you need driver version 418.39 or later. 
You can install pytorch for cuda 10 using command 
```
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
```
to install pytorch compiled with cuda 10 that should run on your system. 
@lk1983823 can you please check which cuda version was used to compile pytorch and which cuda driver you have? (you can use script to collect your environment https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py).

**Comment by zhirihuixin** [comment]
@ngimel Thank your very much! I solved this problem by reinstall pytorch1.3.1(torch-1.3.1+cu100-cp36-cp36m-linux_x86_64.whl) for cuda 10.0, The command (pip install torch) is for cuda 10.1.

```
PyTorch version: 1.3.1+cu100
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp
GPU 4: TITAN Xp
GPU 5: TITAN Xp
GPU 6: TITAN Xp
GPU 7: TITAN Xp

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1+cu100
[pip3] torchvision==0.4.2+cu100
[conda] Could not collect

```

**Comment by lk1983823** [comment]
@ngimel Thank you !!

> @zhirihuixin Please refer to table 1 here, for cuda 10.1 (which is cuda version used to build pytorch 1.3, according to your output, you need driver version 418.39 or later.
> You can install pytorch for cuda 10 using command
> 
> ```
> conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
> ```
> 
> to install pytorch compiled with cuda 10 that should run on your system.
> @lk1983823 can you please check which cuda version was used to compile pytorch and which cuda driver you have? (you can use script to collect your environment https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py).
