### ISSUE TITLE
LibTorch(C++) with Cuda is raising an exception

### ISSUE THREAD

**Issue by Andrej-sens** [pytorch/pytorch#30076]
I am trying to create NN with LibTorch 1.3 and C++ using Cuda 10.1 and Windows 10. For the build I am using Visual Studio 2019.

So far I tried basic examples and [MNIST example][1] with CPU which is working. However I cannot run it with CUDA. I tried to move model to GPU as it is described [here][2], but it is not working. 

> To move your model to GPU memory, you can write model.to(at::kCUDA);. Make sure the inputs to a model are also living in CUDA memory by calling tensor.to(at::kCUDA), which will return a new tensor in CUDA memory.

So I tried just simple

    int main(){
        auto net = std::make_shared<Net>();
        net->to(torch::kCUDA); //crashes here
    }

Then I tried to move simple Tensors to gpu memory but it crashes as well.

    #include <torch/torch.h>

    int main() 
    {
	    torch::Tensor a = torch::ones({ 2, 2 }, torch::requires_grad());
	    torch::Tensor b = torch::randn({ 2, 2 });
	    a.to(torch::kCUDA);    //Here it crashes
	    b.to(torch::kCUDA);    //
	    auto c = a + b;
    }

and I got:

    Exception thrown at 0x00007FFB8263A839 in Resnet50.exe: Microsoft C++ exception: c10::Error at memory location 0x000000E574979F30.
    Unhandled exception at 0x00007FFB8263A839 in Resnet50.exe: Microsoft C++ exception: c10::Error at memory location 0x000000E574979F30.

In debug mode it is pointing to `KernelBase.dll` to

    auto operator()(Parameters... args) -> decltype(std::declval<FuncType>()(std::forward<Parameters>(args)...)) {
      return kernel_func_(std::forward<Parameters>(args)...);
    }

Using `torch::cuda::is_available()` shows it can find cuda device. 

Therefore I decided to build it from source but I it's not working either. It's related to [this](https://github.com/pytorch/pytorch/issues/30075#issue-525005329) post.

  [1]: https://pytorch.org/cppdocs/frontend.html#end-to-end-example
  [2]: https://pytorch.org/tutorials/advanced/cpp_export.html#step-4-executing-the-script-module-in-c

**Comment by peterjc123** [comment]
We fixed a similar bug in https://github.com/pytorch/pytorch/issues/22681. Please use the nightly build or build from source.

**Comment by Andrej-sens** [comment]
Current nightly verison causing same error again.

**Comment by peterjc123** [comment]
@Andrej-sens Maybe related to https://github.com/pytorch/pytorch/issues/31611.

**Comment by Andrej-sens** [comment]
Yes, that's the case. Thank you.
