### ISSUE TITLE
CUDA Memory Leak in torch.qr

### ISSUE THREAD

**Issue by chrischoy** [pytorch/pytorch#3009]
It seems like the function `torch.qr` leaks memory.
I'm using `torch.__version__`  0.2.0_4 on anaconda python 3.6 CUDA 8.0 using the standard conda installation.

```
import torch
B = torch.rand(4000, 1000).cuda()   # nvidia-smi output 298MiB
_ = torch.qr(B)   # 388MiB
for i in range(100): torch.qr(B)  # Constantly increases until 1941MiB
```

So the memory footprint increases up to 1.9G though each `qr` takes about 100M.
compared to `svd` where it takes up more memory but doesn't leak memory and the memory foot print fluctuates between 414M and 432M and back to 414M.

```
import torch
B = torch.rand(4000, 1000).cuda()   # nvidia-smi output 298MiB
_ = torch.svd(B)   # 399MiB
for i in range(100): torch.svd(B)  # fluctuates between 414 to 432 and back to 414
```

Aside from that, is there a reason for using Magma instead of cuBLAS?

**Comment by colesbury** [comment]
Thanks for catching this! Looks like we're leaking `a`:

https://github.com/pytorch/pytorch/commit/91a118c116d15d280a99a39666d298be15c6d592

I think at the time we added the Magma bindings cuBLAS didn't provide a QR solver. I'm not sure there's any reason to prefer it now.
