### ISSUE TITLE
Nuke local UserRRefs when shutting down RPC

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#30105]
This issue is created based on discussion with @jjlilley and @zzzwen. @pritamdamania87  and @aazzolini and I also encountered similar struggle in #30022 and https://github.com/pytorch/examples/pull/662

Currently, application code needs to make sure there is no reference to `UserRRef` before calling `join_rpc()`, otherwise, those `UserRRef`s will be held alive by the application code and won't send messages to deref `OwnerRRef`. This would result in RRef leak errors. In our test and examples, we solve this by putting test/example code that involves RRefs into a separate function, and only call `join_rpc()` after exiting the function. When exiting the function scope, Python GC would deref the `UserRRef` is most cases. However, there are at least two problems with this approach:

1. Behavior is unclear when there are circular dependencies.
2. When the application code becomes complex, it is hard to track all RRefs and make sure they are de-referenced before calling `join_rpc()`. It would be a pain for application developers to debug and find dangling RRefs. 

### Proposal

Let's have a new arg in `join_rpc()/shutdown()` or even having a new API to specify whether we should nuke all local UserRRefs during shutdown. We can do this by:

1. Keep a `weak_ptr` to all `UserRRefs` in `RRefContext`, and use those to kill `UserRRef`s if necessary.
2. If `UserRRef` is destructed after nuke, do nothing. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by rohan-varma** [comment]
There's also no guarantee that the python GC would garbage collect the reference by the time we want it to, correct?

**Comment by mrshenli** [comment]
> There's also no guarantee that the python GC would garbage collect the reference by the time we want it to, correct?

Yes, based on yesterday's discussion, we are going ignore those RRef leaks at shutdown time, because shutdown means the application no longer cares about the local state. We would still enforce leak checking for tests though, to make sure that `OwnerRRef`s are indeed deleted properly. see #30217

**Comment by mrshenli** [comment]
closed by #31893
