### ISSUE TITLE
Binding Variable methods/functions in native_functions.yaml is awkward due to AutoNonVariableTypeMode

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#30102]
Right now, some "Variable" functions are bound using `native_functions.yaml`, and some are not.  For example, `Tensor::view()` is manually bound on the Variable class, but `Tensor::backward()` is bound using `native_functions.yaml`. I thought, for uniformity sake, it would be better if all of these functions were bound on `native_functions.yaml`. But I cannot conveniently do this: when I do, https://github.com/ezyang/pytorch/commit/162e888329de0f6a7424249fa3745b0bb9f11f30 it fails with:

```
RuntimeError: is_view is not implemented for Tensor
```

The problem seems to be that my implementation strategy, which is defining an implementation on `VariableType` and then having it manually be registered as VariableTensorId, will result in a registered kernel that won't get called if variable mode is disabled. Being able to skip the variable implementation is desirable in the case of a function like add(), but for functions which have no reasonable non-variable implementation, like `backward`, we ought NOT to respect NonVariableTypeMode.

Does this mean we need a separate dispatch key for non toggleable variable implementations? Or maybe these should just be registered as composite ops. See also #29548

cc @yf225

**Comment by smessmer** [comment]
register them to the compound op key?

**Comment by ezyang** [comment]
@smessmer Yes, I think that would fix it.

**Comment by smessmer** [comment]
This issue is the background to why https://github.com/pytorch/pytorch/pull/29934 broke torchvision and got reverted. I'm working on it.

**Comment by smessmer** [comment]
see https://github.com/pytorch/pytorch/pull/30649

**Comment by smessmer** [comment]
fixed. cc @ezyang
