### ISSUE TITLE
Add proper destructor to ProcessGroupAgent

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#30127]
## 🚀 Feature
In some cases there are failures and the user cannot shutdown the RPC Agent through the RPC API. In this case, we should implement a destructor for ProcessGroupAgent that tries to call the `shutdown` routine to shutdown the agent cleanly.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pietern** [comment]
The forced shutdown won't be clean, right?

**Comment by rohan-varma** [comment]
@pietern, correct, now that we have a shutdown function, we can call it with `graceful=False`, anad it will not do a sync.

**Comment by rohan-varma** [comment]
This was done in https://github.com/pytorch/pytorch/pull/31023/files
