### ISSUE TITLE
calculate grad error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#30129]
my code as below:
```
import torch

x = torch.ones([1], requires_grad=True) # weight
w = torch.tensor([0.2], requires_grad=True) # lr

def f(x):
    x = x.cuda()
    return torch.pow(x, 2).sum()

def SGD(grad, lr=0.2):
    return -lr*grad

def optimizer(grad):
    return -w*grad

sum_losses = 0
for i in range(3):
    loss = f(x)
    sum_losses += loss
    loss.backward(torch.ones_like(loss), retain_graph=True)
    print('x.grad: {}'.format(x.grad))
    print('w1.grad: {}'.format(w.grad))

    update = optimizer(x.grad)
    x = x + update
    print('x-:{}'.format(x))
    print('x-.grad: {}'.format(x.grad))

    x.retain_grad()
    update.retain_grad()

sum_losses.backward()
print('w.grad: {}'.format(w.grad))

w_update = SGD(w.grad, lr=0.1)
w = w + w_update
print('w====: {}'.format(w))
```
In 0.4.0, the output is
```
x====: tensor([ 1.])
w====: tensor([ 0.2000])
x.grad: tensor([ 2.])
w1.grad: None
x-:tensor([ 0.6000])
x-.grad: None
x.grad: tensor([ 1.2000])
w1.grad: tensor([-2.4000])
x-:tensor([ 0.3600])
x-.grad: None
x.grad: tensor([ 0.7200])
w1.grad: tensor([-5.5680])
x-:tensor([ 0.2160])
x-.grad: None
w.grad: tensor([-13.9584])
w====: tensor([ 1.5958])
```
In pytorch 1.1.0, the result is 
```
x====: tensor([1.], requires_grad=True)
w====: tensor([0.2000], requires_grad=True)
x.grad: tensor([2.])
w1.grad: None
x-:tensor([0.6000], grad_fn=<AddBackward0>)
x-.grad: None
x.grad: tensor([1.2000])
w1.grad: tensor([-3.8400]) xxx
x-:tensor([0.3600], grad_fn=<AddBackward0>)
x-.grad: None
x.grad: tensor([0.7200])
w1.grad: tensor([-7.5264]) xxx
x-:tensor([0.2160], grad_fn=<AddBackward0>)
x-.grad: None
w.grad: tensor([-15.9168]) xxx
w====: tensor([1.7917], grad_fn=<AddBackward0>)
```
The grad of `w` and `w1` is different in different pytorch version, the different places marked by `xxx`.

In pytorch 1.2.0, the program report error:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
I fix thiserror by delete `x = x + update`, but report other error due to the `w.grad` is None, I add `w.retain_grad` the error still exist.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by as754770178** [comment]
`x = x + update` is after `backward`, not between calculate loss and backward, such as after calcalating loss and before backward.

**Comment by as754770178** [comment]
`x = x + update` is after backward, not between calculate loss and backward, such as after calcalating loss and before backward. Whether report the error?

**Comment by as754770178** [comment]
`x = x + update` is after backward, not between calculate loss and backward, such as after calculating loss and before backward. Whether report the error?

**Comment by cpuhrsch** [comment]
Hello @as754770178 - have you considered migrating to a newer version of PyTorch?

**Comment by SsnL** [comment]
What is the relation between this issue and https://github.com/pytorch/pytorch/issues/30073?

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by as754770178** [comment]
@cpuhrsch It's important I want to know why. otherwise, I can't write the code, because I can't promise the code is right. If you kown, please tell me. Thanks

**Comment by albanD** [comment]
The answer is both in the issue that is linked by @SsnL  and the forum post.

Also you already posted this code twice in the forum and this is the second issue here with the exact same code.
Please make sure to read the previous answers. If you have follow up question about the answer, ask them where the answer was given.
Thanks

**Comment by as754770178** [comment]
sorry, I don't know my friend submmit the issue.
