### ISSUE TITLE
RuntimeError: isTensor() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/core/ivalue_inl.h:90, please report a bug to PyTorch. Expected Tensor but got Int (toTensor at /pytorch/aten/src/ATen/core/ivalue_inl.h:90)

### ISSUE THREAD

**Issue by amajidsinar** [pytorch/pytorch#30139]
So, what I'm trying to do is to to convert torchscript model into onnx. Both scripting and tracing works during the creation of graph, but fails when the model is converted into onnx

Here's the error:

> 
Traceback (most recent call last):
  File "yolo2script.py", line 8, in <module>
    torch.onnx.export(model_scripted, dummy_input, "yolov3.onnx", example_outputs=model(dummy_input))
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 235, in _model_to_graph
    method_graph, params = model.forward._lowered_graph()
RuntimeError: isTensor() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/core/ivalue_inl.h:90, please report a bug to PyTorch. Expected Tensor but got Int (toTensor at /pytorch/aten/src/ATen/core/ivalue_inl.h:90)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f83210f0813 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1876251 (0x7f82bdc7d251 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: torch::jit::script::Method::_lowered_graph() + 0x161 (0x7f82c0420771 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x5af698 (0x7f832229b698 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2110f4 (0x7f8321efd0f4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #6: python3() [0x4f88ba]
frame #8: python3() [0x4f6128]
frame #9: python3() [0x4f7d60]
frame #10: python3() [0x4f876d]
frame #12: python3() [0x4f6128]
frame #13: python3() [0x4f7d60]
frame #14: python3() [0x4f876d]
frame #16: python3() [0x4f6128]
frame #17: python3() [0x4f7d60]
frame #18: python3() [0x4f876d]
frame #20: python3() [0x4f6128]
frame #21: python3() [0x4f7d60]
frame #22: python3() [0x4f876d]
frame #24: python3() [0x4f6128]
frame #26: python3() [0x6415b2]
frame #31: __libc_start_main + 0xe7 (0x7f83267afb97 in /lib/x86_64-linux-gnu/libc.so.6)

Here's my system:

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.16.0-rc3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1060 with Max-Q Design
Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.4.0
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torch2trt==0.0.2
[pip3] torchetl==0.3.9
[pip3] torchvision==0.4.2
[conda] Could not collect

If you need the model source code, I will provide it to you asap. Thank you !

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by YesXiamo** [comment]
I met the same error

**Comment by julianmack** [comment]
I have the same error - did you find a workaround?

**Comment by Oktai15** [comment]
I have the same problem

**Comment by riyadshairi979** [comment]
any solution on this? having the same problem!

**Comment by thevooght** [comment]
I'm also having this problem. Found no solution yet.
My code worked several days ago, it failed after a connection break while testing.

**Comment by leimao** [comment]
Got similar problems using PyTorch '1.5.0a0+8f84ded'

**Comment by thevooght** [comment]
I'm not sure, but I think I solved this error by rerunning the code. 
I used a Google Compute Engine and sometimes it gave an error.
If this does not work, maybe upgrade the memory you're using or use more gpu's.

**Comment by leimao** [comment]
> I'm not sure, but I think I solved this error by rerunning the code.
> I used a Google Compute Engine and sometimes it gave an error.
> If this does not work, maybe upgrade the memory you're using or use more gpu's.

This is peculiar. My model is extremely small (10MB), and I was using V100 GPU. In principle, it should not be a GPU problem.

**Comment by Oktai15** [comment]
This thread maybe helps you: https://github.com/pytorch/pytorch/issues/35293

**Comment by thevooght** [comment]
Indeed @leimao . That cannot be the problem in that case. Hope the comment above helps you further.

**Comment by tsaizhenling** [comment]
I tried making similar changes to my models as #35293 but it didn't help :(

**Comment by ares89** [comment]
I have the same error

**Comment by kjdorow7** [comment]
I too have the same error.

**Comment by jbmaxwell** [comment]
I'm seeing this error when running a traced model with LibTorch on iOS.

**Comment by swithmn1** [comment]
I have the same problem

**Comment by garymm** [comment]
This issue is not actionable without reproduction instructions, and it's quite old, so closing.
If you are still having problems:
1. Please try on the latest nightly PyTorch
2. If it's not fixed there, please open a new issue with full reproduction instructions, ideally in a colab notebook

Thanks!

**Comment by 0pow0** [comment]
I solved this by remove first dimension (which is batch). For example, I have shape (1, 3, 5) as input, I changed it to (3, 5) and it works :rofl:

**Comment by mrcghil** [comment]
For those still affected by this, I solved the problem after adding annotations to all the models used in the layers. In my case, there were many custom layers and I noticed that I missed checking the annotations on one of them.
