### ISSUE TITLE
DataLoader fails to re-raise exceptions with required arguments

### ISSUE THREAD

**Issue by samsamoa** [pytorch/pytorch#30147]
## 🐛 Bug
`torch.utils.data.DataLoader` attempts to relay exceptions from its child processes.  It fails to do this when the exception type takes multiple required arguments.

## To Reproduce

Run this:
```
import torch.utils.data
class E(Exception):
    def __init__(self, a, b):
        pass
    def __str__(self):
        return "Special exception message"

class G(torch.utils.data.IterableDataset):
    def __iter__(self):
        raise E(a=1, b=2)
        yield 1
    
d = torch.utils.data.DataLoader(G(), num_workers=1)
next(iter(d))
```

The result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'b'
```

## Expected behavior

Should see the `E: Special exception message` printed. (This works when `num_workers=0`.)

## Environment
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux

cc @SsnL

**Comment by cpuhrsch** [comment]
I'm going to assign myself to keep track of this, but it's unlikely we'll get to around to do this. I'll also let @SsnL comment on this.

**Comment by vadimkantorov** [comment]
previously reported seemingly the same issue: https://github.com/pytorch/pytorch/issues/25522

**Comment by andrewjong** [comment]
This is a problem for me; if my dataloader fails to load a certain file, I want to print the path to know which file it was. But I can't do that because intercepting and reraising exceptions doesn't work.

**Comment by gibiansky** [comment]
Hi there, is there any progress on this issue? I'm hitting this right now and it's pretty tricky to debug.

**Comment by samsamoa** [comment]
fixed by https://github.com/pytorch/pytorch/pull/58131
