### ISSUE TITLE
LibTorch. Namespaces bug.

### ISSUE THREAD

**Issue by 421psh** [pytorch/pytorch#30158]
## 🐛 Bug

Loads of errors during C++ code compilation due to problems with namespaces in LibTorch files.

## What helped
Changes in files:

1. libtorch/include/ATen/detail/CUDAHooksInterface.h 
26 line:
```
namespace at {
using c10::Allocator;	///Changed manually
```
2. libtorch/include/ATen/core/TensorBody.h
35 line: 
```
namespace at {
 using c10::Scalar; ///Changed manually
```
## Environment
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: Quadro M2000
Nvidia driver version: 410.48
cuDNN version: /usr/local/cuda-9.2/lib64/libcudnn.so.7

## Additional context

It would be great not to have this bug in future versions because original file code change is not the best method of creating robust software. Maybe it is possible to prevent this issue using some commands but I don't know them.

cc @yf225

**Comment by yf225** [comment]
@421psh Could you elaborate what errors you saw in your C++ code compilation?

**Comment by 421psh** [comment]
I suppos I managed to solve my problem. There was a conflict between my namespaces in some other files and Libtorch namespaces. That's why there were so many errors like:
```
../../libtorch/include/ATen/Functions.h:922:46: error: ‘Scalar’ has not been declared
 static inline Tensor ge(const Tensor & self, Scalar other);
                                              ^~~~~~
../../libtorch/include/ATen/Functions.h:925:66: error: reference to ‘Scalar’ is ambiguous
 static inline Tensor & le_out(Tensor & out, const Tensor & self, Scalar other);
```

**Comment by zhongqingyang** [comment]
hi,Can you tell me your solution

**Comment by zhongqingyang** [comment]
> > 我想我设法解决了我的问题。我在其他一些文件中的命名空间与 Libtorch 命名空间之间存在冲突。这就是为什么有这么多错误，例如：
> > ```
> > ../../libtorch/include/ATen/Functions.h:922:46: error: ‘Scalar’ has not been declared
> >  static inline Tensor ge(const Tensor & self, Scalar other);
> >                                               ^~~~~~
> > ../../libtorch/include/ATen/Functions.h:925:66: error: reference to ‘Scalar’ is ambiguous
> >  static inline Tensor & le_out(Tensor & out, const Tensor & self, Scalar other);
> > ```
> 
> 同样的问题，你能分享你解决这个问题的方法吗？

Delete the using namespace from your code

**Comment by GeneralJing** [comment]
already solved. thank you.

**Comment by zxl152723** [comment]
I encountered the following issues during the compilation process. How can I resolve them?
`libtorch/include/ATen/core/DeprecatedTypeProperties.h:37:3: error: reference to ‘DeviceType’ is ambiguous
   37 |   DeviceType device_type() const`

**Comment by cabranca** [comment]
I've recently had the same error, there was an amiguity between cv::Allocator and c10::Allocator. I was able to solve it withouth touching the libtorch files, just changing the inclusion order of the headers that led to each Allocator inclusion. Hope this helps.
