### ISSUE TITLE
fp16 fails to speed up HRNet

### ISSUE THREAD

**Issue by taojake** [pytorch/pytorch#30151]
## ❓ Questions and Help
fp16 can't spped up on HRNet
### Please note that this issue tracker is not a help form and this issue will be closed.
ubuntu16.04
pytorch1.1
cuda10.0
cudnn7.5
driver410.78
HRNetw32

inference with fp32:
44.31ms
inference with fp32:
50.40ms

hrnet is pose model, which is full of connection between different blocks, there are many for operation, and + operation(python operation in network, not torch.add()).
I want to know:
1. whether the for operation impacts the running time;
2. whether there are data type transferring in tensor+tensor operation;

thanks a lot.

cc @VitalyFedyunin @ngimel @mruberry

**Comment by cpuhrsch** [comment]
Hello @taojake - could you post the code with this model and show the commands you use to time this plus the hardware environment this ran in? Thank you!

**Comment by taojake** [comment]
first, some words are wrong:
inference with fp32:
44.31ms
inference with fp16:
50.40ms


then, the model code is from https://github.com/leoxiaobin/deep-high-resolution-net.pytorch/blob/master/lib/models/pose_hrnet.py, only output channels are different.

i just apply half() on model class and input data, my hardware is 2080Ti and 1080Ti, but i only use 2080Ti with CUDA_VISIBLE_DEVICES flag.

**Comment by mruberry** [comment]
@mcarilli @csarofeen

**Comment by ptrblck** [comment]
@taojake Could you post the `config` you were using for your experiments?
Also shapes of inputs would be helpful to get a reproducible script.

**Comment by taojake** [comment]
@ptrblck I think it is cuda's issue, when i remove 1080Ti from my server, when 1080Ti can't support fp16 mode, the inference time can speed up about 40%. So, this issue can be closed.
