### ISSUE TITLE
CUDA initialization hangs on CUDA 9

### ISSUE THREAD

**Issue by dogancan** [pytorch/pytorch#3018]
I just installed pytorch HEAD from source with cuda 9 and cudnn 7 using gcc 5.4 on ubuntu 16.04. It seemed to build and install without issue, however the python process hangs if I try to move a tensor to gpu using the cuda method. The following snippet also hangs.

```python
import torch

torch._C._cuda_init()
```

There are 2 Maxwell Titan X and 2 Pascal 1080 Ti cards attached to the machine.

**Comment by ngimel** [comment]
Did you build with magma conda package? If so, try building without it, magma conda package is built with cuda 8 and conflicts with pytorch when it is built with cuda 9.

**Comment by dogancan** [comment]
Yes, that was the problem. Thanks!

**Comment by smoussa** [comment]
Will not installing the magma package affect computational performance?

**Comment by apaszke** [comment]
Magma is not used to boost the performance. It's only that without it some linear algebra functions (linear system solvers, Cholesky decomposition, and similar) will not work. You won't find any difference unless you use those.

**Comment by vickylance** [comment]
@dogancan  Hi, can I know how to built without conda?
