### ISSUE TITLE
CPU scaling issue

### ISSUE THREAD

**Issue by loudinthecloud** [pytorch/pytorch#3021]
Platform: c4.4xlarge EC2 instance (16 vCPUs)
OS: Fedora cloud 26-1.5
Version: PyTorch v0.2.0

Description:
Running 4 workloads on all cores is x8 slower than pinning each workload to 4 different cpus.

How-to reproduce:
```
git clone git@github.com:loudinthecloud/pytorch-ntm.git
git checkout d08291fac4dccaa3c8d081bad06802d9e4d737ea
sudo pip3 install -r requirements
```

The following yields 220 ms/sequence (while not utilizing the CPUs fully):
```
taskset -c 0-3 ./train.py --seed 5 --checkpoint-interval 0
taskset -c 4-7 ./train.py --seed 50 --checkpoint-interval 0
taskset -c 8-11 ./train.py --seed 500 --checkpoint-interval 0
taskset -c 12-15 ./train.py --seed 5000 --checkpoint-interval 0
```

The following yields 1850 ms/sequence:
```
./train.py --seed 5 --checkpoint-interval 0
./train.py --seed 50 --checkpoint-interval 0
./train.py --seed 500 --checkpoint-interval 0
./train.py --seed 5000 --checkpoint-interval 0
```
And moreover, all the CPUs are 100% utilized...

Motivation:
I wanted to scale training on multi-core systems, a single workload not utilized the cpus fully, so I thought about utilizing the rest of the resources by running multiple workloads.

**Comment by apaszke** [comment]
It's probably just a cache issue. If you restrict programs to a subset of CPUs, they won't stomp on each other caches. Additionally, OMP might be detecting this and reducing paralellism. Can you try setting `OMP_NUM_THREADS=4 MKL_NUM_THREADS=4` and run these 4 processes without pinning them to any cores?

**Comment by loudinthecloud** [comment]
[perf.hist.16cores.txt](https://github.com/pytorch/pytorch/files/1368316/perf.hist.16cores.txt)

[perf.hist.4cores.txt](https://github.com/pytorch/pytorch/files/1368311/perf.hist.4cores.txt)
[perf.hist.16cores.txt](https://github.com/pytorch/pytorch/files/1368312/perf.hist.16cores.txt)

I executed 4 workloads on the first 4 cores and it worked fine (performance as in a single workload).
```
taskset -c 0-3 ./train.py --seed 5 --checkpoint-interval 0
taskset -c 0-3 ./train.py --seed 50 --checkpoint-interval 0
taskset -c 0-3 ./train.py --seed 500 --checkpoint-interval 0
taskset -c 0-3 ./train.py --seed 5000 --checkpoint-interval 0
```
The scaling issue happens when running the workloads on all 16 cores.
Attached are the histograms of "perf top" during both tests.

[perf.hist.4cores.txt](https://github.com/pytorch/pytorch/files/1368315/perf.hist.4cores.txt)
[perf.hist.16cores.txt](https://github.com/pytorch/pytorch/files/1368317/perf.hist.16cores.txt)

That's the output for the 16 cores execution:

```
  18.56%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f062
  18.04%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f05e
  15.30%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f3a2
  14.88%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f39e
  12.09%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f05c
  10.16%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f39c
   3.64%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f058
   2.94%  libgomp-ae56ecdc.so.1.0.0                   [.] 0x000000000000f398
   0.23%  libpython3.6m.so.1.0                        [.] _PyEval_EvalFrameDefault
   0.16%  libc-2.25.so                                [.] _int_malloc
   0.13%  libc-2.25.so                                [.] _int_free
   0.13%  [kernel]                                    [k] finish_task_switch
   0.12%  libc-2.25.so                                [.] malloc
   0.10%  libpython3.6m.so.1.0                        [.] _PyType_Lookup
   0.10%  [kernel]                                    [k] _raw_spin_unlock_irqrestore
   0.06%  libpython3.6m.so.1.0                        [.] _PyObject_GenericGetAttrWithDict
   0.05%  libpython3.6m.so.1.0                        [.] PyObject_Malloc
   0.05%  libc-2.25.so                                [.] malloc_consolidate.part.1
   0.05%  libpython3.6m.so.1.0                        [.] PyTuple_New
   0.05%  libpython3.6m.so.1.0                        [.] _init
   0.04%  libc-2.25.so                                [.] free
```

**Comment by mruberry** [comment]
Closing due to age. @loudinthecloud, please file a new issue if you're still seeing this behavior.

**Comment by seuwins** [comment]
> Closing due to age. @loudinthecloud, please file a new issue if you're still seeing this behavior.

I met same problem recently，if here is a rootcause，I will be appreciate. thanks
My question：https://github.com/pytorch/pytorch/issues/57618
