### ISSUE TITLE
cost more video memory than the sum of the input and the output tensor of the func in checkpoint 

### ISSUE THREAD

**Issue by balde-soul** [pytorch/pytorch#30213]
![2019-11-21_110927](https://user-images.githubusercontent.com/22140223/69301105-19eb7600-0c50-11ea-8306-d1108002f2ac.png)

base on the code in the picture,  I set the break point hard upon every checkpoint calling(in the second cell.forward function)
the memory should be growth in 75M in every step in the rolling theoretically, but 400M actually.

**[Untitled.txt](https://github.com/pytorch/pytorch/files/3872664/Untitled.txt)
this file is the code from jupyter, I rename it to .txt**

**the env:**
pytorch 1.2.0+cu92
cuda 10.0
cudnn: major 7 minor 6
python 3.5.6
plaform: ubuntu16  kenel: ubuntu 4.4.0-21-generic
numpy 1.16.3

Thanks!

cc @VitalyFedyunin @ngimel @mruberry

**Comment by cpuhrsch** [comment]
Hello @bado-lee - thanks for posting this! Could you create a smaller Python script to reproduce this issue?

Also there are a few things about your code that surprise me.
a) Why do you use "checkpoint" within the forward instead of applying it to the model?
b) Why do you use numpy zeros instead of [torch.zeros](https://pytorch.org/docs/master/torch.html#torch.zeros)?
c) Why do you call 'pass' these many additional times?

How do you measure how much memory your program uses?

**Comment by balde-soul** [comment]
> Hello @bado-lee - thanks for posting this! Could you create a smaller Python script to reproduce this issue?
> 
> Also there are a few things about your code that surprise me.
> a) Why do you use "checkpoint" within the forward instead of applying it to the model?
> b) Why do you use numpy zeros instead of [torch.zeros](https://pytorch.org/docs/master/torch.html#torch.zeros)?
> c) Why do you call 'pass' these many additional times?
> 
> How do you measure how much memory your program uses?

Sorry for the mistake I have made！the memory I mean is video memory.
a) Is there any error of the using of checkpoint?
b) Does it make any difference...
c) Coding habits....

I think what checkpoint doing is recording the Input and the output, so only the input and output would be remain in the video memory.  the input and output are all in dimension: 500x500x420(please take a look at the last cell in the picture)

**Comment by balde-soul** [comment]
> Hello @bado-lee - thanks for posting this! Could you create a smaller Python script to reproduce this issue?
> 
> Also there are a few things about your code that surprise me.
> a) Why do you use "checkpoint" within the forward instead of applying it to the model?
> b) Why do you use numpy zeros instead of [torch.zeros](https://pytorch.org/docs/master/torch.html#torch.zeros)?
> c) Why do you call 'pass' these many additional times?
> 
> How do you measure how much memory your program uses?

**Comment by cpuhrsch** [comment]
@balde-soul - I saw you closed this issue, should it be reopened?
