### ISSUE TITLE
Add support for fusion of relu6 with conv and bn for quantization

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#30214]
## 🚀 Feature
 Add support for fusing nn.ReLU6  with Conv and BN. 
## Motivation
 Xraymobile and mobilenet models use ReLU6 instead of ReLU. It will be convenient for quantization to directly support ReLU6. Currently ReLU6 module can be quantized, but not fused.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by ggeor84** [comment]
any update on this?

**Comment by zetyquickly** [comment]
Is it possible to adopt such fusing without modifying qnnpack and fbgemm libraries?

**Comment by jerryzh168** [comment]
> Is it possible to adopt such fusing without modifying qnnpack and fbgemm libraries?

I think so, we can implement a fused op without using fbgemm/qnnpack, although the implementation might be slower than implementing this in fbgemm/qnnpack.

**Comment by z-a-f** [comment]
> > Is it possible to adopt such fusing without modifying qnnpack and fbgemm libraries?
> 
> I think so, we can implement a fused op without using fbgemm/qnnpack, although the implementation might be slower than implementing this in fbgemm/qnnpack.

I agree that implementing the fused version might make it slower, unless we modify the backend kernels.

This issue was deprioritized. If there is a need for it, I will implement this after the 08/23
