### ISSUE TITLE
[discussion] conj() method copy/nocopy semantics for real tensors

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#30237]
It seems to copy:
```python
import torch
a = torch.rand(3, 3)
print(a.data_ptr(), a.conj().data_ptr()) # 94290110120192 94290110120320
```

However, if the caller wants to save memory for real tensors and does not use inplace ops, they need to do ifs (and enumerate all complex types) like in https://github.com/pytorch/pytorch/pull/29488/files#diff-62a3ecc69398a4b080599d5222c535b1R70

Also this copy semantics seems not documented: https://pytorch.org/docs/master/torch.html?highlight=conj#torch.conj

cc @VitalyFedyunin @ngimel @mruberry

**Comment by VitalyFedyunin** [comment]
Im not sure we want this kind of copy avoiding optimization is it will be BC-breaking. Plus there are many cases when we do such copy, take ` x.pow(1) ` as example.

**Comment by vadimkantorov** [comment]
Then maybe add to docs "For real tensors, conj returns a copy of the original tensor" or sth similar?

**Comment by vadimkantorov** [comment]
Also, there as an interesting example of `.to(copy=False|True)` argument that allows avoiding copy if the result is already of the good type / on the good device.

**Comment by VitalyFedyunin** [comment]
We are ready to update docs.

**Comment by anjali411** [comment]
closing this issue as it has been fixed. `conj()` no longer returns a copy for real tensors as documented here: https://pytorch.org/docs/1.7.0/generated/torch.conj.html?highlight=conj#torch.conj
```
>>> a = torch.rand(3, 3)
>>> print(a.data_ptr(), a.conj().data_ptr())
94486024130176 94486024130176
```
