### ISSUE TITLE
pytorch-1.4.0a0+f7b12a9 with cuda-10.2 requires libnvrtc.so.10.1 (from cuda-10.1)

### ISSUE THREAD

**Issue by sailfish009** [pytorch/pytorch#30236]
## 🐛 Bug

Installed cuda-10.2 in ubuntu-19.10, run simple mnist.py example from pytorch dist.
get error like below.

However, if i install cuda-nvrtc-10-1 (10.1.243-1) and symbolic link library file within cuda-10.2/lib64,
then the problem go away. 
sudo ln -s /usr/local/cuda-10.1/lib64/libnvrtc.so.10.1.243 /usr/local/cuda/lib64/libnvrtc.so.10.1

why i need cuda-nvrtc-10-1, although i got whole cuda-10-2?

```
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/pin_memory.py", line 31, in _pin_memory_loop
    data = pin_memory(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return [pin_memory(sample) for sample in data]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <listcomp>
    return [pin_memory(sample) for sample in data]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: Error in dlopen or dlsym: /usr/local/cuda/lib64/libnvrtc.so.10.1: version `libnvrtc.so.10.1' not found (required by /usr/local/lib/python3.7/dist-packages/torch/lib/libcaffe2_nvrtc.so)
```

## To Reproduce

1. run simple mnist.py with python3.7

## Expected behavior

some training process...
Train Epoch: 1 [0/60000 (0%)]	Loss: 2.303910
Train Epoch: 1 [640/60000 (1%)]	Loss: 1.157159
Train Epoch: 1 [1280/60000 (2%)]	Loss: 0.648621
Train Epoch: 1 [1920/60000 (3%)]	Loss: 0.507434
Train Epoch: 1 [2560/60000 (4%)]	Loss: 0.615822
...

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0a0+f7b12a9
 - OS (e.g., Linux): ubuntu 19.10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): CC=gcc-8 CXX=g++-8 python3 ./setup.py install
 - Python version:3.7.5rc1
 - CUDA/cuDNN version: 7.6.5.31-1+cuda10.2
 - GPU models and configuration: rtx2060
 - Any other relevant information:

**Comment by cpuhrsch** [comment]
@sailfish009 - you can look at the [environment variables](https://github.com/pytorch/pytorch/blob/master/cmake/Modules_CUDA_fix/upstream/FindCUDA.cmake#L29) within the FindCUDA module. It should be possible for you to specify a path to the runtime you want to link against without using symlinks. We don't distribute for 10.1 and 10.1/10.2 are likely not ABI compatible, so you'll need to compile from source (which you're already doing).

Let me know how it goes.

**Comment by sailfish009** [comment]
i found that if previous nvrtc version exist(ubuntu apt package c state) and build pytorch source result this bug.
i purged nvrtc 10.1, and rebuild source and tested mnist is ok.
