### ISSUE TITLE
[feature request] dtype.is_complex field

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#30238]
`dtype.is_complex` would simplify checks like https://github.com/pytorch/pytorch/pull/29488/files#diff-62a3ecc69398a4b080599d5222c535b1R70 (and `dtype.is_floating_point` already exists)

**Comment by cpuhrsch** [comment]
@vadimkantorov - thanks for creating the issue. I'm flagging this for triage review in case this concept of "is_floating_point" is not current anymore and we're supposed to use something else. Otherwise I think we'd be willing to accept a PR since this appears small to me. Thanks.

**Comment by vadimkantorov** [comment]
There's a very recently added `dtype.is_signed`: https://github.com/pytorch/pytorch/issues/29475

**Comment by VitalyFedyunin** [comment]
Sure, we are ready to accept PR implementing it. Please make sure it is similar to numpy if they support it.

**Comment by vadimkantorov** [comment]
For context: numpy instead of a property defined on dtype has np.iscomplex and np.isreal: https://docs.scipy.org/doc/numpy/reference/generated/numpy.iscomplex.html

**Comment by vadimkantorov** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/33175
