### ISSUE TITLE
cpp frontend torch::nll_loss2d  Crash 

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/pytorch#30231]
## To Reproduce

If do not enter the following target as kLong, it will crash but no message will be generated.

```c++
  std::cout << "NLL Example" << std::endl;

  constexpr int kBatchSize = 1;
  at::Tensor net_output =
      torch::log_softmax(torch::randn({kBatchSize, 2, 300, 300}), /*dim=*/1);
  std::cout << "Log softmax succeeded" << std::endl;

  at::Tensor ground_truth = torch::ones({kBatchSize, 300, 300}).to(at::kF32); // this type Crash 
  std::cout << "Ground truth created" << std::endl;

  try {
    at::Tensor loss = torch::nll_loss(net_output, ground_truth);
  } catch (const std::exception& e) {
    std::cout << "Exception occured\n" << e.what() << std::endl;
    exit(-1);
  }
  std::cout << "Done" << std::endl;
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (1.3.1):
 - OS (Windows10):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 10.2 , cuDNN Lastupdate
 - GPU models and configuration: RTX 2080
 - Any other relevant information:

**Comment by peterjc123** [comment]
Would you please try the nightly build?

**Comment by kerry-Cho** [comment]
thanks.
In nightly builds, a message appears.
Often there are no messages on the cpp frontend.

^^
```
NLL Example
Log softmax succeeded
Ground truth created
Exception occured
expected scalar type Long but found Float (data_ptr at C:/w/1/s/windows/pytorch/build/build/aten/src\ATen/core/TensorMethods.h:6321)
(no backtrace available)
```
