### ISSUE TITLE
Feature Request: Scheduler should be able to load and save state dictionaries

### ISSUE THREAD

**Issue by crazyoscarchang** [pytorch/pytorch#3026]
We can load and save state dictionaries for optimizers. It would be helpful if we have that for learning rate schedulers as well.

**Comment by MaigoAkisame** [comment]
Just ran into the same problem. Running `torch.save(scheduler, filename)` produces the following error:
`cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed`
I'll appreciate it if I could save the state_dict of a scheduler.

**Comment by JakobHavtorn** [comment]
Definitely a +1 on this one from me.

However, a simple workaround might be to simply keep track of the epoch index during training (as many probably do anyway). If training is halted only to be resumed later, the lr_scheduler can be loaded into its previous state simply by reinstatiating it and then setting the last_epoch property. 

It appears that `self.last_epoch` is the only "state" of most learning rate schedulers

`
last_epoch_trained_upon = 42
lr_scheduler = optim.ExponentialLRS(optimizer, gamma=0.99)
lr_scheduler.last_epoch = last_epoch_trained_upon
`

**Comment by ArmenAg** [comment]
I've been using pytorch since it's inception both at work and personally. I am trying to start contributing. I can pick up this task.

Should we save the optimizers state dict in the schedulers state dict @apaszke?
