### ISSUE TITLE
Some error using caffe2.python.onnx.backend in pytorchv1.3

### ISSUE THREAD

**Issue by qjchen1972** [pytorch/pytorch#30289]
There was an error converting the pytorch model to caffe2.
some error info:

File "/root/audio/trainer/onnx_proc.py", line 47, in create_caffe2_model
    rep = backend.prepare(model, device="CPU")
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 713, in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/onnx/backend.py", line 876, in _onnx_model_to_caffe2_net
    onnx_model = onnx.utils.polish_model(onnx_model)
  File "/root/anaconda3/lib/python3.7/site-packages/onnx/utils.py", line 21, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/root/anaconda3/lib/python3.7/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at
---------------------
In fact, caffe2 runs twice as fast as libtorch, so I've been using caffe2 as a deployment, What are some good suggestions for using libtorch?

model size:
ibtorch  --- 2188004 byte 
caffe2 ---  init.net(2363465) + predict_net(58536) = 2422001  byte

time:
input dim is 1 1  160 160 
 size is  1, ans is 0.520016 
caffe2 time = 138885 

 size is  1, ans is 0.520012 
libtorch time = 257761

**Comment by ifedan** [comment]
Please, provide: Steps To Reproduce, Expected behavior and Environment for this issue. And feel free to reopen it again.

**Comment by spandantiwari** [comment]
@ifedan - a quick comment: one thing to try, if you are using the latest PyTorch 1.3 or up, is to set `keep_initializers_as_inputs=True` when exporting your model.

**Comment by qjchen1972** [comment]
> @ifedan - a quick comment: one thing to try, if you are using the latest PyTorch 1.3 or up, is to set keep_initializers_as_inputs=True when exporting your model.

thanks.  set keep_initializers_as_inputs=True, it is OK!
torch.onnx.export(self.model,
                          dummy_input,
                          model_path,
                          verbose=True,
                          input_names=input_names,
                          output_names=output_names,
                          keep_initializers_as_inputs=True)
