### ISSUE TITLE
Windows debug build failure

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#30296]
## 🐛 Bug

```
variable.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl at::impl::VariableHooksRegisterer::VariableHooksRegisterer(struct at::impl::VariableHooksInterface *)" (__imp_??0VariableHooksRegisterer@impl@at@@QEAA@PEAUVariableHooksInterface@12@@Z) referenced in function "void __cdecl torch::autograd::`dynamic initializer for 'registerVariableHooks''(void)" (??__EregisterVariableHooks@autograd@torch@@YAXXZ)
```
More details could be found [here](https://dev.azure.com/pytorch/PyTorch/_build/results?buildId=18306).

## To Reproduce

1. `set DEBUG=1`
2. `python tools/build_libtorch.py`

## Expected behavior

Build pass.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): e3334723b2a423b100213af58e73590dc63229d8
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python tools/build_libtorch.py`
 - Python version: NaN
 - CUDA/cuDNN version: None / 9.2 / 10.1
 - GPU models and configuration: M60
 - Any other relevant information:

## Additional context

cc @peterjc123

**Comment by peterjc123** [comment]
It seems to be related to https://github.com/pytorch/pytorch/pull/28287. cc @ezyang

**Comment by ezyang** [comment]
Probably not enough CAFFE2_API annotations. I'll take a look today
