### ISSUE TITLE
building pytorch without CUDA

### ISSUE THREAD

**Issue by abdmabdullah** [pytorch/pytorch#3030]
Hi
I've been trying to build PyTorch without CUDA so that it uses CPU only. I'm trying to run FlowNet for PyTorch. I exported the NO_CUDA=1 variable but when I run the code it outputs a note that says I need to purchase an NVIDIA GPU. And the calls to CUDA due to which I get the said output are from torch files, not from the FlowNet code files.
Can anybody help me out?
Thanks

**Comment by SsnL** [comment]
Could you copy & paste your command and outputs you see here? It would help us identify the issue better.

**Comment by soumith** [comment]
the problem is that the [FlowNet code](https://github.com/ClementPinard/FlowNetPytorch) NEEDS cuda, they haven't written a non-cuda version
