### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib Referenced from: /usr/local/bin/sccache

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#30321]
All OS X builds are failing due to this https://app.circleci.com/jobs/github/pytorch/pytorch/3698524

CircleCI ticket: https://support.circleci.com/hc/en-us/requests/63093

**Comment by ezyang** [comment]
From CircleCI:

> From an initial look, usually the error message you mentioned is due to openssl not being installed and can usually be rectified by installing from homebrew: brew install openssl. Try giving this a go as a temporary workaround while we investigate this issue further.

**Comment by albanD** [comment]
The test machines did not had libssl1.0.0 anymore for some reason.
Recompiled sccache to statically package libssl to avoid this issue in the future.

**Comment by ezyang** [comment]
Another useful thing to do is to copy paste the commands you ran to bbuild for future reference :>

**Comment by albanD** [comment]
For future reference, the binary is build from the master branch of https://github.com/yf225/sccache (to support nvcc).
You can get the statically linked version with:
```
export OPENSSL_STATIC=yes
cargo build --features=s3 --release
```

This flag is not advertised in the old version of the repo we compile but it does work.

**Comment by ezyang** [comment]
For posterity this is what CircleCI responded with:

----

We have looked into this issue and have found that this is being caused by a dependency conflict.

To install libomp requires the following dependencies (taken from the build log):

==> Installing dependencies for libomp: pkg-config, gdbm, openssl@1.1, readline, sqlite, xz, python, sphinx-doc and cmake
This package is specifically installing OpenSSL 1.1 and higher. When homebrew installs OpenSSL, it will change the symlinks in 
/usr/local/opt/openssl/ to point to the latest version (which truly resides in 
/usr/local/opt/openssl@1.1). This in turns means the file 
/usr/local/opt/openssl/lib/libssl.1.0.0.dylib is no longer in that directory as it has been replaced by 
libssl.1.1.dylib.

The previous version of OpenSSL (1.0) can be found in 
/usr/local/opt/openssl@1.0/ which is where the previous version of the dylib, which is trying to be used, can be found (libssl.1.0.0.dylib).

Your script seems to be using something that is trying to specifically use this version of the dylib. Best practise would be to instead use 
/usr/local/opt/openssl/lib/libssl.dylib which will always point to the latest version of openssl as it is not requesting a specific version. You may need to check the dependencies of the packages you are using and make sure to pin specific versions of these packages to prevent this kind of conflict.

Do you know if any packages you use have been updated recently?
