### ISSUE TITLE
Speed-up per channel fake quantization implementation

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#30349]
## 🚀 Per-channel fake quantization has a for loop that can be parallelized.  The current implementation can be improved: 
https://discuss.pytorch.org/t/quantization-aware-training-extremely-slow-on-gpu/58894/5
Using a parallel for construct in Aten should speed-up the implementation.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by raghuramank100** [comment]
Parallel Aten implementation does not show a speedup under all shapes. Specifically for typical shapes of weights, the parallel implementation is slower. So, this is not a viable path to speed up fake-quant.

**Comment by jerryzh168** [comment]
Can you first benchmark to see where the time is spent?
