### ISSUE TITLE
Speed up calculateQparams for per-channel observers

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#30348]
## Pitch
CalculateQparams gets called every forward with QAT. Speeding this up speeds up quantization aware training. 
Details are at:
https://discuss.pytorch.org/t/quantization-aware-training-extremely-slow-on-gpu/58894/5

Specifically, the task is to remove https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L119 and instead enhance https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L157 to process per-channel calculations directly without needing a for loop.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by hx89** [comment]
PR put up: https://github.com/pytorch/pytorch/pull/30485

**Comment by vkuzo** [comment]
thanks for fixing this, @hx89!
