### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by shersoni610** [pytorch/pytorch#30376]
Hello,

I am trying to install pytorch on ubuntu 18.04 with Cuda10.1 installed.

I am giving the following command:

conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(kaolin)@blackhole:$ 

But after running an application: I get the following message:

    faces = torch.from_numpy(np.vstack(faces).astype(np.int32)).cuda() - 1
RuntimeError: CUDA error: no kernel image is available for execution on the device

Where should I looking for a solution?

Thanks

**Comment by peterjc123** [comment]
We have kicked out support for CC 3.5 GPU cards. You may have to downgrade torch or build it from source.

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions. Thanks
