### ISSUE TITLE
The guidelines for loading a PyTorch model in C++ do not work on Windows

### ISSUE THREAD

**Issue by puhach** [pytorch/pytorch#30379]
## ❓ Issue

Building a minimal C++ application which loads a torch script model results in:
`LINK : fatal error LNK1181: cannot open input file 'torch-NOTFOUND.obj'`

## Reproduce

Follow the guidelines from PyTorch documentation ([this ](https://pytorch.org/tutorials/advanced/cpp_export.html) and [this](https://pytorch.org/cppdocs/installing.html#minimal-example)). 

The issue occurs when executing the following commands:
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
cmake --build .
```

The first guide says to run `cmake make`, which does not work for Visual Studio at all.

Building succeeds on condition that Release configuration is specified:
`cmake --build . --config Release`. Other configurations (MinSizeRel, RelWithDebInfo and the default one fail with the aforementioned linker error).

## Environment

LibTorch 1.3 stable, release, CPU
Windows 8.1 x64
Visual Studio 2019 Community (with CMake component installed)

**Comment by peterjc123** [comment]
I'll fix the docs first.

**Comment by back2yes** [comment]
How can I build the minimal project in Debug mode?

**Comment by back2yes** [comment]
> 
> 
> How can I build the minimal project in Debug mode?

Following the instructions at https://stackoverflow.com/questions/59006561/using-a-pytorch-model-in-c-application-on-windows I finnally managed to make it work in _Debug_ mode.

**Comment by peterjc123** [comment]
You'll need to copy the PDBs along with your executable.

**Comment by back2yes** [comment]
> 
> 
> You'll need to copy the PDBs along with your executable.

Exactly, thanks a lot

**Comment by leoluopy** [comment]
I meet the same problem and found that you can download the debug version of libtorch in the official web site
