### ISSUE TITLE
Meta file not found or corrupted.

### ISSUE THREAD

**Issue by BarakBat** [pytorch/pytorch#30383]
Hi, I'm writing this support issue after I got no answer from the forum:
[https://discuss.pytorch.org/t/imagenet-meta-file-not-found-while-using-torchbench/61356]
My problem is as follows:
I'm trying to run the following simple code:
```
import torchvision.datasets as datasets
input_transform = None

imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
```
This returns:

> Traceback (most recent call last):
  File "test_imagenet.py", line 4, in <module>
    imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 56, in __init__
    wnid_to_classes = self._load_meta_file()[0]
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 108, in _load_meta_file
    "You can use download=True to create it.")
RuntimeError: ('Meta file not found or corrupted.', 'You can use download=True to create it.')

When I'm trying to do "download=True", I'm getting another error, but let's leave it aside since I don't want to download the dataset anyway.

I'll be happy for some help to understand what I am missing.

Thanks.

**Comment by goodclass** [comment]
wget https://github.com/goodclass/PythonAI/raw/master/imagenet/ILSVRC2012_devkit_t12.tar.gz

**Comment by BarakBat** [comment]
Can you please explain, what is missing, what are you proposing and how to use it?

**Comment by goodclass** [comment]
Maybe the link address is invalid Configure new addresses to download and create
datasets.imagenet.ARCHIVE_DICT['devkit']['url'] = "https://github.com/goodclass/PythonAI/raw/master/imagenet/ILSVRC2012_devkit_t12.tar.gz"

**Comment by BarakBat** [comment]
Is this what you mean:
`import torchvision.datasets as datasets
input_transform = None
datasets.imagenet.ARCHIVE_DICT['devkit']['url'] = "https://github.com/goodclass/PythonAI/raw/master/imagenet/ILSVRC2012_devkit_t12.tar.gz"
imagenet = datasets.ImageNet("/dataset-imagenet-ilsvrc2012/", split="val", transform=input_transform, target_transform=None, download=False)`

**Comment by izdeby** [comment]
Sorry, we ask users to use forum for questions. I see that you got no answer there but i will have to close this issue.

**Comment by BarakBat** [comment]
If no one knows what's wrong, this is a bug. thanks.
