### ISSUE TITLE
F.interpolate ONNX export logic change

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#30393]
## 🐛 Bug

a simple and stupid model:

```python
class TinyModel(nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        self.expander = nn.Conv2d(3, 192, 1, 1)

        # upsample cause Gather error
        self.P4_upsampled = nn.Upsample(scale_factor=2, mode='nearest')

    def forward(self, x):
        x = self.expander(x)
        # a = self.P4_upsampled(x)  

        sh = torch.tensor(x.shape[-2:])
        print(sh)
        # a = F.interpolate(x, (sh[0]*2, sh[1]*2))
        a = F.interpolate(x, (544, 1920))
        return a


def export_onnx():
    model = TinyModel().to(device)
    sample_input = torch.rand(1, 3, 544, 1920).to(device)
    model.eval()
    torch.onnx.export(model, sample_input, model_p, input_names=[
                      'img'], output_names=['values'], opset_version=11)
    print('onnx model exported. forward now...')
    # forward now


if __name__ == "__main__":
    export_onnx()

```

I want to export to onnx and convert to tensorrt, so the same operation which is simply Upsampling I need change written format to fit it.

Currently, if export specific opset to 10, it generates a graph like this:

![image](https://user-images.githubusercontent.com/21303438/69511368-c1cbb100-0f7a-11ea-9063-3ef6521ca181.png)

This one can be exported and converted to tensorrt.

While we have lots of features relies on onnx opset11, so we have to using opset11, but in opset11, it generates graph like this:

![image](https://user-images.githubusercontent.com/21303438/69511394-e031ac80-0f7a-11ea-9be9-c98a82e4d090.png)

The question is that, this exporting way generates a `Cast` node, which converts int to INT64 in tensorrt. But actually, `onnx-tensorrt` does not support int64 cast at all, it only supports float32 cast to float16.

So here is my question, why does pytorch need convert a int to int64 when export? How should we change it? I think int64 is unnecessary in most circumstances.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by jinfagang** [comment]
Use int32 as default and remove the Cast op is a better way maybe?

**Comment by garymm** [comment]
Just tried this with PyTorch 1.10.0 and there is no Cast node in the graph:
![image](https://user-images.githubusercontent.com/421339/151464006-4772d1d5-2bd0-4b54-9ca3-5604bfd122b5.png)
