### ISSUE TITLE
Error when building pytorch v1.3.1/v.1.3.0 from source

### ISSUE THREAD

**Issue by mental2008** [pytorch/pytorch#30394]
I want to build pytorch v1.3.1/v1.3.0 from source.

`git clone --recursive https://github.com/pytorch/pytorch -b v1.3.1`

But when cloning into 'android/libs/fbjni', I was asked to input username and password.

The detailed message is as followed.

remote: Repository not found.
fatal: repository 'https://github.com/IvanKobzarev/fbjni.git/' not found
fatal: clone of 'https://github.com/IvanKobzarev/fbjni.git' into submodule path 'android/libs/fbjni' failed

However, I didn't meet the same problem when building pytorch from master branch.

**Comment by ngoldbaum** [comment]
As reported on slack, a workaround is to do:

```
git -c submodule."android/libs/fbjni".update=none submodule update --init --recursive
```

**Comment by IvanKobzarev** [comment]
As a hotfix to unblock you - I returned https://github.com/IvanKobzarev/fbjni to public visibility

**Comment by mental2008** [comment]
The bug is fixed. - Thanks a lot.
