### ISSUE TITLE
Multi-GPU with CUDA 9.0

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#3040]
I updated to cuda 9.0 and update pytorch with master branch. The DataParallel doesn't work any more for mutli-gpus. The training got stuck at creating the cuda model.

**Comment by ngimel** [comment]
Have you build with magma conda package? If so, try building without it, it is built with cuda 8.0 and conflicts with pytorch when it is built with cuda 9.

**Comment by zhanghang1989** [comment]
I installed `conda install -c soumith magma-cuda80` before. Should I uninstall it?

**Comment by ngimel** [comment]
yes.

**Comment by zhanghang1989** [comment]
It works. Thanks @ngimel !
