### ISSUE TITLE
Fix 1.3.1 branch submodule fbjni dependency

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#30416]
As the most recent release, we should support building 1.3.1 from scratch. But the submodule https://github.com/IvanKobzarev/fbjni got removed and switched to https://github.com/facebookincubator/fbjni.git. It should be fixed in 1.3.1 as well if possible. 

cc @ezyang @gchanan @zou3519

**Comment by IvanKobzarev** [comment]
As a hotfix to unblock - I returned https://github.com/IvanKobzarev/fbjni to public visibility

**Comment by mzmssg** [comment]
@IvanKobzarev 
1.3.1 build is still broken.
1.3.1 depends on commit `dc916917e1500527f83bc24b1767a123d6549ca0`, but it can't be found in IvanKobzarev/fbjni.

**Comment by ailzhang** [comment]
I feel we should still fix this, although 1.4.0 is now the latest release.

**Comment by mattip** [comment]
`git checkout v1.3.1; git submodule update --recursive` now finds the correct commits in all submodules.

**Comment by rgommers** [comment]
@mattip could you link to the relevant PR? Then I think this can be closed.

**Comment by mattip** [comment]
In commit 42faf961c83 the submodule `android/libs/fbjni` changed from https://github.com/IvanKobzarev/fbjni  to https://github.com/facebookincubator/fbjni.git. This commit to pytorch was done after 1.3.1 and before 1.4.0. The repo under IvanKobzarev was removed, leading to this issue. Subsequently the removed repo was restored. If there was a PR corresponding to [commit 42faf961c83](https://github.com/pytorch/pytorch/commit/42faf961c83), github is not pointing it out to me.

**Comment by rgommers** [comment]
Thanks @mattip. The two options here are:

1. Assume https://github.com/IvanKobzarev/fbjni will remain in place, close this issue.
2. Add a commit on top of `v1.3.1` to point the submodule to https://github.com/facebookincubator/fbjni/commit/dc916917e15 instead, and then move the git tag to that new commit. Moving tags is not great practice, it could break some things like if people rely on `v1.3.1` and have added a check on commit id or checksum.

@ailzhang any preference?

**Comment by rgommers** [comment]
Now that this has stayed unchanged for longer and `v1.5.0` is out, moving the tag seems less needed and less attractive. 

I propose to close this - will do so next week unless someone disagrees.
