### ISSUE TITLE
Connection closed by peer when using L-BFGS and distributed computing (gloo)

### ISSUE THREAD

**Issue by piyueh** [pytorch/pytorch#30439]
## 🐛 Bug

When using L-BFGS optimizer with distributed computing (CPU only, `gloo` backend), at the last epoch of the training loop, some ranks report an error regarding connection closed by a peer.

The documentation only says:
> Right now all parameters have to be on a single device. This will be improved in the future.

For a simple distributed setup, all processes have exactly the same copy of all parameters. So I'm not sure if this meets "all parameters have to be on a single device`. At first glance, I thought "all parameters on a single device" simply means I can not distribute different parameters to different devices. But now I'm not so sure what this warning means.

## To Reproduce

1. Copy the following toy code to a local python file:
```python
import os
import torch

class Toy(torch.nn.Module):
    """Toy model"""
    def __init__(self):
        """__init__"""
        super(Toy, self).__init__()
        self.L = torch.nn.Linear(1, 50)
        self.out = torch.nn.Linear(50, 1)

    def forward(self, x):
        """forward"""

        Y = torch.tanh(self.L(x))
        Y = self.out(Y)
        return Y

if __name__ == "__main__":

    # some misc settings
    torch.set_num_threads(1)
    torch.set_num_interop_threads(1)
    torch.manual_seed(0)

    # communication setup
    torch.distributed.init_process_group("gloo")
    my_rank = torch.distributed.get_rank()
    world_size = torch.distributed.get_world_size()

    # setup data loaders
    delta = 1. / world_size
    start, end = delta * my_rank, delta * (my_rank + 1)
    x = torch.linspace(start, end, 100//world_size)[:, None]
    y = 2.31 * torch.pow(x, 2) + 1.23 * x - 3.21

    # model, loss, optimizer
    model = torch.nn.parallel.DistributedDataParallel(Toy())
    loss_fn = torch.nn.MSELoss(reduction="mean")
    opter = torch.optim.LBFGS(model.parameters(), line_search_fn="strong_wolfe")

    for epoch in range(3):

        def closure():
            model.train()
            opter.zero_grad()
            pred = model(x)
            loss = loss_fn(pred, y)
            loss.backward()
            return loss

        opter.step(closure)
        print("rank {}: Epoch {} done".format(my_rank, epoch))

    print("rank {}: training finished".format(my_rank))

```

2, Launch the python script with the helper from pytorch -- `torch.distributed.launch`. For example, assuming the script is called `test.py` and that we're using 1 node and 2 processes per node on a local machine:

```
$ python -m torch.distributed.launch --nnodes 1 --nproc_per_node 2 --master_addr 127.0.0.1 --master_port 60000 --use_env test.py
```

3. The program should produce an error message complaining the connection is closed by some peer at `127.0.0.01` at some random port. Something like this:

```
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    opter.step(closure)
  File "/usr/lib/python3.8/site-packages/torch/optim/lbfgs.py", line 421, in step
    loss, flat_grad, t, ls_func_evals = _strong_wolfe(
  File "/usr/lib/python3.8/site-packages/torch/optim/lbfgs.py", line 49, in _strong_wolfe
    f_new, g_new = obj_func(x, t, d)
  File "/usr/lib/python3.8/site-packages/torch/optim/lbfgs.py", line 419, in obj_func
    return self._directional_evaluate(closure, x, t, d)
  File "/usr/lib/python3.8/site-packages/torch/optim/lbfgs.py", line 277, in _directional_evaluate
    loss = float(closure())
  File "test.py", line 60, in closure
    loss.backward()
  File "/usr/lib/python3.8/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 97, in backward
    Variable._execution_engine.run_backward(
RuntimeError: [/build/python-pytorch/src/pytorch-1.3.1-opt-cuda/third_party/gloo/gloo/transport/tcp/pair.cc:572] Connection closed by peer [127.0.0.1]:56449
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/torch/distributed/launch.py", line 248, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'test.py']' returned non-zero exit status 1.
```

## Expected behavior

When using other optimizers, such as Adam, no runtime error happened (though I didn't check if the loss converged). So I expect L-BFGS to be also fine.

Or, my other expectation of the behavior is that, if L-BFGS does not support distributed computing, there should be a clear runtime error pop up during runtime.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- How you installed PyTorch: `sudo pacman -S python-pytorch-opt-cuda`
- PyTorch version: 1.3.1
- Is debug build: No
- CUDA used to build PyTorch: 10.1.243
- OS: Arch Linux
- GCC version: (GCC) 9.2.0
- CMake version: version 3.15.5
- Python version: 3.8
- Is CUDA available: Yes
- CUDA runtime version: 10.1.243
- GPU models and configuration:
  - GPU 0: Tesla K40c
  - GPU 1: GeForce GT 720
  - GPU 2: Tesla K40c
  - GPU 3: Tesla K20c
- Nvidia driver version: 440.31
- cuDNN version: /usr/lib/libcudnn.so.7.6.5
- Versions of relevant libraries:
  - [pip3] numpy==1.17.4
  - [pip3] torch==1.3.1
  - [conda] Could not collect

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by piyueh** [comment]
I think I may know the reason. For each iteration of an L-BFGS solve, the solver evaluates the `closure` function several times. I'm not familiar with 2nd order methods, but I think this happens under some conditions. Anyway, that's why the L-BFGS solver has an argument `max_eval` to control the maximum number of evaluations of `closure` in an iteration.

Different processes have different inputs and different losses. So now, if the L-BFGS solver at one of the processes determines to do one more sweep of `closure`, while other processes don't, than there will be some synchronization issues because of the `loss.backward()`. I think the `loss.backward()` of a `DistributedDataParallel` model triggers some all-reduce operation to sync gradients. But if only one process determines to do one more `closure` and hence one more `loss.backward()`, then the all-reduce operation will hang there.

Now, I guess the all-reduce operation from `gloo` will automatically kill the operation and return an error, instead of just hanging there. But if I try using `nccl` and distributed GPU computing, at some point, the training hangs.

A solution is to limit the `max_eval` to one. And everything goes fine. For example:
```
opter =torch.optim.LBFGS(model.parameters(), max_eval=1)
```
Though I don't know if limiting `max_eval` will affect the solving performance. Not familiar with the math behind optimization.

**Comment by pietern** [comment]
Thanks for posting the issue and the subsequent explanation.

You're exactly right, that if one of the processes decides to run another iteration, then the other one will raise the error you report. You can work your way around this by making a single process responsible for this decision, and broadcasting the decision to the other processes. You can use `torch.distributed` for this, but you'll also need to hack the optimizer to do this. It only takes a closure, from the snippet you shared, so there's not really another way to do this.

> Now, I guess the all-reduce operation from gloo will automatically kill the operation and return an error, instead of just hanging there. But if I try using nccl and distributed GPU computing, at some point, the training hangs.

This is also correct. NCCL hangs if a single process decides to terminate, whereas Gloo always raises an error if this happens.

Closing the issue, as I think there isn't any follow up needed here.

**Comment by piyueh** [comment]
Thanks for the confirmation. I would like to add another workaround so that other people having the same problem can know their options.

Besides hacking the L-BFGS source code, the other thing we can do is to not allow the L-BFGS to run arbitrary numbers of evaluations of `closure`:

1. Don't use `strong_wolfe` for line search. `strong_wolfe` requires executing `closure` several times to find optimal step size, and different processes will need different numbers of executions to find it. I don't know about the line searching, but from the source code, `strong_wolfe` looks like some sort of bi-section method. It looks like `strong_wolfe` relies on both loss and corresponding gradients to do calculations. While the loss returned by `closure` is a local loss to each process, the gradients are not local gradients. In other words, the loss and gradients do not match each other under distributed computing. I'm not sure the line searching algorithm can still work as expected in this case. So simply use `line_search_fn=None`. `None` means the L-BFGS will only use fixed step size (according to the comment in the source code), but I guess that's the trade-off.

2. Don't use any early termination criteria. So set `tolerance_grad` and `tolerance_change` to zero. This makes sure no process will terminate L-BFGS solver earlier than other processes.

i.e.,
```python
opter = torch.optim.LBFGS(
    model.parameters(), tolerance_grad=0, tolerance_change=0, line_search_fn=None)
```

**Comment by pietern** [comment]
Excellent!

It should be possible to come up with an optimizer that is distributed-aware, where all these decisions are made globally instead of by a single machine. Then you can use it in a distributed setting, but will have to average losses, or pick one of the machines are the primary.
