### ISSUE TITLE
`torch.Size` is tranfered  to`torch.Tensor`, values don't equal

### ISSUE THREAD

**Issue by JerryQiang** [pytorch/pytorch#30444]
## 🐛 Bug

`torch.Size` is tranfered  to`torch.Tensor`, values don't equal
## To Reproduce

1.ele = torch.Tensor([1])
2.print(ele.shape, torch.Tensor(ele.shape))  # torch.Size([1]), tensor([-5.2017e-05])

## Environment
 - PyTorch Version (1.3.1):
 - OS (linux):
 - How you installed PyTorch (anaconda):
 - Build command you used (if compiling from source):
 - Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 

## Additional context
first `list()`, then `Tensor()`, the result is right
torch.Tensor(list(ele.shape)) . # tensor([1.]

**Comment by yf225** [comment]
@JerryQiang Does `torch.Tensor(ele.shape)` work in any version of PyTorch, or is this a feature suggestion?

**Comment by JerryQiang** [comment]
> @JerryQiang Does `torch.Tensor(ele.shape)` work in any version of PyTorch, or is this a feature suggestion?
thank you for answering
I research the document, it is my fault to use it.
when you pass `Size`,  it will create a random tensor by shape.
only pass data, it will create a random tensor by data.

the passed parameters as followling:
```
 * (torch.device device)
      didn't match because some of the keywords were incorrect: shape
 * (torch.Storage storage)
      didn't match because some of the keywords were incorrect: shape
 * (Tensor other)
      didn't match because some of the keywords were incorrect: shape
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)
```

**Comment by JerryQiang** [comment]
Thank you for answering
I research the document, it is my fault to use it.
when you pass `Size`,  it will create a random tensor by shape.
only pass data, it will create a random tensor by data.

the passed parameters as followling:
```
 * (torch.device device)
      didn't match because some of the keywords were incorrect: shape
 * (torch.Storage storage)
      didn't match because some of the keywords were incorrect: shape
 * (Tensor other)
      didn't match because some of the keywords were incorrect: shape
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)
```

**Comment by JerryQiang** [comment]
At first, I misunderstand `tensor.size` as the total numbers of tensor elements, 
I want to transfer `Size` to `Tensor` and `cumprod` it.
Lastly I directly use `for each` to count the total num.

**Comment by SsnL** [comment]
`torch.Tensor(shape)` creates an empty tensor of shape `shape`. Don't use deprecated uppercase `Tensor`. Use `torch.tensor(shape)` to create a tensor containing the same value as `shape`.

**Comment by SsnL** [comment]
Finally, just do `shape.numel()` gives you the cumprod.

**Comment by JerryQiang** [comment]
> Finally, just do `shape.numel()` gives you the cumprod. There is no need to copy to tensor.

you're right, bingo!
I want to ask you another question
when I use `PyCharm` to see the source code, sometimes it will open `pyi` file. 
and I can't see more detailed code document
How to solve it?
