### ISSUE TITLE
Is there any plan for Adafactor optimizer?

### ISSUE THREAD

**Issue by benywon** [pytorch/pytorch#30446]
## 🚀 Feature

official Adafactor optimizer
## Motivation
an efficient optimizer Adafactor is currently widely used in some big models, it saves a lot of memory due to its sub-linear running average of the gradient, sometimes result in a sigificant memory footprint reduce and larger batch size.

## Additional context

cc @vincentqb

**Comment by chinokenochkan** [comment]
https://github.com/pytorch/fairseq/blob/master/fairseq/optim/adafactor.py
