### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [pytorch/pytorch#30457]
Hi, thanks for this awesome library! I wanted to let you know that there are now experimental [Ruby bindings](https://github.com/ankane/torch-rb) for it based on LibTorch.

If you have any feedback, let me know or feel free to create an issue in the project for it. Thanks!

**Comment by ankane** [comment]
Also added a Homebrew formula so users can now do:

```sh
brew install libtorch
```

https://github.com/Homebrew/homebrew-core/pull/47222

**Comment by pietern** [comment]
Thanks for sharing! Nice work!

**Comment by pietern** [comment]
I've shared it with the team. Be sure to post about it on https://discuss.pytorch.org/!

**Comment by ankane** [comment]
Thanks @pietern, posted both announcements.
