### ISSUE TITLE
backward not called with custom op

### ISSUE THREAD

**Issue by flymark2010** [pytorch/pytorch#30454]
## 🐛 Bug

I have wrote a CustomOp with torch.autograd.Function, but the  custom backward will not be called.

## To Reproduce

1. Just run the sample code.
2. The backward is not called, (no print message)

```
  1 import torch
  2 import torch.nn as nn
  3
  4 class CustomOp(torch.autograd.Function):
  5   @staticmethod
  6   def forward(ctx, x):
  7     x *= 2.0
  8     return x
  9
 10   @staticmethod
 11   def backward(ctx, grad_output):
 12     print('Running in backward...')
 13     grad_output *= 2.0
 14     return grad_output
 15
 16 def custom_op(x):
 17   return CustomOp.apply(x)
 18
 19 class Net(nn.Module):
 20   def __init__(self, in_channel, out_channel, scale=400.0):
 21     super(Net, self).__init__()
 22     self.fc = nn.Linear(in_channel, out_channel)
 23     self.s = scale
 24
 25   def forward(self, input):
 26     x = self.fc(input)
 27     logits = custom_op(x)
 28 #    logits = logits * self.s
 29     logits *= self.s
 30     return logits
 31
 32 if __name__=='__main__':
 33   bs = 32
 34   in_channel = 128
 35   out_channel = 512
 36   dummy_x = torch.rand(bs, in_channel)
 37
 38   net = Net(in_channel, out_channel)
 39   x = net(dummy_x)
 40   x.mean().backward()
```
## Expected behavior

- The backward method should be called.  

## Environment

 - PyTorch Version : 1.3.1
 - OS : Linux
 - How you installed PyTorch : pip
 - Python version: 3.5

## Additional context

When comment line 29 and uncomment line 28,  thing seems OK. I'am wondering if "*=" is right usage.

**Comment by pietern** [comment]
So the real issue is that the behavior is different between:

```python
logits = logits * self.s
```

And 

```python
logits *= self.s
```

?

**Comment by flymark2010** [comment]
You can say that way. I've not idea what happend behind the "*=" operater or the Pytorch custom op.

**Comment by mruberry** [comment]
@albanD

**Comment by albanD** [comment]
Hi,

Please see the latest documentation for extending autograd [here](https://pytorch.org/docs/master/notes/extending.html#extending-torch-autograd).
This was not as clear before but you should be using `mark_dirty()` in your forward pass for everything to work properly.

Please use the forum if you have further questions: https://discuss.pytorch.org/
