### ISSUE TITLE
Meta file not found or corrupted.

### ISSUE THREAD

**Issue by BarakBat** [pytorch/pytorch#30455]
## To Reproduce

```
import torchvision.datasets as datasets
input_transform = None

imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
```

Gives error:
> Traceback (most recent call last):
  File "test_imagenet.py", line 4, in <module>
    imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 56, in __init__
    wnid_to_classes = self._load_meta_file()[0]
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 108, in _load_meta_file
    "You can use download=True to create it.")
RuntimeError: ('Meta file not found or corrupted.', 'You can use download=True to create it.')

## Expected behavior

 Expected behavior? load ImageNet and not break.

## Environment
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0

## Additional context
Thanks.

**Comment by pietern** [comment]
Have you tried specifying `download=True`?

I'm closing the issue as this is a `torchvision` issue. Please report at https://github.com/pytorch/vision/.
