### ISSUE TITLE
torch.tensor([np.array, np.array]) slower than torch.tensor(np.array([np.array, np.array]))

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#30460]
A example.

In my computer output.
```
4.814477205276489
0.03499555587768555
```

code
```
import torch
import numpy as np
import time

a = [np.random.random([512, 512, 3]).astype(np.float32) for i in range(10)]

t1 = time.time()
b = torch.tensor(a, dtype=torch.float32)
t2 = time.time()

c = torch.tensor(np.array(a), dtype=torch.float32)
t3 = time.time()

print(t2-t1)
print(t3-t2)

```

**Comment by pietern** [comment]
This is likely because the first variant where you specify a list of numpy arrays is interpreted as literal contents, whereas the second variant is interpreted directly as a numpy array.

I've labeled this for triage review to figure out a resolution.

**Comment by mruberry** [comment]
@gchanan duplicate

**Comment by mruberry** [comment]
Dupe of https://github.com/pytorch/pytorch/issues/13918
