### ISSUE TITLE
[jit] Spurious error when type comments are found in the body of a function.

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#30477]
Repro:
```
@torch.jit.script
class Timebase:
    def __init__(
        self,
        numerator,  # type: int
        denominator,  # type: int
    ):
        # type: (...) -> None
        self.numerator = numerator  # type: int
        self.denominator = denominator  # type: int
```
Produces the error:
```
RuntimeError: Return type line '# type: (...) -> ...' not found on multiline type annotation
(See PEP 484 https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)
```

Even though we have clearly put the return type comment in the function. This is due to a bug in the type comment parser, which expects the return type line to be the last element of the list (see [here](https://github.com/pytorch/pytorch/blob/681b610f35968761435b28a6bc564e17a7f553d0/torch/jit/annotations.py#L157)).

Fix is simple, just search for the return type line instead of assuming it's the last one.

cc @suo

**Comment by yyn19951228** [comment]
Can I try to fix this issue?

**Comment by yyn19951228** [comment]
Oh sorry I see it has been fixed.
