### ISSUE TITLE
RuntimeError: stack.size() >= num_inputs INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#30494]
## 🐛 Bug

Reproduce:

```python
import torch

@torch.jit.script
def f():
    l = []
    for n in [2, 1]:
        l.append(torch.zeros(n))

    return l[0]

f()
f()
```

Error:
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    f()
RuntimeError: stack.size() >= num_inputs INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/interpreter.cpp:1025, please report a bug to PyTorch. 
The above operation failed in interpreter, with the following stack trace:
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by eellison** [comment]
Thanks for the minimal repro! What version are you on ? I think https://github.com/pytorch/pytorch/pull/25124 fixed this issue. The above code sample works on master so I'm closing.

**Comment by zasdfgbnm** [comment]
@eellison Are you sure the code works on master? The version of the master I am using is very recent:
```
1.4.0a0+ec5c08d
ec5c08de74ffc5709baaef944788c296fa091d70
```
which is
```
commit ec5c08de74ffc5709baaef944788c296fa091d70 (HEAD -> master, upstream/master)
Author: Richard Zou <rzou@fb.com>
Date:   Wed Nov 27 08:36:40 2019 -0800

    Revert D18580867: Add logical_and and logical_or
```

I think the problem starts after `1.4.0.dev20191112` younger versions are working fine.

**Comment by eellison** [comment]
I'm on .1.4.0a0+a182dac and it works fine

**Comment by zasdfgbnm** [comment]
@eellison I didn't find an `a182dac` on the master I have. Could it be the branch you are working with is based on the master older than 20191112?

**Comment by eellison** [comment]
Oops ya that's my local branch, but I'm on top of commit e9cc4a594279080d0459b73b4c1a6d9e8e6b75e7

**Comment by zasdfgbnm** [comment]
Strange, `e9cc4a5` is new enough. Let me do a full clean up and rebuild to see if the problem is still there.

**Comment by zasdfgbnm** [comment]
Just did a
```
pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
```
It is still failing
```
1.4.0.dev20191127
3b178ac7baa33b7af017fc16619082264677796f
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    f()
RuntimeError: stack.size() >= num_inputs INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/interpreter.cpp:1025, please report a bug to PyTorch. 
The above operation failed in interpreter.
Traceback (most recent call last):
```

**Comment by eellison** [comment]
hmm, strange. @ailzhang could you try as well ?

**Comment by zasdfgbnm** [comment]
For more info:

```python
def f():
    l = []
    for n in [2, 1]:
        l.append(torch.zeros(n))

    return l[0]
```

Unrolling the loop or not returning anything would make the script work.

**Comment by ailzhang** [comment]
@eellison I have a recent master (like 2 days ago) and it fails on my build.

**Comment by eellison** [comment]
I was adding this as a function to `test_jit.py`, and we have some setting locally that causes it to not fail there. Confirmed repro in a stand-alone file. cc @Krovatkin

**Comment by eellison** [comment]
With `enable_profiling_mode` this fails. Hopefully https://github.com/pytorch/pytorch/pull/30186#event-2816965025 this fixes it but it might not.

**Comment by Krovatkin** [comment]
@eellison i'll take a look. for loop counters are just so painful to handle 😢

**Comment by Krovatkin** [comment]
@eellison this is mostly FYI: tests in `test_jit.py` run a simple executor unless `with enable_profiling_mode` specified. Otherwise, a full profiler is enabled by default.

**Comment by Krovatkin** [comment]
@zasdfgbnm this is a new issue. I believe we have a fix though, but it hasn't gone through a review process yet: https://github.com/pytorch/pytorch/pull/30643

**Comment by zasdfgbnm** [comment]
cc: @ptrblck for visibility

**Comment by eellison** [comment]
Closed with https://github.com/pytorch/pytorch/pull/31724
