### ISSUE TITLE
flaky curl causes "apt-key add" to fail with gpg error message

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#30500]
Observed 4 instances of the error `gpg: no valid OpenPGP data found` in master builds last week (2019-11-17 through 2019-11-24).  This was one of the [top network-related failures for the week](https://dr.pytorch.org/flakiness-review.html).

I will add the `--retry 3` parameter to curl invocations throughout the build scripts as a workaround.

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by ngimel** [comment]
closing due to age
