### ISSUE TITLE
torch.sparse.mm/addmm(mat1, mat2)  FAIL

### ISSUE THREAD

**Issue by elbarto91** [pytorch/pytorch#30510]
## 🐛 Bug

When i use  ' torch.sparse.addmm(mat, mat1, mat2)' and 'torch.sparse.mm(mat1, mat2)' 
the computation stop with the following error:
 'RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591, please report a bug to PyTorch.'

## To Reproduce

-python3 ffnspeedcompareBUG.py

CODE 
```
import torch.nn as nn
import torch 
import argparse
import torch,time

class Net(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Net, self).__init__()                    # Inherited from the parent class nn.Module
        self.fc1 = nn.Linear(input_size, hidden_size,bias=False)  # 1st Full-Connected Layer:  (input data) ->  (hidden node)
        nn.init.kaiming_normal_(self.fc1.weight)
        self.fc2 = nn.Linear(hidden_size, output_size,bias=False) # 2nd Full-Connected Layer:  (hidden node) ->  (output class)        
        nn.init.kaiming_normal_(self.fc2.weight)
        self.LRelu = nn.LeakyReLU(0.25)
        self.fnn = nn.Sequential(
            self.fc1,
            self.LRelu,
            self.fc2
        ) 

def forward(self,x):
        return self.fnn(x)
           
device= torch.device('cuda')
start = time.time()
nodes_num=100
x = torch.ones(nodes_num, 12).to(device)
y = torch.ones(nodes_num, 1).to(device)
dummy = torch.zeros(12*nodes_num,nodes_num)
dummy[0][0]=1
dummy=dummy.to_sparse()
dummy.to(device)
print(dummy)
parent=torch.ones(12*nodes_num,1).to (device)
net = Net(12,4,1)
net.to(device)
optimizer = torch.optim.RMSprop(net.parameters())
criterion = nn.MSELoss()
start_event = torch.cuda.Event(enable_timing=True)
end_event = torch.cuda.Event(enable_timing=True)
start_event.record()
res=net(x)
new_parent=torch.sparse.mm(dummy,res)
end_event.record()
torch.cuda.synchronize()  # Wait for the events to be recorded!
elapsed_time_ms = start_event.elapsed_time(end_event)
```

COMPLETE OUTPUT

tensor(indices=tensor([[0],
                       [0]]),
       values=tensor([1.]),
       size=(1200, 100), nnz=1, layout=torch.sparse_coo)
Traceback (most recent call last):
  File "ffnspeedcompareBUG.py", line 55, in <module>
    new_parent=torch.sparse.mm(dummy,res)
  File "/XX/XX/XXX/.local/lib/python3.6/site-packages/torch/sparse/__init__.py", line 68, in mm
    return torch._sparse_mm(mat1, mat2)
RuntimeError: !t.is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/sparse/SparseTensorMath.cpp:591, please report a bug to PyTorch.

## Expected behavior

Simple operation's result between a sparse matrix and a dense matrix.

## Environment

 - PyTorch Version (e.g., 1.0):  1.3.0+cu92
 - OS (e.g., Linux):  Ubuntu 18.04 LTS 64bit
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): python3 ffnspeedcompareBUG.py
 - Python version:  Python 3.6.9
 - CUDA/cuDNN version: cu92
 - GPU models and configuration: ASUS GeForce GTX 1080 Ti 3584 Cores 11G RAM
 - Any other relevant information:

## Additional context

///////////////////////

**Comment by albanD** [comment]
You need to replace `dummy.to(device)` by `dummy = dummy.to(device)` to get it on the gpu.

Also please use the forum to ask questions please: https://discuss.pytorch.org/
