### ISSUE TITLE
torch.dot() and torch.tensordot() give different results

### ISSUE THREAD

**Issue by Jakob-Unfried** [pytorch/pytorch#30520]
## Issue description

When using torch.dot() or torch.tensordot() to calculate the scalar product of two vectors (1D torch.Tensor s) the result occasionally differs by up to 1e-7.

## Code example

`
    import torch

    for n in range(10):
        a = torch.rand(5)
        b = torch.rand(5)
    
        ab_dot = torch.dot(a, b)
        ab_tensordot = torch.tensordot(a, b, ([0], [0]))
    
        assert torch.norm(ab_dot - ab_tensordot).item() < 1e-15
`

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.0.2            py37h1de35cc_0  
[conda] mkl_fft                   1.0.12           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] pytorch                   1.3.1                   py3.7_0    pytorch

**Comment by SsnL** [comment]
Note that 1e-7 is small enough for float32 to be caused by precision.

**Comment by albanD** [comment]
Hi,

Yes, 1e-7 is at the level of floating point precision. This is expected as these two operations might have different implementation / parallelization strategy.
You can use double precision floats if you need more precision.
