### ISSUE TITLE
add torch.square

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#30524]
torch.square would be useful when you need to do x*x but x is a large expression

```
np.square([1,2,3])        # => array([1, 4, 9])
tf.square([1,2,3]).eval() # => array([1, 4, 9], dtype=int32)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.square.html
https://www.tensorflow.org/api_docs/python/tf/math/square

**Comment by albanD** [comment]
As a workaround, you can use `torch.pow(foo, 2)`. But I guess we can add this as well.

**Comment by TH3CHARLie** [comment]
Implement this op seems straightforward, would you mind I take a try? @albanD

**Comment by albanD** [comment]
@TH3CHARLie please do !
Let us know here if you need any help.

**Comment by TH3CHARLie** [comment]
@albanD Hi! Thanks for letting me do it and after some trials and errors I think my PR is now review-ready, so if you have time would you please do a review on #30719, thanks
