### ISSUE TITLE
Compile Source code in macOs Catalina 10.15.1 failed

### ISSUE THREAD

**Issue by Marvinmw** [pytorch/pytorch#30542]
## ❓ Questions and Help
I compiled source code but after python setup.py develop. It gives the error non Python.h found.

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

Please read the template you just posted and use the forum for questions: https://discuss.pytorch.org/
Thanks
