### ISSUE TITLE
Meshes not showing in tensorboard 

### ISSUE THREAD

**Issue by cfd1** [pytorch/pytorch#30561]
Hi,

I am using pytorch 1.3.1 and tf-nighty (as per the pytorch documentation). 
I have tried the [example code](https://pytorch.org/docs/stable/tensorboard.html) for `add_mesh` to add a mesh to tensorboard
```
from torch.utils.tensorboard import SummaryWriter
vertices_tensor = torch.as_tensor([
    [1, 1, 1],
    [-1, -1, 1],
    [1, -1, -1],
    [-1, 1, -1],
], dtype=torch.float).unsqueeze(0)
colors_tensor = torch.as_tensor([
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
    [255, 0, 255],
], dtype=torch.int).unsqueeze(0)
faces_tensor = torch.as_tensor([
    [0, 2, 3],
    [0, 3, 1],
    [0, 1, 2],
    [1, 3, 2],
], dtype=torch.int).unsqueeze(0)

writer = SummaryWriter()
writer.add_mesh('my_mesh', vertices=vertices_tensor, colors=colors_tensor, faces=faces_tensor)

writer.close()
```

This is what I get
![image](https://user-images.githubusercontent.com/57766372/69811674-80d7d480-11e6-11ea-9245-8c98b5e18d45.png)
I can't find any solutions online to this issue. 

- Does anyone have any suggestion to get this to work?
- Has anyone managed to get this to work?

Thanks

Adam

**Comment by mruberry** [comment]
Thanks for reporting this issue! 

You may also want to ask this question on the PyTorch forums: https://discuss.pytorch.org/.

**Comment by cfd1** [comment]
Thanks. 

I have raised it here [PyTorch Forum](https://discuss.pytorch.org/t/meshes-not-showing-in-tensorboard/62565)

**Comment by cfd1** [comment]
I forgot to say I'm using python 3.6 in a conda environment on linux and reproduced this on two different systems.

- I have switched to tensorboard 2.0.2 with pytorch 1.3.1 and get the same issue.
- I have made a new conda environment with pytorch-nightly and tensorboard 2.0.2 and get the same issue. I have provided more info in the forum.

**Comment by cfd1** [comment]
The issue was firefox. It works in chrome.
