### ISSUE TITLE
torch.where and torch.nonzero cause out of memory

### ISSUE THREAD

**Issue by Yihan-zz** [pytorch/pytorch#30568]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
![image](https://user-images.githubusercontent.com/46353683/69868248-26bd3900-12e4-11ea-8d92-6074a1a14934.png)
I am wondering why torch.nonzero cost lots of vram

**Comment by mruberry** [comment]
Try asking this question on the PyTorch forum at https://discuss.pytorch.org/.
