### ISSUE TITLE
Cannot build Simple c++ after building Libtorch from Source on Windows

### ISSUE THREAD

**Issue by eric-tc** [pytorch/pytorch#30571]
## 🐛 Bug

Hi,
i have compiled libtorch on Windows from source. Now i'am trying to build simple c++ program to use compiled version of libtorch. 
When i run cmake --build . --config Release i got the following error `cmake -DCMAKE_PREFIX_PATH=C:\Users\tondelli\Desktop\CustomLibTorch -Ax64 ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27024.1
-- The CXX compiler identification is MSVC 19.16.27024.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2 (found version "9.2")
-- Caffe2: CUDA detected: 9.2
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2
-- Caffe2: Header version is: 9.2
-- Found CUDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/lib/x64/cudnn.lib
-- Found cuDNN: v7.6.5  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.2/lib/x64/cudnn.lib)
CMake Warning (dev) at C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Caffe2/public/cuda.cmake:369 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Warning (dev) at C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Caffe2/public/utils.cmake:81 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Caffe2/Caffe2Config.cmake:121 (caffe2_interface_library)
  C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/tondelli/Desktop/CustomLibTorch/share/cmake/Torch/TorchConfig.cmake:108 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found torch: C:/Users/tondelli/Desktop/CustomLibTorch/lib/torch.lib
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV: C:/Users/tondelli/Desktop/opencv/opencv-3.4.3/build/install (found version "3.4.3")
-- Found OpenCV 3.4.3 in C:/Users/tondelli/Desktop/opencv/opencv-3.4.3/build/install/x64/vc15/lib
-- You might need to add C:\Users\tondelli\Desktop\opencv\opencv-3.4.3\build\install\x64\vc15\bin to your PATH to be able to run your applications.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/tondelli/Desktop/pytorchPlusPlus/testCustomLib/build

C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\build>cmake --build . --config Release
Microsoft (R) Build Engine versione 15.9.20+g88f5fadfbe per .NET Framework
Copyright (C) Microsoft Corporation. Tutti i diritti sono riservati.

  Checking Build System
  Building Custom Rule C:/Users/tondelli/Desktop/pytorchPlusPlus/testCustomLib/CMakeLists.txt
  train.cpp
C:\Users\tondelli\Desktop\CustomLibTorch\include\torch/csrc/jit/tracer.h(285): warning C4273: 'torch::jit::tracer::addI
nputs': inconsistent dll linkage [C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\build\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\torch/csrc/jit/tracer.h(273): note: see previous definition of 'addI
  nputs'
C:\Users\tondelli\Desktop\CustomLibTorch\include\torch/csrc/jit/tracer.h(292): warning C4273: 'torch::jit::tracer::addI
nputs': inconsistent dll linkage [C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\build\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\torch/csrc/jit/tracer.h(279): note: see previous definition of 'addI
  nputs'
C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): warning C4477: 'printf' : format string '%ld' r
equires an argument of type 'long', but variadic argument 2 has type 'int64_t' [C:\Users\tondelli\Desktop\pytorchPlusPl
us\testCustomLib\build\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): note: consider using '%lld' in the format str
  ing
  C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): note: consider using '%Id' in the format stri
  ng
  C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): note: consider using '%I64d' in the format st
  ring
C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): warning C4477: 'printf' : format string '%5ld'
requires an argument of type 'long', but variadic argument 3 has type 'size_t' [C:\Users\tondelli\Desktop\pytorchPlusPl
us\testCustomLib\build\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\train.cpp(516): note: consider using '%zd' in the format stri
  ng
C:\Users\tondelli\Desktop\CustomLibTorch\include\c10/util/Half.h(451): warning C4018: '>': signed/unsigned mismatch [C:
\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\build\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\c10/util/Half.h(497): note: see reference to function template insta
  ntiation 'bool c10::overflows<To,From>(From)' being compiled
          with
          [
              To=int64_t,
              From=int64_t
          ]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\c10/core/Scalar.h(72): note: see reference to function template inst
  antiation 'To c10::checked_convert<int64_t,int64_t>(From,const char *)' being compiled
          with
          [
              To=int64_t,
              From=int64_t
          ]
c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): error C2672: 'c10::impl::b
oxAndCallBoxedFunc': no matching overloaded function found [C:\Users\tondelli\Desktop\pytorchPlusPlus\testCustomLib\bui
ld\trainCustomLib.vcxproj]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\ATen/core/dispatch/Dispatcher.h(179): note: see reference to functio
  n template instantiation 'Return c10::KernelFunction::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,boo
  l>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
          with
          [
              Return=void
          ]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\ATen/core/dispatch/Dispatcher.h(154): note: see reference to functio
  n template instantiation 'Return c10::Dispatcher::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(c
  onst c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
          with
          [
              Return=void
          ]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\ATen/core/TensorMethods.h(65): note: see reference to function templ
  ate instantiation 'Return c10::OperatorHandle::callUnboxed<void,const at::Tensor&,const at::Tensor&,bool,bool>(const
  at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
          with
          [
              Return=void
          ]
c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): error C2770: invalid expli
cit template argument(s) for 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (_
_cdecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)' [C:\Users\tondelli\Des
ktop\pytorchPlusPlus\testCustomLib\build\trainCustomLib.vcxproj]
          with
          [
              _Ty=int
          ]
  C:\Users\tondelli\Desktop\CustomLibTorch\include\ATen/core/boxing/boxing.h(52): note: see declaration of 'c10::impl::
  boxAndCallBoxedFunc'
c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): error C2893: Failed to spe
cialize function template 'Result c10::impl::boxAndCallBoxedFunc(c10::KernelFunction::InternalBoxedKernelFunction (__cd
ecl *),c10::OperatorKernel *,const c10::OperatorHandle &,Args...,enable_if<_Test,_Ty>::type)' [C:\Users\tondelli\Deskto
p\pytorchPlusPlus\testCustomLib\build\trainCustomLib.vcxproj]
          with
          [
              _Ty=int
          ]
  c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): note: With the following
   template arguments:
  c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): note: 'Result=Return'
  c:\users\tondelli\desktop\customlibtorch\include\aten\core\boxing\KernelFunction_impl.h(66): note: 'Args={at::Tensor
  &, bool}'`

## To Reproduce

1. you can download my copiled libtorch version from here https://drive.google.com/open?id=17hRtgkFcWAE14fmsvBoEZa36h9PQdOra

2. Create a simple LibTorch example based on https://pytorch.org/cppdocs/installing.html

## Environment

Collecting environment information...
PyTorch version: 1.4.0a0+1350b99
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 419.17
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] numpydoc==0.9.1
[pip] torch==1.4.0a0+1350b99
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-include               2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.14           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] torch                     1.4.0a0+1350b99          pypi_0    pypi

**Comment by peterjc123** [comment]
Last time we met this when compiling torchvision using VS 2017 15.16 [here](https://circleci.com/gh/pytorch/vision/32385?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link&fbclid=IwAR2CUUfQzPSxdno_YCEHOeslpTI2jRRVHX0W62bpJrwo-nEVjfqPZRG8Qew) and finally we resolved that problem by updating to VS 2019.

**Comment by mruberry** [comment]
Build-related issues like this are best asked on the forums: https://pytorch.org/.

Thanks @peterjc123 for your helpful comment ;)

**Comment by kakri** [comment]
" Last time we met this when compiling torchvision using VS 2017 14.16 [here](https://circleci.com/gh/pytorch/vision/32385?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link&fbclid=IwAR2CUUfQzPSxdno_YCEHOeslpTI2jRRVHX0W62bpJrwo-nEVjfqPZRG8Qew) and finally we resolved that problem by updating to VS 2019. Alternatively, you could downgrade to VS 2017 14.11."

While I was trying to downgrade to v14.11 toolset, as default v14.16 latest v141 tools is also getting installed. The errors are remain still unresolved. Can you help out in resolving the errors C2672,C2770,C2893 pytorch nightly build
