### ISSUE TITLE
Using non-system compiler and undefined references to pthread 

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/pytorch#30570]
On a Centos which has gcc 4.8.5 by default, I have built gcc-6.1.0 from source and want to tell pytorch to use that.

I have specified CC and CXX as below:
```
$ export CC=/storage/users/mnaderan/tools/gcc-6.1.0/bin/gcc
$ export CXX=/storage/users/mnaderan/tools/gcc-6.1.0/bin/g++
```
However, I get this error:
```
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /storage/users/mnaderan/pt/pytorch/build/CMakeFiles/CMakeTmp

Run Build Command(s):/bin/gmake cmTC_bceed/fast && gmake: Warning: File `Makefile' has modification time 19 s in the future
/bin/gmake -f CMakeFiles/cmTC_bceed.dir/build.make CMakeFiles/cmTC_bceed.dir/build
gmake[1]: Entering directory `/storage/users/mnaderan/pt/pytorch/build/CMakeFiles/CMakeTmp'
gmake[1]: Warning: File `CMakeFiles/cmTC_bceed.dir/flags.make' has modification time 19 s in the future
Building C object CMakeFiles/cmTC_bceed.dir/src.c.o
/storage/users/mnaderan/tools/gcc-6.1.0/bin/gcc   -DCMAKE_HAVE_LIBC_PTHREAD -fPIE   -o CMakeFiles/cmTC_bceed.dir/src.c.o   -c /storage/users/mnaderan/pt/pytorch/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_bceed
/storage/users/mnaderan/tools/cmake-3.15.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bceed.dir/link.txt --verbose=1
/storage/users/mnaderan/tools/gcc-6.1.0/bin/gcc  -DCMAKE_HAVE_LIBC_PTHREAD   -rdynamic  CMakeFiles/cmTC_bceed.dir/src.c.o  -o cmTC_bceed
CMakeFiles/cmTC_bceed.dir/src.c.o: In function `main':
src.c:(.text+0x2f): undefined reference to `pthread_create'
src.c:(.text+0x3b): undefined reference to `pthread_detach'
src.c:(.text+0x4c): undefined reference to `pthread_join'
src.c:(.text+0x60): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
```
Any idea?

**Comment by mruberry** [comment]
This question is more appropriate for the forums: https://discuss.pytorch.org/.

Please try asking there.

**Comment by mahmoodn** [comment]
None of my questions on the forum has been answered. But here I get feedback.
I don't know if other see my posts or not!
https://discuss.pytorch.org/t/using-non-system-compiler-and-undefined-references-to-pthread/62537

**Comment by mruberry** [comment]
@mahmoodn I'm sorry to hear the forums haven't answered your issue.

I think it's just hard for people to help with build issues. Build environments are very different from each other.

**Comment by mahmoodn** [comment]
I think so. If I know where the cmake command is created, I can go for it and test different options. However, I myself haven't figured out where that happens.

**Comment by mahmoodn** [comment]
@mruberry  @xuhdev 
I checked with cmake guys and it seems that there is a problem with 
```
CMake Error at third_party/benchmark/CMakeLists.txt:231 (message):
  Failed to determine the source files for the regular expression backend
```
So, the error lies in
```
# C++ feature checks
# Determine the correct regular expression engine to use
cxx_feature_check(STD_REGEX)
cxx_feature_check(GNU_POSIX_REGEX)
cxx_feature_check(POSIX_REGEX)
if(NOT HAVE_STD_REGEX AND NOT HAVE_GNU_POSIX_REGEX AND NOT HAVE_POSIX_REGEX)
  message(FATAL_ERROR "Failed to determine the source files for the regular expression backend")
endif()
```
These CXX checks are related to google benchmark which is defined [here](https://github.com/google/benchmark/blob/505be96ab23056580a3a2315abba048f4428b04e/cmake/CXXFeatureCheck.cmake).
It seems that file doesn't log verbosity and it is not clear what is the problem exactly.

It may not directly related to pytorch.
Thanks.

**Comment by xuhdev** [comment]
Is this the same issue as your original comment? If not, could you open a new issue and provide more information (e.g., your system environment, cmake version, PyTorch version)? Can you also manually examine whether you have any regex engine installed?

**Comment by mahmoodn** [comment]
Actually yes. But cmake guys says that pthread is something else and there is a problem with cxx features which is related to benchmark/
I have been confused with this problem for some weeks.
The question is how thirdparty/benchmark is included in pytorch build system. [Here](https://github.com/google/benchmark/issues/914).

**Comment by mahmoodn** [comment]
Since this thread is going to be messy, I will close it and open a new issue for cxx features. I think this is the main problem.

**Comment by solidcc2** [comment]
Hi, I have the same problem with you. And any suggestions for me? I will be very grateful for this.
I need to compile with the source of torch v1.3.0

System Info:
Centos7
Linux localhost.localdomain 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
conda 4.9.2
Python 3.5.6 :: Anaconda, Inc.
gcc installed by 'conda install -c omgarcia gcc-6'   gcc/g++ 6.1.0
cmake installed by 'conda install cmake'   cmake 3.12.2
cuda 10.0
cudnn 7.6.5

Below is the key failure hint:
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- compiled but failed to run
CMake Error at third_party/benchmark/CMakeLists.txt:231 (message):
  Failed to determine the source files for the regular expression backend

And I have tried to compile with python=3.6 , but got the same error infos.

Thank you
