### ISSUE TITLE
Need ONNX helper function for creating tensor constants/scalars

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3058]
Similar to what we do in the implementation of Index (in terms of Slice), we often need to allocate tensor constants. We need to make it easier to do this by adding some helper functions (similar to how we have the `op` helper function.)

**Comment by houseroad** [comment]
Now since we don't support 0-dimension tensor, we cannot create scalars...

**Comment by houseroad** [comment]
we have constant and _z support for constant tensor and scalar support now. :-)
