### ISSUE TITLE
clang 9 segfaults when trying to compile PyTorch

### ISSUE THREAD

**Issue by skn123** [pytorch/pytorch#30584]
## 🐛 Bug

During compilation with mainline clang (9.0.1) in Ubuntu 18.04, compilation crashes.
## To Reproduce
Either building with CMake or building the python binding causes this bug

1.
1.
1.

clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.0.1-+201911131414230800840845a1eea-1~exp1~20191113225612.79 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/SobolEngineOps-4be05a.cpp
clang: note: diagnostic msg: /tmp/SobolEngineOps-4be05a.sh
clang: note: diagnostic msg: 

********************
caffe2/CMakeFiles/torch.dir/build.make:1824: recipe for target 'caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/SobolEngineOps.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/SobolEngineOps.cpp.o] Error 254
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5809: recipe for target 'caffe2/CMakeFiles/torch.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/mnt/a442cd4a-5fc8-4d5f-affa-1a614edfaac9/srcs/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/mnt/a442cd4a-5fc8-4d5f-affa-1a614edfaac9/srcs/pytorch/tools/setup_helpers/cmake.py", line 337, in build
    self.run(build_args, my_env)
  File "/mnt/a442cd4a-5fc8-4d5f-affa-1a614edfaac9/srcs/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Mainline branch
 - OS (e.g., Linux): Ubuntu 18.04.1
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): sudo python3 setup.py install
 - Python version:3.6
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information:clang 9.0.1

## Additional context

The problem is coming from this line:
https://github.com/pytorch/pytorch/blob/dd52f50fc85e6710f020936c1fc5f14673508350/aten/src/ATen/native/SobolEngineOpsUtils.h#L153

If I change this to :
``static int64_t initsobolstate[1111][13]''
then, the code builds fine.

cc @ezyang @gchanan @zou3519 @malfet

**Comment by pietern** [comment]
Thanks for reporting. We do run CI with clang, but I believe with an older version.

Is there any other clang crash information available, e.g. a stack?

cc @vishwakftw because of Sobol.

**Comment by pietern** [comment]
cc @kostmo @ezyang We should consider adding builds for newer clang versions.

**Comment by skn123** [comment]
@pietern I do not have any other information. I wanted it to build correctly and that's why reported the (potential) fix also. 9.0.1 is as of today (Dec 2019) the latest version of clang.

**Comment by pietern** [comment]
@skn123 Now I see the fix -- removing `constexpr`. I thought it removed the assignment, which would make the code invalid, but that's not the case...

**Comment by Bo98** [comment]
Just to add, this now affects Xcode 11.4 (Apple Clang 11.0.3) which is based on LLVM 9.

**Comment by malfet** [comment]
This huge array doesn't need to be defined in the header (nor does it have to be constexpr)

**Comment by malfet** [comment]
Will something like that solve a problem even on latest clangs: https://github.com/pytorch/pytorch/pull/37086

**Comment by malfet** [comment]
@Bo98 can you please check if above PR fixes the issue for your version of clang?

**Comment by ngimel** [comment]
This should be fixed on master, please reopen if this is not the case.
