### ISSUE TITLE
The number of batches in epoch is affected by (num_workers + IterableDataset)

### ISSUE THREAD

**Issue by huntzhan** [pytorch/pytorch#30599]
## 🐛 Bug

The `num_workers` affect the total number of batches in an epoch when passing the Iterable-style datasets to dataloader. This behavior is inconsistent with the map-style datasets.

## To Reproduce

Map-style datasets (size = 5):

```
from torch.utils.data import *

list(DataLoader([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], batch_size=2, num_workers=4))

Out:
[tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9])]
```

Iterable-style datasets (size = 5 * 4 = 20):

```
from torch.utils.data import *
import random

class MockIterableDataset(IterableDataset):
    def __iter__(self):
        nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        random.shuffle(nums)
        for i in nums:
            yield i

list(DataLoader(MockIterableDataset(), batch_size=2, num_workers=4))

Out:
[tensor([6, 0]),
 tensor([5, 8]),
 tensor([0, 1]),
 tensor([8, 2]),
 tensor([5, 9]),
 tensor([6, 2]),
 tensor([4, 9]),
 tensor([1, 0]),
 tensor([1, 4]),
 tensor([4, 0]),
 tensor([7, 8]),
 tensor([4, 5]),
 tensor([7, 2]),
 tensor([7, 1]),
 tensor([5, 3]),
 tensor([3, 7]),
 tensor([8, 3]),
 tensor([9, 3]),
 tensor([2, 6]),
 tensor([6, 9])]
```

## Expected behavior

The `num_workers` should not affect the total number of batches in an epoch when passing the Iterable-style datasets to dataloader.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SsnL** [comment]
This behavior as well as the recommended solution are well documented: https://pytorch.org/docs/stable/data.html#iterable-style-datasets

**Comment by huntzhan** [comment]
Thank you for confirming this behavior is by design.
