### ISSUE TITLE
Load data directly from GPU without copy to CPU

### ISSUE THREAD

**Issue by solarflarefx** [pytorch/pytorch#30595]
Hi all,

I am relatively new to PyTorch (coming from a TensorFlow background) and I was wondering about the following.

In most applications (at least from my experience) source data is usually coming from the CPU, whether that be in training or deployment. Many times, developers will train a model utilizing the GPU for training and then may or may not use the GPU in deployment, depending on the application and needs. However, even when the GPU is used in deployment, from what I have seen the data source to the model is usually stored in disk, manipulated (perhaps a formatting process), and then passed through the model.

In my case, I am working within a pipeline architecture where the source data is already in the GPU and I need to pass this data through a model. So far at each phase of the pipeline the data resides in the GPU and stays there (as a Cuda array).  I need to insert a trained model into the pipeline. As of now, the only way I know of using the model is to pass the data from the GPU to the CPU and then pass the data into the model (and perhaps then get the data from the CPU and pass it to the GPU again for use in the pipeline). The is seemingly very inefficient (my datasets are pretty large and speed of the overall pipeline is important). I was wondering if it is possible to pass data to the learned model directly from the GPU and then continue passing data through the pipeline without having to do copies to/from the CPU. I am wondering if the data pipelines in PyTorch would allow for something like this. Or if there is another approach, I am open to that as well.

**Comment by xsacha** [comment]
I've posted this a few times but cannot find it right now.

Example for changing data from a cv::cuda::GpuMat to a torch::Tensor (supporting float type and byte type, converting to float)

```C++
void deleter(void *arg){};
    torch::Tensor matToTensor(const cv::cuda::GpuMat &image, int device)
    {
        bool isByte = (image.type() & 0xF) < 2;
        auto chans = image.channels();
        std::vector<int64_t> dims = {image.rows, image.cols, chans};
        std::vector<int64_t> strides = {(int64_t)image.step1(), chans, 1};
        auto options = torch::TensorOptions().dtype(isByte ? torch::kByte : torch::kFloat).device(torch::kCUDA, device);
        auto tensorImage = torch::from_blob(image.data, dims, strides, deleter, options);

        if (isByte)
        {
            tensorImage = tensorImage.to(torch::kFloat);
        }

        return tensorImage;
    }
```

The part you are interested in: **torch::from_blob**

**Comment by pietern** [comment]
Thanks for posting your solution, @xsacha.

Please use the forums at https://discuss.pytorch.org/ for questions and discussion.

We use the issue tracker for issues only.
