### ISSUE TITLE
torch division is not consistent

### ISSUE THREAD

**Issue by akbir** [pytorch/pytorch#30613]
## 🐛 Bug

`torch.div` is not consistent with different versions torch.tensor([0]) and torch.zeros(1)

## To Reproduce
Simply run the script
```
torch.div(torch.ones(1), torch.zeros(1))
# tensor([inf])
torch.div(torch.tensor([1]), torch.tensor([0]))
# Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```

## Expected behavior
The behavior should be consistent. 

## Environment

 - PyTorch Version : 1.3.1
 - OS : Linux
 - How you installed PyTorch: `pip`
 - Python version: 3.8
 - CUDA/cuDNN version: 10.1

**Comment by pietern** [comment]
Thanks for the report.

cc @gchanan

**Comment by mruberry** [comment]
I believe this is fixed now that our division operator always performs true division. @akbir, if you're still seeing inconsistent behavior, would you update and reopen this issue?
