### ISSUE TITLE
Problem installation via pip pytorch 1.3.0 and 1.2.0 on windows cuda 10.0

### ISSUE THREAD

**Issue by carlosmenezesanjos** [pytorch/pytorch#30631]
## 🐛 Bug

Installing via pip using this command: pip install torch==1.2.0+cu100 torchvision==0.4.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

Doesn't work as shown bellow

When trying to install via pip for version 1.2.0 for cuda 10.0 i had to use a direct link like this:

pip install https://download.pytorch.org/whl/cu100/torch-1.2.0-cp36-cp36m-win_amd64.whl

For pytorch 1.3.0 and 1.3.1 couldn't find a link on https://download.pytorch.org/whl/torch_stable.html

## To Reproduce

pip install torch==1.2.0+cu100 torchvision==0.4.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.2.0+cu100 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu92)
ERROR: No matching distribution found for torch==1.2.0+cu100

The same happen for torchvision 0.4.0, 0.4.1 and 0.4.2

**Comment by peterjc123** [comment]
As for cuda 10.0 and pytorch 1.2.0, the version specifier is 1.2.0. And we don't build pytorch 1.3.x binaries with CUDA 10.0, so you should use the CUDA 10.1 ones instead, which has the version specifer of 1.3.0 and 1.3.1.

**Comment by peterjc123** [comment]
You could get more details here: https://github.com/pytorch/pytorch/issues/23656.
