### ISSUE TITLE
What is the different between nn.Functional.conv2d and nn.Conv2d?It seems a bit redundant?

### ISSUE THREAD

**Issue by wulongjian** [pytorch/pytorch#30654]
## ❓ Questions and Help
Hi,I have just started learning pytorch recently. In the official website tutorials, I often see nn.Conv2d and nn.Functional.conv2d. I don't understand the difference between the two writing methods. It seems that one of these two is enough.

**Comment by pietern** [comment]
Please use the discussion forums for questions: https://discuss.pytorch.org/.

**Comment by wulongjian** [comment]
OK, thanks.
