### ISSUE TITLE
Pytorch android Tensor.Shape() function not producing expected results.

### ISSUE THREAD

**Issue by nauyan** [pytorch/pytorch#30652]
I am loading an image from assets folders in the form of bitmap. Next, I convert it into Tensor using **TensorImageUtils.bitmapToFloat32Tensor()** method after that when I check the shape of Image using the **.Shape()** function and print it on the log I am getting values like **Tensor Shape is [J@41c1e52** whereas If I just print the tensor on the console the output I get is **Tensor([1, 3, 384, 384], dtype=torch.float32)**. Can you please verify the issue with shape function?

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 18
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.5
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by pietern** [comment]
This sounds like a stringification issue. Can you run some kind of `toString()` function on the shape?

**Comment by ljk53** [comment]
Currently tensor.shape() simply returns a raw long[]: https://github.com/pytorch/pytorch/blob/master/android/pytorch_android/src/main/java/org/pytorch/Tensor.java#L351

You should be able to use "System.out.println(**Arrays.toString**(tensor.shape()));" to print its content correctly.

@dreiss @IvanKobzarev - do you think it's worth creating a shape type?

**Comment by nauyan** [comment]
@ljk53 System.out.println(Arrays.toString(tensor.shape())); does certainly print the shape of tensor but tensor.shape() doesn't print the shape.

**Comment by dreiss** [comment]
I don't think it's worth creating a shape type, or returning a `List<Integer>` instead of the current `int[]`.  Let's just leave this as-is.
