### ISSUE TITLE
test_DistributedDataParallel is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#30676]
https://app.circleci.com/jobs/github/pytorch/pytorch/3760117

```
Dec 03 17:59:26 Traceback (most recent call last):
Dec 03 17:59:26   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Dec 03 17:59:26     self.run()
Dec 03 17:59:26   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Dec 03 17:59:26     self._target(*self._args, **self._kwargs)
Dec 03 17:59:26   File "test_distributed.py", line 2082, in _run
Dec 03 17:59:26     rank=self.rank
Dec 03 17:59:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
Dec 03 17:59:26     store, rank, world_size = next(rendezvous_iterator)
Dec 03 17:59:26   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 168, in _env_rendezvous_handler
Dec 03 17:59:26     store = TCPStore(master_addr, master_port, world_size, start_daemon)
Dec 03 17:59:26 RuntimeError: Address already in use
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
Two possible causes I can imagine:
* The OS had something hogging onto port 29500 (which I assume this test was using)
* The Python process didn't GC the TCP store from the previous test fast enough

We can consider using the file store for all cases where we don't specifically test the TCP store.

**Comment by zhaojuanmao** [comment]
has not been reported in the past 2 years, also TCP store allows dynamic port allocation now and this issue should not happen any more, closing it.
