### ISSUE TITLE
Support the unary quantized operator

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#30675]
## 🐛 Bug

There is already one issue in pytorch forum: https://discuss.pytorch.org/t/static-quantization-error/61727. When we apply the unary operator like "-x5", the runtime will error out.

## To Reproduce

https://discuss.pytorch.org/t/static-quantization-error/61727

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
This can be achieved by doing mul_scalar(x5, -1). 
Closing the issue since there doesn't seem to be a requirement for this feature since this was filed.
