### ISSUE TITLE
PyTorch - ONNX Export Error with Opset 11 caused by F.Interpolate/nn.Upsampling...2d

### ISSUE THREAD

**Issue by glenn-jocher** [pytorch/pytorch#30681]
## 🐛 Bug

PyTorch model export to ONNX fails when using PyTorch 1.3.1 or nightly and ONNX 1.5.0. Failure is caused by all upsample operations: 

- `nn.UpsamplingBilinear2d(scale_factor=2)`
- `nn.UpsamplingNearest2d(scale_factor=2)`
- `F.interpolate(x, scale_factor=2)`

Error message:
```bash
torch version 1.4.0.dev20191127
onnx version 1.5.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/iD/upsample_error_reproduce.py", line 28, in <module>
    onnx.checker.check_model(oml)
  File "/Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Resize_23) has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "input" input: "20" input: "20" input: "23" output: "24" name: "Resize_23" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }
```

## To Reproduce

```python
# conda install pytorch torchvision -c pytorch-nightly
# conda install -c conda-forge onnx
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # fails
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # fails
        x = F.interpolate(x, scale_factor=2)  # fails
        return x


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
onnx.checker.check_model(oml)
```

## Expected behavior

Successful export and ONNX verification.

## Environment

```bash
Collecting environment information...
PyTorch version: 1.4.0.dev20191127
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.1
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.4.0.dev20191127
[pip] torchvision==0.5.0a0+91a78e1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.4.0.dev20191127         py3.7_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20191127        py37_cpu    pytorch-nightly
```

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by kossnick** [comment]
+1, I have the same issue.

**Comment by lara-hdr** [comment]
@glenn-jocher, it doesn't seem like the issue is from the exporter. I tried your code and the error is happening in "onnx.checker.check_model(oml)". But when I remove the call to check_model() and try running the exported model (with onnxruntime), it runs and predicts the right output.

`import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx
import onnxruntime
import numpy as np


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # fails
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # fails
        x = F.interpolate(x, scale_factor=2)  # fails
        return x


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
output = tml(img)
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
#onnx.checker.check_model(oml)

ort_sess = onnxruntime.InferenceSession("model.onnx")

def to_numpy(tensor):
    if tensor.requires_grad:
        return tensor.detach().cpu().numpy()
    else:
        return tensor.cpu().numpy()
input, _ = torch.jit._flatten(img)
output, _ = torch.jit._flatten(output)

inputs = list(map(to_numpy, input))
outputs = list(map(to_numpy, output))

print(img.detach().numpy().shape)
ort_inputs = dict((ort_sess.get_inputs()[i].name, input) for i, input in enumerate(inputs))
#print(ort_inputs['x'].shape)
ort_outs = ort_sess.run(None, ort_inputs)

# compare onnxruntime and PyTorch results
assert len(outputs) == len(ort_outs), "number of outputs differ"

# compare onnxruntime and PyTorch results
[np.testing.assert_allclose(out, ort_out) for out, ort_out in zip(outputs, ort_outs)]
`

**Comment by lara-hdr** [comment]
@glenn-jocher, I tried it with onnx 1.6.0 and it does not produce the error.

**Comment by glenn-jocher** [comment]
@lara-hdr thanks, I thought I was using the latest version of ONNX, but I guess not. I will install 1.6.0 and try again.

**Comment by glenn-jocher** [comment]
@lara-hdr how did you install PyTorch and ONNX to get this to work? I installed ONNX 1.6 in a new Conda 3.7 environment, but receive an error on `import onnx`. See https://github.com/onnx/onnx/issues/2493

```python
>>> import onnx

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libprotobuf.20.dylib
  Referenced from: /Users/glennjocher/opt/anaconda3/envs/pn2/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by glenn-jocher** [comment]
@lara-hdr I tried out a `pip install onnx` command instead of a conda install, and **the pip version of onnx 1.6 does work**, however I'm unable to export my onnx model to coreml (my final destination is an iOS app), as there is an error message regarding an onnx-coreml version constraint **onnx==1.5**, which produces the original error above.


Error message
```bash
ERROR: onnx-coreml 1.0 has requirement onnx==1.5.0, but you'll have onnx 1.6.0 which is incompatible.
```

To Reproduce
```bash
$ pip install onnx

Proceed (y/n)? y
  Successfully uninstalled onnx-1.5.0
(pytorch_nightly) glennjocher@JermainsMacBook yolov3 % pip install onnx
Collecting onnx
  Using cached https://files.pythonhosted.org/packages/e3/ed/56a6c94cbe98e7b6ad783ed5ce63c174eab6a862a56111a04156effda135/onnx-1.6.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: typing-extensions>=3.6.2.1 in /Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages (from onnx) (3.7.4.1)
Requirement already satisfied: six in /Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages (from onnx) (1.13.0)
Requirement already satisfied: numpy in /Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages (from onnx) (1.17.4)
Requirement already satisfied: protobuf in /Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages (from onnx) (3.11.1)
Requirement already satisfied: setuptools in /Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages (from protobuf->onnx) (42.0.2.post20191203)
ERROR: onnx-coreml 1.0 has requirement onnx==1.5.0, but you'll have onnx 1.6.0 which is incompatible.
Installing collected packages: onnx
Successfully installed onnx-1.6.0
```

**Comment by CConory** [comment]
> @glenn-jocher, I tried it with onnx 1.6.0 and it does not produce the error.

hallo，can i ask your pytorch version?

**Comment by cloudrivers** [comment]
meet the same issue.

pytorch : 1.3.1
onnx: 1.5.0

Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 52, in detect
    onnx.checker.check_model(model)  # Check that the IR is well formed 
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "675" input: "698" input: "698" input: "697" output: "699" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }

**Comment by cloudrivers** [comment]
after upgrade onnx to 1.6.0. meet another issue.

pytorch : 1.4.0
onnx: 1.6.0
Namespace(agnostic_nms=False, cfg='cfg/yolov3.cfg', classes=None, conf_thres=0.3, device='', fourcc='mp4v', half=False, img_size=416, iou_thres=0.5, names='data/myclass.names', output='output', save_txt=False, source='data/samples', view_img=False, weights='weights/best.pt')
Using CPU

Segmentation fault (core dumped)

**Comment by glenn-jocher** [comment]
@cloudrivers you might want to try a premade environment. The export process for yolov3-spp currently works correctly, so we are unable to reproduce.

- **Your environment.** If your issue is not reproducible in a common environment, such as a [GCP Quickstart Guide](https://github.com/ultralytics/yolov3/wiki/GCP-Quickstart) VM we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, PyTorch >= 1.4 etc. You can also use our [Google Colab Notebook](https://colab.research.google.com/drive/1G8T-VFxQkjDe4idzN8F-hbIBqkkkQnxw) and our [Docker Image](https://hub.docker.com/r/ultralytics/yolov3) to test your code in working environment.

**Comment by cloudrivers** [comment]
Hi @glenn-jocher, I tried python3.7.4 & 3.7.6, PyTorch 1.4.0, onnx 1.6.0.  onnx.checker.check_model(oml) will Segmentation fault.

python3 detect.py  --cfg cfg/yolov3-spp-1cls.cfg --weights weights/best.pt  --names data/myclass.names
Namespace(agnostic_nms=False, cfg='cfg/yolov3-spp-1cls.cfg', classes=None, conf_thres=0.3, device='', fourcc='mp4v', half=False, img_size=416, iou_thres=0.5, names='data/myclass.names', output='output', save_txt=False, source='data/samples', view_img=False, weights='weights/best.pt')
Using CPU

Segmentation fault
