### ISSUE TITLE
Remove deprecated codepath for old-style autograd.Function

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#30696]
The legacy python `autograd.Function` were advertised as being removed from 1.3 onward [see comment](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_function.cpp#L620-L622). So it should be safe to delete now.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/blob/13e4ee7883106c412d3efe17fbbe8087a6d4c5e2/torch/csrc/autograd/python_function.cpp#L620-L622 is the thread to pull on -- there should be a bunch of code in both C++ and Python that we can delete.

**Comment by gchanan** [comment]
We should probably turn the warning into an error, hopefully in the init, but in the place above too is probably okay.

**Comment by glaringlee** [comment]
Removed _do_forward. Looking into removing more legacy functions, will update pr later.
