### ISSUE TITLE
[ONNX] We should not export with com.facebook domain

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3070]
Right now, our ONNX exports always export with 'com.facebook' domain, but the intended semantics of this is to identify the *model*, not the model creator. So it's inappropriate for us to slap this domain on the models; instead it should be a configurable parameter.

**Comment by houseroad** [comment]
Shall we modify the export api to let user fill the model domain?

**Comment by ezyang** [comment]
Yes. While we're at it, we should also let them configure the model version and model name.

**Comment by houseroad** [comment]
The interesting thing is there is no model name in model.proto now... Very funny.

**Comment by ezyang** [comment]
"Oops"

**Comment by ezyang** [comment]
This is fixed.
