### ISSUE TITLE
Build error about C++14 required

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#30722]
## Bug

Got something like `#error C++14 required` today.
Previous day was fine so it should be a new regression.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2

**Comment by xkszltl** [comment]
https://github.com/pytorch/pytorch/commit/c0299d2707b0d2100d76edfc050f805c90c959eb

This may be related since it contains `--std=c++11`

**Comment by zou3519** [comment]
We've recently started requiring a C++14 compiler for pytorch: https://github.com/pytorch/pytorch/blob/master/README.md#from-source. @smessmer can answer any questions you might have about this.

**Comment by xkszltl** [comment]
@zou3519 
I think you misread this.
We use gcc-8, so it is not because we use an old compiler.

**Comment by xkszltl** [comment]
Oops sorry, seems it is in torchvision instead....
![image](https://user-images.githubusercontent.com/5203025/70176968-48287700-168e-11ea-8e97-fc25b882622f.png)

**Comment by zou3519** [comment]
@xkszltl sorry, you're right, I completely misread this. If there's a build issue in torchvision then please submit an issue to https://github.com/pytorch/vision/issues.

**Comment by rilesdg3** [comment]
Had same problem. Using Eclipse IDE I had to set the **Language standard** to "blank" i.e. nothing in there, and add -std=c++14 to **Other dialect flags**

**Comment by alan101-tech** [comment]
I met this problem when using gcc 4.8.5, after updating to gcc 7.3.1, it was solved.
