### ISSUE TITLE
Triangular system solver using BLAS

### ISSUE THREAD

**Issue by juancamilog** [pytorch/pytorch#3073]
CUDA does not implement the trtrs function for the triangular solver operation. However, through CUBLAS, it provides the trsm and trsv functions, which appear to do exactly the same as trtrs.

As far as I can tell, common CPU BLAS implementations provide the trsm and trsv functions (e.g. OpenBLAS and MKL). MAGMA also provides an implementation of both.

This feature would allow for faster computation of the backward function for Cholesky factorization (potrf). both on CPU and GPU. [The current implementation](https://github.com/pytorch/pytorch/blob/14d8c034245708c0c9fb792a955223241ddaee78/torch/autograd/_functions/linalg.py#L143) uses a solver for general matrices, which requires computing an LU factorization (done internally in gesv). Using the triangular system solver, the factorization step is no longer required.

Cholesky factorization and triangular system solve operations are commonplace in Bayesian machine learning methods, when dealing with Gaussian distributions.

**Comment by samuela** [comment]
I also need a differentiable `trtrs`!

**Comment by soumith** [comment]
@samuela we'll implement it. @SsnL can take care of it.

**Comment by SsnL** [comment]
looking into this

**Comment by SsnL** [comment]
Actually, together with many other linalg methods, both CPU and GPU `potrf` now all directly using LAPACK/MAGMA native `potrf` implementation:

CPU: https://github.com/pytorch/pytorch/blob/14d8c034245708c0c9fb792a955223241ddaee78/torch/lib/TH/generic/THTensorLapack.c#L590-L612
GPU: https://github.com/pytorch/pytorch/blob/14d8c034245708c0c9fb792a955223241ddaee78/torch/lib/THC/generic/THCTensorMathMagma.cu#L519-L552

**Comment by lucasb-eyer** [comment]
Yes, I was looking for `torch.trsm` and `torch.trsv` exactly while implementing the log-likelihood for a reparameterized gaussian. Currently, I'm forced to use `torch.potrs` which is calling `trsm` twice, which is once more than necessary in this application!

**Comment by to-mi** [comment]
This might be a useful reference for this:
Seeger et al. Auto-Differentiating Linear Algebra
https://arxiv.org/abs/1710.08717

**Comment by fmassa** [comment]
#6648 added CUDA support for `trtrs`, but I believe we still don't have the derivatives implemented, so I'm keeping this open for the moment.

**Comment by fehiepsi** [comment]
@fmassa Derivatives are available at #3972 (worked for both gpu and cpu).

**Comment by fmassa** [comment]
Thanks @fehiepsi , closing the issue then.
