### ISSUE TITLE
[ONNX] ONNX broadcasting plan

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3075]
There's an ongoing discussion about broadcasting in https://github.com/onnx/onnx/issues/83

In the meantime, here is our plan for PyTorch:

1. In the short term, we are going to implement add by scalar using the `broadcast=1` attribute in ONNX. So for example, if we have x + 3, we export this as `Add[broadcast=1] x const_tensor`, where `const_tensor` is a 1-dimensional, 1 element tensor containing 3

2. Longer term, if we get a `Broadcast` op in ONNX, we can drop the `broadcast=1` attribute, export a zero-dim tensor containing 3, and use the `Broadcast` operator to get the zero dim into a compatible shape. ()the onnx-caffe2 backend will handle translating this back into a broadcast=1 attribute.) One minor short term problem that must be overcome is we can't actually create zero-dim tensors yet, so we need to wait for scalars to become a thing or special case it in symbolic.

**Comment by houseroad** [comment]
Here are more details:
Condition 1: Two tensors have different dimensions, easy to handle, just extend the dimension from right to left.
Condition 2: Two tensors have same dimension, but different shape, raise exception
Condition 3: One tensor and one constant, turn one constant into a 1d tensor.

**Comment by ezyang** [comment]
This is fixed.
