### ISSUE TITLE
cannot install pytorch on Ubuntu

### ISSUE THREAD

**Issue by ramybaly** [pytorch/pytorch#3078]
I'm trying to install pytorch on Ubuntu using pip (python 3.6, cuda 8). I keep getting the "wheel is not supported" error.

my machine is 64-bit.

any advise? Thanks

**Comment by esube** [comment]
Check out the source and just runs: python setup.py install instead.

**Comment by zou3519** [comment]
@ramybaly How do the new pytorch 0.3 binaries work for you?
ie `pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl`

**Comment by mruberry** [comment]
Closing due to age. @ramybaly, I hope you're not still having trouble installing PyTorch ;) But if you are, please file a new issue!
