### ISSUE TITLE
How accurate is export_chrome_trace?

### ISSUE THREAD

**Issue by rabbitwayne** [pytorch/pytorch#30791]
Wonder how accurate is the chrome trace generated by torch.autograd.profiler.profile.export_chrome_trace()?

Are the events shown in the trace accurate? Do they accurately record the times when all these api calls and cuda kernels started and ended? How much overhead is added by the profiler?

From my experience, the cpu time by the profiler is highly unreliable and significantly affected by the asynchronous wait on CUDA Kernels. Can I trust the results generated by export_chrome_trace?

Thanks a lot!

**Comment by gchanan** [comment]
Please refer questions to: https://discuss.pytorch.org/.
