### ISSUE TITLE
How can I implement "nn.unFold" on 5D tensor?

### ISSUE THREAD

**Issue by EricKani** [pytorch/pytorch#30798]
❓ How can I implement "nn.unFold" on 5D tensor?

I am implementing an operation on 3D image. I found I need "nn.unFold" function in my process. But until now, pytorch does not have official implementation in latest release version. 

I want to implement it in official release code form by myself. But I am a little confused by the relationship  between implementation part of c++ and cuda code. 

Could some one give me some suggestions that which files I should refer to corresponding to implementation of "nn.unFold" in 4D version...

**Comment by albanD** [comment]
You might be able to get some inspiration from the implementation we had in the old torch7 library [here](https://github.com/torch/nn/blob/872682558c48ee661ebff693aa5a41fcdefa7873/lib/THNN/generic/VolumetricConvolutionMM.c#L99-L263).
I'm not sure how efficient it will be though.

**Comment by waterljwant** [comment]
Hi, I got the same problem. I try to use "Tenror.unfold()" to implement the function, however, it consumes a lot of memory.
k = kernel_size
s = step
d = dilation
f= x.unfold(2, k, s).unfold(3, k, s).unfold(4, k, s) 
f= f[:, :, ::d, ::d, ::d, :, :, :]

**Comment by mruberry** [comment]
This question is more appropriate to our forums, here: https://discuss.pytorch.org/.
