### ISSUE TITLE
How to Build pytorch with local protobuf rather than third_party/protobuf?

### ISSUE THREAD

**Issue by Raneee** [pytorch/pytorch#30796]
## ❓ Questions and Help
I want to build pytorch with my own os built protobuf lib rather than third_part/protobuf, Which prefix to change, Can anyone help me?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by gchanan** [comment]
See message about the discussion forum.
