### ISSUE TITLE
RPC threads should return an error message instead of crash on failures

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#30819]
The recv function in [`ProcessGroupAgent`](https://github.com/pytorch/pytorch/blob/f2a2fec47cd7f3b715189338e45c6aebdf5f65f2/torch/csrc/distributed/rpc/process_group_agent.cpp#L367) would crash if there are failures during `wireDeserialize`, or unrecognized message types, or races in futureTimeouts map, etc. However, that would result in bad debugging experiences, as the caller would only see a timeout instead of what really went wrong. A better solution would be capture the failures, wrap them into an error message and set the futures according to show the error details on the caller. 

This also relates to #29703 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by mrshenli** [comment]
cc @zdevito

**Comment by rohan-varma** [comment]
I believe that https://github.com/pytorch/pytorch/pull/31023 and @jjlilley's PR https://github.com/pytorch/pytorch/pull/31299 should help with some of these issues.

**Comment by rohan-varma** [comment]
Should be fixed with https://github.com/pytorch/pytorch/pull/31023, https://github.com/pytorch/pytorch/pull/34413
