### ISSUE TITLE
CUDA 9 + CUDNN 7 - seg fault

### ISSUE THREAD

**Issue by esube** [pytorch/pytorch#3081]
I have update my cuda to 9 and cudnn to 7003 and and checked out the latest pytorch and compiled with the new setup. When an exception happens, it produces a segmentation fault. 

Previously (cuda 8 and cudnn 5.1), it used to handle exceptions with error message and crash gracefully. The segmentation fault core dump leaves the processes hanging around and that is unpleasant. Smaller network or smaller minibatch size works fine with same code.

**Comment by apaszke** [comment]
Can you please run your script under gdb (`gdb --args <the command you usually use`, then type `r`)? Once the segfault happens type in `bt` and paste the output here.

**Comment by esube** [comment]
```
Thread 49 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe973b0700 (LWP 23151)]
torch::autograd::InputBuffer::add (this=this@entry=0x7ffe973afb10, pos=pos@entry=0, var=...)
    at torch/csrc/autograd/input_buffer.cpp:17
17        if (!item.first.defined()) {
(gdb) bt
#0  torch::autograd::InputBuffer::add (this=this@entry=0x7ffe973afb10, pos=pos@entry=0, var=...)
    at torch/csrc/autograd/input_buffer.cpp:17
#1  0x00007fffb1951fad in torch::autograd::Engine::evaluate_function (
    this=this@entry=0x7fffb2b95d00 <engine>, task=...) at torch/csrc/autograd/engine.cpp:268
#2  0x00007fffb195354e in torch::autograd::Engine::thread_main (this=0x7fffb2b95d00 <engine>, 
    graph_task=0x0) at torch/csrc/autograd/engine.cpp:144
#3  0x00007fffb1950382 in torch::autograd::Engine::thread_init (
    this=this@entry=0x7fffb2b95d00 <engine>, device=device@entry=1)
    at torch/csrc/autograd/engine.cpp:121
#4  0x00007fffb19728ea in torch::autograd::python::PythonEngine::thread_init (
    this=0x7fffb2b95d00 <engine>, device=1) at torch/csrc/autograd/python_engine.cpp:28
#5  0x00007ffff3967c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7bc16ba in start_thread (arg=0x7ffe973b0700) at pthread_create.c:333
#7  0x00007ffff78f73dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by apaszke** [comment]
Hmm that's still not enough information to solve the issue. Can you please prepare a script that would let us reproduce the problem?

**Comment by esube** [comment]
The code base is large to share. But, I just noticed that a medium network (ResNet34 base network with various modifications) produced the same segmentation fault although the GPUs (2 Titan X) didn't run out of memory. The strange thing is: switching to ResNet50 (used as feature extractor) instead of ResNet34 dies earlier. However, ResNet18 trains and finishes without a hitch. All the three networks use same code base, same dataset, same DataParallel (2 GPUs). It appears that some exceptions are not being handled. 

The machine has an Intel Xeon CPU and Titan X GPUs. It could be related to #3089 so I am changing the out of memory error title on this one. For me, pytorch + cuda 8 + cudnn v5.1 was working without this segfault ever. I switch to cuda 9 + cudnn v7 this week and checked pytorch and rebuild it and this started happening.

**Comment by JhonsonWanger** [comment]
Same error: [https://github.com/mingyuliutw/UNIT/issues/13](url)

**Comment by apaszke** [comment]
I understand that your codebase is large, but can you please try to write up a small sample that we could use to reproduce the problem? Just a tiny standalone snippet (e.g. create a model, wrap in data parallel, get random data, run and crash). It's really hard for us to debug issues via comments.

**Comment by JhonsonWanger** [comment]
@apaszke Thanks a lot. I have fixed this issue. This issue may be caused by dependency bug. I reinstalled python and all the dependencies using conda and set the version of cudnn to 6 (previously 5.1).  There are no issues left.

**Comment by apaszke** [comment]
@JhonsonWanger yeah, 5 is no longer supported

**Comment by mmderakhshani** [comment]
Hi there,
I have got the same error when forwarding a batch of input to my module. Here is the output of my gdb:

> Thread 73 "python" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7ffdd21c4700 (LWP 15179)]
> 0x00007fffa22ee8d5 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
> (gdb) bt
> #0  0x00007fffa22ee8d5 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
> #1  0x00007fffa243e914 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
> #2  0x00007fffa23dae80 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
> #3  0x00007ffff7bc16ba in start_thread (arg=0x7ffdd21c4700) at pthread_create.c:333
> #4  0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
> 

Is this error related to my cuda and cudnn?
