### ISSUE TITLE
kthvalue/median with scalar and dim=1 inconsistent between CPU and CUDA

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#30818]
```
>>> import torch
>>> torch.kthvalue(torch.tensor(2, device='cuda'), 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: dimension specified as 0 but tensor has no dimensions
>>> torch.kthvalue(torch.tensor(2, device='cpu'), 1)
torch.return_types.kthvalue(
values=tensor(2),
indices=tensor(0))
```

**Comment by ezyang** [comment]
This case is explicitly tested for on CPU, so I'm guessing the CPU version is right and the CUDA version is wrong.

**Comment by albanD** [comment]
cc @gchanan who is currently fixing these.

**Comment by ezyang** [comment]
median is also affected by this.

**Comment by gchanan** [comment]
This is out of scope of what I'm currently fixing.  I'm currently fixing the part of scalar handling across the TH->ATen boundary that is: "you returned to me a size `(1,)` tensor, but did you really mean to return me a size `()` Tensor?"

Scalar handing within ops is a bit of a different issue and I believe @ezyang's analysis of this specific case is correct.
