### ISSUE TITLE
DISABLED test_max_pool2d (__main__.TestQuantizedOps)

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#30848]
## 🐛 Bug

19:19:52 ERROR: test_max_pool2d (__main__.TestQuantizedOps)
19:19:52 ----------------------------------------------------------------------
19:19:52 Traceback (most recent call last):
19:19:52   File "test_quantized.py", line 403, in test_max_pool2d
19:19:52     min_side=1, max_side=10),
19:19:52   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 991, in wrapped_test
19:19:52     raise the_error_hypothesis_found
19:19:52   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 950, in wrapped_test
19:19:52     state.run()
19:19:52   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 686, in run
19:19:52     info.__expected_traceback,
19:19:52   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 582, in execute
19:19:52     % (test.__name__, text_repr[0])
19:19:52   File "/usr/local/lib/python3.6/dist-packages/hypothesis/core.py", line 741, in __flaky
19:19:52     raise Flaky(message)
19:19:52 hypothesis.errors.Flaky: Hypothesis test_max_pool2d(self=<__main__.TestQuantizedOps testMethod=test_max_pool2d>, X=(array([[[[-75., -75., -75., ..., -75., -75., -75.],

From: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/10054//console

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jamesr66a** [comment]
Hypothesis deadline testing is now disabled altogether so we can reenable this test (if needed, on a plane and haven’t checked)

**Comment by jamesr66a** [comment]
@eellison is this still an issue?
