### ISSUE TITLE
Are there any plans to release a prebuilt-binary for Windows?

### ISSUE THREAD

**Issue by AlanCPSC** [pytorch/pytorch#30843]
Hello everyone,

I was wondering if you guys have any plans to release official prebuilt-binaries for Windows 7/8/10 (+ Mac OS if possible)? I've been working on helping fellow students at school install pytorch onto their laptops - mainly through python's anaconda online package registry (https://anaconda.org/search?q=pytorch).

Unfortunately this has been an incredibly challenging task, as finding a compatible distribution for everyone has not been easy.

I believe that releasing official prebuilt-binaries will help beginners/students pick up this library quicker.

cc @ezyang

**Comment by xsacha** [comment]
The prebuilt binaries are available here: https://pytorch.org/get-started/locally/

**Comment by peterjc123** [comment]
What do you mean by prebuilt-binary? The easiest way to use PyTorch is to install Anaconda3, open Anaconda Command Prompt and then type in the install commands in https://pytorch.org, such as `conda install -c cudatoolkit=10.1 pytorch torchvision`.

**Comment by AlanCPSC** [comment]
Thank you for your response. I appreciate your contribution and development of this library for the rest of us. I will try the methods that you have provided during the next tutorial section that I am supervising.

I will respond later on if we run into any unexpected road blocks during setup and installation, otherwise I will mark this issue as closed.

**Comment by albanD** [comment]
Closing as we do provide conda binaries.
Do re-open if you find missing binaries.
