### ISSUE TITLE
[feature request] torch.cdist to compute pdist by default

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#30844]
A suggestion: have x2=None default argument value. If it's not specified, set x2:=x1. Then some computation can be saved (depending on how cdist is implemented), and it would still return a symmetric square form (as opposed to pdist which returns a condensed form).

**Comment by gchanan** [comment]
Hmm...https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html doesn't do this.  I guess my main question is if this is what you want, why don't you just pass x2 yourself?

**Comment by vadimkantorov** [comment]
I thought this would simplify inner detection that the same tensor was passed (if optimizations can be applied), but of course - currently I pass it twice.

**Comment by vadimkantorov** [comment]
Another way would be enabling `squareform=True` argument for pdist: https://github.com/pytorch/pytorch/issues/9406#issuecomment-427149837, but unfortunately this has not been okayed

**Comment by gchanan** [comment]
honestly, `squareform` sounds strictly better than this (although I'm not necessarily saying we should do `squareform`).  But this is inconsistent with NumPy and we can easily do a detection if the tensors are the same (if it's really important to optimize that case).

**Comment by vadimkantorov** [comment]
While pdist does not support batches, the easiest might be to allow `cdist` to accept one arg and then zero-out diagonal as postproc
