### ISSUE TITLE
backward hooks on parameters don't work with distributed autograd.

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#30850]
Distributed autograd doesn't use the `AccumulateGrad` function and as a result none of the backward hooks (e.g: `register_backward_hook`) for the parameters are executed for the gradients. We should look into enabling this. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @jjlilley

**Comment by pietern** [comment]
FWIW, this is also needed to enable DDP.

If done, we can easily mix and match RPC with DDP for combined model and data parallelism.

**Comment by pietern** [comment]
cc @zhaojuanmao @mrshenli

**Comment by pritamdamania87** [comment]
This should be resolved by https://github.com/pytorch/pytorch/pull/34501 and https://github.com/pytorch/pytorch/pull/33214
