### ISSUE TITLE
How to specify install path when build libtorch？no use cmake-gui

### ISSUE THREAD

**Issue by LinGeLin** [pytorch/pytorch#30869]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
`cmake -DCMAKE_INSTALL_PREFIX="YOUR PATH" ..`
