### ISSUE TITLE
doc improve

### ISSUE THREAD

**Issue by XuVision** [pytorch/pytorch#30868]
## 📚 Documentation

in Tutorials > TorchVision Object Detection Finetuning Tutorial
official:
`class PennFudanDataset(object):`
wrong! sholud be:
`class PennFudanDataset(torch.utils.data.Dataset):`

**Comment by peterjc123** [comment]
Would you please make a PR on this?

**Comment by gchanan** [comment]
@XuVision thanks!  I reported your issue in the tutorials repo: https://github.com/pytorch/tutorials/issues/759.
