### ISSUE TITLE
implement unique function for `Half` 

### ISSUE THREAD

**Issue by Dicksonchin93** [pytorch/pytorch#30883]
## 🚀 Feature

computing Spearman Rank Correlation Metric needs to utilize rank data values, using torch.unique() accomplishes this but it is not supported for fp16

## Motivation
running torch.unique() on half precision values returns this error

```
import torch
x = torch.empty([5, 20], dtype=torch.half)
torch.unique(x, sorted=True, return_inverse=True)

RuntimeError: "unique" not implemented for 'Half'
```

## Pitch
enable torch.unique for half precision values

**Comment by zasdfgbnm** [comment]
fixed in https://github.com/pytorch/pytorch/pull/31211
