### ISSUE TITLE
No Variable.transpose_() problem

### ISSUE THREAD

**Issue by CuriousCat-7** [pytorch/pytorch#3088]
r = torch.rand(2,3,4)
r.transpose_(1,2)

is ok

but,
r = Variable(torch.rand(2,3,4))
r.transpose_(1,2)
will:
'Variable' object has no attribute 'transpose_'

I believe this should be fixed

Thank you,
Neo

**Comment by albanD** [comment]
Hi,

The `.transpose(1,2)` operation does not allocate new memory.
You can use it instead of `.transpose_(1,2)`.

**Comment by apaszke** [comment]
As pointed out by @albanD `transpose(1, 2)` is free, so please use this. The issue will be resolved once Variables and Tensors are merged, which is underway.
