### ISSUE TITLE
Segfault when using data parallel on PPC64

### ISSUE THREAD

**Issue by M-Eng** [pytorch/pytorch#3089]
When training a resnet152 wrap into a data_parallel it creates a segfault. 
It works on a single GPU with the same parameters, but when switching to two or more it produces a segfault after a few iterations.

Here is the gdb trace:

> Thread 10 "python" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x120000d1f1a0 (LWP 101627)]
> torch::autograd::InputBuffer::add (this=0x120000d1e2a0, pos=0, var=...) at torch/csrc/autograd/input_buffer.cpp:17
> 17        if (!item.first.defined()) {
> (gdb) bt
> #0  torch::autograd::InputBuffer::add (this=0x120000d1e2a0, pos=0, var=...) at torch/csrc/autograd/input_buffer.cpp:17
> #1  0x00001000a6e6774c in torch::autograd::Engine::evaluate_function (this=<optimized out>, task=...)
>     at torch/csrc/autograd/engine.cpp:268
> #2  0x00001000a6e6920c in torch::autograd::Engine::thread_main (this=0x1000a80e1700 <engine>, graph_task=0x0)
>     at torch/csrc/autograd/engine.cpp:144
> #3  0x00001000a6e6522c in torch::autograd::Engine::thread_init (this=0x1000a80e1700 <engine>, device=<optimized out>)
>     at torch/csrc/autograd/engine.cpp:121
> #4  0x00001000a6e96590 in torch::autograd::python::PythonEngine::thread_init (this=0x1000a80e1700 <engine>,
>     device=<optimized out>) at torch/csrc/autograd/python_engine.cpp:28
> #5  0x00001000a6e6c014 in std::_Mem_fn_base<void (torch::autograd::Engine::*)(int), true>::operator()<int, void>(torch::autograd::Engine*, int&&) const (__object=<optimized out>, this=<error reading variable: value has been optimized out>)
>     at /usr/include/c++/5/functional:600
> #6  std::_Bind_simple<std::_Mem_fn<void (torch::autograd::Engine::*)(int)> (torch::autograd::Engine*, int)>::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=<error reading variable: value has been optimized out>)
> ---Type <return> to continue, or q <return> to quit---
>    5/functional:1531
> #7  std::_Bind_simple<std::_Mem_fn<void (torch::autograd::Engine::*)(int)> (torch::autograd::Engine*, int)>::operator()() (this=<error reading variable: value has been optimized out>) at /usr/include/c++/5/functional:1520
> #8  std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (torch::autograd::Engine::*)(int)> (torch::autograd::Engine*, int)> >::_M_run() (this=<optimized out>) at /usr/include/c++/5/thread:115
> #9  0x00001000a30f49a4 in ?? () from /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
> #10 0x0000100000338070 in start_thread (arg=0x120000d1f1a0) at pthread_create.c:335
> #11 0x00001000005e3a30 in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc64/clone.S:96

I'm working a ppc64 machine, cuda-8.0, where I installed pytorch from source, no error at compilation. Tests fails but might come from #1297. The installation seems to work fine on a single GPU.

**Comment by esube** [comment]
This issue seems similar to mine (#3081). Were you monitoring the memory usage using nvidia-smi before the segfault?

**Comment by M-Eng** [comment]
Yes and it doesn't appear to be an out of memory. it works well on a single GPU using only half the ram.

**Comment by mruberry** [comment]
Closing due to age. @M-Eng if you still experience this issue, would you please open a new issue?
