### ISSUE TITLE
I can't build pytorch 1.3.1 from sources. 

### ISSUE THREAD

**Issue by thorpy1992** [pytorch/pytorch#30910]
I followed the steps from README for building pytorch v1.3.1 from sources but I have this error: 
Cmake Error: Error: generator : Ninja
Does not match the generator used previously: Visual Studio 15 2017 Win64
Either remove the CMakeCache.txt file and CmakeFiles directory or choose a different binary directory.

My configuration is:

set CMAKE_GENERATOR=Visual Studio 15 2017 Win64

set CMAKE_GENERATOR_TOOLSET_VERSION=14.11

for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%

set USE_CUDA=0

set BUILD_SHARED_LIBS=OFF

When I run "python setup.py build", I get the error from above. 

P.S: I use Windows10. There is nothing in the build folder.

Thanks in advance!

cc @peterjc123

**Comment by peterjc123** [comment]
Please try `python setup.py build --cmake` instead.

**Comment by thorpy1992** [comment]
Thank you, @peterjc123! Unfortunately, I get the same error.

**Comment by peterjc123** [comment]
What about just cloning the repo again?

**Comment by peterjc123** [comment]
Also, could you please post the full log while you type in those commands?

**Comment by thorpy1992** [comment]
It's the same error when cloning the repo again. 

The full error file is:

CMake Error: Error: generator : Ninja
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "setup.py", line 756, in <module>
    build_deps()
  File "setup.py", line 324, in build_deps
    cmake=cmake)
  File "C:\Work\TORCH130\pytorch\tools\build_pytorch_libs.py", line 56, in build_caffe2
    rerun_cmake)
  File "C:\Work\TORCH130\pytorch\tools\setup_helpers\cmake.py", line 318, in generate
    self.run(args, env=my_env)
  File "C:\Work\TORCH130\pytorch\tools\setup_helpers\cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\czurini\AppData\Local\Continuum\anaconda2\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_SHARED_LIBS=OFF', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 15 2017', '-DCMAKE_GENERATOR_TOOLSET_VERSION=14.11', '-DCMAKE_INSTALL_PREFIX=C:\\Work\\TORCH130\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\Users\\czurini\\AppData\\Local\\Continuum\\anaconda2\\Lib\\site-packages', '-DNUMPY_INCLUDE_DIR=C:\\Users\\czurini\\AppData\\Local\\Continuum\\anaconda2\\lib\\site-packages\\numpy\\core\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\czurini\\AppData\\Local\\Continuum\\anaconda2\\python.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\czurini\\AppData\\Local\\Continuum\\anaconda2\\include', '-DPYTHON_LIBRARY=C:\\Users\\czurini\\AppData\\Local\\Continuum\\anaconda2/libs/python27.lib', '-DTORCH_BUILD_VERSION=1.3.0a0+ee77ccb', '-DUSE_CUDA=False', '-DUSE_NUMPY=True', 'C:\\Work\\TORCH130\\pytorch']' returned non-zero exit status 1

**Comment by thorpy1992** [comment]
It worked with USE_NINJA=OFF. Thank you guys for your support.

**Comment by peterjc123** [comment]
I know why it happens. It is simply because `CMAKE_GENERATOR` and the generators specified in the command conflicts. Let me put up a fix.

**Comment by thorpy1992** [comment]
In my case, is the same error even after your fix. And with VS 2017, I cannot finish the build on static mode because of "fatal error LNK1248: image size (10007FE9E) exceeds maximum allowable size (FFFFFFFF)", even though I tried with "/Zi". Does it work for you on WINDOWS after your fix?

**Comment by peterjc123** [comment]
> In my case, is the same error even after your fix.

You'll need to clean the build cache first.

> "fatal error LNK1248: image size (10007FE9E) exceeds maximum allowable size (FFFFFFFF)", even though I tried with "/Zi"

You'll need to set `-DMSVC_Z7_OVERRIDE=OFF` in the cmake command.

**Comment by lorenzznerol** [comment]
This "set NINJA=OFF" is one thing that helped, probably the essential part. Yet I am not 100 % sure since after this, it still did not succeed, but went much further and showed:  

```
CMake Error at cmake/public/cuda.cmake:432 (message):
  CUDA 10.0 is not compatible with MSVC toolchain version >= 19.20.  (a.k.a
  Visual Studio 2019, VS 16.0) Please upgrade to CUDA >= 10.1 or set the
  following environment variable to use another version (for example):

    set "CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"
```
The next step was

`set "CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"
`
and then it ran through. In the readme.md they clearly say that it is just optional, I did not expect it to be needed:

> :: [Optional] If you want to override the cuda host compiler
> set CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe

Context:
My install: an underpowered but stil useful Asus GeForce GT 710 CUDA CC 3.5
Compiler, using cmake: MS Visual Studio 2019 16.7.1
-->  Indivudual components: 
- most recent MSVC v142 - VS 2019 C++-x64/x86-Buildtools (v14.27) (the most recent x64 version at that time)
- most recent Windows 10 SDK (10.0.19041.0) (the most recent x64 version at that time)
