### ISSUE TITLE
[jit] runtime error with backward of matmul and squeeze 

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#30936]
## 🐛 Bug

The following code throws the error `RuntimeError: Function torch::jit::(anonymous namespace)::DifferentiableGraphBackward returned an invalid gradient at index 0 - got [] but expected shape compatible with [2]
`

## To Reproduce

```python
import torch

def f(x):
    return torch.ones(3, 2).matmul(x.unsqueeze(-1)).squeeze(-1).sum()

jf = torch.jit.trace(f, torch.ones(2,))
x = torch.ones(2, requires_grad=True)
jf(x).backward()
```

## Expected behavior

No error happens

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6

## Additional context

Instead of `matmul`, using `mm` gives error
```
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
The above operation failed in interpreter, with the following stack trace:
at <string>:200:19
        #         grad_self = AD_index_select_backward(grad_output, dim, result1, self_size, keepdim)
        #         return grad_self, None, None, None

        #     return result0, result1, backward

        def AD_mm_backward_self(grad, mat2):
            return grad.mm(mat2.t())

        def AD_mm_backward_mat2(grad, self):
            return self.t().mm(grad)
                   ~~~~~~~~~~~ <--- HERE

        def mm(self, mat2):
            def backward(grad_output):
                grad_self = AD_mm_backward_self(grad_output, mat2)
                grad_mat2 = AD_mm_backward_mat2(grad_output, self)
                return grad_self, grad_mat2

            return torch.mm(self, mat2), backward
```

cc @suo @neerajprad

**Comment by suo** [comment]
Hm, this does not reproduce for me on master. Can you install the latest nightly and see if it reproduces in your environment?

**Comment by fehiepsi** [comment]
Thanks, @suo! I can confirm that the issue is fixed in the nightly version.
