### ISSUE TITLE
The DepthWise Convolution with 3*3 kernels is operating faster than that with 1*3 or that with 3*1.

### ISSUE THREAD

**Issue by PoonKinWang** [pytorch/pytorch#30933]
I found that the DepthWise Convolution with 3×3 kernels is operating faster than that with 1×3 or that with 3×1. Theoretically, the 1×3 convolution has the same number of unfolded tensors as 3×3, and it has a smaller area needed to be considerated, therefore its resource consumption should be less, or equal at lease. Can you give me some advices to address the problem? I want to know the reason. Thanks in advance.

**Comment by ngimel** [comment]
Depthwise convolutions have special templated initializations for 3x3 kernels, 1x3 and 3x1 go to generic less efficient initialization https://github.com/pytorch/pytorch/blob/6848f9abb82edc4e03e34b2c45a6c559a45a6c7c/aten/src/THCUNN/generic/SpatialDepthwiseConvolution.cu#L72-L87. You can experiment if initializing templates for 1x3 actually makes them faster. Closing for now, as it does not seem there's an action here for devs to take.
