### ISSUE TITLE
TorchScript led to CPU OOM

### ISSUE THREAD

**Issue by xiaodao2049** [pytorch/pytorch#30949]
Hello, I want to use TorchScript to accelerate my training, but I found my cpu memory is going up and finally blow up, but if I don't use TorchScript, everything is fine. I have no idea if it's a bug, Can you give me some advice?

cc @suo

**Comment by xsacha** [comment]
Is this only with MKL-DNN enabled?

Related issues:
https://github.com/pytorch/pytorch/issues/27971
https://github.com/intel/mkl-dnn/issues/489
https://github.com/pytorch/pytorch/issues/25267

**Comment by xiaodao2049** [comment]
@xsacha  My training phase  was on  GPU and I set cudnn.enabled=True

**Comment by suo** [comment]
Hi @xiaodao2049, is this a duplicate of https://github.com/pytorch/pytorch/issues/30949? If so, can you close this issue? Thanks!
