### ISSUE TITLE
ONNX exporter: graph name does not respect ONNX specification

### ISSUE THREAD

**Issue by Guriido** [pytorch/pytorch#30952]
## 🐛 Bug

When exporting a model to ONNX format, the default name of the graph is set to `torch-jit-export` which doesn't respect the ONNX specification (all names must adhere to C identifier syntax rules)
https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph

## To Reproduce

1. use `torch.onnx.export(…)` on any model
2. print(onnx.load('my_exported_model.onnx').graph.name)  # <-- checks the name of the graph 

## Expected behavior

The default name should be change to something like `torch_jit_export`, and the user should be able to set it to through a parameter of `torch.onnx.export(…)`. 
(currently, the user has to open the exported file, edit the graph name with `onnx` and save again, which can be bothersome)

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch: pip3
 - Python version: 3.6.8

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
I'm looking into this. But I assume this is not a blocking issue @Guriido, could you please confirm?

**Comment by Guriido** [comment]
Thank you for your answer.
As the graph name can be modified through the `onnx` package, this is indeed not a blocking issue.

**Comment by neginraoof** [comment]
How about using the existing default name "torch-jit-export"? 
I understand that this does not comply with the spec. Do you see ant issues when exporting or running the model?

**Comment by Guriido** [comment]
> All names MUST adhere to C identifier syntax rules.

ONNX explicitly defines this as an absolute requirement of the specification, and third party tools based on ONNX may use the name as an identifier. So even if the export itself does not result in an error, the non-compliance with the specification would raise issues when used with onnx-based software down-the-road.

An use-case is using the exported graph as a function in a C code, where the name `torch-jit-export` results in a syntax error.
Also, the graph name is expected to be user defined, for example in this case the user should be able to use graphs of several models at the same time, without overlap in the namespace.
