### ISSUE TITLE
Assigning int values to autograd tensors by Tensor.data

### ISSUE THREAD

**Issue by huohuayuzhong** [pytorch/pytorch#30961]
## 🐛 Bug

When trying to create a Tensor with int values but requires_grad=True, it comes up with a RunTime Error. But when trying to assign the data of a tensor that requires_grad, no Error reported.

## To Reproduce

> foo = torch.tensor(1)
> bar = torch.tensor(2, requires_grad = True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Only Tensors of floating point dtype can require gradients
> bar = torch.tensor(2.0, requires_grad = True)
> bar

tensor(2., requires_grad=True)
> bar.data = foo.data
> bar

tensor(1, requires_grad=True)

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 396.54
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.1
[pip3] numpydoc==0.8.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.0.1.post2
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchtext==0.3.1
[pip3] torchvision==0.2.2.post3
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.1.0            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.0.13           py37h516909a_1    conda-forge
[conda] mkl_random                1.0.4            py37hf2d7682_0    conda-forge
[conda] pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torchvision               0.3.0                    pypi_0    pypi

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
`.data` should not be used. It is not even in the documentation.

You can do many many wrong things if you use `.data`.
I'm going to close this in favor of https://github.com/pytorch/pytorch/issues/30987 that explicitly aims at actually removing `.data`. Feel free to discuss there if you think we should change the outlined plan.
