### ISSUE TITLE
AttributeError: 'Embedding' object has no attribute 'named_paramters'

### ISSUE THREAD

**Issue by SunChao3555** [pytorch/pytorch#30963]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
- [env]
> Windows 10 System
> Python 3.6
> torch (1.3.1)
> torchtext (0.4.0)
> torchvision (0.4.2)

- [main code snippet]
```
net=nn.Embedding(200,300)

for n,p in net.named_parameters():
    print(n,p)#   get result
class Encoder(nn.Module):
    def __init__(self, vocab_size, embed_size, num_hiddens, num_layers, drop_prob=0.):
        super(Encoder, self).__init__()
        self.embedd = nn.Embedding(vocab_size, embed_size)
        self.rnn = nn.GRU(embed_size, num_hiddens, num_layers, dropout=drop_prob)

    def forward(self, inputs, state):
        embedding = self.embedd(inputs.long()).permute(1, 0, 2)
        return self.rnn(embedding)
encoder = Encoder(20, 64, 64, 2,0.5)
print(encoder)
def init_weights(m):
    print(m)
    for name,param in m.named_paramters():
        init.uniform_(param.data,-0.08,0.08)

encoder.apply(init_weights)
```

- [problem]

> Traceback (most recent call last):
>   File "C:/Users/SunChao/Desktop/PytorchInAction/test.py", line 110, in <module>
>     encoder.apply(init_weights)
>   File "C:\Users\SunChao\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 287, in apply
>     module.apply(fn)
>   File "C:\Users\SunChao\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 288, in apply
>     fn(self)
>   File "C:/Users/SunChao/Desktop/PytorchInAction/test.py", line 105, in init_weights
>     for name,param in m.named_paramters():
>   File "C:\Users\SunChao\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 585, in __getattr__
>     type(self).__name__, name))
> AttributeError: 'Embedding' object has no attribute 'named_paramters'
> 

When I run code:
```
net=nn.Embedding(200,300)

for n,p in net.named_parameters():
    print(n,p)#   get result
```

 it works well;
but when I run :
` encoder.apply(init_weights)`

it raise above exception
Thanks !!!

**Comment by yenicelik** [comment]
Looks like you have a typo? `named_paramters`

**Comment by jbschlosser** [comment]
Closing this; if more help is needed, please visit the [forums](https://discuss.pytorch.org/).
