### ISSUE TITLE
No "out" keyword paramter for masked_select

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3097]
```
>> torch.masked_select(x, amask, out=ax)
*** TypeError: masked_select() got an unexpected keyword argument 'out'
```

The documentation says this keyword should exist in PyTorch 0.2

**Comment by zou3519** [comment]
I'm running pytorch 0.2.0_4 and it appears to work. Could you let me know what exactly 
 the output of your `torch.__version__` is?

**Comment by ebetica** [comment]
Hmm, I updated to master and it seems to be there now.
