### ISSUE TITLE
test_rref_context_debug_info is flaky

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#30988]
Circleci jobs:
https://app.circleci.com/jobs/github/pytorch/pytorch/3811402
https://app.circleci.com/jobs/github/pytorch/pytorch/3832986
https://app.circleci.com/jobs/github/pytorch/pytorch/3834981
https://app.circleci.com/jobs/github/pytorch/pytorch/3844225
https://app.circleci.com/jobs/github/pytorch/pytorch/3858223

cc @ezyang @gchanan @zou3519

**Comment by suo** [comment]
Test is still flaky even after the fix: https://app.circleci.com/jobs/github/pytorch/pytorch/3897091. 

@mrshenli can you take another look?

**Comment by osalpekar** [comment]
This should be fixed by PR  #32749!
