### ISSUE TITLE
Does Distributed Data Parallel Support model parallel where output of the model are in different devices?

### ISSUE THREAD

**Issue by dzk9528** [pytorch/pytorch#30989]
By following the tutorial, I combine the model parallel and DDP together but the last layer(the parameter is really large) is doing some model parallel work like this code [source](https://github.com/bindog/pytorch-model-parallel/blob/8d1c0b91d4eb75c861059f4940159b06574189df/model.py#L39). However, it stuck at here

```python
model.features = model.features.to(args.gpu_list[0])
model = torch.nn.parallel.DistributedDataParallel(model)
```

the gpu list for first DDP is [0, 1, 2, 3]
the gpu list for second DDP is [4, 5, 6, 7]
I modify the source code to make sure the chunk follow the parameter of gpu list

```python
class FullyConnected(nn.Module):
    def __init__(self,
                 in_dim,
                 out_dim,
                 gpu_list=[],
                 model_parallel=False,
                 class_split=None):
        super(FullyConnected, self).__init__()
        self.gpu_list = gpu_list
        self.model_parallel = model_parallel
        if model_parallel:
            self.fc_chunks = nn.ModuleList()
            for i in range(len(self.gpu_list)):
                self.fc_chunks.append(
                    nn.Linear(in_dim, class_split[i], bias=True).cuda(self.gpu_list[i])
                )
        else:
            self.fc = nn.Linear(in_dim, out_dim, bias=True)

    def forward(self, x, labels=None):
        # print(x.size())
        if self.model_parallel:
            x_list = []
            for i in range(len(self.gpu_list)):
                _x = self.fc_chunks[i](x.cuda(self.gpu_list[i]))
                x_list.append(_x)
            return tuple(x_list)
        else:
            return self.fc(x)
```

If it does not support output on multiple device, how can I reorganize the last layer?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by zhangguanheng66** [comment]
Any ideas? @mrshenli

**Comment by zhaojuanmao** [comment]
IIUC, DDP requires input and output signatures of the models in different processes/GPUs/nodes are exactly the same, and models are called in the same order among different processes. if each process runs different divided models, input and output signatures are also different, then it should not work

**Comment by pietern** [comment]
@dzk9528 What is the problem here?

If this is a question, please post on https://discuss.pytorch.org/ -- we reserve the issue tracker for issues.
