### ISSUE TITLE
flaky docker pull on android build ci

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#31027]
On my PRs, I'm seeing a lot of errors that look like: 
```
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:405-0ec30231faf246d27ad54e902993efb64eec393e-android-arm-v7a not found
```
Examples:
- https://app.circleci.com/jobs/github/pytorch/pytorch/3873186
- https://app.circleci.com/jobs/github/pytorch/pytorch/3873214
- https://app.circleci.com/jobs/github/pytorch/pytorch/3873247

This happens pretty consistently for PRs but doesn't seem to affect master. @IvanKobzarev maybe?

cc @ezyang @gchanan @zou3519

**Comment by IvanKobzarev** [comment]
On PR's we run only x86 build. On master - all 4 abi's. So this looks like some problem with configuration that job on PR is trying to find .*-android-arm-v7a while it is not built on PR.
I am checking CI config.

**Comment by suo** [comment]
@IvanKobzarev Is there a fix on the way?

**Comment by IvanKobzarev** [comment]
@suo No. That variable is set by CircleCI internally, I am checking if we had some recent Circle updates etc.

**Comment by IvanKobzarev** [comment]
@suo @ezyang 
I prepared PR with hotfix workaround for non-leaf PRs that does not have `CIRCLE_PULL_REQUEST` environment variable, but have `CIRCLE_BRANCH`

https://github.com/pytorch/pytorch/pull/31088

After checking CircleCI jobs if works ok - (It's non-leaf PR with dummy PR on the top) - we can temporary push it.

**Comment by IvanKobzarev** [comment]
workaround https://github.com/pytorch/pytorch/commit/4ead2e8996c7dd8a0d3a07541449da48c2b9f3c6 is in master
I am monitoring failres on PRs

**Comment by IvanKobzarev** [comment]
Looks like workaround works - closing the issue.
