### ISSUE TITLE
torch.jit.script return type for torch.isinf(Tensor) is bool, but method actually returns tensor

### ISSUE THREAD

**Issue by fuzic** [pytorch/pytorch#31021]
## Issue description

torch jit thinks that torch.isinf returns a boolean, but in practice it returns a BoolTensor (operates elementwise).

```
Return value was annotated as having type Tensor but is actually of type bool:
at x.py:5:4
@torch.jit.script
def foo(x: torch.Tensor) -> torch.Tensor:
    return torch.isinf(x)
```

## Code example

```
import torch

@torch.jit.script
def foo(x: torch.Tensor) -> torch.Tensor:
    return torch.isinf(x)
```

## System Info
- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: mac
- PyTorch version: master
- Python version: 3.7
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

cc @suo

**Comment by suo** [comment]
Thanks for the report! This is indeed a bug; `isinf` uses a legacy binding method that does not work well with the JIT (see: https://github.com/pytorch/pytorch/issues/30786 for more info). The solution is to port this op to C++ (an example for `isfinite`: https://github.com/pytorch/pytorch/pull/30083). We are always happy to review a PR that does this 😛.

cc @yf225: is this method planned for C++ parity work?

**Comment by yf225** [comment]
@suo This method is planned for C++ parity work, but I am thinking maybe @eellison's work on https://github.com/pytorch/pytorch/issues/30788 would get to it sooner. @eellison do you plan to work on this?

**Comment by eellison** [comment]
> @suo This method is planned for C++ parity work, but I am thinking maybe @eellison's work on #30788 would get to it sooner. @eellison do you plan to work on this?

No. The work there was intended to be identification of pytorch ops we do not support and not remediation. I was trying to knock out a few ops that compiled and silently gave wrong semantics but that's separate from parity work https://github.com/pytorch/pytorch/pull/30493 https://github.com/pytorch/pytorch/pull/27629

**Comment by TH3CHARLie** [comment]
@suo Hi, can I take a try for the C++ parity work on `isinf` here?

**Comment by suo** [comment]
@TH3CHARLie of course! Please add @yf225 as a reviewer on the PR. Thanks!
