### ISSUE TITLE
torch.gels gives different results on cpu and on cuda

### ISSUE THREAD

**Issue by nkundiushuti** [pytorch/pytorch#3103]
b = torch.randn(600,1)
A = torch.randn(600,2)
X, _ = torch.gels(b,A)
X.size()  #torch.Size([2, 1])
Y, _ = torch.gels(b.cuda(),A.cuda())
Y.size()  #torch.Size([600, 1])

**Comment by zou3519** [comment]
@nkundiushuti that is interesting.

(The documentation)[http://pytorch.org/docs/master/torch.html#torch.gels] says that the first `n` rows returned (`n=2` here) include the solution of the least-squares problem. I've verified that the first 2 rows of X and Y are the same so you can probably use that for now while we figure out what the rest of the output is.
