### ISSUE TITLE
Tutorial Error for "Using the PyTorch C++ Frontend"

### ISSUE THREAD

**Issue by lzxzy** [pytorch/pytorch#31037]
## 📚 Documentation

Hi, when I try to follow the tutorial **Using the PyTorch C++ Frontend**. At the beginning of the article，the toy example CMakeLists.txt was written like this:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(dcgan)

find_package(Torch REQUIRED)

add_executable(dcgan dcgan.cpp)
target_link_libraries(dcgan "${TORCH_LIBRARIES}")
set_property(TARGET dcgan PROPERTY CXX_STANDARD 11)
```

But I get the **error** `error: #error You need C++14 to compile PyTorch`.
I guess in the latest libtorch version, you may use some C++ 14 features. So, I change the last line in CMakeLists.txt to `set_property(TARGET dcgan PROPERTY CXX_STANDARD 14)`. It worked. I think we should make some updates for this tutorial.

**Comment by peterjc123** [comment]
Would you please put up a PR in https://github.com/pytorch/examples/tree/master/cpp?

**Comment by lzxzy** [comment]
> Would you please put up a PR in https://github.com/pytorch/examples/tree/master/cpp , https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_frontend.rst and https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_export.rst?

Of course, It's my pleasure. I'll put up that as soon

**Comment by holly1238** [comment]
Closing this issue. All corresponding PRs have been merged.
