### ISSUE TITLE
How to load PyTorch model using C++ api

### ISSUE THREAD

**Issue by henbucuoshanghai** [pytorch/pytorch#31041]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by henbucuoshanghai** [comment]
where is the official document?

**Comment by peterjc123** [comment]
https://github.com/pytorch/examples/tree/master/cpp https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_frontend.rst https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_export.rst

Last but not least, let's say something more important.

### **Please note that this issue tracker is not a help form and this issue will be closed.**
### **Please note that this issue tracker is not a help form and this issue will be closed.**
### **Please note that this issue tracker is not a help form and this issue will be closed.**
