### ISSUE TITLE
ROCm support to pytorch

### ISSUE THREAD

**Issue by shixinglingguihua** [pytorch/pytorch#31049]
## ❓  while compile failed tipes is The following variables are used in this project, but they are set to NOTFOUND

compile env is  ubuntu18.04   ROCm 2.10  GPU is Vega56-8G

here is mine error log:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
**ROCM_ROCTX_LIB
    linked by target "torch_hip" in directory** /home/ling/build**/pytorch/caffe2**

-- Configuring incomplete, errors occurred!
See also "/home/ling/build/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/ling/build/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/ling/build/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/home/ling/build/pytorch/tools/setup_helpers/cmake.py", line 321, in generate
    self.run(args, env=my_env)
  File "/home/ling/build/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/ling/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/ling/build/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/ling/anaconda3/lib/python3.7/site-packages', '-DNUMPY_INCLUDE_DIR=/home/ling/anaconda3/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/ling/anaconda3/bin/python', '-DPYTHON_INCLUDE_DIR=/home/ling/anaconda3/include/python3.7m', '-DPYTHON_LIBRARY=/home/ling/anaconda3/lib/libpython3.7m.so.1.0', '-DTORCH_BUILD_VERSION=1.4.0a0+190dac1', '-DUSE_NUMPY=True', '-DUSE_ROCM=1', '/home/ling/build/pytorch']' returned non-zero exit status 1.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by izdeby** [comment]
@shixinglingguihua, can you, please, provide your environment info?

**Comment by shixinglingguihua** [comment]
> @shixinglingguihua, can you, please, provide your environment info? And repro steps of what exactly you are doing?

this is mine env :system is ubuntu 18.04 and GPU is amd vega56 ,adm dev info is latest version ROCm2.10.
here is mine build step:
 install amd dev  with https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html#ubuntu

**Comment by XeonHis** [comment]
I meet this problem too and have tried use ln to link, but it doesn't have work. My GPU is rx580.

**Comment by chengjiun** [comment]
I met the same problem, and it seems to work by installing rocmtracer-dev.

**Comment by shixinglingguihua** [comment]
> @shixinglingguihua, can you, please, provide your environment info? And repro steps of what exactly you are doing?

**Comment by shixinglingguihua** [comment]
> I meet this problem too and have tried use ln to link, but it doesn't have work. My GPU is rx580.

I had solved it, please see my blog [pytorch complie on ubuntu with rocm](https://www.jianshu.com/p/02b770c017f8)

**Comment by shixinglingguihua** [comment]
> I met the same problem, and it seems to work by installing rocmtracer-dev.

[pytorch complie on ubuntu with rocm](https://www.jianshu.com/p/02b770c017f8)
