### ISSUE TITLE
an error occured when complie the source code with cuda

### ISSUE THREAD

**Issue by lonl** [pytorch/pytorch#3105]
I'm trying to compile from the source  CUDA 7.5, CUDNN 5.0, and Anaconda Python 2.7 using python setup.py , there is en error as follows when compile the source code:

/home/hanpc/work/pytorch/torch/lib/gloo/gloo/common/linux.h:26:26: error: ‘__T0’ was not declared in this scope
 const auto kPCIClass3D = PCIClassMatch{0x030200, 0xffff00};
                          ^
/home/hanpc/work/pytorch/torch/lib/gloo/gloo/common/linux.h:29:31: error: ‘__T0’ was not declared in this scope
 const auto kPCIClassNetwork = PCIClassMatch{0x020000, 0xff0000};
                               ^
CMake Error at gloo_cuda_generated_cuda_private.cu.o.cmake:263 (message):
  Error generating file
  /home/hanpc/work/pytorch/torch/lib/build/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda_private.cu.o
make[2]: *** [gloo/CMakeFiles/gloo_cuda.dir/./gloo_cuda_generated_cuda_private.cu.o] error 1
make[2]: *** unfinished task....
/home/hanpc/work/pytorch/torch/lib/gloo/gloo/common/linux.h:26:26: error: ‘__T0’ was not declared in this scope
 const auto kPCIClass3D = PCIClassMatch{0x030200, 0xffff00};
                          ^
/home/hanpc/work/pytorch/torch/lib/gloo/gloo/common/linux.h:29:31: error: ‘__T0’ was not declared in this scope
 const auto kPCIClassNetwork = PCIClassMatch{0x020000, 0xff0000};
                               ^
CMake Error at gloo_cuda_generated_cuda.cu.o.cmake:263 (message):
  Error generating file
  /home/hanpc/work/pytorch/torch/lib/build/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o

make[2]: *** [gloo/CMakeFiles/gloo_cuda.dir/./gloo_cuda_generated_cuda.cu.o] error 1
make[1]: *** [gloo/CMakeFiles/gloo_cuda.dir/all] error 2

**Comment by ngimel** [comment]
Could be your gcc version is too new for cuda 7.5 https://devtalk.nvidia.com/default/topic/856954/bug-nvcc-and-gcc-4-9-3-get-into-conflict-over-unnamed-type-template-parameters/

**Comment by soumith** [comment]
@lonl i presume it was the gcc version, let me know if not (and reopen the issue if you need to)
