### ISSUE TITLE
RuntimeError: "roll_cuda" not implemented for 'Bool'

### ISSUE THREAD

**Issue by santient** [pytorch/pytorch#31079]
## Bug

```
In [51]: t = torch.zeros(10, dtype=torch.bool).cuda()                           

In [52]: t.roll(1)                                                              
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-93dfb28bb43d> in <module>
----> 1 t.roll(1)

RuntimeError: "roll_cuda" not implemented for 'Bool'
```

This works fine on CPU though. It seems that some functions are still missing for bool tensors.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 1060 6GB

cc @izdeby

**Comment by izdeby** [comment]
Fixed
