### ISSUE TITLE
torch.logsumexp only works on a single dimension, but doc says tuple of dims should work

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#31084]
Trying to use `torch.logsumexp` over multiple dimensions errors out.

```python3
>>> A = torch.ones(3, 3)
>>> torch.logsumexp(A, dim=(0, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: logsumexp(): argument 'dim' must be int, not tuple
```

However, in the latest stable documents (https://pytorch.org/docs/stable/torch.html#torch.logsumexp), it clearly states for the `dim` parameter:
```
dim (int or tuple of python:ints) – the dimension or dimensions to reduce.
```
Throughout the description, it also talks about `dim` as being allowed to be multi-dimensional.

According to #15597, this should be fixed, but it's not.

Furthermore, I believe that `torch.logsumexp` should treat dimension similarly to `torch.sum`. Just like `torch.sum`, it should absolutely allow for `dim` to be a tuple of ints. And if `dim` is not specified, it should operate over the whole tensor.

**Comment by teichert** [comment]
I think this is fixed as of version 1.5:

```python
>>> A = torch.ones(3, 3) 
>>> torch.logsumexp(A, dim=(0, 1))                                                                                   
Out[]: tensor(3.1972)
```
