### ISSUE TITLE
memory overflow in torchvision object detection finetuning tutorial

### ISSUE THREAD

**Issue by xuanjunlee** [pytorch/pytorch#31097]
why memory overflow?

120 training pictures, 50 test pictures. memory is 65G. 

When I was training the model, the following errors occurred:
python3.6: /pytorch/third_party/ideep/mkl-dnn/src/common/scratchpad.cpp:63: mkldnn::impl::global_scratchpad_t::global_scratchpad_t(size_t): Assertion `scratchpad_ != nullptr' fa                                           iled.

**Comment by izdeby** [comment]
Can you, please, provide a repro code? Please, reopen the issue once its provided.
