### ISSUE TITLE
ONNX py3.6 gcc5 doesn't work

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#31103]
This build flavor appears to not work: `caffe2_onnx_py3_6_gcc5_ubuntu16_04_test`. This problem was revealed after I upgraded this flavor from py2 to py3.6 in: https://github.com/pytorch/pytorch/pull/31082

This job was disabled by https://github.com/pytorch/pytorch/pull/31100.

Test failures look like: 
- https://app.circleci.com/jobs/github/pytorch/pytorch/3897517
- https://app.circleci.com/jobs/github/pytorch/pytorch/3897222

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by bddppq** [comment]
This CI apparently failed in #31082, why was it still merged in the first place?

**Comment by suo** [comment]
I only waited for the build to finish, I assumed there wouldn’t be a runtime difference between clang and gcc if they both built without failure. Clearly that was wrong lol 

Nevertheless, since we have dropped py2 support everywhere else and py3 + gcc5 apparently never worked, I don’t think it’s a regression to disable it for now while we fix it.

**Comment by suo** [comment]
Closed for now, as we have re-enabled the original build
