### ISSUE TITLE
syncbn bug

### ISSUE THREAD

**Issue by karlcao** [pytorch/pytorch#31109]
## To Reproduce

1.
1.
1.

<File "/home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/functions/syncbn.py", line 58, in forward
    _ex, _exs = lib.gpu.expectation_forward(x)
RuntimeError: cudaGetLastError() == cudaSuccess ASSERT FAILED at /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu:424, please report a bug to PyTorch. (Expectation_Forward_CUDA at /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu:424)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7ff103b5f021 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7ff103b5e8ea in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: Expectation_Forward_CUDA(at::Tensor) + 0x281 (0x7ff08852d822 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #3: <unknown function> + 0x8a413 (0x7ff088506413 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #4: <unknown function> + 0x83698 (0x7ff0884ff698 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #5: <unknown function> + 0x7bfb7 (0x7ff0884f7fb7 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #6: <unknown function> + 0x7c123 (0x7ff0884f8123 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
frame #7: <unknown function> + 0x6985c (0x7ff0884e585c in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/encoding/lib/gpu/enclib_gpu.so)
<omitting python frames>
frame #16: THPFunction_apply(_object*, _object*) + 0x581 (0x7ff104082ab1 in /home/lumeng/anaconda3/envs/ann/lib/python3.6/site-packages/torch/lib/libtorch_python.so)>

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):torch.__version__==1.0.1
 - ubuntu 18
 - How you installed PyTorch (`conda`, `pip`, source):pip 
 - Build command you used (if compiling from source):
 - Python version:3.6.8
 - CUDA/cuDNN version:9.2
 - GPU models and configuration:
 - Any other relevant information:torch-encoding

**Comment by izdeby** [comment]
@karlcao, can you, please, provice a repro and description of what is the problem?
Feel free to reopen the issue once this info is provided, thank you.
