### ISSUE TITLE
 CPU memory would not release at the beginning of the next iteration

### ISSUE THREAD

**Issue by WenmuZhou** [pytorch/pytorch#31101]
When I used dataset and dataloader to load the data, I found that the data from dataset would not release their CPU memory at the beginning of the next iteration, and the memory usage reached the highest point with the end of the first epoch. At the time, when my data set exceeded the machine memory, there would be an OOM error. How can I avoid it?
```python
# -*- coding: utf-8 -*-
# @Time    : 2019/8/23 21:54
# @Author  : zhoujun
import numpy as np
from torch.utils.data import DataLoader,Dataset


class DemoDataset(Dataset):
    def __init__(self):
        pass

    def  __getitem__(self,idx):
        img = np.zeros((1,3,640,640))
        return img
    
    def __len__(self):
        return 100


if __name__ == '__main__':
    import time
    train_data = DemoDataset()
    train_loader = DataLoader(dataset=train_data, batch_size=1, shuffle=True, num_workers=0)
    start_run = time.time()
    for e in range(10):
        for i, img in enumerate(train_loader):
            if i == 0:
                print('epoch: {} start time: {}'.format(e,time.time()-start_run))

```
memory jpg

![image](https://user-images.githubusercontent.com/12406017/70680177-4a17b900-1cd2-11ea-88a5-2a34a3360b8c.png)

run scipt, and the figure will show
```bash
pip3 install memory_profiler psutil
mprof run demo.py
mprof plot
```

cc @VitalyFedyunin @SsnL @ngimel @mruberry

**Comment by mruberry** [comment]
Thank you for providing such a clear reproduction. I also see the memory increase until it hits a limit, then it stops increasing.
