### ISSUE TITLE
TestAutogradDeviceTypeCUDA.test_logdet_1x1_cuda is flaky

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#31102]
https://app.circleci.com/jobs/github/pytorch/pytorch/3876399
https://app.circleci.com/jobs/github/pytorch/pytorch/3865899
https://app.circleci.com/jobs/github/pytorch/pytorch/3872182

cc @ezyang @gchanan @zou3519 @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry

**Comment by suo** [comment]
@gchanan do you know who the right owner for this is? Blame is not very enlightening

**Comment by ezyang** [comment]
Don't blame, use pickaxe. `git log -Slogdet_1x1` reveals this test was added by @SsnL; Simon, maybe you have some ideas?

**Comment by SsnL** [comment]
The links don't seem to work anymore. Have they just recently become flaky? I remember them being fine...

**Comment by suo** [comment]
Our tracking is not good enough to say when they started being flaky unfortunately, but yes it was relatively recent (last few weeks?)

**Comment by suo** [comment]
if the links are not working anymore, a sample error looks like:
```
Dec 10 04:00:25 ======================================================================
Dec 10 04:00:25 FAIL [0.106s]: test_logdet_1x1_cuda (__main__.TestAutogradDeviceTypeCUDA)
Dec 10 04:00:25 ----------------------------------------------------------------------
Dec 10 04:00:25 Traceback (most recent call last):
Dec 10 04:00:25   File "/var/lib/jenkins/workspace/test/common_utils.py", line 631, in wrapper
Dec 10 04:00:25     method(*args, **kwargs)
Dec 10 04:00:25   File "/var/lib/jenkins/workspace/test/common_utils.py", line 515, in __exit__
Dec 10 04:00:25     self.name, after - before, i))
Dec 10 04:00:25   File "/var/lib/jenkins/workspace/test/common_utils.py", line 839, in assertEqual
Dec 10 04:00:25     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
Dec 10 04:00:25 AssertionError: 1024 not less than or equal to 1e-05 : __main__.TestAutogradDeviceTypeCUDA.test_logdet_1x1_cuda leaked 1024 bytes CUDA memory on device 0
```

**Comment by rohan-varma** [comment]
This is still happening: https://app.circleci.com/jobs/github/pytorch/pytorch/4178635, with the same error as @suo 's sample.

**Comment by kostmo** [comment]
Here's a list of all occurrences since mid-December, including dozens from the past week: https://dr.pytorch.org/pattern-details.html?pattern_id=137

**Comment by mruberry** [comment]
This is probably addressed by https://github.com/pytorch/pytorch/pull/36605.

**Comment by kurtamohler** [comment]
Has this issue shown up at all after PR #36605 was merged. If not, perhaps this issue can be closed since it has been several months.

**Comment by mruberry** [comment]
I don't think it has, @kurtamohler. Let's close it.
