### ISSUE TITLE
macOS 10.15  on Ryzen get Intel MKL ERROR: CPU 0 is not supported.

### ISSUE THREAD

**Issue by liygzting** [pytorch/pytorch#31106]
## To Reproduce

```
>>> import torch
>>> import torch.nn as nn
>>> import torch.nn.functional as F
>>> class Net(nn.Module):
...     def __init__(self):
...         super(Net, self).__init__()
...         # 构造的网络框架主体
...         # kernel
...         self.conv1 = nn.Conv2d(1, 6, 3)
...         self.conv2 = nn.Conv2d(6, 16, 3)
...         # 线性连接
...         self.fc1 = nn.Linear(16*6*6, 120)
...         self.fc2 = nn.Linear(120, 84)
...         self.fc3 = nn.Linear(84, 10)
...     def forward(self,x):
...         # 池化层
...         x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
...         x = F.max_pool2d(F.relu(self.conv2(x)), 2)
...         x = x.view(-1, self.num_flat_features(x))
...         x = F.relu(self.fc1(x))
...         x = F.relu(self.fc2(x))
...         x = self.fc3(x)
...         return x
...     def num_flat_features(self, x):
...         size = x.size()[1:]
...         num_features = 1
...         for s in size:
...             num_features *= s
...         return num_features
... 
>>> net = Net()
>>> print(net)
Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
>>> params = list(net.parameters())
>>> print(len(params))
10
>>> print(params[0].size())
torch.Size([6, 1, 3, 3])
>>> input = torch.randn(1, 1, 32, 32)
>>> out = net(input)
Intel MKL ERROR: CPU 0 is not supported.
print(out)

>>> import numpy
>>> numpy.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @VitalyFedyunin

**Comment by great12366** [comment]
You even installed MacOS on AMD, but can't install MKL on the device?

**Comment by liygzting** [comment]
That's right
The mkl download from intel,but can't install
or is there some way that  pytorch use numpy with out mkl?

**Comment by liygzting** [comment]
And my enviroment is:
```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect
```

**Comment by vpirogov** [comment]
@liygzting,

Intel MKL throws the error you observe when an environment variable `MKL_DEBUG_CPU_TYPE` is set to 0. This means either you have this variable defined in your environment or something else in the stack is defining it.

**Comment by liygzting** [comment]
@vpirogov ,
yes when I set environment 
```
export MKL_DEBUG_CPU_TYPE=5
```
pytorch script run well
```
Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
10
torch.Size([6, 1, 3, 3])
tensor([[ 0.1278, -0.1342, -0.0672,  0.0173, -0.0244,  0.0364,  0.0166, -0.1153,
         -0.0851,  0.1414]], grad_fn=<AddmmBackward>)
```
 maybe [this website](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/?__cf_chl_captcha_tk__=cbdce49a1a838b6805e0b1136057a356e4931dcd-1576163232-0-ASif9pBI7ouX_Cp5fO9PhyclWagoASQZBAcAZxKoA_be_Mnmn_-54guZwm7YTrFR26_FuXE5uxgHDND2877n-28U6dRKIq0eeKYFClX6PtRWvWbytzOAi_hd40chEplVf7_2Dj6DglU9yBLpEk4Dxgx3ZMbgO0Mj47KMlwLDC6Nt11HZfrkX7TdpiiCJmZ1C7C8W7Y2l3PuMJub7TB6ZvBqd8sJnNUEMaSbEa2npK5wzmOO2wkIVr_DGt9hY-yPjQ04a9c_6FMuNvWRO76OiQJeuaqfvzqcdKoJ1jOtOOPVbuzRBtbgFtvEkkzBZwKOtZunzrXDlkgMpaPS8X1ZxIU7bxYr2ZGzZfk-4yS7hkjxgSFhen5iRteLasN8zQsoaN4w1uy1zt_R4Bc0Vbm4S6MRNUOskgdjn-mPvdrDrkM5tWTDBzanoLDfAYrI3b7yldOlpkp-auiXv8Ow-9dHn2WU) give me reason

**Comment by SheezyGuo** [comment]
@liygzting 
export MKL_DEBUG_CPU_TYPE=5
this seems to work well for me,mac os 15.1 on AMD,老哥牛皮

**Comment by AMDfans** [comment]
How to install MKL for MACOS 10.15.3 on Ryzen? My MATLAB cannot work because it lacks BLAS.

**Comment by T-Mofeng** [comment]
> @liygzting
> export MKL_DEBUG_CPU_TYPE=5
> this seems to work well for me,mac os 15.1 on AMD,老哥牛皮

How to set export MKL_DEBUG_CPU_TYPE=5?

**Comment by rgommers** [comment]
@T-Mofeng it's an environment variable, set it on the command line before starting Python.

**Comment by T-Mofeng** [comment]
> @T-Mofeng it's an environment variable, set it on the command line before starting Python.

I installed macos on Ryzen, but this command does not work.

**Comment by DemoorBug** [comment]
I was using matplotlib provided by anaconda, and it turned out to be the problem, I just uninstalled it.
I installed it via python3 -m pip install -U matplotlib and it didn't report any errors.

**Comment by hevinzhou** [comment]
MKL_DEBUG_CPU_TYPE=5 does't work for me.

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.2.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.18.1-g262b901
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.20.3           py39h4b4dc7a_0  
[conda] numpy-base                1.20.3           py39he0bd621_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
