### ISSUE TITLE
No grad backward after .squeeze() or .unsqueeze()?

### ISSUE THREAD

**Issue by igodogi** [pytorch/pytorch#31105]
## To Reproduce
import torch

a1 = torch.rand([4, 4], requires_grad=True).squeeze(0)
b1 = a1**2
b1.sum().backward()
print(a1.grad)

a2 = torch.rand([1, 4, 4], requires_grad=True).unsqueeze(0)
b2 = a2**2
b2.sum().backward()
print(a2.grad)

## Environment
torch.__version__
'1.3.0'

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
You need to save the variable prior to squeeze.

```
import torch

a1 = torch.rand([4, 4], requires_grad=True)
b1 = a1.squeeze(0)**2
b1.sum().backward()
print(a1.grad)

a2 = torch.rand([1, 4, 4], requires_grad=True)
b2 = a2.unsqueeze(0)**2
b2.sum().backward()
print(a2.grad)
```
