### ISSUE TITLE
test_process_group_debug_info is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#31112]
https://app.circleci.com/jobs/github/pytorch/pytorch/3898338

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by kostmo** [comment]
Two more instances:
* https://circleci.com/gh/pytorch/pytorch/3897091
* https://circleci.com/gh/pytorch/pytorch/3872182

**Comment by rohan-varma** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/31533
