### ISSUE TITLE
Improve handling of precision in testing

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#31135]
Some tests need to validate equality with low precision. The most common use-case is when testing operations on low-precision dtypes like torch.half or torch.bfloat16. There are a number of ways we handle this in testing code:

* We have a dtype2precision map we use in test_torch.py.
* We set a default precision as a member variable of TestCase in common_utils.py, which can be overriden by individual calls to `self.assertEqual(x, y, prec=newPrecision)`
* Sometimes we use `assertAlmostEqual`
* We use per-dtype precisionOverride annotations defined in common_device_type.py.
* Since tests for mixed-type operations don't work with the precisionOverride/dtypes annotation, test_type_promotion uses other workarounds in https://github.com/pytorch/pytorch/pull/30429 (not yet landed).

Since most of these cases target testing for torch.half, it seems like we should be able to come up with an approach that requires less special handling at call sites, and is used more consistently.

**Comment by gchanan** [comment]
CC @mruberry

**Comment by mruberry** [comment]
It would be nice to have more consistency.

**Comment by mruberry** [comment]
@nairbv's improvements to the default selection of atol/rtol, the precisionOverride decorator, the removal of the test_torch specific dtype2precision map, and the removal of assertAlmostEqual have greatly improved our consistency here. 

@ezyang, what are your thoughts?
