### ISSUE TITLE
CAFFE2_API macros missing for DecodeMultipleClipsFromVideo and FreeDecodedData function

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#31132]
## 🐛 Bug

While **DecodeMultipleClipsFromVideo** and **FreeDecodedData** was moved from **caffe2/video/video_io.h** to **caffe2/video/video_decoder.h** in d2ceab27661b6f16e0b0d9e958b0d880793ba564, CAFFE2_API macros was removed  from functions signature which were added in c2a75926cac36b770c9afcca894d07feb307592e.
Now building PyTorch with enabled USE_OPENCV=1 and USE_FFMPEG=1 flags fails with

```
[ 95%] Linking CXX executable ../../../../bin/torch_shm_manager
/home/user/PyTorch/build/lib/libtorch_cuda.so: undefined reference to `caffe2::DecodeMultipleClipsFromVideo(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, caffe2::Params const&, int, int, std::vector<int, std::allocator<int> > const&, bool, int&, int&, std::vector<unsigned char*, std::allocator<unsigned char*> >&)'
caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/build.make:102: recipe for target 'bin/torch_shm_manager' failed
collect2: error: ld returned 1 exit status
```

Adding back CAFFE2_API macros to function declarations (probably enough to add only to DecodeMultipleClipsFromVideo) solves the problem.

## To Reproduce

Build current master from source using command:
`USE_OPENCV=1 USE_FFMPEG=1 python3 setup.py install`

cc @ezyang @gchanan @zou3519 @fmassa

**Comment by ezyang** [comment]
@h6197627 Thanks for the report. Do you think you could open a PR for this?

**Comment by h6197627** [comment]
@ezyang, I opened PR resolving this issue
