### ISSUE TITLE
cannot find /usr/local/cuda-* and no nvcc inside pytorch docker container

### ISSUE THREAD

**Issue by marcoleewow** [pytorch/pytorch#31171]
## 🐛 Bug

We can see that pytorch can load cuda 10.1, but inside the docker container, we cannot see nvcc or /usr/local/cuda-10.1 folder.

## To Reproduce

`docker run --rm --gpus all pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime python -c "import torch; print(torch.version.cuda)"`

gives `10.1.243`

`docker run --rm --gpus all pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime ls /usr/local/cuda*`

gives `ls: cannot access '/usr/local/cuda*': No such file or directory`

`docker run --rm --gpus all pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime nvcc --version`

result in 

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"nvcc\": executable file not found in $PATH": unknown.
```
## Expected behavior

Expect `nvcc --version` shows Cuda 10.1 (below is 10.0 output) and expect to find `/usr/local/cuda-10.1` inside container
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

cc @ezyang

**Comment by colesbury** [comment]
@ezyang does someone review the "module: docker"?

@marcoleewow, I don't know what the expected behavior is... hopefully someone familiar with the docker image can comment. But if CUDA works but there's no `/usr/local/cuda*` directory than I'd guess it's installed somewhere else.

**Comment by ezyang** [comment]
No, docker image is something the community has helped us out a bit with. But in this case, it's not really our problem: our docker image is based off of `FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04` which manages the CUDA installation. If CUDA is in a weird place, complain to NVIDIA about it ;)

**Comment by marcoleewow** [comment]
no, you can check that `nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04` works as expected.

```
docker run --rm --gpus all nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04 ls /usr/local/cuda*

ls: cannot access '/usr/local/cuda-8.0': No such file or directory
/usr/local/cuda:
LICENSE
README
bin
compat
doc
extras
include
lib64
nvml
nvvm
share
src
targets
version.txt

/usr/local/cuda-10.1:
LICENSE
README
bin
compat
doc
extras
include
lib64
nvml
nvvm
share
src
targets
version.txt
```

But all the cuda files in pytorch official image are gone. I am sure this is something wrong in pytorch dockerfile.

**Comment by marcoleewow** [comment]
would be great if you can point me to how `pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime` was build @ezyang so I can do further investigation :)

**Comment by ezyang** [comment]
Curious. If you build the docker file in `docker/pytorch` from scratch, does it also have this problem?(I may simply just be mistaken about how this docker image was built!) cc @ngimel who appears to be the uploader of the most recent images.

**Comment by ngimel** [comment]
@marcoleewow you are using runtime images that don't contain cuda toolkit and nvcc. If you need cuda toolkit, you should use *devel pytorch image that, as @ezyang says, uses `nvidia/cuda:10.1-cudnn7-devel-ubuntu16.04` as a base.

**Comment by marcoleewow** [comment]
@ngimel yes you are right, I feel like an idiot after realising I have been using `runtime` images instead of `devel`. Thanks for the quick reply.

**Comment by luohao123** [comment]
@ngimel @marcoleewow  Sorry for ping here, does that means, using runtime am not able to use torch c++ plugin build?
