### ISSUE TITLE
Cannot init cuda under cuda10.1 & pytorch 1.3.1

### ISSUE THREAD

**Issue by GanjinZero** [pytorch/pytorch#31179]
## 🐛 Bug

Cannot init cuda under cuda10.1

And i get "THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp line=50 error=999 : unknown error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/veritas/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 193, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (999) : unknown error at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/THCGeneral.cpp:50
"
## To Reproduce

```python
a=torch.tensor(1.)
a.cuda()
```

## Environment

Please copy and paste the output from our
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 435.21
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] mkl                       2019.4                      243    https://repo.anaconda.com/pkgs/main
[conda] mkl-service               2.3.0            py37he904b0f_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.0.14           py37ha843d7b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.1.0            py37hd6b4f25_0    https://repo.anaconda.com/pkgs/main
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch

cc @ngimel

**Comment by colesbury** [comment]
I'm not sure there's much to suggest other than trying:

1) PyTorch built with a different CUDA version
2) Updating your NVIDIA driver

From what I understand, this is installed via conda, right? Does your GPU work otherwise?

The Julia documentation suggests:

```
unknown error (code 999): this often indicates that your set-up is broken, eg. because you didn't load the correct, or any, kernel module. Please verify your set-up, on Linux by executing nvidia-smi or on other platforms by compiling and running CUDA C code using nvcc.
```
(From http://juliagpu.github.io/CUDAdrv.jl/v0.5.1/)

**Comment by aluo-x** [comment]
@GanjinZero I'm curious how you eventually fixed this error. I have the exact same issue. Pytorch 1.4.0 built from source against CUDA 10.2

**Comment by GanjinZero** [comment]
> @GanjinZero I'm curious how you eventually fixed this error. I have the exact same issue. Pytorch 1.4.0 built from source against CUDA 10.2

Downgrade to pytorch 1.2.0

**Comment by aluo-x** [comment]
I ended up fixing my issue by re-installing the proprietary Nvidia driver on linux with the line `--no-nvidia-modprobe` **removed**. I was then able to build pytorch 1.4.0 from source:
`USE_CUDA=1 USE_CUDNN=1 USE_MKLDNN=1 USE_MKLDNN_CBLAS=1 python setup.py develop` which installed pytorch into my conda environment.

**Comment by sodik82** [comment]
jsut for future googlers: I found following solution - https://discuss.pytorch.org/t/cuda-runtime-error-999/69658/11

> You could try to reload the nvidia kernel module via:
> 
> sudo rmmod nvidia_uvm
> sudo modprobe nvidia_uvm
> Ubuntu seems to have some issues with sleep/suspend (or maybe Linux in general?).
>
