### ISSUE TITLE
[libtorch]  "tensor(cuda) to cv::Mat" has different results with" tensor(cpu) to cv::Mat"

### ISSUE THREAD

**Issue by iamwangyabin** [pytorch/pytorch#31183]
## 🐛 Bug
when I use libtorch v1.3.1,I found I always have wrong results when I convert a cuda tensor to opencv Mat ,so I run a simple test :

```
    torch::Tensor abc=torch::randn({3,3}).cuda();
    cout<<abc<<endl;
    cout<<abc.cpu()<<endl;

    torch::Tensor abc2 = abc.cpu();

    cv::Mat des1(abc.size(0), abc.size(1), CV_32FC1, abc2.data<float>());
    cout<<des1<<endl;
    cv::Mat des2(abc.size(0), abc.size(1), CV_32FC1, abc.cpu().data<float>());
    cout<<des2<<endl;
```
 which result is :+1: 

```
 1.6148  0.0606 -0.5458
-1.0770  0.3455 -1.3513
 0.0765 -0.1091 -0.2482
[ Variable[CUDAFloatType]{3,3} ]

 1.6148  0.0606 -0.5458
-1.0770  0.3455 -1.3513
 0.0765 -0.1091 -0.2482
[ Variable[CPUFloatType]{3,3} ]

[1.6148461, 0.060610425, -0.54580522;
 -1.0769745, 0.3454887, -1.3513325;
 0.076490507, -0.10907244, -0.24816529]

[6.8572272e+33, 4.5704751e-41, 1.4012985e-45;
 -1.0769745, 7.8132725e-06, 0;
 0.076490507, -0.10907244, -0.24816529]
```

Could I just simply use `Tensor.cpu()` without create a new cpu tensor to convert a cuda tensor to cv::Mat?

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

**Comment by colesbury** [comment]
Yes you can use `Tensor.cpu()` to create a CPU tensor for cv::Mat:

```c++
    torch::Tensor abc2 = abc.cpu();

    cv::Mat des1(abc.size(0), abc.size(1), CV_32FC1, abc2.data<float>());
    cout<<des1<<endl;
```

The second example is WRONG because the CPU tensor gets immediately destroyed. You need to make sure that the CPU tensor (i.e. `abc2`) stays alive for at least as long as the `cv::Mat` is alive.

```c++
    cv::Mat des2(abc.size(0), abc.size(1), CV_32FC1, abc.cpu().data<float>());
    cout<<des2<<endl;
```
