### ISSUE TITLE
ONNX to PYTORCH

### ISSUE THREAD

**Issue by kshamaramesh** [pytorch/pytorch#31189]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.3.1
 - OS (e.g., Linux):16.04
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:10.0
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

please find the code here

`from networks1 import*

def convert_onnx():
    generator = VAEGen(3).cuda() # Initalize your weights there
    dummy_input = torch.randn(1 ,3, 256, 256).cuda()
    torch.onnx.export(generator, dummy_input, "exported.onnx")

convert_onnx()
`

**Comment by colesbury** [comment]
This issue has no description of the problem. Please re-open with a description of the bug.
