### ISSUE TITLE
DataLoader: missing data fields

### ISSUE THREAD

**Issue by fhamborg** [pytorch/pytorch#31182]
## 🐛 Bug

When having multiple data fields in a dictionary that is passed to a `DataLoader` object, where some of these fields have a similar name, the resulting batch only contains a subset of these fields.

Specifically, the fields are named:
```
text_raw_indexes
special_text_target
...
global_context_ids0
global_context_type_ids0
global_context_attention_mask0
global_context_ids1
global_context_type_ids1
global_context_attention_mask1
global_context_ids2
global_context_type_ids2
global_context_attention_mask2
...
```

After passing a list of dicts, where each dict represents one document and the dict has keys named as shown above and respective data in each value, only the first three `global_context_*0` are contained in the batch, e.g., at the point `# here` in the following snippet, the variable `sample_batched` will only contain the following keys: `text_raw_indexes, special_text_target, ..., global_context_ids0, global_context_type_ids0, global_context_attention_mask0`. 

Note that `global_context*1 and 2` are missing.

```
for i_batch, sample_batched in enumerate(train_data_loader):
       # here
```

## Expected behavior

`sample_batched` should contain all keys, particularly not only the first three starting with `global_context_*0`.

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.2
GCC version: Could not collect
CMake version: version 3.15.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] pytorch-transformers==1.2.0
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      233
[conda] pytorch                   1.3.0                   py3.7_0    pytorch
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torchvision               0.4.1                  py37_cpu    pytorch

cc @SsnL

**Comment by colesbury** [comment]
That's strange... we would definitely accept PRs to fix this!

**Comment by SsnL** [comment]
This happens when your dicts don't have matching set of keys...

**Comment by colesbury** [comment]
@SsnL do you mean that some entries are missing say "global_context_attention_mask1" so it's not included in the batch?

@fhamborg would you please check if that's the issue. A self-contained reproducible example would also help.

**Comment by fhamborg** [comment]
@colesbury Indeed, that seems to be the cause of the issue - not all entries contained `global*3`, for example. Sorry for the confusion and thanks a lot for the quick help. So, I guess this is not a bug then and the issue could be closed. 

However, the behavior is also at least slightly unexpected, i.e., one might assume that either (1) all names are contained but containing a `None` for data items that actually not contain the name(s), (2) throw an error. Just my two cents :-) Thanks again for your help!
