### ISSUE TITLE
Quantized LSTM: "RuntimeError: expected scalar type Float but found QInt32"

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#31192]
## 🐛 Bug

When using the quantized LSTM, an error pops up saying `RuntimeError: expected scalar type Float but found QInt32`

## To Reproduce

```python
import torch
import torch.nn.quantized.dynamic as nnqd

seq_len = 128
batch = 16
input_size = 3
hidden_size = 7
num_layers = 2
bias = True
bidirectional = False

x = torch.rand(seq_len, batch, input_size)
h = torch.rand(num_layers * (bidirectional + 1), batch, hidden_size)
c = torch.rand(num_layers * (bidirectional + 1), batch, hidden_size)

dtype = torch.qint8

cell_dq = nnqd.LSTM(input_size=input_size,
                    hidden_size=hidden_size,
                    num_layers=num_layers,
                    bias=bias,
                    batch_first=False,
                    dropout=0.0,
                    bidirectional=bidirectional,
                    dtype=dtype)

y, (h, c) = cell_dq(x, (h, c))
```

## Expected behavior

The behavior should be equivalent to the non-quantized LSTM. Replacing the above code with `nn` instead of `nnqd` works.

## Environment

```console
python ./torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.4.0a0+bf60aba
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.1
GCC version: Could not collect
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.4.0a0+bf60aba
[pip3] torchsummary==1.5.1
[conda] Could not collect
```

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jamesr66a** [comment]
This indeed looks like a bug. Notice the `from_float` method directly pulls the bias from the original module: https://github.com/pytorch/pytorch/blob/cc8d6342fced4218f03f11d31b1316559aa80fae/torch/nn/quantized/dynamic/modules/rnn.py#L239

Whereas the __init__ constructor instantiates an int32 tensor: https://github.com/pytorch/pytorch/blob/cc8d6342fced4218f03f11d31b1316559aa80fae/torch/nn/quantized/dynamic/modules/rnn.py#L111

I believe the `__init__` case is incorrect. I'll send a patch
