### ISSUE TITLE
Bool tensors should be able to be flipped

### ISSUE THREAD

**Issue by fuzic** [pytorch/pytorch#31213]
## 🐛 Bug

Most tensor types support the `.flip(dim: int)`, but not `BoolTensor`s. It seems they ought to support flipping too.

## To Reproduce

```
>>> torch.BoolTensor([False, True]).flip(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "flip_cpu" not implemented for 'Bool'
```

## Expected behavior

This should not error

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

cc @izdeby

**Comment by izdeby** [comment]
Will be fixed by this [PR](https://github.com/pytorch/pytorch/pull/31267)

**Comment by izdeby** [comment]
Fixed
