### ISSUE TITLE
Better initialization in Embedding class

### ISSUE THREAD

**Issue by robertoalotufo** [pytorch/pytorch#3121]
I noticed that the weight initialization in the Embedding class is:

    def reset_parameters(self):
        self.weight.data.normal_(0, 1)

It took me many hours to find out the reason why my net did not train. The values are too high.
I suggest to initialize with the same option as other linear layers.

A workaround to this is just to make the initialization yourself.

**Comment by mruberry** [comment]
Closing due to age. @robertoalotufo, if this is still an issue, would you please file a new issue?
