### ISSUE TITLE
graph computation, out of memory, Reduce Failed to Synchronise, device-side assert triggered

### ISSUE THREAD

**Issue by lscelory** [pytorch/pytorch#31231]
Hello,
Thank you for reading my long question.
First, my model can be denoted as:
```def forward(self, x, y):  
    x, temp = self.backbone(x)  
    y, temp = self.backbone(y)  
    *some operation to x and y*  
    x = self.module(x, y)  
    y = self.module(x, y)  
    return x, y, temp  
```
My model consist of two parts, one backbone and one post process module. I have two inputs and three outputs. Now I want to train this model using data from two different dataset. images from dataset 1 are focusing on data extracting and images from dataset 2 are paired images which have strong relationship, and I want to use this pair images to train the post module. I train my model in an alternative way. Like:
```
for iter, batch in enumerate(dataset):
    #from dataset 1
    image = batch['image'].cuda()
    gt = batch['gt'].cuda()
    #from dataset 2
    target = batch['target'].cuda()
    target_gt = batch['target_gt'].cuda()
    search = batch['search'].cuda()
    search_gt = batch['search_gt'].cuda()
    optim.zero_grad()
    if iter % 3 == 0: # every 3 iters 1 time
      pred1, pred2, pred3 = model(image, image)
      loss = crit(pred3, gt)
      loss.backward() 
    else:
      pred1, pred2, pred3 = model(target, search)
      loss = crit(pred1, target_gt) + crit(pred2, search_gt) 
      loss.backward() 
    optim.step()
```
Now my questions are:
1. out of memory
I run my training code and it always out of memory after the first iteration, which means, the model can run an entire forward backward iteration only once and at second iteration forward process, it out of memory.
However, when I delete the *if* branch, only use data from dataset 2 to train, it works successfully. I don't know whether it related to pytorch computation graph such as the framework will create two different graph when I use two dataset by if...else... And the gpu can't hold two graph intermediate variables.

Then I change my code like this:
```
    optim.zero_grad()
    if iter % 3 == 0: # every 3 iters 1 time
      pred1, pred2, pred3 = model(image, image)
    else:
      pred1, pred2, pred3 = model(target, search)
    loss1 = crit(pred3, gt)
    loss2 = crit(pred1, target_gt) + crit(pred2, search_gt)       
    if iter % 3 == 0:
      lambda1 = 0
      lambda2 = 1
    else:
      lambda1 = 0
      lambda2 = 1
    loss = lambda1*loss1 + lambda2*loss2
    loss.backward() 
    optim.step()
```
I think my change can make pytorch compute the same graph every iteration and it indeed ran successfully and did not out of memory ... for some epochs...
After about 1 epoch, I got a runtimeerror called:
`
    return torch._C._nn.binary_cross_entropy(input, target, weight, size_average, reduce)
RuntimeError: reduce failed to synchronize: device-side assert triggered
`
2. It seems my output of model(pred3) are out of range [0, 1] because my criterion is *nn.BCELoss* which need input tensor in [0, 1]. Since I have used *nn.Sigmoid* at the last layer in my model, I think it appear NaN somewhere in my model intermediate variables.

There are my env:
- OS: Ubuntu 16.04
- PyTorch version: 0.4.1
- Python version: Python 3.6
- CUDA/cuDNN version: CUDA 9.0, cudnn 7.6
- GPUs: Nvidia 1080Ti 11G

Thank you again for your patient. I wish your reply about my two questions.
My questions are related to #2209 #5560

**Comment by zou3519** [comment]
This seems like a question. If it is not an explicit bug report or feature request, you should post at discuss.pytorch.org to get support.

However, there might be a bug lurking around here, so please re-open this if there is a bug somewhere.
