### ISSUE TITLE
libtorch can not link program now

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#31237]
## 📚 Documentation

Download libtorch from website, old program using libtorch can not link now:

```
libtorch/include/c10/util/C++17.h:20:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch

```

While I have already set C++14 in cmakelists:

```

set(CMAKE_CXX_STANDARD 14)
add_definitions(-std=c++14)
```

But keep get such error.

cc @yf225

**Comment by zou3519** [comment]
Do you have a self-contained script which we could use to reproduce the problem, or more of the build output? I suspect something is wrong with your cmakelists

**Comment by rgommers** [comment]
Possibly because `conda` adds `-std=c++17`, see https://github.com/pytorch/pytorch/issues/35012#issuecomment-603419283 for how to undo that.

Anyway, no response so closing.
