### ISSUE TITLE
How to do independent random number generatation in multiprocessing dataloader.

### ISSUE THREAD

**Issue by EricKani** [pytorch/pytorch#31246]
When I use num_woker > 0 in DataLoader, and I generate a random number in __getitem__ function.

I found all threads will generate the same random number... 

For example, I set num_worker=8, and I want to got a random number to define my scale augmentation. 

I will get 
0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9
eight same 0.9!

So I want to know how to inplement  independent random number generation in multiprocessing dataloader.

THanks...

cc @SsnL

**Comment by SsnL** [comment]
See https://pytorch.org/docs/stable/notes/faq.html#my-data-loader-workers-return-identical-random-numbers
