### ISSUE TITLE
Does pytorch have Softmax3D ？

### ISSUE THREAD

**Issue by barrykui** [pytorch/pytorch#3124]
I am doing a 3d project and I found that pytorch has conv3d, pooling3d and batchnorm3d, but I didn't find the softmax3d. 
Does anyone have softmax3d layer?

**Comment by apaszke** [comment]
We don't have a layer, but the functional version works:
```
import torch.nn.functional as F
F.softmax(Variable(torch.randn(1, 3, 5, 5, 5)))
```

**Comment by barrykui** [comment]
@apaszke Thanks for your kind hearted reply. However, `F.softmax` is only support  1D, 2D, 3D or 4D tensor, not support 5D tensor (batch, channel, Width, Height, Length ) yet. So I come here to encounter someone who has implemented the  5D tensor supported softmax.

The followings is the output of the code you shared.
```
>>> import torch
>>> from torch.autograd import Variable                                                                               
>>> import torch.nn.functional as F                                                                                   
>>> a=F.softmax(Variable(torch.randn(1, 3, 5, 5, 5)))                                                                 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jsptgpu/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 529, in softmax
    return _functions.thnn.auto.Softmax.apply(input)
  File "/home/jsptgpu/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/thnn/auto.py", line 174, in forward
    getattr(ctx._backend, update_output.name)(ctx._backend.library_state, input, output, *args)
RuntimeError: invalid argument 2: 1D, 2D, 3D or 4D tensor expected at /pytorch/torch/lib/THNN/generic/SoftMax.c:40
```

**Comment by apaszke** [comment]
Ah my bad! That will be fixed once #2899 lands.

**Comment by barrykui** [comment]
Wow, Great! Thank you. When and how that version would be available?

**Comment by apaszke** [comment]
Once it's merged it will be in master, so you can use it as long as you install from source. After this, it will be in the next binaries, but I don't know when we'll release them

**Comment by barrykui** [comment]
OK, got it, thank you very much.

**Comment by sunformoon** [comment]
Hello I am wondering do we have the merged Softmax3D in master? There seems to be no document description for Softmax3D yet.

Thanks!

**Comment by soumith** [comment]
yes it is there. now Softmax can take `dim` argument that will allow you to do Softmax3D
