### ISSUE TITLE
Unnormal cpu usage of  'torch.triu()' 

### ISSUE THREAD

**Issue by SpartaG117** [pytorch/pytorch#31242]
## 🐛 Bug

 the cpu usage of torch.triu() can be multitimes(10~20) higher than that of other normal operation. eg. normal operation (100% CPU usage), troch.triu() (1000%~2000% CPU usage) under top command.

## To Reproduce
can be reproduced easily by:

```
for i in range(100000000):
    sz = 16
    mask = torch.triu(torch.ones(sz, sz))
```
## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40
GPU 4: Tesla P40
GPU 5: Tesla P40
GPU 6: Tesla P40
GPU 7: Tesla P40

Nvidia driver version: 418.87.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.3.1                    pypi_0    pypi
[conda] torchvision               0.4.2                    pypi_0    pypi

**Comment by VitalyFedyunin** [comment]
`triu` is using multi-threading optimization and might use multiple CPU cores. Feel free to reopen this issue if you feel it is bug and you need to report the issue.
