### ISSUE TITLE
Add ONNX model generator with IR 0.0.3 for TensorRT

### ISSUE THREAD

**Issue by MaratZakirov** [pytorch/pytorch#31249]
## 🚀 Feature
Please add dumping ONNX model with IR of version 0.0.3 for TensorRT support

## Motivation
TensorRT currently does not support ONNX models with IR > 0.0.3. Even pretty old PyTorch versions generate ONNX with IR = 0.0.4. Or probably dumping to caffe format may also help, but as know there are no such option.

UPDATE

Are Caffe2 dead (caffe2.io at least)? I tried to install caffe2 package using conda but it seems to be dead also

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by zwqnju** [comment]
I meet the same problem. 
I tried the older versions of PyTorch. It seems that PyTorch 1.0.0 exports ONNX model with IR 0.0.3. But I still cannot run it with TensorRT engine.

I run the sample code here:
[https://github.com/RizhaoCai/PyTorch_ONNX_TensorRT/blob/master/pytorch_onnx_trt.ipynb](url)

I get the following errors:
`
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.

Traceback (most recent call last):
File "main.py", line 43, in <module>
    context = engine.create_execution_context() 
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
`

**Comment by jlucier** [comment]
I think your problem is related to the `opset_version` pytorch seems to be exporting. Check this out:
https://github.com/NVIDIA/TensorRT/issues/148#issuecomment-617257189

**Comment by thiagocrepaldi** [comment]
@MaratZakirov Do you still have this issue?

Caffe2 will be dropped in the next PyTorch version

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
