### ISSUE TITLE
torch.cuda.is_available() is False

### ISSUE THREAD

**Issue by ucasiggcas** [pytorch/pytorch#31243]
hi,Dear
Just want to install the great pytorch, but when I use pip ,ups the error
 ```
$ pip install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html
$ python3
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False

```
**Ubuntu1804,
python37**

So what should I do ?
any advice or suggestion will be appreciated.
thx

**pls do not close the issue quickly**

**Comment by peterjc123** [comment]
Would you please update the gpu driver? What's the output of nvidia-smi?

**Comment by ucasiggcas** [comment]
@peterjc123 
410.48,,
need higher ??

**Comment by peterjc123** [comment]
Yes, you'll need to update it to at least 418.39. Please refer to this page. https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

**Comment by 44REAM** [comment]
At first I install the stable version with

`pip3 install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html

and the cuda is work perfectly fine
`
But I got this after I install nightly version by conda install ignite -c pytorch-nightly

```
print(torch.cuda.is_available())
False
```

nvidia driver version: 441.41
PyTorch Version : 1.3.1
OS (e.g., Linux): Windows10
How you installed PyTorch (conda, pip, source): conda install ignite -c pytorch-nightly
Python version: 3.7.4
CUDA/cuDNN version: cuda 10.1 V 10.1.105

Can you help?
Thank

**Comment by peterjc123** [comment]
It is possible that the dependency `torch` in `ignite` is pinned to the cpu version. You could try installing it with the flag `--no-deps`. Alternatively, just keep consistent in the choice of the package manager and use `pip install --pre pytorch-ignite`.
