### ISSUE TITLE
I feel mask slice takes too much time.

### ISSUE THREAD

**Issue by erdongchendou** [pytorch/pytorch#31245]
## ❓ Questions and Help

```
pred = torch.rand((30000, 10))
pred = pred.cuda(6)
ind = pred[:, 5] > 0.9

st = time.time()
pred = pred[ind]
time_pased = time.time() - st
print(time_pased)
```
The time_pased is about 10ms. Is it normal? Or did I do anything wrong?

**Comment by albanD** [comment]
Please do not post both on the forum and here.
You should use the forum for questions.

Ref to the forum post with answer: https://discuss.pytorch.org/t/i-feel-mask-slice-takes-too-much-time/63982

**Comment by erdongchendou** [comment]
ok, sorry.
