### ISSUE TITLE
torch.sqrt gives different result on CPU and GPU

### ISSUE THREAD

**Issue by ousou** [pytorch/pytorch#31250]
## 🐛 Bug

In some cases torch.sqrt returns different values when evaluated on CPU and GPU.

## To Reproduce

```
# On GPU
>>> torch.sqrt(torch.tensor([0.5158079862594604], dtype=torch.float32).to(0)).item()
0.718197762966156

# On CPU
>>> torch.sqrt(torch.tensor([0.5158079862594604], dtype=torch.float32)).item()
0.7181977033615112

# Result on NumPy for comparison
>>> np.sqrt(np.array([0.5158079862594604], dtype=np.float32)).item()
0.718197762966156
```

Another example:
```
# On GPU
>>> torch.sqrt(torch.tensor([0.5028960704803467], dtype=torch.float32).to(0)).item()
0.7091516852378845

# On CPU
>>> torch.sqrt(torch.tensor([0.5028960704803467], dtype=torch.float32)).item()
0.7091516256332397

# Result on NumPy for comparison
>>> np.sqrt(np.array([0.5028960704803467], dtype=np.float32)).item()
0.7091516852378845
```

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 418.87.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.3.0
[conda] Could not collect

## Additional context

I generated 100000 random values with torch.rand, and the value of torch.sqrt was different on CPU vs. GPU about 600 times (i.e. about 0.6% of the time).

I found the issue when using the function torch.nn.functional.pairwise_distance and noticed there some differing results when running on CPU vs. GPU.

**Comment by ousou** [comment]
I noticed something strange: The bug does not occur when I run them on my own laptop, and when I use another AWS cloud instance type (p3.2xlarge). I can repeat the bug on the AWS instance type  g4dn.12xlarge, with CPU type Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz. 

The bug does not happen when using instance type p3.2xlarge with CPU type Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz, or on my laptop which has the CPU Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz.

**Comment by xsacha** [comment]
Is it the CPU producing a different result or the GPU in this instance?
That is, is the Turing architecture (Tesla T4) responsible?

**Comment by albanD** [comment]
Hi,

The difference is smaller than 1e-7. So this is expected: these two numbers are actually equal up to the precision of float32. You see difference in some cases but not all because some hardware use the same algorithm to compute the square root but not all, and not for all input values.

You will need to use double precision if you want more accurate results.

**Comment by ousou** [comment]
Great, thanks for the clarification!
