### ISSUE TITLE
How calling an instance of class 'Linear' works if there is no method/function '__call__()' defined in class 'Linear' ?

### ISSUE THREAD

**Issue by DeepakIITJ** [pytorch/pytorch#31257]
Code:

from torch.nn import Linear
model = Linear(in_features = 1, out_features = 1)
y = model(x) # calling an instance of class Linear

Although, ‘Linear’ class inherits ‘Module’ class, which has ‘__ call()__’ defined in it. I could not catch it from there. Kindly help. 

As far as I know; In python, to call an instance (here model()) of a class, the class must have ‘__ call()__’ defined in it. But how does this work in the case of class- ‘Linear’?

**Comment by vishwakftw** [comment]
The `__call__` basically calls `forward()` with the arguments passed to it. This can be seen at `pytorch/torch/nn/modules/module.py`.

Questions like these are better catered to on the [forums](https://discuss.pytorch.org)

**Comment by zou3519** [comment]
@DeepakIITJ Please direct future questions to the forums. We like to keep the issue tracker filled with real bug reports and/or feature requests.

**Comment by DeepakIITJ** [comment]
Thank you @vishwakftw and @zou3519 .
 I'll take care of it.
