### ISSUE TITLE
cudnn version detection script may not always choose latest CuDNN

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3126]
My CuDNN install looks like this:

```
ls /usr/local/cuda/lib64 | grep cudnn
libcudnn.so
libcudnn.so.5
libcudnn.so.5.1.10
libcudnn.so.6
libcudnn.so.6.0.21
libcudnn_static.a
```

Notably, `libcudnn.so` is linked to a suitably new version of CuDNN.

```
ls -l /usr/local/cuda/lib64/libcudnn.so
lrwxrwxrwx. 1 sgross users 13 Apr 12  2017 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.6
```

However, the version detection code added in 1322f9a272db91b8bc0254c6cdf4ea787120631b does not look at the default `libcudnn.so`, and instead arbitrarily picks on of the versions visible from the filesystem. In my system, it picks wrong, and concludes that I don't have a recent enough version of CuDNN (even though I do.)

CC @zou3519

**Comment by apaszke** [comment]
Let's just edit the code to either follow the symlink, or always pick the newest one

**Comment by soumith** [comment]
let's make it pick the newest one.

**Comment by zou3519** [comment]
Instead of reading the names of the .so files and inferring the library version I could make the script read cudnn.h and look at CUDNN_MAJOR. I think that should be unambiguous -- what do you guys think about that?

**Comment by ezyang** [comment]
Can you paste a copy of one of the gcc invocations that is failing? For your particular case, this shouldn't happen because we always put the CuDNN include directory before the CUDA directory. But maybe there's something else going on. In any case, this is unrelated to this issue, so I'd recommend opening a new issue.

**Comment by frankang** [comment]
This might be an example of the gcc code. So the correct path has been indicated by the setup.py file, and both the correct include path and wrong version(v5) include path are in the gcc -I options.

`gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/user99/miniconda3/include -I/home/user99/pytorch -I/home/user99/pytorch/torch/csrc -I/home/user99/pytorch/torch/lib/pybind11/include -I/home/user99/pytorch/torch/lib/tmp_install/include -I/home/user99/pytorch/torch/lib/tmp_install/include/TH -I/home/user99/pytorch/torch/lib/tmp_install/include/THNN -I/home/user99/pytorch/torch/lib/tmp_install/include/ATen -I/home/user99/miniconda3/lib/python3.6/site-packages/numpy/core/include -I/home/user99/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda-8.0/include -I/home/user99/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/user99/miniconda3/include/python3.6m -c /home/user99/pytorch/torch/csrc/generated/cuda_TensorByte.cpp -o build/temp.linux-x86_64-3.6/home/user99/pytorch/torch/csrc/generated/cuda_TensorByte.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda-8.0/lib64 -DWITH_NCCL -DWITH_CUDNN
In file included from torch/csrc/cudnn/Types.h:7:0,
                 from torch/csrc/cudnn/Types.cpp:2:
torch/csrc/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"`

**Comment by ezyang** [comment]
And at risk of asking a silly question, you are sure there is a `cudnn.h` in `/home/userXXX/miniconda3/include` (and it's not in some subdirectory like `/home/userXXX/miniconda3/include/cudnn`?)

**Comment by frankang** [comment]
Yes, I just checked that. There is a cudnn.h file in the /home/userXXX/miniconda3/include folder of version 6021. And there is no subdirectory of "/home/userXXX/miniconda3/include/cudnn" @ezyang

**Comment by lshiwjx** [comment]
try the reverse operation of https://github.com/pytorch/pytorch/pull/5026/commits/5ac463751393b9439661830589251b91d625e376
