### ISSUE TITLE
Compile Error for .cu files when using libtorch (caused by nvcc flags)

### ISSUE THREAD

**Issue by auroraustc** [pytorch/pytorch#31283]
## 🐛 Bug

After the cmake is done, when compiling .cu files in my project, the following error will occur:
```bash
nvcc fatal   : Unknown option 'Wall'
```
The `flags.make` shows the following result:
```bash
$cat CMakeFiles/train.dir/flags.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# compile CUDA with /usr/local/cuda-9.2/bin/nvcc
# compile CXX with /usr/bin/c++
CUDA_FLAGS =  -O3   -D_GLIBCXX_USE_CXX11_ABI=1 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -fopenmp -std=c++14

CUDA_DEFINES = -DAT_PARALLEL_OPENMP=1
......
```
The `-O3` flag was added using `CMAKE_CUDA_FLAGS` in the `CMakeLists.txt`

## To Reproduce

1. Write a .cu file in the project
2. cmake then make
3. The error occurs

## Expected behavior

Those -Wxxx flags should not be added as cuda flags.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Compile from source
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
```bash
BUILD_TORCH=ON \
CMAKE_PREFIX_PATH="/usr/bin/;/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/;/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/;/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/include/" \
CUDA_BIN_PATH=/usr/local/cuda/bin \
CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/ \
CUDNN_LIB_DIR=/usr/local/cuda/lib64 \
USE_CUDA=1 \
USE_NNPACK=1 \
MAX_JOBS=8 \
python3 setup.py build
```
 - Python version: 3.6
 - CUDA/cuDNN version: 9.2/7.5
 - GPU models and configuration: NVIDIA GTX Titan
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @malfet @yf225 @glaringlee @ngimel

**Comment by zou3519** [comment]
@auroraustc are you linking a .cu file with libtorch, or are you compiling libtorch and adding a new .cu file?

**Comment by auroraustc** [comment]
@zou3519 Linking a .cu file with libtorch. I also tried the nightly build (2019/12/13) downloaded from pytorh.org, and got the same error. However, the stable version (1.3) works fine.
I am using an old GPU, therefore I have to compile pytorch from source to utilize my GPU.

**Comment by auroraustc** [comment]
Hello:
I have found out the reason of this problem: cuda is not fully compatible with gcc. After I switched to cuda10.1/gcc7.3, everything goes fine.

**Comment by zou3519** [comment]
@auroraustc what configuration were you using before?

**Comment by hxbai** [comment]
https://github.com/pytorch/pytorch/blob/5b3492df18f0c27c59bffc7e52bfea4db63907e6/cmake/public/utils.cmake#L252
maybe here should not be PUBLIC

**Comment by traveller59** [comment]
I have same problem when I build torch extension by cmake and torch nightly 1.6.0.dev20200331. after I remove all flags in 'INTERFACE_COMPILE_OPTIONS' in Caffe2Targets.cmake, the problem is solved.

**Comment by hxbai** [comment]
I hacked this problem by
```
if(TARGET torch_cuda)
  set_target_properties(torch_cuda PROPERTIES
                        INTERFACE_COMPILE_OPTIONS "")
endif()
if(TARGET torch_cpu)
  set_target_properties(torch_cpu PROPERTIES
                        INTERFACE_COMPILE_OPTIONS "")
endif()
```

**Comment by zsef123** [comment]
Same Issues in https://github.com/pytorch/vision/issues/2001

@fmassa

**Comment by auroraustc** [comment]
@zou3519 The pytorch version is 1.3. I compiled from source using cuda 9.2 and gcc 7.3. Actually the simplest way to get rid of this error is just removing the "-Wall" and some other flags in CMakeFiles/xxx/flags.cmake. No need to spend hours to recompile pytorch.
Anyway, I tried to use cuda 10.2 and cuda 10.1 to recompile, and cuda 10.1 seems fine, therefore I suspect that it might be a compatibility issue.
I will try the solutions mentioned by @hxbai and @traveller59

**Comment by jamesljlster** [comment]
The problem seems to be resolved after cmake 3.17.
I can compile cuda extension successfully without any patch under the environment:
- Docker image: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
- PyTorch 1.5.0 under miniconda (py3.7_cuda10.2.89_cudnn7.6.5_0)
- CMake 3.17.2 (build from source)

**Comment by traveller59** [comment]
This problem is "solved" in cuda 10.2, not cmake 3.17. it looks no problem when add these flags to nvcc in cuda 10.2.

**Comment by zou3519** [comment]
Given there are six independent reports of this in this thread, I am going to pre-emptively bump the priority of this

**Comment by malfet** [comment]
I think two things must be done here:
 - Guard all host compiler specific options in https://github.com/pytorch/pytorch/blob/7a3c223bbb711c7a93910ce406a0126b8000b43b/cmake/public/utils.cmake#L254 with  $<$<COMPILE_LANGUAGE:CXX>: as recommended in [Modern CMake with CUDA] (https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9444-build-systems-exploring-modern-cmake-cuda-v2.pdf) GTC talk
