### ISSUE TITLE
Fix simple typo: whos -> whose

### ISSUE THREAD

**Issue by timgates42** [pytorch/pytorch#31287]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine caffe2/python/core.py.
2. Search for `whos`.

# Expected Behaviour

1. Should read `whose`.

**Comment by zou3519** [comment]
Feel free to submit a PR and tag me as reviewer.

**Comment by timgates42** [comment]
@zou3519 thanks here is the PR https://github.com/pytorch/pytorch/pull/31288 - I could not seem to assign it to you sorry.
