### ISSUE TITLE
wrong parameter momentum when torch.onnx.export()

### ISSUE THREAD

**Issue by anguschowchowxu** [pytorch/pytorch#31296]
## 🐛 Bug

when model exported as onnx representation, batchnorm2d momentum is not the same.

## To Reproduce

1.Steps to reproduce the behavior:

Create PyTorch model:
import torch
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

class PytorchModel(nn.Module):
    def __init__(self):
        super(PytorchModel, self).__init__()
        self.bn = nn.BatchNorm2d(1, momentum=0.2)

    def forward(self, x):
        x = self.bn(x)
        return x

pytorch_model = PytorchModel()
pytorch_model.eval()

x_data = np.random.uniform(0, 1, size=(1, 1, 224, 224))
x = Variable(torch.Tensor(x_data))

2. torch_out = torch.onnx._export(pytorch_model, x, "model.onnx", export_params=True)

3.import onnx
onnx_model = onnx.load("model.onnx")
onnx.checker.check_model(onnx_model)
onnx.helper.printable_graph(onnx_model.graph)

out[0]: 'graph torch-jit-export (\n  %input[FLOAT, 1x1x224x224]\n) initializers (\n  %1[FLOAT, 1]\n  %2[FLOAT, 1]\n  %3[FLOAT, 1]\n  %4[FLOAT, 1]\n  %5[INT64, scalar]\n) {\n  %6 = BatchNormalization[epsilon = 9.99999974737875e-06, momentum = 0.800000011920929](%input, %1, %2, %3, %4)\n  return %6\n}'

## Expected behavior

print(pytorch_model.bn)
out[1]: BatchNorm2d(1, eps=1e-05, momentum=0.2, affine=True, track_running_stats=True)

## Environment

 - PyTorch Version (e.g., 1.0):  1.3.0
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): - 
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: -
 - Any other relevant information: onnx 1.0

## Additional context

whether the pytorch batchnorm2d momentum params should be the opposite to the onnx batchnorm momentum or not.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @vincentqb

**Comment by SsnL** [comment]
I think onnx is right here. PyTorch `momentum` is really `1-momentum` but unfortunately we can't change due to historical reasons.

**Comment by anguschowchowxu** [comment]
> I think onnx is right here. PyTorch `momentum` is really `1-momentum` but unfortunately we can't change due to historical reasons.

thx for reply.
I

**Comment by anguschowchowxu** [comment]
@SsnL Hi Could you do me another favor. This is my test code.
```
import sys
import os
import numpy as np
import onnxruntime as ort

import torch
import torch.nn as nn
from torch.autograd import Variable

class PytorchModel(nn.Module):
    def __init__(self):
        super(PytorchModel, self).__init__()
        self.bn = nn.Sequential(
        	# nn.BatchNorm2d(3, momentum=0.2),
            nn.ConvTranspose3d(3, 3, (2,2,2), (2,2,2)),
        	)

    def forward(self, x):
        x = self.bn(x)
        return x

pytorch_model = PytorchModel()
pytorch_model.eval()

x_data = np.random.uniform(0, 1, size=(1, 3, 224, 224, 224))
x = Variable(torch.Tensor(x_data))
torch_out = torch.onnx._export(pytorch_model, x, "model.onnx", export_params=True)

x_data = np.random.uniform(0, 1, size=(1, 3, 224, 224, 224))
x = Variable(torch.Tensor(x_data))
output_t = pytorch_model.cuda()(x.cuda())

model_path = 'model.onnx'
sess = ort.InferenceSession(model_path, None)
input_name = sess.get_inputs()[0].name  
output_name = sess.get_outputs()[0].name 

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

output_o,  = sess.run([output_name], {input_name: to_numpy(x)})

print(output_o.shape)
print(np.testing.assert_allclose(to_numpy(output_t), output_o, rtol=1e-03, atol=1e-05))
```

It raise error as,
```
2019-12-16 06:17:36.389459089 [E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running ConvTranspose node. Name:'' Status Message: Input X must be 4-dimensional. X: {1,3,224,224,224}
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    output_o,  = sess.run([output_name], {input_name: to_numpy(x)})
  File "/home/xyh/anaconda3/envs/myonnxrt/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ConvTranspose node. Name:'' Status Message: Input X must be 4-dimensional. X: {1,3,224,224,224}
```

**Comment by wuzhi19931128** [comment]
Obviously should be two 224

**Comment by neginraoof** [comment]
This is an onnxruntime issue. ORT used to have support for 2D ConvTranspose. It has recently been updated to support 1D ConvTranspose as well. But 3D is not supported yet. You can follow this issue through: https://github.com/microsoft/onnxruntime/issues/965

**Comment by anguschowchowxu** [comment]
> This is an onnxruntime issue. ORT used to have support for 2D ConvTranspose. It has recently been updated to support 1D ConvTranspose as well. But 3D is not supported yet. You can follow this issue through: [microsoft/onnxruntime#965](https://github.com/microsoft/onnxruntime/issues/965)

Thx a lot. This solves my confusion.

**Comment by Joevaen** [comment]
> > This is an onnxruntime issue. ORT used to have support for 2D ConvTranspose. It has recently been updated to support 1D ConvTranspose as well. But 3D is not supported yet. You can follow this issue through: [microsoft/onnxruntime#965](https://github.com/microsoft/onnxruntime/issues/965)
> 
> Thx a lot. This solves my confusion.

Hi, my input data is 5-dim which is same with yours. Did you convert pth to onnx successfully? I didn't meet error or warning but the onnx converted was false and useless.

**Comment by spandantiwari** [comment]
Closing as original issue seems to be resolved.
