### ISSUE TITLE
RuntimeError: cublas runtime error when using torch.bmm on cuda 10

### ISSUE THREAD

**Issue by drewkerwin** [pytorch/pytorch#31291]
## 🐛 Bug

When performing matrix multiplication on batches, the torch.bmm function results in an error when performing the equivalent of a matrix multiplied by it's transpose

## To Reproduce

1. Run python
2. Verify python env has torch and requirements
3. Verify using ubuntu linux 16.04 with cuda 10.0
4. Run code below

```
import torch
x = torch.randn(3,4,6)
x = x.cuda(device=0)
z = torch.bmm(x, x.permute(0,2,1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450
```

## Expected behavior

Expected result of a bmm of x with shape (3,4,6) with it's transpose is z with shape (3,4,4)

## Environment

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:450
```

 - PyTorch Version torch==1.1.0
 - OS: 
         lsb_release -a
         No LSB modules are available.
         Distributor ID: Ubuntu
         Description:    Ubuntu 16.04.6 LTS
         Release:        16.04
         Codename:       xenial

 - How you installed PyTorch pip
 - Build command you used (if compiling from source): n/a
 - Python version: Python 3.5.6 :: Anaconda, Inc.
 - CUDA/cuDNN version:

```
Sat Dec 14 14:54:36 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:65:00.0 Off |                  N/A |
| 31%   44C    P2    63W / 250W |   8755MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     20328      C   python                                      2017MiB |
|    0     22796      C   python                                      2017MiB |
|    0     50613      C   python                                       857MiB |
|    0     57660      C   python                                      2015MiB |
|    0     77732      C   python                                      1839MiB |
+-----------------------------------------------------------------------------+
```

 - GPU models and configuration: RTX 2080ti
 - Any other relevant information:

## Additional context

cc @ngimel

**Comment by zou3519** [comment]
I'm not sure what is going on here. @ngimel have you seen this error message before?

**Comment by ngimel** [comment]
FWIW, it does not reproduced on Turing in colab, with pytorch 1.3.1. Not sure if pytorch 1.1 with cublas version that it came with had problems, but I doubt it. Error message looks like some setup problem.
https://colab.research.google.com/drive/1eKvaFERyxLM5x4hZCu3IdgsjPAb3vTNK

**Comment by drewkerwin** [comment]
The issues is reproducible based on the torch 1.1.0 as noted in the initial write up. 

Since then, updating cudatoolkit & torch has resolved the problem.
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
