### ISSUE TITLE
Sparse SGD + momentum  = cuda memory issue.

### ISSUE THREAD

**Issue by cedias** [pytorch/pytorch#3129]
When using classic SGD optimizer with momentum with sparse embeddings the memory keeps garbage collecting / allocating leading to slow down and out of memory error eventually. [Here is a minimal exemple to reproduce the issue](https://gist.github.com/cedias/946a380807b7e1bf92d738268b71415a)

![slowing](https://user-images.githubusercontent.com/1705336/31611730-87b2ccbc-b27d-11e7-8826-12023e848a77.png)

![memoryerror](https://user-images.githubusercontent.com/1705336/31612140-0fea1080-b27f-11e7-99b7-8dae06d931b1.gif)

The issue dissapears when momentum is not used
![nomomentum](https://user-images.githubusercontent.com/1705336/31611728-86c7a9f8-b27d-11e7-85b3-979ce180ec3d.png)

or when embeddings are not sparse
![notsparse](https://user-images.githubusercontent.com/1705336/31611729-872bb416-b27d-11e7-8ca1-65629cfae6bc.png)

I'm using the last pytorch version on conda: `'0.2.0_4'`

**Comment by SsnL** [comment]
I tried out your script with momentum 0.1 on master, it takes roughly 10800mb gpu memory max. This is caused by using sparse buffer. I'm sending out a PR for this.
