### ISSUE TITLE
[Tensorboard] Result of the graphs are different across pytorch versions

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#31305]
```
import torch
from torchvision.models import resnet50
from torch.utils.tensorboard import SummaryWriter


model = resnet50()
writer = SummaryWriter("/home/tensorboard_test")
board_input = torch.rand((3, 224, 224)).unsqueeze(0)
writer.add_graph(model, board_input)
writer.close()
```

I found that SummaryWriter in different version pytorch, I result is different.
In torch 1.1.0, the result is OK.
In torch 1.2.0, the program not report error, but no graph display in tensorboard.
In torch 1.3.0, the graph display in tensorboard, but the graph different between 1.1.0 and 1.3.0.
The graph, in torch 1.3.0, is very difficult to use. 

I suggest revert SummaryWriter to torch 1.1.0.

**Comment by as754770178** [comment]
I once submmit Issue #24904, but don't deal with.

**Comment by orionr** [comment]
cc @sanekmelnikov, @J0Nreynolds, @lanpa

**Comment by orionr** [comment]
@as754770178, can you do us a favor and try the version in nightly and see if it improves things? We had a regression in 1.3, but should be greatly improved for 1 .4.

**Comment by as754770178** [comment]
I try 1.4, the graph style is same with 1.3. The network show in horizontal, it's very hard to use.

**Comment by orionr** [comment]
@as754770178, sorry to hear that. @sanekmelnikov, @J0Nreynolds and @lanpa can you debug for the ResNet-50 architecture? Might not make it for 1.4, but we should try and improve for 1.5 at a minimum.

**Comment by as754770178** [comment]
I can't upload the tensorboard graph as a result of network, I describe it. In torch 1.1.0, I open the graph resnet50, the node is common operation such as conv, bn, etc. Now the node is detailed weight, and the graph is very long in horizontal. 
I think the format in torch 1.1.0 is good, because I only want to know the network architecture. If user want to comprehend in detail, they open the node to view, like the way in tensorflow.

**Comment by lanpa** [comment]
@as754770178 @orionr  This issue should already have been solved before 1.4.0a0+65f6e44 (a month ago)

And here is the result of this version. Would you like to try to build from master or use pytorch-nightly again?
![image](https://user-images.githubusercontent.com/2005323/72180231-ac72ef00-3421-11ea-9882-7593725d8a0c.png)

**Comment by as754770178** [comment]
@lanpa Thanks. The effect is very good.

**Comment by as754770178** [comment]
@lanpa Thanks. The effect is very good.

**Comment by as754770178** [comment]
@lanpa Thanks. The effect is very good.

**Comment by J0Nreynolds** [comment]
Hi @as754770178. Did the suggestion from @lanpa fix your issue?

**Comment by as754770178** [comment]
my torch version is 1.4.0a0+2c51e06, the result still like before that is different with @lanpa

**Comment by as754770178** [comment]
tensorboard version is 1.14.0

**Comment by lanpa** [comment]
Just tested with torch 1.4.0 from PyPI and the result is good too. Closing this.
