### ISSUE TITLE
THCAtomics.cuh equivalent for CPU 

### ISSUE THREAD

**Issue by palver7** [pytorch/pytorch#31309]
Hi, 
I am looking for the equivalent of THCAtomics.cuh in the ATen/src/TH folder and I cannot find it. I want to port a program written in CUDA to C/C++ to be used in CPU and I need the functionality of THCAtomics.cuh. Can someone point me to the right direction?

**Comment by zou3519** [comment]
Please direct questions to the pytorch forums: discuss.pytorch.org
