### ISSUE TITLE
Build libtorch with AMD support

### ISSUE THREAD

**Issue by yngtodd** [pytorch/pytorch#31318]
## 🚀 Feature
Build `libtorch` with AMD support. 

## Motivation

I will be working on a new machine that has AMD GPUs, and we would like to avoid the overhead of Python.

## Pitch

If possible, I would like to contribute to this effort. I would appreciate any guidance in that process.

## Alternatives

There could be a binary dump and all associated CMAKE files like the current release of libtorch, but I'd prefer to be able to cook it up myself.

## Additional context

This would be a great step in enabling Pytorch to run on the next generation of supercomputers. :wink:

cc @yf225

**Comment by zou3519** [comment]
I'm not sure what it would take to get this done or how good our rocm support is right now. @yf225 might be able to help

**Comment by vadimkantorov** [comment]
I think @t-vi tried it out, I remember a series of tweets :)

**Comment by t-vi** [comment]
1) @bddppq  and @iotamudelta are the [persons of interest for ROCm support](https://pytorch.org/docs/stable/community/persons_of_interest.html#amd-rocm-hip).
2) I always advise people to build the PyTorch package to get libtorch (I build on ROCm like [described on my blog](http://lernapparat.de/pytorch-rocm/)). PyTorch is a strict superset of libtorch and you can use the libraries and includes from there. (It used to be that this is how the official libtorch packages are built, I didn't check recently.)
3) So the Python interface currently presents the ROCm-supported cards as CUDA, but as far as I know the C++ interface does not but has a separate device type instead (I think).
4) As an aside: For most people I talked to, the overhead of Python isn't what they thought. (It's 10% for the LLTM extension example on a typical machine, probably less for CNNs; more if you are on RaspPi / embedded, but likely you are not.)
5) I use PyTorch on my Radeon VII, and I am very happy with it. I have not hit anything provided by PyTorch itself that has not worked. Some more "exotic" functions provided through third party libraries might not be supported out of the box yet (for example, I didn't compile MAGMA, so I don't have SVD yet). Again, I am using PyTorch on ROCm for my day-to-day work and that is very smooth and covers everything I need, but you could look through the `tests/` and draw your own conclusions or something.

(None of the opinions here are anyone's except my own.)

**Comment by yngtodd** [comment]
Thanks, @t-vi, I appreciate your input. I have been running Pytorch with the Radeon VII in my workstation, and it really has been smooth. 

I am curious about testing how much the Python overhead affects our applications. I work on the supercomputers at Oak Ridge National Lab, and, while 10% overhead may not be too bad for a single workstation, things quickly get expensive on Summit. That machine consumes a lot of energy, and every bit of cost savings is important. 

Summit uses NVIDIA GPUs, of course, and I am currently looking into how libtorch may help reduce our computational costs there. At the same time, we are already looking forward to our next supercomputer, Frontier, which will be a Cray/AMD machine. I'd like for us to hit the ground running by the time that machine comes around. And, broadly speaking, I am a fan of Pytorch and would like to contribute to its place in HPC.

**Comment by t-vi** [comment]
It'll be interesting to see some serious benchmarking of PyTorch / JITed PyTorch / LibTorch in that type of setup. :) I'm usually just doing some ad-hoc benchmarking on my local machine.

**Comment by yngtodd** [comment]
Yeah, I am very interested in that too. That is probably worth another thread, but I am curious what sort of speeds we get if we first JIT a model and then train it with the libtorch interface.

**Comment by rchavezj** [comment]
I'm using [tch-rs](https://github.com/LaurentMazare/tch-rs) which is a rust library binding Libtorch. The Rust works on my NVIDIA laptop but not on an AMD GPU. Will the shell script from the [article](http://lernapparat.de/pytorch-rocm/) by referenced by @t-vi help?
