### ISSUE TITLE
project c10_intrusive_ptr_benchmark link error

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/pytorch#31315]
## To Reproduce

Windows Build link fail
https://github.com/google/benchmark/blob/505be96ab23056580a3a2315abba048f4428b04e/src/benchmark.cc#L102
error message
LNK2005 "int FLAGS_v" (? FLAGS_v @@ 3HA) is already defined in c10.lib (Logging.obj). c10_intrusive_ptr_benchmark D: \ repo \ pytorch \ build \ c10 \ benchmark \ benchmark.lib (benchmark.obj) 1

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 409151e1bb90c66546901d372f59930f72242ee9
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): build
 - Build command you used (if compiling from source): scripts/build_windows.bat
 - Python version:
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 2080Ti
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @peterjc123

**Comment by peterjc123** [comment]
Is this a naming conflict?

**Comment by kerry-Cho** [comment]
Yes

**Comment by ezyang** [comment]
This is probably because c10 contains a tiny gflags polyfill that you're not supposed to use if you're actually linking against gflags. I'm not too sure about how to fix it though.

**Comment by peterjc123** [comment]
Hit this error when trying to build static binaries with the debug configurations. I think there're several options to resolve that:
1. Add `/FORCE:MULTIPLE` to the linker options, but this is somehow dangerous.
2. Use glog when building C10 so that there will be only one copy of the symbol.
3. Don't build test binaries `set BUILD_TEST=0`.

**Comment by vladimir-aubrecht** [comment]
Could not reproduce with latest stack. Closing as it seems stale, feel free to open new issue if problem persists.
