### ISSUE TITLE
Build from source, and miss file `caffe2/caffe2/contrib/aten/gen_aten_op.h`

### ISSUE THREAD

**Issue by nan0755** [pytorch/pytorch#31354]
## To Reproduce

I follow the build from source procedure, and found this ERROR:
`python setup.py build develop` 

```
In file included from ../caffe2/contrib/aten/aten_op.cc:1:0:
../caffe2/contrib/aten/aten_op.h:1:52: fatal error: caffe2/caffe2/contrib/aten/gen_aten_op.h: No such file or directory
```

## Environment

 - PyTorch Version (e.g., 1.0): 
 - OS (e.g., Linux): Ubuntu 16.0
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py build develop` 
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1 
 - GPU models and configuration: 1080Ti
 - Any other relevant information:

**Comment by nan0755** [comment]
I found the solution:
`set USE_NINJA=OFF`
before build
`python setup.py build`

**Comment by nan0755** [comment]
I found the solution: `USE_NINJA=OFF`
But don't know where to set it.

**Comment by kerry-Cho** [comment]
export USE_NINJA=OFF

**Comment by nan0755** [comment]
@kerry-Cho 
Thanks!
