### ISSUE TITLE
Require GPU based dataloader.

### ISSUE THREAD

**Issue by WhatAShot** [pytorch/pytorch#31359]
In my opinion, the pytorch needs faster data loader via GPU, like [this project](https://github.com/tanglang96/DataLoaders_DALI). Please consider this feature. Thank you!

cc @SsnL

**Comment by SsnL** [comment]
You can already directly load data onto GPU.

**Comment by pbelevich** [comment]
Should we support NVIDIA DALI in pytorch?

**Comment by WhatAShot** [comment]
Sorry, I didn't make it clear. I meant something like 
```
imagenet_data = torchvision.datasets.ImageNet('path/to/imagenet_root/')
data_loader = torch.utils.data.DataLoader(imagenet_data,
                                          GPU_data = True,
                                          batch_size=4,
                                          shuffle=True,
                                          num_workers=args.nThreads,)
```

**Comment by ptrblck** [comment]
@pbelevich DALI is usable in PyTorch already.
Adding @JanuszL from NVIDIA for comments.

**Comment by JanuszL** [comment]
@ptrblck - the project mentioned here is a prebaked DALI pipeline for CIFAR data set.
@WhatAShot - what you exactly expects to happen when you call:
```
imagenet_data = torchvision.datasets.ImageNet('path/to/imagenet_root/')
data_loader = torch.utils.data.DataLoader(imagenet_data,
                                          GPU_data = True,
                                          batch_size=4,
                                          shuffle=True,
                                          num_workers=args.nThreads,)
```
beyond what DALI does now?

**Comment by WhatAShot** [comment]
@JanuszL Thanks. DALI did it. But maybe an API can be merged into DataLoader (or other operations), which makes this DALI based operation more popular and easier.

**Comment by JanuszL** [comment]
Merging DALI into DataLoader is definitely a broader discussion, as DALI has different API comparing to DataLoader. Also, DALI is meant to provide similar experiences across the different frameworks so bending internal behavior toward specific FW is rather not the way we see it. Still, providing familiar Python API is definitely the thing that can be worked out.
The one reservation I have it that you can get different results between CPU (current DataLoader) and GPU based pipeline (DALI). In DALI we compare CPU and GPU implementations (as DALI provides many operators for the CPU as well). But we are not comparing that much against PIL or anything else.

**Comment by WhatAShot** [comment]
Thank you~ @JanuszL
