### ISSUE TITLE
ICE on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#31418]
## 🐛 Bug

Error text:
```
    [1054/2736] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\ExpandUtils.cpp.obj
    FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/ExpandUtils.cpp.obj
    C:\w\1\s\windows\tmp_bin\sccache.exe  cl  /nologo /TP -DAT_PARALLEL_OPENMP=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DMAGMA_V2 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_OPENMP_NOFORCE_MANIFEST -Dtorch_cpu_EXPORTS -Iaten\src -I..\aten\src -I. -I..\ -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\third_party\foxi -Ithird_party\foxi -I..\caffe2\..\torch\csrc\api -I..\caffe2\..\torch\csrc\api\include -I..\caffe2\aten\src\TH -Icaffe2\aten\src\TH -I..\caffe2\..\torch\..\aten\src -Icaffe2\aten\src -Icaffe2\..\aten\src -Icaffe2\..\aten\src\ATen -I..\caffe2\..\torch\csrc -I..\caffe2\..\torch\..\third_party\miniz-2.0.8 -I..\aten\src\TH -I..\aten\..\third_party\catch\single_include -I..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\third_party\miniz-2.0.8 -I..\caffe2\core\nomnigraph\include -I..\c10\.. -I..\third_party\cpuinfo\include -I..\third_party\FP16\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -IC:\w\1\s\windows\mkl\include -I..\cmake\..\third_party\eigen -IC:\w\1\s\windows\conda\envs\py37\include -IC:\w\1\s\windows\conda\envs\py37\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include -I\opt\rocm\hip\include -I\include -I..\cmake\..\third_party\cub -IC:\w\1\s\windows\magma_cuda101_release\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I..\caffe2 /DWIN32 /D_WINDOWS  /GR  /w /EHa /MP /bigobj -openmp -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MD /O2 /Ob2  /w /EHa /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -std:c++14 /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\ExpandUtils.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c ..\aten\src\ATen\ExpandUtils.cpp
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(302): error C2061: syntax error: identifier 'IValue'
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(302): error C2238: unexpected token(s) preceding ';'
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(306): error C2988: unrecognizable template declaration/definition
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(306): error C2059: syntax error: 'return'
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(306): error C2653: 'Tag': is not a class or namespace name
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(306): error C2238: unexpected token(s) preceding ';'
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(307): error C2146: syntax error: missing ';' before identifier 'toGenericDict'
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(307): error C2270: 'toGenericDict': modifiers not allowed on nonmember functions
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): error C2653: 'Tag': is not a class or namespace name
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): error C2065: 'None': undeclared identifier
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): error C2614: 'c10::IValue': illegal member initialization: 'payload' is not a base or member
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): error C2614: 'c10::IValue': illegal member initialization: 'tag' is not a base or member
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): error C2614: 'c10::IValue': illegal member initialization: 'is_intrusive_ptr' is not a base or member
    C:\w\1\s\windows\pytorch\aten\src\ATen/core/ivalue.h(63): fatal error C1903: unable to recover from previous error(s); stopping compilation
    Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
    INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe'
        Please choose the Technical Support command on the Visual C++
        Help menu, or open the Technical Support help file for more information
```

## To Reproduce

1. python setup.py install

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 3c8892aa0cd80e62f01b1ba3c99e4f5fd713868c
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): source
 - Python version: 3.5/3.6/3.7
 - CUDA/cuDNN version: Node / 9.2 / 10.1
 - GPU models and configuration: None
 - Any other relevant information:

## Additional context

cc @peterjc123

**Comment by peterjc123** [comment]
cc @ezyang

**Comment by peterjc123** [comment]
This is caused by some commit between 52b8a52e4dfcbc074be9c743bde2a8f86aa3c0e1 and c05538b8314d2413a2b294fa71ff22768599d666.

**Comment by peterjc123** [comment]
Bisecting shows that https://github.com/pytorch/pytorch/commit/f0243ea7129cea3b6e1042057503a4da15fadec2 is the cause, which only happens for MSVC 14.11.

**Comment by peterjc123** [comment]
Okay, looks like this doesn't work in MSVC 14.16 too. So actually using VS 2017 is not feasible. Can we revert it for now? Otherwise, the CUDA 9.x builds will totally be broken. cc @ezyang

**Comment by AshutoshUpadhya** [comment]
I am facing same issue for same environment properties. Any update?

**Comment by peterjc123** [comment]
@AshutoshUpadhya As a user, you can do `git revert f0243ea` and then rebuild the project.

**Comment by AshutoshUpadhya** [comment]
m still getttiing after after reverting to previous checkpoint. 
Error : 
cmake --build . --target install --config Release -- -j 4
[1/1571] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\core\DeprecatedTypeProperties.cpp.obj
FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/core/DeprecatedTypeProperties.cpp.obj
C:\PROGRA~2\MICROS~1\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DAT_PARALLEL_OPENMP=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -Dtorch_cpu_EXPORTS -Iaten\src -I..\..\aten\src -I. -I..\..\ -I..\..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\..\third_party\onnx -Ithird_party\onnx -I..\..\third_party\foxi -Ithird_party\foxi -I..\..\caffe2\..\torch\csrc\api -I..\..\caffe2\..\torch\csrc\api\include -I..\..\caffe2\aten\src\TH -Icaffe2\aten\src\TH -I..\..\caffe2\..\torch\..\aten\src -Icaffe2\aten\src -Icaffe2\..\aten\src -Icaffe2\..\aten\src\ATen -I..\..\caffe2\..\torch\csrc -I..\..\caffe2\..\torch\..\third_party\miniz-2.0.8 -I..\..\aten\src\TH -I..\..\aten\..\third_party\catch\single_include -I..\..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\..\third_party\miniz-2.0.8 -I..\..\caffe2\core\nomnigraph\include -I..\..\c10\.. -I..\..\third_party\cpuinfo\include -I..\..\third_party\FP16\include -I..\..\cmake\..\third_party\googletest\googlemock\include -I..\..\cmake\..\third_party\googletest\googletest\include -I..\..\third_party\protobuf\src -I..\..\cmake\..\third_party\eigen -I..\..\cmake\..\third_party\pybind11\include -I\opt\rocm\hip\include -I\include -I..\..\cmake\..\third_party\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -I..\..\caffe2 /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MD /O2 /Ob2  /w /EHa /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -std:c++14 /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\core\DeprecatedTypeProperties.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c ..\..\aten\src\ATen\core\DeprecatedTypeProperties.cpp
c:\users\ashutoshkumar\ashutosh\pytorch\aten\src\aten\core\boxing\KernelFunction_impl.h(66): error C2672: 'c10::impl::boxAndCallBoxedFunc': no matching overloaded function found
C:\Users\ashutoshkumar\ashutosh\pytorch\aten\src\ATen/core/dispatch/Dispatcher.h(179): note: see reference to function template instantiation 'Return c10::KernelFunction::callUnboxed<Return,const at::Tensor&,const at::Tensor&,bool,bool>(const c10::OperatorHandle &,const at::Tensor &,const at::Tensor &,bool,bool) const' being compiled
        with
        [
            Return=void
        ]

**Comment by AshutoshUpadhya** [comment]
can you pls have a look @peterjc123

**Comment by peterjc123** [comment]
@AshutoshUpadhya Your problem is a duplicate of https://github.com/pytorch/pytorch/issues/30886. We are actively looking into it but doesn't have an easy workground. At present, you can only update to VS2019 to resolve this build error.

**Comment by peterjc123** [comment]
cc @smessmer Maybe we should revert the PR first. Then we can back it out when we finish the update to VS 2019 in all the related parts. (e.g. Nightly machines, Release machines and CI)
