### ISSUE TITLE
can't close torch.utils.tensorboard.SummaryWriter in __del__

### ISSUE THREAD

**Issue by ponzioPJ** [pytorch/pytorch#31410]
The program can not exit (print 'closed') when I try to close the `SummaryWriter` in `__del__()`.
```
from torch.utils.tensorboard import SummaryWriter


class Test:
    def __init__(self):
        self.tblog = SummaryWriter('exp/tb/exit_test')
        # self.tblog.close()

    def __del__(self):
        self.tblog.close()
        print('closed')


if __name__ == '__main__':
    tblog = Test()
```
The program can exit if the `close()` is not in `__del__()`.

Python 3.7.5

Pytorch 1.3.1

tensorboard 2.0.0

OS: Ubuntu and Win10

**Comment by albanD** [comment]
Hi,

The `__del__` function has many caveats in python. In particular there are not that many guarantees that it will always be called.
If you want to ensure this is called, you should use a `try:` `finally:` statement.

Also we use github issues only for bug reports, please use the forum for further questions: https://discuss.pytorch.org/
