### ISSUE TITLE
Different return type for MNIST and CIFAR10 datasets

### ISSUE THREAD

**Issue by harshitagrawal294** [pytorch/pytorch#31417]
## To Reproduce

1.Run the given code sample

train=datasets.MNIST(root='/dataset/', train=True, download=True,transform=transform)
print(type(train.data))

train=datasets.CIFAR10(root='/dataset/', train=True, download=True,transform=transform)
print(type(train.data))

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Enealor** [comment]
I'm having trouble understanding the issue, and I can't reproduce the issue as I don't have enough context. In particular, what is `transform` in this case? What output are you getting, and what differences are you are noticing? Both return `<class 'torch.Tensor'>` for me when the default argument is used.

The two datasets contain different data, and so minor differences are to be expected. e.g. MNIST has images of shape 1x28x28, while CIFAR has color images of shape 3x32x32.

**Comment by albanD** [comment]
We use the github issue tracker only for bugs and features. Please use the forum: https://discuss.pytorch.org/ to ask questions.
