### ISSUE TITLE
On pytorch mobile (android), module forward returns org.pytorch.IValue type. But on my detection module, supposes to return a tuple IValue.

### ISSUE THREAD

**Issue by Sakulaki** [pytorch/pytorch#31415]
## 🐛 Bug

The original code in pytorch mobile demo:
final Tensor outputTensor = mModule.forward(IValue.from(mInputTensor)).toTensor();

my code:
final IValue[] outputTensor = mModule.forward(IValue.from(mInputTensor));
or
final Tensor[] outputTensor = mModule.forward(IValue.from(mInputTensor)).toTensor();

I need to separate the tuple output first and analysis.

## Environment
org.pytorch:pytorch_android:1.3.0

**Comment by IvanKobzarev** [comment]
Hello @Sakulaki ,

IValue works as a 'tagged union' for all supported types, extracting them calling  appropriate for your type `IValue${TYPE}` method.
So for the case of tuple it should be used smth like this:
```
    final IValue output = mModule.forward(IValue.from(mInputTensor));
    IValue[] outputTuple = output.toTuple();
    for (int i = 0; i < outputTuple.length; i++) {
      IValue tupleElement = outputTuple[i];
    }
```

**Comment by Sakulaki** [comment]
Hi @IvanKobzarev ,

Thanks for your reply, it works, nice!
