### ISSUE TITLE
Pytorch C++ API only works with -O0 optimization

### ISSUE THREAD

**Issue by seeker-Liu** [pytorch/pytorch#31411]
## 🐛 Bug

My program is suffering from a weird bug. It works well with -O0 optimization but crashes with any higher optimization level (-O, -O2 and -O3).

## To Reproduce

My program load the program with the following code
```
    torch::jit::script::Module module;
    try
    {
        // Deserialize the ScriptModule from a file using torch::jit::load().
        module = torch::jit::load("../c_model.th");
    }
    catch (const c10::Error& e)
    {
        std::cerr << "error loading the model\n";
        return -1;
    }
```

Then pass it by reference to another function, and work about it with the following code

```
    torch::IntArrayRef size{1,1,64,256};
    at::TensorOptions options(torch::kFloat32);
    auto tensor = torch::empty(size, options);
    //Sadly we have to write the loop to set the value by ourselves.
    auto accessor = tensor.accessor<float, 4>();
    for(size_t i = 0; const auto &frame : mag)
    {
        for(size_t j = 0; const auto mag_entry : frame)
        {
            accessor[0][0][i][j] = mag_entry;
            j++;
        }
        i++;
    }

    auto result = module.forward({tensor}).toTensor();
    auto result_accessor = result.accessor<float, 2>();
    float x = result_accessor[0][0];
    float y = result_accessor[0][1];
```

However program crashes with the following info printed to console in -O1 or higher optimization level.

```
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at CPUAllocator.cpp:47] ((ptrdiff_t)nbytes) >= 0. alloc_cpu() seems to have been called with negative number: 10177264015417475072
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x6a (0x7ff247458fea in /home/liu/software/pytorch/torch/lib/libc10.so)
frame #1: c10::alloc_cpu(unsigned long) + 0x4f0 (0x7ff2474403f0 in /home/liu/software/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x179ea (0x7ff2474419ea in /home/liu/software/pytorch/torch/lib/libc10.so)
frame #3: at::native::empty_cpu(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) + 0x10b (0x7ff2483c174b in /home/liu/software/pytorch/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x11c0ba0 (0x7ff248632ba0 in /home/liu/software/pytorch/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x11c9dd7 (0x7ff24863bdd7 in /home/liu/software/pytorch/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x16a31 (0x5648e8b7da31 in /home/liu/work/PyTorchCppTest/cmake-build-debug/PyTorchCppTest)
frame #7: <unknown function> + 0x851e (0x5648e8b6f51e in /home/liu/work/PyTorchCppTest/cmake-build-debug/PyTorchCppTest)
frame #8: <unknown function> + 0xa473 (0x5648e8b71473 in /home/liu/work/PyTorchCppTest/cmake-build-debug/PyTorchCppTest)
frame #9: __libc_start_main + 0xeb (0x7ff245714b6b in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: <unknown function> + 0x79aa (0x5648e8b6e9aa in /home/liu/work/PyTorchCppTest/cmake-build-debug/PyTorchCppTest)
```

I used the debugger to trace down the control flow, it looks like program crashes in ```torch::empty``` function.

## Expected behavior

Run correctly in higher optimization level.

## Environment

PyTorch version: 1.4.0a0+18ec463
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 19.04
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torchsummary==1.5.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] torch                     1.4.0a0+18ec463          pypi_0    pypi
## Additional context

cc @ezyang @gchanan @zou3519 @yf225

**Comment by seeker-Liu** [comment]
Note: The module is pre-trained in Python.

**Comment by gchanan** [comment]
is it possible for you to share the model?

**Comment by seeker-Liu** [comment]
It is not my model so I'm afraid I must ask for permission, could you give me your e-mail address?
@gchanan

**Comment by yf225** [comment]
@seeker-Liu Please feel free to send it to willfeng@fb.com and I will debug it.

**Comment by ezyang** [comment]
```
torch::IntArrayRef size{1,1,64,256};
```

This isn't valid. It will create a reference to the temporary initializer list `{1, 1, 64, 256}` which will promptly die at the end of this statement. Replace it with something like `std::array<int64_t, 4> size = {1, 1, 64, 256}` and your code will work.
