### ISSUE TITLE
Should we expose CircleCI CUDA10 tests as XImportant and run on PRs?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31427]
This comes when working on https://github.com/pytorch/pytorch/pull/30898

**Long story short:**
`torch.addmv` for `torch.half` has a different code path from other dtypes. Due to an issue on CUDA9 on old hardware (https://github.com/pytorch/pytorch/issues/31006) I have to disable the zero-sized tensor test for `torch.addmv` + `torch.half` on CUDA9. This means this specific code path is not covered by any test in our CI for PR. The skipped test is:
```python
@skipCUDAIfRocm
@dtypesIfCUDA(*(torch.float, torch.double) +
              # This test is disabled on CUDA 9, due to:
              # See: https://github.com/pytorch/pytorch/issues/31006
              ((torch.half,) if torch.version.cuda and float(torch.version.cuda) >= 10.0 else ()))
@dtypes(*(set(torch.testing.get_all_dtypes()) - {torch.half, torch.bool}))
def test_blas_alpha_beta_empty(self, device, dtype):
```

This case seems to be a very edge case. I don't know if it worth to enable CUDA 10 test on PRs, or just switch from CUDA 9 to CUDA 10 test on PRs.

cc: @ngimel @ezyang 
cc: @VitalyFedyunin 

cc @ezyang @ngimel

**Comment by ngimel** [comment]
I vote for running cuda 10 instead of cuda 9 on PRs unless we have serious issues blocking this.

**Comment by ezyang** [comment]
Yeah, let's just swap the XImportant designation. @zasdfgbnm do you think you can do this?

**Comment by VitalyFedyunin** [comment]
If possible I really want to have one of out rests running CUDA9 with older version of CudNN as it might reveal different issues (like CudNN not really friendly to non-contiguous formats with some shapes).

**Comment by ezyang** [comment]
The suggestion in this issue is to change which tests run on all PRs, but not change the overall set of tests we run on all master commits

**Comment by zasdfgbnm** [comment]
@ezyang I can do the work if we decide to do so.

**Comment by ezyang** [comment]
Let's do it!
