### ISSUE TITLE
sparse cuda inplace multiplication seems to give incorrect results

### ISSUE THREAD

**Issue by nairbv** [pytorch/pytorch#31449]
## 🐛 Bug

Incorrect results on master for sparse in-place multiplication on cuda.

## To Reproduce
```
import torch
a=torch.randint(-5, 10, [5, 5], device='cuda')
b=torch.randint(-5, 10, [5, 5], device='cuda')
a_s=a.to_sparse()
b_s=b.to_sparse()
a.mul_(b)
a_s.mul_(b_s)
print( "success" if torch.allclose(a, a_s.to_dense()) else "fail")
```
## Expected behavior

example code prints "success", sparse op gives the same result as the dense op.

## Environment

I'm on a recent checkout of master. I think this is recently introduced, I was using mul_ in a PR with all my tests passing, and then started seeing test failures after rebasing master.

Blocks landing of https://github.com/pytorch/pytorch/pull/30429

cc @ezyang @gchanan @zou3519 @ngimel @vincentqb @VitalyFedyunin

**Comment by nairbv** [comment]
Not failing when I checkout:

commit 0414463007cecbc987ec376e95639073d26d7d2d (HEAD)
Author: nikitaved <nikitavedeneev@gmail.com>
Date:   Wed Dec 11 15:59:45 2019 -0800

**Comment by nairbv** [comment]
test script passes if we change `nz.clone()` call in dense_to_sparse in SparseTensor.cpp to use MemoryFormat::Contiguous, implying this is a failure caused by non-contiguous indices introduced through the to_sparse() call in the test script.

An alternate test script that manually causes indices to be non-contiguous still passes after making the dense_to_sparse fix described above though:

```
import torch

a=torch.randint(-5, 10, [5, 5], device='cuda')
b=torch.randint(-5, 10, [5, 5], device='cuda')

a_s=a.to_sparse()
i = a_s._indices()
i=i.transpose(0, 1)
i=i.contiguous()
i=i.transpose(0, 1)
print(i.is_contiguous())
a_s=torch.sparse_coo_tensor(indices=i, values=a_s._values())

b_s=b.to_sparse()
i = b_s._indices()
i=i.transpose(0,1)
i=i.contiguous()
i=i.transpose(0,1)

print(i.is_contiguous())
b_s=torch.sparse_coo_tensor(indices=i, values=b_s._values())

a.mul_(b)
a_s.mul_(b_s)
print( "success" if torch.allclose(a, a_s.to_dense()) else "fail")
```

**Comment by cpuhrsch** [comment]
cc @VitalyFedyunin  as of fix PR that seems to be landed already
