### ISSUE TITLE
Consolidate worthRecopying logic across multiple backends

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#31447]
As mentioned in https://github.com/pytorch/pytorch/pull/31357#pullrequestreview-334318146, we should consolidate this piece of code in a separate reusable function so that multiple backends can easily use it.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528

**Comment by pietern** [comment]
In the hypothetical case that you're sending multiple views into the same storage, it can be better to encode the underlying storage just once and keep the views into that storage. This implies doing some kind of 2 pass pickling where first you see if a storage is used multiple times, and compute some kind of "occupancy" of the storage. Then that would inform if it should be transferred as a whole, or if the views should get their own (smaller) storages.
