### ISSUE TITLE
ImportError libshm.so 

### ISSUE THREAD

**Issue by duxiaoyang06** [pytorch/pytorch#3145]
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: libshm.so: cannot open shared object file: No such file or directory
>>> 
env:ubuntu 16.04,python2.7
So,what should I do?

**Comment by zou3519** [comment]
How did you install pytorch?

**Comment by duxiaoyang06** [comment]
wget http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl 
and then
pip install torch-0.2.0.post3-cp27-cp27mu-manylinux1_x86_64.whl 
Should I change another version whl?

**Comment by duxiaoyang06** [comment]
I fixed it by using http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl

**Comment by mruberry** [comment]
Looks like the issues was addressed.
