### ISSUE TITLE
torch.gather in pytorch.onnx and onnxruntime

### ISSUE THREAD

**Issue by xubin1994** [pytorch/pytorch#31464]
I have a model that uses torch.gather () API ,and the model runs well in pytorch.
```python
warped_right_feature_map_a = torch.gather(right_input,dim=3, index=right_y_coordinate_a.long())
```
 I successfully converted the model to an onnx file using torch.onnx.export () API, and the checkmodel is also verified,
```python
import onnx
onnx_model = onnx.load("IresNet-1.onnx")
onnx.checker.check_model(onnx_model)
```
 but when I run the onnx file using onnxruntime, the program crashes and without report message. If I comment out "torch.gather"" API, the program can run normally, In the torch.onnx doc，the "torch.gather" API is supported.So what is the problem?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by albanD** [comment]
Is the problem with the onnx runtime or pytorch? It seem that it is the onnx runtime no? Maybe you want to open an issue on their repo?

**Comment by xubin1994** [comment]
> Is the problem with the onnx runtime or pytorch? It seem that it is the onnx runtime no? Maybe you want to open an issue on their repo?

OK,I will open an issue on their repo to get a solution.

**Comment by albanD** [comment]
Closing this as a dependency issue for now. Please re-open if they say it comes from pytorch !

**Comment by xubin1994** [comment]
> Closing this as a dependency issue for now. Please re-open if they say it comes from pytorch !

Hi,Hello, I talked with onnxruntime and found that the problem may still come from torch.gather OP.
https://github.com/microsoft/onnxruntime/issues/2699
```python
torch.onnx.export(learn.model,               # model being run
                  (left,right),                         # model input (or a tuple for multiple inputs)
                  "Test.onnx",   # where to save the model (can be a file or file-like object)
                  verbose = True,
                  export_params=True,        # store the trained parameter weights inside the model file
                  input_names = ['input1','input2'],   # the model's input names
                  output_names = ['output1'], # the model's output names
                    )
```
With the "verbose = True", torch.gather(right_input,dim=3, index=right_y_coordinate_a.long()) Corresponding to the onnx code below,
```python
  %521 : Tensor = onnx::Gather[axis=0](%520, %519), scope: Pytorch_IresNet/DRS_net[DRS_net]/SpatialTransformer
  %522 : Tensor = onnx::OneHot[axis=3](%517, %521, %518), scope: Pytorch_IresNet/DRS_net[DRS_net]/SpatialTransformer
```
This is also the prbblem mentioned by onnxruntime(https://github.com/microsoft/onnxruntime/issues/2699)。
It is confusing because I don't use OneHot OP，could you please help me analyze this problem?

**Comment by albanD** [comment]
Hi, Could you share the code that corresponds to the op in the image shared in the issue on onnxr (LeakyRelu, Gather, Clip, Cast)?

**Comment by xubin1994** [comment]
> Hi, Could you share the code that corresponds to the op in the image shared in the issue on onnxr (LeakyRelu, Gather, Clip, Cast)?
Hi,here is the relevant code.
```python
class SpatialTransformer(nn.Module):
    def __init__(self):
        super(SpatialTransformer, self).__init__()

    def forward(self, right_input, disparity_samples):
        """
        Args:
            :right_input: Right Image Features,with shape [B,C,H,W],in the Inference mode:the real shape is [1,32,704,1280]
            :disparity_samples:  Disparity,with shape [B,C,H,W],in the Inference mode:the real shape is [1,1,704,1280]
        Returns:
            :warped_right_feature_map: right image features warped according to input disparity.,
            with shape [B,C,H,W],in the Inference mode:the real shape is [1,32,704,1280]
        """
        device = right_input.get_device()
        # B, C, H, W = right_input.shape
		#[H,W]
        left_y_coordinate = torch.arange(0.0, 1280).repeat(704)
        #[H,W]
        left_y_coordinate = left_y_coordinate.view(704, 1280)

        left_y_coordinate = torch.clamp(left_y_coordinate, min=0, max= 1280 - 1)
        #[B,H,W]
        # left_y_coordinate = left_y_coordinate.expand(1, -1, -1)
        # left_y_coordinate = left_y_coordinate.expand(1,  -1,  -1, -1)
        #[B,H,W]
        left_y_coordinate = left_y_coordinate.unsqueeze(0)
        #[B,C,H,W]
        left_y_coordinate = left_y_coordinate.unsqueeze(0)
        

        right_y_coordinate = left_y_coordinate + disparity_samples

	
		#[B,C,H,W]
        right_y_coordinate_a = torch.floor(right_y_coordinate)
        right_y_coordinate_b = right_y_coordinate_a + 1
		
        wa = right_y_coordinate_b - right_y_coordinate
        wb = right_y_coordinate   - right_y_coordinate_a

        wa = wa.repeat(1, 32, 1, 1)
        wb = wb.repeat(1, 32, 1, 1)

        right_y_coordinate_a = right_y_coordinate_a.repeat(1, 32, 1, 1).long()
        right_y_coordinate_b = right_y_coordinate_b.repeat(1, 32, 1, 1).long()
        #[B,C,H,W]
        right_y_coordinate_a = torch.clamp(right_y_coordinate_a.float(), min=0, max= 1280 - 1)
        right_y_coordinate_b = torch.clamp(right_y_coordinate_b.float(), min=0, max= 1280 - 1)
        #test_index = torch.zeros_like(right_input)


        warped_right_feature_map_a = torch.gather(right_input, dim=3, index=right_y_coordinate_a.long())
        warped_right_feature_map_b = torch.gather(right_input, dim=3, index=right_y_coordinate_b.long())	
		
        warped_right_feature_map = wa * warped_right_feature_map_a + wb * warped_right_feature_map_b

        # #right_y_coordinate_1 = right_y_coordinate_1.expand(right_input.size()[1], -1, -1, -1).permute([1, 0, 2, 3]))
        right_y_coordinate_1 = right_y_coordinate.repeat(1, 32, 1, 1)
        warped_right_feature_map = (1.0 - ((right_y_coordinate_1 < 0).float() +
                                   (right_y_coordinate_1 > torch.tensor([1280 - 1], dtype=torch.float32))).float()) * \
            (warped_right_feature_map) + torch.zeros_like(warped_right_feature_map)
        return warped_right_feature_map   
```
You can use random input to verify this function to determine if there is a problem with torch.gather() op when after "torch.onnx.export()".
It should be noted that, in order to convert into an onnx model, I set the input size:
right_input [1,32,704,1280]
disparity_samples:[1,1,704,1280]

**Comment by KsenijaS** [comment]
Hi,
As stated in https://github.com/microsoft/onnxruntime/issues/2699 OneHot op will run out of memory and that's why in opset 11 Gather op is optimized and it's created without OneHot operator.
Set in your torch.onnx.export function the opset version to 11 (opset_version=11) and that should resolve your issue.
If you still have problems with your model, feel free to comment and the issue will be reopened.

**Comment by spandantiwari** [comment]
Please re-open if some issue remains.

**Comment by xubin1994** [comment]
> Hi,
> As stated in [microsoft/onnxruntime#2699](https://github.com/microsoft/onnxruntime/issues/2699) OneHot op will run out of memory and that's why in opset 11 Gather op is optimized and it's created without OneHot operator.
> Set in your torch.onnx.export function the opset version to 11 (opset_version=11) and that should resolve your issue.
> If you still have problems with your model, feel free to comment and the issue will be reopened.

![image](https://user-images.githubusercontent.com/28856641/75312499-0aa24700-5895-11ea-991e-96a807c5da31.png)


> Hi,
> As stated in [microsoft/onnxruntime#2699](https://github.com/microsoft/onnxruntime/issues/2699) OneHot op will run out of memory and that's why in opset 11 Gather op is optimized and it's created without OneHot operator.
> Set in your torch.onnx.export function the opset version to 11 (opset_version=11) and that should resolve your issue.
> If you still have problems with your model, feel free to comment and the issue will be reopened.

I change the opset version to 11,  but I still got a problem with gather OP:
![image](https://user-images.githubusercontent.com/28856641/75312577-50f7a600-5895-11ea-9a21-4d83bfeb80d7.png)
Is this gather OP fully tested? Or is there anything I need to pay attention to in  usage when export to onnx?

**Comment by KsenijaS** [comment]
Can you please send info about your environment, what versions of pytorch, onnx, etc you use?

**Comment by xubin1994** [comment]
> Can you please send info about your environment, what versions of pytorch, onnx you use?

torch version is 1.3.1.
onnx version is  1.5.0.

**Comment by xubin1994** [comment]
> Can you please send info about your environment, what versions of pytorch, onnx you use?

Can you tell me what kind of environment you use for the opset version 11? I can try the same configuration as you

**Comment by KsenijaS** [comment]
I built my pythorch from master branch and it's now 1.5 and ONNX 1.6

**Comment by xubin1994** [comment]
> orch from master branch and it's now 1.5 and ONNX 1.6

I tried this environment: torch1.4 + onnx 1.6. But there are still problems. This time the problem is on the clip OP. I'm not sure if there is a problem with the gather OP. Can you help me to transform the Class SpatialTransformer to the onnx file and verify  on onnxruntime？
Here is my Class SpatialTransformer:
```python
class SpatialTransformer(nn.Module):
    def __init__(self):
        super(SpatialTransformer, self).__init__()

    def forward(self, right_input, disparity_samples):
        B, C, H, W = right_input.shape
        device = right_input.get_device()
        left_y_coordinate = torch.arange(0.0, W).repeat(H)

        left_y_coordinate = left_y_coordinate.view(H, W)

        left_y_coordinate = left_y_coordinate.unsqueeze(0)
        left_y_coordinate = left_y_coordinate.unsqueeze(0)
        

        right_y_coordinate = left_y_coordinate + disparity_samples

        right_y_coordinate_a = torch.floor(right_y_coordinate)
        right_y_coordinate_b = right_y_coordinate_a + 1
		
        wa = right_y_coordinate_b - right_y_coordinate
        wb = right_y_coordinate   - right_y_coordinate_a

        wa = wa.repeat(1, C, 1, 1)
        wb = wb.repeat(1, C, 1, 1)

        right_y_coordinate_a = right_y_coordinate_a.repeat(1, C, 1, 1).long()
        right_y_coordinate_b = right_y_coordinate_b.repeat(1, C, 1, 1).long()


        right_y_coordinate_a = torch.clamp(right_y_coordinate_a, min=0, max= W - 1)
        right_y_coordinate_b = torch.clamp(right_y_coordinate_b, min=0, max= W - 1)

        warped_right_feature_map_a = torch.ones_like(right_input)
        warped_right_feature_map_b = torch.ones_like(right_input)


        warped_right_feature_map_a = right_input.gather(dim=3, index=right_y_coordinate_a.long())
        warped_right_feature_map_b = torch.gather(right_input, dim=3, index=right_y_coordinate_b.long())	
		
        warped_right_feature_map = wa * warped_right_feature_map_a + wb * warped_right_feature_map_b

        right_y_coordinate_1 = right_y_coordinate.repeat(1, C, 1, 1)
        
        warped_right_feature_map = (1.0 - ((right_y_coordinate_1 < 0).float() +
                                   (right_y_coordinate_1 > torch.tensor([W - 1], dtype=torch.float32))).float()) * \
            (warped_right_feature_map) + torch.zeros_like(warped_right_feature_map)

        print("new stn")
        return warped_right_feature_map    
```
