### ISSUE TITLE
Better performance without OMP

### ISSUE THREAD

**Issue by loudinthecloud** [pytorch/pytorch#3146]
EDIT (@apaszke): inlined script into the issue

---

The following script was used to generate the results below:
```python
#!/usr/bin/env python
import time
import sys

import numpy as np
import torch
from torch import nn
from torch.autograd import Variable
from torch import optim
import torch.nn.functional as F


NUM_INPUTS = 100
NUM_OUTPUTS = 100
BATCH_SIZE = 4


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc = nn.Linear(NUM_INPUTS, NUM_OUTPUTS)

    def forward(self, x):
        o = self.fc(x)
        return F.sigmoid(o)

def dataloader(batch_size=BATCH_SIZE):
    while True:
        x = Variable(torch.randn(batch_size, NUM_INPUTS))
        y = Variable(torch.randn(batch_size, NUM_OUTPUTS))
        yield x, y


def getus():
    return time.time() * 1000000

def main():
    if (len(sys.argv) > 1) and (sys.argv[1] == 'single'):
        torch.set_num_threads(1)

    net = Model()
    criterion = nn.MSELoss()
    optimizer = optim.SGD(net.parameters(), lr=0.0001)

    timings = []

    for i, (x, y) in enumerate(dataloader()):
        s = getus()
        optimizer.zero_grad()
        o = net(x)
        loss = criterion(o, y)
        loss.backward()
        optimizer.step()
        e = getus()

        timings += [e - s]
        if i % 10000 == 0:
            arr = np.array(timings)
            print("Time: {:.6f} us (std: {:.6f} us)".format(arr.mean(), arr.std()))
            timings = []

if __name__ == '__main__':
    main()
```

As seen below, 4 tests + performance measurements are listed. I tried running pytorch on single core but run into some problems. The tests below are running the benchmark script with/without specifying `MKL_NUM_THREADS=1 OMP_NUM_THREADS=1` and with/without calling `torch.set_num_threads(1)`

Problems arise from these tests:
1. Running with `MKL_NUM_THREADS=1 OMP_NUM_THREADS=1` and with `torch.set_num_threads(1)` has different behavior
2. Better performance without MKL/OMP
3. Overall low CPU utilization for multi-threading
4. High CPU utilization when calling `torch.set_num_threads(1)` but performance gain is not proportional (Utilization: 22.5% -> 75%, Performance: 700us -> 435us), i.e, overhead included
5. No way to run pytorch on single thread

***

**Test 1**
Command: `./1.py`
Time: 689.201600 us (std: 188.663304 us)
CPU Utilization: 22.5%
[perf.hist.0.txt](https://github.com/pytorch/pytorch/files/1390607/perf.hist.0.txt)

**Test 2**
Command: `MKL_NUM_THREADS=1 OMP_NUM_THREADS=1 ./1.py`
Time: 541.709725 us (std: 139.295126 us)
CPU Utilization: 22.5%
[perf.hist.1.txt](https://github.com/pytorch/pytorch/files/1390608/perf.hist.1.txt)

**Test 3**
Command: `./1.py single`
Time: 435.998200 us (std: 192.966656 us)
CPU Utilization: 75%
[perf.hist.2.txt](https://github.com/pytorch/pytorch/files/1390609/perf.hist.2.txt)

**Test 4**
Command: `MKL_NUM_THREADS=1 OMP_NUM_THREADS=1 ./1.py single`
Time: 511.281300 us (std: 66.547017 us)
Utilization: 24%
[perf.hist.3.txt](https://github.com/pytorch/pytorch/files/1390610/perf.hist.3.txt)

cc @VitalyFedyunin @ngimel @mruberry

**Comment by loudinthecloud** [comment]
To run on a single core `OMP_NUM_THREADS=1` indeed creates a single thread but it is migrated between the cores too often for some reason. If setting the affinity to a single core, the best performance is achieved.

`OMP_NUM_THREADS=1 taskset -c 0 ./1.py`
Time: 314.611275 us (std: 29.617539 us)

**Comment by loudinthecloud** [comment]
I just made sure that the single core test is better not because of Turbo Boost.

I executed the script as a separate workload on each of the cores:

> GOMP_CPU_AFFINITY="0" OMP_NUM_THREADS=1 ./1.py
> GOMP_CPU_AFFINITY="1" OMP_NUM_THREADS=1 ./1.py
> GOMP_CPU_AFFINITY="2" OMP_NUM_THREADS=1 ./1.py
> GOMP_CPU_AFFINITY="3" OMP_NUM_THREADS=1 ./1.py

And the result was slightly worse than single workload on single core:
`Time: 336.240175 us (std: 134.900685 us)`

Note that the variance did increase, this may be purely attributed to the CPU as each workload is running in a single thread pinned to a different cpu.

**Comment by Stonesjtu** [comment]
@loudinthecloud could you plz add the command of generating the `perf.hist.1.txt`.

**Comment by Stonesjtu** [comment]
I think the problem set is too tiny for CPU, and the OMP overhead dominates the execution time. Actually, I have increased the `NUM_INPUTS` and `NUM_OUTPUTS` to *1000*, and set the `batch_size` to *40*, then significant speedup is achieved.

**Comment by loudinthecloud** [comment]
@Stonesjtu, the perf file was generated by dumping the histogram using the `sudo perf top` command.

When increasing the batch size or the number of parameters, does the performance increase with the number of cores?

**Comment by wohlbier** [comment]
@mingfeima I am seeing twice as many processes as threads in htop, and I gather it is because of the issue you mention regarding two different OpenMP thread pools. You said that you were close to solving this in May 2018. Have you solved it? Thanks!

**Comment by mingfeima** [comment]
@wohlbier we have finished the coding but the PR was not accepted.
Anyway, the performance issue triggered by dual OpenMP thread pool can be greatly alleviated by regulating KMP environment variables, a.k.a. `OMP_NUM_THREADS` and `KMP_AFFINITY`, etc.
This is an [example](https://github.com/mingfeima/convnet-benchmarks/blob/master/pytorch/run.sh) how you can set these environment variables.
`KMP_AFFINITY` will make sure the corresponding threads from forward and backward to be located on the very same core, avoiding unnecessary cache swapping.

**Comment by soumith** [comment]
@mingfeima which PR are you referring to?

**Comment by wohlbier** [comment]
@mingfeima Thanks very much for the information. I used your example with a small tweak. I wanted to test it with different numbers of threads and cores less than are in a socket to do a scaling study. I ended up with this:
```
          OMP_NUM_THREADS=${NTHREADS} \
          KMP_HW_SUBSET=1s,${NTHREADS}c,2t \
          KMP_AFFINITY=granularity=fine,compact,1,0 \
```
Using that I was able to get forward and backward on two threads of the same core for a number of threads less than there are cores on the socket.

I experimented for some time trying to accomplish the same thing using `OMP_PLACES` and `OMP_PROC_BIND` but did not have success.

**Comment by vpirogov** [comment]
cc @gujinghui, @XiaobingSuper, @PenghuiCheng

**Comment by choidongyeon** [comment]
Is this issue still relevant?

@mingfeima, you mentioned that you opened a PR. Can you point me to this PR?

**Comment by mingfeima** [comment]
@choidongyeon the discussion here is out dated. 
Anyway, for better CPU performance, please regulate environment variables like **OMP_NUM_THREADS** etc, you can find an example of settings [here](https://github.com/mingfeima/op_bench-py/blob/master/run.sh).

**Comment by mruberry** [comment]
Closing due to age. Please file a new issue with a recent version of PyTorch if there's still an improvement to be made.
