### ISSUE TITLE
Crash when building pytorch from sources with CUDA: ld: cannot find -lcuda

### ISSUE THREAD

**Issue by cjsg** [pytorch/pytorch#3147]
When building pytorch from sources with cuda support (for cuda-8.0 and cudnn-6.0), it crashes (relatively at the end I think) with the following message:

> /home/cjsimon/anaconda3/compiler_compat/ld: cannot find -lcuda
> collect2: error: ld returned 1 exit status
> error: command 'gcc' failed with exit status 1

I followed the steps described in the official [readme](https://github.com/pytorch/pytorch#installation), using a clean conda environment. I use the system-wide gcc (version 5.4.0) with Ubuntu 16.04.01 LTS.
Inspired by [this](https://github.com/pytorch/pytorch/issues/3050) post, I also tried first installing a new gcc with conda (leading to a gcc version 4.8.5), but then the build stops right away with the following output:

> running install
> running build_deps
> cmake: /lustre/home/cjsimon/anaconda3/envs/pytorch/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by cmake)
> cmake: /lustre/home/cjsimon/anaconda3/envs/pytorch/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
> cmake: /lustre/home/cjsimon/anaconda3/envs/pytorch/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)

(This in turn seems related to the [following](https://github.com/ContinuumIO/anaconda-issues/issues/483) issue, which essentially states that I would need a gcc version 4.9 or higher. But conda does not provide it.)
Importantly, I do not have sudo rights on that server, so installing another system-wide version of gcc is not an option.
Thanks for your help!

**Comment by apaszke** [comment]
Please post a complete build log in an environment that doesn’t have conda’s gcc, to a GitHub gist

**Comment by cjsg** [comment]
[Here](https://gist.github.com/cjsg/7ba0558e74d5d991bdc85f4ded9e4927) is the requested GitHub gist.
You'll first find my exact command lines, followed by the output of the last command (python setup.py install).
Thanks for looking into this and sorry I did not provide this in the original post.

**Comment by apaszke** [comment]
Great, that's exactly what I needed. Do you know where your CUDA libraries are? It seems that you don't have it in the default paths. Build system finds `CUDA_HOME` to be `/is/software/nvidia/cuda-8.0/`, so it assumes CUDA runtime libs are in `/is/software/nvidia/cuda-8.0/lib64`.

**Comment by cjsg** [comment]
That's exactly where my CUDA runtime libs: `/is/software/nvidia/cuda-8.0/lib64` .
Just in case it helps, I added a few `ls` commands from my CUDA directory at the end of the GitHub gist, so you can see its architecture. Apart from separating the CUDA and CUDNN libraries, this architecture seems quite in line with what the pytorch/tools/setup_files/{cuda.py,cudnn.py} expect.
So just to be sure: when you say

> It seems that you don't have it in the default paths.

you don't mean that I should add cuda-8.0/lib64 directory to my PATH environment variable, but just that this architecture with separate cuda and cudnn directories is a bit unusual, right?

**Comment by apaszke** [comment]
Huh, so I just realized that `libcuda.so` on my system isn't where all other CUDA libs are, but in `/usr/lib/x86_64-linux-gnu/`, so it's picked up by the compiler automatically. @ngimel what's a reliable way to look for `libcuda`? Is it symlinked somewhere in the toolkit dir?

**Comment by soumith** [comment]
libcuda comes with the nvidia driver. if your driver install went correctly, it should already be in ldconfig path.

**Comment by Johnqczhang** [comment]
@cjsg I met the same problem but I found it may be caused by the Anaconda, according to this [issue](http://github.com/conda/conda/issues/6030). After upgrading the Anaconda to the latest version (Anaconda2-5.0.0.1), this problem solved. You can also try downgrading your conda to the older version.

**Comment by cjsg** [comment]
Thanks to all for your help and suggestions! Special thanks to @soumith, who gave the right hint!

The reason it failed is because I was trying to build/install pytorch on the login node of a cluster. And while the cuda/cudnn binaries/libraries are accessible from there, the login node has no GPU card and thus no nvidia drivers. That is why the `ld` command would not recognize the `-lcuda` option.
So to make the installation work, I simply logged into a node with GPU, and did the installation there.

Two suggestions though:
- Maybe it would make sense to check at the beginning of the installation whether the nvidia drivers are in the ldconfig path. This would avoid spending 45 minutes to do the build just to notice around the end that the installation is bound to fail because of ld .
- even with 10GB of memory, the installation ran out of memory. I had to request 20GB to make it work. I think, it's because the installation assumes that it can use all the system's memory, whereas on clusters, users usually get allocated only a fraction of the total memory. Don't know how difficult it would be to tell the installation to use only that allocated memory (or a pre-specified maximal amount).

**Comment by zhfwyy** [comment]
I have the same problem with you ,have you solve it?
Than you very much
/home/wyy/anaconda3/compiler_compat/ld: cannot find -lm
/home/wyy/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/wyy/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
Include directories: ['/usr/local/cuda/include']
Library directories: ['/usr/local/cuda/lib64']
Cannot build a stub file.
Original error: command 'g++' failed with exit status 1
