### ISSUE TITLE
[docs] torch.histc docs mention min/max have int type

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#31475]
https://pytorch.org/docs/master/torch.html?highlight=histc#torch.histc:
```
min (int) – lower end of the range (inclusive)
max (int) – upper end of the range (inclusive)
```

I think this is erroneous, the type should be float and also to accept PyTorch scalar type (as it can be common to write `min = bins_tensor.min(), max = bins_tensor.max())`

**Comment by vadimkantorov** [comment]
Also, it's a bit strange that histc returns integer counts but as float dtype.

**Comment by ngimel** [comment]
Thank you for your bug report! Would you mind sending a PR to fix documentation? And I agree, returning counts as floats is strange.

**Comment by vadimkantorov** [comment]
I'll try to do a PR, but don't promise doing that super-fast :/ It'd be my first PR to docs.

Also I checked, min/max accept PyTorch scalars, but not sure if/how that should be formulated in docs.

**Comment by vadimkantorov** [comment]
@ngimel Should I open another issue about `histc` returning float values?
