### ISSUE TITLE
cuDNN convolution memory usage

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31500]
Sometimes the cuDNN implementation of convolutions is trying to use too large workspace. For example:

```python
import torch
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True
conv = torch.nn.ConvTranspose2d(1, 1, 1, 1, bias=False).cuda().half()
input_large = torch.randn(1024, 1, 1024, 1024, dtype=torch.half, device='cuda')
ret = conv(input_large)
```
gives
```
RuntimeError: CUDA out of memory. Tried to allocate 48.01 GiB (GPU 0; 15.78 GiB total capacity; 4.00 GiB already allocated; 10.75 GiB free; 4.00 GiB reserved in total by PyTorch)
```

I find this extremely annoying when I try to fix https://github.com/pytorch/pytorch/issues/22496: it is sometimes hard to find a good configuration that has more than 2^31 elements but can still runnable on my 16GB Volta card.

In such a case, should PyTorch be smart enough to know:
- Which algorithm of cuDNN has a small enough memory usage that fits the device, and
- If all algorithms of cuDNN use too large memory, should we fall back to a kernel that uses small memory. 

cc: @csarofeen @ptrblck @ngimel 

cc @ngimel

**Comment by ngimel** [comment]
@zasdfgbnm for your testing purposes the workaround is to set `torch.backends.cudnn.deterministic=True` (and `benchmark=False`), it will pick implicit gemm algorithm that is 1) supported for all cases 2) uses relatively little memory. It is also a nice fallback for your second question, as far as I understand there should not be a situation where implicit gemm algorithm is not applicable. I thought pytorch should fall back to it when it fails to allocate requested workspace but looks like I'm wrong.

**Comment by zasdfgbnm** [comment]
@ngimel After setting
```python
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True
```
I still have the same problem...

**Comment by zasdfgbnm** [comment]
For backward, the default algorithm is
```C++
static constexpr auto DEFAULT_ALGO = CUDNN_CONVOLUTION_BWD_DATA_ALGO_1;
```

**Comment by ngimel** [comment]
Per offline conversation, looks like a bug in cudnn, because algo 1 should always use small amount of memory.
