### ISSUE TITLE
torch.cuda.manual_seed() assertion error without CUDA

### ISSUE THREAD

**Issue by christoph-conrads** [pytorch/pytorch#3153]
According to the [PyTorch CUDA documentation](https://github.com/pytorch/pytorch/blob/6647475bc2ba906c452a21e3857571d4de6ecadc/torch/cuda/random.py#L62-L64), `torch.cuda.manual_seed(seed)` and `torch.cuda.manual_seed_all(seed)` can be called even when CUDA is unavailable yet the following MWE stops with an assertion error on my computer without GPU:

Code:
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
import torch.cuda

print('CUDA available?', torch.cuda.is_available())

torch.cuda.manual_seed(1)
```

Output:
```
christoph:/tmp$ python seed-crash.py 
CUDA available? False
Traceback (most recent call last):
  File "seed-crash.py", line 9, in <module>
    torch.cuda.manual_seed(1)
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/torch/cuda/random.py", line 27, in manual_seed
    _lazy_init()
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

I am using PyTorch py27ha262b23_4cu75 for Conda 4.3.29.

**Comment by apaszke** [comment]
You link to source code, which has been updated since you installed PyTorch. I don't think this change made it yet to the binaries, but you'll be able to call this safely in a source install for sure

**Comment by christoph-conrads** [comment]
I can confirm that it works with PyTorch 0.2.0+6647475 built from source.
