### ISSUE TITLE
Prepare() ignores 'qconfig_dict'

### ISSUE THREAD

**Issue by Unity05** [pytorch/pytorch#31549]
## 🐛 Bug

When using ```prepare()```, the passed ```qconfig_dict``` is ignored and thus leads to the safe calling of the UserWarning defined in the next lines.
(l. 144)

## To Reproduce

1.) ```qmodel = quantization.prepare(model=model, qconfig_dict={"ModuleName": quantization.get_default_qconfig())})```

UserWarning: 
```...\quantize.py:147: UserWarning: None of the submodule got qconfig applied. Make sure you passed correct configuration through `qconfig_dict` or by assigning the `.qconfig` attribute directly on submodules```

--> passed qconfig_dict is ignored

## Expected behavior

I expect that there are modules in ```model``` which have the attribute ```qconfig``` after the execution of ```propagate_qconfig_()```.

## Environment

PyTorch version: 1.3.1+cu92
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 432.00
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.1+cu92
[pip] torchvision==0.4.2+cu92
[conda] Could not collect

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by Unity05** [comment]
I am on it.

**Comment by jerryzh168** [comment]
That is correct, we don't want to use qconfig_dict in top level eager mode API.

**Comment by jerryzh168** [comment]
we should remove this
