### ISSUE TITLE
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by XiaoshuiHuang** [pytorch/pytorch#31554]
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory

Environment: 
1. Pytorch 1.3.1
2. Linux
3. Pycharm

**Comment by XiaoshuiHuang** [comment]
I found a solution: include the lib path of anaconda into LD_LIBRARY_PATH before running pycharm.

**For my own case:** run the following code line in the command line.

export LD_LIBRARY_PATH=/data/xiaoshua/miniconda3/lib/python3.7/site-packages/torch/lib:$LD_LIBRARY_PATH

**For your case:**  change the path of "/data/xiaoshua/miniconda3/" to your own directory. Then, run the above export code line.

**Comment by mruberry** [comment]
Great to hear you found a solution!
