### ISSUE TITLE
Can pytorch 1.3 support cuda 9.0 

### ISSUE THREAD

**Issue by yustaub** [pytorch/pytorch#31556]
the machine nvidia driver version is 390.67, and I have no power to update the driver, but the detectron2 requires pytorch1.3, and can pytorch 1.3 support cuda 9.0 ？Or anyone knows how pytorch1.3 and cuda 9.0 coexist?sincere thanks！！

**Comment by peterjc123** [comment]
I guess you'll need to build from source.

**Comment by yustaub** [comment]
@peterjc123 oh, I think I can not handle it now ,I just a newer for deep learning

**Comment by mruberry** [comment]
This question is more appropriate for the forums: https://discuss.pytorch.org/.

https://pytorch.org/ may also answer your questions.

**Comment by chg0901** [comment]
> the machine nvidia driver version is 390.67, and I have no power to update the driver, but the detectron2 requires pytorch1.3, and can pytorch 1.3 support cuda 9.0 ？Or anyone knows how pytorch1.3 and cuda 9.0 coexist?sincere thanks！！

I post a question about it. Did you get the answer?
https://discuss.pytorch.org/t/can-pytorch1-0-0-in-win10-with-cuda9-0-use-tensorboard/65747

**Comment by mruberry** [comment]
I'm sorry I don't understand your question. It appears your question was answered on the forum?
