### ISSUE TITLE
Model Loading Issue in Android

### ISSUE THREAD

**Issue by mohitranawat** [pytorch/pytorch#31564]
## 🐛 Bug

I was loading my model in the Pytorch Android with the nighly build for pytorch android but the model is not loading.

Then I was trying to load the MobilenetV2 given in the pytorch demo app with the nighly build version but this model is also not loading. It was loading few days back.

Is there any changes in the nightly version which I need to replicate to load the model correctly ?

Error in android studio - 
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11805 (demo_app), pid 11805 (demo_app)
```

```

 - PyTorch Version (e.g., 1.0): Pytorch Nightly 1.4.0
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:3.7.3
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by dreiss** [comment]
This was a bug in PyTorch.  Fixed in https://github.com/pytorch/pytorch/pull/31582 .  Please try the latest nightly release.
