### ISSUE TITLE
regarding tgt_mask: (T, T) set as optional in nn.TransformerDecoder

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#31567]
shouldn't tgt_mask be always there, because we do not want nn.TransformerDecoder to look at ahead words during training.
for example if input to nn.TransformerDecoder is the sequence,
```
<sos> hello world.
```
then if we do not provide tgt_mask, and pass (tgt, tgt, tgt) in self_attn, then the representation of 'hello' would consider 'world' also, when computing self attention.

**Comment by mruberry** [comment]
This question seems more appropriate for the PyTorch forums,  https://discuss.pytorch.org/.
