### ISSUE TITLE
libpytorch_jni.so happen crash on Version:"pytorch_android:1.4.0-SNAPSHOT"

### ISSUE THREAD

**Issue by binhongwang** [pytorch/pytorch#31589]
## 🐛 Bug
libpytorch_jni.so happen crash after updata "pytorch_android:1.4.0-SNAPSHOT"

log:
01-05 02:52:50.746 28769 28769 F DEBUG   : pid: 28732, tid: 28732, name: orch.helloworld  >>> org.pytorch.helloworld <<<
01-05 02:52:50.746 28769 28769 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
01-05 02:52:50.746 28769 28769 F DEBUG   : Cause: null pointer dereference
01-05 02:52:50.746 28769 28769 F DEBUG   :     x0  0000000000000030  x1  0000007159cd3800  x2  000000715aeb1c0f  x3  0000000000000000
01-05 02:52:50.746 28769 28769 F DEBUG   :     x4  0000000000000001  x5  0000000000000000  x6  5f676e696e6e7572  x7  7261765f676e696e
01-05 02:52:50.747 28769 28769 F DEBUG   :     x8  00000071f7369ca2  x9  0000000000000012  x10 0000000000000011  x11 0000000000000000
01-05 02:52:50.747 28769 28769 F DEBUG   :     x12 0080000000800001  x13 0000000000000001  x14 0000000000000008  x15 aaaaaaaaaaaaaaab
01-05 02:52:50.747 28769 28769 F DEBUG   :     x16 000000715b1d1870  x17 00000071f7306c94  x18 0000000000000010  x19 0000000000000000
01-05 02:52:50.747 28769 28769 F DEBUG   :     x20 00000071598d1621  x21 000000000000002e  x22 0000000000000000  x23 00000071598d1621
01-05 02:52:50.747 28769 28769 F DEBUG   :     x24 0000007fdfed0be8  x25 0000007fdfecfc20  x26 00000071f99455e0  x27 0000007fdfecf968
01-05 02:52:50.747 28769 28769 F DEBUG   :     x28 0000007fdfecfb00  x29 0000007fdfecf7f0
01-05 02:52:50.747 28769 28769 F DEBUG   :     sp  0000007fdfecf770  lr  0000007159ebdd0c  pc  0000007159ebddf8
01-05 02:52:50.906 28769 28769 F DEBUG   : 
01-05 02:52:50.906 28769 28769 F DEBUG   : backtrace:
01-05 02:52:50.906 28769 28769 F DEBUG   :     #00 pc 00000000001b4df8  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #01 pc 0000000000fa0e3c  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #02 pc 0000000000f946cc  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #03 pc 0000000000f5fdfc  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #04 pc 0000000000f6969c  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #05 pc 0000000000f9ce84  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so
01-05 02:52:50.907 28769 28769 F DEBUG   :     #06 pc 0000000000f9cc30  /data/app/org.pytorch.helloworld-x-EnhV86xlizR4xD4Ew1_A==/lib/arm64/libpytorch_jni.so

## To Reproduce

1.download pytorch android helloworld demo
2.update 1.3 to 1.4.0-SNAPSHOT
3.run app, crash happen

**Comment by dreiss** [comment]
This was a bug in PyTorch.  Fixed in https://github.com/pytorch/pytorch/pull/31582 .  Please try the latest nightly release.
