### ISSUE TITLE
torch_nightly on Windows still installs 20191216 build 

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#31585]
## 🐛 Bug

PyTorch nighly on Windows still installs 20191216 build.

## To Reproduce

```
C:\>pip install --pre --no-cache-dir torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.4.0.dev20191216%2Bcpu-cp36-cp36m-win_amd64.whl (82.0MB)
```

## Expected behavior

More recent build including fix for #31370. 

cc @ezyang @gchanan @zou3519 @peterjc123

**Comment by peterjc123** [comment]
Yes, I'm aware of it will try to restore the nightly build into a working state asap.

**Comment by aaost** [comment]
> Yes, I'm aware of it and will try to restore the nightly build into a working state asap.

Thanks! Voting with both arms here!

**Comment by peterjc123** [comment]
The nightly build is green again. Closing.
