### ISSUE TITLE
when i try to export a pytorch model to ONNX, got RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.

### ISSUE THREAD

**Issue by lerancool** [pytorch/pytorch#31591]
## To Reproduce

```
/Users/duke/opt/anaconda3/bin/python /Volumes/无极山/project/code/pytorch2ONNX.py
/Volumes/无极山/project/code/models/anchors.py:24: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  image_shape = np.array(image_shape)
/Volumes/无极山/project/code/models/anchors.py:35: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return torch.from_numpy(all_anchors.astype(np.float32))
Traceback (most recent call last):
  File "/Volumes/无极山/project/code/pytorch2ONNX.py", line 39, in <module>
    save2ONNX(args)
  File "/Volumes/无极山/project/code/pytorch2ONNX.py", line 27, in save2ONNX
    torch.onnx.export(model, x, export_ONNX_file)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/duke/opt/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 356, in forward
    torch._C._tracer_exit(tuple(out_vars))
RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.

Process finished with exit code 1
```

##Here is the code

```
import torch
import torch.onnx
from torch.autograd import Variable
from models.retinanet import resnet34, resnet50
from build_network import build_network
input_model = '../user_data/model_data/model_at_epoch_1.dat'
output_dir = 'torch_onnx_model.onnx'
dummy_input = torch.randn(2, 3, 800, 800)
checkpoint = torch.load(input_model)
model, _ = build_network(snapshot=None, backend='retinanet')
model.load_state_dict(checkpoint['state_dict'])
torch.onnx.export(model, dummy_input, output_dir)
print('Done')
```

## Expected behavior

The ONNX should be exported successfully.

## Environment
Python 3.7.4
pytorch '1.3.1'
macos 10.15

cc @suo

**Comment by suo** [comment]
Thanks for the report! As the error message indicates, the tracer detected that the output of your model didn't have any relationship to the input. Without seeing your model, it's not possible for us to tell why the tracer failed in this instance; can you post a small script that we can run to reproduce your issue?

**Comment by mjjimenez** [comment]
Hi, I just wanted to confirm since I've been getting this error as well. By "having a relationship to the input" do you mean that the output tensor should be in the same computational graph as the input?

**Comment by suo** [comment]
Yeah, basically the tracer is detecting that—based on its understanding—the input doesn't affect the output at all. So changing the input would not lead to a change in output.

Since that is rarely actually the case (because there's not much use for a function that does not depend on its inputs), we consider it a red flag that the tracer messed up in some way.

**Comment by daydayfun** [comment]
I have the same problem

**Comment by hurun** [comment]
so do i, same problem

**Comment by irina160** [comment]
same problem here! I'm doing everything the same way as described in [this tutorial](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html) : 
`the_model = SimpleCNN()
dictionary = torch.load('best_model_dict.pt')
the_model.load_state_dict(dictionary)
the_model.eval()
x = torch.randn(1, 6, 100, 100, requires_grad=True)
torch_out = the_model(x)

# Export the model
torch.onnx.export(the_model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "the_model.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                'output' : {0 : 'batch_size'}})`
The model itself is certainly working and producing an output (image predictions) that depends on the input.

**Comment by justinchuby** [comment]
@irina160 are you doing any `resize_` in the model?

**Comment by youcef4k** [comment]
Same problem with: https://github.com/zjjMaiMai/TinyHITNet

**Comment by irina160** [comment]
> @irina160 are you doing any `resize_` in the model?

@justinchuby my apologies for the late response; yes, I am - does it intervene with the scripting in some way?

**Comment by justinchuby** [comment]
`resize_` is not yet supported by the jit tracer. Replacing them with reshape or view may help

**Comment by satpalsr** [comment]
I am getting some similar trace warnings for other model
```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  image_shape = np.array(image_shape)
pytorch-retinanet/retinanet/anchors.py:38: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return torch.from_numpy(all_anchors.astype(np.float32)).cuda()
pytorch-retinanet/retinanet/model.py:268: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalScores = torch.Tensor([])
pytorch-retinanet/retinanet/model.py:269: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalAnchorBoxesIndexes = torch.Tensor([]).long()
pytorch-retinanet/retinanet/model.py:270: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  finalAnchorBoxesCoordinates = torch.Tensor([])
pytorch-retinanet/retinanet/model.py:280: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores_over_thresh.sum() == 0:
  ```
 Causing onnx model trace to be wrong
![image](https://user-images.githubusercontent.com/39311993/196389179-798cbf2f-e51d-4476-a611-5452d7140986.png)

How to fix them?

**Comment by codegrafix** [comment]
Hey guys, I am running in the same problem. Any solution so far?

**Comment by elvinagam** [comment]
So, 3 years, and ppl still running into this. please, @suo check this out one more time.

**Comment by RobinGRAPIN** [comment]
I also faced this problem. For me, it happened using a compiled cuda operator in my model ( my testcase is while exporting PointRCNN https://github.com/sshaoshuai/PointRCNN iou_3D_cuda.nms_gpu operator). I have an argument that is modified by reference inside the C++/Cuda code. I suspect that this modification con not be traced by the python tracer, which then not understand how the input has been modified, causing this error message. The slution I found was to re-write this operator using python functions. It is way slower but for training I keep the initial operator, I only switch for ONNX export.

**Comment by rounak890** [comment]
I have also faced the same problem and find out that for `torch.onnx.export()`  to work both input and output of model must return either a tensor or a list of tensor .If the model is returning a dictionary or anything else than `torch.onnx.export()` will not work. In my case my model was returning a dict so i converted it to a list of tensors and it worked. 

Hope that it helps you.

**Comment by likecaulfield** [comment]
@rounak890 Would you be able to share your converted code please? as I am facing the same problem. I converted the output to list of tensors (from tuple) but it's still showing the error.
