### ISSUE TITLE
Wrong function arguments for Tensor.scatter()

### ISSUE THREAD

**Issue by ShnitzelKiller** [pytorch/pytorch#31601]
## 📚 Documentation

https://pytorch.org/docs/stable/tensors.html#torch.Tensor.scatter
> `scatter(dim, index, source)` → Tensor

The argument name is `src`, not `source`. `source` will cause an error in the current Pytorch version, and `src` will cause an error in older versions.

**Comment by mruberry** [comment]
Thank you for reporting this issue. Would you like to submit a fix correcting "source" to "src" in the docs?

**Comment by ShnitzelKiller** [comment]
#31617 seems to cause build failure, which I don't understand since it's just a change to the documentation.

**Comment by mruberry** [comment]
Thanks for the PR! The build errors were unrelated. I've approved it and will merge it after New Year's.

Thanks for reporting and fixing this issue, @ShnitzelKiller!
