### ISSUE TITLE
the example program using libtorch is not linked against torch_cuda when USE_CUDA is ON

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#31611]
## 🐛 Bug

Looks like https://github.com/pytorch/pytorch/issues/15992 is coming back again after the split of the torch library.

## To Reproduce

1. The following script throws "Torch is not linked against CUDA" and gets 0 as output.
```cpp
#include <ATen/ATen.h>
#include <torch/torch.h>
#include <iostream>

int main() {
	std::cout << torch::cuda::is_available() << std::endl;
	torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
        return 0;
}
```
2. The following one is working correctly and gets 1 as output.
```cpp
#include <ATen/ATen.h>
#include <torch/torch.h>
#include <iostream>
#include <Windows.h>

int main() {
	LoadLibraryA("torch_cuda.dll");
	std::cout << torch::cuda::is_available() << std::endl;
	torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
        return 0;
}
```

## Expected behavior

The behaviour keeps consistent in code snippet 1 and code snippet 2.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: doesn't matter
 - CUDA/cuDNN version: doesn't matter
 - GPU models and configuration: doesn't matter
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @ngimel @peterjc123

**Comment by peterjc123** [comment]
@ezyang

**Comment by gchanan** [comment]
Is this an issue in 1.4?  I will check.

**Comment by gchanan** [comment]
This is not a problem with 1.4, which doesn't have the split change (it got reverted).

**Comment by ezyang** [comment]
This appears to be Windows specific because following the instructions in https://pytorch.org/tutorials/advanced/cpp_frontend.html I get output of "1" (correct)

**Comment by ezyang** [comment]
I don't know when I'm going to get to this, unassigning myself for now.

**Comment by peterjc123** [comment]
I just found out that this issue could be solved by using the `/INCLUDE` switch. torch_cuda.dll contains the function signature "?warp_size@cuda@at@@YAHXZ" ("int __cdecl at::cuda::warp_size(void)"). So adding `/INCLUDE:"?warp_size@cuda@at@@YAHXZ"` to the linker flags will force the library/executable to link against `torch_cuda.dll`. What do you think, @ezyang ?

**Comment by ezyang** [comment]
@peterjc123 Hmm, while I'm not so hot about hard coding one specific symbol (I guess if we document it appropriately it's fine), I don't have any better ideas. SGTM.

**Comment by peterjc123** [comment]
@ezyang Recently, more and more users are complaining about this. It seems that they like to construct a VS project on their own instead of rely on CMake, which will need to set the flag manually. MSVC has a pragma for adding linker flags https://docs.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=vs-2019#linker. But I don't know where should I add it. Is there a header that only exist in CUDA build and will be included by `#include <torch/extension.h>`?

**Comment by ezyang** [comment]
@peterjc123 Do you think maybe the strategy here might work? https://github.com/pytorch/vision/issues/2134#issuecomment-625075418

Then they have to import a CUDA specific header, but that is all.

**Comment by peterjc123** [comment]
@ezyang That one sounds more portable and both methods should be effective.

**Comment by powderluv** [comment]
I am noticing the same issue with Linux.  torch::cuda::is_available() returns zero.  

There is a weird hack were if you create a dummy network and pass it to c++ data_parallel somehow CUDA is detected again.

**Comment by ezyang** [comment]
@powderluv do you mind opening a new issue for this?

**Comment by powderluv** [comment]
I have opened https://github.com/pytorch/pytorch/issues/42018

**Comment by sipie800** [comment]
I.m using Clion 2021.1 and MSVC(vs2019) as a c++ builder. Reproduced this error using libtorch 1.9(cuda 11.1). Finally figured out the decent way to deal with this error. that's **USING CMAKE**!

I started my project using a manually link cmake file:
...
include_directories(LIBORCH_DIR/include LIBORCH_DIR/include/torch/csrc/api/include)
#link_directories(LIBORCH_DIR/lib)
#add_executable(test main.cpp)
#target_link_libraries(test c10.dll c10_cuda.dll torch_cpu.dll torch_cuda.dll)
...
It is built with no error and torch::cuda::is_available() always got FALSE.

I don't use VS2019 IDE, have no idea how to add /INCLUDE=?warp_size@cuda@at@@YAHXZ hack to my project.
Here are some tried-and-failed solutions:

A:cmake add link flag
set_target_properties(test PROPERTIES LINK_FLAGS /INCLUDE=?warp_size@cuda@at@@YAHXZ)

B as microsoft recommend, add condition compile to code:
#pragma comment(linker, "/include:?warp_size@cuda@at@@YAHXZ")

C:working yet so weird(as mentioned before in this post)
using windows.h api LoadLibraryA("torch_cuda.dll") at the very begining of the program.At the same time you have to copy all the libtorch dll (not only torch_cuda.dll )to exe directory, or it doesn't work.

### D: working naturally
use cmake as following:
**set(CMAKE_PREFIX_PATH "LIBORCH_DIR/share/cmake/Torch")
find_package(Torch REQUIRED)
add_executable(test main.cpp)
target_link_libraries(test "${TORCH_LIBRARIES}")**
it's very easy, just that official developer mean to deploy this way while it made more difficult the regular way of cmake.
