### ISSUE TITLE
nelements is not jitable

### ISSUE THREAD

**Issue by vincentqb** [pytorch/pytorch#31626]
## 🐛 Bug

As mentioned in [comment](https://github.com/pytorch/audio/pull/365/files#r357952316), `nelement` is not jitable even though [documentation](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.nelement) points one to the other as the same function.

cc @suo

**Comment by eellison** [comment]
Thanks for issue! This is more generally covered by https://github.com/pytorch/pytorch/issues/30774, so I'm going to close this one. FWIW, full list of unsupported ops is [here](https://pytorch.org/docs/master/jit_unsupported.html), and each section has an outstanding issue to cover it.
