### ISSUE TITLE
torch.pow has a question of Doc

### ISSUE THREAD

**Issue by breerpeer** [pytorch/pytorch#31623]
At torch.pow last paragraph:
        >>> exp = torch.arange(1., 5.)
        >>> base = 2
        >>> torch.pow(base, exp)
        tensor([  2.,   4.,   8.,  16.])

But,the following if True:
In [11]: torch.pow(torch.arange(1.,5.),2)
Out[11]: tensor([ 1.,  4.,  9., 16.])

it's 1 is'n 2

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
@breerpeer you reversed the arguments. This is expected behavior. `torch.pow(2, torch.arange(1., 5.))` gives ` tensor([ 2., 4., 8., 16.])`.
