### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory     (no backtrace available)

### ISSUE THREAD

**Issue by Kuloud** [pytorch/pytorch#31620]
## To Reproduce

1. Module.load(modelFile.absolutePath) 
2.PytorchStreamReader failed reading zip archive

## Expected behavior

Load the model file correct.

## Environment

 - PyTorch Android Version : 1.3.1 ( org.pytorch:pytorch_android:1.3.1 )
 - Device Info: Mi 8 / MIUI 11.0.4.0 / Qualcomm Dragon 845

## Additional context

[onet_epoch.pt.zip](https://github.com/pytorch/pytorch/files/4001839/onet_epoch.pt.zip)

```
    com.facebook.jni.CppException: [enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory
    (no backtrace available)
        at org.pytorch.Module$NativePeer.initHybrid(Native Method)
        at org.pytorch.Module$NativePeer.<init>(Module.java:70)
        at org.pytorch.Module.<init>(Module.java:25)
        at org.pytorch.Module.load(Module.java:21)
```

cc @suo

**Comment by ngimel** [comment]
Can you please provide a minimum script demonstrating the error?

**Comment by zdevito** [comment]
The attached file does not seem to be a valid TorchScript file (i.e. one generated with `.save` on a ScriptModule object). Can you provide more detail about how it was generated?

**Comment by Kuloud** [comment]
> The attached file does not seem to be a valid TorchScript file (i.e. one generated with `.save` on a ScriptModule object). Can you provide more detail about how it was generated?

this model file comes from 
https://github.com/Sierkinhane/mtcnn-pytorch

the script to generate the file : 
https://github.com/Sierkinhane/mtcnn-pytorch/blob/master/mtcnn/train_net/train.py

Thanks.

**Comment by Kuloud** [comment]
> Can you please provide a minimum script demonstrating the error?
line 65 in the file:
https://github.com/didi/AoE/blob/master/Android/third_party/pytorch/src/main/kotlin/com/didi/aoe/runtime/pytorch/PyTorchInterpreter.kt

I try to load the attached model file  in this way.

**Comment by driazati** [comment]
The `onet_epoch.pt.zip` file you provided looks like it's produced by calling `torch.save` (maybe [here](https://github.com/Sierkinhane/mtcnn-pytorch/blob/master/mtcnn/train_net/train.py#L226)?). TorchScript on mobile can only load a compiled model (one saved with `torch.jit.save`). 

You will need to make your model compatible with TorchScript (either via tracing or scripting, [details here](https://pytorch.org/docs/master/jit.html#creating-torchscript-code)), then save that via `torch.jit.save`.

**Comment by Kuloud** [comment]
> The `onet_epoch.pt.zip` file you provided looks like it's produced by calling `torch.save` (maybe [here](https://github.com/Sierkinhane/mtcnn-pytorch/blob/master/mtcnn/train_net/train.py#L226)?). TorchScript on mobile can only load a compiled model (one saved with `torch.jit.save`).
> 
> You will need to make your model compatible with TorchScript (either via tracing or scripting, [details here](https://pytorch.org/docs/master/jit.html#creating-torchscript-code)), then save that via `torch.jit.save`.

Ok, It works for me, thank you.

**Comment by saurabhmalviya25** [comment]
@Kuloud  Can you please share the code with scripting.
I am also facing the same issue but unable to resolve it.

**Comment by Coderx7** [comment]
I faced this issue and my problem was that, the pretrained model I used, had saved the model wholely ( saved it like `torch.save({'model': model})` and as you know, this is very bad, since in order to use that model, you need to have the same module/file/dir heirarchy or else it will crash. 
I tried to convert this model into torch script, it went fine, but upon using I faced this error. 

to solve this, I simply first saved the models state_dict() into a new checkpoint file, loaded from the new checkpoint and then converted my model.
hope it helps you as well

**Comment by HeyangQin** [comment]
In my case, this error was caused by a corrupted saved file. So I switch to older checkpoints and the problem is gone.

**Comment by tejan-rgb** [comment]
`
model_mdetr, postprocessor = torch.hub.load('ashkamath/mdetr:main', 'mdetr_efficientnetB5', pretrained=True, return_postprocessor=True)
`

I am running this and it is showing me this error:

`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
`
Help!

**Comment by bekirbakar** [comment]
> In my case, this error was caused by a corrupted saved file. So I switch to older checkpoints and the problem is gone.

I had the same problem today. In my case, it was because of corrupted download files. Somehow it stops downloading and goes to the next process which is unzipping. There the problem occurs.

There must be hash control or something else for downloads and I think an exception should be raised.

**Comment by naveenjafer** [comment]
@bekirbakar Did you manage to fix this? I am running into the same issue.

**Comment by adeljalalyousif** [comment]
/// same error

import torch
from torch import nn
import torchvision
resnet = torchvision.models.resnet101(pretrained=True) 
 

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by bekirbakar** [comment]
Download model manually and load it from local. See this [post][1].

[1]: https://stackoverflow.com/questions/52628270/is-there-any-way-i-can-download-the-pre-trained-models-available-in-pytorch-to-a

**Comment by RezaYazdaniAminabadi** [comment]
I run into this issue when different processes on different GPU ranks want to load the same file using `map_location='cpu'`. I have also checked that I can load the same checkpoint at python shell.  Does anyone know how to resolve this?
Thanks,
Reza

**Comment by QinHsiu** [comment]
I have faced the same problem.

**Comment by Boyangs3** [comment]
I solved it by redownloading the checkpoints file reasoning that the file is Incomplete in docker.
