### ISSUE TITLE
Quantization unit tests are poorly named

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#31625]
I needed to execute EagerModePostTrainingQuantTest to debug one of my PRs.

There are two obvious issues with this name:
1) It doesn't follow the PyTorch standard, where the all(?) of our existing tests start with "Test", i.e. "TestNN", "TestAutograd", etc.
2) it's not clear which file this test is in.  There are multiple "quant" test files, i.e. `test_quantization.py  test_quantized_models.py  test_quantized_nn_mods.py  test_quantized.py  test_quantized_tensor.py`.  So clearly whatever the wildcard means in `quant*` is semantically meaningful, but then it's used without a suffix.  That seems pretty confusing.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
For test files, I think `test_quantized.py` can be renamed to `test_quantized_kernels.py` or `test_quantized_ops.py` and `test_quantized_models.py` can be merged into `test_quantization.py`. 
Here is what each test file means:
- `test_quantization.py` is the e2e integration tests
- `test_quantized_kernel.py` or `test_quantized_op.py` is the quantized kernel/op test
- `test_quantized_nn_mods.py` is the quantized module test
- `test_quantized_tensor.py` is  the quantized tensor test.

**Comment by jerryzh168** [comment]
For naming, I think `EagerModePostTrainingQuantTest` should be something like `TestQuantizationEagerModePostTrainingStatic`.

**Comment by jerryzh168** [comment]
fixed now
