### ISSUE TITLE
latest libtorch debug error

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#31649]
libtorch-win-shared-with-deps-debug-latest 2019.12.18
debug x64 NO GPU|win10
---------------------------------------------------------
#include "torch/torch.h"
#include <iostream>
int main()
{
	torch::Tensor b= torch::randn({ 2 },torch::kCPU);
	std::cout << b << std::endl;
	system("pause");
}
---------------------------------------------------------
“ConsoleApplication1.exe”(Win32): 已加载“C:\Users\william\source\repos\ConsoleApplication1\x64\Debug\libiomp5md.dll”。
0x00007FF92A38A839 处(位于 ConsoleApplication1.exe 中)引发的异常: Microsoft C++ 异常: std::logic_error，位于内存位置 0x000000929F4FED18 处。
Debug Error!

Program: ...e\repos\ConsoleApplication1\x64\Debug\ConsoleApplication1.exe

abort() has been called

(Press Retry to debug the application)
------------------------------------------------------------------------
TypeIndex.h 
inline constexpr string_view extract(
    string_view prefix,
    string_view suffix,
    string_view str) {
#if !defined(__CUDA_ARCH__) // CUDA doesn't like std::logic_error in device code
  return (!str.starts_with(prefix) || !str.ends_with(suffix))
      ? (throw std::logic_error("Invalid pattern"), string_view())
      : str.substr(prefix.size(), str.size() - prefix.size() - suffix.size());
#else
  return str.substr(prefix.size(), str.size() - prefix.size() - suffix.size());
#endif
}

**Comment by peterjc123** [comment]
See https://github.com/pytorch/pytorch/issues/31370#issuecomment-569202683.
