### ISSUE TITLE
About torch.poisson

### ISSUE THREAD

**Issue by zoulu995** [pytorch/pytorch#31646]
There is no description of torch.poisson in the document. What is the specific function of this interface?
```
import torch
a = torch.randn(4)
torch.poisson(a)
```

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by ngimel** [comment]
Thank you for reporting this bug. This function is not documented, most likely it returns a value sampled according to poisson distribution with the parameter given by the input. 
@vishwakftw can you please submit a PR to document this function, if you know what it's doing?

**Comment by vishwakftw** [comment]
@ngimel Sure. The behavior is exactly what you have suggested. I'll document this and send in a PR tomorrow.

**Comment by zoulu995** [comment]
> Thank you for reporting this bug. This function is not documented, most likely it returns a value sampled according to poisson distribution with the parameter given by the input.
> @vishwakftw can you please submit a PR to document this function, if you know what it's doing?
thanks!!

**Comment by vishwakftw** [comment]
Reopening, as this is yet to be resolved.
