### ISSUE TITLE
[Feature Request] batched gesv

### ISSUE THREAD

**Issue by josephcourtney** [pytorch/pytorch#3164]
I would like to have access to a batched version of gesv. MAGMA provides magma_sgesv_batched and magma_dgesv_batched methods but they, and all the MAGMA batched methods, require the creation of a magma_queue. 

I am willing to help implement this feature but I don't have any experience with cuda programming and I am uncertain how to incorporate the creation of a magma_queue. If there were a general way of managing magma queues in pytorch it would ease the incorporation of other MAGMA batched routines.

**Comment by apaszke** [comment]
I don't think we're using MAGMA queues anywhere at the moment. Are they expensive to create?
