### ISSUE TITLE
DimCounter::increment unexpected/incorrect behaviour

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#31645]
## 🐛 Bug

DimCounter::increment produces unexpected DimCounter::values.

## To Reproduce

```c++
// similar to TensorIterator::for_each
// suppose x has shape (2, 1)
auto counter = at::DimCounter(x.sizes(), {0, x.numel()});
print_counter_values(counter.values);
counter.increment(counter.max_2d_step());
print_counter_values(counter.values);
```
Produces:
```
0, 0
0, 0
```

## Expected behavior
Something like:
```
0, 0
1, 0
```

## Environment

PyTorch version: 1.4.0a0+99350b3
Is debug build: Yes
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (crosstool-NG 1.23.0.452-d158) 7.3.0
CMake version: version 3.15.5

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 430.50
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.4.0a0+99350b3
[conda] magma-cuda101             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] torch                     1.4.0a0+99350b3           dev_0    <develop>

**Comment by ngimel** [comment]
Does this result in some user-facing bug? In this example, 2d-tensor is iterated over in one iteration, offset is properly incremented by `step[0]*step[1]`, so DimCounter.is_done() will return `true` and `counter.values` won't matter. If it were a 3-d tensor, then counter value for the third dimension would be properly incremented (unless it's `1`, in which case it won't matter if it's incremented or not, DimCounter is done).

**Comment by nikitaved** [comment]
I do check whether it is done. I expected max_2d_step to increment by 1, which is wrong, of course. My mistake. Thanks for the clarification!
