### ISSUE TITLE
test_conv_transposed_large_cuda failed on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#31650]
## 🐛 Bug

```
======================================================================
ERROR: test_conv_transposed_large_cuda (__main__.TestNNDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\test\common_device_type.py", line 180, in instantiated_test
    return test(self, device_arg)
  File "test_nn.py", line 9321, in test_conv_transposed_large
    ret = conv(input_large)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\modules\module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\nn\modules\conv.py", line 778, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA out of memory. Tried to allocate 6.00 GiB (GPU 0; 14.85 GiB total capacity; 8.00 GiB already allocated; 1.95 GiB free; 12.13 GiB reserved in total by PyTorch)
```

## To Reproduce

1. python setup.py install
2. python test/test_nn.py

## Expected behavior

Test pass.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla P4
 - Any other relevant information:

## Additional context

According to the commit history, either https://github.com/pytorch/pytorch/pull/31510 or https://github.com/pytorch/pytorch/pull/31444 is the cause. cc the authors of the PRs: @zasdfgbnm @jjsjann123 

cc @ezyang @gchanan @zou3519 @ngimel @peterjc123

**Comment by ngimel** [comment]
cc @zasdfgbnm, apparently 16GB cards are not enough to run your large convolution test? Can you please either decrease the sizes, or disable it on windows or based on available memory?

**Comment by peterjc123** [comment]
I disabled the test in #30897. Maybe someone can restore that later.

**Comment by zasdfgbnm** [comment]
@peterjc123 Do you see this failure on the CI or on your local machine? The test succeeds on my local Linux machine with 16GB volta card. It seems to be hard to predict how much memory is required.

**Comment by peterjc123** [comment]
The failure is seen in CI.

**Comment by charleshofer** [comment]
This doesn't look like it's just a Windows thing. This test is failing on Power Linux as well. It'd be nice if it was skipped there too and the message update accordingly.
