### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '__config__'

### ISSUE THREAD

**Issue by EoinKenny** [pytorch/pytorch#31654]
Just tried to upgrade pytorch  and got this error

AttributeError: module 'numpy' has no attribute '__config__'

Here is the trace 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-051d4e3cd005> in <module>
      1 import os
----> 2 import torch
      3 import torchvision
      4 import torch.nn as nn
      5 import pickle

/anaconda3/envs/exp1/lib/python3.6/site-packages/torch/__init__.py in <module>
     40 # or there is risk that later c modules will segfault when importing numpy
     41 try:
---> 42     import numpy as _np  # noqa: F401
     43 except ImportError:
     44     pass

/anaconda3/envs/exp1/lib/python3.6/site-packages/numpy/__init__.py in <module>
    226         # We don't actually use this ourselves anymore, but I'm not 100% sure that
    227         # no-one else in the world is using it (though I hope not)
--> 228         from .testing import Tester
    229 
    230     # Pytest testing

/anaconda3/envs/exp1/lib/python3.6/site-packages/numpy/testing/__init__.py in <module>
     10 from unittest import TestCase
     11 
---> 12 from ._private.utils import *
     13 from ._private import decorators as dec
     14 from ._private.nosetester import (

/anaconda3/envs/exp1/lib/python3.6/site-packages/numpy/testing/_private/utils.py in <module>
     55 IS_PYPY = platform.python_implementation() == 'PyPy'
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None
---> 57 HAS_LAPACK64 = hasattr(numpy.__config__, 'lapack_ilp64_opt_info')
     58 
     59 

AttributeError: module 'numpy' has no attribute '__config__'
`

**Comment by mruberry** [comment]
Try asking this question on the forums: https://discuss.pytorch.org/.

You may have to reinstall numpy (numpy failing to have attributes appears to be a common configuration issue).
