### ISSUE TITLE
[docs] torch.onnx.export docs contains two descriptions for example_outputs arg

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#31678]
https://pytorch.org/docs/master/onnx.html?highlight=export#torch.onnx.export
![image](https://user-images.githubusercontent.com/1041752/71543968-89ecca80-2979-11ea-8bbc-366b6e5c556c.png)

cc @ezyang @zou3519

**Comment by vadimkantorov** [comment]
It would be nice to have some automated tests to make sure all arguments are described / argument names are matching (at least for functions that specify all their arguments / no kwargs used) maybe inspect module can help

**Comment by ezyang** [comment]
Yeah, I think that's a good idea, though it's unlikely the core team is going to get around to doing this in the near future. Maybe someone can write a PR for it :)

**Comment by vadimkantorov** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/31826
