### ISSUE TITLE
About torch.constant_pad_nd

### ISSUE THREAD

**Issue by zoulu995** [pytorch/pytorch#31687]
There is no description of torch.constant_pad_nd in the document. What is the specific function of this interface? I tried to read the source code of aten（aten/src/ATen/native/ConstantPadNd.cpp）, but it was a little difficult for me hh.
```
import torch
a = torch.randn(4)
torch.constant_pad_nd(a, [1, 2], 0.5)
```

**Comment by SsnL** [comment]
This is not supposed to be exposed as public API, so I suggest not using it.

**Comment by ezyang** [comment]
This is a general problem we have, which is that everything in `native_functions.yaml` (sans an exclusion) gets exported to Python, even if it shouldn't be, and we haven't carefully audited this. But yes, as Simon says, please don't use it.

**Comment by mruberry** [comment]
Closing this issue since we do not intend to document the function.
