### ISSUE TITLE
how to set cuda stream by  call Aten function

### ISSUE THREAD

**Issue by kuramawzw1** [pytorch/pytorch#31696]
at::Tensor a = at::ones({16, 32}, opts);
at::Tensor b = at::randn({32, 64}, opts);
at::Tensor b1 = at::randn({32, 64}, opts);
auto c = at::matmul(a,b);
auto c1 = at::matmul(a,b1);
  I want to call matmul by attach different cuda stream.
 call  at::matmul(a,b) by using stream1 , and call  at::matmul(a,b1) by using stream2.
How to do it?   Thanks

cc @ngimel

**Comment by ngimel** [comment]
You need to create streams using `at::cuda::getStreamFromPool` API, and then either use `at::cuda::CUDAStreamGuard` to set the stream to the desired stream, or set stream using `at::cuda::setCurrentCUDAStream`. You can look at https://github.com/pytorch/pytorch/blob/a024e1e0913dafe0dd889f64e5d563c4f55e2715/aten/src/ATen/test/cuda_stream_test.cpp for some usage examples.

**Comment by kuramawzw1** [comment]
1. what's the role of at::cuda::CUDAStreamGuard?  
if I don't use CUDAStreamGuard, and just set stream like this 
   auto st1 = at::cuda::getStreamFromPool(false, device_index);
   at::cuda::setCurrentCUDAStream(st1); 
   auto c = at::matmul(a,b);
what's the problem of this.

2. I really want to extend a new fusion  Pytorch layer to save Gpu memory,  and in  backward function, some  kernel can run parllelel, so i want o use multi cuda stream, but i'm worried that it will influenced other op  stream if i use  at::cuda::setCurrentCUDAStream,  I'm not sure pytorch will use multi stream in auto grad. How it works?

**Comment by ngimel** [comment]
1. CUDAStreamGuard will reset the stream to the previously used stream once it goes out of scope, if instead you are using stream manually, you may forget to change it back, thus unexpectedly changing current stream for the user. 
2. Using setCurrentCUDAStream won't influence operations running on other streams. You need to make sure though that the default stream is synchronized with the stream your operation is running on. In many cases, using concurrent streams does not provide appreciable benefits.

**Comment by kuramawzw1** [comment]
> 1. CUDAStreamGuard will reset the stream to the previously used stream once it goes out of scope, if instead you are using stream manually, you may forget to change it back, thus unexpectedly changing current stream for the user.
> 2. Using setCurrentCUDAStream won't influence operations running on other streams. You need to make sure though that the default stream is synchronized with the stream your operation is running on. In many cases, using concurrent streams does not provide appreciable benefits.

I get it now, thanks
