### ISSUE TITLE
duplicated result when getting cloned Tensor`s data_ptr in list comprehension

### ISSUE THREAD

**Issue by allenling** [pytorch/pytorch#31695]
## To Reproduce

```
In [1]: import torch                                                                                                                                                                         

In [2]: x = torch.randn(1, 2, 3).to("cuda:0")                                                                                                                                                

In [3]: y = torch.randn(1, 2, 4).to("cuda:0")                                                                                                                                                

In [4]: bindings = [x.clone().data_ptr(), y.clone().data_ptr()]                                                                                                                              

In [5]: bindings                                                                                                                                                                             
Out[5]: [140582636749824, 140582636749824]

In [6]: y.clone().data_ptr()                                                                                                                                                                 
Out[6]: 140582636749824
```

data_ptrs in bindings are same as `y.clone().data_ptr()`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.5

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.3.0
[pip3] torch2trt==0.0.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.4.1
[conda] Could not collect

**Comment by agolynski** [comment]
Seems like when you are doing x.clone().data_ptr(), after that call is done the tensor is deallocated, same goes for y.clone().data_ptr(). 

Maybe try this?
x1 = x.clone()
y1 = y.clone()
bindings = [x1.data_ptr(), y1.data_ptr()]

**Comment by agolynski** [comment]
Closing it for now, let me know if it works for you. If not, feel free to reopen

**Comment by allenling** [comment]
@agolynski thanks for reply!

yes, when i clone outside list first, it works fine. 


> after that call is done the tensor is deallocated, same goes for `y.clone().data_ptr()`

would you please explain how that happen in more detail? 

how could that affect data_ptr in list comprehension after a tensor is deallocated?

**Comment by allenling** [comment]
ok, i got the answer from [pytorch forum](https://discuss.pytorch.org/t/duplicated-result-when-getting-cloned-tensor-s-data-ptr-in-list-comprehension/65330)
