### ISSUE TITLE
How to implement multiple different kernel shapes in 2D convolution?

### ISSUE THREAD

**Issue by vhchuong1997** [pytorch/pytorch#31699]
Hello. I’m currently working on spherical convolutional network topic. Right now I’m trying to develop a new kind of kernel used for the convolutional layer.
The usual kernel is 3x3 matrix. But for spherical images, after being projected onto a plane using equirectangular projection, there will be distortion. So I want to define the kernel as a spherical cap and project it on plane according to its position.
For example, the kernel at different positions of the sphere perspective to the panorama pictures will look like this:
![image](https://user-images.githubusercontent.com/51077545/71574908-c6f5c000-2b25-11ea-80e1-1387ccdcfc82.png)
Is there any way to determine the shape of the kernels in these ways? I have already had the whole coordinate of the points in every case. I would very appreciate any help and information.
Thank you guys very much!

cc @csarofeen @ptrblck

**Comment by ezyang** [comment]
You'd probably have to write an efficient CPU kernel for this.

**Comment by albanD** [comment]
Hi,

Given that you would need a hand tuned implementation for every possible cases you want to try, this is going to be time consuming to implement properly.
I would advise finding the smallest rectangular kernel that contains your points. For example, your first case would be a 3x3 kernel with a 0 in the center. And the last one would be a 1x3500 with 0s where you don't have values.
Then you can use the [functional interface](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.conv2d) to evaluate the result.

This might not work for very extreme cases where the rectangle will be very large but should be fast enough for prototyping.
If you have more questions, you can post in the [forum](https://discuss.pytorch.org/).

**Comment by vhchuong1997** [comment]
Hello! Thank you so much for replying!
Right now, my intention with this method has changed to another direction as mentioned in the forum [here](https://discuss.pytorch.org/t/how-to-implement-multiple-different-kernel-shapes/65334/8)
Please take a look at this. Thank you!

**Comment by albanD** [comment]
Thanks, I'll close this issue for now. You can re-open it after the forum discussion is finalized and if we conclude that this is something we want to add to the core of pytorch.
