### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'gels'

### ISSUE THREAD

**Issue by casijoe5231** [pytorch/pytorch#31700]
## 🐛 Bug

As the title says, **gels** seems to be missing in my installation.

## To Reproduce

1. Run this code:
```
import torch
b = torch.randn(600,1)
A = torch.randn(600,2)
X, _ = torch.gels(b,A)
X.size() #torch.Size([2, 1])
Y, _ = torch.gels(b.cuda(),A.cuda())
Y.size() #torch.Size([600, 1])
```
2.Error:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    X, _ = torch.gels(b,A)

AttributeError: module 'torch' has no attribute 'gels'
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1+cpu
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.9
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA

**Comment by peterjc123** [comment]
In the 1.3.0 release doc, I find this line.

> torch.gels: removed deprecated operator, use torch.lstsq instead. (26480).

So I believe this is not a bug.
