### ISSUE TITLE
how to multiply two matrics of 4-dimensions?

### ISSUE THREAD

**Issue by liyheart** [pytorch/pytorch#3172]
Now, I have two matrics A and B, suppose A is a matrix with size(10, 3, 4,5), and 10 is batch size. B is a matrix with size(10, 5,6,7), and 10 is batch size. how can I multiply the two matrics with batch multiply and get the result matrix with size (10, 3,4,6,7)? I tried iterate over the batchsize and use torch.mm, but failed. Is there any  good solution?

**Comment by chenyuntc** [comment]
```python
import torch as t
a=t.Tensor(10, 3, 4,5)
b=t.Tensor(10, 5,6,7)
r=a.view(10,-1,5).bmm(b.view(10,5,-1))
r = r.view(10,3,4,6,7)
```
ask it in  [ the forum](https://discuss.pytorch.org) if you have any question next time．
