### ISSUE TITLE
Static libtorch.a causes JIT tests to fail

### ISSUE THREAD

**Issue by HardLaugh** [pytorch/pytorch#31749]
set BUILD_SHARED_LIBS=OFF, and compilation is all right, but run build/bin/test_jit , test failed

cc @suo

**Comment by HardLaugh** [comment]
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x57 (0xc14cb7 in ./build/bin/test_jit)
frame #1: ./build/bin/test_jit() [0x75bd60]
frame #2: ./build/bin/test_jit() [0x75db5b]
frame #3: ./build/bin/test_jit() [0x75e0ef]
frame #4: ./build/bin/test_jit() [0x75c147]
frame #5: ./build/bin/test_jit() [0x75db5b]
frame #6: torch::jit::AliasDb::AliasDb(std::shared_ptr<torch::jit::Graph>) + 0x24d (0x75df3d in ./build/bin/test_jit)
frame #7: ./build/bin/test_jit() [0x78eef6]
frame #8: torch::jit::CustomFuseGraph(std::shared_ptr<torch::jit::Graph>&, std::function<bool (torch::jit::Node*)>, c10::Symbol, unsigned long) + 0x151 (0x791501 in ./build/bin/test_jit)
frame #9: torch::jit::test::testCustomFusionNestedBlocks() + 0x2e5 (0x5bcc75 in ./build/bin/test_jit)
frame #10: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x33 (0x9892b3 in ./build/bin/test_jit)
frame #11: ./build/bin/test_jit() [0x98066b]
frame #12: ./build/bin/test_jit() [0x980985]
frame #13: ./build/bin/test_jit() [0x980bc5]
frame #14: testing::internal::UnitTestImpl::RunAllTests() + 0xb9e (0x981b1e in ./build/bin/test_jit)
frame #15: testing::UnitTest::Run() + 0x74 (0x981e14 in ./build/bin/test_jit)
frame #16: main + 0xba (0x57eb3a in ./build/bin/test_jit)
frame #17: __libc_start_main + 0xf5 (0x7f435e2b6f45 in /lib/x86_64-linux-gnu/libc.so.6)
frame #18: ./build/bin/test_jit() [0x58a0c7]

**Comment by HardLaugh** [comment]
[----------] Global test environment tear-down
[==========] 51 tests from 1 test case ran. (65 ms total)
[  PASSED  ] 17 tests.
[  FAILED  ] 34 tests, listed below:
[  FAILED  ] JitTest.ADFormulas
[  FAILED  ] JitTest.ControlFlow
[  FAILED  ] JitTest.CreateAutodiffSubgraphs
[  FAILED  ] JitTest.CustomOperators
[  FAILED  ] JitTest.CustomOperatorAliasing
[  FAILED  ] JitTest.IValueKWargs
[  FAILED  ] JitTest.CustomFusion
[  FAILED  ] JitTest.Differentiate
[  FAILED  ] JitTest.DifferentiateWithRequiresGrad
[  FAILED  ] JitTest.IValue
[  FAILED  ] JitTest.PassManagement
[  FAILED  ] JitTest.RegisterFusionCachesKernel
[  FAILED  ] JitTest.SubgraphUtils
[  FAILED  ] JitTest.AliasAnalysis
[  FAILED  ] JitTest.ContainerAliasing
[  FAILED  ] JitTest.AliasRegistration
[  FAILED  ] JitTest.WriteTracking
[  FAILED  ] JitTest.Wildcards
[  FAILED  ] JitTest.ConstantPooling
[  FAILED  ] JitTest.ConstantPropagation
[  FAILED  ] JitTest.NetDefConverter
[  FAILED  ] JitTest.THNNConv
[  FAILED  ] JitTest.ATenNativeBatchNorm
[  FAILED  ] JitTest.NoneSchemaMatch
[  FAILED  ] JitTest.Profiler
[  FAILED  ] JitTest.InsertAndEliminateRedundantGuards
[  FAILED  ] JitTest.InsertBailOuts
[  FAILED  ] JitTest.PeepholeOptimize
[  FAILED  ] JitTest.RecordFunction
[  FAILED  ] JitTest.ModuleDefine
[  FAILED  ] JitTest.ClassImport

**Comment by ezyang** [comment]
Take a look at https://github.com/pytorch/pytorch/issues/21737

Do you have the error message thrown by the test?

**Comment by HardLaugh** [comment]
oh, thank you for your reply, i dont know what happened to test_jit, because it did not happen when i build shared libs . i just set BUILD_SHARED_LIBS=OFF and build it.

i want to static link against my project, although test_Jit failed. unfortunately，i got  errors about mkl. what should i do to static link against libmkl*.so

../../3rdparty/linux64/libtorch.a(ParallelOpenMP.cpp.o): In function `at::set_num_threads(int)':
ParallelOpenMP.cpp:(.text+0xdb): undefined reference to `MKL_Set_Num_Threads'
ParallelOpenMP.cpp:(.text+0xe2): undefined reference to `MKL_Set_Dynamic'
../../3rdparty/linux64/libtorch.a(ParallelOpenMP.cpp.o): In function `at::init_num_threads()':
ParallelOpenMP.cpp:(.text+0x325): undefined reference to `MKL_Get_Max_Threads'

i amd confused about mkl libraries, which have so many .so files

**Comment by HardLaugh** [comment]
@ezyang 
oh, thank you for your reply, i dont know what happened to test_jit, because it did not happen when i build shared libs . i just set BUILD_SHARED_LIBS=OFF and build it.

i want to static link against my project, although test_Jit failed. unfortunately，i got errors about mkl. what should i do to static link against libmkl*.so

../../3rdparty/linux64/libtorch.a(ParallelOpenMP.cpp.o): In function at::set_num_threads(int)': ParallelOpenMP.cpp:(.text+0xdb): undefined reference to MKL_Set_Num_Threads'
ParallelOpenMP.cpp:(.text+0xe2): undefined reference to MKL_Set_Dynamic' ../../3rdparty/linux64/libtorch.a(ParallelOpenMP.cpp.o): In function at::init_num_threads()':
ParallelOpenMP.cpp:(.text+0x325): undefined reference to `MKL_Get_Max_Threads'

i amd confused about mkl libraries, which have so many .so files

**Comment by HardLaugh** [comment]
@ezyang 
ok, i had successfully linked against my project, but failed to run. i may have something to do with test_jit-failed

**Comment by HardLaugh** [comment]
terminate called after throwing an instance of 'c10::Error'
  what():  No functions are registered for schema aten::empty(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, MemoryFormat? memory_format=None) -> Tensor (getOpTable at /home/46799/build_torch/libtorch/include/ATen/core/ATenDispatch.h:98)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x57 (0x5e8c87 in ./bin/linux64/ep_od_test)
frame #1: ./bin/linux64/ep_od_test() [0x55c567]
frame #2: ./bin/linux64/ep_od_test() [0x585cc8]
frame #3: ./bin/linux64/ep_od_test() [0x58b12c]
frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x1b3 (0x58cc73 in ./bin/linux64/ep_od_test)
frame #5: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x65 (0x58ce05 in ./bin/linux64/ep_od_test)
frame #6: pytorch_yolo_open + 0x59 (0x559069 in ./bin/linux64/ep_od_test)
frame #7: EP_OD_Create_v2(void**, ep_od_model_info_tag*) + 0x55 (0x557e35 in ./bin/linux64/ep_od_test)
frame #8: demo_od(char const*, dhivs_pic_tag*) + 0x99 (0x556f95 in ./bin/linux64/ep_od_test)
frame #9: main + 0x57 (0x557324 in ./bin/linux64/ep_od_test)
frame #10: __libc_start_main + 0xf5 (0x7f3903762f45 in /lib/x86_64-linux-gnu/libc.so.6)
frame #11: ./bin/linux64/ep_od_test() [0x556b08]

**Comment by HardLaugh** [comment]
function torch::jit::load , parse model failed, i dont think libtorch was compiled successfully when i set BUILD_SHARED_LIBS=OFF, but it did not gives me error information about libtorch

**Comment by HardLaugh** [comment]
CUDA not available. Disabling CUDA and MultiCUDA tests
Note: Google Test filter = *-*_CUDA:*_MultiCUDA
[==========] Running 51 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 51 tests from JitTest
[ RUN      ] JitTest.ADFormulas
unknown file: Failure
C++ exception with description "No functions are registered for schema aten::randn(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor (getOpTable at /home/46799/lxl/pytorch/aten/src/ATen/core/ATenDispatch.h:98)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x57 (0xc14cb7 in ./build/bin/test_jit)
frame #1: ./build/bin/test_jit() [0x5ffca7]
frame #2: ./build/bin/test_jit() [0x58fca8]
frame #3: ./build/bin/test_jit() [0x60e969]
frame #4: torch::jit::test::testADFormulas() + 0xe35 (0x5d3875 in ./build/bin/test_jit)
frame #5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 0x33 (0x9892b3 in ./build/bin/test_jit)
frame #6: ./build/bin/test_jit() [0x98066b]
frame #7: ./build/bin/test_jit() [0x980985]
frame #8: ./build/bin/test_jit() [0x980bc5]
frame #9: testing::internal::UnitTestImpl::RunAllTests() + 0xb9e (0x981b1e in ./build/bin/test_jit)
frame #10: testing::UnitTest::Run() + 0x74 (0x981e14 in ./build/bin/test_jit)
frame #11: main + 0xba (0x57eb3a in ./build/bin/test_jit)
frame #12: __libc_start_main + 0xf5 (0x7f281ff67f45 in /lib/x86_64-linux-gnu/libc.so.6)
frame #13: ./build/bin/test_jit() [0x58a0c7]
" thrown in the test body.
[  FAILED  ] JitTest.ADFormulas (1 ms)
[ RUN      ] JitTest.Attributes
[       OK ] JitTest.Attributes (1 ms)
[ RUN      ] JitTest.Blocks
[       OK ] JitTest.Blocks (0 ms)
[ RUN      ] JitTest.CodeTemplate
[       OK ] JitTest.CodeTemplate (0 ms)
[ RUN      ] JitTest.ControlFlow
unknown file: Failure
C++ exception with description "
Unknown builtin op: aten::mul.
Could not find any similar ops to aten::mul. This op may not exist or may not be currently supported in TorchScript.
:

**Comment by HardLaugh** [comment]
ok, fixed it by #21737
