### ISSUE TITLE
Emit compiler CPP version when compiling from source.

### ISSUE THREAD

**Issue by v0dro** [pytorch/pytorch#31757]
## 🚀 Feature
The `setup.py` should emit the CPP version being used for the compilation along with things like `USE_CUDA`, etc. 

## Motivation

I recently ran into an issue where I got an error stating that pytorch requires atleast C++14 for compilation. Although I managed to compile pytorch after some changes, it was hard to figure out how exactly it is being compiled since I had to browse the compilation output to check the `-std=c++14` flag being passed to gcc.

## Pitch

There should be a `CPP_VERSION: <version number>` in the compilation summary.

## Alternatives

Maybe output the library versions used in some text file for easy reference.

cc @yf225

**Comment by ezyang** [comment]
Seems reasonable, though if our cmake is setup correctly, it should ONLY ever be c++14 you're compiled with. The relevant code here is `aten/src/ATen/Version.cpp` and if there is a relevant macro you could just add it here.
