### ISSUE TITLE
Incorrect type hint for ".cuda()" method

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#31753]
I'm getting my type-checking marking `tensor.cuda(0)` as an error even though it works (ie, example usage in [lighning](https://github.com/williamFalcon/pytorch-lightning/blob/47659daa5f3908217d537cd529352263787ca5bb/pytorch_lightning/testing/model_mixins.py#L36)). The reason is that type hints require `_device` type. It should probably be `Union[_device, int]` rather than `_device`

in site-packages/torch/init.pyi
```
def cuda(self, device: Optional[_device]=None,
...
_device = device
...
class device:
    type: str
    index: _int

```

cc @ezyang

**Comment by ezyang** [comment]
Should be an easy fix, just edit the manual definition of cuda in `tools/pyi/gen_pyi.py`. It would be good to also check if any other functions were incorrectly bound this way.

**Comment by yaroslavvb** [comment]
also possibily related, `cuda.manual_seed_all` is missing in pyi

**Comment by ezyang** [comment]
If someone wants to open a PR for this, tag me as reviewer.

**Comment by jeongukjae** [comment]
> If someone wants to open a PR for this, tag me as reviewer.

@ezyang I created a PR related to this issue.

**Comment by rgommers** [comment]
The main issue was fixed by gh-33762, annotation is now `Optional[Union[_device, _int, str]]=None`.



> also possibily related, `cuda.manual_seed_all` is missing in pyi

This was also fixed, it's present in `torch/cuda/random/pyi`.

So closing, thanks all.
