### ISSUE TITLE
Building ONNX (proto file not being generated)

### ISSUE THREAD

**Issue by skn123** [pytorch/pytorch#31764]
## 🐛 Bug

Building ONNX which comes as a TPL dependency for pytorch
## To Reproduce
Just a simple make

1.python3
1.external or in-built protobuf
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): source code
 - OS (e.g., Linux): ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): make -j8
 - Python version:3.6.9
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

[ 50%] Built target Caffe2_PROTO
Scanning dependencies of target gen_onnx_proto
make[2]: *** No rule to make target 'third_party/onnx/onnx/onnx.in.proto', needed by 'third_party/onnx/onnx/onnx_onnx_torch-ml.proto'.  Stop.
CMakeFiles/Makefile2:2773: recipe for target 'third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all' failed
make[1]: *** [third_party/onnx/CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I have a feeling that this file is not getting generated. I did not see this behavior earlier. Has something changed in the last month?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by skn123** [comment]
A bump; A fresh checkout from git still does not solve this issue.

**Comment by thiagocrepaldi** [comment]
I just cloned pytorch with all its third party dependencies and built onnx from source without bugs (pytorch 1.110-dev)
