### ISSUE TITLE
Using torch.multiprocessing along with torch.distributed (mpi-backend)

### ISSUE THREAD

**Issue by Usama-Zafar** [pytorch/pytorch#31762]
## 🐛 Bug

 Trying to communicate between spawned sub-processes using Pytorch's multiprocessing class within an Openmpi distributed Backend process group fails.

## To Reproduce

1. Install Openmpi
2. Build / install Pytorch from source
3. Run the following code using "mpirun -np 2 python test_code.py"

```
def run(i, *args):
    print("I WAS SPAWNED BY:", args[0])
    
    tsr = torch.zeros(1)
    
    if args[0] == 0:
        tsr += 100
        dist.send(tsr, dst=1)
    else:
        dist.recv(tsr)
        print ("RECEIVED VALUE =", tsr)

if __name__ == '__main__':
    
    # Initialize Process Group
    dist.init_process_group(backend="mpi")
    
    mp.set_start_method('spawn')    
    
    # get current process information
    world_size = dist.get_world_size()
    rank = dist.get_rank()
    
    # spawn sub-processes
    mp.spawn(run, args=(rank, world_size,), nprocs=1)
```

Following exception is raised "Default process group is not initialized"
```
Traceback (most recent call last):
  File "test_code_2.py", line 29, in <module>
    mp.spawn(run, args=(rank, world_size,), nprocs=1)
  File "/home/usama/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/usama/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/usama/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/usama/Personal/Study/LAB/experiments/codes/test_code_2.py", line 12, in run
    dist.send(tsr, dst=1)
  File "/home/usama/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 660, in send
    _check_default_pg()
  File "/home/usama/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 185, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

## Expected behavior

Each sub-process should be able to communicate not only with other sub-processes but also with parent processes.

## Environment

PyTorch version: 1.1.0a0+8f0603b
Is debug build: No
CUDA used to build PyTorch: 10.1.105

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 430.64
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] numpydoc==0.9.1
[pip] torch==1.1.0a0+c182824
[pip] torchvision==0.2.2
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.0.1           cuda100py37he554f03_0  
[conda] tensorflow                1.15.0          mkl_py37h28c19af_0  
[conda] tensorflow-base           1.15.0          mkl_py37he1670d9_0  
[conda] torch                     1.1.0a0+c182824          pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

## Additional context

Is it even possible to communicate between sub-process to two different parent processes?

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by ezyang** [comment]
This sounds like advertised to work functionality simply does not work, but I do not know enough about the API to tell if it was used correclty.

**Comment by pietern** [comment]
This won't work because you initialize the default process group in the parent process and not its children. If you need to spawn processes **and** use MPI, you're going to have a bad time because MPI manages process execution itself (through `mpirun`). 

I don't know anything about your use case, but in general you have 2 options:
1. Don't use MPI. Have a parent process spawn N subprocess and initialize the default process group in those subprocesses using either the `gloo` or `nccl` backends.
2. Use MPI, but don't use `torch.distributed` from those subprocesses.

**Comment by pietern** [comment]
Closing the issue because this is not actionable.
