### ISSUE TITLE
model.to("cuda") get large memory

### ISSUE THREAD

**Issue by TinDang97** [pytorch/pytorch#31767]
Hi, everyone,

I'm a newbie. At the morning, I created a very small model like:

> model = Conv1d(12, 24, 1) 

but after I run 

> model.to("cuda")

My program takes 1.3gb memory in ram and 436mb VRAM GPU. I don't know what wrong here, but it takes too much.
Please help me fix it.
Thanks.

cc @ngimel

**Comment by ezyang** [comment]
This is a side effect of the CUDA runtime loading kernel images, see https://github.com/pytorch/pytorch/issues/12873 for more details.

**Comment by TinDang97** [comment]
> This is a side effect of the CUDA runtime loading kernel images, see #12873 for more details.

Thank you.
