### ISSUE TITLE
TestFakeQuantizePerChannel.test_backward_per_channel is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#31774]
failed: https://app.circleci.com/jobs/github/pytorch/pytorch/4099266

`test_forward_per_channel` and `test_fq_module` also failed in that test.

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by mrshenli** [comment]
@jerryzh168 sorry that I miss identified the problem, it was actually due to version bump of hypothesis I think. I am landing #31794 which pins the hypothesis version. When finishing investigation, could you please remove that version pin as well, thanks!

**Comment by jerryzh168** [comment]
OK
