### ISSUE TITLE
CI test should use PR commit instead of pulling the latest master

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#31788]
IIUC, currently we alway pull the latest master in CI tests, meaning that if we rerun tests on a master commit X, it could pull in more recent commits after X. This would make it harder to find out which commit breaks master. 

For example, https://app.circleci.com/jobs/github/pytorch/pytorch/4101228 is a test for #31763, but the its git log contains #31526.

cc @ezyang

**Comment by imskr** [comment]
I would like to work on this issue!  Assign me.

**Comment by imskr** [comment]
Can I work on this @mrshenli

**Comment by huydhn** [comment]
Resolve this as this issue is ancient and doesn't apply to the current CI anymore.
