### ISSUE TITLE
Can optimizer's state leverage parameters' names (string) as keys?

### ISSUE THREAD

**Issue by chenwydj** [pytorch/pytorch#31793]
## ❓ Questions and Help

Currently, the optimizer's state is a dictionary with the parameter itself (i.e. tensor-like matrix) as the key. (e.g. in [sgd.py](https://github.com/pytorch/pytorch/blob/master/torch/optim/sgd.py#L95))

I wonder if the key can be implemented as the optimizer's name (string) (i.e. passing model's `named_parameters()` to the optimizer instead of `parameters()`)? Any Pros and Cons?

Thank you!

**Comment by jerryzh168** [comment]
could you post the question in forums instead? https://discuss.pytorch.org/
