### ISSUE TITLE
max_norm not supported for nn.Embedding

### ISSUE THREAD

**Issue by backpropper** [pytorch/pytorch#3179]
The following code snippet reproduces the error:
```
enc = nn.Embedding(10, 200, max_norm=10)
input = Variable(torch.LongTensor([[1,2,4,5],[4,3,2,9]]))
enc(input)
```
It gives the following error:
`TypeError: _renorm() missing 1 required positional argument: 'norm_type'`
Even when I give some value to the argument norm_type, it gives the same error.
I saw in the documentation that _renorm() is not supported. Will it be fixed in the next release version?
Pytorch version : 0.2.0_4

**Comment by zou3519** [comment]
Yes, this has been fixed in master: https://github.com/pytorch/pytorch/issues/2620
You can build pytorch from source if you need the functionality

**Comment by backpropper** [comment]
Thanks!
