### ISSUE TITLE
A strange issue about detection of tensor in-place modification

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#31819]
I was implementing CTC in pure python PyTorch for fun (and possible modifications). I do alpha computation by modifying a tensor inplace. If `torch.logsumexp` is used in `logadd`, everything works fine but slower (especially on CPU). If custom `logadd` lines are used, I receive:
```
  File "ctc.py", line 76, in <module>
    custom_ctc_grad, = torch.autograd.grad(custom_ctc.sum(), logits, retain_graph = True)
  File "/miniconda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 157, in grad
    inputs, allow_unused)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 10]], which is output 0 of SliceBackward, is at version 17; expected version 16 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
It is strange because neither logadd version does inplace, so it's not clear why version tracking is much different.

Another issues is absence of fast logsumexp (for two/three arguments) on CPU (related https://github.com/pytorch/pytorch/issues/27522). A custom version is considerably faster on CPU, not sure why. It would be nice if we have all reduction functions supporting lists of tensors to do without temporary torch.stack and not roll custom implementations: in this code these are torch.max/torch.logsumexp.

```python
import torch
import torch.nn.functional as F

def logadd(x0, x1, x2):
    # everything works if the next line is uncommented
    # return torch.logsumexp(torch.stack([x0, x1, x2]), dim = 0)
    # keeping the following 4 lines uncommented causes an exception
    m = torch.max(torch.max(x0, x1), x2)
    m = m.masked_fill(m == float('-inf'), 0)
    res = (x0 - m).exp() + (x1 - m).exp() + (x2 - m).exp()
    return res.log().add(m)

def ctc_loss(log_probs, targets, input_lengths, target_lengths, blank : int = 0, reduction : str = 'none', alignment : bool = False):
    # https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/LossCTC.cpp#L37
    # https://github.com/skaae/Lasagne-CTC/blob/master/ctc_cost.py#L162
    B = torch.arange(len(targets), device = input_lengths.device)
    targets_ = torch.cat([targets, targets[:, :1]], dim = -1)
    targets_ = torch.stack([torch.full_like(targets_, blank), targets_], dim = -1).flatten(start_dim = -2)
    diff_labels = torch.cat([torch.as_tensor([[False, False]], device = targets.device).expand(len(B), -1), targets_[:, 2:] != targets_[:, :-2]], dim = 1)

    zero, zero_padding = torch.tensor(float('-inf'), device = log_probs.device, dtype = log_probs.dtype), 2
    log_probs_ = log_probs.gather(-1, targets_.expand(len(log_probs), -1, -1))
    log_alpha = torch.full((len(log_probs), len(B), zero_padding + targets_.shape[-1]), zero, device = log_probs.device, dtype = log_probs.dtype)
    log_alpha[0, :, zero_padding + 0] = log_probs[0, :, blank]
    log_alpha[0, :, zero_padding + 1] = log_probs[0, B, targets_[:, 1]]
    for t in range(1, len(log_probs)):
        log_alpha[t, :, 2:] = log_probs_[t] + logadd(log_alpha[t - 1, :, 2:], log_alpha[t - 1, :, 1:-1], torch.where(diff_labels, log_alpha[t - 1, :, :-2], zero))

    l1l2 = log_alpha[input_lengths - 1, B].gather(-1, torch.stack([zero_padding + target_lengths * 2 - 1, zero_padding + target_lengths * 2], dim = -1))
    loss = -torch.logsumexp(l1l2, dim = -1)
    if not alignment:
        return loss

    path = torch.zeros(len(log_alpha), len(B), device = log_alpha.device, dtype = torch.int64)
    path[input_lengths - 1, B] = zero_padding + 2 * target_lengths - 1 + l1l2.max(dim = -1).indices
    for t in range(len(path) - 1, 1, -1):
        indices = path[t]
        indices_ = torch.stack([(indices - 2) * diff_labels[B, (indices - zero_padding).clamp(min = 0)], (indices - 1).clamp(min = 0), indices], dim = -1)
        path[t - 1] += (indices - 2 + log_alpha[t - 1, B].gather(-1, indices_).max(dim = -1).indices).clamp(min = 0)
    return torch.zeros_like(log_alpha).scatter_(-1, path.unsqueeze(-1), 1.0)[..., 3::2]


if __name__ == '__main__':
    import time

    T, B, C = 16, 4, 2
    t = 4
    device = 'cuda'
    seed = 1
    rtol = 1e-3
    for set_seed in [torch.manual_seed] + ([torch.cuda.manual_seed_all] if device == 'cuda' else []):
        set_seed(seed)

    logits = torch.randn(T, B, C, device = device).requires_grad_()
    log_probs = logits.log_softmax(dim = -1)
    targets = torch.randint(1, C, (B, t), dtype = torch.long, device = device)
    input_lengths = torch.full((B,), T, dtype = torch.long, device = device)
    target_lengths = torch.full((B,), t, dtype = torch.long, device = device)

    tictoc = lambda: (device == 'cuda' and torch.cuda.synchronize()) or time.time()
    tic = tictoc()
    builtin_ctc = F.ctc_loss(log_probs, targets, input_lengths, target_lengths, blank = 0, reduction = 'none')
    print('Built-in CTC loss seconds:', tictoc() - tic)
  
    tic = tictoc()
    custom_ctc = ctc_loss(log_probs, targets, input_lengths, target_lengths, blank = 0, reduction = 'none')
    print('Custom CTC loss seconds:', tictoc() - tic)

    builtin_ctc_grad, = torch.autograd.grad(builtin_ctc.sum(), logits, retain_graph = True)
    custom_ctc_grad, = torch.autograd.grad(custom_ctc.sum(), logits, retain_graph = True)
   
    print('Device:', device)
    print('Log-probs shape:', 'x'.join(map(str, log_probs.shape)))
    print('Custom loss matches:', torch.allclose(builtin_ctc, custom_ctc, rtol = rtol))
    print('Grad matches:', torch.allclose(builtin_ctc_grad, custom_ctc_grad, rtol = rtol))
   
    print(builtin_ctc_grad[:, 0, :], custom_ctc_grad[:, 0, :])
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
Hi,

This happens because in this for-loop:
```python
```

**Comment by vadimkantorov** [comment]
> When you use `logsumexp`, this does not happen because stack returns new memory and does not save its input.

In other words, logsumexp does allocate new memory (akin to clone()) inside?

Would you have an advise how to rewrite this code to avoid this problem within framework of computing a full `log_alpha` matrix (I have a workaround that does not preserve the full matrix explicitly, but I think the full matrix iterative computation case is also an important one) without cloning and keeping PyTorch version tracking happy? E.g. would prior `torch.unbind()` and later inplace modification work?

**Comment by albanD** [comment]
> In other words, logsumexp does allocate new memory (akin to clone()) inside?

No, your `torch.stack()` allocates the memory, not `logsumexp`.

> would prior torch.unbind() and later inplace modification work?

Yes, but not for the right reason. It is currently buggy and does not track the version properly...

> Would you have an advise how to rewrite this code

Given that you never actually use `log_alpha` as a full Tensor, I would keep the first dimension in a list. That way, no need to do inplace on Tensor, just change the entry in the list.

**Comment by vadimkantorov** [comment]
> No, your `torch.stack()` allocates the memory, not `logsumexp`.

Both versions of `logadd` consume output of stack. so if this was ok, torch.max version would have also worked

> I would keep the first dimension in a list.

Yeah, the unbind idea was also to this end! I just wanted to make sure that the tensor is allocated as a chunk (if possible) and might even be reused. When dealing with big sequences, these quadratic matrices can be huge, so allocator quirks can bite. That's why I thought of allocating one big storage (within a tensor) and then unbinding. I guess an explicit storage offset computation tricks would allow to use unbind without relying on buggy version tracking of unbind?

**Comment by albanD** [comment]
> Both versions of logadd consume output of torch.stack.

Hmm I don't think so, `return torch.logsumexp(torch.stack([x0, x1, x2]), dim = 0)` does a stack on the inputs before passing to logsumexp. `m = torch.max(torch.max(x0, x1), x2)` work directly with the inputs. There is no stack in that version of the function.

> so allocator quirks can bite

If you do the same allocations repeatedly on CUDA, the allocation is basically for-free (using our caching allocator). So you should not worry too much about this.

**Comment by vadimkantorov** [comment]
> There is no stack in that version of the function

Oh, you are right! :)

Btw the buggy unbind maybe should stay that way, the semantics of untying version tracking is sometimes important and maybe worth exposing to the user (I think I have filed a similar issue but in another context)

**Comment by albanD** [comment]
> Btw the buggy unbind maybe should stay that way

The only issue is that it will silently compute wrong gradients if you modify both the base and an output :'( 
We are looking into ways to extend the version check to handle these non-overlapping cases. But that adds a lot of complexity and is quite hard. 
Let's continue the discussion in the other issue for version counter improvement.

**Comment by vadimkantorov** [comment]
Sure @albanD! Thanks for looking into this case!

**Comment by vadimkantorov** [comment]
@albanD I remembered also why I wanted to do it inplace: I'm filling only the part of the tensor, the rest must be padded by some padded value. But it should be possible to achieve the same without a giant pre-filled tensor.
