### ISSUE TITLE
How to convert model with a new QConv to onnx?

### ISSUE THREAD

**Issue by Wuqiman** [pytorch/pytorch#31821]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
I wrapped a new conv class to support quantization. When I convert this model to onnx, I want each conv in the onnx model to have quantized parameters such as quantization bits. Could you tell me  how to convert this model to onnx.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
onnx support for quantization is still in development I think, @supriyar 
Also could you post in discussion forum instead next time?

**Comment by supriyar** [comment]
We have a flow to convert conv (and some other) quantized pytorch operators from PyTorch to Caffe2 through ONNX. But this uses a Caffe2 specific representation in ONNX so the operator in itself is not runnable in ONNX.

**Comment by Wuqiman** [comment]
> We have a flow to convert conv (and some other) quantized pytorch operators from PyTorch to Caffe2 through ONNX. But this uses a Caffe2 specific representation in ONNX so the operator in itself is not runnable in ONNX.

Thank you very much. I want to support convert conv (and some other) quantized pytorch operators from PyTorch directly to ONNX. Could you give me a simple example or flow？Or show me  how through Caffe2? So I will know how to do next. Thank you very much~

**Comment by supriyar** [comment]
The regular pytorch -> onnx -> caffe2 conversion should work if the operators are supported. For example -

```
def test_quantized_convert(self):
        torch.backends.quantized.engine = "qnnpack"
        module_quant = torch.jit.load("/home/pytorch/model_quantized.pt")
        x_numpy = np.random.random((2, 3, 8, 8)).astype("float32")
        X = torch.from_numpy(x_numpy)
        module_quant.eval()
        output = module_quant(X)
        torch.set_default_tensor_type(torch.FloatTensor)
        input_names = ["x"]
        f = io.BytesIO()
        torch.onnx.export(module_quant, (X), f, verbose=False, example_outputs=output, input_names=input_names, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=9)
        f.seek(0)
        onnx_model = onnx.load(f)
        sample_inputs = (
            x_numpy,
        )
        caffe_res = c2.run_model(onnx_model, dict(zip(input_names, sample_inputs)))[0]
        np.testing.assert_almost_equal(output.numpy(), caffe_res, decimal=3)
```

List of supported operators are present in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_caffe2.py

**Comment by ggeor84** [comment]
also interested in this

**Comment by ggeor84** [comment]
@jerryzh168 wondering if any progress was made on this as well. right now we can't export quantized models to onnx, which is a very important flow for production

**Comment by jerryzh168** [comment]
> @jerryzh168 wondering if any progress was made on this as well. right now we can't export quantized models to onnx, which is a very important flow for production

can you paste the error message? I think quantized conv is supported

**Comment by ggeor84** [comment]
with pytorch 1.4.0, the following command:
torch.onnx.export(model, 
                    dummy_input, 
                    tmp_onnx_model_path, 
                    verbose=True, 
                    input_names=input_names, 
                    output_names=output_names, 
                    dynamic_axes=dynamic_axes,
                    keep_initializers_as_inputs=True , 
                    operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK )

yields the following:

Traceback (most recent call last):
  ...
  File "/home/gegeo/dev_space/virtualenvs/quant_1.4.0/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/gegeo/dev_space/virtualenvs/quant_1.4.0/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/gegeo/dev_space/virtualenvs/quant_1.4.0/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/gegeo/dev_space/virtualenvs/quant_1.4.0/lib/python3.7/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/gegeo/dev_space/virtualenvs/quant_1.4.0/lib/python3.7/site-packages/torch/onnx/utils.py", line 130, in _optimize_graph
    torch._C._jit_pass_onnx_unpack_quantized_weights(graph, params_dict)
RuntimeError: getValues: Quantized weight value not found amongst constant parameters.

**Comment by eleflea** [comment]
> > @jerryzh168 wondering if any progress was made on this as well. right now we can't export quantized models to onnx, which is a very important flow for production
> 
> can you paste the error message? I think quantized conv is supported

I tried with pytorch 1.5.0, and the same error occurred.

```
Traceback (most recent call last):
  File "convert.py", line 63, in <module>
    export_quant_to_onnx('model/cfg/mobilenetv2-yolo.cfg', weight_path)
  File "convert.py", line 57, in export_quant_to_onnx
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK
  File "/home/eleflea/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/eleflea/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/eleflea/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/eleflea/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/onnx/utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/eleflea/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/onnx/utils.py", line 137, in _optimize_graph
    torch._C._jit_pass_onnx_unpack_quantized_weights(graph, params_dict)
RuntimeError: getValues: Quantized weight value not found amongst constant parameters.
```

**Comment by supriyar** [comment]
@eleflea what layers does your model have? There is a test (see link below) which demonstrates the flow to be used to convert a model from pytorch -> onnx -> Caffe2. Right now caffe2 is the only backend supported for this flow. Also, it currently works for traced models.

https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_caffe2_quantized.py#L237

**Comment by ggeor84** [comment]
@supriyar Problem is that export is broken, we don't even get to generate a quantized onnx model

**Comment by houseroad** [comment]
@ggeor84 are you going to use Caffe2 as the backend? or you just need onnx model? If the latter, then this workflow probably wont' work for you.

**Comment by ggeor84** [comment]
@houseroad I just need the onnx model. I was looking to run it with onnxruntime

**Comment by supriyar** [comment]
We currently do not have any plans to support exporting pytorch quantized models to ONNX as part of the workflow. Please feel free to submit a feature request/PR if this is high priority for you.
