### ISSUE TITLE
How to save int value in ctx.save_for_backward

### ISSUE THREAD

**Issue by kuramawzw1** [pytorch/pytorch#31869]
I want to define a new memory  op,  and first impl  a new   memory function(torch.autograd.Function), but forward and backward are static method, 
and inputs have some int value for some config(like stride in conv function), ctx.save_for_backward can't save int value,   How to fix this problem?  

First, i want to follow torch.nn.conv1d example,  but i can't find any source for F.conv1d function?

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
