### ISSUE TITLE
torch.nn.quantized.functional.conv2d failed on CPU

### ISSUE THREAD

**Issue by parai** [pytorch/pytorch#31868]
## To Reproduce
I run the documented example code on CPU WSL 18.04 python3.6 torch==1.3.1
```python
from torch.nn.quantized import functional as qF
filters = torch.randn(8, 4, 3, 3, dtype=torch.float)
inputs = torch.randn(1, 4, 5, 5, dtype=torch.float)
bias = torch.randn(4, dtype=torch.float)

scale, zero_point = 1.0, 0
dtype = torch.quint8

q_filters = torch.quantize_per_tensor(filters, scale, zero_point, dtype)
q_inputs = torch.quantize_per_tensor(inputs, scale, zero_point, dtype)
qF.conv2d(q_inputs, q_filters, bias, scale=scale, zero_point=zero_point, padding=[1,1])
```
I got below error:
>>> qF.conv2d(q_inputs, q_filters, bias, scale=scale, zero_point=zero_point, padding=[1,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/nn/quantized/functional.py", line 115, in conv2d
    weight, bias, stride, padding, dilation, groups)
RuntimeError: expected scalar type QInt8 but found QUInt8 (data_ptr<c10::qint8> at /pytorch/aten/src/ATen/core/TensorMethods.h:5748)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f00dd77d813 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1ca5064 (0x7f00df884064 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x1ce86bf (0x7f00df8c76bf in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x1ceaa11 (0x7f00df8c9a11 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x31d9729 (0x7f00e0db8729 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x3e16013 (0x7f00e19f5013 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x4fe43c (0x7f0125f3243c in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x4ccda4 (0x7f0125f00da4 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x2110f4 (0x7f0125c450f4 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7f0134201b97 in /lib/x86_64-linux-gnu/libc.so.6)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by soumith** [comment]
> "RuntimeError: expected scalar type QInt8 but found QUInt8"

Check your code and change your dtype

**Comment by parai** [comment]
hi @soumith, you are not right.
First, this is documented code from page https://pytorch.org/docs/stable/quantization.html#module-torch.nn.quantized.functional
![image](https://user-images.githubusercontent.com/3183386/71816403-6cc4a400-30bd-11ea-95e1-9407f242111d.png)
Second, I have tried as you suggested, almost the same error, I think you need to reopen this issue and check it again.
```python
from torch.nn.quantized import functional as qF
filters = torch.randn(8, 4, 3, 3, dtype=torch.float)
inputs = torch.randn(1, 4, 5, 5, dtype=torch.float)
bias = torch.randn(8, dtype=torch.float)

scale, zero_point = 1.0, 0
dtype = torch.qint8

q_filters = torch.quantize_per_tensor(filters, scale, zero_point, dtype)
q_inputs = torch.quantize_per_tensor(inputs, scale, zero_point, dtype)
qF.conv2d(q_inputs, q_filters, bias, scale=scale, zero_point=zero_point, padding=[1,1])Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/nn/quantized/functional.py", line 119, in conv2d
    groups, scale, zero_point)
RuntimeError: expected scalar type QUInt8 but found QInt8 (data_ptr<c10::quint8> at /pytorch/aten/src/ATen/core/TensorMethods.h:5748)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f4052f2d813 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe88254 (0x7f4053fda254 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0xebf3b6 (0x7f40540113b6 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0xec1ea7 (0x7f4054013ea7 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x23bc699 (0x7f405550e699 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x2ff8f83 (0x7f405614af83 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x4c42fc (0x7f4060ad42fc in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x492c64 (0x7f4060aa2c64 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x1e76c4 (0x7f40607f76c4 in /home/parai/anaconda3/envs/ai3.6/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7f406ec01b97 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by soumith** [comment]
fair enough

**Comment by jerryzh168** [comment]
The example is incorrect, sorry for the confusion.
input dtype should be `quint8` and filter dtype should be `qint8` for the conv2d kernel.
cc @jlin27 could you fix the doc?

**Comment by jerryzh168** [comment]
the doc is already fixed in the code actually: https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/functional.py#L94-L105
we need to regenerate the doc I think.

**Comment by reuvenperetz** [comment]
> The example is incorrect, sorry for the confusion.
> input dtype should be `quint8` and filter dtype should be `qint8` for the conv2d kernel.
> cc @jlin27 could you fix the doc?

Hi,
I know it was a mistake at the doc, and that it was fixed, but I was wondering whether it's possible to use qint8 for the activation observer?
When I try different observers (e.g., histogram, min-max) with qint8, I get a similar error to what @parai got...

**Comment by supriyar** [comment]
@reuvenperetz most of the quantized operators expect the input type to be quint8. So you will run into issues at the op level when you try with qint8.
At this point we don't have plans to support operators with qint8 activations. Feel free to open a feature request if this is something you need and we will look into it. Thanks!
