### ISSUE TITLE
A pattern fuse or pattern replace tool for quantization.

### ISSUE THREAD

**Issue by neolinsu** [pytorch/pytorch#31872]
## 🚀 Feature
A handy method to fuse some specific layers in a exsiting model with preset patterns.

## Motivation

Some of layers (e.g. `DownSample`) may have not be supported in quantization computing yet.
Or some layers can be fused into other layers (e.g. `Relu` into 'Conv') for the better performance.
The current examples put the fusing responsibility in the model implementation [code](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#model-architecture),
which may not be handy in view of the possibility that *who quantizes the model may not the one implements the algorithm in the `model`*.

## Pitch

It may seems like [quant_tool](https://github.com/neolinsu/pytorch_quant_tool)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
Eager mode quantization requires many user modifications, including fusing models for better performance. We have graph mode quantization coming soon, which is much more automated and it will free users from worrying about these things.
Reason I don't think we need the fusion API is, we will probably always apply fusion if we want to get a better performance, so the only option we need for user is whether to apply fusion or not, and the tool can take care of figuring out where to apply fusions.

**Comment by parvizp** [comment]
@jerryzh168 Graph-mode quantization tooling is exciting, I noticed from your PR https://github.com/pytorch/pytorch/pull/26390 the `test_conv_bn` tests is disabled.
Can you share an estimate of when you think this might be considered "ready" for common vision models?

**Comment by jerryzh168** [comment]
@parvizp I just re-enables it few days ago: https://github.com/pytorch/pytorch/pull/29220
Ideally we should actually fuse ConvBn in the aten function level, but that requires more refactoring and cleanup, that's why we are doing it in the module level right now.
It is ready for common vision models as long as you can script it.

**Comment by z-a-f** [comment]
I don't think we will work on this feature, as this is needed only for eager, and in eager we were expecting the user to have the burden of fusion. @neolinsu  I am closing this feature request for now, however if there is a PR with this feature implemented, I will be happy to review it.
