### ISSUE TITLE
Pytorch not recognizing CUDA

### ISSUE THREAD

**Issue by WoozyDragon** [pytorch/pytorch#31876]
## Issue description

Pytorch is not recognizing CUDA despite correct version being installed.

## Code example

`nvcc --version`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
```

import torch
`torch.version.cuda`
    `'10.0'`

`torch.cuda.is_available()`
   `False`

## System Info
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 7 Professional
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7

Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce 210
Nvidia driver version: 342.01
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudn
n64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.2.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.0+cu92
[conda] Could not collect

**Comment by peterjc123** [comment]
GeForce 210 is not a supported card in our binary. Please build from source.
