### ISSUE TITLE
INT tensor with gradients

### ISSUE THREAD

**Issue by XHPlus** [pytorch/pytorch#31880]
## 🚀 Feature

We want to quantize the data to int8 to accelerate the training process.
However, PyTorch currently does not support a INT tensor with gradients.
If I execute the following code, there will be an error said "**RuntimeError: only Tensors of floating point dtype can require gradients**".
```
t = torch.randn(3)
int8_t = t.char()
int8_t.requires_grad = True
```

## Motivation

Our motivation is to utilize the INT tensor to accelerate the training process.

## Pitch

It would be helpful to support autograd and gradients for INT tensor.

**Comment by soumith** [comment]
please look at https://pytorch.org/docs/stable/quantization.html and the Quantization-aware training section.

**Comment by XHPlus** [comment]
It seems that the quantized tensor is mainly **for inference** and the quantization-aware training utilizes fake quant and the data flow with gradient is still in float format. The quantized tensor does not support autograd and requres_grad (The following code snippet still raises "**only Tensors of floating point dtype can require gradients**"). 
```
int_tensor = torch.randint(0, 10, size=((4,4,3,3)), dtype=torch.uint8)
scale, zero_point = 1e-1, 0
q = torch._make_per_tensor_quantized_tensor(int_tensor, scale, zero_point)
q.requires_grad = True
```

However, we want to directly use INT8 tensor with gradients rather than fake quant.
Then we can accelerate the forward process and save memory consumption **for training**.
I wonder that if it is possible to support autograd and requires_grad for INT tensor.

Thanks!

@soumith

**Comment by soumith** [comment]
> However, we want to directly use INT8 tensor with gradients rather than fake quant.

how do you compute gradients of an integer operation?

**Comment by XHPlus** [comment]
> > However, we want to directly use INT8 tensor with gradients rather than fake quant.
> 
> how do you compute gradients of an integer operation?

The integer operation follows the same pattern as floating-point operation to calculate gradients.
As for the round operation, we utilizes the STE (straight through estimator) to directly pass through the gradients.

**Comment by aabbas90** [comment]
@XHPlus : Were you able to fix the problem? I also have a custom torch autograd module with integer outputs and want to just pass the gradients during training. Thanks.

**Comment by XHPlus** [comment]
> @XHPlus : Were you able to fix the problem? I also have a custom torch autograd module with integer outputs and want to just pass the gradients during training. Thanks.

We have tried to directly ignore the check for integer outputs, and it can run. But we pend this work later.

**Comment by ken012git** [comment]
> > @XHPlus : Were you able to fix the problem? I also have a custom torch autograd module with integer outputs and want to just pass the gradients during training. Thanks.
> 
> We have tried to directly ignore the check for integer outputs, and it can run. But we pend this work later.

I have the same issue. How could I work this around? Thanks.

**Comment by chrpro** [comment]
What kind of learning rate you use ?
I mean even if you can estimate the gradients, how you compute the delta , e.g., if you combine something like:
loss.backward() # assume autograd pass 
optimizer.step() # then ?
the step will need to compute something like x += -learning_rate * x.grad 

How you deal with that?

**Comment by KPJoshi** [comment]
> We have tried to directly ignore the check for integer outputs, and it can run. But we pend this work later.
@XHPlus can you give steps for ignoring the check? Is it as simple as commenting out the check in your local torch install?

**Comment by webstorms** [comment]
Did anyone else manage to get this to work?
