### ISSUE TITLE
Issue like #22681 and #27976 may still exist in 3.1 debug distribution

### ISSUE THREAD

**Issue by mboedigh** [pytorch/pytorch#31891]
## 🐛 Bug

When using PyTorch1.3.1 c++ distribution in Visual Studio 2019 and following the dcgan.cpp example code a run-time exception is thrown while sending the nn::Sequential model to the cuda device.
I'm using CUDA 10.1

## To Reproduce

1. download PyTorch 1.3.1 c++ debug distribution and unzip to \torch_dir
2. download pytorch examples https://github.com/pytorch/examples.git
3. cd to cpp\dcgan example and configure project as suggested, using torch_dir\libtorch as the cmake_prefix_path
4. open configured solution ./dcgan.sln in VS 2019, select debug configuration and run to dcgan.cpp:line 74: (this automatically builds the solution)
` generator->to(device);`
5. debug -- step over-- and get exception similar to

Unhandled exception at 0x00007FF9B4F5A839 in dcgan.exe: Microsoft C++ exception: c10::Error at memory location 0x000000C645CFB5F0. occurred

## Expected behavior
output similar to that described in the example program documentation

## Environment 
Below is taken from collect.py, but note I have pytorch c++ distribution, pytorch from conda install, and pytorch I built from source yesterday). I ran the above cmake and collect.py from my conda environment, if that matters.
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Microsfot Windows 10 Pro
 - How you installed PyTorch (`conda`, `pip`, source): unzipped c++ distribution
 - Build command you used (if compiling from source): for dcgan project: 
      cmake -DCMAKE_PREFIX_PATH=c:\torch_dir\libtorch ..
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1.243
 - GPU models and configuration: GeForce GTX 1080
 - Any other relevant information:

## Additional context
None

**Comment by peterjc123** [comment]
Because the fixes didn't go in the 1.3.1 branch. You may have to try out the nightlies or wait for the 1.4.0 release.

**Comment by mboedigh** [comment]
Thanks. The fix is in 1.4.0 and the example the new DCGAN cpp example program runs fine. Thanks.
