### ISSUE TITLE
test_nn.py::test_upsampling_not_recompute_scale_factor differs from expected on Power

### ISSUE THREAD

**Issue by charleshofer** [pytorch/pytorch#31915]
## 🐛 Bug

When running `test_nn.py` the `test_upsampling_not_recompute_scale_factor` test case fails with an assertion error (pasted below) on [line 7031](https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L7301) complaining that the expected tensor is off by a bit. It's just outside the default precision of 1e-05, sitting at 1.57356e-05. I added a line to print out the actual result returned by `F.interpolate` and ran the test again. It looks like the 5th decimal place is off by about 1 or 2 on some elements. Here's the actual vs. the expected:

```
Expected:
tensor([[[[-0.32725, -0.08843, 0.37933, 0.79744],
          [0.15039, 0.38921, 0.85697, 1.27508],
          [1.08591, 1.32473, 1.79249, 2.21060],
          [1.92213, 2.16095, 2.62871, 3.04682]],

         [[3.67275, 3.91157, 4.37933, 4.79744],
          [4.15039, 4.38921, 4.85697, 5.27508],
          [5.08591, 5.32473, 5.79249, 6.21060],
          [5.92213, 6.16095, 6.62871, 7.04682]]]])

Actual:
tensor([[[[-0.32725, -0.08843,  0.37933,  0.79744],
          [ 0.15039,  0.38921,  0.85697,  1.27508],
          [ 1.08591,  1.32473,  1.79249,  2.21060],
          [ 1.92212,  2.16094,  2.62870,  3.04681]],

         [[ 3.67275,  3.91157,  4.37933,  4.79743],
          [ 4.15039,  4.38921,  4.85697,  5.27508],
          [ 5.08591,  5.32473,  5.79249,  6.21059],
          [ 5.92212,  6.16094,  6.62870,  7.04680]]]], dtype=torch.float32)
```
What do you guys advise to fix this? I'm not sure why exactly this differs on Power vs. whatever the expected was computed on (I assume x86), but lowering the precision from 1e-05 to 1e-04 [line 7301](https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L7301) using `assertEqual`'s `prec` argument makes the test case pass.

## To Reproduce
1. Install PyTorch from source using the master branch on Power 8 or 9
2. Run `test/test_nn.py`
3. Should see the following error in the output:

```
======================================================================
FAIL: test_upsampling_not_recompute_scale_factor (__main__.TestNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_nn.py", line 7301, in test_upsampling_not_recompute_scale_factor
    self.assertEqual(out_t, expected_out_t)
  File "/home/jenkins/pytorch_builder/ci/pytorch/test/common_utils.py", line 846, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/jenkins/pytorch_builder/ci/pytorch/test/common_utils.py", line 816, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.57356e-05, dtype=torch.float32) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```

## Expected behavior
The test case should pass

## Environment
PyTorch version: 1.4.0a0+0426bf4
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/powerpc64le-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0a0+0426bf4
[pip3] torchvision==0.5.0a0+44a5bae
[conda] torch                     1.4.0a0+0426bf4          pypi_0    pypi

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
Marking this as high-pri because there is a correctness issue. I'm not sure how good our support for POWER is though

**Comment by charleshofer** [comment]
I'm with IBM Power. If you guys suggest something we can look at to try and get this fixed, we're happy to look at it.

**Comment by charleshofer** [comment]
I ran the test input through OpenCV on Power, which gives the "incorrect" result that PyTorch is giving on Power. It looks like this is Power and x86 having slight differences in their floating point math and not something wrong with PyTorch. The differences are within plus or minus 0.00002. Could we just raise the tolerance on this test case?
