### ISSUE TITLE
Setting download = True on ImageNet does not raise required error.

### ISSUE THREAD

**Issue by AND2797** [pytorch/pytorch#31918]
## To Reproduce

```python
from torchvision import datasets, transforms
train_set = datasets.ImageNet('./data',train=True,download=True,
                                 transform = transforms.Compose([transforms.ToTensor()]))

test_set = datasets.ImageNet('./data',train=False,download=True,
                                 transform = transforms.Compose([transforms.ToTensor()]))
```

## Expected behavior
It should raise an error like so,
```
HTTPError: Not Found
```

However, as per documentation if `download` parameter is set to `True` then it should instead raise a different error. 
```python
if download is True:
    msg = ("The dataset is no longer publicly accessible. You need to "
                   "download the archives externally and place them in the root "
                   "directory.")
   raise RuntimeError(msg)
```

## Environment

```
PyTorch version: 1.3.1 [conda]
torchvision: 0.4.2 [conda]
Microsoft Windows 10 Home
Python version: 3.7
IDE: Spyder 4.0

```

## Additional context

https://pytorch.org/docs/stable/_modules/torchvision/datasets/imagenet.html#ImageNet

**Comment by albanD** [comment]
Hi,

You mean it raises the wrong error? This is most likely because you have an old version of torchvision.

I'm going to close this as this is not a pytorch problem but torchvision one and the correct error is raised on the latest version of torchvision.
