### ISSUE TITLE
torch.inverse can't export onnx

### ISSUE THREAD

**Issue by jingbanghu** [pytorch/pytorch#31914]
torch.inverse can't export onnx
a simple example like this:

import torch
import torchvision
import torchvision.transforms as transforms

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
    def forward(self,x):
                
        x = torch.inverse(x)
        return x
net = Net()

#input_names = [ "conv1" ,"conv2","fc1","fc2","fc3"]
input_names = [ "input"]
output_names = [ "output" ]
dummy_input = torch.randn(4, 1, 28, 28, device='cpu')
#print("FORWARD:",net(dummy_input))
print("FORWARD shape:",net(dummy_input).shape)
torch.onnx.export(net, dummy_input, "test.onnx", verbose=False,training=False,input_names=input_names, output_names=output_names,opset_version=11)

ERROR:
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:617: UserWarning: ONNX export failed on ATen operator inverse because torch.onnx.symbolic_opset11.inverse does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "testExport.py", line 30, in <module>
    torch.onnx.export(net, dummy_input, "mnist.onnx", verbose=False,training=False,input_names=input_names, output_names=output_names,opset_version=11)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py", line 92, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'inverse'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by jingbanghu** [comment]
it seem that i should not do inverse op at predict parse,should do it at C++ code

**Comment by lastsongforu** [comment]
I meet the same problem. my network also include torch.inverse(), how to process it?

**Comment by jingbanghu** [comment]
> I meet the same problem. my network also include torch.inverse(), how to process it?

u should do it at C++ code by yourself,not in the network

**Comment by shijianjian** [comment]
Why is this closed? Including this operator to ONNX shall be pretty useful.

**Comment by gigadeplex** [comment]
how to add this as a custom op?

**Comment by saiarthiraguram** [comment]
> how to add this as a custom op?

you can build from source  add this as a custom op, build the onnxruntime and get the .so file and run inference
