### ISSUE TITLE
processes of distributed with Gloo backend never join in a docker

### ISSUE THREAD

**Issue by tanguycdls** [pytorch/pytorch#31940]
Hi i'm trying to run a toy example of Pytorch distributed with a Gloo backend that runs in my local computer on a jupyter notebook hosted on Kubeflow (docker in Kubernetes ) and I cannot make it run. The script freezes on p.join() and never stops.

## To Reproduce

```
import os
import tempfile
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp
import datetime
from torch.multiprocessing import Process

from torch.nn.parallel import DistributedDataParallel as DDP
def run(rank, size):
    a=torch.tensor([rank])
    b=a**2

    tensor_list1 = [torch.zeros_like(b) for _ in range(size)]

    if rank==0:
        dist.gather(tensor=b,dst=0, gather_list=tensor_list1)
    else:
        dist.gather(tensor=b, dst=0)

    print('Rank ', rank, 'b: ', tensor_list1)

def init_processes(rank, size, fn, backend='gloo'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group(backend, rank=rank, world_size=size)
    fn(rank, size)


if __name__ == "__main__":
    size = 4
    processes = []
    for rank in range(size):
        p = Process(target=init_processes, args=(rank, size, run))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
```

The script creates the 4 processes but never ends, if I do a ctrl + c i can see its waiting on p.join(). All the other processes are suspended. I tried modifying the port to a lower number and the ip to localhost but nothing changes. I also tried using a file instead to share data but the problem is the same. 

Sometimes I get that error instead:
```
RuntimeError: [/opt/conda/conda-bld/pytorch_1573049304260/work/third_party/gloo/gloo/transport/tcp/pair.cc:563] Read error [***********]:17795: Connection reset by peer
````

## Environment
```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Debian GNU/Linux 9 (stretch)
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.1
[conda] _tflow_select             2.3.0                       mkl  
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] tensorflow                2.0.0           mkl_py36hef7ec59_0  
[conda] tensorflow-base           2.0.0           mkl_py36h9204916_0
```
## Additional context

I'm in a jupyter in Kubeflow (opened an issue there as well https://github.com/kubeflow/kubeflow/issues/4627). I tried using file instead of a a tcp port to init_process_group but the bug is still present and the processes never stops. 

* How can i increase the verbose of Gloo so that I can debug it ? 

Thanks, 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by pietern** [comment]
Does your script hang at `init_process_group`?

You can pass a `timeout` kwarg to that function to make it fail faster. The default timeout is set quite high to 30 minutes.

**Comment by tanguycdls** [comment]
The script hanged at the join, i cannot check where the parallel processes that freezes actually hang.. 

I found the solution: the network interface chosen by GLOO was not the correct one. I fixed it using:
``GLOO_SOCKET_IFNAME="lo"``

I dont understand why eth0 was used instead of loop the master addr was localhost so it should be set automatically. 

Thanks

**Comment by pritamdamania87** [comment]
Closing this out since it looks like we have a solution here.
