### ISSUE TITLE
Strange memory behavior when moving module to cuda

### ISSUE THREAD

**Issue by francoishernandez** [pytorch/pytorch#31947]
## 🐛 Bug

It seems memory is not freed (from either RAM or GPU RAM) when deleting a module that has been moved `.to("cuda")`, whereas it works when explicitly deleting each of the module parameters.

## To Reproduce
1. Seems to work fine with a single tensor

| Command | RAM | GPU RAM |
| -------------- | ------ | -------------- |
| `t = torch.randn((8192, 8192))` | 427M | N/A |
| `u = t.to("cuda")` | 1981M | 817M |
| `del t` | 1725M | 817M |
| `del u` | 1725M | 817M |
| `torch.cuda.empty_cache()` | 1725M | 561M |
| ... | ... | ... |

(I assume these 1725M in RAM and 561M on GPU are just the cuda overheads.)

2. Starts to look shady with a module

 | Command | RAM | GPU RAM |
| -------------- | ------ | -------------- |
| `m = torch.nn.Linear(8192, 8192)` | 428M | N/A |
| `m.to("cuda")` | 1726M | 819M |
| `del m` | 1726M | 819M |
| `torch.cuda.empty_cache()` | 1726M | 819M |
| `m = torch.nn.Linear(8192, 8192)` | 1982M | 819M |
|  `m.to("cuda")` | 1726M | 1075M |
| `del m` | 1726M | 1075M |
| `torch.cuda.empty_cache()` | 1726M | 1075M |
| ... | ... | ... |

3. It seems to work when explicitly deleting module parameters before

 | Command | RAM | GPU RAM |
| -------------- | ------ | -------------- |
| `m = torch.nn.Linear(8192, 8192)` | 427M | N/A |
| `m.to("cuda")` | 1726M | 819M |
| `del m.weight` | 1726M | 563M |
| `torch.cuda.empty_cache()` | 1726M | 819M |
| `del m.bias` | 1726M | 563M |
| `torch.cuda.empty_cache()` | 1726M | 561M |
| ... | ... | ... |

4. On CPU only it also seems to work properly

 | Command | RAM | GPU RAM |
| -------------- | ------ | -------------- |
| `import torch` | 170M | N/A |
| `m = torch.nn.Linear(8192, 8192)` | 427M | N/A |
| `del m` | 171M | N/A |
| ... | ... | ... |

## Expected behavior

`del m` followed by `torch.cuda.empty_cache()` should have the same effect as deleting the parameters explicitly.

## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 435.21
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.1
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2

## Additional context

This issue was stumbled upon when debugging for [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) REST server, where we might build some modules and delete them when unloading, and then reload it later, etc.
cc @ezyang @gchanan @zou3519 @ngimel @vince62s

**Comment by zou3519** [comment]
I'm not well-versed in the behavior of our CUDA caching allocator, but these do look like memory leaks to me so I am marking this high-pri for investigation

**Comment by ezyang** [comment]
You're typing this into an ipython interpreter, I bet? ipython is retaining a reference to `m` even though you've deleted it. If you do `%xdel m` you won't leak anymore.

**Comment by francoishernandez** [comment]
Made sure to test both ipython and raw python shell, which has the same behaviour. But indeed via a script it releases the memory properly.
