### ISSUE TITLE
Device Object doesn't work as JIT annotation in PY3

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#31950]
## 🐛 Bug

There is no `Device` object that is exposed in the pytorch namespace. It is defined in `torch/__init__.pyi.in` so PY2 style comments work, but PY3 style comments fail. 

Works:
```
@torch.jit.script
def fn(m):
    # type: (Tensor) -> Device
    return m.device
```

Doesn't work:

```
@torch.jit.script
def fn(m: Tensor) -> torch.Device:
    return m.device
```
> Traceback (most recent call last):
  File "test/test_jit.py", line 5197, in test_elias
    from torch import Device
ImportError: cannot import name 'Device' from 'torch' (/home/eellison/anaconda3/lib/python3.7/site-packages/torch/__init__.py)

cc @suo

**Comment by driazati** [comment]
Finishing up #29623 should also fix this, I'll try to polish it up today

**Comment by eellison** [comment]
@driazati I don't think the object exists in python, so it's related but somewhat tangential. I updated the example above. You get a python error not a TorchScript error.

**Comment by driazati** [comment]
It's supposed to be `torch.device`
