### ISSUE TITLE
PyTorch throws an exception on import when denormals are flushed to zero

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#3195]
This happens, for example, when you import DyNet before importing PyTorch. The code from #3113 tries to take the log(0) which throws an exception.

My guess is that DyNet is setting FTZ or DAZ (or both). See:
https://software.intel.com/en-us/node/523328

**Comment by colesbury** [comment]
cc @SsnL

**Comment by SsnL** [comment]
I plan to look into this after dealing with the sparse stuff. How urgent is this?

**Comment by ezyang** [comment]
Since it seems easy to work around, it doesn't sound super urgent to me.

**Comment by colesbury** [comment]
We need to fix this before the next release, but it can definitely wait until after the sparse stuff

There's an easy fix: just replace the computation in `__MIN_LOG_SCALE` with `-323`. The minimum denormalized number for IEEE float64s is unlikely to change.
