### ISSUE TITLE
torch.expand() bug

### ISSUE THREAD

**Issue by isaykatsman** [pytorch/pytorch#3196]
Literally try the example from docs to repro:

```
x = torch.Tensor([[1], [2], [3]])
x.expand(-1, 4)
```

Trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: The expanded size of the tensor (-1) must match the existing size (3) at non-singleton dimension 0. at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/generic/THTensor.c:308
```

Same thing happens when you try to expand along any other dimension that isn't 0.

**Comment by fmassa** [comment]
Can you print `torch.__version__`? It works on my version (compiled from master a few weeks ago, `0.2.0+6a800be`).

**Comment by rajathkmp** [comment]
I am facing the same issue

**Comment by isaykatsman** [comment]
@fmassa Anyone that installs from the website with `conda install pytorch torchvision cuda80 -c soumith` (maybe even other installations) will currently face this issue. The version is `0.2.0_4`.

**Comment by rajathkmp** [comment]
@isaykatsman any workaround?

**Comment by isaykatsman** [comment]
@rajathkmp This is janky, but you can essentially use a list comprehension to construct a tuple and then pass that to cat. For example expanding along dimension 1 (of size 1) to size `stack_size`:

```
torch.cat(tuple([x for i in range(stack_size)]), 1)
```

**Comment by apaszke** [comment]
@isaykatsman wouldn't `x.expand(x.size(0), 4)` work? It seems that support for `-1` in expand has been merged after the newest binaries have been publised

**Comment by isaykatsman** [comment]
@apaszke Expanding along dimension 0 was never an issue. For other dimension you would get the same error message. But let's hope all that's fixed in the newest binaries, in which case we can close this entire issue

**Comment by albanD** [comment]
@isaykatsman the documentation for the version you're running (0.2.0) does not contain this example: [here](http://pytorch.org/docs/0.2.0/tensors.html?highlight=expand#torch.Tensor.expand).
You were looking at the documentation corresponding to the master branch.

**Comment by isaykatsman** [comment]
@albanD I suppose so. I guess we'll wait for changes to from 0.2.0+ to make it to 0.2.0_.
