### ISSUE TITLE
[libtorch, jit] Unexpected right-hand found in assignment in class body. This is not yet supported.

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31960]
## 🐛 Bug

Originally found by @peastman at https://github.com/aiqm/torchani/issues/407 and thanks for @peastman's minimal C++ script.

Libtorch is unable to load jit module with `Final` fields while Python `torch.jit.load` can.

## To Reproduce

Python:

```python
import torch
from torch.jit import Final
print(torch.__version__)

class Model(torch.nn.Module):
    a: Final[int]

    def __init__(self):
        super().__init__()
        self.a = 5

    def forward(self, x):
        return x

m = torch.jit.script(Model())
torch.jit.save(m, 'model.pt')
torch.jit.load('model.pt')
```

C++
```c++
#include <torch/script.h>

int main() {
    torch::jit::load("model.pt");
    return 0;
}
```

The python code runs successfully, but the C++ code fails with

```
terminate called after throwing an instance of 'torch::jit::script::ErrorReport'
  what():  
Unexpected right-hand found in assignment in class body. This is not yet supported.:
Serialized   File "code/__torch__.py", line 4
  __parameters__ = []
  training : bool
  a : Final[int] = 5
                   ~ <--- HERE
  def forward(self: __torch__.Model,
    x: Tensor) -> Tensor:

Aborted (core dumped)
```

## Expected behavior

Both python and libtorch succeeds.

cc @suo

**Comment by zasdfgbnm** [comment]
As @peastman found, `Linear` is also broken:

```python
import torch
print(torch.__version__)

m = torch.jit.script(torch.nn.Linear(10, 10))
torch.jit.save(m, 'model.pt')
torch.jit.load('model.pt')
```

**Comment by suo** [comment]
cc @driazati for Final constant handling

**Comment by driazati** [comment]
Something is broken in our nightly build, this works fine on master but is reproduces in the nightly libtorch.

**Comment by yf225** [comment]
@driazati libtorch nightly builds should be back working again. Would you like to check it?

**Comment by driazati** [comment]
Looks like it's working properly now, thanks!

@zasdfgbnm feel free to re-open if you're still running into problems

**Comment by peastman** [comment]
I also confirmed that it works correctly with the latest nightly build.  Thank you!

**Comment by Yasin40** [comment]
I have same problem, but not worked with last nightly version.
https://github.com/pytorch/vision/issues/4271

**Comment by Yasin40** [comment]
I have same problem, but not worked with last nightly version.
https://github.com/pytorch/vision/issues/4271
