### ISSUE TITLE
test_c10d.test_allgather_ops is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#31977]
## 🐛 Bug

See failure: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/12946/console

```
02:17:18 test_allgather_ops (__main__.ProcessGroupNCCLTest) ... Memory access fault by GPU node-7 (Agent handle: 0x3e06190) on address (nil). Reason: Page not present or supervisor privilege.
02:17:33 Traceback (most recent call last):
02:17:33   File "test/run_test.py", line 456, in <module>
02:17:33     main()
02:17:33   File "test/run_test.py", line 449, in main
02:17:33     raise RuntimeError(message)
02:17:33 RuntimeError: test_c10d failed! Received signal: SIGIOT
02:17:34 + cleanup
02:17:34 + retcode=1
02:17:34 + set +x
```
It might me ROCm specific, since it does not seemed to have failed on any other jobs.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by mruberry** [comment]
Closing as this no longer appears to be happening.
