### ISSUE TITLE
self.modules() results in infinite recursion

### ISSUE THREAD

**Issue by ludwigwinkler** [pytorch/pytorch#31986]
The idea is supposed to be to recursively reset the parameters of all the modules (Linear, Conv etc) in the current module (the main network i.e. a CNN).

That way reseting the parameters would be a one-liner and autograd and the optimizer would still track the right arrays (when checking for 'id(parameterxyz)'.

I am aware that one can use the 'apply()' function but I thought this might be a bug.
```
from torch.nn import Sequential, Conv2d, ConvTranspose2d, LayerNorm, Linear, BatchNorm1d, MaxPool2d

class CNN(torch.nn.Module):
	def __init__(self):
		super(CNN, self).__init__()

		self.conv1          = Conv2d(1, 32, kernel_size=5)
		self.pool           = MaxPool2d(2, 2)
		self.conv2          = Conv2d(32, 32, kernel_size=5)
		self.fc1            = Linear(512, 256)
		self.fc2            = Linear(256, 10)

       def reset_parameters(self):
		for module in self.modules():
			module.reset_parameters()

	def forward(self, x):
		x = self.pool(F.relu(self.conv1(x)))
		x = self.pool(F.relu(self.conv2(x)))
		x = x.view(x.size(0), -1)
		x = F.relu(self.fc1(x))
		x = self.fc2(x)
		return x

model = CNN()
model.reset_parameters()
```

 - PyTorch Version : 1.3.1
 - OS (e.g., Linux): Mac

PS: Sorry for the format ... somehow I'm not succeeding at making the code format work
(EDIT: fixed)

**Comment by zou3519** [comment]
According to the [example in the documentation](https://pytorch.org/docs/master/nn.html#torch.nn.Module.modules), this is expected behavior. It sounds like you were looking for `self.children()`:

```
def reset_parameters(self):
    for module in self.children():
         module.reset_parameters()
```

I am going to classify this as a documentation issue because I think our documentation could better state that `modules()` includes `self`. Would you be interested in submitting a doc fix, @ludwigwinkler?

**Comment by ludwigwinkler** [comment]
Yeah, I can submit a doc fix. Thanks a lot for the clarification.
