### ISSUE TITLE
Number of Workers and batch size multiplication problem

### ISSUE THREAD

**Issue by artest08** [pytorch/pytorch#31988]
Hello,

I am trying to train with 4 V100 GPU. What I have observe is that when the multiplication of batch size with number of workers exceeds some limit, I get the following error below. I cannot understand what is the limiting fact. One reason can be the RAM size because the system gives me a warning that swap + memory has exceeds the limits at least one even if the code does not stop because of the error specified below. Or is it the memory limit in GPU? Thanx in advance for your help. 

I am using,
Torch 1.1.0,
Cuda9.0

If you need further package details, I can provide. 
Thanx in advance

Traceback (most recent call last):
  File "two_stream_bert.py", line 713, in <module>
    main()
  File "two_stream_bert.py", line 297, in main
    train(train_loader, model, criterion,criterion2, optimizer, epoch,setMseCoeff,modality)
  File "two_stream_bert.py", line 451, in train
    output, input_vectors, sequenceOut, maskSample = model(inputs)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x2ad6b175f441 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x2ad6b175ed7a in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x1581d (0x2ad6b381481d in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x16247 (0x2ad6b3815247 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::TensorOptions const&) + 0x121 (0x2ad674e42f81 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: at::CUDAType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x19b (0x2ad673a8a6fb in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #6: torch::autograd::VariableType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x284 (0x2ad6b2522094 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) + 0x506 (0x2ad6a7b67666 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #8: at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x17 (0x2ad6a7de6857 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #9: torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x2c2 (0x2ad6b240bb52 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #10: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<c10::cuda::CUDAStream>, std::allocator<c10::optional<c10::cuda::CUDAStream> > > > const&) + 0x389 (0x2ad6b295ffd9 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #11: <unknown function> + 0x5a27bf (0x2ad6720a27bf in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x130cfc (0x2ad671c30cfc in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #13: _PyCFunction_FastCallDict + 0x154 (0x2ad6591c0b94 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #14: <unknown function> + 0x19e67c (0x2ad65925067c in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #16: <unknown function> + 0x197a94 (0x2ad659249a94 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #17: <unknown function> + 0x198941 (0x2ad65924a941 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #18: <unknown function> + 0x19e755 (0x2ad659250755 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #20: PyEval_EvalCodeEx + 0x329 (0x2ad65924b459 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #21: <unknown function> + 0x19a264 (0x2ad65924c264 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #22: PyObject_Call + 0x3e (0x2ad6591c099e in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #23: THPFunction_apply(_object*, _object*) + 0x6b1 (0x2ad671eb3481 in /truba/home/mkalfaoglu/anaconda3/envs/master/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #24: _PyCFunction_FastCallDict + 0x91 (0x2ad6591c0ad1 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #25: <unknown function> + 0x19e67c (0x2ad65925067c in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #27: <unknown function> + 0x197dae (0x2ad659249dae in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #28: _PyFunction_FastCallDict + 0x1bb (0x2ad65924ae1b in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #29: _PyObject_FastCallDict + 0x26f (0x2ad6591c0f5f in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #30: <unknown function> + 0x12a552 (0x2ad6591dc552 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #31: PyIter_Next + 0xe (0x2ad659205c9e in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #32: PySequence_Tuple + 0xf9 (0x2ad65920aad9 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x563a (0x2ad659277ffa in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #34: <unknown function> + 0x197dae (0x2ad659249dae in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #35: <unknown function> + 0x198941 (0x2ad65924a941 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #36: <unknown function> + 0x19e755 (0x2ad659250755 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #38: <unknown function> + 0x197dae (0x2ad659249dae in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #39: <unknown function> + 0x198941 (0x2ad65924a941 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #40: <unknown function> + 0x19e755 (0x2ad659250755 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #42: <unknown function> + 0x197a94 (0x2ad659249a94 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #43: <unknown function> + 0x198941 (0x2ad65924a941 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #44: <unknown function> + 0x19e755 (0x2ad659250755 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x10ba (0x2ad659273a7a in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #46: <unknown function> + 0x19870b (0x2ad65924a70b in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #47: <unknown function> + 0x19e755 (0x2ad659250755 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #49: <unknown function> + 0x197a94 (0x2ad659249a94 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #50: _PyFunction_FastCallDict + 0x3db (0x2ad65924b03b in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #51: _PyObject_FastCallDict + 0x26f (0x2ad6591c0f5f in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #52: _PyObject_Call_Prepend + 0x63 (0x2ad6591c5a03 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #53: PyObject_Call + 0x3e (0x2ad6591c099e in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #54: _PyEval_EvalFrameDefault + 0x1ab0 (0x2ad659274470 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #55: <unknown function> + 0x197a94 (0x2ad659249a94 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #56: _PyFunction_FastCallDict + 0x1bb (0x2ad65924ae1b in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #57: _PyObject_FastCallDict + 0x26f (0x2ad6591c0f5f in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #58: _PyObject_Call_Prepend + 0x63 (0x2ad6591c5a03 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #59: PyObject_Call + 0x3e (0x2ad6591c099e in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #60: <unknown function> + 0x16b9b7 (0x2ad65921d9b7 in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #61: _PyObject_FastCallDict + 0x8b (0x2ad6591c0d7b in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #62: <unknown function> + 0x19e7ce (0x2ad6592507ce in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)
frame #63: _PyEval_EvalFrameDefault + 0x2fa (0x2ad659272cba in /truba/home/mkalfaoglu/anaconda3/envs/master/bin/python)

cc @ngimel

**Comment by zou3519** [comment]
> RuntimeError: CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)

It says CUDA out of memory
