### ISSUE TITLE
repeat_interleave Performance Issue

### ISSUE THREAD

**Issue by Rick-McCoy** [pytorch/pytorch#31980]
## 🐛 Bug

repeat_interleave is ~3.5x slower compared to other equivalent methods.

## To Reproduce

```
import torch
import timeit
timeit.timeit('torch.randn(10000).repeat_interleave(100, -1)', 'import torch', number=100)
timeit.timeit('torch.randn(10000)[..., None].expand(-1, 100).flatten(-2, -1)', 'import torch', number=100)
```

Outputs: 

```
0.37211750000000166
0.10460659999995414
```

## Expected behavior

Tensor.repeat_interleave is equivalent to Tensor.expand().flatten().
The execution time should be within acceptable bounds, and yet the performance difference is quite drastic.

## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.16.4

[pip3] pytorch-lightning==0.5.3.2

[pip3] torch==1.3.1

[pip3] torchvision==0.4.2
[conda] Could not collect

cc @VitalyFedyunin @ngimel @gchanan @mruberry

**Comment by zou3519** [comment]
Thank you for the repro and the baseline, @Rick-McCoy. I agree that we can make repeat_interleave faster

**Comment by AndrewZinc** [comment]
I'd like to work on this issue.

**Comment by AndrewZinc** [comment]
Sure 😀On May 30, 2023, at 11:47, Brandon Tong ***@***.***> wrote:﻿
Hi, can I give this a go?

**Comment by grazder** [comment]
i have the same problem on torch == 1.13 and cpu

```
self.erb_indices = torch.tensor([
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 7, 7, 8, 
    10, 12, 13, 15, 18, 20, 24, 28, 31, 37, 42, 50, 56, 67
])
gains = torch.randn(32)
```
this is much slower
```
gains = torch.repeat_interleave(gains, self.erb_indices)
```
than this
```
gains = torch.cat([x.repeat(num_x) for x, num_x in zip(gains, self.erb_indices)])
```

**Comment by vadimkantorov** [comment]
@ezyang btw I wonder, does repeat/repeat_interleave with fixed static repeat pattern compile into something unrolled and nice by inductor?

**Comment by lezcano** [comment]
Regarding the OP, in my machine I get
```
>>> timeit.timeit('torch.randn(10000).repeat_interleave(100, -1)', 'import torch', number=100)
0.01837850920855999
>>> timeit.timeit('torch.randn(10000)[..., None].expand(-1, 100).flatten(-2, -1)', 'import torch', number=100)
0.013084527105093002
```
which is slower, but not much slower really.

That being said, it makes sense to me to simply implement `repeat_interleave` in terms of expand + flatten, as flatten is implemented in terms of clone, and clone is well optimised.

**Comment by ezyang** [comment]
Yeah, will happily take fast path proposals if someone wants to send them in.

**Comment by b0noI** [comment]
I might be missing something but it does look like, at least for the following implementation it is already done in terms of expand + flatten:

https://github.com/pytorch/pytorch/blob/ad9a27f3e5b1d2b69b2b078663d556e51f7a9daf/aten/src/ATen/native/Repeat.cpp#L113
