### ISSUE TITLE
what should i do to disable libcaffe2_nvrtc.so

### ISSUE THREAD

**Issue by HardLaugh** [pytorch/pytorch#31985]
I find that executable file must link against libcaffe2_nvrtc.so，but I dont want to link against it due to my projects, I need  pure executable file without anything  .so about torch, so I build static torch libs and unfortunately  libcaffe2_nvrtc.so stoped me

the question is about CUDAHooks.cpp
```
static std::pair<std::unique_ptr<at::DynamicLibrary>, at::cuda::NVRTC*> load_nvrtc() {
#if defined(_WIN32)
  std::string libcaffe2_nvrtc = "caffe2_nvrtc.dll";
#elif defined(__APPLE__)
  std::string libcaffe2_nvrtc = "libcaffe2_nvrtc.dylib";
#else
  std::string libcaffe2_nvrtc = "libcaffe2_nvrtc.so";
#endif
  std::unique_ptr<at::DynamicLibrary> libnvrtc_stub(
      new at::DynamicLibrary(libcaffe2_nvrtc.c_str()));
  auto fn = (at::cuda::NVRTC * (*)()) libnvrtc_stub->sym("load_nvrtc");
  return std::make_pair(std::move(libnvrtc_stub), fn());
}
```
and the errors is :
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory
The above operation failed in interpreter, with the following stack trace:
```

cc @ngimel

**Comment by zou3519** [comment]
I'm not following what "pure executable file without anything .so about torch" means, could you please clarify?

**Comment by HardLaugh** [comment]
@zou3519 If the system environment changes, which only install mkl and cuda,  however, executable file cannot run because it need the shared libs--libcaffe2_nvrtc.so
```
linux-vdso.so.1 =>  (0x00007ffd2d8a1000)
        libmkl_intel_lp64.so => /home/46799/anaconda3/envs/eptorch/lib/libmkl_intel_lp64.so (0x00007f1360261000)
        libmkl_gnu_thread.so => /home/46799/anaconda3/envs/eptorch/lib/libmkl_gnu_thread.so (0x00007f135eb4e000)
        libmkl_core.so => /home/46799/anaconda3/envs/eptorch/lib/libmkl_core.so (0x00007f135ab45000)
        libgomp.so.1 => /home/46799/anaconda3/envs/eptorch/lib/libgomp.so.1 (0x00007f135ab17000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f135a8da000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f135a6d2000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f135a4cd000)
        libstdc++.so.6 => /home/46799/anaconda3/envs/eptorch/lib/libstdc++.so.6 (0x00007f135a193000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1359e8d000)
        libgcc_s.so.1 => /home/46799/anaconda3/envs/eptorch/lib/libgcc_s.so.1 (0x00007f1359e78000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1359aaf000)
        /lib64/ld-linux-x86-64.so.2 (0x000055866a236000)
```

**Comment by wahlberg82** [comment]
I'm in the same situation. I'm building a plugin for a commercial host application. This plugin, which is in the form of a shared library (.so file), is statically linking libtorch (i.e. it's baking all of it into it's own so file). The only libraries that are dynamically linked against are the CUDA libs. This plugin needs to be portable to other systems without the need to install lots of dependencies (CUDA is fine to be needed as an additional install). Everything works, except I can't get my shared library to not also need the torch library "libcaffe2_nvrtc.so". Since it doesn't exist a static version of this library "libcaffe2_nvrtc.a", I can't seem to get around it. Is there a way to not have libtorch dynamically depend on this library and still have GPU support? I can build libtorch with CPU support only, and then I don't have the problem, but I need the GPU accelleration.
Cheers, David

**Comment by yeoserene** [comment]
I am having the same problem as @wahlberg82. Running my executable with CPU only doesn't spawn any problems, but trying to run it with GPU after compilation gives: "Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory". I also need this as a standalone that can run perfectly by itself.

**Comment by paklau99988** [comment]
Is have same problem. Hoe make static link libtorch?

**Comment by malfet** [comment]
PR against master should address the issue (although your application will still have dynamic dependency on NVRTC library)

**Comment by wahlberg82** [comment]
I did a pull of the nightly master yesterday and recompiled statically. I can confirm that this fix is working well and solving the issue. Thanks all for fixing this so quickly and being such a great community!
Cheers, Davd
