### ISSUE TITLE
[Segmentation Fault] torch.max gives a seg fault for a CPU input tensor and CUDA out tensors

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#32001]
## 🐛 Bug

torch.max gives a segmentation fault when the device types of the input tensor has a CPU device type and one or both of the out tensors(values, indices) are CUDA tensors.  

## To Reproduce

>>> import torch
>>> a=torch.randn(10)
>>> values=torch.randn(10).cuda()
>>> indices=torch.LongTensor().cuda()
>>> torch.max(a, 0, out=(values, indices))

Segmentation fault (core dumped)
## Expected behavior

Ideally, there should be a RuntimeError with a clear error message that max is not supported for input and out tensors with different device type

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.5.0a0+ce3e151
Is debug build: Yes
CUDA used to build PyTorch: 9.2

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 396.69
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.1.2

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.5.0a0+ce3e151
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] torch                     1.5.0a0+ce3e151           dev_0    <develop>
[conda] torchvision               0.4.2                    pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by anjali411** [comment]
However, when the input tensor is a cuda tensor and out tensors are cpu tensors, then there's a RunTime error with proper error message:

>>> import torch
>>> x=torch.randn(10).cuda()
>>> values=torch.randn(10)
>>> indices=torch.LongTensor()
>>> torch.max(x, 0, out=(values, indices))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of device type cuda but got device type cpu for argument #0 'max' in call to _th_max_out

**Comment by ezyang** [comment]
There need to be tests in the CUDA kernels that all inputs are CUDA.

**Comment by Baranowski** [comment]
This will require first migrating `max` and `min` to ATen (https://github.com/pytorch/pytorch/issues/24594 and https://github.com/pytorch/pytorch/issues/24595).

@ezyang If my intuition about meaning of the `high priority` label is correct, this might warrant re-triaging those two issues or lowering the priority on this one.

**Comment by ezyang** [comment]
Although I agree migrating max/min to ATen would solve the problem, I am not sure I would conclude it's the only way to fix this problem. The next thing I'd check is: are all other TH functions affected in a similar way? If every TH function (not just torch.max) is affected, that points at a bug in the automatic checked casts we do when moving from ATen to TH land.

**Comment by Baranowski** [comment]
Good point. I only checked min/max vs. a couple ATen operators. I will test and report back.

**Comment by Baranowski** [comment]
Actually the problem is not the max CUDA kernel. The problem is that the call is dispatched to the CPU kernel which crashes. I will continue working on this.

As for the other TH CUDA ops, I have verified that `remainder` and `cumsum` throw a `RuntimeError` when they get CPU operands and CUDA output.
