### ISSUE TITLE
Tutorials should be run in CI

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#32004]
I was attempting to run https://pytorch.org/tutorials/advanced/cpp_frontend.html on master but it didn't work, because the cmake is out of date: it needed to be `CXX_STANDARD 14` now that we are C++14.

This should have been caught in CI for the change that made us C++14. The problem is that we are not running the tutorial examples in CI. We should do so.

cc @ezyang @gchanan @zou3519

**Comment by zhangguanheng66** [comment]
Agree. After the release of 1.3, the tutorial for transformer was broken. Batter to catch those errors before the release.

**Comment by ezyang** [comment]
One thing to be careful about is some of the tutorials may take a long time to run, if they involve actually training a model.

**Comment by ezyang** [comment]
gchanan says that we should run this on every PR, because otherwise you have to do a scramble at release time to update the tutorials.

**Comment by brianjo** [comment]
If we could get this script working we could add CI to the examples repo to test PRs like we do with tutorials. https://github.com/pytorch/examples/blob/master/run_python_examples.sh  I'll try to debug if I get a chance, but if somebody can do it faster that would be great. I see this error:
```
./run_python_examples.sh: 30: ./run_python_examples.sh: Syntax error: "(" unexpected
```
on Ubuntu. 
On my mac I get this: 
```
Some examples failed:

dcgan failed
imagenet example failed
mnist hogwild failed
reinforcement learning failed
couldn't download 'en' model needed for snli
```

**Comment by jlin27** [comment]
@brianjo - Currently the very first line of run_python_examples.sh is `#!/bin/sh` but if you change it to `#!/bin/bash` it should run and get the same example fails as what you posted that you see on the mac. ([Details](https://unix.stackexchange.com/a/45784) on why that syntax error is removed by changing the bang line)

**Comment by mattip** [comment]
@jlin27 will you be turning your experiments into a PR?

**Comment by ezyang** [comment]
BTW, the discussion on this issue has been about `pytorch/examples`, but we also should test `pytorch/tutorials`. Tutorials is substantially more involved, since these are basically unstructured rst files, and we need to come up with some system for transforming these into executable programs. Perhaps the best thing to do is to restructure the code so that it lives in an executable repo (like pytorch/examples), and then directly transclude the code into the tutorial.

**Comment by mattip** [comment]
xref pytorch/examples#798 which now runs examples via CI (github actions).

**Comment by mattip** [comment]
The tutorials repo has [CI](https://github.com/pytorch/tutorials/blob/master/.circleci/config.yml) that builds the [website](https://pytorch.org/tutorials). How did the original error slip through?

**Comment by brianjo** [comment]
> The tutorials repo has [CI](https://github.com/pytorch/tutorials/blob/master/.circleci/config.yml) that builds the [website](https://pytorch.org/tutorials). How did the original error slip through?

That tutorial (Using the PyTorch C++ Frontend) is an [rst file](https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_frontend.rst). These don't get built by the CI.

**Comment by mattip** [comment]
The tutorial refers to code (in the [conclusion](https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_frontend.rst#conclusion)) from the examples repo, so now that there is CI for the examples that particular instance of the general principle should be covered. With that, I think there may be some value to reducing the copy-paste of code into the tutorial RST files. Maybe if we moved to using [`.. literalinclude::`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) instead the tutorial would always be in sync with the code. That is made harder by the fact that the tutorials and examples live in different repos, but certainly for other tutorials it would be feasible to refactor.

Also, note that the CI for the examples (and tutorials) repo is triggered only on merging PRs to that repo. I wonder if there is a way to trigger it on merging a PR to the main pytorch repo as well, or via a cron job. If we did that, who would see the CI failure when something broke?

**Comment by ezyang** [comment]
> Also, note that the CI for the examples (and tutorials) repo is triggered only on merging PRs to that repo. I wonder if there is a way to trigger it on merging a PR to the main pytorch repo as well, or via a cron job. If we did that, who would see the CI failure when something broke?

The "easiest" way to do this is have PyTorch CI check out a specific hash of example/tutorials repo and then run the test that way. We would then need to occasionally update this hash as new changes are landed to examples.

**Comment by mattip** [comment]
I think it is too much to run pytorch/example CI on every pytorch/pytorch PR push or merge. What would you think of this strategy:
- Run the CI on pytorch/examples on a daily cron trigger
- If it fails open a new issue in that repo, we could use something like this github action https://github.com/rishabhgupta/git-action-issue.

**Comment by brianjo** [comment]
I think that's a great idea. Once a day is plenty and opening an issue on a failure would get somebody's attention.

**Comment by mattip** [comment]
xref pytorch/examples#811

**Comment by mattip** [comment]
Examples are being [run now](https://github.com/pytorch/examples/actions) once a day with a pytorch wheel from https://download.pytorch.org/whl/nightly/cpu. Is there more to be done here?

**Comment by ezyang** [comment]
We can probably file subissues for making tutorials that are not currently runnable today, actually runnable in CI. So yeah, closed!
