### ISSUE TITLE
Memory Leak & Performance Decrease on AMD CPU with PyTorch >1.3

### ISSUE THREAD

**Issue by MichaelLutter** [pytorch/pytorch#32008]
## 🐛 Bug

It seems there is a memory leak and performance decrease within torch.matmul on AMD processors and PyTorch >1.3. When I multiply two 'big' zero matrices 100000 times, the computation time is four times as long as for PyTorch >1.3 and the computation leaks around 600 MB. Interestingly, I can only observe this behaviour on AMD Processors running PyTorch greater 1.4. When running PyTorch 1.3.1 everything works fine.

For Intel Processors (OS = Ubuntu & Mac) running PyTorch 1.4.0, I did not observe the memory leak or the performance decrease.

## To Reproduce
```
import os
import numpy as np
import psutil
import torch
from tqdm import trange

if __name__ == "__main__":
    print("\n\n\n")
    n_samples = 100000

    pid = os.getpid()
    prev_memoryUse = 0.0

    py = psutil.Process(pid)
    init_mem = py.memory_info()[0] / 2. ** 30
    print(f"PyTorch Version {torch.__version__}")
    for i in trange(n_samples, desc="Torch Memory:", ncols=100):
        tmp = torch.matmul(torch.zeros((1, 256, 256)), torch.zeros((1, 256, 2)))

    memoryUse = py.memory_info()[0] / 2. ** 30
    print(f"Torch Memory: Memory = {memoryUse:.3e}Gb \t Delta Memory = {memoryUse - init_mem:+.3e}Gb")
```
## Expected behavior

 **600MB Memory Leak and 4x Computation Time with PyTorch 1.4.0 & 1.5.0 and AMD**

AMD 3900X  -> PyTorch Version 1.4.0 / Conda Installation / Ubuntu 18.04:
Torch Memory:: 100%|█████████████| 100000/100000 [00:19<00:00, 5091.66it/s]
Torch Memory: Memory = 7.318e-01Gb 	 Delta Memory = +5.883e-01Gb

AMD 3900X  -> PyTorch Nightly Version 1.5.0.dev20200109 / Pip Installation / Ubuntu 18.04:
PyTorch Version 1.5.0.dev20200109
Torch Memory:: 100%|█████████████| 100000/100000 [00:19<00:00, 5105.87it/s]
Torch Memory: Memory = 6.871e-01Gb 	 Delta Memory = +5.464e-01Gb

 **Correct Behaviour with PyTorch 1.3.1 & AMD**

AMD 3900X  -> PyTorch Version 1.3.1 / Conda Installation / Ubuntu 18.04:
Torch Memory:: 100%|█████████████| 100000/100000 [00:05<00:00, 17323.61it/s]
Torch Memory: Memory = 1.603e-01Gb 	 Delta Memory = +4.295e-03Gb

AMD 3900X -> PyTorch Version 1.3.1 / Pip Installation / Ubuntu 18.04:
Torch Memory:: 100%|█████████████| 100000/100000 [00:05<00:00, 17804.70it/s]
Torch Memory: Memory = 1.531e-01Gb 	 Delta Memory = +3.162e-03Gb

 **Correct Behaviour with PyTorch 1.4 and Intel CPU**

Intel i7 - 8th Edition -> PyTorch Version 1.4.0 / Conda Installation
Torch Memory:: 100%|█████████████| 100000/100000 [00:03<00:00, 27692.34it/s]
Torch Memory: Memory = 1.705e-01Gb 	 Delta Memory = +3.803e-03Gb

Intel i7 - 9th Edition -> PyTorch Version 1.4.0 / Conda Installation
Torch Memory:: 100%|█████████████| 100000/100000 [00:03<00:00, 26194.08it/s]
Torch Memory: Memory = 1.562e-01Gb 	 Delta Memory = +4.036e-03Gb

MacBook Pro 2018 i7 -> PyTorch Version 1.4.0 / Conda Installation
Torch Memory:: 100%|█████████████| 100000/100000 [00:05<00:00, 19769.36it/s]
Torch Memory: Memory = 8.743e-02Gb 	 Delta Memory = +1.949e-03Gb

## Environment
 - PyTorch Version: various, see above at expected behaviour
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): various, see above at expected behaviour
 - Python version: 3.7
 - CUDA/cuDNN version: CPU only

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel @mruberry

**Comment by emfomenk** [comment]
Hi @MichaelLutter,

I tried to reproduce the behavior on different systems, but don't see an memory leaks.
Could you please run your reproducer with `MKL_VERBOSE=1` to check what version is used?
(**Caution**: the verbose output will be huge, so you may want to cut the number of iterations to 1)

Also, out of curiosity, could you please run it with `MKL_DISABLE_FAST_MM=1` to disable memory caching on Intel MKL side and see if helps?

Finally, given that different systems have different number of cores, could you please repeat the experiment on AMD and Intel systems with `OMP_NUM_THREADS` set to the same number, say 4?

**Comment by MichaelLutter** [comment]
Hi @emfomenk,
I produced the logs you described. You can find them including the testing shell scripts [here](https://github.com/MichaelLutter/pytorch_debugging). For every setup i created a new conda environment with the current stable Pytorch version 1.4. I might did something wrong as the debug output is not huge.

From observing the results it looks like the number of cores & processes significantly affects the performance. For the standard i7 everything works fine but for the large core machines the standard setup degrades the performance. On these machines the ```OMP_NUM_THREADS=4``` makes the processing faster & the memory leak on AMD CPU's disappear. E.g., the AMD computation time decreases to 8.1s from 20s and the memory leak dissappears. This is still much slower compared to the numpy computation of 5.7s. Similarily the DGX station computation time drops from 12s to 7.6s for pytorch while the numpy computations time is 6.5s.

**AMD 3900X (24 Cores & PyTorch Version 1.4.0):**
```Default Configuration: ```
Computation Time = 1.9e+01s 	Memory = 7.351e-01Gb 	 Delta Memory = +5.912e-01Gb

```MKL_DISABLE_FAST_MM=0 & OMP_NUM_THREADS=4:```
Computation Time = 8.1s 	Memory = 1.496e-01Gb 	 Delta Memory = +5.836e-03Gb


**DGX Station (2x Intel Xeon E5-2698 v4, 40 Cores & PyTorch Version 1.4.0)**
```Default Configuration: ```
Computation Time = 1.2e+01s 	Memory = 1.542e-01Gb 	 Delta Memory = +3.624e-03Gb

```MKL_DISABLE_FAST_MM=0 & OMP_NUM_THREADS=4:```
Computation Time = 7.6s 	Memory = 1.510e-01Gb 	 Delta Memory = +1.747e-03Gb

**Comment by CaoZhongZ** [comment]
https://github.com/MichaelLutter/pytorch_debugging/issues/1

**Comment by CaoZhongZ** [comment]
### Current progress.

Since the problem is version related, so I found the critical commit that revealed the symptoms.
Culprit commit ID: 6eaea39867abf6d11bf4d7183923168962be051f

This commit barely enabled torch.fill_ to use TensorIterator implementation instead of old TH one. We suspected that anything used at::parallel_for might related to the trouble. And tests showed positive results.

Testcase involved:

1. Substitute fill_ operator with rand. The performance degradation and memory bloating vanished ✅
2. Substitute fill_ operator with add_ operator, performance degradation and memory bloating still exists. ❌
3. Make internal::GRAIN_SIZE ridiculously large to disable at::parallel_for, performance degradation and memory bloating vanished. ✅
4. torch.set_num_threads(1), performance degradation and memory bloating vanished. ✅

### Next step
Check the implementation and find more details.

**Comment by ezyang** [comment]
Nice sleuthing. cc @gchanan author of this patch

**Comment by CaoZhongZ** [comment]
### Progress

https://github.com/pytorch/pytorch/blob/8fd3eaed257884361828217f3aeaabc0296ae906/aten/src/ATen/ParallelOpenMP.h#L30-L49

The parallel region created by the code throttled number of OpenMP threads to 2 (num_threads) in our testcase. We could observe exiting of 126 threads at the end of the block, but MKL will boost the number of OpenMP threads back to 128, many threads spawning and exiting during the test and resulted (strongly suspected) the memory leak. So the memory leak might not relate to AMD or Intel, it should be related to OpenMP library in the Linux distro.

A simple proof is this patch (demonstration only): https://github.com/CaoZhongZ/pytorch/pull/1 apply it and the leak goes away. Performance degradation will also be relieved.

**Comment by CaoZhongZ** [comment]
Confirmed the leakage was resulted by GOMP thread number thrashing, more threads more significant of the leakage. I changed the test script to isolate the problem solely to thread numbers. https://github.com/MichaelLutter/pytorch_debugging/pull/2

So I think that's the conclusion. Further investigation should put into why GOMP leak memory.

**Comment by milutter** [comment]
Sorry, I wasnt aware that this was still of any use. When cleaning my repos, I did not remember the use case of the repo and deleted it. However, I found a local copy on my machine and uploaded it again at:
https://github.com/milutter/pytorch_debugging

**Comment by imaginary-person** [comment]
Thanks a lot for your help, @milutter! :)
I've copied those files. I'm not a PyTorch team member, but had requested those scripts for my own edification.
Have a nice weekend!

**Comment by imaginary-person** [comment]
> A simple proof is this patch (demonstration only): [CaoZhongZ#1](https://github.com/CaoZhongZ/pytorch/pull/1) apply it and the leak goes away. Performance degradation will also be relieved.

@CaoZhongZ's [patch](https://github.com/CaoZhongZ/pytorch/pull/1/files) was working because the extant code had a bug that his patch addressed:

In the extant code, `chunk_size` should have been computed according to the `num_threads` threads in the parallel region, but it was being computed according to `omp_get_num_threads()`.

So, the issue might not have been related to libgomp, as fixing this bug (as in @CaoZhongZ's sample-patch) was fixing the leak at the time.

**Comment by imaginary-person** [comment]
I've verified that even in the erstwhile `libgomp` version, the `num_threads` clause doesn't cause some threads to exit.
Moreover, unlike the current implementation, in which the threads of the OpenMP thread pool are created during PyTorch initialization, in PyTorch 1.4.0, more threads are added to the thread-pool when required, so only one more OpenMP thread was being created in the test-script, hence the total of 2 OpenMP threads in `at::parallel_for`. So, how can 126 threads exit if OpenMP only had 2?
 
Correlation doesn't necessarily imply causation, so while making the OpenMP thread-pool fixed-sized fixed the issue, I believe another factor would've been responsible for the 126 threads that @CaoZhongZ reported as exiting. @CaoZhongZ also mentioned MKL creating & destroying threads, [which has caused similar issues in the past as well,
but they are supposed to be fixed](https://github.com/pytorch/pytorch/issues/13757#issuecomment-437472174).
So, it'd be great if we can figure out how to reproduce this issue, as I couldn't do so with the given information.

I tried in vain to reproduce this issue with 3 PyTorch 1.4.0 builds on two processors with 20 & 32 physical cores respectively, both running on Ubuntu 18.04:

1. PyTorch 1.4.0 from Conda. It installed Intel MKL & Intel OpenMP with it.
2. PyTorch 1.4.0 from PIP. It uses libgomp.
3. PyTorch 1.4.0 built from the `release/1.4.0` branch. Intel MKL 2019.3-199 was used for the build.

The test scripts do matrix multiplication 100k times. One extra OpenMP thread is added to the thread pool, which, as expected, only exits at the end of the program, and not between each iteration of the matrix-multiplication. This can be verified with `gdb` by setting `breakpoints` for `pthread_create`, `pthread_exit`, & `exit`.

**Comment by imaginary-person** [comment]
In PyTorch 1.4.0, the threads of the OpenMP thread-pool were actually created when desired. For instance, only one additional OpenMP thread was created for the following snippet of code:
```
import torch
torch.eye(252)
```
On the other hand, the current implementation creates the threads of the OpenMP thread pool before any parallel operation is done, so it'd create threads equal to the number of physical cores (eg. 32 on a machine with 32 physical cores), but use only 2 for this snippet.

**Comment by imaginary-person** [comment]
I tried in vain to reproduce this issue with 3 PyTorch 1.4.0 builds on two processors with 20 & 32 physical cores respectively, both running on Ubuntu 18.04:

1. PyTorch 1.4.0 from Conda. It installed Intel MKL & Intel OpenMP with it.
2. PyTorch 1.4.0 from PIP. It uses libgomp.
3. PyTorch 1.4.0 built from the `release/1.4.0` branch. Intel MKL 2019.3-199 was used for the build.

The test scripts do matrix multiplication 100k times. One extra OpenMP thread is added to the thread pool, which, as expected, only exits at the end of the program, and not between each iteration of the matrix-multiplication. This can be verified with `gdb` by setting `breakpoints` for `pthread_create`, `pthread_exit`, & `exit`.

**Comment by imaginary-person** [comment]
Issue reproduced on a 64-core AMD EPYC 7542, Ubuntu 18.04, gcc 7.5.0 with this PR's changes & the master branch's source-code. The debugger is hanging up without triggering all breakpoints, so I'll provide an update in a few hours. I'll also check if a more recent gcc version has fixed this code. Then I'll submit a bug report to gnu, if required.

**Comment by imaginary-person** [comment]
@CaoZhongZ, can you please confirm on what platform you had managed to reproduce this issue?
I see that @emfomenk & you work at Intel, so I'm confused about what platform you debugged this issue on.
Thank you!
