### ISSUE TITLE
[docs] Missing docs for torch.no_grad, instead there are docs for torch.autograd.no_grad

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#32014]
https://pytorch.org/docs/master/search.html?q=torch.no_grad&check_keywords=yes&area=default

https://pytorch.org/docs/master/autograd.html?highlight=torch%20no_grad#torch.autograd.no_grad

The docs describe the usage of `torch.no_grad()` to create the context manager but they are filed under class `torch.autograd.no_grad`

It would be nice to have docs for `torch.no_grad` as well. User may well want to search for it when reading some source code. It'd also be nice to draw users' extra attention to the fact that parenthesis must be used after the `@torch.no_grad()` versus e.g. `@staticmethod` (which goes without parens)

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
Yes, we should update the doc to reflect both bindings of these functions.
