### ISSUE TITLE
test_handle_send_exceptions is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#32019]
## 🐛 Bug

This test is flaky in `test_rpc_spawn.py`: 
https://app.circleci.com/jobs/github/pytorch/pytorch/4194509

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley

**Comment by mrshenli** [comment]
https://app.circleci.com/jobs/github/pytorch/pytorch/4219403

**Comment by pietern** [comment]
It's likely flaky because the error handling for the libuv transport in Gloo is not as good as the tcp one.

**Comment by rohan-varma** [comment]
Also per @mrshenli's comment (for the py3.5 failure) https://github.com/pytorch/pytorch/pull/30063#issuecomment-574398233 - " if something crashed and prevents us from running _cleanup_python_rpc_handler() it will crash and only crash in PY35"

**Comment by rohan-varma** [comment]
After doing a lot of debugging, it turns out that this is blocked by https://github.com/pytorch/pytorch/issues/25516, specifically the enqueueRecv part. 

The issue was hard to debug since we wouldn't get a stack trace due to the exception in a different thread
