### ISSUE TITLE
libtorch function API problem

### ISSUE THREAD

**Issue by Erissonleo** [pytorch/pytorch#32028]
I am trying to make my project using c++ with libtorch1.3.1 with cuda10.1. In my Python project, I used a function in pytorch and the funciton is torch.autograd.grad(). However I can't find the same funcion in libtorch. Is there a similar fucntion in libtorch ? Thanks!

My computer config is:
OS : win10
libtorch: 1.3.1 with cuda10.1
Ananconda: python3.7 with pytorch1.31

**Comment by gchanan** [comment]
Please use the forum for questions, thanks!

Forum: https://discuss.pytorch.org/
