### ISSUE TITLE
[Doc] torch.triu doc mistakenly said that elements on and BELOW the main diagonal are retained.

### ISSUE THREAD

**Issue by peter9711** [pytorch/pytorch#32032]
## 📚 Documentation
https://pytorch.org/docs/stable/torch.html#torch.triu
![image](https://user-images.githubusercontent.com/33718979/72134835-ef9c7600-33bf-11ea-99ba-7b2599dc3a39.png)

It seems that the highlighted "below" should be "upper“.

**Comment by vishwakftw** [comment]
Hi, thank you for bringing this up. I'll send in a patch to fix it.
