### ISSUE TITLE
Different input parameter names for scatter_ 

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#3203]
Based on the type of the source for `scatter_`, the parameter name seems to change.
The [docs](http://pytorch.org/docs/master/tensors.html#torch.Tensor.scatter_) use `src` as the parameter name.

Depending wheter a `Tensor` or `Variable` is used, the names change.
The exception message gives a hint to use `value` for `float` values when using `Tensor`s.
Using `Variable`s, the exception message does not give a hint.

Code to reproduce the issue:

    # Init 
    a = torch.FloatTensor(3, 3).normal_()
    print(a)

    # Tensor + value (float)
    a1 = a.scatter_(dim=1, index=torch.LongTensor([[0], [0], [0]]), value=1.0)
    print(a1)

    # Tensor + src (FloatTensor)
    a2 = a.scatter_(dim=1,
                    index=torch.LongTensor([[0], [0], [0]]),
                    src=torch.FloatTensor([[1], [2], [3]]))
    print(a2)

    # Variable + source (float)
    a3 = Variable(a).scatter_(dim=1,
                              index=torch.LongTensor([[0], [0] ,[0]]),
                              source=1.23)
    print(a3)

    # Variable + source (FloatTensor)
    a4 = Variable(a).scatter_(dim=1,
                              index=torch.LongTensor([[0], [0] ,[0]]),
                              source=torch.FloatTensor([[1], [2], [3]]))
    print(a4)
  
    # Fail cases
    try:
        a1 = a.scatter_(dim=1, index=torch.LongTensor([[0], [0], [0]]), src=1.0)
    except TypeError as e:
        print(e)

    try:
        a3 = Variable(a).scatter_(dim=1,
                                  index=torch.LongTensor([[0], [0] ,[0]]),
                                  src=1.23)
    except TypeError as e:
        print(e)

I tried to hunt down the issue, but could not find the parameter names [here](https://github.com/pytorch/pytorch/blob/f608208a8051a8708e71291e84768bf8be720a1a/torch/lib/TH/generic/THTensorMath.c).

Maybe someone could give me a hint, where to look for the param names, so I could try to fix this.

Greets!

**Comment by zou3519** [comment]
It looks like Variable takes in src (a tensor) or value (a float) now, so the parameter names should be consistent.

The parameter names are here: https://github.com/pytorch/pytorch/blob/ea7652e0116e4602476be9c70460536499607726/torch/csrc/generic/methods/Tensor.cwrap#L773

**Comment by mruberry** [comment]
Hey @ptrblck! Hope you're doing well and staying safe during quarantine. I'm going to close this due to age, but if it's still happening (somehow) please reopen it.
