### ISSUE TITLE
nll_loss does not check for negative indices

### ISSUE THREAD

**Issue by abaisero** [pytorch/pytorch#32049]
## 🐛 Bug

F.nll_loss does not check for negative indices, and returns garbage when negative indices are used (with the exception of the ignore_index parameter, which works as expected).

## To Reproduce

```
import torch
import torch.nn.functional as F

logits = torch.randn(5, 2).log_softmax(-1)

F.nll_loss(logits, torch.tensor([0, 1, 0, 1, 0]), reduction='none') # works as intended
F.nll_loss(logits, torch.tensor([0, 1, 0, 1, -100]), reduction='none') # works as intended
F.nll_loss(logits, torch.tensor([0, 1, 0, 1, 100]), reduction='none') # raises exception as intended
F.nll_loss(logits, torch.tensor([0, 1, 0, 1, -99]), reduction='none') # should but does not raise an exception, returns garbage
```

## env info

I've tested this with both torch 1.2 and 1.3.

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.7.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.2.0
[conda] torch                     1.3.1                    pypi_0    pypi
[conda] torchvision               0.4.2                    pypi_0    pypi

cc @albanD @mruberry

**Comment by iamarpan** [comment]
@gchanan Is this issue still open. If yes, this would be my first open-source contribution. Can you please tell me what error message needs to be displayed in case of negative value.

**Comment by mruberry** [comment]
I just re-ran the case in the issue and this has been fixed. Relevant code snippet:

https://github.com/pytorch/pytorch/blob/7680358122e62387737a3e4f3b7621e23bd133b1/aten/src/ATen/native/LossNLL.cpp#L61

It must have been accidentally left open.
