### ISSUE TITLE
Libtorch iOS Build can't be used in unit test target

### ISSUE THREAD

**Issue by mjjimenez** [pytorch/pytorch#32040]
## 🐛 Bug

The current build for libtorch for iOS installed using cocoapods can't be included in a unit test target.

I've filed a cocoapods issue on this and they discovered that `libnnpack.a` is not a universal library,
causing the build error.

https://github.com/CocoaPods/CocoaPods/issues/9473

## To Reproduce

I just cloned your demo app here https://github.com/pytorch/ios-demo-app and added a unit test target to the HelloWorld demo.

I forked the repo and added the unit test target here:

https://github.com/mjjimenez/ios-demo-app

## Environment

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.3 (11C29)
         Git : git version 2.8.1
Ruby lib dir : /Users/mjjim2003/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 7bb44aaa4557b457f1c13cb1a7e403248a0ef594
               rnapier - git - https://github.com/rnapier/RNCryptor.git @ 5e3bbf44f08bf90049537cb8902d8f4fa911a79a
               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68
```

### Podfile

```
platform :ios, '12.0'
target 'HelloWorld' do
    pod 'LibTorch', '~> 1.3.0'

    target 'HelloWorldTests' do
      inherit! :search_paths

    end

end
```

**Comment by xta0** [comment]
@mjjimenez  As discussed in the forum,  this is a known issue, as NNPACK doesn’t support the iOS simulator architecture - https://github.com/Maratyszcza/NNPACK. We've actively working on enabling XNNPACK which will replace NNPACK in the future.

**Comment by Jthora** [comment]
@xta0 What is the ETA on the fix? 

The lack of simulator is a blocker for our production team's ability to go next-stage with PyTorch. We have opened discussions to use TensorFlow instead as a result of this blocker, but PyTorch would have been preferred by some elements in our development pipeline. 

If you can estimate a time range for when the issue will be resolved: We can create a plan around that as to go with PyTorch instead of TensorFlow.

**Comment by xta0** [comment]
> @xta0 What is the ETA on the fix?
> 
> The lack of simulator is a blocker for our production team's ability to go next-stage with PyTorch. We have opened discussions to use TensorFlow instead as a result of this blocker, but PyTorch would have been preferred by some elements in our development pipeline.
> 
> If you can estimate a time range for when the issue will be resolved: We can create a plan around that as to go with PyTorch instead of TensorFlow.

Hey we've already enabled the XNNPACK for our mobile build. The official cocoapods (1.6.0) release will be in July.
