### ISSUE TITLE
logdet on GPU is slower than on CPU and  uses a lot of CPU-time

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#32048]
## 🐛 Bug

logdet on a GPU matrix is much slower than on a CPU-matrix. The GPU-version also uses a lot of CPU-time (even more CPU-time than the CPU-version?!).

## To Reproduce

```py
import torch
import time

a = torch.rand(300, 300, device="cuda")
start = time.time()
for i in range(5000):
    torch.logdet(a)
print(time.time() - start)  # 18.659279346466064

a = a.cpu()
start = time.time()
for i in range(5000):
    torch.logdet(a)
print(time.time() - start)  # 3.3905134201049805
```

## Expected behavior
logdet shouldn't use much CPU-time at all (and should be faster than the CPU version).

## Environment

```
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 9.2.1-17ubuntu1~16.04) 9.2.1 20191102
CMake version: version 3.15.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 418.43
cuDNN version: /usr0/local/cuda-9.0/lib64/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu100    pytorch
```

cc @VitalyFedyunin @ngimel @mruberry

**Comment by vishwakftw** [comment]
Hi @twoertwein, thank you for opening the issue. This is related to #23940.

I did some benchmarking on Colab, and this is what I got:

| n | best gpu (in seconds) | best cpu (in seconds) |
| - | ----- | ----- |
| 100 | 0.0014519537639999954 | 0.0001178999996000016 |
| 200 | 0.002751796090000198 | 0.00029353885099999387 |
| 500 | 0.0035182207200000447 | 0.0022295741199991424 |
| 1000 | 0.005821415069999602 | 0.01259447002999991 |
| 2000 | 0.011968499399999928 | 0.08614811779999627 |
| 5000 | 0.12622647200000756 | 1.1689550489999192 |
| 10000 | 0.4611854409999978 | 8.58576884799993 |
| 20000 | 1.8240422789999684 | 65.82807065700001 |

**Comment by twoertwein** [comment]
@vishwakftw Thanks for confirming the performance issue.

Could it be that `logdet` is already using your proposed solution ("Implicitly offload computation to CPU, and move the result to GPU.")? That could explain why it uses so many CPU resources. It would be nice to have an option to force GPU-operations to be able to compare a pure GPU-logdet, a pure-CPU logdet, and your mixed approach.

**Comment by vishwakftw** [comment]
In MAGMA, for small matrix sizes, the `getrf` routine for computing the LU decomposition automatically dispatches to LAPACK on the CPU. This along with CPU-GPU transfer could _perhaps_ explain the increased CPU usage.

**Comment by Lezcano** [comment]
Just repeated the test and, while computing the determinant is still slower on CUDA than on CPU for small matrices (which is expected, as pivoting on CUDA is slow), we're getting closer. For small matrices GPU is  2-5 times slower than CPU, rather than x10 that we had before.
```
[---------- torch.linalg.slogdet -----------]
                          |   cpu   |   cuda
1 threads: ---------------------------------
      shape (100, 100)    |     84  |    400
      shape (200, 200)    |    296  |    538
      shape (500, 500)    |   2257  |   1696
      shape (1000, 1000)  |  12700  |   4902
      shape (2000, 2000)  |  83000  |  12400
```

<details>
<summary>Script</summary>

```python
import torch
from torch.utils.benchmark import Compare, Timer


def get_timer(device, n):
    shape = (n, n)
    A = torch.randn(shape, device=device)

    timer = Timer(
        r"""
        torch.linalg.slogdet(A)""",
        globals={"A": A},
        label="torch.linalg.logdet",
        description=f"{device}",
        sub_label=f"shape {shape}",
        num_threads=1,
    )
    return timer.blocked_autorange()


def get_params():
    ns = (100, 200, 500, 1000, 2000)
    for device in ("cpu", "cuda"):
        for n in ns:
            yield device, n


compare = Compare([get_timer(*params) for params in get_params()])
compare.trim_significant_figures()
compare.print()
```

</details>
