### ISSUE TITLE
Missing documentation for is_quantized

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#32064]
## 📚 Documentation
There is no documentation for the tensor attribute is_quantized that specifies if a tensor is a qtensor or not. This needs to be added to:https://pytorch.org/docs/stable/tensors.html#torch-tensor similar to is_cuda attribute

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by imskr** [comment]
I want to work on this issue!
