### ISSUE TITLE
torch.mean keepdim is not working correctly

### ISSUE THREAD

**Issue by Linus4world** [pytorch/pytorch#32089]
## 🐛 Bug

_torch.mean()_ removes the first dimension of a tensor, if it is of size 1. Even if keepdim=True
## To Reproduce

```
>>>  torch.randn(1,2,3,4).mean(2, keepdim=True)[0].size()
torch.Size([2, 1, 4])
```

## Expected behavior
```
>>>  torch.randn(1,2,3,4).mean(2, keepdim=True)[0].size()
torch.Size([1, 2, 1, 4])
```

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1

Python version: 3.7

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1

**Comment by vadimkantorov** [comment]
I think it's `[0]` that removes the first dimension

**Comment by ngimel** [comment]
As @vadimkantorov says, behavior is as expected, dimension is preserved.
