### ISSUE TITLE
Support for torch.onnx.symbolic_opset11._new_empty_tensor_op

### ISSUE THREAD

**Issue by peasant98** [pytorch/pytorch#32085]
## ❓ Questions and Help
Hi, is there support yet for torch.onnx.symbolic_opset11._new_empty_tensor_op? It seems to cause the failure in the ONNX export for MaskRCNN from torchvision's models.

**Comment by izdeby** [comment]
Please, use out the [forum](https://discuss.pytorch.org/) for questions as github issues are monitored for issues and feature requests only.
