### ISSUE TITLE
Occassionally get illegal memory access in Cuda copy

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#32081]
## 🐛 Bug

While inferencing, I occassionally get the following exception in my forward call:
CUDA error: an illegal memory access was encountered (copy_kernel_cuda at C:/w/1/s/windows/pytorch/aten/src/ATen/native/cuda/Copy.cu:187)
(no backtrace available)

It appears to refer to this line of code:
https://github.com/pytorch/pytorch/blob/v1.3.1/aten/src/ATen/native/cuda/Copy.cu#L187

## To Reproduce

1. After running my model tens of thousands of times, eventually I get an exception. I can't get any minimal reproduction

## Expected behavior

No exception

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): Binaries from website
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1/7.6
 - GPU models and configuration: RTX 2060
 - Any other relevant information:

## Additional context

Wish I could be of more help. Is it a known issue?

cc @ngimel

**Comment by peterjc123** [comment]
It may be some corner cases that are hard to reproduce. Recently I resolved a similar issue that is related to the `pow` op with CUDA in https://github.com/pytorch/pytorch/issues/31108.

**Comment by peterjc123** [comment]
It will be helpful for us if you could get the exact crash site with the help of setting `CUDA_LAUNCH_BLOCKING =1`.

**Comment by xsacha** [comment]
It takes a while to hit but I'll run with this set for now.
Thanks.

**Comment by izdeby** [comment]
@xsacha, can you provide some repro code, please?

**Comment by xsacha** [comment]
Seems to happen while generating multiple models at the same time. Some race condition. Not sure how to give a simple or fast repro.

**Comment by xsacha** [comment]
No longer happens in latest version
