### ISSUE TITLE
QAT Multi-GPU support

### ISSUE THREAD

**Issue by robotcator** [pytorch/pytorch#32082]
## 🐛 Bug
`_broadcast_coalesced` raise `incompatible function arguments` errors when tensors argument contains class 'NoneType'.  
1. If I fill [the state_dicts' none element in the list](https://github.com/pytorch/pytorch/blob/v1.3.1/torch/nn/parallel/distributed.py#L294), the error disappears.
2. The `Nonetype` elements in the buffers exist in [there](https://github.com/pytorch/pytorch/blob/v1.3.1/torch/quantization/fake_quantize.py#L52)

## To Reproduce

1. the code is in there. https://github.com/pytorch/vision/blob/master/references/classification/train_quantization.py
2. python -m torch.distributed.launch --nproc_per_node=8 --use_env train_quantization.py --data-path=~/test/imagenet_1k

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: python 3.6
 - CUDA/cuDNN version: 10.1

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by robotcator** [comment]
cc @jerryzh168 Do you have any idea?

**Comment by jerryzh168** [comment]
Looks like `self.scale` is None, did you run the fake_quant? and did you enable observer?
Also cc @raghuramank100

**Comment by robotcator** [comment]
> Looks like `self.scale` is None, did you run the fake_quant? and did you enable observer?

Yes, I run the fake quantization mode. [Here](https://github.com/pytorch/vision/blob/master/references/classification/train_quantization.py#L58)
is the preparation of fake quantization.

FYI, the default value of `observer_enabled` is true and the `scale and zero_point` can be calculated in the [forward phase](https://github.com/pytorch/pytorch/blob/master/torch/quantization/fake_quantize.py#L81).
The distributed broadcast in call before this process.

**Comment by robotcator** [comment]
Hi, actually, I think there are something need to clarify. 
1: I print all the parameter's when call the `_broadcast_coalesced `, it seems that not only the `scale` and `zero_point`, the `min_val` and `max_val` value is also None.
2: I change the 'min_val' and 'max_val' in `https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L304` to default value. 
3: It will raise runtime error, the error seems that the tensor didn't move to GPU device 


```
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: Tensors must be CUDA and dense
```

**Comment by jerryzh168** [comment]
@robotcator year we noticed that as well, and current plan is to use `torch.tensor([])` as default value for min_val and max_val, I haven't tested that though, do you mean it does not work?

**Comment by robotcator** [comment]
Yes, sorry for the late reply. Even give default value, it doesn't work.

**Comment by jerryzh168** [comment]
It should be fixed after https://github.com/pytorch/pytorch/pull/32733 is landed

**Comment by jerryzh168** [comment]
@robotcator please rebase on master and check again

**Comment by robotcator** [comment]
@jerryzh168 Great, sorry for miss the message, I will try  and check it.

**Comment by vkuzo** [comment]
looks like https://github.com/ttumiel/pytorch/commit/15abfa68d3846dafab339e67fcc6a21a6973a13b fixed this issue.  We also landed various other bugfixes in the past couple of months and QAT + DDP works correctly now.  Closing, please reopen if there are further issues!
