### ISSUE TITLE
logical_not for Boolean tensor has peculiar behavior

### ISSUE THREAD

**Issue by ironjr** [pytorch/pytorch#32094]
## 🐛 Bug

`torch.logical_not` operation or '~' for `torch.BoolTensor` does not apply correctly.

## To Reproduce

Simple code to reproduce the behavior.
```python
import torch

a = torch.BoolTensor(1, 2)`
print(a) # expected tensor([[ True, True ]])
a[0, 1] = False
print(a) # expected tensor([[ True, False ]])

print(~a) # expected tensor([[ False, True ]]) but we get tensor([[ True, True ]])
print(~~a) # expected tensor([[ True, False ]]) and we DO get this correctly.

# The following codes produce the same result
print(a.logical_not())
print(a.logical_not().logical_not())

print(torch.logical_not(a))
print(torch.logical_not(torch.logical_not(a)))

# The following codes produce errors
# print(1 - a) # RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported.
               # If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
# c.neg()      # RuntimeError: the same as above.
```

## Expected behavior

When you apply a proper logical NOT operation ('~' in python), you should get all original Trues to be Falses and vice versa. Therefore, in the above code, you should get `tensor([[ False, True ]])` instead of `tensor([[ True, True ]])` when you logically negate `tensor([[ True, False ]])`.

However by applying two negation, you get the original Boolean tensor correctly. It means that information is not lost in negating the tensor (as you should expect), but the internal representation of the negation of a BoolTensor is not correct.

## Environment

```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.44
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py36h7b6447c_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py36_cu101    pytorch
```

## Additional context

cc @ezyang @gchanan @zou3519 @izdeby

**Comment by ironjr** [comment]
\+ Some additional information
If you cast the above BoolTensor to ByteTensor, you see this:
```
# ... codes above ...
print(a.type(torch.ByteTensor)) # You get tensor([[ 44, 0 ]], dtype=torch.uint8)
print((~a).type(torch.ByteTensor)) # You get tensor([[ 211, 255 ]], dtype=torch.uint8)
```
The value of 44 changes every time you run the code.

However, if you cast ByteTensor to BoolTensor, the internal representation seems to change correctly (True -> 1, False -> 0). The main problem I found was two-fold:

1. Initialization of Boolean tensor by torch.BoolTensor does not reset the internal representation and thus contain non-zero, non-unity values (e.g. 44).
1. `logical_not` or `~` operation simply do bitwise negation, and likely to fail converting True into False (e.g. 44 -> 211), but instead, correctly converts False into True (Since only 0 represents False).

Type casting from different representation to BoolTensor forces regular internal representation (1 for True, and 0 for False). I don't think this solves the core problem, though.

**Comment by ezyang** [comment]
Can you check if this occurs on 1.4? I think we fixed this one

**Comment by gchanan** [comment]
I don't think we fixed this.

**Comment by MuhongGuo** [comment]
I tested the above code with PyTorch 2.0.0 and don't have the issues. All behaviors of the code are expected.
