### ISSUE TITLE
deterministic sampling

### ISSUE THREAD

**Issue by tarungog** [pytorch/pytorch#32095]
## ❓ Questions and Help
When we are training RL algorithms such as A2C, it is common to utilize random sampling at train time and deterministic (highest probability) sampling at test time. Is there a way to make torch distribution act deterministically and output the highest probability action?

If not, I would like to request this feature.

**Comment by SsnL** [comment]
IIUC, you are asking for `distn.mode`, right?

**Comment by tarungog** [comment]
A Categorical distribution doesn't seem to have a mode property or method. What is `distn` in this case? @SsnL

**Comment by SsnL** [comment]
Yes, it does not exist. I was just wondering if this is a feature request for `distribution.mode`.

**Comment by artemisart** [comment]
Just take the argmax of your distribution, or is there something I'm missing ?

**Comment by tarungog** [comment]
Yeah you’re right
