### ISSUE TITLE
cudnn convolutions should be using `benchmark=False; determimistic=True` by default

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#32103]
## 🚀 Feature
cudnn convolutions should be using `torch.backends.cudnn.benchmark=False; torch.backends.cudnn.deterministic=True` by default, currently both are set to `False`
## Motivation
When `benchmark` and `deterministic` are set to `False`, cudnn heuristics is used. It is useless at best, and is leading to slowdowns/crashes at worst (https://discuss.pytorch.org/t/deterministic-cudnn-flag-results-in-2x-speedup-how-is-this-possible/36199, #31336). Setting `deteministic` to `True` would cause pytorch to use predefined algos that can always be used (@ptrblck to verify) and have decent performance, thus providing better user experience. 

## Alternatives
Setting cudnn modes can be done manually, but many users don't know how and why to do that, and instead are reporting bugs. 

cc @csarofeen @ptrblck @ezyang for his take

cc @csarofeen @ptrblck

**Comment by ezyang** [comment]
OK, SGTM.
