### ISSUE TITLE
cpp extension in nightly is broken

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#32136]
## 🐛 Bug

nightly Pytorch cannot compile cpp extension

## To Reproduce

Extension [here](https://pytorch.org/tutorials/advanced/cpp_extension.html#writing-a-mixed-c-cuda-extension) defines:

```c++
#define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
```

results in deprecation:

```text

warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement

```

but there is no `is_cuda` in `options` struct.
The fix was to call `x.is_cuda()` directly, which is nicer.

```c++
#define CHECK_CUDA(x) TORCH_CHECK(x.is_cuda(), #x " must be a CUDA tensor")
```

## Expected behavior

Examples to be tested

## Environment

Collecting environment information...
PyTorch version: 1.5.0.dev20200113
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.87.01
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.5.0.dev20200113
[pip] torchvision==0.5.0a0+e50d746
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.15           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] pytorch                   1.5.0.dev20200113 py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20200113      py36_cu100    pytorch-nightly

## Additional context

cc @yf225

**Comment by bwesen** [comment]
Just FYI this is broken in the official PyTorch C++ Tutorial as well (it should be updated to use x.is_cuda() as well)
