### ISSUE TITLE
python error UnboundLocalError in jit/frontend.py

### ISSUE THREAD

**Issue by arvrmd** [pytorch/pytorch#32139]
## 🐛 Bug

One of the error cases in the function ```build_param_list``` uses ```ctx_range``` without defining it, in the following context:
```
    if not PY2 and py_args.kw_defaults:
        raise NotSupportedError(ctx_range, _vararg_kwarg_err)
```
## To Reproduce

I was using ```torch.jit.script()``` on a large module, and since it's the error reporting that's failing I don't have a line reference. By inspection, however, I believe the unsupported feature was the asterisk in the following function definition:
```
    @torch.jit.export
    def initState(self, *, n_tokens: int, device_name: str) -> None:
```

## Expected behavior

Relevant error message should be reported.

cc @suo

**Comment by suo** [comment]
cc @driazati can you take a look?
