### ISSUE TITLE
Weird semantics for torch.diag()

### ISSUE THREAD

**Issue by w4nderlust** [pytorch/pytorch#3213]
The semantics of the function `torch.diag()` changes completely depending on the size of the inputs.
It the input is a vector, it creates a matrix with that vector as diagonal. It the input is a matrix, it extracts it's diagonal and returns a vector.
This is pretty weird to me, those should be two different functions. Also this doesn't consider a more than bi-dimensional case.

Ideally one function would take a tensor of any dimension and return its diagonal. This could be called `extract_diag`.
The other function should take a vector and a number of dimensions and should create a tensor with the number of dimensions specified with that vector as its diagonal. It should include also the actual offset parameter diagonal, maybe calling it offset would be easy to understand. This could be called `diag`.

**Comment by t-vi** [comment]
For numpy users, this is exactly what they expect from [diag](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html).

**Comment by colesbury** [comment]
Yeah, it's weird. I would not do it this way if I were designing an API from scratch. But a lot of our users come from NumPy or Matlab and they both have this behavior.

Maybe we should add `diagonal` and `diagflat`:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagflat.html

**Comment by w4nderlust** [comment]
I i think that that’s a weird choice in numpy too.
I understand trying to keep as much compibility to numpy as possible, but at the same time additional cleaner functions would be a nice idea. Call it diagonal or n_diagonal or other ways, but faithfullness to numpy shouldn’t be keep to have more reasonable functions imho.
