### ISSUE TITLE
Cannot directly use lr_scheduler in current pip-install package

### ISSUE THREAD

**Issue by TengdaHan** [pytorch/pytorch#3214]
When I install pytorch using pip, I found lr_scheduler.py is in `optim/`, but this line is missing:
https://github.com/pytorch/pytorch/blob/d89d9d74bdd0b64c119980003aa29195a61f93a9/torch/optim/__init__.py#L18
Thus user should manually add `from . import lr_scheduler` to use torch.optim.lr_scheduler.
I hope it will be updated in the next version.

**Comment by RoyiAvital** [comment]
I also installed PyTorch 0.2.0 form Anaconda and `torch.optim.lr_scheduler` isn't available (Though according to release notes and documentation it should be there).

I typed `torch.__version__` and the result was `0.2.0_0`.

Thank You.

**Comment by apaszke** [comment]
It's because this code was added after the package was released. It will be there if you update.

**Comment by RoyiAvital** [comment]
Hi,
Update how?

They only updated it today as answer for a request:

https://github.com/ContinuumIO/anaconda-issues/issues/7410

**Comment by apaszke** [comment]
Don't use the default conda channel. It has very old version of PyTorch only. Install with `conda install -c soumith pytorch`, or even better see the instructions in README.

**Comment by RoyiAvital** [comment]
They updated the default one today to 0.2.0_0 (Using `torch.__version__` as I wrote above).
On other computer I used `soumith` channel I got the exact same version.

The [Release page of GitHub talks about version 0.2.0](https://github.com/pytorch/pytorch/releases/tag/v0.2.0) as well.

**Comment by apaszke** [comment]
I think 0.2.0_4 is the newest one. Also, 0.3 is coming out this week.

**Comment by RoyiAvital** [comment]
OK, I will wait 0.3 is updated.
But you see the problem in having Release Notes for version 0.2.0 stating on features while it is actually implemented only in 0.2.0_4.

**Comment by taochenshh** [comment]
Hi, I am using pytorch 0.2.0_4, but I cannot use lr_scheduler still.
```python
Python 3.5.4 |Anaconda, Inc.| (default, Oct  5 2017, 08:00:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: torch.__version__
Out[2]: '0.2.0_4'

In [3]: torch.optim.lr_scheduler
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a472c70f0769> in <module>()
----> 1 torch.optim.lr_scheduler

AttributeError: module 'torch.optim' has no attribute 'lr_scheduler'
```

**Comment by apaszke** [comment]
Please update to 0.3
