### ISSUE TITLE
Need unittests for the quantization save_state/load_state

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#32189]
Need to make sure the loading/saving the states is checked for `rnn.py`, `linear.py`, `conv.py`, etc.

TODO: Write unittests for quantized save/load state

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by gottbrath** [comment]
+1 .. having unit tests for this would be great.

**Comment by gottbrath** [comment]
removed the Low priority tag on this. Test coverage should be a higher priority.

**Comment by andrewor14** [comment]
Looks like these tests now exist throughout `test/quantization`. Closing this.
