### ISSUE TITLE
pytorch_linux_xenial_cuda10_1_cudnn7_py3_slow_test triggered on all PRs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#32196]
## 🐛 Bug

Slow tests should not be triggered on PRs

## To Reproduce

Open a new PR. Or see sample PR https://github.com/pytorch/pytorch/pull/32187

cc @ezyang @gchanan @zou3519

**Comment by zou3519** [comment]
I think this is high-pri because it slows down developers who wait for builds to finish. Not sure how easy a fix is.

**Comment by ezyang** [comment]
Actually, this is intentional, because slow test isn't actually isn't that slow, compared to the rest of the test suite :) But it's easy to fix; just change the XImportant designation on slow to be just X.

**Comment by zou3519** [comment]
Oh, I didn't realize this was intentional. (downgrading the priority...). I was confused because I haven't seen slow tests run on PRs previously

**Comment by huydhn** [comment]
This issue was ancient, so we can close it now.  Xenial is not even used on CI anymore
