### ISSUE TITLE
Size checks in recurrent cells should be moved from python to c++ implementations

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#32193]
According to @slayton58 commenting out size checks here https://github.com/pytorch/pytorch/blob/ecc349717261185c61110c38c83dff00edceaade/torch/nn/modules/rnn.py#L935-L940 saves ~20 us, hopefully moving them to c++ should result in approximately the same savings. 

cc @VitalyFedyunin @ngimel @mruberry

**Comment by adeeb10abbas** [comment]
Can I work on this @VitalyFedyunin? Anything I should keep in mind while working on it. New to contributions on Github

**Comment by mstfbl** [comment]
Hey @VitalyFedyunin @ngimel @izdeby , I see that the `check_forward_hidden` and `check_forward_input` functions are already implemented in C++ [here](https://github.com/pytorch/pytorch/blob/2ec3e803eb5bd490cf93f3e725cc9f99df930bf5/torch/csrc/api/src/nn/modules/rnn.cpp#L699-L715). I am confused though on how to call these C++ functions in `torch/nn/modules/rnn.py`.

I also see that these two functions are identically copied in these two files below:

https://github.com/pytorch/pytorch/blob/5f2ec6293d6a443b8acca1d3ff7d57f9121afcc7/torch/nn/quantized/dynamic/modules/rnn.py#L702-L717

https://github.com/pytorch/pytorch/blob/b89827b73f7881a8108518452768654894862e5d/torch/jit/quantized.py#L123-L141

I wonder why the same code had to be repeated in these two files, and why the two functions couldn't have been imported from `torch/nn/modules/rnn.py`. Thanks.
