### ISSUE TITLE
Very Slow moving model to device with model.to(device)

### ISSUE THREAD

**Issue by tayo** [pytorch/pytorch#32192]
This is in a new python3 venv with packages installed using pip on 2020 Jan-13, so binaries should be fresh.

My program spends upward of 60 minutes (and counting) for my model:

> device = torch.device("cuda", 0)
> my_model = my_model.to(device)

The model is large and there are 16 GPUs, but the latency still seems incorrect.

My environment:
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM3-32GB
GPU 1: Tesla V100-SXM3-32GB
GPU 2: Tesla V100-SXM3-32GB
GPU 3: Tesla V100-SXM3-32GB
GPU 4: Tesla V100-SXM3-32GB
GPU 5: Tesla V100-SXM3-32GB
GPU 6: Tesla V100-SXM3-32GB
GPU 7: Tesla V100-SXM3-32GB
GPU 8: Tesla V100-SXM3-32GB
GPU 9: Tesla V100-SXM3-32GB
GPU 10: Tesla V100-SXM3-32GB
GPU 11: Tesla V100-SXM3-32GB
GPU 12: Tesla V100-SXM3-32GB
GPU 13: Tesla V100-SXM3-32GB
GPU 14: Tesla V100-SXM3-32GB
GPU 15: Tesla V100-SXM3-32GB

Nvidia driver version: 418.116.00
cuDNN version: /usr/local/cuda-10.1-update-2-with-cudnn-7.6.5/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.3.1
[pip3] torchviz==0.0.1
[conda] Could not collect

pip freeze results:
future==0.18.2
graphviz==0.13.2
joblib==0.14.1
numpy==1.18.1
onnx==1.6.0
pkg-resources==0.0.0
protobuf==3.11.2
pydot==1.4.1
pyparsing==2.4.6
scikit-learn==0.22.1
scipy==1.4.1
six==1.13.0
torch==1.3.1
torchviz==0.0.1
typing-extensions==3.7.4.1

cc @ngimel @VitalyFedyunin @mruberry

**Comment by AmrMKayid** [comment]
Did you check `torch.cuda.is_available()` in your code?
Also, did you try `my_model.cuda()` ?

**Comment by soumith** [comment]
this seems like a PTX to SASS compilation at startup (if you run `perf top` on your machine while those 60 mins are being spent, you'll see some nv* functions pop-up)

@ptrblck @csarofeen can you please confirm that these Tesla V100-SXM3-32GB GPUs are arch 7.0 or arch 7.5 compatible? I cant think of any other reason why this slowdown would occur

**Comment by ptrblck** [comment]
The Tesla V100-SXM3-32GB is arch 7.0.

@tayo I assume the `model.to('cuda:0')` is the first CUDA call in your script?
I try to grab a similar machine and try to reproduce this startup issue.

Also, do you need to use an older PyTorch version (`1.3.1` is the current stable release, while you seem to use `1.0.0`)?

**Comment by tayo** [comment]
Thanks for taking a look @ptrblck .

The 1.0.0 is an artifact -- that was just the last version I tried.  I tried all versions in {1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.0}.  All seem to exhibit this behavior.

It's not quite the first cuda call.  Here is more skeleton of my structure:

> if torch.cuda.is_available():
>   torch.cuda.manual_seed_all(args.numpy_rand_seed)
>   torch.backends.cudnn.deterministic = True
>   device = torch.device("cuda", 0)
>   ngpus = torch.cuda.device_count()  # 1
>   print("Using {} GPU(s)...".format(ngpus))
>
> # ..some stuff
> 
> my_model = MyModel  # instantiate nn.Module object
> if torch.cuda.is_available():
>   my_model = my_model.to(device)

**Comment by ptrblck** [comment]
Thanks for the information!
I've tried to following dummy code:
```python
import torch
import torch.nn as nn


if torch.cuda.is_available():
    torch.cuda.manual_seed(2809)
    torch.backends.cudnn.deterministic = True
    device = torch.device('cuda:0')
    ngpus = torch.cuda.device_count()
    print("Using {} GPU(s)...".format(ngpus))

model = nn.Sequential(
    nn.Conv2d(3, 6, 3, 1, 1),
    nn.ReLU(),
    nn.Conv2d(6, 1, 3, 1, 1)
)
if torch.cuda.is_available():
    model = model.to(device)

torch.cuda.synchronize()
print('done')
```

with the following binaries:

| pytorch | cudatoolkit |
| ---------- | -------------- |
| 1.1.0 | 9.0 |
| 1.3.1 | 9.2 |
| 1.4.0 | 9.2 |
| 1.4.0 | 10.1|

On a server with 16x Tesla V100-SXM3 32GB as well as 8x Tesla V100-SXM2 32GB and cannot reproduce the issue.

Are you using some custom extensions, which might miss the arch flag or are you just using the PyTorch binaries?
Could you also check, if you can reproduce this slowdown using my code snippet or if I'm missing something, please?

**Comment by tayo** [comment]
Good idea @ptrblck .  The problem persists for me with your example.

I've annotated your example with timing instrumentation.  Here is the code:

`import torch
import torch.nn as nn
import timeit

print("Beginning..")

t0 = timeit.default_timer()
if torch.cuda.is_available():
    torch.cuda.manual_seed(2809)
    torch.backends.cudnn.deterministic = True
    device = torch.device('cuda:0')
    ngpus = torch.cuda.device_count()
    print("Using {} GPU(s)...".format(ngpus))
print("Setup takes {:.2f}".format(timeit.default_timer()-t0))

t1 = timeit.default_timer()
model = nn.Sequential(
    nn.Conv2d(3, 6, 3, 1, 1),
    nn.ReLU(),
    nn.Conv2d(6, 1, 3, 1, 1)
)
print("Model init takes {:.2f}".format(timeit.default_timer()-t1))


if torch.cuda.is_available():
    t2 = timeit.default_timer()
    model = model.to(device)
print("Model to device takes {:.2f}".format(timeit.default_timer()-t2))

t3 = timeit.default_timer()
torch.cuda.synchronize()
print("Cuda Synch takes {:.2f}".format(timeit.default_timer()-t3))

print('done')`

Can you run this?

Here are my results:

`Beginning..
Using 16 GPU(s)...
Setup takes 1.64
Model init takes 0.00
Model to device takes 5.03
Cuda Synch takes 0.00
done`

Running with:
torch==1.2.0
Cuda 10.1

**Comment by tayo** [comment]
> Are you using some custom extensions, which might miss the arch flag or are you just using the PyTorch binaries?

No custom extensions are used.  My setup is essentially:
```
$ python3 -m venv v_py3
$ # activate venv
$ pip install torch
$ python myscript.py
```

**Comment by ngimel** [comment]
Ok, so @ptrblck's example runs reasonably fast, which indicates that there is something special about your model, @tayo. Can you please provide a minimum example actually demonstrating slow-down? Also, as @soumith  was asking, what is the output of `perf top` during the slow `to` call?

**Comment by tayo** [comment]
@ngimel  -- 5 seconds is a surprising amount of time to PCIe-transfer the model in @ptrblck 's example.  It is a small model.  My model is much bigger, so I assume the overheads accumulate.  

As a reference, I've just run the same example on my local workstation (single Quadro P1000, torch 1.3.1, cuda 10.1):

```
Beginning..
Using 1 GPU(s)...
Setup takes 0.02
Model init takes 0.00
Model to device takes 1.91
Cuda Synch takes 0.00
done
```
I assume this demonstrates the slowdown, so I was interested in seeing @ptrblck 's results on his dgx2. 

To your question, I will now pull up my environment and run ```perf top```.

**Comment by tayo** [comment]
Samples of output after running ```perf top```:

First few seconds:
```
  14.58%  _mt19937.cpython-36m-x86_64-linux-gnu.so           [.] __pyx_f_5numpy_6random_8_mt19937_mt19937_double
   9.13%  [kernel]                                           [k] clear_page_erms
   8.88%  [kernel]                                           [k] down_read_trylock
   6.82%  [kernel]                                           [k] __handle_mm_fault
   6.69%  [kernel]                                           [k] up_read
   5.08%  _multiarray_umath.cpython-36m-x86_64-linux-gnu.so  [.] _aligned_contig_cast_double_to_float
   4.74%  [kernel]                                           [k] lru_cache_add_active_or_unevictable
```

After about five minutes:
```
  6.66%  libcuda.so.418.116.00                              [.] 0x0000000000133a00
   5.51%  [kernel]                                           [k] _nv029567rm
   5.05%  [kernel]                                           [k] _raw_spin_lock
   2.34%  [kernel]                                           [k] clear_page_erms
   2.02%  [kernel]                                           [k] prepare_exit_to_usermode
   1.97%  [kernel]                                           [k] try_charge
   1.96%  libc-2.27.so                                       [.] 0x000000000018ef2d
   1.92%  [kernel]                                           [k] handle_pte_fault
   1.45%  [kernel]                                           [k] mem_cgroup_try_charge
   1.44%  [kernel]                                           [k] native_irq_return_iret
   1.41%  [kernel]                                           [k] get_page_from_freelist
   1.30%  libpthread-2.27.so                                 [.] __pthread_mutex_lock
   1.30%  libc-2.27.so                                       [.] 0x00000000000a9e8a
   1.25%  libnvidia-ptxjitcompiler.so.418.116.00             [.] 0x00000000000aa2ee
   1.11%  libpthread-2.27.so                                 [.] __pthread_mutex_unlock
   1.05%  [kernel]                                           [k] sync_regs
   1.04%  [kernel]                                           [k] error_entry
   1.02%  [kernel]                                           [k] swapgs_restore_regs_and_return_to_usermode
   0.96%  libc-2.27.so                                       [.] 0x00000000000bb703
   0.91%  libc-2.27.so                                       [.] malloc
   0.83%  libcuda.so.418.116.00                              [.] 0x0000000000115845
   0.79%  libc-2.27.so                                       [.] 0x00000000000bb686
   0.77%  libcuda.so.418.116.00                              [.] 0x0000000000133a17
   0.76%  [kernel]                                           [k] copy_page
   0.75%  [kernel]                                           [k] nvlink_memRd32
   0.73%  [kernel]                                           [k] change_protection_range
   0.68%  libnvidia-ptxjitcompiler.so.418.116.00             [.] 0x00000000004b34c9
   0.67%  libc-2.27.so                                       [.] 0x00000000000bb69d
   0.62%  libc-2.27.so                                       [.] cfree
   0.55%  [kernel]                                           [k] __indirect_thunk_start
   0.55%  [kernel]                                           [k] get_mem_cgroup_from_mm
   0.53%  libc-2.27.so                                       [.] 0x00000000000bb706
   0.50%  libcuda.so.418.116.00                              [.] 0x000000000010f153
   0.50%  libnvidia-fatbinaryloader.so.418.116.00            [.] 0x000000000000a01f
   0.49%  libcuda.so.418.116.00                              [.] 0x00000000003c8f09
   0.48%  libc-2.27.so                                       [.] 0x00000000000bb682
   0.48%  [kernel]                                           [k] os_match_mmap_offset
   0.48%  libc-2.27.so                                       [.] 0x00000000000aa102
   0.46%  libnvidia-fatbinaryloader.so.418.116.00            [.] 0x000000000000a018

```

**Comment by ngimel** [comment]
> @ngimel -- 5 seconds is a surprising amount of time to PCIe-transfer the model in @ptrblck 's example. It is a small model. My model is much bigger, so I assume the overheads accumulate.

It's not PCIe transfer, it's initializing cuda context. Your previous cuda-related calls don't initialize context. If you want to time just the transfer, initialize the context before with `torch.randn(1, device="cuda")`. It's not surprising that initialization on 16-GPU server takes longer than on your local workstation.

**Comment by ptrblck** [comment]
@tayo Could you post the model definition, which takes 60 minutes to finish, so that I could rerun it on your machines, please?

**Comment by soumith** [comment]
@tayo I suspect you are running into an OpenMP deadlock, you are likely using fork in your code, and OpenMP doesn't like fork.

Can you please run your program with the following env varible:

```
OMP_NUM_THREADS=1 python [yourprogram.py]
```

**Comment by tayo** [comment]
Apologies for the delay everyone.

@ptrblck -- I am running a slightly modified version of [https://github.com/facebookresearch/dlrm].   
--arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" --arch-mlp-top="1024-1024-512-256-1" --data-generation=dataset --mini-batch-size=2048

You probably don't want to do all the data downloading and preprocessing, but hopefully that gives you a sense of the model size and type.

@soumith -- I don't recall a system fork calls, as I believe it is single-threaded but I will investigate. I wonder if any pytorch calls are multi-threaded under the hood?  I will try that parameter as you describe.

**Comment by ptrblck** [comment]
Thanks for the link!

There is an option to use random data, so I executed the code with this command:
```
python dlrm_s_pytorch.py --use-gpu --debug-mode --arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" --arch-mlp-top="1024-1024-512-256-1" --data-generation=random --mini-batch-size=2048
```
using PyTorch `1.4.0` and CUDA10.1 and cannot reproduce the slow down on a 16x V100-SXM3 32GB machine.

Did you add any modifications to the code besides the mentioned arguments?
Also, do you see the issue using random data or only if you use your real dataset?

Did @soumith's suggestion help?

**Comment by tayo** [comment]
@ptrblck -- Thanks for giving the model a try.  

I have just run using a clean repo from _HEAD_, with cuda 10.1 and torch==1.4.0.

* My experience replicates yours -- the issue does **not** occur with randomly generated data.  I guess this is related to the dataset/dataloader objects somehow.
* My clean run does not have any modifications to the model, beyond print() statements to let me know where in the code it is stuck.

Next, I tried with @soumith 's suggestion.  Full command line:

```
OMP_NUM_THREADS=1  python dlrm_s_pytorch.py --use-gpu --arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" --arch-mlp-top="1024-1024-512-256-1" --max-ind-range=10000000 --data-generation=dataset --data-set=terabyte --raw-data-file=<raw file location>  --processed-data-file=<processed file location>  --loss-function=bce --round-targets=True --learning-rate=1.0 --mini-batch-size=2048 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16  --memory-map --mlperf-logging --data-sub-sample-rate=0.875 
```

Unfortunately, this does not help.  It's currently stuck in the same place after about 20 minutes.

'perf top' output after ~5 minutes:
```
   4.65%  libpthread-2.27.so                                 [.] __pthread_mutex_lock
   3.22%  [kernel]                                           [k] _nv029567rm
   2.60%  libpthread-2.27.so                                 [.] __pthread_mutex_unlock
   2.04%  python3                                            [.] _PyEval_EvalFrameDefault
   1.64%  libcuda.so.418.116.00                              [.] 0x000000000036906f
   1.38%  libc-2.27.so                                       [.] cfree
   1.12%  libc-2.27.so                                       [.] malloc
   0.89%  python3                                            [.] PyObject_GetAttr
   0.88%  libcuda.so.418.116.00                              [.] 0x0000000000115845
   0.87%  [kernel]                                           [k] do_syscall_64
   0.79%  libcuda.so.418.116.00                              [.] 0x0000000000115b2d
   0.66%  libc10_cuda.so                                     [.] c10::cuda::CUDACachingAllocator::THCCachingAllocator::malloc
   0.63%  [unknown]                                          [.] 0000000000000000
```

After ~20 minutes:
```
   4.50%  [kernel]                                           [k] _nv029567rm
   4.38%  libpthread-2.27.so                                 [.] __pthread_mutex_lock
   2.64%  libpthread-2.27.so                                 [.] __pthread_mutex_unlock
   2.09%  python3                                            [.] _PyEval_EvalFrameDefault
   1.59%  libcuda.so.418.116.00                              [.] 0x000000000036906f
   1.34%  libc-2.27.so                                       [.] cfree
   1.07%  libc-2.27.so                                       [.] malloc
   0.86%  python3                                            [.] PyObject_GetAttr
   0.84%  [kernel]                                           [k] do_syscall_64
   0.78%  libcuda.so.418.116.00                              [.] 0x0000000000115845
   0.75%  libcuda.so.418.116.00                              [.] 0x0000000000115b2d
   0.63%  libc10_cuda.so                                     [.] c10::cuda::CUDACachingAllocator::THCCachingAllocator::malloc
   0.62%  [unknown]                                          [.] 0000000000000000
   0.57%  [kernel]                                           [k] __indirect_thunk_start
   0.55%  [kernel]                                           [k] nvlink_memRd32
   0.50%  [kernel]                                           [k] syscall_return_via_sysret
   0.46%  [kernel]                                           [k] __schedule
   0.46%  libtorch.so                                        [.] at::Tensor::size
   0.44%  python3                                            [.] _PyObject_GenericGetAttrWithDict
```

**Comment by ptrblck** [comment]
Thanks for the information @tayo.
Since this issue does not occur with the random data, I think it might be related to the `cython` compilation of some data utilities from [here](https://github.com/facebookresearch/dlrm/blob/master/cython/cython_compile.py).
I'm still wondering, why you would see the hang in your `model.to()` call, so could you try to just use the data utilities (without the model) and check, if you see a similar behavior?

**Comment by tayo** [comment]
Thanks @ptrblck.  

Reading the code more closely, the cython path is provided just as a convenience for faster data preprocessing.  It needs to be invoked manually, using the Cython library installed on the system.  There should be no cython compilation in everyday use.  For example, I do not have Cython installed in my test environment.

Earlier in the thread, @ngimel said that model.to() initializes the cuda context on the 16-GPU server.  Perhaps something to do with how context initialization might interact with a dataloader on a 16-GPU system?  I'll continue with experimenting with the dataloader.

**Comment by ptrblck** [comment]
@tayo If the issue is created by the context initialization, e.g. `torch.randn(1, device="cuda")` should also take the same amount of time.
Did you test it and do you see the slowdown?

**Comment by tayo** [comment]
Closing this for now as unreproducible.  Thank you @ptrblck @soumith @ngimel  for your awesome help!

**Comment by cenkbircanoglu** [comment]
Using cuda=9.2 will solve this problem

**Comment by mathandy** [comment]
> The Tesla V100-SXM3-32GB is arch 7.0.
> 
> @tayo I assume the `model.to('cuda:0')` is the first CUDA call in your script? I try to grab a similar machine and try to reproduce this startup issue.
> 
> Also, do you need to use an older PyTorch version (`1.3.1` is the current stable release, while you seem to use `1.0.0`)?

was having the same problem with `torch==1.4.0` on a 3090, but the problem went away when I tried in 1.12. 👍

**Comment by tayo** [comment]
Thanks @mathandy for the data point!
