### ISSUE TITLE
PyTorch android not working with Progaurd and minified enabled in release mode android.

### ISSUE THREAD

**Issue by pranavpandey2511** [pytorch/pytorch#32211]
## 🐛 Bug

I trained a model on my desktop and then traced it and converted it using torch.jit.trace() function to use it on mobile phone(android). It is working fine when the app is in debug mode on android. But when I use Proguard and enable minified and create apk in release mode it is not working (means apk is not successfully made) and I get an error

## To Reproduce

1. Train any model on desktop or laptop.
2. Set it to eval mode and trace it using torch.jit.trace() function and save it to a ".pt' file.
3. Use PyTorch Android 1.3.0 and load the model on your android app.
4. Create .apk for your app with ProGuard enabled and Minified enbaled, you'll get this error.

below is complete stack trace for android:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/lavender/lavender:9/PKQ1.180904.001/V11.0.6.0.PFGINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 16528, tid: 16694, name: ModuleActivity  >>> org.pytorch.demo <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
**Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lorg/pytorch/Module$NativePeer;.initHybrid(Ljava/lang/String;)Lcom/facebook/jni/HybridData;"'**
    x0  0000000000000000  x1  0000000000004136  x2  0000000000000006  x3  0000000000000008
    x4  00000071fa9dd000  x5  00000071fa9dd000  x6  00000071fa9dd000  x7  0000000000935d34
    x8  0000000000000083  x9  39149cced3ee5849  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000000000140  x14 0000000000000000  x15 00000071f66eb000
    x16 00000071f66df2b0  x17 00000071f65fecd0  x18 0000000000000010  x19 0000000000004090
    x20 0000000000004136  x21 0000007157f648c0  x22 0000000000000016  x23 0000007174514443
    x24 00000071745142f7  x25 0000000000000001  x26 0000007157d7ae90  x27 0000000000000043
    x28 0000007174cad720  x29 0000007157d7ad40
    sp  0000007157d7ad00  lr  00000071f65f2144  pc  00000071f65f216c

backtrace:
    #00 pc 000000000002216c  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000465684  /system/lib64/libart.so (art::Runtime::Abort(char const*)+1196)
    #02 pc 0000000000008ce0  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
    #03 pc 00000000002e5ec8  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1640)
    #04 pc 00000000002e6038  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
    #05 pc 00000000000fdabc  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+148)
    #06 pc 00000000000fc498  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+1152)
    #07 pc 00000000000fb804  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+628)
    #08 pc 00000000000fe794  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewRef(char const*, _JNIEnv*, _jobject*, art::IndirectRefKind)+684)
    #09 pc 0000000000498cdc  /system/lib64/libart.so (art::Thread::SetClassLoaderOverride(_jobject*)+64)
    #10 pc 00000000002e9ad8  /system/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+3236)
    #11 pc 0000000000004038  /system/lib64/libopenjdkjvm.so (JVM_NativeLoad+412)
    #12 pc 00000000002f4298  /system/framework/arm64/boot-core-oj.oat (offset 0x2dc000) (java.lang.Runtime.nativeLoad [DEDUPED]+200)
    #13 pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #14 pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #15 pc 0000000000280338  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #16 pc 000000000027a34c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    #17 pc 00000000005279cc  /system/lib64/libart.so (MterpInvokeStatic+204)
    #18 pc 0000000000549b14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #19 pc 00000000000da3e2  /system/framework/boot-core-oj.vdex (java.lang.Runtime.loadLibrary0+38)
    #20 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #21 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #22 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #23 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #24 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #25 pc 00000000000dddbc  /system/framework/boot-core-oj.vdex (java.lang.System.loadLibrary+16)
    #26 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #27 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #28 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #29 pc 00000000005279cc  /system/lib64/libart.so (MterpInvokeStatic+204)
    #30 pc 0000000000549b14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #31 pc 000000000006bdd2  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (org.pytorch.Module$NativePeer.<clinit>+4)
    #32 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #33 pc 0000000000516d7c  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #34 pc 00000000005604fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #35 pc 000000000055764c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #36 pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #37 pc 0000000000128044  /system/lib64/libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+2196)
    #38 pc 00000000001133dc  /system/lib64/libart.so (art::ClassLinker::EnsureInitialized(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+192)
    #39 pc 000000000052a50c  /system/lib64/libart.so (MterpNewInstance+760)
    #40 pc 0000000000547390  /system/lib64/libart.so (ExecuteMterpImpl+4496)
    #41 pc 00000000000f325a  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (org.pytorch.Module.<init>+6)
    #42 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #43 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #44 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #45 pc 0000000000527808  /system/lib64/libart.so (MterpInvokeDirect+296)
    #46 pc 0000000000549a94  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    #47 pc 00000000000f3248  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (org.pytorch.Module.a+4)
    #48 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #49 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #50 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #51 pc 00000000005279cc  /system/lib64/libart.so (MterpInvokeStatic+204)
    #52 pc 0000000000549b14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #53 pc 00000000000f486a  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (org.pytorch.demo.vision.ImageClassificationActivity.a+64)
    #54 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #55 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #56 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #57 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #58 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #59 pc 00000000000f47c0  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (org.pytorch.demo.vision.ImageClassificationActivity.a)
    #60 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #61 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #62 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #63 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #64 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #65 pc 00000000000f45bc  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (c.a.c.o.h.b+28)
    #66 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #67 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #68 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #69 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #70 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #71 pc 00000000000f44c8  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (c.a.c.o.b.a+4)
    #72 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #73 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #74 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #75 pc 0000000000527444  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #76 pc 0000000000549b94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #77 pc 000000000009b2a0  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (a.c.b.v0.a+44)
    #78 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #79 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #80 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #81 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #82 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #83 pc 000000000009b88e  /data/app/org.pytorch.demo-TyRnrpVecS_14v9W3F4V_g==/oat/arm64/base.vdex (a.c.b.y0$a.run+8)
    #84 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #85 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #86 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #87 pc 0000000000527444  /system/lib64/libart.so (MterpInvokeInterface+1392)
    #88 pc 0000000000549b94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
    #89 pc 0000000000bcfc3a  /system/framework/boot-framework.vdex (android.os.Handler.handleCallback+4)
    #90 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #91 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #92 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #93 pc 00000000005279cc  /system/lib64/libart.so (MterpInvokeStatic+204)
    #94 pc 0000000000549b14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #95 pc 0000000000bcfac8  /system/framework/boot-framework.vdex (android.os.Handler.dispatchMessage+8)
    #96 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #97 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #98 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #99 pc 00000000005264c8  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #100 pc 0000000000549994  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #101 pc 0000000000be26b4  /system/framework/boot-framework.vdex (android.os.Looper.loop+414)
    #102 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #103 pc 0000000000259b44  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #104 pc 000000000027a330  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
    #105 pc 00000000005279cc  /system/lib64/libart.so (MterpInvokeStatic+204)
    #106 pc 0000000000549b14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #107 pc 0000000000bcf470  /system/framework/boot-framework.vdex (android.os.HandlerThread.run+56)
    #108 pc 0000000000254050  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3557229793+488)
    #109 pc 0000000000516d7c  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
    #110 pc 00000000005604fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #111 pc 0000000000557388  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #112 pc 00000000000cfcc8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #113 pc 000000000045dd7c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #114 pc 000000000045ee38  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
    #115 pc 0000000000489d28  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
    #116 pc 0000000000090328  /system/lib64/libc.so (__pthread_start(void*)+36)
    #117 pc 0000000000023a28  /system/lib64/libc.so (__start_thread+68)

## Expected behavior

Expected the apk to be generated without any issue.

 - PyTorch Version (e.g., 1.0): **1.3.0**
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source): **conda**
 - Build command you used (if compiling from source):
 - Python version: 3**.6**
 - CUDA/cuDNN version: **10.2**
 - GPU models and configuration: **RTX 2080 Ti 11GB**
 - Any other relevant information:

**Comment by izdeby** [comment]
closing as a [duplicate](https://github.com/pytorch/pytorch/issues/32212).
