### ISSUE TITLE
Problem in KL Divergence

### ISSUE THREAD

**Issue by leela93** [pytorch/pytorch#32220]
Hallo Soumith, I am using KLDivLoss in Pytorch, as per the documentation of KLDivLoss. My 'x' value is prediction from network where the last layer is Sigmoid. And my 'y' value is a distribution, where value will be '1' or '0' .
 Now my doubt is should i sent direct 'x' or log'x' to KLDivLoss in pytorch, to obtain the correct value.

**Comment by izdeby** [comment]
Please, use out the [forum](https://discuss.pytorch.org/) for questions as github issues are monitored for issues and feature requests only.
