### ISSUE TITLE
Abort all nccl communicators explicitly when destroy process group

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#32231]
right now, process group holds a vector of share_ptrs of nccl communicators, when process group is destroyed, the nccl communicators may be still held by pending/stuck processGroup::work. 

Ideally all nccl communicators should be aborted explicitly when process group is destroyed, otherwise pending nccl kernels may block any CUDA op to run even after destroying process group, this is not good for failure recovery

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by rohan-varma** [comment]
@zhaojuanmao I know some work recently went into NCCL error handling, is this issue still relevant/ Please feel free to close otherwise.

**Comment by jramapuram** [comment]
I just observed a deadlock on a 30 GPU distributed job using `pytortch1.5` from anaconda. What is the recommended workaround here?

**Comment by osalpekar** [comment]
cc @jiayisuse - related to NCCL reliability/error handling

**Comment by jiayisuse** [comment]
@osalpekar Yeah, we could do this clean up
