### ISSUE TITLE
`torch.isfinite` not supported in TorchScript

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#32245]
## 🐛 Bug

I am not sure if this is already tracked somewhere but `torch.isfinite` doesn't seem to have properly annotated output for TorchScript and fails when used along with `torch.all`.

## To Reproduce
The following fails
```python
import torch

@torch.jit.script
def fails(tensor):
    return torch.isfinite(tensor).all(dim=0)
```
with
```python
  File "torch_repro.py", line 3, in <module>
    @torch.jit.script
  File "/home/jatentaki/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::all(Tensor self) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'bool'.
  
  aten::all.dim(Tensor self, int dim, bool keepdim=False) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'bool'.
  
  aten::all.out(Tensor self, int dim, bool keepdim=False, *, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'bool'.

The original call is:
at torch_repro.py:5:11
@torch.jit.script
def fails(tensor):
    return torch.isfinite(tensor).all(dim=0)
           ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

whereas a very similar
```python
import torch

@torch.jit.script
def succeeds(tensor):
    return torch.isnan(tensor).all(dim=0)
```
succeeds.

## Expected behavior

Correct JIT compilation.
## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] cpuonly                   1.0                           0    pytorch
[conda] pytorch                   1.3.1               py3.7_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.4.2                  py37_cpu  [cpuonly]  pytorch

cc @suo

**Comment by driazati** [comment]
This should be fixed on master (your repro runs fine for me) with #28918, could you try the nightly version of PyTorch or wait a bit and try 1.4 when it comes out? If it still doesn't work, feel free to re-open this issue.

We're aware of a few ops that have problems like this, #30786 has the whole list
