### ISSUE TITLE
the results when using opset10 and when using opset11 are different.

### ISSUE THREAD

**Issue by schyun9212** [pytorch/pytorch#32267]
## 🐛 Bug

I am trying to export maskrcnn-benmark model to onnx. While I was debugging as my model failed to load with ShapeInferenceError, changing the opset version to get rid of following warning had different results.(10 -> 11).

```bash
UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 10. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode)
```

## To Reproduce
```python
import torch

from PIL import Image
from maskrcnn_benchmark.config import cfg
from predictor import COCODemo
from maskrcnn_benchmark.structures.image_list import ImageList
from maskrcnn_benchmark.structures.bounding_box import BoxList

import numpy as np
import onnx
import onnxruntime as ort

config_file = "./configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml"
cfg.merge_from_file(config_file)
cfg.merge_from_list(["MODEL.DEVICE", "cpu"])
cfg.freeze()

# Create model
coco_demo = COCODemo(
    cfg,
    confidence_threshold=0.7,
    min_image_size=800,
)

for p in coco_demo.model.parameters():
    p.requires_grad_(False)

class Backbone(torch.nn.Module):
    def __init__(self):
        super(Backbone, self).__init__()

    def forward(self, image):
        image_list = ImageList(image.unsqueeze(0), [(image.size(-2), image.size(-1))])

        result = coco_demo.model.backbone(image_list.tensors)
        return result

backbone = Backbone()
backbone.eval()

from torchvision import transforms as T
from torchvision.transforms import functional as F
from demo.predictor import Resize

def load_image(path):
    image = Image.open(path).convert("RGB")
    image = np.array(image)[:, :, [2, 1, 0]]
    return image

def build_transform(cfg):
    if cfg.INPUT.TO_BGR255:
        to_bgr_transform = T.Lambda(lambda x: x * 255)
    else:
        to_bgr_transform = T.Lambda(lambda x: x[[2, 1, 0]])

    normalize_transform = T.Normalize(
        mean=cfg.INPUT.PIXEL_MEAN, std=cfg.INPUT.PIXEL_STD
    )
    min_size = cfg.INPUT.MIN_SIZE_TEST
    max_size = cfg.INPUT.MAX_SIZE_TEST
    transform = T.Compose(
        [
            T.ToPILImage(),
            Resize(min_size, max_size),
            T.ToTensor(),
            to_bgr_transform,
            normalize_transform,
        ]
    )
    return transform

def transform_image(cfg, original_image):
    transforms = build_transform(cfg)
    image = transforms(original_image)
    from maskrcnn_benchmark.structures.image_list import to_image_list
    image_list = to_image_list(image, cfg.DATALOADER.SIZE_DIVISIBILITY)
    image_list = image_list.to(torch.device(cfg.MODEL.DEVICE))
    return (image_list.tensors[0], image.size(-1), image.size(-2))

original_image = load_image("./demo/sample.jpg")
from transform import transform_image
image, _, _ = transform_image(cfg, original_image)

expected_result = backbone(image)

BACKBONE_OPS10_PATH = "backbone_ops10.onnx"
BACKBONE_OPS11_PATH = "backbone_ops11.onnx"

torch.onnx.export(backbone, image, BACKBONE_OPS10_PATH,
                    verbose=False,
                    do_constant_folding=False,
                    opset_version=10, input_names=["i_image"])
torch.onnx.export(backbone, image, BACKBONE_OPS11_PATH,
                    verbose=False,
                    do_constant_folding=False,
                    opset_version=11, input_names=["i_image"])

ort_session = ort.InferenceSession(BACKBONE_OPS10_PATH)
input_feed = {ort_session.get_inputs()[0].name: image.numpy()}
backbone_ops10_result = ort_session.run(None, input_feed)

ort_session = ort.InferenceSession(BACKBONE_OPS11_PATH)
input_feed = {ort_session.get_inputs()[0].name: image.numpy()}
backbone_ops11_result = ort_session.run(None, input_feed)
```
I tried using demo image in maskrcnn-benchmark. The results are
```
# expected_value[0]
tensor([[[[ 0.9369, -0.8697, -0.7064,  ...,  1.3006,  1.4174,  0.8498],
          [ 2.8381,  2.0348,  0.8487,  ...,  0.9150,  0.8716,  0.4233],
          [ 3.2201,  3.5565,  1.5070,  ...,  1.1903,  1.1665,  0.7802],
          ...,

# backbone_ops10_result[0]
array([[[[ 0.9368568 , -0.8697343 , -0.7064086 , ...,  1.3005723 ,
           1.4173995 ,  0.8498174 ],
         [ 2.8381152 ,  2.0348258 ,  0.8486756 , ...,  0.9149905 ,
           0.87161803,  0.42327812],
         [ 3.2201462 ,  3.5565038 ,  1.5070242 , ...,  1.1903342 ,
           1.1665052 ,  0.7801977 ],
         ...,

# backbone_ops11_result[0]
array([[[[ 2.0550726e-01,  2.1759667e-02,  8.5308425e-02, ...,
           2.9880115e-01,  1.9291577e-01,  6.4862418e-01],
         [ 2.2530836e-01,  8.5458875e-01,  1.5711826e-01, ...,
          -1.4410090e+00, -1.6364489e+00, -6.3897264e-01],
         [ 2.4900815e-01,  1.4109960e+00,  2.4709302e-01, ...,
          -1.1907353e+00, -1.2746851e+00, -3.5361561e-01],
         ...,
```

## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.44
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] onnx==1.6.0
[pip3] onnxruntime==1.1.0
[pip3] onnxruntime-gpu==1.1.0
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect

I exported shape infered onnx model repectively. The result was shown differently.

OPSET 10

![Screenshot from 2020-01-16 13-00-41](https://user-images.githubusercontent.com/36091236/72492517-d2a0f080-3860-11ea-8507-800df7466e7f.png)

OPSET 11

![Screenshot from 2020-01-16 13-00-58](https://user-images.githubusercontent.com/36091236/72492520-d6347780-3860-11ea-87a5-01d49cf8771c.png)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by bpstark** [comment]
@schyun9212 I am trying to reproduce this issue, and am unable to use the code provided, can you please explain where "coco_demo.model.backbone(image_list.tensors)" is coming from? I do not see any import that would bring in coco_demo, and thus cannot even run your code.

**Comment by schyun9212** [comment]
Sorry @bpstark  I missed some code while editing the issue. I updated reproduce code.
Thank you.

**Comment by bpstark** [comment]
@schyun9212 This code is still not runable, can you provide a fully functional codebase.

**Comment by schyun9212** [comment]
@bpstark Can you tell me the error you met? The code base is [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark). In my case it works fine if I build the project and run the reproduction code.

**Comment by bpstark** [comment]
@schyun9212 
from demo.predictor import Resize fails
NameError: name 'Image' is not defined
np not defined  # this is at least an easy fix 
This is just the issues I have found so far, but once those get fixed there may be more

**Comment by schyun9212** [comment]
@bpstark I updated reproduction code. I had missed importing pillow and numpy. I'm really sorry for my mistake.

**Comment by bpstark** [comment]
@schyun9212 can you please provide the commit ID of maskrcnn-benchmark code you are using since latest master does not seem to be compatible with the version of pytorch you specified?

**Comment by schyun9212** [comment]
@bpstark I think the problem you met is due to the Pillow version. Because maskrcnn-benchmark is not compatible with Pillow > 7.0.0, I used 6.2.2 version. I tested this issue on lastest master branch.

**Comment by thiagocrepaldi** [comment]
@schyun9212 Is this still a relevant issue? COuld you provide a commit id and more information for an actual repro?

**Comment by thiagocrepaldi** [comment]
Closing as there is no response for a long time
