### ISSUE TITLE
'cannot initialize type "WorkerId"' crashing pytest in 1.4.0

### ISSUE THREAD

**Issue by david-alexander-white** [pytorch/pytorch#32270]
## 🐛 Bug

After the release today, my tests (pytest with pytest-cov enabled) are now failing with

```
collecting ... terminate called after throwing an instance of 'std::runtime_error'

[531]  what(): generic_type: cannot initialize type "WorkerId": an object with that name is already defined

[532] Fatal Python error: Aborted

[533] Current thread 0x00007f13cc0f4740 (most recent call first):

[534]  File "/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 16 in <module>
```

on linux. I’m not using any kind of RPC, and the failure occurs before I actually run any tests. i switched back to 1.3.1 and the problem went away.

was requested to submit an issue at https://discuss.pytorch.org/t/cannot-initialize-type-workerid-in-1-4-0/66805, don't have time right now to fill out the full report. can do if it would be super helpful, otherwise i'm just rolling back.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
Hey @david-alexander-white 

I installed v1.4 locally using conda, and tried RPC, but didn't see that error. Could you please add some more context to this issue? Which environment are you on? and what test are you trying to run?

**Comment by mrshenli** [comment]
Just adding some background here. `WorkerId` is a type we used to have in 1.3.1, but got removed in 1.4.0. So based in the error message below, it seems that `rpc/__init__.py` tries to call into `torch._C._rpc_init()` from 1.3.1?

```
[534]  File "/opt/conda/envs/pytorch/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 16 in <module>

```

**Comment by david-alexander-white** [comment]
thank you, that helped me figure it out. I think it's basically my fault.

what was going on was I was basically using pip to install something which had pytorch as a dependency, then using conda to install pytorch, and I think I ended up with a weird mishmash of both versions.

I think all that's happening is that conda hasn't updated their version to 1.4 yet. I'm pretty happy to close this if you are.

**Comment by mrshenli** [comment]
@david-alexander-white thanks for the clarification. Closing now :)

**Comment by shi27feng** [comment]
Hi,
I got same issue, even when imports pytorch, anybody knows what does it happen?

src$ python3
Python 3.7.6 (default, Dec 19 2019, 23:50:13) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "WorkerId": an object with that name is already defined
torchAborted (core dumped)

**Comment by mrshenli** [comment]
@shi27feng Based on the previous discussion, looks like you are using PyTorch v1.4 Python API with v1.3.1 shared object, i.e., v1.4 Python scripts are trying to call into v1.3.1 C++ code. Do you have two PyTorch versions in your dev envs?

**Comment by shi27feng** [comment]
@mrshenli Thanks for prompt reply.
I do have pytorch 1.4 installed, and I used command pip install --upgrade to update pytorch, do you mean the previous version (e.g 1.3.1) is still existing in my system?
Thanks again

**Comment by mrshenli** [comment]
@shi27feng looks like so, because the type `WorkerId` only exists in 1.3.1. Do you see the same trace as described in this issue (`torch/distributed/rpc/__init__.py` being the culprit)?

**Comment by shi27feng** [comment]
@mrshenli Hi, I just checked my system, I have only torch 1.4 and torchvision 0.5 installed, what else should I do? Thanks

**Comment by mrshenli** [comment]
Does it work if you pip uninstall them and then install it again?

**Comment by shi27feng** [comment]
@mrshenli OK, I'll try what you suggest, thanks again.

**Comment by david-alexander-white** [comment]
My problem was caused by having torch installed through both pip and conda,
my guess is it could be the same for you. You might try conda remove pytorch

**Comment by shi27feng** [comment]
@david-alexander-white Thanks, and @mrshenli is right, my torch 1.3.1 is really hidden by version 1.4. I tried uninstall twice and reinstall, then it works well now.

**Comment by mrshenli** [comment]
@soumith Does this mean `pip install --upgrade` cannot upgrade cleanly for us?
