### ISSUE TITLE
Hi i found a typo in the Documentation 

### ISSUE THREAD

**Issue by abdjava** [pytorch/pytorch#32279]
## 📚 Documentation

Hi so i was looking at the pytorch Documentation for torchvision.transforms at https://pytorch.org/docs/stable/torchvision/transforms.html
I found this typo .
![image](https://user-images.githubusercontent.com/44923912/72512376-e1c57580-3843-11ea-897c-bd64eb7b5998.png)

Looking at the highlighted part of the test it states
input[channel] = (input[channel] - mean[channel]) / std[channel]
but it should be 
Output[channel] = (input[channel] - mean[channel]) / std[channel]

as i understand .

cc @fmassa

**Comment by mrshenli** [comment]
Hey @abdjava, thanks for the catch! Your suggestion looks correct to me. Would you like to submit a PR to fix that?

**Comment by abdjava** [comment]
Sure  i am but bit new and unsure how to do so .  Do i just need branch the main pytorch git then change the file ? and call a pull request or are the more rules  . I had a look thought the git was unable to find the HTML file for that page could please point me the right direction .

**Comment by mrshenli** [comment]
The doc html is auto generated from code comments here:

https://github.com/pytorch/vision/blob/64917bcc58a8dbf9a93a41f36f739173c3706a7d/torchvision/transforms/transforms.py#L146-L151

> Do i just need branch the main pytorch git then change the file ? and call a pull request or are the more rules .

The comment lives in [pytorch/vision](https://github.com/pytorch/vision). So you need to clone that repo, and submit the pull request to that repo accordingly.

**Comment by abdjava** [comment]
Hi thanks for the help i made a pull request to fix the typo .
