### ISSUE TITLE
pytorch 1.4.0 doesn't compile

### ISSUE THREAD

**Issue by svenstaro** [pytorch/pytorch#32277]
## 🐛 Bug

pytorch 1.4.0 doesn't compile. During compiling, tons of errors like

```
/build/python-pytorch/src/pytorch-1.4.0/c10/util/LeftRight.h:67:10: error: ‘typename std::result_of<F(const T&)>::type c10::LeftRight<T>::read(F&&) const [with F = c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>; T = ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>; typename std::result_of<F(const T&)>::type = at::Tensor]’, declared using local type ‘c10::Dispatcher::doCallUnboxedOnly(const c10::DispatchTable&, const c10::LeftRight<ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction> >&, Args ...) const [with Return = at::Tensor; Args = {const at::Tensor&, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>, c10::ArrayRef<long int>}]::<lambda(const ska::flat_hash_map<c10::TensorTypeId, c10::KernelFunction>&)>’, is used but never defined [-fpermissive]
```
appear.

Full log: [build.txt.zip](https://github.com/pytorch/pytorch/files/4069839/build.txt.zip)

## To Reproduce

1. Get release 1.4.0
1. cd into the extracted dir
1. git submodule update --init --recursive
1. Set these:
```
  export VERBOSE=1
  export PYTORCH_BUILD_VERSION="${pkgver}"
  export PYTORCH_BUILD_NUMBER=1

  # Check tools/setup_helpers/cmake.py, setup.py and CMakeLists.txt for a list of flags that can be set via env vars.
  export USE_MKLDNN=OFF
  export USE_FFMPEG=ON
  export USE_GFLAGS=ON
  export USE_GLOG=ON
  export BUILD_BINARY=ON
  export USE_OPENCV=ON
  export USE_SYSTEM_NCCL=ON
  export CUDAHOSTCXX=g++-8
  export CUDA_HOME=/opt/cuda
  export CUDNN_LIB_DIR=/usr/lib
  export CUDNN_INCLUDE_DIR=/usr/include
  export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
  export TORCH_CUDA_ARCH_LIST="3.2;3.5;3.7;5.0;5.2;5.3;6.0;6.0+PTX;6.1;6.1+PTX;6.2;6.2+PTX;7.0;7.0+PTX;7.2;7.2+PTX;7.5;7.5+PTX"
  export USE_CUDA=0
  export USE_CUDNN=0
```
5. python setup.py build

## Expected behavior

It should compile cleanly.

## Environment

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.2.89

OS: Arch Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.44
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.3.1
[conda] Could not collect

## Additional context

I'm the packager for the official Arch Linux pytorch package and so this currently blocks the update to 1.4.0 in Arch.

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by soumith** [comment]
cc: @smessmer @ezyang

**Comment by ezyang** [comment]
Does it get fixed if you cherry-pick https://github.com/pytorch/pytorch/pull/30333 ? (I'm not sure but you might also need https://github.com/pytorch/pytorch/pull/30332 , not sure.) I verified the patch applies cleanly but haven't tried compiling with it.

**Comment by smessmer** [comment]
if you patch #30333 you do also need #30332 or PyTorch could run into race conditions.

**Comment by svenstaro** [comment]
The patches do appear to work.

**Comment by soumith** [comment]
@svenstaro shall I create a branch (and eventually a tag) called v1.4.0.1 for your purposes? or do you prefer to use the two patches directly?

**Comment by svenstaro** [comment]
Making a new release would be nice for everyone. :)

**Comment by rgommers** [comment]
> (and eventually a tag) called v1.4.0.1

Minor comment: that's not a PEP 440 compliant version number. I'm not sure if it gives problems with recent `pip` for example, but it's not guaranteed to work. This looks like a normal bugfix release, so `1.4.1` would be nicer. There's also `.post0` you can tack on instead, but those are a bit non-standard and really only meant for, e.g., rebuilding binaries without source code changes.

**Comment by tgandor** [comment]
This problem also comes up when building Python packages like `detectron2` (platform: anaconda, python 3.7 on Manjaro, torch 1.4.0 from PyPI). A workaround for me was having, and using, GCC 8:
`CC=gcc-8 CXX=g++-8 python setup.py install`

**Comment by rgommers** [comment]
Ah yes. I ran into a bunch of issues on Arch Linux with GCC 9.1 as default before. New ones keep getting introduced; the structural solution would be to add a new CI job or change an existing one to use GCC 9.1 I'd think.

**Comment by svenstaro** [comment]
How about that new release?
