### ISSUE TITLE
pytorch sets the usage of one graphics card to 60% and the usage of the other graphics card to 40%.

### ISSUE THREAD

**Issue by gengyanlei** [pytorch/pytorch#32273]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by gengyanlei** [comment]
Excuse me, how does it work?

**Comment by mrshenli** [comment]
Hey @gengyanlei, if this is a question, please submit to [PyTorch Forum](https://discuss.pytorch.org/). To report a bug, please add more context and some instructions to reproduce. 

I am closing this issue now. Please feel free to create new ones when you have more context. Thanks!
