### ISSUE TITLE
Python 3.8 serialization error

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#32289]
## 🐛 Bug

Error text:
```pytb
======================================================================
ERROR: test_serialization_filelike_api_requirements (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4446, in test_serialization_filelike_api_requirements
    _ = torch.load(filemock)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

======================================================================
ERROR: test_serialization_filelike_missing_attrs (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4473, in test_serialization_filelike_missing_attrs
    self._test_serialization_filelike(to_serialize, mock, desc)
  File "test_torch.py", line 4458, in _test_serialization_filelike
    b = torch.load(data)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

======================================================================
ERROR: test_serialization_filelike_stress (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4479, in test_serialization_filelike_stress
    self._test_serialization_filelike(a, lambda x: FilelikeMock(x, has_readinto=False),
  File "test_torch.py", line 4458, in _test_serialization_filelike
    b = torch.load(data)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 590, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\serialization.py", line 754, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

----------------------------------------------------------------------
Ran 3620 tests in 103.071s
```

## To Reproduce

1. python test_torch.py

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): e4db0a5
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @peterjc123 @suo

**Comment by peterjc123** [comment]
I've skipped them in https://github.com/pytorch/pytorch/pull/32215.

**Comment by soumith** [comment]
not just windows. reproduced on OSX / Linux

**Comment by Tpt** [comment]
I just got this problem too with Flair on Python 3.8:

```
state = torch.load(f, map_location=flair.device)
  File "/usr/lib/python3.8/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/lib/python3.8/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes
```

**Comment by ngoldbaum** [comment]
I can reproduce this on Python 3.8.1. Note that on `master` these tests have moved to `tests/test_serialization.py`.

**Comment by ngoldbaum** [comment]
I've created https://bugs.python.org/issue39681 as I'm not sure if this was an intentional change in CPython.

@Tpt any chance you can share a little bit more context for that error? It would be nice to know how you created `f`. If you can make a short example I can copy/paste and run locally that would be even better.

**Comment by ngoldbaum** [comment]
So I *think* the issue with flair comes down to it no longer being possible to unpickle a memory-mapped file, see https://bugs.python.org/issue39681#msg362291.

**Comment by ngoldbaum** [comment]
@ezyang do you think it's sufficient to wait on CPython for a fix or do you think we need to have some kind of workaround in pytorch?

**Comment by ezyang** [comment]
Well, even when it's upstream's fault, it's not much solace for your SOL users. Depends on how hard working around it our end is.

**Comment by pitrou** [comment]
As pointed in the CPython bug report, if you're unpickling from a mmap object, it's far more efficient to do so directly from memory:
```python
data = pickle.loads(memoryview(mmap_object))
```
than to issue `read()` calls by treating the mmap as a regular file object:
```python
data = pickle.load(mmap_object)
```
The former is able to do less memory copies and also avoids indirections through the file object.
(try both on Python 3.7 and large pickled data)
