### ISSUE TITLE
Use system NCCL library in PyTorch

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#32286]
## 🐛 Bug

In **setup.py** in **Environment variables for feature toggles:** section
>    USE_SYSTEM_NCCL=0
>      disables use of system-wide nccl (we will use our submoduled
>      copy in third_party/nccl)

however, in reality building PyTorch master without providing **USE_SYSTEM_NCCL** flag will build bundled version. To use system NCCL user should explicitly provide **USE_SYSTEM_NCCL=1**.
It might be a bug in configuration process which is unable to set system NCCL properly without **USE_SYSTEM_NCCL** flag or misleading documentation in **setup.py** as enabling toggles have slightly different usage comparing to disabling toggles.

## To Reproduce

1. `python3 setup.py build`
builds bundled NCCL library
2. `USE_SYSTEM_NCCL=1 python3 setup.py build`
builds with system NCCL library

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.2/7.6.5

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by h6197627** [comment]
Another problem is that while building with
`USE_SYSTEM_NCCL=1 python3 setup.py build`
Gloo is emiting warning about not able to find NCCL and disabling its support for it.

**Comment by mrshenli** [comment]
> however, in reality building PyTorch master without providing USE_SYSTEM_NCCL flag will build bundled version. To use system NCCL user should explicitly provide USE_SYSTEM_NCCL=1.

This means by default it uses the bundled NCCL in submodules, and that seems like the correct action to me. Because all tests will be run with the bundled version, which helps to make sure they are compatible. If users would like to use the system NCCL, that needs to be explicit I think. 

@h6197627 Are you suggesting to use system NCCL by default? Or will adding more clarification comments in `setup.py` help here?

**Comment by mrshenli** [comment]
> Another problem is that while building with `USE_SYSTEM_NCCL=1 python3 setup.py build`
Gloo is emiting warning about not able to find NCCL and disabling its support for it.

This is indeed a problem we need to fix.

**Comment by h6197627** [comment]
I think some clarification in setup.py will be helpful. It can be changed like other flags that require explicit user setting for enabling some additional functionality (for example USE_IBVERBS or USE_OPENCV)
Something like:
```
# USE_SYSTEM_NCCL
#     enables use of system-wide nccl
```

Considering Gloo, somehow it is failing to find nccl.h header (I don't know why - cmake scripts looks correct). However, I tried to checkout and configure standalone Gloo source and it is able to find NCCL.

**Comment by mrshenli** [comment]
> Considering Gloo, somehow it is failing to find nccl.h header

@pietern does Gloo have dependency on NCCL?

**Comment by h6197627** [comment]
Another strange thing:
I am building PyTorch without setting USE_SYSTEM_NCCL flag. Configuration step outputs:

> --   USE_NCCL              : ON
> --     USE_SYSTEM_NCCL     : OFF

Than building process outputs:

> Linking    libnccl.so.2.4.8                    > /home/user/Work/pytorch/build/nccl/lib/libnccl.so.2.4.8
> Archiving  libnccl_static.a                    > /home/user/Work/pytorch/build/nccl/lib/libnccl_static.a
> [ 75%] No install step for 'nccl_external'
> [ 75%] Completed 'nccl_external'
> [ 75%] Built target nccl_external

But after successful building checking with ldd outputs:

> ldd /usr/local/lib/python3.6/dist-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so | grep nccl                                                                                                          
> libnccl.so.2 => /usr/lib/x86_64-linux-gnu/libnccl.so.2 (0x00007fd1c52ff000)

And

> ls -lA /usr/lib/x86_64-linux-gnu/ | grep libnccl                                                                                                                            
> lrwxrwxrwx  1 root root        12 Nov 11 03:05 libnccl.so -> libnccl.so.2
> lrwxrwxrwx  1 root root        16 Nov 11 03:05 libnccl.so.2 -> libnccl.so.2.5.6
> -rw-r--r--  1 root root  77292848 Nov 11 03:05 libnccl.so.2.5.6
> -rw-r--r--  1 root root  78485032 Nov 11 03:05 libnccl_static.a

Actually, the one that is really linked to NCCL is:

> readelf -d /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so | grep nccl
> 0x0000000000000001 (NEEDED)             Shared library: [libnccl.so.2]

So, at the end, it looks like PyTorch is still using system NCCL library

**Comment by Dirtybluer** [comment]
> Another strange thing:
> I am building PyTorch without setting USE_SYSTEM_NCCL flag. Configuration step outputs:
> 
> > -- Found NCCL: /usr/include
> > -- Determining NCCL version from the header file: /usr/include/nccl.h
> > -- NCCL_MAJOR_VERSION: 2
> > -- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
> > ...
> > --   USE_NCCL              : ON
> > --     USE_SYSTEM_NCCL     : OFF
> 
> Than building process outputs:
> 
> > Linking    libnccl.so.2.4.8                    > /home/user/Work/pytorch/build/nccl/lib/libnccl.so.2.4.8
> > Archiving  libnccl_static.a                    > /home/user/Work/pytorch/build/nccl/lib/libnccl_static.a
> > [ 75%] No install step for 'nccl_external'
> > [ 75%] Completed 'nccl_external'
> > [ 75%] Built target nccl_external
> 
> But after successful building checking with ldd outputs:
> 
> > ldd /usr/local/lib/python3.6/dist-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so | grep nccl
> > libnccl.so.2 => /usr/lib/x86_64-linux-gnu/libnccl.so.2 (0x00007fd1c52ff000)
> 
> And
> 
> > ls -lA /usr/lib/x86_64-linux-gnu/ | grep libnccl
> > lrwxrwxrwx  1 root root        12 Nov 11 03:05 libnccl.so -> libnccl.so.2
> > lrwxrwxrwx  1 root root        16 Nov 11 03:05 libnccl.so.2 -> libnccl.so.2.5.6
> > -rw-r--r--  1 root root  77292848 Nov 11 03:05 libnccl.so.2.5.6
> > -rw-r--r--  1 root root  78485032 Nov 11 03:05 libnccl_static.a
> 
> Actually, the one that is really linked to NCCL is:
> 
> > readelf -d /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cuda.so | grep nccl
> > 0x0000000000000001 (NEEDED)             Shared library: [libnccl.so.2]
> 
> So, at the end, it looks like PyTorch is still using system NCCL library

I've encountered similar confusion, finding PyTorch is seemingly using system NCCL library. I've been building PyTorch 1.0 (for some needs) from source. 
An error `libnccl.so.2: cannot open shared object file: No such file or directory` occurs when there is no file named `libnccl.so.2` under `/usr/lib/x86_64-linux-gnu/`(I guess this is where system-wide NCCL lies).
Strange enough, this seems to happen only when you built PyTorch from source.
When I tried installing Pytorch via anaconda I discovered:
1. it works fine without any file named `libnccl.so.2`
2. nothing was output when I ran `ldd _C.cpython-36m-x86_64-linux-gnu.so | grep nccl`
3. there isn't any file named `libtorch_cuda.so`

Then I start to wonder where is the NCCL library it uses?

**Comment by h6197627** [comment]
> Then I start to wonder where is the NCCL library it uses?

I guess Anaconda version is using statically linked version of NCCL (and probably this is the write thing for avoiding collisions with system libraries). The question is why PyTorch built manually from the source is not doing the same.

**Comment by h6197627** [comment]
Fixed in #82773
