### ISSUE TITLE
Pytorch 1.4.0 deadlock in multiprocessing 

### ISSUE THREAD

**Issue by rtaori** [pytorch/pytorch#32299]
## 🐛 Bug

PyTorch 1.4.0 deadlocks when using queues and events with multiprocessing.

## To Reproduce
Minimal example:
```
import torch.multiprocessing as mp

def main_worker(gpu, queue, event):
    print(f'gpu {gpu} putting into queue')
    queue.put({'gpu': gpu})

    print(f'gpu {gpu} waiting')
    event.wait()

def main():
    num_gpus = 4

    queue = mp.Queue()
    event = mp.Event()

    jobs = []
    for i in range(num_gpus):
        p = mp.Process(target=main_worker, args=(i, queue, event))
        p.start()
        jobs.append(p)

    print('started processes')

    for i in range(num_gpus):
        print(f'getting {i}th queue value')
        d = queue.get()
        print(d)

    event.set()
    for p in jobs:
        p.join()

main()
```
Output:
```
started processes
getting 0th queue value
gpu 1 putting into queue
gpu 0 putting into queue
gpu 3 putting into queue
gpu 2 putting into queue
```
And then it hangs

## Expected behavior
Using python multiprocessing API does not have this bug
```
import multiprocessing as mp

def main_worker(gpu, queue, event):
    print(f'gpu {gpu} putting into queue')
    queue.put({'gpu': gpu})

    print(f'gpu {gpu} waiting')
    event.wait()

def main():
    num_gpus = 4

    queue = mp.Queue()
    event = mp.Event()

    jobs = []
    for i in range(num_gpus):
        p = mp.Process(target=main_worker, args=(i, queue, event))
        p.start()
        jobs.append(p)

    print('started processes')

    for i in range(num_gpus):
        print(f'getting {i}th queue value')
        d = queue.get()
        print(d)

    event.set()
    for p in jobs:
        p.join()

main()
```
Output:
```
gpu 0 putting into queue
started processes
getting 0th queue value
gpu 1 putting into queue
gpu 0 waiting
popped {'gpu': 0}
getting 1th queue value
gpu 1 waiting
gpu 2 putting into queue
popped {'gpu': 1}
getting 2th queue value
gpu 3 putting into queue
gpu 2 waiting
popped {'gpu': 2}
getting 3th queue value
gpu 3 waiting
popped {'gpu': 3}
```
## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] efficientnet-pytorch      0.4.0                    pypi_0    pypi
[conda] mkl                       2019.3                      199
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.10           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

**Comment by mrshenli** [comment]
Have you tried using `SimpleQueue ` and `spawn` mode as suggested in the [doc](https://pytorch.org/docs/stable/notes/multiprocessing.html)?

**Comment by rtaori** [comment]
Yes, I had initially started with those, but none of those changes help. I provided this example here since it is exactly comparable to the python version (which works).

**Comment by rtaori** [comment]
Upon revisiting the issue, the problem is actually with `mp.spawn`. I'm closing this issue and have created a new one at #32322
