### ISSUE TITLE
LibTorch nightly build is not available on https://pytorch.org/

### ISSUE THREAD

**Issue by ziyuv** [pytorch/pytorch#32329]
## 🐛 Bug

For example, https://download.pytorch.org/libtorch/nightly/cu101/libtorch-cxx11-abi-shared-with-deps-latest.zip is pointing to 1.4.0 instead of actual nightly build as of submitting this bug report.

## To Reproduce

N/A

## Expected behavior

Expect nightly build of LibTorch.

## Environment

N/A

## Additional context

N/A

cc @ezyang @gchanan @zou3519

**Comment by soumith** [comment]
@yf225 has been working on fixing this

**Comment by yf225** [comment]
https://github.com/pytorch/builder/pull/394 is merged which should fix it. I will check and make sure that the nightly build tonight is up to date.

**Comment by ziyuv** [comment]
Appreciate it. I'll check, too. Thanks!

**Comment by yf225** [comment]
libtorch nightly build is up to date again. Closing this issue.
