### ISSUE TITLE
CUDA MPS system

### ISSUE THREAD

**Issue by tarungog** [pytorch/pytorch#32332]
## 🚀 Feature

Enable PyTorch to work with MPS in multiple processes. Currently program just crashes if you start a second one.

## Motivation
Certain shared clusters have CUDA exclusive mode turned on and must use MPS for full system utilization. If there is an easy way to make PyTorch work with MPS, would be great.

## Pitch
https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

cc @ngimel

**Comment by andyljones** [comment]
Github pointed me at this while filing [this bug](https://github.com/pytorch/pytorch/issues/32575), and I can only say I haven't had this problem with multiple PyTorch processes using MPS. The linked bug aside, it all works fine.

**Comment by ngimel** [comment]
@tarungog our experiments also show that pytorch works with mps out of the box (bugs like @andyljones reported aside), so I'm closing this issue as MPS is already supported. Please file bug reports if you encounter problems.

**Comment by venkataganti** [comment]
> Github pointed me at this while filing [this bug](https://github.com/pytorch/pytorch/issues/32575), and I can only say I haven't had this problem with multiple PyTorch processes using MPS. The linked bug aside, it all works fine. My system is
> 
> ```
> PyTorch version: 1.4.0
> Is debug build: No
> CUDA used to build PyTorch: 10.1
> 
> OS: Ubuntu 18.04.3 LTS
> GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
> CMake version: Could not collect
> 
> Python version: 3.7
> Is CUDA available: Yes
> CUDA runtime version: 10.1.243
> GPU models and configuration: 
> GPU 0: GeForce RTX 2080 Ti
> GPU 1: GeForce RTX 2080 Ti
> 
> Nvidia driver version: 440.26
> cuDNN version: Could not collect
> 
> Versions of relevant libraries:
> [pip] numpy==1.18.1
> [pip] torch==1.4.0
> [pip] torchfile==0.1.0
> [pip] torchvision==0.5.0
> [conda] blas                      1.0                         mkl  
> [conda] mkl                       2019.4                      243  
> [conda] mkl-service               2.3.0            py37he904b0f_0  
> [conda] mkl_fft                   1.0.15           py37ha843d7b_0  
> [conda] mkl_random                1.1.0            py37hd6b4f25_0  
> [conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
> [conda] torchfile                 0.1.0                    pypi_0    pypi
> [conda] torchvision               0.5.0                py37_cu101    pytorch
> ```
@andyljones I am trying to run two pytorch programs with MPS (nvidia), but I dont see any concurency. Instead I see the GPU is running them in serial (one after the other), like time slicing. I am running the MPS with the following setings:

**sudo nvidia-smi -c EXCLUSIVE_PROCESS
sudo nvidia-cuda-mps-control -d**

The pytorch code is very simple:

    **a = torch.randn(10000, 10000).cuda()
    b = torch.randn(10000, 10000).cuda()
    while True :
        result = torch.matmul(a, b)
        mean = result.mean()
        toc = time.perf_counter()**
    
Please advise if you have any suggestions.
