### ISSUE TITLE
missing LAPACK

### ISSUE THREAD

**Issue by DBordo** [pytorch/pytorch#32344]
## Issue description

after installing pytorch on Jetson xavier agx
with this steps:
1) wget https://nvidia.box.com/shared/static/phqe92v26cbhqjohwtvxorrwnmrnfx1o.whl -O torch-1.3.0-cp36-cp36m-linux_aarch64.whl
2) pip3 install numpy torch-1.3.0-cp36-cp36m-linux_aarch64.whl

3) sudo apt-get install libjpeg-dev zlib1g-dev
4) git clone --branch v0.4.2 https://github.com/pytorch/vision torchvision
5) cd torchvision
6) sudo python setup.py install
7) cd ../
8) cd pytorch
9) git clone --recursive --branch v1.3.0 http://github.com/pytorch/pytorch

10) export USE_NCCL=0
11) export USE_DISTRIBUTED=0
12) export TORCH_CUDA_ARCH_LIST="5.3;6.2;7.2"
13) export PYTORCH_BUILD_VERSION=1.3.0
14) export PYTORCH_BUILD_NUMBER=1

15) sudo apt-get install python3-pip cmake
16) sudo pip3 install -U setuptools
17) sudo pip3 install -r requirements.txt
18) pip3 install scikit-build --user
19) pip3 install ninja --user
20) python3 setup.py bdist_wheel
when i use simple functions as torch.solve or torch.lu i receving error that 

## Code example
>>> import torch
>>> A = torch.randn(2, 3, 3)
>>> A_LU, pivots = torch.lu(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier/.local/lib/python3.6/site-packages/torch/functional.py", line 798, in lu
    result = torch._lu_with_info(A, pivot=pivot, check_errors=(not get_infos))
RuntimeError: lu: LAPACK library not found in compilation

## System Info
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.326

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.166
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/aarch64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.3.0
[pip3] torchvision==0.4.2
[conda] Could not collect

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): **described above**
- Build command you used (if compiling from source): **described above**

**Comment by mrshenli** [comment]
@DBordo does the problem persist if you switch to 1.3.1 or 1.4.0?

Hey @orionr, I saw you authored the lines below. If LAPACK is not available in the env, wouldn't we set `USE_LAPACK` to 0 and skip them in build?

https://github.com/pytorch/pytorch/blob/1f1ce53e8e93c80b3f88b9e6c84013a037e9c074/cmake/Dependencies.cmake#L1363-L1366

**Comment by DBordo** [comment]
Nvidia released the wheel for 1.4.0 today
But the link is corrupt and we waiting for new link.

Can i install 1.4.0 without using wheel on Jetson platform?

**Comment by soumith** [comment]
@dusty-nv the wheels are not linking to any LAPACK. Looks like a packaging problem. What BLAS are you linking to on ARM?

**Comment by dusty-nv** [comment]
@soumith the PyTorch 1.4 wheels for Jetson were built with OpenBLAS.  The links are now working:  https://devtalk.nvidia.com/default/topic/1049071/jetson-nano/pytorch-for-jetson-nano-version-1-4-0-now-available/

**Comment by mruberry** [comment]
This issue appears to have been resolved. @DBordo, if you're still encountering this issue would you please update and reopen it?
