### ISSUE TITLE
NCCL_ROOT_DIR in Cmake FindNCCL

### ISSUE THREAD

**Issue by ChaiBapchya** [pytorch/pytorch#32342]
## 🐛 Bug

1. NCCL_ROOT_DIR is deprecated according to https://cmake.org/cmake/help/latest/policy/CMP0074.html

But still why is it being "marked as advanced"
https://github.com/pytorch/pytorch/blob/ef5ae4823a00923342c82e08dd06adf579f5bc26/cmake/Modules/FindNCCL.cmake#L88

2. In this file - https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindNCCL.cmake

Why aren't we checking if nccl.h exists in the default location for unix - /usr/local/cuda

Or is it being done implicitly somewhere?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment]
Not sure why we mark them as advanced variables here, maybe @pietern can help explain.

> Why aren't we checking if nccl.h exists in the default location for unix - /usr/local/cuda

I guess this is because by default we use the bundled NCCL in submodules, and only use system NCCL when `USE_SYSTEM_NCCL` is set to 1. This guarantees that the default compile procedure will use compatible NCCL and torch.distributed versions.

**Comment by ChaiBapchya** [comment]
@mrshenli I checked pytorch codebase to see where USE_SYSTEM_NCCL case is being handled under cmake I couldn't find one. Would be great to see it pointed out if that's not too much to ask.
Thanks again!

**Comment by mrshenli** [comment]
Hey @ChaiBapchya, git grep gives me the following output:

```
CMakeLists.txt:    USE_SYSTEM_NCCL "Use system-wide NCCL" OFF
cmake/External/nccl.cmake:  if (USE_SYSTEM_NCCL)
cmake/Summary.cmake:    message(STATUS "    USE_SYSTEM_NCCL     : ${USE_SYSTEM_NCCL}")
setup.py:#   USE_SYSTEM_NCCL=0
setup.py:        if cmake_cache_vars['USE_NCCL'] and cmake_cache_vars['USE_SYSTEM_NCCL']:
torch/CMakeLists.txt:    if (USE_SYSTEM_NCCL)
```

Looks like this is how it gets into cmake:

https://github.com/pytorch/pytorch/blob/9a4219eb39ca02b759b8bb0790fcd4c66695ab6e/setup.py#L401-L403

**Comment by ChaiBapchya** [comment]
Oh so basically `cmake_cache_vars['USE_SYSTEM_NCCL']` is by default pointing to `/usr/local/cuda` for UNIX?

**Comment by mrshenli** [comment]
> Oh so basically cmake_cache_vars['USE_SYSTEM_NCCL'] is by default pointing to /usr/local/cuda for UNIX?

Given the above code, it will look for system NCCL using env vars `NCCL_LIBRARIES` and `NCCL_INCLUDE_DIRS`

**Comment by zhaojuanmao** [comment]
looks like it is resolved
