### ISSUE TITLE
torch.nn.LogSoftmax doesn't take dim argument

### ISSUE THREAD

**Issue by abisee** [pytorch/pytorch#3235]
I'm trying to use the torch.nn.LogSoftmax module and I want to specify the dim. I tried
```
ls = torch.nn.LogSoftmax(dim=1)
```
as indicated in the [docs](http://pytorch.org/docs/master/nn.html?highlight=nllloss#torch.nn.LogSoftmax) but got
```
TypeError: __init__() got an unexpected keyword argument 'dim'
```
I'm running pytorch version 0.2.0_4.

Thanks!

**Comment by soumith** [comment]
that change hasn't gotten into a release yet. we are finally cutting a release in the week of November 1st, which will include that change. You are looking at docs for master branch. You can click the small dropdown and get to versioned docs: http://pytorch.org/docs/versions.html

**Comment by Atcold** [comment]
@soumith, is this new release out?

**Comment by fmassa** [comment]
@Atcold a new release is planned for Monday or Tuesday

**Comment by ranhan429** [comment]
not working for me (torch.__version__ => '0.2.0_4')
Any updates?
