### ISSUE TITLE
Gaps for making template-unboxing work for all operators

### ISSUE THREAD

**Issue by smessmer** [pytorch/pytorch#32366]
This is a follow-up task to https://github.com/pytorch/pytorch/issues/24132

Background
-------
About 25% of our operators are currently using the new templated mechanism for unboxing operators when they're called from a boxed world like JIT or Mobile. The other 75% still use the old mechanism where we run a Python codegen script to generate the C++ code doing the unboxing. We want to use the templated mechanism everywhere, but there's a few issues we have to fix first.

Note: If an op uses the templated mechanism or the codegen mechanism is determined by the `use_c10_dispatcher` flag in `native_functions.yaml`. If it is set to `use_c10_dispatcher: full`, then it uses the templated mechanism. If it is set to anything else (or if it is missing), then it uses the codegen mechanism.

Gaps
------
The percentage numbers in parentheses denote how many of our ops are using this feature

- [x] (17%) out functions don't work
   - [x] they have different argument order in C++ as in the jit schema (https://github.com/pytorch/pytorch/pull/47711, https://github.com/pytorch/pytorch/pull/47712, https://github.com/pytorch/pytorch/pull/47792, https://github.com/pytorch/pytorch/pull/47793, https://github.com/pytorch/pytorch/pull/48910, https://github.com/pytorch/pytorch/pull/48911, https://github.com/pytorch/pytorch/pull/48912, https://github.com/pytorch/pytorch/pull/49006, https://github.com/pytorch/pytorch/pull/49012)
   - [x] they use `Tensor&` instead of `const Tensor&` (https://github.com/pytorch/pytorch/pull/42712)
- [x] (9%) Tensor? (i.e. optional tensor) doesn't work nicely with undefined tensor sometimes being undefined tensor and sometimes being None. (https://github.com/pytorch/pytorch/pull/41610, https://github.com/pytorch/pytorch/pull/41947)
- [x] (6%) TensorOptions ops don't work
  - [x] They have different dispatch algorithms in the boxed and the unboxed world (https://github.com/pytorch/pytorch/pull/36562)
  - [x] They have different runtime representations (packed vs unpacked) in the boxed and the unboxed world (not sure if this is still an issue) (https://github.com/pytorch/pytorch/pull/39492, https://github.com/pytorch/pytorch/pull/39611)
  - [x] Backend Select currently doesn't work with `use_c10_dispatcher: full` because  gen_backend_select_register.py doens't support it yet (https://github.com/pytorch/pytorch/pull/39492)
  - [x] They have different signatures (https://github.com/pytorch/pytorch/pull/39611, https://github.com/pytorch/pytorch/pull/41169)
- [x] Argument types not supported in the function schema inference yet:
  - [x] (8%) ScalarType (https://github.com/pytorch/pytorch/pull/39492)
  - [x] (6%) Device (https://github.com/pytorch/pytorch/pull/39492)
  - [x] (6%) Layout (https://github.com/pytorch/pytorch/pull/39492)
  - [x] (1%) Storage (https://github.com/pytorch/pytorch/pull/49146)
  - [x] (4%) Generator (https://github.com/pytorch/pytorch/pull/26434)
  - [x] (4%) Dimname (https://github.com/pytorch/pytorch/pull/49008)
  - [x] (1%) MemoryFormat (https://github.com/pytorch/pytorch/pull/39492)
  - [x] (1%) ConstQuantizerPtr (https://github.com/pytorch/pytorch/pull/49150, https://github.com/pytorch/pytorch/pull/49463)
- [x] (15%) Fixed size arrays don't work yet (https://github.com/pytorch/pytorch/pull/34399)
- [x] (14%) ArrayRef arguments don't work, the custom op API expects `torch::List`. (https://github.com/pytorch/pytorch/pull/34335)
- [x] (1%) Lists of optional tensors (i.e. `Tensor?[]`) don't work yet (https://github.com/pytorch/pytorch/pull/49138)
- [x] (1%) Optional lists (i.e. `Dimname[]?`) don't work yet (https://github.com/pytorch/pytorch/pull/49088)
- [x] (14%) Multiple return values work differently
- [x] (4%) Generator is currently a dispatch-relevant argument for unboxed dispatch but boxed dispatch ignores it. This is because it is a JIT type but not an IValue type, so boxed dispatch cannot recognize it. We need to either make it a full IValue type and add it to boxed dispatch or remove it from unboxed dispatch. (https://github.com/pytorch/pytorch/pull/49013)

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by zdevito** [comment]
ScalarType, Device, Layout, Dimname, Generator, and MemoryFormat can be added as types to JIT, and values to IValue. I think Generator may actually already be an unused type.
Storage and ConstQuantizerPtr warrant more discussion. ConstQuantizerPtr is weirdly named, might be fine if it were called Quantizer.
