### ISSUE TITLE
Dimension issue with `softmax` and related functions for 1D tensors

### ISSUE THREAD

**Issue by iffsid** [pytorch/pytorch#3238]
There seems to be an erroneous dimension calculation for any function that uses the `_get_softmax_dim` private function. If the input is a 1D tensor, the implicit dimension computed is 1, which is a problem since `dim=1` is invalid for a 1D tensor.

Minimal reproducible example:
``` python
import torch
from torch.nn.functional import softmax
from torch.autograd import Variable
s = softmax(Variable(torch.zeros(3)))
```
This produces the error:
```
/<..>/.virtualenvs/pytorch/bin/ipython:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  #!/<...>/.virtualenvs/pytorch/bin/python2.7
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-82ccfcf6f7ce> in <module>()
----> 1 softmax(Variable(torch.Tensor([1,2,3])))

/<...>/.virtualenvs/pytorch/lib/python2.7/site-packages/torch/nn/functional.pyc in softmax(input, dim, _stacklevel)
    658     if dim is None:
    659         dim = _get_softmax_dim('softmax', input.dim(), _stacklevel)
--> 660     return torch._C._nn.softmax(input, dim)
    661 
    662 

RuntimeError: invalid argument 4: dim out of range (got 1, but input has 1 dims) at /<...>/pytorch/torch/lib/THNN/generic/SoftMax.c:19
```
I'm running pytorch installed from source, from `master` (off of commit dc6510f7)

**Comment by apaszke** [comment]
Ah of course. Will send a fix today. Sorry for the trouble

**Comment by herlimenezes** [comment]
I got a similar error when following tutorial 
http://pytorch.org/tutorials/beginner/nlp/deep_learning_tutorial.html
There was a warning:

**Comment by herlimenezes** [comment]
Solved stating 
** usual imports **

> torch.manual_seed(1)
dim = 0

data2 = autograd.Variable(torch.randn(5))
print(data2)
print(F.softmax(data2, dim))
print(F.softmax(data2, dim).sum())
print(F.log_softmax(data2, dim))

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/commit/638b10d39bb5e1a62f4cf9dfd577654f8663810a

**Comment by martinbel** [comment]
This works fine but the same issue is present in nn.Softmax().
