### ISSUE TITLE
Changing last linear layer of a pretrained model changes the activation to tanh(x)

### ISSUE THREAD

**Issue by Asa-Nisi-Masa** [pytorch/pytorch#32388]
## 🐛 Bug

When loading the mobilenet_v2 model and changing the last classifier linear layer to accompany a different number of classes, the activation gets also changed (from f(x) = x to f(x) = tanh(x)).

## To Reproduce

Run the example code below. Before changing the last layer the output is in the range [-inf, inf], after changing it, it is in the range [-1, 1].

```
import torch
from torchvision import models


model = models.mobilenet_v2(pretrained=True)
# last layer(s) defined in model.classifier

print(model.classifier)
# Sequential(
# (0): Dropout(p=0.2, inplace=False)
# (1): Linear(in_features=1280, out_features=1000, bias=True)
# )

x = torch.randn((1, 3, 224, 224))
y = model.forward(x)

print(y.min().item(), y.max().item())
# -3.4289, 2.9577

# change the last layer to predict 3 classes
model.classifier[1] = torch.nn.Linear(in_features=1280, out_features=3, bias=True)

y = model.forward(x)
print(y.min().item(), y.max().item())
# -0.185, 0.6268
```

## Expected behavior

I expect the last print statement to output numbers outside of the range [-1, 1] as well. Even after putting the last two lines in a loop I never get values outside that range.

## Environment

Collecting environment information...
PyTorch version: 1.2.0+cpu
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Microsoft Windows 10 Pro
GCC version: (tdm-1) 5.1.0
CMake version: version 3.15.3

Python version: 3.5
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 710M
Nvidia driver version: 376.51
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.2.0+cpu
[pip3] torchvision==0.4.1
[conda] Could not collect

**Comment by SsnL** [comment]
It is probably that the new fc's weights are initialized with a relatively small variance that makes it unlikely to output large values. You can try by explicitly initializing the weight matrix to all 100.

Also there is no activation after the last layer.

**Comment by Asa-Nisi-Masa** [comment]
> It is probably that the new fc's weights are initialized with a relatively small variance that makes it unlikely to output large values. You can try by explicitly initializing the weight matrix to all 100.


Thanks, that seems to confirm that there is no activation imposed.
