### ISSUE TITLE
JIT does not autodiff Conv & BN

### ISSUE THREAD

**Issue by WoosukKwon** [pytorch/pytorch#32394]
Hi,

recently I found that JIT does not create `DifferentiableGraph` nodes corresponding to Conv and BN modules.

Both ops are not registered in symbolic_script.cpp and considered to be “non-differentiable” in the sense that their gradients are always computed by Autograd engine, which loses the opportunity of making bigger `DifferentiableGraph`s.

What’s the reason behind such non-optimal behavior of JIT?

cc @suo

**Comment by zdevito** [comment]
We do not have any optimization passes that will look at these operators and optimize them. There are such passes that we might do in the future, such as Conv-BN fusions, but we haven't added them yet. Without being able to optimize, creating DifferentiableGraphs nodes just creates overhead, so we do not include these ops yet.
