### ISSUE TITLE
PyTorch - ONNX Export Error with Opset 7 caused by Round

### ISSUE THREAD

**Issue by Wuqiman** [pytorch/pytorch#32391]
## 🐛 Bug
PyTorch model export to ONNX fails when using PyTorch 1.3.1 or nightly and ONNX 1.6.0. Failure is caused by all upsample operations:
input = (input / scale).round().clamp(-127, 127)

## Environment
 - PyTorch Version (e.g., 1.0):1.3
 - OS (e.g., Linux):Linux
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):conda
 - Python version:3.6.0
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

Hello, how to reset ONNX's op_set_version?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
Round is only supported with `opset_version >= 11`. The Round operator was added to the ONNX standard in op set 11, so it's unlikely we'll be able to support it in the exporter for older op sets:
<https://github.com/onnx/onnx/blob/main/docs/Changelog.md#round-11>
