### ISSUE TITLE
Unexpected keyword argument "align_corners" for "grid_sample"

### ISSUE THREAD

**Issue by edgarriba** [pytorch/pytorch#32392]
## 🐛 Bug

After upgrading to PyTorch 1.4.0 when I make explicit the `align_corners` parameter in `F.grid_sample`, `mypy` returns an error complaining about the input parameters.

## To Reproduce

`F.grid_sample(image_src, points_2d_src_norm, align_corners=True)` ->  error: Unexpected keyword argument "align_corners" for "grid_sample"

`F.grid_sample(image_src, points_2d_src_norm, 'bilinear', 'zeros', True)` ->  error: Too many arguments for "grid_sample"

## Expected behavior

I could hack this by adding `#type: ignore`, however, later JIT probably won't trace correctly the function.

cc @ezyang

**Comment by ezyang** [comment]
It looks like there's a mistake in the typing annotation. It should be a relatively simple fix; tag me on a PR if you fix it.

I would *hope* `# type: ignore` doesn't cause JIT to stop working.

**Comment by edgarriba** [comment]
Solved in here https://github.com/pytorch/pytorch/pull/32492
