### ISSUE TITLE
Log_Softmax error with a singleton Tensor

### ISSUE THREAD

**Issue by iffsid** [pytorch/pytorch#3240]
Applying `log_softmax` to a singleton Tensor returns an incorrect answer; `-inf` instead of 0.

Minimal breaking example:
``` python
import torch
from torch.nn.functional import log_softmax
from torch.autograd import Variable
s = log_softmax(Variable(torch.Tensor([0.7])))
```
This should return (as it does in the release `0.2.0_3`)
```
Variable containing:
 0
[torch.FloatTensor of size 1]
```
However, it actually returns
```
Variable containing:
-inf
[torch.FloatTensor of size 1]
```
I'm running pytorch installed from source, from master (off of commit dc6510f)

**Comment by zou3519** [comment]
Thanks for reporting this! I think I know what's causing it, will send out a fix soon.
