### ISSUE TITLE
how to install pytorch on AMD GPU

### ISSUE THREAD

**Issue by PIPIKAI-Sung** [pytorch/pytorch#32418]
I find that the pytorch offer one version of downloading which not requires CUDA. And  I follow the instruction.
I choose the pytorch 1.4.
My OS is Windows.
Pip is used to install.
My version of python is python 3.6
CUDA None
and I run the command pip3 install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
However, here comes two errors
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0+cpu
Why? Thanks a lot for help

**Comment by peterjc123** [comment]
Are you using 32-bit Python?

**Comment by peterjc123** [comment]
If you are using Python 64-bit, you should get `8` as the output of the command `python -c "import struct; print(struct.calcsize('P'))"`

**Comment by PIPIKAI-Sung** [comment]
@peterjc123 Yes, I am pretty sure that I am using 64-bit Python

**Comment by peterjc123** [comment]
What about `python -m pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html`?

**Comment by PIPIKAI-Sung** [comment]
@peterjc123 It works！ Thanks a lot. Could you please explain the reason that why pip works and pip3 failed?

**Comment by peterjc123** [comment]
It means that pip3 and python belong to two different Python environments. Uou can use the following scripts to check.
```
where pip3
where python
```

**Comment by damico** [comment]
I just made a python code that tests PyTorch support for AMD GPUs with ROCM: https://gist.github.com/damico/484f7b0a148a0c5f707054cf9c0a0533
