### ISSUE TITLE
showing symbolic representation

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#32417]
current scenario -
when I do 
```
import torch
torch.nn.Sigmoid()
```
then it gives output
```
Sigmoid()
```
expected scenario -
I do something like
```
import torch
torch.nn.Sigmoid(symbolic=True)
```
gives
![Screenshot (230)](https://user-images.githubusercontent.com/43755000/72700241-abaf2b00-3b8e-11ea-9acc-ac274f25d23b.png)
or
![Screenshot (232)](https://user-images.githubusercontent.com/43755000/72700665-df3e8500-3b8f-11ea-9a15-ebdfbbd6593e.png)

**Comment by yf225** [comment]
@soumith Would this be a useful feature to add?

**Comment by soumith** [comment]
no, i don't think this is useful. It sounds like documentation?
We should put that / already have the tex formulas in docstrings
