### ISSUE TITLE
Custom CUDNN_LIB_DIR not added to rpath

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/pytorch#3242]
Compiling pytorch master version 0.2.0+0989889 with a custom CUDNN_LIB_DIR and CUDNN_INCLUDE_DIR location, with cuda 8.0 and cudnn 7, it seems the compiled binaries do not include the path to CUDNN_LIB_DIR in their rpath, causing an error on import

> ldd _C.so|grep libcudnn
> 	libcudnn.so.7 => not found

> patchelf --print-rpath _C.so 
> [..]/miniconda2/envs/neural4/lib:/usr/local/cuda-8.0/lib64:$ORIGIN/lib

Might be an addition worth adding to the build system?

**Comment by apaszke** [comment]
Yes, please send a PR!
