### ISSUE TITLE
Running example use of torch.conj

### ISSUE THREAD

**Issue by sebastienwood** [pytorch/pytorch#32437]
## 🐛 Bug

When trying to use the torch.conj example of the documentation, this raise a RuntimeError : could not infer dtype of complex.

## To Reproduce

1. Launch a python shell
2. Run ```import torch; torch.conj(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))```

Example trace : 
```Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.conj
<built-in method conj of type object at 0x7f0bd05621e0>
>>> torch.conj(torch.tensor([-1 + 1j, -2 + 2j, 3 - 3j]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Could not infer dtype of complex 
```

## Expected behavior

The documentation line should work as is, or the error message should be a little more specific.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (Homebrew gcc 5.5.0_4) 5.5.0
CMake version: version 3.13.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                intel_243    intel
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
[conda] torchviz                  0.0.1                    pypi_0    pypi

cc @ezyang

**Comment by artemisart** [comment]
Precision: the problem comes from `tensor()` and not `conj()`, on pytorch 1.4 `torch.tensor([1j])` gives `RuntimeError: Could not infer dtype of complex`.
https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype According to these docs complex types are not yet supported.

**Comment by ezyang** [comment]
cc @dylanbespalko but at the moment proper complex support lives out of tree https://gitlab.com/pytorch-complex/pytorch-cpu-strided-complex https://gitlab.com/pytorch-complex/pytorch-cuda-strided-complex

**Comment by dylanbespalko** [comment]
As stated above, 

Complex number support is found here:
[cpu_strided_complex](https://gitlab.com/pytorch-complex/pytorch-cpu-strided-complex)
[cuda_strided_complex](https://gitlab.com/pytorch-complex/pytorch-cuda-strided-complex)

I plan to internalize these modules soon based on the progress in #24507. 

I'm a bit bogged down. I will try to close this bug next week.

**Comment by ezyang** [comment]
By the way, @dylanbespalko, there's a decent chance that this half we will start looking to move your excellent work in tree to PyTorch proper :D Let me know if there's anything on your own end we should know about.

cc @anjali411

**Comment by mruberry** [comment]
This should work in the latest PyTorch. @sebastienwood would you try on nightly or wait for 1.7. If this still reproduces please reopen this issue.
