### ISSUE TITLE
Precompute dispatch tables to simplify dispatch hot path

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#32454]
The basic concept is, instead of having separate entries for "operator function pointer, backend fallback, catch all kernel", we combine all of these entries into a single "this is the function pointer for dispatch key and operator", and have a more complex registration process that "fills in" the entirety of all operators for a backend if you, e.g., register a backend fallback.

**Comment by smessmer** [comment]
note that catch all kernel can be removed thanks to CompoundOpId, so it's currently only operator function pointer and backend fallback.
