### ISSUE TITLE
softmax (and log_softmax) fail for 3D tensors in CUDA

### ISSUE THREAD

**Issue by jwvdm** [pytorch/pytorch#3246]
First off, thank you for your work on this project. 

There is an issue with the new `log_softmax` and `softmax` implementations that support dim arguments (as of a806d1a). 

The following code works:
```python
v = Variable(torch.rand(2,3,4))
torch.nn.functional.softmax(v, v.dim()-1)
```

However, running the same code in CUDA mode 
```python
v = Variable(torch.rand(2,3,4).cuda())
torch.nn.functional.softmax(v, v.dim()-1)
```
throws the error
> RuntimeError: invalid argument 4: dim has to be 0 for 3D input at /home/janwillem/Cloud/git/probtorch/probtorch/build/pytorch/torch/lib/THCUNN/generic/SoftMax.cu:42

Edit: I just realized that #3245 may already address this issue. If so, feel free to close.

**Comment by apaszke** [comment]
Yup, I just submitted a PR that fixes it. Thanks for the report.
