### ISSUE TITLE
softmax (and log_softmax) fail for dim < 0

### ISSUE THREAD

**Issue by jwvdm** [pytorch/pytorch#3247]
It would be nice if softmax and log_softmax supported negative dimension indexing. As of a806d1a, the following fails
```python
v = torch.autograd.Variable(torch.rand(2,3,4))
torch.nn.functional.log_softmax(v, -1)
```
with Error message
> RuntimeError: invalid argument 4: dim out of range (got -1, but input has 3 dims) at /home/janwillem/Cloud/git/probtorch/probtorch/build/pytorch/torch/lib/THNN/generic/LogSoftMax.c:20

**Comment by colesbury** [comment]
We need to change `nn.yaml` to add:

```
  wrap_dim:
    dim: input
```

to the softmax and log_softmax declarations

**Comment by zou3519** [comment]
Was fixed in https://github.com/pytorch/pytorch/pull/3689
