### ISSUE TITLE
How to specify pytroch as a package requirement on windows ?

### ISSUE THREAD

**Issue by George3d6** [pytorch/pytorch#32485]
## ❓ Questions and Help

I have a python package which depends on pytorch and which I’d like windows users to be able to install via pip (the specific package is: https://github.com/mindsdb/lightwood, but I don’t think this is very relevant to my question).

What are the best practices for going about this ?

Are there some project I could use as examples ?

It seems like the pypi hosted version of torch & torchvision aren’t windows compatible and the “getting started” section suggests installing from the custom pytorch repository, but beyond that I’m not sure what the ideal solution would be to incorporate this as part of a setup script.

**Comment by peterjc123** [comment]
If you know the version specifier beforehand, then just write sth like
```
torch===1.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
```
Otherwise, if you want to install the latest pytorch for a specified spec.
```
torch -f https://download.pytorch.org/whl/cu92/torch_stable.html
```
