### ISSUE TITLE
 TypeError: Type torch.sparse.LongTensor doesn't implement stateless method cat

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [pytorch/pytorch#3248]
```
a = torch.sparse.LongTensor(torch.Size([2,3]))
b = torch.sparse.LongTensor(torch.Size([2,3]))
torch.sparse.torch.cat((a, b))
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-54-10a82d668fd1> in <module>()
----> 1 torch.sparse.torch.cat(a, b)

TypeError: Type torch.sparse.LongTensor doesn't implement stateless method cat
```
Is it correct behaviour?

**Comment by dd210** [comment]
Same error:
`import torch
i = torch.LongTensor([[0, 1], [2, 0]])
v = torch.FloatTensor([3, 4])
sp = torch.sparse.FloatTensor(i, v, torch.Size([2,3]))
torch.cat((sp, sp))`
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-da5b036cb5b7> in <module>()
      3 v = torch.FloatTensor([3, 4])
      4 sp = torch.sparse.FloatTensor(i, v, torch.Size([2,3]))
----> 5 torch.cat((sp, sp))

TypeError: Type torch.sparse.FloatTensor doesn't implement stateless method cat`

**Comment by deepmipt-VladZhukov** [comment]
temporal solution:
```
def sparse_cat(a, b, dim=0):
    a_size = a.size()
    b_index = copy(b._indices())
    b_index[dim, :] += a_size[dim]
    all_index = torch.cat((a._indices(), b_index), 1)
    all_values = torch.cat((a._values(), b._values()))
    all_size = list(copy(a_size))

    all_size[dim] += b.size()[dim]
    return torch.sparse.LongTensor(all_index, all_values, torch.Size(all_size))
sparse_cat(a, b, 0)
``

**Comment by ezyang** [comment]
CC @SsnL, if this is something you might be interested at looking at :)

**Comment by SsnL** [comment]
I believe `cat` is not implemented for sparse tensors at the moment. But I'll take a look to add this once I'm free.

**Comment by deepmipt-VladZhukov** [comment]
You can add "slice" method for sparse matrices to this list too ;)

**Comment by SsnL** [comment]
@deepmipt-VladZhukov do you mean `narrow`? :)

**Comment by weiyangfb** [comment]
closing this since both of `cat` and `narrow_copy` are already implemented
