### ISSUE TITLE
Typing Error in torch.nn.parameter

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#32481]
## 🐛 Bug

Typing interface file([`nn/parameter.pyi`](https://github.com/pytorch/pytorch/blob/master/torch/nn/parameter.pyi) file) does not match with source code ([`nn/parameter.py`](https://github.com/pytorch/pytorch/blob/master/torch/nn/parameter.py) file).

## Expected behavior

`nn/parameter.pyi` should be

```python
from .. import Tensor
import builtins

class Parameter(Tensor):
    def __init__(self, data: Tensor = ..., requires_grad: builtins.bool = ...): ...
    ...
```

because arguments in `nn.Parameter`'s constructor has default values. (`def __new__(cls, data=None, requires_grad=True):`)

## References

* [PEP 484 Type Hints - Arbitrary argument lists and default argument values](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values)

**Comment by pbelevich** [comment]
@jeongukjae thank you for reporting this! Would you like to create a pull request to fix this?

**Comment by jeongukjae** [comment]
@pbelevich Okay. I will fix this soon.

And one more thing.. I think this issue should be labeled with `module: typing`.

**Comment by jeongukjae** [comment]
> @jeongukjae thank you for reporting this! Would you like to create a pull request to fix this?

I created one.
