### ISSUE TITLE
AttributeError: module 'torch.nn.utils' has no attribute 'prune'

### ISSUE THREAD

**Issue by Oktai15** [pytorch/pytorch#32483]
## 🐛 Bug

AttributeError: module 'torch.nn.utils' has no attribute 'prune'

## To Reproduce

```
pip install torch==1.4.0 torchvision
python -c "import torch; print(torch.__version__), print(torch.nn.utils.prune.random_structured)"
```

```
1.4.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch.nn.utils' has no attribute 'prune'
```

## Expected behavior

prune should be in torch 1.4.0

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: Tesla T4

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0

**Comment by pbelevich** [comment]
you need to `import torch.nn.utils.prune` no only `import torch`
