### ISSUE TITLE
SobolEngine init crashes if default tensor type is cuda

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#32494]
## 🐛 Bug

When setting the default tensor type to cuda using `set_default_tensor_type`, initializing a `SobolEngine` results in a crash.

## To Reproduce

```
import torch
from torch.quasirandom import SobolEngine

torch.set_default_tensor_type(torch.cuda.FloatTensor)
se = SobolEngine(3)  # crashes w/o any error message here
```

## Expected behavior

Should not crash.

## Environment

Linux, pytorch master (fb infra)

**Comment by Balandat** [comment]
This seems to be some basic issue with cuda tensors getting intermixed with cpu ones in the `SobolEngine` constructor, I'm working on a fix.

**Comment by ParticularlyPythonicBS** [comment]
Is there a temporary fix for this?
or a successful build that includes this?

**Comment by Balandat** [comment]
This should have made it into the nightlies by now.
