### ISSUE TITLE
Download/install extremely slow (San Diego)

### ISSUE THREAD

**Issue by salvatoreloguercio** [pytorch/pytorch#3250]
conda install pytorch torchvision cuda80 -c soumith

cuda80 and libgcc installed fast, but pytorch goes extremely slow - it starts like 60kB/s then slows down to an unbearable ~10kB/s. I restarted it different times and got the same behavior. Any workaround for this?

Thanks,
Sal

**Comment by zou3519** [comment]
I don't know much about this, but if you're in a rush you can install pytorch from source.

**Comment by ezyang** [comment]
PyTorch conda builds are distributed by Anaconda Cloud, so I'm afraid there's not much we can do if there's a connectivity issue.
