### ISSUE TITLE
Java bindings for Windows

### ISSUE THREAD

**Issue by dreiss** [pytorch/pytorch#32516]
## 🚀 Feature
It would be cool if the Java bindings worked on Windows.  They don't right now.  If you are interested in this feature, please comment on this issue with information on how/why you want to use it.  We will use this information to prioritize the work.

cc @peterjc123

**Comment by wajihullahbaig** [comment]
Why not on windows? At my office we have a variety different Windows and linux machines.
They wont allow me to install Linux, so I have to work with windows and since no Java support, I am left with limit computing resources. Hope you will officially support java full fledged.

**Comment by sergiosanchezstb** [comment]
This problem is also affecting recently released TorchServe when trying to serve a model on Windows. I hope it gets fixed soon. 

torchserve --start --model-store model_store --models model_store/densenet161.mar

Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer

**Comment by erip** [comment]
This is very important for me because I'm developing a Java plugin for a common fat client application to load PyTorch models. Can you share the technical limitations/blockers to supporting JNI builds for Windows currently?

**Comment by dreiss** [comment]
Hey, sorry I missed these comments.  I think there are two main issues.

- fbjni doesn't currently build with Visual Studio.  If someone can debug this, that would be great.  fbjni uses a lot of modern C++ template magic.  We can't compromise code cleanliness too much in order to support VS, and we probably can't compromise binary size more than a *tiny* bit.  (Most of the template magic is to minimize Android app size.)
- We could possibly build PyTorch with VS and the PyTorch JNI binding (plus fbjni) with clang.  However, when building fbjni on Windows with clang, a few of the tests don't pass.  I suspect this is due to a legitimate bug in fbjni that simply doesn't reproduce on Mac and Linux, but I have not been able to track it down yet.

**Comment by macster110** [comment]
I am a developer for a predominately Java program for detecting and classifying whale and dolphin sounds which is used widely in industry academia but almost always on Windows machines. It's just the default operating system for most people, including researchers, academics and industry. The java library is great- allowing us to integrate deep learning directly into the the program, however, limiting it to Linux and Mac (which does not benefit from CUDA) means that almost no one will use these new capabilities - the adoption of a new operating system is too much of a time and technical barrier for many users. Therefore, for us, Windows support is critical to allow the wider adoption of deep learning for acoustic detection and classification and, consequently, the inevitable gains in performance over older methods, will feed directly into more efficient monitoring of many whale and dolphin species. So, yes please, Windows support would be fantastic!

**Comment by JonathanSum** [comment]
So...it doesn't support window10 ?

**Comment by JonathanSum** [comment]
At 2:48 of Pytorch's official video, it said the java bidding is PR merged.
https://www.youtube.com/watch?v=0mIXKxbY2zc

**Comment by peterjc123** [comment]
cc @erip

**Comment by erip** [comment]
@JonathanSum Yes, ideally if you can script it it should run on Windows. There are a few lingering PRs to fix the build to bundle the DLLs in libtorch, so keep an eye on changelogs for coming releases.

**Comment by erip** [comment]
This now officially works out of the box on Windows. See discussion [here](https://github.com/dreiss/java-demo/issues/1#issuecomment-737217879)
