### ISSUE TITLE
cuDNN not correctly linked in master.5795b17

### ISSUE THREAD

**Issue by PiotrSokol** [pytorch/pytorch#3251]
Compilation goes without a problem but importing torch gives
`ImportError: /lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudnnSetConvolutionGroupCount
`
Compiling from source v0.2.0 works fine.

Set up is 
>Python 3.6.2 :: Anaconda custom (64-bit)
>Cuda compilation tools, release 8.0, V8.0.61
> #define CUDNN_MAJOR      7
>gcc (GCC) 4.8.5 
>centos-release-scl-rh-2-2.el7.centos.noarch

**Comment by apaszke** [comment]
It's likely a configuration issue of your system. You built with cuDNN7, but cuDNN6 is loaded at runtime. Can you please run `LD_DEBUG=libs python -c 'import torch'` and paste the output in a gist?

**Comment by PiotrSokol** [comment]
OK, here's the [gist](https://gist.github.com/PiotrSokol/5fb65bfa73097c9b3af9aaadc6ade815).

**Comment by apaszke** [comment]
That's weird. It doesn't even seem to be linked. Can you post the output of `ldd /lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so`? Did you build from source? Can you clean the repo (`git clean -xfd` **ASSUMING YOU DID NO CHANGES YOURSELF - THIS MIGHT DESTROY THEM**), build form scratch, and post the build log in a gist as well?

**Comment by PiotrSokol** [comment]
Hey Adam, I made a mistake. This is the correct [gist](https://gist.github.com/PiotrSokol/8658376ddf5e114d9116197fd30fb41d). And [here's](https://gist.github.com/PiotrSokol/66ef8568124f714e9ce90f756338b275) the ldd just in case.

**Comment by apaszke** [comment]
Ok. cuDNN isn't linked. How did you install PyTorch?

**Comment by PiotrSokol** [comment]
Compiled from source, following the instructions.

**Comment by apaszke** [comment]
Please rebuild and post the build lot

**Comment by PiotrSokol** [comment]
Done, here's the [log](https://gist.github.com/PiotrSokol/ac0ed1ded78b1d4fc8e6833eb5bf1b78).

**Comment by apaszke** [comment]
The build log looks correct. I think the problem is that you have multiple Python environments with different PyTorch packages. In your run time log, torch is loaded from `/lib/python3.6/site-packages/`, but in your build log it's installed in `/home/piotr/anaconda3/lib/python3.6/site-packages/`. Cleaning up the global install should fix it for you.

**Comment by PiotrSokol** [comment]
Ok, so I made sure pytorch wasn't installed in the global python. Checked & removed `/lib/python3.6/site-packages/` from the Anaconda `sys.path`. Now the `sys.path` only shows 
`['', '/home/piotr/anaconda3/lib/python36.zip', '/home/piotr/anaconda3/lib/python3.6', '/home/piotr/anaconda3/lib/python3.6/lib-dynload', '/home/piotr/anaconda3/lib/python3.6/site-packages']`

Still, get
`ImportError: /home/piotr/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudnnSetConvolutionGroupCount`

Again, runtime [gist](https://gist.github.com/PiotrSokol/3f77252bef89e48a0bf81638604175cd) and the [dependencies](https://gist.github.com/PiotrSokol/8f26cdf99dbdb58b53ce837b09d959f6) of the `.so` from the error

**Comment by apaszke** [comment]
Eh, I'm running out of tricks. Maybe there's sth wrong with the compiler? you can see that there's a `-lcudnn` flag when building `_C.so`.  Try prepending `LDFLAGS="-Wl,--no-as-needed"` before the build command

**Comment by PiotrSokol** [comment]
The sysadmin installed both cuDNN 6.0 and 7.0 and that's causing the problem. I followed #3255 but still found it necessary to insert at the beginning with `library_dirs.insert(0,CUDNN_LIB_DIR)` . Now the import doesn't throw any errors.

**Comment by apaszke** [comment]
hmm yeah, it should also go in the front of `library_dirs`. Can you please submit a PR with the fix?

**Comment by PiotrSokol** [comment]
Will do

**Comment by soumith** [comment]
@ezyang i believe this patch in the second last comment has to be adapted for your refactor.
