### ISSUE TITLE
record_function decorator in autograd profiler does not work with RPC

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#32517]
## 🐛 Bug

Nested `RecordFunction`s during profiling do not work with RPC calls, due to mismanagement of some internal variables in `record_function.cpp` caused by handling `RecordFunction` objects completing in different hreads.

## To Reproduce

```
with torch.autograd.profiler.profiler() as prof:
    with torch.autograd.profiler.record_function("foo"):
        rpc.rpc_async(...)
```

will result in an error:
```
> I0122 16:32:15.967217 594065 record_function.cpp:214] Exception in RecordFunction::end(): (thread_local_func_ == thi
s) || (thread_local_func_ == nullptr && threadId_ != 0) INTERNAL ASSERT FAILED at caffe2/torch/csrc/autograd/record_fu
nction.cpp:235, please report a bug to PyTorch. baze: must be top of stack. If you are calling RecordFunction::end in
aseparate thread, call RecordFunction::setThreadId() in the creatingthread. (end at caffe2/torch/csrc/autograd/record_
function.cpp:235)
```

This is because the handling of the thread local variables `thread_local_func` and `parent_` are not managed properly when `RecordFunction::end` is called from a separate thread.

Expected behavior:
The nested scopes should be profiled correctly as non-RPC code would be.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by ezyang** [comment]
> when RecordFunction::end is called from a separate thread.

Why is RecordFunction::end being called from a separate thread?

**Comment by rohan-varma** [comment]
@ezyang This happens because futures that correspond to RPC calls complete in a different thread. We want to stop profiling for an RPC when the future corresponding to it as marked as completed, hence the need to call it from a different thread. The PR description in https://github.com/pytorch/pytorch/pull/31381 describes the reasoning behind this more thoroughly.

**Comment by rohan-varma** [comment]
This is now fixed, see the relevant test at https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/distributed/rpc/rpc_test.py#L638
