### ISSUE TITLE
Instantiating `torch.distributions.Categorical` with all-zero long-dtype probabilities crashes Python

### ISSUE THREAD

**Issue by iamlucaswolf** [pytorch/pytorch#32532]
## 🐛 Bug

As stated in the title, instantiating a categorical distribution (`torch.distributions.Categorical`) with an all-zero long-dtype `probs` argument (e.g. `Categorical(probs=torch.tensor([0,0,0]))`) will elicit a core dump.

I am aware that this is a somewhat nonsensical edge case, however it differs from the failure behavior of other nonsensical edge cases, in particular:

```python
## Instantiating a categorical with all-zero float-dtype probabilites

# still works
c = Categorical(probs=torch.tensor([0,0,0], dtype=torch.float))

c.sample()
>>> RuntimeError: invalid multinomial distribution (encountering probability entry < 0)
```

and also

```python
## Instantiating a categorical with non-zero long-dtype probabilities

# works as well
c = Categorical(torch.tensor([1,2,3]))

c.sample()
>>> RuntimeError: multinomial only supports floating-point dtypes for input, got: Long
```

## To Reproduce

```python
import torch
from torch.distributions import Categorical

c = Categorical(probs=torch.tensor([0,0,0])
```

## Expected behavior

As outlined above, a `RuntimeError` is usually used to handle invalid input of this kind. 

## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 440.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.3.1
[pip3] torchstat==0.0.7
[conda] Could not collect

## Additional context

N/A

cc @ezyang @gchanan @zou3519 @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by alicanb** [comment]
It's the divide-by-0 behavior. `torch.zeros(1,dtype=torch.float) / 0` gives `nan`, `torch.zeros(1,dtype=torch.long) / 0` crashes.

**Comment by ezyang** [comment]
@albanD why did you remove triage review from this issue?

**Comment by albanD** [comment]
It was a mistake !

**Comment by v0dro** [comment]
Removing my assign since this is still under triage review.

**Comment by Baranowski** [comment]
@v0dro, do you still want to work on this? Otherwise, I will take it.

**Comment by ezyang** [comment]
hurray
