### ISSUE TITLE
RandomSampler with replacement=True should generate samples on-the-fly

### ISSUE THREAD

**Issue by xdever** [pytorch/pytorch#32530]
## 🚀 Feature

Generate samples on the fly in the RandomSampler if replacement=True.

## Motivation

My primary use of random sampler with replacement=True would be to have an infinite sampler of random elements that do not require a restart of the loader processes. To do this, I would like to specify a big number of samples with replacement=True.

For 2 cases this is especially useful: for super big datasets where the shuffling takes forever (for example Deepmind's math dataset) and for small datasets (like MNIST), where restarting the processes can use time comparable to the actual training time. 

However, a random sampler with replacement=True generates a list of int64 samples in advance:

```python
return iter(torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64).tolist())
```

This makes it use a lot of memory if num_samples is big.

## Pitch

Use a generator function instead, which saves the memory overhead of the list. The performance penalty for generating random integers one-by-one should not be comparable for the data loading time, even for tiny datasets.

## Alternatives

Provide a different sampler class that samples from the dataset on the fly.

cc @SsnL

**Comment by ydaiming** [comment]
Hi, there. If you haven't, I can create a PR and work on it.
