### ISSUE TITLE
Channel-wise quantization for activations for conv/linear operators

### ISSUE THREAD

**Issue by ggeor84** [pytorch/pytorch#32542]
## 🚀 Feature
Currently channel-wise quantization for conv and linear operators is only supported for weights. Extending support of conv/linear operators for channel-wise quantization for activations would be fantastic.

## Motivation

Accuracy of a network can greatly benefit if activations are also quantized channel-wise.
## Pitch

Conv/linear operators should support channel-wise quantization of both weights and activations

## Alternatives

None

## Additional context

None

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
I think we have discussed this before, the argument against channel wise activation is that it makes kernel much more slower which defeats the purpose of quantization(which is to make the model run faster with little or no loss of accuracy).

**Comment by ggeor84** [comment]
Got it. Well, I don't have experience to argue against this, so I'll take your word for it :)
