### ISSUE TITLE
PyTorch 1.4 ONNX Producer Version Mismatch

### ISSUE THREAD

**Issue by rmccorm4** [pytorch/pytorch#32561]
## 🐛 Bug

I'm exporting a PyTorch model to ONNX with `torch==1.4.0` and `onnx==1.6.0`, but the metadata in the ONNX model reports "Producer Version: 1.3".

## To Reproduce

1. Install torch==1.4 and produce ONNX model
```
# Install dependencies
pip install torch==1.4.0 onnx==1.6.0 torchvision==0.5.0

# Download sample onnx model code
wget https://gist.githubusercontent.com/rmccorm4/b72abac18aed6be4c1725db18eba4930/raw/fbdb009152ef54abe7d8b23a9fd57a0f250e03e4/alexnet_onnx.py

# Run sample code
python alexnet_onnx.py 
```

2. Check PyTorch version is correct
```python
import torch
print(torch.__version__)
# '1.4.0'
```

3. Check ONNX metadata
```python
# check.py
import sys
import onnx
onnx_model = onnx.load(sys.argv[1])
print("Producer Name:", onnx_model.producer_name)
print("Producer Version:", onnx_model.producer_version)
print("Opset", onnx_model.opset_import[0])
```

ONNX model reporting PyTorch 1.3:
```bash
root@1793b42aa4bf# python check.py alexnet_fixed.onnx 
Producer Name: pytorch
Producer Version: 1.3
Opset version: 11

root@1793b42aa4bf# python check.py alexnet_dynamic.onnx 
Producer Name: pytorch
Producer Version: 1.3
Opset version: 11
```

## Expected behavior

`onnx_model.producer_version == "1.4"`

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0

cc @ezyang @gchanan @zou3519 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by mattip** [comment]
On master, the file `torch/csrc/onnx/onnx.h` has a `static const char* PRODUCER_VERSION`. No such constant exists on the v1.4.0 branch. On [PyPI](https://pypi.org/project/pytorch/#files) the last available version is 1.0.2. The issue description specifically states `pip install`. @rmccorm4 could you clarify where you got that version?

**Comment by rmccorm4** [comment]
Hi @mattip , you linked the pip package `pytorch`, when it should actually just be `torch`. See here: https://pypi.org/project/torch/

**Comment by mattip** [comment]
Thanks, indeed the correct name for the package is `torch`. @soumith do you have any insights?

**Comment by rgommers** [comment]
> On master, the file `torch/csrc/onnx/onnx.h` has a `static const char* PRODUCER_VERSION`. No such constant exists on the v1.4.0 branch

Isn't this a matter of checking out the 1.4.0 branch and following the trail back from `onnx_model.producer_version`? There's no `PRODUCER_VERSION` in that branch, so where does it come from?

Also, is it fixed in master? `PRODUCER_VERSION` seems to be a hardcoded string, which may break again.

**Comment by rgommers** [comment]
@mattip maybe the part you were missing is how releases get built? See https://github.com/pytorch/builder for build scripts for wheels, conda packages, etc. It has `PYTORCH_BUILD_VERSION` which should set the version.

**Comment by mattip** [comment]
Yes that is helpful, thanks

**Comment by mattip** [comment]
I think this can be closed. If needed for the 1.4 branch #36795 can be merged, and #36797 was merged to master.

**Comment by rmccorm4** [comment]
@mattip this issue will automatically be closed by your mentioned PR when it's merged, as long as the right words were used in the description.

**Comment by rgommers** [comment]
@mattip I suggest to address https://github.com/pytorch/pytorch/pull/36797#issuecomment-620048920 in a follow-up PR and close this issue with that PR.
