### ISSUE TITLE
RuntimeError: "roll_cuda" not implemented for 'Bool'

### ISSUE THREAD

**Issue by Ajk4** [pytorch/pytorch#32583]
## 🐛 Bug

torch.roll not working for bool tensor with cuda.

## To Reproduce

```
import torch
t = torch.zeros(10, dtype=torch.bool).cuda()
t.roll(1)
```
yields `RuntimeError: "roll_cuda" not implemented for 'Bool'`

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1
OS: Microsoft Windows 10 Pro
GCC version: (tdm64-1) 5.1.0
CMake version: Could not collect
Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 441.20
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
PyDev console: starting.
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32

## Additional context

It might be a regression since it was already reported in https://github.com/pytorch/pytorch/issues/31079

**Comment by ngimel** [comment]
This is fixed on master, but not in 1.4.0 version.
