### ISSUE TITLE
Massive memory leak on CPU with varying batch sizes

### ISSUE THREAD

**Issue by hollance** [pytorch/pytorch#32596]
## 🐛 Bug

Doing a simple inference loop with a different batch size in each iteration will quickly eat up all your memory. Only happens when running on the CPU, not on the GPU.

## To Reproduce

Run the following script and keep and eye on `htop`:

```
import torch
import random

# This problem only occurs on the CPU, not the GPU.
device = torch.device("cpu")

# Uncomment the following line and the problem goes away.
# device = torch.device("cuda:0")

from torchvision.models.resnet import resnext50_32x4d
model = resnext50_32x4d(pretrained=False).to(device)
_ = model.eval()

def predict():
    # Using this line, memory usage blows up (but only on the CPU!)
    x = torch.zeros((random.randint(10, 30), 3, 224, 224)).float()

    # Using the following line, memory usage is constant.
    #x = torch.zeros((30, 3, 224, 224)).float()

    print("batch size is:", x.shape[0])

    with torch.no_grad():
        y_pred = model(x)
        return y_pred.mean().item()

predictions = []
for i in range(100):
    y_pred = predict()
    predictions.append(y_pred)
```

## Expected behavior

The memory used should be stable. But it quickly grows until you run out of free RAM.

This only happens when:

- `device` is `"cpu"`
- the batch size of `x` changes in each iteration

When the size of `x` is the same in every iteration, the problem does not occur.

When using the GPU, this doesn't happen (even if the batch size changes all the time).

## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.20190318-gb06f8

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.4
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchvision               0.4.1                    pypi_0    pypi
```

---

NOTE: I also tested this with PyTorch 1.4.0 and it gave the same results.

## Additional context

n/a

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by ngimel** [comment]
Can you please try with the latest pytorch version (1.4.0)?

**Comment by SsnL** [comment]
same as https://github.com/pytorch/pytorch/issues/32037, may be make it a high pri?

**Comment by ngimel** [comment]
Ok, I'll close this in favor of #27971, and bump it for triage review.
