### ISSUE TITLE
torch.max(value, dim=None) throws an error

### ISSUE THREAD

**Issue by jwvdm** [pytorch/pytorch#3261]
This may be expected/unavoidable behavior, but it turns out one cannot explicitly pass a `dim=None` argument to `torch.max`:
```python
r = torch.rand(2, 3)
torch.max(r) # this works
torch.max(r, dim=None) 
```
this returns the error
> TypeError: torch.max received an invalid combination of arguments - got (torch.FloatTensor, dim=NoneType), but expected one of:
> * (torch.FloatTensor source)
> * (torch.FloatTensor source, torch.FloatTensor other)
>      didn't match because some of the keywords were incorrect: dim
> * (torch.FloatTensor source, int dim)
> * (torch.FloatTensor source, int dim, bool keepdim)

This becomes an issue when writing functions that themselves accept a `dim` argument, e.g.
```python
def log_sum_exp(value, dim=None, keepdim=False):
    """Numerically stable implementation of the operation

    value.exp().sum(dim, keepdim).log()
    """
    # TODO: torch.max(value, dim=None) threw an error at time of writing
    if dim is not None:
        m, _ = torch.max(value, dim=dim, keepdim=True)
        value0 = value - m
        if keepdim is False:
            m = m.squeeze(dim)
        return m + torch.log(torch.sum(torch.exp(value0),
                                       dim=dim, keepdim=keepdim))
    else:
        m = torch.max(value)
        sum_exp = torch.sum(torch.exp(value - m))
        if isinstance(sum_exp, Number):
            return m + math.log(sum_exp)
        else:
            return m + torch.log(sum_exp)
```

**Comment by gchanan** [comment]
it's expected -- they are really two different functions that share a name;  for example, `keepdim` doesn't make sense when dim is None, and in the tensor API they actually return different types (python number vs tensor).  We are doing some work to unify the return types now; I guess if we uniformly supported multiple dimensions of reduction across all reduction functions and renamed `keepdim` to `keepdims` we could make it one function for which all combination of arguments make sense (where `dim=None` means all dimensions).  But I haven't seen anyone explicitly propose that yet (I could have missed it).

**Comment by jwvdm** [comment]
Right, my mistake. 

Re-reading the docs, I see that `dim` is in fact not a keyword argument, but an optional argument. I wrongly assumed the syntax was analogous to that in Numpy, i.e. `numpy.max(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)`.

Closing, with thanks.

**Comment by narfanar** [comment]
At least in Python this flexibility would be welcome. Would the additional dispatch point be that much of a performance issue?
