### ISSUE TITLE
PyTorch Build from Source fails from Android Ubuntu

### ISSUE THREAD

**Issue by snyguy** [pytorch/pytorch#32613]
## 🐛 Bug

Building from source in headless ubuntu 19.04 in android termux:

> $ cd ~/ubuntu && ./start-ubuntu.sh
> 
> % su - username
> $ USER=username
> $ cd /home/${USER} && cd pytorch
> $ NO_CUDA=1
> $ python3 setup.py install --user

> 
[ 41%] Built target c10_TypeList_test                make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):                     File "setup.py", line 737, in <module>
    build_deps()                                       File "setup.py", line 316, in build_deps               cmake=cmake)                                       File "/home/username/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2                             cmake.build(my_env)                                File "/home/username/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)                       File "/home/username/pytorch/tools/setup_helpers/cmake.py", line 141, in run                                    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)           subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.

My cmake version

$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

??? Not sure what dependency is required

**Comment by ngimel** [comment]
Please post a full log with your error.

**Comment by ljk53** [comment]
Sounds like you are trying to build PyTorch on Android device with Termux + Ubuntu root image? - it is not something we currently support.
You can cross-compile LibTorch for Android/iOS from source on desktop with Android NDK/XCode, or you can use prebuilt binaries we released. Please find more details at: https://pytorch.org/mobile/home/
