### ISSUE TITLE
No __rsub__ methods type stub on torch.Tensor

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#32618]
## 🐛 Bug

```python
import torch

random_tensor = torch.rand((10, 20))
1.0 - random_tensor
```

Above code raises type error.

* mypy result:

  ```shell
  $ mypy test.py
  test.py:4: error: Unsupported operand types for - ("float" and "Tensor")
  Found 1 error in 1 file (checked 1 source file)
  ```

* pyright result:

  ```shell
  $ pyright test.py
  Searching for source files
  Found 1 source file
  /some/path/test.py
    4:1 - error: Operator '-' not supported for types 'Literal[1]' and 'Tensor'
  1 error, 0 warnings 
  Completed in 1.696sec
  ```

## Expected behavior

```python
import torch

random_tensor = torch.rand((10, 20))
1.0 - random_tensor
```

Above code should not raise any errors.

`torch.Tensor` needs below type hinting.

```python
    def __rsub__(self, other: Any) -> Tensor: ...
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip

## Additional context

I think this line([tools/pyi/gen_pyi.py#L177](https://github.com/pytorch/pytorch/blob/6ad9e5c70d1f496b9eaca191ec18e26c106c6436/tools/pyi/gen_pyi.py#L177)) is the cause.

**Comment by ngimel** [comment]
Thank you for reporting this. Would you mind submitting PR with a fix?

**Comment by jeongukjae** [comment]
> Thank you for reporting this. Would you mind submitting PR with a fix?

Good. I will create a PR for this issue!

**Comment by jeongukjae** [comment]
I think this issue is fixed by https://github.com/pytorch/pytorch/pull/30576, so I will close this issue.
