### ISSUE TITLE
Should I expect a performance difference between jit and native c++ models?

### ISSUE THREAD

**Issue by bmanga** [pytorch/pytorch#32628]
## ❓ Questions and Help

Hi, I was wondering if I should expect any performance difference between:
* creating and training a model in python, script it with `jit.script` and run it in c++
* creating, training and running a model directly using the C++ API.

Thanks!

cc @suo

**Comment by suo** [comment]
Yes, you should expect a performance difference. The C++ API has the same execution model as PyTorch eager, and re-uses the same infrastructure. It will execute your model code op by op, as you wrote it.

The JIT has a domain-specific optimizing runtime, so in general you should expect your code to be faster than the C++ frontend. However, we're still early on in delivering perf wins using compilation techniques (it's a big focus for us for 2020), so I'd encourage you to benchmark different approaches for your workload.

Going to close this issue to help with our triage process, but feel free to comment if you have followup questions!
