### ISSUE TITLE
[Feature Request] Relax .view and .reshape argument restrictions so that ints and tuples can be interspersed

### ISSUE THREAD

**Issue by SamPruden** [pytorch/pytorch#32627]
## 🚀 Feature
Relax `.view` and `.reshape` argument restrictions so that `int`s and iterables can be interspersed and automatically flattened such that `.view(1, 2, (3, 4, 5), 6)` is equivalent to `.view(1, 2, 3, 4, 5, 6)`. Also allow the iterables to not only be `tuple`s and `list`s, but also 1D numpy arrays and 1D CPU tensors.

## Motivation
I quite often find myself writing code like this ugly mess. `tile` is a tuple of ints.
```Python3
exploded_kernel = kernel.view((-1, ) + tile + (kernel.shape[1], ) + (2, 2, 2))
```

With this change, this would be much neater.
```Python3
exploded_kernel = kernel.view(-1, tile, kernel.shape[1], 2, 2, 2)
```

Sometimes there's another way to approach this by combining other reshaping ops, but that's often fiddly in its own way. 

Another example of a fiddly reshape I have in my current project. Actually this is a simplified version.
```Python3
x = x.view(
  -1,
  x.shape[2] // (kernel_size[0] - 1),
  x.shape[3] // (kernel_size[1] - 1),
  x.shape[4] // (kernel_size[2] - 1)
)
```

This could currently be done like this, but it's a mess. `ten` is `torch.tensor` and `kernel_size` is already a tensor.
```Python3
x = x.view((-1, ) + tuple(ten(x.shape[2 : 5]) // (kernel_size - 1)))
```

If 1D tensors were allowed too we could drop the `tuple(...)` from that. It's a small thing, but it helps a lot with readability.

```Python3
x = x.view(-1,  ten(x.shape[2 : 5]) // (kernel_size - 1))
```

If `torch.Size` was itself a tensor or otherwise operable with tensors that could be even neater, but I guess that change isn't likely for backward compatibility reasons. That would take this from a tiny feature to a complex one, so I'm not going there for now.

## Pitch
`Tensor.view` and `Tensor.reshape` should allow more argument types. Currently the docs say `shape (torch.Size or python:int...) – the desired size`. That's not actually quite right, as `tuple`s and `list`s are also allowed.

I would like that to be expanded to

```
(torch.Size | int tuple | int list | 1D np int array | 1D CPU int tensor | int)...
```

Where all of the iterables get expanded in place, so that `.view(1, 2, (3, 4, 5), 6)` is equivalent to `.view(1, 2, 3, 4, 5, 6)`.

**Comment by ngimel** [comment]
You can easily use tuples now
```
In [12]: a=torch.randn(8,8)                                                                                                                                          

In [13]: tup = (2,2)                                                                                                                                                 

In [14]: b=a.view(-1, *tup)                                                                                                                                          

In [15]: b.size()                                                                                                                                                    
Out[15]: torch.Size([16, 2, 2])
```

**Comment by SamPruden** [comment]
> You can easily use tuples now

I'm an idiot. I wrote code that did that a week ago. I have no excuse. Closing.
