### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED on Python 3.7 but not Python 3.6

### ISSUE THREAD

**Issue by 6etacat** [pytorch/pytorch#32626]
## 🐛 Bug

I installed PyTorch using conda on Python 3.7 environment, and when I run any RNN models, it will give me CUDNN_STATUS_EXECUTION_FAILED error. Rolling back to Python 3.6 solves the problem. This is with either defaults channel or conda-forge channel Pythons. 

## To Reproduce

1. `conda create -n test python=3.7`
2. `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`
3. Run `python main.py --cuda --epochs 6` in [official language model example](https://github.com/pytorch/examples/tree/master/word_language_model)

## Expected behavior

The program should run. 

## Environment

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Manjaro Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 430.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] mkl                       2019.5                      281    conda-forge
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch

## Additional context

If you run `conda install python=3.6` and then get environment, you will get:

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Manjaro Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 430.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] mkl                       2019.5                      281    conda-forge
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

cc @ezyang

**Comment by 6etacat** [comment]
I believe this is an issue with the PyTorch package in the conda repository. I think you guys may have uploaded the wrong binary (pytorch 1.1.0 cuda9.0) under `pytorch 1.4.0 py3.6_cuda10.1.243_cudnn7.6.3_0`.

**Comment by ngimel** [comment]
There is something wrong with your environment, probably some leftovers of earlier pytorch installations. Creating a fresh environment as in your reproduction instructions and installing pytorch 1.4 python 3.7 package reports correct pytorch version and correct cuda version:
```
python collect_env.py 
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1
```

**Comment by 6etacat** [comment]
After a couple hours of frustration, I finally figured it out. Seems like it's due to some remained files in `.local/lib/python3.7`. I don't remember why anything would be in there. Now it's working. :smiley:
