### ISSUE TITLE
Unbound local variable in LR scheduler

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#32639]
This is about a mysterious error. I have the following code that runs ok:
```python
import torch

class MultiStepLR(torch.optim.lr_scheduler._LRScheduler):
    def __init__(self, optimizer, gamma, milestones, last_epoch = -1):
        self.init_lr = [group['lr'] for group in optimizer.param_groups]
        self.gamma = gamma
        self.milestones = milestones
        super().__init__(optimizer, last_epoch)

    def get_lr(self, *args):
        global_step = self.last_epoch #iteration number in pytorch
        gamma_power = ([0] + [i + 1 for i, m in enumerate(self.milestones) if global_step >= m])[-1]
        return [init_lr * (self.gamma ** gamma_power) for init_lr in self.init_lr]

optimizer = torch.optim.SGD([torch.rand(1)], lr = 1)
scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])
```

Then, if instead of `*args` I write `step` (essentially I want to remove reliance on `self.last_epoch` while reusing some of existing LR scheduler functionality), this happens:

```
  File "bug.py", line 16, in <module>
    scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])
  File "bug.py", line 8, in __init__
    super().__init__(optimizer, last_epoch)
  File "/miniconda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 78, in __init__
    self.step()
  File "/miniconda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 151, in step
    for param_group, lr in zip(self.optimizer.param_groups, values):
UnboundLocalError: local variable 'values' referenced before assignment
```

In theory this can never happen, since all branches of code in `lr_scheduler.py` initialize the `values` variable

(It's also quite sad that the LR scheduler base class code in PyTorch is (unexpectedly) more complex than the optimizer base class code, this makes it really hard to understand what's going on. In the end I've had to do without PyTorch-provided scheduler API, since it actively prevents me from implementing a closed-form schedulers when I want to)

cc @vincentqb

**Comment by vincentqb** [comment]
* Can you also provide the modified code that fails?
* As we [discussed](https://github.com/pytorch/pytorch/issues/29697#issuecomment-566624811), have you considered LambdaLR to implement the closed form scheduler you wanted?

**Comment by vadimkantorov** [comment]
This code fails:
```
import torch

class MultiStepLR(torch.optim.lr_scheduler._LRScheduler):
    def __init__(self, optimizer, gamma, milestones, last_epoch = -1):
        self.init_lr = [group['lr'] for group in optimizer.param_groups]
        self.gamma = gamma
        self.milestones = milestones
        super().__init__(optimizer, last_epoch)

    def get_lr(self, step):
        global_step = self.last_epoch #iteration number in pytorch
        gamma_power = ([0] + [i + 1 for i, m in enumerate(self.milestones) if global_step >= m])[-1]
        return [init_lr * (self.gamma ** gamma_power) for init_lr in self.init_lr]

optimizer = torch.optim.SGD([torch.rand(1)], lr = 1)
scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])
```
i.e. `step` instead of `*args`

**Comment by vincentqb** [comment]
`base_lrs` simply come from the optimizer, so you can specify `optimizer(..., lr=1)`, and now your formula in `LambdaLR` is exactly the formula that determines your schedule.

You can also simply create a function to set your schedule:
```python
def my_scheduler(epoch):
  lr = 2**(-epoch)
  return lr

for i in range(len(optimizer.param_groups)):
  optimizer.param_groups[i]['lr'] = my_scheduler(epoch)
```

That being said, as mentioned in #26423, the function `get_lr` should not have an `epoch` parameter:
```python
import torch

class MultiStepLR(torch.optim.lr_scheduler._LRScheduler):
    def __init__(self, optimizer, gamma, milestones, last_epoch = -1):
        self.init_lr = [group['lr'] for group in optimizer.param_groups]
        self.gamma = gamma
        self.milestones = milestones
        super().__init__(optimizer, last_epoch)

    def get_lr(self):
        global_step = self.last_epoch #iteration number in pytorch
        gamma_power = ([0] + [i + 1 for i, m in enumerate(self.milestones) if global_step >= m])[-1]
        return [init_lr * (self.gamma ** gamma_power) for init_lr in self.init_lr]

optimizer = torch.optim.SGD([torch.rand(1)], lr = 1)
scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])
```

Since these solutions resolve your issue, I will close it. Please feel free to re-open if the problem persists.

**Comment by vadimkantorov** [comment]
1) In the first place, this issue is about a mystical Python error ("variable not bound", even though it seems to be bound), not about architectural discussion. I know that architectural decision about the pytorch scheduler has been taken. Even given that, this error is very cryptic for schedulers passing to the new API.

2) On `base_lrs`: No, the provided lambda function must be aware of the base_lrs values if it wants to force a specific lr, since LambdaLR expects it to return a multiplier. I undersand where `base_lrs` are coming from, but this still doesn't make it convenient to use LambdaLR in this scenario (and it is a common scenario), especially for polynomial decay functions that expect start and end lr. As you point out, I had to roll my own function.

**Comment by vincentqb** [comment]
> 1. In the first place, this issue is about a mystical Python error ("variable not bound", even though it seems to be bound), not about architectural discussion. I know that architectural decision about the pytorch scheduler has been taken. Even given that, this error is very cryptic for schedulers passing to the new API.

I agree that the documentation could be improved, see [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L163). Please feel free to open a pull request for this. :)

> 2. On `base_lrs`: No, the provided lambda function must be aware of the base_lrs values if it wants to force a specific lr, since LambdaLR expects it to return a multiplier. I undersand where `base_lrs` are coming from, but this still doesn't make it convenient to use LambdaLR in this scenario (and it is a common scenario), especially for polynomial decay functions that expect start and end lr. As you point out, I had to roll my own function.

`MultiplicativeLR` and `LambdaLR` are different. The former takes a function that returns a multiplicative factor. The latter multiplies the initial learning rate by the returned value of the function.
```python
import torch                                                                                                                                                             
from torch.nn import Parameter 
from torch.optim import SGD 
from torch.optim.lr_scheduler import LambdaLR, MultiplicativeLR

model = [Parameter(torch.randn(2, 2, requires_grad=True))] 
optimizer = SGD(model, lr=1.)                                                                                                                                            

func = lambda epoch: 2.                                                                                                                 
scheduler = LambdaLR(optimizer, func)

for epoch in range(10): 
  print(epoch, scheduler.get_last_lr()[0]) 
  optimizer.step() 
  scheduler.step() 
```

```
0 2.0
1 2.0
2 2.0
3 2.0
4 2.0
5 2.0
6 2.0
7 2.0
8 2.0
9 2.0
```

```python
model = [Parameter(torch.randn(2, 2, requires_grad=True))] 
optimizer = SGD(model, lr=1.)                                                                                                                                            

func = lambda epoch: 2.                                                                                                                 
scheduler = MultiplicativeLR(optimizer, func)

for epoch in range(10): 
  print(epoch, scheduler.get_last_lr()[0]) 
  optimizer.step() 
  scheduler.step() 
```

```
0 1.0
1 2.0
2 4.0
3 8.0
4 16.0
5 32.0
6 64.0
7 128.0
8 256.0
9 512.0
```

Hope this addresses your comment :)

**Comment by vadimkantorov** [comment]
1. Is the variable `values` really unbounded there? It seems initialized in all code branches. This is what is strange. Even if `get_lr(self, epoch)` signature should be avoided. The error is so cryptic that I thought it may indicate some code bug.

2. Then the choice of LambdaLR scheduler should force the user to pass `lr=1` to the optimizer. Yes, this is possible to hack around, I agree.

`The latter multiplies the initial learning rate by the returned value of the function.` -> essentially, this is also multiplicative, but wrt initial value, not the previous value.

**Comment by vincentqb** [comment]
Indeed, this should remain opened for 1.

**Comment by vincentqb** [comment]
#32997 addresses 1 by letting the relevant error being raised.

```python
In [1]: import torch 
   ...:  
   ...: class MultiStepLR(torch.optim.lr_scheduler._LRScheduler): 
   ...:     def __init__(self, optimizer, gamma, milestones, last_epoch = -1): 
   ...:         self.init_lr = [group['lr'] for group in optimizer.param_groups] 
   ...:         self.gamma = gamma 
   ...:         self.milestones = milestones 
   ...:         super().__init__(optimizer, last_epoch) 
   ...:  
   ...:     def get_lr(self, step): 
   ...:         global_step = self.last_epoch #iteration number in pytorch 
   ...:         gamma_power = ([0] + [i + 1 for i, m in enumerate(self.milestones) if global_step >= m])[-1] 
   ...:         return [init_lr * (self.gamma ** gamma_power) for init_lr in self.init_lr] 
   ...:  
   ...: optimizer = torch.optim.SGD([torch.rand(1)], lr = 1) 
   ...: scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])                                                                                                                                
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-7fad6ba050b0> in <module>
     14 
     15 optimizer = torch.optim.SGD([torch.rand(1)], lr = 1)
---> 16 scheduler = MultiStepLR(optimizer, gamma = 1, milestones = [10, 20])

<ipython-input-1-7fad6ba050b0> in __init__(self, optimizer, gamma, milestones, last_epoch)
      6         self.gamma = gamma
      7         self.milestones = milestones
----> 8         super().__init__(optimizer, last_epoch)
      9 
     10     def get_lr(self, step):

~/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/optim/lr_scheduler.py in __init__(self, optimizer, last_epoch)
     75         self._step_count = 0
     76 
---> 77         self.step()
     78 
     79     def state_dict(self):

~/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/optim/lr_scheduler.py in step(self, epoch)
    141                 print("1a")
    142                 # try:
--> 143                 values = self.get_lr()
    144                 # except TypeError:
    145                     # raise RuntimeError

TypeError: get_lr() missing 1 required positional argument: 'step'
```

**Comment by deJQK** [comment]
Perhaps this is related to modification of pytorch's convention on last epoch. Before 1.1, the initial last epoch is -1, but since 1.1 it is changed to 0.
1.0.1: https://pytorch.org/docs/1.0.1/_modules/torch/optim/lr_scheduler.html
1.1.0: https://pytorch.org/docs/1.1.0/_modules/torch/optim/lr_scheduler.html

You can find that last_epoch is set to 0 in 1.1.0 before assigned to self.last_epoch.
