### ISSUE TITLE
log cdf and log survival function of normal distribution

### ISSUE THREAD

**Issue by occam-ra-zor** [pytorch/pytorch#32632]
why is there no log_cdf and log_sf in atleast pytorch normal distributions yet ? while even tensorflow and scipy has it

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by alicanb** [comment]
We have `.cdf` for most distributions, you can get what you want (e.g. for normal distribution) via `log_cdf = normal_dist.cdf(x).log()` and `log_sf = torch.log1p(-normal_dist.cdf(x))`.

**Comment by fritzo** [comment]
@occam-ra-zor as open source contributors we must each ask ourselves "why don't I contribute the feature I want, for I am free to do so" 😉

**Comment by occam-ra-zor** [comment]
@alicanb  What I meant is numerically stable version.  :)

**Comment by alicanb** [comment]
Depending on where you are operating, what i wrote might be good enough. See here: https://gist.github.com/alicanb/8383e93aac3edb148168d029e5bdd20a

**Comment by vishwakftw** [comment]
We'll be tracking progress of this issue in https://github.com/pytorch/pytorch/issues/52973 henceforth. Closing because it's a duplicate.
