### ISSUE TITLE
LambdaLR type bug

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#32645]
## 🐛 Bug

In `torch/optim/lr_scheduler.pyi`, type of `LambdaLR`'s constructor is

```python
class LambdaLR(_LRScheduler):
    def __init__(self, optimizer: Optimizer, lr_lambda: float, last_epoch: int=...) -> None: ...
```

but description of `LambdaLR` in `torch/optim/lr_scheduler.py` is as follow.

```python
class LambdaLR(_LRScheduler):
    """Sets the learning rate of each parameter group to the initial lr
    times a given function. When last_epoch=-1, sets initial lr as lr.

    Args:
        optimizer (Optimizer): Wrapped optimizer.
        lr_lambda (function or list): A function which computes a multiplicative
            factor given an integer parameter epoch, or a list of such
            functions, one for each group in optimizer.param_groups.
        last_epoch (int): The index of last epoch. Default: -1.

    Example:
        >>> # Assuming optimizer has two groups.
        >>> lambda1 = lambda epoch: epoch // 30
        >>> lambda2 = lambda epoch: 0.95 ** epoch
        >>> scheduler = LambdaLR(optimizer, lr_lambda=[lambda1, lambda2])
        >>> for epoch in range(100):
        >>>     train(...)
        >>>     validate(...)
        >>>     scheduler.step()
    """
```

I think type of `LambdaLR` should be as follow.

```python
LRLambdaType = Callable[[int], float]

class LambdaLR(_LRScheduler):
    def __init__(self, optimizer: Optimizer, lr_lambda: Union[LRLambdaType, List[LRLambdaType]], last_epoch: int=...) -> None: ...
```

cc @vincentqb

**Comment by vincentqb** [comment]
I agree that the type should be updated. `lr_lambda` returns a float though. Did you mean the following?

```python
LRLambdaType = Callable[[int], float]

class LambdaLR(_LRScheduler):
    def __init__(self, optimizer: Optimizer, lr_lambda: Union[LRLambdaType, List[float]], last_epoch: int=...) -> None: ...
```

Please feel free to open a PR for this.

**Comment by jeongukjae** [comment]
@vincentqb No. `lr_lambda` takes a function that returns a float and takes a int, or such functions . So type of `lr_lambda` should be `Callable[[int], float]` or `List[Callable[[int], float]]`. You can see `lr_lambda` takes list of lambda functions in the example of `LambdaLR`.

**Comment by vincentqb** [comment]
> @vincentqb No. `lr_lambda` takes a function that returns a float and takes a int, or a list of such functions . So type of `lr_lambda` should be `Callable[[int], float]` or `List[Callable[[int], float]]`. You can see `lr_lambda` takes list of lambda functions in the example of `LambdaLR`.

Oops, you are correct :)

**Comment by jeongukjae** [comment]
> > @vincentqb No. `lr_lambda` takes a function that returns a float and takes a int, or a list of such functions . So type of `lr_lambda` should be `Callable[[int], float]` or `List[Callable[[int], float]]`. You can see `lr_lambda` takes list of lambda functions in the example of `LambdaLR`.
> 
> Oops, you are correct :)

I created a PR to fix this issue.
