### ISSUE TITLE
Ubuntu reboot when trainning

### ISSUE THREAD

**Issue by LeeHuan18** [pytorch/pytorch#32664]
## 🐛 Bug

I wrote a simple DNN in Pytorch, and using CPU to train it. However the ubuntu system randomly reboot when training, with or without using Jupyter notebook.

The code is simple DNN. Memory usage is around 1%. Runing the code in other computer doesn't cause reboot.

The computer is also no problem, after several test by techcian.

No error message. When training, the computer just freeze, then reboot. 

So what's the possible resaon or at least how to get the error message?
Thank you very much!

The enviroment is below:

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1
OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2
Python version: 3.7
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.129
cuDNN version: Could not collect
Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] numpy-stl==2.3.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch

**Comment by zhangguanheng66** [comment]
It seems very unique to your computer and hard to reproduce. @ezyang any ideas?

**Comment by ezyang** [comment]
Unfortunately this is almost certainly a configuration issue with your machine. You could try running a simple example with TensorFlow to see if it's specific to PyTorch. Some folks have reported similar issues in https://github.com/pytorch/pytorch/issues/24081 and have some workarounds, which may be worth a try. Other than that, there's not much we can do to help.
