### ISSUE TITLE
Will squeeze() influence gradient?

### ISSUE THREAD

**Issue by wilsonlym** [pytorch/pytorch#3268]
Hi all, recently I am implementing matrix factorization models in pytorch and find something interesting.
Here are two models:
```python
class Model1(nn.Module):
    def __init__(self, n_users, n_items, user_emb=5, item_emb=5):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, user_emb)
        self.item_emb = nn.Embedding(n_items, item_emb)
        self.user_bias = nn.Embedding(n_users, 1)
        self.item_bias = nn.Embedding(n_items, 1)

    def forward(self, users, items):
        user_emb = self.user_emb(users)
        item_emb = self.item_emb(items)
        user_bias = self.user_bias(users)
        item_bias = self.item_bias(items)
        ########################
        out = user_bias + item_bias
        out += (user_emb * item_emb).sum(1)
        return out.squeeze(1)
        ########################


class Model2(nn.Module):
    def __init__(self, n_users, n_items, user_emb=5, item_emb=5):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, user_emb)
        self.item_emb = nn.Embedding(n_items, item_emb)
        self.user_bias = nn.Embedding(n_users, 1)
        self.item_bias = nn.Embedding(n_items, 1)

    def forward(self, users, items):
        user_emb = self.user_emb(users)
        item_emb = self.item_emb(items)
        user_bias = self.user_bias(users)
        item_bias = self.item_bias(items)
        #########################
        out = (user_emb * item_emb).sum(1) + user_bias.squeeze(1) + item_bias.squeeze(1)
        return out
        #########################
```
For Model1, we will get the following warning

> lib/python3.5/site-packages/torch/autograd/_functions/basic_ops.py:15: UserWarning: other is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
>   return a.add_(b)

Does it mean it will be reduced to pointwise add? So I tried the following code:
```
loss_func = torch.nn.MSELoss()

model1 = Model1(10, 10)
model2 = Model2(10, 10)
model2.load_state_dict(model1.state_dict())

X = autograd.Variable(torch.LongTensor([1, 2]))
Y1= autograd.Variable(torch.LongTensor([2, 3]))
Y2 = autograd.Variable(torch.FloatTensor([4, 5]))

y1 = model1.forward(X, Y1)
print(loss_func(y1, Y2))

y1 = model2.forward(X, Y1)
print(loss_func(y1, Y2))
```
And we got the same outputs:

> Variable containing:
>  12.9656
> [torch.FloatTensor of size 1]
> 
> Variable containing:
>  12.9656
> [torch.FloatTensor of size 1]

But for gradient, 
```
y1 = model1.forward(X, Y1)
model1.zero_grad()
loss = loss_func(y1, Y2)
loss.backward()
for p in list(model1.parameters()):
    print(p.grad)

y1 = model2.forward(X, Y1)
model2.zero_grad()
loss = loss_func(y1, Y2)
loss.backward()
for p in list(model2.parameters()):
    print(p.grad)
```
We got quite different results:
model1:

> Variable containing:
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  8.2215 -8.7861 -3.2524  5.8750  4.0597
>  9.4413  2.6375  0.7764 -4.0542  4.1427
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
> [torch.FloatTensor of size 10x5]
> 
> Variable containing:
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   8.4739  -2.0651  -8.1959  -6.7616  11.1125
>   6.7948   6.4563   3.0686  11.5589   3.6424
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
>   0.0000   0.0000   0.0000   0.0000   0.0000
> [torch.FloatTensor of size 10x5]
> 
> Variable containing:
>  0.0000
> -3.1769
> -3.9797
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
> [torch.FloatTensor of size 10x1]
> 
> Variable containing:
>  0.0000
>  0.0000
> -3.1769
> -3.9797
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
> [torch.FloatTensor of size 10x1]

model2:

> Variable containing:
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  3.6496 -3.9003 -1.4438  2.6080  1.8022
>  5.2502  1.4667  0.4317 -2.2545  2.3037
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
> [torch.FloatTensor of size 10x5]
> 
> Variable containing:
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  3.7617 -0.9167 -3.6383 -3.0016  4.9330
>  3.7785  3.5903  1.7064  6.4277  2.0255
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
>  0.0000  0.0000  0.0000  0.0000  0.0000
> [torch.FloatTensor of size 10x5]
> 
> Variable containing:
>  0.0000
> -3.1769
> -3.9797
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
> [torch.FloatTensor of size 10x1]
> 
> Variable containing:
>  0.0000
>  0.0000
> -3.1769
> -3.9797
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
>  0.0000
> [torch.FloatTensor of size 10x1]

Thus, I am wondering why there is difference in gradient?
By the way, I am using pytorch 0.2.0_3 and python 3.5.2. Thanks for your time!

**Comment by JasonLC506** [comment]
I encounter another problem with using Embedding.
Actually if you replace
(user_emb * item_emb).sum(1) + user_bias.squeeze(1) + item_bias.squeeze(1) 
with
(user_emb * item_emb).sum(1) + user_bias + item_bias
the dimension of output becomes odd.

To temporarily solve the problem, following the Linear module defined in pytorch, use torch.nn.Parameter(torch.FloatTensor(shape)) to replace torch.nn.Embedding(shape)

**Comment by zou3519** [comment]
I think this bug has been fixed somewhere down the line. @wilsonlym I reran your code on master and it now errors out with the following:
```
<ipython-input-6-0a8660ac7977> in forward(self, users, items)
     19         out = user_bias + item_bias
     20         import pdb; pdb.set_trace()
---> 21         out += (user_emb * item_emb).sum(1)
     22         return out.squeeze(1)
     23         ########################

RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 1
```

This implies the following fix to model1:
```
out = user_bias + item_bias
out += (user_emb * item_emb).sum(1).unsqueeze(1)  # added the unsqueeze(1)
return out.squeeze(1)
```

which results in the gradients from model1 and model2 being equal.

**Comment by wilsonlym** [comment]
Thank you so much @zou3519 ! Nice to hear that, and I will take a look at it.

**Comment by zou3519** [comment]
If you're curious, I think what happened was `squeeze()` was rewritten [at some point](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/NativeFunctions.cpp#L229-L232). Let me know if you still spot a bug
