### ISSUE TITLE
When using autograd in a Jupyter notebook, cuda is initialized even if cuda is not used

### ISSUE THREAD

**Issue by adefossez** [pytorch/pytorch#32707]
## 🐛 Bug

When using autograd in a Jupyter notebook, cuda is initialized even if it is not used. This prevents any use of `ProcessPoolExecutor` for instance if any gradient has been computed in the main process.

## To Reproduce

```python
import torch as th
from concurrent.futures import ProcessPoolExecutor

def run():
    x = th.tensor([1.], requires_grad=True)
    for _ in range(100):
        loss = th.sum((x + 1)**2)
        loss.backward()
        x.data -= 0.01 * x.grad
        x.grad.zero_()
    return x[0].item()
        
with ProcessPoolExecutor(1) as pool:
    r = pool.submit(run)
    print("before it works", r.result())
print("calling run in main process", run())
print("Now it breaks, but only in jupyter notebook")
with ProcessPoolExecutor(1) as pool:
    r = pool.submit(run)
    r.result()
```

1. Save the above code as `bug.py` and run it, it works fine.
1. Save the above code in a Jupyter notebook cell and run it.
1. Observe that the last call to `r.result()` fail. If you go see the jupyter process in the terminal, you will see some error related to cuda initialization. However, we do not use cuda in this code.

Here is the stack trace from the Jupyter process in the terminal:
```bash
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: initialization error (setDevice at /opt/conda/conda-bld/pytorch_1573049310284/work/c10/cuda/impl/CUDAGuardImpl.h:42)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f5a70cdf687 in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xedf2 (0x7f5a70f12df2 in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: torch::autograd::Engine::set_device(int) + 0x159 (0x7f5a762c15d9 in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: torch::autograd::Engine::thread_init(int) + 0x1a (0x7f5a762c160a in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: torch::autograd::python::PythonEngine::thread_init(int) + 0x2a (0x7f5aa0b485ca in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xc819d (0x7f5acaa1319d in /private/home/defossez/miniconda3/envs/main/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6)
frame #6: <unknown function> + 0x76db (0x7f5acdad56db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #7: clone + 0x3f (0x7f5acd7fe88f in /lib/x86_64-linux-gnu/libc.so.6)
````

## Expected behavior

I expected cuda not to be initialized when using jupyter so that I can both run computation in the main thread and also use `ProcessPoolExecutor`.

## Environment

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.3.1
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.3.1           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu100    pytorch

cc @ngimel

**Comment by VitalyFedyunin** [comment]
Might be same as #32835 as I have seen this funny CUDA errors when autograd threads went nuts.

**Comment by VitalyFedyunin** [comment]
@adefossez  can you please retest with pytorch nightly build. It should be fixed.
