### ISSUE TITLE
DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#32743]
This has been flaky on master lately, disabling it via #30978

- [result 1](https://circleci.com/gh/pytorch/pytorch/4363741?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console)
- [result 2](https://circleci.com/gh/pytorch/pytorch/4356508?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console)
- [result 3](https://circleci.com/gh/pytorch/pytorch/4356068?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jianyuh** [comment]
The same as https://github.com/pytorch/pytorch/issues/32644. Add the asserts in https://github.com/pytorch/pytorch/pull/32739 and temporarily disable the tests in https://github.com/pytorch/pytorch/pull/32742.

**Comment by driazati** [comment]
This task will automatically disable the test rather than have to wait for that PR to land, I think we should keep it open (or just change the title of #32644 to be the same as this one, then #32742 will be unnecessary).

**Comment by jianyuh** [comment]
Sure. Reopen the issue.

**Comment by jianyuh** [comment]
Check the progress in https://github.com/pytorch/pytorch/issues/32644. Closing the issue.
