### ISSUE TITLE
LambdaLR.load_state_dict has a undocumented side-effect

### ISSUE THREAD

**Issue by PetrochukM** [pytorch/pytorch#32756]
## 🐛 Bug

`LambdaLR.load_state_dict` has a undocumented side-effect here: https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L220

This caused us an issue because it'd modify our state dict object without our knowledge. We finally noticed the bug after we accidentally ran `load_state_dict` twice with the same state object and it failed.

## To Reproduce

Code:
```python
import torch

from torch.optim.lr_scheduler import LambdaLR

params = torch.nn.LSTM(10, 10).parameters()
optimizer = torch.optim.Adam(params)
scheduler = LambdaLR(optimizer, lambda x: 1.0)
state_dict = scheduler.state_dict()
scheduler.load_state_dict(state_dict)
scheduler.load_state_dict(state_dict)
```

Trace:
```bash
Traceback (most recent call last):
  File "blah.py", line 10, in <module>
    scheduler.load_state_dict(state_dict)
  File "/Users/michaelp/Code/Text-to-Speech/venv/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 150, in load_state_dict
    lr_lambdas = state_dict.pop('lr_lambdas')
KeyError: 'lr_lambdas'
```

## Expected behavior

The side-effect is either removed or documented. 

cc @vincentqb

**Comment by vincentqb** [comment]
Thanks for reporting this! Indeed, `LambdaLR` and its derivative, `MultiplicativeLR`, both suffer from this bug. They should be the only ones though as they are the only ones using `pop`. It seems like a fix would be to simply replace that line 220 by `lr_lambdas = state_dict['lr_lambdas']`. Could this have other side effects? If not, please feel free to open a pull request with this.

**Comment by jyx1244204317** [comment]
lr_lambdas = state_dict['lr_lambdas'] is also error.
KeyError: 'lr_lambdas'
