### ISSUE TITLE
[quantization] Need fused relu FP16 dynamic quantized linear

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#32775]
Basically revert this https://github.com/pytorch/pytorch/pull/32774 while making the op actually use the ReluFused template param

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
There doesn't seem to be a use-case for this op. Currently no plan to implement it. Can revisit if there is a need.
cc @raghuramank100
