### ISSUE TITLE
Grammar error - Transforms on torch.*Tensor

### ISSUE THREAD

**Issue by njcurtis3** [pytorch/pytorch#32818]
## 📚 Documentation
Just a very small grammatical issue. 
![grammar_error_transformsontorch](https://user-images.githubusercontent.com/11468122/73418974-183ece00-42e3-11ea-992b-bdce07172f07.PNG)
Suggested fix: "mutates" to "mutate"

**Comment by vincentqb** [comment]
Thanks for pointing this out. Please feel free to open a pull request for this.

**Comment by njcurtis3** [comment]
Thanks for adding labels. Forgot to do that. I will make a pull request
