### ISSUE TITLE
Incorrect typing errors

### ISSUE THREAD

**Issue by Tetratrio** [pytorch/pytorch#32824]
## 🐛 Bug

Mypy will report typing errors for some operations that should be allowed. I have encountered four different type check errors although I am only sure one of them is an actual bug. But I will list the others as well.

#### Error 1 - in-place operations on tensor
```python
t_1 = torch.rand(3)
t_2 = torch.ones_like(t_1)
t_1.add_(t_2)
```
The error message:
```
error: "Tensor" has no attribute "add_"; maybe "addr_", "addmv_", or "addmm_"?
```
---
#### Error 2 - creating a parameter requires argument 'requires_grad' even though it has a default value
```python
t_1 = torch.rand(3)
p_1 = torch.nn.Parameter(t_1)
```
The error message:
```
error: Too few arguments for "Parameter"
```
---
#### Error 3 - `torch.is_tensor()` is not counted as a assertion for typing
```
from typing import Union
def scale_values(input: torch.Tensor, weight: Union[float, torch.Tensor]) -> torch.Tensor:
    if not torch.is_tensor(weight):
        weight = torch.tensor(weight)
    # the following line is required for mypy to not report an error:
    # assert isinstance(weight, torch.Tensor)
    return input * weight.to(input)
```
The error message:
```
error: Item "float" of "Union[float, Tensor]" has no attribute "to"
```
---
#### Error 4 - `torch.nn.Module.training` is not a bool
```python
class Dropout(torch.nn.Module):

    def forward(self, input) -> torch.Tensor: # type: ignore
        return torch.nn.functional.dropout(
            input,
            p=0.5,
            training=self.training
        )
```
The error message:
```
error: Argument "training" to "dropout" has incompatible type "Union[Tensor, Module[Any]]"; expected "bool"
```

## Expected behavior

I know that the first error is an actual bug but the others I am not sure of as there might be some internal design decision that create these errors and that it is intended.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                mkl
[conda] mkl                       2019.4         243
[conda] mkl-service          2.3.0            py37he904b0f_0
[conda] mkl_fft                  1.0.14           py37ha843d7b_0
[conda] mkl_random         1.1.0             py37hd6b4f25_0
[conda] pytorch                1.4.0             py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision           0.5.0            py37_cu101    pytorch

## Additional context

Using mypy 0.750

cc @ezyang

**Comment by vincentqb** [comment]
Would you be interested in opening pull requests to address these?

**Comment by Tetratrio** [comment]
I would need to read up more about mypy before I do that. I could potentially open one sometime in the future if no one else has fixed this issue by then. But I am unable to at this very moment.

**Comment by ezyang** [comment]
I think I agree (1) and (2) are bugs, and should be relatively easy to fix, just change the pyi files to have the correct types. We would love a PR for them. (3) is also a bug but is going to be a bit more difficult to fix, I suspect the only way to fix this is with a mypy plugin (I tried to google for existing references to this problem but couldn't find them). (4) also looks like a bug, I don't know how easy it is to fix.

**Comment by rgommers** [comment]
(1), (2) and (4) are all fixed.

(3) will be coming back in many forms; `mypy` has trouble narrowing types for code like that. The [docs on Union types](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#union-types) recommend using `isinstance(..., some_type)` to remove `some_type` from the union and give the narrower type for code that follow.

This works:
```
from typing import Union
def scale_values(input: torch.Tensor, weight: Union[float, torch.Tensor]) -> torch.Tensor:
    if isinstance(weight, float):
        weight = torch.tensor(weight)

    return input * weight.to(input)
```
Using `if not isinstance(weight, torch.Tensor)` instead of `if isinstance(weight, float)` still works.

There are a number of other issues where unions need narrowing for type checking in pytorch to work, so it would be good to figure this out. A plugin should look something like:
```
from typing import Optional, Callable

from mypy.plugin import Plugin, FunctionContext
from mypy.types import Type, Instance
from mypy.options import Options


class TorchPlugin(Plugin):
    def __init__(self, options: Options) -> None:
        super().__init__(options)

    def get_function_hook(self, fullname: str
                         ) -> Optional[Callable[[FunctionContext], Type]]:
        if fullname == 'torch.is_tensor':
            return get_istensor_type

        return None


def get_istensor_type(ctx: FunctionContext) -> Type:
    print('TODO: force type narrowing here somehow')
    return ctx.default_return_type

def plugin(version: str):
    # ignore version argument, the plugin works with all mypy versions (TODO:
    # check that).
    return TorchPlugin
```

That runs fine, I just haven't figured out how to narrow the type. All this stuff is undocumented and still experimental (API for `get_function_hook` is considered poor and may change without warning), so I'm not yet sure if this is actually a healthy idea. If a plugin like this is added, it would be good to pin the mypy version it works with.

**Comment by rgommers** [comment]
In this case (and probably in most other cases) changing the code is better than a plugin. Here `is_tensor` is trivial:
```
def is_tensor(obj):
    return isinstance(obj, torch.Tensor)
```
so just replace any `is_tensor` call with `isinstance(obj, torch.Tensor)` and things will work. I'll open a PR.

**Comment by rgommers** [comment]
This is all fixed (3 is a user code snippet that needs changing as in the comment above), so closing.

gh-38062 replaces `is_tensor` usages in this repo in anticipation of adding mypy typechecking on that code, to avoid potential issues.
