### ISSUE TITLE
Autograd fails if used before multiprocessing Pool

### ISSUE THREAD

**Issue by Tetratrio** [pytorch/pytorch#32835]
## 🐛 Bug

Just like [#3966](https://github.com/pytorch/pytorch/issues/3966) autograd fails when using it on main process before a child process but not for normally started processes but for process pools.

## To Reproduce
```python
import torch
from torch import multiprocessing as mp

FAIL = True

def f(a=1):
    torch.rand(3).requires_grad_(True).mean().backward()
    return a ** 2

if FAIL:
    f()

# This always works
p = mp.Process(target=f)
p.start()
p.join()

# This fails if autograd has been used
with mp.Pool(3) as pool:
    result = pool.map(f, [1, 2, 3])
print(result)
```

## Expected Behavior
This can be fixed by adding
```python
if __name__ == '__main__':
    mp.set_start_method("spawn")
```
As using a normal mp.Process works without this addition (after a fix for the issue described in [#3966](https://github.com/pytorch/pytorch/issues/3966)) I am unsure if this is a bug or not. Adding the snippet above to your code can be hard for more interactive uses such as jupyter notebook.
## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas 1.0 mkl
[conda] mkl 2019.4 243
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.14 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] pytorch 1.4.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.5.0 py37_cu101 pytorch

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
This is more or less expected as fork and threading is never a very good thing to do.

We should replicate the logic we have for cuda [here](https://github.com/pytorch/pytorch/blob/94ddc2c462bd7c79426057d67b03d4a397db0dd1/torch/csrc/cuda/Module.cpp#L32-L51) in the autograd engine to raise a nice error stating that spawn should be used (everyone should be in python 3.4+ now so everyone should be able to do that).

Will you be able to send a PR to do that? :)

**Comment by Tetratrio** [comment]
I am not too familiar with C++ so better someone else takes a look, sorry.
Definitely worth adding some kind of error message as you suggested.

**Comment by gchanan** [comment]
We probably want a check around https://github.com/pytorch/pytorch/blob/13e4ee7883106c412d3efe17fbbe8087a6d4c5e2/torch/csrc/autograd/engine.cpp#L740, which is initializing the autograd.
