### ISSUE TITLE
Installing torch nightly gives me 1.4.0

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#32845]
## 🐛 Bug

Installing torch nightly gives me 1.4.0.

In a clean virtual environment, run the following command, as instructed on https://pytorch.org/get-started/locally/

    pip install -U --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html

Then

```
$ pip freeze | grep torch                                                                                    
torch==1.4.0
torchvision==0.5.0
```

**Comment by xsacha** [comment]
I do not think there is a CUDA 11.0 version yet.
Try changing cu110 to cu101
https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html

**Comment by xuhdev** [comment]
@xsacha You're right, got characters swapped XD
