### ISSUE TITLE
Implement Swish activation function

### ISSUE THREAD

**Issue by Ujjwal-9** [pytorch/pytorch#3285]
Swish activation function often performs better than ReLu.
[Paper](https://arxiv.org/pdf/1710.05941) on Swish Function recently published by a team at Google.

**Comment by Ujjwal-9** [comment]
hey, I am up for it if you find this relevant. If so then could you guide me which files will be needing attention to implement it? 😅

**Comment by zou3519** [comment]
We'd like to wait a bit before deciding to add the swish activation function to pytorch. Please see [this](https://github.com/pytorch/pytorch/pull/3182#issuecomment-337982454) and [this](https://github.com/pytorch/pytorch/issues/3169#issuecomment-337736118) for previous discussion on this topic.

[this](https://github.com/pytorch/pytorch/pull/3182#issuecomment-337982454) is how you would go about implementing it :)

**Comment by Ujjwal-9** [comment]
👍🏻
