### ISSUE TITLE
AssertionError: torch.nn.quantized.ReLU does not support inplace

### ISSUE THREAD

**Issue by ashishgupta2598** [pytorch/pytorch#32859]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
Are you using master? I remember this is already fixed by @z-a-f

**Comment by z-a-f** [comment]
I am sure this will be resolved after rebase

**Comment by z-a-f** [comment]
Please, reopen if this shows again
