### ISSUE TITLE
device().has_index() calls torch_cpu function and crashes

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#32865]
## 🐛 Bug

Since PyTorch 1.5, torch_cpu and torch_cuda have been split.
After updating to this version, my code now crashes on:
ATen/Functions.h:1197
```
if (options.device().has_index()) {
```

I notice the call stack shows it calling torch_cpu instead of torch_cuda despite my device being CUDA.
{type_=CUDA (1) index_=0 }

If I remove torch_cpu.dll, it fails delay loading the DLL.
When listing dependencies of torch, it appears to only be linked to torch_cpu.dll

Site of crash in debug mode:
![image](https://user-images.githubusercontent.com/61218/73537271-cf6a4f00-4473-11ea-9199-692067b09505.png)

## To Reproduce

1. Try to use cuda and link to torch

## Expected behavior

CUDA code uses torch_cuda

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0 nightly
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): prebuilt
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 10.1/7.6
 - GPU models and configuration: RTX 2060
 - Any other relevant information:

cc @ngimel @peterjc123

**Comment by peterjc123** [comment]
Seems to be related to https://github.com/pytorch/pytorch/issues/31611.

**Comment by ezyang** [comment]
Yes, I agree with this diagnosis. Unfortunately I haven't had time to setup a Windows reproduction environment for the issue yet.

**Comment by xsacha** [comment]
I don't seem to get this anymore with the latest nightly. Not sure when it was fixed.
