### ISSUE TITLE
PILLOW_VERSION not available in PIL 7.0.0

### ISSUE THREAD

**Issue by beaulima** [pytorch/pytorch#32887]
The new version of PIL does not support PILLOW_VERSION anymore
this creates an error in 

torchvision/transforms/functional.py
at 
from PIL import Image, ImageOps, ImageEnhance,PILLOW_VERSION (line 6)

ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' ... python3.7/site-packages/PIL/__init__.py)

the package  PIL version 7.0 says

# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 7.0.0.
# Use __version__ instead.
__version__ = _version.__version__

Maybe a workaround would be

by replacing line  6 and 7 in
torchvision/transforms/functional.py
by 
import PIL
from PIL import Image, ImageOps, ImageEnhance
PILLOW_VERSION = PIL.__version__

for me it resolved the thing

**Comment by peterjc123** [comment]
Please see https://github.com/pytorch/vision/issues/1712 for more details.
