### ISSUE TITLE
RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by zihaozhang9** [pytorch/pytorch#32893]
I installed pytorch using the following command
`conda install pytorch == 1.1.0 torchvision == 0.3.0 cudatoolkit = 10.0 -c pytorch`

Then run the code and find the following error
`     input = module (input)
   File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in__call__
     result = self.forward (* input, ** kwargs)
   File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 74, in forward
     self.num_batches_tracked + = 1
RuntimeError: CUDA error: misaligned address`

` nvcc -V`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

` cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2`
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

**Comment by ezyang** [comment]
Please try again on a newer version of PyTorch, and reopen the bug if this persists.

**Comment by yeyupiaoling** [comment]
@zihaozhang9 请问你是如何解决这个问题的，我的机器也出现了这个问题。
```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```

错误信息：
```
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    main()
  File "train.py", line 157, in main
    batch_size=args.batch_size)
  File "train.py", line 92, in train
    nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
  File "/home/test/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/utils/clip_grad.py", line 35, in clip_grad_norm_
    if clip_coef < 1:
RuntimeError: CUDA error: misaligned address

```

**Comment by zihaozhang9** [comment]
> @zihaozhang9 请问你是如何解决这个问题的，我的机器也出现了这个问题。
> 
> ```
> conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
> ```
> 
> 错误信息：
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 161, in <module>
>     main()
>   File "train.py", line 157, in main
>     batch_size=args.batch_size)
>   File "train.py", line 92, in train
>     nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
>   File "/home/test/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/utils/clip_grad.py", line 35, in clip_grad_norm_
>     if clip_coef < 1:
> RuntimeError: CUDA error: misaligned address
> ```

我的是显卡硬件坏了，已经寄回厂家维修了。

The graphics card hardware is damaged. It has been mailed to the manufacturer for repair.

**Comment by yeyupiaoling** [comment]
好的，谢谢
