### ISSUE TITLE
Unittests for c10 types check from jit tracing

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#32892]
An issue was raised that some ops registered with c10 were not correctly handled in jit tracing. #32886 resolves one of such issues. 

Probably need unittests for c10 op registrations + tracing/scripting

cc @suo

**Comment by masahi** [comment]
I hit this issue with the following module after quantize and trace. #32886 resolved it.
```
class Hsigmoid(nn.Module):
    def __init__(self, inplace=True):
        super(Hsigmoid, self).__init__()
        self.inplace = inplace
        self.skip_add = nn.quantized.FloatFunctional()
        self.quant = QuantStub()
        self.dequant = DeQuantStub()

    def forward(self, x):
        quant = self.quant(x)
        out = F.relu(self.skip_add.add_scalar(quant, 3.))
        return self.dequant(out)
```

**Comment by z-a-f** [comment]
@masahi is it still there after #32886?

**Comment by masahi** [comment]
No I said #32886 resolved my issue. Thanks :)
