### ISSUE TITLE
Trying to compile Pytorch for contributing to the codebase.

### ISSUE THREAD

**Issue by sarkararpan710** [pytorch/pytorch#32908]
Hi, I have wanting to understand the PyTorch codebase and am interested to  contributing to PyTorch and as a first step, I am trying to compile PyTorch from source using the command python setup.py develop.

Previously I was able to compille PyTorch without the develop flag in order to do the FastAI course.
But while compiling it for develop mode. I am getting this error. I tried looking for solutions and saw many people able to get through this error by compiling protobuf from source. I compiled protobuf from source using Visual Studio Solution file. 

This is the error I am facing when trying to build PyTorch for development

`(base) D:\pytorch\pytorch\pytorch>python setup.py develop
Building wheel torch-1.5.0a0+040bc1d
-- Building version 1.5.0a0+040bc1d
cmake --build . --target install --config Release -- -j 8
[2/804] Linking CXX shared library bin\torch_cpu.dll
FAILED: bin/torch_cpu.dll lib/torch_cpu.lib
cmd.exe /C "cd . && D:\CMake\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cpu.dir --manifests  -- "D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe" /nologo @CMakeFiles/torch_cpu.rsp  /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO   && cd ."
LINK: command "D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe /nologo @CMakeFiles/torch_cpu.rsp /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cpu.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\torch_cpu.lib and object lib\torch_cpu.exp
libprotobuf.lib(text_format.cc.obj) : error LNK2019: unresolved external symbol __std_reverse_trivially_swappable_8 referenced in function "void __cdecl std::_Buffered_inplace_merge_divide_and_conquer2<class google::protobuf::Message const * *,class google::protobuf::DynamicMapSorter::MapEntryMessageComparator>(class google::protobuf::Message const * *,class google::protobuf::Message const * *,class google::protobuf::Message const * *,__int64,__int64,class google::protobuf::Message const * * const,__int64,class google::protobuf::DynamicMapSorter::MapEntryMessageComparator,class google::protobuf::Message const * *,class google::protobuf::Message const * *,__int64,__int64)" (??$_Buffered_inplace_merge_divide_and_conquer2@PEAPEBVMessage@protobuf@google@@VMapEntryMessageComparator@DynamicMapSorter@23@@std@@YAXPEAPEBVMessage@protobuf@google@@00_J1QEAPEBV123@_JVMapEntryMessageComparator@DynamicMapSorter@23@0011@Z)
libprotobuf.lib(wire_format.cc.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8
bin\torch_cpu.dll : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "D:\pytorch\pytorch\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "D:\pytorch\pytorch\pytorch\tools\setup_helpers\cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "D:\pytorch\pytorch\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\Anaconda\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.`

cc @peterjc123

**Comment by peterjc123** [comment]
Some suggestions according to my experience:
1. MSVC 2017 14.16.27023 is not supported. Please try out VS 2019 instead.
2. As for the linking error, please use the protobuf in this repo rather than the one in your system.

**Comment by cristianPanaite** [comment]
Hello @sarkararpan710,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error. 

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.
