### ISSUE TITLE
isfinite() as a torch.Tensor method

### ISSUE THREAD

**Issue by bnehoran** [pytorch/pytorch#32910]
## 🚀 Feature

Allow `isfinite()` to be a tesnor method, so that it can be called as `x.isfinite()` instead of `torch.isfinite(x)`. That is, allow both options.

#### Example usage:
```python
# slightly awkward code
print(torch.isfinite(x.sqrt()).sum().item())

# much neater
print(x.sqrt().isfinite().sum().item())
```
_(Note: This is a simplification of an actual use case. Of course, for `sqrt()` you could just check for negative inputs.)_

As an added bonus, if numpy also follows suit, it could allow writing simpler code that seamlessly works on both PyTorch tensors and numpy ndarrays (deciding between `torch.isfinite(x)` and `np.isfinite(x)` vs simply `x.isfinite()`).
There may very well be other functions for which this could be useful. This is just one that’s been bothering me a lot.

**Comment by Kiyosora** [comment]
I'm a newbie of pytorch, and I'd like to have a try on this. :)

**Comment by ShawnZhong** [comment]
This issue is resolved in https://github.com/pytorch/pytorch/pull/37942
