### ISSUE TITLE
[ONNX] torch.onnx emits -1 in shape for Expand

### ISSUE THREAD

**Issue by shinh** [pytorch/pytorch#32926]
## 🐛 Bug

torch.onnx may emit -1 in the second input of Expand op for `torch.tensor.expand`. It seems ONNX does not allow -1 as dims in the expanded shape. I think torch.onnx should translate -1 to 1.

## To Reproduce

1. Run the following script.
1. Notice the Constant node fed to Expand op has a negative value.

```
import onnx
import onnx.numpy_helper
import torch

class Model(torch.nn.Module):
    def forward(self, x):
        return x.expand((-1, 3, 3, 1))

model = Model()
torch.onnx.export(model, torch.rand(3, 3, 1, 1), 'expand.onnx')

m = onnx.load('expand.onnx')
n = m.graph.node[0]
assert n.op_type == 'Constant'
# [-1  3  3  1]
print(onnx.numpy_helper.to_array(n.attribute[0].t))
```

## Expected behavior

I think -1 should be translated to 1.

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.4.0
[pip3] torchvision==0.2.1
[pip3] warpctc-pytorch==0.1
[conda] Could not collect

## Additional context

Both ONNX's shape inference and ONNX runtime are confused by this.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
We will take a look.

**Comment by garymm** [comment]
I think fixed by https://github.com/pytorch/pytorch/pull/34069. Please re-open with more details if this is not the case.
