### ISSUE TITLE
Effectiveness of pruning

### ISSUE THREAD

**Issue by xDuck** [pytorch/pytorch#32928]
When using the new pruning module in 1.4 `torch.nn.utils.prune` I notice it is only zeroing out the weights in my model, not actually re-structuring the model to remove the connections, so my model size remains the same before and after pruning.

Is there a step I am missing or do I have to implement my own model reducing function based on the pruning?

I am following the example here - https://github.com/pytorch/tutorials/pull/605/files#diff-29c3cda700bf3f4f1074765450c286aa

**Comment by xDuck** [comment]
After reading the original issue and looking into the code, it seems pruning is strictly in research phase still and not actually providing any benefits yet.

**Comment by LearnedVector** [comment]
bump! any news on this? also trying pruning but wanting to know if it's even worth it at this stage for model compression.

**Comment by Aarsh2001** [comment]
> When using the new pruning module in 1.4 `torch.nn.utils.prune` I notice it is only zeroing out the weights in my model, not actually re-structuring the model to remove the connections, so my model size remains the same before and after pruning.
> 
> Is there a step I am missing or do I have to implement my own model reducing function based on the pruning?
> 
> I am following the example here - https://github.com/pytorch/tutorials/pull/605/files#diff-29c3cda700bf3f4f1074765450c286aa

Have you reached any conclusion regarding , reducing the model size after pruning?
