### ISSUE TITLE
Tensor constructor passed numpy ndarray does not check type.

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3293]
```
>>> torch.Tensor(numpy.ndarray(shape=(2,2),dtype="int8"))

 0.6229  0.0000
 0.0000  0.0000
[torch.FloatTensor of size 2x2]

>>> torch.from_numpy(numpy.ndarray(shape=(2,2),dtype="int8"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.
```

According to @colesbury, however, it does look like ndarray passed into Tensor is doing the correct codepath.

CC @aszlam

**Comment by apaszke** [comment]
I'm not sure what can we do about it short term. There's no guarantee that we can reliably represent `int8` until we change `char` to `signed char`. It's fine to use such array in a constructor which will cast the memory

**Comment by ezyang** [comment]
The bug is not that we don't support int8, but that if we don't support it, Tensor constructor needs to reject it.

**Comment by apaszke** [comment]
No, I can't see why would we need to make it this way. `torch.from_numpy` has no choice other than raising an error, because there is no corresponding type in torch, so it would violate the contract. However, when you use a tensor constructor, you explicitly agree on what the type should be, so casting the array to whatever is needed is a reasonable decision

**Comment by aszlam** [comment]
maybe I am misunderstanding "you explicitly agree on what the type should be" ?   with torch.Tensor(numpy_array) ?

________________________________

**Comment by apaszke** [comment]
Yes. `torch.Tensor` is always an alias for one of the tensor types, not a "try to infer the datatype" thing. By default it's `torch.FloatTensor`, but you can change it with `torch.set_default_tensor_type`

**Comment by ezyang** [comment]
NOTABUG.
