### ISSUE TITLE
Dynamic Linear quantization fails with engine 'qnnpack when trying to  create a quantized based model for use on an Android mobile device

### ISSUE THREAD

**Issue by DeleOgunjumelo** [pytorch/pytorch#32934]
## 🐛 Bug

Dynamic Linear quantization fails with engine 'qnnpack.' I am trying to create a quantized based model for use on an Android mobile device. 

## To Reproduce

Steps to reproduce the behaviour:
1. Modify ( Enable quantization ) python script for serialising a network model in the root folder of Pytorch Mobile demo HelloWorld app (https://pytorch.org/mobile/android/ ).

See modified script below: -

import torch
import torchvision

model = torchvision.models.resnet18(pretrained=True)
model.eval()

model.qconfig = torch.quantization.get_default_qconfig('qnnpack')
torch.backends.quantized.engine = 'qnnpack'
quant_model = torch.quantization.quantize_dynamic(model.cpu(), {torch.nn.Linear}, dtype=torch.qint8)

example = torch.rand(1, 3, 224, 224)
traced_script_module = torch.jit.trace(quant_model, example)
traced_script_module.save("app/src/main/assets/model.pt")

# Error
```
/home/pytorch-mobile/android-demo-app/HelloWorldApp$ python3 trace_test_model.py 
Traceback (most recent call last):
  File "trace_test_model.py", line 13, in <module>
    traced_script_module = torch.jit.trace(quant_model, example)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torchvision/models/resnet.py", line 216, in forward
    return self._forward_impl(x)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torchvision/models/resnet.py", line 211, in _forward_impl
    x = self.fc(x)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pytorch-mobile/env/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/linear.py", line 41, in forward
    x, self._packed_params._packed_params)
RuntimeError: Expected temporary cpp type wrapper of type PackedLinearWeight (cast at /pytorch/aten/src/ATen/cpp_custom_type_hack.h:23)
```

# Expected behavior
Script runs with no error message and a new model.pt file is generated in the assets folder of the android application. 

## Environment
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0

## Additional context
I am trying to run quantized int8 and fp16 model on a mobile device. Apart from the quantized Mobilenet_v2 model which comes with the PyTorch Mobile Demo, are there other pre-compiled quantized network models available for use on Pytorch Mobile?

cc @fmassa @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by DeleOgunjumelo** [comment]
Also, using qnnpack as it was mentioned in the docs (https://pytorch.org/docs/stable/quantization.html) that quantization currently supports two backends: fbgemm (for use on x86, https://github.com/pytorch/FBGEMM) and qnnpack (for use on the ARM 
QNNPACK library https://github.com/pytorch/QNNPACK). I am also interested in quantizing a model to run on ARM CPU on a mobile device.

**Comment by jianyuh** [comment]
Have you upgraded PyTorch to the latest version. Recently @supriyar added the dynamic linear support with QNNPACK: https://github.com/pytorch/pytorch/pull/32479

**Comment by DeleOgunjumelo** [comment]
I am using PyTorch version 1.4.0 which i think is the latest version. Do you mean using the latest version of the master branch ?

**Comment by jianyuh** [comment]
Right. IIRC, the PR was merged two weeks ago, while PyTorch 1.4.0 was
released last December.

**Comment by DeleOgunjumelo** [comment]
Thanks, I have caught up with the change and I can now create a quantized model. However, i currently have some issues with the demo app when using the new model. Perhaps, i need to also build a new PyTorch android library using the master branch  .https://pytorch.org/mobile/android/#building-pytorch-android-from-source
 
**Current Environment**

Collecting environment information...
PyTorch version: 1.5.0.dev20200206
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.5.0.dev20200206
[pip3] torchvision==0.6.0.dev20200206
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0

**Comment by DeleOgunjumelo** [comment]
This issue has now been resolved.

**Comment by Yeongtae** [comment]
I also had been facing this problem. But currently, it has been solved.
This link may be helpful for you guys in the same situation.
https://github.com/pytorch/pytorch/tree/master/android
