### ISSUE TITLE
Can't use avg_pool2d with the default stride when converting to ONNX

### ISSUE THREAD

**Issue by elliotwaite** [pytorch/pytorch#32954]
## 🐛 Bug

When calling `torch.onnx.export()` with a model that uses `F.avg_pool2d()` without specifying a stride, an error occurs. According to the docs, if the stride is left as `None`, it should by default be set to the kernel size.

## To Reproduce

Run this script:

```
import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
  def forward(self, x):
    x = F.avg_pool2d(x, 2)
    return x


def main():
  model = Model()
  dummy_input = torch.zeros(1, 1, 4, 4)
  torch.onnx.export(model, dummy_input, 'model.onnx', verbose=True)


if __name__ == '__main__':
  main()
```

Here is the output with the error message:
```
graph(%0 : Float(1, 1, 4, 4)):
  %1 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0], value=0.](%0)
  %2 : Float(1, 1, 2, 2) = onnx::AveragePool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=annotate(List[int], [])](%1)
  return (%2)

...

RuntimeError: Attribute 'strides' is expected to have field 'ints'

==> Context: Bad node spec: input: "1" output: "2" name: "AveragePool_1" op_type: "AveragePool" attribute { name: "kernel_shape" ints: 2 ints: 2 type: INTS } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "strides" type: INTS }
```

In contrast to `avg_pool2d`, `max_pool2d` handles the default stride correctly, as demonstrated by running the code below.

```
import torch
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
  def forward(self, x):
    x = F.max_pool2d(x, 2)
    return x


def main():
  model = Model()
  dummy_input = torch.zeros(1, 1, 4, 4)
  torch.onnx.export(model, dummy_input, 'model.onnx', verbose=True)


if __name__ == '__main__':
  main()
```

This will output a graph with the correct `strides=[2, 2]`:
```
graph(%0 : Float(1, 1, 4, 4)):
  %1 : Float(1, 1, 2, 2) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%0)
  return (%1)
```

## Environment

PyTorch version: 1.5.0.dev20200203
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0.dev20200203
[pip] torchvision==0.6.0a0+a5525e9
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] pytorch                   1.5.0.dev20200203         py3.7_0    pytorch-nightly
[conda] torchvision               0.6.0.dev20200203        py37_cpu    pytorch-nightly

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@elliotwaite - could you let us what runtime are you using for evaluating the ONNX model? 
`strides` is an optional field in average pooling op in ONNX. Here's the excerpt from ONNX.
`Stride along each spatial axis. If not present, the stride defaults to 1 along each spatial axis.`

Could this be a runtime issue?

**Comment by elliotwaite** [comment]
I am using ONNX.js to evaluate the model, and it works as you mentioned, using a default stride of 1. However, PyTorch uses the default stride of the kernel size, which is 2 in the example above. So the model runs differently in PyTorch than it does in ONNX when the stride isn't specified.

**Comment by spandantiwari** [comment]
OK, I will take a look.

**Comment by spandantiwari** [comment]
@elliotwaite - yes, this seems to be an issue with the nn.functional average pooling. If you are blocked by this, please use [torch.nn.AvgPool2d](https://pytorch.org/docs/stable/nn.html?highlight=avgpool#torch.nn.AvgPool2d). I have tested that it exports the average pooling node with correct strides.
In the meantime, we will prioritize this higher.

**Comment by elliotwaite** [comment]
Got it. Sounds good.

**Comment by neginraoof** [comment]
The following PR addresses this issue:
https://github.com/pytorch/pytorch/pull/33017

Thanks

**Comment by rakshak-t** [comment]
PR #33017 has been closed, can this issue be closed as well?

**Comment by elliotwaite** [comment]
Yep
