### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by xiaolonghao** [pytorch/pytorch#32967]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by xiaolonghao** [comment]
Can dockerfile only run on ubuntu, and what to do if you want to run on centos？

**Comment by jerryzh168** [comment]
Please post questions in the discussion forum, Thanks!
