### ISSUE TITLE
Can't convert model with torch.triu to ONNX

### ISSUE THREAD

**Issue by bes-dev** [pytorch/pytorch#32968]
Models that contain torch.triu can not be converted to ONNX.

Error message:

> UserWarning: ONNX export failed on ATen operator triu because torch.onnx.symbolic_opset9.triu does not exist

Simple reproducer is here.

```
import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(10, 10, 3, padding=1, bias=False)

    def forward(self, x):
        x = self.conv(x)
        mask = torch.triu(torch.ones_like(x))
        x = x * mask
        return x

model = SimpleModel()
var = torch.ones(1, 10, 120, 120)

torch.onnx.export(
    model,
    (var,),
    "simple_model.onnx",
    input_names=["x"],
    output_names=["out"]
)
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by BelBES** [comment]
As a temporal solution we can use redefined Triu function:

```
class TriuFunc(torch.autograd.Function):
    @staticmethod
    def symbolic(g, x, diagonal):
        return g.op("TriuFunc", x, diagonal_i=diagonal)

    @staticmethod
    def forward(ctx, x, diagonal=0):
        mask = torch.triu(torch.ones_like(x), diagonal)
        ctx.save_for_backward(mask)
        return x * mask

    @staticmethod
    def backward(ctx, grad_output):
        mask, = ctx.saved_tensors
        return grad_output * mask
```

**Comment by spandantiwari** [comment]
@BelBES - yes, torch.triu is not supported in the exporter. Do you need this as part of any specific model?

**Comment by BelBES** [comment]
> @BelBES - yes, torch.triu is not supported in the exporter. Do you need this as part of any specific model?

Yes, this function used for some Transformer networks. Currently, I use a workaround from my previous comment. But I think that torch.triu can be handled as other not supported in ONNX nodes, using op.Aten node.

**Comment by Oktai15** [comment]
@BelBES how it helps to use model in OnnxRuntime? I have the following error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : No Op registered for TriuFunc with domain_version of 10
```

**Comment by BelBES** [comment]
@Oktai15 I'm not sure about onnxruntime (i use other inference engine), but I sure that you can create custom implementation of Triu kernel for onnxruntime (it is really simple function) and use it.

**Comment by robinderat** [comment]
> As a temporary solution we can use re-defined Triu function:
> 
> ```
> class TriuFunc(torch.autograd.Function):
>     @staticmethod
>     def symbolic(g, x, diagonal):
>         return g.op("TriuFunc", x, diagonal_i=diagonal)
> 
>     @staticmethod
>     def forward(ctx, x, diagonal=0):
>         mask = torch.triu(torch.ones_like(x), diagonal)
>         ctx.save_for_backward(mask)
>         return x * mask
> 
>     @staticmethod
>     def backward(ctx, grad_output):
>         mask, = ctx.saved_tensors
>         return grad_output * mask
> ```

@bes-dev 
How does one use the redefined operator to export a pre-trained model like those from huggingface?

**Comment by vatsalsaglani** [comment]
Hey @Oktai15 , I got the same error while converting a Seq2Seq Transformer model, I used the `numpy.triu()` method and then converted it to torch tensor using `torch.from_numpy()`, it worked for me. You can also give it a try.

**Comment by vadimkantorov** [comment]
Also stumbled on this. Current workaround for square matrices and not supporting `diagonal` arg:
```python
 def triu_onnx(x):
     arange = torch.arange(len(x), device = x.device)
     mask = arange.unsqueeze(-1).expand(-1, len(x)) <= arange
     return x * mask
```

`triu` fails fairseq model exports :(

**Comment by tianleiwu** [comment]
Another workaround for triu for ONNX export is like:
```
torch_triu = torch.triu

def triu_onnx(x, diagonal=0, out=None):
    assert out is None
    assert len(x.shape) == 2 and x.size(0) == x.size(1)
    template = torch_triu(torch.ones((1024, 1024), dtype=torch.uint8), diagonal)   #1024 is max seq length
    mask = template[:x.size(0),:x.size(1)]
    return torch.where(mask.bool(), x, torch.zeros_like(x))

torch.triu = triu_onnx
torch.onnx.export(...)   # export your model here
torch.triu = torch_triu
```

**Comment by Konstantina-Lazaridou** [comment]
@tianleiwu thanks for this. I just tried it with exporting the `bart-large-mnli` model, but I got this erros:

``` 
Please note TensorFlow doesn't support exporting model > 2Gb /!\
ModuleNotFoundError: No module named 'keras2onnx'
Exception: Cannot import keras2onnx required to convert TF model to ONNX. Please install keras2onnx first.
```

**Comment by spandantiwari** [comment]
> @tianleiwu thanks for this. I also had the same error and I just tried your proposed workaround with exporting the `bart-large-mnli` (which doesn't support ONNX yet) and `bart-large` model from the `tranformers`, but I got this errors:
> 
> ```
> Please note TensorFlow doesn't support exporting model > 2Gb /!\
> ModuleNotFoundError: No module named 'keras2onnx'
> Exception: Cannot import keras2onnx required to convert TF model to ONNX. Please install keras2onnx first.
> ```

Does this specific error have anything to do with PyTorch or is this a different converter?

**Comment by dashesy** [comment]
@vadimkantorov  thanks! I ended up using this

```python
def triu_onnx(x, diagonal=0):
    l = x.shape[0]
    arange = torch.arange(l, device=x.device)
    mask = arange.expand(l, l)
    arange = arange.unsqueeze(-1)
    if diagonal:
        arange = arange + diagonal
    mask = mask >= arange
    return mask * x
```

It also works in ORT for zero-dim x, as opposed to using `expand(-1, l)` that throws in ORT for zero dimension inputs

**Comment by stas00** [comment]
> @BelBES - yes, torch.triu is not supported in the exporter. Do you need this as part of any specific model?

FWIW, HF `transformers` uses it it in half-dozen models.

**Comment by stas00** [comment]
> As a temporary solution we can use re-defined Triu function:
> 
> ```
> class TriuFunc(torch.autograd.Function):
>     @staticmethod
>     def symbolic(g, x, diagonal):
>         return g.op("TriuFunc", x, diagonal_i=diagonal)
> 
>     @staticmethod
>     def forward(ctx, x, diagonal=0):
>         mask = torch.triu(torch.ones_like(x), diagonal)
>         ctx.save_for_backward(mask)
>         return x * mask
> 
>     @staticmethod
>     def backward(ctx, grad_output):
>         mask, = ctx.saved_tensors
>         return grad_output * mask
> ```

I couldn't figure out how to make it work.

I get on export:
```
E                   RuntimeError: No Op registered for TriuFunc with domain_version of 12
E                   
E                   ==> Context: Bad node spec: input: "214" output: "215" name: "TriuFunc_122" op_type: "TriuFunc" attribute { name: "diagonal" i: 1 type: INT }
```

I'm new to ONNX - any pointers at how to make your proposal work, @bes-dev 
p.s. I also had to modify `return x * mask` to `return x.masked_fill(mask==0, 0)` as the former was not handling `-inf` and giving me `nan` instead of 0.

**Comment by stas00** [comment]
I ended up with adjusting @dashesy's version to handle `-inf` in x:
```
def triu_onnx(x, diagonal=0):
    l = x.shape[0]
    arange = torch.arange(l, device=x.device)
    mask = arange.expand(l, l)
    arange = arange.unsqueeze(-1)
    if diagonal:
        arange = arange + diagonal
    mask = mask >= arange
    return x.masked_fill(mask==0, 0)
```

**Comment by mathmax12** [comment]
@stas00 
Could you detail how you achieved that?
I am facing the same issue and here is my code
`print("----> Making the model: :", onnx_file_name)
        # net = net.cpu()

        torch_triu = torch.triu
        def triu_onnx(x, diagonal=0):
            l = x.shape[0]
            arange = torch.arange(l, device=x.device)
            mask = arange.expand(l, l)
            arange = arange.unsqueeze(-1)
            if diagonal:
                arange = arange + diagonal
            mask = mask >= arange
            return x.masked_fill(mask==0, 0)

        torch.triu = triu_onnx

        torch.onnx.export(net,
                        args=preprocessed,
                        f=onnx_file_name,
                        opset_version=11)
        torch.triu = torch_triu`

But I still got the 
`RuntimeError: Exporting the operator triu to ONNX opset version`
Thanks.

**Comment by stas00** [comment]
I haven't tried overriding `torch.triu`, but used it directly:

https://github.com/huggingface/transformers/blob/95dab34d5588fb155dfed8293ac2fbb1217a95a7/src/transformers/models/fsmt/modeling_fsmt.py#L323

Perhaps check that it's actually overridden at the point of use? Your `net` has already "closured" on the real `torch.triu` by this time if it makes sense. You want to override it before you create `net`.

**Comment by mathmax12** [comment]
Thanks. 
For my case I can't find the source code part using triu. It's called by the pytorch
` File "C:\Users\Segmentation\lib\site-packages\torch\onnx\utils.py", line 931, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "C:\Users\Segmentation\lib\site-packages\torch\onnx\symbolic_registry.py", line 116, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator triu to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

I also tried to put it before the creation of the net
```
     torch_triu = torch.triu
    def triu_onnx(x, diagonal=0):
        l = x.shape[0]
        arange = torch.arange(l, device=x.device)
        mask = arange.expand(l, l)
        arange = arange.unsqueeze(-1)
        if diagonal:
            arange = arange + diagonal
        mask = mask >= arange
        return x.masked_fill(mask == 0, 0)

    torch.triu = triu_onnx
   
    with torch.no_grad():
           net = Segmentation_network()
           net.eval()
           
           input_tensor = np.zeros((550, 550,3), np.float32)
           preprocessed = FastBaseTransform()(input_tensor.unsqueeze(0)).cuda()
           torch.onnx.export(net,
                        args=preprocessed,
                        f=onnx_file_name,
                        # operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
                        opset_version=11) 
```
@tianleiwu @dashesy  Any suggestion will be appreciated.

**Comment by tianleiwu** [comment]
@maximsch2
Below is an example script that works in pytorch 1.8.0
```
import torch
import torch.nn as nn

class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        mask = torch.triu(torch.ones_like(x))
        return x * mask

def triu_onnx(x, diagonal=0):
    l = x.shape[0]
    arange = torch.arange(l, device=x.device)
    mask = arange.expand(l, l)
    arange = arange.unsqueeze(-1)
    if diagonal:
        arange = arange + diagonal
    mask = mask >= arange
    return x.masked_fill(mask == 0, 0)
    
def register_custom_op():
    def triu(g, self, diagonal):
        return g.op("com.microsoft::Trilu", self, diagonal, upper_i=1)
    torch.onnx.register_custom_op_symbolic('::triu', triu, 1)
    
use_onnxruntime = False
if use_onnxruntime:
    register_custom_op() # ONNX Runtime CPU execution provider supports custom op Trilu (similar to Trilu in onnx opset version 14).
else:
    torch.triu = triu_onnx 

model = SimpleModel()
input = torch.ones(10, 10)

torch.onnx.export(
    model,
    (input,),
    "simple_model.onnx",
    input_names=["x"],
    output_names=["out"],
    opset_version=11,
    custom_opsets={'com.microsoft': 1}  if use_onnxruntime else {}
)
```
You can set a break point in triu_onnx function in debugger to find out whether it is used in your code.

**Comment by mathmax12** [comment]
@tianleiwu 
Thank you very much for sharing.
Yes, this works for me.

**Comment by spandantiwari** [comment]
Keeping this as the main issue for tracking `triu` support work. 

We have just added a new op in ONNX called trilu in opset 14 which will be included in the latest release. Once it is available we will add support for it as we enable Opset 14.

**Comment by genolve** [comment]
**Both triu and tril seem to want a constant for the diagonal parameter but this is often a variable.**
For huggingface transformerxl, at code line:

> dec_attn_mask = (torch.triu(all_ones, diagonal=1 + mlen) + torch.tril(all_ones, -mask_shift_len))[:, :, None] 

On ONNX Export with opset 14, I'm getting this error:

> ....
> File "/home/craig/envcond/transformers/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 166, in <listcomp>
>     args = [_parse_arg(arg, arg_desc, arg_name, fn_name)  # type: ignore[assignment]
>   File "/home/craig/envcond/transformers/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 93, in _parse_arg
>     raise RuntimeError("Expected node type 'onnx::Constant' "
> **RuntimeError: Expected node type 'onnx::Constant' for argument 'diagonal' of node 'triu', got 'onnx::Add'.**

Pytorch: 1.11.0.dev20211124+cu113
onnx:     1.10.2
onnxconverter-common:   1.8.1
onnxruntime    1.9.0

Furthermore, if I remove the variable **mlen** and set a constant (e.g diagonal=1), the previous error goes away. I still get another error but looks like it is from ORT:

>....
> File "/home/craig/envcond/transformers/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 378, in _create_inference_session
> sess.initialize_session(providers, provider_options, disabled_optimizers)
> onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : **Could not find an implementation for Trilu(14) node with name 'Trilu_64'**
