### ISSUE TITLE
Difference behavior between torch's Tensor and torch.cuda's Tensor

### ISSUE THREAD

**Issue by yasufumy** [pytorch/pytorch#3297]
I'm using `0.2.0` version of pytorch and I found this.
```py
x = torch.LongTensor([0, 0, 0, 0, 0])
x.topk(1)  # (0, 4)
x = x.cuda()
x.topk(1)  # (0, 0) 
```
also
```py
x = torch.ByteTensor([0, 0, 0, 0, 0])
x.max(0)  # (0, 0)
x = x.cuda()
x.max(0)  # (0, 1) 
```
Is this expected or not?

**Comment by apaszke** [comment]
Yes, it's possible. CUDA and CPU algorithms differ. This has been reported multiple times and we don't plan to always unify them, because it would decrease CUDA perf dramatically. All outputs you posted are valid in this case.

**Comment by fmassa** [comment]
@apaszke we should probably mention that in the docs, for each operation that has different behavior in corner cases. What do you think?

**Comment by apaszke** [comment]
I'm not sure. The results could potentially be different even on a single device if they might depend on e.g. the order of atomic adds or swaps. They are all valid outputs. We could put a sentence mentioning this somewhere in the docs, but I don't think adding notes to each function will help a lot

**Comment by fmassa** [comment]
So maybe a general note in the docs mentioning the differences between CPU and GPU computations, and that results might be slightly different due to floating point arithmetics (non-associativity for example) or differences in algorithmic implementation?
Maybe in http://pytorch.org/docs/master/notes/cuda.html ?

**Comment by apaszke** [comment]
Yes, that sounds good
