### ISSUE TITLE
Issue with transformer.compose ( )

### ISSUE THREAD

**Issue by wanifarooq** [pytorch/pytorch#32971]
When I was trying  to load 16 bit .png grayscale image with torchvision.datasets.imagefolder ,it is loading every image as white only. 
I solved this issue by doing transformation operations outside Compose function.

cc @SsnL

**Comment by choidongyeon** [comment]
Hi, I'd like to work on this issue. Can anyone help me get started?

**Comment by wanifarooq** [comment]
You can create dummy dataset of 16-bit grayscale images and try to load it using compose function .By default the compose function is loading only first 8-bits of every pixel and therefore all images are becoming white as the intensities of each pixel is becoming 255

**Comment by SsnL** [comment]
Could you open the issue in the torchvision repo instead https://github.com/pytorch/vision/ ? Thanks!

**Comment by SsnL** [comment]
I created one at https://github.com/pytorch/vision/issues/2218. Let me know if it is inaccurate.
