### ISSUE TITLE
[jit] augmented assignment on int attributes doesn't work

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#32973]
## 🚀 Feature

It'd be nice of TorchScript could support assigning to fields with simple Python types (e.g. non-tensors). For example:

```python
import torch
import torch.nn as nn

class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.x: int = 0    # int field
    def forward(self):
        self.x += 1       # fails to script
        return self.x
```

## Motivation

I'm writing a real-time streaming wrapper around some of PyTorch's modules so that they an run online, sample-by-sample. For convolutions, this requires some bookkeeping to buffer up the receptive field that requires incrementing and decrementing various counters, which would be nice to support natively in Torchscript.

## Alternatives

Currently, we're working around this by using 0d "scalar" tensors (e.g. `torch.tensor(0)`). This works, but it's not really ideal (it requires verbose `dtype` annotations, it means that these counters could be moved to the GPU unnecessarily, it's requires some amount of boilerplate).

## Additional context

cc @suo

**Comment by suo** [comment]
We support this, but augmented assignment is not implemented for non-tensor fields. So the following will work:
```
import torch
import torch.nn as nn

class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.x: int = 0    # int field
    def forward(self):
        self.x = self.x + 1  # not +=
        return self.x
```
This is an unintentional gap that we'll fix in a future release, cc @driazati for tracking.
