### ISSUE TITLE
[JIT] Trace only one class method while keeping the others

### ISSUE THREAD

**Issue by Rikorose** [pytorch/pytorch#32975]
## 🚀 Feature

I have a module, where only for some parts the input shape is known at compile/trace time.

A simplified module for illustration
```py
class MyRNN(nn.Module):
    def forward_parallel_part(self, input: Tensor) -> Tensor:
        # input has a time dimension that is not known at trace time
        return input

    def forward_recurrent_part(
        self, input: Tensor, h: Tensor
    ) -> Tuple[Tensor, Tensor]:
        out = input * h
        return out, h

    def forward(self, input: Tensor, h: Tensor) -> Tensor:
        out_p = self.forward_parallel_part(input)
        for t in out_p.shape[0]
            h = self.forward_recurrent_part(out_p[t], h)
        return h
```

I only want to trace the recurrent part and use jit for the parallel part, since the time dimension is not known at compile time.

```py
rnn_recurr_in = {"forward_recurrent_part": (torch.empty(2, 5), torch.empty(2, 5))}
rnn = torch.jit.trace_module(MyRNN(), rnn_recurr_in)  # rnn has no methods 'forward' or 'forward_parallel_part'
# Now I want to use torch.jit.script to compile a graph for the forward/forward_parallel_part methods
rnn = torch.jit.script(rnn)  # This fails with the message: RuntimeError: 'Module' has no attribute 'forward_parallel_part'
```

A Workaround could be to create 2 separate modules and only trace one of them. In my case this could work, however if we want to share weights, this might get difficult.

cc @suo

**Comment by suo** [comment]
Yes, the canonical way of doing this is probably separating out the traced code into a different module and tracing that one directly. Then as long as you attach it as a submodule in `__init__`, you can script the whole model.

Parameter sharing should work in this instance, but feel free to open a separate issue if it doesn't.
