### ISSUE TITLE
PyTorch should hide CUDNN symbols in libtorch.so

### ISSUE THREAD

**Issue by nvpohanh** [pytorch/pytorch#32983]
## 🐛 Bug

PyTorch's `libtorch.so` exposes a lot of CUDNN API symbols. This causes issues when our application (independent from PyTorch) uses a different CUDNN version.

## To Reproduce

Install PyTorch 1.4.0. Run `nm` on the `libtorch.so`, and there will be a lot of CUDNN API symbols.

```
nvpohanh@ubuntu:~$ nm /usr/local/lib/python3.5/dist-packages/torch/lib/libtorch.so | grep ' cudnnCreate'
000000000f479c30 T cudnnCreate
000000000f475ff0 T cudnnCreateActivationDescriptor
000000000f4747e0 T cudnnCreateAlgorithmDescriptor
000000000f474930 T cudnnCreateAlgorithmPerformance
000000000f473e90 T cudnnCreateConvolutionDescriptor
000000000f621a10 T cudnnCreateCTCLossDescriptor
000000000fc8cb50 T cudnnCreateDropoutDescriptor
000000000f47b3c0 T cudnnCreateFilterDescriptor
000000000f476460 T cudnnCreateLRNDescriptor
000000000f4752d0 T cudnnCreateOpTensorDescriptor
000000000fbe5520 T cudnnCreatePersistentRNNPlan
000000000f476af0 T cudnnCreatePoolingDescriptor
000000000f474f00 T cudnnCreateReduceTensorDescriptor
000000000fbe4f90 T cudnnCreateRNNDataDescriptor
000000000fbe3880 T cudnnCreateRNNDescriptor
000000000f475450 T cudnnCreateSpatialTransformerDescriptor
000000000f47aca0 T cudnnCreateTensorDescriptor
000000000f47cde0 T cudnnCreateTensorTransformDescriptor
```

## Expected behavior

PyTorch should hide CUDNN symbols in libtorch.so

## Environment

```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.13.3

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: TITAN RTX
Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.2.1
[conda] Could not collect
```

## Additional context

cc @csarofeen @ptrblck

**Comment by pranavm-nvidia** [comment]
We are running into the same issue - when torch is imported, cuDNN calls from our application are redirected to `libtorch.so` (we looked at a backtrace from `gdb` to confirm this).

**Comment by zeroepoch** [comment]
Any update on this bug?

**Comment by rmccorm4** [comment]
Seeing an issue probably related to this one when importing torch with other GPU-accelerated packages as mentioned above: https://github.com/NVIDIA/TensorRT/issues/317#issuecomment-613716637

**Comment by mcarilli** [comment]
To get more information about what's actually happening, does LD_PRELOAD help?
```
$ LD_PRELOAD=/path/to/preferred/libcudnn.so python script.py
```
?

**Comment by pranavm-nvidia** [comment]
Yes, with LD_PRELOAD it loads the correct cuDNN library, and my application runs without error. 
Without this, I get several cuDNN errors (and in this case, as mentioned before, `gdb` says the functions are in `libtorch.so`)

**Comment by mcarilli** [comment]
> with LD_PRELOAD it loads the correct cuDNN library

Does "it" here mean 
1. Your application
2. The Pytorch internal cudnn calls
3. Both

?  I expect 1, `libtorch.so`'s statically linked internal calls should not be affected by `LD_PRELOAD`.

Do you want Torch-internal calls to use your external cudnn version as well, or do you want the torch-internal calls to continue using `libtorch.so`'s statically linked internal cudnn definitions, while your application uses your external cudnn?

**Comment by pranavm-nvidia** [comment]
Sorry, "it" was referring to my application. 

I just need to make sure my application is using the right cuDNN library; I'm fine with PyTorch using whatever it needs to (presumably what it statically links). 

I think the only thing that needs to be done in PyTorch to fix the issue I see is to hide the cuDNN symbols, either [during linking](https://accu.org/index.php/journals/1372), or afterwards, with something like `strip`

**Comment by mcarilli** [comment]
Pytorch already has [visibility control](https://github.com/pytorch/pytorch/blob/master/c10/macros/Export.h) for the functions it defines internally (and therefore probably compiles with `-fvisibility` although I'm not 100% sure of that for the binary builds).  Do you know if we expect compiling `libtorch.so` with `-fvisibility` to hide symbols for externally defined functions, ie, the symbols for the definitions that statically linking against cudnn pulls in?

**Comment by pranavm-nvidia** [comment]
I'm not sure if that's a reliable way to hide symbols from an external, statically linked library. For example, cuDNN might be using visibility attributes, and if you just use `-fvisibility`, I'd imagine that they would be visible in the final library (and they are, as we can see from inspection). 

In fact, it seems that the [linker doesn't impose visibility constraints on static archives](https://stackoverflow.com/a/2251477), so I guess it wouldn't work even if cuDNN doesn't use visibility specifiers.

However, it looks like there's a linker option that can fix this, which might be a lot easier than the solutions I suggested earlier: [-Wl,--exclude-libs](https://sourceware.org/binutils/docs/ld/Options.html)

**Comment by mcarilli** [comment]
After playing with minimal working samples, `-Wl,--exclude-libs,libdummy.a` works to hide symbols statically linked from libdummy.a, even if libdummy.a was compiled with default visibility.

Another working solution is applying pragmas to declarations for symbols you want to hide in consumer (ie Pytorch) cpp files:
```C++
#pragma GCC visibility push(hidden)
#include "cudnn_whatever.h"
#pragma visibility pop
```
Then, even if cudnn is statically linked, and even if the cudnn static library was compiled with default visibility, the resulting `libtorch_whatever.so` should hide the cudnn symbols.  See [here](https://gcc.gnu.org/wiki/Visibility), ctrl+f
>#pragma GCC visibility is stronger than -fvisibility; it affects extern declarations as well.

**Comment by pranavm-nvidia** [comment]
I don't think cuDNN defines any exceptions, but assuming it did, would PyTorch propagate those (or any other cuDNN types) across its own library boundary? Wouldn't they be caught and handled internally?

If you need more fine-grained control (I don't think you do for cuDNN), a [linker exports map](https://accu.org/index.php/journals/1372) might be the easiest way

**Comment by mcarilli** [comment]
I don't know enough about the build system to decide the right approach here.  I'll ping devs on pytorch slack.

**Comment by soumith** [comment]
`-Wl,exclude-libs` is a reasonable and easy fix, we should do it.

Presumably, has to be inserted here: https://github.com/pytorch/pytorch/blob/6e4f99b0633f704f8c7bf3bb3b9733680f5dc18b/cmake/public/cuda.cmake#L256-L271

follow along `USE_STATIC_CUDNN=1`
