### ISSUE TITLE
Why should pad be smaller than half of kernel size in MaxPool2

### ISSUE THREAD

**Issue by yueruchen** [pytorch/pytorch#3298]
If I run:
```
torch.nn.MaxPool2d(4,stride=4,padding=3)(Variable(torch.rand(1,1,20,20)))
```
it turns out:

RuntimeError: invalid argument 2: pad should be smaller than half of kernel size, but got padW = 3, padH = 3, kW = 4, kH = 4 at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/THNN/generic/SpatialDilatedMaxPooling.c:35

Do I have any choice to avoid it?

**Comment by apaszke** [comment]
You can use `torch.nn.functional.pad` before you do the pooling

**Comment by fmassa** [comment]
@yueruchen  The reason IIRC is that the starting values of the MaxPool is `-inf`, and if your padding were to be too large, you would have `-inf` values in the boundaries, which is probably not what you want.

**Comment by acschaefer** [comment]
I ran into the same issue, and I do not get the reason why pytorch throws an error. Is the purpose to protect the user from himself? 

Actually, this is not a runtime error - it could be a warning. As such, it could also be ignored or suppressed. 

Could you please change the behavior to throw a warning instead of an error?

**Comment by soumith** [comment]
it's a limitation of the implementation

**Comment by hyperfraise** [comment]
I agree it shuld be at least half of `kernel_size * dilation`

**Comment by richard-vogl** [comment]
@hyperfraise is completely correct, the correct implementation for a padding limit should be 
`kernel_size * dilation / 2`
not `kernel_size / 2`

can we reopen this issue, or should we create a new one? @soumith ?

**Comment by xingyuuchen** [comment]
> The limit should be half of `kernel_size * dilation`

can't agree more, but this issue seems still exists in Pytorch...

**Comment by ElvenMonky** [comment]
@soumith Would you consider reopening, because clearly current implementation does not account for dilation.
