### ISSUE TITLE
torch.nonzero issues a DeprecationWarning for non-deprecated usages

### ISSUE THREAD

**Issue by ngoldbaum** [pytorch/pytorch#32994]
## 🐛 Bug

Afaics any usage of `torch.nonzero` is producing a deprecation warning

## To Reproduce

```
In [1]: import torch

In [2]: t = torch.arange(2)

In [3]: torch.nonzero(t)
../torch/csrc/utils/python_arg_parser.cpp:738: UserWarning: This overload of nonzero is deprecated:
        nonzero(Tensor input, Tensor out)
Consider using one of the following signatures instead:
        nonzero(Tensor input, bool as_tuple)
Out[3]: tensor([[1]])
```

## Expected behavior

No deprecation warning

## Environment

```
PyTorch version: 1.5.0a0+d2098bd
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.16.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.5.0a0+d2098bd
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] torch                     1.5.0a0+d2098bd           dev_0    <develop>
```

cc @albanD @mruberry

**Comment by jinfagang** [comment]
So doest anyone follow this up? Old code all get this error after upgrade to torch1.5

**Comment by jinfagang** [comment]
*warning

**Comment by xkszltl** [comment]
Also having this issue for a while.

@jerryzh168 
Seems this is not a logging issue, but due to bad function signature:
https://github.com/pytorch/pytorch/blob/c9a1fc2b31ded472c63b227ad24859bc14131f42/tools/autograd/templates/python_torch_functions.cpp#L567
`as_tuple` has default value `False` but not listed here, causing parser to treat is as `out=None`.

**Comment by mshuaibii** [comment]
Just upgraded to 1.5 and also getting this issue

**Comment by apiszcz** [comment]
same issue here with 1.5

**Comment by bakhsanzh** [comment]
Just installed torch 1.5 and having similar issue.
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated: nonzero(Tensor input, *, Tensor out)

**Comment by sizhky** [comment]
Use `torch.nonzero(x, as_tuple=True)` to get back a tuple of ix,jx,kx... (much like numpy.nonzero) or `torch.nonzero(x, as_tuple=False)` to get back a torch tensor...

**Comment by sykimm** [comment]
Same issue with 1.5

**Comment by liuqidong07** [comment]
> 
> 
> Use `torch.nonzero(x, as_tuple=True)` to get back a tuple of ix,jx,kx... (much like numpy.nonzero) or `torch.nonzero(x, as_tuple=False)` to get back a torch tensor...

Thanks a lot! Your solution works and the warning diappears.

**Comment by wmpauli** [comment]
I'm also getting this warning, in version 1.6.0, even if i follow above suggestion and use `torch.nonzero(<the_good_tensor>, as_tuple=False)`

**Comment by lamhoangtung** [comment]
I'm also having this issue

**Comment by hiyyg** [comment]
Same here

**Comment by nguyendong07** [comment]
> > Use `torch.nonzero(x, as_tuple=True)` to get back a tuple of ix,jx,kx... (much like numpy.nonzero) or `torch.nonzero(x, as_tuple=False)` to get back a torch tensor...
> 
> @sizhky Thanks a lot! Your solution works and the warning diappears.

>@dongnv which location file i can  fix it?

**Comment by Jomonsugi** [comment]
After running into this [issue](https://github.com/pytorch/pytorch/issues/38718) when using the argument `as_tuple` and converting to torchscript, I reverted to not using the argument as follows (nevermind that the code is nonsensical, it's just to show an example):

```
t=torch.randint(1,10,(10,3))
t_nonzero = torch.nonzero(F.pad(t,(0,10)))
as_tuple  = t[(t_nonzero[:,0], t_nonzero[:,1])]
```
where I would have wanted to do something like the following to get away from the warning:
```
t=torch.randint(1,10,(10,3))
as_tuple = t[torch.nonzero(F.pad(t,(0,10)), as_tuple=True)]
```

So in this case I can't use `as_tuple` if I want to convert to torchscript and I if I don't use `as_tuple` I see this warning.

**Comment by chiboreache** [comment]
1.7 - we are still open -_-

**Comment by zetayue** [comment]
Found a solution by replacing nonzero with `where`:
https://github.com/pytorch/vision/pull/2705
https://github.com/pytorch/vision/pull/2705/files

**Comment by ysl208** [comment]
Hi, I'm still getting the error even though I have that solution posted by @zetayue already. Anyone can help?

**Comment by mruberry** [comment]
We are implementing a fix now.

You can use the function version of nonzero: torch.nonzero(), for now.

**Comment by ysl208** [comment]
I'm getting the error below, which seems to be pointing at a line which uses `nonzero()` without any arguments.

```
UserWarning: This overload of nonzero is deprecated:
	nonzero()

Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/utils/python_arg_parser.cpp:882.)
```
So I'm not sure what to replace exactly. Could you elaborate?

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/51618 should have fixed this!

**Comment by mruberry** [comment]
> I'm getting the error below, which seems to be pointing at a line which uses `nonzero()` without any arguments.
> 
> ```
> UserWarning: This overload of nonzero is deprecated:
> 	nonzero()
> 
> Consider using one of the following signatures instead:
> 	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/utils/python_arg_parser.cpp:882.)
> ```
> 
> So I'm not sure what to replace exactly. Could you elaborate?
> 
> Edit: I found the solution [here](https://github.com/facebookresearch/detectron2/pull/1974)

Glad you found a solution, and this issue should be fixed now, but previously you could do:

```
torch.nonzero(t)
```

without complaint, but 

```
t.nonzero()
```

would complain.

**Comment by mruberry** [comment]
> torch.**version**
> '1.7.1'
> t = torch.arange(2)
> t.nonzero()

On Colab this is working for me with PyTorch 1.9. Would you try with a later version of PyTorch?
