### ISSUE TITLE
Segfault on typecasting of Tensor that lives on GPU

### ISSUE THREAD

**Issue by EltayebAhmed** [pytorch/pytorch#32995]
## 🐛 Bug

Typecasting a `torch.FloatTensor` called `x` that lives on a GPU to a `torch.ByteTensor` in-place using `x = torch.ByteTensor(x)` caused a segfault

## To Reproduce

Run following code snippet:
```
import torch
x = torch.zeros(64, 64).cuda()
x = torch.ByteTensor(x)
print("Hello world")
```

## Expected behavior
For the code to print `"Hello World"`

## Actual Behaviour
Output of code is
`Segmentation fault (core dumped)`

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.0
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.15           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

-----
I know my cudatoolkit version is 10.0
## Additional context

I don't think the bug is specific to `torch.ByteTensor`, over the past few weeks my code has been plagued by various segfaults when converting to different types

**Comment by Enealor** [comment]
I think the issue you are encountering is related to how you are trying to cast. `torch.ByteTensor` is a class, and its constructor is not designed for casting. To cast, try `x.to(dtype=torch.uint8)`. This is discussed further on [this page](https://pytorch.org/docs/stable/tensors.html#torch-tensor) of the docs - the third note down mentions using `to`.

**Comment by mrshenli** [comment]
I am closing this issue as @Enealor has answered it. 

@EltayebAhmed please feel free to re-open it if the suggested solution does not work for you.
