### ISSUE TITLE
random_pruning, remove_pruning typo

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#32991]
## 📚 Documentation

documentation includes use of random_pruning, but there is nothing like random_pruning.
```
m = random_pruning(nn.Linear(5, 7), name='weight', amount=0.2)
prune.random_pruning(m, name='weight', amount=0.2)
```
AttributeError: module 'torch.nn.utils.prune' has no attribute 'random_pruning'

same thing for remove_pruning also,
```
>>> m = remove_pruning(m, name='weight')
```
AttributeError: module 'torch.nn.utils.prune' has no attribute 'remove_pruning'

**Comment by jerryzh168** [comment]
Looks like it's been updated to `random_structured`, `random_unstructured` and `remove`. yeah we need to update the docs, thanks for reporting

**Comment by jerryzh168** [comment]
cc @mickypaganini could you take a look?

**Comment by albanD** [comment]
Corresponding PR has been merged.
