### ISSUE TITLE
Can I use the multi GPU training model in windows?

### ISSUE THREAD

**Issue by huang229** [pytorch/pytorch#33005]
Can I use the multi GPU training model in windows?Thank you very much.

**Comment by mrshenli** [comment]
If you are looking for `torch.distributed` package or `DistributedDataParallel`, then no, they are not available yet on Windows. But you can still use `DataParallel` to do single-machine multi-GPU training on windows. Closing this issue, and let's move questions to the [forum](https://discuss.pytorch.org/).

**Comment by anas-zafar** [comment]
@mrshenli is it available now?
