### ISSUE TITLE
CuDNN backend not available in nightly (20200205)

### ISSUE THREAD

**Issue by Evpok** [pytorch/pytorch#33016]
## 🐛 Bug

CuDNN works fine if I use 1.4.0, but it is not found in nightly, see a few checks below

```python
>>> torch.version.git_version
'1c420dd12b190e716be0f3e031254adcfc2a8a05'
>>> torch.cuda.is_available()
True
>>> torch._C._get_cudnn_enabled()
True
>>> torch._C.has_cudnn
True
>>> torch.backends.cudnn.version() is None
True
```

## Environment

```
PyTorch version: 1.5.0.dev20200205
Is debug build: No          
CUDA used to build PyTorch: 10.1     
                                         
OS: Debian GNU/Linux bullseye/sid
GCC version: (Debian 9.2.1-25) 9.2.1 20200123
CMake version: version 3.15.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-9.1/lib64/libcudnn.so.7.1.3

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] numpydoc==0.9.2
[pip3] pytorch-ignite==0.2.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.5.0.dev20200205
[conda] Could not collect
```

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Repros for me

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch._C._get_cudnn_enabled()
True
>>> torch.version.git_version
'1c420dd12b190e716be0f3e031254adcfc2a8a05'
>>> torch.backends.cudnn.version()
```

**Comment by ezyang** [comment]
However, it seems that the actual cudnn algorithms are working, so it's just a problem reporting the cudnn version.

```
import torch
print(torch.cudnn_convolution(torch.zeros(1,4,5,5).cuda(), torch.zeros(8,4,3,3).cuda(), (0,0), (1,1), (1,1), 1, False, False))
```

**Comment by Evpok** [comment]
The convolution example works for me too, but this

```python
torch.nn.LSTM(5, 5).cuda()(torch.randn(5,5,5, device="cuda"))
```

gives a warning

```
[REDACTED]/torch/backends/cudnn/__init__.py:113: UserWarning: cuDNN library not found. Check your LD_LIBRARY_PATH}.get(sys.platform, 'LD_LIBRARY_PATH'))
```

Is there a way to see if it is actually using cudnn?

**Comment by ezyang** [comment]
Yeah, just `nvprof` the execution and see if it actually used a cudnn kernel. So I get:

```
==47145== Profiling application: python test.py                                                            
==47145== Profiling result:  
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name                          
 GPU activities:   38.25%  50.303us        25  2.0120us  1.0240us  3.2640us  [CUDA memcpy DtoH]            
                   15.47%  20.351us         1  20.351us  20.351us  20.351us  void cudnn::detail::explicit_c
onvolve_sgemm<float, int, int=1024, int=5, int=5, int=3, int=3, int=3, int=0, bool=1>(int, int, int, float 
const *, int, float const , int, cudnn::detail::explicit_convolve_sgemm<float, int, int=1024, int=5, int=5,
 int=3, int=3, int=3, int=0, bool=1>*, kernel_conv_params, int, int, float, float, int, float const *, floa
t const *)
               ```

On the convolution one

**Comment by ezyang** [comment]
Hmm, I do get your warning too, but nvprof seems to claim that we are getting to the cudnn kernel in the end:

```
==47400== NVPROF is profiling process 47400, command: python test.py
/scratch/ezyang/miniconda3/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py:113: UserWarning: c
uDNN library not found. Check your LD_LIBRARY_PATH
  }.get(sys.platform, 'LD_LIBRARY_PATH')))
==47400== Warning: Profiling results might be incorrect with current version of nvcc compiler used to compi
le cuda app. Compile with nvcc compiler 9.0 or later version to get correct profiling results. Ignore this
warning if code is already compiled with the recommended nvcc version
/opt/conda/conda-bld/pytorch_1580890734253/work/aten/src/ATen/native/cudnn/RNN.cpp:1262: UserWarning: RNN m
odule weights are not part of single contiguous chunk of memory. This means they need to be compacted at ev
ery call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
==47400== Profiling application: python test.py
==47400== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   23.86%  24.128us         5  4.8250us  3.8720us  8.3520us  void gemmSN_NN_kernel<float, i
nt=128, int=2, int=4, int=8, int=5, int=4, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorSt
ridedBatched<float>>(cublasGemmSmallNParams<float const , cublasGemvTensorStridedBatched<float const >, flo
at>)
                   17.37%  17.567us         5  3.5130us  2.6880us  6.4640us  void LSTM_elementWise_fp<float
, float, float, cudnnRNNBiasMode_t=2>(int, int, int, int, float const *, float const *, float const *, floa
t const *, cudnn::reduced_divisor, float*, float*, float*, float const *, float*, bool, int, cudnnRNNClipMo
de_t, cudnnNanPropagation_t, float, float)
                   12.82%  12.960us         1  12.960us  12.960us  12.960us  sgemm_32x32x32_NN
```

**Comment by ezyang** [comment]
Bumping up the priority because the warning is scary looking (even though everything is actually working under the hood)

**Comment by ngoldbaum** [comment]
Are the build script that generate the nightly conda builds public somewhere? It looks like only the conda builds are affected, if I build pytorch from source I get a sensible answer from `torch.backends.cudnn.version()`, but I am able to reproduce using the nightly conda builds.

**Comment by ezyang** [comment]
conda nightly stuff lives at https://github.com/pytorch/builder/tree/master/conda the best way to see how it works is to read the CI scripts to see what scripts are run. @seemethere should also be able to answer questions

**Comment by peterbell10** [comment]
Okay, so `backends.cudnn` uses a dynamic library call to get the `cuDNN` version. 
https://github.com/pytorch/pytorch/blob/d7f00b1b45b5a783a4877b8dc22400f50de90bf0/torch/backends/cudnn/__init__.py#L56
You can check that the `.so` was loaded successfully by looking at the value of `lib`:
```python
import torch
torch.backends.cudnn.lib is None
```
I get `True` on nightly but `False` for a local build. Also note that on \*nix this doesn't actually load cudnn specifically, it just inspects all global symbols using `LoadLibrary(None)`.

Since #31162, the only globally exported symbols come from `libtorch_global_deps.so`. Using `objdump -p`, I can see that the version included in nightly builds doesn't load `cudnn` but my local dev build does. That makes sense: the nightly builds static link cudnn, so `libtorch_global_deps.so` isn't linked against the dynamic library either.

So, why did it work before? If I build an old version of `libtorch` with static cudnn, `cudnnGetVersion` is exported from `torch_cuda.so` so the version check succeeds.

**Comment by peterbell10** [comment]
Fixing the version check should be trivial, we can just move it into `torch._C` and use whatever version of cudnn is linked. However, `lib` is a publicly accessible symbol so not having it available would be a BC-breaking change.

**Comment by peterbell10** [comment]
Okay, It's more complicated than just the version check. `cudnn.lib` is used for all the bindings in `cudnn/__init__.py`:
```python
In [2]: torch.backends.cudnn.CuDNNHandle()                                                    
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2d1e16287869> in <module>
----> 1 torch.backends.cudnn.CuDNNHandle()

~/miniconda3/envs/pytorch-dev/lib/python3.7/site-packages/torch/backends/cudnn/__init__.py in __init__(self)
    172     def __init__(self):
    173         ptr = ctypes.c_void_p()
--> 174         check_error(lib.cudnnCreate(ctypes.byref(ptr)))
    175         self._as_parameter_ = ptr
    176 

AttributeError: 'NoneType' object has no attribute 'cudnnCreate'

```

**Comment by peterbell10** [comment]
How about instead of statically linking cudnn, we just distribute the `.so`?

**Comment by peterbell10** [comment]
Or actually, the cudnn bindings don't seem to actually be used anywhere in `torch`. I guess this was all moved into `ATen` but the implementation details were left in place.

@ezyang Is `torch.backends` considered a public API? It doesn't seem to be in the [documentation](https://pytorch.org/docs/stable/index.html) and if not then this becomes much more straightforward.

**Comment by ezyang** [comment]
Ooooh, this is kind of my fault. In @apaszke's original patch #28536 for removing RTLD_GLOBAL he moved all of the cudnn backends logic inside _C, but it turned out we need to load the cudnn dynamic library anyway for users who manually load it (like here!) I think we should probably revive this part of Adam's patch, maybe something like https://github.com/pytorch/pytorch/pull/31160 but this PR failed in an exciting and hard to debug way last time I tried it, so it might be better to just do it all from scratch.

**Comment by ezyang** [comment]
And yes, backends is public API, so we need to preserve its functionality.

> How about instead of statically linking cudnn, we just distribute the .so?

I'm pretty sure we have a good reason for it but only @soumith  or @seemethere will know.

**Comment by soumith** [comment]
> How about instead of statically linking cudnn, we just distribute the .so?

That adds an extra 150MB or so, and will be a no-go for binary packaging.
With static CuDNN, we strip CuDNN of all GPU architectures except the ones we want to support, and that saves this ridiculous amount of space.
