### ISSUE TITLE
Is it possible to not generate so much code at compiling phase(arch)?

### ISSUE THREAD

**Issue by zzz6519003** [pytorch/pytorch#33031]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mrshenli** [comment]
Closing this issue. Please post questions to the [forum](https://discuss.pytorch.org/).
