### ISSUE TITLE
allclose and isclose should support bool tensors

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#33048]
Currently torch::allclose() fails with
`C++ exception with description "Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead. (sub_check at ../aten/src/ATen/native/BinaryOps.h:24)`
on bool tensors

cc @yf225 @izdeby

**Comment by mruberry** [comment]
allclose is implemented with isclose, so isclose suffers from the same issue.

**Comment by pmeier** [comment]
Closing this in favor of the discussion in #60533.
