### ISSUE TITLE
[feature request] torch.cat to apply to as_tensor to inputs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#33042]
This is useful for some easy padding scenarios. Having it infer device would be extra-nice.

```
>>> np.concatenate(([False], np.ones((3,), dtype = np.bool), [False] ))
array([False,  True,  True,  True, False])

>>> torch.cat(([False], torch.ones((3,), dtype = torch.bool), [False] ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected Tensor as element 0 in argument 0, but got list

>>> torch.cat((torch.as_tensor([False]), torch.ones((3,), dtype = torch.bool), torch.as_tensor([False]) ))
tensor([False,  True,  True,  True, False])

>>> torch.cat((torch.as_tensor([False]), torch.ones((3,), dtype = torch.bool, device = 'cuda'), torch.as_tensor([False]) ))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 0 in sequence argument at position #1 'tensors'

```

cc @mruberry @rgommers @heitorschueroff

**Comment by fmassa** [comment]
I think in general it might be useful to have `as_tensor` to be called in every argument of a torch function, so that things like `torch.exp(5)` works.

**Comment by fmassa** [comment]
We discussed about this during the triage meeting.
This could have implications on torchscript, so it requires further consideration

**Comment by mruberry** [comment]
Following @fmassa's point above, I don't think we'd want to fix this for just torch.clamp. We either want to consistently support tensor-likes or not.

**Comment by mruberry** [comment]
I created https://github.com/pytorch/pytorch/issues/46138 to track the more general issue.
