### ISSUE TITLE
Build ahead-of-time C++ extensions with ninja on windows

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#33045]
## 🚀 Feature

Right now, C++ extensions support building with ninja on unix-based systems. This task is to enable that support for windows. See #32495 for the PR that added support for building with ninja on unix-based systems.

cc @yf225 @peterjc123

**Comment by peterjc123** [comment]
I skimmed the PR. Looks like you disabled ninja on Windows, right? That's a big step back. BTW, may I know what's blocking this on Windows?

**Comment by zou3519** [comment]
@peterjc123:

> I skimmed the PR. Looks like you disabled ninja on Windows, right? That's a big step back. 

Before my PR: ahead-of-time C++ extensions build with distutils. just-in-time C++ extensions build with ninja (all systems)

After my PR: ahead-of-time C++ extensions build with ninja, except for windows, which still uses distutils.  just-in-time C++ extensions build with windows (all systems).

There is no regression in how windows cpp extensions support ninja.

> BTW, may I know what's blocking this on Windows?

Mostly my lack of knowledge of how building things works on Windows and how distutils does things on windows. It shouldn't be too hard to get it to work once we figure out how all of that works.

**Comment by peterjc123** [comment]
Looks like the PR will be sth like https://github.com/pytorch/pytorch/pull/3993.
