### ISSUE TITLE
make script module object to pass over wire in rpc layer 

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#33052]
Right now there is no way to pass  script module object over wrie in rpc layer. 

1. When calling python myScriptModule constructor as follows, myScriptModule will be serialized by python pickler, but python pickler does not support scriptModule object serialization 
ret = rpc_sync(work1, myScriptModule, args=()) 
or rref = remote(work1, myScriptModule, args=()), rref.to_here()

2. When calling torchscript function to construct myScriptModule as follows, myScriptModule will be serialized by JIT pickler internally when we wrap the data to Message, but JIT pickler complained scriptModule is not supported type

@torch.jit.script
def construct_my_script_module():
   myScriptModule()

ret = rpc_sync(work1, construct_my_script_module, args=()) 
or rref = remote(work1, construct_my_script_module, args=()), rref.to_here()

**Solution**
We need to do special handling for script module object by calling torch.save() and torch.load() before dumping it to Message and pass it over wire

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @gmagogsfm @suo @xush6528

**Comment by SciPioneer** [comment]
This is also a limitation for RemoteModule. A scriptable RemoteModule cannot be send over RPC.

**Comment by rohan-varma** [comment]
@SciPioneer The specific examples in this issue should have been enabled enabled by this PR: https://github.com/pytorch/pytorch/pull/48293 . Although that PR only adds support for spending ScriptModule over RPC, but not Scripted RemoteModules. I wonder if we can add similar pickling logic for RemoteModule.

**Comment by SciPioneer** [comment]
Close this issue as it's already resolved by #48293.
