### ISSUE TITLE
Migrate `masked_select` from TH to ATen (CPU)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33053]
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko  as this affects complex tensor bring up

**Comment by ezyang** [comment]
This is high priority because `masked_select` is called when printing tensors

**Comment by mingfeima** [comment]
please check #33269
