### ISSUE TITLE
[feature request] Support SoftMax on bare Tensors

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#3305]
```python
torch.nn.functional.softmax(torch.rand(5, 5), dim = 0)
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File ".../python2.7/site-packages/torch/nn/functional.py", line 660, in softmax
#    return torch._C._nn.softmax(input, dim)
#RuntimeError: softmax(): argument 'input' (position 1) must be Variable, not torch.FloatTensor

torch.nn.functional.normalize(torch.rand(5, 5), dim = 0) # works
```

The workaround is easy, but it'd be nice to have. I guess this may work automagically when Variables and Tensors are unified?

**Comment by apaszke** [comment]
Yes. The fact that you gave a function arguments of unsupported types and it worked, is not a reason that all functions should work like this. Will be fixed automatically once we merge Variable and Tensor. Until then, wontfix

**Comment by vadimkantorov** [comment]
Cool! Till then the workaround will serve fine.
