### ISSUE TITLE
`copy.deepcopy` does not copy gradient buffers of `torch.autograd.Variable` instance

### ISSUE THREAD

**Issue by geoffroeder** [pytorch/pytorch#3307]
I ran into unexpected behaviour with `copy.deepcopy` applied to a `Variable`. The gradient buffer of the `Variable` is not copied.
```
a = torch.autograd.Variable(torch.ones(1))
a.grad = torch.autograd.Variable(torch.ones(1))
b = copy.deepcopy(a)
print(b.grad)
```
I think it would be a good idea to copy the gradient buffer during a deep copy. My use case is recording the gradient of a model's parameter space for optimization research. This would also be useful for debugging/development of complex models that involve atypical gradient operations.

This is handled here: https://github.com/pytorch/pytorch/blob/5760b036fb338eacd641418321f23aee51b1aee9/torch/autograd/variable.py#L89-L97

A solution would be to also copy the `grad` attribute of the current `Variable`, which would involve a recursion of the deep copy since the grad attribute is also a `Variable`.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @SsnL

**Comment by soumith** [comment]
@colesbury is this worth fixing, because of the upcoming Tensor <-> Variable merge?

**Comment by apaszke** [comment]
Not because of the merge, but it would make sense to copy it, so `deepcopy` would actually give you a full copy of the object. It might be a good idea to forbid `.grad` to have history, which would also solve the ref cycles we have.

**Comment by arogozhnikov** [comment]
It looks that in pytorch==0.4 (after merge) this issue is still valid. 

Also when trying to deepcopy a model, accumulated gradients for parameters are not preserved (which is not a significant problem)

**Comment by renesax14** [comment]
> Not because of the merge, but it would make sense to copy it, so `deepcopy` would actually give you a full copy of the object. It might be a good idea to forbid `.grad` to have history, which would also solve the ref cycles we have.

Has this been fixed? I am getting a similar issue but when I manually update the values of the weights e.g.

```
for name, w in mdl.named_parameters():
            w_new = MyFunc(w) 
            setattr(mdl, name, w_new)
```

**Comment by ezyang** [comment]
No it's still broken.

```
>>> import torch
>>> import copy
>>> x = torch.zeros(1)
>>> x.grad = torch.ones(1)
>>> y = copy.deepcopy(x)
>>> y.grad
>>> 
>>> torch.__version__
'1.4.0.dev20191210'

**Comment by albanD** [comment]
The `__deepcopy__` function located [here](https://github.com/pytorch/pytorch/blob/e2f12885140c36c1d5bf82de6eb47797856fdacd/torch/tensor.py#L42-L76) for Tensor needs to be updated. To do this.

**Comment by renesax14** [comment]
@soumith @apaszke @albanD 

I came across a very strange bug (?)  that is related to this. It seems I can't make deepcopies even if all the tensor's are leafs...which seemed weird, is this a bug in pytorch or what is going on?

```
import torch
import torch.nn as nn

import copy
from collections import OrderedDict

model = nn.Sequential( OrderedDict( [ ('fc0', nn.Linear(3,1)) ] ) )
w = model.fc0.weight
print(f'w = {w.norm(2)}')
for i in range(5):
    w_new = w - 1000
print(f'w_new = {w_new.norm(2)}')
print(f'w_new is not a leaf?: {not(w_new.is_leaf)}')
assert not(w_new.is_leaf)
#model.fc0.weight = nn.Parameter( w_new )
setattr(model,'fc0.weight', w_new )
print(f'model.fc0.weight.norm(2) = {model.fc0.weight.norm(2)}')
print(model.fc0.weight.is_leaf)
print(model.fc0.bias.is_leaf)
model_copy = copy.deepcopy(model)
```

output:

```
w = 0.4955401122570038
w_new = 1732.4461669921875
w_new is not a leaf?: True
model.fc0.weight.norm(2) = 0.4955401122570038
True
True
.
.
.
__deepcopy__(self, memo)
     42     def __deepcopy__(self, memo):
     43         if not self.is_leaf:
---> 44             raise RuntimeError("Only Tensors created explicitly by the user "
     45                                "(graph leaves) support the deepcopy protocol at the moment")
     46         if id(self) in memo:

RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

https://discuss.pytorch.org/t/how-is-it-possible-that-i-cant-create-a-deep-copy-although-all-my-parameters-are-leafs/69864

**Comment by albanD** [comment]
This is unrelated, this is a bad use of `setattr`, I answered on the forum.

**Comment by gchanan** [comment]
we should support deepcopy of `.grad`, as long as `.grad` is a leaf, consistent with our existing deepcopy for Tensors (see below).

```
In [7]: copy.deepcopy(x)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-4c90fdcacde0> in <module>()
----> 1 copy.deepcopy(x)

/data/users/gchanan/anaconda3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
    159             copier = getattr(x, "__deepcopy__", None)
    160             if copier:
--> 161                 y = copier(memo)
    162             else:
    163                 reductor = dispatch_table.get(cls)

/data/users/gchanan/_pytorch11/torch/tensor.py in __deepcopy__(self, memo)
     42     def __deepcopy__(self, memo):
     43         if not self.is_leaf:
---> 44             raise RuntimeError("Only Tensors created explicitly by the user "
     45                                "(graph leaves) support the deepcopy protocol at the moment")
     46         if id(self) in memo:

RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

**Comment by gchanan** [comment]
I got pinged on this; just noting that this isn't fixed.

**Comment by zdhNarsil** [comment]
I think this is still not fixed now.

**Comment by albanD** [comment]
Taking for bootcamp.
The implementation [here](https://github.com/pytorch/pytorch/blob/e2f12885140c36c1d5bf82de6eb47797856fdacd/torch/tensor.py#L42-L76) should be updated to properly deepcopy the `.grad` field if it exists.

**Comment by xiexie123** [comment]
> Taking for bootcamp.
> The implementation [here](https://github.com/pytorch/pytorch/blob/e2f12885140c36c1d5bf82de6eb47797856fdacd/torch/tensor.py#L42-L76) should be updated to properly deepcopy the `.grad` field if it exists. The corresponding tests (and doc if we document the deepcopy behavior) should be added as well.

not fixed

**Comment by zou3519** [comment]
@albanD is there someone lined up to fix this? Otherwise, based on the user activity, we should probably bump it up to high priority.

**Comment by albanD** [comment]
No this has not been done yet.

**Comment by xiexie123** [comment]
> @albanD is there someone lined up to fix this? Otherwise, based on the user activity, we should probably bump it up to high priority.

works for me

`class Tensor(torch._C._TensorBase):
    def __deepcopy__(self, memo):
        if self.is_leaf:
            if id(self) in memo:
                return memo[id(self)]
            with torch.no_grad():
                if self.is_sparse:
                    new_tensor = self.clone()
                else:
                    new_storage = self.storage().__deepcopy__(memo)
                    new_tensor = self.new()
                    new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
                memo[id(self)] = new_tensor
                new_tensor.requires_grad = self.requires_grad
                return new_tensor
        else:
            if id(self) in memo:
                return memo[id(self)]
            if self.is_sparse:
                new_tensor = self.clone()
            else:
                new_storage = self.storage().__deepcopy__(memo)
                new_tensor = self.new()
                new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
            new_tensor.requires_grad = self.requires_grad
            if self.grad is not None:
                new_tensor.grad = self.grad.__deepcopy__(memo)
            memo[id(self)] = new_tensor
            return new_tensor`

**Comment by Emmanuel357** [comment]
> > @albanD is there someone lined up to fix this? Otherwise, based on the user activity, we should probably bump it up to high priority.
> 
> works for me
> 
> ```java
> class Tensor(torch._C._TensorBase):
> 	def __deepcopy__(self, memo):
> 		if self.is_leaf:
> 			if id(self) in memo:
> 				return memo[id(self)]
> 			with torch.no_grad():
> 				if self.is_sparse:
> 					new_tensor = self.clone()
> 				else:
> 					new_storage = self.storage().__deepcopy__(memo)
> 					new_tensor = self.new()
> 					new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
> 				memo[id(self)] = new_tensor
> 				new_tensor.requires_grad = self.requires_grad
> 				return new_tensor
> 		else:
> 			if id(self) in memo:
> 				return memo[id(self)]
> 			if self.is_sparse:
> 				new_tensor = self.clone()
> 			else:
> 				new_storage = self.storage().__deepcopy__(memo)
> 				new_tensor = self.new()
> 				new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
> 			new_tensor.requires_grad = self.requires_grad
> 			if self.grad is not None:
> 				new_tensor.grad = self.grad.__deepcopy__(memo)
> 			memo[id(self)] = new_tensor
> 			return new_tensor
> ```

The gradient is not still copied.

**Comment by albanD** [comment]
Hi,

Did you tried on a nightly build?

**Comment by mattip** [comment]
@Emmanuel357 could you provide a code sample where `deepcopy` fails on PyTorch HEAD? Note the fix for this is not yet in an official release.

**Comment by Emmanuel357** [comment]
Here is my pytorch code. It keeps returning none.

```
import matplotlib.pyplot as plt
import torch
from torch import nn, optim
import copy
import numpy as np
from tools import *
space = 8
			
class NN(nn.Module):
	def __init__(self):
		super(NN, self).__init__()
		
		self.model = nn.Sequential(
			nn.Linear(1,5),
			nn.LeakyReLU(0.2,inplace=True),
			nn.Linear(5,1),
			nn.LeakyReLU(0.2, inplace=True)
		)
		
	def forward(self, x):
		x = self.model(x)
		return x

lf = NN()
optimlf = optim.Adam(lf.parameters(), lr = 0.01)
mse_loss = nn.MSELoss()
	
for j in range(151*5):
	optimlf.zero_grad()
	for i in range(space):
		xv = torch.tensor([i]).float()
		yv =  torch.tensor([real_function(i)]).float()
		out = lf(xv)
		loss = mse_loss(out,yv)
		loss.backward()
		
		sd = copy.deepcopy(lf.state_dict(keep_vars=True)); print(sd["model.0.weight"].grad); quit() #returns none here.

	optimlf.step()

```

**Comment by Emmanuel357** [comment]
real_function is just np.sin

**Comment by albanD** [comment]
Right, you need to use the nightly build to have this fix. Or wait for the 1.8 release.

**Comment by Emmanuel357** [comment]
how do I download the nightly build?

**Comment by albanD** [comment]
You can select `nightly` instead of `1.7.1` in the get started page: https://pytorch.org/get-started/locally/ !

**Comment by Emmanuel357** [comment]
Thank you very much. God bless you.

**Comment by Emmanuel357** [comment]
Do I still have to replace  __deepcopy__ with the __deepcopy__  below because the nightly build is not working. My present pytorch version is: 1.8.0.dev20210201+cpu


```
def __deepcopy__(self, memo):
		if self.is_leaf:
			if id(self) in memo:
				return memo[id(self)]
			with torch.no_grad():
				if self.is_sparse:
					new_tensor = self.clone()
				else:
					new_storage = self.storage().__deepcopy__(memo)
					new_tensor = self.new()
					new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
				memo[id(self)] = new_tensor
				new_tensor.requires_grad = self.requires_grad
				return new_tensor
		else:
			if id(self) in memo:
				return memo[id(self)]
			if self.is_sparse:
				new_tensor = self.clone()
			else:
				new_storage = self.storage().__deepcopy__(memo)
				new_tensor = self.new()
				new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
			new_tensor.requires_grad = self.requires_grad
			if self.grad is not None:
				new_tensor.grad = self.grad.__deepcopy__(memo)
			memo[id(self)] = new_tensor
			return new_tensor
```

**Comment by Emmanuel357** [comment]
Have you tried the nightly build to see if it actually works?

**Comment by albanD** [comment]
Yes, checked with this script on colab:
```python
!pip uninstall --y torch
!pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
print("Make sure to restart the env after the new version is installed")

import torch
import copy
import inspect

a = torch.rand(10)
a.grad = torch.rand(10)

print(a.grad)
b = copy.deepcopy(a)
print(b.grad)
```

**Comment by jhuebotter** [comment]
This does not translate to the deepcopy of nn.Module:

`
import torch
import copy

c = torch.nn.Linear(1, 10)

c.weight.grad = torch.rand((10, 1))

print(c.weight.grad)
d = copy.deepcopy(c)
print(d.weight.grad)
`
Tested with version 1.13.1. Running the code from @albanD gives the expected result. It would be great if we could find a way to copy an entire (larger) model including its gradients without having to copy every one by hand.
