### ISSUE TITLE
Build a generic failure injection mechanism for RPC

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#33072]
## 🚀 Feature
Due to the distributed, multi-process nature of the RPC framework it can be challenging to test certain functionality, such as timeouts, error handling, and error conditions that arise from separate threads of execution. 

It might be thus useful to have a generic failure injection mechanism where we could specify which, if any, failures to insert into the RPC agent when writing a unit test. This might reduce some of the hacks/methods that we have in the codebase that are currently unit test specific (though might also add some test-specific code hooks in the codebase).

One example where this could have been useful is the tests for the PR that added exception handling in `ProcessGroupAgent::enqueueSend()` (https://github.com/pytorch/pytorch/pull/31023), where should be able to insert a failure injection which causes errors that we can assert against.

I can also see this being useful in https://github.com/pytorch/pytorch/pull/32602 that is implementing retryability for RPCs.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by osalpekar** [comment]
Closed by https://github.com/pytorch/pytorch/pull/33636
