### ISSUE TITLE
Indices overflow

### ISSUE THREAD

**Issue by limberc** [pytorch/pytorch#33077]
## To Reproduce

1. Implementing a anto-grad Function that calculate the topk of the stored gradient
```
class some_function(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input
    @staticmethod
    def backward(ctx, grad_output):
        grad_input = grad_output.clone()
        grad_diff = grad_input.view(-1) - input.view(-1)
        torch.topk(-grad_diff.view(-1), int(grad_diff.view(-1).shape[0] * 0.5))[1]
        grad_input.view(-1)[indices] = input.view(-1)[indices]
``` 
2. It works fine in first few iteration. However, after a few iteration, the indices has blow up. `print(indices.max())` returns a very big value.

## Environment

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
CMake version: version 3.5.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration:
GPU 0: TITAN Xp COLLECTORS EDITION
GPU 1: TITAN Xp COLLECTORS EDITION

Nvidia driver version: 430.64
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.8.0
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] _pytorch_select           0.2                       gpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.4                      243    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py37ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py37hd6b4f25_0    defaults
[conda] torch                     1.2.0                     <pip>
[conda] torchvision               0.4.0                     <pip>

**Comment by fmassa** [comment]
It looks like your code snippet is incomplete, as you don't return anything from `backward`.

Can you please try to provide a reproducible script that illustrates the overflow?

**Comment by limberc** [comment]
This has been addressed by a new update strategy.
