### ISSUE TITLE
torch.h not included in LibTorch download.

### ISSUE THREAD

**Issue by JamieMair** [pytorch/pytorch#33088]
## Issue description

I have downloaded the LibTorch zip from [here](https://pytorch.org/get-started/locally/). I used the 1.4 stable build for windows with CUDA 10.1 support. However the torch folder within the include directory does not contain the "torch.h" header file used in many [examples](https://pytorch.org/cppdocs/installing.html#minimal-example). This error comes up when I use the line:
`
#include <Torch/torch.h>
`
The error simply says "cannot open torch.h".

I am using Microsoft Visual Studio 2019 and I have already added the additional include and library directories. The only "torch.h" file I can find is at "....\include\torch\csrc\api\include\torch\torch.h" but this does not include all of the other header files I need such as for the torch::nn::Module class etc.

## System Info

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
CMake version: version 3.15.0-rc2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 431.36
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] numpydoc==0.8.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.2                      1
[conda] mkl-service               1.1.2            py36h57e144c_4
[conda] mkl_fft                   1.0.1            py36h452e1ab_0
[conda] mkl_random                1.0.1            py36h9258bd6_0

cc @ezyang @gchanan @zou3519 @yf225 @peterjc123

**Comment by yf225** [comment]
@JamieMair Could you paste the list of folders / files you saw in the `include\torch\csrc\api\include\torch\` folder?

**Comment by peterjc123** [comment]
Normally speaking, the include dirs are `[LIBTORCH_DIR]\include` and `[LIBTORCH_DIR]\include\torch\csrc\api\include`, so there's nothing wrong there. if you use CMake, those options will be automatically set. That's why we suggest using CMake instead of creating projects with VS. Actually, VS itself supports CMake now.

**Comment by JamieMair** [comment]
> @JamieMair Could you paste the list of folders / files you saw in the `include\torch\csrc\api\include\torch\` folder?
I have just posted the image below of that folder. 
![image](https://user-images.githubusercontent.com/13971435/74152432-2efbf380-4c06-11ea-801f-59b6453da7a7.png)

**Comment by JamieMair** [comment]
> Normally speaking, the include dirs are `[LIBTORCH_DIR]\include` and `[LIBTORCH_DIR]\include\torch\csrc\api\include`, so there's nothing wrong there. if you use CMake, those options will be automatically set. That's why we suggest using CMake instead of creating projects with VS. Actually, VS itself supports CMake now.

Even when including the other folder as you said, the code from the example pages ([end to end example](https://pytorch.org/cppdocs/frontend.html)) in the documentation do not run correctly as there missing references to items like "torch::nn::Module" or "register_module".

**Comment by peterjc123** [comment]
Would you please try out the CMake script? The steps are listed below:
1. Create a new file named `test.cpp` based on the code in the example.
2. Create a new file named `CMakeLists.txt` with the following code.
```cmake
cmake_minimum_required(VERSION 2.8)

project(test)
set(CMAKE_CXX_STANDARD 14)

find_package(Torch REQUIRED)

add_executable(${PROJECT_NAME} "test.cpp")
target_link_libraries(${PROJECT_NAME} "${TORCH_LIBRARIES}")

# The following code block is suggested to be used on Windows.
# According to https://github.com/pytorch/pytorch/issues/25457,
# the DLLs need to be copied to avoid memory errors.
if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET ${PROJECT_NAME}
                     POST_BUILD
                     COMMAND ${CMAKE_COMMAND} -E copy_if_different
                     ${TORCH_DLLS}
                     $<TARGET_FILE_DIR:${PROJECT_NAME}>)
endif (MSVC)
```
3. Run the following script
```cmd
mkdir build
cd build
cmake -G"Visual Studio 16 2019" -Ax64 -Tx64 -DCMAKE_PREFIX_PATH="/path/to/libtorch" ..
cmake --build . --config Release
```

**Comment by JamieMair** [comment]
I have used cmake on both Windows and Linux and it works as expected on both.

**Comment by ali2210** [comment]
Sir I have a problem with libtorch 
[error](https://drive.google.com/file/d/1kjSYlhF7d6TSoDf4WYGQyiWr8Pw0F-1e/view?usp=drive_link)
[add cmake](https://drive.google.com/file/d/1_jXkhAJBILE8BTKHp26BgJwgFpy6kIW8/view?usp=drive_link)

I am working on rust bert and libtorch should be require to create and execute models. So I follow documentation
https://crates.io/crates/rust-bert
But all vain error presitent 

Os = deepin linux
arch = x86
family = linux
device = cpu

Kindly help me to resolve this issue
