### ISSUE TITLE
`__div__` and `__truediv__` behave as `__floordiv__` on Byte and LongTensors

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/pytorch#3308]
For compatibility with Python and numpy, maybe it could be considered to return a FloatTensor for the division containing ByteTensor and LongTensor, and preserve the type only with `__truediv__` (or div in python 2 without `from __future__ import division`).

This would also mitigate the floating exception of dividing by Long and Byte tensors with 0 values, since with the true division by default the user would get floating point infinities.

**Comment by mruberry** [comment]
This is actually fixed!
