### ISSUE TITLE
Have some way to pass number of workers to cpp extensions

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#33091]
## 🐛 Bug

After we merged https://github.com/pytorch/pytorch/pull/32495, cpp extensions started building with `use_ninja=True`. This caused the CI for nestedtensor to fail.

After some investigation, the hypothesis is that the CI OOM'ed because of the number of jobs being run in parallel. ninja, by default, uses #CPU + 2 workers. We should probably add some mechanism to let users control the degree of parallelism if they run into this problem (and also investigate more to see if that was indeed the cause).

cc @yf225 @cpuhrsch @ezyang

**Comment by zou3519** [comment]
In an ideal world I think I'd want something like being able to pass a number of workers to python setup.py. However, I don't think that is possible, so maybe an environment variable would be the best second option.

**Comment by cpuhrsch** [comment]
I wonder if [an alias](https://github.com/ninja-build/ninja/issues/797#issuecomment-456137713) will work. Looks like ninja itself decided against an environment variable.

**Comment by fmassa** [comment]
I think this might also be affecting torchvision see https://github.com/pytorch/pytorch/issues/33103 and https://github.com/pytorch/vision/issues/1857

**Comment by zou3519** [comment]
> I think this might also be affecting torchvision see #33103 and [pytorch/vision#1857](https://github.com/pytorch/vision/issues/1857)

I looked into it a bit, let's keep that discussion [to the torchvision thread](https://github.com/pytorch/vision/issues/1857#issuecomment-584709441). The TL;DR is that I don't think this is related because the torchvision CI started failing _before_ I merged the c++ extensions refactor
