### ISSUE TITLE
Delete zero_dim_dispatch_when_scalar

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33094]
This is for legacy TH. It is currently used by the following TH functions:

- [ ] `_th_scatter_` #24621 #24757
- [ ] `_th_fmod` #24565 #24701
- [x] `_th_remainder` #24753 #24615

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
An alternative for deleting this codegen is to just move the codegen into the implementation (which is a shorter thing to do).

**Comment by Baranowski** [comment]
I will work on moving this codegen into the implementation.

**Comment by Baranowski** [comment]
@ezyang This is only used by `_th_scatter_`.

`_th_fmod` and `_th_remainder` both have
```
        - arg: THTensor* self
          broadcast: other inplace fallback
        - THTensor* other
```

which makes `handle_zero_dim()` ignore them due to:

```
        if broadcasts_arg:
            return []
```

`_th_scatter_` is already being migrated to ATen, so I propose that I will abandon this issue.

**Comment by ezyang** [comment]
ok sgtm. when scatter lands we can pick this up again.
