### ISSUE TITLE
Saving a small view of the tensor resulted in saving all 

### ISSUE THREAD

**Issue by RemonComputer** [pytorch/pytorch#33101]
## 🐛 Bug

Saving a view of a tensor resulted in saving all of the tensor data, even the data outside this view

## To Reproduce

```
>>> big_tensor = torch.randn((100,100,100), dtype=float)
>>> buggy_tensor = big_tensor[0]
>>> good_tensor = big_tensor[0].clone()
>>> torch.save(buggy_tensor, 'buggy_checkpoint.pth')
>>> torch.save(good_tensor, 'good_checkpoint.pth')
```

buggy_checkpoint.pth has size of 8 MB
good_checkpoint has size of 80.3 KB
They both should have the same size

I noticed this because I was saving intermediate activation of a neural network per image, and the activation per image was so huge and the activation per image size changed when the batch size changed, So I realized it was saving all the batch data !!! 

## Expected behavior

The two checkpoints sizes should be the same

## Environment
This is the output from collect environment script:

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1060 with Max-Q Design
Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.16.3
[pip3] torch==1.3.1
[pip3] torchaudio==0.2
[pip3] torchfile==0.1.0
[pip3] torchtext==0.3.1
[pip3] torchvision==0.4.2
[pip3] warpctc-pytorch==0.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch

**Comment by fmassa** [comment]
This is expected -- a view of a tensor doesn't copy the memory, and holds a reference to the original storage.

This allows for efficient indexing / reshaping, but has the caveat that you mentioned.
Cloning the view makes it own the memory, so you should do it instead if you want to only serialize the part of the tensor being viewed.
