### ISSUE TITLE
doc.py file was built, but not reflected.

### ISSUE THREAD

**Issue by cold-pumpkin** [pytorch/pytorch#33119]
Hello. I have question about building documentation files.
I add some codes to `_torch_docs.py` file to solve the issue no. #29758 and built it.
Build was successful and I got an `index.html` file in `build/html/`folder, but the code I wrote was not reflected at all.
I tried a few times but couldn't solve it. Please give me a hand on which part to check.

I'm sorry, but @vishwakftw can you give me some advice?

## 📚 Documentation

```patch
diff --git a/torch/_torch_docs.py b/torch/_torch_docs.py
index 6d968a5191..9f3c06ffdd 100644
--- a/torch/_torch_docs.py
+++ b/torch/_torch_docs.py
@@ -3356,12 +3356,13 @@ Example::

 add_docstr(torch.mean,
            r"""
-.. function:: mean(input) -> Tensor
+.. function:: mean(input, dtype=None) -> Tensor

 Returns the mean  @value of all elements in the :attr:`input` tensor.

 Args:
     {input}
+    {dtype}

 Example::

@@ -3371,7 +3372,7 @@ Example::
     >>> torch.mean(a)
     tensor(0.3367)

-.. function:: mean(input, dim, keepdim=False, out=None) -> Tensor
+.. function:: mean(input, dim, keepdim=False, out=None, dtype=None) -> Tensor

 Returns the mean value of each row of the :attr:`input` tensor in the given
 dimension :attr:`dim`. If :attr:`dim` is a list of dimensions,
@@ -3384,6 +3385,7 @@ Args:
     {dim}
     {keepdim}
     {out}
+    dtype (:class:`torch.dtype`): the desired data type of returned tensor.

 Example::
```

**Comment by vishwakftw** [comment]
I believe you have to rebuild PyTorch from source. The docs are built with the version of PyTorch installed, so if you don’t install PyTorch after making these changes, you won’t be able to see it.
