### ISSUE TITLE
torch.tensor([0.1, 999999999999999999999]) fails with "Overflow when unpacking double"

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33111]
Work around is to add a decimal to the end of the big number.

**Comment by fmassa** [comment]
I think for floating point tensors we should handle the overflow ourselves and do the lossy cast, but for integer tensors, I wonder if raising an overflow error wouldn't be better?

For example, this numpy snippet
```python
np.array([1, 999999999999999999999], dtype='int64')
```
raises
```python
OverflowError: Python int too large to convert to C long
```

**Comment by ezyang** [comment]
Note that the Numpy example is not comparable, as the intended final type is a float tensor, not an int tensor.
