### ISSUE TITLE
[ROCm] fails on pdist tests

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#33128]
## 🐛 Bug

1. While working on #31593 we added a test for the backward pass using existing shapes, which fail on ROCm devices as seen in #32758 .

The first failure is for an input shape of `[4, 5]`, `p='Inf'` and `dtype=torch.float64` with a max absolute error of  `grad.abs().max(): 1.7263`.

2. We changed the indexing for `pdist_kernel_cuda_impl` to `int64_t`, since we encountered an overflow for large input shapes ([commit](https://github.com/pytorch/pytorch/pull/31593/commits/43cd34b0fbe872a5e5fd0e31a70596ddf7a7b656)).
A test for this change using a tensor of `[50000, 1]` also fails for ROCm in the forward pass.

3. To relax the shape limitation for the backward pass, we also changed `pdist_backward_kernel_cuda_impl`. Since 1. fails on ROCm devices without the changes, these particular changes might be unrelated.

We've disabled the tests for ROCm for now to unblock #31593

CC @iotamudelta , @ngimel

**Comment by iotamudelta** [comment]
Resolved in #34103
