### ISSUE TITLE
Could not find previous version of libtorch

### ISSUE THREAD

**Issue by HongShiKuan** [pytorch/pytorch#33131]
Cannot find the previous version of libtorch on the pytorch official website, such as v1.0

**Comment by peterjc123** [comment]
Linux
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.0.0.zip
https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-1.0.0.zip

Mac
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.0.0.zip

Windows: 
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.0.0.zip
https://download.pytorch.org/libtorch/cu80/libtorch-win-shared-with-deps-1.0.0.zip
https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-1.0.0.zip
https://download.pytorch.org/libtorch/cu100/libtorch-win-shared-with-deps-1.0.0.zip

**Comment by HongShiKuan** [comment]
thank you very much

**Comment by HongShiKuan** [comment]
> Linux
> https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.0.0.zip
> https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-1.0.0.zip
> 
> Mac
> https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.0.0.zip
> 
> Windows:
> https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.0.0.zip
> https://download.pytorch.org/libtorch/cu80/libtorch-win-shared-with-deps-1.0.0.zip
> https://download.pytorch.org/libtorch/cu90/libtorch-win-shared-with-deps-1.0.0.zip
> https://download.pytorch.org/libtorch/cu100/libtorch-win-shared-with-deps-1.0.0.zip

thank you very much

**Comment by eusoubrasileiro** [comment]
Still cannot find on the docs previous 1.4.0 version

**Comment by zhangyingbit** [comment]
@eusoubrasileiro maybe you need this https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.4.0.zip
