### ISSUE TITLE
Inconsistent handling of undefined Tensors in gradient formulas

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#33138]
In the cpp backend, undefined Tensors are used to efficiently represent a Tensor full of `0`s.
Even though we do support this in many functions, there are a lot that almost never get undefined gradients and are thus not properly implemented:
- All the backwards with direct formulas in `derivatives.yaml`
- Most functions in `Functions.cpp`.

In particular, the assumption that a function with a single output cannot get undefined gradients is not correct.
An example of such issue can be found in https://github.com/pytorch/pytorch/issues/33037 and https://github.com/pytorch/pytorch/issues/32619

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by kurtamohler** [comment]
@albanD, am I correct that this is the right way to add undefined tensor support to backward functions? https://github.com/kurtamohler/pytorch/commit/ac6b82ed064149166685a63145e06ff338f124cf

**Comment by albanD** [comment]
Yes that looks good.
I read it as: "if the grad_input is a Tensor full of 0s, the grad_output is also a Tensor full of 0s for this op". Since you don't need to care about sizes here.
Another way to fix this would be not to call this function when grad is not defined by changing the entry in derivatives.yaml to `self: "grad.defined() ? slice_backward(grad, self.sizes(), dim, start, end, step) : grad"`.

I don't have a strong preference for one in particular though.

**Comment by kurtamohler** [comment]
Alright cool, that makes sense. It feels cleaner to make these changes in Functions.cpp when possible, to keep all the logic in one place.

I'm wondering how to minimally reproduce these undefined gradients in python so I can add tests for them. Is there a way to create an undefined tensor in python, or is that only possible in the C++ api? I though something like this might work, but it ended up exercising the defined codepath in `slice_backward`:

```
a = torch.Tensor()
a.requires_grad = True
b=a[2:5].sum()
b.backward()
```

**Comment by albanD** [comment]
The best way would be to add a new custom Node definition to `torch/csrc/autograd/functions` that will do a clone in input and return an undefined Tensor in backward that we can use for testing purposes.

Otherwise, the (almost) minimal repro example I can thing of is:
```
import torch
from torch import nn
from torch.autograd import grad

x= torch.randn(2,5,12,12,dtype=torch.float)
x.requires_grad = True
x1 = nn.Conv2d(5,6,5, padding=2, bias=True)(x)
x1 = nn.PReLU(6, init=0.25)(x1)
x2 = nn.Conv2d(5,6,3, padding=1, bias=True)(x)
x2 = nn.PReLU(6, init=0.25)(x2)
out = torch.cat((x1, x2), dim=1)
out = nn.Sigmoid()(out)
g, = grad(out.sum(), x, create_graph=True)
grad(g.sum(), x)
```
But that requires double backward and a few ops :D

**Comment by kurtamohler** [comment]
Once I create the new node, how do I attach it to a graph from within python? I can see that it will become available as a member within `torch._C._functions`, but I don't know what to do with that.

**Comment by albanD** [comment]
Yes you can register it ther with a constructor to be sure you can create it from python. Then you instantiate an instance and call it on the Tensor to get a new Tensor that has this Node in the backward graph.
You can check how `DelayedError` is defined and used for an example.

Your test would look like:
```
inp = # Some input that requires grad
out = fn_to_test(inp)
res = UndefinedGradNode()(out)
res.sum().backward() # Note that the gradient we backprop here will actually be ignored.
```

**Comment by kurtamohler** [comment]
The way I have things set up at the moment, `res = torch._C._functions.UndefinedGrad()(inp)` is calling UndefinedGrad's constructor twice, once with no arguments and then once with the argument `inp`. But what we really want is for it to call the constructor once with no args and then call the `operator()` method with `inp` as the argument.

For some reason, if I don't provide any arguments to the second pair of parentheses, then it _does_ call `operator()`. I'm not sure what I'm doing wrong.

Right now, I have the new node declared like this:
```
struct TORCH_API UndefinedGrad : public Node {
  using Node::Node;
  variable_list apply(variable_list&& inputs) override;
  std::string name() const override { return "UndefinedGrad"; }
}
```
The constructor is defined as:
```
struct UndefinedGradCtor {
  UndefinedGrad* operator()(PyObject* args) {
    TORCH_CHECK(PyTuple_GET_SIZE(args) == 0, "Requires zero arguments, got ", PyTuple_GET_SIZE(args));
    return new UndefinedGrad();
  }
};
```
And I'm adding it to the `torch._C._functions` module like this:
```
  static PyTypeObject UndefinedGradClass;
  addClass<UndefinedGrad, UndefinedGradCtor>(module, UndefinedGradClass, "UndefinedGrad")
```

**Comment by albanD** [comment]
I haven't looked at this API in a while :D 
But that looks good. `torch._C._functions.UndefinedGrad()` should give you an instance of a `PythonCppFunction` for which the call is defined in `python_cpp_functions.cpp`.

If you add a dummy argument, does it work better?

Maybe we should move this discussion to the forum to reduce noise on this issue. Can you add a post there and ping me?

**Comment by kurtamohler** [comment]
Ah, I realized that I could call `DelayedError` in the way you described, which meant that there was some key difference between it and `UndefinedGrad`. I found out that I need to call `add_input_metadata(Node::undefined_input());` inside `UndefinedGrad::UndefinedGrad()` to give the python `__call__` function one argument. Now I can successfully add an `UndefinedGrad` node to the graph in python.

**Comment by kurtamohler** [comment]
@albanD, alright I finished up some tweaks to `UndefinedGrad`'s behavior and I believe I'm now in the position to include unit tests for the derivative formula changes. I just have one question for you to make sure the undefined grads are behaving as expected. This script first calculates the grad of a `torch.slice()` call with an `UndefinedGradBackward` node in the graph that sends an undefined tensor into the `slice_backward()` function, and then the script calculates the grad normally, without an undefined grad:
```
import torch
a = torch.rand(10)
a.requires_grad = True
b = a[:]
torch._C._functions.UndefinedGrad()(b).sum().backward()
print("a.grad with undefined grad: %s" % (a.grad))
b.sum().backward()
print("a.grad with defined grad: %s" % (a.grad)
```
As expected, if I use the original implementation of `slice_backward`, I get this error:
```
RuntimeError: tensor does not have a device
Exception raised from device at ../c10/core/TensorImpl.h:465 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x58 (0x7f020d617878 in /work/kurtamohler/development/pytorch-undefined-tensor-gradients/torch/lib/libc10.so)
...
```
Then when I use the updated implementation of `slice_backward` which handles the undefined grad case, I get this output:
```
a.grad with undefined grad: None
a.grad with defined grad: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
I'm wasn't completely sure if we want the python result to be `None` when the grad is undefined, so I just wanted to double check with you. I was under the (possibly incorrect) assumption that when an undefined grad is passed back to python, it would either look like or be converted into a defined tensor of zeros matching the size of tensor `a`. I can see how `a.grad == None` would also be valid, as long as that's the intended result.

**Comment by albanD** [comment]
Hi,

How we represent independent/0 gradients is a broader question yes.
For now, None or a Tensor full of 0s are both valid.
We might want to change that in the future but it is unlikely to happen any time soon.

**Comment by kurtamohler** [comment]
@albanD, I've added undefined gradient support to a portion of the backward functions (still have more to go), and I started writing a test for them (only a handful of cases so far).

Here's the test: https://github.com/kurtamohler/pytorch/commit/ebc99ec58b14334227e15da9e4638401c1e3984c#diff-e7525582ab432c30821289d64cc52bc3R217

I figured that the test should be easily extensible, so adding a case for a new backward function should only require one line. Although maybe there's an even better way that could automatically find all the differentiable operations in pytorch. Is there a way to do that?

I also figured that I should test the case where the output gradient is a defined zero tensor. If for any reason a backward method calculates a non-zero input gradient when given a zero output gradient, then returning an undefined grad when given an undefined grad would be invalid. I can't think of any mathematical reason why a zero output grad would not result in a zero input grad, given that we're using the chain rule, but I think that testing it is safer than not testing it.

While I've been going through all the backward functions, I was wondering, would there be an easier way to add the undefined gradient checks in one place to make it apply to all backward operations? Don't all or most of the backward functions have an auto-generated wrapper, and if so, could I just add the check there?

**Comment by kurtamohler** [comment]
I found out that `tools/autograd/gen_autograd_functions.py` is what I would need to modify to automatically apply the defined check to all backward functions. For instance, for single derivatives, I would need to modify this `DERIVATIVE_SINGLE` template: https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_autograd_functions.py#L58

However, one challenge here is that depending on what the `${derivative}` substitution is, `grad_result` can either be a single Tensor or a tuple of Tensors. So I couldn't just do something like `auto grad_result = check_any_defined(grads) ? ${derivative} : Tensor();`. I'm not sure at the moment how to do it correctly. The `derivatives.yaml` file shows whether the output is a Tensor or a tuple of Tensors, so I'm assuming that that information is available within `gen_autograd_functions.py`, I just need to find out how to access it.

**Comment by kurtamohler** [comment]
I realized that the only single derivatives that need to return a list of Tensors are `cat` and `stack`, so I was able to just check the operation name within `gen_autograd_functions.py`. See the above commit. @albanD , is there any obvious reason we wouldn't want to do it this way? To me it seems more manageable than manually adding duplicate logic to every backward function.

**Comment by albanD** [comment]
Hi,

I thing there are two things here:
- Implementation-wise, modifying the codegen to automatically handle undefined gradient would be a good thing (note that only things with a single output can be done automatically here).
  - There are actually a bunch of functions in derivatives.yaml that have multiple outputs so this won't cover everything :/
- For testing, you  want to check
  - add_test() in test_autograd.py [here](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/test/test_autograd.py#L4312) that is called for each configuration and is currently used to generate all the backward tests based on the op list from [here](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/torch/testing/_internal/common_methods_invocations.py#L117).
  - In particular, [run_funtional_check](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/test/test_autograd.py#L4283) could be extended to run the undefined gradient test on top of the regular gradcheck.


> I can't think of any mathematical reason why a zero output grad would result in a non-zero input grad.

The one case that comes to mind here are `inf` and `nan`
At the moment, what happens for most functions is that undefined remains underfined and zeros become `nan`.
Since you don't change any behavior here, just add new feature, you can continue with this I think.

**Comment by kurtamohler** [comment]
Alright, everything is mostly working now, and the undefined grad tests are passing. However, I noticed that two test cases in `test_nn.py` are failing. Once I've fixed those, I'll create a PR.

**Comment by albanD** [comment]
Perfect! Thanks for looking into it!
Let me know if you need any help for the `test_nn.py` tests.

**Comment by kurtamohler** [comment]
I just ran the two failing tests on master (commit 176174a68ba2d36b9a5aaef0943421682ecc66d4), and they fail there too, so they're not introduced by my changes after all. Going to rebase and submit a PR now.
