### ISSUE TITLE
Support multiple-build-type generators for CMake

### ISSUE THREAD

**Issue by fmigneault** [pytorch/pytorch#33132]
## To Reproduce

Building torch with MSVC 2019.
Getting : 
```
3>------ Build started: Project: __aten_op_header_gen, Configuration: Debug x64 ------
4>------ Build started: Project: torch_cpu, Configuration: Debug x64 ------
4>cl : command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible
```
Seems similar to #4475, but the cmake files are now completely different from that time.

## Expected behavior

Flag /Ox not added for debug build.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
$ python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows▒10 Professionnel
GCC version: Could not collect
CMake version: version 3.16.1

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 441.22
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.1
[pip] numpydoc==0.8.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.0                      118
[conda] mkl-service               1.1.2            py37hb217b18_5
[conda] mkl_fft                   1.0.4            py37h1e22a9b_1
[conda] mkl_random                1.0.1            py37h77b88f5_1
```

 - PyTorch Version (e.g., 1.0): master

cc @peterjc123

**Comment by peterjc123** [comment]
Could you please post the steps you used to trigger a debug build? In our CI builds, we do `set DEBUG=1` before calling `python tools/build_libtorch.py`. Currently, it is not impossbile to use VS as a multi-configuration generator for CMake.

**Comment by fmigneault** [comment]
Using `CMAKE_BUILD_TYPE=Release`, there is no issue.
With `CMAKE_BUILD_TYPE=Debug`, the problem remains.
The specific cxx flags per configuration in cmake seem correct (eg: `CMAKE_CXX_FLAGS_DEBUG=/MDd /Zi /Ob0 /Od /RTC1`). 
I can change things in the GUI, but this is only a temporary patch as it gets reset on the next cmake autorun by VisualStudio.

**Comment by peterjc123** [comment]
Yeah, currently you can only using it like a single-build-type generator, which use a consistent `CMAKE_BUILD_TYPE` across configuration and build. However, we don't rely on this in our CI or release builds so this may not be fixed with a high priority. (We use Ninja.) Anyway, PRs are welcomed.

**Comment by peterjc123** [comment]
BTW, if you don't use VS GUI,  you can use the command `cmake --build . --config Release` to ensure a Release build.

**Comment by alinpahontu2912** [comment]
Hey @fmigneault, is this issue still relevant? I believe it has been resolved. Both Ninja and VS are supported, and multiple CMAKE_BUILD_TYPEs are available (Release, RelWithDebInfo, Debug).

**Comment by fmigneault** [comment]
@alinpahontu2912 This is most probably resolved since. I have not tried it recently. Will reopen if it ever becomes a problem.
