### ISSUE TITLE
Summary writer doesn't support None

### ISSUE THREAD

**Issue by mpariente** [pytorch/pytorch#33140]
## 🐛 Bug
If a `None` is encountered [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/summary.py#L139), `hparams` will raise an error.
Is there a reason we don't want `None`? In this case, can we just convert them to string? 

## To Reproduce
```
from torch.utils.tensorboard.summary import hparams 
to_hparams = dict(this=1, and=2, that=None)
a, b, c = hparams(hparam_dict=to_hparams, metric_dict={})
```
## Expected behavior
Just support `None` values.

## Environment
This is not related to environments, the reason is pretty clear. 
I can make a PR if you agree.

**Comment by mpariente** [comment]
@cpuhrsch Anything about this issue?

**Comment by orionr** [comment]
cc @J0Nreynolds @lanpa @sanekmelnikov

**Comment by lanpa** [comment]
ported from https://github.com/lanpa/tensorboardX/commit/9d267066a6d67991ad8263c3a4f4a8c570367c53

**Comment by mpariente** [comment]
Thanks @lanpa, I commented on the PR as well. 
In the future, should I open an issue here or in tensorboardX?

**Comment by lanpa** [comment]
Maybe new feature suggestion in tensorboardX; and bug reports here :)
