### ISSUE TITLE
Pytorch with Cuda 10.2

### ISSUE THREAD

**Issue by csverma610** [pytorch/pytorch#33188]
Hello 

My ubuntu 18.04 automatically upgraded the Nvidia driver to 440.59 
and I see the following with nvidis-smi

-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+
|   0  GeForce GTX TIT...  Off  | 00000000:65:00.0  On |                  N/A |
| 26%   32C    P8    16W / 250W |    600MiB /  6080MiB |      0%      Default |

Now, how do I install Pytorch which uses Cuda10.2 ? The website only support 10.1 and
installing Pytorch from the source turned out to be a non-trivial task.

Thanks.

cc @ngimel

**Comment by ptrblck** [comment]
Your local CUDA installation won't be used if you install the PyTorch binaries, as they ship with their own CUDA, cudnn etc.

If you want to build from source, follow [these instructions](https://github.com/pytorch/pytorch#from-source) and let me know, if you encounter any trouble.
Also, note that CUDA extensions are currently broken in 10.2 as described [here](https://github.com/pytorch/pytorch/issues/33203).

**Comment by Coderx7** [comment]
If he uses `pip`, the local cuda will be used. We have cuda10.2.89 /cudnn 7.6.5 installed with Pytorch 1.4.0 and everything seems fine so far since I'm training right now with our V100! and havent had any issues!

**Comment by ptrblck** [comment]
@Coderx7 
This shouldn't be the case.
You can check the linked version e.g. via `ldd .../torch/_C.cpython-36m-x86_64-linux-gnu.so`
which should output the `libcudart` library in the same location as your wheel, while a source build will point to your local CUDA install dir (e.g. `/usr/local/cuda`).

You can also check the used CUDA and cudnn versions inside PyTorch via
```python
print(torch.version.cuda)
print(torch.backends.cudnn.version())
```

**Comment by Coderx7** [comment]
its strange! 
Pytorch reports the cuda version to be `10.1.243` and cudnn version to be `7.6.3` while quering the 
`nvcc --version` reports cuda to be `10.2.89` and cudnn `7.6.5` !

**Comment by Lornatang** [comment]
I think one of the biggest issues with CUDA10.2 is that it is not compatible with Nvidia's Apex training tool, because I can't increase my Batch size! . So now I'm using cuda10.1 @ @Coderx7

**Comment by ptrblck** [comment]
@Coderx7 
That's expected. 
As explained, the binaries ship with their own runtime and your local CUDA and cudnn will only be used if you build PyTorch from source. 

@Lornatang 
`apex` works with CUDA10.2.
If you are using the PyTorch binaries with 10.1, we recommend to build these also with 10.2, as a CUDA version mismatch might yield side effects.

**Comment by Lornatang** [comment]
The Apex tool will be compiled in Ubuntu with support for CUDA10.1 only for the time being. I mean, if it was compiled under CUDA10.2, would it have been updated? @ptrblck

**Comment by jinfagang** [comment]
When will pytorch official site update cuda 10.2 binary installation link? @ptrblck

**Comment by ngimel** [comment]
@ptrblck does not control pytorch binaries. If you need 10.2 version now, probably nvidia NGC pytorch containers have it, @ptrblck can confirm, but I don't expect pytorch build with 10.2 version to be significantly different than 10.1.

**Comment by jinfagang** [comment]
@ngimel  thanks. 10.2 is an embarrassing release of CUDA. TensorRT 7.0 doesn't support 10.2... (only 9.0 and 10.0 10.1 supports). I think I'd better stick with 10.1...

**Comment by ptrblck** [comment]
Yes, our NGC PyTorch containers are built with CUDA10.2.89 currently.
[Release notes for 20.01](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-01.html#rel_20-01).

@jinfagang 
We ship our PyTorch container with TensorRT7.0 and CUDA10.2.
The [TensorRT 7 docs](https://docs.nvidia.com/deeplearning/sdk/tensorrt-install-guide/index.html) also mention the supported CUDA versions:

> Verify that you have the CUDA Toolkit installed; versions 9.0, 10.0, and 10.2 are supported.

**Comment by jinfagang** [comment]
Oh, I miss remembered, it was 10.1 not supported in tensorrt 7.0. So when will 10.2 based pytorch wheel release?

**Comment by seemethere** [comment]
I'll be taking this one on this week, will update more when there's more news.

**Comment by seemethere** [comment]
Just merged in #33471, binaries should be available in the nightly channels starting tomorrow.

**Comment by seemethere** [comment]
This should be resolved now, am able to confirm that installing with `cudatoolkit=10.2` on `pytorch-nightly` installs a version of pytorch that has been compiled with cuda 10.2

**Comment by jinfagang** [comment]
@seemethere How about install from pip?

**Comment by ajagarao** [comment]
torch.version.cuda problem   to install cdqa
