### ISSUE TITLE
Bug in scatter_kwargs when DataParallel.forward has multiple kwargs and one input

### ISSUE THREAD

**Issue by Erotemic** [pytorch/pytorch#33185]
## 🐛 Bug

I'm pretty sure I've discovered a bug that happens when you have a Module where the forward function accepts kwargs and you pass it fewer inputs than there are kwargs. I'm not sure the best way to explain it, but I can give a MWE to reproduce.  

Its possible that this is expected behavior, but if that is the case I'm interested in why, but all my testing leads me to believe this is a bug. 

## To Reproduce

```python

        import torch
        from torch.nn.parallel import DataParallel

        # First lets create a simple model where the forward function accepts
        # kwargs. I don't really care what they do for this example, but imaging
        # they are flags that change the behavior of forward.

        class MyModel(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.conv = torch.nn.Conv2d(1, 1, 1)

            def forward(self, im, **kwargs):
                return self.conv(im)

        raw_model = MyModel()
        raw_model = raw_model.to(0)

        # Next create some dummy input and verify the model works by itself
        im = torch.zeros(1, 1, 1, 1).to(0)
        raw_model.forward(im)

        # Now create a DataParallel object to map the input across two devices
        par_model = DataParallel(raw_model, device_ids=[0, 1], output_device=0)

        # In the case where kwargs are not specified DataParallel correctly
        # understands that there is only one item in the batch and applies the
        # operation on only one GPU.
        par_model.forward(im)

        # Howver, if you pass kwargs, then data parallel breaks
        par_model.forward(im, flag1=True)
```

This causes a TypeError: 
```
TypeError: Caught TypeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/joncrall/.local/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'im'
```

The reason for this is in the implementation of `scatter_kwargs`, which I'm pasting here for reference: 

```python

def scatter_kwargs(inputs, kwargs, target_gpus, dim=0):
    r"""Scatter with support for kwargs dictionary"""
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
    kwargs = scatter(kwargs, target_gpus, dim) if kwargs else []
    if len(inputs) < len(kwargs):
        inputs.extend([() for _ in range(len(kwargs) - len(inputs))])
    elif len(kwargs) < len(inputs):
        kwargs.extend([{} for _ in range(len(inputs) - len(kwargs))])
    inputs = tuple(inputs)
    kwargs = tuple(kwargs)
    return inputs, kwargs

```

when the `dict(flag1=True)` kwargs is scattered it returns `[{'flag1': True}, {'flag1': True}]`, which has length 2 even though the scattered inputs (`[{'flag1': True}, {'flag1': True}]`) only have length 1. The subsequent checks add empty tuples to the inputs. 

Thus when the scattered data is applied across the model replicas one of them receives an empty `*args`, which is causes an error because it expects at least one argument. 

## Expected behavior

In an ideal world I would expect DataParallel to "understand" that only one tensor is passed in (which happens sometimes for the very last batch in an epoch) and the kwargs are scalar flags, so only one model replica should be made. 

Unfortunately, I'm not sure if fixing this is possible if there is a use case where users are passing Tensors into kwargs that are expected to be aligned with any other input tensors (or perhaps someone only accepts `**kwargs` in the forward function in which case `*args` should always be empty). However, if the previous use case I described is not expected or supported (i.e. torch forward functions should always expect at least one positional argument), then this use case might be fixed by tweaking  `scatter_kwargs` 

It might be possible to explicitly handle the case where there are at least some positional arguments, but some of them are empty. Something like: 

```python
def scatter_kwargs(inputs, kwargs, target_gpus, dim=0):
    r"""Scatter with support for kwargs dictionary"""
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
    kwargs = scatter(kwargs, target_gpus, dim) if kwargs else []
    if len(inputs) < len(kwargs):
        inputs.extend([() for _ in range(len(kwargs) - len(inputs))])
    elif len(kwargs) < len(inputs):
        kwargs.extend([{} for _ in range(len(inputs) - len(kwargs))])

    # patch for cases where #inputs < len(target_gpus) and len(kwargs) > 0
    is_empty = [len(p) == 0 for p in inputs]
    num_empty = sum(is_empty)
    num_full = len(inputs) - num_empty
    if num_full > 0 and num_empty > 0:
        kwargs = kwargs[0:num_full]
        inputs = inputs[0:num_full]

    inputs = tuple(inputs)
    kwargs = tuple(kwargs)
    return inputs, kwargs
```

## Environment

    [PyTorch version: 1.4.0
    Is debug build: No
    CUDA used to build PyTorch: 10.1

    OS: Ubuntu 18.04.3 LTS
    GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
    CMake version: version 3.15.3

    Python version: 3.8
    Is CUDA available: Yes
    CUDA runtime version: 10.1.243
    GPU models and configuration: 
    GPU 0: GeForce GTX 1080 Ti
    GPU 1: GeForce GTX 1080 Ti

    Nvidia driver version: 435.21
    cuDNN version: /home/joncrall/.local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5

    Versions of relevant libraries:
    [pip3] numpy==1.18.1
    [conda] blas                      1.0                         mkl  
    [conda] mkl                       2019.4                      243  
    [conda] mkl-service               2.3.0            py38he904b0f_0  
    [conda] mkl_fft                   1.0.15           py38ha843d7b_0  
    [conda] mkl_random                1.1.0            py38h962f231_0  
    [conda] torch                     1.4.0                    pypi_0    pypi
    [conda] torchvision               0.2.2.post3              pypi_0    pypi

**Comment by SsnL** [comment]
I didn't read the description in details. Is this similar to https://github.com/pytorch/pytorch/issues/31460?

**Comment by gchanan** [comment]
@SsnL that looks like the same issue to me.  I'm going to close this, please reopen if you disagree.

**Comment by jlim13** [comment]
Is there any workaround for this?
