### ISSUE TITLE
c++ make torch::nn::Sequential push_back(AnyModule) methods public

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#33192]
## 🚀 Feature
can these private _push_back_ functions be made public?

```
/// Adds a type-erased `AnyModule` to the `Sequential`.
  void push_back(AnyModule any_module) {
    push_back(c10::to_string(modules_.size()), std::move(any_module));
  }

  void push_back(std::string name, AnyModule any_module) {
    modules_.push_back(std::move(any_module));
    const auto index = modules_.size() - 1;
    register_module(std::move(name), modules_[index].ptr());
  }
```

## Motivation

If i already have an `AnyModule a`,
I can't figure out how to add it to a _Sequential_ without something like
`if(auto* m=a.as<torch::nn::Conv2d>()) seq->push_back<torch::nn::Conv2d>(*m)`
which will then turn it back into an AnyModule and add it.

Or making the single AnyModule into a vector:
`seq->extend(std::vector<AnyModule>{a})`

Thanks

cc @yf225

**Comment by meganset** [comment]
It looks like moving the two private _push_back()_ methods from private -> public in 
_nn/modules/container/sequential.h_ doesn't cause any build problems using _master_ from this morning.

Does it seem reasonable to make these methods public?
(_AnyModule_ is part of the public interface, and _Sequential_ is a vector of _AnyModule's_)

Thanks

**Comment by yf225** [comment]
@meganset Yes I think it would make sense to make `push_back(AnyModule)` methods public. Curious would you be interested in opening a PR for it? Thanks!

**Comment by yf225** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/34208.
