### ISSUE TITLE
A possible bug in `binary_cross_entropy`.

### ISSUE THREAD

**Issue by IssamLaradji** [pytorch/pytorch#3320]
After upgrading to 0.2 I am facing an issue with using `binary_cross_entropy`.

I tried to run the example code for using `binary_cross_entropy` in the documentation:
```python
input = autograd.Variable(torch.randn(3), requires_grad=True)
target = autograd.Variable(torch.LongTensor(3).random_(2))

# Error happens here
loss = F.binary_cross_entropy(F.sigmoid(input), target)
loss.backward()
```
but I get the following run-time error:
```
*** TypeError: is_same_size received an invalid combination of arguments - got (torch.FloatTensor), but expected (torch.LongTensor other)
```
It seems that `binary_cross_entropy` checks whether the predicted sigmoid values are `long` - should that be the case ?

**Comment by IssamLaradji** [comment]
It seems that converting `target` to have dtype `float` solves the issue. I am closing the issue. :)

**Comment by alykhantejani** [comment]
Hi @IssamLaradji, 

This is because the `is_same_size` function requires both tensors to be of the same type. This was removed and `input.nelement() == target.nelement()` was used instead. You can probably solve this by upgrading to a newer version of pytorch/building from master

**Comment by IssamLaradji** [comment]
Thanks for explaining!
