### ISSUE TITLE
nn.LSTM output shape is mis-documented

### ISSUE THREAD

**Issue by LiboShen** [pytorch/pytorch#33215]
## 📚 Documentation

https://pytorch.org/docs/stable/nn.html#lstm

> output of shape (seq_len, batch, num_directions * hidden_size): tensor containing the output features (h_t) from the last layer of the LSTM, for each t. If a torch.nn.utils.rnn.PackedSequence has been given as the input, the output will also be a packed sequence.

The shape should actually be `(batch, seq_len, num_directions * hidden_size)`

cc @jlin27 @mruberry @albanD @jbschlosser @zou3519

**Comment by ptrblck** [comment]
The documentation refers to the default setup, which is `batch_first=False`:
```python
model = nn.LSTM(
    input_size=10,
    hidden_size=20,
    num_layers=1,
    batch_first=False # default
)

seq, batch_size, f = 100, 5, 10
x = torch.randn(seq, batch_size, f)
output, (h, c) = model(x)
print(output.shape)
> torch.Size([100, 5, 20])
```
The docs explains this case for `batch_first=True`:

> batch_first – If True, then the input and output tensors are provided as (batch, seq, feature). Default: False

**Comment by LiboShen** [comment]
I see, thanks.

Although the doc could be clearer, like what you pointed out. If it's just me get confused, please feel free to close this issue.

**Comment by EoinKenny** [comment]
Sorry for my ignorance, but it seems so strange to not have batch first as the default, why is that?

**Comment by mariosasko** [comment]
> Sorry for my ignorance, but it seems so strange to not have batch first as the default, why is that?

It's for efficiency reasons. Basically, for each timestamp you can feed the recurrent cell with all the values from the batch at that timestamp and the time-first format means faster indexing.

**Comment by jbschlosser** [comment]
Closing because output shape now explicitly specifies shapes for both `batch_first=False` and `batch_first=True`. Feel free to reopen with specific comments if there is still confusion.
