### ISSUE TITLE
Add get_type() API to RRef

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#33210]
## 🚀 Feature: Add get_type() API to RRef

It would be useful to add a `get_type()` function on `RRef` that returns the type of the object that the RRef is holding. This would be pretty useful for user debugging purposes, such as validating that a certain RRef holds an `nn.Module` that is created remotely and the like.

It would also be useful to look at this type information if we add support to gather all parameters that exist on remote workers, see https://github.com/pytorch/pytorch/issues/33115.

The API should look roughly as follows:

```
# on A and B
def create_tensor():
    return torch.ones(1)

# on B
rref = rpc.remote(A, create_tensor, args=())
rref_type = rref.get_type()
>>> rref_type
<class 'torch.Tensor'>
```

After speaking to @mrshenli offline, one way we could go about implementing this is wrapping the call and running it on the remote worker. We should be able to do this by sending an RPC with a new request type to the owning node, which returns and deserializes the type. We would then need to convert it to a Python type . Efficiency wise, this is not ideal since it requires an RPC round trip, so open to other suggestions as well.

Code pointers/work items:
1) Expose python `get_type` on RRef by adding it to the pybind layer: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/init.cpp#L112

2) Python RRef:https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/py_rref.cpp

3) RRef C++ API (PyRRef from above wraps around this): https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rref_impl.cpp

There are many instances of `TypePtr rrefType` (see py_rref: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/py_rref.cpp) , we can use this attribute and then convert to a python type to get the type.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by agolynski** [comment]
@mrshenli @rohan-varma 

The type of rref is not known after 
`rref = rpc.remote(A, create_tensor, args=())`
(since create_tensor might not have executed yet), right?

Optimizations-wise: do we want some kind of eager notifications like 'rref' is ready (maybe together with type, other meta). Do we already have some kind of notifications like that?

**Comment by rohan-varma** [comment]
@agolynski - Sorry, must have missed this. I think this is correct and @mrshenli mentioned to me too that the type of the RRef might not be known when we call `get_type()`. 

I wonder if we can do something like block returning on `get_type()` until the creation of the RRef on the remote end has been satisfied and the appopriate ACK has been received? Although, from a user standpoint this might not be great since users probably don't expect a simple `get_type()` to potentially block for that long. 

For eager notifications, I don't believe that we have those right now - if we wanted to do that, I'm guessing we'd need to implement some sort of listener on each node that takes actions corresponding to the notifications that it receives?

**Comment by agolynski** [comment]
@rohan-varma We've talked with @mrshenli about this and he proposed a simple python implementation of this, e.g.

@_require_initialized
def typeof(rref):
    return rpc_sync(rref.owner(), _typeof, args = (rref,))

def _typeof(rref):
    return type(rref.local_value())

This would block on sending rpc with rref to owner as you'd proposed.

As @mrshenli mentioned, this is only needed for debugging at the moment, so how about we make it an internal function or you'd prefer to expose it in API?

@rohan-varma : would this simple python implementation be sufficient for your/internal/external client purposes or you'd prefer to have a faster c++ one with perhaps some more fine tuning, e.g. 
* block/not block on ready rrefs
* potentially optimize for extra rpc round trip, etc

**Comment by rohan-varma** [comment]
I think the main use case I intended was for debugging, at least for now. If this API turns out to be pretty frequently used by our users and we find use cases where speeding it up will be benefecial, then we could look towards a C++ implementation, but this approach should be good for now.

**Comment by mrshenli** [comment]
It has been a while since last update, and this is needed for making RRef helper functions working with async execution. I am taking this issue over.
