### ISSUE TITLE
SummaryWriter.add_video() creates videos that don't match input tensors

### ISSUE THREAD

**Issue by RylanSchaeffer** [pytorch/pytorch#33226]
## 🐛 Bug
I’m trying to create a video by generating a sequence of 500 matplotlib plots, converting each to a numpy array, stacking them and then passing them to a `SummaryWriter()`'s `add_video()`. When I do this, the colorbar is converted from colored to black & white, and only a small number (~3-4) of the matplotlib plots comprise the video. I confirmed that my numpy arrays are correct by using them to recreate the matplotlib figure.

## To Reproduce

See the comment below for a minimal working example.

## Expected behavior

The video should loop over each frame in the sequence (length 500). Instead, only a few frames are displayed.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.9
 - CUDA/cuDNN version: NA

**Comment by RylanSchaeffer** [comment]
Here's a minimal working example:

```
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch.utils.tensorboard import SummaryWriter


tensorboard_writer = SummaryWriter()
print(tensorboard_writer.get_logdir())


def fig2data(fig):

    # draw the renderer
    fig.canvas.draw()

    # Get the RGB buffer from the figure
    data = np.frombuffer(fig.canvas.tostring_rgb(), dtype=np.uint8)
    data = data.reshape(fig.canvas.get_width_height()[::-1] + (3,))
    return data


size = 500
x = np.random.uniform(0, 2., size=500)
y = np.random.uniform(0, 2., size=500)
trajectory_len = len(x)
trajectory_indices = np.arange(trajectory_len)
width, height = 3, 2

# tensorboard takes video of shape (B,C,T,H,W)
video_array = np.zeros(
    shape=(1, 3, trajectory_len, height*100, width*100),
    dtype=np.uint8)

for trajectory_idx in trajectory_indices:

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(width, height),
        gridspec_kw={'width_ratios': [1, 0.05]})
    fig.suptitle('Example Trajectory')
    # plot the first trajectory
    sc = axes[0].scatter(
        x=[x[trajectory_idx]],
        y=[y[trajectory_idx]],
        c=[trajectory_indices[trajectory_idx]],
        s=4,
        vmin=0,
        vmax=trajectory_len,
        cmap=plt.cm.jet)

    axes[0].set_xlim(-0.25, 2.25)
    axes[0].set_ylim(-0.25, 2.25)

    colorbar = fig.colorbar(sc, cax=axes[1])
    colorbar.set_label('Trajectory Index Number')

    # extract numpy array of figure
    data = fig2data(fig)

    # UNCOMMENT IF YOU WANT TO VERIFY THAT THE NUMPY ARRAY WAS CORRECTLY EXTRACTED
    # plt.show()
    # fig2 = plt.figure()
    # ax2 = fig2.add_subplot(111, frameon=False)
    # ax2.imshow(data)
    # plt.show()

    # close figure to save memory
    plt.close(fig=fig)

    video_array[0, :, trajectory_idx, :, :] = np.transpose(data, (2, 0, 1))

# tensorboard takes video_array of shape (B,C,T,H,W)
tensorboard_writer.add_video(
    tag='sampled_trajectory',
    vid_tensor=torch.from_numpy(video_array),
    global_step=0,
    fps=4)

print('Added video')

tensorboard_writer.close()

```

**Comment by zhangguanheng66** [comment]
Have you checked `vid_tensor` after converting numpy array to torch tensor?

**Comment by RylanSchaeffer** [comment]
@zhangguanheng66 yes. `vid_tensor` has type `torch.uint8` with min value 0 and max value 255, per the documentation.

**Comment by RylanSchaeffer** [comment]
What else would you recommend checking?

**Comment by RylanSchaeffer** [comment]
@zhangguanheng66 when you run my minimal example above, what do you see?

**Comment by zhangguanheng66** [comment]
I'm able to run the code snippet and print out "Added video" without complaint.

**Comment by RylanSchaeffer** [comment]
Yes, the code runs fine. My question is whether the video, when visualized,
makes sense. Do you see a sequence of 500 random dots?

**Comment by RylanSchaeffer** [comment]
My issues isn't that any error emerges - my issues is that the video's
content does not match the input tensor.

**Comment by RylanSchaeffer** [comment]
@zhangguanheng66 any updates?

**Comment by RylanSchaeffer** [comment]
@zhangguanheng66 bump

**Comment by lanpa** [comment]
@RylanSchaeffer Hi, Just happened to see this post and I have reproduced the issue. Have you solved the problem already?

**Comment by RylanSchaeffer** [comment]
Nope. And I haven't haerd from @zhangguanheng66 . To be honest, I'm unsure he understood the problem.

**Comment by lanpa** [comment]
@RylanSchaeffer The dimension of the video tensor should be (N,T,C,H,W) whereas your comment says (B,C,T,H,W).

The working fix:
```
video_array = np.zeros(
    shape=(1, trajectory_len, 3, height*100, width*100),
    dtype=np.uint8)
video_array[0, trajectory_idx, :, :, :] = np.transpose(data, (2, 0, 1))
```

**Comment by RylanSchaeffer** [comment]
Beautiful! Thank you for catching my mistake :)

**Comment by daniel-bogdoll** [comment]
Hey @RylanSchaeffer , I have a quick question regarding your usage of add_video. I'm basically trying the same, but in my TensorBoard only images are shown. How did you view the videos?

**Comment by RylanSchaeffer** [comment]
I'm afraid I don't remember :(
