### ISSUE TITLE
ImportError: DLL load failed: The operating system cannot run %1

### ISSUE THREAD

**Issue by Jreyno40** [pytorch/pytorch#33223]
Hi all. I've tried a lot of different things and I have no idea why this isn't working. All google-able solutions discuss conda, which I'm not using. I'm really at a loss for how to move forward.

## Issue description

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

## Code example

Literally just import torch after installing it. I've tried python 3.6.2 & 3.6.8. It works on one windows 10 install, but not on another.

```
python
import torch
```

## System Info
---
python collect_env.py
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 441.87
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.2.0+cu92
[pip3] torchvision==0.4.0+cu92
[conda] Could not collect
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): N/A
- OS: Windows 10
- PyTorch version: 1.2.0
- Python version: 3.6.8 & 3.6.2 (tried both)
- CUDA/cuDNN version: 10.0
- GPU models and configuration: GTX 1070
- GCC version (if compiling from source): N/A
- CMake version: N/A
- Versions of any other relevant libraries: N/A

cc @peterjc123

**Comment by peterjc123** [comment]
Please use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and use the filter to capture logs for executable name `python.exe`. After that, please post the full log here.

**Comment by Jreyno40** [comment]
Thanks for the help! Here's the generated log file (.pml format - github required it be zipped). 
[Logfile.zip](https://github.com/pytorch/pytorch/files/4194992/Logfile.zip)

**Comment by peterjc123** [comment]
Would you please remove `C:\Windows\System32\libiomp5md.dll` and try again?

**Comment by Jreyno40** [comment]
That fixed it! How did that fix it? 👍

**Comment by peterjc123** [comment]
That dll in the system directory is preferred over the one in our package. So removing that conflicting dll resolves this problem.

**Comment by inikishev** [comment]
Getting the same issue, but I do not have libiomp5.dll in my windows32. Noticed this happened after I installed pygmo, which did this:
```
The following packages will be DOWNGRADED:

  boost-cpp                               1.85.0-ha5ead02_4 --> 1.84.0-ha5ead02_6
  libboost                                1.85.0-h444863b_4 --> 1.84.0-h444863b_6
  libboost-devel                          1.85.0-h91493d7_4 --> 1.84.0-h91493d7_6
  libboost-headers                        1.85.0-h57928b3_4 --> 1.84.0-h57928b3_6
  pybind11-abi                                 5-hd3eb1b0_0 --> 4-hd3eb1b0_1
```
