### ISSUE TITLE
What's the difference between the implementation details of batch_norm1d, batch_norm2d and batch_norm3d?

### ISSUE THREAD

**Issue by huang229** [pytorch/pytorch#33231]
I have looked at all the header files and scripts related to batch_norm in the python source code (c + + / C). But there is no difference between 1D, 2D and 3D implementations. I think the dimensions are different. In order to consider the calculation efficiency, the calculation method should be different.

**Comment by SsnL** [comment]
There is no difference up to the kernel/cudnn call, which then actually does dimension dependent things. The difference in API is due to historic reasons.
