### ISSUE TITLE
HTTP Error 403: Forbidden, when using pretrained models

### ISSUE THREAD

**Issue by RashmiHC** [pytorch/pytorch#33234]
## To Reproduce

1. Instantiate a pre-trained model using torchvision

import torchvision
model = torchvision.models.resnet18(pretrained=True)
## Expected behavior

model instantiated with weights downloaded from "https://download.pytorch.org/models/resnet18-5c106cde.pth"
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): -
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0/7
 - GPU models and configuration: Nvidia Geforce 920m
 - Any other relevant information:

**Comment by ptrblck** [comment]
Could you rerun the code now?
We had some server issues as explained [here](https://discuss.pytorch.org/t/loading-pretrained-resnet-on-google-colab-fails-with-http-403-forbidden/69427/7?u=ptrblck), which should be resolved now.

I just verified that I'm able to download checkpoints from torch hub again.

**Comment by zhangguanheng66** [comment]
The problem should be resolved. Feel free to reopen the issue if you still have the problem.

**Comment by jarlva** [comment]
Getting 403 again. using wget it will start and at some point kick out:
`wget  https://conda.anaconda.org/pytorch/win-64/pytorch-1.5.0-py3.7_cuda102_cudnn7_0.tar.bz2`

HTTP request sent, awaiting response... 403 Forbidden
2020-05-26 13:10:29 ERROR 403: Forbidden.
