### ISSUE TITLE
ONNX exporter is not raising an error if non-ONNX ops are exported

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3324]
In an effort to make it easier to do https://github.com/ezyang/pytorch/issues/241 the exporter now simply passes an operator through unchanged if it doesn't understand. But that means you can end up with 'expand' in the final exported output; that's not good! Add a pass to actually check everything is OK at the end.

**Comment by apaszke** [comment]
It was like this, because we used the ONNX pass to convert things to internal JIT format (and having unknown ops was ok). We can make the pass stricter now

**Comment by ezyang** [comment]
Actually, I think it is a good idea for the pass not to fail immediately. Then we can tell the user about all unsupported ops all at once at the end.

**Comment by ezyang** [comment]
Implemented this in #3325
