### ISSUE TITLE
torch.argmax and torch.max output different indices

### ISSUE THREAD

**Issue by SamMuq** [pytorch/pytorch#33253]
## 🐛 Bug

I am implementing the torch.argmax function in a Classifier and discovered that when there are multiple elements that have the same max value, argmax and max operations output different indices. Here is an example from my script:

**torch.max**:  values=tensor([[0, 0, 0, 0]], device='cuda:0'), indices=tensor([[0, 0, 0, 0]], device='cuda:0'))

**torch.argmax**: tensor([[3, 3, 3, 3]], device='cuda:0')

## To Reproduce

1. Create a tensor with elements all equal to 0
2. Compare torch.argmax and torch.max output indices 
3. torch.max will output the first maximum element and torch.argmax does not.

**Comment by ptrblck** [comment]
This is expected behavior due to parallelization as explained [here](https://github.com/pytorch/pytorch/issues/32343#issuecomment-575737333).

**Comment by SamMuq** [comment]
> This is expected behavior due to parallelization as explained [here](https://github.com/pytorch/pytorch/issues/32343#issuecomment-575737333).

Thank you for clarifying.
