### ISSUE TITLE
TestCppExtensionAOT.test_cuda_extension is flaky on Windows

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#33270]
It seems that `test_cuda_extension (__main__.TestCppExtensionAOT)` test is flaky on Windows now, starting from https://github.com/pytorch/pytorch/pull/33084.
```
======================================================================
FAIL: test_cuda_extension (__main__.TestCppExtensionAOT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cpp_extensions_aot.py", line 67, in test_cuda_extension
    self.assertEqual(z, torch.ones_like(z))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 862, in assertEqual
    assertTensorsEqual(x, y)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 832, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: tensor(1.) not less than or equal to 1e-05 : 

----------------------------------------------------------------------
```
Instances of the failure:
https://app.circleci.com/jobs/github/pytorch/pytorch/4469204
https://app.circleci.com/jobs/github/pytorch/pytorch/4470030
https://app.circleci.com/jobs/github/pytorch/pytorch/4470035
https://app.circleci.com/jobs/github/pytorch/pytorch/4479604

cc @peterjc123 @ezyang @gchanan @zou3519

**Comment by peterjc123** [comment]
If it is only flaky when building cpp extensions with ninja, then maybe we should remove some conflicting compiler options. Otherwise, it may be sth related to CUDA.

**Comment by peterjc123** [comment]
Would you please disable this test first? @yf225

**Comment by yf225** [comment]
@peterjc123 Sounds great, I created a PR to disable it: https://github.com/pytorch/pytorch/pull/33282.

**Comment by peterjc123** [comment]
I believe sth related to CUDA is breaking. Because the test failures are starting to appear in some other sites.
