### ISSUE TITLE
[C++] Add strong wolfe line search to the LibTorch interface

### ISSUE THREAD

**Issue by chenzhekl** [pytorch/pytorch#33284]
## 🚀 Feature

Add the same strong wolfe line search option to the LibTorch interface as the Python counterpart.

https://pytorch.org/docs/master/optim.html

## Motivation

Unify the interface between Python and C++

## Pitch

Implement the strong wolfe line search algorithm and add a flag to the `LBFGSOptions` struct

## Additional context

cc @yf225

**Comment by yf225** [comment]
I believe this will be covered by @anjali411's work on C++ optimizers (https://github.com/pytorch/pytorch/issues/28440).

**Comment by yf225** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/34564.
