### ISSUE TITLE
Round to specified decimal place

### ISSUE THREAD

**Issue by TTitcombe** [pytorch/pytorch#33287]
## 🚀 Feature
`torch.round` to take an optimal argument which specifies the decimal place to which rounding should occur

## Pitch
`torch.round` should have the same functionality as `numpy.around`. Specifying a decimal place will round _up to_ that decimal place, using the same rounding strategy as `torch.round` currently uses. The default value of the decimal parameter should be 0 to keep current behaviour.
E.g.
```
>>> tensor = torch.tensor([0.1234, 0.1237])
>>>torch.round(tensor, decimals=3)
tensor([0.123, 0.124])
```

## Alternatives
You can use `numpy.around` on the tensor, but I assume this has some performance hit?

cc @yf225

**Comment by mruberry** [comment]
It appears this issue was miscategorized! Closing in favor of the new high priority https://github.com/pytorch/pytorch/issues/65908, which will address this.
