### ISSUE TITLE
segfaults on .numpy() on cuda tensor

### ISSUE THREAD

**Issue by ggoossen** [pytorch/pytorch#33300]
## To Reproduce

1. torch.zeros((7, ), device="cuda").numpy()

produces segfaults.

With stacktrace include raising the exception with message to call .cpu method:
https://our.intern.facebook.com/intern/diffusion/FBS/browse/master/fbcode/caffe2/torch/csrc/utils/tensor_numpy.cpp?commit=cea4fcd5898cf33ec83ebd2eac23eb035047fe27&lines=78-80

## Expected behavior

runtime error with message about having to call .cpu first.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): trunk
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by SsnL** [comment]
Post the trace somewhere that is publicly available please.

**Comment by pbelevich** [comment]
reproducible, crashes in TypeError c-tor

**Comment by mruberry** [comment]
#33612 should address this.
