### ISSUE TITLE
Need to support clone for per channel quantized tensor

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#33309]
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/QTensor.cpp#L160

reported in: https://discuss.pytorch.org/t/pretrained-quantized-models-export-to-onnx-fails/67334

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by ggeor84** [comment]
@jerryzh168 was wondering if you have any plans to fix this issue?
