### ISSUE TITLE
Picker should work for constants

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#33319]
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/pickler.cpp#L109
Right now it does not save constants?

cc @suo

**Comment by suo** [comment]
@jerryzh168, I thought this was added as part of constant serialization support? How are we preserving the constants on save/load today?

**Comment by driazati** [comment]
Constants that are primitive types / containers are saved as literals in the serialized code. For tensor constants, references to these are saved as `constants.c<tensor number>` and the data stored in `constants.pkl` as a tuple of tensors.

**Comment by jerryzh168** [comment]
Yeah, class constants are considered to be part of code, not part of the state of model instance. I see, then we don't need this.
