### ISSUE TITLE
"RuntimeError: geqrf: Lapack library not found in compile time" occured

### ISSUE THREAD

**Issue by imai-lm** [pytorch/pytorch#3332]
In calling `torch.nn.init.orthogonal`, the error like below has occurred.
```
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/init.py", line 328, in orthogonal
    orthogonal(tensor.data, gain=gain)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/init.py", line 342, in orthogonal
    q, r = torch.qr(flattened)
RuntimeError: geqrf: Lapack library not found in compile time
 at /workspace/pytorch/torch/lib/TH/generic/THLapack.c:237
```
I googled and checked it, but most of what I got was about torch7, not PyTorch. I also checked #199, and tried installing OpenBLAS and then PyTorch again, but it didn't work.
What is the problem? Any help would be appreciated.

**Comment by apaszke** [comment]
OpenBLAS is a BLAS, not LAPACK library (BLAS doesn't contain a lot of more complicated linear algebra algorithms like the QR decomposition required to use this initialization). Install a library implementing LAPACK interface and recompile PyTorch.

**Comment by Supe2015** [comment]
i meet the same problem, and i install a lapack library lapack.a in /usr/lib/ and recompile pytorch, but it doesn't work.

**Comment by jolinxql** [comment]
Same error. I use bash on windows. OpenBlas installed, pytorch recompiled. It happend when
```
>>> import torch
>>> A=torch.randn(1,3,3)
>>> A_LU = torch.btrifact(A)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: getrf : Lapack library not found in compile time
 at /mnt/d/xql/Source/OpenSrc/pytorch/aten/src/TH/generic/THLapack.cpp:140
```
