### ISSUE TITLE
windows10 + Vs2015,Compiling libtorch1.4 failed

### ISSUE THREAD

**Issue by HongShiKuan** [pytorch/pytorch#33333]
I downloaded the Release version of libtorch1.4, and built the project through cmake on win10, Vs2015.
When generating a solution, the following error is prompted. Has anyone encountered this kind of error? Greatful! !! !! !!
![image](https://user-images.githubusercontent.com/45912889/74502692-44845c80-4f29-11ea-8b5e-1cf363d2a623.png)

The content of my cpp file is as follows！！！！
![image](https://user-images.githubusercontent.com/45912889/74502469-937dc200-4f28-11ea-8f43-b81a9de02fe3.png)

The content of CMakelists.txt is as follows! !! !! !!
![image](https://user-images.githubusercontent.com/45912889/74502491-ad1f0980-4f28-11ea-9dad-b3d4d78bd34e.png)

The cmake instructions used when generating the Vs project are:cmake -DCMAKE_PREFIX_PATH=F:\0_change2.5D\target_tracking\libtorch\libtorch-win-shared-with-deps-1.4.0\libtorch -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" ..

**Comment by peterjc123** [comment]
PyTorch has migrated to use C++14. According to the [doc](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019) in MSDN, Visual Studio 2015 is not a supported compiler.
