### ISSUE TITLE
GPU is not utilized

### ISSUE THREAD

**Issue by manza-ari** [pytorch/pytorch#33335]
## 🐛 Bug

 I am implementing the following project: https://github.com/sinhasam/vaal
 and it is not using system's GPU. Kindly check main.py

## To Reproduce

1.
1.
1.
https://github.com/sinhasam/vaal

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @VitalyFedyunin @ngimel

**Comment by ptrblck** [comment]
Could you please create a topic in our [discussion board](https://discuss.pytorch.org/) with your system information (used GPU, NVIDIA driver) and how you installed PyTorch?

**Comment by manza-ari** [comment]
OK, I made it.

**Comment by agolynski** [comment]
Could you include a link to your post? 

I found a similar post 
https://discuss.pytorch.org/t/no-gpu-utilization-although-cuda-seems-to-be-activated/40964

In my experience this also could be due to other bottlenecks: CPU, disk (e.g. utilized by decoder/data loader).

**Comment by VitalyFedyunin** [comment]
I think we can close this one as discussion moved to the forum. Feel free to reopen if you need to submit a bug.
