### ISSUE TITLE
test_memory_stats fail on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#33331]
## 🐛 Bug

```pytb
======================================================================
FAIL: test_memory_stats (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cuda.py", line 278, in test_memory_stats
    for _ in self._test_memory_stats_generator(self):
  File "test_cuda.py", line 207, in _test_memory_stats_generator
    assert_change(0, empty_cache=True)
  File "test_cuda.py", line 172, in assert_change
    self.assertEqual(new_m, last_m_arr[0])
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 893, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 3072 not less than or equal to 1e-05 : 
```

## To Reproduce

1. python setup.py install
2. cd test && python run_test.py -i cuda

## Expected behavior

Test passes.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): source
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla P4
 - Any other relevant information:

## Additional context

BTW, looks like sth related to CUDA is breaking. It should be related to some changes in last two days.
Test failure in torchvision:
https://app.circleci.com/jobs/github/pytorch/vision/88617

cc @peterjc123

**Comment by peterjc123** [comment]
cc @ezyang

**Comment by ezyang** [comment]
cc @SsnL. I'm OK with disabling this on Windows for now.

**Comment by ezyang** [comment]
but it kind of looks like the errors started with #26512

**Comment by ezyang** [comment]
cc @mcarilli

**Comment by peterjc123** [comment]
@ezyang Yeah, looks like that's cause because the CIs are fine after reverting it.
