### ISSUE TITLE
Issue with longe sequence

### ISSUE THREAD

**Issue by blizda** [pytorch/pytorch#33345]
## 🐛 Bug

I try to train Reformer in Pytorch implementation from here

https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch

using this script

https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py

only change I made - add 16 bit model training with model.half()

I set batch size to 16 and sequence lenght - 24960

after I tried to start training I get this error: 

RuntimeError                              Traceback (most recent call last)
<ipython-input-11-9219ded2be62> in <module>
     28         loss = loss_fn(output, labels)
     29         optimizer.zero_grad()
---> 30         loss.backward()
     31         optimizer.step()
     32         running_loss += loss.item()

/opt/anaconda/envs/train_torch/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    193                 products. Defaults to ``False``.
    194         """
--> 195         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    196 
    197     def register_hook(self, hook):

/opt/anaconda/envs/train_torch/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     97     Variable._execution_engine.run_backward(
     98         tensors, grad_tensors, retain_graph, create_graph,
---> 99         allow_unreachable=True)  # allow_unreachable flag
    100 
    101 

RuntimeError: index_put_ with accumulation is not supported on large tensors, number of source elements =12189265920file a support request on github

if I switch batch size to 2, training is going fine

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] reformer-pytorch==0.12.7
[pip] revtorch==0.2.4
[pip] torch==1.4.0
[pip] torchvision==0.4.2
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] reformer-pytorch          0.12.7                   pypi_0    pypi
[conda] revtorch                  0.2.4                    pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.4.2           cpu_py37h9ec355b_0

cc @ngimel

**Comment by agolynski** [comment]
Seems like this limitation was introduced here:
https://github.com/pytorch/pytorch/pull/20557

@ngimel
