### ISSUE TITLE
Behavior of view on out= functions

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#33351]
When I fix test failures on XLA backend, I found this example (not in our test) giving surprising results. 

```
In [1]: import torch

In [2]: a = torch.rand(4, 4)

In [3]: base = torch.zeros_like(a)

In [4]: first_row = a[0]

In [5]: torch.pow(base, 2, out=first_row)
Out[5]:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]: a
Out[6]:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
```
So as a user I only know `first_row` shares the first row with `a`. But when we update `first_row`, we actually update the whole tensor of `a`. 
I was expecting all rows of `a` except the first to remain the old values instead of 0. 

I kinda understand this is an outcome of `first_row` shares storage with `a` so when we do the update we just did it inplace. 
But I want to argue that the current behavior might be bad:
- Updating tensor `first_row` which is a tensor of size 4, affected all 16 elements in its base tensor. This doesn't look right and can cause unexpected changes. 

Also want to add that the current behavior, if implemented on XLA backend (graph based view), requires view tensor to have full knowledge of all its base tensors, which element of storage it touched during chains of views, which can complicate the problem a lot. In fact I ran out of ideas how to match this behavior on XLA end, thus opening an issue here. :P 
cc: @ezyang @albanD @gchanan for thoughts. 

cc @ezyang @SsnL @gchanan @albanD @zou3519 @gqchen

**Comment by gchanan** [comment]
IMO the thing that is wrong is that resize the out argument (especially if it's a view).

**Comment by ailzhang** [comment]
Btw I had a discussion with @albanD on chat, he introduced the background and motivations behind this, here's a brief summary:
1. **It's a known issue of using `resize_` (`out=` funcs calls `resize_`).**
Calling `resize_` on view might do a fake resize and expand to the existing storage shared by other tensors. Thus it might update other tensors accidentally.
2. **Why do we have this `resize_` behavior?** 
The original goal for `resize_` is to have buffer Tensor that you can resize and that are very cheap.
In particular, if you scale them up and down during training, you don't want to reallocate for every growth.
Historically it was used a lot in lua torch
On GPU it is useless as the caching allocator will be as fast by just deleting the Tensor and re-allocating.
On CPU there might be some gain as we use generic allocators that might not be very well tailored for our use case (of we run the same alloc/dealloc pattern in a for loop)
3. **Why does `out=` funcs use `resize_`?**
This is useful when we want to reuse the same existing buffer for outputs. 
And it allows optimizing memory usage:
```
res = torch.tensor(2, 100)
foo(a, out=res[0])
bar(b, out=res[1])
return res
```
v.s.
```
out1 = foo(a)
out2 = bar(b)
return torch.stack([out1, out2], 0)
```
Note that the second snippet has 2x more peak memory usage. 

4. **Can't we use inplace ops instead of `out=`?**
Yes for ops like `pow`, using `pow_` is preferred over `pow(.., out=)`. 
But for ops like `max` and `min` where having an inplace ops is weird, `out` still has the advantage. 
5. **Proposed BC-breaking change: enforce exact shape match for `out=` funcs**
There're a few benefits we can get from this proposal:
-  For users who want to get the benefit of reusing buffers, they can still get it for free when shape matches. If shape doesn't match, they'll need to call `resize_` before `out=` to make sure they know the risk.
- Not all ops know output shape beforehand, e.g. `nonzero`. But in case of `nonzero` where output size varies, reusing buffer undertakes the risk of wrong result in (1), while getting some benefit of speed. Doesn't seem to be worth it.
- We can support autograd for `out=` if shape matches! This is a feature request from https://github.com/pytorch/pytorch/issues/29378. 
Thanks for @albanD for providing examples and background! Please feel free to add if I'm missing something!

**Comment by gchanan** [comment]
I think one open question is what we do with 0 element tensors.  We often create 0 element tensors internally and then pass them to the out variant, so we can just use the out variant handling.  I think this violates NumPy semantics though (can you check @ailzhang?).

**Comment by ailzhang** [comment]
@gchanan You are right. Numpy doesn't allow resizing for `out=`, the only exception when it allows shape mismatch is broadcast. 
```
In [18]: a = np.arange(3).reshape(1, 3)

In [20]: b = np.arange(3).reshape(3, 1)

In [21]: np.add(a, b, out=np.arange(9).reshape(3, 3))
Out[21]:
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [22]: np.add(a, b, out=np.array([]))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-e9a0f7478979> in <module>
----> 1 np.add(a, b, out=np.array([]))

ValueError: operands could not be broadcast together with shapes (3,3) (3,3) (0,)
```
I think matching Numpy behavior for `out=` functions makes sense. cc: @mruberry ;) 
For all our internal uses of `out=` with empty tensor, we can change those I guess? `nonzero` might be a little tricky but still doable.

**Comment by gchanan** [comment]
that's not a shape mismatch, that's the shape of the result, right?

**Comment by ailzhang** [comment]
Aha yeah shape of out should always match result. Broadcasting is not an issue here.

**Comment by mruberry** [comment]
I think https://github.com/pytorch/pytorch/issues/41027 will resolve this? What do you think, @ailzhang?

**Comment by mruberry** [comment]
Closing in favor of #41027.
