### ISSUE TITLE
How do i build libtorch without cuda?

### ISSUE THREAD

**Issue by guapizyq** [pytorch/pytorch#33372]
my computer have cuda env but i want to build libtorch without cuda
i try this cmd : NO_CUDA=1 python ../tools/build_libtorch.py
but it alway be sth like libcaffe2_detectron_ops_gpu
how do i make sure that the cuda or gpu version is no work so that i can build libtorch with cpu only

**Comment by peterjc123** [comment]
What about `USE_CUDA=0 python ../tools/build_libtorch.py`

**Comment by guapizyq** [comment]
> What about `USE_CUDA=0 python ../tools/build_libtorch.py`?

OK, i will try

**Comment by guapizyq** [comment]
> What about `USE_CUDA=0 python ../tools/build_libtorch.py`?

it seems work  thanks
