### ISSUE TITLE
Is torch.nn.Sequential able to take a list as the input?

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#33398]
Hi, guys,
I am working on reimplementing the DeepLabV3+ these days,
and I am thinking about whether the torch.nn.Sequential can take a list of modules as an input?
I think this would be an awesome feature!

Any answer or idea will be appreciated!

**Comment by peterjc123** [comment]
The constructor of `torch.nn.Sequential` accepts an `OrderedDict` object and that of `torch.nn.ModuleList` accepts a `list` object. Please see the example [here](https://pytorch.org/docs/stable/nn.html#sequential).

**Comment by songyuc** [comment]
@peterjc123 , thanks for your reminder,
but I think it will be more convenient if `torch.nn.Sequential` can take a `list` object as input.
Because, sometime, we may want to use a loop to initialize our modules, and with `list.append`, it will provide an easy way to construct a network with repeated modules.

**Comment by josh-gleason** [comment]
@songyuc You can [unpack a list into multiple positional arguments](https://docs.python.org/3.7/tutorial/controlflow.html#unpacking-argument-lists) using `torch.nn.Sequential(*list_of_modules)`

**Comment by ptrblck** [comment]
For completeness: related discussion in the [forum](https://discuss.pytorch.org/t/is-torch-nn-sequential-able-to-take-a-list-as-the-input/69933/2?u=ptrblck).

**Comment by songyuc** [comment]
@josh-gleason , hi, Josh,
your proposal is great, thanks!
