### ISSUE TITLE
name 'StochasticFunction' is not defined

### ISSUE THREAD

**Issue by akolishchak** [pytorch/pytorch#3340]
Getting this error:
 File torch/autograd/variable.py", line 209, in reinforce
    if not isinstance(self.grad_fn, StochasticFunction):
NameError: name 'StochasticFunction' is not defined

The issue seems introduced by this commit:
https://github.com/pytorch/pytorch/commit/d9b89a352c4ceeff24878f4f5321e16f059e98c3#diff-aaab4dd580a0c7e992b97c4649b21d9f

**Comment by elbaro** [comment]
It seems like .reinforce() is going away in favor of torch.distributions. Can someone confirm this?

http://pytorch.org/docs/master/distributions.html?highlight=distributions#module-torch.distributions

**Comment by colesbury** [comment]
Yes, StochasticFunction is being removed. If your building from master, please you the `torch.distributions` package instead.

**Comment by akolishchak** [comment]
If I understand correctly it was easier with reinforce(), required just saving actual samples for backward pass. Now we need to save samples + Distribution object, e.g.:
`
probs = network(input)
m = Multinomial(probs)
action = m.sample()
`
Both `m` and `action` should be saved for backward pass. The saving is typically required for backup of reward from the last action in an RL episode.

**Comment by soumith** [comment]
@akolishchak yes that is correct.
