### ISSUE TITLE
libtorch `to(at::kCUDA)` operation is VERY SLOW?

### ISSUE THREAD

**Issue by FantasyJXF** [pytorch/pytorch#33414]
* CentOS 7.3
* Tesla P40
* libtorch 1.2.0 + cu100

When I test the `to(at::kCUDA)` operation, it consume a long time, like more than 4 secounds with create a tensor only needs `1e-5` seconds. 

My code is as follows.

```
#include <torch/torch.h>
#include <iostream>
#include <chrono>

using namespace std;
using namespace chrono;

int main() {
    std::cout <<"HAS GPU? " << torch::cuda::is_available() << std::endl;
    
    auto time_start = system_clock::now();
    torch::Tensor tensor = torch::rand({300,300,3});
    auto time1 = system_clock::now();
    auto duration1 = duration_cast<microseconds>(time1 - time_start);
    cout << "Create the tensor costs "
         << double(duration1.count()) * microseconds::period::num / microseconds::period::den
         << "s" << endl;
    
    tensor = tensor.to(at::kCUDA);
    
    auto time_end = system_clock::now();
    auto duration2 = duration_cast<microseconds>(time_end - time1);
    cout << "Move tensor to CUDA costs "
         << double(duration2.count()) * microseconds::period::num / microseconds::period::den
         << "s" << endl;
}
```

Output:
```
HAS GPU? 1
Create the tensor costs 0.002385s
Move tensor to CUDA costs 4.13141s
```

**Comment by FantasyJXF** [comment]
What's more, move the tensor from CUDA to CPU use `to(at::kCPU)` is quite fast

**Comment by FantasyJXF** [comment]
I think there might need a warmup the first time using GPU, since I found it's very fast the next times move the tensors between tensors.


<img width="333" alt="QQ20200217-0" src="https://user-images.githubusercontent.com/16235526/74642112-5bd37c00-51ad-11ea-9a2f-cf38648c1c2f.png">

**Comment by jzw0025** [comment]
Did you have any clue about this for speeding up the data transferring using to(torch::kCPU)?

**Comment by gemfield** [comment]
Your code is incorrect, check https://zhuanlan.zhihu.com/p/363319763 and https://github.com/DeepVAC/libdeepvac/issues/30
