### ISSUE TITLE
torch.where segfaults on mixed cpu and cuda arguments

### ISSUE THREAD

**Issue by ggoossen** [pytorch/pytorch#33422]
## To Reproduce

torch.where(torch.rand(16, device="cpu") > 0.7, torch.rand(16, device="cpu"), torch.rand(16, device="cuda"))

Produces segfault:
 *** Signal 11 (SIGSEGV) (0x7f8d2b200000) received by PID 234776 (pthread TID 0x7f8dfcc18000) (linux TID 234776) (code: invalid permissions for mapped object), stack trace: ***
>     @ 000000001eaf4df9 folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t*, void*)
>     @ 0000000000000000 (unknown)   
>     @ 000000001b319397 void c10::function_ref<void (char**, long const*, long)>::callback_fn<at::native::(anonymous namespace)::cpu_kernel<at::native::(anonymous namespace)::where_kernel_impl(at::TensorIterator&, c10::ScalarType)::$_0::operator()() const::{lambda()#4}::operator()
() const::{lambda(bool, float, float)#1}>(at::TensorIterator&, at::native::(anonymous namespace)::where_kernel_impl(at::TensorIterator&, c10::ScalarType)::$_0::operator()() const::{lambda()#4}::operator()() const::{lambda(bool, float, float)#1}&&)::{lambda(char**, long const*, long
)#1}>(long, char**, long const*, long)           
>     @ 000000001b34e461 void c10::function_ref<void (char**, long const*, long, long)>::callback_fn<at::TensorIterator::for_each(c10::function_ref<void (char**, long const*, long)>)::$_5>(long, char**, long const*, long, long)
>     @ 000000001b347b0d at::TensorIterator::serial_for_each(c10::function_ref<void (char**, long const*, long, long)>, at::Range) const
>     @ 000000001b3476a3 at::TensorIterator::for_each(c10::function_ref<void (char**, long const*, long)>)
>     @ 000000001b310b15 at::native::(anonymous namespace)::where_kernel_impl(at::TensorIterator&, c10::ScalarType)
>     @ 000000001b309c52 at::native::_s_where(at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 000000001b3ec3b4 at::TypeDefault::_s_where(at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 0000000016354b07 c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&, at::Tensor const&), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&> >, a
t::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 000000000c867de7 at::Tensor c10::KernelFunction::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&, at::Tensor const&) const
>     @ 000000000c867cb6 at::Tensor c10::Dispatcher::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&, at::Tensor const&) const
>     @ 0000000016700b22 torch::autograd::VariableType::(anonymous namespace)::_s_where(at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 0000000016354b07 c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, at::Tensor const&, at::Tensor const&), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&> >, a
t::Tensor (at::Tensor const&, at::Tensor const&, at::Tensor const&)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 000000000c867de7 at::Tensor c10::KernelFunction::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&, at::Tensor const&) const
>     @ 000000000c867cb6 at::Tensor c10::Dispatcher::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&, at::Tensor const&) const
>     @ 000000001b309384 at::native::where(at::Tensor const&, at::Tensor const&, at::Tensor const&)
>     @ 000000001b3ebae4 at::TypeDefault::where(at::Tensor const&, at::Tensor const&, at::Tensor const&)

## Expected behavior

Raise an error about not allowing mixed cpu and cuda tensors.

## Environment

 - PyTorch Version (e.g., 1.0): trunk

**Comment by VitalyFedyunin** [comment]
We are not supporting mixed location arguments, operator should error out gracefully instead.

**Comment by VitalyFedyunin** [comment]
I'm closing because in pytorch nightly ( >= 1.4.0) we actually do such check:
```
In [182]: torch.where(torch.rand(16, device="cpu") > 0.7, torch.rand(16, device="cpu"), torch.rand(16, device="cuda"))                                                                                                                        
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-182-15caa7552506> in <module>
----> 1 torch.where(torch.rand(16, device="cpu") > 0.7, torch.rand(16, device="cpu"), torch.rand(16, device="cuda"))

RuntimeError: Expected tensor to have CUDA Backend, but got tensor with CPU Backend (while checking arguments for CUDA_tensor_apply4)
```
