### ISSUE TITLE
Matrix dot product returns wrong value on some random elements

### ISSUE THREAD

**Issue by Kenisy** [pytorch/pytorch#33421]
## 🐛 Bug

Matrix dot product returns wrong value on some random elements.

## To Reproduce

1. Download 2 attached tensors [tensors.zip](https://github.com/pytorch/pytorch/files/4214412/tensors.zip)
2. Run this code with those tensors
```
import torch
torch.set_printoptions(precision=20)
tensor1 = torch.load('tensor1.t')
tensor2 = torch.load('tensor2.t')
result = tensor1 @ tensor2
print(result[6, 0]) # incorrect
print(sum(tensor1[6] * tensor2[:, 0])) # correct
print(result[4, 0]) # correct
```
3. This is the result I got:
```
tensor(-0.00154018448665738106)
tensor(-0.00154018541797995567)
tensor(-0.00154018541797995567)
```

## Expected behavior

result[6, 0] should returns tensor(-0.00154018541797995567) like result[4, 0]

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] pytorch                   1.4.0               py3.7_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.5.0                  py37_cpu  [cpuonly]  pytorch

## Additional context

This bug doesn't occur on google colab, I tried create new conda environment or used a difference laptop but the bug still happened.

**Comment by VitalyFedyunin** [comment]
Please refer https://discuss.pytorch.org/t/numerical-difference-in-matrix-multiplication-and-summation/28359 for the answer.
