### ISSUE TITLE
Sequential and ModuleList call add_module() with integer keys

### ISSUE THREAD

**Issue by ozancaglayan** [pytorch/pytorch#3343]
Hello,

In the case where these classes sequentially append the received elements with `add_module(str(idx), value)`, the modules become inaccessible since a variable name starting with a number is forbidden in Python.

I attached a patch that names the modules as `module_%d` instead of just numbers.

```python
In [17]: foo = nn.Sequential(*[nn.Linear(10, 100), nn.Linear(100, 5)])

In [18]: hasattr(foo, '0')
Out[18]: True

In [19]: foo.0
  File "<ipython-input-19-a18cb4ba7f54>", line 1
    foo.0
        ^
SyntaxError: invalid syntax
```

**Comment by colesbury** [comment]
Use `foo[0]` syntax for Sequential and ModueList.

**Comment by ozancaglayan** [comment]
possible but the attributes are there and they are obviously shown in autocompletion suggestions in IPython for example and when you try to access it you got an error because their naming does not conform to Python rules.

**Comment by colesbury** [comment]
Perhaps we should exclude them from `Module.__dir__`
