### ISSUE TITLE
CUDA 10.1 for Windows under C++ API not working

### ISSUE THREAD

**Issue by fmigneault** [pytorch/pytorch#33435]
## ❓ Questions and Help

I have successfully built LibTorch for C++ API under Windows with CUDA 10.1.

Although CUDA seems to be enabled and configured correctly in CMake, and `torch_cuda.lib` is correctly inserted into the linker directives of `torch.lib`, I still get a message saying it is not linked with CUDA support in my test app.

``` c++
try {    
    std::cout << torch::cuda::is_available() << std::endl;
    torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
}
catch (exception& ex) {
    std::cout << ex.what() << std::endl;
}
```

```
TestApp.exe
0
PyTorch is not linked with support for cuda devices (getDeviceGuardImpl at E:\develop\torch\torch\c10/core/impl/DeviceGuardImplInterface.h:216)
```

`torch` config in VS2019: 
![image](https://user-images.githubusercontent.com/19194484/74712816-3b2f1480-51f5-11ea-8b8d-d80fc472dc2d.png)

CMAKE config output : 
```
******** Summary ********
General:
  CMake version         : 3.16.4
  CMake command         : C:/Program Files/CMake/bin/cmake.exe
  System                : Windows
  C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
  C++ compiler id       : MSVC
  C++ compiler version  : 19.24.28316.0
  BLAS                  : MKL
  CXX flags             : /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental
  Build type            : Debug
  Compile definitions   : ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;_CRT_SECURE_NO_DEPRECATE=1;WIN32_LEAN_AND_MEAN;MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS
  CMAKE_PREFIX_PATH     : E:/develop/cudnn/v10.1;E:/develop/cuda/v10.1
  CMAKE_INSTALL_PREFIX  : E:/develop/torch/torch-1.5.0a-source-cuda-10.1/install/debug

  TORCH_VERSION         : 1.1.0
  CAFFE2_VERSION        : 1.1.0
  BUILD_CAFFE2_MOBILE   : ON
  USE_STATIC_DISPATCH   : OFF
  BUILD_BINARY          : OFF
  BUILD_CUSTOM_PROTOBUF : ON
    Link local protobuf : ON
  BUILD_DOCS            : OFF
  BUILD_PYTHON          : OFF
  BUILD_CAFFE2_OPS      : ON
  BUILD_SHARED_LIBS     : ON
  BUILD_TEST            : OFF
  BUILD_JNI             : OFF
  INTERN_BUILD_MOBILE   : 
  USE_ASAN              : OFF
  USE_CUDA              : ON
    CUDA static link    : OFF
    USE_CUDNN           : ON
    CUDA version        : 10.1
    cuDNN version       : 7.6.4
    CUDA root directory : E:/develop/cuda/v10.1
    CUDA library        : E:/develop/cuda/v10.1/lib/x64/cuda.lib
    cudart library      : E:/develop/cuda/v10.1/lib/x64/cudart_static.lib
    cublas library      : E:/develop/cuda/v10.1/lib/x64/cublas.lib
    cufft library       : E:/develop/cuda/v10.1/lib/x64/cufft.lib
    curand library      : E:/develop/cuda/v10.1/lib/x64/curand.lib
    cuDNN library       : E:/develop/cudnn/v10.1/lib/x64/cudnn.lib
    nvrtc               : E:/develop/cuda/v10.1/lib/x64/nvrtc.lib
    CUDA include path   : E:/develop/cuda/v10.1/include
    NVCC executable     : E:/develop/cuda/v10.1/bin/nvcc.exe
    NVCC flags          : -Xcompiler /w -w;-DONNX_NAMESPACE=onnx_torch;-gencode;arch=compute_61,code=sm_61;-Xcudafe;--diag_suppress=cc_clobber_ignored;-Xcudafe;--diag_suppress=integer_sign_change;-Xcudafe;--diag_suppress=useless_using_declaration;-Xcudafe;--diag_suppress=set_but_not_used;-Xcompiler;-MD$<$<CONFIG:Debug>:d>;--expt-relaxed-constexpr;--expt-extended-lambda;-Xcompiler /wd4819 -Xcompiler /wd4503 -Xcompiler /wd4190 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4275 -Xcompiler /wd4522;-Wno-deprecated-gpu-targets;--expt-extended-lambda;-gencode;arch=compute_61,code=sm_61;-DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
    CUDA host compiler  : $(VCInstallDir)Tools/MSVC/$(VCToolsVersion)/bin/Host$(Platform)/$(PlatformTarget)
    USE_TENSORRT        : OFF
  USE_ROCM              : OFF
  USE_EIGEN_FOR_BLAS    : ON
  USE_FBGEMM            : OFF
  USE_FFMPEG            : OFF
  USE_GFLAGS            : OFF
  USE_GLOG              : OFF
  USE_LEVELDB           : OFF
  USE_LITE_PROTO        : OFF
  USE_LMDB              : OFF
  USE_METAL             : OFF
  USE_MKL               : OFF
  USE_MKLDNN            : ON
  USE_MKLDNN_CBLAS      : OFF
  USE_NCCL              : OFF
  USE_NNPACK            : OFF
  USE_NUMPY             : OFF
  USE_OBSERVERS         : ON
  USE_OPENCL            : OFF
  USE_OPENCV            : OFF
  USE_OPENMP            : ON
  USE_TBB               : OFF
  USE_PROF              : OFF
  USE_QNNPACK           : OFF
  USE_REDIS             : OFF
  USE_ROCKSDB           : OFF
  USE_ZMQ               : OFF
  USE_DISTRIBUTED       : OFF
  Public Dependencies  : Threads::Threads;caffe2::mkldnn
  Private Dependencies : cpuinfo;fp16;aten_op_header_gen;foxi_loader
```

CUDA info: 
```
deviceQuery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1080"
  CUDA Driver Version / Runtime Version          10.2 / 10.1
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8192 MBytes (8589934592 bytes)
  (20) Multiprocessors, (128) CUDA Cores/MP:     2560 CUDA Cores
  GPU Max Clock rate:                            1734 MHz (1.73 GHz)
  Memory Clock rate:                             5005 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.1, NumDevs = 1
Result = PASS
```

cc @peterjc123

**Comment by peterjc123** [comment]
Duplicate of https://github.com/pytorch/pytorch/issues/33415.

**Comment by fmigneault** [comment]
Specified fix https://github.com/pytorch/pytorch/issues/31611#issue-542332909 does not work.
I have tried both loading explicitly the DLL and also removing it completely for the directory, where my app does not even crash because of missing DLL. It seems the CUDA implementation is simply ignored.

Also, I do not encounter any link error as in #33415. The libraries compile and are all generated in the appropriate location, while CMake report `WITH_CUDA=1`. When compiling, all *.cu files do get processed. 

It just seems as if torch lib ignores that CUDA is there.

**Comment by peterjc123** [comment]
> Specified fix [#31611 (comment)](https://github.com/pytorch/pytorch/issues/31611#issue-542332909) does not work.

You mean you tried the following code, right?
```c++
try {
    LoadLibrary("torch_cuda.dll");    
    std::cout << torch::cuda::is_available() << std::endl;
    torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
}
catch (exception& ex) {
    std::cout << ex.what() << std::endl;
}
```
It is weird. Would you please whether it helps if it works if building the binary with CMake?
The steps are listed below.
1. Put `CMakeLists.txt` along with your C++ source file `test.cpp`
```cmake
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(test)

find_package(Torch REQUIRED)

add_executable(test test.cpp)
target_link_libraries(test "${TORCH_LIBRARIES}")

if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET test
                     POST_BUILD
                     COMMAND ${CMAKE_COMMAND} -E copy_if_different
                     ${TORCH_DLLS}
                     $<TARGET_FILE_DIR:test>)
endif (MSVC)
```
2. Run the following command
```cmd
mkdir build && cd build
cmake -G"Visual Studio 16 2019" -Ax64 -Tx64 -DCMAKE_PREFIX_PATH="/path/to/libtorch" ..
cmake --build . --config Debug
cd x64\Debug
test.exe
```

**Comment by fmigneault** [comment]
Yes, that code doesn't work even with explicit call `LoadLibrary("torch_cuda.dll");`
My test app was already generated by cmake.

I went ahead and tried loading all pieces one by one: 
```
    LoadLibraryA("ATen_cuda.dll");
    LoadLibraryA("c10_cuda.dll");
    LoadLibraryA("torch_cuda.dll");
    LoadLibraryA("torchvision.dll");

    try { 
	    std::cout << "CUDA:   " << torch::cuda::is_available() << std::endl;
        std::cout << "CUDNN:  " << torch::cuda::cudnn_is_available() << endl;
	    std::cout << "GPU(s): " << torch::cuda::device_count() << std::endl;
    } 
    catch (exception& ex) {
        std::cout << ex.what() << std::endl;
    }
    try { 
        std::cout << "List devices:" << std::endl; 
        for (size_t d = 0; d++; d <= static_cast<size_t>(c10::DeviceType::COMPILE_TIME_MAX_DEVICE_TYPES)) {
            std::cout << d << ": " << c10::impl::device_guard_impl_registry[d] << std::endl;
        }

	    torch::Tensor tensor = at::tensor({ -1, 1 }, at::kCUDA);
    }
    catch (exception& ex) {
        std::cout << ex.what() << std::endl;
    }
```
Which produces output: 
```
CUDA:   0
CUDNN:  0
GPU(s): 0
List devices:
Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library. (initCUDA at E:\develop\torch\torch\aten\src\ATen/detail/CUDAHooksInterface.h:63)
(no backtrace available)
``` 
So I used [Dependency Walker](http://dependencywalker.com/) to check `torch_cuda.dll` as suggested by the corresponding `ldd` tool in the message, which looks like follows: 

![image](https://user-images.githubusercontent.com/19194484/74778792-4b350b80-526a-11ea-8aee-3ef06e7cc659.png)

What I can see is that there isn't even a reference (even not a missing link) to `ATen_cuda.dll`.
Is a reference to it missing for Windows during the generation of `c10_cuda.dll`?

I will attempt finding corresponding options `-Wl,--no-as-needed` for Visual Studio to recompile and see what I get out of it, but I wonder if the issue is not due to missing link lower down in c10/aten stuff?

**Comment by fmigneault** [comment]
I have added the missing `nvToolsExt64_1.dll` and I'm now getting CUDA with 1 GPU available!
For anyone that could encounter similar issues, CMake's `find_package(CUDA)` doesn't help a lot to obtain all CUDA DLLs, but also nvToolsExt is not installed in the same location as the others by default.

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin`
vs
`C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64`

**Comment by Tiansong97** [comment]
I encountered this problem too. But I found nvToolsExt64_1.dll in libtorch\lib,and the error is 
Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library. (initCUDA at C:\w\b\windows\pytorch\aten\src\ATen/detail/CUDAHooksInterface.h:63)
(no backtrace available)
Can you give me some more details about how to solve this? Thx!

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/issues/37124#issuecomment-618142192

**Comment by LESSuseLESS** [comment]
The root cause is,

1. at::cuda::detail::CUDAHooks.cpp uses a static initializer "REGISTER_CUDA_HOOKS(CUDAHooks);" to register the critical CUDAHooks class. Without this class correctly registered, default class will report a hard-coded device count of 0.
2. Unfortunately, this static initializer is in torch_cuda.lib ( I assume ), which doesn't appear to have any symbols needed to bring in, thus ignored by Visual C++. So it is not executed at all.
3. torch::cuda::device_count() goes through the hook as in at::detail::getCUDAHooks().getNumGPUs(), hence getting 0.
4. at::cuda::getNumGPUs() doesn't go through the hook, hence getting a correct non-zero count.

Adding "-INCLUDE:?warp_size@cuda@at@@YAHXZ" helped, because it forces to link against torch_cuda.lib, hence bringing in the static initializer :-)

I think it is plainly wrong to count on static initializer to register an important class like this:

1. The given workaround of adding "-INCLUDE:?warp_size@cuda@at@@YAHXZ" is not acceptable in long run.
2. It is totally legit for a linker not to link an .a in these scenarios.
3. Forcing linking with -whole-archive has its own downsides: larger sizes of binary, potentially collision of symbols, etc..

I would recommend completely change the way how CUDAHooks is registered in future versions?

**Comment by gemfield** [comment]
If you got "PyTorch is not linked with support for cuda devices”, and is using libtorch static library, that is because the cuda registration (C10_REGISTER_GUARD_IMPL(CUDA, CUDAGuardImpl)) is in compile unit CUDAGuardImpl.cpp.o, which will be ar to libc10_cuda.a. make sure use -Wl,--whole-archive on libc10_cuda.a during link phase.

**Comment by ikarus-999** [comment]
> If you got "PyTorch is not linked with support for cuda devices”, and is using libtorch static library, that is because the cuda registration (C10_REGISTER_GUARD_IMPL(CUDA, CUDAGuardImpl)) is in compile unit CUDAGuardImpl.cpp.o, which will be ar to libc10_cuda.a. make sure use -Wl,--whole-archive on libc10_cuda.a during link phase.

How To solve in CMakeLists txt?   
I wonder How to solve this problem in Ubuntu like this...(ubuntu 20.04 CUDA 11.1, V100 GPU)
problem still remains...

**Comment by gast128** [comment]
I have this problem as well now. Strangely enough with LibTorch 2.0.1 torch_cuda.dll is loaded (through a static variable of type LoadingNvfuserLibrary in torch_cpu.dll) but this code has been removed from 2.6.0 and now it doesn't load automatically.
