### ISSUE TITLE
add is deprecated?

### ISSUE THREAD

**Issue by ygwangthu** [pytorch/pytorch#33444]
I have sucessfully compiled the source pytorch code.
I tried to train the network and it has the following warning
![11](https://user-images.githubusercontent.com/19385144/74743641-ba772380-529b-11ea-9df7-770254d73567.png)

I am not sure how to solve this problem?

**Comment by VitalyFedyunin** [comment]
You can change operands order, instead of `x = 1 + y` please use `x = y + 1`

**Comment by ygwangthu** [comment]
> You can change operands order, instead of `x = 1 + y` please use `x = y + 1`

No. The problem is related to #32580
