### ISSUE TITLE
How could I releasedthe GPU memory

### ISSUE THREAD

**Issue by Nyn2019** [pytorch/pytorch#33446]
Recently, I use pytorch to generate some adversarial samples, and the algothim is FGSM. Just like
https://pytorch.org/tutorials/beginner/fgsm_tutorial.html .  It was very smooth at the beginning of mu program. But soon pytorch told me that cuda is out of memory.  I guess there will be a part of the GPU memory has not been released. And I know torch.cuda.empty_cache(）but it didn't work. So how could  I resolve this problems? Thanks for anyone who could help me!  :)

**Comment by Nyn2019** [comment]
The code is here

def fgsm_attack(image, epsilon, data_grad):
   
    sign_data_grad = data_grad.sign()
    perturbed_image = image + epsilon*sign_data_grad
    perturbed_image = t.clamp(perturbed_image, 0, 255)

    return perturbed_image

def gen_adv(model, device, data, target, epsilon):

    data, target = data.to(device), target.to(device)
    data.requires_grad = True

    output = model(data)
    init_pred = output.max(1, keepdim=True)[1]
    if init_pred.item() != target.item():
        return

    loss = F.nll_loss(output, target)
    model.zero_grad()
    loss.backward()
    data_grad = data.grad.data
    data = unnormalized_show(data)

    perturbed_data = fgsm_attack(data, epsilon, data_grad)
    perturbed_data = perturbed_data.cpu().detach().numpy()
    perturbed_data = perturbed_data.reshape(3, 224, 224)
    perturbed_data = np.transpose(perturbed_data, (1, 2, 0))

    return perturbed_data

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
