### ISSUE TITLE
2nd derivative for im2col and col2im not implemented

### ISSUE THREAD

**Issue by jotterbach** [pytorch/pytorch#33452]
## 🚀 Feature

Implement second derivate for im2col and col2im. The following operations do not allow for backpropping the second derivative

```
_im2col = nn.Unfold(kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation)
_col2im = nn.Fold(top_shape, kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation)
```

and error with 

```
RuntimeError: derivative for im2col_backward is not implemented
```

## Motivation

The operation is needed, e.g. when using gradient penalties on architectures that involve gradients of these operations. The workaround using native slicing and reindexing of the tensors is extremely slow, resulting in a 10-20x slow-down. 

## Pitch

Implement the AD function that generates the 2nd derivative of above operations

## Alternatives

See motivation. Workarounds lead to significant slow-down.  Also see #22274

## Additional context

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by musikisomorphie** [comment]
Hi @VitalyFedyunin, I was wondering if this issue was addressed, sounds like an interesting one. I would like to give it a try.

**Comment by VitalyFedyunin** [comment]
CC @soumith to decide if we can take this feature

**Comment by soumith** [comment]
yes please, would love to take a PR on this one.

**Comment by musikisomorphie** [comment]
@t-vi, @soumith, @VitalyFedyunin, I am trying to implement double backward of im2col and col2im.   So I added multiple lines in derivatives.yaml, https://github.com/musikisomorphie/pytorch/blob/a6f07f274a9a1fdd25f2840adcaed3c46a009d4b/tools/autograd/derivatives.yaml#L1275-L1279

```
- name: im2col_backward(Tensor grad_output, int[2] input_size, int[2] kernel_size, int[2] dilation, int[2] padding, int[2] stride) -> Tensor
  grad_output: im2col(grad, kernel_size, dilation, padding, stride)


- name: col2im_backward(Tensor grad_output, int[2] kernel_size, int[2] dilation, int[2] padding, int[2] stride) -> Tensor
  grad_output: col2im(grad, {grad_output.size(2), grad_output.size(3)}, kernel_size, dilation, padding, stride)

```

Then I compiled the pytorch. As far as I understand, im2col and col2im are wrapped as nn.Unfold, nn.Fold,  so I run the following test, 

```
import torch
from torch import optim
from torch import nn
from torch.autograd import grad
import torch.nn.functional as F

torch.manual_seed(1)

x = torch.randn(2, 3, 8, 8, requires_grad=True)
unfold = nn.Unfold(kernel_size=(3, 3))
x_unfold = unfold(x)
y = x_unfold.view(2, -1).sum()
grads = grad(y, x, grad_outputs=torch.ones(y.size()), create_graph=True, retain_graph=True, only_inputs=True)[0]

print(x_unfold.grad_fn, grads.grad_fn)

grads1 = grads + 1
grads1.backward()

```
Then my terminal reports:

> <Im2ColBackward object at 0x7f487fe7f1d0> None
> Traceback (most recent call last):
>   File "im2col.py", line 57, in <module>
>     grads1.backward()
>   File "/home/path-to-torch/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/path-to-torch/torch/autograd/__init__.py", line 100, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

I also investigated  _aten/src/ATen/native/native_functions.yaml_ , couldn't find a clue. Can someone help me with this issue? Thank you very much.

My local configuration:
```
PyTorch version: 1.6.0a0+f84261e
Is debug build: Yes
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 430.50
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0a0+f84261e
[conda] blas                      1.0                         mkl  
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.0                      166  
[conda] mkl-include               2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] torch                     1.6.0a0+f84261e          pypi_0    pyp

```

**Comment by ezyang** [comment]
At a wild guess, what happens if you rewrite your example to directly call `torch._C._nn.im2col`; does it work then?

**Comment by albanD** [comment]
Hi,

That looks like the right implementation.
In your test code, you need to make sure that you require gradients for the grad_output: `torch.ones(y.size(), requires_grad=True)`. Because this is a Linear transformation and so the backward does not depend on the original input value and so when you consider just this op, the double backward will give you gradients only for the grad_output.

**Comment by musikisomorphie** [comment]
> Hi,
> 
> That looks like the right implementation.
> In your test code, you need to make sure that you require gradients for the grad_output: `torch.ones(y.size(), requires_grad=True)`. Because this is a Linear transformation and so the backward does not depend on the original input value and so when you consider just this op, the double backward will give you gradients only for the grad_output.

@albanD, @ezyang, thank you for your replies. After running multiple experiments, I think my discovery is similar to what @albanD suggested. After finishing the testing codes, I will open a PR.

**Comment by AntoineHX** [comment]
Hi,

I would have a use for such a feature as 2nd derivative for im2col. But as the PR was refused, i was wondering if the solution you've found isn't working or if it's only a minor issue ?

**Comment by albanD** [comment]
Hi,

No the PR was actually merged (all the PRs are closed because we have a custom process to merge into master).
You cannot use double backward for nn.Fold/nn.Unfold on the latest pytorch?

**Comment by AntoineHX** [comment]
I'm using the last stable version. With 1.5.0, i'm getting a RuntimeError: derivative for im2col_backward is not implemented.

You're probably talking about the master version ?

**Comment by albanD** [comment]
Yes it should be in the nightly version.

**Comment by albanD** [comment]
This is now in based on comment above
