### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#3345]
Got error:

> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/rluo/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
>     from torch._C import *
> ImportError: /home/rluo/anaconda2/lib/python2.7/site-packages/torch/lib/libATen.so.1: undefined symbol: THNN_CudaClassNLLCriterion_updateOutput

version a0ce84e

**Comment by zou3519** [comment]
Did you build pytorch from source? If so, could you try a `python setup.py clean` and then re-installing from source?

**Comment by ruotianluo** [comment]
I'll try
