### ISSUE TITLE
Forcing type will return zeroed tensor using torch.from_numpy.

### ISSUE THREAD

**Issue by willianrampazzo** [pytorch/pytorch#3346]
I updated to pytorch 0.2.0_4 and when I use the following syntax I get a tensor with all elements as 0:

y_train = torch.from_numpy(y_train).type(torch.LongTensor)

Here is an example:

print(y_train.shape)
(1929, 30)
print(y_train[0])
[ 0.37569925 -0.18745263 -0.37027067 -0.24121504  0.24129324 -0.17401204
  0.5235489  -0.16729173 -0.24257143 -0.22105414 -0.51139849 -0.22105414
  0.18652631 -0.39513233  0.67139852 -0.32858044 -0.16192481 -0.39578497
 -0.65924209 -0.38234437 -0.07457143  0.18889172  0.27490225  0.66604513
 -0.40386465  0.61227065 -0.09765413  0.51948869 -0.10144361  0.76012027]
torch.from_numpy(y_train)

 0.3757 -0.1875 -0.3703  ...   0.5195 -0.1014  0.7601
 0.3403 -0.2715 -0.3761  ...   0.4639 -0.0528  0.7808
 0.3554 -0.2727 -0.3562  ...   0.4623 -0.0151  0.6387
          ...             ⋱             ...          
 0.4256 -0.1948 -0.3980  ...   0.6467 -0.0172  0.8655
 0.3365 -0.3606 -0.4375  ...   0.6521  0.2211  0.6741
 0.3892 -0.2816 -0.3587  ...   0.5826  0.1026  0.7221
[torch.FloatTensor of size 1929x30]
torch.from_numpy(y_train).type(torch.LongTensor)

    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
       ...          ⋱          ...       
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
    0     0     0  ...      0     0     0
[torch.LongTensor of size 1929x30]

This syntax used to work on the previous version I was using (0.1x), so is zeroing all elements an expected behavior now?

**Comment by ozancaglayan** [comment]
Well since you are casting a floating point tensor to an integer type and all the values in your tensor are smaller than zero, doesn't it make sense that you obtain all zeros at the end? What was the behaviour in the previous version?

**Comment by colesbury** [comment]
The syntax still works. Converting a floating point to long performs integer truncation:

```python
In [51]: x = np.random.randn(5,5)

In [52]: torch.from_numpy(x)
Out[52]:

 1.9055  0.4037  0.5977 -1.0222 -0.0626
-1.1010 -2.0935 -0.3348 -0.1940 -0.6865
-1.2164  0.7486  0.7357 -1.6349  1.0273
 0.6048 -0.3195 -1.3211 -0.5026  1.3730
 0.2556 -0.6248  0.4777 -2.4683  1.1871
[torch.DoubleTensor of size 5x5]

In [53]: torch.from_numpy(x).type(torch.LongTensor)
Out[53]:

 1  0  0 -1  0
-1 -2  0  0  0
-1  0  0 -1  1
 0  0 -1  0  1
 0  0  0 -2  1
[torch.LongTensor of size 5x5]
```

**Comment by willianrampazzo** [comment]
Okay, never mind, I had in mind that pytorch long tensor was a floating point variable, and that was how I was using it previously. So, seems the bug existed on the previous version, before I update, not now. Thanks for the quick answer.
