### ISSUE TITLE
baddbmm(c, a, b) forgets to add c when a @ b inner dimension is empty

### ISSUE THREAD

**Issue by andrewdelong** [pytorch/pytorch#33467]
## 🐛 Bug

Corner case where `torch.baddmm(c, a, b)` doesn't match `torch.bmm(a, b) + c`: if the inner dimension of *a* and *b* is empty, the result is *zeros_like(c)* rather than  *c*.

Easy to work around, but gives subtly wrong results, so maybe worth fixing.

## To Reproduce

```python
a = torch.zeros((2, 1, 0))
b = torch.zeros((2, 0, 1))
c = torch.ones((2, 1, 1))
torch.bmm(a, b) + c     # <-- ones((2, 1, 1))  (OK)
torch.baddbmm(c, a, b)  # <-- zeros((2, 1, 1)) (WRONG)
```
## Possible Fix

The bug seems to be in `bmm_out_or_baddbmm_` from `aten/src/ATen/native/LinearAlgebra.cpp`:
```c++
  // handle pathological cases that blas may not like
  if (self_or_result.numel() == 0) {
    return self_or_result;
  } else if (contraction_size == 0) {
    return self_or_result.zero_();       // <-- BUG for baddbmm
  }
```
Replacing that line with this seems to fix it:
```c++
    if (is_bmm_out) {
      return self_or_result.zero_();
    } else {
      return self_or_result.mul_(beta);
    }
```

## Environment

 - PyTorch 1.5.0a0+6dd6b0b
 - MacOS
 - conda install
 - `USE_CUDA=0 python setup.py develop`
 - Python 3.8.1

**Comment by yf225** [comment]
@andrewdelong Thanks a lot for finding the bug! Curious would you be interested in opening a PR to fix this? Thanks!
