### ISSUE TITLE
JIT does not support binary operators

### ISSUE THREAD

**Issue by twostay** [pytorch/pytorch#33473]
## 🐛 Bug

I have a code that looks like this
```
import torch as tc
from torch import jit
@jit.script
def func(inp):
    return inp<<1
a = tc.tensor([3,4,5])
func(a)
```
when I run it, I got the error:
```
torch.jit.frontend.NotSupportedError: unsupported binary operator: LShift:
  File "example.py", line 5
@jit.script
def func(inp):
    return inp<<1
              ~~ <--- HERE
```
However, if I change `inp<<1` to `inp.__lshift__(1)`, it works. This also happens in C++.

## Expected behavior

I expect the binary operators to work without changing them to the call to methods.

## Environment

PyTorch version: 1.4.0+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.4.0+cpu
[pip3] torchvision==0.5.0+cpu
[conda] Could not collect
## Additional context

It is not a very severe problem and I would like to fix it if I know where the source code is located.

cc @suo

**Comment by eellison** [comment]
Hi, here is a good PR to follow https://github.com/pytorch/pytorch/commit/f649d8b3a9145563852721763cd1fb6246a9ad21.

**Comment by twostay** [comment]
Thanks, I'll take a try :).

**Comment by eellison** [comment]
HI @twostay , are you working on this ?

**Comment by twostay** [comment]
Hi, I found it complicated :( to make the modification, so I failed to do it. Please try to fix it. Thanks

**Comment by tugrulince** [comment]
With #34563, we can now perform shift operations. I will be closing this issue in the next few days unless I hear complications.
