### ISSUE TITLE
Incomplete conversion from PyTorch model to ONNX model

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#33488]
## To Reproduce

1.get code from https://github.com/Coldog2333/pytoflow.git
2.train a PyTorch model
3.convert the PyTorch model to ONNX

log with JIT trace (input of the generated ONNX model becomes shape of the original input tensor):
pytoflow/Network.py:211: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(frames.size(1)):
pytoflow/Network.py:212: TracerWarning: There are 3 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  frames[:, i, :, :, :] = normalize(frames[:, i, :, :, :])
pytoflow/Network.py:77: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if tensorFirst[0].size(2) > 32 or tensorFirst[0].size(3) > 32:
pytoflow/Network.py:82: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(math.floor(tensorFirst[0].size(2) / 2.0)),
pytoflow/Network.py:83: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  int(math.floor(tensorFirst[0].size(3) / 2.0)))
pytoflow/Network.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if tensorUpsampled.size(2) != tensorFirst[intLevel].size(2):
pytoflow/Network.py:91: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if tensorUpsampled.size(3) != tensorFirst[intLevel].size(3):
pytoflow/Network.py:27: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if str(tensorFlow.size()) not in Backward_tensorGrid:
pytoflow/Network.py:28: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  tensorHorizontal = torch.linspace(-1.0, 1.0, tensorFlow.size(3)).view(1, 1, 1, tensorFlow.size(3)).expand(tensorFlow.size(0), -1, tensorFlow.size(2), -1)
pytoflow/Network.py:29: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  tensorVertical = torch.linspace(-1.0, 1.0, tensorFlow.size(2)).view(1, 1, tensorFlow.size(2), 1).expand(tensorFlow.size(0), -1, -1, tensorFlow.size(3))
pytoflow/Network.py:33: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  Backward_tensorGrid[str(tensorFlow.size())] = torch.cat([tensorHorizontal, tensorVertical], 1)
pytoflow/Network.py:38: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return torch.nn.functional.grid_sample(input=tensorInput, grid=(Backward_tensorGrid[str(tensorFlow.size())] + tensorFlow).permute(0, 2, 3, 1), mode='bilinear', padding_mode='border')
pytorch_py37/lib/python3.7/site-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
pytoflow/Network.py:223: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  opticalflows[:, 1, :, :, :] = self.SpyNet(frames[:, 0, :, :, :], frames[:, 1, :, :, :]) / 2
pytoflow/Network.py:224: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  opticalflows[:, 0, :, :, :] = self.SpyNet(frames[:, 1, :, :, :], frames[:, 0, :, :, :]) / 2
pytoflow/Network.py:235: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  warpframes[:, i, :, :, :] = self.warp(frames[:, i, :, :, :], opticalflows[:, i, :, :, :])
pytoflow/Network.py:182: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(1, frames.size(1)):
graph(%0 : Float(1, 2, 3, 256, 448),
      %SpyNet.moduleBasic.0.moduleBasic.0.weight : Float(32, 8, 7, 7),
      %SpyNet.moduleBasic.0.moduleBasic.0.bias : Float(32),
      %SpyNet.moduleBasic.0.moduleBasic.2.weight : Float(64, 32, 7, 7),
      %SpyNet.moduleBasic.0.moduleBasic.2.bias : Float(64),
      %SpyNet.moduleBasic.0.moduleBasic.4.weight : Float(32, 64, 7, 7),
      %SpyNet.moduleBasic.0.moduleBasic.4.bias : Float(32),
      %SpyNet.moduleBasic.0.moduleBasic.6.weight : Float(16, 32, 7, 7),
      %SpyNet.moduleBasic.0.moduleBasic.6.bias : Float(16),
      %SpyNet.moduleBasic.0.moduleBasic.8.weight : Float(2, 16, 7, 7),
      %SpyNet.moduleBasic.0.moduleBasic.8.bias : Float(2),
      %SpyNet.moduleBasic.1.moduleBasic.0.weight : Float(32, 8, 7, 7),
      %SpyNet.moduleBasic.1.moduleBasic.0.bias : Float(32),
      %SpyNet.moduleBasic.1.moduleBasic.2.weight : Float(64, 32, 7, 7),
      %SpyNet.moduleBasic.1.moduleBasic.2.bias : Float(64),
      %SpyNet.moduleBasic.1.moduleBasic.4.weight : Float(32, 64, 7, 7),
      %SpyNet.moduleBasic.1.moduleBasic.4.bias : Float(32),
      %SpyNet.moduleBasic.1.moduleBasic.6.weight : Float(16, 32, 7, 7),
      %SpyNet.moduleBasic.1.moduleBasic.6.bias : Float(16),
      %SpyNet.moduleBasic.1.moduleBasic.8.weight : Float(2, 16, 7, 7),
      %SpyNet.moduleBasic.1.moduleBasic.8.bias : Float(2),
      %SpyNet.moduleBasic.2.moduleBasic.0.weight : Float(32, 8, 7, 7),
      %SpyNet.moduleBasic.2.moduleBasic.0.bias : Float(32),
      %SpyNet.moduleBasic.2.moduleBasic.2.weight : Float(64, 32, 7, 7),
      %SpyNet.moduleBasic.2.moduleBasic.2.bias : Float(64),
      %SpyNet.moduleBasic.2.moduleBasic.4.weight : Float(32, 64, 7, 7),
      %SpyNet.moduleBasic.2.moduleBasic.4.bias : Float(32),
      %SpyNet.moduleBasic.2.moduleBasic.6.weight : Float(16, 32, 7, 7),
      %SpyNet.moduleBasic.2.moduleBasic.6.bias : Float(16),
      %SpyNet.moduleBasic.2.moduleBasic.8.weight : Float(2, 16, 7, 7),
      %SpyNet.moduleBasic.2.moduleBasic.8.bias : Float(2),
      %SpyNet.moduleBasic.3.moduleBasic.0.weight : Float(32, 8, 7, 7),
      %SpyNet.moduleBasic.3.moduleBasic.0.bias : Float(32),
      %SpyNet.moduleBasic.3.moduleBasic.2.weight : Float(64, 32, 7, 7),
      %SpyNet.moduleBasic.3.moduleBasic.2.bias : Float(64),
      %SpyNet.moduleBasic.3.moduleBasic.4.weight : Float(32, 64, 7, 7),
      %SpyNet.moduleBasic.3.moduleBasic.4.bias : Float(32),
      %SpyNet.moduleBasic.3.moduleBasic.6.weight : Float(16, 32, 7, 7),
      %SpyNet.moduleBasic.3.moduleBasic.6.bias : Float(16),
      %SpyNet.moduleBasic.3.moduleBasic.8.weight : Float(2, 16, 7, 7),
      %SpyNet.moduleBasic.3.moduleBasic.8.bias : Float(2),
      %ResNet.conv_3x2_64_9x9.weight : Float(64, 6, 9, 9),
      %ResNet.conv_3x2_64_9x9.bias : Float(64),
      %ResNet.conv_3x7_64_9x9.weight : Float(64, 21, 9, 9),
      %ResNet.conv_3x7_64_9x9.bias : Float(64),
      %ResNet.conv_64_64_9x9.weight : Float(64, 64, 9, 9),
      %ResNet.conv_64_64_9x9.bias : Float(64),
      %ResNet.conv_64_64_1x1.weight : Float(64, 64, 1, 1),
      %ResNet.conv_64_64_1x1.bias : Float(64),
      %ResNet.conv_64_3_1x1.weight : Float(3, 64, 1, 1),
      %ResNet.conv_64_3_1x1.bias : Float(3)):
  %51 : Tensor = onnx::Shape(%0)
  %52 : Tensor = onnx::Constant[value={0}]()
  %53 : Long() = onnx::Gather[axis=0](%51, %52) # /home/intel/Documents/Frameworks/PyTorch/exps/pytoflow/Network.py:219:0
  %54 : Tensor = onnx::Shape(%0)
  %55 : Tensor = onnx::Constant[value={1}]()
  %56 : Long() = onnx::Gather[axis=0](%54, %55) # /home/intel/Documents/Frameworks/PyTorch/exps/pytoflow/Network.py:219:0
  %57 : Tensor = onnx::Shape(%0)
  %58 : Tensor = onnx::Constant[value={3}]()
  %59 : Long() = onnx::Gather[axis=0](%57, %58) # /home/intel/Documents/Frameworks/PyTorch/exps/pytoflow/Network.py:219:0
  %60 : Tensor = onnx::Shape(%0)
  %61 : Tensor = onnx::Constant[value={4}]()
  %62 : Long() = onnx::Gather[axis=0](%60, %61) # /home/intel/Documents/Frameworks/PyTorch/exps/pytoflow/Network.py:219:0

log with JIT script (failed to do the conversion with JIT script mode):
Traceback (most recent call last):
  File "evaluate.py", line 127, in <module>
    vimeo_evaluate(dataset_dir, './evaluate', pathlistfile, task=task, cuda_flag=cuda_flag)
  File "evaluate.py", line 119, in vimeo_evaluate
    onnx.export(torch.jit.script(net), input_frames, 'model.onnx', verbose=True)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "pytorch_py37/lib/python3.7/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::avg_pool2d(Tensor self, int[2] kernel_size, int[2] stride=[], int[2] padding=[0, 0], bool ceil_mode=False, bool count_include_pad=True, int? divisor_override=None) -> (Tensor):
  Argument self not provided.
  
  aten::avg_pool2d.out(Tensor self, int[2] kernel_size, int[2] stride=[], int[2] padding=[0, 0], bool ceil_mode=False, bool count_include_pad=True, int? divisor_override=None, *, Tensor(a!) out) -> (Tensor(a!)):
  Argument self not provided.

The original call is:
  File "pytoflow/Network.py", line 78
        for intLevel in range(3):
            if tensorFirst[0].size(2) > 32 or tensorFirst[0].size(3) > 32:
                tensorFirst.insert(0, torch.nn.functional.avg_pool2d(input=tensorFirst[0], kernel_size=2, stride=2))
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                tensorSecond.insert(0, torch.nn.functional.avg_pool2d(input=tensorSecond[0], kernel_size=2, stride=2))

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->
fully convert PyTorch model to ONNX one. Currently, the input of the generated ONNX model is shape of the original input tensor with JIT trace mode. JIT script mode doesn't work.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
 - PyTorch Version (e.g., 1.0): 1.4.0+cpu
 - OS (e.g., Linux): Ubuntu 18.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->


cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@jingxu10 - Could you please try one of the nightly builds (from pytorch.org) and check if this issue repros? If it does, could you please submit a smaller repro, with mostly the offending part (possibly with just avg_pool2d). That will help speed up the investigation.

**Comment by BowenBao** [comment]
```
Argument self not provided.

The original call is:
tensorFirst.insert(0, torch.nn.functional.avg_pool2d(input=tensorFirst[0], kernel_size=2, stride=2))
```

@jingxu10 - From the error message, it seems that jit is unable to recognize `input=tensorFirst[0]` as `self`. As a quick workaround, can you try changing the function call to `torch.nn.functional.avg_pool2d(tensorFirst[0], kernel_size=2, stride=2)`, and see if the error goes away?

**Comment by jessie-zhao** [comment]
@BowenBao, I modified according to your advice. That error seems to get solved, but the following new error occurred.
$ python evaluate.py --task interp --dataDir ./tiny/vimeo_triplet/sequences --pathlist ./tiny/vimeo_triplet/tri_testlist.txt --model ./toflow_models/interp.pkl 2>&1 | tee convert_onnx.log
Traceback (most recent call last):
  File "evaluate.py", line 128, in <module>
    vimeo_evaluate(dataset_dir, './evaluate', pathlistfile, task=task, cuda_flag=cuda_flag)
  File "evaluate.py", line 119, in vimeo_evaluate
    onnx.export(torch.jit.script(net), input_frames, 'model.onnx', verbose=True)
  File "/home/intel/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/home/intel/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/xx/Documents/Frameworks/PyTorch/venvs/venv_pytorch_nightly_py38/lib/python3.8/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
'module' object is not subscriptable:
  File "/home/xx/Documents/Frameworks/PyTorch/exps/pytoflow/Network.py", line 100
            #              upsampling flow]
            # then we obtain the final flow. 最终再加起来得到intLevel的flow
            tensorFlow = self.moduleBasic[intLevel](torch.cat([tensorFirst[intLevel],
                         ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                               Backward(tensorInput=tensorSecond[intLevel],
                                                                        tensorFlow=tensorUpsampled,

**Comment by jessie-zhao** [comment]
> @jingxu10 - Could you please try one of the nightly builds (from pytorch.org) and check if this issue repros? If it does, could you please submit a smaller repro, with mostly the offending part (possibly with just avg_pool2d). That will help speed up the investigation.

I tried nightly build, not working.

**Comment by garymm** [comment]
From the stack trace and error message, it appears this is a problem inside `torch.jit.script` and has nothing to do with ONNX.

I think this issue was discussed in https://github.com/pytorch/pytorch/issues/16123.

Closing this. If I'm wrong please feel free to open a new issue with clear reproduction instructions.
