### ISSUE TITLE
[Complex] Incorrect Complex Tensor inference

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#33493]
>>> a=torch.tensor([3/5+4/5j])
>>> a
tensor([(0.6000 - 0.8000j)], dtype=torch.complex128)

Expected: tensor([(0.6000 + 0.8000j)], dtype=torch.complex128)

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
Wow, how the heck did that happen!

**Comment by anjali411** [comment]
> Wow, how the heck did that happen!

It's a python bug:
1/2j gives -0.5j on python

**Comment by anjali411** [comment]
filed an issue: https://github.com/python/psf-infra-meta/issues/59

**Comment by zou3519** [comment]
Hypothesis: python is parsing the string wrong... 1/2j gets parsed as "1 / (2j) " which gives us "-0.5j"

**Comment by anjali411** [comment]
> Hypothesis: python is parsing the string wrong... 1/2j gets parsed as "1 / (2j) " which gives us "-0.5j"

yup I think so too

**Comment by anjali411** [comment]
> Hypothesis: python is parsing the string wrong... 1/2j gets parsed as "1 / (2j) " which gives us "-0.5j"

yeah I think so too

**Comment by vadimkantorov** [comment]
@anjali411 Is psf-infra-meta the good place for reporting Python bugs? it seems it's for "psf-infra-meta Meta-repository for PSF backed or managed systems.". All other issues registered there are about hosting / releases issues.

**Comment by dylanbespalko** [comment]
@anjali411,

I think I've run into this issue before. There needed to be a way to specify a number in another number system, so `j` is a suffix to the number 2, not a variable. See the following code snippet.

``` Python
j = 10
c_num = eval("1/2j")  # c_num = -0.5j (j is the suffix of 2)
c_num = eval("(1/2)*j") #c_num = 10 (j is a variable = 10)
```

Python is an interpreted language so it would be very difficult interpret` j` as a suffix of `1/2` without breaking the case where `j` is a variable. I think the solution is to change hypothesis to the following:

``` Python
j = 10
c_num = eval("1j/2")  # c_num = 0.5j (j is the suffix of 2)
```

It's confusing, but this method allows people to use a variable named `j`.
