### ISSUE TITLE
Complex number printing inconsistent with float

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#33494]
Zeros and  tensor printing for float and complex

1. In float tensor print, the trailing zeros ( with precision 4) are printed only when there’s one or more digit after decimal or otherwise just a decimal is printed
2. In complex tensor print rn, the trailing zeros are printing in all cases

>>> torch.zeros((2,2), dtype=torch.float64)                       
tensor([[0., 0.],
[0., 0.]], dtype=torch.float64)

>>> torch.tensor([1.2, 1.340], dtype=torch.float64)
tensor([1.2000, 1.3400], dtype=torch.float64)

>>> torch.tensor([1, 1], dtype=torch.float64)
tensor([1., 1.])

>>> torch.zeros((2,2), dtype=torch.complex64)
tensor([[(0.0000 + 0.0000), (0.0000 + 0.0000j)],
[(0.0000 + 0.0000j), (0.0000 + 0.0000j)]], dtype=torch.complex64)

>>> torch.tensor([1.2 + 1.340], dtype=torch.complex64)
tensor([1.2000 + 1.3400j], dtype=torch.complex64)

>>> torch.tensor([1, 1], dtype=torch.complex64)
tensor([1.0000, 1.0000], , dtype=torch.complex64)

cc @ezyang @anjali411 @dylanbespalko

**Comment by anjali411** [comment]
side note: it takes more space to print complex numbers than floating point numbers. So it might make sense to print less digits by default.
Also, Numpy does something kind of interesting when printing complex numbers:
>>> numpy.array([1.1123123+2.1j, 3.1+5.2j])
array([ 1.1123123+2.1j, 3.1000000+5.2j])

**Comment by anjali411** [comment]
side note: it takes more space to print complex numbers than floating point numbers. So it might make sense to print less digits by default.
Also, Numpy does something kind of interesting when printing complex numbers:
>>> numpy.array([1.1123123+2.1j, 3.1+5.2j])
array([ 1.1123123+2.1j, 3.1000000+5.2j])

**Comment by dylanbespalko** [comment]
@anjali411,

In the context to pretty printing multiple complex values it would be beneficial to keep the same formatting for every entry in the tensor. It would be nice to have the following:
1. `, ` should line up across multiple lines of output.
2. `+/-` should line up across multiple lines of output.
3. When the output is not abbreviated with `...` for length, it should be possible to copy the output string into an `eval(str)` and convert the number back into a python list or pytorch tensor.

**Comment by dylanbespalko** [comment]
>`ret = '({{:.{}f}} {{}} {{:.{}f}}j)'.format(p, p).format(value.real, '+-'[value.imag < 0], abs(value.imag))`

You might also consider using `g` engineering notation instead of `f` scientific notation because it uses sane SI units that you encounter in real life. Scientific notation will use less space though and is probably numpy compatible.

**Comment by choidongyeon** [comment]
Hi, I would like to try my hands on this. Can someone point me to the right place to start looking into this issue?

**Comment by shihongzhi** [comment]
> Hi, I would like to try my hands on this. Can someone point me to the right place to start looking into this issue?

@choidongyeon I think you can looking into this file `torch/_tensor_str.py`

        elif self.complex_dtype:
            p = PRINT_OPTS.precision
            ret = '({{:.{}f}} {{}} {{:.{}f}}j)'.format(p, p).format(value.real, '+-'[value.imag < 0], abs(value.imag))

**Comment by choidongyeon** [comment]
I have a mostly complete solution. However, I have a question regarding @anjali411's sample output. In the current version of source (1.6.0a0+9650f46), it seems that

`torch.tensor([1.2 + 1.340], dtype=torch.complex64)`

yields the sum of the real and imaginary parts,  `tensor([     (2.5400 + 0.0000j)], dtype=torch.complex64)`, rather than what is mentioned above (`tensor([1.2000 + 1.3400j], dtype=torch.complex64)`. Can someone confirm that this is the case for them, too? Should I file a separate issue for this?

**Comment by anjali411** [comment]
> I have a mostly complete solution. However, I have a question regarding @anjali411's sample output. In the current version of source (1.6.0a0+9650f46), it seems that
> 
> `torch.tensor([1.2 + 1.340], dtype=torch.complex64)`
> 
> yields the sum of the real and imaginary parts, `tensor([ (2.5400 + 0.0000j)], dtype=torch.complex64)`, rather than what is mentioned above (`tensor([1.2000 + 1.3400j], dtype=torch.complex64)`. Can someone confirm that this is the case for them, too? Should I file a separate issue for this?
 Hey @choidongyeon, I think it should be fine if you try:
```torch.tensor([1.2 + 1.340j], dtype=torch.complex64)``` instead of ```torch.tensor([1.2 + 1.340], dtype=torch.complex64)```

**Comment by choidongyeon** [comment]
@anjali411  Awesome thanks for pointing it out!

**Comment by choidongyeon** [comment]
@anjali411 Close this issue? :)
