### ISSUE TITLE
Sequential does not allow muti-output modules such as RNN, LSTM

### ISSUE THREAD

**Issue by anaheata** [pytorch/pytorch#3349]
I think the forward function in Sequential should be modified to the following to be able to accept multi-output layers followed by other layers that require one input: 

    def forward(self, input): 
        for module in self._modules.values():
            input = module(input)
            if isinstance(input, tuple):
                input = input[0] 
        return input

Currently the following is not possible: 
model = nn.Sequential(
nn.LSTM(…),
---> since LSTM will return a tuple, the forward function gives an error here
nn.Linear(…)
)

**Comment by SsnL** [comment]
As I said in forum, this is not a bug.

**Comment by soumith** [comment]
Sequential is reserved for the most simple cases. it's a deliberate choice. anything more complex is written as a python program.

**Comment by anaheata** [comment]
Thanks for the answers! I will probably learn why Sequential needs to be simple after working more on nns.
