### ISSUE TITLE
Pytorch + Cuda + GCC Version 

### ISSUE THREAD

**Issue by shersoni610** [pytorch/pytorch#33530]
Hello,

I am using Ubuntu 18.04 which has gcc-9.0 installed. I also use Titan black card for which
I need to install pytorch from the sources.

However, when I try to compile the source codes, I see that cuda 10.2 does not support the
gcc > 7.0.  Why there is a such a restriction? Can I use gcc > 8 to compile pytorch?

Thanks

**Comment by ptrblck** [comment]
I'm using the default gcc 7.4.0 in Ubuntu 18.04.3 and it works fine.
I haven't tried to update it, but based on [this guide](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements) you might need to install an older version.

**Comment by albanD** [comment]
Based on the answer, this is a cuda limitation. So there isn't much we can do here.
