### ISSUE TITLE
Inconsistency between torch.abs() and np.absolute() for complex tensors

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#33567]
```
import torch
>>> a = torch.tensor([1+2j])
tensor([(1.0000 + 2.0000j)], dtype=torch.complex128)
>>> a.abs()
tensor([   (2.2361 + 0.0000j)], dtype=torch.complex128)


import numpy as np
>>> a=np.array([1+2j])
>>> a.dtype
dtype('complex128')
>>> np_res = np.absolute(a)
array([2.23606798])
>>> np_res.dtype
dtype('float64')
```

cc @ezyang @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
I don't see a discrepancy here, it's just Numpy prints complex arrays differently when there are no imaginary components.

**Comment by vadimkantorov** [comment]
I wonder if it’s a good idea to have a user-accessible function to check if a complex tensor is in fact a real tensor, i.e. the imaginary part or exactly zero (or maybe even with provided tolerance)

**Comment by wDaniec** [comment]
I will try to fix it.

**Comment by VIGNESHinZONE** [comment]
How can i reproduce this issue??  And i tried reading https://github.com/pytorch/pytorch/issues/755 . 
Im getting 
RuntimeError: Could not infer dtype of complex

**Comment by dachosen1** [comment]
is this still being worked on? Could i take a shot at it.

**Comment by wDaniec** [comment]
Yes. I am working on it. Couldn't spend much time on it last week because of illness.

**Comment by dachosen1** [comment]
ok no worries. let me know if you need help

**Comment by wDaniec** [comment]
Sorry for such a long delay. I've been trying to workout how to solve it in a reasonable way but got stuck at the moment. Was hoping to just overload the __abs__ method in Tensor class, but the tensor.abs() function seems to be Cpp implemented and linked in the torch/__init__.py. I am confused as to where to find the function itself.

**Comment by anjali411** [comment]
you can find the abs functions here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_float.h and here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_double.h however this change is not a straightforward as the vec256_base class is constrained to return the vec256<T> for all methods in vec256 class
