### ISSUE TITLE
Type conversion overflow causes uncaught std::domain_error (Mac only)

### ISSUE THREAD

**Issue by andrewdelong** [pytorch/pytorch#33562]
## 🐛 Bug

On macOS, comparing or assigning an integer value that is too large for the tensor type will raise a `std::domain_error` that goes uncaught by Python and terminates the process. Reproduces in PyTorch 1.4 (conda installed) and current 1.5 dev (built from source).

This causes `python test/run_test.py -i test_torch` to crash out at `test_comparison_ops_check_for_scalar_overflow` and `test_comparison_ops_check_for_zerodim_tensor_overflow`. Unless it's just my setup, could be worth fixing. (Contributors would need to disable these tests on macOS in order to test their own contributions.)

## To Reproduce

```
$ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
>>> import torch
>>> torch.tensor([0], dtype=torch.uint8) < 256
libc++abi.dylib: terminating with uncaught exception of type std::domain_error
[1]    83419 abort      python
$ 
```

## Expected behavior

On Linux the `std::domain_error` gets successfully converted to a `RuntimeError` and raised in Python.
```
$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
>>> import torch
>>> torch.tensor([0], dtype=torch.uint8) < 256
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atd/ext/anaconda3/envs/ml/lib/python3.7/site-packages/torch/tensor.py", line 28, in wrapped
    return f(*args, **kwargs)
RuntimeError: value cannot be converted to type uint8_t without overflow: 256
>>>
```

## Clues / Possible fix

Changing `std::domain_error` to `std::runtime_error` below seems to fix it on macOS:
https://github.com/pytorch/pytorch/blob/d119de8abde8ba436e429d66764fce0624e0e9e6/c10/util/TypeCast.h#L183

Not sure what code is converting the original exception to `RuntimeError`, since [pybind11 converts `std::domain_error` to `ValueError`](https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html).

## Environment

 - PyTorch 1.4.0 or 1.5.0a0+34c0b74
 - MacOS only
 - `conda install` for PyTorch 1.4.0
 - `USE_CUDA=0 python setup.py develop` for PyTorch 1.5 dev
 - Python 3.8.1

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
The possible fix sounds reasonable. We have our own error catching code and we don't catch `domain_error`; another fix would be to modify that code to catch domain error too.

**Comment by andrewdelong** [comment]
@ezyang You're right, catching `domain_error` broadly sounds like a much better fix. (Someone might try to throw `domain_error` in another context down the road.) I'm just not sure where to look.

**Comment by ezyang** [comment]
Right at `torch/csrc/Exceptions.h`

**Comment by peterbell10** [comment]
`HANDLE_TH_ERRORS` already includes a catch clause that should cover all standard exception types:
https://github.com/pytorch/pytorch/blob/5a8562a6af2f4097975ad079e982a88924c4fd07/torch/csrc/Exceptions.h#L76-L80

Is it possible there's some weirdness because the exception is thrown from a shared library (`c10`)?

**Comment by ezyang** [comment]
Yes, there could be some weak symbol fiasco and we're ending up with two RTTI copies of `std::exception`. However, if that's true, then adding `std::domain_error` guard probably wouldn't help either.

**Comment by andrewdelong** [comment]
Raising `std::runtime_error` instead of `std::domain_error` fixes the problem on Mac, so not sure if that's consistent with "extra RTTI copy" hypothesis 🤔.

**Comment by ezyang** [comment]
Weird. Well, I'll accept a PR that changes the type. Or you can try adding an extra try-catch and see if that works too.
