### ISSUE TITLE
Weights won't update during backpropogation

### ISSUE THREAD

**Issue by Mickey-Livesgood** [pytorch/pytorch#3358]
I have updated my model to use a dataset to train it in batches. Before I did that (and didn't use mini-batches) the model worked great and the backpropogation was training my network, getting it to reach high accuracy).
However, it seems now that the optimizer.step() does not update my weights. I'm not sure what the problem is. I tried to change the learning rate, the loss function and the optimization function but nothing work.

This is the code of my model (removed irrelevant parts):
```python

train_file_name = "train.csv"

class DataSet(Dataset):
    
    def __init__(self, file_name):
        xy = np.loadtxt(file_name, dtype=np.float32, skiprows=1, delimiter=",")
        #xy= pd.read_csv(train_file_name, encoding = "ISO-8859-1")
        self.len = xy.shape[0]
        self.x_data = torch.from_numpy(xy[:,3:303])
        self.y_data = torch.from_numpy(xy[:,1:3])
        
    def __getitem__(self,index):
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len

D_in, H, D_out = 300, 300, 2

class model(torch.nn.Module):
    
    def __init__(self, D_in, H, D_out):
        super(model, self).__init__()
        ## Initiate two linear levels with the dimensions given to the object
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, H)
        self.linear3 = torch.nn.Linear(H,H)
        self.linear4 = torch.nn.Linear(H, H)
        self.linear5 = torch.nn.Linear(H, D_out)
        
    def forward(self, x):
        func = torch.nn.Softmax()
        z1 = self.linear1(x).clamp(min=0) # relu
        z2 = self.linear2(z1).clamp(min=0) # relu
        z3 = self.linear3(z2).clamp(min=0) # relu
        z4 = self.linear4(z3).clamp(min=0) # relu
        z5 = func(self.linear5(z4))
        return z5
 

net = model(D_in, H, D_out)

#criterion = torch.nn.MSELoss(size_average = False)
criterion = torch.nn.BCELoss(size_average = False)
optimizer = torch.optim.SGD(net.parameters(), lr=0.00002)


train_data_set = DataSet(train_file_name)
train_loader = DataLoader(dataset=train_data_set, batch_size = 128, shuffle = True)

for epoch in range(500):
    # go in batches of 32
    for i, data in enumerate(train_loader, 0):
        inputs, labels = data
        # wrap the input in a Variable
        inputs, labels = Variable(inputs), Variable(labels)
        #print(inputs, labels)
        # forward pass
        y_pred = net(inputs)
        
        # compute the loss
        loss = criterion(y_pred, labels)
        print(epoch, i, loss.data[0])
        
        # backpropogation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
```

I would love some help on this issue. I'm guessing it has to do with the Dataset and batch loop that I added. Thanks!

**Comment by IssamLaradji** [comment]
Let's see if the gradients are getting computed.  
Try running this code just under `loss.backward()`,
```
for param in net.parameters():
    print(param.grad.data.sum())
```
are the values all zeros ? if not, then the learning rate might be too small in the optimizer.

**Comment by Mickey-Livesgood** [comment]
@IssamLaradji 
Thanks for the reply.
I have tried it, but my gradients are not all zero.. I guess that it has something to do with the `step()` part. This is an example of what your code prints:
```
-0.5104657087122177
-0.058136511710472405
4.710732403683254
0.3100423458381556
-10.81544414441908
-1.4291214804979973
8.55161297514863
1.877118336444255
0.0
0.0
```

**Comment by IssamLaradji** [comment]
Yes, the learning rate has to be smaller for mini-batch learning,  because the smaller the batch size the larger the gradient variance you have which can cause bad optimization steps when the step size is not decreased. 

Stochastic gradient descent usually oscillate heavily between different loss function values and would asymptotically decrease with lower step size. The convergence rate of stochastic gradient descent depends heavily on the step size [1]. 

With full-batch gradient descent, you have the full gradient information of the batch which allows you to take a bigger step size without risking having "bad" optimization steps.

[1] https://www.cs.ubc.ca/~schmidtm/Documents/2014_Google_SAG.pdf

**Comment by soumith** [comment]
your learning rate simply has to be increased, and as Issam pointed out SGD has quite a bit of variance in the gradients.

**Comment by RyanCV** [comment]
@IssamLaradji I run your for loop to print the param.grad but got the following error
```
print(param.grad.data.sum())
AttributeError: 'NoneType' object has no attribute 'data'
```
any idea? 
Thanks.

**Comment by princessmittens** [comment]
> @IssamLaradji I run your for loop to print the param.grad but got the following error
> 
> ```
> print(param.grad.data.sum())
> AttributeError: 'NoneType' object has no attribute 'data'
> ```
> any idea?
> Thanks.
add your model name, instead of net.  
loss.backward()

for param in <insertyourmodelname>.parameters():
    print(param.grad.data.sum())

# start debugger
import pdb; pdb.set_trace()

optimizer.step()

**Comment by VDeamoV** [comment]
> > @IssamLaradji I run your for loop to print the param.grad but got the following error
> > ```
> > print(param.grad.data.sum())
> > AttributeError: 'NoneType' object has no attribute 'data'
> > ```
> > any idea?
> > Thanks.
> > add your model name, instead of net.
> > loss.backward()
> 
> for param in .parameters():
> print(param.grad.data.sum())
> 
> # start debugger
> import pdb; pdb.set_trace()
> 
> optimizer.step()

Hi there,
I have the same issue, `print(param)` can print the params normally, but it didn't contained grad.

my optim's code is below

```python
torch.optim.Adam([{'params': model.parameters()}, {'params': model_2.parameters()}], 
                    lr=opt.learning_rate)
```

**Comment by tarun005** [comment]
@RyanCV I am facing the same issue. Somehow, param.grad is None. Did you find a solution?

**Comment by yushuinanrong** [comment]
for n, param in model.named_parameters():
      if param.grad is not None:
            print(n, param.grad.data.sum())
import pdb; pdb.set_trace()
