### ISSUE TITLE
pack_padded_sequence's enforce_sorted doc improvement

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#33602]
## 📚 Documentation

torch/nn/utils/rnn.html:

`pack_padded_sequence` has a confusing and incomplete description of the `enforce_sorted` param. Currently it goes:

```
        enforce_sorted (bool, optional): if ``True``, the input is expected to
            contain sequences sorted by length in a decreasing order. If
            ``False``, this condition is not checked. Default: ``True``.
```

The second part "this condition is not checked" (1) makes no sense since the alluded to condition is not described and (2) it's incomplete as it doesn't reflect the important part, that it actually does the sorting. I think it should say something like:

```
        enforce_sorted (bool, optional): if ``True``, the input is expected to
            contain sequences sorted by length in a decreasing order. If
            ``False``, the input will get sorted unconditionally. Default: ``True``.
```

I'm not sure whether it should also mention `sorted_indices` to enable recovering of the original sorting order, if one doesn't use `pad_packed_sequence` to unpack it.

Thanks.

cc @zou3519

**Comment by albanD** [comment]
Hi,

This sounds like a good clarification indeed. I don't think you need to mention `sorted_indices` as it is properly described in the `PackedSequence` properties that one needs to read if they want to work with it directly.
Could you send a PR with this change?

**Comment by stas00** [comment]
Here it is: https://github.com/pytorch/pytorch/pull/33617

Thank you for your review,  @albanD

**Comment by albanD** [comment]
Cooresponding PR is now merged.
Thanks again for the PR.
