### ISSUE TITLE
nn.ConstantPad2d Not working correct! NotImplementedError: Only 4D and 5D padding is supported for now

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#3360]
I installed pytorch using pip

I noticed that  for the following code I receive error:

```
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch import autograd

input = autograd.Variable(torch.randn(3, 3))

m = nn.ConstantPad2d((1,1,1,1), 0)
output = m(input)
print(output)
```

NotImplementedError: Only 4D and 5D padding is supported for now

Though some people mentioned it works if you install pytorch using the source, it is not working yet when I install pytorch using pip

Please fix this issue

**Comment by apaszke** [comment]
As you mentioned, this is already fixed, so there's no actionable item for us at this point. Next binary release will contain the fixes. If you need them now, you can always install PyTorch from source (should be seamless, it's just a single command).

**Comment by isalirezag** [comment]
What single command?
The installation from source sounds a little vague.
I have ubuntu 16.04 and I don't use Anaconda, it sounds like you guys just have installation from source given that the user having/using anaconda :/ 
Lemme know if there is any other way that I am not aware of...

**Comment by apaszke** [comment]
You can build without conda using `python setup.py install`

**Comment by ragulpr** [comment]
Could reproduce @isalirezag  error with latest binary. Worked after building from source (on osx) using:
```
conda create -n pytorchsource python=2.7 
source activate pytorchsource
conda install numpy pyyaml setuptools cmake cffi   
git submodule update --init        
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install

python 
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch import autograd

input = autograd.Variable(torch.randn(3, 3))

m = nn.ConstantPad2d((1,1,1,1), 0)
output = m(input)
print(output)

Variable containing:
 0.0000  0.0000  0.0000  0.0000  0.0000
 0.0000  0.5107  2.0236 -1.2180  0.0000
 0.0000  0.8027 -0.2484  1.7507  0.0000
 0.0000  0.0755  0.2109 -0.9640  0.0000
 0.0000  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x5]
```
