### ISSUE TITLE
Multilayer BiRNNs are sharing state across directions

### ISSUE THREAD

**Issue by mjudell** [pytorch/pytorch#33625]
## 🐛 Bug

Multilayer BiRNNs are sharing state across directions

**Evidence:**
(1) Multi-layer BiRNNs overfit sequences almost immediately, while concatenated unidirectional RNNs do not
(2) Multi-layer BiRNNs have significantly more parameters than we would expected from (a) textbook definitions, (b) the docs, (c) the concatenation of orthogonal RNN instances
(3) Pinning the `_reverse` weights of the BiRNN to fixed values affects results from the left-right model

I noticed (2) when I tried to debug (1) by filling unidirectional RNNs with parameters from the bidirectional model. I thought (2) might be some kind of ninja weight-tying to facilitate parallelization, but given (3) I suspect it is a bug.

## To Reproduce

**Recreate 2**
```
import torch.nn as nn
from numpy import prod

dim = 29
layers = 5
use_bias = True

bigru = nn.GRU(dim, dim, layers, bidirectional=True, bias=use_bias)
bigru_params = sum(prod(p.size()) for p in bigru.parameters())

bigru_docs = 2*layers*(dim*dim + dim*dim +    # Wir, Whr in docs
                       use_bias*(dim + dim) + # bir, bhr in docs
                       dim*dim + dim*dim +    # Wiz, Whz in docs
                       use_bias*(dim + dim) + # biz, bhz in docs
                       dim*dim + dim*dim +    # Win, Whn in docs
                       use_bias*(dim + dim))  # bin, bnn in docs
                       
gru = nn.GRU(dim, dim, layers, bidirectional=False, bias=use_bias)
gru_stacked_params = 2 * sum(prod(p.size()) for p in gru.parameters())

print('\n'.join([
    'BiGRU Params: {:d}'.format(bigru_params),
    'Expected BiGRU Params: {:d}'.format(bigru_docs),
    'Stacked GRU Params: {:d}'.format(gru_stacked_params)]))
```

**Recreate 3**
```
import torch
import torch.nn as nn
from numpy import prod

torch.random.manual_seed(2718)

dim = 29
layers = 3
use_bias = True
bigru = nn.GRU(dim, dim, layers, bidirectional=True, bias=use_bias)

seq_len = 5
batch_size = 7
ntokens = 11

emb = nn.Embedding(ntokens, dim)

tokens = torch.randint(low=0, high=ntokens-1, size=(seq_len, batch_size))
tokens_emb = emb(tokens)

out_prefill, _ = bigru(tokens_emb)
out_prefill = out_prefill.view(seq_len, batch_size, 2, dim)

bigru.weight_ih_l0_reverse.data.fill_(100.)
bigru.weight_hh_l0_reverse.data.fill_(100.)
bigru.weight_ih_l1_reverse.data.fill_(100.)
bigru.weight_hh_l1_reverse.data.fill_(100.)

out_postfill, _ = bigru(tokens_emb)
out_postfill = out_postfill.view(seq_len, batch_size, 2, dim)

lr_diff = (out_prefill[:, :, 0, :] -
           out_postfill[:, :, 0, :])

rl_diff = (out_prefill[:, :, 1, :] -
           out_postfill[:, :, 1, :])

print('Forward Mean Abs Diff: {:.3f}'.format(lr_diff.mean().item()))
print('Backward Mean Abs Diff: {:.3f}'.format(rl_diff.mean().item()))
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.6
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

cc @zou3519

**Comment by mjudell** [comment]
I should have caught this immediately.

This is not an implementation bug, but a strange design choice.  Pytorch multi-layer BiRNNs are [structured](https://github.com/pytorch/pytorch/issues/4930) as `BiRNN --> BiRNN` rather than `concat(RNN--->RNN; RNN-->RNN)` which is a dramatic departure from what is called a multi-layered BiRNN in the literature.  

I can't think of any conceivable use of `BiRNN -> BiRNN`, as one pays the enormous parallelization penalty from recurrence but immediately destroys the time separation in the second layer.

Perhaps it might be helpful to include a warning in RNN constructors when users select `layers>1` and `bidirectional=True`, or at least alert users to this design choice in the docs?

**Comment by zou3519** [comment]
This might be related: https://github.com/pytorch/pytorch/issues/4930#issuecomment-580599849 . PyTorch implements one of the two types of bidirectional RNNs.

**Comment by mjudell** [comment]
Thanks!  Sorry for the hassle there.
