### ISSUE TITLE
Failed to build pytorch 1.4.0 on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by xdever** [pytorch/pytorch#33637]
## 🐛 Bug

After running setup.py, I get a very long error message complaining about pybind11. If I re-run setup.py, it will take long time building again, and will start complaining about:

```/home/robert/pytorch/torch/csrc/jit/init.cpp:64:10: fatal error: pybind11/iostream.h: No such file or directory
 #include <pybind11/iostream.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
followed by a very-very-very long list of C++ garbage error messages (I have to Ctrl+C the script to be able to copy the snippet above, otherwise it is scrolled out of the terminal's buffer. Here is a screen buffer worth of it: https://pastebin.com/DVYkEERk).

The above message is not visible when I run it for the first time. But it is consistently printed if setup.py is re-run.

The visible part of the build progress printed out to the screen can be found here: 
https://pastebin.com/t0bSTKhr

"python3-pybind11" package is installed globally.

I have PyTorch set up on many machines, all running Ubuntu 18.04, and I never had this issue before, just with the fresh Ubuntu server 18.04.4 install.

I have tried system pybind11, setuptools and wheel and pip3 based version of them, nothing changes.

## To Reproduce

1. Run:
```bash
git clone --recursive https://github.com/pytorch/pytorch; cd pytorch
git checkout tags/v1.4.0; git submodule update --recursive
CUDA_HOME=/usr/local/cuda CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/ CUDNN_INCLUDE_DIR=/usr/include NCCL_LIB_DIR=/usr/lib/x86_64-linux-gnu/ NCCL_INCLUDE_DIR=/usr/include USE_MKLDNN=ON python3 setup.py bdist_wheel
```

## Expected behavior

Build the wheel file.

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] Could not collect

**Comment by albanD** [comment]
Hi,

It does look like you're missing submodules.
Isnt't  this command  `git submodule update --recursive` missing a `--init` ? Otherwise it won't initialize them.

**Comment by xdever** [comment]
The source is cloned with --recursive, so it should be fine. I can see the submodules and their files in third_party. I use this procedure of installing PyTorch for a long time, and never had problems so far.

Long story: I'm involved in maintaining our servers in the research group. I have a procedure written down for setting up a new server from the ground up, with every single step (this was useful when I clean installed 5 machines at once). Now we got some new machines and decided to reinstall the really old ones too, and all of them fail with the same problem. A year ago the exact same procedure worked with Ubuntu 18.04.

Now I'm trying to collect a full log from the terminal output. I was not able to find any log files where the error message is shown.

**Comment by xdever** [comment]
Full log (too big for pastebin):

https://drive.google.com/file/d/1z4aob0BW_HtAu0_H-21tvevr0YXPyFki/view?usp=sharing

**Comment by xdever** [comment]
The issue is with the system-wide pybind11-dev package (Version: 2.0.1-4). After removing it pytorch builds just fine.
