### ISSUE TITLE
[Quantization]Quant and Dequant is changing memory layout

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#33643]
## 🐛 Bug

THe quantize and dequantize currently call into contiguous, which may lead to underlying NHWC=>NCHW change. 

## To Reproduce
https://github.com/pytorch/pytorch/blob/bd3c6e8e91cc8eca58b1a113a081e7701a1d595f/aten/src/ATen/quantized/Quantizer.cpp#L577

1. construct a residual add path, one is from qconv and another is directly from quantize input.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by Luonic** [comment]
Looks like i have the same problem, getting absolutely random noise from properly trained HRNet. Any possible workaround of this issue?

**Comment by vkuzo** [comment]
this should be fixed by https://github.com/pytorch/pytorch/pull/42178
