### ISSUE TITLE
Slight error in docs of tensor.index_put_

### ISSUE THREAD

**Issue by v0dro** [pytorch/pytorch#33641]
## 📚 Documentation

The docs for [index_put_](https://pytorch.org/docs/master/tensors.html#torch.Tensor.index_put_) state in the second paragraph:
```
If accumulate is True, the elements in tensor are added to self. If accumulate is False, the behavior is undefined if indices contain duplicate elements.
```

It should be corrected to `elements in _value_ are added to self`.

**Comment by albanD** [comment]
You're right, can you send a PR to fix this please?
