### ISSUE TITLE
Improve speed of per-channel fake quant operator

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#33647]
Current implementation of per-channel fake-quant is much slower than per tensor fake-quant. This is due to the increased overhead of calling multiple cuda kernels per channel. A rewrite with a single call should make this significantly faster.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by ngimel** [comment]
cc @csarofeen, I thought quantization team at nvidia was going to do this?

**Comment by csarofeen** [comment]
Yes, we plan to do this.

**Comment by ngimel** [comment]
Any ETA?

**Comment by raghuramank100** [comment]
Second that. We need this soon for internal needs, so having an ETA would help in planning this out.
