### ISSUE TITLE
Why Pytorch1.3.0/Python3 is Slower than Pytorch0.2.0/Python2

### ISSUE THREAD

**Issue by yaoyiran** [pytorch/pytorch#33658]
When running the piece of code below, I found that pytorch0.2.0 is much faster than the new version. Anyone know how to fix it?

import torch
import time
batch_size = 64
tt = torch.cuda
torch.cuda.set_device(0)
live = [ [ ( 0.0, [ 2 ], 0 ) ] for ii in range(batch_size) ]
a = time.time()
pre_prob = tt.FloatTensor( [ [ x[0] for x in ee ] for ee in live ] ).view(batch_size, -1, 1)
b = time.time()
print("time cost tt.FloatTensor:", b-a)
a = time.time()
pre_prob2 = pre_prob + pre_prob
b = time.time()
print("time cost add:", b-a)

In Pytorch 1.3.0:
time cost tt.FloatTensor: 2.321345090866089
time cost add: 0.00013875961303710938
In Pytorch 0.2.0
('time cost tt.FloatTensor:', 1.5947380065917969)
('time cost add:', 0.00011014938354492188) 

cc @ngimel @VitalyFedyunin

**Comment by yaoyiran** [comment]
When I try to migrate some code from pytorch 0.2.0 to 1.3.0, I found that the time cost increases a lot (the time cost increased by several times) but I do not know why. I found that even creating a tensor on a GPU or operations like adding two tensors in 0.2.0 would be faster than the 1.3.0 version. Above are two simple examples.

**Comment by albanD** [comment]
Hi,

For the Tensor creation is that only the first Tensor you create? Because here, the creation of the first cuda Tensor initialize the whole cuda context.
Since the library increased in size, the cuda context is longer to initialize.
Does creating another Tensor afterward similar?

For the addition, given the very small value, I'm not sure this is really significant.
Also the cuda api is asynchronous so you only measure the launch time here, not the time to do the addition. You need to use torch.cuda.synchronize() if you want to get the actual runtime to perform the operation.

**Comment by yaoyiran** [comment]
Thanks for your comments. I met this problem when doing beam search, the original code of which is in 0.2.0 and I tried to migrate that to version 1.3.0. 

The beam search function, used in the bleu score evaluation, is from line 427-line 506 in https://github.com/facebookresearch/translagent/blob/master/src/sentence/models.py

I found that the runtime of beam search is about 5 times in 1.3.0 more than that in 0.2.0. I found that line almost everything running on gpu is much slower than the 0.2.0 version including: line 449, 451, 452, 454, 455, 462, 463, 471(most serious), 472(most serious), 473(most serious), 475, 476, 477, 483, 484, 488(most serious), 490, 501. 

Interestingly, the training process goes very well, the time cost of the 1.3.0 version is shorter than the 0.2.0 version. But the time cost of the beam search function in the evaluation steps for calculation bleu scores increases by 5 times. Do you know how can I fix it?

**Comment by ngimel** [comment]
Can you please create a small reproduction example that demonstrates regression?
