### ISSUE TITLE
CMake build error with *.cu source files

### ISSUE THREAD

**Issue by loolzaaa** [pytorch/pytorch#33659]
Hello, i'm try to build simple project in CMake with libtorch, but **by default** i get some errors.

Firstly, my **CMakeLists.txt** (of course, i change path to libtorch):
```cmake
cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(torch-start LANGUAGES CXX CUDA)

set(CMAKE_PREFIX_PATH "absolute\path\to\libtorch")

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(torch-start torch-start.cpp kernel.cu)
target_link_libraries(torch-start "${TORCH_LIBRARIES}")
set_property(TARGET torch-start PROPERTY CXX_STANDARD 14)

set_target_properties(torch-start PROPERTIES CUDA_SEPARABLE_COMPILATION ON)

# The following code block is suggested to be used on Windows.
# According to https://github.com/pytorch/pytorch/issues/25457,
# the DLLs need to be copied to avoid memory errors.
if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET torch-start
                     POST_BUILD
                     COMMAND ${CMAKE_COMMAND} -E copy_if_different
                     ${TORCH_DLLS}
                     $<TARGET_FILE_DIR:torch-start>)
endif (MSVC)
```
--------------
So, as you can see, i include two source files in project...

**torch-start.cpp**:
```cpp
#include <torch/torch.h>
#include <iostream>

void test(torch::Tensor tensor);

int main() {
  torch::Tensor tensor = torch::rand({2, 3}, torch::device(torch::kCUDA));
  std::cout << "Input: \n" << tensor << std::endl;  
  test(tensor);  
  std::cout << "Output: \n" << tensor << std::endl;
}
```
**kernel.cu**:
```cuda
#include <torch/torch.h>

__global__ void kernel(float *tensor) {
    int idx = threadIdx.x;
    tensor[idx] += idx;
}

void test(torch::Tensor tensor) {
    const dim3 threads = tensor.size(0) * tensor.size(1);
    kernel<<<1, threads>>>(tensor.data<float>());
}
```
--------------
CMake successfully configure and generate project files. After that, i try to build project...
`> cmake --build . --config Release`
... and get an error:
>nvcc fatal   : Unknown option 'openmp'

**Question 1: Why -openmp is unknown option for me and is it really need?**

I found this option in `.\libtorch\share\cmake\Caffe2\Caffe2Targets.cmake`, try remove it, build project again and get new error:
>nvcc fatal   : A single input file is required for a non-link phase when an output file is specified

Well, i know that NVCC is very sensible to command line syntax. It interpret any non _well-forming_ commands as file name. Anyway, i found problem in property from which i removed _-openmp_ option.
Piece of `.\libtorch\share\cmake\Caffe2\Caffe2Targets.cmake`:
```cmake
set_target_properties(torch PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AT_PARALLEL_OPENMP=1"
  #INTERFACE_COMPILE_OPTIONS "/Z7;/EHa;/DNOMINMAX;/wd4267;/wd4251;/wd4522;/wd4522;/wd4838;/wd4305;/wd4244;/wd4190;/wd4101;/wd4996;/wd4275;/bigobj"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Program Files/NVIDIA Corporation/NvToolsExt/include;${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "protobuf::libprotobuf;c10;Threads::Threads;caffe2::mkl;torch::cudart;c10_cuda;C:/Program Files/NVIDIA Corporation/NvToolsExt/lib/x64/nvToolsExt64_1.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/lib/x64/cudart_static.lib;caffe2::cufft;caffe2::curand;caffe2::cublas;caffe2::cudnn"
)
```
If i comment out `INTERFACE_COMPILE_OPTIONS` property (already did that in code above), CMake successfully build project, so...

**Question 2: Where is the problem in syntax of this property?**

---------
### Environment:
- Windows 10
- VS2019 with compiler 19.24.28316 for x64 architecture
- PyTorch 1.4.0
- CUDA 10.1.168
- cuDNN 7.6.1.34
- CMake 3.15.19101501-MSVC_2
- NVIDIA GeForce GTX 1060 6GB
-----------
*Offtop question 3: is there some links where i can find info about reduce size of output files?*

**Comment by peterjc123** [comment]
Question 1 and 2:
Sorry, we don't currently support the new CUDA source support of CMake. You need to replace `project(torch-start LANGUAGES CXX CUDA)` with `project(torch-start LANGUAGES CXX)` and then use `find_package(CUDA)` and `cuda_add_executable` instead.

Offtop question 3:
What do you mean by that? Are you referring to the size of your library, or PyTorch? As for the former one, you may replace `/Z7` with `/Zi` in the compile flags. There's also a configuration set called `MinSizeRel` that you can try. If you are talking about the latter one, then you may try `set MSVC_Z7_OVERRIDE=OFF` and try to build it again.

**Comment by loolzaaa** [comment]
> You need to replace `project(torch-start LANGUAGES CXX CUDA)` with `project(torch-start LANGUAGES CXX)` and then use `find_package(CUDA)` and `cuda_add_executable` instead.

Thank you for answer! It works - project build without errors.

---------
*Offtop: may be my question is silly. Full size of my Release folder is ~1.2Gb, but i only add some numbers to random tensor. I asked about methods (links to articles may be) to reduce this size if it possible of course.*

*I will try what you propose, thanks.*
