### ISSUE TITLE
torch.tril_indices returns a float tensor on master

### ISSUE THREAD

**Issue by sdaulton** [pytorch/pytorch#33651]
## 🐛 Bug

`torch.tril_indices` returns a `torch.float32` tensor, but it should return an `torch.int64` tensor

## To Reproduce

1. Install pytorch master
2. Run the following code
```
import torch
print(torch.tril_indices(4,2).dtype)
print(torch.tril_indices(4,2, device=torch.device("cuda")).dtype)
```

## Expected behavior
This method should return an `torch.int64` tensor, but instead this method returns `torch.float32` tensor.

## Environment

PyTorch version: 1.5.0a0-fb
Is debug build: No
CUDA used to build PyTorch: 9.2.88

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.14.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
Nvidia driver version: 396.69

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by albanD** [comment]
High priority as it looks like a serious problem.

@sdaulton does specifying the dtype work? `print(torch.tril_indices(4,2, device=torch.device("cuda"), dtype=torch.long).dtype)` ?

**Comment by sdaulton** [comment]
Yes specifying the `dtype` works

**Comment by acairncross** [comment]
This seems to have been introduced in #33305. In particular, in the `tri[lu]_indices` functions, `options_.dtype_opt()` seems to have a float value (instead of having no value, which is what the code seems to expect).

**Comment by albanD** [comment]
cc @ezyang that did the PR and might have a better idea why this happens.

**Comment by acairncross** [comment]
Works fine using the C++ frontend btw

**Comment by ezyang** [comment]
It's because the Python frontend unconditionally fills in the default to be float. Let's revert the diff for now.

**Comment by albanD** [comment]
But why does it work on CPU then?

**Comment by ezyang** [comment]
It fails on both CPU and CUDA

**Comment by albanD** [comment]
I don't think so: `print(torch.tril_indices(4,2).dtype)` returns `torch.int64` for me.

**Comment by acairncross** [comment]
That's strange, are you sure? I get `torch.float32` for that

**Comment by albanD** [comment]
My bad, I messed-up updating my install to latest master. It does return a float32.
