### ISSUE TITLE
Error instaling using PIP and CUDA on windows 10

### ISSUE THREAD

**Issue by ammartist** [pytorch/pytorch#33654]
Hi,

When I try installing using this command:
pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
I get this error:

Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.4.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.4.0

I am using Windows Version 10.0.18363.657 i9 9900 and Cuda on 2080 ti

I hope someone can help in solving this.

thanks in advance

**Comment by peterjc123** [comment]
Please use 64-bit Python instead.

**Comment by ammartist** [comment]
Thanks a lot, it worked now ;-)
