### ISSUE TITLE
Still get this error--module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by jmq19950824** [pytorch/pytorch#33655]
I tried to reproduce the code from [https://github.com/samet-akcay/ganomaly](url) and run the commands in the git bash software. But I meet the following problems and it seems difficult for me to fix it by myself:

![image](https://user-images.githubusercontent.com/39890732/75091679-2367df80-55ab-11ea-8097-5617abd1910a.png)

**the main error is "AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'"**

1.
I tried to fix this problems by refering [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/360](url) and [https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/67](url)
that is, I change the code **torch.cuda.set_device(self.opt.gpu_ids[0])** to  **torch.cuda.set_device(self.opt.gpu_ids[-1])** and **torch._C._cuda_setDevice(device)** to **torch._C._cuda_setDevice(-1)**，but it still not works.

2.
I tried to reinstall the pytorch and update to the newest version (1.4.0), still exists error.

3.
I read the PyTorch Q&A and there may be some problems about my CUDA, I tried to add **--gpu_ids -1** to my code (that is, sh experiments/run_mnist.sh --gpu_ids -1, see the following picture), still exit error.
![image](https://user-images.githubusercontent.com/39890732/75091866-f9afb800-55ac-11ea-90bc-7f45dced0c60.png)

I was stucked by this problem by few days and I hope someone could help me. Thanks a lot!

**My PC is Windows 10 and only has a cpu.**

**Comment by peterjc123** [comment]
I don't think the function `torch._C._cuda_setDevice` or `torch.cuda.set_device` is  available in a cpu-only build. You may just comment it out.

**Comment by jmq19950824** [comment]
> I don't think the function `torch._C._cuda_setDevice` or `torch.cuda.set_device` is available in a cpu-only build. You may just comment it out.

Thanks for your answer. It seems part of these problems have been solved and the data is automatically downloaded when I run the codes. However, some new errors appear as follows:
![image](https://user-images.githubusercontent.com/39890732/75101894-e806f880-561e-11ea-945d-cf941b258877.png)

**And I wonder that if it may be impossible to run these codes in the cpu only computer?**

**Comment by peterjc123** [comment]
It seems that you need to add `--device cpu` in the command line to make it work. https://github.com/samet-akcay/ganomaly/blob/master/options.py#L40
BTW, I have to close this issue because it's not a problem of this repo. It's better to ask on https://github.com/samet-akcay/ganomaly.

**Comment by jmq19950824** [comment]
> It seems that you need to add `--device cpu` in the command line to make it work. https://github.com/samet-akcay/ganomaly/blob/master/options.py#L40
> BTW, I have to close this issue because it's not a problem of this repo. It's better to ask on https://github.com/samet-akcay/ganomaly.

OK. Thanks a lot.

**Comment by earlpeterg** [comment]
Be sure to install PyTorch with CUDA support. See instructions here https://pytorch.org/get-started/locally/
The default one installed is only with CPU support.

**Comment by droptpackets** [comment]
For those encountering this where the above is not working, adding this to the arguments resolved it for me when using torchrun:
--no_cuda=True

For some reason, my code was trying to use cuda even when my system does not support it.
