### ISSUE TITLE
type_as() method change device too

### ISSUE THREAD

**Issue by loolzaaa** [pytorch/pytorch#33662]
## 📚 Documentation
In documentation for `torch.Tensor` there is a method `type_as(tensor) → Tensor`. Original description:
>Returns this tensor cast to the **type** of the given tensor.
>
>**This is a no-op if the tensor is already of the correct type**. This is equivalent to self.type(tensor.type())

So, i think this method must only change **type** of the tensor if source tensor has **different** type, but it change **device** too.

### Actual behavior:
```python
>>> A = torch.rand((2, 3), device='cuda')
>>> A
tensor([[0.7261, 0.6957, 0.3470],
        [0.8001, 0.4091, 0.5418]], device='cuda:0')
>>> B = torch.randint(0, 4, (2,3))
>>> B
tensor([[0, 1, 0],
        [0, 3, 2]])
>>> A.type()
'torch.cuda.FloatTensor'
>>> A.device
device(type='cuda', index=0)
>>> B.type()
'torch.LongTensor'
>>> B.device
device(type='cpu')
>>> C = B.type_as(A)
>>> C
tensor([[0., 1., 0.],
        [0., 3., 2.]], device='cuda:0')
>>> C.type()
'torch.cuda.FloatTensor'
```
### Expected behavior:
```python
>>> C = B.type_as(A)
>>> C
tensor([[0., 1., 0.],
        [0., 3., 2.]])
>>> C.type()
'torch.FloatTensor'
>>> C.device
device(type='cpu')
```
Moreover, if both tensors have equal types and different devices, i expect no-op, but actually:
```python
>>> A
tensor([[0.7261, 0.6957, 0.3470],
        [0.8001, 0.4091, 0.5418]], device='cuda:0')
>>> B
tensor([[0.6601, 0.3256, 0.1848],
        [0.4785, 0.6826, 0.3101]])
>>> C = B.type_as(A)
>>> print(A.type(), '- device: ', A.device)
torch.cuda.FloatTensor - device:  cuda:0
>>> print(B.type(), '- device: ', B.device)
torch.FloatTensor - device:  cpu
>>> print(B.type(), '- device: ', B.device)
torch.cuda.FloatTensor - device:  cuda:0
```
**I think, that logically, `torch.FloatTensor` and `torch.cuda.FloatTensor` are the same, but technically not.** But in this case all types for CPU are not equal GPU types and method `type_as()` will always change the device.

**So, if this is not only my problem, i think need to change description of method.**

-----------
### Environment:
- Windows 10
- Python 3.8.1
- PyTorch 1.4.0
- CUDA 10.1.168
- cuDNN 7.6.1.34
- NVIDIA GeForce GTX 1060 6GB

cc @ezyang @gchanan @zou3519

**Comment by albanD** [comment]
That function should be deprecated and the doc updated.
Use `.to()` instead.

**Comment by loolzaaa** [comment]
Ok, if i want to change dtype `torch.cuda.FloatTensor` of tensor *A* to dtype `torch.LongTensor` of tensor *B*, i need to code this:
```python
>>> B.to(A.dtype)
```
------------------------
What about `type(dtype=None ...)` method? If i code `B.type(A.dtype)` then only dtype change, but if i code `B.type(A.type())` then device change too.

In documentation, first argument of type() method is:
> dtype (python:type or string) – The desired type  **<<< not tensor type object**

Strange situation... 
If i put dtype as first argument -> i change only dtype.
if i put tensor type object (**which does not accept by type() method in docs**) -> i change dtype and *device*.

**Comment by albanD** [comment]
Because `type()` is like `torch.cuda.FloatTensor`. Which contains both the device and dtype.
For backward compatibility, this function supports all of them. But the new `.to()` API should remove that confusion by only accepting clear arguments.

**Comment by loolzaaa** [comment]
Yep, i see that `.to()` throw an error if i put tensor type object as argument.

I think some explanations for the methods (`type(dtype ...)` and `type_as()`) would not hurt.

**Thanks for help!**
