### ISSUE TITLE
CUDA test failure on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#33660]
## 🐛 Bug

Error text:
```pytb

======================================================================
ERROR: test_zeros_like_cuda (__main__.TestTorchDeviceTypeCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 180, in instantiated_test
    return test(self, device_arg)
  File "test_torch.py", line 10208, in test_zeros_like
    expected = torch.zeros((100, 100,), device=device)
RuntimeError: CUDA error: unspecified launch failure

======================================================================
ERROR: setUpClass (__main__.TestViewOpsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_device_type.py", line 235, in setUpClass
    t = torch.ones(1).cuda()
RuntimeError: CUDA error: unspecified launch failure

----------------------------------------------------------------------
Ran 3782 tests in 137.305s
```
Details in https://app.circleci.com/jobs/github/pytorch/pytorch/4570311

## To Reproduce

1. python run_test.py -i torch

## Expected behavior

Test passes.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): source
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla P4
 - Any other relevant information:

## Additional context

It seems that https://github.com/pytorch/pytorch/pull/32534 is the cause. Usually, this is caused by the SFINAE in NVCC under Windows, just like sth. in https://github.com/pytorch/pytorch/issues/31108. It is really annoying that it doesn't raise compile errors but crash during runtime. cc @ezyang @pbelevich

**Comment by pbelevich** [comment]
sorry, my fault, unlanding #32534

**Comment by pbelevich** [comment]
#32534 unlanded and CUDA tests on Windows are good
