### ISSUE TITLE
Is a there a function like np.vectorize() that can realize an efficient value mapping?

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#33671]
Hi, guys,
I am learning about semantic segmentation these days,
and  I need to map a matrix into another according to some rules,
like mapping the ids into trainIds, as 
![微信图片_20200223164520](https://user-images.githubusercontent.com/27288110/75110986-c4b86980-566f-11ea-9d6f-f399ac60705e.png)

And in numpy, we have a function of `np.vectorize()`  to do the mapping.
So, I want to know whether there is a function like `np.vectorize()` that can realize an efficient value mapping?

Any answer or idea will be appreciated!

**Comment by albanD** [comment]
Hi,

Cross post from the forum: https://discuss.pytorch.org/t/how-to-realize-the-function-of-looking-up-table-with-pytorch-in-a-most-efficient-way/70747

We only answer questions on the forum and we use git issues only for bug/features. So we will answer there.
