### ISSUE TITLE
python int type how to convert to at::IntArrayRef

### ISSUE THREAD

**Issue by zhryang** [pytorch/pytorch#33673]
## ❓ Questions and Help
When I write C++/CUDA extension, I use at::IntArrayRef in my C++ source code. But I build custom layer using python, I find that I do not use my C++ extension. Because int of python does not convert to at::IntArrayRef of C++. How to solve this problem?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

As mentioned in the template in your message, you should use [the forum](https://discuss.pytorch.org/) to ask questions. This issue tracker is only used for issues/features.
