### ISSUE TITLE
torch.Tensor does not have zeros_like_

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#33698]
## 🐛 Bug

in generated `torch/__init__.pyi`, there are several `zeros_like_`, `zeros_like__`, and so on. However, actual `torch.Tensor` does not have those methods.

## Expected behavior

I think `zeros_like_+` should be removed.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.7.4
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

**Comment by ngimel** [comment]
Thank you for your report, we will accept a PR fixing this.
