### ISSUE TITLE
C++ RNN options is now a protected member of torch::nn::RNNImpl

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#33694]
## 🐛 Bug

With PR #33027, the fix to allow Sequential to call forward with default args skipped,
the options element in RNNImpl is protected (was public before)

```
 protected:
  FORWARD_HAS_DEFAULT_ARGS({1, AnyValue(Tensor())})

  RNNOptions options;
```

cc @yf225

**Comment by ngimel** [comment]
cc @yf225

**Comment by yf225** [comment]
@meganset Thanks a lot for the bug report! It should be fixed by https://github.com/pytorch/pytorch/pull/33718 and I will land the fix today.
