### ISSUE TITLE
No bfloat16 method in torch.Tensor stubs

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#33699]
## 🐛 Bug

There is [a documentation for `bfloat16` method](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.bfloat16), but `bfloat16` does not exist in type stub.

## Expected behavior

`torch.Tensor` should have `bfloat16` method.

## Environment

 - PyTorch Version (e.g., 1.0): master branch
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py develop`
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ngimel** [comment]
`.bfloat16()` method that you link in the documentation exists (e.g. `x.bfloat16()` works) - did you mean something else?

**Comment by jeongukjae** [comment]
> `.bfloat16()` method that you link in the documentation exists (e.g. `x.bfloat16()` works) - did you mean something else?

I mean type stub! In generated __init__.pyi, there is no bfloat16 method. It works and has docs, but no stub.

**Comment by ngimel** [comment]
Would you mind submitting a PR to fix this?

**Comment by jeongukjae** [comment]
> Would you mind submitting a PR to fix this?

I will create a PR for this. :)
