### ISSUE TITLE
[cpp_extension] should allow ccache g++ in checks

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#33701]
I am on Ubuntu, with `g++` symlinked to `.../ccache/bin/ccache`. 

Yet the `cpp_extension` code check that the compiler binary is one of `['g++', 'gcc', 'gnu-c++', 'gnu-cc']`, and would issue a warning from
https://github.com/pytorch/pytorch/blob/e3ba533c8b5842df370c4bff3e552895cff22e98/torch/utils/cpp_extension.py#L178-L194

That is, `torch.utils.cpp_extension.check_compiler_abi_compatibility('g++')` gives 
```
XXXXXX/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
```

cc @yf225

**Comment by ngimel** [comment]
Thanks for a report, we'll accept a PR fixing this.

**Comment by lkskstlr** [comment]
@ngimel I have made a PR for this and would be happy to hear your opinion and potentially improve the pull request.
