### ISSUE TITLE
Multi-gpu training with custom dataset

### ISSUE THREAD

**Issue by tiberium24** [pytorch/pytorch#33728]
Hello,

I created a custom dataset list exactly using your example at the end of this link: (https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html)

It looks like this:
data_list = [Data(...), ..., Data(...)]

I then try to use DatalistLoader instead of Dataloader to perform multi-gpu training but they dont seem to be compatible. What is the way to do it based on the data I provide?

**Comment by ngimel** [comment]
Please use forums for questions like this, discuss.pytorch.org
