### ISSUE TITLE
Is there a way to specify the -j flag for number of threads used to build the library?

### ISSUE THREAD

**Issue by JasonRuonanWang** [pytorch/pytorch#33731]
In my environment when I run setup.py it automatically uses -j 128 to run cmake and build the the library. The number is too large and I don't have enough memory to compile.

**Comment by taras-sereda** [comment]
Hi, you can specify number of parallel build jobs by setting `MAX_JOBS` env variable
this should work: `env MAX_JOBS=4 python setup.py build`

**Comment by ngimel** [comment]
Closing, the answer above is the right one.
