### ISSUE TITLE
CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)

### ISSUE THREAD

**Issue by alexwq100** [pytorch/pytorch#33741]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/45087291/75208219-eae82180-57b5-11ea-86cc-ccb9e81c9617.png)

## To Reproduce
  I check many times, it seems it is the out of index error ,but when I try to debug,all the data in the gpu can't be accessed.

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
PyTorch Version 1.1
docker container centos
conda install
Python version: Python 3.7.2
CUDA/cuDNN version: cuda-10.1
GPU models and configuration: p100
Any other relevant information:
You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by alexwq100** [comment]
![image](https://user-images.githubusercontent.com/45087291/75209954-b034b800-57ba-11ea-8994-845bcfb39ab4.png)
And from this, it is seen the tensor crashed?

**Comment by ngimel** [comment]
Yes, the error is in the indexing kernel, you are supplying an out-of-range index. This is typically caused by invalid user-supplied data. If you want to debug, you have to inspect data before the indexing call that causes a crash, because afterwards the context is invalidated. 
Please provide a minimum reproducible example to help us debug the issue.

**Comment by alexwq100** [comment]
![image](https://user-images.githubusercontent.com/45087291/75220486-81c6d500-57da-11ea-9e55-d2429876b40c.png)


![image](https://user-images.githubusercontent.com/45087291/75220502-8ab7a680-57da-11ea-8308-f2e587132317.png)
The error is very weird. please see the first figure. in order to judge ,bbox_target_list is a list of tensor,  I get one tensor in the list indexed by the map_level, and want to get its dimension to make sure sys is not out of the tensor bound(sys is the index I want to fetch in the tensor index by the map_level). But the error reported. So I notice at that time, before I fetch the element in the tensor ,I just get its dimension, the error reported. so at that time ,the tensor list (i.e. bbox_target_list) crashed already. I am very confused.


![image](https://user-images.githubusercontent.com/45087291/75220502-8ab7a680-57da-11ea-8308-f2e587132317.png)
The error is very weird. please see the first figure. in order to judge ,bbox_target_list is a list of tensor,  I get one tensor in the list indexed by the map_level, and want to get its dimension to make sure sys is not out of the tensor bound(sys is the index I want to fetch in the tensor index by the map_level). But the error reported. So I notice at that time, before I fetch the element in the tensor ,I just get its dimension, the error reported. so at that time ,the tensor list (i.e. bbox_target_list) crashed already. I am very confused.

**Comment by ngimel** [comment]
The error is not weird, it means you are passing invalid indices to your indexing operation, as the error message says. Please inspect indices and tensor sizes before indexing operation.
