### ISSUE TITLE
pad_packed_sequence doc improvement

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#33746]
## 📚 Documentation

torch/nn/utils/rnn.html:

`pad_packed_sequence` doc has a confusing stand-alone statement in the description of the function:

> Batch elements will be ordered decreasingly by their length.

Ordered when and where? 

On the contrary the padded output is "unsorted" to how it was originally sorted when `pack_padded_sequence` or `pack_sequence` were called. So the statement in question is only correct if the original sequence was ordered decreasingly by the length of its elements and isn't necessarily the case with `enforce_sorted=False`.

Perhaps it should say instead:

> Batch elements will be re-ordered as they were ordered originally when the batch was passed to `pack_padded_sequence` or `pack_sequence`.

But then it's possible that  `sequence.unsorted_indices` is `None`, in which case no sorting will happen.

And perhaps the sorting note would be better serving in the `Returns` part of the description?

Example:

```
seq = torch.tensor([[1,2,3,0], [4,5,0,0], [6,3,5,1]])
lens = [3, 2, 4]
packed = pack_padded_sequence(seq, lens, batch_first=True, enforce_sorted=False)
packed
seq_unpacked, lens_unpacked = pad_packed_sequence(packed, batch_first=True)
seq_unpacked
lens_unpacked
```
```
PackedSequence(data=tensor([6, 1, 4, 3, 2, 5, 5, 3, 1]), batch_sizes=tensor([3, 3, 2, 1]), sorted_indices=tensor([2, 0, 1]), unsorted_indices=tensor([1, 2, 0]))
tensor([[1, 2, 3, 0],
        [4, 5, 0, 0],
        [6, 3, 5, 1]])
tensor([3, 2, 4])
```
i.e. everything is nicely restored to the original order (which is not ordered by lengths).

Thank you.

**Comment by ngimel** [comment]
Thank you, those are valid points. Would you mind submitting a PR that improves documentation?

**Comment by stas00** [comment]
Thank you for your follow up, @ngimel 

So would something like the following be OK:

> Batch elements will be re-ordered as they were ordered originally when the batch was passed to `pack_padded_sequence` or `pack_sequence`. If `sequence.unsorted_indices` is `None`, the padded output will be returned unsorted.

Should I include the example as well?

**Comment by ngimel** [comment]
This sounds good, and example is definitely useful. Nit: `unsorted_indices` can be `None` only if your lengths were originally sorted in decreasing order, so in this case, I think, padded input will be returned sorted by decreasing sequence length rather than unsorted. It still will be in the order it was passed to `pack_padded_sequence`.

**Comment by stas00** [comment]
Thank you for your useful commentary, @ngimel.
PR: https://github.com/pytorch/pytorch/pull/33768
