### ISSUE TITLE
The docs of `MultiplicativeLR` use `LambdaLR` as example

### ISSUE THREAD

**Issue by HearyShen** [pytorch/pytorch#33752]
## 📚 Documentation

The docs of `MultiplicativeLR` use `LambdaLR` as example, instead, `MultiplicativeLR` itself should be used.

The issue exists in docs of `MultiplicativeLR`:

https://github.com/pytorch/pytorch/blob/4460c8b034f8fd544ff9c271c4aa21698644d352/torch/optim/lr_scheduler.py#L238-L257

in line 252, it should use `MultiplicativeLR` as example: 

https://github.com/pytorch/pytorch/blob/4460c8b034f8fd544ff9c271c4aa21698644d352/torch/optim/lr_scheduler.py#L252

It seems that this example was copied from `LambdaLR` but hasn't been correctly edited.

**Comment by ngimel** [comment]
Thank you for your report. Would you mind submitting a PR to fix the issue?

**Comment by HearyShen** [comment]
FYI, the PR(#33805)  has been submitted.

**Comment by mruberry** [comment]
PR landed. Thanks again, @HearyShen!
