### ISSUE TITLE
[minor] support reversed(torch.Tensor)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#3376]
```python
sorted(torch.Tensor([3, 2, 1])) # works

reversed(torch.Tensor([3, 2, 1])) # doesn't 
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#TypeError: argument to reversed() must be a sequence

reversed(np.array([3, 2, 1])) # works
#<reversed object at 0x7f2ea830b290>
```

This can be addressed by implementing [`__reversed__`](https://bugs.python.org/issue18826) magic.

(Workaround, of course, is `reversed(list(torch.Tensor([3, 2, 1])))`)

**Comment by apaszke** [comment]
Note that `sorted(tensor)` is a bad idea. `torch.sort` is likely to be a lot faster

**Comment by vadimkantorov** [comment]
Valid point. I stumbled upon this when converting some code dealing with small indices NumPy arrays with strides -1 (which aren't currently supported).
