### ISSUE TITLE
Multiplying a complex scalar to a non-complex tensor outputs tensor with only real values

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#33780]
>>> torch.ones(2,2)*2
tensor([[2., 2.],
        [2., 2.]])
>>> torch.ones(2,2)*2j
tensor([[0., 0.],
        [0., 0.]])
>>> torch.tensor([[1,1],[1,1]], dtype=torch.complex64)*2j
tensor([[(0.0000 + 2.0000j), (0.0000 + 2.0000j)],
        [(0.0000 + 2.0000j), (0.0000 + 2.0000j)]], dtype=torch.complex64)
>>> torch.ones(2,2)*(1+2j)
tensor([[1., 1.],
        [1., 1.]])

cc @ezyang @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
Sounds like a promotion bug :)
