### ISSUE TITLE
random_() is not supported for bfloat16 CUDA tensors on Windows

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#33793]
This is a known issue, that requires further investigation, currently calling any random_() method on bfloat16 CUDA tensor on Windows makes CUDA context invalid, all subsequent CUDA calls fail with 'CUDA error: unspecified launch failure'

Assignee, please look for "TODO: https://<span></span>github.com/pytorch/pytorch/issues/<span></span>33793" in the source code

cc @ngimel

**Comment by peterjc123** [comment]
@pbelevich I solved an issue that may be related to this in https://github.com/pytorch/pytorch/pull/37302. Would you please try again based on that PR?
