### ISSUE TITLE
How to release the gpu memory after use interpolate？

### ISSUE THREAD

**Issue by lyc6749** [pytorch/pytorch#33809]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

 After used the interpolate ，the gpu memory can not be released during inference。I try to use torch.cuda.empty_cache() after, but it can work only in feding the images one by one。when theimages is concurrently fedding ，the GPU still increase。Can you tell me how to do？

**Comment by mruberry** [comment]
Hi @lyc6749, thanks for your question. Please ask it on the forums: https://discuss.pytorch.org/. They're very active and the best place to get an answer to your question.
