### ISSUE TITLE
Transformer to ONNX: we don't have an op for aten::uniform but it isn't a special case.

### ISSUE THREAD

**Issue by bhaveshkr** [pytorch/pytorch#33813]
## 🐛 Bug

I've trained a transformer_iwslt_de_en model and loaded using TransformerModel.from_pretrained. I'm getting runtime error (aten:uniform is not available) while exporting to ONNX. Am I missing something? Or It is the expected behaviour at the moment.

## To Reproduce

Load the pre-trained transformer_iwslt_de_en model and export it to ONNX.

src_tokens = torch.LongTensor(batch_size, max_seq_length).to(device)
src_lengths = torch.LongTensor(batch_size).to(device)
prev_output_tokens = torch.LongTensor(batch_size, max_seq_length).to(device)
onnx_file = "model.onnx"        

torch.onnx.export(model,
                      (src_tokens, src_lengths, prev_output_tokens),
                      onnx_file,
                      input_names = ["src_tokens", "src_lengths", "prev_output_tokens"],
                      output_names = ["output"],
                      verbose=True)

## Error log
RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::uniform but it isn't a special case. (analyzeImpl at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/jit/passes/alias_analysis.cpp:300)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fdc68933627 in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x3cc822b (0x7fdc6e2a022b in /root/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so)

## Expected behavior
Working torch.onnx.export method for Transformer based Machine Translation model.

## Environment
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] pytorch-pretrained-bert==0.6.2
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-pretrained-bert   0.6.2                    py37_0    conda-forge
[conda] torchvision               0.5.0                py37_cu101    pytorch

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by suo** [comment]
cc @spandantiwari

**Comment by artmatsak** [comment]
Same issue here when exporting a BART model.

**Comment by vprelovac** [comment]
+1

**Comment by pthinh14** [comment]
I am facing the same issue. Any update?

**Comment by spandantiwari** [comment]
From the error stack, this doesn't seem to be an ONNX Runtime error. I have updated the title to reflect that. 

@suo @eellison - This error seems to be coming from the alias analysis pass. Would it be possible for you to take a first look?

`RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::uniform but it isn't a special case. (analyzeImpl at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/jit/passes/alias_analysis.cpp:300)
`

**Comment by eellison** [comment]
This is the same issue as https://github.com/pytorch/pytorch/issues/39575#issuecomment-640921180 - `_jit_pass_onnx_prepare_inplace_ops_for_onnx` is invalidating the IR by insert schemas thaat don't exist

**Comment by garymm** [comment]
@bhaveshkr is this still an issue with the latest PyTorch nightly?
If so, could you please provide code that we can use to reproduce?
In particular please provide code for `Load the pre-trained transformer_iwslt_de_en model`.

**Comment by BowenBao** [comment]
Hi @vprelovac @bhaveshkr @artmatsak,

We’ve gone ahead and closed this issue because it is stale, and it is likely resolved like https://github.com/pytorch/pytorch/issues/39575 in later PyTorch releases.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team

**Comment by fxmarty** [comment]
@BowenBao Hi, the issue still exists:

```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::uniform' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

**Comment by Cai-RS** [comment]
> @BowenBao Hi, the issue still exists:
> 
> ```
> torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::uniform' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
> ```
> 
> An alternative is to use `aten::rand` or `aten::randint` that are supported.

Hello! I also got this issue when I tried converting an old pytorch model to ONNX, but could not find which torch functions call the  aten::uniform op.... Could you tell me which functions may call this op?

**Comment by rajeshgangireddy** [comment]
Facing the same issue. How do I figure out which of the torch functions I use call the aten::uniform operator?
