### ISSUE TITLE
Redirect docs.pytorch.org to pytorch.org/docs

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#33820]
This page is 404:
http://docs.pytorch.org/

This can be confusing, and we should issue a redirect to pytorch.org/docs

cc @ezyang @gchanan @zou3519

**Comment by VitalyFedyunin** [comment]
@soumith is it related to the cloudfare move?

**Comment by soumith** [comment]
hopefully should be fixed in a few hours. there was a spurious DNS record (from the CloudFlare migration) that was overriding my Page Rule

**Comment by colesbury** [comment]
This appears to still be broken

**Comment by colesbury** [comment]
@soumith this is still broken

**Comment by soumith** [comment]
I changed some settings, and it seems to be fixed.

I tested it locally as well as with screenshotmachine.com
