### ISSUE TITLE
change dtype for scales/zero_points in per channel quantization to float Tensor and int Tensor

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#33827]
Currently it's double and long since previously we are using python list and python only have double and long, now that we have changed type of scale/zero_point to Tensor, we can have float Tensor and int Tensor now.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by andrewor14** [comment]
Closing this in favor of https://github.com/pytorch/pytorch/issues/106432, which is based on more recent discussions
