### ISSUE TITLE
Method overrides and instantiate_device_type_tests don't play nicely

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#33821]
Steps to reproduce:
1. Add an override to `assertEqual` in a class that is instantiated by `instantiate_device_type_tests`
2. Run the test and see if your override is called

Expected result: It is called
Actual result: it is not

cc @mruberry

**Comment by ezyang** [comment]
This is because the determination of members per

```
    generic_members = set(dir(generic_test_class)) - set(dir(empty_class))
    generic_tests = [x for x in generic_members if x.startswith('test')]
```

will exclude all members that already exist on the parent class. Thus, overriding is not possible.

**Comment by mruberry** [comment]
Yep. Thanks Ed! I'll fix this.

**Comment by ezyang** [comment]
@mruberry Here's what I'm using locally to work around:

```
diff --git a/torch/testing/_internal/common_device_type.py b/torch/testing/_internal/common_device_type.py
index 16acff7c80..a1e90dffe7 100644
--- a/torch/testing/_internal/common_device_type.py
+++ b/torch/testing/_internal/common_device_type.py
@@ -270,7 +270,7 @@ def instantiate_device_type_tests(generic_test_class, scope, except_for=None):
     empty_class = type(empty_name, generic_test_class.__bases__, {})
 
     # Acquires members names
-    generic_members = set(dir(generic_test_class)) - set(dir(empty_class))
+    generic_members = set(generic_test_class.__dict__.keys()) - set(empty_class.__dict__.keys())
     generic_tests = [x for x in generic_members if x.startswith('test')]
 
     # Creates device-specific test cases
@@ -294,7 +294,7 @@ def instantiate_device_type_tests(generic_test_class, scope, except_for=None):
                 # Instantiates the device-specific tests
                 device_type_test_class.instantiate_test(name, test)
             else:  # Ports non-test member
-                assert not hasattr(device_type_test_class, name), "Redefinition of non-test member {0}".format(name)
+                assert name not in device_type_test_class.__dict__, "Redefinition of directly defined member {0}"
.format(name)
 
                 # Unwraps to functions (when available) for Python2 compat
                 nontest = getattr(generic_test_class, name)
```

**Comment by mruberry** [comment]
Haha, do you just want to submit a PR, @ezyang?

**Comment by ezyang** [comment]
If you like my modification I can roll it up with the work I'm doing

**Comment by mruberry** [comment]
Let me test a few things and I'll let you know.

**Comment by ezyang** [comment]
There is a submarine problem with the patch, btw, which is that `super(classname, self)` doesn't work as we removed `classname` from `globals()` so it's out of scope. So you have to hardcode the superclass to call.

**Comment by mruberry** [comment]
I like your patch. You can also invoke the non-overridden methods like by calling super like this: `super(self.__class__, self)`. I also looked at a few variants but I think your approach preserves the assertion best.

What do you think about adding a note to your PR explaining the super behavior?

**Comment by ezyang** [comment]
> You can also invoke the base classes' methods by calling super like this: super(self.__class__, self).

This is wrong though, right? Because `self.__class__` will dynamically changed based on what self actually is, if you subclass it more.

Note sounds good, I'll add it soon.

**Comment by mruberry** [comment]
It's true that `self.__class__` changes dynamically, although I think I would be interested in a scenario where someone inherits from a class created at runtime by the generic test framework and gets an unexpected result here. Your proposal sounds great, though: let's just go with that.
