### ISSUE TITLE
RFC: JIT C++ source code reorganization

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#33828]
Right now the, the layout of `torch/csrc/jit/` is pretty random. It's mostly flat, with some folders that may or may not make sense.

I propose reorganizing the JIT source tree to better reflect the actual components of the JIT. There are three goals for this reorg:
1. Help newcomers navigate the JIT codebase by providing hints about the structure. Experienced JIT developers probably know what file they need and can fuzzy search for it, thus the physical layout of the code is largely irrelevant to them.
2. Provide a high-level structure to help guide design. If your `frontend/foo.cpp` is depending on `runtime/bar.h`, this is a signal to reviewers that there may be unnecessary coupling.
3. Not be so complicated that it introduces friction. It should be super obvious from a quick `ls` which folder your file should go in.

The proposed layout:
- `frontend/`: lexer/parser/ir emitter,…
- `runtime/`: graph executor, interpreter,…
- `serialization/`: import/export, python_print
- `passes/`: passes
- `api/`: Any user-facing C++/Python construct: `Module`, `Method`, `Function`, etc.
- `python/`: Python bindings and python-only code
- `codegen/`: `fuser/`, `tensor_expr/`, etc.
- `testing/`: testing utilities
- `mobile/`: mobile specific code (lite interpreter, etc.)
- `ir/`: core IR abstractions and utils (`ir.h`, `ir_views.h`, etc.)

Here is a [complete mapping](https://gist.github.com/suo/dad6f29852aabd8a3b2e0bbc4aa8af91) of files to their new locations.

cc @suo

**Comment by jamesr66a** [comment]
LGTM.

Where does Operator-related stuff go? e.g. `register_prim_ops`

**Comment by suo** [comment]
ccing frequent contributors to this part of the code:
@zdevito, @ezyang, @jamesr66a, @eellison, @driazati, @ZolotukhinM, @t-vi, @jerryzh168, @Krovatkin, @xuhdev, @spandantiwari, @jjlilley, @ljk53, @iseeyuan, @ailzhang, @wanchaol

**Comment by suo** [comment]
> Where does Operator-related stuff go? e.g. `register_prim_ops`
today they are in `runtime`. They do cut across things so I am not sure about that placement. Conceivably: a separate `operators` folder?

**Comment by eellison** [comment]
LGTM. one suggestion is to have python-only files mirror the rest of the file structure, so for instance `python_sugared_value.cpp` would be `python/frontend/python_sugared_value.cpp`. but i don't care that much, in general i would say this is an improvement and we can always separately merge follow ups instead of holding this up.

**Comment by t-vi** [comment]
Sounds great.

**Comment by driazati** [comment]
This sounds pretty good. It’d also be nice if we could get rid of the `docs` folder and break it up into readmes distributed into the corresponding folder. (maybe now is also good time for file owners to update those docs)

**Comment by spandantiwari** [comment]
cc: @houseroad @BowenBao @lara-hdr

**Comment by suo** [comment]
Closing as this has landed. Thanks for the comments, I'll work on addressing them!
