### ISSUE TITLE
Scalablity of concurrent pytorch models

### ISSUE THREAD

**Issue by riyadshairi979** [pytorch/pytorch#33822]
Hi, what is a good way to utilize all threads when running multiple pytorch models. For example, if I run inference on one single model like below, all threads do almost equal amount of work.

```
at::init_num_threads();
module.run_method("forward", data, h0, c0);
```

But if I run multiple models like below, one thread gets heavily loaded.<br/>

```
at::init_num_threads();
for (int32_t i = 0; i < n_models; i++) {
    int32_t model_id = rand() % n_models;
    at::IValue outputs = module[model_id].run_method("forward", data, h0, c0);
}
```
Any suggestion, on how to configure/design etc.?

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Please see this note https://pytorch.org/docs/master/notes/cpu_threading_torchscript_inference.html and also ask questions on the forums (discuss.pytorch.org)/

**Comment by riyadshairi979** [comment]
From that note I can see that we can use torch.jit._fork() to do parallel execution of forward() methods in my loop. But what is the equivalent forking function in C++ libtorch runtime?

**Comment by riyadshairi979** [comment]
> Please see this note https://pytorch.org/docs/master/notes/cpu_threading_torchscript_inference.html and also ask questions on the forums (discuss.pytorch.org)/

From that note I can see that we can use torch.jit._fork() to do parallel execution of forward() methods in my loop. But what is the equivalent forking function in C++ libtorch runtime?
