### ISSUE TITLE
Performance improvement of qmul/qadd_scalar/qmul_scalar

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#33843]
## 🐛 Bug
Currently, the implementation of these quantized op are not vectorized. It shows very low performance when running on X86 CPU. We need to add vectorized version with tensor iterator.

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by dskhudia** [comment]
qmul and qadd_scalar are optimized in the following PRs. 
https://github.com/pytorch/pytorch/pull/34925
https://github.com/pytorch/pytorch/pull/34834

**Comment by vkuzo** [comment]
closing as the issue seems to be closed by @dskhudia 's PRs.  Please reopen if we need more work here.
