### ISSUE TITLE
[minor] Support F.normalize on 1-dim vectors without explicit dim

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#3385]
Because of default dim = 1, `normalize` fails on vectors.

```python
torch.nn.functional.normalize(torch.autograd.Variable(torch.rand(10)))
# RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```

My two cents is that if a default dim is at all supported, this is the most reasonable case where it makes sense (same issue with softmax). Yet I remember many discussions about this (e.g. wrt softmax refactoring), so feel free to close it if the decision was taken. The docs faithfully mention: "With default arguments normalizes over the *second* dimension with Euclidean norm."

(the simple workaround is `torch.nn.functional.normalize(torch.autograd.Variable(torch.rand(10)).unsqueeze(0)).squeeze(0)`)

**Comment by soumith** [comment]
we dont have an expectation for torch.nn to work on non-minibatches. I think this behavior is okay, as the error message is clear.

**Comment by vadimkantorov** [comment]
Should I reopen this when Tensors and Variables are unified?

@apaszke [mentioned](https://github.com/pytorch/pytorch/issues/3305#issuecomment-339689454) that after the unification `functional` functions will automatically work on tensors (in fact `normalize` already works on tensors now), and then it makes more sense to support it.

**Comment by vadimkantorov** [comment]
works in master
