### ISSUE TITLE
Can't save to ostream using documentation example

### ISSUE THREAD

**Issue by JesperLindberg** [pytorch/pytorch#33862]
## 🐛 Can't save to ostream

I want to save my model as a `istream` for later processing.
I found the following on the api:

https://pytorch.org/cppdocs/api/function_namespacetorch_1a99dc9f736064b2179cc58e6436f7a021.html#exhale-function-namespacetorch-1a99dc9f736064b2179cc58e6436f7a021

https://pytorch.org/cppdocs/api/function_namespacetorch_1a4b369494adfb10b9a005aeb0bb6207cb.html#exhale-function-namespacetorch-1a4b369494adfb10b9a005aeb0bb6207cb

## To Reproduce
`torch::optim::SGD sgd(0.9);` give me error: 

>Error (active)	E0289	no instance of constructor "torch::optim::SGD::SGD" matches the argument list

## Environment

 - PyTorch Version (e.g., 1.0): LibTorch 1.4
 - OS (e.g., Linux): Windows 7 64 bit
 - How you installed PyTorch (`conda`, `pip`, source): source: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.4.0.zip
 - Build command you used (if compiling from source): cmake --build . --config Release --target INSTALL
 - Python version: 3.6
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

cc @yf225

**Comment by peterjc123** [comment]
cc @yf225

**Comment by yf225** [comment]
@anjali411 Would you like to take a look at this?

**Comment by anjali411** [comment]
Hi @JesperLindberg sorry about this. this seems like a documentation issue (cc. @yf225 ). you will need to input the params(or param_groups) and options to initialize the sgd optim. this should work
```
auto model = torch::nn::Linear(5, 2);
auto params = model1->parameters();
torch::optim::SGD sgd(params, 1e-1); 
```
