### ISSUE TITLE
Scalar cuda Tensors are automatically moved to different device

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#33870]
Scalar cuda Tensors are automatically casted to the right device.
This enables automatic device copy. But the autograd does not expect that to be possible.

```python
import torch

torch.autograd.set_detect_anomaly(True)

a = torch.rand([], requires_grad=True, device="cuda:0")
b = torch.rand(10, requires_grad=True, device="cuda:1")

c = a * b
c.sum().backward() # Fails
# RuntimeError: Function MulBackward0 returned an invalid gradient at index 0 - expected device cuda:0 but got cuda:1 (validate_outputs at /opt/conda/conda-bld/pytorch_1582704525289/work/torch/csrc/autograd/engine.cpp:477)
```

Is the forward behavior expected? 
If so, then we need to fix the autograd engine.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by ailzhang** [comment]
I'd vote for errorring out for forward. ;) 
Looks like it worked only because of empty storage. 
```
In [4]: torch.autograd.set_detect_anomaly(True)
   ...:
   ...: a = torch.rand([1], requires_grad=True, device="cuda:0")
   ...: b = torch.rand(10, requires_grad=True, device="cuda:1")
   ...:
   ...: c = a * b
^M---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-adbfbf0fa06f> in <module>
      4 b = torch.rand(10, requires_grad=True, device="cuda:1")
      5
----> 6 c = a * b

RuntimeError: expected device cuda:0 but got device cuda:1
```

**Comment by ailzhang** [comment]
Update from chat with @ngimel : 
```
torch.tensor(3, device='cpu') * torch.rand(2, 2, device='cuda')
torch.tensor(3, device='cuda') * torch.rand(2, 2, device='cpu')
``` 
Also works and expected...
autograd also failed in those cases
```
import torch

a = torch.tensor(3., device='cuda', requires_grad=True)
b = torch.rand(2, 2, device='cpu')
c = a + b
c.sum().backward()
print(a.grad)
```

**Comment by albanD** [comment]
The auto-casting is not a problem in itself, but the backward formula are for the function without the auto-casting.
So if this auto-casting is considered valid in the forward, we have to find a way for the backward formula to match.

**Comment by colesbury** [comment]
We should support this in autograd:

1) For backwards compatibility. There's likely code that depends on this (in the "forward" pass).
2) Even before we supported mixed-type operations, we supported mixing types with a scalar. The same logic applies to devices.

It should be fixable at the place where the error is raised in the autograd engine, without too much work. If the `output_device != metadata.device()` (and the shape is a scalar), just copy to the metadata.device().

**Comment by Baranowski** [comment]
I'm on it. For the record, in the latter case the exception raised is different:

```
Traceback (most recent call last):
  File "test_scalar_move.py", line 16, in <module>
    c.sum().backward()
  File "/home/wbaranowski/git/Quansight/pytorch/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/wbaranowski/git/Quansight/pytorch/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function AddBackward0 returned an invalid gradient at index 0 - expected type TensorOptions(dtype=float, device=cuda:0, layout=Strided, requires_grad=false) but got TensorOptions(dtype=float, device=cpu, layout=Strided, requires_grad=false) (validate_outputs at ../torch/csrc/autograd/engine.cpp:505)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x46 (0x7faa78e38526 in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2ae4799 (0x7faa97cb2799 in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x548 (0x7faa97cb4428 in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3ee (0x7faa97cb63de in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_init(int) + 0x39 (0x7faa97cae5a9 in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7faa9a7ab168 in /home/wbaranowski/git/Quansight/pytorch/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xc8163 (0x7faa9ccb9163 in /home/wbaranowski/miniconda3/envs/pytorch-cuda-dev/lib/./libstdc++.so.6)
frame #7: <unknown function> + 0x76db (0x7faacc7d06db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x3f (0x7faacc4f988f in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by albanD** [comment]
@colesbury I would argue that given that it is the op that does the casting in the forward pass, it should be the op that does the casting in the backward pass as well. Not the engine.
You don't think so?

**Comment by ngimel** [comment]
Autograd engine is already summing to the necessary shape and casting to the necessary type, to account for broadcasting and type promotion that the op did in forward. Is moving across devices conceptually different?

**Comment by colesbury** [comment]
@albanD I think it will be easier to implement this as part of the engine and simpler to maintain. I think the situation is similar to broadcasting. Originally, we implemented broadcasting per-op, without any broadcasting logic in the autograd engine. This turned out to be hard to maintain: you have a mix of complicated derivative expressions and conservative calls to sum and casting.

**Comment by albanD** [comment]
Ok,
As a side note: This code (and the broadcasting one) should be careful about setting the grad mode properly otherwise higher order derivatives won't work.
