### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by kekeshukk** [pytorch/pytorch#3389]
It will occur an error when I type "import torch".
but if I build at another location,no errors occur.
this is the message:
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'torch'

**Comment by apaszke** [comment]
I'm not sure exactly what you did. If you run `python setup.py install` then it is expected that you have to move to a different directory to use PyTorch. This is a user error and not a bug. I'm closing the issue.
