### ISSUE TITLE
implement tensor copy from list and from numpy.ndarray

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#339]
Suggestions from @yuandong-tian 

RuntimeError: copy from list to FloatTensor isn't implemented
RuntimeError: copy from numpy.ndarray to FloatTensor isn't implemented

**Comment by weiyangfb** [comment]
Has this been fixed already?

**Comment by fmassa** [comment]
I think this can be obtained with `torch.tensor`, but I might be misunderstanding the meaning of copy here

**Comment by weiyangfb** [comment]
@fmassa Yeah, I agree. Maybe clarify a bit can be helpful cc @soumith @apaszke

**Comment by weiyangfb** [comment]
Indeed creating a new tensor from list or NumPy array both work now, @soumith could you help to clarify what does copy mean here?

```
torch.tensor([1, 2, 3])
torch.tensor(np.array([1, 2, 3]))
```

**Comment by weiyangfb** [comment]
closing this because copy from NumPy array have already been supported. Please feel free to open an issue if there is any other need.

**Comment by zmonoid** [comment]
@weiyangfb 
```python
x = torch.tensor([1,2,3])
```
creates a new tensor from numpy array or list.

What copy means here is that, if I have a tensor ```x``` previously declared, I want to do the following
```python
x.copy_([4, 5, 6])
```
But dont known whether this give any speed up compared to directly declare.

**Comment by soumith** [comment]
@zmonoid there wont be any speedup even if we implement the `x.copy_(list or numpy array)`
