### ISSUE TITLE
[cuDNN FAILURE] NHWC conv2d fails on Windows CI 

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#33918]
## 🐛 Bug

NHWC 2d convolution triggers cuDNN failure.
cuDNN reports `RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM` on legit cudnn config.

Failure was captured by windows CI in PR #33784 

## To Reproduce

 ```
import torch
dtype = torch.float16
input = torch.randn((1, 16, 1, 1), dtype=dtype, device="cuda", requires_grad=True)
weight = torch.randn((8, 16, 3, 3), dtype=dtype, device="cuda", requires_grad=True)
weight = weight.to(memory_format=torch.channels_last)
o = torch.conv2d(input, weight, None, (2, 1), (1, 1), (1, 1), 1)
o.sum().backward()
```

## Environment

Unfortunately I don't have the repro (it originates from CI).
CI got this issue in Windows PyTorch build with CUDA 10.1 cuDNN 7.6.4.38

These I believe could be relevant (from CI log):
```
+ export IMAGE_COMMIT_TAG=pytorch-win-ws2019-cuda10-cudnn7-py3-59f21415ca9da70e5dfb4de4ba58a1681bb21e9d
Extracting archive: C:\Users\circleci\project\build\win_tmp\pytorch-win-ws2019-cuda10-cudnn7-py3-59f21415ca9da70e5dfb4de4ba58a1681bb21e9d.7z
```

## Additional context

Can't repro the same issue with linux build (CUDA 10.1 cuDNN 7.6.4.38).

Windows build with later library works fine as well (CUDA 10.2 cuDNN 7.6.5). I checked cudnn API log, nothing jumps out neither. I am suspicious that it's the packaging of library on Windows. If we are further investigating this, we should start from there.

cc @peterjc123

**Comment by vincentqb** [comment]
I don't see any errors in the CI of #33784. Can you provide the link to the failure?

**Comment by jjsjann123** [comment]
There we go: https://circleci.com/gh/pytorch/pytorch/4615662?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
It's failing on commit 59f2141

**Comment by peterjc123** [comment]
Could you please print the loaded DLLs through the following code?
```python
import psutil, os
p = psutil.Process( os.getpid() )
for dll in p.memory_maps():
  print(dll.path)
```

**Comment by jjsjann123** [comment]
Unfortunately I do NOT have a repro on the Windows machine.
The failure is on circle ci. I don't know if one can (and how to) access CI machine directly. :cry:

**Comment by cristianPanaite** [comment]
Hello @jjsjann123,

I tried to reproduce the error on the latest versions, using the script you provided, but unfortunately I could not. Here is the environment I used:

```PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
Nvidia driver version: 517.66
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchvision==0.15.2+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.1+cu118              pypi_0    pypi
[conda] torchaudio                2.0.2+cu118              pypi_0    pypi
[conda] torchvision               0.15.2+cu118             pypi_0    pypi  ```

Also, there are currently no Windows-related jobs running on CircleCI. I tried to identify the error in the current CI/CD jobs, but I could not find anything similar.

If you identify the error in the latest versions or in some more recent CI/CD job, please feel free to open a new issue with the details of how we can reproduce it.
