### ISSUE TITLE
[jit] inplace `_construct` RecursiveScriptModule

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#33912]
**What**: inplace option to construct RecursiveScriptModule 
**Why**: This is needed to support inplace option for graph mode quantization, and we want this to be able to align with eager mode quantization API

cc @suo

**Comment by gottbrath** [comment]
Ping .. this is the most important one of these items for Jerry.

**Comment by gottbrath** [comment]
I am hearing from Jerry that this is a potential release blocker for graph mode quantization. can we get feedback and/or a scope estimate and/or progress on this issue?

**Comment by gottbrath** [comment]
per discussion on our internal chat tool the JIT team can likely have this done in about 1 week.

**Comment by SplitInfinity** [comment]
@jerryzh168 Can you post a code sample of how this will be used?

**Comment by jerryzh168** [comment]
oh, this is used for implementing the inplace quantization for quantization, I have a sample PR here: https://github.com/pytorch/pytorch/pull/38831, feel free to create a new PR based on that.

```python
def _prepare_script(model, qconfig_dict, inplace=False, is_dynamic=False):
    ...
   cpp_module = torch._C._jit_pass_insert_observers(model._c,
                                                               'forward',
                                                               scripted_qconfig_dict,
                                                               inplace,
                                                               is_dynamic)
    if inplace:
      model._c = cpp_module
      model._reconstruct()
    else:
      model = wrap_cpp_module(cpp_module)
    return model
```

**Comment by SplitInfinity** [comment]
I don't think a perfect reconstruction is possible because `@ignored/@unused` methods are copied from the original `nn.Module` to a `ScriptModule` during scripting and cannot be recovered from `cpp_module`. Will that be a problem for you?

**Comment by jerryzh168** [comment]
> I don't think a perfect reconstruction is possible because `@ignored/@unused` methods are copied from the original `nn.Module` to a `ScriptModule` during scripting and cannot be recovered from `cpp_module`. Will that be a problem for you?

you still have the original module, which is `self`, would that work?

**Comment by SplitInfinity** [comment]
I think it would if the annotations are preserved when copying these functions from `nn.Module` -> `ScriptModule`. Let me try and see.

**Comment by SplitInfinity** [comment]
Is it possible that the new and old C++ modules correspond to different types? And that the unused/ignored methods from your old module don't apply to the new one?

**Comment by jerryzh168** [comment]
> Is it possible that the new and old C++ modules correspond to different types? And that the unused/ignored methods from your old module don't apply to the new one?

to give more context, the new cpp module is the module from quantizing the old cpp module, it is a module with inlined graph and also might be frozen. but the unused/ignored methods should still apply.

**Comment by gottbrath** [comment]
@jerryzh168  can you review #39979 and comment if it doesn't meet the needs for quantization.
