### ISSUE TITLE
Is there a way to parallelize independent sequential steps?

### ISSUE THREAD

**Issue by 522730312** [pytorch/pytorch#33937]
I am currently working with a model which has a fixed set of heavy operations applied on different versions of the same input. It would be really nice if I could perform these operations in parallel as each one of them takes a big chuck of total execution time. In Theano, with graph optimizations, this would have been automatically executed in parallel. But I am not sure how to parallelize these operations in PyTorch. I looked into Python’s multiprocessing module and PyTorch’s wrapper for it. But I am not sure if it’s usage would maintain the autograd’s graph integrity and how they’d work while performing backprop (which is actually an even more expensive than forward propagation).

The example of the model that captures the problem.
`def forward(x):`
    `    #process each transformed input by the same function`
    `    # my_func here is time consuming and the current bottleneck, but is internally optimized`
    `    # ideally, all four my_func calls below should execute in parallel`
    `    a = my_func1(x1)`
    `    b = my_func2(x2)`
    `    c = my_func3(x3)`
    `    result = a + b + c `
    `    return result`

Is there any way I could speed up this function? Not being able to parallelize this hurts me even more when I stack many such steps, which I am planning to do next. So any suggestions to speed this up in any way would help a lot.

Thanks!

**Comment by 522730312** [comment]
upper

**Comment by ezyang** [comment]
@zou3519 I think this would be solved by vmap

**Comment by ezyang** [comment]
If all operations support batching you could manually stack the inputs and then run everything in batched mode. May be annoying to do in some situations though.

**Comment by 522730312** [comment]
> If all operations support batching you could manually stack the inputs and then run everything in batched mode. May be annoying to do in some situations though.
I don`t think vmap can help me while traing
Would you tell me how can JAX.vmap work with pytorch?  JAX.vmap work with Gpu?

**Comment by 522730312** [comment]
my problem maybe define as below, How can a and b compute in parallel:
a = my_func1(x1)
b = my_func2(x2)
result = a + b
return result

**Comment by zou3519** [comment]
@522730312 are your `my_func1`, `my_func2` different functions?

**Comment by 522730312** [comment]
@zou3519   yes,they are different, did multi stream in gpu can slove this problem

**Comment by zou3519** [comment]
Since the functions are different, this isn't a use case for vmap. Python multiprocessing (for CPU tensors) or multi-stream (for CUDA) sound like reasonable solutions.

Does https://pytorch.org/docs/stable/notes/multiprocessing.html#asynchronous-multiprocess-training-e-g-hogwild help answer some of your questions, @522730312 ?

**Comment by mruberry** [comment]
Questions like this are best asked on the PyTorch forums, here: https://discuss.pytorch.org/.

Whether or not you can effectively parallelize depends on many factors. While the operations may be independent, each may still be consuming all available device resources, so parallelizing them would achieve nothing.
