### ISSUE TITLE
torch.save cpu memory leak

### ISSUE THREAD

**Issue by kazemSafari** [pytorch/pytorch#33933]
## 🐛 Bug

Saving multiple model instances during training, if the save name used is the same, causes no leak. However when model is being saved with different names (e.g. via an index), the free memory goes down and moves (leaks) into buffer/cache memory . Also the buffer/cache memory does not get release by os after the code exits on its own. 

## To Reproduce

1. Open a terminal and type "watch -n 5 free -m" to monitor the memory usage
2. Run the simple example in a separate terminal (given below). You can use less iterations for the simple example.
3. Observe the decrease in free memory and the increase in the buffer/cache memory which does not get released even after the code exits.
4. However, the program does not crash. The free memory stabilizes and fluctuates around 400-800 megabytes. The used memory stabilizes around 3500 megabytes and buff/cache memory also stabilizes around 58GB. 
5. You need to forcefully release the memory via typing in a terminal: " sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches' ".

Here is a simple example:
````
import torch
from pathlib import Path

a = torch.zeros(1000, 10000).cuda()
save_path = "leak"
Path(save_path).mkdir(exist_ok=True)

for i in range(10000000):
    ###################################
    torch.save(a, save_path+'/'+"{}.pt".format(i))
    ############################

````

## Expected behavior
The free available memory to a process should not change after each save with a different name. It should stay the same just like the case when saving a model with the same name (overwriting).
Instead after each save some free memory (equal approximately to the size of the saved model in megabytes) moves into the buffer/cache memory.

## Environment
 - PyTorch Version: 1.4.0
 - OS : Linux Ubuntu 16.04
 - How you installed PyTorch: pip
 - Python version: 3.7 (3.5 and 3.6)
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 2 GTX 1080TI
 - GPU Driver Version: 440.33.01
 - CPU model: intel corei7 7700k
 - RAM: 64 GB

I would like to be able to save multiple instances of a model during training, without worry about running out of memory.

cc @ezyang @gchanan @zou3519

**Comment by Baranowski** [comment]
@kazemSafari, thank for the report.

Is there some particular reason why you consider this behaviour a bug? From your description this behaviour seems harmless to me, as per https://www.linuxatemyram.com/ (apologies for the patronizing tone of that site, it's the best summary I could find after quick googling).

Of course, it's possible that I'm missing something here.

**Comment by kazemSafari** [comment]
@Baranowski Thank you so much for your reply and sharing the link. That does answer my question although I reached the same conclusion after doing more searches. Btw, i do not have a great background in computer science. I am just a mathematician and am learning these things for the first time. Thanks again.

**Comment by Baranowski** [comment]
Cool. Thanks again for taking the time to report and please keep reporting things when they look like a bug.

**Comment by duaisha** [comment]
What is the solution to this memory leak bug in torch.save? I am facing same, can someone explain me this?

**Comment by linjiapro** [comment]
@duaisha, look at this if you are on a linux/ubuntu machine: https://www.linuxatemyram.com/

I think the point is that if you keep touching disk to do saving, Linux OS will start to allocate memory for "disk cache" and the memory on your machine will look low but actually the available memory is high. Things are fine.
