### ISSUE TITLE
Error: convert pytorch int8 maxpool to onnx to c2

### ISSUE THREAD

**Issue by Pluto1944** [pytorch/pytorch#33932]
🐛 Bug

I get the same error when I try to convert pytorch int8 **maxpool** to onnx to c2.

## To Reproduce

1. I run torch2onnx_maxpool.py(the code list bellow) to get onnx and get this warning:
"symbolic_helper.py:176: UserWarning: ONNX export failed on max_pool2d because input size not accessible not supported"

2. when I run run_onnx_maxpool.py to load onnx model, I get this error
"Exception: Don't know how to translate op max_pool2d"

What should I do? The code is here
https://github.com/boydyang1/test_pytorch_int8_maxpool/blob/master/torch2onnx_maxpool.py
https://github.com/boydyang1/test_pytorch_int8_maxpool/blob/master/run_onnx_maxpool.py
@supriyar @houseroad @suo 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by supriyar** [comment]
Yeah, we don't have a mapping for max_pool2d from pytorch to c2. 
I created a quick patch here - https://github.com/pytorch/pytorch/pull/33945, you can try with this to see if it unblocks your testing.

For future ops, you can follow similar flow to add mapping from pytorch to C2 (if the op exists in C2).

**Comment by boydyang1** [comment]
Thank you for your reply!
The new patch #33945  unblocks your testing. 
When I add the "ceil_mode" attribute in kwargs, I get a new error:
` @parse_args('v', 'is', 'is', 'is', 'is', 'i')
  def max_pool2d(g, input, kernel_size, stride, padding, dilation, ceil_mode):
       if input not in sym_help._quantized_ops:
           from torch.onnx.symbolic_opset9 import max_pool2d
           return max_pool2d(g, input, kernel_size, stride, padding, dilation, ceil_mode)
     kwargs = {
         "strides_i": stride,
         "pads_i": padding + padding,                                                                         
         "kernel_i": kernel_size[0],
         "order_s": "NHWC",
         "Y_scale_f": input.node()["Y_scale"],
         "Y_zero_point_i": input.node()["Y_zero_point"],
         **"ceil_mode": ceil_mode,**
         }
`
File "/lib/python3.5/site-packages/torch/onnx/utils.py", line 516, in _add_attribute
    " must be suffixed with type, e.g. 'dim_i' or 'dims_i'").format(key))
IndexError: Invalid attribute specifier 'ceil_mode' names  must be suffixed with type, e.g. 'dim_i' or 'dims_i'

I know little about C2 and my pytorch model set 'ceil_mode=True' in maxpool. How to solve this problem? thank you!

**Comment by garymm** [comment]
Caffe2 is no longer being developed, so closing this.
