### ISSUE TITLE
Memory leak from Function.save_for_backward() when looping over batch

### ISSUE THREAD

**Issue by pbloem** [pytorch/pytorch#3394]
Due to some quirks of my model, I'm forced to loop over individual instances in a batch and apply a function to each individually. I ran into a memory leak, as illustrated by the following minimal example:

```python
import torch
from torch.autograd import Variable
from torch import nn
from tqdm import trange

CUDA = False

B = 2
BIG = 512

criterion = nn.MSELoss()

class Mult(torch.autograd.Function):

    def __init__(self):
        super().__init__()

    def forward(self, big, vector):

        # Comment this and problems go away
        self.save_for_backward(big)

        return vector * 2.0

    def backward(self, grad_output):

        return None, None

def iteration():
    mult = Mult()

    big = torch.zeros(B, BIG, BIG)
    x = torch.rand(B, 32)
    y = torch.zeros(B, 32)
    target = x.clone()

    if CUDA:
        big, x, y, target = big.cuda(), x.cuda(), y.cuda(), target.cuda()
    big, x, y, target = Variable(big), Variable(x, requires_grad=True), Variable(y), Variable(target)

    for b in range(B):
      y[b, :] = mult(big[b, :, :], x[b, :])

    # Use this instead of the above, and problems go away
    # y = mult(big, x)

    loss = criterion(y, target)

    del mult

for i in trange(int(10e7)):
    iteration()

```
On both my laptop (OSX, CPU) and a cluster node (RedHat, TitanX GPU) the memory use skyrockets with a few iterations. Since every torch object is created in the iteration() function the memory use should stay roughly stable from one iteration to the next.

Some things I noticed:

* The problem goes away when you apply the function to the whole batch in one go.
* The problem also goes away when you don't store anything for backward.
* Recovering the tensor 'big' in backward(), or actually using it in the computation graph makes no difference.
* The problem happens on both the CPU and the GPU.
* [A possibly related issue](https://discuss.pytorch.org/t/autograd-for-sparse-matmul-getting-either-cuda-memory-leak-or-buffers-have-already-been-freed-error/3806)

I think I've reached the limits of my understanding of pytorch. Did I misunderstand the Function API, or is this a genuine memory leak? If it is a bug, is there a simple workaround I could use?

**Comment by pbloem** [comment]
Workaround/Fix: The problem goes away if you use static methods, as done in the docs here:
http://pytorch.org/docs/master/notes/extending.html#extending-torch-autograd

I don't know which version is preferred, the one using static methods from the docs, or the one using instance methods [from the tutorials](http://pytorch.org/tutorials/beginner/pytorch_with_examples.html#pytorch-defining-new-autograd-functions). If the latter is deprecated, I guess this is not a big issue.

**Comment by soumith** [comment]
the `@staticmethod` stuff is the right / official way. We'll change the tutorials right away.
