### ISSUE TITLE
dlopen libnvrtc instead of dynamically linking against it

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3395]
Starting from commit https://github.com/pytorch/pytorch/commit/50e51eaa7fa5c252c2f4508cb5984734050177f1 we are linking against nvrtc and libcuda on CUDA builds. 
This has two consequences:
- pytorch CUDA builds can only be done on GPU-enabled machines, because libcuda.so comes with the nvidia driver
- the pytorch binaries with libcuda.so link dependency cant be run on CPU-only machines.

We need to fix this, and instead dlopen nvrtc, so that we can ship the next set of binaries to run on CPU / CUDA machines (just like our previous releases).

**Comment by soumith** [comment]
cc: @ngimel

**Comment by ngimel** [comment]
We are building inside docker, which is technically not GPU-enabled. If toolkit is installed (which it can be without driver), libcuda is found in stubs and build proceeds normally.

**Comment by soumith** [comment]
@ngimel i cant ship the libcuda stub in binaries, can I?

**Comment by ngimel** [comment]
Probably not, so the second problem still remains.

**Comment by soumith** [comment]
according to https://github.com/pytorch/pytorch/pull/3455#issuecomment-341690170 it's still not working for CUDA9

**Comment by xdever** [comment]
My setup details in #3455: Arch Linux, CUDA 9.0.176, cuDNN 7.0.3, gcc 6.4.1, built without docker or virtualenv, by running python setup.py install --user. Just in case you need it.

**Comment by soumith** [comment]
@xdever i finally reproduced it on an ArchLinux docker, looking...

**Comment by soumith** [comment]
@xdever fixed on master
