### ISSUE TITLE
Tensor Shape Type Hint Issue

### ISSUE THREAD

**Issue by vivekmig** [pytorch/pytorch#33953]
## 🐛 Bug

Type hint changes to a Tensor causes an error when type checking code accessing tensor shape indices after 0 when using nightly build. This is causing type checking failures for downstream applications, particularly in Captum.

## To Reproduce

Type check code such as:
```
t = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
s = t.shape[1]
```

MyPy error: error: Tuple index out of range

## Expected behavior
Shape should be type hinted to be an arbitrary length tuple as opposed to a tuple containing a single integer.

## Additional context

It looks like this problem is caused by the change in this PR (#33762), Size was changed to Tuple[_int], this should actually be Tuple[_int, ...].

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
You're absolutely right. Do you think you could submit a PR fixing this?

**Comment by prajjwal1** [comment]
Hi,
I want to take a shot at this if that's okay. Could you please suggest some pointer regarding where to start ?

**Comment by zou3519** [comment]
@prajjwal1 https://github.com/pytorch/pytorch/blob/4a194f89aadc7cd1d7e24622b53855cfb885da75/torch/__init__.pyi.in#L73 looks like the offending line. Things that would be good to figure out
1. what should we change that to? (probably Tuple[_int, ...] should work, according to the issue description)
2. how do we test that the change works? (Running mypy on some code that uses torch.Size should trigger the error. When submitting a PR, there should be a test case that uses torch.Size that the type checker runs over. I'm not sure how we test type hints but feel free to yell if you can't find it)

**Comment by prajjwal1** [comment]
Thanks. I'll work upon it and let you know my findings.

**Comment by prajjwal1** [comment]
Hi @zou3519 ,
Where do I add the test, I mean in which file ?

**Comment by prajjwal1** [comment]
I think that [this](https://github.com/pytorch/pytorch/blob/master/test/test_torch.py) might be a suitable place to add the test. Could you please provide some pointer on how to add the test so that it works in the intended manner ?

**Comment by zou3519** [comment]
@prajjwal1 Since the change should not be too large and it looks like our current method of testing type hints is complicated, I am happy to review a change without a test unless you have an idea of how to do the testing. The problem with adding a test to `test_torch.py` is that I don't think we run mypy over that file.

@ezyang is there a better way to test type hints than adding an example to a docstring? I found https://github.com/pytorch/pytorch/blob/master/test/test_type_hints.py#L115 while searching the codebase.

**Comment by prajjwal1** [comment]
@zou3519 What type of test do you want me to add ? I mean would running mypy over this example 
```
import torch
t = torch.tensor([[1.0, 2.0, 3.0, 4.0]])
s = t.shape[1]
```
won't be enough ?

**Comment by zou3519** [comment]
Running mypy over the simple example would work. How are you planning on running mypy in the test? You could use the `subprocess` module to shell out to mypy and run it over some file that has the code in your example.

**Comment by prajjwal1** [comment]
I was thinking of doing something like https://github.com/pytorch/pytorch/blob/cd9d9a2235567eb76743a5d863e0f2d4074d8956/test/test_torch.py#L377 
Like adding lines of code into a list like `test_type_hints` and running mypy over them ?

**Comment by prajjwal1** [comment]
Please provide your suggestions:
Here's the example code
```
input = []
input.append(torch.tensor([1.0, 2.0, 3.0, 4.0]))
input.append(torch.tensor([[1.0, 2.0, 3.0, 4.0]]))
input.append(torch.tensor([[[1.0, 2.0, 3.0, 4.0]]]))
input[0].shape[0]
input[1].shape[1]
input[2].shape[2]
```
Here's the file that should invoke the error, this can be placed inside `test_type_hints`
```
from subprocess import PIPE, Popen
process = Popen(['mypy', '33953.py'], stdout=PIPE, stderr=PIPE)
stdout, stderr = process.communicate()
print(stdout)
```
Returns 
```
b'33953.py:8: error: Tuple index out of range\n33953.py:9: error: Tuple index out of range\nFound 2 errors in 1 file (checked 1 source file)\n'
```

**Comment by zou3519** [comment]
Hmm, but you're not getting that if you run mypy locally? What changes did you make to the type hints for shape? It might be helpful if you submitted a pull request (even if it the test is not working) so that we could debug together on that.

**Comment by prajjwal1** [comment]
Yes, I'm getting it when I'm trying it on my machine. This change 
`
class Size(Tuple[_int, ...]): ... 
`
fixes the problem.
I can send a PR, but I don't know where to put the example. The subprocess code can come inside `test_type_hint` but I don't know where to put the example.

**Comment by zou3519** [comment]
There are a couple of options here. You could include the file under a new folder under the test/ directory, somewhere like `pytorch/test/type_hint_tests/size.py`. Alternatively, you could write the contents of the test to a temporary file and then run mypy over that temporary file.

**Comment by prajjwal1** [comment]
@zou3519  I've opened a PR here https://github.com/pytorch/pytorch/pull/34595. Please provide your suggestions.

**Comment by prajjwal1** [comment]
@zou3519 you can close this now.

**Comment by zou3519** [comment]
Thanks for the fix, @prajjwal1!
