### ISSUE TITLE
profiler.export_chrome_trace does not generate valid JSON when profiler is used with CUDA

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#33961]
## 🐛 Bug

Exporting chrome trace with a profiler that was enabled with cuda results in invalid json being generated, and thus, we cannot view the chrome trace. To repro, use this script:

```
import torch
device = torch.device("cuda:0")
t1 = torch.ones(1, device=device)

with torch.autograd.profiler.profile(use_cuda=True) as p:
    torch.add(t1, t1)

print(p.key_averages())
p.export_chrome_trace("/tmp/foo.txt")
print("Exported trace")
```

This generates the following JSON (pretty-printed for visibility): 

```
[{
	"name": "add",
	"ph": "X",
	"ts": 101.524,
	"dur": 134.49,
	"tid": 1,
	"pid": "CPU functions",
	"args": {}
}, {
	"name": "add",
	"ph": "s",
	"ts": 101.524,
	"tid": 1,
	"pid": "CPU functions",
	"id": 0,
	"cat": "cpu_to_cuda",
	"args": {}
}, {
	"name": "    add",
	"ph": "f",
	"ts": 102.95699890136719,
	tid": 0,
	"pid": "CUDA functions",
	"id": 0,
	"cat": "cpu_to_cuda",
	"args": {}
}, {
	"name": "add",
	"ph": "X",
	"ts": 102.95699890136719,
	"dur": 134.17599487304688,
	"tid": 0,
	"pid": "CUDA functions",
	"args": {}
}]
```
As we can see the JSON is not formatted correctly so we can't open this up in chrome://tracing

## Expected behavior

The JSON should be valid

## Environment
This is happening on master 

cc @ezyang @gchanan @zou3519

**Comment by rohan-varma** [comment]
Pretty sure this is caused by https://github.com/pytorch/pytorch/pull/30724/files. Looking into it.

**Comment by yf225** [comment]
@rohan-varma Curious should we close this issue, since https://github.com/pytorch/pytorch/pull/33987 is merged? Thanks!

**Comment by rohan-varma** [comment]
@yf225, yes, thanks for closing it out!
