### ISSUE TITLE
Cuda runtime error(59) again and weird

### ISSUE THREAD

**Issue by YazhiGao** [pytorch/pytorch#3398]
I am encountering the notorious cuda 59 error.
The error occurs after some normal iterations.
I think I do not have label mismatch problem.
I am using h5py for reading data to dataloader which was accused of multiprocessing problem previously.
Setting the workers to 1 and add
import torch import torch.multiprocessing torch.multiprocessing.set_start_method('spawn')
does not solve my problem.
Any replacement I can use other than h5py but preserve the speed or did i use numpy the wrong way?
The data loader is for resnet image features and text bow representations.
I have checked my training code, the batch on cpu at the error batch No. can be seen, 
the variable just got run after i invoke .cuda()

```python
from model import baseline
from util import data
from util import utils
from util import config
from tqdm import *
import torch.backends.cudnn as cudnn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.functional as F
import pdb
import torch

if __name__=="__main__":
    train = True
    cudnn.benchmark = True
    training,train_dict_size =  data.get_loader(train=True,full_batch = False)
    val,val_dict_size = data.get_loader(val=True,full_batch=True)
    model = baseline.BOWIMG(config.max_answers,train_dict_size,config.word_embed_dim,config.image_embed_dim,config.batch_size)
    best_perf = 0.0
    model.cuda()
    var_params = {
        'requires_grad': False,
	'volatile': False
    }
    val_params = {
        'requires_grad': False,
        'volatile': True
    }
    optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad])
    print("data is fully loaded")
    for i in tqdm(range(config.epochs)):
        iteration = 0
        for v,q,a,item,_ in training:
            q = Variable(q.cuda(async=True),**var_params)
            a = Variable(a.cuda(async=True),**var_params)
            v = Variable(v.cuda(async=True),**var_params)
            o = model(q=q,v=v)
            optimizer.zero_grad()
            loss =(-o*(a/10)).sum(dim=1).mean() # F.nll_loss(o,a)
            loss.backward()
            optimizer.step()
            acc = utils.batch_accuracy(o.data,a.data).cpu()
            print("epoch %s, iteration %s, loss %s, accuracy %s" %(str(i),str(iteration),str(loss.data[0]),str(acc.mean())))
            iteration+=1
        if (i+1)%config.val_interval ==0:
            for v,q,a,_ in val:
                q = Variable(q.cuda(async=True),**val_params)
                a = Variable(a.cuda(async=True),**val_params)
                v = Variable(v.cuda(async=True),**val_params)
                o = model(q=q,v=v)
                optimizer.zero_grad()
                loss =(-o*(a/10)).sum(dim=1).mean()
                loss.backward()
                optimizer.step()
                acc = utils.batch_accuracy(o.data,a.data).cpu()
            print("epoch %s, validation accuracy %s" %(str(i),str(acc.mean())))
            if acc > best_perf:
                best_perf = acc
                torch.save(model,"./best_model.model")
```

I try to replace h5py with numpy.load but the system got very slow using numpy load.
Is there any advice on data loading ?
https://github.com/Cyanogenoid/pytorch-vqa/blob/master/data.py
I used the code above and get (this is the trace i get using CUDA_LAUNCH_BLOCKING =1 trick):

`/pytorch/torch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, 
IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexT
ype = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [57,0,0], thread: [95,0,0] Assertion `srcIndex < 
srcSelectDimSize` failed.
torch.Size([100, 23, 1024])
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generated/../generic/THCTensorMathReduce.cu line=17 error=59 : 
device-side assert triggered
Traceback (most recent call last):
File "training.py", line 39, in <module>
  o = model(q=q,v=v)
File "/home/cs231n/myVE35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
  result = self.forward(*input, **kwargs)
File "/home/leon_gao19/10707/10707_Project/model/baseline.py", line 16, in forward
  embedding = torch.sum(embeds,dim=1)
File "/home/cs231n/myVE35/lib/python3.5/site-packages/torch/autograd/variable.py", line 476, in sum
  return Sum.apply(self, dim, keepdim)
File "/home/cs231n/myVE35/lib/python3.5/site-packages/torch/autograd/_functions/reduce.py", line 21, in forward
  return input.sum(dim)
RuntimeError: cuda runtime error (59) : device-side assert triggered at / 
pytorch/torch/lib/THC/generated/../generic/THCTensorMathReduce.cu:17`

**Comment by ngimel** [comment]
It should be CUDA_LAUNCH_BLOCKING, actually.

**Comment by YazhiGao** [comment]
please excuse my typo there, I used the right command. it does not work.

**Comment by YazhiGao** [comment]
found the problem, wrong indexing in the model file.
