### ISSUE TITLE
'LocalFileSystem' object has no attribute 'makedirs'

### ISSUE THREAD

**Issue by nkalavak** [pytorch/pytorch#34028]
## To Reproduce

While working with the `add_embedding` method for TensorBoard (for the first time), there seems to be an issue with one of the lines in the `writer.py` files that is invoked. The simplest way to reproduce would be to test the **Adding a "Projector" to TensorBoard** section of the TensorBoard tutorial (Link: https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html#adding-a-projector-to-tensorboard)

```
warning: Embedding dir exists, did you set global_step for add_embedding()?
  File "training_visualization.py", line 87, in <module>
    writer.add_embedding(features, metadata=class_labels, label_img=images.unsqueeze(1))
  File "/home/nivii/Desktop/python_environments/pytorch_py36/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 794, in add_embedding
    make_tsv(metadata, save_path, metadata_header=metadata_header)
  File "/home/nivii/Desktop/python_environments/pytorch_py36/lib/python3.6/site-packages/torch/utils/tensorboard/_embedding.py", line 20, in make_tsv
    fs.write(fs.join(save_path, 'metadata.tsv'), metadata_bytes, binary_mode=True)
AttributeError: 'LocalFileSystem' object has no attribute 'write'


```

## Expected behavior

No error, I presume. I am not sure where is should be setting the `global_step` in the case of the tutorial, while following it sequentially.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0/7/5/0
 - GPU models and configuration: NVIDIA RTX2060
 - Any other relevant information: Tensorboard 1.14.0

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Marking as high priority as it seems that basic functionality in tensorboard does not seem to work

**Comment by savadhanistablab** [comment]
This worked for me: 
- Uninstalled tensorflow, 
- Reinstalled Tensorboard. 
PS: Restart Kernel and tensorboard.

**Comment by peterbell10** [comment]
`write` was added to `tensorboard`'s `LocalFileSystem` stub in  tensorflow/tensorboard#2260 which included in tensorboard 1.15 and up (September 2019).

@savadhanistablab's workaround probably just updates `tensorboard`.

So, should we add a version check for `tensorboard`, or just give a better error if `not hasattr(fs, 'write')`?

**Comment by peterbell10** [comment]
1.14 seems to be the enforced minimum version currently
https://github.com/pytorch/pytorch/blob/58f5a89c9ac47a51c57cd08b4cce5082e2ee5706/torch/utils/tensorboard/__init__.py#L5

**Comment by beikejinmiao** [comment]
tensorboard==1.14.0 is now work.
