### ISSUE TITLE
A minor bug in unused grad_input check of run_backward() 

### ISSUE THREAD

**Issue by hczhu** [pytorch/pytorch#34029]
## 🐛 Bug

A pretty obvious bug that `num_inputs` is always 0.

https://github.com/pytorch/pytorch/blob/877c96cddfebee00385307f9e1b1f3b4ec72bfdc/torch/csrc/autograd/autograd.cpp#L103-L113

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
well spotted
