### ISSUE TITLE
Numerical instability of core algorithms

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#3402]
There are (at least) a couple examples of classical [numerical instability](https://en.wikipedia.org/wiki/Numerical_stability) to be found in `THTensorMath.c` algorithm implementations.

More precisely, what it has been done [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L3090-L3116) is simply criminal, from a stability point of view.
Same thing applies [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L3045-L3071), for example.
See [here](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) for better implementations.

I fixed a similar issue, a while ago, in the main *Torch* core library.
It is my belief that more examples of such bad behaviour are available, if one would sift through the code.

**Comment by ngimel** [comment]
I especially like this bit https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L3106. They know what they've done!

**Comment by ngimel** [comment]
Welford one-pass computation is pretty stable https://docs.google.com/document/d/1V3VEm9zQ17jsbWT9dxK_iS5qRZZenU6tdApj-VsbGk0/edit

**Comment by Atcold** [comment]
I just found one more [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCTensorMathReduce.cuh#L275-L278).
