### ISSUE TITLE
Documentation is super heavy

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#34032]
## 📚 Documentation

The documentation webpage is ridiculously heavy (~300MB on Chrome) and will crash any phone's browser. Can we section it into smaller chunks?

<img width="514" alt="Screenshot 2020-02-29 22 02 32" src="https://user-images.githubusercontent.com/2119355/75618659-82939a00-5b3f-11ea-8d57-a01994277f22.png">

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
related https://github.com/pytorch/pytorch/issues/20984

**Comment by ezyang** [comment]
Marking as high priority as this is a recurring major ux issue for users of our docs, as seen in the old bug. It seems we've fixed load time but not memory usage.

**Comment by rgommers** [comment]
+1 for breaking up. https://github.com/pytorch/pytorch/issues/32838#issuecomment-590584581 (similar issue about improving docs searchability) has a slightly more detailed proposal for doing this.

**Comment by rgommers** [comment]
This is fixed in https://pytorch.org/docs/master/ (1.5.0 still has the heavy page). For current status and follow-up ideas for further improvements, see https://github.com/pytorch/pytorch/pull/37419#issuecomment-625227494

Closing, thanks @mattip for tackling this.
