### ISSUE TITLE
Computation graph optimization during training

### ISSUE THREAD

**Issue by 522730312** [pytorch/pytorch#34057]
Hi, is it possible or neccessary to optimize the dynamic computation graph generated during training for a higher throughput?If it is, then what is the recommended way to achieve that? Thanks in advance.

cc @suo

**Comment by ezyang** [comment]
In principle the JIT compiler with TorchScript should be able to help with this; in practice you'll get most speed ups from fusing pointwise operations together. Check out https://pytorch.org/blog/optimizing-cuda-rnn-with-torchscript/ for an example
