### ISSUE TITLE
Export to ONNX models including logical masks

### ISSUE THREAD

**Issue by Enolerobotti** [pytorch/pytorch#34054]
## 🐛 Bug

This is a bug in torch.onnx module during export. Unable to handle with a logical mask due to TypeError.

## To Reproduce

1. type to the forward method something like
> mask = input_mask.clone()
> mask[mask != some_constant] = 1
> mask[mask == some_constant] = 0
2. export the model to onnx: 
>torch.onnx.export(model, dummy_input, filename, verbose=True, opset_version=11)

3. load the model by 
>onnxruntime.InferenceSession(filename)

4. catch the error. 
>This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (337) of operator (ScatterND) in node () is invalid.

5. see the log
>...
  %334 : Bool(20, 50, 6) = onnx::Cast[to=9](%333) # C:\Users\....\file.py:49:0
  %335 : Long() = onnx::Constant[value={1}]() # C:\Users\....\file.py:49:0
  %336 : Tensor = onnx::Shape(%334)
  %337 : Tensor = onnx::Unsqueeze[axes=[-1]](%334)
  %338 : Tensor = onnx::Shape(%atom_degree_list)
  %339 : Tensor = onnx::Constant[value={0}]()
  %340 : Tensor = onnx::Constant[value={1}]()
  %341 : Tensor = onnx::Constant[value={9223372036854775807}]()
  %342 : Tensor = onnx::Slice(%338, %340, %341, %339)
  %343 : Tensor = onnx::Concat[axis=0](%336, %342)
  %344 : Tensor = onnx::Reshape(%335, %343)
  %345 : Long(20, 50, 6) = onnx::ScatterND(%input_mask, %337, %344) # C:\Users\....\file.py:49:0
...

## Expected behavior
The workaround:
I can alter the code in the forward method like 
> mask = input_mask.clone()
> mask = mask - some_constant
> mask = numpy.heaviside(mask.abs(), 0).long()

and load the exported model successfully by onnxruntime. 
But I'm trying to export a network from a third-party library. Therefore I'm not allowed to alter the code.

## Environment

 - PyTorch Version : 1.4.0
 - OS: Windows 10 Pro 64 bit
 - How you installed PyTorch (`conda`, `pip`, source): current repo (git clone ...)
 - Build command you used (if compiling from source): setup.py build/install
 - Python version: 3.6
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: opset 11

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@Enolerobotti - @shubhambhokare1 has added a PR for this. If possible, please track it and see if you can test this patch on your end.

**Comment by Enolerobotti** [comment]
@spandantiwari thanks! Will test it ASAP.

**Comment by Enolerobotti** [comment]
@spandantiwari,  unfortunately this does not work for me.
```
import torch
import torch.nn as nn
import onnxruntime

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
    
    def forward(self, x):
        x = x.clone()
        x[x <= 1] = 0
        x[x > 1] = 1
        return x

model = Net()
x=torch.tensor([4, 1, 3])
torch.onnx.export(model, x, "dummy.pt", verbose=True, opset_version=11)
```

> graph(%0 : Long(3:1, requires_grad=0, device=cpu)):
>   %1 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={1}]()
>   %2 : Tensor = onnx::Greater(%0, %1)
>   %3 : Bool(3:1, requires_grad=0, device=cpu) = onnx::Not(%2) # /home/artem/.conda/envs/torchonnx_custom/lib/python3.6/site-packages/torch/tensor.py:27:0
>   %4 : Bool(3:1, requires_grad=0, device=cpu) = onnx::Cast[to=9](%3) # <ipython-input-2-9aaec6508d0a>:7:0
>   %5 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={0}]() # <ipython-input-2-9aaec6508d0a>:7:0
>   %6 : Tensor = onnx::Constant[value={-1}]()
>   %7 : Tensor = onnx::Reshape(%4, %6)
>   %8 : Tensor = onnx::Shape(%7)
>   %9 : Tensor = onnx::Unsqueeze[axes=[-1]](%7)
>   %10 : Tensor = onnx::Shape(%0)
>   %11 : Tensor = onnx::Constant[value={0}]()
>   %12 : Tensor = onnx::Constant[value={1}]()
>   %13 : Tensor = onnx::Constant[value={9223372036854775807}]()
>   %14 : Tensor = onnx::Slice(%10, %12, %13, %11)
>   %15 : Tensor = onnx::Concat[axis=0](%8, %14)
>   %16 : Tensor = onnx::Reshape(%5, %15)
>   %17 : Long(3:1, requires_grad=0, device=cpu) = onnx::ScatterND(%0, %9, %16)
>   %18 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={1}]()
>   %19 : Bool(3:1, requires_grad=0, device=cpu) = onnx::Greater(%17, %18) # /home/artem/.conda/envs/torchonnx_custom/lib/python3.6/site-packages/torch/tensor.py:27:0
>   %20 : Bool(3:1, requires_grad=0, device=cpu) = onnx::Cast[to=9](%19) # <ipython-input-2-9aaec6508d0a>:8:0
>   %21 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={1}]() # <ipython-input-2-9aaec6508d0a>:8:0
>   %22 : Tensor = onnx::Constant[value={-1}]()
>   %23 : Tensor = onnx::Reshape(%20, %22)
>   %24 : Tensor = onnx::Shape(%23)
>   %25 : Tensor = onnx::Unsqueeze[axes=[-1]](%23)
>   %26 : Tensor = onnx::Shape(%17)
>   %27 : Tensor = onnx::Constant[value={0}]()
>   %28 : Tensor = onnx::Constant[value={1}]()
>   %29 : Tensor = onnx::Constant[value={9223372036854775807}]()
>   %30 : Tensor = onnx::Slice(%26, %28, %29, %27)
>   %31 : Tensor = onnx::Coonnxruntime.InferenceSession('dummy.pt')ncat[axis=0](%24, %30)
>   %32 : Tensor = onnx::Reshape(%21, %31)
>   %33 : Long(3:1, requires_grad=0, device=cpu) = onnx::ScatterND(%17, %25, %32)
>   return (%33)

`onnxruntime.InferenceSession('dummy.pt')`

> ---------------------------------------------------------------------------
> InvalidGraph                              Traceback (most recent call last)
> <ipython-input-8-c17394c87f10> in <module>
> ----> 1 onnxruntime.InferenceSession('dummy.pt')
> 
> ~/.conda/envs/torchonnx_custom/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
>     156         self._path_or_bytes = path_or_bytes
>     157         self._sess_options = sess_options
> --> 158         self._load_model(providers or [])
>     159         self._enable_fallback = True
>     160         Session.__init__(self, self._sess)
> 
> ~/.conda/envs/torchonnx_custom/lib/python3.6/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
>     175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
>     176 
> --> 177         self._sess.load_model(providers)
>     178 
>     179         self._sess_options = self._sess.session_options
> 
> InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (9) of operator (ScatterND) in node (ScatterND_16) is invalid.

**Comment by shubhambhokare1** [comment]
I have made some changes to the functionality that gets rid of this error, will update ASAP.

**Comment by shubhambhokare1** [comment]
@Enolerobotti see if you can test this patch and if it resolves the issue you are facing

**Comment by Enolerobotti** [comment]
Thank you @shubhambhokare1! It works!

**Comment by jinfagang** [comment]
@shubhambhokare1 torch.floor will also introduce ScatterND, how to avoid it?
