### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by EricLucife** [pytorch/pytorch#34056]
I have installed PyTorch in miniconda. I can import torch in Anaconda Prompt. But when I try to import torch in IDLE, the first time there is a Warning. Then I try it again, there are nothing wrong. the path of IDLE is "D:\Miniconda3\Lib\idlelib\idle.bat"
![image](https://user-images.githubusercontent.com/35440115/75662736-90196300-5caa-11ea-9abc-dfb708391554.png)

**Comment by peterjc123** [comment]
The warning is thrown by numpy, please open a ticket at https://github.com/numpy/numpy/issues instead.
