### ISSUE TITLE
Incorrect det value on CPU

### ISSUE THREAD

**Issue by Alexander-H-Liu** [pytorch/pytorch#34061]
## 🐛 Bug

Incorrect det value on CPU

## To Reproduce

```
import torch

torch.manual_seed(0)

for N in [100,350,400,401]:
    W = torch.qr(torch.FloatTensor(N, N).normal_())[0]
    print('C = {}, det on cpu/gpu = {:.6f} / {:.6f}'.format(N,W.det(),W.cuda().det()))
```

## Expected behavior

```
C = 100, det on cpu/gpu = -0.999999 / -0.999999
C = 350, det on cpu/gpu = -173.111664 / -1.000001
C = 400, det on cpu/gpu = -0.000000 / -1.000002
C = 401, det on cpu/gpu = 0.000000 / 1.000001
```

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce GTX 1060 6GB
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.44
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchaudio==0.5.0a0+ac5dd79
[pip3] torchvision==0.5.0
[pip3] warpctc-pytorch==0.1
[conda] Could not collect
```

cc @VitalyFedyunin @vishwakftw @SsnL @jianyuh

**Comment by vishwakftw** [comment]
Hi, thank you for opening the issue. The bug has been isolated:
```
import torch

torch.manual_seed(0)

for N in [100,350]:
    W = torch.qr(torch.FloatTensor(N, N).normal_())[0]
    print('C = {}, det on cpu/gpu = {:.6f} / {:.6f}'.format(N,W.det(),W.cuda().det()))

W.lu()[0].diagonal(offset=0, dim1=-2, dim2=-1) == W.lu()[0].diag()  # This is true
W.lu()[0].diagonal().prod(-1)  # Returns tensor(173.1120)
W.lu()[0].diag().prod(-1)  # Returns tensor(1)
W.lu()[0].diagonal(offset=0, dim1=-2, dim2=-1).stride()  # (351,)
W.lu()[0].diag().stride()  # (1,)
```

Sounds like some kind of out-of-bounds access in the `prod` implementation.

**Comment by vishwakftw** [comment]
I've done more testing, seems like the effect starts for a `n` < 350.

```python
torch.manual_seed(0)

for N in range(270, 350):
    W = torch.qr(torch.FloatTensor(N, N).normal_())[0]
    print('C = {}, det on cpu/gpu = {:.6f} / {:.6f}'.format(N,W.det(),W.cuda().det()))
```

| C | CPU | GPU |
|--|--|--|
| 270 | -1.000010 | -1.000009 |
| 271 | 1.000003 | 1.000000 |
| 272 | -1.000006 | -1.000005 |
| 273 | 0.999998 | 0.999997 |
| 274 | -1.000002 | -1.000001 |
| 275 | 1.000000 | 1.000000 |
| 276 | -0.999998 | -1.000000 |
| 277 | 1.000004 | 1.000004 |
| 278 | -1.000008 | -1.000006 |
| 279 | 1.000003 | 1.000005 |
| 280 | -1.000004 | -1.000004 |
| 281 | 1.000005 | 1.000005 |
| 282 | -1.000004 | -1.000001 |
| 283 | 1.000003 | 1.000002 |
| 284 | -1.000003 | -1.000004 |
| 285 | 1.000002 | 1.000002 |
| 286 | -1.000003 | -1.000003 |
| 287 | 0.999999 | 1.000002 |
| 288 | -1.000003 | -1.000008 |
| 289 | 1.000002 | 1.000002 |
| 290 | -1.000007 | -1.000003 |
| 291 | 1.000000 | 0.999999 |
| 292 | -1.000000 | -1.000004 |
| 293 | 1.000004 | 1.000003 |
| 294 | -1.000001 | -1.000004 |
| 295 | 0.999999 | 0.999998 |
| 296 | -1.000014 | -1.000001 |
| 297 | 1.000004 | 1.000005 |
| 298 | -1.000001 | -1.000002 |
| 299 | 0.999997 | 1.000004 |
| 300 | -0.999990 | -1.000000 |
| 301 | 0.999958 | 1.000001 |
| 302 | -1.000000 | -0.999999 |
| 303 | 0.999995 | 1.000009 |
| 304 | -0.999931 | -1.000000 |
| 305 | 1.000023 | 1.000003 |
| 306 | -0.999948 | -1.000001 |
| 307 | 0.999972 | 1.000006 |
| 308 | -1.000222 | -1.000003 |
| 309 | 0.999940 | 1.000006 |
| 310 | -1.000059 | -1.000009 |
| 311 | 1.000276 | 1.000004 |
| 312 | -0.997294 | -1.000002 |
| 313 | 1.000545 | 1.000003 |
| 314 | -0.999901 | -1.000004 |
| 315 | 0.999601 | 1.000001 |
| 316 | -1.000752 | -1.000000 |
| 317 | 0.993782 | 1.000002 |
| 318 | -0.998647 | -1.000003 |
| 319 | 0.989083 | 1.000006 |
| 320 | -0.997824 | -1.000002 |
| 321 | 0.958771 | 1.000003 |
| 322 | -0.994043 | -1.000005 |
| 323 | 1.049997 | 1.000001 |
| 324 | -0.973644 | -0.999999 |
| 325 | 1.033144 | 1.000007 |
| 326 | -0.929843 | -1.000013 |
| 327 | 0.955417 | 1.000000 |
| 328 | -1.058516 | -0.999998 |
| 329 | 1.147103 | 1.000006 |
| 330 | -1.060216 | -1.000005 |
| 331 | 0.911528 | 1.000003 |
| 332 | -0.889485 | -1.000008 |
| 333 | 0.846748 | 0.999999 |
| 334 | -0.650189 | -1.000002 |
| 335 | 0.595321 | 1.000003 |
| 336 | -0.841948 | -1.000000 |
| 337 | 1.056087 | 1.000004 |
| 338 | -7.545174 | -1.000005 |
| 339 | 4.078619 | 1.000000 |
| 340 | -3.608356 | -0.999998 |
| 341 | 38.720287 | 1.000000 |
| 342 | -0.000000 | -1.000001 |
| 343 | 5.907115 | 1.000008 |
| 344 | -11.655735 | -1.000002 |
| 345 | 55.242165 | 0.999998 |
| 346 | -155.373413 | -1.000002 |
| 347 | 90.358154 | 1.000003 |
| 348 | -0.000000 | -1.000003 |
| 349 | 116.430588 | 1.000010 |
