### ISSUE TITLE
Adding and use `assertAllClose` API in our tests. 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#34096]
Currently we have many uses of 
```
self.assertEqual(ans.shape, expected.shape)
self.assertTrue(np.allclose(ans.cpu(), expected, rtol=1e-02, atol=1e-03, equal_nan=True))
``` 
in our tests. e.g. https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L11270
`torch.allclose` won't work well here as it only accept two tensors.
But this way is hard for backends like XLA to override precisions :P 
We want to propose make an API
```
self.assertAllClose(torch_tensor, np_array, rtol, atol, equal_nan)
```
to replace it. 
@mruberry @gchanan @ezyang Does this sound good? 
cc: @JackCaoG

**Comment by ezyang** [comment]
Existing `assertEqual` has tolerance kwargs; is this not working for the xla case for some reason?

**Comment by ailzhang** [comment]
@ezyang `assertEqual` works since XLA can override the precision. 
But when PyTorch test calls `np.allclose` instead of `assertEqual`(e.g. https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L11270) , it'll be tricky for XLA to override precision. ;)

**Comment by ailzhang** [comment]
@gchanan Yup but we do need an `allclose`-like API since it doesn't check dtype while `assertEqual` might/will?

**Comment by ezyang** [comment]
assertEqual currently doesn't check dtype, and even after my tightening up, you can expliictly request no dtype check with `exact_dtype=False`

**Comment by ailzhang** [comment]
Nice, sounds like an easier solution is just replace all uses of `np.allclose` in our tests with `assertEqual(..., exact_dtype=False)`? 
I'll send a PR if that sounds good!

**Comment by ezyang** [comment]
Yeah, that would be great. (Note that most tests still default to `exact_dtype=False`, but we want to fix that.)

**Comment by ailzhang** [comment]
Oh I just realized we do have a `assert_allclose` API already. But it's not in `TestCase` class. https://github.com/pytorch/pytorch/blob/master/torch/testing/__init__.py#L18
I somehow feel they should be in one place... Let me know if you have any preference between these it and `assertEqual`. ;)

**Comment by ezyang** [comment]
Yes, we should put them all in one place :> TestCase seems like the logical spot.

**Comment by ailzhang** [comment]
I feel @nairbv 's PR https://github.com/pytorch/pytorch/pull/34258 is bringing closer by adding `atol` and `rtol` to `assertEqual`, I'll hold my PR until his is merged.

**Comment by gchanan** [comment]
I don't think TestCase is a good spot -- the point of the testing packages is to collect things that are useful for other projects that use pytorch, but not our test framework.  I think assert_allclose fits in there and the assertEqual in TestCase is an anti-pattern.

**Comment by ailzhang** [comment]
@gchanan with PR #34258 we'll essentially merge the functionality of `allclose` check into `assertEqual`. We can keep both, while `assertEqual` being the major API used in our test framework?

**Comment by ezyang** [comment]
> I don't think TestCase is a good spot -- the point of the testing packages is to collect things that are useful for other projects that use pytorch

This is `torch.testing._internal`, not the general `torch.testing` module. Which exists solely because @pritamdamania really wanted to be able to put tests in subdirs in `tests/` ;)
