### ISSUE TITLE
Implement range reduction for activations on dynamic quantization kernels and enable per-tensor and per-channel dynamic quant with range reduction

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#34113]
We do not backoff activations to eliminate overflow in dynamic quantization: https://bddppq.github.io/codebrowser/pytorch/pytorch/aten/src/ATen/native/quantized/cpu/qlinear_dynamic.cpp.html#70

We need to support range reduction for both per channel and per tensor dynamic quantization as a valid qconfig option. 
This should enable better accuracy for dynamic quantization.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
this should be fixed by https://github.com/pytorch/pytorch/pull/39041
