### ISSUE TITLE
Runtime Error when using DistributedDataParallel with torch.no_grad()

### ISSUE THREAD

**Issue by JoyHuYY1412** [pytorch/pytorch#34120]
I meet the similar problem in https://github.com/pytorch/pytorch/issues/19896, while I use torch-1.0.0.dev20190328. I tried to edit the distributed.py while finally, it says: `AttributeError: module 'torch.distributed' has no attribute '_compute_bucket_assignment_by_size'`. I find it is out of my control.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @aazzolini @xush6528 @osalpekar

**Comment by ptrblck** [comment]
The mentioned method seems to be added in this [PR](https://github.com/pytorch/pytorch/pull/18953), which landed after the `1.0` release, while you are using a `1.0` pre-release.
Are you seeing the same issue with the latest stable release or do you need to stick to this particular version?
