### ISSUE TITLE
 KeyError: 'tril' occured while export onnx model 

### ISSUE THREAD

**Issue by mdztravelling** [pytorch/pytorch#34129]
## To Reproduce

1. `KeyError: 'tril'  ` occured while  running torch.onnx.export  pytorch model to onnx. There is `torch.tril(ret, out=ret)` in code.  how to convert it ?
1. onnx opset_version=10

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version (e.g., 1.0):  1.2.0
 - OS (e.g., Linux):   CentOS 6.3
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.5
 - CUDA/cuDNN version: 10.0, 7.5
 - GPU models and configuration: P4
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Thanks for reporting this. This is on our list of ops that we want to support. This would likely require adding op(s) to the ONNX spec.

**Comment by borisfom** [comment]
+1. Need this for NMT network.

**Comment by spandantiwari** [comment]
Yes, we are in the process of adding an op for this in the ONNX spec. https://github.com/onnx/onnx/pull/3291

**Comment by martinitus** [comment]
It [onnx/onnx#3291] is now merged and the new op version 15 has been released. 
When I tried to exporting a script model derived from [gpytorch](https://github.com/cornellius-gp/gpytorch) to ONNX i still get the error `Exporting the operator tril to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`. I used `opset_version=13` as argument to `torch.onnx.export`.Opset version 14 and 15 seem not to be supported yet in (my) torch version `1.8.1+cu102`

**Comment by gugarosa** [comment]
Hey @martinitus! Hope everything is going well with you.

While PyTorch still does not support these operators, you could use the following:

```
from typing import Optional

import torch

def triu_onnx(inputs: torch.FloatTensor,
              diagonal: Optional[int] = 0) -> torch.FloatTensor:
    """Caveat to export an triu-based operator with ONNX.

    Args:
        inputs: Input tensor.
        diagonal: Value of diagonal.

    Returns:
        (torch.FloatTensor): Output tensor.

    """

    arange = torch.arange(inputs.size(0), device=inputs.device)
    arange2 = torch.arange(inputs.size(1), device=inputs.device)

    mask = arange.unsqueeze(-1).expand(-1, inputs.size(1)) <= (arange2 - diagonal)

    return inputs.masked_fill(mask == 0, 0)


def tril_onnx(inputs: torch.FloatTensor,
              diagonal: Optional[int] = 0) -> torch.FloatTensor:
    """Caveat to export an tril-based operator with ONNX.

    Args:
        inputs: Input tensor.
        diagonal: Value of diagonal.

    Returns:
        (torch.FloatTensor): Output tensor.

    """

    arange = torch.arange(inputs.size(0), device=inputs.device)
    arange2 = torch.arange(inputs.size(1), device=inputs.device)

    mask = arange.unsqueeze(-1).expand(-1, inputs.size(1)) >= (arange2 - diagonal)

    return inputs.masked_fill(mask == 0, 0)


if __name__ == '__main__':
    inputs = torch.randn((10, 10))
    assert (triu_onnx(inputs) - torch.triu(inputs)).sum() == 0
    assert (tril_onnx(inputs) - torch.tril(inputs)).sum() == 0
```

Just make sure that prior to the export, you use `torch.triu = triu_onnx` and `torch.tril = tril_onnx`.

Best regards,
Gustavo.

**Comment by shubhambhokare1** [comment]
Closing issue a PR has been merged into Pytorch master branch
