### ISSUE TITLE
Windwos Install libtorch issue

### ISSUE THREAD

**Issue by alex-zador** [pytorch/pytorch#34124]
When trying install libtorch as in https://pytorch.org/cppdocs/installing.html I've got error:
 C:\libtorch\include\ATen/core/PhiloxRNGEngine.h(183): error C2719: 'ctr': formal parameter with requested alignment o
f 16 won't be aligned [C:\Users\alex\Desktop\Uni 201x\Uni19-20\МИШ\CTorch\CTorch\build\CTorch.vcxproj]
  C:\libtorch\include\ATen/core/PhiloxRNGEngine.h(183): error C2719: 'in_key': formal parameter with requested alignmen
t of 16 won't be aligned [C:\Users\alex\Desktop\Uni 201x\Uni19-20\МИШ\CTorch\CTorch\build\CTorch.vcxproj]

How can I overcome it and what is the reason? 

cc @peterjc123

**Comment by peterjc123** [comment]
Looks like some alignment things are not working on some old versions of MSVC.  Related issue: https://github.com/recp/cglm/issues/4. The workground is to use VS >= 1413 (2017 Update 6).

**Comment by alex-zador** [comment]
Thank you peterjc123! Update to VC 2019 solved the problem.
