### ISSUE TITLE
CMake Error at third_party/protobuf/cmake/cmake_install.cmake:48 (file):

### ISSUE THREAD

**Issue by shiyongde** [pytorch/pytorch#34121]
## 🐛 Bug
When build pytorch from source . Return Error  !!
[2388/2389] Install the project...
-- Install configuration: "Release"
CMake Error at third_party/protobuf/cmake/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "pytorch/build/third_party/protobuf/cmake/CMakeFiles/CMakeRelink.dir/protoc".
Call Stack (most recent call first):
  cmake_install.cmake:80 (include)

FAILED: CMakeFiles/install.util
cd pytorch/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 757, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "pytorch/tools/setup_helpers/cmake.py", line 332, in build
    self.run(build_args, my_env)
  File "pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/data1/annaconda3/envs/conda36_torch13/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '24']' returned non-zero exit status 1.

## To Reproduce
export BUILD_TEST=0
python setup.py install

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla K40m
GPU 1: Tesla K40m
GPU 2: Tesla K40m
GPU 3: Tesla K40m

Nvidia driver version: 410.78
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] magma-cuda100             2.5.2                         1    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.15           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] pytorch                   1.4.0           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu100    pytorch

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
FULL info :
(conda36_torch13) .@yyinc:/data5/./program/caffe2/pytorch$ python setup.py install
Building wheel torch-1.4.0a0+7963631
-- Building version 1.4.0a0+7963631
cmake --build . --target install --config Release -- -j 24
[0/1] Re-running CMake...
-- std::exception_ptr is supported.
-- NUMA is available
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/data5/./program/caffe2/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Trying to find preferred BLAS backend of choice: MKL
-- MKL_THREADING = OMP
CMake Warning at cmake/Modules/FindMKL.cmake:357 (MESSAGE):
.........................................
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
Generated: /data5/./program/caffe2/pytorch/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto
Generated: /data5/./program/caffe2/pytorch/build/third_party/onnx/onnx/onnx-operators_onnx_torch-ml.proto
--  Summary 
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1
--   CMAKE_PREFIX_PATH     : /data1/./annaconda3/envs/conda36_torch13;/usr/local/cuda-10.0
--   CMAKE_INSTALL_PREFIX  : /data5/./program/caffe2/pytorch/torch
--   CMAKE_MODULE_PATH     : /data5/./program/caffe2/pytorch/cmake/Modules;/data5/./program/caffe2/pytorch/cmake/public/../Modules_CUDA_fix
--   ONNX version          : 1.6.0
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
--   Protobuf compiler     :
--   Protobuf includes     :
--   Protobuf libraries    :
--   BUILD_ONNX_PYTHON     : OFF
-- Summary 
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1
--   CMAKE_PREFIX_PATH     : /data1/./annaconda3/envs/conda36_torch13;/usr/local/cuda-10.0
--   CMAKE_INSTALL_PREFIX  : /data5/./program/caffe2/pytorch/torch
--   CMAKE_MODULE_PATH     : /data5/./program/caffe2/pytorch/cmake/Modules;/data5/./program/caffe2/pytorch/cmake/public/../Modules_CUDA_fix
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx_torch
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   Protobuf compiler     :
--   Protobuf includes     :
--   Protobuf libraries    :
--   BUILD_ONNX_PYTHON     : OFF
-- /usr/bin/c++ /data5/./program/caffe2/pytorch/caffe2/../torch/abi-check.cpp -o /data5/./program/caffe2/pytorch/build/abi-check
-- Determined _GLIBCXX_USE_CXX11_ABI=1
-- MPI_INCLUDE_PATH: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_LIBRARIES: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPIEXEC: /usr/bin/mpiexec
-- pytorch is compiling with OpenMP.
OpenMP CXX_FLAGS: -fopenmp.
OpenMP libraries: /usr/lib/gcc/x86_64-linux-gnu/5/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so.
-- Caffe2 is compiling with OpenMP.
OpenMP CXX_FLAGS: -fopenmp.
OpenMP libraries: /usr/lib/gcc/x86_64-linux-gnu/5/libgomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so.
-- Using ATen parallel backend: OMP
-- Using lib/python3.6/site-packages as python relative installation path
CMake Warning at CMakeLists.txt:581 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.
--  Summary 
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 5.4.0
--   BLAS                  : MKL
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /data1/annaconda3/envs/conda36_torch13;/usr/local/cuda-10.0
--   CMAKE_INSTALL_PREFIX  : /data5/./program/caffe2/pytorch/torch
--   TORCH_VERSION         : 1.4.0
--   CAFFE2_VERSION        : 1.4.0
--   BUILD_CAFFE2_MOBILE   : ON
--   USE_STATIC_DISPATCH   : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.6.10
--     Python executable   : /data1/./annaconda3/envs/conda36_torch13/bin/python
--     Pythonlibs version  : 3.6.10
--     Python library      : /data1/./annaconda3/envs/conda36_torch13/lib/libpython3.6m.so.1.0
--     Python includes     : /data1/./annaconda3/envs/conda36_torch13/include/python3.6m
--     Python site-packages: lib/python3.6/site-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   INTERN_BUILD_MOBILE   :
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 10.0
--     cuDNN version       : 7.2.1
--     CUDA root directory : /usr/local/cuda-10.0
--     CUDA library        : /usr/local/cuda-10.0/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda-10.0/lib64/libcudart.so
--     cublas library      : /usr/local/cuda-10.0/lib64/libcublas.so
--     cufft library       : /usr/local/cuda-10.0/lib64/libcufft.so
--     curand library      : /usr/local/cuda-10.0/lib64/libcurand.so
--     cuDNN library       : /usr/lib/x86_64-linux-gnu/libcudnn.so
--     nvrtc               : /data1/./annaconda3/envs/conda36_torch13/lib/libnvrtc.so
--     CUDA include path   : /usr/local/cuda-10.0/include
--     NVCC executable     : /usr/local/cuda-10.0/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : OFF
--   USE_MKLDNN            : ON
--   USE_MKLDNN_CBLAS      : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_TBB               : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkldnn
--   Private Dependencies : qnnpack;pytorch_qnnpack;nnpack;cpuinfo;fbgemm;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring done

........................

 inline void deprecated_AT_CHECK() {}
             ^
[2388/2389] Install the project...
-- Install configuration: "Release"
CMake Error at third_party/protobuf/cmake/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/data5/./program/caffe2/pytorch/build/third_party/protobuf/cmake/CMakeFiles/CMakeRelink.dir/protoc".
Call Stack (most recent call first):
  cmake_install.cmake:80 (include)
..........................................................
FAILED: CMakeFiles/install.util
cd /data5/./program/caffe2/pytorch/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 757, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/data5/./program/caffe2/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/data5/./program/caffe2/pytorch/tools/setup_helpers/cmake.py", line 332, in build
    self.run(build_args, my_env)
  File "/data5/./program/caffe2/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/data1/./annaconda3/envs/conda36_torch13/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '24']' returned non-zero exit status 1.

**Comment by shiyongde** [comment]
Finally ,I fixed it .
remove your ***/bin/protoc  in your PATH, then conda install protobuf.
rebuild it .

**Comment by MinaAbdElMassih** [comment]
@shiyongde Hey, I am facing the same error, i don't quiet understand which path are you referring to.
Could you clarify it, please ? 
Thanks. :)

**Comment by ouguozhen** [comment]
> @shiyongde Hey, I am facing the same error, i don't quiet understand which path are you referring to.
> Could you clarify it, please ?
> Thanks. :)
> PS: I am using windows.

Hi, i meet the same error, have you found the PATH?

**Comment by UniEa** [comment]
> > @shiyongde Hey, I am facing the same error, i don't quiet understand which path are you referring to.
> > Could you clarify it, please ?
> > Thanks. :)
> > PS: I am using windows.
> 
> Hi, i meet the same error, have you found the PATH?

Hi, I meet the same error! Have you solved it? I really need help. Thank you so much

**Comment by UniEa** [comment]
I met the same error and I have simply solved it by updating cmake to ver 3.14.0 (previous version was 3.5). You need to run `python setup.py clean` and then build it again.
