### ISSUE TITLE
Indexing with an empty vector of indices throws a RuntimeError

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/pytorch#3416]
Arguably, indexing a Tensor by a LongTensor with no dimension should return a LongTensor with no dimension. Consider the following case:
```
>>> a = torch.ones(5)
>>> a[a<0]
[torch.FloatTensor with no dimension]
>>> a[(a<0).nonzero().squeeze()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 3: Index is supposed to be a vector at /opt/conda/conda-bld/pytorch_1503966894950/work/torch/lib/TH/generic/THTensorMath.c:248
```
This breaks indexing by indices when the list of indices is empty, which can be hard to detect. In my use-case, I use such a masking to select rows of a tensor corresponding to "valid" entries in a vector; I had not considered that it would not work when there are no valid entries.

**Comment by SsnL** [comment]
Thanks! I'll take a look.
