### ISSUE TITLE
Kaiming/Xavier initializer cannot deal with bias term

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#3418]
The current implementation of Kaiming/Xavier initializer in `nn.init` cannot deal with the network with bias term, since it raises an error of `Fan in and fan out can not be computed for tensor with less than 2 dimensions`.

**Comment by SsnL** [comment]
Correct me if I am wrong. I think those methods are not supposed to deal with bias terms. In the paper, bias terms are initialized to zeros, which you can achieve by `layer.bias.data.zero_()`

**Comment by alykhantejani** [comment]
or if you want to use `nn.init` for this you can do `nn.init.constant(layer.bias, 0)`

**Comment by vishwakftw** [comment]
Or you could have a `Warning` instead of a `ValueError`. Something like this could be a solution right:
```python
if dimensions < 2:
    warnings.warn("Fan in and fan out can not be computed for tensor with less than 2 dimensions, hence initializing all zeros", RuntimeWarning)
```

I feel this is more appropriate since that can't be classified as an error per se.

**Comment by apaszke** [comment]
I think this is a clear error. You can't get `fan_in` and `fan_out`, which are required by this initialization method, so it should fail (there's no way to satisfy the contract if this happens).
