### ISSUE TITLE
[docs] Unclear arg signature of torch.meshgrid: kwargs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#34206]
https://pytorch.org/docs/master/torch.html?highlight=meshgrid#torch.meshgrid

arg spec has some "**kwargs", but it's not described in the doc string and there is no code example 

I think it should be removed

**Comment by colesbury** [comment]
Yeah, it looks like it's not doing anything useful. It should be removed from both the code and documentation. It got added in this PR:

PRs welcome.

https://github.com/pytorch/pytorch/pull/11600
