### ISSUE TITLE
Implementation Discussion: Native CTC

### ISSUE THREAD

**Issue by mittagessen** [pytorch/pytorch#3420]
Hi All,

CTC as a loss function quite often used in sequence to sequence models isn't currently implemented and installing binding to warp-ctc is quite hacky (and warp-ctc isn't developed anymore). I'd like to add it natively to pytorch, probably based on the implementation of [clstm](http://github.com/tmbdev/clstm).

My question is first of if that is even desired and second where to include the code? Is torch/lib/THNN/generic the right location?

**Comment by stefbraun** [comment]
CUDNN 7 added cudnnCTCLoss, maybe we just need a binding to the newest CUDNN?

**Comment by mittagessen** [comment]
I'd prefer a non-binding approach as there are already a few extensions out there. Getting a CTC without having to compile anything seems like a nice thing to have even if it isn't as fast as the latest ultra-optimized CUDA implementation.

**Comment by hmc-cs-mdrissi** [comment]
cuda + cudnn is fairly common though so it's not adding much of a requirement as it is typically strongly recommended if you have a gpu. That'd be my ideal option as that would both give a nicely optimized gpu implementation and as it is part of cudnn it'll likely remain actively maintained.

As a related note, in actually using ctc one useful function besides the loss would be a way of doing the beam search to find the most likely sequence. The loss by itself is still nice though as you can always just use the greedy method of choosing the most likely labels when doing the decoding.

**Comment by mittagessen** [comment]
> cuda + cudnn is fairly common though so it's not  adding much of a requirement as it is typically strongly recommended if  you have a gpu. That'd be my ideal option as that would both give a  nicely optimized gpu implementation and as it is part of cudnn it'll  likely remain actively maintained.

Most of the people using the software I need CTC in pytorch for are using CPUs so my focus is there. I've looked at the code and adding a cuDNN wrapper to the existing ones should be fairly easy, although I am fairly sure the CPU implementation is producing different results from cuDNN (or most other CTC implementations) which is another reason not to transparently switch between both.

>  As a related note, in actually using ctc one useful function besides the loss would be a way of doing the beam search to find the most likely sequence.

Does it actually improve output accuracy? I know ocropy/clstm CTC trains robust networks (more so than other CTCs) for OCR that tend to perform equally well with either greedy or beam search and most stuff I've seen in the wild use either greedy or some model like WFST and RNN-LM for decoding.

**Comment by stefbraun** [comment]
Pytorch is heavily integrated with cuDNN (e.g. [LSTM implementation](http://pytorch.org/docs/master/nn.html?highlight=lstm#torch.nn.LSTM))

Therefore, using the CTC loss function provided by cuDNN 7 should be OK, too. Also, it is probably heavily optimized and it will be actively maintained by the cuDNN team.

**Comment by mittagessen** [comment]
> Pytorch is heavily integrated with cuDNN (e.g. LSTM implementation)

I realized that when looking at the backend wrapper.

> Also, it is probably heavily optimized...

I'll do some comparisons once I got the CPU implementation going.

**Comment by MaigoAkisame** [comment]
I would like to have a native CTC loss. I just wrote one myself and it's pretty slow...

**Comment by mittagessen** [comment]
After spending a few days on a CTC loss in THNN, I came to the conclusion that it isn't really feasable without wrapping it in an amount of python code that makes it unmergable. The main reason is that gradients and loss are calculated concurrently in CTC but they are separate function calls without data sharing in THNN. 
Retaining the gradient through a python wrapper class is possible but wrapper class functionality for THNN kernels were moved from python to C a while back and doing it differently for a single loss function seems wrong. Running CTC twice, once for the loss and once for the gradients is also unacceptable.
I've updated an old python CTC implementation for my requirements, if you or the people you're shipping software to are fine with compling and need the performance I'd suggest using warp-ctc (with pytorch bindings), cctc or similar. As my main requirement is 'works out of box' I have to live with a slower python CTC.

**Comment by stefbraun** [comment]
Your effort is much appreciated, but in my opinion the best solution is a binding to the cudnn-ctc loss for the already mentioned reasons.

**Comment by jfolt** [comment]
Cudnn implementation of CTC would be my preferred choice.

**Comment by nlgranger** [comment]
For what it's worth, I have implemented CTC using just theano so that it can run either on CPU or GPU without low level bindings (https://github.com/nlgranger/Recipes/tree/connectionist_temporal_classification/papers/connectionist_temporal_classification). I guess it would be possible to translate that to PyTorch although some parts might be tricky, and I cannot say anything about the speed either.

**Comment by stefbraun** [comment]
is there any update on this? should we do a feature request on cudnn-ctc?

**Comment by WenmuZhou** [comment]
udopate?

**Comment by mittagessen** [comment]
Not a cuDNN implementation but the I ultimately adapted the chainer CTC as it was roughly twice as fast as my naïve implementation in unnormalized log-space. It is pure python so doesn't require any compiling and can be found [here](https://github.com/mittagessen/kraken/blob/master/kraken/lib/ctc.py). It should also be numerically identical to a standard formulation with slight differences to warp-ctc's output.

**Comment by SivanKe** [comment]
While it's not integrated to pytorch, @SeanNaren created a pytorch binding for Baidu's implementation of warp-ctc, which is a great, fast and parallel implementation of ctc both on gpu and on cpu.
I use it all the time and its awesome! Also, thanks to @SeanNaren its very easy to install and use :)
link: https://github.com/SeanNaren/warp-ctc

**Comment by diggerdu** [comment]
@Sivanke

warp-ctc is out of maintain, and cudnn.ctc is 20x faster

**Comment by SivanKe** [comment]
Wow, good to know - thanks! :)

**Comment by edchengg** [comment]
@SivanKe Could you help me with the CTC loss? an example code would be really appreciate

**Comment by diggerdu** [comment]
@edchengg 
https://github.com/diggerdu/PyTorch-LipNet/blob/master/models/pix2pix_model.py#L58
https://github.com/diggerdu/PyTorch-LipNet/blob/master/models/pix2pix_model.py#L181

**Comment by SeanNaren** [comment]
I plan on deprecating my warp-ctc package for @t-vi ATen supported package, so if anyone plans to use warp-ctc I'd suggest using this: https://github.com/t-vi/warp-ctc

**Comment by ZhengHui-Z** [comment]
I would like to have a native CTC loss too.

**Comment by soumith** [comment]
@ZhengHui-Z it's part of Preview release, you can install it from our website.
https://pytorch.org/docs/master/nn.html#torch.nn.CTCLoss

**Comment by tuananhvip** [comment]
> @SivanKe
> 
> warp-ctc is out of maintain, and cudnn.ctc is 20x faster

How to install it in linux? i use torch and thay said that:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1a84affba9e0> in <module>()
----> 1 ctc_loss = nn.CTCLoss()

AttributeError: module 'torch.nn' has no attribute 'CTCLoss'
```
This is what i were install:
```
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch 
```
thanks

**Comment by t-vi** [comment]
You would have to use 1.0rc, I wasn't quite finished in time for 0.4.1.

**Comment by tuananhvip** [comment]
> You would have to use 1.0rc, I wasn't quite finished in time for 0.4.1.

Thanks @t-vi, I just found the installations instructions:
```
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'
print(accelerator)
!pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html 
import torch 
```
That code work!
