### ISSUE TITLE
Additions and subtractions are not implemented for FP16

### ISSUE THREAD

**Issue by frgfm** [pytorch/pytorch#34219]
## 🐛 FP16 inplace operations

Hello there,

I was trying to switch an inference script to FP16. But I encountered an issue, as inplace additions/subtractions are not implemented for `torch.float16`. It prevents the user from using `torchvision.transforms.functional.normalize` inplace for instance.

## To Reproduce

```
import torch
t = torch.zeros(8, dtype=torch.float16)
t += 1
```

which yields
```
RuntimeError: "add_cpu/sub_cpu" not implemented for 'Half'
```

## Expected behavior

Inplace operations working for `torch.float16` just like `torch.float32`.

## Environment

 - PyTorch Version : 1.4.0
 - OS: Linux
 - How you installed PyTorch: `conda`
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1.168 (cuDNN 7.6.2)
 - GPU models and configuration: GeForce GTX 1050 (driver 440.59)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by colesbury** [comment]
Arithmetic (add, sub, mul, div) is not implemented for float16 on CPU. (Not just in-place ops).

It is implemented for GPU.

It hasn't been a high priority because float16 is ops are generally slower on CPU than float32 ops.

**Comment by colesbury** [comment]
We should document support (or lack thereof) for torch.float16 and torch.bfloat16. I didn't see bfloat16 even mentioned on https://pytorch.org/docs/master/tensors.html.

**Comment by z-a-f** [comment]
Should this still have a `quantization` label?

**Comment by frgfm** [comment]
Since the documentation has been updated, and support has been extended at least in release `1.6.0`, I'm closing this issue. Feel free to reopen if you think I might have missed something!
