### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered when bactchsize > 1

### ISSUE THREAD

**Issue by Penuoz** [pytorch/pytorch#34220]
### When batchsize = 1, the training process is normal. Once it is set to a number greater than 1, an error is reported: CUDA error: an illegal memory access was encrypted.

```
The following is a complete error report：
Traceback (most recent call last):
  File "/home/penuoz/Celldetection/train.py", line 34, in <module>
    loss_tmp += np.array(model.get_current_losses())
  File "/home/penuoz/Celldetection/models/base_model.py", line 152, in get_current_losses
    errors_ret.append(float(getattr(self, 'loss_' + name)))  # float(...) works for both scalar tensor and float number
RuntimeError: CUDA error: an illegal memory access was encountered
```

Process finished with exit code 1

Related code snippets
`self.loss_hm = self.criterion(self.output, self.target)`
` self.loss_hm.backward()`
`errors_ret = []`
`for name in self.loss_names:`
`      if isinstance(name, str):`
`            errors_ret.append(float(getattr(self, 'loss_' + name)))  `
`return errors_ret`

**Comment by colesbury** [comment]
Would you please re-open the issue with additional information? There's not enough currently to figure out what's going on.  A self-contained repro would be ideal.
