### ISSUE TITLE
[cpp_ext] tmp build dir permission issue

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#34238]
## 🐛 Bug

In systems where multiple users share the tmp folder, the first a CPP extension build creates `/tmp/torch_extensions/build` with `os.makedirs` with the current umask value. https://github.com/pytorch/pytorch/blob/ac6e75a1651cd14cec7f2f41b2c7b9ec7dcb3ecf/torch/utils/cpp_extension.py#L1348-L1353

If that is restrictive, subsequent builds from other users will fail with 
```py
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/fused'
```

So I propose to do either of the following:
1. have user-specific default temp build dir, e.g., `/tmp/torch_extensions/$USER/`, then you still need `/tmp/torch_extensions` to be writable for all users. Maybe `/tmp/torch_extensions_$USER`?
2. force the folder to be 777 with `os.chmod` after `makedirs`

### Current workaround
set `TORCH_EXTENSIONS_DIR`

cc @yf225

**Comment by colesbury** [comment]
If this is a temporary directory, why aren't we using normal temporary directory mechanisms (e.g. tempfile in Python)?

**Comment by SsnL** [comment]
@colesbury I'm not sure, but I assume caching across sessions.

**Comment by colesbury** [comment]
Then it seems like we should be using a cache directory not tmp. e.g. https://github.com/pypa/pip/blob/c04798f5fddd8d29425e9f15dd13fa1c3bb5d176/src/pip/_vendor/appdirs.py#L268

**Comment by zhangmozhe** [comment]
> ## 🐛 Bug
> In systems where multiple users share the tmp folder, the first a CPP extension build creates `/tmp/torch_extensions/build` with `os.makedirs` with the current umask value.
> 
> https://github.com/pytorch/pytorch/blob/ac6e75a1651cd14cec7f2f41b2c7b9ec7dcb3ecf/torch/utils/cpp_extension.py#L1348-L1353
> 
> If that is restrictive, subsequent builds from other users will fail with
> 
> ```python
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/tmp/torch_extensions/fused'
> ```
> 
> So I propose to do either of the following:
> 
> 1. have user-specific default temp build dir, e.g., `/tmp/torch_extensions/$USER/`, then you still need `/tmp/torch_extensions` to be writable for all users. Maybe `/tmp/torch_extensions_$USER`?
> 2. force the folder to be 777 with `os.chmod` after `makedirs`
> 
> ### Current workaround
> set `TORCH_EXTENSIONS_DIR`
> 
> cc @yf225

I have exactly the same issue.

**Comment by israrbacha** [comment]
I Got the permission error with PyTorch v1.6 on Docker. anyone have an idea how to fix it?

File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 970, in load
    build_directory or _get_build_directory(name, verbose),
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1454, in _get_build_directory
    os.makedirs(build_directory, exist_ok=True)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'

**Comment by skiingpacman** [comment]
Looks like this issue may still exist when running DeepSpeed on shared machines. Work around (as suggested above) is to use something like `export TORCH_EXTENSIONS_DIR=/tmp/$USER/torch_extensions/`
