### ISSUE TITLE
 Derive onnx model from caffe2 int8 related model using torch 

### ISSUE THREAD

**Issue by lisa0314** [pytorch/pytorch#34296]
As we all know, `torch.onnx.export(*args, **kwargs)` could derive onnx model from caffe2. However, I didn't find the int8 related ops(https://github.com/pytorch/pytorch/tree/master/caffe2/quantization/server#quantization-operators) in the op list which torch support.  So I want to make sure if I could use pytorch to tranfer the int8 caffe2 model into onnx  and how to transfer.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
Caffe2 is no longer being developed.
