### ISSUE TITLE
ONNX export failed on ATen operator round because torch.onnx.symbolic_opset9.round does not exist

### ISSUE THREAD

**Issue by l4zyf9x** [pytorch/pytorch#34290]
## To Reproduce

Run following code:
```
import torch
class RoundLayer(torch.nn.Module):
    def forward(self, x):
        return torch.round(x)
torch.onnx.export(RoundLayer(), torch.rand(1), 'round.onnx')
```
Got output:
```
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator round because torch.onnx.symbolic_opset9.round does not exist
  .format(op_name, opset_version, op_name))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-254-372622201e52> in <module>()
      3     def forward(self, x):
      4         return torch.round(x)
----> 5 torch.onnx.export(RoundLayer(), torch.rand(1), 'tst.onnx')

7 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
     89         warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
     90     global _registry
---> 91     return _registry[(domain, version)][opname]

KeyError: 'round'
```

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect
```

## Additional context
Following  [onnx  documentation](https://pytorch.org/docs/stable/onnx.html#supported-operators), round operator is supported but when I looked [symbolic_opset9.py](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py) there is no round function

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by yaeldekel** [comment]
Hi @l4zyf9x , you are getting this error message because the "round" operator is not a part of opset 9, which is the default version that PyTorch uses to export models to ONNX. It was added in opset 11, so if you try 
```
torch.onnx.export(RoundLayer(), torch.rand(1), 'round.onnx', opset_version=11)
```
you should be able to export your model.

The error message you saw was not very clear, but it has been fixed to a more friendly error message:

> Exporting the operator round to ONNX opset version 9 is not supported. Support for this operator was added in version 11, try exporting with this version.

Please try updating your PyTorch version to 1.5 to see if you get the friendlier error message (if not, then it will definitely be there in the next version).
