### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by shiyongde** [pytorch/pytorch#34295]
## 🐛 Bug

>>> F.interpolate(prev_features, scale_factor=2)# mode="nearest")
Floating point exception (core dumped)

## To Reproduce
import torch
import torch.nn.functional as F
prev_features = torch.ones((2,22,22,4))*0.1
prev_features =prev_features.cuda()
F.interpolate(prev_features, scale_factor=2)# mode="nearest")

## Environment

Collecting environment information...
PyTorch version: 1.4.0a0+7963631
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla K40m
GPU 1: Tesla K40m
GPU 2: Tesla K40m
GPU 3: Tesla K40m

Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorchviz==0.0.1
[pip3] torch==1.4.0a0+7963631
[pip3] torchfile==0.1.0
[pip3] torchvision==0.5.0a0+85b8fbf
[conda] Could not collect

 

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by shiyongde** [comment]
prev_features = torch.ones((2,22,22,4))*0.1
prev_features =prev_features 
F.interpolate(prev_features, scale_factor=2)# mode="nearest") 
is well
So ,It must cuda() problem

**Comment by ptrblck** [comment]
Thanks for reporting this issue.
I can neither reproduce this issue with the stable binaries + CUDA10.1 and CUDA9.2 nor with a build from source + CUDA10.2.

I assume you've compiled PyTorch from source, as you are using CUDA10.0?
Could you try to update CUDA to 10.1 or 10.2 and run the code again?

Also, could you post the stacktrace from gdb please?

**Comment by shiyongde** [comment]
I fixed it by using docker。
