### ISSUE TITLE
libtorch: Enable static dispatch

### ISSUE THREAD

**Issue by AZ-Visuals** [pytorch/pytorch#34297]
Hello. I would like to enable static dispatch (USE_STATIC_DISPATCH) in libtorch C++ because some tensor operations are very CPU consuming (for instance, stack etc.) - I am assuming that this happens due to the dynamic dispatch.

However, the macros USE_STATIC_DISPATCH is unavailable from CMake when I build libtorch. Is there any way to enable static dispatch correctly? Defining 
    #define USE_STATIC_DISPATCH
in c10/macros/Macros.h produces linker errors while compiling my project.

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ . Because of it, I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.

Also have you tried to set USE_STATIC_DISPATCH as env variable?
