### ISSUE TITLE
How can I change the torch.Size?

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#34293]
Hi, guys,
today I want to create an zeros tensor based on similar shape of another torch.Tensor,
so I change the shape like:
```python
        shape = pred_batch.shape
        # [4,1020,3384]
        shape[1] = 690
```
However, an error appeared as
> TypeError: 'torch.Size' object does not support item assignment

So how can I realize this task?

Any answer or idea  will be appreciated!

**Comment by prajjwal1** [comment]
Hi,
You should discuss such questions on [Pytorch forums](https://discuss.pytorch.org/). There's an amazing community to help you out with your Pytorch related queries. 
Regarding your query, I think this will do.
```
t = torch.rand(128,3,64)
t = torch.zeros(t.shape)
```

**Comment by songyuc** [comment]
Hi, Prajjwal,
I am sorry for not post this question on  Pytorch forums, but for some unknow reasons, I cannot successfully to connect to this website today, which might be due to the censorship firewall in my country.
And I think your code just shows how to get the shape of a torch tensor using  `t.shape`, but my question focuses on how to change the obtained shape, as I have known about getting the shape as `shape = pred_batch.shape`.

**Comment by VitalyFedyunin** [comment]
`shape = list(pred_batch.shape)` should do the trick

**Comment by Gavin-Evans** [comment]
> Hi, guys, today I want to create an zeros tensor based on similar shape of another torch.Tensor, so I change the shape like:
> 
> ```python
>         shape = pred_batch.shape
>         # [4,1020,3384]
>         shape[1] = 690
> ```
> 
> However, an error appeared as
> 
> > TypeError: 'torch.Size' object does not support item assignment
> 
> So how can I realize this task?
> 
> Any answer or idea will be appreciated!

you may have a try:
        b, c, *d = pred_batch.shape
        # [4,1020,3384]
        c = 690
        new_tensor = torch.randn((b , c, *d))
