### ISSUE TITLE
rename .cuda(async=..) parameters

### ISSUE THREAD

**Issue by kmike** [pytorch/pytorch#3431]
According to https://www.python.org/dev/peps/pep-0492/#deprecation-plans, `async` will become a keyword in Python 3.7; it means it can't be used as an argument name, as it'd be a SyntaxError.

**Comment by colesbury** [comment]
They've made this a `SyntaxError` for real now in Python 3.7, so we should fix this soon.

@apaszke suggests `nonblocking` as the replacement keyword, which seems reasonable to me.

For backwards compatibility, we should try to accept both the new keyword and `async` in the C++ bindings for things like `Tensor.copy_` and `Tensor.cuda`.

**Comment by ezyang** [comment]
@goldsborough has volunteered to work on this, so he can unblock our pytorch-dockerfiles deploy (since the nightly binaries we were using have revved to a version of Python which hard errors on async now.)

**Comment by johntiger1** [comment]
Was this fixed?

**Comment by colesbury** [comment]
@johntiger1 yes

**Comment by johntiger1** [comment]
Thanks, yep it is `non_blocking` now from my understanding

https://pytorch.org/docs/stable/tensors.html#torch.Tensor.cuda
