### ISSUE TITLE
ONNX Export option to exclude a function from tracing

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#34342]
## 🚀 Feature

When exporting a model some times to fix the shape of an intermediate tensor.
For example the shape could be `1x3x10x10`  but we want to continue tracing with `2x3x10x10`.
In this case since the network is such that it can handle different batch sizes, the output is valid. 

## Motivation

Currently some ONNX ops are exported assuming fixed shapes and the input shape determines the logic and ops used in export, e.g. 

```Python
def view(g, self, size):
    size = sym_help._maybe_get_const(size, 'is')
    if sym_help._is_value(size):
        shape = size
    else:
        if self.isCompleteTensor():
            self_sizes = self.type().sizes()
            if self_sizes and len(size) == 2 and self_sizes[0] == size[0]:
                return g.op("Flatten", self, axis_i=1)
        shape = g.op("Constant", value_t=torch.LongTensor(size))
    return g.op("Reshape", self, shape)
```

while this is fine for static models we want to decouple the shapes of some tensors at export time.
Since the shapes are dynamic, we cannot guarantee an intermediate tensor has the shape we want for tracing. So if we export and `Flatten` is used, it may not work later for an ops that needs `Reshape` because `Resahpe` is more powerful it can handle more cases than `Flatten`.

## Pitch

Provide a decorator like `@trace_ignore` that we could use and reshape tensors at export time without it being traced.

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
I don't really understand what's being requested here. @eslambakr @dashesy can you please give a concrete example of a model that would be treated differently under this proposal, and why `dynamic_axes` or `torch.jit.script` of a sub-module or sub-function can't be used to achieve what you want?

**Comment by dashesy** [comment]
Basically, would be nice to have an attribute to declare the shape of and intermediate tensor (to help shape inference with dynamic shapes). This is to help shape inference where otherwise it is difficult to correctly find the shape. 
This will be helpful even with custom ops, or when we manually change the exported onnx later

**Comment by garymm** [comment]
Thanks for explaining.

If the user sets `dynamic_axes` on the inputs, this should be propagated through to intermediate tensors by shape inference.
Is there an example where this doesn't work?

**Comment by dashesy** [comment]
Sometimes with `dynamic_axes` still some shape is not correctly inferenced (for some intermediate tensor) as being dynamic. I remember some cases special-cased certain shapes (Flatten was an example at the time). Also, custom ops break the shape inference.

**Comment by garymm** [comment]
@dashesy there's already an API for custom ops to specify output shapes, though I guess it's not documented:

**Comment by dashesy** [comment]
Yes that would address all the issue, thanks

**Comment by garymm** [comment]
Filed https://github.com/pytorch/pytorch/issues/73871 to track. Closing this one.
