### ISSUE TITLE
torch.nn.PixelShuffle does not support dynamic_axes when using onnxruntime.InferenceSession.run?

### ISSUE THREAD

**Issue by reddandelion217** [pytorch/pytorch#34352]
## 🐛 Bug

torch.nn.PixelShuffle does not support dynamic_axes when using onnxruntime.InferenceSession.run

## To Reproduce

```
    class Test_shuffle(torch.nn.Module):
        def __init__(self):
            super(Test_shuffle, self).__init__()
            self.shuffle = torch.nn.PixelShuffle(2)
        def forward(self, x):
            return self.shuffle(x)

    x = torch.ones(2, 4, 4, 4)
    torch.onnx.export(Test_shuffle(), tuple((x,)), 'test_shuffle.onnx', verbose=True,
                      input_names=['input'], output_names=['output'],
                      dynamic_axes={'input': [0, 2, 3], 'output': [0, 2, 3]})
    x = torch.ones(2, 4, 5, 4)
    ort_inputs = {'input': np.array(x)}
    ort_session = onnxruntime.InferenceSession("test_shuffle.onnx")
    ort_outs = ort_session.run(None, ort_inputs)
```

> verbos is below:
 %2 : Tensor = onnx::Reshape(%input, %1)
  %3 : Tensor = onnx::Transpose[perm=[0, 1, 4, 2, 5, 3]](%2)
  %4 : Tensor = onnx::Constant[value=-1  1  8  8 [ CPULongType{4} ]]()
  %output : Float(2, 1, 8, 8) = onnx::Reshape(%3, %4) # D:\python3.7.3\lib\site-packages\torch\nn\modules\pixelshuffle.py:43:0
  return (%output)

> Traceback:
onnxruntime::ReshapeHelper::ReshapeHelper (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2,4,5,4}, requested shape:{-1,1,2,2,4,4}

## Environment
 - PyTorch Version :1.4.0
 - OS :Win10
 - How you installed PyTorch:pip
 - Python version:3.7.3
 - CUDA/cuDNN version:10.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@yf225 - we will take a look.

**Comment by neginraoof** [comment]
Thanks @yf225. I believe this issue is resolved as part of opset 11 export. 
Pixel_shuffle op was updated as part of ONNX opset 11 export. Prior to that, ONNX did not have an operator to match pixel_shuffle directly, so we were using a subgraph which didn't allow for dynamic shapes to export this op.
If you specify the opset_version=11 when calling the export API, you should no longer see this exception.

**Comment by reddandelion217** [comment]
thanks for all your help! you indeed solve my question!@neginraoof  @spandantiwari @yf225

**Comment by codender** [comment]
> thanks for all your help! you indeed solve my question!@neginraoof @spandantiwari @yf225

Hi @reddandelion217 , after specifying the opset_version=11, PixelShuffle supports dynamic_axes?
