### ISSUE TITLE
pytorch sparse_coo_tensor broadcasting in multiplication

### ISSUE THREAD

**Issue by amirhajibabaei** [pytorch/pytorch#34355]
Using broadcasting in normal tensors, the following works
```
torch.ones(3, 1)*torch.ones(3, 10)
```
I need to extend this behavior to sparse vectors, but I can't:
```
i = torch.tensor([[0, 1, 1],
                          [2, 0, 2]])
a = torch.sparse_coo_tensor(i, torch.ones(3, 1), [2, 4, 1])
b = torch.sparse_coo_tensor(i, torch.ones(3, 10), [2, 4, 10])
# gives RuntimeError: mul operands have incompatible sizes
```
Why shouldn't this work? Is there an pytorch function to do this? If not what is the best alternative algorithm?

cc @vincentqb

**Comment by vincentqb** [comment]
Related to #3158

**Comment by LittileFatNoRun** [comment]
I am trapped in the same question. Is there anyone has solutions.

**Comment by amjames** [comment]
Closing as this example no longer errors. `torch.mul` now supports broadcasting over dense dimensions.

**Comment by LittileFatNoRun** [comment]
邮件已收到。                   --ade
