### ISSUE TITLE
torch::from_blob() issues when making a tensor from a vector

### ISSUE THREAD

**Issue by JesperLindberg** [pytorch/pytorch#34362]
## 🐛 Bug

I want to make my `current_state`, which is made of `std::vector<double>` to a `torch::Tensor`.

## To Reproduce

1: Have a dobule vector, i.e `0.0642382 0.0395936 0 0.219108 0.372894 0.422909 0.554452 0.302765 1`
2: `torch::Tensor current_state = torch::from_blob(current_state.data(), { 9}).to(*device);`
3: std::cout << "next state is: \n" << next_state << std::endl;

observe the output: 
```
next state is: 
-1.7024e+35
1.3785e+00
-6.2066e+14
1.2834e+00
0.0000e+00
0.0000e+00
-1.0163e+17
1.5941e+00
nan
```

## Expected behavior

To get a tensor with the same values as my vector...

## Environment

 - PyTorch Version (e.g., 1.0): Libtorch 1.4
 - OS (e.g., Linux): Windows 7 64 bit
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): `cmake --build . --config Release --target INSTALL`
 - Python version: 3.6
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

## Additional context
The following line gives me a tensor that looks like I want, however it crashes when I try to feed it through the network...

`torch::Tensor test_next_state = torch::tensor(current_state);`

**Comment by peterjc123** [comment]
cc @yf225

**Comment by JesperLindberg** [comment]
Solve, was apparently not a bug...
https://discuss.pytorch.org/t/converting-vector-of-double-to-tensor-issues/72256/2
