### ISSUE TITLE
gumbel_softmax encounter nan problem

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/pytorch#34372]
## To Reproduce

1. simply invoke the gumbel_softmax function many times in fp16 mode. Occainonly, it may encounter an nan problem. 

I debug into the gumbel_softmax function and found that in https://github.com/pytorch/pytorch/blob/9a5e9d8cecb1c68eebd69618729a7ec5671b2a06/torch/nn/functional.py#L1495  an element of gumbels is inf.
This happens occasionally. I guess, is it possible by something wrong with fp16 mode?

## Expected behavior

all generated tensor element should be a normal number.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.6.1810 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Graphics Device
GPU 1: Graphics Device

Nvidia driver version: 410.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torch-scatter             1.4.0                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

**Comment by mruberry** [comment]
I was unable to reproduce this issue on a more recent build of PyTorch. @fuzihaofzh, does this issue still occur? If it does, would you post a script I can run to reproduce it, too?
