### ISSUE TITLE
Update PyTorch copyright year for 2020

### ISSUE THREAD

**Issue by Enealor** [pytorch/pytorch#34377]
## 📚 Documentation

The current documentation still copyrights PyTorch for 2019. This can be seen on the [documentation for master](https://pytorch.org/docs/master/) near the bottom.

Note: I addressed this in PR #34291 along with some other documentation issues. This one stands out as it makes information appear to be outdated.

**Comment by mihaimaruseac** [comment]
IANAL but afaik copyright years should not be updated. A copyright year of x means that the file was created in year x and all changes to the file from year x until end of copyright period as defined by law are covered.

Updating the year to x + 1 means that all contributions in year x are no longer covered by copyright

**Comment by Enealor** [comment]
If that's the case, then it shouldn't have been updated from 2018 (#21372).
