### ISSUE TITLE
rand() method for complex dtype

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#34380]
Similar to https://github.com/pytorch/pytorch/pull/34037/files we can view a complex tensor as a float tensor and pass it to uniform_ used by rand

cc @ezyang @anjali411 @dylanbespalko

**Comment by kostekIV** [comment]
Hello, I would like to work on it as my first contribution to pytorch. Could I claim this issue?

**Comment by anjali411** [comment]
Hi @kostekIV yeah for sure!! this task is similar to adding complex support for randn so this might be helpful https://github.com/pytorch/pytorch/pull/34037 feel free to ask any questions and add me as a reviewer on your PR! :)

**Comment by kostekIV** [comment]
@anjali411 Thank you. :)

**Comment by kostekIV** [comment]
Hi @anjali411 I looked into how it was done with `randn` function and have couple of questions.
I see that `normal_` is dispatched through file `native_functions.yml` either to `normal_cpu_` or `normal_cuda_`. Similarly  `uniform_` is dispatched to either `legacy::cpu::_th_uniform_` or to `uniform_cuda_`. I see that function `legacy::cpu::_th_uniform_` is being generated in build directory. I am not sure how it is generated and from what? Do I follow this chain correctly? If so where should I look for places to modify `legacy::cpu::_th_uniform_`? And in this case function `at::native::view_complex_as_float` would probably needed to be in some header file to be reused but there is some issue blocking that, right? Thank you for your time.

**Comment by anjali411** [comment]
Hey @kostekIV  I think we should definitely put at::native::view_complex_as_float in a header in a new file for complex ```/aten/src/ATen/ComplexHelper.h```. That issue might be resolved if the function is defined inline :) And so passing in the resized tensor (complex tensor viewed as fp tensor, similar to that in randn) to the existing rand function and updating the function calls in this file ```/aten/src/ATen/native/TensorFactories.cpp``` should work. thank you so much for working on this :D let me know if you have any more questions
