### ISSUE TITLE
Implementing SLIDE algorithm within Pytorch

### ISSUE THREAD

**Issue by mritunjaymusale** [pytorch/pytorch#34391]
## 🚀 Feature
Implementing the SLIDE algorithm.

## Motivation

I came across [this](https://arxiv.org/abs/1903.03129v2) new paper while browsing through the AI group on facebook. I haven't read it completely yet, but I believe what they have manged to pull off(based on my current understanding) is, they have gotten rid of matrix multiplication all together  from Network and replace it with hashing based approach which runs on CPU but can train the  model with the speed at which a typical GPU would do. It also has almost linear scaling i.e more cores = faster training. 

## Pitch

A custom implementation of SLIDE algorithm in Pytorch which is built purely for supporting the  Pytorch ecosystem.

## Alternatives

I went on [their](https://github.com/keroro824/HashingDeepLearning/issues/7) Git repo and asked them for a Cython implementation and they agreed and are interested in making it happen. So maybe Pytorch team can port their Cython implementation(once it's available) within Pytorch.

**Comment by gchanan** [comment]
We'll wait until we have more signal (namely citations).  If that happens, please reopen.
