### ISSUE TITLE
Have isFloatingType, tensor.is_floating_point() return true for complex dtype

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#34392]
https://github.com/pytorch/pytorch/pull/34093/files

cc @ezyang @anjali411 @dylanbespalko

**Comment by wDaniec** [comment]
Hey. I've been using pytorch for quite some time now and wanted to contribute to it in some way. It seems like this issue could be a nice starting point. Is it ok if I claim this issue?

**Comment by ezyang** [comment]
Yes, this should be a pretty small fix. Tag @anjali411 as reviewer.

**Comment by anjali411** [comment]
@wDaniec following this https://github.com/pytorch/pytorch/pull/34093#issuecomment-597354763, we might not want to make this change anymore. However if you would like, you can work on one of these two issues:
https://github.com/pytorch/pytorch/issues/33568
https://github.com/pytorch/pytorch/issues/33567

**Comment by wDaniec** [comment]
> @wDaniec following this [#34093 (comment)](https://github.com/pytorch/pytorch/pull/34093#issuecomment-597354763), we might not want to make this change anymore. However if you would like, you can work on one of these two issues:
> #33568
> #33567

Thank you for sending alternative issues. I will work on #33567 then.

**Comment by anjali411** [comment]
closing this because we no longer want this behavior. `isFloatingType` returns for complex dtypes and `isComplexType` has been added to check if it's a complex type
