### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by DanlanChen** [pytorch/pytorch#3441]
http://pytorch.org/tutorials/beginner/nlp/deep_learning_tutorial.html
“You don’t need to worry about what specifically these algorithms are doing unless you are really interested. Torch provies many in the torch.optim package, and they are all completely transparent. ”
---->Torch provides many in the torch.optim package,

**Comment by soumith** [comment]
fixed via #172, the tutorials should be regenerated shortly.
