### ISSUE TITLE
Dynamically specify the in_features of nn.linear() in pytorch

### ISSUE THREAD

**Issue by bupt-renpei** [pytorch/pytorch#34464]
class Network(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(784, 256)
        self.output = nn.Linear(256, 10)

Hi everyone,

Is there any approach to avoid calculate the in_feature in nn.linear()? For example, I want to replace the previous statement with the following style:

self.hidden = nn.Linear(None, 256)
self.output = nn.Linear(None, 10)

**Comment by ptrblck** [comment]
That's not possible, as you need to initialize the parameters (`weight` and `bias`) with a certain shape.
You could [concatenate/crop](https://discuss.pytorch.org/t/how-to-dynamically-change-the-size-of-nn-linear/29634/2?u=ptrblck) the parameters or precalculate the shape.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
In the future, please use the forum to ask questions: https://discuss.pytorch.org/
