### ISSUE TITLE
The output tensors are different when same code is implemented in Jupyter and Spyder .

### ISSUE THREAD

**Issue by SerendipityForZhch** [pytorch/pytorch#34477]
## ❓ Questions and Help

The demo is simple as follows.
```
print(torch.__version__)    
x = torch.tensor([1.0,2.2],requires_grad=True)
print(x)  
y = x + 2  
print(y)  
print(y.grad_fn , x.grad_fn)  
```
In Jupyter, the demo output:  
```
1.2.0  
tensor([1.0000, 2.2000], requires_grad=True)  
tensor([3.0000, 4.2000], grad_fn=<AddBackward0>)  
<AddBackward0 object at 0x000000000F22A630> None  
```
In Spyder, the demo output:  
```
1.2.0  
tensor([1.0000, 2.2000], requires_grad=True)  
tensor([3.0000, 4.2000])  
None None  
```  
As we can see, the y.grad_fn is None in Spyder which is not expected.  When we try y.backward(), a RuntimeError occur.  
"RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn."

I have report this issue to Spyder, but they think this is a problem with Pytorch.
I don't know why the results are different.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
Hi,

As you saw in the issue templace, we use github issues only for bugs or feature requests.
In the future, use the forum to ask questions: https://discuss.pytorch.org/

For your problem, can you check in Spyder if grad mode is enabled with `torch.is_grad_enabled()`. Most likely you disabled it and did not restart the python environment?

**Comment by ezyang** [comment]
This is also a really old version of PyTorch. I'm closing this as non-actionable. If you manage to repro with the latest version of PyTorch and have a clear description of the Spyder setup, maybe we can help more.
