### ISSUE TITLE
Missing ‘get_trace_graph’ function in Torch1.4 

### ISSUE THREAD

**Issue by XYAskWhy** [pytorch/pytorch#34476]
‘get_trace_graph’ function could be found in Torch1.3, but not in 1.4 version. I wonder if it is replaced with another function? If so, which one? Thanks in advance : )

cc @suo

**Comment by suo** [comment]
Yes, `get_trace_graph` was an internal function that was intended for use by ONNX export only. As an alternative, please get the graph like: 
```
traced = torch.jit.trace(model, inputs)
traced_graph = traced.graph
```
Let me know if you're having any issues!
