### ISSUE TITLE
get error when load checkpoint and finetune with optimizer, RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float

### ISSUE THREAD

**Issue by vincezengqiang** [pytorch/pytorch#34470]
hi， i get error when i load checkpoint and used to init optimizer，the  code is fellowed:
# save
torch.save(
                        {
                            'epoch': epoch,
                            'model': model,
                            'optimizer_state_dict': optimizer.state_dict(),
                            'loss': loss
                        },
                        '{0}/CRNN_{1}_{2}_ckpt.pth'.format(
                            expr_dir, epoch, best_ratio))

# load
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
checkpoint = torch.load(path)
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
crnn.load_state_dict(torch.load(pretrained)['model'].state_dict(),
                             strict=True)

then, get error :RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float

but if I don't load the state_dict of optimizer, program will work on, so could you please help me?
thanks a lot!

**Comment by amritkumar9595** [comment]
i am running into this error, every time I am trying to resume my training from the checkpoint. How did u solve this issue?

**Comment by ofekp** [comment]
Experiencing the same issue, would love to know how to solve this please.

**Comment by waystogetthere** [comment]
This solution worths more browsing
