### ISSUE TITLE
CUDA for Pytorch

### ISSUE THREAD

**Issue by SirGaLaHaD69** [pytorch/pytorch#34481]
I already had installed cudatoolkit 10.1.243 for TensorFlow GPU. Now while installing PyTorch there's again a requirement of cudatoolkit 10.1.168. I had also set my ENV variables for the previous version.

So what should I do now?

Can I (if possible ) ignore the cuda installation ? how will it affect ?

cc @ezyang @seemethere

**Comment by peterjc123** [comment]
PyTorch packages doesn't rely on the global CUDA installation. For conda packages, it relies on a conda package called `cudatoolkit`. For wheels packages, the CUDA libraries are installed locally.
