### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by keloemma** [pytorch/pytorch#34482]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hello, I ma trying to train a model on a server I ma getting this error : 

NFO - 03/09/20 15:24:35 - 0:00:00 - Number of parameters (model): 341725
INFO - 03/09/20 15:24:42 - 0:00:07 - Before setting SingleTrainer variables.
INFO - 03/09/20 15:24:42 - 0:00:07 - After setting SingleTrainer variables.
INFO - 03/09/20 15:24:42 - 0:00:07 - Found 0 memories.
INFO - 03/09/20 15:24:42 - 0:00:07 - Found 4 FFN.
INFO - 03/09/20 15:24:42 - 0:00:07 - Found 69 parameters in model.
Traceback (most recent call last):
  File "train.py", line 391, in <module>
    main(params)
  File "train.py", line 266, in main
    trainer = SingleTrainer(model, data, params)
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/trainer.py", line 857, in __init__
    super().__init__(data, params)
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/trainer.py", line 77, in __init__
    self.set_optimizers()
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/trainer.py", line 188, in set_optimizers
    self.optimizers['model'] = get_optimizer(self.parameters['model'], params.optimizer)
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/optim.py", line 270, in get_optimizer
    return optim_fn(parameters, **optim_params)
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/optim.py", line 112, in __init__
    weight_decay=weight_decay,
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/optim.py", line 39, in __init__
    state['exp_avg'] = torch.zeros_like(p.data)
RuntimeError: CUDA error: no kernel image is available for execution on the device

cuda : 10.0
pytorch :1.4

**Comment by peterjc123** [comment]
Would you please tell me what is your GPU?

**Comment by keloemma** [comment]
> Would you please tell me what is your GPU?

-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 26%   26C    P8    12W / 250W |     75MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 26%   27C    P8    14W / 250W |     75MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17781      C   python3.5                                     63MiB |
|    1     17781      C   python3.5                                     63MiB |

**Comment by peterjc123** [comment]
The name of the GPU is not complete in your previous output. BTW, may I ask which command did you use to install PyTorch?

**Comment by keloemma** [comment]
> The name of the GPU is not complete in your previous output. BTW, may I ask which command did you use to install PyTorch?

name of the GPU is hyperion but when you said name  I do not understand could you be a clearer. I install Putorch with this command : 

pip install torch==1.4+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by peterjc123** [comment]
Is your GPU Titan X, Titan V or Titan XP?

**Comment by keloemma** [comment]
> Is your GPU Titan X, Titan V or Titan XP?

When I run nvidia-smi  ; I get this : GPU  Name        Persistence-M

**Comment by peterjc123** [comment]
No no no, it is a column name. I want to know what exactly is `| 0 GeForce GTX TIT... ` referring to.

**Comment by keloemma** [comment]
> No no no, it is a column name. I want to know what exactly is `| 0 GeForce GTX TIT... ` referring to.

I do not really know I will ask one of my colleagues

**Comment by keloemma** [comment]
> No no no, it is a column name. I want to know what exactly is `| 0 GeForce GTX TIT... ` referring to.

GPU 0: GeForce GTX TITAN Black (UUID: GPU-b090c9b8-e98c-158d-fb91-3efb70f15a12)
GPU 1: GeForce GTX TITAN Black (UUID: GPU-4bea0593-e7f5-7904-06f7-cb09f0bd49d2)

**Comment by peterjc123** [comment]
According to https://developer.nvidia.com/cuda-gpus, they are of CUDA compute compatibility 3.5, which is already kicked out in our binaries builds starting from 1.3.1. So there are two options:
1. Build for source
2. Use old packages like 1.3.0

**Comment by keloemma** [comment]
> According to https://developer.nvidia.com/cuda-gpus, they are of CUDA compute compatibility 3.5, which is already kicked out in our binaries builds starting from 1.3.1. So there are two options:
> 
>     1. Build from source
> 
>     2. Use old packages like 1.3.0

thank you
