### ISSUE TITLE
build from source error

### ISSUE THREAD

**Issue by busterbyron** [pytorch/pytorch#34484]
**Description:**
I'm trying to build pytorch from source, but this happens:

[ 26%] Linking CXX static library ../../../../lib/libmkldnn.a
[ 26%] Built target mkldnn
[ 26%] Built target fbgemm_avx2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/buster/Google Drive/Code/test/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/buster/Google Drive/Code/test/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/home/buster/Google Drive/Code/test/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/buster/miniconda3/envs/test/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

**Preceding Commands:**
conda create -n test python=3.7
conda activate test

conda install numpy pyyaml mkl mkl-include setuptools cmake cffi
conda install -c pytorch magma-cuda102 

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch

export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export CUDNN_LIB_DIR=/usr/include/cudnn.h/lib64
export CUDNN_INCLUDE_DIR=/usr/include/cudnn.h/include

python3 setup.py install

**Other Info:**
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 770     Off  | 00000000:01:00.0 N/A |                  N/A |
| 35%   30C    P8    N/A /  N/A |    285MiB /  1996MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.

OS: Ubuntu 18.04

And I'm pretty new to Linux, so it's entirely possible that I'm flat-out making a dumb mistake.

**Comment by albanD** [comment]
Hi,

There is not much information in what you shared. Could you share the full build log please? Also if you can locate the actual error message.

**Comment by busterbyron** [comment]
Hey, thanks for responding. Turns out I had a driver (and thus cuda) that was incompatible with my system, and I think I messed up the path a bit.

PyTorch is working great now, except that despite building from source I still get the following message--is that to be expected?

it__.py:87: UserWarning: 
    Found GPU0 GeForce GTX 770 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.

  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))it__.py:87: UserWarning:

**Comment by albanD** [comment]
Yes, because the new features in 3.5 give very large speed improvement, we do not restrict ourselves to not use these features. So running on 3.0 might stop working at any time as it is not an officially supported capability.
We try to do our best to make it still work, but that might not be possible going forward.

This is a python warning, so you can silence it as any other python warning if you don't want to see it.
