### ISSUE TITLE
cudnn backend needs contiguity checks to report better error messages

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#345]
Currently given a non contiguous input it will do forward (not sure about correctness) and fail on grad wrt weight with `RuntimeError: CUDNN_STATUS_INTERNAL_ERROR`

**Comment by glample** [comment]
Yes, LSTM fails for me without .contiguous() (at least in the batch_first=True mode)

**Comment by suryabhupa** [comment]
But this is a known precondition for CuDNN, right? Is the request simply to have CuDNN report better error messages?

**Comment by soumith** [comment]
yes, i think the issue is about better error messages from what i understand as well.

**Comment by szagoruyko** [comment]
afaik there are no contiguity checks right now, and one can get either an error or incorrect outputs/gradients.

**Comment by glample** [comment]
Is it really possible it returns something wrong?? For now I have written my code without thinking too much about the contiguity of what I feed to Conv / LSTM modules, I just assumed pytorch would complain if it requires something contiguous, and simply add .contiguous() where it's necessary.

**Comment by apaszke** [comment]
Ok, so it appears that cuDNN conv modules could give invalid results, but that could happen only if one had non-contiguous weights. As long as you sticked to nn modules this bug did not affected you in any way. For RNN modules, we haven't seen any issues like these with conv, but we'll go over the code to make sure there are no more errors like these.

Another other error is that sometimes non-contuguous inputs gave `CUDNN_STATUS_INTERNAL_ERROR` for some unknown reason. But it was harmless in a sense, that it would quietly mess up your results.

@ngimel do you know of any other places where we should be more careful with contiguity checks? any hints on why non-contig inputs can give internal errors?

**Comment by suryabhupa** [comment]
@glample -- yeah CuDNN will complain that things aren't contiguous but it will not go ahead and make it contiguous for you. This is just part of the interface/precondition for using it, and maybe allocating memory to make it contiguous would make CuDNN slow, so they don't do it.

**Comment by ngimel** [comment]
Weights should be contiguous everywhere (filterDescriptor does not have strides parameter). For bn, all auxiliary tensors (savevar, savemean, running averages) should be contiguous, for all rnn variants inputs and outputs should be contiguous. Different convolution algos have different requirements wrt data contiguity, but they should error with CUDNN_STATUS_NOT_SUPPORTED if given an input they can't handle. Also, conv and bn performance on non-contiguous inputs can be quite horrible. 
@szagoruyko, can you please give an example where you are getting CUDNN_STATUS_INTERNAL_ERROR?

**Comment by soumith** [comment]
now the relevant buffers are checked for contiguity in master

**Comment by zhanghan328** [comment]
I got the same problem.  what should I do?
runfile('/home/wind/demo/facial_expression_classification/main.py', wdir='/home/wind/demo/facial_expression_classification')
Traceback (most recent call last):

  File "<ipython-input-27-6ab2f2a1fc04>", line 1, in <module>
    runfile('/home/wind/demo/facial_expression_classification/main.py', wdir='/home/wind/demo/facial_expression_classification')

  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/home/wind/demo/facial_expression_classification/main.py", line 93, in <module>
    train(epoch)

  File "/home/wind/demo/facial_expression_classification/main.py", line 64, in train
    output = model(data)

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/wind/demo/facial_expression_classification/main.py", line 47, in forward
    x = self._forward_features(x)

  File "/home/wind/demo/facial_expression_classification/main.py", line 40, in _forward_features
    x = F.relu(F.max_pool2d(self.conv1(x),2))

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 202, in __call__
    result = self.forward(*input, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 37, in conv2d
    _pair(0), groups)

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/conv.py", line 35, in forward
    output = self._update_output(input, weight, bias)

  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/conv.py", line 93, in _update_output
    self.groups, cudnn.benchmark)

RuntimeError: CUDNN_STATUS_BAD_PARAM

![2017-03-16 11-04-03](https://cloud.githubusercontent.com/assets/16316669/23980056/4ab1a498-0a38-11e7-97c3-40792b55eb56.png)

**Comment by zhanghan328** [comment]
@soumith @apaszke
