### ISSUE TITLE
Any reason to keep AT_WARN?

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#34502]
The use of `AT_WARN` generates a considerable amount of warning messages during compilation. Does `AT_WARN` still have any remaining value, I wonder? Would it be OK to replace all `AT_WARN` with `TORCH_WARN` and remove the definition of `AT_WARN` at this moment?

**Comment by albanD** [comment]
cc @ezyang we do want to just remove them all right?

**Comment by ezyang** [comment]
Ye, we should rename all of them and delete `AT_WARN` entirely. The problem is we don't have a Werror build so people keep finger macroing the old name when they add warnings. So we have to rip the bandaid off entirely to keep it fixed.
