### ISSUE TITLE
RNN + DataParallel + scripting is broken 

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#34513]
## 🐛 Bug

Because of complex handling of parameters in RNN modules, trying to script RNN module and wrap it in DataParallel results in errors. 

## To Reproduce
1) Script module + move it to .cuda():
```
m = torch.nn.RNN(10,20,2)
m = torch.jit.script(m)
m = m.cuda() #moving after scripting, only generic _apply is called, params are not flattened
input = torch.randn(5,3,10, device="cuda")
out = m(input) #Warning: parameters are not flattened ...
```
Happens because RNN’s _apply is not called, and parameters are not reflattened after being moved.  To avoid this, first move module to cuda, then script. It's still only a warning and some perf penalty, the model actually works.

2) cuda module + script + DataParallel
```
m = torch.nn.RNN(10,20,2).cuda()
m = torch.jit.script(m)
m = torch.nn.DataParallel(m, [0,1]) # many things went wrong here. overriden _replicate_for_data_parallel was not called, so _flat_weights and _flat_weights_names lists were not copied. Overriden __setattr__ was not called, so _flat_weights is pointing to some wrong tensors with wrong history
input = torch.randn(6,4,10)
out = m(input) #RuntimeError: parameters are on the wrong device ...
```
There is no workaround for this that I know of. First wrapping in DataParallel and the scripting does not work because of kwargs in DataParallel’s forward that script refuses to script. 

cc @suo

**Comment by eellison** [comment]
Dup of https://github.com/pytorch/pytorch/issues/30635

**Comment by ngimel** [comment]
No it's not a dup. #30635 is "module wrapped in DataParallel cannot be scripted", this is "a particular scripted module cannot be wrapped in DataParallel".

**Comment by albanD** [comment]
I guess the custom "replicate" logic that exists for the RNN module in `RNNBase` is not properly replicated on the jit side?

**Comment by ngimel** [comment]
Yes, see the comment in the failing snippet. `_replicate_for_data_parallel` and `__setattr__` in jit don't call custom RNN overrides.

**Comment by eellison** [comment]
@suo were you looking at `__apply__` / weights compaction at some point ?

**Comment by you74674** [comment]
> m = torch.nn.RNN(10,20,2)
> m = torch.jit.script(m)

I wonder why this line doesn't give error?
Is #28418 fixed? (Or did you patch it by yourself?)
I have tried in the latest nightly build(1.5.0.dev20200326) and it's not fixed yet.

**Comment by betklab** [comment]
this issue still holds for all versions of pytorch. Do you have any plan to fix this?

**Comment by talipturkmen** [comment]
This issue still persists for all versions of Pytorch. Do you have any plan to fix this?
