### ISSUE TITLE
Small error in the parameter description of OneCycleLR 

### ISSUE THREAD

**Issue by lordeddard** [pytorch/pytorch#34531]
## 📚 Documentation

In the parameter description of `total_steps` in the class `OneClassLR` it says
> The total number of steps in the cycle. Note that if a value is provided here, then it must be inferred by providing a value for epochs and steps_per_epoch. Default: None

Shouldn't that be 
> The total number of steps in the cycle. Note that if a value is **not** provided here, then it must be inferred by providing a value for epochs and steps_per_epoch. Default: None

The corresponding line in the source code. https://github.com/pytorch/pytorch/blob/4f62cbe7de8f867809ca601c996dd48a5a28ffca/torch/optim/lr_scheduler.py#L1046

cc @vincentqb

**Comment by albanD** [comment]
Hi,

Good catch. Could you send a PR to fix the typo?

**Comment by lordeddard** [comment]
Sure!
