### ISSUE TITLE
`torch.exp` hangs for CPU execution 

### ISSUE THREAD

**Issue by turtleizzy** [pytorch/pytorch#34533]
## 🐛 Bug

`torch.exp` hangs for CPU execution.

## To Reproduce

`torch.exp(torch.tensor([1.0, 2.0]))`

## Expected behavior

It should not hang. It does not hang for pytorch <1.2. 

## Environment

 - PyTorch Version (e.g., 1.0): 1.2-1.4
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): conda environment, pytorch installed via pip
 - Python version: 3.6
 - Any other relevant information:
This problem seems to be related to system configuration since I was not able to reproduce in pytorch official docker image (pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime).

**Comment by turtleizzy** [comment]
Similar issue: https://github.com/pytorch/pytorch/issues/25904

**Comment by albanD** [comment]
Closing in favor of #25904 that is the same issue. Please send there a full script to reproduce the deadlock.
