### ISSUE TITLE
Onnx export of scripted `scatter_` fails silently

### ISSUE THREAD

**Issue by julianmack** [pytorch/pytorch#34538]
## 🐛 Bug

`torch.onnx.export`-ing a `torch.script`-ed model with the `.scatter_` operation fails silently. 

## To Reproduce

I would like to export an onnx graph with the functionality:
```python
class IdxModel(torch.nn.Module):
    def forward(self, x):
        b = torch.ones(x.shape[1:])
        i = 1
        x[i] = b
        x += 1. # so that onnx model is not a no-op
        return x
```
A requirement of my use-case is that the model must be scripted before exporting (due to control flow not shown here). 

**As noted in the docs** an export of `IdxModel` ignores the line `x[i] = b` meaning the exported onnx model is not equivalent to the PyTorch model: https://pytorch.org/docs/stable/onnx.html#limitations

In the link above, it is suggested that the `scatter_` operation should be used instead for inplace indexing giving the following class:

```python3
class IdxModelScatter(torch.nn.Module):
    def forward(self, x):
        b = torch.ones((x.shape[1:]))
        i = 1
        idx = torch.tensor([i], dtype=torch.int64).expand(x.shape[1:]).unsqueeze(0)
        x.scatter_(0, idx, b.unsqueeze(0))
        x += 1. 
        return x
```

Define the following helper function to test the equivalence of the `onnxruntime` and PyTorch versions of these models:

```python3

import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""
import onnx
import torch 
from torch import Tensor
import onnxruntime as ort
from copy import deepcopy

def onnx_export_and_check_equiv(model):
    """Exports onnx inplace indexing model and returns ort and PyTorch equivalence."""
    input_size = 2
    seq_len = 3
    batch = 2
    INPUT_NAMES = ["input"]
    OUTPUT_NAMES = ["out"]
    DYNAMIC_AXES = {
        "input": {0: "seq_len", 1: "batch"},
        "out": {0: "seq_len", 1: "batch"},

    }
    fp = 'idx.onnx'

    # gen args for torch and ort session
    args = torch.zeros(seq_len, batch, input_size),
    args_np = [x.numpy() for x in deepcopy(args)]
    dict_args = {k: args_np[idx] for idx, k in enumerate(INPUT_NAMES)}


    example_outputs = model(*deepcopy(args))

    torch.onnx.export(
                model,
                args,
                fp,
                export_params=True,
                verbose=False,
                example_outputs=example_outputs,
                dynamic_axes=DYNAMIC_AXES,
                input_names=INPUT_NAMES,
                output_names=OUTPUT_NAMES,
                opset_version=11,
            )

    onnx_model = onnx.load(fp)
    onnx.checker.check_model(onnx_model)

    # start ort session 
    ort_session = ort.InferenceSession(fp)

    outputs = ort_session.run(None, dict_args)
    return torch.allclose(torch.tensor(outputs), example_outputs, atol=1e-4, rtol=1e-2)
```

And check the results are as expected for the two models above:

```python
model = IdxModel()
assert not onnx_export_and_check_equiv(model)

model = IdxModelScatter()
assert  onnx_export_and_check_equiv(model) 
```
Both of these asserts pass, demonstrating that `scatter_` **is necessary**. 

However, if the second model is `torch.jit.script`-ed, the second assert now fails:
```python3
model = torch.jit.script(IdxModelScatter())
assert  onnx_export_and_check_equiv(model) 
```
... raises assertion error. **Looking at the values confirms that this is the result of ignoring the inplace index**. Without knowing exactly what is going on here, this suggests that scripting the `.scatter_` makes it invisible to ONNX export in a similar way to that in which `a[i] = b` is ignored. 

An possible workaround here is to `torch.jit.trace` the scatter operation in a submodule and then  script the rest of the module but I was not able to get this to work - all suggestions welcome! 

## Expected behaviour

Expect `torch.jit.script` of `IdxModelScatter` to be identical in PyTorch and onnx. 
 

## Environment
```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 435.21
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.4.0
[pip] torchaudio==0.4.0
[pip] warprnnt-pytorch==0.1
[conda] _pytorch_select           0.1                       cpu_0    anaconda
[conda] blas                      1.0                         mkl    conda-forge/label/cf201901
[conda] mkl                       2019.4                      243    anaconda
[conda] mkl-service               2.3.0            py37he904b0f_0    anaconda
[conda] mkl_fft                   1.0.12           py37ha843d7b_0    anaconda
[conda] mkl_random                1.0.2            py37hd81dba3_0    anaconda
[conda] pytorch                   1.4.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.4.0                    pypi_0    pypi
```

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ezyang** [comment]
This is likely because the "functionalization" that ONNX does during tracing doesn't know about aliases, so while the immediate view operation gets functionalized, the mutation doesn't reflect on the base.

@asuhan if we get XLA's view handling in repo that would solve this problem.

**Comment by garymm** [comment]
This is being tracked internally by Microsoft at  https://msdata.visualstudio.com/Vienna/_workitems/edit/1421807.

**Comment by justinchuby** [comment]
`torch.onnx` currently handles inplace ops as if there are not. I suggest always using non- inplace ops when possible.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
