### ISSUE TITLE
RuntimeError: sparse_.is_sparse() INTERNAL ASSERT FAILED  on torch 1.4

### ISSUE THREAD

**Issue by yanty123** [pytorch/pytorch#34532]
## 🐛 Bug

I try to build a GCN model, and i use the torch.sparse to compute the sparse matrix, in the loss.backward() funtion, it breaks.  

## To Reproduce

1.build the network with torch.sparse
1.

  File "E:/GCN/GCN (1).py", line 123, in <module>
    loss.backward()
  File "C:\Users\小翔\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\小翔\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\autograd\__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: sparse_.is_sparse() INTERNAL ASSERT FAILED at ..\torch\csrc\autograd\generated\Functions.cpp:541, please report a bug to PyTorch. 

## Expected behavior

i just want it runs. 

## Environment
PyTorch version: 1.4.0+cpu
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Microsoft Windows 10 家庭中文版
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 970M
Nvidia driver version: 399.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.14.6
[pip3] torch==1.4.0+cpu
[pip3] torch-sparse==0.6.0
[pip3] torchvision==0.5.0+cpu
[conda] Could not collect

## Additional context

cc @vincentqb @aocsa @nikitaved @pearu @mruberry

**Comment by peterjc123** [comment]
Would you please share the code?

**Comment by yanty123** [comment]
OK, my ugly code is in the annex.
You can run GCN.py to recover it.


And I have run it without any problems with torch 1.0+cpu right now, maybe there is something wrong with the new version?





Thank you very much!
Good luck and best wishes!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peterjc123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月10日(星期二) 晚上6:09
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Faker "<316506204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] RuntimeError: sparse_.is_sparse() INTERNAL ASSERT FAILED  on torch 1.4 (#34532)




Would you please share the code?

**Comment by peterjc123** [comment]
Where is GCN.py?

**Comment by yanty123** [comment]
> Where is GCN.py?
sorry, i emailed it ,but it didn't appear here before.
[GCN_codes.zip](https://github.com/pytorch/pytorch/files/4312870/GCN_codes.zip)

**Comment by albanD** [comment]
Looking at the code, the error is because `_sparse_addmm` is called with a non-sparse Tensor.

**Comment by yanty123** [comment]
Maybe sparse_.mm？&nbsp;&nbsp;
But i&nbsp; am sure that there is one dense tensor and one sparse&nbsp; tensor.&nbsp;&nbsp;
And it can run in the caclucate lines. however it&nbsp; breaks after&nbsp; loss. backend()
thank you

---Original---

**Comment by albanD** [comment]
Not sure how you end up calling this function but `_sparse_addmm` is an internal function that you should not call directly.
And it works fine if used directly:
```python
import torch

i = torch.LongTensor([[0, 1, 1],
                          [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])
s = torch.sparse.FloatTensor(i, v, torch.Size([2,3]))

d = torch.rand(3, 4)
d2 = torch.rand(2, 4)

s.requires_grad_()

res = torch._sparse_addmm(d2, s, d)

res.sum().backward()
```

**Comment by yanty123** [comment]
OK thank you very much.&nbsp;
I will check it sincerely after .&nbsp;
By the way, its amazing that there is no problems when I run it with torch&nbsp; 1. 0.



---Original---

**Comment by mruberry** [comment]
Looks like this issue has been solved.

**Comment by betterzhou** [comment]
> Looking at the code, the error is because `_sparse_addmm` is called with a non-sparse Tensor.

Yes. It is the same for GAT. 
Add the following code into your file
        if x.is_sparse:
            h = torch.sparse.mm(x, self.W)
        else:
            h = torch.mm(x, self.W)
