### ISSUE TITLE
Stop storing THPLayout in the Python argument parser

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#34543]
`torch/csrc/utils/python_arg_parser.h` is the code responsible for parsing our Python arguments, distinguishing between various overloads, and filling in defaulted arguments. The FunctionParameter struct represents a function parameter, and it stores defaults to be used in some cases:

```
struct FunctionParameter {
  FunctionParameter(const std::string& fmt, bool keyword_only);

  bool check(PyObject* obj, std::vector<py::handle> &overloaded_args);

  void set_default_str(const std::string& str);
  std::string type_name() const;

  ParameterType type_;
  bool optional;
  bool allow_none;
  bool keyword_only;
  bool allow_numbers_as_tensors = false;
  int size;
  std::string name;
  // having this as a raw PyObject * will presumably leak it, but these are only held by static objects
  // anyway, and Py_Finalize can already be called when this is destructed.
  PyObject *python_name;
  at::SmallVector<PyObject *, 5> numpy_python_names;
  at::Scalar default_scalar;
  std::vector<int64_t> default_intlist;
  union {
    bool default_bool;
    int64_t default_int;
    double default_double;
    double default_complex[2]; // see Scalar
    at::ScalarType default_scalartype;
    THPLayout* default_layout;
  };
};
```

Note that `default_layout` is the odd entry out for the union: the default in this case points to a THPLayout object, which is a Python object; this is comparison to all the fields which correspond to straight C++ objects. Actually, we also have a C++ type for layouts: `at::Layout`. The goal of this bug is to replace THPLayout with at::Layout, and then work through the consequences.

In https://github.com/pytorch/pytorch/pull/33826 I've already identified some of the other sites which need modifying, but those changes are entwined with other changes which cannot be landed as they break tests. Your job is to read the patch, understand what it does, and extract out *only* the THPLayout changes and verify that tests pass with only these changes.

cc @VitalyFedyunin @jamesr66a

**Comment by terhuhf** [comment]
Closed by https://github.com/pytorch/pytorch/pull/34584
