### ISSUE TITLE
Building pytorch for IOS. Undefined Symbol

### ISSUE THREAD

**Issue by MattToul** [pytorch/pytorch#34541]
I am trying to build pytorch locally to use on an IOS device. 

I have followed every step from : https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source.

The Header Search Path is defined, and I have added the linker flag for libtorch.a.

Unfortunately after finishing the XCode setup, when trying to build the following error occurs : 
<img width="584" alt="Capture d’écran 2020-03-10 à 18 12 24" src="https://user-images.githubusercontent.com/16106984/76339930-1103da80-62fb-11ea-8703-bb205411215b.png">

I also want to point that even if I executed the following command to build Libtorch for IOS : `BUILD_PYTORCH_MOBILE=1 IOS_ARCH=arm64 ./scripts/build_ios.sh`

I get the following warnings which make me believe that the build was unsuccessful : 
<img width="584" alt="warnings" src="https://user-images.githubusercontent.com/16106984/76340137-5b855700-62fb-11ea-8986-f9c3236424a4.png">

Thank you for your help, 
Best,

**Comment by MattToul** [comment]
Solved it by using libtorch_cpu.a

**Comment by maksfourlife** [comment]
> Solved it by using libtorch_cpu.a

Hello, I have the exact same problem as you and I need your help. What do you mean by _"using libtorch_cpu.a"_? What are your header and library search paths? What are your linked binaries? Maybe you used another version of Xcode, Cmake, flags, etc. when compiling?
Thank you for your help
