### ISSUE TITLE
Multidimensional CUDA irfft modifies input

### ISSUE THREAD

**Issue by ar4** [pytorch/pytorch#34551]
## 🐛 Bug

torch.irfft modifies the input Tensor for the multidimensional case on a GPU

## To Reproduce

```
import torch
t = torch.ones(2,2,2).cuda()
t_backup = t.clone()
torch.irfft(t, 2, signal_sizes=(2,2))
print((t-t_backup).abs().sum().item()) # should be 0, but is 8
```

## Expected behavior

The input should not be modified

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ar4** [comment]
It appears that this does not occur in all situations. I have tried running the example code on K80, P4, and P100 GPUs and it always prints the expected 0.0. Either it occurs on T4 GPUs (as in the case I reported above), or there was something wrong with the instance I was using when the problem occurred. I have not yet been able to re-test it on another T4 instance.

**Comment by ar4** [comment]
I note that the cuFFT manual says

> Out-of-place complex-to-real FFT will overwrite input buffer if custom strides are set by the user.

Is is possible that there are situations in which PyTorch might be setting a custom stride?

**Comment by ezyang** [comment]
Yes, we may have misunderstood the specification and are setting up custom strides without cloning first, esp if the input is noncontiguous. sounds like this might be easy to fix, in that case; just clone the input before calling.

**Comment by ar4** [comment]
I ran the example code above on a new T4 instance, with the same result (8 instead of the desired 0). I imagine that the Tensor should be contiguous in memory when allocated in this way. If so, a custom stride may not be the issue.
