### ISSUE TITLE
Backward operations not decorated with stashed seq marker

### ISSUE THREAD

**Issue by mkardas** [pytorch/pytorch#34565]
## 🐛 Bug
According to `Forward-backward correlation` section of [autograd documentation](https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.emit_nvtx), when CUDA profiling is enabled forward operations should be decorated with `seq=<N>` and backward operations should be decorated with `stashed seq=<N>` with matching numbers for corresponding forward-backward operations. Currently all operations are decorated with `seq=<N>` markers.

## To Reproduce

```python
# test.py
import torch

with torch.autograd.profiler.emit_nvtx():
  w = torch.randn(2, 2).cuda().requires_grad_()
  b = torch.randn(2, 1).cuda().requires_grad_()
  x = torch.randn(2, 1).cuda()
  y = (w @ x + b).sum()
  y.backward()
```

```python
# log.py
import sqlite3
import pandas as pd

with sqlite3.connect("cuda.prof") as conn:
  print(pd.read_sql_query("SELECT value FROM CUPTI_ACTIVITY_KIND_MARKER as markers INNER JOIN StringTable as names on markers.name = names._id_ WHERE markers.flags = 2", conn))
```

```shell
nvprof --profile-from-start on -f -o cuda.prof -- python test.py
python log.py

                                  value
0                           to, seq = 0
1                        empty, seq = 0
2            is_floating_point, seq = 0
3                           to, seq = 0
4                        empty, seq = 0
5            is_floating_point, seq = 0
6                           to, seq = 0
7                        empty, seq = 0
8                       matmul, seq = 0
9                           mm, seq = 0
10                         add, seq = 1
11                         sum, seq = 2
12  torch::autograd::GraphRoot, seq = 3
13                SumBackward0, seq = 2
14                      expand, seq = 0
15                AddBackward0, seq = 1
16      torch::autograd::AccumulateGrad
17                       clone, seq = 0
18                  MmBackward, seq = 0
19                           t, seq = 0
20                          mm, seq = 0
21      torch::autograd::AccumulateGrad
22                               detach
```

## Expected behavior

Correct output from pytorch v1.0.1:
```shell
                                        value
0                                   to, seq=0
1                                empty, seq=0
2                    is_floating_point, seq=0
3                                   to, seq=0
4                                empty, seq=0
5                    is_floating_point, seq=0
6                                   to, seq=0
7                                empty, seq=0
8                               matmul, seq=0
9                                   mm, seq=0
10                                 add, seq=1
11                                 sum, seq=2
12  torch::autograd::GraphRoot, stashed seq=3
13                SumBackward0, stashed seq=2
14                              expand, seq=0
15                AddBackward0, stashed seq=1
16            torch::autograd::AccumulateGrad
17                               clone, seq=0
18                  MmBackward, stashed seq=0
19                                   t, seq=0
20                                  mm, seq=0
21            torch::autograd::AccumulateGrad
```

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 418.87.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torchbench                0.0.25                   pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

**Comment by aaronenyeshi** [comment]
fwd-bwd correlation should be available in trace files now. Closing this old issue.
