### ISSUE TITLE
how can i make sure that when my pytorch code run in cpu can use avx2

### ISSUE THREAD

**Issue by zhujun5164** [pytorch/pytorch#34574]
## ❓ Questions and Help

environment: cpu  i7-9700
system: win10
python: 3.7
pytorch: 1.4

i use the cpu-z it ask me the i7-9700 cpu can use avx2. 
Does it means that when my pytorch code run in my cpu, it can use the avx2 automaticly?
And how can i make sure that

**Comment by peterjc123** [comment]
> Does it means that when my pytorch code run in my cpu, it can use the avx2 automaticly?

It will be used when avx2 is available on your cpu. 

> And how can i make sure that
Maybe we can add a new api for this. cc @ezyang

**Comment by ezyang** [comment]
Yeah, this seems reasonable. We could make `__config__` report what the detected avx level is as an easy test here.

**Comment by ezyang** [comment]
Reserving this task for a bootcamper

**Comment by zhujun5164** [comment]
thanks if have any result, please ask to me.

**Comment by great-way** [comment]
It seems we do have such functionality in the latest pytorch version. You can use torch.config.show() to print out the versions of libraries used by pytorch including whether you are using AVX, AVX2, or not. 

Code pointer: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Version.cpp#L168
Related pull request: https://github.com/pytorch/pytorch/pull/18579
