### ISSUE TITLE
Could not run 'quantized::conv2d' with arguments from the 'CPUTensorId' backend. 'quantized::conv2d' is only available for these backends: [QuantizedCPUTensorId].

### ISSUE THREAD

**Issue by guanxiang** [pytorch/pytorch#34583]
I follow the official document to quantize ERFNET，but some error happened ,when I eval the quantized model. The error is as below:

```
RuntimeError: Could not run 'quantized::conv2d' with arguments from the 'CPUTensorId' backend. 'quantized::conv2d' is only available for these backends: [QuantizedCPUTensorId].
The above operation failed in interpreter.
Traceback (most recent call last):
Serialized   File "code/__torch__/erfnet_q_backup.py", line 9
  def forward(self: __torch__.erfnet_q_backup.ERFNet,
    input: Tensor) -> Tensor:
    output = (self.encoder).forward(input, )
              ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (self.decoder).forward(output, )
class Encoder(Module):
Serialized   File "code/__torch__/erfnet_q_backup.py", line 19, in forward
  def forward(self: __torch__.erfnet_q_backup.Encoder,
    input: Tensor) -> Tensor:
    output = (self.initial_block).forward(input, )
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _0 = self.layers
    _1 = getattr(_0, "0")
Serialized   File "code/__torch__/erfnet_q_backup.py", line 56, in forward
    _14 = __torch__.torch.nn.functional.___torch_mangle_5.relu
    output = (self.conv).forward(input, )
    conv_output = __torch__.torch.nn.functional.relu(output, False, )
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    output12 = (self.pool).forward(input, )
    pool_output = _14(output12, False, )
Serialized   File "code/__torch__/erfnet_q_backup.py", line 55, in relu
    input: Tensor) -> Tensor:
    _14 = __torch__.torch.nn.functional.___torch_mangle_5.relu
    output = (self.conv).forward(input, )
              ~~~~~~~~~~~~~~~~~~ <--- HERE
    conv_output = __torch__.torch.nn.functional.relu(output, False, )
    output12 = (self.pool).forward(input, )
  File "/home/guanx/anaconda3/envs/py37_torch14/lib/python3.7/site-packages/torch/nn/quantized/modules/conv.py", line 213
        if len(input.shape) != 4:
            raise ValueError("Input shape must be `(N, C, H, W)`!")
        return ops.quantized.conv2d(
               ~~~~~~~~~~~~~~~~~~~~ <--- HERE
            input, self._packed_params, self.stride, self.padding,
            self.dilation, self.groups, self.scale, self.zero_point)
Serialized   File "code/__torch__/torch/nn/quantized/modules/conv.py", line 37, in forward
    _13 = [_11, _12]
    _14, _15, = _4
    _16 = ops.quantized.conv2d(input, _1, _10, _13, [_14, _15], _5, _6, _7)
          ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _16
  def __getstate__(self: __torch__.torch.nn.quantized.modules.conv.Conv2d) -> Tuple[int, int, Tuple[int, int], Tuple[int, int], Tuple[int, int], Tuple[int, int], bool, int, int, str, Tensor, Optional[Tensor], float, int, bool]:
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
this means you are feeding non-quantized Tensor to a quantized kernel. I think probably QuantStub is not placed correctly, could you post your model?

Also please use https://discuss.pytorch.org/c/quantization/17 for questions.

**Comment by guanxiang** [comment]
hi jerry
thanks for your replay. I do not add any QuantStub, DeQuantStub in the code, just convert model to quantized model

**Comment by z-a-f** [comment]
@guanxiang You need to make sure your inputs are quantized.

**Comment by supriyar** [comment]
please use https://discuss.pytorch.org/c/quantization/17 for questions. Closing this issue.

**Comment by misslibra** [comment]
> @guanxiang You need to make sure your inputs are quantized.
@jerryzh168 @z-a-f 

hi I have the same problem when I do  inference with a quantized model.
I try two methods,AND I got error:
`
  File "/home/cindy/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/quantization/stubs.py", line 14, in __init__
    if qconfig:
RuntimeError: bool value of Tensor with more than one value is ambiguous
` 
1:
`
images = QuantStub(images)
 outputs = model(images)`

2. in model:

`

    def forward(self, x):
        x = QuantStub(x)
        out = self.conv1(x)
        out = QuantStub(out)
        out = self.stack1(out)
        out = self.stack2(out)
        out = self.stack3(out)
        out = self.stack4(out)

        # out = F.avg_pool2d(out, 4)
        out = F.avg_pool2d(out, (12, 4))
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        out = DeQuantStub(out)

        return out
`

Please help me with how to quantize inputs, Thanks!

**Comment by misslibra** [comment]
I also try before put to model,but fail :
images = images.to(torch.float16)

**Comment by Aravindbolloju** [comment]
> hi jerry
> thanks for your replay. I do not add any QuantStub, DeQuantStub in the code, just convert model to quantized model

Hey Buddy,

Did you solved the issue

**Comment by nieyan** [comment]
@misslibra   Maybe you should add QuantStub like this :   https://discuss.pytorch.org/t/quantization-how-to-quantize-model-which-include-not-support-to-quantize-layer/76528

**Comment by gemfield** [comment]
When using static quantized model, you need to insert QuantStub and DeQuantStub at the beginning and end of the network.

**Comment by fucker007** [comment]
> I also try before put to model,but fail :
> images = images.to(torch.float16)

Hi， misslibra, I have a same problem , do u sovled it?  help

**Comment by mheriyanto** [comment]
> QuantStub and DeQuantStub

My issue is solved using this solution. Thanks @gemfield .

**Comment by Ak670676** [comment]
NotImplementedError: Could not run 'quantized::conv2d.new' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::conv2d.new' is only available for these backends: [QuantizedCPU, QuantizedCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].   i got thisissue

**Comment by jerryzh168** [comment]
please see: https://pytorch.org/docs/stable/quantization.html#passing-a-non-quantized-tensor-into-a-quantized-kernel

**Comment by lslsldjehg** [comment]
@Ak670676  Have you solved your problem? I have also encountered the same problem as you
