### ISSUE TITLE
Why apply kaiming_normal_ with mode='fan_out' to ResNet in torchvision.models

### ISSUE THREAD

**Issue by X-funbean** [pytorch/pytorch#34592]
Although the doc says:
> Choosing `'fan_in'`preserves the magnitude of the variance of the weights in the forward pass. 
> Choosing `'fan_out'` preserves the magnitudes in the backwards pass.
But I can't get it, and I haven't found many materials talking about how to choose between 'fan_in' and 'fan_out'.
What's the criterion of choosing the mode? When should 'fan_in' or 'fan_out' be chosen?  Anybody plz help me out.

**Comment by ngimel** [comment]
These sort of questions is better suited for the forums, discuss.pytorch.org

**Comment by X-funbean** [comment]
I found similar questions on discuss.pytorch.org, but it seems theres no satisfying answers, so I wish to find some answers here. Thanks a lot. @ngimel
