### ISSUE TITLE
RuntimeError: Could not run 'aten::thnn_conv2d_forward' with arguments from the 'QuantizedCPUTensorId' backend. 'aten::thnn_conv2d_forward' is only available for these backends: [CPUTensorId, VariableTensorId].

### ISSUE THREAD

**Issue by mk123qwe** [pytorch/pytorch#34613]
## 🐛 Bug

 - PyTorch Version (e.g., 1.0):1.4
 - OS (e.g., Linux):ubuntu16.04
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:10.1
 - GPU models and configuration:
 - Any other relevant information:

## Additional context
RuntimeError: Could not run 'aten::thnn_conv2d_forward' with arguments from the 'QuantizedCPUTensorId' backend. 'aten::thnn_conv2d_forward' is only available for these backends: [CPUTensorId, VariableTensorId].

code:(https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html)
myModel = MobileNetV2().to('cpu')
myModel.fuse_model()
myModel.qconfig = torch.quantization.default_qconfig
print(myModel.qconfig)
torch.quantization.prepare(myModel, inplace=True)
...

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
This means you are feeding a quantized Tensor to a non-quantized kernel, could you paste your code?

**Comment by jerryzh168** [comment]
Also please post questions in: https://discuss.pytorch.org/c/quantization/17

**Comment by zjjott** [comment]
important part: add `model.eval()` before quantization.

**Comment by aryan461** [comment]
I faced the same issue, when I run:
```python
model.eval()
model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
model.fuse_model()
model_backbone_prep = torch.quantization.prepare(model)
sample_input = torch.rand(1, 3, 224, 224, device='cpu')
model_backbone_prep(sample_input)
q_model = torch.quantization.convert(model_backbone_prep)
q_model(sample_input)
```

this is the error:
```
RuntimeError: Could not run 'aten::thnn_conv2d_forward' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::thnn_conv2d_forward' is only available for these backends: [CPU, CUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
```

`model` is a resnet101, set on CPU device.

PyTorch version 1.8
CUDA 11
python 3.8
OS: ubuntu 

Whst do you suggest?

**Comment by ImolaFodor** [comment]
@smivv Vladimir hi! i had the same, and by doing the fusion before selecting the schemes (fbgemm me) and no problem.. now i have the error to do aten::dequantize()..

**Comment by MingDongLi0088** [comment]
Hello @ImolaFodor 
Did you solve the problem?
`aten::dequantize()`

**Comment by jerryzh168** [comment]
@aryan461 sorry just saw this, can you print the model?

**Comment by jerryzh168** [comment]
please checkout: https://pytorch.org/docs/stable/quantization.html#passing-a-quantized-tensor-into-a-non-quantized-kernel
