### ISSUE TITLE
TestNN.test_cpu_vs_cudnn_no_dropout does not test MIOpen RNN on ROCm

### ISSUE THREAD

**Issue by ashishfarmer** [pytorch/pytorch#34615]
Running `PYTORCH_TEST_WITH_ROCM=1 python test_nn.py TestNN.test_rnn_cpu_vs_cudnn_no_dropout` does not run MIOpen path. 
This [line](https://github.com/pytorch/pytorch/blob/70f3298684538ee1b37fb61a2c8b858ad277c16d/test/test_nn.py#L5556) in test_nn.py sets data type of tensors for the test to `double`, which is not supported by MIOpen which is why during execution we fall back to HIP kernels rather than using MIOpen. The change came from PR #27628 where the default datatype of the test was changed from `float` to `double`. Can we get a little more clarity on this change or if there could be a way to run MIOpen RNN in the CI tests.

cc: @mruberry @ezyang @iotamudelta

**Comment by ashishfarmer** [comment]
Enforcing the `dtype` in `_test_RNN_cpu_vs_cudnn` to `float` ensured that the input and hx and cx tensors are `floats` however, it initialized weights tensor as `double` because of the global setting [here](https://github.com/pytorch/pytorch/blob/56832bf7f3ab44dd3472ac82e7acc471479441d6/test/test_nn.py#L27).

**Comment by ngimel** [comment]
You could probably cast the module to `dtype` to make sure it's `float`?

**Comment by ezyang** [comment]
Inability to specify dtype when allocating module parameters is a long standing wart in PyTorch's API. Natalia's suggestion is the most expedient. I couldn't find an issue about this, but maybe we should consider (1) expunging the use default data type in our tests (somehow) and (2) figuring out a way to let modules allocate at different dtype/device directly.

**Comment by ashishfarmer** [comment]
Resolved in #36772
