### ISSUE TITLE
Could you please add a torch setting like torch.set_checkpoint_enabled(True)

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#34643]
## 🚀 Feature
Hope you to add a torch setting like `torch.set_bp_cp_enabled(True)`, so that every `nn.module` in the code will conduct the backward in the checkpoint mode so as to minimize the GPU memory usage.

## Motivation
I'm always frustrated when the parameters number of a model is so large that I will be worried that I cannot train it on my own GPU server.  

## Pitch

When `torch.set_bp_cp_enabled(True)`, every `nn.module` in code will conduct the backward in the checkpoint mode so as to minimize the GPU memory usage.

## Alternatives

Or I think control the checkpoint scope in the module-level, like:
```python
memory_efficient=True
conv = nn.Conv2d(num_input_features, bn_size *growth_rate, kernel_size=1, stride=1,
                                           bias=False, checkpoint = memory_efficient)
relu = nn.ReLU(inplace = inplace, checkpoint = memory_efficient)
bn = nn.BatchNorm2d(num_input_features, checkpoint = memory_efficient)

```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ngimel** [comment]
Thank you for the suggestion. We would be willing to accept a PR enabling this feature

**Comment by albanD** [comment]
For the alternative method with a module-level flag. The thing is that checkpointing is only useful if you wrap multiple modules together. As the memory it saves is the intermediary results between module.
So this wouldn't be useful I think.

For the global context, how would you plan on doing this?

**Comment by songyuc** [comment]
Hi, @albanD ,
in fact, I think I misunderstand the function of checkpoint, so, I need to rethink my idea.
And there is one thing I realized, which is very important, that is,
I find that checkpoint can only be used to wrap the some operations together, 
like,
```python
class NetA(nn.Module):
    def __init__(self, use_checkpoint=False):
        super().__init__()
        self.use_checkpoint = use_checkpoint

        k = 2
        # 32x32
        self.layer1 = conv_bn_relu(3, 32*k, 3, 1, 1)
        self.layer2 = conv_bn_relu(32*k, 32*k, 3, 2, 1)
        # 16x16
        self.layer3 = conv_bn_relu(32*k, 64*k, 3, 1, 1)
        self.layer4 = conv_bn_relu(64*k, 64*k, 3, 2, 1)
        # 8x8
        self.layer5 = conv_bn_relu(64*k, 128*k, 3, 1, 1)
        self.layer6 = conv_bn_relu(128*k, 128*k, 3, 2, 1)
        # 4x4
        self.layer7 = conv_bn_relu(128*k, 256*k, 3, 1, 1)
        self.layer8 = conv_bn_relu(256*k, 256*k, 3, 2, 1)
        # 1x1
        self.layer9 = nn.Linear(256*k, 10)

    def seg0(self, y):
        y = self.layer1(y)
        return y

    def seg1(self, y):
        y = self.layer2(y)
        y = self.layer3(y)
        return y

    def seg2(self, y):
        y = self.layer4(y)
        y = self.layer5(y)
        return y

    def seg3(self, y):
        y = self.layer6(y)
        y = self.layer7(y)
        return y

    def seg4(self, y):
        y = self.layer8(y)
        y = F.adaptive_avg_pool2d(y, 1)
        y = torch.flatten(y, 1)
        y = self.layer9(y)
        return y

    def forward(self, x):
        y = x
        # y = self.layer1(y)
        y = y + torch.zeros(1, dtype=y.dtype, device=y.device, requires_grad=True)
        if self.use_checkpoint:
            # 使用 checkpoint
            y = checkpoint(self.seg0, y)
            y = checkpoint(self.seg1, y)
            y = checkpoint(self.seg2, y)
            y = checkpoint(self.seg3, y)
            y = checkpoint(self.seg4, y)
        else:
            # 不使用 checkpoint
            y = self.seg0(y)
            y = self.seg1(y)
            y = self.seg2(y)
            y = self.seg3(y)
            y = self.seg4(y)
```

But,  maybe it cannot directly have influence on forward function, like,
```python
x = img_batch
mask_batch = cp.checkpoint(self.model, x)
y = torch.sum(mask_batch)
y.backward()
```
Here is my understanding, am I right?
 
As a result, I think **`checkpoint` have a very similar feature like  Decorator in Python**, and an similar example is `@torch.no_grad()`.
So, `@torch.checkpoint()` might be a good alternative for `forward()` function.

**Comment by albanD** [comment]
Hi,

You can apply it to any object that you can `__call__` in python (functions or nn.Module invocation for example)
If you want to make sure a function is always called as checkpoint, I guess you can wrap it with:
```python
def with_checkpoint(fn):
  def tmp(*args, **kwargs):
    return torch.checkpoint(fn, *args, **kwargs)
  return tmp

@with_checkpoint
def your_fn():
  pass
```

**Comment by albanD** [comment]
Closing this for now as it is unclear if we can provide such API.
Feel free to re-open if you have more ideas.
