### ISSUE TITLE
Usage block in `__mul__` for Variables

### ISSUE THREAD

**Issue by okcd00** [pytorch/pytorch#3464]
I want to make an element-wise `mul` operation for `Variable` and a mask matrix,
but the usage for this might be blocked, I guess.
Here's an example for detail:

```
import torch
import numpy as np
from torch.autograd import Variable

x = np.ones((2,3))
f = torch.FloatTensor(x)
t = Variable(torch.ones((2,3)))
t2 = Variable(f) 
```

when I try `t.mul(x)` , it shows types I can select from is `float` and `torch.FloatTensor`:
```
TypeError: mul received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
 * (torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (numpy.ndarray)
```

So, I tried `t.mul(f)`:
```
/usr/local/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.pyc in mul(self, other)
    339             return Mul.apply(self, other)
    340         else:
--> 341             assert not torch.is_tensor(other)
    342             return MulConstant.apply(self, other)
    343 

AssertionError: 
```

Only when we use `Variable` as `other` (`t.mul(t2)`) it works,
(so does the function `masked_scatter_`, maybe.)

Does it mean 'if `other` is a tensor, raise AssertError' ?
If so, how can I use `mul` operation for the `Variable`?

**Comment by zou3519** [comment]
As the second error message suggests, you can only multiply a Variable with an equivalent python number type (float in this case) or another Variable.

The first error message looks a little funky and could be a bug. I tried it out on master and it looks like this:
![image](https://user-images.githubusercontent.com/5652049/32379123-0c25714e-c083-11e7-8c48-11e97e7f010b.png)
so it is consistent with the second error message.
