### ISSUE TITLE
DISABLED test_keypoint_rcnn (__main__.TestONNXRuntime_opset11)

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#34658]
## 🐛 Bug

https://app.circleci.com/pipelines/github/pytorch/pytorch/138566/workflows/850299ec-3258-4e78-b680-cfad253c746a/jobs/4782754/parallel-runs/0/steps/0-105

```
Mar 12 17:35:27 =================================== FAILURES ===================================
Mar 12 17:35:27 __________________ TestONNXRuntime_opset11.test_keypoint_rcnn __________________
Mar 12 17:35:27 
Mar 12 17:35:27 self = <test_pytorch_onnx_onnxruntime.TestONNXRuntime_opset11 testMethod=test_keypoint_rcnn>
Mar 12 17:35:27 
Mar 12 17:35:27     def wrapper(self):
Mar 12 17:35:27         if self.opset_version < min_opset_version:
Mar 12 17:35:27             raise unittest.SkipTest("Skip verify test for unsupported opset_version")
Mar 12 17:35:27 >       return func(self)
Mar 12 17:35:27 
Mar 12 17:35:27 test/onnx/test_pytorch_common.py:54: 
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
Thanks Elias. About the WIP PR you have for interpolate to optimize the executed ops, can you tell me in what stage is the PR? I'm trying to see if can look into this PR more.

**Comment by eellison** [comment]
It's mostly getting the size & shape info of the input tensor, and then figuring out ways to constant prop that through. It has a few dependencies so probably a week or two out from being landed.

**Comment by ezyang** [comment]
The disable is not working. https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4801840/output/105/0?file=true&allocation-id=5e6ba83115bd6173c2cd319b-0-build%2F1F1A2E8E

**Comment by spandantiwari** [comment]
@eellison - are there are any other ONNX tests besides this one that is being disabled because of your interpolate PR?

**Comment by eellison** [comment]
The interpolate scripting one. let's centralize conversation on  https://github.com/pytorch/pytorch/issues/34718 if that works for you.

**Comment by spandantiwari** [comment]
@eellison - do you think we can close this issue?

**Comment by eellison** [comment]
Yea, this works now.
