### ISSUE TITLE
[jit] pow of 2 `int`s returns a `float`

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#34672]
```python
def fn():
    return 2 ** 3

print(type(fn()))  # int
print(type(torch.jit.script(fn)()))  # float
```

cc @suo

**Comment by eellison** [comment]
This is expected behavior. 2 ** -2 returns a float. We could return ScalarType but thought it’d be a worse ux.

**Comment by eellison** [comment]
Discussion is [here](https://github.com/pytorch/pytorch/pull/26926#discussion_r328839368) for context. I'm going to close, reopen if you think there is something else to discuss.
