### ISSUE TITLE
Broken Hinting for PyCharm, torch 1.4.0

### ISSUE THREAD

**Issue by tjysdsg** [pytorch/pytorch#34699]
## 🐛 Bug

Broken hinting in IDEs like PyCharm

Similar issue to #7318, but for version 1.4.0

## To Reproduce

- `torch.cuda.manual_seed` cannot find `manual_seed`
- `torch.cuda.manual_seed_all` cannot find `manual_seed_all`
- `torch.utils` cannot find `utils`
- `torch.backends` cannot find `backends`
- `torch.optim.lr_scheduler._LRScheduler.step()` argument `epoch` unfilled, while it's optional
- `torch.Tensor(4, 1)` unexpected arguments & argument `requires_grad` unfilled
- `torch.optim.Adadelta` cannot find `Adadelta`
- `torch.nn.TransformerEncoderLayer` cannot find `TransformerEncoderLayer`
- `torch.nn.TransformerEncoder` cannot find `TransformerEncoder`

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Arch Linux
GCC version: (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130
CMake version: version 3.16.5

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 440.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0a0
[conda] _pytorch_select           0.1                       cpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] mkl                       2019.0                   pypi_0    pypi
[conda] mkl-fft                   1.0.6                    pypi_0    pypi
[conda] mkl-random                1.0.1.1                  pypi_0    pypi
[conda] mkl-service               2.3.0            py36he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py36ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py36hd6b4f25_0    defaults
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi
```

cc @ezyang

**Comment by agolynski** [comment]
CC @ezyang @zou3519 who already helped with 
https://github.com/pytorch/pytorch/issues/7318
Also a related issue here:
https://github.com/pytorch/pytorch/issues/16996

Not sure if we have a category for such issues.

**Comment by ezyang** [comment]
We're not going to backport type hinting fixes to 1.4.0, sorry.

**Comment by EMCP** [comment]
I am seeing the same issue in v1.5.x .. anyone know where I can track the progress of that fix ?

**Comment by ezyang** [comment]
@EMCP can you file a new issue about new problems?

**Comment by ParnaChowdhury** [comment]
where can i track progress for this issue?

**Comment by ezyang** [comment]
@ParnaChowdhury if you are on 1.9 and there are still broken type hints please file a new issue describing the problem
