### ISSUE TITLE
Beta Distribution values wrong for a=b---> 0 (again)

### ISSUE THREAD

**Issue by kulalexey** [pytorch/pytorch#34717]
In pytorch 1.4.0 we have same problem as in https://github.com/pytorch/pytorch/issues/15738 with same way to reproduce

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by agolynski** [comment]
also CC @cpuhrsch

**Comment by alicanb** [comment]
I'm going to reopen #15738 and close this one. Let's continue to discuss it there.
