### ISSUE TITLE
Wrong Result when Converting Odd Integers Larger than 2^24 to Tensor

### ISSUE THREAD

**Issue by melissa135** [pytorch/pytorch#34758]
## 🐛 Bug

The torch.Tensor(), also named torch.FloatTensor(), returns wrong result when converts odd integers larger than 2^24. The value of returned tensor is not the original integer, but a number of it +1 or -1.

It's quite strange. Although the bug can be resolve by explicitly using torch.IntTensor(), I wonder the reason that caused the bug.

## To Reproduce

1. It is correct when number < 2^24
```
>>> 2**24
16777216
>>> t = torch.Tensor([16777215])
>>> t
tensor([16777215.])
>>> t = torch.Tensor([16777216])
>>> t
tensor([16777216.])
```

2. Gets wrong for the odd number > 2^24, while even number is correct.
```
>>> t = torch.Tensor([16777217])
>>> t
tensor([16777216.])
>>> t = torch.Tensor([16777218])
>>> t
tensor([16777218.])
>>> t = torch.Tensor([16777219])
>>> t
tensor([16777220.])
>>> t = torch.Tensor([16777220])
>>> t
tensor([16777220.])
```

3. IntTensor() vs FloatTensor()
```
>>> t = torch.IntTensor([16777219])
>>> t
tensor([16777219], dtype=torch.int32)
>>> t = torch.FloatTensor([16777219])
>>> t
tensor([16777220.])
```

## Environment

 - PyTorch Version: 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04 64bit
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.9

**Comment by ptrblck** [comment]
This is expected, as it's a float32 limitation.
From the [Wikipedia article](https://en.wikipedia.org/wiki/Single-precision_floating-point_format):
> Integers between 0 and 16777216 can be exactly represented (also applies for negative integers between −16777216 and 0)
Integers between `2**24=16777216` and `2**25=33554432` round to a multiple of 2 (even number)
Integers between `2**25` and `2**26` round to a multiple of 4
...
