### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by zyzhang1130** [pytorch/pytorch#34766]
Hi, I'm not sure how to solve this issue, but I think it might be possible:

when I did this:
X = torch.cuda.FloatTensor(X)

for using gpu to training my network, it throw me this error:
RuntimeError: CUDA error: out of memory

I understand that it is probably because X is too large (it is indeed), however I do have 4 GTX 1080 at hand, and I'm thinking of making use of all gpus to store X. The existing multi GPU related tutorials are mostly on modules rather than data itself, so I'm still unclear what I'm supposed to do.

**Comment by ptrblck** [comment]
You could split the data and push each chunk onto a specific device via: `x0 = x0.to('cuda:0')` etc.
However, note that operations on tensors have to be applied on the same device and you would have to use some workarounds as e.g. described [here](https://discuss.pytorch.org/t/matmul-on-multiple-gpus/33122/2?u=ptrblck).

**Comment by zyzhang1130** [comment]
I did something like this:

for epoch in range(epoch):
    perm = torch.randperm(N)  # Generate a set of random numbers of length: sample size
    sum_loss = 0  # Loss for each epoch
        
    for i in range(0, N, batch_size):
        x = X[perm[i:i + batch_size]]  # Pick random samples by iterating over random permutation
        y = Y[perm[i:i + batch_size]]  # Pick the correlating class
        
        x = torch.cuda.FloatTensor(x)  # Convert X and Y to FloatTensors
        # y = torch.from_numpy(np.array(y))
        # y = torch.cuda.FloatTensor(y)
        
        x = Variable(x)  # Convert features and classes to variables
        y = Variable(y)

        optimizer.zero_grad()  # Manually zero the gradient buffers of the optimizer
        output = model(x)  # Compute the output by doing a forward pass
        
        loss = torch.mean(torch.clamp(1 - output * y, min=0))  # hinge loss
        loss.backward()  # Backpropagation
        optimizer.step()  # Optimize and adjust weights

        sum_loss += loss.item()  # Add the loss
        
    print("Epoch {}, Loss: {}".format(epoch, sum_loss))


So I just loaded the batch data to gpu right before training  on one single GPU. In other words the GPU only loads a small piece of data at a time. It could run without error. However the loss is very very high. Not sure if it has anything to do with the method I used.

**Comment by ptrblck** [comment]
Could you create a topic in our [discussion board](https://discuss.pytorch.org/) please, so that we can continue the discussion there or do you think there is still a bug/issue in the code?
The code looks alright (besides the usage of `Variable`, which is deprecated since PyTorch `0.4.0`).

**Comment by zyzhang1130** [comment]
sure.  Thanks for the reply anyways
