### ISSUE TITLE
Where can I find how torch computes gradients for the basic mathematic operators,  like round, mode, clamp

### ISSUE THREAD

**Issue by jia2lin3yuan1** [pytorch/pytorch#34771]
##  Where can I find how torch computes gradients for the basic mathematic operators,  like round, mode, clamp.

 I know the mathematic gradients equation, but I am not sure how it is computed in torch, especially how torch computes the sub-gradients. It would be great if there is a document to introduce this.

Thank you for the help!

**Comment by colesbury** [comment]
See https://github.com/pytorch/pytorch/blob/master/tools/autograd/derivatives.yaml

That file is used to generate torch/csrc/autograd/generated/Functions.cpp during the build process. Here is an example of the generated output from a recent version of PyTorch:

https://gist.github.com/colesbury/0620ea5bbba1d073002c7ed9612c9e91
