### ISSUE TITLE
Build PyTorch from source...

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#34789]
Sorry for my naive questions...

1. I tried to build **PyTorch** using **CMAKE**, and it seems except **caffe2**, there is **NO python package of PyTorch** has been generated.

2. Just wonder what's the **difference between**
- cmake build
- `python setup.py build`

3. How to configure those **MACROS** before running `python setup.py build` ?
Please refer to my current **DIRECT build** with the following configuration at:
[https://pastebin.com/CcpPBPt7](https://pastebin.com/CcpPBPt7)

**Comment by colesbury** [comment]
Use `python setup.py install` to build the Python package. It will use cmake under the hood, but you should not call cmake directly; that's not a supported way to build the Python package

These environment variables control the build:
https://github.com/pytorch/pytorch/blob/d927d58c2a72e46e84d03bcd4fa01118e7b9f4b3/setup.py#L28-L115
