### ISSUE TITLE
torch.stft does not accept complex input

### ISSUE THREAD

**Issue by Rikorose** [pytorch/pytorch#34797]
## 🐛 Bug

torch.stft fails with the error message `expected a 1D or 2D tensor of floating types` if complex input is provided (i.e. last dim = 2 for real and imaginary part).

## To Reproduce

```py
batch=5
time=100
n_fft=16
hop=8
input=torch.rand((batch, time, 2))
torch.stft(input, n_fft=n_nfft, hop_length=hop)
```

## Expected behavior

It should run the fft on the complex valued input

cc @ezyang @anjali411 @dylanbespalko

**Comment by HopefulRational** [comment]
Hi @Rikorose. Actually work is still going on for all this. For example, check this : 
https://github.com/pytorch/pytorch/issues/33152#issuecomment-599735453
hope this helps.

**Comment by Rikorose** [comment]
There is already `torch.fft` that supports complex input via separate real and imaginary part in the last dimension.

The problem lies within the stft implementation ([here](https://github.com/pytorch/pytorch/blob/40265e2/aten/src/ATen/native/SpectralOps.cpp#L196), and [here](https://github.com/pytorch/pytorch/blob/40265e2/aten/src/ATen/native/SpectralOps.cpp#L252)).

An option would be to additionally check the last dimension shape, or add a parameter that allows to specify that there is complex valued input.

**Comment by HopefulRational** [comment]
hi @Rikorose . ok... I am actually new but wanted to contribute... sorry i didn't do my homework...

**Comment by VitalyFedyunin** [comment]
We will gladly accept PR implementing Complex support.
