### ISSUE TITLE
Does pytorch support complex neural network trainning?

### ISSUE THREAD

**Issue by CholoeMoretz** [pytorch/pytorch#34801]
I am working on some radar datasets,which actually includes the phase of the electromagnetic wave that described with complex numbers.
The job is to classify them into different object classes,whichi definitely will use complex number as part of traininng.
Does pytorch support the comlex number neural network  trainning? Or Is ther any package that supports the complex number neural nertwork training?

**Comment by gchanan** [comment]
CC @anjali411.

Not yet, although it is planned, see https://github.com/pytorch/pytorch/issues/33152.

If you have further questions, do you mind asking on the forums (https://discuss.pytorch.org/)? We try to limit github issues to bugs / feature requests, etc.
