### ISSUE TITLE
Support arbitrary types in jit

### ISSUE THREAD

**Issue by NeilGirdhar** [pytorch/pytorch#34852]
It would be really nice and elegant to be able to pass objects of arbitrary types to a jitted function.  Currently, it seems that you have to manually deconstruct the object before the call and reconstruct it after the call.

I think the easiest most complete implementation would be to simply copy `jax.register_pytree_node` (https://jax.readthedocs.io/en/latest/notebooks/JAX_pytrees.html).  Essentially, if we can tell pytorch how to decompose (and reconstruct) an object of a particular type into (and from) more fundamental objects, then pytorch would be able to accept these as arguments to jitted functions.

As for the inelegance of the `register_pytree_node` interface, consider that you can build an abstract base class that exposes the decontruction and reconstruction methods and calls register in `__init_subclass__` . This would make using such classes in pytorch jitted functions as easy as inheriting from a base class and writing the two methods.

cc @suo

**Comment by driazati** [comment]
We have support for [classes in TorchScript](https://pytorch.org/docs/master/jit_language_reference.html#id2), is there something in particular that's missing that you're looking for? `NamedTuple`s are also supported. We also have other things like `enum.Enum` and `@dataclass` on our roadmap but no concrete timeline yet. We're also introducing a way to [bind C++ classes into TorchScript](https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html) in our next release.

**Comment by NeilGirdhar** [comment]
Got it, that makes sense.
