### ISSUE TITLE
load_state_dict_from_url error with weights downloaded from Google Drive ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/pytorch#34850]
## 🐛 Bug
It gives me an error when i pass a sharable link to `.pth` weights on google drive to the `load_state_dict_from_url` function

## To Reproduce
`torch.hub.load_state_dict_from_url("https://drive.google.com/open?id=1P_ZYUWuUjt2DAUtPxG882mdQX95TIX3D")`

## Expected behavior

to return the state_dict

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.3.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.5.1
[pip3] numpy==1.17.1
[pip3] torch==1.3.0
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.4.1
[conda] Could not collect

**Comment by colesbury** [comment]
That URL is not a PyTorch file (.pth). It's a webpage with a link to a PyTorch file.

You need a direct download URL. Google drive doesn't support that directly, but you can use  something like https://sites.google.com/site/gdocs2direct/
