### ISSUE TITLE
Pytorch 1.4 backward error

### ISSUE THREAD

**Issue by as754770178** [pytorch/pytorch#34857]
```
    loss.backward()
  File "/usr/local/python14/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/python14/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: The size of tensor a (0) must match the size of tensor b (11) at non-singleton dimension 2
```

The loss is `tensor(17.5398, device='cuda:0', grad_fn=<PermuteBackward>)`.
In torch1.2, the program can run. In torch1.4 report error.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by mrshenli** [comment]
Hey @as754770178, could you please add a repro for this error?

**Comment by mli0620** [comment]
@as754770178 Hi, have you solved the problem?

**Comment by albanD** [comment]
Closing this for now as we have no info to repro.
Feel free to re-open if you have a code sample to reproduce the problem on the latest version!
