### ISSUE TITLE
[C++ API] Support for CIFAR10 and CIFAR100 Datasets

### ISSUE THREAD

**Issue by prabhuomkar** [pytorch/pytorch#34862]
## 🚀 Feature
C++ API should support Famous Open Datasets CIFAR10 and CIFAR100.
**Dataset Reference**: [https://www.cs.toronto.edu/~kriz/cifar.html](https://www.cs.toronto.edu/~kriz/cifar.html)

## Motivation
While creating PyTorch C++ tutorials [https://github.com/prabhuomkar/pytorch-cpp](https://github.com/prabhuomkar/pytorch-cpp), I came to know that PyTorch has support for these datasets via [vision](https://github.com/pytorch/vision/tree/master/torchvision/datasets). As of now, [C++ API for Datasets](https://github.com/pytorch/pytorch/tree/master/torch/csrc/api/src/data/datasets) only has MNIST.
Support for standard datasets like CIFAR, COCO, ImageNet, etc out of the box will help developers play with C++ API easily.

## Pitch
- Add [cifar.h](https://github.com/pytorch/pytorch/tree/master/torch/csrc/api/include/torch/data/datasets) header with _`TORCH_API`_ `CIFAR` class.
- Add [cifar.cpp](https://github.com/pytorch/pytorch/tree/master/torch/csrc/api/src/data/datasets) with both `CIFAR10` and `CIFAR100` support similar to vision for reading images, targets and getting train/test data. 

## Alternatives
N/A

## Additional context
Reference C++ Implementation: [cifar10.h](https://github.com/prabhuomkar/pytorch-cpp/blob/master/tutorials/intermediate/deep_residual_network/include/cifar10.h) and [cifar10.cpp](https://github.com/prabhuomkar/pytorch-cpp/blob/master/tutorials/intermediate/deep_residual_network/src/cifar10.cpp)
Reference Python Implementation: [cifar.py](https://github.com/pytorch/vision/blob/master/torchvision/datasets/cifar.py)

cc @yf225 @fmassa

**Comment by prabhuomkar** [comment]
cc @yf225 @soumith @apaszke

**Comment by yf225** [comment]
@prabhuomkar Thanks a lot for the suggestions! My personal take is that we should put the C++ vision datasets in https://github.com/pytorch/vision, same as the Python ones. @fmassa Curious what are your thoughts on this?

**Comment by prabhuomkar** [comment]
@fmassa would like to know your thoughts on this before closing this.

**Comment by soumyadipghosh** [comment]
@prabhuomkar Did you finally implement support for CIFAR-10/ImageNet in C++ in torchvision?

**Comment by prabhuomkar** [comment]
@soumyadipghosh  
Not yet, but I have a reference CIFAR implementation: 
https://github.com/prabhuomkar/pytorch-cpp/blob/31d325e34c0d3d3578dd5e811a2b459a78dcc32f/tutorials/popular/blitz/training_a_classifier/include/cifar10.h
https://github.com/prabhuomkar/pytorch-cpp/blob/31d325e34c0d3d3578dd5e811a2b459a78dcc32f/tutorials/popular/blitz/training_a_classifier/src/cifar10.cpp

**Comment by soumyadipghosh** [comment]
@prabhuomkar Thats great! Are you aware of anything similar for ImageNet?

**Comment by prabhuomkar** [comment]
Not yet, will try to add one by this weekend as an example

**Comment by soumyadipghosh** [comment]
That would be nice!

**Comment by prabhuomkar** [comment]
@soumyadipghosh use this https://github.com/prabhuomkar/pytorch-cpp/issues/73 to track?

**Comment by soumyadipghosh** [comment]
Ok
