### ISSUE TITLE
Creating a C extension API for PyTorch

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#3486]
This issues tracks the ability to be able to write Python C extension libraries that can interact with PyTorch tensors. We currently do not provide a good way to do this.

- [ ] We should install header files with functions from `DynamicTypes.h` that can convert PyObject * into at::Tensor objects and also make the aten headers available. Like other libraries we can provide a function like `torch.include_directory()` that lets builds know where they can find these headers in the current install. For ATen this directory should be `$PREFIX/include/`, but for PyTorch's headers, it can be wherever.
- [ ] We should document how to build C extensions that use PyTorch and ensure that a user's favored way of building them works. For instance, a pybind11 module should be usable.
- [ ] We should also consider more user-friendly ways of getting access to C-land such as providing Cython support and possibly just helping to compile C++ code at runtime for quick experiments.

@prigoyal this should make building PyTorch extensions a lot less hacky.

**Comment by soumith** [comment]
yes it does

**Comment by mattkanwisher** [comment]
```python
from torch.utils import cpp_extension

# Define include and library directories for PyTorch
torch_include_dirs = torch.utils.cpp_extension.include_paths()
torch_library_dirs = torch.utils.cpp_extension.library_paths()

```
for anyone else that bumps into this
