### ISSUE TITLE
why the bias is float in quantization model

### ISSUE THREAD

**Issue by linchaozhang** [pytorch/pytorch#34872]
I've found the bias in quantization model is float after convert.

i think the bias should be int32 for inference in paper

and how can i extract the params in quantization model?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by mrshenli** [comment]
@linchaozhang could you please the [forum](https://discuss.pytorch.org/c/quantization/17) for questions? Closing this issue now. Feel free to create another issue if this becomes a concrete feature request.
