### ISSUE TITLE
Could please add a member function like "nn.Module.get_out_channels()"

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#34877]
## 🚀 Feature
I want a member function like "nn.Module.get_out_channels()".

## Motivation
It will be more convenient as I can write the code as:
```python
self.inplanes = 64
self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3,
                               bias=False)
self.bn1 = norm_layer(self.conv1.get_out_channels())
self.relu = nn.ReLU(inplace=True)
```

Thanks in advance!

**Comment by Evpok** [comment]
I don't think that would be practical, since the output of a module can be anything and in particular, if it is a tensor there is in general no guarantee that the dimensions are constant.
Maybe something can be done with type hints for layers that do have a static output shape?

**Comment by mrshenli** [comment]
@songyuc 

If you are only looking for this API in conv layers, I think it is already there. You can get the out channels by calling `conv1.out_channels`.

For general `nn.Module`, I agree with @Evpok's comments. Not all modules have a channel dimension.

**Comment by songyuc** [comment]
I get it, and thanks sincerely for your answer, @Evpok and @mrshenli.
