### ISSUE TITLE
max / min doesn't work on tensors with 0 elements

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#34907]
## 🐛 Bug

Current `min` / `max` implementation is too restrictive wrt tensors with zero elements.
Indeed, min/max reduction over an empty dimension should raise an error, as they don't have an identity, but if the dimension being reduced is not of size 0 (but the tensor has 0 elements), then it should work.

## To Reproduce

```python
a = torch.rand(0, 4)
print(a.max(1))
```
raises
```
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```
while
```python
a = torch.rand(0, 4)
print(a.numpy().max(1))
```
returns
```
array([], dtype=float32)
```

---
PyTorch version `1.5.0.dev20200225`

cc @ezyang @gchanan @zou3519 @mruberry @rgommers @heitorschueroff

**Comment by gchanan** [comment]
CC @mruberry

**Comment by ngimel** [comment]
Bumping priority based on user activity, we should review if #38238 fixes it.

**Comment by rgommers** [comment]
Agreed that this should work. gh-38238 does look like it's going in the right direction but seems to have stalled. That PR followed up on gh-35062, which also stalled.

Some shape checks are still missing in that PR, e.g. the PyTorch equivalents of:
```
In [10]: x = np.ones((0, 3, 4))                                              

In [11]: np.max(x, axis=1)                                                   
Out[11]: array([], shape=(0, 4), dtype=float64)

In [12]: np.max(x, axis=2)                                                   
Out[12]: array([], shape=(0, 3), dtype=float64)
```
to make sure the fix doesn't unconditionally return a shape `(0,)` sized tensor.

@willwray this seems like a good issue to work on and get it over the finish line.

**Comment by v0dro** [comment]
Do we need to support the `kthvalue` function with 0 dim tensors? CC @ngimel

**Comment by v0dro** [comment]
One more question about `mode`. The function currently supports zero-dim tensors, but the output is not like the other methods where the dimension being reduced is the only one that is removed from the result. Instead, it returns a tensor of dimensions `[0]`. Should this be changed to make it similar to say reduction of min/max in numpy as pointed by @rgommers in https://github.com/pytorch/pytorch/issues/34907#issuecomment-679188146?

FYI, `scipy.stats` also returns the same dimensions if specifying a 0-dim numpy array:

**Comment by rgommers** [comment]
> Do we need to support the `kthvalue` function with 0 dim tensors?

I'd say yes, nice for consistency. It's a similar reduction, where an input of shape `(n, m)` gives an output of shape `(n,)` for `dim=1`. However, I don't see how it's related to this issue easily, some more context to the question would have been useful. 

If you need to solve it to land the PR for `min`/`max` then do so I'd say, other fine to do as a follow-up - whatever is easier.

> One more question about `mode`. The function currently supports zero-dim tensors, but the output is not like the other methods where the dimension being reduced is the only one that is removed from the result. Instead, it returns a tensor of dimensions `[0]`. Should this be changed to make it similar to say reduction of min/max in numpy as pointed by @rgommers in [#34907 (comment)](https://github.com/pytorch/pytorch/issues/34907#issuecomment-679188146)?

I don't see any inconsistency here. Note that a _zero-dimensional_ tensor is different from a tensor with an _empty dimension_. Comparing `max`, `min` and `mode`, it looks the same to me:
```
>>> a_zerodim = torch.tensor(3)                                                                    
>>> torch.max(a_zerodim)                                                                           
tensor(3)
>>> torch.min(a_zerodim)                                                                           
tensor(3)
>>> torch.mode(a_zerodim)                                                                          
torch.return_types.mode(
values=tensor(3),
indices=tensor(0))
>>>                                                                                                
>>> a0 = torch.rand(0, 4)                                                                          
>>> torch.max(a0, dim=1)                                                                           
Traceback (most recent call last):
  File "<ipython-input-107-c4f5d9f5c635>", line 1, in <module>
    torch.max(a0, dim=1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

>>> torch.mode(a0, dim=1)                                                                          
Traceback (most recent call last):
  File "<ipython-input-108-754d784a9aa1>", line 1, in <module>
    torch.mode(a0, dim=1)
RuntimeError: cannot perform reduction function mode on tensor with no elements because the operation does not have an identity
```

Either way, my comment you referenced applies to `mode` as well.

> FYI, `scipy.stats` also returns the same dimensions if specifying a 0-dim numpy array:

The SciPy behavior is wrong here, and there's an open issue about it: https://github.com/scipy/scipy/issues/9955#issuecomment-474166442. Please ignore that, `mode` should work like other reductions.
