### ISSUE TITLE
Deadlock when using lstm with multiprocessing on CentOS

### ISSUE THREAD

**Issue by Desperado000** [pytorch/pytorch#3490]
I was just writing a rnn with multiprocessing for some test, and the input and output dimension are 2000 and 64 respectively, it works fine on Win10 and MacOS, but when I migrated this network to CentOS, this network was deadlock and when I changed the output dimension to 10 or lower, it could run again. I was wondering if anyone has the same issue like this? Thanks~

**Comment by SsnL** [comment]
Interesting, is the deadlock happening in dataloader or training? Could you share a small script that can reproduce the issue? Thank you :)

**Comment by Desperado000** [comment]
It solved by setting multiprocessing with mp.set_start_method('forkserver') or mp.set_start_method('spawn')...
