### ISSUE TITLE
Cannot use setup.py install 

### ISSUE THREAD

**Issue by chiehpower** [pytorch/pytorch#34947]
## 🐛 Bug
Hi all, 
I already have torch and there is no issue if I import torch.
However, if I import `caffe2.python` Then I will get this error message. 
```
>>> import caffe2.python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chieh/github/pytorch/caffe2/python/__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
  File "/home/chieh/github/pytorch/caffe2/proto/__init__.py", line 11, in <module>
    from caffe2.proto import caffe2_pb2, metanet_pb2, torch_pb2
ImportError: cannot import name 'caffe2_pb2'
```
So I am going to install pytorch repo from stratch. 
However, when I use this command...
```
python3 setup.py install      
```
Then I get these error messages below.
```
$ sudo python3 setup.py install      
Building wheel torch-1.4.0a0+4983ef8
-- Building version 1.4.0a0+4983ef8
cmake --build . --target install --config Release -- -j 8
[  1%] Built target nccl_external
[  1%] Built target pthreadpool
[  1%] Built target clog
[  1%] Built target gtest
[  2%] Built target benchmark
[  2%] Built target libprotobuf-lite
[  3%] Built target asmjit
[  4%] Built target fbgemm_avx512
[  4%] Built target fbgemm_avx2
[  5%] Built target gloo
[  5%] Built target fbgemm_generic
[  7%] Built target libprotobuf
[  8%] Built target c10
[  8%] Built target foxi_loader
[  8%] Built target ATEN_CPU_FILES_GEN_TARGET
[  8%] Built target common
[ 26%] Built target python_copy_files
[ 26%] Built target mkrename
[ 26%] Built target mkdisp
[ 26%] Built target mkalias
make[2]: *** No rule to make target '/usr/local/cuda-10.2/lib64/stubs/libcuda.so', needed by 'lib/libcaffe2_nvrtc.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 26%] Built target ATEN_CUDA_FILES_GEN_TARGET
[ 26%] Building CXX object caffe2/CMakeFiles/caffe2_nvrtc.dir/__/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.cpp.o
[ 26%] Built target mkmasked_gnuabi
[ 26%] Built target mkrename_gnuabi
[ 26%] Built target arraymap
In file included from /home/chieh/github/pytorch/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.h:3:0,
                 from /home/chieh/github/pytorch/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.cpp:1:
/home/chieh/github/pytorch/aten/src/ATen/cuda/ATenCUDAGeneral.h:3:10: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
[ 26%] Built target torch_python_stubs
caffe2/CMakeFiles/caffe2_nvrtc.dir/build.make:62: recipe for target 'caffe2/CMakeFiles/caffe2_nvrtc.dir/__/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_nvrtc.dir/__/aten/src/ATen/cuda/nvrtc_stub/ATenNVRTC.cpp.o] Error 1
CMakeFiles/Makefile2:7924: recipe for target 'caffe2/CMakeFiles/caffe2_nvrtc.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_nvrtc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 27%] Built target generate-torch-sources
[ 30%] Built target mkldnn
[ 31%] Built target cpuinfo_internals
[ 31%] Built target cpuinfo
[ 31%] Built target nnpack_reference_layers
[ 34%] Built target libprotoc
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/chieh/github/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/chieh/github/pytorch/tools/setup_helpers/cmake.py", line 339, in build
```
It said that ` fatal error: cuda.h: No such file or directory #include <cuda.h>```
I have exported my cuda library and I confirmed I have this file in my cuda folder.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64
export CUDA_INSTALL_DIR=/usr/local/cuda-10.0
export PATH=$PATH:/usr/local/cuda-10.0/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-10.0
export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```
How can I solve this problem?

## To Reproduce

git clone https://github.com/pytorch/pytorch.git && cd pytorch
git submodule update --init --recursive
python3 setup.py install

## Expected behavior

Can successfully import caffe2.python.onnx.backend

## Environment

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.15.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.16.0
[pip3] numpydoc==0.7.0
[pip3] torch==1.3.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.2
[conda] Could not collect

**Comment by colesbury** [comment]
Here are the environment variables that control the build:

https://github.com/pytorch/pytorch/blob/d927d58c2a72e46e84d03bcd4fa01118e7b9f4b3/setup.py#L120

You might want to try `CUDA_HOME` instead of `CUDA_INSTALL_DIR`.

@orionr, Is caffe2 included with the PyTorch wheel? I was under the impression that it was.

**Comment by orionr** [comment]
Caffe2 (potentially minus some operators right now - @ezyang might now on that front) should be included. caffe2_pb2 would be built as a part of that. cc @malfet

**Comment by orionr** [comment]
Also, heads up that we aren't supporting the Caffe2 APIs with new builds moving forward, so this might break. We strongly encourage folks to move to the PyTorch APIs.

**Comment by malfet** [comment]
Can you please try removing `build` folder and run `setup.py` again?
Also, please check that `which nvcc` returns path to the correct version of CUDA compiler.

Because from the logs it looks like build is using  CUDA-10.2, although you've selected to use CUDA-10.0:

> make[2]: *** No rule to make target '/usr/local/cuda-10.2/lib64/stubs/libcuda.so', needed by 'lib/libcaffe2_nvrtc.so'.  Stop.
> export PATH=$PATH:/usr/local/cuda-10.0/bin

To change the default, please put path to CUDA-10 bin folder as the first candidate in search path, by invoking:
` export PATH=/usr/local/cuda-10.0/bin:$PATH`

**Comment by chiehpower** [comment]
Hi all, 
Thanks for all your reply and suggestions!!

> Here are the environment variables that control the build:
> 
> https://github.com/pytorch/pytorch/blob/d927d58c2a72e46e84d03bcd4fa01118e7b9f4b3/setup.py#L117-L126
> 
> You might want to try `CUDA_HOME` instead of `CUDA_INSTALL_DIR`.
> 
> @orionr, Is caffe2 included with the PyTorch wheel? I was under the impression that it was.
Hi colesbury,
In my source, I put both indeed. You can see my previous provided export.
Also, I have tried to export particularly `CUDA_HOME`, but the result is same.

Hi orionr,
Thanks for your useful information! I will notice it.

> Can you please try removing `build` folder and run `setup.py` again?
> Also, please check that `which nvcc` returns path to the correct version of CUDA compiler.
> 
> Because from the logs it looks like build is using CUDA-10.2, although you've selected to use CUDA-10.0:
> 
> > make[2]: *** No rule to make target '/usr/local/cuda-10.2/lib64/stubs/libcuda.so', needed by 'lib/libcaffe2_nvrtc.so'.  Stop.
> > export PATH=$PATH:/usr/local/cuda-10.0/bin
Hi malfet,
Thanks for your suggestion. I haven't tried to remove build folder. (I will try it later.)
Also I already output `which nvcc`
```
/usr/local/cuda-10.0/bin/nvcc
```
It seems like correct!

Although my `nvidia-smi` output shows CUDA-version 10.2, my `nvcc -V` is 10.0
```                                            
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

Now I am going to clone again without removing original pytorch repo, and rebuild again.

> To change the default, please put path to CUDA-10 bin folder as the first candidate in search path, by invoking:
> ` export PATH=/usr/local/cuda-10.0/bin:$PATH`
I will tried your method as well .

I will keep updating here. Thanks for your everyone help!

**Comment by chiehpower** [comment]
Now it seems like successfully finish the setup.py. Somethings like below:
```
running install_egg_info
running egg_info
creating torch.egg-info
writing torch.egg-info/PKG-INFO
writing dependency_links to torch.egg-info/dependency_links.txt
writing entry points to torch.egg-info/entry_points.txt
writing requirements to torch.egg-info/requires.txt
writing top-level names to torch.egg-info/top_level.txt
writing manifest file 'torch.egg-info/SOURCES.txt'
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
Copying torch.egg-info to /usr/local/lib/python3.6/dist-packages/torch-1.5.0a0+b8e043a-py3.6.egg-info
running install_scripts
Installing convert-caffe2-to-onnx script to /usr/local/bin
Installing convert-onnx-to-caffe2 script to /usr/local/bin
```
Although I can successfully import `caffe2` and  `caffe2.python`.
```
>>> import caffe2
>>> import caffe2.python
```

However, I cannot still import the relevant caff2 package.
```
>>> import caffe2.python.onnx.backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chieh/github/pytorch_github/caffe2/python/onnx/backend.py", line 28, in <module>
    from caffe2.python import core, workspace, rnn_cell, gru_cell
  File "/home/chieh/github/pytorch_github/caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```
And 
```
>>> from caffe2.python import core, workspace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chieh/github/pytorch_github/caffe2/python/core.py", line 9, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```
Is there any idea for this issue? 
Thank you very much!!

**Comment by malfet** [comment]
> ModuleNotFoundError: No module named 'past'
Module `past` is part of `python3-future` package on Ubuntu (or just `pip3 install future`)

**Comment by chiehpower** [comment]
> pip3 install future

Thanks for your help!
It works!! 
I will close this issue!
