### ISSUE TITLE
how could i load model in c++ and use other method not forward

### ISSUE THREAD

**Issue by liyuanyaun** [pytorch/pytorch#34950]
for exanple:
```python
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv = nn.Conv2d(1, 1, 3)

    def forward(self, x):
        return self.conv(x)
   def weighted_kernel_sum(self, weight):
        return weight * self.conv.weight

n = Net()
example_weight = torch.rand(1, 1, 3, 3)
example_forward_input = torch.rand(1, 1, 3, 3)
inputs = {'forward' : example_forward_input, 'weighted_kernel_sum' : example_weight}
module = torch.jit.trace_module(n, inputs)
```

and in libtorch
the mothod 'forward' can be used by (torch::jit::script::Module)model.forward. if i want to use method 'weighted_kernel_sum', but how to referance the method   'weighted_kernel_sum'?

cc @suo

**Comment by jamesr66a** [comment]
Hi @liyuanyaun,

You can use `Module::run_method()`, which allows you to pass in the name of the method you'd like to run.

Also, the proper place for questions is PyTorch forums under the [JIT tag](https://discuss.pytorch.org/c/jit/13). Please feel free to ask questions there

James

**Comment by liyuanyaun** [comment]
> Hi @liyuanyaun,
> You can use Module::run_method(), which allows you to pass in the name of the method you'd like to run.
> Also, the proper place for questions is PyTorch forums under the JIT tag. Please feel free to ask questions there
> James

thank you very much, could you tell me which version of libtorch is needed?
