### ISSUE TITLE
ParameterList and ModuleList with named modules or parameters

### ISSUE THREAD

**Issue by dhpollack** [pytorch/pytorch#3499]
Both ParameterList and ModuleList could be easily modified to allow for a tuple of named parameters/modules.  It would be nice to retain the name of the parameters/modules if they were used.

Relating to this, I also thought it would be nice if both these lists accepted the generators produced by Module.modules(), Module.parameters(), Module.named_parameters(), Module.named_modules() as in input for the extend() function.  Thus one could do something like:

       model = torchvision.models.resnet18()
       plist = nn.ParameterList()
       plist.extend(model.layer4.parameters())
       plist.extend(model.fc.parameters())
       optimizer = optim.SGD(plist, lr = 0.1)

lastly, the ParameterList should have a different repr() function.  Currently it prints out a list of modules, which is always empty.  It should print out the Parameters or some sort of summary of the Parameters.

I could throw together a pr pretty quickly for these issues.

Of course, another idea would be to add a ParameterOrderedDict and ModuleOrderedDict as separate classes to work with the named_parameters/modules functions.  Also not very difficult but a little more work.

**Comment by apaszke** [comment]
I like the idea with `extend` and changing the `__repr__`. Please send a PR. I don't think parameter or module dicts are necessary - any `nn.Module` can work as such dict.

**Comment by dhpollack** [comment]
alright, this should do it.  You will get funny behavior if one were to add two sets of modules/parameters with the named_*() functions.  The items in the dict get overwritten because the submodules often have names that are integer strings.  To prevent modules from getting overwritten, I added an option to prefix the names with a string.  

       model = torchvision.models.resnet18()
       mlist = nn.ModuleList()
       mlist.extend(model.layer3.named_modules(), "layer3")
       mlist.extend(model.layer4.named_modules(), "layer4")

I also added the ability to reference the contents via an integer index or a string key value.  

finally, the `__repr__` shows a summary of the Parameter, but not a printout of the entire matrix.  This felt nicer than printing out the whole matrix especially if the ParameterList was long.

**Comment by GuillaumeLeclerc** [comment]
I agree that the fact that it prints an empty object is extremely misleading. I think having `__repr__` that actually describe the parameter list (at least the number of elements in it) would be super useful. I really thought there was a bug

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/3505
