### ISSUE TITLE
[Master Plan] Merge c10::ivalue::Future and torch::utils::Future<T>

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#34997]
Ideally we should have one Future abstraction in PyTorch codebase to have unified code paths regarding Future usage. 

torch::utils::Future<T> is a generic Future, we can specialize it as torch::utils::Future[IValue] and make torch::utils::Future[IValue] to be an IValue. After that, we can kill c10::ivalue::Future implementation

cc @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @ilia-cher @wanchaol

**Comment by xush6528** [comment]
Motivation

* It is causing RPC C++ entries to return different types, RPC TorchScript returns ivalue::Future. This is blocking Dist autograd Profiler(Rohan) and adding Future Python Type Annotation(Wanchao, Shihao).
* Autograd, DistAutograd, RPC is using utils::Future<T>, while JIT/TorchScript is using ivalue::Future. On integration point of RPC and JIT modules, this always creates divergent code paths and inconvenience for developers.

Plan

* Wrap utils::Future<rpc::Message> returned by RPC Python/BuiltinOp code paths into ivalue::Future[PyObject]. https://github.com/pytorch/pytorch/pull/35154
* Make ivalue::Future behave not exactly the same as utils::Future<T>. There are a few differences now. Will change them to the same behavior before replace ivalue::Future with utils::Future<IValue>
    * ivalue::Future::wait() only waits, does not returns value.
    * ivalue::Future::value() always returns a copy.  While utils::Future<T> wait() returns a reference.
    * ivalue::Future::FutureError and utils::FutureError are 2 types.
    * ivalue::Future::markCompleted takes FutureError. utils::Future<T>::setError takes FutureError.
    * ivalue::Future::addCallback adds a lambda that takes no argument. utils::Future<T>::addCallback adds a lambda that takes T and FutureError.
    * ivalue::Future assumes the value is default construct-able, so it can mark future as completed without providing value.
    * ivalue::Future support stream operator

**Comment by pritamdamania87** [comment]
@xush6528 Thanks for all the work on this! Since https://github.com/pytorch/pytorch/pull/35849 and https://github.com/pytorch/pytorch/pull/35154 are closed, could you update this issue with any outstanding items that we still need to address?

**Comment by rohan-varma** [comment]
We have completely deleted `torch/csrc/utils/future.h` and are using c10::ivalue::Future across the RPC codebase now, so closing this out.
