### ISSUE TITLE
`torch.cat` should do type promotion

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#35014]
## 🐛 Bug

When concatenating tensors of different dtypes, the result is unexpected (and often incorrect). This could be fixed by using type promotion.

## To Reproduce

```python
>>> xt = torch.ones((2, 1, 3), dtype=torch.int8)
>>> yt = torch.ones((2, 1, 3), dtype=torch.int32)
>>> torch.cat([xt, yt])
tensor([[[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 0, 0]],
        [[0, 1, 0]]], dtype=torch.int8)
>>> torch.cat([yt, xt])
tensor([[[        1,         1,         1]],
        [[        1,         1,         1]],
        [[ 16843009,       257, 180739632]],
        [[        1,  10605347, 805308415]]], dtype=torch.int32)
```

## Expected behavior

Here are possible behaviors:

### Solution 1. Raise an error.

This makes sense with the current implementation where there is no actual type promotion.
```python
>>> xt = torch.ones((2, 1, 3), dtype=torch.int8)
>>> yt = torch.ones((2, 1, 3), dtype=torch.int32)
>>> torch.cat([xt, yt])
ValueError: Cannot concatenate tensors of different dtypes!
```

### Solution 2. Promote/Demote to the dtype of the first tensor
This solution will lose precision
Notice the output dtype in the examples below.

```python
>>> xt = torch.ones((2, 1, 3), dtype=torch.int8)
>>> yt = torch.ones((2, 1, 3), dtype=torch.int32)
>>> torch.cat([xt, yt])
tensor([[[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]]], dtype=torch.int8)  # Because the first element is int8
>>> torch.cat([yt, xt])
tensor([[[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]]], dtype=torch.int32)  # Because the first element is int32
```

### Solution 3. Promote to the dtype of the tensor with the highest hierarchy
![](https://emertxe.com/blog/wp-content/uploads/2018/02/5-1.jpg)

```python
>>> xt = torch.ones((2, 1, 3), dtype=torch.int8)
>>> yt = torch.ones((2, 1, 3), dtype=torch.int32)
>>> torch.cat([xt, yt])
tensor([[[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]]], dtype=torch.int32)  # Because int32 > int8
>>> torch.cat([yt, xt])
tensor([[[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]],
        [[1, 1, 1]]], dtype=torch.int32)  # Because int32 > int8
```

## Environment

```console
$> python ./torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.5.0a0+762be86
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.2
GCC version: Could not collect
CMake version: version 3.13.3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.5.0a0+762be86
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.5.0a0+66f2922
[conda] Could not collect
```

## Additional context

cc @ezyang @gchanan @zou3519 @SsnL

**Comment by VitalyFedyunin** [comment]
Need to check it in v1.4, possibly regression.

**Comment by VitalyFedyunin** [comment]
Can we please do simple fix to Raise error (as we need it in 1.5) and discuss type promotion after.

**Comment by VitalyFedyunin** [comment]
pytorch 1.4


```python

In [1]: import torch

In [2]: xt = torch.ones((2, 1, 3), dtype=torch.int8)

In [3]: yt = torch.ones((2, 1, 3), dtype=torch.int32)

In [4]: torch.cat([xt, yt])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-59a5703f4b97> in <module>
----> 1 torch.cat([xt, yt])

RuntimeError: Expected object of scalar type Char but got scalar type Int for sequence element 1 in sequence argument at position #1 'tensors'

```

**Comment by albanD** [comment]
We already added a fix for the device here: https://github.com/pytorch/pytorch/pull/35053 shall we add a similar one for dtype?

**Comment by mruberry** [comment]
Disallowing sounds like a good start to prevent silent breaks. NumPy will type promote in this case: 

```
a0 = np.array((3, 4), dtype=np.int32)
a1 = np.array((5, 6), dtype=np.float32)
np.concatenate((a0, a1))
: array([3., 4., 5., 6.])
```

So in the future I'd expect PyTorch to type promote, too (following our own type promotion rules).

**Comment by albanD** [comment]
That might have complex implications for the backward formulas. So that would need to be discussed.

**Comment by ezyang** [comment]
Can't you just compute at the promoted type and then the autograd engine will take care of converting the dtype as necessary?

**Comment by gchanan** [comment]
@ezyang I don't know if the autograd engine handles that case currently, but it should.

**Comment by yf225** [comment]
We will raise error for this case in 1.5, and we will implement the type promotion approach after discussion.

**Comment by emcastillo** [comment]
I started to work on a type promotion approach in #35030

**Comment by z-a-f** [comment]
Landing #35150 which will throw an error. Not closing this issue in order to keep the discussion for the type promotion going.

**Comment by gchanan** [comment]
removing bc-breaking because as @VitalyFedyunin points out, it's not bc-breaking.

**Comment by gchanan** [comment]
I'm going to create a new issue for this because trying to overload issues in this way can be confusing.

**Comment by gchanan** [comment]
as suggested by @VitalyFedyunin I'm going to file an issue for the broken one and leave this for type promotion.

**Comment by emcastillo** [comment]
Hi, Can I get some feedback in  #35030?
Thanks!

**Comment by tianboh** [comment]
Hi there, I find a edge case for this issue.
PyTorch version 1.7.1
```
a = torch.zeros(5, dtype=torch.long)
b = torch.tensor([])
c = torch.cat([a,b])
print(c)
```
The result type for c is float, where the expected behavior should be long.

**Comment by mruberry** [comment]
Would you file a new issue for that bug, @tianboh?

**Comment by tianboh** [comment]
> Would you file a new issue for that bug, @tianboh?

Sure, I filed a new issue here -> #57938
