### ISSUE TITLE
Is grad attribute in Variable immutable?

### ISSUE THREAD

**Issue by lanpa** [pytorch/pytorch#3502]
The [doc](http://pytorch.org/docs/master/autograd.html?highlight=reassigned#variable) says :
"This attribute is lazily allocated and can’t be reassigned."

but It can be modified instead. See the example: 

```python
import torch
m = torch.nn.Linear(4, 1)
x = torch.autograd.Variable(torch.rand(4))
y = m(x)
print(m.weight.grad) # None
y.backward()
print(m.weight.grad)
ww = m.weight.grad.clone()

m.weight.grad *= 100
print(m.weight.grad)

m.weight.grad = ww
print(m.weight.grad)
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by qbx2** [comment]
Inplace operations are available I think

**Comment by soumith** [comment]
@colesbury what's our future positioning on this? shall we update the docs to say it's supported, or not really?

**Comment by apaszke** [comment]
It probably makes sense to allow assigning it. Disallowing it doesn't really change anything because you can do `torch.autograd.backward(var, var_grad)` to load `var_grad` as `var.grad`, except that it's unnecessarily convoluted.

**Comment by albanD** [comment]
This is out of date. You can assign it now and it works as expected.
