### ISSUE TITLE
Refactor record_function_ops.cpp to not use cpp_custom_type_hack

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#35026]
## 🚀 Feature
Currently the implementation of the `record_function` class is not ideal in that it uses a `cpp_custom_type_hack` to cast a tensor into a custom C++ object, in this case, `torch::autograd::profiler::RecordFunction`. See https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/record_function_ops.cpp.

Now with the availibility of torchbind, we can register the above as a custom C++ class to expose it to JIT (https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html#defining-custom-operators-that-take-or-return-bound-c-classes), and get rid of this hack.

cc @suo

**Comment by aaronenyeshi** [comment]
`cpp_custom_type_hack` is deprecated. Closing this old issue.
