### ISSUE TITLE
DistributedDataParallel typo bug 

### ISSUE THREAD

**Issue by levyben1** [pytorch/pytorch#3503]
Hi, wanted to report a typo bug I found in DistributedDataParallel class:

line: 107
self._module**s**_copies = [self.module]

should be : 
self._module_copies = [self.module]

**Comment by zou3519** [comment]
Thanks for the report!
I'm not seeing this on [master](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py), perhaps it has been fixed?

**Comment by soumith** [comment]
this was fixed on master. Will be part of the next release.
