### ISSUE TITLE
torch.cat is moving Tensors across devices silently

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#35045]
## 🐛 Bug

Giving input from different devices to torch.cat moves them all to the device of the first input.

As a side effect, since the autograd formula is not aware of this, it fails during the backward.

## To Reproduce

See user report here: https://discuss.pytorch.org/t/multi-gpu-backward-error/73427/

## Expected behavior

`torch.cat` should never move Tensors across devices.

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ngimel** [comment]
@Baranowski can you please look into a quick fix here?

**Comment by vadimkantorov** [comment]
One case (hopefully supported in future) where moving between devices makes sense:
`torch.cat([torch.rand(3, device = 'cuda'), 1])` for appending python scalars to a tensor
