### ISSUE TITLE
failed on onnx.checker.check_model after torch.onnx.export

### ISSUE THREAD

**Issue by sam-cts** [pytorch/pytorch#35096]
## 🐛 Bug
Failed to check_model after exporting a model with torch.onnx.export

`
  File "tools/pytorch2onnx.py", line 122, in main
    onnx.checker.check_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "1107" op_type: "Constant" attribute { name: "value" s: "cuda:0" type: STRING }
`

I have tried to transfer the memories from cuda() to cpu(), both of them output same error
`
  File "tools/pytorch2onnx.py", line 122, in main
    onnx.checker.check_model(onnx_model)
  File "/usr/local/lib/python3.6/dist-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "1107" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
`

Here is the export options
`
            torch.onnx.export(
                model,
                inputs,
                f,
                operator_export_type=OperatorExportTypes.ONNX_ATEN,
                verbose=True, 
                opset_version=11
            )
`

Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 440.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Can you add proper repro steps?

**Comment by LeonWlw** [comment]
I got the same err,did u solve it? @sam-cts

**Comment by spandantiwari** [comment]
@sam-cts - please add some repro steps? Also, could you test with the latest PyTorch.

**Comment by kksweet8845** [comment]
I got the same error.

I export the MaskRCNN implemented by Detectron2 as a submodule. Trying to export it by torch.onnx.export.
After exporting successfully by torch.onnx.export, I got the same kind of error.

```
Traceback (most recent call last):
  File "export.py", line 64, in <module>
    onnx.checker.check_model(onnx_model)
  File "/media/nober_workspace/pyenv/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "325" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
```
### The module class named `ToOnnx` defined in here
It is exported to onnx format successfully.
```
from torch import nn
import torch.utils.model_zoo as model_zoo
import torch.onnx as tonnx

from os.path import isfile, isdir, join

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2 import model_zoo
import torch

from torch.onnx import ONNX_ARCHIVE_MODEL_PROTO_NAME, ExportTypes, OperatorExportTypes

class ToOnnx(nn.Module):
    def __init__(self, model_name, ckpt_dir):
        super(ToOnnx, self).__init__()
        self.model_name = model_name
        self.ckpt_dir = ckpt_dir
        self.initCfg()
        self.predictor = DefaultPredictor(self.cfg)

        self.add_module("mask_rcnn", self.predictor.model)

    def initCfg(self):
        cfg = get_cfg()
        cfg.merge_from_file(model_zoo.get_config_file(self.model_name))
        cfg.DATALOADER.NUM_WORKERS = 2
        cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(self.model_name)  # Let training initialize from model zoo
        cfg.SOLVER.IMS_PER_BATCH = 2
        cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
        cfg.SOLVER.MAX_ITER = 5400    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
        cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
        cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4  # only has one class (ballon)

        cfg.OUTPUT_DIR = self.ckpt_dir
        cfg.MODEL.WEIGHTS = join(cfg.OUTPUT_DIR, "model_final.pth")
        cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.8   # set the testing threshold for this model

        self.cfg = cfg
        

    def exportModel(self, model, input, input_names, output_names,
    output_dir="super_resolution.onnx", version=10, dynamic_axes={}):
        def _check_eval(module):
            assert not module.training

        # model.eval()
        # print(model.training)
        # model.apply(_check_eval)
        with torch.no_grad():
            with open(output_dir, 'w') as f:
                tonnx.export(
                    model, ## Model being run
                    input,
                    "mask_rcnn.onnx",
                    verbose=False,
                    export_params=True,
                    opset_version=12,
                    do_constant_folding=True,
                    input_names=input_names,
                    output_names=output_names,
                    dynamic_axes=dynamic_axes,
                    use_external_data_format=True,
                    operator_export_type=OperatorExportTypes.ONNX_ATEN
                )


    def forward(self, original_image):

        original_image = np.asarray(original_image)

        out = self.predictor(original_image)
        predictions = out['instances'].to('cpu')
        img_height, img_width = predictions.image_size

        boxes = predictions.pred_boxes if predictions.has("pred_boxes") else None
        scores = predictions.scores if predictions.has("scores") else None
        classes = predictions.pred_classes if predictions.has("pred_classes") else None


        if predictions.has("pred_masks"):
            masks = torch.tensor(predictions.pred_masks, dtype=int).detach()
            # masks = [GenericMask(x, img_height, img_width) for x in masks]
        else:
            masks = None

        
        return {
            'pred_boxes' : boxes.tensor,
            'scores' : scores,
            'pred_classes' : classes,
            'pred_masks' : masks
        }

```

### The code which the `ToOnnx` being invoked

```
    model_name = model_name = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    ckpt_dirs = './output-R50_FPN-v2-10800'

    toonnx = ToOnnx(model_name, ckpt_dirs)
    toonnx.exportModel(toonnx,
                       original_image,
                       ['image'],
                       ['pred_boxes', 'scores', 'pred_classes', 'pred_masks'],
                       output_dir="./mask_rcnn.onnx",
                       dynamic_axes={
                           'image' : {
                               0 : 'C',
                               1 : 'H',
                               2 : 'W'
                           },
                           'pred_boxes' : {
                               0 : 'N'
                           },
                           'scores' : {
                               0 : 'N'
                           },
                           'pred_classes' : {
                               0 : 'N'
                           },
                           'pred_masks' : {
                               0 : 'N',
                               1 : 'H',
                               2 : 'W'
                           }

                       })
    
```
### And I check the model shown as following
Error occurred.
```
    onnx_model = onnx.load("mask_rcnn.onnx")
    onnx.checker.check_model(onnx_model)
```

```
Traceback (most recent call last):
  File "export.py", line 64, in <module>
    onnx.checker.check_model(onnx_model)
  File "/media/nober_workspace/pyenv/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "325" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
```


Environment
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.5.0

Python version: 3.6.9
Is CUDA available: Yes
CUDA runtime version: 10.2
GPU models and configuration: GPU 0: GeForce GTX 2080
Nvidia driver version: 450.57
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[pip3] onnx==1.7.0


cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

Thx

**Comment by spandantiwari** [comment]
@sam-cts - please reopen this issue with a repro, if you like. 
@kksweet8845 - I see that you have already opened a separate issue. https://github.com/pytorch/pytorch/issues/42995

**Comment by chaorensx** [comment]
similar problem

**Comment by ShidiDaisy** [comment]
same problem

**Comment by spandantiwari** [comment]
See https://github.com/pytorch/pytorch/issues/42995 for tracking related issue.

**Comment by neginraoof** [comment]
Operator export type ONNX_ATEN is used to export ops as ATen ops, not ONNX.
This export type should be used for backend which do support ATen operators.
For exporting a model to ONNX, please don't change the default export type.
