### ISSUE TITLE
`bin/test_jit --gtest_filter=JitTest.CustomOperators --gtest_repeat=2` fails

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#35103]
## 🐛 Bug

Multiple runs of JitTest.CustomOperators fail with:
```
C++ exception with description "(ops.size()) == (1) INTERNAL ASSERT FAILED at /home/nshulga/git/pytorch/test/cpp/jit/test_custom_operators.cpp:17, please report a bug to PyTorch.  (testCustomOperators at /home/nshulga/git/pytorch/test/cpp/jit/test_custom_operators.cpp:17)
```

## To Reproduce

`cmake /path/to/pytorch -G Ninja;  ninja test_jit; bin/test_jit --gtest_filter=JitTest.CustomOperators --gtest_repeat=2`

cc @suo

**Comment by malfet** [comment]
Looking into this one now.

**Comment by malfet** [comment]
And it happens because deregister is not implemented: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/register_c10_ops.cpp#L160

**Comment by suo** [comment]
lol, cc @smessmer
