### ISSUE TITLE
Consolidate RRef type class and RRef impl class

### ISSUE THREAD

**Issue by zzzwen** [pytorch/pytorch#35110]
Python3 typing for `rpc.RRef` is missing.  If I do `from torch.rpc.distritubed import RRef`, then `rref_module : RRef[nn.Module]` will result in error `'pybind11_type' object is not subscriptable`

cc @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by xush6528** [comment]
@zzzwen the type class in under `_jit_internal.py`.

try this
```py
from torch._jit_internal import RRef
```

**Comment by xush6528** [comment]
From @zzzwen 's feedback,
> If I do `from torch.rpc.distritubed import RRef` then `rref_module : RRef[nn.Module]`
Then I will get the error, 'pybind11_type' object is not subscriptable
