### ISSUE TITLE
I have installed libomp but still cannot import Pytorch

### ISSUE THREAD

**Issue by ShirleyTse** [pytorch/pytorch#35156]
**BUG:**

I tried to install torch1.0, but I failed.

Terminal gave me this:
```>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 9): Library not loaded: @rpath/libcufft.10.0.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.dylib
  Reason: image not found
```

And I saw a solution on GitHub, which told me to install libomp. However, it didn't work.

**My Environment:**

macOS High Sierra 10.13.6
NVIDIA GeForce GTX 1070
GPU Driver Version: 387.10.10.10.40.133
CUDA Driver Version: 396.148
CUDA Version: 9.2
cuDNN Version: 7.2
Python Version: 3.7.7
Pytorch  Version: 1.0

**Comment by malfet** [comment]
According to `ImportError` message, import failed because `libcufft.10.0.dylib` is missing on your system. 
That is, it looks like you've install pytorch with CUDA 10 support, although only CUDA-9 is available on your system.

**Comment by pbelevich** [comment]
> I tried to install torch1.0, but I failed.
How did you do that? Please specify exact steps

**Comment by ShirleyTse** [comment]
> According to `ImportError` message, import failed because `libcufft.10.0.dylib` is missing on your system.
> That is, it looks like you've install pytorch with CUDA 10 support, although only CUDA-9 is available on your system.

Stupid me. 

You’re right. I installed CUDA10 and cuDNN7.4 and it goes well now. Thank u!
