### ISSUE TITLE
pytorch model convert onnx KeyError: 'im2col'

### ISSUE THREAD

**Issue by daixiangzi** [pytorch/pytorch#35155]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.4.0
 - OS (e.g., Linux):ubuntu 16
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by take-cheeze** [comment]
You can export it with custom torch.onnx exporter with [UnfoldToDepth-12 operator]( https://github.com/onnx/onnx/blob/master/docs/Operators.md#unfoldtodepth)

**Comment by daixiangzi** [comment]
i solved this problem ,thanks&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Takeshi Watanabe"<notifications@github.com&gt;; 
发送时间: 2020年3月23日(星期一) 中午1:47
收件人: "pytorch/pytorch"<pytorch@noreply.github.com&gt;; 
抄送: "代翔子"<543826458@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pytorch/pytorch] pytorch model convert onnx KeyError: &#39;im2col&#39; (#35155)





 
You can export it with custom torch.onnx exporter with UnfoldToDepth-12 operator

**Comment by rivergold** [comment]
@daixiangzi How did you solve this problem?

**Comment by caoyifeng001** [comment]
@daixiangzi 
 i have same problem
