### ISSUE TITLE
Questions about cudaStreamSynchronize in Pytorch

### ISSUE THREAD

**Issue by stoneboy100200** [pytorch/pytorch#35171]
Hello, I am a user of pytorch (1.0.1). I would like to ask a question about the cuda operator. This question has troubled me for a long time and I have not found an answer.

Many cuda operators, such as "aten/src/ATen/native/cuda/Activation.cu: prelu_cuda". In this function, "at::cuda ::getCurrentCUDAStream(curDevice)" is called, but "cudaStreamSynchronize(stream)" is not called, I know that cuda's operators are asynchronous, but should reasonably call "cudaStreamSynchronize(stream)" in a suitable place, I only found "cudaStreamSynchronize(stream)" in "aten/src/ATen/native/cuda/Copy.cu" , But this happens during the process of copying cpu to cuda or cuda to cpu. If running a network, the CPU releases the memory allocated for cuda in advance, such as calling cudaFree, but cuda is not calculated at this time, the release of these cuda resources is triggered by the release of the temporary Tensor in the network (if I am wrong please correct me, thank you), this will cause serious problems, right? So I want to know how the pytorch guarantees that cuda is already calculated when the temporary Tensor is released, I think that "cudaStreamSynchronize" should be called once before the intermediate Tensor is released. I don't know if you will reply to me, but I'm still looking forward to your help to answer this question that has troubled me for a long time. 

Thank you very much!

**Comment by ngimel** [comment]
Please ask the questions on discuss.pytorch.org. To answer your questions very briefly, the situation you described is correctly handled by pytorch because pytorch uses caching allocator, and when allocating gpu memory it also marks the stream it is used on. As long as you keep launching cuda work on the same stream, the memory you are using might be marked as free, but in fact no other stream will be able to reuse it, and on your stream the correct ordering will be preserved. If you intend to use this memory from another stream it's your responsibility to call `record_stream` on the memory. For more details you can look at the source code of cuda caching allocator.

**Comment by stoneboy100200** [comment]
Hi Ngimel,
Thank you very much for your reply. I know that cuda will guarantee the sequential execution of programs in the same stream. In fact, my problem is that the destruction of the intermediate Tensor will cause the memory allocated for cuda on the CPU side to be destroyed. If cuda is calculating at this time, This behavior will cause some problems, so pytorch should have a mechanism to extend the life cycle of the temporary Tensor to ensure that cuda has completed the calculation, right?

My other questions:

- I read the code for allocating memory for cuda, but it doesn't seem to be tied to the stream (I'm not sure if my point is correct): caffe2/core/context_gpu.cu

```
struct DefaultCUDAAllocator final : public at::Allocator {
   at::DataPtr allocate(size_t nbytes) const override {
    ...
     switch (g_cuda_memory_pool_type) {
       case CudaMemoryPoolType::NONE:
         if (nbytes != 0) {
           CUDA_ENFORCE(cudaMalloc(&ptr, nbytes));
         }
         if (FLAGS_caffe2_gpu_memory_tracking) {
           g_size_map[ptr] = nbytes;
           g_cuda_device_affiliation[ptr] = CaffeCudaGetDevice();
         }
         return {ptr, ptr, &Delete, at::Device(CUDA, CaffeCudaGetDevice())};
       case CudaMemoryPoolType::CUB:
       case CudaMemoryPoolType::THC:
```
I don't know which memory pool is used in pytorch. CudaMemoryPoolType::NONE? CudaMemoryPoolType::CUB? or CudaMemoryPoolType::THC?

- According to my inference, pytorch should call sync function(such as "cudaStreamSynchronize") before recycling cuda resources to ensure that cuda has completed the calculation. For example in the following code: 
```
caffe2/core/context_gpu.cu
static void Delete(void* ptr) {
...
     switch (g_cuda_memory_pool_type) {
       case CudaMemoryPoolType::NONE: {
         // If memory pool is not set up, use simple cudaFree.
         cudaError_t error = cudaFree(ptr);
         // For some reason, in Python runtime we sometimes delete a data pointer
         // after the cuda runtime exits - this is odd but is probably caused by
         // a static workspace that pycaffe2 uses, and the destruction got
         // entangled in some race condition. Anyway, since cuda runtime is
         // exiting anyway, we will not need to worry about memory leak, so we
         // basically ignore it. This is definitely not ideal but works for now.
         if (error != cudaSuccess && error != cudaErrorCudartUnloading) {
           LOG(FATAL) << "Error at: " << __FILE__ << ":" << __LINE__ << ": "
                      << cudaGetErrorString(error);
         }

         if (FLAGS_caffe2_gpu_memory_tracking) {
           g_cuda_device_affiliation.erase(g_cuda_device_affiliation.find(ptr));
         }

         break;
       }
       case CudaMemoryPoolType::CUB: {
         auto it = g_cuda_device_affiliation.find(ptr);
         DCHECK(it != g_cuda_device_affiliation.end());
         VLOG(2) << "CUB freeing pointer " << ptr << " on device " << it->second;
         CUDA_ENFORCE(g_cub_allocator->DeviceFree(it->second, ptr));
         g_cuda_device_affiliation.erase(it);
         break;
       }
       case CudaMemoryPoolType::THC: {
       ....
}
```
streamSync like this:
```
...
     switch (g_cuda_memory_pool_type) {
       case CudaMemoryPoolType::NONE: {
         // stream sync
         cudaGetDevice(&curDevice); 
         cudaStream_t stream = at::cuda::getCurrentCUDAStream(curDevice);
         cudaStreamSynchronize(stream)
         // If memory pool is not set up, use simple cudaFree.
         cudaError_t error = cudaFree(ptr);
```

**Comment by ngimel** [comment]
Caching allocator is in this file https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDACachingAllocator.cpp. 
No, this behavior does not cause problems because of stream ordering guarantees.

**Comment by stoneboy100200** [comment]
Is it the same for pytorch 1.0.1?

**Comment by ngimel** [comment]
Yes, it did not change for a long time.
