### ISSUE TITLE
whl package for CUDA 10.2

### ISSUE THREAD

**Issue by Borda** [pytorch/pytorch#35181]
## ❓ Questions and Help

I am wondering if and when there will be also supported with pre-build wheels for CUDA 10.2 as it for other  CUDA versions at https://download.pytorch.org/whl/cu102 or via pip as
```
pip install torch==1.4.0+cu102 torchvision==0.5.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html
```

Thanks

**Comment by peterjc123** [comment]
CUDA 10.2 packages will be added in the next major release. There's no plan of publishing cuda 10.2 packages for 1.4.0.
