### ISSUE TITLE
Eigen error stop when building source on rocm 2.10 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by wormwang** [pytorch/pytorch#35186]
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version : 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch : building source
 - Build command you used: gcc 7.5.0
 - Python version: python3
 - CUDA/cuDNN version: AMD ROCm 2.10
 - GPU models and configuration: AMD vega

-- ******** Summary ********
-- General:
--   CMake version         : 3.10.2
--   CMake command         : /usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 7.5.0
--   BLAS                  : MKL
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow
--   Build type            : Release
--   Compile definitions   : NDEBUG;ONNX_ML=1;ONNX_NAMESPACE=onnx_torch;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1
--   CMAKE_PREFIX_PATH     : /usr/lib/python3/dist-packages
--   CMAKE_INSTALL_PREFIX  : /home/motech/pytorch/torch
-- 
--   TORCH_VERSION         : 1.4.0
--   CAFFE2_VERSION        : 1.4.0
--   BUILD_CAFFE2_MOBILE   : ON
--   USE_STATIC_DISPATCH   : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.6.9
--     Python executable   : /usr/bin/python3
--     Pythonlibs version  : 3.6.9
--     Python library      : /usr/lib/libpython3.6m.so.1.0
--     Python includes     : /usr/include/python3.6m
--     Python site-packages: lib/python3/dist-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   BUILD_JNI             : OFF
--   INTERN_BUILD_MOBILE   : 
--   USE_ASAN              : OFF
--   USE_CUDA              : 0
--   USE_ROCM              : ON
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : OFF
--   USE_MKLDNN            : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : ON
--   USE_NNPACK            : 0
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : 0
--   USE_TBB               : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : 0
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads
--   Private Dependencies : pytorch_qnnpack;cpuinfo;/usr/lib/aarch64-linux-gnu/libnuma.so;fp16;/usr/lib/aarch64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/aarch64-linux-gnu/openmpi/lib/libmpi.so;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring done

/home/motech/pytorch/cmake/../third_party/eigen/Eigen/src/Core/MathFunctions.h:465:28: error: no member named 'arg' in the global namespace
      EIGEN_USING_STD_MATH(arg);
      ~~~~~~~~~~~~~~~~~~~~~^~~~
/home/motech/pytorch/cmake/../third_party/eigen/Eigen/src/Core/util/Macros.h:918:46: note: expanded from macro 'EIGEN_USING_STD_MATH'
  #define EIGEN_USING_STD_MATH(FUNC) using ::FUNC;
                                           ~~^
1 warning and 1 error generated.
CMake Error at torch_generated_sinh_op.hip.o.cmake:174 (message):
  Error generating file
  /home/motech/pytorch/build/caffe2/CMakeFiles/torch.dir/operators/hip/./torch_generated_sinh_op.hip.o

Error stop when building meet the error

The same error also produce at PyTorch v1.0.1 building but, it been skiped then building are successful.

**Comment by wormwang** [comment]
meet same error when building source of v1.3.1 on ROCm & Ubuntu 18.04

**Comment by jeffdaily** [comment]
Please update to latest ROCm and latest PyTorch, ROCm 3.9 and PyTorch 1.7 at of time of writing.  Open a new issue if build problems persist.  Thanks.
