### ISSUE TITLE
Lower bound for torch::randint.

### ISSUE THREAD

**Issue by JesperLindberg** [pytorch/pytorch#35205]
## 🚀 Feature
I would want to have a lower limit for torch::randint. The reason for this is so that I can sample ints from 5-10 for example.

## Motivation
In C++ there is no "good" go-to default random number generator, however libtorch offers a solution for it. This solution seems to be forgotten or very out-of date as its missing one crucial feature. To be able to adjust the starting value of the random numbers...

## Alternatives

Using pseudo random number generator in C++. Which is not good when dealing with ML.

**Comment by nikitaved** [comment]
5 + randint(5) should resolve your issue?

**Comment by pbelevich** [comment]
[torch::randint() has lower bound](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorFactories.cpp#L520), you can write`torch::randint(5, 10, {3, 3});`

**Comment by JesperLindberg** [comment]
@pbelevich Apparently there are multiple different torch::randint? I get 4 to choose from now when I look into this matter further.

**Comment by pbelevich** [comment]
@JesperLindberg There are 4 overloaded methods `torch::randint()`, 2 overloader methods `torch::randint_out()` and 2 `torch::randint_like()`,  what is your question?
