### ISSUE TITLE
Documentation for torch::randint seems to be out of date?

### ISSUE THREAD

**Issue by JesperLindberg** [pytorch/pytorch#35204]
## 📚 Documentation
When I use function `torch::randint()` it takes arguments `int64_t high, at::IntArrayRef size, at::TensorOptions &options = {}` however, at the documentation it says there should also be a `at::Generator generator`

https://pytorch.org/cppdocs/api/function_namespacetorch_1ad86f0f5e4b92098660b54e584342a188.html?highlight=randint

I am using libtorch 1.4

cc @yf225

**Comment by pbelevich** [comment]
That's true, I'm rewriting RNG infrastructure, the documentation will be updated soon
