### ISSUE TITLE
I could bulild the Dlls and LIbs but they were different file-size from the Original Dlls nad Libs.  

### ISSUE THREAD

**Issue by yoshihingis** [pytorch/pytorch#35206]
Questions or Bugs ?

 I could build the Dlls and the Libs of libtorch Ver4.0 by buld_pytorch.bat, I got the libtorch-win-shared-with-deps-1.4.0.zip whicn included the DLLs and the Libs have same names as original  	
libtorch-win-shared-with-deps-1.4.0.zip.

  I built the Dlls and the LIbs by both VS17and VS19, I compared the file sizes of the DLLs and the Libs with the Orignal Dlls and Libs , Please refer to attached excel file.

 Some Dlls and Libs had the different file size with the original Dlls and LIbs , but the mnist example operated correctly  with both the Dlls & Libs of VS17  and the Dlls & Libs of VS19.

Is no-problem of different file-sizes of Dlls of Libs from the orignal Dlls and Libs? 

[libtorch_dll_lib00323_compare_a.xlsx](https://github.com/pytorch/pytorch/files/4368133/libtorch_dll_lib00323_compare_a.xlsx)

**Comment by peterjc123** [comment]
This is not a bug. The size of the binary is not consistent and there're too many factors that will affect that.
