### ISSUE TITLE
API doc for torch.max/min is broken

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#35216]
with [1.4 stable](https://pytorch.org/docs/stable/torch.html#torch.max), both max and min are broken

<img width="880" alt="Screen Shot 2020-03-23 at 1 10 07 PM" src="https://user-images.githubusercontent.com/16999635/77343167-a776c980-6d07-11ea-9f1a-1e4621228f18.png">

on [master](https://pytorch.org/docs/master/torch.html#torch.min), min is broken

<img width="875" alt="Screen Shot 2020-03-23 at 1 13 23 PM" src="https://user-images.githubusercontent.com/16999635/77343563-413e7680-6d08-11ea-8042-faaa845d90bc.png">

**Comment by zou3519** [comment]
Fixed by #36319 and #36347
