### ISSUE TITLE
[RuntimeError] copy_() : CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#35225]
CUDA error: unspecified launch failure when I changed the dispatch here https://github.com/pytorch/pytorch/blob/9441c7a9443dbc810c1190e4ca1e06c7c8308e47/aten/src/ATen/native/cuda/Copy.cu#L64 to AT_DISPATCH_ALL_TYPES_AND_COMPLEX_AND3 
and ran this code on cuda:

import torch
a=torch.randn(2,3,dtype=torch.complex64).cuda()
b=a.to(torch.complex128)

RuntimeError: CUDA error: unspecified launch failure

cc @ezyang @anjali411 @dylanbespalko @ngimel

**Comment by ngimel** [comment]
cc @zasdfgbnm

**Comment by anjali411** [comment]
Here's the PR for reference: https://github.com/pytorch/pytorch/pull/34093

**Comment by zasdfgbnm** [comment]
I can not reproduce this on
```
NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2
GeForce RTX 2080 Ti
```

**Comment by zasdfgbnm** [comment]
With `torch.cuda.synchronize()`, I can reproduce now

**Comment by anjali411** [comment]
alternately you can also use CUDA_LAUNCH_BLOCKING=1, 
for eg. for #35255: CUDA_LAUNCH_BLOCKING=1 python test.cpp
