### ISSUE TITLE
Continuous Learning

### ISSUE THREAD

**Issue by develooper1994** [pytorch/pytorch#35222]
## 🚀 Feature

Continuous Learning.
## Motivation
I am considering to learning should continue while collecting data. There is infrastructure apis to use pretrained network but I can't continue to train with it.

I'm always frustrated when comes to mobile. There is only infrastructure libraries.
## Pitch

There for "mobile gpu support" may requires to continuous training.

**Comment by pbelevich** [comment]
Please use https://discuss.pytorch.org for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.
