### ISSUE TITLE
Low performance issue on CPU-only machine

### ISSUE THREAD

**Issue by juliusshufan** [pytorch/pytorch#3525]
Hi, 

I cloned the latest source code from master branch and installed it from source code under anaconda environment on a CPU-only machine. I did set the NO_CUDA as 1 before installing, but the performance for both CNN and RNN models downgraded dramatically compared to the install from source code using release v0.2.0 or install from conda directly. 

I noticed the CPU load is at most 100% when the performance issue happened even I correctly set the OMP_NUM_THREADS matching the CPU type. 

May I have any clues why this issue happens?

Thanks.

Shufan

**Comment by SsnL** [comment]
Thanks for reporting. What are the structures of your model? Do you have concrete numbers on the performance degrading? A script will also be nice so we can try to spot issues :)

**Comment by MlWoo** [comment]
@SsnL  I have checked the code. [blas modification](https://github.com/pytorch/pytorch/commit/d04574b1fc73929faa1d6743e0486cda6586fd95#diff-845f134a51f3a63b10766c164a82c345) has a bug when try to disable MKL  if stride values are not supported. The code in [lines](https://github.com/pytorch/pytorch/blob/d04574b1fc73929faa1d6743e0486cda6586fd95/torch/lib/TH/generic/THBlas.c#L325-L326) 
~~~
      (lda >= THMax(1, (transa_ ? m : k))) && (lda <= INT_MAX) &&
      (ldb >= THMax(1, (transb_ ? k : n))) && (ldb <= INT_MAX) &&
~~~
has mistaken the condition so that it conflicts with the manual of [MKL](https://software.intel.com/en-us/mkl-developer-reference-fortran-gemm). it should be that
~~~
      (lda >= THMax(1, (transa_ ? k : m))) && (lda <= INT_MAX) &&
      (ldb >= THMax(1, (transb_ ? n : k))) && (ldb <= INT_MAX) &&
~~~
Plz double check it and summit it to repo if no problems.

**Comment by qbx2** [comment]
I cloned master, installed and executed same generator rnn. I got 15% of previous speed without cuda.

**Comment by SsnL** [comment]
cc @albanD on the issue raised by @MlWoo .

**Comment by MlWoo** [comment]
@SsnL I noticed that the other modifications also have similar bugs.  

- ger operation 
[Intel manual](https://software.intel.com/en-us/mkl-developer-reference-c-cblas-ger) explains that 
~~~
For Layout = CblasColMajor, the value of lda must be at least max(1, m).

For Layout = CblasRowMajor, the value of lda must be at least max(1, n).
~~~
Howerver, the modification does not check the transposing info and give the limit condition
~~~
(lda >= THMax(1, n)) && (lda <= INT_MAX) &&
~~~

- gemv operation
[Intel manual](https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemv) explains that
~~~ 
For Layout = CblasColMajor, the value of lda must be at least max(1, m).

For Layout = CblasRowMajor, the value of lda must be at least max(1, n).
~~
A similar bug also exsits.
~~~
(lda >= THMax(1, n)) && (lda <= INT_MAX) &&
~~~

**Comment by SsnL** [comment]
Hey @juliusshufan , how did you run your benchmark script? Could you tell us your CPU and the option you used please? I tried yesterday and it successfully utilized multiple cores. Also, were your looking at GFLOPS? How many iterations did you look at? Thanks!

**Comment by SsnL** [comment]
@MlWoo Thanks! The gemv thing is probably a bug.

On ger: blas assumes col major (https://www.math.utah.edu/software/lapack/lapack-blas/sger.html) likely due to that row major is easy to work around by changing the vectors' order. We already do that here. https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorMath.c#L1558-L1571.

**Comment by MlWoo** [comment]
@SsnL  yes, you point is right.

**Comment by juliusshufan** [comment]
@SsnL, the benchmark entry is run.sh, it mainly set the OMP_NUM_THREADS per the CPU model, another two parameters select the parameters for LSTM (hidden layers, sentence length, etc.) and if backward computation time cost will be taken account of,
i.e. : with command "**./run.sh bdw train daily**" , CPU model is Broadwell.
You will get the backward+forward benchmarks for the the two popular LSTM parameter combinations.
If you use  "**./run.sh bdw daily**", you will get the forward-only benchmarks for the the two popular LSTM parameter combinations.

You can extend the run.sh to support the CPU model you have, as long as the OMP_NUM_THREADS matching the CPU spec.

Thanks.

**Comment by juliusshufan** [comment]
@ colesbury , Thanks for the prompt fix, I tried your fix for this issue, and:

1. Looks like the macro "USE_BLAS" in line 323 is not set/defined even mkl correctly installed in conda,  I have to explicitly drop a line "#define USE_BLAS" in the THBlas.c to hit the code changes from you. 
2. Meanwhile, with explicit definition of the USE_BLAS and your fix, now the forward computation works well, but backward computation is still very slow. ( looks like not benefiting from the OMP).

May I have your comments? Thanks for your time.

Shufan

**Comment by tianleliu** [comment]
if( (m <= INT_MAX) && (n <= INT_MAX) && (k <= INT_MAX) &&
-      (lda >= THMax(1, (transa_ ? m : k))) && (lda <= INT_MAX) &&
-      (ldb >= THMax(1, (transb_ ? k : n))) && (ldb <= INT_MAX) &&
-      (ldc >= THMax(1, n)) && (ldc <= INT_MAX) )
+      (lda >= THMax(1, (transa_ ? k : m))) && (lda <= INT_MAX) &&
+      (ldb >= THMax(1, (transb_ ? n : k))) && (ldb <= INT_MAX) &&
+      (ldc >= THMax(1, m)) && (ldc <= INT_MAX) ) 

ldc‘s condition is also a bug. If fixed, gemm and its performance seem back to normal.

**Comment by SsnL** [comment]
@MlWoo So it turned out that ger code actually has a bug. If you look at the FORTRAN doc (the function we are using) at https://software.intel.com/en-us/mkl-developer-reference-fortran-ger, we are indeed checking lda wrong :P. I fixed those in #3604 .

**Comment by SsnL** [comment]
@juliusshufan This is a known issue if you installed mkl via conda. @soumith is working on a fix. Sorry about that.

**Comment by soumith** [comment]
@juliusshufan it only started being an issue since last week after we did a big refactor, i'm looking into this.
