### ISSUE TITLE
[RFC] TensorPipe RPC agent

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#35251]
### What is TensorPipe?

TensorPipe (https://github.com/pytorch/tensorpipe) is a library that provides a new primitive for point-to-point communication for machine learning. A so-called pipe is an ordered bidirectional stream of structured messages between two processes. Each message contains a list of payloads/tensors, which are represented as buffers: by a pointer and a length, residing on CPU or GPU. The pipe’s job is to copy the contents of those buffers to the other endpoint in the most efficient way possible. TensorPipe comes with a collection of “backends” which implement different ways of transferring data (TCP between machines in a network, shared memory inside the same machine, CUDA device-to-device memcpy, ...). The pipe is backend-agnostic and will autodiscover the capabilities of the two endpoints and negotiate the best available backend.

### What problems is it trying to solve?

For long, networking in PyTorch was synonymous with torch.distributed, which performs collective communication that works great for data parallelism. Some projects however have been pushing the envelope of that paradigm. Think model parallelism, parameter servers, actor-learner separation, elastic training, .... Those applications would benefit from point-to-point communication. This is what PyTorch’s RPC module has recently enabled. However, the backbone of RPC, its so-called “agent”, is based on Gloo, one of the libraries that were developed for the collective communication of torch.distributed. TensorPipe aims to power an alternative RPC agent designed from the group up for point-to-point communication and optimized for that scenario. For example, TensorPipe doesn’t require rendezvous between all pairs of processes (it supports arbitrary topologies and discovery methods), it offers asynchronous and asymmetric communication, and more.

Another challenge TensorPipe aims to address is the burden of supporting and leveraging all the transport techniques and interconnect fabrics available in modern hardware. It often falls to the user to be aware of where their code is run (threads of the same process, processes on the same machine, servers on the same rack, ...) and what their communication capabilities are (shared memory, NVLink, InfiniBand, GPUDirect, ...), and use that information to make informed choices in their code. TensorPipe wants to ship with builtin support for all of these backends and automatically figure out at runtime which one it should use based on the capabilities and the circumstances.

### What would we like to do?

We would like to implement an additional RPC agent that leverages TensorPipe. This would live side-to-side with the current Gloo-based one (ProcessGroup), with that one remaining the default one. As TensorPipe matures and gains more in-the-field experience we can see how it holds up against Gloo in real-world scenarios and decide whether to consolidate behind it.

### Who are we?

The team working on TensorPipe includes @jiayisuse, @beauby, @javier-m and @osalpekar . The project is the brainchild of @pietern, the author of Gloo.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by lw** [comment]
CC @mrshenli @pritamdamania87 @serhaty @satgera @jjlilley

**Comment by seemethere** [comment]
@lw Where are we at with this feature?

We are cutting for 1.6.0 tomorrow and would like to have this feature in before that cut happens.

**Comment by lw** [comment]
This feature has landed into master and is ready for today's branch cut. This first version provides a feature-complete RPC agent for CPU tensors, matching and beating the capabilities of the Gloo-based RPC agent. For v1.6 it will opt-in, with Gloo remaining the default, but this may change in v1.7. We're also working on getting support for GPU tensors in by v1.7.

**Comment by gchanan** [comment]
I'm going to close this given it's landed.
