### ISSUE TITLE
Undesired type cast in arithmetic between tensor and ndarray

### ISSUE THREAD

**Issue by KiddoZhu** [pytorch/pytorch#35257]
## To Reproduce

```python
import numpy as np
import torch

a = np.array([1], dtype=np.int64)
b = torch.tensor([1], dtype=torch.int64)
print((a[0] * b).dtype)
```

## Expected behavior

```
torch.float32
```

## Environment

 - PyTorch Version: 1.4.0

## Additional context

This happens for any numpy type (int32, uint32, int64, uint64) and any arithmetic (+, -, *).

cc @ezyang @gchanan @zou3519

**Comment by mruberry** [comment]
This issue reproduces on older PyTorch builds (like the one on Colab) but appears fixed in newer builds. See https://github.com/pytorch/pytorch/pull/35945 where I added a test for this behavior. 

Thanks for reporting this issue, @KiddoZhu!
