### ISSUE TITLE
Torch Version

### ISSUE THREAD

**Issue by shersoni610** [pytorch/pytorch#35271]
Hello,

I used pip to install pytorch ( stable 1.4 version). I followed the command on the web i.e.

pip install torch torchvision

However on executing, I see the versin 1.3.1
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.3.1'
>>> 

Why it is so?

Thanks

cc @ezyang @seemethere

**Comment by ptrblck** [comment]
Could you post the install log here and make sure to only use a single PyTorch installation in your current environment?

**Comment by albanD** [comment]
Also make sure that your conda is up to date as it might prevent you from getting the latest version of pytorch.

**Comment by prajjwal1** [comment]
You can also explicitly specify pytorch==1.4 while installing. This ensures that you get the version you require.

**Comment by albanD** [comment]
Closing this as it does not seem to be an issue with pytorch.
Feel free to re-open if you think it is a bug.

If you have more questions, please use the forum: https://discuss.pytorch.org/
