### ISSUE TITLE
torch.load(map_location="cuda") always indicates device0

### ISSUE THREAD

**Issue by kamo-naoyuki** [pytorch/pytorch#35289]
## ❓ Questions or feature request

- Repro

```python
import torch
torch.cuda.set_device(1)
model = torch.nn.Linear(10, 10)
model.cuda()
torch.save(model.state_dict(), "a.pth")

torch.cuda.set_device(2)
print(torch.load("a.pth")["weight"].device)
print(torch.load("a.pth", map_location="cuda")["weight"].device)
print(torch.load("a.pth", map_location=torch.device(torch.cuda.current_device()))["weight"].device)
```

```
cuda:1
cuda:0
cuda:2
```
(pytorch=1.4.0)

Is this expected? By intuition, map_location="cuda" should indicates the current device because tensor.to("cuda") implies the current device, but actually it always points to device=0.

If it's expected, in my understanding, the only way to specify the current device is "map_location=torch.device(torch.cuda.current_device())", but this seems too verbose. What is the correct way to load the state in the current GPU device?
~~Just using torch.device("cuda") looks fine.~~ torch.load(map_location=torch.device("cuda")) also points to device0.

cc @ngimel

**Comment by SsnL** [comment]
fwiw i can not reproduce on `1.5.0a0+0f0a5b1`

**Comment by kamo-naoyuki** [comment]
I found that this bug was fixed by https://github.com/pytorch/pytorch/commit/2f5eefe525d2602222117de8ab990ec495763cc1
