### ISSUE TITLE
torch.nn.functional.conv2d doesn't check filters shape

### ISSUE THREAD

**Issue by demikandr** [pytorch/pytorch#3528]
If I pass 2-dimension filter to conv2d then I get SegmentationFault.

Example:
```
import torch
import numpy as np
from torch.autograd import Variable

Z = Variable(torch.from_numpy(np.ones((100,100))).type(torch.FloatTensor).view(1,1,100,100))

filters = Variable(torch.from_numpy(np.array([[1,1,1],
                        [1,0,1],
                        [1,1,1]])).type(torch.FloatTensor))
N = torch.nn.functional.conv2d(Z,filters,padding=1).data.view(*Z.shape)` 

```

If I reshape filter to (1,1,100,100) - then everything is ok.

[Maybe it's worth it to add similar check for filters?](https://github.com/pytorch/pytorch/blob/b043a749191e32bf6c1d0fdee3170c45dce9d3d9/torch/nn/functional.py#L84)

**Comment by soumith** [comment]
the checks were added in master. will be part of the next release.
