### ISSUE TITLE
Interpolate Bug on Opset 11

### ISSUE THREAD

**Issue by briliantnugraha** [pytorch/pytorch#35287]
Hi guys, sorry to disturb you guys. 

I just want to mention that when I saved the model with torch.onnx.export or torch.onnx._export with opset_version=11, then I will "always" get incorrect model whenever the model contains pytorch tensor with "torch.FloatTensor" type. 

You could use this as reference to reproduce: https://discuss.pytorch.org/t/onnx-export-no-bilinear-interpolation-support/42527 (change the input x as torch.rand, and add opset_version=11 to it).

My only working solution is to downgrade the opset_version=10 and it takes me 2.5 days to figure it out (because we want to avoid warnings that will show up on opset_version=10 at first). Hope you guys could take a look at the export function on opset_version 11 so that other people will not stumble on a supposedly-unnecessary bug.

Thank you.
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS: Windows 10
 - Installed source: pip
 - Python version: 3.6.5
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: gtx1080
 - Any other relevant information: ONNX 1.6.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@briliantnugraha - can you add repro steps please?

**Comment by briliantnugraha** [comment]
Hi @spandantiwari, sure.

The exact problem comes from [this link](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/backbone/fpn.py#L64).

a. If I change it into this:
```
last_inner = inner_lateral #+ inner_top_down
results.insert(0, getattr(self, layer_block)(last_inner))
```

b. Make a new custom model (with only the backbone and FPN) like [this](https://github.com/briliantnugraha/custom_torchvision_model/blob/master/custom_resnext101.py#L40-#L55) on [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L12).


c. Do some prediction, and code export the model [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L239) with [this way]( https://discuss.pytorch.org/t/onnx-export-no-bilinear-interpolation-support/42527).

d. Save the image preprocessing  of the model input like [this](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L239):
```
img_preprocess = image_list.tensors.cpu().numpy()
np.save('input_pytorch.npy', img_preprocess)
```

e. Meanwhile, you could also try to print the prediction output mean of each tensor [here ](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L243) like this:

```
for i in range(len(predictions)): 
    print(i, predictions[i].mean())
```


e. Open the exported model with onnxruntime or onnx_tf like this:
```
import onnxruntime as rt
import numpy as np
img_preprocess  = np.load('input_pytorch.npy', allow_pickle=True)
sess = rt.InferenceSession(pathmodel)
input1 = sess.get_inputs()[0].name
outputs = sess.run(None, {input1: img_preprocess})
```

Then the output will be identical. Vice versa, If I don't do step **a**, then the output will be different.

**Comment by spandantiwari** [comment]
@briliantnugraha - can you try this in latest PyTorch 1.6. Many new ops and features have been added since 1.3. Also, please use the `torch.onnx.export` API instead of `_export` API. Finally there are some caveats for ONNX export related to tensor indexing. You can read about them on the ONNX doc page. https://pytorch.org/docs/stable/onnx.html. Please make sure that you are using supported indexing in your code.

If you still see an issue, let us know.

**Comment by garymm** [comment]
Closing due to lack of reply from @briliantnugraha . Please open another issue if this is still not working with latest PyTorch nightly.
