### ISSUE TITLE
`torch.einsum` allocates vastly different amount of memory depending on arguments order

### ISSUE THREAD

**Issue by philip-bl** [pytorch/pytorch#35299]
## 🐛 Bug

When doing einsum with the equation `'abcdefghijklmnopt,qrsp,qrso,qrsn,qrsm,qrsl,qrsk,qrsj,qrsi,qrsh,qrsg,qrsf,qrse,qrsd,qrsc,qrsb,qrsa->qrst'`, if I move the `abcdefghijklmnopt` argument to the front, pytorch allocates a significantly different amount of memory.

## To Reproduce

1. Run the following script
```python
import torch
big_core = torch.randn(
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    dtype=torch.float64, device="cuda", requires_grad=True
)
batches_of_small_cores = [
    torch.randn(8, 25, 25, 2, dtype=torch.float64, device="cuda", requires_grad=True)
    for _ in range(16)
]

result = torch.einsum(
    'qrsp,qrso,qrsn,qrsm,qrsl,qrsk,qrsj,qrsi,qrsh,qrsg,qrsf,qrse,qrsd,qrsc,qrsb,qrsa,abcdefghijklmnopt->qrst', *batches_of_small_cores, big_core
)

peak_allocated_GiB = torch.cuda.memory_stats()["allocated_bytes.all.peak"] / 1024 / 1024 / 1024
print(peak_allocated_GiB)
total_allocated_GiB = torch.cuda.memory_stats()["allocated_bytes.all.allocated"] / 1024 / 1024 / 1024
print(total_allocated_GiB)
# peak allocated GiB: 4.9                                                                                                                                                                            
# total allocated GiB: 4.9
```
2. Run the following script, which differs only in `einsum` arguments order.
```python
import torch
big_core = torch.randn(
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    dtype=torch.float64, device="cuda", requires_grad=True
)
batches_of_small_cores = [
    torch.randn(8, 25, 25, 2, dtype=torch.float64, device="cuda", requires_grad=True)
    for _ in range(16)
]

result = torch.einsum(
    'abcdefghijklmnopt,qrsp,qrso,qrsn,qrsm,qrsl,qrsk,qrsj,qrsi,qrsh,qrsg,qrsf,qrse,qrsd,qrsc,qrsb,qrsa->qrst', big_core, *batches_of_small_cores
)


peak_allocated_GiB = torch.cuda.memory_stats()["allocated_bytes.all.peak"] / 1024 / 1024 / 1024
print(peak_allocated_GiB)
total_allocated_GiB = torch.cuda.memory_stats()["allocated_bytes.all.allocated"] / 1024 / 1024 / 1024
print(total_allocated_GiB)
# peak allocated GiB: 6.1                                                                                                                                                                            
# total allocated GiB: 7.3
```
3. Notice that the amount of allocated memory is significantly different.

## Expected behavior

I expected the second script to allocate the same amount of memory as the first script.

## Environment

* PyTorch version: 1.4.0
* Is debug build: No
* CUDA used to build PyTorch: 10.1
* OS: Debian GNU/Linux 10 (buster)
* GCC version: (Debian 8.3.0-6) 8.3.0
* CMake version: version 3.13.4
* Python version: 3.8
* Is CUDA available: Yes
CUDA runtime version: 9.2.148
* GPU models and configuration: 
* GPU 0: Graphics Device
* GPU 1: GeForce GTX 1070
* Nvidia driver version: 418.74
* cuDNN version: Could not collect
* Versions of relevant libraries:
* [pip3] numpy==1.16.2
* [conda] mkl                       2020.0                      166  
* [conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
* [conda] torchvision               0.5.0                py38_cu101    pytorch

**Comment by albanD** [comment]
Hi,

I think this is expected behavior.
You can use projects like [optimized einsum](https://optimized-einsum.readthedocs.io/en/stable/) if you want to find good re-ordering.

**Comment by philip-bl** [comment]
If this is the expected behaviour, then I think it should be documented. Right now the documentation for `torch.einsum` doesn't say how it's computed.

**Comment by albanD** [comment]
We would be happy to accept a PR for better documentation on einsum's details.
