### ISSUE TITLE
Unit test failures are not reported as failure by Windows CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#35300]
For example    [pytorch_windows_vs2019_py36_cuda10.1_test2](https://app.circleci.com/pipelines/github/pytorch/pytorch/144817/workflows/c0ac3f91-edb1-4294-9cf4-aad70b6a89d0/jobs/4916119) reported to have finished successfully, but if one to grep the log, he can observe that number of tests have failed:
```
$ curl "https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4916119/output/103/0?file=true&allocation-id=5e79202a061b9e62ea99a5d1-0-build%2F29689000"|grep FAILED|grep '('
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3497k    0 3497k    0     0  2466k      0 --:--:--  0:00:01 --:--:-- 2466k
[  FAILED  ] BoundShapeInference.Int8QuantizeInferInputBackwards (1 ms)
[  FAILED  ] MetaprogrammingTest.FilterMap_onlyCopiesIfNecessary (0 ms)
[  FAILED  ] MetaprogrammingTest.FilterMap_onlyMovesIfNecessary_1 (0 ms)
[  FAILED  ] PowTest.LongTensorPowAllScalars (7 ms)
[  FAILED  ] RoiAlignTest.CheckCPUGPUEqual (148 ms)
```

cc @ezyang @gchanan @zou3519 @seemethere @peterjc123

**Comment by ezyang** [comment]
@malfet, I'm sure you know this already, but for others: Windows has this thing where you have to explicitly check for the error code of processes, it won't automatically quit the parent batch script (like `set -e` does in bash)

**Comment by peterjc123** [comment]
I'm pretty sure the exit code is checked. https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/win-test-helpers/test_libtorch.bat

**Comment by malfet** [comment]
@ezyang alas, I'm well aware of that
@peterjc123 there there were two issues with that script:
 - Test error code can be different than 1 (i.e. `if errorlevel 1` should have been `if not errorlevel 0`)
 - Apparently `exit` command just returns from the function rather than aborting the entire script.
After making those two changes errors are now properly reported

**Comment by peterjc123** [comment]
According to https://ss64.com/nt/errorlevel.html, if errorlevel 1 catches the situations that the exit code is greater than 1. And if not errorlevel 0 catches the sitiations that the exit code is lower than zero.

**Comment by malfet** [comment]
Good point, let me modify those scripts to use `if %errorlevel% NEQ 0` to cover both positive and negative error cases

**Comment by peterjc123** [comment]
@malfet This way, it is relying on a variable called errorlevel so when users do `set errorlevel=XXX` then it won't work as you expected. There are two options for fixing this:
1. Placing two kinds of if clauses
```cmd
python test.py
if errorlevel 1 exit /b 1
if not errorlevel 0 exit /b 1
```
2. Use or logic
```cmd
python test.py || exit /b 1
```

**Comment by malfet** [comment]
Filed follow up issues for disabled unit tests:
https://github.com/pytorch/pytorch/issues/35544
https://github.com/pytorch/pytorch/issues/35546
https://github.com/pytorch/pytorch/issues/35547
https://github.com/pytorch/pytorch/issues/35548
