### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by werkt** [pytorch/pytorch#35316]
## 🚀 Feature
Support a Bazel build of pytorch, equal in capacity to the cmake build

## Motivation

pytorch integration with bazel projects is substantially easier with a bazel ruleset and target surface. Additional uses include from-source build capacity, with unique global configurations like sanitizers.

## Pitch

bazel building and testing with clear instructions for using pytorch as an external repository without patches, direct from release/git commit.

## Alternatives

Using binary-only releases and rules_foreign_cc

## Additional context

This is currently in use at Uber ATG, where a successful build and test of cpu and gpu (nvcc) targets occurs on a daily basis. The changes required for this will be adapted, improved, and released as the starting point. Further work should be detailed in additional tasks.

**Comment by fenollp** [comment]
Thanks for https://github.com/pytorch/pytorch/pull/36011 :)

**Comment by 1e100** [comment]
This is great. Any plans for a *.whl build as well?

**Comment by jackshi0912** [comment]
When I try to add @pytorch//:torch as my dependency I get 
```
"error loading package '@pytorch//': Unable to find package for @pybind11_bazel//:build_defs.bzl: The repository '@pybind11_bazel' could not be resolved."
```

It's fine if I `bazel build :torch`. But It doesn't work if I link it remotely and `bazel build @pytorch//:torch`

Has anyone else ran into this issue?

**Comment by depthwise** [comment]
It probably wants you to define `@pybind11_bazel` in your workspace. This is usually dealt with by checking if a given dependency already exists in the parent workspace using `native.existing_rules()` and if it doesn't, introducing the dependency. Ex: https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl#L149

**Comment by jackshi0912** [comment]
If I add it to my WORKSPACE, the error becomes:
no such package 'tools/config': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package: /home/usr_name/projects/tools/config
It seems that bazel is trying to resolve dependency from my local workspace instead of pytorch's remote workspace. This is the first time I've ran into this issue. Anyone has any ideas on what could be going on?

**Comment by thymbahutymba** [comment]
I have the same issue even though [here](https://github.com/pytorch/pytorch/blob/master/WORKSPACE#L22) the dependency is already defined.

**Comment by ArekSredzki** [comment]
After working around the `pybind11_bazel` issue by defining the libraries manually, I was able to avoid the `tools/config` error by defining a dummy BUILD file in that directory within my project. That said, it's rather painful to specify all of the required dependencies, I wish this were a more seamless experience.

**Comment by diptanu** [comment]
Has anyone figured out how to include torch as an external bazel dependency to a bazel cpp project? @jackshi0912 were you able to solve the issue you reported? I am seeing the same issue.

**Comment by ezyang** [comment]
^- @dagitses

**Comment by bedbad** [comment]
Why is this closed?
