### ISSUE TITLE
[GitHub] Add pull request template

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#35319]
## Issue description
PyTorch makes use of issue templates, but does not use a pull request template. It might be a good idea to add one in order to help make sure all PRs have good, descriptive messages that make sense to contributors and users who need to dig through the commit history but may be unfamiliar with some parts of the code. It might be a good idea to combine this with the suggestions in #15059 for the addition of general contribution guidelines to `CONTRIBUTING.md`.

## Steps to Reproduce
1. Try to open a pull request.
2. Observe that the giant box for typing in the PR message is empty.

## System Info
N/A

**Comment by SplitInfinity** [comment]
cc: @suo @jamesr66a @eellison @tugrulince @zdevito @driazati 

Would appreciate feedback on this. It's super simple but maybe there's reason it hasn't been done already...

**Comment by eellison** [comment]
Not sure how this would work with ghstack, which at this point is a good portion of PRs.

**Comment by SplitInfinity** [comment]
I was wondering that myself. #35115 is one my `ghstack` PRs and my original commit message seems to have been appended below the list of all the PRs in the stack. I think that's fine, assuming it also gets committed by the ShipIt bot that way.

**Comment by albanD** [comment]
cc @soumith might be interested in this.

**Comment by SplitInfinity** [comment]
Just wanted to follow up on this. I have seen a variety of commit and PR messages, some to my liking, and some not, and it would great to have some standard of what's expected and what's not.

**Comment by soumith** [comment]
Adding a section to CONTRIBUTING sounds better, or a PR Template that is *extremely* simple, for example like literally having one line that says "Fixes ### " so that people don't forget to list the issues it fixes.

**Comment by SplitInfinity** [comment]
What about prompts for including an informative summary and test plan?
