### ISSUE TITLE
`pytorch_jni` is not available in nightly for OS X.

### ISSUE THREAD

**Issue by erip** [pytorch/pytorch#35342]
## 🐛 Bug

`pytorch_jni` is not available in pytorch-nightly.

## To Reproduce

1. `conda install -c pytorch-nightly pytorch -y`
1. `ls ~/miniconda3/envs/$CONDA_DEFAULT_ENV/lib/python3.6/site-packages/torch/lib`
1. Observe no `pytorch_jni` lib

## Expected behavior

pytorch_jni should be distributed with OS X in 1.5.0 builds according to [this](https://github.com/pytorch/java-demo/#setup)

## Environment

```
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.3
GCC version: Could not collect
CMake version: version 3.16.5

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0.dev20200324
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py36hfbe908c_0
[conda] mkl_fft                   1.0.15           py36h5e564d8_0
[conda] mkl_random                1.1.0            py36ha771720_0
[conda] pytorch                   1.5.0.dev20200324         py3.6_0    pytorch-nightly
```

## Additional context

Replicating `pytorch/java-demo` on OS X is currently not possible. 🙍‍♂

**Comment by ngimel** [comment]
cc @dreiss

**Comment by dreiss** [comment]
The JNI bindings are only distributed with the libtorch distribution, not conda.  At https://pytorch.org/get-started/locally/ , click on "C++/Java".

**Comment by erip** [comment]
So the site is out of date?

> MacOS binaries do not support Java. Support is only available for Linux. Download here for C++:
https://download.pytorch.org/libtorch/nightly/cpu/libtorch-macos-latest.zip

When I built from source I was able to generate the `libpytorch_jni.dylib`, but it didn't link appropriately with my code. That's a separate issue, though.

**Comment by dreiss** [comment]
@erip, yeah, I noticed that as well.  I'll probably ask them to update it with the 1.5 release.

**Comment by erip** [comment]
Got it. 😄 I assumed it would've needed to be built from source which is the route I took. Not sure if you want to keep this open for the 1.5.0 milestone or not. Feel free to close if this is clearly on your radar already.
