### ISSUE TITLE
[Discussion] Implement sth like torch_global_deps on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#35358]
## What is wrong there?
In https://discuss.pytorch.org/t/torch-cat-runtimeerror-error-in-loadlibrarya/71188/5, we can see that it is caused by the fact that `caffe2_nvrtc.dll` is not loaded during initialization. Currently, it will only happen when one trys to use CUDA in the official distribution of Python 3.8. It doesn't apply the changes to `PATH` for DLL search purposes, which makes  `caffe2_nvrtc.dll`  not able to found during runtime.

## Possible solutions
1. Load `caffe2_nvrtc.dll` when possible during initialization.  This is a quick fix, which is not so general.
2. Write the dependencies to a text file and load them one by one during initialization.
3. Load torch_global_deps during initialization. However, there is currently no easy way to force linking against unused shared libraries unless we use sth like `/INCLUDE:[symbol_name]`. Related PR: https://github.com/pytorch/pytorch/pull/34288.
4. Load all DLLs in the lib directory (Looks like a decent solution)

cc @peterjc123 @ezyang @malfet @EscapeZero @kostmo @soumith

**Comment by peterjc123** [comment]
I'll implement solution 4 because it seems the best one among all.

**Comment by ezyang** [comment]
sgtm

**Comment by peterjc123** [comment]
Failure in conda smoke tests:
```
Smoke testing imports
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\w\1\s\tmp_conda_3.8_232434\conda\envs\env_py3.8_cuda102_cudnn7_0_20200325\lib\site-packages\torch\__init__.py", line 77, in <module>
    ctypes.CDLL(dll)
  File "C:\w\1\s\tmp_conda_3.8_232434\conda\envs\env_py3.8_cuda102_cudnn7_0_20200325\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\w\1\s\tmp_conda_3.8_232434\conda\envs\env_py3.8_cuda102_cudnn7_0_20200325\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

**Comment by peterjc123** [comment]
Okay, this should be a false alarm because the build machines don't have GPUs on it.
