### ISSUE TITLE
Accessing Tensor::grad() in the C++ API for a non-leaf tensor should warn

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#35379]
## To Reproduce

In python, accessing the .grad attribute of a non-leaf tensor is a common pitfall users run into. For example:
```
x = torch.randn(3, requires_grad=True).cuda()
y = x ** 2
y.sum().backward()
x.grad
```
Luckily, this raises a nice warning in Python:
```
/scratch/rzou/pt/cudnn_double_Bwd/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "
```

In the C++ API, no warning happens: https://discuss.pytorch.org/t/very-confused-with-changes-in-autograd/74355 . It would be great for usability to add that warning.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @yf225

**Comment by yf225** [comment]
I believe it should be easy to add the warning https://github.com/pytorch/pytorch/blob/3645d9b8323e571411012672f894dc7c2318e377/torch/tensor.py#L745-L750 to https://github.com/pytorch/pytorch/blob/3645d9b8323e571411012672f894dc7c2318e377/c10/core/TensorImpl.cpp#L36-L45. @glaringlee Curious would you like to work on this task? Thanks!

**Comment by albanD** [comment]
If the warning is added in cpp, it should be removed from the python side right?

**Comment by yf225** [comment]
> If the warning is added in cpp, it should be removed from the python side right?

Yes I think so, because under the hood, Python `.grad` calls `._grad` which is bound to the C++ `.grad()`:
https://github.com/pytorch/pytorch/blob/7e327e1210b06b814a48e98ba38493e1d6b41998/torch/csrc/autograd/python_variable.cpp#L513
https://github.com/pytorch/pytorch/blob/7e327e1210b06b814a48e98ba38493e1d6b41998/torch/csrc/autograd/python_variable.cpp#L250-L255
