### ISSUE TITLE
Minor: docker build fails on submodule because of gitdir with absolute path name (problem with git v 2.7/2.8, fixed in git v 2.9)

### ISSUE THREAD

**Issue by utke1** [pytorch/pytorch#3542]
error message is 
```
Removing intermediate container dee615013001
Step 9/14 : COPY . .
 ---> 489276daed51
Step 10/14 : RUN git submodule update --init
 ---> Running in ca195ce4b458
fatal: Not a git repository: /data/work/Git/pytorch/.git/modules/torch/lib/gloo
Unable to find current revision in submodule path 'torch/lib/gloo'                                      
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 1
```
Reason:  pytorch was cloned with --recursive (as recommended) into ```/data/work/Git/```  and the submodule stores in file 
```/data/work/Git/pytorch/.git/modules/torch/lib/gloo/.git```
the absolute pathname as
```
gitdir: /data/work/Git/pytorch/.git/modules/torch/lib/gloo
```
But when 
```
COPY . . 
``` 
is run to copy  everything into ```/opt``` the absolute pathname won't match - hence the error.

This is apparently a know problem in git, see https://lwn.net/Articles/691223/  and fixed in v 2.9 
So may be you can just put a note on the page telling people about this to save them time.

**Comment by IssamLaradji** [comment]
I am getting the same error, so the solution is to install git v 2.9 ?

**Comment by utke1** [comment]
I don't think changing the dockerfile to adapt to a broken git logic makes sense. But yes,  git version 2.9 or newer should do the trick without any other changes.

**Comment by IssamLaradji** [comment]
thanks, so it might be a good idea to make the docker install `git` version >= 2.9. Using the current `DockerFile`, it seems that it installs an older version of `git`. Is it easy to change the docker to have it install version >= 2.9 ?

**Comment by happinesszl** [comment]
Hi, @utke1 . I changed the Dockerfile to install git 2.9 and git 2.19. But I still got a similar error message as follows. 

```
Step 9/12 : RUN git submodule update --init
 ---> Running in 673898e16516
fatal: not a git repository (or any of the parent directories): .git
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128
```

It would be great if you could give me some advice.

**Comment by zeyuanchen23** [comment]
Hi! I am trying to build an image on Google Cloud with this [dockerfile](https://raw.githubusercontent.com/pytorch/pytorch/master/docker/pytorch/Dockerfile) and got the same error. Any help will be appreciated! Basically I typed 

gcloud builds submit --tag  gcr.io/an_image_name

and got a fatal error:

Step 9/13 : RUN git submodule update --init
 ---> Running in 8c3312e41bdc
fatal: Not a git repository (or any of the parent directories): .git
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 128
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 128

**Comment by bafonso** [comment]
I am running into this and it does not get fixed with a git upgrade of the docker version or host machine (I fail to see why that would be).

**Comment by malfet** [comment]
Default version of git has long been updated and I can not repro it with git-2.31. Please do not hesitate to create a new issue if it happens again.
