### ISSUE TITLE
torch.svd() get error, w/ CUDA 9.0 w/o MAGMA

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#3543]
I got the following error using torch.svd(). It may because missing magma package with CUDA 9.0. Is there any work around? many thanks!
```bash
U,D,V = torch.svd(x)
RuntimeError: No CUDA implementation of 'gesvd'. Install MAGMA and rebuild cutorch (http://icl.cs.utk.edu/magma/) at /home/hangzhang/pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:280
```

**Comment by soumith** [comment]
@zhanghang1989 now we have magma for cuda90 with `conda install magma-cuda90 -c soumith`

**Comment by zhanghang1989** [comment]
awesome! thx

**Comment by tomahawk810** [comment]
Are there any solutions for this problem when using PyTorch on Windows?

It seems `magma-cuda90` is only available for linux.

**Comment by soulslicer** [comment]
I am not using conda, how do i do this?
