### ISSUE TITLE
Generate caffe2 LMDB file for imagenet 

### ISSUE THREAD

**Issue by qiangwang57** [pytorch/pytorch#35444]
Hi there,

I want to generate caffe2 LMDB for imagenet. I follow the advice in [this thread](https://github.com/facebookarchive/caffe2/issues/1755). Unfortunately, I cannot locate where the make_image_db is as I install pytorch 1.4 using conda as recommended on your website. I tried to build from source code but no luck at all. I wonder how I could use the script for the generation with conda installed pytorch?

Best wishes,

Chiang

**Comment by ngimel** [comment]
Please ask the questions on the forum, discuss.pytorch.org.
