### ISSUE TITLE
[QAT] RuntimeError: length of scales must equal to channel

### ISSUE THREAD

**Issue by wizardk** [pytorch/pytorch#35452]
## 🐛 Bug

PyTorch Version 1.4.0

just follow the tutorial [static_quantization_tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html)

in the line:
quantized_model = torch.quantization.convert(qat_model.eval(), inplace=False)

I got:
RuntimeError: length of scales must equal to channel

**Comment by wizardk** [comment]
my fault...

**Comment by ailias** [comment]
What is the fault? I met same error, but I don't know where the fault is.

**Comment by ckf1111** [comment]
I meet same error, could you tell me how to deal with it? Thanks!

**Comment by ckf1111** [comment]
@wizardk

**Comment by xieydd** [comment]
@ckf1111 @ailias @wizardk I meet same error, any solution?
