### ISSUE TITLE
[ONNX] ONNX generates a separated shape branch that may be buggy while handling group_norm

### ISSUE THREAD

**Issue by ersheng-ai** [pytorch/pytorch#35457]
## 🐛 Bug

ONNX generates a separated shape branch that may be buggy while handling group_norm

## To Reproduce

1. Find a CNN pytorch model that has group_norm layers
2. Export this model using torch.onnx.export
3. The exported onnx model would contain this structure:

![image](https://user-images.githubusercontent.com/62684483/77614832-db045e80-6f68-11ea-9bcd-df57f2cfd1b2.png)

## Expected behavior
The expected structure should be like this:
![image](https://user-images.githubusercontent.com/62684483/77614907-1010b100-6f69-11ea-895b-7f437b9c30b3.png)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): 
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: cuda 10.2, cudnn 7 or 8
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

Suggested code update:

Updating   torch/onnx/symbolic_opset9.py  could fix this issue.

Function needing update:
def group_norm(g, input, num_groups, weight, bias, eps, cudnn_enabled):
Replace the line
norm = g.op('Reshape', norm_reshaped, g.op("Shape", input))
with
norm = g.op('Reshape', norm_reshaped, g.op('Constant', value_t=torch.LongTensor(input_sizes)))

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ngimel** [comment]
Thank you for reporting the issue! Do you mind sending the PR to fix it?

**Comment by spandantiwari** [comment]
@ersheng-ai - why do you say this is wrong? AFAIK, these types of patterns are in there for a reason, most commonly to ensure that the model runs with different sizes of dynamic axes such as batch axis. Statically encoding the shape as a `Constant` won't do that. 

If you are seeing a case where the current export is not mathematically correct, let us know, and we will take a look.

**Comment by ersheng-ai** [comment]
`norm = g.op('Reshape', norm_reshaped, g.op('Constant', value_t=torch.LongTensor(input_sizes)))`
`input_sizes` contains all shape information from the input.
So can it be sure the output shape of after the second reshape is consistent with the input before the first reshape?

**Comment by ersheng-ai** [comment]
My second question is, even if I export the model with `**dynamic_axes=None**`, the second reshape will still be considered dynamic in the exported onnx. This would lead to some inconsistency problems.
Therefore, is there a solution considering both circumstances?
If I export the model as dynamic, the second reshape would be dynamic; otherwise, the second reshape should be a constant.
Thank you!

**Comment by spandantiwari** [comment]
I am not sure what you mean by "the second reshape will still be considered dynamic in the exported onnx". What ever input dimension size you bind to this, you can expect to get the correct result.

If you are seeing an incorrect result in some scenario, please share the repro with us.

**Comment by ersheng-ai** [comment]
I agree with you that the output is mathematically correct. My concern is whether property of the second reshape operation is consistent with `dynamic_axes` argument of `torch.onnx.export()`.

My suggestion:
`g.op('Reshape', norm_reshaped, g.op("Shape", input))` for `dynamic_axes!=None`
`g.op('Reshape', norm_reshaped, g.op('Constant', value_t=torch.LongTensor(input_sizes)))` for 'dynamic_axes==None`

**Comment by spandantiwari** [comment]
If you are setting `dynamic_axes=None`, then you should get the right output.

**Comment by spandantiwari** [comment]
Please feel free to re-open if there's still an issue.
