### ISSUE TITLE
After quantization the model, mobile pytorch raise exception

### ISSUE THREAD

**Issue by whl287** [pytorch/pytorch#35465]
## 🐛 Bug

when i follow the example of mobile pytorch example:
torch.quantization.convert(my_mobile_model)

when load this model with mobile for inference, report exception:
empty not implemented for TensorTypeSet(VariableTensorId, QuantizedCPUTensorId) (empty at /home/*********/pytorch1.4/pytorch/build_android/aten/src/ATen/Functions.h:3999)
(no backtrace available) 

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by z-a-f** [comment]
Can you, please, post a minimum example to reproduce the error. Are you following a specific example on the hub?

**Comment by vkuzo** [comment]
@whl287 , please let us know how to reproduce this, happy to take a look.  Closing until that time, and we can reopen if needed.
