### ISSUE TITLE
torch.isclose() undocumented

### ISSUE THREAD

**Issue by smonsays** [pytorch/pytorch#35471]
## 📚 Documentation
Is there a reason that `torch.isclose()` is undocumented or should it be added?

**Comment by mruberry** [comment]
Hey @smonsays! Good point. If it's behavior is consistent with NumPy's isclose then it'd be great to document it. We'd welcome a PR to document it if you validate its behavior, too.

**Comment by smonsays** [comment]
Okay, I can look into it in two weeks time!

**Comment by mruberry** [comment]
See https://github.com/pytorch/pytorch/issues/36462, which discusses a possible implementation of torch.isclose.

**Comment by mruberry** [comment]
This issue was addressed in https://github.com/pytorch/pytorch/pull/36456.
