### ISSUE TITLE
Custom Sampler 

### ISSUE THREAD

**Issue by FrancescaAlf** [pytorch/pytorch#35485]
I am new with pytorch! I am tryng to write a custom sampler to split my dataset into balanced batches during the training of my model. 

Here is my code:
"
import numpy as np
import torch
from torch.utils.data import Sampler

class MySamplerForBalancedBatches(Sampler):
    def __init__(self, data_source, n_classes, batch_size, steps):
        self.data_source = data_source
        self.n_classes = n_classes
        self.batch_size = batch_size
        self.steps= steps

    def __iter__(self):
       
        idx_cl=dict()
        elm=dict()
        elm4class=dict()
        
        target=np.asarray(self.data_source[:][1].tolist())
        
        for i in range(self.n_classes):
            idx_cl[i]=np.asarray(np.transpose(np.where(target==i)))
        
        for i in range(self.n_classes):    
            elm[i]=idx_cl[i].shape[0]
            elm4class[i]=math.floor(self.batch_size*(elm[i]/len(target)))

        while (elm4class[0]+elm4class[1]+elm4class[2]) < self.batch_size:
            elm4class[0]+=1

        for i in range(self.steps):      
            elm_cl_0=self.data_source[idx_cl[0][:elm4class[0]]] 
            elm_cl_1=self.data_source[idx_cl[1][:elm4class[1]]] 
            elm_cl_2=self.data_source[idx_cl[2][:elm4class[2]]]
            
            x_batch=torch.cat([elm_cl_0[0],elm_cl_1[0],elm_cl_2[0]],axis=0)
            y_batch=torch.cat([elm_cl_0[1],elm_cl_1[1],elm_cl_2[1]],axis=0)
            
            torch.manual_seed(50)
            x_batch=x_batch[torch.randperm(x_batch.size()[0])]
            x_batch=x_batch.resize_((500,12))
            torch.manual_seed(50)
            y_batch=y_batch[torch.randperm(y_batch.size()[0])]
            y_batch=y_batch.resize_((500,1))

            idx_cl[0]=np.delete(idx_cl[0],np.arange(elm4class[0]))
            idx_cl[1]=np.delete(idx_cl[1],np.arange(elm4class[1]))
            idx_cl[2]=np.delete(idx_cl[2],np.arange(elm4class[2]))
            
            batch = [x_batch,y_batch]
            yield batch
            
n_classes=3
batch_size=500
steps=int(Y_train.shape[0]/batch_size)
train_dataset = TensorDataset(X_train,y_train)
sampler= MySamplerForBalancedBatches(train_dataset, n_classes, batch_size,steps) 
train_loader = DataLoader(train_dataset, shuffle=False, sampler=sampler)

"
I am not sure it is working as I expect, when I try to check what the function DataLoader gives me back by using:

"for sample in train_loader:
    print(sample[0])
    break"

I have this error:
<IndexError: tensors used as indices must be long, byte or bool tensors>

Does anyone know how to solve this problem? 
Thank you

**Comment by mruberry** [comment]
Hey @francescaalf! Welcome to PyTorch! Sorry to hear you're having some trouble.

This is a great question for our forums: https://discuss.pytorch.org/. Please try asking your question there.
