### ISSUE TITLE
PyTorch complex support has NumPy incompatible functions

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#35494]
## 🐛 Bug

The new complex number support introduces APIs that are incompatible with NumPy. Some of these functions existed in PyTorch 1.4, but they were practically useless and undocumented.

I'm concerned that this is going to make our life difficult going forward as we try to balance backwards compatibility with NumPy support. In general, we shouldn't be releasing new APIs that are incompatible with NumPy without good reasons.

Here are some examples I found with a few minutes of testing:

`Tensor.real()` is a function but `ndarray.real` is a property

```python
>>> torch.randn(10, dtype=torch.complex64).real
<function Tensor.real>
>>> torch.randn(10, dtype=torch.complex64).numpy().real
array([ 0.1262403 , -0.40131333,  0.52708787, -0.10931669,  1.5780342 ,
       -0.17833038,  0.4660201 , -0.35434407,  0.73025763,  0.44405413],
      dtype=float32)
```

`torch.real()` (and `Tensor.real()`) returns a complex-type Tensor, but `np.real` (and `ndarray.real`) return floating-point type arrays:

```python
>>> x = torch.randn(10, dtype=torch.complex64)
>>> torch.real(x).dtype
torch.complex64
>>> np.real(x.numpy()).dtype
dtype('float32')
```

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by colesbury** [comment]
cc @gchanan

**Comment by vadimkantorov** [comment]
About function vs property: if it always returns a view, maybe property is okay. If it always clones or will allow custom arguments (like `copy=False`), then a function is more flexible

**Comment by colesbury** [comment]
@vadimkantorov this issue isn't about the merits of functions vs. properties, but about matching the NumPy API. We often prefer functions over properties for the reasons you mention, but those reasons are outweighed by a desire to match the NumPy API, or at minimum, at least not prevent us from matching NumPy's API in the future.

We have an opportunity to address this before the 1.5 release goes out. It's probably too big a task to change their functionality/return type to match NumPy, but @gchanan suggests that we can deprecate the functions. We can also adjust the documentation. For example, we may want to remove torch.real/imag and Tensor.real/imag from the 1.5 docs.

**Comment by vadimkantorov** [comment]
> without good reasons.

I was only pointing out that copy behavior or wishing to control it may be "good reasons" for diverging API in this particular case or at least must be considered when deciding the destiny of these functions.

> , but those reasons are outweighed by a desire to match the NumPy API
I see

NumPy API is old. While it's important to be compatible to make it easier for users, I just hope it doesn't prevent PyTorch from introducing well-designed, new, performant APIs. NumPy often lacks APIs flexible enough to do inplace or copy/allocation-avoiding APIs, so perfect compatibility should hopefully not strain PyTorch design too much...

**Comment by ezyang** [comment]
Having `real` avoid allocation is blocked on #33950 which is being worked on atm.

**Comment by vadimkantorov** [comment]
A few related questions: will torch support conversion from `(*, 2)` to complex? What about `(*, 2, *)` what if that 2 dimension is not contiguous? Will conversion copy? Or will `.real` copy?

**Comment by zasdfgbnm** [comment]
Related: https://github.com/pytorch/pytorch/issues/35517

**Comment by mruberry** [comment]
This PR fixes the worst of it (by disallowing real and imag on complex): https://github.com/pytorch/pytorch/pull/35560.

**Comment by vincentqb** [comment]
Related: #35532

**Comment by anjali411** [comment]
fixed in [39033](https://github.com/pytorch/pytorch/issues/39033)
