### ISSUE TITLE
Quantized Conv1d  and ConvTransposeXd implementation should migrate to aten

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#35515]
Currently the Conv1d uses Conv2d. However, the profiler shows `at::conv2d` instead of the `at:conv1d`. Need to move the implementation to the C++ side. Basically this could be done by implementing the packing that would unsqueeze/squeeze the weight and the forward that does the same with the input.

Similarly, ConvTransposeXd uses the ConvXd under the hood -- need to move the implementation to the C++ domain in order for the profiler to show the correct `aten` ops

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jamesr66a** [comment]
I don't quite understand. It makes sense that conv2d would show up, but I would imagine that's as a sub-frame of conv1d. Could you provide an example to further explain what's going on here?
