### ISSUE TITLE
libtorch1.3.1 under centos7

### ISSUE THREAD

**Issue by cheneyfan** [pytorch/pytorch#35518]
--BUG-------------------------------------------------------------------------------------------------------
../../../../lib/libtorch.so: undefined reference to `gloo::getCudaPCIBusID(int)'
../../../../lib/libtorch.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

--libgloo_cuda.a--------------------------------------------------------------------------------------------
[root@TENCENT64 ~/torchInference/TorchInference/3rdparty/pytorch/build]# nm /usr/local/lib/libgloo_cuda.a |grep "getCudaPCIBusID"
                 U _ZN4gloo15getCudaPCIBusIDEi
                 U _ZN4gloo15getCudaPCIBusIDEi
                 U _ZN4gloo15getCudaPCIBusIDEi
                 U _ZN4gloo15getCudaPCIBusIDEi
0000000000000038 b _ZGVZN4gloo15getCudaPCIBusIDB5cxx11EiE6busIDs
00000000000004ef T _ZN4gloo15getCudaPCIBusIDB5cxx11Ei
00000000000009e8 t _ZSt11__addressofIZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_EUlvE_EPS5_RS5_
00000000000009f6 t _ZSt13__invoke_implIvZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
00000000000009a9 t _ZSt7forwardIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_EOT_RNSt16remove_referenceIS2_E4typeE
00000000000009b7 t _ZSt8__invokeIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS3_DpOS4_
000000000000087d t _ZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_
0000000000000014 b _ZZN4gloo15getCudaPCIBusIDB5cxx11EiE4once
0000000000000020 b _ZZN4gloo15getCudaPCIBusIDB5cxx11EiE6busIDs
00000000000002e4 t _ZZN4gloo15getCudaPCIBusIDB5cxx11EiENKUlvE_clEv
0000000000000832 t _ZZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv
000000000000086c t _ZZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE0_cvPFvvEEv
000000000000080c t _ZZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
000000000000085c t _ZZSt9call_onceIZN4gloo15getCudaPCIBusIDB5cxx11EiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
[root@TENCENT64 ~/torchInference/TorchInference/3rdparty/pytorch/build]# nm /usr/local/lib/libgloo_cuda.a |grep "EnforceNotMet"
                 U _ZN4gloo13EnforceNotMetC1EPKciS2_RKSs
0000000000000000 W _ZN4gloo13EnforceNotMetD0Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD1Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD2Ev
0000000000000000 n _ZN4gloo13EnforceNotMetD5Ev
                 U _ZTIN4gloo13EnforceNotMetE
                 U _ZTVN4gloo13EnforceNotMetE
                 U _ZN4gloo13EnforceNotMetC1EPKciS2_RKSs
0000000000000000 W _ZN4gloo13EnforceNotMetD0Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD1Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD2Ev
0000000000000000 n _ZN4gloo13EnforceNotMetD5Ev
                 U _ZTIN4gloo13EnforceNotMetE
                 U _ZTVN4gloo13EnforceNotMetE
                 U _ZN4gloo13EnforceNotMetC1EPKciS2_RKSs
0000000000000000 W _ZN4gloo13EnforceNotMetD0Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD1Ev
0000000000000000 W _ZN4gloo13EnforceNotMetD2Ev
0000000000000000 n _ZN4gloo13EnforceNotMetD5Ev
                 U _ZTIN4gloo13EnforceNotMetE

--libtorch.so------------------------------------------------------------------------------------------------
[root@TENCENT64 ~/torchInference/TorchInference/3rdparty/pytorch/build]# nm lib/libtorch.so |grep "EnforceNotMet"
                 U _ZN3c1018ThrowEnforceNotMetEPKciS1_RKSsPKv
                 U _ZN4gloo13EnforceNotMetC1EPKciS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
0000000006271f40 T _ZN4gloo13EnforceNotMetC1EPKciS2_RKSs
0000000006271f40 T _ZN4gloo13EnforceNotMetC2EPKciS2_RKSs
0000000002668630 t _ZN4gloo13EnforceNotMetD0Ev
0000000002667ff0 t _ZN4gloo13EnforceNotMetD1Ev
0000000002667ff0 t _ZN4gloo13EnforceNotMetD2Ev
0000000006271dc0 T _ZNK4gloo13EnforceNotMet3msgEv
0000000006271db0 T _ZNK4gloo13EnforceNotMet4whatEv
000000002286a4d8 V _ZTIN4gloo13EnforceNotMetE
00000000077ff9a0 V _ZTSN4gloo13EnforceNotMetE
000000002286a4f0 V _ZTVN4gloo13EnforceNotMetE
[root@TENCENT64 ~/torchInference/TorchInference/3rdparty/pytorch/build]# nm lib/libtorch.so |grep "getCudaPCIBusID"
                 U _ZN4gloo15getCudaPCIBusIDEi
[root@TENCENT64 ~/torchInference/TorchInference/3rdparty/pytorch/build]#

--enviroment---------------------------------------------------------------------------------------------
gcc 7.3
cmake 3.16
make 4.3
torch1.3.1
cuda-10.0
cudnn-7.6
binutils-2.26
tensorrt-7

--try-------------------------------------------------------------------------------------------------------
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")
both in torch&gloo cmakefile， still fail with same error！！！！

**Comment by mruberry** [comment]
Hey @cheneyfan, sorry to hear you're having an issue. Could you elaborate on how you're hitting this issue, exactly? Are you trying to build from source or link against libtorch?

**Comment by cheneyfan** [comment]
i want to build libtorch.so from source，but the bug shows when use libtorch.so building “torch_shm_manager” and in my own test case。


[ 95%] Linking CXX executable ../../../../bin/torch_shm_manager
make[2]: Entering directory '/root/torchInference/TorchInference/3rdparty/pytorch/build'
Scanning dependencies of target torch_python
../../../../lib/libtorch.so: undefined reference to `gloo::getCudaPCIBusID(int)'
../../../../lib/libtorch.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/build.make:98: bin/torch_shm_manager] Error 1

**Comment by mruberry** [comment]
What instructions are you using to build libtorch from scratch?

**Comment by cheneyfan** [comment]
git clone https://github.com/pytorch/pytorch
cd pytorch 
git submodule sync
git submodule update --init --recursive

checkout 1.3.1

cmake & make

**Comment by mruberry** [comment]
We don't typically recommend using that approach. See https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst. 

By following the Github instructions to build PyTorch normally you'll also build lib torch. Would you try the approaches in that doc?

**Comment by cheneyfan** [comment]
thx，i will try @mruberry

**Comment by cheneyfan** [comment]
[ 87%] Linking CXX executable ../bin/generate_proposals_op_gpu_test
/root/torchInference/TorchInference/3rdparty/pytorch/build_libtorch/build/lib/libtorch.so: undefined reference to `gloo::getCudaPCIBusID(int)'
/root/torchInference/TorchInference/3rdparty/pytorch/build_libtorch/build/lib/libtorch.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/generate_proposals_op_gpu_test] Error 1
gmake[1]: *** [caffe2/CMakeFiles/generate_proposals_op_gpu_test.dir/all] Error 2
[ 87%] Linking CXX executable ../bin/generate_proposals_op_util_nms_gpu_test
/root/torchInference/TorchInference/3rdparty/pytorch/build_libtorch/build/lib/libtorch.so: undefined reference to `gloo::getCudaPCIBusID(int)'
/root/torchInference/TorchInference/3rdparty/pytorch/build_libtorch/build/lib/libtorch.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/generate_proposals_op_util_nms_gpu_test] Error 1
gmake[1]: *** [caffe2/CMakeFiles/generate_proposals_op_util_nms_gpu_test.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 23, in <module>
    rerun_cmake=True, cmake_only=False, cmake=CMake())
  File "/root/torchInference/TorchInference/3rdparty/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    cmake.build(my_env)
  File "/root/torchInference/TorchInference/3rdparty/pytorch/tools/setup_helpers/cmake.py", line 334, in build
    self.run(build_args, my_env)
  File "/root/torchInference/TorchInference/3rdparty/pytorch/tools/setup_helpers/cmake.py", line 142, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 2.

@mruberry

**Comment by mruberry** [comment]
What command did you run to get that? python setup.py build?

**Comment by cheneyfan** [comment]
mkdir build_libtorch && cd build_libtorch
python ../tools/build_libtorch.py

**Comment by cheneyfan** [comment]
mkdir build_libtorch && cd build_libtorch
python ../tools/build_libtorch.py

And in CMakeLists.txt， add：
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")

**Comment by mruberry** [comment]
Would you try the second approach?

Why are you editing CMakeLists.txt, by the way?

**Comment by cheneyfan** [comment]
because local gcc is 7.3.
second approach？

**Comment by mruberry** [comment]
Yes, this one:

python setup.py build

ls torch/lib/tmp_install # output is produced here
ls torch/lib/tmp_install/lib/libtorch.so # of particular interest

Huh, I'm not familiar with manipulating CMAKE when compiling with gcc7.

**Comment by cheneyfan** [comment]
it‘s ok：’
   mkdir build_libtorch && cd build_libtorch
   python ../tools/build_libtorch.py

but fail when use libtorch.so， i have linked 
        ${TORCH_INCLUDE_DIRS}/../lib/libc10.so 
        ${TORCH_INCLUDE_DIRS}/../lib/libc10_cuda.so
        ${TORCH_INCLUDE_DIRS}/../lib/libtorch.so

bug as follows：

CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `at::cat(c10::ArrayRef<at::Tensor>, long) [clone .constprop.371]':
infer_test.cpp:(.text+0x981): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `TestTorchInfer(std::string const&, std::string const&, std::string const&, int, int, int, std::string const&)':
infer_test.cpp:(.text+0x186c): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
infer_test.cpp:(.text+0x1ff3): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
infer_test.cpp:(.text+0x2353): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
infer_test.cpp:(.text+0x25ee): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o:infer_test.cpp:(.text+0x28ac): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `c10::Symbol::dimname(std::string const&)':
infer_test.cpp:(.text._ZN3c106Symbol7dimnameERKSs[_ZN3c106Symbol7dimnameERKSs]+0x56): undefined reference to `c10::Symbol::fromQualString(std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `c10::Device::validate()':
infer_test.cpp:(.text._ZN3c106Device8validateEv[_ZN3c106Device8validateEv]+0x37e): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
infer_test.cpp:(.text._ZN3c106Device8validateEv[_ZN3c106Device8validateEv]+0x62e): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `c10::intrusive_ptr<c10::intrusive_ptr_target, c10::detail::intrusive_target_default_null_type<c10::intrusive_ptr_target> >::reclaim(c10::intrusive_ptr_target*)':
infer_test.cpp:(.text._ZN3c1013intrusive_ptrINS_20intrusive_ptr_targetENS_6detail34intrusive_target_default_null_typeIS1_EEE7reclaimEPS1_[_ZN3c1013intrusive_ptrINS_20intrusive_ptr_targetENS_6detail34intrusive_target_default_null_typeIS1_EEE7reclaimEPS1_]+0x2cd): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `std::string c10::str<char [21], c10::Layout>(char const (&) [21], c10::Layout const&)':
infer_test.cpp:(.text._ZN3c103strIJA21_cNS_6LayoutEEEESsDpRKT_[_ZN3c103strIJA21_cNS_6LayoutEEEESsDpRKT_]+0x237): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o: In function `c10::TensorOptions::computeTensorTypeId() const':
infer_test.cpp:(.text._ZNK3c1013TensorOptions19computeTensorTypeIdEv[_ZNK3c1013TensorOptions19computeTensorTypeIdEv]+0x139): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/infer_test.cpp.o:infer_test.cpp:(.text._ZNK3c1013TensorOptions19computeTensorTypeIdEv[_ZNK3c1013TensorOptions19computeTensorTypeIdEv]+0x346): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
CMakeFiles/infer_test.dir/image.cpp.o: In function `torch::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)':
image.cpp:(.text._ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE[_ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE]+0xa0): undefined reference to `c10::Symbol::fromQualString(std::string const&)'
image.cpp:(.text._ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE[_ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE]+0x376): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
image.cpp:(.text._ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE[_ZN5torch5emptyEN3c108ArrayRefIlEERKNS0_13TensorOptionsENS0_8optionalINS0_12MemoryFormatEEE]+0x55c): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/image.cpp.o: In function `at::Tensor::permute(c10::ArrayRef<long>) const':
image.cpp:(.text._ZNK2at6Tensor7permuteEN3c108ArrayRefIlEE[_ZNK2at6Tensor7permuteEN3c108ArrayRefIlEE]+0x34d): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/image.cpp.o: In function `std::vector<c10::IValue, std::allocator<c10::IValue> >::vector(std::initializer_list<c10::IValue>, std::allocator<c10::IValue> const&)':
image.cpp:(.text._ZNSt6vectorIN3c106IValueESaIS1_EEC2ESt16initializer_listIS1_ERKS2_[_ZNSt6vectorIN3c106IValueESaIS1_EEC5ESt16initializer_listIS1_ERKS2_]+0x23a): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
image.cpp:(.text._ZNSt6vectorIN3c106IValueESaIS1_EEC2ESt16initializer_listIS1_ERKS2_[_ZNSt6vectorIN3c106IValueESaIS1_EEC5ESt16initializer_listIS1_ERKS2_]+0x3fb): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
CMakeFiles/infer_test.dir/image.cpp.o:image.cpp:(.text._ZN3c106detail19boxAndCallBoxedFuncIN2at6TensorEJRKS3_NS_6ScalarEEE4callEPFvPNS_14OperatorKernelEPSt6vectorINS_6IValueESaISB_EEES9_S5_S6_[_ZN3c106detail19boxAndCallBoxedFuncIN2at6TensorEJRKS3_NS_6ScalarEEE4callEPFvPNS_14OperatorKernelEPSt6vectorINS_6IValueESaISB_EEES9_S5_S6_]+0x358): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
../../bin/libinfer_lib.a(torch_infer.cpp.o): In function `TorchInfer::LoadModel(std::string const&)':
torch_infer.cpp:(.text+0x8b): undefined reference to `torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&)'
torch_infer.cpp:(.text+0x7aa): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0xd96): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x109f): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x12ef): undefined reference to `c10::Error::msg() const'
../../bin/libinfer_lib.a(torch_infer.cpp.o): In function `TorchInfer::Forward(std::vector<c10::IValue, std::allocator<c10::IValue> > const&, bool)':
torch_infer.cpp:(.text+0x18d6): undefined reference to `torch::jit::script::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::string, c10::IValue, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&)'
torch_infer.cpp:(.text+0x1c84): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x21eb): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x241f): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x2917): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
torch_infer.cpp:(.text+0x2b7d): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(torch_infer.cpp.o):torch_infer.cpp:(.text+0x2cb5): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
../../bin/libinfer_lib.a(trt_api_infer.cpp.o): In function `TrtApiInfer::LoadModule(std::string const&, std::vector<c10::IValue, std::allocator<c10::IValue> > const&)':
trt_api_infer.cpp:(.text+0x1faf): undefined reference to `torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&)'
trt_api_infer.cpp:(.text+0x20fb): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
trt_api_infer.cpp:(.text+0x21cb): undefined reference to `c10::Error::msg() const'
../../bin/libinfer_lib.a(trt_api_infer.cpp.o): In function `TrtApiInfer::Forward(std::vector<c10::IValue, std::allocator<c10::IValue> > const&)':
trt_api_infer.cpp:(.text+0x37d8): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
trt_api_infer.cpp:(.text+0x3a73): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_infer.cpp.o): In function `c10::TensorTypeSet::has(c10::TensorTypeId) const':
trt_api_infer.cpp:(.text._ZNK3c1013TensorTypeSet3hasENS_12TensorTypeIdE[_ZNK3c1013TensorTypeSet3hasENS_12TensorTypeIdE]+0x143): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_infer.cpp.o): In function `_ZNKR3c106IValue8toTensorEv':
trt_api_infer.cpp:(.text._ZNKR3c106IValue8toTensorEv[_ZNKR3c106IValue8toTensorEv]+0x1d3): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
trt_api_infer.cpp:(.text._ZNKR3c106IValue8toTensorEv[_ZNKR3c106IValue8toTensorEv]+0x303): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_infer.cpp.o):trt_api_infer.cpp:(.text._ZNKR3c106IValue12toTensorListEv[_ZNKR3c106IValue12toTensorListEv]+0x18b): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow
../../bin/libinfer_lib.a(trt_api_torch_parser.cpp.o): In function `torch::ones(c10::ArrayRef<long>, c10::TensorOptions const&)':
trt_api_torch_parser.cpp:(.text._ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE[_ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE]+0x97): undefined reference to `c10::Symbol::fromQualString(std::string const&)'
trt_api_torch_parser.cpp:(.text._ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE[_ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE]+0x39e): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
trt_api_torch_parser.cpp:(.text._ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE[_ZN5torch4onesEN3c108ArrayRefIlEERKNS0_13TensorOptionsE]+0x58e): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_torch_parser.cpp.o): In function `c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >::retain_()':
trt_api_torch_parser.cpp:(.text._ZN3c1013intrusive_ptrINS_6ivalue6ObjectENS_6detail34intrusive_target_default_null_typeIS2_EEE7retain_Ev[_ZN3c1013intrusive_ptrINS_6ivalue6ObjectENS_6detail34intrusive_target_default_null_typeIS2_EEE7retain_Ev]+0xc6): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_torch_parser.cpp.o): In function `_ZNKR3c106IValue8toObjectEv':
trt_api_torch_parser.cpp:(.text._ZNKR3c106IValue8toObjectEv[_ZNKR3c106IValue8toObjectEv]+0x19b): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
trt_api_torch_parser.cpp:(.text._ZNKR3c106IValue8toObjectEv[_ZNKR3c106IValue8toObjectEv]+0x2ce): undefined reference to `c10::Error::Error(c10::SourceLocation, std::string const&)'
../../bin/libinfer_lib.a(trt_api_torch_parser.cpp.o):trt_api_torch_parser.cpp:(.text._ZNK2at6Tensor1tEv[_ZNK2at6Tensor1tEv]+0x30e): more undefined references to `c10::Error::Error(c10::SourceLocation, std::string const&)' follow

**Comment by mruberry** [comment]
Progress! 

Did you take a look at the example here and would you try to link an example program against libtorch.so?

https://tutorials.pytorch.kr/advanced/cpp_frontend.html

At this point this question may also be more appropriate for our forums, see related thread:

https://discuss.pytorch.org/t/issues-linking-with-libtorch-c-11-abi/29510/13

And checkout this doc, too: 

https://pytorch.org/cppdocs/installing.html

**Comment by cheneyfan** [comment]
it's ok without set CXX ABI for gcc

**Comment by mruberry** [comment]
Glad to haer it.
