### ISSUE TITLE
invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

### ISSUE THREAD

**Issue by kmj970311** [pytorch/pytorch#35538]
from os.path import basename, join

import torch.optim as optim
from torch.utils.data import DataLoader

import torchvision.transforms as T

from cellcount.utils import (ChunkSampler, ImageWithMask, train,
                             get_val_example, gpu_dtype, save_epoch_image)
from cellcount.models import FPN
from cellcount.losses import fpn_loss

BBBC = 'synthetic-cell-images-and-masks-bbbc005-v1/'

transform = T.Compose([T.Scale((256)), T.ToTensor()])

NUM_TRAIN = 1000
NUM_VAL = 200

train_data = ImageWithMask(join(BBBC, 'BBBC005_v1_ground_truth/'),
                           transform=transform)
train_data.imgs = [(join(BBBC, 'BBBC005_v1_images/BBBC005_v1_images/%s') % basename(i), i)
                   for i, _ in train_data.imgs]

loader_train = DataLoader(train_data, batch_size=2,
                          sampler=ChunkSampler(NUM_TRAIN, 0))
loader_val = DataLoader(train_data, batch_size=2,
                        sampler=ChunkSampler(NUM_VAL, NUM_TRAIN))

x_var, y_var = get_val_example(loader_val)
_, _, h, w = x_var.size()

fpn = FPN(h, w).type(gpu_dtype)

lr = 5e-4
epochs = 1000
for i in range(epochs):
    print('epoch: %s' % i)
    if i > 0 and (i % 20 == 0):
        lr *= .95
    optimizer = optim.Adam(fpn.parameters(), lr=lr, weight_decay=0.)
    train(loader_train, fpn, fpn_loss, optimizer)
    if (i % 20 == 0):
        save_epoch_image(x_var, y_var, fpn, i)

IndexError                                Traceback (most recent call last)
<ipython-input-1-ee4b0e275e6e> in <module>
     42         lr *= .95
     43     optimizer = optim.Adam(fpn.parameters(), lr=lr, weight_decay=0.)
---> 44     train(loader_train, fpn, fpn_loss, optimizer)
     45     if (i % 20 == 0):
     46         save_epoch_image(x_var, y_var, fpn, i)

~/MJ/cellcount/utils.py in train(loader_train, model, loss_fn, optimizer, num_epochs, print_every)
    115             loss = loss_fn(scores, y_var)
    116             if (t + 1) % print_every == 0:
--> 117                 print('t = %d, loss = %.4f' % (t + 1, loss.data[0]))
    118 
    119             optimizer.zero_grad()

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by agolynski** [comment]
Could you give more details? What line produced the error here?

**Comment by kmj970311** [comment]
> Could you give more details? What line produced the error here?

train(loader_train, fpn, fpn_loss, optimizer)
This line!
Should I add module that I made?

**Comment by agolynski** [comment]
maybe replace
loss.data[0] by loss.item()?

**Comment by kmj970311** [comment]
> maybe replace
> loss.data[0] by loss.item()?

Thank you It works ! (-:
