### ISSUE TITLE
Complex exponential unexpected behaviour

### ISSUE THREAD

**Issue by PanTheRiceMan** [pytorch/pytorch#35532]
## 🐛 Bug

PyTorch shows unexpected results when using the exponential of a complex tensor.

## To Reproduce
```
from math import pi
import torch
a = torch.arange(4, dtype=torch.float32)/3*pi
z = a.type(torch.complex64)
print(z)
zz = z*1j
print(z)
zzexp = zz.exp()
print(zzexp)

```
>>> tensor([     (0.0000 + 0.0000j),      (1.0472 + 0.0000j),
>>>                  (2.0944 + 0.0000j),      (3.1416 + 0.0000j)],
>>>            dtype=torch.complex64)
>>> tensor([ (0.0000 + 0.0000j),  (0.0000 + 1.0472j),  (0.0000 + 2.0944j),
         (0.0000 + 3.1416j)], dtype=torch.complex64)
>>> tensor([        (1.0000 + 0.0000j),         (1.0000 + 0.8660j),
>>>                 (1.0000 + 0.8660j),         (1.0000 - 0.0000j)],
>>>            dtype=torch.complex64)

## Expected behavior
```
import numpy as np
b = np.arange(4, dtype=torch.float32)/3*pi
z_numpy = np.exp(1j*b)
print(z_numpy)
```

>>> [ 1.        +0.0000000e+00j  0.49999997+8.6602545e-01j
>>> -0.50000006+8.6602539e-01j -1.        -8.7422777e-08j]

The emaginary part seems to be calculated correctly. Just the real part stays at one. It should be the cosine of the imaginary part in this case, to match the behavior of numpy.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Manjaro Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.17.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 440.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchaudio==0.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.0.15           py38ha843d7b_0  
[conda] mkl_random                1.1.0            py38h962f231_0  
[conda] pytorch                   1.5.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.6.0.dev20200326      py38_cu101    pytorch-nightly

cc @ezyang @anjali411 @dylanbespalko

**Comment by aayn** [comment]
I can reproduce this on my machine with similar configuration. Though I think you meant `b = np.arange(4, dtype=np.float32)/3*pi`. I'd like to take this issue up.

**Comment by aayn** [comment]
This issue is also there on the `master` branch version.

**Comment by aayn** [comment]
I have a question. When I call `torch.exp(x)` where `x` is a `Tensor` with `dtype=torch.complex64`, where is the `exp` function/method that is called? Is it currently from [`aten/src/ATen/cpu/vec256/vec256_complex_float.h`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_float.h)? This is for the CPU case.
@ezyang @anjali411 @dylanbespalko @agolynski

**Comment by dylanbespalko** [comment]
@aayn,

When you call exp() there are two functions that actually get called:
 1. The regally std::exp() function.
 2. The Vec256::exp() function in [aten/src/ATen/cpu/vec256/vec256_complex_float.h)](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_float.h)

How it works is the Intel CPU has hw accelerated Single-Instruction Multiple-Data (SIMD) registers that operate on 256 bits of data. In the case of a 32-bit float, it operates on (8 numbers) * (32-bit) = 256 bit. To test the code, you should do the following:

```python
a = torch.tensor([0 + 0j, 1 + 1j, 2 + 2j, 3 + 3j, 4 + 4j, 5 + 5j, 6 + 6j, 7 + 7j, 8 + 8j], dtype=torch.float)
b = torch.exp(a)  
```

This will call Vec256::exp() for indices 0-7, and std::exp() for index 8.

**Comment by aayn** [comment]
@dylanbespalko 

There's probably something wrong with the [exp function](https://github.com/pytorch/pytorch/blob/860790de8805856342a1bee37103184f47a0c26d/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L244). I tried a couple of simple testcases that fail with the current implementation, but pass if you change the `exp` function to just be `return map(std::exp)`. Should I submit a PR with just those testcases first?

In your example, `__m256 values` in the `Vec256` class will just store `[0, 0, 1, 1, 2, 2, 3, 3]`, right?

I am currently trying to understand AVX. I had a few questions regarding how `_mm256_permute_ps` works, but I'll explore myself before asking them here. If you could point me to resources (other than Intel documentation) for the same, I'd appreciate that. Thanks!

**Comment by dylanbespalko** [comment]
@aayn,

Yes, I wrote this function, but I'm currently a bit stressed out and  tied to a version of PyTorch that is a few months old, making it difficult to fix this. I would appreciate if you could submit a PR to fix this. Using `map(std::exp)` will fix the problem, but will eliminate the hw acceleration. 

I'm aware that tensor flow uses `tf.exp(x + iy) = tf.exp(x) * (tf.cos(y) + 1j * tf.sin(y))`, but maybe I messed up a `permute()` operation.  Also beware of the subtle difference between `permute_pd` and `permute_ps()`. I always found it easy to implement `complex_double` first. This is the best link for[ AVX functions](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=5016,4158&text=_mm256_permute&techs=AVX2)

**Comment by aayn** [comment]
@dylanbespalko 
Thanks for the link! I'll get that PR asap. Does it make sense to submit another PR of just the failing testcases (no C++ changes) first?

**Comment by dylanbespalko** [comment]
@aayn,

Not sure what you mean here, but any PR you submit must pass all test cases or else the CI will fail. They won't accept any PR that fails CI, so I think you need to change the C++ code and the test cases in the same PR.

**Comment by aayn** [comment]
@dylanbespalko 

I fixed the bug (in just `complex_double` first)! You were missing a permute operation. I need to go for a class now, but I'll submit a PR shortly.
