### ISSUE TITLE
caffe2 BoundShapeInference.Int8QuantizeInferInputBackwards fails on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#35544]
From [pytorch_windows_vs2017_14.16_py36_cuda10.1_test2](https://app.circleci.com/pipelines/github/pytorch/pytorch/147364/workflows/bd161994-54d9-4e71-af7e-20c99084d5de/jobs/4973123)
```
[ RUN      ] BoundShapeInference.Int8QuantizeInferInputBackwards
unknown file: error: C++ exception with description "[enforce fail at ..\caffe2\opt\bound_shape_inferencer.cc:223] schema. 
(no backtrace available)" thrown in the test body.
[  FAILED  ] BoundShapeInference.Int8QuantizeInferInputBackwards (0 ms)
```

cc @peterjc123

**Comment by vladimir-aubrecht** [comment]
@malfet Is this test also executed somewhere in GitHub Actions? Or just Circle CI? (I tried to find it in GitHub Actions workflows/jobs and cannot see it executed anywhere ...)

**Comment by malfet** [comment]
@vladimir-aubrecht , this test is part of Caffe2 (see https://github.com/pytorch/pytorch/blob/b23cfe54657eddb002fa0174fb0ecce1e625d26a/caffe2/opt/bound_shape_inference_test.cc#L1 ), but as we've stopped shipping PyTorch with caffe2 almost a year ago, I guess one can ignore this failure.
