### ISSUE TITLE
nn.Module subclasses don't typecheck due to lack of contravariant input types

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#35566]
## ❓ Questions and Help

I've asked about this in the [discussion forum](https://discuss.pytorch.org/t/how-to-correctly-annotate-subclasses-of-nn-module/74317), but got no answer so far. Although it not has been up for that long, I think other _users_ of PyTorch won't be able to help me out. Thus, I'm asking this here. If you disagree, please tell me [how to proceed](https://discuss.pytorch.org/t/meta-what-can-i-do-if-i-cant-get-support-in-this-forum/74514).

---

I'm trying to annotate subclasses of `nn.Module` inline in `python3.6`, but for now I unable to get it to work. For my project I create an abstract subclass of `nn.Module`

```python
from typing import Any
from torch import nn


class Foo(nn.Module):
    def forward(self, *input: Any, **kwargs: Any) -> Any:
        pass
```

Running [`mypy`](http://mypy-lang.org/) on this succeeds. In a second step I add a more concrete class

```python
import torch


class Bar(Foo):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        pass
```

Now `mypy` errors with

```
error: Signature of "forward" incompatible with supertype "Foo"
error: Signature of "forward" incompatible with supertype "Module"
```

while pointing to `forward()` of `Bar` both times. I'm aware that this is valid error since `Bar` violates the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle). I don't think it is intended for every subclass of `nn.Module` to have that exact signature, but I'm puzzled how to get around this.

Looking at the stub of `nn.Module`

https://github.com/pytorch/pytorch/blob/d6377b7cef0c7bc822df80eedd86689bc51e83d2/torch/nn/modules/module.pyi.in#L12-L15

I think this paragraph is related, but for now I was unable to comprehend it. Can you provide me with a minimal example how to do this?

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect
```
### Extendend Environment

```
Package           Version
----------------- -------
mypy              0.770  
mypy-extensions   0.4.3  
typed-ast         1.4.1  
typing-extensions 3.7.4.1
```

cc @ezyang

**Comment by ezyang** [comment]
Try

```
class Foo(nn.Module[torch.Tensor]):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        pass
```

**Comment by pmeier** [comment]
Running `mypy` on

```python
import torch
from torch import nn


class Foo(nn.Module[torch.Tensor]):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        pass
```

results in the same error

```
error: Signature of "forward" incompatible with supertype "Module"
```

**Comment by ezyang** [comment]
Ah, it turns out the return type is working correctly; it's the input types that mismatch. This typechecks for me:

```
import torch
from torch import nn
from typing import Any


class Foo(nn.Module[torch.Tensor]):
    def forward(self, *input: Any, **kwargs: Any) -> torch.Tensor:
        pass
```

I guess this means we may need to parametrize Module covariantly on the input parameter types as well; Any isn't going to cut it. I wonder if there is a way to write this sort of "function like" object natively in mypy.

**Comment by malmaud** [comment]
Hmm, as I think back to this, I'm not sure there's any valid typing possible given that `forward`'s usage  in PyTorch really does violate Liskov substitutability, as pmeier says. Consider

```python
def f(x: Module):
   return x("hi")

x = nn.Linear(...)
f(x)
```

I can't think of any way of adding type parameters to `Module` such that `f(x)` type-checks but `x("hi")` doesn't.

**Comment by bartosz319** [comment]
If `Foo.forward` is meant to be abstract, just leave it undefined.

```py
import torch
from torch import nn

class Foo(nn.Module):
    pass

class Bar(Foo):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.tensor(3.5)
```

But if you need to have an implementation of `forward` in `Foo`, you can put the annotations for `Foo` in a `.pyi` file (inspired by [this](https://github.com/pytorch/pytorch/blob/d6377b7cef0c7bc822df80eedd86689bc51e83d2/torch/nn/modules/module.pyi.in#L24)):

```py
# foo.py
from torch import nn

class Foo(nn.Module):
    def forward(self, *input, **kwargs):
        print("Foo.forward called")
```

```py
# foo.pyi
from typing import Callable, TypeVar
from torch import nn

T_co = TypeVar("T_co", covariant=True)

class Foo(nn.Module[T_co]):
    forward: Callable[..., T_co]
```

```py
# bar.py
import torch
from foo import Foo

class Bar(Foo):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.tensor(3.5)
```

But if you need to have an implementation of `forward` in `Foo` and you want to use inline annotations, then this is the best I could think of:

```py
from typing import Any, Callable, Generic, TypeVar, TYPE_CHECKING
import torch
from torch import nn

T_co = TypeVar("T_co", covariant=True)

if TYPE_CHECKING:
    ModuleGeneric = nn.Module[T_co]
else:
    ModuleGeneric = nn.Module

class Foo(ModuleGeneric, Generic[T_co]):
    def _real_forward(self, *input: Any, **kwargs: Any) -> Any:
        print("Foo.forward called")

    forward: Callable[..., T_co] = _real_forward

class Bar(Foo):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.tensor(3.5)
```

But it's not a perfect solution. For example, `Foo().forward.__name__` is `_real_forward`.

Note: I've only tested these with PyTorch 1.5.

**Comment by pmeier** [comment]
> If Foo.forward is meant to be abstract, just leave it undefined.

Running

```python
import torch
from torch import nn

class Foo(nn.Module):
    pass

class Bar(Foo):
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return torch.tensor(3.5)
```
through `mypy` still errors with 

```
error: Signature of "forward" incompatible with supertype "Module"
```

**Comment by ezyang** [comment]
This seems tough. I'll say that one of our goals was to make all of our annotations inline (for ease of maintenance). Maybe this is a reason to not do that.

**Comment by malmaud** [comment]
Here's the relevant section from mypy: https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides. 

I'm worried that whether the annotations are inline or not is irrelevant. Fundamentally, the design of `nn.Module.forward` violates Liskov substitution and so is incompatible with being typechecked under the semantics of PEP 484.

**Comment by pmeier** [comment]
@malmaud 

> incompatible with being typechecked under the semantics of PEP 484.

If I understand it correctly, annotating forward with `forward: Callable[..., T_co]` tells `mypy` to not check the input arguments at all. Unfortunately, this syntax is only available in a stub.

So, we can could get it type checked but not with inline annotations.

**Comment by malmaud** [comment]
What would happen if we just didn't have any type annotations on `nn.forward`? Would that be substantially different then having that generic annotation in a stub?

**Comment by rgommers** [comment]
Maybe you've all seen this and I'm stating the obvious, but the original bug report here was for 1.4.0. With 1.5.0 the examples above typecheck just fine, because of commit e3d40f857b7 which changes the annotation to `forward: Callable[..., T_co]`.

Removing the `# type: ignore` comments from `def forward(...` for `Module` subclasses works as well, so those can all be moved inline. So it looks to me like we can keep the current `module.pyi.in` as is, move to inline annotations for other stubs in `nn/modules/` and call it good?

**Comment by ezyang** [comment]
Sounds good to me!
