### ISSUE TITLE
DISABLED test_debug_info (__main__.DistAutogradTestWithSpawn)

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#35575]
Saw 2 instances on test, pytorch_linux_xenial_py3_6_gcc5_4_test

https://app.circleci.com/pipelines/github/pytorch/pytorch/147576/workflows/ee6a83a9-b219-488c-8224-b1d8404ad9f1/jobs/4978490

https://app.circleci.com/pipelines/github/pytorch/pytorch/147327/workflows/b0fd43f7-d18a-4b47-a6c2-8c881c1cac63/jobs/4972041

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by agolynski** [comment]
Some debug info from the logs that might be useful:

Mar 27 06:57:08   test_debug_info (__main__.DistAutogradTestWithSpawn) ... Process process 3:
...
Mar 27 06:57:08 RuntimeError: Could not find autograd context with id: 844424930131968
...
Mar 27 06:58:11 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:712)
Mar 27 06:58:11 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:712)
Mar 27 06:58:11 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:712)
Mar 27 06:58:11 ok (1.119s)
Mar 27 06:58:12   test_error_in_context (__main__.DistAutogradTestWithSpawn) ... [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 27 06:58:12 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 27 06:58:12 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41
Mar 27 06:58:12 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41

**Comment by nolifenameless** [comment]
debug info exist in these links below,
https://app.circleci.com/pipelines/github/pytorch/pytorch/147327/workflows/b0fd43f7-d18a-4b47-a6c2-8c881c1cac63/jobs/4972041/steps
https://app.circleci.com/pipelines/github/pytorch/pytorch/147327/workflows/b0fd43f7-d18a-4b47-a6c2-8c881c1cac63/jobs/4972041/tests
would we disable them all or keep one of them?

**Comment by mrshenli** [comment]
Closing this issue, as `DistAutogradTestWithSpawn` is now part of `TensorPipe` and `ProcessGroup` RPC tests. This issue disables nothing for the new test structure.
