### ISSUE TITLE
zero CUDA device with libtorch nightly

### ISSUE THREAD

**Issue by divideconcept** [pytorch/pytorch#35604]
## 🐛 Bug

The latest nightly of libtorch does not find any CUDA device (Windows).

## To Reproduce

1. Download the latest nightly https://download.pytorch.org/libtorch/nightly/cu101/libtorch-win-shared-with-deps-latest.zip
2. Create a C++ project pointing to the nightly libs and headers
3. Execute std::cout << "CUDA DEVICE COUNT: " << torch::cuda::device_count() << std::endl;
4. The returned device_count is zero, and no tensor or model can be moved to CUDA without crashing the program

This works as expected with 1.4 stable https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.4.0.zip

## Environment

Windows 10, RTX 2060, MSVC 2017

**Comment by peterjc123** [comment]
If you didn't construct the VS project using CMake, then you'll need to add `/INCLUDE:"?warp_size@cuda@at@@YAHXZ"` to the linker options manually.

**Comment by divideconcept** [comment]
Thanks that worked ! Might be worth mentioning it in the doc ? I didn't have to do that with 1.4

**Comment by divideconcept** [comment]
BTW is there a similar flag I should set on macOS and Linux ?

**Comment by peterjc123** [comment]
Yeah. Alternatively, I'll try to add the [comment pragma](https://docs.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=vs-2019#linker) so that you don't have to do this manually.

**Comment by ailzhang** [comment]
Closing via https://github.com/pytorch/pytorch/issues/35604#issuecomment-605489498
