### ISSUE TITLE
Naming conflict of `test_api` in Windows release builds for wheels

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#35602]
## 🐛 Bug

The target name `test_api` is used by a test executable in mkldnn.
```
    CMake Error at test/cpp/api/CMakeLists.txt:39 (add_executable):
      add_executable cannot create target "test_api" because another target with
      the same name already exists.  The existing target is an executable created
      in source directory
      "C:/w/1/s/windows/pytorch/third_party/ideep/mkl-dnn/tests/gtests/api".  See
      documentation for policy CMP0002 for more details.
    
    
    CMake Error at test/cpp/api/CMakeLists.txt:41 (target_link_libraries):
      The plain signature for target_link_libraries has already been used with
      the target "test_api".  All uses of target_link_libraries with a target
      must be either all-keyword or all-plain.
    
      The uses of the plain signature are here:
    
       * third_party/ideep/mkl-dnn/cmake/utils.cmake:45 (target_link_libraries)
```

## To Reproduce

1. set BUILD_TEST=1
2. python setup.py build

## Expected behavior

CMake configure passes.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): v1.5.0-rc2
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.x
 - CUDA/cuDNN version: 9.2 / 10.1 / 10.2 / NA
 - GPU models and configuration: Tesla M60
 - Any other relevant information:

## Additional context

We should not build tests for mkldnn.

**Comment by JerrikEph** [comment]
I have encountered the same error, how do I resolve it?

**Comment by peterjc123** [comment]
@JerrikEph It is actually mkldnn that is out of sync. So running the following script should help.
```bash
git submodule sync
git submodule update --init --recursive
```

**Comment by RafayAK** [comment]
> @JerrikEph It is actually mkldnn that is out of sync. So running the following script should help.
> 
> ```shell
> git submodule sync
> git submodule update --init --recursive
> ```

Thanks a lot for this I posted this on the PyTorch Discussions but to no avail, and now I've finally understood the reason of this error. Thanks a lot.
Surprisingly, for me th build works out if I build from the master repo, but changing to a different version always fails.
