### ISSUE TITLE
Does the build_pytorch.bat has the option to build  the Dlls and Libs without CAFFE2? 

### ISSUE THREAD

**Issue by yoshihingis** [pytorch/pytorch#35610]
This is not the bug report , only question.
[Question]
Does the build_pytorch.bat has the option to build  the Dlls and Libs without CAFFE2? 

[Detail]
 Thanks for your support , I could build the Dlls ,the LIbs and etc. for libtorch Ver1.4.
But I don't need the CAFFE2 ,only need "Torch".

 The "build_pytorch,py" has the option "BUILD_CAFFE2_OPS=0" to disable build of Caffe2 operators.
 Does the build_pytorch.bat has same option?

 

cc @peterjc123

**Comment by peterjc123** [comment]
Nope. But you can do `set BUILD_CAFFE2_OPS=0` before calling `build_pytorch.bat`.

**Comment by yoshihingis** [comment]
Dear peterjc123

Thank you for your advide.
I built libtorch accoriding with your advice, but it seemed like that the CAFFE2 was built normally.

I want your opinions.


[My procedure is as below.]
1.Open the Command prompt as Administrator. 
2.chcp 65001
3.git clone https://github.com/pytorch/builder.git
4.cd builder/windows
5.set BUILD_PYTHONLESS=1
6.set PYTORCH_REPO=pytorch
7.set PYTORCH_BRANCH=v1.4.0
8.set BUILD_CAFFE2_OPS=0
9.build_pytorch.bat 101 1.4.0 0.5.0

[Results]
I am now building ,the message indicates "caffe2/Camkefiles..._XX.
it seems like that CAFFE2 is building now  

[the messages in command prompt]
.
.
.

[444/1492] Building NVCC (Device) object caffe2/CMakeFiles...__/aten/src/THC/torch_generated_THCReduceApplyUtils.cu.obj
THCReduceApplyUtils.cu
THCReduceApplyUtils.cu
[445/1492] Building NVCC (Device) object caffe2/CMakeFiles....dir/__/aten/src/THC/torch_generated_THCStorageCopy.cu.obj
THCStorageCopy.cu
THCStorageCopy.cu
[446/1492] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCTensor.cu.obj
THCTensor.cu
THCTensor.cu
[447/1492] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCStorage.cu.obj
THCStorage.cu
THCStorage.cu
[448/1492] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/torch_generated_THCSleep.cu.obj
THCSleep.cu
THCSleep.cu 

Regards,

**Comment by peterjc123** [comment]
@yoshihingis Could you please search for `BUILD_CAFFE2_OPS` in the log?

**Comment by peterjc123** [comment]
@yoshihingis I didn't see anything wrong there because the target name is caffe2 and you can see the file that compiled that is actually from aten.

**Comment by yoshihingis** [comment]
Dear peterjc123

OK.
After finished to building, I will check the contents of this build and the build.log,

Regards,

**Comment by yoshihingis** [comment]
Dear peterjc123

Thank you for your advide.
I built libtorch accoriding with your advice, but it seemed like that the CAFFE2 was built normally.

Der peterjc123,

I checked the option "set BUILD_CAFFE2_OPS=0 " to build the Dlls&Libs  of libtorch without CAFFE2.
I built the Dlls & Libs of CPU version libtorch Ver1.4 , because CUDA version needs very long time to build.

I have two versions of libtorch-win-shared-with-deps-1.4.0.zip .
First version , I set "set BUILD_CAFFE2_OPS=0 " ,and in another version, I set "set BUILD_CAFFES_OPS=1".

After Two zip files was built , I compared both contents by the free software "Winmerge".
 there were differences in only 9 files.
1.libotch\bin\protoc.exe
2.libtorch\lib\c10.dll
3.libtorch\lib\caffe2_module_test_dynamic.dll
4.libtorch\lib\clog.lib
5.libtorch\lib\cpuinfo.lib
6.libtorch\lib\libprotobuf-lite.lib
7.libtroch\lib\libprotobuf.lib
8.libtorch\lib\libprotoc.lib
9.libtorch\lib\torch.dll

※Please refer to attatched Excel file．

[Question]
Is this result reasonable with setting of "BULD_CAFFE2_OPS" ?

[My procedure is as below.]
 1.Open the Command prompt as Administrator.
 2.chcp 65001
 3.git clone https://github.com/pytorch/builder.git
 4.cd builder/windows
 5.set BUILD_PYTHONLESS=1
 6.set PYTORCH_REPO=pytorch
 7.set PYTORCH_BRANCH=v1.4.0
 8.set set NO_CUDA=1
 9.set BUILD_CAFFE2_OPS=0 or set BUILD_CAFFE2_OPS=1
10.build_pytorch.bat cpu 1.4.0 0.5.0

Regards,
[wCAFFE2_woCAFFE2_cmp.xlsx](https://github.com/pytorch/pytorch/files/4418883/wCAFFE2_woCAFFE2_cmp.xlsx)

**Comment by peterjc123** [comment]
That's expected. `BUILD_CAFFE2_OPS=0` turns off the build process for sources under `caffe2/operators/`. If you are talking about removing all the sources in `caffe2/`, then I don't think it's possible.

**Comment by yoshihingis** [comment]
Dear peterjc123
Thank you for your reply.
I could understand the function of "BUILD_CAFFES_OPS=0".
Regards,
