### ISSUE TITLE
qconfig in torch.nn.qat.modules.linear is not used.

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#35634]
I suppose the passed-in qconfig should overwrite the existing one.

the `qconfig = mod.qconfig` makes no sense for me.

https://github.com/pytorch/pytorch/blob/618c6214aaab1fc478ac576bee8d212b7c35f482/torch/nn/qat/modules/linear.py#L37-L55

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
not sure why do we have this argument, we should probably remove that
