### ISSUE TITLE
nn.Module hooks ignore kwargs

### ISSUE THREAD

**Issue by zjplab** [pytorch/pytorch#35643]
To reproduce:

https://gist.github.com/zjplab/1d7b2a22a13d63f3ad83a59563cc4141

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ezyang @SsnL @zou3519 @gqchen

**Comment by ndronen** [comment]
👍

**Comment by albanD** [comment]
Yes all the keyword arguments are ignored for all the hooks (forward_pre, forward and backward).
We should update the doc to reflect this.

**Comment by ndronen** [comment]
Why not support kwargs instead?

**Comment by albanD** [comment]
I'm not sure how would that look like to ensure that it does not break existing code.
All the hooks today expect the `input` as a tuple of all the `*args` given to module.
Changing this signature would break a lot of existing code.

Another issue is that it is not clear what would be a natural return value for these hooks to support modifications.
Finally, for the backward hooks, how should the keyword arguments be handled?

**Comment by albanD** [comment]
Re-opened the issue to discuss if we want to add support for kwargs for nn.Module hooks. And if so how given the issues mentioned above.

**Comment by ndronen** [comment]
Thanks for re-opening it. I'll respond with a strawman proposal in a few days.

**Comment by ndronen** [comment]
I really dislike the try/except block in `forward`. It would be straightforward, and possibly more performant, to inspect the signature of the hook at the time it is registered and use that knowledge to invoke the hook without causing a `TypeError` to be raised by hooks written for the current version of the hook API.

**Comment by albanD** [comment]
I feels like the simplest here would be to add a new arg to `register_forward_hook` and `register_forward_pre_hook`: `with_kwargs=False`.
Based on this, the signature of the hook is `out = hook(mod, args, out)` or `args, kwargs = hook(mod, args, kwargs, out)` for the first and `args = hook(mod, args)` or `args, kwargs = hook(mod, args, kwargs)` for the second.
Does that sound good?

**Comment by gchanan** [comment]
This seems like a reasonable request.

@albanD's proposal above seems reasonable, although I don't think we are married to anything in particular.

**Comment by ndronen** [comment]
I agree. The hook signatures make much more sense and `with_kwargs=False` does, too.

**Comment by albanD** [comment]
cc @jbschlosser the proposal above might be better than the `register_pre_forward_hook_with_hook()` that we talked about? What do you think?

**Comment by jbschlosser** [comment]
> cc @jbschlosser the proposal above might be better than the `register_pre_forward_hook_with_kwargs()` that we talked about? What do you think?

Yes, I like the flag better than a new function.

**Comment by Padarn** [comment]
Hey all, any update on the plans for this one?

**Comment by ndronen** [comment]
If you poke around in the current docs for hook registration, I think they now say that kwargs are just not supported.

**Comment by Padarn** [comment]
thanks @ndronen do you happen to have any reference? I couldn't find anything

**Comment by ndronen** [comment]
Take a look at https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.register_forward_pre_hook.
![Screenshot_20220720-202700](https://user-images.githubusercontent.com/21194/180116829-f335e655-7a04-4aaa-9a77-6f13ebb4fd8b.png)

**Comment by Padarn** [comment]
Oh sorry 'not' supported. Yes that is my current understanding.

**Comment by albanD** [comment]
If you're interesting in sending a PR that implements https://github.com/pytorch/pytorch/issues/35643#issuecomment-620033102 I can review/merge it!

**Comment by Padarn** [comment]
Sure! I'll have a look this weekend

**Comment by Padarn** [comment]
I opened a draft about this here: https://github.com/pytorch/pytorch/pull/82042 

Currently, there is a lot of work left to do (especially in docs/tests, of which I've done none), but thought I'd open it as a draft to get feedback on the implementation direction.
