### ISSUE TITLE
Queue get function stucks when using multiprocessing 

### ISSUE THREAD

**Issue by cocoakang** [pytorch/pytorch#35660]
## 🐛 Bug

 When getting Tensors from a multiprocessing queue, the program will be stuck randomly.

## To Reproduce

Here is a snippet of code to reproduce this problem.  The program will be stuck randomly.
```python
import torch
import time
from torch.multiprocessing import set_start_method,Queue

try:
    set_start_method('spawn')
except RuntimeError:
    pass

def f(nproc,q,generate_device_list):
    while True:
        training_data_map = {
            "multiview_lumitexel_list":[torch.randn(50,24576,1,device=generate_device_list[i%len(generate_device_list)]) for i in range(8)],
            "rendered_slice_diff_gt_list":[torch.randn(50,24576,1,device=generate_device_list[i%len(generate_device_list)]) for i in range(8)],
            "rendered_slice_spec_gt_list":[torch.randn(50,384,1,device=generate_device_list[i%len(generate_device_list)]) for i in range(8)],
            "normal_label":torch.randn(50,3,device=generate_device_list[0]),
            "input_positions":torch.randn(50,3,device=generate_device_list[0]),
            "geometry_normal":torch.randn(50,3,device=generate_device_list[0])
        }
        # print("[PROCESS] before putting...")
        q.put(training_data_map)
        # print("[PROCESS] put one item")
        # time.sleep(0.5)

if __name__ == '__main__':
    torch.random.manual_seed(2333)
    q = Queue(100)
    generate_device_list = [torch.device("cuda:0"),torch.device("cuda:1"),torch.device("cuda:2"),torch.device("cuda:3")]
    training_device = torch.device("cuda:0")

    ctx = torch.multiprocessing.spawn(f, args=(q,generate_device_list), nprocs=1, join=False, daemon=True)
    time.sleep(30.0)
    print(q.qsize())
    counter = 0
    while True:
        print("[MAIN] before getting...")
        batch_data = q.get()

        input_positions = batch_data["input_positions"].to(training_device,copy=True)
        multiview_lumitexel_list = [a.to(training_device,copy=True) for a in batch_data["multiview_lumitexel_list"]]
        rendered_slice_diff_gt_list = [a.to(training_device,copy=True) for a in batch_data["rendered_slice_diff_gt_list"]]
        rendered_slice_spec_gt_list = [a.to(training_device,copy=True) for a in batch_data["rendered_slice_spec_gt_list"]]
        normal_label = batch_data["normal_label"].to(training_device,copy=True)
        geometry_normal = batch_data["geometry_normal"].to(training_device,copy=True)

        del batch_data
        print("[MAIN] got one item:{}".format(counter))
        counter+=1

    ctx.join()
```
## Expected behavior

The main process will be stuck randomly, i.e. counter value cannot be anticipated when stuck. I expect that the program runs forever, but it will hang.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 418.74
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] torch                     1.4.0                     <pip>
[conda] torchvision               0.5.0                     <pip>

**Comment by dvolgyes** [comment]
Maybe unrelated, but i got hangs / issues on Ubuntu when i ran out of file descriptors.
(Too many open files.) Since in unix almost everything is a file (network sockets, shared memory, etc.),
i needed to increase the max number of file descriptors.
You can query it:
```ulimit -n```
And change it:
```ulimit -n 8192```

Do you get hangs with increased limit too?
(I couldn't decide if it was pytorch's fault, mine, or just python was slow with cleanup.)

**Comment by cocoakang** [comment]
> Maybe unrelated, but i got hangs / issues on Ubuntu when i ran out of file descriptors.
> (Too many open files.) Since in unix almost everything is a file (network sockets, shared memory, etc.),
> i needed to increase the max number of file descriptors.
> You can query it:
> `ulimit -n`
> And change it:
> `ulimit -n 8192`
> 
> Do you get hangs with increased limit too?
> (I couldn't decide if it was pytorch's fault, mine, or just python was slow with cleanup.)

I think it is caused by pytorch itself in my case, some deadlock things, because after I upgraded my pytorch version to 1.5, everything went fine.
Thank you anyway!

**Comment by dvolgyes** [comment]
Well, if it disappeared after 1.5, could you check it with 1.6? I guess if it works, this ticket could be renamed like "prior v1.5 ..." (in case somebody got stuck with old version)  and then you could close it.
