### ISSUE TITLE
torch::cat has no documentation?

### ISSUE THREAD

**Issue by JesperLindberg** [pytorch/pytorch#35667]
## 📚 Documentation

torch::cat is missing documentation? Following this link, where I searched for the documentation only returned other functions where torch::cat are begin used in the body?

https://pytorch.org/cppdocs/search.html?q=torch%3A%3Acat&check_keywords=yes&area=default

cc @brianjo @mruberry @yf225 @glaringlee

**Comment by glaringlee** [comment]
@JesperLindberg 
torch::cat is actuall at::cat. You can check the doc for at::cat at here:
https://pytorch.org/cppdocs/search.html?q=cat&check_keywords=yes&area=default

The usage is same as torch.cat, so there is not much there at the moment

**Comment by mruberry** [comment]
Closing because @glaringlee has answered this question.
