### ISSUE TITLE
Function request: unravel_index

### ISSUE THREAD

**Issue by KiaraGrouwstra** [pytorch/pytorch#35674]
## 🚀 Feature

This function would mirror `np.unravel_index`; a basic Torch implementation and todo to formally expose such an implementation were previously added [here](https://github.com/pytorch/pytorch/blob/c73e97033a3aef97a5685588ea014d54a5cc11cc/torch/testing/__init__.py#L41-L49).
A few more suggestions for implementation may be found at this [SO thread](https://stackoverflow.com/questions/53212507/how-to-efficiently-retrieve-the-indices-of-maximum-values-in-a-torch-tensor).

## Motivation

As per the SO thread, functions like `argmax` now return a flat index, while sometimes one may want an unravel (/ multi-dimensional) index.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @rgommers @heitorschueroff

**Comment by teichert** [comment]
Another implementation is presented in [this post](https://discuss.pytorch.org/t/how-to-do-a-unravel-index-in-pytorch-just-like-in-numpy/12987).

**Comment by francois-rozet** [comment]
I wrote a `torch` implementation of `numpy.unravel_index`:

```python
def unravel_index(
    indices: torch.LongTensor,
    shape: Tuple[int, ...],
) -> torch.LongTensor:
    r"""Converts flat indices into unraveled coordinates in a to target shape.

    This is a `torch` implementation of `numpy.unravel_index`.

    Args:
        indices: A tensor of indices, (*, N).
        shape: The targeted shape, (D,).

    Returns:
        unravel coordinates, (*, N, D).
    """

    shape = torch.tensor(shape)
    indices = indices % shape.prod()

    coord = torch.zeros(indices.size() + shape.size(), dtype=int)

    for i, dim in enumerate(reversed(shape)):
        coord[..., i] = indices % dim
        indices = indices // dim

    return coord.flip(-1)
```

It is NOT exactly the same interface, but I believe it is better as it doesn't return tuples.

**Comment by ptrblck** [comment]
Thanks for sharing your approach, @francois-rozet!
I believe we are targeting a matching interface with numpy, but might not always be too strict.
CC @mruberry who is leading this work. :)

**Comment by francois-rozet** [comment]
Well I always disliked that `numpy.unravel_index` returns a `tuple` of arrays, instead of a single 2D array. `numpy` (and `torch`) should be as efficient as possible and the `tuple` is a bottleneck, in my opinion, especially if the coordinates need to be packed (`stack` or `cat`) together afterwards. If the user *really* needs a `tuple`, he can still do `tuple(np.unravel_index(...))`.

This is why I made the function return a `Tensor`. Also this implementation is more general as it doesn't assume the input to be 1D.

Since it is not exactly the same, maybe call it a little differently like `unravel_indices` and use it in another function `unravel_index` that match the one of `numpy` ?

Something like that ?

```python
def unravel_indices(
    indices: torch.LongTensor,
    shape: Tuple[int, ...],
) -> torch.LongTensor:
    r"""Converts flat indices into unraveled coordinates in a target shape.

    Args:
        indices: A tensor of (flat) indices, (*, N).
        shape: The targeted shape, (D,).

    Returns:
        The unraveled coordinates, (*, N, D).
    """

    shape = torch.tensor(shape)
    indices = indices % shape.prod()  # prevent out-of-bounds indices

    coord = torch.empty(indices.size() + shape.size(), dtype=int)

    for i, dim in enumerate(reversed(shape)):
        coord[..., i] = indices % dim
        indices = indices // dim

    return coord.flip(-1)

def unravel_index(
    indices: torch.LongTensor,
    shape: Tuple[int, ...],
) -> Tuple[torch.LongTensor, ...]:
    r"""Converts flat indices into unraveled coordinates in a target shape.

    This is a `torch` implementation of `numpy.unravel_index`.

    Args:
        indices: A tensor of (flat) indices, (N,).
        shape: The targeted shape, (D,).

    Returns:
        A tuple of unraveled coordinate tensors of shape (D,).
    """

    coord = unravel_indices(indices, shape)
    return tuple(coord)
```

**Comment by francois-rozet** [comment]
Well, I went to read the C code of `numpy.unravel_index`. Damn it is [wild](https://github.com/numpy/numpy/blob/92bf2f6d81252f97a7acc69fcc016636b29d1277/numpy/core/src/multiarray/compiled_base.c#L1167). In fact, they have a sub-function that unravels a single integer, which is probably why they return a `tuple` instead of a 2D array.

**Comment by mruberry** [comment]
Hey @tycho01, thanks for suggesting this feature. Is a workaround importing NumPy and using Numpy's `unravel_index()`?

**Comment by francois-rozet** [comment]
> Hey @tycho01, thanks for suggesting this feature. Is a workaround importing NumPy and using Numpy's `unravel_index()`?

This would mean that it would not work for CUDA LongTensor. (and won't leverage GPU)

**Comment by mruberry** [comment]
OK. I marked this as "needs (a little) design" to work out the UX for supporting multiple device types.

**Comment by Parskatt** [comment]
> ```python
> coord = torch.zeros(indices.size() + shape.size(), dtype=int)
> ```

Note that this will go to cpu even if indices are on gpu. You could add something like torch.zeros(..., device=indices.device)

**Comment by francois-rozet** [comment]
> @francois-rozet
> 
> > ```python
> > coord = torch.zeros(indices.size() + shape.size(), dtype=int)
> > ```
> 
> Note that this will go to cpu even if indices are on gpu. You could add something like torch.zeros(..., device=indices.device)

Yes, I noticed and corrected myself in https://github.com/pytorch/pytorch/issues/35674#issuecomment-739560051 (6 months ago 😅).

**Comment by Parskatt** [comment]
Ah! should have read that part more closely.
That's what I get for copy-pasting code  :p

**Comment by francois-rozet** [comment]
> Ah! should have read that part more closely.
> That's what I get for copy-pasting code  :p

I don't know your use case, but you might want to check https://github.com/francois-rozet/torchist
where `unravel_index` and `ravel_index` are implemented as well as `histogramdd`.

**Comment by digital-idiot** [comment]
Similarly, it would great to add a function equivalent to [numpy.ravel_multi_index](https://numpy.org/doc/stable/reference/generated/numpy.ravel_multi_index.html)

**Comment by ShoufaChen** [comment]
Hi, @francois-rozet 

Thanks for your great work.

I found the this implementation with pytorch has a different behavior with numpy in some case:

```
    import jax.numpy as jnp
    import numpy as np

    indices = list(range(15))
    shape = (1920, )

    out_jax = jnp.unravel_index(indices, shape)
    out_np = np.unravel_index(indices, shape)
    out_torch = unravel_index(torch.Tensor(indices), shape)

    print(out_jax)
    print(out_np)
    print(out_torch)
```

**Results**:
```
(DeviceArray([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int32),)
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)
(tensor([0.]), tensor([1.]), tensor([2.]), tensor([3.]), tensor([4.]), tensor([5.]), tensor([6.]), tensor([7.]), tensor([8.]), tensor([9.]), tensor([10.]), tensor([11.]), tensor([12.]), tensor([13.]), tensor([14.]))
```

A workaround which is not very elegant here:
```
    coord = []

    for dim in reversed(shape):
        coord.append(indices % dim)
        indices = indices // dim

    if len(coord) == 1 and coord[0].dim() == 1:
        return coord
    coord = torch.stack(coord[::-1], dim=-1)

    return coord
```

Would you mind helping to check it?

Thanks.

**Comment by codingpy** [comment]
It's so weird that the implementation has already been existing but unavailable:
https://github.com/pytorch/pytorch/blob/971c57f1d094806eab5340263dd59dd817267994/torch/testing/_core.py#L28-L45

**Comment by krshrimali** [comment]
Picking this up, a PR will hopefully show up next week. Thank you everyone for your views, and sharing relevant links.

**Comment by mruberry** [comment]
Triage review recommends adding to functional.py only so this will only be available in the Python API

**Comment by Pedrexus** [comment]
Hello, folks! Any news on this feature? I believe it is still desired.

**Comment by albanD** [comment]
@lezcano do you think someone on your end could get this through the finish line? I'm sure we already have a pure python implementation in the compat layer and we could just move that to torch.

**Comment by lezcano** [comment]
@kurtamohler will have a look

**Comment by francois-rozet** [comment]
Hello @albanD, @lezcano, @kurtamohler. Follows loop-free CUDA-compatible versions of `ravel_multi_index` and `unravel_index` taken from [torchist](https://github.com/francois-rozet/torchist).

```python
def ravel_multi_index(coords: Tensor, shape: Size) -> Tensor:
    r"""Converts a tensor of coordinate vectors into a tensor of flat indices.

    This is a `torch` implementation of `numpy.ravel_multi_index`.

    Args:
        coords: A tensor of coordinate vectors, (*, D).
        shape: The source shape.

    Returns:
        The raveled indices, (*,).
    """

    shape = coords.new_tensor(shape + (1,))
    coefs = shape[1:].flipud().cumprod(dim=0).flipud()

    return (coords * coefs).sum(dim=-1)


def unravel_index(indices: Tensor, shape: Size) -> Tensor:
    r"""Converts a tensor of flat indices into a tensor of coordinate vectors.

    This is a `torch` implementation of `numpy.unravel_index`.

    Args:
        indices: A tensor of flat indices, (*,).
        shape: The target shape.

    Returns:
        The unraveled coordinates, (*, D).
    """

    shape = indices.new_tensor(shape + (1,))
    coefs = shape[1:].flipud().cumprod(dim=0).flipud()

    return torch.div(indices[..., None], coefs, rounding_mode='trunc') % shape[:-1]
```
