### ISSUE TITLE
undefined symbol: cudnnSetConvolutionGroupCount while running with cuDNN 7.0.3 and CUDA 9

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#3567]
Installed from source, tried various branches _(master, v0.3.0, soumith-patch-1)_, but still getting this error.
Full uninstall and reinstall didn't help either. 
Calling `inception.cuda()` (form torchvision module) works fine, creating variables on the device doesn't seem to provoke this error either.
I've also just ran `LD_DEBUG=libs python -c 'import torch'` and got this [log](https://gist.github.com/VladislavZavadskyy/8b1a5abffe6298fe2908fe0e3bd6cbf9), which suggests that it searches for cudnn 6, but I have no idea why or how to fix it.

**Comment by VladislavZavadskyy** [comment]
There turned out to be sneaky conda package.
Fixed by doing `conda uninstall cuda` and recompiling.

**Comment by da-wad** [comment]
Thanks VladislavZavadskyy, this fixed the issue for me too!
