### ISSUE TITLE
tensor addition assignment strange behavior

### ISSUE THREAD

**Issue by iammarvelous** [pytorch/pytorch#3569]
It seems there is a really strange behavior for addition assignment operator. When changing the else statement from addition assignment to naive addition, outputs are different. The first element in the list is changed and it is not desired for addition assignment. The same thing would happen for `/=, *=, -=`
```
import torch
torch.manual_seed(1)
loss_list = [] 
for i in range(2):
    tmp = torch.FloatTensor(1).normal_()
    loss_list.append(tmp)
    if i == 0:  
        l = tmp
    else:
        l += tmp
    print tmp
    print loss_list
```

output: `l += tmp`
```
-2.9718
[torch.FloatTensor of size 1]

[
-2.9718
[torch.FloatTensor of size 1]
]

 1.7070
[torch.FloatTensor of size 1]

[
-1.2649
[torch.FloatTensor of size 1]
, 
 1.7070
[torch.FloatTensor of size 1]
]
```
output: `l = l + tmp`
```
-2.9718
[torch.FloatTensor of size 1]

[
-2.9718
[torch.FloatTensor of size 1]
]

 1.7070
[torch.FloatTensor of size 1]

[
-2.9718
[torch.FloatTensor of size 1]
, 
 1.7070
[torch.FloatTensor of size 1]
]
```

**Comment by apaszke** [comment]
This is expected. `+=` is the same as `add_`. If you ran the same snippet in NumPy you'd see exactly the same output.
