### ISSUE TITLE
Make adding buffers more like adding parameters to modules.

### ISSUE THREAD

**Issue by josh-gleason** [pytorch/pytorch#35735]
## 🚀 Feature
Add a `nn.Buffer` type to mirror the behavior of `nn.Parameter` without the need to explicity call `nn.Module.register_buffer`.

## Motivation

It's currently intuitive and easy to add a parameter to an `nn.Module` by wrapping it in a `nn.Parameter`. To the best of my knowledge a buffer is very similar to a parameter from an end user perspective except it doesn't get returned by `nn.Module.parameters()`.

It would therefore make sense to have a similar method for adding buffers to modules. Currently you have to explicitly call `nn.Module.register_buffer` which, in my opinion, is not very elegant as it requires you to provide the name of the member variable you want to create as a string.

    # currently
    class Foo(nn.Module):
        def __init__(self):
            super(Foo, self).__init__()
            self.weights = nn.Parameter(torch.zeros(10, 10))
            self.register_buffer('my_buffer', torch.zeros(10, 10))

    # proposed
    class Foo(nn.Module):
        def __init__(self):
            super(Foo, self).__init__()
            self.weights = nn.Parameter(torch.zeros(10, 10))
            self.my_buffer = nn.Buffer(torch.zeros(10, 10))

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by Balandat** [comment]
Is anyone working on this? Would be nice to have this to streamline dealing with buffers.

**Comment by asanakoy** [comment]
I agree. It Would be more consistent to have `nn.Buffer` along with `nn.Parameter`

**Comment by r-barnes** [comment]
This would be a great thing to have.

**Comment by albanD** [comment]
I'm afraid no-one is working on this at the moment no.
But I would be happy to review a PR adding this if anyone wants to do it!

**Comment by ekamiti** [comment]
> I'm afraid no-one is working on this at the moment no. But I would be happy to review a PR adding this if anyone wants to do it!

@albanD Just posted a [PR](https://github.com/pytorch/pytorch/pull/104069) for this. Mostly test changes, actual product code changes are not that much. Let me know what you think and whether I've missed any important considerations. Thanks!

**Comment by fzimmermann89** [comment]
I believe this has in the end not been merged, right?

Is there any chance that the PR will be merged or a different implementation will be considered?
