### ISSUE TITLE
torch.einsum() behaviour is different from that of numpy.einsum()

### ISSUE THREAD

**Issue by karthikprasad** [pytorch/pytorch#35737]
## 🐛 Bug

I discovered that the behaviour of `torch.einsum()` is different from that of `numpy.einsum()`. I couldn't find any explanation for this difference, so I'm assuming this is a bug.
As a work around, I'm doing `torch.tensor(numpy.einsum(...))`, but I'm not sure if this has perf issues and GPU support issues

## To Reproduce
```
A = torch.tensor([[[0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.3000, 0.3000, 0.3000],
         [0.3000, 0.3000, 0.3000, 0.3000]],
        [[0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.3000, 0.3000, 0.3000],
         [0.3000, 0.3000, 0.3000, 0.3000]]])
print(A); print(A.shape)

B = torch.tensor([[[ 0.0220,  0.0275, -0.0471, -0.0067],
         [-0.0039, -0.0336,  0.0682,  0.0491],
         [ 0.0243, -0.0246, -0.0425, -0.0074]],
        [[ 0.0220,  0.0275, -0.0471, -0.0067],
         [-0.0039, -0.0336,  0.0682,  0.0491],
         [ 0.0243, -0.0246, -0.0425, -0.0074]]])
print(B); print(B.shape)
```
## Actual behavior
```
torch_res = torch.einsum("noq,npq->nop", B, A)
print(torch_res); print(torch_res.shape)
```
```
tensor([[[-4.3000e-04, -4.3000e-04, -8.6000e-04, -8.6000e-04, -1.2900e-03,
          -1.2900e-03],
         [ 7.9800e-03,  7.9800e-03,  1.5960e-02,  1.5960e-02,  2.3940e-02,
           2.3940e-02],
         [-5.0200e-03, -5.0200e-03, -1.0040e-02, -1.0040e-02, -1.5060e-02,
          -1.5060e-02]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00],
         [ 9.1835e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00]]])
torch.Size([2, 3, 6])
```
## Expected behavior
```
numpy_res = np.einsum("noq,npq->nop", B, A)
print(numpy_res); print(numpy_res.shape)
```
```
[[[-0.00043 -0.00043 -0.00086 -0.00086 -0.00129 -0.00129]
  [ 0.00798  0.00798  0.01596  0.01596  0.02394  0.02394]
  [-0.00502 -0.00502 -0.01004 -0.01004 -0.01506 -0.01506]]

 [[-0.00043 -0.00043 -0.00086 -0.00086 -0.00129 -0.00129]
  [ 0.00798  0.00798  0.01596  0.01596  0.02394  0.02394]
  [-0.00502 -0.00502 -0.01004 -0.01004 -0.01506 -0.01506]]]
(2, 3, 6)
```
## Environment
 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): CentOS Linux 7 (Core)
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

cc @ezyang @gchanan @zou3519

**Comment by vincentqb** [comment]
Marking as high priority as this is a silent correctness issue.

**Comment by ezyang** [comment]
cc @t-vi

**Comment by t-vi** [comment]
`(torch_res - numpy_res).abs().max()`
gets me 
`tensor(3.4694e-18)`
so I'm not actually sure what we're talking about except numerical precision and formatting.

@vincentqb What did you expect to be fixed here?

**Comment by karthikprasad** [comment]
Hi @t-vi , `torch_res[1]` is not the same as `numpy_res[1]`, even though it should have been.
I am surprised you are getting such low value while I am seeing `tensor(0.0239)`

**Comment by t-vi** [comment]
I used some 1.5 dev version and had default dtype float64 enabled (the latter is why I have e-18 ish vs. e-9ish). That the output format differs between PyTorch and Numpy is probably not einsum's fault (and I don't really think it's a bug). So I don't think we have an einsum bug here.

The concrete result would also depend on the underlying BLAS library. If you did funny things there, it would show on torch.matmul and by proxy also einsum (which reduces to bmm currently) -- in the distant past we had people get completely bogus results due to some BLAS linking problems. Maybe with ancient tooling around PyTorch (like gcc 4.8.x) you manage to hit bugs somewhere in or around BLAS. If you have special requirements around using 5 year old tooling for business reasons, maybe you need some sort of commercial support, too. They'd know the type of pitfalls with their stack.

**Comment by karthikprasad** [comment]
Thank you @vincentqb and @t-vi, I had used version `1.4` when I saw this issue. I don't see it anymore in `1.5` anymore. While this result still boggles my mind, I will close this task as this is no longer an issue in the later versions.
