### ISSUE TITLE
Error exporting to onnx pytorch 1.4

### ISSUE THREAD

**Issue by cri5Castro** [pytorch/pytorch#35743]
## 🐛 Bug

Hello there im working with conv nets , i tried to used an adaptativeMaxPool2d to resize the feature maps but since is not suppported by onnx currently , I followed a custom implementation from a github issue

## To Reproduce
I tried with 
```
class custom_AdaptiveMaxPool2d(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x): 
        inp_size = x.size()
        size1=inp_size[2]
        size2=inp_size[3]
        return nn.functional.max_pool2d(input=x,
                  kernel_size= (size1, size2))
```

since kernel_size needs to be constant
and also with : 

```
class custom_AdaptiveMaxPool2d(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x): 
        inp_size = x.size()
        return nn.functional.max_pool2d(input=x,
                  kernel_size= (inp_size[3], inp_size[3]))
```

but same error happens
`RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible`

this is how I'm exporting the model, I have also tried with `operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK`

```
import torch.onnx
torch_out = torch.onnx._export(network,             # model being run
                               specs,                       # model input (or a tuple for multiple inputs)
                               "sample.onnx")
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by vincentqb** [comment]
Can you provide some context about your environment by copy-pasting the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)?

**Comment by spandantiwari** [comment]
@vincentqb - can you provide env details. Also, please provide complete repro including all variable that are used for export API call (such as `spec`). 
Also, please use the `torch.onnx.export` API instead of `_export` and if possible, retry with the latest version of PyTorch.

**Comment by garymm** [comment]
@cri5Castro can you please test on the latest nightly PyTorch? If it's still an issue, please update the description showing the construction of `network` and `specs` args.

**Comment by BowenBao** [comment]
Hi @cri5Castro ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
