### ISSUE TITLE
Move PyTorch Convolution into ATen

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3578]
ATen does have a THNN binding for convolution, but PyTorch supports a far richer interface to convolution that hooks up to CuDNN and nnpack. We should move this code into ATen.

Task list:

- [X] Support computing derivatives for multiple inputs simultaneously
- [X] Do warmup porting prelu to ATen, which has many similar characteristics to convolution
- [X] Teach ATen build system to link against CuDNN
- [x] Port `torch/csrc/cudnn` to use ATen tensors instead of THVoidTensor
- [x] Restructure `torch/csrc/cudnn` so that it stratifies types and implementations, so it can be included from core ATen headers
- [x] Redesign the API of cudnn so that it more closely matches THNN's (e.g., drop THCState parameter, reorder arguments, get rid of Convolution)
- [x] Rename the THNN binding from conv2d to conv2d_thnn
- [x] Implement ATen backend functions for cudnn and nnpack; these skip backend selection and always use their respective backend.
- [x] Implement a native ATen function to dispatch to an implementation appropriately
- [x] Teach ATen build system to link against nnpack

Some design flex:

- The old PyTorch cudnn library took the CuDNN handle in as arguments; at all call sites, these CuDNN handles were retrieved from a global, mutex protected hash. Because I'm going to expose a generic `conv` method which is backend agnostic, my current plan is to NOT expose any ATen functions which take explicit CuDNN handles. (~~This simplifies codegen, since I don't have to teach the code generator to automatically insert code to fill in these arguments on the backend functions.~~ Blah I should probably teach the codegen to do this properly.)
- The old cudnn Convolution interface had a "Convolution" struct which it allocated on the heap and then reused on subsequent invocations, saving us from having to rewrite the descriptors each time. I've undone this optimization because it's a bit annoying to actually achieve this.

**Comment by zdevito** [comment]
cuDNN also has planning routines for choosing the best way to run a convolution (and a backward input conv, and backward weight conv). ATen will either need to implement a cache for these plans or will need to take handles in to retrieve an existing plan. Do you have a plan for what approach you want to take? I'd eventually like to have to cache.

**Comment by ezyang** [comment]
My current plan is to take all the code that is called from `torch/csrc/autograd/functions/conv.cpp`, and yes, I believe that includes the cache.

**Comment by ezyang** [comment]
All fixed and merged.
