### ISSUE TITLE
Variance Pooling

### ISSUE THREAD

**Issue by ShairozS** [pytorch/pytorch#35811]
What is the best way to apply a local pooling operation across an input tensor that gives me the variance of the window (instead of the max/mean which is more traditional) in a way that is differentiable? I'd like to be able to parameterize local image patches with mean/variance. 

Related to issue [#17169](https://github.com/pytorch/pytorch/issues/17169), which doesn't seem to have made progress.

**Comment by jerryzh168** [comment]
Looks like this is the same issue, could you comment there?
