### ISSUE TITLE
Documentation references incorrect cuda version 

### ISSUE THREAD

**Issue by ahmedhosny** [pytorch/pytorch#35828]
## 📚 Documentation

Under [installing new versions](https://pytorch.org/get-started/previous-versions/), more precisely:
-  v1.2.0 
- cuda 10.0
- using pip
- for linux & windows

the docs give this line

```
# CUDA 10.0
pip install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

```
It seems that this line grabs the cuda 9.2 version instead:
```
Collecting torch==1.2.0
  Downloading https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp27-cp27mu-manylinux1_x86_64.whl (663.1MB)
```
Probably the docs need to be updated?

**Comment by ahmedhosny** [comment]
somewhat related #34064

**Comment by peterjc123** [comment]
Would you please try out `pip install torch===1.2.0 torchvision===0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`?

**Comment by ahmedhosny** [comment]
Using triple equals seems to work. It downloads "torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl" and torch.version.cuda returns '10.0.130'. Anyway I think the docs might need an update..

**Comment by mruberry** [comment]
Closing due to age. @ahmedhosny if you're still experiencing this issue with the most recent version of PyTorch/CUDA would you please reopen this?
