### ISSUE TITLE
PyTorch and Libtorch for Xcode/IOS header file location/visibility issue.

### ISSUE THREAD

**Issue by linjiapro** [pytorch/pytorch#35864]
## 🐛 Bug
I am trying to follow this tutorial https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source to integrate PyTorch into a Xcode project. 

I installed LibTorch 1.4.0 via Pod, and after 
#import <LibTorch/LibTorch.h>, found out that some simple classes such as torch::nn::Module is not available. Here is the reason behind it: LibTorch.h only included some headers under Pod folder. Others are in extension.h under this path:
Pods/LibTorch/install/include/torch
I manually included "extension.h", and building app starts to fail. After some digging, here seems to be the reason. There are a group of files under:
Pods/LibTorch/install/include/torch/csrc/api/include/torch
After moving those files up to:
Pods/LibTorch/install/include/torch/
and correct few import errors, everything start to work. 

Are those files location wrong at the first place? Without moving those, important classes such as torch::nn::Module cannot accessed. This could be related to the build process. 

## Expected behavior
After pod install, and import #import <LibTorch/LibTorch.h>, we should be immediately use classes such as torch::nn::Module

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version: 1.4
 - OS : Mac OS
 - How you installed PyTorch: pod via this tutorial: https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source 
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by linjiapro** [comment]
Though the program compiles. Now there are link errors saying that  torch::nn::Module's functions implementation cannot be found.

**Comment by xta0** [comment]
@linjiapro the APIs under nn namespace are being used to support eager mode in Python. Since we’re using torchscript on mobile, we didn’t compile that part of code in our binary. However, I think you can manually enable it by changing the `NO_API` value to OFF in the root `CMakeLists.txt` and rebuild the libraries. However, I personally haven’t tried, so not sure if they’ll work or not.

**Comment by linjiapro** [comment]
It turns out that integrating the libtorch distributed version with Xcode is difficult to maintain and use. I changed the IDE to visual studio code, and CMake. Everything works like a charm.
