### ISSUE TITLE
Installing torch on python 3.8.2: could not find a version that satisfies requirement

### ISSUE THREAD

**Issue by jhoorneman** [pytorch/pytorch#35873]
## ❓ Questions and Help
I'm trying to install torch with Python 3.8.2 but get the following error message:
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0+cpu

The install command used was:
 `pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html`
All other relevant information is in the checklist below.

In another issue I saw this can mean there are no binaries available, but in that same issue it was stated binaries for python 3.8 are now available.

 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip 20.0.2
 - Build command you used (if compiling from source): -
 - Python version: 3.8.2
 - CUDA/cuDNN version: none
 - GPU models and configuration: Intel HD Graphics 620
 - Any other relevant information: -

**Comment by MatevzFa** [comment]
Having the same issue. Encountered while trying to install [stanza](https://github.com/stanfordnlp/stanza). Same message occurs when trying to install with
```
pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
(as described on the PyTorch website).

Specs:

- Python 3.7.2
- pip 20.0.2
- Windows 10 (18363.752)
- No Nvidia GPU

**Comment by peterjc123** [comment]
Are you guys using x64 Python?

**Comment by jhoorneman** [comment]
No, I was on 32 bit. Installing x64 Python solved the issue for me. Thanks!

**Comment by fan-of-dark** [comment]
Hi friends , I encountered the similar error while installing fastai-cpu into local windows 10 using conda.

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.4.0  (from torchvision>=0.1.9->-r C:\Users\windows\fastai\fastai\condaenv.pkqlr_xm.requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0 (from torchvision>=0.1.9->-r C:\Users\windows\fastai\fastai\condaenv.pkqlr_xm.requirements.txt (line 1))
failed
CondaEnvException: Pip failed

for installing , I fallowed the simple steps provided in [https://medium.com/@pierre_guillou/fastai-how-to-start-663927d4db63](url).

can you please help me with this error my friend?
