### ISSUE TITLE
LIBRT missing

### ISSUE THREAD

**Issue by traits** [pytorch/pytorch#35875]
## 🐛 Bug

Windows build fails with the following error:

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.                
Please set them or make sure they are set and tested correctly in the CMake files:                          
LIBRT                                                                                                       
    linked by target "benchdnn" in directory V:/src/pytorch/pytorch/third_party/ideep/mkl-dnn/tests/benchdnn`

Introduced probably in https://github.com/shibatch/sleef/commit/a0537162e045f6300139865474d9212de16360a1  (third_party\sleef\src\quad-tester)

**Comment by peterjc123** [comment]
It is because mkldnn is out of sync. You can resolve this by doing `git submodule sync && git submodule update --init --recursive`.
