### ISSUE TITLE
when I print a quantized tensor, why it is in float32 fomat?

### ISSUE THREAD

**Issue by HumberMe** [pytorch/pytorch#35874]
## ❓ Questions and Help
While doing post-training, I find that we cannot see the data of quantized tensor directly(it is supposed to be uint8 or int8).
The data we can see is dequanted, and it is in float32 format.   
It will be confusing if we wanna figure out what happend in the inference of quantized model. 
Is that a bug?

**Comment by jerryzh168** [comment]
yeah we print the floating point tensor value represented by the quantized tensor, that's not a bug.
If you want to look at the integer values, you can call `t.int_repr()`
Also please use the discussion forum for questions: https://discuss.pytorch.org/

**Comment by HumberMe** [comment]
> yeah we print the floating point tensor value represented by the quantized tensor, that's not a bug.
> If you want to look at the integer values, you can call `t.int_repr()`
> Also please use the discussion forum for questions: https://discuss.pytorch.org/

By changing a little bit pytorch code, I added a function of generating A8W4 quantized model(by using int8 weights to simulate int4), can I push it?
