### ISSUE TITLE
pytorch installation on windows 10 fails

### ISSUE THREAD

**Issue by joepareti54** [pytorch/pytorch#35880]
## 🐛 Bug
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.4.0+cpu
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://download.pytorch.org/whl/torch_stable.html: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/torch_stable.html (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by peterjc123** [comment]
It's not our fault. A better fix is to get ssl installed in your environment but I won't talk about it here. The easy workground is to download the wheels manually from https://download.pytorch.org/whl/torch_stable.html and then install that through `pip install "path/to/wheel"`.

**Comment by Spenhouet** [comment]
> It's not our fault.

Strange that most other packages do not have this issue, it must be the user fault. ;)

@joepareti54 

This would also work:

`pip install -f https://download.pytorch.org/whl/torch_stable.html torch===1.4.0+cpu`
