### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by VinceKumar** [pytorch/pytorch#3591]
When I try to build the Dockerfiles, they fail at this line 
```
RUN git clone https://github.com/pytorch/vision.git && cd vision && pip install -v .
```
Here is the error returned:

```
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d_0hrixx/torch/
```

I tried manually inserting the packages from setup.py but it failed to load import torchvision after compiling

AWS ubuntu p2.xlarge w/ CUDA 9.0, cuDNN 7, Nvidia 384.81

**Comment by ClaireYang** [comment]
How do you fix this issue? I met the same issue.

**Comment by tsdaemon** [comment]
I have a similar error trying to build a Docker image on Windows. The problem was in line endings, which was automatically converted from LF to CRLF by Git. I have set a global option `git config --global core.eol lf` and cloned the pytorch project again and the problem was solved.
