### ISSUE TITLE
RunTimeError while unscaling optimizer gradients

### ISSUE THREAD

**Issue by poppingtonic** [pytorch/pytorch#35926]
## 🐛 Bug

I updated my learner to follow the typical mixed-precision training scenario provided [here](https://pytorch.org/docs/master/notes/amp_examples.html#typical-mixed-precision-training), but got a 
```
RuntimeError Could not run 'aten::_amp_non_finite_check_and_unscale_' with arguments from the 'CPUTensorId' backend. 'aten::_amp_non_finite_check_and_unscale_' is only available for these backends: [CUDATensorId, VariableTensorId].
```
## To Reproduce

1. Compile PyTorch `master` from source
1. Build training 'Learner' like so [Jupyter Notebook]: https://github.com/poppingtonic/fastai2/commit/5bd7b42ae58420564d40f9192d082b97518f634e
1. Replace device asserts with `.cuda()` calls to clear 3 `AssertionError` minefields in `grad_scaler.py`: https://github.com/poppingtonic/pytorch/commit/807e042622c3abb0623ffaeb151dc8a6a232322b
1. Attempt to train the model on one batch of data 

```
     90         # If these gradients do not contain infs or NaNs, optimizer.step() is then called,
     91         # otherwise, optimizer.step() is skipped.
---> 92             self.scaler.step(self.opt);                      self('after_step')
     93             # self.opt.step();                                 self('after_step')
     94             # Updates the scale for next iteration.

~/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py in step(self, optimizer, *args, **kwargs)
    278 
    279         if optimizer_state["stage"] == self.READY:
--> 280             self.unscale_(optimizer)
    281 
    282         assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."

~/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py in unscale_(self, optimizer)
    229         found_inf = torch.full((1,), 0.0, dtype=torch.float32, device=self._scale.device)
    230 
--> 231         optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
    232         optimizer_state["stage"] = self.UNSCALED
    233 

~/anaconda3/envs/pytorch-nightly/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py in _unscale_grads_(self, optimizer, inv_scale, found_inf, allow_fp16)
    180                         torch._amp_non_finite_check_and_unscale_(param.grad,
    181                                                                  per_device_found_inf.get(param.grad.device),
--> 182                                                                  per_device_inv_scale.get(param.grad.device))
    183 
    184         return per_device_found_inf._per_device_tensors


RuntimeError: Could not run 'aten::_amp_non_finite_check_and_unscale_' with arguments from 
the 'CPUTensorId' backend. 'aten::_amp_non_finite_check_and_unscale_' is only available for
these backends: [CUDATensorId, VariableTensorId].
```

## Expected behavior

Run without any runtime errors, obtain lower loss

## Environment

PyTorch version: 1.6.0a0+6d24f8f
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.59
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0a0+6d24f8f
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] faiss-gpu                 1.6.3            py37h1a5d453_0    pytorch
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.0                      166  
[conda] mkl-include               2020.0                      166    conda-forge
[conda] numpy                     1.18.1           py37h8960a57_1    conda-forge
[conda] torch                     1.6.0a0+6d24f8f          pypi_0    pypi
[conda] torchvision               0.5.0                py37_cu101    pytorch

## Additional context

I made several updates to pytorch code to get to this point, by directly moving data to the device:
https://github.com/poppingtonic/pytorch/commit/807e042622c3abb0623ffaeb151dc8a6a232322b

**Comment by jerryzh168** [comment]
The error message says it's because you are feeding `aten::_amp_non_finite_check_and_unscale_` with CPU Tensors, could you check?

**Comment by gchanan** [comment]
CC @mcarilli 

are we clear in our docs that AMP is only supported on CUDA?  It might also make sense to implement CPU overloads for some of these functions that just say "this isn't supported on CPU, use CUDA instead" so the error message is nicer.
