### ISSUE TITLE
JIT: int(str) fails

### ISSUE THREAD

**Issue by IlyaOvodov** [pytorch/pytorch#35948]
## 🐛 Bug

int(some_string) fails when doing torch.jit.script:

## To Reproduce
```
def f(s: str):
    return int(s)
f = torch.jit.script(f)
```
results in error:
```
  File "C:\Miniconda3\lib\site-packages\torch\jit\__init__.py", line 1281, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::Int(Tensor a) -> (int):
  Expected a value of type 'Tensor' for argument 'a' but instead found type 'str'.
  
  aten::Int(bool a) -> (int):
  Expected a value of type 'bool' for argument 'a' but instead found type 'str'.
  
  aten::Int(float a) -> (int):
  Expected a value of type 'float' for argument 'a' but instead found type 'str'.
  
  aten::Int(Scalar a) -> (int):
  Expected a value of type 'number' for argument 'a' but instead found type 'str'.

The original call is:
  File "D:/GitHub/yolov3/qwe.py", line 6
def f(s: str):
    return int(s)
           ~~~ <--- HERE
```

 - PyTorch Version (e.g., 1.0): 1.4.0 (current stable)
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html
 - Build command you used (if compiling from source): --
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: 1050
 - Any other relevant information:

cc @suo

**Comment by IlyaOvodov** [comment]
The problem persists in a latest nightly version (1.5.0.dev20200325) as well.

**Comment by suo** [comment]
Thanks for the request! This seems like a reasonable thing to add, we'll look into it (cc @driazati)

**Comment by vishwakftw** [comment]
@suo @driazati we seem to have support for `float()`, could I send in a PR for `int()`?

**Comment by driazati** [comment]
Sure, tag me as a reviewer when you do
