### ISSUE TITLE
Build latest master from source fails

### ISSUE THREAD

**Issue by IlyaOvodov** [pytorch/pytorch#35947]
## 🐛 Bug

build master branch rev.8484ca  from source fails: 

(base) D:\Programming\3rd_party\PyTorch\pytorch_ovod_master>python setup.py build develop
Building wheel torch-1.6.0a0+8484ca5
-- Building version 1.6.0a0+8484ca5
cmake --build . --target install --config Release -- -j 12
[12/319] Building CXX object test_api\CMakeFiles\test_api.dir\modules.cpp.obj
FAILED: bin/torch_cuda.dll lib/torch_cuda.lib
cmd.exe /C "cd . && C:\Miniconda3\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cuda.dir --manifests  -- C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1411~1.255\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp  /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO   && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1411~1.255\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cuda.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\torch_cuda.lib and object lib\torch_cuda.exp
torch_cuda_generated_Activation.cu.obj : error LNK2019: unresolved external symbol __imp_THLog1p referenced in function "public: double __cdecl <lambda_0b87f60e23817c63adca5fb71036c1e8>::operator()(double)const " (??R<lambda_0b87f60e23817c63adca5fb71036c1e8>@@QEBANN@Z)
bin\torch_cuda.dll : fatal error LNK1120: 1 unresolved externals

## Environment
Windows 10, MS VC 2017 15.8.8 + v14.11 toolset, CUDA 10.0

**Comment by peterjc123** [comment]
Could not reproduce locally. And I could not find any occurrence of `THLog1p` in the codebase. Could you please do a fresh clone and build again?

**Comment by IlyaOvodov** [comment]
Yes, getting frech clone fixed to problem. Probably, long history of version changes left some rudimentary files.
