### ISSUE TITLE
commit version 35715a56a93363bc61fdf924175d4c4d6352f813 cause DLRM benchmark performance drop

### ISSUE THREAD

**Issue by JianpingChen066** [pytorch/pytorch#35940]
## 🐛 Bug

commit version 35715a56a93363bc61fdf924175d4c4d6352f813 (HEAD -> Mar30-35715a56a9)
Author: Mingzhe Li <mingzhe0908@fb.com>
Date: Mon Mar 30 14:37:01 2020 -0700
[reland] Skip OpenMP Thread when OMP_NUM_THREADS is 1 (#35541)

cause DLRM benchmark performance drop

Without this check-in the DLRM benchmark result is like:
```
numactl --physcpubind=0-27 -m 0 python dlrm_s_pytorch.py --mini-batch-size=2048 --num-batches=100 --data-generation=random --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --arch-sparse-feature-size=64 --arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup=100 --arch-interaction-op=dot --numpy-rand-seed=727 --print-freq=100 --print-time --enable-profiling > model1_CPU_PT_28.log
Min time per iteration = 1578.36
```
with this check-in , the result is like:
```
numactl --physcpubind=0-27 -m 0 python dlrm_s_pytorch.py --mini-batch-size=2048 --num-batches=100 --data-generation=random --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --arch-sparse-feature-size=64 --arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup=100 --arch-interaction-op=dot --numpy-rand-seed=727 --print-freq=100 --print-time --enable-profiling > model1_CPU_PT_28.log
Min time per iteration = 1691.71
```
From the profiling data, you can see some Ops in DLRM got very big slower as below :
|                 | Before | This    |
|-----------------|----------:|----------:|
|  `index_select` | 9.113s | 59.894s |
| `mm`            | 10.788s   |   12.420s |
| `addmm`         | 6.103s   | 16.652s |
| `relu`         | 1.830s   | 13.994s |
| `threshold_backward`         | 1.572s   | 12.352s |
| `_embedding_bag`         | 3.192s   | 31.880s |

The time is for 1000 iterations

## To Reproduce

1. Download the DLRM from https://github.com/facebookresearch/dlrm
2. Modify the bench/dlrm_s_benchmark.sh to just run pytorch on cpu version, as
     build=0
     cpu=1
     gpu=0
     pt=1
     c2=0
   And variables as
    export KMP_BLOCKTIME=1
    export KMP_AFFINITY="granularity=fine,compact,1,0"

3. Run bench/dlrm_s_benchmark.sh on CLX8280 machine. performance profiling data is stored at file model1_CPU_PT_28.prof
    'This' is got from commit-id: 35715a56a93363bc61fdf924175d4c4d6352f813
     'Before' is got from commit-id: a0dc36e501d336c92c10462057716f0355a0108c

## Expected behavior

The DLRM performance has no impacted, Thanks

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.6.0a0+35715a5
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] numpydoc==0.9.2
[pip3] torch==1.6.0a0+35715a5
[conda] mkl                       2020.1                intel_217    intel
[conda] mkl-include               2020.1                intel_217    intel
[conda] mkl-service               2.3.0                    py37_0    intel
[conda] mkl_fft                   1.0.15           py37ha68da19_3    intel
[conda] mkl_random                1.1.0            py37ha68da19_0    intel
[conda] numpy                     1.17.4           py37ha68da19_4    intel
[conda] numpy-base                1.17.4                   py37_4    intel
[conda] torch                     1.5.0a0+59c95bf          pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel

**Comment by JianpingChen066** [comment]
@VitalyFedyunin @ezyang please have a check, thanks

**Comment by ezyang** [comment]
@mingzhe09088 could you please take a look at this?

**Comment by ezyang** [comment]
Marked as high priority as it is a 10x performance regression

**Comment by VitalyFedyunin** [comment]
cc @ilia-cher as reviewer of offending PR

**Comment by mingzhe09088** [comment]
The referred commit has been reverted in master. Could you rebase to latest master and retry?

**Comment by mingzhe09088** [comment]
In your environment, did you set OMP_NUM_THREADS to 1?

**Comment by JianpingChen066** [comment]
@mingzhe09088 OMP_NUM_THREADS is set to 28 and numactl --physcpubind=0-27

**Comment by JianpingChen066** [comment]
@mingzhe09088 If I make a modification as below:
```
diff --git a/aten/src/ATen/ParallelOpenMP.h b/aten/src/ATen/ParallelOpenMP.h
index 7eb08aa1b0..9b8948df93 100644
--- a/aten/src/ATen/ParallelOpenMP.h
+++ b/aten/src/ATen/ParallelOpenMP.h
@@ -25,7 +25,7 @@ inline void parallel_for(
 #ifdef _OPENMP
   std::atomic_flag err_flag = ATOMIC_FLAG_INIT;
   std::exception_ptr eptr;
-  if (!omp_in_parallel() && ((end - begin) > grain_size) && omp_get_num_threads() > 1) {
+  if (!omp_in_parallel() && ((end - begin) > grain_size)) { // && omp_get_num_threads() > 1) {
 #pragma omp parallel
     {
       // choose number of tasks based on grain size and number of threads
```

The performance can come back for these Ops

**Comment by mingzhe09088** [comment]
I was not able to reproduce the regression on my machine so I will revert the offending diff first in #36198.

**Comment by JianpingChen066** [comment]
yes, it's OK now, thanks
