### ISSUE TITLE
RuntimeError: grad_columns needs to be contiguous

### ISSUE THREAD

**Issue by seerdecker** [pytorch/pytorch#35957]
## 🐛 Bug

Pytorch 1.4 broke previously working code involving a transpose convolution in the backward pass. This is similar to https://github.com/pytorch/pytorch/issues/33168. Although the issue is marked as fixed, it isn't quite fixed in all use cases. I have tested this with the latest nightly build.

IMPORTANT: this is a minimally-reduced example of the bug that will trigger on CPU only. If you run this with cuda_flag = 1, the test will pass. However, in my real implementation (too complex to include here), it will fail on CUDA as well, with a similar error message.

## To Reproduce

```
#!/usr/bin/env python3

import os, sys
import numpy as np
import torch

cuda_flag = 0

def numpy_to_torch_var(np_t):
    if cuda_flag: t = torch.from_numpy(np_t).cuda()
    else: t = torch.from_numpy(np_t).clone()
    t.requires_grad = True
    return t

class SomeFunc(torch.autograd.Function):

    @staticmethod
    def forward(ctx, in_act):
        return in_act

    @staticmethod
    def backward(ctx, grad_out):
        return grad_out.clone()

prev_layer = numpy_to_torch_var(np.random.randn(1, 84, 84, 4).astype(np.float32))
prev_layer = torch.transpose(prev_layer, 1, 3).contiguous()
weight_var = numpy_to_torch_var(np.random.randn(4, 4, 1, 1).astype(np.float32))
prev_layer = torch.nn.functional.conv_transpose2d(prev_layer, weight_var, None)
prev_layer = torch.transpose(prev_layer, 1, 3).contiguous()
prev_layer = SomeFunc.apply(prev_layer)

print("Should fail here")
prev_layer.sum().backward()
print("Should have failed here")
```

```
Should fail here
Traceback (most recent call last):
  File "./torch_bug.py", line 33, in <module>
    prev_layer.sum().backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: grad_columns needs to be contiguous
```

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.10
GCC version: (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by xwang233** [comment]
Thanks for the issue! I was able to run your script with the latest master build at 1.6.0a0+de04a18. So I guess it's probably fixed somewhere.

**Comment by seerdecker** [comment]
Thank you. I confirm it works now. I blindly executed the pip install for the nightly build without substituting pip for pip3. Oops.

Unfortunately, it seems that the nightly build introduces even more bugs. 

torch.nn.functional.max_pool2d broke:

  File "/home/delta/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 539, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got -4)

I will downgrade to pytorch 1.1. I suggest adding more regression tests to reduce the number of these regressions.

Thanks again for the help.

**Comment by xwang233** [comment]
Oops, would you mind post a script that triggers the bug on `max_pool2d`? That could help developers better solve the problem.
