### ISSUE TITLE
Feature Request: Add quantile function support

### ISSUE THREAD

**Issue by matthewfeickert** [pytorch/pytorch#35977]
## 🚀 Feature

It would be good to add a `torch.percentile` function that has a similar API to NumPy's [`np.percentile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html), including interpolation schemes.

## Motivation

For performing statistical analyses and operations with PyTorch it is useful to be able to specify the q-th percentile of arbitrary numeric data stored in a Tensor.

For a specific example, this functionality is [needed in `pyhf`](https://github.com/scikit-hep/pyhf/issues/815) &mdash; a library for likelihood-based fits in high energy physics (full disclosure I'm on the dev team). It is also noted as being useful/of interest by @ezyang in Issue #32769 (for the similar [`numpy.nanpercentile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanpercentile.html)).

## Pitch

Implement equivalent functionality to [`numpy.percentile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html) with the same or similar API.

## Alternatives

As noted in [the linked `pyhf` Issue](https://github.com/scikit-hep/pyhf/issues/815) this functionality can be achieved with 

```python
def percentile(self, tensor_in, q):
    k = 1 + round(0.01 * float(q) * (tensor_in.numel() - 1))
    return tensor_in.view(-1).kthvalue(k).values.item()
```

however, this is for the unrolled tensor and this produces the equivalent of `numpy.percentile`'s "nearest" interpolation method, which is not always desirable.

Also, while [`torch.distributions.distribution.icdf`](https://pytorch.org/docs/stable/distributions.html#torch.distributions.distribution.Distribution.icdf) gives the

> the inverse cumulative density/mass function evaluated at value

this is only for a probabilistic distribution, while the functionality desired would be for arbitrary Tensors.

## Additional context

As mentioned above, more detail and information is covered in [`pyhf` Issue 815](https://github.com/scikit-hep/pyhf/issues/815).

cc @lukasheinrich @kratsg

**Comment by matthewfeickert** [comment]
@zou3519 Just curious if you think that this is something that would be looked at by a dev team member in the (somewhat) near future, or if you think that this would only happen if someone from the community made a PR?

**Comment by zou3519** [comment]
I'm not sure. @mruberry, who works on numpy compatibility, should be able to give you a better answer for that.

**Comment by mruberry** [comment]
We're planning to add torch.quantile, analogous to numpy.quantile, but not numpy.percentile. As I understand it numpy.quantile is preferred to numpy.percentile, and numpy.percentile may even be deprecated in the future. Will numpy.quantile address your needs?

fyi @rgommers

**Comment by kratsg** [comment]
> We're planning to add torch.quantile, analogous to numpy.quantile, but not numpy.percentile. As I understand it numpy.quantile is preferred to numpy.percentile, and numpy.percentile may even be deprecated in the future. Will numpy.quantile address your needs?

We would be fine with quantile -- as they're analogous except one is [0,1] while the other is [0,100] -- and I believe numpy percentile calls quantile under the hood anyway.

**Comment by mruberry** [comment]
Great! Thanks for the follow-up @kratsg, I'm going to change the issue's title to reflect our thinking.

**Comment by mruberry** [comment]
Duping to https://github.com/pytorch/pytorch/issues/38349, where quantile is already part of the rollup. https://github.com/pytorch/pytorch/pull/39417 will address this.

**Comment by matthewfeickert** [comment]
> I believe numpy percentile calls quantile under the hood anyway.

Yup. Both `percentile` and `quantile` in NumPy are wrappers around [`_quantile_unchecked`](https://github.com/numpy/numpy/blob/94721320b1e13fd60046dc8bd0d343c54c2dd2e9/numpy/lib/function_base.py#L3821-L3830).


Thanks for the follow up, @mruberry! I've subscribed to both the Issue and the PR so that the `pyhf` dev team can follow along. :rocket:
