### ISSUE TITLE
[JIT] Tensor method API schema discrepancy, Tensor.requires_grad_(..)

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#35987]
For Python, schema is "Tensor.requires_grad_(requires_grad=False)".
For JIT, schema is "Tensor.requires_grad_(_requires_grad=False)".

https://github.com/pytorch/pytorch/blob/fd1dfaa7d049a2b1661ae3d297ede50018dbc17e/torch/csrc/jit/runtime/register_prim_ops.cpp#L659

cc @suo

**Comment by zdevito** [comment]
https://github.com/pytorch/pytorch/pull/36168 attempts to rename the kwarg to match, let's see if it passes tests.
