### ISSUE TITLE
raise warning when compiled with a CUDA version that will JIT on the current GPU

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3598]
There's quite a few user-reports of installing the CUDA 7.5 binary of pytorch and then running on GTX 1080 / 1070, and there will be reports of installing 7.5 / 8.0 binaries and running on V100.

Raising a user-warning in such situations and letting them know will fix the problem.

**Comment by alykhantejani** [comment]
The version of CUDA used to compile the binary should be available thanks to this PR: https://github.com/pytorch/pytorch/pull/3036

**Comment by fmassa** [comment]
@alykhantejani I think https://github.com/pytorch/pytorch/pull/3601 is a more robust way of getting the CUDA used to compile PyTorch, as currently if there are multiple CUDA installed in the machine, the heuristics used in #3036 might not match those used by CMake FindCUDA. I think that we should modify the `torch.version.cuda` to return the cuda version used during compilation (which might require saving this information in a file during compilation and trying to parse it from python afterwards).
What do you think?
