### ISSUE TITLE
Support custom modules in Quantization APIs

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#35999]
## 🚀 Feature
Add support to prepare and convert API to use a custom user module 
## Pitch

We need to update prepare API to accept a custom module. The workflow will perform a module swap in the prepare step.
The user should provide their module similar to existing ones like quantized.modules.nn.Linear. They should also implement a `from_float` function for their module that the workflow will use when quantizing the module. https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/linear.py#L231

Add documentation showing how user can use custom modules with quantization.

## Additional context

Reason for this feature request was a use-case where custom Linear module was implemented to support batch size of 0. 

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
this is documented here: https://pytorch.org/docs/master/quantization.html#quantization-custom-module-api
