### ISSUE TITLE
RFC: Proper timeout support with rpc.remote() API

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#36000]
## 🚀 Feature

As https://github.com/pytorch/pytorch/pull/34650 is adding support for per-RPC timeouts for `rpc_sync` and `rpc_async`, this RFC is to get feedback on how timeouts should behave with the remote API.

## Motivation
Currently, the underlying `future` is marked with an error when an RPC times out. In the case of sync and async RPC, this works since the user directly interacts with the returned future and this thus alerted of the timeout with an `Exception`. However, `rpc.remote` does not directly return the future back to the user and it is kept internal. Thus the timeouts do not work properly. Exceptions can actually end up in a `std::terminate` (see https://github.com/pytorch/pytorch/issues/33803)

## Pitch

The future corresponding to an invocation of `rpc.remote` is created in the following places:
- For remote torchscript, happens in `remoteTorchscript` 
- For remote UDF, `pyRemotePythonUDF`
- For remote builtin, `pyRemoteBuiltin`

We can augment the `PyRRef` constructor to take in the future that was responsible for creating it and pass in the future in all of these cases. Then, when calling APIs such as `to_here()` or forking the RRef, we check this future to ensure that it did not have errors. If it did, then we can use the call to APIs such a `to_here()` to surface the error back to the user. All internal RRef APIs that depend on the successful creation of the RRef would have to be augmented to check this newly added future.

A downside of this is that the user is not necessarily notified immediately when the error happens, and they can in fact never be notified if they never use the RRef again, but still somehow assume that it has been successfully created. We may be able to add a LOG(WARNING) in this case.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
> We can augment the PyRRef constructor to take in the future that was responsible for creating it and pass in the future in all of these cases. 

#31893 adds a [`deletedOnOwner`](https://github.com/pytorch/pytorch/blob/82d58ed484eb04f894475de0551055f7e070f481/torch/csrc/distributed/rpc/rref_impl.h#L303) flag to indicate whether the RRef has been deleted. I wonder if we should reuse and extend this flag to record RRef state. E.g., it can be an Enum of pending, confirmed, error, deleted, etc. 

> A downside of this is that the user is not necessarily notified immediately when the error happens, and they can in fact never be notified if they never use the RRef again, but still somehow assume that it has been successfully created. 

This looks OK to me as a first step. Is this actually similar to async RPC? If I make an async call and never wait on the future, we also would lose the opportunity to report the error promptly? 

For the long term, we might be able to allow applications to install a listener to react to RPC failures.

**Comment by rohan-varma** [comment]
@mrshenli That is true for async RPCs as well.

In addition to extending the `deletedOnOwner` flag, we also might want to look into being able to install custom error handlers, such as overriding the default RRef error handling, which simply rethrows the error (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/rref_context.cpp#L73)

**Comment by rohan-varma** [comment]
Done by https://github.com/pytorch/pytorch/pull/38590
