### ISSUE TITLE
Remove "using namespace" in libtorch headers

### ISSUE THREAD

**Issue by ychen306** [pytorch/pytorch#36008]
## 🚀 Feature

Can we remove "using namespace ..." from the public headers of libtorch?

## Motivation
E.g., `torch/csrc/api/include/torch/nn/modules/_functions.h` has this line `using namespace torch::autograd;`. This pollutes the namespace of some applications.

cc @yf225

**Comment by yf225** [comment]
@ychen306 Thanks for the report! This issue has been fixed on master (https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/modules/_functions.h) and the fix will also be in 1.5 release.

**Comment by ychen306** [comment]
Thank you!
