### ISSUE TITLE
Ensure quantization workflows work with batch-size 0 tensors

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#36001]
Check the behavior of observers and fake quant operators inserted in the model when dealing with tensors of batch size is 0.
They should work as expected and we should be inserting observers and fake quant operators even for 0 batch tensors.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
@supriyar , is this one finished and ready to close?
