### ISSUE TITLE
Implement Complex Support that allows Complex Tests to run in test_torch.py

### ISSUE THREAD

**Issue by dylanbespalko** [pytorch/pytorch#36029]
I am listing the issues that prevent complex dtypes from being used in `test_torch.py`

- [x] rand()

- [x] randn()

- [x] assertEqual()

- [x] from_numpy()

- [ x] isclose() (torch.equal not supported for complex).

Please suggest more kernels here if you find any. 
 
cc: @ngimel, @kostekIV, @aayn, @anjali411, @ezyang 

cc @ezyang @anjali411 @dylanbespalko

**Comment by ngimel** [comment]
For `isclose`, the real issue is not <=. After #35871 is merged and `abs` returns floating point tensor, that should be solved. However, there are other places in `isclose` that require adjustments for complex numbers https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorCompare.cpp#L21-L58 - in particular, `nan` and infinity checking should be done for real part and imaginary part separately, there may be something else.

**Comment by aayn** [comment]
@dylanbespalko @ngimel @anjali411 

I'd like to work on this. Is that okay or is someone already working on it?

**Comment by dylanbespalko** [comment]
Please proceed @aayn,

#35954 is another blocker for this issue for this.

Here is a [link](https://gitlab.com/pytorch-complex/pytorch-cpu-strided-complex/-/blob/master/test/test_torch.py) to some preliminary test cases that I was using in Jan 2020. There are comments that cited the use of  old `th_...` functions. `TH` was used before `ATen` and did not support complex numbers.

Also search for `legacy::cpu::_th` in [native_functions.yaml ](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml) to see which functions  have not been ported to ATen. 

You may need to port `th_take()` or `th_put()` to ATen first. There is a guide somewhere to porting TH kernels to ATen.

**Comment by aayn** [comment]
@dylanbespalko 

Thanks! That should help me get started. I found the [TH to ATen porting guide](https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide) (note for self).
A small aside: I just noticed that [this line](https://github.com/pytorch/pytorch/blame/master/aten/src/ATen/native/README.md#L9) has incorrect grammar ("either...and"); should I just submit a PR fixing it or post an issue first (sorry if this seems like nitpicking!)?

**Comment by ngimel** [comment]
@anjali411 has been working on porting th functions are needed for basic complex functionality to ATen, she has a better idea of what a priority of things are. tbh, I don't think we need any th ports for `isclose`, all the changes can be localized in the isclose implementation itself hopefully? There should be some masking operations to find nans and infs, and I think they are being worked on.

**Comment by dylanbespalko** [comment]
@aayn,

I don't know, but I would lump doc fixes with other code fixes when it's a simple correction. Thanks for reading the docs!

**Comment by aayn** [comment]
@dylanbespalko @ngimel 

I have something approximating a first draft ready. I'm waiting on #35871. Apart from that, I have a question: how do you access the real and imaginary parts of a tensor within the C++ backend? Just using `.real()`/`.imag()` or `.real`/`.imag` doesn't seem to work. I tried to find the implementation of `Tensor` in `ATen`, which took me to `Tensor.h` that includes `TensorBody.h` and `TensorMethods.h`, but I can't find them anywhere. What am I missing?

**Comment by kostekIV** [comment]
@aayn I think use of `real` and `imag`  was disabled in pr #35560 for complex tensors. And in  #35879 `copy_real()` and `copy_imag()` were added instead.

**Comment by dylanbespalko** [comment]
@aayn,

The `tensor.real()` and `tensor.imag()` methods are defined [here](https://github.com/pytorch/pytorch/blob/a91535930fc39f40cb564f6c03215729af5f98ea/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp#L75)

The code for `real_impl` and `imag_impl` is found [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/zmath.h)

Perhaps you have run into problems with #35560? I think they needed to disable some complex number support to fix some memory problems.

**Comment by ngimel** [comment]
.real() and .imag() are disabled for now so that we don't expose numpy-incompatible behavior. In numpy, when you call .real() or .imag() you get a view of the original complex tensor (and can operate on real/imaginary parts in place), our implementations for now can only return copies. But all this is not a problem for isclose.

**Comment by anjali411** [comment]
> For `isclose`, the real issue is not <=. After #35871 is merged and `abs` returns floating point tensor, that should be solved. However, there are other places in `isclose` that require adjustments for complex numbers https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorCompare.cpp#L21-L58 - in particular, `nan` and infinity checking should be done for real part and imaginary part separately, there may be something else.

we will also need torch.equal for this [line](https://github.com/pytorch/pytorch/blob/126d00c8ddcca996a5045f6a6c59cf86c120936c/aten/src/ATen/native/TensorCompare.cpp#L49) to work. not entirely sure what methods are called for comparison with [INFINITY](https://github.com/pytorch/pytorch/blob/126d00c8ddcca996a5045f6a6c59cf86c120936c/aten/src/ATen/native/TensorCompare.cpp#L50-L51) and if it would work for complex

**Comment by ngimel** [comment]
It looks to me like out of those 3 lines in isclose
```
close.__ior__(self == other);
close.__iand__((self == INFINITY) == (other == INFINITY));
close.__iand__((self == -INFINITY) == (other == -INFINITY));
```
only the first one is needed. For complex tensors, if we don't support == already (do we?), we should just separately compare real and imaginary parts. 
Also, fun fact, it looks like `isclose` itself is not tested, which looks like an oversight.

**Comment by anjali411** [comment]
> It looks to me like out of those 3 lines in isclose
> 
> ```
> close.__ior__(self == other);
> close.__iand__((self == INFINITY) == (other == INFINITY));
> close.__iand__((self == -INFINITY) == (other == -INFINITY));
> ```
> 
> only the first one is needed. For complex tensors, if we don't support == already (do we?), we should just separately compare real and imaginary parts.
> Also, fun fact, it looks like `isclose` itself is not tested, which looks like an oversight.

equal hasn't been ported from TH to ATen so torch.equal is not supported for complex tensors right now. 
yeah, I agree. as a work around, we can do `self.copy_real() == other.copy_real() && self.copy_imag() == other.copy_imag()` until equal is supported.

@ngimel why don't we need the other two lines?

**Comment by ngimel** [comment]
suppose your `self` and `other` have some `inf`s or `-inf`s. If those infs happen in the different places, `close` will correctly have `false` in those places, and it won't be changed by the first line (because self != other for those). Now, suppose inf's are in the same place. Then `close` erroneously has `false` there, but it is fixed by the first line, because `inf == inf` (same for -inf). Second and third lines just confirm what has already been done by the first.

**Comment by anjali411** [comment]
> suppose your `self` and `other` have some `inf`s or `-inf`s. If those infs happen in the different places, `close` will correctly have `false` in those places, and it won't be changed by the first line (because self != other for those). Now, suppose inf's are in the same place. Then `close` erroneously has `false` there, but it is fixed by the first line, because `inf == inf` (same for -inf). Second and third lines just confirm what has already been done by the first.

makes sense

**Comment by aayn** [comment]
Thank you all for the inputs. Seems like #35871 has been merged. I'll pull the latest stuff, update my local build and send a PR with a solution shortly.

**Comment by aayn** [comment]
@dylanbespalko @ngimel @anjali411 

I have a few questions. Testing the current (hardware accelerated) exp function with `rtol=0` and `atol=0` doesn't work. There is almost always some small error between the backend computation and the torch computation. What would be the right tolerances to set here? I isolated this to our exp implementation: if you change the [this function](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L245) and [this function](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_complex_double.h#L207) to simply `return map(std::exp);` then the tests pass with zero tolerances.

**Comment by dylanbespalko** [comment]
@aayn,

Floating-point tolerances are currently define for non-complex dtypes. I simply borrowed these numbers as follows:

```python
c2r_dtype = {th.complex64: th.float32,
             th.complex128: th.float64}
tol_kwargs = {"rtol": th.finfo(c2r_dtype[dtype]).eps, "atol": th.finfo(c2r_dtype[dtype]).tiny}

assert_allclose(t2n(th.exp(a)), np.exp(t2n(a)), **tol_kwargs)
```
assert_allclose is from numpy.test

Also for hw acceleration, SLEEF defines the tolerances for each function [here](https://sleef.org/x86.xhtml). I've noticed that some functions have different tolerances.

**Comment by dylanbespalko** [comment]
Related #35954

**Comment by aayn** [comment]
@dylanbespalko It actually works with zero tolerance too. I was making a stupid mistake.

@dylanbespalko @ngimel @anjali411 I'm submitting a preliminary PR. Let me know if my solution is acceptable, and please suggest changes if not.

**Comment by mruberry** [comment]
torch.isclose is in but for testing we should use self.assertEqual, which has different and preferred behavior for comparing complex tensors when testing. 

I believe this issue is now addressed!

**Comment by dylanbespalko** [comment]
@aayn 

> It actually works with zero tolerance too

Great to hear you are having success! This was a concerning statement. When you don't specify `atol` or `rtol` it defaults to a type specific epsilon not zero. Make sure you never specify `atol=0.0` or `rtol=0.0` in your code.
