### ISSUE TITLE
torch.gather export onnx not properly

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#36022]
A tiny snippet:

```python
idxs = torch.argmax(prob, dim=-1)
scores = torch.gather(prob, -1, idxs.unsqueeze(-1))
```

which get idxs and scores out from a tensor like this:

```
[[0.2, 0.3, 0.5], [....], ...]]
```
but the onnx exported GatherElements,
GatherElements is not supported by onnx-tensorrt, is there a way to avoid it? (I suppose it should be Gather would be much more properly)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@jinfagang - GatherElements op is part of ONNX spec and is a legal op. If this is the only issue then I would say that ONNX export is working all right for your model. 
For your specific need, you can try modifying the ONNX model using ONNX APIs.

**Comment by jinfagang** [comment]
@spandantiwari  This issue still exists in pytorch 1.7 and opset all along with 10 11 12 

May I ask, why using GatherElements rather than Gather with this operation?
what's their difference? How to make this op export as Gather?

**Comment by spandantiwari** [comment]
@jinfagang  - Gather is definitely more generic that GatherElements, and IIRC (I could be wrong about this), not every scenario that GatherElements supports can be supported easily with Gather. Also, we wanted to keep GatherElements and ScatterElements aligned.
