### ISSUE TITLE
commit version 618104185bce6591c4697063b1faf2027c3761e7 cause DLRM benchmark performance drop

### ISSUE THREAD

**Issue by JianpingChen066** [pytorch/pytorch#36038]
## 🐛 Bug

commit 618104185bce6591c4697063b1faf2027c3761e7 (HEAD -> Mar26-618104185)
Author: Wanchao Liang <wanchaol@users.noreply.github.com>
Date:   Thu Mar 26 17:06:08 2020 -0700

    [autograd] enable graph level thread parallelism on CPU (#33157)

    Summary:
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/33157
  
cause DLRM performance drop, especially on SGD related Ops

Without this check-in the DLRM benchmark result is like:
```
numactl --physcpubind=0-27 -m 0 python dlrm_s_pytorch.py --mini-batch-size=2048 --num-batches=100 --data-generation=random --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --arch-sparse-feature-size=64 --arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup=100 --arch-interaction-op=dot --numpy-rand-seed=727 --print-freq=100 --print-time --enable-profiling > model1_CPU_PT_28.log
Min time per iteration = 1523.89
```
with this check-in , the result is like:
```
numactl --physcpubind=0-27 -m 0 python dlrm_s_pytorch.py --mini-batch-size=2048 --num-batches=100 --data-generation=random --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --arch-sparse-feature-size=64 --arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup=100 --arch-interaction-op=dot --numpy-rand-seed=727 --print-freq=100 --print-time --enable-profiling > model1_CPU_PT_28.log
Min time per iteration = 1633.51
```
From the profiling data, you can see some Ops in DLRM got very big slower as below :
|                 | Before | This    |
|-----------------|----------:|----------:|
|  `add_` | 1497.139s | 1561.464s |
|  `zero_` | 485.043ms | 10.816s |
|  `torch::autograd::AccumulateGrad` | 62.293ms | 10.297s |
|  `index_select` | 1.263s | 9.395s |
| `mm`            | 9.169s   |   10.977s |
| `addmm`         | 4.984s   | 6.138s |
| `relu`         | 425.576ms   | 1.898s |
| `threshold_backward`         | 650.896ms   | 1.503s |
| `_embedding_bag_backward`         | 104.387ms   | 956.360ms |

The time is for 1000 iterations
## To Reproduce

1. Download the DLRM from https://github.com/facebookresearch/dlrm
2. Modify the bench/dlrm_s_benchmark.sh to just run pytorch on cpu version, as
     build=0
     cpu=1
     gpu=0
     pt=1
     c2=0
    Install jemalloc as "conda install jemalloc"  //since my test result is with jemalloc enabled, 
                                                                         // without this may also can reproduce this regression
   please ensure mkl and mkl-inlcude installed
       "conda install mkl mkl-include numpy -c intel"

And export env variables as
    export KMP_BLOCKTIME=1
    export KMP_AFFINITY="granularity=fine,compact,1,0"
    export MALLOC_CONF="retain:true,narenas:$ncores,percpu_arena:percpu,background_thread:true,dirty_decay_ms:9000000000,muzzy_decay_ms:9000000000,abort_conf:true"
    export LD_PRELOAD=$HOME/anaconda3/lib/libjemalloc.so  //modify the path according to where jemalloc installed

3. Run bench/dlrm_s_benchmark.sh on CLX8280 machine. performance profiling data is stored at file model1_CPU_PT_28.prof
    'This' is got from commit-id: 618104185bce6591c4697063b1faf2027c3761e7
     'Before' is got from commit-id: a0dc36e501d336c92c10462057716f0355a0108c

## Expected behavior

The DLRM performance has no impacted, Thanks

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.6.0a0+35715a5
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] numpydoc==0.9.2
[pip3] torch==1.6.0a0+35715a5
[conda] mkl                       2020.1                intel_217    intel
[conda] mkl-include               2020.1                intel_217    intel
[conda] mkl-service               2.3.0                    py37_0    intel
[conda] mkl_fft                   1.0.15           py37ha68da19_3    intel
[conda] mkl_random                1.1.0            py37ha68da19_0    intel
[conda] numpy                     1.17.4           py37ha68da19_4    intel
[conda] numpy-base                1.17.4                   py37_4    intel
[conda] torch                     1.5.0a0+59c95bf          pypi_0    pypi

## Additional context

@ezyang There is another issue on the commit 618104185bce6591c4697063b1faf2027c3761e7 which cause the first DLRM performance regression , please have a check on this. Thanks

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @VitalyFedyunin @ngimel

**Comment by ezyang** [comment]
cc @wanchaol

**Comment by wanchaol** [comment]
Thanks for the report, looking into it.

**Comment by wanchaol** [comment]
@JianpingChen066, I spent sometime on reproducing the regression, but so far what I get is not a regression but rather a minor perf improvement, also I don't see `zero_` time is increasing. see this result https://gist.github.com/wanchaol/6e0c52720313047f67789dc447f53ed0

Can you retry your benchmark locally? or can you share what additional set up you might have on your setup? Thanks!

**Comment by JianpingChen066** [comment]
@wanchaol which kind of machine you used for profiling, looks like it more slower than the performance on CLX8280 28-core (add_ performance is ~1561s on CLX8280 with 28-core while the add_ in your report is about 2241s, is that for 1000 iterations ) ? Is this check-in may introduce some uncertainty ? something like lock conflict, when it's not happen then perform is OK while when conflict happen, it will drop the performance ?

**Comment by JianpingChen066** [comment]
@wanchaol Is there an option to disable the graph level thread parallelism on CPU ? Thanks

**Comment by JianpingChen066** [comment]
@wanchaol Could you try the following way to see whether this can be reproduced ?
1) wget https://github.com/pytorch/pytorch/pull/23057.diff (This is try to improve add_out_dense_sparse performance for non-coalesced hybrid sparse tensor)
2) Apply this diff to the commit version Mar26-618104185 and Mar26-9b8c9d6c respectively
3) Compare these two performance and profiling data 

When I apply this to Mar26-618104185, the performance is like
```
Finished training it 1000/1000 of epoch 0, 93.10 ms/it, loss 0.083365, accuracy 0.000 %
```
When I apply this to Mar26-9b8c9d6c, the performance is like
```
Finished training it 1000/1000 of epoch 0, 40.21 ms/it, loss 0.083365, accuracy 0.000 %
```
And index_select has changed from 1.232s to 9.334s

**Comment by wanchaol** [comment]
@JianpingChen066 My machine is with Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz, 80 cores, and the benchmark is also with 28 cores, the perf on my side is pretty bad though, with either revision, I got something like:
```
Finished training it 1000/1000 of epoch 0, 2248.37 ms/it, loss 0.083328, accuracy 0.000 %
```
I am applying the patch you had to see if there's a difference, but from the patch content I guess there's not too much difference. I will update here once I get the numbers.

**Comment by JianpingChen066** [comment]
@wanchaol For Intel(R) Xeon(R) CPU E5-2698 v4 , is that machine 20 core-per-slot ? if so, you may try tor compare the performance with 20 cores to avoid the numa issue (28 core will cross the slot and have numa performance issue). By the way, do you have done "conda install mkl mkl-inlcude numpy -c intel " for that ? Thanks

**Comment by JianpingChen066** [comment]
This look like caused by the jemalloc MALLOC_CONF, remove the following export, the performance will back
```
export MALLOC_CONF="retain:true,narenas:$ncores,percpu_arena:percpu,background_thread:true,dirty_decay_ms:9000000000,muzzy_decay_ms:9000000000,abort_conf:true"
```
I will close this issue, thanks

**Comment by wanchaol** [comment]
I see, that's possible. I installed the jemalloc and try to set the env vars, but there were some warnings so it might not being correctly set up and the perf I got might be without jemalloc. Glad that you figured things out :)
