### ISSUE TITLE
Freeze when importing CARLA and Torchvision (jit.script related)

### ISSUE THREAD

**Issue by germanros1987** [pytorch/pytorch#36034]
## 🐛 Bug

When using PyTorch along with the [CARLA simulator](https://github.com/carla-simulator/carla) the system freezes. More specifically, when importing the carla module before importing torchvision the system freezes.

I have been tracking down this issue and it seems deeply connected to torch.jit.script. That is why it happens when processing the torchvision import, since the detection module uses a few torch.jit.script decorators. The issue seems to be in torch._C._jit_script_compile, which for some reason freezes. 

Some things to notice:

* If carla is not imported everything works
* If carla is imported after the torch.jit.script decorators have been processed everything works
* if the function to be decorated is "simple enough" everything works.

Please, see a functional minimal example below.

## To Reproduce

1. Create a new conda environment: conda create --name py36 python=3.6
2. Install pytorch + torchvision for your cuda distribution (I have tried 9.2 and 10.1).
3. Install CARLA by downloading the binary [release:](https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.8.tar.gz) 
4. Unzip it and install the CARLA Python API using easy_install while your conda environment is active: easy_install {CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.8-py3.*...
5. Run the code example below:

```
BREAK_IT = False
 if BREAK_IT:
    import carla

import torch._C
import torch._jit_internal as _jit_internal
from torch._jit_internal import _qualified_name
from torch.jit.frontend import get_jit_def, get_default_args

def example_function(input_param):
    out = input_param * torch.zeros((0, 3, int(input_param)), dtype=torch.float32)
    return out


def run():
    obj = example_function
    ast = get_jit_def(obj)
     _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)

    qualified_name = _qualified_name(obj)
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
    
    return fn

if __name__ == '__main__':
    run()
    print('Everything went well...')
```

## Expected behavior

This code should not freeze.

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 with Max-Q Design
Nvidia driver version: 440.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.6_cuda9.2.148_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                 py36_cu92    pytorch

```

Any help would be very appreciated.

cc @ezyang @gchanan @zou3519 @suo

**Comment by suo** [comment]
Thanks for the report! We will investigate with your repro. In the meantime, what does gdb say if you attach it to the frozen process and print a backtrace?

**Comment by germanros1987** [comment]
Hi, we have been digging into the root of the problem and it seems to be due to different versions of libstdc++ used by Pytorch and CARLA. I think we have found a fix and I am currently testing it. I will report results soon so that you can close this issue.

**Comment by germanros1987** [comment]
I confirm the bug is solved and it was related to libstdc++ issues. https://github.com/carla-simulator/carla/commit/711738b1b91fc60325e693ed2a1d884f5b1fa6db
