### ISSUE TITLE
Unable to use cuda Runtime Error(801)

### ISSUE THREAD

**Issue by molicaca** [pytorch/pytorch#36037]
When i run the trainning project, the compiler report the "Runtime Error(801) operation not supported at C:\w\1\s\windows\pytorch\torch/csrc/generic/StorageSharing.cpp:245".
I am just a green hand and even cant understand what it is. Anybody who can help me and solve this problem?

**Comment by peterjc123** [comment]
You cannot share CUDA tensors across processes on Windows. For more details, see https://pytorch.org/docs/stable/notes/windows.html#cuda-ipc-operations.
