### ISSUE TITLE
Cannot load cuda state_dict in cpu mode

### ISSUE THREAD

**Issue by isacarnekvist** [pytorch/pytorch#3603]
```
# ...
model = model.cuda()
# ...
with open('model.pkl', 'wb') as f:
    pickle.dump(model.state_dict(), f)
```
Loading this in a cpu-only version crashes and complains about missing NVIDIA drivers. Is this really the wanted behavior?

**Comment by karandwivedi42** [comment]
Does this help? 
https://discuss.pytorch.org/t/loading-weights-for-cpu-model-while-trained-on-gpu/1032

**Comment by ozancaglayan** [comment]
Yes you need to explicitly map the storage with lambda as in the given example in order to avoid using the same storage defined in the pkl file.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/issues/3603#issuecomment-343233247
