### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'manual_seed'

### ISSUE THREAD

**Issue by ddevsantos** [pytorch/pytorch#36042]
## 🐛 Bug

AttributeError: module 'torch' has no attribute 'manual_seed'

It happens just importing torch on Spyder's session.

Curiously, It happens only when i change the base files directory ( C:\etc...   to    E:\etc... )

![image](https://user-images.githubusercontent.com/61477111/78499958-29b0b600-772a-11ea-821f-5cd3c4480386.png)

```

 - PyTorch Version 💯   1.4
  - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`  ):

 - Python version:  3.7.7
 - CUDA/cuDNN version: have no idea
 


cc @ezyang @seemethere

**Comment by peterjc123** [comment]
Maybe you have `torch.py` under that folder?

**Comment by oplatek** [comment]
I got the same error when using `mypy`on ubuntu 16.04 `torch==1.4.0`

However, when I run in the same environment the following command. It runs fine.
```
python -c 'import torch; torch.manual_seed(43)' 
```

**Comment by rgommers** [comment]
> Maybe you have `torch.py` under that folder?

That seems most likely.



> I got the same error when using `mypy`...

This is fixed:
```
$ cat tmp.py
import torch

reveal_type(torch.manual_seed(1))


$ mypy tmp.py
tmp.py:3: note: Revealed type is 'torch._C.Generator'
```
