### ISSUE TITLE
Crash when creating a tensor from a tensor on a different device

### ISSUE THREAD

**Issue by Sun694** [pytorch/pytorch#36045]
## 🐛 Bug

When executing the following code, Python crashes.

## To Reproduce

import torch.nn
Tensor = torch.cuda.FloatTensor
print(torch.nn.Parameter(Tensor(torch.ones(3,))))

## Expected behavior

An error message instead of a complete crash. If you replace torch.cuda.FloatTensor with torch.FloatTensor, it works as expected (no crash, no error).

## Environment

 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): Windows, CoLab
 - How you installed PyTorch (`conda`, `pip`, source): Conda
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GTX 980, CoLab GPU

## Additional context

Able to reproduce problem on CoLab as well.

cc @ezyang @gchanan @zou3519

**Comment by lufol** [comment]
I could reproduce this.
The crash can be avoided if correct device is passed to the `Tensor`:
```
import torch.nn
Tensor = torch.cuda.FloatTensor
Tensor(torch.ones(3,device='cuda'))
```

However if `device="cpu"` (probably the default) this code crashes:
`Tensor(torch.ones(3,device='cpu'))`

So `torch.cuda.FloatTensor`should potentially check if `torch.cuda.is_available`and if move the passed tensor to gpu first. Otherwise if on cpu an error message should be thrown directly.

**Comment by zou3519** [comment]
Marked as high-pri for crash

**Comment by ezyang** [comment]
Doesn't sound like it should be too hard to fix.

**Comment by albanD** [comment]
Is this related to Parameter or is it just calling `torch.cuda.FloatTensor(torch.ones(3))`?

**Comment by gchanan** [comment]
we should fix, but you'll have a better time if you don't use `Tensor`.  `torch.ones` already creates a Tensor and you can pass whatever specification you want there.

**Comment by lufol** [comment]
@albanD  Its unrelated to `nn.Parameter` and `torch.cuda.FloatTensor(torch.ones(3))` alreay crashes.

**Comment by Sun694** [comment]
> @albanD Its unrelated to `nn.Parameter` and `torch.cuda.FloatTensor(torch.ones(3))` alreay crashes.

Thanks for figuring it out.  I didn't think to remove the nn.Parameter.



> we should fix, but you'll have a better time if you don't use `Tensor`. `torch.ones` already creates a Tensor and you can pass whatever specification you want there.

Will do, thanks.

**Comment by Baranowski** [comment]
This has been already fixed. I can reprodue the crash on 1.4.0 but on master I get TypeError.

I originally misunderstood the scope of this issue. I thought the goal was to implement that functionality. As per https://github.com/pytorch/pytorch/pull/36235#pullrequestreview-390404480, that's not the case.
