### ISSUE TITLE
Add moveaxis function

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#36048]
## 🚀 Feature
Add a function that behaves like numpy's [moveaxis](https://docs.scipy.org/doc/numpy/reference/generated/numpy.moveaxis.html).

## Motivation

In my experience, it is extremely clumsy and bug-prone to use [permute](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.permute) or a sequence of [transposes](https://pytorch.org/docs/stable/torch.html#torch.transpose) to move an axis from a source to a destination, especially when working with a variable-dimension tensor.

## Pitch

Implement a function `torch.moveaxis` that moves axes to new positions while keeping the other axes in their original order.

**Comment by zou3519** [comment]
I think this would be useful, there have been many a time when I've needed this. A simple workaround is to use `.unsqueeze(location).transpose(location, dim)`.

cc @mruberry for numpy compatability

**Comment by SsnL** [comment]
single dim version

```py
def _moveaxis(tensor: torch.Tensor, source: int, destination: int) -> torch.Tensor:
    dim = tensor.dim()
    perm = list(range(dim))
    if destination < 0:
        destination += dim
    perm.pop(source)
    perm.insert(destination, source)
    return tensor.permute(*perm)
```

**Comment by mruberry** [comment]
Thanks for the suggestion, @carlosgmartin! I added this to our NumPy function request issue.

**Comment by ngimel** [comment]
Added in #41480
