### ISSUE TITLE
Runtime Error adding bool and complex tensors

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36057]
Script to reproduce: 

```
import torch
a = torch.tensor((True,), dtype=torch.bool)
b = torch.tensor((1 + 1j,), dtype=torch.complex128)
print(a + b)
```

Result:

`RuntimeError: dtype != ScalarType::Undefined INTERNAL ASSERT FAILED at ../aten/src/ATen/native/TensorIterator.cpp:124, please report a bug to PyTorch.`

cc @ezyang @anjali411 @dylanbespalko

**Comment by anjali411** [comment]
seems like a type promotion bug. probably need to modify https://github.com/pytorch/pytorch/blob/82d58ed484eb04f894475de0551055f7e070f481/aten/src/ATen/native/TypeProperties.cpp#L59
