### ISSUE TITLE
FileNotFoundError       

### ISSUE THREAD

**Issue by anweshpanda** [pytorch/pytorch#36063]
I am trying to execute the following code in google colab:::
.................................................
TEXT = data.Field(tokenize = 'spacy', lower = True)
LABEL = data.LabelField()
train_data, valid_data, test_data = datasets.SNLI.splits(TEXT, LABEL)
....................................................
However, I am getting the following error:::
....................................................
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-30-3cbb82bfebca> in <module>()
----> 1 train_data, valid_data, test_data = datasets.SNLI.splits(TEXT, LABEL)

3 frames
/usr/local/lib/python3.6/dist-packages/torchtext/data/dataset.py in __init__(self, path, format, fields, skip_header, csv_reader_params, **kwargs)
    249             'tsv': Example.fromCSV, 'csv': Example.fromCSV}[format]
    250 
--> 251         with io.open(os.path.expanduser(path), encoding="utf8") as f:
    252             if format == 'csv':
    253                 reader = unicode_csv_reader(f, **csv_reader_params)

FileNotFoundError: [Errno 2] No such file or directory: '.data/snli/snli_1.0/snli_1.0_train.jsonl'
.....................................................

Can anyone please help?

cc @SsnL

**Comment by zou3519** [comment]
This seems like a torchtext issue. You should cross post an issue there: https://github.com/pytorch/text

**Comment by anweshpanda** [comment]
Ok... thanks @zou3519
