### ISSUE TITLE
Flask report "RuntimeError: cuda runtime error (3) : initialization error "

### ISSUE THREAD

**Issue by mashuai191** [pytorch/pytorch#36068]
## 🐛 Bug

I have a trained Detectron2 model, and i want to integreate it with Flask to make it a web service. It works well in single process, but failed in multi-process. I'm struggling with this issue for several days and after some searching i found similar ones (https://github.com/rusty1s/pytorch_geometric/issues/131, https://github.com/pytorch/pytorch/issues/15734) but not sure about that. 

1. after checking [this link](https://pytorch.org/docs/stable/notes/multiprocessing.html), i added the `mp.set_start_method('spawn',force=True)` inside `if __name__ == "__main__":` as below:

```import os
from flask import Flask, render_template, Response
import multiprocessing as mp

app = Flask(__name__)

@app.route('/video_feed1')
def video_feed1():
    return Response(gen(segPrediction()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == "__main__":
    mp.set_start_method('spawn',force=True)
    app.run(host='0.0.0.0', threaded=False, processes=2)
```
then it report:
``` File "/content/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 41, in __init__
    pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

2. then i moved the `mp.set_start_method('spawn',force=True)`  outside of `if __name__ == "__main__" as below:

```import os
from flask import Flask, render_template, Response
import multiprocessing as mp
mp.set_start_method('spawn',force=True)

app = Flask(__name__)

@app.route('/video_feed1')
def video_feed1():
    return Response(gen(segPrediction()),
                    mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == "__main__":
    app.run(host='0.0.0.0', threaded=False, processes=2)
```
this time it report:
```
  File "<ipython-input-22-95b269c1163b>", line 42, in frames
    predictor = DefaultPredictor(cfg)
  File "/content/detectron2_repo/detectron2/engine/defaults.py", line 163, in __init__
    self.model = build_model(self.cfg)
  File "/content/detectron2_repo/detectron2/modeling/meta_arch/build.py", line 19, in build_model
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/content/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 41, in __init__
    pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /pytorch/aten/src/THC/THCGeneral.cpp:54
```

## Environment

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.4.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect

cc @ngimel

**Comment by mashuai191** [comment]
waiting for some who knows some workaroud to bypass this issue...

**Comment by basit26374** [comment]
@mashuai191 I am also facing the issue. 
Can you debug this issue?

If yes, so kindly write the procedure to overcome this issue

**Comment by mashuai191** [comment]
@basit26374 docker is a solution for isolation.

**Comment by eladrich** [comment]
Hi,
I'm having a similar issue when trying to do inference in `gunicorn`.
The model is successfully loaded into the GPU during the server init but fails to move tensors to GPU during inference (`image.cuda()`) with a `Cuda error: initialization error`. 
I've tried to set `set_start_method('spawn',force=True)` but that doesn't seem to help.

Any ideas on how to approach this problem?

**Comment by obravo7** [comment]
@mashuai191 I get the same error as you do when running both tensorflow 1.15 and pytorch within a Flask application. [Because tensorflow holds on to memory until the session is killed](https://github.com/tensorflow/tensorflow/issues/19731#issuecomment-473215534), it is suggested to use multiprocessing to release memory when the process is done running. However this seems to be a problem with Pytorch, and I can't find a workaround.

**Comment by HK-NJUST** [comment]
@eladrich this is same with me.  I dual with it by Removing --preload in gunicorn cmd.

**Comment by mashuai191** [comment]
@obravo7 

> @basit26374 my issue may be caused by running both pytorch and tensorflow simultaneously. docker is a solution for isolation.

**Comment by HGamalElDiin** [comment]
> @basit26374 my issue may be caused by running both pytorch and tensorflow simultaneously. docker is a solution for isolation.

so how to fix this case when both are needed?

**Comment by macksjlazarus** [comment]
> preload

Somehow this saved me 2 years later. TY

**Comment by macksjlazarus** [comment]
> @eladrich this is same with me. I dual with it by Removing --preload in gunicorn cmd.
This saved me. Tysm
