### ISSUE TITLE
Assert MKL conditions in THBlas.c

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#3606]
The checks in https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THBlas.c should really always pass, eg ld* ones, except for `INT_MAX` ones. Maybe we should assert them rather than checking and resorting to slow c code when failing.

cc @soumith

**Comment by colesbury** [comment]
They will not pass for things like expanded tensors:

```python
x = torch.randn(1).expand(5, 5)
x.mm(x)
```

**Comment by SsnL** [comment]
Good point. How about we make it such that the caller should handle

**Comment by soumith** [comment]
discussed with Sam, on zero-strided Tensors, we should makeContiguous + gemm, because the C code that runs by default is SUPER not performant.

**Comment by SsnL** [comment]
working on this

**Comment by albanD** [comment]
@soumith I think this can be closed.

**Comment by soumith** [comment]
closed via #4056
