### ISSUE TITLE
padding_mode

### ISSUE THREAD

**Issue by vpapaioannou** [pytorch/pytorch#36089]
## 📚 Documentation

From the docs, https://pytorch.org/docs/stable/nn.html, `padding_mode` is not documented in terms of the available options. Only the `zeros` option is shown whereas there was one more `circular` option if someone checks earlier versions of the code, 1.4.0 specifically. In the most recent code release, https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L341, there is only `zeros` and non `zeros` option.

A consequent problem with this, is how to set the kernel and dilation size. If kernel/dilation size is not small enough accross the network then the following exception is raised, 

![image](https://user-images.githubusercontent.com/6065702/78597329-55f82f80-781b-11ea-8f58-c47b34005942.png)

**Comment by SsnL** [comment]
pretty sure https://github.com/pytorch/pytorch/commit/c6f41ae01b2014e4001996b30fd0f429002ecb87#diff-b793ba6085845a09bf615ef5c58df900 fixed this

**Comment by vpapaioannou** [comment]
It's fixed for PyTorch releases >= 1.5. In PyTorch 1.4 which is the latest stable release is not fixed. This version is used also by Anaconda. Hence, ``kernel size`` and ``dilation`` options in ``Convnd`` cannot be used error free.

Finally, the fix, is not reflected into the documentation; no options are shown for ``padding_mode`` i.e. ``valid_padding_modes = {'zeros', 'reflect', 'replicate', 'circular'}``.

Let me know, if you would like me to help with updating the documentation.

Thanks.

**Comment by SsnL** [comment]
Fixes are not backported in general.

**Comment by vpapaioannou** [comment]
I understand that.

By the way, at [conv.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L28) 4 valid padding modes are defined whereas at [functional.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3385) 5 padding modes are defined.

Is this as expected?

**Comment by SsnL** [comment]
General constant padding mode is not integrated in conv. Correct me if I am wrong. My understanding is that nonzero constant paddings is uncommon in practice. Since it would complicate the API (adding another option `padding_value`) so extra explicit `nn.ConstantPadding` should be more desired for this case.

**Comment by vpapaioannou** [comment]
I totally agree. As of implementation, since ``functional.pad`` implements this constant - padding already, allowing users to use it would be alright. In conv.py, the padding( mode) is treated as

``
if self.padding_mode != 'zeros':

     return F.conv2d(F.pad(... mode=self.padding_mode), ...)
``

i.e. the handling of a padding mode is delegated to ``F.pad`` which already takes care of the constant wise padding.

So, I would let users to have that option since it is already implemented and to have a consistent "logic" across the code i.e. wherever functional.pad is used, the interface/options is the same.

Thanks for your comments and explanations.
