### ISSUE TITLE
binary cross entropy requires double tensor for target

### ISSUE THREAD

**Issue by Kuzphi** [pytorch/pytorch#3608]
```python
input = autograd.Variable(torch.randn(3), requires_grad=True)
target = autograd.Variable(torch.LongTensor(3).random_(2))
loss = F.binary_cross_entropy(F.sigmoid(input), target)
loss.backward()
```

```
RuntimeError: Expected object of type Variable[torch.FloatTensor] but found type Variable[torch.LongTensor] for argument #1 'target'
```

in latest release, binary_cross_entropy requires double tensor rather than long tensor.
 which does not make sense for cross entropy.

**Comment by zou3519** [comment]
I think BCELoss has always required a float or double tensor for its input: http://pytorch.org/docs/master/nn.html?highlight=bceloss#torch.nn.BCELoss (you can change the version number and the docs look the same).

Are you thinking of CrossEntropyLoss? That one takes LongTensors for target

**Comment by ShigekiKarita** [comment]
@Kuzphi  @zou3519 @soumith I think he might see this page http://pytorch.org/docs/master/nn.html#torch.nn.functional.binary_cross_entropy , it is not BCELoss page. As you mentioned, the documentation is wrong.
