### ISSUE TITLE
High GPU memory usage on master

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#3610]
Running cyclegan from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix on master takes huge amount of memory (>11G with default options). It only takes 3.5G on 0.3 and 0.2 branches. 

The memory usage increases as I run more iteration. It seems some tensors are not freed properly.

I remember running on a pre-ATen-merge version without such issue.

Repro command:
```
python train.py --dataroot ./datasets/maps --name maps_cyclegan --model cycle_gan --no_dropout --niter 1 --niter_decay 0 --no_html --max_dataset_size 10 --batchSize 1
```

By the way, this doesn't happen on the other model in the repo, pix2pix

**Comment by ducksoup** [comment]
We observed the same issues with many other kinds of CNNs, both in our own code and the pytorch examples.

For example, launching a resnet101 training on ImageNet with https://github.com/pytorch/examples/blob/master/imagenet/main.py on four Titan Xp works with v0.2 but immediately goes out of memory with master.

**Comment by soumith** [comment]
@ducksoup try out the `v0.3.0` branch, it should be stable and have most of the latest fixes.

**Comment by soumith** [comment]
@SsnL can you confirm that master is fixed on this issue? if not follow up with @colesbury

**Comment by SsnL** [comment]
@soumith It is indeed fixed. However, GPU memory consumption on master is about 4G rather than 3.5G on 0.2 and 0.3 branches.

**Comment by SsnL** [comment]
This seems fixed.
