### ISSUE TITLE
minor formatting issue in the quantization doc

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#36104]
As shown in the image below, a section on the static post training quantization workflow is a numbered list with a sub-list that should be presented in list format but appears instead in paragraph form. Not a big deal but would be easier to understand if it appeared more clearly as distinct items. 

<img width="1212" alt="nits-on-quant-doc-20200406" src="https://user-images.githubusercontent.com/45861273/78610335-77581c00-7819-11ea-86ba-ebe20e51945b.png">

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
This is not an issue in the latest version of the quantization docs https://pytorch.org/docs/stable/quantization.html
Closing.
