### ISSUE TITLE
Jitscript doesnot support tensor to list conversion?

### ISSUE THREAD

**Issue by merisgong208** [pytorch/pytorch#36117]
A simple test as follows:
`
#--------------------------------------------
import torch
def myadd(a):
    m = torch.tensor([1,2,a,5])
    list1 = list(m)
    return list1

m = torch.jit.script(myadd)
print(myadd(5))

`

#---------------------------------------
Traceback (most recent call last):
  File "xxx.py", line 28, in <module>
    m = torch.jit.script(myadd)
  File "D:\ProgramData\Anaconda3\envs\kkpytorch37\lib\site-packages\torch\jit\__init__.py", line 1289, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::list(str t) -> (str[]):
  Expected a value of type 'str' for argument 't' but instead found type 'Tensor'.
  
  aten::list.t(t[] l) -> (t[]):
  Could not match type Tensor to List[t] in argument 'l': Cannot match List[t] to Tensor.

The original call is:
  File "D:/PytorchProjects/yolov3-ultralytics-tracetest/kktest.py", line 23
    # type: (int) -> List[int]
    m = torch.tensor([1,2,a,5])
    list1 = list(m)
            ~~~~ <--- HERE
    #print(type(list1))#<class 'list'>
    return list1



cc @suo

**Comment by merisgong208** [comment]
import torch
from typing import List

def myadd(a:float):
    #m = (1.0, 2.0, a, 5) # OK
    m = [1.0, 2.0, a, 5] # error
    #m = [1.0, 2.0, a, 5.0] # OK
    return m

m = torch.jit.script(myadd)
print(myadd(5))

**Comment by merisgong208** [comment]
`import torch
from typing import List

def myadd(a:float):
    #m = (1.0, 2.0, a, 5) # OK
    m = [1.0, 2.0, a, 5] # error
    #m = [1.0, 2.0, a, 5.0] # OK
    return m

m = torch.jit.script(myadd)
print(myadd(5))`

**Comment by merisgong208** [comment]
import torch

def myadd(a:float):
         #m = (1.0, 2.0, a, 5) # OK
         m = [1.0, 2.0, a, 5] # error
         #m = [1.0, 2.0, a, 5.0] # OK
         return m

m = torch.jit.script(myadd)
print(myadd(5))

**Comment by suo** [comment]
Thanks for the report! We indeed do not have the `list()` builtin supported for tensors. On master, `tensor.tolist()` is supported (cc @SplitInfinity), which may be a feasible workaround.

Not sure if we have time to implement `list()` for tensors right now, as it's pretty niche, but we would be happy to review a PR to add it :)

**Comment by eellison** [comment]
I actually landed https://github.com/pytorch/pytorch/pull/33818/ but it got unlanded because one slow test timed out... i can reland at some point
