### ISSUE TITLE
unknown type name 'ssize_t' with gcc 4.8.5 on Linux

### ISSUE THREAD

**Issue by andreh7** [pytorch/pytorch#3611]
when building the pytorch head (1bf717e17) I get several errors like the following with gcc4.8.5 on Linux:

```
aten/src/TH/THMemoryFile.c: In function 'THMemoryFile_writeByte':
aten/src/TH/THMemoryFile.c:181:9: error: unknown type name 'ssize_t'
         ssize_t nByteWritten;                                           \
         ^
```

This can be fixed by adding 
```
#include <sys/types.h>
```

to `aten/src/TH/THMemoryFile.c`

(I'm happy to provide a pull request if wanted)

**Comment by soumith** [comment]
yes please, for Pull Request!

**Comment by andreh7** [comment]
The current head cc8fd5bd compiles for me now -- thanks for merging ! I'll close this issue.
