### ISSUE TITLE
how to get cuda stream in torch 1.5?

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#36132]
I previous using this get cuda stream:

```
modulated_deformable_col2im_coord_cuda(THCState_getCurrentStream(state),
```

I found this API gone `THCState_getCurrentStream` without even a deprecation warning, what's the altinate of this API?
in torch 1.5?

cc @yf225

**Comment by 522730312** [comment]
Hey, jinfa. Have you ever build torch 1.5 from source success?

**Comment by gchanan** [comment]
@jinfagang please ask questions on the forum (https://discuss.pytorch.org/) in the future.

But you should be able to use `c10::cuda::getCurrentCUDAStream()`.

**Comment by jinfagang** [comment]
@522730312 what do u mean by build success from source? I install nightly from pytorch.org. Also I am able to build source code sucessfully many times.

@gchanan Thanks so much, I will have a try. I post it here because it very common in many extensions such as DCNv2. I suppose other people might also have this issue.
