### ISSUE TITLE
Deterministic convolution is nondeterministically being nondeterministic on CUDNN 7

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3614]
Here are the most recent build logs with this problem:

* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py3-test/236/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py2-test/235/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py2-test/228/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py3-test/210/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py3-test/207/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda9-cudnn7-py2-test/202/console

The problem appears to only happen on CUDA9/CuDNN7. NVIDIA did not know of any known issues with deterministic convolution on M60s. The problem has reproduced on multiple GPU workers (0 and 2) so it is unlikely to be a worker misconfiguration.

Error traces:

```
23:59:46 ======================================================================
23:59:46 FAIL: test_Conv2d_deterministic_cudnn (__main__.TestNN)
23:59:46 ----------------------------------------------------------------------
23:59:46 Traceback (most recent call last):
23:59:46   File "test_nn.py", line 1863, in test_Conv2d_deterministic_cudnn
23:59:46     self.assertEqual(conv1.weight.grad.data, conv2.weight.grad.data, prec=0.0)
23:59:46   File "/var/lib/jenkins/workspace/test/common.py", line 204, in assertEqual
23:59:46     assertTensorsEqual(x, y)
23:59:46   File "/var/lib/jenkins/workspace/test/common.py", line 196, in assertTensorsEqual
23:59:46     self.assertLessEqual(max_err, prec, message)
23:59:46 AssertionError: 9.5367431640625e-07 not less than or equal to 0.0 : 
23:59:46 
23:59:46 ----------------------------------------------------------------------
```

```
22:49:20 ======================================================================
22:49:20 FAIL: test_Conv2d_deterministic_cudnn (__main__.TestNN)
22:49:20 ----------------------------------------------------------------------
22:49:20 Traceback (most recent call last):
22:49:20   File "test_nn.py", line 1863, in test_Conv2d_deterministic_cudnn
22:49:20     self.assertEqual(conv1.weight.grad.data, conv2.weight.grad.data, prec=0.0)
22:49:20   File "/var/lib/jenkins/workspace/test/common.py", line 204, in assertEqual
22:49:20     assertTensorsEqual(x, y)
22:49:20   File "/var/lib/jenkins/workspace/test/common.py", line 196, in assertTensorsEqual
22:49:20     self.assertLessEqual(max_err, prec, message)
22:49:20 AssertionError: 4.76837158203125e-07 not less than or equal to 0.0
```

CC @prigoyal

**Comment by ezyang** [comment]
From #devs:

> I suspect it might be something about concurrent runs of 2 backward passes https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L1860-L1861. Can you try putting cuda.synchronize between them and see if the problem persists? I'm still not able to see tolerance failure, only CUDNN_STATUS_NOT_SUPPORTED, which still should not happen, so there's a bug somewhere.

**Comment by ezyang** [comment]
I happened to be reading the deterministic algorithm selection code (for unrelated reasons), and I realized that we are falling back on nondeterministic algorithms if no deterministic ones are available:

```
template<typename perf_t>
perf_t getBestAlgorithm(perf_t *perfResults, bool deterministic, int n_algo) {
  if (deterministic) {
    // iterate over perf results of all algorithms and find the best deterministic algo
    for (int i = 0; i < n_algo; i++) {
      if (perfResults[i].status == CUDNN_STATUS_SUCCESS &&
          perfResults[i].determinism == CUDNN_DETERMINISTIC) {
        return perfResults[i];
      }
    }
  }
  return perfResults[0];
} 
```

This is bad, and probably related to the problem here. A plausible explanation is that, when running cudnnFindConvolutionForwardAlgorithmEx in multiple threads concurrently, deterministic algorithms may incorrectly be reported as not supported.

(I'm unfortunately knee deep refactoring this code, so I am not going to also attempt to fix this.)

**Comment by ngimel** [comment]
Usually there's at least one deterministic algo available (except for fp16, where there may be none), so while I agree that silent falling back is bad, it's likely not the primary culprit.

**Comment by apaszke** [comment]
It would still be nice to at least assert if we fail to find one

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/3631
