### ISSUE TITLE
len(DataLoader) doesn't take into account DataLoader.batch_size when using IterableDataset

### ISSUE THREAD

**Issue by Craigacp** [pytorch/pytorch#36176]
## 🐛 Bug

The length of a `DataLoader` when using a map `Dataset` is the defined by the sampler, usually defaulting to `BatchSampler`'s method which divides the number of examples in the dataset by the batch size. When using an `IterableDataset` it just returns `len(IterableDataset)`, rather than `len(IterableDataset) // batch_size`. If the `IterableDataset` defines `__len__`, and `loader.batch_size > 0` then the loader will only ever return `len(IterableDataset) // batch_size` batches, so the loader should return this as it's length. This occurs with single process data loading, I understand that multiprocess has other complexities which will cause this to fail in other ways.

## Expected behavior

`len(loader) == (len(dataset) // batch_size)`

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a

cc @SsnL

**Comment by belph** [comment]
This bit me today as well. Here is a simple test script to demonstrate this behavior:
```python
import torch
from torch.utils import data

class MapDataset(data.Dataset):
    def __len__(self):
        return 10

    def __getitem__(self, x):
        return x

class IterableDataset(data.IterableDataset):
    def __len__(self):
        return 10

    def __iter__(self):
        return iter(range(10))


map_loader = data.DataLoader(MapDataset(), batch_size=2)
iterable_loader = data.DataLoader(IterableDataset(), batch_size=2)

print(f"map:  {len(map_loader)}")
print(f"map data: {list(map_loader)}")
print(f"iter: {len(iterable_loader)}")
print(f"iter data: {list(iterable_loader)}")
# map:  5
# map data: [tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9])]
# iter: 10
# iter data: [tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9])]
```

**Comment by SsnL** [comment]
Thanks for reporting! Yes, this is a bug and should be fixed.

**Comment by choidongyeon** [comment]
Hi, I would like to work on this issue.
