### ISSUE TITLE
document depthwise convolution

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3618]
Right now, if folks come searching for depthwise convolution in the docs, they dont know that the `groups` setting in Conv*d is what they are looking for.

For such folks, document depthwise convolutions in docs, detailing equivalent argument conversions (depthwise_multiplier, etc.)

**Comment by killeent** [comment]
I should do this probably.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/commit/25b166ed1f58fe1ba255cf218f8b44bf7cc9bb5b
