### ISSUE TITLE
got cmakelists error

### ISSUE THREAD

**Issue by scirocc** [pytorch/pytorch#36204]
I try to create a simple project. And do the instructions as the' https://pytorch.org/cppdocs/installing.html' says.
"wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
unzip libtorch-shared-with-deps-latest.zip"

my cmakelists is like this:
`cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(libtorchTest)
find_package(Torch REQUIRED)`

and got that error:
`CMake Error at D:/Program Files/CLion2019.2.2/bin/cmake/win/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Torch (missing: TORCH_LIBRARY)
Call Stack (most recent call first):
  D:/Program Files/CLion2019.2.2/bin/cmake/win/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  G:/libtorch/share/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
  CMakeLists.txt:3 (find_package)
-- Configuring incomplete, errors occurred!`

 looks like the problem is from here "TorchConfig.cmake",line 130:
`find_package_handle_standard_args(Torch DEFAULT_MSG TORCH_LIBRARY TORCH_INCLUDE_DIRS)
`  Could NOT find Torch (missing: TORCH_LIBRARY)
what can I do to fix this problem?Any advice is highly appreciated!

**Comment by peterjc123** [comment]
Did you pass the correct `CMAKE_PREFIX_PATH` to cmake?

**Comment by scirocc** [comment]
> Did you pass the correct `CMAKE_PREFIX_PATH` to cmake?

cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(libtorchTest)
set(CMAKE_PREFIX_PATH "E:\\CLionProjects\\libtorchTest\\share\\cmake\\Torch")
find_package(Torch REQUIRED)
Thanks man，but after I adjust the cmakelists，the error is still the same

**Comment by peterjc123** [comment]
Please try `set(CMAKE_PREFIX_PATH "E:\CLionProjects\libtorchTest)`.

**Comment by scirocc** [comment]
> Please try `set(CMAKE_PREFIX_PATH "E:/CLionProjects/libtorchTest")`.

Thanks man，my bad，my platform is windows，but I unzip the linux version libtorch.
Now the problem is gone .
