### ISSUE TITLE
'off_t' undeclared with gcc 4.8.5 on Linux

### ISSUE THREAD

**Issue by andreh7** [pytorch/pytorch#3620]
(similar to #3611): with gcc 4.8.5 on Linux I get the following error (with the head from yesterday 1bf717e ):

```
/home/users/aholz/pytorch-head/aten/src/TH/THDiskFile.c:186:30: error: 'off_t' undeclared (first use in this function)
   if(fseeko(dfself->handle, (off_t)position, SEEK_SET) < 0)
```

Adding `#include <sys/types.h>` in `aten/src/TH/THDiskFile.c` fixes this. 

Should I open a new pull request for this (similar to #3612, with guard against `_WIN32`) or piggyback on #3612 ?

**Comment by apaszke** [comment]
I’m fine with both, whatever works for you

**Comment by andreh7** [comment]
ok added commit a1062cc62 to pull request #3612

**Comment by ezyang** [comment]
Let's consider adding CI against gcc 4.8. Probably doing just builds (not test) should be OK.

**Comment by andreh7** [comment]
in fact, I see a few more problems like the one in #3571 with gcc 4.8 but I'll wait until #3612 is sorted out.

**Comment by andreh7** [comment]
The current head cc8fd5bd compiles for me now -- thanks for merging ! I'll close this issue.
