### ISSUE TITLE
Non contiguous output of meshgrid

### ISSUE THREAD

**Issue by TropComplique** [pytorch/pytorch#36219]
## 🐛 Bug

Output of meshgrid is non contiguous. 
This behavior can easily cause hard to find bugs.

## To Reproduce

```python
import torch

y, x = torch.meshgrid(torch.arange(2), torch.arange(3))
assert (not y.is_contiguous()) and (not x.is_contiguous())

print(x)
print(y)
"""
tensor([[0, 1, 2],
        [0, 1, 2]])
tensor([[0, 0, 0],
        [1, 1, 1]])
"""

dx = torch.ones(2, 3)
dy = torch.ones(2, 3)

print(x + dx)
print(y + dy)
"""
tensor([[1., 2., 3.],
        [1., 2., 3.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) <- ERROR!
"""

print(x.contiguous() + dx)
print(y.contiguous() + dy)
# the output is correct here
```

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti

Nvidia driver version: 440.64.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1
[conda] numpy                     1.18.2                   pypi_0    pypi
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchvision               0.4.1                    pypi_0    pypi

cc @VitalyFedyunin @jamesr66a

**Comment by gchanan** [comment]
It's not in the operator contract that tensors are returned are contiguous and it shouldn't cause hard to find bugs as our operators work with non-contiguous tensors.  In fact, meshgrid needs to be implemented this way for performance reasons.

The issue you are seeing is a major bug in 1.3.0 that we fixed in 1.3.1 and is due to type promotion.
