### ISSUE TITLE
What kind of function does USE_QNNPACK do?

### ISSUE THREAD

**Issue by yoshihingis** [pytorch/pytorch#36210]
This is only Question, not BUG report.

[Question]
 What kind of function does USE_QNNPACK do?
If I will set USE_QNNPACK=1, build_pytorch.bat  build some patrs of codes will be build by quantized  8bit?    

Regards,

**Comment by gchanan** [comment]
please use the forums for questions, as we try to keep this clean for features/bug reports: https://discuss.pytorch.org/
