### ISSUE TITLE
Deserialize BERT Sequence Lassifier Quantized Model & Inferencing Issue #3695

### ISSUE THREAD

**Issue by suryapa1** [pytorch/pytorch#36218]
https://github.com/huggingface/transformers/issues/3695#issue-596475184

**Comment by gchanan** [comment]
is this a PyTorch issue?  I'm going to close this because it's not actionable.  But if you want to follow our template and expand on the issue, someone may be able to help you.

**Comment by gchanan** [comment]
trans
