### ISSUE TITLE
conda install torch?

### ISSUE THREAD

**Issue by cdeil** [pytorch/pytorch#3622]
Hi, I'm new to torch / pytorch, so apologies for the basic question!

I see at http://pytorch.org/ that `conda install pytorch` is supported and it works for me. But as far as I can see, I still need to install torch separately, it's not installed as a dependency? And from what I gather at http://torch.ch/docs/getting-started.html torch itself doesn't have a conda package at all?

If this is the case, maybe it would be worth mentioning something about installing `torch` in the `pytorch` install docs or about conda in the `torch` docs?

PS: my motivation to install torch / pytorch is to get https://github.com/jcjohnson/neural-style to run and see if it works on my images, but following their install instructions executes a bash script which tries to install brew on my Mac, which is not what I want.

**Comment by soumith** [comment]
`conda install pytorch` installs an old version of PyTorch that the anaconda team checked-in. you need to use `conda install pytorch -c soumith ...` the command from our website.

torch is a separate product from pytorch, pytorch has no depedency on torch. we are not going to add any details of installing it on the pytorch website. Right now torch can be installed from source using the page you pointed out, the install is a bit clunky with a shell script, no way around it.

**Comment by cdeil** [comment]
@soumith - OK, I understand now, thanks for your help!

To run https://github.com/jcjohnson/neural-style I need torch, not pytorch, and unfortunately there's no easy install via conda.

> torch is a separate product from pytorch, pytorch has no depedency on torch. 

Well, except from the name, the expectation that `pytorch` is strongly connected to `torch` is probably a mistake that new users like me that haven't used either package before are likely to make? So I still think a sentence at http://pytorch.org either in the install or on the about page explicitly stating that one doesn't need http://torch.ch/ would be helpful (especially given their complex install).

**Comment by saria85** [comment]
@cdeil I have the same problem.
Can you please let me know how did you resolve installing torch?

**Comment by cdeil** [comment]
@saria85 - I gave up on the torch install, and just used codes using pytorch and tensorflow where install is more pleasant.

**Comment by felexkemboi** [comment]
i need help on how i can install pytorch in my anaconda in ubuntu

**Comment by Eiad7** [comment]
@felexkemboi you can use this "conda install pytorch torchvision -c pytorch"

**Comment by NagabhushanSN95** [comment]
`pip install torch` worked for me
[see here](https://stackoverflow.com/a/53481440/3337089)

**Comment by jumorap** [comment]
`pip install torchvision --force --user`
`pip install pytorch==1.3.0 --force --user`

Worked for me. If don't works, try to use the "manager" Anaconda3, using:
`conda install torchvision`
`conda install  pytorch`
