### ISSUE TITLE
Fix MKL / Anaconda detection

### ISSUE THREAD

**Issue by edmBernard** [pytorch/pytorch#3623]
Is there a turorial to build pytorch from source with mkl support ?

**Comment by soumith** [comment]
These commands guide you to install with MKL https://github.com/pytorch/pytorch#from-source
Currently on master there is a small bug that was introduced last week where MKL detection is not working properly, I am fixing it.

**Comment by edmBernard** [comment]
yeah I used these instructions
I'll wait your fix
thanks for your answer

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/commit/5478d0154fca6859c2bd6c8147b6797074d1efcf

The latest master will detect MKL correctly.
Thanks for waiting.

**Comment by edmBernard** [comment]
@soumith thanks a lot
