### ISSUE TITLE
[JIT] Doesn't support dict() 

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#36247]
```py
my_dict : Dict[int, Tensor] = dict()
```
Error is it expects one arg.

Have to work around it.
```py
my_dict : Dict[int, Tensor] = {}
```

Same for list,
```py
my_list : List[int] = list()
```
Error is it expects one arg.

Have to work around it.
```py
my_list : List[int] = []
```

cc @suo @gmagogsfm

**Comment by mrshenli** [comment]
If no one is working on this, I would like to reserve it for bootcamp.

**Comment by mrshenli** [comment]
un-assign myself. This is no longer reserved for bootcamp. Please feel free to grab it if you are interested.

**Comment by gmagogsfm** [comment]
Assigning to myself, reserved for bootcamp

**Comment by ansley** [comment]
Task is more complex than it seems. Tags changed at the suggestion of @gmagogsfm

**Comment by gmagogsfm** [comment]
As far as I know this is implemented by @ansley. Closing.
