### ISSUE TITLE
nn.Module.cuda() is not propagated to submodules in v0.3.0

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#3626]
To reproduce:
```sh
git clone git@github.com:uber/pyro
cd pyro
pip install .
python examples/vae.py -n 1 --cuda
```
This works with pytorch `0.2.0_4` but fails with `v0.3.0` as of 1f694e9

See https://github.com/uber/pyro/issues/554
CC: @zou3519 @soumith

**Comment by zou3519** [comment]
@fritzo It doesn't seem to error out for me:
![image](https://user-images.githubusercontent.com/5652049/32670537-0d25aaac-c612-11e7-8c20-8b922b64fcf7.png)
Could you show the output of your `torch.__version__`?

**Comment by fritzo** [comment]
`torch.__version__ == 0.3.0b0+1f694e9`

**Comment by fritzo** [comment]
@zou3519 sorry, I was testing on the `0.1.1` release of Pyro. You're right: the tests pass on Pyro dev (and with the 0.1.2 patch release we're planning to release today). Sorry for misattributing this bug, it was probably due to a bug on our side.
