### ISSUE TITLE
Extra whitespace issue when printing complex tensors

### ISSUE THREAD

**Issue by choidongyeon** [pytorch/pytorch#36279]
Printing complex tensors yields extra white spaces that follow the element. This seems to be related to the way that ```self.max_width``` is set in the Formatter constructor.

This is a follow up to the conversation that can be found here: https://github.com/pytorch/pytorch/pull/35841

## To Reproduce

```
print(torch.tensor([[1 + 1.340j, 3 + 4j], [1.2 + 1.340j, 6.5 + 7j]], dtype=torch.complex64))
```
Will yield
```
tensor([[                     (1.0000 + 1.3400j),
                              (3.0000 + 4.0000j)],
        [                     (1.2000 + 1.3400j),
                              (6.5000 + 7.0000j)]], dtype=torch.complex64)
```

## Expected behavior

Instead, we want it to look like

```
tensor([[(1.0000 + 1.3400j),
         (3.0000 + 4.0000j)],
        [(1.2000 + 1.3400j),
         (6.5000 + 7.0000j)]], dtype=torch.complex64) 
```

cc @ezyang @anjali411 @dylanbespalko

**Comment by choidongyeon** [comment]
I will work on this issue, but in the meantime, if there are any other suggestions on any additional changes we'd like to see in the expected print behavior, I would love your input!

**Comment by anjali411** [comment]
Thanks @choidongyeon keep me updated and let me know if you need any help.

**Comment by choidongyeon** [comment]
Changes have been merged, closing issue.
