### ISSUE TITLE
why the quantized weights are showed in wrong values?

### ISSUE THREAD

**Issue by HumberMe** [pytorch/pytorch#36304]
## ❓ Questions and Help
how to get the right values of quantized weights(in uint8 format)?
the image showed below is a conv module I quantized, and either the number of weights or the values are not right

![1](https://user-images.githubusercontent.com/40233154/78878092-6828d680-7a84-11ea-9114-c2e0d11f45c8.png)

- [Discussion Forum](https://discuss.pytorch.org/)

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by z-a-f** [comment]
Are you printing the weights? It might be that you are seeing the packed weights.

**Comment by HumberMe** [comment]
> Are you printing the weights? It might be that you are seeing the packed weights. Can you, please, post what's the code that is printing this?

Yes, i do print the packed weights, and my issue is how to get the weights(in int8 format) from the quantized model, after all, the only weights of quantized model i can see is the packed weights. 
I print the packed weights in the pycharm debugger,  the code fragment is something like "print(quantized_,model.conv1._packed_params)"
By the way, what do packed params stand for?

**Comment by supriyar** [comment]
@HumberMe quantization backends like FBGEMM and QNNPACK pre-pack the weights one time into a format that is based on the backend and makes the actual computation faster.  
If you want to access the original weight you can call the `weight` method on the quantized module. 
https://github.com/pytorch/pytorch/blob/67e0bf14b734f9dfc312d811922b4c04709e4672/torch/nn/quantized/modules/conv.py#L329

Please use discussion forum (https://discuss.pytorch.org/c/quantization/17) for questions that are not an issue or feature request.
