### ISSUE TITLE
Docs should say that standard arithmetic operations for torch.half are not supported

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#36318]
## 🐛 Bug

Standard arithmetic operations with `dtype==torch.half` are broken.

## To Reproduce

```python
import torch

x = torch.tensor(1.0, dtype=torch.half)

x + 1.0
x - 1.0
x * 1.0
x / 1.0
```

```
RuntimeError: "add_cpu/sub_cpu" not implemented for 'Half'
RuntimeError: "mul_cpu" not implemented for 'Half'
RuntimeError: "div_cpu" not implemented for 'Half'
```
## Environment

```
Collecting environment information...
PyTorch version: 1.6.0a0+3d199aa
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.6.0a0+3d199aa
[pip3] torchvision==0.6.0a0+684f48d
[conda] Could not collect
```

Build from source a few hours ago.

cc @ezyang @gchanan @zou3519

**Comment by pmeier** [comment]
Same error for 

```python
x ** 2.0
torch.sqrt(x)
torch.max(x)
torch.ceil(x)
```

**Comment by vadimkantorov** [comment]
Half is not supported on CPU I think. On CPU you can use another type - bfloat16 (which has different precision properties compared to Half, though)

**Comment by pmeier** [comment]
@vadimkantorov That indeed works. Is there any documentation on this? The [documentation about `dtype`](https://pytorch.org/docs/stable/tensor_attributes.html?highlight=dtype#torch.torch.dtype) does not list `torch.bfloat16`.

**Comment by vadimkantorov** [comment]
That's a good question to real PyTorch team members :)

**Comment by zhangguanheng66** [comment]
We should update the doc of either `torch.half` or `torch.bfloat16` in order to close the issue.

**Comment by malfet** [comment]
Latest nighly supports basic math operations over torch.half, although they will be pretty slow (since type is not natively supported on the CPU.

**Comment by mattip** [comment]
The fixes for both documentation and the implementation sides of this issue are merged. Closing. Please reopen if needed.
