### ISSUE TITLE
torch.eye cpu not supported for complex

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#36327]
>>> import numpy as np
>>> np.eye(2,dtype=np.complex64)
array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]], dtype=complex64)
>>> import torch
>>> torch.eye(2, dtype=torch.complex64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "eye" not implemented for 'ComplexFloat'

cc @ezyang @anjali411 @dylanbespalko

**Comment by imskr** [comment]
Please assign this to me @anjali411

**Comment by imskr** [comment]
@anjali411 Can you please tell me which file I have to make changes?

**Comment by imskr** [comment]
This is closed, i was working? @anjali411
