### ISSUE TITLE
masked_fill not implemented for complex

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#36322]
>>> import torch
>>> x=torch.zeros(2,3, dtype=torch.cfloat)
>>> mask =torch.zeros(2,3,dtype=torch.long)
>>> mask[0][1]=1
>>> x.masked_fill(mask, 2+3j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "masked_fill" not implemented for 'ComplexFloat'

cc @ezyang @anjali411 @dylanbespalko

**Comment by imskr** [comment]
@anjali411 Can I work on this?

**Comment by anjali411** [comment]
> @anjali411 Can I work on this?

I already made a patch for this but here's another similar issue: https://github.com/pytorch/pytorch/issues/36327 if you'd like to work on it
