### ISSUE TITLE
torch.gather doesn't work for complex tensors

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#36340]
>>> torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: method_name not implemented for 'ComplexFloat'

cc @ezyang @anjali411 @dylanbespalko

**Comment by nuka137** [comment]
I would like to tackle this issue.

**Comment by anjali411** [comment]
> I would like to tackle this issue.

sounds good! let me know if you have any questions. feel free to add me for the PR review once you have a working PR

**Comment by dvlshah** [comment]
I am looking to contribute. Can you please help me on how to get started?

**Comment by anjali411** [comment]
@nuka137 please test torch.gather in test_torch where this function is tested for other dtypes

**Comment by nuka137** [comment]
@anjali411 

Thanks for your instruction. I'll tackle them.
