### ISSUE TITLE
/app/install/libtorch/examples-cpp/cpp/example-app/example-app.cpp:9:24: error: 'indexing' is not a namespace-name

### ISSUE THREAD

**Issue by Edwardmark** [pytorch/pytorch#36359]
I try to use index namesapce, with 
using namespace torch::indexing
but I got the error:
/app/install/libtorch/examples-cpp/cpp/example-app/example-app.cpp:9:24: error: 'indexing' is not a namespace-name
 using namespace torch::indexing
 why is that?

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions. Thank you
