### ISSUE TITLE
how to ensure the quality of pytorch framework?

### ISSUE THREAD

**Issue by MountainHil** [pytorch/pytorch#36367]
Hi, I am a postgrad student, and I am developing my own deep-learning framework inside my lab, I just curious about how you guys maintained your framwork?Besides unit tests, is there any methods that can guarantee qulity?

**Comment by choidongyeon** [comment]
I don't have a direct answer to your question, but I think this question is better suited for PyTorch forums: https://discuss.pytorch.org/ as this isn't really an issue and more a request for information and discussion.
