### ISSUE TITLE
The jit misinterprets complex values as integers

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36368]
```
import torch

def fn(a):
    return a + (1 + 1j)

t = torch.tensor((1,))
print(fn(t))

scripted = torch.jit.script(fn)
print(scripted(t))
```

Will print
```
tensor([(2.+1.j)], dtype=torch.complex64)
tensor([3])
```

The latter result is, of course, wrong. It appears the jit is interpreting 1+1j as 2. 

cc @suo @ezyang @anjali411 @dylanbespalko

**Comment by choidongyeon** [comment]
I would like to take a look into this.

**Comment by mruberry** [comment]
Hi @choidongyeon! Thanks for your interest. You should ask @suo, I'm not sure what his thinking on this issue is.

**Comment by eellison** [comment]
@choidongyeon probably the first step here is just to throw an error when we encounter a complex value - that can probably be done in frontend.py but I could be wrong.

**Comment by eellison** [comment]
Reassigning as I think this is in progress

**Comment by anjali411** [comment]
closed by https://github.com/pytorch/pytorch/pull/52881
