### ISSUE TITLE
Accept tensor-like objects in place of tensor inputs

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36363]
In NumPy, array-like objects, like tuples and lists, can substitute for arrays. For example, the following is possible in NumPy:

```
a = np.array((1, 2))
tup = (3, 4)

np.add(tup, a)
np.add(a, tup)
np.add(tup, tup)

tup + a
a + tup
```

In PyTorch, tuples lists and NumPy arrays should be tensor substitutes, too. Today, however, the following operations will throw an error:

```
t = torch.tensor((1, 2))

torch.add(tup, t)
torch.add(t, tup)
torch.add(tup, tup)

torch.add(a, t)
torch.add(t, a)

tup + t
t + tup

a + t
```

Note that `t + a` DOES work in current PyTorch.

**Comment by gchanan** [comment]
can the JIT handle it? :).

**Comment by mruberry** [comment]
Dupe of https://github.com/pytorch/pytorch/issues/11695.
