### ISSUE TITLE
torch.utils.data.DataLoader multiprocess hanging when matplotlib.pyplot imported after torch

### ISSUE THREAD

**Issue by parkseobin** [pytorch/pytorch#36375]
## 🐛 Bug

 For some reason, `torch.utils.data.DataLoader` hangs on multiprocess setting (`num_workers>0`) when `matplotlib.pyplot` is imported after `torch`. Many pytorch codes, including [pytorch tutorials](https://github.com/pytorch/tutorials) imports `matplotlib.pyplot` AFTER `torch`, so this is very concerning. I would like to know why this happens and whether there exists a general fix for this problem. 

## To Reproduce

1. `DataLoader` with `matplotlib.pyplot`
```python
import torch
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


if __name__=='__main__':
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(torch.cuda.get_device_name(device=device))

    dataset = datasets.FakeData(transform=transforms.ToTensor())
    loader = DataLoader(dataset, batch_size=4, num_workers=4, timeout=5)
    iterator = iter(loader)
    try:
        sample_data = next(iterator)
        print('\n[*] Success: ({})\n'.format(sample_data[0].shape))
    except RuntimeError as err:
        print('\n[*] Runtime error ({})\n'.format(err)
```

Output:
```
GeForce RTX 2080 Ti

[*] Runtime error (DataLoader timed out after 5 seconds)
```

</br>

2. `DataLoader` without `matplotlib.pyplot` (commented out)
```python 
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


if __name__=='__main__':
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(torch.cuda.get_device_name(device=device))

    dataset = datasets.FakeData(transform=transforms.ToTensor())
    loader = DataLoader(dataset, batch_size=4, num_workers=4, timeout=5)
    iterator = iter(loader)
    try:
        sample_data = next(iterator)
        print('\n[*] Success: ({})\n'.format(sample_data[0].shape))
    except RuntimeError as err:
        print('\n[*] Runtime error ({})\n'.format(err)
```

Output:
```
GeForce RTX 2080 Ti

[*] Success: (torch.Size([4, 3, 224, 224]))
```

## Expected behavior

 I expect `[*] Success:` log at both 1., 2. tests. 

## Environment

Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 418.67
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21

Versions of relevant libraries:
[pip3] numpy==1.11.0
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.3.1           cuda100py37h53c1284_0  
[conda] torchvision               0.4.2           cuda100py37hecfc37a_0

## Additional context

`matplotlib` version is 3.1.3. 
Both tests (1., 2.) works fine with on CPU setting (`device = 'cpu'`) and `num_workers=0` setting. 

Thnak you!

cc @SsnL

**Comment by SsnL** [comment]
Interestingly the script works for me properly on newer pytorch versions. Could you try 1.5.0?

**Comment by parkseobin** [comment]
The script seems to work fine on PyTorch version 1.9.0.
