### ISSUE TITLE
Incorrect view behavior for split/split_with_sizes/chunk

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#36403]
These three functions are not properly listed as view ops in `tools/gen_autograd.py`.
First attempt to fix it in https://github.com/pytorch/pytorch/pull/32044 was reverting because it breaks many valid user code.

This happens because even though the views returned are non-overlapping, the inplace detection code we have today is not able to handle that and mark all the views as modified.
This is actually safe to do as long as only the views are modified and not the base. Or only the base and not the views.

### Attempt 1 (failed)
In https://github.com/pytorch/pytorch/pull/32044 I tried to only allow what we can handle with the current inplace checks.
But these functions are widely used and so I had to revert the diff because it breaks a lot of correct user code.

### Attempt 2 (Too complex)
Add the ability to handle these non-overlaping views in our inplace detection code.
The current implementation is a version counter associated with the base and shared with all the views.
This is very simple and efficient (both for speed and memory).

A proposed new API + implementation can be found in this gist: https://gist.github.com/albanD/b6d65740ece54056b750186b4aec2507
The basic idea is to make the version counter to be a tree with the root being the base. And the logic to bump the version counter walks the tree.

Unfortunately, because of the very big increase in complexity and the big regression in terms of memory usage, we did not try to implement this further.

### Attempt 3
Given that we cannot fix all the valid use case in an efficient manner, the final proposal here is going to make the general version safe and provide an unsafe version for users that know what they're doing.
This means the following plan:
- Escape hatch: Introduce `unsafe_*` version of the three functions above that have the current behavior (outputs not tracked as views). The documentation will explain in detail why they are unsafe and when it is safe to use them. (basically, only the outputs OR the input can be modified inplace but not both. Otherwise, you will get wrong gradients).
- Deprecation: Use the `CreationMeta` on views to track views created by these three ops and throw warning when any of the views is modified inplace saying that this is deprecated and will raise an error soon. For users that really need to modify these views inplace, they should look at the doc of the `unsafe_*` version to make sure their usecase is valid:
  - If it is not, then pytorch is computing wrong gradients for their use case and they should not do inplace anymore.
  - If it is, then they can use the `unsafe_*` version to keep the current behavior.
- Removal: Use the `CreationMeta` on view to prevent any inplace on these views (like we do for all other views coming from multi-output Nodes). The users will still be able to use the `unsafe_` versions if they really need to do this.

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @cpuhrsch @mruberry that were interested in this issue.

**Comment by vadimkantorov** [comment]
`unbind` should be added to the list?

**Comment by albanD** [comment]
`unbind` is already properly listed as a view and is already safe. So no need to add it here.
The "unpacking" as a set of Tensors use `select()` which is also already in the view list and is properly safe.

**Comment by vadimkantorov** [comment]
Oh cool :) I just remembered there was sth strange about unbind + inplace ops in https://github.com/pytorch/pytorch/issues/31819

**Comment by cpuhrsch** [comment]
I still like this approach! Are there any updates?

**Comment by albanD** [comment]
I don't think anyone complained about it. So it should be good to go forward with 3.

**Comment by vadimkantorov** [comment]
Will (3) prevent inplace ops on splitted tensors? Same would be for unbind? Then https://github.com/pytorch/pytorch/issues/31819 would be impossible: in there was big tensor first allocated, and then chunks are filled with inplace.

**Comment by albanD** [comment]
You will still be able to do it with the `unsafe_*` version of these functions.
But the thing is that the autograd/inplace check do not handle that. Inplace checks could be fixed with a more complex version counter logic (at a price in perf), but the autograd won't support multi-output Node views any time soon.

**Comment by Baranowski** [comment]
I will work on (3).

**Comment by Baranowski** [comment]
@albanD, should `unbind` also be turned into `unsafe_unbind` and `unbind`? Currently I get:

```
In [37]: x1,x2,x3 = a.unbind()

In [39]: x1.add_(1.0)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-39-23ec30446112> in <module>
----> 1 x1.add_(1.0)

RuntimeError: Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

AFAICT, this is currently the only built-in op that produces views with `CreationMeta::MULTI_OUTPUT_NODE`

**Comment by albanD** [comment]
Unbind has the correct behavior. So no need for an unsafe version.
The unsafe version is just for backward compatibility purposes and make sure we provide a way for users with working code to have their code still work.

**Comment by vadimkantorov** [comment]
Unsafe unbind version can be useful even for non-legacy code when the unbind() purpose was to save on many allocations/concatenations for target tensors and do one big allocation (the original usecase in https://github.com/pytorch/pytorch/issues/31819) prefilled with zeros

**Comment by albanD** [comment]
Given that these functions will be *very* unsafe as can very easily lead to silently wrong gradients, I don't think we want to create too many of them.
The ultimate goal here would be to improve the version checking and remove these unsafe_ functions altogether.
