### ISSUE TITLE
torch.select errors on index=-1

### ISSUE THREAD

**Issue by eladhoffer** [pytorch/pytorch#3642]
To reproduce:
`x=torch.rand(3,3);
x.select(0, -1)
`
This happens on master, but not on 0.2

**Comment by zou3519** [comment]
It doesn't work for me on 0.2 or master:
```
>>> import torch
>>> torch.__version__
'0.2.0+0b92e5c'
>>> x = torch.randn(3, 3)
>>> x.select(0, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 3: out of range at /home/rzou/pytorch/torch/lib/TH/generic/THTensor.c:458
```

I'm not sure if this is supposed to work (it probably is), but as a workaround, `x[-1]` works and should be equivalent to `x.select(0, -1)` if it worked.

**Comment by zou3519** [comment]
Looking into fixing this.

**Comment by zou3519** [comment]
`x.select(0, -1)` works when `x` is a Variable. We're deleting all of the tensor methods when the tensor/variable merge happens, so this will be fixed when that happens.

**Comment by zou3519** [comment]
I've verified this has been fixed on master after the Tensor/Variable merge.
