### ISSUE TITLE
Softmax only taking one arguement

### ISSUE THREAD

**Issue by lren90** [pytorch/pytorch#3643]
Per pytorch documentation (http://pytorch.org/docs/master/nn.html#torch-nn-functional)  the softmax function should be able to take dimension as an input.  However, I'm getting this error: TypeError: softmax() takes exactly 1 argument (2 given).

**Comment by apaszke** [comment]
You're looking at `master` branch docs (see `/docs/master` in the URL). To get this functionality install from source or wait until the next release (should happen this week).
