### ISSUE TITLE
torch.isclose is not implemented for cpu half tensors

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36451]
```
a = torch.tensor((1.,), dtype=torch.half)
b = torch.tensor((1.,), dtype=torch.half)
torch.isclose(a, b)
```

results in 

```
RuntimeError: "mul_cpu" not implemented for 'Half'
```

**Comment by vadimkantorov** [comment]
is it same reason as https://github.com/pytorch/pytorch/issues/36318 ? almost no operations are supported for half on cpu, right? (except fakefp16 support is implemented into pytorch, not just in caffe2?)

**Comment by mruberry** [comment]
Looks like the same underlying reason, yep.

**Comment by malfet** [comment]
Trying to address that one in https://github.com/pytorch/pytorch/pull/37121

**Comment by malfet** [comment]
@mruberry, works in latest nightly, mind closing this one?

**Comment by mruberry** [comment]
@malfet Cool!
