### ISSUE TITLE
torch.cuda.amp.GradScaler: RuntimeError

### ISSUE THREAD

**Issue by jpcenteno80** [pytorch/pytorch#36466]
## 🐛 Bug

@mcarilli:
Getting the following error at random while training a 3d segmentation network using `amp.autocast()` and `amp.GradScaler()`.
`RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/autograd/engine.cpp:926, please report a bug to PyTorch.`

The Traceback is as follows:
```
Traceback (most recent call last):
  File "lungs_training.py", line 95, in <module> 
    run()
  File "lungs_training.py", line 92, in run
    benchmark=True)
  File "/data/QILCode/python/development/qiltoolkit/qiltoolkit/basic_engine.py", line 105, in train
    self.run_backward_and_step(loss)
  File "/data/QILCode/python/development/qiltoolkit/qiltoolkit/basic_engine.py", line 185, in run_backward_and_step
    self.scaler.scale(loss).backward()
  File "/home/qiluser/miniconda3/envs/qiltoolkit/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/qiluser/miniconda3/envs/qiltoolkit/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED at /pytorch/torch/csrc/autograd/engine.cpp:926, please report a bug to PyTorch.
```

## To Reproduce

Modified DeepLabV3Plus architecture to allow for 3d segmentation. Since error seems to be coming up here: `self.scaler.scale(loss).backward()` it could be related to the loss function I'm using:
```
def one_hot(labels, nc, device=None, dtype=None, eps=1e-6):
    batch_size, height, width, depth = labels.shape
    one_hot = torch.zeros(batch_size, nc, height, width, depth, device=device,
                          dtype=dtype)
    return one_hot.scatter_(1, labels.unsqueeze(1), 1.0) + eps

class TverskyLoss3d(nn.Module):
    def __init__(self, nc, tversky_beta=0.45, raw_logits=True):
        super().__init__()
        self.nc = nc
        self.raw_logits = raw_logits
        self.eps = 1e-6
        self.beta = tversky_beta
        self.alpha = 1 - self.beta

    def forward(self, pred, target):
        if self.raw_logits:
            pred_soft = F.softmax(pred, dim=1)
        else:
            pred_soft = pred.exp()
        ones = pred_soft*0 + 1.0

        target_one_hot = one_hot(target, nc=self.nc, device=pred.device,
                                 dtype=pred.dtype)

        dims = (0,2,3,4)
        intersection = (pred_soft * target_one_hot).sum(dims)
        fps = torch.sum(pred_soft * (ones - target_one_hot), dims)
        fns = torch.sum((ones - pred_soft) * target_one_hot, dims)

        numerator = intersection
        denominator = intersection + self.alpha * fps + self.beta * fns

        tversky_idx = \
        torch.ones((self.nc)).cuda(pred.device) - ((numerator + self.eps)/(denominator + self.eps))
        
        return tversky_idx.sum()
```
The forward and backward passes are computed like this (with the attribute `self.mixed_prec==True` and `self.scaler = torch.cuda.amp.GradScaler()`):
```
    def zero_opt_and_calc_batch_stats(self, x, y):
        y = y.cuda(self.dev)
        self.optimizer.zero_grad()
        if self.mixed_prec:
            with autocast():
                out = self.model(x.cuda(self.dev))
                return self.criterion(out, y), self.metric_fn(out, y), out
        else:
            out = self.model(x.cuda(self.dev))
            return self.criterion(out, y), self.metric_fn(out, y), out

    def run_backward_and_step(self, loss):
        if self.mixed_prec:
            self.scaler.scale(loss).backward()
            self.scaler.step(self.optimizer)
            self.scaler.update()
        else:
            loss.backward()
            self.optimizer.step()
```
I also had to modify `nn.Conv3d` module to clamp output within the FP16 range:
```
class ClampedConv3d(nn.Conv3d):
    '''
    Modified nn.Conv3d that clamps output to FP16 range avoiding infinity.
    '''
    def __init__(self, in_channels, out_channels, kernel_size, stride=1,
                 padding=0, dilation=1, groups=1, bias=True,
                 padding_mode='zeros', **kwargs):
        self.fp16 = None
        if 'fp16' in kwargs:
            self.fp16 = kwargs['fp16']
            kwargs.pop('fp16')
        super().__init__(in_channels, out_channels, kernel_size, stride,
                         padding, dilation, groups, bias, padding_mode)

    def forward(self, input):
        if self.padding_mode == 'circular':
            expanded_padding = ((self.padding[2] + 1) // 2, self.padding[2] // 2,
                                (self.padding[1] + 1) // 2, self.padding[1] // 2,
                                (self.padding[0] + 1) // 2, self.padding[0] // 2)
            output = F.conv3d(F.pad(input, expanded_padding, mode='circular'),
                              self.weight, self.bias, self.stride, expanded_padding,
                              self.dilation, self.groups)
            if self.fp16:
                output = torch.clamp(output, -6.55e4, 6.55e4)
            return output
        output = F.conv3d(input, self.weight, self.bias, self.stride,
                          self.padding, self.dilation, self.groups)
        if self.fp16:
            output = torch.clamp(output, -6.55e4, 6.55e4)
        return output
```
The model is also wrapped with `nn.DataParallel`, input size is `2x3x256x256x256` and `torch.backends.cudnn.benchmark = True`.

## Expected behavior

Be able to complete mixed precision training.

## Environment

PyTorch version: 1.6.0.dev20200406+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.16.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 435.21
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.6.0.dev20200406+cu101
[pip] torchvision==0.6.0.dev20200406+cu101
[conda] numpy                     1.18.1           py37h8960a57_1    conda-forge
[conda] torch                     1.6.0.dev20200406+cu101          pypi_0    pypi
[conda] torchvision               0.6.0.dev20200406+cu101          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @ngimel

**Comment by ezyang** [comment]
cc @ilia-cher for Future related

**Comment by albanD** [comment]
cc @wanchaol that introduced this logic recently.

**Comment by mcarilli** [comment]
@jpcenteno80 The autocast state is thread local, and `DataParallel` spawns side threads internally.  See if the [recommended DataParallel usage](https://pytorch.org/docs/master/notes/amp_examples.html#dataparallel-in-a-single-process) fixes your script.

Also, for general convenience, use `autocast` and `GradScaler`'s `enabled=True|False` arguments so you don't have to litter your code with if statements.  For example, instead of
```
        if self.mixed_prec:
            with autocast():
                out = self.model(x.cuda(self.dev))
                return self.criterion(out, y), self.metric_fn(out, y), out
        else:
            out = self.model(x.cuda(self.dev))
            return self.criterion(out, y), self.metric_fn(out, y), out
```
write
```
        with autocast(enabled=self.mixed_prec):
                out = self.model(x.cuda(self.dev))
                return self.criterion(out, y), self.metric_fn(out, y), out
```

**Comment by jpcenteno80** [comment]
Thanks @mcarilli. I've restructured the forward call of the model as follows:
```
class seg3d_mod(nn.Module):
    def __init__(self, fp16=True):
        super().__init__()
        self.fp16 = fp16
        ...
    def forward(self, inp):
        with autocast(enabled=self.fp16):
            ...
            return x
```
While keeping the following in the forward pass:
```
        with autocast(enabled=self.mixed_prec):
            out = self.model(x.cuda(self.dev))
            return self.criterion(out, y), self.metric_fn(out, y), out
```
Everything works fine on single GPU. I am waiting on training to complete on another GPU before I can re-test `nn.DataParallel` again. I will report back so that I can close the issue. Thanks!

**Comment by mcarilli** [comment]
To be clear, the additional `autocast` embedded in `model.forward` is only necessary for `DataParallel`, not single-GPU, because on single-GPU `forward` runs on the main thread (unless you manually fork off new threads).

**Comment by jpcenteno80** [comment]
Thanks for the clarification @mcarilli. I fixed the code by adding a "parallel" boolean argument to the model instantiation that will toggle `autocast()` on or off.
However, I am still running into the issue mentioned at the top of this thread when running the model in `nn.DataParallel` mode. When I was first testing this architecture, I noticed that clearing the cuda cache after each iteration helped me squeeze in a larger input to the model. I wonder if that is screwing things up. I have turned it off and letting something run. Here is the call to clear the cuda cache that I have turned off:
```
manage_mem = False

for i, (x, y) in enumerate(trn_loader):
    "forward and backward passes..."
    if manage_mem: torch.cuda.empty_cache()
   ....
```

**Comment by mcarilli** [comment]
> I have turned it off and letting something run.

Do you mean without the `empty_cache()` call, DataParallel + native Amp runs without errors?

**Comment by jpcenteno80** [comment]
Yes, so far no errors without the `empty_cache()` call, DataParallel + native Amp. However, I will keep monitoring it as the model takes several days to train and the error seems to have appeared at random times during training. Just wanted to give an update of the actions taken with my previous post.

**Comment by mcarilli** [comment]
That's good to know.  I'm not sure what the pathologic interaction with `empty_cache` might be, that can have complex consequences.  In any case `empty_cache` is a heavyweight call that synchronizes and does a lot of deep memory movement, so calling it each iteration isn't great for performance.  Hopefully autocast itself (without empty_cache) provides enough memory savings to get you where you need to be.

**Comment by jpcenteno80** [comment]
Thanks for the tip on the `empty_cache()` call. I got rid of it and the model trained for almost two days in `nn.DataParallel` mode, with native AMP, but it just died again with the same error as above. Could the error be related to this: `torch.backends.cudnn.benchmark = True`?

**Comment by mcarilli** [comment]
The error message you observe is not a consequence of Amp that I've seen before, so I don't know.  Can you also print `scaler.get_scale()` every iteration?  A very small scale value indicates the scaling logic is causing too many infs/nans.  A value > 1 usually means training is numerically healthy at that point.

**Comment by jpcenteno80** [comment]
Thanks, I'll give that a try (forcing the loss to be at FP32). I also printed out`scaler.get_scale()` at each iteration and it is still at the default value of 2^16 when it fails with the same error. The error also appears to come up much faster when I resume training from a long trained checkpoint. For example, in this latest try, I loaded the checkpoint that trained for over 5000 iterations, resumed training, and it failed after 50 iterations.

**Comment by mcarilli** [comment]
Did you try the loss function in fp32?  Is this issue otherwise resolved?
>The error also appears to come up much faster when I resume training from a long trained checkpoint.
Use [scaler.state_dict() and load_state_dict()](https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html#saving-resuming) for bitwise accurate saving/restoring of runs with gradient scaling.

Closing for now due to inactivity, please reopen if you have updates.
