### ISSUE TITLE
torch.isclose for complex tensors

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36462]
Issue https://github.com/pytorch/pytorch/issues/36029 requests several functions be implemented for complex tensors, including torch.isclose. This issue separates the isclose discussion since it's nuanced and we have a choice of behaviors to implement.

@ngimel and I think there are two candidates for torch.isclose behavior.

The first is to be like NumPy's [isclose](https://numpy.org/doc/1.18/reference/generated/numpy.isclose.html?highlight=isclose#numpy.isclose). This function appears to be broken when dealing with non-finite values, however. See [this issue](https://github.com/numpy/numpy/issues/15959). One possible fix is to handle non-finite values like Python's cmath.isclose, where if a non-finite value is present two complex numbers are "close" only if they are identical. In particular, this approach would:

- When the imaginary and real parts of the complex numbers are finite, the typical isclose() algorithm of `abs(a - b) <= (atol + rtol * abs(b))` is used. (Consistent with current NumPy on finite values, divergent from cmath which uses a symmetric comparison. Torch is already consistent with NumPy for floats.)
- If any part is -inf or inf, the numbers must be identical.
- If any part is NaN, the numbers are never close, unless equal_nan=True, in which case NaN is treated like an infinity and the numbers must be identical.

Requiring the real and imaginary part of a complex number be identical is a stringent test, and likely not what we want in our test suite. A second option, then, is to compare the complex numbers' parts. That is, torch.isclose(Complex) = torch.isclose(Real) and torch.isclose(Imag). This would make our testing easier, and we think isclose is principally for testing. It would diverge our behavior from Python and NumPy, however. 

Since NumPy's isclose for complex is broken on non-finite values, and this error hasn't been noticed, that may suggest that NumPy isclose is little-used on complex arrays and its behavior may be able to change, too.

cc @ezyang @anjali411 @dylanbespalko
cc @rgommers

**Comment by mruberry** [comment]
I'd like to propose the following implementation, following cmath and NumPy:

To determine if a number `a` is "close" to a number `b` apply the first case which applies:

- If both numbers are finite (neither is -inf, inf, or NaN or, if complex, has -inf, inf, or NaN as its real or imaginary part), then `a` is "close" to `b` if `abs(a - b) <= (atol + rtol * abs(b))`
- If equal_nan=False and a number is NaN or, if complex, has NaN as its real or imaginary part, then it's not close to any number, including itself.
- If a number is -inf or inf or, if complex, has -inf or inf as its real or imaginary part, then it's only close to itself.
- If equal_nan=True and a number is NaN or, if complex, has NaN as its real or imaginary part, then it's only close to itself.

For testing, I propose we update our test functions (e.g. assertEqual) to perform a part-wise comparison for complex tensors. That is, our test functions do not compare whether two complex tensors are close or not, they instead compute `isclose(real) and isclose(imag)`. 

This seems like it respects other implementations of isclose and unifies the function for all scalar types. Just because our tests want a different behavior doesn't mean isclose has to provide it.

**Comment by anjali411** [comment]
Sounds good to me except that I think in the case where complex, has -inf or inf as its real or imaginary part, the finite value(real/element shouldn't necessarily have to be same for them to be close). for eg isclose should return true for (1, inf) and (1 + eps, inf) such that eps is within the specified bound

**Comment by mruberry** [comment]
> Sounds good to me except that I think in the case where complex, has -inf or inf as its real or imaginary part, the finite value(real/element shouldn't necessarily have to be same for them to be close). for eg isclose should return true for (1, inf) and (1 + eps, inf) such that eps is within the specified bound

@anjali411 and I had a chance to discuss this early and I agree it's a reasonable way to handle complex numbers with nonfinite parts. But until we have an example of where we need this kind of behavior, is it worth diverging from cmath/NumPy? It would also increase the code complexity and decrease the performance of isclose for complex tensors. If we later implemented quaternions, for example, it could become a very complex behavior to emulate.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/36456 implements isclose for complex tensors. It decided to wait on handling the equal_nan keyword pending NumPy's discussion.
