### ISSUE TITLE
GPU Memory Leak at Master Branch

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#3646]
When switching back to version: '0.2.0+53b0152' , there is no memory leak. 
Maybe because of `torch.cat` function, since it fails at that line.

**Comment by soumith** [comment]
@colesbury found some memory leaks that he's fixing. it's only on the master branch and not the release branch v0.3.0

**Comment by auzxb** [comment]
I meet the same bug. `torch.cat` function has GPU memory leak bug!!!

**Comment by fmassa** [comment]
@auzxb can you provide a minimum working example that illustrates the leak?

**Comment by ailzhang** [comment]
Closing since this issue is stale, please reopen with a repro script if you still see the memory leak.
