### ISSUE TITLE
How do pytorch calculate image gradient

### ISSUE THREAD

**Issue by TimingSpace** [pytorch/pytorch#36464]
### `I(u,v)` is the intensity of a pixel in location `(u,v)`, how do pytorch autograd function calculate it automatically?

If I calculate by myself, I will do it by `dI(u,v)/d(u)=dI(u+1,v)-dl(u,v)` or similar approach.

I want to know do you pytorch implements it in the package of autograd.

As when I learn optical flow or ego-motion, I use image loss `I_1(u,v)- I_2(u,v)`, the pytorch can calculate the gradient  `dI(u,v)/d(u,v)` by itself.

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions. Thank you
