### ISSUE TITLE
LBFGS Optimizer is non-deterministic?

### ISSUE THREAD

**Issue by samuelsunarjo96** [pytorch/pytorch#36472]
LBFGS Optimizer:
https://github.com/pytorch/pytorch/blob/6be85603757a810be3d18b70279b104c0653e9b3/torch/optim/lbfgs.py#L183

I was wondering if this optimizer is supposed to produce non-deterministic results? Given that these results were produced under the same parameter initialization and optimization setting. Simply running the program multiple times without any changes would produce different results.

I have set the following to attempt disabling the non-deterministic outcome but no luck:
`np.random.seed(0)`
`torch.manual_seed(0)`
`torch.backends.cudnn.deterministic = True`
`torch.backends.cudnn.benchmark = False`

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions. Thank you
