### ISSUE TITLE
torch.argmax() returns wrong indices for very big GPU tensors

### ISSUE THREAD

**Issue by kuynzereb** [pytorch/pytorch#36482]
## 🐛 Bug

`torch.argmax()` returns wrong indices for very big GPU tensors. It looks like it happens when the total size of the tensor is greater than 2^31 bytes. At the same indices from `torch.max()` are correct.
## To Reproduce

```python
import torch

device = 'cuda:0'
num_channel = 2 ** 6

for dtype in [torch.float64, torch.float32, torch.float16]:
    element_size = torch.tensor([], dtype=dtype).element_size()
    numel = 2 ** 31 // element_size

    t = torch.zeros([num_channel, numel // num_channel], dtype=dtype, device=device)
    t[num_channel // 2] = 1

    print(f"{dtype}, small tensor")
    print("Indices from torch.argmax():", torch.argmax(t, dim=0))
    print("Indices from torch.max():", torch.max(t, dim=0)[1])
    print()

    t = torch.zeros([num_channel, numel // num_channel + 1], dtype=dtype, device=device)
    t[num_channel // 2] = 1

    print(f"{dtype}, big tensor")
    print("Indices from torch.argmax():", torch.argmax(t, dim=0))
    print("Indices from torch.max():", torch.max(t, dim=0)[1])
    print()
```
When I run the above code I obtain the following output:
```
torch.float64, small tensor
Indices from torch.argmax(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')

torch.float64, big tensor
Indices from torch.argmax(): tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')

torch.float32, small tensor
Indices from torch.argmax(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')

torch.float32, big tensor
Indices from torch.argmax(): tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')

torch.float16, small tensor
Indices from torch.argmax(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')

torch.float16, big tensor
Indices from torch.argmax(): tensor([0, 0, 0,  ..., 0, 0, 0], device='cuda:0')
Indices from torch.max(): tensor([32, 32, 32,  ..., 32, 32, 32], device='cuda:0')
```
## Expected behavior

Correct argmax indices after `torch.argmax()`.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: TITAN RTX
Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.0                      166  
[conda] numpy                     1.18.1           py36h95a1406_0    conda-forge
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

cc @ezyang @gchanan @zou3519

**Comment by vadimkantorov** [comment]
Could you please try with a nightly build? A similar bug was fixed in https://github.com/pytorch/pytorch/issues/32863

**Comment by kuynzereb** [comment]
@vadimkantorov Indeed, it works correctly with a nightly build. I will close this issue then.
