### ISSUE TITLE
Support arbitrary file-like object in serialization functions

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#3648]
Useful when you e.g. want to receive/send objects via network. See #1567.

**Comment by sbhaaf** [comment]
Hey, first of all I appreciate all you guys are doing. I've got a workaround to this issue that I'm using right now (writing to disk), but I'm wondering if this is an issue that can be easily resolved in one of the upcoming releases. I've tested through '0.4.0'.

**Comment by soumith** [comment]
@zou3519 this is related to the other task that just got onto your plate.

@sbhaaf we could target to finish this in the 0.4.0 final release, @zou3519 can work on the over the next couple of weeks.

**Comment by sbhaaf** [comment]
Thank you guys!

**Comment by sbhaaf** [comment]
Awesome! Thank you guys
