### ISSUE TITLE
Meaning of _quantized namespace isn't documented

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#36510]
cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @iseeyuan 

They were added in https://github.com/pytorch/pytorch/pull/33294 and the PR says "The "_" prefix registration will be removed when the operators are all migrated to mobile." This should be reflected in the code somewhere.

**Comment by ezyang** [comment]
I guess I'll fix this when I reorg the operator registrations

**Comment by supriyar** [comment]
Hey @ezyang  assigning this to you based on your comment. We can take this up if you can't get to it. Thanks!
