### ISSUE TITLE
Fix far-fetched Boolean ambiguity for byte tensor with one value in it.

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#3652]
Testing non-empty tensor in an if statement will unconditionally raise a RuntimeError stating that "bool value of non-empty torch.ByteTensor objects is ambiguous". But when there's only one value, it's bool value is pretty straightforward.
What do you think?

**Comment by apaszke** [comment]
Yes, that makes sense. I thought we support this, but apparently we don't. NumPy does so it's better to do it as well for consistency

**Comment by VladislavZavadskyy** [comment]
Ok, will do a pull request in a few hours.
