### ISSUE TITLE
AvgPool3d gives argument error on padding

### ISSUE THREAD

**Issue by saru95** [pytorch/pytorch#3654]
Using a simple average 3d pool gives the following error:

```py
a = nn.AvgPool3d(3, padding=3)
print(a)
```

```
TypeError: __init__() got an unexpected keyword argument 'padding'
```

Although the docs do mention that padding is a valid argument (http://pytorch.org/docs/master/_modules/torch/nn/modules/pooling.html#AvgPool3d)

(http://pytorch.org/docs/master/nn.html#torch.nn.AvgPool3d)

I'm running version `0.2.0_3`

**Comment by apaszke** [comment]
You're looking at master branch docs (`/docs/master` in the URL). [Here's a doc for 0.2.0](http://pytorch.org/docs/0.2.0/nn.html#torch.nn.AvgPool3d) and it doesn't include padding. Next version should be released this week, so stay tuned!
