### ISSUE TITLE
pytorch-linux-xenial-py3-clang5-android-ndk-r19c docker build job is flaky

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#36541]
Reran 4 times on https://github.com/pytorch/pytorch/pull/36187/files and finally got android ndk downloaded successfully. 
Problematic line is `curl -Os --retry 3 https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip`. 
We might want to consider hosting the files ourselves if it happens again in the future. 

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by seemethere** [comment]
Also experiencing this as well, this is very annoying to deal with

**Comment by IvanKobzarev** [comment]
The problem is addressed in https://github.com/pytorch/pytorch/pull/42393, changes are merged into https://github.com/pytorch/pytorch/pull/40950

**Comment by seemethere** [comment]
Closing this, this is now resolved
