### ISSUE TITLE
Orthogonal Init Cost Large Memory

### ISSUE THREAD

**Issue by boscotsang** [pytorch/pytorch#36569]
## Issue description
Using orthogonal init cost large memory than other init method. As code example blow, I create a two layer fully connected neural network.  Using xavier_normal_ cost about 180M memory while using orthogonal_ cost mort than 360M memory.

## Code example

```
#!/usr/bin/env python
# encoding: utf-8

import os
import psutil
import sys
import torch
import torch.nn as nn

print(torch.__version__)


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.fc = nn.Sequential(
            nn.Linear(512, 256), nn.ReLU(inplace=True), nn.Linear(256, 64),
        )
        if sys.argv[1] == "orth":
            print("orth init")
            for m in self.fc.modules():
                if isinstance(m, nn.Linear):
                    nn.init.orthogonal_(m.weight)
        else:
            print("xavier init")
            for m in self.fc.modules():
                if isinstance(m, nn.Linear):
                    nn.init.xavier_normal_(m.weight)


if __name__ == "__main__":
    print(psutil.Process(os.getpid()).memory_info())
    model = Model()
    print(psutil.Process(os.getpid()).memory_info())

```

## System Info
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 8.3.0-16ubuntu3~16.04) 8.3.0
CMake version: version 3.16.0-rc4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40
GPU 4: Tesla P40
GPU 5: Tesla P40
GPU 6: Tesla P40
GPU 7: Tesla P40

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.5
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] msgpack-numpy             0.4.5                    pypi_0    pypi
[conda] numpy                     1.17.2           py37haad9e8e_0
[conda] numpy-base                1.17.2           py37hde5b4d6_0
[conda] numpydoc                  0.9.1                      py_0
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

**Comment by boscotsang** [comment]
It seems that the memory of variable q,r returned by torch.qr(tensor) was not released correctly.

**Comment by colesbury** [comment]
Yes, computing the QR decomposition takes more memory than generating random variables. That should be expected. There's no issue with tensor memory not being released correctly.

**Comment by boscotsang** [comment]
> Yes, computing the QR decomposition takes more memory than generating random variables. That should be expected. There's no issue with tensor memory not being released correctly.

Should the memory be released after the weight had been initialized since the intermediate variable q, r was no longer useful?

**Comment by colesbury** [comment]
It depends on what you mean by "released". The process's resident set size (rss) may not decrease because the memory may not be returned to the os, but still available for reuse within the process. Calling torch.qr the first time may also initialize a library, map in code pages, and initialize static data structures.

If the memory keeps increasing with subsequent `torch.qr` or `nn.init.orthogonal_` then I would be concerned, but that doesn't seem to be the case.
