### ISSUE TITLE
Type promotion for unary "universal functions (ufuncs)"

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#36571]
NumPy has the concept of a "[universal function](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc)", a class of element-wise functions. This post is concerned with PyTorch's implementation of type promotion for unary universal functions like `torch.sin` and `torch.abs`. It describes PyTorch's and NumPy's current unary ufunc type promotion behavior and makes three proposals for how PyTorch can change to be more compatible with NumPy. 

First, let's define the unary ufuncs in PyTorch (separated into two groups that will be explained shortly):

- **Type preserving unary ufuncs**: abs, conj, bitwise_not, clamp, mul, reciprocal, neg, round, square
- **Floating unary ufuncs**: angle, cos, cosh, acos, sin, sinh, asin, tan, tanh, atan, ceil, floor, digamma, lgamma, mvlgamma, polygamma, erf, erfc, erfinv, exp, expm1, frac, log, log10, log1p, log2, sqrt, rsqrt, sigmoid, sign, trunc

When describing "type promotion" for these functions we're looking at two things:

- the computation type
- the output type

And how these are affected by:

- the input type
- the dtype kwarg's (optional) value
- the out kwarg's (optional) tensor

## The default case (no kwargs)

With no kwargs, "type preserving unary ufuncs" like `np.abs` perform their computation in the input type and set their output type to the same. Most unary ufuncs, however, are "floating unary ufuncs." Let's look at NumPy's cosine as an example. With no kwargs, `np.cos` performs its computation in and outputs in the default scalar type when given integer inputs:

```
np.cos((1, 2, 3))
: array([ 0.54030231, -0.41614684, -0.9899925 ])

a = np.array((1, 2, 3), dtype=np.float16)
np.cos(a)
: array([ 0.5405, -0.4163, -0.99  ], dtype=float16)
```

This behavior is natural since the result of the cosine operation may not be expressible as an integer.

In PyTorch today, on the other hand, `torch.cos` simply fails on integer inputs:

```
t = torch.tensor((1, 2, 3))
torch.cos(t)
: RuntimeError: cos_vml_cpu not implemented for 'Long'
```

**Proposal 1**: PyTorch adopts the same floating unary ufunc (no kwargs) behavior as NumPy, mapping integer inputs to the default scalar type for their computation type. 

## Setting the dtype kwarg

The dtype kwarg determines the type of the computation. For example:

```
a = (1.1, 1.2, 1.3)
np.cos(a)
: array([0.45359612, 0.36235775, 0.26749883])

np.cos(a).astype(np.float16)
: array([0.4536, 0.3623, 0.2676], dtype=float16)

np.cos(a, dtype=np.float16)
:array([0.4539, 0.362 , 0.2676], dtype=float16)
```

Note the difference between computing in np.float16 and computing in np.double and then casting the result to np.float16. This behavior is easier to see with a binary ufunc like add:

```
np.add(1.7, .5, dtype=np.long, casting='unsafe')
: 1
```

Both inputs are cast to long before being added. (Note the casting rule is set to unsafe to permit this.) This can also occur with safe casting:

```
np.add(1/3, 3/7, dtype=np.half)
: 0.7617

np.add(1/3, 3/7, dtype=np.double)
: 0.7619
```

This is not to say that every function supports every computation type. For example:

```
np.sin(np.pi, dtype=np.long)
: TypeError: No loop matching the specified signature and casting was found for ufunc sin
```

Unfortunately many of PyTorch's unary ufuncs are missing the dtype keyword.

**Proposal 2**: PyTorch adds the dtype keyword to the unary ufuncs and adopts the same behavior as NumPy. 

## Setting the out kwarg

In NumPy, setting the out kwarg, as might be expected, determines a unary ufunc's out type. For example,

```
a = (1.1, 1.2, 1.3)
out = np.empty(3, dtype=np.float16)
np.cos(a, out=out)
: array([0.4536, 0.3623, 0.2676], dtype=float16)

np.cos(a, dtype=np.float16, out=out)
: array([0.4539, 0.362 , 0.2676], dtype=float16)
```

Note that setting the out kwarg did NOT change the computation type. PyTorch's behavior  is **divergent** in similar circumstances. For instance:

```
torch.set_printoptions(precision=20)

a = torch.tensor((19327107107.,))
b = torch.tensor((107076232663.,))
out = torch.empty(1, dtype=torch.float64)

torch.div(a, b)
: tensor([0.18049857020378112793])

torch.div(a, b, out=out)
: tensor([0.18049857434444288584], dtype=torch.float64)

torch.div(a, b, out=out) == torch.div(a, b)
: tensor([False])
```

Setting the out kwarg changed the dtype of the computation. Here's the same operations in NumPy:

```
a = np.array((19327107107.,), dtype=np.float32)
b = np.array((107076232663.,), dtype=np.float32)
out = np.empty(1, dtype=np.float64)

np.divide(a, b, out=out) == np.divide(a,b)
: True
```

**Proposal 3**: PyTorch adopts the same out kwarg type promotion behavior as NumPy. 

## Summary

This issue discussed unary ufunc type promotion in PyTorch and three places where we're incompatible with NumPy's behavior:

- PyTorch doesn't have a notion of "floating unary ufuncs" that perform their computation in floating point when given integer tensors.
- PyTorch's unary ufuncs are often missing the dtype kwarg.
- PyTorch's handling of the out kwarg can change the type of the computation performed, unlike NumPy's behavior where it simply specifies the output type.

I propose PyTorch adopt NumPy's type promotion behavior for its unary ufuncs. Natural follow-ups to this issue would be to review type promotion for the binary ufuncs (like add) and reductions (like mean, std, var, and sum). In particular, the binary ufuncs suffer from these same issues, although with the binary ufuncs we have the additional complication of multiple input tensors. Generalizing this proposal to binary ufuncs wouldn't change our existing logic for picking a computation type, but it would stop tensors specified in the out kwarg from participating in it. 

cc @nairbv, @gchanan, @ngimel, @rgommers

**Comment by nairbv** [comment]
A few comments/thoughts:

* I see a plan to support python3-like division where `int_tensor / int_tensor => floating_tensor`, so when we make changes to how we think about type preserving vs floating ufuncs, we should think about how that applies beyond just the unary ones.

* Proposal1: nit: technically there are (or will be) cases where a function can be either a "Type preserving unary ufunc" or "Floating unary ufuncs" depending on context, e.g. we will expect `torch.abs(complex_tensor)` to return a floating tensor, even though `abs(int)->int`. I'm not sure what the full specification of categories of ufuncs is.

* Proposal2: Would we want to wait to offer the dtype arg until/unless we also add more complete casting rules? Right now we don't support `casting='unsafe'`

* Proposal3: What do the use-cases here look like and what specifically makes numpy preferable? Will it make sense across all types of ops?

Some other examples for (3):
* 1f / 3f with out=double in numpy is: 0.3333333432674408 and in pytorch is: 0.3333333333333333. This is consistent with C++ (for `double third = f1 / f3`). 
* True + True with out=int or float in numpy is 1 and in pytorch is 2. This could be inconsistent with how we handle boolTensor.sum().
* Currently `torch.div(torch.tensor(5), torch.tensor(2))` returns 2 but `torch.div(torch.tensor(5), torch.tensor(2), out=floating_tensor)` returns 2.5. If we just ignore the out dtype we'll get the `2` which is inconsistent with numpy, unless we first change the behavior of integer division.

If we add the dtype argument from Proposal2 (and specify dtype=out.dtype) I assume the expectation is we'd get the original pytorch result in these examples?

**Comment by mruberry** [comment]
Hey @naibv! Thanks for taking a look. Let me respond to each part of your thoughtful comment:

> I see a plan to support python3-like division where int_tensor / int_tensor => floating_tensor, so when we make changes to how we think about type preserving vs floating ufuncs, we should think about how that applies beyond just the unary ones.

Yep! So there are a few floating binary ufuncs, like div, and in 1.7 we do want to change torch.div to torch.true_divide. 

> Proposal1: nit: technically there are (or will be) cases where a function can be either a "Type preserving unary ufunc" or "Floating unary ufuncs" depending on context, e.g. we will expect torch.abs(complex_tensor) to return a floating tensor, even though abs(int)->int. I'm not sure what the full specification of categories of ufuncs is.

You're right that torch.abs has additional type behavior that falls outside it just being a floating unary ufunc. For simplicity I'm trying to limit the description of floating unary ufuncs here to those unary ufuncs that perform their computations in the default scalar type when given integer inputs. They might have other behavior for other inputs, too. The categorization of angle as a "type preserving" unary ufunc is actually an even worse misnomer, since it won't preserve complex inputs, but these are semantic issues. You're also correct that this issue does not describe how every unary function handles types, and if it'd be helpful we can remove abs and angle from this discussion.

> Proposal2: Would we want to wait to offer the dtype arg until/unless we also add more complete casting rules? Right now we don't support casting='unsafe'

I think we want to add dtypes first, especially if we're changing how out works. Setting the casting kwarg seems like niche behavior, and not adding support for unsafe casts seems OK to start?

> Proposal3: What do the use-cases here look like and what specifically makes numpy preferable? Will it make sense across all types of ops?

This is a really great question. Maybe NumPy got it wrong? I think though, we should flip the question to ask why we think it's worthwhile diverging from NumPy? Let's talk about the cases you mention first.

> 1f / 3f with out=double in numpy is: 0.3333333432674408 and in pytorch is: 0.3333333333333333. This is consistent with C++ (for double third = f1 / f3).

That seems like a compiler bug. In Clang 7 the following program:

```
int main() {
  float f = 1./3;
  float one = 1.;
  float three = 3.;
  double d = one/three;
  double other_d = (float) 1. / (float) 3.;
  double all_double = 1./3.;
  std::cout << std::setprecision(20) << f << std::endl;
  std::cout << std::setprecision(20) << d << std::endl;
  std::cout << std::setprecision(20) << other_d << std::endl;
  std::cout << std::setprecision(20) << all_double << std::endl;

  return 0;
}
```

prints:

```
0.3333333432674407959
0.3333333432674407959
0.3333333432674407959
0.33333333333333331483
```

I believe the standard requires the computation occur in float in the first three cases.

> True + True with out=int or float in numpy is 1 and in pytorch is 2. This could be inconsistent with how we handle boolTensor.sum().

I don't think it is inconsistent. For example, in NumPy:

```
np.sum((True, True, False))
: 2
```

I think the sum reduction just uses a computation type of the default integer type when given a bool input? The choice of computation type is often pragmatic.

> Currently torch.div(torch.tensor(5), torch.tensor(2)) returns 2 but torch.div(torch.tensor(5), torch.tensor(2), out=floating_tensor) returns 2.5. If we just ignore the out dtype we'll get the 2 which is inconsistent with numpy, unless we first change the behavior of integer division.

You're right! But, as mentioned above, in 1.6 we'll likely stop letting you use torch.div to perform integer division and in 1.7 it will likely be equivalent to true_divide always. We're already divergent from NumPy on torch.div since it can sometimes perform integer division, so we're not increasing the divergence, and by the 1.6 release we should be erroring where we're divergent on torch.div.

> If we add the dtype argument from Proposal2 (and specify dtype=out.dtype) I assume the expectation is we'd get the original pytorch result in these examples?

We don't always compute in the out type! For example:

```
t = torch.tensor((.0000001,), dtype=torch.double).cuda()
t_half = t.to(torch.half)
out = torch.empty((1,), dtype=torch.half).cuda()

print(torch.add(t, t, out=out))
print(torch.add(t, t).to(torch.float16))
print(torch.add(t_half, t_half))
```

Will print:

```
tensor([1.7881e-07], device='cuda:0', dtype=torch.float16)
tensor([1.7881e-07], device='cuda:0', dtype=torch.float16)
tensor([2.3842e-07], device='cuda:0', dtype=torch.float16)
```

So we can see here that we computed in double since double is higher in our type hierarchy than half and then we cast the result to half. Setting dtype=torch.float16 would change the computation to occur in half. We can see this in the corresponding NumPy:

```
a = np.array((.0000001,), dtype=np.double)
a_half = a.astype(np.half)
out = np.empty((1,), dtype=np.half)

print(np.add(a, a, dtype=np.float16, out=out))
print(np.add(a, a).astype(np.float16))
print(np.add(a_half, a_half))
```

Which gives:

```
[2.384185791015625e-07]
[1.7881393432617188e-07]
[2.384185791015625e-07]
```


Getting back to Proposal #3, I think the behavior is consistent with C++ and NumPy, and those are tough conventions to deviate from -- I think we'd want a compelling reason to do so. I also think the behavior is intuitive and simple to describe, whereas today PyTorch sometimes computes in the out type and sometimes doesn't depending on where the out type's dtype is in the type hierarchy compared to the input dtypes. So we're actually already consistent with NumPy's out behavior when the input dtypes are "above" the output's dtype in our type hierarchy, but we're inconsistent when they're "below" it. I'm sure there are users who want that behavior, but I don't think we see evidence that this behavior is expected or so popular that it's worth deviating from convention.

**Comment by nairbv** [comment]
>> 1f / 3f with out=double in numpy is: 0.3333333432674408 and in pytorch is: 0.3333333333333333. >> This is consistent with C++ (for double third = f1 / f3).

> That seems like a compiler bug.

I meant that your proposal is consistent with C++, not our behavior. I also get the 0.3333333432674408 result on my compiler, and I agree that consistency is preferable.

> We don't always compute in the out type! For example:

I just meant that (I believe) in those three specific examples we'll have a way to get behavior identical to the original.

> The choice of computation type is often pragmatic.

yup, just something to watch out. There are probably tests, but I think the current impl might be relying on our particular current boolean arithmetic behavior.

> Setting the casting kwarg seems like niche behavior

It does seem low-priority. I guess I just want to make sure that if we're not adding it, we're highlighting examples of the proposal that don't require it (which I think we have now).

**Comment by mruberry** [comment]
Aha! My mistake. Yep, you are correct, correct, correct, and correct.

**Comment by mruberry** [comment]
Closing this issue because we now have floating unary elementwise ops and they handle the out= argument in a NumPy-compatible fashion.
