### ISSUE TITLE
how to remove ios dependency

### ISSUE THREAD

**Issue by avanilkumar** [pytorch/pytorch#36574]
I have written pytorch c++ app.
I clone pytorch code and build it as per guidelines in pytorch mobile
when i compile the app for x86_64 i am getting ios dependencies as below.
please help me avoid these ios errors. I want to run app in x86 linux pc.

-- The C compiler identification is GNU 6.5.0
-- The CXX compiler identification is GNU 6.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found torch: /home/anilkumar.av/pytorch-mobile/pytorch/build_android/install/lib/libtorch.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anilkumar.av/pytorch-mobile/helloworld/build
Scanning dependencies of target pythExec
[ 50%] Building CXX object CMakeFiles/pythExec.dir/pythExec.cpp.o
[100%] Linking CXX executable pythExec
/home/anilkumar.av/pytorch-mobile/pytorch/build_android/install/lib/libc10.a(TensorImpl.cpp.o): In function `std::__ndk1::basic_ios<char, std::__ndk1::char_traits<char> >::init(std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >*)':
/home/anilkumar.av/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/ios:711: undefined reference to `std::__ndk1::ios_base::init(void*)'
/home/anilkumar.av/pytorch-mobile/pytorch/build_android/install/lib/libc10.a(TensorImpl.cpp.o): In function `basic_streambuf':
/home/anilkumar.av/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/streambuf:232: undefined reference to `std::__ndk1::locale::locale()'

**Comment by colesbury** [comment]
That's not an iOS (the Apple operating system) dependency. That's the standard C++ header file https://en.cppreference.com/w/cpp/io/ios_base.

If you want to run on x86 linux pc why are you building for android?

It looks like you have errors in your build file that are not part of PyTorch. I don't think we're going to be able to help you with that. Check out https://stackoverflow.com/questions/10906275/undefined-reference-to-stdios-baseinitinit
