### ISSUE TITLE
No link to the previous version doc in master doc

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#3657]
http://pytorch.org/docs/master/
The link to switch doc is dead.

http://pytorch.org/docs/0.2.0/
Old versions are still available and the link is ok there.

**Comment by soumith** [comment]
thanks for the heads-up, not sure what happened there, will look.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/builder/commit/70fae11cb7baec08210135fd7c5b27fb3b156887
