### ISSUE TITLE
pytorch_bazel_test doesn't report test failures in console

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#36595]
Example: https://app.circleci.com/pipelines/github/pytorch/pytorch/154632/workflows/d292c250-eb0e-493d-b3f9-44f89adaacec/jobs/5134201

There are failures, but the failure logs are not reported anywhere.

cc @ezyang @seemethere @werkt @malfet

**Comment by malfet** [comment]
Fixed
