### ISSUE TITLE
Exception in find_cuda_windows_lib

### ISSUE THREAD

**Issue by liuxingbaoyu** [pytorch/pytorch#36592]
## To Reproduce

1.run nn.Module.cuda()

```
  File "C:\users\流星暴雨\appdata\local\programs\python\python37\lib\site-packages\torch\cuda\__init__.py", line 199, in _lazy_init        
    _cudart = _load_cudart()
  File "C:\users\流星暴雨\appdata\local\programs\python\python37\lib\site-packages\torch\cuda\__init__.py", line 80, in _load_cudart
    lib = find_cuda_windows_lib()
  File "C:\users\流星暴雨\appdata\local\programs\python\python37\lib\site-packages\torch\cuda\__init__.py", line 52, in find_cuda_windows_lib
    out = out.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 9: invalid start byte
```

## Expected behavior

success

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.4
 - OS (e.g., Linux):WIN10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.7.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peterjc123** [comment]
You'll have to modify the functions https://github.com/pytorch/pytorch/blob/v1.4.0/torch/cuda/__init__.py#L33-L61 and https://github.com/pytorch/pytorch/blob/v1.4.0/torch/backends/cudnn/__init__.py#L21-L46.

```py
def find_cuda_windows_lib():
    # Override the default search process
    # Fixes https://github.com/pytorch/pytorch/issues/20202
    # The libary selection will be done in these directories one by one
    # 1. [Package Root]\Lib
    #    That's where our libraries are in, which should be loaded first.
    # 2. [Python Root]\Library\bin
    #    That's where `cudatoolkit` store the cuda libraries.
    # 3. Default directories
    #    That is stored in the environment variable `PATH`.
    test_env = os.environ.copy()
    old_path = test_env['PATH']
    py_dll_path = os.path.join(sys.exec_prefix, 'Library', 'bin')
    th_dll_path = os.path.join(os.path.dirname(
        os.path.dirname(__file__)), 'lib')
    test_env['PATH'] = ';'.join([th_dll_path, py_dll_path, old_path])
    proc = Popen(['where', 'cudart64*.dll'], stdout=PIPE,
                 stderr=PIPE, stdin=PIPE, env=test_env)
    out, err = proc.communicate()
    import locale
    enc = locale.getpreferredencoding()
    out = out.decode(enc).strip()
    if len(out) > 0:
        if out.find('\r\n') != -1:
            out = out.split('\r\n')[0]
        cuda_lib_name = os.path.basename(out)
        cuda_lib = os.path.splitext(cuda_lib_name)[0]
        cuda_lib = str(cuda_lib)
        return ctypes.cdll.LoadLibrary(cuda_lib)
    else:
        return None
```

```py
def find_cudnn_windows_lib():
    # Override the default search process
    # Fixes https://github.com/pytorch/pytorch/issues/20202
    # The libary selection will be done in these directories one by one
    # 1. [Package Root]\Lib 
    #    That's where our libraries are in, which should be loaded first.
    # 2. Default directories
    #    That is stored in the environment variable `PATH`.
    test_env = os.environ.copy()
    old_path = test_env['PATH']
    th_dll_path = os.path.join(os.path.dirname(
        os.path.dirname(os.path.dirname(__file__))), 'lib')
    test_env['PATH'] = ';'.join([th_dll_path, old_path])
    proc = Popen(['where', 'cudnn64*.dll'], stdout=PIPE,
                 stderr=PIPE, stdin=PIPE, env=test_env)
    out, err = proc.communicate()
    import locale
    enc = locale.getpreferredencoding()
    out = out.decode(enc).strip()
    if len(out) > 0:
        if out.find('\r\n') != -1:
            out = out.split('\r\n')[0]
        cudnn_lib_name = os.path.basename(out)
        cudnn_lib = os.path.splitext(cudnn_lib_name)[0]
        cudnn_lib = str(cudnn_lib)
        return ctypes.cdll.LoadLibrary(cudnn_lib)
    else:
        return None
```

**Comment by liuxingbaoyu** [comment]
> You'll have to modify the functions https://github.com/pytorch/pytorch/blob/v1.4.0/torch/cuda/__init__.py#L33-L61 and https://github.com/pytorch/pytorch/blob/v1.4.0/torch/backends/cudnn/__init__.py#L21-L46.
> 
> ```python
> def find_cuda_windows_lib():
>     # Override the default search process
>     # Fixes https://github.com/pytorch/pytorch/issues/20202
>     # The libary selection will be done in these directories one by one
>     # 1. [Package Root]\Lib
>     #    That's where our libraries are in, which should be loaded first.
>     # 2. [Python Root]\Library\bin
>     #    That's where `cudatoolkit` store the cuda libraries.
>     # 3. Default directories
>     #    That is stored in the environment variable `PATH`.
>     test_env = os.environ.copy()
>     old_path = test_env['PATH']
>     py_dll_path = os.path.join(sys.exec_prefix, 'Library', 'bin')
>     th_dll_path = os.path.join(os.path.dirname(
>         os.path.dirname(__file__)), 'lib')
>     test_env['PATH'] = ';'.join([th_dll_path, py_dll_path, old_path])
>     proc = Popen(['where', 'cudart64*.dll'], stdout=PIPE,
>                  stderr=PIPE, stdin=PIPE, env=test_env)
>     out, err = proc.communicate()
>     import locale
>     enc = locale.getpreferredencoding()
>     out = out.decode(enc).strip()
>     if len(out) > 0:
>         if out.find('\r\n') != -1:
>             out = out.split('\r\n')[0]
>         cuda_lib_name = os.path.basename(out)
>         cuda_lib = os.path.splitext(cuda_lib_name)[0]
>         cuda_lib = str(cuda_lib)
>         return ctypes.cdll.LoadLibrary(cuda_lib)
>     else:
>         return None
> ```
> 
> ```python
> def find_cudnn_windows_lib():
>     # Override the default search process
>     # Fixes https://github.com/pytorch/pytorch/issues/20202
>     # The libary selection will be done in these directories one by one
>     # 1. [Package Root]\Lib 
>     #    That's where our libraries are in, which should be loaded first.
>     # 2. Default directories
>     #    That is stored in the environment variable `PATH`.
>     test_env = os.environ.copy()
>     old_path = test_env['PATH']
>     th_dll_path = os.path.join(os.path.dirname(
>         os.path.dirname(os.path.dirname(__file__))), 'lib')
>     test_env['PATH'] = ';'.join([th_dll_path, old_path])
>     proc = Popen(['where', 'cudnn64*.dll'], stdout=PIPE,
>                  stderr=PIPE, stdin=PIPE, env=test_env)
>     out, err = proc.communicate()
>     import locale
>     enc = locale.getpreferredencoding()
>     out = out.decode(enc).strip()
>     if len(out) > 0:
>         if out.find('\r\n') != -1:
>             out = out.split('\r\n')[0]
>         cudnn_lib_name = os.path.basename(out)
>         cudnn_lib = os.path.splitext(cudnn_lib_name)[0]
>         cudnn_lib = str(cudnn_lib)
>         return ctypes.cdll.LoadLibrary(cudnn_lib)
>     else:
>         return None
> ```

Thank you! Why is this not fixed in the master?

**Comment by peterjc123** [comment]
These functions are alreadly removed in master.
