### ISSUE TITLE
ProcessGroupAgent handling listenLoop Errors 

### ISSUE THREAD

**Issue by osalpekar** [pytorch/pytorch#36629]
Currently, if `ProcessGroupAgent` catches an exception in its `listenLoop`, it prevents any further sends/receives from the agent, but it also doesn't shutdown. This leaves the agent in somewhat of a "zombie" state - it can do nothing and must wait for its `shutdown` function to be called.

One possible exception PGA may encounter is the "connection closed by peer" error seen when another agent shuts down during communication. For elasticity to work in the future, we cannot have all agents in the gang enter a dysfunctional state if only one shutdown. Additionally, in order for `test_backward_node_failure_python_udf` to succeed, we must allow agents to continue receiving and processing messages (or shutdown) even if another agent shuts down. 

Thus we must do one of the following if PGA encounters an exception in `listenLoop`:
1. Shutdown the Agent. This should make `test_backward_node_failure_python_udf` pass, and is still logical right now given that we have no elasticity guarantees around the RPC framework currently. In essence, if one agent shuts down, they all shut down.
2. Continue allowing send/recv. This will make the test pass and enable elasticity going forward. If the Tensorpipe RPC Agent becomes the go-to RPC backend by the time elasticity in the RPC framework is shipped, a simple shutdown should suffice.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by rohan-varma** [comment]
Curious about how 1. Shutdown the Agent can be implemented

We can't take the solution of just calling `this->shutdown()` because then we'll have the issue of a thread trying to join itself indirectly. It seems like we can only do this from `send()`?

**Comment by osalpekar** [comment]
This specific test is fixed by #36969. Shutting down the agent from `send` would likely be the option for 1, but fixing 2 would be ideal. We'll ensure elasticity in Tensorpipe Agent once the first PR is merged.
