### ISSUE TITLE
I had build pytourch from source. But how to install after making a build?

### ISSUE THREAD

**Issue by tnavadiya** [pytorch/pytorch#36644]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Can anybody let me know how to install after build from source?

**Comment by ptrblck** [comment]
`python setup.py install` (or `python setup.py develop`) will automatically install `torch` in your current environment. 
You could check it via `conda list | grep torch` or `pip list | grep torch`.

**Comment by tnavadiya** [comment]
Ok thanks. It was installed. 

I am getting this error: AssertionError: Torch not compiled with CUDA enabled

But when I build it from source I enabled USE_CUDA=1 in setup.py. Is there anything else required to build with CUDA?

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org. Most likely it means that the build was not able to locate your cuda compiler.
