### ISSUE TITLE
CUDA quantization is not currently supported in pytorch1.4?

### ISSUE THREAD

**Issue by KnightYao** [pytorch/pytorch#36645]
CUDA quantization is not currently supported in pytorch1.4?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by ngimel** [comment]
Quantization on CUDA is not supported in 1.4

**Comment by KnightYao** [comment]
tks

**Comment by raghuramank100** [comment]
Yes, we do not support quantization on CUDA as part of pytorch. TensorRT provides a way to quantize models.
