### ISSUE TITLE
THCUNN/BCECriterion.cu:42: Assertion `input >= 0. && input <= 1.` failed.

### ISSUE THREAD

**Issue by cherepanovic** [pytorch/pytorch#36647]
## 🐛 Bug

I got the following exception caused by BCE objective even though the last operation on the output ist the sigmoid function. 

`/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [4,0,0], thread: [224,0,0] Assertion `input >= 0. && input <= 1.` failed.`

I tried to train an VAE only on one class of the dataset MNIST.
https://github.com/pytorch/examples/blob/master/vae/main.py

The single change in the code which I did was:

```
dataset =  datasets.MNIST(root='./mnist_data/')
train_dataset = torch.utils.data.TensorDataset(torch.tensor(dataset.data[dataset.test_labels == 5].unsqueeze(1)).float(), torch.tensor(dataset.targets[dataset.test_labels == 5]).float())
test_dataset = torch.utils.data.TensorDataset(torch.tensor(dataset.data[dataset.test_labels == 5].unsqueeze(1)).float(), torch.tensor(dataset.targets[dataset.test_labels == 5]).float())

train_loader = torch.utils.data.DataLoader(
    train_dataset,
    batch_size=args.batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    test_dataset,
    batch_size=args.batch_size, shuffle=True, **kwargs) 
```

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 19.04
GCC version: (Ubuntu 8.3.0-6ubuntu1) 8.3.0
CMake version: version 3.13.4

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 430.50
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.17.2           py37haad9e8e_0
[conda] numpy-base                1.17.2           py37hde5b4d6_0
[conda] numpydoc                  0.9.1                      py_0
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
```

**Comment by cherepanovic** [comment]
I discovered advice from @ptrblck 

`torch.autograd.set_detect_anomaly(True)`

then I git this error 

```
...
...
...
/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [11,0,0], thread: [159,0,0] Assertion `input >= 0. && input <= 1.` failed.
Traceback (most recent call last):
  File "simple_vae.py", line 136, in <module>
    train(epoch)
  File "simple_vae.py", line 108, in train
    loss = loss_function(recon_batch, data, mu, log_var)
  File "simple_vae.py", line 87, in loss_function
    BCE = F.binary_cross_entropy(recon_x, x.view(-1, 784), reduction='sum')
  File "/root/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2077, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: cudaErrorAssert: device-side assert triggered
```

**Comment by cherepanovic** [comment]
(btw) I tried the same execution with smaller learning rates 1e-4/1e-5/1e-6 over 150 iterations and didn't get any errors.

Still waiting for help regarding this issue.

**Comment by ptrblck** [comment]
As you are not normalizing the data, you are passing the target with values in `[0, 255]` to `F.binary_cross_entropy`, while the model output is using a `sigmoid` and thus can take values in `[0, 1]`, which will create an offset in the loss.

Also, passing unnormalized data to your model returns output tensors with a large range, which will blow up the (KLD) loss, and thus creates NaN outputs after ~2 iterations on my system.
I assume the assertion error might be raised to a NaN input.

Normalizing the data seems to yield similar results compared to the original script.

[Forum post](https://discuss.pytorch.org/t/kld-loss-goes-nan-during-vae-training/42305/3) for reference.

**Comment by cherepanovic** [comment]
I don't see any point where the data in original code (https://github.com/pytorch/examples/blob/master/vae/main.py) will be normalized, why does it work there without any problems?

**Comment by ptrblck** [comment]
The [`__getitem__`](https://github.com/pytorch/vision/blob/1b9f25111415dee8772e7b2e9c1962b7fa7349b1/torchvision/datasets/mnist.py#L94-L97) of `datasets.MNIST` will create a `PIL.Image` for each sample and apply the passed transformation on it. 
The original implementation uses [`ToTensor()`](https://github.com/pytorch/examples/blob/391be73bbd191a08776c9ba05d29ef1e05c0c83b/vae/main.py#L32) as the transformation, which will normalize the tensor to the range `[0, 1]`.

**Comment by cherepanovic** [comment]
why this 

`dataset =  datasets.MNIST(root='./mnist_data/', transform=transforms.ToTensor())`

does not transform the data in my case?

**Comment by ptrblck** [comment]
Because you are creating a new `TensorDataset` by grabbing the underlying `.data` attributes.

**Comment by cherepanovic** [comment]
thank a lot! 

is there any fast method provided by pytorch for that case?

**Comment by ptrblck** [comment]
You could scale the inputs via:
```python
data = data / 255.
```
in your training loop.
However, the better approach would be to create a `CustomMNIST` dataset by deriving from `datasets.MNIST` and add your label manipulation in its `__init__` method.
This would also allow you to use image transformations other than the scaling such as `RandomCrop` etc.

**Comment by flandrewries** [comment]
i have met this question too, but when i debug this problem.
i discovered that this may happens when your network initiated with a bad startup.
usually the output is too big , eg , sigmoid(20.) == 1
so, this will occurs when you want to do (sth + sigmoid(20.)) with BCE ,this output will over then one.

solution:
torch.nn.init.xavier_normal_(weight)
torch.nn.init.constant_(bias, 0)
may help to you
