### ISSUE TITLE
Add torch.sgn to return complex sign

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#36655]
Following discussion in https://github.com/pytorch/pytorch/issues/36323
Add `torch.sgn` to return `z/abs(z)`
cc @ezyang @anjali411 @dylanbespalko

**Comment by kshitij12345** [comment]
@choidongyeon Are you working on it? Otherwise I would like to take this up.

**Comment by choidongyeon** [comment]
@kshitij12345 Hi, yes I am working on it.

**Comment by mruberry** [comment]
Would you update this issue with your plan/approach? How would the function work? How would it handle extremal values?

**Comment by choidongyeon** [comment]
I spent some time working on this but it seems beyond my current understanding of PyTorch. @kshitij12345 , would you like to take this issue?

**Comment by kshitij12345** [comment]
@choidongyeon 
Sure I would like to give it a shot.

@mruberry @anjali411 
I am planning to use the existing `abs` and `div` operation to implement the op.
Also, I am planning to return `0` when `abs(z) == 0`  
and otherwise `z/abs(z)` (even for extreme values. I'll also check if `z/abs(z)` agrees with numpy on extreme values).
Let me know if you have any suggestions on the same.

**Comment by anjali411** [comment]
> @choidongyeon
> Sure I would like to give it a shot.
> 
> @mruberry @anjali411
> I am planning to use the existing `abs` and `div` operation to implement the op.
> Also, I am planning to return `0` when `abs(z) == 0`
> and otherwise `z/abs(z)` (even for extreme values. I'll also check if `z/abs(z)` agrees with numpy on extreme values).
> Let me know if you have any suggestions on the same.

Implementation wise I think we should return tensor corresponding to (r, θ) = (1, z.angle()) which makes me think if we should add API to get complex tensors when input (r, θ) until we don't have polar coordinates. 

cc. @dylanbespalko @zasdfgbnm

**Comment by anjali411** [comment]
added in #39955
