### ISSUE TITLE
parameter requires_grad of new_zeros doesn't work

### ISSUE THREAD

**Issue by duzx16** [pytorch/pytorch#36702]
## 🐛 Bug

The parameter `requires_grad` of `new_zeros` method of tensors can't set the `requires_grad` attribute of the created tensor correctly. 

## To Reproduce

```
import torch
a = torch.tensor((1.0,))
print(a.new_ones((1,), requires_grad=True).requires_grad)
print(a.new_zeros((1,), requires_grad=True).requires_grad)
```

## Expected behavior

The output of both print statements should be `True`. However, while the first is `True`, the second is `False`.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04.2 LTS
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1/7.6.1
 - GPU models and configuration: GeForce RTX 2080 Ti

## Additional context

The `requires_grad` parameter of `new_empty` and `new_full` methods also doesn't work. 

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
Likely related to #36455

**Comment by mruberry** [comment]
Thanks for reporting this issue, @duzx16!

**Comment by ezyang** [comment]
It's the same thing as #36455

**Comment by mruberry** [comment]
Closing as duplicate.
