### ISSUE TITLE
Need to fix nn.quantized.Linear API

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#36703]
Right now it is possible to initialize a `nn.quantized.Lienar` module with `dtype=torch.float16`: https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/linear.py#L116, but that is invalid, we should fix this API to disallow this.

`nn.quantized.Linear` should be renamed to a `nn.quantized._Linear` module and both `nn.quantized.Linear` and `nn.quantized.dynamic.Linear` should inherit from this module and `nn.quantized.Linear` should only allow dtype = quint8

cc @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @jerryzh168 @dzhulgakov

**Comment by vkuzo** [comment]
@jerryzh168 , is this still relevant after the reference model design changes?

**Comment by jerryzh168** [comment]
I think so, this is talking about eager mode quantized linear module support

**Comment by andrewor14** [comment]
Looks like the check exists already so I'm closing this.
https://github.com/pytorch/pytorch/blob/4d8c73b2b7f15b5ef4581772f1dcc9416827b946/torch/ao/nn/quantized/modules/linear.py#L143-L149
