### ISSUE TITLE
[TensorPipe] Set handshake IP address properly

### ISSUE THREAD

**Issue by jiayisuse** [pytorch/pytorch#36715]
In tensorpipe rpc agent, we currently hardcoded localhost as pipes handshake IP address. Ideally tensorpipe could provide a helper to get IP address for given device interface or host names, or return the IP address of the default host name. More specifically like Gloo https://github.com/facebookincubator/gloo/blob/master/gloo/transport/tcp/device.cc#L142. As this is not supported in tensorpipe right now, we could have a couple of work around:

* Retrieve the default IP address on rpc agent layer
* Let user specify IP address by rpcBackendOption
* Hard code 127.0.0.1 for now for single machine only

cc @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma

**Comment by mruberry** [comment]
Hey @jiayisuse, should we maybe make a separate triage queue for RPC and Tensorpipe issues?

**Comment by osalpekar** [comment]
@jiayisuse this issue is closed by #37910 right?

**Comment by lw** [comment]
Yes, done as part of #37910 and #39184.
