### ISSUE TITLE
A word's embedding from nn.TransformerEncoder is same in different sentences

### ISSUE THREAD

**Issue by DogeWatch** [pytorch/pytorch#36723]
case like this:
![image](https://user-images.githubusercontent.com/13670813/79475812-c46a9800-803a-11ea-9abb-fcbdd3f0b951.png)
is my usage wrong? pytorch version is 1.4.0

**Comment by mruberry** [comment]
Hey @DogeWatch! Cool question, but it's more appropriate to our forums at https://discuss.pytorch.org/. Try asking there ;)
