### ISSUE TITLE
torch.triangular_solver doesn't work on batched inputs

### ISSUE THREAD

**Issue by rmhofer** [pytorch/pytorch#36734]
## 🐛 Bug

The output of torch.triangular_solver is different for two batch elements that are identical but works fine on unbatched inputs.

## To Reproduce

Download and unzip to get inputs A and input_ (below):
[A and input.zip](https://github.com/pytorch/pytorch/files/4489133/A.%2B.input.zip)

```
import torch

A = torch.load('A.ct')
input_ = torch.load('input.ct')

print(f"A.shape: {A.shape}")
print(f"input.shape: {input_.shape}")

assert (A[0] == A[1]).all()
assert (input_[0] == input_[1]).all()

solution = torch.triangular_solve(input_, A, upper=False)[0]

print(f"(solution[0] == solution[1]).all() {(solution[0] == solution[1]).all()}")

solution_0 = torch.triangular_solve(input_[0], A[0], upper=False)[0]
solution_1 = torch.triangular_solve(input_[1], A[1], upper=False)[0]

print(f"(solution_0 == solution_1).all() {(solution_0 == solution_1).all()}")
```

Output:
```
A.shape: torch.Size([2, 274, 274])
input.shape: torch.Size([2, 274, 1])
(solution[0] == solution[1]).all() False
(solution_0 == solution_1).all() True
```

## Expected behavior

solution[0] should be identical to solution[1].

Expected output:
```
A.shape: torch.Size([2, 274, 274])
input.shape: torch.Size([2, 274, 1])
(solution[0] == solution[1]).all() True
(solution_0 == solution_1).all() True
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.1
 - CUDA/cuDNN version: not running on cuda
 - GPU models and configuration:
 - Any other relevant information:

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
Thanks for the bug report, @rmhofer. This is likely an issue with LAPACK, which PyTorch uses for triangular_solve, however maybe we're calling it improperly or can work around this issue in PyTorch. It'd be great to get a PR if that's the case!

**Comment by ashish-hacker** [comment]
Is someone working on it? @mruberry 
I want to resolve this issue. If someone is working I can assist them too.

**Comment by ashish-hacker** [comment]
The problem seems to be resolved. 
I tested it with the data @rmhofer had provided and it gives the expected output.
Is there anything else I can work on in this issue?

**Comment by mruberry** [comment]
Thanks for the update @ashish-hacker. @rmhofer, do you also see this issue fixed on the latest PyTorch release?

**Comment by rmhofer** [comment]
Yes, the issue seems to be fixed now. Thank you!

**Comment by mruberry** [comment]
Happy resolution.
