### ISSUE TITLE
Explicitly Define Gradient for Certain Computation

### ISSUE THREAD

**Issue by occam-ra-zor** [pytorch/pytorch#36735]
## 🚀 Feature
Say there is function F . which cannot be computed exactly but it’s gradient can be perfectly defined can I define function s.t I tell the autograd , how gradient should be computed instead of autograd figuring about by computation graph. So my requirement is as following,

```
function F(x) :
      #cannot be computed exactly 
      approx = some_decent_approx_of_F(x)
      return approx
```

```
function Grad_of_F(x):
      #can be computed exactly
     grad  = exact_grad_of_F(x)
     return grad
```

so instead of gradient computed based on computational graph of F. I want to explicitly say use Grad_of_F for computation of gradient in backward pass 
## Motivation

consider use case where F is CDF of standard normal. CDF cannot be computed perfectly but its's derivative PDF can be computed exactly which is what one need for learning.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by kshitij12345** [comment]
@occam-ra-zor 
I guess this tutorial might be useful. You can implement your Function/Operator the way `MyRelu` is defined.
https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

**Comment by mruberry** [comment]
Hey @occam-ra-zor, you can implement a custom function with its own backward pass, where the forward implements your approximation and the backward is any arbitrary function. 

This might help you out: https://pytorch.org/tutorials/advanced/cpp_extension.html.

**Comment by albanD** [comment]
You can also find here: https://pytorch.org/docs/stable/notes/extending.html the notes on how to create functions with custom backward in the autograd engine.
