### ISSUE TITLE
Incorrect error message when detach_

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#3674]
Calling `detach_` on `some_view_variable.contiguous()` variable gives weird error message. cc @colesbury 

```
>>> x = Variable(torch.randn(3,1,2)).transpose(1, 0)
>>> x.detach_()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Can't detach views in-place. Use detach() instead
>>> x.contiguous().detach_()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Can't detach views in-place. Use detach() instead
```

**Comment by apaszke** [comment]
How is that unclear? `x` is not a leaf (it's a result of `Transpose` on a leaf)

**Comment by colesbury** [comment]
So the second line `x.contiguous().detach_()` should work. The problem is that `contiguous()` modifies the `data` attribute on Variable, so it's still treated as a view when it isn't really

**Comment by SsnL** [comment]
Sorry for the confusion. @colesbury is right, my description was wrong. It is updated now.

**Comment by colesbury** [comment]
Actually, this is expected. `x` is already contiguous, even after the transpose. So `x.contiguous()` just returns x.
