### ISSUE TITLE
Documentation of LU Decomposition

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#36752]
## 📚 Documentation

The LU decomposition returns a tuple containing the 'factorization' and the pivoting order. It would be great to have a mathematical expression how the input relates to these two outputs, especially since the naive assumption (that L is the lower part of the 'factorization' and U is the upper part of the 'factorization') is not true.

```py
X = torch.rand(3, 3)
LU, piv = torch.lu(X.cuda(), pivot=False) # simple case without pivoting
LU.tril().mm(LU.triu()) # not the same as X
```

**Comment by vadimkantorov** [comment]
maybe related: https://discuss.pytorch.org/t/torch-lu-pivots-are-not-permutations-sometimes/53825

**Comment by mruberry** [comment]
Thanks for pointing this out, twoertwein! A PR fixing this would be great!

**Comment by twoertwein** [comment]
I would be happy to fix it, if I knew what the output is (I know what it is not).
