### ISSUE TITLE
torch.load() requires model module in the same folder

### ISSUE THREAD

**Issue by clairett** [pytorch/pytorch#3678]
I define a function using `torch.load()` in folder A and call that function in folder B, and get an error indicating `No module named 'model'`. BTW, I put the model.py in folder A. It seems like Pytorch requires "model.py" in the folder you use that function related to `torch.load()`. I check the `map_location`, which only allows you to change the device for loading. Could you please how to specify the loading path?

**Comment by apaszke** [comment]
PyTorch internally uses `pickle` and it's a limitation of pickle. You can try meddling with `sys.path` to include the directory where `module.py` is. This is exactly why we recommend saving only the state dicts and not whole model objects.

**Comment by kmario23** [comment]
To fix this issue, add the below two lines at the top of the Python module from where you're loading the pre-trained model (for instance in `train.py`):

```
import sys
sys.path.insert(0, './WordLM')
```
where `./WordLM` is a subdirectory inside your main project directory, which has the pre-trained model. The directory tree would then look something like:

```
├── process_input_files.py
├── datasets.py
├── eval.py
├── WordLM
│     ├── model_arch.py
│     ├── checkpoint
│           ├── pretrained_model.pt
├── models.py
├── README.md
├── train.py
└── utils.py
```

**Comment by tothedistance** [comment]
Say I need to load yolov5 module. And I'd like to manage yolov5 version in another repo as many model use different version. And I kind of not want to hard code the path to yolov5. Is there a way like `import yolov5.model as model` to solve this issue?

**Comment by sudomaze** [comment]
I have managed to over-write the modules by adding `import pdb; pdb.set_trace()` into `UnpicklerWrapper` and then updating the string of `mod_name` with the proper one that should be loaded. Then I saved the new loaded model. This works :)

**Comment by nik-vostrosablin-sp** [comment]
> I have managed to over-write the modules by adding `import pdb; pdb.set_trace()` into `UnpicklerWrapper` and then updating the string of `mod_name` manually with the proper module path (e.g. rather than `submodule.model`, it would be `package.module.submodule.model`) that should be loaded. Then I saved the new loaded model. This works :)
> 
> More context of my situation: My issue was the original model was using relative import (e.g. `submodule.model`) rather than the absolute import (e.g. `package.module.submodule.model`), so when I moved the weight file around, it caused this failure. This fix managed to have the model to be loaded correctly.

this helped a lot, thanks for the hit :)
