### ISSUE TITLE
Implementation of xLARFG / calling of LAPACK functions

### ISSUE THREAD

**Issue by coquelin77** [pytorch/pytorch#36794]
## 🚀 Feature

I would like to be able to use a xLARFG function, or alternatively it would be great to be able to have a small extension for calling an arbitrary LAPACK function.

## Motivation

I want to generate transformation vectors using xLARFG and I do not want to do it in pure python. Even with JITing i believe that this will be significantly slower than the LAPACKs implementation. It would be great if xLARFG could be implemented. 

Also I think that it would be really beneficial to have some way to access specific LAPACK functions which are not yet implemented.

## Pitch

The implementation of the mirrored function for xLARFG. Or a way to implement/call native LAPACK functions without a new release on your end. 

## Alternatives

Implement the function in python and JIT. Although this would increase the efficiency of the function itself it will likely not reach the same level as a native implementation

**Comment by mruberry** [comment]
Thanks for the feature suggestion, @coquelin. A PR implementing this would be interesting.

**Comment by narang99** [comment]
I'm interested in doing this. 
Do we intend to extend an interface like [scipy.linalg.lapack](https://docs.scipy.org/doc/scipy/reference/linalg.lapack.html) for torch? I didn't understand what it means to provide LAPACK functionality without a new release

**Comment by mruberry** [comment]
Yes, I think we would accept contributions to a new torch.linalg.lapack (exact name TBD) namespace that provided more direct access to LAPACK routines.

cc @Lezcano

**Comment by narang99** [comment]
Ohk I found some lapack routines in the codebase. Now do I just need to create a new namespace, add the required functions and create entries in `native_functions.yml` to dispatch the routines to correct device specific routines?
I'm new to the code so I hope you could give me some guidance. Thanks:)

**Comment by Lezcano** [comment]
Have you tried [`torch.linalg.householder_product`](https://pytorch.org/docs/master/generated/torch.linalg.householder_product.html)? Is this good enough for your application?

A priori, I do not know of an application for which `linalg.householder_product` should not be good enough without having to go as low-level as `xLARFG`. In what context would this function be useful? @coquelin77

**Comment by coquelin77** [comment]
my apologies, its been some time since i was working on this problem. This was in the context of needing the householder matrix for an implementation of a step during a distributed SVD function for a package which I am a contributor to. So @Lezcano your original suggestion was spot on, thanks!

there are some slight differences in `larfg` and `qeqrf` which are actually best shown in the LAPACK docs ([dlarft](https://www.netlib.org/lapack/explore-html/d8/d9b/group__double_o_t_h_e_rauxiliary_gaabb59655e820b3551af27781bd716143.html) and [dqeqrf](https://www.netlib.org/lapack/explore-html/df/dc5/group__variants_g_ecomputational_ga3766ea903391b5cf9008132f7440ec7b.html)). 

while my initial issue was solved in v1.9.0 with the addition of `torch.linalg.householder_product`, there seems to be interest in the LAPACK side of this issue. From my end, this can be closed, but I leave it do the dev team to decide how to proceed.

**Comment by Lezcano** [comment]
I'll close this for now, but do stay tuned, as we plan to keep improving `torch.linalg`. In particular, one of the things at the top of the list is to add more low-level bindings into LAPACK / MAGMA / cuBLAS on PyTorch core in 1.10 to make these performand libraries possible to build on top of PyTorch core :)
