### ISSUE TITLE
`Tensor.exponential_(0)` incorrectly gives a Tensor full of 0's

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#36798]
## 🐛 Bug

It should give a Tensor full of Inf.

## To Reproduce

In 1.4.0:
```
>>> torch.randn(3).exponential_(0)
tensor([inf, inf, inf])
```

In 1.5.0 and master, on both CPU and CUDA
```
>>> torch.randn(3).exponential_(0)
tensor([0., 0., 0.])
```

## Expected behavior

This should return a tensor full of Inf https://pytorch.org/docs/stable/tensors.html#torch.Tensor.exponential_ the documentation says the argument `lambd` is the rate parameter.

Looking at the [wikipedia definition](https://en.wikipedia.org/wiki/Exponential_distribution) for the rate parameter, we expect the distribution to have mean `1/lambd`. As `lambd` approaches 0 from the positive side, the distribution should produce larger and larger values. So returning `0.` for `lambd = 0` seems incorrect.

**Comment by gchanan** [comment]
Just repeating my comment from https://github.com/pytorch/pytorch/pull/32501:

I think both scale and the result should be `inf`, i.e.:

```
>>> np.random.exponential(np.array(1.)/np.array(0.))
//anaconda2/envs/pytorch1.4/bin/ipython:1: RuntimeWarning: divide by zero encountered in true_divide
  #!//anaconda2/envs/pytorch1.4/bin/python
inf
```
