### ISSUE TITLE
unittest should print test immediately when it starts running

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#36801]
When tests timeout we usually only say the immediately preceeding test in the output. It would be better if we could see the actual test that was running at the time of timeout.

Ex. https://github.com/pytorch/pytorch/issues/36434#issuecomment-614171554

**Comment by AnkilP** [comment]
Can I claim this?

**Comment by ezyang** [comment]
@AnkilP Sure! But we're likely to have opinions on exactly how one goes about doing this, so try to propose a solution first before trying to polish it (e.g., get all of CI working) first.

**Comment by AnkilP** [comment]
Absolutely, thanks!

**Comment by nolifenameless** [comment]
how about print out "setting up {}".format(self._testMethodName) in setup() stage? @ezyang

**Comment by ezyang** [comment]
@nolifenameless that won't work for the default Python test view, which prints only a single `.` per test. It would probably look somewhat ugly in verbose mode, though this would be easy enough to test and see.
