### ISSUE TITLE
Nondeterministic output from Optimizer.state_dict()

### ISSUE THREAD

**Issue by aphedges** [pytorch/pytorch#36831]
## 🐛 Bug

[`Optimizer.state_dict()`](https://pytorch.org/docs/stable/optim.html#torch.optim.Optimizer.state_dict) uses the built-in [`id()`](https://docs.python.org/3.7/library/functions.html#id) function, which has nondeterministic output between runs. This prevents easy testing for consistent training, even though the actual values are identical.

## To Reproduce

1. Run `python optimizer_test.py` twice.
1. Note that the output differs even though the input is the same.

Minimal code example as `optimizer_test.py`:
```python
import torch

torch.manual_seed(0)
linear_parameters = list(torch.nn.Linear(1, 1).parameters())
print(linear_parameters)
optimizer = torch.optim.Adam(linear_parameters)
print(optimizer.state_dict())
```

Program output:
```text
$ python optimizer_test.py
[Parameter containing:
tensor([[-0.0075]], requires_grad=True), Parameter containing:
tensor([0.5364], requires_grad=True)]
{'state': {}, 'param_groups': [{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [4551637984, 5094761248]}]}

$ python optimizer_test.py
[Parameter containing:
tensor([[-0.0075]], requires_grad=True), Parameter containing:
tensor([0.5364], requires_grad=True)]
{'state': {}, 'param_groups': [{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [4694905872, 4694905952]}]}
```

## Expected behavior

The output should be the same between runs.

## Environment

Output from the [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py):
```text
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.3
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] numpydoc==0.9.1
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.3.1
[conda] Could not collect
```

## Additional context

The apparent fix to this seems to be assigning integers in iteration order instead of using the value from `id()`. The values here appear to be entirely arbitrary as long as they are internally consistent.

Inspection of [`torch/optim/optimizer.py`](https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py) on `master` reveals this issue still exists for the latest version.

I'm unsure of exactly how to fully test it, but I believe I would be able to fix it. I can put out a PR if this is deemed worth fixing.

cc @vincentqb

**Comment by mruberry** [comment]
Thanks for the bug report, @aphedges!

**Comment by vincentqb** [comment]
Can you elaborate on how this makes testing harder?

**Comment by aphedges** [comment]
I have everything set up to train deterministically, so ensuring no change in the output of `state_dict()` for the model and optimizer parameters should be enough to detect unintentional changes. There are no issues comparing the model parameters between runs, but comparing the optimizer parameters between runs requires manually transforming the IDs into consistent indices. Once done, the outputs are identical.

This might not be the test way to handle it, but the following code is what I use:
```python
# Optimizer.state_dict() relies on id(),
# so modification is required to remove the nondeterminism
param_mappings = {}
index = 0
for param_group in data['optimizer']['param_groups']:
    new_params = []
    for param in param_group['params']:
        param_mappings[param] = index
        new_params.append(index)
        index += 1
    param_group['params'] = new_params

new_state = {}
for k, v in data['optimizer']['state'].items():
    if k in param_mappings:
        new_k = param_mappings[k]
    else:
        new_k = k
    new_state[new_k] = v
data['optimizer']['state'] = new_state
```

This works because the order is consistent between runs, even if the ID is not. Something like this could probably be done in `Optimizer.state_dict()` to remove references to the ID with another, more consistent value. The specific values don't appear to be used in  `Optimizer.load_state_dict()` or in the model analogs, so arbitrary values are probably safe.

**Comment by vincentqb** [comment]
If there is a way of changing the numbering without breaking backward compatibility, I would welcome a pull request for this. Do you want to open one?

**Comment by aphedges** [comment]
Sure. It will be a couple of days before I get to it, but I should be able to handle this.
