### ISSUE TITLE
Can't initialize nn.Embedding with specific values

### ISSUE THREAD

**Issue by joshim5** [pytorch/pytorch#3685]
Currently, in pyTorch, one would have to initialize an Embedding and then set the weight parameters manually. This requires memory to be written twice, which can be a significant slow-down for large matrices.

Here is an example:
```
self.lambda = nn.Embedding(num_elms, K)
self.lambda.weight.data = torch.ones(num_elms, K) * -10
```

pyTorch should allow for a default weight matrix to be set.

**Comment by joshim5** [comment]
@jackdent

**Comment by jihunchoi** [comment]
I think the following would be much more efficient, though I haven't actually run them.
```
from torch.nn import init

self.lambda = nn.Embedding(num_elms, K)
init.constant(self.lambda.weight.data, val=-10)
```
Or,
```
self.lambda = nn.Embedding(num_elms, K)
self.lambda.weight.data.fill_(-10)
```

**Comment by ezyang** [comment]
Yes, just fill. But a related issue is #18182.
