### ISSUE TITLE
torch.assert operator / async assertion for cuda tensors

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#36853]
## 🚀 Feature

Launch a non-blocking "assert" op for cpu/cuda tensors.

## Motivation
It's common to use assertion to check pre-conditions or unexpected inputs in code, as a form of defensive programming. For example, sometimes we want to assert that all elements of a tensor is all positive, or finite.

However, doing assert in python has the following problems in pytorch:
* when dealing with cuda tensors, using python's `assert (t>0).all()` or `assert torch.isfinite(t).all()` will wait for results of the cuda kernel and most if not all its preceding kernel launches, thus potentially cause significantly slow down.
It would be good to have a way to execute an assert as an async call.
* it does not work nicely with tracing or FX, because it is considered as control logic

## Pitch
```
x = some_tensor()
(x>0).all().assert("I got a bad data x")
y = torch.log(x)
torch.Assert(y.all(), "message")
```
(assert is a reserved keyword. Tensorflow uses tf.Assert. we can also use `torch.assert_` since the op can be used with in-place style: `y.all().assert_()`)

cc @ngimel

**Comment by mruberry** [comment]
Thanks for the suggestion, @ppwwyyxx. Implementing a general notion of non-blocking assertions seems tricky and niche, but if you want you can implement your own by waiting for the CUDA kernel to complete and then querying its result.

**Comment by ppwwyyxx** [comment]
I'm pitching this again as having an assertion op would help tracing and FX as well (and we're encountering such problems recently).

Making it not a pain for users to write assertions encourages users to write better & safer pytorch code.
(TensorFlow has assertion ops for ages, if that matters).

**Comment by NicolasHug** [comment]
Hi all, I'm wondering whether we should re-open this issue? I looks like pytorch#53086 got merged and reverted?

**Comment by ngimel** [comment]
It was later relanded https://github.com/pytorch/pytorch/commit/cfd9360d090842fa3fc72987c8e70c8091ad4b03

**Comment by thomassajot** [comment]
@ngimel, is this async assert available as python bindings by any chance?

**Comment by ngimel** [comment]
Yes it is, `torch.assert_async`

**Comment by randolf-scholz** [comment]
@ngimel  There only seems to be a private binding `torch._assert_async`, but no public binding `torch.assert_async`.

```python
>>> import torch
>>> print(torch.__version__)
2.12.0+cu130
>>> torch.assert_async
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    torch.assert_async
  File "/home/rscholz/.venv/lib/python3.14/site-packages/torch/__init__.py", line 2922, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'assert_async'
>>> torch._assert_async
<built-in method _assert_async of type object at 0x7aa46e5f3c20>
```

The docs also do not know about this method https://docs.pytorch.org/docs/2.12/search.html?q=assert_async

**Comment by ngimel** [comment]
We'll accept a PR making this method public and documenting it
