### ISSUE TITLE
Error at import torch - ImportError: DLL load failed: O sistema operacional não pode executar %1.

### ISSUE THREAD

**Issue by jcesteves** [pytorch/pytorch#36868]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.4.0
 - OS (e.g., Linux): Windows10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: No Have
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

![Capturar](https://user-images.githubusercontent.com/13789419/79638737-81551580-815d-11ea-98f3-fa340c64c152.PNG)

**Comment by peterjc123** [comment]
Please capture the log using `Process Monitor` and upload it here. Usually this error indicates that you are trying to load against a conflicting DLL (e.g. `libiomp5md.dll`) from the other places.

**Comment by jcesteves** [comment]
Hello man,

I can find the error, it's just a dll conflict in system32. I delete this
dll and run ok.
Thanks.

Em sáb., 18 de abr. de 2020 às 13:00, peterjc123 <notifications@github.com>
escreveu:
