### ISSUE TITLE
test_fmod_cuda in test_autograd is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#36862]
## 🐛 test_fmod_cuda in test_autograd is flaky
Very occasionally with `RuntimeError: graph_task->future_result_->completed() INTERNAL ASSERT FAILED`
See example failure:
https://app.circleci.com/pipelines/github/pytorch/pytorch/156952/workflows/8c86dcb0-85b9-42a7-ba74-b2a4ee890fe9/jobs/5181549

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by osalpekar** [comment]
Looks like https://github.com/pytorch/pytorch/pull/36856 should fix this internal assertion issue

**Comment by albanD** [comment]
The PR has been merged. Please re-open if we see this again.
