### ISSUE TITLE
Is caffe2 still under maintenance？

### ISSUE THREAD

**Issue by liuqibj** [pytorch/pytorch#36877]
little confused about the importance of caffe2 and pytorch in FB. Is caffe2 still under maintenance？ thanks

**Comment by albanD** [comment]
cc @soumith

**Comment by soumith** [comment]
no, caffe2 has no commitment on any fixes or patches or actions on bug reports. If you are relying on it now, you should treat it as "end of life" support: https://en.wikipedia.org/wiki/End-of-life_(product)
