### ISSUE TITLE
Add an option for filling the last batch in DataLoader

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#36872]
## 🚀 Feature

An option for `torch.utils.data.DataLoader` to fill the last batch (if it does not have the same length as the previous ones), instead of discarding it as the `drop_last` argument does.

## Motivation

While `drop_last` has become quite standard, I think it would be better to fill the last batch to obtain the same length (the missing values are sampled randomly among the previous examples), so that **all examples are taken into account by every epoch**.

## Pitch

One may think about adding a new boolean argument called `fill_last`, but I think we can replace the `drop_last` argument by a new string argument, e.g. `last_batch`:
- If `last_batch='drop'`, drop the batch.
- If `last_batch='fill'`, fill the batch.

cc @SsnL

**Comment by gchanan** [comment]
We think a workaround is sufficient here -- take the un-dropped last_batch and fill in the 'missing' data in the way you want.
