### ISSUE TITLE
Potential division by zero in quantization observer

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#36888]
Didn't manifest itself, but while reading the code, noticed that if min == max, the result will be infinity: https://github.com/pytorch/pytorch/blob/b0b9e704ed1f31ed1c81994c20e5a9f3715d2583/torch/quantization/observer.py#L894-L895

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
this is fixed by https://github.com/pytorch/pytorch/pull/40310
