### ISSUE TITLE
Add an optional arg for specifying classes to load in ImageFolder

### ISSUE THREAD

**Issue by toto-maru** [pytorch/pytorch#36892]
## 🚀 Feature
Add "classes" option to`torchvision.datasets.ImageFolder.__init__()` method, which specify the classes I want to use under "root", not every classes (folders) under "root".

## Motivation

I'd like to specify classes to use under "root" path, but current ImageFolder loads every classes (dirs) under "root" path.
 In Keras' [ImageDataGenerator.flow_from_directory](https://keras.io/preprocessing/image/), I can specify classes to use under "root" by passing "classes" optional argument. I'd like pytorch ImageFolder to have the same argument as Keras' ImageDataGenerator.flow_from_directory.

## Pitch

Add a new optional argument "classes" which takes list of classes I need, on 
`torchvision.datasets.ImageFolder.__init__()` method. 
If argument "classes" is not passed, ImageFolder loads all classes under "root" (same as current behavior).

cc @SsnL

**Comment by SsnL** [comment]
Could you please open an issue in https://github.com/pytorch/vision instead? This repo is about core PyTorch. The issue you raised is specific to torchvision. Thanks.
