### ISSUE TITLE
VS2019 compiler error

### ISSUE THREAD

**Issue by skn123** [pytorch/pytorch#36895]
## 🐛 Bug

Compiler error when building pytorch (fresh checkout from repo) using Visual Studio 2019
## To Reproduce
Usual CMake process

1.
1.
1.

![pytorch_error](https://user-images.githubusercontent.com/4594354/79685893-b777bf80-8259-11ea-970c-2364b0ccb35e.png)

## Environment
Visual Studio 2019 64Bit, Windows 10 profession.

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @peterjc123

**Comment by peterjc123** [comment]
Could you please tell me what have you done (exact steps)?

**Comment by skn123** [comment]
Fresh checkout from repo
CMake - CPU mode only
Python 3.6.8 (enabled in CMake)
Generated .sln file and opened it in VS 2019.
It downloaded all necessary dependencies and started the build process and this compilation error came.
Just for the sake of completeness; The same codebase could compile in UBuntu (Windows subsystem for linux to be specific)

**Comment by peterjc123** [comment]
> Fresh checkout from repo

Have you added the `--recursive` option?

> Generated .sln file and opened it in VS 2019.

How is the solution generated?

**Comment by peterjc123** [comment]
Anyway you can refer to the description here.
https://github.com/pytorch/pytorch#from-source

**Comment by skn123** [comment]
> 
> 
> > Fresh checkout from repo
> 
> Have you added the `--recursive` option?
> 
> > Generated .sln file and opened it in VS 2019.
> 
> How is the solution generated?

Absolutely, as I said, the same solution builds perfectly fine under Ubuntu. As you see, the error is related with a function in <algorithm>. So does this mean that something different (as in flags, etc.,) has to be done for VS versus Linux?

**Comment by peterjc123** [comment]
But the nightly builds fine so there's probably something wrong with your configuration. Could you please post the full log during configuration and build?

**Comment by mszhanyi** [comment]
@skn123 does the issue still exist? As https://github.com/pytorch/pytorch#from-source, there're some additional env variables need to set for VS.
Since there's no update for more than 3 months and VS 2019 is working well in our CI pipelines. 
We'll close this thread soon.
