### ISSUE TITLE
Loading entire dataset in one batch with utils.data.DataLoader

### ISSUE THREAD

**Issue by InCogNiTo124** [pytorch/pytorch#36909]
## 🚀 Feature

I'd like to propose a new feature of the `torch.utils.data.DataLoader`class, to have its `batch_size` equal to `len(dataset)`
## Motivation
Sometimes when testing and/or validating my model, I want to change the ratio of training set to the test/val set. When I do testing, though, I frequently wish to not have more than one iteration, but pass the entire dataset at once. I usually just bypass this with `batch_size=len(dataset)`, but that seems very inelegant to me.
Even more worrying situation is, when cross validating, to have data splits with different sizes. Although that too can me mitigated, in this case by dropping data, why not allow users not to drop it?

## Pitch
```python
# Let's load our test set
test_loader = DataLoader(test_dataset, batch_size=.....
# Wait I forgot what the dimensions are... Ah how frustrating
# Oh well I could use len() I guess
test_loader = DataLoader(test_dataset, batch_size=len(test_dataset))
# Well that looks just plain ugly. I wish there was a better way...
```

## Alternatives
As I said, the alternatives are either changing the batch sizes manually for every dataloader when testing/validating, or using the inelegant `len(dataset)` or even `.shape` attribute of tensors.

## Possible implementations
It could be implemented by setting `batch_size` to `0` or `-1`.

## Additional context
As I'm a student, most of my datasets are either The Standard Ones or very small real world datasets that can store entire test/val datasets in memory, but I do see that there definitely exist use cases where it is impossible to store test sets in memory at once.
Also, I'm also kinda looking to start contributing to open source and I figured this would be the best way I guess.

cc @SsnL

**Comment by SsnL** [comment]
Actually I don't see how 
```py
test_loader = DataLoader(test_dataset, batch_size=len(test_dataset))
```
is ugly. It seems much clearer and more readable than having `batch_size=-1` magically meaning loading the full dataset.

**Comment by gchanan** [comment]
I agree with @SsnL -- this doesn't look particularly ugly, and a magic sentinel isn't the best solution.
