### ISSUE TITLE
type annotation `-> (List[int], List[int])` gives RuntimeError for JIT

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#36902]
## 🐛 Bug

The JIT and MyPy disagree on what a valid type annotation should look like:
```
ERROR [0.008s]: test_class_sorting (jit.test_class_type.TestClassType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\circleci\project\test\jit\test_class_type.py", line 394, in test_class_sorting
    self.checkScript(test, ([Foo(2), Foo(1), Foo(3)],))
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 393, in checkScript
    frames_up=2)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 369, in checkScript
    cu = torch.jit.CompilationUnit(script, _frames_up=frames_up)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\jit\__init__.py", line 1058, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\jit\__init__.py", line 1063, in define
    self._c.define(lang, rcb)
RuntimeError: 
Expression of type tuple-literal cannot be used in a type expression:
  File "<string>", line 2
def test(li, reverse=False):
    # type: (List[Foo], bool) -> (List[int], List[int])
                                  ~~~~~~~~~~~~~~~~~~~ <--- HERE
    li_sorted = sorted(li)
    ret_sorted = torch.jit.annotate(List[int], [])
```
without `-> (List[int], List[int])` it's a syntax error for MyPy (and those cannot be handled with `ignore_errors`), with it the JIT gives a `RuntimeError`.

Discovered in gh-36584, in that PR (which enables running MyPy in CI over the whole code base) I'll disable this test.

## To Reproduce

1. Add the missing return type annotation ` -> (List[int], List[int])` in the place indicated by the traceback above.
2. Run the tests in `jit\test_class_type.py`.

## Expected behavior

No `RuntimeError`.

## Environment

Reproducible in CI, e.g. in `pytorch_linux_xenial_cuda10_2_cudnn7_py3_ge_config_legacy_test` - see gh-36584.

cc @suo

**Comment by suo** [comment]
Does using the tuple type `Tuple[List[int], List[int]]` work?

**Comment by fmassa** [comment]
FYI this is something that happened with torchvision as well, and for now we haven't found a solution https://github.com/pytorch/vision/pull/1696

**Comment by rgommers** [comment]
> Does using the tuple type `Tuple[List[int], List[int]]` work?

It does. And that's arguably more correct, even though MyPy seems to be happy with `(...)`. I'll send a PR to re-enable the test. Thanks @suo, sorry for the noise.

**Comment by rgommers** [comment]
torchvision CI errors look the same indeed, `Tuple[...]` should fix that.
