### ISSUE TITLE
"yolo layer  int libtorch 

### ISSUE THREAD

**Issue by bravestpeng** [pytorch/pytorch#36919]
### Please note that this issue tracker is not a help form and this issue will be closed.

libtorch1.4,there is a problem in yolo layer when I use cuda,but it is normal when I use cpu.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

Can you please fill in the template properly?
Also if you want to ask questions, as mentioned in the template, you should use the forum.

Closing this until it contains all info.
