### ISSUE TITLE
Why AdaptiveAvgPool2d use input.contiguous().view({-1, mean_size}).mean(-1) instead of mean({-1, -2}, true)

### ISSUE THREAD

**Issue by tgsmdww** [pytorch/pytorch#36916]
Op mean support more than 1 dim and can use keep_dim=true. The result is same.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your specific question the answer is that `AdaptiveAvgPool2d` was implemented before the support for multiple dims were added to mean.
