### ISSUE TITLE
Flatten in nn/modules/__init__.pyi

### ISSUE THREAD

**Issue by jerryc05** [pytorch/pytorch#36915]
## To Reproduce

1. `import torch.nn as nn`
2. `nn.` does not pop up `Flatten` (I mean autocomplete)

I also noticed that `from .flatten import Flatten` is missing from `nn/modules/__init__.pyi`. I am not sure if this is a bug.

I am using PyCharm.

## Environment
```
PyTorch version: 1.6.0.dev20200419+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1
OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect
Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: D:\Program Files\NVIDIA\CUDA\v10.0\bin\cudnn64_7.dll
Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.6.0.dev20200419+cu101          pypi_0    pypi
[conda] torchvision               0.7.0.dev20200419+cu101          pypi_0    pypi
```

cc @ezyang

**Comment by albanD** [comment]
Hi,

This is most likely the issue indeed. Do you want to try and change it to see if it works. And if so send a PR?

**Comment by jerryc05** [comment]
sure i will let you know if it worked

**Comment by jerryc05** [comment]
pr submitted

**Comment by zou3519** [comment]
This should be fixed now since we've inlined all the .pyi files straight into the module definitions (e.g., https://github.com/pytorch/pytorch/blob/69839ea3f6680d068db38795afe03ae4b8a30962/torch/nn/modules/flatten.py#L132). Please re-open this if it is not the case.
