### ISSUE TITLE
Error in lu_solve for batched large matrices on the GPU

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#36921]
## 🐛 Bug

lu_solve throws an error if it is provided with large batched data that is on the GPU. It works for unbachted data, data on the CPU, or tiny matrices (at least 3 x 3).

## To Reproduce
```py
import torch

# works for (1, 3, 3)
A = torch.rand(1, 1109, 1109)

# works on the CPU
A = A.cuda()

B = torch.eye(A.shape[1], dtype=A.dtype, device=A.device).expand(A.shape[0], -1, -1)

# works for unbatched data
# A = A[0]
# B = B[0]

LU_data, pivots = torch.lu(A)
torch.lu_solve(B, LU_data, pivots)
```

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> /pool01/home/twoertwe/test.py in <module>
>      13 
>      14 LU_data, pivots = torch.lu(A)
> ---> 15 torch.lu_solve(B, LU_data, pivots)
> 
> RuntimeError: CUDA error: invalid configuration argument

## Expected behavior

It should work! :)

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 9.2.1-17ubuntu1~16.04) 9.2.1 20191102
CMake version: version 3.15.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr0/local/cuda-9.0/lib64/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.0                      166    conda-forge
[conda] numpy                     1.18.1           py38h8854b6b_1    conda-forge
[conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py38_cu101    pytorch

```

cc @ezyang @gchanan @zou3519 @ngimel @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by ngimel** [comment]
Adding high-priority, as it is a crash.

**Comment by vishwakftw** [comment]
It seems to work for me on Google Colab.

**Comment by vishwakftw** [comment]
I'm testing MAGMA's implementation internally now.

**Comment by twoertwein** [comment]
> ~It seems to work for me on Google Colab.~ Actually not, it seems to silently fail with an incorrect result.

I hope that doesn't imply that `torch.inverse` has the same issue for batched-large-GPU matrices (I think I read somewhere that it is using LU behind the scenes.)

**Comment by vishwakftw** [comment]
@twoertwein Yes, you are right. `torch.inverse` isn't affected based on the MWE that you have given.

**Comment by vishwakftw** [comment]
Can confirm, this is a bug in MAGMA. Their tests don't pass for large enough matrix sizes. Specifically for the size in the MWE, we get:
```
% MAGMA 2.5.1 svn compiled for CUDA capability >= 5.0, 32-bit magma_int_t, 64-bit pointer.
% CUDA runtime 10000, driver 10010. OpenMP threads 4. 
% device 0: GeForce 940M, 1176.0 MHz clock, 2004.5 MiB memory, capability 5.0
% Mon Apr 20 15:19:43 2020
% Usage: ./testing/testing_dgesv_batched [options] [-h|--help]

% BatchCount   N  NRHS   CPU Gflop/s (sec)   GPU Gflop/s (sec)   ||B - AX|| / N*||A||*||X||
%============================================================================================
         1  1109  1109     ---   (  ---  )     16.49 (   0.22)   1.05e-07   failed
```

**Comment by vishwakftw** [comment]
Reported in MAGMA issues : https://bitbucket.org/icl/magma/issues/19/dgesv_batched-dgetrs_batched-fails-for

**Comment by twoertwein** [comment]
@vishwakftw someone on MAGMA asked for more information about the test output plus your setup (I guess mainly the output that you posted here)

**Comment by hejia-zhang** [comment]
I'm using pytorch 1.2.0.

I also use lu_solve and my matrix size is 936 * 1832. When I use FloatTensor it will work, while it doesn't work when I use DoubleTensor. The error message is cuda: too many resources requested to launch. I wonder if it's also related to this issue.

Thanks!

**Comment by rkansal47** [comment]
Hi, I was wondering if there was any update on this issue?

**Comment by twoertwein** [comment]
I don't think so, but you can easily avoid it with code like the following:

```py
@torch.jit.script
def lu_solve_batched(
    B: torch.Tensor, LU: torch.Tensor, pivots: torch.Tensor
) -> torch.Tensor:
    """Until https://github.com/pytorch/pytorch/issues/36921 is fixed."""
    if B.dim() == 2:
        B = B.expand(LU.shape[0], -1, -1)
    if B.shape[1] < 1025:
        return torch.lu_solve(B, LU, pivots)
    results = torch.empty_like(B)
    for ibatch in range(int(B.shape[0] / 1024)):
        index = torch.arange(
            1024 * ibatch, min(1024 * (ibatch + 1), B.shape[0]), dtype=torch.long
        )
        results[index] = torch.lu_solve(B[index], LU[index], pivots[index])
    return results
```

**Comment by rkansal47** [comment]
Thanks for the response! Unfortunately this appears to produce the same error: 

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/app/emd_loss/qpth/solvers/pdipm/batch.py", line 29, in lu_solve_batched
        B = B.expand(LU.shape[0], -1, -1)
    if B.shape[1] < 1025:
        return torch.lu_solve(B, LU, pivots)
               ~~~~~~~~~~~~~~ <--- HERE
    results = torch.empty_like(B)
    for ibatch in range(int(B.shape[0] / 1024)):
RuntimeError: CUDA error: invalid configuration argument
```

**Comment by twoertwein** [comment]
This doesn't seem to be an issue anymore, at lest not with CUDA 11.1 and pytorch 1.9

```py
import torch

A = torch.rand(1, 1109, 1109) + 10*torch.eye(1109).unsqueeze(0)
B = torch.eye(1109).unsqueeze(0)

A = A.cuda()
B = B.cuda()

LU_data, pivots = torch.lu(A)
solved = torch.lu_solve(B, LU_data, pivots)

(A.bmm(solved) - B).abs().max()  # tensor(1.5497e-06, device='cuda:0')
```

**Comment by rkansal47** [comment]
Hi, @twoertwein unfortunately I don't think this has been fully fixed. While your example does seem to work for me, e.g. this and many similar examples continue to produce the same error:

```
import torch

A = torch.rand(1, 1, 1) + 10*torch.eye(1).unsqueeze(0)
B = torch.rand(1, 1109).unsqueeze(0)

A = A.cuda()
B = B.cuda()

LU_data, pivots = torch.lu(A)
solved = torch.lu_solve(B, LU_data, pivots)
```

Additionally, your example but with `double` tensors instead of `float` also give the error:

```
import torch

A = torch.rand(1, 1109, 1109) + 10*torch.eye(1109).unsqueeze(0)
B = torch.eye(1109).unsqueeze(0)

A = A.double().cuda()
B = B.double().cuda()

LU_data, pivots = torch.lu(A)
solved = torch.lu_solve(B, LU_data, pivots)
```

**Comment by twoertwein** [comment]
@rkansal47  you are right, it still doesn't work when using `double` :(

```sh
    solved = torch.lu_solve(B, LU_data, pivots)
RuntimeError: CUDA error: invalid configuration argument
```
