### ISSUE TITLE
torch.backends.cudnn.version() is None

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#3693]
While `torch.backends.cudnn.enabled` is True; `torch.version__version__` is `0.2.0+50a63ee` (can't check master because of https://github.com/pytorch/pytorch/issues/3669)

Is it expected? I was looking for cudnn version used in runtime.

**Comment by zou3519** [comment]
It shows up on master but not 0.2 for me. Not sure why it doesn't show up in 0.2 but somewhere down the line it seems to have been fixed.

**Comment by soumith** [comment]
will be part of next release.
