### ISSUE TITLE
Retire torch/cuda/nccl.py

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#36940]
While investigating #36870, I just realized that there is another implementation to wrap NCCL APIs in `pytorch/torch/cuda/nccl.py` added > 2 years ago. These set of APIs are not tests or documented. We probably should just get rid of them.

cc @ngimel @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by ngimel** [comment]
DataParallel uses them, IIRC?

**Comment by mrshenli** [comment]
Hmm, I might missed sth. Looks like DataParallel's replicate and gather calls into `cuda.comm.broadcast_coalesced` and `cuda.comm.gather` which directly calls into pybind APIs. Only `reduce_add` uses APIs in `nccl.py`, but `reduce_add` and `reduce_add_coalesced` do not seem to be used anywhere.

**Comment by mrshenli** [comment]
Looks like we have two implementations here `cuda/comm.cpp` and `cuda/python_nccl.cpp`. It might worth consolidate them into one.

**Comment by zhaojuanmao** [comment]
@mrshenli looks like python_nccl.cpp includes python APIs binded to NCCL c++ APIs, cuda/comm.cpp are some util functions. sounds fine to keep them separated, how do you think?

**Comment by rohan-varma** [comment]
DataParallel indeed seems to call into the python APIs in `torch.cuda.comm()`, and don't appear to use torch.cuda.nccl. Although, this package is technically public and some users may be relying on it, so not sure if we can simply delete it. Also I saw some code checking the version with `torch.cuda.nccl.version().

**Comment by mrshenli** [comment]
Yep, saw an issue reporting usage on this API #38019. Looks like we cannot retire it, at least for now.

**Comment by mrshenli** [comment]
I am closing this issue for now, but please feel free to reopen if this surfaces again.
