### ISSUE TITLE
bin/protoc symlink failure when building from source on arch

### ISSUE THREAD

**Issue by MiroFurtado** [pytorch/pytorch#36950]
## Bug

When building pytorch from source on a clean install of Manjaro linux (with conda installed), I get the following error while building caffe2:

`[249/4074] Creating executable symlink bin/protoc
FAILED: bin/protoc 
/home/miro/anaconda3/bin/cmake -E cmake_symlink_executable bin/protoc-3.11.4.0 bin/protoc && :
CMake Error: failed to create symbolic link 'bin/protoc': function not implemented
`

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Manjaro Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-include               2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0

## Additional context

I've already run `conda install protobuf`. 

From `find`, protoc appears to be located at `/usr/bin/protoc`, `/home/miro/anaconda3/bin/protoc`, and `pytorch/third_party/protobuf/kokoro/release/protoc`

cc @malfet

**Comment by malfet** [comment]
@MiroFurtado, what filesystem `pytorch` is mounted on? Can you run `ln -s bin/protoc-3.11.4.0 bin/protoc` in `pytorch/build` folder?

**Comment by MiroFurtado** [comment]
Ah, apologies - I didn't realize that symlinks didn't work on `exfat` which is what my pytorch is mounted on.
