### ISSUE TITLE
refactor test/quantization/test_backward_compatibility.py with bundled_inputs

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#36958]
We have support for bundled inputs in
https://github.com/pytorch/pytorch/blob/master/torch/utils/bundled_inputs.py#L17
PR: https://github.com/pytorch/pytorch/pull/35631
we can refactor the backward_compatibility tests to use this.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by andrewor14** [comment]
This issue looks a bit out of date. I'm closing this since I don't think we're actually planning to do this anymore. @jerryzh168 Please let me know if this is not the case.
