### ISSUE TITLE
Under `ceil_mode=True` for `AvgPooling2d`, Pytorch fails in calculating pooling output shape as expected, and gets `NaN` results.

### ISSUE THREAD

**Issue by shiningrain** [pytorch/pytorch#36977]
## 🐛 Bug

**Under `ceil_mode=True` for `AvgPooling2d`, Pytorch fails in calculating pooling output shape as expected, and gets `NaN` results, no matter executing with CPU version or GPU version.**

**Taking Pytorch with CPU version as an example, given an input with the shape (1, 16, 4, 4), I get an unexpected output under layer the `AvgPool2d` , which contains `NaN`(Not a Number) results**，as shown in the following picture.

![avg-fig2](https://user-images.githubusercontent.com/46860123/79817052-23236f00-83b7-11ea-815c-605d80921c1a.jpg)

 In this case, the parameters of `AvgPool2d` are as follows:

```python
{
  'kernel_size': (1, 2), 
 'padding': (0, 1), 
 'stride': (2, 2),
 'ceil_mode': True, 
 'count_include_pad': True}
```

To investigate the root cause of such `NaN` results, I conduct a code tracing in the source code of Pytorch when executing `AvgPool2d`. Relevant code can be found in`aten/src/ATen/native/Pool.h`  and `aten/src/ATen/native/AveragePool2d.cpp`. 

Firstly, Pytorch invokes the function `pooling_output_shape_pad_lr` in `aten/src/ATen/native/AveragePool2d.cpp line 129-130`  to calculate to pooling output shape. 

![avg-fig3](https://user-images.githubusercontent.com/46860123/79817065-2880b980-83b7-11ea-8a53-cb88f590e5f7.jpg)

Then Pytorch passes the two parameters `outputHeight` and `outputWidth` to function `avg_pool2d_out_frame` in `aten/src/ATen/native/AveragePool2d.cpp (near line 14)` to calculate the average pooling for each pool unit. 

The implementation of `pooling_output_shape_pad_lr` is defined in `aten/src/ATen/native/Pool.h (near line 25)` . See the following picture.

![if_pad_l](https://user-images.githubusercontent.com/46860123/79817072-2d456d80-83b7-11ea-95df-df4fd0a34d3c.jpg)

The parameter `ceil_mode=True` indicates Pytorch uses ceil value instead of floor value when getting an output (refer to the official  [website](https://pytorch.org/docs/stable/nn.html?highlight=avgpool2d#torch.nn.AvgPool2d)). For pooling calculations,  the `ceil_mode=True` may make the last pool unit start outside the image. From the above code, we know that Pytorch tries to avoid such condition  by executing `--outputsize`. This indeed works, but is only be triggered when using padding on this dimension (see`if(pad_l) line 31`). In other words, if there is no padding  (`pad_l=0`) on this dimension, the outputsize will not be reduced by 1.

As a result, passing the output shape (also called `out-of-range` output shape) to `avg_pool2d_out_frame`, it will cause the last pool unit to be outside the image, as shown in the following example.

![avg-fig1](https://user-images.githubusercontent.com/46860123/79817084-33d3e500-83b7-11ea-90d5-7959559822fa.jpg)

To be specific, an `out-of-range` output shape will generate a `hstart`(or `wstart`) whose value is greater or equal to `hend`（or `wend`), thus making the `pool_size=(hend-hstart)*(wstart-wend)` be zero or a negative value,  as shown between the `line 46-83` in  `aten/src/ATen/native/AveragePool2d.cpp`.  

![hstart=hend](https://user-images.githubusercontent.com/46860123/79817095-39c9c600-83b7-11ea-847b-450f563022c8.jpg)

In particular, just as our example, when `hstart=hend` (or `wstart=wend` ), it will make `poolsize = 0`,`divide_factor=0` and`sum = 0`. Consequently,  the corresponding average pooling unit is calculated with  0 divided by 0, thus triggering `NaN`. Actually, the premise of function `avg_pool2d_out_frame` is that `hstart ` and `wstart ` are always smaller than `hend` and `wend`, and this needs to be guaranteed by the previous function `pooling_output_shape_pad_lr` in `pool.h`. But due to `if (pad_l)`, it only executes the relevant judgments and reductions when using padding on this dimension.

In addition, I also try multiple sets of other different parameters. They all trigger the `NaN` problem 
 on both CPU and GPU version, because of the same reason (`hstart=hend`), as shown in the following table.

| Parameters for `AvgPool2D`                                   | Input Shape     | Output Shape    |
| ------------------------------------------------------------ | --------------- | --------------- |
| {'ceil_mode': True, 'count_include_pad': True, 'kernel_size': (1, 4), 'padding': (0, 1), 'stride': (2, 2)} | (1, 16, 32, 32) | (1, 16, 17, 16) |
| {'ceil_mode': True, 'count_include_pad': True, 'kernel_size': 2, 'padding': (0, 1), 'stride': (3, 3)} | (1, 16, 9, 9)   | (1, 16, 4, 4)   |
| {'ceil_mode': True, 'count_include_pad': True, 'kernel_size': (1, 3), 'padding': (0, 1), 'stride': (4, 4)} | （1,16,4,4）    | (1, 16, 2, 2)   |

### Key insight

**Under the `ceil_mode=True`, the statement `if (pad_l)`  in function `pooling_output_shape_pad_lr` (see `aten/src/ATen/native/Pool.h` ) cannot reduce the `out-of-range` outputshape, making some pools are taken outside the input image.  Such situations occur in both CPU version and GPU version. Even worse, the special case when `hstart=hend` or `wstart=wend` will trigger the `NaN` output. Such `NaN` output in pooling operations will confuse users, and also will affect the subsequent calculation in the model, causing unexpected results.**

## To Reproduce

1. Just run the following code.

### Code to reproduce 

```
import numpy as np
import torch
   
kwargs = {
	'ceil_mode': True, 
	'count_include_pad': True, 
	'kernel_size': (1, 2), 
	'padding': (0, 1), 
	'stride': (2, 2)
	}  
input = (10 * np.random.randn(1,16,4,4)).astype(np.float32)    
layer = torch.nn.AvgPool2d(**kwargs)
modelinput=torch.from_numpy(input)
output = layer(modelinput)
ytrue=output.detach().numpy()
nanresult=np.isnan(ytrue).any()

print(nanresult)
```

## Expected behavior

The output is a matrix of constants, at least no 'Nan'

## Environment
Using /pytorch/torch/utils/collect_env.py to collect the environment.
```

Collecting environment information...
PyTorch version: 1.6.0a0+6ba734b
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V

Nvidia driver version: 430.26
cuDNN version: /usr/local/cuda-9.0/lib64/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0+cu92
[pip] torchvision==0.5.0+cu92
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-include               2020.0                      166  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] numpy                     1.18.1           py36h4f9e942_0  
[conda] numpy-base                1.18.1           py36hde5b4d6_1  
[conda] torch                     1.6.0a0+6ba734b          pypi_0    pypi

```

 - PyTorch Version (e.g., 1.0): 1.6.0a0+6ba734b(It is a CPU version, I compiled from Pytorch(master branch) source code ); 1.4.0-cu92 ( It is a GPU version, I used ` pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html ` command to install )
 - OS (e.g., Linux): Linux Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):( Just follow the guide in `https://github.com/pytorch/pytorch`, using `python setup.py install `)
 - Python version: 3.6.10
 - CUDA/cuDNN version: 9.2
 - GPU models and configuration:TITAN V
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by gchanan** [comment]
Thanks for the report -- I didn't look in detail, just noting that this behavior reproduces back to PyTorch 1.2.0 -- I didn't check before then.

**Comment by ngimel** [comment]
Thanks for the report, looks like a real bug. Setting high-pri because of a silent wrong answer. What output value do you expect if pooling window is fully outside the image - 0?

**Comment by shiningrain** [comment]
> Thanks for the report, looks like a real bug. Setting high-pri because of a silent wrong answer. What output value do you expect if pooling window is fully outside the image - 0?

 Thank you for your reply!
    **In general, the pool should not be entirely outside the image**. Thus the output size should be clipped to avoid this situation.  In fact, Pytorch does clip the output size(the `pooling_output_shape_pad_lr` mentioned above does have a clipping operation), but it only cuts the dimension with the pad(See the line with code 'if(pad_l)' in the above figures).  This makes the last line(or columns) of pools that have no pad in its dimension has not been clipped, then leads to unexpected output. Under certain parameters, it will get 'nan' results.
   **I think that in the above case all dimensions should be checked and clipped to avoid the situation of taking the pools outside the image. This issue should be avoided fundamentally.**

**Comment by Baranowski** [comment]
Can @shiningrain or anyone else please explain why `ceil_mode=True` might be even useful in AvgPool2d? I've been trying to make sense of the formula in the `pooling_output_shape_pad_lr` function that Shiningrain has pointed out:

```
div_rtn(
  inputSize + pad_l + pad_r - dilation * (kernelSize - 1) - 1 + (ceil_mode ? stride - 1 : 0),
  stride
) + 1
```

After removing the ceil_mode component this can be conceptually simplified as:

 ```
floor(
  inputSize + padding - (kernelSize - 1) - 1,
  stride
) + 1
```

But that is already equal to:

```
ceil(
  inputSize + padding - (kernelSize - 1),
  stride
)
```

That is, I believe that the default formula (with `ceil_mode=False`) already produces ceiling of the fraction `(inputSize + padding - (kernelSize - 1))/stride`, and I also think that this fraction is what size of the output approximates.

**Comment by shiningrain** [comment]
> Can @shiningrain or anyone else please explain why `ceil_mode=True` might be even useful in AvgPool2d? I've been trying to make sense of the formula in the `pooling_output_shape_pad_lr` function that Shiningrain has pointed out:
> 
> ```
> div_rtn(
>   inputSize + pad_l + pad_r - dilation * (kernelSize - 1) - 1 + (ceil_mode ? stride - 1 : 0),
>   stride
> ) + 1
> ```
> 
> After removing the ceil_mode component this can be conceptually simplified as:
> 
> ```
> floor(
>  inputSize + padding - (kernelSize - 1) - 1,
>  stride
> ) + 1
> ```
> 
> But that is already equal to:
> 
> ```
> ceil(
>   inputSize + padding - (kernelSize - 1),
>   stride
> )
> ```
> 
> That is, I believe that the default formula (with `ceil_mode=False`) already produces ceiling of the fraction `(inputSize + padding - (kernelSize - 1))/stride`, and I also think that this fraction is what size of the output approximates.

Hello, thanks for your reply!  I agree with your idea to some extent.  

In fact, this calculation can be found in the [official documentation](https://pytorch.org/docs/stable/nn.html?highlight=avgpool2d#torch.nn.AvgPool2d) (see AvgPool2d section).  I think that the calculation method is given in the document (see the following figure).

![image](https://user-images.githubusercontent.com/46860123/83588783-b2aa6900-a584-11ea-8761-fc40e076bf35.png)

In the document, for the mode of `ceil_mode = false`, the equivalent calculation is 

```
floor(
 inputSize + padding - (kernelSize - 1) - 1,
 stride
) + 1
```

When `ceil_mode =True`, the equivalent calculation is

```
ceil(
 inputSize + padding - (kernelSize - 1) - 1,
 stride
) + 1
```

Both of the cases have '+1', so I agree with your point that `ceil_mode = false` has already added 1.

**Therefore, I want to confirm whether Pytorch has an error in implementing `ceil_mode`, or is there a special reason for this extra calculation?**

**Comment by navyamehta** [comment]
Can we fix this by potentially changing how the output size is calculated to begin with? Maybe
<img src="https://render.githubusercontent.com/render/math?math=Output_i = \lfloor \frac{Input_i + (ceilMode ? Kernel_i - 1 : 0) - Kernel_i}{Stride_i} + 1 \rfloor">

**Comment by FredSRichardson** [comment]
Wow, I just came across this problem and it is really hard to fathom.  The documentation for `torch.nn.AvgPool1d` doesn't really tell you what the impact of `ceil_mode` is.

In my case, I was hoping for an easy way to deal with samples that are less than one window width.  I simply wanted the input to get zero padded on the right.  I believe @navyamehta suggestion above would fix this problem, but basically right now with `ciel_mode=True` the input length must be no less than `(kernel_size - stride + 1)` to avoid an error which is very strange...  I realize I could manually zero pad myself to deal with this problem.

```
>>> import torch
>>> kernel_size=50
>>> stride=10
>>> m = torch.nn.AvgPool1d(kernel_size, stride, ceil_mode=True)
>>> m(torch.randn(1, 1, kernel_size))
tensor([[[-0.1868]]])
>>> m(torch.randn(1, 1, kernel_size - stride + 1))
tensor([[[0.3020]]])
>>> m(torch.randn(1, 1, kernel_size - stride))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
/path/conda/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
/path/conda/envs/hf/lib/python3.10/site-packages/torch/nn/modules/pooling.py", line 559, in forward
    return F.avg_pool1d(
RuntimeError: Given input size: (1x1x40). Calculated output size: (1x1x0). Output size is too small
>>> 
 ```
