### ISSUE TITLE
HashNode does not support tuples

### ISSUE THREAD

**Issue by mneilly-et** [pytorch/pytorch#36979]
## 🐛 Bug

Glow has a caching graph runner that [hashes graphs using PyTorch's torch::hash_combine()](https://github.com/pytorch/glow/blob/master/torch_glow/src/Registration.cpp#L42) and uses the hash to determine if a graph has already been compiled for subsequent requests.

Glow also has [adaptive_avg_pool2d](https://github.com/pytorch/glow/blob/master/torch_glow/tests/nodes/adaptive_avg_pool2d_test.py#L10) tests which call _torch.nn.functional.adaptive_avgpool2d()_. Each of the three tests passes a different tuple as the _output_size_ parameter. 

When running these tests Glow fails because the same hash is returned for all three functions.

The failure occurs because PyTorch's _[HashNode](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/ir/node_hashing.cpp#L192)_ returns zero as the hash for each of the _output_size_ parameters. _output_size_ is defined in the PyTorch docs as:

> output_size – the target output size (single integer or double-integer tuple)

HashNode currently only support constants which are int, float or bool.

## To Reproduce

1. git clone https://github.com/pytorch/glow.git
2. cd glow/torch_glow
3. python setup.py install --run_cmake
4. cd tests
5. python -m pytest ./nodes/adaptive_avg_pool2d_test.py

## Expected behavior

HashNode returns a valid hash for constant tuple nodes

## Environment

PyTorch version: 1.5.0a0+8eaafbd
Is debug build: Yes
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.5.0a0+8eaafbd
[pip3] torch-glow==0.0.0
[pip3] torchtext==0.5.0
[pip3] torchvision==0.5.0
[conda] Could not collect

## Additional context

Related to pytorch/glow#4330

cc @suo

**Comment by suo** [comment]
cc @eellison

**Comment by eellison** [comment]
Hi @mneilly-et, this seems like a misuse of a (semi private) API. Hash functions don't guarantee that each input will map to a unique output. For that you can use `EqualNode`.
