### ISSUE TITLE
Failed to export an ONNX attribute 'onnx::Div', since it's not constant

### ISSUE THREAD

**Issue by malemo** [pytorch/pytorch#36997]
Trying to convert this model I get this error:
```
Traceback (most recent call last):
  File "save.py", line 19, in <module>
    torch.onnx.export(net, dummy, "Model.onnx", input_names=["image"], output_names=["output"])
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 657, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py", line 129, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py", line 82, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Div', since it's not constant, please try to make things (e.g., kernel size) static if possible
```

Printing the node from symbolic_helper just before the error is thrown:
`%344 : Long() = onnx::Div(%342, %343)`

I've checked everywhere and cannot find `Div` in the model, even the above line does not show the location of the error. 

What could it be?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ngimel** [comment]
Please provide a reproduction script that would allow us to reproduce the error.

**Comment by malemo** [comment]
I'm converting this [model](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing). 

My code: 
```
from unet import unet
import torch.onnx
import torch
from onnx_coreml import convert
import coremltools
import onnx




net = unet().cuda()
net.load_state_dict(torch.load('/content/drive/My Drive/Collab/f5/CelebAMask-HQ/face_parsing/model.pth'))


dummy = torch.rand(1,3,512,512).cuda()


torch.onnx.export(net, dummy, "Model.onnx", input_names=["image"], output_names=["output"])

onnx_model = onnx.load("Model.onnx")
onnx.checker.check_model(onnx_model)
onnx.helper.printable_graph(onnx_model.graph)

finalModel = convert('Model.onnx', minimum_ios_deployment_target='13', image_output_names=["output"], image_input_names=["image"])

finalModel.save('ModelML.mlmodel')


```

**Comment by yaeldekel** [comment]
Hi @malemo ,
The node where you are seeing this error is a "Pad" operation. In older versions of ONNX, the Pad operation took the lengths of the paddings as an attribute, i.e. these lengths have to be constant at compile time. in the U-Net model, the lengths of the paddings come from the output of previous nodes in the graph, which is why you could not export the model to ONNX. In version 11, the Pad operation in ONNX changed to take the lengths of the padding as an input, so if you try to export your model using `opset_version=11`, you should be able to export the model to ONNX.

**Comment by malemo** [comment]
@yaeldekel, thank you for your suggestion.
Exporting with opset_version=11, however, yields the following errors:
`Failed to export an ONNX attribute 'onnx::Cast', since it's not constant, please try to make things (e.g., kernel size) static if possible`

**Comment by yaeldekel** [comment]
Hi @malemo. I was not able to reproduce this error using opset 11. The only difference between the script I ran and your script above is that I did not use `net = unet().cuda()`, but `net = unet()`. It doesn't seem likely to me, but could that be making the difference?
Also, which .pth model did you use here?
>`net.load_state_dict(torch.load('/content/drive/My Drive/Collab/f5/CelebAMask-HQ/face_parsing/model.pth'))`

I used the model that can be downloaded from [here](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing#well-trained-model).

**Comment by malemo** [comment]
@yaeldekel, yes, I'm using the `model.pth` from the page you mentioned.

I've tried removing `.cuda()` and this resulted in further errors:
`RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

Were you able to finish the conversion without errors and generate .mlmodel file?

**Comment by yaeldekel** [comment]
@malemo, can you try loading the torch model with `map_location=torch.device('cpu')`?
```
torch.load('/content/drive/My Drive/Collab/f5/CelebAMask-HQ/face_parsing/model.pth', map_location=torch.device('cpu'))
```
To answer your question, I was not able to finish the conversion, the `convert` call gave a segmentation fault, I don't have any details where or why.

**Comment by dan0978520303** [comment]
hi @malemo  
I also encounter the same problem~
Could you give me some idea to solve this problem ?
Thank you very much!!!

**Comment by shubhambhokare1** [comment]
The segmentation fault occurs when you call the `convert` function imported from the `onnx_coreml` library on the line 500
`onnx_model = onnx.shape_inference.infer_shapes(onnx_model)`

In order to avoid running into the segfault, you can look into the [repo](https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing) you provided, especially the model_utils.py file. In the line 217, `offset` is returned as tensor, whereas you would want it to be a int value. Changing the code to 
`offset = int(outputs2.size()[2] - inputs1.size()[2])`
will resolve the segfault issue

**Comment by spandantiwari** [comment]
Thanks @shubhambhokare1 .
