### ISSUE TITLE
pytorch for cuda 10.0

### ISSUE THREAD

**Issue by ardeal** [pytorch/pytorch#36992]
Hi,

on the page:
https://pytorch.org/get-started

I could only find the torch for cuda 9.2 and cuda 10.1, but I can't find torch for 10.0.
Is torch for cuda 10.0 missing on the page? 
or is there any other solution for this problem?
or there is no torch for cuda 10.0?

Thanks,
Ardeal

**Comment by peterjc123** [comment]
there is no torch for cuda 10.0, but it doesn't mean you can't use torch with cuda 10.0 installed locally. It just mean that we don't build for cuda 10.0. Actually, if you have a new gpu driver, then you can use the cuda 10.1 package.
