### ISSUE TITLE
how to convert quantization_ware_training model to onnx

### ISSUE THREAD

**Issue by onesnow123q** [pytorch/pytorch#36991]
## ❓ Questions and Help
python  3.6
pytorch version: 1.4.0
onnx 1.6.0
In most issues, some of them mentioned about this question. but I still don't know how to convert a int8 model to onnx. I followed the tutorial (https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#quantization-aware-training) to try to train a quantization model, the pretrained model is got from model zoo. I already got the int8 model, but how to convert it to onnx??

**Comment by ngimel** [comment]
Please ask questions at discuss.pytorch.org.
