### ISSUE TITLE
Bad interaction between no_grad and numpy conversion

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#37000]
The code below raises an error:

```python
import torch

a = torch.rand(10, requires_grad=True)

with torch.no_grad():
    b = a.numpy()
# RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

Two issues here:
- Variable should not be mentioned in that error message
- Given that this is exactly what happens in custom autograd.Function, I think this should be allowed. The fact that we run in no_grad mode means that the user expects no gradients to flow.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by chengjinfang1216** [comment]
@ngimel  @albanD  Could I work on this issue？ I want to confirm with you about the fix princinple

**Comment by chengjinfang1216** [comment]
@ngimel  @albanD  Could I fix this issue as follows?
1. about error message, change "Variable" to "Tensor".
2. when use "with torch.no_grad():", allow user to call numpy() directly although its requires_grad is true.

**Comment by albanD** [comment]
Hi,

Yes sure !
First point is correct.
For the second one, yes, I think you can simply modify the conversion code that throw this error to check for `at::GradMode::is_enabled()` and not throw the error when it is not enabled.

You can add me as a reviewer to the PR when it is ready for review !

**Comment by chengjinfang1216** [comment]
@albanD, thank you for you kind reply，I'll work on it.

**Comment by albanD** [comment]
Corresponding PR is now merged.
