### ISSUE TITLE
Trying to build a Docker image

### ISSUE THREAD

**Issue by VIGNESHinZONE** [pytorch/pytorch#37047]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Hi , I want to get into open source development and i have been using pytorch for a while . Im trying build the Installation using Docker. Could you pls help me out

**Comment by VIGNESHinZONE** [comment]
On the main page it says that , all the install dependencies { numpy ninja pyyaml mkl mkl-include setuptools cmake cffi} and in the contributing guide there is guide to building it using docker

**Comment by ngimel** [comment]
Please follow the directions for the docker build on the main page. Please ask the questions at discuss.pytorch.org.

**Comment by VIGNESHinZONE** [comment]
Sorry for the inconvenience. Could pls look into this disscussion
https://discuss.pytorch.org/t/docker-build-error/77970

**Comment by ngimel** [comment]
cc @seemethere
