### ISSUE TITLE
CPU usage high when inferencing on CPU

### ISSUE THREAD

**Issue by tuanhanhdmprof** [pytorch/pytorch#37062]
I have a pre-trained model using pytorch. (only use CPU)
My laptop has 12 cores. 
When I inferenced on CPU, I saw system monitor. CPU usage of all cores is about 50%. Can I adjust the CPU usage for 2-4 cores (each core 100% is ok)?

Thank you.

cc @VitalyFedyunin

**Comment by peterjc123** [comment]
Would you please try out `torch.set_num_threads(2)`?

**Comment by tuanhanhdmprof** [comment]
I tried to do it. But not work :(

**Comment by colesbury** [comment]
On Linux, use something like `taskset -c 0-3 <program>` to only run on the first four cores. On Windows, you can apparently do something similar with `start /AFFINITY 0xf <program>`

https://stackoverflow.com/questions/10829974/taskset-equivalent-in-windows

**Comment by tuanhanhdmprof** [comment]
@peterjc123 I used this method but instead of 2 CPUs being used at 100%, 4 CPUs are using about 50%

**Comment by mruberry** [comment]
Hey @tuanhanhdmprof, sorry to hear you're not seeing the behavior you'd like. I'm not sure how much PyTorch can do in this case, however, as the operating system has considerable discretion about how it schedules threads.

**Comment by gchanan** [comment]
this doesn't appear to be a PyTorch bug or feature request and we try to limit github issues to that scope.  If you have more questions, kindly direct them to https://discuss.pytorch.org/.
