### ISSUE TITLE
[Poll] Add Windows support to torch.distributed package

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37068]
We have seen several requests for adding Windows support to `torch.distributed` package recently. ([1](https://discuss.pytorch.org/t/torch-distributed-for-windows-7-10/77855), [2](https://discuss.pytorch.org/t/pytorch-windows-is-parallelization-over-multiple-gpus-now-possible/59971), [3](https://discuss.pytorch.org/t/distributed-error-module-torch-distributed-has-no-attribute-is-initialized/31872), [4](https://discuss.pytorch.org/t/module-torch-distributed-has-no-attribute-is-initialized/55391/2), [5](https://github.com/pytorch/pytorch/issues/31363)) This issue is created to track how many people need this feature. Please add a reaction or comment below if your project needs `torch.distributed` on Windows.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
I hope this could be supported. We brought MKLDNN and FBGEMM support in 1.5.0. So maybe distributed is one (or maybe the only one) of the major features that are missing on Windows.

**Comment by lironmo** [comment]
+1.
what are the limitations using windows based os?

**Comment by mrshenli** [comment]
> what are the limitations using windows based os?

We are technically ready for adding this support, as libuv is cross platform and it already works well for PT Distributed on MacOS. It just requires additional engineering work and code maintenance overhead. We would like to make sure there are a reasonable amount of usages and adoptions if we pay the effort.

**Comment by danibendi** [comment]
Also joining the request. In terms of backends, will you be able to support GLOO on Windows?

**Comment by mrshenli** [comment]
> Also joining the request. In terms of backends, will you be able to support GLOO on Windows?

Yes, it will be GLOO-only in the first version. NCCL does not seem to support Windows: https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html#downloadnccl

**Comment by nbcsm** [comment]
> We are technically ready for adding this support 
just curious, technically ready means there is already a run-able implementation?

**Comment by mrshenli** [comment]
> just curious, technically ready means there is already a run-able implementation?

Yes for Gloo, but no for PyTorch Distributed. https://github.com/facebookincubator/gloo/pull/212 is the PR that adds libuv to Gloo. So technically Gloo can work on Windows, but we still need to add that to PyTorch's build script and tweak a few `#ifdef`s like the following one:

https://github.com/pytorch/pytorch/blob/3a0ff3cd2f04fcf3d4f6d152ab0772f048375cb6/torch/lib/c10d/ProcessGroupGloo.cpp#L429-L499

**Comment by ruslanvasylev** [comment]
torch.distributed would be very much appreciated for windows!

**Comment by abodh** [comment]
torch.distributed for windows is highly appreciated!

**Comment by N3bul0** [comment]
I would very like to see this too on windows. Any news regarding further plans?

**Comment by jounjieli** [comment]
torch.distributed would be very much appreciated for windows!

**Comment by XiaomoWu** [comment]
I'm a content creator as well as a deep learning researcher. It would be great that I can do distributed training on my Windows machine without relying on WSL2 (which is still in its early stage regarding CUDA support) or dual booting. Thanks.

**Comment by y78h11b09** [comment]
I hope this could be supported,  all of my work is  on windows 10

**Comment by AlbertoCenzato** [comment]
+1 for windows support

**Comment by peterjc123** [comment]
@mrshenli Could you please make a complete list about what is missing there so that I can contribute if I have time? Would you mind if I start by adding a Windows build job at https://github.com/facebookincubator/gloo?

**Comment by yeonmin** [comment]
+1 for windows support

**Comment by lexionbear** [comment]
+1 ! would love to have gaming desktop do some non gaming workloads

**Comment by nbcsm** [comment]
https://github.com/pytorch/pytorch/issues/42095

**Comment by Ownmarc** [comment]
yes!

**Comment by nbcsm** [comment]
@mrshenli, since this is tracked in https://github.com/pytorch/pytorch/issues/42095, maybe we can close this poll?

**Comment by mrshenli** [comment]
Yep, closing this issue. And please post future comments and feedback to #42095.

**Comment by siddhinath081** [comment]
+1 for windows support highly appreciated!

**Comment by mrshenli** [comment]
Hey @siddhinath081 

Windows supports for `DistributedDataParallel` (only with `FileStore` , i.e., `init_method="file://..."`) are landed in both master and [1.7 release branch](https://github.com/pytorch/pytorch/tree/release/1.7). Please feel free to try it and let us know your thoughts. Thanks!

**Comment by cheny1ming** [comment]
+1 for windows support highly appreciated!

**Comment by vukovicnikola** [comment]
+1 for torch.distributed for windows

**Comment by skyline75489** [comment]
Guys please use the GitHub reaction button instead, if you just want to “+1” on this. 

And we are working on this in #42095.

**Comment by wrrogers** [comment]
At my university, the servers are windows only and no plan to add support for linux.  Extremely frustrating.  There is WSL but the university windows contract won't allow for the upgrade to allow WSL for many years still.

**Comment by skyline75489** [comment]
@wrrogers If you can get PyTorch 1.7.0, you should be able to use DDP on WIndows. See https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

**Comment by lenisha** [comment]
Hi all,
The feature is now available https://pytorch.org/tutorials/intermediate/ddp_tutorial.html , It supports supports Gloo backend, FileStore and TcpStore. Could you give it a spin and let us know how did it go?
@wrrogers @vukovicnikola @cheny1ming @siddhinath081 @Ownmarc @lexionbear @yeonmin @AlbertoCenzato @y78h11b09   @XiaomoWu @jounjieli @N3bul0 @abodh @ruslanvasylev @danibendi @lironmo @peterjc123 @maksim-m @oke-aditya  @Jonas1312 @david-littlefield  @jeroenmollink @Nikronic @raresdolga @ljl371581995 @SivilTaram @Coldfire93 @deklesen  @Majeriot @Psiopteryx @ArthurEsquerrePourtere @alexorona @wrrogers @lyf6 @Tomas1337  @windspirit95 @sgbaird  @minkyu-choi04 @NaxAlpha @moatteya

**Comment by sebasarbe** [comment]
+1 please add windows!

**Comment by faseehahmed26** [comment]
please add windows support for RPC!

**Comment by sneha117** [comment]
please add windows support. This issue was opened on apr of 2020. Can anyone please try to solve it.
