### ISSUE TITLE
Building 1.5 from source failed to build NCCL

### ISSUE THREAD

**Issue by saareliad** [pytorch/pytorch#37108]
## 🐛 Bug

Building 1.5 from source failed to build NCCL

## To Reproduce

1. follow build from source instructions, tag 1.5. (python 3.8, cuda 10.2) 
2. can run full build, OR:
```
cd third_party/nccl/nccl
make -C src build BUILDDIR=/home_local/saareliad/pytorch/build/ncc
``` 

error is:

include/socket.h:329:60: error: 'SO_REUSEPORT' was not declared in this scope

cc @malfet

**Comment by saareliad** [comment]
checking out 
https://github.com/NVIDIA/nccl/tree/v2.6.4-1

seems to pass work better, i'll know tomorrow...

**Comment by malfet** [comment]
@saareliad can you please share a bit more information about your build environment, namely Linux OS flavor, cmake version. This can be done in an automated fashion by running `torch/utils/collect_env.py` in PyTorch repo checkout.

`SO_REUSEPORT` should be defined after `<sys/socket.h>` is included. Can you please run:
```
printf '#include <stdio.h>\n#include <sys/socket.h>\nint main(void) { return printf("SO_REUSEPORT=0x%%x\\n", SO_REUSEPORT); }' | cc -x c -; ./a.out
``` 
in terminal and share the output here?

**Comment by saareliad** [comment]
@malfet , output for the command is `SO_REUSEPORT=0xf`
I made changes in the env since so I didn't post it right away.

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.1

Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.82
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.18.1
[conda] blas                      1.0                         mkl
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.0                      166
[conda] mkl-include               2020.0                      166
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.0.15           py38ha843d7b_0
[conda] mkl_random                1.1.0            py38h962f231_0
[conda] numpy                     1.18.1           py38h4f9e942_0
[conda] numpy-base                1.18.1           py38hde5b4d6_1
```
Two importent things:
1. I first used cmake14.0 and then install from source, because I encounter cmake problems
 (cmake can't find pthread and therefore can't find MKL & BLAS), I tried solving it for hours and nothing helped.
2. I mannaged to accidently build the NCCL used by the repo with pip, in an env without [my cuda-aware-open-mpi](https://anaconda.org/saareliad/se-msnag2
), but yet without aforementioned MKL & BLAS.

**Comment by saareliad** [comment]
This was env pollution  problem.
Occurred because I build on "screen" and it inherited previous env variables.
I made it work by building everything from source.
