### ISSUE TITLE
What prior knowledge do I need to contribute to this project?

### ISSUE THREAD

**Issue by YuanYingdong** [pytorch/pytorch#37116]
I'm a freshman to PyTorch but good at c++, what prior knowledge do I need to contribute to this project? Better to make a list.

**Comment by mruberry** [comment]
Hey @YuanYingdong! You can look at our [Contribution Guide](https://pytorch.org/docs/stable/community/contribution_guide.html) for a better idea of how to start contributing. I suggest you find a starter project like it recommends and focus on working through it. The project should naturally suggest the skills you need.
