### ISSUE TITLE
torch.isfinite() doesn't work for fp16 on CPU

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#37111]
## 🐛 Bug

torch.isfinite() doesn't work for fp16 on CPU

## To Reproduce
```
In [1]: import torch

In [2]: t = torch.tensor([1], dtype=torch.float16)

In [3]: torch.isfinite(t)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-853377915b40> in <module>()
----> 1 torch.isfinite(t)

RuntimeError: "abs_cpu" not implemented for 'Half'
```

## Expected behavior

torch.isfinite should work for fp16 on CPU

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.1
[pip3] torch==1.5.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2017.0.3                      0  
[conda] numpy                     1.13.1                   py36_0  
[conda] numpy                     1.15.1                    <pip>
[conda] torch                     1.5.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

## Additional context

`abs_cpu` and probably `eq_cpu` need to support fp16 to make `isfinite` work with fp16.

**Comment by mruberry** [comment]
Thanks for reporting this issue, @kit1980!

**Comment by malfet** [comment]
@kit1980 this should be addressed in the latest nighly build, can you please verify?

**Comment by kit1980** [comment]
@malfet Works for me with nightly. Thank you for such a fast turnaround!
