### ISSUE TITLE
Link error, Libtorch 1.5 on Windows

### ISSUE THREAD

**Issue by slaweks17** [pytorch/pytorch#37124]
## 🐛 Bug
Large number of link errors when trying rebuild an existing program with the new 1.5 version of Libtorch on Windows

## To Reproduce

1. Create a following program

#include <torch/torch.h>
int main(int argc, char** argv) {
    torch::Tensor x_t;
}

2. Try to build it. The compilation is successful, the link fails with messages like
LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl at::Tensor::Tensor(void)" (__imp_??0Tensor@at@@QEAA@XZ) referenced in function main	Pytorch15	C:\progs\c++\CTorch\Pytorch15\test.obj	1	

## Environment
Windows 10, Visual Studio 2019, toolset either v141 or v142, the linker options:
/OUT:"C:\progs\c++\CTorch\x64\Debug\Pytorch15.exe" /MANIFEST /NXCOMPAT /PDB:"C:\progs\c++\CTorch\x64\Debug\Pytorch15.pdb" /DYNAMICBASE "torch.lib" "c10.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG /MACHINE:X64 /INCREMENTAL /PGD:"C:\progs\c++\CTorch\x64\Debug\Pytorch15.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Debug\Pytorch15.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"C:\progs2\libtorch_debug\lib" /TLBID:1 

The program builds and works when liked with libtorch 1.4.

**Comment by peterjc123** [comment]
Well, it looks like you are constructing the VS project by hand. Please link against `torch_cpu.lib` instead of `torch.lib`. If you are using CUDA, then you'll need link against `torch_cuda.lib` and add the following argument `-INCLUDE:?warp_size@cuda@at@@YAHXZ`.

**Comment by slaweks17** [comment]
Great! Thank you very much!!

**Comment by jianyin2016** [comment]
> Well, it looks like you are constructing the VS project by hand. Please link against `torch_cpu.lib` instead of `torch.lib`. If you are using CUDA, then you'll need link against `torch_cuda.lib` and add the following argument `-INCLUDE:?warp_size@cuda@at@@YAHXZ`.

That is it! but where should I add the argument `-INCLUDE:?warp_size@cuda@at@@YAHXZ` ?

**Comment by peterjc123** [comment]
http://nanapro.org/en-us/documentation/img/linker_cmdline.png

**Comment by jianyin2016** [comment]
That is very nice of you. @peterjc123 
thanks!

**Comment by xpngzhng** [comment]
hi @peterjc123 
Sorry to bother you again, I did not understand your solution.

What the the connection between
"__declspec(dllimport) public: __cdecl at::Tensor::Tensor(void)" (_imp??0Tensor@at@@QEAA@XZ)
and
-INCLUDE:?warp_size@cuda@at@@YAHXZ

for my project, If I only link against torch_cuda.lib, there are 81 unsolved references.
adding  -INCLUDE:?warp_size@cuda@at@@YAHXZ  in the Linker -> Command Line -> Additional Options  did not work.

**Comment by peterjc123** [comment]
@xpngzhng For all the linker flags, please refer to the script [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L1249). I don't expect some many of you guys creating a VS project by yourself without using CMake.

**Comment by xpngzhng** [comment]
@peterjc123 
got it, thanks

**Comment by yoshihingis** [comment]
hi @peterjc123
Sorry to bother you again ,
I built mnist.cpp with the libtorch ver1.5  according with your advice , but I did not get good result.

(1) About Linked Libs
 torch.lib : not linked.
torch_cpu.lib : linked.
torch_cuda.lib : linked

(2)Commnad line
 a. I did not add the additional command , mnist operated correctly at CPU mode.
 b. I add the additional command -INCLUDE:?warp_size@cuda@at@@YAHXZ , GPU was detected and The Message "CUDA available ! Trining on GPU" was indicated, but any information of training progress was never indicated. I attached the capture image
![mnist_error](https://user-images.githubusercontent.com/18341725/80786491-cb5ae400-8bbe-11ea-81d7-76545061ef14.jpg)

・I made mnist.sln file by cmake by using CmakeLists.txt as blow. I could build mnist with no error.
[CMakeLists.txt](https://github.com/pytorch/pytorch/files/4562712/CMakeLists.txt)

But the result was same at GPU MODE, only  "CUDA available ! Training on GPU" was indicated ,but 
any information of training progress was never indicated.

 I want to know your opinion.

Regards,

**Comment by peterjc123** [comment]
@yoshihingis You'll need to copy the libtorch DLLs to the directory of your target executable.

**Comment by yoshihingis** [comment]
Dear peterjc123

 Thank you for your reply.
But I copy the libtorch Dlls to the same directory of executable file. hence the mnist operated correctly at CPU mode . Unfortunately I faced on the trouble at only GPU mode.

**Comment by peterjc123** [comment]
@yoshihingis Please try the following commands.
```cmd
git clone https://github.com/pytorch/examples.git
curl -kLO https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-d
eps-1.5.0.zip
set LIBTORCH_ROOT=%CD%\libtorch
7z x libtorch-win-shared-with-deps-1.5.0.zip
cd examples\cpp\mnist
mkdir build
cd build
cmake -G"Visual Studio 16 2019" -Ax64 -Thost=x64 -DCMAKE_PREFIX_PATH="%LIBTORCH_ROOT%" ..
cmake --build . --config Release
:: Please note that the directory `data` must be in the current working directory
:: Otherwise, please specify the absolute path in your code
Release\mnist.exe
```

**Comment by yoshihingis** [comment]
Dear peterjc123
Thank you for your support.

The mnist of libtorch ver1.5 operated correctly at GPU mode , 

I wonder why the mnist did not operated correctly at GPU MODE by built GUI Visual Studio 2019?

regards,
![commnad_mnist](https://user-images.githubusercontent.com/18341725/80798295-0d941d80-8bdf-11ea-817f-474c2342c0f4.jpg)

**Comment by peterjc123** [comment]
@yoshihingis please see the comments in the previous post.

**Comment by Whu-wxy** [comment]
@peterjc123 
Hello, are you familiar with Qt?
`torch::cuda::is_available() ` always return false in Qt , linux, so how should I add the argument `-INCLUDE:?warp_size@cuda@at@@YAHXZ`  in Qt?

**Comment by peterjc123** [comment]
@Whu-wxy Sorry, I'm so familiar with Qt. But someone else mentioned that you could add it to the QMAKE_LFLAGS entry in the .pro file and regenerate the project.

**Comment by Whu-wxy** [comment]
@peterjc123 Thanks, i will try this

**Comment by yoshihingis** [comment]
Dear peterjc123

Issue:
(1) Can I use  Cmake method to make sln file only with PC which is installed Nvidia CUDA .
(2) Where I have to add the  the argument -INCLUDE:?warp_size@cuda@at@@YAHXZ,
   command line or linker :additional dependent file?

Environment:
 Windows 10 Pro 64bit build 1909
 Microsoft Visual Studio 2019 community.
 libtorch Ver1.5 (  libtorch-win-shared-with-deps-1.5.0)
 
Reproduce:
I made Visual studio 2019 sln file by Cmake according with your advice.
The  "mnist.cpp" GPU mode operated correctly .
And I checked linler:  the additional dependent file of Visual studio's  mnist property.
(a)Please refer to attached Excel file sheet 1: 
[libtorch_v1.5_file.xlsx](https://github.com/pytorch/pytorch/files/4642238/libtorch_v1.5_file.xlsx)
  1. The libs of Nvidia were linked by the absolute path
      They were almost linked against Nvidia CUDA  toolkit folder.
     If the CUDA was not installed to my PC, I could not make VS sln file.

 2. I found the  argument -INCLUDE:?warp_size@cuda@at@@YAHXZ at the linker : additional 
   dependent folder.
   Do I have to this argument  on the Command LINE?
   Which is right?

Question:
 ・If I will made Visual studio project file by hand , Are only 7 files are mandatory as below ?
   c10.lib
  caffe2_nvrtc.lib 
  c10_cuda.lib
  torch.lib
  torch_cuda.lib
  torch_cpu.lib
  caffe2_module_test_dynamic.lib

・Please refer to excel sheet 2 .
    I checked  caffe2_module_test_dynamic.dll by software "Dependancies".
    caffe2_module_test_dynamic.dll has dependencies with various Nvidia dlls whic were included within libtorch version1.5 zip file.
  
   If  I will use  caffe2_module_test_dynamic.lib at the additional dependent file of VS , the caffe2_module_test_dynamic.dll called various Nvidia dlls which were included within zip file.
 Hence , absolute path will be not needed and the installation of CUDA.
  Please refer to attached excel file sheet 3.

 Is My thought right ?

**Comment by peterjc123** [comment]
> (1) Can I use Cmake method to make sln file only with PC which is installed Nvidia CUDA .

Your problem is not clear. Is "Can I use something other than CMake to create my project based on LibTorch given that I have CUDA installed globally" what you mean? If that's the problem, then the answer is yes. You can use VS GUI to create a project.



> (2) Where I have to add the the argument -INCLUDE:?warp_size@cuda@at@@YAHXZ,
> command line or linker :additional dependent file?

libraries: 
- Navbar -> Project -> Properties -> Linker -> Command Line -> General -> Additional Library Directories 
- Navbar -> Project -> Properties -> Linker -> Command Line -> Input -> Additional Dependencies

linker flags: 

- Navbar -> Project -> Properties -> Linker ->Command Line -> Additional flags



> 1. The libs of Nvidia were linked by the absolute path
>    They were almost linked against Nvidia CUDA  toolkit folder.
>    If the CUDA was not installed to my PC, I could not make VS sln file.

That's normal. You'll need to install CUDA before building a LibTorch project that uses CUDA.



> 2\. I found the  argument -INCLUDE:?warp_size@cuda@at@@YAHXZ at the linker : additional
>     dependent folder.
>     Do I have to this argument  on the Command LINE?
>     Which is right?

I am not fully aware of what you want to express. But you can refer to the answer of the second question.



> ・If I will made Visual studio project file by hand , Are only 7 files are mandatory as below ?
> c10.lib
> caffe2_nvrtc.lib
> c10_cuda.lib
> torch.lib
> torch_cuda.lib
> torch_cpu.lib
> caffe2_module_test_dynamic.lib

Well, they are all the libs of LibTorch. `caffe2_module_test_dynamic.lib` and `caffe2_nvrtc.lib` is not required. But if you use something else like OpenCV, then you may need additional libs.



> If I will use caffe2_module_test_dynamic.lib at the additional dependent file of VS , the caffe2_module_test_dynamic.dll called various Nvidia dlls which were included within zip file.
> Hence , absolute path will be not needed and the installation of CUDA.
> Please refer to attached excel file sheet 3.
> 
> Is My thought right ?

I don't quite understand your question.

**Comment by yoshihingis** [comment]
Dear Peter
 Thank you for your quick answer.
  Your answer is very clear..  
 You answer deleted my problems for Cmake to make VS sln file. 

・The quesiton is as blow ， it is my miss-understanding．
　Please forget it. sorry for my mistakes. 

If I will use caffe2_module_test_dynamic.lib at the additional dependent file of VS , the caffe2_module_test_dynamic.dll called various Nvidia dlls which were included within zip file.
Hence , absolute path will be not needed and the installation of CUDA.
Please refer to attached excel file sheet 3.

**Comment by albertchristianto** [comment]
Hi, everyone. 
this problem still appears in libtorch version 1.6, while trying to add libtorch c++ cuda to my existing project.

For future reference, the solution is: 
add `/INCLUDE:"?warp_size@cuda@at@@YAHXZ"` in Configuration Properties -> Linker -> Command Line -> Additional Options . by reading this comment from @peterjc123 https://github.com/pytorch/pytorch/issues/31611#issuecomment-594383154. use "/"  not "-"

thank you very much for the help.

**Comment by InfiniteLife** [comment]
I am having same issue.

I've built project with cmake, which created VS Studio 2019 project. I tried to add line `/INCLUDE:"?warp_size@cuda@at@@YAHXZ"` but it do not helps. 
I have all libraries linked in dependencies and if I remove `torch_cpu.lib` project wont build(although `torch_gpu.lib` is also linked). CPU version works fine.

Here is call stack:

![image](https://user-images.githubusercontent.com/7304884/95577879-9e4b1100-0a3b-11eb-84d5-2648280a17ee.png)

![image](https://user-images.githubusercontent.com/7304884/95577907-aa36d300-0a3b-11eb-844c-9b94fc9f020f.png)

Here is code:
```
    torch::NoGradGuard no_grad;
    torch::jit::script::Module module;
    torch::Device device(torch::kCUDA);

    try {
        // Deserialize the ScriptModule from a file using torch::jit::load().
        module = torch::jit::load(path, device);
    }
    catch (const c10::Error& e) {
        std::cerr << "error loading the model\n";
        return -1;
    }

    std::cout << "ok\n";

    torch::Tensor tensor = torch::ones({ 1, 3, 384, 640 }, device);

    // Execute the model and turn its output into a tensor.
    auto output = module.forward({ tensor }).toTuple();
    std::cout << "ok\n";
```

**Comment by rcg12387** [comment]
@InfiniteLife What is you libtorch version? Try `/INCLUDE:"?ignore_this_library_placeholder@@YAHXZ"`.

**Comment by tom-huntington** [comment]
> @InfiniteLife What is you libtorch version? Try `/INCLUDE:"?ignore_this_library_placeholder@@YAHXZ"`.

Thanks, this is what worked for me worked in visual studio
