### ISSUE TITLE
missing tools.nnwrap module on completely clean Win 10 install

### ISSUE THREAD

**Issue by kdemarest** [pytorch/pytorch#37126]
I just got a completely new Window 10 machine. Installed Python 3.7.0 and nothing else. Attempted 
to use pip to install pytorch. Below is the log.

The exact error that is stopping me is:
    ModuleNotFoundError: No module named 'tools.nnwrap'

To be clear, this is the simplest possible install. At first I was on python 3.8 and discovered that I was in 32 bit. I removed that and installed 3.7.0 64 bit instead, and when I run python I see

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32

Here is the exact log:

    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kende\\AppData\\Local\\Temp\\pip-install-vc8yd3w8\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\kende\\AppData\\Local\\Temp\\pip-install-vc8yd3w8\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kende\AppData\Local\Temp\pip-record-hmsivr3t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python37\Include\torch'
         cwd: C:\Users\kende\AppData\Local\Temp\pip-install-vc8yd3w8\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kende\AppData\Local\Temp\pip-install-vc8yd3w8\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\kende\AppData\Local\Temp\pip-install-vc8yd3w8\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\kende\AppData\Local\Temp\pip-install-vc8yd3w8\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kende\\AppData\\Local\\Temp\\pip-install-vc8yd3w8\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\kende\\AppData\\Local\\Temp\\pip-install-vc8yd3w8\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kende\AppData\Local\Temp\pip-record-hmsivr3t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python37\Include\torch' Check the logs for full command output.

cc @malfet

**Comment by mruberry** [comment]
Could you be facing this issue? 

https://discuss.pytorch.org/t/error-installing-torch/53352/2

Historically getting a single Python 64 has addressed this issue.

**Comment by kdemarest** [comment]
Not exactly.

I had to remove 32 bit python, yes, but then I ALSO had to run in Windows
Powershell, I think because it is 64 bit and perhaps the old Cmd.exe
(Command Prompt) is not?

Anyhow, I have gotten it to work. But if would be a LOT more kind if
pytorch somehow checked for 32 bit. I wasted substantial time, and I can't
be alone.

*Ken Demarest*
ken.demarest@gmail.com
415.342.9731
Austin, Texas ▪ United States

**Comment by mruberry** [comment]
@kdemarest You're definitely NOT alone judging from how many posts there are on the issue. Maybe there is some way we can provide some information earlier in this process.

**Comment by peterjc123** [comment]
> Anyhow, I have gotten it to work. But if would be a LOT more kind if pytorch somehow checked for 32 bit. I wasted substantial time, and I can't be alone.

Related: https://github.com/pytorch/pytorch/issues/27815

**Comment by peterjc123** [comment]
> I had to remove 32 bit python, yes, but then I ALSO had to run in Windows Powershell, I think because it is 64 bit and perhaps the old Cmd.exe (Command Prompt) is not?

It'll be good to keep only Python environment in PATH. Otherwise, it will easily leads to environment inconsistency. (e.g. Python and pip points to different envs.) To get cleaner envs with multiple python installations, maybe you can use the package manager conda.
