### ISSUE TITLE
How to rebuild the libtorch to get the lib.so after download the libtorch from https://download.pytorch.org/libtorch/nightly/cu92/libtorch-win-shared-with-deps-latest.zip?

### ISSUE THREAD

**Issue by Edwardmark** [pytorch/pytorch#37132]
how to build and make libtorch after I change the code in https://download.pytorch.org/libtorch/nightly/cu92/libtorch-win-shared-with-deps-latest.zip?
Any guide please?
Thanks in advance.

**Comment by peterjc123** [comment]
It depends on which part of code you're changing. If you are changing the headers in LibTorch and your own source files, then you may simply trigger a rebuild of the project. Otherwise, you'll need to build LibTorch from source.

**Comment by Edwardmark** [comment]
@I just change the headers for add namespace in DeviceType as using c10::DeviceType, how to trigger a rebuild of the project? Do I have to rebuild the lib?

**Comment by Edwardmark** [comment]
@I just change the headers for add namespace in DeviceType as using c10::DeviceType, how to trigger a rebuild of the project? Do I have to rebuild the lib?

**Comment by peterjc123** [comment]
Nope, just retry the build commands. If you are using VS GUI, then click `BUILD->REBUILD`. If you are using cmake, then `cmake --build . --config Release`.

**Comment by Edwardmark** [comment]
@peterjc123 but libtorch do not have cmakelists in the prebuild packages https://download.pytorch.org/libtorch/nightly/cu92/libtorch-win-shared-with-deps-latest.zip? , so how to run cmake?
So you mean that I do not rebuild libtorch but just use it to rebuild my new project?
Is that right?

**Comment by peterjc123** [comment]
@Edwardmark Yeah, just write the CMakeLists.txt according to https://github.com/pytorch/examples/blob/master/cpp/custom-dataset/CMakeLists.txt.
