### ISSUE TITLE
torch.distributions.utils.broadcast_all does not support Tensor-like objects

### ISSUE THREAD

**Issue by HEmile** [pytorch/pytorch#37141]
## 🐛 Bug

`torch.distributions.utils.broadcast_all` will crash when it receives Tensor-like objects, as `torch.is_tensor` returns `False` on Tensor-likes that do not subclass Tensor. This prevents creating distribution objects using Tensor-likes.

## To Reproduce

Consider the class

```python
class TensorLike:
    def __torch_function__(func, types, args=(), kwargs=None):
        print("In __torch_function_")
```
Now create (for example) a Normal distribution using it:

```python
from torch.distributions import Normal

Normal(loc=TensorLike(), scale=1)
```

This crashes with
```
Traceback (most recent call last):
  File "/Users/emile/Documents/GitHub/storchastic/test/test_broadcast_all.py", line 11, in <module>
    Normal(TensorLike(), scale=1)
  File "/Users/emile/.conda/envs/threes-ai/lib/python3.7/site-packages/torch/distributions/normal.py", line 44, in __init__
    self.loc, self.scale = broadcast_all(loc, scale)
  File "/Users/emile/.conda/envs/threes-ai/lib/python3.7/site-packages/torch/distributions/utils.py", line 24, in broadcast_all
    raise ValueError('Input arguments must all be instances of numbers.Number or torch.tensor.')
ValueError: Input arguments must all be instances of numbers.Number or torch.tensor.
```

## Expected behavior

If a Tensor-like is given to `broadcast_all`, the `torch.broadcast_tensors` call will defer handling of Tensor-likes to `__torch_function__`. Tensor-likes should pass the first check in `broadcast_all`. Tensor-likes should be ignored when creating `Tensor` objects from `Number`s. This should allow Tensor-likes to be used in `broadcast_all`.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] storchastic==0.0.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] numpy                     1.17.2           py37h99e6662_0  
[conda] numpy-base                1.17.2           py37h6575580_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] torch                     1.3.1                    pypi_0    pypi

## Additional context

`torch.is_tensor` is in the list of `get_ignored_functions`, meaning that it will not call `__torch_function__` by design and thus will not allow Tensor-likes to pass by design.

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by HEmile** [comment]
My apologies for the bump, but this is still a big problem for me, as I use Distributions a lot in my code and it makes little sense to inherit `torch.Tensor`.

**Comment by fritzo** [comment]
Feel free to suggest a fix in the form of a PR 😄
