### ISSUE TITLE
torch.cdist produces nan gradients in Pytorch 1.5, but not Pytorch 1.4

### ISSUE THREAD

**Issue by brianhhu** [pytorch/pytorch#37154]
## 🐛 Bug

torch.cdist produces nan gradients in Pytorch 1.5, but not Pytorch 1.4

## To Reproduce

1. Run the similarity example here: https://github.com/pytorch/vision/tree/master/references/similarity

2. On Pytorch 1.4, training proceeds normally with the loss decreasing each iteration

3. On Pytorch 1.5, the gradients become nan after the first iteration, which breaks training

4. I used torch.autograd.detect_anomaly to identify that torch.cdist is the problem (error trace below)

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/Projects/vision/references/similarity/train.py in <module>
    171 if __name__ == '__main__':
    172     args = parse_args()
--> 173     main(args)

~/Projects/vision/references/similarity/train.py in main(args)
    132     for epoch in range(1, args.epochs + 1):
    133         print('Training...')
--> 134         train_epoch(model, optimizer, criterion, train_loader,
    135                     device, epoch, args.print_freq)
    136 

~/Projects/vision/references/similarity/train.py in train_epoch(model, optimizer, criterion, data_loader, device, epoch, print_freq)
     25         with torch.autograd.detect_anomaly():
     26             loss, frac_pos_triplets = criterion(embeddings, targets)
---> 27             loss.backward()
     28         optimizer.step()
     29 

~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    196                 products. Defaults to ``False``.
    197         """
--> 198         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    199 
    200     def register_hook(self, hook):

~/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     96         retain_graph = create_graph
     97 
---> 98     Variable._execution_engine.run_backward(
     99         tensors, grad_tensors, retain_graph, create_graph,
    100         allow_unreachable=True)  # allow_unreachable flag

RuntimeError: Function 'SqrtBackward' returned nan values in its 0th output.
```

## Expected behavior

Training proceeds normally without nan gradients due to torch.cdist

## Environment

 - PyTorch Version (e.g., 1.0): Pytorch 1.5
 - OS (e.g., Linux): Ubuntu 18.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
 - Python version: 3.8.2
 - CUDA/cuDNN version: 10.1/7.6
 - GPU models and configuration: RTX 2080 Ti/Titan Xp (tried both)
 - Any other relevant information: I believe things work in Pytorch 1.4

cc @ezyang @gchanan @zou3519 @fmassa

**Comment by klicperajo** [comment]
Maybe a faster way to reproduce this:

1. [Download the tensors](https://figshare.com/s/47d6035b990fa62d730d)
2. Run the code
```python
import torch

emb1, emb2, cdist_grad = torch.load('cdist_grad.pt')

emb1.retain_grad()
d = torch.cdist(emb1, emb2)
d.backward(cdist_grad)

print(emb1.grad[0, 17])
```

**Comment by emcastillo** [comment]
Seems the problem here is that the gradient that serving as an input for the sqrt backward pass has negative values

**Comment by emcastillo** [comment]
I cloned the cdist function in Python to make debugging easy and it also yields Nans

```python
import torch


def cloned_cdist(x1, x2):
    x1_norm = x1.pow(2).sum(-1, True)
    x1_pad = torch.ones_like(x1_norm)
    x2_norm = x2.pow(2).sum(-1, True)
    x2_pad = torch.ones_like(x2_norm)
    x1_ = torch.cat([x1.mul(-2), x1_norm, x1_pad], -1)
    x2_ = torch.cat([x2, x2_pad, x2_norm], -1)
    result = torch.matmul(x1_, x2_.transpose(-2, -1)).clamp_min(0)
    return torch.sqrt(result.clamp_min(0))
    return result


emb1, emb2, cdist_grad = torch.load("cdist_grad.pt")
emb1 = emb1.cpu()
emb2 = emb2.cpu()
cdist_grad = cdist_grad.cpu()
emb1.retain_grad()
d = cloned_cdist(emb1, emb2)
# d = torch.cdist(emb1, emb2)
d.backward(cdist_grad)
print(d[0, 17])
print(emb1.grad[0, 17])
```

**Comment by ngimel** [comment]
We could either clamp to some eps value rather than zero (performant but less accurate) or use a workaround that is currently used to return subgradients for norm https://github.com/pytorch/pytorch/blob/a5af478f29efbb25eb7d16897c355b617576571f/tools/autograd/templates/Functions.cpp#L115-L116, which is less performant because one has to find and mask zero values.

**Comment by emcastillo** [comment]
I just found that in the original cuda kernel
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/DistanceKernel.cu#L61

the gradient is 0 if the input is 0.
is it possible to add such condition in `derivatives.yaml`?

**Comment by ngimel** [comment]
@Baranowski #37337 already contains a fix.

**Comment by bauerbach95** [comment]
@albanD Hi there. I am running into this same issue when trying to run a backward pass after using cdist to compute the pairwise euclidean distances among samples.

Forgive me if this is obvious...but how can I get your changes for the updated PyTorch cdist function? Thanks for your help!

**Comment by ngimel** [comment]
You can get pytorch nightly builds, use the commands provided on pytorch.org

**Comment by bauerbach95** [comment]
Thanks @ngimel !

**Comment by KevinMusgrave** [comment]
Was this supposed to be fixed in 1.5.1? Here's some code I ran on google colab:
Code:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
print(torch.__version__)
```
Output:
```
1.5.1+cu101
```


Code:
```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(512, 128)

    def forward(self, x):
        x = self.fc1(x)
        return x

model = Net().cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=0.000001)
for i in range(10):
    x = torch.randn(32, 512, requires_grad=True).cuda()
    output = model(x)

    loss = torch.cdist(output,output)
    print(loss.size())
    loss = torch.mean(loss)
    print(loss)
    loss.backward()
    optimizer.step()
```
Output:
```
torch.Size([32, 32])
tensor(8.7667, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
torch.Size([32, 32])
tensor(nan, device='cuda:0', grad_fn=<MeanBackward0>)
```

**Comment by brianhhu** [comment]
I think this has been fixed in the latest stable version of Pytorch (1.6). I remember trying after 1.5 and 1.5.1, but cdist still produced NaN gradients. Hope this helps!

**Comment by KevinMusgrave** [comment]
@brianhhu Thanks, I'll try 1.6
