### ISSUE TITLE
Sampled Softmax / Log-Uniform Sampler - Google Billion Word Language Model

### ISSUE THREAD

**Issue by rdspring1** [pytorch/pytorch#3718]
I implemented the [Sampled Softmax](https://www.tensorflow.org/api_docs/python/tf/nn/sampled_softmax_loss) and [Log-Uniform Sampler](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/log-uniform-candidate-sampler) ops for PyTorch.

I tested my implementation on the Google Billion Word dataset.
52.68 Perplexity after 10 training epochs on a 4-layer, 512-unit LSTM Language Model
https://github.com/rdspring1/PyTorch_LM

The [Multinomial Sampler](http://pytorch.org/docs/master/torch.html?highlight=multinomial#torch.multinomial) without replacement was extremely slow, so I prototyped the Log-Uniform Sampler in Cython.

Is this something worth adding to PyTorch?

**Comment by soumith** [comment]
this seems legit, @fritzo should we add this in?

**Comment by fritzo** [comment]
@soumith I haven't heard of [candidate sampling](https://www.tensorflow.org/extras/candidate_sampling.pdf) but it seems useful. It seems like these sampling ops would live outside of torch.distributions.

**Comment by rdspring1** [comment]
The Log Uniform sampler is similar to the torch.distributions.Multinomial op, so it could fall inside torch.distributions.

The Sampled Softmax loss function is the standard for training large-scale language models. Currently, only TensorFlow and Torch support training those models.

I also added unit tests, derived from TensorFlow's implementation, to check the ops.

**Comment by magic282** [comment]
Hi @rdspring1 , I have read your LM code and it is really great job. I am considering to use pytorch [multinominal](http://pytorch.org/docs/master/torch.html?highlight=multinomial#torch.multinomial) to implement to avoid the cython build.

Do you think I can just change the code in your repo https://github.com/rdspring1/PyTorch_GBW_LM/blob/master/lm/model.py#L29
to `torch.multinomial(weights, nsample)`, where weights is a uniform distribution (1/vocab_size) with size (batch, vocab_size) and nsample is the `hps.num_sampled`.

Do you think this is a correct implementation?

Thank you.

**Comment by rdspring1** [comment]
Yes, you can use torch.multinomial to sample from a uniform distribution.

However, since the multinomial function is for general purpose sampling, it is slower for standard distributions, such as "uniform" or "log-uniform".

**Comment by magic282** [comment]
@rdspring1 I see. I just tried your SampledSoftmax class code with
```python
self.sampler = SampledSoftmax(self.num_classes, 8000, 1024, False)
```
and
```python
forward_logits, forward_new_targets = self.sampler(forward_hidden, forward_output_tokens)
```
`forward_hidden` is the hidden of RNN with shape `(batch, seq_len, dim)`
`forward_output_tokens` is the target with shape (batch, seq_len)`
When executing this line
```python
sample_values = self.sampler.sample(self.nsampled, labels.data.cpu().numpy())
```
I got the following error:
```
  File "/workspace/tmp/elmo/allennlp/allennlp/models/xelmo.py", line 43, in forward
    sample_values = self.sampler.sample(self.nsampled, labels.data.cpu().numpy())
  File "log_uniform.pyx", line 32, in log_uniform.LogUniformSampler.sample
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_long
TypeError: an integer is required
```
Could you please give some hints about this error? I tried to change it to `labels.data.int().cpu().numpy()` but the error is the same.
Thanks.

**Comment by rdspring1** [comment]
First, I'd try running the log_uniform_sampler_utest. Ignore "test_avoid" but "test_unique" should pass.
Then, I would print the labels during the failure case to confirm if they're integers.

**Comment by yinhanliu** [comment]
Hi, I was wondering if this negative sampling is already implemented in pytorch or not yet? Thanks!

**Comment by hveigz** [comment]
Hi, is negative sampling / something like tensorflows' sampled_softmax_loss implemented in pytorch yet ? Thanks!

**Comment by TimidLion** [comment]
Hi, I also wondering if this is implemented in pytorch yet! I'll wait for the answer. Thanks!

**Comment by Santosh-Gupta** [comment]
update?

**Comment by Wronskia** [comment]
@magic282 , I think the implementation of @rdspring1 is assuming a multiclass format.

**Comment by mruberry** [comment]
Since this is an older issue conflating two feature requests, I filed two separate new issues tracking each proposal: 

https://github.com/pytorch/pytorch/issues/38184 for the log uniform sampler
https://github.com/pytorch/pytorch/issues/38185 for the sampled softmax loss
