### ISSUE TITLE
Do you have any documents to compile libotch using source code?

### ISSUE THREAD

**Issue by huang229** [pytorch/pytorch#37203]
Do you have any documents to compile libotch using source code? Thank you!!!

**Comment by deepali-c** [comment]
Building PyTorch from source builds libtorch.so too. 
Document - https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.

**Comment by huang229** [comment]
Thank you!!!@deepali-c @izdeby
