### ISSUE TITLE
Pytorch upgrade 1.4 -> 1.5 broken on Windows

### ISSUE THREAD

**Issue by daniel-p-gonzalez** [pytorch/pytorch#37209]
## Issue description

Just upgraded to 1.5 on Windows 10 using conda, and pytorch fails to import with the following error:
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "(user dir)\Anaconda3\envs\cenv\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "(user dir)\Anaconda3\envs\cenv\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

## Code example

import torch

## System Info

collect_env.py fails due to import torch failure above.

- Installed PyTorch via conda, from 1.4 with cudatoolkit=10.1, to 1.5 with cudatoolkit=10.2, with the following command:
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
- Windows 10
- Python version: 3.6.9
- CUDA/cuDNN version: 10.2

cc @peterjc123 @nbcsm @guyang3532

**Comment by FBMachine** [comment]
Note: not sure, but may be related to https://github.com/pytorch/pytorch/pull/33856

**Comment by peterjc123** [comment]
Please provide the logs using Process Monitor and make sure you are not using a CUDA variant of PyTorch on a PC without NVidia GPU.

**Comment by FBMachine** [comment]
I train models daily on an NVidia GPU - as I said this is the result of upgrading from 1.4 (with cudatoolkit=10.1), to 1.5 (with cudatoolkit=10.2).

**Comment by peterjc123** [comment]
Please provide the logs using Process Monitor to help locating the problem.

**Comment by FBMachine** [comment]
It appears that \Anaconda3\envs\cenv\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll is missing from the installation.

**Comment by peterjc123** [comment]
@FBMachine Let me  check.

**Comment by peterjc123** [comment]
![image](https://user-images.githubusercontent.com/9998726/80207062-0eb5cf80-8660-11ea-8243-16afbcb818a3.png)
It is in the package.

**Comment by FBMachine** [comment]
You're right, that just happened to be the dll it was loading when the error was thrown - it seems to be from a deeper dependency. I managed to get a more specific error:

"The procedure entry point cudnnSetCTCLossDescriptorEx could not be located in the dynamic link library (user dir)\Anaconda3\envs\cenv\Lib\site-packages\torch\lib\torch_cuda.dll"

To be clear, I've been training just fine on GPU using pytorch for the past year, up until I tried upgrading from 1.4 to 1.5 last night. So there is either a new dependency that is missing, or perhaps the install silently failed in some way.

**Comment by peterjc123** [comment]
It seems that you have a conflicting cudnn installed. Would you please try to remove it first?

**Comment by DongpingQ** [comment]
I am having the same problem. @FBMachine  May I ask if you have solved this? Thank you!

**Comment by peterjc123** [comment]
Currently the easiest fix is replace your local copy of `__init__.py` with [this one](https://gist.github.com/peterjc123/bcbf4418ff63d88e11313d308cf1b427) on Gist.

**Comment by DongpingQ** [comment]
Yeah, any attempt of using CUDA fails on my computer though CPU-only installation works. Good to know and thanks! @peterjc123

**Comment by ashwithadevasya** [comment]
Hey folks, I am facing the same issue! My environment set up - 
1. System with NVIDIA GeForce MX250
2. CUDA 10.2, added CUDNN binaries for 10.2 explicitly (Note: When installing CUDA Toolkit, I unchecked GeForce component, as it was failing when I followed standard installation)
3. Installed PyTorch with CUDA 10.2

Earlier, I was using PyTorch with CPU only option, but then I was getting the error ""Torch not compiled with CUDA enabled". So I installed PyTorch with CUDA.

@FBMachine How did you get around this?

@peterjc123 I tried overwriting __init__.py from the gist you shared, it prints error more explicitly - 
`File "F:\Softwares\anaconda\lib\site-packages\torch\__init__.py", line 103, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "F:\Softwares\anaconda\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.`

**Comment by peterjc123** [comment]
@ashwithadevasya Have you installed the GPU driver? Which package manager are you using?

**Comment by peterjc123** [comment]
@ashwithadevasya You can refer to this [doc](https://github.com/peterjc123/pytorch_dll_load_smoketests#how-to-contribute-or-report-issues) to get more details about the dll load failure.

**Comment by FBMachine** [comment]
Apologies for letting this issue just sit. I ended up fixing the problem, but then had a long unpleasant hospital stay shortly after this. I'll try to remember the process of fixing, but my memory is definitely hazy.

I remember having to remove all system installed versions of cuda and cudnn (simply changing environment variables did not work). I then updated my GPU drivers. Finally (I think), I uninstalled then reinstalled pytorch. I THINK this is all it took to get it working, and either every step was necessary, or certainly the latter steps since I tested after every attempted fix. Hope that helps.

**Comment by ashwithadevasya** [comment]
> @ashwithadevasya Have you installed the GPU driver? Which package manager are you using?

My GPU drivers are already upto date. I didn't do anything  special for this.

If I understood your question correctly, I am using anaconda as the package manager.

**Comment by ashwithadevasya** [comment]
There are 2 parts to this issue I am facing. Basically, I have been trying to run my code from PyCharm. Also, given, my anaconda installation path is not the default one.
1. All this while, I was creating the project interpreter as a **virtual env** with anaconda python as the base, marked inherit all the global packages though. In this case, I was running to this issue -`OSError: [WinError 126] The specified module could not be found`

2. When I executed `import torch` from the anaconda prompt, it didn't throw this error. 
Instead, I was getting `AssertionError: Torch not compiled with CUDA enabled`. To my surprise, when I run this command and install `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`,  and then I see this -
`>>> torch.has_cuda
False`

Below is package plan I see for the above installation - 
`## Package Plan ##

  environment location: F:\Softwares\anaconda

  added / updated specs:
    - cudatoolkit=10.2
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  pytorch            pytorch/win-64::pytorch-1.5.0-py3.7_cpu_0
  torchvision        pytorch/win-64::torchvision-0.6.0-py37_cpu`

I hope I am not deviating the main topic here!!

**Comment by ashwithadevasya** [comment]
> There are 2 parts to this issue I am facing. Basically, I have been trying to run my code from PyCharm. Also, given, my anaconda installation path is not the default one.
> 
> 1. All this while, I was creating the project interpreter as a **virtual env** with anaconda python as the base, marked inherit all the global packages though. In this case, I was running to this issue -`OSError: [WinError 126] The specified module could not be found`
> 2. When I executed `import torch` from the anaconda prompt, it didn't throw this error.
>    Instead, I was getting `AssertionError: Torch not compiled with CUDA enabled`. To my surprise, when I run this command and install `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`,  and then I see this -
> 
> ```
> >>> torch.has_cuda
> False
> ```
> 
> Below is package plan I see for the above installation -
> 
> ```
> 
>   environment location: F:\Softwares\anaconda
> 
>   added / updated specs:
>     - cudatoolkit=10.2
>     - pytorch
>     - torchvision
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
>   pytorch            pytorch/win-64::pytorch-1.5.0-py3.7_cpu_0
>   torchvision        pytorch/win-64::torchvision-0.6.0-py37_cpu
> ```
> 
> I hope I am not deviating the main topic here!!

I am closing my thread here and redirecting it to the community - [https://discuss.pytorch.org/t/pytorch-for-cuda-10-2/65524/35?u=ashwitha_d]

**Comment by peterjc123** [comment]
> 1. All this while, I was creating the project interpreter as a **virtual env** with anaconda python as the base, marked inherit all the global packages though. In this case, I was running to this issue -`OSError: [WinError 126] The specified module could not be found`

How did you create the virtual env? `conda create` or `venv`?

**Comment by peterjc123** [comment]
ashwithadevasya I created two issues for you. https://github.com/pytorch/pytorch/issues/39619 and https://github.com/pytorch/pytorch/issues/39620.

**Comment by ashwithadevasya** [comment]
> > 1. All this while, I was creating the project interpreter as a **virtual env** with anaconda python as the base, marked inherit all the global packages though. In this case, I was running to this issue -`OSError: [WinError 126] The specified module could not be found`
> 
> How did you create the virtual env? `conda create` or `venv`?

I did it directly on PyCharm, selected the option of creating a new interpreter of type venv

**Comment by peterjc123** [comment]
@ashwithadevasya Then it is using `venv`. Please see the newly-opened issue https://github.com/pytorch/pytorch/issues/39620 and the corresponding fix https://github.com/pytorch/pytorch/pull/39622.

**Comment by peterjc123** [comment]
@ashwithadevasya After some investigation, it seems a bit tricky to use virtualenv with conda if you inherit global packages because conda relies on its own implementation to activate the environment and it is not well handled by PyCharm. I think you should report a bug to PyCharm. Alternatively, you could use conda envs introduced [here](https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html).

**Comment by yles9056** [comment]
I encountered the same issue. I noticed that pytorch seems to conflict with opencv-python if opencv-python is compiled from source with CUDA support.

I'm using Windows 10 with CUDA 10.1. All my python packages are installed in a conda virtual environment with python 3.7.7.
First, I use `pip` to install `opencv-python==4.3.0` (no CUDA) and `torch==1.5.1+cu101` (CUDA 10.1) in a conda virtual environment.
```
conda create --name myenv python=3.7
pip install opencv-python
pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

I can import both of packages without any issue.
```python
import torch
import cv2
# Everything is working fine.
```

Then, I removed `opencv-python` and compile it from source with CUDA support. If I import `torch` **before** `cv2`, no error would occur.
```python
import torch
import cv2
# Everything is working fine.
```

But if I import `cv2` **first**, an error would occur.
```python
import cv2
import torch
# An error occurs:
# The procedure entry point cudnnSetCTCLossDescriptorEx could not be located in the dynamic link library <user dir>\Anaconda3\envs\<env name>\Lib\site-packages\torch\lib\torch_cuda.dll
```

**Comment by peterjc123** [comment]
@yles9056 It's a cudnn conflicit. Unluckily you may have to build either one from source to resolve this.

**Comment by yles9056** [comment]
> @yles9056 It's a cudnn conflict. Unluckily you may have to build either one from source using the same version of cudnn to resolve this.

Thank you. I'll give it a try and see if the issue will be resolved.

**Comment by kit1980** [comment]
Closing as long obsolete.
