### ISSUE TITLE
Should ATen elementSizeInBytes return an int64_t?

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#3721]
Currently it returns a size_t (the return type of sizeof), but this isn't really a first class ATen type, i.e. it is never exposed in Declarations.yaml.

Background: I tried to implement this as a native function but the jit generated uncompilable code:
`
torch/csrc/jit/generated/aten_dispatch.cpp:601:59: error: conversion from ‘std::size_t {aka long unsigned int}’ to ‘at::Scalar’ is ambiguous
       pack_list(outputs, at::elementSizeInBytes(inputs[0]));
`

Maybe better to just check that sizeof doesn't return something over the int64_t numeric limit and throw an exception if it does?

CC @zdevito @ezyang

**Comment by apaszke** [comment]
I don't think you even need the check. I doubt anyone has 2^63 bytes of RAM in their system, so having types this large is quite impractical :wink:

**Comment by gchanan** [comment]
Sure, I think on a recent C++ it should all be compile time anyway, so doesn't seem to hurt.

**Comment by zdevito** [comment]
> Should ATen elementSizeInBytes return an int64_t? 
Yes

**Comment by ezyang** [comment]
> I doubt anyone has 2^63 bytes of RAM in their system

With today's actual 64-bit hardware, it is literally impossible to address that much RAM, physics constraints notwithstanding.

https://github.com/zdevito/ATen/issues/171 seems related.

Did we ever write down our `int64_t` philosophy anywhere? It definitely feels like, when using 64-bit uniformly, the place it hurts the most is when you need to convert into `ssize_t`, and now compilers will give a warning unless you explicitly convert.

**Comment by ezyang** [comment]
Mooted by 80a7eac79ec59ace79b96368e7a0022614940ac2
