### ISSUE TITLE
Compiling release/1.5 broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by bmanga** [pytorch/pytorch#37217]
## 🐛 Bug

When building third_party/ideep/mkl-dnn, the compilation fails. Some of the errors are:
* ``` third_party/ideep/mkl-dnn/include/dnnl_config.h:81:2: #error "BOTH DNNL_CPU_RUNTIME and DNNL_GPU_RUNTIME must be defined"```
* ```third_party/ideep/mkl-dnn/src/common/dnnl_thread.hpp:115:12:  error: ‘DNNL_THR_SYNC’ was not declared in this scope ```
* ```third_party/ideep/mkl-dnn/src/common/dnnl_thread_parallel_nd.hpp:41:27: error: there are no arguments to ‘dnnl_get_max_threads’ that depend on a template parameter, so a declaration of ‘dnnl_get_max_threads’ must be available```

## To Reproduce

1. (in build directory) ```cmake .. -DBUILD_PYTHON=OFF```
2. ```cmake --build .```

## Environment
 - PyTorch Version (e.g., 1.0): branch release/1.5, @ commit 96f218d7dd5f9e2a8fe49f463bb28e6151fa1e83
 - OS (e.g., Linux): Ubuntu 18.04
 - CUDA/cuDNN version: 10.1

**Comment by bmanga** [comment]
@peterjc123 do you know what could cause this?

**Comment by peterjc123** [comment]
You may need to sync the submodules.
```bash
git submodule sync
git submodule update --init --recursive
```

**Comment by bmanga** [comment]
Thanks!
Seems like `git submodule update` wasn't enough... This is why I don't like submodules :(
