### ISSUE TITLE
commit 1592d6842cc8d4fabca35a6f9ac3117c34348e70 caused DLRM benchmark running with "--enable-profiling" crash

### ISSUE THREAD

**Issue by JianpingChen066** [pytorch/pytorch#37216]
## 🐛 Bug
The following check-in make DLRM benchmark running crashed with "--enable-profiling" crash

commit 1592d6842cc8d4fabca35a6f9ac3117c34348e70
Author: James Reed <jamesreed@fb.com>
Date:   Tue Apr 21 16:31:17 2020 -0700

    [resubmit] Move profiler to a dispatch wrapper (#36766)

    Summary:
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/36766

## To Reproduce

1. Download the DLRM from https://github.com/facebookresearch/dlrm
2. Modify the bench/dlrm_s_benchmark.sh to just run pytorch on cpu version, as
   cpu=1
   gpu=0
   pt=1
   c2=0
The cpu core number may also need to be modified according to the core number of one slot on your testing machine (see above command line as example)
3.  Run bench/dlrm_s_benchmark.sh, then it will crashed. If you disable the "--enable-profiling" in the scripts, it can run pass without crash

The error is like below:
```
numactl --physcpubind=0-23 -m 0 python dlrm_s_pytorch.py --mini-batch-size=2048 --num-batches=100 --data-generation=random --arch-mlp-bot=512-512-64 --arch-mlp-top=1024-1024-1024-1 --arch-sparse-feature-size=64 --arch-embedding-size=1000000-1000000-1000000-1000000-1000000-1000000-1000000-1000000 --num-indices-per-lookup=100 --arch-interaction-op=dot --numpy-rand-seed=727 --print-freq=100 --print-time --enable-profiling > model1_CPU_PT_Apr21-1631_24.log
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 934, in <module>
    E.backward()
  File "/home/.../anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/.../anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Unrecognized tensor type ID: Profile (dispatchKeyToBackend at ../c10/core/Backend.h:102)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x7fda71d45ebe in /home/.../anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
...
```

## Expected behavior

DLRM should run success with "--enable-profiling"

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
 - PyTorch Version (e.g., 1.0): Build from source code
 - Build command you used (if compiling from source): 
    python setup.py install
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:
    - OS: CentOS Linux 7 (Core)
    - GCC version: (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
    - CMake version: version 3.14.0

## Additional context

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.6.0a0+1592d68
[pip] torchviz==0.0.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                intel_166    intel
[conda] mkl-include               2019.0                    <pip>
[conda] mkl-include               2020.0                intel_166    intel
[conda] mkl-service               2.3.0                    py37_0    intel
[conda] mkl_fft                   1.0.15           py37ha68da19_3    intel
[conda] mkl_random                1.1.0            py37ha68da19_0    intel
[conda] numpy                     1.17.4           py37ha68da19_4    intel
[conda] numpy-base                1.17.4                   py37_4    intel
[conda] torch                     1.6.0a0+1592d68           <pip>
[conda] torchviz                  0.0.1                     <pip>

@VitalyFedyunin @ezyang please have a check on this. Thanks

**Comment by ezyang** [comment]
cc @ilia-cher, I think the diff you have in preparation will fix this

also cc @jamesr66a for visibility

**Comment by ilia-cher** [comment]
@ezyang I'm blocked on dispatcher side of things now because dispatcher now fails on mobile, we can land server-only fix but it this is not optimal

**Comment by ilia-cher** [comment]
originally seems to be caused by https://github.com/pytorch/pytorch/pull/36766

**Comment by ilia-cher** [comment]
(the fix https://github.com/pytorch/pytorch/pull/37292)

**Comment by ilia-cher** [comment]
actually "Unrecognized tensor type ID: Profile" should be fixed in https://github.com/pytorch/pytorch/pull/37194

**Comment by JianpingChen066** [comment]
yes, it fixed
