### ISSUE TITLE
Bad performance with python threads

### ISSUE THREAD

**Issue by SSS135** [pytorch/pytorch#37259]
## 🐛 Bug

concurrent.futures.ThreadPoolExecutor with max_workers=1 loads all CPU cores (24 cores / 100% load) when torch.zeros(64, 8, 2, 128) is used inside it's thread. If torch.zeros used with smaller size, like (16, 8, 2, 128), then there is no performance hit. Also this sometimes happens with torch.logsumexp, tensor indexing, tensor copying.
Edit: multiprocessing.dummy.Pool is also affected

## To Reproduce

Run this code:
```
import torch
torch.set_num_threads(1)
torch.set_num_interop_threads(1)
from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor(max_workers=1)

def train_async(data):
    with torch.no_grad():
        torch.zeros(64, 8, 2, 128)
            
while True:
    executor.submit(train_async, []).result()
```

## Expected behavior

Only single CPU core being utilized.

## Environment

```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Њ ©Єа®б®дв Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 442.19
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] numpydoc==0.9.1
[pip] ppo-pytorch==0.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h74a9793_0
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] numpy                     1.17.4           py37h4320e6b_0
[conda] numpy-base                1.17.4           py37hc3f5095_0
[conda] numpydoc                  0.9.1                      py_0
[conda] ppo-pytorch               0.1                       dev_0    <develop>
[conda] pytorch                   1.5.0           py3.7_cuda101_cudnn7_0    pytorch
[conda] pytorch-qrnn              0.2.1                    pypi_0    pypi
[conda] torchvision               0.6.0                py37_cu101    pytorch
```

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
cc @ilia-cher

**Comment by kshitij12345** [comment]
I have tried the sample and I do see that all cores are utilised as noted.

However with a small change of calling `train_async` directly only leads to 100% utilization of single core,

i.e. All cores seem to be utilized when `train_async` is called through the executor.
```
import torch
torch.set_num_threads(1)
torch.set_num_interop_threads(1)
from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor(max_workers=1)

def train_async(data):
    with torch.no_grad():
        torch.zeros(64, 8, 2, 128)
            
while True:
    train_async([])
```

**Comment by ngimel** [comment]
Setting high priority, looks like a bug

**Comment by peterbell10** [comment]
`torch.set_num_threads` calls `omp_set_num_threads` which I think writes to a thread-local variable internally. That thread-local isn't propagated when the `ThreadPoolExecutor` thread is created. 

A simple workaround is to move the `torch.set_num_threads` call into the body of `train_async`.

For a more general fix, `at::init_num_threads` needs to be called on each new thread. It's not clear where this call should go though

**Comment by ilia-cher** [comment]
If it's not documented enough, I can update the doc but, as you mentioned, because OpenMP's settings are thread local, we have to call at::init_num_threads at the moment a new thread is initialized

We do already call at::init_num_threads for many threads that PyTorch creates, so it's either so unaccounted case (bug) or just a separate user thread, in this case user needs to call at::init_num_threads in it

**Comment by peterbell10** [comment]
`at::init_num_threads` is not exposed to python so there's no way for the user to call it here.

**Comment by ilia-cher** [comment]
sg, let's add this as an api and update the docs accordingly, I can take this

**Comment by ilia-cher** [comment]
example where we already do this aten/src/ATen/PTThreadPool.h

**Comment by peterbell10** [comment]
Okay, I'll work on that as an alternative to #37461

**Comment by ilia-cher** [comment]
#37461 might be good too - we would still want to enable original settings if user uses ATen/Parallel API, it is just we can't do much when user creates a new thread themselves and then directly execute code that uses OpenMP
