### ISSUE TITLE
Variable methods which need to change before we combine Variable and Tensor

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#3726]
## missing Python magic
- [x] `__array__`
- [x] `__array_wrap__`
- [ ] `__getstate__`
- [x] `__invert__`
- [x] `__itruediv__`

## RNG
- [x] bernoulli_
- [x] uniform_
- [x] exponential_
- [x] cauchy_
- [x] normal_
- [x] random_

## Missing in ATen
- [x] clamp_
- [x] is_sparse
- [x] resize_
- [x] resize_as_
- [x] renorm_
- [x] _sparse_mask
- [x] _new_with_metadata_file (deleted)
- [x] _write_metadata (unused, deleted)

## storage
- [x] storage
- [x] storage_type
- [x] share_memory_
- [x] is_pinned
- [x] is_shared
- [x] pin_memory

## misc
- [x] numpy
- [x] new
- [x] tolist
- [ ] `__str__`
- [x] _cdata

## type conversions
- [x] type
- [x] cuda
- [x] cpu
- [x] float/double/half/int/etc.
- [x] `__float__`/`__long__`/`__int__` (use toCFloat, etc.)

## python specific
- [x] apply_
- [x] map2_
- [x] map_

**Comment by gchanan** [comment]
This is missing the remaining fallthrough methods.

**Comment by gchanan** [comment]
This also doesn't include parameter differences, e.g.:
>>> a=Variable(torch.randn(2).cuda()).type()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type() missing 1 required positional argument: 't'
>>> torch.randn(2).cuda().type()

**Comment by colesbury** [comment]
We have additional work to do before we can combined Variable and Tensor, but all these methods are implemented.
