### ISSUE TITLE
intermittent failures of "test_remote_script_module"

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#37261]
Two instances from this week:
* https://app.circleci.com/pipelines/github/pytorch/pytorch/157232/workflows/4260f754-067c-45ab-86a1-69ae89e5782c/jobs/5187452/tests
* https://app.circleci.com/pipelines/github/pytorch/pytorch/158816/workflows/63d3cc14-96c4-45ab-81b6-a6cd98d27c21/jobs/5221734/tests

Error message:
```

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 174, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 278, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 330, in _check_return_codes
    "Expected zero exit code but got {}".format(first_process.exitcode)
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 958, in assertEqual
    super().assertLessEqual(abs(x - y), atol, message)
AssertionError: 1 not less than or equal to 1e-05 : Expected zero exit code but got 1
```

cc @ezyang @gchanan @zou3519 @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by zhaojuanmao** [comment]
test_remote_script_module (__main__.JitRpcTestWithSpawn) ... [E request_callback_impl.cpp:94] Received error while processing request type 0: 
Apr 22 20:03:43 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':
Apr 22 20:03:43 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface
Apr 22 20:03:43 Process process 0:
Apr 22 20:03:43 Traceback (most recent call last):
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Apr 22 20:03:43     self.run()
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Apr 22 20:03:43     self._target(*self._args, **self._kwargs)
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 236, in _run
Apr 22 20:03:43     getattr(self, test_name)()
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 80, in new_test_method
Apr 22 20:03:43     return_value = old_test_method(self, *arg, **kwargs)
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 785, in test_remote_script_module
Apr 22 20:03:43     args=(remote_ref, torch.ones(self.rank)),
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Apr 22 20:03:43     return func(*args, **kwargs)
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 592, in rpc_sync
Apr 22 20:03:43     return fut.wait()
Apr 22 20:03:43 RuntimeError: Error on Node 1: 
Apr 22 20:03:43 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':
Apr 22 20:03:43 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface
Apr 22 20:03:43 [E request_callback_impl.cpp:94] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
Apr 22 20:03:43 Traceback of TorchScript (most recent call last):
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 658, in run_ref_script_module
Apr 22 20:03:43 def run_ref_script_module(ref_script_module, t):
Apr 22 20:03:43     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
Apr 22 20:03:43     module = ref_script_module.to_here()
Apr 22 20:03:43              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Apr 22 20:03:43     return module.forward() + t
Apr 22 20:03:43 RuntimeError: User RRef with RRefId=GloballyUniqueId(1, 0) and ForkId=GloballyUniqueId(1, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker2, to user, worker1.
Apr 22 20:03:43 
Apr 22 20:03:43 [E request_callback_impl.cpp:94] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
Apr 22 20:03:43 Traceback of TorchScript (most recent call last):
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 658, in bailout
Apr 22 20:03:43 def run_ref_script_module(ref_script_module, t):
Apr 22 20:03:43     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
Apr 22 20:03:43     module = ref_script_module.to_here()
Apr 22 20:03:43              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Apr 22 20:03:43     return module.forward() + t
Apr 22 20:03:43 RuntimeError: User RRef with RRefId=GloballyUniqueId(3, 0) and ForkId=GloballyUniqueId(3, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker0, to user, worker3.
Apr 22 20:03:43 
Apr 22 20:03:43 [E request_callback_impl.cpp:94] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
Apr 22 20:03:43 Traceback of TorchScript (most recent call last):
Apr 22 20:03:43   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 658, in bailout
Apr 22 20:03:43 def run_ref_script_module(ref_script_module, t):
Apr 22 20:03:43     # type: (RRef[MyModuleInterface], Tensor) -> Tensor
Apr 22 20:03:43     module = ref_script_module.to_here()
Apr 22 20:03:43              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
Apr 22 20:03:43     return module.forward() + t
Apr 22 20:03:43 RuntimeError: User RRef with RRefId=GloballyUniqueId(2, 0) and ForkId=GloballyUniqueId(2, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker3, to user, worker2.
Apr 22 20:03:43
