### ISSUE TITLE
Torch norm error on gpu tensors

### ISSUE THREAD

**Issue by fgvbrt** [pytorch/pytorch#37272]
## 🐛 Bug

`torch.norm` throws error, when I use it on gpu tensor with `dim` argument and `keep_dims=True` 

## To Reproduce

```
import torch
a = torch.randn(1, 4, 4).cuda()

# throws error (see below)
torch.norm(a, dim=[1, 2], keepdim=True)

# works
torch.norm(a.cpu(), dim=[1, 2], keepdim=True)
```
error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/functional.py", line 755, in norm
    return torch._C._VariableFunctions.frobenius_norm(input, dim, keepdim=keepdim)
RuntimeError: Could not run 'aten::conj.out' with arguments from the 'CUDATensorId' backend. 'aten::conj.out' is only available for these backends: [CPUTensorId, VariableTensorId].
```

## Expected behavior
I expect to get norm of tensor as in case with cpu tensor

## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.11.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 418.87.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

**Comment by ngimel** [comment]
This has been fixed on master and in 1.5

**Comment by vadimkantorov** [comment]
offtopic: why complex conjugate was being called for non-complex tensor? https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/LinearAlgebra.cpp#L556

Also I wonder if `sqrt((self*self),sum(dim)` has again numerical instability / gradient blowup at 0 of sqrt and no eps used

**Comment by ngimel** [comment]
Calling conjugate was a bug that was fixed. norm_backward has special handling for zero norms https://github.com/pytorch/pytorch/blob/a5af478f29efbb25eb7d16897c355b617576571f/tools/autograd/templates/Functions.cpp#L115-L116

**Comment by vadimkantorov** [comment]
@ngimel Yes, but not the multidim inline formula. I filed a new issue for it: https://github.com/pytorch/pytorch/issues/37323

**Comment by vadimkantorov** [comment]
@ngimel You are right, it's supposed to call into `norm_backward` even in `IntArray dim` version, but somehow it doesn't work, as evidenced in https://github.com/pytorch/pytorch/issues/37323
