### ISSUE TITLE
Broadcasting does not work for Quantization aware training with multiple GPUs

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#37270]
Repro code and error info are at: 
https://discuss.pytorch.org/t/quantization-awareness-training-multi-gpu-suport/66106

Snippet of error at:
Traceback (most recent call last):
File “train_quantization.py”, line 258, in
main(args)
File “train_quantization.py”, line 77, in main
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.gpu])
File “xxx/.conda/envs/pytorch1.3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py”, line 298, in init
self.broadcast_bucket_size)
File “xxx/.conda/envs/pytorch1.3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py”, line 480, in _distributed_broadcast_coalesced
dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
TypeError: _broadcast_coalesced(): incompatible function arguments. The following argument types are supported:
1. (process_group: torch.distributed.ProcessGroup, tensors: List[at::Tensor], buffer_size: int) -> None

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x7f943f78dd18>, [tensor([[[[ 1.3185e-02, -4.3213e-03, 1.4823e-02],
…

Note that problem is present in pytorch 1.5

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
https://github.com/pytorch/vision/pull/2191 updates the tutorial to work better with QAT+DDP.  There is still work to do in verifying BN correctness, which will be in a separate PR.

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/38587, https://github.com/pytorch/pytorch/pull/39031, https://github.com/pytorch/pytorch/pull/38368, https://github.com/pytorch/pytorch/pull/38478 fixed this issue.
