### ISSUE TITLE
USE_MKLDNN=1 is must for cross compiling on x86 for arm rpi ?

### ISSUE THREAD

**Issue by aaripakaprashad** [pytorch/pytorch#37298]
want to know usecase of USE_MKLDNN 

console log:
--   USE_MKLDNN            : OFF
disabling MKLDNN because USE_MKLDNN is not set

console log saying USE_MKLDNN is OFF.

- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.8.2
--   CMake command         : /home/prashad/install_durga/sysroots/x86_64-rdksdk-linux/usr/bin/cmake
--   System                : Linux
--   C++ compiler          : /home/prashad/install_durga/sysroots/x86_64-rdksdk-linux/usr/bin/arm-rdk-linux-gnueabi/arm-rdk-linux-gnueabi-g++
--   C++ compiler id       : GNU
--   C++ compiler version  : 6.4.0
--   BLAS                  : MKL

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.
