### ISSUE TITLE
I got a oserror while importing torch after installing pytorch.

### ISSUE THREAD

**Issue by Black-sodiq** [pytorch/pytorch#37317]
![20200426_114542](https://user-images.githubusercontent.com/47804704/80305763-d379e480-87b6-11ea-83b3-672a86e25195.jpg)
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
- OS: windows 10
- PyTorch version: 1.5
- Python version:3.6.8
- CUDA/cuDNN version:10.2
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by peterjc123** [comment]
Are you using a CUDA variant of PyTorch on a PC without GPU? If yes, then please install the CPU-only version instead.

**Comment by izdeby** [comment]
@Black-sodiq, could you, please, provide more info on how to reproduce the issue?
