### ISSUE TITLE
Deprecation warnings appear inconsistently

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#37315]
Today in PyTorch our deprecation warnings sometimes use the TORCH_WARN macro and other times the TORCH_WARN_ONCE macro, creating inconsistent behavior. This issue is to discuss what behavior deprecation warnings should have. Two suggestions are:

- They should always warn once. Users complain of excessive warnings and they can spam logs. 
- They should always warn. Ensuring users see deprecation warnings is important, and users should address deprecated functionality to silence the warnings.

Although there may be reasonable schemes that sometimes warn and other times warn once.

The issue that prompted this discussion is https://github.com/pytorch/pytorch/issues/37065, which provides additional context on the user experience. 

cc @ngimel, @ilia-cher, @dzhulgakov, @gchanan

**Comment by dzhulgakov** [comment]
Here are more reasonable compromises:
* TORCH_WARN_ONCE_IN_A_WHILE / TORCH_WARN_EVERY_MS - produce warning only every X ms or ever X minutes
* Have some notion of "scope" for warnings. For example, log only once but for each JIT execution context. I'm mostly concerned about multi-tenant inference servers where warn_once can mask some errors from other models

we should probably go with time-based approach as a simple compromise

**Comment by gchanan** [comment]
The other nice thing about "once in a while" or "every ms" is that you can provide more context, e.g. you can say something like "suppressed similar 576 warnings since the last warning."  Also having some toggles like always warn, setting the frequency yourself seems useful.

**Comment by mruberry** [comment]
It seems like we have a solid idea. Given how there's engineer confusion about which type of warnings to use, too, what about renaming our warnings so that:

WARN -> warns every X minutes
WARN_ALWAYS -> yells at you every time

Especially since WARN_ONCE will no longer be an accurate name. The guidance on when to WARN_ALWAYS can be for situations where the user may lose data or get incorrect results. For example, converting a complex tensor to a float tensor discards the imaginary part, and we probably want to warn every time that occurs. Warnings about dangers of tracing conditionals, too, would be something we'd always want to warn about.

**Comment by mruberry** [comment]
This issue has been addressed with updates to PyTorch's Github Wiki here: https://github.com/pytorch/pytorch/wiki/Developer-FAQ#when-should-i-torch_warn-vs-torch_warn_once
