### ISSUE TITLE
torch.onnx.symbolic_opset10._thnn_fused_gru_cell does not exist

### ISSUE THREAD

**Issue by BridgetteSong** [pytorch/pytorch#37318]
when i try to export torch onnx model ,i got the this error.
UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable lenght with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")
/ssd4/exec/yins/tools/anaconda/envs/pytorch/lib/python3.6/site-packages/torch/onnx/utils.py:617: UserWarning: ONNX export failed on ATen operator _thnn_fused_gru_cell because **torch.onnx.symbolic_opset10._thnn_fused_gru_cell does not exist.**

someone solved the question?

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.
