### ISSUE TITLE
torch.cuda.is_available() get false on cuda10

### ISSUE THREAD

**Issue by WenmuZhou** [pytorch/pytorch#37320]
install command is pip3 install torch
outptu of python -m torch.utils.collect_env is
```sh
PyTorch version 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

Os: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0： Tesla P100-PCIE-16GB
GPU 1： Tesla P100-PCIE-16GB
GPU 2： Tesla P100-PCIE-16GB
GPU 3： Tesla P100-PCIE-16GB

Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Version of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ethman** [comment]
+1 

Also pip installed: pip -U install pytorch torchvision
Output of python -m torch.utils.collect_env:

    $ python -m torch.utils.collect_env
    Collecting environment information...
    PyTorch version: 1.5.0
    Is debug build: No
    CUDA used to build PyTorch: 10.2
    
    OS: Ubuntu 18.04.2 LTS
    GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    CMake version: version 3.10.2
    
    Python version: 3.8
    Is CUDA available: No
    CUDA runtime version: Could not collect
    GPU models and configuration: 
    GPU 0: Tesla V100-PCIE-16GB
    GPU 1: Tesla V100-PCIE-16GB
    GPU 2: Tesla V100-PCIE-16GB
    GPU 3: Tesla V100-PCIE-16GB
    GPU 4: Tesla V100-PCIE-16GB
    GPU 5: Tesla V100-PCIE-16GB
    GPU 6: Tesla V100-PCIE-16GB
    GPU 7: Tesla V100-PCIE-16GB
    
    Nvidia driver version: 418.87.00
    cuDNN version: Probably one of the following:
    /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
    /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
    /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
    
    Versions of relevant libraries:
    [pip3] numpy==1.17.2
    [pip3] torch==1.2.0
    pip3] torchvision==0.4.0
    [conda] gpytorch                  1.1.1                    pypi_0    pypi
    [conda] pytorch-ignite            0.3.0                    pypi_0    pypi
    [conda] torch                     1.5.0                    pypi_0    pypi
    [conda] torchvision               0.6.0                    pypi_0    pypi

**Comment by ptrblck** [comment]
@WenmuZhou @ethman 
Your drivers seem to be too old for CUDA10.2.
Based on [this table](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver) CUDA10.2.89 needs >=440.33, while yours is 410.104 and 418.87, respectively.

Could you update the drivers and reinstall the binaries, please?

I just installed them in a new environment and can successfully run PyTorch on the GPU.

**Comment by WenmuZhou** [comment]
Sorry, my server is inconvenient to update the driver. The torch1.4 I downloaded on this page （https://download.pytorch.org/whl/cu100/torch_stable.html） is available. When will this page be able to update torch1.5?

**Comment by ngimel** [comment]
Removing high priority. 1.5 pytorch version is available for download, however, it does not support cuda 10 (10.1 and 10.2 only)

**Comment by sbelharbi** [comment]
@ngimel 
> Removing high priority. 1.5 pytorch version is available for download, however, it does not support cuda 10 (10.1 and 10.2 only)

is this information mentioned somewhere? i was looking for any indication about this in the [release](https://github.com/pytorch/pytorch/releases/tag/v1.5.0) page, and there is none. i just installed pytorch 1.5 using `pip install torch` on a gpu device with cuda 10.0 and pytorch did not detect the gpu. i was suspecting to run to this issue since the pytorch [page](https://pytorch.org/) points to cuda 10.2 to install the latest version.

if pytorch 1.5 supports only cuda 10.1/2, it would be helpful to mention it in the release page or in the doc. i was trying to upgrade from pytorch 1.4 until i run into this thread.
thanks a lot.

**Comment by i-chaochen** [comment]
Extraclly the same issue here.

```
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
```

I tried pytorch 1.4 and 1.5 all torch.cuda.is_available() return False


Any way to fix it except upgrade Driver Version?
