### ISSUE TITLE
how to covert libtorch model to onnx model in libtorch1.5

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#37341]
how to convert libtorch model to onnx model in libtorch1.5 .      how to convert libtorch model to tensorrt model in libtorch ？

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by mrshenli** [comment]
Hey @laizewei, could you please use the [forum](https://discuss.pytorch.org/) for questions? I am closing this issue for now. Please feel free to open another issue if this turns out to be a bug report or feature request. Thanks!
