### ISSUE TITLE
Unexpected result on c10::ArrayRef

### ISSUE THREAD

**Issue by zsef123** [pytorch/pytorch#37346]
## 🐛 Bug
Trash values are assign on `ArrayRef` when using initializer_list on **msvc**(Release, /O2)

Codes
```
int main()
{
        uint32_t x = 64;
	c10::ArrayRef<int64_t> a({64, 64, 64, 64});
	std::cout << "a : " << a << std::endl;
	return 0;
}
```

Results
```
a : [834242869776, 4, 140734498917936, 0]
```

## Expected behavior

```
a : [64, 64, 64, 64]
```
( working on gcc ) 

## Environment

OS: Microsoft Windows 10 Pro
Compiler : Microsoft Visual C++ 2019
Flags : O2  (actually the problem happens on /Og)

## Additional context

I think, when msvc optimzation codes, compiler have removed the temporary initializer_list before passed on constructor in this line `c10::ArrayRef<int64_t> a({64, 64, 64, 64});` 

So if under code is working fine
```
int main()
{
        uint32_t x = 64;
        std::initializer_list<int64_t> y = {64, 64, 64, 64};
	c10::ArrayRef<int64_t> a(y);
	std::cout << "a : " << a << std::endl;
	return 0;
}
```

Is can prevent on code level?

**Comment by ezyang** [comment]
Yeah, this is user error. Unfortunately it's not so easy to get a compiler warning in this situation; it's a general problem with view types in C++. Hopefully the "Ref" is enough to tell you that there is a view going on.
