### ISSUE TITLE
torch_onnx_export crash

### ISSUE THREAD

**Issue by wguo1983** [pytorch/pytorch#3736]
i want to convert the example "fast_neural_style" trained model to caffe2 used torch.onnx, then got the error as follows， anyone can help me fix this?
thanks...........

File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 75, in export
    _export(model, args, f, export_params, verbose, training)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 122, in _export
    _optimize_trace(trace)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 81, in _optimize_trace
    torch._C._jit_pass_onnx(trace)
RuntimeError: untraced buffer

**Comment by ezyang** [comment]
You need a commit of HEAD after this PR: https://github.com/pytorch/pytorch/pull/3691

**Comment by wguo1983** [comment]
@ezyang it doesn't work for me, got the same error, and the InstanceNorm is used in fast-neural-style.

**Comment by wguo1983** [comment]
您好，这个问题能帮我再看看吗

发自我的 iPhone

**Comment by ezyang** [comment]
I recently rewrote how the export works for batchnorm in HEAD. Does fast-neural-style still fail?

**Comment by jackyko1991** [comment]
I also have this error in my onnx exportm

my code:
```
import torch
from torch import nn
import torch.onnx
import vnet
import onnx
import onnx_caffe2.backend
from torch.autograd import Variable
import os
import torch.backends.cudnn as cudnn

def pause():
    programPause = raw_input("Press the <ENTER> key to continue...")

# create the network model
gpus = [0,1]
torch_model = vnet.VNet(elu=False, nll=True)

# load trained model weights
snapshot_path = '/home/jacky/disk0/projects/vnet-data-brain/snapshot/snapshot_975.pth.tar'
batch_size = 1    # just a random number
cudnn.enabled = False

# Initialize model with the pretrained weights
map_location = lambda storage, loc: storage
if torch.cuda.is_available():
    map_location = None

snapshot = torch.load(snapshot_path, map_location=map_location)
state_dict = snapshot['state_dict']

# In state dict keys there is an extra word inserted by model parallel: "module.". We remove it here.
from collections import OrderedDict
new_state_dict = OrderedDict()

for k, v in state_dict.items():
  if k[0:6] == 'module':
    name = k[7:] # remove `module.`
  else:
    name = k
  new_state_dict[name] = v

print "load state dict"

torch_model.load_state_dict(new_state_dict)
torch_model = torch_model.cpu()

print "finish loading model"

# set the train mode to false since we will only run the forward pass.
torch_model.train(False)

# Input to the model
x = Variable(torch.randn(batch_size, 1, 128, 128, 128).float(), requires_grad=True)

# Export the model
onnx_export_path = "/home/jacky/disk0/projects/vnet-data-brain/onnx/vnet_ventricle.onnx"
if not os.path.isdir(os.path.dirname(onnx_export_path)):
	os.mkdir(os.path.dirname(onnx_export_path))

torch_out = torch.onnx._export(torch_model,             # model being run
                               x,                       # model input (or a tuple for multiple inputs)
                               onnx_export_path,        # where to save the model (can be a file or file-like object)
                               export_params=True)      # store the trained parameter weights inside the model file     
```

**Comment by pradeephike** [comment]
I am also facing the same error. @wguo1983 @ezyang @jackyko1991 did you find any solution for the same? I am trying to convert the fast-neural-style model into caffe2.

**Comment by 00hello** [comment]
@pradeephike Hey. Experiencing the same problem. Did you ever find a solution?

**Comment by pradeephike** [comment]
@00hello I skipped this approach and went ahead with training the network on tensor flow and directly copied the weights for caffe2 net. The approach worked fine for me and I was able to get a caffe2 model for running on the client side for style transfer.

Apart from that you can also look into the latest branch https://github.com/pytorch/examples/tree/master/fast_neural_style as the community has updated the code with onnx conversion. Although I was facing some problem in it but the best part was onnx export was successful with the latest commit.

**Comment by 00hello** [comment]
@pradeephike  Thanks for the advice. Hopefully pytorch 1.0 solves these issues

**Comment by wguo1983** [comment]
@pradeephike @00hello I used batchnorm instead of instancenorm, and set the training status to be True. It works for me.

**Comment by pradeephike** [comment]
@wguo1983 Thank you for the solution. Much appreciated!! I will give it a try on my side as well.

**Comment by ezyang** [comment]
Looks like this is fixed.
