### ISSUE TITLE
.sum() not return ideal result?

### ISSUE THREAD

**Issue by tomahawklin** [pytorch/pytorch#3738]
Hey I have this problem when I want to just get the sum of a tensor.

I have a 1d tensor with entries being either 0 or 1 (mostly 0).

`>>>diff`
`Variable containing:
 0
 0
 0
⋮ 
 0
 0
 0
[torch.cuda.ByteTensor of size 86945 (GPU 0)]`  

If I do torch.sum(diff) or diff.sum(), it gives me 
`>>> torch.sum(diff)`
`Variable containing:
 40
[torch.cuda.ByteTensor of size 1 (GPU 0)]`

However, with a naive approach:
`>>> for i in diff:`
    `...         ssum += i.data[0]`
This gives me ssum = 552

I transform the diff tensor to a list and calculate sum of that list, it does return 552, so what's going on with the torch.sum() function?

**Comment by gchanan** [comment]
it's probably overflowing your ByteTensor, try converting it to a larger type and doing the sum on that.
