### ISSUE TITLE
PyTorch doesn't construct bool tensors from non-bool values correctly

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#37398]
```
vals = (-.3, 0, .3, 1, 3/7)
t = torch.tensor(vals, dtype=torch.bool)
print(t)
a = np.array(vals, dtype=np.bool)
print(a)
```

produces 

```
tensor([False, False, False,  True, False])
[True False  True  True  True]
```

PyTorch's behavior is inconsistent with NumPy, Python and C++. 

cc @mruberry @ezyang @SsnL @gchanan

**Comment by chengjinfang1216** [comment]
@mruberry, I'm a newbie of pytorch, and I'd like to work on this.

**Comment by mruberry** [comment]
Hey @chengjinfang1216! Welcome to the community. It'd be great to get a PR fixing this. The Contribution Guide (https://pytorch.org/docs/stable/community/contribution_guide.html) might be helpful, too, if you haven't read it.

**Comment by chengjinfang1216** [comment]
@mruberry Thank you for your kind reply. I have fixed this issue locally and will open a pull request later.

**Comment by mruberry** [comment]
This issue was fixed by the linked PR.
