### ISSUE TITLE
how can i obtian the value of two-dimensional matrix from tensor in libtorch of C++ API?

### ISSUE THREAD

**Issue by MrCrazyCrab** [pytorch/pytorch#37401]
i use libtorch to do inference, and i got a two-dimensional tensor, but how can i obatian the value, or how can i transform the tensor in C++ to  a array?

**Comment by mrshenli** [comment]
Say `x` is the 2d tensor, one way is

```c++
x[i][j].item().to<int64_t>()
```

Or you can directly get the data pointer and use that as an array:

```c++
int64_t* ptr = x.data_ptr<int64_t>();
```

I am closing this issue for now. Please use the [forum](https://discuss.pytorch.org/) for questions, and feel free to open another issue if this turns out to be a feature request. Thanks!
