### ISSUE TITLE
Pytorch-GPU Installation Using Anaconda

### ISSUE THREAD

**Issue by SumantSoni** [pytorch/pytorch#37412]
Hello Friends, 
I have installed CUDA, Cunn and all other supporting files for GPU during tensorflow GPU installation by conda.

Now, I want to create a separate environment for PyTorch GPU version.

Please comment on it.

**Comment by kshitij12345** [comment]
@SumantSoni This blog should help:
http://makang.fun/2019/09/13/Install-Pytorch-GPU-by-Anaconda/

**Comment by colesbury** [comment]
Please see @kshitij12345's suggestion or the conda documentation

**Comment by SumantSoni** [comment]
I am getting error:

First I created an environment named as pytorch and then I run a command 

conda install pytorch torchvision cudatoolkit=10.1


after it, I got the following error :


---------------------------------------------------------------------
(pytorch) C:\Users\SUMANT>conda install pytorch torchvision cudatoolkit=10.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



(pytorch) C:\Users\SUMANT>
