### ISSUE TITLE
torch.utils.tensorboard.writer.SummaryWriter.add_graph missing documentation

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#37415]
## 📚 Documentation

The `add_graph` function on SummaryWriter doesn't have documentation

https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_graph

<img width="913" alt="Screen Shot 2020-04-28 at 11 13 26 AM" src="https://user-images.githubusercontent.com/655866/80504712-6cd50200-8941-11ea-94ed-62a5670970c6.png">

**Comment by orionr** [comment]
Looks like our logging (used for internal purposes) might have broken this?

For example, `torch._C._log_api_usage_once("tensorboard.logging.add_graph")` should be  below the docstring.

@lanpa any chance you could help out here with @natalialunova? Thanks.

**Comment by lanpa** [comment]
@orionr Correct, tried your fix and it renders like before.
