### ISSUE TITLE
The first sample in dataset cannot be evaluated properly.

### ISSUE THREAD

**Issue by Michael-J98** [pytorch/pytorch#37413]
## 🐛 Bug
I don't know where goes wrong,
but whatever the dataset is, as long as you feed the very 1st sample into evaluation, all you can get is that all the metrics are 0 or -1, even the model outputs a right outcome.(using coco metrics)

## To Reproduce

1. Train a mrcnn or keypoint-rcnn.
2.  Generate a sub_dataset containing the very 1st sample of its original dataset as well as its dataloader.
3.  Apply engine.evaluate. For example, if you write like this:

```python
indices = torch.arange(len(dataset)).tolist()
sub_dataset = torch.utils.data.Subset(dataset_test, indices[:1])
data_loader_test = torch.utils.data.DataLoader(sub_dataset, batch_size=1, shuffle=False, num_workers=num_workers,collate_fn=utils.collate_fn)
evaluate(model, data_loader_test, device=device)
```
you'll get 0 or -1.
But if you change 'torch.arange' for 'torch.randperm' like this:

```python
indices = torch.randperm(len(dataset)).tolist()
```

you'll get 1 or -1.
I tried several models and datasets, they are all the same.
## Expected behavior

The metrics equal 1 or -1.

## Environment

I run it on colab.

**Comment by colesbury** [comment]
There's not enough information here to be a useful bug report -- the PyTorch developers won't know why your metrics are 0 when you expect 1 or -1. You'll have to debug that yourself. 

Please reopen the issue if you narrow down the problem to a bug in PyTorch.
