### ISSUE TITLE
Questions about "torch.utils.tensorboard.add_graph": Could I use it to see network graph's compute time and memory? 

### ISSUE THREAD

**Issue by AugF** [pytorch/pytorch#37411]
## ❓ Questions

I want to check the step's compute time and memory of model,  and I find tensorboard in tensorflow can do it. But I run the document in official website (https://pytorch.org/docs/stable/tensorboard.html?highlight=tensorboard), it's not clearly. Could I use it to see network graph's compute time and memory? If yes, how to do it?

**Comment by colesbury** [comment]
Does the PyTorch tensorboard integration support tracking iteration time and memory usage?

This is a reasonable question and I don't see any answer in our documentation. Tagging @orionr and @lanpa who I think recently worked on tensorboard integration.

The `add_graph` functions docs also seem to have disappeared. Filed https://github.com/pytorch/pytorch/issues/37415 to track that as well.

**Comment by orionr** [comment]
cc @sanekmelnikov @natalialunova @J0Nreynolds 

Profiler extensions (where we connect autograd profiler output to TensorBoard) are a work in progress.  @J0Nreynolds and folks might be able to add some more details.

**Comment by aaronenyeshi** [comment]
Closing this as tensorboard plugin for profiler is deprecated (https://github.com/pytorch/kineto?tab=readme-ov-file#pytorch-tensorboard-profiler-deprecated). Please open a new Issue if this is for tensorboard instead of profiler plugin.
