### ISSUE TITLE
feature_alpha_dropout is not documented

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#37436]
https://pytorch.org/docs/master/search.html?q=feature_alpha_dropout&check_keywords=yes&area=default#

**Comment by albanD** [comment]
Note that the cpp doc actually tries to point to it here: https://pytorch.org/cppdocs/api/function_namespacetorch_1_1nn_1_1functional_1a73f6f4c90805456dd3217287ebf25b33.html?highlight=feature_alpha_dropout

**Comment by choidongyeon** [comment]
I have a PR out for this: https://github.com/pytorch/pytorch/pull/36295

**Comment by choidongyeon** [comment]
@ezyang  I think this issue can be closed now.
