### ISSUE TITLE
Runtime error(s) for Conv2d second gradient

### ISSUE THREAD

**Issue by dmarnerides** [pytorch/pytorch#3743]
The following code:
```
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(1, 1, 1, 1),
            nn.ReLU(),
            nn.Conv2d(1, 1, 1, 1),
        )
    def forward(self, v_x):
        return self.main(v_x).view(v_x.size(0), 1)

net = Network()
net.cuda()
v_in = Variable(torch.Tensor(2,1,1,1).cuda(), requires_grad=True)
grad_out = Variable(torch.ones(2,1,1,1).cuda())

gradient = autograd.grad(outputs=net(v_in), inputs=v_in,
                         grad_outputs=grad_out,
                         create_graph=True, retain_graph=True, 
                         only_inputs=True)[0]
gradient.mean().backward()
```
produces this error
> RuntimeError: Expected a Tensor of type Variable[torch.cuda.FloatTensor] but found an undefined Tensor for argument #0 'grad_output'

Also, removing the ReLU from the network:
```
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(1, 1, 1, 1),
            nn.Conv2d(1, 1, 1, 1),
        )
    def forward(self, v_x):
        return self.main(v_x).view(v_x.size(0), 1)
```
causes the error to change to:
> RuntimeError: ConvNdBackward: expected Variable at argument 0 (got None)

However, when the second convolution is removed as well:
```
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(1, 1, 1, 1),
        )
    def forward(self, v_x):
        return self.main(v_x).view(v_x.size(0), 1)
```
then the code runs error free

I'm on a ppc64le architecture with a P100 GPU, CUDA 8.0 and PyTorch version '0.4.0a0+6eca9e0'

**Comment by vic4ever** [comment]
I'm also having this problem using branch v0.3.0

**Comment by soumith** [comment]
i could reproduce this as well. we'll look into this.

**Comment by martinarjovsky** [comment]
I'm having the same error :/

**Comment by aelnouby** [comment]
same error with gradient penalty for WGAN

**Comment by hudongloop** [comment]
When you execute `gradient.mean().backward()` that cause memory leak？

**Comment by soumith** [comment]
@hudongloop no there shouldn't be a memory leak.

**Comment by aelnouby** [comment]
I am having an out of memory error as well, only when applying backward to the output of this method. I am using 3 titans GPUs so memory is not a problem I would assume.

    def compute_GP(netD, real_data, real_embed, fake_data, LAMBDA):
        BATCH_SIZE = real_data.size(0)
        alpha = torch.rand(BATCH_SIZE, 1)
        alpha = alpha.expand(BATCH_SIZE, int(real_data.nelement() / BATCH_SIZE)).contiguous().view(BATCH_SIZE, 3, 64, 64)
        alpha = alpha.cuda()
        interpolates = alpha * real_data + ((1 - alpha) * fake_data)
        interpolates = interpolates.cuda()
        interpolates = autograd.Variable(interpolates, requires_grad=True)
        disc_interpolates, _ = netD(interpolates, real_embed)
        gradients = autograd.grad(outputs=disc_interpolates, inputs=interpolates,
                                  grad_outputs=torch.ones(disc_interpolates.size()).cuda(),
                                  create_graph=True, retain_graph=True, only_inputs=True)[0]
        gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean() * LAMBDA
        return gradient_penalty
`

**Comment by hudongloop** [comment]
@aelnouby I am also using it with gradient penalty for WGAN, But When I use gradient_penalty.backward(), the memory leak is happen, My pytorch is 0.4.0a0+4d405a4.

**Comment by dmarnerides** [comment]
I can reproduce the memory leak with this:

```
import gc
import resource
import torch
from torch import nn, autograd
from torch.autograd import Variable

class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(1, 1, 1, 1),
            nn.Conv2d(1, 1, 1, 1),
        )
    def forward(self, v_x):
        return self.main(v_x).view(v_x.size(0), 1)

net = Network()

i = 0
while True:
    v_in = Variable(torch.Tensor(2,1,1,1), requires_grad=True)
    grad_out = Variable(torch.ones(2,1,1,1))

    gradient = autograd.grad(outputs=net(v_in), inputs=v_in,
                             grad_outputs=grad_out,
                             create_graph=True, retain_graph=True, 
                             only_inputs=True)[0]
    gradient.mean().backward()

    i += 1
    if i % 512 == 0:
        gc.collect()
        max_mem_used = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        print("{:.2f} MB".format(max_mem_used / 1024))
```

However the leak disappears when only one convolution is used:
```
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.main = nn.Sequential(
            nn.Conv2d(1, 1, 1, 1),
        )
    def forward(self, v_x):
        return self.main(v_x).view(v_x.size(0), 1)
```

Also, if nn.Linear is used, there is no leak.

Torch version: 0.4.0a0+8ebf18b

**Comment by apaszke** [comment]
I've opened a separate issue for that memory leak: #3835
