### ISSUE TITLE
torch.from_file is not documented

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#37439]
I'm not sure this was intentionally put in the torch namespace

cc @svekars @carljparker

**Comment by ezyang** [comment]
@albanD says this is a useful function but shouldn't be called `from_file`

**Comment by albanD** [comment]
I feel like this should be a low level function (we currently use it as such for multiprocess Tensor sharing IIRC).
Maybe we should provide a nice high level API for people that want to do disk-backed Tensor (for very large Tensors or sharing across processes).

**Comment by afcruzs** [comment]
> Maybe we should provide a nice high level API for people that want to do disk-backed Tensor (for very large Tensors or sharing across processes).

@albanD is as of today torch.from_file the only way to accomplish this? Is it recommended? Basic use case for me would be to read a fraction of a very large tensor stored in disk (without loading it entirely to memory).

**Comment by afcruzs** [comment]
Oh this looks very nice, looking forward to it!

**Comment by vadimkantorov** [comment]
Though torch.load mmap still deals only with certain packed formats. A bare torch.from_file would still be nice to have

**Comment by albanD** [comment]
Agree, we should add doc for this!

**Comment by vmoens** [comment]
> I feel like this should be a low level function (we currently use it as such for multiprocess Tensor sharing IIRC). Maybe we should provide a nice high level API for people that want to do disk-backed Tensor (for very large Tensors or sharing across processes).

In https://github.com/pytorch/pytorch/pull/112441 I provide a bunch of tools to create tensors on disk using this function. Would they fit the purpose?
