### ISSUE TITLE
There is a significant (>2x) reduction in JIT based RNN speed (comparing to PyTorch 1.4)

### ISSUE THREAD

**Issue by Kipok** [pytorch/pytorch#37455]
## 🐛 Bug

There is a significant (>2x) reduction in JIT based RNN speed (comparing to PyTorch 1.4). Here is the output of official PyTorch RNN benchmark script (https://github.com/pytorch/pytorch/tree/master/benchmarks/fastrnns):

```
python -m fastrnns.bench
Namespace(cnns=None, cuda_pointwise_block_count=None, cuda_pointwise_block_size=None, cuda_pointwise_loop_level=None, device='cuda', fuser='te', group=['cnns', 'rnns'], hiddenSize=512, inputSize=512, miniBatch=64, nloops=100, numLayers=1, print_json=None, rnns=None, sep=' ', seqLength=100, variable_lstms=False, warmup=10)
Benchmarking LSTMs...
            name          avg_fwd          std_fwd         info_fwd          avg_bwd          std_bwd         info_bwd
           cudnn            11.19           0.4118             None            14.31           0.4703             None
            aten            15.73           0.3472             None            29.82            2.899             None
             jit            24.17            1.169             None            67.43            2.373             None
      jit_premul            21.41           0.9056             None            66.24             3.45             None
 jit_premul_bias            19.91            0.798             None            65.87            2.384             None
      jit_simple            23.62           0.8895             None             66.7            3.799             None
  jit_multilayer            24.31            1.069             None            68.32            1.988             None
              py            28.68           0.9271             None            50.49            3.447             None
```

I'm getting the same numbers if I additionally add `torch._C._jit_set_profiling_mode(True)` to the beginning of `bench.py` script.

The same script based on PyTorch 1.4 produces the following output:

```
python -m fastrnns.bench
Namespace(cnns=None, device='cuda', group=['cnns', 'rnns'], hiddenSize=512, inputSize=512, miniBatch=64, nloops=100, numLayers=1, print_json=None, rnns=None, sep=' ', seqLength=100, variable_lstms=False, warmup=10)
Benchmarking LSTMs...
            name          avg_fwd          std_fwd         info_fwd          avg_bwd          std_bwd         info_bwd
           cudnn            10.96           0.3011             None             14.1           0.4423             None
            aten             16.2           0.4902             None            22.86           0.7291             None
             jit            11.34           0.3869             None            17.96            3.052             None
      jit_premul            9.825           0.2596             None            13.46            1.702             None
 jit_premul_bias            10.08           0.2104             None            12.86            1.788             None
      jit_simple            11.04           0.4475             None           0.5909          0.02453             None
  jit_multilayer            11.21           0.4251             None            20.68            5.719             None
              py            26.42            2.303             None            53.71              2.5             None
```

I'm seeing the same reduction for some of my personal JIT based RNN code.

## To Reproduce

1. Install PyTorch 1.5, clone PyTorch, then `git checkout v1.5.0`
2. Run `python -m fastrnns.bench` from https://github.com/pytorch/pytorch/tree/master/benchmarks
3. Install PyTorch 1.4, then `git checkout v1.4.0`
4. Run `python -m fastrnns.bench` from https://github.com/pytorch/pytorch/tree/master/benchmarks

## Expected behavior

Speed should be the same or faster with PyTorch 1.5

## Environment
PyTorch 1.5 environment:
```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      2.15                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              hfd86e86_0
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] liblapacke                3.8.0                    15_mkl    conda-forge
[conda] mkl                       2020.0                      166
[conda] numpy                     1.16.4           py37h95a1406_0    conda-forge
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch
```
PyTorch 1.4 environment:
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[pip] warprnnt-pytorch==0.1
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.0                      166
[conda] numpy                     1.18.1           py37h95a1406_0    conda-forge
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
```

cc @ezyang @gchanan @zou3519 @suo

**Comment by wanchaol** [comment]
@Krovatkin can you take a look? I believe this is similar to the regression that adam observed.

**Comment by VitalyFedyunin** [comment]
cc @VitalyFedyunin

**Comment by Krovatkin** [comment]
Hi @Kipok 
Thanks for reporting this!
In v1.5 we had to disable some optimizations as our users have run into a few pathological cases with very long compilation times.
We are working on improving the profiling executor, which will be our preferred approach to deliver more performance for our users. 
There's still a whole lot of work to be done and in some cases we might be getting suboptimal performance when using the profiling executor.
I will take a look at `fastrnns` to address this issue.
In order to get better performane out of the profiling executor, I'd recommend increasing `torch._C._jit_set_bailout_depth` and making sure the number of profiled runs stays equal to 1 
```
torch._C._jit_set_profiling_mode(True)
torch._C._jit_set_bailout_depth(100)
torch._C._jit_set_num_profiled_runs(1)
```

**Comment by Kipok** [comment]
Thanks for fast response @Krovatkin! Just tried to plug in those 3 lines and still getting significantly suboptimal performance (although a bit better then before):

```
python -m fastrnns.bench
Namespace(cnns=None, device='cuda', group=['cnns', 'rnns'], hiddenSize=512, inputSize=512, miniBatch=64, nloops=100, numLayers=1, print_json=None, rnns=None, sep=' ', seqLength=100, variable_lstms=False, warmup=10)
Benchmarking LSTMs...
            name          avg_fwd          std_fwd         info_fwd          avg_bwd          std_bwd         info_bwd
           cudnn            11.02           0.2974             None            14.41           0.3502             None
            aten            16.12           0.3933             None            30.63            2.927             None
             jit            20.86           0.7442             None             50.9            2.236             None
      jit_premul             18.2           0.7024             None            51.53            0.844             None
 jit_premul_bias               16            1.774             None            44.16            8.476             None
      jit_simple            19.09            2.143             None            41.75             8.68             None
  jit_multilayer            18.53           0.5577             None            35.78            2.911             None
              py            25.27            2.219             None            37.99            7.989             None
```
By the way, is there any documentation on those parameters (bailout_depth, num_profiled_runs)? I only saw "torch._C._jit_set_profiling_mode(True)" referenced in v1.5 release document, but don't really understand what other parameters are doing.

**Comment by Krovatkin** [comment]
@Kipok 

The other parameters were added to help other developers working on jit performance to unblock their experiments. They are internal.
Our goal is to provide our users with good out-of-the-box performance after the dust of all the performance work settles.

`torch._C._jit_set_bailout_depth` is the number of different specializations of a graph the profiling executor is allowed to generate.  The graph is specialized based on the properties of input tensors such as shapes, strides, requires gradient, etc and optimized for those properties. When the profiling executor exhausts the number of the allowed specializations, it falls back to a compilation strategy that doesn't use any profiling information (that's the default compilation strategy in v1.5)

However, too many specializations isn't ideal as it forces the profiling executor to compile every time the properties of the input tensors change and if they change in every run, any possible gains from more efficient specializations will be negated by compilation time overhead. This is where `torch._C._jit_set_num_profiled_runs(1)` might come handy.
`torch._C._jit_set_num_profiled_runs(N)` makes the executor profile for a specified number of runs `N` before it tries to specialize. If during these runs the profiler observes different input shapes, it combines these signals in a lossy way (i.e. the knowledge about specific individual dimensions might be lost/generalized), so some optimizations will perform worse, but the result will be more robust to the changes in the properties of the input tensors.

**Comment by mravanelli** [comment]
I also observed a major speed issue with my customized RNN models compiled with jit and pytorch 1.5. Pytorch 1.4 works fine. See #38342 . Any idea?

**Comment by cpuhrsch** [comment]
cc @suo who mentioned you can still turn on the old fuser to gain the prior performance

**Comment by Kipok** [comment]
Any progress for this issue? Or maybe any hacks/workarounds that can bring the performance closer to what it was with PyTorch 1.4?

**Comment by ZolotukhinM** [comment]
> Any progress for this issue? Or maybe any hacks/workarounds that can bring the performance closer to what it was with PyTorch 1.4?

You could try the following workaround:
```
torch._C._jit_set_profiling_executor(False)
```
It should bring the performance close to PyTorch 1.4. However, I would not recommend using it heavily if you can avoid it, because it is an internal API that could be changed at any point.
