### ISSUE TITLE
Support indexing in JIT dispatch

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#3747]
The new index() and index_put_() methods take both `Tensor` and `TensorList` arguments. The JIT dispatch code doesn't currently handle this case, which means that calls to these functions will not be JIT-able.

See https://github.com/pytorch/pytorch/pull/3725

cc @ezyang @apaszke

**Comment by jamesr66a** [comment]
I believe this is closed by https://github.com/pytorch/pytorch/pull/8173
