### ISSUE TITLE
Conv2d padding gradient computation error

### ISSUE THREAD

**Issue by BeierZhu** [pytorch/pytorch#37479]
## ❓ Questions and Help

@zou3519 @colesbury 
### This issue is related to the closed issue https://github.com/pytorch/pytorch/issues/14798#event-3280657372

I met the same problem when I attempt to reproduce the result from Pytorch samples- fast_neural_style https://github.com/pytorch/examples/tree/master/fast_neural_style.
The original code works fine. However, if I change the nn.ReflectionPad2d to zero_padding, as follows:

Original Code from https://github.com/pytorch/examples/blob/master/fast_neural_style/neural_style/transformer_net.py:
```
class ConvLayer(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvLayer, self).__init__()
        reflection_padding = kernel_size // 2
        self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride)

    def forward(self, x):
        out = self.reflection_padding(x)
        out = self.conv2d(out)
        return out
```
Modified Code:
```
class ConvLayer(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvLayer, self).__init__()
        reflection_padding = kernel_size // 2
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding=reflection_padding)

    def forward(self, x):
        out = self.conv2d(x)
        return out
```
It throws the following error during graph computation:
Traceback (most recent call last):
  File "neural_style/neural_style.py", line 240, in <module>
    main()
  File "neural_style/neural_style.py", line 234, in main
    train(args)
  File "neural_style/neural_style.py", line 90, in train
    total_loss.backward()
  File "/mnt/lustre/share/platform/env/miniconda3/envs/pt1.0.1/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre/share/platform/env/miniconda3/envs/pt1.0.1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

This is quite strange.

**Comment by SsnL** [comment]
Usually this is because the input to this layer is reused elsewhere and modified inplace. The first version works because a copy is made via the reflection padding.

**Comment by SsnL** [comment]
Use the forum for questions please. Github is only for issues.
