### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.nn._functions'

### ISSUE THREAD

**Issue by codeprb** [pytorch/pytorch#37477]
Hi 

I am trying to run my code on the terminal I  get the following error. 

import torch
import pdb
import torch.nn as nn
import math

File "/Users/xxxxxx/Desktop/Code/BBN/models/bnmodules.py", line 65, in <module>
    import torch.nn._functions as tnnf
ModuleNotFoundError: No module named 'torch.nn._functions'

This happens only from command line. It works all good when I directly run form the visual studio on anaconda. May I know how can I fix this. when I check for the PyTorch version I get the following.

>>> import torch
>>> torch.__version__
'1.4.0'
>>> import torchvision
>>> torchvision.__version__
'0.5.0'

This is the same issue when I try to run on the remote server (Ubuntu 18).

**Comment by SoyedTuhinAhmed** [comment]
I have the same error

**Comment by louislxw** [comment]
> Hi
> 
> I am trying to run my code on the terminal I get the following error.
> 
> import torch
> import pdb
> import torch.nn as nn
> import math
> 
> File "/Users/xxxxxx/Desktop/Code/BBN/models/bnmodules.py", line 65, in
> import torch.nn._functions as tnnf
> ModuleNotFoundError: No module named 'torch.nn._functions'
> 
> This happens only from command line. It works all good when I directly run form the visual studio on anaconda. May I know how can I fix this. when I check for the PyTorch version I get the following.
> 
> > > > import torch
> > > > torch.**version**
> > > > '1.4.0'
> > > > import torchvision
> > > > torchvision.**version**
> > > > '0.5.0'
> 
> This is the same issue when I try to run on the remote server (Ubuntu 18).

Hi, 
May I know if you have solved this problem? Thanks!

**Comment by defineHong** [comment]
I have the same error and I need help QwQ

**Comment by skaudrey** [comment]
Anyone works it out? Waiting for help QAQ
