### ISSUE TITLE
FP16 implementation has the same speed as FP32 on Tesla V100

### ISSUE THREAD

**Issue by michaelhuang74** [pytorch/pytorch#3748]
I am trying to improve the speed of neural style transfer by converting it to FP16 implementation to take the advantage of Tensor Core on the Tesla V100 GPU.

The original FP32 implementation is at https://github.com/leongatys/PytorchNeuralStyleTransfer

I put the VGG-19 model to FP16 and leave the loss function at FP32 (to avoid overflow and underflow). The modified code is at https://gist.github.com/michaelhuang74/009e149a2002b84696731fb599408c90

When I run both FP32 and FP16 implementations using the Tesla V100 on Amazon AWS cloud, the speed is same. When the image size is set 800 pixel, both FP32 and FP16 implementations take around 17 seconds for 100 iterations. 

Following is the environment setting.
CUDA 9, CUDNN 7, the latest PyTorch. 

I am wondering if the computation is really carried out on the Tensor Cores for my FP16 implementation?

**Comment by csarofeen** [comment]
I tested vgg19 with batch size 64 and got the following results:

FP32 Iterations per second:  2.84
FP16 Iterations per second:  3.98

The script I used is [test_pytorch_vgg19_fp16.py](https://gist.github.com/csarofeen/f07e2d59e56052dbfa695bac0748d764). However, as you aren't simply using vgg and doing more, I'm not sure how the performance of the rest of the network will impact this. For example if vgg takes 50% of total time, no matter how fast it gets your network will never be more than 2x faster if you don't also speed up the rest of the network.

There are some complexities for training accurately in fp16. I would recommend following the code in [fp16 imagenet example](https://github.com/csarofeen/examples/tree/fp16_examples/imagenet) as it follows best practices.

**Comment by u39kun** [comment]
For anyone interested, here's what I got on Titan V by running [test_pytorch_vgg19_fp16.py](https://gist.github.com/csarofeen/f07e2d59e56052dbfa695bac0748d764):

FP32 Iterations per second:  2.346192444809963
FP16 Iterations per second:  3.345746130309632

**Comment by u39kun** [comment]
Another run on PyTorch 0.3.0, CUDA 9.0.176, CUDNN 7005 based on nvcr.io/nvidia/pytorch:17.12 docker image:

FP32 Iterations per second:  2.343622650013177
FP16 Iterations per second:  3.382694757257183

**Comment by borisfom** [comment]
@csarofeen : we may need to look at LBGFS optimizer. It actually gives more intersesting results than Adam for this algo. I just tried LBGFS and it fails like this :

# optimizer = optim.Adam([opt_img],lr=1e1,eps=1e-04)
optimizer = optim.LBFGS([opt_img], lr=1e1)

python neural-style-Gatys-half.py 
/usr/local/lib/python2.7/dist-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
print out the vgg layers
VGG(
  (conv1_1): Conv2d (3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv1_2): Conv2d (64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2_1): Conv2d (64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2_2): Conv2d (128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv3_1): Conv2d (128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv3_2): Conv2d (256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv3_3): Conv2d (256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv3_4): Conv2d (256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4_1): Conv2d (256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4_2): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4_3): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4_4): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv5_1): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv5_2): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv5_3): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv5_4): Conv2d (512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
  (pool2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
  (pool3): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
  (pool4): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
  (pool5): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1))
)
('Print loss layers', ['r11', 'r21', 'r31', 'r41', 'r51', 'r42'])
('Print loss functions', [GramMSELoss(
), GramMSELoss(
), GramMSELoss(
), GramMSELoss(
), GramMSELoss(
), MSELoss(
)])
('Print weights', [0.244140625, 0.06103515625, 0.0152587890625, 0.003814697265625, 0.003814697265625, 1.0])
('The length of targets:', 6)
Traceback (most recent call last):
  File "neural-style-Gatys-half.py", line 194, in <module>
    optimizer.step(closure)
  File "/usr/local/lib/python2.7/dist-packages/torch/optim/lbfgs.py", line 197, in step
    gtd = flat_grad.dot(d)  # g * d
RuntimeError: cublas runtime error : unknown error at /pytorch/torch/lib/THC/THCBlas.cu:67

**Comment by ngimel** [comment]
@borisfom I cannot reproduce the error running LBFGS optimizer on a generic network, please share an example that reproduces the error.

**Comment by borisfom** [comment]
@ngimel: Please run https://gist.github.com/michaelhuang74/009e149a2002b84696731fb599408c90 (uncomment line with LBGFS and comment Adam line)
