### ISSUE TITLE
Libtorch 1.5 failed to access CUDA devices

### ISSUE THREAD

**Issue by jianyin2016** [pytorch/pytorch#37481]
## Description

1.   `torch::cuda::is_available()` returns **false** on the newly released libtorch 1.5, while it returns **true** when using libtorch 1.4. 
1. It may depends on the environment, there are two kinds of GPU on the machine, 1 GTX 1080Ti and 2 Tesla P100, besides, the OS is Windows 7 enterprise. I can't access the env_collect script currently, so the environment info I could offer is limited. I have multi-version cuda installed, from cuda 8.0 to cuda 10.2, I guess maybe libtorch failed to find the right version?:(

 `NVIDIA_SMI`  executed info:
> NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2   

 `nvcc -V` executed info:
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Tim
> Cuda compilation tools, release 10.2, V10.2.89

## Expected behavior

All the GPU should be detected by libtorch.

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/issues/37124#issuecomment-618142192
