### ISSUE TITLE
Segmentation fault when calling eig() on an tensor with nan values.

### ISSUE THREAD

**Issue by kunalmenda** [pytorch/pytorch#37499]
## 🐛 Bug

When calling `x.eig()` on a tensor `x` containing nan values, I get a segmentation fault with the following error message.
```
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Segmentation fault: 11
```

## To Reproduce

```
import torch
import numpy as np
A = np.nan * torch.ones((3,3))
A.eig()
```

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: (GCC) 6.3.0
CMake version: version 3.14.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.1
[pip3] numpydoc==0.8.0
[pip3] torch==1.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] numpy                     1.15.4           py37hacdab7b_0  
[conda] numpy                     1.15.4                    <pip>
[conda] numpy-base                1.15.4           py37h6575580_0  
[conda] pytorch                   1.1.0                   py3.7_0    PyTorch
[conda] torch                     1.1.0                     <pip>
[conda] torch                     1.5.0                     <pip>
[conda] torchvision               0.2.1                      py_2    pytorch

Thanks!

**Comment by lufol** [comment]
I could confirm this in colab.
Interestingly on pytorch 1.4.0 the following error was raised 
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-3-b4c3563dda98> in <module>()
----> 1 A.eig()

RuntimeError: Lapack Error in geev : Illegal Argument 4 at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:237
```
I could not find a python wrapper of the `.eig()` call. But a wrapper could check for nans in the tensor prior to handing it over to MKL.

**Comment by cpaulse** [comment]
numpy's eig() does a check for np.inf and np.NaN elements [here](https://github.com/numpy/numpy/blob/4753652c605833e2398d7e46b754a71729a54713/numpy/linalg/linalg.py#L1063). I guess this check could be made for the THTensor `a_` [here](https://github.com/pytorch/pytorch/blob/a7da4490cc44fc9d9740ed508ad5048cbdca9e10/aten/src/TH/generic/THTensorLapack.cpp#L195).

**Comment by jamaliki** [comment]
If this problem still exists @cpaulse I would like to help, but I could not find the file you were mentioning in master anymore. Is the relevant functionality here, aten/src/ATen/native/BatchLinearAlgebra.cpp? Because I saw some NaN input checks there.
