### ISSUE TITLE
Load Quantized BERT Classifier model from Disk

### ISSUE THREAD

**Issue by suryapa1** [pytorch/pytorch#37518]
## 🐛 Bug

Deserialize BERT dynamically quantized model.

## To Reproduce

1. Train BertClassifier and train the model
2. Initiate below code to quantize model and save on disk
3. Problem to load serialize model, How to do that??
4. BertSequenceClassifier.pre_trained_model(quantized_output_dir) is not working as expected.

quantized_output_dir = configs.output_dir + "quantized/"
if not os.path.exists(quantized_output_dir):
    os.makedirs(quantized_output_dir)
    quantized_model.save_pretrained(quantized_output_dir)

## Expected behavior

When compared predictions without quantization model and inference using loaded quantized model is very uncertain. Any code sample of deserialized of the quantized model would be greatly appreciated

As of now, when am trying this it is not working when using following load&save transformer models.

def load_transformer_model(self, model_path, train_args_=train_args):

        model = RobertaForSequenceClassification.from_pretrained(model_path)
        # model.model.eval()
        return model

    def save_transformer_model(self, model, output_dir):
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        print("Saving model to %s" % output_dir)
        model_to_save = model.module if hasattr(model,
                                                'module') else model  # Take care of distributed/parallel training
        model_to_save.save_pretrained(output_dir)
        self.tokenizer.save_pretrained(output_dir)
        torch.save(self.train_args, os.path.join(output_dir, 'training_args.bin'))

## Additional context
https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/dynamic_quantization_bert_tutorial.ipynb

**Comment by pbelevich** [comment]
Please create an issue either in https://github.com/pytorch/tutorials or ask it on https://discuss.pytorch.org/
