### ISSUE TITLE
[c10d] Make ProcessGroup::Work::wait() take a timeout argument

### ISSUE THREAD

**Issue by echaozh** [pytorch/pytorch#37571]
## 🚀 Feature
Make ProcessGroup::Work::wait() take a timeout argument, and aborts waiting if the timeout expires. 

## Motivation

For NCCL all reduce, when some of the nodes become unreachable, the wait() call doesn't return and the whole operation hangs. There is no hope to continue the operation, at least we can know that the fact,abort the training and try again.

## Pitch

Add a timeout argument to ProcessGroup::Work::wait(), and call wait_for() instead of wait() on the condition_variable it already uses.

## Alternatives

1. Use another thread to call ProcessGroup::Work::wait(). wait() suspends the calling thread, to create a thread for it is clumsy.
2. Do not call wait(), but periodically check ProcessGroup::Work::is_completed(). There's a performance penalty here.

## Additional context

None

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by zhaojuanmao** [comment]
actually right now nccl all reduce work has timeout, it needs to be enabled by manually setting env variable NCCL_BLOCKING_WAIT = 1

**Comment by echaozh** [comment]
When setting blocking wait, the synchronize() function sleeps a while and check for completion. The constant length of each sleep is 10ms, which is too long. Or can you tune down the constant to microsecond level?

**Comment by pritamdamania87** [comment]
@echaozh A microsecond level constant might cause a tight busy wait loop. Usually collective operations are expensive network calls and hence we have a constant of 10ms. Could you elaborate how a microsecond level constant would help in your case?
