### ISSUE TITLE
Add a CI job using conda compilers

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#37584]
## 🐛 Bug

There's regularly issues building PyTorch with either conda compilers or with a very new (system installed) GCC + conda Python+dependencies. Using a development setup based on conda is recommended (https://github.com/pytorch/pytorch#from-source) so this is not a great situation. Example issues:

- https://github.com/pytorch/pytorch/issues/29093 (has some relevant discussion)
- https://github.com/pytorch/cpuinfo/issues/36
- The patches we're carrying around for a build setup used by ~8 people, gets quite inefficient: https://github.com/Quansight/pearu-sandbox/blob/master/working-envs/activate-pytorch-dev.sh

Furthermore, making the build config with conda compilers robust is required for making the conda binaries conda-forge compatible so they can be synced to `conda-forge/pytorch` (there's more to do there that I need to follow up on, this is step 1 - xref https://github.com/conda-forge/pytorch-cpu-feedstock/issues/7).

## Expected behavior

Using conda compilers on Linux should work out of the box. To make it more reliable, we should add a CI job using it. The question I have is if it should be an extra CI job entry, or if we should modify an existing one (and if so, which one)?

Cc @ezyang 

cc @malfet @ezyang @seemethere

**Comment by ezyang** [comment]
> The question I have is if it should be an extra CI job entry, or if we should modify an existing one (and if so, which one)?

Extra CI seems right

**Comment by mattip** [comment]
gh-35363 will fix gh-29093. The [cpuinfo PR](https://github.com/pytorch/cpuinfo/pull/37) was already merged to master. What remains is
- set up a CI build job with an environment close to the one used in [conda/conda-forge](https://github.com/conda-forge/pytorch-cpu-feedstock/blob/master/conda-forge.yml)
- use the environment variables in @pearu 's scripts  in the CI job
- carefully read through the discussions around conda-forge/pytorch-cpu-feedstock#7 to see what else is missing

I think we should only add one CI job on linux in a docker with CUDA.

**Comment by rgommers** [comment]
> I think we should only add one CI job on linux in a docker with CUDA.

I agree.

> carefully read through the discussions around conda-forge/pytorch-cpu-feedstock#7 to see what else is missing

There's a whole bunch of stuff there that's better left for a follow-up. A job that exactly matches the setup on our current build server seems like the better first step. Doing it the conda-forge way  requires more changes, patching conda-smithy, relying on mutex packages, etc.

I think the scope of this issue is "stop the bleeding".

**Comment by rgommers** [comment]
> gh-35363 will fix gh-29093.

Those are both issues. gh-37506 is the PR that upgrades NCCL

**Comment by mattip** [comment]
>  A job that exactly matches the setup on our current build server seems like the better first step.

All the docker images call [`install_base.sh`](https://github.com/pytorch/pytorch/blob/master/.circleci/docker/common/install_base.sh). Is that OK as a base or should we build an entirely new image without the packages installed there?

**Comment by rgommers** [comment]
It probably can't hurt, because once you activate the conda env, conda packages/tools take precedence anyway (e.g. CMake, MKL). So easier to keep it, for things like git, vim, valgrind, curl.

**Comment by ezyang** [comment]
I think @seemethere may have an opinion here

**Comment by mattip** [comment]
The idea would be to do something like
`conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing pytest compile flake8 psutil hypothesis nvcc_linux-64=10.2 magma-cuda102`
as extra commands, then use these in the regulare `*_build` `*_test` cycle. 

Extra tweaks to environment variables like `CFLAGS` and `LDFLAGS` may be needed to get this going, but eventually that all could be folded back into the CMake scripts.

How would I get started with adding a build job? I understand I need to add something to `.circleci/cimodel`, but there are not many comments about how to do that.

**Comment by rgommers** [comment]
I think the advice in `.circleci/README` under _CircleCI configuration generator_ is up to date. gh-38747 was just opened to add new CI jobs for GCC 9, that may be a template to follow for the build job. It lacks the corresponding test job as far as I can tell, but I assume that's analogous.

**Comment by h-vetinari** [comment]
If your CI can take images, there are several (including cuda-enabled ones) [here](https://hub.docker.com/u/condaforge) coming from this [repo](https://github.com/conda-forge/docker-images).

CC @isuruf @jakirkham

**Comment by malfet** [comment]
@rgommers I'm adding build and test jobs as well, but it had to be done in stages.

**Comment by mattip** [comment]
I think the documentation is outdated: the file `.circleci/verbatim-sources/workflows/workflows-docker-builder.yml` is used to *build* images. I have started gh-38796 and will follow gh-38747 to see how to add the build/test jobs

**Comment by jakirkham** [comment]
cc @kkraus14 (for vis)

**Comment by malfet** [comment]
@mattip Thank you very much for doing it. Please do not hesitate to ping me if you are blocked.
