### ISSUE TITLE
Fix and enable DDP SPMD tests

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37593]
As [`run_tests.py`](https://github.com/pytorch/pytorch/blob/bbd2350c99db334f27e910f50d377bd8de0fd39b/test/run_test.py#L160) sets `world_size` to 3 for `test_distributed.py`, SPMD path is only tested when there are at least 6 GPUs. But our CI offers at most 4, so these tests are actually not run. As we haven't officially retire SPMD yet, we should fix and enable those tests. More discussions are in #36939.

For context, IIUC, the reason for using `world_size=3` is to enable subgroup tests for `torch.distributed`. We should keep those tests enabled as well.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by rohan-varma** [comment]
SPMD mode is deprecated, so we will no longer support these tests
