### ISSUE TITLE
Rewrite documentation coverage tests

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#37590]
## 📚 Documentation

PR gh-37419 disabled the tests in `tests/test_doc_coverage.py` as explained in [this comment](https://github.com/pytorch/pytorch/pull/37419#issuecomment-621431059). Rather than delay that PR, this issue was opened to track refactoring those tests.

**Comment by mattip** [comment]
We only need to check coverage once. It would be useful to do this while building documentation in the CI `pytorch_python_doc_push` job. Would a failure there show up correctly in CI?

**Comment by rgommers** [comment]
Guess so, why wouldn't it? You may have to nudge it along with something like `set -o pipefail`, but must be possible.
