### ISSUE TITLE
additional continuous builds

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3759]
The following additional continuous build configurations are needed:

- gcc 4.8 CPU
- gcc 7.x CPU
- move travis contbuild configurations over to ci.pytorch.org (CPU builds)
   - travis is turning out to be too slow (1hr+ for build matrix)
- Windows CI

**Comment by peterjc123** [comment]
@soumith Good news to here. I could provide some help if needed.

**Comment by stefan-it** [comment]
Hi :)

would it be possible to test `pytorch` compilation for GCC 7? `.travis.yml` uses *Trusty* as Ubuntu Distribution and - according to the *Travis CI* documentation - GCC 7 is available using `g++-7` on *Trusty*. For more information see [here](https://docs.travis-ci.com/user/languages/cpp/#GCC-on-Linux) :)

**Comment by peterjc123** [comment]
Any progress here?

**Comment by soumith** [comment]
this will happen over the next week (starting monday). @yf225 will be working on it.

**Comment by yf225** [comment]
Done moving Travis contbuilds to ci.pytorch.org.

Windows CI is currently running slow (~40 mins for a clean build, and incremental build with clcache is unstable), probably need to speed up more before enabling it in PRs.

Also working on gcc 4.8 and 7.x CPU contbuilds.

**Comment by yf225** [comment]
gcc 4.8 and 7.2 CPU contbuilds are up

**Comment by yf225** [comment]
Windows CI is now enabled
