### ISSUE TITLE
Attribute error while using SummaryWriter.add_image()

### ISSUE THREAD

**Issue by jainnitk** [pytorch/pytorch#37601]
## 🐛 Bug

I am using Colab notebook and while running SummaryWriter.add_image(), it gives me an error "AttributeError: 'str' object has no attribute '_check_caffe2_blob' ".

## To Reproduce

1.I am using Pytorch. 
1.Following is the code I am using :
train_set=torchvision.datasets.FashionMNIST(
    root='./data/FashionMNIST',
    train=True,
    download=True,
    transform=transforms.Compose([
        transforms.ToTensor()
    ]))
train_loader=torch.utils.data.DataLoader(train_set,batch_size=100)
tb=SummaryWriter
images,labels=next(iter(train_loader))
grid=torchvision.utils.make_grid(images)

tb.add_image('images',grid,0)
tb.add_grpah(network,images)
tb.close()

Error :
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-167-ac549479ff1e> in <module>()
      5 grid=torchvision.utils.make_grid(images)
      6 
----> 7 tb.add_image('images',grid,0)
      8 tb.add_grpah(network,images)
      9 tb.close()

/usr/local/lib/python3.6/dist-packages/torch/utils/tensorboard/writer.py in add_image(self, tag, img_tensor, global_step, walltime, dataformats)
    535         """
    536         torch._C._log_api_usage_once("tensorboard.logging.add_image")
--> 537         if self._check_caffe2_blob(img_tensor):
    538             img_tensor = workspace.FetchBlob(img_tensor)
    539         self._get_file_writer().add_summary(

AttributeError: 'str' object has no attribute '_check_caffe2_blob'
## Expected behavior

No error.

Environment:

 - PyTorch Version (e.g., 1.0):1.5.0+cu101
 - OS (e.g., Linux):Google Colab
 - How you installed PyTorch (`conda`, `pip`, source): Pre Installed with Colab
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Colab
 - Any other relevant information:

**Comment by Aceticia** [comment]
Hello, was this problem solved? I encountered the same issue. It looks really strange that the object method calls all ignored the first argument of 'self'.

**Comment by avnishere** [comment]
If it helps, recheck for trivial errors. In my case, the class 'SummaryWriter()' had a typo 'SummaryWriter' while declaring the tensorboard.
