### ISSUE TITLE
[JIT] Error accessing NamedTuple field by name in module's forward

### ISSUE THREAD

**Issue by stas-sl** [pytorch/pytorch#37668]
## 🐛 Bug

When I try to access NamedTuple field by name like this:

```python
import torch
from typing import NamedTuple

class Params(NamedTuple):
    p1: float
    p2: int

class MyModule(torch.nn.Module):
    def __init__(self, params):
        super().__init__()
        self.params = params

    def forward(self):
        print(self.params.p1)

params = Params(1.0, 2)
m = torch.jit.script(MyModule(params))
m()
```
The following error is raised:
```
RuntimeError: 
Tried to access nonexistent attribute or method 'p1' of type 'Tuple[float, int]'.:
  File "test_torch_script.py", line 72
    def forward(self):
        print(self.params.p1)
              ~~~~~~~~~~~~~~ <--- HERE
```
Though if accessing by index `self.params[0]` it works.

Also I tried to pass NamedTuple directly to `forward` method
```python
import torch
from typing import NamedTuple

class Params(NamedTuple):
    p1: float
    p2: int

class MyModule(torch.nn.Module):
    def __init__(self, params):
        super().__init__()
        self.params = params

    def forward(self, params: Params):
        print(params.p1)

params = Params(1.0, 2)
m = torch.jit.script(MyModule(params))
m(params)
```
And it also raises an error (though the type in the message is different):
```
RuntimeError: 
Tried to access nonexistent attribute or method 'name' of type '__torch__.Params'.:
  File "test_torch_script.py", line 72
    def forward(self, params: Params):
        print(params.name)
              ~~~~~~~~~~~ <--- HERE
```
As in the first case `params[0]` also works here.

The last thing I tried is standalone function:
```python
import torch
from typing import NamedTuple

class Params(NamedTuple):
    p1: float
    p2: int

params = Params(1.0, 2)

@torch.jit.script
def f(params: Params):
    print(params.p1)

f(params)
```
And surprisingly it worked as expected.

## Expected behavior

It should be able to access NamedTuple fields by name in all the cases above.

## Environment

```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 430.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.5.0
[pip] torch-model-archiver==0.1.0b20200409
[pip] torchserve==0.0.1b20200409
[pip] torchtext==0.6.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_0
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch-model-archiver      0.1.0b20200409           pypi_0    pypi
[conda] torchserve                0.0.1b20200409           pypi_0    pypi
[conda] torchtext                 0.6.0                      py_1    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch
```

cc @suo

**Comment by SplitInfinity** [comment]
I'm looking into this at the moment

**Comment by SplitInfinity** [comment]
Your second example works fine actually; I think you referenced an attribute called `name` that doesn't exist as per your definition of `Params`.

**Comment by eellison** [comment]
@SplitInfinity probably in the type inferrence in pybind_utils.h we're not checking for NamedTuples

**Comment by stas-sl** [comment]
> Your second example works fine actually; I think you referenced an attribute called `name` that doesn't exist as per your definition of `Params`.

Good catch! Sorry for false alarm

**Comment by SplitInfinity** [comment]
@eellison Yeah that's basically it. When inferring types of attributes, we first check if something is a class as per `inspect.isclass` and if it is, we look for an already scripted type for it. If we find nothing, then we try inferring a container type and that happens to work out in this case.

But I'm not quite sure how to detect whether something is a `NamedTuple` or was created using `collections.namedtuple`. `inspect.isclass` will return `True` for both cases, but `issubclass` and `isinstance` will return `False`. Once we figure that out, as long as we impose the restriction that any member of a `NamedTuple` must be another `NamedTuple` or a TorchScript type, I think we can fix this.

**Comment by eellison** [comment]
What do you mean
> But I'm not quite sure how to detect whether something is a NamedTuple or was created using collections.namedtuple

Is there a difference between the two ? you can check if something is a NamedTuple in python with:
```
def is_namedtuple(x):
    return isisnstance(x, tuple) and not type(x) == tuple
```

Once you know it's a named tuple you can look up the class in python, compile it, then call `toIValue` on the object isinstance and see if it succeeds.

**Comment by SplitInfinity** [comment]
Dumb question but compile how? `CompilationUnit::define` gives back a list of functions :(

**Comment by eellison** [comment]
hey sorry, i didn't see your comment till just now. nn Module attributes get added here https://github.com/pytorch/pytorch/blob/master/torch/jit/_recursive.py#L98,  and then within `_jit_try_infer_type` you can reuse the logic from https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/python/python_sugared_value.cpp#L629
