### ISSUE TITLE
[DISCUSSION] Expose Future() in Python API

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37678]
Futures or Future-like types are currently used in several places:

1. [`ivalue::Future`](https://github.com/pytorch/pytorch/blob/deb4100928f306c2f92a9e006393d9a2c79389c7/aten/src/ATen/core/ivalue_inl.h#L222)
2. [`utils::Future`](https://github.com/pytorch/pytorch/blob/deb4100928f306c2f92a9e006393d9a2c79389c7/torch/csrc/utils/future.h#L29): used by `torch.distributed.rpc`
3. [`c10d::ProcessGroup::work`](https://github.com/pytorch/pytorch/blob/deb4100928f306c2f92a9e006393d9a2c79389c7/torch/lib/c10d/ProcessGroup.hpp#L38): used by asynchronous c10d operators

There is an on-going effort to gradually merge these (see #34997 #35154). Since the merged `Future` type will be used by several different components, the question is where it should live? This was not an urgent issue to resolve previously, as applications only get the `Future` as the return value from some functions. However, in the near term, we are going to expose `Future`'s constructor for the async RPC user function support (see #36071), applications will need to explicitly import the `Future` type. In this case, neither `torch.distributed.rpc.Future` nor `torch.jit.Future` look good. What about exposing it as `torch.Future` or `torch.concurrent.Future` or `torch.futures.Future`?

cc @suo @ezyang @SsnL @albanD @zou3519 @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @aazzolini @xush6528 @osalpekar @jjlilley

**Comment by mrshenli** [comment]
cc @nairbv @gchanan

**Comment by albanD** [comment]
I would vote for `torch.Future` if it is really a single class.
If it requires extra functions to work with it, then`torch.futures.*` sounds good.

Also do we have a unified stable API for these?

**Comment by mrshenli** [comment]
> Also do we have a unified stable API for these?

The merge is still ongoing. We have been thinking about keeping it similar to Python's [`concurrent.futures.Future`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future) APIs.

**Comment by mrshenli** [comment]
closed by #39008
