### ISSUE TITLE
Incorrect Type Promotion for torch.pow

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#37673]
Unlike np.power, `torch.pow(int_tensor, float_exponent)` outputs an int tensor instead of a float tensor
```
>>> torch.pow(torch.tensor([1,2]), 2.3)
tensor([1, 4])
>>> torch.pow(torch.tensor([1,2]), 2.3).dtype
torch.int64
>>> np.power(np.array([1,2]), 2.3)
array([1.        , 4.92457765])
>>> np.power(np.array([1,2]), 2.3).dtype
dtype('float64')
```

**Comment by nairbv** [comment]
PR: https://github.com/pytorch/pytorch/pull/37098

Related issue: https://github.com/pytorch/pytorch/issues/32436
