### ISSUE TITLE
convert pytorch model( pytorch_model.bin) to model.pt 

### ISSUE THREAD

**Issue by pumpkinband** [pytorch/pytorch#37708]
i have, PROJECT(folder)
├── pytorch_model.bin
├── bert_config.json
└── vocab.txt

i would like to convert it to model.onnx

thanks a lot.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ngimel** [comment]
Can you please provide a full script reproducing your problem, or ask your question on the forums, discuss.pytorch.org.

**Comment by pumpkinband** [comment]
working on colab
doc (folder)
├── pytorch_model.bin
├── bert_config.json
├── vocab.txt
├──model.ckpt-231879.meta
├──model.ckpt-231879.index
└── model.ckpt-231879.data-00000-of-00001

```
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForNextSentencePrediction, BertForQuestionAnswering
PRE_TRAINED_MODEL_NAME_OR_PATH = 'doc'
model = BertForQuestionAnswering.from_pretrained( PRE_TRAINED_MODEL_NAME_OR_PATH, cache_dir=None, from_tf=False, state_dict=None)
torch.save(model, 'model.pt')
model = torch.load('model.pt')
model.eval()

```
ERROR :- `RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]`

i think i have done something wrong here please help.

**Comment by ngimel** [comment]
This is a question for the forums, closing.
