### ISSUE TITLE
Broken link from "Contribution Guide" to "Governance"

### ISSUE THREAD

**Issue by mathemage** [pytorch/pytorch#37716]
## 📚 Documentation

The link to [PyTorch Governance](https://pytorch.org/docs/source/community/governance.rst) seems to be broken, when accessed from PyTorch Contribution Guide (both on the [master version](https://pytorch.org/docs/master/community/contribution_guide.html#the-pytorch-contribution-process) and the [stable version](https://pytorch.org/docs/stable/community/contribution_guide.html#the-pytorch-contribution-process)).

Though, when [viewing from Github](https://github.com/pytorch/pytorch/blob/master/docs/source/community/contribution_guide.rst#the-pytorch-contribution-process), it does seem to work. But it leads to the [Github `*.rst` version](https://github.com/pytorch/pytorch/blob/master/docs/source/community/governance.rst).

Is this a bug or a desired behaviour?

**Comment by ShawnZhong** [comment]
Maybe related to https://github.com/pytorch/pytorch/pull/30814?

**Comment by ngimel** [comment]
Thanks for reporting, this looks like a bug. We'll accept a PR fixing it.

**Comment by mathemage** [comment]
@ngimel 
The [stable version](https://pytorch.org/docs/stable/community/contribution_guide.html#the-pytorch-contribution-process)) to the broken [PyTorch Governance](https://pytorch.org/docs/source/community/governance.rst).

Is this the desired behaviour? Does `master` version become `stable` once in a while? Hence `stable` would work in the next stable release? (Pardon my ignorance, new to PyTorch ecosystem :-) )

**Comment by ngimel** [comment]
Yes, master version becomes stable when the new release happen, latest pytorch release is 1.5.

**Comment by mathemage** [comment]
> Yes, master version becomes stable when the new release happen, latest pytorch release is 1.5.

@ngimel Thanks! ^_^
