### ISSUE TITLE
dilation for avg_pool

### ISSUE THREAD

**Issue by zjhthu** [pytorch/pytorch#37717]
## 🚀 Feature

It is weird to see current [AvgPool2d](https://pytorch.org/docs/stable/nn.html#torch.nn.AvgPool2d) does not support dilation while [MaxPool2d](https://pytorch.org/docs/stable/nn.html#torch.nn.MaxPool2d) supports, why?
Can pytorch support this feature?

**Comment by zjhthu** [comment]
I just find a similar issue in Dec 2018 #14907

**Comment by ngimel** [comment]
Closing in favor of #14907.
