### ISSUE TITLE
Exception: Operator `conv2d` lost channels_last property

### ISSUE THREAD

**Issue by quinor** [pytorch/pytorch#37725]
## 🐛 Bug

I am following the new memory_format tutorial:
https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html

When running it on a custom convolutional network, I get:
```
`conv2d` got channels_last input, but output is not channels_last: torch.Size([8, 32, 256, 512]) (4194304, 131072, 512, 1) cuda:0 torch.float32
`conv2d` inputs are:
 (4194304, 1, 16384, 32) torch.Size([8, 32, 256, 512]) cuda:0 torch.float32
 (25, 1, 5, 1) torch.Size([32, 1, 5, 5]) cuda:0 torch.float32
 None
 <class 'tuple'>
     1
     1
 <class 'tuple'>
     4
     4
 <class 'tuple'>
     2
     2
 32
```

despite conv2d being said to support `channels_last` property.

## To Reproduce

1. Follow the memory_format tutorial on a convolutional model containing ???
2. ???

## Expected behavior

The `conv2d` should keep the `channels_last` property

## Environment

PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 8.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] pytorch-lightning==0.7.4
[pip3] torch==1.5.0+cu101
[pip3] torchvision==0.6.0+cu101

## Additional context

cc @ngimel @csarofeen @ptrblck @VitalyFedyunin @jamesr66a

**Comment by ngimel** [comment]
cc @VitalyFedyunin @jjsjann123

**Comment by jjsjann123** [comment]
I saw this line in the system `cuDNN version: Could not collect`
what cudnn version do you have? We do have a heuristic that turns off nhwc for conv when cudnn version is low. https://github.com/pytorch/pytorch/blob/5baa6b6c34c9a61c936f90168b6449421814553d/aten/src/ATen/native/ConvUtils.h#L84-L95

**Comment by quinor** [comment]
I am not sure, I think it's the correct version:

```
$ python -c "import torch; print(torch.backends.cudnn.version())"
7603
```

I did not install cudnn by hand (I'm on a cluster) so I'm relying on whatever is shipped with pytorch. The `collect_env.py` script seems to ask `ldconfig` so it's obviously not there.

**Comment by VitalyFedyunin** [comment]
Indeed we are loosing channel last property while dispatching to old code https://github.com/pytorch/pytorch/blob/a0075c4825491b79e54b2d1af8c5ec65789eea5e/aten/src/ATen/native/Convolution.cpp#L673
dispatch decision drived by https://github.com/pytorch/pytorch/blob/a0075c4825491b79e54b2d1af8c5ec65789eea5e/aten/src/ATen/native/Convolution.cpp#L415 code here. 

Easiest way to replicate is:

```python
import torch
import torch.nn.functional as F                                                                                                                                                                                                               
x = torch.rand(200, 24, 56, 56, dtype=torch.float16, device='cuda').to(memory_format=torch.channels_last) 
w = torch.rand(24, 1, 3, 3, dtype=torch.float16, device='cuda').to(memory_format=torch.channels_last) 
r = F.conv2d(x, w, None, (2,2), (1, 1), (1, 1), 24)   
```

I think most rational is to add channels last support to `thnn_conv_depthwise2d` but I wonder what @ptrblck think

**Comment by VitalyFedyunin** [comment]
Potential material for 1.5.1 if we fix it with few lines as in @ptrblck suggestion.

**Comment by dthul** [comment]
I have the same issue on CPU (not using CUDA/cuDNN). I compiled @xwang233's cudnn-conv-channels-last branch, but that does not seem to fix the issue on CPU at least.

**Comment by xwang233** [comment]
@dthul , thanks for the comment! My PR only fix the channels_last convolution problem for cuDNN backend. Convolution on CPU backend goes through another implementation, and may not have channels_last support at this moment (I'm not 100% sure).

**Comment by VitalyFedyunin** [comment]
Channels Last kernels are not implemented yet for cpu, see https://github.com/pytorch/pytorch/wiki/Operators-with-Channels-Last-support
