### ISSUE TITLE
Module doesn't like attributes with "__" prefix 

### ISSUE THREAD

**Issue by Ge0rges** [pytorch/pytorch#37724]
## 🐛 Bug

If you have an attribute in a subclassed module whose name start with two underscores, referencing that object sometimes crashes.

## To Reproduce
Run below code.

```
import torch 

class SampleModel(torch.nn.Module):
    def __init__(self):
        super(SampleModel).__init__()
        self.__attribute = None
    
    def forward(x):
        return x

class SampleManager:
    def __init__(self):
        self.model = SampleModel()

    def crash(self):
        print(self.model.__attribute)


if __name__ == "__main__":
    m = SampleManager()
    m.crash()

```

Stack trace:

```
Traceback (most recent call last):
  File "sample.py", line 21, in <module>
    m.crash()
  File "sample.py", line 16, in crash
    print(self.model.__attribute)
  File "/home/gio/Documents/KNet/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'SampleModel' object has no attribute '_SampleManager__attribute'

```
## Expected behavior

No crash.

## Environment

 - PyTorch Version: 1.5.0
 - OS: Ubuntu 19
 - How you installed PyTorch: pip
 - Python version: 3.7

**Comment by SsnL** [comment]
This is a Python thing. See more about double-underscore attributes here: https://stackoverflow.com/questions/44114560/how-to-access-double-underscore-variables-in-methods-added-to-a-class/
