### ISSUE TITLE
Empty GPU memory cache after Jupyter notebook interrupted

### ISSUE THREAD

**Issue by bluemonk482** [pytorch/pytorch#37726]
## ❓ Questions and Help
I have used one of my GPUs for feature learning on a remote Jupyter Notebook. However the learning processing was interrupted and the network was cut off before I was able to leave the notebook properly, which resulting in the memory cache still lives in that particular GPU, as shown in `nividia-smi`.

+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 30%   28C    P8    22W / 250W |   8525MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

I do have another ongoing training process which uses another GPU. My question is how do I empty the memory cache from the unused GPU w/o affecting the ongoing process? Just to clarify, there is no process using the GPU with the memory cache from the notebook. 

I have tried

```
In [10]: with torch.cuda.device('cuda:7'):
    ...:     torch.cuda.empty_cache()
```

But it did not work.

This is on a computing cluster with Ubuntu 18. I installed pytorch with pip and the version is 1.3.1 because the I am cuda 10. 

Thanks!

**Comment by SsnL** [comment]
jupyter notebook holds reference to the exception when interrupted (for things like %debug), which holds reference to the stack frames, which hold reference to the variables. so empty_cache won't work. this is not really a pytorch issue per se.
