### ISSUE TITLE
Module attributes can't be changed when exporting scripted module to ONNX

### ISSUE THREAD

**Issue by IlyaOvodov** [pytorch/pytorch#37720]
## 🐛 Bug

When module attribute is changed within forward(), such a module can be exported to ONNX directly but it fails it this module is converted to TorchScript.
This problem is a cause of #34002 (specific fix is proposed there, but it does not solve the problem itself

## To Reproduce
```
class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
        self.num_batches_tracked = 0
    def forward(self, x):
        self.num_batches_tracked = 1
        return x
model = MyClass()
img = torch.zeros((2, 3,))
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img) # OK
model = torch.jit.script(model)
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img) # fail
```
->
```
Traceback (most recent call last):
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 320, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(model.forward.graph, model._c)
RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%self, %2)
:
Process finished with exit code 1
```
torch versions: 1.4.0,  1.5.0a0+2dc2933, 1.6.0a0+4ed790d

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by garymm** [comment]
Blocked by #39365

**Comment by braindevices** [comment]
any update on this?

**Comment by ghazalehtrb** [comment]
Is there any progress on this? The model I'm using has an activation buffer that changes in the forward pass.

**Comment by BowenBao** [comment]
Validated original script to be working under latest PyTorch. (Discarding `example_outputs` argument as it's deprecated).

The original issue was filed under torch 1.4. It has been fixed in later releases.

Closing.
