### ISSUE TITLE
"The specified procedure could not be found" importing `caffe2_detectron_ops_gpu.dll` via torch

### ISSUE THREAD

**Issue by ChrisSwinchatt** [pytorch/pytorch#37733]
## 🐛 Bug

* Importing torch results in the above error on Torch 1.50 for CUDA 10.1 and 10.2, plus nightly 10.2 builds when installed via Pip.
* I **have not** tried with other package managers 
* I **have** tried downloading the LibTorch DLLs from pytorch.org, which exhibit the same behaviour
* I **have not** tried building LibTorch from source
* Torch 1.4.0 for CUDA 9.2 **works** even though I have a CUDA 10.2 capable GPU and CUDA 10.2 is installed

## To Reproduce

1. Install Torch 1.5.0 stable or nightly for CUDA 10.2 via Pip on Windows
1. Try to import torch
1. Receive the following error:
```
Traceback (most recent call last):
  File ".\train-ocr.py", line 9, in <module>
    import torch
  File "P:\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "P:\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```

By inserting a print statement in the ctypes.CDLL constructor I've determined that the DLL in question is `caffe2_detectron_ops_gpu.dll`

When I run `objdump.exe` from MSys on this file, it says there are no exported symbols. The DLL distributed with the LibTorch download is the same. I can see the names of some symbols in the DLL in a hex viewer though.

## Expected behavior

Torch would be imported

## Environment

```Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (GCC) 9.3.0
CMake version: version 3.14.5

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 441.22
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.3

[pip3] torch==1.5.0

[pip3] torchvision==0.6.0
[conda] Could not collect```

**Comment by ChrisSwinchatt** [comment]
Unfortunately the reason I upgraded to 1.5.0 was to fix this error:
```
RuntimeError: cuDNN version incompatibility: PyTorch was compiled against 7201 but linked against 7104
```

This is PyTorch 1.4.0 for CUDA 9.2 via Pip, on Python 3.7 on Windows 10 with NVIDIA GTX 1060. CUDA 10.2 is installed.

cuDNN is not installed. CPU training works with PyTorch 1.4.0 (but obviously I didn't get that far with 1.5+).

Should I make a separate issue for this?

**Comment by peterjc123** [comment]
cudnn should be intergrated in the package. Could you please post the files in the torch package using the following command in CMD?
```cmd
tree [directory of your Python installation]\Lib\site-packages\torch
```

**Comment by peterjc123** [comment]
To give more details, you can install Debugging Tools on Windows [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools). And then you can type in the following commands in CMD/powershell.
```powershell
gflags /i python.exe +sls
cdb -o -c "~*g; q" python -c "import torch"
gflags /i python.exe -sls
```

**Comment by ChrisSwinchatt** [comment]
Here is a Gist with all requested information: https://gist.github.com/ChrisSwinchatt/fc946c586991256b13afdf0118844b2d

**Comment by ChrisSwinchatt** [comment]
I noticed it was having problems with the cudnn64_7.dll in my C:\Windows\System32 folder. Replacing it with the one distributed with Torch (~100 MB larger) seems to have fixed it. I'm guessing this is related to having multiple versions of CUDA installed?

**Comment by peterjc123** [comment]
Well, the DLLs in the system dirs are loaded first. We will look into plans to improve this situation.

**Comment by ChrisSwinchatt** [comment]
Thanks for your help @peterjc123, I suppose this can be closed.

**Comment by AsmaZbt** [comment]
hello , i have the same error could you help me please? 

I didn't understand your solution ? 

thank you so much

**Comment by peterjc123** [comment]
@AsmaZbt The easiest solution is to patch `__init__.py` for PyTorch. Please use the modified version (for v1.5.0) [here](https://gist.github.com/peterjc123/bcbf4418ff63d88e11313d308cf1b427).

**Comment by this-is-shashank** [comment]
I didnot get the solution. Can you please elaborate on how to fix it a bit more?

**Comment by peterjc123** [comment]
@this-is-shashank 
I answered your question at https://gist.github.com/peterjc123/bcbf4418ff63d88e11313d308cf1b427#gistcomment-3372140. Please tell me which version of PyTorch are you using.

**Comment by sephorae** [comment]
I get this error OSError: [WinError 127] The specified procedure could not be found. 
I installed pytorch a few days ago and hit this error for the first time today ... so I don't think it's an installation problem...
I am using  torch 1.5.1+cu101 and python 3.8.5 on windows 10 
if someone could help me on this would be glad 
thanks a lot

**Comment by peterjc123** [comment]
@sephorae I don't know what you refers to "installation problem" here. But I can infer from the error message that PyTorch is trying to load a wrong version of the library since it says "The specified procedure could not be found" which means the DLL is found but some function in it is not. The solution are listed below:
1. There may be some old DLLs in the `lib` directory so you may just clean those up by `pip uninstall torch`
2. If that doesn't solve the problem, then there are some conflicting DLLs in your system directory. You could delete them or just patch the `__init__.py` of PyTorch with https://gist.github.com/peterjc123/fb2d75a25afd6fe460114084b9c20bc8, which may help PyTorch finds the correct version of the DLL files.

**Comment by TomArrow** [comment]
I am getting this same error in pytorch 1.10.0. What is the proposed solution? I don't think patching with the old file is a good idea at this point.

**Comment by ElpadoCan** [comment]
I am getting a similar error with pytorch 1.10.1. I am using conda. I tried `conda remove pytorch` and then `conda install -c pytorch pytorch=1.9` and 1.9.1 got installed, but I get the same error. What could be the issue?

**Comment by Giulio-Cusenza** [comment]
I am getting the same error. Is it possible that my pytorch version includes functions with features unsupported by python 3.8? How can I find which pytorch version fits my python version the best?
