### ISSUE TITLE
torch.utils.checkpoint.checkpoint +  torch.cuda.amp fails

### ISSUE THREAD

**Issue by lopuhin** [pytorch/pytorch#37730]
## 🐛 Bug

torch.utils.checkpoint.checkpoint fails when used with torch.cuda.amp on pytorch nightly. They both allow to reduce the memory usage so seem like a natural combination to use together.

## To Reproduce

Here is an example program derived from https://pytorch.org/docs/master/notes/amp_examples.html#typical-mixed-precision-training

```
import torch
from torchvision.models import resnet18

amp_enabled = True
checkpoint_enabled = True
device = torch.device('cuda')

class ResNetWithCheckpoints(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.base = resnet18()

    def forward(self, x):
        base = self.base
        x = base.conv1(x)
        x = base.bn1(x)
        x = base.relu(x)
        x = base.maxpool(x)

        if checkpoint_enabled:
            x = torch.utils.checkpoint.checkpoint(base.layer1, x)
            x = torch.utils.checkpoint.checkpoint(base.layer2, x)
            x = torch.utils.checkpoint.checkpoint(base.layer3, x)
            x = torch.utils.checkpoint.checkpoint(base.layer4, x)
        else:
            x = base.layer1(x)
            x = base.layer2(x)
            x = base.layer3(x)
            x = base.layer4(x)

        x = base.avgpool(x)
        x = torch.flatten(x, 1)
        x = base.fc(x)

        return x

model = ResNetWithCheckpoints()
model.to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
loss_fn = torch.nn.CrossEntropyLoss()
scaler = torch.cuda.amp.GradScaler(enabled=amp_enabled)

xs = torch.randn(5, 3, 128, 128).to(device)
ys = torch.tensor(range(len(xs))).to(device)
for _ in range(20):
    optimizer.zero_grad()
    with torch.cuda.amp.autocast(enabled=amp_enabled):
        ys_pred = model(xs)
        loss = loss_fn(ys_pred, ys)
    print(float(loss))
    scaler.scale(loss).backward()
    scaler.step(optimizer)
    scaler.update()
```

This script fails when both amp and checkpointing are enabled, and does not fail otherwise:

```
7.273253440856934
Traceback (most recent call last):
  File "amp_checkpoint.py", line 51, in <module>
    scaler.scale(loss).backward()
  File "lib/python3.6/site-packages/torch/tensor.py", line 184, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "lib/python3.6/site-packages/torch/autograd/__init__.py", line 115, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

## Expected behavior

I expect it to work with both amp and checkpoint enabled (I also expect memory savings from checkpointing but I'm not yet sure that my example should provide them).

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0.dev20200502+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1050 Ti
GPU 1: GeForce RTX 2080 Ti   (this is the one used here)

Nvidia driver version: 430.50
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.6.0.dev20200502+cu101
[pip3] torchvision==0.7.0.dev20200501+cu101
[conda] Could not collect
```

**Comment by ptrblck** [comment]
Thanks for raising this issue!
My best guess is that [`CheckpointFunction.backward`](https://github.com/pytorch/pytorch/blob/843c0230f2928aad61a6940688da3a6cd6c4cd57/torch/utils/checkpoint.py#L77-L102) uses the stored mixed-precision tensors from its `forward`, but breaks the autocasting contract for the backward.
If you run `scaler.scale(loss).backward()` inside the `autocast` block, it should work for now as a workaround.

CC @mcarilli

**Comment by lopuhin** [comment]
> If you run scaler.scale(loss).backward() inside the autocast block, it should work for now as a workaround.

@ptrblck this works indeed, thank you!

**Comment by kaimingkuang** [comment]
Thanks for the workaround! However, backward with autocast isn't recommended according to PyTorch docs. I wonder why autocast backward isn't a recommended practice? And why in this particular case it is safe to do so?

**Comment by jareturing** [comment]
I have the same issure. when i use torch.utils.checkpoint.checkpoint + torch.cuda.amp in my project, RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same. run scaler.scale(loss).backward() inside the autocast block,

**Comment by neonbjb** [comment]
Running backward() inside of the autocast block does not work for me, it causes CUDA to run OOM. It seems that autocast does some caching which defeats the memory-saving purposes of checkpointing. Probably for smaller models this issue does not present itself.

A rather unsavory workaround is to edit torch's checkpoint.py. Add "with torch.cuda.amp.autocast():" before this line:
https://github.com/pytorch/pytorch/blob/master/torch/utils/checkpoint.py#L95

This has unblocked me, but sucks because now am forced to run in autocast mode without further modifications to the torch library.

**Comment by mcarilli** [comment]
Can you check if https://github.com/pytorch/pytorch/pull/40221's diffs resolve the issue?

**Comment by mcarilli** [comment]
Should be fixed after https://github.com/pytorch/pytorch/pull/49757, if not, please reopen and tag me.
