### ISSUE TITLE
Exception: Operator `conv2d` lost channels_last property

### ISSUE THREAD

**Issue by lvjunsetup** [pytorch/pytorch#37732]
I am following the new memory_format tutorial:
https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html

When running it on a custom convolutional network, I get:

`conv2d` got channels_last input, but output is not channels_last: torch.Size([8, 32, 256, 512]) (4194304, 131072, 512, 1) cuda:0 torch.float32
`conv2d` inputs are:
 (4194304, 1, 16384, 32) torch.Size([8, 32, 256, 512]) cuda:0 torch.float32
 (25, 1, 5, 1) torch.Size([32, 1, 5, 5]) cuda:0 torch.float32
 None
 <class 'tuple'>
     1
     1
 <class 'tuple'>
     4
     4
 <class 'tuple'>
     2
     2
 32
despite conv2d being said to support channels_last property.

To Reproduce

Follow the memory_format tutorial on a convolutional model containing ???
???
Expected behavior
The conv2d should keep the channels_last property

Environment
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 8.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] pytorch-lightning==0.7.4
[pip3] torch==1.5.0+cu101
[pip3] torchvision==0.6.0+cu101

**Comment by ptrblck** [comment]
Thanks for raising this issue.
This might be probably related to https://github.com/pytorch/pytorch/issues/37725.

I tried to reproduce it using PyTorch `1.5.0`, CUDA10.1, cudnn7604 (installed from the binaries) and the code works fine on an MX150.

Did you build PyTorch from source or have you also used the binaries?

CC @jjsjann123 @VitalyFedyunin

**Comment by quinor** [comment]
I am pretty sure this issue is a text copy of my issue (the one you linked to). I had installed it using pip.

@ptrblck I can try and provide you with more details if you tell me what you need. I could also share my code that led to this issue - I just don't wanna do it publictly.

**Comment by ngimel** [comment]
I'm closing this in favor of #37725, please continue discussion there.

**Comment by lvjunsetup** [comment]
> I'm closing this in favor of #37725, please continue discussion there.

thank you！

**Comment by lvjunsetup** [comment]
> Thanks for raising this issue.
> This might be probably related to #37725.
> 
> I tried to reproduce it using PyTorch `1.5.0`, CUDA10.1, cudnn7604 (installed from the binaries) and the code works fine on an MX150.
> 
> Did you build PyTorch from source or have you also used the binaries?
> 
> CC @jjsjann123 @VitalyFedyunin

Thank you, I did not compile and install from source.

**Comment by lvjunsetup** [comment]
> I am pretty sure this issue is a text copy of my issue (the one you linked to). I had installed it using pip.
> 
> @ptrblck I can try and provide you with more details if you tell me what you need. I could also share my code that led to this issue - I just don't wanna do it publictly.

thank you！
