### ISSUE TITLE
PyTorch 1.5 conda package disallows OpenBLAS 

### ISSUE THREAD

**Issue by iutlu** [pytorch/pytorch#37746]
## 🐛 Bug

On one of our Linux machines I discovered that (unrelated to PyTorch) a third-party library is crashing under a conda environment with MKL. So I updated the environment.yml file to require OpenBLAS instead -- only to discover that PyTorch 1.5 causes dependency errors in this new environment.

I've inspected the packages and basically the reason is that PyTorch 1.5 appears to have started listing MKL BLAS as a dependency (at least on Linux x64). Compare:

PyTorch 1.4:
```
"depends": [
  "cudatoolkit >=10.1,<10.2",
  "mkl >=2018",
  "ninja",
  "numpy >=1.11",
  "python >=3.7,<3.8.0a0"
],
```

PyTorch 1.5:
```
"depends": [
  "blas * mkl",
  "cudatoolkit >=10.1,<10.2",
  "mkl >=2018",
  "ninja",
  "numpy >=1.11",
  "python >=3.7,<3.8.0a0"
],
```

I've skimmed the release notes for v1.5, and did not notice any change that could suggest this. Is this intended? For reference, PyTorch 1.4 works fine with `blas=2.16=openblas` from conda-forge.

## To Reproduce

1. Run `conda create -n test python=3.7 pytorch=1.5 blas=*=openblas -c pytorch`, which fails
2. whereas `conda create -n test python=3.7 pytorch=1.4 blas=*=openblas -c pytorch` is OK

cc @ezyang @seemethere @malfet

**Comment by seemethere** [comment]
The pull request that added this is here: https://github.com/pytorch/builder/pull/399

Perhaps @isuruf can give us some insight as to why this was necessary to make PyTorch packages compatible with conda-forge?

**Comment by isuruf** [comment]
I believe it was @soumith who complained that conda-forge was using non-MKL builds with PyTorch and that he didn't want non-MKL builds with PyTorch when using conda-forge.

**Comment by soumith** [comment]
yes, MKL is a hard-dependency for PyTorch conda packages, it uses MKL API beyond BLAS/LAPACK as well, like for fft.

**Comment by soumith** [comment]
we didn't have the dependencies encoded correctly before, and thanks to @isuruf it is fixed now.

**Comment by iutlu** [comment]
Understood, thank you for the info 👍

**Comment by ekerazha** [comment]
@soumith 
This makes the conda package unsuitable for AMD CPUs, as Intel MKL uses a slow code path for AMD processors. For broader hardware compatibility and to avoid vendor lock-in, OpenBLAS should be used instead.
