### ISSUE TITLE
Windows 10 Libtorch installation issue.

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/pytorch#37741]
Hello Folks,

I am trying to run this [doc example](https://pytorch.org/cppdocs/installing.html#minimal-example)

I have MS Visual Studio 2019 and Cmake version 3.14 installed.
I have downloaded both release as well as debug zips and extracted them in `C:\Program Files x86`. 

I have made the folder and CMakeLists.txt file as said.

```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(example-app)

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)

# The following code block is suggested to be used on Windows.
# According to https://github.com/pytorch/pytorch/issues/25457,
# the DLLs need to be copied to avoid memory errors.
if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET example-app
                     POST_BUILD
                     COMMAND ${CMAKE_COMMAND} -E copy_if_different
                     ${TORCH_DLLS}
                     $<TARGET_FILE_DIR:example-app>)
endif (MSVC)
```

On Building I am getting the following error.

![image](https://user-images.githubusercontent.com/47158509/80924585-5eef0900-8da7-11ea-837a-3553500d11dd.png)

Any fix for this issue ?
Is there anything that documentation has missed out or I have missed ?

**Comment by oke-aditya** [comment]
Similar Issues do exist #12449. There seems to be no proper solution. 
Can I have a proper CMakeLists.txt file and proper documentation of how should it run with Windows and CMake.

**Comment by oke-aditya** [comment]
Okay. I resolved it myself. 👍 
The tutorial needs to add this line in CMakeLists.txt file
``` set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch") ```

which should point to where Torch is unzipped appropriately.
Please update the docs. This issue is quite prelevant

**Comment by oke-aditya** [comment]
```cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(custom_ops)
set(CMAKE_PREFIX_PATH "C:/Program Files (x86)/libtorch/libtorch_release/share/cmake/Torch")
find_package(Torch REQUIRED)

add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)

if (MSVC)
    file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
    add_custom_command(TARGET example-app
                 POST_BUILD
                 COMMAND ${CMAKE_COMMAND} -E copy_if_different
                 ${TORCH_DLLS}
                 $<TARGET_FILE_DIR:example-app>)
endif (MSVC)```

This is the proper CMakeLists.txt file. Please correct it.

**Comment by peterjc123** [comment]
> Similar Issues do exist #12449. There seems to be no proper solution.
> Can I have a proper CMakeLists.txt file and proper documentation of how should it run with Windows and CMake.

It seems that you typed an additional space between `-DCMAKE_PREFIX_PATH` and the value, so the argument is not properly propagated.

**Comment by peterjc123** [comment]
> Okay. I resolved it myself. 👍
> The tutorial needs to add this line in CMakeLists.txt file
> `set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch")`
> 
> which should point to where Torch is unzipped appropriately.
> Please update the docs. This issue is quite prelevant

I don't think that's the case because I just tried that three days ago in https://github.com/pytorch/pytorch/issues/37124#issuecomment-622288331.

**Comment by peterjc123** [comment]
I don't think it's a bug. However, if you disagree, please feel free to reopen it.

**Comment by oke-aditya** [comment]
No, it isn't a bug in Libtorch package. It isn't mentioned in PyTorch docs about the Set() 
Also, the Cmake file isn't quite complete and needs to be updated. Maybe new users don't know about it.

``` set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch") ```

[here](https://pytorch.org/tutorials/advanced/cpp_export.html) as well as [here](https://pytorch.org/tutorials/advanced/cpp_frontend.html)

The CMake file needs to be clear in the documentation. It is causing trouble for many people.
#12449 #21976 #806 #12449

It's not a bug. But a doc improvement issue.

**Comment by oke-aditya** [comment]
I have created a new issue under docs section #37766. I initially thought it was a bug.

**Comment by peterjc123** [comment]
I mean `set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch")` should not be needed. Could you please try `-DCMAKE_PREFIX_PATH=[path to libtorch]"` again (in a new folder perhaps)? I could not reproduce this bug so I'm just curious about the cause.

**Comment by oke-aditya** [comment]
I have tried. But it didn't work instead threw me an error

> 
> 
> Hello Folks,
> 
> I am trying to run this [doc example](https://pytorch.org/cppdocs/installing.html#minimal-example)
> 
> I have MS Visual Studio 2019 and Cmake version 3.14 installed.
> I have downloaded both release as well as debug zips and extracted them in `C:\Program Files x86`.
> 
> I have made the folder and CMakeLists.txt file as said.
> 
> ```
> cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
> project(example-app)
> 
> find_package(Torch REQUIRED)
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
> 
> add_executable(example-app example-app.cpp)
> target_link_libraries(example-app "${TORCH_LIBRARIES}")
> set_property(TARGET example-app PROPERTY CXX_STANDARD 14)
> 
> # The following code block is suggested to be used on Windows.
> # According to https://github.com/pytorch/pytorch/issues/25457,
> # the DLLs need to be copied to avoid memory errors.
> if (MSVC)
>   file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
>   add_custom_command(TARGET example-app
>                      POST_BUILD
>                      COMMAND ${CMAKE_COMMAND} -E copy_if_different
>                      ${TORCH_DLLS}
>                      $<TARGET_FILE_DIR:example-app>)
> endif (MSVC)
> ```
> 
> On Building I am getting the following error.
> 
> ![image](https://user-images.githubusercontent.com/47158509/80924585-5eef0900-8da7-11ea-837a-3553500d11dd.png)
> 
> Any fix for this issue ?
> Is there anything that documentation has missed out or I have missed ?

I tried that as well. It gave me this error.

**Comment by oke-aditya** [comment]
It could not find torch until I explicitly set it. :( But now everything is working fine after it.

**Comment by peterjc123** [comment]
That's weird. I don't have to do that on my local PC. But I'll try to see if a directory with space is the problem.

**Comment by DineshRajanT** [comment]
> It could not find torch until I explicitly set it. :( But now everything is working fine after it.

@oke-aditya  How did u set the torch path?

**Comment by oke-aditya** [comment]
Have a look at #12449.

```
Add this in your CMakeLists.txt file before find_package(Torch REQUIRED)
set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch")

Which should point to where Torch is unzipped appropriately.
Please update the docs. This issue is quite prelevant.
```

This solved for me

**Comment by DineshRajanT** [comment]
> Have a look at #12449.
> 
> ```
> Add this in your CMakeLists.txt file before find_package(Torch REQUIRED)
> set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch")
> 
> Which should point to where Torch is unzipped appropriately.
> Please update the docs. This issue is quite prelevant.
> ```
> 
> This solved for me

cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(example-app)
set(CMAKE_PREFIX_PATH "Z:/PhospheneAI/Inference/libtorch-win-shared-with-deps-1.7.1%2Bcu110/libtorch/share/cmake/Torch")
set(Torch_DIR "Z:/PhospheneAI/Inference/libtorch-win-shared-with-deps-1.7.1%2Bcu110/libtorch/share/cmake/Torch")

find_package(Torch REQUIRED)

add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)

if (MSVC)
    file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
    add_custom_command(TARGET example-app
                 POST_BUILD
                 COMMAND ${CMAKE_COMMAND} -E copy_if_different
                 ${TORCH_DLLS}
                 $<TARGET_FILE_DIR:example-app>)
endif (MSVC)  

Now this is my file
I am still getting the error @oke-aditya

**Comment by oke-aditya** [comment]
I cannot really debug this also I cannot reproduce such error.
Can you open issue on the PyTorch forums https://discuss.pytorch.org/ ?
Maybe people can help from there.

**Comment by peterjc123** [comment]
@DineshRajanT Please try removing the special characters (e.g. % ) from the directory.
