### ISSUE TITLE
DataLoader.__len__ for IterableDataset

### ISSUE THREAD

**Issue by tmbdev** [pytorch/pytorch#37753]
## 🐛 Bug

The logic for `__len__` on `IterableDataset` doesn't seem right to me in the general case, since it seems to ignore the batch_size entirely. [code](https://github.com/pytorch/pytorch/blob/843c0230f2928aad61a6940688da3a6cd6c4cd57/torch/utils/data/dataloader.py#L297)

The current logic is correct when `batch_size` is `None`, but when it is something other than `None` or 1, it isn't even approximately correct. Furthermore, while the comment suggests that the `Dataset` should return the correct length, the `Dataset` doesn't know the `batch_size`.

## To Reproduce

```
import torch
import torch.utils.data as data

class MyDataset(object):
    def __init__(self):
        super().__init__()
        self.n = 1000000
    def __len__(self):
        return self.n
    def __getitem__(self, index):
        return torch.zeros((99, 99)), torch.zeros((99, 99))
            
dataset = MyDataset()
loader = data.DataLoader(dataset, batch_size=128)
print(len(dataset), len(loader))

class MyDataset2(data.IterableDataset):
    def __init__(self):
        super().__init__()
        self.n = 1000000
    def __len__(self):
        return self.n
    def __iter__(self):
        for i in range(self.n):
            yield torch.zeros((99, 99)), torch.zeros((99, 99))
            
dataset2 = MyDataset2()
loader = data.DataLoader(dataset2, batch_size=128)
print(len(dataset), len(loader))
```

Output:
```
1000000 7813
1000000 1000000
```

## Expected behavior

The two datsets should behave the same way, but they output wildly different lengths for the dataloader; this is also what PyTorch Lightning expects. The length of the dataloader should be the number of batches returned by it, but it obviously is not.

## Environment

```
Collecting environment information...
PyTorch version: 1.5.0a0+8f84ded
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.18.1
[pip3] pytorch-lightning==0.7.5
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.5.0a0+8f84ded
[pip3] torchmore==0.1.0
[pip3] torchtext==0.4.0
[pip3] torchvision==0.6.0a0
[conda] Could not collect
```

## Additional context

The current logic is mostly correct if `batch_size` is None, that is, if the `IterableDataset` itself performs batching. But it seems to me that the reason for allowing a `DataLoader` to be instantiated with an `IterableDataset` in the first place is so that existing code using `DataLoader` doesn't have to be changed significantly; however, that existing code does usually set a `batch_size` on the `DataLoader` triggering this problem. In other words, the way it is, it's not possible to write an `IterableDataset` that can replace a `Dataset` without special-casing the code around the invocation of `DataLoader`.

The `__len__` method on the `DataLoader` seems to be used mainly for progress bars. Yet, the unit tests and the internal checks seem to be assuming an exact computation of length. Exact lengths can be very costly to determine in general for `IterableDataset` (though reasonable estimates are usually available).

My recommendation in the short term would be the following:

- (for unusual circumstances) allow the user to set the number of batches explicitly (`DataLoader(..., length=...)`)
- (normal case) if the number of batches is not given by the user, return len(dataset) if batch_size is None, and len(dataset)//batch_size otherwise
- make it clear that `len(loader)` is only approximate, and mainly useful for progress bars
- drop the checks that test for exact correspondence of incoming samples and outgoing batches

I believe this would be backwards compatible, but it would also handle the case where `batch_size` is not `None` well enough for progress bars.

I can try to generate a pull request if this sounds good to you.

(Long term, it might be worth looking into how the code can be refactored without breaking existing code that depends on `DataLoader` internals, while also making this easier to maintain and port. I have done something like that for an older version of PyTorch and it was efficient and probably more easily extensible.)

**Comment by choidongyeon** [comment]
@tmbdev Are you still working on this? If not, I'd love to work on it.

**Comment by SsnL** [comment]
@choidongyeon I think this has been resolved by your patch.
