### ISSUE TITLE
Missing arg in documentation

### ISSUE THREAD

**Issue by danpovey** [pytorch/pytorch#37752]
The documentation for the out-of-place version of index_add and other similar functions like index_copy appears to be missing the first argument; these functions accept 4 arguments, not 3.

https://github.com/pytorch/pytorch/blob/e26631b33332e7409ac799470b3a4b50b4a8bdc4/torch/_tensor_docs.py#L3550

**Comment by ngimel** [comment]
Thank you for reporting, we'll accept a PR fixing that.

**Comment by danpovey** [comment]
How about replacing
```
index_add(dim, index, tensor) -> Tensor
Out-of-place version of :meth:`torch.Tensor.index_add_`
```
with
```
index_add(tensor1, dim, index, tensor2) -> Tensor
Out-of-place version of :meth:`torch.Tensor.index_add_`;  `tensor1` corresponds
to `self` in :meth:`torch.Tensor.index_add_`.
```

**Comment by ngimel** [comment]
Sounds good.
