### ISSUE TITLE
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory ( torch_geometric/utils/loop.py)

### ISSUE THREAD

**Issue by AugF** [pytorch/pytorch#37757]
## 🐛 Bug
when I use 'nsys' to profile torch's code, get this bug:
```
File "/home/xxx/anaconda3/envs/pyg/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 132, in add_remaining_self_loops
    edge_weight = torch.cat([edge_weight[mask], loop_weight], dim=0)
RuntimeError: Error in dlopen or dlsym: libcaffe2_nvrtc.so: cannot open shared object file: No such file or directory: 
```
command
```
nsys profile -t cuda,osrt,nvtx -o baseline -e LD_LIBRARY_PATH -w true python gcn/train_cora.py
```
tried use the way in https://github.com/pytorch/pytorch/issues/31554#issue-541403748, that is `export LD_LIBRARY_PATH=/home/xxx/anaconda3/envs/pyg/lib/python3.8/site-packages/torch:${LD_LIBRARY_PATH} ` , but failed.
## Environment

```
Linux
Anaconda3-2019.10-Linux-x86_64.sh
torch 1.5.0
python 3.8
cuda 10.1
torch_geometric 1.4.3
```

**Comment by ngimel** [comment]
This is a bug in nsys, you are probably using an old version. If you can run your pytorch script without nsys, it is not a pytorch bug.

**Comment by DelightRun** [comment]
@AugF `LD_LIBRARY_PATH` should be `/home/xxx/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/lib:${LD_LIBRARY_PATH}. 
There should be a `/lib` after `site-packages/torch/`
