### ISSUE TITLE
Better testing on CPUs without AVX capabilities

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#37786]
https://github.com/pytorch/pytorch/issues/37577 is the latest occurrence of cases where we broke users with non-AVX CPUs because we accidentally let AVX instructions sneak in to code that isn't guarded by DispatchStub. It would be good to actually test for this case.

According to @colesbury, there are no x86 CPUs on AWS that don't support AVX.

Another test we could do is a limited test to see if our static initializers have any AVX instructions, or files that aren't explicitly intended to be AVX/AVX2 compiled. This might be hard to do robustly.

Possibly related https://github.com/pytorch/pytorch/issues/22338

cc @malfet @VitalyFedyunin

**Comment by malfet** [comment]
MacPro’s CircleCI is using do not have AVX2 support (this is how I’ve discovered the issue in DistributionHelpers.h)
I wonder why this one wasn’t caught by CI on MacOS

**Comment by colesbury** [comment]
Do the MacPro's have AVX support? For #37577, the global initializer was in a file compiled with AVX2 enabled, but I think it only contained AVX instructions (vmovaps, vmovdqa, vzeroupper).

**Comment by malfet** [comment]
Yes, it supports AVX, but not AVX2.
I wonder if it's possible to use CPUs performance counters to check that no no AVX or AVX2 instructions are issued during the runtime, when test is invoked with `ATEN_CPU_CAPABILITY=native`

There are bunch of perf counters that could be of use, see https://download.01.org/perfmon/index/ivytown.html

**Comment by colesbury** [comment]
That's an interesting idea. I think it would be difficult because things like `memset` and `memcpy` will internally use AVX instructions on CPUs that support it. `ATEN_CPU_CAPABILITY` won't affect libraries that have their own CPU feature detection (like glibc or MKL).

**Comment by malfet** [comment]
In that case we can run cpp tests under quemu, which can be configured not to support any vecorized instructions.

**Comment by zou3519** [comment]
I attempted importing PyTorch in "user-space" qemu and it appears to segfault. I'm still investigating but not sure what is up; importing things like numpy works
```
(/scratch/rzou/pt/workspace-env) [139] rzou@devfair0317:/scratch/rzou/pt/workspace (workspace) $ qemu-x86_64 $(which python)
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Python 3.7.5 (default, Oct 25 2019, 15:51:11)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

**Comment by malfet** [comment]
@zou3519 can you please share backtrace from coredump here? And have you used 1.5.0 release or your local build?

**Comment by malfet** [comment]
I didn't know `qemu` supports usermode now.
And looks like it automagically works:
```
$ qemu-x86_64 -E ATEN_CPU_CAPABILITY=default ./bin/basic  --gtest_filter=BasicTest.BasicTestCPU
Running main() from ../third_party/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = BasicTest.BasicTestCPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BasicTest
[ RUN      ] BasicTest.BasicTestCPU
Unsupported ioctl: cmd=0xffffffffc04846d2
   415 ms
   563 ms
[       OK ] BasicTest.BasicTestCPU (1141 ms)
[----------] 1 test from BasicTest (1145 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1148 ms total)
[  PASSED  ] 1 test.
$ qemu-x86_64 -E ATEN_CPU_CAPABILITY=avx ./bin/basic  --gtest_filter=BasicTest.BasicTestCPU
Running main() from ../third_party/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = BasicTest.BasicTestCPU
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BasicTest
[ RUN      ] BasicTest.BasicTestCPU
Unsupported ioctl: cmd=0xffffffffc04846d2
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)
```
