### ISSUE TITLE
Add API documents for TensorPipeRpcBackendOptions when the implementation is ready

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#37783]
The pybind-exposed `TensorPipeRpcBackendOptions` in `rpc/init.cpp` should include proper documents to explain the API.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby

**Comment by lw** [comment]
I think this has been done, right? Please reopen if not.
