### ISSUE TITLE
saved_tensors attribute for grad_fn

### ISSUE THREAD

**Issue by diefimov** [pytorch/pytorch#3778]
Hi,

This script for graph visualization worked on previous versions: https://github.com/szagoruyko/functional-zoo/blob/master/visualize.py
For the latest version the visualized graph shows just variables, but not saved tensors. Could you please advise how can saved tensors for neural network computational graph be accessed now (before we could use attribute saved_tensors in grad_fn)?

Thanks,
Dmitry

**Comment by fmassa** [comment]
I think now (or soon?) it might be better to export the model to ONNX and then use the visualization tool they provide to inspect the graph?

**Comment by ezyang** [comment]
ONNX export is still functional, we still might need to figure out how to do a layer-by-layer export.

**Comment by fmassa** [comment]
If I understand correctly, a layer by layer export visualization is possible once scopes are integrated, so that we can group everything under the same scope/module?

**Comment by diefimov** [comment]
Modification of this code [net_drawer.py](https://github.com/caffe2/caffe2/blob/master/caffe2/python/net_drawer.py) works pretty well for me:

```
class Net(nn.Module):
    def __init__(self, input_shape):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(input_shape, 100)
        self.dropout1 = nn.Dropout(p=0.1)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(100, 200)
        self.dropout2 = nn.Dropout(p=0.1)
        self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(200, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        output = self.linear1(x)
        output = self.dropout1(output)
        output = self.relu1(output)
        output = self.linear2(output)
        output = self.dropout2(output)
        output = self.relu2(output)
        output = self.linear3(output)
        output = self.sigmoid(output) 
        return output

net = Net(X_train.shape[1])
net.cuda()
inputs = Variable(torch.FloatTensor(128,X_train.shape[1])).cuda()
outputs = net(inputs)
torch.onnx.export(net, inputs, "pytorch_model.proto", verbose=True)

model = ModelProto()
with open("pytorch_model.proto", 'rb') as fid:
    content = fid.read()
    model.ParseFromString(content)
pydot_graph = GetPydotGraph(
    model.graph,
    name=model.graph.name,
    rankdir="LR",
    node_producer=GetOpNodeProducer(
        embed_docstring=False,
        **OP_STYLE
    ),
)
pydot_graph.write_dot("pytorch_model.dot")

```

The visualization is attached.
![pytorch_model](https://user-images.githubusercontent.com/4885361/33102067-f09c3734-cf12-11e7-80a3-701665f99349.png)
