### ISSUE TITLE
关于下载地址的请求Request for download address

### ISSUE THREAD

**Issue by luzhiguang** [pytorch/pytorch#37806]
https://nvidia.box.com/v/torch-stable-cp36-jetson-jp42
您好，我在中国，由于网络环境原因，这个地址的网站无法打开下载，请问有备用下载地址吗？
Hello, I am in China. Due to the network environment, the website at this address cannot be opened for download. Is there an alternative download address?

**Comment by ngimel** [comment]
Please ask questions on the forums, discuss.pytorch.org
