### ISSUE TITLE
at::native::copy_impl causes a SegFault if iter.device_type(1) == kHIP

### ISSUE THREAD

**Issue by mergian** [pytorch/pytorch#37819]
## 🐛 Bug

```at::native::copy_imp``` (https://github.com/pytorch/pytorch/blob/v1.5.0/aten/src/ATen/native/Copy.cpp#L89) accepts to process tensors of device_type kCPU, kCUDA, kHIP (see https://github.com/pytorch/pytorch/blob/v1.5.0/aten/src/ATen/native/Copy.cpp#L79). To support device to host memcopies, the method checks if the source tensor is located on kCUDA (see  https://github.com/pytorch/pytorch/blob/v1.5.0/aten/src/ATen/native/Copy.cpp#L142). In this case, it uses ```copy_kernel_cuda``` instead of ```copy_kernel```. However, if ```iter.device_type(1)``` is kHIP also ```copy_kernel``` will be executed, resulting in a segfault, as it would try to access a HIP device pointer from the CPU.

## Expected behavior
```cpp
DeviceType device_type = iter.device_type(0);
if (iter.device_type(1) == kCUDA) {
	device_type = kCUDA;
} else if(iter.device_type(1) == kHIP) {
	device_type = kHIP;
}
```

or more generic

```cpp
DeviceType device_type = iter.device_type(0);
if (iter.device_type(1) != kCPU) {
	device_type = iter.device_type(1);
}
```

## Environment
 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): CentOS
 - How you installed PyTorch (`conda`, `pip`, source): pip3
 - Python version: 3.6

**Comment by mruberry** [comment]
Thank you for reporting this issue, @mergian! We would accept a PR fixing this.
