### ISSUE TITLE
Is there a precompiled version of torchlib for x86?

### ISSUE THREAD

**Issue by sierenavg** [pytorch/pytorch#37817]
I transferred my pytorch model from python to vs2017 x64 system successfully by using the great precompiled dll. However, i can't use the same dll on x86 system and i can't find any precompiled x86 dll as well. I really need (c10.lib,torch.lib,torch_cpu.lib) x86 version, so i can deploy my model. Can any pro save the day? Thank you very very much.

**Comment by peterjc123** [comment]
No, and there's no plan for providing those for x86 environment currently. However, you can build it on your own. If we see sufficient user requests, then we may reconsider.

**Comment by sierenavg** [comment]
Thank you for answering

**Comment by mordecaihamo** [comment]
Is there any change here?
