### ISSUE TITLE
tensor.max(other) not documented

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#3784]
The `torch.max(tensor, other)` is documented. But the one defined on tensor is not.

**Comment by zou3519** [comment]
Does it make sense to have `tensor.max(other)`? It's hard to tell that what this does is take pairwise max over `tensor` and `other`.

**Comment by SsnL** [comment]
Maybe we should just disable that.

**Comment by ezyang** [comment]
Documented now: https://pytorch.org/docs/stable/tensors.html#torch.Tensor.max
