### ISSUE TITLE
Issue with ibverbs support

### ISSUE THREAD

**Issue by OnezeroW** [pytorch/pytorch#3787]
I tried the script in [https://github.com/pytorch/examples/blob/master/imagenet/main.py](https://github.com/pytorch/examples/blob/master/imagenet/main.py)
to train resnet50 on imagenet dataset. The default backend is gloo when trained on multiple GPUs. Just as the following code
`parser.add_argument('--dist-backend', default='gloo', type=str, help='distributed backend')`.
I know that Pytorch use Gloo TCP by default. I wonder how to enable IBVERBS. Should I compile the gloo with `GLOO_USE_IBVERBS=ON`?

**Comment by zjoe** [comment]
I found a patch [here](https://github.com/pytorch/pytorch/pull/2903), which add ibverbs support for gloo. However I didn't get it work, you may have a try.

**Comment by ailzhang** [comment]
@OnezeroW  @zjoe  NCCL2 backend could automatically pick up infiniband support. The patch should also work for compiling ibverbs support for gloo. 
@zjoe Happy to help if you have any trouble using the patch.

**Comment by teng-li** [comment]
I think this issue is good to be closed @OnezeroW
