### ISSUE TITLE
Support @property decorator in TorchScript

### ISSUE THREAD

**Issue by brian112358** [pytorch/pytorch#37883]
## 🚀 Feature
Currently, trying to use a `@property`-decorated method in TorchScript results in the following error:
```
(This attribute exists on the Python module, but it's an @property method. @property methods are not yet supported in TorchScript. Please file a feature request on Github):
```

It would be useful to support `@property` decorated methods in TorchScript rather than throwing the error.

## Motivation

When implementing a `nn.Module`, it is useful to be able to distinguish between publicly-accessible instance variables and internal instance variables. Using the `@property` decorator is a useful way to distinguish between the two.

## Pitch

Support the `@property` decorator for methods called within TorchScript. For example:

```
import torch
from torch import nn

class Foo(nn.Module):
  def __init__(self, bar: int):
    super().__init__()
    self._bar = bar

  @property
  def bar(self) -> int:
    return self._bar

  def forward(self, input: torch.Tensor) -> torch.Tensor:
    return input + self.bar

foo = Foo(3)
torch.jit.script(foo)
```

Currently, running the above returns the following error:
```
RuntimeError: 
Module 'Foo' has no attribute 'bar' 
(This attribute exists on the Python module, but it's an @property method. @property methods are not yet supported in TorchScript. Please file a feature request on Github):
  File "<ipython-input-7-5327862aa311>", line 14
  def forward(self, input: torch.Tensor) -> torch.Tensor:
    return input + self.bar
                   ~~~~~~~~ <--- HERE
```

Adding support for `@property` methods would fix this error when calling `torch.jit.script`.

## Alternatives

Several alternatives are:
1. Avoid using the `@decorator` methods in any scripted methods, and use the internal variables (e.g. `self._bar` here) instead. However, this is poor practice when other classes / modules want to access the `@decorator` instance variable, since we are bypassing the `@decorator` public API.
2. Use instance variables instead of `@decorator` methods (e.g. `self.bar = bar` in the `__init__()` function above).

I am currently using alternative 1, but am running into issues where I need to access the internal instance variables, where I would like to use the `@decorator` public method.

## Additional context

N/A

cc @suo

**Comment by roytseng-tw** [comment]
Is this functionality supported now?

**Comment by randolf-scholz** [comment]
@SplitInfinity It doesn't seem to work at all, please reopen.

```python
import torch
from torch import Tensor, jit, nn


class Foo(nn.Module):
    @property
    def bar(self) -> Tensor:
        return torch.tensor(1)


model = Foo()
print(model.bar)  # <- tensor(1)
scripted_model = jit.script(model)
print(scripted_model.bar)  # <- <property object>
jit.save(scripted_model, "model.pt")
reloaded_model = jit.load("model.pt")
print(reloaded_model.bar)  # AttributeError
```

**Comment by justusschock** [comment]
I have seen the same with https://github.com/Lightning-AI/lightning/issues/13887

After looking around a bit, it seems that the code from https://github.com/pytorch/pytorch/blob/master/torch/jit/_script.py#L432 is missing for modules. Would adding this be a suitable solution @SplitInfinity @eellison @zdevito ?

**Comment by randolf-scholz** [comment]
One issue here is that properties need to be defined on a per-class level, but Torchscript always returns the same class type, no matter the input Module type. So adding the property to the `RecursiveScriptModule` dynamically is problematic.

This seems like a weird design choice to be honest, why doesn't TS dynamically create subclasses of RecursiveScriptModule instead?

Alternatively, property access could be handled through `RecursiveScriptModule.__getattr__` and `RecursiveScriptModule.__setattr__`. However, here one needs to be careful that the property does not get lost through serialization.

**Comment by janeyx99** [comment]
TorchScript has been deprecated in favor of torch.export as of 2.11. https://pytorch.org/blog/pytorch-2-11-release-blog/ Closing this issue as we are not further developing on it--please ping if you believe this issue was erroneously closed.
