### ISSUE TITLE
broadcasting behaves differently on CPU and GPU

### ISSUE THREAD

**Issue by hitvoice** [pytorch/pytorch#3789]
GRUCell and LSTMCell on GPU do not support broadcasting, while RNNCell supports broadcasting on both CPU and GPU. This inconsistency is not expected and not documented.

Here's the example code:
```python
import torch
import torch.nn as nn
from torch.autograd import Variable

rnn = nn.RNNCell(10, 20)
gru = nn.GRUCell(10, 20)
input = Variable(torch.randn(3, 10))
h0 = Variable(torch.randn(1, 20)) # this should be (3, 20)
# both cells support broadcasting on CPU
hx_rnn = rnn(input, h0)
hx_gru = gru(input, h0)
assert hx_rnn.size() == hx_gru.size()

# send models and variables to GPU
rnn.cuda()
gru.cuda()
input = input.cuda()
h0 = h0.cuda()

# RNNCell is OK
try:
    hx_rnn_cuda = rnn(input, h0)
except RuntimeError as e:
    print('rnn error\n', e)

# GRUCell on GPU does not support broadcasting
try:
    hx_gru_cuda = gru(input, h0)
except RuntimeError as e:
    print('gru error\n', e)
```
The output of this example is:
```
gru error
invalid argument 3: Input and Hidden tensor sizes should be the same. at /pytorch/torch/lib/THCUNN/generic/FusedRNNKernel.cu:19
```

Is this a known issue or not expected?

**Comment by hitvoice** [comment]
Testing environment:
- Ubuntu 16.04 LTS
- CUDA 8.0.61 (GeForce GTX 960)
- pytorch 0.2.0_3

**Comment by zou3519** [comment]
Looking into this one

**Comment by csarofeen** [comment]
@zou3519 Probably the best thing to do is manually try to broadcast in https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/rnn.py#L24-L65 before calling the fused kernels. I have hard checks in the fused backend to make sure tensors are of expected size.

@hitvoice out of curiosity, why would you want initial hidden state to be broadcasted? I'm a little concerned that this would typically be an error in user script. Possibly, an inconsequential one in the grand scheme of things.

**Comment by hitvoice** [comment]
@csarofeen It's when you want to set the initial hidden state to fixed values (like all zeros). One can create a new all-zero variable in the "forward" function but will have to deal with whether to send it to GPU manually. Another option is to make it a parameter of the module and set "requires_grad" to False. In this case, the batch size is not known when defining the model and should be able to change during runtime, so it'll be very convenient if GRUCell and LSTMCell support hidden state broadcasting.

**Comment by ngimel** [comment]
If you need all zeros hidden state, you can just omit it (it will be created automatically). If you need a non-zero constant value, I can see how it can be useful.

**Comment by hitvoice** [comment]
@ngimel Can you provide more details on how to omit the hidden state?  If I just pass one argument I get "TypeError: forward() missing 1 required positional argument: 'hx'". If I use None or 0 for hx I get "'NoneType' object has no attribute 'dim'". Thanks!

**Comment by ngimel** [comment]
For nn.{RNN,GRU,LSTM} it is handled here https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L131-L147, just omit hidden in the arguments to forward call. For LSTMCell/GRUCell you are right, you cannot omit it.
