### ISSUE TITLE
Let future expose a then() API

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#37908]
## 🚀 Feature
As mentioned by @xush6528 in https://github.com/pytorch/pytorch/issues/37557, A future `.then()` API that satisfies the following contract would be useful:
```
fut = rpc.rpc_async(...).then(lambda result: some_other_potentially_async_fn(result)
fut.wait() # will be completed once rpc_async is completed and the above lambda has finished execution
```
The implementation could look something like:
```
def then(self, func):
    ret = Future()
    self.addCallback(lambda result: func(result) ; ret.markCompleted())
    return ret
```

## Motivation
The original motivation for this is fixing the RPC profiling - currently, the profiling is done through attached callbacks; however, this does not guarantee that the callbacks are ran when the profiler exits. We already enforce that the future corresponding to the RPC must be awaited in order to be correctly profiled - so wrapping the callbacks in the `.then()` as above and then waiting on this future is a viable solution.

It may also be useful for async user functions in RPC (https://github.com/pytorch/pytorch/issues/36071), although I'll let @mrshenli clarify whether it would be useful or not.

Note: `add_done_callback` is also being exposed to the user, see https://github.com/pytorch/pytorch/pull/37311. The user could of course implement the above with `add_done_callback`, but it's worth considering to support this natively.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
> It may also be useful for async user functions in RPC (#36071), although I'll let @mrshenli clarify whether it would be useful or not.

yes, I agree this will also be useful for async UDF.

Does this mean, we no longer need `add_done_callback(cb) -> None`, and will replace it with `then(cb) -> Future`?

**Comment by jjlilley** [comment]
Does it make sense to create both `add_done_callback(cb) -> None` and `then(cb) -> Future`? 
(Given that the former is lighter weight?)

(Next, somebody will ask for `via(executor)` and `thenError()` :) )

**Comment by mrshenli** [comment]
self-assigned to reserve for new team member on-boarding

**Comment by mrshenli** [comment]
created a dedicated issue (#45552) for the followup `add_done_callback` API. closing this one
