### ISSUE TITLE
CUDA sources are not cached with sccache

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#37928]
## 🐛 Bug

The CUDA build seems to be significantly slower (15 min -> 44 min) and the count of the cache misses has doubled. So there must be sth wrong there.

```
Compile requests                   3015
Compile requests executed          2293
Cache hits                         2219
Cache hits (C/C++)                 2219
Cache misses                         67
Cache misses (C/C++)                 67
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  1
Cache errors                          6
Cache errors (C/C++)                  6
Non-cacheable compilations           39
Non-cacheable calls                 714
Non-compilation calls                 8
Unsupported compiler calls            0
Average cache write               0.195 s
Average cache read miss           9.577 s
Average cache read hit            0.103 s
Failed distributed compilations       0

Non-cacheable reasons:
-M                                  357
multiple input files                357
```

## To Reproduce

1. python setup.py build

## Expected behavior

The non-cacheable reasons `multiple input files` should not exist.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py build
 - Python version: 3.6, 3.7, 3.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla T4
 - Any other relevant information:

## Additional context
I suppose it is due to some newly-introduced flags in `cmake/public/cuda.cmake`. Mostly probably `--Werror`.

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel @pytorch/pytorch-dev-infra @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by peterjc123** [comment]
Related PR in sccache: https://github.com/pytorch/sccache/pull/2.

**Comment by peterjc123** [comment]
Binary updated.

**Comment by mszhanyi** [comment]
Using sccache 0.2.15, the error became 
```
Non-cacheable reasons:
multiple input files                 304
```
It looks we need to merge the latest sccache and fix the regresion.

**Comment by mszhanyi** [comment]
-M should stand for 

```
4.2.2.12. --generate-dependencies (-M)
Generate a dependency file that can be included in a Makefile for the .c, .cc, .cpp, .cxx, and .cu input file.
```

verified locally.
![image](https://user-images.githubusercontent.com/16190118/144081062-a288cec7-5dd2-4835-b5ee-4b549ed436ee.png)

**Comment by peterjc123** [comment]
@mszhanyi Are you sure it works properly? It reports only 171 hits for the cuda sources. In my memory, the number of the cuda source files should be close to 300-500.

**Comment by mszhanyi** [comment]
@peterjc123 , I think the count is right.
For one recent nightly build log, the count of `Building CUDA object` is 167
![image](https://user-images.githubusercontent.com/16190118/144195242-2867cc00-2bcd-4afb-aa31-09a2a635abd1.png)

https://circleci.com/api/v1.1/project/github/pytorch/pytorch/16787871/output/104/0?file=true&allocation-id=61a48a2e45b1e22d633c6b88-0-build%2F3F88CF6C

And the count of non-cacheable reasons is match too.
```
Non-cacheable reasons:
-x                                  168
-M                                    2
```

the change should be caused by the BUILD_SPLIT_CUDA #49050 cc @janeyx99

**Comment by peterjc123** [comment]
@mszhanyi Okay, sounds reasonable.

**Comment by mszhanyi** [comment]
And I checked one 10.2 build (BUILD_SPLIT_CUDA only works on 11.X)
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/16255853/output/104/0?file=true&allocation-id=61540fc83c14e3232f3124c5-0-build%2FD05F24
There're 336` Building NVCC (Device) object`.
and 
```
Non-cacheable reasons:
-M                                   336
```

**Comment by mszhanyi** [comment]
Submit an issue to sccache, hit cache but link errors
https://github.com/mozilla/sccache/issues/1077

**Comment by b0noI** [comment]
Side note: nightly builds should not be using sccache.
