### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by DELTA37** [pytorch/pytorch#3793]
Program received signal SIGSEGV, Segmentation fault.
0x00007fffec41a623 in THPFloatTensor_toNumpy (self=0x7fffb42f72c8, args=<optimized out>)
   from /home/delta37/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so

    def _create(shapes):
        res = []
        for i in range(len(shapes)):
            shape = shapes[i]
            if not isinstance(shape, int):
                print(shape)
                tens = _create(list(shape))
                res.append(tens)
        if len(res) == 0:
            return torch.randn(*list(shapes))
        return None

x = Variable(_create(((10, 4), (2,3))))

python 3.6

**Comment by soumith** [comment]
Thanks George. what is `print(torch.__version__)`?

**Comment by DELTA37** [comment]
Thank you, i have checked. it is a bug in my code. Thank you!
