### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by wdxpython** [pytorch/pytorch#37931]
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1320,0,0], thread: [102,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1586,0,0], thread: [44,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1187,0,0], thread: [3,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1231,0,0], thread: [36,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1453,0,0], thread: [73,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1098,0,0], thread: [65,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1497,0,0], thread: [106,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1142,0,0], thread: [98,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda ->auto::operator()(int)->auto: block: [1364,0,0], thread: [7,0,0] Assertion index >= -sizes[i] && index < sizes[i] && "index out of bounds" failed.
Traceback (most recent call last):
File "train.py", line 130, in
main()
File "train.py", line 120, in main
log_interval = cfg.log_config.interval
File "/media/adas/File/wdx/dianyun/SA-SSD/tools/train_utils/init.py", line 95, in train_model
log_interval = log_interval
File "/media/adas/File/wdx/dianyun/SA-SSD/tools/train_utils/init.py", line 57, in train_one_epoch
outputs = batch_processor(model, data_batch)
File "/media/adas/File/wdx/dianyun/SA-SSD/tools/train_utils/init.py", line 29, in batch_processor
losses = model(**data)
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
return self.module(*inputs[0], **kwargs[0])
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/media/adas/File/wdx/dianyun/SA-SSD/mmdet/models/detectors/base.py", line 79, in forward
return self.forward_train(img, img_meta, **kwargs)
File "/media/adas/File/wdx/dianyun/SA-SSD/mmdet/models/detectors/single_stage.py", line 83, in forward_train
(x, conv6), point_misc = self.neck(vx, ret['coordinates'], batch_size)
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/media/adas/File/wdx/dianyun/SA-SSD/mmdet/models/necks/cmn.py", line 109, in forward
x = x.dense()
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/spconv/init.py", line 73, in dense
res = scatter_nd(self.indices.long(), self.features, output_shape)
File "/home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/spconv/init.py", line 41, in scatter_nd
ret[slices] = updates.view(*output_shape)
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
what(): CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fc6cd77bdc5 in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: + 0x14792 (0x7fc6ca692792 in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x50 (0x7fc6cd76b640 in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: + 0x3067fb (0x7fc6cadb27fb in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: + 0x14019b (0x7fc6fc79819b in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: + 0x3bfc84 (0x7fc6fca17c84 in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: + 0x3bfcd1 (0x7fc6fca17cd1 in /home/adas/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

frame #24: __libc_start_main + 0xf0 (0x7fc70c3cf830 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)

**Comment by wdxpython** [comment]
Can someone help me?

**Comment by SsnL** [comment]
your index is out of bounds. see the `index out of bounds` message.

**Comment by wdxpython** [comment]
> your index is out of bounds. see the `index out of bounds` message.

 def dense(self, channels_first=True):
       
        output_shape = [self.batch_size] + list(self.spatial_shape) + [self.features.shape[1]]
        
        res = scatter_nd(self.indices.long(), self.features, output_shape)
        if not channels_first:	
            return res
        ndim = len(self.spatial_shape)
        trans_params = list(range(0, ndim + 1))
        trans_params.insert(1, ndim + 1)
        return res.permute(*trans_params).contiguous()

def scatter_nd(indices, updates, shape):
    """pytorch edition of tensorflow scatter_nd.
    this function don't contain except handle code. so use this carefully
    when indice repeats, don't support repeat add which is supported
    in tensorflow.
    """

    ret = torch.zeros(*shape, dtype=updates.dtype, device=updates.device)
    ndim = indices.shape[-1]
    output_shape = list(indices.shape[:-1]) + shape[indices.shape[-1]:]

    flatted_indices = indices.view(-1, ndim)
    slices = [flatted_indices[:, i] for i in range(ndim)]
    slices += [Ellipsis]
    ret[slices] = updates.view(*output_shape)
    return ret
But I didn't find the index out of bounds

**Comment by SsnL** [comment]
GitHub is for tracking bugs and feature requests in PyTorch, not for helping users with writing pytorch code. Please use the forum for that. https://discuss.pytorch.org/

that said, your `ret[slices]` could very well be oob.
