### ISSUE TITLE
TensorPipe dependency breaks build for non-X86; it expects x86intrin.h

### ISSUE THREAD

**Issue by dncliss** [pytorch/pytorch#37949]
## 🐛 Bug

This breakage occurred recently, with the introduction of https://github.com/pytorch/pytorch/pull/36695
When building on a non-X86 platform (or at least, confirmed broken on `ppc64le` platform) the build breaks during compilation of new `tensorpipe` dependency.  Within `tensorpipe`, there is a header file `tensorpipe/common/system.h` which explicitly and unconditionally includes an X86-specific header on line 18:
```#include <x86intrin.h>```
Thus, on a `ppc64le` platform (confirmed on both Ubuntu and RHEL), and presumably any non-X86, the build ultimately fails with an error:
```In file included from ../third_party/tensorpipe/tensorpipe/common/system.cc:9:0:
../third_party/tensorpipe/tensorpipe/common/system.h:18:10: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

## To Reproduce
Simply build on ppc64le or (presumably) any non-X86.  One full example run of this build can be seen in the nightly CI build as in this example: https://powerci.osuosl.org/job/pytorch-linux-cuda92-cudnn7-py3-mpi-build-test-gpu/796/console
(search output for `x86intrin.h`

## Environment
-PyTorch Version: Build of current pytorch `master` branch
-Error independent of python version (3.6, 3.7....)
-ppc64le platform, Linux (RHEL or Ubuntu), or presumably any non-X86.
- CUDA version not relevant to the issue (but, 10.2)

## Fix assumption
Presumably either TensorPipe needs to be configured to only conditionally include the x86 required header if on that platform, or Pytorch should only conditionally include TensorPipe depending on platform.

cc @ezyang @gchanan @zou3519 @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma

**Comment by lw** [comment]
Thanks for flagging this! It looks like it's a useless include which we forgot to remove. I have https://github.com/pytorch/tensorpipe/pull/164 ready to address that.

**Comment by lw** [comment]
This should have been fixed as part of https://github.com/pytorch/pytorch/pull/38013. Let me know if you still see issues!
