### ISSUE TITLE
make CPU RNG thread-safe

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3794]
currently our RNG functions on the CPU are not thread-safe, and one can run into weird segfaults if running them from multiple threads.

**Comment by yf225** [comment]
I will take a look at this one

**Comment by Stonesjtu** [comment]
What about using different generators for multi-threads.

**Comment by ezyang** [comment]
@Stonesjtu That'd be my preferred resolution.

**Comment by yf225** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/4041.
