### ISSUE TITLE
Can't Install from source if path contains a space

### ISSUE THREAD

**Issue by chrisorm** [pytorch/pytorch#3798]
Hi everyone,

silly "gotcha" installing the latest master from source (on ubuntu 16)- if there is a space in the path you install from, it fails to compile the "compiler simple test", and throws some fairly obscure error messages about cc being an unrecognised compiler.

Perhaps just needs a line in the instructions, as it took digging through the compiler logs to find the issue (unless i missed something!).

Apologies if duplicated, but couldn't find a relevant issue in a quick search. Happy to contribute fix to docs etc if required.

**Comment by zou3519** [comment]
As you noticed a lot of the build steps assume that the path doesn't contain a space.  For now an addition to the README in the build from source section would be great.

**Comment by ezyang** [comment]
We've made a lot of improvements here, e.g., #38860. Going to pray that we've fixed this. If there are still problems feel free to file issues.
