### ISSUE TITLE
torch.unique not support for torch.jit.script

### ISSUE THREAD

**Issue by lgray** [pytorch/pytorch#37986]
## 🚀 Feature
Add `torch.unique` support to `torch.jit.script` so that it is possible to jit-script graph pooling in using pytorch geometric.

This was mentioned back in #12206.

@suo 

## Motivation

I am writing models using pytorch_geometric that I would like to jit-script. I have started by making automatic GNN model synthesis that makes jittable convolution operations, but we also need to do graph pooling to have the full range of functionality. This latter bit requires `torch.unique` in python to be jit-scriptable.

## Pitch

I would like:
```python
@torch.jit.script
def f(x):
    return torch.unique(x)
```
to not result in:
```
Traceback (most recent call last):
  File "quicktest.py", line 3, in <module>
    @torch.jit.script
  File "/data/gaoxiang/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 639, in script
    graph = _jit_script_compile(ast, rcb)
RuntimeError: 
unknown builtin op:
@torch.jit.script
def f(x):
    return torch.unique(x)
           ~~~~~~~~~~~~ <--- HERE
```

but rather a working jit function!

## Alternatives

Writing everything in C++ for torch_geometric, which is a significant time burden for developers, where this could be fixed easily and centrally.

## Additional context

This is supporting an effort here:
https://github.com/rusty1s/pytorch_geometric/pull/1191

to make pytorch_geometric easily jittable without major rewrites or changes of user code.

cc @suo

**Comment by zdevito** [comment]
`torch.unique` is similar to `torch.norm` in that it includes a python function that figures out dispatch to the actual builtin op. Trying to script that function directly doesn't work at the moment. @eellison I think you looked at norm, do you know what it would take to make unique work too?

**Comment by eellison** [comment]
it would be a similar to https://github.com/pytorch/pytorch/pull/33737/

`torch.unique` is a little trickier because you'd have to add a `boolean_dispatch` for both the `return_inverse` arg and the `return_counts` arg.
