### ISSUE TITLE
Index out of bounds error in torch.gather when using non 64 bit integer indices

### ISSUE THREAD

**Issue by tylerjthomas9** [pytorch/pytorch#37996]
## 🐛 Bug

torch.gather fails with an index out of bounds error when using non 64 bit integers for the index tensor. 

## To Reproduce

1. Create a 2x2 torch tensor with any values. (tensor1)
2. Create a 2x1 torch tensor with non 64 bit integers. (tensor2)
3. Run torch.gather with tensor1 and tensor2.

## Example
```
import torch
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[0], [1]], dtype=torch.int32)
tensor1.gather(1, tensor2)
```

Error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-91329ddacef3> in <module>
----> 1 tensor1.gather(1, tensor2)

RuntimeError: index 4294967296 is out of bounds for dimension 1 with size 2
```

## Expected behavior
I expect a 2x1 tensor to be returned with the values 1,4. 

```
import torch
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[0], [1]], dtype=torch.int64)
tensor1.gather(1, tensor2)
```
Result : 
```
tensor([[1], [4]])
```

## Environment

PyTorch version: 1.5.0+cpu
Is debug build: No
CUDA used to build PyTorch: None
OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect
Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Versions of relevant libraries:
[pip] numpy==1.18.4
[pip] pytorch-lightning==0.7.5
[pip] torch==1.5.0+cpu
[pip] torchvision==0.6.0+cpu
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] pytorch-lightning         0.7.5                    pypi_0    pypi
[conda] torch                     1.5.0+cpu                pypi_0    pypi
[conda] torchvision               0.6.0+cpu                pypi_0    pypi

cc @ezyang @gchanan @zou3519

**Comment by cloudhan** [comment]
tested with current master, 
```
>>> import torch
>>> tensor1 = torch.tensor([[1, 2], [3, 4]])
>>> tensor2 = torch.tensor([[0], [1]], dtype=torch.int64)
>>> tensor1.gather(1, tensor2)
tensor([[1],
        [4]])
```

**Comment by tylerjthomas9** [comment]
Did it work as expected when dtype was set to a non 64-bit integer?

**Comment by cloudhan** [comment]
heck, copied wrong code snippet, it indeed crashed with the same error on master (almost)

**Comment by cloudhan** [comment]
```python
import torch
torch.scatter(torch.ones(4), 0, torch.tensor([0, 1], dtype=torch.int64), torch.zeros(4))
```
have the similar issue.

**Comment by glaringlee** [comment]
cc @ezyang @gchanan @zou3519
mark it high priority since this caused crush
