### ISSUE TITLE
DistributedDataSampler converts NamedTuple to regular tuple

### ISSUE THREAD

**Issue by malhotraa** [pytorch/pytorch#38028]
## 🐛 Bug

DistributedDataSampler converts NamedTuple to regular tuple due to [this](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/scatter_gather.py#L14) code.

## To Reproduce

1. Create a NamedTuple type `MyTuple`
2. Return a `MyTuple` object from the `collate_fn` in your dataset
3. During training you will find the loaded data batch is a regular tuple instead of named tuple.

## Expected behavior
NamedTuple data loaded using DDP shouldnt be implicitly converted to regular tuples.

## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 418.39
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] numpy 1.18.1 pypi_0 pypi
[conda] torch 1.4.0 pypi_0 pypi
[conda] torchvision 0.5.0 pypi_0 pypi

## Additional context
n/a

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by malhotraa** [comment]
cc @mrshenli

**Comment by mrshenli** [comment]
Hi @malhotraa, thanks for reporting the issue and identifying the culprit code. Would you like to contribute a PR to fix this? :)

**Comment by malhotraa** [comment]
@mrshenli for sure. will create a PR shortly.

**Comment by malhotraa** [comment]
@mrshenli I am struggling a bit with finding a clean way to check if an object is an instance of `namedtuple` so that it can be handled correctly by the `scatter` method. There is a kinda hacky check [here](https://stackoverflow.com/a/2166841). Would you recommend using it?

**Comment by malhotraa** [comment]
Looks like this issue has been addressed by https://github.com/pytorch/pytorch/pull/44220
