### ISSUE TITLE
[ONNX] A 'Constant' node before ConvTranspose? 

### ISSUE THREAD

**Issue by masahi** [pytorch/pytorch#3804]
Hi, I found that when I export a model that uses ConvTranspose2d, I get ONNX 'Constant' node before 'ConvTranspose' node. Looking at the comments [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/functions/onnx/convolution.cpp#L7), I'm assuming that the 'Constant' node is added for Caffe2 compatibility reason. 

But now that Caffe2ConvTranspose was removed in onnx/onnx#225, is this Constant node still necessary?

This problem bothers me because NNVM's ONNX frontend doesn't support ONNX 'Constant' operator at the moment, so I can't import my Pytorch-trained model into NNVM.

**Comment by ezyang** [comment]
This should be fixed in HEAD now.
