### ISSUE TITLE
Quantization: FakeQuant and Observers should sync enabled flags with DDP

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#38081]
## 🐛 Bug

We should make sure that the following work properly in DDP by moving the state variables to in observer.py and fake_quant.py to buffers:

```
model.apply(torch.quantization.disable_fake_quant)
model.apply(torch.quantization.disable_observer)
```

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by pritamdamania87** [comment]
Is there a reason to apply these quantization methods on DDP itself instead of applying it to the original model and then wrapping the original model with DDP?

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/blob/8d6a8d2b3fd2a6ec788378843fc518824acf274b/torch/nn/parallel/distributed.py#L147 has some more context.

Yep, the quantization methods should be created before DDP.  This issue is just to track that currently some of the quantization flags are not buffers, so they will not be replicated properly if wrapped with DDP and then changed in the middle of training.

**Comment by vkuzo** [comment]
this is completed
