### ISSUE TITLE
Remove all self.assertEqualIgnoreTypes instances

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#38095]
As `self.assertEqual` now compares tensor's dtypes as well as values, there are some number of tests which are unhappy with it. So we temporarily replaced such cases of `self.assertEqual` with `self.assertEqualIgnoreTypes`. 

However it is temporary measure, as `self.assertEqualIgnoreTypes` calls need to be reviewed on case-by-case basis and replaced with `self.assertEqual` calls and proper dtypes or `self.assertEqual` with `exact_dtype=False` wherever it is not possible by design.

All this tasks are searchable by: `TODO(#38095)` after landing of #38102

cc @mruberry

**Comment by kit1980** [comment]
https://github.com/pytorch/pytorch/pull/90741 was the last PR:

```
$ grep -r --exclude-dir=.git 'self.assertEqualIgnoreType' -In . | wc -l
0
```

Closing this as completed!
