### ISSUE TITLE
Unary and binary operations don't preserve strides of `out` argument

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#38107]
## 🐛 Bug
Unary and binary operations don't preserve strides of `out` argument for correctly sized `out`. 
## To Reproduce
```
import torch

a = torch.randn(3, 4).t()
b = torch.randn(3, 4).t()
out = torch.empty(4, 3)
print(out.stride())  # prints 3,1 as expected
torch.add(a, b, out=out)
print(out.stride())  # prints 1,4
out = torch.empty(4, 3)  # reset out strides
torch.sin(a, out=out)
print(out.stride())  # prints 1,4
```
## Expected behavior
When `out` is incorrectly sized, we either error out or resize it, there is not a lot of consistency unfortunately.  However, completely restriding correctly sized `out` is unexpected and incompatible with numpy

This behavior was introduced by #33165
cc @mruberry @glaringlee

**Comment by glaringlee** [comment]
@ngimel 
Ah, I know this behavior.
The fast setup will flatten the non-contiguous tensors to 1d if all input tensors have same shape and stride. So the pointwise iteration will be applied to a 1d array in sequence which increase the iteration performance, but the output tensor needs to have exact the same shape and stride as input, so the output tensor is re-strided even the output tensor has a same size as input. 

I actually had a discussion about this behavior with NY people when doing the implementation, it seems we all missed the numpy behavior. 

Will put a fix to preserve the strides.
