### ISSUE TITLE
Allow Devices >= device_num or Get Device by UUID in CUDA Memory Utils

### ISSUE THREAD

**Issue by nflu** [pytorch/pytorch#38100]
## 🚀 Feature
It would be nice if we could get GPU by UUIDs or GPUs by indices that are >= device_num but in CUDA_VISIBLE_DEVICES. I've opened up a [pull request](https://github.com/pytorch/pytorch/pull/38097) for the second feature.

If you use the built-in [CUDA memory usage functions](https://github.com/pytorch/pytorch/issues/24463) with CUDA_VISIBLE_DEVICES=1 and GPU 1 it will fail [due to this check](https://github.com/pytorch/pytorch/blob/0d9e3b48c4ef54a7b5395c501ee370a8eba34bad/c10/cuda/CUDACachingAllocator.cpp#L882-L885). 

## Motivation

The current implementation only works if the GPUs being used start at 0 and are sequential (e.g. 0,1,2,3). On shared computing resources often someone else may be using some of the GPUs thus it becomes impossible to use these memory usage functions. For example if I am on a machine with 8 GPUs and GPU 0 is being used and I use 3 GPUs I will be assigned CUDA_VISIBLE_DEVICES=1,2,3 but 3 >= device_num so I can't get memory usage statistics for device 3.

**Comment by SsnL** [comment]
Once you set `CUDA_VISIBLE_DEVICE`, user of CUDA (PyTorch in this case) does not see devices outside the specified indices. Moreover, it sees the first in the specified list as device 0, the second as device 1, etc., which means that if `CUDA_VISIBLE_DEVICES=3,2,1,0`, the user program will in fact use gpu #3 when they ask for device numbered 0. Moreover, the user program will have no way to access devices outside that list.

Importantly, this is an abstract that should not be broken. E.g., `CUDA_VISIBLE_DEVICES=3,0` should make the program run as if on a machine with 2 GPUs, the first being the same as the 3rd physical GPU and the second being the same as the 1st physical GPU.

The behavior introduced by your PR also doesn't quite make sense and introduces great inconsistency. If `CUDA_VISIBLE_DEVICES=1,3`, and you ask for `cuda:1`, does it refer to 3rd physical GPU or the 1st? 

In the end, user program should treat as if `CUDA_VISIBLE_DEVICES` does not exist.

**Comment by nflu** [comment]
Ah thanks for the explanation! That makes sense.

I suppose you can close [this as well](https://github.com/pytorch/pytorch/issues/24463) since that user should just be doing `device = torch.device("cuda:0")`
