### ISSUE TITLE
pytorch-mobile memory leak or emptyCache api

### ISSUE THREAD

**Issue by NortonAhu** [pytorch/pytorch#38117]
I use the latest pytorch version 1.5.0， build mobile static lib by use script/build_pytorch_android.sh and use this libs link in my project just like android directory use。but when i use it load my module and forward running in android device ，the native memory is increasing。but is not increase in Linux system(ubuntu)。i suppose it because module have cache something，but i can‘t find api to clear them. is clear by themselves. i just find a api is torch.cuda.emptyCache(),there no CPU clear cahce methon. have someone encount this question. forgive my bad english.

NDK r20b
pytorch 1.5.0
’

**Comment by malfet** [comment]
@NortonAhu can you please provide more information on which tools did you use measure memory utilization on Android and Linux?

It would be also very helpful if you could provide an example code that demonstrates the issue using a sample model.

**Comment by NortonAhu** [comment]
module code
`import torch

print(torch.__version__)


# simple module

class SimpleModule(torch.nn.Module):
    def __init__(self):
        super(SimpleModule, self).__init__()
        self.conv = torch.nn.Sequential(
            torch.nn.Conv2d(1, 32, 3, 2),
            torch.nn.ReLU(),
            torch.nn.Conv2d(32, 32, 3, 2),
            torch.nn.ReLU()
        )
        
    def forward(self, chunk):
        chunk = torch.as_tensor(chunk).unsqueeze(0)
        y = chunk.unsqueeze(1)  
        y = self.conv(y)
        b, c, t, f = y.size()
        y.transpose(1, 2).contiguous().view(b, t, c * f)
        return y
    

simple_cell = SimpleModule()

chunk = torch.randn(100, 80)
print(simple_cell(chunk))

simple_torchscript = torch.jit.script(simple_cell)
simple_torchscript.save("simple.pt")`

C++ sample code：
`#include <iostream>
#include "torch/csrc/api/include/torch/torch.h"
#include "torch/csrc/api/include/torch/utils.h"
#include <caffe2/utils/threadpool/ThreadPool.h>
#include <caffe2/utils/threadpool/ThreadPoolMobile.h>
#include "torch/script.h"
#include <utility>
#include <unistd.h>
#include <vector>
#include <pthread.h>

using std::cout;
using std::endl;
torch::jit::Module module_;
struct JITCallGuard {
  // AutoGrad is disabled for mobile by default.
  torch::autograd::AutoGradMode no_autograd_guard{false};
  // VariableType dispatch is not included in default mobile build. We need set
  // this guard globally to avoid dispatch error (only for dynamic dispatch).
  // Thanks to the unification of Variable class and Tensor class it's no longer
  // required to toggle the NonVariableTypeMode per op - so it doesn't hurt to
  // always set NonVariableTypeMode for inference only use case.
  torch::AutoNonVariableTypeMode non_var_guard{true};
  // Disable graph optimizer to ensure list of unused ops are not changed for
  // custom mobile build.
  torch::jit::GraphOptimizerEnabledGuard no_optimizer_guard{false};
};

void *autoTest(void *args) {
  printf("start load \n");
  try {
    JITCallGuard guard;
    module_ = torch::jit::load(std::move("./simple.pt"));
//    module_ = torch::jit::load(std::move("./model/libbestm.so"));
  } catch (const c10::Error &e) {
    printf("load module resource failed.");
    return 0;
  }
  module_.eval();
  printf("load over \n");
  usleep(1000 * 1000);

  // run forward
  caffe2::mobile_threadpool()->setNumThreads(1);
  torch::jit::getProfilingMode() = false;
  torch::jit::getExecutorMode() = false;
  torch::jit::setGraphExecutorOptimize(false);
  printf("start recycle \n");
  int count = 3;
  while (count >= 0) {
    float *data = new float[8000];
    torch::Tensor datas = torch::from_blob(data, {100, 80});
    std::vector<torch::jit::IValue> inputs{};
    inputs.emplace_back(datas);
    JITCallGuard guard;
    module_.forward(inputs);
    delete[] data;
    usleep(500 * 1000);
    printf("current count is %d .\n", count);
    count--;
  }
  pthread_exit(NULL);
}


int main() {
  cout << "Test TorchScript Memory Leak pytorch 1.5.0" << endl;
  for (int i = 0; i < 200; i++) {
    cout << "times is " << i << endl;
    pthread_t tid;
    pthread_attr_t attr;
    void *status;
    pthread_attr_init(&attr);

    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
    int ret = pthread_create(&tid, &attr, autoTest, NULL);
    if (ret != 0) {
      cout << "pthread_create error: error_code=" << ret << endl;
      return 0;
    }
    pthread_attr_destroy(&attr);
    int rc = pthread_join(tid, &status);
    if (rc) {
      cout << "Error:unable to join," << rc << endl;
      exit(-1);
    }
    cout << "Main: completed thread id : "
            "exiting with status :" << status << endl;

  }
  return 0;
}`

get memory info by
`pid=`ps -A | grep sample| awk '{print $2}'`;while [ 1 ];do cat /proc/${pid}/status | grep VmRSS;sleep 3;done`

**Comment by NortonAhu** [comment]
> @NortonAhu can you please provide more information on which tools did you use measure memory utilization on Android and Linux?
> 
> It would be also very helpful if you could provide an example code that demonstrates the issue using a sample model.

can you help me check my code have something wrong?

**Comment by NortonAhu** [comment]
@malfet hi, we found that the pytorch mobile static lib libnnpack.a is the reason for memory leak, w rebuild pytorh mobile without nnpack , is work fine

**Comment by xing-shuai** [comment]
我也尝试了重新编译，不使用nnpack，但是发现内存还是会不断涨上去，我的操作过程是不停初始化，跑几次前传，最后释放。

**Comment by xing-shuai** [comment]
@NortonAhu 请问你是直接在Cmakelist中将USE_NNPACK 设置为OFF吗
![image](https://user-images.githubusercontent.com/23748405/134840022-458ed693-bef2-424d-9527-8487c6ac651d.png)
