### ISSUE TITLE
how to get the libtorch code from the python?

### ISSUE THREAD

**Issue by Peterisfar** [pytorch/pytorch#38129]
![image](https://user-images.githubusercontent.com/31852119/81431554-ea93db80-9193-11ea-96f4-d2f1df0982ce.png)

in the python, it's easy to slice, but in the libtorch i don't find any information about it? so please tell me how to get the code from the above python code? thanks

**Comment by zou3519** [comment]
@Peterisfar please ask your question on the pytorch forums (https://discuss.pytorch.org/). We like to keep issues open on our issue tracker for real bug reports / feature requests to minimize noise.

To answer your question, you are looking for https://pytorch.org/cppdocs/notes/tensor_indexing.html?highlight=index
