### ISSUE TITLE
multiprocess test error when run_test.sh

### ISSUE THREAD

**Issue by douhaoexia** [pytorch/pytorch#3812]
I install the released pytorch-v0.2.0-0b92e5c ；and run test ,then an error occurred like this:

![pytorch](https://user-images.githubusercontent.com/15043401/33081626-bdf59e62-cf15-11e7-931d-0f2cde20fb94.png)

How to handle it ?

**Comment by douhaoexia** [comment]
The environment is ubuntu 14.04.4 LTS-4.2.0-27-generic, with cuda 8.0 and cudnn v5.1

**Comment by zou3519** [comment]
What happens if you try to run again? Sometimes there are some transient failures with the multiprocessing tests.
```
python test/test_multiprocessing.py TestMultiprocessing.test_cuda
```

**Comment by soumith** [comment]
this is a flaky test. it has a timeout / retry.
