### ISSUE TITLE
Functions in torch._C._nn and torch._C._onnx are not pickleable

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#38137]
This is due to the same bug fixed in https://github.com/pytorch/pytorch/pull/38136 We need to apply the same fix in the other situations too

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by ezyang** [comment]
Actually please apply the fix as seen in https://github.com/pytorch/pytorch/pull/38136

**Comment by albertcthomas** [comment]
gpytorch models cannot be pickled because of this, see related issue cornellius-gp/gpytorch#907. A temporary fix is to use `dill` or redefine needed functions if possible, see [this comment](https://github.com/cornellius-gp/gpytorch/issues/907#issuecomment-723638638). However maybe this can be fixed in pytorch as you suggest @ezyang?

**Comment by albertcthomas** [comment]
By the way I might be missing something but with pytorch 1.7 if I do a `import torch._C._VariableFunctions` I get a `ModuleNotFoundError: No module named 'torch._C._VariableFunctions'; 'torch._C' is not a package`

**Comment by ezyang** [comment]
Yes it should be fixable by PyTorch. `_VariableFunctions` is not a module, I think it's a faux class (but I could be wrong).

**Comment by mattip** [comment]
It seems this is a shortcoming in python3. The meaning of `torch._C._onnx` is that there really is a directory `_C` under the directory `torch`, and inside that directory there is a module `_onnx`. 

`_onnx` is created via a call to `pybind11`'s `def_submodule`, and a [discussion of use of `def_submodule`](https://github.com/pybind/pybind11/issues/2639) points out the shortcomings. Some of the other submodules, like `_nn`, are created with `PyModule_Create`. Refactoring `_C` to break out these submodules would be one solution. The easier thing to do is to push all these submodules into `sys.modules` [as was done](https://github.com/pytorch/pytorch/pull/38136/files#diff-d7e90d0f94b43db763b44fba679a5c1b4cabe3668aaf34f2aee07de8e2d1b2faR528) in gh-38136:
```
for x in dir(torch._C):
    c = getattr(torch._C, x)
    if type(c) is type(torch):
        sys.modules[f'torch._C.{x}'] = c
```

I also opened an issue [for CPython](https://bugs.python.org/issue43367)
