### ISSUE TITLE
So I updated the pytorch and I am trying to run a 2dtodepth.py program which fails to run as it does not find the module torch but Ive tested on jupyter and conda list and it is there. 

### ISSUE THREAD

**Issue by saigol17** [pytorch/pytorch#38168]
So I updated the pytorch and I am trying to run a 2dtodepth.py program which fails to run as it does not find the module torch but Ive tested on jupyter and conda list and it is there. The issue now i am having after updating the pytorch is entry point not found.

**Comment by saigol17** [comment]
![pytorch](https://user-images.githubusercontent.com/62231162/81456932-1d64b200-9149-11ea-9669-4c58a58f828f.png)

**Comment by ailzhang** [comment]
Closing as this doesn't include enough information about the error message and how to repro. Please feel free to reopen with a detailed repro instruction. Thanks!
