### ISSUE TITLE
Not able to change the size/dimension of a fully connected layer (torch.nn.linear)

### ISSUE THREAD

**Issue by RoopIITGN** [pytorch/pytorch#38181]
## ❓ Questions and Help
I am trying to change the size/dimension of a particular fully connected layer of a pre-trained model. 

Previously this code used to work perfectly :
net.state_dict()["fc1.weight"].resize_( size_1, size_2)

But now it's throwing the error message :
RuntimeError: set_sizes_contiguous is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y) 

The entire model architecture is like this:
## code
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.fc1 = nn.Linear(16 * 4 * 4, 300)
        self.fc2 = nn.Linear(300, 100)
        self.fc3 = nn.Linear(100, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 4 * 4)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return F.log_softmax(x, dim=1)
    
net = Net()

Do you have any idea about how can I change the size of this particular weight matrix in just one single chunk of code?

**Comment by ngimel** [comment]
Please ask questions on the forums, discuss.pytorch.org. You cannot change sizes of the pretrained models weights - how would you know what to fill it with?
