### ISSUE TITLE
test_linspace takes too long to run

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#38187]
As a result of this PR https://github.com/pytorch/pytorch/pull/27957 test_linspace(_cpu) is timing out on some internal test runners. 

@xuhdev Maybe we can keep the test effective but reduce its runtime? 

cc @mruberry

**Comment by xuhdev** [comment]
#38093 might be a solution

**Comment by xuhdev** [comment]
I looked back at #27957 again and I think I made a mistake: The benchmark there was run with neither TBB nor OpenMP enabled. #38093 should be able to remedy this and make the code utilize both parallelization and SIMD (the version before #27957 did not use SIMD).

**Comment by xuhdev** [comment]
Could you test again? #38093 has been merged to master now.

**Comment by mruberry** [comment]
> Could you test again? #38093 has been merged to master now.

I re-enabled the float32 version of the test internally. Let's see what happens ;)

**Comment by mruberry** [comment]
Looks like the test is working internally now!
