### ISSUE TITLE
autograd profiler with use_cuda=True has memory not released

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#38183]
## 🐛 Bug

autograd profiler with `use_cuda=True` has memory not released

## To Reproduce

Run the following code and monitor the memory usage of the python process, e.g. `top` on linux.

```python
import torch
for i in range(1000000):
    if i % 10000 == 0:
        print(i)
    x = torch.randn(1000, device='cpu', dtype=torch.float)
    with torch.autograd.profiler.profile(use_cuda=True) as prof:
        y = torch.nn.ReLU(x)
```
The memory usage of the python process keeps increasing. Using `gc.collect()` or `torch.cuda.empty_cache()` doesn't help. Change device of x to 'cuda' shows similar behavior.

However, change `use_cuda` to False
```python
    with torch.autograd.profiler.profile(use_cuda=False) as prof:
        y = torch.nn.ReLU(x)
```
or simply remove the profiling
```python
    y = torch.nn.ReLU(x)
```
will keep the memory usage roughly unchanged. 

## Expected behavior

autograd profiler with use_cuda=True releases memory after each use

## Environment

PyTorch version: 1.6.0a0+86d2870
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Fedora 31 (Workstation Edition)
GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
CMake version: version 3.15.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 440.31
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0a0+86d2870
[pip3] torchvision==0.7.0a0+f9ef235
[conda] Could not collect

## Additional context

cc @ptrblck

**Comment by xwang233** [comment]
might be related to #37313

**Comment by ilia-cher** [comment]
https://github.com/pytorch/pytorch/pull/39962 fixes that
