### ISSUE TITLE
Can't create tensor from tensor list, but tensor from numpy arrays list works fine

### ISSUE THREAD

**Issue by Jkasnese** [pytorch/pytorch#38196]
## 🐛 Bug

I'm able to create a torch.Tensor from a list of numpy arrays, but I'm not able to create torch.Tensor from a list of torch.Tensors, raising:

`ValueError: only one element tensors can be converted to Python scalars`

## To Reproduce

This code raises above error:

```
tensors_list = [torch.Tensor(1,3), torch.Tensor(1,3)]
list_to_tensor = torch.Tensor(tensors_list)
```

While this code works fine:
```
np_list = [np.random.rand(1,3), np.random.rand(1,3)]
list_to_tensor = torch.Tensor(np_list)
```

## Environment
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX150
Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.6.0
[conda] Could not collect

## Additional context

This is probably very minor bug, not sure if I should've posted it here, but I'm too much of a beginner to judge so here it is.

**Comment by malfet** [comment]
Thank you for reporting the issue. We would accept a patch that fixes this.

**Comment by Jkasnese** [comment]
Cool! I'll do my best on Saturday! Thanks for incentivizing! (:

**Comment by gchanan** [comment]
I'm pretty sure this issue is a duplicate.

**Comment by gchanan** [comment]
here's the original issue: https://github.com/pytorch/pytorch/issues/26354, I'll close this and let discussion happen on the original.

There's some advice for implementation in the other issue as well.
