### ISSUE TITLE
Implement Variable::ID()

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3819]
I think this is all that's required to do `at::ones_like(Variable)` directly from C++. Currently many calls that should work do not:

  what():  VariableType::ID() not implemented

**Comment by ebetica** [comment]
Nevermind, this is spurious, you can't create a variable from a variable.

**Comment by ezyang** [comment]
I have mentioned to @colesbury that we should check this case and give a better error message... and then I failed to actually implement it.
