### ISSUE TITLE
[onnx]export model error,Attribute 'axes' is expected to have field 'ints'

### ISSUE THREAD

**Issue by heliqi** [pytorch/pytorch#38218]
## 🐛 Bug

When export torch model to onnx, threw an error:
```
File "torch/onnx/__init__.py", line 168,in export
        ,use_external_data_format)
FIle "torch/onnx/utils.py", line 69, in export
      use_external_data_format=use_external_data_format)
File "torch/onnx/utils.py",line 515, _export
      _check_onnx_proto(proto)
RuntimeError: Attribute 'axes' is expected to have field 'ints'

=> Context: Bad node spec: input: "3394" output: "agg_score" name: "Squeeze_2299" op_type:"Squeeze" attribute {name: "axes" type: INTS}
```
## Environment
Pytorch Version == 1.5.0+cu101
OS == Linux
onnx == 1.6.0
CUDA Version == 10.1
## Additional context
Here's a similar error:  https://github.com/pytorch/pytorch/issues/5146.
But I didn't find any problem with “Squeeze". 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Can you please share a repro with exact model and export code?

**Comment by libinta** [comment]
I got the same issue with https://github.com/emadRad/lstm-gru-pytorch/blob/master/lstm_gru.ipynb GRUModel on torch 1.5.1 with export code as input1 = torch.randn(100,28,28)
model = GRUModel(input_dim, hidden_dim, layer_dim, output_dim)
torch.onnx.export(model, (input1), "grumodel.onnx")

**Comment by spandantiwari** [comment]
@heliqi - can you share a small repro of this issue. 

@libinta - could you distill your notebook to a smaller repro.

**Comment by heliqi** [comment]
I'm sorry,My model and code are on the Intranet and cannot be provided.

**Comment by garymm** [comment]
@libinta your provided code runs successfully on PyTorch 1.10.0.

@heliqi if this is still a problem, please open a new issue with some repro instructions. Even if you can't share the full model, we need something to work with.
