### ISSUE TITLE
Issues with namespace c10 in ‘jit/ir/ir.h’

### ISSUE THREAD

**Issue by avisrazo** [pytorch/pytorch#38224]
Hi,
I’m trying to include PyTorch library in my CPP project.
I’m using ndk21 and C++14, torch version 1.5.0 for CPU.

I get the following compilation error:

pytorch-1.5.0-py3.7_cpu_0\Lib\site-packages\torch/include\torch/csrc/jit/ir/ir.h:66:17: error:

 no namespace named 'prim' in namespace 'c10'; did you mean simply 'prim'?*
using namespace ::c10::prim;

           ^~~~~~~~~~~*
           prim*
I get 7 similar compilation errors regarding namespace ‘c10’.
Can someone please help me to overcome this?
Thanks.

cc @suo

**Comment by aviaisr** [comment]
All the errors can be found below:
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:67:17: error: no
namespace named ‘prim’ in namespace ‘c10’; did you mean simply ‘prim’?
using namespace ::c10::prim;
^~~~~~~~~~~
prim
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:66:11: note: namespace
‘prim’ defined here
namespace prim {
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:70:17: error: no
namespace named ‘attr’ in namespace ‘c10’; did you mean simply ‘attr’?
using namespace ::c10::attr;
^~~~~~~~~~~
attr
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:69:11: note: namespace
‘attr’ defined here
namespace attr {
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:73:17: error: no
namespace named ‘aten’ in namespace ‘c10’; did you mean simply ‘aten’?
using namespace ::c10::aten;
^~~~~~~~~~~
aten
C:\REPOSCPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:72:11: note: namespace
‘aten’ defined here
namespace aten {
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:1309:34: error: no
member named ‘prim’ in namespace ‘c10’; did you mean simply ‘prim’?
static constexpr Symbol Kind = ::c10::prim::profile;
^~~~~~~~~~~
prim
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:66:11: note: ‘prim’
declared here
namespace prim {
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:1309:47: error: no
member named ‘profile’ in namespace ‘torch::jit::prim’
static constexpr Symbol Kind = ::c10::prim::profile;
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:1311:21: error: no
member named ‘prim’ in namespace ‘c10’; did you mean simply ‘prim’?
: Node(graph, ::c10::prim::profile), callback_(callback) {}
^~~~~
prim
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:66:11: note: ‘prim’
declared here
namespace prim {
^
C:\REPOS\CPU\libtorch-shared-with-deps-latest\libtorch/include\torch/csrc/jit/ir/ir.h:1311:34: error: no
member named ‘profile’ in namespace ‘torch::jit::prim’
: Node(graph, ::c10::prim::profile), callback_(callback) {}

**Comment by ailzhang** [comment]
This report doesn't contain enough information to debug as it lacks steps to repro, please reopen a minimal repro if possible. Thanks!

**Comment by avisrazo** [comment]
1. I have a CPP android project. I'm compiling it using ndk-build (ndk21 and C++14).
2. I have a file named "main.cpp" and I'm trying to **#include "torch/script.h"**.
3. I downloaded libtorch using this command:
**wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz** 
4. In my Android.mk file, I'm giving the path to:
LOCAL_C_INCLUDES += $(TORCH_REPO_PATH) \
					$(TORCH_REPO_PATH)/include \
					$(TORCH_REPO_PATH)/include/torch \
					$(TORCH_REPO_PATH)/include/torch/csrc/api/include
5. When I'm trying to compile, I get the errors demonstrated bellow.
How can I overcome this issue?

**Comment by k90armstrong** [comment]
Hi @avisrazo , 

I am running into the same issue.  Did you ever figure out how to solve this?

**Comment by avisrazo** [comment]
Hi,
I followed the example in https://github.com/ljk53/pytorch-android-cpp-demo
and compiled static libraries for Android. I'm including these libraries in my CPP Android project. 
Now I'm not getting these specific compilation errors, but I have different compilation errors.
You can try that and see if it helps. If it does and you can help me as well, please do :)
Thanks
