### ISSUE TITLE
Docs of KLDivLoss seems incorrect

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/pytorch#38227]
## 📚 Documentation
![{F510068B-29A9-4020-A7A2-C6172C4C7543}_20200511222346](https://user-images.githubusercontent.com/7830725/81572821-4a79c480-93d6-11ea-95fb-06f301a146d9.jpg)

KLDivLoss, the formulation is incorrect. 
It should be 
$l_n = y_n \cdot (log_{y_n} - log_{x_n})$ ?

**Comment by vadimkantorov** [comment]
The `x_n` seems to be accepted in log-probs format while `y_n` in probs format:
```
As with NLLLoss, the input given is expected to contain log-probabilities and is not restricted to a 2D Tensor. The targets are given as probabilities (i.e. without taking the logarithm).
```
so there seems no error in the formula

**Comment by ailzhang** [comment]
Closing via https://github.com/pytorch/pytorch/issues/38227#issuecomment-626832274
