### ISSUE TITLE
Perform backward process in libtorch

### ISSUE THREAD

**Issue by Linkeyboard** [pytorch/pytorch#38225]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Now I have models trained by pytorch, and I hope to load and finetune my models with libtorch in C++ . How can I achieve that?
It seems that torchscript does not work. I tried to put the parameters into optimizer, however the data type does not match. 
```
    std::string netdir = "model.pt";
    std::shared_ptr<torch::jit::script::Module> module = std::make_shared<torch::jit::script::Module>(torch::jit::load(netdir));
    torch::optim::SGD optimizer(module->get_parameters(), /*lr=*/0.0001);
```

cc @suo

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org. libtorch does not support finetuning a model. If you want to fine-tune a model in C++, you can use C++ front-end APIs.
