### ISSUE TITLE
Store TORCH_CUDA_ARCH_LIST in torch and use it for C++ extensions

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#38229]
When compiling C++ extensions, users sometimes need to worry about specific implementation details like `TORCH_CUDA_ARCH_LIST`, which specifies the CUDA compute capabilities that we will be computing the CUDA code for the extensions, even though they might just be using a pre-compiled PyTorch installations which was compiled for all CUDA architectures.

I propose to store the `TORCH_CUDA_ARCH_LIST` that was used to compile PyTorch somewhere in the library (maybe in `torch.__config__.show()`, but it should be easily accessible stand-alone as well), and let the CPP extensions tooling we have use this information when compiling the extensions, if `TORCH_CUDA_ARCH_LIST` is not already an environment variable.

Also discussed in https://github.com/pytorch/vision/issues/1841#issuecomment-626625664

cc @malfet @yf225 @glaringlee @peterjc123 @ezyang

**Comment by qhaas** [comment]
In the meantime, one can use [CUDA bin utils](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#cuobjdump) to determine this via scripting.  A developer could verify the list upon deploying the dependency before compiling:
```
$ cuobjdump ~/.local/lib/python3.6/site-packages/torch/lib/libtorch_cuda.so -lelf | awk -F. '{print $3}' | grep sm | sort -u
sm_35
sm_37
sm_50
sm_60
sm_61
sm_70
sm_75
```

**Comment by malfet** [comment]
It's been done already and available via `torch.cuda.get_arch_list()`, see 
https://github.com/pytorch/pytorch/blob/d3cb065b2fb59cdd715f7e2c55d9246795cd8152/torch/cuda/__init__.py#L411-L418
