### ISSUE TITLE
Adding typing_extensions as a dependency of pytorch

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#38221]
## 🚀 Feature

Make the `typing_extensions` dependency non-optional to better support type annotations in pytorch.

## Motivation

All type annotations are being moved inline (see gh-16574) and the aim is to make all code using pytorch type-checkable. In gh-38201 we ran into needing `typing_extensions`, in that case to use `Literal`. The `typing_extensions` package is already an optional dependency; the JIT is using `Final` (see `torch._jit_internal.py`).

There are multiple features of `typing_extensions` that will come in handy beyond `Literal` and `Final`, such as `Protocol` and `Text`.

## Pitch

I think it needs to be added in the following places:

- [ ] `install_requires` in `setup.py`
- [ ] `requirements.txt`
- [ ] docs: `README.md`
- [ ] wiki: https://github.com/pytorch/pytorch/wiki/Guide-for-adding-type-annotations-to-PyTorch
- [ ] build scripts in https://github.com/pytorch/builder

## Alternatives

Keep it optional, don't use `Literal`, `Final`, etc.

cc @ezyang @gchanan @zou3519 @malfet @rgommers

**Comment by ezyang** [comment]
Yes, I think this would be quite useful. Not sure how easy this will be to fix; might be as simple as adding it to the dep list... or maybe not.

**Comment by rgommers** [comment]
Looks like it should be pretty straightforward, it's pure Python and packaged in conda as well, so don't see any major stumbling blocks. I'll give it a go.
