### ISSUE TITLE
RuntimeError: [enforce fail at context_gpu.cu:239] . peer mapping resources exhausted

### ISSUE THREAD

**Issue by liuchanglab** [pytorch/pytorch#38223]
When I use workspace..FeedBlob("image", image,  device_option= device_option) for GPU memory
It raise error: [enforce fail at context_gpu.cu:239] . peer mapping resources exhausted
What is the problem?

## To Reproduce
1、pip install torch
2、from caffe2.python import core, workspace
3、workspace feedblob get an error

python 3.7
[GCC 7.3.0] :: Anaconda, Inc. on linux
It is ok for create memory use torch

    workspace.FeedBlob("image", image,  device_option= device_option)
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/workspace.py", line 353, in FeedBlob
    return _Workspace_feed_blob(ws, name, arr, device_option)
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/workspace.py", line 712, in _Workspace_feed_blob
    return ws.create_blob(name).feed(arr, device_option)
  File "/root/anaconda3/lib/python3.7/site-packages/caffe2/python/workspace.py", line 742, in _Blob_feed
    return blob._feed(arg, device_option)
RuntimeError: [enforce fail at context_gpu.cu:239] . peer mapping resources exhausted

**Comment by liuchanglab** [comment]
I have fixed this error by reducing the device from 4 to 1 in docker:
--device /dev/nvidia0:/dev/nvidia0  --device /dev/nvidia1:/dev/nvidia1  --device /dev/nvidia2:/dev/nvidia2  --device /dev/nvidia3:/dev/nvidia3

to  only use --device /dev/nvidia0:/dev/nvidia0

**Comment by GuanhuaWang** [comment]
I had the same issue. Reducing device should not the correct solution if we want to do in-parallel training/serving
