### ISSUE TITLE
python3--no module named PIL

### ISSUE THREAD

**Issue by ljh0279** [pytorch/pytorch#3825]
when i Loading and normalizing CIFAR10, said  that 'from PIL import Image
ModuleNotFoundError: No module named 'PIL''. 
However, PIL only supports python2.7, how can i solve it?

**Comment by Gosicfly** [comment]
just try this:
pip3 install pillow

**Comment by ljh0279** [comment]
pillow is already installed. However, it does not work.

**Comment by zou3519** [comment]
I would recommend uninstalling Pillow, PIL (if they exist) and reinstalling pillow.
Something like:
```
pip uninstall Pillow
pip uninstall PIL
pip install Pillow
```
In the future you should post your question to https://discuss.pytorch.org/ , we like to keep issues on github to PyTorch-only bugs.

**Comment by ljh0279** [comment]
ok. thank you! it works.  I will post these questions to there in the future.

**Comment by KingCyrus** [comment]
> I would recommend uninstalling Pillow, PIL (if they exist) and reinstalling pillow.
> Something like:
> 
> ```
> pip uninstall Pillow
> pip uninstall PIL
> pip install Pillow
> ```
You saved my career! I have been on this for weeks. Thanks.

**Comment by lukhuak** [comment]
It works in:
![Capture](https://user-images.githubusercontent.com/51322089/75117577-2a731880-56a5-11ea-86c7-0069bf94e2dd.PNG)
 
Set path of NetBeans11.2 IDE to the interpreter anaconda in python 3.7.4

>>> import cv2
>>> import numpy as np
>>> from PIL import Image

**Comment by indolentdeveloper** [comment]
you might get below error in mac.

WARNING: The directory '/Users/<username>/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that director

user -H option to uninstall

e.g. sudo -H pip3 uninstall PIL

**Comment by uaahacker** [comment]
C:\Users\uaahacker>pip uninstall Pillow
Found existing installation: pillow 7.2.0
Uninstalling pillow-7.2.0:
  Would remove:
    c:\users\uaahacker\anaconda3\lib\site-packages\pil\*
    c:\users\uaahacker\anaconda3\lib\site-packages\pillow-7.2.0.dist-info\*
Proceed (y/n)? y
  Successfully uninstalled pillow-7.2.0

C:\Users\uaahacker>pip uninstall PIL
WARNING: Skipping PIL as it is not installed.

C:\Users\uaahacker>pip install Pillow
Collecting Pillow
  Downloading Pillow-8.0.1-cp38-cp38-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 261 kB/s
Installing collected packages: Pillow
Successfully installed Pillow-8.0.1

C:\Users\uaahacker>pip install PIL
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

C:\Users\uaahacker>

**Comment by Ali-Kamel** [comment]
> I would recommend uninstalling Pillow, PIL (if they exist) and reinstalling pillow.
> Something like:
> 
> ```
> pip uninstall Pillow
> pip uninstall PIL
> pip install Pillow
> ```
> 
> In the future you should post your question to https://discuss.pytorch.org/ , we like to keep issues on github to PyTorch-only bugs.

thank you it worked for me aswell !

**Comment by uaahacker** [comment]
thanks

**Comment by isl-raph** [comment]
Hey guys, to anyone for whom "pip install Pillow" didn't work, you can simply try :
pip3 install Pillow
it worked a treat :)
Thank's a lot ! 

> 
> 
> > I would recommend uninstalling Pillow, PIL (if they exist) and reinstalling pillow.
> > Something like:
> > ```
> > pip uninstall Pillow
> > pip uninstall PIL
> > pip install Pillow
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the future you should post your question to https://discuss.pytorch.org/ , we like to keep issues on github to PyTorch-only bugs.
> 
> thank you it worked for me aswell !
