### ISSUE TITLE
Add support for output padding in ONNX convolution

### ISSUE THREAD

**Issue by boundles** [pytorch/pytorch#3826]
RuntimeError: torch/csrc/autograd/functions/onnx/convolution.cpp:68: symbolic: output padding is not supported.

Pls any solutions?

**Comment by ezyang** [comment]
Yep, seems that it is not currently supported, and it seems ONNX does support the attributes necessary to do this (https://github.com/onnx/onnx/issues/102), we just have to do the output size calculation and do it. Should be a fairly simple patch.

**Comment by boundles** [comment]
So, How long does it take about?

**Comment by anilyuce** [comment]
Also need this, any news on the implementation or has anyone found a work-around?

**Comment by houseroad** [comment]
Create a PR in ONNX to add adjs attributes directly. (Although we can choose output_shape.) Adjs/output_padding is more widely used, and it's worth adding.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/4583
