### ISSUE TITLE
Is Tensor.is_distributed() always going to return False?

### ISSUE THREAD

**Issue by choidongyeon** [pytorch/pytorch#38291]
## 🐛 Bug

I'm studying the code and having difficulty understanding what ```Tensor.is_distributed()``` is supposed to do. As noted in https://github.com/pytorch/pytorch/issues/37442, there is no documentation, so I can only go off of this [this line](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TypeProperties.cpp#L14). But unless I'm missing something, this means that ```is_distributed()``` is always going to return ```False```. The relevant line is copied below:
```
bool is_distributed(const Tensor& self) {
  return false;
}
```

**Comment by ailzhang** [comment]
Yea we should either delete it or document it. We can record progress in #37442. Thanks!
