### ISSUE TITLE
DataLoader for Numpy datasets

### ISSUE THREAD

**Issue by stepelu** [pytorch/pytorch#3830]
Currently the DataLoader’s default collate_fn expects the dataset to return Torch tensors.

Going forward, it makes sense for datasets to be provided by external libraries, instead of being embedded inside of DL frameworks.
The observations library is a good step in this direction that provides many datasets.

It would be nice if PyTorch’s default collate_fn could handle numpy arrays too (returning aggregated versions, still in numpy arrays), as this would make it compatible with that kind of datasets.

**Comment by soumith** [comment]
returning numpy arrays is horribly inefficient, because it goes through the default pickler that is really slow. if you pass around torch.*Tensor, we use a custom pickler that uses system shared memory and runs in a zero copy design.

**Comment by soumith** [comment]
We started supporting numpy ndarray in the default collate_fn at some point.
https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L105-L116
