### ISSUE TITLE
with emit_nvtx, but got nothing except the word:<torch.autograd.profiler.emit_nvtx object at 0xxxxxxx>

### ISSUE THREAD

**Issue by guyiyifeurach** [pytorch/pytorch#38318]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
I use the profile tool to get the time of cuda with conv-one-layer run on gpu, but I get nothing except one word:prof2 is <torch.autograd.profiler.emit_nvtx object at 0x7ff8bd228a50>.I want to see what in the object, but has no ways.And the docs of Pytorch also don't show more information about it.Even the code is I see in one forum of Pytorch. I also think the profile tool of Pytorch is too simple, not enough information with it.
If someone knows the problem, please tell me something, thank you with lot!

![43bdf5453c856db9f62f9accca339a32-685865](https://user-images.githubusercontent.com/32059046/81701652-e66e0380-949c-11ea-8a4a-22b48f6c750f.jpg)
![454d39c9030adeb8adc1e773cfdddd49-614459](https://user-images.githubusercontent.com/32059046/81701656-e8d05d80-949c-11ea-922e-51e0212864fd.jpg)

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by guyiyifeurach** [comment]
![43bdf5453c856db9f62f9accca339a32-685865](https://user-images.githubusercontent.com/32059046/81701837-1ddcb000-949d-11ea-878e-81b021b12dcf.jpg)

**Comment by guyiyifeurach** [comment]
And this is the Pytorch1.0.0 version.

**Comment by albanD** [comment]
Hi,

As you can see in the body of the issue you posted, we use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
