### ISSUE TITLE
How to pass parameters to another model

### ISSUE THREAD

**Issue by norveclibalikci** [pytorch/pytorch#3832]
I want to pass my pre-trained parameters to my new model. They are equlivalent in terms of number of parameters however, this code does not work and I have not found out a workaround it.
`
>>> params = []
>>> for p in old_G.parameters():
>>>   params.append(p)
>>> for i, p in enumerate(new_G.parameters()):   
>>>   p = params[i]
`

**Comment by apaszke** [comment]
`old_G.load_state_dict(new_G.state_dict())`

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
