### ISSUE TITLE
a %= b not supported in TorchScript

### ISSUE THREAD

**Issue by GrzegorzKarchNV** [pytorch/pytorch#38336]
## 🐛 Bug

An attempt to jit script `a %= b` results in an error `unsupported kind of augumented assignment`

## To Reproduce

In interactive Python run
```bash
@torch.jit.script
def mm(a,b):
    a %= b
    return a
```
this will throw an error: 
```bash
NotSupportedError: unsupported kind of augumented assignment: Mod:
  File "<ipython-input-5-dcecdbcf8ec0>", line 3
@torch.jit.script
def mm(a,b):
    a %= b
      ~~ <--- HERE
    return a
```
an alternative with `fmod_` works as expected:
```bash
@torch.jit.script 
def mm(a,b): 
    a.fmod_(b) 
    return a 
```

## Expected behavior

Successful compilation of the scripted function.

cc @suo

**Comment by suo** [comment]
Notes for bootcamp: should be relatively straightforward, a case needs to be added to `emitAugAssignment` and related places in `ir_emitter.cpp`.
