### ISSUE TITLE
Symbol lookup error: undefined symbol: cudnnSetConvolutionGroupCount

### ISSUE THREAD

**Issue by napsternxg** [pytorch/pytorch#3834]
I am getting the following error after using #3831 

```
python: symbol lookup error: /home/username/anaconda3/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: cudnnSetConvolutionGroupCount
```

The error was not present when using `0.2.0` from conda.

As per the discussion on #3831 with @apaszke , I re-ran the build process and searching for CUDNN in the build  logs shows the following:

```
$ grep -i cudnn ~/Codes/pytorch/build.log 
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.0.4  (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
creating build/lib.linux-x86_64-3.5/torch/backends/cudnn
copying torch/backends/cudnn/__init__.py -> build/lib.linux-x86_64-3.5/torch/backends/cudnn
copying torch/backends/cudnn/rnn.py -> build/lib.linux-x86_64-3.5/torch/backends/cudnn
-- Detected cuDNN at /usr/local/cuda/lib64, /usr/local/cuda/include
```

I am trying to pin-point the exact code block which causes the issue, and will post it soon.

**Comment by napsternxg** [comment]
@apaszke here is the build log. 
https://gist.github.com/napsternxg/07f6688f61271dd54939c63d1b1bc8c5

**Comment by soumith** [comment]
@napsternxg i think it might be that your `cudnn.h` in /usr/local/cuda/include is not of version 7, but v6 or v5?

**Comment by napsternxg** [comment]
Hi @soumith, my cudnn.h is version 7. This is what I have:

```
$ grep "_MAJOR" /usr/local/cuda/include/cudnn.h 
#define CUDNN_MAJOR 7
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
```

But, I am going to try the fix suggested at https://github.com/pytorch/pytorch/issues/3567 as well.

**Comment by apaszke** [comment]
And what's the output of `ls /usr/lib/x86_64-linux-gnu/libcudnn.*`?

**Comment by napsternxg** [comment]
@apaszke 

```
$ ls -l /usr/lib/x86_64-linux-gnu/libcudnn.*
lrwxrwxrwx 1 root root        29 Nov 21 22:01 /usr/lib/x86_64-linux-gnu/libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root        17 Oct 27 02:38 /usr/lib/x86_64-linux-gnu/libcudnn.so.7 -> libcudnn.so.7.0.4
-rw-r--r-- 1 root root 217592088 Oct 27 02:38 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.4
```

**Comment by napsternxg** [comment]
Ok I confirm that using the steps from #3567 fixes this issue. 
Basically, the conda version of cudnn was interfering with the installed version. 
I ran `conda uninstall cudnn` and then re-ran `python setup.py install`
Works.
