### ISSUE TITLE
svd_backward() consumes unnecessary amount of memory for tall / fat matrices

### ISSUE THREAD

**Issue by mattorourke17** [pytorch/pytorch#38353]
## 🐛 Bug

For tall or fat input matrices ```A``` to ```svd```, the ```svd_backward``` function consumes an unnecessary amount of memory. Consider the following source code snippet from ```svd_backward```:

```cpp
  auto ut = u.transpose(-2, -1);
  auto im = at::eye(m, self.options());
  auto in = at::eye(n, self.options());
  auto sigma_mat = sigma.diag_embed(/*offset=*/0, /*dim1=*/-2, /*dim2=*/-1);
  auto sigma_mat_inv = sigma.pow(-1).diag_embed(/*offset=*/0, /*dim1=*/-2, /*dim2=*/-1);
  auto sigma_sq = sigma.pow(2);
  auto F = sigma_sq.unsqueeze(-2) - sigma_sq.unsqueeze(-1);
  // The following two lines invert values of F, and fills the diagonal with 0s.
  // Notice that F currently has 0s on diagonal. So we fill diagonal with +inf
  // first to prevent nan from appearing in backward of this function.
  F.diagonal(/*offset=*/0, /*dim1=*/-2, /*dim2=*/-1).fill_(INFINITY);
  F = F.pow(-1);

  Tensor u_term, v_term;

  if (gu.defined()) {
    u_term = at::matmul(u, at::matmul(F.mul(at::matmul(ut, gu) - at::matmul(gu.transpose(-2, -1), u)), sigma_mat));
    if (m > k) {
      u_term = u_term + at::matmul(im - at::matmul(u, ut), at::matmul(gu, sigma_mat_inv));
    }
    u_term = at::matmul(u_term, vt);
  } else {
    u_term = at::zeros_like(self, LEGACY_CONTIGUOUS_MEMORY_FORMAT);
  }

  if (gv.defined()) {
    auto gvt = gv.transpose(-2, -1);
    v_term = at::matmul(sigma_mat, at::matmul(F.mul(at::matmul(vt, gv) - at::matmul(gvt, v)), vt));
    if (n > k) {
      v_term = v_term + at::matmul(sigma_mat_inv, at::matmul(gvt, in - at::matmul(v, vt)));
    }
    v_term = at::matmul(u, v_term);
  } else {
    v_term = at::zeros_like(self, LEGACY_CONTIGUOUS_MEMORY_FORMAT);
  }

  return u_term + sigma_term + v_term;
}
```

If our input matrix ```A``` had dimensions ```m x n```, where for example maybe ```m >> n```, this code actually forms an identity matrix ```im``` of size ```m x m``` and then computes another ```m x m``` matrix with ```at::matmul(u, ut)```. For a large but manageable input matrix ```A```, these ```m x m``` matrices can be huge and really take a toll on performance. Given that the final matrix we obtain for the gradient should be the same dimensions as the input matrix, it is clear that it should not be necessary to explicitly form these large matrices. Instead, one only needs to form matrices at largest ```m x n``` by distributing the matrix multiplications.

Explicilty, if this line:
```cpp
u_term = u_term + at::matmul(im - at::matmul(u, ut), at::matmul(gu, sigma_mat_inv));
```
is changed to something like
```cpp
auto tmp = at::matmul(gu, sigma_mat_inv);
u_term = u_term + ( tmp - at::matmul(u, at::matmul(ut, tmp)) );
```
then only ```m x n``` matrices are formed and operated on.

An identical consideration can be made in the case ```n >> m``` with the line:
```cpp
v_term = v_term + at::matmul(sigma_mat_inv, at::matmul(gvt, in - at::matmul(v, vt)));
```

cc @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by vincentqb** [comment]
Have you considered some of other implementations we have? See [here](https://github.com/pytorch/pytorch/pull/29488).

**Comment by nikitaved** [comment]
LOBPCG and low-rank SVD do not support backward yet, I am working on it now.

The code from above could be modified to eliminate the Identity matrix, as it is not needed explicitly.
The `mxm` projection matrix is needed, but, I presume, it is possible to use some associativity to lighten the memory/computational burden a bit, exactly as you suggest, @mattorourke17.
Would you like to submit a PR?
