### ISSUE TITLE
Implementing deg2rad, rad2deg

### ISSUE THREAD

**Issue by aayn** [pytorch/pytorch#38372]
It's finally here :slightly_smiling_face:!  Since I'm somewhat new, I'd like to start with a simple one. Let me try `deg2rad` and `rad2deg`. What would be right place to put that @mruberry?  #38349

Also, I don't have write access to assign labels.

cc @mruberry

**Comment by mruberry** [comment]
Cool!

Take a look at how similar functions, like sin, are implemented. See: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/UnaryOps.cpp for the device-independent part of the code. Then you have the CPU and CUDA-specific parts in ATen/native/cpu and ATen/native/cuda, respectively.

**Comment by aayn** [comment]
Gotcha, thanks!

**Comment by cloudhan** [comment]
I'd suggest starting with #24507 to port some trivail legacy TH functions to ATen to get some sense of kernel dispatch. After that, implementing `deg2rad` and the like will be straightforward.

**Comment by aayn** [comment]
Okay, will do! However, at first glance, most trivial legacy functions seem to already have been ported. I'll probably study a few of those PRs in detail and then start implementing this.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/38852 has landed!
