### ISSUE TITLE
Implementing HyperLSTM

### ISSUE THREAD

**Issue by Ar-Kareem** [pytorch/pytorch#38383]
## 🚀 Feature
Add implementation for HyperLSTM. 
A model described in [Ha et al. (2016)](https://arxiv.org/pdf/1609.09106.pdf) published by Google Research and accepted by ICLR 2017.
The approach uses an LSTM, which acts as a hypernetwork, to generate the weights for another LSTM.

## Motivation

The results of the proposed network as given in the paper are state-of-the-art (although this was 3/4 years ago). Excerpt from the abstract:
> main result is that hypernetworks can generate non-shared weights for LSTM and achieve near state-of-the-art results on a variety of sequence modelling tasks including character-level language
modelling, handwriting generation and neural machine translation, challenging
the weight-sharing paradigm for recurrent networks.

Most notably, the paper was cited by 350 publications [as shown in Google Scholar](https://scholar.google.com/scholar?cites=3668354792918495805&as_sdt=800005&sciodt=0,15&hl=en). The model was also used as the decoder to ['Sketch-RNN'](https://arxiv.org/abs/1704.03477) where they state that 

> For the decoder RNN, we use HyperLSTM, as this type of RNN cell excels at sequence generation tasks [8]. The ability for HyperLSTM to spontaneously augment its own weights enables it to adapt to many different regimes in a large diverse dataset.

(Possible Conflict Of Interest, HyperLSTM and Sketch-RNN were both developed and published by Google Brain)

The 'Sketch-RNN' paper was also cited by 265 publications [as shown in Google Scholar](https://scholar.google.com/scholar?cites=2337146750300919321&as_sdt=800005&sciodt=0,15&hl=en).

## Pitch

I would like someone to give me the green light to start working on the model. I would like to implement this and hopefully make it as high quality as I can. Following the Python Contribution Guide, I hopefully fulfilled the requirement of 

> “Do we want this operator/optimizer?”  Giving evidence for its utility, e.g., usage in peer reviewed papers, or existence in other frameworks, helps a bit when making this case.

## Alternatives

Since this is a model, the alternative to implementing it is the decision that this doesn't fit the PyTorch library. And I completely understand if that is the decision.

I hope I managed to follow the Contribution Guidelines and the Code of Conduct.

cc @albanD @mruberry

**Comment by mruberry** [comment]
Hey @Ar-Kareem! First, if you want to make a model with PyTorch: go for it! That's what PyTorch is for. But we don't typically put models into the PyTorch repo (unless they're examples/tutorials). Usually models live in their creators' repositories or in more specific packages like torchvision.

In this case, I'd encourage you to build the model how you like and write a blog post if you'd like to message it to the community. I'm not sure there's much for us to do in that process.

If, however, there's some functionality that HyperLSTM needs that's tricky to implement in PyTorch, then it makes sense to file a more focused issue requesting that functionality.

**Comment by Ar-Kareem** [comment]
I see, that makes sense. Thanks for the response @mruberry.

> If, however, there's some functionality that HyperLSTM needs that's tricky to implement in PyTorch, then it makes sense to file a more focused issue requesting that functionality.

There is one thing, however I don't know if I should open another issue or if it's not really worth discussing.

Inside the hyperLSTM, two regular LSTM's exist. However, one of them needs LayerNormalization applied to the variable `c` (the long term memory) before it is multiplied by the output gate. The original paper on LayerNormalization also describes the same technique. 

Is it worthy to open another issue to request this feature be implemented (a boolean `layerNorm` passed to the LSTM)? Or is this is a niche use-case where it would be better off if I just implement my own variant of an LSTM that includes LayerNormalization.

**Comment by mruberry** [comment]
I would encourage you to start by implementing your own. PyTorch is designed to be a framework/toolkit for you to build neural networks on top of, and not every component will be available "off the shelf." If a component is very hard to implement in current PyTorch or becomes very common, then we would think about making it available in the framework, too.

**Comment by Ar-Kareem** [comment]
Got it, will do. 

Thanks again for the response.
