### ISSUE TITLE
Inefficient data copy between cpu and gpu after inferring-forward

### ISSUE THREAD

**Issue by exploreZJ** [pytorch/pytorch#38386]
## ❓ Questions and Help

I tested a model on gpu. 
data = data.cuda()  0.00166s
out = model(data)  0.00492s
data = torch.from_numpy(np.random.rand(1,1)).cuda()  0.0354s
**After the inferring, a very small numpy.array ([1*1]) is copyed from cpu to gpu, but this step takes 0.0354s. It's incredible！！！！**

But if "out = model(data)" is not processed,  "data = torch.from_numpy(np.random.rand(1,1)).cuda()" takes a very short time. 

What is the key problem? Would switching from calculation on gpu to data copy(gpu-cpu or cpu-gpu) be the the most time-consuming step?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by ezyang** [comment]
CUDA is asynchronous: to get accurate timings, you have to run with `CUDA_LAUNCH_BLOCKING=1`, or synchronize. You're attributing cost of `out = model(data)` to the line below.

If you have more questions about this, please follow up in the forums!
