### ISSUE TITLE
Implement toCFloat() for Variables and numel() = 1 Tensors

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3839]
For convenience, is it possible to do this? Currently, I have to do something like `Variable.data().sum().toCFloat()`, when I prefer to do `Variable.toCFloat()` if I know it's suppose to represent a single number. One reason both `.data().sum()` is needed I think is because Variable.sum() will return a 1-dim tensor, which is not the behavior of Tensor.sum().

**Comment by gchanan** [comment]
I'll look into this; the reason Variable.sum() and Tensor.sum() return different things right now is because we force all Variables to be at least 1-dimensional because we haven't exposed scalars to pytorch.

**Comment by gchanan** [comment]
this is now implemented.
