### ISSUE TITLE
Missing matmul behavior

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#384]
We're missing some cases described in the matrix multiplication PEP for the matmul (`@`) operator:

```python
a = torch.randn(3)
b = torch.randn(3, 2)
print(a @ b)  # currently prints None
print((a.view(1, 3) @ b).squeeze(0))  # should be this
```

```python
a = torch.randn(3)
print(a @ a)  # currently prints None
print(a.dot(a))  # should print this
```

https://www.python.org/dev/peps/pep-0465/#semantics

**Comment by fmassa** [comment]
This should be fixed when https://github.com/pytorch/pytorch/pull/1563/files#r121140809 is implemented for Variables.

**Comment by soumith** [comment]
i guess this was fixed via https://github.com/pytorch/pytorch/issues/1756 's PRs
