### ISSUE TITLE
load_state_dict_from_url() download location inconsistency

### ISSUE THREAD

**Issue by valgur** [pytorch/pytorch#38401]
## 🐛 Bug

The state dict download location for [`torch.hub.load_state_dict_from_url()`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L435) varies depending on whether any of [`torch.hub.list()`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L256), [`torch.hub.help()`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L289) or [`torch.hub.load()`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L323) have been called before or not.

The download location is:
* `$TORCH_HOME/checkpoints` if any of the other functions has not been called before and
* `$TORCH_HOME/hub/checkpoints` after any of them have been called.

Unlike `load_state_dict_from_url()`, the mentioned functions make use of [`_setup_hubdir()`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L107), which appends `/hub` to the [`hub_dir`](https://github.com/pytorch/pytorch/blob/61bea93fca35ad7ace2c9856499d3f478ffb1377/torch/hub.py#L62) global variable.

This inconsistency seems to stem from the changes introduced in PR #32844.

## To Reproduce

1. 
```python
import torch.hub

torch.hub.load_state_dict_from_url('https://download.pytorch.org/models/mobilenet_v2-b0353104.pth')
```
Prints *Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /home/martin/.cache/**torch/checkpoints**/mobilenet_v2-b0353104.pth*

2.

```python
import torch.hub

torch.hub.list('pytorch/vision')
torch.hub.load_state_dict_from_url('https://download.pytorch.org/models/mobilenet_v2-b0353104.pth')
```
Prints *Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /home/martin/.cache/**torch/hub/checkpoints**/mobilenet_v2-b0353104.pth*

## Expected behavior

Download location is always either `$TORCH_HOME/checkpoints` or `$TORCH_HOME/hub/checkpoints`.

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 2.7 / 3.8

cc @ailzhang

**Comment by ailzhang** [comment]
Thanks for the report @valgur ! Would you mind submitting a fix for it btw?
