### ISSUE TITLE
CUDA irfft may be doing unnecessary cloning of input

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#38413]
Context:
1. In [cuFFT,](https://docs.nvidia.com/cuda/cufft/index.html#data-layout)
    > Out-of-place complex-to-real FFT will overwrite input buffer if custom strides are set by the user.
2. We therefore had this check in `CuFFTPlanCache.h`
https://github.com/pytorch/pytorch/blob/899a075b25300460614169394588b22937a900f4/aten/src/ATen/native/cuda/CuFFTPlanCache.h#L177-L192
3. Users still reported irfft input being modified on T4 https://github.com/pytorch/pytorch/issues/34551
4. An unconditional input cloning for irfft seemed to have fixed it https://github.com/pytorch/pytorch/pull/35219

We should figure out why the previous check doesn't detect all the cases, whether it is a bug in our check or in cuFFT. I don't have access to a T4 so I write this issue to document the situation in case anyone wants to take a look.

cc @ngimel @mruberry @peterbell10 @VitalyFedyunin

**Comment by peterbell10** [comment]
>1. In [cuFFT](https://docs.nvidia.com/cuda/cufft/index.html#data-layout),
>> Out-of-place complex-to-real FFT will overwrite input buffer if custom strides are set by the user.

Today, that same documentation says:
>Out-of-place complex-to-real FFT will always **overwrite** input buffer.

So, it seems this was just an error in the CuFFT documentation.

**Comment by ngimel** [comment]
Thanks for checking, @peterbell10 ! Closing the issue, the clone looks to be necessary.
