### ISSUE TITLE
Indexing Variable with repeated indices

### ISSUE THREAD

**Issue by trypag** [pytorch/pytorch#3844]
Hey,
I have been thinking about this problem for a few days now, trying to get some help from the forum [also](https://discuss.pytorch.org/t/indexing-with-repeating-indices-numpy-add-at/10223/6), but none seems to work. The problem might seem simple, I found no solution to it :

let's say you have a first index tensor `m` containing indices between 0 and 5 : 
```
Variable containing:
(0 ,.,.) = 
  4  4  3  0
  3  4  2  3
  2  3  1  1
  1  4  3  1
[torch.LongTensor of size 1x4x4]
```

and a second index tensor `p` of same size, containing indices between 0 and 5 : 
```
Variable containing:
(0 ,.,.) = 
  1  1  1  1
  1  1  1  1
  1  1  1  1
  1  1  1  1
[torch.LongTensor of size 1x4x4]
```

finally a matrix `g` of size 5x5 initially set to 0.
```
g = torch.LongTensor(5,5).zero_()
```

The indexing would proceed like this, pair each index from tensor `m` and `p` and increment the `g` matrix at each index pair.
```
g[m, p] += 1
```

For example for the first row of `m` and `p`, I would want this behaviour:
```
g[1, 4] += 1
g[1, 4] += 1 # same index as previous
g[1, 3] += 1
g[1, 0] += 1
```

you will notice however that the output of `g` is :
```
(0 ,.,.) = 
  0  1  0  0  0
  0  1  0  0  0
  0  1  0  0  0
  0  1  0  0  0
  0  1  0  0  0
[torch.LongTensor of size 1x5x5]
```

The current indexing only increases g[1, 4] by 1 instead of 2 (because of repeated indices). There is an equivalent to this in numpy with https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ufunc.at.html

Soumith pointed me to `index_add_`, not sure this would be a good candidate however it's an inplace op, not compatible with autograd.

Thanks :)

**Comment by vadimkantorov** [comment]
For the inplace `index_add_`, there is an undocumented copying wrapper on variables: `index_add` ( https://github.com/pytorch/pytorch/issues/1885)

**Comment by trypag** [comment]
Good to know, thank you @vadimkantorov .

I got an answer to this problem on the [forum](https://discuss.pytorch.org/t/indexing-with-repeating-indices-numpy-add-at/10223/12). I did not try it yet as it requires last version (v0.3), but from the spec this is precisely what I need, so I will close this issue for now ! 

Thanks to the community

http://pytorch.org/docs/master/tensors.html#torch.Tensor.put_
