### ISSUE TITLE
JitTest.testAutogradProfiler is broken in test_misc.cpp

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#38443]
## 🐛 Bug

The test here https://github.com/pytorch/pytorch/blob/master/test/cpp/jit/test_misc.cpp#L1186 is broken. I'm not sure whether these tests run in any of the CI systems, but the test does not pass running locally. It looks like the tests expects a count to be 200, but it is actually 600 from running it locally (https://github.com/pytorch/pytorch/blob/master/test/cpp/jit/test_misc.cpp#L1211)

cc @suo @mruberry

**Comment by SplitInfinity** [comment]
I don't think it runs in CI because it's not a part of the tests listed by `build/bin/test_jit  --gtest_list_tests`, and I'm curious how you ran it in the first place.

This test was added in [#16580](https://github.com/pytorch/pytorch/pull/16580) by @zdevito and disabled (maybe by accident?) in [#17947](https://github.com/pytorch/pytorch/pull/17947) by @suo. Do either of you two know why this test was not included in the migration from `no-gtest.cpp` to `gtest.cpp`?

**Comment by rohan-varma** [comment]
@SplitInfinity I was able to run it by adding the test to `tests/cpp/jit/tests.h` and then run it internally with buck.

**Comment by SplitInfinity** [comment]
That makes sense; what was the underlying motivation for doing so?

**Comment by rohan-varma** [comment]
I was working with `RecordProfile` for an unrelated change, and ran into an issue and found this test that was doing something similar as I was trying to do. So I ran this test, which confirmed that it seems like a general issue with the profiler

**Comment by SplitInfinity** [comment]
Seems legit; let's wait to hear from zdevito and suo who probably have more context on why this test was disabled during some test migration work.

**Comment by suo** [comment]
I honestly have no clue about this test, maybe @zdevito @jamesr66a have some context?

**Comment by jamesr66a** [comment]
I don't have context on this test specifically but reading through it, hardcoding the number `200` is probably sub-optimal testing practice. We're now recording many more operations in profiling now, so that number probably just needs to be updated to reflect higher-fidelity profile traces

**Comment by SplitInfinity** [comment]
But does anyone know why it was disabled instead of deleted?

**Comment by aaronenyeshi** [comment]
Looks like this was fixed in https://github.com/pytorch/pytorch/commit/22c6dafd33ab57d00ea0d5caa106f15494d1e0f6 . Closing this old issue.
