### ISSUE TITLE
[Feature] View a floating point tensor as complex tensor, and vice versa

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#38458]
## 🚀 Feature

```python
t = torch.randn(M, N, dtype=torch.complex64)
r = t.view_as_floating()
```
gets a float tensor of shape `(M, N, 2)` and dtype `torch.float32` **sharing the same data_ptr**. That is: `r[..., 0] == t.real()` and `r[..., 1] == t.imag()`.

```python
t = torch.randn(M, N, 2, dtype=torch.float32)
r = t.view_as_complex()
```
gets a complex64 tensor of shape `(M, N)` and dtype `torch.complex64` **sharing the same data_ptr**. That is, `r == t[..., 0] + t[..., 1] i`.

This operator could be easy to implement, and most importantly, this would allow user to do any transformation `x + yi --> f(x) + f(y)i` easily and efficiently, and many operators in PyTorch could be implemented by first viewing as floating, do the op, and the view it back as complex.

**This behavior is justified by the [array-oriented access of `std::complex`](https://en.cppreference.com/w/cpp/numeric/complex) (and `c10::complex`)**

cc @ezyang @anjali411 @dylanbespalko

**Comment by vadimkantorov** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/29013

**Comment by zasdfgbnm** [comment]
@vadimkantorov Thanks for the cross-reference! I was thinking about it, but I don't remember the issue number.

**Comment by vadimkantorov** [comment]
Also, there may be some need for constructing a complex tensor out of two separate real + imaginary tensors. Copying may be needed, though copying may be avoided if they are just slices of a tensor (but this is a bit magical)

**Comment by zasdfgbnm** [comment]
@vadimkantorov Do you mean something like `torch.complex(real_tensor, imag_tensor)` that does
```python
torch.complex(tensor([a, b]), tensor([c, d])) --> tensor([a+ci, b+di])
```
? That sounds like a great idea to me, maybe it deserve a separate issue for discussion?

**Comment by zasdfgbnm** [comment]
Another benefit is, when `view_as_floating` is implemented, then `torch.real` could be implemented as `torch.view_as_floating(z)[..., 0]` which is copy-free.

**Comment by vadimkantorov** [comment]
> @vadimkantorov Do you mean something like `torch.complex(real_tensor, imag_tensor)` that does
> 
> ```python
> torch.complex(tensor([a, b]), tensor([c, d])) --> tensor([a+ci, b+di])
> ```
> 
> ? That sounds like a great idea to me, maybe it deserve a separate issue for discussion?

Yep, that's what I meant

**Comment by vadimkantorov** [comment]
> Another benefit is, when `view_as_floating` is implemented, then `torch.real` could be implemented as `torch.view_as_floating(z)[..., 0]` which is copy-free.

Again, a little nuisance about naming, since in theory one can imagine complex integer pairs (quantized or maybe some Zn for cryptography needs), then `view_as_floating` would be confusing

**Comment by vadimkantorov** [comment]
`view_as_real`, `view_as_complex` would be more clear opposition. but if you also implement `real_view`, there may be more confusion :) so may be `reinterpret(torch.complex)`, `reinterpret(torch.real)`? except `torch.real` could be synonym for `tensor.real()`. Argh, naming is hard.

Also I think property `.real` and `.imag` were recided for compat with NumPy, so not sure if `torch.real(x)` even exists now or not

**Comment by anjali411** [comment]
`torch.real` and `torch.imag` have been disabled for complex and the plan is to add `tensor.real`, `tensor.imag`, `tensor.view_as_real`, `tensor.view_as_complex` views. The latter two views would skip a copy to switch from m x n x 2 floating point tensor to an m x n complex tensor

**Comment by anjali411** [comment]
btw numpy does something that makes no sense at all
```
>>> a = np.array([1., 2., 3.])
>>> b = a.view(np.complex64)
>>> b
array([ 0.+1.875j,  0.+2.j   ,  0.+2.125j], dtype=complex64)
>>> a.dtype
dtype('float64')
```

**Comment by vadimkantorov** [comment]
Related request for another consructor from polar representation: https://github.com/pytorch/pytorch/issues/38879#issue-622642171

one variant to merge both:
```python
torch.tensor(re = re, im = im, dtype = torch.complex64)
torch.tensor(mag = mag, phase = phase, dtype = torch.complex64)
```
but probably worth checking what numpy / matlab / tf do...

**Comment by anjali411** [comment]
@vadimkantorov `numpy` doesn't seem to have a specific API for it. 
`matlab` has a complex [constructor](https://www.mathworks.com/help/matlab/ref/complex.html) (`z=complex(a, b)  z=complex(x)`) 
[`tensorflow`](https://www.tensorflow.org/api_docs/python/tf/dtypes/complex) has an API similar to `matlab` 
```
real = tf.constant([2.25, 3.25])
imag = tf.constant([4.75, 5.75])
tf.complex(real, imag)
```
`[jax](https://jax.readthedocs.io/en/latest/_modules/jax/lax/lax.html#complex)` has something similar as well:
```
>>> jax.lax.complex(np.array([1.]), np.array([2.]))
DeviceArray([1.+2.j], dtype=complex64)
>>>
```

Since most of them have a somewhat similar API, I think we should follow that as well. I think having an additional `kwarg` that specifies if the input is in `cartesian` or `polar` coordinate would be useful to incorporate complex construction from absolute values and angle.
```
torch.complex(re, im)
torch.complex(abs, angle, polar=True)
```
where `re`, `im`, `abs` and `angle` are tensors.

cc. @ezyang @dylanbespalko @mruberry
