### ISSUE TITLE
Should torch.real, torch.imag be implemented as a view?

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#38468]
Complex numbers obey [array-oriented access](https://en.cppreference.com/w/cpp/numeric/complex), therefore, we could implement `torch.real` and `torch.imag` just by creating a new tensor metadata and reuse the same data_ptr. This implementation will make `real` and `imag` copy-free, therefore improving performance. The user would also be able to change the real/imag part of a tensor in place by doing something like
```python
complex_tensor.real().zero_()
```

If not, I suggest we should have at least a `complex_tensor.real_view()` and `complex_tensor.imag_view()` for the same purpose.

Related issue: https://github.com/pytorch/pytorch/issues/38458#issuecomment-628517520

cc @ezyang @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
This is planned but #33950 needs to be finished first. Fortunately Kurt has a nearly complete patch

**Comment by ShawnZhong** [comment]
Seem to be resolved in #39033
