### ISSUE TITLE
C++ Autograd lacks .relu()

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#3847]
Instead we have to do clamp_min(0), which is not very pretty.

**Comment by apaszke** [comment]
You can always bootstrap the function module :wink:
```cpp
namespace F {
inline Tensor relu(Tensor x) { return x.clamp_min(0); }
}
```

**Comment by colesbury** [comment]
We should just stick this as a NativeFunction since it's so commonly used.

**Comment by apaszke** [comment]
The only problem I'd have with native functions is that it would get added to the tensor interface, and I think it's cleaner to keep it in `nn` (as it's not really a linear algebra op, but a nonlinearity commonly used in NNs). But no big deal

**Comment by ezyang** [comment]
If you declare it as a function-only, it doesn't get added as a method, does it?

**Comment by ebetica** [comment]
@apaszke `pprelu` and `rrelu` already exists, so it's quite confusing why relu would not.

**Comment by apaszke** [comment]
uh ok...

**Comment by vishwakftw** [comment]
Could I work on a PR to implement ReLU in C++?
