### ISSUE TITLE
torch.einsum does not pass equation argument to __torch_function__ API

### ISSUE THREAD

**Issue by alondj** [pytorch/pytorch#38479]
## 🐛 Bug

when delegating torch.einsum call to an object which implements
`__torch_function__` API the equation argument is not passed resulting in the error.
```TypeError: einsum(): argument 'equation' (position 1) must be str, not Tensor```

this was tested on pytorch 1.5.0

I've actually found the cause of this bug and have written a fix.

the following script illustrates the problem and the proposed solution

## To Reproduce

```python 
import torch

class Wrapper():
    def __init__(self,data):
        self.data = data
    
    def __torch_function__(self, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}

        #unwrap inputs if necessary
        def unwrap(v):
            return v.data if isinstance(v,Wrapper) else v
        args = map(unwrap,args)
        kwargs = {k:unwrap(v) for k,v in kwargs.items()}

        return func(*args, **kwargs)



# fixed einsum implementation
from torch import Tensor,_VF
from torch._overrides import has_torch_function,handle_torch_function
def fixed_einsum(equation,*operands):
    if not torch.jit.is_scripting():
        if any(type(t) is not Tensor for t in operands) and has_torch_function(operands):
            # equation is not passed
            # return handle_torch_function(einsum, operands, *operands)
            return handle_torch_function(fixed_einsum, operands, equation,*operands)
    if len(operands) == 1 and isinstance(operands[0], (list, tuple)):
        # the old interface of passing the operands as one list argument
        operands = operands[0]

        # recurse incase operands contains value that has torch function
        #in the original implementation this line is omitted
        return fixed_einsum(equation,*operands)

    return _VF.einsum(equation, operands)


if __name__ == "__main__":
    print(torch.__version__)
    # uncomment to use fixed einsum
    # torch.einsum = fixed_einsum

    #operands are wrapped
    x = Wrapper(torch.randn(5))
    y = Wrapper(torch.randn(4))
    assert torch.allclose(torch.einsum('i,j->ij',x, y),torch.ger(x,y))  # outer product
    print("works with wrapped inputs")    

    #old interface operands is a list
    a = Wrapper(torch.randn(2,3))
    b = Wrapper(torch.randn(5,3,7))
    c = Wrapper(torch.randn(2,7))
    assert torch.allclose(torch.einsum('ik,jkl,il->ij', [a, b, c]),torch.nn.functional.bilinear(a,c,b)) # bilinear interpolation
    print("works with old API operands is list")
    
    #equation is wrapped
    As = Wrapper(torch.randn(3,2,5))
    Bs = Wrapper(torch.randn(3,5,4))
    equation = Wrapper('bij,bjk->bik')
    assert torch.allclose(torch.einsum(equation, As, Bs),torch.matmul(As,Bs)) # batch matrix multiplication
    print("works with equation wrapped")

    #see that it also works with plain tensors
    x = torch.randn(5)
    y = torch.randn(4)
    assert torch.allclose(torch.einsum('i,j->ij',x, y),torch.ger(x,y)) 
    print("works with no wrapped values")



```

cc @albanD @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @alondj!

Also cc @rgommers since this is a torch_function issue.

**Comment by rgommers** [comment]
Thanks for reporting @alondj. That's a clear bug. 

Your example can make a good regression test. I'd also like to fix the existing test (generated by `generate_tensor_like_override_tests` in `test/test_overrides.py`) which didn't catch this.

**Comment by rgommers** [comment]
gh-38741 will fix this. thanks for providing that fix @alondj!

> Your example can make a good regression test. I'd also like to fix the existing test (generated by `generate_tensor_like_override_tests` in `test/test_overrides.py`) which didn't catch this.

This is a little convoluted. It's hard to get at the expected types for all functions. @hameerabbasi has a plan for this, connected to his work on extending `__torch_function__`. It should become a lot easier once there's complete type annotations. Until that time we decided the best strategy is to fix issues as they come up. There have been only two so far, `cat` and `einsum`, and @hameerabbasi went through the full list of covered functions again.

**Comment by alondj** [comment]
@rgommers glad I could help
