### ISSUE TITLE
Plan for supporting cudnn.is_acceptable in ATen

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3848]
Things we need to continue to support:

1. `torch.backends.cudnn.enabled`. This is the current method for enabling/disabling cudnn globally, but obviously ATen doesn't have access to Python global variables.  Perhaps the right thing to do is put a flag tracking CuDNN being enabled or disabled in the Context (which is our existing global state sin bin) which we can check, and then somehow monkeypatch the Python module to intercept when this variable is set. But this is a bit annoying to do because we have to do something like https://stackoverflow.com/questions/2447353/getattr-on-a-module
2. Emitting a warning when you try to use a CuDNN enabled function, but PyTorch was not built without CuDNN support. I guess we can just print something to std::cerr? I feel dirty doing this. But it seems most expedient.

**Comment by apaszke** [comment]
Regarding 2, I'd rather use Python warnings. ATen could have a "warning callback" that would be set to a function which prints things to `cerr` by default, but you could change it (to e.g. emit a Python warning).

**Comment by colesbury** [comment]
(1) sounds good. I guess we do the hack you referred to.

What situations are you referring to in (2)? If you use `conv2d` without cuDNN, that should just use the fastest available method. (e.g. `cuDNN`, `NNPACK`, whatever AMD provides, etc.) If you use something that's explicitly cuDNN (e.g. `cudnn_conv2d`), then that should be an error if cuDNN isn't supported. We don't currently warn if in `conv2d` if there's no cuDNN support.

Callbacks are annoying and complicate the code.  If we really want to warn that there isn't cuDNN support, do it when we initialize CUDA (but I don't think it's worth it)

**Comment by ezyang** [comment]
> What situations are you referring to in (2)? If you use conv2d without cuDNN, that should just use the fastest available method. (e.g. cuDNN, NNPACK, whatever AMD provides, etc.) If you use something that's explicitly cuDNN (e.g. cudnn_conv2d), then that should be an error if cuDNN isn't supported. We don't currently warn if in conv2d if there's no cuDNN support.
>
> Callbacks are annoying and complicate the code. If we really want to warn that there isn't cuDNN support, do it when we initialize CUDA (but I don't think it's worth it)

Today, if you use `conv2d` with CUDA and without cuDNN, you get a warning telling you that cuDNN is not used. This seems like a relatively useful warning that helps people know if they've messed up their install. It's fine for us to decide that callbacks are too annoying for us to support this; I just want to explicitly acknowledge it.

**Comment by apaszke** [comment]
Yeah I think there's little point in warning that we can't use cuDNN if you're not even asking for it. I can't see a problem with implementing `at::warn` that would dispatch to a callback (this logic lives in a single place).

**Comment by ezyang** [comment]
This is fixed now.

**Comment by ezyang** [comment]
Actually, no, the warnings are missing.

**Comment by ezyang** [comment]
I don't plan to add warnings
