### ISSUE TITLE
[Feature Request] Can torch.quantization support ReLU6 ?

### ISSUE THREAD

**Issue by Lyken17** [pytorch/pytorch#38516]
## 🚀 Feature & Motivation

Currently, `torch.quantization.fuse_modules` and [`qconv.cpp`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv.cpp#L701) only support original relu. However, its variants such as ReLU6 are widely used in models like [MobilenetV2](https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py#L39). Could you add support for that?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by raghuramank100** [comment]
With quantization, we learn the output ranges by collecting statistics.  Using ReLU6 restricts the output range to [0,6] which is not compatible with QAT. Please replace ReLU6 with ReLU instead

**Comment by supriyar** [comment]
Closing as this doesn't seem like something we will support. @raghuramank100 feel free to re-open if that is not the case.

**Comment by jerryzh168** [comment]
does it make sense to support conv - relu6 fusion in post training quantization?

**Comment by LMerCy** [comment]
> collecting



> With quantization, we learn the output ranges by collecting statistics. Using ReLU6 restricts the output range to [0,6] which is not compatible with QAT. Please replace ReLU6 with ReLU instead

why

> With quantization, we learn the output ranges by collecting statistics. Using ReLU6 restricts the output range to [0,6] which is not compatible with QAT. Please replace ReLU6 with ReLU instead

why? relu restricts the output range to [0, MAX]，relu6 just restricts the upper limits.

**Comment by LMerCy** [comment]
> With quantization, we learn the output ranges by collecting statistics. Using ReLU6 restricts the output range to [0,6] which is not compatible with QAT. Please replace ReLU6 with ReLU instead

why ? ReLU restricts the output range to [0, MAX], ReLU6 just restricts the upper limitation.
