### ISSUE TITLE
Improve error message for RuntimeError: inconsistent tensor size in RNN

### ISSUE THREAD

**Issue by oneTaken** [pytorch/pytorch#3851]
I run RNN sucessfully with the code.
```
rnn = nn.RNN(features, hidden_size, num_layers)
o, hidden = rnn(x, hidden)
```
and I run embedding example. Then, got RuntimeError.
```
RuntimeError: inconsistent tensor size, expected r_ [5 x 25], t [5 x 25] and src [2 x 25] to 
have thesame number of elements, but got 125, 125 and 50 elements respectively at 
/opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/generic/THTensorMath.c:887
```
I set `batch_first=True` to use `Embedding`
```
x.size is [5, 8, 15]
hidden_size is [5, 2, 25]
```
nothing seems wrong.
And the error info seems not the dim problem?
The error is so strange.

**Comment by zou3519** [comment]
What exactly do you mean by "embedding example"? Could you provide a code snippet that causes the RuntimeError?

**Comment by oneTaken** [comment]
@zou3519 
To better reproduce the error, I use the official code example of [torch.nn.RNN](http://pytorch.org/docs/master/nn.html?highlight=rnn#recurrent-layers)
The origin runs well:
```
rnn = nn.RNN(10, 20, 2, batch_first=False)
input = Variable(torch.randn(5, 3, 10))
h0 = Variable(torch.randn(2, 3, 20))
output, hn = rnn(input, h0)
output.size(), hn.size()
```
Due to use `embedding`, I have to make batch first.
And then , it raises error.
```
rnn = nn.RNN(10, 20, 2, batch_first=True)
input = Variable(torch.randn(5, 3, 10).transpose(0, 1))
h0 = Variable(torch.randn(2, 3, 20).transpose(0, 1))
output, hn = rnn(input, h0)
output.size(), hn.size()
```

```
RuntimeError: inconsistent tensor size, expected r_ [3 x 20], t [3 x 20] and src [2 x 20] to
 have the same number of elements, but got 60, 60 and 40 elements respectively at 
/opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/TH/generic/THTensorMath.c:887
```

**Comment by zou3519** [comment]
Thank you for the example!

The [docs](http://pytorch.org/docs/master/nn.html?highlight=rnn#torch.nn.RNN) say that setting `batch_first=True` means that the first dim of input is the batch, ie, input has size `(batch, seq_len, num_features)`. `h0` however is unchanged, so the following should work:

```
rnn = nn.RNN(10, 20, 2, batch_first=True)
input = Variable(torch.randn(5, 3, 10).transpose(0, 1))
h0 = Variable(torch.randn(2, 3, 20))
output, hn = rnn(input, h0)
output.size(), hn.size()
```

I do agree the error message could be better, though
