### ISSUE TITLE
`strict` keyword doesn't exist in the optimizer's `load_state_dict`

### ISSUE THREAD

**Issue by IssamLaradji** [pytorch/pytorch#3852]
```python
# This works
model.load_state_dict(checkpoint['model_state_dict'], strict=False)

# This gives me "TypeError: load_state_dict() got an unexpected keyword argument 'strict'"
opt.load_state_dict(checkpoint['opt_state_dict'], strict=False)
```
I am using version '0.4.0a0+6dc1fc7'

**Comment by apaszke** [comment]
This is expected. Optimizers don't hold parameters by their names, so there's no way for us to align the state dicts if they are mismatched. You can try to patch the new optimizer yourself by copying state for corresponding parameters, but I don't think it's a tractable problem in general.

**Comment by apaszke** [comment]
I'll close this, but feel free to reopen if you want to suggest an idea for how to auto match the dicts.

**Comment by IssamLaradji** [comment]
Thanks for the quick reply. Is there a reason why optimizer's state dict don't use names like model's state dict ?

**Comment by apaszke** [comment]
Yes. You construct optimizers by giving them a plain list of parameters, so there's no name assignment that they have access to. It might change if we add support for naming Variables
