### ISSUE TITLE
ENH: refactor onnx expecttests

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#38545]
## 🐛 Bug

Fallout from gh-36797, relating to [this comment](https://github.com/pytorch/pytorch/pull/36797#issuecomment-620048920) by @ezyang :

> It's going to suck if we have to codemod all of these tests every time we update our nightly version, even if you can just accept them all automatically. A nice follow up would be to strip out the version number from the expect strings before running the expect test, so we're left with some generic version number so they don't wobble every time we increase the version

In the code that [actually does the comparison](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1145), there is a comment about using `--accept` to regenerate the files rather than fail tests, but I could not find documentation how to use it. Calling `python pytest test/onnx/test_operators.py --accept` did not work. Perhaps it would be better to document updating the files rather than ignoring this one field.

Also worth noting: these tests are run via `scripts/onnx/test.sh`, which calls `pytest test/onnx`, skipping some tests that are slow or not applicable to the environment. It might be worthwhile to refactor this to use pytest-style decorators on the tests rather than hide the choices in a bash file.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @mruberry

**Comment by ezyang** [comment]
You can also set envvar `EXPECTTEST_ACCEPT=1` to accept. We should update the docs, maybe you can submit a PR for that?

> Perhaps it would be better to document updating the files rather than ignoring this one field.

I think we should do both :)

**Comment by neginraoof** [comment]
@mattip Could you give us more details about the issue you see with --accept flag? I'm not able to repro this.

**Comment by neginraoof** [comment]
Also for the ignored tests, we can definitely improve the script and refactor the code in https://github.com/pytorch/pytorch/blob/87aa2d25aef1f7863382e73a46f037114eb7a09a/scripts/onnx/test.sh#L48
to skip the tests using pytest-style decorators.

But apart from this, some tests are ignored/enabled based on the $BUILD_ENVIRONMENT for CI,
to split the tests between the jobs and speed up the CI.

**Comment by mattip** [comment]
> I'm trying: `python test/onnx/test_operators.py --accept`

Cool, that was the missing piece. CI invokes `scripts/onnx/test.sh`, which calls `python -m pytest test/onnx`, so I didn't think of trying  `python test/onnx/test_operators.py --accept` directly. In the meantime, I have submitted gh-38629 and started documenting [tests](https://github.com/pytorch/pytorch/pull/38629/files#diff-e33f11af28bc4c24bf034e2fadfe4e08R52), maybe that invocation should be added to the docstring and/or added to the testing documentation.

**Comment by neginraoof** [comment]
Sure, I can update the documentation in test file.

**Comment by neginraoof** [comment]
I have a PR ready: https://github.com/pytorch/pytorch/pull/38829/files
Please let me know if we can close this issue.
