### ISSUE TITLE
test_broadcast_basics_cuda (__main__.ProcessGroupGlooTest) is flaky on ROCm

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38549]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28061//console

```
06:31:23 ======================================================================
06:31:23 ERROR: test_broadcast_basics_cuda (__main__.ProcessGroupGlooTest)
06:31:23 ----------------------------------------------------------------------
06:31:23 Traceback (most recent call last):
06:31:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
06:31:23     self._join_processes(fn)
06:31:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
06:31:23     self._check_return_codes(elapsed_time)
06:31:23   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 339, in _check_return_codes
06:31:23     raise RuntimeError(error)
06:31:23 RuntimeError: Processes 0 2 3 exited with error code 10
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jeffdaily @sunway513 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by mrshenli** [comment]
cc @jithunnair-amd do we need to disable this test for ROCm?

**Comment by jithunnair-amd** [comment]
Yes please 👍 I'll make a note of this flaky test.

**Comment by jeffdaily** [comment]
These mGPU tests were flaky due to a bug in our kernel.  The error manifests as a memory access fault, eventually leading to a test timeout.  Our CI hosts were patched prior to the week starting Monday June 1 2020.

**Comment by jeffdaily** [comment]
@jaglinux do you know if this test is still flaky?

**Comment by jaglinux** [comment]
I ran the test manually and also verified the CI logs. The test is running fine.
22:36:41   test_broadcast_basics_cuda (__main__.ProcessGroupGlooTest) ... ok (0.148s)

test_broadcast_basics_cuda (__main__.ProcessGroupGlooTest) ... ok
