### ISSUE TITLE
Can you add an overloaded operator &,|,^ to a libtorch tensor

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#38546]
Can you add an overloaded operator &,|,^ to a libtorch tensor
example:
python: 
a=torch.tensor((1))  
b=torch.tensor((1))  
c=a&b
libtorch:
auto a=torch::tensor({1});
auto b=torch::tensor({1});
auto c=a&b;////no support

cc @yf225 @glaringlee @ezyang

**Comment by ezyang** [comment]
This seems reasonable. Tag me as a reviewer if you add this.
