### ISSUE TITLE
Scatter is not checking that input and value type match

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#38554]
As per title.

Minimal repro: `torch.zeros(1, dtype=torch.float).scatter_(0, torch.tensor([0]), torch.tensor([1], dtype=torch.int))` (removing both dtype args gives the same behavior, they are just here to make the issue obvious).

This is most likely due to the fact that we don't compute common dtype [here](https://github.com/pytorch/pytorch/blob/15da26f8aafe50fb34d343d872c7461546d7a317/aten/src/ATen/native/cpu/ScatterGatherKernel.cpp#L65) and we don't have extra check for input and value specifically.

**Comment by ngimel** [comment]
cc @nikitaved

**Comment by gchanan** [comment]
I'm also adding various asserts to try to catch this kind of problem over in the https://github.com/pytorch/pytorch/pull/38817 stack.

**Comment by gchanan** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/38646.
