### ISSUE TITLE
Convolution in v1.5.0 using more memory than previous versions

### ISSUE THREAD

**Issue by chcodes** [pytorch/pytorch#38568]
## 🐛 Bug

The convolution layer appears to be using extra memory that is around the size of the output, that it didn't use in PyTorch 1.4.0 and earlier versions. Not sure if this is intended, but that extra memory is valuable for medical imaging/video applications.

If it is intended, what is the reason for it? Would it be possible to have an option to use the memory efficient convolution from the previous versions?

## To Reproduce

The following script should reproduce.

```python
import torch


def torch_memory(device):
    print(f'{torch.cuda.memory_allocated(device)/1024/1024:.2f} MB USED')
    print(f'{torch.cuda.max_memory_allocated(device)/1024/1024:.2f} MB USED MAX')
    print('')


# Options that should affect which algorithm is chosen
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device(0)

conv0 = torch.nn.Conv3d(64, 64, 3, padding=1).to(device)

x = torch.randn((1, 64, 24, 512, 512), dtype=torch.float32, device=device)
print('Memory after input array is created:')
torch_memory(device)

with torch.no_grad():
    y = conv0(x)
    print('Memory after convolution is computed:')
    torch_memory(device)
```
The output I get from PyTorch 1.5.0:
```
Memory after input array is created:
1536.42 MB USED
1536.42 MB USED MAX

Memory after convolution is computed:
3072.42 MB USED
4608.42 MB USED MAX
```
The output I get from PyTorch 1.4.0:
```
Memory after input array is created:
1536.42 MB USED
1536.42 MB USED MAX

Memory after convolution is computed:
3072.42 MB USED
3180.61 MB USED MAX
```
## Expected behavior

The input array x should occupy 1536 MB and the output y should also occupy 1536 MB, totalling 3072 MB. But it seems an intermediate array was used during the computation in pytorch 1.5.0.

## Environment

 - PyTorch Version: 1.5.0
 - OS: Tried both Linux and Windows
 - How you installed PyTorch: conda
 - Python version: 3.7.6
 - CUDA version: 10.1
 - cuDNN version: 7.6
 - GPU models and configuration: Tried on V100 and GTX 1080 TI

## Additional context

Also tried 2D convolution. Also tried making input/output arrays much smaller. Also tried toggling torch.backends.cudnn.deterministic and torch.backends.cudnn.benchmark. All cases still used that extra memory.

cc @ezyang @gchanan @zou3519 @csarofeen @ptrblck

**Comment by VitalyFedyunin** [comment]
looks like legit hi-pri, cc @jjsjann123 as it might be related to `Ex` functions call or to the fact that somewhere we keep unnecessary contig or non-contig tensor.

**Comment by jjsjann123** [comment]
This is not related to NHWC.
Traced it down to convolution bias add. We should use inplace version here if we want to avoid the extra memory usage. 
https://github.com/pytorch/pytorch/blob/eb224721d20bde5dc80289ada23d527d923dbba9/aten/src/ATen/native/Convolution.cpp#L695

**Comment by jjsjann123** [comment]
PR issued: #38674

**Comment by Baranowski** [comment]
Assigning to @jjsjann123 who has implemented a fix

**Comment by jjsjann123** [comment]
Verified the fix for repro script in master. I'm closing this issue.
