### ISSUE TITLE
torch._C._cuda_getDriverVersion() reporting CUDA version instead of NVIDIA driver version

### ISSUE THREAD

**Issue by cth7** [pytorch/pytorch#38572]
## 🐛 Bug

I installed PyTorch with CUDA 10.2 and then tried to run something but my driver version was too old and failed a check (https://github.com/pytorch/pytorch/blob/master/torch/cuda/__init__.py#L45). The error message intends to let me know which version my driver is but it instead seems to tell me the version of my CUDA.

## To Reproduce

```python
import torch
torch._C._cuda_getDriverVersion()
```

Does it tell you your CUDA version or driver version? For me it said 

> 10010

## Environment

 - PyTorch Version: 1.5.0
 - OS: Linux and windows
 - How you installed PyTorch: conda
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.1

cc @ngimel

**Comment by peterjc123** [comment]
No, it is telling you the latest CUDA version that is supported by your driver. 10010 -> 10.1

**Comment by ppwwyyxx** [comment]
The same confusion happened in https://github.com/pytorch/pytorch/issues/25590 as well, and it also confused me once. Would be nice to update the error message to be more clear

**Comment by agolynski** [comment]
"""it doesn't return the CUDA version. It returns "Returns the latest version of CUDA supported by the driver.".
If you have CUDA10 installed, but driver that only supports CUDA9, it will return 9000
"""

+1 on adding better error message if possible.

**Comment by peterjc123** [comment]
So there are two options there:
1. Report the actual driver version through `NvAPI_GetDisplayDriverVersion`, but this relies on `cuda.lib`, which means that you cannot call this function if you don't have a NV card.
2. Rename this API and rewrite the message. This should be fairly simple.

@ezyang What do you think?

**Comment by ezyang** [comment]
It's an underscored function and fair game to rename. Let's think about some public API that we can release for querying this sort of information.

**Comment by cth7** [comment]
Closing this as that driver checking function has been removed (https://github.com/pytorch/pytorch/pull/42249), making this irrelevant.
