### ISSUE TITLE
Remove the pickle deprecation warning

### ISSUE THREAD

**Issue by andyljones** [pytorch/pytorch#38597]
## 🚀 Feature
Remove the pickle deprecation warning.

## Motivation
Back in January, [a warning got added about how pickle would be deprecated for torch.Storage in favour of `torch.save`](https://github.com/pytorch/pytorch/pull/32244/files#diff-782706594ba5e75a6089c3d7d084d97cR34)

```python
warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
```

[The original intent](https://github.com/pytorch/pytorch/pull/32244#issuecomment-583560637) of deprecating pickling was that it's a subset of the functionality provided by `torch.save`. 

However - [as discussed further down the same PR](https://github.com/pytorch/pytorch/pull/32244#issuecomment-628331184), every other part of the Python ecosystem uses pickle, and this means you can reliably pickle heterogeneous datastructures of numpy arrays, pandas dataframes, torch tensors, etc etc etc without caring what exact types are inside the datastructure. Insisting on using `torch.save` for torch data breaks this nice black-box-ness and requires third-party serialization code to take note of whether there's a tensor in there somewhere.    

[The original author of the warning](https://github.com/pytorch/pytorch/pull/32244#issuecomment-629556178) feels this is a convincing reason to keep pickle support, and asked that the discussion be summarized in a new issue.

## Pitch
Remove [this one line](https://github.com/pytorch/pytorch/blob/1f09f7ea448f404fff135b5e4c1c3d63d157de79/torch/storage.py#L34).

## Additional context
I'd make a PR but I don't know if there's other prep work for the deprecation that should be rolled back along with the warning?

**Comment by stsievert** [comment]
:+1:

In "[Pickle isn't slow, it's a protocol][1]," @mrocklin has some arguments against using only specialized protocols:

> **Hard for users**
> Today we use a large and rapidly changing set of libraries. It’s hard for users to become experts in all of them. Increasingly we rely on new libraries making it easy for us by adhering to standard APIs, providing informative error messages that lead to good behavior, and so on.
> 
> **Hard for other libraries**
> Other libraries that need to interact definitely won’t read the documentation, and even if they did it’s not sensible for every library to special case every other library’s favorite method to turn their objects into bytes. Ecosystems of libraries depend strongly on the presence of protocols and a strong consensus around implementing them consistently and efficiently.

There are benefits to specialized protocols (speed and sharing pop to mind), but Pickle provides a lot of usability. For example, my use of [Dask-ML's hyperparameter optimization][3] uses the Pickle protocol to communicate objects between Python processes.

[2]:https://arxiv.org/abs/1603.06560
[3]:https://ml.dask.org/hyper-parameter-search.html#adaptive-hyperparameter-optimization

>  I'd make a PR but I don't know if there's other prep work for the deprecation that should be rolled back along with the warning?

I'd submit a PR I think if I were you; that seems like the appropriate place to discuss any prep work. I'd really like to see this in the next minor version.

[1]:http://matthewrocklin.com/blog/work/2018/07/23/protocols-pickle

**Comment by ezyang** [comment]
The PR was merged
