### ISSUE TITLE
CITATION file not formatted properly

### ISSUE THREAD

**Issue by caseydm** [pytorch/pytorch#38606]
The editors portion of the CITATION file located [here](https://github.com/pytorch/pytorch/blob/master/CITATION) is not formatted properly. Specifically this part:

`editor = {H. Wallach and H. Larochelle and A. Beygelzimer and F. d\textquotesingle Alch\'{e}-Buc and E. Fox and R. Garnett}`

My goal is to make the citation work with [citeas.org](https://citeas.org). But I had to ignore that part of the citation to make it work.

**Comment by agolynski** [comment]
@soumith

**Comment by soumith** [comment]
@caseydm would you know what the fix is?
I got it from Google Scholar.

**Comment by caseydm** [comment]
@soumith Actually please disregard. The issue is with the conversion of the name F. d' Alché-Buc to F. d\textquotesingle Alch\'{e}-Buc. After additional research it seems that is the proper way to convert special characters within bibtex. I just need to find a way to convert them back properly within citeas.org.
