### ISSUE TITLE
C++ pytorch traced_bert crash in forward

### ISSUE THREAD

**Issue by prenaudon** [pytorch/pytorch#38601]
## To Reproduce

1.  Load traced_bert.pt model
2. Create id tensor and attention tensor
3. Call model.forward

The error : Microsoft C++ exception: c10::Error at memory location 0x000000000019D190.

The code is the following

torch::jit::script::Module model;
model = torch::jit::load("traced_bert.pt");
model.eval();

std::vector<std::int32_t> ids({
  101,  2256,  2814,  2180,  1005,  1056,  4965,  2023,  4106,  1010,
  2292,  2894,  1996,  2279,  2028,  2057, 16599,  1012,   102,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0});

std::vector<std::int32_t> attention({ 
1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1,  0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0});

auto opts = torch::TensorOptions().dtype(torch::kInt32);
torch::Tensor id_tensor         = torch::from_blob(ids.data(), { 1, 64 }, opts);
torch::Tensor attention_tensor  = torch::from_blob(attention.data(), { 1, 64 }, opts);

auto forward_pass_result = model.forward({ id_tensor, attention_tensor });

## Expected behavior

Should get a Tensor

## Environment
 - PyTorch Version 1.5
 - visual studio 2017, vc140, x64 release
 - OS windows 7
 - CPU only

**Comment by peterjc123** [comment]
Please check the following things:
1. Please ensure you copied all the DLLs in LibTorch to the location of your target executable.
2. Please be sure your model is on CPU (when you save it in Python).
3. Please make sure the data type of your input is consistent in Python and C++. `kInt32 = torch.int; kInt64 = torch.long`.

If you checked those things and the problem is still there, then maybe you could use the debug version to get some additional info, like stacktrace.

**Comment by peterjc123** [comment]
Also cc @glaringlee for C++ API usage.

**Comment by prenaudon** [comment]
@peterjc123 

Thank you for the timely answer.

Changing from kInt32 to kInt64  and from std::int32_t  to std::int64_t in the above code solved the issue. 

I am very experienced in C++ but a newbie in Python. And it shows.

**Comment by prenaudon** [comment]
I ma closing this issue
