### ISSUE TITLE
Torch: : Max conflicts with minwindef. H Max macro

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#38617]
libtorch 1.5 release; win10 x64; visual studio 16.6.0;
torch::Tensor a=torch::tensor({0});
torch::Tensor b=torch::tensor({1});
torch::Tensor c=torch::max(a,b);

Torch: : Max conflicts with minwindef. H Max macro
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\minwindef.h 
line 193 :#define max(a,b)            (((a) > (b)) ? (a) : (b))
Torch: : min is the same.

------------------------------
#undef max 
This definition solves the problem

**Comment by peterjc123** [comment]
Well, we already set `NOMINMAX` in our CMake configuration. I really don't understand why don't you use CMake.

**Comment by laizewei** [comment]
I download libbtorch from https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.5.0.zip
I manually configure the environment.

**Comment by peterjc123** [comment]
Yeah, I know. Actually, we are looking into how to improve the user experience for creating a LibTorch-based project. And the following are the main points:
1. Use CMake. This is well maintained, but according to our observations, users rarely pick this route.
2. Better docs. BTW, may I ask which doc/page are you referring to when you create a project based on LibTorch? Actually, our tutorial page are already based on CMake so I am curious about this.
3. Use property sheet (*.props) as described in https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=vs-2019. Do you think it is convenient for you?

cc @ezyang

**Comment by laizewei** [comment]
I learn libtorch from https://github.com/pytorch/pytorch/tree/master/test/cpp/api
I use libtorch in Windows 10 x64. I don't use in Linux. I don't use cmake.

**Comment by peterjc123** [comment]
@laizewei Okay, understood. Actually `cmake` is portable, and `make` is Unix only. So do you think it is a good idea to put Windows specific docs there, including CMake-based and VS-GUI-based ones?

**Comment by laizewei** [comment]
I think the c ++ documentation on the official website is not easy to view now. It is better to look at the examples.You can put a sample file of windows header file conflicts on the official website.

**Comment by peterjc123** [comment]
@laizewei Our c++ examples lies in https://github.com/pytorch/examples/tree/master/cpp. Do you think it is sufficient to provide a link to the docs at the download site and put the Windows docs in the examples repo?

**Comment by laizewei** [comment]
Yes, that's good.
