### ISSUE TITLE
CUDA 9.0 PyTorch on Mac gives "Found no NVIDIA driver" error

### ISSUE THREAD

**Issue by ctongfei** [pytorch/pytorch#3864]
Installation:
PyTorch 0.4.0a0, macOS 10.13 High Sierra, Mac Command Line Tools 8.2.3, Apple LLVM 6.0
CUDA 9.0.197

Installation **with CUDA enabled from source** succeeded.

When starting PyTorch, however, I get
```
>>> torch.cuda.is_available()
False
>>> torch.cuda.FloatTensor(1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tongfei/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 377, in _lazy_new
    _lazy_init()
  File "/Users/tongfei/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 139, in _lazy_init
    _check_driver()
  File "/Users/tongfei/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 81, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
>>> torch._C._cuda_isDriverSufficient()
False
>>> torch._C._cuda_getDriverVersion()
0
```

**Comment by ezyang** [comment]
Forgive me for asking, but do you actually have an NVIDIA GPU on your system?

**Comment by yukatherin** [comment]
@ezyang OP has CUDA 9.0.197 which implies an NVIDIA GPU. I'm experiencing the same.

**Comment by ngimel** [comment]
Having a toolkit (Cuda 9.0.197) does not imply having a gpu with installed driver in the system.

**Comment by ctongfei** [comment]
@ezyang Yes, I do. TensorFlow GPU runs perfectly on this Mac.

**Comment by apaszke** [comment]
@ctongfei are you sure you have a CUDA9 compatible driver? Maybe you have only updated the toolkit, but not the driver?

**Comment by soumith** [comment]
@ctongfei cuda 9.0 needs a newer driver than cuda 8.0. this is most definitely the issue. Either use pytorch with cuda 8.0, or upgrade your driver so that you can use pytorch with cuda 9.0.

**Comment by ctongfei** [comment]
Thanks @apaszke @soumith . It is because my GPU driver is not updated.

If anyone runs into the same problem, download the newest GPU driver from http://www.nvidia.com/download/driverResults.aspx/126538/en-us.
