### ISSUE TITLE
torch while loading weighs found runtime error on storage has wrong size: expected 4254413747647032608 got 1024

### ISSUE THREAD

**Issue by jeykarlokes** [pytorch/pytorch#38644]
filepath = 'mask1_model_resnet101.pth'
model = torch.load(filepath,map_location=torch.device("cpu"))

RuntimeError Traceback (most recent call last)
in
38
39 filepath = 'mask1_model_resnet101.pth'
---> 40 model = torch.load(filepath,map_location=torch.device("cpu"))
41
42

/Env/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
591 return torch.jit.load(f)
592 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 593 return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
594
595

/Env/lib/python3.6/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
778 for key in deserialized_storage_keys:
779 assert key in deserialized_objects
--> 780 deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
781 if offset is not None:
782 offset = f.tell()

RuntimeError: storage has wrong size: expected 4254413747647032608 got 1024

**Comment by agolynski** [comment]
closing this, let's follow up in https://github.com/pytorch/pytorch/issues/38643
