### ISSUE TITLE
Difference in `round` between vec256_base and vec256_float

### ISSUE THREAD

**Issue by kimishpatel** [pytorch/pytorch#38659]
I see that `round` at vec256_base:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_base.h#L389
and at vec256_float:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vec256_float.h#L193

are different. The former does round-to-nearest-integer-ties-to-even while the latter does round-to-nearest-integer.

Is there a reason for this discrepancy. I suppose the latter can be implemented by cvt instruction to convert float to in and then convert int back to float.

**Comment by kimishpatel** [comment]
cc: @ezyang, @colesbury

**Comment by colesbury** [comment]
Is there actually a difference in behavior?

**Comment by kimishpatel** [comment]
Maybe not. But my guess is that without ties-to-even, ties are rounded towards zero. With ties to even 1.5 and 2.5 will be rounded to 2. But my guess is that for the just to-nearest 1.5 will be rounded to 1 and 2.5 to 2? I can check and confirm.

**Comment by colesbury** [comment]
I think it's the same (round to nearest; half to even): https://gcc.godbolt.org/z/xE8cER

It would be good to have some tests that `torch.round` always behaves as expected. I didn't see anything in test_torch.py

**Comment by kimishpatel** [comment]
Close as not a bug? Or you want to keep it open to add test?

**Comment by colesbury** [comment]
Turns out we have a test (`test_device_rounding` in test_torch.py)
