### ISSUE TITLE
Add index number to THArgCheck error message

### ISSUE THREAD

**Issue by orena1** [pytorch/pytorch#38652]
## 🚀 Feature + Motivation
It would be very efficient if this error: https://github.com/pytorch/pytorch/blob/176174a68ba2d36b9a5aaef0943421682ecc66d4/aten/src/THC/generic/THCTensorMath.cu#L64

Could also return the index numbers that made this exception, one might have a single offending index in a very large dataset, and when he gets this error, he needs to iterate over the full dataset to search for the index

## Pitch
Instead of returning this error:
```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1278 and 1277 in dimension 1 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensor.cpp:612
```
it should return this error:
```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1278 and 1277 in dimension 1 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/TH/generic/THTensor.cpp:612
The offending indices are [1,10,100,1000, ]
```
 if there are more than x indices in the batch it can save it to file...

Thanks.

cc @ngimel

**Comment by agolynski** [comment]
@orena1 : if this is a small enough change, feel free to send a PR

**Comment by orena1** [comment]
Sorry @agolynski , I'm not strong enough in C

**Comment by Kiyosora** [comment]
I proposed a pull request #38978 trying to fix this issue, please make a review if it's convenient for you. 
cc: @agolynski
