### ISSUE TITLE
where did torch/csrc/autograd/generated/VariableType.h go?

### ISSUE THREAD

**Issue by Ayanamiyui** [pytorch/pytorch#38660]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
i cant find it now can anyone help?

**Comment by agolynski** [comment]
does this answer your question? 
https://discuss.pytorch.org/t/where-does-the-torch-csrc-autograd-generated-variabletype-h-file-move-to/40136
