### ISSUE TITLE
ONNX export fails on nn.Upsample 

### ISSUE THREAD

**Issue by iNLyze** [pytorch/pytorch#38685]
## 🐛 Bug

I am trying to export a model containing nn.Upsample. At best it will export, but `onnxruntime` will throw InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : No Op registered for Shape with domain_version of 12

## To Reproduce

1. You need a model with nn.Upsample in it, such as 
```python
class FixedUpsample(nn.Module):
    def __init__(self, scale_factor=2, mode='nearest', align_corners=False):
        super(FixedUpsample, self).__init__()
        self.mode=mode
        self.align=align_corners
        self.scale=scale_factor
    def forward(self,x):
        _,_,h,w = x.shape
        return nn.Upsample(size=(h*self.scale,w*self.scale),mode=self.mode,)(x)
```
2. You export using 
```python
torch.onnx.export(FixedUpsample(mode='bilinear'),
                  img,
                  'test_fixedUpsample.onnx', 
                  verbose=False, 
                  export_params=True, 
                  keep_initializers_as_inputs=True,
                  do_constant_folding=True,
                  opset_version=12, 
                  operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK)
onnx.checker.check_model(onnx.load('test_fixedUpsample.onnx'))
```
3. You run using 
```python
import onnxruntime as ort
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
ort_sess = ort.InferenceSession(str(onnx_path))
ort_inputs = {ort_sess.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_sess.run(None, ort_inputs)

# compare ONNX Runtime and PyTorch results
np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)
```

## Expected behavior

ort_sess would run the model without errors and its output would be similar to `torch_out` within the tolerances given.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Arch Linux 5.6.6-arch1-1 #1 SMP PREEMPT Tue, 21 Apr 2020 10:35:16 +0000 x86_64 GNU/Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.4
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Quadro RTX 6000
 - Any other relevant information: ONNX v 1.7.0, op_set version 12

## Additional context
I tried all op_set versions from [7,8,9,10,11,12] - each gives a different permutation of problems, but none works. 
I looked at the following issues trying to resolve, but unsuccessful so far:
https://github.com/pytorch/pytorch/issues/22959
https://github.com/pytorch/pytorch/issues/18113
https://github.com/openvinotoolkit/openvino/issues/483
https://github.com/pytorch/pytorch/issues/27376
It would be great, if you could take a look at this. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@iNLyze - If the model exports fine, and you do not see any obvious issue in the exported ONNX model, then it may be better to open an issue with ORT.
Also, opset 12 is still under works in the exporter and not officially released. Can you try using opset 11?

**Comment by iNLyze** [comment]
@spandantiwari, thanks for the advice. I tried again with opset 11. 
During export I get 
```python
TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if len(inputs) == 2:
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  image_shape = np.array(image_shape)
TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchors = torch.from_numpy(all_anchors.astype(np.float32))
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores_over_thresh.sum() == 0:
UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 11. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  "" + str(_export_onnx_opset_version) + ". "
``` 
`onnx.checker.check_model()` throws: 
```python
ValidationError: Op registered for Upsample is deprecated in domain_version of 11

==> Context: Bad node spec: input: "1066" input: "1105" output: "1106" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }
```

resulting in an invalid graph as noted by `onnxruntime`: 
```python
InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : Op registered for Upsample is deprecated in domain_version of 11
```
Do you think it is related to ORT only? I am happy to post there, though I am under the impression something goes wrong before we get there. From the linked issues above I interpred this as if `nn.Upsample` export was changed from being restricted to `mode=nearest`  to `mode=bilinear`. However, switching mode alone does not solve the issue. Another part of the issue appears to be that `nn.Upsample` does not export correctly, when I use the `scale` parameter instead of `size`. The exporter seems to expect a constant, rather than the scale variable. I just don't know how to work around this as the exact size of the input tensor is only known at runtime.
Should I still open an issue in ORT (being reluctant to double-post)?

**Comment by spandantiwari** [comment]
We will look into it.

**Comment by KsenijaS** [comment]
Hi @iNLyze

I couldn't reproduce your issue, I tried with pytorch 1.5 and also pytorch built from master.
Can you please share the input img, and ort version that you used.
For img I used img=torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
and for onnxruntime I used ort-nightly 1.3, available here: https://test.pypi.org/project/ort-nightly/

**Comment by iNLyze** [comment]
@KsenijaS, thanks for taking a look and for the hint: I can confirm that with the nightly build v1.3.0 and usind `mode=bilinear` the error is gone. I had used `onnxruntime.__version__==1.2.0` before, which is what vanilla `pip install onnxruntime` gave me. So, it seems this part I am using is under active development. I'll close the issue for now and report back, if problems persist. I haven't checked if the output actually makes sense, but I get one now - thanks a lot!

**Comment by KsenijaS** [comment]
When operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK flag is left out of torch.onnx.export function there is no exception when mode is set to nearest, but it seems that there is a bug when operator_export_type is set to OperatorExportTypes.ONNX_ATEN_FALLBACK.

cc: @houseroad

**Comment by iNLyze** [comment]
@KsenijaS, thanks for reporting.
