### ISSUE TITLE
variable advanced indexing with assignment

### ISSUE THREAD

**Issue by xinyuwufei** [pytorch/pytorch#3868]
pytorch version: 0.4.0a0+6dc1fc7 wich cudnn support
 OS: Mac OS 10.12

I'm new to the pytorch, I found a issue when variable.data is failed to assign when the case likes:
* out[0,:].data = torch.mul(out[0,:].data,zero_one_mat), see details below:

```python
import torch
from torch.autograd import Variable
import numpy as np
```

```python
out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
print(out)
out = Variable(torch.from_numpy(out).cuda())
print(out)
```

    [[  5.57370008e-08   1.22179998e-07]]
    Variable containing:
    1.00000e-07 *
      0.5574  1.2218
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

```python
zero_one_mat = np.zeros((1,2),dtype=np.float32)
zero_one_mat[0,0] = 1.
zero_one_mat = torch.from_numpy(zero_one_mat).cuda()
print(zero_one_mat)
```

     1  0
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

```python
print('wrong result:')

out[0,:].data = torch.mul(out[0,:].data,zero_one_mat)
print(out.data)

print('**************')
print('correct result:')
print(torch.mul(out[0,:].data,zero_one_mat))

print(torch.mul(out.data[0,:],zero_one_mat))

out.data[0,:] = torch.mul(out[0,:].data,zero_one_mat)
print(out.data)

out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
out.data[0,:] = torch.mul(out.data[0,:],zero_one_mat)
print(out.data)

out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
torch.mul(out[0,:].data,zero_one_mat,out=out[0,:].data)
print(out.data)

out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
torch.mul(out.data[0,:],zero_one_mat,out=out[0,:].data)
print(out.data)

out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
torch.mul(out.data[0,:],zero_one_mat,out=out.data[0,:])
print(out.data)

out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
torch.mul(out[0,:].data,zero_one_mat,out=out.data[0,:])
print(out.data)
```

    wrong result:

    1.00000e-07 *
      0.5574  1.2218
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]
    
    **************
    correct result:
    
    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

    1.00000e-08 *
      5.5737  0.0000
    [torch.cuda.FloatTensor of size 1x2 (GPU 0)]

**Comment by apaszke** [comment]
That's expected. When you do `var[idx]` you get a new Variable, and changing its `.data` won't modify the `.data` of `var` in any way. If you want to differentiate this operation remove `.data` altogether. If you don't. Do `var[idx].data.copy_(some_expression.data)`.

**Comment by xinyuwufei** [comment]
hi apaszke,
thanks for the explanation.
I want to do an in-place operation for some indexes of var.data, now I think the more natural way is to use var.data[idx].
just for my curiosity,  what happens for the use case of this:

```python
out=np.array([[5.5737e-08,1.2218e-07]],dtype=np.float32)
out = Variable(torch.from_numpy(out).cuda())
torch.mul(out[0,:].data,zero_one_mat,out=out[0,:].data)
print(out.data)
```

it still gives me the right result.

Thanks!

**Comment by apaszke** [comment]
That will give you the correct result, but why even bother with using Variable if you don't want to differentiate it anyway?

**Comment by xinyuwufei** [comment]
Really thanks for the clarification!
Actually, I do want to differentiate the operation, I tried to use the var directly but run into the in-place error, I thought use var.data would do the trick, now I realize is wrong.

I saw the solution on the forum is to use the clone() method, below is my current implementation:
```python
        for key, values in location.items():
            for v in values:
                zero_one_mat = np.zeros(self.vocab_dim,dtype=np.float32)
                zero_one_mat[statistics_hardcoded.yunjiao_stat[v[1]]] = 1.
                zero_one_mat = Variable(torch.from_numpy(zero_one_mat).cuda())

                x = outs[key].clone() # outs is a list containing vars
                x[v[0]]= x[v[0]] * zero_one_mat
                norm = torch.sum(x[v[0]])
                x[v[0]] = x[v[0]] / norm
                outs[key] = x.clone()   
        return outs
```

 but now I'm facing the out of memory run-time error.

any idea to solve this issue?

Thanks

**Comment by apaszke** [comment]
That's a hard one. I think you can try running the thing without `clone` on master. We relaxed some of the constraints so it might help
