### ISSUE TITLE
[JIT] Add test infra for checking that source ranges in error messages are in the right place

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#38698]
## 🚀 Feature
JIT has test infrastructure to allow engineers to check that the string representation of an exception matches a given regular expression. This is often used to make sure that the expected error message is thrown when compiling/executing a piece of code. Depending on the cause, these error messages can include snippets of the source code with the problematic parts highlighted. However, there is currently no way to check that the right part of the source code part is highlighted. I propose that we add some small test infra code to allow test writers to assert that the range of the source highlighted in an error message is somewhat in the right place.

## Motivation
It is important that the source ranges highlighted by error messages are in the right place. That is, it is important that they refer to the parts of the source code that have resulted in the error. If this is not the case, users may find it frustrating or even difficult to write and run TorchScript. While in itself a minor annoyance, I think that this can be one of the proverbial "one thousand cuts" that amount to a poor user experience. 

Here is an example of a case in which the wrong portion of the source is highlighted:

```
Expected type hint for result of tolist():
def to_list_missing_type_annotation(x):
    # type: (torch.Tensor) -> List[float]
    li = x.tolist()
         ~~~~~~~~~ <--- HERE
    return li
```

While the solution may be easy to figure out based on the error message itself, I think that in this case, `li` should be highlighted, not `x.tolist()`, because that is where the annotation should appear:

```
Expected type hint for result of tolist():
def to_list_missing_type_annotation(x):
    # type: (torch.Tensor) -> List[float]
    li = x.tolist()
    ~~~ <--- HERE
    return li
```
If this feature existed, we could check this as part of the test itself.

## Pitch
I propose that we augment our `FileCheck` tool with a new type of check, say `CHECK_SOURCE_RANGE` (name suggestions welcome), that would be used like so:
```
FileCheck().check_source_range(source_token).run(error_message)
```
This check will search `error_message` for `source_token`, and make sure that the next line has a highlight string (i.e. `~~~~~~~~~ <--- HERE`) that highlights `source_token`, and not some other part of the previous line.

## Alternatives
The only realistic alternative is to do this same thing in `jit_utils.py` using Python string functions, but what this proposal contains is a slightly modified version of `CHECK-NEXT`, so I think FileCheck is the right tool for this job.

cc @suo

**Comment by eellison** [comment]
This is kind of yak-shaving, but `tolist()` can also be emitted as an expression, so it's not always being assigned to a variable. e.g. `print(torch.jit.annotate(List[int], x.totensor()))`. I'm not sure how you would emit the error for `tolist()` at `li` in a general way that makes sense.
