### ISSUE TITLE
Functions with multiline signature not displayed properly in docs

### ISSUE THREAD

**Issue by ShawnZhong** [pytorch/pytorch#38694]
## 📚 Documentation

Functions with multiline signature are not properly displayed in the online docs

Take `randint` as an example, the function signature takes two lines in the docstring. 

https://github.com/pytorch/pytorch/blob/15da26f8aafe50fb34d343d872c7461546d7a317/torch/_torch_docs.py#L4667-L4670

But on the docs website https://pytorch.org/docs/master/generated/torch.randint.html, the second line is not recognized as part of the function signature. 

![image](https://user-images.githubusercontent.com/6421097/82273101-21ab7f00-9942-11ea-8e9b-717d3fa52684.png)

A similar issue happens to the index page as well: the second column shows the first line of the signature, instead of the description. 

![image](https://user-images.githubusercontent.com/6421097/82273128-3d168a00-9942-11ea-9f95-64cb698f4cb4.png)

cc @ezyang @zou3519

**Comment by ezyang** [comment]
At least part of this is because the 'r' specifier was used on the docblock, which means the backslash is interpeted literally, and I guess Sphinx doesn't know how to deal.
