### ISSUE TITLE
how can i fix 'ONNX export failed: Couldn't export operator aten::floor'

### ISSUE THREAD

**Issue by Ayanamiyui** [pytorch/pytorch#38701]
## ❓ Questions and Help
when i export a onnx model from torch
i got 'ONNX export failed: Couldn't export operator aten::floor'
it seems that i need to edit torch/onnx/symbolic.py
but how? can anybody give some help :(
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by take-cheeze** [comment]
Seems you need to add following to torch/onnx/symbolic_opset9.py
```python
def floor(g, self):
    return g.op("Floor", self)
```
Or register it to `torch.onnx.symbolic_registry`.

**Comment by agolynski** [comment]
@take-cheeze: Thanks for help!

@Ayanamiyui: It'd be appropriate for the discussion forum, could you post questions there in the future?
