### ISSUE TITLE
[JIT] Bad alias annotations

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#38731]
## 🐛 Bug

There are at least a few schemas in `native_functions.yaml` which have incorrect alias annotations, such as `func: view_as(Tensor self, Tensor other) -> Tensor`. 

We currently have a couple different bits of test machinery that could have caught this bug.

- a [test registry](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L117) of tensor methods with representative inputs. These get compiled and run in `add_autograd_test` in test_jit.py - (the autograd tests may or may not be helpful).
- a utility for [checking alias annotations](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/utils/check_alias_annotation.cpp)

The task here would be to set up testing so that the bad alias annotation in `view_as` would fail our tests (and to fix any bad schemas discovered along the way).

cc @suo

**Comment by rahuln32** [comment]
PR enabling the tests that catch these to run on all operators has been pushed. Fixed some broken test logic along the way along with one operator's alias annotation (conj).
