### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ztc1990** [pytorch/pytorch#38743]
## ❓ Questions and Help
Hello, I just stuck in the code which I can't solve (For the GAN code). The problem as follows:

import torch
from torch import optim
from torch.autograd import Variable
import torchvision

# hyperparameters 
batch_size = 64
z_dim = 100
lr = 1e-4
n_epoch = 10
save_dir = os.path.join(workspace_dir, 'logs')
os.makedirs(save_dir, exist_ok=True)

# model
G = Generator(in_dim=z_dim).cuda()
D = Discriminator(3).cuda()
G.train()
D.train()

When I run to the G = Generator(in_dim=z_dim).cuda(). There is an error as follows,

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-13-4fb2d9499abd> in <module>
     13 
     14 # model
---> 15 G = Generator(in_dim=z_dim).cuda()
     16 D = Discriminator(3).cuda()
     17 G.train()

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in cuda(self, device)
    305             Module: self
    306         """
--> 307         return self._apply(lambda t: t.cuda(device))
    308 
    309     def cpu(self):

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    201     def _apply(self, fn):
    202         for module in self.children():
--> 203             module._apply(fn)
    204 
    205         def compute_should_use_set_data(tensor, tensor_applied):

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    201     def _apply(self, fn):
    202         for module in self.children():
--> 203             module._apply(fn)
    204 
    205         def compute_should_use_set_data(tensor, tensor_applied):

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    223                 # `with torch.no_grad():`
    224                 with torch.no_grad():
--> 225                     param_applied = fn(param)
    226                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    227                 if should_use_set_data:

~\Anaconda3\lib\site-packages\torch\nn\modules\module.py in <lambda>(t)
    305             Module: self
    306         """
--> 307         return self._apply(lambda t: t.cuda(device))
    308 
    309     def cpu(self):

~\Anaconda3\lib\site-packages\torch\cuda\__init__.py in _lazy_init()
    147             raise RuntimeError(
    148                 "Cannot re-initialize CUDA in forked subprocess. " + msg)
--> 149         _check_driver()
    150         if _cudart is None:
    151             raise AssertionError(

~\Anaconda3\lib\site-packages\torch\cuda\__init__.py in _check_driver()
     45 def _check_driver():
     46     if not hasattr(torch._C, '_cuda_isDriverSufficient'):
---> 47         raise AssertionError("Torch not compiled with CUDA enabled")
     48     if not torch._C._cuda_isDriverSufficient():
     49         if torch._C._cuda_getDriverVersion() == 0:

AssertionError: Torch not compiled with CUDA enabled. 

My laptop does not have GPU. I was wondering how can I revise line 13 in order to run it. 
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
Just remove the `.cuda()` calls.
e.g.
```py
G = Generator(in_dim=z_dim)
D = Discriminator(3)
```
