### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator ScaledL2

### ISSUE THREAD

**Issue by DancingJane** [pytorch/pytorch#38760]
I met this error when transforming a trained network in pytorch to onnx.

I transform this model using the following function:
torch.onnx.export(model,x,'fastfcn0520.onnx',verbose=True,opset_version=11)

Error output in detail is as follows:
Traceback (most recent call last):
  File "onnx_transformer.py", line 53, in <module>
    output = transformer()
  File "onnx_transformer.py", line 24, in transformer
    torch.onnx.export(model,x,'fastfcn0520.onnx',verbose=True,opset_version=11)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 503, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: ONNX export failed: Couldn't export Python operator ScaledL2

Defined at:
/Files/segmentation/FastFCN-latest/encoding/functions/encoding.py(96): scaled_l2
/Files/segmentation/FastFCN-latest/encoding/nn/encoding.py(102): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py(100): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/Files/segmentation/FastFCN-latest/encoding/models/encnet.py(63): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/Files/segmentation/FastFCN-latest/encoding/models/encnet.py(112): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/Files/segmentation/FastFCN-latest/encoding/models/encnet.py(35): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py(348): wrapper
/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py(361): forward
/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py(550): __call__
/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py(278): _get_trace_graph
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py(291): _trace_and_get_graph_from_model
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py(334): _model_to_graph
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py(488): _export
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py(69): export
/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py(168): export
onnx_transformer.py(24): transformer
onnx_transformer.py(53): <module>

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@DancingJane - can you please share your model code (smaller the better) and export code.

**Comment by mruberry** [comment]
Closing due to lack of response. @DancingJane, please reopen if you're still hitting this issue and you can provide a snippet to reproduce it.

**Comment by hyperfraise** [comment]
I have the same issue when trying to export models from https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html

Here is the code I'm using : 


```
import torch
import encoding

# Get the model
model = encoding.models.get_model('Encnet_ResNet50s_PContext', pretrained=True).cuda()
model.eval()
dummy_input = (
	torch.zeros(
	    32,
	    3,
	    375,
	    500,
	    requires_grad=False,
	)
	.float()
	.cuda()
)
with torch.no_grad():
	torch.onnx.export(
	    model,  # model being run
	    dummy_input,  # model input (or a tuple for multiple inputs)
	    "/veesion/PyTorch-Encoding/segmenter.onnx",
	    input_names=["input"],  # the model's input names
	    output_names=["output"],  # the model's output names
	    export_params=True,
	    verbose=True,
	)
```

**Comment by shubhambhokare1** [comment]
This is a limitation of the exporter. However there are no plans to add ScaledL2 support in the immediate future. It is being tracked internally by the team.

**Comment by pribadihcr** [comment]
+1
