### ISSUE TITLE
Potential bug when using fancy indexing with CUDA

### ISSUE THREAD

**Issue by benmoseley** [pytorch/pytorch#38771]
## 🐛 Bug

Using fancy indexing whilst a tensor is on CUDA does not appear to throw an exception when one of the indices is out of range, which could potentially lead to difficult to find errors. On a CPU the correct behaviour is observed (i.e. an exception is thrown).

## To Reproduce

```
import torch

torch.manual_seed(123)

for device in [torch.device("cuda:0"), torch.device("cpu")]:

    a = torch.rand(10, 20, 21).to(device)
    ix = torch.arange(10).to(torch.int64).to(device)
    iy = torch.arange(10).to(torch.int64).to(device)
    ib = torch.arange(10).to(torch.int64).to(device)

    ix[0] = 900
    print("Testing device: %s"%(device))
    print(a[ib, ix, iy])
```

Output:

```
Testing device: cuda:0
tensor([0.0000, 0.1928, 0.2886, 0.8904, 0.7965, 0.3803, 0.5128, 0.1565, 0.1407,
        0.5789], device='cuda:0')
Testing device: cpu
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(a[ib, ix, iy])
IndexError: index 900 is out of bounds for dimension 1 with size 20
```

## Expected behavior

An IndexError should be thrown when using CUDA, similar to the CPU case.

## Environment

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN V
GPU 1: TITAN V
GPU 2: TITAN V
GPU 3: TITAN V

Nvidia driver version: 440.44
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.0.1.post2
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ailzhang** [comment]
I can repro this on master branch, marking as high priority to fix.
