### ISSUE TITLE
`torch.channels_last` does not show "hint" in IDE.

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#38784]
Nit: `torch.channels_last` does not show "hint" in IDE. 
![image](https://user-images.githubusercontent.com/24860335/82405652-63f3bf80-9a19-11ea-88f6-08a29b77799f.png)

_Originally posted by @xwang233 in https://github.com/pytorch/pytorch/issues/37837#issuecomment-631232305_

cc @VitalyFedyunin @jamesr66a

**Comment by Kiyosora** [comment]
Hi @VitalyFedyunin , I proposed a pull request #39120 , trying to fix this issue.
Please make a review if it's convenient to you :)

**Comment by VitalyFedyunin** [comment]
Closed with #39120
