### ISSUE TITLE
DISABLED test_memory_profiler (__main__.TestAutograd)

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#38799]
Consistently failing for py3.6-clang7-rocmdeb-ubuntu16.04-test2, examples:

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28568//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28632//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28631//console

cc @ezyang @gchanan @zou3519

**Comment by ilia-cher** [comment]
https://github.com/pytorch/pytorch/pull/38795 is the fix
