### ISSUE TITLE
Setting the weight argument in nn.Loss functions, suggestions for a better error message

### ISSUE THREAD

**Issue by imwillhang** [pytorch/pytorch#3879]
I spent 20 minutes banging my head against this until I figured it out. When the _weight_ Tensor argument in nn.Loss is NOT .cuda() when the Variables going into the function are .cuda(), PyTorch will raise an uninformative error message. 

Perhaps the error message could check if the arguments going into the Loss definition are .cuda() and inform the user to set all arguments to .cuda() or not .cuda() depending on the inputs into the instance of the loss function?

**Comment by apaszke** [comment]
Can you post the error message you got?

**Comment by jdhao** [comment]
I have also met this issue when I use `nn.CrossEntropyLoss`. You should also put the weight vector in GPU and wrap it with Variable. But I think the error message is good to know what is wrong.

**Comment by zou3519** [comment]
@jdhao Is this what you mean?
```
import torch
from torch.autograd import Variable
import torch.nn as nn

x = Variable(torch.randn(2, 2).cuda(), requires_grad=True)
t = Variable(torch.LongTensor([0, 1]).cuda(), requires_grad=False)
weight = torch.randn(2)
m = nn.CrossEntropyLoss(weight=weight)
m(x, t)

TypeError: CudaClassNLLCriterion_updateOutput received an invalid combination of arguments - got
(int, torch.cuda.FloatTensor, torch.cuda.LongTensor, torch.cuda.FloatTensor, bool, torch.FloatTen
sor, torch.cuda.FloatTensor, int), but expected (int state, torch.cuda.FloatTensor input, torch.c
uda.LongTensor target, torch.cuda.FloatTensor output, bool sizeAverage, [torch.cuda.FloatTensor w
eights or None], torch.cuda.FloatTensor total_weight, int ignore_index)
```

**Comment by jdhao** [comment]
@zou3519 , the weight vector should also be variable and on GPU. The criterion should also be on GPU.
```
import torch
from torch.autograd import Variable
import torch.nn as nn

x = Variable(torch.randn(2, 2).cuda(), requires_grad=True)
t = Variable(torch.LongTensor([0, 1]).cuda(), requires_grad=False)
weight = torch.randn(2).cuda()
m = nn.CrossEntropyLoss(weight=weight).cuda()
m(x, t)
```

**Comment by imwillhang** [comment]
Sorry, forgot to clarify that I figured out already that the issue is that the weight vector needs to be a Variable and cuda enabled when the rest of your tensors are cuda. Basically all your tensors need to be cuda. It'd be nice to have this error message assert to help out.

**Comment by zou3519** [comment]
I'm not sure what changed, but the error message looks like this on master:
![image](https://user-images.githubusercontent.com/5652049/33454084-ba5423ba-d5e5-11e7-881a-d98baad9e1a9.png)
which is more readable than before :)

**Comment by kkorovesis** [comment]
`weight = torch.randn(2).cuda()`
Don't forget to cuda() your weights

**Comment by martinbel** [comment]
I'm got the same error as above (in the screenshot) and after changing everything to cuda got this: 

Any ideas? 

```
wg = torch.Tensor([1.,  4.,  2., 1., 1., 3.,  3.,  3., 4., 4., 1., 2., 1., 1., 3., 4., 1.]).cuda()
criterion = torch.nn.MultiLabelSoftMarginLoss(weight=wg).cuda()

mdl = train_model(dataloaders, model, criterion, optimizer, scheduler, num_epochs=25)
## -- End pasted text --
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-85e810cd12fe> in <module>()
    182 
    183 
--> 184 mdl = train_model(dataloaders, model, criterion, optimizer, scheduler, num_epochs=25)

/mnt/kaggle_data/planet-understanding-the-amazon-from-space/helpers.py in train_model(dataloaders, model, criterion, optimizer, scheduler, num_epochs)
     95 
     96                 running_loss += loss.data[0]
---> 97                 running_corrects += torch.sum(preds == labels.data)
     98 
     99             if phase == 'train':

~/anaconda3/lib/python3.6/site-packages/torch/tensor.py in __eq__(self, other)
    358 
    359     def __eq__(self, other):
--> 360         return self.eq(other)
    361 
    362     def __ne__(self, other):

TypeError: eq received an invalid combination of arguments - got (torch.cuda.FloatTensor), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (torch.cuda.FloatTensor)
 * (torch.cuda.LongTensor other)
      didn't match because some of the arguments have invalid types: (torch.cuda.FloatTensor)

```

**Comment by fmassa** [comment]
There is a conflict somewhere between Long an Float tensors. Just cast the Long tensor to float and you'll be fine
