### ISSUE TITLE
Quantization inference on CUDA

### ISSUE THREAD

**Issue by felicitywang** [pytorch/pytorch#38803]
## ❓ Does PyTorch support quantization inference on CUDA now?

Hi, my understanding is that quantization inference on CUDA isn't supported by PyTorch yet. But I saw this pull request of the QuantizedCUDA implementation by @jerryzh168 with no further documentation - is it designed for inference CUDA support? 

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by raghuramank100** [comment]
We are not planning to add support for quantized inference on CUDA yet. The QuantizedCuda PR only allows for creating quantized tensors on Cuda, there is no kernel support. We welcome PRs enabling this feature!

**Comment by andrewor14** [comment]
Closing this since it seems to be addressed in https://github.com/pytorch/pytorch/issues/87395
