### ISSUE TITLE
DISABLED test_reduce_scatter (__main__.TestNCCL)

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#38835]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28226//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28233//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28234//console

cc @ezyang @gchanan @zou3519

**Comment by jithunnair-amd** [comment]
@pritamdamania Please close this issue as you have already addressed it here: bf93954

**Comment by jithunnair-amd** [comment]
cc @ezyang

**Comment by jithunnair-amd** [comment]
cc @mrshenli
