### ISSUE TITLE
DISABLED test_reduce (__main__.TestNCCL)

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#38834]
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28226//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28233//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28234//console

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
@pritamdamania87 If I understand correctly, by disabling the test here, you've disabled it globally for ALL test configurations, not just ROCm. If it is just ROCm flakiness, it would be FAR better to skip it in the rocm code only using a skip decorator.

**Comment by jithunnair-amd** [comment]
@pritamdamania Please close this issue as you have already addressed it here: https://github.com/pytorch/pytorch/commit/bf9395438f5ccf0acfcdb2451c8745ec199c7237

**Comment by jithunnair-amd** [comment]
cc @mrshenli
