### ISSUE TITLE
Do   you  have  pure  numpy  version ?  Thanks  for  reply .

### ISSUE THREAD

**Issue by heartInsert** [pytorch/pytorch#38864]
## 🚀 Feature
If  there  is  a   numpy  version  would  be  perfect !!!

## Motivation
Hi , sorry  to  bother you .
 I'm  a  newer  to  pytorch ,  and also  new to   DL ,  so  I  want  to    understand  the  basic  of   Pytorch  ,  it's  autograd   mechanism . I  have  already   read  about  most  part  of  Pytorch's  frame , but   the  most  important  part   `autograd  mechanism` and  so  many  other  parts  are    complied  in  C++ . I  think   there  is  a  lot  of  guys  like  me  who  has  this  problem ,   that   wants to  `understand and study `  whole  `Pytorch   `through  Python for  convenient.

## Additional context
Thanks  for your reply .

**Comment by colesbury** [comment]
No, there is no NumPy or Python implementation of PyTorch's autograd.

If you want to study a clean Python implementation, you might want to look at https://github.com/karpathy/micrograd
