### ISSUE TITLE
requires_grad cannot be set to True for non-leaf nodes, but retain_grad needs requires_grad to be True

### ISSUE THREAD

**Issue by calebh** [pytorch/pytorch#3890]
I am attempting to save the gradient of a non-leaf node. I attempt to set requires_grad to be true, and receive the following error:
> RuntimeError: you can only change requires_grad flags of leaf variables.

Attempting to call retain_grad returns an error because requires_grad is False:
> RuntimeError: can't retain_grad on Variable that has requires_grad=False

This makes saving the gradient of an already existing Variable by way of retain_grad impossible. Here's example code that produces these errors:
```
import torch
import numpy as np
from torch.autograd import Variable

x = Variable(torch.zeros(3,3), requires_grad=True)
s = torch.sigmoid(x)
s.requires_grad = True
s.retain_grad()
total = torch.sum(s)
total.backward()
assert(s.grad is not None)
```

I am using Python 3.5.2 and PyTorch 0.2.0.post3

**Comment by apaszke** [comment]
A workaround for now is to do `s = Variable(s.data, requires_grad=true)`, but this should be fixed in the next release (variables that don't require grad are now effectively always leaves).

**Comment by apaszke** [comment]
Actually I'm not sure what's the problem. It looks like in your snippet `s` requires_grad, so you should be able to call `s.retain_grad()`.

**Comment by calebh** [comment]
That's the problem...
Attempting to set requires_grad to True gives an error.

**Comment by apaszke** [comment]
but why do you need to set it? it already requires grad

**Comment by calebh** [comment]
Ah okay, it is working now. My mistake.

**Comment by sudiptap** [comment]
thanks apaszke.
