### ISSUE TITLE
Typing Error in torch.utils.data.DataLoader and Dataset

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#38913]
## 🐛 Bug

In [dataloader.py#60](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/torch/utils/data/dataloader.py#L60), `DataLoader` does not inherit `typing.Generic`, but in [dataloader.pyi#15](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/torch/utils/data/dataloader.pyi#L15) type inferace of `DataLoader` inherits `typing.Generic`.

`Dataset` is also in same situation. See also [dataset.py#L8](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/torch/utils/data/dataset.py#L8), [dataset.pyi#L6](https://github.com/pytorch/pytorch/blob/d035d05080729c30636ff30fcc068de3c7e9badd/torch/utils/data/dataset.pyi#L6).

## To Reproduce

```python
>>> import torch
>>> from typing import List
>>> from torch.utils.data import Dataset, DataLoader
>>> class SomeDatasetClass(Dataset[List[torch.Tensor]]):
...     ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

```python
>>> import torch
>>> from typing import List
>>> from torch.utils.data import Dataset, DataLoader
>>> class SomeDatasetClass(Dataset):
...     ...
... 
>>> def _create_dataloader(is_train: bool) -> DataLoader[List[torch.Tensor]]:
...     ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

## Expected behavior

`DataLoader` and `Dataset` should inherit `typing.Generic`, so above code should run without any exceptions.

```python
>>> from typing import Generic, TypeVar
>>> T = TypeVar('T')
>>> class SomeGenericClass(Generic[T]):
...     ...
... 
>>> def create_some_generic_class() -> SomeGenericClass[bool]:
...     ...
...
>>>
```

Like above code snippet.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - Python version: Python 3.7.5

## Additional context

I think this issue is related to #31765

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
If you could inline the annotations into the py module, that would also fix this problem. I tried to do this for Module in https://github.com/pytorch/pytorch/pull/38211 but it didn't work due to JIT problems. I think DataLoader/DataSet should be less problematic.
