### ISSUE TITLE
computing hessian for conv2d with torch1.5 

### ISSUE THREAD

**Issue by AlNasserAli** [pytorch/pytorch#38924]
## Issue description

I am trying to use from torch.autograd.functional.hessian to compute the hessian of a simple network (conv2d followed by fc), The error I'm getting is: 

`RuntimeError                              Traceback (most recent call last)
<ipython-input-238-a035a6bfbb36> in <module>
     18 print(c.grad)
     19 print(fc.grad)
---> 20 H = hessian(loss,c,fc)

/opt/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/autograd/functional.py in hessian(func, inputs, create_graph, strict)
    539         return jac
    540 
--> 541     res = jacobian(jac_func, inputs, create_graph=create_graph, strict=strict)
    542     return _tuple_postprocess(res, (is_inputs_tuple, is_inputs_tuple))
    543 

/opt/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/autograd/functional.py in jacobian(func, inputs, create_graph, strict)
    414 
    415     is_inputs_tuple, inputs = _as_tuple(inputs, "inputs", "jacobian")
--> 416     inputs = _grad_preprocess(inputs, create_graph=create_graph, need_graph=True)
    417 
    418     outputs = func(*inputs)

/opt/anaconda3/envs/torch1.5/lib/python3.8/site-packages/torch/autograd/functional.py in _grad_preprocess(inputs, create_graph, need_graph)
     49     res = []
     50     for inp in inputs:
---> 51         if create_graph and inp.requires_grad:
     52             # Create at least a new Tensor object in a differentiable way
     53             if not inp.is_sparse:

RuntimeError: bool value of Tensor with more than one value is ambiguous
`

## Code example
`c = torch.rand([6,3,3,3] ,requires_grad = True)

a = torch.rand([10,3,25,25])
fc = torch.rand([144*3,10], requires_grad=True)

def loss(c,fc):
    y = torch.randint(high=10,size=[10])
    z = torch.nn.functional.conv2d(a,c)
    z = torch.nn.functional.max_pool2d(a,2)
    z = z.reshape(a.shape[0],-1)
    z = z @ fc
    l = torch.nn.CrossEntropyLoss()
    return l(z,y)
    
l = loss(c,fc)
l.backward()
print(c.grad)
print(fc.grad)
H = hessian(loss,c,fc)`

## System Info

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.12.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:

[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py38hfbe908c_0
[conda] mkl_fft                   1.0.15           py38h5e564d8_0
[conda] mkl_random                1.1.0            py38h6440ff4_0
[conda] numpy                     1.18.1           py38h7241aed_0
[conda] numpy-base                1.18.1           py38h6575580_1
[conda] pytorch                   1.5.0                   py3.8_0    pytorch
[conda] torchvision               0.6.0                  py38_cpu    pytorch

**Comment by SsnL** [comment]
the 3rd arg should be a boolean. `torch.autograd.functional.hessian(func, inputs, create_graph=False, strict=False)`

https://pytorch.org/docs/stable/autograd.html#torch.autograd.functional.hessian
