### ISSUE TITLE
Test asserts in cuda kernels

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#38944]
So far, we have been avoiding testing cuda kernels in the situations where they will generate device assert (e.g. indexing kernels getting invalid indices from user). This is because device assert invalidates cuda context, and no subsequent tests can be run in the same process. But what is not tested breaks, and we should not leave important behavior untested (see #38943).
One option is to have a separate test suite that would test assertion behavior by launching a process per test, and initializing cuda context in each process. It is extremely slow unfortunately (cuda context initialization takes a few seconds).  

cc @ngimel @mruberry @malfet 
cc @ngimel @mruberry

**Comment by ezyang** [comment]
Alternately, we can finish https://github.com/pytorch/pytorch/pull/26776/ and then we will no longer break the CUDA context with asserts in this way.

**Comment by malfet** [comment]
I don't think we should rely on asserts in release code. If this is a common workflow, we should raise some sort of global error flag

**Comment by ezyang** [comment]
@malfet The problem is, short of doing something like #26776, there really isn't any good way to do data-dependent error reporting on CUDA...

**Comment by ngimel** [comment]
And #26776 is not without its problems. The error it returns is ultimately irrecoverable because data is likely corrupted at this point, so the end effect is pretty much the same as in-kernel assert + a lot of code complexity. Unless we prioritize and plan for a solution like #26776 (personally I don't think we should) in-kernel asserts are with us to stay.

**Comment by malfet** [comment]
I think having a test (using current implementation is the first step)
But I think we need a separate discussion on boundary checks(which may be expensive) and on error reporting(accurate error reporting requires switching cud’s execution model from asynchronous to synchronized)

**Comment by malfet** [comment]
Actually, as @ngimel mentioned in PR, we already have one such test:
https://github.com/pytorch/pytorch/blob/0e8c65f756c5c24620c843d70f4ceca6a5faeb24/test/test_cuda.py#L1701-L1734
