### ISSUE TITLE
Skip allreducing `local_used_maps_dev_` when `find_unused_param=False`

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#38942]
@mcarilli spotted that we can avoid populating and  allreducing `local_used_maps_dev_` when `find_unused_param=False`, as all parameters will be reduced anyway. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mcarilli** [comment]
Great work, thanks for fixing this!
