### ISSUE TITLE
cudnn version found error, v7 files but got v5.1.10

### ISSUE THREAD

**Issue by oneTaken** [pytorch/pytorch#3896]
I got this two problem  #2575 , #1637 .
And when I use conda install 
`conda install pytorch torchvision cuda80 -c soumith`
the cudnn version is `6021`, got by `torch.backends.cudnn.version()`, even though I got `7.0.3`
 So, I have to install from source.
And the install log says `cuDnn version not supported`. 
`note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. `

And in the install log, I get this:
`-- Found cuDNN: v5.1.10  (include: /usr/local/cuda-8.0/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)$`

The` cudnn.h` in the ` include` folder is v7.
```
ll /usr/local/cuda-8.0/include/cudnn*  # /usr/local/cuda-8.0/include/cudnn.h -> /usr/include/cudnn.h
ll /usr/include/cudnn.h  # /usr/include/cudnn.h -> /etc/alternatives/libcudnn
ll /etc/alternatives/libcudnn # /usr/include/x86_64-linux-gnu/cudnn_v7.h
```
And the `libcudnn.so` is also v7.
```
ll /usr/lib/x86_64-linux-gnu/libcudnn.so # /etc/alternatives/libcudnn_so*
ll /etc/alternatives/libcudnn_so* # /usr/lib/x86_64-linux-gnu/libcudnn.so.7*
ll /usr/lib/x86_64-linux-gnu/libcudnn.so.7* # /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3*
```

So, where does the cudnn found file find cudnn v5.1.10?

**Comment by apaszke** [comment]
You might have another cuDNN header somewhere in the more important system paths that are searched by the compiler before those.

**Comment by oneTaken** [comment]
Thanks for your reply. @apaszke 
I checked the user path and the root path.
And I found nothing suspect. Actually, I have picked out some path before.
This is my user` path`:
```
/data1/public/research_venv/anaconda3/bin:/usr/local/mpi/bin:/usr/local/cuda-8.0/:
/usr/local/cuda-8.0/bin:/usr/local/cuda-8.0/lib64:/usr/local/hadoop/bin/:/usr/local/sbin:
/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:
/home/node/torch/install/lib:/home/node/torch/install/bin:/home/node/bin
```
Any suggestions?

**Comment by apaszke** [comment]
The `PATH` env variable has nothing to do with this. Run this `echo | gcc -E -Wp,-v -` to get the list

**Comment by oneTaken** [comment]
Thanks a lot. @apaszke .
But, I didn't solve it too...

This is the `echo | gcc -E -Wp,-v -` result:
```
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
```
The final 2 folder has `cudnn_v7.h`.
So, the problem is the folder 2?
But I found nothing related to cudnn in my opinon.

Am I missing something?

**Comment by apaszke** [comment]
Look into all these directories and see if you can find `cudnn.h` in any of them. Additionally, run `locate cudnn.h` and see it this returns any new results

**Comment by oneTaken** [comment]
The last two folder both have `cudnn.h`
```
/usr/include/x86_64-linux-gnu/cudnn_v7.h
/usr/include/cudnn.h
```

**Comment by apaszke** [comment]
but is any of these files a symlink, or are they both regular files? if they are symlinks, please copy the full chain in here

**Comment by oneTaken** [comment]
@apaszke The last file is a symlink, it's linked to the first file.
So, I copy the linked file.
Install again and failed again.

**Comment by apaszke** [comment]
Can you please paste a full build log into a github gist?

**Comment by oneTaken** [comment]
@apaszke .
Yeah, this is the install log gist [link](https://gist.github.com/oneTaken/041109209d88f6f7d5419500a28eabc0).

**Comment by ozancaglayan** [comment]
What does this say? `grep CUDNN_MAJOR /usr/include/cudnn.h`

**Comment by oneTaken** [comment]
@ozancaglayan 
```
#define CUDNN_MAJOR      5
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
```
This is the output.

**Comment by ozancaglayan** [comment]
So this is the header to blame, it is an old cudnnv5 installed into the system paths which is detected before your other installations.
