### ISSUE TITLE
what is the difference of 'torch.onnx._export()' and 'torch.onnx.export()'?

### ISSUE THREAD

**Issue by 2165998** [pytorch/pytorch#38965]
## ❓ Questions and Help
Sorry, I can not understand.
When the inputs are same, their output files(onnx file) are difference .

**Comment by Suncheng2022** [comment]
> ## ❓ Questions and Help
> Sorry, I can not understand. When the inputs are same, their output files(onnx file) are difference .

After many years, I have the same question. I'm going to try "_export()" out for failing to export ncnn from onnx.
