### ISSUE TITLE
Memory leak after OOM (maybe RRelu specific)

### ISSUE THREAD

**Issue by Roffild** [pytorch/pytorch#38966]
## 🐛 Bug

Pytorch 1.5
Python 3.7
Windows 10

NVIDIA RTX 2080 8GB (6GB)

You need to catch the exception "RuntimeError: CUDA out of memory." at torch.rrelu().

```python
import torch

model = torch.nn.Sequential(
    torch.nn.Linear(in_features=1746, out_features=500, bias=True),
    torch.nn.RReLU(lower=0.125, upper=0.3333333333333333),
    torch.nn.Linear(in_features=500, out_features=100, bias=True),
    torch.nn.RReLU(lower=0.125, upper=0.3333333333333333),
    torch.nn.Linear(in_features=100, out_features=2, bias=True)
)
dev = torch.device("cuda")
mem = 480593
intrain = torch.rand((int(mem), 1746), device=dev, dtype=torch.float32)
outtrain = torch.rand((int(mem), 2), device=dev, dtype=torch.float32)
model.to(device=dev)
# model.train()
before = torch.cuda.memory_allocated(dev)
try:
    model(intrain)
except:
    # raise
    pass
after = torch.cuda.memory_allocated(dev)
print("Memory:")
print(before, "- before")
print(after, "- after")
```
```
Memory:
3364003328 - before
6440500224 - after
```

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ezyang** [comment]
Typically, when this sort of "leak" happens, it's because someone is holding onto the backtrace, which is keeping the frame live. It doesn't look like this is happening in this example, however. (See https://github.com/pytorch/pytorch/pull/35214 and https://github.com/pytorch/pytorch/issues/18853)

cc @peterbell10

**Comment by ezyang** [comment]
I'm not marking this high priority as the memory leak only happens upon OOM. Let me know if you disagree with this assessment.

**Comment by Roffild** [comment]
From https://github.com/pytorch/pytorch/pull/35214/files
> The solution is to move you OOM recovery code outside
of the ``except`` clause.

In my example, 
```python 
after = torch.cuda.memory_allocated(dev) 
```
 is already outside of except.

**Comment by Roffild** [comment]
This bug is not related to the feature of holding memory inside a ```except```.

This memory leak is only in RReLU.

Maybe you need to assign the highest priority to this bug ...

**Comment by peterbell10** [comment]
I was able to reproduce and the leak appears to be genuine. There is no difference inside or outside of the except clause and calling `gc.collect` in python does not help.

**Comment by ngimel** [comment]
fwiw, I can't reproduce (cuda 10.1, master), neither with oom nor without it.

**Comment by peterbell10** [comment]
To reproduce, I had to tweak the `mem` value to just the right amount. I'm guessing there are multiple allocations going on and only one of these is liable to leak.
