### ISSUE TITLE
How to change the values in nn.Embedding?

### ISSUE THREAD

**Issue by Gosicfly** [pytorch/pytorch#3897]
I first pretrain word2vec using gemsim.models.word2vec, then I want copy the values to embeddings in Pytorch, but
`
embed = nn.Embedding(2,2)

index = Variable(torch.LongTensor([1]))

embed(index).data = torch.Tensor([1,1,1])
`
the code above cannot change the value in embed.

**Comment by apaszke** [comment]
`embed.weight.data[[1]] = torch.Tensor([1, 1, 1])`

We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

**Comment by Gosicfly** [comment]
Got that, thank you.
