### ISSUE TITLE
Minor doc improvements in various locations (need review)

### ISSUE THREAD

**Issue by KushajveerSingh** [pytorch/pytorch#38981]
This is a summary of the potential doc improvements that I came up with. I can work on a pull request for these changes after review of what changes need to be made.

1. Make clear that `torch.set_default_dtype` and `torch.get_default_dtype` only affect `torch.Tesor` and not `torch.tensor`.
   
    Suggestion:-
    In [torch.set_default_dtype](https://pytorch.org/docs/stable/torch.html#torch.set_default_dtype) change:
    The default floating point dtype is initially `torch.float32`. -> The default floating-point dtype used by `torch.Tensor` is initially `torch.float32`.

    In [torch.get_default_dtype](https://pytorch.org/docs/stable/torch.html#torch.get_default_dtype) change:
    Get the current default floating-point `torch.dtype` -> Get the current default floating point `torch.dtype` used by `torch.Tensor`.

2. Specify the default value of **sci_mode** in [torch.set_printoptions](https://pytorch.org/docs/stable/torch.html#torch.set_printoptions). 

    Currently, it says to look for the default value defined by _Formatter. But to get to the default value a lot of work has to be done like:
    ```python
    torch.set_printoptions??  # Get location `torch/_tensor_str.py`
    torch._tensor_str._Formatter??  # Default value defined in the __init__ method of this class
    ```

    Suggestion:-
    Specify the default value of `False` in the docs or specify the exact path of `_Formatter` as `torch._tensor_str._Formatter`.

3. The header of [torch.full_like](https://pytorch.org/docs/stable/torch.html#torch.full_like) is placed incorrectly.

4. Add example for [torch.split](https://pytorch.org/docs/stable/torch.html#torch.split).

5. Add a note/warning in [torch.squeeze](https://pytorch.org/docs/stable/torch.html#torch.squeeze). When using batch_size=1, using torch.squeeze can result in an error. So add a warning telling the users to be careful when using torch.squeeze.

6. The header of [torch.randint(low=0, high, size](https://pytorch.org/docs/stable/torch.html#torch.randint) is placed incorrectly.

7. The header of [torch.randint_like](https://pytorch.org/docs/stable/torch.html#torch.randint_like) is placed incorrectly.
   
8. Add documentation for `_use_new_zipfile_serialization=False` argument of [torch.save](https://pytorch.org/docs/stable/torch.html#torch.save) + Add example using the above argument and pickle_protocol=4/5.

9.

**Comment by ShawnZhong** [comment]
3, 6 & 7 have been fixed in https://github.com/pytorch/pytorch/pull/38768. You can take a look at the master docs at https://pytorch.org/docs/master/

**Comment by KushajveerSingh** [comment]
Thanks for the reminder. Did not realize I was on 1.5 branch. I will then work for the other changes and post here the changes that I have made before submitting a PR.

**Comment by ezyang** [comment]
Re (1) this is not accurate. Default dtype also affects factory functions like `torch.zero`. I guess `torch.tensor` is special as it infers dtype based on the Python objects that are passed in.

**Comment by KushajveerSingh** [comment]
I was wrong in my initial statement. It does change `torch.tensor` behavior also. This example shows it

```python
a = torch.tensor([1.,2.])
a.dtype
# torch.float32

torch.set_default_dtype(torch.float64)

a = torch.tensor([1.,2.])
a.dtype
# torch.float64
```

After looking at the source code, I found that it in turn changes the default type for all the cases. In `torch.tensor` there is still an exception as shown below. But it is the expected behavior of `torch.tensor`.

```python
torch.set_default_dtype(torch.float64)

a = torch.tensor([1])
a.dtype
# torch.int64
```

**Comment by KushajveerSingh** [comment]
I made a PR with changes to 2,4,5,8. #39303
