### ISSUE TITLE
GPU selection error

### ISSUE THREAD

**Issue by Gosicfly** [pytorch/pytorch#3900]
Run 'CUDA_VISIBLE_DEVICES=5 python3 train.py'
output:
Variable containing:
  2.5000 -13.2386
[torch.cuda.FloatTensor of size 1x2 (GPU 0)]   # Not on GPU 5

And my machine has 7 GPU.
Is this a bug?

**Comment by SsnL** [comment]
Not a bug.

CUDA_VISIBLE_DEVICES is a flag for CUDA that determines which GPUs are exposed from CUDA tt  the applications using CUDA, e.g. PyTorch. So if `CUDA_VISIBLE_DEVICES=5`, then in PyTorch the device with id `0` is actually GPU `5`. Similarly, if `CUDA_VISIBLE_DEVICES=5,0,2`, then in PyTorch the device with id `0` is actually GPU `5`, device with id `1` is actually GPU `0`, and device with id `2` is actually GPU `2`. There is nothing we can do as this changes how CUDA exposes device information to PyTorch.
