### ISSUE TITLE
API for torch sparse functions like "coalesce"

### ISSUE THREAD

**Issue by mdanb** [pytorch/pytorch#39006]
## 📚 Documentation

I am trying to understand what the function "coalesce" does for sparse tensors [here](https://pytorch.org/docs/stable/sparse.html#torch.sparse.FloatTensor.coalesce). However, the API is not provided. 

cc @vincentqb

**Comment by SsnL** [comment]
see note above it https://pytorch.org/docs/stable/sparse.html?highlight=coalesce

**Comment by ezyang** [comment]
We're a bit overdue to add proper docstrings to all of these functions though. Although copy pasting them from dense is probably not a great way of fixing it.

**Comment by rgommers** [comment]
The question is answered, and I opened a new issue with details of how the sparse docs should be updated (gh-44635). So I'll close this issue.
