### ISSUE TITLE
Tensor to GPU startup very slow

### ISSUE THREAD

**Issue by zhangchenxia** [pytorch/pytorch#39005]
## 🐛 Bug

when I use 'torch.from_numpy(img).cuda(device=self.gpu_num)' to transfer image to GPU, at the first or the first& second calls,  it will cost almost 1~2s to load a 1280*768 image sporadically . 

## To Reproduce

1. 
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):Pytorch 1.3
 - OS (e.g., Linux): ubuntu 16.04.6 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
 - Python version: python3.7
 - CUDA/cuDNN version: cuda 10.1.243
 - GPU models and configuration: 2080Ti
 - Any other relevant information:

**Comment by ezyang** [comment]
CUDA context initialization can, unfortunately, take this long. If you are on a machine with a lot of GPUs and only use one, setting `CUDA_VISIBLE_DEVICES=0` could help
