### ISSUE TITLE
A neat way to truncate models made using nn.ModuleList

### ISSUE THREAD

**Issue by varghesealex90** [pytorch/pytorch#3901]
Hi;

I have a fcdensenet made using nn.ModuleList. https://github.com/bfortuner/pytorch_tiramisu.
Is there a feature that would help in truncating models. The easiest was by modifying the forward function. I also tried using __delattr__ (https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L412). However even the delattr function requires the forward function to be modified. I am looking for techniques just like how nn.Sequential models could be truncated using 
trimmed_model = nn.Sequential(*list(trained_model.children())[:-1])

Could I expect something like this?

**Comment by SsnL** [comment]
Could you please point me to the file containing the ModuleList? I'm not sure if I understand your needs fully so I want to look at the code. :)

**Comment by varghesealex90** [comment]
This [https://github.com/bfortuner/pytorch_tiramisu/blob/master/tiramisu-pytorch.ipynb](tiramisu_model) is the model. Upon training the model for semantic segmentation I would like to truncate the model only up to the bottleneck layer.

**Comment by varghesealex90** [comment]
I would like to truncate the trained tiramisu network till bottleneck layer so as to add extract the encoded version of the input and add an average pooling layer to the bottleneck layer followed by a linear layer with 5 neurons.

**Comment by varghesealex90** [comment]
@SsnL  Thank you. One final query. Say that I have trained the entire tiramisu. Now if I load the model using torch.load () and use delattr and modify the forward function will I be guranteed that I get a truncated model?

**Comment by soumith** [comment]
yes
