### ISSUE TITLE
IntegrationTest.CartPole is flaky

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#39034]
## 🐛 Bug
`IntegrationTest.CartPole` from `test/cpp/api/integration.cpp` sometimes times out on `pytorch_bazel_build` CI jobs, see for example:
See failure: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/5577465/output/104/0?file=true&allocation-id=5ecd716dc9b52d5635d36866-0-build%2F5B5F7F46

cc @ezyang @gchanan @zou3519 @malfet @yf225 @glaringlee

**Comment by glaringlee** [comment]
@malfet 
https://github.com/pytorch/pytorch/blob/master/BUILD.bazel#L1992
It seems the cpp api test's size should be marked as large, medium's default timeout is 300s ish.

**Comment by malfet** [comment]
@glaringlee two suggestions:
 - If we want to run this test per PR, can we make it smaller (5 min sounds like a lot)
 - If it is not run in other configs, than perhaps we can simply exclude it from bazel tests?

**Comment by malfet** [comment]
Intermittent failures should be fixed by https://github.com/pytorch/pytorch/pull/40263

**Comment by glaringlee** [comment]
Close per @malfet 's comment above.
