### ISSUE TITLE
Exported ONNX model's output differ from torch output

### ISSUE THREAD

**Issue by WIll-Xu35** [pytorch/pytorch#39046]
## 🐛 Bug

Exported ONNX model's output differ from torch output. Original pytorch model is a road lane segmentation model from this repo: [https://github.com/jaeoh2/Road-Lane-Instance-Segmentation-PyTorch](https://github.com/jaeoh2/Road-Lane-Instance-Segmentation-PyTorch). I modified the model and replaced Max_Unpool2d layers with other layers since it is not supported by TensorRT for now.

## To Reproduce

1. model and inference code can be accessed here: [https://drive.google.com/drive/folders/1qY39K8hViS1OW2GH5_TkZzE9lpHtXfru?usp=sharing](https://drive.google.com/drive/folders/1qY39K8hViS1OW2GH5_TkZzE9lpHtXfru?usp=sharing)
2. run torch_inference.py to run torch inference and export onnx model
3. run onnx_inference.py to run onnx inference
4. check outputs from torch model and onnx model, they are not the same

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.17.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_etc.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0a0
[conda] Could not collect

onnx == 1.6.0
onnxruntime == 1.2.0

## Additional context

I'm using NVIDIA Jetson AGX Xavier, NVIDIA related environment (driver, cuda, cudnn, etc.) are configured by the NVIDIA SDK manager. My final goal is to convert torch model to TensorRT engine (through ONNX) and run inference on AGX Xavier platform.

Thanks!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by pancho111203** [comment]
I'm getting the same issue

**Comment by spandantiwari** [comment]
@WIll-Xu35 - do you see anything obviously wrong with the exported ONNX model? Let us know if you do. Otherwise it may be better to open an issue with TensorRT to why the numbers are different from PyTorch.

**Comment by pancho111203** [comment]
@spandantiwari Could you please explain what's the role of TensorRT on this? My example uses CPU for computing both on PyTorch API and on onnxruntime after conversion of the same model, and the results are completely different. 

I'm a bit lost here as it's not clear who's repository is responsible for the bug (onnx, onnxruntime, PyTorch, TensorRT, ....)

**Comment by spandantiwari** [comment]
@pancho111203 - In this case PyTorch is the exporter of the ONNX model. Once the model is exported, it can be run in any backend that supports ONNX, such as Onnx Runtime and TensorRT. 

Opening post on this issue is about running the model in TensorRT, hence my suggestion to followup there (unless there's some indication that exported model is wrong, which cannot be ruled out). 

BTW, you mentioned you are seeing the same issue. Are you running this exact same model?

**Comment by spandantiwari** [comment]
@pancho111203 - would it be OK to close this issue?

**Comment by pancho111203** [comment]
@spandantiwari Yes, the issue ended up being unrelated to ONNX. Thanks for your help

**Comment by spandantiwari** [comment]
@pancho111203 - OK, thanks for confirming.
