### ISSUE TITLE
Scoped tracing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3906]
General strategy:
* We're going to introduce a new, special attribute, "impl_graph", available for all nodes, which contains a subgraph that could be inlined inplace of this node and preserve the semantics. The intent is that when we start tracing in a "scope", we'll create a single node, and then start tracing into the impl_graph subgraph for internal tracing that occurs. We call a node with "impl_graph" set an "aggregate node"
* How do we decide what graph we're tracing into? We're going to switch forward tracing to use TLS. Now the thread local state variable tracks what `impl_graph` you should be tracing into at any given point in time. In lieu of doing this properly, a global variable should suffice: https://github.com/pytorch/pytorch/pull/3016/files is a good place to start, as it does tracing in this way.
* How do we export a graph with these aggregate nodes? We first test if we know how to directly export the node. If so, we export and discard "impl_graph". Otherwise, we inline "impl_graph" and rerun the export on it.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by lantiga** [comment]
Looks great. Should I close #3016 ?

**Comment by ezyang** [comment]
No, I think we want to build off of that PR :)

**Comment by lantiga** [comment]
I see, let me know if I can help. I've come to enjoy working in `ir.h` :-)

**Comment by garymm** [comment]
Hi, I'm going through old issues with `module: onnx`.
Is this issue still relevant?
If so, how exactly does this relate to ONNX?
Perhaps made redundant by https://github.com/pytorch/rfcs/pull/24?

@ezyang

**Comment by ezyang** [comment]
This issue is still relevant, but feel free to close it if you don't know how to action it.

**Comment by garymm** [comment]
@BowenBao is there overlap between this and pytorch/rfcs#24?

**Comment by garymm** [comment]
Discussed with @BowenBao. For now this doesn't seem useful for ONNX export. We're getting some of this functionality via pytorch/rfcs#24.
