### ISSUE TITLE
Unable to Compile Code torch code in Visual Studio 2019

### ISSUE THREAD

**Issue by imanpalsingh** [pytorch/pytorch#39072]
# Description

I've tried finding resources regarding to this but they seem outdated.
The problem is that I am trying to build in visual studio with the binaries I downloaded from 

`https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.5.0.zip`

I have set the following properties in Visual Studio 2019

1) Additional include directories : `libtorch\include` ; `libtorch\include\torch\csrc\api\include\`
2) Additional Library Directory for linker : `\libtorch\lib\` 
3) Conformance mode to No
4) Linker input : `torch.lib;c10.lib` 
However the resources are also suggesting libs like `caffe2_nvrtc.lib` and `caffe2.lib` but they are not present in `\libtorch\lib\`

I tried to run the following program 

```cpp
#include<torch/torch.h>
#include<iostream>
int main()
{
	torch::Tensor tensor = torch::eye(3);
	std::cout << tensor << std::endl;
}
```
I got series of errors and warnings :

![Screenshot (48)](https://user-images.githubusercontent.com/49276301/83049178-646b0680-a068-11ea-85d8-af5c58cac6f4.png)

![Screenshot (49)](https://user-images.githubusercontent.com/49276301/83049521-f115c480-a068-11ea-824f-c1d4cb633131.png)

Operating System :  Windows 10

**Comment by imanpalsingh** [comment]
Found it to be a duplicate

**Comment by OodapowUiPath** [comment]
@imanpalsingh can you link the duplicate please?
