### ISSUE TITLE
``ToTensor()`` Exception for ``num_workers`` in ``DataLoader`` when ``torch.set_default_tensor_type(torch.cuda.FloatTensor)``

### ISSUE THREAD

**Issue by ain-soph** [pytorch/pytorch#39088]
## 🐛 Bug

Assume ``torch.set_default_tensor_type(torch.cuda.FloatTensor)``.
The Dataset is loaded from ``torchvision`` (e.g. ``torchvision.datasets.CIFAR10``) with ``transform=torchvision.transforms.ToTensor()``
We wrap the dataset with ``torch.utils.Dataloader`` and ``num_workers>0``.

Finally we traverse the data in the wrapped dataloader.

There will be ``RuntimeError`` for CUDA forked subprocess, which requires it to be ``spawn`` start method to use CUDA with multiprocessing. But excepted behavior of ``ToTensor()`` is to load data to cpu and there shouldn't such errors.

My understanding is that ``ToTensor()`` will involve CUDA when default tensor type is set to be ``cuda``. But it's not expected to do so
-------------------------------------------------------------

I can work around following the instructions to set ``spawn``. But this is annoying when I have many scripts. 

When ``num_worker=0`` or ``torch.multiprocessing.set_start_method('spawn')``, there will be no Exception and the data is loaded to ``cpu``  even though the default tensor type is ``cuda``.

> For Windows, the default method is already ``spawn`` rather than ``fork``. So it doesn't raise any Exception. there will be no Exception and the data is loaded to ``cpu`` as well.

Therefore, it seems the excepted behavior is that ``ToTensor()`` will only get ``PIL.Image`` to cpu tensor. Then maybe we should avoid involving CUDA during ``ToTensor()`` even when default tensor type is set to be ``cuda``. If that's the case, we can use ``fork`` start method and get cpu tensors without any Exception.

> Another small thing is that Windows requires ``if __name__ == '__main__':``, otherwise there will be an Exception about ``__main__`` and ``freeze_support()``. There will be no such Exception on Linux. I know it's easy to fix and a good manner to write it, but maybe it'll be better to fix it.

## To Reproduce

```python3

import torch
import torchvision

# Windows requires ``if __name__ == '__main__':`` for worker processes.
if __name__ == '__main__':
    dataset = torchvision.datasets.CIFAR10(
        root='./', transform=torchvision.transforms.ToTensor(), download=True)
    dataloader = torch.utils.data.DataLoader(dataset, num_workers=4)
    #------------------------------------------------------#
    # 1st stage
    print('cpu default')
    torch.set_default_tensor_type(torch.FloatTensor)
    try:
        for data in dataloader:
            print(data[0].device)
            break
    except Exception as e:
        print(e)
    #------------------------------------------------------#
    # 2nd stage
    print('move to gpu')
    torch.set_default_tensor_type(torch.cuda.FloatTensor)
    try:
        for data in dataloader:
            print(data[0].device)
            break
    except Exception as e:
        print(e)
    #------------------------------------------------------#
    # 3rd stage
    print('move to cpu')
    torch.set_default_tensor_type(torch.FloatTensor)
    try:
        for data in dataloader:
            print(data[0].device)
            break
    except Exception as e:
        print(e)

```

The output on Linux is:

```
cpu default
cpu
move to gpu
<Exception>
move to cpu
cpu
```

The Exception is 

```
Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 70, in default_collate
    return torch.tensor(batch)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 148, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

```

## Expected behavior

```
cpu default
cpu
move to gpu
cpu
move to cpu
cpu
```

## Environment

 - PyTorch Version: 1.5.0
 - OS: Ubuntu 18.04 and Windows10
 - How you installed PyTorch: conda
 - Python version: 3.7.7
 - CUDA version: 10.2

**Comment by SsnL** [comment]
the root cause is that `fork` inherits the current process state, including default tensor type, while `spawn` doesn't. this is a fundamental difference between the two start methods, and not really pytorch/torchvision specific.

**Comment by ain-soph** [comment]
> the root cause is that `fork` inherits the current process state, including default tensor type, while `spawn` doesn't. this is a fundamental difference between the two start methods, and not really pytorch/torchvision specific.

Yeah I understand that. But if ``ToTensor()`` doesn't use the default tensor type and only transforms data to cpu tensors, there will be no Exceptions for ``fork`` start method.

**Comment by SsnL** [comment]
I'm not convinced that `ToTensor`'s expected behavior is to move to CPU though. It's name suggests that it just converts to a tensor.

**Comment by ain-soph** [comment]
> I'm not convinced that `ToTensor`'s expected behavior is to move to CPU though. It's name suggests that it just converts to a tensor.

I think it's a widely applied transform function for dataset during image processing. And there will be such exceptions when default tensor type it set to be ``cuda`` and start method is ``fork``. If we use the ``spawn`` start, the subprocess will forget the default tensor and transform data to cpu tensors.

If that's the case, why not just make it fixed to cpu tensors? So that we can still use it in ``fork`` start without any modification. Otherwise, we have to change the start method.

**Comment by SsnL** [comment]
Okay, so the actual issue this is about is that `as_tensor(np_array)` initializes CUDA context when `default_tensor_type` is a CUDA tensor type. This sounds like a bug that should be fixed. Is this the case?

For your specific case, it is always advised against to using `set_default_tensor_type`, exactly because of these weird default behavior it introduces. It solely exists for legacy reasons. If the user want the code to be start-method-agnostic, they should not rely on fork vs spawn behavior anyways. If you want the worker to have a default tensor type, you should put `set_default_tensor_type` in either your dataset code or `worker_init_fn`.

**Comment by ain-soph** [comment]
> Okay, so the actual issue this is about is that `as_tensor(np_array)` initializes CUDA context when `default_tensor_type` is a CUDA tensor type. This sounds like a bug that should be fixed. Is this the case?
> 
> For your specific case, it is always advised against to using `set_default_tensor_type`, exactly because of these weird default behavior it introduces. It solely exists for legacy reasons. If the user want the code to be start-method-agnostic, they should not rely on fork vs spawn behavior anyways. If you want the worker to have a default tensor type, you should put `set_default_tensor_type` in either your dataset code or `worker_init_fn`.

Yes. Certainly you got my idea.

I ``set_default_tensor_type`` to cuda in the first line of my main script. And then I use a dataloader with num_workers, which causes such issues. I think this is the universal method.
You propose a good solution that to call ``set_default_tensor_type`` in ``worker_init_fn``. I think it's quite a good idea if we aim to transform data to gpu by calling ``ToTensor()``

**Comment by SsnL** [comment]
Okay so it turns out that `as_tensor` does the correct thing with `default_tensor_type` is CUDA. It moves the data to CUDA. 

However, torchvision uses `from_numpy` which never copies and thus always return a CPU tensor. Interestingly, their new addition of `pil_to_tensor` uses `as_tensor`, which means that it would return a CUDA tensor with a changed `default_tensor_type`. 

In view of this, this is not really a pytorch issue but a torchvision one. I've opened an issue at https://github.com/pytorch/vision/issues/2269. If you agree with my assessment, I will close this issue. 

Thanks for raising this to our concern!

**Comment by ain-soph** [comment]
> Okay so it turns out that `as_tensor` does the correct thing with `default_tensor_type` is CUDA. It moves the data to CUDA.
> 
> However, torchvision uses `from_numpy` which never copies and thus always return a CPU tensor. Interestingly, their new addition of `pil_to_tensor` uses `as_tensor`, which means that it would return a CUDA tensor with a changed `default_tensor_type`.
> 
> In view of this, this is not really a pytorch issue but a torchvision one. I've opened an issue at [pytorch/vision#2269](https://github.com/pytorch/vision/issues/2269). If you agree with my assessment, I will close this issue.
> 
> Thanks for raising this to our concern!

Glad to here that. It does turn out to be an torchvision issue. Thanks for you reply in time.

**Comment by ain-soph** [comment]
I think there still remain another inconsistency issue between ``DataLoader`` and ``default_tensor_type``.

In the setting of ``torch.set_default_tensor_type(torch.cuda.FloatTensor)`` and ``Dataset`` returns a tuple ``(cpu_tensor, int)``, we use ``DataLoader`` to wrap ``Dataset``.
Current ``DataLoader`` will return a tuple of ``(cpu_tensor, cuda_tensor)``. **Obviously the ``DataLoader`` batch the labels into a tensor using default type.** Is this the expected behavior? If so, maybe it should also transform the image data tensor to ``cuda`` as well.
```python3 
import torch
import torchvision

torch.set_default_tensor_type(torch.cuda.FloatTensor)

# Windows requires ``if __name__ == '__main__':`` for worker processes.
if __name__ == '__main__':
    # torch.multiprocessing.set_start_method('spawn')
    dataset = torchvision.datasets.CIFAR10(
        root='./', transform=torchvision.transforms.ToTensor(), download=True)

    #------------------------------------------------------#
    # 1st stage
    print()
    print('1st stage')
    dataloader = torch.utils.data.DataLoader(dataset, num_workers=0)
    try:
        for data in dataset:
            print(data[0].device)
            print(type(data[1]))
            print()
            break
    except Exception as e:
        print(e)
    #------------------------------------------------------#
    # 2nd stage
    print()
    print('2nd stage')
    dataloader = torch.utils.data.DataLoader(dataset, num_workers=0)
    try:
        for data in dataloader:
            print(data[0].device)
            print(data[1].device)
            print()
            break
    except Exception as e:
        print(e)

Script Output:

```
Files already downloaded and verified

1st stage
cpu
<class 'int'>


2nd stage
cpu
cuda:0

```

**Comment by SsnL** [comment]
It is expected, and I don’t think we should change it. The collated result
is from the collate_fn used. And the default one respects existing dtype.
Anyways, you should not use set_default_tensor_type, but use device
objects, as is recommended.
