### ISSUE TITLE
[v1.5.1] Release Tracker

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#39104]
We cut a [release branch](https://github.com/pytorch/pytorch/tree/release/1.5) for a 1.5.1 maintenance release.

This issue is for tracking cherry-picks to the branch.  The criteria for a change to be included is ALL of the following:

1. bug fix or documentation fix/improvement (i.e. NOT a feature and doesn't break BC)
2. already landed in master or specific to 1.5.1
3. worth the risk/reward.  We will most likely only include changes that fix regressions from 1.4.0 to 1.5.0 (or fixes for features that weren't in 1.4), but tiny fixes for large bugs will also be considered.

If you need a change to be cherry-picked to the branch, please open a PR against the [release/1.5](https://github.com/pytorch/pytorch/tree/release/1.5) branch and comment below.  Any details you can provide about the criteria above (e.g. links to master PR, description of the severity of the bug fix) are helpful.  Ultimately we will make an inclusion / no inclusion call and communicate that here.

**NOTE: do not land the PRs yourself.  Our normal tools (ghstack / ghimport, etc.) do not work on the release branch.  Someone else will land your change for you.**

--------

[Current PRs open against the branch](https://github.com/pytorch/pytorch/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Arelease/1.5)

cc @ezyang @seemethere @malfet

**Comment by gchanan** [comment]
placeholder: 1.5.1 version of https://github.com/pytorch/pytorch/pull/34307.

**Comment by gchanan** [comment]
placeholder: 1.5.1 version of https://github.com/pytorch/pytorch/pull/36503.

**Comment by mrshenli** [comment]
placeholder: 1.5.1 version of #38512

**Comment by gchanan** [comment]
placeholder for port of https://github.com/pytorch/pytorch/pull/38033.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38695.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38615.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38046.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38674.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/37788.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38943.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/35069/.

**Comment by SsnL** [comment]
https://github.com/pytorch/pytorch/pull/39149, port of https://github.com/pytorch/pytorch/pull/38925

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/37355.

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/38670.

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/38860.

**Comment by rohan-varma** [comment]
Should we cherry pick https://github.com/pytorch/pytorch/pull/38729? It fixes a SyncBN issue that wasn't an issue in 1.4, but is in 1.5.

**Comment by zasdfgbnm** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/39212

This PR can not be trivially cherry-picked to 1.5.1 branch, because the implementations of `min` and `max` are different. I will write a PR for 1.5.1 once it is merged on master. cc: @ngimel

**Comment by gchanan** [comment]
> Should we cherry pick #38729? It fixes a SyncBN issue that wasn't an issue in 1.4, but is in 1.5.

Multiple people on the issue reported that it was a regression, so yes.

**Comment by seemethere** [comment]
https://github.com/pytorch/pytorch/pull/39278, FBGEMM submodule update to fix compilation on windows.

cc @malfet

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/pull/39288, port of #39218.

**Comment by peterjc123** [comment]
#39290, port of #37811.

**Comment by peterjc123** [comment]
#39291, port of #38302.

**Comment by gchanan** [comment]
placeholder for https://github.com/pytorch/pytorch/pull/38156.

**Comment by seemethere** [comment]
Tracking release branches for domain libraries that will need to be updated for `v1.5.1`:

- [x] [pytorch/vision@release/0.6](https://github.com/pytorch/vision/tree/release/0.6)
- [x] [pytorch/audio@release/0.5](https://github.com/pytorch/audio/tree/release/0.5)

Torch doesn't actually need to be updated since it's dependencies don't actually list a specific version for `torch`/`pytorch` other than `>=1.2`

cc @vincentqb @fmassa

**Comment by zasdfgbnm** [comment]
How about this? https://github.com/pytorch/pytorch/pull/39339
It is the `unique_consecutive` version of #38156.

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/39344, port of https://github.com/pytorch/pytorch/pull/38729

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/39301.

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/39375.

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/39047.

**Comment by VitalyFedyunin** [comment]
#39484 port of #37968

**Comment by raghuramank100** [comment]
#39499 port of #35961

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/pull/39515

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/39542, port of https://github.com/pytorch/pytorch/pull/39540.

**Comment by gchanan** [comment]
https://github.com/pytorch/pytorch/pull/39543, port of https://github.com/pytorch/pytorch/pull/38264.

**Comment by seemethere** [comment]
https://github.com/pytorch/pytorch/pull/39547, port of https://github.com/pytorch/pytorch/pull/39253

**Comment by gchanan** [comment]
Placeholder for https://github.com/pytorch/pytorch/pull/38646.

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/pull/40080, port of #39987
