### ISSUE TITLE
HalfTensor should have contiguous()

### ISSUE THREAD

**Issue by dzhulgakov** [pytorch/pytorch#3910]
Is there a good reason it's not there? Feels like we should provide it (it's probably a missing part in ATen, not higher-level wrappers)

```
In [1]: import torch
In [2]: x=torch.FloatTensor([2])
In [3]: y=torch.HalfTensor([2])
In [4]: x.contiguous()
Out[4]:
 2
[torch.FloatTensor of size 1]
In [5]: y.contiguous()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-7809c9b217bf> in <module>()
----> 1 y.contiguous()
AttributeError: 'torch.HalfTensor' object has no attribute 'contiguous'
```

cc @zdevito @ezyang

**Comment by soumith** [comment]
torch.HalfTensor  (the CPU side) has no ops except copy and serialization. It's provided just as a serialization helper for the GPU equivalent.

**Comment by apaszke** [comment]
On the other hand contiguous() is `torch.HalfTensor(t.size()).copy_(t)`, so there's no reason why it shouldn't be supported

**Comment by vishwakftw** [comment]
I believe we support `.contiguous()` for half Tensors now, closing in view of this.
