### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zuoxiang95** [pytorch/pytorch#3911]
hello, when i use command "python setup.py install " to install pytorch, i get this error:

torch/csrc/cudnn/Conv.cpp: In instantiation of ‘void torch::cudnn::{anonymous}::findAlgorithm(THCState*, cudnnHandle_t, const torch::cudnn::Convolution&, bool, bool, void*, void*, void*, algo_t*) [with algo_t = cudnnConvolutionBwdDataAlgo_t; THCState = THCState; cudnnHandle_t = cudnnContext*]’:
torch/csrc/cudnn/Conv.cpp:468:83:   required from ‘torch::cudnn::{anonymous}::Workspace torch::cudnn::{anonymous}::chooseAlgorithm(THCState*, cudnnHandle_t, const torch::cudnn::Convolution&, bool, bool, void*, void*, void*, algo_t*) [with algo_t = cudnnConvolutionBwdDataAlgo_t; THCState = THCState; cudnnHandle_t = cudnnContext*]’
torch/csrc/cudnn/Conv.cpp:725:18:   required from here
torch/csrc/cudnn/Conv.cpp:451:96: error: ‘struct cudnnConvolutionBwdDataAlgoPerf_t’ has no member named ‘determinism’
torch/csrc/cudnn/Conv.cpp: In instantiation of ‘void torch::cudnn::{anonymous}::findAlgorithm(THCState*, cudnnHandle_t, const torch::cudnn::Convolution&, bool, bool, void*, void*, void*, algo_t*) [with algo_t = cudnnConvolutionBwdFilterAlgo_t; THCState = THCState; cudnnHandle_t = cudnnContext*]’:
torch/csrc/cudnn/Conv.cpp:468:83:   required from ‘torch::cudnn::{anonymous}::Workspace torch::cudnn::{anonymous}::chooseAlgorithm(THCState*, cudnnHandle_t, const torch::cudnn::Convolution&, bool, bool, void*, void*, void*, algo_t*) [with algo_t = cudnnConvolutionBwdFilterAlgo_t; THCState = THCState; cudnnHandle_t = cudnnContext*]’
torch/csrc/cudnn/Conv.cpp:765:20:   required from here
torch/csrc/cudnn/Conv.cpp:451:96: error: ‘struct cudnnConvolutionBwdFilterAlgoPerf_t’ has no member named ‘determinis’
error: command 'gcc' failed with exit status 1

I am very appreciate if anyone can give me some advices.

**Comment by apaszke** [comment]
What's your cuDNN versions?

**Comment by zuoxiang95** [comment]
My cuDNN‘s version is 5.1.5

**Comment by apaszke** [comment]
That's the problem. We only support 6 and up. Please upgrade it before building.
