### ISSUE TITLE
THCudaCheck Error

### ISSUE THREAD

**Issue by sydney0zq** [pytorch/pytorch#3912]
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCStorage.c line=32 error=4 : unspecified launch failure
Traceback (most recent call last):
  File "resnet50_avg.py", line 133, in <module>
    model = train_model(model, criterion, optimizer_ft, exp_lr_scheduler, n_epochs=70)
  File "resnet50_avg.py", line 87, in train_model
    running_loss += loss.data[0]
RuntimeError: cuda runtime error (4) : unspecified launch failure at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/THCStorage.c:32
```

It occurs in Epoch 3/69. I don't know how to solve it. Can anyone help?

**Comment by SsnL** [comment]
Did this happen in the middle of training? Or it happened at the beginning? What happens if you restart and train again?
Could you check that driver and CUDA (and cuDNN if used) are installed properly please?

**Comment by sydney0zq** [comment]
Yes, it happened in the middle of training. And I restart my program, mostly it goes well to the end.

**Comment by SsnL** [comment]
Okay, that's good to hear. 

Let us know if it happens again :) In that case, it would be great if you can provide a reproducing script.
