### ISSUE TITLE
`verbose` unused in `torch.backends.cudnn`

### ISSUE THREAD

**Issue by ShawnZhong** [pytorch/pytorch#39129]
Seems that `verbose` is unused in `torch.backends.cudnn`

https://github.com/pytorch/pytorch/blob/f5bc91f851f7d3b862643b51f06f0281eb225b8c/torch/backends/cudnn/__init__.py#L87-L100

cc: @ezyang 

cc @csarofeen @ptrblck

**Comment by guol-fnst** [comment]
I can fix it by removing this parameter.

**Comment by ezyang** [comment]
It would be good to double check what it was historically used for, but yes, let's get rid of it if it isn't actually used, or document where it is used if otherwise.
