### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 16 6 5 5, expected input[6, 16, 2, 2] to have 6 channels, but got 16 channels instead

### ISSUE THREAD

**Issue by lee64456546** [pytorch/pytorch#39135]
I have a simple network:
```python
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
     
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.conv2(x)
        return x
```

and try to call 
```python
torch.jit.trace
```
to get the graph, here is my code 
```python
input_shape = (3, 20, 20)
dummy_input = torch.randn(6, *input_shape)
graph = torch.jit.trace(model, dummy_input)
```
And I got the error, is there a way to solve it ? Thanks.

**Comment by lufol** [comment]
Hey, after you call `x = self.pool(F.relu(self.conv2(x)))` in the forward function of your model the dimensions of the resulting tensor are `torch.Size([6, 16, 2, 2])` and thus `x = self.conv2(x)` in the line after cannot deal with the 16 input channels as it expects just 6. 

Depending on what you intended to achieve with this model, I would either create a `conv3` with `nn.Conv2d(16, x, 5)` where `x` is your desired output channel size or just get rid of the last line in the forward function.

**Comment by SsnL** [comment]
Please use the forum for questions https://discuss.pytorch.org/
