### ISSUE TITLE
ReduceLROnPlateau

### ISSUE THREAD

**Issue by harikrishnavydana** [pytorch/pytorch#3916]
ReduceLROnPlateau is defined in lr_schedule but it is not pasted in __init__.py...so even after compiling new bleeading edge from github ...i could just see it but could not import it 
dir(torch.optim.lr_schedule.ReduceLROnPlateau) works it shows the operations 

import torch.optim.lr_schedule.ReduceLROnPlateau give import error

**Comment by apaszke** [comment]
`from torch.optim.lr_schedule import ReduceLROnPlateau`

**Comment by harikrishnavydana** [comment]
from torch.optim.lr_schedule import ReduceLROnPlateau
did not work i have added this line in __init__.py
from .lr_scheduler import *

dir(torch.optim)
['ASGD', 'Adadelta', 'Adagrad', 'Adam', 'Adamax', 'ExponentialLR', 'LBFGS', 'LambdaLR', 'MultiStepLR', 'Optimizer', 'RMSprop', 'ReduceLROnPlateau', 'Rprop', 'SGD', 'SparseAdam', 'StepLR', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'bisect_right', 'lr_scheduler', 'sparse_adam']



dir(torch.optim.ReduceLROnPlateau)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_init_is_better', '_reduce_lr', '_reset', 'in_cooldown', 'step']



from torch.optim import ReduceLROnPlateau                   gives this 
<class 'torch.optim.lr_scheduler.ReduceLROnPlateau'>

may be now it works
