### ISSUE TITLE
Add name argument to load_state_dict_from_url

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/pytorch#39196]
## 🚀 Feature
A ```name``` argument to the ```torch.hub.load_state_dict_from_url``` function

## Motivation

There is this problem when i download a pth file from a direct link to google drive, it is named by default ```uc```.

Now this is fine in normal cases but when i have multiple files i want to download, the function doesn't download them because the name is still there in the temporary folder.

In short, we need to add an argument to the function for naming so no confusion can happen.

## Pitch

Add a name to the downloaded file

## Alternatives

We can make folders to each file but i consider this a tedious solution and we can do better than this.

cc @ailzhang

**Comment by ailzhang** [comment]
Hmmm if google drive forces the name to be `uc`, it's a fair request to add an optional `file_name` argument to `load_state_dict_from_url`. 
@MohamedAliRashad Would you be interested in submitting a PR for it? It should be pretty straightforward. Thanks!

**Comment by MohamedAliRashad** [comment]
@ailzhang Can you check the PR and tell me your reviews ?

**Comment by MohamedAliRashad** [comment]
It has been merged here https://github.com/pytorch/pytorch/commit/f3f9415f81bb530dde63bf3f198656a06e5b5665
