### ISSUE TITLE
Convert onnx reduce functions with multiple axes to pytorch

### ISSUE THREAD

**Issue by kitstar** [pytorch/pytorch#3921]
Hi guys,

How could I convert ONNX reduce functions (ReduceMean, ReduceSum...) with multiple axes to pytorch? Seems the implementation of pytorch only support single axis? Thanks.

BR,
Kit

**Comment by ezyang** [comment]
Look here: https://discuss.pytorch.org/t/sum-mul-over-multiple-axes/1882

Basically, do multiple reductions.

**Comment by ezyang** [comment]
Also we are tracking the enhancement to PyTorch here: https://github.com/pytorch/pytorch/issues/2006
