### ISSUE TITLE
[FR] Add space as delimiter in TORCH_CHECK and other macros

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#39235]
## 🚀 Feature

Add space as delimiter in TORCH_CHECK, TORCH_INTERNAL_ASSERT and other macros. 

This should be as simple as changing `ss << t;` to `ss << t << " ";` here. (unless there is any CI checking exception string format)

https://github.com/pytorch/pytorch/blob/d068a456d3ad05e483738954436038a79221f7be/c10/util/StringUtil.h#L35-L39

## Motivation

The TORCH_INTERNAL_ASSERT message shown here. https://github.com/pytorch/pytorch/issues/39227

See the original code here https://github.com/pytorch/pytorch/blob/ce0500eb4cbcc4c3e48f59ebb28b60ce60e16634/aten/src/ATen/native/cuda/Indexing.cu#L220

The string "... value tensor" and two numbers are passed as va_args to TORCH_INTERNAL_ASSERT macro, and later printed on the screen without any delimiters. Because of that, user is seeing an output as *"... value tensor21"*, which should be *"... value tensor 2 1"*. The current message is very confusing.

## Pitch

See above.

## Additional context

If a string argument in the current version of TORCH_CHECK macro already contains a trailing or leading space, this extra space may cause two consecutive spaces printed in the output. This scenario definitely exists. Not sure if this is a concern. 

cc @ezyang @bhosmer @smessmer @ljk53

**Comment by ShawnZhong** [comment]
> If a string argument in the current version of TORCH_CHECK macro already contains a trailing or leading space, this extra space may cause two consecutive spaces printed in the output. This scenario definitely exists. Not sure if this is a concern.

By browsing through the code base, it seems to me that space is already added in the string literal in most cases. Maybe we can just fix each individual places where the delimiter is missing. 

https://github.com/pytorch/pytorch/blob/d1212e58143982978b8c02d5f54c3f96ee804186/aten/src/ATen/core/ivalue_inl.h#L755-L826

https://github.com/pytorch/pytorch/blob/d1212e58143982978b8c02d5f54c3f96ee804186/aten/src/ATen/native/NamedTensor.cpp#L319-L323

**Comment by gchanan** [comment]
If I understand correctly, you are asking that we automatically add a space after each delimiter.  I don't think we are going to do this, because it makes it impossible to _not_ have a space when you don't want it (and you can find a number of examples in the codebase where we don't want a space).

**Comment by ngimel** [comment]
Agree with @ShawnZhong, in most cases error strings already contain the necessary spaces, those that don't can be fixed at the call site, it does not make sense to silently insert spaces in the TORCH_CHECK macro itself.
