### ISSUE TITLE
Missing code in 'Installing C++ distribution of Pytorch'

### ISSUE THREAD

**Issue by Dudly01** [pytorch/pytorch#39236]
## 📚 Documentation

The document enclosing the details of how one installs the C++ distribution of Pytorch, found [here](https://pytorch.org/cppdocs/installing.html), is missing one paragraph of code between the sentences _In that case CMake configuration step would look something like follows:_ and _If all goes well, it will look something like this:_

Apologies if this is not the place to report this, this was the best fit according to the template text.

cc @yf225 @glaringlee

**Comment by ShawnZhong** [comment]
There is a missing empty line in the doc. I have opened a PR https://github.com/pytorch/pytorch/pull/39237 to fix this.

**Comment by glaringlee** [comment]
@ShawnZhong Approved, thanks for adding this back. cc @yf255
