### ISSUE TITLE
Histogram Observer throws RuntimeError if input is zero

### ISSUE THREAD

**Issue by samgd** [pytorch/pytorch#39239]
## 🐛 Bug

The `HistogramObserver` class assumes that the data it receives is non-zero. If the data it receives is zero initially (i.e. no non-zero data passed to it for the first two samples) it throws a `RuntimeError` as it attempts to create a tensor with shape that is large and negative. 

---

The `self.min_val` and `self.max_val` attributes initially contain no values:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L649-L650

On the first call, the observer sets the `self.min_val` and `self.max_val`. However, it does not check if they are zero:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L833-L840

The next call then triggers the else condition. The else condition calls into the `self._adjust_min_max` method to compute the `downsample_rate`:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L841-L850

The `self._adjust_min_max` method computes the downsample rate by dividing the new histogram width by the old, where the old width is computed by multiplying the number of bins by `hist_bin_width`:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L788-L797

However, `hist_bin_width` is zero as `self.max_val - self.min_val == 0 - 0 == 0`.

The `downsample_rate` variable is therefore a value divided by zero, meaning it ends up being `torch.ceil(torch.tensor(float("inf"))).to(torch.int)`. This is a very large negative number.

`downsample_rate` is then passed to `self._combine_histograms call:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L855-L861

where it is used to initialise a zero-valued tensor:

https://github.com/pytorch/pytorch/blob/a53422e0ee9dd28fa25140c3ae9a4e622467fcf5/torch/quantization/observer.py#L815

This call fails with a `RuntimeError` such as this:

```
RuntimeError: Trying to create tensor with negative dimension -4398046511104: [-4398046511104]
```

## Expected behavior

`HistogramObserver` should be able to gracefully receive zero-valued data initially. Many domains, such as audio, do contain zero-valued data initially.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by supriyar** [comment]
Thanks for bringing up the issue @samgd! 
Confirmed that this is indeed a bug and we will work on a fix for this.

**Comment by supriyar** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/40191

**Comment by samgd** [comment]
@supriyar can you try it with all the same constant value that is not equal to zero also? I expect it to fail and not be caught by the fix
