### ISSUE TITLE
API suggestion: add torch.mod and maybe deprecate torch.fmod

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#39259]
On C/C++, the `f` in `fmod` means floating point. But PyTorch's `torch.fmod` supports all dtypes, it makes no sense to have an `f` in the front.

cc @mruberry

**Comment by gchanan** [comment]
I believe it's the same as numpy.

**Comment by mruberry** [comment]
@gchana is correct, and @zasdfgbnm is correct the names are misleading.

numpy.mod returns the remainder of floor division, numpy.fmod returns the remainder of true division.
