### ISSUE TITLE
 torch.distributed.init_process_group() init_method arg needs better docs

### ISSUE THREAD

**Issue by jlquinn** [pytorch/pytorch#3927]
At the moment, the documentation for the init_method argument just says that env is the default, but doesn't specify what valid arguments are, nor where to find that out.   There is a distributed tutorial that describes this:
http://pytorch.org/tutorials/intermediate/dist_tuto.html 

Please provide a link to that tutorial, if that is the official documentation on what init_methods are supported.  Otherwise, this function should document the valid options.

**Comment by apaszke** [comment]
What about [the distributed docs](http://pytorch.org/docs/master/distributed.html#tcp-initialization)?
