### ISSUE TITLE
Move replicate from DataParallel to C

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#3930]
It can take as long as 180ms for networks as large as ResNet1001, mostly because it has a lot of tiny parameters, and Python loops take forever. The broadcasts itself are quite fast. The snippet below prints 34ms for the first loop and 4ms for the second one.

```python
import time                                                 
import torch                                                
from torch.cuda.comm import broadcast_coalesced             
                                                            
params = [torch.cuda.FloatTensor(3500) for i in range(3000)]
                                                            
for i in range(10):                                         
    start = time.time()                                     
    broadcast_coalesced(params, [0, 1])                     
    torch.cuda.synchronize()                                
    end = time.time()                                       
    print(((end - start) * 1000), 'ms')                     
                                                            
print('-' * 80)                                             
flat_param = torch.cat(params)                              
for i in range(10):                                         
    start = time.time()                                     
    broadcast_coalesced([flat_param], [0, 1])               
    torch.cuda.synchronize()                                
    end = time.time()                                       
    print(((end - start) * 1000), 'ms')                     
```

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
But parameters are flattened? I've never seen broadcast take 180ms (though I did not run resnet 1001). Using torch.cat instead of memcopy to flatten parameters makes some difference.  
And remove broadcasting buffers, it's useless, as we've discussed :-)

**Comment by apaszke** [comment]
Actually I just realized that it's not only broadcast, but the whole `replicate` part. In `nvvp` Broadcast takes 82ms, but there are still 120ms of other stuff that we do before we start forward (I haven't finished annotating the trace yet).

**Comment by apaszke** [comment]
Also, yes I know making everything flat makes a difference - the point is that we're really far from the optimal perf in this case.

**Comment by ngimel** [comment]
Yes, whole replicate part is pretty bad. Doing it once in the __init__ would be awesome, but what if model has changed? Don't trust nvvp traces, though, they are distorted beyond recognition for broadcast/optimizer, because lots of small kernels.

**Comment by apaszke** [comment]
That's true, but I'm still pretty sure that there are still some pretty significant savings waiting there. Yes, doing that only once in `__init__` would be the best, but I don't think there's any way to do it in general. We might need some cleverness to improve/simplify `replicate`. I have some pretty complicated ideas that could solve it, but would like to see if there's nothing simpler that would help.

**Comment by apaszke** [comment]
I'll annotate all the ranges in the CPU profiler to get their real CPU cost tomorrow.

**Comment by vadimkantorov** [comment]
Concerning the Python loops, I once got 2x-5x time improvement by converting loops to using map / list comprehensions

**Comment by apaszke** [comment]
I did some CPU-only benchmarking (no nvprof, just `time.time()`), and here are the results. If you look at the [code of replicate](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/replicate.py#L4), you can see that it has 4 main parts:
1. Broadcasting modules
2. Broadacsting buffers
3. Cloning modules
4. Assigning parameters after cloning

The costs of each of these parts look like this:
1. 47.58 ms (drop from 58ms before @ngimel's patch)
2. 25.30 ms (drom frop 33ms before @ngimel's patch)
3. 54.28 ms 
4. 13.26 ms 

**TOTAL: 140.42ms**

So even though the patch helps a bit, there's still a long way to go. I think I have an idea that would let us cache the modules so we could avoid the expensive cloning, and the remaining logic just needs to be moved to C++.

**Comment by apaszke** [comment]
Some preliminary results from caching the replicas. Unless the cache doesn't need to be refreshed the times look like this:

1. Broadcasting parameters - 34.05 ms 
2. Broadcasting buffers - 16.02 ms 
3. Result assignment - 15.74 ms

**TOTAL: 65.81 ms**

BTW This change doesn't move anything to C++, so that is still an option to get better perf.
