### ISSUE TITLE
Use nn.spectral_norm in LSTM

### ISSUE THREAD

**Issue by valexsyu** [pytorch/pytorch#39311]
Hi ,
I want to use nn.spectral_norm in LSTM. 
Spectral_norm need name of weight, but LSTM has 2 weights( weight_ih_l[k] and weight_hh_l[k]) in one layer. So I use a for loop to iterate LSTM's weight.  

## To Reproduce

1.  i use the following code to apply spectral_norm in LSTM 
```
    def lstm_spectral_norm(self,input_size, hidden_size, n_layers, batch_first=True, bidirectional = False):
        lstm = nn.LSTM(input_size, hidden_size, n_layers, batch_first, bidirectional)
        name_pre = 'weight'
        for i in range(n_layers):
            name = name_pre+'_hh_l'+str(i)
            spectral_norm(lstm, name)
            name = name_pre+'_ih_l'+str(i)
            spectral_norm(lstm, name)
        return lstm
 ```   

2.  after running my_model.cuda(), i got the following error:

```    Traceback (most recent call last):
  File "run.py", line 220, in <module>
    trainer = RENILANMTTrainer(
  File "/home/valex/Documents/Study/renilanmt/renilanmt/trainer.py", line 29, in __init__
    self.dis_trainer = TrainerKit1( model.dis, dataset, dis_optimizer, dis_scheduler, multigpu, using_horovod)
  File "/usr/lib/python3.8/site-packages/nmtlab/trainers/base.py", line 54, in __init__
    self.register_model(model)
  File "/usr/lib/python3.8/site-packages/nmtlab/trainers/base.py", line 125, in register_model
    self._model.cuda()
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 140, in _apply
    self.flatten_parameters()
  File "/usr/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 126, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: param_from.type() == param_to.type() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/cudnn/RNN.cpp:541, please report a bug to PyTorch. parameter types mismatch
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Arch Linux
GCC version: (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130
CMake version: Could not collect

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 440.59
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.4.0
[pip3] torchtext==0.5.0
[conda] Could not collect

## Additional context

cc @albanD @mruberry @zou3519

**Comment by albanD** [comment]
Hi,

It looks like the spectral_norm utils does not work well with the LSTM because of the way the weights need to be packed to be used by cudnn.

**Comment by valexsyu** [comment]
> Hi,
> 
> It looks like the spectral_norm utils does not work well with the LSTM because of the way the weights need to be packed to be used by cudnn.

Thanks for your reply .
yes, it happen this error after run my_model.cuda(). How do I to pack weights for using cudnn?
Thanks~

**Comment by albanD** [comment]
The packing is done automatically when it is possible to be used by cudnn. So usually when you move the weights to cuda.

**Comment by valexsyu** [comment]
> The packing is done automatically when it is possible to be used by cudnn. So usually when you move the weights to cuda.

Hi albanD,
 Thank you ,
   I am not clear about cuda, I would like to ask you for advice, as your mention, but I don't know how to fix the problem, could you give me some specific  ways to do ,if the problem can be fixed.

**Comment by mruberry** [comment]
fyi @ngimel, too.

**Comment by albanD** [comment]
I'm afraid there is no easy way to fix it.
Either lstm or spectral_norm would need to be modified to work properly.

**Comment by ngimel** [comment]
fwiw, the following script works on master (and likely in 1.5)
```
import torch

def lstm_spectral_norm(input_size, hidden_size, n_layers=1):
    lstm = torch.nn.LSTM(input_size, hidden_size, n_layers)
    name_pre = 'weight'
    for i in range(n_layers):
        name = name_pre+'_hh_l'+str(i)
        torch.nn.utils.spectral_norm(lstm, name)
        name = name_pre+'_ih_l'+str(i)
        torch.nn.utils.spectral_norm(lstm, name)
    return lstm

ninp = 128
m = lstm_spectral_norm(ninp, ninp)
name = 'weight_hh_l0'
m = m.cuda()
print([(name, p.device) for name, p in m.named_parameters()])
inp = torch.randn(3, 32, 128, device="cuda")
```
There was a bug that was fixed couple months back.

**Comment by ngimel** [comment]
Closing, feel free to reopen if it is still repros.

**Comment by valexsyu** [comment]
> I'm afraid there is no easy way to fix it.
> Either lstm or spectral_norm would need to be modified to work properly.

Thanks for you reply

**Comment by valexsyu** [comment]
> fwiw, the following script works on master (and likely in 1.5)
> 
> ```
> import torch
> 
> def lstm_spectral_norm(input_size, hidden_size, n_layers=1):
>     lstm = torch.nn.LSTM(input_size, hidden_size, n_layers)
>     name_pre = 'weight'
>     for i in range(n_layers):
>         name = name_pre+'_hh_l'+str(i)
>         torch.nn.utils.spectral_norm(lstm, name)
>         name = name_pre+'_ih_l'+str(i)
>         torch.nn.utils.spectral_norm(lstm, name)
>     return lstm
> 
> ninp = 128
> m = lstm_spectral_norm(ninp, ninp)
> name = 'weight_hh_l0'
> m = m.cuda()
> print([(name, p.device) for name, p in m.named_parameters()])
> inp = torch.randn(3, 32, 128, device="cuda")
> ```
> 
> There was a bug that was fixed couple months back.

Hi ngimel ,
Thanks for your reply.
I will try it on 1.5 version.

**Comment by valexsyu** [comment]
> Closing, feel free to reopen if it is still repros.
hi ngimel,

i will get the below warring after using pytorch 1.5:
'''
../aten/src/ATen/native/cudnn/RNN.cpp:1269: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
'''
 the problem is the same even using self.lstm.flatten_parameters() before self.lstm(input)

thanks a lot 
valex
