### ISSUE TITLE
Using caffe2 models under GPU Windows

### ISSUE THREAD

**Issue by dryarullin** [pytorch/pytorch#39325]
## 🐛 Bug

When I use libtorch 1.3 from official site and libtorch builded by me, I get an error:
_[enforce fail at context_gpu.h:206] error == cudaSuccess. 700 vs 0. Error at: C:/..\..\caffe2/core/context_gpu.h:206: an illegal memory access was encountered
Error from operator:
input: "input" input: "tdnn1.affine_w" input: "tdnn1.affine_b" output: "tdnn1.affine" type: "Conv" arg { name: "kernels" ints: 1 ints: 5 } arg { name: "dilations" ints: 1 ints: 1 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 }(no backtrace available)_

When using a 1.5 version from the official site, I get runtime error:
_ucrtbase.dll abort()_

CPU versions work correctly.

## To Reproduce

```
	caffe2::TensorCPU m_tensorInCPU(caffe2::CPU);
	const std::vector<std::size_t> dims{ 1, N, 1, M};
	m_tensorInCPU.Resize(dims);

	caffe2::NetDef initNetDef;
	caffe2::ReadProtoFromFile(initNetFile, &initNetDef);
	const auto cuda_device = caffe2::TypeToProto(caffe2::CUDA);
	initNetDef.mutable_device_option()->set_device_type(cuda_device);

	caffe2::Workspace m_ws;
```

Here Libtorch 1.5 version from the official site, runtime error:ucrtbase.dll abort():
```
	m_ws.RunNetOnce(initNetDef);
```

```
        caffe2::NetDef m_netDef;
	caffe2::ReadProtoFromFile(predNetFile, &m_netDef);
	m_netDef.mutable_device_option()->set_device_type(caffe2::PROTO_CUDA);

	float* netInputData =  m_tensorInCPU.mutable_data<float>();
	for (size_t i = 0; i < N; i++) {
		for (size_t j = 0; j < M; j++) {
			*netInputData = 1.0;
			++netInputData;
		}
	}
	std::unique_ptr<caffe2::Workspace> m_wsLocal;
	caffe2::Blob* blobIn;
	caffe2::NetBase* net;

	m_wsLocal.reset(new caffe2::Workspace(&m_ws));
	blobIn = m_wsLocal->CreateLocalBlob("input");
	m_wsLocal->CreateLocalBlob("output");
	net = m_wsLocal->CreateNet(m_netDef);

	caffe2::TensorCPU* tensorIn = BlobGetMutableTensor(blobIn, caffe2::CUDA);

	tensorIn->ResizeLike(m_tensorInCPU);
	tensorIn->ShareData(m_tensorInCPU);
```
Here Libtorch 1.3 version
[enforce fail at context_gpu.h:206] error == cudaSuccess. 700 vs 0. 

```
	try {
		net->Run();
	}
	catch (c10::Error& ex) {
		std::cout << ex.what() << std::endl;
	}
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.3 and 1.5
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): binaries from pytorch.org and builded me
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1/7.6.4
 - GPU models and configuration: GeForce RTX 2080
 - Any other relevant information:

## Additional context

cc @peterjc123 @nbcsm @guyang3532

**Comment by kcarlson** [comment]
I'm also seeing this issue running 1.6 on windows 10 with GPU support.

**Comment by Blackhex** [comment]
Closing as Caffe2 on Windows is out of support.
