### ISSUE TITLE
Log probability of Relaxed Bernoulli

### ISSUE THREAD

**Issue by yannadani** [pytorch/pytorch#39332]
## 🐛 Bug

The probability computed by Relaxed Bernoulli samples seems to be greater than 1 on most occasions. Not sure if its a bug or just a behaviour due to numerical issues.
## To Reproduce

1. See the code snippet below 
```
import torch
dist =  torch.distributions.relaxed_bernoulli.RelaxedBernoulli(torch.tensor(0.1), probs = torch.tensor([0.8]))
samp = dist.rsample()
samp_prob = torch.exp(dist.log_prob(samp))
print(samp_prob)
```
## Expected behavior
I am assuming probability to be less than 1 always.

## Environment

 - PyTorch Version (e.g., 1.5):
 - OS (e.g., Linux):
 - How you installed PyTorch (`pip`):
 - Python version: 3.7.3
 - CUDA/cuDNN version: 10.2

**Comment by SsnL** [comment]
density of continuous distribution can be > 1.

**Comment by yannadani** [comment]
Yes sure. But I was interpreting the semantics of `log_prob` to be the actual probability since thats how it is used pretty much at all other places. Thanks for clarifying though.
