### ISSUE TITLE
Can not find documentation about torch._thnn.type2backend

### ISSUE THREAD

**Issue by lukelu0520** [pytorch/pytorch#39366]
Dear pytorch,

I've searched Documentation but can not find any description on type2backend.
Maybe I miss something, so was wondering if you could point out a direction to me.
So we are able to know what does type2backend do in many opensource projects (especially, those used 0.4 version)

Best,
-- Luke

**Comment by izdeby** [comment]
Please, use our [forum](http://discuss.pytorch.org/) for questions.
