### ISSUE TITLE
ONNX.export

### ISSUE THREAD

**Issue by suppwilly** [pytorch/pytorch#39396]
I want to find the corresponding relationship between pytorch model and onnx model during transformation, I found that scope in the conversion process can provide those information,
```
Float(64, 10, 24, 24) = onnx::Conv, scope: Net/Conv2d[conv1_3x3]
```
But when I add clone after this layer, this information will disappear:
```
        x = self.conv1_3x3(x)
        x = x.clone()
```
```
Float(64, 10, 24, 24) = onnx::Conv, scope: Net
```
How can I solve this problem, or do you have a better way to get the corresponding relationship.

**Comment by izdeby** [comment]
Please, use our [forum](http://discuss.pytorch.org/) for questions.
