### ISSUE TITLE
Documentation for torch.nn page is slow to load

### ISSUE THREAD

**Issue by drozzy** [pytorch/pytorch#39391]
### Problem
Every time I navigate to torch.nn documentation, the right menu takes about **5 seconds** to load.
https://pytorch.org/docs/stable/nn.html

Here is the menu I'm talking about:

<img width="1424" alt="menu" src="https://user-images.githubusercontent.com/140710/83494890-eb631900-a484-11ea-813e-6462405d5ed0.png">

and here is how it looks _before_ the page is fully loaded:

<img width="1213" alt="loading" src="https://user-images.githubusercontent.com/140710/83495864-42b5b900-a486-11ea-9d51-c53a1e239e6d.png">

### Why is this an issue?

This presents the issue to the user for the following reasons:
1. It is not clear if the documentation page is broken: when user lands on the nn page - it looks like the right menu is _not_ working. 
2. It is not clear if menu is hidden. Menu can disappear if the browser window is resized to be smaller. Here is how that looks (notice how it is very similar to the case where menu hasn't loaded yet):
<img width="1029" alt="hidden" src="https://user-images.githubusercontent.com/140710/83495033-25341f80-a485-11ea-848a-80527f1973b5.png">

3. This is a quality of life issue that I'm sure affects every pytorch user multiple times a day. Considering that this is the most common doc page, it probably translates to hundreds of hours of waiting time across the developer community.

### Solution

There are a few possible solutions to this (in my personal order of preference):

1. Speed it up - the best solution would be for the page to load in under 1 second.
2. Show signs of life - the next best solution would be to indicate to the user that the menu is still loading in some way.
3. Put the menu on the left, replacing the left-hand menu. This should remove the need for dynamic loading of the menu or maybe give it more room.

Thank you!

P.S.: I love Pytorch guys, it's great! Thanks for all the hard work.

**Comment by ShawnZhong** [comment]
The loading speed issue has been fixed in the master docs at https://pytorch.org/docs/master/nn.html

**Comment by izdeby** [comment]
Closing as fixed.
