### ISSUE TITLE
Return namedtuples from torch.* function with multiple return arguments

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#394]
Because this:
```python
actions = model(input).max(1).indices
```
looks much better than this:
```python
actions = model(input).max(1)[1]
```

**Comment by zasdfgbnm** [comment]
I'm working with C++ functions at https://github.com/pytorch/pytorch/pull/15429

**Comment by zasdfgbnm** [comment]
List of ATen operators we should change:
- [ ] adaptive_max_pool1d
- [ ] embedding_bag
- [ ] gesv
- [ ] kthvalue
- [ ] max
- [ ] median
- [ ] min
- [ ] mode
- [ ] slogdet
- [ ] unique
- [ ] gels
- [ ] trtrs
- [ ] symeig
- [ ] eig
- [ ] svd
- [ ] pstrf
- [ ] qr
- [ ] geqrf
- [ ] orgqr
- [ ] ormqr
- [ ] btrifact
- [ ] sort
- [ ] topk
- [ ] adaptive_max_pool2d
- [ ] adaptive_max_pool3d

**Comment by zasdfgbnm** [comment]
We also need to make JIT support namedtuple

**Comment by zasdfgbnm** [comment]
@ezyang Should we reopen this?

**Comment by ezyang** [comment]
Yeah sure.

**Comment by zasdfgbnm** [comment]
Just a note here, need to refactor TupleTypes into TupleTypes and NamedTupleTypes, as discussed in
https://github.com/pytorch/pytorch/pull/16505#discussion_r253032509

**Comment by zasdfgbnm** [comment]
need to reopen...

**Comment by KushajveerSingh** [comment]
@zasdfgbnm Are you still working on this? I can also work on this issue. Any pointers on what I should be working on?

**Comment by zasdfgbnm** [comment]
@KushajveerSingh No, I am not working on this right now. You can take a look at https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml and find an operator that you are interested in and is not supporting namedtuple yet.

**Comment by KushajveerSingh** [comment]
@zasdfgbnm  Thanks for the info.
