### ISSUE TITLE
Pytorch could save the model in FP16(Half) mode and reload it to FP32.

### ISSUE THREAD

**Issue by PistonY** [pytorch/pytorch#39428]
The test code as below with Pytorch 1.5.0.
```python
import torch
from torchvision.models import resnet18

model = resnet18().cuda().half().eval()
test_data = torch.randn(1, 3, 224, 224, requires_grad=False).half().cuda()
o1 = model(test_data)
torch.save(model.state_dict(), 'model.pkl')

model_reload = resnet18().cuda().eval()
model_reload.load_state_dict(torch.load('model.pkl'))
o2 = model_reload(test_data.float())

print(o1[0, :10])
print(o2[0, :10])
```
Output is
```shell
tensor([-2.6133,  1.2568,  1.2480, -3.5898,  2.0137, -3.8184,  0.0066, -2.9961,
         1.4814, -0.0954], device='cuda:0', dtype=torch.float16,
       grad_fn=<SliceBackward>)
tensor([-2.6130,  1.2568,  1.2472, -3.5904,  2.0137, -3.8177,  0.0066, -2.9975,
         1.4819, -0.0968], device='cuda:0', grad_fn=<SliceBackward>)
```
I don't know this is actually allowed or it's a bug.

**Comment by vadimkantorov** [comment]
I think it is actually allowed. This is no different from any other `float32_tensor.copy_(float16_tensor)` operation that incurs a type cast.

**Comment by PistonY** [comment]
When I load a FP16 model to FP32, all the calculation is in FP32 mode right?That's the reason why results are a little different.

**Comment by PistonY** [comment]
Even if it is allowed, I think a warning here should be good.

**Comment by vadimkantorov** [comment]
> When I load a FP16 model to FP32, all the calculation is in FP32 mode right?That's the reason why results are a little different.

Correct, all calculation is in FP32

**Comment by izdeby** [comment]
Closing as expected behavior.

**Comment by jinfagang** [comment]
@vadimkantorov This is confusing, while i saevd fp16 model in pth, when exporting it to onnx, it return a bug to me
