### ISSUE TITLE
How to save tensor to 16-bit image?

### ISSUE THREAD

**Issue by wh75er** [pytorch/pytorch#39427]
So, I have a Tensor, which represents my 16-bit 3-channel image and I wanna save it. How could I do this? I was trying 

```
torchvision.utils.save_image(gt[j], f"hdr_{j+1}.tiff")
```
But seems like it works only for 8-bit images... Could someone help me to save my tensor to 16-bit 3-channel image(any format would be good. I think .tiff is fine)?

**Comment by izdeby** [comment]
Please, use our [forums](discuss.pytorch.org) for questions.
