### ISSUE TITLE
verify_ninja_availability does not return True

### ISSUE THREAD

**Issue by 0phoff** [pytorch/pytorch#39436]
## 🐛 Bug

According to the [documentation](https://pytorch.org/docs/stable/cpp_extension.html#torch.utils.cpp_extension.verify_ninja_availability), the `verify_ninja_availability()` function should return True if Ninja is available on the user system.

However, quickly looking at the implementation shows that it returns nothing and just raises a RuntimeError if ninja is not available.

## To Reproduce

```python
# Run on system with and without Ninja

from torch.utils.cpp_extension import verify_ninja_availability
verify_ninja_availability()   # Does not return bool
```

## Expected behavior

Either the documentation should be updated to correctly tell it will raise an error, or the function itself should be modified to return a boolean.

Personally, I am more in favor of returning a boolean, as it is annoying to need to wrap a function in a try/except.

## Environment
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro M2000
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] lightnet-torch==1.1.0
[pip3] numpy==1.16.1
[pip3] torch==1.5.0+cu101
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.0+cu101
[conda] Could not collect

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
@0phoff 
It seems this doc line is for _is_ninja_available instead of verify_ninja_availability, if you need a true or false return value, you can use _is_ninja_available. I will update the doc and will change _is_ninja_available to is_ninja_available since this should be a public api. cc @yf225

**Comment by 0phoff** [comment]
is `_is_ninja_available()` a public function that we are meant to use ?  
I figured that since it started with an underscore, it means it is an internally used function.
