### ISSUE TITLE
Expected a value of type 'Tensor' for argument 'input' but instead found type 'int'.

### ISSUE THREAD

**Issue by KevinZ1992** [pytorch/pytorch#39442]
MyModule is one part of my model, i try to transform it on android, but meet the error just like:
forward(__torch__.torch.nn.quantized.modules.activation.ReLU self, Tensor input) -> (Tensor):
Expected a value of type 'Tensor' for argument 'input' but instead found type 'int'.
Inferred 'input' to be of type 'Tensor' because it was not annotated with an explicit type.

## To Reproduce
`class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.act = nn.ReLU(inplace=False)  

    def forward(self, input):
        xx = 0
        i = -1
        #xx = torch.ones(2,3)
        if i > 0:
            xx = torch.ones(2,3)
            xx = self.act(xx)
        return xx

model = MyModule()
torch.jit.script(model).save('test.pt')`

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 5.5.0
CMake version: version 3.17.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 410.48
cuDNN version: Could not collect

**Comment by izdeby** [comment]
Please, use our [forum](http://discuss.pytorch.org/) for questions.
