### ISSUE TITLE
Any Pytorch function can work as Keras's "TimeDistributed"?

### ISSUE THREAD

**Issue by shizhenjun** [pytorch/pytorch#3946]
In keras,there is a timedistributed function (https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py)  which can apply a layer to each temporal slice, I hope the author can develop a function like that.

**Comment by soumith** [comment]
you can do `TimeDistributed` in pytorch with a regular `for` loop.

**Comment by julioasotodv** [comment]
Indeed, this works with the default "eager mode". However, I cannot make it to work with a for loop in TorchScript mode...

**Comment by soumith** [comment]
@julioasotodv for loops are supported in TorchScript mode, as documented

**Comment by julioasotodv** [comment]
@soumith indeed, but only looping over range() or a tuple; not over a tensor

**Comment by soumith** [comment]
@julioasotodv we do support looping over a Tensor's size.

```
In [3]: @torch.jit.script
   ...: def foo(x):
   ...:     for i in range(x.size(0)):
   ...:         print(i)
   ...:

In [4]: foo(torch.randn(10))
0
1
2
3
4
5
6
7
8
9
```

You can also loop on the value of a Tensor:

```
In [5]: @torch.jit.script
   ...: def foo(x):
   ...:     for i in range(int(x[0])):
   ...:         print(i)
   ...:

In [6]: foo(torch.full((5,), fill_value=10.0))
0
1
2
3
4
5
6
7
8
9
```
