### ISSUE TITLE
pytorch README build table cleanup for ppc64le

### ISSUE THREAD

**Issue by dncliss** [pytorch/pytorch#39461]
## 🐛 Bug
The current top level README.md has a table that lists CI builds and python versions.  The versions are listed as 3.6, 3.7, and 3.8.
The ppc64le builds are listed under the 3.8 column, even though we have been building it on 3.7 for a while.  This happened when the columns were renamed under #35677 (but the ppc64le build links weren't moved to stay under 3.7).

A second related issue with the ppc64le links in this table is that the GPU link points to our nightly CI build titled "pytorch-linux-cuda92-cudnn7-py3-mpi-build-test-gpu".  This is misleading as
we are building with cuda 10.2, not 9.2.  The action I will take here is to remove the cuda version
from the URL link by renaming the actual build job.  However, once I do that, the link URL in the README will be incorrect and thus broken.  So, I will prepare a PR here and submit it, first; I will then rename the job soon after, so that the window of time when the link is wrong will be minimal.

The CPU link is named `pytorch-master-nightly-py3-linux-ppc64le` so I think I'll just add a `-gpu` suffix to the same name to indicate the GPU build.

cc @ezyang @seemethere @malfet

**Comment by dncliss** [comment]
PR https://github.com/pytorch/pytorch/pull/39475/files submitted.

The build has now been renamed, so the link to the old name is briefly incorrect (until this file is merged).

**Comment by seemethere** [comment]
closed with #39475, thanks for the contribution @dncliss!
