### ISSUE TITLE
Refactor RPC's matchBuiltinOp

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#39465]
## 🚀 Feature
the `matchBuiltinOp` function in rpc/python_functions.cpp goes through potentially all operators for a symbol i.e. those given by `torch::jit::getAllOperatorsFor(symbol)`, and tries to match a schema with `torch::jit::createStackForSchema`. However since the ordering is not necessarily guaranteed, we could potentially go through a large amount of schemas before finding the right one. It's also not great that we swallow errors here, this leads to an issue with RPC-based profiling where we print out the tensor in the error message, thus resulting in a bunch more incorrect ops reported in profiler output.

## Motivation
This issue originally came from investigating an issue with the profiler in RPC, where unexpected operators are showing up in the profiler output. This is the case because this causes stringification of the tensors in its error handling, resulting in additional operators.

## Pitch
Hopefully it's possible to directly find the right schema using the symbol, args, and kwargs, instead of searching through the list.

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @gmagogsfm @suo @xush6528

**Comment by ezyang** [comment]
Yes please fix this

**Comment by wconstab** [comment]
It sounds like @rohan-varma may be working (or planning to work) on this issue and coordinating with JIT team.  Let us know if not and we can discuss in our triage.

**Comment by rohan-varma** [comment]
@wconstab @ezyang To fix this from the RPC framework perspective, my main thinking was to refactor `matchBuiltinOp` in rpc/python_functions.cpp to do something similar to `invokeOperatorFromPython` in `pybind_utils.h`, which essentially searches through the given list of operators and tries to find a matching schema.

In the case it cannot find a matching schema, it throws an invalid operator error and I believe we should do the same for RPC, as this indicates that something went wrong when trying to run the operator that the user specified with the given args/kwargs. In this case, we essentially get rid of the exception swallowing by throwing the exception when we cannot find a match out of all candidates.

**Comment by wconstab** [comment]
@rohan-varma we're removing from the jit triage queue assuming you're working on it. let us know otherwise.

**Comment by rohan-varma** [comment]
@wconstab Sounds good, I will probably ping JIT folks on the PR to get feedback on any jit side changes.
