### ISSUE TITLE
torch.flatten returns a view, but isn't documented or tested for doing so

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#39474]
We should add the appropriate documentation, registration, and tests. See also https://github.com/pytorch/pytorch/issues/36403. 

@albanD 

cc @jlin27 @mruberry @suo @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by SsnL** [comment]
it works like `reshape`, only returning a view when it is able to.

**Comment by albanD** [comment]
So for the jit, no need to mark these ops as returning views?

**Comment by eellison** [comment]
[related](https://github.com/pytorch/pytorch/issues/38731) 😛

**Comment by albanD** [comment]
Ok so I guess you want to add `reshape` and `flatten` to that list.
We can scope this issue in only adding them to the view doc. The other issue will take care of fixing the jit behavior.

**Comment by mruberry** [comment]
> Ok so I guess you want to add `reshape` and `flatten` to that list.
> We can scope this issue in only adding them to the view doc. The other issue will take care of fixing the jit behavior.

We should still update flatten's actual doc and add a test in TestViewOps. Even reshape describes its behavior as returning a view if possible.

**Comment by albanD** [comment]
Yes that's why I marked the issue as docs and operator for the testing.

**Comment by mruberry** [comment]
This was fixed by #49501!
