### ISSUE TITLE
a bug of data loading

### ISSUE THREAD

**Issue by alexalex1234** [pytorch/pytorch#3948]
I compile the pytorch by source .
I have this bug when I train my model

![bug](https://user-images.githubusercontent.com/17522043/33421347-b588e5bc-d5ec-11e7-9258-7ee945b423d9.png)

**Comment by apaszke** [comment]
It's not a bug, it's a problem of your system, which probably ran out of shared memory. You can try to resize the shared memory file system as described e.g. [in here](http://www.walkernews.net/2010/05/04/how-to-resize-devshm-filesystem-in-linux/). You can check the size with `df -h /dev/shm`.

Please try these steps, and reopen the issue only if this doesn't help you.
