### ISSUE TITLE
Aten compile error

### ISSUE THREAD

**Issue by Minju-Jung** [pytorch/pytorch#3949]
I got the following errors when I compile the pytorch source code.
I tried the solution suggested in #3571, but it didn't work for me ...

[Environment]
CentOS - 7.2.1511
python - 3.5.2
gcc - 4.8.5
cmake - 3.6.2

I will really appreciate if someone give me the way to solve this issue.

> Scanning dependencies of target ATen
[  2%] Building CXX object src/ATen/CMakeFiles/ATen.dir/CPUGenerator.cpp.o
[  3%] Building CXX object src/ATen/CMakeFiles/ATen.dir/CUDAGenerator.cpp.o
[  5%] Building CXX object src/ATen/CMakeFiles/ATen.dir/Context.cpp.o
[  5%] Building CXX object src/ATen/CMakeFiles/ATen.dir/DLConvertor.cpp.o
[  6%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ExpandUtils.cpp.o
[  9%] Building CXX object src/ATen/CMakeFiles/ATen.dir/Scalar.cpp.o
[  9%] Building CXX object src/ATen/CMakeFiles/ATen.dir/Formatting.cpp.o
[  9%] Building CXX object src/ATen/CMakeFiles/ATen.dir/UndefinedTensor.cpp.o
[ 11%] Building CXX object src/ATen/CMakeFiles/ATen.dir/UndefinedType.cpp.o
[ 11%] Building CXX object src/ATen/CMakeFiles/ATen.dir/Utils.cpp.o
[ 13%] Building CXX object src/ATen/CMakeFiles/ATen.dir/native/Indexing.cpp.o
[ 13%] Building CXX object src/ATen/CMakeFiles/ATen.dir/native/NativeFunctions.cpp.o
[ 15%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUByteStorage.cpp.o
[ 18%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUByteType.cpp.o
[ 18%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUByteTensor.cpp.o
[ 19%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUCharStorage.cpp.o
[ 21%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUCharType.cpp.o
[ 23%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUCharTensor.cpp.o
[ 23%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUDoubleStorage.cpp.o
[ 24%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUDoubleType.cpp.o
[ 24%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUDoubleTensor.cpp.o
[ 25%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUFloatStorage.cpp.o
[ 25%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUFloatType.cpp.o
[ 26%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUFloatTensor.cpp.o
[ 27%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUIntStorage.cpp.o
[ 28%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUIntType.cpp.o
[ 29%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPUIntTensor.cpp.o
[ 30%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPULongStorage.cpp.o
[ 31%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPULongType.cpp.o
In file included from /home/m/minju-jung/pytorch/aten/src/ATen/Scalar.h:13:0,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/Tensor.h:4,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUDoubleTensor.h:8,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUDoubleTensor.cpp:1:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUDoubleTensor.cpp: In member function ‘virtual at::Scalar at::CPUDoubleTensor::localScalar()’:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUDoubleTensor.cpp:69:64: error: expected ‘)’ before ‘PRId64’
   AT_ASSERT(numel == 1,"localScalar() called on Tensor with %" PRId64 " elements",numel);
                                                                ^
/home/m/minju-jung/pytorch/aten/src/ATen/Utils.h:12:65: note: in definition of macro ‘AT_ASSERT’
 #define AT_ASSERT(cond, ...) if (! (cond) ) { at::runtime_error(__VA_ARGS__); }
                                                                 ^
In file included from /home/m/minju-jung/pytorch/aten/src/ATen/Scalar.h:13:0,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/Tensor.h:4,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUFloatTensor.h:8,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUFloatTensor.cpp:1:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUFloatTensor.cpp: In member function ‘virtual at::Scalar at::CPUFloatTensor::localScalar()’:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUFloatTensor.cpp:69:64: error: expected ‘)’ before ‘PRId64’
   AT_ASSERT(numel == 1,"localScalar() called on Tensor with %" PRId64 " elements",numel);
                                                                ^
/home/m/minju-jung/pytorch/aten/src/ATen/Utils.h:12:65: note: in definition of macro ‘AT_ASSERT’
 #define AT_ASSERT(cond, ...) if (! (cond) ) { at::runtime_error(__VA_ARGS__); }
                                                                 ^
In file included from /home/m/minju-jung/pytorch/aten/src/ATen/Scalar.h:13:0,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/Tensor.h:4,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUByteTensor.h:8,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUByteTensor.cpp:1:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUByteTensor.cpp: In member function ‘virtual at::Scalar at::CPUByteTensor::localScalar()’:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUByteTensor.cpp:69:64: error: expected ‘)’ before ‘PRId64’
   AT_ASSERT(numel == 1,"localScalar() called on Tensor with %" PRId64 " elements",numel);
                                                                ^
/home/m/minju-jung/pytorch/aten/src/ATen/Utils.h:12:65: note: in definition of macro ‘AT_ASSERT’
 #define AT_ASSERT(cond, ...) if (! (cond) ) { at::runtime_error(__VA_ARGS__); }
                                                                 ^
In file included from /home/m/minju-jung/pytorch/aten/src/ATen/Scalar.h:13:0,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/Tensor.h:4,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.h:8,
                 from /home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp:1:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp: In member function ‘virtual at::Scalar at::CPUCharTensor::localScalar()’:
/home/m/minju-jung/pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp:69:64: error: expected ‘)’ before ‘PRId64’
   AT_ASSERT(numel == 1,"localScalar() called on Tensor with %" PRId64 " elements",numel);
                                                                ^
/home/m/minju-jung/pytorch/aten/src/ATen/Utils.h:12:65: note: in definition of macro ‘AT_ASSERT’
 #define AT_ASSERT(cond, ...) if (! (cond) ) { at::runtime_error(__VA_ARGS__); }
                                                                 ^
[ 32%] Building CXX object src/ATen/CMakeFiles/ATen.dir/ATen/CPULongTensor.cpp.o
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/ATen/CPUFloatTensor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/ATen/CPUDoubleTensor.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/ATen/CPUByteTensor.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/ATen/CPUCharTensor.cpp.o] Error 1

**Comment by vadimkantorov** [comment]
If you have an existing version of PyTorch installed, this problem may be another manifestation of https://github.com/pytorch/pytorch/issues/3669, i.e. old headers are picked up. A workaround for https://github.com/pytorch/pytorch/issues/3669 is removing the old headers from system include path.

**Comment by romejoe** [comment]
I ran into the same problem today, only running on Redhat 7.2 instead. @vadimkantorov I removed my initial PyTorch install and any other clones that I had, but that didn't help. I followed the solution in [3571](https://github.com/pytorch/pytorch/issues/3571) and got it to work. Here's my diff:

`
diff --git a/aten/src/ATen/templates/TensorDerived.h b/aten/src/ATen/templates/TensorDerived.h
index 9ef474d..69a8f91 100644
--- a/aten/src/ATen/templates/TensorDerived.h
+++ b/aten/src/ATen/templates/TensorDerived.h
@@ -1,5 +1,8 @@
 #pragma once
 
+#define __STDC_FORMAT_MACROS
+#include <inttypes.h>
+
 $th_headers
 
 #include "ATen/Tensor.h"
`

**Comment by Minju-Jung** [comment]
Thank you for kind helping!
Unfortunately, romejoe's solution does not work for me ...

**Comment by lysuhin** [comment]
I had similar issue and was able to fix that by removing `libtorch` package in conda distribution (I thought only `pytorch` and `torchvision` are the ones to be removed).

**Comment by gchanan** [comment]
this seems to be addressed.
