### ISSUE TITLE
[QAT] Modules use qconfig to reinit a activation instance and weight instance.

### ISSUE THREAD

**Issue by huyangc** [pytorch/pytorch#39521]
Why the QAT modules reinit a activation/weight instance in of qconfig other than use the existed one?

For example, https://github.com/pytorch/pytorch/blob/master/torch/nn/qat/modules/conv.py#L31

After using the prepare_qat, observers have already added into the module, and here just reinit again other than use the one before, I am a little confused. Because if I want to implement some observers that with status(correlated with the original observed modules), the status will be remove when reinit another one.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
please post questions to https://discuss.pytorch.org/c/quantization/17
This is not a `reinit`, qconfig.activation is not a observer module instance, it is a function that can create observer module instance.

**Comment by huyangc** [comment]
thanks
