### ISSUE TITLE
[1.5.1] py3.6-devtoolset7-rocmrpm-centos7-build is failing on the 1.5. branch

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#39545]
See e.g.: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py3.6-devtoolset7-rocmrpm-centos7-build/33487/console

cc @jeffdaily @sunway513

**Comment by VitalyFedyunin** [comment]
Can we close it?

**Comment by gchanan** [comment]
The build is passing now, although the tests might be failing (although it might have been an environment failure).
