### ISSUE TITLE
throw error when EmbeddingBag(..., sparse=True) and slice the embedding's weight

### ISSUE THREAD

**Issue by guvcolie** [pytorch/pytorch#39559]
## 🐛 Bug

I use EmbeddingBag(..., sparse=**True**, ...) and SGD optimizer. And I will **slice** the embedding.weight dynamicly when forward, then F.embedding_bag(inputs, weight=[**sliced_embedding_weight**], offsets=offset, sparse=**True**).
It's OK when forward and got my correct loss, however, I got a error report when loss.backward()

## To Reproduce

My EmbeddingBag warp code is. as below:
```
import torch.nn as nn
import torch.nn.functional as F
class DynamicEmbeddingBag_(nn.Module):
    def __init__(self, num_embeddings,
                 max_embedding_dim,
                 mode="mean",
                 sparse=True):
        super(DynamicEmbeddingBag_, self).__init__()
        self.max_embedding_dim = max_embedding_dim
        self.num_embeddings = num_embeddings
        self.mode = mode
        self.sparse = sparse

        self.current_embedding_dim = self.max_embedding_dim

        # TODO fixed params for nn.EmbeddingBag
        self.max_norm = None
        self.norm_type = 2.
        self.scale_grad_by_freq = False
        self.include_last_offset = False

        self.embedding = nn.EmbeddingBag(num_embeddings=num_embeddings,
                                         embedding_dim=self.max_embedding_dim,
                                         max_norm=self.max_norm,
                                         norm_type=self.norm_type,
                                         scale_grad_by_freq=self.scale_grad_by_freq,
                                         mode=self.mode,
                                         sparse=self.sparse,
                                         _weight=None,
                                         # include_last_offset=self.include_last_offset
                                         )

    def forward(self, inputs, offset=None, out_embedding_dim=None):
        if out_embedding_dim is None:
            out_embedding_dim = self.current_embedding_dim

        assert out_embedding_dim <= self.max_embedding_dim, \
            "out_embedding_dim %d is more than max_embedding_dim %d !!!" % (out_embedding_dim, self.max_embedding_dim)

        self.current_embedding_dim = out_embedding_dim
        # slice op or [x: y] is NOT supported now!!!
        weight = self.embedding.weight[:, : self.current_embedding_dim].contiguous()  # slice weight !!!
        result = F.embedding_bag(inputs,
                                 weight=weight,
                                 offsets=offset,
                                 max_norm=self.max_norm,
                                 norm_type=self.norm_type,
                                 scale_grad_by_freq=self.scale_grad_by_freq,
                                 mode=self.mode,
                                 sparse=self.sparse)
        return result
```

the error report is as below:

```
Traceback (most recent call last):
  File "/Users/xxx/work/AAA/main.py", line 212, in <module>
    training(stage=Stage.FullTrain, **main_kwargs)
  File "/Users/xxx/work/AAA/main.py", line 161, in training
    train_net(train_dataloader, model, loss_fn, optimizer_fn, **kwargs)
  File "/Users/xxx/work/AAA/train_normal.py", line 36, in train_net
    loss.backward()
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: sparse tensors do not have strides (strides at /Users/distiller/project/conda/conda-bld/pytorch_1587428061935/work/aten/src/ATen/SparseTensorImpl.cpp:52)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x10c22aab7 in libc10.dylib)
frame #1: at::SparseTensorImpl::strides() const + 448 (0x111610240 in libtorch_cpu.dylib)
frame #2: at::native::slice(at::Tensor const&, long long, long long, long long, long long) + 652 (0x111a4ee7c in libtorch_cpu.dylib)
frame #3: at::TypeDefault::slice_Tensor(at::Tensor const&, long long, long long, long long, long long) + 14 (0x111ddbb6e in libtorch_cpu.dylib)
frame #4: c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long long, long long, long long, long long), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long long, long long, long long, long long> >, at::Tensor (at::Tensor const&, long long, long long, long long, long long)>::call(c10::OperatorKernel*, at::Tensor const&, long long, long long, long long, long long) + 34 (0x111e44932 in libtorch_cpu.dylib)
frame #5: at::Tensor c10::OperatorHandle::callUnboxed<at::Tensor, at::Tensor const&, long long, long long, long long, long long>(at::Tensor const&, long long, long long, long long, long long) const + 281 (0x11161e689 in libtorch_cpu.dylib)
frame #6: torch::autograd::VariableType::slice_Tensor(at::Tensor const&, long long, long long, long long, long long) + 1482 (0x113e6c39a in libtorch_cpu.dylib)
frame #7: c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<at::Tensor (*)(at::Tensor const&, long long, long long, long long, long long), at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, long long, long long, long long, long long> >, at::Tensor (at::Tensor const&, long long, long long, long long, long long)>::call(c10::OperatorKernel*, at::Tensor const&, long long, long long, long long, long long) + 34 (0x111e44932 in libtorch_cpu.dylib)
frame #8: at::Tensor c10::OperatorHandle::callUnboxed<at::Tensor, at::Tensor const&, long long, long long, long long, long long>(at::Tensor const&, long long, long long, long long, long long) const + 281 (0x11161e689 in libtorch_cpu.dylib)
frame #9: torch::autograd::generated::SliceBackward::apply(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&&) + 419 (0x113818ef3 in libtorch_cpu.dylib)
frame #10: torch::autograd::Node::operator()(std::__1::vector<at::Tensor, std::__1::allocator<at::Tensor> >&&) + 658 (0x114004ed2 in libtorch_cpu.dylib)
frame #11: torch::autograd::Engine::evaluate_function(std::__1::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 1408 (0x113ffb6a0 in libtorch_cpu.dylib)
frame #12: torch::autograd::Engine::thread_main(std::__1::shared_ptr<torch::autograd::GraphTask> const&, bool) + 497 (0x113ffa8b1 in libtorch_cpu.dylib)
frame #13: torch::autograd::Engine::thread_init(int) + 152 (0x113ffa648 in libtorch_cpu.dylib)
frame #14: torch::autograd::python::PythonEngine::thread_init(int) + 52 (0x110b4aa04 in libtorch_python.dylib)
frame #15: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (torch::autograd::Engine::*)(int), torch::autograd::Engine*, int> >(void*) + 66 (0x114009c32 in libtorch_cpu.dylib)
frame #16: _pthread_start + 148 (0x7fff69ce8109 in libsystem_pthread.dylib)
frame #17: thread_start + 15 (0x7fff69ce3b8b in libsystem_pthread.dylib)
```

## Expected behavior

EmbeddingBag(..., sparse=**True**, ...) should support slice op or embeding_bag.weight[start: end] when **loss.backward()** and **optimizer.step()**.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 430.14
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchfile==0.1.0
[pip] torchnet==0.0.4
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h6bb024c_0    defaults
[conda] mkl                       2020.0                      166    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py37ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py37hd6b4f25_0    defaults
[conda] numpy                     1.18.1           py37h4f9e942_0    defaults
[conda] numpy-base                1.18.1           py37hde5b4d6_1    defaults
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.5.0                py37_cu101    pytorch

cc @ezyang @SsnL @albanD @zou3519 @gqchen @mruberry

**Comment by guvcolie** [comment]
hi @ezyang @SsnL @albanD @zou3519 @gqchen @mruberry, this error appears only when EmbeddingBag(..., sparse=True, ...) and slice the embeddingbag's weight. 
If I set sparse=False, everything is OK, but the training efficiency is very low (4~5 time cost more than sparse=True). So I wish that EmbeddingBag(..., sparse=True, ...) can support slice op, I think it's very meaningful. Thank you!

**Comment by albanD** [comment]
Hi,

The issue is that the sparse embedding bag returns sparse gradients which are not handled by most backward functions.
I think only the gradient accumulation on the weights is expected to work fine here actually. I will expect the autograd engine to raise an error, even if slice computed the gradients, because the type of the gradients is different from the type of the forward Tensor (Sparse vs Dense).

I'm sure we could change the backward implementation of slice, but I'm not sure about the engine's behavior here.

**Comment by guvcolie** [comment]
hi @albanD , thanks for the quick reply！

You said "the type of the gradients is different from the type of the forward Tensor (Sparse vs Dense).", I don't particularly understand that.  I think there's no difference between my warpper implementation and the raw EmbeddingBag, except for an slice op.
I'm sure that nn.Linear1d and other CV's convolution ops can support the slice op and [start: end] when loss.backward() and optimizer.step(), but only the sparse embedding bag raise an error. 
 
Could you tell me when do you plan to finish  the backward implementation of slice ^_^ Thank you!

**Comment by SsnL** [comment]
@albanD 
> I will expect the autograd engine to raise an error, even if slice computed the gradients, because the type of the gradients is different from the type of the forward Tensor (Sparse vs Dense).

I don't think this is right. Dense tensor (leaf or intermediate result) should be able to have sparse gradients with no problem.

**Comment by SsnL** [comment]
@guvcolie What @albanD said is the following:

Backprop through embeddingbag is fine, but that gives you a sparse gradient, which is further backprop'ed through the slicing before embeddingbag. And slice backward doesn't support sparse gradient yet.

**Comment by guvcolie** [comment]
@SsnL Thank you for the detailed answer. Maybe the underlying mechanism of pytorch is more complicated than I thought.

Do you plan to implement this issue officially, including the backprop and autograd? I have no experience with autograd module ...

**Comment by albanD** [comment]
> I don't think this is right. Dense tensor (leaf or intermediate result) should be able to have sparse gradients with no problem.

Ok makes sense. I wasn't sure.

> And slice backward doesn't support sparse gradient yet.

The thing is that even slice forward does not support it. I think this is mainly because slice returns views but returning a view for this sparse Tensor might not be possible.
@SsnL  do you have an idea how to implement this? Or just the backward without using slicing?

 > A current alternative workaround is to implement a custom slice backward that supports sparse gradients in a python autograd Function.

@guvcolie  you can use the following as a workaround for now:
```python
import torch
from torch import autograd


a = torch.rand(2, 10, requires_grad=True)

# This assumes a 2D input where you take only the idx elements of the second dimension
class MyFn(autograd.Function):
    @staticmethod
    def forward(ctx, inp, idx):
        ctx.inp_size = inp.size()
        ctx.idx = idx
        out = inp[:, :idx]
        return out

    @staticmethod
    def backward(ctx, gO):
        assert gO.is_sparse, "Only sparse gradient implemented for MyFn"
        gI = torch.sparse.FloatTensor(size=ctx.inp_size).to(gO.device, gO.dtype)
        # This is bad bad bad, but works
        # Note that you won't be able to do double backward here
        gI.indices = gO.indices
        gI.values = gO.values

        return gI, None

if False:
    # Raises the same error as your example
    b = a[:, :5]
else:
    b = MyFn.apply(a, 5)

b.backward(torch.sparse.FloatTensor(size=(2, 5)))
```

**Comment by SsnL** [comment]
@guvcolie there is another easy alternative, do slicing after embeddingbag.

**Comment by SsnL** [comment]
@albanD 
> The thing is that even slice forward does not support it. I think this is mainly because slice returns views but returning a view for this sparse Tensor might not be possible.

I don't think forward is related though. The problem is `grad_out` is sparse. When the dense view receives a sparse gradient, it should be able to backpropagate through slice okay (by offsetting the indices).

**Comment by guvcolie** [comment]
> @guvcolie there is another easy alternative, do slicing after embeddingbag.

That's a excellent trick! Thank you!
