### ISSUE TITLE
Different CIFAR10 performance on different version of torch

### ISSUE THREAD

**Issue by zhengxiawu** [pytorch/pytorch#39560]
## ❓ I tested the NASNet on cifar10 with the different torch versions. Surprisingly, 1.0.1.post2 has the highest performance, what is the difference of 1.0.1.post2 with other versions (PS: I also tested other architectures and have a similar result)

The detailed experiments are listed as follows:

| Version   | Acc. | training time <br> (hours)|
| -         | :-:  | :----------------------:  |
| 1.5.0     | 97.02| 31.43                     |
| 1.0.1     | 96.79| 32.7025                   |
|1.0.1.post2| 97.11| 40.8297                   |
| 1.1.0     | 96.86| 42.3611                   |
| 1.2.0     | 96.79| 40.7019                   |
| 1.3.0     | 96.86| 34.0188                   |
| 1.3.1     | 96.69| 41.6177                   |
| 1.4.0     | 97.02| 34.2972                   |

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by ptrblck** [comment]
Double post from the [forum](https://discuss.pytorch.org/t/different-cifar10-performance-on-different-version-of-torch/84265/2?u=ptrblck).
Pasting my comment from there:

> How many runs did you try and how large are the standard deviation and mean values for these versions? Single runs between different versions might not be bitwise accurate due to changes in the libs (CUDA, cudnn) as well as the PyTorch backend.
