### ISSUE TITLE
Quickstart Guide: CUDA only possible with building from source

### ISSUE THREAD

**Issue by lukasfolle** [pytorch/pytorch#39578]
## 📚 Documentation

In the getting started section [this](https://pytorch.org/get-started/locally/#linux-from-source) section the following quote appears:

> You will also need to build from source if you want CUDA support.

I guess this is from previous versions where CUDA support was not built-in and this can be removed, correct?

cc @ezyang @gchanan @zou3519 @jlin27

**Comment by VitalyFedyunin** [comment]
This seems to be easy fixable docs issue

**Comment by lufol** [comment]
If https://github.com/pytorch/pytorch.github.io/pull/391 gets merged this is fixed.

**Comment by brianjo** [comment]
Thanks for the PR @lukasfolle. Just merged it.
