### ISSUE TITLE
INTERNAL ASSERT FAILED during torch.onnx.export

### ISSUE THREAD

**Issue by ag14774** [pytorch/pytorch#39575]
## To Reproduce

```
import torch
import torch.nn as nn
import torch.jit
import torch.onnx

@torch.jit.script
def check_init(input_data, hidden_size, prev_state):
    # type: (torch.Tensor, int, torch.Tensor) -> torch.Tensor
    batch_size = input_data.size(0)
    spatial_size_0 = input_data.size(2)
    spatial_size_1 = input_data.size(3)
    # generate empty prev_state, if None is provided
    state_size = (2, batch_size, hidden_size ,spatial_size_0, spatial_size_1)
    state = torch.zeros(state_size, device=input_data.device)
    if prev_state.size(0) != 0:
        state[:] = prev_state
    return state

class Example(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        self.hidden_size = hidden_size

    def forward(self, input_data, prev_state):
        prev_state = check_init(input_data, self.hidden_size, prev_state)
        return prev_state

random_data = torch.rand((1,5,30,30))
empty_tensor = torch.tensor([], dtype=torch.float).view(0,0,0,0,0)
traced_module = torch.jit.trace(Example(10), (random_data, empty_tensor,))
outputs = list(traced_module(random_data, empty_tensor))

torch.onnx.export(traced_module,
                  (random_data, empty_tensor),
                  "test.onnx",
                  example_outputs=outputs,
                  opset_version=11,
                  do_constant_folding=True,
                  input_names=['input_data', 'prev_state'],
                  output_names=['state'],
                  dynamic_axes={
                                'prev_state': {0: 'state_num', 1: 'batch_size', 2:'hidden_dim', 3: 'height', 4: 'width'},
                                'state': {1: 'batch_size', 3: 'height', 4: 'width'},
                              }, verbose=True)
```
Error message:
```
Traceback (most recent call last):
  File "minimum_bug.py", line 33, in <module>
    torch.onnx.export(traced_module,
  File "/home/envs/test/lib/python3.8/site-packages/torch/onnx/__init__.py", line 163, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/envs/test/lib/python3.8/site-packages/torch/onnx/utils.py", line 63, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/envs/test/lib/python3.8/site-packages/torch/onnx/utils.py", line 483, in _export
    graph, params_dict, torch_out = _model_to_graph(model, args, verbose,
  File "/home/envs/test/lib/python3.8/site-packages/torch/onnx/utils.py", line 349, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/envs/test/lib/python3.8/site-packages/torch/onnx/utils.py", line 125, in _optimize_graph
    torch._C._jit_pass_lint(graph)
RuntimeError: 0 INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/ir/ir.cpp:511, please report a bug to PyTorch. 40 not in scope
```

## Expected behavior

I would expect to output something or at least provide a more meaningful error message

## Environment

PyTorch version: 1.5.0+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Manjaro Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.17.2

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.5.0+cpu
[pip3] torchvision==0.6.0+cpu
[conda] Could not collect

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
This seems like an IR related issue showing in the JIT pass. @eellison @suo could you please take a first look?

**Comment by eellison** [comment]
Confirmed this repo's and fails at the lint pass. When I comment out the ONNX pass right before `_jit_pass_onnx_prepare_inplace_ops_for_onnx`, this no longer fails lint, so I think this is an issue in `_jit_pass_onnx_prepare_inplace_ops_for_onnx`.

**Comment by BowenBao** [comment]
Took a look, can confirm the issue is coming from `_jit_pass_onnx_prepare_inplace_ops_for_onnx`. The root cause seems to be that the outer `If` node emitted empty output. This is due to inplace `aten::copy_` emitted for code `state[:] = prev_state`, and inplace op outputs are not part of subblock outputs. 

Any suggestions @eellison ? Would it be a good idea utilizing aliasDb and adding to `if` output anything that is both updated in the sub-block and aliased from the outside?
```
  %state.1 : Tensor = aten::zeros(%15, %6, %6, %21, %6)
  %18 : bool = aten::ne(%17, %7)
   = prim::If(%18)
    block0():
      %19 : Tensor = aten::slice(%state.1, %7, %7, %5, %10)
      %20 : Tensor = aten::copy_(%19, %prev_state, %4)
      -> ()
    block1():
      -> ()
```

**Comment by eellison** [comment]
@BowenBao yea, something with the alias db could help here. I think we should consider consolidating around [this pass](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/create_functional_graphs.cpp#L453) then try to maintain two semantically valid passes to remove mutation. Also, I think it would be okay if ONNX through an error on parts of the model it didn't know how to rewrite and asked the user to rewrite functionally.

**Comment by Riccorl** [comment]
I have a similar issue, any update you can share?

**Comment by BowenBao** [comment]
This should be resolved under latest master.

One small thing to point out that in code, example_outputs should be passed in like `example_outputs = traced_module(random_data, empty_tensor)` instead of `example_outputs = list(traced_module(random_data, empty_tensor))`. The list bracket confuses the exporter for expecting sequence model output.

**Comment by thiagocrepaldi** [comment]
This repro has been successfully exported and numerically matched pytorch numbers when compared to ort's inferencesession api
