### ISSUE TITLE
extracting location of >1d patch within a tensor

### ISSUE THREAD

**Issue by vainaijr** [pytorch/pytorch#39574]
## 🚀 Feature

if I have a tensor like,
```
a = torch.tensor([[1., 0., 1.], 
                  [0., 1., 0.],
                  [1., 0., 1.]])
```
and I want to extract location of a 1d patch, then I do it using torch.where, that is,

```
torch.where(a == 1)
```
gives,
```
(tensor([0, 0, 1, 2, 2]), tensor([0, 2, 1, 0, 2]))
```
but if I want to extract location of a 2d patch, then there be no way to do it, for example,
```
a.unfold(0, 2, 1).unfold(1, 2, 1)
```
gives
```
tensor([[[[1., 0.],
          [0., 1.]],

         [[0., 1.],
          [1., 0.]]],


        [[[0., 1.],
          [1., 0.]],

         [[1., 0.],
          [0., 1.]]]])
```
now, if I want to know the location of the patch,
```
[[1., 0.],
  [0., 1.]]
```
in the original tensor, this location could be location of all four pixels, or only the border pixels, (for 2x2 patch, all pixels are border, but if our original tensor was 5x5, and we extracted 3x3 patch, then middle pixel would not be border), then I stuck.

that is something like,
```
torch.where(a == [[1., 0.],
                               [0., 1.]])
```
which would return
```
tensor([0, 0], [0, 1], [1, 0], [1, 1])
tensor([1, 1], [1, 2], [2, 1], [2, 2])
```

## Motivation
extracting location information from tensor enable to compare it with neighbor element

## Alternative

please inform me how to achieve this

**Comment by VitalyFedyunin** [comment]
Might take a lot of memory, but

```
a = torch.Tensor([[0, 2, 1, 0, 6, 7],
				  [1, 0, 1, 2, 5, 6],
				  [0, 2, 1, 1, 2, 1],
				  [1, 0, 1, 0, 0, 1],
				 ])
b = torch.Tensor([[2, 1],
		              [0, 1]])
H, W = a.shape
h, w = b.shape
snapshots = (H-h)*W+(W-w)+1
z = a.clone().as_strided_((snapshots,h,w),(1,W,1))
e = z.eq(b).as_strided((snapshots, h*w), (h*w, 1))
ee = e.cumprod(1).as_strided((snapshots,),(h*w,),h*w-1).clone()
where = ee.as_strided((H-h+1,W-w+1),(W,1))
as_coordinates = where.nonzero()
```

**Comment by vainaijr** [comment]
hello, thanks for your reply, I check it out.
