### ISSUE TITLE
What is the difference between 0.4.1 and 0.4.1.post2?

### ISSUE THREAD

**Issue by Lucksong** [pytorch/pytorch#39573]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, but feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
