### ISSUE TITLE
10% performance regression on CuDNN convolution dispatch path

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#3958]
This PR https://github.com/pytorch/pytorch/pull/3666 introduces a 10% performance regression on the CuDNN convolution dispatch path. There is no single smoking gun, but it needs to be as fast as the old CuDNN code was. I spent this morning trying to fix it to no avail, so this is to remind me to fix it before next release.

cc @csarofeen @ptrblck

**Comment by ezyang** [comment]
@SsnL Were you using group convolution on CuDNN 6? I can believe that this would have increased GPU memory. All the other cases should not have been affected, so if it is happening I need to investigate that too.

**Comment by ezyang** [comment]
(Is it this one? https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix )

**Comment by SsnL** [comment]
Yeah that's the one :) related: #3610

**Comment by csarofeen** [comment]
@ezyang I can no longer run batch 128 across 2 GPUs with resnet 50. I don't know if it was the cuDNN/aten re-write but will look into it.

**Comment by csarofeen** [comment]
Opened a new issue for this https://github.com/pytorch/pytorch/issues/4081
