### ISSUE TITLE
Weak symbols are resolved to the AVX version even on non-AVX machine

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#39600]
Follow-up of discussion at https://github.com/pytorch/pytorch/issues/39123#issuecomment-639525506

The problem is, for any symbol that is used both in and outside `ATen/native/cpu`, there will be many versions of weak symbols generated, and some of them are optimized by the compiler with AVX enabled. There is no guarantee which of these weak symbols will be used, and there are possibilities that, on a machine without AVX, the AVX version are picked.

One solution might be to split the `libtorch_cpu.so` further into `libtorch.so` and `libtorch_avx.so`, and only export symbols when necessary. But there might be circular dependencies issues.

Another solution suggested by @colesbury is to link AVX/AVX2 object files last so that symbols from the rest of libtorch are preferred.

cc: @colesbury @ezyang 

cc @ezyang @gchanan @zou3519 @malfet @VitalyFedyunin

**Comment by tedyu** [comment]
There is typo in the subject of this issue.
Can you fix the typo ?

Thanks

**Comment by zasdfgbnm** [comment]
🤣
@tedyu fixed thanks for pointing it out!

**Comment by VitalyFedyunin** [comment]
Boosting priority as this issue reappears in different forms at least on monthly basis

**Comment by VitalyFedyunin** [comment]
We all agree that it should be or weak symbols check or moving everything to a separate lib.

**Comment by Baranowski** [comment]
In case anyone else struggles to understand the problem like I did, I found this article http://gudok.xyz/inline/ to be an excellent explanation (the _When inlining fails [C]_ section can be skipped).

**Comment by Baranowski** [comment]
I suspect increasing the minimum required version of CMake from 3.5 to 3.6 (and also bumping accordingly the version used in CI) is not very tenable? If we need to stick to 3.5, I will have to implement list filtering manually, instead of using the new `list(FILTER ...)` syntax. It's not much of a burden, I just wanted to check before adding complexity to the draft linked above.

**Comment by ezyang** [comment]
cmake version is usually related to what Linux distro LTS ship by default.
