### ISSUE TITLE
Multinomial sampling without replacements is slow

### ISSUE THREAD

**Issue by Randl** [pytorch/pytorch#39624]
## 🚀 Feature
Add a faster implementation of multinomial sampling.

## Motivation
As for now, sampling without replacements is very slow because the code runs in `O(n*m)` and is sequential: https://github.com/pytorch/pytorch/blob/c9a1fc2b31ded472c63b227ad24859bc14131f42/aten/src/ATen/native/cpu/MultinomialKernel.cpp#L105-L127.

## Pitch

There exists a faster way to sample from multinomial distribution without replacements: https://stackoverflow.com/a/20548895/1894478

python code is pretty simple:
```python
def WeightedSelectionWithoutReplacement(weights, m):
    elt = [(math.log(random.random()) / weights[i], i) for i in range(len(weights))]
    return [x[1] for x in heapq.nlargest(m, elt)]
```
which runs in `O(n+mlogm)` with possible parallelization to `O(n)` part.

cc @VitalyFedyunin @ngimel

**Comment by Randl** [comment]
Related tensorflow issue https://github.com/tensorflow/tensorflow/issues/9260

**Comment by VitalyFedyunin** [comment]
This is not highest priority for us, but we will gladly accept PR which implements fast path.

**Comment by ngimel** [comment]
Yeah, this was first proposed in https://github.com/pytorch/pytorch/issues/11931.
