### ISSUE TITLE
masked_fill_ (and possibly others) produces a different output than masked_fill on cpu

### ISSUE THREAD

**Issue by stanleyts** [pytorch/pytorch#39639]
## Issue description

`masked_fill_` produces an output different from its out-of-place counterpart on cpu.

## To Reproduce
`masked_fill_` on cpu:
```python
tensor_cpu = torch.LongTensor([[0], [1]]).expand(2, 4)
mask_cpu = torch.BoolTensor(
    [[False,  True, False, False],
     [False, False, False, False]]
    )
tensor_cpu.masked_fill_(mask_cpu, 3)
print(tensor_cpu)
```
Output:
```
tensor([[3, 3, 3, 3],
        [1, 1, 1, 1]])
```
Notice that the first row of the output tensor is filled with 3 instead of only the second item in this row as specified by `mask_cpu`.

## Expected Behavior
One would expect `masked_fill_` and `masked_fill` to produce the same output on cpu and gpu.

`masked_fill` on cpu:
```python
tensor_cpu = torch.LongTensor([[0], [1]]).expand(2, 4)
masked_tensor_cpu = tensor_cpu.masked_fill(mask_cpu, 3)
print(masked_tensor_cpu)
```
Output:
```
tensor([[0, 3, 0, 0],
        [1, 1, 1, 1]])
```

The expected behavior is also produced by `masked_fill_` and `masked_fill` on gpu:
```python
tensor_cuda = torch.LongTensor([[0], [1]]).expand(2, 4).to('cuda')
mask_cuda = torch.BoolTensor(
    [[False,  True, False, False],
     [False, False, False, False]]
    ).to('cuda')
masked_tensor_cuda = tensor_cuda.masked_fill(mask_cuda, 3)
print(masked_tensor_cuda)                   # out-of-place version
tensor_cuda.masked_fill_(mask_cuda, 3)
print(tensor_cuda)                          # in-place version
```
Output:
```
tensor([[0, 3, 0, 0],
        [1, 1, 1, 1]], device='cuda:0')
tensor([[0, 3, 0, 0],
        [1, 1, 1, 1]], device='cuda:0')
```

## Possible Source
I'm guessing this has something to do with `expand` while initializing `tensor_cpu`. If I do not use `expand`, I get the expected behavior from `masked_fill_` on cpu:
```python
other_cpu = torch.LongTensor(
    [[0, 0, 0, 0],
     [1, 1, 1, 1]]
    )
print(other_cpu.masked_fill_(mask_cpu, 3))
```
Output:
```
tensor([[0, 3, 0, 0],
        [1, 1, 1, 1]])
```

## System Info
Here's the output of your `collect_env.py` script:
```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 840M
Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.5.0
[pip] torchtext==0.6.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0  
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchtext                 0.6.0                      py_1    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch
```

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
You are trying to do an inplace operation on a self-overlapping tensor that results from `expand`. This is not going to work. Results on the GPU are different because when you are copying tensor to the GPU it becomes contiguous and not self-overlapping. The only thing we can do here is issue a warning or disallow inplace masked_fill on a self-overlapping tensor.

**Comment by stanleyts** [comment]
Thanks for the clarification @ngimel. Out of curiosity, I tried moving the tensor to gpu before expanding:
```python
tensor_cuda = torch.LongTensor([[0], [1]]).to('cuda').expand(2, 4)
tensor_cuda.masked_fill_(mask_cuda, 3)
print(tensor_cuda)
```
Output:
```
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1]], device='cuda:0')
```
This is different from the cpu version where the first row was filled with 3. For consistency, would it make sense to have both of these (cpu & gpu versions) to produce the same output?


> The only thing we can do here is issue a warning or disallow inplace masked_fill on a self-overlapping tensor.

Yes, having one of these would be nice. It would help prevent bugs from silently creeping into models. I just found that this warning is already mentioned in the documentation for `expand`. But it would be helpful having it displayed at runtime (or as you mentioned, disallowing `masked_fill_` on a self-overlapping tensor altogether). Should I close this issue?

**Comment by ngimel** [comment]
The output on gpu is expected to be different from the output on the cpu because there's no guarantees for the order in which writes happen for the same memory location in this case. 
Please leave the issue open until we disallow these operations.

**Comment by ngimel** [comment]
Setting high priority as this is a silent error. We should audit inplace operations and disallow inplace operations on broadcasted tensors the way we do for pointwise currently.

**Comment by peterbell10** [comment]
After gh-43423, the `masked_fill_` call now gives a deprecation warning. Most `TensorIterator` operators now check for memory overlap as well.
