### ISSUE TITLE
jit result fails when __call__ is used instead of forward

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#39633]
## 🐛 Bug

I have been crawling GitHub to find common things people write that don't work in TorchScript.  Putting code in `__call__` (instead of `forward`) happens at least once in around 1% of the projects I looked at.  This pattern works in eager, but fails in TorchScript -- and worse, the failure happens when you run the model not when you `jit.script()` it.

This is easy to workaround, so low priority, but could be annoying for users.

## To Reproduce

Code:
```
import torch


class Example(torch.nn.Module):
    def __call__(self, input):
        return torch.nn.functional.relu(input)


# Runs through jit.script() fine:
module = torch.jit.script(Example())

# But throws an error when used:
module(torch.zeros(8))
```

Output:
```
$ python call_not_forward.py
Traceback (most recent call last):
  File "call_not_forward.py", line 13, in <module>
    module(torch.zeros(8))
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 577, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jansel/pytorch/torch/jit/__init__.py", line 1846, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/home/jansel/pytorch/torch/jit/__init__.py", line 1624, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/home/jansel/pytorch/torch/nn/modules/module.py", line 620, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'forward'
```

## Expected behavior

`torch.jit.script()` should either handle this, or throw an error earlier at compile time, not runtime.

cc @suo

**Comment by kaiyaointel** [comment]
@jansel Hi Jason, Could you share some experiences on what kinds of jit.script failure cases is out there? I'm also looking to collect some jit.script failure cases because it seems like there's a lot of categories... Would you happen to have a summarization on this? Thanks a lot for your time

**Comment by jansel** [comment]
@kaiyaointel,

The source code I used to crawl github and find errors is here:
https://github.com/jansel/pytorch-jit-paritybench

I haven't touched it since 2020, but it should be easy to get setup and generate a updated list of TorchScript errors.

**Comment by kaiyaointel** [comment]
@jansel  Thank you so much. That seems a very useful tool! 😊😊
