### ISSUE TITLE
init_num_threads() is not a member of 'torch on libtorch cpu Windows machine

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [pytorch/pytorch#39650]
I try to use libtorch cpu version on windows10. 

When i try to used below code, it gives "'init_num_threads': is not a member of 'torch'" .  However, i know that init_num_threads() function can be used. What is the problem here?

    torch::init_num_threads();
	torch::Tensor img_tensor = torch::from_blob(frameInRGB.data, { 1, frameInRGB.rows, frameInRGB.cols, 3 }, torch::kByte);
	img_tensor = img_tensor.permute({ 0, 3, 1, 2 }); // convert to CxHxW
	img_tensor = img_tensor.to(torch::kFloat);

	std::vector<torch::jit::IValue> inputs;

**Comment by peterjc123** [comment]
Have you included the headers in LibTorch?
