### ISSUE TITLE
Add custom request headers to torch.hub.download_url_to_file

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#39657]
## 🚀 Feature

Add the ability to specify request headers for `torch.hub.download_url_to_file`.

## Motivation

Some download servers (such as the one I'm using) refuse a connection if no `User-Agent` is set. Thus, I can't use `torch.hub.download_url_to_file`, since it internally uses plain `urlopen`:

https://github.com/pytorch/pytorch/blob/820e81ba09df46ed89f803f587b53a220a8a4757/torch/hub.py#L376-L379

## Pitch

Instead of calling `urlopen(url)` we could create a customized request first and open that:

```python
from urllib.request import Request, urlopen

def download_url_to_file(url, ..., **headers):
    ...

    req = Request(url, headers=headers)
    u = urlopen(req)

    ...
```

With that the user could customize the request headers if it is needed. 

## Alternatives

AFAIK most servers that refuse a connection due to a missing `User-Agent` do not care about the value. Thus for my purpose it is enough to do

```python
from urllib.request import Request, urlopen

def download_url_to_file(...):
    ...

    req = Request(url, headers={"User-Agent": "torch.hub"})
    u = urlopen(req)

    ...
```

cc @ailzhang

**Comment by ailzhang** [comment]
Hi @pmeier, we'll happily accept a PR that adding `headers={}` to `download_url_to_file` API. Would you mind sending a PR for it? Please feel free to request me as reviewer there. Thanks!
