### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] For Inception Resnet V2 on Google Colab

### ISSUE THREAD

**Issue by hot9cups** [pytorch/pytorch#39654]
I'm trying to use pretrained model from torchvision and receiving urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>
I have the issue while trying to download Inception resnet V2

I'm running my code on **Google Colab**
To reproduce the error, here's the code
```
!pip install pretrainedmodels
!pip install efficientnet-pytorch
from pretrainedmodels.models.inceptionresnetv2 import inceptionresnetv2
model_transfer = inceptionresnetv2(pretrained='imagenet')
```

The following was the output:
![image](https://user-images.githubusercontent.com/32614018/84025583-783c3400-a9a9-11ea-8188-34da1fdb4970.png)

But, when I set pretrained = False, no error is reported and everything works fine.
However, that is not what I desire since I want to use the pretrained weights.

How do I solve this?
(There have been a couple of issues in the past reported with the same error, however they were closed stating the error had been resolved)

**Comment by pbelevich** [comment]
PyTorch has nothing to do with this, it's pretrained-models's hosting issue, maybe [this one](https://github.com/Cadene/pretrained-models.pytorch/issues/193). The workaround mentioned in the comments works btw

**Comment by hot9cups** [comment]
Thank you, that does indeed provide a workaround, albeit not a very clean one. But I'm curious, why does this happen?
