### ISSUE TITLE
[proposal] Fuse mm+add for inputs > 2D

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#39661]
F.linear goes down to `addmm` for 2d tensors and to `matmul + add_` for other cases: https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L1672-L1679

HuggingFace instead do `view + addmm + view` for 3d tensors: https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_utils.py#L1740-L1743

I propose to fuse `mm + add_` for >= 3d tensors as well, for a minor optimization (saving one kernel launch per linear layer usage and maybe slightly more precise operation). Maybe automatic batching (view into 2d and then view back) can be moved into `addmm`, so that user does not have to do that.

If support of >= 3d tensors goes into addmm, it would be good if it didn't force contiguousness of first dimensions, as long as channels_last is satisfied (e.g. reshape may force an unnecessary copy if first few dimensions are reshuffled, but channels are list the last contig dim) - more context in https://github.com/pytorch/pytorch/issues/28090. So probably instead of a simple reshape, a smart permute sorting by stride is needed (then reshape would not copy).

cc @VitalyFedyunin @ngimel @ezyang

**Comment by vadimkantorov** [comment]
Maybe there is already some version of batched mmadd that would handle broadcasting: https://github.com/pytorch/pytorch/pull/40927#issuecomment-653801918

**Comment by ngimel** [comment]
There won't be kernel launches saved. What happens under the hood in addmm is bias is first materialized as contiguous non-broadcasted tensor (1st kernel launch), and then gemm with beta=1 is called (another kernel launch), so, as the comment says, optimization is marginal, if it exists at all. `matmul` api from cublasLt on cuda 10+ provides truly fused bias addition iirc, but matmul is not integrated into pytorch, it had some problems in the beginning, I don't know if it's ready for use now. 
cc @ptrblck for comment on `matmul`

**Comment by vadimkantorov** [comment]
The way I stumbled on this is that I observed some differences between HuggingFace linear and core Linear, and the difference was matmul+add_ vs addmm. But maybe there are other correlated factors like different inner blocking used...

**Comment by ngimel** [comment]
Small numerical difference is real, perf difference would be very surprising. 
Changing addmm api to accept more than 2d tensors is confusing, "matrix" is 2d. Should we have addtt?

**Comment by vadimkantorov** [comment]
Also ~4different apis for addbmm/baddbmm kind of ops is a lot. I wonder if we can come up with a better api. Maybe better extend matmul with an optional bias? Or introduce a new matmul_add? Matmul already does batched multiplies iirc

**Comment by ptrblck** [comment]
Re: cublasLt fused matmul + bias:
Our internal tests show the fused matmul + bias calls are faster and are using indeed the fused kernel, which is great.
However the end to end time is often not reduced and we are trying to narrow down the issue.
At the moment we suspect the additional CPU overhead from the caching or heuristics might be the reason, but need to investigate more. In the current state it's not usable yet and we'll update this issue with more information.

**Comment by vadimkantorov** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/74070
