### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by utpalh** [pytorch/pytorch#39679]
## 🐛 Bug

I try to install as the  website description 

https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support
 but got the following error. How can i solve it?

## To Reproduce

#git clone https://github.com/pytorch/pytorch.git
# git submodule update --init --recursive
# python setup.py install

Building wheel torch-1.6.0a0+8251f18
-- Building version 1.6.0a0+8251f18
cmake --build . --target install --config Release -- -j 8
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/mnt/f/tool/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/mnt/f/tool/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/mnt/f/tool/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.0

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
## Additional context

i downloaded and build cuda and cudnn. dont know why it is not showing

**Comment by pbelevich** [comment]
That site says that it was deprecated 2 years ago, please consider using [pytorch.org](https://pytorch.org/get-started/locally/) and [github.com/pytorch](https://github.com/pytorch/pytorch#from-source)
