### ISSUE TITLE
Autograd custom functions with trainable variable

### ISSUE THREAD

**Issue by minhson** [pytorch/pytorch#39704]
Hello,
Could you show me how i can make autograd custom function with trainable variable?

Thanks you in advance!

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your particular question, this is not possible.
Custom Functions are just stateless functions.
You most likely want to build an nn.Module that builds around your Function that will hold the Parameter and all the required states.
