### ISSUE TITLE
[distributed] [nccl] should check whether reduceop is supported

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#39708]
Currently the input `ReduceOp` goes through a map to become `ncclRedOp_t`, e.g.,
https://github.com/pytorch/pytorch/blob/0251ba61089795a7a27c0473e4bb022805432c1f/torch/lib/c10d/ProcessGroupNCCL.cpp#L718

However, this doesn't check whether `opts.reduceOp` is supported or not, i.e., whether it is in the map or not. When `opts.reduceOp` is not in the map, the `[]` syntax will create an entry instead, using the default ctor of `ncclRedOp_t`, i.e., getting `ncclSum`!

This causes correctness issues ***silently***!!!!

The maps should be marked const, and checking code should be added.

```py
import torch
torch.distributed.init_process_group('nccl', init_method='tcp://localhost:10402', world_size=2, rank=0)
x = torch.zeros(3, device=0).fill_(2.4)
torch.distributed.reduce(x, 0, torch.distributed.ReduceOp.BXOR)
print(x)
# tensor([4.8000, 4.8000, 4.8000], device='cuda:0')
```

```py
import torch
torch.distributed.init_process_group('nccl', init_method='tcp://localhost:10402', world_size=2, rank=1)
x = torch.zeros(3, device=1).fill_(2.4)
torch.distributed.reduce(x, 0, torch.distributed.ReduceOp.BXOR)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by rohan-varma** [comment]
Fixed by #42669
