### ISSUE TITLE
undefined reference to torch::jit::load

### ISSUE THREAD

**Issue by DuongNo** [pytorch/pytorch#39718]
Hi all

I'm trying to build a  c++ in QT use qmake that loads a model from a file by libtorch on ubuntu machine. 
but get error

```
undefined reference to torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```
my config 
```
TEMPLATE = app
CONFIG += console c++14
CONFIG -= app_bundle
CONFIG -= qt
CONFIG += no_keywords
SOURCES += main.cpp

QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0
INCLUDEPATH = libtorch-shared-with-deps-1.5.0/libtorch
INCLUDEPATH += libtorch-shared-with-deps-1.5.0/libtorch/include
INCLUDEPATH += libtorch-cxx11-abi-shared-with-deps-1.5.0/libtorch/include/torch/csrc/api/include
LIBS = -L$$libtorch-cxx11-abi-shared-with-deps-1.5.0/libtorch/lib
LIBS += -ltorch -lc10
```
I hope anyone can help me, Thank you!

cc @suo

**Comment by eellison** [comment]
cc @voznesenskym, serialization issue, maybe the old `torch::jit::load` got removed, we should probably have it call into `torch::load` to not break BC

**Comment by DuongNo** [comment]
@eellison  thank for your help but     ` torch::jit::load`   is correct
problem is config libtorch, i can run it on cmake but can not run on qmake
my program build in QT and need add model make by pytorch to project

**Comment by DuongNo** [comment]
i was fixed by change -ltorch to -ltorch_cpu
