### ISSUE TITLE
import Error, Any Suggestions? 

### ISSUE THREAD

**Issue by munavircp** [pytorch/pytorch#39723]
## To Reproduce

1.I Have followed All the details in documentation of installation procedure still  Shows Error

-- Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\**\**\**\**\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\**\**\**\**\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

 - PyTorch Version (e.g., 1.0):Latest
 - OS (e.g., Linux):Windows
 - How you installed PyTorch (`conda`, `pip`, source): Both(Conda And Pip)
 - Build command you used (if compiling from source): 
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Intel HD
 - Any other relevant information:

cc @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
First, make sure you have GPU and its driver properly installed. Second, you can patch `__init__.py` with [this](https://gist.github.com/peterjc123/bcbf4418ff63d88e11313d308cf1b427) version.

**Comment by peterjc123** [comment]
> * CUDA/cuDNN version: 10.2
> * GPU models and configuration: Intel HD

So you don't have Nvidia GPU, right? Please use the CPU version instead.

**Comment by mszhanyi** [comment]
No user inputs for 2 months. close it
@munavircp If you still have this issue, feel free to reopen it.
