### ISSUE TITLE
FileNotFoundError when importing on Windows 10 2004

### ISSUE THREAD

**Issue by gan-lin** [pytorch/pytorch#39734]
## 🐛 Bug

On Windows 10 2004, `import torch` will result in a FileNotFoundError.

## To Reproduce

1. Install Python from Windows store.
1. Disable Windows path length limit.
1. Install PyTorch CPU version from pip according to [the tutorial](https://pytorch.org/get-started).
1. run `import torch` in Python.

Error message: (Sorry for lacking of accurate error message, because I'm afraid to corrupt my system to reproduce it, see below.)
`FileNotFoundError: Could not find module '...\c10.dll' (or one of its dependencies)`

## Expected behavior

Import succeed and no error.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0+cpu
 - OS (e.g., Linux): Windows 10 2004
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.8.3
 - CUDA/cuDNN version: No (CPU version)
 - GPU models and configuration:
 - Any other relevant information: Python is installed from Windows Store

## Additional context

I used Dependency Walker to check c10.dll and found it depends on msvcp140.dll which is missing. So I installed [Visual C++ redistributable 2017](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) and the problem disappeared. Maybe this package is removed from system by default since Windows 10 2004. I think this is the problem, and this dependency needs to be mentioned for Windows 10 2004 users.

cc @peterjc123 @nbcsm @guyang3532

**Comment by malfet** [comment]
I think this is already documented in https://pytorch.org/docs/stable/notes/windows.html#import-error:
> Actually, we include almost all the essential files that PyTorch need for the conda package except VC2017 redistributable and some mkl libraries.

**Comment by gan-lin** [comment]
Sorry for ignoring it. The issue can be closed now.

**Comment by peterjc123** [comment]
But for better user experience, I think we should improve by providing some better message.

**Comment by peterjc123** [comment]
Or we could just package the VC Redist into the binary. @malfet @ezyang What do you think?

**Comment by peterjc123** [comment]
These are available options:
1. For non-conda environments
a. We could add a windows only dependecy `msvc_runtime` which contains all the runtime DLLs.
b. Add a runtime check. If vc redist is not installed, then we ask them to do `pip install msvc_runtime`.
2. For conda environments
a. Create a vs2019_runtime package in the pytorch channel and make pytorch depend on it.
b. Copy all the DLLs to our local library directory.
c. Add a runtime check. If vc redist is not installed, then we ask them to do `pip install msvc_runtime`.

**Comment by peterjc123** [comment]
@ezyang Well, the redist files are small (<1M) so I guess it's okay to be packaged into our binary. But I'll do what you say first.

**Comment by ezyang** [comment]
Oh, that's a lot smaller than I expected (am I thinking of some other redistributable? I had the impression that it was quite large).
