### ISSUE TITLE
Misleading documentation for weighted NLL Loss

### ISSUE THREAD

**Issue by czhang96** [pytorch/pytorch#3973]
Current documentation does not suggest that class weight effects how the average is computed, ie, weight is also in the denominator when the average is computed.

For example, the current documentation would make it seem like setting weight=0 would still include those observations in the average. In reality, it has the same effect as setting ignore_index.

**Comment by SsnL** [comment]
working on it

**Comment by SsnL** [comment]
It's easy to fix the doc... but if the weights are really in the denominator, then it isn't **size**_average anymore. What should we do about this? @soumith

**Comment by vishwakftw** [comment]
I believe this can be closed now. @soumith
