### ISSUE TITLE
CrossEntropyLoss or NLLLoss does not check values of the target ?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/pytorch#39769]
## 🐛 Bug
Given a task of `N`-classification, if some value of the target is larger than `N`, then it also works,
and the loss sometimes turns out negative.

## To Reproduce
```python
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
# target = torch.tensor([1, 0, 4])
target = torch.tensor([1, 0, 5])
output = loss(m(input), target)
output.backward()
```

 - PyTorch Version (e.g., 1.5):
 - OS (e.g., Linux):

**Comment by wangtingwei1993** [comment]
@Naruto-Sasuke  @ngimel 
It seems that the same thing happens to me. I test the code on both CPU side and GPU side.
1. CPU side works correctly: 
Line `output = loss(m(input), target)` raises an error: `IndexError: Target 5 is out of bounds.` I think this is what we want.

2. GPU side fails to detect the error label id:
Implementation: `(1) input.cuda() & target.cuda(); (2) input.to(torcvh.device('cuda')) & target.to(torch.device('cuda'))`
Line `output = loss(m(input), target)` is executed sucessfully. 
In addition, I do not see any negative output.

**Comment by ngimel** [comment]
If you are on pytorch 1.5 please update to 1.5.1. There was a bug in 1.5 that could result in this behavior.

**Comment by wangtingwei1993** [comment]
@ngimel That is the pytorch version I use. Thanks a lot for your kind reply!

**Comment by ngimel** [comment]
Closing, please reopen if updating to 1.5.1 does not fix it.
