### ISSUE TITLE
Cannot build pytorch 1.6.0 from source

### ISSUE THREAD

**Issue by Bueryoung** [pytorch/pytorch#39776]
Type command: python setup.py build
Building wheel torch-1.6.0a0+8a6914d
-- Building version 1.6.0a0+8a6914d
cmake -GVisual Studio 16 2019 -Ax64 -Tversion=0,host=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR=Visual Studio 16 2019 -DCMAKE_GENERATOR_TOOLSET_VERSION=0 -DCMAKE_INSTALL_PREFIX=D:\fhyProgram\pytorch\pytorch_source\torch -DCMAKE_PREFIX_PATH=D:\fhyProgram\anaconda\installed\Lib\site-packages -DNUMPY_INCLUDE_DIR=D:\fhyProgram\anaconda\installed\lib\site-packages\numpy\core\include -DPYTHON_EXECUTABLE=D:\fhyProgram\anaconda\installed\python.exe -DPYTHON_INCLUDE_DIR=D:\fhyProgram\anaconda\installed\include -DPYTHON_LIBRARY=D:\fhyProgram\anaconda\installed/libs/python36.lib -DTORCH_BUILD_VERSION=1.6.0a0+8a6914d -DUSE_NINJA=OFF -DUSE_NUMPY=True D:\fhyProgram\pytorch\pytorch_source
CMake Error: Error: generator toolset: version=0,host=x64
Does not match the toolset used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\setup_helpers\cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\fhyProgram\anaconda\installed\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GVisual Studio 16 2019', '-Ax64', '-Tversion=0,host=x64', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 16 2019', '-DCMAKE_GENERATOR_TOOLSET_VERSION=0', '-DCMAKE_INSTALL_PREFIX=D:\\fhyProgram\\pytorch\\pytorch_source\\torch', '-DCMAKE_PREFIX_PATH=D:\\fhyProgram\\anaconda\\installed\\Lib\\site-packages', '-DNUMPY_INCLUDE_DIR=D:\\fhyProgram\\anaconda\\installed\\lib\\site-packages\\numpy\\core\\include', '-DPYTHON_EXECUTABLE=D:\\fhyProgram\\anaconda\\installed\\python.exe', '-DPYTHON_INCLUDE_DIR=D:\\fhyProgram\\anaconda\\installed\\include', '-DPYTHON_LIBRARY=D:\\fhyProgram\\anaconda\\installed/libs/python36.lib', '-DTORCH_BUILD_VERSION=1.6.0a0+8a6914d', '-DUSE_NINJA=OFF', '-DUSE_NUMPY=True', 'D:\\fhyProgram\\pytorch\\pytorch_source']' returned non-zero exit status 1.

My configuration is:
(1) set USE_NINJA=OFF
(2) set CMAKE_GENERATOR=Visual Studio 16 2019
(3) set CMAKE_GENERATOR_TOOLSET_VERSION=14.24**(i am not sure CMAKE_GENERATOR_TOOLSET_VERSION value from my pc)**
(4)for /f "usebackq tokens=*" %i in ("%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%

When I run "python setup.py build", I get the error from above.
P.S: I use Windows7. There is nothing in the build folder.
Thx in advance

cc @malfet @peterjc123 @nbcsm @guyang3532

**Comment by Bueryoung** [comment]
@peterjc123  
Could you pls take a look and make some suggestion?

**Comment by peterjc123** [comment]
First, you could get the path of your VS installation using `"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath`. (e.g. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community`) Then you could list all the available toolchains by changing your directory to `VC\Tools\MSVC`. For example, `dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\"`, 
```
 Volume in drive C has no label.
 Volume Serial Number is C87A-331E

 Directory of C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC

2020/05/29  15:45    <DIR>          .
2020/05/29  15:45    <DIR>          ..
2020/05/29  15:46    <DIR>          14.26.28801
               0 File(s)              0 bytes
               3 Dir(s)  62,453,141,504 bytes free

```
And finally just omit the revision version number, so in my example, it should be `14.26`.

**Comment by Bueryoung** [comment]
Some supplement:
vs2019 is installed in D:\fhySoftware\VS2019Com\installed, and splited into (1)D:\fhySoftware\VS2019Com\installed\DownloadCache  
(2)D:\fhySoftware\VS2019Com\installed\SharedSDK  
(3)D:\fhySoftware\VS2019Com\installed\VSIDE  
In the mean time, once installer has launched, C:\Program Files (x86)\Microsoft Visual Studio\Installer directory will be created(or updated), and new setup.exe, vs installer.exe, vs_installershell.exe inside will shown.
1. Type command:  
C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -version [16^, 17^] -products * latest -property D:/fhySoftware/VS2019Com/installed
Log:  
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.6.2109.55756]
Copyright (C) Microsoft Corporation. All rights reserved.
Error 0x57: Argument expected  
2.Tools\MSVC could be find in D:\fhySoftware\VS2019Com\installed\VSIDE\VC\Tools\MSVC, two folder is list, 14.16.27023 and 14.26.28801 respectively.  
Is that mean the command should be "set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
" rather than 14.24?
But i have tried to set it to 14.26, still error like above, and just 14.24 of log was replaced to 14.26.
[logAfterSet CMAKE_GENERATOR_TOOLSET_VERSION=14.26.txt](https://github.com/pytorch/pytorch/files/4761832/logAfterSet.CMAKE_GENERATOR_TOOLSET_VERSION.14.26.txt)

**Comment by Bueryoung** [comment]
Thx for ur  reply.
Some supplement:
vs2019 is installed in D:\fhySoftware\VS2019Com\installed, and splited into (1)D:\fhySoftware\VS2019Com\installed\DownloadCache
(2)D:\fhySoftware\VS2019Com\installed\SharedSDK
(3)D:\fhySoftware\VS2019Com\installed\VSIDE
In the mean time, once installer has launched, C:\Program Files (x86)\Microsoft Visual Studio\Installer directory will be created(or updated), and new setup.exe, vs installer.exe, vs_installershell.exe inside will shown.

Type command:
C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -version [16^, 17^] -products * latest -property D:/fhySoftware/VS2019Com/installed
Log:
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.6.2109.55756]
Copyright (C) Microsoft Corporation. All rights reserved.
Error 0x57: Argument expected
2.Tools\MSVC could be find in D:\fhySoftware\VS2019Com\installed\VSIDE\VC\Tools\MSVC, two folder is list, 14.16.27023 and 14.26.28801 respectively.
Is that mean the command should be "set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
" rather than 14.24?
But i have tried to set it to 14.26, still error like above, and just 14.24 of log was replaced to 14.26.

**Comment by Bueryoung** [comment]
@peterjc123 
Thx for ur reply.
Some supplement:
vs2019 is installed in D:\fhySoftware\VS2019Com\installed, and splited into (1)D:\fhySoftware\VS2019Com\installed\DownloadCache
(2)D:\fhySoftware\VS2019Com\installed\SharedSDK
(3)D:\fhySoftware\VS2019Com\installed\VSIDE
In the mean time, once installer has launched, C:\Program Files (x86)\Microsoft Visual Studio\Installer directory will be created(or updated), and new setup.exe, vs installer.exe, vs_installershell.exe inside will shown.

Type command:
C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -version [16^, 17^] -products * latest -property D:/fhySoftware/VS2019Com/installed
Log:
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.6.2109.55756]
Copyright (C) Microsoft Corporation. All rights reserved.
Error 0x57: Argument expected
2.Tools\MSVC could be find in D:\fhySoftware\VS2019Com\installed\VSIDE\VC\Tools\MSVC, two folder is list, 14.16.27023 and 14.26.28801 respectively.
Is that mean the command should be "set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
" rather than 14.24?
But i have tried to set it to 14.26, still error like above, and just 14.24 of log was replaced to 14.26.
[logAfterSet CMAKE_GENERATOR_TOOLSET_VERSION=14.26.txt](https://github.com/pytorch/pytorch/files/4761846/logAfterSet.CMAKE_GENERATOR_TOOLSET_VERSION.14.26.txt)

**Comment by peterjc123** [comment]
Please try the following commands.
```
set USE_NINJA=OFF
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
call D:\fhySoftware\VS2019Com\installed\VSIDE\VC\Auxiliary\Build\vcvarsall.bat x64 -vcvars_ver=14.26
python setup.py install --cmake
```

**Comment by Bueryoung** [comment]
reinstall vs2019 to C disk
`λ call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvarsall.bat" x64 -vcvars_ver=14.26`
_**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.2
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'_

λ python setup.py install -cmake
Building wheel torch-1.6.0a0+8a6914d
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option -m not recognized

**Comment by peterjc123** [comment]
It should be two hyphens before cmake.

**Comment by Bueryoung** [comment]
Still like above.
`λ python setup.py install --cmake`
Building wheel torch-1.6.0a0+8a6914d
-- Building version 1.6.0a0+8a6914d
cmake -GVisual Studio 16 2019 -Ax64 -Tversion=14.26,host=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR=Visual Studio 16 2019 -DCMAKE_GENERATOR_TOOLSET_VERSION=14.26 -DCMAKE_INSTALL_PREFIX=D:\fhyProgram\pytorch\pytorch_source\torch -DCMAKE_PREFIX_PATH=D:\fhyProgram\anaconda\installed\Lib\site-packages -DNUMPY_INCLUDE_DIR=D:\fhyProgram\anaconda\installed\lib\site-packages\numpy\core\include -DPYTHON_EXECUTABLE=D:\fhyProgram\anaconda\installed\python.exe -DPYTHON_INCLUDE_DIR=D:\fhyProgram\anaconda\installed\include -DPYTHON_LIBRARY=D:\fhyProgram\anaconda\installed/libs/python36.lib -DTORCH_BUILD_VERSION=1.6.0a0+8a6914d -DUSE_NINJA=OFF -DUSE_NUMPY=True D:\fhyProgram\pytorch\pytorch_source
CMake Error: Error: generator toolset: version=14.26,host=x64
Does not match the toolset used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\setup_helpers\cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "D:\fhyProgram\pytorch\pytorch_source\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\fhyProgram\anaconda\installed\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GVisual Studio 16 2019', '-Ax64', '-Tversion=14.26,host=x64', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 16 2019', '-DCMAKE_GENERATOR_TOOLSET_VERSION=14.26', '-DCMAKE_INSTALL_PREFIX=D:\\fhyProgram\\pytorch\\pytorch_source\\torch', '-DCMAKE_PREFIX_PATH=D:\\fhyProgram\\anaconda\\installed\\Lib\\site-packages', '-DNUMPY_INCLUDE_DIR=D:\\fhyProgram\\anaconda\\installed\\lib\\site-packages\\numpy\\core\\include', '-DPYTHON_EXECUTABLE=D:\\fhyProgram\\anaconda\\installed\\python.exe', '-DPYTHON_INCLUDE_DIR=D:\\fhyProgram\\anaconda\\installed\\include', '-DPYTHON_LIBRARY=D:\\fhyProgram\\anaconda\\installed/libs/python36.lib', '-DTORCH_BUILD_VERSION=1.6.0a0+8a6914d', '-DUSE_NINJA=OFF', '-DUSE_NUMPY=True', 'D:\\fhyProgram\\pytorch\\pytorch_source']' returned non-zero exit status 1.

**Comment by peterjc123** [comment]
Would you please remove `D:\fhyProgram\pytorch\pytorch_source\build` and try again?

**Comment by peterjc123** [comment]
BTW, could you please tell me which version of CMake are you using?

**Comment by Bueryoung** [comment]
`D:\fhyProgram\pytorch\pytorch_source\build` is null, and was deleted, error again 
Cmake 3.17.3
config test with CMake3.17.3, delete cache and specify the generator for test project.
choose Visual Studio 16 2019 
Log in file 
[cmake3.17.3TestLog.txt](https://github.com/pytorch/pytorch/files/4762411/cmake3.17.3TestLog.txt)
![Image 2](https://user-images.githubusercontent.com/22030631/84341668-40fe9a80-abd6-11ea-8185-0d21781ec02b.jpg)

**Comment by peterjc123** [comment]
> `D:\fhyProgram\pytorch\pytorch_source\build` is null, and was deleted, error again
> Cmake 3.17.3
> config test with CMake3.17.3, delete cache and specify the generator for test project.
> choose Visual Studio 16 2019
> Log in file
> [cmake3.17.3TestLog.txt](https://github.com/pytorch/pytorch/files/4762411/cmake3.17.3TestLog.txt)
> ![Image 2](https://user-images.githubusercontent.com/22030631/84341668-40fe9a80-abd6-11ea-8185-0d21781ec02b.jpg)
> 
> ![Image 2](https://user-images.githubusercontent.com/22030631/84341713-5ffd2c80-abd6-11ea-98b9-8b146f7a21be.jpg)

Sorry, I don't understand your comment. Why do you use CMake GUI? The log you posted is about OpenCV. How is it related to this issue?

**Comment by Bueryoung** [comment]
i just wanna show u whether my CMake 3.17.3  work well with vs 16 2019 generator.

**Comment by Bueryoung** [comment]
so far, my question is just along with CMake, Visual Studion 2019 , 
Not related to CUDA, CUDANN, any CUDA** or GPU** those stuff, right?

**Comment by Bueryoung** [comment]
Any info u need, pls tell me, i will get that for u

**Comment by peterjc123** [comment]
I could not reproduce this error on my local PC. Actually I have VS 2019 and CMake 3.17 too. That's what I did in CMD.
```
set USE_NINJA=OFF
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
python setup.py build --cmake
```
BTW, is there any specific reason why you don't use Ninja? If not, then you can use `set USE_NINJA=ON`.

**Comment by Bueryoung** [comment]
No specific reason,  just got no idea about Ninja. Does Ninja is recommend than CMake?  
My visual studio 2019 and CMake must be messed up by myself. 
Things gonna changed.  
The reason why i build pytorch form source is my GPU is too old(cuda compute capability only 3.0 and not supported by pytorch of any version).
So now, i have update GPU to a better one with higher CUDA compute capacity.
In that case, i could use pytorch lib from pytorch.org like v1.2.0, v1.5.0 and torchvision accompanied.
Not solve the problem directly just choose the other method to make it worked.
Not sure whether "build from source" will be experienced again some day. If so, 
set USE_NINJA=ON
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.26
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
python setup.py build 
Hope this will work


Thx again for ur help.
BR : )

**Comment by peterjc123** [comment]
Glad that you figured it out yourself.
