### ISSUE TITLE
finetune model forward error

### ISSUE THREAD

**Issue by gjtjx** [pytorch/pytorch#3980]
I hava finetune the Nasnetalager model from imagenet,change the liner layer to 30
but when I forward the forward model ,the output is 1000
print(self.linear)
x = self.linear(x)
print(x)

Linear(in_features=4032, out_features=30)
Variable containing:
-0.3304  0.5077  1.0844  ...  -0.2731  0.0184 -0.2642
[torch.cuda.FloatTensor of size 1x1000 (GPU 0)]

why?

**Comment by soumith** [comment]
https://discuss.pytorch.org
