### ISSUE TITLE
Reduce the number of variations of `quantized::add`

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#39817]
There are many quantized::add APIs: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qadd.cpp#L253-L260

But we should reduce the numbers so that some of the functions can be reused.
Blocked by `quantized::add` support broadcasting.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by jerryzh168** [comment]
This would make supporting graph mode quantization much easier

**Comment by jerryzh168** [comment]
I tried https://github.com/pytorch/pytorch/pull/42769 but I feel it might be hard since original `add` is not postfixed with anything, and looks like the overloading is not recognized

**Comment by jerryzh168** [comment]
looks like it works, didn't compile correctly last time

**Comment by vkuzo** [comment]
for triage

**Comment by supriyar** [comment]
Should be addressed by  #42769
