### ISSUE TITLE
errors about custom build of PyTorch Android

### ISSUE THREAD

**Issue by KevinZ1992** [pytorch/pytorch#39845]
When i do custom build of PyTorch Android
`git clone https://github.com/pytorch/pytorch.git
cd pytorch
sh ./scripts/build_pytorch_android.sh`
I get error just like:
Build with ANDROID_ABI[armeabi-v7a with NEON], ANDROID_NATIVE_API_LEVEL[21]
Bash: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Caffe2 path: /home/zhangxiaojian/pytorch
Using Android NDK at /home/zhangxiaojian/android_profile/android-ndk-r16b
Android NDK version: 16
CMake Warning at /home/zhangxiaojian/android_profile/android-ndk-r16b/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  /home/zhangxiaojian/android_profile/android-ndk-r16b
Call Stack (most recent call first):
  build_android/CMakeFiles/3.17.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:23 (project)

-- std::exception_ptr is supported.
-- Turning off deprecation warning due to glog.
-- Trying to find preferred BLAS backend of choice: Eigen
CMake Error at cmake/Dependencies.cmake:291 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/pthreadpool

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:311 (add_subdirectory):
  The binary directory

    /home/zhangxiaojian/pytorch/build_android/confu-deps/pthreadpool

  is already used to build a source directory.  It cannot be used to build
  source directory

    /home/zhangxiaojian/pytorch/third_party/pthreadpool

  Specify a unique binary directory name.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:345 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/cpuinfo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:350 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:304 (add_subdirectory):
  add_subdirectory given source
  "/home/zhangxiaojian/pytorch/third_party/cpuinfo/deps/clog" which is not an
  existing directory.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:308 (set_property):
  set_property could not find TARGET clog.  Perhaps it has not yet been
  created.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:326 (add_subdirectory):
  The binary directory

    /home/zhangxiaojian/pytorch/build_android/confu-deps/cpuinfo

  is already used to build a source directory.  It cannot be used to build
  source directory

    /home/zhangxiaojian/pytorch/third_party/cpuinfo

  Specify a unique binary directory name.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:336 (add_subdirectory):
  The binary directory

    /home/zhangxiaojian/pytorch/build_android/confu-deps/pthreadpool

  is already used to build a source directory.  It cannot be used to build
  source directory

    /home/zhangxiaojian/pytorch/third_party/pthreadpool

  Specify a unique binary directory name.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:362 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/FXdiv

  does not contain a CMakeLists.txt file.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:377 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/psimd

  does not contain a CMakeLists.txt file.

CMake Error at aten/src/ATen/native/quantized/cpu/qnnpack/CMakeLists.txt:394 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/FP16

  does not contain a CMakeLists.txt file.

CMake Error at cmake/Dependencies.cmake:407 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:409 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

-- Brace yourself, we are building NNPACK
CMake Error at cmake/External/nnpack.cmake:68 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/NNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:417 (include)
  CMakeLists.txt:461 (include)

CMake Error at cmake/External/nnpack.cmake:73 (set_property):
  set_property could not find TARGET nnpack.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:417 (include)
  CMakeLists.txt:461 (include)

CMake Error at cmake/External/nnpack.cmake:74 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:417 (include)
  CMakeLists.txt:461 (include)

CMake Error at cmake/External/nnpack.cmake:75 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:417 (include)
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:448 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/XNNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:452 (set_property):
  set_property could not find TARGET XNNPACK.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:461 (target_compile_definitions):
  Cannot specify compile definitions for target "XNNPACK" which is not built
  by this project.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Warning at cmake/Dependencies.cmake:645 (message):
  Turning USE_FAKELOWP off as it depends on USE_FBGEMM.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:775 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/FP16

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

-- Using third party subdirectory Eigen.
-- Using third_party/pybind11.
-- pybind11 include dirs: /home/zhangxiaojian/pytorch/cmake/../third_party/pybind11/include
CMake Error at cmake/Dependencies.cmake:1678 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/fmt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

CMake Error at cmake/Dependencies.cmake:1687 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  fmt-header-only
Call Stack (most recent call first):
  CMakeLists.txt:461 (include)

-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR)
-- don't use NUMA
disabling CUDA because USE_CUDA is set false
AT_INSTALL_INCLUDE_DIR include/ATen/core
core header install: /home/zhangxiaojian/pytorch/build_android/aten/src/ATen/core/TensorBody.h
CMake Error at caffe2/CMakeLists.txt:67 (add_subdirectory):
  The source directory

    /home/zhangxiaojian/pytorch/third_party/FXdiv

  does not contain a CMakeLists.txt file.

-- /home/zhangxiaojian/android_profile/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ /home/zhangxiaojian/pytorch/caffe2/../torch/abi-check.cpp -o /home/zhangxiaojian/pytorch/build_android/abi-check
/home/zhangxiaojian/pytorch/caffe2/../torch/abi-check.cpp:1:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
CMake Error at caffe2/CMakeLists.txt:730 (message):
  Could not compile ABI Check: 1

-- Configuring incomplete, errors occurred!
See also "/home/zhangxiaojian/pytorch/build_android/CMakeFiles/CMakeOutput.log".
See also "/home/zhangxiaojian/pytorch/build_android/CMakeFiles/CMakeError.log".

Thx in advance

cc @malfet

**Comment by malfet** [comment]
`add_subdirectory` failures  happened  because you have not checked out  sub-modules.
Please issue `git clone --recursive https://github.com/pytorch/pytorch` as recommended in https://github.com/pytorch/pytorch/#get-the-pytorch-source to check-out pytorch repository with its dependencies
