### ISSUE TITLE
NaN handling in cuda nn.MaxPool3d

### ISSUE THREAD

**Issue by turtleizzy** [pytorch/pytorch#39846]
## 🐛 Bug

NaN becomes a negative float after nn.MaxPool3d

## To Reproduce

```
import numpy as np
import torch

mp = torch.nn.MaxPool3d(kernel_size=2, stride=2, dilation=1)
empty = torch.tensor([np.nan]*(4**3)).reshape([1, 1, 4, 4, 4]).cuda()
print (mp(empty))

# tensor([[[[[-3.4028e+38, -3.4028e+38],
#            [-3.4028e+38, -3.4028e+38]],

#           [[-3.4028e+38, -3.4028e+38],
#            [-3.4028e+38, -3.4028e+38]]]]], device='cuda:0')
```

## Expected behavior

```
tensor([[[[nan, nan],
          [nan, nan]]]], device='cuda:0')
```

## Environment

PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 435.21
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.18.2
[pip] torch==1.5.0+cu101
[pip] torchcontrib==0.0.2
[conda] numpy                     1.18.2                   pypi_0    pypi
[conda] torch                     1.5.0+cu101              pypi_0    pypi
[conda] torchcontrib              0.0.2                    pypi_0    pypi

## Additional context

nn.MaxPool2d and cpu version of nn.MaxPool3d works fine.

cc @albanD @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @turtleizzy. We would appreciate a PR fixing this!
