### ISSUE TITLE
"Found no NVIDIA driver on your system."

### ISSUE THREAD

**Issue by baobabKoodaa** [pytorch/pytorch#3989]
I'm trying to set up pyTorch on Ubuntu 16.04. I installed pyTorch with the "get started" instructions for Linux, pip, Python 2.7, CUDA 8.0. I updated my NVIDIA drivers to version 384.98, but I'm still getting this error. I also tried to install CUDA separately, but that didn't help either. How can I get pyTorch running on this system?

**Comment by albanD** [comment]
Hi,
I assume you have a nvidia gpu on your machine right?
Which version of CUDA did you installed?
Are you able to run the cuda samples from nvidia that come with the cuda install?

**Comment by baobabKoodaa** [comment]
Hi, thanks for responding. I hava a NVIDIA GPU and I am able to run cuda samples.
CUDA version: 9.0
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.98  Thu Oct 26 15:16:01 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

**Comment by albanD** [comment]
Humm, not sure then :/
Then something must be preventing the python process from accessing the nvidia driver? Do you get a full stack trace please?

**Comment by baobabKoodaa** [comment]
I tried to install a different version with a different package manager and it looks like it works now. Thanks!

**Comment by albanD** [comment]
Perfect !
