### ISSUE TITLE
Why does Libtorch use more memory than Pytorch does in Python？

### ISSUE THREAD

**Issue by qingfengmingyue** [pytorch/pytorch#39927]
Why does Libtorch use more memory than Pytorch does in Python？ Such as:ESRGAN

**Comment by agolynski** [comment]
Could you give more details as to how you use ESRGAN? What OS, which memory CPU/GPU, how you measure? It's hard to diagnose the issue as stated.

**Comment by agolynski** [comment]
Could you update this with more details and reopen when done?

**Comment by qingfengmingyue** [comment]
> Could you give more details as to how you use ESRGAN? What OS, which memory CPU/GPU, how you measure? It's hard to diagnose the issue as stated.

ubuntu18.04 ，Directly predict in two ways, on the 2080TI libtorch can only predict 200X200, and the other can predict 800X800
