### ISSUE TITLE
How to deploy C++ LibTorch in Windows XP 32bit? 

### ISSUE THREAD

**Issue by SakuraRiven** [pytorch/pytorch#39936]
I want to deploy a CNN model in Windows XP 32 bit, and here are my operations:

compile LibTorch-1.4.0 32bit with VS2017;
finish the C++11 code and the .exe run successfully in win10 and win7 32bit;
The code fails in XP which reports “MSVCP140.dll is invalid”.
I want to use VS2015_XP to compile and avoid the error in XP. However, the LibTorch uses C++11/14 which is not supported by VS2015. So, what should I do to run successfully in XP 32bit? 

Need help! TAT

**Comment by peterjc123** [comment]
https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=vs-2019 It seems there's `vs141_xp` toolchain. Could you please try that?

**Comment by SakuraRiven** [comment]
Hi, thanks for your reply. My VS2017 is a community version and there is no "C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]" as you recommend vs141_xp toolchain. Should I use the Enterprise or Professional？

**Comment by peterjc123** [comment]
Maybe you could try. I haven't tried that before so it's hard to say.

**Comment by peterjc123** [comment]
Well, I could find `Windows XP support for C++` with a VS2017 Enterprise installation.

**Comment by SakuraRiven** [comment]
Thank you for your help!~ I am installing the Enterprise version~~ :)

**Comment by SakuraRiven** [comment]
I have tried the `v141_xp` toolset but it still can not work in XP : (

Actually, it needs several dll and I have added these into current path. The last error is `Unable to locate program input point`...

Maybe XP is indeed too old...

**Comment by agolynski** [comment]
just linking discussion here: https://discuss.pytorch.org/t/how-to-deploy-c-libtorch-in-windows-xp-32bit/85170

resolution is that XP is unsupported.
