### ISSUE TITLE
How to resolve this issue in pycharm?  ERROR: Could not find a version that satisfies the requirement torch>=1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) I have installed through command promt but still it is showing same issue as before.

### ISSUE THREAD

**Issue by RizwanShaukat936** [pytorch/pytorch#39939]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment]
Either you are using a 32-bit of Python or you are using a Python version that we haven't added support (e.g. 3.9).
