### ISSUE TITLE
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#39968]
I am seeing an error

```
caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/torch_cuda_generated_THCStorage.cu.o: in function `__device_stub__ZN6thrust8cuda_cub4core13_kernel_agentINS0_14__parallel_for16ParallelForAgentINS0_6__fill7functorINS_10device_ptrIN3c107complexIdEEEESA_EElEESC_lEEvT0_T1_(thrust::cuda_cub::__fill::functor<thrust::device_ptr<c10::complex<double> >, c10::complex<double> >&, long)':
/home/gaoxiang/cuda11/include/cuda_runtime.h:209:(.text+0x7d4): additional relocation overflows omitted from the output
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
when building with CUDA11 on my archlinux box.

There was no problem with the combination CUDA 10.2 + my archlinux, and CUDA11 + NVIDIA's NGC container.

After searching, seems that it is due to the code size being too large (see [code model](https://eli.thegreenplace.net/2012/01/03/understanding-the-x64-code-models), thank @mcarilli for pointing out the issue), and MXNet had the same issue: https://github.com/apache/incubator-mxnet/issues/17045

The cause of this problem could be because we are generating code for too many architectures by default:

```
--     CUDA include path   : /home/gaoxiang/cuda11/include
--     NVCC executable     : /home/gaoxiang/cuda11/bin/nvcc
--     NVCC flags          : -DONNX_NAMESPACE=onnx_torch;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75;-Xcudafe;--diag_suppress=cc_clobber_ignored;-Xcudafe;--diag_suppress=integer_sign_change;-Xcudafe;--diag_suppress=useless_using_declaration;-Xcudafe;--diag_suppress=set_but_not_used;-Xcudafe;--diag_suppress=field_without_dll_interface;-Xcudafe;--diag_suppress=base_class_has_different_dll_interface;-Xcudafe;--diag_suppress=dll_interface_conflict_none_assumed;-Xcudafe;--diag_suppress=dll_interface_conflict_dllexport_assumed;-Xcudafe;--diag_suppress=implicit_return_from_non_void_function;-Xcudafe;--diag_suppress=unsigned_compare_with_zero;-Xcudafe;--diag_suppress=declared_but_not_referenced;-Xcudafe;--diag_suppress=bad_friend_decl;-std=c++14;-Xcompiler;-fPIC;--expt-relaxed-constexpr;--expt-extended-lambda;-Wno-deprecated-gpu-targets;--expt-extended-lambda;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75;-Xcompiler;-fPIC;-DCUDA_HAS_FP16=1;-D__CUDA_NO_HALF_OPERATORS__;-D__CUDA_NO_HALF_CONVERSIONS__;-D__CUDA_NO_HALF2_OPERATORS__
--     CUDA host compiler  : /usr/bin/gcc-8
--     NVCC --device-c     : OFF
--     USE_TENSORRT        : OFF
```

I am wondering if it is possible to add `-mcmodel=medium` during linking (tried for a few hours, didn't figure out how).

cc @ezyang @gchanan @zou3519 @malfet @ngimel

**Comment by mcarilli** [comment]
Does `-mcmodel=medium|large` need to be present at compile time as well as link time?  Different instructions need to be baked in.

**Comment by zasdfgbnm** [comment]
I don't think the compiler has a `-mcmodel`, at least nvcc doesn't.

**Comment by mcarilli** [comment]
You'd need to pass it to the underlying host compiler via [`nvcc --compiler-options`](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-passing-specific-phase-options-compiler-options) , I believe.

**Comment by mcarilli** [comment]
As a temporary workaround, I discovered if you're building on a system that already has a nccl .so, using system nccl instead of compiling and statically linking pytorch's nccl subrepo drives down the binary size enough to link successfully.
```
 CUDA_HOME="/usr/local/cuda"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     NCCL_INCLUDE_DIR="/usr/include/"     NCCL_LIB_DIR="/usr/lib/"     USE_SYSTEM_NCCL=1     USE_OPENCV=0 python setup.py develop
```

(thanks to @ptrblck for this suggestion)

**Comment by zasdfgbnm** [comment]
I get a standalone repro of this at https://github.com/zasdfgbnm/cuda-linking-experiment, will experiment with my standalone repro

**Comment by zasdfgbnm** [comment]
One potential solution could be https://github.com/zasdfgbnm/cuda-linking-experiment/pull/2

**Comment by xkszltl** [comment]
Hit the same issue a while ago (no we haven't figured out any working solution) when moving to CUDA 11.
We build shared lib with debuginfo (-O3 -g) for only Pascal+Volta:
https://github.com/xkszltl/Roaster/blob/13b6301c0ab41cfcc98c68ca6e988bf3733b0cb6/pkgs/pytorch.sh#L91-L130

**Comment by peijason** [comment]
Issue ongoing today here... 


```console
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o: in function `_init':
(.init+0xb): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o: in function `at::native::cudnn_affine_grid_generator_forward(at::Tensor const&, long, long, long, long)':
AffineGridGenerator.cpp:(.text+0x6c): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x294): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x2b8): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x4f0): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
AffineGridGenerator.cpp:(.text+0x6c3): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o: in function `at::native::cudnn_affine_grid_generator_backward(at::Tensor const&, long, long, long, long)':
AffineGridGenerator.cpp:(.text+0x999): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `c10::UndefinedTensorImpl::_singleton' defined in .bss section in ../lib/libc10.so
CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o: in function `c10::Error::~Error()':
AffineGridGenerator.cpp:(.text._ZN3c105ErrorD2Ev[_ZN3c105ErrorD5Ev]+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for c10::Error' defined in .data.rel.ro._ZTVN3c105ErrorE[_ZTVN3c105ErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o: in function `at::native::cudnn_affine_grid_generator_forward(at::Tensor const&, long, long, long, long) [clone .cold]':
AffineGridGenerator.cpp:(.text.unlikely+0x283): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `typeinfo for c10::Error' defined in .data.rel.ro._ZTIN3c105ErrorE[_ZTIN3c105ErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
AffineGridGenerator.cpp:(.text.unlikely+0x4c1): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `typeinfo for c10::Error' defined in .data.rel.ro._ZTIN3c105ErrorE[_ZTIN3c105ErrorE] section in CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o
AffineGridGenerator.cpp:(.text.unlikely+0x662): additional relocation overflows omitted from the output
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/build.make:278142: lib/libtorch_cuda.so] Error 1
make[2]: Leaving directory '/mnt/data/jiapei/ml/dl/pytorch/pytorch/build'
make[1]: *** [CMakeFiles/Makefile2:4332: caffe2/CMakeFiles/torch_cuda.dir/all] Error 2
make[1]: Leaving directory '/mnt/data/jiapei/ml/dl/pytorch/pytorch/build'
make: *** [Makefile:163: all] Error 2

****  Installation failed. Aborting package creation.

Restoring overwritten files from backup... FAILED!

Cleaning up...OK

Bye.
```

**Comment by ptrblck** [comment]
Could you try https://github.com/pytorch/pytorch/pull/43074 as a potential workaround?

**Comment by janeyx99** [comment]
I'm not sure this is the right place to post this, but when trying to enable CUDA 11.1 nightly binaries, I get the same error. A CI run with this failure is here: https://app.circleci.com/pipelines/github/pytorch/pytorch/239814/workflows/2dd7d5fc-c75f-46ab-903a-cf4886177e36/jobs/8972288

@zasdfgbnm's change is committed in the repo so is there something else I should try?

**Comment by xkszltl** [comment]
@janeyx99 
See if you can build with only one or a few cuda arch.
As more and more arch released, fatbin is becoming too fat.

You can also see this trend of obesity here:
https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/
<img width="876" alt="image" src="https://user-images.githubusercontent.com/5203025/99312356-dfcfa700-2898-11eb-8c35-8299ea9cdfce.png">

**Comment by zasdfgbnm** [comment]
Reopen because this is not resolved yet

**Comment by zasdfgbnm** [comment]
@janeyx99 Unfortunately this is a limitation of the host compiler, so there is really nothing PyTorch or CUDA can do. The only way to workaround is to manually set `TORCH_CUDA_ARCH_LIST`  to build on only a few architectures.

**Comment by malfet** [comment]
We can try to hint to the linker how we want those sections to be ordered (puting cubins sections in front of the code section might solve the problem)

**Comment by nelson-liu** [comment]
Does anyone have a sense of whether this issue is being actively worked on? It's a bit disappointing that these limits prevent building recent pytorch binaries that support a wide range of `TORCH_CUDA_ARCH_LIST`.

From trawling github and the pytorch discuss forum, I think I saw somewhere that @janeyx99 was planning on looking at this issue sometime---no worries if you haven't gotten to it, but any updates on your investigation would be great. It's hard for me to know how fundamental of a limitation this is, so any information helps. Thanks in advance!

**Comment by janeyx99** [comment]
@nelson-liu I am indeed still actively working on this issue by splitting up the torch_cuda library (#49050), which should help shrink the size of statically linked binaries. This is certainly a priority for us as we'd like to enable support for more platforms as well.

**Comment by nelson-liu** [comment]
Great, thanks so much for the update and pointer @janeyx99 !

**Comment by gemfield** [comment]
@xkszltl build pytorch with cuda11.1 failed on this issue too. 
And after reduce the TORCH_CUDA_ARCH_LIST number, the build can be successful.

**Comment by nelson-liu** [comment]
I saw that https://github.com/pytorch/pytorch/pull/49050 was merged, and that 1.8.0 provides CUDA 11.1 binaries. It'd be nice to get an update on this issue---is this still a problem? (gentle ping to @janeyx99 , thanks so much!)

**Comment by janeyx99** [comment]
Oh thank you @nelson-liu for the ping :) Yes, this should no longer be an issue when enabling the BUILD_SPLIT_CUDA option when compiling torch.

**Comment by nelson-liu** [comment]
Great! Can `BUILD_SPLIT_CUDA` be used on older versions of PyTorch, or is it only 1.8.0-forward? Thanks again for handling this issue!

**Comment by janeyx99** [comment]
Enabling BUILD_SPLIT_CUDA did incur CMake build configuration changes (among other code changes), so it won't work before that change.

**Comment by nelson-liu** [comment]
makes sense, thanks for the information!

**Comment by kgizdov** [comment]
This is still an issue on pytorch 1.9.0 and CUDA 11.3.1 for us at Arch Linux. None of the above mentioned workarounds have helped, unfortuantely.

**Comment by janeyx99** [comment]
> This is still an issue on pytorch 1.9.0 and CUDA 11.3.1 for us at Arch Linux. None of the above mentioned workarounds have helped, unfortunately.

Could I ask for specifics on the workarounds you tried? For example, when reducing your TORCH_CUDA_ARCH_LIST, what architectures remained in the list? When running BUILD_SPLIT_CUDA, where did the linker error occur?

**Comment by kgizdov** [comment]
The `TORCH_CUDA_ARCH_LIST` we used so far may have been too overarching:
```sh
export TORCH_CUDA_ARCH_LIST="5.2;5.3;6.0;6.1;6.2;7.0;7.0+PTX;7.2;7.2+PTX;7.5;7.5+PTX;8.0;8.0+PTX;8.6;8.6+PTX"
```
In any case, it seemed to work fine for pytorch 1.8.1. For 1.9.0, the error occurs at linking libtorch to cudart at final stages of compilation - a linking truncation occurs. If we supply only `BUILD_SPLIT_CUDA=ON` and don't truncated the `TORCH_CUDA_ARCH_LIST` variable, the is no difference. However, we managed to build successfully by supplying only cubin versions and no PTX:
```
export TORCH_CUDA_ARCH_LIST="5.2;5.3;6.0;6.1;6.2;7.0;7.2;7.5;8.0;8.6"
```
Do you think that may impact users in any way?

**Comment by xkszltl** [comment]
If you're targeting Maxwell+ Geforce/Tesla, they're sufficient.
Would be better if you can include at least one PTX for future compatibility.

**Comment by kgizdov** [comment]
We're targeting all non-deprecated arches. In case of future compatibility, what is the recommendation - always, go for latest available arch + PTX - 8.6+PTX; since all the others have cubin? Just trying to fully minimize the set of architectures.

**Comment by xkszltl** [comment]
> We're targeting all non-deprecated arches

You probably need to think about whether you need compatibility with low-end GeForce and Jetson.

> In case of future compatibility, what is the recommendation

Yes, as long as you're satisfied with your "since all the others have cubin" claim, i.e. whatever not listed doesn't really matter.
You may also reduce some cubin list to contain only the lowest version within the same generation if rarely used, or even use PTX instead, depending on whether you like faster start time or better optimization (e.g. reg alloc).

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#binary-compatibility

> In other words, a cubin object generated for compute capability X.y will only execute on devices of compute capability X.z where z≥y.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ptx-compatibility

> 3.1.3. PTX Compatibility
>
> Some PTX instructions are only supported on devices of higher compute capabilities.
> For example, Warp Shuffle Functions are only supported on devices of compute capability 3.0 and above.
> The -arch compiler option specifies the compute capability that is assumed when compiling C++ to PTX code.
> So, code that contains warp shuffle, for example, must be compiled with -arch=compute_30 (or higher).
>
> PTX code produced for some specific compute capability can always be compiled to binary code of greater or equal compute capability.
> Note that a binary compiled from an earlier PTX version may not make use of some hardware features.
> For example, a binary targeting devices of compute capability 7.0 (Volta) compiled from PTX generated for compute capability 6.0 (Pascal) will not make use of Tensor Core instructions, since these were not available on Pascal.
> As a result, the final binary may perform worse than would be possible if the binary were generated using the latest version of PTX.

**Comment by kgizdov** [comment]
> You may also reduce some cubin list to contain only the lowest version within the same generation if rarely used, or even use PTX instead, depending on whether you like faster start time or better optimization (e.g. reg alloc).

Interesting. So, if I understand correctly, cubin is compiled in general for any device say with 6.1 capability and may not optimise as well as 6.1+PTX at runtime, given the PTX version will take into account runtime device characteristics. Is that correct?
In that case, since 6.0, 7.0, 8.0 are essentially single-device specific, would this be a better and also more general option:
```sh
export TORCH_CUDA_ARCH_LIST="5.2+PTX;5.3+PTX;6.0;6.1+PTX;6.2+PTX;7.0;7.2+PTX;7.5+PTX;8.0;8.6+PTX"
```
*`5.2` is the lowest not yet deprecated arch in CUDA and we are aiming to support as many devices as possible.

**Comment by xkszltl** [comment]
> So, if I understand correctly, cubin is compiled in general for any device say with 6.1 capability and may not optimise as well as 6.1+PTX at runtime, given the PTX version will take into account runtime device characteristics. Is that correct?

No you didn't, it's the opposite.
PTX is just a more abstracted cubin.
- cubin will work for higher minor version, but may not take full advance of that hardware.
- Both PTX/cubin won't work across major version or for older minor version.
- PTX can run on higher version.
- PTX takes time to JIT into cubin when running.
- JIT may utilize hardware info for optimization, but may not be as good as offline nvcc for compilation latency.
- There's no chance for cubin to use extra hardware capability on higher minor version because there's no JIT.

**Comment by kgizdov** [comment]
I think maybe I did understand, maybe didn't phrase it well.
> - cubin will work for higher minor version, but may not take full advance of that hardware.
Yes, that's clear.
> - cubin won't work across major version or for older minor version.
Also, yes. That's why we keep 6.0, 7.0, 8.0 cubins, while 5.2 and 5.3 are PTX given they are minor versions. 5.2 might be better as cubin if we decide Maxwell Quadro is important.
> - PTX can run on higher version, won't work for older version.
That's clear too.
> - PTX takes time to JIT into cubin when running.
Yes, but only at first.
> - JIT may utilize hardware info for optimization, but may not be as good as offline nvcc for compilation latency.
This I don't understand. If you take into account actual hardware, you should end up with better code, which in the long run will end up faster. E.g. compiling for x86_64 is in general a bit slower than compiling for x86_64_v3 or native skylake. Compilation latency is only important for short ephemeral tasks, right? Why would you run those on dedicated GPUs?
> - There's no chance for cubin to use extra hardware capability on higher minor version because there's no JIT.
That's also clear.

What I was aiming is to use that fact that x.0 ones are normally the high-end single card in a generation and cubin version already has full device information at compile time, so PTX has no advantage. For minor versions (lower tier devices) it makes sense to keep PTX as lots of different hardware and possibly end up with better performance in the long run. Unless I am missing something else etirely.

**Comment by xkszltl** [comment]
> This I don't understand. If you take into account actual hardware, you should end up with better code, which in the long run will end up faster. E.g. compiling for x86_64 is in general a bit slower than compiling for x86_64_v3 or native skylake. Compilation latency is only important for short ephemeral tasks, right? Why would you run those on dedicated GPUs?

JIT is usually faster than offline compilation, in the price of less optimization.
The purpose of JIT is not to optimize code, but to convert IR into runnable machine code.

> What I was aiming is to use the fact that x.0 ones are normally the high-end single card in a generation

Not exactly, it's quite massy...

https://developer.nvidia.com/cuda-gpus

3.0/5.0 is for low-end cards.
3.7 is the best of Kepler.
7.5 is different from 7.0, although Tuning and Volta are not too different.

> and cubin version already has full device information at compile time, so PTX has no advantage.

A good example would be 3.7 has a few more registers than 3.5.

**Comment by kgizdov** [comment]
Ah, I thought JIT is better at optimising given it has runtime info. If that's the opposite then it's not really a problem. We provide all the cubins with one PTX for future. I think that's the safest and from what I understand the most optimised in performance. We won't be supporting deprecated arches, so we only need cubins for 5.2+. Thanks a lot for your help.

**Comment by xkszltl** [comment]
FYI, CUDA 11.4.2 added `--host-linker-script` that may help with this issue

> CUDA Compiler: Relocation models of GNU/Linux on many architectures, such as ARM AArch64 and AMD x86-64, have certain size limitations. While building a CUDA application or a shared library, if the device code crosses such size limitations, the host linker fails with a relocation truncation error.
A new option (--host-linker-script) under nvcc is provided to prepare a host linker script to enable the host linker support for relocatable device object files that are larger in size. Refer to nvcc --help or the CUDA Toolkit Documentation for more details.

https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
