### ISSUE TITLE
Docs of v0.3.0 lack torchvision reference and page of master docs does not contain version selector combo box .

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/pytorch#3997]
See [docs v0.3.0](http://pytorch.org/docs/0.3.0/) and [docs master](http://pytorch.org/docs/master/)

**Comment by soumith** [comment]
thanks for reporting. both are fixed now.

**Comment by vfdev-5** [comment]
@soumith [v0.3.1](http://pytorch.org/docs/0.3.1/) still lacks Torchvision

**Comment by JindongJiang** [comment]
That is true.
