### ISSUE TITLE
Torch.nn.utils.clip_grad.clip_grad_norm_ is too slow 

### ISSUE THREAD

**Issue by Viczyf** [pytorch/pytorch#39988]
https://discuss.pytorch.org/t/torch-nn-utils-clip-grad-clip-grad-norm-is-too-slow/85310

cc @albanD @mruberry @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Closing, as the issue on forums is withdrawn.

**Comment by GoingMyWay** [comment]
The same issue, can someone provide some clues?
