### ISSUE TITLE
Issue when importing Torch on Python 3.7.7 and Windows 10

### ISSUE THREAD

**Issue by chansts** [pytorch/pytorch#39980]
## 🐛 Bug
Hi team,

I am a novice to PyTorch. Currently I have installed Python 3.7.7 and download PyTorch following the instruction "pip install torch==1.5.0+cu92 torchvision==0.6.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html"

However, there seems to be a bug when trying to import Torch. (below). Appreciate your advice.

FYI my computer is using on Windows 10 Home version.

-------------

Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by peterjc123** [comment]
Several questions:
1. Do you have Nvidia GPU? If not, please uninstall torch and torchvision and install the cpu version instead.
2. Have you installed VS 2017 redist? If not, you could download the installer at https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by chansts** [comment]
Thanks very much for the useful advice. It s working fine now.
