### ISSUE TITLE
Save big file is slow

### ISSUE THREAD

**Issue by playma** [pytorch/pytorch#3999]
It spent a lot of time for I to save file by torch.save().

The file size is about 3.5G, and it costs 2hr 49m totally. Is it make sense?

**Comment by zou3519** [comment]
I replied to your post on the [forums](https://discuss.pytorch.org/t/using-torch-save-to-save-big-file-is-very-slow/10749/2), feel free to reply to them there or here. 

As an addenum, I tried running the following:
```
x = torch.zeros(3500000000//4)
torch.save(x, "tmp.txt")
```
and it runs in around 2 seconds for me (I am on an ssd, though).

**Comment by soumith** [comment]
lets keep the discusson on forums for this one.

**Comment by playma** [comment]
I have replied the discussion on the forums
