### ISSUE TITLE
ERROR: torchvision has requirement torch which is incompatible

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#40013]
```
~: python -m pip install --quiet --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html 

ERROR: torchvision 0.7.0.dev20200610 has requirement torch==1.6.0.dev20200609, but you'll have torch 1.6.0.dev20200610 which is incompatible.
```

cc @malfet @fmassa

**Comment by glaringlee** [comment]
@lutzroeder 
Can you try uninstall the pytorch first, and install torch vision again? I think it will install the correct version of pytorch for you.

**Comment by BE-Lau** [comment]
i have the same issues, uninstall and reinstall doesn't fix the issues

**Comment by BE-Lau** [comment]
works for now... found the stable version at https://pytorch.org/get-started/locally/
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch

**Comment by lutzroeder** [comment]
@glaringlee

```
~: pip uninstall torch torchvision
[...]
~: pip install --quiet --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html  
ERROR: torchvision 0.7.0.dev20200610 has requirement torch==1.6.0.dev20200609, but you'll have torch 1.6.0.dev20200610 which is incompatible.
```

**Comment by glaringlee** [comment]
@lutzroeder try this, it will install correct pytorch version automatically.
pip install --quiet --pre torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

**Comment by Abinaya-0106** [comment]
torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 1.0.0 which is incompatible.
torchtext 0.11.0 has requirement torch==1.10.0, but you'll have torch 1.0.0 which is incompatible.
torchaudio 0.10.0+cu111 has requirement torch==1.10.0, but you'll have torch 1.0.0 which is incompatible.
syft 0.2.9 has requirement torch~=1.4.0, but you'll have torch 1.0.0 which is incompatible.
opacus 1.1.0 has requirement torch>=1.8, but you'll have torch 1.0.0 which is incompatible.

**Comment by sabdha** [comment]
@Abinaya-0106 do you know which torch vision is compatible with torch1.10.0

**Comment by sangeetsu** [comment]
torchvision 0.11.0 has requirement torch==1.10.0+cu102, but you'll have torch 1.10.0 which is incompatible.
