### ISSUE TITLE
Implementing gcd, lcm

### ISSUE THREAD

**Issue by aayn** [pytorch/pytorch#40018]
From #38349.

cc @mruberry

**Comment by aayn** [comment]
Are there any resources on the top of your head that could be useful for this implementation? @mruberry

**Comment by mruberry** [comment]
You could look at how the functions are implemented in NumPy for inspiration, and how similar functions like add are implemented on CPU and CUDA. There are also papers on the topic, like this for GCD: http://www.iaeng.org/IJCS/issues_v42/issue_4/IJCS_42_4_01.pdf. LCM is also computable using the GCD, so you may want to start with GCD.

**Comment by aayn** [comment]
Thanks!

**Comment by aayn** [comment]
Starting from C++17, there are `std::gcd` and `std::lcm` functions under the `numeric` header. Is it okay to use those for the CPU scalar versions? Also, is `BinaryOps.cpp` the right place for gcd (and lcm) or would it be better to put them elsewhere?

@mruberry

**Comment by mruberry** [comment]
Putting it in BinaryOps.cpp is fine to start. You can't use C++17 features, sorry. PyTorch supports C++14.

**Comment by aayn** [comment]
What would I put as the derivatives of `gcm` and `lcm`? Just `grad` (letting the gradient pass through without change), or throwing an exception saying that it is undefined? :thinking: 

@mruberry

**Comment by mruberry** [comment]
@albanD, what would you recommend?

**Comment by albanD** [comment]
Hey,

If I'm not mistaken, these only work for integer types (IntTensor and LongTensor). And these cannot require gradients. So no need to worry about the autograd ;)

**Comment by aayn** [comment]
Oh yeah, thanks!
