### ISSUE TITLE
[caffe2] how can I get the shape of a matrix in the forward graph definition

### ISSUE THREAD

**Issue by banshee1** [pytorch/pytorch#40019]
Hi, I am new to caffe2 and now I have a problem:
I have:

a blob W1 of shape (N, C, H, W) that N is not fixed 
a blob W2 of shape (C, H, W). 

Now I want to tile the W2 (C, H, W) to (N, C, H, W). 
However, since N is not fixed, I may need to get the shape of (N, C, H, W) and pass N to the 'tile' operator.
But how could I get the shape of a blob in the forward code?
Please help me !

**Comment by banshee1** [comment]
Plz help me !!!!!!!!!!!!!!

**Comment by glaringlee** [comment]
@banshee1 
I suggest you to switch to pytorch.
caffe2 is deprecated, check here. https://caffe2.ai/

**Comment by mruberry** [comment]
Closing this issue since it's a question more appropriate to the PyTorch forums here: https://discuss.pytorch.org/.
