### ISSUE TITLE
The wrong output of  argmin and argmax when input tensor has dimension Nx1, N > 32767

### ISSUE THREAD

**Issue by zhyx12** [pytorch/pytorch#40022]
## 🐛 Bug

The wrong output of  argmin and argmax when input tensor has dimension Nx1, N > 32767
## To Reproduce

1. Normal case when N <=32767:
```
a = torch.randn((32767,1))
b = torch.argmin(a,dim=1)
torch.max(b)
```
The output is 0

2. Wrong case when N > 32767
```
a = torch.randn((32767,1))
b = torch.argmin(a,dim=1)
torch.max(b)
```
The output changes in different machines, but is larger than 0

## Expected behavior

Output is always 0.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[pip] warpctc-pytorch==0.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch
[conda] warpctc-pytorch           0.1                      pypi_0    pypi

**Comment by ngimel** [comment]
This is fixed on master, #38946
