### ISSUE TITLE
Overflow when binary shifting negative integer tensors stored on CPU

### ISSUE THREAD

**Issue by ValerianRey** [pytorch/pytorch#40032]
## 🐛 Bug

Overflow when binary shifting integer tensors stored on CPU

## To Reproduce

_in:_ torch.tensor(-2) >> 1
_out:_ tensor(9223372036854775807)

Note that when using cuda or when doing the operation with python integers, the result does not overflow like this and instead performs the expected integer division by a power of 2

_in:_ torch.tensor(-2, device='cuda') >> 1
_out:_ tensor(-1, device='cuda:0')

_in:_ -2 >> 1
_out:_ -1

## Expected behavior

The output of torch.tensor(-2) >> 1 should be -1. I understand that this is probably caused by the 2's complement way of storing signed integers, but the result should still be consistent with the cuda result and the python native result.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Famille
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.5.0
[pip] torchvision==0.6.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] numpy                     1.18.1           py37h93ca92e_0
[conda] numpy-base                1.18.1           py37hc3f5095_1
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.5.0           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.6.0                py37_cu102    pytorch

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
64 bits system, x64 cpu

cc @VitalyFedyunin @ngimel @mruberry @ezyang @SsnL @gchanan @zou3519

**Comment by glaringlee** [comment]
mark high priority since cpu and gpu have different behavior

**Comment by xwang233** [comment]
CPU and GPU results should be the same now in master. 

https://github.com/pytorch/pytorch/pull/35339 Might be related.  @xuhdev

**Comment by ngimel** [comment]
On master cpu and gpu have the same behavior (overflow), and it differs from python native and numpy.

**Comment by ValerianRey** [comment]
Is it possible to make both behave like python and numpy instead? It would be better in my opinion, and I don't really see the reason why not doing it.

**Comment by ngimel** [comment]
```
In [1]: import torch                                                                                                                                                                                       

In [2]: import numpy as np                                                                                                                                                                                 

In [3]: torch.tensor(-2) >> 1                                                                                                                                                                              
Out[3]: tensor(9223372036854775807)

In [4]: torch.tensor(-2, device='cuda') >> 1                                                                                                                                                               
Out[4]: tensor(9223372036854775807, device='cuda:0')

In [5]: -2 >> 1                                                                                                                                                                                            
Out[5]: -1

In [6]: np.right_shift(-2, 1)                                                                                                                                                                              
Out[6]: -1
```
C++ standard says `For negative a, the value of a >> b is implementation-defined (in most implementations, this performs arithmetic right shift, so that the result remains negative).`, starting from c++20 this behavior will be mandated, and not be implementation-defined. https://en.cppreference.com/w/cpp/language/operator_arithmetic
