### ISSUE TITLE
RPC package should provide a backend-agnostic helper to verify names/ids

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40048]
In OSS, ProcessGroup RPC backend verifies all worker names are distinct and uses ranks as ids. So that wrong name-to-id mapping will be spotted at construction time. However, for other RPC backend without collective communication capabilities, it is not that easy to gather all information from all workers and check their correctness. 

An alternative is to let `torch.distributed.rpc` provide a backend-agnostic helper to check all worker names using `c10d::Store`, and assign ids using the `c10d::Store`. This should help prevent applications from introducing unintentional mapping errors.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @xush6528

**Comment by mrshenli** [comment]
cc @kiukchung and @agolynski as this might be a common feature required by elasticity support.

**Comment by kiukchung** [comment]
We can extract out the changes in D22051616 to be dealt with in the thrift backend handler.
