### ISSUE TITLE
Restore top-level link to RPC

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#40046]
## 📚 Documentation

PR gh-37419 refactored the content of `docs/source/rpc/index.rst` into `docs/source/rpc.rst` but did not link to the latter from `doc/source/index.rst` so the top-level RPC documentation is missing from https://pytorch.org/docs/master/.

This should be fixed before the next release. I think it should be enough to replace `rpc/index.rst` with `rpc` on [`docs/source/index.rst`](https://github.com/pytorch/pytorch/blob/master/docs/source/index.rst) and make sure the top-level page is then visible.

noticed by @mrshenli 

cc @jlin27 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by mrshenli** [comment]
@lw and @rohan-varma spotted this first :)

**Comment by mrshenli** [comment]
Hey @mattip

qq, I noticed that the toc table and right navigation bar are showing the same content. Is this intentional? 

<img width="1060" alt="Screen Shot 2020-06-17 at 1 48 12 PM" src="https://user-images.githubusercontent.com/16999635/84931902-76f1c200-b0a1-11ea-817f-da925f698579.png">

cc @jlin27

**Comment by mattip** [comment]
The docs UX is not really my forte, but I would be willing to help implement whatever layout is desired.

**Comment by mrshenli** [comment]
@mattip no worries at all, not trying to blame anyone :)

It's just as we are getting close to v1.6 branch cut, I would like to learn what is the expected layout and will try to make things consistent for the next release. @jlin27 might now more.
