### ISSUE TITLE
reduce option in NLLLoss

### ISSUE THREAD

**Issue by pdakwale** [pytorch/pytorch#4005]
Current online documentation states that loss per batch element can be obtained by setting 'reduce=False' while calling NLLLoss

http://pytorch.org/docs/master/_modules/torch/nn/modules/loss.html

But when I am calling 
loss  = nn.NLLLoss(reduce=False)

It throws error : 

TypeError: __init__() got an unexpected keyword argument 'reduce'

I pulled latest pytorch. Is this option implemented in the last release ?

**Comment by soumith** [comment]
pull the latest pytorch in a few hours, we are in the process of transitioning over to a new release.

**Comment by Victor0118** [comment]
How about MarginRankingLoss for the same issue? Anyone working on this?

**Comment by apaszke** [comment]
I don't think so. Go for it if you want
