### ISSUE TITLE
C API pollutes the global namespace

### ISSUE THREAD

**Issue by elbaro** [pytorch/pytorch#40083]
## 🐛 Bug

`libtorch/include/c10/util/logging_is_not_google_glog.h` exposes `ERROR`, `FATAL`, etc in the global namespace.
This is included by `torch/script.h`.

This causes the conflict with a user code.

## Expected behavior

Put them in some namespace.

## Environment

build-hash: 4ff3872a2099993bf7e...
build-version: 1.5.0+cpu

cc @malfet @yf225 @glaringlee

**Comment by malfet** [comment]
This header mimics https://github.com/google/glog/blob/master/src/glog/log_severity.h#L68, but it sounds reasonable that pytorch should be compileable with GLOG_NO_ABBREVIATED_SEVERITIES

**Comment by hikatech** [comment]
I have the same problem.  
It seems that [this old commit (caffe2/core/logging_is_not_google_glog.h)](https://github.com/pytorch/pytorch/commit/6463eebc7bc3e648b5b17b05e7d461fb026e5c2f#) contained the bug.
