### ISSUE TITLE
Make torch.optim.Optimizer a context manager

### ISSUE THREAD

**Issue by Yura52** [pytorch/pytorch#40099]
## 🚀 Feature
I suggest making `torch.optim.Optimizer` a context manager:
```python
class Optimizer:
    ...
    def __enter__(self):
        self.zero_grad()
    def __exit__(self):
        self.step()
```

## Motivation
The following pattern...
```python
optimizer.zero_grad()  # STEP 1
...
loss.backward()
...
optimizer.step()  # STEP 2
```
... is ubiquitous. It is easy to forget about the STEP 1 or the STEP 2. The suggested feature makes an optimization step less error-prone and more expressive:
```python
with optimizer:
    ...
    loss.backward()
    ...
```

cc @vincentqb

**Comment by malfet** [comment]
This sounds like a useful feature, though it might negatively affect code readability. Perhaps something like that would be better:
```
with step_context(optimizer):
   ...
   loss.backward()
   ...
```

**Comment by Yura52** [comment]
I agree that _in general_ making something a context manager can be non-obvious for readers. However, this particular case is about a pattern that is familiar to everyone who has implemented a train loop at least once, so there is a good chance that the community will easily grasp the "Optimizer is a context" thing. This is why, in my opinion, a separate context manager that requires one extra import and one extra function call to _every_ train loop is not worth it.

Anyway, let's wait for other opinions :)

**Comment by vincentqb** [comment]
This is an interesting idea, but the gain seems very limited (not forgetting `zero_grad`?). Users are familiar with `zero_grad` and `step`, and each of those two operations have a clear orthogonal goal. 

Could there be other benefits from a context manager for an optimizer?

**Comment by Yura52** [comment]
Totally agree about orthogonality. However, in the pattern I described, the calls `zero_grad()` and `step()` form a very specific _context_, namely, "optimization step", which is "atomic" in some sense. This is why using a native Python construction for _contexts_ feels natural to me: I just say `with optimizer` and the right things happen automatically. Correspondingly, manual calls and a chance to forget one of them... it doesn't feel right. Well, may be, it is just me :)

> Could there be other benefits from a context manager for an optimizer?

The motivation I described above is the only motivation I implied, so yes, the benefit is minor ( ergonomics and some protection against possible mistakes). Well, the price for this benefit is also minor (close to zero?), as I see it.

**Comment by vincentqb** [comment]
Though I find the idea neat, I see the cost to this idea is an increase interface to maintain, and adding a new way for users to be confused on how to call optimizers. Hopefully whenever needed someone can help you remember :) One use case where a context may in fact add to the confusion would be when considering meta learning as in #39279.

In general, pytorch is also currently staying away from offering integrated training loop in favor of given control to the user. The new implementation would start blurring the line here :) Thoughts?

**Comment by Yura52** [comment]
> In general, pytorch is also currently staying away from offering integrated training loop in favor of given control to the user.

And I _really_ like that (if it was up to me, I would make PyTorch even more minimal 😄 ). Well, I see, for different people this "line" is different. Then it is better not to change anything here.
