### ISSUE TITLE
[proposal] Preserve strides and storage size for simple element-wise ops

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#4010]
This is a controversial proposal, since it would imply a change to the C-contiguity contract, but it may be useful to save memory and some computation.

```python
a = torch.ones(5, 1, 1)

print(a.expand(len(a), 10, 10).stride())
print(a.expand(len(a), 10, 10).storage().size())
# (1L, 0L, 0L)
# 5L

print(a.expand(len(a), 10, 10).mul(5).stride())
print(a.expand(len(a), 10, 10).mul(5).storage().size())
# (100L, 10L, 1L)
# 500L
```

**Comment by soumith** [comment]
This is a bad idea on multiple levels. I want to expand, but I think you already know the downsides of this proposal.

**Comment by vadimkantorov** [comment]
You refer mainly to the C-contiguity?

**Comment by soumith** [comment]
- It's a big change
- It's a breaking change
- It's a big performance regression
- The benefit is that memory profiles of output are the same as input. With the caching allocator and python being refcounted, I'm not even sure this is that big of a benefit.

**Comment by vadimkantorov** [comment]
Agreed, the benefits aren't obvious especially when we have good broadcasting.

For perf regression, for actually contiguous chunks of memory this wouldn't be the case, right?
For memory profiles, preserving small storage size should save memory for big expands. But again, not sure how frequent this happens.

Anyway, closing this issue.

**Comment by soumith** [comment]
wrt perf regressions, writing to expanded Tensors isn't good for cache hits. The large the expansion, worse it gets. Reading is also bad, but writing is particularly bad.

**Comment by vadimkantorov** [comment]
Where would writing to expanded tensor happen? I was thinking the op would perform and then would reshape/expand again.

I was thinking of something like (when reshape gets [added](https://github.com/pytorch/pytorch/issues/3919#issuecomment-347931970)):
```python
def mul(x, c):
    return (x.reshape(-1) * c).reshape(x.size()) if sum(x.stride()) == 1 else x * c
```
