### ISSUE TITLE
Add a helper function to DDP to print out all relevant env vars

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40105]
We have seen several complains on DDP hang/crash due to mis-configured env vars. Sometimes due to the subprocess didn't load the env vars correctly. Sometimes caused by env var overriding by some 3rd party libraries. It will be helpful to introduce a helper in DDP (maybe just in ctor) to read and print out all DDP-related env vars. So that it will be obvious which configurations are wrong.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by huangyi1979** [comment]
I plan to use `logging.info(os.environ)` in DDP's ctor to dump all environment variables. Is this approach expected? It has two obvious flaws:

1. This method dumps too many things. Do we have any filtering method to pick up what we need only? It seems that those env vars don't have a consistent name pattern.
2. Some env vars may not be set so this method cannot explicitly display them.

Example output:
> environ({'LANG': 'en_US.UTF-8', 'LOGNAME': 'huangyi', 'MKL_NUM_THREADS': '1', 'NO_MULTIPROCESSING_SPAWN': '0', 'OMP_NUM_THREADS': '1', 'PYTORCH_TEST': '1', 'PYTORCH_TEST_WITH_ASAN': '0', 'PYTORCH_TEST_WITH_TSAN': '0', 'PYTORCH_TEST_WITH_UBSAN': '0', 'SKIP_TEST_BOTTLENECK': '1', 'TEST_PILOT': 'True',...})

@mrshenli

**Comment by mrshenli** [comment]
Hey @huangyi1979, thanks for working on this.

We can explicitly consult the env vars that we care, including the following (I might miss some):

1. "RANK"  (see https://pytorch.org/docs/stable/distributed.html#environment-variable-initialization)
2. "WORLD_SIZE"
3. "MASTER_PORT"
4. "MASTER_ADDR"
5. "CUDA_VISIBLE_DEVICES"
6. "NCCL_SOCKET_IFNAME" (see https://pytorch.org/docs/stable/distributed.html#choosing-the-network-interface-to-use)
7. "GLOO_SOCKET_IFNAME"
8. "NCCL_DEBUG" (see https://pytorch.org/docs/stable/distributed.html#other-nccl-environment-variables)
9. "NCCL_DEBUG_SUBSYS"
10. "NCCL_IB_DISABLE" (see https://discuss.pytorch.org/t/torch-distributed-not-working-on-two-machines-nccl-backend/87659/7)
11. NCCL env vars https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html (it might be an overkill to print all nccl env vars, it's up to you if you would like to add all of them or skip)
