### ISSUE TITLE
Specify a particular arch for PyTorch..

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#40138]
1. To build PyTorch with so many archs is really time-consuming... I'm using **cmake** to build PyTorch, which turns out to build **caffe2** in the end. Anyway, I was using the command `ccmake ../`, I can't find anywhere I can specify a particular arch. Can anybody help please?

```console
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
```

2. It seems **cmake** is for building and installing **caffe2** ONLY???
To install **Python PyTorch**, I **MUST** use `python setup.py install` ???

**Comment by peterjc123** [comment]
```bash
# for Unix
export TORCH_CUDA_ARCH_LIST=7.5
# for Windows
set TORCH_CUDA_ARCH_LIST=7.5
```

**Comment by peterjc123** [comment]
> 1. It seems **cmake** is for building and installing **caffe2** ONLY???
>    To install **Python PyTorch**, I **MUST** use `python setup.py install` ???

`cmake -DBUILD_BUILDING_WITH_TORCH_LIBS=ON [other options]`
