### ISSUE TITLE
failed to load binary files saved from nightly build in version 1.5

### ISSUE THREAD

**Issue by SeungjunNah** [pytorch/pytorch#40140]
## 🐛 Bug

I am using both PyTorch 1.5 (stable) and nightly build (1.6.0.dev20200611).
Sometimes I need to run code in v1.5 and use files saved by ```torch.save``` from the nightly build.
However, PyTorch 1.5 fails to ```torch.load``` such files.

## To Reproduce

* PyTorch nightly

```python
import torch
a = torch.randn(1)
torch.save(a, 'a.pt')
```
* PyTorch 1.5 
```python
import torch
torch.load('a.pt')
```

Then it shows the following error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seungjun/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 586, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/seungjun/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 246, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1587428266983/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 4, but the maximum supported version for reading is 3. Your PyTorch installation may be too old.

## Expected behavior

I expect PyTorch 1.5 to load files without error.
Current behavior could be due to the update in PyTorchFileReader but I assume 1.5 and 1.6 should be compatible as their version number is close to each other.

## Environment

Loading: 
 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch  
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2.89, 7.6.5

Saving: 
 - PyTorch Version (e.g., 1.0): 1.6.0.dev20200611 for saving
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch-nightly  
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2.89, 7.6.5

cc @ezyang @gchanan @zou3519

**Comment by driazati** [comment]
The serialization in 1.6 uses a different format that should be load-able in 1.5 if not for that version check assert you are hitting. But regardless, you can use the old serialization format by doing 

```python
torch.save(a, 'a.pt', _use_new_zipfile_serialization=False)
```

**Comment by SeungjunNah** [comment]
@driazati 
Thanks for the comment. The default argument value ```_use_new_zipfile_serialization``` for torch.save is ```False``` in v1.5.0 and ```True``` in the current nightly.

I can try saving with the optional value to avoid current version conflict. However, I believe this is not an optimal way if PyTorch will eventually use the new serialization in future releases.
I wish 1.5.0 (or at least from 1.5.1) would be updated in the next post so that torch.load could read whichever serialization is used.

**Comment by albanD** [comment]
Hi,

In general we don't guarantee forward compatibility of the model (loading a file saved with a newer version of pytorch from an older version).
cc @mruberry who is looking into these issues, is this a duplicate.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/40279 will address this.

**Comment by SeungjunNah** [comment]
@albanD @mruberry 
Thanks! I'm looking forward for #40279 to be merged into master.

**Comment by mruberry** [comment]
Let's keep this issue open until #40279 is merged and we've verified it address this issue ;)

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/40279 is merged and should address this issue.
