### ISSUE TITLE
Can we get a conda package with cuda10.0 on windows

### ISSUE THREAD

**Issue by lhc741** [pytorch/pytorch#40216]
## 🚀 Feature
Need a conda package compiled with cuda10.0 on windows in pytorch channel

## Motivation
version>=1.3
I found there are conda packages compiled with cuda10.0 on Linux in pytorch channel, but  not found a package  compiled with cuda10.0 on Windows.
If we both use pytorch and tensorflow 1.1x on windows, it can't work well on GPUs. 
I think it will more convenient  if the package is  provided.
Thanks for your work!

## Pitch
Need a conda package compiled with cuda10.0 on windows in pytorch channel

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Yes, it can inferred from https://anaconda.org/pytorch/pytorch/files that we have packages for CUDA 10.0 in v1.3.0, v1.3.1 and v1.4.0 on Linux. But I wonder how meaningful it is to publish binaries for the versions 5 months ago. As far as I know, this is the only FR that asks for the cuda 10.0 package on Windows.



> If we both use pytorch and tensorflow 1.1x on windows, it can't work well on GPUs.

The workground is to install pytorch using pip if you want to install them into one environment. Virtual environment is another option. The third option is to build from source.

**Comment by kit1980** [comment]
Closing as CUDA 10.0 no longer supported.
