### ISSUE TITLE
Conda Package: cpuonly should be a mutex package

### ISSUE THREAD

**Issue by wolfv** [pytorch/pytorch#40213]
Currently, the pytorch conda packages use "track_features" to enable/disable CUDA vs. CPU.

`track_features` is discouraged by conda (e.g. in this blog post https://www.anaconda.com/blog/understanding-and-improving-condas-performance)

> Track_features are legacy metadata once used for lining up mkl and debug packages. They are deprecated in general, but are still sometimes used to effectively implement a default variant of a package by “weighing down” alternatives with track_features

The "new" way of achieving the desired result is through "mutex" packages, and there is a good explanation in this google doc: https://docs.google.com/document/d/1S2D4lTYfDV4GNGbRSDWobH2PWilUVXTHRgl-2tnzdxY

The additional benefit from switching is that pytorch's installation would work well with `mamba`, the fast C++ re-implementation of conda. (https://github.com/quantstack/mamba). We had a corresponding bug report there: https://github.com/QuantStack/mamba/issues/336

Sorry if I am posting this in the wrong place -- let me know if I should move it.

cc @ezyang @seemethere @malfet

**Comment by peterjc123** [comment]
@seemethere @ezyang What do you think?

**Comment by SylvainCorlay** [comment]
+1 on dropping `track_features`. They cause all kind of issues with the conda solver, and are now deprecated.

**Comment by ezyang** [comment]
Seems reasonable.

**Comment by seemethere** [comment]
Wait so if I'm reading this correctly, this will not effect the current installation instructions?

Like if we change `cpuonly` to be a `mutex` package then the installation instructions should still be:

```
conda install -c pytorch pytorch cpuonly
```

If those stay the same then yes I'd say this is reasonable.

**Comment by wolfv** [comment]
Yep, the installation instructions should stay the same.
But you might have to patch your repodata for the older pytorch versions.

**Comment by wolfv** [comment]
@seemethere @ezyang anything I can do to help you guys implement this?

**Comment by ezyang** [comment]
Our binary packaging is kind of wild and wooly but if you don't mind YOLOing (as in submitting a patch without testing it) you could try updating https://github.com/pytorch/builder/tree/master/conda/cpuonly to be a mutex package. If the PyTorch package itself also needs updating, a diff for that would be helpful too. It'll probably be difficult for you to actually build the packages unless you have a beefy machine, but I can help you get setup there if you are feeling really intrepid.

**Comment by wolfv** [comment]
I can just remove the actual build step or `touch` some files to generate the packages ;)

**Comment by IvanYashchuk** [comment]
Seems like the attempt to fix the problem no longer works and the PR was closed https://github.com/pytorch/builder/pull/488#issuecomment-888169348.
I'll work on resubmitting the required changes.
