### ISSUE TITLE
futures.wait_all should throw exceptions if there is any

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40226]
The `torch.futures.wait_all()` API currently silently returns all results acquired from the future. To stay consistent with `Future.wait()`, it might be better to re-throw exceptions if there is any. Otherwise, applications code will have to inspect all and throw.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by jjlilley** [comment]
I believe we already do this, though we didn't actually have a unittest coverage of that behavior. The following should add it:
  https://github.com/pytorch/pytorch/pull/40233

**Comment by mrshenli** [comment]
Closed by #40291
