### ISSUE TITLE
Seg fault in freeze_module during optimize_for_mobile on macOS.

### ISSUE THREAD

**Issue by kimishpatel** [pytorch/pytorch#40228]
## 🐛 Bug

This specifically happens only on macOS.
This has been tried on googlenet model from torchvision.
What happens is that when we get model and script this model and then pass it through optimize for mobile, seg fault is observed. See the reproducing steps.
I narrowed this down to freeze_module step in optimize_for_mobile at https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/xnnpack_rewrite.cpp#L317. 
Interesting to note is that
1. When we disable batch_norm fusion pass it work.
2. If I do freeze_module, on top of where it is done, at the beginning of optimizeForMobile, then also it works.

Try to reproduce the same by tracing the module instead of scripting it, but tracing did not work on torchvision's googlenet model.

## To Reproduce

1. Build pytorch from master on macos with
```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
USE_MKLDNN=0 REL_WITH_DEB_INFO=1 USE_FBGEMM=1 BUILD_CAFFE2_OPS=1 NO_CUDA=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py develop
```
Build torchvision from master.
2. Run the following:
```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile
model = torchvision.models.googlenet(pretrained=True)
ts_model = torch.jit.script(model)
opt_model = optimize_for_mobile(ts_model)
```
That should segfault.
3. Run the following:
```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile
from torch._C import MobileOptimizerType
model = torchvision.models.googlenet(pretrained=True)
ts_model = torch.jit.script(model)
optimization_blacklist_no_fold_bn = {MobileOptimizerType.CONV_BN_FUSION}
opt_model = optimize_for_mobile(ts_model, optimization_blacklist_no_fold_bn)
```
This should not seg fault.

cc @suo @fmassa

**Comment by eellison** [comment]
Are we sure the bug is not in batch_norm fusion pass ?

**Comment by kimishpatel** [comment]
> Are we sure the bug is not in batch_norm fusion pass ? Could you try running lint after the pass ?

Seg fault happens during freeze_module. It is possible that something in bn fusion is setting things up wrong and hence freeze_module fails.

I will check for that. Will put myself in the assignee as well.

**Comment by eellison** [comment]
This no longer repros, closing.
