### ISSUE TITLE
`torch.cuda.set_rng_state_all`  documentation refers `new_state` as an argument. 

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#40239]
#### Link

https://pytorch.org/docs/stable/cuda.html#torch.cuda.set_rng_state_all

#### API

`torch.utils.checkpoint.checkpoint_sequential`

#### Issue

In the "Parameters" section, there is an input ` new_state`, but it is not in the signature, and it is not accepted by the function. It should be `new_states`

Running code :

~~~python
torch.cuda.set_rng_state_all(new_state=(torch.ByteTensor(1)))
~~~

gives exception 

~~~python
TypeError: set_rng_state_all() got an unexpected keyword argument 'new_state'
~~~

#### **System information**

- OS: MacOS Mojave 10.14
- Tensorflow version:  1.5.0
- Python version: 3.8.2

cc @ngimel @jlin27

**Comment by vincentqb** [comment]
@ngimel -- do you want to comment on this?

**Comment by ngimel** [comment]
This is a documentation bug, not cuda bug.
