### ISSUE TITLE
Wrong versions in https://pytorch.org/docs/versions.html

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#40234]
## 📚 Documentation

Some of the version links on https://pytorch.org/docs/versions.html are wrong.

- master (unstable) -- correct
- v1.5.1 (stable release) -- links to https://pytorch.org/docs/master/ (wrong!)
- v1.5.0 -- links to https://pytorch.org/docs/stable/ which is 1.5.1 (wrong!)

The remaining links seem OK.

**Comment by jspisak** [comment]
@jlin27  - can you take a look?

**Comment by seemethere** [comment]
I think you may just need to reload the page, the versions for me are correct now.

From the HTML:
![Screen Shot 2020-06-18 at 5 31 33 PM](https://user-images.githubusercontent.com/1700823/85084458-b3005200-b189-11ea-9f9b-f947b34ad68e.png)

**Comment by soumith** [comment]
yea can confirm it must be a cache thing. they look correct to me.
