### ISSUE TITLE
b'CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ElijahLai** [pytorch/pytorch#4023]
~~~~~~~~~~~~~~~~~~~~~~~~~~  ERROR INFOR
~/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py in backward_extended(self, grad_output, grad_hy)
    332                 output,
    333                 weight,
--> 334                 grad_weight)
    335         else:
    336             grad_weight = [(None,) * len(layer_weight) for layer_weight in weight]

~/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py in backward_weight(fn, input, hx, output, weight, grad_weight)
    462             ctypes.c_void_p(workspace.data_ptr()), workspace.size(0),
    463             fn.w_desc, ctypes.c_void_p(dw.data_ptr()),
--> 464             ctypes.c_void_p(fn.reserve.data_ptr()), fn.reserve.size(0)
    465         ))
    466 

~/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py in check_error(status)
    253 def check_error(status):
    254     if status is not 0:
--> 255         raise CuDNNError(status)
    256 
    257 

CuDNNError: 8: b'CUDNN_STATUS_EXECUTION_FAILED'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~  MY CODE
class DecoderRNN(nn.Module):
    def __init__(self,embedding_size,hidden_size,vervab_size,n_layers=1,dropout_p=0.2):
        """
        :param embedding_size: word embedding size
        :param hidden_size: encoder hidden size
        :param vervab_size: output size(all the vercabulary)
        :param n_layers: layers of cells(lstm/gru)
        :param dropout_p: drop out persentage
        """
        super(DecoderRNN,self).__init__()
        # define data size
        self.n_layers = n_layers
        self.hidden_size = hidden_size
        self.dropout_p = dropout_p
        
        # define operation
        self.embedding = nn.Embedding(vervab_size,embedding_size)
        self.dropout = nn.Dropout(self.dropout_p)
        self.lstm = nn.LSTM(embedding_size,hidden_size)
        self.out = nn.Linear(hidden_size,vervab_size)
        self.softmax = nn.LogSoftmax()
        
    def forward(self,input,hidden):
        embedded = self.embedding(input)
        output = self.dropout(embedded)
        for i in range(self.n_layers):
            output, hidden = self.lstm(output,hidden)
        output = self.softmax(self.out(output[0]))
        return output,hidden
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I'm very comfused what happen to my code, I can use GPU to run another case but I always meet this error information during runing Attention-based seq2seq and now vanilla seq2seq.

Could anyone help me ?

**Comment by ezyang** [comment]
Could you tell us your version of CUDA and CuDNN, as well as your driver version (displayed by nvidia-smi)?

**Comment by ElijahLai** [comment]
Here~~
cuda 8.0 V8.0.61
NVIDIA-SMI 384.66
Driver Version: 375.26
cudnn 6 0 21

**Comment by juiceboxjoe** [comment]
@ElijahLai did you resolve your issue? I'm having the same problem when I try to make a prediction with my trained model. My CUDA version is 8.0.61, CuDNN version is 6.0.21, and driver version is 384.111.

**Comment by ElijahLai** [comment]
Yep, I figured out that I make a mistake with cudnn soft link during install cuda. Your should make a soft link in cuda-8.0(or cuda8.0, I dont remember) but not in cuda. like this:

sudo cp cudnn.h /usr/local/cuda-8.0/include/
sudo cp lib* /usr/local/cuda-8.0/lib64/    
cd /usr/local/cuda-8.0/lib64/sudo rm -rf libcudnn.so libcudnn.so.6
sudo ln -s libcudnn.so.6.0.21 libcudnn.so.6  
sudo ln -s libcudnn.so.6 libcudnn.so

**Comment by juiceboxjoe** [comment]
@ElijahLai thank you for your quick response. 

libcudnn.so and libcudnn.so.6 already exist as soft links inside cuda-8.0/lib64. Did you regenerate those soft links or did you simple not have them (you added them for the first time)?

I ask because my setup already has cudnn.h in cuda-8.0/include, the lib files in cuda-8.0/lib64, and already has the soft links you mentioned.

Thanks in advance!

**Comment by ElijahLai** [comment]
Just regenerate them, you can run what I provide above and pay most attention to the path !!

**Comment by juiceboxjoe** [comment]
@ElijahLai I regenerated the soft links (without copying the cudnn.h file and lib* files - I just used what was already there in cuda-8.0/include and cuda-8.0/lib64/) but that did not solve my problem.

**Comment by ElijahLai** [comment]
maybe you should check the cuda path your pytorch are using

**Comment by mruberry** [comment]
Closing due to age and apparent solution. Please reopen if you're still experiencing this issue on the latest PyTorch.
