### ISSUE TITLE
Format issue in `kaiming_uniform_` and `kaiming_normal_` documentation parameter section

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#40240]
#### Link

[https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_normal_](https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_normal_)

[https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_uniform_](https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.kaiming_uniform_)

#### API

`torch.nn.init.kaiming_uniform_` 

`torch.nn.init.kaiming_normal_`

#### Issue

In the "Parameters" section, there is an input :

**with 'leaky_relu')** (*used*) –

which should be part of the description for input argument `a`

cc @jlin27 @albanD @mruberry

**Comment by vincentqb** [comment]
Thanks for reporting this! Do you want to open a pull request to fix this?

**Comment by DNXie** [comment]
@vincentqb I tried to make the document several times, but all failed.  I followed the guidance here: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#writing-documentation
But got the error message every time:
~~~
Exception occurred:
  File "/miniconda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'katex': 'katex'
~~~
Since it is a format issue, I really need to look at the HTML file after `make` to make sure the format is correct. Sorry for that. Please assign some other developer for this. Thank you!

**Comment by albanD** [comment]
Yes, you need to have `katex` installed (available via node.js package manager or with apt with name "node-katex" for ubuntu-like distros).

**Comment by thomasjpfan** [comment]
Closing because this issue was fixed in https://github.com/pytorch/pytorch/pull/37739
