### ISSUE TITLE
import error with v0.3 binary

### ISSUE THREAD

**Issue by mingdachen** [pytorch/pytorch#4025]
I got an import error after installing v0.3 binary. Installed pytorch via conda using python3.5.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mingdachen/anaconda2/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libmkl_gf_lp64.so: cannot open shared object file: No such file or directory

**Comment by floringogianu** [comment]
Same here on a cloned virtualenv.

**Comment by soumith** [comment]
did mkl get installed in your environment?

**Comment by floringogianu** [comment]
Yes, `mkl 2017.0.3`. The same version as in my `torch 0.2` virtualenv which works fine.

**Comment by soumith** [comment]
There should've been a line like this when you updated PyTorch:

```
The following packages will be UPDATED:

    mkl:          2017.0.3-0                                         --> 2018.0.1-h19d6760_4
```

Did yyou see it?

**Comment by soumith** [comment]
@floringogianu can you tell me your linux distro? I want to be able to reproduce this in a docker image. Right now I'm not able to (weird)

**Comment by floringogianu** [comment]
Ubuntu 17.04, kernel 4.10.0-40-generic,  cuda v8.0.61, gcc 4.9.4

Just to be clear, installing in a fresh virtualenv gave me the same error. I tried updating from pytorch 0.2 to see if mkl gets upgraded but it is not, all I get is this:

```
The following NEW packages will be INSTALLED:

    cudatoolkit: 8.0-3                           

The following packages will be UPDATED:

    pytorch:     0.2.0-py36h53baedd_4cu80 soumith [cuda80] --> 0.3.0-py36_cuda8.0.61_cudnn7.0.3h06d1a12_1 pytorch
    torchvision: 0.1.9-py36h7584368_1     soumith --> 0.2.0-py36h17b6947_1                       pytorch
```

Also I find it a bit weird that I don't have `libmkl_gf_lp64.so` anywhere in the system. I have multiple virtualenvs and most of the shared mkl libraries are where they are supposed to be, except this one.

**Comment by mingdachen** [comment]
@soumith I tried the same method as @floringogianu and I also failed. Now I am using pytorch built from v0.3 branch. Here is my platform info:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by soumith** [comment]
@floringogianu i dont know what exactly it is happening, but you are getting pytorch build `0.3.0_1`, whereas the latest build is `0.3.0_4`.

**Comment by soumith** [comment]
What commands are you using for upgrading? I think both of you have the same problem, the latest build `4` is not getting installed, but build `1` is...

**Comment by mingdachen** [comment]
I am using

conda install pytorch torchvision -c pytorch

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/mingdachen/anaconda2/envs/py35:

The following NEW packages will be INSTALLED:

    cudatoolkit: 8.0-3

The following packages will be UPDATED:

    pytorch:     0.2.0-py35hb1547bd_4cu80 soumith [cuda80] --> 0.3.0-py35_cuda8.0.61_cudnn7.0.3h34519bc_1 pytorch
    torchvision: 0.1.9-py35h72e4c6f_1     soumith --> 0.2.0-py35heaa392f_1                       pytorch

Proceed ([y]/n)?

**Comment by soumith** [comment]
this is super weird. Can you guys both clear your conda cache...

```
conda clean --all
conda uninstall -y pytorch
conda install pytorch torchvision -c pytorch
```

**Comment by floringogianu** [comment]
@soumith I already did exactly that several times :) It didn't help.

What eventually did the trick was this:
```
conda upgrade conda
conda upgrade anaconda
```
This somehow forced `mkl 2018.0.1 h19d6760_4` to be installed.

**Comment by mingdachen** [comment]
It doesn't work for me. After cleaning and updating conda, conda found an even older version of pytorch

conda install pytorch torchvision -c pytorch
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/mingdachen/anaconda2/envs/py35:

The following NEW packages will be INSTALLED:

    cudatoolkit: 8.0-3
    cudnn:       6.0.21-cuda8.0_0
    nccl:        1.3.4-cuda8.0_1
    pytorch:     0.1.12-py35cuda8.0cudnn6.0_1
    torchvision: 0.1.8-py35_0

Proceed ([y]/n)?

**Comment by soumith** [comment]
@mingdachen are you behind some kind of proxy? That's the only thing I can think of, where anaconda servers are being cached somewhere on your path.

**Comment by mingdachen** [comment]
@soumith I am not using any proxy. Since I can install v0.3 via pip, I can close this issue if this problem only occurs on my machines.

**Comment by jihunchoi** [comment]
I also had the same issue, and I'm not behind any proxy too.
For me, as in @mingdachen's case, conda kept trying to install pytorch in the default repo, instead of the one in the pytorch repo.
It seems that the latest version of mkl is one of dependencies of pytorch, so the following line solved my problem (though downloading mkl is a bit slow).
`conda install -c anaconda mkl`

Before:
```
▶ conda install -c pytorch pytorch cuda90
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jhchoi/anaconda3/envs/ml:

The following NEW packages will be INSTALLED:

    cuda90:      1.0-h6433d27_0               pytorch
    cudatoolkit: 8.0-3
    cudnn:       6.0.21-cuda8.0_0
    nccl:        1.3.4-cuda8.0_1
    pytorch:     0.1.12-py36cuda8.0cudnn6.0_1

Proceed ([y]/n)? ^C%                                    
```

After installing the latest mkl:
```
▶ conda install -c pytorch pytorch cuda90
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jhchoi/anaconda3/envs/ml:

The following NEW packages will be INSTALLED:

    cuda90:  1.0-h6433d27_0                              pytorch
    pytorch: 0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4 pytorch [cuda90]

Proceed ([y]/n)? y
```
