### ISSUE TITLE
[JIT] Support `with torch.autograd.profiler.record_function`

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#40260]
Now that #34705 has landed, we need to add support for `with torch.autograd.profiler.record_function()`.

cc @suo

**Comment by brian112358** [comment]
Hi @SplitInfinity - has there been any progress made on this issue? Adding support for this would make it much cleaner to add annotations to the `torch.autograd.profiler` in TorchScripted modules. I've currently been working around it using code like this:
```
handle = torch.ops.profiler._record_function_enter('foo')
# profiled code here
torch.ops.profiler._record_function_exit(handle)
```

which works properly in a Torchscripted module, but using a `with` context manager would be much cleaner.

**Comment by SplitInfinity** [comment]
No progress has been made. However, I just got #41371 approved (using `torch.no_grad` in `with` statements), so I can work on this next.

**Comment by SplitInfinity** [comment]
@brian112358 Someone has submitted a PR for this.
