### ISSUE TITLE
RuntimeError: Only Tensors of floating point dtype can require gradients

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/pytorch#40264]
## 🐛 Bug

pytorch did not support LongTensor requires grad but allowed Tensor with "requires_grad=True" convert to "Long" type.

## To Reproduce

```python
import torch
x = torch.rand(3, 3)
x.long().requires_grad_()  # will throw an RuntimeError
x.requires_grad_().long()  # will work and get an Long tensor with requires_grad=True
```

It seems the codes will check Tensor's datatype when set requires grad = True, but will not check whether requires_grad when change Tensor's datatype. 

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by vincentqb** [comment]
Assigned "module: autogra" due to `requires_grad`.

@albanD -- do you want to comment on this? or do you know which module would be more appropriate?

**Comment by albanD** [comment]
Hi,

Which version of pytorch are you using?
It is expected that it does not raise an error (for BC reasons) but the returned Tensor won't require gradients. So all should be fine right?

**Comment by zhuhaozhe** [comment]
@albanD. Sorry I have made a mistake, the returned Tensor won't require gradients by the steps I provided. However, I still meet this situation (get a long tensor with requires_grad=True)
 
My pytorch version is 1.5rc3, using these to reproduce:
>>> import torch
>>> LL = torch.nn.Linear(3,3)
>>> LL.weight.data = LL.weight.long()
>>> LL.weight
Parameter containing:
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], requires_grad=True)

**Comment by zhuhaozhe** [comment]
In fact I meet this at https://github.com/pytorch/pytorch/blob/v1.5.0-rc3/test/test_nn.py#L8372

After this line, the module's weight will be a long Tensor with requires_grad=True

**Comment by albanD** [comment]
Hi,

You should **never** use `.data` :D  By using it you can many many things that you should not be able to do. We're in the progress of deprecating and removing it.

> After this line, the module's weight will be a long Tensor with requires_grad=True

Yes this test looks like it should be updated. Making nn.Parameter with long type does not make sense (and that's why the test does forward only and has to use the internal `_apply` API to be able to achieve this).
I think we should just change these to regular Tensors to avoid these issues.

**Comment by zhuhaozhe** [comment]
OK, thank you @albanD .

**Comment by xiangyu-getklothed** [comment]
I tried this `x.requires_grad_().long()`. But require gradient is still false. My pytorch version is 1.1.0.

> ##  Bug
> pytorch did not support LongTensor requires grad but allowed Tensor with "requires_grad=True" convert to "Long" type.
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> ```python
> import torch
> x = torch.rand(3, 3)
> x.long().requires_grad_()  # will throw an RuntimeError
> x.requires_grad_().long()  # will work and get an Long tensor with requires_grad=True
> ```
> 
> It seems the codes will check Tensor's datatype when set requires grad = True, but will not check whether requires_grad when change Tensor's datatype.
> 
> cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by albanD** [comment]
Hi,

This is the expected behavior. `LongTensor` cannot require gradients.

**Comment by nyukers** [comment]
> Hi,
> 
> This is the expected behavior. `LongTensor` cannot require gradients.

It's so good but [bug](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/issues/33) exists.

**Comment by LukeLIN-web** [comment]
I am trying to use int8 model but also has this problem.
```
import torch

from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video

pipe = StableVideoDiffusionPipeline.from_pretrained(
    "siliconflow/stable-video-diffusion-img2vid-xt-int8", torch_dtype=torch.float16
)
pipe.enable_model_cpu_offload()

# Load the conditioning image
image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
frames = pipe(image, decode_chunk_size=8, generator=generator).frames[0]

export_to_video(frames, "generated.mp4", fps=7)
```
