### ISSUE TITLE
Information about training option in torch.onnx.export()

### ISSUE THREAD

**Issue by alex96295** [pytorch/pytorch#40272]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hi,

I would like to ask a question: if I happen to have a pytorch .pth model, and want to convert it in onnx, then I would go for torch.onnx library. Yet, I want to convert the onnx model to tensorflow model.

First question: should I put model.eval() before exporting? Because there is an option in torch.onnx.export() - called 'training' - that says:

``` training (bool, default False): export the model in training mode. At the moment, ONNX is oriented towards exporting models for inference only, so you will generally not need to set this to True.``` 

Therefore, I was wondering how that option is related to me putting or no 'model.eval()' before.

**Comment by ezyang** [comment]
As the template text says, you should ask this question in the forum.

**Comment by alex96295** [comment]
@ezyang Yes I did but they told me maybe to ask in the pytorch forum
