### ISSUE TITLE
ComplexDoubleStorage

### ISSUE THREAD

**Issue by sinanmut** [pytorch/pytorch#40277]
with pytorch 1.5.1 version I am getting this error:

<ipython-input-1-eb42ca6e4af3> in <module>
----> 1 import torch

usr/lib/python3.7/site-packages/torch/__init__.py in <module>
    316 
    317 # Shared memory manager needs to know the exact location of manager executable
--> 318 _C._initExtension(manager_path())
    319 del manager_path
    320 

AttributeError: module 'torch' has no attribute 'ComplexDoubleStorage'

Is there any package I have to install for this? Thanks

cc @ezyang @seemethere @malfet @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
This suggests some sort of corrupted install. Can you uninstall all copies of pytorch (e.g., `pip uninstall torch` repeatedly until it no-ops) and try installing again?

If that still doesn't resolve your error please use https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py to give us more information about your environment

**Comment by ezyang** [comment]
I verified the OS X release doesn't have this problem, so I'm leaving this at not high priority until we have more clarity on the issue.

**Comment by sinanmut** [comment]
I am getting this when I run with collect_env script:

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
OS: Arch Linux
GCC version: (GCC) 7.4.1 20181207
CMake version: version 3.17.3
Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 440.82
cuDNN version: /usr/lib/libcudnn.so.7.6.5
Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] numpydoc==0.8.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

Thanks

**Comment by sinanmut** [comment]
I think it is related to cython, but don't know how to solve it. Previous torch versions (1.4, 1.3 aand 1,2) gave errors like: 

/usr/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z10initModulev

**Comment by ezyang** [comment]
How did you install PyTorch? Can you install a Miniconda environment and then install PyTorch inside that?

**Comment by sinanmut** [comment]
I  installed it with pip. Today I tried it with conda, I don't get any errors but pytorch-geometric doesn't provide a conda package so I still need to install it using pip. Thanks

**Comment by seemethere** [comment]
Yeah I couldn't recreate using an archlinux docker image.

```bash
docker run --rm -it -v $(pwd)/test-arch:/test-arch:ro archlinux bash /test-arch
```

`test-arch`
```bash
#!/usr/bin/env bash

set -eoux pipefail

pacman -Sy --noconfirm python3 python-pip
pip install torch torchvision
python -c "import torch; print(torch.version.git_version)"
```

**Comment by ezyang** [comment]
Sounds like a botched pip install one way or another. I'm going to close this for now, but if you run into further problems feel free to reopen.
