### ISSUE TITLE
Conbine two variables in a special way?

### ISSUE THREAD

**Issue by BIgRunner** [pytorch/pytorch#4030]
As the title, I wanted to conbine two variables in a special way:
```
a = nn.Linear(*, 6)
b = nn.Linear(*, 3)
```
and I need to get output at lelement level like
```
for r  in range(batch_size):
  for c in range(3*6):
    output[r][c] = a[r][c // 3]  + b[r][c % 3]
```
How can I get the output? and I want to use it in backward function.

**Comment by colesbury** [comment]
Please ask your question on the forums: https://discuss.pytorch.org/
