### ISSUE TITLE
DISABLED test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#40303]
https://app.circleci.com/pipelines/github/pytorch/pytorch/183267/workflows/af7c3c56-4437-47f7-ad4c-f816e4485705/jobs/5930451/steps

```
Jun 19 20:19:53 ======================================================================
Jun 19 20:19:53 ERROR [100.089s]: test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)
Jun 19 20:19:53 ----------------------------------------------------------------------
Jun 19 20:19:53 Traceback (most recent call last):
Jun 19 20:19:53   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jun 19 20:19:53     self._join_processes(fn)
Jun 19 20:19:53   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 306, in _join_processes
Jun 19 20:19:53     self._check_return_codes(elapsed_time)
Jun 19 20:19:53   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 344, in _check_return_codes
Jun 19 20:19:53     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Jun 19 20:19:53 RuntimeError: Process 0 terminated or timed out after 100.07188177108765 seconds
Jun 19 20:19:53 
Jun 19 20:19:53 ----------------------------------------------------------------------
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @lw @beauby @agolynski @SciPioneer @H-Huang @cbalioglu @xush6528

**Comment by rohan-varma** [comment]
Another instance: https://app.circleci.com/pipelines/github/pytorch/pytorch/219927/workflows/99f97810-bcee-480a-9fd4-ff71b21ed680/jobs/7804436/tests

**Comment by lw** [comment]
Did this start reappearing after some recent change? I remember @mrshenli mentioning something about this test in one discussion about adding barriers to init_rpc or init_process_group...

**Comment by janeyx99** [comment]
Closing as TensorPipeAgentRpcTestWithSpawn has not been run in the last 2 weeks so this test no longer is triggered by anything.
