### ISSUE TITLE
Rename all "quantization" kernels in the native_functions.yaml

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#40315]
Current naming convention for the quantized ops is `quantized_...`. However, with the introduction of different devices, such as quantized cuda, this will become a little hard to maintain. Need to rename all the `quantized_...` names into `..._quantized_cpu`, which is the pattern for the non-quantized kernels.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @dzhulgakov

**Comment by Nishikoh** [comment]
Can I tackle this issue?

**Comment by z-a-f** [comment]
> Can I tackle this issue?

Please, go ahead!!!

**Comment by z-a-f** [comment]
> Can I tackle this issue?

Thank you for doing this.

**Comment by z-a-f** [comment]
There are still some names that are using the old format (`quantized_...`). Will leave this open until it's done

**Comment by mchirag2002** [comment]
May I change the rest of them?

**Comment by sonuagarwal1008** [comment]
I want to work on this issue. Is this still open?

**Comment by z-a-f** [comment]
> I want to work on this issue. Is this still open?

If there are names that are not conforming -- please, go ahead

**Comment by ps-19** [comment]
@z-a-f is it still not resolved?? i would like to work on this issue.

**Comment by param-thakker** [comment]
Hi @z-a-f , is this still not finished? I would love to contribute and learn!

**Comment by ps-19** [comment]
Hi @z-a-f assign me if it is not done yet i would like to work upon it

**Comment by pranav-chandrode** [comment]
can I contribute to this issue?

**Comment by andrewor14** [comment]
@supriyar @jerryzh168 Should we close this for now? This seems like a stale issue and any renaming now will be BC breaking

**Comment by jerryzh168** [comment]
yeah I feel it might be fine to close for now, we are generally moving away from these ops anyways
