### ISSUE TITLE
NVIDIA memory not deallocated after interupt

### ISSUE THREAD

**Issue by tamis-laan** [pytorch/pytorch#4031]
When I interrupt my Pytorch script using Ctrl-C occasionally GPU memory is not deallocated. Also threads related to my script may or may not still be running. If they are running I kill them using "kill -9 PID". However this does not deallocate memory on the GPU. 

> Tue Dec  5 14:12:11 2017       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  TITAN X (Pascal)    Off  | 00000000:02:00.0  On |                  N/A |
> | 31%   54C    P2    58W / 250W |   7829MiB / 12189MiB |      3%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0      1213      G   /usr/lib/xorg/Xorg                           166MiB |
> |    0      2355      G   compiz                                       249MiB |
> |    0     32412      G   ...-token=00DF6CCAB2487BD6F9AE70914F3A9358     8MiB |
> +-----------------------------------------------------------------------------+

**Comment by soumith** [comment]
try: `killall python`. Some processes dont show up in `nvidia-smi`

**Comment by tamis-laan** [comment]
I do:
> ls -Al | grep python
I then kill any python instance that is still running using:
> kill -9 PID
Yet the memory is still allocated on the GPU.

**Comment by albanD** [comment]
Hi,

You can run `lsof /dev/nvidia0` to list all processes using the GPU. One of them is taking some memory, kill it.

**Comment by neighthan** [comment]
I've had this issue a couple of times as well. I added a function to a small repo of GPU utilities that I have to kill processes that are using GPUs as shown by `lsof /dev/nvidia*` but which aren't listed by `nvidia-smi`. Take a look [here](https://github.com/neighthan/gpu-utils/blob/c6329f21fa3780ee89985b7974194cb808643f5c/gpu_utils/utils.py#L114) if you're interested.

**Comment by mruberry** [comment]
Closing due to age and proposed solution. Please reopen if you're still experiencing this issue.

**Comment by bagustris** [comment]
Facing this issue on Pytorch 1.10.1, the process name becomes hyphen after `kill -9 PID` (shown below: the last line). The memory cannot be taken back except restarting PC.

![image](https://user-images.githubusercontent.com/3158361/147333678-a8bdcc27-5cf7-4961-bf54-5ede1551723b.png)
