### ISSUE TITLE
Improve error reporting in "Check for no AVX instruction by default"

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#40320]
When AVX/AVX2 instruction is encountered while running `basic` unit test, qemu segfaults, which does give developer a good idea why the test have failed.
This could be improved by re-running `qemu` with gdbserver and printing a backtrace + instruction that caused the failure. This can be done by modifying
https://github.com/pytorch/pytorch/blob/a80dd02a224ea0f2c9582f428bc12d4579deaa92/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml#L135 
To something along the following lines:
```
$ qemu-x86_64 -g 2345 -cpu Broadwell -E ATEN_CPU_CAPABILITY=default ./basic --gtest_filter=BasicTest.BasicTestCPU &
$ gdb ./basic -ex "target remote :2345" -ex "continue" -ex "bt"
```

How to test that the change:
Add global AVX variable to any .cpp file, for example:
```
const __m256i foobar = _mm256_set_epi32(0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08);
```

**Comment by RockingJavaBean** [comment]
@malfet thank you so much for the kind tip on how to manipulate gdbserver to print backtrace/instruction.
I have modified the CI files according in the draft PR.
```bash
echo "apt-get update && apt-get install -y qemu-user gdb" | docker exec -u root -i "$id" bash
echo "cd workspace/build; qemu-x86_64 -g 2345 -cpu Broadwell -E ATEN_CPU_CAPABILITY=default ./bin/basic --gtest_filter=BasicTest.BasicTestCPU & gdb ./bin/basic -ex 'target remote :2345' -ex 'continue' -ex 'bt' -ex='set confirm off' -ex 'quit'" | docker exec -u jenkins -i "$id" bash
```

Below are the logs for the `Check for no AVX instruction by default` step of the `pytorch_linux_bionic_py3_6_clang9_test` job.
```
Reading symbols from ./bin/basic...(no debugging symbols found)...done.
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Remote debugging using :2345
...
...
warning: TCG doesn't support requested feature: CPUID.07H:EBX.rdseed [bit 18]
warning: TCG doesn't support requested feature: CPUID.80000001H:ECX.3dnowprefetch [bit 8]
[       OK ] BasicTest.BasicTestCPU (1880 ms)
[----------] 1 test from BasicTest (1884 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1887 ms total)
[  PASSED  ] 1 test.
[Inferior 1 (Remote target) exited normally]
No stack.
CircleCI received exit code 0
```
The gdbserver connected to the qemu via 2345 port, and it seems that there is no qemu segfault during this CI step.

In terms of testing the change, I have looked up the existing code using `_mm256_set_epi32` function, and It is guarded by the `CPU_CAPABILITY_AVX2`.

https://github.com/pytorch/pytorch/blob/ecd9a6471270725365065e26101bd168cf5575c5/aten/src/ATen/cpu/vec256/vec256_qint.h#L106-L111

I tried adding the similar code to the `basic.cpp`  testcase, the `qemu segfaults` still were not shown in the `Check for no AVX instruction by default` step.

Please kindly share the suggestions on how to add the global AVX variable to test the change.
