### ISSUE TITLE
Access Denied error when trying to download libtorch v1.5.1 for Windows

### ISSUE THREAD

**Issue by mfl28** [pytorch/pytorch#40339]
## To Reproduce

1. On the PyTorch website click on the Debug or Release download links for  libtorch v1.5.1 on Windows either without CUDA or with CUDA versions 9.2 or 10.1 (10.2 works fine).

Error message:
![image](https://user-images.githubusercontent.com/46156789/85204779-18357e00-b317-11ea-811e-8e9221bf5f23.png)

## Expected behavior

Selected libtorch version is downloaded.

## Environment
 - Libtorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Windows
 - CUDA versions: None, 9.2, 10.1

**Comment by peterjc123** [comment]
CPU:
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.5.1%2Bcpu.zip
CUDA 9.2
https://download.pytorch.org/libtorch/cu92/libtorch-win-shared-with-deps-1.5.1%2Bcu92.zip
CUDA 10.1
https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.5.1%2Bcu101.zip

Related code: https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/binary_populate_env.sh#L88
Do we need to get rid of those version tags?
cc @seemethere
