### ISSUE TITLE
Onnx export: segmentation fault

### ISSUE THREAD

**Issue by carpo93** [pytorch/pytorch#4033]
When I try to run the onnx export tutorial from here (http://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html#transfering-srresnet-using-onnx) everything works fine.
When i try to do it like here (https://github.com/pytorch/pytorch/blob/master/docs/source/onnx.rst) I get a segmentation fault
For everything else torchvision is working perfectly

**Comment by fmassa** [comment]
Are you using the master branch of pytorch?
There is a PR fixing a segfault in ONNX export in https://github.com/pytorch/pytorch/pull/4014 , maybe it fixes your problem?

**Comment by carpo93** [comment]
Yes, compiled it from the github sources less than 2 hours ago

**Comment by fmassa** [comment]
The PR I mentioned just got merged. Can you try seeing if recompiling pytorch fixed your problem?

**Comment by carpo93** [comment]
I'm going to check tomorrow morning, thanks!

**Comment by carpo93** [comment]
Thanks, now it is working!

**Comment by Sucran** [comment]
Hi, @fmassa 
I met the same issue in Pytorch 0.4.1, I installed it by pypi in Ubuntu 14.04, CUDA 8.0 just yesterday.
I do not install onnx.
I just run the tutorial code of onnx [tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb) and it happened.
