### ISSUE TITLE
THCIntegerDivider.cuh is not included into PyTorch pip nightly builds

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#40356]
I build a cpp extension and I `#include <ATen/cuda/detail/OffsetCalculator.cuh>`. If PyTorch is installed via conda(nightly/release) or pip(release) everything is ok, but if PyTorch is installed via pip nightly builds compilation fails:
```
/opt/circleci/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/include/ATen/cuda/detail/OffsetCalculator.cuh:8:37: fatal error: THC/THCIntegerDivider.cuh: No such file or directory
```

cc @ezyang @seemethere @malfet

**Comment by ezyang** [comment]
How are you installing PyTorch through pip?

**Comment by pbelevich** [comment]
@ezyang `pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

**Comment by ezyang** [comment]
You're installing the CPU wheel, it's not too surprising that CUDA headers are not included...

**Comment by pbelevich** [comment]
yeah, my mistake! thanks for your help!
