### ISSUE TITLE
RuntimeError: _th_exp_out not supported on CUDAType for Long

### ISSUE THREAD

**Issue by mariusjohan** [pytorch/pytorch#40357]
## ❓ Questions and Help
I'm trying to finetune a transformer model for question answering, and am using the BCEWithLogitsLoss function. 
However when I try calculating loss i get this error:
> RuntimeError: _th_exp_out not supported on CUDAType for Long

I'm inputting matrices with the shape and dtype of ```[16, 2]``` and ```Long```  
Bud sadly I've no idea to solve this. I tried using another dtype (int32, float32, double), which didn't work, and

Here is the code:
```python
def loss_fn(self, preds, labels):
    return torch.nn.BCEWithLogitsLoss()(preds, labels)

def train_fn(self, dataloader, model, optimizer, device):
    # Some other stuff here
    pred = model(
            token_ids = token_ids,
            attention_mask = attention_mask,
            token_type_ids = token_type_ids)
    start_scores = torch.argmax(pred[0], dim=1)
    end_scores = torch.argmax(pred[1], dim=1)
        
    pred = torch.tensor(list(zip(start_scores, end_scores)))
    pred = pred.to(device, dtype=torch.long)

    batch_loss = self.loss_fn(pred, label)
```

cc @jlin27 @albanD @mruberry

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/28703

**Comment by ngimel** [comment]
BCEWithLogitsLoss expects both preds and labels to be floating point (they are not labels, they are logits btw, so it makes sense that they are floating point.

**Comment by zou3519** [comment]
What @ngimel said. We could probably improve the error message on this, though.

**Comment by mariusjohan** [comment]
Thank you @ngimel

**Comment by mariusjohan** [comment]
@zou3519 That would be great! 

I'm thinking something like: 
> The long dtype isn't supported on CUDA devices. Please change the dtype to a double

It would also be great if you could show in which order the error came. But I don't if that's possible.
I first got the long error, and when I changed it, I got this error: 
> result type Double can't be cast to the desired output type Long
Which confused me into thinking that the previous dtype had to be long
