### ISSUE TITLE
Type strings of torch.jit.trace and torch.onnx.export forbid torch.Tensor as argument

### ISSUE THREAD

**Issue by JBamberger** [pytorch/pytorch#40350]
## 🐛 Bug

The type annotations for the  `example_input` and `args` arguments of `torch.jit.trace` and `torch.onnx.export` respectively are too restrictive. They only allow a tuple as input but the doc string explicitly mentions that a `torch.Tensor` object is also a valid input (which matches the actual behavior). In IDEs that use these annotations for type-checking (e.g. PyCharm) this leads to a warning `Expected type 'tuple',  got 'Tensor' instead` when a tensor is used as argument. The code works fine nevertheless.

## To Reproduce

Add the following script to a new PyCharm project and then run the code inspection tool (or look for the yellow highlights in the code).

```python
import torch

net = torch.nn.Identity()
x = torch.tensor([1, 2, 3])

# these two lines create warnings in PyCharm (i.e. example_inputs=x and args=x are highlighted in yellow
# and the code inspection lists the warnings "Expected type 'tuple',  got 'Tensor' instead")
torch.jit.trace(func=net, example_inputs=x)
torch.onnx.export(model=net, args=x, f="test.onnx")

# these two don't
torch.jit.trace(func=net, example_inputs=(x,))
torch.onnx.export(model=net, args=(x,), f="test2.onnx")
```

## Expected behavior

No warnings are produced for a `torch.Tensor` object as input.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0
 - OS (e.g., Linux): Microsoft Windows 10 Pro
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2.89 / v7.6.5.32
 - GPU models and configuration: NVIDIA RTX 2070 SUPER
 - Any other relevant information: Also happens with PyTorch 1.6.0a0+c73095e built from source

## Additional context

The expected behavior can be created by replacing `(tuple)` with `(tuple or torch.Tensor)` in the type annotation of the doc comments of the functions.
I could create a PR with these changes if desired.

cc @suo

**Comment by suo** [comment]
hey sorry for the delay @JBamberger, we'd be happy to take a PR with your proposed change :)

**Comment by JBamberger** [comment]
Hi, thanks for your response. I've created the PR.
