### ISSUE TITLE
C++ API: add `torch::cuda::manual_seed` like torch.cuda.manual_seed

### ISSUE THREAD

**Issue by kingaza** [pytorch/pytorch#40361]
## ❓ Questions and Help
if in pytorch
    `torch.manual_seed(0)`
then in libtorch
    `torch::manual_seed(0);`

so, in pytorch
```
    torch.cuda.manual_seed(0)
    torch.cuda.manual_seed_all(0)
```
in libtorch
`??`

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @yf225 @glaringlee

**Comment by zou3519** [comment]
I don't think this exists right now (correct me if I'm wrong, @glaringlee). It seems like a reasonable feature ask.

**Comment by glaringlee** [comment]
@kingaza @zou3519 
torch::manual_seed actually will do both CPU and GPU(if it is available).
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Context.h#L230

**Comment by kingaza** [comment]
got it.
thx

**Comment by glaringlee** [comment]
We should overload manual_seed() to support cpu or gpu only, this might be an onboarding task.
