### ISSUE TITLE
cuda context destroyed before Destroy()

### ISSUE THREAD

**Issue by 522730312** [pytorch/pytorch#40372]
// this is because of something dumb in the ordering of
// destruction. Sometimes atexit, the cuda context (or something)
// would already be destroyed by the time this gets destroyed. It
// happens in fbcode setting. @colesbury and @soumith decided to not destroy
// the handle as a workaround.
//   - Comments of @soumith copied from cuDNN handle pool implementation

Hi , I am reading code of ./aten/src/ATen/cuda/CublasHandlePool.cpp.  
The code-annotation has shown above is before  cusparseDestroy().
I wonder the fbcode setting is what setting and the ordering of destruction is mean what.
It is very good If you have some link or documents for me
@soumith   @colesbury

**Comment by zou3519** [comment]
Please direct any questions to our forums: https://discuss.pytorch.org/. We like to keep the issue tracker filled with issues and/or feature requests.
