### ISSUE TITLE
Feature request: allow to distribute load unevenly in DataParallel

### ISSUE THREAD

**Issue by kmike** [pytorch/pytorch#4037]
It is not uncommon to have 2 GPUs: one, beefy, for training, and another, cheaper one, for validation / experiments. In this setup DataParallel is not very helpful if you want to train a single model faster: a less performant GPU with less RAM can make things slower instead of speeding them up.

What do you think about adding an option to DataParallel to distribute load unevenly? It can be simply an option to change ratio of data sent to each GPU. 

See also (thanks @geffy for the links): 

* https://discuss.pytorch.org/t/single-node-multi-gpu-with-different-cards/1575 
* http://mxnet-tqchen.readthedocs.io/en/latest/how_to/multi_devices.html#advanced-usage

**Comment by apaszke** [comment]
That seems reasonable. Are you interested in sending a PR? I think we could add an argument to `DataParallel` that would divide the batches differently. It's probably a good idea to do it in a way `MXNet` does it (i.e. have multipliers instead of ratios).

**Comment by kmike** [comment]
Yes, I'm interested, but I'm not sure I'll have time for it this week. It is up for grabs if someone wants to implement it sooner :)

**Comment by daemon** [comment]
Bumping this issue.. any updates for this feature request?

**Comment by anands-repo** [comment]
I think this is already supported.

Notice the function scatter in pytorch/torch/nn/parallel/scatter_gather.py. If the argument to the forward function is a class object, the scatter function (and hence the DataParallel module) simply passes it along to each replicated model instance without splitting the data. This allows us to split the data in whichever way we like and pass it along, and DataParallel will honor our split. This is not tailor-made towards splitting data, but solves a more generic problem of how to do arbitrary things with the data when sending to a module wrapped within DataParallel. A rough example is below.

Assume that tensor0 and tensor1 are two uneven splits of a single batch. Then you could simply do this:

```
class Batch:
   def __init__(self, tensor0, tensor1):
       self. tensor0 = tensor0.cuda(device=torch.device('cuda:0'), non_blocking=True);
       self. tensor1 = tensor1.cuda(device=torch.device('cuda:1'), non_blocking=True);

class Model(torch.nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__();
        # Network definition goes here
        # self.network = torch.nn.Sequential( .. etc ..)

    def forward(self, batch):
        device = next(self.parameters()).get_device();
        tensor = getattr(batch, 'tensor%d' % device);
        return self.network(tensor);
```

Then a Model object can simply be wrapped within a DataParallel module, and objects of type Batch may be passed to it safely.
