### ISSUE TITLE
torch.onnx._export adds pad node of 10 dimension

### ISSUE THREAD

**Issue by kunalgoyal9** [pytorch/pytorch#40387]
## 🐛 Bug
I don't know if it's a bug or not.
I am trying to convert my slowfast torch model to onnx using `torch.onnx._export`. When I converted it to onnx and visualize that i got to know there is unknown pad in 10 dimensions.

![image](https://user-images.githubusercontent.com/21281457/85319941-ef141980-b4df-11ea-8ec2-e1dd388c4d58.png)

## To Reproduce

1.Take slow fast model from [here](https://github.com/facebookresearch/SlowFast)
2. Convert it using `torch.onnx._export(model, sample_input_tensor, "slow_fast.onnx", verbose=True, export_params=True, keep_initializers_as_inputs=True)`
3. load slow_fast model and visualize 362nd node.

## Expected behavior
Model without pad node

## Environment
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.15.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.0
[conda] blas                      1.0                         mkl  
[conda] cuda100                   1.0                           0    pytorch
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2019.1                      144  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.1            py37h0da4684_0    conda-forge
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torch                     1.3.1                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.4.2                    pypi_0    pypi

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@kunalgoyal9 - Could you distill this into a smaller repro, and also include your export code?
Also I suggest using the `torch.onnx.export` API and not the internal `_export` API.

**Comment by spandantiwari** [comment]
Please reopen this issue with repro steps.
