### ISSUE TITLE
Exponential distribution invalid parameter

### ISSUE THREAD

**Issue by oycz** [pytorch/pytorch#40386]
When I use `torch.distributions.exponential.Exponential`, like

```
lmda = torch.tensor(1.)  
e = torch.distributions.exponential.Exponential(lmda)
```

Then I optimize over `lmda`. If lmda becomes less than zero in the optimization, I can still call apis of `e` like `e.sample()`. But I think it is an unexpected behavior because parameter of exponential distribution can not less than zero, there should be something like an error message.

**Comment by alicanb** [comment]
Distributions have a `validate_args` argument (default is False). If you set it True, I think it will do what you're looking for.
