### ISSUE TITLE
mypy doesn't recognize torch functions that start with `_` 

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#40397]
## 🐛 Bug

torch functions that start with `_` aren't recognized by mypy. This causes the typechecker to choke on files that use functions that start with `_`. Said functions are generally for internal use only, so users won't run into this problem, but pytorch developers will.

## To Reproduce

Put the following in foo.py, then run the typechecker with `mypy foo.py`.
```
import torch
x = torch.randn(3, 3)
y = torch._softmax(x, -1, False)
print(y)
```

Now, `torch._softmax` exists. From some debugging, it looks like `torch/_C/_VariableFunctions.pyi` contains the following entry for `_softmax`, as well as all of the other torch functions. However, for some reason, the `_softmax` seems to be ignored. I'm not sure what is up here.
```
def _softmax(self: Tensor, dim: _int, half_to_float: _bool) -> Tensor: ...
```

## Environment

master

cc @ezyang @malfet @rgommers

**Comment by ezyang** [comment]
It's probably because of reexport semantics. Functions are made visible to mypy in `torch` module via these lines:

```
# Appease the type checker: it can't deal with direct setting of globals().
# Note that we will see "too many" functions when reexporting this way; there
# is not a good way to fix this problem.  Perhaps, try to redesign VariableFunctions
# so that this import is good enough
if False:
    from torch._C._VariableFunctions import *
```

My guess is that this excludes all functions with leading underscores.

**Comment by ezyang** [comment]
I don't know a good way to fix this problem

**Comment by diego-plan9** [comment]
> My guess is that this excludes all functions with leading underscores.

Inspired by your comment, I took a stab at it in #40499 - mostly an attempt to make use of `__all__` for also including the private functions for the purposes of mypy analysis (and keeping my fingers crossed about the potential side effects!).

**Comment by rgommers** [comment]
gh-40499 indeed fixed this, so closing. thanks @diego-plan9, all
