### ISSUE TITLE
libtorch_python.so: undefined symbol: PyThread_tss_create

### ISSUE THREAD

**Issue by ligonzheng** [pytorch/pytorch#40415]
## 🐛 Bug

Hello,
I made a c++ api  using libtorch and then warp it by pybind11. Then I use the api in python with pytorch used at the same time. A bug was occur : 
libtorch_python.so: undefined symbol: PyThread_tss_create
It seems like the libtorch is dependent on a set of dynamic libraries and pytorch also is dependent on another set of dynamic libraries. But when I used them at the same time, only one set of libraries would be used. Then something was wrong.
torch version : 1.5.0
python version : 3.6.9

**Comment by ligonzheng** [comment]
Oh,  Problem was solved by update the python to 3.7.

**Comment by a333klm** [comment]
If someone else encounters this especially when using torch with c++:
In my case I had the c++ library on my LD_LIBRARY_PATH. This led to the issue above when I used pytorch in python.
