### ISSUE TITLE
quantized ops don't support multithreading?

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#40473]
When I compare float/quantized resnet18, I found that time running quantized models does not change when I set num threads to different numbers(1, 2, 4), while float model runs faster after I set num threads to a larger number.

```
# Setting threads to 1 for comparison
torch.set_num_threads(1)
print('Running time for scripted float model:')
run_benchmark(saved_model_dir + scripted_float_model_file, data_loader_test)
print('Running time for graph mode quantized model:')
run_benchmark(saved_model_dir + graph_mode_model_file, data_loader_test)
print('Running time for eager mode quantized model:')
run_benchmark(saved_model_dir + eager_mode_model_file, data_loader_test);
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
@jerryzh168 Looks like this was filed 3 years ago. Is this still an issue?

**Comment by jerryzh168** [comment]
I think we can close
