### ISSUE TITLE
test_mem_leak is flaky on Windows jobs

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#40485]
## 🐛 Bug

```pytb
FAIL [6.916s]: test_mem_leak (__main__.TestProfiler_cuda)
Checks that there's no memory leak when using profiler with CUDA
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_profiler.py", line 42, in test_mem_leak
    self.assertTrue(max_diff < 100 * 1024)
AssertionError: False is not true
```

https://app.circleci.com/pipelines/github/pytorch/pytorch/184822/workflows/02c77496-bf42-4dc8-a0ab-735e7d717995/jobs/5989573/steps
https://app.circleci.com/pipelines/github/pytorch/pytorch/184822/workflows/02c77496-bf42-4dc8-a0ab-735e7d717995/jobs/5989573/steps

cc @ezyang @gchanan @zou3519 @mruberry @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
The following commits are likely the root cause for this.
- Increase shapes column length https://github.com/pytorch/pytorch/commit/b82bd654cc70b02e2d73ed2d4b16c796cf336fb6
- Destroy CUDA events after profiling https://github.com/pytorch/pytorch/commit/d8c384544e940933304c963d1877947cdb394f93
- Fix demangle 't' issue in profiler https://github.com/pytorch/pytorch/commit/a54bb4e907ad091a6ab836f9f5c46d297f44605a

cc @ilia-cher

**Comment by xwang233** [comment]
"Destroy CUDA events after profiling" is the PR that introduces the test. I believe this is an important bug fix (especially to the 1.6 release), so we should disable the flaky test on Windows instead of revert the PR.

**Comment by peterjc123** [comment]
Yes, I'm trying to disable it first. At the same time, we should also investigate why it is failing on Windows.

**Comment by ngimel** [comment]
Closing, there's a separate issue for disabling this test
