### ISSUE TITLE
Pytorch custom model downloader

### ISSUE THREAD

**Issue by atemysemicolon** [pytorch/pytorch#40501]
## 🚀 Feature
A simple and easy way to download custom pytorch models with private URLs (such as JFROG), to a custom path. To provide a consistent API for the same. As an additional feature, it would be great to auto-save to a url.
If need be, we should be able to implement a custom download/uploader.

```python
model_dict = torch.load_from_url(url, local_path, env_variables = 'JFROG_SERVER=xyz.com', custom_downloader=my_jfrog_downloader)
torch.save_to_url(model_dict, url, env_variables='', custom_uploader=my_jfrog_uploader)
```

## Motivation

There are lots of individuals and organizations that host their models on custom artefactories / google-drive / etc. Each one has to implement their own way to download the weights file, and often is done in an ugly fashion - bash scripts, curl requests, etc. Often, it might not be reproducable

## Pitch

With more and more people training their own custom models, and hosting it somewhere. It is essential to have a consistent api to simplify and standardise these tasks. At the moment, the community chooses to do it in it's own way, and there might be unnecessary dependencies.

## Alternatives

Bash scripts, python scripts with urllib, requests. 

## Additional context

None

cc @ailzhang

**Comment by gchanan** [comment]
I'm not sure what "auto-save to a url" means, can you clarify?

`torch.save` and `torch.load` already support file-like objects -- why is that not sufficient?

**Comment by ailzhang** [comment]
Also a `save_to_url` API requires to handle authentication inside the implementation, which might be tricky. 
Currently you can do it with `torch.save` and manually authenticate/upload, is the feature request to make them one step by `save_to_url`?

**Comment by atemysemicolon** [comment]
The feature request is primarily regarding `load_from_url`. `save_to_url` I understand might be way more complicated, and my bad  -  should've been made as a separate feature request

**Comment by atemysemicolon** [comment]
I just saw this : https://github.com/pytorch/pytorch/blob/b4db529352eca5b096c883c31c50adbb0c88c9aa/torch/hub.py#L427

Perhaps this is redundant then. Does it make sense to promote this function to work like `torch.load`?

**Comment by ailzhang** [comment]
@atemysemicolon Yep `load_state_dict_from_url` might does what you want. We currently want to keep `torch.load` separate from the `urllib` stuff which is well maintain in `load_state_dict_from_url`. Would this 2-step procedure work for your use case? 
If not, please feel free to update here about your feature request. Thanks!

**Comment by atemysemicolon** [comment]
It would work for my use case, thanks!
