### ISSUE TITLE
CppOp parameters retrieve in JIT

### ISSUE THREAD

**Issue by kitstar** [pytorch/pytorch#4051]
Hi guys,

I want to retrieve the CppOP(like ConvForward) parameters with jit trace. Is there any way to achieve that?

Thanks.

**Comment by ezyang** [comment]
No, but soon it won't matter as all these functions will be ported away from CppOp, making their parameters available the same way all other functions are.

On December 5, 2017 11:10:10 PM PST, Kit CHEN <notifications@github.com> wrote:
>Hi guys,
>
>I want to retrieve the CppOP(like ConvForward) parameters with jit
>trace. Is there any way to achieve that?
>
>Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytorch/pytorch/issues/4051

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
