### ISSUE TITLE
torch.cuda.is_availaible() isnt found, but all other torch.cuda stuff works

### ISSUE THREAD

**Issue by SamuelSchwienbacher** [pytorch/pytorch#40571]
this is the errormessage:
Traceback (most recent call last):
  File "models.py", line 13, in <module>
    if torch.cuda.is_availaible():
AttributeError: module 'torch.cuda' has no attribute 'is_availaible'

other methods like current_device work. Has this one been patched out or do i use it wrong ?

**Comment by Ajay95** [comment]
It's `torch.cuda.is_available() ` you have `torch.cuda.is_availaible()`
