### ISSUE TITLE
Parameterize _MultiProcessingDataLoaderIter's multiplier of prefetched items'

### ISSUE THREAD

**Issue by jeongukjae** [pytorch/pytorch#40604]
## 🚀 Feature

as is:

```python
# 20 workers will be launched and up to 40 items(2 * num_workers) will be prefetched. (in queue)
dataloader = DataLoader(dataset, batch_size=64, num_workers=20)
```

to be:

```python
# 20 workers will be launched and up to 80 items(4 * num_workers) will be prefetched. (in queue)
dataloader = DataLoader(dataset, batch_size=64, num_workers=20, max_prefetched_item=80)
# or
# dataloader = DataLoader(dataset, batch_size=64, num_workers=20, worker_factor=4)
```

## Motivation

https://github.com/pytorch/pytorch/blob/ac79c874cefee2f8bc1605eed9a924d80c0b3542/torch/utils/data/dataloader.py#L754

I want to preload more data but use only small number of workers.

## Pitch

Parameterize _MultiProcessingDataLoaderIter's multiplier or the number of prefetched items'.

**Comment by yl-to** [comment]
Will look into this and try to create a PR.
