### ISSUE TITLE
The impact of different pytorch versions on the same model

### ISSUE THREAD

**Issue by deepmeng** [pytorch/pytorch#40607]
1. If we use different versions of PyTorch to train the same model respectively, is there different performance between the two models?
2. If we use pyTorch V1.1 load the well-trained model under pyTorch V1.0 or use pyTorch V1.0 load the well-trained model under pyTorch V1.1, is there any influence on the prediction result?

**Comment by izdeby** [comment]
Please, use our [forums](https://discuss.pytorch.org/) for questions.
