### ISSUE TITLE
is_available and device_count does not update after change of CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by Spenhouet** [pytorch/pytorch#40618]
## 🐛 Bug

When `torch.cuda.is_available()` was already called when a GPU was available and `CUDA_VISIBLE_DEVICES` was changed afterwards, then `is_available` does not update.

## To Reproduce

Running the following:

```
CUDA_VISIBLE_DEVICES=1 python3.7 -c "import torch; import os; os.environ['CUDA_VISIBLE_DEVICES']=''; print(torch.cuda.is_available()); print(torch.cuda.device_count())"
```

gives the expected out:

> False
> 0

But running the following:

```
CUDA_VISIBLE_DEVICES=1 python3.7 -c "import torch; import os; print(torch.cuda.is_available()); print(torch.cuda.device_count()); os.environ['CUDA_VISIBLE_DEVICES']=''; print(torch.cuda.is_available()); print(torch.cuda.device_count())"
```

gives the unexpected (wrong) output:

> True
> 1
> True
> 1

## Expected behavior

The expected output should be:

> True
> 1
> False
> 0

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: version 2.8.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 440.82
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.4.0
[conda] Could not collect

## Additional context

I need this for unittests to work.

**Comment by SsnL** [comment]
Setting `CUDA_VISIBLE_DEVICES` only works before the program make any CUDA calls.

**Comment by Spenhouet** [comment]
Good to know. I did not expect that. Thanks.
