### ISSUE TITLE
Negative mask unsupport (ByteTensor) in Pytorch 0.3

### ISSUE THREAD

**Issue by jiesutd** [pytorch/pytorch#4066]
When I use the negative mask like : 

`mask = torch.autograd.Variable(torch.zeros((3,4 ))).byte()`
`mask =  1- mask `
Pytorch 0.3 shows "RuntimeError: neg is not implemented for type torch.ByteTensor"

It is also observed in Pytorch 0.2, but can be solved in Pytorch 0.2 using:
`mask =  1 + (-1) *mask`

While in Pytorch 0.3, the previous solution gives the "RuntimeError: value cannot be converted to type uint8_t without overflow: -1".

It is caused by the ByteTensor does not support negative operation. So I use  `mask = (1-mask.long()).byte()` to solve the problem, but it is not elegant.

**Comment by bheinzerling** [comment]
If you don't need to do this on variables, you can use the bitwise NOT operator `~` on **plain** ByteTensors:

```Python
>>> mask = torch.zeros((3, 4)).byte()
>>> ~mask
1 1 1 1
1 1 1 1
1 1 1 1
[torch.ByteTensor of size 3x4]

```
But the NOT operator doesn't work on Variables.

All other bitwise operators  (OR, XOR, AND, bitshift) work, on both ByteTensors and Variables.
