### ISSUE TITLE
Conv3d is slower than Conv2d for tensors of same data size

### ISSUE THREAD

**Issue by MJITG** [pytorch/pytorch#40664]
## ❓ Questions and Help
For a tensor of the same size, Conv2d is much faster than Conv3d. For example, when I merged the depth dimension into the channel dimension, which looks like [B, C, D, H, W] ---> [B, C*D, H, W], and changed Conv3d to Conv2d, my model ran faster. I wonder how these two types of convolutions work differently? Or what should I refer to?
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @VitalyFedyunin @ngimel

**Comment by Geeks-Sid** [comment]
2D Convolutions have less number of parameters and has less area to cover in general compared to 3D so the difference usually does exists,

**Comment by MJITG** [comment]
@Geeks-Sid In the case mentioned above, you can see there exist more params covering a wider area in conv2d compared to conv3d. In detail, conv2d has [C*D, C*D, 3, 3] kernel size while conv3d has [C, C, 3, 3, 3] kernel size. If D > 3, conv2d's computational complexity surpassed conv3d's.

**Comment by MJITG** [comment]
@soumith Could you plz help me figure it out?

**Comment by Geeks-Sid** [comment]
@MJITG Hi, This blog is written wonderfully, could you take a look [here](https://towardsdatascience.com/2d-or-3d-a-simple-comparison-of-convolutional-neural-networks-for-automatic-segmentation-of-625308f52aa7)?

**Comment by ngimel** [comment]
Please use forums for general questions.
