### ISSUE TITLE
torch.jit.save create zip file in linux

### ISSUE THREAD

**Issue by starskabi** [pytorch/pytorch#40678]
it's very strange ,when i used "torch.save",it could create a .pt file . (in  ubuntu18.04),when i used "torch.jit.save ", it created zip file ,but when i copy them to the windows ,they become .pt again.

a simple example
`
import torch
import torchvision

model = torchvision.models.resnet18()

example = torch.rand(1, 3, 224, 224)

.
traced_script_module = torch.jit.trace(model, example)

torch.jit.save(traced_script_module, '1.pt')

`
then i open file, "1.pt" became zip, "1.pt"became a name

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
(assuming you are using latest pytorch)

.pt file is indeed of zip-file format. You can use unzip to open it in Ubuntu as well.

**Comment by starskabi** [comment]
Thanks for your reply !
but i need to load it in C++  (my IDE is kdevelop and pycharm)

because i need to use this model to predict result(It links to some third-party libraries such as octomap )
should i uninstall my pytorch and reinstall it?
Thank you very much!!

**Comment by gmagogsfm** [comment]
I don't think you need to reinstall pytorch. Do you see any error during model loading?

Here is a tutorial that should be relevant for your case:
https://pytorch.org/tutorials/advanced/cpp_export.html

**Comment by starskabi** [comment]
Thanks for your advise !
but i still can not solve  this problem

here is part of my code
`
    if (argc != 2) 
    {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
    }
    
   torch::jit::script::Module module;
    try
    {
    module = torch::jit::load(argv[1]);
    }
    catch (const c10::Error& e)
    {
    std::cerr << "error loading the model\n";
    return -1;
    
    }
    
    std::cout << "ok\n";
`
if i load the zipfile it shows 
`
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:137] . PytorchStreamReader failed closing reader: file not found
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7fbf7709ce06 in /home/starskabi/libtorch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::valid(char const*) + 0x8d (0x7fbf78fe764d in /home/starskabi/libtorch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::~PyTorchStreamReader() + 0x1b (0x7fbf78fe768b in /home/starskabi/libtorch/lib/libtorch.so)
frame #3: <unknown function> + 0x2d98efc (0x7fbf7a049efc in /home/starskabi/libtorch/lib/libtorch.so)
frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x23f (0x7fbf7a050e1f in /home/starskabi/libtorch/lib/libtorch.so)
frame #5: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x75 (0x7fbf7a050f85 in /home/starskabi/libtorch/lib/libtorch.so)
frame #6: <unknown function> + 0xa58d (0x555a9674358d in ./lastversion)
frame #7: __libc_start_main + 0xe7 (0x7fbf7635bb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0x8f5a (0x555a96741f5a in ./lastversion)

`


lastversion is a cppfile
if i unzip it , it still can not be loaded
it shows
`error loading the model`

**Comment by gmagogsfm** [comment]
From the stack trace alone, it looks like it can't find the file. Do you mind sharing the exact command you ran? and show content of the folder, in which your saved model resides?

**Comment by starskabi** [comment]
Thanks for your reply again
i am sorry to tell you that my libtorch version is 1.2.0,and my pytorch version is 151 and another environment  is  131,i think maybe it causes my problem

my content of the folder is

/media/starskabi/LJY/1.png

my command is
./lastversion trace_model1.pt
(trace_model1.pt is a zip file)
it shows

terminate called after throwing an instance of 'c10::Error'
what(): [enforce fail at inline_container.cc:137] . PytorchStreamReader failed closing reader: file not found
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, void const*) + 0x76 (0x7fbf7709ce06 in /home/starskabi/libtorch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::valid(char const*) + 0x8d (0x7fbf78fe764d in /home/starskabi/libtorch/lib/libtorch.so)...............................................



(after i unzip it )
my another command is
./lastversion trace_model1
it shows

error loading the model

**Comment by starskabi** [comment]
![1](https://user-images.githubusercontent.com/65332547/85970149-1eed8080-b9fc-11ea-8929-982adf9b1860.png)

**Comment by starskabi** [comment]
sorry to bother you again 
i changed my pytorch version to 120 and my libtorch to 120
and it works 
my problem has been solved 


thanks for your reply!
wish you good luck!

**Comment by gmagogsfm** [comment]
Glad to know it works now : )
