### ISSUE TITLE
Gradients of a mini-batch of images

### ISSUE THREAD

**Issue by hyunjaecho94** [pytorch/pytorch#40674]
I am trying to get the gradients of a mini-batch of image like below:
```
images.grad.data
```

but I get an error `AttributeError: 'NoneType' object has no attribute 'data'`. Why is `images.grad` None?

I've tried `img_variable = Variable(images, requires_grad=True)` and `images.requires_grad = True` but no success.

**Comment by mrshenli** [comment]
Hey @hyunjaecho94 

The `.grad` field is set during the backward pass if they are not present. So if the `img_variable` is used during the forward pass, you should be able to access its `.grad` field after the backward pass.

**Comment by mrshenli** [comment]
Please use the [forum](https://discuss.pytorch.org/) for questions. I am closing this issue for now, but please feel free to open an new issue if this turns out to be a bug report or feature request.
