### ISSUE TITLE
Can this operation change the value of grad_input?

### ISSUE THREAD

**Issue by nicksunyang** [pytorch/pytorch#40683]
Tensor grad_input_n = grad_input.select(0, elt);

            col2hvol<scalar_t, dim>(
                stream,
                columns.data_ptr<scalar_t>(),
                nInputPlane,
                input_size,
                output_size,
                kernel_size,
                stride_size,
                pad_size,
                dilation_size,
                grad_input_n.data_ptr<scalar_t>());
          }
file "pytorch\aten\src\ATen\native\cuda\NaiveDilatedConvolution.cu"

**Comment by mrshenli** [comment]
Hey @nicksunyang, could you please use the [forum](https://discuss.pytorch.org/) for questions? I am closing this issue for now, but please feel free to open a new one if this turns out to be a bug report or feature request. Thanks!
