### ISSUE TITLE
torch.cuda.is_available() is False

### ISSUE THREAD

**Issue by ningdez** [pytorch/pytorch#40682]
PyTorch version:1.5.0+cu101
My cuda version is 10.1 and the nvidia driver version is 442.92. I don't know why torch.cuda.is_available() always return false? I try to change pytorch version to 1.4.0+cu101, and change nvidia driver version to 451 or 426, but the problem still exist.
Thanks a lot.

outptu of python -m torch.utils.collect_env is
> Collecting`environment information...
> PyTorch version: 1.5.0+cu101
> Is debug build: No
> CUDA used to build PyTorch: 10.1
> 
> OS: Microsoft Windows Server 2019 Standard
> GCC version: (MinGW.org GCC Build-20200227-1) 9.2.0
> CMake version: Could not collect
> 
> Python version: 3.7
> Is CUDA available: Yes
> CUDA runtime version: 10.1.243
> GPU models and configuration:
> GPU 0: TITAN RTX
> GPU 1: TITAN RTX
> 
> Nvidia driver version: 442.92
> cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
> 
> Versions of relevant libraries:
> [pip] numpy==1.19.0
> [pip] numpydoc==0.9.1
> [pip] torch==1.5.0+cu101
> [pip] torchvision==0.6.0+cu101
> [conda] blas                      1.0                         mkl
> [conda] mkl                       2019.4                      245
> [conda] mkl-service               2.3.0            py37hb782905_0
> [conda] mkl_fft                   1.0.14           py37h14836fe_0
> [conda] mkl_random                1.1.0            py37h675688f_0
> [conda] torch                     1.5.0+cu101              pypi_0    pypi
> [conda] torchvision               0.6.0+cu101              pypi_0    pypi
>

**Comment by peterjc123** [comment]
> Is CUDA available: Yes

But when you run `python -m torch.utils.collect_env`, it reports that `torch.cuda.is_available()` is True.

**Comment by ningdez** [comment]
OK, I got it. Thank you very much.
