### ISSUE TITLE
why the value of print（model.state_dict().items()）different every time？

### ISSUE THREAD

**Issue by Wenbin94** [pytorch/pytorch#40693]
the model weight after  quantification 。
code：
```
encoder= torch.jit.load('/home/luowenbin/vstqm/QAT_model/seg_v7_2202.pt')#encoder模型
keys=[]
for k,v in encoder.state_dict().items():
    if v.shape:
        keys.append(k)
    print(k,'\n',v)
```
Run twice ，Partial result screenshot：

![20200629163939](https://user-images.githubusercontent.com/50608741/85992305-4279f080-ba27-11ea-953e-3afb9846ee9e.png)
![20200629164026](https://user-images.githubusercontent.com/50608741/85992310-4443b400-ba27-11ea-97d7-582e6510f2e7.png)

cc @suo @gmagogsfm @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by mrshenli** [comment]
Hey @Wenbin94 

I tried with simple linear layers but cannot reproduce it. Could you please share a min reproduce-able exmaple?

```python
import torch

class ToyModel(torch.jit.ScriptModule):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(5, 5)
        self.l2 = torch.nn.Linear(5, 5)

    @torch.jit.script_method
    def forward(self, x):
        # type: (Tensor) -> Tensor
        return self.l1(self.l2(x))

model = ToyModel()
torch.jit.save(model, "tmp.pt")
loaded_model = torch.jit.load("tmp.pt")

print("============== 1st time ==================")
for k,v in loaded_model.state_dict().items():
    print(k,'\n',v)

loaded_model = torch.jit.load("tmp.pt")

print("============== 2nd time ==================")
for k,v in loaded_model.state_dict().items():
    print(k,'\n',v)
```

Outputs are:

```
============== 1st time ==================
l1.weight 
 tensor([[ 0.3701,  0.2520,  0.2035, -0.0360, -0.2089],
        [ 0.1070, -0.0112, -0.0208, -0.0010, -0.3826],
        [ 0.3362,  0.0029, -0.1520,  0.3353, -0.2238],
        [ 0.2524, -0.0348,  0.3138,  0.3516,  0.2696],
        [-0.2201, -0.2724, -0.0639,  0.3095, -0.2026]])
l1.bias 
 tensor([-0.2203, -0.0935,  0.2656,  0.0842,  0.1465])
l2.weight 
 tensor([[-0.1403,  0.2467, -0.1145,  0.0531, -0.3791],
        [-0.2576,  0.2757,  0.4321,  0.0907,  0.3012],
        [ 0.0645,  0.3533, -0.0789,  0.1702,  0.0034],
        [-0.0451, -0.2190, -0.1453, -0.1630, -0.2193],
        [ 0.1452, -0.1812,  0.2365, -0.2464, -0.1026]])
l2.bias 
 tensor([ 0.3744, -0.1177, -0.3584, -0.1200,  0.3215])
============== 2nd time ==================
l1.weight 
 tensor([[ 0.3701,  0.2520,  0.2035, -0.0360, -0.2089],
        [ 0.1070, -0.0112, -0.0208, -0.0010, -0.3826],
        [ 0.3362,  0.0029, -0.1520,  0.3353, -0.2238],
        [ 0.2524, -0.0348,  0.3138,  0.3516,  0.2696],
        [-0.2201, -0.2724, -0.0639,  0.3095, -0.2026]])
l1.bias 
 tensor([-0.2203, -0.0935,  0.2656,  0.0842,  0.1465])
l2.weight 
 tensor([[-0.1403,  0.2467, -0.1145,  0.0531, -0.3791],
        [-0.2576,  0.2757,  0.4321,  0.0907,  0.3012],
        [ 0.0645,  0.3533, -0.0789,  0.1702,  0.0034],
        [-0.0451, -0.2190, -0.1453, -0.1630, -0.2193],
        [ 0.1452, -0.1812,  0.2365, -0.2464, -0.1026]])
l2.bias 
 tensor([ 0.3744, -0.1177, -0.3584, -0.1200,  0.3215])
```

**Comment by SsnL** [comment]
I think quantization must play a role in this issue...

**Comment by Wenbin94** [comment]
> 嘿@ Wenbin94
> 
> 我尝试使用简单的线性层，但无法复制它。您能不能分享一个可复制的小礼物呢？
> 
> ```python
> 进口 火炬
> 
> 类 ToyModel（火炬。JIT。ScriptModule）：
>      高清 __init__（个体经营）：
>          超（）。__init__（）
>          自我。l1  =  火炬。nn。线性（5，5）
>          自我。l2  =  火炬。nn。线性（5，5）
> 
>     @ 火炬。准时。script_method
>      def  forward（self，x）：
>          ＃类型：（Tensor）-> Tensor 
>         return  self。L1（自我。L2（X））
> 
> 模型 =  ToyModel（）
>  火炬。准时。保存（模型，“ tmp.pt”）
>  loaded_model  =  火炬。准时。加载（“ tmp.pt”）
> 
> 打印（“==============第1次==================” ）
>  为 ķ，v  在 loaded_model。state_dict（）。items（）：
>      打印（k，' \ n '，v）
> 
> loading_model  =  火炬。准时。加载（“ tmp.pt”）
> 
> 打印（“==============第二时间==================” ）
>  为 ķ，v  在 loaded_model。state_dict（）。items（）：
>      打印（k，' \ n '，v）
> ```
> 
> 输出为：
> 
> ```
> ============== 1st time ==================
> l1.weight 
>  tensor([[ 0.3701,  0.2520,  0.2035, -0.0360, -0.2089],
>         [ 0.1070, -0.0112, -0.0208, -0.0010, -0.3826],
>         [ 0.3362,  0.0029, -0.1520,  0.3353, -0.2238],
>         [ 0.2524, -0.0348,  0.3138,  0.3516,  0.2696],
>         [-0.2201, -0.2724, -0.0639,  0.3095, -0.2026]])
> l1.bias 
>  tensor([-0.2203, -0.0935,  0.2656,  0.0842,  0.1465])
> l2.weight 
>  tensor([[-0.1403,  0.2467, -0.1145,  0.0531, -0.3791],
>         [-0.2576,  0.2757,  0.4321,  0.0907,  0.3012],
>         [ 0.0645,  0.3533, -0.0789,  0.1702,  0.0034],
>         [-0.0451, -0.2190, -0.1453, -0.1630, -0.2193],
>         [ 0.1452, -0.1812,  0.2365, -0.2464, -0.1026]])
> l2.bias 
>  tensor([ 0.3744, -0.1177, -0.3584, -0.1200,  0.3215])
> ============== 2nd time ==================
> l1.weight 
>  tensor([[ 0.3701,  0.2520,  0.2035, -0.0360, -0.2089],
>         [ 0.1070, -0.0112, -0.0208, -0.0010, -0.3826],
>         [ 0.3362,  0.0029, -0.1520,  0.3353, -0.2238],
>         [ 0.2524, -0.0348,  0.3138,  0.3516,  0.2696],
>         [-0.2201, -0.2724, -0.0639,  0.3095, -0.2026]])
> l1.bias 
>  tensor([-0.2203, -0.0935,  0.2656,  0.0842,  0.1465])
> l2.weight 
>  tensor([[-0.1403,  0.2467, -0.1145,  0.0531, -0.3791],
>         [-0.2576,  0.2757,  0.4321,  0.0907,  0.3012],
>         [ 0.0645,  0.3533, -0.0789,  0.1702,  0.0034],
>         [-0.0451, -0.2190, -0.1453, -0.1630, -0.2193],
>         [ 0.1452, -0.1812,  0.2365, -0.2464, -0.1026]])
> l2.bias 
>  tensor([ 0.3744, -0.1177, -0.3584, -0.1200,  0.3215])
> ```

```
import torchvision.models.quantization as models
import torch
from torch import nn
import torch.optim as optim
from torch.quantization import convert
model_fe = models.resnet18(pretrained=True, progress=True, quantize=True)
num_ftrs = model_fe.fc.in_features
def create_combined_model(model_fe):
    # Step 1. Isolate the feature extractor.
    model_fe_features = nn.Sequential(
    model_fe.quant,  # Quantize the input
    model_fe.conv1,
    model_fe.bn1,
    model_fe.relu,
    model_fe.maxpool,
    model_fe.layer1,
    model_fe.layer2,
    model_fe.layer3,
    model_fe.layer4,
    model_fe.avgpool,
    model_fe.dequant,  # Dequantize the output
    )

    # Step 2. Create a new "head"
    new_head = nn.Sequential(
    nn.Dropout(p=0.5),
    nn.Linear(num_ftrs, 2),
    )

    # Step 3. Combine, and don't forget the quant stubs.
    new_model = nn.Sequential(
    model_fe_features,
    nn.Flatten(1),
    new_head,
    )
    return new_model
new_model = create_combined_model(model_fe)
new_model.cpu()
convert(new_model, inplace=True)
torch.jit.script(new_model).save("tmp.pt")
loaded_model = torch.jit.load("tmp.pt")
print("============== 1st time ==================")
c=0
for k,v in loaded_model.state_dict().items():
    if c==10:
        print(k,'\n',v)
    c=c+1

loaded_model = torch.jit.load("tmp.pt")
c1=0
print("============== 2nd time ==================")
for k,v in loaded_model.state_dict().items():
    if c1==10 :
        print(k,'\n',v)
    c1=c1+1
```
`============== 1st time ==================
0.6.1.conv1._packed_params 
 tensor([ 48, 130,  39,  84,  16,   2,   0,   0,   1,  27, 208,  81,  16,   2,
          0,   0,  80, 172,  91,  79,  16,   2,   0,   0, 128,  57, 195,  89,
         16,   2,   0,   0, 128,  59, 195,  89,  16,   2,   0,   0, 128,  59,
        195,  89,  16,   2,   0,   0,  96, 151, 232,  86,  16,   2,   0,   0,
        112, 151, 232,  86,  16,   2,   0,   0, 112, 151, 232,  86,  16,   2,
          0,   0, 208,  34, 195,  89,  16,   2,   0,   0, 208,  36, 195,  89,
         16,   2,   0,   0, 208,  36, 195,  89,  16,   2,   0,   0,  96,  86,
        195,  89,  16,   2,   0,   0,  96,  88, 195,  89,  16,   2,   0,   0,
         96,  88, 195,  89,  16,   2,   0,   0,   1,  27, 208,  81,  16,   2,
          0,   0], dtype=torch.uint8)
============== 2nd time ==================
0.6.1.conv1._packed_params 
 tensor([112, 226,  39,  84,  16,   2,   0,   0,   1, 107,  34,  82,  16,   2,
          0,   0,  32, 203, 129,  90,  16,   2,   0,   0, 240,  95, 162,  84,
         16,   2,   0,   0, 240,  97, 162,  84,  16,   2,   0,   0, 240,  97,
        162,  84,  16,   2,   0,   0, 160, 143,  34,  82,  16,   2,   0,   0,
        176, 143,  34,  82,  16,   2,   0,   0, 176, 143,  34,  82,  16,   2,
          0,   0, 192,  89, 162,  84,  16,   2,   0,   0, 192,  91, 162,  84,
         16,   2,   0,   0, 192,  91, 162,  84,  16,   2,   0,   0,   0,  98,
        162,  84,  16,   2,   0,   0,   0, 100, 162,  84,  16,   2,   0,   0,
          0, 100, 162,  84,  16,   2,   0,   0,   1, 109,  34,  82,  16,   2,
          0,   0], dtype=torch.uint8)`

**Comment by z-a-f** [comment]
When you use quantization the weights are packed and stored in the `_packed_params`. The packed structure is a container that is only supposed to be used by `fbgemm` and `qnnpack`, and it stores information about pointers to the memory location of the raw weight data. That means that if you run it multiple times, it is very likely the "representation" of the `_packed_tensor` will be different. To access the weights you need to use the methods `weight_bias` or `weight` in the conv/linear.

BTW, when you store the quantized model the packed weight is unpacked.

**Comment by Wenbin94** [comment]
> When you use quantization the weights are packed and stored in the `_packed_params`. The packed structure is a container that is only supposed to be used by `fbgemm` and `qnnpack`, and it stores information about pointers to the memory location of the raw weight data. That means that if you run it multiple times, it is very likely the "representation" of the `_packed_tensor` will be different. To access the weights you need to use the methods `weight_bias` or `weight` in the conv/linear.
> 
> BTW, when you store the quantized model the packed weight is unpacked.

thank  you
