### ISSUE TITLE
"masked_fill_" fails to handle infinite values

### ISSUE THREAD

**Issue by hitvoice** [pytorch/pytorch#4069]
Example code:
```python
import torch
from torch.autograd import Variable

# OK for FloatTensor
x = torch.randn(1, 5)
mask = torch.eq(x, 0)
x.masked_fill_(mask, 0)
x.masked_fill_(mask, float('-inf'))

# fails when called by Variable
x = Variable(x)
mask = torch.eq(x, 0)
x.masked_fill_(mask, 0)
x.masked_fill_(mask, float('-inf'))
```
And the result is:
```
Traceback (most recent call last):
  File "xxx.py", line 14, in <module>
    x.masked_fill_(mask, float('-inf'))
RuntimeError: value cannot be converted to type float without overflow: -inf
```
which is not expected.

Testing environment:
- pytorch: 0.3.0.post4
- python: 3.6.1
- platform: Linux-4.10.0-41-generic-x86_64-with-debian-stretch-sid (Ubuntu 16.04)

**Comment by zou3519** [comment]
This works for me on master without any errors. It was probably fixed somewhere down the line.

![image](https://user-images.githubusercontent.com/5652049/33776134-75a2d3d6-dc0e-11e7-9655-d4411b1ffdd7.png)

**Comment by hitvoice** [comment]
Install from the master branch and indeed, the problem is gone. Thanks!
