### ISSUE TITLE
Training on top of an already existing model in C++

### ISSUE THREAD

**Issue by Nitya05** [pytorch/pytorch#40695]
I am saving my model in Python using torch.jit.trace(model, example), and using this model in C++ for inference purpose. Is there a method by which I can train on top of this existing model in C++ itself? Or can it be done by Annotation instead of Tracing?

**Comment by mrshenli** [comment]
Hey @Nitya05, could you please use the [forum](https://discuss.pytorch.org/) for questions? I am closing this issue for now, but please feel free to open a new one if this turns out to be a bug report or feature request. Thanks!
