### ISSUE TITLE
Implement autograd functions for c10d communication operations

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#40702]
This is inspired by #40690 and other requests we saw before. Applications might want to use c10d operations (e.g., `all_gather`, `all_reduce`) in the forward pass and expect they been linked in the same autograd graph. This would require implementing autograd functions for c10d operations as what's done for `scatter` and `gather` in [nn/parallel/_functions.py](https://github.com/pytorch/pytorch/blob/b35cdc5200af963e410c0a25400fd07f30b89bca/torch/nn/parallel/_functions.py).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse

**Comment by jiayisuse** [comment]
That would be awesome if we can generalize autograd functions for c10d operations. TSC folks are manually implementing backward grad propagation for alltoall and reduce_scatter

**Comment by emcastillo** [comment]
We have implemented this in [chainermn](https://github.com/chainer/chainer/blob/master/chainermn/functions/collective_communication.py)
I will try to make a port for these :)

**Comment by chenyangyu1988** [comment]
@emcastillo Can you share what comm do you use to support cross host communication? We currently use NCCL as backend and it doesn't support gather and scatter at this moment.

**Comment by emcastillo** [comment]
Sorry for the late reply, 
I think  you can implement gather/scatter yourself using nccl as it is described in 

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/p2p.html
