### ISSUE TITLE
`.dim()` is not handled properly by the autograd codegen

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#40701]
Having `self.dim()` in the autograd codegen currently saves `self` while only an int could be saved.
This is used in the repeat backward formula right now and can cause unexpected behavior (see forum [here](https://discuss.pytorch.org/t/expand-vs-repeat-used-within-backward-raise-error/87303))

A new special case can be added here: https://github.com/pytorch/pytorch/blob/b35cdc5200af963e410c0a25400fd07f30b89bca/tools/autograd/load_derivatives.py#L276-L313 to handle it.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @VitalyFedyunin @ngimel

**Comment by ezyang** [comment]
Should be pretty easy to fix.
