### ISSUE TITLE
make_grid function description is puzzling

### ISSUE THREAD

**Issue by oneTaken** [pytorch/pytorch#4070]
`make_grid` doc is [here](http://pytorch.org/docs/0.3.0/torchvision/utils.html#torchvision.utils.make_grid), 
Should `nrow` means the number of row?
But in the code, it means the number of column.
I got the counterintuitive result when I saved the image.

**Comment by apaszke** [comment]
This is unrelated to the core repo. Please open an issue in pytorch/vision.
