### ISSUE TITLE
Einsum and BMM x50 slower on K80 CUDA + Half vs just CUDA

### ISSUE THREAD

**Issue by Laksh1997** [pytorch/pytorch#40767]
## 🐛 Bug

Title says it all.

## To Reproduce

```python
import torch
import torch.nn as nn

W = torch.randn(500, 10, 100, requires_grad=True).cuda().half()
x = torch.randn(32, 500, 10).cuda().half() 
torch.cuda.synchronize()

%%timeit
torch.bmm(x.transpose(0, 1), W).transpose(0, 1); torch.cuda.synchronize()

%%timeit
torch.einsum("bij, ijl -> bil", x, W); torch.cuda.synchronize()


W = torch.randn(500, 10, 100, requires_grad=True).cuda()
x = torch.randn(32, 500, 10).cuda()
torch.cuda.synchronize()

%%timeit
torch.bmm(x.transpose(0, 1), W).transpose(0, 1); torch.cuda.synchronize()

%%timeit
torch.einsum("bij, ijl -> bil", x, W); torch.cuda.synchronize()

```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): Pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by colesbury** [comment]
The K80 doesn't have hardware support for accelerated half-precision operations. I think this is expected but cc @ngimel in case I'm missing something.
