### ISSUE TITLE
pca_lowrank memory allocation

### ISSUE THREAD

**Issue by eitanrich** [pytorch/pytorch#40768]
The code below allocates a large amount of memory (same size as the input A) in order to subtract the mean.
This can probably be avoided...
https://github.com/pytorch/pytorch/blob/b9cca4b186797b4ccdc12197b3b71db94d8e2297/torch/_lowrank.py#L273

cc @VitalyFedyunin @ngimel

**Comment by colesbury** [comment]
We would welcome a patch to improve the performance of pca_lowrank

**Comment by ngimel** [comment]
Indeed, if I'm reading the code right what you want here is C expanded to the original A shape to compute (A-C)? You can just right it directly, C would be implicitly broadcast by subtraction operation. There no need to create ones_m1 matrix and compute matmul.

**Comment by eitanrich** [comment]
Thanks for the quick response. Passing A-C to _svd_lowrank works, but I think it still allocates new storage for A-C, which can be very large (same size as the input A). I tried avoiding this and use the svd_lowrank argument M (mean) instead:
_svd_lowrank(A, q, niter=niter, M=C), but I get some matmul errors in:
https://github.com/pytorch/pytorch/blob/b9cca4b186797b4ccdc12197b3b71db94d8e2297/torch/_lowrank.py#L79
I think svd_lowrank does not handle the optional M argument properly.

**Comment by pearu** [comment]
> I get some matmul errors in ..

What are the errors? Can you provide a small example as a reproducer?

**Comment by pearu** [comment]
I think I understand why matmul errors on `M=C` input:
The input `M` has to be the same size as `A` but `C` is not. The expression `A - M` relies on broadcasting but broadcasting is not effective within `matmul`.

**Comment by pearu** [comment]
Here's a stride-trick idea that saves memory for non-batch cases:

Define `M = C.as_strided(A.shape, (0, 1))` and then use `_svd_lowrank(A, q, niter=niter, M=M)`.

**Comment by pearu** [comment]
The stride trick can be generalized to batch cases. The suggested change is submitted as https://github.com/pytorch/pytorch/pull/40853#discussion_r448975081

**Comment by eitanrich** [comment]
The following code reproduces the error:

```
import torch
A = torch.ones([1, 100, 10], dtype=torch.float32).cuda()
torch.pca_lowrank(A, 5, center=True)
# The same error is caused by the below:
torch.svd_lowrank(A, 5, M=A.mean(dim=1, keepdim=True))
```
I think the problem with the line below is that matmul doesn't support broadcasting the singleton dimension in M or M_H.
https://github.com/pytorch/pytorch/blob/b9cca4b186797b4ccdc12197b3b71db94d8e2297/torch/_lowrank.py#L79

A simple solution that worked for me is changing the above (and two other similar lines) line to:

```
(Q, _) = matmul(A_H-M_H, Q).qr()
```
I'm not sure why two separates matmul operations are better.
The stride trick seems like a good option too.  Perhaps M.expand(... can be used as well.

BTW As an efficient workaround I subtracted the mean from my original data A before calling pca_lowrank,, since I don't mind corrupting it.

**Comment by pearu** [comment]
> A simple solution that worked for me is changing the above (and two other similar lines) line to:
> 
> ```
> (Q, _) = matmul(A_H-M_H, Q).qr()
> ```

This would be even worse because this would generate more large temporary tensors (`A_H - M_H`) during the iteration.
Notice that `Q` has small number of columns so that `matmul(A_H, Q) - matmul(M_H, Q)` is very memory efficient compared to `matmul(A_H - M_H, Q)`.

**Comment by ngimel** [comment]
2 matmuls are more memory efficient (unless M_H is blown up in matmul, I'm not sure), but typically would be less compute-efficient, depending on the sizes. If you don't backprop through pca_lowrank and don't otherwise need A_H, you can compute A_H-M_H inplace, which will give you the best of both worlds - a single matmul and no additional memory.

**Comment by pearu** [comment]
If the input to pca_lowrank is already centered, then use `center=False` that eliminates dealing with `M` in the svd algorithm.

**Comment by ngimel** [comment]
If batched (3d) matrices go into matmul, their expanded form is materialized, so it's expensive in terms of memory:
https://github.com/pytorch/pytorch/blob/5db5a0f2bb6b5bfa1822fd8c4e1ad67af88cab00/aten/src/ATen/native/LinearAlgebra.cpp#L482-L483. 2d tensors going to matmul call at::mm, and ultimately also materialize expanded tensor https://github.com/Quansight/pytorch/blob/0154de5ccf32cf37c611d11a7cb5976300befb9d/aten/src/ATen/native/cuda/LinearAlgebra.cu#L46, so `matmul(M_H, Q)` in any case allocates expanded tensor to hold intermediate.

**Comment by pearu** [comment]
@ngimel Notice that `tensor1_expand_size == tensor1.size()`. Does the `expand` still return a copy in this case?

**Comment by ngimel** [comment]
`expand` does not return a copy, but contiguous does.
```
a=torch.randn(1,1).expand(10,10) # size of a is 10x10, a occupies 1 element physical memory
a=a.contiguous() # size of a is still 10x10, and now it is blown up and takes 100 elements physical memory
```

**Comment by pearu** [comment]
Ah, the problem might be in `M_H` that is not contiguous even when `M` is.

**Comment by pearu** [comment]
So, it looks like that the most memory and processor efficient way is to ensure that the input to `pca_lowrank` is already centered and use `torch.pca_lowrank(A, center=False)`.
