### ISSUE TITLE
[jit] round not equivalent between python and torchscript

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#40771]
## 🐛 Bug

Originally reported by @vfdev-5  in https://github.com/pytorch/vision/pull/2342#discussion_r447587088

The behavior of `round` is not the same between torchscript and Python.
```python
import torch

def foo():    
    return round(2.5)

sfoo = torch.jit.script(foo)
print(foo(), sfoo())
# gives
# 2, 3.0
```
There are two differences: the value is different, but the returned type as well (float instead of int).

I'm using PyTorch version `'1.6.0.dev20200617'`

cc @suo @gmagogsfm

**Comment by cloudhan** [comment]
I can't reproduce the bug with value 3.5, 5.5, 7.5, 9.5, etc. Maybe just don't use 2.5 as argument for round ;) or, even better, only call round on <odd number>.5   XDDD

FYI, python part is using Bankers Rounding.
