### ISSUE TITLE
Missing ATen/native/cuda headers?

### ISSUE THREAD

**Issue by grohf** [pytorch/pytorch#40784]
I'm just curious if there is any particular reason for not including the ATen native cuda headers?
https://github.com/pytorch/pytorch/blob/a6a31bcd47094ecaa3a0a44644b86db985a051a3/aten/src/ATen/CMakeLists.txt#L371

I was toying around with fusing some element-wise operations in the TorchScript+libtorch tandem. So, I stumbled over CUDALoops.cuh etc. for some quick fusing tests. 
But unfortunately, they didn't get "installed".

Thanks!

cc @ezyang @seemethere @malfet @ngimel

**Comment by ngimel** [comment]
Adding triage review to prioritize in the meeting, This is not the first time a request to expose TensorIterator and at least its pointwise kernels (reductions would be great too) appears.

**Comment by ezyang** [comment]
IMO we should just expose these headers.

**Comment by albanD** [comment]
We would be happy to expose these and accept a PR for it.
It won't be a stable API though as we fairly often need to change it to support everything we need.
