### ISSUE TITLE
ninja builds are not rebuilding source files dependent on derivatives.yaml

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4078]
Steps to reproduce:
1. Do a build of PyTorch with ninja enabled (`pip install ninja`)
2. Edit `tools/autograd/derivatives.yaml`
3. Rebuild with `python setup.py develop`

Expected result: Change shows up in generated source
Actual result: Change does not show up

**Comment by colesbury** [comment]
This looks like it's fixed.
