### ISSUE TITLE
randint is missing Generator argument from typing annotation

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#40803]
Relevant code is 

```
        'randint': ['def randint(low: _int, high: _int, size: _size, *, {}) -> Tensor: ...'
                    .format(FACTORY_PARAMS),
                    'def randint(high: _int, size: _size, *, {}) -> Tensor: ...'
                    .format(FACTORY_PARAMS)],

```

In `tools/pyi/gen_pyi.py`

cc @ezyang @malfet @rgommers

**Comment by yl-to** [comment]
Will work on this to create a PR, thanks for pointing out!

**Comment by scintiller** [comment]
> Will work on this to create a PR, thanks for pointing out!

Oh sorry... I've been working on it yesterday and forgot to reply.

**Comment by san7988** [comment]
Hi. Won't we close the issue after the PR is merged?
