### ISSUE TITLE
Suppress Warnings for functions that internally cast complex values (with imag=0) to real values

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#40838]
Some time back, I added warnings to `copy_` for the scenario when a complex value is casted to a real value. However these warnings are also generated for functions that internally use `copy_` because of other limitations. for eg. the kernel for`.angle()` `.abs()` first returns a complex tensor with imag value as 0 which is then casted to the required out dtype (floating point). I think to avoid any confusion, these warnings should be suppressed in such cases.

```
>>> phase_0 = complex_specgrams[..., :1].angle()
__main__:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  ../aten/src/ATen/native/Copy.cpp:165.)
```

cc. @mruberry 

cc @ezyang @anjali411 @dylanbespalko

**Comment by ezyang** [comment]
There should be a way to say "I want to do a copy, discard imaginary part" explicitly, without having a warning. That would be the most logical way to suppress the warning.
