### ISSUE TITLE
emit_nvtx context manager is very slow

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/pytorch#40843]
Hello! There are 2 modes under torch.autograd.profiler, profile & emit_nvtx. 
In [pytorch bottleneck docs](https://pytorch.org/docs/stable/bottleneck.html), I found the words "please take into account that the **NVTX overhead is very high** and often gives a heavily skewed timeline".
However, in [NVTX docs](https://nvidia.github.io/NVTX/doxygen/index.html), I found the words "The library introduces close to **zero overhead** if no tool is attached to the application. The overhead when a tool is attached is specific to the tool".
In [pytorch autograd docs](https://pytorch.org/docs/master/autograd.html), I found the words "Adds approximately 4us of overhead to each tensor operation" under the "use_cuda" paramter of "torch.autograd.profiler.profile".

Then my confusion is, among the "profile" using cudaEventRecord and "emit_nvtx" using ::nvtxRangePushA, which one has smaller additional overhead? 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @VitalyFedyunin @ngimel @ilia-cher @gdankel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @SsnL

**Comment by ezyang** [comment]
Hello @smartcat2010. The "NVTX overhead" in the bottleneck is referring to the overhead when the tool is attached, which doesn't contradict the NVTX docs. We can't do bottleneck profiling without actually instrumenting NVTX.

The autograd profiler is another mechanism and it does have its own overhead, independently of NVTX. This is because we insert a lot of new ranges automatically.

If you are looking for the lowest overhead profiling mechanism, I am not sure; try both and see which one is faster!

**Comment by smartcat2010** [comment]
> Hello @smartcat2010. The "NVTX overhead" in the bottleneck is referring to the overhead when the tool is attached, which doesn't contradict the NVTX docs. We can't do bottleneck profiling without actually instrumenting NVTX.
> 
> The autograd profiler is another mechanism and it does have its own overhead, independently of NVTX. This is because we insert a lot of new ranges automatically.
> 
> If you are looking for the lowest overhead profiling mechanism, I am not sure; try both and see which one is faster!

Thank you very much!
As for the "attached", does it mean attaching a debugger to the process which calls NVTX?

**Comment by ezyang** [comment]
Not a generic debugger (e.g., gdb), but specifically nvprof, I believe.

**Comment by smartcat2010** [comment]
> Not a generic debugger (e.g., gdb), but specifically nvprof, I believe.

Thanks a lot! Really helpful!

**Comment by FRAOTIAC** [comment]
> Hello @smartcat2010. The "NVTX overhead" in the bottleneck is referring to the overhead when the tool is attached, which doesn't contradict the NVTX docs. We can't do bottleneck profiling without actually instrumenting NVTX.
> 
> The autograd profiler is another mechanism and it does have its own overhead, independently of NVTX. This is because we insert a lot of new ranges automatically.
> 
> If you are looking for the lowest overhead profiling mechanism, I am not sure; try both and see which one is faster!

Hi @ezyang , I'm a little confused, what do you mean by "doesn't contradict the NVTX docs"? 

I'm working on profiling model Training currently, when using `with torch.autograd.profiler.emit_nvtx()` in the training for-loop, a 500ms iteration slows down to 4s, that's huge overhead there.

**Comment by ezyang** [comment]
Is this slow down when you have nvprof attached or not?

**Comment by FRAOTIAC** [comment]
Yes, it has slowed down, mainly because of this with statement.

**Comment by FRAOTIAC** [comment]
From a problem-solving perspective, I recommend using `torch.cuda.nvtx.range_push(msg)`, which eliminates the need to use with statement, thus avoiding overhead.

**Comment by ezyang** [comment]
Thanks for the note. I'll reopen this issue as a general perf optimization issuef or the context manager.

**Comment by aaronenyeshi** [comment]
Profiler has been greatly optimized and re-written. Please re-open if the overhead issue persists.
