### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator SwishJitAutoFn

### ISSUE THREAD

**Issue by DJMeng** [pytorch/pytorch#40847]
When I exported effcientnet b7 to onnx:
my env is torch 1.5, opset11.and I try other's version of torch or opset, it will meet other problems.
someone meet this error? Please help. Thanks.

cc @suo @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by eellison** [comment]
HI, could you include a repro please ?

**Comment by rsomani95** [comment]
@DJMeng were you using [Ross Wightman's repo](https://github.com/rwightman/pytorch-image-models) ?

If so, when you call `create_model`, you can pass in a `scriptable=True` to make sure you create a model with an activation function compatible with ONNX. I've tried this with `efficientnet_b3a`

```python
from timm import create_model

model = create_model('efficientnet_b3a', pretrained=True, scriptable=True)
torch.onnx._export(model, ...)
```

**Comment by jhagege** [comment]
> When I exported effcientnet b7 to onnx:
> my env is torch 1.5, opset11.and I try other's version of torch or opset, it will meet other problems.
> someone meet this error? Please help. Thanks.
> 
> cc @suo @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

Hi @DJMeng , have you found a solution ?

**Comment by DJMeng** [comment]
> > When I exported effcientnet b7 to onnx:
> > my env is torch 1.5, opset11.and I try other's version of torch or opset, it will meet other problems.
> > someone meet this error? Please help. Thanks.
> > cc @suo @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof
> 
> Hi @DJMeng , have you found a solution ?

no,I still not find.

**Comment by Ekta246** [comment]
Any solution?

**Comment by thiagocrepaldi** [comment]
This is working on latest pytorch/torchvision

To verify:

```
import torch
import torchvision

data = torch.randn(1, 3, 224, 224)
model=torchvision.models.efficientnet_b7()

torch.onnx.export(model, (data,), 'my_efficientnet_b7.onnx', verbose=True)
```

The exported ONNX was fed to ONNX Runtime's `InferenceSession` API to compare its result with PyTorch. Both ONNX and PyTorch result matched perfectly
