### ISSUE TITLE
Don't know how to translate op Conv

### ISSUE THREAD

**Issue by Korijn** [pytorch/pytorch#40855]
(sent here from https://github.com/onnx/onnx/issues/2822)

I'm only seeing this error on Windows. It's working fine on Linux (Docker).

I can't find any other issues or documentation, but I get the impression that the op registry is not populated fully. Is there some kind of setup that I need to go through? Prerequisite installation needed?

I'm working on Windows 10, python 3.6, I've installed `onnx==1.7.0` indirectly with pip by installing pytorch according to the [getting started page instructions at pytorch's website](https://pytorch.org/get-started/locally/): `pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/torch_stable.html`

```
.venv\lib\site-packages\caffe2\python\onnx\backend.py:713: in prepare
    init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'caffe2.python.onnx.backend.Caffe2Backend'>
onnx_model = ir_version: 3
producer_name: "pytorch"
producer_version: "0.4"
graph {
  node {
    input: "0"
    input: "1"
    outp... dim {
            dim_value: 512
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 9
}

device = 'CPU', opset_version = 9, include_initializers = False

# <snip>

E           RuntimeError: ONNX conversion failed, encountered 69 errors:

# <snip>

E           . Exception: [enforce fail at ..\caffe2\onnx\backend.cc:1426] . Don't know how to translate op Conv
E           (no backtrace available)
```

**Comment by peterjc123** [comment]
Would you please try pytorch>=1.5? We tried to fix that by loading all DLLs on startup in https://github.com/pytorch/pytorch/pull/35362.

**Comment by Korijn** [comment]
That fixed it! Thanks!
