### ISSUE TITLE
pytorch build from source with CUDA 9 and CUDNN 7

### ISSUE THREAD

**Issue by yanghuanflc** [pytorch/pytorch#4086]
If I want to build PyTorch from source with CUDA9 and CUDNN 7, is that right to simply change "magma-cuda80" to "magma-cuda90" then follow the instructions in README?

Just like this:

export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
conda install numpy pyyaml mkl setuptools cmake cffi
conda install -c soumith magma-cuda90
git clone --recursive https://github.com/pytorch/pytorch
python setup.py install

Really thanks!
@soumith

**Comment by ngimel** [comment]
Yes.

**Comment by VisheshTanwar-IITR** [comment]
@yanghuanflc 

I just have a silly question that in export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../", 

what is dirname and which conda?

my which conda output is "/home/vishesh/anaconda2/bin/anaconda"

Thanks a lot

**Comment by 2name** [comment]
@VisheshTanwar-IITR 
Hi,now,do you know what dirname and which conda is in export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"}.
Thank you for your reply.

**Comment by 2name** [comment]
@VisheshTanwar-IITR Hi,I solved it!

run export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]

or

run echo 'export CMAKE_PREFIX_PATH="~/anaconda3/bin"' >> ~/.bashrc

or

run vi ~/.bashrc 
then add export CMAKE_PREFIX_PATH=~/anaconda3/bin        
then run source ~/.bashrc
