### ISSUE TITLE
Unable to locate program input point

### ISSUE THREAD

**Issue by williamlzw** [pytorch/pytorch#40892]
win10 x64 | libtorch1.5.0 release x64| cuda10.2 | 
---------------------------------------------------------
I tried to compile the project into a DLL. Then loading the DLL with LoadLibraryA prompted the following error:
Unable to locate program input point
?dispatchKeySetToDispatchKey_@DispatchKeyExtractor@c10@AEBA?AW4DispatchKey@2@VDispatchKeySet@2@00@Z on dynamic link library D:\Project2\x64\Release\Project2.dll
------------------------------------------------------------
dllmain.cpp

#include "dllmain.h"
BOOL APIENTRY DllMain(HMODULE hModule,
    DWORD  ul_reason_for_call,
    LPVOID lpReserved
)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}
struct wtensor {
	void* ptr;
	int64_t* size;
	int size_number;
	int type;
};
 void* tensor_new(float* data, int64_t* size, int size_number, int type)
{
	std::vector<float> aa(data, data + sizeof(data) / sizeof(float));
	torch::Tensor c;
	if (type == 0) {
		c = torch::tensor(aa, c10::ScalarType::Byte);
	}
	else if (type == 3) {
		c = torch::tensor(aa, c10::ScalarType::Int);
	}
	else if (type == 4) {
		c = torch::tensor(aa, c10::ScalarType::Long);
	}
	else if (type == 6) {
		c = torch::tensor(aa, c10::ScalarType::Float);
	}
	std::vector<int64_t> asize;
	for (int index = 0; index < size_number; index++) {
		asize.push_back(size[index]);
	}
	c.view(asize);
	auto ret = new wtensor();
	ret->ptr = c.data_ptr();
	ret->size = size;
	ret->type = type;
	ret->size_number = size_number;
	return  ret;
}
---------------------------------------------------
dllmain.h

#pragma once
#include "torch/torch.h"
#include <windows.h>
------------------------------------------------
dllmain.def

LIBRARY "Project2"
EXPORTS
tensor_new @ 1

-----------------------------------------------------
test.cpp

#include "test.h"
int main(){
	std::string path = "D:/Project2/x64/Release/Project2.dll";
	HMODULE   hDllInst = LoadLibraryA((LPCSTR)path.c_str());
	std::cout << hDllInst << std::endl;
	std::cout << GetLastError() << std::endl;
       if (hDllInst)
	{
		/*typedef   void*(*fun_tensor_new)(float*, int64_t*, int, int);
		fun_tensor_new ptensor_new = (fun_tensor_new)GetProcAddress(hDllInst, "tensor_new");
		float a[] = { 3.,4. };
		int64_t b[2] = { 1,2 };
		int type = 6;
		void* c = ptensor_new(a, b, 2, type);
		std::cout << c << std::endl;*/
		
		FreeLibrary(hDllInst);
	}
        system("pause");
	return 0;
}
---------------------------------------------
test.h

#pragma once
#include <iostream>
#include <Windows.h>
----------------------------------------------------
dllmain.sln project properties
--------------------------------
c/c++ -> command line: 

/GS /TP /W3 /Gy /Zc:wchar_t /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" /Z7 /Gm- /O2 /Ob2 /Fd"x64\Release\vc142.pdb" /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /GR /Gd /MD /openmp /std:c++17 /FC /Fa"x64\Release\" /EHa /nologo /Fo"x64\Release\" /Fp"x64\Release\Project2.pch" /diagnostics:column 
---------------------------------------
 Linker-> command line: 

/OUT:"D:\Project2\x64\Release\Project2.dll" /MANIFEST /LTCG:incremental /NXCOMPAT /PDB:"D:\Project2\x64\Release\Project2.pdb" /DYNAMICBASE "c10.lib" "c10_cuda.lib" "asmjit.lib" "caffe2_detectron_ops_gpu.lib" "caffe2_module_test_dynamic.lib" "caffe2_nvrtc.lib" "clog.lib" "cpuinfo.lib" "fbgemm.lib" "libprotobuf.lib" "libprotobuf-lite.lib" "libprotoc.lib" "mkldnn.lib" "torch.lib" "torch_cpu.lib" "torch_cuda.lib" "C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cudart_static.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cufft.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\curand.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cublas.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cudnn.lib" "-INCLUDE:?warp_size@cuda@at@@YAHXZ" "D:\opencv\build\x64\vc15\lib\opencv_world430.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEF:"main.def" /IMPLIB:"D:\Project2\x64\Release\Project2.lib" /DLL /MACHINE:X64 /OPT:REF /INCREMENTAL:NO /PGD:"D:\Project2\x64\Release\Project2.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Release\Project2.dll.intermediate.manifest" /OPT:ICF /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64" /TLBID:1 
---------------------------------------------
test.sln project properties
--------------------------------
c/c++ -> command line: 

/permissive- /GS /GL /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /sdl /Fd"x64\Release\vc142.pdb" /Zc:inline /fp:precise /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /Gd /Oi /MT /FC /Fa"x64\Release\" /EHsc /nologo /Fo"x64\Release\" /Fp"x64\Release\Project1.pch" /diagnostics:column 
-----------------------------------
 Linker-> command line: 

/OUT:"D:\Project2\x64\Release\Project1.exe" /MANIFEST /LTCG:incremental /NXCOMPAT /PDB:"D:\Project2\x64\Release\Project1.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG /MACHINE:X64 /OPT:REF /INCREMENTAL:NO /PGD:"D:\Project2\x64\Release\Project1.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Release\Project1.exe.intermediate.manifest" /OPT:ICF /ERRORREPORT:PROMPT /NOLOGO /TLBID:1

cc @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
> /_typedef void_(_fun_tensor_new)(float_, int64_t*, int, int);
> fun_tensor_new ptensor_new = (fun_tensor_new)GetProcAddress(hDllInst, "tensor_new");

Is there a reason that you have to do this explicitly? Have you loaded the DLLs beforehand? (Since you are using VS, the loaded DLLs are shown in the `Output` window.)

> D:\Project2\x64\Release\Project2.dll

How did you build this DLL? Could you please share more details about it? Alternatively, when it is possible, could you please upload the whole project to a github repo and write down the steps to build your project?

**Comment by laizewei** [comment]
Demo link:https://github.com/laizewei/errordemo

I tried to compile it to run as a DLL to speed up debugging.

**Comment by peterjc123** [comment]
@laizewei There's no README in the project. So I have to guess all the things in your question.

### Steps
You are trying to warp all the libs in Project2.DLL and load it explicitly in Project1. So build Project2 and then Project1.

### Purpose
I guess what you said "debugging" in the previous post actually refers to the configuration of the Visual Studio project. Actually we have CMake. But you said you don't use it. That's okay but I don't know other ways to make it simpler using VS.

### Methodology
As for what you are trying to do, I don't think it's the best way to achieve the aforementioned purpose. Apparently you could create a static lib (Project2 in your case) and then link Project1 against it. In this way, you may avoid to load the DLLs explicitly.

**Comment by laizewei** [comment]
How do I change the project2.SLN project properties so that project2.DLL can be loaded.
I will use Project2.DLL in C and other languages.So I tried to compile project2.dll.
----------------------------------
demo
   -Project.sln
   -Project1
       -Project1.vcxproj
       -Project1.vcxproj.filters
       -Project1.vcxproj.user
       -testmain.cpp
       -testmain.h
   -Project2
       -Project2.vcxproj
       -Project2.vcxproj.filters
       -Project2.vcxproj.user
       -main.cpp
       -main.h
       -learn
             -libtorch
             -opencv

**Comment by mszhanyi** [comment]
@laizewei try as the below image
![image](https://user-images.githubusercontent.com/16190118/94255240-82833d80-ff5a-11ea-924f-9244b9a776c8.png)

**Comment by mantaionut** [comment]
The demo above is no longer available. I've tried to create my own DLL project and then load that DLL with LoadLibraryA and I had no issues as long as the other torch DLLs were present. The only errors I encountered were when I was mixing debug and release DLLs.  Do you still have this issue? If so can you reshare your demo?
