### ISSUE TITLE
[FR] JIT can't handle list(range(k))

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#40915]
Currently it fails with `range cannot be used as a value`

cc @suo @gmagogsfm

**Comment by eellison** [comment]
dup of https://github.com/pytorch/pytorch/issues/40915

**Comment by SsnL** [comment]
@eellison hey you referred to this same issue...

**Comment by eellison** [comment]
oop lol. this one https://github.com/pytorch/pytorch/issues/40869. as i commented on that one, i landed a PR for this but it can unlanded bc of aa slow test, i'll try to reland it.

**Comment by SsnL** [comment]
@eellison ohh i see. that would be great! thanks!
