### ISSUE TITLE
Get rid of 'backend_types' in codegen

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#40929]
See this declaration: https://github.com/pytorch/pytorch/blob/1a74bb84f2b0fd0e1a532941645e24e2cfea1e6a/aten/src/ATen/Declarations.cwrap#L349

it's the only current usage of `backend_types` and can be replaced with relatively simple code with Dispatch (https://github.com/pytorch/pytorch/blob/1a74bb84f2b0fd0e1a532941645e24e2cfea1e6a/aten/src/ATen/Dispatch.h) and templates similar to how https://github.com/pytorch/pytorch/blob/1a74bb84f2b0fd0e1a532941645e24e2cfea1e6a/aten/src/TH/THBlasUtils.h is done.

**Comment by heitorschueroff** [comment]
https://github.com/pytorch/pytorch/pull/40646 removed the reference but nn_parse.py still uses 'backend_types' so this cannot be entirely removed from preprocess_declarations.py
