### ISSUE TITLE
Move the pruning module to a higher level

### ISSUE THREAD

**Issue by he-y** [pytorch/pytorch#40966]
## 🚀 Feature
Call the pruning function needs several sub-functions, e.g., [`torch.nn.utils.prune.BasePruningMethod`](https://pytorch.org/tutorials/intermediate/pruning_tutorial.html).
Move the pruning module to a higher level might be better.

## Motivation
When more pruning methods are added, as discussed [here](https://github.com/pytorch/pytorch/issues/39765) and [here](https://github.com/pytorch/pytorch/pull/40662), it's not convenient to add all the pruning methods into one file.

In contrast, calling Quantization requires much fewer sub-functions:
As shown in the [Quantization tutorial](https://pytorch.org/docs/stable/quantization.html), call the Quantization function just need `torch.quantization`.
Considering Quantization is a parallel method with pruning for neural network acceleration, moving the pruning module to the same level as the Quantization module might be better.

cc @albanD @mruberry

**Comment by he-y** [comment]
@mickypaganini 
How do you think about this suggestion?

**Comment by SsnL** [comment]
I personally would just use the `import X as Y` here. I.e., `import torch.nn.utils.prune as prune`.

**Comment by albanD** [comment]
I would agree that you can simply import a submodule to be able to access it more easily.
Also, not having everything at the base level makes it easier to organize your code (and the library).

**Comment by he-y** [comment]
Thanks. I agree.
