### ISSUE TITLE
Unable to install 0.3 on Python 3.6.2, Anaconda, Ubuntu 14.04

### ISSUE THREAD

**Issue by agent-jay** [pytorch/pytorch#4097]
I was using the older 0.2 release on the soumith channel. When using the command
`conda install pytorch torchvision -c pytorch` listed on the website to install 0.3, conda instead downgrades to
```
    cudatoolkit: 8.0-3                       
    cudnn:       6.0.21-cuda8.0_0            
    nccl:        1.3.4-cuda8.0_1             
    pytorch:     0.1.12-py36cuda8.0cudnn6.0_1
```
This happens even when I try to install it in a new environment
```
    cffi:        1.10.0-py36_0               
    cudatoolkit: 8.0-3                       
    cudnn:       6.0.21-cuda8.0_0            
    libffi:      3.2.1-1                     
    libgcc:      5.2.0-0                     
    mkl:         2017.0.3-0                  
    nccl:        1.3.4-cuda8.0_1             
    numpy:       1.13.1-py36_0               
    pycparser:   2.18-py36_0                 
    pytorch:     0.1.12-py36cuda8.0cudnn6.0_1
```
I ended up installing it using pip. But any suggestions on how to update using conda?

**Comment by michalwols** [comment]
I ran into the same issue in one of my environments. Seems to be a peer dependency issue with opencv.

**Comment by daniilsorokin** [comment]
Updating conda itself resolved the issue for me

**Comment by agent-jay** [comment]
That did the trick, @daniilsorokin . Thanks!
