### ISSUE TITLE
Easier method for model inference and deployment

### ISSUE THREAD

**Issue by kleingeo** [pytorch/pytorch#40981]
I have been looking into ways to deploy and use models after they are trained. I originally started machine/deep learning using Keras/Tensorflow, and one of the options with them is the ability to save the model architecture as a `.json` file and loading the weights into that. Is there any plans on doing something like with with PyTorch? For a lot of use cases, it isn’t ideal to use the same development project to rebuild the model architecture to load the weights into in the deployment use-case.

**Comment by albanD** [comment]
Hi,

You can look up online, there is a lot of material about this. This blogpost should give a good intro: https://pytorch.org/blog/model-serving-in-pyorch/
Also don't hesitate to open a new topic on the forum (https://discuss.pytorch.org/) if you have any follow up questions.

**Comment by kleingeo** [comment]
> Hi,
> 
> You can look up online, there is a lot of material about this. This blogpost should give a good intro: https://pytorch.org/blog/model-serving-in-pyorch/
> Also don't hesitate to open a new topic on the forum (https://discuss.pytorch.org/) if you have any follow up questions.

I have done a lot of reading on this topic, and the link for the blog post doesn't have much information relevant in it. I am not using an embedded system or any other special kind of system. I am simply looking to use the trained model's in a simpler way, but not with any kind of special system, server, or other framework. All info about using model inferencing through the PyTorch site deals with loading the weights into a build architecture.

**Comment by albanD** [comment]
In this case, you can follow the same instruction as for the cpp deployement above where you trace/script your model with the jit and export this. Then instead of loading it in cpp to evaluate it, you can import it in python. This will be a standalone version of your model (though not modifiable of course).

**Comment by kleingeo** [comment]
> In this case, you can follow the same instruction as for the cpp deployement above where you trace/script your model with the jit and export this. Then instead of loading it in cpp to evaluate it, you can import it in python. This will be a standalone version of your model (though not modifiable of course).

I will give this a shot. However, I am not entirely sure between `torch.jit.sript(Model())` vs. `torch.jit.trace(Model())`.

**Comment by albanD** [comment]
`script` will preserve the python logic (if statement, loop conditions) but won't work for everything.
`trace` will only record the ops that were performed and so won't keep conditions but it will always work.
