### ISSUE TITLE
In-place operation between cpu scalar and gpu scalar throws an error

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#40986]
## To Reproduce

```
a=torch.tensor(2.)
b=torch.tensor(2., device="cuda")
a += b
```
results in 
```
RuntimeError: Trying to pass too many CPU scalars to CUDA kernel!
```

## Expected behavior

No error (that's tricky to implement though) or better error message

cc @mruberry, @albanD

**Comment by albanD** [comment]
In this case, do we really want to pass the GPU scalar which is already on the correct device by value?
Does that mean that we need to get it from the GPU first before being able to call the kernel?

**Comment by ngimel** [comment]
`a` is a cpu scalar, and it's not on the correct device, and we can't pass it by value because we want to change it. Whether b is passed by value (it isn't) does not matter. This case just does not fall into limited exception category that we allow for gpu - cpu scalar interop, and we should error out on it like on any other device mismatch, with a sensible error message.

**Comment by albanD** [comment]
Ho my bad! I though it was the scalar on the left side that was on the GPU.
In that case yes a nice error message sounds like the right thing.
