### ISSUE TITLE
incorrect torch.cat signature

### ISSUE THREAD

**Issue by sniklaus** [pytorch/pytorch#40990]
## 🐛 Bug

According to the documentation, the signature of `torch.cat` is `torch.cat(tensors, dim=0, out=None)`. However, it is not possible to call `torch.cat` with three positional arguments.

## To Reproduce

```
>>> torch.cat([torch.rand(1, 2, 3), torch.rand(1, 2, 3)], 0, torch.FloatTensor(12))
TypeError: cat() received an invalid combination of arguments - got (list, int, Tensor), but expected one of:
 * (tuple of Tensors tensors, name dim, *, Tensor out)
 * (tuple of Tensors tensors, int dim, *, Tensor out)
```

The following works though, notice that I only added `out=` to the third argument. However, this should not be required as per the signature definition in the documentation.

```
>>> torch.cat([torch.rand(1, 2, 3), torch.rand(1, 2, 3)], 0, out=torch.FloatTensor(12))
tensor([[[0.6310, 0.3772, 0.7654],
         [0.8126, 0.7031, 0.6288]],

        [[0.3101, 0.7344, 0.5670],
         [0.0366, 0.5181, 0.3637]]])
```

## Expected behavior

`torch.cat` should be callable without having to use a named argument for `out`.

## Environment

```
PyTorch version: 1.5.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: version 3.16.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 440.64
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.5.0+cu101
[pip3] torchvision==0.6.0+cu101
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.5.0+cu101              pypi_0    pypi
[conda] torchvision               0.6.0+cu101              pypi_0    pypi
```

cc @jlin27

**Comment by ngimel** [comment]
`out` is always a keyword-only argument (for other functions as well), having it as a positional argument would be confusing and not always possible for functions with the different number of tensor args. We will accept a PR fixing the documentation to indicate that `out` is keyword-only.

**Comment by sniklaus** [comment]
Thank you for the explanation, updating the documentation would resolve this. :+1:

**Comment by AnirudhDagar** [comment]
This can be closed. Was fixed in gh-43583.
