### ISSUE TITLE
update_s3_htmls job is failing on CircleCI

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#40998]
## 🐛 Bug

Per title. Actually the job is queued for a long time and never get running. 
See 
https://app.circleci.com/pipelines/github/pytorch/pytorch/187773/workflows/0c569c8f-ebfe-4247-a364-dea5f60f10ae/jobs/6113912
https://app.circleci.com/pipelines/github/pytorch/pytorch/187926/workflows/432dbe98-ca2f-484d-acc7-0482cb3fd01f/jobs/6118566

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by peterjc123** [comment]
Looks like https://github.com/pytorch/pytorch/pull/41000 has not fixed that. @seemethere Could you please look into it?

**Comment by seemethere** [comment]
I think https://github.com/pytorch/pytorch/pull/41354 should resolve this along with re-opening https://github.com/pytorch/pytorch/pull/27167
