### ISSUE TITLE
Export to ONNX fails using F.interpolate with mode='area'

### ISSUE THREAD

**Issue by omasaht** [pytorch/pytorch#41009]
## 🐛 Bug

When I try to export my model to ONNX that uses F.interpolate with mode set to 'area', I get an error. I tried changing scale_factor (both upsampling and downsampling) but error stays the same. I have attached a sample code which may be used to reproduce the error below.

## Sample Code To Reproduce Error:

``` python
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx

# Model Architecture with Interpolate function
class MyModel(nn.Module):
    def __init__(self,scale_factor,mode):
        super(MyModel, self).__init__()
        self.interp_mode = mode
        self.sf = scale_factor

    def forward(self,x):
        x = F.interpolate(x,
            scale_factor=self.sf,
            mode=self.interp_mode)

        return x

#initialize model object
scale_factor = 1/2
mode = 'area'
model = MyModel(scale_factor,mode)

#export model to onnx
x = torch.randn(1,1,100,100)
model_out = model(x)
torch.onnx.export(model,
                  x,
                  'sample.onnx',
                  export_params=True,
                  opset_version=11,
                  input_names = ['input'],
                  output_names = ['output'])
```
## Stack Traces and Error Message

```
/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/nn/functional.py:2854: UserWarning: The default behavior for interpolate/upsample with float scale_factor will change in 1.6.0 to align with other frameworks/libraries, and use scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor will change "
Traceback (most recent call last):
  File "bug.py", line 34, in <module>
    output_names = ['output'])
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/utils.py", line 154, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/__init__.py", line 199, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/utils.py", line 740, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/omasa/anaconda3/envs/work/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 81, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Floor', since it's not constant, please try to make things (e.g., kernel size) static if possible

```

## Expected behavior

Pytorch model using F.interpolate(mode='area') should be exported to ONNX

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 450.36.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.0

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      2.16                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.1                      219    conda-forge
[conda] numpy                     1.18.5           py37h8960a57_0    conda-forge
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.6.1                py37_cu102    pytorch

## Additional context

All the other interpolate modes ('nearest', 'linear', 'bilinear', 'bicubic', 'trilinear') work fine. 
**Note:** I had to change input dimension in above sample code to test other interpolation modes.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@omasaht - `area` mode is not explicitly supported in ONNX spec, and therefore, not supported in the exporter.
