### ISSUE TITLE
Enable Intel® VTune™ Profiler's Instrumentation and Tracing Technology APIs (ITT) to PyTorch

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#41001]
## 🚀 Feature

Enable Intel® VTune™ Profiler's Instrumentation and Tracing Technology APIs (ITT) to PyTorch

## Motivation

This is Intel's counterpart functionality of NVidia’s NVTX (https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.emit_nvtx).
1.	The instrumentation and tracing technology (ITT) APIs of Intel® VTune Profiler enables application to generate and control the collection of trace data during its execution. ITT provides scoped timer and visualizes your program execution in OP/function/sub-function granularity. By applying the API functions on executed ops, we can get performance visualization on individual PyTorch ops. From the following screenshot we can see CPU usage on each op, like the conv2d in this example. This will be helpful for op-level tuning.
![ITT1](https://user-images.githubusercontent.com/25193121/86559027-ed455e00-bf95-11ea-979c-58472fde7789.png)

2.	Upon existing op level profiling, users can annotate a scope of multiple ops to have a higher level understanding of performance manually.
In the following screenshot of ResNet50 profiling result, each epoch, with train step and test step inside, is shown in timeline graph. Also, it is very clear to see how long was spent on train step, how long was spent on test step.
![ITT2](https://user-images.githubusercontent.com/25193121/86559036-f6cec600-bf95-11ea-8046-c00d71323c43.png)

      We can also expand this timeline graph to see profiling results with more details, in case users need to track how individual ops got invoked in their topologies.
![ITT3](https://user-images.githubusercontent.com/25193121/86559047-fc2c1080-bf95-11ea-9eb2-ac684d8992ce.png)

## Pitch

1. Visualize execution of topology as well as performance of metrics of each op.
2. Annotation of a scope of ops to have a higher level understanding of the topology execution.

## Additional context

cc @VitalyFedyunin @ngimel

**Comment by VitalyFedyunin** [comment]
cc @ilia-cher

**Comment by jingxu10** [comment]
Hi @ilia-cher, does this PR make sense? Please let me know if you need more information from me. Thank you.
