### ISSUE TITLE
Pytorch installation error

### ISSUE THREAD

**Issue by Captfan** [pytorch/pytorch#41005]
## ❓ Questions and Help

Hi, 

I am trying to install PyTorch for my Python 3.7.4, so from the Get Started page, I've selected:

PyTorch Build: Stable(1.5.1)
Your OS: Windows
Package: Pip
Language Python
CUDA: None (as I don't have Nvidia graphic card installed)

However, there is an error when run the generated command:

C:\Python\Python37-32\Scripts>pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html

ERROR: Could not find a version that satisfies the requirement torch==1.5.1+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.1+cpu

Any advice on how to solve such problem? Thanks.

**Comment by peterjc123** [comment]
Please use a 64-bit Python installation instead.
