### ISSUE TITLE
`floor` and potentially other operations don't check dtype of `out` kwarg producing incorrect results

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#41047]
## 🐛 Bug

When the output tensor is permuted (by `permute()`), many operators don't produce correct results.

## To Reproduce

Use `floor` as an example.

```
In [1]: import torch

In [2]: a=torch.arange(0, 300000*3*3, dtype=float)

In [3]: res = torch.rand(3, 3, 300000).permute(2, 0, 1)

In [4]: a
Out[4]: 
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 2.7000e+06, 2.7000e+06,
        2.7000e+06], dtype=torch.float64)

In [5]: a.floor()
Out[5]: 
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 2.7000e+06, 2.7000e+06,
        2.7000e+06], dtype=torch.float64)

In [6]: torch.floor(a, out=res)
Out[6]: tensor([0.8226, 0.1410, 0.7213,  ..., 0.6565, 0.6220, 0.5195])
```

Note the strange behavior in Output 6. This issue doesn't show up on CUDA.

## Environment

PyTorch version: 1.7.0.dev20200705+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Debian GNU/Linux 10 (buster)
GCC version: (Debian 8.3.0-6) 8.3.0
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro P400
Nvidia driver version: 440.100
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.7.0.dev20200705+cu101
[conda] Could not collect

## Additional context

I investigated a bit, seems like `is_contiguous` always returns `true`:

https://github.com/pytorch/pytorch/blob/078669f6c3b0eb48cdb32be4bd4c3e7a9500e682/aten/src/ATen/native/cpu/Loops.h#L222

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @nairbv

**Comment by ngimel** [comment]
The issue here is with res datatype rather than permutation (`a` datatype is torch.float64, `out` datatype is torch.float). Setting high priority because of silent wrong results.

**Comment by zou3519** [comment]
On 1.5.1 this produces an error:
```
[ins] In [1]: import torch

[ins] In [2]: a=torch.arange(0, 300000*3*3, dtype=float)

[ins] In [3]: res = torch.rand(3, 3, 300000).permute(2, 0, 1)

[ins] In [4]: a
Out[4]:
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 2.7000e+06, 2.7000e+06,
        2.7000e+06], dtype=torch.float64)

[ins] In [5]: a.floor()
Out[5]:
tensor([0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 2.7000e+06, 2.7000e+06,
        2.7000e+06], dtype=torch.float64)

[ins] In [6]: torch.floor(a, out=res)
```
So I'd also mark this as a regression. We should try to figure out if the release branch for 1.6 has this problem

**Comment by ngimel** [comment]
Changed the title to reflect this issue. non-contiguous `out` arguments can lead to confusing behavior, but that's a separate issue and we are tracking it in #41027
