### ISSUE TITLE
convenience function for loading a non-DP/DDP model from a DP/DDP state_dict

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#41048]
## 🚀 Feature

Add a utility to PyTorch to enable users to load models without DP/DDP from a DP/DDP state dict.  This essentially means that we provide the code to strip the `module` prefix from all items in the state dict and the metadata.  One existing example is here: https://github.com/facebookresearch/fvcore/blob/master/fvcore/common/checkpoint.py#L239.

## Motivation

This is a common user need.  See the traffic in https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/33, and we are getting internal requests to provide a PT native solution to this.

Basic repro here: https://gist.github.com/vkuzo/248862f89147d80cea34aa3e08782e0b. 

## Pitch

* add a converter similar to fvcore's `_strip_prefix_if_present` to `torch/distributed/utils`, and document its existence

## Alternatives

* detect when the user is loading a DP/DDP state_dict into a model without DP/DDP, and print a warning linking to the suggested solution

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @xush6528

**Comment by rohan-varma** [comment]
I wonder if it's better to do this with a utility or to build this directly into the `model.load_state_dict()` code so that it "just works"?

**Comment by vkuzo** [comment]
> I wonder if it's better to do this with a utility or to build this directly into the `model.load_state_dict()` code so that it "just works"?

+1 if that's landable and there aren't gotchas.  That would be better for the user.
