### ISSUE TITLE
Support object unloading in JIT

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4105]
At the moment, we only ever dlopen `.so` files, which means that a process that continually uses the JIT will eventually OOM, since this is never GCed. Make this not be the case.

I know GHCi linker supports unloading, so it will just take some legwork.

**Comment by eellison** [comment]
Is this still an issue ?

**Comment by ezyang** [comment]
DynamicLibrary appears to dlclose on destruction. So it's fixed.
