### ISSUE TITLE
Performance regression for inference from pytorch 1.4.0 to >= 1.5.0

### ISSUE THREAD

**Issue by interesaaat** [pytorch/pytorch#41057]
## 🐛 Bug

With [Hummingbird](https://github.com/microsoft/hummingbird) we translate trained traditional ML models into PyTorch for faster inference. We found that most of our tree models on CPU have a 10x performance degradation when we move from pytorch 1.4.0 to => 1.5.0. 

Issues related to this problem can be found [here](https://github.com/microsoft/hummingbird/issues/177) and [here](https://github.com/microsoft/hummingbird/issues/12#issuecomment-637077289). Notebooks for 1.5.0 and 1.4.0 can be found [here](https://github.com/mmbhatk/hummingbird/blob/notebooks-test/notebooks/Random%20Forest%20Regressor%20-%20Pytorch%201.5.0.ipynb) and [here](https://github.com/mmbhatk/hummingbird/blob/notebooks-test/notebooks/Random%20Forest%20Regressor%20-%20Pytorch%201.4.ipynb)

## To Reproduce

1. mkdir hummingbird
2. cd hummingbird
3. git clone https://github.com/microsoft/hummingbird.git .
4. pip install -e .[docs,tests,extra]
5. run sklearn-random-forest-example.ipynb
6. pip uninstall torch
7. pip install torch==1.4.0
8. run sklearn-random-forest-example.ipynb

## Expected behavior

Newest PyTorch versions should have similar or better performance compared to previous versions.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.4.0, 1.5.0, 1.5.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Setting high priority because of a large regression. Are you using multi-threaded or single-threaded setting?

**Comment by interesaaat** [comment]
We didn't set anything, so I am assuming this is multi-threaded.

**Comment by ezyang** [comment]
Thanks for the report. If you can easily do so, running the benchmark on a recent nightly would also be helpful.

**Comment by interesaaat** [comment]
Thanks @ezyang. I tried with the nightly build (`1.7.0.dev20200705+cpu`) and I indeed see performance similar to 1.4.0. I am going to close the issue.
