### ISSUE TITLE
When using _MultiProcessingDataLoaderIter in Dataloader, how to add a filelock in Dataset to make the file io thread-safety?  

### ISSUE THREAD

**Issue by GeekOrangeLuYao** [pytorch/pytorch#41064]
## ❓ Questions and Help
When I use DataLoader to load a dataset consisted of several files, I find when I cannot set the `num_workers > 0` because it will occurs a Error `TypeError: function takes exactly 5 arguments (1 given)`.

When I set `shuffle = True` into DataLoader,  this Error when occur randomly (e.g. I will train it for several epochs and the Error happens), however, when I set the `shuffle = False`, the error will appear in the first several minibatch.

I'm very sure that the bug is from the _MultiProcessingDataLoaderIter in Dataloader and the data I've prepared is correct, because if I set the `num_workers = 0`, my code can finished the training process.

### Code Details
I offer some details here, and hope someone can help me 😭

This is the Dataset:
```python
class ChunkDataset(Dataset):
    def __init__(self, feat_scp_file, chunk_size_range=(100, 500)):
        super(ChunkDataset, self).__init__()
        self.feat_scp_file = feat_scp_file

        self.feature_reader = SynchronizedFeatureReader(self.feat_scp_file)
        self.utt_list = self.feature_reader.get_utt_list()
        self.min_chunk_size = chunk_size_range[0]
        self.max_chunk_size = chunk_size_range[1]

    def __len__(self):
        return len(self.feature_reader)

    def __getitem__(self, item):
        utt_id = self.utt_list[item]
        feat = self.feature_reader[utt_id]
        feat_len = feat.shape[0]

        chunk_size = random.randint(self.min_chunk_size, self.max_chunk_size)
        chunk_start = random.randint(0, max(0, feat_len - chunk_size))

        return feat[chunk_start: min(chunk_start + chunk_size, feat_len), :]
```
The key part in it is the SynchronizedFeatureReader: ( I wrapper the data reader many times because other function need it ,not just for pytorch)
```python
class SynchronizedFeatureReader(object):
    def __init__(self, scp_file):
        self.scp_file = scp_file
        self.feat_dict = ScriptReader(scp_file)

    def _load(self, utt_id):
        return self.feat_dict[utt_id]

    def __len__(self):
        return len(self.feat_dict)

    def __getitem__(self, item):
        return self.feat_dict[item]

    def __iter__(self):
        for (utt_id, feat) in self.feat_dict:
            yield utt_id, feat

    def get_utt_list(self):
        return self.feat_dict.index_keys
```

And finally, you can see how I read the data:
```python
class ScriptReader(Reader):
    def __init__(self, ark_scp):
        self.fmgr = dict()
        def addr_processor(addr):
            addr_token = addr.split(":")
            if len(addr_token) == 1:
                raise ValueError("Unsupported scripts address format")
            path, offset = ":".join(addr_token[0:-1]), int(addr_token[-1])
            return (path, offset)

        super(ScriptReader, self).__init__(ark_scp,
                                           value_processor=addr_processor)

    def __del__(self):
        for name in self.fmgr:
            self.fmgr[name].close()

    def _open(self, obj, addr):
        if obj not in self.fmgr:
            self.fmgr[obj] = open(obj, "rb")
        arkf = self.fmgr[obj]
        arkf.seek(addr)
        return arkf

    def _load(self, key):
        path, addr = self.index_dict[key]
        fd = self._open(path, addr) 
        obj = io.read_float_mat_vec(fd, direct_access=True) 
        return obj
```
I have to explain here the `io.read_float_mat_vec` is writtern by myself, it will read the first two bytes to make sure the `fd.seek()` is right. The assert is like:
```python
def expect_binary(fd):
    flags = bytes.decode(fd.read(2))
    throw_on_error(flags == '\0B', f'Expect binary flag, but gets {flags}')
```
and you will find the the flags will be wrong when dataloader run.

The `scp_file` I used is like this , It's come from other code which is not important for this issue, I think. The format is like:
```
a0001 file.vec.ark:9
a0002 file.vec.ark:2076
a0003 file.vec.ark:4143
a0004 file.vec.ark:6210
a0005 file.vec.ark:8277
a0006 file.vec.ark:10344
......
```

The Error log is:
```
Traceback (most recent call last):
  File "TestFeatureReader.py", line 172, in <module>
    main()
  File "TestFeatureReader.py", line 168, in main
    process.test_data(tr_dataloader)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/process/test_process.py", line 31, in test_data
    for index, (data, label) in enumerate(data_loader):
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)
```
I find the mistakes occurs because the reader is not thread-safe, and I try to fix this in the following methods, but the code won't run as I expect because the file-lock won't work in the DataLoader.

### Environments
Linux Ubuntu
Python3.6.3
torch 1.5.0+cu92
I think some other key lib is all from python built-in and I'm sure all my experiment is run in the `__name__ == '__main__'`

### Some method I have tried
I want to make the reader thread-safe, but I think it cannot do because the pytorch Dataloader deep-copy dataset when creating-fetcher so that the file lock is not shared by several process in _MultiProcessingDataLoaderIter. But I have read the code for many times, and I think it could be happen because it's always `self.dataset = dataset` and I cannot solve this problem because I cannot make a log for that except changing the pytorch code. 😭

Here are some details I have tried, it may be helpful for you to learn more about what I wanna do.

#### 1. Try to remove the `self.fmgr` so that every fetch will get the its own `fd`.
Yes, It worked, but it will cost me many requests for `fd = open()` and `fd.close()` and that's not satisfy me.

#### 2. Add a `multiprocessing.Lock()` For every fd I have store in `self.fmgr`
I change the code like this but it will not work.
```python
class ScriptReader(Reader):
    def __init__(self, ark_scp):
        self.fmgr = dict()
        self.main_lock = Lock()

        def addr_processor(addr):
            addr_token = addr.split(":")
            if len(addr_token) == 1:
                raise ValueError("Unsupported scripts address format")
            path, offset = ":".join(addr_token[0:-1]), int(addr_token[-1])
            return (path, offset)

        super(ScriptReader, self).__init__(ark_scp,
                                                              value_processor=addr_processor)

    def __del__(self):
        for name in self.fmgr:
            self.fmgr[name]['handle'].close()

    def _load(self, key):
        path, addr = self.index_dict[key]

        self.main_lock.acquire()
        if path not in self.fmgr:
            # print("Create new lock")
            self.fmgr[path] = dict()
            self.fmgr[path]['handle'] = open(path, "rb")
            self.fmgr[path]['lock'] = Lock()
        self.main_lock.release()

        lock = self.fmgr[path]['lock']
        lock.acquire()
        fd = self.fmgr[path]['handle']
        fd.seek(addr)
        obj = io.read_float_mat_vec(fd, direct_access=True)
        lock.release()
        return obj
```
I also consider that the `if path not in self.fmgr:` may cause a bug, so I just add a `main_lock` for it will be safe to `open()`. But unluckily, it failed! 😭
The error report is also the `fd.seek()` is bad.
```
fd = 140574381870952
Expect binary flag, but gets +Z
fd = 140574381870952
Expect binary flag, but gets
Traceback (most recent call last):
  File "TestFeatureReader.py", line 172, in <module>
fd = 140574381870952
    main()
  File "TestFeatureReader.py", line 168, in main
Expect binary flag, but gets @b
    process.test_data(tr_dataloader)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/process/test_process.py", line 31, in test_data
    for index, (data, label) in enumerate(data_loader):
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)
```

I have to repeat that I have checked the data many times, the `io.read_float_mat_vec` will check the head two bytes to ensure `fd.seek` is in a right location to read, but it's obviously wrong.

#### 3. Use the file lock lib
I have also use other lib to lock the file like:
* fcntl
* portalocker

You can find what these lib can do in github.

### Some questions or Suggestiongs maybe
Sorry for costing you so much time.
* How can I solve the problem? Use lock more smartly, some other beautiful tricks or use some other thread-safe method like `Queue` or something?
* I wonder **Whether the Dataset will be deep-copy several times when create_fetch in the _worker_loop** ? So that the lock won't work? I read the code about Dataloader and I'm convinced that the dataset I have made is always *single-instance*, but my experiment reminds me that the `id(lock)` to cause the bugs is different if you use `try-catch` to print the except error and the lock. It is very strange!
* I find many other people ask a similar question and they just adjust the `num_workers == 0` to solve the problem. Can the community build a more safe Dataset class or provide some good examples for the users?

cc @SsnL

**Comment by ag14774** [comment]
I would go with your choice num 1 where you open and close for every fetch. It is quite a common practice in my opinion. Even the pytorch tutorial here: https://pytorch.org/tutorials/beginner/data_loading_tutorial.html does exactly that where they use `io.imread` to read the image for every __getitem__ which would effectively open and close a new fd. Other alternatives would be to use some other process like memcache to do the loading and then your dataset would just communicate with that process instead of loading directly from files.

**Comment by SsnL** [comment]
Is there no traceback for TypeError?

**Comment by GeekOrangeLuYao** [comment]
> Is there no traceback for TypeError?

I add a `try-catch` to debug, so some traceback is missing, it's:
```python
Traceback (most recent call last):
  File "TestFeatureReader.py", line 168, in <module>
    main()
  File "TestFeatureReader.py", line 164, in main
    process.test_data(tr_dataloader)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/process/test_process.py", line 31, in test_data
    for index, (data, label) in enumerate(data_loader):
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/work_nfs2/lycheng/env/anaconda3/anaconda_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "TestFeatureReader.py", line 96, in __getitem__
    feat = self.feature_reader[utt_id]
  File "TestFeatureReader.py", line 49, in __getitem__
    return self.feat_dict[item]
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/lib/kaldi_python_io/inst.py", line 190, in __getitem__
    return self._load(index)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/lib/kaldi_python_io/inst.py", line 265, in _load
    obj = io.read_float_mat_vec(fd, direct_access=True)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/lib/kaldi_python_io/_io_kernel.py", line 390, in read_float_mat_vec
    expect_binary(fd)
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/lib/kaldi_python_io/_io_kernel.py", line 45, in expect_binary
    throw_on_error(flags == '\0B', f'Expect binary flag, but gets {flags}')
  File "/home/lycheng/workspace/corecode/Python/SRE-Pytorch-Tools/lib/kaldi_python_io/_io_kernel.py", line 21, in throw_on_error
    raise RuntimeError(info)
RuntimeError: Expect binary flag, but gets 6:
```
If I set the `shuffle=False`, there could be no traceback about the `fetcher`, but only the `TypeError: function takes exactly 5 arguments` because the problem is randomly happen when the `fd.seek` is wrong between two process.

**Comment by SsnL** [comment]
Is your `fmgr` empty in the data loader workers? E.g., if you use the reader outside the dataloader, the `fmgr` cache will be filled and the worker processes (assuming linux and `fork`) will all share the same `fd`s for those entries, which might cause trouble. Try clearing it in `worker_init_fn`.

Also, could you isolate the problem by trying to reproduce without the data loader framework? It seems just not playing nicely with multiprocessing. What if you just start two `mp.Process`, send the reader to each, and let them read all entries?

**Comment by GeekOrangeLuYao** [comment]
> Is your `fmgr` empty in the data loader workers? E.g., if you use the reader outside the dataloader, the `fmgr` cache will be filled and the worker processes (assuming linux and `fork`) will all share the same `fd`s for those entries, which might cause trouble. Try clearing it in `worker_init_fn`.
> 
> Also, could you isolate the problem by trying to reproduce without the data loader framework? It seems just not playing nicely with multiprocessing. What if you just start two `mp.Process`, send the reader to each, and let them read all entries?

I think the `fmgr` is empty when the program run. When I get a new `IOWrapper`, :the fmgr will set a new (key -> value) pair in it, so that we can get the `fd` without opening and closing it frequantly.

Yes, I have tried only use `mp.Process` already.  The code is like this:
```python
def load_utt(reader, utt_id):
        return reader[utt_id].shape

def test_multiprocess_script_reader(scp, max_num = 100):
    # test ScriptReader
    scp_reader = ScriptReader(scp)
    pool = Pool(processes=8)
    try:
        utt_list = scp_reader.index_keys
        result_list = list()
        num_done = 0
        for utt_id in utt_list:
            result = pool.apply_async(load_utt, (scp_reader, utt_id))
            result_list.append(result)
            num_done += 1
            if num_done > max_num:
                break
        pool.close()
        pool.join()
        print("script_reader finished!")
    except TypeError as e:
        print("Using ScriptReader leads to the error:\n", e)
    finally:
        del scp_reader
        del pool

    # test SynchronizedScriptReader
    scp_reader = SynchronizedScriptReader(scp)
    pool = Pool(processes=8)
    try:
        utt_list = scp_reader.index_keys
        result_list = list()
        num_done = 0
        for utt_id in utt_list:
            result = pool.apply_async(load_utt, (scp_reader, utt_id))
            result_list.append(result)
            num_done += 1
            if num_done > max_num:
                break
        pool.close()
        pool.join()
        print("synchronized_script_reader finished!")
    except TypeError as e:
        print("Using SynchronizedScriptReader leads to the error:\n", e)
    finally:
        del scp_reader
        del pool

    print("TEST *multiprocess_script_reader* DONE!")
```
The `ScriptReader` is the initially version, the `SynchronizedScriptReader` is add a mutex to control all the `fd.seek`. Actually, in my computer, two `try-catch` can run completely without `except`, which is very strange.  The `max_num = 0` is just a limit to save time for testing. But when the process move to Pytorch, that causes a error.

**Comment by SsnL** [comment]
> I think the fmgr is empty when the program run

@GeekOrangeLuYao Yes, but I am asking whether it is empty when you start the workers. If you call the reader in main process before starting an epoch, it won't be empty.

**Comment by GeekOrangeLuYao** [comment]
> > I think the fmgr is empty when the program run
> 
> @GeekOrangeLuYao Yes, but I am asking whether it is empty when you start the workers. If you call the reader in main process before starting an epoch, it won't be empty.

I think when I use 
```python
for index, (data, label) in enumerate(data_loader):
     # somethings
     print(f"data = {data.shape}")
     pass
```
Here, the `fmgr` is empty.
However, I find the error do not happen the first several batches, which means, it can print the first several batchs, and then get error. The

**Comment by GeekOrangeLuYao** [comment]
> > I think the fmgr is empty when the program run
> 
> @GeekOrangeLuYao Yes, but I am asking whether it is empty when you start the workers. If you call the reader in main process before starting an epoch, it won't be empty.

Thanks for your tips about whether the `fmgr` is empty. I find I use another function will make the `fmgr` not empty. Besides, I change the `multiprocess.Lock()` to `multiprocess.Manager().Lock()` and solve the problem.
