### ISSUE TITLE
How to use (torch.utils.data.DataLoader) in android? 

### ISSUE THREAD

**Issue by Micla-SHL** [pytorch/pytorch#41065]
Now , I try running PSENet in Android .  Project urls : https://github.com/whai362/PSENet 
Its testcode need  （torch.utils.data.DataLoader）。 you can look PSENet Project .> test_ic15.py    72 lines 
I have torch==1.4.0    change PSENet.pth ==> PSENet.pt  and  model load  in Android is OK。But，
next I don't know what to do.
       I want  a little alittle translation the PSENet testcode in Android 。
       Sorry，my English is very poor, if you can, give me some android advice

**Comment by mruberry** [comment]
Hi @Micla-SHL, sorry you're having a problem with PyTorch on Android.

You should try asking this question on the PyTorch Forums (https://discuss.pytorch.org/) and reviewing the PyTorch Android documentation (https://pytorch.org/mobile/android/).

**Comment by Micla-SHL** [comment]
I‘m sorry, now，I can't access https://discuss.pytorch.org/.  the PyTorch Android document help me  load model in Android，but  not have next action

**Comment by mruberry** [comment]
I'm sorry, I'm not sure I understand what you mean by "next action." The documentation describes how to perform inference using the model.
