### ISSUE TITLE
TorchScript to ONNX weird conversion failure when using nn.Upsample layer from saved model

### ISSUE THREAD

**Issue by clementabary** [pytorch/pytorch#41072]
## 🐛 Bug

`nn.Upsample` layer converts ok from PyTorch to ONNX, but fails from TorchScript to ONNX with type inconsistency, only when it is saved & loaded beforehand.

## To Reproduce

```python
import torch as th
import onnx
import onnxruntime


model = th.nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)
dummy_input = th.randn(1, 3, 256, 256, dtype=th.float32)
output = model(dummy_input)


# We trace the model and convert it right away : JIT model check is OK
traced_model = th.jit.trace(model, dummy_input)
th.onnx.export(traced_model, dummy_input, "ts_nosave_upsample.onnx",
               example_outputs=(output), verbose=True, opset_version=12)
onnx_model = onnx.load("ts_nosave_upsample.onnx")
onnx.checker.check_model(onnx_model, full_check=True)
ort_session = onnxruntime.InferenceSession("ts_nosave_upsample.onnx")


# Here we save the modules first, load them..
th.save(model, "upsample.pt")
th.jit.save(traced_model, "upsample.ts")
model = th.load("upsample.pt")
traced_model = th.jit.load("upsample.ts")

# and only then convert to ONNX..
th.onnx.export(model, dummy_input, "pt_upsample.onnx",
               example_outputs=(output), verbose=True, opset_version=12)
th.onnx.export(traced_model, dummy_input, "ts_upsample.onnx",
               example_outputs=(output), verbose=True, opset_version=12)

# so we can load them afterwards
pt_onnx_model = onnx.load("pt_upsample.onnx")
ts_onnx_model = onnx.load("ts_upsample.onnx")

# This model is OK
onnx.checker.check_model(pt_onnx_model, full_check=True)
ort_session = onnxruntime.InferenceSession("pt_upsample.onnx")

# Fails : ----> type inconsistency error in mul nodes (float64 instead of float32) <----
onnx.checker.check_model(ts_onnx_model, full_check=True)
ort_session = onnxruntime.InferenceSession("ts_upsample.onnx")
```

## Expected behavior

`onnx.checker.check_model` and `onnxruntime` should run OK for TorchScript upsampling layer saved and loaded beforehand.

What I get instead is : 
```
ValidationError: B has inconsistent type tensor(double)
```
Nodes `Mul 5` and `Mul 13` have scale factor casted to type `float64` instead of `float32`. I don't get how saving/loading the JIT module ends up with this kind of weird error.

## Environment

 - PyTorch : 1.5.0
- ONNX : 1.7.0
- onnxruntime : 1.3.0

cc @suo @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Yes, this could be related to the known issue with ScriptModules where the lack of type information does not allow us to export the correctly. There's some work related to type inference underway and we can test this scenario when that lands.

**Comment by garymm** [comment]
Seems to work with PyTorch 1.10.0.
Please open a new issue if this is still a problem on the latest PyTorch nightly version.
