### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by arsalan993** [pytorch/pytorch#4108]
I am running a code from repository that imports pytorch via anaconda but i am getting this error

(myroot3) arslan993@ubuntu:~/Desktop/crnn.pytorch$ python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import torch
  File "/home/arslan993/.conda/envs/myroot3/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/arslan993/.conda/envs/myroot3/lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN4thpp10THCSTensorIlEC1EP8THCStateP14THCSLongTensor

**Comment by zou3519** [comment]
How did you install pytorch? Does uninstalling/reinstalling help? What version of ubuntu are you using / is there CUDA?

**Comment by arsalan993** [comment]
Issue resolved .. i installed it via conda and it wasnt working correctly but when i installed it using pip it worked like a charm.
