### ISSUE TITLE
This is a Bug? Or is my problem? For torch.index_select()

### ISSUE THREAD

**Issue by kenjewu** [pytorch/pytorch#4109]
I used the function, torch.index_select(), to do something. But always have some problem. 
the error:
    conv_rs_sub1 = tr.index_select(conv_rs_single, 2, sub1_index)
RuntimeError: index_select(): argument 'index' (position 2) must be Variable, not torch.LongTensor

my sub code:
sub1_index = tr.from_numpy(np.arange(0, candi_index, step=1)).type(tr.LongTensor)
conv_rs_sub1 = tr.index_select(conv_rs_single, 2, sub1_index)

the conv_rs_single size is (1, 1, 30, 220)

Please help me .

**Comment by albanD** [comment]
I guess some of the arguments to the function are `Variable`s ? In that case all `Tensor` arguments should be wrapped into a `Variable`.
