### ISSUE TITLE
Error when exporting torch model  HRNet-Semantic-Segmentation to onnx

### ISSUE THREAD

**Issue by sakura-iv** [pytorch/pytorch#41118]
## ❓ Questions and Help

I am trying to transform torch HRNet-Semantic-Senmentation model to onnx model, but I met the error:
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

> 
Traceback (most recent call last):
  File "tools/torch2onnx.py", line 118, in <module>
    main()
  File "tools/torch2onnx.py", line 112, in main
    operator_export_type = torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
**RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible**
> 

The whole project is here: [https://github.com/HRNet/HRNet-Semantic-Segmentation](url)
And the model could be downloaded here: [https://1drv.ms/u/s!Aus8VCZ_C_33gSlK7Fju_sXCxFUt?e=WZ96Ck](url)

The question is very similar with #23474 , but we are using different models, and I could not fix my error by the same method. And I heard that this error may be because of pytorch 1.1 version, but this project could only ran on torch 1.1 or torch 0.4.1, so I think I could not update it either.

What should I do? Could anyone help me?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@sakura-iv  - are you using ONNX_ATEN_FALLBACK for the export? Can you try ONNX export also.

Also, can you share a smaller, more distilled, repro for this issue, including the export code. It will help up investigate faster.

**Comment by sakura-iv** [comment]
Wow I tried ONNX_ATEN export and it worked. Many many thanks !!!!

**Comment by sakura-iv** [comment]
I am so sorry that I still have some problems... I found that if I export this torch model with 
> 
operator_export_type = torch.onnx.OperatorExportTypes.ONNX_ATEN
> 
I could not transform this model to tensorflow model, since it raises 
>
 KeyError: 'org.pytorch.aten'
> 
So I think I have to export this model with onnx operator. 

My export code is :
`# ------------------------------------------------------------------------------
# Copyright (c) Microsoft
# Licensed under the MIT License.
# Written by Ke Sun (sunk@mail.ustc.edu.cn)
# ------------------------------------------------------------------------------

import argparse
import os
import pprint
import shutil
import sys

import logging
import time
import timeit
from pathlib import Path

import numpy as np

import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn

import _init_paths
import models
import datasets
from config import config
from config import update_config
from core.function import testval, test
from utils.modelsummary import get_model_summary
from utils.utils import create_logger, FullModel


def parse_args():
    parser = argparse.ArgumentParser(description='Train segmentation network')

    parser.add_argument('--cfg',
                        help='experiment configure file name',
                        required=True,
                        type=str)
    parser.add_argument('opts',
                        help="Modify config options using the command-line",
                        default=None,
                        nargs=argparse.REMAINDER)

    args = parser.parse_args()
    update_config(config, args)

    return args


def main():
    args = parse_args()

    logger, final_output_dir, _ = create_logger(
        config, args.cfg, 'test')

    logger.info(pprint.pformat(args))
    logger.info(pprint.pformat(config))

    # cudnn related setting
    cudnn.benchmark = config.CUDNN.BENCHMARK
    cudnn.deterministic = config.CUDNN.DETERMINISTIC
    cudnn.enabled = config.CUDNN.ENABLED

    # build model
    model = eval('models.' + config.MODEL.NAME +
                 '.get_seg_model')(config)

    dump_input = torch.rand(
        (1, 3, config.TRAIN.IMAGE_SIZE[1], config.TRAIN.IMAGE_SIZE[0])
    )
    logger.info(get_model_summary(model.cuda(), dump_input.cuda()))

    if config.TEST.MODEL_FILE:
        model_state_file = config.TEST.MODEL_FILE
    else:
        model_state_file = os.path.join(final_output_dir,
                                        'final_state.pth')
    logger.info('=> loading model from {}'.format(model_state_file))

    pretrained_dict = torch.load(model_state_file)
    model_dict = model.state_dict()
    pretrained_dict = {k[6:]: v for k, v in pretrained_dict.items()
                       if k[6:] in model_dict.keys()}
    for k, _ in pretrained_dict.items():
        logger.info(
            '=> loading {} from pretrained model'.format(k))
    model_dict.update(pretrained_dict)
    model.load_state_dict(model_dict,strict=False)

    os.environ["CUDA_VISIBLE_DEVICES"] = "2"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model=model.to(device)


    model.eval()
    x = torch.randn(1, 3, 512, 1024, requires_grad=True)
    x=x.to(device)

    torch.onnx.export(model,  # model being run
                      x,  # model input (or a tuple for multiple inputs)
                      'to_onnx.onnx',  # where to save the model (can be a file or file-like object)
                      export_params=True,  # store the trained parameter weights inside the model file
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names=['input'],  # the model's input names
                      output_names=['output1'],  # the model's output names
                      **operator_export_type = torch.onnx.OperatorExportTypes.ONNX_ATEN**
                      )



if __name__ == '__main__':
    main()
`

So... how should I solve this error? [crying...]

> 
**RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible**
>
