### ISSUE TITLE
import error when runing pytorch without cuda

### ISSUE THREAD

**Issue by WuJunde** [pytorch/pytorch#4112]
I download the the cpu version through 
'conda install pytorch torchvision -c pytorch'
when I run 'import torch'
it comes:
Traceback (most recent call last):
  File "/home/XXX/.PyCharmCE2017.1/config/scratches/scratch.py", line 1, in <module>
    import torch
  File "/home/XXX/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

libcudart.so.8.0 is a cuda file, but I select the no cuda version,why it still need it.

can I run torch without cuda?

**Comment by rhymebumblebutt** [comment]
#4133

**Comment by ozancaglayan** [comment]
As far as I understand, there's no CPU version so far. When you click on `None` on pytorch web site, you can see that it lists the same installation command as the CUDA8 link. This can be a mistake in the web page. Let's ask @soumith for clarifications.

**Comment by soumith** [comment]
the same binary works for CPU-only machines as well.

If you see in `/home/XXX/anaconda3/lib/`, you will see `libcudart.so.8.0`, because invoking `conda install pytorch torchvision -c pytorch` should've installed `cudatoolkit` package in anaconda.

**Comment by WuJunde** [comment]
I know, it means cpu version still need the cuda to install.
I shouldn't installed cuda7 in my anaconda before I installed pytorch.
It works after I uninstall the origin cuda and run 'conda install pytorch torchvision -c pytorch' again
Thanks for everybody.
