### ISSUE TITLE
torch.from_numpy() ignores torch.set_default_tensor_type()

### ISSUE THREAD

**Issue by djsaunde** [pytorch/pytorch#4114]
I am using:

```torch.set_default_tensor_type('torch.cuda.FloatTensor')```.

However, on reading a `.npy` file from disk, the output of `type([loaded Tensor])` is `torch.FloatTensor`, mismatching what you might expect (`torch.cuda.FloatTensor`).

Should the `set_default_tensor_type` function be extended to such cases?

**Comment by apaszke** [comment]
Default tensor type shouldn’t have any effect on `from_numpy`. The documentation says that it always returns a tensor if type corresponding to that of np array
