### ISSUE TITLE
torch.distributed C++ tests not run in CI

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#41143]
C++ tests defined in `torch/lib/c10d/test` are not run in CI. Same thing occurs to RPC C++ tests. 

cc @ezyang @gchanan @zou3519 @seemethere @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jjlilley @mruberry

**Comment by malfet** [comment]
Some of the tests in that folder needs to be converted to gtest framework, for example: https://github.com/pytorch/pytorch/issues/41929

**Comment by rohan-varma** [comment]
I believe @osalpekar/@mrshenli/@malfet worked on this last half, are we able to close this issue out?

**Comment by malfet** [comment]
Yes
