### ISSUE TITLE
Problem about type conversion between quantized module and float module

### ISSUE THREAD

**Issue by linbinskn** [pytorch/pytorch#41166]
##### Problem description
I have read the source code about quantization. I found that during the quantizing process. The module in DEFAULT_MODULE_MAPPING will be converted to low-bit type such as integer. But when the module is not in the map, the quantization for it will be skipped. The skipped module will still be a float type. So how can the different type of module(quantized module and float module) connected each other? Is there any data covert between them? I think there will be something wrong if a float module's output is float and the next module(quantized module) can only process integer. I find no conversion between them.

**Comment by agolynski** [comment]
We typically use pytorch forum for support questions, did you try posting there?

**Comment by agolynski** [comment]
I am going to close this for now. @linbinskn: please post on PT quantization forum https://discuss.pytorch.org/c/quantization/.
