### ISSUE TITLE
Why the CPU utility has reached about 100% when i run libtorch model in VS

### ISSUE THREAD

**Issue by MrCrazyCrab** [pytorch/pytorch#41172]
i change my pytorch model into libtorch one and runs it in VS2017. However, i found the consumption of GPU is about 1G which is same as pytorch model run in the python. It is strange that the CPU utility has reached about 100% and never decreased until the program is over.
How should i to slove the p[roblem and decrease the pre-consumption of CPU resource?
Can anyone help me? thanks！
I use windows10 libtoch1.4 cuda10 Vs2017

**Comment by agolynski** [comment]
changing python frontend to c++ doesn't always give you GPU memory savings, tensors would still need to be allocated on GPU, right?

What is pre-consumption of CPU in this context? How does it compare to pytorch and how the runtimes compare?

**Comment by agolynski** [comment]
I am going to close this for now. Feel free to reopen with more data.
