### ISSUE TITLE
Jit remove mutation pass does not replace zero_ and fill_

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#41192]
## 🐛 Bug

Torch jit remove tensor mutation removes inplace ATen ops and replaces them with the equivalent functional op. The logic to map any inplace op to an equivalent op is to remove the '\_' suffix in op's name. But this logic does not cover a number of inplace ops (fill_, zero_, copy_ etc.).

## To Reproduce

```python
    class CopyModel(torch.nn.Module):
        def forward(self, x, data):
            x = x + 2
            x[1:3] = data
            return x

    m = torch.jit.script(CopyModel())
    m.eval()

    m._c.dump()
    freezed_m = torch._C._freeze_module(m._c)
    method_graph = freezed_m._get_method('forward').graph
    torch._C._jit_pass_remove_mutation(method_graph)

    print(method_graph)
```

## Expected behavior

The inplace op in the following graph should be replaced by an equivalent op (such as zeros_like).

```
graph(%self : __torch__.___torch_mangle_0.CopyModel,
      %x.1 : Tensor):
  %3 : int = prim::Constant[value=2]() # test_onnx.py:204:20
  %2 : int = prim::Constant[value=1]()
  %x.3 : Tensor = aten::add(%x.1, %3, %2) # test_onnx.py:204:16
  %5 : Tensor = aten::zero_(%x.3) # test_onnx.py:205:19
  return (%5)
```

cc @suo @gmagogsfm

**Comment by neginraoof** [comment]
cc @eellison @bzinodev

**Comment by eellison** [comment]
Do you mind if I make this into a more concrete issue ? the repro`x[1:3] = data` is a different issue than the `aten::zero_` issue. It is only expected than remove mutation does not replace all inplace ops - it only replaces ops that have an equivalent functional lowering.

**Comment by neginraoof** [comment]
We see a similar issue in x[1:3] = data which translates to aten:copy_.
But yeah we can definitely look into certain cases for now.
Thanks.

**Comment by neginraoof** [comment]
@eellison Thanks!
