### ISSUE TITLE
Kill NN buffers harder

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4120]
In #4096, we are unable to delete all of the special-casing for NN because of buffers. @colesbury has an idea for how to get rid of buffer parameters from NN entirely. The design:

* Intuitively, buffers should be returned from forwards, and taken as arguments to backwards
* Since you don't want to actually see the buffers if you're an ordinary user, there should be a NATIVE function `foo`, which invokes `foo_forward` that actually implements a derivative

Now we no longer need to know about the correspondence between `foo_forward` and `foo` because the implementation of `foo` is acceptable for both Tensor and Variable.

This will require reworking how NN codegen in ATen works, because you need to actually generate `foo` as a native function now (and not the way it is right now.) We recommend merging #4096 before working on this. CC @lantiga 

cc @albanD @mruberry

**Comment by apaszke** [comment]
Does this mean that backward functions will be removed from the interface?

**Comment by ezyang** [comment]
There certainly won't be "user friendly" versions of the backwards functions. Which is already the case.

**Comment by apaszke** [comment]
So the idea is that the friendly method handles creating the graph if it’s a variable so it’s easy to use, and if it’s a tensor then it means you can’t get the gradient unless you create the buffers in some super hacks way. Is that right?

**Comment by ezyang** [comment]
Yes. Well, we could expose `foo_forward` and `foo_backward` and it wouldn't be a very nice interface but it would get the job done.

**Comment by lantiga** [comment]
I like this. What about the upcoming merging between Tensors and Variables?

**Comment by colesbury** [comment]
@apaszke, the difference in API is pretty small from today: buffers are currently arguments to the `foo_forward` functions. They would become return values.

**Comment by apaszke** [comment]
That all sounds good, I was mostly curious what's the idea :+1:

**Comment by albanD** [comment]
I don't think this is relevant anymore as it discusses the THNN binding which are (almost) completely removed now.
