### ISSUE TITLE
ERROR : torch not compiled with cuda enabled

### ISSUE THREAD

**Issue by FRahmani368** [pytorch/pytorch#41227]
Hi, I have an issue with using CUDA. I got this error "torch not compiled with cuda enabled" when I wanted to define a tensor on GPU.
for pytorch installation, I used:
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
and I have Geforce GTX 1080 Ti
Nvidia CUDA driver is 11.0.197. GPU version 451.48
I am using pycharm.
when I run torch.cuda.is_available() --> I get False.
What is the problem? Please advise me. thank you

cc @ezyang @seemethere @malfet @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
waht is the output of `conda info`?

**Comment by peterjc123** [comment]
@guyang3532

**Comment by FRahmani368** [comment]
conda info
     active environment : G:\Farshid\myenvs
    active env location : G:\Farshid\myenvs
            shell level : 1
       user config file : C:\Users\fzr5082\.condarc
 populated config files : C:\Users\fzr5082\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\fzr5082\.conda\pkgs
                          C:\Users\fzr5082\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\fzr5082\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\fzr5082\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False

**Comment by FRahmani368** [comment]
OS: Microsoft Windows Server 2016 Standard
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 451.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.0

**Comment by FRahmani368** [comment]
I was surprised that I do not get the error when I downgrade pytorch to 1.2 and torchvision to 0.4.0 and cudatoolkit to 10.00.
