### ISSUE TITLE
Make Collate a Class such that extension can subclass it

### ISSUE THREAD

**Issue by Haydnspass** [pytorch/pytorch#41239]
## 🚀 Feature
Make the default collate a class instead of a function so that people can subclass for new types but can still use the default collate functionality.

## Motivation
Currently, the default collate is a function that checks the type of the first element of the batch and recursively class itself when containers such as lists or tuples are used. When creating a custom collate function for a Dataset that returns multiple types this means that one has to implement all the types again. 

## Pitch
It would be useful to make the collate a class, which you can subclass.

```
class DefaultCollate:

  
  def __call__(self, batch):
      self.forward(batch)

  @staticmethod
  def forward(batch):
    r"""Puts each data field into a tensor with outer dimension batch size"""

    elem = batch[0]
    elem_type = type(elem)
    if isinstance(elem, torch.Tensor):
        # [...]
        return torch.stack(batch, 0, out=out)

    # [...]
    


class MyCollateThatSupportsNone(DefaultCollate):

    @staticmethod
    def forward(batch):

        elem = batch[0]

        if elem is None:
            return None
        else:
            return super().forward(batch)
```

## Alternatives
The current "alternative" is, I suppose?, to copy and paste the default collate and add `elif isinstance(elem, MyTYPE)` for new custom types.

**Comment by SsnL** [comment]
Relevant proposal: https://github.com/pytorch/pytorch/issues/33181, which I personally like better :)
