### ISSUE TITLE
from blob got "terminate called after throwing an instance of 'std::system_error'   what():  Unknown error -1 Aborted (core dumped) "

### ISSUE THREAD

**Issue by chuanhuayang** [pytorch/pytorch#41235]
I want build some preprocess tensor in my c++ code， example as

    # include "common/libtorch/include/torch/script.h"
    # include "common/libtorch/include/torch/csrc/api/include/torch/torch.h"
    # include <iostream>
    # include <vector>
    using namespace std;
    int main(int argc, char *argv[]) {
        // 构建示例输入
        // std::vector<torch::jit::IValue> inputs;
        std::vector<int64_t> res_data;
        res_data.resize(1 * 3* 16 * 16);
        cout << res_data.size() << endl;
        torch::Tensor res_tensor = torch::from_blob(res_data.data(),{1, 3, 16, 16}, torch::kInt64);
        cout << "OK" << endl;
    }

but i got the error:

    terminate called after throwing an instance of 'std::system_error'
    what():  Unknown error -1
    Aborted (core dumped)

my g++ version=5.5，using std=c++14 option，my libtorch version=1.5. Is someone know about this error ? thank you very much !!

    

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
@chuanhuayang 
I don't have gcc5.5 on hand, I tested your code with gcc5.4 and gcc7.3
Under, libtorch 1.5, 1.5.1 and nightly build. All works fine.

Please make sure you downloaded the correct libtorch version. libtorch has abi and non-abi version since 1.5.
And check this page see whether your CMakeList.txt is correct.
https://pytorch.org/cppdocs/installing.html#

**Comment by chuanhuayang** [comment]
thanks for your reply，I am using bazel build. maybe the error is caused by  the absence of  `-lpthread` link option.
after added this option, the error is gone!

**Comment by glaringlee** [comment]
@chuanhuayang Great! For bzl build, there is a bzl file in pytorch folder as well, you can take it as a reference.
