### ISSUE TITLE
as_tensor_list naming is dodgy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4125]
We have both `as_tensor_list` and `as_variable` in VariableType.cpp. What do you think they do? It's asymmetric:

- `as_tensor_list` just does the downcast from `Variable` to `Tensor`
- `as_variable` *creates* a variable

So they aren't inverses of each other, which is pretty confusing. There is a legitimately useful operation which upcasts from `Tensor` to `Variable` (when you know that the Tensor in question is really just a downcasted Variable)...

**Comment by apaszke** [comment]
Maybe let’s just rename the first one to upcast_variable_list?

**Comment by ezyang** [comment]
Mooted by variable tensor merge.
