### ISSUE TITLE
In DDP's reducer merge `work` and `future_work`

### ISSUE THREAD

**Issue by sinannasir** [pytorch/pytorch#41266]
DDP main structure communication hook #40848 uses separate `bucket.work` and `bucket.future_work`. These use async works `ProcessGroup::Work` and `jit::Future`, respectively.
https://github.com/pytorch/pytorch/blob/45d735208b29aaa9dcfdf4d2b426c219866a8097/torch/csrc/distributed/c10d/reducer.cpp#L592-L596

We will replace `work` by `future_work` and use `AllreduceHook` by default once `get_future` API is supported by Gloo, see #42048 . There is a PR for this issue (#41840) that can be merged `get_future` API after Gloo support and review.

NOTE: This can be done after https://github.com/pytorch/pytorch/issues/42048 is addressed.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse

**Comment by sinannasir** [comment]
We will replace `work` by `future_work` and use `AllreduceHook` by default once `get_future` API is supported by Gloo, see #42048 . There is a PR for this issue (#41840) that can be merged `get_future` API after Gloo support and review.

**Comment by agolynski** [comment]
cc: @agolynski

**Comment by rohan-varma** [comment]
cc @agolynski @SciPioneer now that the futures are merged we should be able to do this one right?

**Comment by SciPioneer** [comment]
@rohan-varma  Yeah, confirmed with @agolynski last week, this one is unblocked now.
