### ISSUE TITLE
how should I cite PyTorch in the paper?

### ISSUE THREAD

**Issue by habor777** [pytorch/pytorch#4126]
I have several experiments on PyTorch and am going to write a paper. How should I cite PyTorch?

**Comment by soumith** [comment]
For now you could cite our NIPS 2017 workshop paper that discusses just the autodiff engine of PyTorch:

```
@article{paszke2017automatic,
  title={Automatic differentiation in PyTorch},
  author={Paszke, Adam and Gross, Sam and Chintala, Soumith and Chanan, Gregory and Yang, Edward and DeVito, Zachary and Lin, Zeming and Desmaison, Alban and Antiga, Luca and Lerer, Adam},
  year={2017}
}
```

Once we release a full paper (with more authors), I will update this thread with a new citation.

**Comment by habor777** [comment]
@soumith thanks

**Comment by rasbt** [comment]
@soumith just had the same question, and maybe it wouldn't be such a bad idea to add this e.g., at the bottom of the "About" page?

**Comment by D-X-Y** [comment]
Can I use this citation?
```
@inproceedings{paszke2017automatic,
  title={Automatic differentiation in PyTorch},
  author={Paszke, Adam and Gross, Sam and Chintala, Soumith and Chanan, Gregory and Yang, Edward and DeVito, Zachary and Lin, Zeming and Desmaison, Alban and Antiga, Luca and Lerer, Adam},
  booktitle={NIPS-W},
  year={2017}
}
```

**Comment by apaszke** [comment]
Yes, that's the best thing we have right now 😕

**Comment by katrinleinweber** [comment]
Have you considered [making the code itself citable](https://guides.github.com/activities/citable-code/)?

**Comment by apaszke** [comment]
It looks like that would effectively make every PyTorch version citable separately, and I'm not sure if that's what we want. The project is under very active development, so it doesn't make sense to me to fragment those references.

**Comment by katrinleinweber** [comment]
Hm, yeah, good point. Zenodo [uses versioned DOIs by default, but mints an overarching one](https://help.zenodo.org/#versioning) as well. I guess, it's optimised for the librarian's point of view of preserving what exactly was cited and the academic's PoV of specifying which version they used. I'm not sure whether they aggregate the citation data again for a record, which is cited by different people at different "points" of the "version history", so to speak.

**Comment by rasbt** [comment]
I think Zenodo is still not considered as a publication in academic citation databases (ISI, Scopus, Google Scholar), so I would encourage authors to always cite the academic publication if possible. Regarding versions, since all PyTorch versions are available from GitHub, I also think that linking to the version on Zenodo is not really necessary in this case. E.g., one could cite it as
"... we used PyTorch v0.3 (Paszke et al) to implement x."

**Comment by jeasinema** [comment]
@soumith  Congrats! Time to cite the NeurIPS'19 paper now? https://neurips.cc/Conferences/2019/AcceptedPapersInitial

**Comment by soumith** [comment]
@jeasinema thanks, we are still in progress of writing some more papers, as there are a lot of subsystems and authors since the 0.4 release that are not covered in that paper.

**Comment by nian-liu** [comment]
@soumith what do you mean by "writing some more papers"? Now I am preparing my CVPR 2020 submission, can I cite the NeurIPS2019 paper with the authors listed on the NeurIPS'19 AcceptedPapersInitial webpage?

**Comment by soumith** [comment]
@nian-liu we will always keep https://github.com/pytorch/pytorch/blob/master/CITATION up to date.  You can use it for now. When the papers we wrap up come up on Arxiv, we will put them in the CITATION file

**Comment by brando90** [comment]
how does one add that citation to mendeley etc. Like usually the way I do it is add the paper to my library then mendeley, zotero provides the citation automagically...

**Comment by rasbt** [comment]
I think you can 

1. copy & paste it into a text file
2. save that text file as .bib
3. drag the file into the UI

**Comment by shaibagon** [comment]
How do I cite `torchvision`?

**Comment by soumith** [comment]
@aisosalo no, that's not a relevant paper.

Please cite torchvision as a github repository, for example as described here: https://academia.stackexchange.com/a/14015

@NicolasHug @fmassa @datumbox maybe add a CITATION file to the torchvision repo?

**Comment by 70nybl4nc0** [comment]
I find this citation on http://citebay.com/how-to-cite/pytorch/

```@incollection{NEURIPS2019_9015,
  title     = {PyTorch: An Imperative Style, High-Performance Deep Learning Library},
  author    = {Paszke, Adam and Gross, Sam and Massa, Francisco and Lerer, Adam and Bradbury, James and Chanan, Gregory and Killeen, Trevor and Lin, Zeming and Gimelshein, Natalia and Antiga, Luca and Desmaison, Alban and Kopf, Andreas and Yang, Edward and DeVito, Zachary and Raison, Martin and Tejani, Alykhan and Chilamkurthy, Sasank and Steiner, Benoit and Fang, Lu and Bai, Junjie and Chintala, Soumith},
  booktitle = {Advances in Neural Information Processing Systems 32},
  pages     = {8024--8035},
  year      = {2019},
  publisher = {Curran Associates, Inc.},
  url       = {http://papers.neurips.cc/paper/9015-pytorch-an-imperative-style-high-performance-deep-learning-library.pdf}
}```

**Comment by orena1** [comment]
> @nian-liu we will always keep https://github.com/pytorch/pytorch/blob/master/CITATION up to date. You can use it for now. When the papers we wrap up come up on Arxiv, we will put them in the CITATION file

Can you please update your comment? the link that you referred to is not working.

**Comment by cwpearson** [comment]
Looks like it may be here now:

https://github.com/pytorch/pytorch/blob/main/CITATION.cff

**Comment by Patataman** [comment]
Or click on "cite this repository"

![imagen](https://github.com/pytorch/pytorch/assets/10652313/2c65d29a-7fda-48b6-8e8a-a0bc6867f1a6)
