### ISSUE TITLE
'None' is not accepted as default value for Tensor Argument to function 

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#41277]
This is from ParityBench analysis, showing up as one of the most common errors:

```
@torch.jit.script
def fn(x):
    return x


fn(None)
```

```
Traceback (most recent call last):
  File "none.py", line 9, in <module>
    fn(None)
RuntimeError: fn() Expected a value of type 'Tensor' for argument 'x' but instead found type 'NoneType'.
Position: 0
Value: None
Declaration: fn(Tensor x) -> (Tensor)
Cast error details: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'at::Tensor'
```
A concrete case is [here](https://github.com/jansel/pytorch-jit-paritybench/blob/6c23f5bcbed5ad85ac21573024748b335b8019eb/generated/test_arashwan_matrixnet.py#L446)

The root cause is that TorchScript by default infers a type to be `Tensor`.

The workaround is simple, ie setting type annotation to `Optional[Tensor]`. However, I wonder if we should by default infer type to be `Optional[Tensor]`, which is more user friendly and kind of matches python convention better (ie. everything might be none).

cc @suo @gmagogsfm

**Comment by eellison** [comment]
Dup of https://github.com/pytorch/pytorch/issues/40867

**Comment by gmagogsfm** [comment]
Closing since there is a dup.
