### ISSUE TITLE
Expected integer literal for index

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#41281]
A common error in ParityBench

Repro:
```
import torch
from typing import List


@torch.jit.script
def indexing(array: List[int], idx):
    return array[idx]


print(indexing([1, 2, 3], 0))
```

```
Traceback (most recent call last):
  File "int_index.py", line 12, in <module>
    print(indexing([1, 2, 3], 0))
RuntimeError: indexing() Expected a value of type 'Tensor (inferred)' for argument 'idx' but instead found type 'int'.
Inferred 'idx' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 1
Value: 0
Declaration: indexing(int[] array, Tensor idx) -> (int)
Cast error details: Unable to cast Python instance of type <class 'int'> to C++ type 'at::Tensor'
```

[Concrete example](https://github.com/jansel/pytorch-jit-paritybench/blob/6c23f5bcbed5ad85ac21573024748b335b8019eb/generated/test_YuxianMeng_Matrix_Capsules_pytorch.py#L75)

The real issue is that `idx` argument isn't annotated, but I think there may be a chance for improvement here because the only thing that can appear in subscript of an integer array is an integer.

cc @suo @gmagogsfm

**Comment by eellison** [comment]
This is getting into the business of inferring types from usages, which we don't want to venture into just yet. The error message thrown is pretty good. Closing for now.
