### ISSUE TITLE
python value of type 'str' cannot be used as a value

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#41288]
From common errors in ParityBench

```
compile,58,RuntimeError: python value of type 'str' cannot be used as a value:,"RuntimeError: 
python value of type 'str' cannot be used as a value:
  File ""/tmp/paritybenchydc_9oju/pbg51yh9q6.py"", line 51
    def forward(self, x):
        x = functional.batch_norm(x, self.running_mean, self.running_var, self.weight, self.bias, self.training, self.momentum, self.eps)
        if self.activation == ACT_RELU:
                              ~~~~~~~~ <--- HERE
            return functional.relu(x, inplace=True)
        elif self.activation == ACT_LEAKY_RELU:
```

Code example is [here](https://github.com/jansel/pytorch-jit-paritybench/blob/6c23f5bcbed5ad85ac21573024748b335b8019eb/generated/test_zllrunning_face_parsing_PyTorch.py#L533)

cc @suo @gmagogsfm

**Comment by suo** [comment]
We do not allow users to close over globals in torchscript, as TorchScript functions need to not contain any references to the outer Python scope. The error message can be improved here by checking if the symbol (`ACT_RELU`) is available in the Python `globals()` table and error with a more specific message if it is.

**Comment by gmagogsfm** [comment]
> We do not allow users to close over globals in torchscript, as TorchScript functions need to not contain any references to the outer Python scope. The error message can be improved here by checking if the symbol (`ACT_RELU`) is available in the Python `globals()` table and error with a more specific message if it is.

Thanks! I will try to improve the error message.

**Comment by gmagogsfm** [comment]
## To Reproduce

```
import torch


MY_STR_CONST = "Hi, I am a string, please realize I am a constant"


@torch.jit.script
def fn():
    return MY_STR_CONST


print(fn())
```
```
Traceback (most recent call last):
  File "closed_over_string.py", line 8, in <module>
    def fn():
  File "/private/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 929, in script
    fn = torch._C._jit_script_compile(
RuntimeError:
python value of type 'str' cannot be used as a value:
  File "closed_over_string.py", line 9
@torch.jit.script
def fn():
    return MY_STR_CONST
           ~~~~~~~~~~~~ <--- HERE
```

**Comment by gmagogsfm** [comment]
Any suggestion on how to implement it? The only way I can think of is improving ResolutionCallBack function to tell caller whether an object is in globals() of frame/closure/env or not. But it seems a bit complicated.
