### ISSUE TITLE
Conda with cudatoolkit=10.2 don't work if you don't have a Cuda compatible card.

### ISSUE THREAD

**Issue by BurguerJohn** [pytorch/pytorch#41296]
## 🐛 Bug

From what i could gather at last it seen to be caused by not having a cuda compatible card.
I use a computer without cuda to develop to other computers.
This error don't occur by changing cudatoolkit to 10.1

 ctypes.CDLL(dll)
File "[***]/ctypes__init__.py", line 364, in init self._handle = _dlopen(self._name, mode) OSError: [WinError 126] The specified module could not be found

## To Reproduce

1. Install torch on miniconda: conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
2. Try to execute a .py file that call torch without having a CUDA card.

## Expected behavior

It should work the script unless I plan to run something using CUDA

**Comment by peterjc123** [comment]
Fixed in master. We now allow users to run `import torch` with the cuda variant on a CPU only machine.
