### ISSUE TITLE
Determinant computation is slow on CUDA for singular matrices

### ISSUE THREAD

**Issue by n-gao** [pytorch/pytorch#41308]
## 🐛 Bug
All determinant functions, `torch.det`, `torch.logdet` and `torch.slogdet`, are extremely slow if the input is singular, so its determinant is 0. This does not affect the CPU implementation.

#### Singular matrix
```python
import torch
singular_matrix = torch.tensor([
    [1., 2.],
    [0.5, 1.]
])
x = torch.stack([singular_matrix]*128, 0).cuda()
%timeit torch.det(x); torch.cuda.synchronize()
#480 ms ± 58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
#### Non-singular matrix
```python
x = torch.randn_like(x).cuda()
%timeit torch.det(x); torch.cuda.synchronize()
#680 µs ± 34.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

## Expected behavior
The performance should be better and at best case be as good as for regular matrices or at least match the CPU performance.

## Environment
 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): Windows 10 2004
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.4
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: Nvidia GTX 1050
 - Any other relevant information:

## Additional context

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi @VitalyFedyunin

**Comment by mszhanyi** [comment]
@n-gao , could your try install the nightly build? I tested in windows and the issue doesn't exist

**Comment by n-gao** [comment]
I can confirm that PyTorch 1.6 fixes this on Windows and Linux! Thanks for the notice.
