### ISSUE TITLE
Input strides are not propagated for unary ops

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#41314]
## 🐛 Bug

#38895 broke stride propagation for unary operations, now output is contiguous regardless of what the input was

## To Reproduce

```
ipython -c "import torch; a=torch.randn(2,3).t(); print(a.sin().stride())"
(2, 1)
```

## Expected behavior

For unary operations, strides of the output should match strides of the input, at least for dense non-overlapping tensors. In the example above, strides should be (1,3). 
numpy propagates input strides in this case

cc @mruberry @rgommers @VitalyFedyunin @jamesr66a @glaringlee

**Comment by glaringlee** [comment]
Will take a look at.
