### ISSUE TITLE
Issue in installing torch

### ISSUE THREAD

**Issue by hvaratharaj** [pytorch/pytorch#41310]
Im using python 3.7

Im trying to install torch and getting following error on my window 10 64 bit machine

(my-rdkit-env) C:\Users\vharikrishnan\Downloads\GENTRL-master\GENTRL-master>pip install torch
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
     |████████████████████████████████| 216 kB 3.3 MB/s
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\VHARIK~1\AppData\Local\Temp\pip-wheel-pfgoder0'
       cwd: C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\site-packages\setuptools\__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
ERROR: gentrl 0.1 requires scipy>=1.1.0, which is not installed.
ERROR: molsets 0.1.3 requires fcd-torch>=1.0.5, which is not installed.
ERROR: molsets 0.1.3 requires matplotlib>=3.0.0, which is not installed.
ERROR: molsets 0.1.3 requires scipy>=1.1.0, which is not installed.
ERROR: molsets 0.1.3 requires seaborn, which is not installed.
ERROR: molsets 0.1.3 requires tqdm>=4.26.0, which is not installed.
ERROR: gentrl 0.1 has requirement torch==1.0.1, but you'll have torch 0.1.2.post2 which is incompatible.
ERROR: molsets 0.1.3 has requirement torch>=1.0.1, but you'll have torch 0.1.2.post2 which is incompatible.
Installing collected packages: pyyaml, torch
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VHARIK~1\AppData\Local\Temp\pip-record-_l9r2mlw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\Include\torch'
         cwd: C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\VHARIK~1\AppData\Local\Temp\pip-install-cvlq2c7a\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\VHARIK~1\\AppData\\Local\\Temp\\pip-install-cvlq2c7a\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\VHARIK~1\AppData\Local\Temp\pip-record-_l9r2mlw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\vharikrishnan\Anaconda3\envs\my-rdkit-env\Include\torch' Check the logs for full command output.

**Comment by peterjc123** [comment]
The probable reasons for this kind of error are listed below.
1. You are using 32-bit Python `python -c "import sys; print(sys.maxsize)"` should return 9223372036854775807 in 64-bit Python.
2. You are using Python versions that we haven't added support yet, including 2.7, 3.9.

**Comment by hvaratharaj** [comment]
Im using 3.7 python and please find the attached 
![image](https://user-images.githubusercontent.com/41865766/87244406-f1112e80-c434-11ea-937a-52381be9ce29.png)

I did copy the command and executed from https://pytorch.org. still facing issue as torch module not found

**Comment by peterjc123** [comment]
> Im using 3.7 python and please find the attached
> ![image](https://user-images.githubusercontent.com/41865766/87244406-f1112e80-c434-11ea-937a-52381be9ce29.png)
> 
> I did copy the command and executed from https://pytorch.org. still facing issue as torch module not found

Then you probably have multiple python envs messed up. You can use `python -m pip` instead of `pip` to specify the one that points to the current env.

**Comment by hvaratharaj** [comment]
I tried in another machine which doesn’t have any other python versions and
still end up facing the same problem

**Comment by peterjc123** [comment]
> same

What do you mean by "same" here? Cannot install PyTorch? Or, PyTorch could not be found in Python after installation?

**Comment by hvaratharaj** [comment]
Yeah ‘torch‘ module not found

**Comment by peterjc123** [comment]
Please write down what you have done to install PyTorch step by step. Given the limited description here, I could not tell anything useful.

**Comment by hvaratharaj** [comment]
I tried to install torch using following command.

*pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f
https://download.pytorch.org/whl/torch_stable.html
<https://download.pytorch.org/whl/torch_stable.html>*



Its installed successfully but when I try to execute the program im getting
error as follows





Thanks & Regards

Raj



*From:* peterjc123 <notifications@github.com>
*Sent:* Sunday, July 12, 2020 3:27 PM
*To:* pytorch/pytorch <pytorch@noreply.github.com>
*Cc:* hvaratharaj <vharikrishnan@zuora.com>; Author <
author@noreply.github.com>
*Subject:* Re: [pytorch/pytorch] Issue in installing torch (#41310)



Please write down what you have done to install PyTorch step by step. Given
the limited description here, I could not tell anything useful.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pytorch/pytorch/issues/41310#issuecomment-657229210>,
or unsubscribe

**Comment by peterjc123** [comment]
@hvaratharaj What is the result of `where pip` and `where python`?

**Comment by peterjc123** [comment]
Does `python -m pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html` help?

**Comment by hvaratharaj** [comment]
This magic worked. Thank you so much for your help.

Thanks & Regards
Raj
