### ISSUE TITLE
Adding as_strided with onnx conversion

### ISSUE THREAD

**Issue by Nouman97** [pytorch/pytorch#41326]
Hello,

I was trying to convert my longformer question answering model to onnx, but apparently as_strided is not yet supported by onnx. Can you please add its support?

Thank you and best regards!

![image](https://user-images.githubusercontent.com/42269506/87273759-6d6a4700-c4f3-11ea-98a7-d0d9ba0222be.png)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by BowenBao** [comment]
hi @Nouman97 thanks for reporting, I have created a PR #41569
