### ISSUE TITLE
torchaudio bug

### ISSUE THREAD

**Issue by joinhe** [pytorch/pytorch#41331]
## 🐛 Bug

torchaudio.compliance.kaldi.fbank 

dither (float, optional) – Dithering constant (0.0 means no dither). If you turn this off, you should set the energy_floor option, e.g. to 1.0 or 0.1 (Default: 0.0)
 the Default: 0.0 is bad ,if you use Default: 0.0 (I think Default is not 0.0)

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by albanD** [comment]
Hi,

Can you open the issue in the torchaudio repo directly please: https://github.com/pytorch/audio

Also make sure to specify what is the issue you're seeing and if possible a small code sample that shows it.
