### ISSUE TITLE
CANNOT IMPORT TORCH SEGMENTAT FALT

### ISSUE THREAD

**Issue by rhymebumblebutt** [pytorch/pytorch#4133]
# I CANNOT IMPORT PYTORCH ANYMORE SINCE I TRIED LATER ON TODAY

# HERE IS WHAT HAPPENS

# IMPORT TORCH
# Segmentation fault (core dumped)

# YOU CAN NOT TRUST LIBS ANYMORE NOWADAYS

**Comment by rhymebumblebutt** [comment]
@eklitzke @apaszke @soumith @gchanan @zou3519 @colesbury @ezyang @zdevito @killeent @andreh7 @andresy @pietern @SsnL @ghostFaceKillah @moskomule @nitsky

### SOLVE IT IMMEDIATELY

## MY JOB DEPENDS ON IT

# PLEASE

**Comment by soumith** [comment]
I'm sorry for everone tagged. The person who wrote the issue has etiquette issues.
