### ISSUE TITLE
Circleci nightly job fail

### ISSUE THREAD

**Issue by guyang3532** [pytorch/pytorch#41336]
1. Several CI test jobs on nightly branch fail for these two days:

        https://app.circleci.com/pipelines/github/pytorch/pytorch/190074/workflows/bf36ca5c-50f4-45ae-ae0f-d1c5d38f7e52/jobs/6217176

CI test job' error log:

> + chmod +x /home/circleci/project/ci_test_script.sh
> + VOLUME_MOUNTS='-v /home/circleci/project/:/circleci_stuff -v /home/circleci/project/final_pkgs:/final_pkgs -v /home/circleci/project/pytorch:/pytorch -v /home/circleci/project/builder:/builder'
> + '[' -n 1 ']'
> ++ docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --runtime=nvidia -v /home/circleci/project/:/circleci_stuff -v /home/circleci/project/final_pkgs:/final_pkgs -v /home/circleci/project/pytorch:/pytorch -v /home/circleci/project/builder:/builder -t -d pytorch/conda-cuda
> docker: Error response from daemon: Unknown runtime specified nvidia.
> See 'docker run --help'.
> + export id=
> + id=
> + export 'COMMAND=((echo "source /circleci_stuff/env && /circleci_stuff/ci_test_script.sh") | docker exec -i "$id" bash) 2>&1'
> + COMMAND='((echo "source /circleci_stuff/env && /circleci_stuff/ci_test_script.sh") | docker exec -i "$id" bash) 2>&1'
> + echo '((echo' '"source' /circleci_stuff/env '&&' '/circleci_stuff/ci_test_script.sh")' '|' docker exec -i '"$id"' 'bash)' '2>&1'
> + unbuffer bash ./command.sh
> + ts
> Jul 13 08:30:17 Error: No such container: 
> 

2. This failure made the uploading jobs blocked and no packages is uploaded to [conda-nightly](https://anaconda.org/pytorch-nightly/pytorch) for two days. However the old packages on [conda-nightly](https://anaconda.org/pytorch-nightly/pytorch) are deleted maybe for saving storage. So installation of pytorch nightly by conda will fail because of the packages are unavailable.:
    
   conda install -y -c pytorch-nightly pytorch cudatoolkit=10.1

@seemethere @malfet @ezyang @peterjc123 

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by malfet** [comment]
@seemethere can you please have check if nighly docker images hash needs to be updated.

**Comment by ezyang** [comment]
#41144 removed nvidia runtime installs and I'm guessing it's the culprit

**Comment by ezyang** [comment]
the key error message is

```
++ docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --runtime=nvidia -v /home/circleci/project/:/circleci_stuff -v /home/circleci/project/final_pkgs:/final_pkgs -v /home/circleci/project/pytorch:/pytorch -v /home/circleci/project/builder:/builder -t -d pytorch/conda-cuda
docker: Error response from daemon: Unknown runtime specified nvidia.
```

@malfet

**Comment by seemethere** [comment]
This should be resolved as of https://github.com/pytorch/pytorch/commit/86d803a9da2b5d35481e11f42850a0aced22e28d

Will leave this open until we get a successful nightly run though.

**Comment by peterjc123** [comment]
I think problem 1 is resolved. But with the current mechanism, problem 2 may sometimes occur. @guyang3532 If you have some good advice for that, could you please open a new issue?
