### ISSUE TITLE
Do not remove future support of saving tensors and models with pickle (need for AutoML!)

### ISSUE THREAD

**Issue by renesax14** [pytorch/pytorch#41341]
## 🚀 Feature
I'd like to save tensors with pickle, dill etc for purposes of AutoML.

## Motivation

I saw this warning:

```
warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)
```

that came from pytorch.

I am generating models on the fly so I do not have a class for them as the recommended suggest (https://pytorch.org/docs/master/notes/serialization.html#recommend-saving-models).

If my pickled code won't work later, how am I suppose to save the model that is agnostic to model class code? (i.e. I do NOT have a way to do:

```
the_model = TheModelClass(*args, **kwargs)
```

)

Pickling is really a fantastic solution for my case since I just do:

```
child_model = db['child_model']
```

Can we keep the pickling code avaible for us please?

## Pitch

Be able to save tensors, models in a dictionary and be able to load them example code:

```
db = torch.load(path2file)
tensors1 = db["tensor1"]
mdl = db['mdl']
```
not as nice but this is at least something:
```
mdl.load_state_dict(db['params'])
mdl.eval()
```

Though anything that allows me to use pickle would be nice and I could save models separately...

Though as I said with automl maybe my models are generated on the fly.

## Alternatives

I'm still thinking about this since the problem is about being able to generate arbitrary models and save them without problem. Currently I am only able to do this with sequential models.

## Additional context

Models are generate on the fly so dill or pickle would be amazing.

forum link: https://discuss.pytorch.org/t/how-does-one-store-and-restore-models-for-automl/88270

**Comment by vincentqb** [comment]
cc @ezyang who may have more visibility about this

**Comment by ezyang** [comment]
cc @driazati by blame. Also cc @andyljones from #39003 this may not actually be deprecated now

**Comment by albanD** [comment]
This was not actually deprecated.
