### ISSUE TITLE
C++ build fails on some machines

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#41370]
I have a code that successfully compiles on some machines but not on the others. 

project structure:
foreach_cuda
--[libtorch]
--CMakeLists.txt
--main.cu
--[build] 

**How am i running it**
-> module list 
 1) cuda/10.2   2) cudnn/v7.6.5.32-cuda.10.2

-> cd build 
-> cmake -DCMAKE_PREFIX_PATH=/private/home/iuriiz/fun/cuda-tutorial/libtorch ..
-> cmake --build . --config Release
FAIL

Build error: 
_make[2]: *** No rule to make target '/usr/local/cuda/lib64/libnvToolsExt.so', needed by 'foreach_cuda'.  Stop.
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/foreach_cuda.dir/all' failed
make[1]: *** [CMakeFiles/foreach_cuda.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2_

**Setup**
Machine: internal devfair
CUDA version: 10.2
Libtorch: https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.5.1.zip

**Code**
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(foreach_cuda)

find_package(Torch REQUIRED)
find_package(CUDA REQUIRED)

cuda_add_executable(foreach_cuda main.cu)

target_link_libraries(foreach_cuda "${TORCH_LIBRARIES}")
set_property(TARGET foreach_cuda PROPERTY CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
```

main.cu

```
#include <iostream>
#include <math.h>
#include <torch/torch.h>
#include <torch/cuda.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <ATen/ATen.h>
#include <ATen/AccumulateType.h>
#include <ATen/cuda/CUDAContext.h>
#include <ATen/cuda/Exceptions.h>
#include <chrono>


int main(void)
{
  std::cout << "CUDA available: " << torch::cuda::is_available() << std::endl;
  
  return 0;
}
```

cc @malfet @yf225 @glaringlee

**Comment by glaringlee** [comment]
@izdeby 
Can you check the follwoing and let me know?
1. Does /usr/local/cuda/lib64/libnvToolsExt.so exist?
2. What is your LD_LIBRARY_PATH? is /usr/local/cuda/lib64 in it?
3. What is your CUDA_ROOT? Is /usr/local/cuda/lib64 in it?

**Comment by izdeby** [comment]
@glaringlee,
1) No
2) LD_LIBRARY_PATH=/public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/**lib64**:/public/apps/cuda/10.2/**lib64**::/public/slurm/20.02.1/lib:/public/slurm/20.02.1/lib
LD_LIBRARY_PATH_modshare=:1:/public/apps/cuda/10.2/**lib64**:1:/public/slurm/20.02.1/lib:1:/public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/**lib64**:1

3) CUDA_ROOT - no value

**Comment by glaringlee** [comment]
@malfet 
Is this because pytorch find cuda files using a fixed path (which is /usr/local/cuda/lib64)?
It seems the cuda is installed in another path on the machine above (devfair). Any advise here? Edit CUDA_ROOT?

**Comment by malfet** [comment]
@glaringlee yes, cmake’s FindCUDA script searches for CUDA in /usr/local/cuda unless CUDA_ROOT is defined

**Comment by glaringlee** [comment]
@izdeby 
Can you setup your CUDA_ROOT? 
Add these paths in: /public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/lib64:/public/apps/cuda/10.2/lib64

**Comment by izdeby** [comment]
@glaringlee, i've updated CUDA_ROOT 
-> env | grep CUDA_ROOT
<- CUDA_ROOT=/public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/lib64:/public/apps/cuda/10.2/lib64

Then rebuilt everything from scratch but it still fails.
Error: 
_make[2]: *** No rule to make target '/usr/local/cuda/lib64/libnvToolsExt.so', needed by 'foreach_cuda'.  Stop.
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/foreach_cuda.dir/all' failed
make[1]: *** [CMakeFiles/foreach_cuda.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2_

**Comment by glaringlee** [comment]
@malfet 
Did I missed anything here? The CUDA_ROOT is updated, but the cuda path is still /usr/local/cuda/lib64. Any advise?

**Comment by glaringlee** [comment]
@izdeby 
In the meantime, a temp fix is:
In the file /path/to/libtorch/share/cmake/Caffe2/Caffe2Targets.cmake
Replace the references to /usr/local/cuda/... with your CUDA path.
Let me know if it works.

**Comment by izdeby** [comment]
@glaringlee 
I made the changes but they didnt work.
there are 2 issues that i've noticed: 
1) the only place in Caffe2Targets.cmake that was mentioning `/usr/local/cuda/` was this line: 
`INTERFACE_LINK_LIBRARIES "torch::cudart;c10_cuda;/usr/local/cuda/lib64/libnvToolsExt.so;/usr/local/cuda/lib64/libcudart.so;torch_cpu_library;caffe2::cufft;caffe2::curand;caffe2::cublas;caffe2::cudnn"`

i've updated it to be 
`INTERFACE_LINK_LIBRARIES "torch::cudart;c10_cuda;public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/lib64/libnvToolsExt.so;public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/lib64/libcudart.so;torch_cpu_library;caffe2::cufft;caffe2::curand;caffe2::cublas;caffe2::cudnn"`

The problem is that in /public/apps/cudnn/v7.6.5.32-cuda.10.2/cuda/lib64 there is no libnvToolsExt.so and libcudart.so
There are these files: libcudnn.so  libcudnn.so.7  libcudnn.so.7.6.5  libcudnn_static.a 

2) even with updated Caffe2Targets.cmake, the error mentions a different path: 
_-- Build files have been written to: /private/home/iuriiz/study/foreach_cuda/build
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libnvToolsExt.so', needed by 'foreach_cuda'.  Stop.
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/foreach_cuda.dir/all' failed
make[1]: *** [CMakeFiles/foreach_cuda.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2_

**Comment by glaringlee** [comment]
@izdeby 
Oh, I see, I've thought you have those .so, but not in /usr/local/cuda.
If you don't have them， probably your cuda installation has problem, can you search your local drive broadly, if still can not find those .so, try re-install cuda env.

**Comment by izdeby** [comment]
@glaringlee 
Ok, that looks like my setup issue so im closing the issue for now. 
Thank you for your help!
