### ISSUE TITLE
It seems the documentation of torch.norm is a little wrong.

### ISSUE THREAD

**Issue by WANGZhaowei-Wesley** [pytorch/pytorch#41388]
## 📚 Documentation
For the parameter 'dim', the documentation says 'If the value is None, matrix norm will be calculated when the input tensor only has two dimensions, vector norm will be calculated when the input tensor only has one dimension. If the input tensor has more than two dimensions, the vector norm will be applied to last dimension.'

My code is:
A = torch.randn(4, 3, 3)
B = torch.norm(A)
print(B)
The result is:
tensor(5.7707)

It seems that torch.norm computes the sum of the square of every number in the tensor A and returns the square root of the sum. However, the documentation says ' the vector norm will be applied to the last dimension'. I think what the function does contradicts the documentation. By the way, I prefer what the function does, because computing the Frobenius norm of a three or more dimensional tensor is useful. So, I think to change the documentation is a good idea, instead of to fix the implementation of torch.norm.

cc @jlin27 @mruberry @vincentqb @vishwakftw @jianyuh @nikitaved @pearu

**Comment by ezyang** [comment]
cc @kurtamohler

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/40924 may be of interest

**Comment by kurtamohler** [comment]
Yes, #40924 is related. The plan for that PR is to add a new `norm` function to `torch.linalg`, once that module exists, and deprecate the current `torch.norm` and `torch.functional.norm` interfaces. In that case, it makes sense to update the current documentation, so I'll make that change.
