### ISSUE TITLE
Generate overloads in VariableType for non-s methods

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4138]
Right now, overloads in VariableType are only ever generated for `s_foo` functions, which are functions which assume that their arguments are already expanded as necessary. This is fine for derivatives, but it's more convenient for ONNX tracing (and some cases for the optimizer, perhaps) for us to get the non-expanded API calls. Now that we have #4127, it's actually not too difficult to make the broadcasting operators get generated: just generate dispatch code for `foo` as well!

It might be necessary to make these virtual. We don't mind.

**Comment by eellison** [comment]
Is this still an issue? Seems like it is no longer relevant.
