### ISSUE TITLE
Searchsorted differentiable?

### ISSUE THREAD

**Issue by krihabu** [pytorch/pytorch#41389]
If the searchsorted function from version 1.7.0 is used with `values` being a tensor with `requires_grad=True` following error occures:

```
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1594019302472/work/torch/csrc/autograd/functions/utils.h":59, please report a bug to PyTorch. 
```

## Code example
```
import torch

a = torch.tensor([1,2,3])
val = torch.tensor(2.5, requires_grad=True)

ind = torch.searchsorted(a, val)
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- OS: Linux Mint 19
- PyTorch version: 1.7.0.dev20200706
- Python version: 3.8.1
- CUDA/cuDNN version: 10.2.89

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by vincentqb** [comment]
I can reproduce.

**Comment by albanD** [comment]
It outputs a LongTensor so it cannot be differentiable.
But we should mark it properly as such to avoid this crash.

A workaround for now is just to detach the input that requires gradient before passing it to searchsorted to avoid the crash.

**Comment by topiaruss** [comment]
I'm getting a similar issue, but related to torch.unique. Here's the traceback

    2020-07-15 20:55:53,769: detect
    Traceback (most recent call last):
      File "detect.py", line 20, in wrapped_detect
        detect(pipeline, event, save_img)
      File "detect.py", line 108, in detect
        for c in det[:, -1].unique():    # for all detected classes
      File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 386, in unique
        return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
      File "/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py", line 247, in fn
        return if_false(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py", line 247, in fn
        return if_false(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 695, in _return_output
        output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
      File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 612, in _unique_impl
        return_counts=return_counts,
    RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/media/nvidia/WD_NVME/PyTorch/JetPack_4.4/GA/pytorch-v1.6.0-rc2/torch/csrc/autograd/functions/utils.h":59, please report a bug to PyTorch.

Versions:
torch==1.6.0
installed via pip
Python 3.6.9

This is occurring in a dockerized app built on the following base image:

    docker pull nvcr.io/nvidia/l4t-ml:r32.4.3-py3

**Comment by albanD** [comment]
I guess this is in the case where you give a floating point input that requires grad?

**Comment by topiaruss** [comment]
@albanD Probably. Can you suggest a diagnostic print I could put in there, to confirm what you need to know, bearing in mind this is not my code. Is there something like 'det[:, -1].shape()' that can provide useful info?

**Comment by albanD** [comment]
`det[:, -1].type()` and `det[:, -1].requires_grad` would give us all the info here. Thanks!

**Comment by topiaruss** [comment]
@albanD Thanks!

                print(f'type: {det[:, -1].type()}')
                print(f'requires_grad: {det[:, -1].requires_grad}')

                for c in det[:, -1].unique():    # for all detected classes
                    ...

yields

        type: torch.cuda.FloatTensor
        requires_grad: True

**Comment by topiaruss** [comment]
And of course for anyone led here by google, while looking for a quick solution.
I applied @albanD's suggestion of detaching the input to unique. So the line:

    for c in det[:, -1].unique():

became

    for c in det[:, -1].detach().unique():

And all is fine...

**Comment by jifengtuo** [comment]
hello,I also have the same error,can you tell me how to correct the error in specific file?thank you

**Comment by jifengtuo** [comment]
thanks, I have solved the problem with your advices

**Comment by saksim** [comment]
> And of course for anyone led here by google, while looking for a quick solution.
> I applied @albanD's suggestion of detaching the input to unique. So the line:
> 
> ```
> for c in det[:, -1].unique():
> ```
> 
> became
> 
> ```
> for c in det[:, -1].detach().unique():
> ```
> 
> And all is fine...

Thanks for @topiaruss's help. This actually works and solves this issue.
