### ISSUE TITLE
Running tests with --pytest fails with unrecognized arguments: --subprocess

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41393]
## 🐛 Bug

When running run_tests.py with --pytest the test test_cuda_primary_ctx.py fails with "unrecognized arguments: --subprocess"

## To Reproduce

- `python -m pytest test_cuda_primary_ctx.py --subprocess` to easily reproduce
- `python run_tests.py --pytest` for "regular" use which causes the above call

The reason is that unittest (likely) ignores all unknown parameters while pytest does not. There are 2 solutions:
- Make `run_tests.py` be aware of it and don't use pytest for such tests
- Make the test aware of pytest and/or always use pytest so the options can be added to the pytest parser

## Environment

- PyTorch 1.6.0-rc2

cc @mruberry @VitalyFedyunin

**Comment by vincentqb** [comment]
@mruberry -- do we officially support running tests using both unittest and pytest?

**Comment by mruberry** [comment]
> @mruberry -- do we officially support running tests using both unittest and pytest?

Officially just unittest, but we keep most test cases working with pytest. It'd be nice to fix this since there are people who really like pytest.

**Comment by Flamefire** [comment]
I've implemented the 2nd suggestion in #41397 which falls back to unittest when custom arguments are present. This is the first solution proposed above.

**Comment by mruberry** [comment]
> I've implemented the 2nd suggestion in #41397 which falls back to unittest when custom arguments are present. This is the first solution proposed above.

Seems like that's perceived as overly invasive and possibly confusing. Is this scenario really worth fixing?

**Comment by Flamefire** [comment]
Just as a remainder: The scenario is `python run_tests.py --pytest` which isn't to special and it failing is confusing at least.

I don't understand why this is confusing or invasive as it only removes pytest and only when extra args are passed (which are known to fail with pytest according to this issue). If there is anything to improve please share it in the PR. Thank you!
