### ISSUE TITLE
Is it planning to support nn.Embeddings quantization?

### ISSUE THREAD

**Issue by skurzhanskyi** [pytorch/pytorch#41396]
First of all, I would like to thank you for the awesome `torch.quantization`. But at the moment, the quantization of embeddings is not supported, although it's one of the biggest (in terms of size) parts of the models in NLP. 
I tried to use `nn.Embeddings` as `nn.Linear` because they have a very similar nature, but get the following error:
```
RuntimeError: Could not run 'aten::index_select' with arguments from the 'QuantizedCPUTensorId' backend. 'aten::index_select' is only available for these backends: [CPUTensorId, CUDATensorId, SparseCPUTensorId, SparseCUDATensorId, VariableTensorId].
```
So I'm interested whether it's planned to support `nn.Embeddings` quantization?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by vkuzo** [comment]
Hi @skurzhanskyi , quantization of `nn.Embedding` and `nn.EmbeddingBag` is in the works.  We don't have a specific timeline we can share, but it should be ~months (not weeks or years).

**Comment by erip** [comment]
@vkuzo is there a relevant PR or branch to track this?

**Comment by supriyar** [comment]
We currently do support quantization of `nn.Embedding` and `nn.EmbeddingBag`. Please try with pytorch nightly to get the relevant changes. 
Embedding quantization is supported using the eager mode static api (i.e `prepare` and `convert`). The qconfig for the embedding layers need to be set to `float_qparams_weight_only_qconfig`.

An example of how to enable quantization on embedding layers can be found here https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize.py#L521

**Comment by vkuzo** [comment]
for triage

**Comment by tejasdubhir** [comment]
> We currently do support quantization of `nn.Embedding` and `nn.EmbeddingBag`. Please try with pytorch nightly to get the relevant changes.
> Embedding quantization is supported using the eager mode static api (i.e `prepare` and `convert`). The qconfig for the embedding layers need to be set to `float_qparams_weight_only_qconfig`.
> 
> An example of how to enable quantization on embedding layers can be found here https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize.py#L521

Can you please recheck the link? It appears to be invalid.

**Comment by pfeatherstone** [comment]
Yes, could you refresh the link please

**Comment by tejasdubhir** [comment]
> Yes, could you refresh the link please

It still shows "Page not found"...

**Comment by evrrn** [comment]
Seems like for now the recipe from the https://github.com/pytorch/pytorch/issues/41396#issuecomment-764230203 is [here](https://github.com/pytorch/pytorch/issues/65185#issue-998785028)
