### ISSUE TITLE
test_torch.py fails with nan results

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41401]
## 🐛 Bug

2 test out of test_torch.py fail with results containing NaN:
- TestTorchDeviceTypeCUDA.test_det_logdet_slogdet_batched_cuda_float64
- TestTorchDeviceTypeCUDA.test_lu_cuda

## To Reproduce

1. pytest test_torch.py -k 'not float16' (due to #41340)

            run_test(matsize, batchdims, mat_chars=['sym_pd'])
>           run_test(matsize, batchdims, mat_chars=['sing'])

```
test_torch.py:7664: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_torch.py:7660: in run_test
    self.assertEqual(actual_value, expected_value)
/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1085: in assertEqual
    self.assertTrue(result, msg=msg)
E   AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 3 element(s) (out of 3) whose difference(s) exceeded the margin of error (including 3 nan comparisons). The greatest difference was nan (nan vs. 0.0), which occurred at index 0.

...

>       run_test(device, True)

test_torch.py:15087: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_torch.py:15081: in run_test
    run_subtest(ms, batch, device, pivot, singular=True, a=a)
test_torch.py:15057: in run_subtest
    self.assertEqual(P.matmul(L.matmul(U)), a)
/lustre/ssd/ws/s3248973-EasyBuild/easybuild-haswell/software/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:1085: in assertEqual
    self.assertTrue(result, msg=msg)
E   AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1e-07 and atol=1e-07, found 18 element(s) (out of 18) whose difference(s) exceeded the margin of error (including 18 nan comparisons). The greatest difference was nan (nan vs. 1.0), which occurred at index (0, 0, 0).

```

## Environment

Collecting environment information...
PyTorch version: 1.6.0-rc2
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
GCC version: (GCC) 8.3.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 450.36.06
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0
[conda] Could not collect

cc @ngimel @mruberry @VitalyFedyunin

**Comment by ezyang** [comment]
That's pretty mysterious, esp since it doesn't repro in our ci. Does it repro in nightlies?

**Comment by ngimel** [comment]
@ezyang it's likely related to k80s, #41340 also repros only on K80s.

**Comment by Flamefire** [comment]
Another datapoint: I've seen failures related to CUDA 11 as described here: https://github.com/pytorch/pytorch/pull/40452#discussion_r446451164

This failure did happen on the same node too and went away after I applied the patch from #40452. The output of `nvcc --version` is `Cuda compilation tools, release 10.1, V10.1.243` but `nvidia-smi` shows: ` NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0`. So it is likely that the failure from above is not related to the cuda compiler version but to the cuda driver version. This makes it even more important to include that patch in the upcoming release.

So it might be worth checking if this issue to repros on the updated driver.

**Comment by zasdfgbnm** [comment]
@Flamefire Could it be you installed both CUDA 11 and CUDA 10.1, and your shell picked up CUDA10.1 but PyTorch is built with  11? What is your `print(torch.version.cuda)`?

**Comment by Flamefire** [comment]
Yes and no. There are 2 parts of CUDA: The driver and the runtime libraries including the compiler. Usually (at least for quite a while) those 2 don't need to be the same version but can interop within a "window" (e.g. you'd expect a CUDA 10.2 driver to handle programs build with CUDA 10.1). See https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility

So we have CUDA 11 drivers installed (which includes nvidia-smi hence the reported version there) but I'm compiling with CUDA 10.1 (as reported by `torch.version.cuda`, see also `CUDA used to build PyTorch: 10.1`). This is done to support newer GPUs by using a recent driver. But the compiler cannot be upgraded as easily as there are certain requirements on e.g. the base GCC version and interop with existing binaries.

**Comment by Lezcano** [comment]
These tests don't exist anymore. Since these functions have gone through fairly big rewrite and current tests do pass, I'm closing this.
