### ISSUE TITLE
test_torch.py fails if not build with MKL

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#41402]
## 🐛 Bug

Due to not using conda on our cluster we build PyTorch without MKL.
When running the tests `TestTorchDeviceTypeCUDA.test_istft_of_sine_cuda_float64` fails with `RuntimeError: fft: ATen not compiled with MKL support`

## To Reproduce

1. pytest test_torch.py -k 'not float16' (due to #41340)

Last line before failure:
```
        return _VF.istft(
>           input, n_fft, hop_length, win_length, window, center, normalized, onesided, length)
E       RuntimeError: fft: ATen not compiled with MKL support

```

## Environment

Collecting environment information...
PyTorch version: 1.6.0-rc2
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
GCC version: (GCC) 8.3.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 450.36.06
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0
[conda] Could not collect

cc @mruberry @VitalyFedyunin

**Comment by ezyang** [comment]
Thanks. We should just skip the test when mkl is not available. Should be an easy fix.
