### ISSUE TITLE
Memory corruption and crash in quantized convolution with small inputs

### ISSUE THREAD

**Issue by dbalchev** [pytorch/pytorch#41406]
## 🐛 Bug
When I run `torch.nn.quantized.Conv2d` on inputs with small widths there's a memory corruption, an error message from `malloc` and the process is terminated.

## To Reproduce

1. Run the following script
    
    ```python
    import torch

    print(torch.__version__)

    x = torch.rand([1, 72, 7, 1]) * 255
    q = torch.quantize_per_tensor(x, 1, 0, dtype=torch.quint8)
    l = torch.nn.quantized.Conv2d(72, 72, kernel_size=(5, 5), stride=(2, 2),padding=(2, 2), groups=72)
    for _ in range(20):
        l(q)
    print("Didn't crash")
    ```

1. Example output:
    ```
    1.5.1+cpu
    [1]    22724 segmentation fault (core dumped) 
    ```

## Expected behavior
No memory corruption

## Environment

```
PyTorch version: 1.5.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1+cpu
[conda] numpy                     1.19.0                    <pip>
[conda] torch                     1.5.1+cpu                 <pip>
```

### Notes:
- This doesn't happen with `kernel_size=(3, 3)`, with shape `1, 72, 7, 3` or without passing `groups`
- When I run the script multiple times I get various `malloc` errors

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by dskhudia** [comment]
@dbalchev Thanks a lot for reporting the issue. https://github.com/pytorch/FBGEMM/pull/395 fixes this.

**Comment by dbalchev** [comment]
Thanks for fixing it so fast

**Comment by dskhudia** [comment]
https://github.com/pytorch/pytorch/pull/41814 is the merge PR in PyTorch.
