### ISSUE TITLE
Build Android error, Task :pytorch_android:bundleReleaseAar FAILED

### ISSUE THREAD

**Issue by hehedaozuiteng** [pytorch/pytorch#41407]
hi all，

I am trying to build pytorch android from source by following this website: https://pytorch.org/mobile/android/#building-pytorch-android-from-source

I runned it on mac with zsh.

gradle: v5.6.4

jdk8  : v1.8.0_251

ndk: 21.3.6528147

sdk:  30.0.3

> git clone --recursive https://github.com/pytorch/pytorch
> cd pytorch
> git submodule sync
> git submodule update --init --recursive
> 
> cd pytorch
> sh ./scripts/build_pytorch_android.sh

at the end I recived the error:

> Task :pytorch_android:bundleReleaseAar FAILED
> 
> FAILURE: Build failed with an exception.
> 
> Where:
> Build file ‘/Users/huanghenglin/pytorch/android/pytorch_android/build.gradle’ line: 115
> 
> What went wrong:
> Execution failed for task ‘:pytorch_android:bundleReleaseAar’.
> 
> Could not find method execute() for arguments [] on task ‘:pytorch_android:addHeadersTobundleReleaseAar’ of type org.gradle.api.DefaultTask.

It seems like stuck on the release the aar file. what should I do to finish the compilar?

**Comment by msinkec** [comment]
Downgrading gradle to version 4 fixed it for me.

**Comment by hehedaozuiteng** [comment]
> Downgrading gradle to version 4 fixed it for me.

which vision of your gradle, I tried 4.10.3 and met another error.

**Comment by hehedaozuiteng** [comment]
> Downgrading gradle to version 4 fixed it for me.


which vision of your gradle, I tried 4.10.3 and met another error.

`* What went wrong:
Could not determine the dependencies of task ':pytorch_android_torchvision:externalNativeBuildRelease'.

Could not resolve all task dependencies for configuration ':pytorch_android_torchvision:releaseRuntimeClasspath'.
Could not resolve project :pytorch_android.
Required by:
project :pytorch_android_torchvision
> Unable to find a matching configuration of project :pytorch_android:
- None of the consumable configurations have attributes.`

**Comment by hehedaozuiteng** [comment]
I used the 4.10.2 grald solve the problem.
