### ISSUE TITLE
PyTorch memory footprint much larger than TF/ONNX 

### ISSUE THREAD

**Issue by CoderHam** [pytorch/pytorch#41427]
## 🐛 Bug

Significantly larger memory footprint of PyTorch for vanilla Resnet50 (possibly other models too). Unlike Tensorflow and ONNX, it consumes significantly extra memory and is unable to run even 1 instance with batch size of 128 on a GPU with 12GB memory (Titan V)

## To Reproduce

1. Grab Resnet50 model from TorchVision models. 
2. Prepare torchscript model using tracing. 
3. Run torchscript model with random input data with batch size 128 using the LibTorch C++ API

## Expected behavior

Even with a GPU that has 12GB it will report and out of memory error. It is likely that PyTorch can optimize their memory management further to be comparable with these other frameworks that use close to 9GB.

## Environment

Pytorch 1.5.1
CUDA 10.2 
Ubuntu 18.04 container
Python 3.6
GPU: TITAN V

cc @ezyang @gchanan @zou3519 @ngimel @albanD @mruberry

**Comment by xsacha** [comment]
What happens if you don't use torchscript?
Also, what happens if you del(model) for the resnet50 model you grabbed prior to loading the torchscript model.
Also, are you using with torch.no_grad()?

**Comment by ezyang** [comment]
I'm marking this as high priority because, if true as stated, this is a serious issue, however, we need a more clear repro; @xsacha's data point suggests there is something wrong with the test case

**Comment by rgommers** [comment]
@CoderHam can you please provide the code you used? That would be really helpful to figure out if there's an issue and how to address it.

**Comment by mruberry** [comment]
Closing due to age and lack of response. @CoderHam, if you're still experiencing this issue, would you reopen and update this?
