### ISSUE TITLE
ONNX fails to export Fold / col2im

### ISSUE THREAD

**Issue by panchgonzalez** [pytorch/pytorch#41423]
## 🐛 Bug

`torch.onnx.export` fails when `nn.Fold` module is present. 

## To Reproduce

```python
import torch
import torch.nn as nn
import numpy as np

class Demo(nn.Module):
    def __init__(self):
        super().__init__()
        self.fold = nn.Fold(output_size=(4,5), kernel_size=(2,2))
        
    def forward(self, x):
        folded = self.fold(x)
        return folded
    
input_tensor = torch.randn((1, 3*2*2, 12))
demo = Demo()
out = demo(input_tensor)

torch.onnx.export(
    demo,
    input_tensor,
    "debug.onnx",
    verbose=True,
    input_names=["data"],
    opset_version=12,
    dynamic_axes={"data": {0: "batch"}}
)
```

This returns
```
RuntimeError: Exporting the operator col2im to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

## Environment

[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py) output
```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.1.0            py36h23d657b_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.18.5           py36ha1c710e_0  
[conda] numpy-base                1.18.5           py36hde5b4d6_0  
[conda] pytorch                   1.5.1           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.1                py36_cu102    pytorch

```

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by mpariente** [comment]
Is this fixed? 
Or on the roadmap for 1.9?

**Comment by whcjb** [comment]
is there a walk around for Fold, as known as col2im ?

**Comment by BowenBao** [comment]
@hwangdeyu please take a look.

**Comment by hwangdeyu** [comment]
> @hwangdeyu Deyu Huang FTE please take a look.

Sure, thanks for the reminder.

**Comment by hwangdeyu** [comment]
hi @panchgonzalez, I'm working on fixing the issue. Could you tell me which model would cause this issue?

**Comment by GuardSkill** [comment]
> hi @panchgonzalez, I'm working on fixing the issue. Could you tell me which model would cause this issue?
hello, when can we export nn.Fold() ?

**Comment by mychina75** [comment]
any updates about this issue? thank you...

**Comment by dreaquil** [comment]
Has anyone picked this up? I would like to perhaps try it if not.

**Comment by Xiangyi1996** [comment]
I encountered the same issue. Anyone knows how to solve that issue? Thanks.

**Comment by Phoeby2618** [comment]
RuntimeError: Exporting the operator col2im to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

May I ask when you can solve ？

**Comment by Phoeby2618** [comment]
RuntimeError: Exporting the operator col2im to ONNX opset version 11 is not supported

Hi，is there a solution to this issue？

**Comment by thiagocrepaldi** [comment]
https://github.com/onnx/onnx/pull/3948/ is an initial draft and might be merged in the coming months

**Comment by xiaobei2** [comment]
I found functions col2im in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml
but it not found it in torch/_C/_VariableFunctions.pyi. Why?
Many functions can both found in native_functions.yaml and _VariableFunctions.pyi.
What is the magic from  native_functions.yaml => _VariableFunctions.pyi

I want to find the function define in _VariableFunctions.pyi, so i can make a op col2im to use. But how to do? anyone know?

**Comment by xiaobei2** [comment]
I have very little knowledge about ops. So I confused the relationship about them.
I just want to convert a model into onnx, but it with errors. 
RuntimeError: Exporting the operator col2im to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

So i want to add the col2im ops.
someone shows 
1. Search define from torch/_C/_VariableFunctions.pyi or torch/nn/functional.pyi like this for example,
def asinh(input: Tensor, *, out: Optional[Tensor]=None) -> Tensor: ...
2. Add symbolic 
```
from torch.onnx.symbolic_registry import register_op

def asinh_symbolic(g, input, *, out=None):
    return g.op("Asinh", input)

register_op('asinh', asinh_symbolic, '', 9)
```

But i can't find  col2im from torch/_C/_VariableFunctions.pyi or torch/nn/functional.pyi

**Comment by xiaobei2** [comment]
I am ramming around like a hungry deer, thanks for any tips.

**Comment by lminer** [comment]
@thiagocrepaldi any update on when this will be added. Looks like the PR was merged in onnx

**Comment by thiagocrepaldi** [comment]
https://github.com/pytorch/pytorch/pull/84594 will add support to col2im into pytorch exporter, but it is currently blocked by https://github.com/pytorch/pytorch/pull/83201

**Comment by thiagocrepaldi** [comment]
https://github.com/pytorch/pytorch/pull/84594 should solve this
