### ISSUE TITLE
[JIT] Support Dict comprehension

### ISSUE THREAD

**Issue by chenbohua3** [pytorch/pytorch#41448]
Currently, dict comprehension is not supported by JIT but it is widely used in python codes. Is there any plans to support it?

```
class MyModule(nn.Module):
    def forward(self):
        x = {i: i for i in range(2)}
        return x

model = MyModule()
model_s = torch.jit.script(model)
```
we will get:
```
torch.jit.frontend.UnsupportedNodeError: DictComp aren't supported:
  File "main_test.py", line 6
    def forward(self):
        x = {i: i for i in range(2)}
            ~ <--- HERE
        return x
```
we may use a `for-loop` to gradually add elements to the dict as a workaround, but it's a pretty bad user experience.

cc @suo @gmagogsfm

**Comment by ppwwyyxx** [comment]
instead of writing a forloop manually, one interesting workaround is to use list comprehension: `x = dict([(i,i) for i in range(2)])`
