### ISSUE TITLE
[jit] support boolean in dictionary

### ISSUE THREAD

**Issue by chenbohua3** [pytorch/pytorch#41449]
Currently jit does not support the case where boolean value is used as dict key:
```
class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.x = {True: 1}

model = MyModule()
model_s = torch.jit.script(model)
```
we will get:
```
RuntimeError: Cannot create dict for key type 'bool', only int, float, Tensor and string keys are supported
```
we must convert **boolean** to **int** as a workaround, but it will lose the semantic meanings of the key value and make the codes comfusing which may lead to a bad user experience.

cc @suo @gmagogsfm

**Comment by wconstab** [comment]
one fix could be to add support for new key operators, another could be to support arbitrary hashable keys, but unclear if that's worth the effort if that's significantly harder.
