### ISSUE TITLE
Error when converting custom layer with output of tuple to onnx format in pytorch 1.5.1

### ISSUE THREAD

**Issue by kuramawzw3** [pytorch/pytorch#41440]
## To Reproduce

```
import torch
class CustomFunction(torch.autograd.Function):
    @staticmethod
    def symbolic(g, input):
        return g.op('Custom', input, outputs=2)
    @staticmethod
    def forward(ctx, input):
        return input, input
class Custom(torch.nn.Module):
    def forward(self, input):
        return CustomFunction.apply(input)
print ('torch.__version__', torch.__version__)
model = Custom()
batch = torch.FloatTensor(1, 3)
torch.onnx.export(model, batch, "test.onnx", verbose=True)
```
## Expected behavior

(pytorch_1.5.1) wangzhiwei.yt@10.129.116.130:byte_pytorch_tools$ python test_tuple.py 
torch.__version__ 1.5.1
Traceback (most recent call last):
  File "test_tuple.py", line 21, in <module>
    torch.onnx.export(model, batch, "test.onnx", verbose=True)
  File "/data00/home/wangzhiwei.yt/anaconda3/envs/pytorch_1.5.1/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/data00/home/wangzhiwei.yt/anaconda3/envs/pytorch_1.5.1/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/data00/home/wangzhiwei.yt/anaconda3/envs/pytorch_1.5.1/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/data00/home/wangzhiwei.yt/anaconda3/envs/pytorch_1.5.1/lib/python3.7/site-packages/torch/onnx/utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/data00/home/wangzhiwei.yt/anaconda3/envs/pytorch_1.5.1/lib/python3.7/site-packages/torch/onnx/utils.py", line 123, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::PythonOp

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.17.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4
GPU 6: Tesla T4
GPU 7: Tesla T4

Nvidia driver version: 440.95.01
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.5           py37ha1c710e_0  
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.1                py37_cu102    pytorch
## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
This is a sup of https://github.com/pytorch/pytorch/issues/22134.

**Comment by kuramawzw3** [comment]
> This is a dup of #22134.

But still get erros on pytorch 1.5.1

**Comment by kuramawzw3** [comment]
close, move to https://github.com/pytorch/pytorch/issues/22134
