### ISSUE TITLE
received 0 items of ancdata when appending dic elements to a list

### ISSUE THREAD

**Issue by lucabergamini** [pytorch/pytorch#41465]
## 🐛 Bug

When the `__getitem__` returns a dict and an element is appended to a list I get 
`RuntimeError: received 0 items of ancdata` consistently on **linux only**

## To Reproduce
just run the script below on a linux machine

```python
import numpy as np
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    def __init__(self):
        pass
    def __len__(self):
        return 60000 * 64
    def __getitem__(self, idx):
        data_1 = np.zeros((50, 2))
        return {"d1": data_1}


if __name__ == "__main__":
    dl = DataLoader(MyDataset(), batch_size=64, num_workers=4, shuffle=False)
    dt_1 = []

    for data in dl:
        dt_1.append(data["d1"].numpy())
```

## Expected behavior

I'm not aware of any reason why this shouldn't go through (and indeed it does on OSx and Windows)

## Environment

PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 3GB
Nvidia driver version: 440.100
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[conda] Could not collect

pip freeze follows:
```shell
future==0.18.2
numpy==1.19.0
pkg-resources==0.0.0
torch==1.5.1
```
## Additional context
The error disappears by either:
- setting `num_workers` to 0
- adding an additional copy before appending (`dt_1.append(data["d1"].numpy())`)

Changing the strategy of multiprocessing leads to a `SegFault` hard crash

This has been observed on three different Linux machines with slightly different configurations.  

cc @ezyang @gchanan @zou3519 @SsnL @VitalyFedyunin

**Comment by ezyang** [comment]
this is a pretty small repro script, so i'm tentatively marking this high prio for investigation

**Comment by ezyang** [comment]
I ran this test case on a relatively recent develop build of master and couldn't reproduce. @lucabergamini could you try installing a nightly and see if you are affected?

**Comment by lucabergamini** [comment]
Sure @ezyang, any version in particular you want me to try?

**Comment by ezyang** [comment]
Most recent nightly is fine! you can just follow the instructions at https://pytorch.org/get-started/locally/

**Comment by lucabergamini** [comment]
I've tried the nightly on both macos and linux. No issue in macos, while I'm still getting the error in linux but with additional information:

```RuntimeError: received 0 items of ancdata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 845, in _try_get_data
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 845, in <listcomp>
    fs = [tempfile.NamedTemporaryFile() for i in range(fds_limit_margin)]
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 24] Too many open files: '/tmp/tmpmg46o_lk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    for data in dl:
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 400, in __next__
    data = self._next_data()
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1016, in _next_data
    idx, data = self._get_data()
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 983, in _get_data
    success, data = self._try_get_data()
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 849, in _try_get_data
    "Too many open files. Communication with the"
RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using ulimit -n in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code```

```
Again, adding a `copy()` (`dt_1.append(data["d1"].numpy())`) solves the issue on linux

**Comment by ezyang** [comment]
Try increasing your fd limit with ulimit?

**Comment by lucabergamini** [comment]
That's not a solution though @ezyang, isn't it? It will maybe put off the error by some iterations, but I can't see why:
- this example can deplete all available fds;
- that happens only if you append data in the list;
- that doesn't happen if you add an additional copy on line -1;

My gut feeling is more about a fd leak honestly....

**Comment by ezyang** [comment]
Oh, your problem is this one: https://github.com/pytorch/pytorch/issues/13246

Reopen if you disagree.
