### ISSUE TITLE
einsum running 100x slower than expected when controlling for number of ops

### ISSUE THREAD

**Issue by samringer** [pytorch/pytorch#41467]
## 🐛 Bug

For two simple einsum cases, Case 2 is running ~30% slower than Case 1, despite needing to perform 101x fewer ops.

## To Reproduce

**Case 1**
```
a = torch.randn(10000, 100, 101).cuda()
b = torch.randn(10000, 101, 3).cuda()

%%time
for _ in range(10000):
    torch.einsum("bij, bjf->bif", a, b)
    torch.cuda.synchronize()
```
`CPU times: user 26.7 s, sys: 18.8 s, total: 45.5 s
Wall time: 45.5 s`

**Case 2**
```
c = torch.randn(10000, 100, 1).cuda()
d = torch.randn(10000, 100, 1, 3).cuda()

%%time
for _ in range(1000):
    torch.einsum("bic, bicf->bif", c, d)
    torch.cuda.synchronize()
```
`CPU times: user 37.7 s, sys: 23.7 s, total: 1min 1s
Wall time: 1min 1s`

## Expected behavior

I believe the number of ops needed for each case should be approximately:
**Case 1:** 10,000 x 100 x 101 x 3 ( x 2)
**Case 2:** 10,000 x 100 x 1 x 3 (x 2) 
(The factor of 2 is to account for the multiply-accumulate operation used in matrix multiplication)

Despite requiring 101x fewer ops and operating over smaller tensors than Case 1, in the example above Case 2 has a wall clock time 34% greater than Case 1.
Are there methods/kernels that can be used which are more optimised towards the later case?

## Environment

Performed using a fresh Google Colab instance.

PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.1+cu101
[conda] Could not collect

## Additional context
Using `opt_einsum==3.2.1` did not improve performance on Case 2.
```
from opt_einsum import contract
c = torch.randn(10000, 100, 1).cuda()
d = torch.randn(10000, 100, 1, 3).cuda()

%%time
for _ in range(10000):
    contract("bic, bicf->bif", c, d)
    torch.cuda.synchronize()
```
`CPU times: user 39 s, sys: 23.7 s, total: 1min 2s
Wall time: 1min 2s`

cc @ngimel @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @VitalyFedyunin

**Comment by ezyang** [comment]
You are probably falling off the happy path. cc @t-vi

**Comment by t-vi** [comment]
To quote the post on the [forums](https://discuss.pytorch.org/t/einsum-running-100x-slower-than-expected-when-controlling-for-number-of-ops/89339/2):

The problem is that einsum reduces to batch matmul and so copies your data around.
The real solution is to implement a more general contraction. I had a patch using TensorIterators instead a few years ago, but somehow I decided that it would not work on CPU and abandoned it instead of measuring it on GPU. And then it never was enough fun to dust it off.

One work-around would be to try the Keops third party library.
