### ISSUE TITLE
Adam implementation different from paper

### ISSUE THREAD

**Issue by ericpts** [pytorch/pytorch#41477]
In https://pytorch.org/docs/stable/_modules/torch/optim/adam.html#Adam, towards the end, we have

```
                    denom = (exp_avg_sq.sqrt() / math.sqrt(bias_correction2)).add_(group['eps'])
```

However, the [paper](https://arxiv.org/pdf/1412.6980.pdf) uses epsilon by adding it to `exp_avg_sq.sqrt()`; not to a whole fraction.
This is always the case, in both the Algorithm 1 formulation, as well as the one before Section 2.1.

What pytorch does is that it uses `epsilon * sqrt(1 - beta_2^t)` instead of just `epsilon`, for the paper's algoritm formulation.

cc @jlin27 @vincentqb

**Comment by ezyang** [comment]
This wasn't always the case, the divergence from the paper was introduced in fed5ca192c98619947cca2fb9491ac9624b787d2

cc @farhadrgh

**Comment by farhadrgh** [comment]
fed5ca1 actually fixed the divergence from [paper](https://arxiv.org/pdf/1711.05101.pdf). Algorithm 1 is highlighting the difference between SGD and SGDW. Line 12 of Algorithm 2 is the place we should look at. There `epsilon` is added to `sqrt(v_hat)` in which `v_hat` is the `exp_avg_sq` scaled by `bias_correction2`

**Comment by ericpts** [comment]
> [fed5ca1](https://github.com/pytorch/pytorch/commit/fed5ca192c98619947cca2fb9491ac9624b787d2) actually fixed the divergence from this more recent [paper](https://arxiv.org/pdf/1711.05101.pdf). And there Algorithm 1 is highlighting the difference between SGD and SGDW. But line 12 of Algorithm 2 is the place we should look at. There `epsilon` is added to `sqrt(v_hat)` in which `v_hat` is the `exp_avg_sq` scaled by `bias_correction2`

Then I think the current implementation conforms with the paper. 
The issue is that the [documentation](https://pytorch.org/docs/stable/optim.html#torch.optim.Adam) makes it seem like this implements the Adam proposed in the [original paper](https://arxiv.org/abs/1412.6980).

**Comment by ezyang** [comment]
OK, reclassifying this as a doc bug. Should be an easy fix, tag me as reviewer.
