### ISSUE TITLE
Update SobolEngine direction numbers

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#41489]
## 🚀 Feature

Update direction numbers of SobolEngine to the new recent ones by Joe and Kuo from https://web.maths.unsw.edu.au/~fkuo/sobol/. 

## Motivation

The current implementation uses old 1111-dim direction numbers that should not be used anymore.  The update for a cython implementation of SobolEngine is done in https://github.com/scipy/scipy/pull/10844. We can directly port this over, we just need to find a good way to load the direction numbers from a data file in a platform agnostic way (so as to not blow up the binary size too much). 

## Additional context

I am happy to take this on.

cc @pbelevich

**Comment by ezyang** [comment]
cc @malfet

**Comment by ezyang** [comment]
cc @vishwakftw

**Comment by ezyang** [comment]
This seems reasonable. For now keeping the numbers in the cpp file is probably the easiest.

**Comment by Balandat** [comment]
> For now keeping the numbers in the cpp file is probably the easiest.

Easiest yes, but note these will be much larger than the previous ones. RIght now there are ~15K elements in the literals, with the update we will have ~403K.

**Comment by Balandat** [comment]
In the scipy version I'm lazy-loading a `.npz` file. We could do something similar here with `torch.load` if the new constants blow up the binary size.

**Comment by malfet** [comment]
@Balandat I think it's totally fine to have it embedded in .so file and let OS take care of lazy loading the data section. 
As long as literals are kept in C-style arrays it is almost zero runtime overhead to load it.
Please include the python script in your PR that downloads/converts https://web.maths.unsw.edu.au/~fkuo/sobol/new-joe-kuo-6.21201 into https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SobolEngineOpsUtils.cpp

**Comment by tupui** [comment]
> Please include the python script in your PR that downloads/converts https://web.maths.unsw.edu.au/~fkuo/sobol/new-joe-kuo-6.21201 into https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SobolEngineOpsUtils.cpp

@Balandat Should we add this as well into our [Scipy PR](https://github.com/scipy/scipy/pull/10844)? For now I just added a comment based on what you said.

**Comment by Balandat** [comment]
Yes, we can should add that there as well. I'll try to clean this up soon.
