### ISSUE TITLE
Unflatten module for nn.Sequential

### ISSUE THREAD

**Issue by alvgaona** [pytorch/pytorch#41516]
## 🚀 Feature
This feature is an extension to the module `Flatten` which was introduced in this PR #22245. I'd like to have its counterpart, `Unflatten` to be used in `nn.Sequential`.

## Motivation
There are networks, such as the discriminator in a DCGAN, that may flatten a `Conv2d` layer to feed the output into a `Linear` one. With that, the generator might use that flattened output which has to be unflattened for it to be used in a `ConvTranspose2d` layer.
I know the unflattening can be done in the forward method using `view()` or `unflatten()` on a named tensor (not stable), but this would make the code more readable if we can embed that into the Sequential class.

## Pitch
So, to be consistent, I think it's good we add an `Unflatten` module to [flatten.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/flatten.py) the same way `Fold` has its counterpart `Unfold` in [fold.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/fold.py).

## Alternatives
The solution is pretty straight-forward. 
1. Add `class Unflatten(Module)` to `flatten.py`.
2. Add a `forward()` method using `view()` or `unflatten()` from `NamedTensor`. The latter is preferable since it's more semantic.
3. Add tests and documentation

## Additional context

I have implemented this using `unflatten()`, and it's working on my [fork](https://github.com/alvgaona/pytorch/commit/809e7e9111ddeadc747b2237802eee026f5046f4).

cc @albanD @mruberry

**Comment by ezyang** [comment]
This seems pretty reasonable, but I'll let triage review take a look at it for second opinion.

**Comment by albanD** [comment]
Thanks for the suggestion.
One question I would have is how does it know what the output shape should be?
Do you plan on passing the new size in the constructor? But then how do you handle batch size?

**Comment by alvgaona** [comment]
Hi,@albanD

In the constructor you would pass `(channels, height, width)` like [this](https://github.com/alvgaona/pytorch/commit/809e7e9111ddeadc747b2237802eee026f5046f4#diff-c4030952458570f4a02241f1b82585c5R66). 

Then you should just need to do something like [this](https://github.com/alvgaona/pytorch/commit/809e7e9111ddeadc747b2237802eee026f5046f4#diff-c4030952458570f4a02241f1b82585c5R74) and `Unflatten` wouldn't need to know about the batch size at all. It's handled by `unflatten()`. Does it make sense?

**Comment by albanD** [comment]
Right so it will take two arguments, the dimension to unflatten and the new shape this dimension should take. Matching the unflatten API of `tensor.unflatten()`.
Sounds good !

**Comment by alvgaona** [comment]
I'll create a PR then. Is that ok?

**Comment by albanD** [comment]
Yes that sounds good. You can add me as a reviewer when it's ready!

**Comment by zou3519** [comment]
Merged in #41564 thanks to @alvgaona, so I am closing this.
