### ISSUE TITLE
how do I find proper version can be compile with c++11 

### ISSUE THREAD

**Issue by Ilikeyou3000** [pytorch/pytorch#41518]
### My libtorch 1.4 reports bug while  reading torchscripts, libtorch1.5 fixes the bug but it calls for c++14 compilation. I want find a version that works with c++11, where should i start?

the bug issue address: https://github.com/pytorch/pytorch/issues/31960

**Comment by ezyang** [comment]
you need a version of pytorch before d0acc9c0859847e18633fbbcf22399673f53537e
