### ISSUE TITLE
torch.svd docs: `some` parameter?

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#4152]
The documentation of the `some` parameter to `torch.svd` is one of the strangest I've seen... what does `some=True` (the default) do???

> 
> torch.svd(input, some=True, out=None) -> (Tensor, Tensor, Tensor)
> ...
> some represents the number of singular values to be computed. If some=True, it computes some and some=False computes all.
>

**Comment by SsnL** [comment]
Ha it is somewhat weird indeed. When `some=False`, the returned U and V matrices are square orthonormal matrices. I will send out a PR to clarify this.
