### ISSUE TITLE
Support cuda 9.1

### ISSUE THREAD

**Issue by tstandley** [pytorch/pytorch#4156]
Support for cuda 9.1 would be useful. For one thing, currently you can't download cuda 9.0 from NVIDIA's website.

**Comment by soumith** [comment]
this should work out of the box already.

**Comment by soumith** [comment]
and our binaries dont rely on a system cuda being installed, we ship relevant bits ourselves. So, if you install the cuda9 binaries from http://pytorch.org they will just work.

**Comment by tstandley** [comment]
Are you saying I don't need to install cuda at all to use pytorch?

**Comment by soumith** [comment]
you dont need to install cuda or cudnn. all you need to use pytorch on the gpu is a working nvidia driver

**Comment by tstandley** [comment]
Awesome.

On Wed, Dec 13, 2017 at 12:30 PM, Soumith Chintala <notifications@github.com

**Comment by ngimel** [comment]
Because it requires a working nvidia driver, and if someone has cuda 8.0, pytorch compiled with cuda 9.0 won't run on that machine (similarly, if someone has cuda 9.0 driver, pytorch compiled with cuda 9.1 won't run on that machine).

**Comment by gdshen** [comment]
@ngimel maybe the nvidia driver version 384 would support cuda 8&9 both?

**Comment by ngimel** [comment]
Yes, driver is backward-compatible, so 387 would support executables built with both cuda 8 and cuda 9. Not everyone is quick to update driver, though, so pytorch provides builds with cuda 8.

**Comment by u39kun** [comment]
On http://pytorch.org, I see install instructions for cuda 9.0 but not for 9.1, though.  For 9.1, do we need to build PyTorch from source at the moment?

**Comment by soumith** [comment]
@u39kun yes.

**Comment by u39kun** [comment]
Got it.  Thanks for confirming, @soumith

**Comment by untom** [comment]
Are there any plans to make prebuild binaries/wheels available for cuda 9.1 at some point?

**Comment by apaszke** [comment]
CUDA9 binaries should be compatible with 9.1

**Comment by mkwissam** [comment]
hello. 
I tried to use pytorch with cuda 9.1.85 but torch.cuda.is_available() returnes false

My env is:

Ubuntu 18.04.1 LTS
conda 4.6.10

Python 3.5
Command used to install torch 

conda install pytorch torchvision cudatoolkit=9.0 -c pytorchconda

**Comment by soumith** [comment]
@mkwissam the only reason I can see this happen is maybe if you have an insufficient driver. Otherwise, I cant think of a good reason.

**Comment by tashrifbillah** [comment]
> this should work out of the box already.
@soumith , what version should work for the issue description?
