### ISSUE TITLE
ProfilingRecord reports wrong static stride information.

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#41573]
## 🐛 Bug

ProfilingRecord gives wrong static stride_ information when merging TensorType with varying stride.

I have a simple example, where two different shape is feed to a graph.
```
torch._C._jit_set_profiling_mode(True)
torch._C._jit_set_num_profiled_runs(2)

#...

x1 = torch.randn(4, 8, 8, dtype=torch.float32, device="cuda")
jit_model(x1)
x2 = torch.randn(4, 16, 8, dtype=torch.float32, device="cuda")
jit_model(x2)

#...
```

Where the ProfilingRecord wrongfully reports a static stride of `64, 8, 1` for the input tensor. Which is not correct, as we can see the stride for the slowest dimension is not static.

## Additional context

The merging logic looks fine all the way until this line: https://github.com/pytorch/pytorch/blob/728fd37d92462366167e3931b7f41d704606a600/torch/csrc/jit/runtime/profiling_record.cpp#L283
```
            auto type = merged_profiled_types[val_type_pair.first];
            auto merged_type = type->merge(val_type_pair.second);
            if (merged_type->sizes().size().has_value()) {
              auto new_shape = raw_pr->mergeSymbolicShapes(
                  val_type_pair.second->symbolic_sizes(),
                  type->symbolic_sizes(),
                  partition_helper);
              GRAPH_DEBUG(
                  "Merging ",
                  *val_type_pair.second,
                  " of run ",
                  profiled_types_iter->first,
                  " into ",
                  *type);
              merged_type = type->withSymbolicShapes(new_shape);
```
Where we get `merged_type` from `type->withSymbolicShapes()`, so we are basically not merging the stride information at all.

cc @suo @gmagogsfm

**Comment by Krovatkin** [comment]
@jjsjann123 If I remember correctly you either fixed it or it ended up to not matter?

**Comment by jjsjann123** [comment]
It doesn't matter since we don't use type merge, we stick to single profiling run at this moment.

Thanks for tracking this.
