### ISSUE TITLE
Remove torch/csrc/utils/future.h

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#41574]
We currently have two Future classes: https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/future.h#L29 and https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/ivalue_inl.h#L222.

As part of the consolidation work for the Future, my impression was that we only use the latter and not the former. In that case, can we get rid of former? Or are there still a bunch of places that use `torch/csrc/utils/future.h`? If so, are we tracking this work in a separate task?

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @xush6528

**Comment by rohan-varma** [comment]
It's still used internally by the RPC framework as `FutureMessage`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/message.h#L146

**Comment by pritamdamania87** [comment]
>  I think from what I remember, the plan was to make torch/csrc/utils/future.h the single future impl in PyTorch, and have the IValue future be a specialized version of this that is constrained to hold an ivalue.

My impression was that the long term goal was to have only one Future class and that can be IValue future. Looking at the Message class, it looks like it has a payload (std::vector<char>), a list of tensors and a int64_t id. This can be represented as a IValue tuple: (str, list[tensor], int64_t). I think we can do something like `using Message = ivalue::Tuple` and have some helper conversion functions to support the operations we have currently.

**Comment by rohan-varma** [comment]
> My impression was that the long term goal was to have only one Future class and that can be IValue future. Looking at the Message class, it looks like it has a payload (std::vector), a list of tensors and a int64_t id. This can be represented as a IValue tuple: (str, list[tensor], int64_t). I think we can do something like `using Message = ivalue::Tuple` and have some helper conversion functions to support the operations we have currently.

That sounds good to me as well, although we'd probably want to be a bit careful to ensure that adding new fields to the `Message` class does not have to result in too much refactoring around the ivalue future. Having a generic (non-ivalue) future could also be useful in future cases where parts of PT want to use futures without ivalues, although since there isn't a use case for that currently, I can see the reasoning for making it an ivalue future.
