### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by SagarPalyal** [pytorch/pytorch#41585]
## 🐛 Bug

I am using pytorch cpu version 1.5.0 as a dependency for haystack, but when trying importing modules it is giving OSError: which is caused by 'torch' dll's present in directory torch/lib/*.dll

below is the error traceback:

>>> from haystack.indexing.utils import convert_files_to_dicts, fetch_archive_from_http
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\workspace\QAGOT\lib\site-packages\haystack\indexing\utils.py", line 8, in <module>
    from farm.data_handler.utils import http_get
  File "E:\workspace\QAGOT\lib\site-packages\farm\__init__.py", line 3, in <module>
    import torch.multiprocessing as mp
  File "E:\workspace\QAGOT\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "E:\workspace\QAGOT\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

 - PyTorch Version (e.g., 1.5.0):
 - OS (e.g., Linux): windows
 - How you installed PyTorch (`conda`, `pip`, source): pip / source = http://download.pytorch.org/whl/cpu/torch_stable.html
 - Build command you used (if compiling from source):
 - Python version: 3.3.7
 - CUDA/cuDNN version: Not using
 - GPU models and configuration: not using
 - Any other relevant information: using torch as a dependency for haystack

is this torch windows dll related issue or platform issue?

cc @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment]
It should be a env-related problem. You cam try to patch `E:\workspace\QAGOT\lib\site-packages\torch\__init__.py` with https://gist.github.com/peterjc123/bcbf4418ff63d88e11313d308cf1b427.

> * Python version: 3.3.7

Is this a typo? We don't support Python 3.3.

**Comment by SagarPalyal** [comment]
Thanks for your suggestion. Yes thats typo, python version I am using is 3.7

**Comment by mszhanyi** [comment]
@SagarPalyal , Does the issue still exist?

**Comment by SagarPalyal** [comment]
I setup 64 bit Python version and issue resolved.
