### ISSUE TITLE
TorchScript will report an error if my `lengths` is a CUDA tensor

### ISSUE THREAD

**Issue by jimlinntu** [pytorch/pytorch#41582]
## To Reproduce

1. Directly run the following code

```python
import torch
from torch import nn

class DummyModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x, lengths):
        return nn.utils.rnn.pack_padded_sequence(x, lengths, batch_first=True, enforce_sorted=True)

def main():
    N, T, F = 5, 30, 50
    lengths = torch.tensor([5, 4, 2, 2, 1], dtype=torch.int32).cuda()
    x = torch.ones((N, T, F)).cuda()

    model = DummyModel()
    scripted_model = torch.jit.script(model)

    # This ok
    scripted_model(x, lengths.cpu())

    # This will report an error
    scripted_model(x, lengths)

if __name__ == "__main__":
    main()
```

## Expected behavior
`nn.utils.rnn.pack_padded_sequence` should allow a CUDA tensor for the `lengths` argument.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1+cu101
 - OS (e.g., Linux): Ubuntu 18.04.2 LTS
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source): None
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0.130 / 7.6.0
 - GPU models and configuration: NVIDIA
 - Any other relevant information:

cc @zou3519 @suo @gmagogsfm

**Comment by jansel** [comment]
@wanchaol to look into this and triage it.

**Comment by wanchaol** [comment]
@jimlinntu I did some investigation, apparently it's not a torchscript issue, if you comment out the `torch.jit.script` line it still complains that `lengths` should be a 1D CPU int64 tensor. given that `pack_padded_sequence` is a "tensor constructor" and does not involve computation, I don't see a reason why you need to pass `lengths` as CUDA tensor?

cc @zou3519

**Comment by jimlinntu** [comment]
@wanchaol Thanks for pointing out!
I think in the torch 1.3 version, I will not receive an error if I try to pass `lengths` as a CUDA tensor.
So I bump into this situation after I upgrade it from 1.3 to 1.5.

**Comment by wanchaol** [comment]
@jimlinntu do you still have issues on this? I am closing it but feel free to reopen if it still applies to you
