### ISSUE TITLE
Unexpected results when trying to assign an array to another tensor with advanced indexing

### ISSUE THREAD

**Issue by JiangWenPL** [pytorch/pytorch#41581]
## To Reproduce
PyTorch would have unexpected behavior when I try to assign an array wrapped with `torch.tensor` to another torch tensor with advanced indexing. 

I have a simple script to reproduce this bug:

```
import torch
import numpy as np
a = torch.rand(5)
b = np.arange(5)
a[torch.arange(2)] = torch.tensor(b[:2])
print(a)
```

## Expected behavior

The first two entries should be `tensor([0., 1., ...])` but it actually output: `tensor([0.0000e+00, 1.4013e-45, ...])`. Specifying data type in `torch.tensor` could fix this but it's still very weird.

## Environment

```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.56
cuDNN version: /usr/local/lib/libcudnn.so.6

Versions of relevant libraries:
[pip] neural-renderer-pytorch==1.1.3
[pip] numpy==1.17.3
[pip] torch==1.3.0
[pip] torchgeometry==0.1.2
[pip] torchvision==0.4.1
[conda] neural-renderer-pytorch   1.1.3                     <pip>
[conda] numpy                     1.17.3                    <pip>
[conda] torch                     1.3.0                     <pip>
[conda] torchgeometry             0.1.2                     <pip>
[conda] torchvision               0.4.1                     <pip>
```

## Additional context

I tried to search related issues but didn't find them. Please tell me and close this issue if you find a similar issue. Thank you!

**Comment by zou3519** [comment]
@JiangWenPL we've fixed this bug in recent versions of PyTorch. The bug gets triggered when one tries to assign a tensor with a different `dtype` (on the left we have a float tensor and on the right we have a long tensor). As a fix you can upgrade to the latest version of PyTorch (1.5.0), with instructions on our website.

As a workaround, in your example:
```
import torch
import numpy as np
a = torch.rand(5)
b = np.arange(5)
a[torch.arange(2)] = torch.tensor(b[:2]).to(a.dtype)
print(a)
```
