### ISSUE TITLE
[docs] Extra backticks in docs of narrow_copy

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#41590]
https://pytorch.org/docs/master/tensors.html?highlight=narrow_copy#torch.Tensor.narrow_copy:

![image](https://user-images.githubusercontent.com/1041752/87787192-83ea0880-c83b-11ea-9cfa-fc7b78c59591.png)

Maybe worth having some assert/search that docs have no backticks (usually, it's an indicator of markdown problem)

cc @jlin27

**Comment by zou3519** [comment]
That sounds reasonable. Off of the top of my head I think that having an assert that the docs don't have a backtick sounds reasonable, we could add it to the docs CI job
