### ISSUE TITLE
cudnn8 version check fails

### ISSUE THREAD

**Issue by dawonn-haval** [pytorch/pytorch#41593]
https://github.com/pytorch/pytorch/blob/e48ffa84d801a546d1c25bf52867e0fed8805723/cmake/public/cuda.cmake#L128

cmake fails to identify cudnn version:
```
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v?  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at /home/haval/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:170 (message):
  PyTorch requires cuDNN 7 and above.
```

@ /home/haval/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:L148 
the version number is being extracted from cudnn.h, but this may have been moved to a separate file (cudnn_version):
```
/usr/include/x86_64-linux-gnu/cudnn_adv_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_adv_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_backend_v8.h
/usr/include/x86_64-linux-gnu/cudnn_cnn_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_cnn_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_ops_infer_v8.h
/usr/include/x86_64-linux-gnu/cudnn_ops_train_v8.h
/usr/include/x86_64-linux-gnu/cudnn_v8.h
/usr/include/x86_64-linux-gnu/cudnn_version_v8.h
```
Note that cudnn.h now appears to be a 'metapackage' file that includes the rest of the headers for backwards compatibility, but the cmake version regex fails because it doesn't load #include files...

Related: https://github.com/traveller59/spconv/issues/196

cc @malfet @ngimel @csarofeen @ptrblck

**Comment by jasjuang** [comment]
Just ran into the same problem.

**Comment by ngimel** [comment]
cc @zasdfgbnm - how is this handled in the CI builds?

**Comment by zasdfgbnm** [comment]
These lines has already been changed to
```cmake
  # Get cuDNN version
  if(EXISTS ${CUDNN_INCLUDE_PATH}/cudnn_version.h)
    file(READ ${CUDNN_INCLUDE_PATH}/cudnn_version.h CUDNN_HEADER_CONTENTS)
  else()
    file(READ ${CUDNN_INCLUDE_PATH}/cudnn.h CUDNN_HEADER_CONTENTS)
  endif()
```
please update to latest master branch

**Comment by ngimel** [comment]
Closing, please reopen if needed.

**Comment by sainisanjay** [comment]
This issue still exist in the PyTorch 1.7.0.
OS: `Ubuntu 20.04.1 LTS`
CUDA: `11.1`
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
CuDNN: `cudnn-11.1-linux-x64-v8.0.5.39.tgz`


```
python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
creating build/lib.linux-x86_64-3.7/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
running build_ext
Release
|||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/saini/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10700', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saini/siemens_data/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
-- The CXX compiler identification is GNU 9.3.0
-- The CUDA compiler identification is NVIDIA 11.1.105
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-11.1 (found version "11.1") 
-- Caffe2: CUDA detected: 11.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.1/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.1
-- Caffe2: Header version is: 11.1
-- Found CUDNN: /usr/local/cuda-11.1/lib64/libcudnn.so  
-- Found cuDNN: v?  (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
CMake Error at /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/saini/siemens_data/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/home/saini/siemens_data/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/saini/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/saini/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saini/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/home/saini/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saini/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/saini/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 48, in run
    self.build_extension(ext)
  File "setup.py", line 91, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/saini/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/saini/siemens_data/spconv', '-DCMAKE_PREFIX_PATH=/home/saini/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10700', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saini/siemens_data/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by phospheneai** [comment]
> This issue still exist in the PyTorch 1.7.0.
> OS: `Ubuntu 20.04.1 LTS`
> CUDA: `11.1`
> nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Mon_Oct_12_20:09:46_PDT_2020
> Cuda compilation tools, release 11.1, V11.1.105
> Build cuda_11.1.TC455_06.29190527_0
> CuDNN: `cudnn-11.1-linux-x64-v8.0.5.39.tgz`
> 
> ```
> python setup.py bdist_wheel
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.7
> creating build/lib.linux-x86_64-3.7/spconv
> copying spconv/test_utils.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/pool.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/conv.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/tables.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/modules.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/ops.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/__init__.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/identity.py -> build/lib.linux-x86_64-3.7/spconv
> copying spconv/functional.py -> build/lib.linux-x86_64-3.7/spconv
> creating build/lib.linux-x86_64-3.7/spconv/utils
> copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.7/spconv/utils
> running build_ext
> Release
> |||||CMAKE ARGS||||| ['-DCMAKE_PREFIX_PATH=/home/saini/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10700', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saini/siemens_data/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']
> -- The CXX compiler identification is GNU 9.3.0
> -- The CUDA compiler identification is NVIDIA 11.1.105
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc
> -- Check for working CUDA compiler: /usr/local/cuda-11.1/bin/nvcc -- works
> -- Detecting CUDA compiler ABI info
> -- Detecting CUDA compiler ABI info - done
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found CUDA: /usr/local/cuda-11.1 (found version "11.1") 
> -- Caffe2: CUDA detected: 11.1
> -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.1/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.1
> -- Caffe2: Header version is: 11.1
> -- Found CUDNN: /usr/local/cuda-11.1/lib64/libcudnn.so  
> -- Found cuDNN: v?  (include: /usr/local/cuda-11.1/include, library: /usr/local/cuda-11.1/lib64/libcudnn.so)
> CMake Error at /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:174 (message):
>   PyTorch requires cuDNN 7 and above.
> Call Stack (most recent call first):
>   /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
>   /home/saini/anaconda3/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
>   CMakeLists.txt:22 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/saini/siemens_data/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
> See also "/home/saini/siemens_data/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "setup.py", line 108, in <module>
>     zip_safe=False,
>   File "/home/saini/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/home/saini/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/saini/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
>     self.run_command('build')
>   File "/home/saini/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/home/saini/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/home/saini/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/home/saini/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "setup.py", line 48, in run
>     self.build_extension(ext)
>   File "setup.py", line 91, in build_extension
>     subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
>   File "/home/saini/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '/home/saini/siemens_data/spconv', '-DCMAKE_PREFIX_PATH=/home/saini/anaconda3/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DPYTORCH_VERSION=10700', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saini/siemens_data/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
> ```
> 
> @dawonn-haval did you able to solve this issue?


When you copy your cudnn.h file into "cuda/vxx/include" it doesn't contain certain things in the Header portion.
So in this case this you need to copy cudnn_version.h file into your cuda directory.

**Comment by natsume7** [comment]
edit torch/share/cmake/Caffe2/public/cuda.cmake at line 148
replace file(READ ${CUDNN_INCLUDE_PATH}/cudnn.h CUDNN_HEADER_CONTENTS)
with file(READ ${CUDNN_INCLUDE_PATH}/cudnn_version.h CUDNN_HEADER_CONTENTS)

**Comment by zhenyuzhouiu** [comment]
However I meet the question again on my ubuntu (21.04) with CUDA version 11.2 and cudnn 8.1.1. Below is the error:

`-- Found CUDNN: /usr/lib/x86_64-linux-gnu  
CMake Error at /usr/local/libtorch1.8/share/cmake/Caffe2/public/cuda.cmake:152 (file):
  file failed to open for reading (No such file or directory):

    /usr/include/x86_64-linux-gnu/cudnn.h
Call Stack (most recent call first):
  /usr/local/libtorch1.8/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /usr/local/libtorch1.8/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:17 (find_package)


-- Found cuDNN: v?  (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu)
CMake Error at /usr/local/libtorch1.8/share/cmake/Caffe2/public/cuda.cmake:175 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  /usr/local/libtorch1.8/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /usr/local/libtorch1.8/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:17 (find_package)
`

And I check the path  /usr/include/x86_64-linux-gnu, cudnn.h and cudnn_version.h don't exist here!

**Comment by sanjibnarzary** [comment]
I had the same problem encountered when building latest pytorch from source.  (as of 21 September 2023)
I tried changing relevant environment variable in cmake/Modules_CUDA_fix/[FindCUDNN.cmake](https://github.com/pytorch/pytorch/blob/main/cmake/Modules_CUDA_fix/FindCUDNN.cmake) but it did not work for me.

The following will work on latest main branch with CUDA 12.2
Remove the existing cudnn.h from /usr/include/cudnn.h and then link the cudnn_version.h from `$CUDA_HOME/include`. The pytorch setup search for `/usr/include/cudnn.h` or relevant paths.  You can find it from error. Even if it is not there you need to create it or link it.



Assuming you have CUDA 12.2, I am using Nvidia DGX Station with Ubuntu 22.04 (LTS) 4 V100 GPU 32 GB with CUDA 12.2, conda env
First you need to download and copy the required >v8 cudnn library [cudNN](https://developer.nvidia.com/cudnn). Instructions are also available in how to install section.

To create and link cudnn.h
```
sudo rm /usr/include/cudnn.h #in case it exists
sudo ln -s /usr/local/cuda/include/cuda_version.h /usr/include/cudnn.h
```
