### ISSUE TITLE
Is `torch.distributed.barrier` compatible with multi-node distributed data-parallel training?

### ISSUE THREAD

**Issue by leimao** [pytorch/pytorch#41613]
## ❓ Questions and Help

Hello, I have one quick question. Is `torch.distributed.barrier` compatible with multi-node distributed data-parallel training? I was using `torch.nn.parallel.DistributedDataParallel` and `torch.distributed.launch` for training the model on multiple-node, it worked fine on one node and multiple nodes. Later, I wanted to add some code into the Python that is not multi-process safe, such as creating directories and downloading data. So I was making sure only the first local rank in the node is doing those and I used `torch.distributed.barrier`. The new training script worked fine for one node training but halted on multi-node training. I was checking the documents and examples online but was not able to find any evidence that `torch.distributed.barrier` works with multi-node distributed data-parallel training. So I would like to confirm it from the community. Thank you.

Best,

Lei

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by leimao** [comment]
The discussion is in the PyTorch forum. 
https://discuss.pytorch.org/t/torch-distributed-barrier-used-in-multi-node-distributed-data-parallel-training/89711

**Comment by zhaojuanmao** [comment]
yes, it can be used in distributed data parallel training

**Comment by rohan-varma** [comment]
Closing since this is more appropriate for the forums where it is being discussed.
