### ISSUE TITLE
[feature request] torch.left_shift, torch.right_shift (including inplace and out-variant) in addition to existing python magics

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#41624]
There is no version of rshift/lshift functions with out argument. It seems that these functions are only available as Python magics. I propose these functions to be properly exposed in Python as well, with `out` arguments.

I need this for inplace unpackbits: https://github.com/pytorch/pytorch/issues/32867

There may also be a dispatch problem with bitwise_and:

```python
import torch

a = torch.zeros(3, 4, dtype = torch.int32)
b = torch.zeros(3, 4, dtype = torch.int32)

torch.bitwise_and(a, 1, out = b) #works

a.bitwise_and(1, out = b)
#TypeError: bitwise_and() received an invalid combination of arguments - got (int, out=Tensor), but expected one of:
# * (Tensor other)
# * (Number other)
```

It would also be cool to have various reduction modes for out-of-place ops: |=, &=, ^= etc. Then these current lines from https://gist.github.com/vadimkantorov/30ea6d278bc492abf6ad328c6965613a could be simplified:
```python
        compress = sliced_input << (nbits * (packed_size - e - 1))
        torch.bitwise_or(compress, sliced_output, out = sliced_output)

        expand = sliced_input >> (nbits * (packed_size - e - 1))
        torch.bitwise_and(expand, mask, out = sliced_output)
```

Especially given that scatter_ is getting reduction mode choice: https://github.com/pytorch/pytorch/issues/22378

cc @mruberry @rgommers

**Comment by mruberry** [comment]
The method `torch.Tensor.bitwise_and` doesn't support an `out` argument, unlike `torch.bitwise_and`, which is why you're getting the error message in the first case. That issue should be treated separately, however.

The latter request for different reduction modes for certain ops would also be a separate issue. 

As for the main issue here, `left_shift` and `right_shift` are available in NumPy and can be added to the Rollup issue https://github.com/pytorch/pytorch/issues/38349.

**Comment by vadimkantorov** [comment]
It would also be nice if it supported `torch.left_shift(tensor1, tensor2)` (tensor as the amount of shift argument)

**Comment by ngimel** [comment]
IMplemented in #59544

**Comment by vadimkantorov** [comment]
> It would also be cool to have various reduction modes for out-of-place ops: |=, &=, ^= etc.

@ngimel Do you have any thoughts about this feature request? Does it look useful? Should I factor it out in its own issue?

**Comment by ngimel** [comment]
As @mruberry suggested, request for the different reduction modes should go to its own issue
