### ISSUE TITLE
When to support nccl or gloo on windows ?

### ISSUE THREAD

**Issue by y78h11b09** [pytorch/pytorch#41629]
Thank you for your great work.
I run my dataset on window with pytorch 1.4.0
but it's very regret i can't use the torch.distributed funciton on windows
I hope strongly the developmenter to add this feature for some researcher on windows!

best regards for you!

**Comment by peterjc123** [comment]
As for NCCL, please open a post at NVIDIA discussion forum.
Regarding distributed support, please add a comment in https://github.com/pytorch/pytorch/issues/37068.

**Comment by y78h11b09** [comment]
> As for NCCL, please open a post at NVIDIA discussion forum.
> Regarding distributed support, please add a comment in #37068.

Ok, I have do it!
