### ISSUE TITLE
whitelist keyword to quantization.prepare is implemented incorrectly

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#41633]
## 🐛 Bug

The rendered docs for `quantization.prepare` look like this right now (see [the quantization docs page](https://pytorch.org/docs/master/quantization.html#torch.quantization.prepare)):

<img width="554" alt="image" src="https://user-images.githubusercontent.com/98330/87856708-2203ce80-c921-11ea-9a6a-df173ab2b7d7.png">

Using a large `set` as a default argument makes little sense, the right way to do this is `whitelist=None`.

Also, the documentation of this keyword is too sparse. If the user needs to modify this, I assume it's to add their own module to the existing whitelist, rather than providing a whitelist with only their own module. Is that correct? If so, it should be documented how to do that. `torch.quantization.DEFAULT_QCONFIG_PROPAGATE_WHITE_LIST` is public apparently, but not documented in https://pytorch.org/docs/master/quantization.html  

Introduced in gh-36701. @hx89 can you comment on this? 

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
the default argument is changed to None in https://github.com/pytorch/pytorch/pull/42576

**Comment by jerryzh168** [comment]
for doc fixes, we'll revisit before the 1.7 release

**Comment by malfet** [comment]
Seems to be fixed in latest master:
https://pytorch.org/docs/master/torch.quantization.html#torch.quantization.prepare
![image](https://user-images.githubusercontent.com/2453524/120403474-1e8af300-c2f9-11eb-921e-03acc983c719.png)
