### ISSUE TITLE
[Feature Request] Support PyPy

### ISSUE THREAD

**Issue by redradist** [pytorch/pytorch#41634]
## 🚀 Feature
Add support for PyPy interpreter

## Motivation
Increase speed of Python code that do not relate to PyTorch

**Comment by Coderx7** [comment]
Did you check  : https://github.com/pytorch/pytorch/issues/17835

**Comment by redradist** [comment]
@Coderx7 Yeah ) Should be closed as duplicated of https://github.com/pytorch/pytorch/issues/17835
