### ISSUE TITLE
Very uninformative stack-trace when exception thrown in custom autograd backward

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#41659]
I had message-less assert in my custom autograd function backward. Note absence of the function name or class name. This happens with conda python. I think this is standard Python problem: `allow_unreachable=True)  # allow_unreachable flag`, but maybe this is related to Python/C++ interaction?

```
Traceback (most recent call last):
  File "benchmark.py", line 103, in <module>
    y.sum().backward()
  File "/miniconda/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/miniconda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError
```

In fact this is an AssertionError

cc @ezyang @SsnL @albanD @zou3519 @gqchen @yf225 @glaringlee

**Comment by vadimkantorov** [comment]
One more traceback of error from C++ - again truncated traceback:
```
Traceback (most recent call last):
  File "benchmark.py", line 85, in <module>
    y = model(load_batch(batch))
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/convasr/models.py", line 157, in forward
    x = subblock(x, residual = residual, lengths_fraction = xlen)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/convasr/models.py", line 77, in forward
    residual_inputs = [bn(conv(r)) for conv, bn, r in zip(self.conv_residual, self.bn_residual, residual)]
  File "/root/convasr/models.py", line 77, in <listcomp>
    residual_inputs = [bn(conv(r)) for conv, bn, r in zip(self.conv_residual, self.bn_residual, residual)]
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 212, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 31.75 GiB total capacity; 29.70 GiB already allocated; 9.69 MiB free; 30.76 GiB reserved in total by PyTorch)
```

**Comment by ezyang** [comment]
This is worth fixing. Can you run this under gdb and add a `catch throw` breakpoint?

More generally, when errors originate from user C++ extensions, we should STOP suppressing backtraces and print the C++ backtrace as well.

**Comment by vadimkantorov** [comment]
Will do!

**Comment by albanD** [comment]
@ezyang I realized last week that the Future API eats up error types: it only saves the message and then throw a custom FutureError in the waiting thread (which is not even a c10::Error) with the saved message.
Since we moved to use this API recently in the engine, this might be the reason :/

**Comment by vadimkantorov** [comment]
I saw this truncation since forever. Not sure if it's related to any new changes

**Comment by albanD** [comment]
I think the fact that the line is truncated is from python. And I don't think we can do much about it.

The fact that the type of the exception is lost, we should fix.

**Comment by ezyang** [comment]
Err, why is it truncated in Python?

**Comment by vadimkantorov** [comment]
Is it lost in Python stack / traceback info? or is it just printed incorrectly?

**Comment by vadimkantorov** [comment]
If PyTorch controls what RuntimeError message is printed, maybe it could recover some part of stack trace that Python is missing

**Comment by albanD** [comment]
Just to make sure we're talking about the same thing.
You are expecting to see:
```
    Variable._execution_engine.run_backward(
        tensors, grad_tensors, retain_graph, create_graph,
        allow_unreachable=True)  # allow_unreachable flag
```
as the line being pointed at by the stack trace but you only get
```
        allow_unreachable=True)  # allow_unreachable flag
```
right?

It's not truncated in the sense that some frames are missing. It is more that one line of code is not enough to get the information you want.

**Comment by vadimkantorov** [comment]
right! that's the case. it seems it simply doesn't print the full function call line

**Comment by vadimkantorov** [comment]
I wonder if we do not wrap these lines, would Python include the full line? :)

Unfortunately this does not help with the custom autograd function: this error message does not include the line number in my custom code.

**Comment by albanD** [comment]
> I wonder if we do not wrap these lines, would Python include the full line? :)

Yes if we wrote it in a single line, it would print it all. But then the linter won't be happy :D 

> this error message does not include the line number in my custom code.

I think that we want to make two changes here:
- Make sure the error is propagated without alteration between the autograd worker thread and the main thread.
- Attach more info to error that happen when we know that we are running python code in the engine.

**Comment by vadimkantorov** [comment]
Maybe if it's just a few lines in PyTorch that are at Python <-> C++ boundary (and maybe they're mostly in codegen?)?, then silencing linter is an okay solution to the truncation problem?

Also it's a bit nasty that it didn't preserve original AssertionError type in the default message

**Comment by albanD** [comment]
Partially fixed in https://github.com/pytorch/pytorch/pull/43684

**Comment by soulitzer** [comment]
Seems fine when the tensor is on cuda as well (when tested on colab, pytorch 1.7), so the error appears to be propagated properly between the worker thread and main thread. 

```
---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-2-cb744e4701db> in <module>()
     14 
     15 a = torch.tensor(1., requires_grad=True, device="cuda")
---> 16 fn.apply(a).backward()

3 frames

<ipython-input-2-cb744e4701db> in backward(ctx, grad_output)
     10     def backward(ctx, grad_output):
     11         print(grad_output.device)
---> 12         assert False
     13         return torch.zeros_like(grad_output)
     14 

AssertionError: 
```

**Comment by soulitzer** [comment]
Here is the relevant code for the above output:
```
import torch

class fn_(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return torch.ones_like(x)

    @staticmethod
    def backward(ctx, grad_output):
        print(grad_output.device)
        assert False
        return torch.zeros_like(grad_output)
fn = fn_.apply
a = torch.tensor(1., requires_grad=True, device="cuda")
fn(a).backward()
```
@vadimkantorov  does this match what you are expecting, or are there any other issues?

**Comment by vadimkantorov** [comment]
The other part was cut multi-lines in tracebacks. And that it would be good to silence linter and better have long single-lines rather than cut tracebacks

**Comment by albanD** [comment]
> And that it would be good to silence linter and better have long single-lines rather than cut tracebacks (or better traceback printing function e.g. as here).

I am not sure actually if this will be useful to users to see the full line because it calls into `torch._C` that they have no idea what it is anyways.

What about modifying this call side from
```
allow_unreachable=True)  # allow_unreachable flag
```
to
```
allow_unreachable=True)  # Calls into the C++ engine to run the backward pass
```

That would provide as much information to the end user no?

**Comment by vadimkantorov** [comment]
I think it's not enough, since the name of the function is concealed :(

**Comment by vadimkantorov** [comment]
It seems that all function calls inside Python should be on one line :( are there many Python land function calls? (at least on the autograd call path). Given that more and more code is moved to C++, maybe not that many left

**Comment by albanD** [comment]
> I think it's not enough, since the name of the function is concealed :(

But that function internal and does not exist in python (`Variable._execution_engine.run_backward`). Is it really important to show it?

Also, it is concealed only when using the python CLI default stack printer. If you use a notebook for example, you will see it properly. And nothing prevents you from having a custom stack printer in you CLI.


> It seems that all function calls inside Python should be on one line :(

That sounds quite unrealistic and explicitly again the linter's rule.
I think that users that want  to better see these should just use a custom stack printer. And I don't think we should mess with the stack printer because we don't want to break things for people using notebooks for example.

**Comment by vadimkantorov** [comment]
1. It's in this particular example that the function is `Variable._execution_engine.run_backward`. In other examples it would be sth else and is important to know
2. I agree that PyTorch should not mess with the default stack printer. I propose that longer call lines (at least those on the module calling / autograd path, especially for generated code, and maybe data loader path as well) are put on one line, then the default stack printer would work. I think silencing linter is an okay option for easier debugging of these complex paths. Typical error is some incomplete input validation with some strange error message.
3. If it's possible, maybe the comment could include a short URL to instruction about installing/using a better stack printer
4. Maybe PyTorch could also include a modified stack printer in torch.utils? (only for explicit usage by the user)

**Comment by soulitzer** [comment]
Wouldn't putting long call lines on a single long line make it harder for non-CLI people (e.g., notebook users) to decipher tracebacks? So in that sense, we can't call this a pure ux win.

**Comment by vadimkantorov** [comment]
IMO from the user viewpoint, it would be a strict win as it'll be at least clear which function got called

**Comment by vadimkantorov** [comment]
From what I understood from @albanD the Notebook stack printer is a separate one. If it processes multi-line calls correctly, it should format them correctly as well, I guess

**Comment by vadimkantorov** [comment]
Improved in Python 3.8+ and in https://github.com/pytorch/pytorch/pull/65564 and in other PRs mentioned in this issue
