### ISSUE TITLE
torch.nn.functional.grid_sample segfaults on large inputs

### ISSUE THREAD

**Issue by erdmann** [pytorch/pytorch#41656]
## 🐛 Bug

Running `grid_sample` on a single image with large dimensions causes a segfault.

## To Reproduce

The following is a minimum reproducible snippet that will consistently cause a segfault:

```python
import torch
coords = torch.tensor([[[[-1., -1.],
                         [ 1., -1.]],

                        [[-1.,  1.],
                         [ 1.,  1.]]]])

im = torch.zeros([1, 1, 32769, 65536])

result = torch.nn.functional.grid_sample(im, coords, align_corners=False)

```

Note, however, that the following code works fine:

```python
import torch
coords = torch.tensor([[[[-1., -1.],
                         [ 1., -1.]],

                        [[-1.,  1.],
                         [ 1.,  1.]]]])

im = torch.zeros([1, 1, 32768, 65536])

result = torch.nn.functional.grid_sample(im, coords, align_corners=False)

```

## Expected behavior

The first code snippet should not cause a segfault.

## Environment

I tested on two machines:  An NVIDIA DGX STATION, and a MacBook.

DGX STATION:
```
Collecting environment information...
PyTorch version: 1.4.0+cu100
Is debug build: No
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-32GB
GPU 1: Tesla V100-DGXS-32GB
GPU 2: Tesla V100-DGXS-32GB
GPU 3: Tesla V100-DGXS-32GB

Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] numpydoc==0.9.1
[pip] pytorch3d==0.2.0
[pip] torch==1.4.0+cu100
[pip] torchstat==0.0.7
[pip] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] liblapacke                3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.15           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] numpy                     1.17.4           py36hc1035e2_0  
[conda] numpy-base                1.17.4           py36hde5b4d6_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] pytorch3d                 0.2.0                    pypi_0    pypi
[conda] torch                     1.4.0+cu100              pypi_0    pypi
[conda] torchstat                 0.0.7                    pypi_0    pypi
[conda] torchvision               0.4.2                py36_cu100    pytorch

```

MacBook:

```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: version 3.16.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.5.1
[pip] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37hfbe908c_5  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] numpy                     1.16.2           py37hacdab7b_0  
[conda] numpy-base                1.16.2           py37h6575580_0  
[conda] numpydoc                  0.8.0                    py37_0  
[conda] pytorch                   1.5.1                   py3.7_0    pytorch
[conda] torchvision               0.6.1                  py37_cpu    pytorch

```

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by gchanan** [comment]
confirmed this is a problem on master `1.7.0a0+16dde6e`.

**Comment by xwang233** [comment]
It gives illegal memory access for cuda as well.
```py
import torch
coords = torch.tensor([[[[-1., -1.],
                         [ 1., -1.]],

                        [[-1.,  1.],
                         [ 1.,  1.]]]]).half().cuda()

im = torch.zeros([1, 1, 32769, 65536]).half().cuda()

result = torch.nn.functional.grid_sample(im, coords, align_corners=False)

torch.cuda.synchronize()
```

```
THCudaCheck FAIL file=../torch/csrc/cuda/Module.cpp line=218 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "41656.py", line 12, in <module>
    torch.cuda.synchronize()
  File "/XXX/pytorch/torch/cuda/__init__.py", line 398, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at ../torch/csrc/cuda/Module.cpp:218
```

**Comment by zou3519** [comment]
cc @ngimel for CUDA -- peterbell10 brought up in https://github.com/pytorch/pytorch/pull/41923 that we're not sure if we should support 64-bit indexing for `grid_sample` on CUDA. The downsides to supporting it is extra code/binary size/we are not sure if people use 64-bit indexing (this is the first time an issue about this has appeared I think). What are your thoughts?

**Comment by erdmann** [comment]
> cc @ngimel for CUDA -- peterbell10 brought up in #41923 that we're not sure if we should support 64-bit indexing for `grid_sample` on CUDA. The downsides to supporting it is extra code/binary size/we are not sure if people use 64-bit indexing (this is the first time an issue about this has appeared I think). What are your thoughts?

As the bug reporter, here are my two cents.

Coming from the world of cultural heritage (I'm currently photographing the Nightwatch at 5 µm resolution; see  [the 20 µm resolution version here](https://twitter.com/erdmann/status/1260118711920472070)), I can say that the ability to operate on images requiring more than 32 bits for indices is really essential, and the ability to use a GPU on these images will mean the difference between pytorch being the platform of choice for our world or not.

For example, a single photo from our Hasselblad camera is 23200 px × 17400 px × 3 channels, which is already an array with more than 30 bits for indices.  Resolution will continue to go up over time as camera technology improves.  Multi- and hyperspectral cameras that increase the number of channels by a factor of 100 will also be increasingly common, as will cameras that add a depth channel.

I can't speak to how common the need for 64-bit indexing is at the moment, but I think the need will undoubtedly go up.  "32-bit indexing ought to be enough" sounds a bit like the (probably apocryphal) ["640KB ought to be enough for anybody"](https://www.computerworld.com/article/2534312/the--640k--quote-won-t-go-away----but-did-gates-really-say-it-.html) quote.

In any case, I very much appreciate any effort that goes into expanding the limits of pytorch to operate on large arrays.  Thank you!

**Comment by ngimel** [comment]
@erdmann Thank you for your perspective, it's fascinating! 
It's true that as resolution goes up, images become bigger. But in practical terms 
1) GPU memory is usually not big enough to hold multiple large tensors 
2) Even if grid_sample was fixed to properly handle 64-bit indices on the GPU, typically you'd want to call a convolution next, and it won't work because of cudnn limitation. 
That said, binary size increase from fixing grid_sample will probably be pretty small, so if we can, we should just do it.
