### ISSUE TITLE
Weight only config and activations only config in Qconfigdynamic possible?

### ISSUE THREAD

**Issue by dhirensr** [pytorch/pytorch#41652]
### Weight only config and activations only config in Qconfigdynamic possible?

I was wondering that if weight only or activations only config is supported with Post- training dynamic quantization.
In the file https://github.com/pytorch/pytorch/blob/master/torch/quantization/qconfig.py#L64 there seems to be no option for weight only and activation only QConfigDynamic and also when I tried 
```
default_dynamic_qconfig = QConfigDynamic(activation=default_dynamic_quant_observer,
                                         weight=torch.nn.Identity)
```
It throws an error.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
for dynamic quantization, weight observer is used to determine the weight quantization parameters (https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/dynamic/modules/linear.py#L77).  Activation observer is not needed / not used.  Perhaps you are thinking of post-training static quantization, where both weight and activation observers are used?

**Comment by dhirensr** [comment]
@vkuzo : for static quantization there are many layers which are currently not supported and also cannot be fused with. for eg; LayerNorm and also few operations like division ,sin,cos etc are not yet supported. Hence I chose to dynamically quantize the network.

**Comment by vkuzo** [comment]
makes sense.  In dynamic quantization, only the weight observer is used, so modifying activation observers is likely not going to make a difference.

**Comment by raghuramank100** [comment]
Are you trying to model the numerics of quantization in fp32 and trying to simulate the effect of quantizing only weights or activations?

**Comment by dhirensr** [comment]
@vkuzo : I didn't get your point regarding only weight observer is being used.
 I see that now QConfigDynamic is taking 2 args (https://github.com/pytorch/pytorch/blob/master/torch/quantization/qconfig.py#L41) so I was trying to use something like default_weight_only_qconfig  or default_activation_only_qconfig for QConfigDynamic but it doesn't works. 

@raghuramank100 : yes, I'm training in fp32 and post -training trying to apply weights only or activations only quantization.I understand that for activations only there are some calibration required so I would have to run 2-3 epochs for calibration of scale, but the point is there are no Qconfigdynamic supporting the same .

**Comment by vkuzo** [comment]
for triage

**Comment by vkuzo** [comment]
> I didn't get your point regarding only weight observer is being used.
I see that now QConfigDynamic is taking 2 args

The two arguments were just for the signature to be consistent with `QConfig`, the activation argument in `QConfigDynamic` was not used for anything. Sorry if that was not clear.

https://github.com/pytorch/pytorch/pull/69864 removed `QConfigDynamic` to hopefully reduce confusion on this topic, hope that helps!
