### ISSUE TITLE
Enable and disable autograd profiler without context manager mechanics

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#41653]
https://discuss.pytorch.org/t/proper-way-to-enable-and-disable-autograd-profiler/89773

I think there was somewhere an GitHub issue about this already, but I could not find it

I currently do:
```python
if args.profile_autograd:
    autograd_profiler = torch.autograd.profiler.profile()
    autograd_profiler.__enter__()

# model running

if args.profile_autograd:
    autograd_profiler.__exit__(None, None, None)
    autograd_profiler.export_chrome_trace(args.profile_autograd)
```

But enable()-kind of API exists for autograd itself, so I thought maybe it exists for the profiler as well. It also exists for nvprof: torch.cuda.profiler.start()

@t-vi said in forum that context manager mechanics is needed currently

**Comment by sraikund16** [comment]
This implementation of the profiler is deprecated, closing ticket
