### ISSUE TITLE
PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by ddummkopfer** [pytorch/pytorch#41666]
## 🐛 Bug
When i use torch.from_numpy function, the log is: 'RuntimeError: PyTorch was compiled without NumPy support'

## To Reproduce

Follow the official installation guide and conda install numpy successfully.
code:
import torch as t
import numpy as n
a = t.from_numpy(n.empty(1))

## Environment
 - PyTorch Version : 1.5
 - OS : Ubuntu 18.04
 - How you installed PyTorch : From Source Code
 - Build command you used (if compiling from source):
    1. conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
    2. git clone --recursive https://github.com/pytorch/pytorch
        cd pytorch
        git submodule sync
        git submodule update --init --recursive
        export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
        python setup.py install
 - Python version: 1.5 Source Code from master branch.
 - CUDA/cuDNN version: No CUDA and cuDNN.
 - GPU models and configuration: No GPU Environment.
 - Any other relevant information: No.

cc @malfet @mruberry @rgommers

**Comment by gchanan** [comment]
looking into your build logs will probably tell you why, there should be a message about whether numpy support was compiled in or not.

**Comment by ddummkopfer** [comment]
> looking into your build logs will probably tell you why, there should be a message about whether numpy support was compiled in or not.

Hi, Thank you for your significant advisor. Is the build log in the 'build/'? What does the log file's name look like?
In my build dir, there are many files.

**Comment by mruberry** [comment]
Hey @ddummkopfer, sorry you're experiencing this issue!

This is really odd and we haven't seen it elsewhere. I don't know if we're going to be able to help you, unfortunately. The build logs that @gchanan mentions is the console output that appears while building PyTorch from source. It contains lots of useful configuration information, but I don't believe that information is automatically saved for you.

So our recommendation is to ensure that you're building PyTorch in the same conda environment you have NumPy installed in and to take a look at your build logs to check that PyTorch is finding NumPy properly. 

Separately, if you're installing from source, how is it you're getting PyTorch 1.5? The latest source should be version 1.7 now, I think.

**Comment by ddummkopfer** [comment]
Hi, thank you for your answers.
Now i use numpy 1.13.0 in my conda environment to build the pytorch source code(1.5) again.
When it finishs compilation, i test t.from_numpy() again to check if numpy is compiled with pytorch.
Wait a minute.

Another question, what is the best version for the dependency package 'cmake, ninja, mkl, mkl-include,request, setuptools' ?
@gchanan @mruberry

**Comment by mruberry** [comment]
I'm not totally sure what you're asking since those are all separate utilities?

**Comment by ddummkopfer** [comment]
@gchanan @mruberry 
Thank you for your instrcutions. Currently i have covered the issue 'without numpy supported' when i make sure install numpy then build the pytorch source code.
