### ISSUE TITLE
Parameter `timeout` in torch.distributed.init_process_group cannot work 

### ISSUE THREAD

**Issue by worsecoder** [pytorch/pytorch#41665]
Hi, I am building a system that run parallel machine learning tasks on several nodes using `torch.distributed`. I set timeout = 30 seconds in the `init_process_group` function and expected that if one nodes fails, other nodes will wait for a period and then quit. However, in my experiments, they just stuck at the failure point and never exists.

## To Reproduce

I have 2 nodes, each of which runs one process.

First I want to simulate the situations in which the slave node failed at startup, and I expect master node to quit after it cannot contact to slave.
1. In the init_process_group, assign the `world_size` to be 2
2. Set `timeout` to be 30 seconds and set NCCL_BLOCKING_WAIT  = 1
3. Only launch master node
4. Wait for 30 seconds.
5. The master process is just waiting and never terminates.

Then I want to simulate the situation in which slave node failed while training. Similarly, after terminating the slave process manually, the master just waits and stuck there.

## Expected behavior

The python script should exit and raise some errors like "connection timeout".

## Environment

* OS: centos 7.2
* Docker: 19.03.8
* Cuda driver: 10.2
* Docker Image: nvcr.io/nvidia/pytoch:19.06
* Backend: nccl
* Init method: "env://"

## Additional Text

I searched the document and found that the `timeout` parameter is restricted on "operations executed against the process group". What is the exact meaning of this? Does it include operations like initial socket connection establishment?

Thank you in advance.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by zhaojuanmao** [comment]
@worsecoder the timeout does not include initial socket connection establishment. After initializing process group, the time out will be applied to NCCL collective APIs such as all reduce as etc. 

For your need, do you want to try to use torchelastic for failure handling?

**Comment by worsecoder** [comment]
Thank you for your advice! I will have a look and try
