### ISSUE TITLE
CUDA not found when using latest pre-built version (Libtorch 1.5.1  - CUDA 10.1 - Cudnn7.6.4 - VS2017)

### ISSUE THREAD

**Issue by zirid** [pytorch/pytorch#41664]
## 🐛 Bug

I Can't load GPU  when using the latest prebuilt version  Libtorch 1.5.1 with CUDA 10.1 in VS2017

Thank you in advance.

![LibTorch](https://user-images.githubusercontent.com/31682698/87914275-5e633600-caab-11ea-8213-0c0a6c0edcd6.JPG)

## To Reproduce

1) download the latest version of Libtorch  1.5.1 width CUDA 10.1
2)Link in VS 2017
3) Run this test program

`#include <iostream>
#include <memory>
#include<torch/torch.h>
#include<torch/script.h>
#include<torch/cuda.h>
int main(int argc, const char* argv[]) {
	try {
		std::cout << "CUDA:   " << torch::cuda::is_available() << std::endl;
		std::cout << "CUDNN:  " << torch::cuda::cudnn_is_available() << std::endl;
		std::cout << "GPU(s): " << torch::cuda::device_count() << std::endl;
	}
	catch (std::exception& ex) {
		std::cout << ex.what() << std::endl;
	}
}`

Output is :

CUDA:   0
CUDNN:  0
GPU(s): 0

## Expected behavior

Detect GPU card  (RTX2070)

## Environment

 - Libtorch Version:  1.5.1
 - OS (e.g., Linux):  Win10
 - How you installed  Libtorch:  Prebuilt version for windows
 - CUDA/cuDNN version:  CUDA 10.1 / cudnn 7.6.4
 - GPU models and configuration:  RTX2070
 - Any other relevant information:  VS2017 - version 15.9.11

**Comment by peterjc123** [comment]
Please add an linker option `-INCLUDE:?warp_size@cuda@at@@YAHXZ`.
