### ISSUE TITLE
PyTorch _jit_pass_lower_graph fails on FasterRCNN model

### ISSUE THREAD

**Issue by hovhanns** [pytorch/pytorch#41674]
## 🐛 Bug

I'm trying to get the lower graph for torchvision.models.detection.fasterrcnn_resnet50_fpn pre-trained model but getting the following output

temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="_has_warned"](%self, %6)

## To Reproduce

_Run the following part of code_

```
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()
example = torch.randn(1, 3, 1000, 1000)
scripted_model = torch.jit.script(model)
graph, params = torch._C._jit_pass_lower_graph(scripted_model.forward.graph, scripted_model._c)
```

## Expected behavior

Need to have the output graph and corresponding parameters without having an exception.

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: version 3.16.3

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

cc @gmagogsfm @BowenBao @neginraoof @suo

**Comment by suo** [comment]
Thanks for the report! Can you explain what you are trying to accomplish? `_jit_pass_lower_graph` is internal-only so I'm not sure how you tripped this.

**Comment by hovhanns** [comment]
Thanks for your response @suo, I have faced this issue running CoreMLTools, which is using this function.
https://github.com/apple/coremltools/blob/f306f420b7194ff7b771176816eeeba88ebc3c67/coremltools/converters/mil/frontend/torch/converter.py#L328
I reproduced it using only PyTorch to make sure that this also throws an error here too.

**Comment by vadimkantorov** [comment]
Same issue in https://github.com/pytorch/fairseq/issues/2468 and in https://github.com/pytorch/fairseq/issues/2235#issuecomment-672752922

Some fairseq functions like to modify module attributes inside `forward` for some caching. And graph lowering does not like that.

Graph lowering is a mandatory stage during ONNX export: https://github.com/pytorch/pytorch/blob/a6c8730045bc19ec94ed8b15bfabc69d17b3c4f7/torch/onnx/utils.py#L362

**Comment by suo** [comment]
Hey, sorry for the late response here. The ONNX exporter—and the CoreML exporter, which is based on the ONNX exporter—does not handle modification of module attributes within a forward graph, because ONNX does not support doing that operation (not sure whether CoreML does, but I'm guessing it doesn't either).

**Comment by notsimon** [comment]
Hi there,
I came across the same issue while testing out CoreML, but this time on `nn.LSTM`. I'm not sure I understand what you meant @suo.

As I said, I'm going through `coremltools.convert` but it ends up calling `_jit_pass_lower_graph`:
```
model = torch.nn.LSTM(3, 3)
scripted_model = torch.jit.script(model)
torch._C._jit_pass_lower_graph(scripted_model.forward.graph, scripted_model._c)
```

Full error:
```
coremltools/coremltools/converters/_converters_entry.py:184: in convert
    **kwargs
coremltools/coremltools/converters/mil/converter.py:129: in mil_convert
    ConverterRegistry, **kwargs)
coremltools/coremltools/converters/mil/converter.py:171: in mil_convert_to_proto
    prog = frontend_converter(model, **kwargs)
coremltools/coremltools/converters/mil/converter.py:85: in __call__
    return load(*args, **kwargs)
coremltools/coremltools/converters/mil/frontend/torch/load.py:69: in load
    converter = TorchConverter(torchscript, inputs, outputs, cut_at_symbols)
coremltools/coremltools/converters/mil/frontend/torch/converter.py:144: in __init__
    raw_graph, params_dict = self._expand_and_optimize_ir(self.torchscript)
coremltools/coremltools/converters/mil/frontend/torch/converter.py:262: in _expand_and_optimize_ir
    torchscript.forward.graph, torchscript._c
/home/vagrant/.local/lib/python3.6/site-packages/torch/jit/_script.py:558: in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
/home/vagrant/.local/lib/python3.6/site-packages/torch/jit/_script.py:288: in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = RecursiveScriptModule(original_name=LSTM), name = 'forward'

    def __getattr__(self, name: str) -> Union[Tensor, 'Module']:
        if '_parameters' in self.__dict__:
            _parameters = self.__dict__['_parameters']
            if name in _parameters:
                return _parameters[name]
        if '_buffers' in self.__dict__:
            _buffers = self.__dict__['_buffers']
            if name in _buffers:
                return _buffers[name]
        if '_modules' in self.__dict__:
            modules = self.__dict__['_modules']
            if name in modules:
                return modules[name]
        raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
>           type(self).__name__, name))
E       torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'forward'
```

**Comment by letian-jiang** [comment]
Thanks for your advice @suo. Is there any plan to support `prim::SetAttr` in the near future?

**Comment by gmagogsfm** [comment]
> Thanks for your advice @suo. Is there any plan to support lowering `prim::SetAttr` in the near future?

Added ONNX label to involve the experts. @suo and I do not work on ONNX exporter directly.

**Comment by BowenBao** [comment]
Hi @hovhanns ,

We’ve gone ahead and closed this issue because it has been resolved elsewhere. This original failing snippet can be seen in [PyTorch unittest](https://github.com/pytorch/pytorch/blob/2205f56f462fb9cbb1c068acc1cf29aca27aef0a/test/onnx/test_models_onnxruntime.py#L208) and is passing.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
