### ISSUE TITLE
Getting different eigenvalues between using numpy.linalg.eigh() and torch.symeig()

### ISSUE THREAD

**Issue by leockl** [pytorch/pytorch#41688]
## 🐛 Bug

I am trying to understand why am I getting different eigenvalues between using `numpy.linalg.eigh()` and `torch.symeig()`.

## To Reproduce

An example is as below.

Code:
```
import numpy as np
import torch

arr_symmetric = np.array([[1.,2,3], [2,5,6], [3,6,9]])
arr_symmetric, arr_symmetric.dtype
```
**Output:**
```
(array([[1., 2., 3.],
        [2., 5., 6.],
        [3., 6., 9.]]), dtype('float64'))
```
Code:
```
tsr_symmetric = torch.tensor(arr_symmetric)
tsr_symmetric
```
**Output:**
```
tensor([[1., 2., 3.],
        [2., 5., 6.],
        [3., 6., 9.]], dtype=torch.float64)
```
Code:
```
w, v = np.linalg.eigh(arr_symmetric)
w, v
```
**Output:**
```
(array([4.05517871e-16, 6.99264746e-01, 1.43007353e+01]),
 array([[-9.48683298e-01,  1.77819106e-01, -2.61496397e-01],
        [ 2.22044605e-16, -8.26924214e-01, -5.62313386e-01],
        [ 3.16227766e-01,  5.33457318e-01, -7.84489190e-01]]))
```
Code:
```
e, v = torch.symeig(tsr_symmetric, eigenvectors=True)
e, v
```
**Output:**
```
(tensor([-2.6047e-16,  6.9926e-01,  1.4301e+01], dtype=torch.float64),
 tensor([[ 9.4868e-01, -1.7782e-01,  2.6150e-01],
         [ 8.6389e-16,  8.2692e-01,  5.6231e-01],
         [-3.1623e-01, -5.3346e-01,  7.8449e-01]], dtype=torch.float64))
```

As you can see one of the eigenvalues is different, ie. `4.05517871e-16` vs. `-2.6047e-16`

## Expected behavior

We can see that these 2 eigenvalues are really very small and it's close to zero. So numerically it doesn't matter. What concerns me is that one eigenvalue has a +ve value and the other has a -ve value. This affects an algorithm that I am working on which groups the corresponding eigenvectors based on the +ve or -ve eigenvalues.

Would be nice if the calculations for `torch.symeig()` are implemented in the same way as `numpy.linalg.eigh()`, where numpy being the more commonly used library, so there is some consistency between these 2 functions which are used specifically for symmetric matrices.

## Environment

Collecting environment information...
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.1+cu101
[conda] Could not collect

## Additional context

The +ve/-ve sign discrepancy doesn't seem to happen with `numpy.linalg.eig()` and `torch.eig()`, ie. the +ve/-ve eigenvalue signs are the same/consistent between `numpy.linalg.eigh()` and `numpy.linalg.eig()` and `torch.eig()`. Would be great if we could change `torch.symeig()` to be the same too, since `torch.symeig()` is written specifically for symmetric matrices, mirroring `numpy.linalg.eigh()`.

cc @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by vishwakftw** [comment]
That final value is just too close to zero, I wouldn't read into it for practical purposes. The other values that are larger are the same.

I believe this is not an actual issue.

**Comment by leockl** [comment]
Thanks @vishwakftw.

The +ve/-ve eigenvalues affects an algorithm that I am working on which groups the corresponding eigenvectors based on the +ve or -ve eigenvalues, regardless of the numerical value.

Given that the +ve/-ve eigenvalues are consistent between `numpy.linalg.eigh()`, `numpy.linalg.eig()` and `torch.eig()`, it would make sense to also have `torch.symeig()` to be the same too, so that there are all consistent across the board.

**Comment by vishwakftw** [comment]
I think you should clamp those values to 0, which also makes sense since the matrix is not invertible (the first row and the last row are merely multiples of each other). I would suggest you use a clamp on top of this, to eliminate the smallest eigenvalues below a tolerance.

**Comment by leockl** [comment]
Thanks @vishwakftw.

Yeah, I guess I could do that on my end by "clamping" any eigenvalues which are very very close to 0 to be 0 in my estimator/algorithm. 

This though won't fix the issue as I am sure this question would come up again in the future by others. Would be helpful, if a note can be left in the documentation that the eigenvalue signs from `torch.symeig()` for eigenvalues very very close to 0 could be different to `numpy.linalg.eig()`, `numpy.linalg.eigh()` and `torch.eig()`

I guess the important thing here is to have some consistency with the eigenvalues for all the functions calculating this.

**Comment by vishwakftw** [comment]
Hi @leockl, sure I think adding a note would be fine, but I think this is not really an issue with PyTorch, but rather based on the initialization of the procedure `syevd` (for `torch.symeig`), `geev` (for `torch.eig`)  used internally.

**Comment by leockl** [comment]
Thanks @vishwakftw.

From my other post [here](https://github.com/pytorch/pytorch/issues/9382), I understand there is a numpy compatibility work being done by @mruberry.

Would it be possible to put this up for consideration in the numpy compatibility work too?

**Comment by mruberry** [comment]
@leockl yes! You can request torch.linalg.eigh, analogous to NumPy's numpy.linalg.eigh, on this rollup issue for now: https://github.com/pytorch/pytorch/issues/38349.

**Comment by leockl** [comment]
That's great, many thanks @mruberry.

**Comment by mruberry** [comment]
We have added torch.linalg.eigh and I believe it address this issue. When I run the above here's what I see for eigenvalues:

```
# NumPy
[2.77614837e-15 6.99264746e-01 1.43007353e+01]
# torch.symeig
tensor([-2.6047e-16,  6.9926e-01,  1.4301e+01], dtype=torch.float64)
# torch.linalg.eigh
tensor([2.7761e-15, 6.9926e-01, 1.4301e+01], dtype=torch.float64)
```

**Comment by mruberry** [comment]
Closing due to lack of response. @leockl, please let us know if we should reopen this.
