### ISSUE TITLE
Can the timesteps T in deep reinforcement learning be trained?

### ISSUE THREAD

**Issue by zoharli** [pytorch/pytorch#4168]
Recently I'm trying to implement a deep reinforcement learning project which require a variable timesteps.I want to train a network to output a parameter T,and use T as the length or timesteps of policy gradient method or DQN method,I wonder if that's implementable? I mean when we do back-propogate, can me back-propogate through timesteps T？

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
