### ISSUE TITLE
Replace blacklist/whitelist in aten/src/ATen/native/cudnn/Conv.cpp

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41700]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `aten/src/ATen/native/cudnn/Conv.cpp`. See issue #41443 for more information.

**Comment by muhdmud** [comment]
Hi,  I have worked on this a couple days ago #41627 
can i reuse the above or make a new pr

**Comment by SplitInfinity** [comment]
You can reuse the above. Please modify the PR to reference this issue so that the issue is closed automatically when the PR is merged.

**Comment by muhdmud** [comment]
i cannot seem to link the issue on the right side bar of the pr, is it due to some priviledge/permissions?

**Comment by SplitInfinity** [comment]
I linked it for you. The best way to link them is to include "Fixes #{issue number}" in your PR description.

**Comment by muhdmud** [comment]
Oh i see, noted and thanks for that! I will try on other PRs now
