### ISSUE TITLE
Replace blacklist/whitelist in test/test_mobile_optimizer.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41718]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `test/test_mobile_optimizer.py`. See issue #41443 for more information.

**Comment by SplitInfinity** [comment]
cc: @kosuruvarunkumar

**Comment by sans-23** [comment]
I would like to work on this issue. Can I ?

**Comment by SplitInfinity** [comment]
There is already an approved open pull request that is in the process of being merged. This issue does not need further contribution.

**Comment by SplitInfinity** [comment]
Fixed by #45512.
