### ISSUE TITLE
Replace blacklist/whitelist in tools/pyi/gen_pyi.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41722]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `tools/pyi/gen_pyi.py`. See issue #41443 for more information.

**Comment by subedigaurav** [comment]
Hello, @SplitInfinity , can I work on this?

**Comment by SplitInfinity** [comment]
@subedigaurav Sure.
