### ISSUE TITLE
Replace blacklist/whitelist in torch/utils/mobile_optimizer.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41728]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/utils/mobile_optimizer.py`. See issue #41443 for more information.

**Comment by SplitInfinity** [comment]
cc: @kosuruvarunkumar

**Comment by anisha98** [comment]
I would like to work on this issue.

**Comment by SplitInfinity** [comment]
Fixed by #42046.
