### ISSUE TITLE
[Feature Request] Capsule Layer 

### ISSUE THREAD

**Issue by prateekmalhotra** [pytorch/pytorch#4172]
CapsNet [(airxiv)](https://arxiv.org/abs/1710.09829) defines a Capsule Layer (primary or secondary) which outputs activity vectors representing instantiation parameters of a specific entity. Routing by agreement will be used, as mentioned in the paper, to pass information from one capsule layer to the next.

Is this worth a PR?

**Comment by apaszke** [comment]
If it proves to be useful in a few more papers then yes, but let's wait until then.
