### ISSUE TITLE
Replace blacklist/whitelist in CMakeLists.txt

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41739]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `CMakeLists.txt`. See issue #41443 for more information.

**Comment by Huzaib** [comment]
Is someone working on this?
And what exactly is to be done?

**Comment by SplitInfinity** [comment]
There is already a pull request open for this issue.

**Comment by ssooffiiaannee** [comment]
I would like to work on this one.

**Comment by SplitInfinity** [comment]
There is already a pull request open for this.
