### ISSUE TITLE
Replace blacklist/whitelist in aten/src/ATen/gen.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41742]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `aten/src/ATen/gen.py`. See issue #41443 for more information.

**Comment by priyanshuwustl** [comment]
Picking up this issue

**Comment by SplitInfinity** [comment]
It turns out this particular instance is in a file that export command line flags with blacklist/whitelist in the name. That means we need to fix all references to it in the codebase and in internal fbcode targets as well.
