### ISSUE TITLE
Replace blacklist/whitelist in tools/clang_format_all.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41752]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `tools/clang_format_all.py`. See issue #41443 for more information.

**Comment by SplitInfinity** [comment]
cc: @superkirill

**Comment by REX51** [comment]
@SplitInfinity is it okay if I change the 'whitelisted' word to 'allowlisted' ?

**Comment by SplitInfinity** [comment]
Sure. The author of the existing PR does not seem to be working on it anymore.

**Comment by REX51** [comment]
Okay cool.
