### ISSUE TITLE
Replace blacklist/whitelist in tools/code_analyzer/gen_op_registration_whitelist.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41754]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `tools/code_analyzer/gen_op_registration_whitelist.py`. See issue #41443 for more information.

**Comment by kalmufti** [comment]
I'm working on this issue.

**Comment by Vishal487** [comment]
Hi, I am working on it

**Comment by Vishal487** [comment]
Do you want to replace **whitelist** from filename too or only occurences of **whitelist** inside the file?

**Comment by Vishal487** [comment]
@SplitInfinity my all checks are passed.
see it here [https://github.com/pytorch/pytorch/pull/45260](url)
