### ISSUE TITLE
segmentation fault in `torch.orgqr` when input size has element 0

### ISSUE THREAD

**Issue by leeyeetonn** [pytorch/pytorch#41768]
## 🐛 Bug
`torch.orgqr` has segmentation fault when one of the input has size containing 0.

## To Reproduce
```python
import torch
import numpy as np

input = torch.tensor(np.random.rand(2,2))
input2 = torch.tensor(np.random.rand(2,0))

torch.orgqr(input, input2)
```
The above code snippet causes
> Segmentation fault (core dumped)

## Expected behavior
Should not have segmentation fault.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch
## Additional context

cc @ezyang @gchanan @zou3519 @mruberry @rgommers @vincentqb @vishwakftw @jianyuh @nikitaved @pearu

**Comment by ezyang** [comment]
cc @v0dro

**Comment by v0dro** [comment]
I can take this up.

**Comment by toshas** [comment]
Check out my latest package with a drop-in replacement for `torch.orgqr`: https://github.com/toshas/torch-householder
