### ISSUE TITLE
Replace blacklist/whitelist in torch/quantization/_numeric_suite.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41762]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/quantization/_numeric_suite.py`. See issue #41443 for more information.

**Comment by ytobi** [comment]
I like to work on this.

**Comment by SplitInfinity** [comment]
@ytobi There are already open pull requests for this.

**Comment by SplitInfinity** [comment]
Closed by #41756.
