### ISSUE TITLE
torch.nn.functional.avg_pool2d has floating point exception when stride is 0

### ISSUE THREAD

**Issue by leeyeetonn** [pytorch/pytorch#41767]
## 🐛 Bug

`torch.nn.functional.avg_pool2d` has floating point exception when `stride = 0`
## To Reproduce

```python
import numpy as np
import torch

input = torch.tensor(np.random.rand(10, 3, 20, 20))
kernel_size = 4
torch.nn.functional.avg_pool2d(input, kernel_size, stride=0)
```
The above code snippet will result in:

> Floating point exception (core dumped)

## Expected behavior
Should not have floating point exception.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by zhangguanheng66** [comment]
@fmassa is this behavior expected?

**Comment by xwang233** [comment]
@ngimel For `torch.nn.AvgPool2d` module, this line

https://github.com/pytorch/pytorch/blob/6b50874cb70f27020b88d16ce8e7fc6a186549ee/torch/nn/modules/pooling.py#L587-L591

(un)fortunately sets `self.stride` to `kernel_size` silently when `stride = 0`. Do you want that to be fixed as well?

**Comment by ngimel** [comment]
We should distinguish between stride not set (default value of stride is kernel_size, according to the docs) and stride explicitly set to 0 (invalid input).
