### ISSUE TITLE
Replace blacklist/whitelist in torch/quantization/quantize.py

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#41764]
The goal of this issue is to replace all instances of *whitelist* and *blacklist* in `torch/quantization/quantize.py`. See issue #41443 for more information.

**Comment by nditanaka** [comment]
Is this issue still open?

**Comment by SplitInfinity** [comment]
@nditanaka As you can see, there are already open pull requests for this.

**Comment by 0tist** [comment]
Hi, I wish to contribute to this issue, Is someone working on this?

**Comment by SplitInfinity** [comment]
Closed by #41756.
