### ISSUE TITLE
torch.orgqr aborts and core dump

### ISSUE THREAD

**Issue by leeyeetonn** [pytorch/pytorch#41776]
## 🐛 Bug
`torch.orgqr` aborts and core dump when inputs are having some random dimensions. It seems there's a lack of input validity check and proper memory management.

## To Reproduce
```python
import torch
import numpy as np

input = torch.tensor(np.random.rand(14,7))
input2 = torch.tensor(np.random.rand(12,6))
torch.orgqr(input, input2)
```
Run the above code snippet multiple times could get different errors.
> free(): invalid size
Aborted (core dumped)

> malloc(): memory corruption
Aborted (core dumped)

Changing the dimensions slightly could also get other errors:
```python
import torch
import numpy as np

input = torch.tensor(np.random.rand(14,7))
input2 = torch.tensor(np.random.rand(12,16)) # changed here
torch.orgqr(input, input2)
```
> corrupted size vs. prev_size
Aborted (core dumped)

Using different numbers as dimensions could cause other errors, such as:
> double free or corruption (out)

> malloc_consolidate(): invalid chunk size

> corrupted double-linked list

It seems the memory management is not done properly.

## Expected behavior
Should not abort and core dump.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @mruberry @rgommers

**Comment by albanD** [comment]
Hi,

I saw that you open a few issue for segfault, thanks a lot!
Out of curiosity, how did you found all of these?

**Comment by leeyeetonn** [comment]
@albanD Thanks for your interest! We are building a testing tool for DL libraries. These are some of the problems we’ve discovered and found them likely to be of interest to the developers.

**Comment by albanD** [comment]
That's very interesting indeed! We don't usually see that many reports of segfault, so I was afraid we did something wrong haha.

We are actively looking for better ways to cover all use cases of our functions (cc @mruberry ) in testing to try and catch such issues. Don't hesitate to open an issue or directly reach out on slack if you need feature to make your tool better or have specific questions!

**Comment by ezyang** [comment]
@leeyeetonn I'd be interested to know what kind of testing strategy you're doing for your tool

**Comment by leeyeetonn** [comment]
@ezyang Thanks for your interest! Our tool is a Fuzzing-based technique for the API functions. It’s still a work-in-progress. We’d love to share more details once it’s ready!

**Comment by kurtamohler** [comment]
Unassigning myself because I think this issue requires someone who know a bit more about Lapack and orgqr.

As far as I could tell, it seemed like the root cause of the error was coming from the `dorgqr_` and `sorgqr_` Lapack functions themselves in `THLapack_(orgqr)` in `aten/src/TH/generic/THLapack.cpp`. When I comment those functions out (or if I comment out the second `THLapack_(orgqr)` call in `THTensor_(orgqr)` in `aten/src/TH/generic/THTensorLapack.cpp`), leaving everything else the same, the error doesn't happen anymore.

So it doesn't _seem_ to me that memory management is the issue. Seems more likely that input validity is the problem, and I don't know what the valid inputs are supposed to be.

**Comment by mattip** [comment]
The low-level call is [orgqr](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/scalapack-routines/scalapack-computational-routines/orthogonal-factorizations-scalapack-computational-routines/p-orgqr.html) or [dorgqr](http://www.math.utah.edu/software/lapack/lapack-d/dorgqr.html). It is documented as accepting `m`,`n`,`k` where `m, n = ra.shape`, and `k = tau.shape[0]`. When called "normally" as a chained function from the output of `geqrf`, i.e., `Q = torch.orgqr(torch.geqrf(input))`, `n == k` which is what the [code does](https://github.com/pytorch/pytorch/blob/v1.6.0/aten/src/TH/generic/THTensorLapack.cpp#L425). But it should be using `n` directly and also should be checking the conditions `m≥ n`,  `n ≥ k` (which would fail the call of the original report).

I couldn't find explicit tests for `orgqr`, maybe they are generated?

**Comment by mattip** [comment]
While fuzzing this function does expose a problem, in real-world usage the two inputs are tightly coupled in order for the output to have any meaning.

**Comment by kurtamohler** [comment]
Thanks for the help @mattip! I'll go ahead and apply these input conditions.
