### ISSUE TITLE
[JIT] Support partially specified sizes/strides in IRParser

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#41773]
## 🚀 Feature
Currently IRParser only supports types where all sizes/strides are known or none of them is known. E.g. the following types are supported:
```
Float(10, 20)
Float(*, *)
```
But the following type currently can not be parsed:
```
Float(10, *)
```

Technically it is possible to have such type, and hence IRParser should be able to parse it too.

## Test Case
```
import torch
test =  '''
    graph(%x : Float(20, *)):
        return (%x)
'''
graph = torch._C.parse_ir(test)
```

Currently it fails with the following error message:
```
RuntimeError: expected number but found '*' here:
        graph(%x : Float(20, *)):
                             ~ <--- HERE
            return (%x)
```

## Implementation pointers
#41507 could be used as an example of a IRParser change.

cc @suo @gmagogsfm

**Comment by Lilyjjo** [comment]
Is it also valid to mix strided dimensions with un-sized dimensions? For example, would `Float(10:10, *)` be valid?

**Comment by ZolotukhinM** [comment]
I think it is possible in theory, but my guess is that it never happens in practice. So, probably not a big deal if we don't support this case.

**Comment by Lilyjjo** [comment]
Is it possible to have a type where there are no sizes specified? For example, would `Float(requires_grad=true)` or `Float()` be valid?

**Comment by ZolotukhinM** [comment]
Yes, it is possible to have the rank unspecified. In this case, the tensor type would appear as `FloatTensor`, while `Float()` actually corresponds to 0-dim tensor.

You could experiment with various tensor types by manually creating and printing them out (like https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/jit_type.h#L591-L613). The TensorType constructors are defined here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/jit_type.h#L591-L613

**Comment by Lilyjjo** [comment]
> Yes, it is possible to have the rank unspecified. In this case, the tensor type would appear as `FloatTensor`, while `Float()` actually corresponds to 0-dim tensor.
> 
> You could experiment with various tensor types by manually creating and printing them out (like https://gist.github.com/ZolotukhinM/9a0c352cb3eda4d1af10a698e9307e57). The TensorType constructors are defined here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/jit_type.h#L591-L613

Oh, awesome, I was wondering how to test the code :) 
I'll add some test cases there are verify that my code changes still work. I made an initial pull req, but I think I need to update it to treat the empty case correctly, so maybe hold off from looking at it
