### ISSUE TITLE
Implementing broadcast_to

### ISSUE THREAD

**Issue by aayn** [pytorch/pytorch#41786]
Since [broadcast_to](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html) is very different from my previous contributions, it probably has the greatest learning value. So that's what I'll do.

From #38349.

cc: @mruberry

**Comment by kshitij12345** [comment]
@aayn @mruberry 

Wouldn't this be an alias to [expand](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand)

**Comment by mruberry** [comment]
> @aayn @mruberry
> 
> Wouldn't this be an alias to [expand](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand)

Aha! You're right @kshitij12345, sorry about that @aayn and thank you for catching that, @kshitij12345, I had it marked on my spreadsheet incorrectly. Let me remove it from the rollup and mark it as just needing an alias.

**Comment by aayn** [comment]
Yeah, that's right. No worries!

**Comment by mruberry** [comment]
> Yeah, that's right. No worries!

Let me know if you'd like some more REAL suggestions ;)

**Comment by aayn** [comment]
I was just thin

> > Yeah, that's right. No worries!
> 
> Let me know if you'd like some more REAL suggestions ;)

I was just thinking of asking you for suggestions.

**Comment by mruberry** [comment]
If you want something different and tricky there's [digitize](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html?highlight=digitize#numpy.digitize), which is a little like [torch.bincount](https://pytorch.org/docs/master/generated/torch.bincount.html?highlight=bin#torch.bincount). 

If you want something straightforward there's still [divmod](https://numpy.org/doc/stable/reference/generated/numpy.divmod.html?highlight=divmod#numpy.divmod) and functions like [ldexp](https://numpy.org/doc/stable/reference/generated/numpy.ldexp.html?highlight=ldexp#numpy.ldexp).

There was also a [recent request](https://github.com/pytorch/pytorch/issues/38349#issuecomment-660342641) for [packbits](https://numpy.org/doc/stable/reference/generated/numpy.packbits.html?highlight=packbits#numpy.packbits).

Any of those interesting? If not, maybe you could tell me what you're interested in and I'll find an appropriate function?

**Comment by aayn** [comment]
I think [digitize](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html?highlight=digitize#numpy.digitize) sounds interesting. I'd like to work on that. It also shouldn't be too daunting since PyTorch already has [searchsorted](https://pytorch.org/docs/master/generated/torch.searchsorted.html). Thanks!

**Comment by mruberry** [comment]
> I think [digitize](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html?highlight=digitize#numpy.digitize) sounds interesting. I'd like to work on that. It also shouldn't be too daunting since PyTorch already has [searchsorted](https://pytorch.org/docs/master/generated/torch.searchsorted.html). Thanks!

And I misdirected you again! Sorry @aayn, we've been very unlucky with these picks, and everytime I scrutinize our current opset a new one pops up!

I'll try not to include existing functions, of course, but maybe one of those other functions is interesting?

**Comment by aayn** [comment]
It's okay! I thought packbits was also interesting, but isn't @vadimkantorov working on it? I'll take that up if he isn't, else I'll work on divmod. @mruberry

**Comment by aayn** [comment]
I could even do left/right shift (#41624) if that's still available.

**Comment by vadimkantorov** [comment]
I don’t work on packbits either :) so if you wish to work on it - go for it!

**Comment by mruberry** [comment]
> It's okay! I thought packbits was also interesting, but isn't @vadimkantorov working on it? I'll take that up if he isn't, else I'll work on divmod. @mruberry

I think packbits would be really interesting. Thanks for being so flexible, @aayn!
