### ISSUE TITLE
Provide a small CPU-only pip package for CI testing

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#4178]
My team is blocked on upgrading 0.2 -> 0.3 due to inability to `pip install` PyTorch's 0.6GB package on travis-ci.org. Would it be possible to provide a small CPU-only package to facilitate CI testing of packages based on PyTorch? (Most CI services do not have GPUs.)

**Comment by fritzo** [comment]
CC @soumith who suggested this on slack.

**Comment by neerajprad** [comment]
@soumith, @apaszke - It will be nice if the build script is available. We would like to build a PyTorch wheel by pinning the master branch to a certain commit, and using this for CI testing in Pyro. This will greatly help us migrate distributions, and test the integration on the Pyro side.

**Comment by soumith** [comment]
@neerajprad build scripts are in repo:

https://github.com/pytorch/builder/tree/master/conda - both
https://github.com/pytorch/builder/tree/master/manywheel - wheel Linux
https://github.com/pytorch/builder/tree/master/wheel - wheel OSX

I will provide a script for CPU-only builds and have CPU-only binaries soon

**Comment by neerajprad** [comment]
I tried to create the wheels for Ubuntu, and wanted to follow up. For our purposes, we do not need a manylinux wheel that works across multiple linux distros (which is otherwise useful, and for uploading to pypi). I was able to easily create one ~ 45 MB for `linux_x86_64` which is what we need for CI testing on ubuntu machines. I am now trying to figure out where to host it with public read permissions so that CI machines have access to this, and do not need to build PyTorch from source. I wanted to check if you have nightly/weekly PyTorch builds available that we could download for CI testing, instead?  cc. @ezyang.

**Comment by ezyang** [comment]
Yes, we've got this on our list of things to do for our CI system. One minor issue to resolve is where to put all the nightly binaries; it seems best if we never delete them.

**Comment by neerajprad** [comment]
@ezyang - I suppose there is little value in hosting old nightly binaries (beyond  1-2 weeks). Maybe you could have additional binaries hosted for major feature additions. If occasionally one needs to build an older version, they could build it from source. 

> One minor issue to resolve is where to put all the nightly binaries

I suppose we could use Amazon S3 to host it? That's what I was planning to do.

**Comment by rachtsingh** [comment]
Any luck on this?

**Comment by soumith** [comment]
sorry for the delay, i'll have official CPU-only packages out later today.

**Comment by soumith** [comment]
now http://pytorch.org has CPU-only wheels when CUDA=None is selected in the wizard.
The wheels are 45MB each and include statically linked MKL.

<img width="963" alt="screen shot 2018-01-10 at 2 24 20 pm" src="https://user-images.githubusercontent.com/1310570/34791114-fb9abf54-f611-11e7-88b8-04dde48f4575.png">

**Comment by neerajprad** [comment]
@soumith - Thanks a bunch! Is it possible to get the build scripts for the CPU wheel too?

**Comment by soumith** [comment]
@neerajprad 
checked in via https://github.com/pytorch/builder/commit/f01c39a60ebc0059d766ccd6700958590f21d6c5
