### ISSUE TITLE
segfault in torch.nn.functional.embedding

### ISSUE THREAD

**Issue by leeyeetonn** [pytorch/pytorch#41780]
## 🐛 Bug
Could trigger a segfault in `torch.nn.functional.embedding` when the `weight` parameter is not a matrix, but e.g., a scalar tensor.

## To Reproduce
```python
import torch
import numpy as np

input = torch.tensor((np.random.rand(2,2)*100).astype('int64'))
weight = torch.tensor(1)
torch.nn.functional.embedding(input, weight)
```
the code snippet above would trigger a segfault.

## Expected behavior
Should not have a segmentation fault.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.0                py37_cu101    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by yku12cn** [comment]
Wondering about what use case is this.
torch.nn focus on neural network, which essentially is matrix based calculation.
A lot sub-module using torch.nn will assume all parameters are presented as a matrix or at least a vector.

So, why would you using torch.tensor(1) instead of torch.tensor([1])?

If you are trying to pass a variable with no specific dimension to torch.tensor, I would suggest you to do a quick data check and pre-process before passing it into torch.tensor().

**Comment by leeyeetonn** [comment]
@yku12cn Thanks for the comment. I agree with the assumption the input should be at least a matrix or a vector, but it seems to me it would be a good idea for PyTorch to have an input validation against such a case to avoid a Segmentation Fault. After all, a Segmentation Fault is certainly not good and not informative to the user what went wrong.

Other functions in `torch.nn` seem to have implemented such input validity check: e.g., `torch.nn.functional.conv1d` would throw an exception "RuntimeError: weight should have at least three dimensions" when `torch.tensor(1)` is given as `weight`.

**Comment by zhangguanheng66** [comment]
Again, what's the usage case for this request?

**Comment by yku12cn** [comment]
> Again, what's the usage case for this request?

@zhangguanheng66  I think he is simply unhappy about the type of error when it crashes.

**Comment by albanD** [comment]
Whatever the use case is, a segfault is never ok and we should fix it with high priority.
