### ISSUE TITLE
RuntimeError: tensors.size() > 0 INTERNAL ASSERT FAILED at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:672, please report a bug to PyTorch. (compute_bucket_assignment_by_size at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:672)

### ISSUE THREAD

**Issue by tuoniaoren** [pytorch/pytorch#41790]
when i want to combine DDP with Model Parallelism, i meet this question.  in the net, i use Parameters to bulid the linear net, such as 
```
class net(nn.Module):
self.weight1 = Parameter(torch.FloatTensor(out_features, in_features)).to(0)
self.weight2 = Parameter(torch.FloatTensor(out_features, in_features)).to(1)

main():
    DDP(net)
```
How to solve this problem？
i use pytorch 1.2

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @ezyang @bhosmer @smessmer @ljk53

**Comment by ezyang** [comment]
I don't think this question is fully formed, and even if it was, PyTorch 1.2 is too old. Please try upgrading first.
