### ISSUE TITLE
Feature Request: Support torch.autograd.grad() in optimizers

### ISSUE THREAD

**Issue by fritzo** [pytorch/pytorch#4179]
My team is trying to use `torch.autograd.grad(...)` with torch optimizers, but optimizers only consume `.grad` properties, not arbitrary lists of gradients. To work around this, we manually set `.grad` properties from stuff we compute with `grad(...)`.

Could optimizers add first-class support for lists of gradients? @soumith [suggests](https://discuss.pytorch.org/t/using-optimizers-with-torch-autograd-grad/11078) that
>  optimizers should take an optional `grads` argument, either in step or at construction time

cc @ezyang @SsnL @albanD @zou3519 @gqchen @vincentqb

**Comment by apaszke** [comment]
Adding grads to step sounds reasonable. You can't do that at construction time, because `torch.autograd.grad` will produce new values every time you call it.

**Comment by albanD** [comment]
Does adding a `grads` arguement to the step function sounds good @vincentqb  ?

**Comment by vincentqb** [comment]
> Does adding a `grads` argument to the step function sounds good @vincentqb ?

Yes, that's a good option. Another could be to pass a dictionary of parameters to be given to `torch.autograd.grad` in the constructor and to invoke `torch.autograd.grad` automatically in step, right?

@fritzo -- interested in opening a pull request for this?

**Comment by albanD** [comment]
This is being replaced by https://github.com/pytorch/pytorch/issues/45242 that adds a new functional API that takes the gradients as input directly.
Feel free to re-open if it does not cover all the use cases you were looking for here.
