### ISSUE TITLE
about op() function

### ISSUE THREAD

**Issue by moqingxinai** [pytorch/pytorch#41798]
https://github.com/pytorch/pytorch/blob/fe415589a964697a78186189bd4815541f853b47/torch/onnx/symbolic_opset9.py#L385
I want to know how does op() function implement？where is the definition？can someone help and tell me？Thanks your reply

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by bddppq** [comment]
https://github.com/pytorch/pytorch/blob/ea03f95/torch/onnx/utils.py#L979

**Comment by spandantiwari** [comment]
Thanks @bddppq .

**Comment by moqingxinai** [comment]
I see！Thank you very much！




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: bddppq  <notifications@github.com>
 

 
 发送时间: 2020-07-22 14:43:10
 

 
 收件人:pytorch/pytorch <pytorch@noreply.github.com> 

 
 抄送:xinhua2010 <xinhua2010@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [pytorch/pytorch] about op() function (#41798)
 





 https://github.com/pytorch/pytorch/blob/ea03f95/torch/onnx/utils.py#L979
