### ISSUE TITLE
Segfault when passing an empty input to torch.chain_matmul

### ISSUE THREAD

**Issue by mjkim720** [pytorch/pytorch#41817]
## 🐛 Bug

A segmentation fault occurs when passing an empty input to `torch.chain_matmul`

## To Reproduce

```python
import torch

torch.chain_matmul()
```

## Expected behavior

Seems other functions (e.g., `torch.broadcast_tensors()`) do handle an empty input without causing a segfault. I would expect the same for this function.

## Environment

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch

**Comment by mjkim720** [comment]
Could I get any feedback on this issue, please?

**Comment by kshitij12345** [comment]
@mjkim720 What would be the expected behaviour?

`broadcast_tensors()` returns tuple so empty tuple is fine. However `torch.chain_matmul` returns a Tensor (so I think throwing an error is more appropriate)

**Comment by mjkim720** [comment]
Thanks for the feedback. I understand your point, but I would expect an exception message saying something like an empty input is not acceptable rather than just throwing a segfault

**Comment by kshitij12345** [comment]
Sure. Would make PR doing that.
