### ISSUE TITLE
Some confusions about some ops and concepts

### ISSUE THREAD

**Issue by ddummkopfer** [pytorch/pytorch#41838]
Wonderful Deep Learning Framework.
Now i have some questions about some ops and concepts.

1. What do OpaqueTensorImpl, TensorImpl and StorageImpl mean under source code file c10/core?

2. What is to_dense() ? In official website, there is no explanation about the op to_dense().

 Thank you for your attention.

**Comment by ddummkopfer** [comment]
Another Question.
Does cuDNN support BF16 data type?

**Comment by izdeby** [comment]
@ddummkopfer, please use our [forum](https://discuss.pytorch.org/) for questions. thank you.
