### ISSUE TITLE
Error occurs when adding "max_unpool2d" to onnx

### ISSUE THREAD

**Issue by ArtyZe** [pytorch/pytorch#41833]
When I add max_unpool2d operator to symbolic_opset11.py like: 
```
@parse_args('v', 'v', 'is')
def max_unpool2d(g, self, indices, output_size):
    return g.op("max_unpool2d", self, indices, output_size)
```
I got this error while converting model Enet
![image](https://user-images.githubusercontent.com/32027268/88045755-9b99f780-cb81-11ea-8010-4c5db046779e.png)
Could you give me some advice to solve this problem? :(
```
Torch vision:  1.5.0, 1.0.0, neither is ok
onnx vision: 1.6.0
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
The symbolic function creates an ONNX node according to ONNX spec.
You'd need to check https://github.com/onnx/onnx/blob/master/docs/Operators.md#MaxUnpool
and specify node inputs and attributes accordingly.

**Comment by spandantiwari** [comment]
Thanks @neginraoof .
@ArtyZe - If you are adding a symbolic yourself, then it is hard to say. Otherwise, please attach a proper repro for any issue you see and we will take a look.

**Comment by ArtyZe** [comment]
@spandantiwari @neginraoof 
Thanks for your reply.
Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
that means torch/onnx does not recognize this op.
and I see that max_unpool2d is a torch op
![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
So, now 
1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx

**Comment by neginraoof** [comment]
Looks like export of this torch op is not supported yet.

**Comment by jce2090** [comment]
> @spandantiwari @neginraoof
> Thanks for your reply.
> Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
> ![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
> that means torch/onnx does not recognize this op.
> and I see that max_unpool2d is a torch op
> ![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
> so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
> So, now
> 
> 1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
> 2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx

hi, Did you solve this problem

**Comment by spandantiwari** [comment]
As @neginraoof mentioned, this op is not supported. If you can consider contributing a PR for this, that will be great.

**Comment by ArtyZe** [comment]
> > @spandantiwari @neginraoof
> > Thanks for your reply.
> > Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
> > ![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
> > that means torch/onnx does not recognize this op.
> > and I see that max_unpool2d is a torch op
> > ![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
> > so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
> > So, now
> > 
> > 1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
> > 2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx
> 
> hi, Did you solve this problem

Yes, Pytorch/onnx with verion 1.1.0 support "MaxUnpool", same as onnx. But kernel_shape for onnx/MaxUnpool is an attribute, which is input for Pytorch/onnx, so you need to convert onnx model exported by Pytorch/onnx to match onnx.

**Comment by bodhi-tree01** [comment]
> > > @spandantiwari @neginraoof
> > > Thanks for your reply.
> > > Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
> > > ![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
> > > that means torch/onnx does not recognize this op.
> > > and I see that max_unpool2d is a torch op
> > > ![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
> > > so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
> > > So, now
> > > 
> > > 1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
> > > 2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx
> > 
> > 
> > hi, Did you solve this problem
> 
> Yes, Pytorch/onnx with verion 1.1.0 support "MaxUnpool", same as onnx. But kernel_shape for onnx/MaxUnpool is an attribute, which is input for Pytorch/onnx, so you need to convert onnx model exported by Pytorch/onnx to match onnx.

Hello, did you mean to change the PyTorch version to 1.1.0 ?
I also met this problem, and I hope to get your reply, thanks.

**Comment by bodhi-tree01** [comment]
> > > @spandantiwari @neginraoof
> > > Thanks for your reply.
> > > Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
> > > ![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
> > > that means torch/onnx does not recognize this op.
> > > and I see that max_unpool2d is a torch op
> > > ![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
> > > so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
> > > So, now
> > > 
> > > 1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
> > > 2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx
> > 
> > 
> > hi, Did you solve this problem
> 
> Yes, Pytorch/onnx with verion 1.1.0 support "MaxUnpool", same as onnx. But kernel_shape for onnx/MaxUnpool is an attribute, which is input for Pytorch/onnx, so you need to convert onnx model exported by Pytorch/onnx to match onnx.

Hello, did you mean to change the PyTorch version to 1.1.0 ?
I want to convert ENet to an onnx file, I also met this problem, and I hope to get your reply, thanks.

**Comment by ArtyZe** [comment]
> > > > @spandantiwari @neginraoof
> > > > Thanks for your reply.
> > > > Actually, what drives me to add max_unpool op to torch/onnx/symbolic is as below:
> > > > ![image](https://user-images.githubusercontent.com/32027268/88515609-8cea8f00-d01e-11ea-823f-654f53ddd83f.png)
> > > > that means torch/onnx does not recognize this op.
> > > > and I see that max_unpool2d is a torch op
> > > > ![image](https://user-images.githubusercontent.com/32027268/88515891-fa96bb00-d01e-11ea-82fe-19b27abb9903.png)
> > > > so I try to add max_unpool2d to symbolic to support max_unpool2d in converting to onnx.
> > > > So, now
> > > > 
> > > > 1. Enet is ok to run in torch. link: https://github.com/davidtvs/PyTorch-ENet
> > > > 2. could you please tell me which version of torch can support max_unpool2d in converting torch model to onnx
> > > 
> > > 
> > > hi, Did you solve this problem
> > 
> > 
> > Yes, Pytorch/onnx with verion 1.1.0 support "MaxUnpool", same as onnx. But kernel_shape for onnx/MaxUnpool is an attribute, which is input for Pytorch/onnx, so you need to convert onnx model exported by Pytorch/onnx to match onnx.
> 
> Hello, did you mean to change the PyTorch version to 1.1.0 ?
> I want to convert ENet to an onnx file, I also met this problem, and I hope to get your reply, thanks.

right，only PyTorch 1.1.0 support “MaxUnpool” in PyTorch/onnx

**Comment by thiagocrepaldi** [comment]
Although [ONNX spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#maxunpool) supports max_unpool2d already, Pytorch ONNX exporter doesn't

Contributions are most welcome. If you are interested, you can use [Col2Im PR](https://github.com/pytorch/pytorch/pull/84594/files#diff-42f39e6f78dc2c8556dbd43ca3fdb689f151c67cd2b0ef3290d5c3dfef4e1511) as an example. All you have to do is adding the implementation code (similar to your suggestion) at `torch/onnx/symbolic_opset9.py` and at least one unit test

**Comment by thiagocrepaldi** [comment]
Closing this as stale.

As we are currently focusing on `torch.onnx.dynamo_export` API as the new ONNX exporter solution, we don't plan to support new features for the `torch.onnx.export` API.

However, we do consider reviewing and merging user contributions. I am closing this issue as not-planned, but please reopen if you come up with a PR for it
