### ISSUE TITLE
undefined symbol : at::cuda::blas::gemv in v-1.6.0

### ISSUE THREAD

**Issue by lbin** [pytorch/pytorch#41836]
## 🐛 Bug

Before 1.6.0, we used THCudaBlas_Sgemv was OK

**Comment by izdeby** [comment]
@lbin, can you please, provide a repro of an error? Please, reopen the issue once done

**Comment by lbin** [comment]
@izdeby https://github.com/lbin/DCNv2/blob/pytorch1.6/src/cuda/dcn_v2_cuda.cu#L327

**Comment by LordonCN** [comment]
> @izdeby https://github.com/lbin/DCNv2/blob/pytorch1.6/src/cuda/dcn_v2_cuda.cu#L327

this works : https://github.com/lbin/DCNv2/blob/c916fdf2ed69ebebc43cbe8a2cb5e7ce0dd71132/src/cuda/dcn_v2_cuda.cu#L327
