### ISSUE TITLE
Add tests to cover saving/loading DDP modules

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#41854]
Our DDP tutorial already saves/loads `ddp_model. state_dict()`, but we don't have test to cover this feature yet. Let's add some tests to make sure DDP states can be recovered properly.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
self-assigned to reserve for bootcamp

**Comment by mrshenli** [comment]
Some more details about this task. To add tests:

1. Go through [this DDP tutorial](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#save-and-load-checkpoints), especially the "Save and Load Checkpoints" section. For more information about DDP, please refer to [this doc](https://pytorch.org/tutorials/beginner/dist_overview.html#torch-nn-parallel-distributeddataparallel)

2. Add two test cases to `test_c10d.py`, which can be added to after the following test case. One test for CPU module and another test for GPU model. Each test will 1) create a ddp module, 2) run it for a few iterations, 3) save the DDP module, 4) zero out all params in the DDP module, 5) load the ddp module, 6) run it for a few more iterations and make sure the result will be the same with/without the save/load step. 

https://github.com/pytorch/pytorch/blob/4e4626a23d1cf8b2a3c87d2b5f2f63ccd14e44c3/test/distributed/test_c10d.py#L2841


3. Try the test locally:

```bash
pytest test/distributed/test_c10d.py -k your_test_name -vs
```

**Comment by bdhirsh** [comment]
closed through https://github.com/pytorch/pytorch/pull/44906
