### ISSUE TITLE
Pytorch installation 

### ISSUE THREAD

**Issue by geothan** [pytorch/pytorch#41853]
Hello,

i have a nvidia gpu 1650 and i want to use it for training.
I installed the last cuda version 11.2, following the below commands:

`
## Cuda toolkit
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget http://developer.download.nvidia.com/compute/cuda/11.0.2/local_installers/cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1804-11-0-local_11.0.2-450.51.05-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu1804-11-0-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda

## Set Variables
sudo nano /etc/profile.d/cuda.dh
export PATH=/usr/local/cuda-11.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}`

Also i installed the below python libraries through pip command:

`torch
tensorboardX
numpy
scipy
numba
tqdm
h5py
plyfile
six`

but when i execute the below command:

`print(torch.cuda.current_device())`

i get:

`>>> print(torch.cuda.current_device())
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 330, in current_device
    _lazy_init()
  File "/home/george/anaconda3/envs/pvcnn_env/lib/python3.8/site-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:47`

How can i fix this?

**Comment by ChuckTG** [comment]
I can see that have set an anaconda environment pvcnn_env. Since you use conda, in  the anaconda prompt, execute: 

`conda install pytorch torchvision -c pytorch`

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.
