### ISSUE TITLE
Poor performance of dynamic quantazation

### ISSUE THREAD

**Issue by estrulyov** [pytorch/pytorch#41865]
## 🐛 Bug

I am experimenting with dynamic quantization as described here:
https://pytorch.org/blog/introduction-to-quantization-on-pytorch/

I got a pretty good speedup when running with a single thread. (This is a GRPC server application that serves pytorch models). However, I do not see any improvement when using multiple threads and processing multiple concurrent requests. This does not happen when dynamic quantization is not being used: I see pretty good scaling up to about 10 threads. The CPU utilization when running with 10 threads but without quantization is well over 700%. However, when dynamic quantization is enabled, CPU load peaks around 150%, meaning that most of the cores sit idle.

This leads me to believe that python's GIL is the culprit. I noticed that in many parts of the code, pytorch does the following:

pybind11::gil_scoped_release no_gil;

But this does not happen in qlinear_dynamic.cpp which runs on dynamic quantization. This again implies that when dynamic quantization is used, GIL does not get released. This would certainly explain why we see improved performance with one thread but not with multiple threads.

## To Reproduce

1. Set OMP_NUM_THREADS=1 environment variable.

2. Load any model and apply dynamic quantization:

model = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)

3. Use threadpool to make multiple concurrent calls to to the model.

## Expected behavior

Throughput should scale with the number of threads in the threadpool.

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.5
GCC version: Could not collect
CMake version: version 3.15.0

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.1
[pip3] numpy==1.18.4
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

## Additional context

If you remove the dynamic quantization line, single-thread performance is slower but throughput does scale properly with the number of threads in the threadpool.

cc @ezyang @gchanan @zou3519 @suo @gmagogsfm @bhosmer @smessmer @ljk53 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
cc @vkuzo

**Comment by dskhudia** [comment]
Hi @estrulyov, I do see scaling with number of threads for both float and dynamically quantized module with something like OMP_NUM_THREADS=1 python model.py and OMP_NUM_THREADS=4 python model.py 

Is this what you are doing? if not, how are you making concurrent calls to the model?

**Comment by estrulyov** [comment]
As already explained, the GRPC application has a threadpool with 10 threads. OMP_NUM_THREADS is always set to 1. You can try something like this to reproduce it:

from concurrent.futures import ThreadPoolExecutor

def run_model():
  ...

executor = ThreadPoolExecutor(max_workers=10)
futures = []
for i in range(1000):
    future = executor.submit(run_model)
    futures.append(future)

for future in futures:
    future.result()

When dynamic quantization is not used, a single call to run_model() is slower. But overall throughput scales with the number of threads in the threadpool.

However, when dynamic quantization is enabled using the following code:

model = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)

A single call to model is faster, but throughput does not improve with the number of threads.

**Comment by ezyang** [comment]
Relevant code is probably

```
inline py::object invokeOperatorFromPython(
    const std::vector<std::shared_ptr<Operator>>& operations,
    py::args args,
    py::kwargs kwargs) {
  Stack stack;

  if (operations.size() == 1) {
    const Operator& op = *operations.at(0);
    // Create a stack full of the arguments and keyword arguments.
    stack = createStackForSchema(
        op.schema(), std::move(args), std::move(kwargs), c10::nullopt);
    op.getOperation()(&stack);
  } else {
    std::vector<schema_match_error> errors;
    std::shared_ptr<Operator> found_op = nullptr;
    for (const auto& op : operations) {
      try {
        stack = createStackForSchema(op->schema(), args, kwargs, c10::nullopt);
        found_op = op;
        break;
      } catch (schema_match_error& error) {
        errors.push_back(std::move(error));
      }
    }
    if (!found_op) {
      std::stringstream ss;
      ss << "Overloaded torch operator invoked from Python failed to many any schema:\n";
      for (const auto& err : errors) {
        ss << err.what() << "\n\n";
      }
      throw std::runtime_error(ss.str());
    }
    found_op->getOperation()(&stack);
  }

  return createPyObjectForStack(std::move(stack));
}
```

This is how we go from torch.ops to the actual operators. It doesn't look like we nogil here, and we probably should.

**Comment by wconstab** [comment]
@estrulyov Can you let me know if [this gist](https://gist.github.com/wconstab/548ce30bcc1f46de447ec4d0c779dcbc) is an accurate repro for your issue?  I'm building with FBGEMM and no *NNPACK libs currently, and the results i'm seeing are below.

I'm confirming, because while the throughput scaling for quant=True is worse than quant=False, i'm not sure if it's as bad as what you were seeing.

> OMP_NUM_THREADS=1 python repro-quant-gil.py  --threads 1 10 100 1000 
```
Times for quant=False
Threads          1        10      100     1000
---------  -------  --------  -------  -------
Time       1.26877  1.14406   1.37263  1.51471
Rel        1        0.901709  1.08186  1.19384
```
> OMP_NUM_THREADS=1 python repro-quant-gil.py  --threads 1 10 100 1000 --quantize
```
Times for quant=True
Threads          1       10      100     1000
---------  -------  -------  -------  -------
Time       2.38715  2.90515  4.03674  4.03005
Rel        1        1.217    1.69103  1.68822
```

**Comment by estrulyov** [comment]
1. Model should not be reinstantiated in run_model. It's enough to load it once.

2. I am seeing no improvement at all from multiple threads.

**Comment by wconstab** [comment]
@estrulyov I've updated [my gist ](https://gist.github.com/wconstab/548ce30bcc1f46de447ec4d0c779dcbc) to reuse the model.  Can you send me the output from the running the latest gist on your setup?

Can you also send more info about how you got your pytorch binary?  I'm interested in the build configuration, because build-time options like FBGEMM lib or NNPack lib could be relevant.

**Comment by estrulyov** [comment]
```
Times for quant=False
Threads           1        10       100      1000
---------  --------  --------  --------  --------
Time       0.457879  0.377978  0.415642  0.431436
Rel        1         0.825497  0.907755  0.942249


Times for quant=True
Threads           1        10       100      1000
---------  --------  --------  --------  --------
Time       0.465345  0.420382  0.454914  0.471293
Rel        1         0.903377  0.977584  1.01278
```

This is consistent with what I've seen previously. We get optimal throughput right around 10 threads (though for real models the throughput improvement is significantly larger than this test shows). We see no improvement for quantized models.

We have torch==1.5.0 in requirements.txt, so it probably just installed the default build. Let me know if you need any more info.

**Comment by wconstab** [comment]
Ok, sorry to iterate but I'm still not sure if I'm able to repro the same scenario as you, and I need a stable repro before I go digging for a fix.  I reran on mac with torch==1.4,1.5,1.6, and I also used threads=1,2,4,8,16, with larger workloads.  I didn't see much variation across torch versions, and I did see improvement from multiple threads in all cases.  Scaling efficiency tends to drop for me around 8 threads.  

At one point you said 'no improvement at all from multiple threads' -- can you elaborate on this?  I wouldn't expect improvement from more threads than # cores, if you're running a large workload.  Are you seeing numbers like what's below, and wanting better efficiency, or are you seeing something way worse?

```
hidden: 4000
Times for quant=True
Threads    1        2        4        8       16  
---------  -------  -------  -------  ------  ------
Time (s)   81.62    40.63    19.66    16.45   24.27
Scaling    100.00%  100.43%  103.80%  62.01%  21.02%

hidden: 4000, 
Times for quant=False
Threads    1        2       4        8       16  
---------  -------  ------  -------  ------  ------
Time (s)   79.63    40.37   19.14    19.07   27.17
Scaling    100.00%  98.63%  104.02%  52.20%  18.32%

```

**Comment by estrulyov** [comment]
I modified your script to use a real model (distilbert-base-uncased). Here are the numbers I'm getting:

```
Instantiating tokenizer
Instantiating model
Testing with 1 threads
Testing with 2 threads
Testing with 4 threads
Testing with 8 threads
Testing with 16 threads
Times for quant=False
Threads          1          2         4         8        16
---------  -------  ---------  --------  --------  --------
Time       27.5662  14.6914    7.27943   8.72208   9.37816
Rel         1        0.532949  0.264071  0.316405  0.340205
(python3.8) Eugenes-iMac-215:tmp estrulyov$ python repro-quant-gil.py --quantize
Instantiating tokenizer
Instantiating model
Testing with 1 threads
Testing with 2 threads
Testing with 4 threads
Testing with 8 threads
Testing with 16 threads
Times for quant=True
Threads          1         2         4         8        16
---------  -------  --------  --------  --------  --------
Time       7.22862  7.15039   6.80295   6.83436   6.84881
Rel        1        0.989178  0.941113  0.945458  0.947457
```

Make sure you run export OMP_NUM_THREADS=1 first.

**Comment by estrulyov** [comment]
`import torch
import torch.nn as nn
from concurrent.futures import ThreadPoolExecutor
import time
import argparse
from tabulate import tabulate
from transformers import DistilBertModel, DistilBertTokenizer


def run_model(tokenizer, model, txt):
    input_ids = torch.tensor(tokenizer.encode(txt, add_special_tokens=True)).unsqueeze(0)
    outputs = model(input_ids)
    return outputs

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--quantize', action='store_true')
    parser.add_argument('--threads', nargs='+', type=int, default=[1, 2, 4, 8, 16])
    args = parser.parse_args()

    print ("Instantiating tokenizer")
    tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
    print ("Instantiating model")
    model = DistilBertModel.from_pretrained('distilbert-base-uncased')

    if args.quantize:
        model = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)

    times = []
    for threads in args.threads:
        print ("Testing with %d threads" % threads)
        if threads == 0:
            t0 = time.time()
            run_model(quantize=args.quantize)
            t1 = time.time()
        else:
            executor = ThreadPoolExecutor(max_workers=threads)
            futures = []
            t0 = time.time()
            for i in range(1000):
                txt = 'this is a test %i' % i
                future = executor.submit(run_model, tokenizer, model, txt)
                futures.append(future)

            for future in futures:
                future.result()
            t1 = time.time()
            executor.shutdown()
        times.append(t1 - t0)
    header = ["Threads"] + args.threads
    table = [["Time"] + times, ["Rel"] + [float(t)/times[0] for t in times]]
    print("Times for quant={}".format(args.quantize))
    print(tabulate(table, header))
`

**Comment by wconstab** [comment]
Great, thanks, this helps a lot, I'm able to repro now, so I'll update when I have found something.

**Comment by dskhudia** [comment]
Hi @wconstab, I tried the same fix earlier when I was analyzing this issue but it didn't show me any improvements at the time.

**Comment by wconstab** [comment]
@dskhudia Take a look at my post here: https://github.com/pytorch/pytorch/pull/42341#issuecomment-668762373 - can you comment on what repro steps you were using? I was not able to reproduce the issue until I used the distilbert model suggested by @estrulyov, but then I was able to confirm a significant improvement in scaling for the quantized case with this change.

By the wya @estrulyov - I just merged a fix, it should be included in the nightly release that goes out tonight, so maybe you can try tomorrow with the latest torch version and reopen if not fixed?

**Comment by dskhudia** [comment]
I created the following simpler repro using @estrulyov's instructions. 
```
import torch
import torch.quantization
import torch.nn as nn
import copy
import os
import time
import timeit
from concurrent.futures import ThreadPoolExecutor


class linear_for_demonstration(nn.Module):
  def __init__(self, IN, OUT):
     super(linear_for_demonstration,self).__init__()
     self.linear = nn.Linear(IN, OUT)

  def forward(self, inputs):
     return self.linear(inputs)


torch.manual_seed(29592)  # set the seed for reproducibility

#shape parameters
IN=1024
N=20
OUT=1024
WORKERS=4

# random data for input
inputs = torch.randn(N, IN)


 # here is our floating point instance
float_linear = linear_for_demonstration(IN, OUT)

# this is the call that does the work
quantized_linear = torch.quantization.quantize_dynamic(
    float_linear, {nn.Linear}, dtype=torch.qint8
)
def run_float_model():
    float_linear.forward(inputs)
    #pass
def run_quant_model():
    quantized_linear.forward(inputs)
    #pass


executor = ThreadPoolExecutor(max_workers=WORKERS)

start = time.time()
futures = []
for i in range(10000):
    future = executor.submit(run_float_model)
    futures.append(future)

for future in futures:
    future.result()

end = time.time()
print("float time with {} workers: ".format(WORKERS))
print(end - start)

start = time.time()
futures = []
for i in range(10000):
    future = executor.submit(run_quant_model)
    futures.append(future)

for future in futures:
    future.result()

end = time.time()
print("quant time with {} workers: ".format(WORKERS))
print(end - start)

start = time.time()
for _ in range(100):
    float_linear.forward(inputs)
end = time.time()
print("float time: ")
print(end - start)

start = time.time()
for _ in range(100):
    quantized_linear.forward(inputs)
end = time.time()
print("quantize_time time: ")
print(end - start)

# show the changes that were made

print('Here is the f oating point version of this module:')
print(float_linear)
print('')
print('and now the quantized version:')
print(quantized_linear)

def print_size_of_model(model, label=""):
    torch.save(model.state_dict(), "temp.p")
    size=os.path.getsize("temp.p")
    print("model: ",label,' \t','Size (KB):', size/1e3)
    os.remove('temp.p')
    return size

# compare the sizes
f=print_size_of_model(float_linear,"fp32")
q=print_size_of_model(quantized_linear,"int8")
print("{0:.2f} times smaller".format(f/q))
```

Output of an example run (not with your fix) with OMP_NUM_THREADS set to 1:
```
float time with 4 workers:
2.41115665435791
quant time with 4 workers:
5.425195932388306
float time:
0.08111977577209473
quantize_time time:
0.050034523010253906
Here is the f oating point version of this module:
linear_for_demonstration(
  (linear): Linear(in_features=1024, out_features=1024, bias=True)
)

and now the quantized version:
linear_for_demonstration(
  (linear): DynamicQuantizedLinear(in_features=1024, out_features=1024, qscheme=torch.per_tensor_affine)
)
model:  fp32     Size (KB): 4198.965
model:  int8     Size (KB): 1053.686
3.99 times smaller
```

**Comment by wconstab** [comment]
@estrulyov I confirmed that `pytorch-1.7.0.dev20200806` (last night's nightly) shows the improvement I was looking for on both the distilbert script and @dskhudia's script.  If you could confirm, that'd be great.
`conda install pytorch=1.7.0.dev20200806 -c pytorch-nightly`

**Comment by estrulyov** [comment]
I am not seeing improvement. Is there any way to confirm the right version of torch is running?

(base) (python3) Eugenes-iMac-215:tmp estrulyov$ python repro-quant-gil.py --quantize
Instantiating tokenizer
Instantiating model
Testing with 1 threads
Testing with 2 threads
Testing with 4 threads
Testing with 8 threads
Testing with 16 threads
Times for quant=True
Threads          1         2         4         8        16
---------  -------  --------  --------  --------  --------
Time       7.44221  7.36374   6.91737   7.09217   7.21908
Rel        1        0.989456  0.929478  0.952966  0.970018

**Comment by estrulyov** [comment]
version.py has this:

__version__ = '1.5.1'
debug = False
cuda = None
git_version = '3c31d73c875d9a4a6ea8a843b9a0d1b19fbe36f3'
hip = None

**Comment by wconstab** [comment]
Yea, seems like you are still using torch 1.5.1.

You can confirm you have gotten the right torch version by running
`python -c 'import torch; print(torch.__version__)'`

and seeing this as output:
1.7.0.dev20200806

**Comment by estrulyov** [comment]
Now I'm seeing this:

$ cat /usr/local/miniconda3/lib/python3.8/site-packages/torch/version.py 
__version__ = '1.7.0.dev20200806'
debug = False
cuda = None
git_version = 'c81b784a72e93c13ba60e9cc8c799c3e7bcaeb7c'
hip = None

---

```
(base) Eugenes-iMac-215:tmp estrulyov$ python repro-quant-gil.py --quantize
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
Instantiating tokenizer
Instantiating model
Testing with 1 threads
Testing with 2 threads
Testing with 4 threads
Testing with 8 threads
Testing with 16 threads
Times for quant=True
Threads          1         2         4         8        16
---------  -------  --------  --------  --------  --------
Time       8.73314  5.77398   3.62529   3.7916    3.82532
Rel        1        0.661157  0.415118  0.434162  0.438024
```

```
(base) Eugenes-iMac-215:tmp estrulyov$ python repro-quant-gil.py 
To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html
Instantiating tokenizer
Instantiating model
Testing with 1 threads
Testing with 2 threads
Testing with 4 threads
Testing with 8 threads
Testing with 16 threads
Times for quant=False
Threads          1          2         4         8        16
---------  -------  ---------  --------  --------  --------
Time       29.0679  15.807     8.04061   9.72005   10.0229
Rel         1        0.543797  0.276615  0.334392   0.34481
```

Looking much better now, although scaling is not quite as good as for non-quantized model (at 8 threads, .43 vs .33)

**Comment by estrulyov** [comment]
Stil, this looks like a 3.3x reduction in latency and 2.5x improvement in throughput. Nice!

**Comment by wconstab** [comment]
Yea, I have not investigated additional causes for the scaling disparity, other than to look at a trace of each program and note that in the non-quantized case most of the time is spent in the mul kernel with the gil released, while in the quantized case, the quant kernel is so fast that it accounts for a much smaller fraction of the overall program time, meaning that the overhead of all the other 'little' operations becomes more dominant.  If you have reason to believe there's still anything 'broken' about the scaling with a particular op or model, please open another issue.
