### ISSUE TITLE
Towards better C++ exception traces with try...catch

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4187]
Right now, when we raise an error in C++ code, no useful information is made available to the user besides the text at the site the exception was thrown. This is not friendly for our users. At a first glance, one might be tempted to see if there is a way to extract a stack trace from the stack and associate with the exception, but one will quickly find that doing so portably is actually quite a bit of work, and you are still in trouble when library code raises exceptions (where you are unable to replace the throw with your own custom function.)

Fortunately, in ATen we currently make liberal use of code generation, which means we can adopt an alternative strategy for exception handling: add try-catch blocks at all method exit points to annotate exceptions with the necessary metadata to give a good stack trace. And furthermore, modern C++ compilers make try...catch blocks extremely cheap when no exception is thrown.

To implement this, we would need to:

1. Design a new exception type which contains stack information we are interested in. A very simple representation would be a vector of strings, but more sophisticated strategies might include correlating tensors at the exception site to the tensors originally passed in by the user (e.g., if convolution raises an exception about 'input', but it becomes clear later that this is actually the 'grad_output' of a transposed convolution, a structured error representation would let us rewrite the error message to more clearly indicate the name of the tensor.

2. Modify code generation to insert try..catch blocks at appropriate method entry points, catching both the new exception type as well as all other exceptions and augmenting them with the necessary information.

3. Render the exceptions in a nice form when they hit users.

**Comment by apaszke** [comment]
I don't think that's the critical part of providing good error messages. What's important is to show what someone did wrong, not the whole C++ stack. People usually don't want to spend time diving into our code to figure out where the error has happened exactly.

**Comment by colesbury** [comment]
I don't think codegen is needed. There are only a few entry spots to ATen:

1) Variable/Tensor methods. These already have correct stack traces
2) Backwards functions. These can be captured with a `try/catch` around here:

https://github.com/pytorch/pytorch/blob/6d72c829855607953ac001a21e34692f278f6439/torch/csrc/autograd/engine.cpp#L208

We can get the name of the backward function via `fn->name()`.

**Comment by ezyang** [comment]
I reproposed this 2.5 years later LOL. CLosing in favor of the new issue: https://github.com/pytorch/pytorch/issues/37160
