### ISSUE TITLE
[ROCm] [Build Error] [CMake] Cannot find hip

### ISSUE THREAD

**Issue by acxz** [pytorch/pytorch#41886]
## 🐛 Bug

When compiling pytorch with ROCm, pytorch fails when trying to find rocblas, because rocblas fails to find hip.

```
***** Library versions from cmake find_package *****

rocrand VERSION: 2.10.1.0
hiprand VERSION: 2.10.1.0
CMake Error at /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/rocblas/lib/cmake/rocblas/rocblas-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:169 (find_package_and_print_version)
  cmake/Dependencies.cmake:995 (include)
  CMakeLists.txt:411 (include)


-- Configuring incomplete, errors occurred!
```

## To Reproduce

1. git clone
2. python setup.py build

## Expected behavior

The build should successfully complete

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Arch Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py build`
 - Python version: 3.8.3
 - CUDA/cuDNN version: N/A
 - GPU models and configuration:
 - Any other relevant information: ROCm

## Additional context

Downstream issue: https://github.com/rocm-arch/python-pytorch-rocm/issues/2

cc @malfet @jeffdaily @sunway513

**Comment by acxz** [comment]
Upstream issue: https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/1156

**Comment by jeffdaily** [comment]
Did you run `python3 tools/amd_build/build_amd.py`, after step 1 but before step 2?

This blog has also been used by some of our external users with steps to build: http://lernapparat.de/pytorch-rocm/ .  @t-vi 

We tend to use the script `.jenkins/pytorch/build.sh` as a one-shot script to build and install pytorch.  It's the script used by our CI to build.

**Comment by acxz** [comment]
Thanks for responding @jeffdaily 
I am on of the maintainers for [rocm-arch](https://github.com/rocm-arcm) and we are trying to get pytorch compiling with ROCm for Arch Linux users. This includes using Arch Linux packaged ROCm.

I have not ran the `build_amd.py` command specified, thanks for pointing me to it, definitely seems like something I need to be aware of when building ROCm for Arch Linux.

Thanks for pointing me to the blogpost. It seems that they also encountered the same issue:

> At the time of writing, there is a small glitch in the repositories regarding the capitalization of HIP in the CMake tooling. I run for fn in $(find /opt/rocm/ -name \*.cmake ); do sudo sed --in-place='~' 's/find_dependency(hip)/find_dependency(HIP)/' $fn ; done to fix things.

Looks like this issue was previously encountered but nothing was done by the blog post author besides the hacky fix.

As for the exact build procedure I am going about here is the script which should be easy to read through: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pytorch-rocm

**Comment by acxz** [comment]
@jeffdaily based on comments by AMD developers for the rocm-libs like rocfft (https://github.com/ROCmSoftwarePlatform/rocFFT/pull/304#issuecomment-663102731) there is a difference between 'HIP' and 'hip' which is why @t-vi 's hack in the blog link you posted is not correct. Right now pytorch code is finding HIP with FindHIP.cmake but we also need to find 'hip' from 'hip-config.cmake'. On the linked comment's PR chain FindHIP.cmake does not include everything 'hip-config.cmake' does which is why upstream rocm-libs like rocfft use `find_package/dependency(hip)` instead of 'find_package/dependency(HIP)'

I believe eventually `FindHIP.cmake` will be more complete but until then we need to accommodate for both `HIP` and `hip` targets.

**Comment by acxz** [comment]
@jeffdaily I have created a fix that resolves this issue and have tested it on my machine. If you could take a look at it that would be great: https://github.com/pytorch/pytorch/pull/42064

**Comment by t-vi** [comment]
@acxz awesome work digging to the bottom of HIP vs. hip!

**Comment by acxz** [comment]
Thanks for the complements, really means a lot since its coming from you haha!

**Comment by t-vi** [comment]
@acxz Thank you so much for fixing it. I updated [my instructions](https://lernapparat.de/pytorch-rocm/), linking the PR and using github handle. If you have other preferences for crediting you there, I'd be glad to accommodate them.

**Comment by acxz** [comment]
Thanks for updating your post and the credit!
