### ISSUE TITLE
Allow decentralized op registration.

### ISSUE THREAD

**Issue by cloudhan** [pytorch/pytorch#41917]
## 🚀 Feature

When I try to load a plugin library built with 2 cpp file,
```python
torch.ops.load_library("libtorch_plugins.so")
```

I got the following error:
```
Only a single TORCH_LIBRARY can be used to register the namespace decode; please put all of your definitions in a single TORCH_LIBRARY block.  If you were trying to specify implementations, consider using TORCH_LIBRARY_IMPL (which can be duplicated).  Previous registration of TORCH_LIBRARY was registered at /home/cloudhan/workspaces/torch_plugins/src/readjpeg_cpu.cpp:146; latest registration was registered at /home/cloudhan/workspaces/torch_plugins/src/readpng_cpu.cpp:87
```

## Motivation

Currently, the only valid way to build a plugin library is to collect all op registration into one translation unit. 
That is
```cpp
// file foo.cpp

// define op foo
```

```cpp
// file bar.cpp

// define op bar
```

```cpp
// registration.cpp

#include "foo.h"
#include "bar.h"

// register ops foo and bar 
```
In this way, it is hard to maintain flexible extension op set. Since to add a new op,  you need to directly modify `registration.cpp`
To remove unneeded ops, you also need to modify `registration.cpp`

If distributed registration is supported, all I need is
```cpp
// file foo.cpp

// define op foo
// register op foo
```

```cpp
// file bar.cpp

// define op bar
// register op bar 
```

Simply control which cpp file to be compiled and linked, I can now control the registration easier.

cc @yf225 @glaringlee @ezyang @bhosmer @smessmer @ljk53

**Comment by mrshenli** [comment]
Edited the title to replace "distributed" with "decentralized", to make it clear this is irrelevant to `torch.distributed`.

**Comment by mrshenli** [comment]
Adding to triage review as this seems require structural changes to our op registration design, and wanted to bring this to team discussion.

**Comment by cloudhan** [comment]
Ok, I discover `TORCH_LIBRARY_FRAGMENT_THIS_API_IS_FOR_PER_OP_REGISTRATION_ONLY`, based on the extremely long macro name, I don't think it is for end users. But actually works.

**Comment by ezyang** [comment]
Forcing all of the operators to live in one place was an intentional design choice to make it easier for readers to find a list of all of the operators corresponding to a namespace (just one `TORCH_LIBRARY`). This also matches the behavior of pybind11 modules, which are also defined in one space.

I think there is a little extra juice in the API which you may not know about, which might solve your problem. What you can do is define a `TORCH_LIBRARY` but don't provide any implementations in it.

```
TORCH_LIBRARY(decode, m) {
  m.def("foo(Tensor self) -> Tensor");
  m.def("bar(Tensor self) -> Tensor");
}
```

And then, in the separate compilation units, you can write:

```
TORCH_LIBRARY_IMPL(decode, CPU, m) {
  m.impl("foo", foo_cpu);
}
```

the impl blocks can be duplicated without trouble.

More deets in https://pytorch.org/tutorials/advanced/dispatcher.html

**Comment by cloudhan** [comment]
should be good for now, still prefer the decentralized version.

to list all op in a namespace, a `grep -r` into src folder or `dir` in python should be sufficient.

**Comment by ezyang** [comment]
It's even worse than what you imply: if totally decentralized op registration is allowed, you could get operators from a completely different dynamic library that was linked in. So the grep wouldn't necessarily be sufficient ;)
