### ISSUE TITLE
Transform ProcessGroupNCCLTest into a gtest

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#41929]
To make test easily integratabtle into various CI systems it's better if it's based on one of the standard frameworks.

https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/test/ProcessGroupNCCLTest.cpp

Majority of other PyTorch C++ unit tests are using GTest framework, for example https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/test/ProcessGroupNCCLErrorsTest.cpp

cc @ezyang @seemethere @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment]
Related to https://github.com/pytorch/pytorch/issues/28410

**Comment by osalpekar** [comment]
Fixed by #42208
