### ISSUE TITLE
How to Upgrade PyTorch to 1.6 in Docker Image

### ISSUE THREAD

**Issue by zhenhuahu** [pytorch/pytorch#41935]
### Hi, I have a docker image that has pytorch 1.4, torchvision 0.5, cudnn 7.6.5 and cuda 10.1, and other tools and packages. I want to upgrade my pytorch to 1.6. Is there some way to do it without rebuild the whole image again?

Thanks!

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @ezyang @seemethere @malfet

**Comment by seemethere** [comment]
We'll release official docker images for 1.6 as part of our GA release.

Look out for updated tags on https://hub.docker.com/r/pytorch/pytorch/tags

**Comment by zhenhuahu** [comment]
> We'll release official docker images for 1.6 as part of our GA release.
> 
> Look out for updated tags on https://hub.docker.com/r/pytorch/pytorch/tags

Thanks for the reply. I've looked at the website you shared. But if I use the official docker image as the base image, I'll need to reinstall other softwares again. Are there commands that I can use to just upgrade pytorch 1.4 to 1.6, so that I won't need to install other softwares? Thanks/

**Comment by yuanzhedong** [comment]
I have the same question, just want to check if I can quickly test pytorch 1.6 by updating pytorch from 1.5 to 1.6 inside a docker since I don't want to touch the other packages inside the docker yet.

**Comment by seemethere** [comment]
If you'd like to upgrade your pytorch within the docker image you can do so with:
```
/opt/conda/bin/conda upgrade -c pytorch pytorch
```

Going to consider this one closed since 1.6 has already been released
