### ISSUE TITLE
GPU usage 0% while is_cuda() returns true for both variable and NN modules

### ISSUE THREAD

**Issue by fredyjl** [pytorch/pytorch#4194]
GPU-Util is 0% given by `nvidia-smi`, while both `next(module.parameters()).is_cuda()` and `variable.data.is_cuda()` print True. 

Is there any other way I can debug or make sure the GPU usage?

**Comment by soumith** [comment]
make a post at https://discuss.pytorch.org with more details on your code and use-case.
