### ISSUE TITLE
Parameter registration in MultiheadAttention c++ API is incorrect

### ISSUE THREAD

**Issue by glaringlee** [pytorch/pytorch#41951]
## 🐛 Bug

MultiheadAttention c++ API did not register parameters under some conditions. The most important ones are 'in_proj_weight' and 'in_proj_bias'.

Here is the parameter registration phase in c++ impl:
https://github.com/pytorch/pytorch/blob/47766e648ff16d4b1175d04710caed566de14ab4/torch/csrc/api/src/nn/modules/activation.cpp#L450

Here is the parameter registration phase in python impl:
https://github.com/pytorch/pytorch/blob/75a4862f639de666c66a0db240c993918b80707f/torch/nn/modules/activation.py#L842

The problem here is that in python, the following code will register parameter automatically, but c++ version doesn't.
```
self.in_proj_bias = Parameter(torch.empty(3 * embed_dim))
```
The reason is that `Module` has a customized __setattr__ which handles the parameter/module registration automatically:
https://github.com/pytorch/pytorch/blob/eace0533985641d9c2f36e43e3de694aca886bd9/torch/nn/modules/module.py#L657

This will cause problem when people want to update parameters' value by iterating parameter that returned by calling parameters(), since some of the parameters won't be returned by c++ version. Here is an example:
https://github.com/pytorch/pytorch/blob/f71cccc457421ad220cf58914c8bc3801b072300/test/test_nn.py#L4678

The possible equivalent c++ impl will be something like this:
```
torch::MultiheadAttention model(torch::MultiheadAttentionOptions(4, 2).dropout(0.0));
{
    torch::NoGradGuard guard;
    for (auto& p : model->parameters()) {
      auto sz = p.view(-1).size(0);
      p.copy_(torch::cos(torch::arange(0, sz, tensor_options).view(p.sizes())));
    }
}
```
Currently, c++ code will return two less parameters from module->parameters() than python version due to not registering the parameter correctly.

## To Reproduce

Above c++ code piece is an example.

## Expected behavior

Python and c++ api should return same number of parameters when calling parameters().

## Environment

 ```
PyTorch version: 1.7.0a0+fced54a
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
CMake version: version 3.14.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 418.126.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.7.6.5
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.1.4
```

## Additional context

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
Will put a fix since I am working on cpp transformer layer and this MultiheadAttention model will be used within transformer layer's encoder/decoder

**Comment by meganset** [comment]
I'm still seeing a problem with picking up parameters in the latest version of libtorch.

e.g. in python
```
>>> m=torch.nn.MultiheadAttention(64,8)
>>> for n,t in m.named_parameters():
...  print(n,t.size())

in_proj_weight torch.Size([192, 64])
in_proj_bias torch.Size([192])
out_proj.weight torch.Size([64, 64])
out_proj.bias torch.Size([64])

>>> m=torch.nn.MultiheadAttention(64,8,kdim=128)
>>> for n,t in m.named_parameters():
...  print(n,t.size())
... 
q_proj_weight torch.Size([64, 64])
k_proj_weight torch.Size([64, 128])
v_proj_weight torch.Size([64, 64])
in_proj_bias torch.Size([192])
out_proj.weight torch.Size([64, 64])
out_proj.bias torch.Size([64])
```

from latest libtorch builds (I see changes in activation.h, not sure if changes to activation.cpp are making it into libtorch ??)

```
auto m=torch::nn::MultiheadAttention(64,8);
 for(auto& a:m->named_parameters())
  std::cerr << a.key() << " " << a.value().sizes() << "\n";

 m=torch::nn::MultiheadAttention( torch::nn::MultiheadAttentionOptions(64,8).kdim(128));

 std::cerr << "m=torch::nn::MultiheadAttention( torch::nn::MultiheadAttentionOptions(64,8).kdim(128))\n";
 for(auto& a:m->named_parameters())
  std::cerr << a.key() << " " << a.value().sizes() << "\n";


out_proj.weight [64, 64]
out_proj.bias [64]
m=torch::nn::MultiheadAttention( torch::nn::MultiheadAttentionOptions(64,8).kdim(128))
out_proj.weight [64, 64]
out_proj.bias [64]
```

**Comment by glaringlee** [comment]
@meganset 
Which libtorch builds you were using? Can you share the version? thx

**Comment by meganset** [comment]
Thanks for looking into this.
```
cat libtorch/build-version
1.7.0.dev20200916
```
I just downloaded the latest libtorch.zip via
wget https://download.pytorch.org/libtorch/nightly/cu102/libtorch-shared-with-deps-latest.zip

and still see the problem.

**Comment by glaringlee** [comment]
> Thanks for looking into this.
> 
> ```
> cat libtorch/build-version
> 1.7.0.dev20200916
> ```
> 
> I just downloaded the latest libtorch.zip via
> wget https://download.pytorch.org/libtorch/nightly/cu102/libtorch-shared-with-deps-latest.zip
> 
> and still see the problem.

Looked at the code, did not see any issues. I try reproduce this on my end. 
Please make sure you linked your code with a correct version. (Just in case you have multiple libtorch version on your machine)

**Comment by meganset** [comment]
"..make sure you linked your code with a correct version."

Yes, this is the problem -- I wasn't picking up the right library in the make.
Sorry for the confusion.
The parameters show up correctly now and match the python version

```
in_proj_weight [192, 64]
in_proj_bias [192]
out_proj.weight [64, 64]
out_proj.bias [64]

m=torch::nn::MultiheadAttention( torch::nn::MultiheadAttentionOptions(64,8).kdim(128))
q_proj_weight [64, 64]
k_proj_weight [64, 128]
v_proj_weight [64, 64]
in_proj_bias [192]
out_proj.weight [64, 64]
out_proj.bias [64]
```

**Comment by glaringlee** [comment]
@meganset Glad to hear that!
