### ISSUE TITLE
When import torch,ImportError: libcufft.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zz20200** [pytorch/pytorch#41975]
# Issue description

My device is Jetson Nano, using JetPack4.3.
After
![image2020-7-24_10-48-6](https://user-images.githubusercontent.com/40493593/88356689-3f122480-cd9b-11ea-992d-f0666c1e9fe2.png)
then
![image](https://user-images.githubusercontent.com/40493593/88356905-00c93500-cd9c-11ea-8ceb-dca17b423156.png)
Error occured!

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dl/.local/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: libcufft.so.10.0: cannot open shared object file: No such file or directory
```

- PyTorch :
- How you installed PyTorch (conda, pip, source):pip
- OS:Ubuntu18.04
- PyTorch version:1.4.0
- Python version:3.6.8
- CUDA/cuDNN version:10.2
- GCC version (if compiling from source):8.4.0

Sad.....I can't fix it.

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
Can you please tell me, how did you obtained this .whl package? And it looks like it was build against CUDA-10, but author forgot to package dependent libraries inside, so you have to install CUDA dependent libraries from one of older JetPack SDK releases: https://developer.nvidia.com/embedded/jetpack-archive

**Comment by zz20200** [comment]
> Can you please tell me, how did you obtained this .whl package?
> 
> It looks like it was build against CUDA-10, but dependent libraries weren't packaged into it, so you have to install CUDA dependent libraries from one of older JetPack SDK releases: https://developer.nvidia.com/embedded/jetpack-archive

Thanks!
I have solved this problem. It is because I confused the version of jetpack. I thought it was 4.3, but it was actually 4.4. The pytorch1.4.whl I installed was not suitable for 4.4. Finally, I installed pytorch1.6 to solve this problem.
