### ISSUE TITLE
RuntimeError: dim() called on undefined Tensor

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#4198]
Reported here in a different form: https://discuss.pytorch.org/t/runtimeerror-contiguous-is-not-implemented-for-type-undefinedtype/11124/30 .

Took me a while to isolate the bug but below is a script to reproduce this:
```
import torch
from torch.autograd import Variable
from torch.autograd import Function

class Fn(Function):
    def forward(self, x, y):
        return torch.zeros(2, 2, 2)

    def backward(self, grad_output):
        return torch.zeros(2, 2, 2), None

x = Variable(torch.zeros(1), requires_grad=True)
y = x[0].expand(2000, 5)
model = Fn()
model(x, y).sum().backward()
```
I'm looking into it.

**Comment by zou3519** [comment]
Also if anyone has suggestions, I'm having trouble catching the runtime error (it occurs in autograd) in gdb.

**Comment by colesbury** [comment]
A little while ago I added code to `python_function.cpp` that translates `None` from backward to zeros. I think it's only happening for "new style" autograd functions that use `@staticmethod`. We should make it work for these "old style" functions too.
