### ISSUE TITLE
c++ tensor::save is about 5x slower to overwrite the existing tensor.

### ISSUE THREAD

**Issue by cyyever** [pytorch/pytorch#42005]
I found that it is slow to overwrite existing tensor using tensor::save.

## Code
```
#include <chrono>
#include <filesystem>
#include <torch/torch.h>

 uint64_t now_ms() {
    return static_cast<uint64_t>(
        std::chrono::time_point_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now())
            .time_since_epoch()
            .count());
  }

int main(int argc, char **argv) {

  auto tensor = torch::randn({1, 200 * 1024});
  auto begin_ms =now_ms();
  for (int i = 0; i < 100; i++) {
    torch::save(tensor, "tmp_file");
  }
  auto end_ms = now_ms();
  std::cout << "insertion used " << end_ms - begin_ms << " ms" << std::endl;

  begin_ms = now_ms();
  for (int i = 0; i < 100; i++) {
    std::filesystem::remove("tmp_file");
    torch::save(tensor, "tmp_file");
  }
  end_ms = now_ms();
  std::cout << "insertion used " << end_ms - begin_ms << " ms" << std::endl;

  return 0;
}
```

## result
insertion used 557 ms
insertion used 82 ms

## Strace results

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ---------------- 
54.03    0.051799         517       100           writev
 25.79    0.024721         103       238        92 openat 
16.86    0.016168         110       146           close 

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 61.46    0.020940         209       100           writev 
19.27    0.006565          65       100           unlink    
  6.30    0.002147           9       238        92 openat  
3.76    0.001281           9       137           mmap             
  2.01    0.000684           4       146           close 

The only significant difference between these two blocks is that writev syscall is twice slower in the first case.

## Expectation
Overwrite should be as fast as removing the old tensor manually

## Environment
Ubuntu 20.04
pytorch version is github master

cc @yf225 @glaringlee @VitalyFedyunin @ngimel

**Comment by colesbury** [comment]
@suo are you familiar with the torch::save call? It's not clear to me if this is an OS-level issue or an issue in the implementation of save.
