### ISSUE TITLE
Building offline documentation does not work

### ISSUE THREAD

**Issue by demmerichs** [pytorch/pytorch#42003]
## 🐛 Bug

Building the docs for me as an end user (offline documentation) does not work.

## To Reproduce

1. Check out the pytorch repo at tag `v1.5.1`.
1. Create and activate virtual environment: `cd /path/to/pytorch; python3 -m venv .venv; source .venv/bin/activate`
1. Install pytorch version 1.5.1: `pip3 install torch==v1.5.1`
1. Install requirements needed for docs: `cd docs; pip3 install -U -r requirements.txt`
1. Trying to build the docs: `make; make html`

All steps together:
```bash
git clone https://github.com/pytorch/pytorch.git
cd pytorch
git checkout v1.5.1
python3 -m venv .venv
source .venv/bin/activate
pip3 install torch==v1.5.1
cd docs
pip3 install -U -r requirements.txt
make
make html
```

When the `make html` step tries to write the output, it fails like this:
```
preparing documents... done
writing output... [ 23%] distributions                                                                                                                                                                             
Exception occurred:
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'katex': 'katex'
The full traceback has been saved in /tmp/sphinx-err-tsyb3hy5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:38: recipe for target 'html' failed
make: *** [html] Error 2
```

## Expected behavior

I expect the build process to work. Other users seemed to have problems with it before [here](https://discuss.pytorch.org/t/generate-offline-documentation/64643/6) and [here](https://discuss.pytorch.org/t/accessing-pytorch-documentation-offline/20453), but I already avoided the mistakes made there.

## Environment

Generated output from your
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py).

```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Quadro P2000
Nvidia driver version: 410.104
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.5.1
[conda] Could not collect
```

cc @ezyang @zou3519 @jlin27

**Comment by colesbury** [comment]
Per https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#writing-documentation you need katex installed. i.e.

```
npm install -g katex
```

1) We should list this as its own step on CONTRIBUTING.md, not as a code comment below "pip install -r requirements.txt"
2) Ideally, we should check for katex at the start of building docs, and give a useful error message that describes how to install it if it's missing.

**Comment by DavidS3141** [comment]
Yes thanks, seems to work now. Actually, I did not look or found via Google the `contributing.md` :/
Also I thought katex was already installed through the `requirements.txt` with sphinx (bundled or sth like that) and the `FileNotFoundError` did not help clear things up yes.
So the points you mentioned would be helpful, maybe also linking the `contributing.md` part to the docs folder via an additional `docs/readme.md`?
Thanks for the fast answer.

**Comment by ezyang** [comment]
Another possibility is, since we switched to splitting the nn pages, we could switch back to the default sphinx rendering which will just use mathjax and then doesn't require server side rendering.

**Comment by colesbury** [comment]
I like that katex is faster to render and doesn't reflow the page. I think that justifies the slightly more complicated build process for the docs.

**Comment by rgommers** [comment]
> I like that katex is faster to render and doesn't reflow the page. I think that justifies the slightly more complicated build process for the docs.

This was tested recently; katex was still 2x faster than the latest version of mathjax, and the difference on page loading was significant. 

gh-49286 adds the suggested `docs/README.md`, that will close this issue.
