### ISSUE TITLE
libtorch: torch::cuda::is_available() returns zero

### ISSUE THREAD

**Issue by powderluv** [pytorch/pytorch#42018]
## 🐛 Bug

On Top of Master Linux libtorch torch::cuda::is_available() returns zero even when linked against torch_cuda. I have linked against the latest wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

If you put the code inside pytorch's build system with cpp /tests it works ok. 

Snippet:

    torch::Device device = torch::kCPU;
    std::cout << "CUDA DEVICE COUNT: " << torch::cuda::device_count() << std::endl;
    if (torch::cuda::is_available()) {
      std::cout << "CUDA is available! Training on GPU." << std::endl;
      device = torch::kCUDA;
    }

## To Reproduce

1. Download library from https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip

1. link above program and run. Cuda is not detected. 
1.

## Environment

Cuda should be detected. 

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @yf225 @glaringlee

**Comment by ngimel** [comment]
cc @ezyang, @malfet - I remember there was a similar issue recently, but can't find it.

**Comment by malfet** [comment]
@powderluv can you share a more detailed instructions on how you build+link your program?
I've just compiled and run your snippet using something similar to https://pytorch.org/cppdocs/installing.html and it just worked.
Here is my CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(example)

find_package(Torch REQUIRED)

add_executable(example example.cpp)
target_link_libraries(example torch)
set_property(TARGET example PROPERTY CXX_STANDARD 14)
```
and example.cpp
```
include <torch/cuda.h>
#include <iostream>

int main(void) {
  std::cout << "CUDA DEVICE COUNT: " << torch::cuda::device_count() << std::endl;
  if (torch::cuda::is_available()) {
    std::cout << "CUDA is available! Training on GPU." << std::endl;
  }
  return 0;
}
```
And then build it as:
```
$ cmake . -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`; make; ./example
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 10.1
-- Found cuDNN: v7.5.0  (include: /usr/include/cuda, library: /usr/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nshulga/test/cpp_crash/build
Scanning dependencies of target example
[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable example
[100%] Built target example
CUDA DEVICE COUNT: 1
CUDA is available! Training on GPU.
```
And as you can see, it works as expected.

**Comment by powderluv** [comment]
Thanks. Yes I am able to recreate it with your setup and it works as expected. Still doesn't work in my actual setup where I build pytorch via CMake External Project. There is a weird hack if we use C++ data_parallel and run a dummy network then cuda is detected. It does seem like #31611 but for linux. I will dig a bit more and report back.

**Comment by powderluv** [comment]
I have tracked down the issue. In my CMakelist.txt after building the pytorch libs I need to link it with -Wl,--no-as-needed if not they only link to the CPU libs.  

You could add this line to your CMakelist to link properly:

set(CMAKE_LINK_WHAT_YOU_USE TRUE)

Closing.

**Comment by Coderx7** [comment]
Faced this today on 1.7 and [this ](https://github.com/pytorch/pytorch/issues/31611#issuecomment-594383154)solved it

**Comment by liweizheng0528** [comment]
> Faced this today on 1.7 and [this ](https://github.com/pytorch/pytorch/issues/31611#issuecomment-594383154)solved it

How to solve it on linux. My Libtorch is 1.9.0

**Comment by jhillhouse92** [comment]
> I have tracked down the issue. In my CMakelist.txt after building the pytorch libs I need to link it with -Wl,--no-as-needed if not they only link to the CPU libs.
> 
> You could add this line to your CMakelist to link properly:
> 
> set(CMAKE_LINK_WHAT_YOU_USE TRUE)
> 
> Closing.

This fixed it for me. I had to update my cgo to below adding the `-Wl,--no-as-needed` at the beginning (note: the letter after W is a lowercase L not an uppercase i).

```
// #cgo LDFLAGS: -Wl,--no-as-needed -L${SRCDIR}/../libtorch/lib -lc10 -ltorch -lpthread -lcuda -ltorch_cpu -ltorch_cuda
```
