### ISSUE TITLE
A suggestion for the TORCHVISION.TRANSFORMS page

### ISSUE THREAD

**Issue by larry-rystrom** [pytorch/pytorch#42020]
## 📚 Documentation

The transforms documentation page, https://pytorch.org/docs/stable/torchvision/transforms.html ,
has a complete lists of transforms broken down by PIL Image, Torch Tensor, Conversion Transforms, Generic Transforms, and Functional Transforms.

But I have found the RandomChoice and RandomApply transforms, which are under PIL image, useful in the context of custom transforms I have written for a  numpy array. There is nothing specific to PIL images about these transforms.

Would you consider creating a new category, perhaps called Random Selection, that includes these transforms? If so RandomOrder could also go in this category.

Thanks.

**Comment by ngimel** [comment]
Thank you for your suggestion! As this issue concerns torchvision documentation, please file it in pytorch/vision.
