### ISSUE TITLE
[jit] [transformer] [8-bit quantize] Error when trying to quantize pytorch build-in transformer model and then export it with libtorch

### ISSUE THREAD

**Issue by chenxie95** [pytorch/pytorch#42022]
## 🐛 Bug

I found there was some strange error when I tried to apply 8-bit quantize on the pytorch build-in transformer model and then export it using libtorch.  However, if I only do 8-bit quantization or export model using libtorch, it could success without any issue.
It is important to using 8-bit quantization model for transformer model in many scenarios to speedup the evaluation. 
It will be awesome if this bug could be identified and fixed.

## To Reproduce

1. You could simply run the code below to reproduce the error information
2. If I only export the transformer model without 8-bit quantization, it could run smoothly
3. If I only do 8-bit quantization for transformer model, it could also run smoothly
4. However, if I want to do 8-bit quantization and then export the model using libtorch for C++ code, it will throw a strange error as below:
```
method cannot be used as a value:
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/activation.py", line 831
       self.in_proj_weight, self.in_proj_bias,
       self.bias_k, self.bias_v, self.add_zero_attn,
       self.dropout, self.out_proj.weight, self.out_proj.bias,
                     ~~~~~~~~~~~~~~~~~~~~ <--- HERE
       training=self.training,
       key_padding_mask=key_padding_mask, need_weights=need_weights,
```

## Environment

You can reproduce the error simply by running the following code:
```
import torch
class MyModule(torch.nn.Module):
  def __init__(self, N, M):
    super(MyModule, self).__init__()
    self.weight = torch.nn.Parameter(torch.rand(N, M))
    self.layer1 = torch.nn.Linear(640, 1024)
     encoder_layer = torch.nn.TransformerEncoderLayer(1024, nhead=8, dim_feedforward=1024, dropout=0.1, activation='gelu')
    encoder_norm = torch.nn.LayerNorm(1024)
    self.encoder = torch.nn.TransformerEncoder(encoder_layer, 20, encoder_norm)
  def forward(self, x):
    out = self.layer1(x)
    out = self.encoder(out)
    return out

my_module = MyModule(100, 200)
# could quantize the model successfully
my_module = torch.quantization.quantize_dynamic(my_module, dtype=torch.qint8)
# get ERROR in the next command when tracing the quantized model!!!
sm = torch.jit.script(my_module)
torch.jit.save(sm, 'test.jit.model')

```

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Linux Ubuntu 
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.8
 - CUDA/cuDNN version:  CPU only
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by chenxie95** [comment]
I realized that this bug has been fixed in the latest master code (I am using pytorch 1.5.1) in 
https://github.com/pytorch/pytorch/blob/890b52e09ff1a758a2ac814f130a1dc1f1a46e9d/torch/nn/modules/activation.py#L869
by changing the Linear class to _LinearWithBias class, which won't be passed to dynamic quantization function to pack the out_proj.
I add this fix in my code and it works well.
Please simply ignore this above error description then
Thanks

**Comment by vkuzo** [comment]
thanks for the report @chenxie95 .  Closing since this seems fixed.
