### ISSUE TITLE
Document some NCCL environment variable recommendations to tune performance

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#42044]
## 📚 Documentation

We occasionally see users post about performance issues when using NCCL for distributed training ([example](https://discuss.pytorch.org/t/distributeddataparallel-on-multiple-gpu-nodes-slower-than-one-gpu-node/75984), [example](https://github.com/pytorch/fairseq/issues/789)). Often tuning some NCCL environment variables such as `NCCL_MIN_NRINGS`, `NCCL_SOCKET_NTHREADS` can help with the performance depending on the network, so we should document these suggestions in our [distributed docs](https://pytorch.org/docs/stable/distributed.html) to help users self-troubleshoot performance issues. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jlin27

**Comment by kwen2501** [comment]
Closing via PR https://github.com/pytorch/pytorch/pull/74006
