### ISSUE TITLE
[Gloo, MPI] DDP communication hook: getFuture()

### ISSUE THREAD

**Issue by sinannasir** [pytorch/pytorch#42048]
DDP communication hook implementation #39272 provides an API called `get_future` to retrieve a future associated with the completion of `c10d.ProcessGroupNCCL.work`. `get_future` API is currently only supported by NCCL #41596 , because most of the intensive models, where our gradient compression effort might be more useful, use NCCL. 

To support Gloo and MPI, we can modify some of the core ProcessGroupGloo and ProcessGroupMPI code to ensure we can do something similar there.

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @xush6528

**Comment by pritamdamania87** [comment]
Some of the gloo support is being added in https://github.com/pytorch/pytorch/pull/44436.

**Comment by SciPioneer** [comment]
Confirmed that this PR is already in @agolynski transition plan.

**Comment by SciPioneer** [comment]
Close this PR, as collective APIs are already supported by `getFuture()` on MPI and Gloo.
