### ISSUE TITLE
Implementing digitize

### ISSUE THREAD

**Issue by aayn** [pytorch/pytorch#42050]
Related to #38349.

cc @mruberry

**Comment by ngimel** [comment]
Is there an issue here? There doesn't seem to be a discussion needed (yet), so closing for now, reopen if you feel a separate issue is needed. Otherwise, just comment in #38349 that you are going to implement `digitize` is enough.

**Comment by ngimel** [comment]
FYI, this functionality is implemented as torch.bucketize #34577, so all you need is an alias.

**Comment by mruberry** [comment]
Thank you, @ngimel. Sorry @aayn, looks like bucketize snuck past me, too.
