### ISSUE TITLE
torch.svd_lowrank(A) seems to have quadratic space complexity

### ISSUE THREAD

**Issue by sigeisler** [pytorch/pytorch#42062]
## 🐛 Bug

I am trying to invoke a `torch.svd_lowrank(A)` on a *sparse* 659,574x659,574 matrix (with 6,416,728 non-zero elements). However, it seems like internally a dense matrix of the same shape is materialized:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-09172ebe9a68> in <module>
----> 1 torch.svd_lowrank(A)

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in svd_lowrank(A, q, niter, M)
    125         if (not set(map(type, tensor_ops)).issubset((torch.Tensor, type(None))) and has_torch_function(tensor_ops)):
    126             return handle_torch_function(svd_lowrank, tensor_ops, A, q=q, niter=niter, M=M)
--> 127     return _svd_lowrank(A, q=q, niter=niter, M=M)
    128 
    129 

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in _svd_lowrank(A, q, niter, M)
    159         else:
    160             B = matmul(A_t, Q_c) - matmul(M_t, Q_c)
--> 161         U, S, V = torch.svd(_utils.transpose(B))
    162         U = Q.matmul(U)
    163 

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1740151445904 bytes. Error code 12 (Cannot allocate memory)
```

I come to this conclusion because `1740151445904 / 659574^2 = 4`. So I assume the materialized matrix has an element size of 4 bytes.

## To Reproduce

1. Load big sparse matrix (I cannot share my dataset, but it is possible to reproduce the same behavior via the Reddit dataset via PyTorch geometric)
1. Execute `torch.svd_lowrank(A)`

For example, executing
```
import torch
from torch_geometric.datasets import Reddit

reddit = Reddit(root='data')[0]
n = len(reddit.y)
m = len(reddit.edge_index[0])
A = torch.sparse.FloatTensor(
    torch.cat((reddit.edge_index, n+reddit.edge_index, 2*n+reddit.edge_index), dim=-1),
    torch.ones(3*m).float()
)
torch.svd_lowrank(A)
```
raises the following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-09172ebe9a68> in <module>
----> 1 torch.svd_lowrank(A)

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in svd_lowrank(A, q, niter, M)
    125         if (not set(map(type, tensor_ops)).issubset((torch.Tensor, type(None))) and has_torch_function(tensor_ops)):
    126             return handle_torch_function(svd_lowrank, tensor_ops, A, q=q, niter=niter, M=M)
--> 127     return _svd_lowrank(A, q=q, niter=niter, M=M)
    128 
    129 

~/anaconda3/envs/pytorch1p5/lib/python3.7/site-packages/torch/_lowrank.py in _svd_lowrank(A, q, niter, M)
    159         else:
    160             B = matmul(A_t, Q_c) - matmul(M_t, Q_c)
--> 161         U, S, V = torch.svd(_utils.transpose(B))
    162         U = Q.matmul(U)
    163 

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1953816884100 bytes. Error code 12 (Cannot allocate memory)
```

## Expected behavior

`torch.svd_lowrank` should not have quadratic space complexity when the input is a sparse matrix.

## Environment

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-PCIE-32GB
Nvidia driver version: 450.51.05
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1
[pip3] torch-cluster==1.5.6
[pip3] torch-geometric==1.6.0
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.6
[pip3] torch-spline-conv==1.2.0
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch-cluster             1.5.6                    pypi_0    pypi
[conda] torch-geometric           1.6.0                    pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.6                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.6.1                py37_cu102    pytorch

cc @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @aocsa

**Comment by sigeisler** [comment]
Hi, does anybody have a good answer why this makes sense? As I understand the whole purpose is that `svd_lowrank` can handle large sparse matrices. Otherwise, I could simply, use `torch.svd(A.to_dense())` which is clearly undesirable.

If you give me a pointer I am happy to submit a pull request.

**Comment by pearu** [comment]
The algorithm of `torch.svd_lowrank` itself does not materialize the input sparse tensor. The memory problem appears to be in `torch.svd`. Here follows some diagnostics:

For the reddit dataset, the size of the input to `torch.svd` is `(6, 698895)`, which is not large, however, `torch.svd` fails on it:
```
>>> B_t = torch.randn(6, 698895)
>>> U, S, V = torch.svd(B_t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [enforce fail at CPUAllocator.cpp:66] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1953816884100 bytes. Error code 12 (Cannot allocate memory)
>>> 1953816884100**0.5/698895
2.0
```
Notice that allocation size is in the order of the size of the full tensor `V`: 698895 x 698895.
So, it seems as if the default `some=True` argument to `torch.svd` is not effective internally because the size for `V` ought to be `(698895, 6)`.

**Comment by pearu** [comment]
Verified: `some=True` is effective.

According to https://pytorch.org/docs/master/generated/torch.svd.html?highlight=svd#torch.svd :
```
If some is True (default), the method returns the reduced singular value decomposition
i.e., if the last two dimensions of input are m and n, then the returned U and V matrices
will contain only min(n,m) orthonormal columns.
```
which does not correspond to the implementation:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/LinearAlgebraUtils.h#L244-L245
according to which `VT` will have size `(n, n)`, although, the `VT` returned by `torch.svd` has the actual size `(n ,min(n, m))`.

I was able to apply `torch.svd_lowrank` to the given data set by changing the line
https://github.com/pytorch/pytorch/blob/master/torch/_lowrank.py#L146
to `if not (m < n):`. This fix needs verification, however, because it is not clear yet whether `torch.svd` has a bug or not.

**Comment by sigeisler** [comment]
@pearu great analysis!!! In retrospect, I should have been digging a little deeper :-)
