### ISSUE TITLE
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'

### ISSUE THREAD

**Issue by pr2tik1** [pytorch/pytorch#42078]
## 🐛 Bug
Error using the pytorch.hub API:
code: 

import torch
from torch import hub
resnet18_model = hub.load('pytorch/vision:master','resnet18',pretrained=True)

## Error
-----
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to /home/pratik/.cache/torch/hub/master.zip
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
      3 resnet18_model = hub.load('pytorch/vision:master',
      4 'resnet18',
----> 5 pretrained=True)

~/anaconda3/lib/python3.7/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    363     sys.path.insert(0, repo_dir)
    364 
--> 365     hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
    366 
    367     entry = _load_entry_from_hubconf(hub_module, model)

~/anaconda3/lib/python3.7/site-packages/torch/hub.py in import_module(name, path)
     73         spec = importlib.util.spec_from_file_location(name, path)
     74         module = importlib.util.module_from_spec(spec)
---> 75         spec.loader.exec_module(module)
     76         return module
     77     elif sys.version_info >= (3, 0):

~/anaconda3/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

~/anaconda3/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.cache/torch/hub/pytorch_vision_master/hubconf.py in 
      3 
      4 # classification
----> 5 from torchvision.models.alexnet import alexnet
      6 from torchvision.models.densenet import densenet121, densenet169, densenet201, densenet161
      7 from torchvision.models.inception import inception_v3

~/.cache/torch/hub/pytorch_vision_master/torchvision/__init__.py in 
      3 from .extension import _HAS_OPS
      4 
----> 5 from torchvision import models
      6 from torchvision import datasets
      7 from torchvision import ops

~/.cache/torch/hub/pytorch_vision_master/torchvision/models/__init__.py in 
     10 from .shufflenetv2 import *
     11 from . import segmentation
---> 12 from . import detection
     13 from . import video
     14 from . import quantization

~/.cache/torch/hub/pytorch_vision_master/torchvision/models/detection/__init__.py in 
----> 1 from .faster_rcnn import *
      2 from .mask_rcnn import *
      3 from .keypoint_rcnn import *

~/.cache/torch/hub/pytorch_vision_master/torchvision/models/detection/faster_rcnn.py in 
      5 import torch.nn.functional as F
      6 
----> 7 from torchvision.ops import misc as misc_nn_ops
      8 from torchvision.ops import MultiScaleRoIAlign
      9 

~/.cache/torch/hub/pytorch_vision_master/torchvision/ops/__init__.py in 
----> 1 from .boxes import nms, box_iou
      2 from .new_empty_tensor import _new_empty_tensor
      3 from .deform_conv import deform_conv2d, DeformConv2d
      4 from .roi_align import roi_align, RoIAlign
      5 from .roi_pool import roi_pool, RoIPool

~/.cache/torch/hub/pytorch_vision_master/torchvision/ops/boxes.py in 
     40 
     41 
---> 42 @torch.jit._script_if_tracing
     43 def batched_nms(
     44     boxes: Tensor,

AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
---
## Environment
---
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 20.04 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] numpydoc==0.9.1
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0a0+82fd1c8
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.16.2                   pypi_0    pypi
[conda] numpy-base                1.17.2           py37hde5b4d6_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] pytorch                   1.5.0               py3.7_cpu_0  [cpuonly]  pytorch
[conda] tensorflow-base           2.0.0           mkl_py37h9204916_0  
[conda] torchvision               0.6.0                  py37_cpu  [cpuonly]  pytorch

cc @suo @gmagogsfm

**Comment by dipanshug124** [comment]
Try downgrading ` torchversion ` to ` 0.4.0 `
pip uninstall torchvision
pip install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by suo** [comment]
Hi, I believe this is happening due to a version skew, where torchvision is expecting a newer version of PyTorch. We have a release to PyTorch coming very very soon that will probably fix this issue if you upgrade to it, or you can downgrade to an older version of TorchScript while you're waiting for it.

Going to close out this issue, but feel free to re-open if you have additional questions!

**Comment by emilearthur** [comment]
Tried solution at https://github.com/pytorch/pytorch/issues/42078#issuecomment-663971028 but did not work. Got the error below. 

ERROR: Could not find a version that satisfies the requirement torchvision==0.4.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.5.0+cpu, 0.5.0+cu100, 0.5.0+cu92, 0.6.0, 0.6.0+cpu, 0.6.0+cu101, 0.6.0+cu92, 0.6.1, 0.6.1+cpu, 0.6.1+cu101, 0.6.1+cu92, 0.7.0, 0.7.0+cpu, 0.7.0+cu101, 0.7.0+cu92)
ERROR: No matching distribution found for torchvision==0.4.0

**Comment by pr2tik1** [comment]
> Try downgrading `torchversion` to `0.4.0`
> pip uninstall torchvision
> pip install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

Didn't Fix the Issue, Thanks!

**Comment by pr2tik1** [comment]
> Hi, I believe this is happening due to a version skew, where torchvision is expecting a newer version of PyTorch. We have a release to PyTorch coming very very soon that will probably fix this issue if you upgrade to it, or you can downgrade to an older version of TorchScript while you're waiting for it.
> 
> Going to close out this issue, but feel free to re-open if you have additional questions!

I will upgrade to the newest version and check, btw is it out? torch==1.6 and torchvision==0.7.0??

**Comment by pr2tik1** [comment]
> Tried solution at [#42078 (comment)](https://github.com/pytorch/pytorch/issues/42078#issuecomment-663971028) but did not work. Got the error below.
> 
> ERROR: Could not find a version that satisfies the requirement torchvision==0.4.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0, 0.5.0+cpu, 0.5.0+cu100, 0.5.0+cu92, 0.6.0, 0.6.0+cpu, 0.6.0+cu101, 0.6.0+cu92, 0.6.1, 0.6.1+cpu, 0.6.1+cu101, 0.6.1+cu92, 0.7.0, 0.7.0+cpu, 0.7.0+cu101, 0.7.0+cu92)
> ERROR: No matching distribution found for torchvision==0.4.0

Yes, @emilearthur  faced the same issue of,

 No matching distribution found for torchvision==0.4.0

**Comment by pr2tik1** [comment]
Works well on upgrading torch and torchvision to the latest release. @emilearthur, Thanks @suo !

pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by sidml** [comment]
In my case using `pip install torchvision==0.7.0` instead of `torchvision==0.7.0+cpu` solved the error.

**Comment by TheKinginTheNorth-BrandonLuo** [comment]
> In my case using `pip install torchvision==0.7.0` instead of `torchvision==0.7.0+cpu` solved the error.

That's worked for me, thanks!

**Comment by Zheng-Tianyu** [comment]
In my case , I was used pip install torchvision==0.4.0 instead of torvision==0.7.0 to solve the error.

**Comment by mvolkmann** [comment]
I got past this by running `pip install torchvision==0.8.1`.

**Comment by KnitVikas** [comment]
1.3.0 version solved this problem for me

**Comment by DamilolaDecarls** [comment]
I got past this by pip install torchvision==0.1.7.

PyTorch version 1.7.0.

**Comment by fkjslee** [comment]
> Try downgrading `torchversion` to `0.4.0` pip uninstall torchvision pip install torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

At first, My pytorch is 1.9.0 for my RTX3090, but someone tell me to downgrade to 1.4.0 for fitting fairseq(a git rep), now another one tell me to downgrade to 0.4.0. How sad a story....

**Comment by jvictor42** [comment]
I have the same problem. Tried to use torchvision==0.4.0, torchvision==0.7.0, torchvision==0.8.1 and torchvision==0.11.0. None of the versions solve the problem. I use python 3.8.

**Comment by alpacaZa** [comment]
pip install --no-deps torchvision==0.5.0

https://blog.csdn.net/weixin_43899511/article/details/109534387

**Comment by ajavadov** [comment]
torch-1.11.0,  torchvision-0.12.0,  python 3.8.13. Worked for me.

**Comment by Yzh619** [comment]
I have the same problem. Tried to use torch==1.4, torchvision==0.5, torchvision==0.9 and torch==1.6, torchvision==0.6. None of them solve problem.  I use python==3.6 cuda 10.1, which vision should I use.

**Comment by mxz2013** [comment]
I tested "torch==1.7.0+cu110 torchvision==0.8.1+cu110"  and "torch==1.7.1+cu110 torchvision==0.8.2+cu110" same error. Can someone help?

**Comment by zyypostgrduate** [comment]
my version imformation 
(uoais) /mnt/workspace/uoais> python
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print("Installed PyTorch version:", torch.__version__)
Installed PyTorch version: 1.7.1
>>> import torchvision
>>> print(torchvision.__version__)
0.8.2
官方显示版本对应
torch | torchvision | Python
-- | -- | --
1.13 | 0.14 | >=3.7.2, <=3.10
1.12 | 0.13 | >=3.7, <=3.10
1.11 | 0.12 | >=3.7, <=3.10
1.10 | 0.11 | >=3.6, <=3.9
1.9 | 0.10 | >=3.6, <=3.9
1.8 | 0.9 | >=3.6, <=3.9
1.7 | 0.8 | >=3.6, <=3.9
版本没有对应问题为什么还是报错

File "/mnt/workspace/uoais/detectron2/detectron2/layers/wrappers.py", line 171, in <module>
    @torch.jit.script_if_tracing
AttributeError: module 'torch.jit' has no attribute 'script_if_tracing'
