### ISSUE TITLE
Documentation wrong for Linear layer initialization

### ISSUE THREAD

**Issue by louisabraham** [pytorch/pytorch#42083]
Documentation pretends that weights and bias are initialized uniformly in +-1/sqrt(in), whereas the code uses kaiming for weights and a kaiming variant for biases.

cc @jlin27 @albanD @mruberry

**Comment by Nikronic** [comment]
@louisabraham I think this thread might help you:
https://discuss.pytorch.org/t/clarity-on-default-initialization-in-pytorch/84696

**Comment by albanD** [comment]
Closing as the forum discussion clarifies the issue (they are the same in this case).
