### ISSUE TITLE
'UpsamplingBilinear2d' object has no attribute 'mode'

### ISSUE THREAD

**Issue by lidh15** [pytorch/pytorch#4208]
I trained a model with pytorch 0.1 several days ago and now I upgrade to 0.3, the model can't work anymore.

  File "F:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 366, in __getattr__
    type(self).__name__, name))

AttributeError: 'UpsamplingBilinear2d' object has no attribute 'mode'

What can I do?

**Comment by lidh15** [comment]
Anyone here???????

**Comment by apaszke** [comment]
Sorry, we’re a bit overwhelmed by the amount of forum threads, PRs and issues we have to respond to, so sometimes there are some delays.

Your problem looks like a tiny bug in `__setstate__` of that module

**Comment by lidh15** [comment]
OK, I rewrite my code and retrain it, but as others said, 0.3.0 on cpu is obviously slower than 0.1 (about 20~30%). I hope 0.4 can balance both cpu and gpu. I can only use cpu at present because my code need a large memory which gpu cannot hold.

**Comment by apaszke** [comment]
It's still a bug, so I'll leave this open

**Comment by apaszke** [comment]
Also, is your code anywhere online? We're actively investigating slowdowns and it would be helpful to see more examples

**Comment by lidh15** [comment]
frankly say, my code is ugly. So I don't push it online. It is just a naive CNN with conv, convtranspose, bathnorm, dropout and relu.

**Comment by ruiatelsevier** [comment]
Any new updates? I am getting the same error, and also only with GPU. If CPU it works fine.

**Comment by albanD** [comment]
Hi,

This is several years old so all the information here is outdated.
Please re-open a new issue if you still see this with latest version.
