### ISSUE TITLE
Import error from torch.distributed

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/pytorch#42092]
## To Reproduce

Steps to reproduce the behaviour:

This bug is strange as we are trying CI for Linux, Mac and Windows. I have followed the instructions from PyTorch webpage for installating and it gives the following error.
` AttributeError: module 'torch.distributed' has no attribute 'group'`
You can find the CI details [here ](https://github.com/lgvaz/mantisshrimp/pull/226)
I was able to reproduce this bug locally on windows 10 machine as well.
1. Trying to run `from torch.distributed import group` gives error. 

In all the 3 OS cases we are using torch CPU only. No CUDA.

## Expected behavior

1. It should work properly for windows as well.

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Tested working fine on Linux and MacOs, Bug with Windows
 - How you installed PyTorch (`conda`, `pip`, source): Pip
 - Python version: Bug in 3.6, 3.7 and 3.8 in Windows
 - CUDA/cuDNN version: CPU only
 - GPU models and configuration: No GPU
 - Any other relevant information:

## Additional context

I have attached the details of CI run. Please have a look and let us know if there is a work around.
[Here ](https://github.com/lgvaz/mantisshrimp/pull/226/checks?check_run_id=912270604) is the run 

Stack trace
```
ImportError while loading conftest 'D:\a\mantisshrimp\mantisshrimp\tests\conftest.py'.
tests\conftest.py:5: in <module>
    from mantisshrimp.models import efficientdet
mantisshrimp\models\efficientdet\__init__.py:1: in <module>
    from mantisshrimp.models.efficientdet.model import *
mantisshrimp\models\efficientdet\model.py:5: in <module>
    from effdet import get_efficientdet_config, EfficientDet, DetBenchTrain, unwrap_bench
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\effdet\__init__.py:3: in <module>
    from .evaluator import COCOEvaluator, FastMapEvalluator
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\effdet\evaluator.py:5: in <module>
    from .distributed import synchronize, is_main_process, all_gather_container
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\effdet\distributed.py:255: in <module>
    def all_gather_container(container, group=dist.group.WORLD):
E   AttributeError: module 'torch.distributed' has no attribute 'group'
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by oke-aditya** [comment]
Guess Highly linked with #42095. Maybe that is because this doesn't work. Is there any workaround for windows as of now ?

**Comment by mrshenli** [comment]
@oke-aditya you are right, `torch.distributed` does not support Windows yet. I am closing this issue and let's move discussions to #42095. Thanks.
