### ISSUE TITLE
Provide `out` parameter (buffer support) for `tensordot`

### ISSUE THREAD

**Issue by munael** [pytorch/pytorch#42102]
## 🚀 Feature
Add an `out` parameter to `tensordot` to allow using buffers.

## Motivation

Allow using buffers.

## Pitch

Rounds out the API. Also a first step towards making `tensordot` and `einsum` faster.

## Alternatives

N/A

## Additional context

N/A

**Comment by ngimel** [comment]
Thank you for request. We will accept a PR implementing it.
