### ISSUE TITLE
torch.distributed.launch: despite errors, training continues on some GPUs without printing any logs 

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#42107]
## 🐛 Bug

I launched a training of the [DETR](https://github.com/facebookresearch/detr) model on a server that automatically deletes all the files older than 30 days (which I hadn't realized before launching), which resulted in some unexpected behavior.

This is what happened, in order:

- I extracted the COCO dataset.
- I launched the training on 8 GPUs using `torch.distributed.launch`. I checked, it went well for 20-30 minutes.
- Because the timestamps of the extracted COCO files are from 2017, the server's cron started to delete the files.
- As a consequence, after about two hours, I got an error:

`FileNotFoundError: [Errno 2] No such file or directory: '/data/coco/train2017/000000315242.jpg'`

- A few hours later, I checked the GPU usage, and surprisingly the training was still running on 7/8 GPUs (except on the GPU 6). I thought maybe there was some new "fault tolerance" feature recently added to `torch.distributed.launch`, so I went to check the checkpoints: none, and the std logs: none. The 7 GPUs were still at 100%. This is not good at all. The main process on GPU 0 was responsible for printing out the logs and saving the checkpoints, but it didn't do any of these despite running at 100%.

What I would like to have is that the training stops whenever there's an error (which is supposed to be the case, by default).

## To Reproduce

1. Launch the training of DETR on COCO on multiple GPUs with `torch.distributed.launch`. (An alternative to DETR is the `torchvision`'s official reference example on [object detection](https://github.com/pytorch/vision/tree/master/references/detection).)
2. While the training is running, delete a bunch of training images.
3. Observe the results: some processes will obtain errors, some will continue to train (without saving anything).

## Expected behavior

Training should stop whenever there is an error.

## Environment

```
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
GCC version: (GCC) 7.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.1
[pip] torch==1.5.1+cu101
[pip] torchsummary==1.5.1
[pip] torchvision==0.6.1+cu101
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37h516909a_1    conda-forge
[conda] mkl_random                1.1.0            py37hb3f55d8_0    conda-forge
[conda] nomkl                     3.0                           0    https://repo.anaconda.com/pkgs/free
[conda] numpy                     1.18.1           py37h94c655d_0  
[conda] numpy-base                1.18.1           py37h2f8d375_1  
[conda] numpydoc                  0.9.1                      py_0
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
> A few hours later, I checked the GPU usage, and surprisingly the training was still running on 7/8 GPUs (except on the GPU 6). I thought maybe there was some new "fault tolerance" feature recently added to torch.distributed.launch, so I went to check the checkpoints: none, and the std logs: none. The 7 GPUs were still at 100%. This is not good at all. The main process on GPU 0 was responsible for printing out the logs and saving the checkpoints, but it didn't do any of these despite running at 100%.

This is most likely due to those processes hang at `all_reduce`, which would show CUDA utilization at 100% even though no real computation is running. 

[torchelastic](https://pytorch.org/elastic) is design to provide failure recovery for DDP. Can you check if this is sufficient for your use case?

**Comment by netw0rkf10w** [comment]
@mrshenli Unfortunately I don't want fault tolerance, I just want the faulty training to stop completely :( 

> This is most likely due to those processes hang at all_reduce, which would show CUDA utilization at 100% even though no real computation is running.

This is a bug, isn't it?

**Comment by mrshenli** [comment]
> Unfortunately I don't want fault tolerance, I just want the faulty training to stop completely 

Which backend are you using? If it is NCCL, can you try setting `NCCL_BLOCKING_WAIT` env var for all processes to 1, before calling `init_process_group` or creating the `ProcessGroupNCCL` instance? The test below can serve as an example. You can also control the timeout value in `init_process_group`.

https://github.com/pytorch/pytorch/blob/6ca5421a8fb92ab9fb264e3345b89896d8835438/test/distributed/test_c10d.py#L3515-L3527

**Comment by netw0rkf10w** [comment]
@mrshenli Great. As long as one can set a timeout that's fine. I'll try that. Thanks a lot!

**Comment by mrshenli** [comment]
@netw0rkf10w I am closing this issue for now. If `NCCL_BLOCKING_WAIT` does not work for you, please feel free to reopen this issue. Thanks.

**Comment by netw0rkf10w** [comment]
Hi @mrshenli. Over the last days I obtained a similar issue when using fairseq: **Failed jobs do not stop but continue to burn my GPU hours** :((

Let me explain two critical issues that I encountered.

1. For an exact same (multi-GPU) training, sometimes it works, but sometimes it yields: `RuntimeError    : work = group.allreduce([tensor], opts)Socket Timeout`. And the problem happens quite randomly. Would you have an explanation for that?
2. The second issue is even more frustrating: Even when the above issue happens, the training job does not stop! Last night I launched a training, and this morning when I checked the job, I was happy it was still running, until I checked the logs (`Socket Timeout`)! As you know I had already set `NCCL_BLOCKING_WAIT=1` because of the previous issue (and I have checked again, it's always 1), so the issue seems to lie elsewhere. Could you please tell me check this?

Thank you so much again for your help!
