### ISSUE TITLE
[Build Failure] Wrong copy path for shared DNNL

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#42115]
## 🐛 Bug

`bin/dnnl.lib` is not available with `-DDNNL_LIBRARY_TYPE=SHARED` or `-DMKLDNN_LIBRARY_TYPE=SHARED`.
Instead it will be available as `bin/dnnl.dll` and `lib/dnnl.lib` (import lib).

Here's the error:
```
[1/2] cmd.exe /C "cd /D D:\roaster-scratch\pytorch\build\third_party\ideep\mkl-dnn\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/roaster-scratch/pytorch/build/bin/dnnl.lib D:/roaster-scratch/pytorch/build/bin/mkldnn.lib"
FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/compat_libs
cmd.exe /C "cd /D D:\roaster-scratch\pytorch\build\third_party\ideep\mkl-dnn\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/roaster-scratch/pytorch/build/bin/dnnl.lib D:/roaster-scratch/pytorch/build/bin/mkldnn.lib"
Error copying file "D:/roaster-scratch/pytorch/build/bin/dnnl.lib" to "D:/roaster-scratch/pytorch/build/bin/mkldnn.lib".
```

And this is what's available instead:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/5203025/88568520-b1208d00-d06b-11ea-8efd-d9583e61a616.png">
<img width="668" alt="image" src="https://user-images.githubusercontent.com/5203025/88568557-bb428b80-d06b-11ea-93df-d88936e4f0d7.png">

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win Server 2019
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja
 - Python version: 3.8.5

## Additional context

We run into this issue because:
1. We try to pack pytorch as nuget on Windows.
2. There's per-package size limit for our storage.
3. We found DNNL is built as static lib and it's huge (1.1 GB), while we actually have it available externally as shared lib.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by pinzhenx** [comment]
We'll look into that. Copy @emfomenk @vpirogov

**Comment by xkszltl** [comment]
Here's the line triggering this error:
https://github.com/oneapi-src/oneDNN/blob/ab549349fc473f35e9bc41ed4d6bff5b1eaabfe0/src/CMakeLists.txt#L150-L156

**Comment by xkszltl** [comment]
When DNNL built by itself, this line works fine.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/5203025/88573034-b33a1a00-d072-11ea-8539-9157a2034693.png">
However in PyTorch context it fails.

Besides, to me it's strange that the static lib is in `bin/`.

**Comment by pinzhenx** [comment]
As "mkldnn" has been rebranded to "dnnl", the compat_lib was used to generate the lib with the old name for backward compatibility.

In pytorch, I guess you could just skip building `compat_lib`. Currently, we don't have such an option to skip it. But as a quick fix, you could remove three blocks in `ideep/mkl-dnn/CMakeLists.txt` as suggested in [this comment](https://github.com/oneapi-src/oneDNN/issues/768#issuecomment-651843917)

**Comment by xkszltl** [comment]
@pinzhenx 
This is my approach for now: https://github.com/xkszltl/Roaster/commit/84965f7679eddf3c852bf85c7ebff7b90e0eb7cd
```
(cat "third_party/ideep/mkl-dnn/src/CMakeLists.txt") -replace '\$<TARGET_FILE_DIR:\${LIB_NAME}>','$<TARGET_FILE_DIR:${LIB_NAME}>/../lib' | Out-File -Encoding UTF8 "third_party/ideep/mkl-dnn/src/CMakeLists.txt.patching"
```

Basically this is Windows version of `sed 's/\($<TARGET_FILE_DIR:${LIB_NAME}>\)/\1\/..\/lib/'`.

**Comment by pinzhenx** [comment]
@CaoZhongZ

**Comment by CaoZhongZ** [comment]
@xkszltl It's odd, why $<TARGET_FILE_DIR:${LIB_NAME}> gave us a wrong directory in your building environment. The generator expression supposed to handle all things correctly.

**Comment by CaoZhongZ** [comment]
@xkszltl https://github.com/oneapi-src/oneDNN/compare/master...CaoZhongZ:cmakefix?expand=1

Can this patch fix your problem?

**Comment by xkszltl** [comment]
LGTM, will test

**Comment by xkszltl** [comment]
Verified. PR works for me

**Comment by xkszltl** [comment]
Once merge, please also update repos in dependency chain of pytorch->ideep->dnnl

**Comment by CaoZhongZ** [comment]
That'll need a little time. Upgrading DNNL under ideep may need align with DNNL releases.

**Comment by mszhanyi** [comment]
@CaoZhongZ , thank you fixing this issue very much. I'm assign the owner to you.

**Comment by xkszltl** [comment]
Close since ideep has been updated.

**Comment by xkszltl** [comment]
```
-- Configuring done
-- Generating done
-- Build files have been written to: D:/roaster-scratch/pytorch/build
[1/193] cmd.exe /C "cd /D D:\roaster-scratch\pytorch\build\third_party\ideep\mkl-dnn\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/roaster-scratch/pytorch/build/bin/dnnl.lib D:/roaster-scratch/pytorch/build/bin/mkldnn.lib && "C:\Program Files\CMake\bin\cmake.exe" -E touch CMakeFiles/compat_libs"
FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/compat_libs
cmd.exe /C "cd /D D:\roaster-scratch\pytorch\build\third_party\ideep\mkl-dnn\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy D:/roaster-scratch/pytorch/build/bin/dnnl.lib D:/roaster-scratch/pytorch/build/bin/mkldnn.lib && "C:\Program Files\CMake\bin\cmake.exe" -E touch CMakeFiles/compat_libs"
Error copying file "D:/roaster-scratch/pytorch/build/bin/dnnl.lib" to "D:/roaster-scratch/pytorch/build/bin/mkldnn.lib".
```

I thought https://github.com/oneapi-src/oneDNN/commit/2bc4d3c3278ab9e5743d0e83b09574b140d6de3f was released in 1.6.2 but not.
Looks like it won't be there before 1.7:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/5203025/98025833-2d81f380-1e45-11eb-967f-11215780edb5.png">

**Comment by emfomenk** [comment]
The fix should be a part of oneDNN [v1.6.4](https://github.com/oneapi-src/oneDNN/releases/tag/v1.6.4) and beyond.
From release notes:

> This is a patch release containing the following changes to v1.6.3:
>
> ...
> Fixed build issue on Windows for the case when oneDNN is built as submodule (oneapi-src/oneDNN@2fceddf)
> ...

**Comment by xkszltl** [comment]
Great!
Can someone update the pytorch/ideep submodule chain accordingly?

**Comment by CaoZhongZ** [comment]
We'll update v1.7 soon for major performance fix 😄
