### ISSUE TITLE
Speech embedding LSTM model giving different results during inference(I am using model.eval() )

### ISSUE THREAD

**Issue by ashu170292** [pytorch/pytorch#42116]
I am using an LSTM model with 3 hidden layers to produce speech embeddings. The input to the model are MFCC features taken on a window of 0.025 seconds and the hop length is 0.01 seconds. I have two inputs for inference and their size is as follows:

1. torch.Size([54, 24, 40])
2. torch.Size([439, 24, 40])
The first 18 frames in both the inputs is same. I load the model as follows:
```
embedder_net = SpeechEmbedder()
embedder_net.load_state_dict(torch.load(hp.model.model_path))
embedder_net.eval()
```
The state_dict looks like following:
```
LSTM_stack.weight_hh_l0 	 torch.Size([3072, 768])
LSTM_stack.bias_ih_l0 	 torch.Size([3072])
LSTM_stack.bias_hh_l0 	 torch.Size([3072])
LSTM_stack.weight_ih_l1 	 torch.Size([3072, 768])
LSTM_stack.weight_hh_l1 	 torch.Size([3072, 768])
LSTM_stack.bias_ih_l1 	 torch.Size([3072])
LSTM_stack.bias_hh_l1 	 torch.Size([3072])
LSTM_stack.weight_ih_l2 	 torch.Size([3072, 768])
LSTM_stack.weight_hh_l2 	 torch.Size([3072, 768])
LSTM_stack.bias_ih_l2 	 torch.Size([3072])
LSTM_stack.bias_hh_l2 	 torch.Size([3072])
projection.weight 	 torch.Size([256, 768])
projection.bias 	 torch.Size([256])
```
When I use the model for inference on the two inputs, I get results of the following size:

1. torch.Size([54, 256])
2. torch.Size([439, 256])

Since the first 18 frames are same in both the inputs, I expect the first 18 embeddings in both results to be the same. But this is not the case.

In fact the results in both cases are very different from the result I get when I just take frames 18 frames as the input. Any idea why that would happen?

Help appreciated

cc @zou3519

**Comment by ngimel** [comment]
Please provide a self-contained script that would demonstrate the problem.

**Comment by ashu170292** [comment]
Thanks @ngimel for your message. Following is the script:

```
import torch
import torch.nn as nn
```
```
class SpeechEmbedder(nn.Module):
    
    def __init__(self):
        super(SpeechEmbedder, self).__init__()    
        self.LSTM_stack = nn.LSTM(40, 768, num_layers=3, batch_first=True)
        for name, param in self.LSTM_stack.named_parameters():
            if 'bias' in name:
                nn.init.constant_(param, 0.0)
            elif 'weight' in name:
                nn.init.xavier_normal_(param)
        self.projection = nn.Linear(768, 256)
        
    def forward(self, x):
        x, _ = self.LSTM_stack(x.float()) #(batch, frames, n_mels)
        #only use last frame
        x = x[:,x.size(1)-1]
        x = self.projection(x.float())
        x = x/torch.norm(x)
        return x
```

The input files('inp1.pt' and 'inp2.pt') and models are present at the following location:
https://github.com/ashu170292/learning-pytorch/tree/master/files


```
embedder_net = SpeechEmbedder()
##Change location of model
embedder_net.load_state_dict(torch.load('final_epoch_950_batch_id_135.model'))
embedder_net.eval()
```
```
inp1 = torch.load('inp1.pt')
inp2 = torch.load('inp2.pt')
##Checking that first 18 frames in both inputs is same
print (torch.equal(inp1[:18],inp2[:18]))
```
Inference results on first input :
```
res1 =embedder_net(inp1)
```
Inference results on second input:
```
res2 = embedder_net(inp2)
```
The first 18 embeddings should be equal as the first 18 frames of the input are equal but tthis is not the case:
```
print (torch.equal(res1[:18],res2[:18]))
```

**Comment by ngimel** [comment]
Since you are using `norm(x)` in your module, the values for all batch elements contribute to it, so the value of norm(x) is different for inp1 and inp2, and results are expected to be different.
Please use discuss.pytorch.org for questions.
