### ISSUE TITLE
memory leak when eval with multithread environment

### ISSUE THREAD

**Issue by ysyyork** [pytorch/pytorch#42111]
## 🐛 Bug

When I serve the model using flask with multi threaded mode on, the CPU memory keep growing as requests come in. But if I turn the flask to single thread. There is no memory leak. Also I pulled out that piece of inference code to run by a single thread script. Didn't see any memory leak. It seems the model.forward doesn't work with multi threaded environment? can anyone confirm this? 

## To Reproduce

follow this official tutorial and you will get the bug. https://pytorch.org/tutorials/intermediate/flask_rest_api_tutorial.html

## Expected behavior

In multi-threaded env, model initialized once and should be able to be reused without memory leak across threads. 

## Environment

You can get the script and run it with:

 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): no
 - Python version: python 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: I'm actually using detectron2 lib 
 - Any other relevant information:

**Comment by nistarlwc** [comment]
Try to use ```app.run(..., threaded=True)```
But GPU memory leak, do you have solution?

**Comment by fatfishZhao** [comment]
Hi, I'm facing the similar memory leaking problem when using multithread inference. Did you solved this problem?
