### ISSUE TITLE
[feature request] support for division in quantization

### ISSUE THREAD

**Issue by kodonnell** [pytorch/pytorch#42130]
As far as I can see, division isn't supported in quantization (tensor / tensor or tensor / scalar or scalar / tensor) because it's not in [nn.quantized.FloatFunctional](https://github.com/pytorch/pytorch/blob/96aaa311c0251d24decb9dc5da4957b7c590af6f/torch/nn/quantized/modules/functional_modules.py). With a division (overloaded python, or `torch.div`, `FloatFunctional().mul(a, torch.pow(b, -1))`) quantization fails with errors like

```
    fi = torch.div(num, denom)
RuntimeError: Could not run 'aten::div.Tensor' with arguments from the 'QuantizedCPU' backend. 'aten::div.Tensor' is only available for these backends: [CPU, CUDA, SparseCPU, SparseCUDA, Autograd, Profile].
```

Could we please add division support (or document work-arounds if they exist)? 

NB I've tried subclassing `FloatFunctional` as per the pattern i.e.

```
def div(self, x, y):
    r = torch.div(x, y)
    r = self.activation_post_process(r)
    return r
```

But no luck, so I'm guessing there's some underlying code involved.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
hi @kodonnell , we don't have a kernel yet for quantized division (it can be considered for future additions).  A workaround you could use in the meanwhile is surround division with `DeQuantStub` and `QuantStub` to let the computation happen in floating point.

**Comment by kodonnell** [comment]
Thanks @vkuzo - that's a clever work-around, and worked fine. I also just realised that in my case I can just replace division with multiplication and, on retraining, the weights should learn to be the inverse of themselves. (Or, if you have to do it on e.g. a pretrained model with division, you could just use a multiplication but edit the weights manually to be their inverse, achieving the same thing.)

Happy for this issue to be closed if you don't need it as a backlog item.

**Comment by vkuzo** [comment]
glad it helped.  Closing for now, we might revisit this in the future.
