### ISSUE TITLE
GIL deadlock in exit handler

### ISSUE THREAD

**Issue by froody** [pytorch/pytorch#42132]
## 🐛 Bug

torch::autograd::PyNode::release_variables() tries to acquire the python GIL during Py_Exit but it is already held by the same thread

## To Reproduce

1. Checkout https://github.com/facebookresearch/fairscale/tree/deadlock-testcase
2. Run pytest -k test_pipe_layer -s

backtraces at time of deadlock: https://gist.github.com/froody/ecc8bc849b8a95f89218fd5b6dc2ecd6
gdb session: https://gist.github.com/froody/673e6900838d6eee83466ed3541b93b9

## Expected behavior

The test should fail with an exception, but instead it deadlocks

## Environment

PyTorch version: 1.7.0.dev20200721
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0.dev20200721
[pip3] torchvision==0.8.0.dev20200721
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.1.0            py37hc1659b7_1    conda-forge
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] pytorch                   1.7.0.dev20200721 py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.8.0.dev20200721      py37_cu101    pytorch-nightly

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by froody** [comment]
Maybe related to https://github.com/pytorch/pytorch/issues/39855

**Comment by albanD** [comment]
@froody forgot about this but https://github.com/pytorch/pytorch/pull/57488 should have fixed it.
Feel free to re-open if that happens again!
