### ISSUE TITLE
Cannot understand torch._C._dist_init_process_group() in the source code of dist.init_process_group()

### ISSUE THREAD

**Issue by OnezeroW** [pytorch/pytorch#4214]
I am learning to use `torch.distributed` recently. I read the [Initialization Methods](http://pytorch.org/tutorials/intermediate/dist_tuto.html#initialization-methods) in the Pytorch tutorial. However, when I go deep into the source code of `init_process_group` [https://github.com/pytorch/pytorch/blob/master/torch/distributed/__init__.py#L44-L101](https://github.com/pytorch/pytorch/blob/master/torch/distributed/__init__.py#L44-L101) , 
I find `torch._C._dist_init_process_group(backend, init_method, world_size, group_name, rank)` quite confusing.
Where can I locate `torch._C._dist_init_process_group`? What really happens in this function?

**Comment by apaszke** [comment]
This is the entry point to C++. The code [is here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/Module.cpp#L88-L116).

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

**Comment by OnezeroW** [comment]
Thanks. I will be careful next time.


________________________________
发件人: Adam Paszke <notifications@github.com>
发送时间: 2017年12月17日 20:51
收件人: pytorch/pytorch
抄送: OnezeroW; Author
主题: Re: [pytorch/pytorch] Cannot understand torch._C._dist_init_process_group() in the source code of dist.init_process_group() (#4214)


This is the entry point to C++. The code is here<https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/Module.cpp#L88-L116>.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on our forums<discuss.pytorch.org>.

―

**Comment by YuanhuiCheng** [comment]
> This is the entry point to C++. The code [is here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/Module.cpp#L88-L116).
> 
> Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

Hi, the given C++ entry link is invalid now, could u tell where to find the new entry to `init_process_group()`?
