### ISSUE TITLE
share_memory() support for at::Tensor

### ISSUE THREAD

**Issue by bgedik** [pytorch/pytorch#42142]
## 🚀 Feature
In the PyTorch Python API, it is possible to move a tensor to shared memory via calling the `Tensor.share_memory_()` function. I could not find similar functionality on the  C++ side using `at::Tensor`.

## Motivation
I have code that reads tensors from network on the C++ side (using multiple threads). These tensors are then pulled into Python land and go through Python multi-processing transforms. I want to avoid copying tensors across process boundaries, so that the multi-processing transforms can be executed efficiently. To do this, I need to move the tensor storage to shared memory. However, for efficiency purposes, I want to move the tensor memory to shared memory on the C++ side, where I have a thread pool for reading tensors from the network. 

Another potential area where I am planning to use this feature is out-of process execution of PyTorch scripts in C++ land, where again, we can use shared memory to minimize the cost of transferring tensors across processes.

## Pitch

What I want is a `share_memory()` method on `at::Tensor`, mimicking the one on PyTorch tensors.

## Additional context

cc @yf225 @glaringlee

**Comment by xunnanxu** [comment]
https://github.com/pytorch/pytorch/pull/95228

**Comment by xunnanxu** [comment]
#95228 merged. Will have a separate PR to expose that to `at::Tensor`
