### ISSUE TITLE
[bug] Binomial distribution has small chance of returning -1

### ISSUE THREAD

**Issue by jamestwebber** [pytorch/pytorch#42153]
## 🐛 Bug

As it says in the title, I found that the binomial sampler can occasionally return `-1` (about 1 in a 100M trials). This is probably mostly a small issue, but it's a big issue if you're computing log probabilities from the output.

I created PR #38456 for this, which was then merged. Unfortunately the bug still appears which means that my fix was not relevant (I was not able to build pytorch at the time for testing, that's my bad!). I think that PR can remain merged as its harmless, but a fix for the bug is still needed.

Looking at the code again, my fix was obviously wrong because the repro case below doesn't even go through the BTRS code path 🤦

<details>
<summary>edit: this part was wrong, see comments below</summary>
I believe the bug is in [`binomial_inversion`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.h#L159-L177), specifically line 169. If the result of the standard uniform is very close to 1 (like, `> 0.9999999`) then `log(U)` evaluates to 0 and `geom_sum` doesn't increase for a round. The rate of this matches pretty closely with the rate I observe the bug, which is comforting because last time I had no friggin' idea why it was happening.

edit to add: in my previous PR I said this was only on CUDA, but I think I just wasn't patient enough to sample enough on the CPU. Now I see it there as well.
</details>

## To Reproduce

This reliably returns `False`:

```python
(
    torch.distributions.Binomial(
        total_count=torch.tensor(1.0).cuda(), probs=torch.tensor(0.9).cuda()
    ).sample(torch.Size((1000000000,))) >= 0
).all()
```

This also reliably returns `False`:

```python
(
    torch.distributions.Binomial(
        total_count=torch.tensor(1.0).cuda(), probs=torch.tensor(0.1).cuda()
    ).sample(torch.Size((1000000000,))) < 2
).all()
```

(see [Bender's nightmare](https://www.youtube.com/watch?v=MOn_ySghN2Y))

## Expected behavior

Should return `True`!

## Environment

 - PyTorch Version (e.g., 1.0): Running pytorch-nightly 1.7.0.dev20200713
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Titan Xp 
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @vincentqb @fritzo @neerajprad @alicanb @vishwakftw @pbelevich

**Comment by ngimel** [comment]
High priority for silent wrong result

**Comment by ngimel** [comment]
I doubt log(u) being rounded to 0 is the culprit. log of 1-2**(-24), (the largest representable fp32 number less than 1) is  -5.9605e-8, so unless uniform returns 1. (which it should not) the log term should be non-zero. So my suspicion is, standard_uniform is not 1-exclusive.

**Comment by jamestwebber** [comment]
> I doubt log(u) being rounded to 0 is the culprit. log of 1-2**(-24), (the largest representable fp32 number less than 1) is -5.9605e-8, so unless uniform returns 1. (which it should not) the log term should be non-zero. So my suspicion is, standard_uniform is not 1-exclusive.

That makes sense...I was trying to reproduce in a notebook but I imagine that's not using the same primitives for RNG.

A fix for the binomial algorithm would be to always add at least 1 (the zero case should be adding a 1). But if standard_uniform has a bug it's probably better to fix that.

**Comment by ngimel** [comment]
I could not repro on the cpu, on cuda using curand_uniform is the root cause : https://github.com/pytorch/pytorch/blame/5ed7cd0025661c39ae03ce4982958d91fa16baf3/aten/src/ATen/native/cuda/Distributions.cu#L72
curand_uniform is zero-exclusive one-inclusive.

**Comment by jamestwebber** [comment]
> I could not repro on the cpu
Ah you are right, I thought I had repro'd on CPU but must have been looking at a related test with different behavior.
