### ISSUE TITLE
Weird result multiplying a cpu tensor by a cuda:1 tensor 

### ISSUE THREAD

**Issue by lferraz** [pytorch/pytorch#42161]
## 🐛 Bug

Weird behaviour multiplying two tensors (one in `cpu` and the other one in `cuda`).
If the `cuda` tensor is in `cuda:0` both of them can be multiplied. 
If the `cuda` tensor is in `cuda:1` both of them can be multiplied but the result is wrong. 

## To Reproduce

Example of an operation between a tensor `a` in `cuda` and another tensor `b` in `cpu`.

This code provides a correct result:
```
import torch
a = torch.tensor([3., 4.]).to(torch.device('cuda:0'))
b: torch.Tensor = torch.tensor(2.)
b * a
```
**Correct result**: tensor(**[6., 8.]**, device='cuda:0')

This code provides an incorrect result:
```
import torch
a = torch.tensor([3., 4.]).to(torch.device('cuda:1'))
b: torch.Tensor = torch.tensor(2.)
b * a
```

**Incorrect result**: tensor(**[3., 4.]**, device='cuda:1')

## Expected behavior

Error in both cases since `b` is not in the same device as `a` or providing the correct result in both cases. 

## Environment

NOTE: also tested with pytorch 1.5.1

PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 440.64.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchfile==0.1.0
[conda] blas                      2.16                        mkl    conda-forge
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ignite                    0.3.0                    py37_0    pytorch
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.2                      256    conda-forge
[conda] numpy                     1.18.4           py37h8960a57_0    conda-forge
[conda] pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchreid                 1.0.9                    pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    pypi

cc @ngimel

**Comment by zou3519** [comment]
Thanks for the bug report. I can repro the problem on 1.5.1. It appears to be fixed on master but I am not sure which PR fixed it.
```
[ins] In [2]: import torch
         ...: a = torch.tensor([3., 4.]).to(torch.device('cuda:1'))
         ...: b: torch.Tensor = torch.tensor(2.)
         ...: b * a
Out[2]: tensor([6., 8.], device='cuda:1')
```

**Comment by ngimel** [comment]
It was fixed in https://github.com/pytorch/pytorch/pull/39956. Closing, please reopen if needed.
