### ISSUE TITLE
btrifact fails with Variable arguments

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/pytorch#4217]
I'm having trouble getting `torch.btrifact` to work with Variable arguments; either I'm doing something wrong or there's a bug. The trouble seems to be with the `info` argument; there is no plausible type I can think of for `info` that works in the Variable case.

With Tensors, we can either ignore the `info` argument or set it to be an `IntTensor`:

```python
import torch
from torch.autograd import Variable

N, M = 2, 3
A = torch.randn(N, M, M)

# A as FloatTensor, no info
A_LU, pivots = torch.btrifact(A)

# A as FloatTensor, info as IntTensor
info = torch.IntTensor(M)
A_LU, pivots = torch.btrifact(A, info=info)
```

Making A a Variable and not passing `info` crashes:
```python
A_var = Variable(A)
A_LU, pivots = torch.btrifact(A_var)
# RuntimeError: Expected a Tensor of type Variable[torch.FloatTensor]
# but found an undefined Tensor for argument #1 'info'
```

Making A a Variable and `info` a `Variable[IntTensor]` crashes:
```python
A_var = Variable(A)
info = Variable(torch.IntTensor(M))
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: Expected object of type Variable[torch.FloatTensor]
# but found type Variable[torch.IntTensor] for argument #1 'info'
```

Making A a Variable and `info` a `Variable[FloatTensor]` crashes:
```python
A_var = Variable(A)
info = Variable(torch.FloatTensor(M))
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: Expected object of type torch.IntTensor
# but found type torch.FloatTensor for argument #1 'info'
```

Going crazy and making A a Variable and `info` an `IntTensor` also crashes:
```python
A_var = Variable(A)
info = torch.IntTensor(M)
A_LU, pivots = torch.btrifact(A_var, info=info)
# RuntimeError: btrifact(): argument 'info' must be Variable, not torch.IntTensor
```
(Full test script here: https://gist.github.com/jcjohnson/0ae6b433e07d0117016361d8ed9b0410)

Is this a bug, or am I misunderstanding how `torch.btrifact` should be used?

I'm using PyTorch version 0.3.0.post4 installed via pip with Python 3.5.2 on Ubuntu 16.04.

**Comment by SsnL** [comment]
Looking into this
