### ISSUE TITLE
Advanced indexing inconsistent between LongTensor and ByteTensor

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4219]
```
>>> x = torch.Tensor(5, 5, 5)
>>> y = torch.LongTensor([0, 2, 4])
>>> x[y, :, :]

(0 ,.,.) = 
 -1.0020e-19  4.5639e-41 -1.0020e-19  4.5639e-41         nan
         nan  7.0387e+28  1.8496e+31  7.5551e+31  1.7753e+28
  2.0535e-19  7.3909e+22  1.8589e+34  7.2065e+31  1.2708e+31
  4.5145e+16  2.1017e-19  1.8489e+20  3.1024e+27  1.9943e-19
  1.8736e-19  3.0305e+24  1.9436e-19  1.9432e-19  7.0062e+22

(1 ,.,.) = 
  2.2140e-10  7.5661e+28  2.1136e-10  1.7753e+28  4.4724e+21
  1.8220e-10  7.0362e+22  2.0683e-10  6.2655e+22  4.7428e+30
  4.6162e+24  2.7123e-09  1.9810e-41  0.0000e+00  0.0000e+00
  0.0000e+00  3.8255e-43  0.0000e+00  1.0011e-38  0.0000e+00
 -1.0020e-19  4.5639e-41         nan  0.0000e+00  7.0387e+28

(2 ,.,.) = 
  1.8469e+20  2.3340e-09  6.9771e+22  7.5551e+31  7.1463e+22
  4.2324e+21  7.2728e+22  1.8501e+20  3.3081e+24  2.0866e-10
  2.8763e+20  8.4820e+26  1.0899e+27  1.8448e+28  1.0615e+21
  1.8017e+25  1.9205e+31  7.1480e+22  2.2140e-10  7.5661e+28
  2.1136e-10  1.7753e+28  4.4724e+21  1.8220e-10  7.0362e+22
[torch.FloatTensor of size 3x5x5]

>>> y = torch.ByteTensor([0, 2, 4])
>>> x[y, :, :]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Performing basic indexing on a tensor and encountered an error indexing dim 0 with an object of type torch.ByteTensor. The only supported types are integers, slices, numpy scalars, or if indexing with a torch.LongTensor or torch.ByteTensor only a single Tensor may be passed.
```

**Comment by fmassa** [comment]
If you meant using Boolean indexing on a subset of the dimensions of a tensor, I believe this is already implemented in master for variables

**Comment by ezyang** [comment]
Perhaps I misunderstood the semantics of indexing with ByteTensor? I thought it would be like LongTensor except the indices had to fit in 0-255. Maybe not?

**Comment by apaszke** [comment]
No, ByteTensor is like boolean indexing (masking)

**Comment by fmassa** [comment]
Oh, no, boolean indexing means that only non-zero entries will be considered for indexing.
So
```python
a = torch.rand(2, 2, 2)
a[a > 0.5] = 0
print(a[a > 0.5]) # 1d tensor
```
The equivalent in terms of LongTensor indexing would be somewhat similar to using `nonzero` in the boolean array.

**Comment by ezyang** [comment]
OK, maybe there's an opportunity to improve the error message here then.

BTW bug report was prompted by this discuss: https://discuss.pytorch.org/t/indexing-error-object-of-type-variable-torch-cuda-bytetensor/11262/2

**Comment by ozancaglayan** [comment]
I think this is confusing. I was also expecting that it works exactly the same way except the range is btw 0-255. In numpy, a True/False `bool` dtype is around when doing boolean indexing but you can also index for example with an array of dtype=uint8.

**Comment by justinchiu** [comment]
I'm getting:
```
>>> x = torch.arange(0, 25).view(5,5); longidx = torch.LongTensor([0,1]); byteidx = torch.ByteTensor([1,1,0,0,0])
>>> print(x[longidx]); print(x[:, longidx])

 0  1  2  3  4
 5  6  7  8  9
[torch.FloatTensor of size 2x5]


  0   1
  5   6
 10  11
 15  16
 20  21
[torch.FloatTensor of size 5x2]

>>> x[byteidx]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: inconsistent tensor size, expected src [5 x 5] and mask [5] to have the same number of elements, but got 25 and 5 elements respectively at /n/home13/jchiu/python/pytorch/aten/src/TH/generic/THTensorMath.c:207
>>> x[:, byteidx]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Performing basic indexing on a tensor and encountered an error indexing dim 1 with an object of type torch.ByteTensor. The only supported types are integers, slices, numpy scalars, or if indexing with a torch.LongTensor or torch.ByteTensor only a single Tensor may be passed.
```
I think byte masking like this would be pretty useful, am I doing something wrong?
I'm on `torch.__version__ = '0.4.0a0+43ab911'`

**Comment by imsrgadich** [comment]
@soumith any resolution on this? I'm facing a similar issue. 

https://discuss.pytorch.org/t/find-indices-with-value-zeros/10151/4?u=imsrgadich

**Comment by fmassa** [comment]
@imsrgadich if you want to use `nonzero`, you need to squeeze the last dimension first.
Or, you can directly pass the boolean mask and it will work just fine on v0.4
```python
a = torch.rand(4, 4, 4)
mask = torch.rand(4) > 0.5
b = a[mask]
# equivalent to
c = a[mask.nonzero().squeeze(1)]
```

**Comment by fmassa** [comment]
Also, @ezyang are we planning on adding bool tensors in C10? I think we should consider that, and make the boolean indexing use it instead of `ByteTensor`

**Comment by ezyang** [comment]
I think we'd need to agree on what the semantics of BoolTensor would be

**Comment by fmassa** [comment]
Similar semantics as in numpy? The result of comparison operators return bool instead of byte, a bunch of math operations are not supported in book (only logical operations)?
I'm not sure if there is a strong case for it though...
