### ISSUE TITLE
get rid of requiring to do super.__init__ in nn.Container subclasses

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#422]
This seems like its something that users'll forget to do, and we might get a lot of subtle bug reports because of this. Seems like a good usability fix early on.

**Comment by apaszke** [comment]
Right now if you try to assign any module or parameter to a `nn.Module` without calling `super().__init__()` it will raise an error. Since I can't think of any cases when you don't do this in `__init__` I'm closing this issue.
