### ISSUE TITLE
pytorch istft runs slower than torchaudio istft especially at higher n_fft

### ISSUE THREAD

**Issue by apeguero1** [pytorch/pytorch#42213]
## 🐛 Bug

There seems to be a significant performance drop after migrating the istft from torchaudio to pytorch. 
migration discussed here [#34827](https://github.com/pytorch/pytorch/pull/34827)
I've also noticed the performance gap increases with greater n_fft.

## To Reproduce

pip install torch==1.6.0

```
import torch
import time
n_fft = 2**15
x = torch.rand(size=[1, n_fft//2 + 1, 10, 2])
start = time.time()
y = torch.functional.istft(x,n_fft)
end = time.time()
print(end - start)
```

pip install torchaudio==0.5.1

```
import torch
import torchaudio
import time
n_fft = 2**15
x = torch.rand(size=[1, n_fft//2 + 1, 10, 2])
start = time.time()
y = torchaudio.functional.istft(x,n_fft)
end = time.time()
print(end - start)
```

## Expected behavior
I would expect similar timings between:

torch.functional.istft in torch==1.6.0
and
torchaudio.functional.istft in torchaudio==0.5.1  

## Environment running torch.functional.istft 
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchaudio==0.6.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.1+cu101
[conda] Could not collect

## Environment running torchaudio.functional.istft 
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1+cu101
[pip3] torchaudio==0.5.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.6.1+cu101
[conda] Could not collect

## Additional context
Both environments are from google colab 

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ngimel

**Comment by mthrok** [comment]
Hi @apeguero1 

Thanks for bringing the up. 
 - Can you share the number you are talking about?
 - Can you clarify the version you are comparing and fix your issue statement? (there is no torchaudio 1.6.0 and I think you mean pytorch 1.6.0 but `pip install torchaudio==1.6.0` is confusing and I want to make sure I understand you correctly).

**Comment by apeguero1** [comment]
The number I am talking about is just how long it takes for functional.istft to run. 
For me the timings are roughly:

5.0 seconds for torch==1.6.0
0.015 seconds for torchaudio==0.5.1 

Ah yes I made a typo in the issue I made on torchaudio [#834](https://github.com/pytorch/audio/issues/834). I wanted to compare torchaudio==0.5.1 with torchaudio==0.6.0 which ends up using the istft implementation of torch==1.6.0   (can't fix the issue statement though since it's closed). 

Here though I am directly comparing torch==1.6.0 with torchaudio==0.5.1 so I think the versions are correct?

**Comment by mthrok** [comment]
> Thanks for the response @mthrok!
> 
> The number I am talking about is just how long it takes for functional.istft to run.
> For me the timings are roughly:
> 
> 5.0 seconds for torch==1.6.0
> 0.015 seconds for torchaudio==0.5.1
> 
> Ah yes I made a typo in the issue I made on torchaudio [#834](https://github.com/pytorch/audio/issues/834). I wanted to compare torchaudio==0.5.1 with torchaudio==0.6.0 which ends up using the istft implementation of torch==1.6.0 (can't fix the issue statement though since it's closed).
> 
> Here though I am directly comparing torch==1.6.0 with torchaudio==0.5.1 so I think the versions are correct?

Thanks for the number. Yes your versions are correct. I will take a look on my end.

**Comment by apeguero1** [comment]
Awesome thanks!

**Comment by mthrok** [comment]
I confirm that I could reproduce the issue.

|                             |    Total   | Par Call |
|-----------------|:--------:|:------:|
| PyTorch 1.6.0      | 9.0404 | 0.904 |
| torchaudio 0.5.0 | 0.1052 | 0.010 |

<Details><Summary>script</Summary>

```python
import time

import torch
import torchaudio

n_fft = 2**15
x = torch.rand(size=[1, n_fft//2 + 1, 10, 2])

start = time.monotonic()
n = 10
for _ in range(n):
    # y = torchaudio.functional.istft(x,n_fft)
    y = torch.functional.istft(x,n_fft)
elapsed = time.monotonic() - start

print(elapsed, elapsed / n)
```

</Details>

<Details><Summary>Env 1: PyTorch 1.6.0</Summary>

```
$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0
[pip3] torchaudio==0.5.0a0+3305d5c
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] pytorch                   1.5.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.5.0                      py36    pytorch
```

</Details>

<Details><Summary>Env 2: torchaudio 0.5.0</Summary>

```
$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchaudio==0.6.0a0+f17ae39
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.18.5           py36ha1c710e_0
[conda] numpy-base                1.18.5           py36hde5b4d6_0
[conda] pytorch                   1.6.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.6.0                      py36    pytorch
```

</Details>

**Comment by mruberry** [comment]
cc @vincentqb

**Comment by vincentqb** [comment]
@albanD -- @mthrok mentioned you would follow up on this?

**Comment by mattip** [comment]
It seems neither environment is using CUDA, so it would be better to be explicit in the benchmark with `x = torch.rand(size=[1, n_fft//2 + 1, 10, 2], device='cpu')`. The difference is in the post-processing after the call to `irfft`, starting [here](https://github.com/pytorch/audio/blob/v0.5.0/torchaudio/functional.py#L178) in the python implementation and [here](https://github.com/pytorch/pytorch/blob/v1.6.0/aten/src/ATen/native/SpectralOps.cpp#L356) in the cpp one.. 

The python script uses `torch.nn.functional.fold`, where the cpp code uses a much more "expensive" combination of `at::native::eye` and `at::conv_transpose1d`. 

I can reproduce this via
- build pytorch HEAD `python setup.py develop`
- clone pytorch/audio in a new directory, `cd ..; git clone https://github.com/pytorch/audio.git; cd audio; git checkout  v0.5.0`
- `PYTHONPATH=path/to/pytorch pip install .` to install torchaudio 0.5.0
- `cd` back to pytorch
- run the script below, which is an adaptation of the one above

It prints (YMMV)
```
for torchaudio.istft 0.03506781195756048 0.003506781195756048
for torch.istft 13.575328684062697 1.3575328684062697

```
Then I started adding timing code to the CPP implementation of istft to figure out where it is slow.

<details>
<summary>this script</summary>
```
import time

import torch
import torchaudio

n_fft = 2**15
x = torch.rand(size=[1, n_fft//2 + 1, 10, 2], device='cpu')
n = 10

start = time.monotonic()
for _ in range(n):
    y = torchaudio.functional.istft(x,n_fft)
elapsed = time.monotonic() - start
print('for torchaudio.istft', elapsed, elapsed / n)

start = time.monotonic()
for _ in range(n):
    y = torch.functional.istft(x, n_fft)
elapsed = time.monotonic() - start
print('for torch.istft', elapsed, elapsed / n)
```

**Comment by ngimel** [comment]
@mattip you can use profiler to get a breakdown of time taken by different operations:
```
with torch.autograd.profiler.profile() as prof:
    for _ in range(10):
        y = torch.functional.istft(x, n_fft)
print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
output:
```
aten::fill_                      42.35%           4.248s           42.35%           4.248s           60.685ms         70               
aten::istft                      30.47%           3.057s           100.00%          10.031s          1.003s           10               
aten::slow_conv_transpose2d      25.89%           2.598s           25.96%           2.604s           130.209ms        20               
aten::eye                        0.61%            61.133ms         42.90%           4.303s           430.305ms        10               
aten::_fft_with_size             0.22%            22.200ms         0.22%            22.284ms         2.228ms          10               
aten::mul                        0.18%            17.690ms         0.18%            18.423ms         1.842ms          10               
aten::copy_                      0.11%            11.199ms         0.11%            11.199ms         559.961us        20          
```
`istft` itself is still a large fraction

**Comment by mattip** [comment]
Ahh, nice. Thanks. I think `aten::istft` is the aggregate, composed of the other functions which appear in the code for `aten:istft`. The actual fft call used is `irfft`, which doesn't even appear in the profile.

**Comment by ngimel** [comment]
Yeah, it is not profiled because it is dispatched via `at::native::irfft` and avoids being profiled. When I made it `at::irfft` it is profiled, but its self-time is 0, looks like all the time from irfft is spent in `_fft_with_size`.
