### ISSUE TITLE
Compilation error, Performing Test SUPPORT_GLIBCXX_USE_C99 Failed.

### ISSUE THREAD

**Issue by EthanZhangYi** [pytorch/pytorch#42224]
On a server with `CentOS Linux release 7.2.1511`
With **the same environment** (to ensure this, I just tried to compile pytorch1.1.0 and pytorch1.6.0 in the same terminal).
I tried to compile pytorch-1.1.0, pytorch-1.5.1 and pytorch-1.6.0 from source by `python setup.py install`.
Pytorch-1.1.0 can be compiled, but pytorch-1.5.1 and 1.6.0 failed, with `Performing Test SUPPORT_GLIBCXX_USE_C99 Failed` as shown below.
compiling pytorch1.1.0
![b](https://user-images.githubusercontent.com/13479831/88762918-b46b6400-d1a4-11ea-9813-53fcb07e97b9.jpg)
compiling pytorch1.6.0
![a](https://user-images.githubusercontent.com/13479831/88762933-bcc39f00-d1a4-11ea-8bd4-0b61523c4745.jpg)
Issue #5229 can not solve this problem.

cc @malfet

**Comment by albanD** [comment]
Hi,

Are you using gcc 5 by any chance? It seems to say that this might be related to that?

**Comment by malfet** [comment]
Pytorch-1.5 needs a C++14  compatible compiler. You are trying to compile PyTorch-1.6.0 with gcc-4.8.5, which is not fully C++14 compatible. 
Is there a reason why you can not try to compile it with at least gcc-5.4?

**Comment by EthanZhangYi** [comment]
@albanD @malfet 
Solved by install a gcc5.4 locally.

**Comment by denfromufa** [comment]
I was getting this error with gcc toolchain from conda, after removing this issue got resolved.

**Comment by Borda** [comment]
Having the same issue while compiling 2.1 on Kaggle; any advice? :flags:
