### ISSUE TITLE
Mistakes in torch.cuda.amp docs

### ISSUE THREAD

**Issue by kaimingkuang** [pytorch/pytorch#42226]
There is a tiny mistake in the documentation of torch.cuda.amp.GradScaler. Under the description of __init__ parameters:
```Python
"""
        growth_factor (float, optional, default=2.0):  Factor by which the scale is multiplied during
            :meth:`update` if no inf/NaN gradients occur for ``growth_factor`` consecutive iterations
"""
```
Should be for ``growth_interval`` consecutive iterations?

cc @mcarilli @jlin27

**Comment by mcarilli** [comment]
Thanks for spotting!
