### ISSUE TITLE
LSTM export to ONNX Scan op 

### ISSUE THREAD

**Issue by rajeevsrao** [pytorch/pytorch#42235]
## 🚀 Feature
Export multi-layer LSTM/RNNs as ONNX scan op instead of creating multiple ONNX LSTM cells for multilayer torch.nn.LSTM.

## Motivation
Enable efficient ONNX representations of RNN ops instead of generating graphs with single cell LSTMs.

## Pitch
See "Encoding RNN using a Scan" in https://github.com/onnx/onnx/blob/master/docs/Operators.md#scan

## Example
Sample LSTM export to ONNX (produces graph LSTM cells in torch v1.6.0) 
```python
import argparse
import os
import torch
from torch import nn

_EXPORT_MODULES = [
    # Module, Num Inputs, Input shapes
    (nn.LSTM(input_size=16, hidden_size=32, num_layers=2), 1, [(2, 16, 16)]), # input_0=[seq_len,batch,input_size]
]

def export_to_onnx(module, num_inputs, input_shapes, *, module_name=None, outdir=None, device="cuda"):
    """Export a module to ONNX
    Args:
        module: A quantized module
        num_inputs: An Integer of number of inputs to the module
        input_shapes: A list of tuple of integer indicates.
        module_name: String. Module name. Default None.
        outdir: String. Path to write ONNX file. Default None
        device: Default "cuda".
    """
    module.to(device)
    dummy_inputs = [torch.randn(input_shapes[i], device=device) for i in range(num_inputs)]
    if module_name is None:
        module_name = module.__class__.__name__
    onnx_path = F"{module_name}.onnx"
    if outdir is not None:
        onnx_path = os.path.join(outdir, onnx_path)
    input_names = [F"input_{i}" for i in range(num_inputs)]
    torch.onnx.export(module, tuple(dummy_inputs), onnx_path, verbose=True, opset_version=12,
                      input_names=input_names, output_names=["output"])
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--outdir', default='', type=str, help="Path to write ONNX")
    args = parser.parse_args()
    for module, num_inputs, input_shapes in _EXPORT_MODULES:
        export_to_onnx(module, num_inputs, input_shapes, outdir=args.outdir)
if __name__ == '__main__':
    main()
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@rajeevsrao - can this be handled as a ONNX -> ONNX transformation? Would you consider contributing a PR for this.

**Comment by shubhambhokare1** [comment]
Hi @rajeevsrao,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
