### ISSUE TITLE
`torch.hub.load_state_dict_from_url()` is not able to load the new zipfile serialization files

### ISSUE THREAD

**Issue by yukw777** [pytorch/pytorch#42239]
## 🐛 Bug

If you call `torch.hub.load_state_dict_from_url()` on a file saved in the new zipfile serialization format, it raises `RuntimeError('Only one file(not dir) is allowed in the zipfile')`.

## To Reproduce

1. Upload a state dictionary file saved using the vanilla `torch.save()` to a server.
1. Call `torch.hub.load_state_dict_from_url()` to that url.
1. You'll see the `RuntimeError` raised.

We discovered this as part of the effort to support pytorch 1.6 with pytorch lightning. Here's one of the failed test runs: https://github.com/PyTorchLightning/pytorch-lightning/runs/920684391

## Expected behavior

`torch.hub.load_state_dict_from_url()` should load the new zipfile serialization files without any errors.

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-lightning==0.9.0rc3
[pip3] torch==1.6.0
[pip3] torchtext==0.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect
```

## Additional context

We use `torch.hub.load_state_dict_from_url()` to load remote PyTorch Lightning checkpoints.

CC @williamFalcon @borda

cc @ezyang @gchanan @zou3519 @ailzhang

**Comment by farleylai** [comment]
According to the [note](https://github.com/pytorch/pytorch/blob/8c653e05ff713bd5b94766c4ca54591cac4d25ca/torch/serialization.py#L353), the zip format is the default in v1.6 in `torch.save()`:

>     The 1.6 release of PyTorch switched ``torch.save`` to use a new
        zipfile-based file format. ``torch.load`` still retains the ability to
        load files in the old format. If for any reason you want ``torch.save``
        to use the old format, pass the kwarg ``_use_new_zipfile_serialization=False``.

**Comment by yukw777** [comment]
@tgaddair https://github.com/PyTorchLightning/pytorch-lightning/blob/8ab5bcda3d040fbe6fd616ff45793e3dfd1061ce/.github/workflows/ci-testing.yml#L104 why do we skip 3.8? can we add it back in?

**Comment by tgaddair** [comment]
Hey @yukw777, regarding the Horovod Python 3.8 thing, the underlying issue was fixed in Horovod 0.19.2.  So provided the min version is at or above that, we can remove the checks against Python 3.8.

**Comment by jspisak** [comment]
@jamesr66a - can you take a look?

**Comment by ailzhang** [comment]
FYI I'll send a fix for this later today.
