### ISSUE TITLE
problem with F.affine_grid

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#4223]
I think there is an issue with `F.affine_grid`. The problem might not be detectable in a Spatial Transformer Network where everything is learnable, and if images are squared, but using the following code:

```python
x = 1
y = 0
theta = 0
G = F.affine_grid(
    torch.FloatTensor([
        [[np.cos(theta), -np.sin(theta), x],
         [np.sin(theta), np.cos(theta), y]]
    ]),
    torch.Size((1, 1, 100, 200))
)[0]
print(G.size())
print(G[:, :, 0])
print(G[:, :, 1])
```

I get this:

```
torch.Size([100, 200, 2])
Variable containing:
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
          ...             ⋱             ...          
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
 0.0000  0.0101  0.0201  ...   1.9799  1.9899  2.0000
[torch.FloatTensor of size 100x200]

Variable containing:
-1.0000 -1.0000 -1.0000  ...  -1.0000 -1.0000 -1.0000
-0.9798 -0.9798 -0.9798  ...  -0.9798 -0.9798 -0.9798
-0.9596 -0.9596 -0.9596  ...  -0.9596 -0.9596 -0.9596
          ...             ⋱             ...          
 0.9596  0.9596  0.9596  ...   0.9596  0.9596  0.9596
 0.9798  0.9798  0.9798  ...   0.9798  0.9798  0.9798
 1.0000  1.0000  1.0000  ...   1.0000  1.0000  1.0000
[torch.FloatTensor of size 100x200]
```

And I think this is wrong. In particular, `G[0, :, 0]` should be a line full of `0`, `G[:, 0, 0]` should go from `0` to `2`, `G[0, :, 1]` should go from `-1` to `1`, etc.

In particular, on this image:

![image](https://user-images.githubusercontent.com/8885556/34099630-547b074e-e3e0-11e7-9d03-837d62ab624c.png)

The grid above, with `F.grid_sample` should give me this because I'm shifting the image by 1 on the x-axis:

![image](https://user-images.githubusercontent.com/8885556/34099686-7c058866-e3e0-11e7-844f-7aca7ca44509.png)

But I get this instead:

![image](https://user-images.githubusercontent.com/8885556/34099730-a0fdc1c4-e3e0-11e7-959d-64907f0de12c.png)

**Comment by glample** [comment]
Mmm it may be that there is a convention in vision that consists in reversing the x and y axis for easier visualization... if this is actually the expected behavior, please just point me out.

**Comment by soumith** [comment]
affine grid takes Y, X convention i think (to match with H, W)
