### ISSUE TITLE
how to enable CUDNN_TENSOR_OP_MATH for float32 torch.mm operator 

### ISSUE THREAD

**Issue by shz0116** [pytorch/pytorch#42268]
I am wondering in pytorch, how to enable tensor cores for float32 torch.mm operations.
I posted the same question at https://discuss.pytorch.org/t/using-nvidia-tensor-core-for-float-mm-computation/90901,
but got no response. Thanks.

cc @ngimel

**Comment by ngimel** [comment]
Responded on the forum.
