### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._C'  install from source

### ISSUE THREAD

**Issue by CharlesxrWu** [pytorch/pytorch#4227]
I install from source, follow this guide to support MPI backend.
(https://discuss.pytorch.org/t/segfault-using-cuda-with-openmpi/11140)

However, I face the problem

File "/home/charles/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 76, in <module>
    from torch._C import *
ImportError: libmpi.so.40: cannot open shared object file: No such file or directory

I can find the torch in the conda list.

**Comment by soumith** [comment]
when you installed OpenMPI manually, you have to make sure `libmpi.so` files are in your LD_LIBRARY_PATH

See https://unix.stackexchange.com/questions/168340/where-is-ld-library-path-how-do-i-set-the-ld-library-path-env-variable on how to use LD_LIBRARY_PATH
