### ISSUE TITLE
`torch.Generator` produces segfault when input is `device='cuda'` on a machine that is not CUDA-enabled

### ISSUE THREAD

**Issue by lxuechen** [pytorch/pytorch#42281]
## 🐛 Bug
The bug is as described in the title. The bug appears to be only with v1.6.0. 

The case of inputting `device='cuda'` on a machine that is not CUDA-enabled might be rare. But a segfault as outcome doesn't seem to be desirable in any scenario.

## To Reproduce
Run the following on a cpu-only machine:
```python
import torch
g = torch.Generator(device='cuda')
```
Outcome:
```bash
Segmentation fault: 11
```

## Environment
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.4
GCC version: Could not collect
CMake version: version 3.16.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.6.0
[pip3] torch-struct==0.4
[pip3] torchdiffeq==0.0.1
[pip3] torchsde==0.1.1
[pip3] torchsearchsorted==1.1
[pip3] torchvision==0.7.0
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] nomkl                     3.0                           0
[conda] numpy                     1.18.2                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37ha711998_1
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torch-struct              0.4                      pypi_0    pypi
[conda] torchdiffeq               0.0.1                    pypi_0    pypi
[conda] torchsde                  0.1.1                    pypi_0    pypi
[conda] torchsearchsorted         1.1                      pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @pbelevich

**Comment by malfet** [comment]
Grabbing for myself

**Comment by malfet** [comment]
Issue is not specific to Mac or CUDA,  https://github.com/pytorch/pytorch/pull/42490 should fix it.
