### ISSUE TITLE
RuntimeError: the number of sizes provided must be greater or equal to the number of dimensions in the tensor

### ISSUE THREAD

**Issue by hbredin** [pytorch/pytorch#4228]
I am trying to compute a differentiable version of `scipy.spatial.distance.pdist` for use in a custom loss.  

```python
import torch
from torch.autograd import Variable
from torch import Tensor
import torch.nn.functional as F

# one hundred 3-dimensional vectors
X = Variable(Tensor(100, 3).normal_(), requires_grad=True)

# compute the equivalent of scipy.spatial.distance.pdist(X, metric='cosine')
d = []
for i in range(1, 100):
   d.append(F.cosine_similarity(X[i,:].expand(i, -1), X[:i]))
pdist = torch.cat(d) 
```

Up to this point, everything seems to work fine. However, when trying to use this `pdist` in a custom loss and back-propagate the gradient, a `RuntimeError` occurs:

```python
loss = torch.mean(pdist)

# this is where things go wrong
loss.backward()
```

```python
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /Users/soumith/minicondabuild3/conda-bld/pytorch_1512381214802/work/torch/lib/TH/generic/THTensor.c:299
```

I am pretty sure I did a stupid mistake (been playing with pytorch for only a few days) but I must confess I am completely at a loss (pun intended) here. Any idea what I did wrong? I am using version `0.3.0.post4`.

**Comment by zou3519** [comment]
I can reproduce the error on 0.3.0.post4 but it looks like on the master version there is no error so this may have been fixed somewhere down the line.

@hbredin it doesn't look like you're doing anything wrong -- could you try building from source and seeing if the error goes away?

**Comment by zou3519** [comment]
There are plans for nightly builds but we don't have those yet, unfortunately. But yes if you stick with pytorch 0.3.0, maybe try avoiding using `cat` on tensors that have one element.

**Comment by hbredin** [comment]
Closing. I confirm `torch.cat` is fixed in current `master`.

**Comment by paduvi** [comment]
@zou3519 I have same issue using pytorch with pip. I can't built from source for now, because I only have permission to use pip inside virtualenv
