### ISSUE TITLE
Pytorch 1.6.0 Quantization  quantized tensor support on CUDA is not working

### ISSUE THREAD

**Issue by tgisaturday** [pytorch/pytorch#42288]
## 🐛 Bug

As version 1.6.0 released and quantized tensor support on CUDA is included in the release note, I'm trying to run quantized_mobilenetv2 (from torchvision) in GPU. #37081[](https://github.com/pytorch/pytorch/pull/37081)
After I fused the model and run torch.quantization.convert, Pytorch throws me this error:
[](url)
RuntimeError: Could not run 'quantized::conv2d_prepack' with arguments from the 'UNKNOWN_TENSOR_TYPE_ID' backend. 'quantized::conv2d_prepack' is only available for these backends: [QuantizedCPU].  

I'm using "latency_check.py" in [here](https://github.com/clovaai/StatAssist-GradBoost/blob/master/Classification/latency_check.py). The code works fine in CPU setting. 

## To Reproduce

1. Git clone clovaai/StatAssist-GradBoost [repo](https://github.com/clovaai/StatAssist-GradBoost/).
2. Run "Classification/latency_check.py" with args "--use_gpu". 

Traceback (most recent call last):
  File "latency_check.py", line 122, in <module>
    torch.quantization.convert(model.eval(),inplace = True)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/quantization/quantize.py", line 365,in convert
    convert(mod, mapping, inplace=True)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/quantization/quantize.py", line 365,in convert
    convert(mod, mapping, inplace=True)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/quantization/quantize.py", line 365,in convert
    convert(mod, mapping, inplace=True)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/quantization/quantize.py", line 366,in convert
    reassign[name] = swap_module(mod, mapping)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/quantization/quantize.py", line 395,in swap_module
    new_mod = mapping[type(mod)].from_float(mod)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py", line 82, in from_float
    return super(ConvReLU2d, cls).from_float(mod)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py", line 370, in from_float
    qconv.set_weight_bias(qweight, mod.bias)
  File "/home/datamining100/Desktop/100_server_venv/lib/python3.6/site-packages/torch/nn/quantized/modules/conv.py", line 310, in set_weight_bias
    w, b, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Could not run 'quantized::conv2d_prepack' with arguments from the 'UNKNOWN_TENSOR_TYPE_ID' backend. 'quantized::conv2d_prepack' is only available for these backends: [QuantizedCPU].
## Expected behavior

Quantized model runs without any error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2/440.59
 - GPU models and configuration: NVIDIA Titan V
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
hi @tgisaturday , thanks for the report! https://github.com/pytorch/pytorch/pull/37081 is only the first step in adding quantized inference support on GPU, but the actual functionality of running inference of real quantized models on GPU is not expected to work at the moment.

**Comment by gemfield** [comment]
I am using torch.quantization.quantize_dynamic(net, dtype=torch.qint8) API and met this error too:
```bash
RuntimeError: Could not run 'quantized::linear_prepack' with arguments from the 'UNKNOWN_TENSOR_TYPE_ID' backend. 'quantized::linear_prepack' is only available for these backends: [QuantizedCPU].
```
after change the device from cuda to cpu, the error disappeared.

**Comment by jerryzh168** [comment]
yeah linear_prepack only works in cpu

**Comment by jerryzh168** [comment]
I think we can close this, feel free to reopen if you have more questions.
