### ISSUE TITLE
Circleci Windows cu101 build fail

### ISSUE THREAD

**Issue by guyang3532** [pytorch/pytorch#42293]
## 🐛 Bug

The failure job link:
https://app.circleci.com/pipelines/github/pytorch/pytorch/194077/workflows/5124798c-02aa-4049-bec7-295358b25c3e/jobs/6397617

Error message:
[2907/3629] Building NVCC (Device) object caffe2/CMakeFiles/torch_cuda.dir/operators/torch_cuda_generated_elementwise_mul_op.cu.obj
FAILED: caffe2/CMakeFiles/torch_cuda.dir/operators/torch_cuda_generated_elementwise_mul_op.cu.obj 
cmd.exe /C "cd /D %SRC_DIR%\build\caffe2\CMakeFiles\torch_cuda.dir\operators && %BUILD_PREFIX%\Library\bin\cmake.exe -E make_directory C:/cb/pytorch_1000000000000/work/build/caffe2/CMakeFiles/torch_cuda.dir/operators/. && %BUILD_PREFIX%\Library\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=C:/cb/pytorch_1000000000000/work/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_elementwise_mul_op.cu.obj -D generated_cubin_file:STRING=C:/cb/pytorch_1000000000000/work/build/caffe2/CMakeFiles/torch_cuda.dir/operators/./torch_cuda_generated_elementwise_mul_op.cu.obj.cubin.txt -P C:/cb/pytorch_1000000000000/work/build/caffe2/CMakeFiles/torch_cuda.dir/operators/torch_cuda_generated_elementwise_mul_op.cu.obj.Release.cmake"
elementwise_mul_op.cu
elementwise_mul_op.cu
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(171): error C2065: 'OutputIteratorT': undeclared identifier
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(780): note: see reference to class template instantiation 'cub::AgentHistogram<AgentHistogramPolicyT,PRIVATIZED_SMEM_BINS,NUM_CHANNELS,NUM_ACTIVE_CHANNELS,SampleIteratorT,CounterT,PrivatizedDecodeOpT,OutputDecodeOpT,OffsetT,PTX_ARCH>' being compiled
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(179): error C2065: 'OutputIteratorT': undeclared identifier
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(187): error C2065: 'OutputIteratorT': undeclared identifier
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(199): error C2065: 'OutputIteratorT': undeclared identifier
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(203): note: see reference to class template instantiation 'cub::AgentHistogram<AgentHistogramPolicyT,PRIVATIZED_SMEM_BINS,NUM_CHANNELS,NUM_ACTIVE_CHANNELS,SampleIteratorT,CounterT,PrivatizedDecodeOpT,OutputDecodeOpT,OffsetT,PTX_ARCH>::_TempStorage::Aliasable' being compiled
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(204): note: see reference to class template instantiation 'cub::AgentHistogram<AgentHistogramPolicyT,PRIVATIZED_SMEM_BINS,NUM_CHANNELS,NUM_ACTIVE_CHANNELS,SampleIteratorT,CounterT,PrivatizedDecodeOpT,OutputDecodeOpT,OffsetT,PTX_ARCH>::_TempStorage' being compiled
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(200): error C2065: 'OutputIteratorT': undeclared identifier
%SRC_DIR%\third_party\cub\cub\device\dispatch\../../agent/agent_histogram.cuh(201): error C2065: 'OutputIteratorT': undeclared identifier

cc @ezyang @seemethere @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Doesn't seem to be a problem anymore. 
See recent builds.
https://app.circleci.com/pipelines/github/pytorch/pytorch/195771/workflows/9306fc22-60c5-4df0-bb24-20dfde8febda
https://app.circleci.com/pipelines/github/pytorch/pytorch/195651/workflows/1edd947b-5904-4225-b619-38a92323d31e
