### ISSUE TITLE
bug in conversion torch model to onnx model 

### ISSUE THREAD

**Issue by natangold85** [pytorch/pytorch#42292]
## 🐛 Bug
I'm converting a pytorch model to onnx model. in this model there assignment of tensor to a slice of another tensor.
when i'm running the converted model with onnxruntime he crashes when trying to assign the small tensor to the big tensor and ignoring the slice operation.

## To Reproduce
i created a stand alone model to reproduce the problem. this is the error when trying to run the model:

**The input tensor cannot be reshaped to the requested shape. Input shape:{22,256}, requested shape:{56,1,256}**

run the attached code

``import torch
import onnx
import onnxruntime

class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        x[:y.size(0), 0, :] = y
        return x

x = torch.zeros((56,6,256))
y = torch.rand((22,256))

m = Test()
torch_outputs = m(x, y)

path = "/tmp/m.onnx"
torch.onnx.export(m, (x, y), path,
                    do_constant_folding=True,
                    opset_version=12,
                    input_names=["x", "y"],
                    output_names=["z"])

onnx_model = onnx.load_model(path)
onnx.checker.check_model(onnx_model)
inferred_model = onnx.shape_inference.infer_shapes(onnx_model)
onnx.save(inferred_model, path)

ort_model = onnxruntime.InferenceSession(path)

ort_outputs = ort_model.run(["z"], {"x": x.numpy(), "y": y.numpy()})``

## Expected behavior
run successfully the model with onnxruntime

## Environment

 - PyTorch Version: 1.5.1 
 - OS (e.g., Linux): Linux ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.8
 - GPU models and configuration:
 - Any other relevant information: onnxruntime verion 1.4.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by codender** [comment]
occurs this error too~~~

**Comment by spandantiwari** [comment]
OK, we will take a look.

**Comment by shubhambhokare1** [comment]
An alternative to the slice operation could be to use the scatter op.
`def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        indx = torch.zeros(y.size(0), 1, y.size(1), dtype=torch.long)
        x = torch.scatter(x, 1, indx, y.unsqueeze(1))
        return x`
