### ISSUE TITLE
Maybe bind VolumetricConvolution (no MM) in ATen?

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4229]
We currently bind THNN VolumetricConvolutionMM as conv3d, but we don't bind VolumetricConvolution. Instead, VolumetricConvolution is used purely by the legacy NN. Should we bind it in ATen, or is it just legacy code that no one should use if they can avoid it?

**Comment by soumith** [comment]
legacy code that no one should use, so lets not bind it.
