### ISSUE TITLE
This is a question about classification labels.

### ISSUE THREAD

**Issue by shenao1994** [pytorch/pytorch#42294]
I am dividing a set of image data into five categories. I want to set the label like this, because these data are related. Can you tell me how to modify the related code?My original label is [0, 1, 2, 3, 4]

**1 1 0 0 0 0
2 1 1 0 0 0
3 1 1 1 0 0
4 1 1 1 1 0
5 1 1 1 1 1**

Thanks！

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen if you think that you need to report a bug or make feature proposal. Thanks.
