### ISSUE TITLE
KeyError: ‘ExpandBackward’ occurred

### ISSUE THREAD

**Issue by manlinting** [pytorch/pytorch#4230]
I used pytorch 0.2.0_3 to convert a resmet50 pytorch model into a caffe model, but after I upgraded to pytorch 0.3.0.post4, a KeyError: ‘ExpandBackward’ occurred. Will ExpandBackward is adding new layer, how to deal with this problem?

I use https://github.com/longcw/pytorch2caffe/blob/master/pytorch2caffe.py2 to convert pytorch to caffe.

**Comment by soumith** [comment]
please open an issue at `pytorch2caffe`. This is just a case of that converter not handling all functions in a trace yet.
