### ISSUE TITLE
Upgrading to 1.6 produces pylint `abstract-method` warning for custom modules

### ISSUE THREAD

**Issue by mberr** [pytorch/pytorch#42305]
## 🐛 Bug

The following trick for mypy

https://github.com/pytorch/pytorch/blob/269ec767cabe9c47baab18e58fad5d6485d4e65d/torch/nn/modules/module.py#L223-L239

introduced with 1.6 leads to pylint warnings

```
W0223: Method '_forward_unimplemented' is abstract in class 'Module' but is not overridden (abstract-method)
```

when extending `nn.Module` for custom modules.

## To Reproduce

1. Create MWE
```python
from torch import nn

class MyModule(nn.Module):
    def forward(self, x):
        return x
```
2. run pylint
```console
$ pylint --disable=all --enable=abstract-method mwe.py
mwe.py:4:0: W0223: Method '_forward_unimplemented' is abstract in class 'Module' but is not overridden (abstract-method)

```

## Expected behavior

No warnings if `forward` is implemented.

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[conda] Could not collect
```

## Additional context

* I am using pytorch in project with many custom modules where the CI runs pylint. Since upgrading to torch 1.6 I therefore get a large number of warning. Since pylint is quite widespread, I suppose this problem may occur for other users as well.
* I am unsure whether the "bug" type of issue is correct. However, it seemed to be the best fit.

cc @ezyang @malfet @rgommers

**Comment by VitalyFedyunin** [comment]
CC @ezyang

**Comment by ezyang** [comment]
Ugh, this sucks. @mberr, I don't have a lint easily setup right now, but if we "hide" the `raise NotImplemented` in some way (e.g., by putting it in a lambda and then immediately invoking it) does that appease the lint? If so I'd be happy to take the patch.

**Comment by mberr** [comment]
> Ugh, this sucks. @mberr, I don't have a lint easily setup right now, but if we "hide" the `raise NotImplemented` in some way (e.g., by putting it in a lambda and then immediately invoking it) does that appease the lint? If so I'd be happy to take the patch.

Replacing https://github.com/pytorch/pytorch/blob/269ec767cabe9c47baab18e58fad5d6485d4e65d/torch/nn/modules/module.py#L223-L227 by

```python
    # Trick mypy into not applying contravariance rules to inputs by defining
    # forward as a value, rather than a function.  See also
    # https://github.com/python/mypy/issues/8795
    def _forward_unimplemented(self, *input: Any) -> None:
        def f(*x):
            raise NotImplementedError
        return f(*input)
```

stops pylint from raising the `abstract-method` in the MWE from above. However, now it also fails to correctly detect cases where `forward` is not overridden, e.g.

```python
from torch import nn


class MyModule(nn.Module):
    def forward(self, x):
        return x


class MyModule2(nn.Module):
    pass
```

does not raise any `abstract-method` warning.

**Comment by mberr** [comment]
@ezyang I think I found a solution, cf. #42356

**Comment by mberr** [comment]
@ezyang It seems like the fix lead to a failure for one specific build, `pytorch_macos_10_13_py3_test`, but I cannot make much sense out of the error log I see there.
