### ISSUE TITLE
Quantized Conv2d yields incorrect results (torch 1.6.0)

### ISSUE THREAD

**Issue by Smthri** [pytorch/pytorch#42312]
## 🐛 Bug

Quantized torch.nn.Conv2d layer calculates convolution incorrectly, meaning that the dequantized output strongly (sometimes > 1) differs from the float output prior to quantization.

## To Reproduce

1. Initialize random 3x3 weight matrix and 3x3 input.
2. Manually quantize weights, input and perform calculations.
3. Create torch model as nn.Conv2d layer with the same weights, quantize and run the model on the input.
4. Sometimes the model returns correct result, however, often it doesn't.

A ZIP container with jupyter notebook illustrating all steps mentioned above,
[quantization_test.zip](https://github.com/pytorch/pytorch/files/5002219/quantization_test.zip)

## Expected behavior

Expected behavior: return result approximately equal to the float ground truth and dequantized output of the manually quantized convolution.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Windows 10 2004
 - How you installed PyTorch (`conda`, `pip`, source): pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
 - Build command you used (if compiling from source): -
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Nvidia GeForce GTX 970

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
hi @Smthri , thanks for the report.  Would you mind adding the repro in a non-zip format (ideally as plain text, perhaps via gist.github.com)?

**Comment by Smthri** [comment]
Link to gist: https://gist.github.com/Smthri/e7a414798d7fa32fc9f41f44c9bd1b11

**Comment by vkuzo** [comment]
hi @Smthri , you can use the `reduce_range` flag in observers to fix this issue, this is happening because without this flag some values  can overflow in the `fbgemm` backend.  For example, `MinMaxObserver.with_args(reduce_range=True)`.

Keeping this issue open until we either throw a warning or explain this better in the quantization docs.

**Comment by Smthri** [comment]
Thank you!

**Comment by Smthri** [comment]
Thank you! Can you please explain what that flag does in detail?
Also, with this flag, we still get large errors, link to gist: https://gist.github.com/Smthri/7e862838093532f1aa38857d345e2816
Error:
![image](https://user-images.githubusercontent.com/16116223/89220268-ed0ea180-d5d9-11ea-83f7-ec670f0b9356.png)

**Comment by raghuramank100** [comment]
More information about reduce_range can be found at: 
https://github.com/pytorch/pytorch/blob/38bf5be24f2d4bed3f448e95a09d7175c5f40f54/torch/quantization/observer.py#L321
This flag reduces the input activation dynamic range to 7 bits, This avoids saturation in the kernels for conv and linear. 

The script is missing quantizing the outputs of the convolution, once we model that the error is zero. If you add these lines to the end of your script, the error is gone:
``` python
res_q = torch.quantize_per_tensor(torch.Tensor(res), outp_scale, outp_zero_point, torch.quint8)
res_q_dq = res_q.dequantize().numpy()

print(f_outp.detach().numpy()[0] - res_q_dq)
```

**Comment by Smthri** [comment]
Thank you!

**Comment by vkuzo** [comment]
will track this in https://github.com/pytorch/pytorch/issues/46749
