### ISSUE TITLE
Mimic torch.bucketsize in 1.5

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/pytorch#42315]
Pytorch 1.6 beta offers the new function [torch.bucketsize](https://pytorch.org/docs/stable/generated/torch.bucketize.html)
Is it possible to mimic this function in torch 1.5.1?

Thank you

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/. I will close this issue, feel free to reopen if you think that you need to report a bug or make feature proposal. Thanks.
