### ISSUE TITLE
INTERNAL ASSERT FAILED for searchsorted with requires_grad inputs.

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#42328]
## To Reproduce

```
torch.searchsorted(torch.arange(1.,7., requires_grad=True), torch.randn((), requires_grad=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1596092979477/work/torch/csrc/autograd/functions/utils.h":59, please report a bug to PyTorch.
```

Note: either of the inputs requiring grad triggers the assert.

## Expected behavior
See:
https://github.com/pytorch/pytorch/blob/26d58503c220a709117582f48cff77a6fc418d6d/torch/csrc/autograd/functions/utils.h#L57-L58

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.7.0.dev20200730
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 418.126.02
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] torch==1.7.0.dev20200730
[pip] torchvision==0.8.0.dev20200730
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               9.2                           0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.17.3                    <pip>
[conda] numpy                     1.18.5           py36ha1c710e_0
[conda] numpy-base                1.18.5           py36hde5b4d6_0
[conda] pytorch                   1.7.0.dev20200730 py3.6_cuda9.2.148_cudnn7.6.3_0    pytorch-nightly
[conda] torch                     1.3.0+cu92                <pip>
[conda] torchvision               0.8.0.dev20200730       py36_cu92    pytorch-nightly
[conda] torchvision               0.4.1+cu92                <pip>

## Additional context

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by zou3519** [comment]
Seems fixed:
```
>>> torch.searchsorted(torch.arange(1.,7., requires_grad=True), torch.randn((), requires_grad=True))
torch.tensor(0.)
```
