### ISSUE TITLE
Remove Mutation on List/Tuple elements

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#42334]
## 🐛 Bug

Currently, remove_mutation pass does not handle tensors that are put in a list/tuple, even when the tuple/list does not escape the graph.

## To Reproduce

```python
    class Add_(torch.nn.Module):
        def forward(self, x):
            x = x + 1
            return torch.cat([x.add_(3), x])

    graph = torch.jit.script(Add_()).graph
    torch._C._jit_pass_remove_mutation(graph)
    print(graph)


# graph(%self : __torch__.Add_,
#      %x.1 : Tensor):
#  %8 : int = prim::Constant[value=0]()
#  %4 : int = prim::Constant[value=1]()
#  %3 : int = prim::Constant[value=3]() 
#  %5 : Tensor = aten::add_(%x.1, %3, %4)
#  %7 : Tensor[] = prim::ListConstruct(%5, %x.1)
#  %9 : Tensor = aten::cat(%7, %8)
#  return (%9)

#===1. GRAPH===
# graph(%self : __torch__.Add_,
#       %x.1 : Tensor):
#   %8 : int = prim::Constant[value=0]()
#   %4 : int = prim::Constant[value=1]()
#   %3 : int = prim::Constant[value=3]() # test_onnx.py:376:37
#   %5 : Tensor = aten::add_(%x.1, %3, %4) # test_onnx.py:376:30
#   %7 : Tensor[] = prim::ListConstruct(%5, %x.1)
#   %9 : Tensor = aten::cat(%7, %8) # test_onnx.py:376:19
#   return (%9)
#
# ===2. ALIAS DB===
# %x.1 points to: WILDCARD for type Tensor,
# %5 points to: %x.1,
# %7 contains: WILDCARD for type Tensor,
# %self points to: WILDCARD for type __torch__.Add_,
#
# ===3. Writes===
# %5 : Tensor = aten::add_(%x.1, %3, %4) # test_onnx.py:376:30
#   WILDCARD for type Tensor, %x.1,
```
## Expected behavior

The inplace add_ node within the graph should be replaced by its functional equivalent op.

## Additional context

The issue here is that all elements within the List are marked as WILDCARD in alias DB.

cc @suo @gmagogsfm

**Comment by neginraoof** [comment]
cc @eellison

**Comment by ankitaggarwal23** [comment]
can I contribute in this issue

**Comment by eellison** [comment]
@ankitaggarwal23 this isn't a great issue for someone new to the code base to contribute to, maybe  something from https://github.com/pytorch/pytorch/issues/38349 would be good

**Comment by eellison** [comment]
This is hard to handle in the general case, but is not to hard to handle for lists which have a single, non-aliasing use. I submitted https://github.com/pytorch/pytorch/pull/37903 a while back that would fix this, but I need to do a little more work to clean it up before landing.

**Comment by neginraoof** [comment]
@eellison Thanks a lot for looking into this.
Do you think tuple (TupleConstruct) nodes can be handled similarly?

**Comment by eellison** [comment]
I don't think so, because any trivial usage of TupleConstruct would be lowered by our lower_tuples pass. Do you have any examples of real-world models that were affected by this issue ? AFAIK this issue was just thought up in converrsation

**Comment by neginraoof** [comment]
I see. So you suggest to use the lower_tuples pass prior to remove_mutation?

**Comment by eellison** [comment]
@neginraoof yep

**Comment by eellison** [comment]
Closed with https://github.com/pytorch/pytorch/pull/39111
