### ISSUE TITLE
The random seed for torchvision transforms is not fixed in PyTorch 1.6

### ISSUE THREAD

**Issue by weikunhan** [pytorch/pytorch#42331]
## To Reproduce

I create an "ImageFolderSuperpixel" data loader, which is working fine in PyTorch 1.5. In 1.6, there is a problem that transforms Compose can NOT get fix random seed for transforms.RandomHorizontalFlip(),. For example 
            transforms.Compose([
                transforms.RandomResizedCrop(30),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                normalize]))
Only transforms.RandomHorizontalFlip() can NOT get the fixed random seed. Other three are work file. 

I provide my code and unit test file. Please check: 
[bugs.zip](https://github.com/pytorch/pytorch/files/5003634/bugs.zip)

## Expected behavior

 transforms.RandomHorizontalFlip() should also have fixed random seed if setting up

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

[collect_env.zip](https://github.com/pytorch/pytorch/files/5003643/collect_env.zip)

cc @pbelevich @fmassa @vfdev-5

**Comment by weikunhan** [comment]
Someone can confirm it is a bug in Pytorch 1.6?

**Comment by vfdev-5** [comment]
@weikunhan you can set the seed with `torch.manual_seed(seed)`. Previously, it could be done with python's `random.seed(seed)`.
The change is due to input unification (PIL + Tensor). 
Hope this helps.

**Comment by weikunhan** [comment]
@vfdev-5 Thanks for the information. I tried to use torch.manual_seed(seed) in PyTorch 1.5 and 1.6. It couldn't pass the test case. However, random.seed(seed) is working fine in PyTorch 1.5 but not work fine in 1.6. 

Right now, I find a way to hack it. I use torch.manual_seed(5) and random.seed(5) same time. It can pass all test cases. I think it will help someone who has the same problem.

**Comment by vfdev-5** [comment]
@weikunhan indeed, that's true that to completely fix random seed for all transformations with torchvision 0.7 we need to use both expressions:
- `random.seed(seed)`
- `torch.manual_seed(seed)`
This due to the fact that not all transformations are already unified.

**Comment by MaratZakirov** [comment]
Seed indeed fixes random number generation for numpy and torch but somehow torchvision still generates completly different images.

torchvision.__version__ = 0.22

**Comment by cod3r0k** [comment]
It is a bad problem for reproducibility

**Comment by aramiracle** [comment]
You can solve this bug with this:

class MyColorJitter(transforms.ColorJitter):
    def __init__(self, brightness, contrast, saturation, hue, seed):
        super().__init__(brightness, contrast, saturation, hue)
        self.seed = seed

    def forward(self, img):
        torch.manual_seed(self.seed)
        random.seed(self.seed)
        return super().forward(img)
       
    And use it like this:
    
    color_jitter = MyColorJitter(brightness=brightness, contrast=contrast, saturation=saturation, hue=hue, seed=seed)

**Comment by aramiracle** [comment]
You can solve this bug with this:

class MyColorJitter(transforms.ColorJitter):
    def __init__(self, brightness, contrast, saturation, hue, seed):
        super().__init__(brightness, contrast, saturation, hue)
        self.seed = seed

    def forward(self, img):
        torch.manual_seed(self.seed)
        random.seed(self.seed)
        return super().forward(img)
       
    And use it like this:
    
    color_jitter = MyColorJitter(brightness=brightness, contrast=contrast, saturation=saturation, hue=hue, seed=seed)

**Comment by aramiracle** [comment]
You can solve this bug with this:

```
class MyColorJitter(transforms.ColorJitter):
  def init(self, brightness, contrast, saturation, hue, seed):
  super().init(brightness, contrast, saturation, hue)
  self.seed = seed
  
  def forward(self, img):
      torch.manual_seed(self.seed)
      random.seed(self.seed)
      return super().forward(img)

color_jitter = MyColorJitter(brightness=brightness, contrast=contrast, saturation=saturation, hue=hue, seed=seed)
```
