### ISSUE TITLE
fake_quantize_per_tensor_affine failed on float16 input

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#42351]
## 🚀 Feature

To support float16 (optionally bf16) in `fake_quantize_per_tensor_affine` /  `fake_quantize_per_channel_affine`

## Motivation

When `amp.auto_cast` is enabled, the fake_quantize may fail.

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @mcarilli @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @ppwwyyxx

**Comment by vkuzo** [comment]
@supriyar , would you know if this is already planned?

**Comment by supriyar** [comment]
We had this as a P2 item last half in the operator support. But I don't think it is planned for this half so far.

**Comment by raghuramank100** [comment]
We should plan on adding support for this to enable amp for training this half as a QAT perf enhancement

**Comment by ggeor84** [comment]
Just wanted to add my vote for this feature. Any current plans?

**Comment by zpahuja** [comment]
Please consider adding support for this to enable amp for training this half

**Comment by jerryzh168** [comment]
cc @raghuramank100 could you assign this issue to someone if we want to support this in this half?

**Comment by thyeros** [comment]
Second this: Please consider adding support for this to enable amp for training this half

**Comment by rosrad** [comment]
vote on this feature, it is quite useful.

**Comment by HDCharles** [comment]
note: per_tensor support is complete for fp16, I am currently working on the per_channel support

**Comment by HDCharles** [comment]
this was enabled in https://github.com/pytorch/pytorch/pull/52612

There are still some remaining issues with AMP that we are aware of but the fake_quant functions themselves are now working
