### ISSUE TITLE
JIT runtime error after upgrading to 1.6.0

### ISSUE THREAD

**Issue by edgarriba** [pytorch/pytorch#42357]
## 🐛 Bug

We are getting a runtime error during the testing with the JIT version of `kornia.rgb_to_grayscale` [[fcn](https://github.com/kornia/kornia/blob/master/kornia/color/gray.py#L40-L61)] [[fcn_jit](https://github.com/kornia/kornia/blob/master/kornia/jit/__init__.py#L6)] after upgrading to PyTorch 1.6.0.

NOTE: The error is only raised when the CUDA backend is enabled - CPU seems to be 
fine.

ERROR:
```bash
Traceback (most recent call last):
  File "rgb2gray_jit.py", line 29, in <module>
    print(torch.jit.script(rgb_to_grayscale)(x).shape)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: vector::_M_range_check: __n (which is 18446744073709551613) >= this->size() (which is 4)
```

## To Reproduce

1. `git clone https://github.com/arraiyopensource/kornia.git`
2. `cd kornia`
3. `source ./path.bash.inc`
4. `pytest test/ --device cuda --dtype float32,float64`

**OR**

run this:
```python
import torch

def rgb_to_grayscale(input: torch.Tensor) -> torch.Tensor:
    r"""Convert a RGB image to grayscale.
    See :class:`~kornia.color.RgbToGrayscale` for details.
    Args:
        input (torch.Tensor): RGB image to be converted to grayscale.
    Returns:
        torch.Tensor: Grayscale version of the image.
    """
    if not isinstance(input, torch.Tensor):
        raise TypeError("Input type is not a torch.Tensor. Got {}".format(
            type(input)))

    if len(input.shape) < 3 and input.shape[-3] != 3:
        raise ValueError("Input size must have a shape of (*, 3, H, W). Got {}"
                         .format(input.shape))

    r, g, b = torch.chunk(input, chunks=3, dim=-3)
    gray: torch.Tensor = 0.299 * r + 0.587 * g + 0.114 * b
    return gray

x = torch.rand(1,3,4,4).cuda()

print('no jit')
print(rgb_to_grayscale(x).shape)

print('jit')
print(torch.jit.script(rgb_to_grayscale)(x).shape)
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.5           py37ha1c710e_0  
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch

 - Any other relevant information:
`kornia 0.4.0`

## Additional context

This feature was already working with previous PyTorch version 1.5.0

cc @ezyang @gchanan @zou3519 @suo @gmagogsfm

**Comment by t-vi** [comment]
So I tried this on recent master, and it seems gone, at least with the self-contained repro.
@edgarriba Do you still see it?

**Comment by smkravec** [comment]
I was able to reproduce this running their minimal example on my version of torch (1.8.0a0+2dff0b3)

**Comment by edgarriba** [comment]
Right, seems to be gone with recent versions.
