### ISSUE TITLE
A question about torch.nn.Module.__Call__

### ISSUE THREAD

**Issue by AsakusaRinne** [pytorch/pytorch#42367]
In torch.nn there is an important class named Module, and it implements __Call__ with the code below:
`__call__ : Callable[..., Any] = _call_impl`
The "__Call__" returns the return of "_call_impl", how does it works? The "__Call__" doesn't has an "explicit return" while it actually returns a value, why?
I'm not familiar with Python and pytorch yet, so my question may seems a little dull...I will appreciate it if you don't mind answering my question. Thank you!

**Comment by amrishparmar** [comment]
In Python functions are treated as first class objects, so you can assign a function object to another variable trivially. Consider the following example:
```
>>> def fun():
...     pass
... 
>>> fun2 = fun
>>> fun2
<function fun at 0x7ffd26a45d40>
```
The same is happening here. `_call_impl` is being assigned to `__call__`. 

The `: Callable[..., Any]` in the middle is just a type annotation. It doesn't affect the logic of what's happening

**Comment by AsakusaRinne** [comment]
> In Python, functions are treated as first class objects, so you can assign a function object to another variable trivially (they behave like pointers). Consider the following example:
> 
> ```
> >>> def foo():
> ...     pass
> ... 
> >>> bar = foo
> >>> bar
> <function foo at 0x7ffd26a45d40>
> ```
> 
> The same is happening here. `_call_impl` is being assigned to `__call__`.
> 
> The `: Callable[..., Any]` in the middle is just a type annotation. It doesn't affect the logic of what's happening

Your answer is simple and clear, thank you very much!
