### ISSUE TITLE
iOS Issue  - PyTorch is not linked with support for cpu devices

### ISSUE THREAD

**Issue by zy885137** [pytorch/pytorch#42361]
Calling torch:: JIT :: Load () I got an error message:

PyTorch is not linked with support for cpu devices (getDeviceGuardImpl at /Users/distiller/project/c10/core/impl/DeviceGuardImplInterface.h:216)
(no backtrace available)

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi Yang,

Do you mind sharing your environment and steps to repro using the[ bug report template](https://github.com/pytorch/pytorch/issues/new?template=bug-report.md)? Thanks!

**Comment by zy885137** [comment]
> Hi Yang,
> 
> Do you mind sharing your environment and steps to repro using the[ bug report template](https://github.com/pytorch/pytorch/issues/new?template=bug-report.md)? Thanks!

Hello there,
1. I use cocoaPods to reference pytorch 1.5.0 to run my demo, and it works normally.
2. I added the .a library and header files of pytorch1.5.0 in the pod to the static library, and then called the static library.
3. After calling torch::jit::load(filePath.UTF8String); received an error: PyTorch is not linked with support for cpu devices.
4. macOS:10.15.6 XCode:11.6.

```
@implementation MSSpeechTTS {
@protected
    torch::jit::script::Module _impl;
}

- (nullable instancetype)initWithFileAtPath:(NSString *)filePath {
    self = [super init];
    if (self) {
        try {
            auto qengines = at::globalContext().supportedQEngines();
            if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
                at::globalContext().setQEngine(at::QEngine::QNNPACK);
            }
//            c10::optional<c10::Device> device = torch::Device(torch::kCPU);
            _impl = torch::jit::load(filePath.UTF8String);
            _impl.eval();
        } catch (const std::exception& exception) {
            NSLog(@"初始化错误：%s", exception.what());
            return nil;
        }
    }
    return self;
}

@end
```

**Comment by zy885137** [comment]
Before this error, I also encountered an error: Catalina C++: Using <cmath> headers yield error: no member named'signbit' in the global namespace.
I found: Error in C++ system classes cmath and math.h

So my temporary solution is:
1. In the cmath file #include<math.h> is changed to an absolute path #include</Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h>
2. Change #include_next <math.h> in the math.h file to an absolute path #include_next </Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/ math.h>

This temporarily solved the problem, but the PyTorch is not linked with support for cpu devices error occurred.

**Comment by husthyc** [comment]
> > Hi Yang,
> > Do you mind sharing your environment and steps to repro using the[ bug report template](https://github.com/pytorch/pytorch/issues/new?template=bug-report.md)? Thanks!
> 
> Hello there,
> 
> 1. I use cocoaPods to reference pytorch 1.5.0 to run my demo, and it works normally.
> 2. I added the .a library and header files of pytorch1.5.0 in the pod to the static library, and then called the static library.
> 3. After calling torch::jit::load(filePath.UTF8String); received an error: PyTorch is not linked with support for cpu devices.
> 4. macOS:10.15.6 XCode:11.6.
> 
> ```
> @implementation MSSpeechTTS {
> @protected
>     torch::jit::script::Module _impl;
> }
> 
> - (nullable instancetype)initWithFileAtPath:(NSString *)filePath {
>     self = [super init];
>     if (self) {
>         try {
>             auto qengines = at::globalContext().supportedQEngines();
>             if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
>                 at::globalContext().setQEngine(at::QEngine::QNNPACK);
>             }
> //            c10::optional<c10::Device> device = torch::Device(torch::kCPU);
>             _impl = torch::jit::load(filePath.UTF8String);
>             _impl.eval();
>         } catch (const std::exception& exception) {
>             NSLog(@"初始化错误：%s", exception.what());
>             return nil;
>         }
>     }
>     return self;
> }
> 
> @end
> ```

Could you clarify your #1 and #2 please? Did you do them separately? or you did #2 on the basis of #1?

**Comment by zy885137** [comment]
> > > 嗨，杨，
> > > 您是否介意分享您的环境和使用[错误报告模板](https://github.com/pytorch/pytorch/issues/new?template=bug-report.md)进行复制的步骤？谢谢！
> > 
> > 
> > 你好，
> > 
> > 1. 我使用cocoaPods引用pytorch 1.5.0来运行我的演示，并且它正常工作。
> > 2. 我将pod中的.a库和pytorch1.5.0的头文件添加到静态库，然后将其称为静态库。
> > 3. 调用torch :: jit :: load（filePath.UTF8String）;之后 收到错误：PyTorch未与对CPU设备的支持链接。
> > 4. macOS：10.15.6 XCode：11.6。
> > 
> > ```
> > @implementation MSSpeechTTS {
> > @protected
> >     torch::jit::script::Module _impl;
> > }
> > 
> > - (nullable instancetype)initWithFileAtPath:(NSString *)filePath {
> >     self = [super init];
> >     if (self) {
> >         try {
> >             auto qengines = at::globalContext().supportedQEngines();
> >             if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
> >                 at::globalContext().setQEngine(at::QEngine::QNNPACK);
> >             }
> > //            c10::optional<c10::Device> device = torch::Device(torch::kCPU);
> >             _impl = torch::jit::load(filePath.UTF8String);
> >             _impl.eval();
> >         } catch (const std::exception& exception) {
> >             NSLog(@"初始化错误：%s", exception.what());
> >             return nil;
> >         }
> >     }
> >     return self;
> > }
> > 
> > @end
> > ```
> 
> 您能说明一下[第一](https://github.com/pytorch/pytorch/issues/1)和[第二](https://github.com/pytorch/pytorch/issues/2)吗？您是分开做的吗？或者你做[＃2](https://github.com/pytorch/pytorch/issues/2)的基础上，[＃1](https://github.com/pytorch/pytorch/issues/1)？

Yes, #1 and #2 are made separately.

#1   It can ensure that my demo can work normally through pod.
#2  I copied libtorch in the pod and used it as a static library.

You can take a look at my picture of this project

![WX20200804-135120](https://user-images.githubusercontent.com/6452049/89257932-ba0bf280-d659-11ea-83f9-b71f270d0e9d.png)

**Comment by husthyc** [comment]
Please follow https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source if you want to use PyTorch as static library.

**Comment by husthyc** [comment]
Did you try to set up your Xcode project following https://pytorch.org/mobile/ios/#xcode-setup step by step?

**Comment by zy885137** [comment]
> Did you set up your Xcode project following https://pytorch.org/mobile/ios/#xcode-setup step by step?

I checked, I only added other linker flags: -all_load in the static library project.
I now add other linker flags: -all_load to my demo project. Now it can run normally and can work.
Thank you!
