### ISSUE TITLE
Adamax not working in Pytorch1.6

### ISSUE THREAD

**Issue by djordjemiladinovic** [pytorch/pytorch#42364]
## 🐛 Bug

I updated my pytorch from 1.5.1 to 1.6 and now I am not able to run my code. I managed to localize the error and it is related to Adamax optimizer e.g. if i switch back to Adam, then the code works fine, however Adamax is what I need.

I also noticed that in another project Adamax is working just fine.

## Error

  File "/cluster/home/djordjem/projects/snn/lib/de/ImageVE.py", line 207, in optimizer_step
    optimizer.step()
  File "/cluster/home/djordjem/.local/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/cluster/home/djordjem/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/cluster/home/djordjem/.local/lib/python3.7/site-packages/torch/optim/adamax.py", line 83, in step
    torch.max(norm_buf, 0, keepdim=False, out=(exp_inf, exp_inf.new().long()))
RuntimeError: reduce_op(): expected both outputs to have same strides, but output1 has [0, 1, 1, 1, 1] and output2 has [0, 400, 1, 1, 1]

## To Reproduce

I am unfortunately struggling to identify which part of the code is causing this behaviour. Since I intend to publish the code along with the paper, I cannot provide it here. Given that, I was unable to create a code snippet to reproduce this behaviour, not yet. 

## Environment

 - PyTorch Version: 1.6
 - OS: Linux
 - How you installed PyTorch: pip
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: tried on various NVIDIAs e.g. RTX, TeslaV100, GTX

cc @ezyang @gchanan @zou3519 @vincentqb @VitalyFedyunin @jamesr66a @ppwwyyxx

**Comment by mruberry** [comment]
A snippet to reproduce this issue would be very helpful, @djordjemiladinovic. Without it I'm not sure we'll be able to make progress.

**Comment by gchanan** [comment]
I don't think we actually need a snippet to reproduce the adamax failure; what's going on is pretty clear.

Here's the line in question:
https://github.com/pytorch/pytorch/blob/4cdbe5c4952ee6b7be24ff15b1d45d0fb593b13f/torch/optim/adamax.py#L83

`exp_inf.new().long()` will create a contiguous tensor, but there's no guarantee that `exp_inf` is contiguous: https://github.com/pytorch/pytorch/blob/4cdbe5c4952ee6b7be24ff15b1d45d0fb593b13f/torch/optim/adamax.py#L65

and reduce_op in TensorIterator checks that the strides are the same.
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorIterator.cpp#L757-L758

Here's a reproduction and a proof that it's a regression:
Version 1.5.1
```
torch.max(torch.randn(2,3).cuda(1), dim=0, out=(torch.randn(6).cuda(1)[::2], torch.randn(3).long().cuda(1)))
torch.return_types.max_out(
values=tensor([0.1383, 1.9499, 1.2522], device='cuda:1'),
indices=tensor([0, 1, 1], device='cuda:1'))
```

Version 1.6.0
```
>>> torch.max(torch.randn(2,3).cuda(1), dim=0, out=(torch.randn(6).cuda(1)[::2], torch.randn(3).long().cuda(1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: reduce_op(): expected both outputs to have same strides, but output1 has [0, 2] and output2 has [0, 1]
```

**Comment by gchanan** [comment]
Probably: https://github.com/pytorch/pytorch/pull/39029

**Comment by gchanan** [comment]
confirmed it is in fact #39029 that broke this.

**Comment by gchanan** [comment]
probably forcing the same strides would work, something like:

`torch.empty_strided(x.size(), x.stride(), dtype=torch.long, layout=x.layout, device=x.device)`
