### ISSUE TITLE
TensorIterator fails while adding tensors of different dtype

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#42374]
Repro: 
```
import torch

a = torch.zeros(1, 2, device='cpu', dtype=torch.int)
b = torch.ones(1, 2, device='cpu', dtype=torch.bfloat16)

res = a.add(b)
print(res)
```

Result: 
**RuntimeError: common_dtype_ != ScalarType::Undefined INTERNAL ASSERT FAILED at "../aten/src/ATen/native/TensorIterator.cpp":89, please report a bug to PyTorch.**

cc @ezyang @gchanan @zou3519 @nairbv

**Comment by gchanan** [comment]
this isn't a crash.

**Comment by mruberry** [comment]
This is fixed on the latest master.
