### ISSUE TITLE
[macOS] [nightlies] dlopen --: Library not loaded: @rpath/libuv.1.dylib J

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#42372]
Nightly builds for macos conda packages are currently failing when testing imports:

[CircleCI Logs](https://app.circleci.com/pipelines/github/pytorch/pytorch/195335/workflows/4a03e875-785d-4a2a-bfd2-3e5a31eb405b/jobs/6450505)
```
Jul 31 09:10:34 + echo 'Smoke testing imports'
Jul 31 09:10:34 Smoke testing imports
Jul 31 09:10:34 + python -c 'import torch'
Jul 31 09:10:34 Traceback (most recent call last):
Jul 31 09:10:34   File "<string>", line 1, in <module>
Jul 31 09:10:34   File "/Users/distiller/project/conda/envs/env_py3.8_0_20200731/lib/python3.8/site-packages/torch/__init__.py", line 189, in <module>
Jul 31 09:10:34     from torch._C import *
Jul 31 09:10:34 ImportError: dlopen(/Users/distiller/project/conda/envs/env_py3.8_0_20200731/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 2): Library not loaded: @rpath/libuv.1.dylib
Jul 31 09:10:34   Referenced from: /Users/distiller/project/conda/envs/env_py3.8_0_20200731/lib/python3.8/site-packages/torch/lib/libtensorpipe.dylib
Jul 31 09:10:34   Reason: image not found
```

Failures were introduced somewhere in this change set: https://github.com/pytorch/pytorch/compare/0444bac940695ccfa43854f9241839f759ba5f28...2f840b1662b487d5551d7230f8eb4d57645cfff5

cc @ezyang @gchanan @zou3519 @malfet

**Comment by malfet** [comment]
Very likely https://github.com/pytorch/pytorch/commit/352e15f1a2df6b93689a28c14b71a0f87f29cc02 should fix that

**Comment by seemethere** [comment]
> Very likely [352e15f](https://github.com/pytorch/pytorch/commit/352e15f1a2df6b93689a28c14b71a0f87f29cc02) should fix that
> cc: @lw

Alright, I'll keep this issue open until we see a run through of the nightly pipeline with the revert

**Comment by ezyang** [comment]
https://app.circleci.com/jobs/github/pytorch/pytorch/6472161 Looks fixed
