### ISSUE TITLE
Torchscript missing `sorted` support for str

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#42375]
```
class TestModule(torch.nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()
        
    def forward(self, list_of_str: List[str]):
        return sorted(list_of_str)

m = TestModule()
m_scripted = torch.jit.script(m)
# gives runtime error
m_scripted(["str3", "str2", "str1"]) 
```

RuntimeError: To sort a list of str must be of Tensors, ints, floats, bools or a User Defined Class that defines the __lt__ compare method, got list of str

cc @suo @gmagogsfm

**Comment by yf225** [comment]
Note that this is blocking PyPer model's conversion to TorchScript - without this we might have to resort to writing sorting algorithm in Python (perf is bad), or writing a custom op for sorting list of string (which involves much more effort).

**Comment by gmagogsfm** [comment]
This seems like a quick fix, I will give it a try.

**Comment by yf225** [comment]
Thanks so much for your help @gmagogsfm!
