### ISSUE TITLE
torch.save() serializes a bound method in OneCycleLR's state_dict, causing CUDA problems

### ISSUE THREAD

**Issue by mrcslws** [pytorch/pytorch#42376]
## 🐛 Bug

If you `torch.save` a `OneCycleLR` state dict, bad things happen. Anybody who `torch.load`s that checkpoint will often later start seeing crashes like `CUBLAS_STATUS_ALLOC_FAILED`, `CUDNN_STATUS_NOT_INITIALIZED`, or they will run out of CUDA memory. Also, the saved checkpoint is much larger than it needs to be; the serialized LR scheduler state dict contains (unintentionally) the entire serialized LR scheduler and optimizer, including any momentum tensors stored in the optimizer.

There are two issues here, I think.
- **The superficial issue:** the OneCycleLR class should stop putting a function in its state_dict, or at least switch to using a pure function or a staticmethod.
- **The root issue:** `torch.save` and `torch.load` serialize bound methods. Should they? It causes *weird* hard-to-diagnose problems. (For example, this one.)

Here is an example OneCycleLR state_dict:

```
{'total_steps': 37500,
 'step_size_up': 2342.75,
 'step_size_down': 35156.25,
 'anneal_func': <bound method OneCycleLR._annealing_linear of <torch.optim.lr_scheduler.OneCycleLR object at 0x7fea068f2780>>,
 'cycle_momentum': True,
 'use_beta1': False,
 'base_lrs': [1.0, 1.0],
 'last_epoch': 31250,
 '_step_count': 31251,
 '_get_lr_called_within_step': False,
 '_last_lr': [1.0673182506666672, 1.0673182506666672]}
```

That `anneal_func` is **very bad**. For `torch.save` to serialize this, it needs to serialize the object that it's attached to, so:
- the whole LR scheduler is serialized
- ...so the whole optimizer is serialized
- ...so every momentum tensor is serialized.

so this `_annealing_linear` quietly takes up a lot of memory. (e.g. 150 MB in my case, using resnet50)

Later, when someone `torch.load`s this checkpoint, these objects are all reconstructed. They continue to exist in memory as long as the `_annealing_linear` bound method exists. Unwittingly, the caller will have instantiated two different optimizers -- their own, and the one hiding behind the `_annealing_linear` bound method. This means there are two of every momentum tensor.

In my experience, this sometimes leads to weird CUDA errors like CUBLAS_STATUS_ALLOC_FAILED and CUDNN_STATUS_NOT_INITIALIZED later during training. These occur even if I don't call `lr_scheduler.load_state_dict()`. Simply calling `torch.load` on this checkpoint seems to corrupt my Python process (but I don't fully understand this part).

All of these issues disappear if I do `del state_dict["anneal_func"]` before calling `torch.save()`.

## To Reproduce

Here's code that shows the underlying strange behavior.

```python
import torch

def make_lr_scheduler():
    param1 = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
    sgd = torch.optim.SGD([param1], lr=0.1, momentum=0.9)
    return torch.optim.lr_scheduler.OneCycleLR(sgd, 6.0, total_steps=10)

lr_scheduler = make_lr_scheduler()
print(lr_scheduler.anneal_func)

with open("checkpoint", "wb") as f:
    torch.save(lr_scheduler.state_dict(), f)
    
lr_scheduler2 = make_lr_scheduler()
print(lr_scheduler2.anneal_func)

with open("checkpoint", "rb") as f:
    lr_scheduler2.load_state_dict(torch.load(f))
print(lr_scheduler2.anneal_func)
```

This produces the following output.

```
<bound method OneCycleLR._annealing_cos of <torch.optim.lr_scheduler.OneCycleLR object at 0x7f89c229b5c0>>
<bound method OneCycleLR._annealing_cos of <torch.optim.lr_scheduler.OneCycleLR object at 0x7f89c229b630>>
<bound method OneCycleLR._annealing_cos of <torch.optim.lr_scheduler.OneCycleLR object at 0x7f89c229beb8>>
```

As you can see, there are three different `OneCycleLR` objects (three different memory addresses) despite the fact that only two were ever created by the user.

## Expected behavior

The LR scheduler state dict should contain only things that it needs. Deserializing it shouldn't quietly instantiate an LR scheduler, an optimizer, and 150 MB of tensors that it's never going to use.

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Amazon Linux 2
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
CMake version: version 3.13.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] blas                      1.0                         mkl
[conda] botorch                   0.2.2                    pypi_0    pypi
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] gpytorch                  1.0.1                    pypi_0    pypi
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.19.1                   pypi_0    pypi
[conda] nupic-torch               0.0.1.dev0                dev_0    <develop>
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch

cc @vincentqb

**Comment by mruberry** [comment]
Thanks for reporting this issue, @mrcslws. I believe we would accept a PR fixing this, although I don't know offhand how invasive a fix would be.

**Comment by gchanan** [comment]
@vincentqb can you take a look?

**Comment by vincentqb** [comment]
Yes, this should be fixed. It seems like decorating `_annealing_cos` and `_annealing_linear` with `@staticmethod` would be enough for this instance of the bound-method-serialized issue with OneCycle ([here](https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L1231)). Is that correct? If so, I would welcome a pull request for this. Is there a unittest that would help catch such issues in the future?

Have you noticed this issue with other schedulers? In particular, I'm looking at `CyclicLR` since it also has `_triangular_scale_fn`/etc

**Comment by mrcslws** [comment]
A good unit test would be:
- Create an optimizer with a large momentum tensor. (i.e. call `optimizer.step()` at least once)
- Wrap it with an LR scheduler
- Use `torch.save` on the `lr_scheduler.state_dict()`
- Verify that the serialized file is tiny. (This will confirm that the optimizer isn't being silently serialized.)

This unit test could be applied to any of the LR schedulers.

**Comment by vincentqb** [comment]
Great, thanks for the suggestion! Are you interested in opening a pull request for this?

**Comment by mrcslws** [comment]
Not in the immediate future. I might find time to do it, but I won't be offended if someone jumps in and takes over. :)

**Comment by alimoezzi** [comment]
I have this PR https://github.com/pytorch/pytorch/pull/102627 to fix this. Please let me know if needs any change.
