### ISSUE TITLE
Dispatcher fallback mechanism internal asserts for operators with multiple returns

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#42378]
## 🐛 Bug

I attempted to call an operator on a tensor extension that goes through a fallback mechanism. For an operator that has multiple returns (like `torch.var_mean`), the implementations push multiple returns onto the stack. However, that causes an error message to be raised in the dispatcher. The error message implies that the dispatcher only expected a single return on the stack.

Is pushing all the returns onto the stack the right thing to do, or should one push a Tuple of the returns onto the stack?

## To Reproduce

Minimal example modifying `dispatcher/backend_fallback_test.cpp`: https://github.com/pytorch/pytorch/pull/42377/files

Error message: https://gist.github.com/zou3519/90428b51bf4b51285ac9c06de5c8f98e

## Environment

master

cc composability folks: @ezyang @bhosmer @smessmer

**Comment by bhosmer** [comment]
Hi Richard - yeah, the boxing wrapper is expecting a tuple of return values currently, but it looks like that's wrong - it should expect the individual values. Should have a fix up shortly, thanks for flagging!

**Comment by bhosmer** [comment]
@zou3519 #42432 should fix this. Will land as soon as I can get @smessmer to eyeball it 😁

**Comment by zou3519** [comment]
Thank you @bhosmer for the quick fix!

**Comment by zou3519** [comment]
Fixed via #42437
