### ISSUE TITLE
Add NMS version which can do confidence based thresholding

### ISSUE THREAD

**Issue by anujgupt-github** [pytorch/pytorch#42370]
## 🚀 Feature
Add NMS version which takes confidence threshold and prunes out low confidence scores from the entire prediction.

## Motivation

Motivation is that if Pytorch NMS requires only boxes which cross confidence threshold, it means that the filtering should be done apriori. This filtering usually results in an ONNX NONZERO operator, and if using GLOW, NONZERO can't be supported, owing to the dynamic shape of the output tensor. ONNX supports NonMaxSuppression node, which does exactly the same thing. If pytorch also supports this, conversion of Pytorch NMS -> ONNX NMS becomes much easier.

## Pitch

Add an additional input to NMS operator (confidence_threshold). New NMS operator takes entire model prediction as an input, and based on the confidence_threshold, filters out boxes lower than the threshold before moving to IOU.

**Comment by mruberry** [comment]
Should this actually be a request for torchvision, since it implements nms? (https://pytorch.org/docs/stable/torchvision/ops.html?highlight=nms#torchvision.ops.nms)

**Comment by anujgupt-github** [comment]
OK @mruberry . How do you propose I migrate the request to torchvision?

**Comment by mruberry** [comment]
You could open an issue on the torchvision github: https://github.com/pytorch/vision/issues.

**Comment by anujgupt-github** [comment]
opening the FR in torchvision.
