### ISSUE TITLE
diagonal() bug!

### ISSUE THREAD

**Issue by fatalfeel** [pytorch/pytorch#42414]
int64_t scale		= 4; //1x4
	float	value 		= 0.5;

        Tensor	std_action 	= torch::full({scale}, value);
	Tensor	act_mat  	= torch::diag(std_action);

	IntArrayRef s00 		= act_mat.sizes();
	float*	   data_out00 	= (float*)act_mat.data_ptr();
	for(int i=0; i<4; i++)
	{
		std::cout << data_out00[i*4+0];
		std::cout << " ";
		std::cout << data_out00[i*4+1];
		std::cout << " ";
		std::cout << data_out00[i*4+2];
		std::cout << " ";
		std::cout << data_out00[i*4+3];
		std::cout << std::endl;
	}
	act_mat 				= act_mat.diagonal();
	float*		data_out09 	= (float*)act_mat.data_ptr();
	IntArrayRef s05 		= act_mat.sizes();
	std::cout << data_out09[0];
	std::cout << " ";
	std::cout << data_out09[1];
	std::cout << " ";
	std::cout << data_out09[2];
	std::cout << " ";
	std::cout << data_out09[3];
	std::cout << std::endl;

0.5 0 0 0
0 0.5 0 0
0 0 0.5 0
0 0 0 0.5

0.5 0 0 0  //error. 
should be 0.5  0.5  0.5  0.5 in python is OK

s05	         c10::IntArrayRef	{...}	
Data	const long *	0x1735108	
*Data	const long	4	
Length	c10::ArrayRef<long>::size_type	1

**Comment by fatalfeel** [comment]
i trace into bottom 
result  = as_strided      return error number

**Comment by ngimel** [comment]
This is not a bug, `diagonal` returns a view into the source matrix, so you should not print consecutive elements of the result and expect them to be diagonal elements. If you want a copy of diagonal elements rather than a view into source matrix, use `diag`.

**Comment by fatalfeel** [comment]
not agree!
because need diagonal() in to another Tensor and data is wrong!
when i use in python it correct

**Comment by ngimel** [comment]
You are not printing elements of the tensor, you are printing elements of the underlying memory storage ignoring strides information of the tensor. Try `std::cout << act_mat` and you'll see that actual tensor elements are right.

**Comment by fatalfeel** [comment]
thanks pretty will try~~~

**Comment by fatalfeel** [comment]
try fail

action = torch::stack(vec_act).reshape({1,-1});
	IntArrayRef s01 		= action.sizes();
	double*		data_out01 	= (double*)action.data_ptr();
	for(int i=0; i<4; i++)
	{
		std::cout << data_out01[i*4+0];
		std::cout << " ";
		std::cout << data_out01[i*4+1];
		std::cout << " ";
		std::cout << data_out01[i*4+2];
		std::cout << " ";
		std::cout << data_out01[i*4+3];
		std::cout << std::endl;
	}

	torch::Tensor action2 = action.diagonal();
	std::cout << action2;
/////////////////////////


List_NetAddRear: socket 11 added
0.137607 -0.914265 0.199676 0.489233
2.69451e-310 3.21143e-322 1.27759e-316 2.69451e-310
2.74883e-310 2.70342e-310 2.75775e-310 2.75775e-310
2.74883e-310 1.39841e-318 2.70342e-310 2.75775e-310
 0.1376

//screen
http://www.mediafire.com/view/y1g7on6tux00wxw/2020-08-03_21-24-36_%25E7%259A%2584%25E8%259E%25A2%25E5%25B9%2595%25E6%2593%25B7%25E5%259C%2596.png/file#

**Comment by ngimel** [comment]
I don't know what exactly is wrong with your code, for one, you are reshaping `action` to be a 1xn tensor. The following example works:
```
#include <torch/torch.h>
#include <iostream>

int main() {
  torch::Tensor tensor = torch::randn({4,4});
  auto td1 = tensor.diagonal();
  auto td2 = tensor.diag();
  std::cout << tensor << std::endl;
  std::cout << td1 << std::endl;
  std::cout << td2 << std::endl;
}
```
and produces
```-0.4693  0.0351  0.0658  0.2752
 0.8939  1.0137  1.3332  0.8798
-0.8665  1.3351  0.3980  0.3829
-0.2486  0.1471  0.4928 -0.6057
[ CPUFloatType{4,4} ]
-0.4693
 1.0137
 0.3980
-0.6057
[ CPUFloatType{4} ]
-0.4693
 1.0137
 0.3980
-0.6057
[ CPUFloatType{4} ]
```
As I've said, `diagonal` creates a view of original tensor, `diag` produces a new tensor, so use whichever suits your needs better.

**Comment by fatalfeel** [comment]
Thank you Pretty.........will check again what's happen!!! 
you give a good idea to check!
thank u 
thank u

**Comment by fatalfeel** [comment]
double shape = 4;
double scale = 0.5
Tensor action_std	= torch::full({shape}, scale);
Tensor mat_std 	= torch::diag(action_std);
mat_std	= mat_std.diagonal();

	IntArrayRef s02 		= mat_std2.sizes();
	double*		data_out02 	= (double*)mat_std2.data_ptr();
	std::cout << data_out02[0];
	std::cout << " ";
	std::cout << data_out02[1];
	std::cout << " ";
	std::cout << data_out02[2];
	std::cout << " ";
	std::cout << data_out02[3];
	std::cout << std::endl;
