### ISSUE TITLE
einsum fails in THCudaBlas_DgemmStridedBatched only when running on GPU

### ISSUE THREAD

**Issue by boeddeker** [pytorch/pytorch#42418]
## 🐛 Bug

I called `torch.einsum` with manipulated strides. And got the error (Two errors, because I tested in different environments):
```
RuntimeError: cublas runtime error : an invalid numeric value was used as an argument at /pytorch/aten/src/THC/THCBlas.cu:281  # torch.__version__ 1.7.0.dev20200705+cu101
RuntimeError: cublas runtime error : an invalid numeric value was used as an argument at /pytorch/aten/src/THC/THCBlas.cu:359  # torch.__version__ 1.5.1
```

## To Reproduce
I did some memory optimizations for https://github.com/fgnt/nara_wpe/pull/47/files .
To keep it simple in this issue, I produced a toy example that also fails:

```python
import torch
print('torch.__version__', torch.__version__)

x = torch.tensor([[1., 2, 3], [4., 5, 6]]).to(0)

# Do segment_axis
# https://github.com/fgnt/nara_wpe/blob/ae0fd6444a6bb03aa6e29ea2b698e6b73d596253/nara_wpe/wpe.py#L14
# This is a view on the input data, but with a segmentation that is used for example in the stft.
# This view can save large memory.
stride = list(x.stride())
stride.insert(1, 1)
shape = list(x.size())
shape.insert(1, 2)
shape[-1] -= 1
c = torch.as_strided(x, size=shape, stride=stride)

print(c.stride(), c.shape)

torch.einsum('...ab,...bc->...ac', c, c)
```

The stdout on one computer is:
```
torch.__version__ 1.7.0.dev20200705+cu101
(3, 1, 1) torch.Size([2, 2, 2])
 ** On entry to SGEMM  parameter number 8 had an illegal value
...
RuntimeError: cublas runtime error : an invalid numeric value was used as an argument at /pytorch/aten/src/THC/THCBlas.cu:281
```

and on another:

```
torch.__version__ 1.5.1
(3, 1, 1) torch.Size([2, 2, 2])
...
RuntimeError: cublas runtime error : an invalid numeric value was used as an argument at /pytorch/aten/src/THC/THCBlas.cu:359
```

## Expected behavior

That the toy example works.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.5.1 and 1.7.0.dev20200705+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 11.0 and 10.X (I do not know the exact cuda value, probably 10.1)
 - GPU models and configuration: GTX 980 and GTX1080
 - Any other relevant information:

## Additional context

cc @ngimel @mruberry @rgommers @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by mruberry** [comment]
Thank you for reporting this issue, @boeddeker! We would accept a patch fixing this.

**Comment by boeddeker** [comment]
@IvanYashchuk Thank you for the fast fix. I tested now torch 1.7.0.dev20200807 and the code is now executable.
