### ISSUE TITLE
Model Parameters of MultiheadAttention is different in python and C++

### ISSUE THREAD

**Issue by VinodSKumar** [pytorch/pytorch#42424]
## MultiheadAttention model parameters are different in python and C++.
In C++, MultiheadAttention module's parameter is no set, its Linear sub-module's parameters can be retrieved C++. 
In python parameters of the module and sub module can be retrieved.

The corresponding C++ code with output is as follows
```c++
#include <torch/torch.h>
#include <iostream>
namespace nn = torch::nn;
int main() {
  int64_t d_model = 4;
  int64_t nhead = 2;
  double dropout = 0.0;
  nn::MultiheadAttention mmodel = nn::MultiheadAttention(nn::MultiheadAttentionOptions(d_model, nhead).dropout(dropout));
  for (const auto& module : mmodel->modules()) {
    std::cout<< " Module name :" << module->name() << std::endl;
    for (auto& param : module->named_parameters(false)) {
      std::cout<< param.key() << ":" << param.value() << std::endl;
    }
  }
}
```
C++ Output:

 Module name :torch::nn::MultiheadAttention
 Module name :torch::nn::LinearImpl
weight:-0.3390  0.1080 -0.0194 -0.1426
 0.0612  0.0071  0.1883  0.1399
-0.2122  0.4950 -0.2251  0.0851
 0.3598  0.0617 -0.3281 -0.0391
[ CPUFloatType{4,4} ]
bias: 0
 0
 0
 0
[ CPUFloatType{4} ]

Python code with output is as follows

```python
import torch.nn as nn
d_model = 4
nhead = 2
dropout = 0.0
net = nn.MultiheadAttention(d_model, nhead, dropout=dropout)
for m in net.modules():
    print('Module name :', m)
    for nm, p in m.named_parameters(recurse=False):
        print(nm, ":", p)
```
Python Output:

Module name : MultiheadAttention(
  (out_proj): _LinearWithBias(in_features=4, out_features=4, bias=True)
)
in_proj_weight : Parameter containing:
tensor([[ 0.3215,  0.1712, -0.4258,  0.0608],
        [ 0.1573, -0.3351, -0.5111,  0.1464],
        [-0.2922,  0.0303,  0.5510, -0.5638],
        [ 0.3144,  0.2177,  0.1631,  0.0863],
        [ 0.5004, -0.2727,  0.3545, -0.1129],
        [ 0.4676, -0.2856, -0.0074, -0.5064],
        [-0.5378,  0.2378,  0.1775, -0.1606],
        [-0.0225, -0.5279,  0.4279, -0.3752],
        [ 0.4622, -0.2481, -0.3727,  0.5852],
        [-0.6048, -0.4132, -0.6092, -0.5233],
        [-0.3640,  0.1864, -0.3457, -0.5625],
        [ 0.2493, -0.3487, -0.3142, -0.1200]], requires_grad=True)
in_proj_bias : Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
Module name : _LinearWithBias(in_features=4, out_features=4, bias=True)
weight : Parameter containing:
tensor([[-0.3266,  0.3457,  0.2251, -0.3043],
        [-0.0438,  0.4598, -0.0973,  0.3782],
        [ 0.0520,  0.3891, -0.1004, -0.2929],
        [ 0.0734,  0.2197, -0.2849,  0.2117]], requires_grad=True)
bias : Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)

Am I missing something in the C++ usage, or is there a bug. Need help to confirm C++ API usage. 
 

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
@VinodSKumar 
Yep, I found this as well. I think I fixed it and the code is merged already. Can you try using latest master branch and let me know if this still the problem?

**Comment by VinodSKumar** [comment]
@glaringlee Thanks for the fix. we are able to access the parameters in c++. 

Below is the logs from latest

Module name :torch::nn::MultiheadAttention
in_proj_weight: 0.2995  0.5297 -0.4092 -0.3857
-0.5304  0.2763  0.1851 -0.2845
-0.5156 -0.2275  0.4313 -0.5464
 0.3775 -0.5362 -0.5905 -0.1312
-0.3380  0.1951 -0.5954  0.6012
-0.1113  0.5641 -0.1052  0.1242
 0.2003 -0.4684 -0.4139 -0.3167
-0.3513 -0.0350 -0.4654 -0.3853
 0.4510 -0.0153  0.5620  0.5468
 0.5756 -0.3842  0.4061 -0.1789
-0.1104 -0.3945  0.4211 -0.5939
 0.1338  0.4631 -0.1081  0.5188
[ CPUFloatType{12,4} ]
in_proj_bias: 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
[ CPUFloatType{12} ]
 Module name :torch::nn::LinearImpl
weight: 0.3220  0.4806 -0.4374  0.4617
-0.0088 -0.1826 -0.1501  0.0427
-0.2049 -0.4124  0.0247 -0.1894
 0.1453  0.4747  0.3320 -0.0755
[ CPUFloatType{4,4} ]
bias: 0
 0
 0
 0
[ CPUFloatType{4} ]
