### ISSUE TITLE
Cannot Import SWA Utils

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/pytorch#42435]
## 🐛 Bug

Unable to import `swa_utils`.

PyTorch: - Version 1.6
OS: - Windows and Linux
Tested on CUDA as well as CPU only installation

This import failed on all.

### To reproduce

Simply run

```
swa_scheduler = torch.optim.swa_utils.SWALR(
                optimizer, anneal_strategy="linear", anneal_epochs=20, swa_lr=0.05
            )
           AttributeError: module 'torch.optim' has no attribute 'swa_utils'
AttributeError: module 'torch.optim' has no attribute 'swa_utils'
```

### Possible Fix

The problem may be in the init file [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/__init__.py)
`swa_utils` is not imported. 

Adding line from `.swa_utils import AveragedModel, SWALR` will allow it to import 

### Current Alternatives

I am able to do 
```
from torch.optim.swa_utils import SWALR
```

Then I can use SWALR properly.

It would nice If I could use the swa_utils itself to import SWALR. I'm Not sure if this is a bug or this is the way it was designed.

This feature works now. But it would be nice if it would be in `optim` or I can import `swa_utils` as well.

cc @vincentqb

**Comment by vincentqb** [comment]
Thanks for catching this! Do you want to open a pull request to add the module in `__init__`? This should work:
```python
import .swa_utils as swa_utils
```

**Comment by vincentqb** [comment]
Thanks for catching this! PR opened to address this.

**Comment by oke-aditya** [comment]
👍 Great.

**Comment by Vadkoz** [comment]
Same problem now.  torch 1.5.1, windows 10

**Comment by vincentqb** [comment]
Does `from torch.optim.swa_utils import SWALR` work?

**Comment by oke-aditya** [comment]
This feature came in torch 1.6 + so you won't be able to use in torch 1.5.1.
It is broken on torch 1.6 but fixed on master. 
But you can do
```
from torch.optim.swa_utils import SWALR  # on PyTorch 1.6
```
