### ISSUE TITLE
Why is CPU utilization so low when using OpenBLAS as BLAS?

### ISSUE THREAD

**Issue by Codingrunningman** [pytorch/pytorch#42433]
### Why is CPU utilization so low when using OpenBLAS as BLAS?
I compile the source code(version:v1.4.1) on ARMv8 machine(aarch64). MKL do not support ARM, so I choose the OpenBLAS as the BLAS.
And when I installed it successfully, I found it has a low CPU utilization.Does the architecture or the source code cause this? 

### configuration
```
Collecting environment information...
PyTorch version: 1.4.0a0+7404463
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux release 7.6.1810 (AltArch)
GCC version: (GCC) 7.1.0
CMake version: version 3.16.5

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.4.0a0+7404463
[conda] Could not collect
```
machine
```
Linux aln220 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
```
compile message
[compile message](https://github.com/Codingrunningman/Pytorch-issue/blob/master/compile.out)

compile command
```
export USE_OPENMP=1
export USE_CUDA=0
export BLAS=OpenBLAS
export OpenBLAS_HOME=/opt/openblas
python3 setup.py install
```

### problem
I run the following benchmark
```
import timeit
import torch
runtimes = []
threads = [1] + [t for t in range(2, 49, 2)]
for t in threads:
    torch.set_num_threads(t)
    r = timeit.timeit(setup = "import torch; x = torch.randn(1024, 1024); y = torch.randn(1024, 1024)", stmt="torch.mm(x, y)", number=100)
    runtimes.append(r)
    print("{} is done.Time is {}".format(t,r))
```
I get the result
```
1 is done.Time is 15.510971342213452
2 is done.Time is 15.48298014793545
4 is done.Time is 15.502299554878846
6 is done.Time is 15.491661492967978
8 is done.Time is 15.499503097962588
10 is done.Time is 15.52067736000754
...
```
And I found a very low CPU utilization? What is the reason?

cc @csarofeen @ptrblck @VitalyFedyunin @ngimel

**Comment by agolynski** [comment]
Cross referencing https://discuss.pytorch.org/t/the-difference-between-openblas-and-mkl/91321

Seems like openblas uses one thread here? How did you install openblas, did you enable openmp when installing it, e.g. https://github.com/xianyi/OpenBLAS/issues/1591.

**Comment by Codingrunningman** [comment]
Actually, I set the variable USE_OPENMP to 1 before I compile the source code. I am not sure if this will make openblas compile correctly into a multithread version.
In the compile message, I found it
```
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -Wnon-virtual-dtor
```
So I think I install openblas with oepnmp successfully.

**Comment by Codingrunningman** [comment]
I tried to compile the numpy with OpenBLAS. Then I found numpy can not use multi threads. However I compile the OpenBLAS with this command
```
make USE_OPENMP=1
```
and I compile it successfully. I do not know the reason. Thanks for your help, I will detect it.

**Comment by Codingrunningman** [comment]
I noticed a strange phenomenon, when I set this environment variable USE_OPENMP to 0, Pytorch can use multithreading?

However when I set this variable USE_OPENMP to 1, pytorch can not use multithreading. I am totally confused.
