### ISSUE TITLE
pytorch distrubuted example

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#4246]
Hi, everyone
     I'm use pytorch0.3, and i want to use pytorch.distributed module for training models on multi-nodes. I follow the tutorial in [here](http://pytorch.org/docs/master/distributed.html), this really helps me understanding the distributed training using pytorch.
    However, this tutorial does not tell me how can i init my program across multi-nodes, and to the best of my knowledge, pytorch does support distributed training on multi-nodes, and i believe the configuration will be very simple, i'll be glad to any help, thanks.

**Comment by apaszke** [comment]
There are some more docs in the [`torch.distributed` section](http://pytorch.org/docs/master/distributed.html#initialization) and you can look into the [imagenet example](https://github.com/pytorch/examples/blob/master/imagenet/main.py).

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
