### ISSUE TITLE
torchfetch - detect hardware capabilities for PyTorch install

### ISSUE THREAD

**Issue by abitrolly** [pytorch/pytorch#42466]
## 🚀 Feature

Provide small script that detects hardware system capabilities for running PyTorch and/or different types of payloads.

## Motivation

I'm always frustrated when I don't understand if I have sufficient hardware for certain tasks (distributed computing, virtualisation), and what the performance of my hardware would be. It would be very nice to fork/extend tools like `neofetch` to show hardware compatibility stats for PyTorch prior to installing it. For an inspiration.

![image](https://user-images.githubusercontent.com/8781107/89210036-10c8ec00-d5c8-11ea-98ad-9b11c7512e2c.png)

## Pitch

```
          /:-------------:\          anatoli@blackred (86.57.247.127)
       :-------------------::        ---------------- 
     :-----------/shhOHbmp---:\      OS: Linux x86_64 (Fedora)
   /-----------omMMMNNNMMD  ---:
  :-----------sMMMMNMNMP.    ---:    CPU: Intel i5-4300U (4) @ 2.900GHz
 :-----------:MMMdP-------    ---\   GPU: Intel Haswell-ULT (Not Supported)
,------------:MMMd--------    ---:   Memory: 5522MiB / 7660MiB 
:------------:MMMd-------    .---: 
:----    oNMMMMMMMMMNho     .----:   Python: 3.8.5
:--     .+shhhMMMmhhy++   .------/   PyTorch: Not Detected (1.6 Available)
:-    -------:MMMd--------------:    CUDA: No Hardware
:-   --------/MMMd-------------;
:-    ------/hMMMy------------:
:-- :dMNdhhdNMMNo------------;       
:---:sdNMMMMNds:------------: 
:------:://:-------------::
:---------------------://            
```

## Alternatives

Interested to know myself. This might be implemented by some PyTorch installers for some platforms.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py already does some of this

**Comment by ezyang** [comment]
We're not going to implement this, but feel free to make a little third party package to do this, or submit some improvements to `collect_env.py` to get more data!
