### ISSUE TITLE
[Macos][CircleCI] Test failed in test_dataloader.py

### ISSUE THREAD

**Issue by glaringlee** [pytorch/pytorch#42481]
Keep getting CI test failure in test_dataloader.py within pytorch_macos_10_13_py3_test.
File this issue to track the root cause if necessary.

https://app.circleci.com/pipelines/github/pytorch/pytorch/194865/workflows/761bdf70-27f0-4dde-84f1-dd5d6a85fff8/jobs/6477760

cc @ezyang @seemethere

**Comment by malfet** [comment]
@glaringlee please do not disable the test, but rather rebase your PR past  https://github.com/pytorch/pytorch/pull/42191 (test fails if run with python-3.8 on Mac)
