### ISSUE TITLE
state_dict for quantized models

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#42497]
According to https://discuss.pytorch.org/t/nightly-packed-params-no-longer-returned-via-state-dict-method/84588/6, state_dict for quantized model seems to be problematic in 1.6

to repro:
```python
import torch
from torchvision.models.quantization import mobilenet as qmobilenet


def quantize_model(model, inp):
    model.fuse_model()
    model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
    torch.quantization.prepare(model, inplace=True)
    model(inp)
    torch.quantization.convert(model, inplace=True)


qmodel = qmobilenet.mobilenet_v2(pretrained=True).eval()

pt_inp = torch.rand((1, 3, 224, 224))
quantize_model(qmodel, pt_inp)
script_module = torch.jit.trace(qmodel, pt_inp).eval()

graph = script_module.graph
print(script_module.state_dict())
_, params = torch._C._jit_pass_lower_graph(graph, script_module._c)
```

cc @ezyang @gchanan @zou3519 @mruberry @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by raghuramank100** [comment]
Not sure if this is something that should be fixed. Once you have a script model, there is no notion of a state dict, we need to provide an API to access the quantized weights of a scripted model instead of using state_dict. @jerryzh168 , would you be able to work on this?

**Comment by jerryzh168** [comment]
I think `state_dict` in torchscript model is not supported.
replied in the discussion forum, we can follow up there.
