### ISSUE TITLE
mypy type checking errors

### ISSUE THREAD

**Issue by min-xu-ai** [pytorch/pytorch#42508]
## 🐛 Bug

Hi, this could be partially fixed in #32824. I have some mypy errors like:

```
fairscale/nn/data_parallel/oss_ddp.py:141: error: "Tensor" has no attribute "copy_"
fairscale/nn/data_parallel/oss_ddp.py:159: error: "Tensor" has no attribute "div_"
fairscale/nn/data_parallel/oss_ddp.py:161: error: Module has no attribute "reduce"
fairscale/nn/data_parallel/oss_ddp.py:169: error: "Tensor" has no attribute "copy_"
fairscale/nn/data_parallel/oss_ddp.py:186: error: "Parameter" has no attribute "new"
```

This is from 1.5.1

Feel free to close if already fixed.

cc @ezyang @malfet @rgommers

**Comment by agolynski** [comment]
@min-xu-ai Could you provide code that is causing these failures?

**Comment by min-xu-ai** [comment]
Thanks @agolynski. In this PR: https://github.com/facebookresearch/fairscale/pull/19/files#diff-0602a4e171eb461bdf6cd20fa788c4cfR133-R135

The lines with # type: ignore are the corresponding code.

**Comment by ezyang** [comment]
On a master copy of PyTorch, in `torch/_C/__init__.pyi` I do see `copy_` on TensorBase. I'm going to guess that this is fixed on master. Please feel free to reopen if you update to master and still have problems.

**Comment by min-xu-ai** [comment]
Thanks you @ezyang, can you please also kindly check the function for distributed.reduce() as well as Parameter.new()?

**Comment by ezyang** [comment]
new is on Tensor. reduce() is probably a legit bug in your code, since it's looking for reduce on Module but you probably need a more specialized type there.

**Comment by min-xu-ai** [comment]
> new is on Tensor. reduce() is probably a legit bug in your code, since it's looking for reduce on Module but you probably need a more specialized type there.

Can you elaborate why it is a bug to call reduce from the module? It seems that's what the doc is suggesting:

https://pytorch.org/docs/stable/distributed.html#torch.distributed.reduce

When I click on the "Source" above, it does jump to c10d implementation of reduce. Maybe `reduce` is dynamically typed and hence tricked mypy?

**Comment by ezyang** [comment]
Oh, I misinterpreted the error message. reduce is probably still a problem on master. If you could double check on a nightly and then reopen that would be helpful.

**Comment by min-xu-ai** [comment]
Thanks again for your help. I installed the nightly in an venv:

```
[ins] In [2]: torch.__version__
Out[2]: '1.7.0.dev20200805+cpu'
```

Turns out, our repo has some type stubs defined, which makes things confusing. After removing the stubs, I see this error for reduce() function now:

```
fairscale/nn/data_parallel/oss_ddp.py:53: error: Call to untyped function "__init__" in typed context
fairscale/nn/data_parallel/oss_ddp.py:58: error: Call to untyped function "get_rank" in typed context
fairscale/nn/data_parallel/oss_ddp.py:155: error: Call to untyped function "reduce" in typed context
```

The code for __init__ and get_rank is

```
    def __init__(
        self, module: nn.Module, oss: OSS, world_size: int, process_group: Any = None, buffer_size: int = 2 ** 28
    ):
        super().__init__()

        self.module = module
        self.world_size = world_size
        self.process_group = process_group if process_group is not None else dist.group.WORLD
        self.rank = dist.get_rank(self.process_group)
```

But I am not sure this needs to be fixed in pytorch. Maybe those code is meant to be untyped. So I am not reopening.

**Comment by ezyang** [comment]
it would be great for us to eventually fix this, but yes, PyTorch is unlikely to be strict typeable for the forseeable future.
