### ISSUE TITLE
inplace operation error when using nn.ReLU without setting inplace=True

### ISSUE THREAD

**Issue by wangerxiao001** [pytorch/pytorch#42525]
## ❓ When I try to pass some preseted params to nn.ReLU activation function without setting inplace=True, but still got inplace operation error as follows.

1. my code 

- initialize

`
self.p6_w1 = nn.Parameter(torch.ones(2, dtype=torch.float32), requires_grad=True)
self.p6_w1_relu = nn.ReLU()
`

- using 
`
p6_w1 = self.p6_w1_relu(self.p6_w1)
`

- error
`
  File "/home/ubuntu/wangxinglie/.conda/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/ubuntu/wangxinglie/.conda/envs/myenv/lib/python3.7/site-packages/torch/nn/functional.py", line 1061, in relu
    result = torch.relu_(input)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
`

I have set my model to train mode with `model.train()`, and I knew that the forementioned error will occur when setting `inplace=True` in relu function. But I just use the default setting. Was I miss something or pytorch will set `inplace=True` in relu function during training mode?

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by mariosasko** [comment]
You must be missing something. The only thing that `model.train()` does is that it changes the `self.traning` flag of the main module(model) and its submodules(nn.Dropout(), etc.). This flag is important in cases where the module's behaviour between the training phase and the evaluation differs (nn.Dropout, nn.BatchNorm, etc.). `nn.ReLU` just ignores that flag.

**Comment by wangerxiao001** [comment]
> You must be missing something. The only thing that `model.train()` does is that it changes the `self.traning` flag of the main module(model) and its submodules(nn.Dropout(), etc.). This flag is important in cases where the module's behaviour between the training phase and the evaluation differs (nn.Dropout, nn.BatchNorm, etc.). `nn.ReLU` just ignores that flag.

Thanks, I will check it!

**Comment by wangerxiao001** [comment]
error found in model initialize

**Comment by liuyuue** [comment]
Hi, I am running into a similar error. Could you share what problems in initialization you fixed?

**Comment by liuyuue** [comment]
> error found in model initialize
Hi, I am running into a similar error. Could you share what problems in initialization you fixed?

**Comment by liuyuue** [comment]
> error found in model initialize
Hi, I am running into a similar error. Could you share what problems in initialization you fixed?
