### ISSUE TITLE
ProcessGroupRpcBackendOptions cannot found

### ISSUE THREAD

**Issue by BreakVoid** [pytorch/pytorch#42524]
## 🐛 Bug

ImportError: cannot import name 'ProcessGroupRpcBackendOptions' from 'torch.distributed.rpc' (C:\Users\kesongyu3\Anaconda3\envs\torch\lib\site-packages\torch\distributed\rpc\__init__.py)

## To Reproduce

1. Run [main.py](https://github.com/pytorch/examples/blob/master/distributed/rpc/ddp_rpc/main.py) directly.

## Expected behavior

Since the unexpected ImportError, I did not know what the expected behavior should be.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.2/7.6.5
 - GPU models and configuration: RTX 2060 Super
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jjlilley

**Comment by mrshenli** [comment]
Hey @BreakVoid, `torch.distributed` does not support Windows yet. There is an on-going effort to add Windows support. See #42095. I am closing this issue, please feel free to open an new issue if you hit similar errors in Linux or MacOS. Thanks!
