### ISSUE TITLE
master docs push isn't working

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#42532]
https://github.com/pytorch/pytorch/pull/41228 added docs for Stochastic Weight Averaging. However, they haven't appeared on the master documentation yet (https://pytorch.org/docs/master/optim.html, scroll all the way to the bottom).

I suspect something is up with https://github.com/pytorch/pytorch/pull/42136 (@seemethere, do you know how to check if the jobs that PR introduced are running?), which was merged at around the same time as #41228 .

We should have better testing for if the docs build is online or not.

cc @ezyang @gchanan @zou3519 @jlin27 @seemethere

**Comment by zou3519** [comment]
Hmm, looks like the nightly doc pushes have failed for the past week: https://circleci.com/gh/pytorch/workflows/pytorch/tree/nightly

**Comment by gchanan** [comment]
@brianjo

**Comment by zou3519** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/42552
