### ISSUE TITLE
DDP Communication Hook: single process multiple device mode

### ISSUE THREAD

**Issue by sinannasir** [pytorch/pytorch#42542]
DDP communication hook introduced by #39272 does not support single process multiple device (SPMD) mode.
In `Reducer::register_comm_hook`,  we check this condition by
https://github.com/pytorch/pytorch/blob/fc1801774fa2addd13cfc2a3ea8359bcc578d2fb/torch/csrc/distributed/c10d/reducer.cpp#L1135-L1137

Since `process_group.allreduce()` gets list of Tensor, SPMD should work, but we don't promise on features without test coverage. We should add tests for SPMD mode, and then we can imply DDP comm hook would work for both SPMD DDP and SPSD DDP. We disable SPMD mode for now.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment]
Have we added the relevant documentation that this is not expected to work with SPMD mode somewhere in the docs?

**Comment by sinannasir** [comment]
> Have we added the relevant documentation that this is not expected to work with SPMD mode somewhere in the docs?

Yes, we do
https://github.com/pytorch/pytorch/blob/cd74fe2d98498acbabfe5ce66f448df74035275a/torch/nn/parallel/distributed.py#L659-L661

Additionally, we check this in `reducer`:
https://github.com/pytorch/pytorch/blob/cd74fe2d98498acbabfe5ce66f448df74035275a/torch/csrc/distributed/c10d/reducer.cpp#L1137-L1139

**Comment by SciPioneer** [comment]
SPMD mode is going to be deprecated (#54454). Close this issue now.
