### ISSUE TITLE
Is there another way to install pytorch in the develop mode?

### ISSUE THREAD

**Issue by YHuiX** [pytorch/pytorch#42540]
I want to install pytorch in the develop mode, so I have to build it from source code according to the tutorial. But the errror strike me, telling me that my memory is insufficient. 
I have find similar issue, peterjc123 say that it is mainly caused by the merging of caffe.
It seems that I can't build it from source code, SO I want to ask is there another way to install TORCH in the develop mode?
thank you !!!

cc @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi @ezyang

**Comment by malfet** [comment]
Please share the error message you are seeing.
And  what are the reason you want to build pytorch in develop mode? 
If you just want to use libtorch C++ interface, then one can download it from https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.6.0.zip

**Comment by YHuiX** [comment]
Well I want to study the source code, and I see that I can modify the python part code and make it work without building again, if pytorch is installed in the develop mode. I think this will be helpful for me to study.
The issue I find is https://github.com/pytorch/pytorch/issues/27215
And my error is :
[3/1030] Linking CXX shared library bin\torch_cpu.dll
FAILED: bin/torch_cpu.dll lib/torch_cpu.lib
cmd.exe /C "cd . && D:\CMake\cmake-3.17.3-win64-x64\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cpu.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100171~1.0\x64\mt.exe --manifests  -- E:\VisualStudio\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cpu.rsp  /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO   && cd ."
LINK: command "E:\VisualStudio\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cpu.rsp /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cpu.dll.manifest" failed (exit code 1102) with the following output:
  Creating library lib\torch_cpu.lib and objectlib\torch_cpu.exp
LINK : fatal error LNK1102: out of memory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 734, in <module>
    build_deps()
  File "setup.py", line 318, in build_deps
    cmake=cmake)
  File "D:\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "D:\pytorch\tools\setup_helpers\cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "D:\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\Python\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.

**Comment by YHuiX** [comment]
> Please share the error message you are seeing.
> And what are the reason you want to build pytorch in develop mode?
> If you just want to use libtorch C++ interface, then one can download it from https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.6.0.zip

Well I want to study the source code, and I see that I can modify the python part code and make it work without building again, if pytorch is installed in the develop mode. I think this will be helpful for me to study.
The issue I find is #27215
And my error is :
[3/1030] Linking CXX shared library bin\torch_cpu.dll
FAILED: bin/torch_cpu.dll lib/torch_cpu.lib
cmd.exe /C "cd . && D:\CMake\cmake-3.17.3-win64-x64\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cpu.dir --rc=C:\PROGRA2\WI3CF21\10\bin\1001711.0\x64\rc.exe --mt=C:\PROGRA2\WI3CF21\10\bin\1001711.0\x64\mt.exe --manifests -- E:\VisualStudio\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cpu.rsp /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO && cd ."
LINK: command "E:\VisualStudio\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe /nologo @CMakeFiles\torch_cpu.rsp /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cpu.dll.manifest" failed (exit code 1102) with the following output:
Creating library lib\torch_cpu.lib and objectlib\torch_cpu.exp
LINK : fatal error LNK1102: out of memory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
File "setup.py", line 734, in
build_deps()
File "setup.py", line 318, in build_deps
cmake=cmake)
File "D:\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
cmake.build(my_env)
File "D:\pytorch\tools\setup_helpers\cmake.py", line 345, in build
self.run(build_args, my_env)
File "D:\pytorch\tools\setup_helpers\cmake.py", line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File "D:\Python\lib\subprocess.py", line 291, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.

**Comment by YHuiX** [comment]
> Please share the error message you are seeing.
> And what are the reason you want to build pytorch in develop mode?
> If you just want to use libtorch C++ interface, then one can download it from https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.6.0.zip

And my memory is 8G, I have set another 4G visual memory

**Comment by gchanan** [comment]
Please use discuss.pytorch.org for questions like this.

**Comment by YHuiX** [comment]
> Please use discuss.pytorch.org for questions like this.

ok

**Comment by vishal590** [comment]
Got error after running this command for pytorch installation from source. see link - https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#contributing-to-pytorch
`python setup.py develop`
Building wheel torch-1.13.0a0+gite90db17
-- Building version 1.13.0a0+gite90db17
cmake -GVisual Studio 15 2017 -Ax64 -Thost=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=F:\open_source\pytorch\torch -DCMAKE_PREFIX_PATH=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Lib\site-packages -DPYTHON_EXECUTABLE=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\python.exe -DPYTHON_INCLUDE_DIR=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Include -DPYTHON_LIBRARY=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310/libs/python310.lib -DTORCH_BUILD_VERSION=1.13.0a0+gite90db17 -DUSE_NUMPY=True F:\open_source\pytorch
CMake Error at CMakeLists.txt:23 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "F:/open_source/pytorch/build/CMakeFiles/CMakeOutput.log".

**Comment by mszhanyi** [comment]
> Got error after running this command for pytorch installation from source. this command `python setup.py develop` see link - https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#contributing-to-pytorch
> 
> Building wheel torch-1.13.0a0+gite90db17 -- Building version 1.13.0a0+gite90db17 cmake -GVisual Studio 15 2017 -Ax64 -Thost=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=F:\open_source\pytorch\torch -DCMAKE_PREFIX_PATH=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Lib\site-packages -DPYTHON_EXECUTABLE=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\python.exe -DPYTHON_INCLUDE_DIR=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Include -DPYTHON_LIBRARY=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310/libs/python310.lib -DTORCH_BUILD_VERSION=1.13.0a0+gite90db17 -DUSE_NUMPY=True F:\open_source\pytorch CMake Error at CMakeLists.txt:23 (project): Generator
> 
> ```
> Visual Studio 15 2017
> ```
> 
> could not find any instance of Visual Studio.
> 
> -- Configuring incomplete, errors occurred! See also "F:/open_source/pytorch/build/CMakeFiles/CMakeOutput.log".

You'd better use VS2019 and select cmake generator as Ninja

**Comment by vishal590** [comment]
> > Got error after running this command for pytorch installation from source. this command `python setup.py develop` see link - https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#contributing-to-pytorch
> > Building wheel torch-1.13.0a0+gite90db17 -- Building version 1.13.0a0+gite90db17 cmake -GVisual Studio 15 2017 -Ax64 -Thost=x64 -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=F:\open_source\pytorch\torch -DCMAKE_PREFIX_PATH=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Lib\site-packages -DPYTHON_EXECUTABLE=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\python.exe -DPYTHON_INCLUDE_DIR=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310\Include -DPYTHON_LIBRARY=C:\Users\vishal bharat lambe\AppData\Local\Programs\Python\Python310/libs/python310.lib -DTORCH_BUILD_VERSION=1.13.0a0+gite90db17 -DUSE_NUMPY=True F:\open_source\pytorch CMake Error at CMakeLists.txt:23 (project): Generator
> > ```
> > Visual Studio 15 2017
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > could not find any instance of Visual Studio.
> > -- Configuring incomplete, errors occurred! See also "F:/open_source/pytorch/build/CMakeFiles/CMakeOutput.log".
> 
> You'd better use VS2019 and select cmake generator as Ninja

cmake generator as Ninja ?

**Comment by mszhanyi** [comment]
Yes, PyTorch doesn't fully support Visual Studio as the cmake generator

**Comment by vishal590** [comment]
> Yes, PyTorch doesn't fully support Visual Studio as the cmake generator. It only uses cl.exe as the C++ compiler.

which plugin should I install? 
you have link or complete nama of plugin. here are too many plugins

**Comment by mszhanyi** [comment]
`conda install ninja`

**Comment by vishal590** [comment]
> `conda install ninja`

oh first I used only pip. I haven't used conda. ok, I will try
