### ISSUE TITLE
torch.as_strided segfault when stride is empty tuple

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#42541]
## To Reproduce

~~~python
import torch
torch.as_strided(input=torch.tensor([1,2,3]), size=(1,0), stride=(), storage_offset=1)
~~~

The above code snippet would cause segmentation fault:

~~~
Segmentation fault (core dumped)
~~~

## Expected behavior

Shouldn't cause segfault even though the input is not valid

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch

## Additional context

cc @ezyang @bhosmer @smessmer @ljk53

**Comment by glaringlee** [comment]
@DNXie Can you try latest version in pytorch master branch?  it might be fixed already
I did not get segfault, but get
```
mismatch in length of strides and shape
```

**Comment by DNXie** [comment]
@glaringlee Just checked. It is gone in nightly version. Thanks! I will close this commit.
