### ISSUE TITLE
symeig memory leak

### ISSUE THREAD

**Issue by agural** [pytorch/pytorch#42557]
## 🐛 Bug

`torch.symeig()` uses additional memory on each application when the argument matrix dimensions are different from dimensions of matrices applied previously. This issues appears on the GPU, but not the CPU and only for `symeig`, not `eig`.

## To Reproduce

Run the code below to reproduce the behavior (requires `psutil`).

```python
import sys
import psutil
import torch

N = 5000
device = torch.device('cuda:0')
print('torch.symeig system memory:', end=' ')
for i in range(10):
    N += 1
    A = torch.eye(N).to(device)
    d, V = torch.symeig(A, eigenvectors=True)
    print('%.1f%%'%(psutil.virtual_memory().percent), end=' ')
    sys.stdout.flush()
print()

print('torch.eig    system memory:', end=' ')
for i in range(10):
    N += 1
    A = torch.eye(N).to(device)
    d, V = torch.eig(A, eigenvectors=True)
    print('%.1f%%'%(psutil.virtual_memory().percent), end=' ')
    sys.stdout.flush()
print()
```

Example output on my system shows memory increasing at each application for `torch.symeig`, but not `torch.eig`.
```
torch.symeig system memory: 27.3% 27.9% 28.5% 29.1% 29.7% 30.3% 30.9% 31.5% 32.1% 32.7%
torch.eig    system memory: 32.8% 32.8% 32.9% 32.9% 32.9% 32.9% 32.9% 32.9% 32.9% 33.0%
```

## Expected behavior

Memory use should not accumulate when using `torch.symeig` multiple times on different-sized matrices.

## Environment

```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 450.51.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip] numpy==1.19.0
[pip] torch==1.5.1
[pip] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.6            py37h7dd41cf_0  
[conda] mkl_random                1.0.1            py37h4414c95_1  
[conda] numpy                     1.19.0                    <pip>
[conda] numpy                     1.15.4           py37h1d66e8a_0  
[conda] numpy-base                1.15.4           py37h81de0dd_0  
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.6.1                py37_cu102    pytorch
```

cc @ngimel @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry @ezyang @gchanan @zou3519

**Comment by IvanYashchuk** [comment]
I think the problem could be that work arrays that are allocated are not freed.
The behavior for `torch.eig` is different because it is implemented in THC, while `torch.symeig` is implemented in ATen.
Work arrays for `torch.eig` are freed here https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorMathMagma.cu#L186-L190

Temporary work arrays for `torch.symeig` are allocated here https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/BatchLinearAlgebra.cu#L1214-L1215 
I am not yet familiar with ATen and c10 enough to know whether these pinned arrays are freed automatically.

**Comment by ezyang** [comment]
ATen implementation brings a Storage into scope, which is owning and should free the pinned memory when you are done. However, I do notice that the allocators being used in these two cases are different: TH is using magma_malloc_pinned whereas ATen is using the caching host memory allocator; it is possible that this difference is causing trouble. If the ATen behavior flattens out (as opposed to leaks indefinitely), a caching allocator would be sufficient explanation.

**Comment by agural** [comment]
It seems like the issue only happens when subsequent applications are on larger matrices. Therefore, a quick solution to the problem is if you know the largest matrix dimensions are Nmax x Nmax, you can run `torch.symeig(torch.eye(Nmax).to(device))` before running your code.

**Comment by ezyang** [comment]
OK. That sounds like a fragmentation issue from the caching host memory allocator then.

**Comment by agural** [comment]
This makes sense, but is there a good solution for it? I think I agree with [this comment](https://github.com/pytorch/pytorch/issues/41486#issuecomment-665108734) that it still seems like something that needs to be fixed, even if it's not exactly PyTorch's fault. Also, the behavior on my machine is that memory use does not flatten out (in fact, it causes my machine to freeze and have to be rebooted).

**Comment by ezyang** [comment]
If you end up having some fixed set of possible sizes, the memory usage should eventually flatten out. If the set of possible sizes is unbounded, life seems hard...

**Comment by Lezcano** [comment]
Can reproduce in master, but the issue seems gone when using `torch.linalg.eigh`. @agural could you confirm this?

**Comment by Lezcano** [comment]
Closing due to the lack of activity.
