### ISSUE TITLE
View/Reinterpret Tensor as a different type w/o copying

### ISSUE THREAD

**Issue by jakirkham** [pytorch/pytorch#42571]
## 🚀 Feature

It would be useful to have a way to reinterpret the type of existing data as another type (without copying). For example, one can do this with NumPy (or CuPy) like so...

```python
In [1]: import numpy                                                            

In [2]: b = b"\x00\x00\x00<\x00@"                                               

In [3]: a = numpy.asarray(memoryview(b))                                        

In [4]: a                                                                       
Out[4]: array([ 0,  0,  0, 60,  0, 64], dtype=uint8)

In [5]: a.view(numpy.float16)                                                   
Out[5]: array([0., 1., 2.], dtype=float16)
```

## Motivation

In some cases users may feed data into PyTorch, which comes from more raw formats (like `bytes` and `bytearray`). So they don't really have the type factored in when provided. In these cases what's needed is a way to add the type after the fact.

## Pitch

Ideally `Tensor` would get a new method, which allows users to reinterpret the type of data and returns a `Tensor` viewing the same data, but with a different type.

## Alternatives

Suggestions welcome 🙂

## Additional context

NA

Have searched the issue tracker and the discussion forum, but didn't come across anything that looked related. Though please let me know if I've merely overlooked something.

cc @mruberry @rgommers

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/29013

**Comment by mruberry** [comment]
This is a cool idea and with recent changes to storage I think it would be possible to implement. I believe we would accept a function to reinterpret storages as a different dtype, but it might be tricky to get the UX right. It'd also be nice to find a NumPy-compatible way to do it. That is, a UX that would work for both PyTorch tensors and NumPy arrays.

**Comment by vadimkantorov** [comment]
NumPy uses `view()` method for that :/

**Comment by mruberry** [comment]
I could it see it being OK to use `view` on tensors in PyTorch, too, for this. But you'd also have to make numpy dtypes substitutable for PyTorch dtypes, for example.
