### ISSUE TITLE
[c++] Error Compiling libtorch in Window10, Visual Studio Code

### ISSUE THREAD

**Issue by 2012312055** [pytorch/pytorch#42589]
I'm trying to use visual studio code to compile sample code from [loading torchscript](https://pytorch.org/tutorials/advanced/cpp_export.html)

While compiling it gave me error message :

libtorch/include/c10/macros/Macros.h:252:5: error: '__assert_fail' was not declared in this scope
     __assert_fail(#cond, __FILE__, static_cast<unsigned int>(__LINE__),  \
     ^~~~~~~~~~~~~

May I have some advice to fix this problem.
I downloaded libtorch 1.6.0 cpu, used Visual Studio Code, compiled with mingw-x86_64 8.1.0 g++

**Comment by peterjc123** [comment]
sorry, we don't support mingw on Windows at present.

**Comment by 2012312055** [comment]
Thanks for replying.

**Comment by 2012312055** [comment]
.

**Comment by skorpion21sic** [comment]
still persists
