### ISSUE TITLE
Unable to print the min-max of quantized weights using Per-channel affine qscheme

### ISSUE THREAD

**Issue by pksvision** [pytorch/pytorch#42598]
Apologies if the question has been answered somewhere else, I couldn't find it. 
===================================================
Hi ,

I am trying to quantize the MobileNet_V2 model using post-training static quantization methodology in PyTorch.  The qschemes used for weights and activations, respectively, are as follows, 

w : per-channel affine with per-channel min-max observers
a :  per tensor affine with histogram observers

After calibaration and quantization, I am trying to print the range of quantized weights (min, max) using this snippet :  

		for layer in myModel.modules():
			if (
				isinstance( layer, torch.nn.intrinsic.quantized.modules.conv_relu.ConvReLU2d ) or
				isinstance( layer,  torch.nn.quantized.modules.conv.Conv2d ) or 
				isinstance( layer, torch.nn.quantized.modules.linear.Linear)
                           ):	
				print(layer.weight().min())
                                print(layer.weight().max())

However, it is throwing the following error,

print(layer.weight().min())
RuntimeError: self.qscheme() == at::kPerTensorAffine INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/quantized/QTensor.cpp:162, please report a bug to PyTorch. clone for quantized Tensor only works for PerTensorAffine scheme right now.

Please let me know if this is the correct way to get ranges of weights quantized using per-channel scheme, or I'm going wrong.

Thanks in advance

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
for triage

**Comment by vkuzo** [comment]
this is happening when trying to take the minimum of a per-channel quantized tensor, we should either support this or throw a better error
