### ISSUE TITLE
AutoNonVariableTypeMode should clear all autograd keys, not just Autograd

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#42609]
Reported by @cpuhrsch. If you are doing device-custom autograd formulas, AutoNonVariableTypeMode should still be the preferred idiom to remove autograd from consideration, but if it doesn't remove your per-device autograd key, then you will infinite loop.

**Comment by ailzhang** [comment]
@cpuhrsch would you mind adding a code example that would trigger the infinite loop? (I wonder why it wasn't triggered in xla use cases)

**Comment by ailzhang** [comment]
This should be already fixed by #42610? Please feel free to reopen if it's not fully resolved.
