### ISSUE TITLE
Caffe2 NNPACK convolution performance regression between 1.5.1 and 1.6 releases on Android

### ISSUE THREAD

**Issue by h6197627** [pytorch/pytorch#42601]
## 🐛 Bug

While testing performance of ResNet32-like CNN architecture with Caffe2 on Android mobile devices it was noticed substantial (>x2) inference speed regression between 1.5.1 and 1.6 releases. For convolution operations NNPACK backend is used:
`conv_op_def->set_engine("NNPACK")`

Timings for 2 different mobile devices (old and new one):

1.5.1 (Qualcomm Snapdragon 410 CPU)
Forward propagation of 10 batches
Mean (without first batch): 1070.993164 milliseconds
Std (without first batch): 37.190353 milliseconds

1.6 (Qualcomm Snapdragon 410 CPU)
Forward propagation of 10 batches
Mean (without first batch): 2586.928955 milliseconds
Std (without first batch): 12.947020 milliseconds

1.5.1 (Samsung S9 mobile)
Forward propagation of 10 batches
Mean (without first batch): 206.343338 milliseconds
Std (without first batch): 5.481998 milliseconds

1.6 (Samsung S9 mobile)
Forward propagation of 10 batches
Mean (without first batch): 423.842407 milliseconds
Std (without first batch): 8.300196 milliseconds

This commit b7e044f0e58624676130b2ef6a376a453fc6b090 changed threading library version that is used by NNPACK. So, maybe this is the case?

## To Reproduce

Both 1.5.1 and 1.6 Caffe2 versions were built using standard script:
ANDROID_ABI=arm64-v8a ANDROID_NDK=/home/user/Android/sdk/ndk-bundle BUILD_CAFFE2_MOBILE=ON ./build_android.sh

## Expected behavior
At least the same speed

## Environment

- OS: Android
- NDK: r21d

cc @VitalyFedyunin @ngimel

**Comment by malfet** [comment]
cc @dreiss

**Comment by DiegoTorresSED** [comment]
Could be related with this issue that I posted yesterday too #42592

**Comment by dreiss** [comment]
We are not actively developing Caffe2 on Android, so it's possible that this regression happened accidentally due to some work on shared PyTorch/Caffe2 code.  I don't think we have the bandwidth to investigate this right now, but if you can narrow down the cause, we might be able to fix it.

**Comment by dreiss** [comment]
Also, it might be helpful if you can use "top" or systrace to observe the number of CPU cores that are busy during execution.

**Comment by h6197627** [comment]
@dreiss, I tried to do this on PC with 12 core CPU (6+6HT) (as I am not sure how to use top on mobile device):
1.5 (conv engine set to NNPACK): 12 threads ~99%
1.6 (conv engine set to NNPACK): 1 threads ~8%
fprop speed improvement is quite small (I guess because it is better to use only 6 threads without hyper-threaded cores and in general NNPACK is not suited for x86 architectures)
1.5 (default conv engine): 1 threads ~8%
1.6 (default conv engine): 1 threads ~8%
fprop speed is roughly the same

**Comment by h6197627** [comment]
Closing considering Caffe2 is not actively developing for Android and no resources available for fixing this performance degradation.
