### ISSUE TITLE
Segfault in `torch.nn.functional.grid_sample` in reflection mode

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#42616]
## To Reproduce

~~~python
import torch
input = torch.zeros([1,1,1,3])  # shape [1,1,1,3]
grid = torch.tensor([[[[ 2.5e+38, 0]]]])  # shape  [1, 1, 1, 2]
torch.nn.functional.grid_sample(input=input, grid=grid, padding_mode='reflection')
~~~

This bug only occurs when `padding_mode` is 'reflection'.

## Expected behavior

Expect no segfault

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by malfet** [comment]
I can reproduce the crash with the top-of-tree pytorch, grabbing for myself.

**Comment by malfet** [comment]
`2.5e+38` is quite close to `std::numeric_limits<float>::max()`, so shortly during the computation it turns into +Inf
