### ISSUE TITLE
AttributeError: 'UgatitSadalinHourglass' object has no attribute 'training'

### ISSUE THREAD

**Issue by ak9250** [pytorch/pytorch#42622]
trying to export 

https://github.com/minivision-ai/photo2cartoon

to onnx

args = parse_args()

torch_model = UgatitSadalinHourglass(args)
torch_model.build_model() 

random_input = torch.randn(1, 3, 64, 64, dtype=torch.float32)
 
input_names = ["image"]
output_names = ["image"]
 
torch.onnx.export(torch_model, random_input, './model.onnx', verbose=False, 
                  input_names=input_names, output_names=output_names, 
                  opset_version=11)

AttributeError                            Traceback (most recent call last)
<ipython-input-53-cbae6a40b3af> in <module>()
      8 torch.onnx.export(torch_model, random_input, './model.onnx', verbose=False, 
      9                   input_names=input_names, output_names=output_names,
---> 10                   opset_version=11)

4 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in select_model_mode_for_export(model, mode)
     34 def select_model_mode_for_export(model, mode):
     35     if not isinstance(model, torch.jit.ScriptFunction):
---> 36         is_originally_training = model.training
     37 
     38         if mode is None:

AttributeError: 'UgatitSadalinHourglass' object has no attribute 'training'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@malfet - From the stack it seems some attribute is missing in the model object. I am not sure if this is directly related to ONNX. Would you be able to double check, and if possible, send a smaller repro? It will help speed up investigation. 
Also note that ONNX is primarily for inference, so I would recommend using model.eval() to set the eval mode before you export the model.

**Comment by ak9250** [comment]
this was resolved although I still getting this error from the exported onnx model The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

**Comment by spandantiwari** [comment]
@ak9250 - please consider opening a new issue with a small repro for that.

**Comment by lucky-xu-1994** [comment]
> this was resolved although I still getting this error from the exported onnx model The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

@ak9250  Hi! how to solve this problem? I have the same question with you.
