### ISSUE TITLE
onnx export failed when output size are not factor of input size for adaptive_avg_pool2d

### ISSUE THREAD

**Issue by ghost** [pytorch/pytorch#42653]
## 🐛 Bug

onnx export failed when output size are not factor of input size for adaptive_avg_pool2d

## To Reproduce

1. Build a model with `nn.AvgPool2d(kernel_size=i, stride=i)`
2. Export it with
```
torch.onnx.export(self.net,               # model being run
                                    images,                         # model input (or a tuple for multiple inputs)
                                    "model.onnx",   # where to save the model (can be a file or file-like object)
                                    export_params=True,        # store the trained parameter weights inside the model file
                                    opset_version=12,          # the ONNX version to export the model to
                                    do_constant_folding=True,  # whether to execute constant folding for optimization
                                    # operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, #fail when commented
                                    input_names = ['input'],   # the model's input names
                                    output_names = ['output'], # the model's output names
                                    dynamic_axes={'input' : {0 : 'batch_size',1 : 'size_x',2:"size_y"},   
                                                    'output' : {0 : 'batch_size',1 : 'size_x',2:"size_y"}})
```
3. get an error and fail to export 
```
\torch\onnx\symbolic_helper.py:176: UserWarning: ONNX export failed on adaptive_avg_pool2d because output size that are not factor of input size not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
```
## Expected behavior

Export the onnx file without `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`.

## Environment

Pytorch 1.5.1

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by pram991** [comment]
https://github.com/pytorch/pytorch/pull/17412

https://github.com/pytorch/pytorch/blob/1b18adb7e8c8a90fecf12ef81c91bba0e4ca8f97/torch/onnx/symbolic_opset9.py#L825

**Comment by luvwinnie** [comment]
does this error have been resolved or any updates? I'm facing the same issue on adaptive_avg_pool2d in the following environment for (RTX3090).
## Environment that show the issue
CUDA 11.1
CUDNN 7.6.5
torch==1.8.0.dev20210103+cu110
torchvision==0.9.0.dev20210103+cu110

However I'm able to export onnx with adaptive_avg_pool2d in the following environment.
## Environment that work
CUDA 10.2
CUDNN 7.6.5
torch==1.6.0
torchvision==0.7.0

**Comment by jiafatom** [comment]
Seems that there is no simple onnx operator for `torch.adaptive_avg_pool2d`. `Resize` op and `AveragePool` cannot simply do that.
Checked one implementation [here](https://discuss.pytorch.org/t/what-is-adaptiveavgpool2d/26897/12), for the 1d case, `adaptive_avg_pool1d` is like
```python
  def torch_pool(inputs, target_size):
      start_points = (torch.arange(target_size, dtype=torch.float32) * (inputs.size(-1) / target_size)).long()
      end_points = ((torch.arange(target_size, dtype=torch.float32)+1) * (inputs.size(-1) / target_size)).ceil().long()
      pooled = []
      for idx in range(target_size):
          pooled.append(torch.mean(inputs[:, :, start_points[idx]:end_points[idx]], dim=-1, keepdim=False))
      pooled = torch.cat(pooled, -1)
      return pooled
```
I verified this code and seems correct.

**Comment by jiafatom** [comment]
In sum, it is not easy to export adaptive_avg_pool1d using existing onnx operators. It is better to propose a new onnx operator or a custom op in ORT for this.

**Comment by RunningLeon** [comment]
Facing the same issue. What is the most recent status of this issue?

**Comment by JustasB** [comment]
Facing same issue, would like to see this implemented

**Comment by jiafatom** [comment]
@RunningLeon @JustasB Did you see some popular models which use `adaptive_avg_pool2d`? If yes, please provide the model. This will help us prioritize this implementation.

**Comment by ayhokuyan** [comment]
> @RunningLeon @JustasB Did you see some popular models which use `adaptive_avg_pool2d`? If yes, please provide the model. This will help us prioritize this implementation.

Mildly popular but here is one: https://arxiv.org/abs/1902.04502

**Comment by RunningLeon** [comment]
@ayhokuyan Hi, for instance, we have this op in PSPNet in mmseg

https://github.com/open-mmlab/mmsegmentation/blob/7e1d853f2b7195b39efb3eb7c4d8e912e3ca57ae/mmseg/models/decode_heads/psp_head.py#L37

**Comment by developer0hye** [comment]
You should consider `torchvision.transforms.functional.resize` function if you quickly need to solve this problem. I could succeed in converting pytorch model to onnx model instead of using `adaptive avg pool`.

**Comment by JustasB** [comment]
> @RunningLeon @JustasB Did you see some popular models which use adaptive_avg_pool2d? If yes, please provide the model. This will help us prioritize this implementation.

@ayhokuyan PyTorch implementations of ResNets use `adaptive_avg_pool2d`. 

From: https://pytorch.org/hub/pytorch_vision_resnet/
```
import torch
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=False)
model
```

Shows:
```
ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  [.......]
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1)) # <-------------
  (fc): Linear(in_features=512, out_features=1000, bias=True)
)
```

**Comment by jiafatom** [comment]
Filed an internal task to track this: https://msdata.visualstudio.com/Vienna/_workitems/edit/1408925

**Comment by darkecho789** [comment]
Hi I am also facing this problem. I got an error that stated "RuntimeError: Unsupported: ONNX export of operator adaptive_avg_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub." when trying to use dataloader with input size of (128, 3, 100, 100).

**Comment by maisonhai3** [comment]
I got the same Runtime error.
My model uses Adaptive Average Pooling, then ONNX raises that error.

Please support this operator.

**Comment by Wheest** [comment]
I found this occurs on pre-defined VGG models when we pass input sizes other than 224.  This can be valid for these networks, and we get output from them in pure PyTorch.  However, exporting fails.  You can see code I used here:

```python
import torch
import torchvision
import torch.nn as nn

model = torchvision.models.vgg11()

input_shape = 224
input_shape = 512

x = torch.rand((1, 3, input_shape, input_shape))

y = model(x)
print("Got test output okay!")

torch.onnx.export(model, x, "/tmp/model.onnx")
print("Exported to ONNX")
```

THe export fails for all values of `opset_version`, including 9, 10, 11, 12, 13, and 14.  I am running `torch.__version__ == "1.11.0a0+b6df043"`

The error is:


```sh
Traceback (most recent call last):
  File "test_vgg16.py", line 16, in <module>
    torch.onnx.export(model, x, "/tmp/model.onnx")
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 321, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 134, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 746, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 524, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 243, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 378, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1069, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 979, in symbolic_fn
    return sym_help._onnx_unsupported(name + ", since output size is not factor of input size")
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 262, in _onnx_unsupported
    raise RuntimeError("Unsupported: ONNX export of operator {}. "
RuntimeError: Unsupported: ONNX export of operator adaptive_avg_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch
GitHub.
```

**Comment by jinfagang** [comment]
I also met this problem, any solution?

**Comment by developer0hye** [comment]
@jinfagang 

If you can replace Pooling layer with torch.nn.functional.interpolate(bilnear and align_corners=True), I recommend you change the layer and check the results.

**Comment by jinfagang** [comment]
@developer0hye I have solved it. My scene is more complicated, it generates different output size in every featuremap.

**Comment by developer0hye** [comment]
@jinfagang How did you solve it?

**Comment by 2050airobert** [comment]
hi，
Do we need retraining the model like litehrnet etc after changing the code as what you did？
I have changed the code of litehrnet.py ，yet still the same error？ what was wrong ？

BR

**Comment by 2050airobert** [comment]
hi，
Do we need retraining the model like litehrnet etc after changing the code as what you did？
I have changed the code of litehrnet.py ，yet still the same error？ what was wrong ？

BR

**Comment by nikkymen** [comment]
This solution worked for me

```
class AdaptiveAvgPool2dCustom(nn.Module):
    def __init__(self, output_size):
        super(AdaptiveAvgPool2dCustom, self).__init__()
        self.output_size = np.array(output_size)

    def forward(self, x: torch.Tensor):
        stride_size = np.floor(np.array(x.shape[-2:]) / self.output_size).astype(np.int32)
        kernel_size = np.array(x.shape[-2:]) - (self.output_size - 1) * stride_size
        avg = nn.AvgPool2d(kernel_size=list(kernel_size), stride=list(stride_size))
        x = avg(x)
        return x
```

We can replace _AdaptiveAvgPool2d_ module with this _AdaptiveAvgPool2dCustom_.

Because this is just pooling, we don't have to retrain the model, but inference may be slightly different.

**Comment by eliashossain001** [comment]
@developer0hye Can you please help me to fix the issue that I got experienced? I am trying to export a PyTorch model (text-to-speech) to ONNX format using the onnx.export() function with opset_version=12. However, I am encountering an error message stating that the 'aten::unflatten' operator is not supported for this opset version. I would like to request support for this operator when exporting to ONNX opset version 12. It would be greatly appreciated if this operator could be added to the ONNX exporter, or if there is a workaround or alternative solution to this issue.

```
class AlignTTSModelClass(nn.Module):
    def __init__(self, num_graphemes, seq_len):
        super().__init__()

        # Create an instance of the AlignTTSConfig class with the desired parameters
        config = AlignTTSConfig(
            # model_name="align_tts",
            model_args=AlignTTSArgs(
                num_chars=num_graphemes,
                out_channels=80,
                hidden_channels=256,
                hidden_channels_dp=256,
                encoder_type="fftransformer",
                encoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                decoder_type="fftransformer",
                decoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                length_scale=1.0,
                num_speakers=0,
                use_speaker_embedding=False,
                use_d_vector_file=False,
                d_vector_dim=0,
            )
        )

        # Create an instance of the AlignTTS class using the config
        self.align_tts = AlignTTS(config)

        # Set the input shape of the model
        self.input_shape = (seq_len, num_graphemes)

    
    def forward(self, x, x_lengths, y, y_lengths):
        # Perform the forward pass through the AlignTTS model, passing the additional arguments
        return self.align_tts(x, x_lengths, y, y_lengths)

    

if __name__ == '__main__':
    # Parameters
    batch_size = 8
    num_graphemes = 105
    seq_len = 256

    # Load the PyTorch checkpoint
    checkpoint_path = '/home/elias/male_checkpoint.pth'
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))

    dummy_input = torch.randint(low=0, high=num_graphemes, size=(batch_size, seq_len), dtype=torch.long)
    dummy_input_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output = torch.randn(batch_size, seq_len, 80)

    model = AlignTTSModelClass(num_graphemes=num_graphemes, seq_len=seq_len)
    model = torch.nn.DataParallel(model)
    print('Model Architecture:', model)
    # Load the state dictionary from the checkpoint
    state_dict = checkpoint['model']
    model_state_dict = model.state_dict()
    for name, param in state_dict.items():
        if name not in model_state_dict:
            print(f"Ignoring parameter '{name}' in the checkpoint because it does not exist in the model")
        elif param.shape != model_state_dict[name].shape:
            print(f"Ignoring parameter '{name}' in the checkpoint because its shape does not match the corresponding model parameter")
        else:
            model_state_dict[name] = param

    # Load the state dictionary into the model
    model.load_state_dict(model_state_dict, strict=False)

   
    # Export the model to ONNX format
    onnx_path = '/home/elias/male_model.onnx'
    
    
    onnx.export(model.module, (dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths), onnx_path,
            verbose=True, export_params=True, opset_version=12,
            input_names=['input', 'input_lengths', 'output_lengths'],
            output_names=['output'])


============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::unflatten' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "/home/elias/script/onnx_2.py", line 103, in <module>
    onnx.export(model.module, (dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths), onnx_path,
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues. ```

**Comment by developer0hye** [comment]
@eliashossain001 Can you replace an unflatten operator with other operators supported in onnx?

**Comment by eliashossain001** [comment]
@developer0hye I have attempted to work according to your advice. I have changed the forward function so far:

```  def forward(self, x: torch.Tensor, x_lengths: torch.Tensor, y: torch.Tensor, y_lengths: torch.Tensor) -> Dict[str, torch.Tensor]:
        # Perform the forward pass through the AlignTTS model, passing the additional arguments
        aux_input = {"d_vectors": None} # dummy input for the "aux_input" argument
        phase = None # dummy input for the "phase" argument
        return self.align_tts.forward(x, x_lengths, y, y_lengths, aux_input, phase)```

However, still, I'm having a similar error. In addition, lowering the opset version did not provide me with the outcome.

**Comment by ukoehler** [comment]
@developer0hye When using pre-trained models (like me) it is impossible to change anything. The export will just fail. Therefore, I believe it very important to fix the issue.

**Comment by thawro** [comment]
@nikkymen
> This solution worked for me
> 
> ```
> class AdaptiveAvgPool2dCustom(nn.Module):
>     def __init__(self, output_size):
>         super(AdaptiveAvgPool2dCustom, self).__init__()
>         self.output_size = np.array(output_size)
> 
>     def forward(self, x: torch.Tensor):
>         stride_size = np.floor(np.array(x.shape[-2:]) / self.output_size).astype(np.int32)
>         kernel_size = np.array(x.shape[-2:]) - (self.output_size - 1) * stride_size
>         avg = nn.AvgPool2d(kernel_size=list(kernel_size), stride=list(stride_size))
>         x = avg(x)
>         return x
> ```
> 
> We can replace _AdaptiveAvgPool2d_ module with this _AdaptiveAvgPool2dCustom_.
> 
> Because this is just pooling, we don't have to retrain the model, but inference result may be slightly different.

What about the results for different `x` shapes? As far as I know, doing it this way will treat `stride_size` and `kernel_size` as constants for the future calls (trace might not generalize to other inputs).

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
