### ISSUE TITLE
Comparison operators and logical operators would fail if the output tensor has a dtype different from both inputs

### ISSUE THREAD

**Issue by xuhdev** [pytorch/pytorch#42660]
## 🐛 Bug

Comparison operators and logical operators would fail if the output tensor has a dtype different from both inputs.

## To Reproduce

```
In [1]: import torch

In [2]: a=torch.tensor([190, 220], dtype=torch.bfloat16)

In [3]: b=torch.tensor([190, 210], dtype=torch.float32)

In [4]: c=torch.empty(0, dtype=torch.float64)

In [5]: torch.logical_or(a, b, out=c)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-3ac99fe7cb2a> in <module>
----> 1 torch.logical_or(a, b, out=c)

RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cpu/Loops.h":194, please report a bug to PyTorch. 
```

Same is true for comparison operators (e.g., `ge`).

## Environment

Collecting environment information...
PyTorch version: 1.7.0.dev20200805+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Debian GNU/Linux 10 (buster)
GCC version: (Debian 8.3.0-6) 8.3.0
CMake version: version 3.16.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro P400
Nvidia driver version: 440.100
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0.dev20200805+cu101
[conda] Could not collect

cc @nairbv @mruberry

**Comment by ailzhang** [comment]
We should at least throw a proper error message instead of RuntimeError here. @xuhdev would you mind submitting a fix for this? Thanks!

**Comment by xuhdev** [comment]
@ailzhang Is the error considered a bug (output tensor can't be a different dtype)? Or do you think a correction of error message is already sufficient?

**Comment by mruberry** [comment]
This still occurs on 1.7.

**Comment by gchanan** [comment]
also, not a crash.

**Comment by gchanan** [comment]
The error message is saying that thee TensorIterator invocation is bogus and (could) result in a silent correctness problem.

**Comment by mruberry** [comment]
> @ailzhang Is the error considered a bug (output tensor can't be a different dtype)? Or do you think a correction of error message is already sufficient?

Fixing the error message is sufficient. It would be OK for the output tensor to have a different dtype, too. Then safe casting rules would apply (i.e. no float -> int conversions).
