### ISSUE TITLE
Wrong error messages

### ISSUE THREAD

**Issue by NTT123** [pytorch/pytorch#42662]
https://github.com/pytorch/pytorch/blob/17f76f9a7896eccdfdba5fd22fd3a24002b0d917/torch/optim/lr_scheduler.py#L1169-L1178

The error messages should be **Expected positive integer**

cc @vincentqb

**Comment by mariosasko** [comment]
Agree. Nice catch!

**Comment by vincentqb** [comment]
Good point :) Do you want to open a pull request to say "strictly positive integer"?
