### ISSUE TITLE
Store scale as fp32 and zero_point as int32

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#42693]
Currently quantize_per_tensor/quantize_per_channel expects the scale value to be a double and int64 for zero_point in the API as well as in the internal storage. We only need to store float32 since all backends currently only support float32 scale and int32 zero_point. This could have a potential storage win for per-channel quantization.
API - https://pytorch.org/docs/stable/generated/torch.quantize_per_channel.html#torch.quantize_per_channel

Future possibility -
Storing them as Tensors will make this consistent across all quantization functions and will enable user to pass in float32 as scale and int32 as zero_point, for both, per_tensor and per_channel.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by dreiss** [comment]
As discussed internally, using tensors to store these values for per-tensor quantization would have significant on-disk space overheads, so focusing on per-channel is probably the best bet.

**Comment by jerryzh168** [comment]
Hi @dreiss, what is the priority for this request?

**Comment by dreiss** [comment]
Not urgent.  I'd rather have it take longer and get a smaller size as a result (like storing 8 or 16 bits per channel).

**Comment by zetyquickly** [comment]
Hi

> Currently quantize_per_tensor/quantize_per_channel expects the scale value to be a double and int64 for zero_point in the API as well as in the internal storage. We only need to store float32 since all backends currently only support float32 scale and int32 zero_point.

Do you propose to change the types of inputs to float32 and int32 in backends?

> Future possibility -
Storing them as Tensors will make this consistent across all quantization functions and will enable user to pass in float32 as scale and int32 as zero_point, for both, per_tensor and per_channel.

Seems like API is already takes Tensor as input

**Comment by supriyar** [comment]
> Hi
> 
> > Currently quantize_per_tensor/quantize_per_channel expects the scale value to be a double and int64 for zero_point in the API as well as in the internal storage. We only need to store float32 since all backends currently only support float32 scale and int32 zero_point.
> 
> Do you propose to change the types of inputs to float32 and int32 in backends?
> 
> > Future possibility -
> > Storing them as Tensors will make this consistent across all quantization functions and will enable user to pass in float32 as scale and int32 as zero_point, for both, per_tensor and per_channel.
> 
> Seems like API is already takes Tensor as input

We don't need to change the backend since it already expects float32 and int32. Just the pytorch APIs and function signatures will need to change I think.

We don't need to update per-tensor API to accept Tensors (since it will have additional overheard compared to storing float32 and int32 values) so can ignore that for now.

**Comment by raghuramank100** [comment]
Notes:
1. check if int32 and fp32 can be enforced for scalar arguments in python.
2. If not, for per-tensor,ensure that scale and zero-point are always internally calculated  and cast into fp32 and int32 values in C++. We will also need to ensure the same in python (in terms of calculations).

**Comment by supriyar** [comment]
Next steps:
1. for per-tensor ensure we convert scale and zp to fp32 and int32
2. for per-channel ensure that the API only accepts fp32 and int32 dtypes.

**Comment by zetyquickly** [comment]
Is someone already on it, I mean implemented previous steps?

> Next steps:
> 
> 1. for per-tensor ensure we convert scale and zp to fp32 and int32
> 2. for per-channel ensure that the API only accepts fp32 and int32 dtypes.

**Comment by supriyar** [comment]
quantize_per_channel accepts tensor arguments for scale now. https://pytorch.org/docs/stable/generated/torch.quantize_per_channel.html#torch.quantize_per_channel
