### ISSUE TITLE
segfault and abort in `torch.cholesky_solve`

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#42695]
## To Reproduce

The API outputs segfault and several kinds of abort in both nightly version and 1.5.0. The abort messages are:
- munmap_chunk(): invalid pointer    
- double free or corruption (!prev)    
- corrupted double-linked list  
- free(): invalid pointer  
- realloc(): invalid next size  

And with the same input, it produces different error message in 1.5.0 and nightly version. 

### Input#1
~~~python
import torch
torch.cholesky_solve(input=torch.ones([5, 1, 1]), input2 =torch.ones([7, 1,1]), out=torch.ones([1]))
~~~
It gives segfault in nightly version, but abort in 1.5.0 stable version with error message:
~~~python
free(): invalid next size (fast)
Aborted (core dumped)
~~~

### Input#2

~~~python
import torch
torch.cholesky_solve(input=torch.ones([5,3,5,1]), input2 = torch.ones([10,5,5,5]), out=torch.ones([1]))
~~~
The error message in 1.5.0 stable version:
~~~python
free(): invalid pointer
Aborted (core dumped)
~~~
The error message in nightly version 
~~~python
double free or corruption (out)
Aborted (core dumped)
~~~

### Input#3

~~~python
import torch
torch.cholesky_solve(input=torch.ones([5,3,8,1]), input2 = torch.ones([10,5,8,8]), out=torch.zeros([1]))
~~~
This outputs a segfault in 1.5.0 stable version, and aborts in nightly version. The error message in nightly version:
~~~python
munmap_chunk(): invalid pointer
Aborted (core dumped)
~~~

### input#4

~~~python
import torch
torch.cholesky_solve(input=torch.ones([5,2,1]), input2 = torch.ones([10,2,2]), out=torch.ones([1]))
~~~

It aborts in both 1.5.0 and nightly version with the error message:
~~~python
import torch
torch.cholesky_solve(input=torch.ones([5,2,1]), input2 = torch.ones([10,2,2]), out=torch.ones([1]))
~~~

Also, running the equivalent code here:
~~~python
import torch
out = torch.ones([1])
input = torch.ones([5,2,1])
input2 = torch.ones([10,2,2])
torch.cholesky_solve(input=input, input2 = input2, out=out)
~~~ 
gives me **different error message**. The error message is also different when I run the **python script** with the code, and run it in the **command line**. 

### Input#5

The same input is also reported in issue #42648

~~~python
import torch
input = torch.zeros ([1,1,1])
input2 = torch.zeros ([1,4,1,1])
out= torch.zeros([1])
torch.cholesky_solve(input=input, input2=input2, out=out)
~~~

Output this error message in both nightly and 1.5.0:
~~~python
free(): invalid pointer
Aborted (core dumped)
~~~

## Expected behavior

Expect it to work

## Environment

python collect_env.py
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch
## Additional context

Related issue #42648

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Will look at it on Monday

**Comment by mattip** [comment]
For me, #1 above segfaults at `ten/src/ATen/native/BatchLinearAlgebra.cpp:481` inside `auto A_working_copy = cloneBatchedColumnMajor(A);`.

**Comment by mattip** [comment]
running the example in `#1` without the out argument successfully completes and raises an error
```
>>> torch.cholesky_solve(input=torch.ones([5, 1, 1]), input2=torch.ones([7, 1,1]))
RuntimeError: The size of tensor a (5) must match the size of tensor b (7) at \
    non-singleton dimension 0
```

**Comment by mattip** [comment]
The `out` variant failed to broadcast the input arguments. PR incoming.

**Comment by DNXie** [comment]
> For me, #1 above segfaults at `aten/src/ATen/native/BatchLinearAlgebra.cpp:481` inside `auto A_working_copy = cloneBatchedColumnMajor(A);`.
> 
> Edit: typo

Sorry, why is this has something to do with `out`? Thanks!

**Comment by mattip** [comment]
The call is supposed to check its arguments for validity before hitting that line. Before #43137 the call directly hit the helper function that assumes all args have been checked. After #43137 the call first hits the wrapper that checks, and only then calls the helper function. The checking part also broadcasts the arguments as needed, which  the helper does not do.
