### ISSUE TITLE
ScriptModule including tensor attributes in state_dict

### ISSUE THREAD

**Issue by victor-shepardson** [pytorch/pytorch#42710]
## 🐛 Bug

When creating ScriptModule with torch.jit.script, any tensor attribute of the module will appear in the state_dict. The same is true for buffers with persistent=False.

## To Reproduce

```python
import torch

print(torch.__version__)

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.a = torch.zeros(100)
        
print(M().state_dict().keys())

print(torch.jit.script(M()).state_dict().keys())

class M2(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('a', torch.zeros(100), persistent=False)
        
print(M2().state_dict().keys())

print(torch.jit.script(M2()).state_dict().keys())
```

```
1.6.0
odict_keys([])
odict_keys(['a'])
odict_keys([])
odict_keys(['a'])
```

## Expected behavior

I expect the state_dict to be empty in all cases.

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.0.14           py37h5e564d8_0
[conda] mkl_random                1.1.0            py37ha771720_0
[conda] numpy                     1.17.2                   pypi_0    pypi
[conda] numpy-base                1.17.2           py37h6575580_0
[conda] pytorch                   1.6.0                   py3.7_0    pytorch
[conda] pytorch-lightning         0.7.3                    pypi_0    pypi
[conda] torchaudio                0.6.0                      py37    pytorch
[conda] torchvision               0.4.2                    pypi_0    pyp

and

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Quadro RTX 6000
GPU 1: Quadro RTX 6000
GPU 2: Quadro RTX 6000
GPU 3: Quadro RTX 6000

Nvidia driver version: 450.57
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-lightning         0.7.3                    pypi_0    pypi
[conda] torchaudio                0.6.0                      py37    pytorch
[conda] torchvision               0.4.2                    pypi_0    pypi

seeing the same thing in pytorch 1.4 and 1.5

cc @ezyang @gchanan @zou3519 @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting this issue victor-shepardson. I think this behavior is actually intended. See [this comment](https://github.com/pytorch/pytorch/blob/a346e90c4902c8f993211945e78449d76c7880e3/torch/csrc/jit/api/module.h#L115).

TorchScript doesn't support non-persistent buffer. Thus it treats any tensor-type non-parameter module attribute as a buffer. And buffers show up in state dict. 

Therefore, I am closing this issue for now. If this is causing problem for you, feel free to reopen with more details.
