### ISSUE TITLE
OneCycleLR mentions `verbose` as an argument on the doc page when it is not

### ISSUE THREAD

**Issue by dalmia** [pytorch/pytorch#42716]
The documentation for [OneCycleLR](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.OneCycleLR) mentions `verbose` as one of the arguments but the [code](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#OneCycleLR) doesn't have that argument. Thus, it raises an error if someone passes a value for `verbose` just going by the documentation.

cc @jlin27 @vincentqb

**Comment by ailzhang** [comment]
Thanks for reporting! I'll leave it to our optimizer pocs to decide whether we want to change the code or docs.

**Comment by vincentqb** [comment]
Thanks for reporting this! This was added in #41580, see [code](https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L1157). I'll close this issue, but please feel free to re-open if this doesn't address it :)

**Comment by dalmiaman** [comment]
Great, thanks!
