### ISSUE TITLE
AMSGrad mode in SparseAdam is broken

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#4271]
The updates of max square grad average aren't propagated back to the persistent state. See #4034 

cc @vincentqb

**Comment by kashif** [comment]
@apaszke any idea how to get the indicies for scatter from the `grad`? Having trouble finding the right API... at the moment I have something like:

```python
...

torch.max(old_max_exp_avg_sq_values, exp_avg_sq_update_values, out=old_max_exp_avg_sq_values)
denom = old_max_exp_avg_sq_values.sqrt_().add_(group['eps'])
max_exp_avg_sq.scatter_(0, grad_indices, old_max_exp_avg_sq_values)
...
```

**Comment by apaszke** [comment]
Yeah, I think that's exactly what we need. I'm not sure how to get the indices correctly. You might need to view that max tensor as a 1D vector and compute "flattened indices". Then, you can use `.put_`.

**Comment by kashif** [comment]
thanks @apaszke `.put_` works

**Comment by vincentqb** [comment]
Closing since linked PR has been merged.
