### ISSUE TITLE
version below torch 1.4 cannot load model state dict that training on torch 1.6, but torch 1.5 can both load 1.4 and 1.6 model state dict

### ISSUE THREAD

**Issue by ZenFSheng** [pytorch/pytorch#42724]
![image](https://user-images.githubusercontent.com/49142984/89604940-dfd60900-d89e-11ea-80b9-7620965cb4f6.png)
I suddenly found that the model state dict training on torch 1.6 cannot be loaded on torch 1.4 but 1.5 will be alright. My question is :  whether the version torch 1.5 will be the watershed ? Or it is just a temporary question?

**Comment by ezyang** [comment]
please see "Deprecated old torch.save serialization format " in the 1.6 release notes https://github.com/pytorch/pytorch/releases
