### ISSUE TITLE
Some equations in the document do not display on 1.6.0 docs

### ISSUE THREAD

**Issue by Euruson** [pytorch/pytorch#42720]
## 📚 Documentation

Some equations in the document do not display. For example, [L1LOSS](https://pytorch.org/docs/stable/generated/torch.nn.L1Loss.html#torch.nn.L1Loss).

cc @ezyang @zou3519 @jlin27

**Comment by ezyang** [comment]
It seems to be working on master https://pytorch.org/docs/master/generated/torch.nn.L1Loss.html?highlight=l1loss#torch.nn.L1Loss

**Comment by mruberry** [comment]
This appears to be working as expected. Please reopen if you're still seeing this issue.
