### ISSUE TITLE
When should I use the clone function after expand

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#42726]
## 🐛 Bug

I have two code snippets about expand, because they behave differently, so I am not sure if this is a bug.
## To Reproduce

Code snippet-1:
```
import torch

weight = torch.rand(4, 4, 4, 4)
weight_shape = weight.size()

ones = torch.ones(4)
print(ones.size())
new_w = ones[:, None, None, None].expand_as(weight).type_as(weight)
new_w[0] = torch.zeros(weight_shape[1:])

```
It will raise a RuntimeError which is as expected, because that `expand` actually only  create a new view for the tensor. I should `clone` before the in-place action.
```
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation. 
```

However, I get the second code snippet:
Code snippet-2:
```
import torch

weight = torch.rand(4, 4, 4, 4)
weight_shape = weight.size()


filters = weight.size(0)
w_abs = weight.data.abs()
w_abs_structured = w_abs.view(filters, -1).sum(dim=1)
c_mask = torch.gt(w_abs_structured, 0.5)
print(c_mask.size())
new_w = c_mask[:, None, None, None].expand_as(weight).type_as(weight)
new_w[0] = torch.zeros(weight_shape[1:])

```
However, the second code snippet can run successfully, which means we don't need a `clone` before the in-place operation.
Is this inconsistency in line with expectations, or is it caused by a bug?

In addition, when should I add the `clone` function after expand?

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

**Comment by kshitij12345** [comment]
Expand returns a view of the tensor. So if you expand a small tensor to a larger one, it will occupy the same underlying physical memory by manipulating the strides.
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand

Snippet-1: We can see that stride of all dimensions except the first is 0, which means for all elements of those dimension come from same location in physical memory.
```python
>>> import torch
>>> weight = torch.rand(4, 4, 4, 4)
>>> weight_shape = weight.size()
>>> ones = torch.ones(4)
>>> print(ones.size())
torch.Size([4])
>>> new_w = ones[:, None, None, None].expand_as(weight).type_as(weight)
>>> new_w.stride()
(1, 0, 0, 0)
```

Snippet-2: We can see that stride of all dimensions is non-zero. So each element would actually occupy unique location in physical memory.
```python
>>> import torch
>>> weight = torch.rand(4, 4, 4, 4)
>>> weight_shape = weight.size()
>>> filters = weight.size(0)
>>> w_abs = weight.data.abs()
>>> w_abs_structured = w_abs.view(filters, -1).sum(dim=1)
>>> c_mask = torch.gt(w_abs_structured, 0.5)
>>> print(c_mask.size())
torch.Size([4])
>>> new_w = c_mask[:, None, None, None].expand_as(weight).type_as(weight)
>>> new_w.stride()
(64, 16, 4, 1)
```

Hope this helps.
