### ISSUE TITLE
Download of torch wheel is very slow

### ISSUE THREAD

**Issue by ghimireadarsh** [pytorch/pytorch#42730]
## ❓ Questions and Help
Installing the torch package is very slow, while its 3+ mbps for other packages like numpy, pandas, but its not going above 400kbps for torch.    

cc @ezyang @seemethere @malfet

**Comment by ezyang** [comment]
where are you installing torch package from? From pypi or our server?

**Comment by oke-aditya** [comment]
It is conda issue. I too faced in the morning and still. I am downloading from India. 

pip install worked fine..

**Comment by ezyang** [comment]
Unfortunately there is not much we (personally) can do about Anaconda's servers

**Comment by seemethere** [comment]
Yeah to parrot @ezyang we don't personally control the infrastructure that hosts binaries for both PyPI or Conda so there's not anything we can do about slow download speeds on those platforms 😞 

Going to close this since this isn't really related to an issue with the PyTorch project itself.

**Comment by ghimireadarsh** [comment]
I was working with pip install, and it was the issue I faced. I have changed the pypi link to nearby servers, and its working fine now. Thanks.
