### ISSUE TITLE
Add torch.vdot similar to numpy.vdot to calculate the complex dot product

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#42747]
For two complex numbers the [dot product](https://en.wikipedia.org/wiki/Dot_product#Complex_vectors) is defined as:

<img width="840" alt="Screen Shot 2020-08-07 at 3 57 51 PM" src="https://user-images.githubusercontent.com/20081078/89683624-deb8d200-d8c6-11ea-8ed0-4d8bd870317d.png">

The `torch.vdot(a, b)` function (similar to [numpy.vdot](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html))will treat complex numbers differently than dot(a, b). If the first argument is complex the complex conjugate of the first argument will be used for the calculation of the dot product.

cc @ezyang @anjali411 @dylanbespalko @mruberry @rgommers

**Comment by kshitij12345** [comment]
#38349

**Comment by anjali411** [comment]
@kshitij12345 would you like to work on this issue?

**Comment by kshitij12345** [comment]
@anjali411 yes

**Comment by anjali411** [comment]
@kshitij12345 great! there are blas functions we can call into similar to `torch.dot` https://github.com/pytorch/pytorch/pull/42745 . For real tensors `torch.vdot` should just call `torch.dot`. Please let me know if you have any other questions and add me as a reviewer when you have a draft PR.
