### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_nearest2d

### ISSUE THREAD

**Issue by ak9250** [pytorch/pytorch#42752]
trying to export this to onnx https://github.com/minivision-ai/photo2cartoon

import os
import torch
from models import UgatitSadalinHourglass

class Namespace:
  pass

n = Namespace()

n.phase = 'train'
n.light = True

n.dataset = 'photo2cartoon'

n.iteration = 1000000
n.batch_size = 1
n.print_freq = 1000
n.save_freq = 1000
n.decay_flag = True

n.lr = 0.0001
n.adv_weight = 1
n.cycle_weight = 50
n.identity_weight = 10
n.cam_weight = 1000
n.faceid_weight = 1

n.ch = 32
n.n_dis = 6

n.img_size = 256
n.img_ch = 3

n.gpu_ids = [0]
n.benchmark_flag  = False
n.resume = False
n.rho_clipper = 1.0
n.w_clipper = 1.0
n.pretrained_weights = 'models/photo2cartoon_weights.pt'

n.result_dir = './experiment/{}-size{}-ch{}-{}-lr{}-adv{}-cyc{}-id{}-identity{}-cam{}'.format(
    os.path.basename(__file__)[:-3],
    n.img_size,
    n.ch,
    n.light,
    n.lr,
    n.adv_weight,
    n.cycle_weight,
    n.faceid_weight,
    n.identity_weight,
    n.cam_weight)

m = UgatitSadalinHourglass(n)
m.build_model()

trace_input = torch.rand([1, 3, 256, 256])
dynamic_axes = {'image': {0: 'batch', 2: 'height', 3: 'width'}}

torch.onnx.export(
    model=m.genB2A,
    args=(trace_input,),
    f='photo2cartoon_b2a2.onnx',
    input_names=('image',),
    output_names=('output',),
    dynamic_axes=dynamic_axes,
    opset_version=8,
)

Traceback (most recent call last):
  File "convert.py", line 67, in <module>
    opset_version=8,
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/init.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 545, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_nearest2d

happens with opset version 8, not with version 11

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
>> happens with opset version 8, not with version 11
Opset 8 is a very old opset and does not have support for several ops (or all their usages). My recommendation would be to use opset 11 or the latest opset 12.
