### ISSUE TITLE
Proposal: rename upsample to resample

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#4277]
@vadimkantorov pointed out that `torch.nn.functional.upsample` works for downsampling as well. Perhaps we should rename it to `resample` and deprecate `upsample`?

cc @albanD @mruberry

**Comment by vadimkantorov** [comment]
currently only in `mode='bilinear'`

**Comment by albanD** [comment]
This function has been deprecated in favor of [interpolate](https://pytorch.org/docs/stable/nn.functional.html?highlight=upsample#torch.nn.functional.interpolate) so I think this issue has been addressed.
