### ISSUE TITLE
Pytorch with cuda9.2 10.1 10.2, what’s the best in most situations? 

### ISSUE THREAD

**Issue by JiangTanZJU** [pytorch/pytorch#42782]
If we have the latest Nvidia driver, we can install pytorch with cuda in 3 ways:
conda install pytorch cudatoolkit=9.2 -c pytorch
conda install pytorch cudatoolkit=10.1 -c pytorch
conda install pytorch cudatoolkit=10.2 -c pytorch

All three methods work. So what is the difference among installed pytorchs with 3 types of cuda? Such as running efficiency or features?

Which one should we choose in most situations?

cc @ngimel

**Comment by malfet** [comment]
@JiangTanZJU if you can install the latest driver, please consider using latest available CUDA version (i.e. 10.2), which should be faster, support more GPUs(for example RTX2080 is not supported by CUDA-9.2) and have some additional features.
