### ISSUE TITLE
convert to onnx input output mismatch

### ISSUE THREAD

**Issue by ak9250** [pytorch/pytorch#42783]
I am trying to convert this model https://github.com/minivision-ai/photo2cartoon
to onnx

I used this to export

https://gist.github.com/antonpaquin/2614581008c5c84cd4519a4f75735eb7

but the input output does not match

Information
light : True
dataset : photo2cartoon
batch_size : 1
iteration per epoch : 1000000
Discriminator
discriminator layer : 6
Weight
adv_weight : 1
cycle_weight : 50
faceid_weight : 1
identity_weight : 10
cam_weight : 1000
rho_clipper: 1.0
w_clipper: 1.0
[*] Load models/photo2cartoon_weights.pt Success
torch.Size([1, 3, 256, 256])
torch.Size([1, 2])
torch.Size([1, 1, 64, 64]

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
How are you running your ONNX model? I would suggest checking if the ONNX model looks correct. If yes, then it could be an issue with the runtime not the exporter, so please open a bug there. 
Feel free to re-open this issue if you see an issue in export. Also, attach a self-contained repro.
