### ISSUE TITLE
Exporting the operator chunk to ONNX opset version 9, 10, 11 & 12 are not supported. 

### ISSUE THREAD

**Issue by srohit0** [pytorch/pytorch#42785]
## 🐛 Bug

RuntimeError: Exporting the operator chunk to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce

```
np.random.seed(2)

T = 20
L = 1000
N = 100

x = np.empty((N, L), 'int64')
x[:] = np.array(range(L)) + np.random.randint(-4 * T, 4 * T, N).reshape(N, 1)
data = np.sin(x / 1.0 / T).astype('float64')
torch.save(data, open('traindata.pt', 'wb'))
#---------------------
class Sequence(nn.Module):
    def __init__(self):
        super(Sequence, self).__init__()
        self.lstm1 = nn.LSTMCell(1, 51)
        self.lstm2 = nn.LSTMCell(51, 51)
        self.linear = nn.Linear(51, 1)

    def forward(self, input, future = 0):
        outputs = []
        h_t = torch.zeros(input.size(0), 51, dtype=torch.double)
        c_t = torch.zeros(input.size(0), 51, dtype=torch.double)
        h_t2 = torch.zeros(input.size(0), 51, dtype=torch.double)
        c_t2 = torch.zeros(input.size(0), 51, dtype=torch.double)

        for i, input_t in enumerate(input.chunk(input.size(1), dim=1)):
            h_t, c_t = self.lstm1(input_t, (h_t, c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2, c_t2))
            output = self.linear(h_t2)
            outputs += [output]
        for i in range(future):# if we should predict the future
            h_t, c_t = self.lstm1(output, (h_t, c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2, c_t2))
            output = self.linear(h_t2)
            outputs += [output]
        outputs = torch.stack(outputs, 1).squeeze(2)
        return outputs
#---------------------
steps=2
# set random seed to 0
np.random.seed(0)
torch.manual_seed(0)
# load data and make training set
data = torch.load('/content/traindata.pt')
input = torch.from_numpy(data[3:, :-1])
target = torch.from_numpy(data[3:, 1:])
test_input = torch.from_numpy(data[:3, :-1])
test_target = torch.from_numpy(data[:3, 1:])
# build the model
seq = Sequence()
seq.double()
criterion = nn.MSELoss()
# use LBFGS as optimizer since we can load the whole data to train
optimizer = optim.LBFGS(seq.parameters(), lr=0.8)
#begin to train
for i in range(steps):
    print('STEP: ', i)
    def closure():
      optimizer.zero_grad()
      out = seq(input)
      loss = criterion(out, target)
      print('loss:', loss.item())
      loss.backward()
      return loss
    optimizer.step(closure)
    # begin to predict, no need to track gradient here
    with torch.no_grad():
        future = 1000
        pred = seq(test_input, future=future)
        loss = criterion(pred[:, :-future], test_target)
        print('test loss:', loss.item())
        y = pred.detach().numpy()
    # draw the result
    plt.figure(figsize=(30,10))
    plt.title('Predict future values for time sequences\n(Dashlines are predicted values)', fontsize=30)
    plt.xlabel('x', fontsize=20)
    plt.ylabel('y', fontsize=20)
    plt.xticks(fontsize=20)
    plt.yticks(fontsize=20)
    def draw(yi, color):
        plt.plot(np.arange(input.size(1)), yi[:input.size(1)], color, linewidth = 2.0)
        plt.plot(np.arange(input.size(1), input.size(1) + future), yi[input.size(1):], color + ':', linewidth = 2.0)
    draw(y[0], 'r')
    draw(y[1], 'g')
    draw(y[2], 'b')
    #plt.savefig('predict%d.pdf'%i)
    plt.draw()
    plt.close()
 
    # save the model
    torch.onnx.export(seq, test_input, "LSTM2.onnx")
```
## Expected behavior

`torch.onnx.export(seq, test_input, "LSTM2.onnx")` should write the model successfully.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@srohit0 - I see that Chunk has some (at least partial) support. https://github.com/pytorch/pytorch/blob/6471b5dc66a5a56ac48d86ff86a783724cf2c3a6/torch/onnx/symbolic_opset9.py#L484

Could you please try exporting with opset_version=12? Also, I'd recommend setting the model to eval mode (`model.eval`) before exporting. If you still see an issue, let us know.

**Comment by spandantiwari** [comment]
@srohit0 - are you still seeing an issue?

**Comment by srohit0** [comment]
@spandantiwari - we're using [ONNX 1.5](https://github.com/onnx/onnx/releases/tag/v1.5.0) which supports opset versions 8, 9 and 10. So using opset 12 isn't helpful, since it breaks onnx parser.

**Comment by spandantiwari** [comment]
OK, then opset 10 is worth a try. Also, did you try setting the model to eval mode before export?

**Comment by BowenBao** [comment]
@srohit0 - Currently opset 9 and below has only static chunk support, i.e. the number of chunks and sizes are fixed. Depending on the actual use case we can check if this could be extended.

The repro code you provided shows model `Sequence()` encapsulating all the details which are not visible. Can you point a link to the model code if it's public? And if not, could you create sample repro case for us to look at. Thanks.

**Comment by srohit0** [comment]
Thank you @BowenBao and @spandantiwari for such a fantastic support. You guys rock ! 👏

I shall get back to you with required information in few days.

**Comment by spandantiwari** [comment]
@srohit0 - could you please provide some more info/repro?

**Comment by srohit0** [comment]
Thanks for being patient @spandantiwari. Below is more info:

**opset_version=10 fails**
```
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

RuntimeError: Exporting the operator chunk to ONNX opset version 10 is not supported. Please open a bug to request ONNX export support for the missing operator.
```
Since ONNX version 1.5.0 only support opset_version 8, 9 & 10, **fix in versions 11, 12 and beyond aren't helpful.**

I tried those versions anyhow to give you more info. Here are the results:

**opset_version=11 fails**
```
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

RuntimeError: Exporting the operator chunk to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.
```
**opset_version=12 fails**
```
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

RuntimeError: Exporting the operator chunk to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

**opset_version=13 not available**
```
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py in _set_opset_version(opset_version)
    479         _export_onnx_opset_version = opset_version
    480         return
--> 481     raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
    482 
    483 _operator_export_type = None

ValueError: Unsupported ONNX opset version: 13
```

I hope, this helps.

I'd like to get tickets for next PyTorch Developer Conference.  😊 Thanks in advance.

**Comment by srohit0** [comment]
> @srohit0 - Currently opset 9 and below has only static chunk support, i.e. the number of chunks and sizes are fixed. Depending on the actual use case we can check if this could be extended.
> 
> The repro code you provided shows model `Sequence()` encapsulating all the details which are not visible. Can you point a link to the model code if it's public? And if not, could you create sample repro case for us to look at. Thanks.

I added the Sequence() model along with other details to produce the crash in-house.  I hope, this helps.

**Comment by EmreOzkose** [comment]
Any improvement on this issue?

**Comment by srohit0** [comment]
Not so far

**Comment by BowenBao** [comment]
@shubhambhokare1 can you take a look?

**Comment by srohit0** [comment]
> Any improvement on this issue?

Hey @EmreOzkose , 
    don't you see @BowenBao @spandantiwari @smessmer @shubhambhokare1 and others in #Pytorch team are working hard on the issue.

There is no need to remind then EVERY YEAR.  😂🤣

**Comment by BounharAbdelaziz** [comment]
Hi,
Same issue here, tried different opsets but in vain...

No fix has been released yet ?

**Comment by shubhambhokare1** [comment]
The PR #59644 should add support for chunk (with dynamic chunk values) in opset 11.

Currently the PT-ONNX exporter has support for chunk operator (opset 9) onwards but for cases with constant chunk values.
For example,
'''torch.chunk(x, 3, dim=1)'''
is exported correctly as prim_ConstantChunk operator

Now, as in the issue's case, the value of chunk maybe dynamic, for example,
'''torch.chunk(x, x.size(0), dim=1)'''
This case was not supported previously and hence the unrecognized operator messages. This PR should add this functionality opset 11 onwards.

Hope this helps.

**Comment by BounharAbdelaziz** [comment]
Hi,

I fixed it following this : https://github.com/jantic/DeOldify/issues/166#issue-505566455

**Comment by BowenBao** [comment]
We’ve gone ahead and closed this issue because it is resolved for opset >= 11. For opset < 11 it won't be fixed because onnx cannot represent dynamic chunk values. The related issue around `aten::mv` is also resolved. We encourage you to try the latest pytorch-preview (nightly) version.
