### ISSUE TITLE
Transforming from .pth to .onnx failed. 

### ISSUE THREAD

**Issue by Joevaen** [pytorch/pytorch#42788]
Hi,
Below picture is the result of a transformation from pth to onnx who are shown in Neutron:
![image](https://user-images.githubusercontent.com/46133615/89725810-4d706980-da46-11ea-8ddf-dc0ebb057ae7.png)
Left is pth's architecture and right is onnx's architecture.
My origin network of .pth includes conv3d and the input data is 5-dim. Can the onnx do the operations on conv3d?
SOS!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Yes, ONNX has support for 3D conv. Are you seeing any error somewhere? If yes, please feel free to reopen the issue and add a repro. For questions, I would recommend posting on PyTorch discussion forum.
