### ISSUE TITLE
flip operation in onnx export

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#42798]
Flip index such as [::-1, :] operation on pytorch to onnx is not well supported for now.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Can you please provide a reasonable repro for this? We can take a look. Also, please try the latest version of PyTorch as there are some improvements to indexing as well.

**Comment by spandantiwari** [comment]
Please reopen with repro if you like.
