### ISSUE TITLE
Rationalize functions signature specification in native_functions.yaml and derivatives.yaml

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#4279]
See https://github.com/pytorch/pytorch/pull/4259 for a specific case: because gen_variable_type relies on dynamic_types from Declarations.cwrap in order to generate variable unpacking code, we need the `condition` of `torch.where` to end up as a `BoolTensor` in Declarations.yaml, so we type it as a `BoolTensor`.  But `gen_variable_type` does matching on `type` and not `dynamic_type`, so in derivatives.yaml you have to specify the type as a `Tensor`, which doesn't match.

There are a few different ways we could solve this (and they aren't all orthogonal):
1) Merge native_functions.yaml and derivatives.yaml so you only need to specify the function signature once.
2) Have gen_variable_type look at the dynamic_type instead of type.
3) Avoid doing specific-type unpacking.  Right now we do it to avoid a Variable dynamic_cast, but if we had some other way of telling a Variable (i.e. an open-ended typeid or bitmask with unreserved bits) we could do the unwrapping efficiently and drop the type checks.

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by gchanan** [comment]
I believe this has mainly been addressed except derivatives.yaml doesn't use overload names.

**Comment by ezyang** [comment]
It's probably not worth making derivatives.yaml use overload names, as a single derivative definition covers also the inplace and -out place derivatives, so you'd end up copy pasting a lot of stuff in that case.
