### ISSUE TITLE
torch.onnx.export to support saving custom user meta data

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#42808]
This would be useful to store information about hyperparameters. This is already supported:
- by ONNX: https://github.com/onnx/onnx/blob/master/docs/IR.md#optional-metadata
- by ONNXRUNTIME: https://microsoft.github.io/onnxruntime/python/auto_examples/plot_metadata.html

This is currently only possible by manual loading the exported model, adding the meta and storing it back - quite nasty, given that this need is very common.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@vadimkantorov - are you asking for a capability for adding any generic metadata or specifically the “standard optional metadata"? Also, note that ONNX exporter is mainly targeted to inference use cases for now, so the use for storing training hyperparameters hasn't been discussed much.

**Comment by vadimkantorov** [comment]
Even for inference, it is useful for archival purposes (e.g. to be able to share a single onnx file and not onnx+json metadata file).

All these are useful:
```
producer_name | string | The name of the tool used to generate the model.
producer_version | string | A string representing the version of the generating tool.
model_version | int64 | A version of the model itself, encoded in an integer.
doc_string | string | A human-readable documentation for this model. Markdown is allowed.
graph | Graph | The parameterized graph that is evaluated to execute the model.
metadata_props | map<string,string> | Named metadata values; keys should be distinct.
training_info | TrainingInfoProto[]
```

**Comment by spandantiwari** [comment]
Some of them, like producer_version and producer_name, are added by the exporter. training_info is not a metadata field, but the spec for exporting a training model, but is not supported in the exporter. 

I agree that it could be useful to add support for taking other fields from the user. Feel free to consider sending in a PR for that.

**Comment by KarelPeeters** [comment]
Would a PR for this still be welcome? I'm willing to give it a shot.

As far as I can tell this shouldn't be too hard to add, add an extra `Dict[str, str]` argument to the python function and follow the call tree until things are actually written to the file.

**Comment by vadimkantorov** [comment]
@KarelPeeters I think so, go ahead :)

**Comment by SolomidHero** [comment]
Hi, is there any update on this feature? Can't see any linked PR or whatever

**Comment by KarelPeeters** [comment]
I had a lot of trouble getting pytorch to build on my system, and in the mean time my personal use case for this feature went away. I still might revisit this in the future but I have no concrete plans right now.

**Comment by SolomidHero** [comment]
OK.
For anybody, who is wondering how to overcome storing metadata, this code is used (as mentioned in issue starter msg):
```python3
import onnx

assert dict(str(cfg)) == cfg # yours metadata dict, class, whatever

# storing
model = onnx.load(onnx_path)
meta = model.metadata_props.add()
meta.key = "cfg"
meta.value = str(cfg)
onnx.save(onnx_model, onnx_path)

# loading
cfg = eval(onnx.load(onnx_path).metadata_props[0].value)
```
