### ISSUE TITLE
git clone fails with "Unable to checkout 'f015d698006c4a11be15b1ebb75b3b9bb317b914' in submodule path 'third_party/tensorpipe'"

### ISSUE THREAD

**Issue by bnsh** [pytorch/pytorch#42804]
## 🐛 Bug

Basically, I can't seem to clone the repo as suggested here: https://github.com/pytorch/pytorch#get-the-pytorch-source

## To Reproduce

1. git clone --recursive https://github.com/pytorch/pytorch

## Expected behavior

I expected it to clone the repository and not error (or at least return with an exit code of 0 if this is some sort of false positive...)
Instead it errors with

```
Cloning into 'third_party/tensorpipe'...
fatal: reference is not a tree: f015d698006c4a11be15b1ebb75b3b9bb317b914
Unable to checkout 'f015d698006c4a11be15b1ebb75b3b9bb317b914' in submodule path 'third_party/tensorpipe'
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet

**Comment by malfet** [comment]
Please update your repo past https://github.com/pytorch/pytorch/commit/05f00532f52883d29a08d96b2961042cc41573ab
cc: @lw
