### ISSUE TITLE
wrong in torch.var

### ISSUE THREAD

**Issue by zsp1197** [pytorch/pytorch#42803]
## 🐛 Bug

I do not think the calculation of variance in torch.var is correct, as you forget the "1/m" term in "sigma(x_i-u)^2*(1/m)"

## To Reproduce

torch.var(torch.tensor([[-1., -2., 3.],[1., 2., -3.]]),0).numpy()==np.var([[-1., -2., 3.],[1., 2., -3.]],0)

**Comment by SsnL** [comment]
np doesn't use bessel's correction by default (`ddof=0`) yet pytorch does (`unbiased=True`). hence the difference in results.

**Comment by smessmer** [comment]
This looks resolved. Please feel free to reopen if you still have questions.
