### ISSUE TITLE
Implementation of Bipolar Activation Functions

### ISSUE THREAD

**Issue by larspars** [pytorch/pytorch#4281]
We're looking to make a pull request for [bipolar activation functions](https://arxiv.org/abs/1709.04054). Hope to get some feedback.

This is a trick to make activation functions self centering. In short: Because the ReLU keeps only positive numbers, it shifts the post-activation mean in a positive direction. However, if we for every other neuron we instead keep the negative numbers, we cancel this effect. 

So for half the neurons we do `ReLU(x)`, and other half we do `-ReLU(-x)`. For an i.i.d. input vector, the effect of this is to halve the mean of the vector, post-activation, `E[BReLU(x)] = 0.5E[x]`.

In our paper we find empirically that this can help learning in RNNs and ConvNets. Our empirical results are with ReLUs and ELUs, but I would expect it to hold for anything ReLU like.

One way to implement it would be to put something like the following in nn/functional.py:

```python
def _make_bipolar(fn):
    def _fn(x, *args, **kwargs):
        dim = 0 if x.dim() == 1 else 1
        x0, x1 = torch.chunk(x, chunks=2, dim=dim)
        y0 = fn(x0, *args, **kwargs)
        y1 = -fn(-x1, *args, **kwargs)
        return torch.cat((y0, y1), dim=dim)

    return _fn
    
brelu = _make_bipolar(relu)
belu = _make_bipolar(elu)
bselu = _make_bipolar(selu)
leaky_brelu = _make_bipolar(leaky_relu)
bprelu = _make_bipolar(prelu)
brrelu = _make_bipolar(rrelu)
bsoftplus = _make_bipolar(softplus)
bsigmoid = _make_bipolar(sigmoid)
bipolar_max_pool1d = _make_bipolar(max_pool1d)
bipolar_max_pool2d = _make_bipolar(max_pool2d)
bipolar_max_pool3d = _make_bipolar(max_pool3d)
```

This also includes bipolar max-pooling functions (i.e. min-pooling for half the inputs).

1) Would there be interest in a pull request for this?
2) Any comments on the implementation? Of course, we'll have to add doc strings, and also put something similar into nn/modules/activation.py

**Comment by lanpa** [comment]
How about implement it as a decorator? In this way, users can apply it to newer activation functions and you only need to write one doc string.

**Comment by larspars** [comment]
I'm not sure if I understand what you mean. I suppose you could add @_make_bipolar as a decorator to new definitions, e.g:

```python
@_make_bipolar
def my_activation_fn(x):
	return threshold(x, -0.5, -0.5)
```

But I don't see how to use it on the existing activation functions without replacing them.

**Comment by apaszke** [comment]
Thanks for the proposal, but I we're trying to keep the core fairly lean and only extend it with very popular layers and functions. I'm happy to add this if it turns out there are a few papers that successfully use this to achieve good results, and it will become more standard in the community. Until then, especially considering how simple it is to implement it yourself, let's wait and see. Hope you understand!

**Comment by lanpa** [comment]
@larspars 
I means let user define Bipolar function by themselves. So less code will modified. I think that's the same idea as yours:)

```python
@_make_bipolar
def brelu():
    return torch.nn.ReLU()
