### ISSUE TITLE
istft does not support batching

### ISSUE THREAD

**Issue by jonashaag** [pytorch/pytorch#42813]
## 🐛 Bug

`torch.istft` documentation says:

> `input` (Tensor) – The input tensor. Expected to be **output of stft()**, either 3D (fft_size, n_frame, 2) or 4D (channel, fft_size, n_frame, 2).

BUT the output of `torch.stft()` may also have an additional batch dimension that is not supported:

> Returns the real and the imaginary parts together as one tensor of size (∗×N×T×2), where ∗ is the optional batch size of input, [...].

And if you stick `stft()` output into `istft()`, indeed you get an error that says `istft()` does only support 3 or 4 dimensions.

**Comment by faroit** [comment]
I think this was supported in torchaudio (see https://github.com/pytorch/audio/pull/523) 
@vincentqb is there a specific reason why this has been dropped?

**Comment by vincentqb** [comment]
Can you provide a minimal example that fails in pytorch?

```python
In [45]: t1 = torch.rand(2, 100)

In [46]: t2 = torch.stft(t1, 10)

In [47]: t3 = torch.istft(t2, 10)

In [48]: t3.shape
Out[48]: torch.Size([2, 100])
```
```python
In [49]: t1 = torch.rand(2, 2, 100)

In [50]: t2 = torch.stft(t1, 10)  # This is not support in pytorch.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-50-aff354fa0350> in <module>
----> 1 t2 = torch.stft(t1, 10)

~/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/functional.py in stft(input, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided)
    463         input = F.pad(input.view(extended_shape), (pad, pad), pad_mode)
    464         input = input.view(input.shape[-signal_dim:])
--> 465     return _VF.stft(input, n_fft, hop_length, win_length, window, normalized, onesided)
    466 
    467 

RuntimeError: stft(torch.FloatTensor[2, 2, 110], n_fft=10, hop_length=2, win_length=10, window=None, normalized=0, onesided=1): expected a 1D or 2D tensor of floating types
```

```python
In [54]: t1 = torch.rand(2, 100)

In [56]: t2 = torch.stft(t1, 10)

In [57]: t3 = torchaudio.functional.istft(t2, 10)
/private/home/vincentqb/anaconda3/envs/pytorch/lib/python3.8/site-packages/torchaudio/functional.py:109: UserWarning: istft has been moved to PyTorch and will be removed from torchaudio, please use torch.istft instead.
  warnings.warn(

In [58]: t3.shape
Out[58]: torch.Size([2, 100])
```

> I think this was supported in torchaudio (see [pytorch/audio#523](https://github.com/pytorch/audio/pull/523))
> @vincentqb is there a specific reason why this has been dropped?

Example 2 above was indeed supported in torchaudio (using reshape, see [here](https://github.com/pytorch/audio/pull/523/files#r474060046)). torchaudio did not have a batch test for istft, and the migration did not mark the regression in torchaudio in #523. The documentation in torchaudio also claims batch support for spectrograms, [here](https://github.com/pytorch/audio/pull/523/files#diff-292a2ef33b3ecf4c40cda1a4afe58760R87-R88.

Is this an issue with the torch implementation, or with a regression in torchaudio? @mthrok, have you diagnosed that this is not an issue with torchaudio?

**Comment by jonashaag** [comment]
Oops. You are correct, it does support a batch dimension. I just confirmed that the tensor I used was of shape [batch, 1, y, z, 2]; the 2nd dimension was added by some call to `unsqueeze()`.

**Comment by vincentqb** [comment]
Good to hear! Based on your comment, I will close this issue. Please feel free to re-open if this did not resolve it.

**Comment by faroit** [comment]
@jonashaag maybe you want to reopen this one?

**Comment by faroit** [comment]
ping @vincentqb is there any path going forward for nd-stft and nd-istft or at least revert to torchaudios older behaviour?
