### ISSUE TITLE
Cant install PyTorch

### ISSUE THREAD

**Issue by AudeJavel12** [pytorch/pytorch#42832]
## 🐛 Bug

  
Can't install Pytorch.
I tried : 
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
as well as :
pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

## To Reproduce

pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html

```
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\PC\AppData\Local\Temp\pip-install-hxtectme\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
DEPRECATION: Could not build wheels for torch which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pyyaml, torch, torchvision
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-hmkq398i\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\torch'
         cwd: C:\Users\PC\AppData\Local\Temp\pip-install-hxtectme\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PC\AppData\Local\Temp\pip-install-hxtectme\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "d:\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\PC\AppData\Local\Temp\pip-install-hxtectme\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "d:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\PC\AppData\Local\Temp\pip-install-hxtectme\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-hxtectme\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-hmkq398i\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\torch' Check the logs for full command output.
```

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 企业版
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 442.19
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.2
[conda] Could not collect

Process finished with exit code 0

## Additional context

cc @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
@AudeJavel12  can you please check if you are running 32-bit python by running `python -c 'import sys;print(sys.maxsize.bit_length())'` and share the output here?

**Comment by xuhdev** [comment]
Could you also show the complete `pip install` output? I believe there is a package that we forgot to put in `.gitignore` file.

**Comment by AudeJavel12** [comment]
Hi, thx for help! here are outputs!

import sys
print(sys.maxsize.bit_length())  --> output is 31


pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.6.0


second try:

pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Collecting torchvision
  Using cached torchvision-0.2.2.post3-py2.py3-none-any.whl (64 kB)
Requirement already satisfied: pyyaml in d:\python\lib\site-packages (from torch) (5.3.1)
Requirement already satisfied: pillow>=4.1.1 in d:\python\lib\site-packages (from torchvision) (7.0.0)
Requirement already satisfied: six in c:\users\pc\appdata\roaming\python\python38\site-packages (from torchvision) (1.14.0)
Requirement already satisfied: numpy in d:\python\lib\site-packages (from torchvision) (1.18.2)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PC\AppData\Local\Temp\pip-wheel-nlkd7tpa'
       cwd: C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "d:\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "d:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "d:\python\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "d:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "d:\python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Failed to build torch
DEPRECATION: Could not build wheels for torch which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: torch, torchvision
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-ysmnymho\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\torch'
         cwd: C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "d:\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "d:\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\PC\AppData\Local\Temp\pip-install-ho8ed0gb\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-ho8ed0gb\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-ysmnymho\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python\Include\torch' Check the logs for full command output.

**Comment by nbcsm** [comment]
> import sys
> print(sys.maxsize.bit_length()) --> output is 31

your python is 32 bits.
unfortunately, official pytorch package does not support 32bits.

to install 64bits python, please go to https://www.python.org/downloads/windows/, and choose from x86-64.

**Comment by AudeJavel12** [comment]
OK, I upgraded to 64 bits, uninstalled all other versions.

now, outputs:


C:\Users\PC>pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.6.0

C:\Users\PC>pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-12jx861l\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-12jx861l\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\PC\AppData\Local\Temp\pip-pip-egg-info-z78cg8jc'
         cwd: C:\Users\PC\AppData\Local\Temp\pip-install-12jx861l\torch\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PC\AppData\Local\Temp\pip-install-12jx861l\torch\setup.py", line 147, in <module>
        import numpy as np
      File "d:\python\lib\site-packages\numpy\__init__.py", line 140, in <module>
        from . import _distributor_init
      File "d:\python\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
        WinDLL(os.path.abspath(filename))
      File "d:\python\lib\ctypes\__init__.py", line 374, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

C:\Users\PC>

**Comment by xuhdev** [comment]
Try replace `===` with `==`

**Comment by nbcsm** [comment]
I believe the new installed 64 bits python is not added to your PATH correctly.

could you try ```where python``` to see which python you are using?

and you can use ```python -VV``` to see whether it is 32 bits or 64 bits.

**Comment by xuhdev** [comment]
One possibility is that you `pip` is really old. Run `pip --version` to see.

**Comment by nbcsm** [comment]
so is the pip, try ```where pip```,
you may want to adjust your PATH to make sure 64 bits python/pip are placed **before** 32 bits versions.

**Comment by AudeJavel12** [comment]
=== or  == i get same outputs

C:\Users\PC>python -VV
Python 3.9.0b5 (tags/v3.9.0b5:8ad7d50, Jul 20 2020, 18:35:09) [MSC v.1924 64 bit (AMD64)]

C:\Users\PC>pip --version
pip 20.2.1 from d:\python\lib\site-packages\pip (python 3.9)

I uninstalled 32bit versions so I think its the good one working.

**Comment by nbcsm** [comment]
oh, you are using python 3.9.

currently, max python version supported is 3.8.

**Comment by AudeJavel12** [comment]
Ok. I just got 3.8 64bits , now it works. thx all for help!
Any recommendation for beginner tutorial ? =)  ( I would like to do deep learning to solve strategic games. )

**Comment by nbcsm** [comment]
Glad to know it works. Close this issue.

You may want to start with https://pytorch.org/tutorials/

**Comment by faizanahemad** [comment]
> oh, you are using python 3.9.
> 
> currently, max python version supported is 3.8.

I think mentioned this in getting started of pytorch website (https://pytorch.org/get-started/locally/). It only mentions that "It is recommended that you use Python 3.5 or greater" but not that 3.9 is not supported.
