### ISSUE TITLE
Unexpected behavior when initializing float tensor from numpy boolean array

### ISSUE THREAD

**Issue by alexub** [pytorch/pytorch#4288]
`torch.Tensor(np.asarray([True, False]))` appears to have the same behavior as `torch.Tensor(size=2)`. 
Both give something like `-3.8315e+06   4.5761e-41   [torch.FloatTensor of size 2]`

Same behavior with other inputs: it appears to only look at the size of the boolean array.

Passing a list of booleans gives a Tensor with ones and zeros as expected. It would be intuitive for `torch.Tensor(numpy_boolean_array)` to have the same behavior as `torch.Tensor(list_of_booleans)`. If changing the behavior isn't possible, it might make sense to throw an exception.

(I'm using Pytorch 0.3.0.post4, python3.5, cuda8.0).

Edit: I installed Pytorch with pip, which agrees with @albanD 's repro

**Comment by albanD** [comment]
Hi,

Running this with python 2.7 gives the following error `TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.` which is what you should see as well.
Building from source with python 3.5 gives me the correct error message as well.
Installing from pip with python 3.5 or python 2.7 does not raise as reported.

@soumith I guess something is wrong with the pip wheel?
