### ISSUE TITLE
Shapes not documented properly in MarginRankingLoss 

### ISSUE THREAD

**Issue by mariosasko** [pytorch/pytorch#42884]
## 📚 Documentation

This issue refers to #42864, but the original issue was closed by the author while I was writing my response to it.

These are the docs at the moment:
![loss1](https://user-images.githubusercontent.com/47462742/89954344-2f1a9180-dc31-11ea-9dc1-5e73ee5f1d88.PNG)

Based on the [source](https://github.com/pytorch/pytorch/blob/0ff0fea42bf9721b87e01fe15445dfd3ea5f2093/aten/src/ATen/native/Loss.cpp#L74) the correct input/target shape is:
- Input 1: (N, ∗) where ∗ means, any number of additional dimensions
- Input 2: (N, ∗) same shape as Input 1, or it has to be broadcastable to that shape
- Target: (N, ∗), same shape as Input 1 or Input 2, or it has to be broadcastable to that shape

So I think  this part in the docs should be fixed and an example of how to use the loss would be helpful.

cc @jlin27 @albanD @mruberry

**Comment by bharnoufi** [comment]
It actually works with:
Target: (N, 1) and Input: (N, D) (il it is not necessary that Target: (N,D))

**Comment by mruberry** [comment]
We would happily accept a PR fixing this! (I wonder if the tests for this function need to be updated, too?)

**Comment by mariosasko** [comment]
Yes, I can do that. If I recall correctly, the tests are fine and don't need to be updated.
