### ISSUE TITLE
Wrong version after installing from source

### ISSUE THREAD

**Issue by JoabeSilva** [pytorch/pytorch#42892]
## 🐛 Bug

I've just installed pytorch from source, and it should install current 1.7.0 version. But after installing when I print `torch.version` it outputs 1.3.0.

## To Reproduce

1. Install pytorch from source
2. Run code bellow

`import torch
print(torch.__version__)`

## Expected behavior

During installing it outputs "_Building wheel torch-1.7.0a0+7a9ae52_" and everything goes fine. But after installing it looks like the wrong version was installed.

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 435.21
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.3.0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1           py37hbc911f0_0  
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] numpydoc                  1.1.0                      py_0  
[conda] torch                     1.7.0a0+7a9ae52          pypi_0    pypi

**Comment by SsnL** [comment]
> [pip3] torch==1.3.0

uninstall your existing lib

**Comment by JoabeSilva** [comment]
Sorry, there was still an older installation on pip.
After uninstalling it, I got the right version.
