### ISSUE TITLE
Weird numerical error with division between tensor and python built-in int 

### ISSUE THREAD

**Issue by rogerwwww** [pytorch/pytorch#42896]
## 🐛 Bug

When I compute ``2401 // torch.tensor(49)``,  pytorch gives a wrong result 48. Here are several tests I have conducted:

```python
>>> import torch
>>> torch.__version__
'1.3.0'
>>> 2401 // torch.tensor(49)
tensor(48) # wrong!
>>> 2401 // torch.tensor(49).cuda()
tensor(48, device='cuda:0') # wrong!
>>> 2401 // torch.tensor(49).item()
49 # correct
>>> 2401 // 49
49 # correct
>>> torch.tensor(2401) // torch.tensor(49)
tensor(49) # correct
```

And only ``2401 // torch.tensor(49)`` gives the wrong result. I have also tested on several other random digits, and no mistake was found. 

## To Reproduce

1. ``import torch``
1. ``2401 // torch.tensor(49)``
1. See if the program gives the correct result 49.

## Expected behavior

``2401 // torch.tensor(49)`` will result in ``tensor(49)``

## Environment
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.168                      0
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.14           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] numpy                     1.17.2           py36haad9e8e_0
[conda] numpy-base                1.17.2           py36hde5b4d6_0
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

cc @ezyang @gchanan @zou3519

**Comment by zhangguanheng66** [comment]
See the same results on my side.

**Comment by malfet** [comment]
Heh, that's because `2401 // tensor(49)` is computed as `(tensor(49).double().reciprocal() * 2401).type_as(int64)`

**Comment by malfet** [comment]
Wouldn't something like that solve the problem:
```
diff --git a/torch/tensor.py b/torch/tensor.py
index 253ab15b55..f43300c5f3 100644
--- a/torch/tensor.py
+++ b/torch/tensor.py
@@ -505,7 +505,7 @@ class Tensor(torch._C._TensorBase):
         if self.dtype.is_floating_point or self.dtype.is_complex:
             return self.reciprocal() * other
         else:
-            return (self.double().reciprocal() * other).type_as(self)
+            return torch.tensor(other) / self
 
     __rtruediv__ = __rdiv__
     __itruediv__ = _C._TensorBase.__idiv__
```

**Comment by albanD** [comment]
cc @mruberry who was working on div behavior recently.

**Comment by malfet** [comment]
Grabbing for myself, will discuss perf implication on GPU with @ngimel

**Comment by mruberry** [comment]
> Grabbing for myself, will discuss perf implication on GPU with @ngimel

Please request me for review on rdiv changes, too, since our division behavior is changing.

**Comment by ngimel** [comment]
"//" should go to rfloordiv and not rdiv?  https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L541-L545,

**Comment by kshitij12345** [comment]
Probably related #43874

**Comment by mruberry** [comment]
Floordiv incorrectly truncates its quotient instead of flooring it currently. Let's track the issue in one place at: https://github.com/pytorch/pytorch/issues/43874.
