### ISSUE TITLE
torch.Tensor.ndim is not typed

### ISSUE THREAD

**Issue by KKawamura1** [pytorch/pytorch#42908]
## 🐛 Bug

```python
import torch

a = torch.Tensor().ndim  # mypy says: `error: "Tensor" has no attribute "ndim"`
```

## Environment

torch 1.6.0 and master (ecb9e790ed6ceafa738ad52a500b9e50bc0fc241)

## Why this occurs and how to solve

https://github.com/pytorch/pytorch/pull/38157 removed `torch/__init__.pyi.in` and introduced `torch/_C/__init__.pyi.in`, but some methods defined in `torch/__init__.pyi.in` (`ndim`, `T`, and `grad_fn`) was not salvaged and had gone away.
`T` and `grad_fn` was rescued in https://github.com/pytorch/pytorch/issues/40658. Only the `ndim` is still not typed.

The solution wolud be just adding `ndim` attribute to `_TensorBase` in `torch/_C/__init__.pyi.in`.

cc @ezyang @malfet @rgommers

**Comment by zhangguanheng66** [comment]
Can you share a code snippet? I can not reproduce the error when running:
```
import torch
a = torch.Tensor().ndim
```

**Comment by rgommers** [comment]
I can reproduce it, bug report seems correct. On current master:
```
$ cat tmp.py
import torch
reveal_type(torch.Tensor.ndim)
reveal_type(torch._C._TensorBase.ndim)

$ mypy tmp.py 
tmp.py:3: error: "Type[Tensor]" has no attribute "ndim"  [attr-defined]
tmp.py:3: note: Revealed type is 'Any'
tmp.py:4: error: "Type[_TensorBase]" has no attribute "ndim"  [attr-defined]
tmp.py:4: note: Revealed type is 'Any'
```

**Comment by malfet** [comment]
Let me quickly add this one to the list
