### ISSUE TITLE
Installation problems caused by commands provided on the official website

### ISSUE THREAD

**Issue by bulingda** [pytorch/pytorch#42906]
I want to install pytorch1.5.1 torchvision0.6.1 in centos7 cuda10.2 python3.7. 
1.I clicked "Previous Versions of PyTorch" on the Pytroch site. 
2.I choice ‘v1.5.0’，‘wheel’，‘Linux and Windows’，‘# CUDA 10.2 pip install torch==1.5.0 torchvision==0.6.0 -f https://download.pytorch.org/whl/torch_stable.html’.
`(py37) [himap@localhost py37]$ pip install torch==1.5.1 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Requirement already satisfied: torch==1.5.1 in ./lib/python3.7/site-packages (1.5.1+cu92)
Requirement already satisfied: future in ./lib/python3.7/site-packages (from torch==1.5.1) (0.18.2)
Requirement already satisfied: numpy in ./lib/python3.7/site-packages (from torch==1.5.1) (1.18.1)`
After using this command, I get Pytroch1.5.1 + cu92
`>>> torch.__version__
'1.5.1+cu92'
`
3.When I use "pip install torch==1.5.1+cu102 -f https://download.pytorch.org/whl/torch_stable.html", he prompts me" `Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.5.1+cu102 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu92, 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.6.0+cu92)
ERROR: No matching distribution found for torch==1.5.1+cu102"`
So I think there is a problem with the official order.

cc @ezyang @seemethere @malfet @jlin27

**Comment by bulingda** [comment]
Would you please ask the officials to answer this question for me in their free time?

**Comment by bulingda** [comment]
Thank you very much！

**Comment by zhangguanheng66** [comment]
@seemethere  Could you comment on this?

**Comment by malfet** [comment]
You should be able to download pytorch-1.5.1 + CUDA-10.2 using the following link: https://download.pytorch.org/whl/cu102/torch-1.5.1-cp37-cp37m-linux_x86_64.whl 
But we need to update the documentation accordingly

**Comment by malfet** [comment]
Updated https://pytorch.org/get-started/previous-versions/
Closing. Please reopen if installation instructions still doesn't work.
