### ISSUE TITLE
Graph lowering (_jit_pass_lower_graph) during ONNX export of JIT scripted model seems seriously broken: dislikes Python scalars, None, Linear(bias=False)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#42914]
```python
import torch

class Model(torch.nn.Module):
    def __init__(self, x):
        super().__init__()
        self.x = x

    def forward(self, x):
        return x < self.x

def test(*args):
    model = Model(*args)
    dummy_input = [torch.tensor([[10]], dtype=torch.float32)]
    example_outputs = [model(*dummy_input)]
    model = torch.jit.script(model)
    torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)

test(3)
#  File "bug.py", line 16, in test
#    torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)
#  File "/miniconda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 203, in export
#    return utils.export(model, args, f, export_params, verbose, training,
#  File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
#    _export(model, args, f, export_params, verbose, training, input_names, output_names,
#  File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 526, in _export
#    graph, params_dict, torch_out = _model_to_graph(model, args, verbose, input_names,
#  File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 350, in _model_to_graph
#    method_graph, params = torch._C._jit_pass_lower_graph(graph, model._c)
# RuntimeError: Unknown type int encountered in graph lowering. This type is not supported in ONNX export.

test(3.0)
# ...
# RuntimeError: Unknown type float encountered in graph lowering. This type is not supported in ONNX export.

test(torch.tensor(3.0))
# works

test(torch.tensor(3))
# Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Less. Please report a bug to PyTorch. The scalar type Float of the first tensor is chosen.
``` 

cc @suo @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by vadimkantorov** [comment]
Same issue with tensor slicing:
```python
import torch

class Model(torch.nn.Module):
    def __init__(self, x):
        super().__init__()
        self.x = x

    def forward(self, x):
        return x[self.x]

def test(*args):
    model = Model(*args)
    dummy_input = [torch.tensor([[10]], dtype=torch.float32)]
    example_outputs = [model(*dummy_input)]
    model = torch.jit.script(model)
    torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)

test(torch.tensor(0))
# works

test(0)
# RuntimeError: Unknown type int encountered in graph lowering. This type is not supported in ONNX export.
```

**Comment by vadimkantorov** [comment]
cc @ezyang

**Comment by vadimkantorov** [comment]
graph lowering is called at https://github.com/pytorch/pytorch/blob/a6c8730045bc19ec94ed8b15bfabc69d17b3c4f7/torch/onnx/utils.py#L362

**Comment by vadimkantorov** [comment]
`torch.nn.Linear(in_channels, out_channels, bias = False)` is not supported by ONNX export of JIT scripted function. very strange

```python
import torch

class Model(torch.nn.Module):
    def __init__(self, x, bias):
        super().__init__()
        self.embeddings = torch.nn.Linear(1, 10, bias=bias)

    def forward(self, x):
        return self.embeddings(x)

def test(*args):
    model = Model(*args)
    dummy_input = [torch.tensor([[3]], dtype=torch.float32)]
    example_outputs = [model(*dummy_input)]
    model = torch.jit.script(model)
    torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)

test(torch.tensor([[3]]), True)
# works

test(torch.tensor([[3]]), False)
# Traceback (most recent call last):
#   File "bug.py", line 20, in <module>
#     test(torch.tensor([[3]]), False)
#   File "bug.py", line 16, in test
#     torch.onnx.export(model, dummy_input, 'test.onnx', example_outputs=example_outputs)
#   File "/miniconda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 203, in export
#     return utils.export(model, args, f, export_params, verbose, training,
#   File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
#     _export(model, args, f, export_params, verbose, training, input_names, output_names,
#   File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 526, in _export
#     graph, params_dict, torch_out = _model_to_graph(model, args, verbose, input_names,
#   File "/miniconda/lib/python3.8/site-packages/torch/onnx/utils.py", line 350, in _model_to_graph
#     method_graph, params = torch._C._jit_pass_lower_graph(graph, model._c)
# RuntimeError: Unknown type None encountered in graph lowering. This type is not supported in ONNX export.
```

**Comment by vadimkantorov** [comment]
@ezyang Lowering seems broken for ScriptModules, Is it actually needed? E.g. for ScriptFunctions lowering is not performed: https://github.com/pytorch/pytorch/blob/a6c8730045bc19ec94ed8b15bfabc69d17b3c4f7/torch/onnx/utils.py#L362

**Comment by zou3519** [comment]
Adding the labels cc'ed some folks who should be able to answer the question. Looking at the code, it looks like ONNX just doesn't like Python scalars or support type promotion.

**Comment by vadimkantorov** [comment]
Disliking None is an even more serious problem. Checks `if self.some_module is not None` are omnipresent. Maybe it could apply something like tracing anyway, i.e. is there a way to do some annotation with constants / Final somehow to mark an object attributes as Final (after it was set in constructor): https://discuss.pytorch.org/t/why-do-we-use-constants-or-final/70331/4 ?

I think it should support more types, then need for tracing is decreased.

**Comment by vadimkantorov** [comment]
I could use Final for my own code, but it would be good if standard PyTorch modules were annotated by themselves, e.g. Linear

**Comment by vadimkantorov** [comment]
So nn.Linear does: `self.register_parameter('bias', None)` and this leads to lowering disliking None.

And `bias` is not listed in its list of `__constants__`

**Comment by vadimkantorov** [comment]
If optional/undefined tensors [got finally into](https://github.com/onnx/onnx/issues/151) ONNX, then maybe bias could be transformed into checking if some tensor is undefined or not

**Comment by vadimkantorov** [comment]
And it could definitely at least wrap Python scalars into PyTorch Tensors. Also a scriptable type promotion function could be introduced if type promotion is not part of ONNX spec (and maybe deterministic type promotion could be done if all types in the expression are known at lowering time

**Comment by vadimkantorov** [comment]
Would making bias a constant/final help such an export?

**Comment by ailzhang** [comment]
Removing jit label since this issue is more on onnx support, please correct me if I'm wrong. Thanks!

**Comment by vadimkantorov** [comment]
I guess yes, except maybe the nn.Linear case. I guess torch.jit.script could have deduced that bias is a constant (since it does not change inside the scripted graph) and keep only the `bias is None` branch (somehow "tree-shaking" / "reachability analysis"?). Even if we need to do such a pass explicitly, it would be useful. 

I think yes, I guess it's up to ONNX export part of code to be able to wrap constants and known-type Python scalars, promote them to operation arguments, do some type promotion at least for known-type situations and maybe even do some None checks with some special values. But the pass described above would help with many None situations.

**Comment by Lilyjjo** [comment]
cc @spandantiwari

**Comment by spandantiwari** [comment]
There's significant room for improvements in handling the ScriptModule export due to legacy reasons. We are working on some projects to improve that code path right now.
In the meantime, if at all possible, I would recommend passing in the nn.Module to the export API and script only parts of the code that require scripting to get past any blocking issues.

**Comment by vadimkantorov** [comment]
That’s what we ended up doing... I hope some examples in this issue will be useful as potential tests

**Comment by BowenBao** [comment]
Should be resolved with @54112

**Comment by vadimkantorov** [comment]
Hmm, here the problem is about constant / shape / type propagation. Hopefully, #54112 will fix this, but not sure. Will need to check the examples above

**Comment by BowenBao** [comment]
Validated all cases are working correctly. Closing.

**Comment by vadimkantorov** [comment]
@BowenBao Is this one fixed too? https://github.com/facebookresearch/fairseq/issues/2468
