### ISSUE TITLE
3D affine transfrom F.affine_grid 

### ISSUE THREAD

**Issue by oldriver-wang** [pytorch/pytorch#42917]
I already get affine transfrom matrix from itk-snap, and its shape is 4 x 4,
likes:
1.02679 -0.0407256 -0.00554427 -2.419
-0.00454069 1.08451 -0.0294553 9.41757
0.00931154 0.0147304 1.0443 0.870609
0 0 0 1

How can I get a theta to generate a same 3D affined image according to torch.nn.functional.  affine_grid  and grid_sample

cc @albanD @mruberry

**Comment by mruberry** [comment]
This question is more appropriate to our forums: https://discuss.pytorch.org/. Try asking it there.
