### ISSUE TITLE
Lua/Torch to PyTorch

### ISSUE THREAD

**Issue by The-Gupta** [pytorch/pytorch#4292]
Is there a mapping resource - document/website page between libraries and its methods of Torch and PyTorch?
I'm trying to translate [a Lua/Torch code](https://github.com/mdtux89/amr-eager/blob/master/nnets/classify.lua) to Python with PyTorch/Numpy.

**Comment by soumith** [comment]
there isn't such a thing. There are threads on https://discuss.pytorch.org that discuss this, such as this thread: https://discuss.pytorch.org/t/convert-import-torch-model-to-pytorch/37

Use the forums to discuss this topic further.
