### ISSUE TITLE
Zombie process when use GPU

### ISSUE THREAD

**Issue by bamtercelboo** [pytorch/pytorch#4293]
- The same demo,  sometimes, a zombie process maybe appear, result in the GPU can`t use. I wonder to know whether has a same problem in others?  

- I wonder to know whether the CUDA kernel function has some unknown error result in the problem.

**Comment by floringogianu** [comment]
I encountered this over and over again on our servers, with `pytorch` most of the time but also `tensorflow` and `arrayfire` but have no idea how to reproduce this behaviour.

The only consistent observation I could draw is that it happens more often when I kill a process running on `cuda` and that this didn't happen with `lua` code.

**Comment by elanmart** [comment]
Wondering if this is somehow related to https://github.com/pytorch/pytorch/issues/2614

**Comment by bamtercelboo** [comment]
@floringogianu thanks, our linux server have encountered the problem many times in pytorch and arrayfire , every time must be restart server, can`t kill process, so trouble. 
How about you when encountered this, restart ?  or others ?

**Comment by bamtercelboo** [comment]
@elanmart  The version of CUDNN result in the problem?

**Comment by floringogianu** [comment]
@bamtercelboo Yes, the only solution for us is to restart the servers, no other way around it.

**Comment by apaszke** [comment]
Does it happen when you're doing multi-GPU training? NCCL can block the GPU until restart if you launch multiple multi-GPU processes, with some GPUs used by both of them

**Comment by bamtercelboo** [comment]
@apaszke The problem happens only on single GPU. Alought my servers has two GPU, but every time one GPU is enough in my demo.

**Comment by floringogianu** [comment]
I worked mostly with code that was using `multiprocessing` and shared `cuda` tensors between processes and I felt it happened most often with this kind of code, either when using single or multiple GPUs (don't know if NCCL was being involved - I was not using stuff like `torch.nn.DataParallel`). 

But colleagues confirmed this happening on single-process code also (stuff like doing inference through a pretrained VGG-net, etc.). Indeed all the machines where I've encountered this behavior were multi-GPU.

**Comment by bamtercelboo** [comment]
@floringogianu How do you kill a running process, Ctrl + C or kill command ? I am used to Ctrl + C before,  kill command use less, I wonder to know whether there are some influences ?

**Comment by lee2430** [comment]
For anyone who still suffer from this issue, try the following command:
`fuser -k /dev/nvidia*`
or
`kill $(lsof -t /dev/nvidia*)`

**Comment by Daniel451** [comment]
@bamtercelboo why did you close the issue? Did you find a solution?

I also encountered this problem, though it is happening for multi-GPU training only on our servers.

**Comment by ilml** [comment]
Same here
