### ISSUE TITLE
torch.autograd.gradcheck support for Tensor-like types (__torch_function__).

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#42942]
## 🚀 Feature
[gradcheck.py#L264](https://github.com/pytorch/pytorch/blob/master/torch/autograd/gradcheck.py#L264) explicitly requires its inputs to be of type torch.Tensor and thus doesn't work for Tensor-like objects.

## Motivation

Tensor-like objects might implement operations with autograd support. gradcheck helps check their correctness. Extending torch.autograd.gradcheck with support for Tensor-like types makes it easier for users to test their code.

## Pitch

This feature requests asks to extend gradcheck to also accept Tensor-like types and proposes using the presence of ```__torch_function__``` as a determinant, as we [usually do](https://github.com/pytorch/pytorch/blob/3d46e02ea1f8951bcef167c33bad0217ec9da980/torch/csrc/utils/python_arg_parser.cpp#L182). The rest of the code should work fine then, assuming the user has reasonable implementations for the used features. Potentially we could guard using methods such as "is_sparse" based on whether the given type is Tensor-like and actually has that method defined. This might ease the implementation of Tensor-like objects, because it doesn't require the user to implement those. We could signal this with a warning as well as we do when the user doesn't use float64 as an input dtype, etc.

## Alternatives

An alternative as a user is to copy-paste and modify this code for their own purposes.

## Additional context

I'm using this in context of the NestedTensor project. I labeled this as "module: numpy" based on the labels used in https://github.com/pytorch/pytorch/issues/24015.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @mruberry @rgommers @VitalyFedyunin @hameerabbasi

**Comment by rgommers** [comment]
> Potentially we could guard using methods such as `is_sparse`

Yes the tricky bit here seems to be specifying what the "contract" is when we'd accept Tensor-like's with a check like
```
isinstance(inp, torch.Tensor) or hasattr(inp, '__torch_function__')
```
The question is whether to handle these as feature requests as they come in, and then ad-hoc guard less likely to exist methods/attributes like `is_sparse`, or if there's a need to formalize this.

We may want to scan for usage of `isinstance(..., torch.Tensor)` in the whole code base to help give a picture of other features that can/should be made to work.

**Comment by albanD** [comment]
Would [`torch.is_tensor()`](https://pytorch.org/docs/stable/generated/torch.is_tensor.html?highlight=is_tensor#torch.is_tensor) solve this? maybe we should just stop using `isinstance()` altogether?

**Comment by hameerabbasi** [comment]
I had the following idea of making this work:

1. Dispatch `torch.autograd.gradcheck` through `__torch_function__`.
2. Inside `NestedTensor`, use the [`getattr` idiom](https://github.com/pytorch/rfcs/blob/4a82ea7a62ec29d451820aa3975c1d75f85bd50f/RFC-0001-torch-function-for-methods.md#wrapping-torchtensor) to recursively apply this method to all inner `Tensor`s.

The question is: Is that sufficient?

Unfortunately, it seems that this function uses quite a bit of API including `Tensor` methods, and there's no easy way to guarantee the presence of that API on `Tensor`-likes. Functions are easy; they will give a nice error about the absence of `__torch_function__`. A lot of method/property calls would fail with `AttributeError`s if the `Tensor`-like passed in wasn't properly designed or missing API.

**Comment by albanD** [comment]
> Unfortunately, it seems that this function uses quite a bit of API including Tensor methods, and there's no easy way to guarantee the presence of that API on Tensor-likes.

The particular implementation of gradcheck can be updated to work nicely with other objects. As long as we don't change the behavior (and don't make it too complex) it won't be an issue.

**Comment by rgommers** [comment]
> Potentially we could guard using methods such as `is_sparse` based on whether the given type is Tensor-like and actually has that method defined.

I think this is the most pragmatic approach, and if that guard has a clear comment about the `__torch_function__` use case, then it will be clear to people touching the implementation in the future that they should be careful about using some of the more non-standard methods.

> Dispatch `torch.autograd.gradcheck` through `__torch_function__`.

This isn't a good direction. A big part of the benefit of `__torch_function__` is that you can now reuse functions like `gradcheck` without too much trouble. Saying that we need to slap a dispatch method on `gradcheck` is like saying "well we really can't do that reuse".


Let's try using
```
isinstance(inp, torch.Tensor) or hasattr(inp, '__torch_function__')
```
and making it work for `NestedTensor`, and dealing with a more formalized way of what methods and functions a tensor-like must support at a later stage.

**Comment by hameerabbasi** [comment]
I looked into this, it seems it hits `Variable._execution_engine.run_backward` (and, in general, some `Variable._execution_engine` methods). It seems those aren't covered by `__torch_function__`. So we have a decision to make here: Either cover them or follow my original suggestion in https://github.com/pytorch/pytorch/issues/42942#issuecomment-673347857.

**Comment by rgommers** [comment]
It's unclear to me how it gets there, can you share the test code you're using @hameerabbasi?

> Either cover them

Covering private machinery like that with `__torch_function__` cannot be the right way of doing things; it's only public API that should be dispatching. It's possible something is missing, but it's not `_execution_engine`.

**Comment by hameerabbasi** [comment]
Here's the procedure I followed: I replaced `isinstance(..., Tensor)` with `isinstance(..., Tensor) or hasattr(..., "__torch_function__")` every time I hit a snag, until I hit this case, which happens to be defined in C++.

I then got this traceback:

```python
======================================================================
ERROR: test_gradcheck (__main__.TestGradCheckOverride)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_overrides.py", line 725, in test_gradcheck
    gradcheck(torch.add, (a, b), raise_exception=False)
  File "/home/habbasi/git/Quansight/pytorch/torch/autograd/gradcheck.py", line 308, in gradcheck
    analytical, reentrant, correct_grad_sizes = get_analytical_jacobian(tupled_inputs, o, nondet_tol=nondet_tol)
  File "/home/habbasi/git/Quansight/pytorch/torch/autograd/gradcheck.py", line 160, in get_analytical_jacobian
    grads_input = torch.autograd.grad(output, diff_input_list, grad_output,
  File "/home/habbasi/git/Quansight/pytorch/torch/autograd/__init__.py", line 190, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: all inputs have to be Tensors, but got Wrapper
```

The current version of my code can be found here: https://github.com/hameerabbasi/pytorch/tree/gradcheck-override

**Comment by rgommers** [comment]
Okay I can reproduce that. So it's failing inside `torch.autograd.grad`, because that function assumes that if it doesn't get a `Tensor`, it's a list of tensors:
```
    outputs = (outputs,) if isinstance(outputs, torch.Tensor) else tuple(outputs)
    inputs = (inputs,) if isinstance(inputs, torch.Tensor) else tuple(inputs)
```

`autograd.grad` does seem like something that could be considered for putting a dispatcher on. The next line, `get_numerical_jacobian`, will fail too though, with
```
Traceback (most recent call last):
  File "test/test_overrides.py", line 725, in test_gradcheck
    gradcheck(torch.add, (a, b), raise_exception=False)
  File "/home/rgommers/code/pytorch/torch/autograd/gradcheck.py", line 304, in gradcheck
    numerical = get_numerical_jacobian(fn, tupled_inputs, eps=eps)
  File "/home/rgommers/code/pytorch/torch/autograd/gradcheck.py", line 129, in get_numerical_jacobian
    d_tensor[d_idx] = compute_gradient(x_tensor, x_idx)
  File "/home/rgommers/code/pytorch/torch/autograd/gradcheck.py", line 75, in compute_gradient
    x[idx] = orig - eps
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

`gradcheck` does do a few too many things that rely on private implementation details. Things like `_as_tuple` and `torch._C._functions.UndefinedGrad` won't do the right thing for tensor-likes.

> The particular implementation of `gradcheck` can be updated to work nicely with other objects.

After trying Hameer's test, I get the feeling this was maybe a bit optimistic.

**Comment by hameerabbasi** [comment]
I've got this "sort of" working with an ugly hack: https://github.com/hameerabbasi/pytorch/blob/489f24b909621a7cf2156299c9fe37eaea9e1401/torch/autograd/gradcheck.py#L25

The issue @rgommers was seeing was due to `Wrapper` (the test class) having a `data` attribute, which I renamed to `_data`. Mostly, it was adding operators and the "ugly hack" after that.

**Comment by hameerabbasi** [comment]
Here's the set of methods/functions one needs to have defined in `__torch_function__` for this to work:

<details><summary>Defined Attributes</summary>

```
{'abs',
 'clone',
 'data',
 'detach',
 'dtype',
 'is_floating_point',
 'is_sparse',
 'item',
 'layout',
 'max',
 'nelement',
 'numel',
 'requires_grad',
 'reshape',
 'retain_grad',
 'size',
 'stride',
 'view',
 'zero_'}
```
</details>

<details><summary>Attributes that are set</summary>

```
{'requires_grad'}
```
</details>

<details><summary>Functions/methods passed into `__torch_function__`</summary>

```
{<built-in method numel of Tensor object at 0x7f2ef82b9f80>,
 <built-in method is_floating_point of Tensor object at 0x7f2ef814ad80>,
 <built-in method nelement of Tensor object at 0x7f2ef814ad80>,
 <built-in method is_floating_point of Tensor object at 0x7f2ef82c63c0>,
 <built-in method nelement of Tensor object at 0x7f2ef82c63c0>,
 <built-in method view of Tensor object at 0x7f2ef7a37b00>,
 <built-in method zero_ of Tensor object at 0x7f2ef7a37c80>,
 <built-in method numel of Tensor object at 0x7f2ef7a32f80>,
 <built-in method zero_ of Tensor object at 0x7f2ef7a3d180>,
 <built-in method numel of Tensor object at 0x7f2ef82be5c0>,
 <built-in method zero_ of Tensor object at 0x7f2ef7a3d080>,
 <built-in method numel of Tensor object at 0x7f2ef7a32200>,
 <built-in method zero_ of Tensor object at 0x7f2ef7a3d4c0>,
 <built-in method numel of Tensor object at 0x7f2ef7a37cc0>,
 <built-in method zero_ of Tensor object at 0x7f2ef7a3d480>,
 <built-in method abs of Tensor object at 0x7f2ef7a3d340>,
 <built-in method max of Tensor object at 0x7f2ef7a3d440>,
 <built-in method abs of Tensor object at 0x7f2ef7a3d280>,
 <built-in method max of Tensor object at 0x7f2ef7a3d9c0>,
 <built-in method numel of Tensor object at 0x7f2ef7a3d880>,
 <built-in method size of Tensor object at 0x7f2ef7a3d580>,
 <built-in method item of Tensor object at 0x7f2ef7a3dcc0>,
 <built-in method clone of Tensor object at 0x7f2ef7a3dc80>,
 <built-in method clone of Tensor object at 0x7f2ef7a3db40>,
 <built-in method detach of Tensor object at 0x7f2ef7a3df80>,
 <built-in method reshape of Tensor object at 0x7f2ef7a3dec0>,
 <built-in method size of Tensor object at 0x7f2ef7a3dd00>,
 <built-in method item of Tensor object at 0x7f2ef7a3de00>,
 <built-in method clone of Tensor object at 0x7f2ef7a42e00>,
 <built-in method clone of Tensor object at 0x7f2ef7a42f40>,
 <built-in method detach of Tensor object at 0x7f2ef7a42dc0>,
 <built-in method reshape of Tensor object at 0x7f2ef7a42f80>,
 <built-in method size of Tensor object at 0x7f2ef814ad80>,
 <built-in method size of Tensor object at 0x7f2ef82c63c0>,
 <built-in method numel of Tensor object at 0x7f2ef7a37c80>,
 <built-in method stride of Tensor object at 0x7f2ef82c63c0>,
 <built-in method stride of Tensor object at 0x7f2ef814ad80>,
 <built-in method add of type object at 0x7f3093f05a80>,
 <built-in method allclose of type object at 0x7f3093f05a80>,
 <built-in method gt of type object at 0x7f3093f05a80>,
 <built-in method reshape of type object at 0x7f3093f05a80>,
 <built-in method stack of type object at 0x7f3093f05a80>,
 <built-in method sub of type object at 0x7f3093f05a80>,
 <built-in method true_divide of type object at 0x7f3093f05a80>,
 <built-in method zeros_like of type object at 0x7f3093f05a80>,
 <function grad at 0x7f2ef8fce040>,
 <bound method Tensor.retain_grad of tensor(6., requires_grad=True)>,
 <bound method Tensor.retain_grad of tensor(5., requires_grad=True)>,
 <method '__bool__' of 'torch._C._TensorBase' objects>}
```
</details>

**Comment by ezyang** [comment]
Just a meta comment: it is likely that you should implement `gradcheck` differently if you can't assume that what is passed in is a Tensor; you are more likely to try to reduce the set of function you are actually using in this case.

**Comment by hameerabbasi** [comment]
The PR was reverted in https://github.com/pytorch/pytorch/commit/9f67176b821afe4afa75df22f43f4932f1289ef4, we should potentially re-submit another PR.

**Comment by hameerabbasi** [comment]
It looks like the issue I can't seem to fix here originates in #43451, where the `check_undefined_grad` argument was added to `gradcheck` with a default of `True`. Here's the description of that kwarg from the docstring:

```
check_undefined_grad (bool, options): if True, check if undefined output grads
            are supported and treated as zeros
```

`gradcheck` now uses public API not covered by `__torch_function__` directly, (the exact function is `torch._C._functions.UndefinedGrad`): https://github.com/pytorch/pytorch/blob/9201c37d020007979e144693d86c8e8599e2fd8f/torch/autograd/gradcheck.py#L466

I'm not sure I see a way to do this without extracting that out into another function, which will then be dispatched by `__torch_function__`.

**Comment by albanD** [comment]
Hi,

But that custom Function should accept any Tensor like object I think? It is a no-op in the forward.

**Comment by hameerabbasi** [comment]
It accepts `Tensor`s but not Tensor-likes, apparently.

```python
>>> torch._C._functions.UndefinedGrad()(torch.zeros(5))
tensor([0., 0., 0., 0., 0.])
>>> torch._C._functions.UndefinedGrad()(Wrapper(torch.zeros(5)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument 0 is not a Variable
```

**Comment by albanD** [comment]
I'm not very familiar with the difference between the two but this is defined in [here](https://github.com/pytorch/pytorch/blob/c703602e17da94fa7349cbc3e8841bee77409139/torch/csrc/autograd/functions/basic_ops.h#L51-L66). What can we do to make such c++ implemented Function support Tensor-like objects?

**Comment by hameerabbasi** [comment]
> I'm not very familiar with the difference between the two

For reference, `Tensor` is an object for which the type is a subclass of `Tensor`. A Tensor-like is any object that implements `__torch_function__`, including `Tensor`. I don't think exposing this function to `__torch_function__` is the way to go here, as it's private API.

**Comment by albanD** [comment]
Ho right.
Well this test is quite niche (it checks that empty gradients are properly handled by the backward pass). So it might be fine to enforce that flag to be False if you use a Tensor-like object?

**Comment by hameerabbasi** [comment]
> So it might be fine to enforce that flag to be False if you use a Tensor-like object?

The default is `True`, so it won't work by default. This is the part that worries me.

**Comment by ezyang** [comment]
> What can we do to make such c++ implemented Function support Tensor-like objects?

Alban, I think you are stumbling into a more general problem that I don't (personally) think we should solve any time soon, which is supporting *autograd* with Tensor-like types. This would be pretty difficult to do, since we would need to restructure autograd to hold more things than just Tensors (since a `__torch_function__` object, in general, is NOT a Tensor).

I think undefined grads are a concern that is very specific to C++ autograd functions (can you even do this for Python-level autograd functions? No I think, because we always materialize the zero tensors). So yes, I think you should have the defaulting depend on if an input is tensor-like or not. (True by default, but False for tensor-like objects).

**Comment by albanD** [comment]
>  I think you should have the defaulting depend on if an input is tensor-like or not. (True by default, but False for tensor-like objects)

That sounds good to me.

> No I think, because we always materialize the zero tensors

We do so by default but we added options to get around this now: https://pytorch.org/docs/master/autograd.html#torch.autograd.function._ContextMethodMixin.set_materialize_grads 
Note that these changes were added after the undefined Tensor work and that's why the test does not leverage it.

**Comment by hameerabbasi** [comment]
> I think you should have the defaulting depend on if an input is tensor-like or not. (True by default, but False for tensor-like objects).

Done in #45732.

**Comment by Meghana-Praveen** [comment]
Hello,

My idea of fixing the above issue is that the solution that would accept any tensor-like objects and perform the gradcheck with full support which allows the gradcheck to perform the internal validations like checking for undefined gradient. As I analyzed the variables and functions that will be used by the gradcheck module, the fix will be to implement these attributes for the tensor-like object before the core definitions within the gradcheck module are applied on the object.

**Comment by hameerabbasi** [comment]
@Meghana-Praveen The implementation here should work for `Tensor`-likes, if they implement these functions via `__torch_function__` (and the corresponding operators).

https://github.com/hameerabbasi/pytorch/blob/c93a341a6603b3117c5d43fc97633a2484e78433/test/test_overrides.py#L800-L810

**Comment by Meghana-Praveen** [comment]
@hameerabbasi Instead of asking the user to implement these functions, we can assign them default functions, right? This would enable the user to implement only those functions and attributes which would differ from the defaults. In case the user does not provide few of these functions/attributes, the gradcheck would still utilise the default ones and work as expected.
