### ISSUE TITLE
‘RuntimeError: geqrf: Lapack library not found in compile time’

### ISSUE THREAD

**Issue by Supe2015** [pytorch/pytorch#4294]
In calling torch.nn.init.orthogonal, the error like below has occurred.
File "/usr/local/lib/python2.7/dist-packages/torch/nn/init.py", line 328, in orthogonal
    orthogonal(tensor.data, gain=gain)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/init.py", line 342, in orthogonal
    q, r = torch.qr(flattened)
RuntimeError: geqrf: Lapack library not found in compile time
 at /home/xxx/pytorch/aten/src/TH/generic/THLapack.c:237

**Comment by SsnL** [comment]
Yeah, you would need a lapack library to use those functions, e.g. mkl.

**Comment by soumith** [comment]
@Supe2015 i think you installed from source right? but you dont have a working LAPACK library on your machine i think

**Comment by Mirodil** [comment]
How install `lapack` for example in windows.
