### ISSUE TITLE
Complex CPU torch.acos is wrong on some values

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#42952]
```
t = torch.tensor(0.-1.0000e+20j)
torch.acos(t)
: tensor(nan+infj)
```

Expected (1.5708, 46.7448). 

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @VitalyFedyunin @mruberry @rgommers

**Comment by ngimel** [comment]
going one step forward and trying to verify that cos(acos(a))==a also fails:
```
In [25]: a=torch.tensor(math.pi/2+46.744846j)                                                                                                                                                                       
In [26]: a.cos()                                                                                                                                                                                                    
Out[26]: tensor(-4.3711e+12-1.0000e+20j) # should be -1e20j
In [27]: -(a-math.pi/2).sin()                                                                                                                                                                                       
Out[27]: tensor(-0.-1.0000e+20j) #that's ok
```

**Comment by xuhdev** [comment]
This perhaps also relates to #40590

**Comment by mattip** [comment]
Maybe somewhere this is being converted to `float16`?

**Comment by mattip** [comment]
This eventually reaches generated code `IMPLEMENT_COMPLEX_KERNEL(FLOATING, acos)` in `cpu/UnaryOpsKernel.cpp.AVX2.cpp`. I don't know enough about the code generation to say what the precision is in that generated kernel.

**Comment by mattip** [comment]
`acos` is implemented in terms of `asin`. `torch.asin(torch.tensor(0.-1.0000e+20j)` also gives a nonsensical answer. I think the implementationis [`Vec256<c10::complex<float>> asin()`](https://github.com/pytorch/pytorch/blob/v1.6.0/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L212)

**Comment by mattip** [comment]
The problem is that the vec256 [implementation](https://github.com/pytorch/pytorch/blob/v1.6.0/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L212) for `asin` uses the formula `- i*ln(iz + sqrt(1- z^2))` but does not take overflow of `z^2` into account. Note how the [CPython implementation](https://github.com/python/cpython/blob/v3.8.3/Modules/cmathmodule.c#L225) has a separate path for large values. CPython also has an extensive [test suite](https://github.com/python/cpython/blob/master/Lib/test/test_cmath.py) for complex math, based on ["golden results"](https://github.com/python/cpython/blob/master/Lib/test/cmath_testcases.txt)

**Comment by mattip** [comment]
These kernels were added in #28735, where it mentions [these benchmarks](https://docs.google.com/spreadsheets/d/17pObcrSTpV4BOOX9FYf1vIX3QUlEgQhLvL1IBEyJyzs/edit#gid=0) but does not expand existing tests.

**Comment by anjali411** [comment]
> The problem is that the vec256 [implementation](https://github.com/pytorch/pytorch/blob/v1.6.0/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L212) for `asin` uses the formula `- i*ln(iz + sqrt(1- z^2))` but does not take overflow of `z^2` into account. Note how the [CPython implementation](https://github.com/python/cpython/blob/v3.8.3/Modules/cmathmodule.c#L225) has a separate path for large values. CPython also has an extensive [test suite](https://github.com/python/cpython/blob/master/Lib/test/test_cmath.py) for complex math, based on ["golden results"](https://github.com/python/cpython/blob/master/Lib/test/cmath_testcases.txt)

cc. @mruberry who is working on the test suite and was working on adding these special cases for tests.

**Comment by ezyang** [comment]
@anjali411 Mike is the reporter of this issue ;)

**Comment by mattip** [comment]
Coming back to this. I think the way forward is to
- add tests for complex dtypes and various trigonometric functions
- mark as xfail the tests that fail based on OS/device
- merge the tests to master.
- fix the implementations one at a time in new PRs.

In looking at the operator tests in `test/test_torch.py`, I see 
- `torch_op_tests` that use `_TorchMathTestMeta` and match results to numpy/scipy, and 
- `tensor_op_tests` that use `generate_test_function` to compare variants of functions/methods, cpu/gpu, and possibly `out=` to eachother.

Should some form of complex dtypes be added to both? 
@mruberry does this plan make sense?

**Comment by mruberry** [comment]
TorchMathTestMeta is being refactored into test_unary_ufuncs.py and tensor_op_tests will also be refactored to use the OpInfo test pattern in the near future, so I wouldn't invest there. They're also unlikely to show the issue without more significant changes.

I'm not entirely sure how interesting this behavior is to test for or how fixable these behaviors are. If we did want to test for them I would add a property to OpInfo like, "test_hard_complex_values" and add tests like test_reference_numerics in test_unary_ufuncs.py that query these challenging complex values (like complex numbers with inf, nan, or very large values). Then I would only run the tests on ops that opted into them. 

Even doing that would add a lot of clutter, however, as you'd probably have to skip many variants of test_hard_complex_values to produce a working CI.

**Comment by mattip** [comment]
How would you propose moving forward to a place where complex operations are tested and fixed?

> I'm not entirely sure how interesting this behavior is to test for or how fixable these behaviors are

Or are you suggesting to lower the priority of this issue and #43852 for now?

**Comment by mruberry** [comment]
In test_unary_ufunc.py we are testing complex inputs, just not "hard" ones (large values, infs and nans).

We can pursue having operators opt-in to harder complex tests, like the approach I described above.

**Comment by mattip** [comment]
pr gh-43202 moved the needle on this for linux, but windows still fails the tests there. Apparently it takes a different code path. A more comprehensive test and fix is needed. Unassigning myself, maybe someone else will pick it up.

**Comment by malfet** [comment]
Tentatively grabbing for myself, as I've recently fixed similar issue for complex square root (and complex acos is computed using result of complex square root as intermediary)
