### ISSUE TITLE
Enable torch.distributed typechecks during CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#42967]
`TestTypeHints.test_run_mypy_strict` should pass with `[mypy-torch.distributed.*]` deleted from `mypy.ini`

cc @ezyang @malfet @rgommers

**Comment by malfet** [comment]
@xuzhao9 can you please have a look at this one?

**Comment by xuzhao9** [comment]
cc @seemethere

**Comment by xuzhao9** [comment]
Closed by PR #47534
