### ISSUE TITLE
torch.inverse() will cause RuntimeError: cuda runtime error (9) : invalid configuration argument

### ISSUE THREAD

**Issue by Larry-u** [pytorch/pytorch#42992]
## To Reproduce

1. Enter into `python` IDLE
2. Create a large torch Tensor, with the last two dim be a square matrix
3. Apply torch.inverse() on this tensor, store return value to a tmp variable.
4. Check min of the raw tensor, and get error.

```
>>> import torch
>>> mat = torch.rand(1, 105024, 2, 2, device='cuda')
>>> tmp = torch.inverse(mat)
>>> mat.min()
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp line=383 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (9) : invalid configuration argument at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCGeneral.cpp:383
>>>
```

## Expected behavior
`torch.Tensor.min()` should return the minimum.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.17.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080
GPU 4: GeForce GTX 1080
GPU 5: GeForce GTX 1080
GPU 6: GeForce GTX 1080
GPU 7: GeForce GTX 1080

Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/local/cuda-10.0/lib64/libcudnn.so.7

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] numpydoc==1.1.0
[pip] pytorch-points==0.9
[pip] torch==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               10.0.130                      0
[conda] faiss-gpu                 1.5.2            py37h1a5d453_1    pytorch
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.3                      199
[conda] mkl-service               2.0.2            py37h516909a_0    conda-forge
[conda] mkl_fft                   1.0.12           py37h516909a_1    conda-forge
[conda] mkl_random                1.0.4            py37hf2d7682_0    conda-forge
[conda] numpy                     1.16.4           py37h7e9f1db_0
[conda] numpy-base                1.16.4           py37hde5b4d6_0
[conda] numpydoc                  1.1.0              pyh9f0ad1d_0    conda-forge
[conda] pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
[conda] pytorch-points            0.9                      pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

## Additional context

I use anaconda environment to run the code, and the environment file can be found [here](https://github.com/yifita/DSS/blob/master/requirements.txt)

cc @ngimel

**Comment by RafeyIqbalRahman** [comment]
This seems to be an issue with version 1.1.0. Running the same code on version 1.6.0 returned the minimum: 

tensor(1.1177e-06, device='cuda:0')

Environment: Google Colaboratory
PyTorch version: 1.6.0
CUDA runtime version: 10.1.243

**Comment by gchanan** [comment]
closing because this appears to be fixed.
