### ISSUE TITLE
PyTorch 1.4 with CUDA 10.0 not stable anymore?

### ISSUE THREAD

**Issue by aslu98** [pytorch/pytorch#42999]
I followed the guide https://varhowto.com/install-pytorch-cuda-10-0/ 
The command was working just fine until a couple days ago, but now it returns 
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.4.0+cu100 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.0.post4, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.2.0+cpu, 1.2.0+cu92, 1.3.0, 1.3.0+cpu, 1.3.0+cu92, 1.3.1, 1.3.1+cpu, 1.3.1+cu92, 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.6.0+cu92)
ERROR: No matching distribution found for torch===1.4.0+cu100
```

I manually checked  https://download.pytorch.org/whl/torch_stable.html and there is no cu100/[...]
What should I do? I have CUDA 10.0 I would like to use pytorch...

**Comment by peterjc123** [comment]
You could try `pip3 install torch==1.4.0+cu100 -f https://download.pytorch.org/whl/cu100/torch_stable.html` as a temporary workground. cc @seemethere

**Comment by seemethere** [comment]
This is most likely related to this: https://github.com/pytorch/builder/pull/474

I've re-uploaded the stable html to re-include the cu100 binaries, and submitted a PR to make sure this doesn't happen again https://github.com/pytorch/builder/pull/489
