### ISSUE TITLE
Importing PyTorch won't load CUDA symbols unless forced by TORCH_USE_RTLD_GLOBAL

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#43006]
In my project, [PyTorch-BigGraph](https://github.com/facebookresearch/PyTorch-BigGraph), we use the following code to page-lock some shared memory with CUDA:
```
cudart = ctypes.cdll.LoadLibrary(None)
res = cudart.cudaHostRegister(cptr, csize, cflags)
```

We've got a report (https://github.com/facebookresearch/PyTorch-BigGraph/issues/154) saying that with PyTorch 1.6 this isn't working anymore, and an exception is raised: `undefined symbol: cudaHostRegister`. (Although it's not clear yet if it's a regression of PyTorch 1.6, or earlier, or a peculiarity of the user's system).

Setting the env var `TORCH_USE_RTLD_GLOBAL=1` however fixes the problem.

I tried to look into what is going on and it seems a bit surprising, because the CUDA runtime (`cudart`) is linked to the `torch_global_deps` library:
https://github.com/pytorch/pytorch/blob/d39cb84f1fffbb9a1b909be7b203e673c046cca1/caffe2/CMakeLists.txt#L1147
And in turn that library is loaded with `RTLD_GLOBAL`:
https://github.com/pytorch/pytorch/blob/d39cb84f1fffbb9a1b909be7b203e673c046cca1/torch/__init__.py#L137-L141

`TORCH_USE_RTLD_GLOBAL=1` has the effect of loading the entirety of `torch._C` with that flag, but according to the code above that shouldn't matter as far as CUDA symbols are concerned. Am I missing something?

cc @malfet @ngimel

**Comment by malfet** [comment]
I have several theories of what might have gone wrong here.
Most probable one:  when `torch::cudart` is statically linked with `torch_global_deps`, it is not linked as whole library, and as result,  symbols which are not referenced from torch_global_deps are stripped.

Another hypothesis, is that even if the entire libcudart is linked into torch_global_deps, it can be linked with hidden visibility by default.

Both above-mentioned theories can be easily checked by running `nm libtorch_global_deps.so` and checking if `cudaHostRegister` is among the returned symbols.

Two more somewhat shaky theories: 
- perhaps `_load_global_deps()` is never called
- or if it is `ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)` only imports symbols from the current library and if one want to import symbols from dependent libraries (s)he has to use `sys.setdlopenflags(dl_flags.RTLD_GLOBAL)` trick.

**Comment by lw** [comment]
I ran `nm libtorch_global_deps.so` on torch 1.6.0+cu101 installed from pip in a virtualenv and got very few symbols, none of which CUDA-related: https://gist.github.com/lw/5cd8a1a34b7b48e0640defe8a8f33633

**Comment by lw** [comment]
And the same happened when I built PyTorch from source locally.

Without knowing what I was really doing, I tried two more things.
- I added `PUBLIC` to all the `target_link_libraries(torch_global_deps ...)` commands. It didn't change the output of `nm libtorch_global_deps.so`
- I wrapped these calls with `target_link_libraries(torch_global_deps PUBLIC -Wl,--whole-archive)`. This changed the `nm` output, by adding some math-related symbols, but still no CUDA: https://gist.github.com/lw/49913957b701e8efc9cdab1239783143

**Comment by lw** [comment]
Also, quick update, it seems the issue is a regression in PyTorch 1.6.

**Comment by ezyang** [comment]
As a workaround we expose this symbol ourselves in `torch/csrc/cuda/shared/cudart.cpp` and you can get at it by `torch.cuda.cudart()`. cc @adamlerer

**Comment by lw** [comment]
I can't seem to figure out how `torch.cuda.cudart().cudaHostRegister` works.

```py
In [1]: import torch

In [2]: t = torch.zeros((100,))

In [3]: cudart = torch.cuda.cudart()

In [4]: cudart.cudaHostRegister(t, t.numel() * t.element_size(), 0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d4093e639f76> in <module>
----> 1 cudart.cudaHostRegister(t, t.numel() * t.element_size(), 0)

TypeError: cudaHostRegister(): incompatible function arguments. The following argument types are supported:
    1. (arg0: capsule, arg1: int, arg2: int) -> torch._C._cudart.cudaError

Invoked with: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]), 400, 0

In [5]: cudart.cudaHostRegister(t.data_ptr(), t.numel() * t.element_size(), 0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9eee941a4ae0> in <module>
----> 1 cudart.cudaHostRegister(t.data_ptr(), t.numel() * t.element_size(), 0)

TypeError: cudaHostRegister(): incompatible function arguments. The following argument types are supported:
    1. (arg0: capsule, arg1: int, arg2: int) -> torch._C._cudart.cudaError

Invoked with: 94075172795392, 400, 0

In [6]: import ctypes

In [7]: cudart.cudaHostRegister(ctypes.c_void_p(t.data_ptr()), t.numel() * t.element_size(), 0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-59ca85b86ca2> in <module>
----> 1 cudart.cudaHostRegister(ctypes.c_void_p(t.data_ptr()), t.numel() * t.element_size(), 0)

TypeError: cudaHostRegister(): incompatible function arguments. The following argument types are supported:
    1. (arg0: capsule, arg1: int, arg2: int) -> torch._C._cudart.cudaError

Invoked with: c_void_p(94075172795392), 400, 0
```

Pybind says it wants a `capsule` object as first argument. How do we obtain that from a tensor? Do you have an example invocation of this?

Also, another issue is that `torch.cuda.cudart()` doesn't provide `cudaHostUnregister`.

**Comment by ezyang** [comment]
Something like this:

```
            cptr = ctypes.c_void_p(s.data_ptr())
            csize = ctypes.c_size_t(s.size() * s.element_size())
            cflags = ctypes.c_uint(0)
            # FIXME: broken by D20249187
            # cudart = torch.cuda.cudart()
            cudart = ctypes.cdll.LoadLibrary(None)
            res = cudart.cudaHostRegister(cptr, csize, cflags)
            torch.cuda.check_error(res)
            assert s.is_pinned()
```

As for cudaHostUnregister, we should just add it.

**Comment by lw** [comment]
I can't seem to get that to work. I've tried in the same shell I had open before:
```
In [11]: cudart.cudaHostRegister(ctypes.c_void_p(t.data_ptr()), ctypes.c_size_t(t.numel() * t.element_size()), ctypes.c_uint(0))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-99e4c167e51e> in <module>
----> 1 cudart.cudaHostRegister(ctypes.c_void_p(t.data_ptr()), ctypes.c_size_t(t.numel() * t.element_size()), ctypes.c_uint(0))

TypeError: cudaHostRegister(): incompatible function arguments. The following argument types are supported:
    1. (arg0: capsule, arg1: int, arg2: int) -> torch._C._cudart.cudaError

Invoked with: c_void_p(94075172795392), c_ulong(400), c_uint(0)
```

Are you sure that ctypes wrapper work seamlessly with pybind?

**Comment by ezyang** [comment]
Hmm, I lifted this straight from some internal code, so if it doesn't work that's puzzling to me. Let me dig around a little.

**Comment by lw** [comment]
Oh I think I see what happened, you probably copied that snippet from PBG, which is the project I'm working on and which is exactly where we're seeing the problem I'm reporting in this issue: https://github.com/facebookresearch/PyTorch-BigGraph/blob/929dae01fe1a12d583733326e98139c33fc24690/torchbiggraph/train_gpu.py#L152-L160

As I mentioned, that code used to work before PyTorch 1.6 but is now broken. We can fix that by explicitly loading CUDA (i.e., passing an appropriate non-None value to LoadLibrary) but as PyTorch has already loaded CUDA that shouldn't be necessary. We'd also be happy to use torch.cuda.cudart() again if we can figure out how.

**Comment by ezyang** [comment]
It looks like the only way to create capsules is from C. Oops. Makes me wonder what pybind11 was thinking having capsules be the default binding for `void*` arguments. Patch coming.

**Comment by ezyang** [comment]
@lw Oh, this reminds me that I need to clarify something: this is specifically a problem in our fbcode build, right? In open source we have an extra trick to force CUDA to be loaded with `RTLD_GLOBAL`, so OSS users should not be affected by this.

**Comment by lw** [comment]
> this is specifically a problem in our fbcode build, right? In open source we have an extra trick to force CUDA to be loaded with RTLD_GLOBAL, so OSS users should not be affected by this.

Ehm, no, actually what we're seeing is the opposite: in fbcode we've never had issues loading CUDA by doing `cudart = ctypes.cdll.LoadLibrary(None)`, but some of our OSS users started reporting failures with PyTorch 1.6 (see https://github.com/facebookresearch/PyTorch-BigGraph/issues/154).

**Comment by ezyang** [comment]
Oh OK, then this is probably the thing where we're statically linking against CUDA and so some symbols get entirely removed because they are unused. These functions will help.

**Comment by lw** [comment]
Oh, yeah, that would explain it. Why didn't we realize it earlier?

Your PR fixing cudaHostRegister in cudart() doesn't exactly solve the topic of this issue, but it does fix the problem we were having in the BigGraph project, so that's probably good enough for us.

Thanks again!
