### ISSUE TITLE
drive instead of gdrive

### ISSUE THREAD

**Issue by StevenJokes** [pytorch/pytorch#43001]
## 🐛 Bug

https://pytorch.org/tutorials/beginner/colab.html
![image](https://user-images.githubusercontent.com/25657787/90131662-116b3a80-dd9f-11ea-9998-62b82e0cdc4e.png)
![image](https://user-images.githubusercontent.com/25657787/90131713-2ba51880-dd9f-11ea-839a-bbd4520f4065.png)
![image](https://user-images.githubusercontent.com/25657787/90131742-38297100-dd9f-11ea-830c-d017c68fd3c9.png)

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by RafeyIqbalRahman** [comment]
There is nothing wrong here. In fact, this is the valid syntax. It should be "drive". You can see for yourself here: https://colab.research.google.com/notebooks/snippets/drive.ipynb#scrollTo=u22w3BFiOveA. You may close the issue. :)

**Comment by StevenJokes** [comment]
Thanks for your patience answer. The gdriver is only a name.
![image](https://user-images.githubusercontent.com/25657787/90163644-f0b7da80-ddc8-11ea-9244-f2bad1ea276f.png)
