### ISSUE TITLE
[tutorials] Add details for quantized model save/load

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#43016]
The eager mode dynamic quantization tutorial states that `save_pretrained` can be used to save the quantized model. (https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html#serialize-the-quantized-model)
This is incorrect as `save_pretrained` only saves the model state_dict and the config file, so we lose information about the quantized model (https://huggingface.co/transformers/_modules/transformers/modeling_utils.html#PreTrainedModel.save_pretrained)

Users might incorrectly try to use `load_pretrained` to load the quantized model which wouldn't return quantized model.

The tutorial should be updated to the following
```
input_ids = ids_tensor([8, 128], 2)
token_type_ids = ids_tensor([8, 128], 2)
attention_mask = ids_tensor([8, 128], vocab_size=2)
dummy_input = (input_ids, attention_mask, token_type_ids)

traced_model = torch.jit.trace(quantized_model, dummy_input)
torch.jit.save(traced_model, "bert_traced_eager_quant.pt")
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jaehyeongAN** [comment]
In this tutorials, `ids_tesnor` function is not exist. So following code needs to be added.
```python
import random 
global_rng = random.Random()

def ids_tensor(shape, vocab_size, rng=None, name=None):
    #  Creates a random int32 tensor of the shape within the vocab size
    if rng is None:
        rng = global_rng

    total_dims = 1
    for dim in shape:
        total_dims *= dim

    values = []
    for _ in range(total_dims):
        values.append(rng.randint(0, vocab_size - 1))

    return torch.tensor(data=values, dtype=torch.long, device='cpu').view(shape).contiguous()
```
The code referred to this [link](https://pytorch.org/tutorials/prototype/graph_mode_dynamic_bert_tutorial.html#quantizing-bert-model).

**Comment by LXP-Never** [comment]
How to get the quantized parameters out？

**Comment by kshulav** [comment]
> How to get the quantized parameters out？

model.qunatized_layer.weight()
