### ISSUE TITLE
onnx export got unexpected onnx::ATen[operator="index"] node.

### ISSUE THREAD

**Issue by neverrop** [pytorch/pytorch#43045]
Hi, i'm trying to export maskrcnn in [detectron2](https://github.com/facebookresearch/detectron2), and I got unexpected node `onnx::ATen[operator="index"]` in my converted onnx gragh, which is not supported in onnxruntime. How can I fix this?
code like this:
```
def mask_rcnn_inference(pred_mask_logits, pred_instances):# Select masks corresponding to the predicted classes
    num_masks, num_classes, hmask, wmask = pred_mask_logits.shape
    class_pred = cat([i.pred_classes for i in pred_instances])
    indices = torch.arange(num_masks, device=class_pred.device)
    # mask_probs_pred.shape: (B, 1, Hmask, Wmask)
    mask_probs_pred = pred_mask_logits[indices, class_pred][:, None].sigmoid()
    
    num_boxes_per_image = [len(i) for i in pred_instances]
    mask_probs_pred = mask_probs_pred.split(num_boxes_per_image, dim=0)

    for prob, instances in zip(mask_probs_pred, pred_instances):
        instances.pred_masks = prob  # (1, Hmask, Wmask)
```
line `mask_probs_pred = pred_mask_logits[indices, class_pred][:, None].sigmoid()` converted to  onnx like:
`%1304 : Float(2760:784, 28:28, 28:1) = onnx::ATen[operator="index"](%1293, %1303) # /home/code/centermask2/centermask/modeling/centermask/mask_head.py:198:0`.

I also tried using torch.gather instead, like:
```
indices = class_pred.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).expand(num_masks, 1, hmask, wmask)
mask_probs_pred = pred_mask_logits.gather(1, indices).sigmoid()
```

But I got error like below when converting:
```
    _add_attribute(n, k, v, aten=aten)
  File "/home/zuobinhua/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 655, in _add_attribute
    return getattr(node, kind + "_")(name, value)
TypeError: z_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: at::Tensor) -> torch._C.Node

Invoked with: %2668 : Tensor = onnx::Constant()
, 'value', 1
(Occurred when translating gather).
```

How should I fix this, thanks.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neverrop** [comment]
@BowenBao @izdeby @houseroad any help, please 😂

**Comment by neverrop** [comment]
@spandantiwari fixed after using the latest pytorch version, thanks.

**Comment by spandantiwari** [comment]
Thanks for letting us know @neverrop.
