### ISSUE TITLE
pytorch 1.6.0 does not use V100 GPU ?

### ISSUE THREAD

**Issue by mcrn-rocinante** [pytorch/pytorch#43058]
Hi, I'm trying to run some pytorch code on a distant linux server and it isn't using the  V100 GPU(s) that are available.

-torch.cuda.is_available() returns:
False

 -python -m torch.utils.collect_env returns:

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[conda] numpy                     1.19.1                    <pip>
[conda] torch                     1.6.0                     <pip>

So it know that my two GPUs exist but says CUDA is not available. 
However:
 
nvidia-smi returns:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:37:00.0 Off |                    0 |
| N/A   49C    P0    37W / 250W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:86:00.0 Off |                    0 |
| N/A   51C    P0    40W / 250W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

And by my quick researches this CUDA version and driver should work just fine with pytorch.
 

Anybody knows what could be the reason of that?

Thanks a lot

**Comment by thomkeh** [comment]
```
CUDA used to build PyTorch: 10.2
```

```
NVIDIA-SMI 418.67 Driver Version: 418.67 CUDA Version: 10.1
```

**Comment by izdeby** [comment]
Hi, @mcrn-rocinante, please, use our forums for [questions](https://discuss.pytorch.org/).
