### ISSUE TITLE
Importing lua torch model triggers error in SpatialSubtractiveNormalization layer

### ISSUE THREAD

**Issue by lg-zhang** [pytorch/pytorch#4305]
https://github.com/pytorch/pytorch/blob/41c9959ef74277f28358350037a388b6a70b9392/torch/legacy/nn/SpatialSubtractiveNormalization.py#L85

I fixed this by replace 'is None' with 'hasattr'

see also: https://discuss.pytorch.org/t/convert-import-torch-model-to-pytorch/37/4

cc @albanD @mruberry

**Comment by gchanan** [comment]
legacy nn doesn't exist anymore.
