### ISSUE TITLE
import torch; libcublas.so.9.0 error

### ISSUE THREAD

**Issue by kirk86** [pytorch/pytorch#4309]
Hi guys, I just installed pytorch
`conda install pytorch torchvision cuda90 -c pytorch`

and when I import torch I get the following error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-eb42ca6e4af3> in <module>()
----> 1 import torch

~/miniconda3/lib/python3.6/site-packages/torch/__init__.py in <module>()
     54 except ImportError:
     55     pass
---> 56 from torch._C import *
     57
     58 __all__ += [name for name in dir(_C)

ImportError: /home/user/libcublas.so.9.0: version `libcublas.so.9.0' not found (required by /home/john/miniconda3/lib/python3.6/site-packages/torch/lib/libTHC.so.1)
```

if I check `ldconfig -v | grep libcublas*` I get the following results
```
ldconfig -v | grep libcublas*
libcublas.so.8.0 -> libcublas.so.8.0.88
libcublas.so.9.1 -> libcublas.so.9.1.85
```

Any ideas on how to resolve this?

Plus if you issue `conda update --all` it prompts you to downgrade pytorch to cuda8.0, not ideal I would say.

Thanks!

cc @ezyang @seemethere @malfet

**Comment by bamtercelboo** [comment]
maybe you can reference [#2091](https://github.com/pytorch/pytorch/issues/2091)

**Comment by kirk86** [comment]
@bamtercelboo thanks for the reference bu that's cuda8 and I was trying to use cuda9. As I said if you install with cuda9 through anaconda and then tying to import torch throws the above error. I trying to upgrade conda packages then it downgrades to cuda8. The question is how to use cuda9 + pytorch without errors?

**Comment by ozancaglayan** [comment]
I had the exact same linking problem when trying to compile pytorch 0.3 with CUDA 9.1. I couldn't figure out how it manages to find and link to cublas.8. I gave up and installed the `pip` wheel package which contains CUDA, CuDNN everything inside.
