### ISSUE TITLE
Support numpy dtypes as valid jit constants

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#43094]
## Motivation

The following code is common:
```python
import torch
from torch import nn
import numpy as np

shape = (3, 64, 128, 128)
m = nn.Linear(np.prod(shape), 10)
m = torch.jit.script(m)
```

Currently it throws:
```
TypeError: 
'int64' object for attribute 'in_features' is not a valid constant.
Valid constants are:
1. a nn.ModuleList
2. a value of type {bool, float, int, str, NoneType, device, layout, dtype}
3. a list or tuple of (2)

```

workaround: add an extra `int()`

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi ppwwyyxx,

Thanks for reporting this feature request. We currently don't have plan to support arbitrary inter-operability between torch and numpy. I think casing numpy.int64 to normal python int is a good workaround. Closing this issue for now, let me know if you have more concerns.

**Comment by lix19937** [comment]
https://discuss.pytorch.org/t/torch-jit-script/139546   can fix this error
