### ISSUE TITLE
batch_first param for nn.Transformer module

### ISSUE THREAD

**Issue by macabdul9** [pytorch/pytorch#43112]
## 🚀 Feature
Like recurrent nets (nn.RNN, nn.GRU, nn.LSTM etc) nn.Transformer is missing **batch_first** defualt parameter

## Motivation

torchtext BuckterIteror also has batch_first default parameter hence if nn.Transformer would have batch_first, it will save the dimension permutation 

## Pitch

A conditional statement inside the nn.Transformer's forward method to check whether batch_first is True or not we can permute inside the nn.Transformer module if required   

cc @albanD @mruberry @zhangguanheng66

**Comment by colesbury** [comment]
@albanD can you comment on this proposed change?

**Comment by albanD** [comment]
Hi,

I think it would be ok to add this. But I don't think this will give any benefit beyond slightly simpler user code.
cc @zhangguanheng66 who is the original author of the nn.Transformer Module?

**Comment by zhangguanheng66** [comment]
The MHA module in torchtext ([link](https://github.com/pytorch/text/blob/master/torchtext/nn/modules/multiheadattention.py)) supports batch first. You might give a try there.

**Comment by jbschlosser** [comment]
This was requested in #25100.

**Comment by brando90** [comment]
what is the progress on this?

**Comment by jbschlosser** [comment]
Added in #55285.

**Comment by LeonardoEmili** [comment]
Coming from #25100, any update on this?

**Comment by jbschlosser** [comment]
@LeonardoEmili This was added in #55285 as stated above. It is currently available on the master branch and will be included in PyTorch 1.9.
