### ISSUE TITLE
how to compute the gradient of an image in pytorch

### ISSUE THREAD

**Issue by micklexqg** [pytorch/pytorch#4311]
I need to compute the gradient(dx, dy) of an image, so how to do it in pytroch? 
maybe it is a little stupid, any help appreciated!

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

**Comment by micklexqg** [comment]
sorry for that. but I don't know why the site of the forums can't be available recently.

**Comment by tchaton** [comment]
Interested by that two.
