### ISSUE TITLE
Error with division in a Categorical distribution

### ISSUE THREAD

**Issue by MrNeither** [pytorch/pytorch#43138]
## To Reproduce
Hi. You have added a ban on using division on LongTensor, but in this case normalization in the categorical distribution does not work

```
a = torch.randint(10,size=(5,6))
torch.distributions.categorical.Categorical(probs=torch.ones_like(a))
```

return error
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/MrNeither/PythonVenv/lib/python3.7/site-packages/torch/distributions/categorical.py", line 50, in __init__
    self.probs = probs / probs.sum(-1, keepdim=True)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
```

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by fritzo** [comment]
Hmm, I think we should disallow `LongTensor` inputs to probs.

**Comment by MrNeither** [comment]
@fritzo Why? I used most of the distributions, and after the update, the only problem was with this distribution.

**Comment by MrNeither** [comment]
LongTensor makes it possible to use torch in genetic algorithms for discrete optimization problems. Please do not need to remove the support LongTensor. I also plan to offer a PR with the GentTorch module, which will implement the ability to use torch for discrete optimization tasks.

**Comment by fritzo** [comment]
@MrNeither don't worry, even if we were to disallow `LongTensor` probs, you cold easily cast manually
```diff
- Categorical(probs=my_long_tensor)          # error
+ Categorical(probs=my_long_tensor.float())  # ok
```

My concern is that `Categorical` did not originally allow `LongTensor` because PyTorch did not allow implicit casting. Then I assume support for casting temporarily allowed `LongTensor` inputs to `Categorical`; this was not intended. Now that unsafe division again raises an error. I think that error is real and that we should raise it even earlier in distribution arg validation (namely in [constraints.real.check()](https://github.com/pytorch/pytorch/blob/d5bc2a8058c79d3a2d5fc9c9a186a78de3342d70/torch/distributions/constraints.py#L158)).

@neerajprad @fehiepsi do you have an opinion on whether `constraints.real` should allow integer tensors? How do you do this in JAX? Conversely we do allow float storage for `constraints.nonnegative_integer` as in e.g. Poisson, which makes sense for computational reasons (see discussion in #31779).

**Comment by ngimel** [comment]
cc @mruberry. If indeed it makes sense to have Long probs tensor, the test for this behavior should be added.

**Comment by mruberry** [comment]
And note that division behavior is about to change again to always perform true division, like Python3 does, so this would start "working" again but compute its results differently.

**Comment by neerajprad** [comment]
> @neerajprad @fehiepsi do you have an opinion on whether constraints.real should allow integer tensors? How do you do this in JAX?

I think handling this in `constraints.real`, i.e. disallowing integer arguments sounds reasonable. Right now, we are not doing this though, but we raise an error in `jax.random.bernoulli` when we call `sample` and the `probs` attribute doesn't have a float dtype. I think failing earlier, as you suggest, would be better.

@MrNeither's: IIUC, your concerns were around the additional overhead that casting would take when it is avoidable. Have you done any benchmarking to see what the actual overhead of using `probs.float()` is (from @fritzo's snippet above) for your GA application?

**Comment by MrNeither** [comment]
@neerajprad  I'm not sure if I'm taking the correct speed measurement
```
import torch
import time

population_size = 1000
max_score = 1000
device = torch.device("cuda:0")

start = time.time()
for _ in range(10000):
    a = torch.randint(max_score, size=(100 * population_size,),
                      device=device)  # selection,mutation create x100 instance.
    cat = torch.distributions.categorical.Categorical(probs=a.float())

print(time.time() - start)

start = time.time()
for _ in range(10000):
    a = torch.randint(max_score, size=(100 * population_size,),
                      device=device)  # selection,mutation create x100 instance.
    cat = torch.distributions.categorical.Categorical(probs=a)
print(time.time() - start)
```
output:
```
2.0080626010894775
0.4780709743499756
```
It is worth noting that in this case I use true_divide in the categorical distribution,since without this, the error started to come out, which is in the iisue header

**Comment by fritzo** [comment]
can you add timings for
```
...
a = torch.randint(..., dtype=float)
...
```

**Comment by ngimel** [comment]
Please use `Timer` form `torch.utils._benchmark` , you are not synchronizing cuda calls correctly.

**Comment by neerajprad** [comment]
@MrNeither - Could you use @ngimel's advice to correctly time on the GPU? A slightly modified version of your snippet (which is effectively what is happening in `Categorical.__init__` shows that the timings on the CPU are unaffected:

```python
import torch
import time

population_size = 1000
max_score = 1000

start = time.time()
for _ in range(10000):
    a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
    probs = a.float()
    probs = probs / probs.sum(-1, keepdim=True)

print(time.time() - start)

start = time.time()
for _ in range(10000):
    a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
    probs = a.true_divide(a.sum(-1, keepdim=True))
print(time.time() - start)

----------------------
10.444790840148926
10.281699895858765
```

**Comment by MrNeither** [comment]
I'm sorry, I really didn't compare the speed correctly. The fact is that in my code in the version with the conversion to float, I made a mistake, which caused the speed to fall. after the correction, the speed of both algorithms was approximately the same (it felt like without measurements). The script measurement shows that the speed does not differ much.

```python
import torch
from torch.utils._benchmark import Timer

population_size = 10000
max_score = 10000
device = torch.device("cuda:0")
s1, s2 = [], []

def first():
    for _ in range(1000):
        a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
        probs = a.float()
        probs = probs / probs.sum(-1, keepdim=True)
        s1.append(probs)

def second():
    for _ in range(1000):
        a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
        probs = a.true_divide(a.sum(-1, keepdim=True))
        s2.append(probs)

start = Timer('lambda: first()')
print(torch.__version__)
print(start.timeit())
start = Timer('lambda: second()')
print(start.timeit())
```
output
```
<torch.utils._benchmark.utils.common.Measurement object at 0x7faf5730aa10>
lambda: first()
  47.77 ns
  1 measurement, 1000000 runs , 1 thread
<torch.utils._benchmark.utils.common.Measurement object at 0x7faf645d1910>
lambda: second()
  47.17 ns
  1 measurement, 1000000 runs , 1 thread
```
once again, I apologize for what happened. I wonder why the conversion to float is so fast? This also requires memory allocation, and this should be noticeable on such large arrays.

**Comment by ngimel** [comment]
Don't send `lambda`, it's measuring empty statement then, you slightly modified benchmark provides more reasonable results:
```
import torch
from torch.utils._benchmark import Timer

population_size = 10000
max_score = 10000
device = torch.device("cuda:0")

def first():
    for _ in range(10):
        s1=[]
        a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
        probs = a.float()
        probs = probs / probs.sum(-1, keepdim=True)
        s1.append(probs)

def second():
    for _ in range(10):
        s2=[]
        a = torch.randint(max_score, size=(100 * population_size,))  # selection,mutation create x100 instance.
        probs = a.true_divide(a.sum(-1, keepdim=True))
        s2.append(probs)

start = Timer("first()", globals=globals())
print(start.timeit(10))
start = Timer("second()", globals=globals())
print(start.timeit(10))
```
```
<torch.utils._benchmark.utils.common.Measurement object at 0x7f9363bfded0>
first()
  136.24 ms
  1 measurement, 10 runs , 1 thread
<torch.utils._benchmark.utils.common.Measurement object at 0x7f9363691450>
second()
  134.64 ms
  1 measurement, 10 runs , 1 thread
```

**Comment by MrNeither** [comment]
@fritzo @neerajprad @ngimel @mruberry thank you very much for helping solve this problem.

**Comment by ngimel** [comment]
Before we close this issue, @fritzo, @neerajprad do you think we should disallow integer probs? https://github.com/pytorch/pytorch/pull/43139#issuecomment-675774946 or explicitly cast integer probs to float? I'd vote for disallowing. Can someone submit a PR then?

**Comment by fritzo** [comment]
@ngimel I do agree we should disallow integer probs and more generally integer inputs to many real parameters. I'll try to submit a PR this week.
