### ISSUE TITLE
‘tf.io.gfile.GFile’ cannot load the torchvision pretrained models

### ISSUE THREAD

**Issue by wuyujiji** [pytorch/pytorch#43136]
## 🐛 Bug

python == '3.6.2'
torch == 1.6.0 
torchvision == 0.7.0
**note: torch 1.2.0 and torchvision 0.4.0 also occur this problem** 
tensorflow == 1.15.0

when run:
`from torchvision import models`
`model = models.resnet50(pretrained=True)`

it occurs the following error:

## Traceback
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    model = models.resnet50(pretrained=True)
  File "/usr/local/lib64/python3.6/site-packages/torchvision/models/resnet.py", line 265, in resnet50
    **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torchvision/models/resnet.py", line 227, in _resnet
    progress=progress)
  File "/usr/local/lib64/python3.6/site-packages/torch/hub.py", line 495, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/usr/local/lib64/python3.6/site-packages/torch/serialization.py", line 604, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib64/python3.6/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

## torch.load
the modify code of torch.load interface is:
**with _open_file_like(f, 'rb') as opened_file -> with tf.io.gfile.GFile(f, 'rb') as opened_file**

**I ensure that the downloaded file is complete.**

cc @fmassa @vfdev-5

**Comment by wuyujiji** [comment]
my opinion is that the torchvision pretrained model is saved to the file which is opened by **"python builtin open mode"** , and I load it by **"GFile mode opened"**,  so it occurs this problem. I have three questions:

1. To support my opinoin, I did the experiment: 1) define a resnet50 model: model = models.resnet50(); 2) adopt official torch.save interface to save checkpoint, namely opened the file by **"python builtin open mode"** and then wrote data; 3) load the checkpoint by *"GFile mode opened"**.  To my surprise, it works now and I don't know why?
 
2. Maybe the reason is that the torchvision resnet50 download [https://download.pytorch.org/models/resnet50-19c8e357.pth](url) is trained and saved by older pytorch version , but I am not sure. Could you please give me a help that the torchvision resnet50 download url is updated with newer pytorch version?

3. Besides that, I did another experiment, if I don't modify the load interface, namely loading the checkpoint by **"python builtin open mode"** , it also works now. Therefore, it conflicts my second question (namely the newer pytorch version cannot load the model saved by the old pytorch version).  Sincerely hope you can give answers.

**Comment by vfdev-5** [comment]
@wuyujiji could you please post exact snippet code of what are you doing such that we could run and reproduce the issue. Thanks !

**Comment by wuyujiji** [comment]
@vfdev-5 Thanks for your reply. I have solved this problem, the reason is that the old version checkpoint is deserialized by legacy_load function  in  _legacy_load inferface. For python open mode, the opened file stream has "fileno" function and "f_should_read_directly=True". However, for tf gfile mode, it has not "fileno" and "f_should_read_directly=False", so it invokes the new deserialized methods and raise the error.

**Comment by vfdev-5** [comment]
@wuyujiji thanks for the explanation ! Could you please also explain why you would like to open "https://download.pytorch.org/models/resnet50-19c8e357.pth" with `tf.io.gfile.GFile` tool ?

Anyway, if you think that the problem is solved, feel free to close the issue.

**Comment by wuyujiji** [comment]
@vfdev-5 I use "tf gfile" to open the checkopint because loading data and checkpoint from hdfs in training stage. For common "python open", it doesn't support loading from hdfs .
