### ISSUE TITLE
[jit] TorchScript does not work with Python coverage package

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#43146]
Python coverage package could not include those annotated with `torch.jit.script` into their coverage report. 

A simple example:

```
import torch
import unittest

@torch.jit.script
def test_cov(a):
    for i in range(100):
        a += 10

    return a


class TestCoverage(unittest.TestCase):
    def test(self):
        result = test_conv(10)
        self.assertEqual(result, 1000 + 10)
```

with 
```
pytest test.py -k test
```
gives warning:

```
:0
  :0: PytestCollectionWarning: cannot collect 'test_cov' because it is not a function.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

We should fix our Function binding to allow this to be covered by the coverage package.

Possibly integrate TorchScript interpreter and python interpreter via sys.settrace

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi @janeyx99, is this resolved by your recent code coverage enhancement for TorchScript?

**Comment by janeyx99** [comment]
Oh yes! #56708 and #56829 and #56310

**Comment by gmagogsfm** [comment]
> Oh yes! #56708 and #56829 and #56310

Thanks for confirmation!

**Comment by njzjz** [comment]
Hi, can this package be published to PyPI so downstream packages can also use it to mark TorchScript functions as coverable? Currently, we can only vendor this package in our repo, which is not elegant.
