### ISSUE TITLE
Translating PyTorch tutorial into Traditional Chinese

### ISSUE THREAD

**Issue by YinTaiChen** [pytorch/pytorch#4315]
It's an issue about translating PyTorch tutorial into Traditional Chinese.

Mr. @soumith:

It was a nice talk with you during the lunch today at GAN workshop, Taiwan.

I was very happy to get your permission to translate [PyTorch tutorial](http://pytorch.org/tutorials/).

Here is an [example](https://github.com/YinTaiChen/Understanding-PyTorch-in-Depth/blob/master/What%20is%20Pytorch.ipynb), which is translated from [this page](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html).

I raised this issue because I had contacted @chsasank  before met you personally, and he suggested me to do so. He also mentioned that we need to figure how to host/publish the Chinese translation.

Cheers!

### A list to record the progress:
What is PyTorch? - [translated](https://github.com/YinTaiChen/PyTorch-Tutorial-Translated-into-Traditional-Chinese/blob/master/What%20is%20Pytorch.ipynb)
Autograd: automatic differentiation - [translated](https://github.com/YinTaiChen/PyTorch-Tutorial-Translated-into-Traditional-Chinese/blob/master/autograd_tutorial.ipynb)
Neural Networks - [translated](https://github.com/YinTaiChen/PyTorch-Tutorial-Translated-into-Traditional-Chinese/blob/master/neural_networks_tutorial.ipynb)
Training a classifier - [translated](https://github.com/YinTaiChen/PyTorch-Tutorial-Translated-into-Traditional-Chinese/blob/master/Training%20a%20Classifier.ipynb)
Transfer Learning tutorial - translating

**Comment by sasank** [comment]
Hi there, I think you've tagged the wrong person. Maybe you meant @chsasank?

**Comment by SsnL** [comment]
As a Chinese speaker, I can say that the translation is very accurate. However, some places read a bit awkward to me and feel like the translation is too literal, but that could be that I am not familiar with how certain phrases are used in Taiwan. :)

**Comment by YinTaiChen** [comment]
@sasank Indeed and have edited the tag. Thanks!

**Comment by YinTaiChen** [comment]
@SsnL Thanks for your feedback! I understand how you feel. When I was proofreading the translation, some places read a bit awkward and literal as well. The true reason is (more likely) that as a translator I still have a lot to learn and to improve. So if you (and whoever read the translation) let me know where you found awkward specifically, it will be very helpful. Thanks again!

**Comment by yf225** [comment]
@YinTaiChen Thanks for translating the tutorial into Traditional Chinese! The translation looks great and there are just a few places where we could probably discuss a bit on the word choice. Wondering do you use any instant messaging apps like Messenger? Maybe we can chat on it to have a closer look at script. Thanks!

**Comment by SsnL** [comment]
@yf225 @YinTaiChen I would love to join such a conversion if it happens!

**Comment by YinTaiChen** [comment]
@yf225 Thanks for your reply!. I have sent an email with my FB page link to your gmail account.

**Comment by yf225** [comment]
@SsnL @YinTaiChen Awesome I just sent a FB friend request to y'all :D

**Comment by gchanan** [comment]
closing because we have tutorials in Chinese, see https://pytorch.org/resources/.
