### ISSUE TITLE
Do not call nullptr deleter in at::fromDLPack (dlpack)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#43166]
Currently `src->deleter` is always called, regardless if it's `nullptr` or not. It would be mildly more hassle-free if it checked `if(src->deleter)` prior to calling, just like fromDLPack accommodates not-specified strides.

```cpp
auto deleter = [src](void* self) {
    src->deleter(const_cast<DLManagedTensor*>(src));
  };
``` 
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/DLConvertor.cpp#L215

cc @yf225 @glaringlee

**Comment by ezyang** [comment]
I'm going to send this to a bootcamper

**Comment by ezyang** [comment]
For testing, add your test to `aten/src/ATen/test/dlconvertor_test.cpp`

**Comment by vadimkantorov** [comment]
I passed a DLManagedTensor* with a nullptr deleter and was getting access violations in tensor destructor (in my C# bindings for libtorch: https://github.com/vadimkantorov/dotnetlibtorch/blob/master/dotnetlibtorch.cpp#L28). Unfortunately I don't have a ready test, but probably even doing calloc on DLManagedTensor and passing it to frmDLPack would get Access Violation. It should also behave/error out properly if shape pointer is null or ndim is 0.

**Comment by rgommers** [comment]
There's a detailed comment on gh-43404 that explains a bunch of things. The attempted fix there was closed rather than merged though, so this issue still needs addressing.

**Comment by wjakob** [comment]
Is this a duplicate of #117273? (Which is fixed by now).

**Comment by vadimkantorov** [comment]
@wjakob maybe you're right! judging from https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/DLConvertor.cpp#L299:

**Comment by vadimkantorov** [comment]
I'll then close this :)

**Comment by vadimkantorov** [comment]
If anyone can confirm this, let's close this issue :)

**Comment by vadimkantorov** [comment]
I guess the code is there, so I'll yoloclose this issue for now
