### ISSUE TITLE
[quant] Need to rewrite the serialization versioning for the ConvPackedParams

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#43168]
Currently the [ConvPackedParams serialization](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/fbgemm_utils.cpp#L216-L225) is not very generic, and doesn't support explicit versioning. This needs to change, the problem is that this calls for changes in the TorchBind, and it is not straight-forward without breaking the backwards compatibility.

cc @suo @gmagogsfm @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo, @vkuzo, @jamesr66a

**Comment by eellison** [comment]
Is there a specific ask of the JIT team ?

**Comment by jerryzh168** [comment]
resolved
