### ISSUE TITLE
model trace error

### ISSUE THREAD

**Issue by sainttelant** [pytorch/pytorch#43196]
using torchvision to download squeezeNet model, and intend to trace it into squeezenet_01.pt file, however error occurred as follows

terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:366] . PytorchStreamWriter failed writing file version: file write failed
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f7147f7afd7 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamWriter::valid(char const*, char const*) + 0xa2 (0x7f71852746a2 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: caffe2::serialize::PyTorchStreamWriter::writeRecord(std::string const&, void const*, unsigned long, bool) + 0x191 (0x7f7185275121 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamWriter::writeEndOfFile() + 0xe1 (0x7f7185275ca1 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamWriter::~PyTorchStreamWriter() + 0x115 (0x7f7185276495 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x37f98fd (0x7f71867dd8fd in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::jit::ExportModule(torch::jit::Module const&, std::string const&, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, bool) + 0x300 (0x7f71867dcc50 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x67981f (0x7f7193c3a81f in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x275b20 (0x7f7193836b20 in /home/king/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #10: python3() [0x594b71]
frame #13: python3() [0x507f24]
frame #14: python3() [0x509c50]
frame #15: python3() [0x50a64d]
frame #17: python3() [0x507f24]
frame #19: python3() [0x634dd2]
frame #24: __libc_start_main + 0xe7 (0x7f719734cb97 in /lib/x86_64-linux-gnu/libc.so.6)

Enviroment ubuntu18.04
cuda 10.0.1
pytorch stable 1.6.0 
torchvision  0.7.0

**Comment by hhsecond** [comment]
In my case, my script did not have access to write to the `path` I had given. So changing the path or giving the required permission on the path should fix your issue

**Comment by yarkable** [comment]
@hhsecond Thanks, I saved my model to a path that doesn't exist.
