### ISSUE TITLE
[JIT] Unable to cast Python instance to C++ type (compile in debug mode for details)

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/pytorch#43198]
## 🐛 Bug

I'm trying to convert a model to TorchScript format and seem to get a very generic error that untraceable

## To Reproduce

Since I cannot share the code in details, I can only tell that I used

```python
scripted_model = torch.jit.script(model)
```
with model's class is inheritance from `nn.Module`

And get this traceback:

```bash
Traceback (most recent call last):
  File "convert.py", line 22, in <module>
    scripted_model = torch.jit.script(model)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1261, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 357, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1606, in _construct
    init_fn(script_module)
  File "/Users/linus/anaconda3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 325, in init_fn
    cpp_module.setattr(name, orig_value)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

## Expected behavior

The above stack seem very generic and I cannot see how to start fixing.

I also can't find any resource on how to "compile in debug mode for details".

I expect better error message to know how to solve the problem 

## Environment

```console
PyTorch version: 1.5.1
Is debug build: False
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.17)
CMake version: version 3.15.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.4.3
[pip3] numpy==1.17.2
[pip3] torch==1.3.1
[pip3] torchtext==0.5.0
[pip3] torchvision==0.4.2
[conda] _pytorch_select           0.1                       cpu_0  
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.14           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] msgpack-numpy             0.4.4.3                  pypi_0    pypi
[conda] numpy                     1.17.2           py37h99e6662_0  
[conda] numpy-base                1.17.2           py37h6575580_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] tensorflow                1.15.0          mkl_py37hb249377_0  
[conda] tensorflow-base           1.15.0          mkl_py37h032239d_0  
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi
```

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi lamhoangtung,

I understand that you can't share the exact code, but this really isn't enough information for us to investigate. Could you construct a minimal repro that you can share?

**Comment by lamhoangtung** [comment]
@gmagogsfm Sorry for the late reply. I'm constructing a minimal repo to share. In the meantime, since the exception said that RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details). 

Can you show me how to "compile in debug mode for details" first ? Thanks

**Comment by gmagogsfm** [comment]
Looks like the error is coming from pybind11. I am not entirely sure how to enable debug mode, but I am fairly sure more info can be exposed if change this [line](https://github.com/pybind/pybind11/blob/dabbbf315d61d71e9d0a2cb68e0b9a86e4204459/include/pybind11/cast.h#L1707), more info will be displayed.

Also, if you build Pytorch with "DEBUG=1" environment variable, you can use a c++ debugger to step into problematic code and get more info.

**Comment by iiapache** [comment]
> @gmagogsfm Sorry for the late reply. I'm constructing a minimal repo to share. In the meantime, since the exception said that RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details).
> 
> Can you show me how to "compile in debug mode for details" first ? Thanks

Hi，have you solved this problem?

**Comment by lamhoangtung** [comment]
@iiapache I did, after using DEBUG mode I was able to see more useful stack trace

**Comment by xuesea** [comment]
> @iiapache I did, after using DEBUG mode I was able to see more useful stack trace

Hi, is any more details to share?

**Comment by lamhoangtung** [comment]
Not really @xuesea. If you ever encounter this problem, try to use DEBUG mode for more useful stack trace
