### ISSUE TITLE
test_lstm of quantization.test_backward_compatibility.TestSerialization fails

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#43209]
## 🐛 Bug
When running the tests I'm seeing the following error:

```
Traceback (most recent call last):
  File "/tmp/eb-1hbt9lal/tmpiuhh9sss/lib/python3.7/site-packages/torch/testing/_internal/common_quantized.py", line 124, in test_fn
    qfunction(*args, **kwargs)
  File "/tmp/vsc40023/easybuild_build/PyTorch/1.6.0/fosscuda-2019b-Python-3.7.4/pytorch-1.6.0/test/quantization/test_backward_compatibility.py", line 132, in test_lstm
    self._test_op(mod, input_size=[4, 4, 3], input_quantized=False, generate=False, new_zipfile_serialization=True)
  File "/tmp/vsc40023/easybuild_build/PyTorch/1.6.0/fosscuda-2019b-Python-3.7.4/pytorch-1.6.0/test/quantization/test_backward_compatibility.py", line 68, in _test_op
    self.assertEqual(qmodule(input_tensor), expected, atol=prec)
  File "/tmp/eb-1hbt9lal/tmpiuhh9sss/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1111, in assertEqual
    exact_dtype=exact_dtype, exact_device=exact_device)
  File "/tmp/eb-1hbt9lal/tmpiuhh9sss/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1085, in assertEqual
    self.assertTrue(result, msg=msg)
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=1.3e-06 and atol=1e-05, found 13 element(s) (out of 112) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.9640435565029293 (4.41188467448228e-06 vs. 0.9640479683876038), which occurred at index (3, 0, 6).
```

From what I can tell this might be a serious issue as it basically asserts `load(save(qmodule(input_tensor))) == qmodule(input_tensor)` so either the test is wrong or save and load doesn't work.

## To Reproduce

1. Build PyTorch 1.6
1. Run test

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Python version: 3.7.4

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
@raghuramank100 can you take a look at this?

**Comment by supriyar** [comment]
I'm unable to repro this issue. 

```
python test/test_quantization.py TestSerialization.test_lstm                                                                                                                                                 
Couldn't download test skip set, leaving all tests enabled...
.
----------------------------------------------------------------------
Ran 1 test in 0.072s

OK
```

@Flamefire, can you check if you see the same issue with PT nightly?

**Comment by supriyar** [comment]
Closing as there is no local repro. Please re-open if the issue persists with latest PT version.

**Comment by Flamefire** [comment]
Issue initially encountered by @boegel and @terjekv in https://github.com/easybuilders/easybuild-easyconfigs/pull/11041

Can you double-check that?

**Comment by boegel** [comment]
I'm still seeing this issue with PyTorch 1.7.1, see https://github.com/easybuilders/easybuild-easyconfigs/pull/11636#issuecomment-752064404 for more info.

More specifics:

* PyTorch 1.7.1 installed from source with GCC 9.3.0 + CUDA 10.1.243
* Python 3.7.4
* OS: CentOS 7.9
* Intel Xeon Gold 6242 (`cascadelake`)

**Comment by imaginary-person** [comment]
Hey @boegel & @Flamefire, please confirm if you still experience this issue with local PyTorch builds on Intel Cascade Lake machines.
Thank you!
