### ISSUE TITLE
Link error in windows build

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#43216]
## 🐛 Bug

It is introduced by https://github.com/pytorch/pytorch/pull/42718.

## To Reproduce

1. In windows,  lone latest maser branch, run python tools\build_libtorch, there's error 
Error	LNK1356	cannot find library ` C:/git/pytorch/build/LIB/Debug/caffe2_protos.lib' specified to be whole archived	torch_cpu
2. It  works by removing the quota of the path of lib

In visual studio project settings, it's not necessary to add quotation mark for the directory.

cc @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
So what is the correct way to quote? `"-WHOLEARCHIVE:<FILEPATH>"`?

**Comment by peterjc123** [comment]
cc @malfet

**Comment by peterjc123** [comment]
> In visual studio project settings, it's not necessary to add quota for the directory.

But if you use CMake, this is needed, right?

**Comment by malfet** [comment]
> So what is the correct way to quote? `"-WHOLEARCHIVE:<FILEPATH>"`?
I don't know, but I believe there is a way to specify different rules depending on the generator

**Comment by mszhanyi** [comment]
> > In visual studio project settings, it's not necessary to add quota for the directory.
> 
> But if you use CMake, this is needed, right?

It looks that it isn‘t needed either if if(MSVC) even there's a whitespace in the file path. I'm double checking it.

**Comment by malfet** [comment]
@mszhanyi this is needed if the actual build system is not Visual Studio (i.e. cmake or ninja) (In `cmake` parlance `MSVC` does not mean visual studio, but rather Visual C++ compiler)

**Comment by mszhanyi** [comment]
Raise an issue to visual studio
https://developercommunity.visualstudio.com/content/problem/1156344/wholearchived-value-doesnt-support-quoted-file-pat.html
