### ISSUE TITLE
[jit] add support for sorting tuples

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#43219]
## 🚀 Feature

TorchScript's `sorted` function should work with tuple elements.

## Motivation

Workarounds sorting primitive types are messy and without indices sometimes impossible to accomplish.

## Additional context

* LATTE has run into this issue.
* It should be relatively simple to add the implementation by implementing a more generic comparison function in IValue.

cc @suo @gmagogsfm

**Comment by gmagogsfm** [comment]
Do you mean sorting a list of tuples or sorting elements within a tuple?

**Comment by zdevito** [comment]
Sorting lists of tuple elements. Sorting statically-typed tuples is difficult to define.
