### ISSUE TITLE
I cannot use the pytorch that was built successfully from source: (DLL) initialization routine failed. Error loading caffe2_detectron_ops_gpu.dll, and previous pkgs are lost.

### ISSUE THREAD

**Issue by lorenzznerol** [pytorch/pytorch#43210]
**As I am not allowed to post more than two links on https://discuss.pytorch.org/, I will ask here on github, even though this will be closed. I am aware that this is not the right help / support forum. Please answer at https://discuss.pytorch.org/t/i-cannot-use-the-pytorch-that-was-built-successfully-from-source-dll-initialization-routine-failed-error-loading-caffe2-detectron-ops-gpu-dll/93243. Please do not answer here.**

This is a spin-off from https://github.com/pytorch/pytorch/issues/30910 and https://discuss.pytorch.org/t/pytorch-build-from-source-on-windows/40288.

I have (with the help of https://forums.developer.nvidia.com/t/what-is-the-compute-capability-of-a-geforce-gt-710/146956/6):

> Detected 1 CUDA Capable device(s)
> 
> Device 0: "**GeForce GT 710**"
>   CUDA Driver Version / Runtime Version          11.0 / 11.0
>   CUDA Capability Major/Minor version number:    3.5
>   Total amount of global memory:                 2048 MBytes (2147483648 bytes)
>   ( 1) Multiprocessors, (192) CUDA Cores/MP:     192 CUDA Cores

As this is an old and underpowered graphics card, I need to install pytorch from source by compiling it on my computer with various needed settings and conditions - a not very intituitive thing which took me days. At least, my card supports CUDA cc 3.5 and thus it supports all of the latest CUDA and cuDNN versions, as cc 3.5 is just deprecated, nothing worse.

I followed the steps from README for building pytorch from source at https://github.com/pytorch/pytorch#from-source which also links to the right compiler at https://gist.github.com/ax3l/9489132.

I have succeeded in building PyTorch from source on Windows 10 (as described in pytorch repo readme.md: https://github.com/pytorch/pytorch#from-source), and I’m getting an error when running `import pytorch`:

> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

And all pkgs that are not dependencies of pytorch are lost. For example, basic packages like pandas is not available anymore, numpy and mkl are available which are installed dependencies of pytorch.

\\########################################################
\\## Now the steps to reproduce this error:
\\########################################################

Main summary from:
https://discuss.pytorch.org/t/pytorch-build-from-source-on-windows/40288
https://www.youtube.com/watch?v=sGWLjbn5cgs

Interesting remarks from:
https://github.com/pytorch/pytorch/issues/30910
https://github.com/exercism/cpp/issues/250

Steps:

1. https://cmake.org/download/
2. https://git-scm.com/download/win
3. As the compiler, I chose MSVC 2019 since that can handle CUDA cc 3.5 according to https://gist.github.com/ax3l/9489132.

![image](https://user-images.githubusercontent.com/52793248/90531212-113fb600-e176-11ea-95d0-6939cf598add.png)

MS Visual Studio 2019 16.7.1
-->  Indivudual components: 
- most recent MSVC v142 - VS 2019 C++-x64/x86-Buildtools (v14.27) (the most recent x64 version at that time)
- most recent Windows 10 SDK (10.0.19041.0) (the most recent x64 version at that time)
4. (myenv) C:\Users\Admin\Downloads\Pytorch>git clone https://github.com/pytorch/pytorch
5. (myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>git submodule update --init --recursive
6. (myenv) C:\Users\Admin\Downloads\Pytorch>git clone https://github.com/peterjc123/pytorch-scripts
7. Copy all files in C:\Users\Admin\Downloads\Pytorch\pytorch-scripts that are not: "\internal", "\.github", README.md, .gitignore to C:\Users\Admin\Downloads\Pytorch\pytorch; this is according to the youtube guide, and I doubt that it is necessary if I install the latest cuda version anyway. Still, it cannot really harm here, can it?
8. conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests
9. set CMAKE_GENERATOR=Visual Studio 16 2019
10. // `using --cmake` according to https://github.com/pytorch/pytorch/issues/30910
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
`CMake Error: Error: generator : Ninja
Does not match the generator used previously: Visual Studio 16 2019
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.`

11. At this point, I did not know where to remove the CMakeCache.txt. I still leave it here as a potential point. 
12. if this has not worked (according to https://github.com/pytorch/pytorch/issues/30910): set USE_NINJA=OFF
13. (myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
14. if this has not worked (according to https://github.com/pytorch/pytorch/issues/30910):
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>set DMSVC_Z7_OVERRIDE=OFF
15. (myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
16. if this has not worked (according to output):
// Needed according to https://discuss.pytorch.org/t/pytorch-build-from-source-on-windows/40288
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>set "CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"
17. // Mind that running this takes about 3 hours.
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
getting error: 
```
  Building Custom Rule C:/Users/Admin/Downloads/Pytorch/pytorch/caffe2/CMakeLists.txt
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    build_caffe2(version=version,
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\setup_helpers\cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\Admin\anaconda3\envs\ml\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/p:CL_MPCount=4']' returned non-zero exit status 1.`
```

18. // Deleted folder C:\Users\Admin\Downloads\Pytorch\pytorch\caffe2_builders
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
getting error:
```
LINK : fatal error LNK1356: Die zur vollständigen Archivierung angegebene Bibliothek
 "\C:/Users/Admin/Downloads/Pytorch/pytorch/build/lib/Release/caffe2_protos.lib\.lib" wurde nicht gefunden. [C:\Users\Admi
n\Downloads\Pytorch\pytorch\build\caffe2\torch_cpu.vcxproj]
  Building Custom Rule C:/Users/Admin/Downloads/Pytorch/pytorch/caffe2/CMakeLists.txt
  Building Custom Rule C:/Users/Admin/Downloads/Pytorch/pytorch/caffe2/CMakeLists.txt
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    build_caffe2(version=version,
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\setup_helpers\cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "C:\Users\Admin\Downloads\Pytorch\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\Admin\anaconda3\envs\ml\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/p:CL_MPCount=4']' returned non-zero exit status 1.
```

19. // Added folder from C:\Users\Admin\Downloads\Pytorch\pytorch-scripts again
// Mind that running this takes about half a day.
(myenv) C:\Users\Admin\Downloads\Pytorch\pytorch>python setup.py install --cmake
This runs through! My guess why it works is that removing the caffe_builders folder and add it again has somehow cleared the CMakeCache.txt that I have forgotten to try at point 11.

20. But then, at `import pytorch`:

Spyder error message:

```
Traceback (most recent call last):

  File "<ipython-input-1-8dcfa38a0e4c>", line 4, in <module>
    import torch

  File "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err

OSError: [WinError 1114] Eine DLL-Initialisierungsroutine ist fehlgeschlagen. Error loading "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

PyCharm error message:

```
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-54793187acc7>", line 4, in <module>
    import torch
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 1114] Eine DLL-Initialisierungsroutine ist fehlgeschlagen. Error loading "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

21. https://github.com/tensorflow/tensorflow/issues/31172 --> https://www.tensorflow.org/install/gpu#windows_setup (worked only by doing this manually):
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\lib64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include;%PATH%
After copying the latest cuDNN zip-extract to that directory and then set the path:
SET PATH=C:\Program Files\NVIDIA cuDNN\cuda;%PATH

22. At `import pytorch`, same error as above:
```
OSError: [WinError 1114] Eine DLL-Initialisierungsroutine ist fehlgeschlagen. Error loading "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```
In English:
```
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Admin\anaconda3\envs\ml\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```
(like found at https://github.com/tensorflow/tensorflow/issues/31172)

23. My previous packages are mainly lost. Only probably the dependencies in point 8 are available, and for example matplotlib. 
Packages that were gone, among others: pandas, pymongo, scikit-learn, seaborn, scipy, statsmodels. Is ist normal that packages get lost when PyTorch is installed from source?

24. And another thing now occuring, which is rather a new issue, just worth mentioning: dtaidistance package causes issues as well:

`import dtaidistance`

> Exception: The compiled dtaidistance C library is not available.
> See the documentation for alternative installation options.

25. Now what is next?

**PLEASE ANSWER AT https://discuss.pytorch.org/t/i-cannot-use-the-pytorch-that-was-built-successfully-from-source-dll-initialization-routine-failed-error-loading-caffe2-detectron-ops-gpu-dll/93243 since this github project forum is not for help or support, but https://discuss.pytorch.org is.**

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mszhanyi** [comment]
close it since the main thread is in the https://discuss.pytorch.org/t/i-cannot-use-the-pytorch-that-was-built-successfully-from-source-dll-initialization-routine-failed-error-loading-caffe2-detectron-ops-gpu-dll/93243.
