### ISSUE TITLE
Autograd profiler support for torch.distributed

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#43231]
## 🚀 Feature

The [autograd profiler](https://pytorch.org/docs/stable/autograd.html#profiler) does not cover `torch.distributed` ops like allreduce, allgather etc. Adding support for this would be invaluable for debugging performance issues.

We should cover all the collective and point to point operations listed here: https://pytorch.org/docs/stable/distributed.html.

A nice extension for the autograd profiler in the distributed setting would be to have an API like `torch.distributed.combine_profiles`, where a single rank (ex: rank 0) can pull the autograd profiles for all other ranks and provide users with a single chrome trace view which displays the trace across all nodes.

## Motivation

The [autograd profiler](https://pytorch.org/docs/stable/autograd.html#profiler) has been an invaluable tool in PyTorch to debug performance issues and extending this to `torch.distributed` would be beneficial to users. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment]
Some of this work is now complete, although we should still look into the `combine_profiles` idea and have a better story around trace collection for distributed profiling.

**Comment by rohan-varma** [comment]
This feature has now been landed and enabled for all in-tree backends in 1.9 release.
