### ISSUE TITLE
【ERROR】connection reset by peer, when using infiniband

### ISSUE THREAD

**Issue by imyzx2017** [pytorch/pytorch#43258]
## ❓ Questions and Help
ENV: 
ubuntu16.04.6 LTS  +
python=3.6.7  +
torch=1.0.0.a  +
nccl=2.3.7  +
cuda=10.0  +
Nvidia driver version=410.68  +
OPENMPI_VERSION=3.1.2  +
MOFED_VERSION=4.0-1.0.1+infiniband

an error occurs when I do distributed training in contrainer(two node), as list below:
######################################################
python -m torch.distributed.launch --master_addr 192.168.206.131 --master_port 7777 --node_rank 0 --nproc_per_node 4 --nnode 2 tools/train_net.py --fp16 --min_bbox_map 0.377 --min_mask_map 0.339 --config-file configs/e2e_mask_rcnn_R_50_FPN_1x.yaml SOLVER.BASE_LR 0.04 SOLVER.MAX_ITER 80000 SOLVER.WARMUP_FACTOR 0.000064 SOLVER.WARMUP_ITERS 625 SOLVER.WARMUP_METHOD mlperf_linear SOLVER.STEPS '(36000, 48000)' DATALOADER.IMAGES_PER_BATCH_TRAIN 4 MODEL.RPN.FPN_POST_NMS_TOP_N_TRAIN 4000

dgx1-1:13617:13617 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
dgx1-1:13617:13617 [0] NCCL INFO NET : Using interface ib0:172.168.206.131<0>
dgx1-1:13617:13617 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [0] mlx5_64:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [1] mlx5_128:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [2] mlx5_36:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [3] mlx5_74:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [4] mlx5_46:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [5] mlx5_18:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [6] mlx5_84:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [7] mlx5_6:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [8] mlx5_56:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [9] mlx5_28:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [10] mlx5_94:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [11] mlx5_66:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [12] mlx5_38:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [13] mlx5_101:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [14] mlx5_76:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [15] mlx5_48:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [16] mlx5_111:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [17] mlx5_86:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [18] mlx5_8:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [19] mlx5_58:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [20] mlx5_121:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [21] mlx5_96:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [22] mlx5_68:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [23] mlx5_103:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [24] mlx5_11:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [25] mlx5_78:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [26] mlx5_113:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [27] mlx5_21:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [28] mlx5_88:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [29] mlx5_123:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [30] mlx5_31:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [31] mlx5_98:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [32] mlx5_41:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [33] mlx5_105:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [34] mlx5_13:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [35] mlx5_1:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [36] mlx5_51:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [37] mlx5_115:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [38] mlx5_23:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [39] mlx5_61:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [40] mlx5_125:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [41] mlx5_33:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [42] mlx5_71:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [43] mlx5_43:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [44] mlx5_107:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [45] mlx5_15:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [46] mlx5_81:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [47] mlx5_3:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [48] mlx5_53:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [49] mlx5_117:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [50] mlx5_25:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [51] mlx5_91:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [52] mlx5_63:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [53] mlx5_127:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [54] mlx5_35:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [55] mlx5_73:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [56] mlx5_45:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [57] mlx5_109:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [58] mlx5_17:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [59] mlx5_83:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [60] mlx5_5:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [61] mlx5_55:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [62] mlx5_119:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [63] mlx5_27:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [64] mlx5_93:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [65] mlx5_65:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [66] mlx5_37:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [67] mlx5_100:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [68] mlx5_75:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [69] mlx5_47:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [70] mlx5_110:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [71] mlx5_19:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [72] mlx5_85:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [73] mlx5_7:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [74] mlx5_57:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [75] mlx5_120:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [76] mlx5_29:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [77] mlx5_95:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [78] mlx5_67:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [79] mlx5_39:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [80] mlx5_102:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [81] mlx5_10:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [82] mlx5_77:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [83] mlx5_49:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [84] mlx5_112:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [85] mlx5_20:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [86] mlx5_87:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [87] mlx5_9:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [88] mlx5_59:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [89] mlx5_122:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [90] mlx5_30:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [91] mlx5_97:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [92] mlx5_69:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [93] mlx5_40:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [94] mlx5_104:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [95] mlx5_12:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [96] mlx5_79:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [97] mlx5_0:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [98] mlx5_50:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [99] mlx5_114:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [100] mlx5_22:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [101] mlx5_89:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [102] mlx5_60:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [103] mlx5_124:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [104] mlx5_32:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [105] mlx5_99:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [106] mlx5_70:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [107] mlx5_42:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [108] mlx5_106:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [109] mlx5_14:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [110] mlx5_80:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [111] mlx5_2:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [112] mlx5_52:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [113] mlx5_116:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [114] mlx5_24:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [115] mlx5_90:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [116] mlx5_62:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [117] mlx5_126:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [118] mlx5_34:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [119] mlx5_72:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [120] mlx5_44:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [121] mlx5_108:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [122] mlx5_16:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [123] mlx5_82:1/IB 
dgx1-1:13617:13617 [0] NCCL INFO NET/IB: [124] mlx5_4:1/IB 
Traceback (most recent call last):
  File "tools/train_net.py", line 330, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 330, in <module>
Traceback (most recent call last):
  File "tools/train_net.py", line 330, in <module>
    main()
  File "tools/train_net.py", line 245, in main
    torch.distributed.broadcast(torch.tensor([1], device="cuda"), 0)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 646, in broadcast
    main()
  File "tools/train_net.py", line 245, in main
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Connection reset by peer
    torch.distributed.broadcast(torch.tensor([1], device="cuda"), 0)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 646, in broadcast
    main()
  File "tools/train_net.py", line 245, in main
    torch.distributed.broadcast(torch.tensor([1], device="cuda"), 0)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 646, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Connection reset by peer
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: Connection reset by peer

####################################

This error won't occur when I set NCCL_IB_DISABLE=1;
How can I solve this problem with IB enabled? Thanks a lot!!!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rakshithvasudev** [comment]
Hello @imyzx2017  Are you sure every GPU is getting it's own job? This might be worth a try: https://github.com/pytorch/fairseq/issues/277#issuecomment-421186960

**Comment by mrshenli** [comment]
> torch=1.0.0.a +

Could you please try if this error persist with PyTorch nightly release?

**Comment by imyzx2017** [comment]
I found out the solution!!

Because our platform used IPonIB with Infiniband devices, then we need to set RDMA port by $ export NCCL_IB_HCA=mlx5_0, otherwise som DOWN state IB port will be used by NCCL...
