### ISSUE TITLE
Neon intrinsic types issue

### ISSUE THREAD

**Issue by mabuyev** [pytorch/pytorch#43265]
## 🐛 Bug

GCC errors on aarch64 while building Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o

## To Reproduce

1. cmake options: -DUSE_CUDA=OFF -DBUILD_CAFFE2_OPS=OFF -DBUILD_SHARED_LIBS=OFF -DUSE_DISTRIBUTED=OFF -DUSE_QNNPACK=OFF -DUSE_XNNPACK=OFF
2. GCC7, 8 or 9

GCC7 error message:
`In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10:0,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:262:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) const {
   ^~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:267:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) {
   ^~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In static member function ‘static at::vec256::{anonymous}::Vec256<float> at::vec256::{anonymous}::Vec256<float>::loadu(const void*, int64_t)’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:213:14: error: ‘vld1q_f32_x2’ was not declared in this scope
       return vld1q_f32_x2(reinterpret_cast<const float*>(ptr));
              ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:213:14: note: suggested alternative: ‘vld1q_f32’
       return vld1q_f32_x2(reinterpret_cast<const float*>(ptr));
              ^~~~~~~~~~~~
              vld1q_f32
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:230:14: error: ‘vld1q_f32_x2’ was not declared in this scope
       return vld1q_f32_x2(reinterpret_cast<const float*>(tmp_values));
              ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:230:14: note: suggested alternative: ‘vld1q_f32’
       return vld1q_f32_x2(reinterpret_cast<const float*>(tmp_values));
              ^~~~~~~~~~~~
              vld1q_f32
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In member function ‘void at::vec256::{anonymous}::Vec256<float>::store(void*, int64_t) const’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: note: suggested alternative: ‘vst1q_f32’
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
       vst1q_f32
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: note: suggested alternative: ‘vst1q_f32’
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
       vst1q_f32
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator&(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:577:42: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_low())));
                                          ^
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:580:43: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_high())));
                                           ^
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator|(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:588:42: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_low())));
                                          ^
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:591:43: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_high())));
                                           ^
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator^(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:599:42: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_low())));
                                          ^
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:602:43: error: cannot convert ‘uint32x4_t {aka __vector(4) unsigned int}’ to ‘float32x4_t {aka __vector(4) float}’ for argument ‘1’ to ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
       vreinterpretq_u32_f32(b.get_high())));
                                           ^
[ 58%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Integration.cpp.o
caffe2/CMakeFiles/torch_cpu.dir/build.make:2845: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:3407: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`
GCC8-9 error message:
`In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:262:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) const {
   ^~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:267:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) {
   ^~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In member function ‘void at::vec256::{anonymous}::Vec256<float>::store(void*, int64_t) const’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: note: suggested alternative: ‘vld1q_f32_x2’
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
       vld1q_f32_x2
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: note: suggested alternative: ‘vld1q_f32_x2’
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
       vld1q_f32_x2
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator&(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:575:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r0 = vreinterpretq_u32_f32(vandq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_low()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
       vreinterpretq_u32_f32(b.get_low())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:578:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r1 = vreinterpretq_u32_f32(vandq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_high()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
       vreinterpretq_u32_f32(b.get_high())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator|(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:586:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r0 = vreinterpretq_u32_f32(vorrq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_low()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
       vreinterpretq_u32_f32(b.get_low())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:589:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r1 = vreinterpretq_u32_f32(vorrq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_high()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
       vreinterpretq_u32_f32(b.get_high())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In function ‘at::vec256::{anonymous}::Vec256<T> at::vec256::{anonymous}::operator^(const at::vec256::{anonymous}::Vec256<T>&, const at::vec256::{anonymous}::Vec256<T>&) [with T = float; typename std::enable_if<(! std::is_base_of<at::vec256::{anonymous}::Vec256i, at::vec256::{anonymous}::Vec256<T> >::value), int>::type <anonymous> = 0]’:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:597:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r0 = vreinterpretq_u32_f32(veorq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_low()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
       vreinterpretq_u32_f32(b.get_low())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:600:51: error: cannot convert ‘uint32x4_t’ {aka ‘__vector(4) unsigned int’} to ‘float32x4_t’ {aka ‘__vector(4) float’}
   float32x4_t r1 = vreinterpretq_u32_f32(veorq_u32(
                                          ~~~~~~~~~^
       vreinterpretq_u32_f32(a.get_high()),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
       vreinterpretq_u32_f32(b.get_high())));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         
In file included from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/intrinsics.h:22,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/vec256.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vec256/functional.h:6,
                 from /home/dev/dev/libtorch/aten/src/ATen/cpu/vml.h:5,
                 from /home/dev/dev/libtorch/aten/src/ATen/native/GridSampler.cpp:7:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:6004:36: note:   initializing argument 1 of ‘uint32x4_t vreinterpretq_u32_f32(float32x4_t)’
 vreinterpretq_u32_f32 (float32x4_t __a)
                        ~~~~~~~~~~~~^~~
[ 41%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Integration.cpp.o
caffe2/CMakeFiles/torch_cpu.dir/build.make:2845: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/GridSampler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5743: recipe for target 'caffe2/CMakeFiles/torch_cpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0

Versions of relevant libraries:
[pip3] numpy==1.13.3
[conda] Could not collect


cc @malfet

**Comment by AWSNB** [comment]
@mabuyev - on gcc7, seems like the patch to add  ..._x2 intrinsics was not backported

on ubuntu 20.xx,  with gcc9, the intrinsics are supported but the neon code in pytorch has conversion bugs

see patch i just submitted:  https://github.com/pytorch/pytorch/compare/master...AWSNB:patch-1

**Comment by AWSNB** [comment]
@kimishpatel   - thank you for submitting the vec256 neon code.   see the note above regarding gcc7 not supporting the x2 intrinsics.     older ubuntu and redhat would still have gccy

**Comment by kimishpatel** [comment]
@AWSNB, I will submit a PR to ifdef gcc7 and take fallback path instead.

**Comment by AWSNB** [comment]
> @AWSNB, I will submit a PR to ifdef gcc7 and take fallback path instead.

we expect some distributions to actually patch gcc7 with this

let us get back to you on finer grain fallback criteria

**Comment by AGSaidi** [comment]
Maybe add a test for the NEON ACLE in Cmake being present and thus when we get it back ported it will just work and it means you don't have to try and figure out exact versions e.g.:

```
check_c_source_compiles("
#include <arm_neon.h>
int main() {
	int b;
	float a[] = {1.0, 1.0};
	vld1q_f32_x2(a);
	return 0;
}
" MISSING_ARM_VLD1)
```

**Comment by AWSNB** [comment]
@kimishpatel see note above from @AGSaidi , that's a more flexible approach than checking for gcc7.  there are active work to backport the missing instrinsics to gcc7

**Comment by kimishpatel** [comment]
Thanks @AWSNB and @AGSaidi. Yes that approach makes sense.

**Comment by AWSNB** [comment]
@kimishpatel a patch from sebpop to address the [missing intrinsics in GCC7 has been posted by @sebpop](https://github.com/pytorch/pytorch/pull/43683)

**Comment by kimishpatel** [comment]
> @kimishpatel a patch from sebpop to address the [missing intrinsics in GCC7 has been posted by @sebpop](https://github.com/pytorch/pytorch/pull/43683)

Thats awesome.

**Comment by hrw** [comment]
Was something missed or am I doing something wrong?

```
git checkout master
git clean -dfx
time USE_CUDA=0 BUILD_CAFFE2_OPS=0 USE_DISTRIBUTED=0 USE_QNNPACK=0 USE_XNNPACK=0 python3 setup.py install
```

```
In file included from /root/pytorch/aten/src/ATen/cpu/vec256/vec256.h:10,
                 from /root/pytorch/aten/src/ATen/native/cpu/Loops.h:35,
                 from /root/pytorch/aten/src/ATen/native/Normalization.cpp:10:
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:262:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) const {
   ^~~~~
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:267:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const float operator[](int idx) {
   ^~~~~
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h: In member function ‘void at::vec256::{anonymous}::Vec256<float>::store(void*, int64_t) const’:
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:235:7: note: suggested alternative: ‘vld1q_f32_x2’
       vst1q_f32_x2(reinterpret_cast<float*>(ptr), values);
       ^~~~~~~~~~~~
       vld1q_f32_x2
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: error: ‘vst1q_f32_x2’ was not declared in this scope
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
/root/pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h:242:7: note: suggested alternative: ‘vld1q_f32_x2’
       vst1q_f32_x2(reinterpret_cast<float*>(tmp_values), values);
       ^~~~~~~~~~~~
       vld1q_f32_x2
gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/build.make:2014: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/Normalization.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6058: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
gmake: *** [Makefile:141: all] Error 2
```

```
[root@35c5b7181dea pytorch]# gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@35c5b7181dea pytorch]# git log -1
commit f8f35fddd4b2bd788953d6d6ccfadf690b73a3e8 (HEAD -> master, origin/master, origin/HEAD)
Author: Xiao Wang <24860335+xwang233@users.noreply.github.com>
Date:   Fri Sep 4 03:32:09 2020 -0700

    Optimize code path for adaptive_avg_pool2d when output size is (1, 1) (#43986)

```

**Comment by AWSNB** [comment]
@hrw  the ...x2 intrinsics are missing from the gcc lib in the RH/GCC version u using

is @sebpop patch (https://github.com/sebpop/pytorch/commit/5b465263c0f3672ebcaa7d87a3177353ed2f5c8c) included in the source code you compiling from ?

**Comment by hrw** [comment]
Yes, his patch is in. I have hacky fix which need to clean up before submitting. Will open new issue.

**Comment by kimishpatel** [comment]
I thought that @sebpop's patch should have resolved this.

**Comment by AWSNB** [comment]
Could be new issue in RH8.c/gcc8

We tested spop fix on RH7.x/gcc7

Sent from my iPhone

On Sep 4, 2020, at 8:04 AM, Kimish Patel <notifications@github.com> wrote:

﻿

I thought that @sebpop<https://github.com/sebpop>'s patch should have resolved this.

**Comment by hrw** [comment]
> I thought that @sebpop's patch should have resolved this.

Looks like his patch checks for intrinsic which is covered.
