### ISSUE TITLE
[ONNX] export torch.full_like is a constant initializer for ScatterElements

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#43283]
## 🐛 Bug

```python
target_width = torch.full_like(input_width, target_size)
```

This line used to create a in 1.4 a "ConstantOfShape"

![image](https://user-images.githubusercontent.com/873905/90680546-d9d51600-e216-11ea-80ba-326f8f2e68bf.png)

In 1.6 however this is a constant (initialzier) which is incorrect.

![image](https://user-images.githubusercontent.com/873905/90680609-f3765d80-e216-11ea-9c80-a44d9cec6b8a.png)

ScatterElements seems like it only traces the input as a constant

## To Reproduce

1.
1.
1.

## Expected behavior

Work with dynamic sized tensors, instead of converting them to constants.

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.87.01
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] pytorch                   1.6.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py36_cu101    pytorch

## Additional context

Updating to 1.6 model is exported incorrectly

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by dashesy** [comment]
The workaround for 1.6 is to use `torch.zeros` like this:

```python
    shape = list(input_width.shape)
    if not isinstance(shape[0], torch.Tensor):
        shape = [torch.tensor(s).to(input_width.device) for s in shape]

    target_width = torch.zeros(shape, device=input_width.device) + target_size
```

So, `torch.zeros` correctly exports but not `torch.full`

**Comment by BowenBao** [comment]
hi @dashesy, could you give a simple complete repro including the two nodes `full_like` and `scatter`? I tried a small example on my side and cannot repro the same result.

**Comment by dashesy** [comment]
The actual issue comes from a fairly complicated model export. I will try to repro with a small code and update here, otherwise will connect with you for the actual model export in production.

**Comment by dashesy** [comment]
In the process of creating a repro, I figured out that it is an ORT optimizer issue. Created the issue there, closing this one.

**Comment by dashesy** [comment]
@BowenBao looks like this is exporter issue after all. Created new issue.
