### ISSUE TITLE
Refactor duplicated code

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#43306]
Move https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/conv.py#L239-L250 into a function in paren module to reduce code duplication.

There is also a bug because of code duplication https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/conv.py#L241, but I'll fix it soon in my PR.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by noelmat** [comment]
Hi @jerryzh168 
could you assign this to me?

**Comment by jerryzh168** [comment]
Yeah you need to create a new branch and then create a new pull request, could you post your pull request?

**Comment by jerryzh168** [comment]
we want to extract https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/conv.py#L239-L250 as a function in _ConvNd and use it in child classes

**Comment by noelmat** [comment]
I have posted the pull request #43525

**Comment by noelmat** [comment]
I have pushed the changes.

**Comment by noelmat** [comment]
Thank you @jerryzh168 for guiding me through. :)

**Comment by jerryzh168** [comment]
@noelmat Thanks!
