### ISSUE TITLE
torch-1.6.0 contains AVX instruction in the default codepath

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#43300]
Via https://discuss.pytorch.org/t/crashes-when-using-torch-max-in-torch-1-6-0/93376/8
Steps to reproduce:
1. wget https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
2. Unzip it
3. `ATEN_CPU_CAPABILITY=default  gdb python3.7 -ex "set args -c 'import torch;print(torch.rand(1,2,5).max(1))'" -ex "b _ZN2at20TensorIteratorConfig20declare_static_shapeEN3c108ArrayRefIlEEl" -ex "run" -ex "disassemble`
`$rip+85` would contain an AVX instruction:
```
(gdb) x/2i $rip+85
   0x7fffda033709 <_ZN2at20TensorIteratorConfig20declare_static_shapeEN3c108ArrayRefIlEEl+89>:	vmovddup -0x1f8(%rbp),%xmm0
   0x7fffda033711 <_ZN2at20TensorIteratorConfig20declare_static_shapeEN3c108ArrayRefIlEEl+97>:	vmovaps %xmm0,-0x1d0(%rbp)
```

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by ezyang** [comment]
Probably can fix this by removing all of the inline methods from TensorIterator. Not sure how to fix this at a deeper level though.

**Comment by malfet** [comment]
The reason for the failure, is that `at::TensorIteratorConfig::declare_static_shape(c10::ArrayRef<long>, long)` is implemented in the header, see below:
https://github.com/pytorch/pytorch/blob/397325a10975e17e244381752e892f5af5b2859b/aten/src/ATen/native/TensorIterator.h#L526-L533
This header is included from the cpu/native kernels, which are compiled multiple times with different optimization flags. 
To avoid architecture specific code leaking to the default codepath, all the code instantiated from those kernels should be in anonymous namespace (or implemented elsewhere), but `declare_static_shape` violates that convention. One obvious fix to the problem is move the method implementations from .h to .cpp files.

**Comment by gchanan** [comment]
can we add a test? :)

**Comment by malfet** [comment]
@gchanan I have a small patch against qemu which should allow us to test for this particular regression.

**Comment by ximplia-marco-bagnaresi** [comment]
Is this problem solved? Is it possible to use pytorch-1.6 without AVX support? Please let me know.

**Comment by malfet** [comment]
Verified that default codepath of torch-1.7.0.dev20201013%2Bcpu-cp37-cp37m-linux_x86_64.whl no longer contains AVX2 instrucitons by running the following command:
```
~/git/qemu/x86_64-linux-user/qemu-x86_64 -cpu Broadwell -E ATEN_CPU_CAPABILITY=default /usr/bin/python -c 'import torch;print(torch.randn((3,3))+torch.ones((3, 3)))'
```

**Comment by BramVanroy** [comment]
@malfet So in other words, this issue will be fixed in 1.7?

**Comment by malfet** [comment]
@BramVanroy Yes

**Comment by maximtrp** [comment]
I am still having the issue reported [here](https://github.com/pytorch/pytorch/issues/45894) and probably related to this one. Just importing torch causes a crash due to illegal instruction. I am running Arch Linux and using a non-optimized version of [pytorch](https://archlinux.org/packages/community/x86_64/python-pytorch-cuda/). It is built using [these source files](https://github.com/archlinux/svntogit-community/tree/packages/python-pytorch/trunk). What can be wrong in [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/python-pytorch/trunk/PKGBUILD) or [disable_non_x86_64.patch](https://github.com/archlinux/svntogit-community/blob/packages/python-pytorch/trunk/disable_non_x86_64.patch) files? AFAIK, Arch packages are built on modern CPUs with AVX/FMA instructions.

**Comment by ezyang** [comment]
I'm not sure why your disable AVX patch didn't work, but if you can patch in https://github.com/pytorch/pytorch/pull/43554 that might help

**Comment by maximtrp** [comment]
@ezyang I'm installing version 1.7.0, so this patch is already there. Can I somehow debug it?

**Comment by ezyang** [comment]
yes, run it under gdb and tell us what symbol / backtrace the illegal instruction is occurring in

**Comment by ezyang** [comment]
also I suggest opening a new issue, this is probably something different

**Comment by malfet** [comment]
@maximtrp if you running the code on modern CPU you need to build qemu with a small patch to simulate sigill on all AVX instructions.
