### ISSUE TITLE
Question, why Data moving to CUDA is slightly different

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/pytorch#43313]
PyTorch version 1.6
Installed from binary.
OS Used Linux Ubuntu 18.04
Machine used Google Colab

I'm Getting error
```
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

Though by printing devices in both places it came out to be "cuda"

As far I presume this occurs because my data is not on CUDA.
But I'm pushing the data to cuda in my code.

```
In training coder
if torch.cuda.is_available():
        device = "cuda"
    else: 
        device = "cpu"
encoder.to(device)
decoder.to(device)

def train_step(encoder, decoder, train_loader, loss_fn, optimizer, device):
    device = "cuda"
    encoder.train()
    decoder.train()

    print(device)

    for batch_idx, (train_img, target_img) in enumerate(train_loader):
        train_img.to(device)
        target_img.to(device)

        optimizer.zero_grad()

        enc_output = encoder(train_img)
        dec_output = decoder(enc_output)

        loss = loss_fn(dec_output, target_img)
        loss.backward()

        optimizer.step()

    return loss.item()
```

The Training works fine on CPU, so model definition and code is correct. I'm unsure why this error should occur.
The data has to move to CUDA which isn't moving at all.

I tried with P100, T4 both are giving errors.

I can share my entire code too, but this error is really strange. I have trained previously on 1.6 on CUDA it worked fine.

**Comment by oke-aditya** [comment]
Here is my entire code. This is something really absurd. As I don't have GPU I cannot confirm if this error is with Google Colab or with PyTorch.
I suppose with Colab.
[Train_image_similarity.zip](https://github.com/pytorch/pytorch/files/5100571/Train_image_similarity.zip)

**Comment by oke-aditya** [comment]
OMG ! What a mistake from me
```
train_img = train_img.to(device)
traget_img = target_img.to(device)

```
and then code worked.
Why is it this way for data ?

**Comment by ag14774** [comment]
Because `model` is a 'container' for parameters/tensors. `model.to()` will loop over all parameters and call `.to()` on those parameters. A simplified version of how `to()` is implemented for a model is this:
```python
for key, param in self._parameters.items():
    self._parameters[key] = param.to(device)
```

I don't see a way around this. The model will get modified in-place since it is just a container. Note though that you can still do `model = model.to(device)` so that your code will be consistent.

**Comment by pbelevich** [comment]
I'm closing because I think it's resolved, if it's not - please reopen
