### ISSUE TITLE
Move caffe2_onnx_main_py3_6_clang7_ubuntu16_04 off of Caffe2 image

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#43336]
caffe2_onnx_main_py3_6_clang7_ubuntu16_04 is still a Caffe2 image (308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py3.6-clang7-ubuntu16.04:376). This means we cannot easily update it with @seemethere's nice built-in Docker image building process, which means that it is a ticking time bomb; at some point it will be so out of date that someone will not be able to land a change because the Caffe2 image needs updating. We should get this configuration off of the caffe2 image and onto one of the PyTorch images.

cc @malfet @ezyang @seemethere

**Comment by walterddr** [comment]
closed via #44595.
