### ISSUE TITLE
Simple NCCL all_reduce with no group argument fails to complete

### ISSUE THREAD

**Issue by froody** [pytorch/pytorch#43345]
## 🐛 Bug

Running the code below doesn't ever complete, though changing it to pass an explicit group allows it to complete.

## To Reproduce

run the code below, output for me is
```
init nccl 1, 2
init nccl 0, 2
dist init for 1
dist init for 0
past barrier for 0
past barrier for 1
past all_reduce for 0
```
code:
```
import torch
import os


def run(rank, world_size):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "10638"
    os.environ["WORLD_SIZE"] = str(world_size)
    os.environ["RANK"] = str(rank)
    init_method = f"tcp://{os.environ['MASTER_ADDR']}:{os.environ['MASTER_PORT']}"

    print(f"init nccl {rank}, {world_size}")
    torch.distributed.init_process_group(
        backend="nccl", rank=rank, world_size=world_size, init_method=init_method
    )

    if False: # enable to fix it
        torch.distributed.all_reduce(torch.zeros(1).cuda())

    assert torch.distributed.is_initialized()
    assert rank == torch.distributed.get_rank()
    assert world_size == torch.distributed.get_world_size()

    torch.cuda.set_device(0)

    print(f"dist init for {rank}")
    torch.distributed.barrier()

    print(f"past barrier for {rank}")
    t = torch.Tensor(range(10)).cuda()

    torch.distributed.all_reduce(t, op=torch.distributed.ReduceOp.SUM)
    print(f"past all_reduce for {rank}")
    assert torch.equal(t, torch.Tensor(range(0, 20, 2)).cuda())

if __name__ == "__main__":
    world_size = 2
    torch.multiprocessing.spawn(run, args=(world_size,), nprocs=world_size, join=True)
```

## Expected behavior

Program prints "past all_reduce for 0" and "past all_reduce for 1" and exits cleanly.

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchtext==0.7.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0da4684_0    conda-forge
[conda] numpy                     1.19.1           py37hbc911f0_0
[conda] numpy-base                1.19.1           py37hfa32c7d_0
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchtext                 0.7.0                    pypi_0    pypi
[conda] torchvision               0.7.0                py37_cu101    pytorch## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by froody** [comment]
Also works fine if I use gloo backend and convert all tensors to cpu

**Comment by froody** [comment]
Apparently if I add "torch.distributed.all_reduce(torch.zeros(1).cuda())" right after the call to `init_process_group` it works fine, why is this required and not done by `init_process_group`?

**Comment by pritamdamania87** [comment]
You probably need to change `torch.cuda.set_device(0)` to `torch.cuda.set_device(rank)` since in the current code both processes are using the same GPU and trying an allreduce for two tensors on the same GPU. Changing that line to `torch.cuda.set_device(rank)` seems to fix the issue.
