### ISSUE TITLE
Query regarding support for RISC-V Vector ISA 

### ISSUE THREAD

**Issue by soniab** [pytorch/pytorch#43359]
Does Pytorch supports RISC-V ISA or  RISC-V Vector ISA extension? 

cc @VitalyFedyunin @ngimel @ezyang

**Comment by VitalyFedyunin** [comment]
It now supported, but you will need to compile it yourself.

**Comment by zinovya** [comment]
@VitalyFedyunin do you know if there is a blog post or some kind of article describing how to build pytorch for risc-v?

**Comment by joshue031** [comment]
While it is possible to compile PyTorch for RISC-V, I have not yet seen specific support for the vector ISA extension, so I've attempted to replace a few operators (tensor add, matrix multiplication, linear layer forward/backward) with a corresponding version that makes use of RISC-V vector functions (see https://github.com/joshue031/rvv-pytorch)

These operators can be used in training and evaluation for a fully connected NN. The code is currently set up as an incomplete "backend" (really just a re-registration of several operators on the CPU dispatch key) which needs to be compiled to a .so and loaded with `torch.ops.load_library`. So far it has just been run in software simulation, using QEMU with a modified Ubuntu Linux kernel. It would be interesting to run this on real RISC-V hardware to begin quantifying performance gains.

**Comment by kroryan** [comment]
> Si bien es posible compilar PyTorch para RISC-V, todavía no he visto soporte específico para la extensión vectorial ISA, por lo que intenté reemplazar algunos operadores (suma de tensor, multiplicación de matrices, capa lineal hacia adelante/atrás) con un versión correspondiente que hace uso de funciones vectoriales RISC-V (consulte https://github.com/joshue031/rvv-pytorch )
> 
> Estos operadores se pueden utilizar en la capacitación y evaluación de una NN completamente conectada. Actualmente, el código está configurado como un "backend" incompleto (en realidad, solo un nuevo registro de varios operadores en la clave de despacho de la CPU) que debe compilarse en un .so y cargarse con `torch.ops.load_library`. Hasta ahora sólo se ha ejecutado en simulación de software, utilizando QEMU con un kernel de Ubuntu Linux modificado. Sería interesante ejecutar esto en hardware RISC-V real para comenzar a cuantificar las ganancias de rendimiento.



> Si bien es posible compilar PyTorch para RISC-V, todavía no he visto soporte específico para la extensión vectorial ISA, por lo que intenté reemplazar algunos operadores (suma de tensor, multiplicación de matrices, capa lineal hacia adelante/atrás) con un versión correspondiente que hace uso de funciones vectoriales RISC-V (consulte https://github.com/joshue031/rvv-pytorch )
> 
> Estos operadores se pueden utilizar en la capacitación y evaluación de una NN completamente conectada. Actualmente, el código está configurado como un "backend" incompleto (en realidad, solo un nuevo registro de varios operadores en la clave de despacho de la CPU) que debe compilarse en un .so y cargarse con `torch.ops.load_library`. Hasta ahora sólo se ha ejecutado en simulación de software, utilizando QEMU con un kernel de Ubuntu Linux modificado. Sería interesante ejecutar esto en hardware RISC-V real para comenzar a cuantificar las ganancias de rendimiento.

im gonna try it on real hardware, thanks for it, hope still working :)

**Comment by kroryan** [comment]
> While it is possible to compile PyTorch for RISC-V, I have not yet seen specific support for the vector ISA extension, so I've attempted to replace a few operators (tensor add, matrix multiplication, linear layer forward/backward) with a corresponding version that makes use of RISC-V vector functions (see https://github.com/joshue031/rvv-pytorch)
> 
> These operators can be used in training and evaluation for a fully connected NN. The code is currently set up as an incomplete "backend" (really just a re-registration of several operators on the CPU dispatch key) which needs to be compiled to a .so and loaded with `torch.ops.load_library`. So far it has just been run in software simulation, using QEMU with a modified Ubuntu Linux kernel. It would be interesting to run this on real RISC-V hardware to begin quantifying performance gains.

im gonna try it on real hardware, thanks for it :While it is possible to compile PyTorch for RISC-V, I have not yet seen specific support for the vector ISA extension, so I've attempted to replace a few operators (tensor add, matrix multiplication, linear layer forward/backward) with a corresponding version that makes use of RISC-V vector functions (see https://github.com/joshue031/rvv-pytorch)

These operators can be used in training and evaluation for a fully connected NN. The code is currently set up as an incomplete "backend" (really just a re-registration of several operators on the CPU dispatch key) which needs to be compiled to a .so and loaded with `torch.ops.load_library`. So far it has just been run in softwarWhile it is possible to compile PyTorch for RISC-V, I have not yet seen specific support for the vector ISA extension, so I've attempted to replace a few operators (tensor add, matrix multiplication, linear layer forward/backward) with a corresponding version that makes use of RISC-V vector functions (see https://github.com/joshue031/rvv-pytorch)

These operators can be used in training and evaluation for a fully connected NN. The code is currently set up as an incomplete "backend" (really just a re-registration of several operators on the CPU dispatch key) which needs to be compiled to a .so and loaded with `torch.ops.load_library`. So far it has just been run in software simulation, using QEMU with a modified Ubuntu Linux kernel. It would be interesting to run this on real RISC-V hardware to begin quantifying performance gainse simulation, using QEMU with a modified Ubuntu Linux kernel. It would be interesting to run this on real RISC-V hardware to begin quantifying performance gains.)

> While it is possible to compile PyTorch for RISC-V, I have not yet seen specific support for the vector ISA extension, so I've attempted to replace a few operators (tensor add, matrix multiplication, linear layer forward/backward) with a corresponding version that makes use of RISC-V vector functions (see https://github.com/joshue031/rvv-pytorch)
> 
> These operators can be used in training and evaluation for a fully connected NN. The code is currently set up as an incomplete "backend" (really just a re-registration of several operators on the CPU dispatch key) which needs to be compiled to a .so and loaded with `torch.ops.load_library`. So far it has just been run in software simulation, using QEMU with a modified Ubuntu Linux kernel. It would be interesting to run this on real RISC-V hardware to begin quantifying performance gains.

im gonna try it on real hardware, thanks for it

**Comment by joshue031** [comment]
Is there any interest in continuing this development of RISC-V vector ISA instruction support?

**Comment by wf1594149160** [comment]
I want to determine whether pytorch needs RVV support. If so, what needs to be done.

**Comment by joshue031** [comment]
I haven't looked at this in detail in awhile, but from what I understood:

- back in 2022 there was NOT direct support for RVV in Pytorch. That is, if one compiled Pytorch for a RISC-V architecture to run on a processor that implemented the vector instructions, there was no direct calling of the RVV instructions in the Pytorch code.
- I heard that RISC-V compilers were capable of automatically including RVV optimization to some extent, that is they would make use of RVV instructions in the appropriate situations. Perhaps this has even improved since then. I'm not sure how well this worked or now works, or if these optimizations would be on-par with a direct implementation within Pytorch in which the RVV instructions are called explicitly rather than left up to the compiler

It may be that, now or in the future, Pytorch compiled on RISC-V vector processors will automatically make use of the vector optimizations, at least to some extent, but I have a feeling that a more direct implementation of the use of RVV accelerators (similar to what is done for CUDA and MPS) would give better performance.

I would also be interested in knowing if there are further opinions on this. To what extent are people planning to design RISC-V ML accelerators based on RVV? Is there interest in adapting Pytorch to this?
