### ISSUE TITLE
Possible return value bug when a function is registered in boxed form and called unboxed

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#43358]
I was making notes for myself on what happens when a function is
1. Registered in unboxed form, called unboxed.
2. Registered in unboxed form, called boxed.
3. Registered in boxed form, called unboxed.
4. Registered in boxed form, called boxed.

and I saw something weird in case 3 (function registered in boxed form then called unboxed):
[`auto result = guts::tuple_take<ArgTuple, RetCount>(ArgTuple{args...});`](https://github.com/pytorch/pytorch/blob/0dc41ff465891cb7d49e9ae733e2e5c4375990cf/aten/src/ATen/core/boxing/impl/boxing.h#L274)
Why does it return a tuple taken from incoming `args...` instead of `stack`? 

I expected to see `result` created from `stack`, under the assumption `stack` was modified in-place by
[`(*boxed_kernel_func)(functor, opHandle, &stack);`](https://github.com/pytorch/pytorch/blob/0dc41ff465891cb7d49e9ae733e2e5c4375990cf/aten/src/ATen/core/boxing/impl/boxing.h#L267) (i.e., `(*boxed_kernel_func)(functor, opHandle, &stack);`  dropped the args from `stack` and pushed its result(s) to `stack`, which, for example, is how [boxed wrappers for unboxed functions](https://github.com/pytorch/pytorch/blob/0dc41ff465891cb7d49e9ae733e2e5c4375990cf/aten/src/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h#L393-L394) behave).

Returning a tuple based on `args...` instead of `stack` will only work, I think, if `(*boxed_kernel_func)(functor, opHandle, &stack);`'s effect is to modify the first one or several `args...` in place.

If `boxed_kernel_func`'s implementation tries to communicate its return value to the outside world by pushing something to `stack`, `auto result = guts::tuple_take<ArgTuple, RetCount>(ArgTuple{args...});` does not (afaict) faithfully pass along `boxed_kernel_func`'s return value.

git blame says `auto result = guts::tuple_take<ArgTuple, RetCount>(ArgTuple{args...});` was introduced in https://github.com/pytorch/pytorch/pull/38999.  But that didn't alleviate my confusion.  There were no review comments anywhere near [that line in the PR](https://github.com/pytorch/pytorch/pull/38999/files#diff-63afcafe5c0813e43103b1a242566847R286).

These are deep waters and it's possible my concern doesn't make sense.  But @ezyang reassured me this is not an embarrassingly dumb question to ask.  Maybe @bhosmer (author of https://github.com/pytorch/pytorch/pull/38999) or @smessmer can clarify.  If I'm right, this is a bug, and could be fixed by creating `result` from `stack`** instead of `args`. If I'm wrong or needlessly paranoid, I'd like to know why.  Understanding the dispatcher is really valuable when working on autocast.

** getting a typeful `result` from `stack` may require `ivalue_to_arg` metaprogramming magic similar to [call_functor_with_args_from_stack_](https://github.com/pytorch/pytorch/blob/d7aaa3327bf9ad8757897a76879230da92bf607f/aten/src/ATen/core/boxing/impl/make_boxed_from_unboxed_functor.h#L264), but that's manageable.  Fun, even.

**Comment by bhosmer** [comment]
Hi @mcarilli - not a bad question at all, this code is tricky and the use-case is very particular. The motivation is explained in [this comment](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/boxing/impl/boxing.h#L233-L238):
```
// 4. signatures returning a tuple of Tensor references, and taking the same
// number of Tensor refs as their initial arguments.
//
// Note that the passed kernels are assumed to be for inplace/outplace ops,
// and the generated BoxedKernelWrapper specializations will return a tuple
// of those initial arguments.
```
Basically, the "inplace/outplace" ops referred to in the comment are ops that fit the common pattern of returning one or more of their Tensor arguments - this specialization implements boxing wrappers for the "or more" case. (The [preceding one](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/boxing/impl/boxing.h#L191-L228) handles the single-return case.)

Also note that these specializations are only over mutable Tensor references, so we won't lose in-place updates made by the kernel - they'll have modified the Tensor referent; the kernel won't be pushing a new reference onto the stack. (BTW if you're wondering why we go the trouble of carefully scooping off the actual passed arg(s) like this in the first place, the answer is pretty arcane, but comes down to avoiding an extra refcount in the Tensors being returned.)

**Comment by mcarilli** [comment]
Nice!  Ive been trying to digest a lot of code recently and got lazy...i opened the file, saw helper-ish stuff at the top, skipped to the bottom, saw (what I thought was) the definition I wanted, and got tunnel vision parsing it. That'll teach me to read the whole file :facepalm:  It isn't even that long, and the rest looks sensible for all cases (with [fun Result packing](https://github.com/pytorch/pytorch/blob/e8139624f26fe138e87fb403a60c8563542ef652/aten/src/ATen/core/boxing/impl/boxing.h#L143-L144) already present).
