### ISSUE TITLE
unique() and type() are not availabe in graph.nodes()

### ISSUE THREAD

**Issue by hhsecond** [pytorch/pytorch#4337]
``unique()`` and ``type()`` functions are not available in the nodes from ``graph.nodes()`` of ``jit.trace``. I used to fetch those before some upgrade I made recently. As @apaszke suggested, It should be present in the internal data structure but the new upgrade just removed it from python scope

```
for val in trace.graph().nodes():
    print(val.unique())  # doesn't have unique
    for input_node in val.inputs():
        print(input_node.unique())  # has unique
```

**Comment by ezyang** [comment]
Yes this should be pretty simple to add. Tag me on a PR and I'll make sure it gets reviewed.

**Comment by hhsecond** [comment]
@ezyang my CPP knowledge is very minimal but I can give it a shot if you could guide me a little

**Comment by apaszke** [comment]
It should be a matter of adding a few lines in `torch/csrc/jit/python_ir.cpp`

**Comment by hhsecond** [comment]
@apaszke @ezyang Looks like ``unique()`` is not a method of ``node`` anymore and is available in only ``Value``. The return value of ``graph.nodes()`` looks like ``Value`` rather than ``node``. In that case is this even possible to resolve this github issue.

**Comment by apaszke** [comment]
`type()` is unavailable on purpose - every node only produces a number of outputs with specific types, and there's no point in duplicating that information. `unique()` is also no longer necessary - it's used to label SSA registers (Values) in our IR.

**Comment by hhsecond** [comment]
Closing this issue then. I figured out a work around by using ``id()`` of python to get unique id. Thanks @lantiga

**Comment by hhsecond** [comment]
@apaszke Since you mentioned ``unique()`` is also no longer necessary, would that be removed from ``Values`` also? Or it is unnecessary only for ``Node``

**Comment by apaszke** [comment]
It's only unnecessary for `Node`. If you want to get a unique id (within nodes only), you can use `value.node().outputs()[0].unique()` (every node is guaranteed to have at least a single output).
