### ISSUE TITLE
a problem about ELU

### ISSUE THREAD

**Issue by DDDivano** [pytorch/pytorch#43389]
if alpha < 0 
![image](https://user-images.githubusercontent.com/10734244/90847652-8c36e580-e39d-11ea-96ce-e2a9d95d5fa8.png)
returns a wrong result.
I find the code seems that alpha should not input value less than zero？

**Comment by albanD** [comment]
I am not sure to follow. alpha is `negcoef` in this formula. And it seems to be multiplied by the result of the exponential properly no?

**Comment by DDDivano** [comment]
> I am not sure to follow. alpha is `negcoef` in this formula. And it seems to be multiplied by the result of the exponential properly no?
In this formula min(0, alpha * (exp(x) -1)) equal alpha * (exp(x) -1) if alpha is negative
But in this code, if a > scalar_t(0) and alpha is negative, I think it should return a * poscoef + std::exp(a * negiptcoef) - scalar_t(1)

**Comment by albanD** [comment]
> In this formula min(0, alpha * (exp(x) -1)) equal alpha * (exp(x) -1) if alpha is negative

Not necessarily. `(exp(x) -1)` could be negative as well. And so the output will be 0.

**Comment by DDDivano** [comment]
> > In this formula min(0, alpha * (exp(x) -1)) equal alpha * (exp(x) -1) if alpha is negative
> 
> Not necessarily. `(exp(x) -1)` could be negative as well. And so the output will be 0.

if x > 0, exp(x)-1 > 0，if alpha is negative, output will be alpha * (exp(x) -1)
![image](https://user-images.githubusercontent.com/10734244/91248592-8d925480-e787-11ea-90ba-48a25a1bb477.png)

But in this code, if a > scalar_t(0) and alpha is negative, I think it should return a * poscoef + std::exp(a * negiptcoef) - scalar_t(1)

**Comment by albanD** [comment]
I see.
Is it valid though to use a negative alpha? I don't think the formula really makes sense for an activation function.
I think we should just raise an error when the use gives a negative alpha.

**Comment by mariosasko** [comment]
According to the initial [paper](https://arxiv.org/pdf/1511.07289.pdf) that introduced ELU (Section 3), a negative alpha is not valid. That being said, tf.keras supports negative alpha values and yields equal results (ran a few tests myself) so I'm not sure if this issue requires any changes in the source.

**Comment by albanD** [comment]
Ho interesting, when I checked the tf keras doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/activations/elu) it seems to only support `alpha > 0`.

**Comment by mariosasko** [comment]
> Ho interesting, when I checked the tf keras doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/activations/elu) it seems to only support `alpha > 0`.

Yes, I thought the same, but then I ran the code and it works perfectly fine with negative alphas.

**Comment by albanD** [comment]
Interesting. I guess we should update the formulas in the code then to handle the negative case.
We would be happy to accept a PR doing that!
