### ISSUE TITLE
Default initial hidden states for recurrent layers

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/pytorch#434]
The recurrent layers (nn.RNN, nn.LSTM, and nn.GRU) all expect initial hidden (+cell for LSTM) states as a required argument. Would it be possible for these to default to zero if not provided?

**Comment by goelhardik** [comment]
@apaszke Can I work on this issue? Is there a process to do that?

**Comment by apaszke** [comment]
Sure! As far as I know no one is working on that, so go ahead if you want.

**Comment by amrsharaf** [comment]
Can we add this to the RNN documentation page as well? Took me a while to find this information here..

**Comment by mrshu** [comment]
@amrsharaf a change adding that has just been merged. Hopefully, none will need to come here to find that out.

Thanks for suggesting that!

**Comment by amrsharaf** [comment]
great, thanks!

**Comment by nicktogo** [comment]
It seems that document for [LSTMCell](http://pytorch.org/docs/stable/nn.html#lstmcell) did not add default statement while document for [LSTM](http://pytorch.org/docs/stable/nn.html#lstm) does mention the default settings.
