### ISSUE TITLE
Numerical instability in DivBackward0 for multiple backward

### ISSUE THREAD

**Issue by mfkasim91** [pytorch/pytorch#43414]
## 🐛 Bug

A simple division operation: `g = x/y` could produce numerical instability if multiple backward is applied.
This is because the derivative is calculated by `-grad * self / (other * other)` (see `tools/autograd/derivatives.yaml` in `div.Tensor`).
The `other` tensor is squared in one backward operation, so multiple operation will raise `other` to the power of `2^n` and can reach `inf` or `0` very quickly.
A simple fix should be sufficient: by replacing the derivative calculation to `-grad * result / other`, but it makes a bunch of tests fail (I'm not sure why).

## To see the problem

    import torch

    class Div2(torch.autograd.Function):
        @staticmethod
        def forward(ctx, x, y):
            z = x / y
            ctx.save_for_backward(x, y, z)
            return z

        @staticmethod
        def backward(ctx, gz):
            x, y, z = ctx.saved_tensors
            gx = Div2.apply(gz, y)
            gy = Div2.apply(-gz*z, y)
            return gx, gy

    def example(g, y, n):
        gs = [g.item()]
        for i in range(n):
            g, = torch.autograd.grad(g, (y,), create_graph=True)
            gs.append(g.item())
        return gs

    if __name__ == "__main__":
        a = 1e-8
        x = torch.tensor(a, requires_grad=True)
        y = torch.tensor(a, requires_grad=True)
        n = 4
        factorial = lambda i: 1 if i < 2 else i * factorial(i-1)
        print("Div1 (current implementation):")
        print(example(x / y, y, n))
        print("Div2 (proposed implementation):")
        print(example(Div2.apply(x, y), y, n))
        print("Actual:")
        actual = [(-1)**i*factorial(i)/(a**i) for i in range(n+1)] # [1.0, -1/a, 2/(a*a), -3*2/(a*a*a), 4*3*2/(a**4)]
        print(actual)

Output: 

    Div1 (current implementation):
    [1.0, -100000000.0, 1.99999983976448e+16, -inf, nan]
    Div2 (proposed implementation):
    [1.0, -100000000.0, 2.000000054512845e+16, -6.000000083090567e+24, 2.4000002343777533e+33]
    Actual:
    [1.0, -100000000.0, 1.9999999999999996e+16, -5.999999999999999e+24, 2.4e+33]

The current implementation of `DivBackward0` could not calculate the results correctly even with `1e-8` for triple backward, even though the actual result still within the `float32` range.

## Expected behavior

See above.

## Environment

 - PyTorch Version (e.g., 1.0): PyTorch 1.6.0
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by mfkasim91** [comment]
All of them are variables being modified inplace. I guess the formula `-grad * result / other` will introduce BC breaking.

However, when I use `-grad * (self / other) / other` formula, it can pass all the autograd tests successfully (same status with the previous implementation).
So now I think it is up to PyTorch's team to choose between:

1. `-grad * self / (other * other)`
2. `-grad * (self / other) / other`

The first one might be slightly faster (because the use of multiplication instead of division), but the second one provides better numerical stability.

**Comment by albanD** [comment]
> All of them are variables being modified inplace. I guess the formula -grad * result / other will introduce BC breaking.

Yes... the problem is that if you use "result" in the formula, it has to be saved. And if anything changes the result inplace later, it will raise an error.

> the second one provides better numerical stability.

In your example of multiple backward passes, how much better is it? I wouldn't expect the slowdown to be problematic here.

**Comment by mfkasim91** [comment]
> In your example of multiple backward passes, how much better is it? I wouldn't expect the slowdown to be problematic here.

Here's the example above in case of `y=a/b` where `a=b=tensor(1e-8)` (I paste it here to make it easier to read):

      y ,   grad(y,b) , grad(grad(y,b),b)   , grad^3(y,b)            , grad^4(y,b)
    -----------------------------------------------------------------------------------
    Div1 (current implementation):
    [1.0, -100000000.0, 1.99999983976448e+16, -inf, nan]
    Div2 (proposed implementation):
    [1.0, -100000000.0, 2.000000054512845e+16, -6.000000083090567e+24, 2.4000002343777533e+33]
    Actual:
    [1.0, -100000000.0, 1.9999999999999996e+16, -5.999999999999999e+24, 2.4e+33]

1. The first grads are exactly the same
1. For the second grads, the relative error for the current implementation is about `8.0e-8` while for the proposed implementation it is about `2.7e-8` (the errors are still small, but the error for the proposed implementation is lower).
1. For the third and fourth grads, the current implementation already gives `-inf` and `nan` while the actual result (and the proposed implementation) is still within the `float32` range

**Comment by mfkasim91** [comment]
I have just made a more thorough comparison between the current implementation and the new implementation [here](https://colab.research.google.com/drive/1XEkZNputspFHfIQkRFPWFImF0PpW-F_d?usp=sharing).
The conclusions are:

1. The higher order grads for the current implementation can produces `nan` and `inf` while the proposed implementation only produces `inf`.
2. The current implementation results in more anomalies (`nan` and `inf`) than the proposed implementation.
3. There is **no** case where the proposed implementation produces anomaly and the current implementation does not produce anomaly.

**Comment by albanD** [comment]
Hi,

Thanks for the notebook!
I had a chat with people closer to perf questions and it should be ok to replace the multiplication with a division.
A simple sanity check with a `timeit` benchmark on cpu before and after the change should be fine to make sure it does not significantly slow down the backward pass for a the div op.

I'll check that and get back to you.

**Comment by albanD** [comment]
This is what I get with
```python
import torch

a = torch.rand(100, 100, requires_grad=True)
b = torch.rand(100, 100, requires_grad=True)

out = (a / b).sum()

%timeit out.backward(retain_graph=True)
```

before:
44.9 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

after:
45.6 µs ± 1.22 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

So I'm gonna go ahead and send a PR as the perf difference is not significant.
