### ISSUE TITLE
Enable torch.utils.(mkldnn/mobile_optimizer/bundled_inputs) typechecks during CI

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#43431]
`TestTypeHints.test_run_mypy_strict` should pass with `[mypy-torch.utils.mkldnn]/[mypy-torch.utils. mobile_optimizer]/[mypy-torch.utils. bundled_inputs]` deleted from mypy.ini

cc @ezyang @malfet @rgommers

**Comment by rgommers** [comment]
This may depend on gh-43406
