### ISSUE TITLE
Can't export onnx from normal computation graph

### ISSUE THREAD

**Issue by tkclimb** [pytorch/pytorch#4343]
Is there any way to export normal computation graph by `pytorch.onnx.export` ??
I just met an error when I ran a following simple code.

## sample code
```
from torch.autograd import Variable
import torch.onnx
import torchvision


x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
z = y.mean()

torch.onnx.export(z, x, 'cg.onnx.pb', verbose=True)
```

## error message
```
>> python python/computation_graph.py

Traceback (most recent call last):
  File "python/computation_graph.py", line 13, in <module>
    torch.onnx.export(z, x, 'cg.onnx.pb', verbose=True)
  File "/Users/yamada/.pyenv/versions/trillion/lib/python3.6/site-packages/torch/onnx/__init__.py", li
ne 75, in export
    _export(model, args, f, export_params, verbose, training)
  File "/Users/yamada/.pyenv/versions/trillion/lib/python3.6/site-packages/torch/onnx/__init__.py", li
ne 108, in _export
    orig_state_dict_keys = model.state_dict().keys()
  File "/Users/yamada/.pyenv/versions/trillion/lib/python3.6/site-packages/torch/autograd/variable.py"
, line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'state_dict'
```

it seems to be 1st argment is not proper. 
however I have no idea which kind of object I should take here when I'd like actually to do it.

**Comment by hhsecond** [comment]
``onnx.export`` expects the first argument to be a model (inherited from torch.nn.Module) that has ``forward`` method and can be backpropagated. In the above case, you are passing a Variable

**Comment by ezyang** [comment]
@hhsecond you are right on. @tkclimb, give that a try?

**Comment by shbnm21** [comment]
I am facing different issue with onnx.eport function

x = torch.randn(batch_size, 1, 224, 224, requires_grad=True)


torch_out = torch.onnx._export(torch_model, x,                       
                               "model1.onnx",  
                               export_params=True)   

It gives me graph 
But when I print torch_out it gives None

And that is causing AtrributError when comparing torch_out with caffe2 model

np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

In this function I am getting error as
Attribute Error 'Nonetype'object has no attribute 'data'

What could be the reason

Please help
