### ISSUE TITLE
ConvTranspose3d with large input tensor

### ISSUE THREAD

**Issue by tlkvstepan** [pytorch/pytorch#4344]
ConvTranspose3d with large input raises an error:

RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input

``` python
    x = Variable( th.rand([1, 8, 128, 512, 512]).cuda() )
    tconv = nn.ConvTranspose3d(in_channels=8, out_channels=1, kernel_size=4, stride=2, padding=1).cuda()
    y = tconv(x)
```
With smaller inputs the module works fine. CUDA 8.0.44, CUDNN v5.

**Comment by tlkvstepan** [comment]
Ok, as explained in issue #1664 it is cudnn bug. But what is the best fix? 
Is it better to use cudnn.benchmark = True, or disable cudnn?  I am processing large inputs, so I assume that using benchmark flag is not a wise choice. However, my experiments show that with cudnn disabled, networks requires even more GPU memory, than with the benchmark flag..

**Comment by ngimel** [comment]
Try updating your cudnn, cudnn v5 is no longer supported by pytorch. In deciding whether to use cudnn.benchmark what's important is not how big the inputs are, but how often the size of the input changes (if at all). If your inputs are always the same size (or you have just a few possible input sizes) you can use cudnn.benchmark.

**Comment by tlkvstepan** [comment]
thank you for your suggestions, 
I updated cudnn to v7, cuda 8, pytorch 0.3 (pip)  and set cudnn.benchmark = True, 
With benchmark = True, I can process larger inputs than without it. However with even larger inputs I again face the same error message.
