### ISSUE TITLE
some warning in building pytorch（caffe2）

### ISSUE THREAD

**Issue by yang-gis** [pytorch/pytorch#43449]
## ❓ Questions and Help
There are a lot of warnings during pytorch building. What is the third-party (protobuf, for example) version of this third-party library? I have successfully set up Pytorch (Caffe2), but when I compile my CPP file with cmake it will cause an error "Undefined reference to Google ::protobuf..." .
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

As you can see in the template you used, you should use the [forum](https://discuss.pytorch.org/) to ask questions.
Can you open a new topic there explaining what you were trying to do and the error?

Thanks!

**Comment by yang-gis** [comment]
Thanks, I had solved these problems.


| |
婷婷
|
|
yangjinyi_gis@163.com
|
签名由网易邮箱大师定制
On 8/24/2020 21:32，albanD<notifications@github.com> wrote：

Hi,

As you can see in the template you used, you should use the forum to ask questions.
Can you open a new topic there explaining what you were trying to do and the error?

Thanks!
