### ISSUE TITLE
right argument in torch.bucketize works opposite to its boolean value

### ISSUE THREAD

**Issue by eelregit** [pytorch/pytorch#43458]
## 🐛 Bug

As the title suggested, the `right` argument in `torch.bucketize` works opposite to the description of the documentation,
as well as `numpy.digitize`.

## To Reproduce

1. Run the example in the docstring, get the same results as in the docstring
```python
>>> boundaries = torch.tensor([1, 3, 5, 7, 9])
>>> v = torch.tensor([[3, 6, 9], [3, 6, 9]])
>>> torch.bucketize(v, boundaries)
tensor([[1, 3, 4],
        [1, 3, 4]])
>>> torch.bucketize(v, boundaries, right=True)
tensor([[2, 3, 5],
        [2, 3, 5]])
```
2. Run it with `numpy.digitize`
```python
>>> boundaries = numpy.array([1, 3, 5, 7, 9])
>>> v = numpy.array([[3, 6, 9], [3, 6, 9]])
>>> numpy.digitize(v, boundaries)
array([[2, 3, 5],
       [2, 3, 5]])
>>> numpy.digitize(v, boundaries, right=True)
array([[1, 3, 4],
       [1, 3, 4]])
```
3. The two functions have consistent docstrings, but give opposite results.
    To me the pytorch results **contradict the documentation**. (**Edited**)

## Expected behavior

pytorch function behavior should agree with their documentations. (**Edited**)

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: CentOS Linux release 7.8.2003 (Core) (x86_64)
GCC version: (GCC) 7.4.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch

cc @yf225 @glaringlee @mruberry @rgommers

**Comment by ngimel** [comment]
cc @glaringlee

**Comment by glaringlee** [comment]
@eelregit 
Thanks for pointing this out. 
`bucketize` and `searchsorted` were implemented following numpy's searchsorted.
It seems that numpy's `searchsorted` and `digitize` has opposite meaning for flag `right`, I will fix the bucketize soon.

In the meantime, you can use `searchsorted` instead if you don't want to change the right flag later in your code.

**Comment by eelregit** [comment]
Thanks! That makes sense. @glaringlee 

Behavior wise, as you said, `torch.searchsorted` ~ `torch.bucketize` ~ `numpy.searchsorted`, opposite to `numpy.digitize`.

However, documentation wise, `torch.searchsorted` ~ `torch.bucketize` ~ `numpy.digitize`, different from `numpy.searchsorted`, no?

**Comment by glaringlee** [comment]
@eelregit 
Behavior wise, you are right.
Document wise, torch.searchsorted, torch.bucketize and numpy.searchsorted are the same regarding the meaning of `right`, and numpy.digitiize are the opposite, same as behavior. 

For eg. since we assume the input is always ascending order in pytorch, so when `right` is false, we always find the lower bound boundary for x which is `bin[i-1] < x <= bin[i]`, and when `right` is true, we find the upper bound boundary (bin[i-1] <= x < bin[i]).

**Comment by eelregit** [comment]
Well, apparently your documentations disagree.
Let me paste below those tables taken from your master branch and numpy stable
@glaringlee 

`torch.bucketize`:
right | returned index satisfies
-- | --
False | boundaries[i-1] <= input[m][n]...[l][x] < boundaries[i]
True | boundaries[i-1] < input[m][n]...[l][x] <= boundaries[i]

`torch.searchsorted`:
sorted_sequence | right | returned index satisfies
-- | -- | --
1-D | False | sorted_sequence[i-1] <= values[m][n]...[l][x] < sorted_sequence[i]
1-D | True | sorted_sequence[i-1] < values[m][n]...[l][x] <= sorted_sequence[i]

`np.digitize`:
right | order of bins | returned index i satisfies
-- | -- | --
False | increasing | bins[i-1] <= x < bins[i]
True | increasing | bins[i-1] < x <= bins[i]

`np.searchsorted`:
side | returned index i satisfies
-- | --
left | a[i-1] < v <= a[i]
right | a[i-1] <= v < a[i]

**Comment by glaringlee** [comment]
@eelregit 
Ah, I see, I've though you were talking about the document comments within the code. Yes, you are right, the html document is obviously wrong, I will fix it soon. Thanks a lot for pointing out and guiding me to the right spot.

**Comment by mruberry** [comment]
> @ngimel Currently, bucketize is an alias of searchsorted (I did this since tensorflow has both searchsorted and bucketize), should we change the behavior of bucketize to the same as numpy's digitize? or create digitize?

NumPy doesn't have bucketize so I wouldn't change its behavior to match a different NumPy function. We are planning, however, to create torch.digitize.

**Comment by x-zb** [comment]
@glaringlee 
Hi, have you fixed the documentation of torch.searchsorted ? I find the documentation still contradict with the function's behavior, and this confused me a lot.

**Comment by mruberry** [comment]
Would you file a new issue for the searchsorted documentation, @x-zb, explaining the issues you see?

**Comment by glaringlee** [comment]
@x-zb 
It's fixed. Can you provide more details on where you are confused? I can help then.
