### ISSUE TITLE
Error in libtorch.so during make under Raspberry Pi 4b

### ISSUE THREAD

**Issue by luanjianbing** [pytorch/pytorch#43464]
### I tried to deploy libtorch-yolov5s on Raspberry Pi 4b, and there was a problem in the last make:
/usr/bin/ld: /home/ubuntu/libtorch/lib/libtorch.so: error adding symbols: file in wrong format

could anyone give some suggestions?

**Comment by ljk53** [comment]
@luanjianbing where did you get the libtorch.so from? I don't think we have officially released libtorch for Raspberry Pi, so if you are using a version built for other platform then it won't work as expected.

**Comment by luanjianbing** [comment]
> @luanjianbing where did you get the libtorch.so from? I don't think we have officially released libtorch for Raspberry Pi, so if you are using a version built for other platform then it won't work as expected.

**Comment by luanjianbing** [comment]
yes，I find that. I download the libtorch.so from pytorch.org which is not supported for arm64. so if i want to use libtorch in arm64, i need to remake source code?
