### ISSUE TITLE
from sources install pytorch on ubuntu18.04,the question is this.What should I do ?

### ISSUE THREAD

**Issue by HongdaChen** [pytorch/pytorch#43463]
-- Generating done
-- Build files have been written to: /home/wuji/pytorch/build
Traceback (most recent call last):
  File "setup.py", line 737, in <module>
    build_deps()
  File "setup.py", line 321, in build_deps
    cmake=cmake)
  File "/home/wuji/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/home/wuji/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/home/wuji/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/wuji/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/wuji/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/wuji/anaconda3', '-DNUMPY_INCLUDE_DIR=/home/wuji/anaconda3/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/wuji/anaconda3/bin/python', '-DPYTHON_INCLUDE_DIR=/home/wuji/anaconda3/include/python3.7m', '-DPYTHON_LIBRARY=/home/wuji/anaconda3/lib/libpython3.7m.so.1.0', '-DTORCH_BUILD_VERSION=1.7.0a0+7c50c2f', '-DUSE_NUMPY=True', '/home/wuji/pytorch']' returned non-zero exit status 1.

cc @malfet

**Comment by ngimel** [comment]
Please provide full logs.

**Comment by HongdaChen** [comment]
I have solved the problem,thank you!

**Comment by HongdaChen** [comment]
Thank you,I have solved the problem




| |
陈鸿达
|
|
邮箱：aikedaer@163.com
|

签名由 网易邮箱大师 定制

On 08/26/2020 01:15, ngimel wrote:

Closed #43463.
