### ISSUE TITLE
Expose Finfo in libtorch as well

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#43461]
## 🚀 Feature
Expose Finfo in libtorch as well, the same way it is exposed in pytorch.

## Motivation

I wanted to port `np.spacing(1)` and I need finfo for this. this is implemented and exposed in pytorch but not in libtorch.

## Pitch

expose finfo in libtorch!

## Alternatives

The alternative is t o use xtensor which is not ideal as it imposes lots of dependencies!

**Comment by ngimel** [comment]
std::nextafter gives you the necessary information https://en.cppreference.com/w/cpp/numeric/math/nextafter. Btw, torch.nextafter (similar to np.nextafter) is already implemented.

**Comment by Coderx7** [comment]
@ngimel  thanks a lot. I was wondering if I could also use std::nextafter! good to know. 
by the way, I couldnt find any trace of nextafter! neighter `torch.nextafter` nor `torch::nextafter` are valid! should I be including/importing something special from torch?

**Comment by ngimel** [comment]
nextafter was recently merged (#42580)

**Comment by ngimel** [comment]
THPFInfo and THPFInfo_eps exist to make this information available in python, for c++ using std functions should be enough.
