### ISSUE TITLE
Segmentation fault when passing torch.Tensor() a tensor on the gpu in no_grad context

### ISSUE THREAD

**Issue by boykovdn** [pytorch/pytorch#43474]
## 🐛 Bug

Segmentation fault when giving torch.Tensor an input Tensor in no_grad context.

## To Reproduce

import torch
tt = torch.Tensor([1,2,3]).cuda()
with torch.no_grad:
    tt = torch.Tensor(tt)

## Expected behavior

torch.Tensor on the cpu

## Environment

PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.0

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti

Nvidia driver version: 440.59
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] inferno-pytorch==0.4.0
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[pip] torchviz==0.0.1
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0  
[conda] pytorch                   1.4.0           cuda100py37h75a84eb_0  
[conda] torchvision               0.5.0                py37_cu100    pytorch
[conda] torchviz                  0.0.1                     dev_0    <develop>

**Comment by ngimel** [comment]
I can't reproduce on master, I get `TypeError: expected CPU (got CUDA)` error.
