### ISSUE TITLE
How to extract the hidden feature of a multi-submodule model

### ISSUE THREAD

**Issue by QuXinghuaNTU** [pytorch/pytorch#43489]
How to extract the feature in advantage (with dim=512), given a PyTorch model like below.
DuelingCnnDQN(
  (cnn): Sequential(
    (0): Conv2d(1, 32, kernel_size=(8, 8), stride=(4, 4))
    (1): ReLU()
    (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
    (3): ReLU()
    (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
    (5): ReLU()
    (6): Flatten()
  )
  (advantage): Sequential(
    (0): Linear(in_features=3136, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=6, bias=True)
  )
  (value): Sequential(
    (0): Linear(in_features=3136, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=1, bias=True)
  )
)

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org.
