### ISSUE TITLE
"torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &)" cannot be referenced -- it is a deleted function

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#43480]
[While compiling torchcsprng with NVCC on Windows](https://app.circleci.com/pipelines/github/pytorch/csprng/387/workflows/06795339-449f-422f-ba06-01bc87fa6b80/jobs/10817):
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/include\xutility(4387): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked1(_InIt, _InIt, _OutIt, std::false_type) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]" 
(4403): here
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]" 
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/include\vector(1353): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]" 
C:/Users/circleci/project/env/lib/site-packages/torch/include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]" 
C:/Users/circleci/project/env/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/container/parameterdict.h(51): here
```

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by ngimel** [comment]
@izdeby had similar errors on his PRs, the workaround was to trim down the includes so that only the things that are absolutely necessary are included, see discussion here https://github.com/pytorch/pytorch/pull/41554#issuecomment-665358333.

**Comment by mszhanyi** [comment]
So, it should be closed

**Comment by pbelevich** [comment]
@mszhanyi I think it should be fixed

**Comment by GregorKobsik** [comment]
Is there a `copy&paste` solution available?

As far as I could follow the related PR, there is not really a discussion, just a comment to delete the 'copy' function.

I suppose the [`commit eed8f756b0191ff73a2ef632696222555906e15d`](https://github.com/pytorch/pytorch/pull/41554/commits/eed8f756b0191ff73a2ef632696222555906e15d) 'fix build' should be the fix, but sadly this does not help my. 

I'm trying to install `fast-transformers`, which suffers from this issue here. 
Crossreference: https://github.com/idiap/fast-transformers/issues/43

**Comment by catid** [comment]
Trying to build this repo ( https://github.com/sunwj/CAR ) with MSVC 2019 Community Edition and latest stable PyTorch fails:

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include\xutility(4643): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "_OutIt std::_Move_unchecked1(_InIt, _InIt, _OutIt, std::false_type) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
(4659): here
            instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include\vector(1353): here
            instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]"
C:/Users/leon/AppData/Local/Programs/Python/Python39/lib/site-packages/torch/include\torch/csrc/api/include/torch/ordered_dict.h(419): here
            instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]"
C:/Users/leon/AppData/Local/Programs/Python/Python39/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/container/parameterdict.h(51): here

**Comment by peterjc123** [comment]
Discussion continued in https://github.com/pytorch/pytorch/issues/55266.
