### ISSUE TITLE
`torch.poisson`  documentation signature format issue.

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#43496]
#### Link

https://pytorch.org/docs/stable/generated/torch.poisson.html#torch.poisson

#### API

`torch.poisson`

#### Issue

There is an format issue in the function's signature. The input `input * ` should be `input`.

![image](https://user-images.githubusercontent.com/24580222/91066984-59d8f280-e600-11ea-87a4-8955a0144dd4.png)

Code example:

~~~python
import torch
rates = torch.rand(4, 4) * 5 
torch.poisson(input=rates)
~~~

#### **System information**

- OS: MacOS Mojave 10.14
- PyTorch version: 1.7.0.dev20200819+cpu
- Python version: 3.8.2

cc @jlin27

**Comment by ngimel** [comment]
Thank you for reporting, we'll accept a PR fixing this.

**Comment by mruberry** [comment]
@ansley Can we close this now that #45656 is in?
