### ISSUE TITLE
`torch.take`  documentation refers `indices` as an argument. 

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#43495]
#### Link

https://pytorch.org/docs/stable/generated/torch.take.html#torch.take

#### API

`torch.take`

#### Issue

In the "Parameters" section, there is an input ` indices`, but it is not in the signature, and it is not accepted by the function. It should be `index`

![image](https://user-images.githubusercontent.com/24580222/91066752-154d5700-e600-11ea-9371-a77f1a9ed16b.png)

Running code :

~~~python
import torch
src = torch.tensor([[4, 3, 5], [6, 7, 8]])
torch.take(src, indices=torch.tensor([0, 2, 5]))
~~~

gives exception 

~~~python
TypeError: take() missing 1 required positional arguments: "index"
~~~

But it throws no exception when running:

~~~python
torch.take(src, index=torch.tensor([0, 2, 5]))
~~~

#### **System information**

- OS: MacOS Mojave 10.14
- PyTorch version:  1.7.0.dev20200819+cpu
- Python version: 3.8.2

cc @jlin27

**Comment by ngimel** [comment]
Thank you for reporting, we'll accept a PR fixing this.
