### ISSUE TITLE
Issues with numpy-like broadcasting

### ISSUE THREAD

**Issue by saisrivatsan** [pytorch/pytorch#4349]
The code (attached below) throws an error when run
`x=torch.FloatTensor(5,1,4,1)`
`y=torch.FloatTensor(  3,1,1)`
`(x+y).size()`

> RuntimeError: inconsistent tensor size at /py/conda-bld/pytorch_1490981920203/work/torch/lib/TH/generic/THTensorMath.c:827

Pytorch Version: 0.1.12

This is an example that took from here: http://pytorch.org/docs/master/notes/broadcasting.html
Any idea how to get this working?

**Comment by hhsecond** [comment]
@saisrivatsan If I am not wrong, broadcasting is introduced in PyTorch 0.2 and the current PyTorch version is 0.3
An update to 0.2 or 0.3 will resolve this problem for sure.

**Comment by saisrivatsan** [comment]
Yeah, it did.
Thanks.
