### ISSUE TITLE
CPU strided array becomes huge on GPU

### ISSUE THREAD

**Issue by amatsukawa** [pytorch/pytorch#43492]
## 🐛 Bug

Creating a view of an array that contains strides, and subsequently attempting to place that array on GPU results in pytorch attempting to place a huge array on GPU. Placing the tensor first, then taking the view does not have this issue.

Apologies if this is "known" and intended behavior. Without knowing much details, it seems to me like it should be possible to place the underlying data on gpu and propagate the stride information.

## To Reproduce

```python
import torch

n = int(1e8)
a = torch.randn(n)

# this works
print(a.cuda().expand((n, n)))

# this breaks
print(a.expand((n, n)).cuda())
```

This prints:

```
tensor([[-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705],
        [-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705],
        [-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705],
        ...,
        [-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705],
        [-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705],
        [-0.3614, -0.1267, -0.2608,  ..., -0.1106, -0.9925,  0.2705]],
       device='cuda:0')
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(a.expand((n, n)).cuda())
RuntimeError: CUDA out of memory. Tried to allocate 37252902.99 GiB (GPU 0; 7.43 GiB total capacity; 0 bytes already allocated; 6.91 GiB free; 0 bytes reserved in total by PyTorch)
```

## Expected behavior

The two examples above should be equivalent.

cc @VitalyFedyunin @jamesr66a @ppwwyyxx

**Comment by ngimel** [comment]
This is expected behavior, all operations moving tensors between devices turn them into contiguous tensors (this is done to avoid opposite problem than the one you are describing, if one moves a slice of a large tensor to a device). 
Setting "triage review" to discuss under which conditions (if ever) we should preserve striding information when converting between types/devices. Note, any change here would be bc-breaking and hard to detect, so maybe not worth doing.

**Comment by amatsukawa** [comment]
Thanks for the clarification, that makes sense.

Would it be possible to introduce a `make_contiguous=True` default argument to `.cuda(...)`? That would be non-bc-breaking and we can explicitly do `.cuda(..., make_contiguous=False)` when the behavior I've described is desired.

**Comment by albanD** [comment]
I am not sure to see the benefit of this feature (given that it adds more complexity to the API).
You could create the Tensor directly on the GPU or do the expand  after moving it.
Do you have a particular use case where these wouldn't be possible?

**Comment by VitalyFedyunin** [comment]
Basically they want opposite =) to be able copy (or move) tensor with all it's strides preserved and with similarly sized storage. This is actually not the first time I'm seeing such request. Maybe we should submit feature request and let users vote on it.

**Comment by albanD** [comment]
> Basically they want opposite =)

I mean do `a = torch.randn(n, device="cuda").expand(n, n)`. So that it is clear what you want to do.
Is this really much more complex? Or are there cases where you cannot do that?
All the ops that work on size/stride/offset have the same runtime if the Tensor is on CPU or GPU anyways.

**Comment by VitalyFedyunin** [comment]
Alternative option is:

```python

def to_cuda_with_strides(t):
  cuda_storage = t.storage().cuda()
  result = torch.empty(0, device = cuda_storage.device, dtype = cuda_storage.dtype) 
  result.set_(cuda_storage, t.storage_offset(), size=t.shape, stride=t.stride())                              
  return result

```

**Comment by gchanan** [comment]
Allow `preserve` memory format to actually preserve?!

**Comment by ngimel** [comment]
numpy `astype` with the default `K` option (which means "as close to the order the array elements appear in memory as possible") does not preserve zero strides and produces memory-dense non-overlapping arrays.
If an original tensor is a slice, "preserve" can reasonably be taken to mean "preserve permutation of my tensor, but make it memory dense" (which is more or less what we and numpy do, with caveats), or "blindly copy whatever strides I have", or "use the first or the second option, whichever leads to lower memory footprint".

**Comment by amatsukawa** [comment]
The use case is purely out of convenience. I don't only use pytorch. Not taking the view in numpy means I have to reimplement this logic in each of the ML frameworks.

But I just need a way to do it, I'm totally happy to use the snippet provided by @VitalyFedyunin (thanks!). It doesn't make any difference to me whether it's in the API or not, as long as I can accomplish the task. 

Thanks for your attention!

**Comment by albanD** [comment]
Tentatively closing as the proposed solution is satisfying and we most likely don't want to make the `.to()` API even more complex than it currently is.
Feel free to re-open if you want to discuss this further.
