### ISSUE TITLE
torch.distributed.all_reduce_multigpu documentation refers `list` as an input

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#43500]
#### Link

https://pytorch.org/docs/stable/distributed.html#torch.distributed.all_reduce_multigpu

#### API

`torch.distributed.all_reduce_multigpu`

#### Issue

In the "Parameters" section, there is an input `list`, but it is not in the signature, and it is not accepted by the function. It should be `tensor_list`

![image](https://user-images.githubusercontent.com/24580222/91068305-1b443780-e602-11ea-8e9f-c065e3ac5092.png)

Running code :

~~~python
import torch
torch.distributed.all_reduce_multigpu(list=[])
~~~

gives exception 

~~~python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: all_reduce_multigpu() got an unexpected keyword argument 'list'
~~~

#### **System information**

- OS: MacOS Mojave 10.14
- PyTorch version:  1.6.0
- Python version: 3.8.2

cc @jlin27

**Comment by san7988** [comment]
Hi,

Is this fixed?

Regards

**Comment by san7988** [comment]
If okay, shall I raise a PR?
