### ISSUE TITLE
making slicing from torch.fx scriptable

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#43511]
======================================================================
ERROR: test_torchvision (quantization.test_quantize_fx.TestQuantizeFxModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/jerryzh/pytorch/test/quantization/test_quantize_fx.py", line 828, in test_torchvision
    script = torch.jit.script(graph_module)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_script.py", line 888, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 317, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 376, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 292, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:

slice(Tensor 0, Tensor 1, Tensor 2) -> (Tensor 0):
Expected a value of type 'Tensor' for argument '0' but instead found type 'None'.
:
def forward(self, x):
    self = self.root
    getitem = x[(slice(None, None, None), 0)]
                 ~~~~~ <--- HERE
    unsqueeze_1 = torch.unsqueeze(getitem, 1)
    mul_1 = unsqueeze_1 * 0.458


----------------------------------------------------------------------
Ran 1 test in 1.208s

FAILED (errors=1)

cc @gmagogsfm

**Comment by vadimkantorov** [comment]
maybe related: https://github.com/pytorch/pytorch/issues/43125

**Comment by jamesr66a** [comment]
Don't think this is an FX issue, passing over to JIT

**Comment by gmagogsfm** [comment]
Did some initial triaging, I think this is simply because our `aten::slice` doesn't match Python's slice argument type. Python slice allows `None` value while `aten::slice` doesn't.

Jerry, I can't see your original code, thus can't recommend a work-around. Do you mind sharing a bit more about the use case to help us determine work-around and priority of the bug?

**Comment by jerryzh168** [comment]
> Did some initial triaging, I think this is simply because our `aten::slice` doesn't match Python's slice argument type. Python slice allows `None` value while `aten::slice` doesn't.
> 
> Jerry, I can't see your original code, thus can't recommend a work-around. Do you mind sharing a bit more about the use case to help us determine work-around and priority of the bug?

should be reproducible by symbolic trace a googlenet and then script it I think. got the error in this test: https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_fx.py#L916

you can set model_list to googlenet in L920(https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_fx.py#L920):
```python
model_list = ['googlenet']
```
and remove https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_fx.py#L901

and then run the test:
```
python test/test_quantization.py TestQuantizeFxModels. test_torchvision
```

**Comment by gmagogsfm** [comment]
Slice support has been added. Could you sync to HEAD and try again?
