### ISSUE TITLE
MaxPool2d throwing RuntimeError for mkldnn tensor with certain parameters

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#43514]
## 🐛 Bug

Getting the following error when trying to call MaxPool2d with an mkldnn tensor created with .to_mkldnn() method.

__RuntimeError: could not create a descriptor for a pooling forward propagation primitive__

## To Reproduce

```
import torch

# Tensor Parameters
BATCH = 10
CHANNEL = 16
HEIGHT = 2048
WIDTH = 2048
DTYPE = torch.float32
DEVICE = "cpu"

# Pooling Parameters
KERNEL_SIZE = 4
STRIDE = 1
PADDING = 1
DILATION = 2
CEIL_MODE = True

blob = torch.randn(BATCH, CHANNEL, HEIGHT, WIDTH, dtype=DTYPE, device=DEVICE)

model = torch.nn.MaxPool2d(KERNEL_SIZE, STRIDE, PADDING, DILATION, False, CEIL_MODE)
model(blob.to_mkldnn())
```

## Expected behavior

Should compute max_pool2d correctly.

## Environment

Collecting environment information...
PyTorch version: 1.7.0a0+ccce112
Is debug build: False
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0a0+ccce112
[conda] blas                      1.0                         mkl  
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] torch                     1.7.0a0+ccce112           dev_0    <develop>

## Additional context

I'm working on improving the pooling code so I'll look into this issue.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by ngimel** [comment]
Out of curiosity, what RuntimeError are you getting?

**Comment by heitorschueroff** [comment]
> Out of curiosity, what RuntimeError are you getting?

RuntimeError: could not create a descriptor for a pooling forward propagation primitive

**Comment by XiaobingSuper** [comment]
What I know is that OneDNN not support dilation pooling before, and should report a error to user for dilation case. I will double check it.

**Comment by XiaobingSuper** [comment]
@heitorschueroff @ngimel, we will throw a error which say OneDNN not support dilation case for dilation max_pooling now. Please help review https://github.com/pytorch/pytorch/pull/43538.
