### ISSUE TITLE
[JIT] test_dropout_module_requires_grad failed

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#43568]
## 🐛 Bug

```bash
$ PYTORCH_TEST_WITH_SLOW=1 python test/test_jit_profiling.py TestJit.test_dropout_module_requires_grad
E
======================================================================
ERROR: test_dropout_module_requires_grad (test_jit.TestJit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xwang/Developer/pytorch/torch/testing/_internal/common_utils.py", line 501, in wrapper
    fn(*args, **kwargs)
  File "/home/xwang/Developer/pytorch/test/test_jit.py", line 1455, in test_dropout_module_requires_grad
    FileCheck().check("aten::bernoulli_").run(scripted.graph_for(X, profile_and_replay=True))
RuntimeError: Expected to find "aten::bernoulli_" but did not find it
Searched string:
graph(%self : __torch__.test_jit.MyModule,
~~~~~~~~~~~~~~~~ <--- HERE
      %input.1 : Tensor):
  %2 : float = prim::Constant[value=0.5]() # /home/xwang/Developer/pytorch/torch/nn/modules/dropout.py:58:32
From CHECK: aten::bernoulli_


----------------------------------------------------------------------
Ran 1 test in 0.375s

FAILED (errors=1)
```

## To Reproduce

```bash
PYTORCH_TEST_WITH_SLOW=1 python test/test_jit_profiling.py TestJit.test_dropout_module_requires_grad
```

## Expected behavior

Not fail

## Environment

Collecting environment information...
PyTorch version: 1.7.0a0+87905b5
Is debug build: False
CUDA used to build PyTorch: 11.0

OS: Fedora 31 (Workstation Edition) (x86_64)
GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Clang version: 7.0.1 (Fedora 7.0.1-6.fc29)
CMake version: version 3.15.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 450.51.05
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.0.1
/usr/lib64/libcudnn_adv_infer.so.8.0.1
/usr/lib64/libcudnn_adv_train.so.8.0.1
/usr/lib64/libcudnn_cnn_infer.so.8.0.1
/usr/lib64/libcudnn_cnn_train.so.8.0.1
/usr/lib64/libcudnn_ops_infer.so.8.0.1
/usr/lib64/libcudnn_ops_train.so.8.0.1

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.7.0a0+87905b5
[pip3] torchvision==0.8.0a0+446eac6
[conda] Could not collect

cc @gmagogsfm

**Comment by nikithamalgifb** [comment]
Same here removing the JIT triaged label. Feel free to re-add if needed

**Comment by desertfire** [comment]
I can not reproduce with the master build. Can anyone else give it a try?

**Comment by desertfire** [comment]
Actually this can be reproduced by commenting out https://github.com/pytorch/pytorch/blob/6997e7bd3934f9d8fa3d425336f2e20de2705358/test/test_jit.py#L1423. @Krovatkin, it looks like you made a relevant change in https://github.com/pytorch/pytorch/pull/44815, so is the failure expected here if GRAPH_EXECUTOR != ProfilingMode.LEGACY?

**Comment by Krovatkin** [comment]
Yeah, we regressed the test because at some point we weren't running the legacy tests. I turned on the legacy tests, but we didn't fix the test yet.
