### ISSUE TITLE
tensor() and Tensor() return different values for a list of bools

### ISSUE THREAD

**Issue by CamiloHernandez** [pytorch/pytorch#43565]
## 🐛 Bug

Given an array of bools calling `tensor()` yields a different tensor than calling the class constructor with `Tensor`. The `Tensor` constructor will do an implicit conversion into floats while the `tensor()` function will not. 

## To Reproduce

```python
import torch
bool_list = [True, True, False, False]

tensor1 = torch.tensor(bool_list)
tensor2 = torch.Tensor(bool_list)

print(tensor1)
# tensor([ True,  True, False, False])

print(tensor2)
# tensor([1., 1., 0., 0.])
```

## Expected behavior

According to [this post ](https://discuss.pytorch.org/t/what-is-the-difference-between-tensor-and-tensor-is-tensor-going-to-be-deprecated-in-the-future/17134/4) and the documentation, both tensors should be equal.

## Environment

```
[pip3] numpy==1.19.1
[pip3] torch==1.6.0+cu101
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect
```

 - PyTorch Version (e.g., 1.0): 1.6.0 for CUDA 10.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): Pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: RTX 2060
 - Any other relevant information: N/A

**Comment by mruberry** [comment]
Thank you for reporting this issue, @CamiloHernandez. We encourage people to use `torch.tensor` and not `torch.Tensor`, but I think we would take a PR fixing this behavior, anyway, since it's so clearly wrong.

**Comment by kshitij12345** [comment]
> torch.Tensor is a kind of mixture between torch.empty and torch.tensor , but when pass in data, torch.Tensor uses a global default dtype, torch.tensor infers data type from data

Based on the above comment, I think the output is expected?!
`torch.Tensor` makes it float while `torch.tensor` correctly infers the type to be `boolean`

Comment Link:
https://discuss.pytorch.org/t/what-is-the-difference-between-tensor-and-tensor-is-tensor-going-to-be-deprecated-in-the-future/17134/7?u=kshitij

**Comment by CamiloHernandez** [comment]
I understand your point, but I think It's rather confusing and bug-prone to have two nearly identical calls that are supposed to have the same results in most cases but not on this one. It just leads to trouble.

The post you linked does mention that `torch.Tensor` is sort of legacy though. If no changes in behavior are made I would propose that this is better documented, since the current docs make it look like both `torch.Tensor` and `torch.tensor()` yield the same results.

**Comment by mruberry** [comment]
We would always a PR improving our documentation, but the current version of torch.Tensor's documentation points, correctly, to alternatives like torch.tensor:

https://pytorch.org/docs/master/tensors.html?highlight=torch%20tensor#torch.Tensor

It is confusing. Another problem with changing type inference for torch.Tensor, however, would be backwards-compatibility, where people may be relying on it always returning float.

**Comment by CamiloHernandez** [comment]
Ok, I see.  I'll close the issue then. Thanks for your time @mruberry and @kshitij12345.
