### ISSUE TITLE
Which torch version is this?

### ISSUE THREAD

**Issue by beew** [pytorch/pytorch#43574]
I cloned the git repository and checkout the v1.4 branch(git checkout -b origin/v1.4) but after compilation and installation successfully the torch version is displayed as 1.7.0xxxx by pip list.

But
```
$ python
Python 3.7.9 (default, Aug 24 2020, 16:50:14) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.4.0'
```

So which version do I have really?

**Comment by erip** [comment]
Sounds like you may have installed it multiple times. What happens if you `pip uninstall pytorch` and try `python -c "import torch; print(torch.__version__)"` again?

**Comment by beew** [comment]
You are right, there are two versions installed, somehow the first time pip uninstall torch didn't uninstall 1.4.0 installed from pip and pip list showed my compiled version. 
Now the question is why is my compiled version is 1.7.0XXX even though I checkout the 1.4.0 branch?
Thanks

**Comment by mruberry** [comment]
It looks like PyTorch 1.4 was correctly installed (per `torch.__version`) and it's difficult to comment on what's happening with pip.

Maybe try creating a new conda environment or scrub your PyTorch installs?

**Comment by beew** [comment]
Turns out need to export PYTORCH_BUILD_VERSION=1.4.0 PYTORCH_BUILD_NUMBER=1  for the version to be reported correctly.
https://github.com/pytorch/pytorch/issues/9926
This should be better documented.
