### ISSUE TITLE
Cannot allocate new tensor of type qint8

### ISSUE THREAD

**Issue by isaacrob** [pytorch/pytorch#43593]
## 🐛 Bug

I want to allocate a new quantized tensor with torch.qint8 type, but this raises an error. More importantly, in my network I run `q_vec.sum(1)` to sum across channels, and it crashes when it tries to allocate an empty quantized vector to hold the sum.

## To Reproduce

`import torch`
`vec = torch.zeros(10, 10, dtype=torch.qint8)`

This raises error:

`RuntimeError: Could not run 'aten::empty.memory_format' with arguments from the 'QuantizedCPU' backend. 'aten::empty.memory_format' is only available for these backends: [CPU, CUDA, MkldnnCPU, SparseCPU, SparseCUDA, BackendSelect, Autograd, Profiler, Tracer].`

## Expected behavior

I would expect to be able to create new vectors of the torch.qint8 type without a crash. 

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1050
Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.6.0
[pip3] torch-scatter==2.0.5
[pip3] torch-stft==0.1.4
[pip3] torchaudio==0.5.0
[pip3] torchcontrib==0.0.2
[pip3] torchtext==0.6.0
[pip3] torchvision==0.6.0
[conda] Could not collect

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
This won't be supported actually, please take a look at https://github.com/pytorch/pytorch/wiki/Introducing-Quantized-Tensor for how to create quantized tensors.

Closing now, feel free to reopen if you have more questions.

**Comment by jerryzh168** [comment]
are you calling sum on a quantized tensor? it's probably not supported right now, feel free to open an issue for that.
