### ISSUE TITLE
Windows nightly build failed (CUDA + DEBUG + LIBTORCH)

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#43607]
## 🐛 Bug

```
   Creating library lib\torch_cuda.lib and object lib\torch_cuda.exp
kernel_cache.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class c10::optional<class std::vector<class c10::optional<struct c10::Stride>,class std::allocator<class c10::optional<struct c10::Stride> > > > const & __cdecl c10::VaryingShape<struct c10::Stride>::sizes(void)const " (__imp_?sizes@?$VaryingShape@UStride@c10@@@c10@@QEBAAEBV?$optional@V?$vector@V?$optional@UStride@c10@@@c10@@V?$allocator@V?$optional@UStride@c10@@@c10@@@std@@@std@@@2@XZ) referenced in function "public: bool __cdecl torch::jit::fuser::cuda::GraphCache::InputsRequirement::complyWith(struct torch::jit::fuser::cuda::GraphCache::InputsRequirement const &)" (?complyWith@InputsRequirement@GraphCache@cuda@fuser@jit@torch@@QEAA_NAEBU123456@@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: class c10::optional<class std::vector<class c10::optional<__int64>,class std::allocator<class c10::optional<__int64> > > > const & __cdecl c10::VaryingShape<__int64>::sizes(void)const " (__imp_?sizes@?$VaryingShape@_J@c10@@QEBAAEBV?$optional@V?$vector@V?$optional@_J@c10@@V?$allocator@V?$optional@_J@c10@@@std@@@std@@@2@XZ)
    "__declspec(dllimport) public: class c10::optional<class std::vector<struct c10::ShapeSymbol,class std::allocator<struct c10::ShapeSymbol> > > __cdecl c10::SymbolicShape::sizes(void)const " (__imp_?sizes@SymbolicShape@c10@@QEBA?AV?$optional@V?$vector@UShapeSymbol@c10@@V?$allocator@UShapeSymbol@c10@@@std@@@std@@@2@XZ)
    "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl at::Tensor::sizes(void)const " (__imp_?sizes@Tensor@at@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
    "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl caffe2::Tensor::sizes(void)const " (__imp_?sizes@Tensor@caffe2@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
    "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl at::TensorGeometry::sizes(void)const " (__imp_?sizes@TensorGeometry@at@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
    "__declspec(dllimport) public: virtual class c10::ArrayRef<__int64> __cdecl c10::TensorImpl::sizes(void)const " (__imp_?sizes@TensorImpl@c10@@UEBA?AV?$ArrayRef@_J@2@XZ)
    "__declspec(dllimport) public: struct c10::VaryingShape<__int64> __cdecl c10::TensorType::sizes(void)const " (__imp_?sizes@TensorType@c10@@QEBA?AU?$VaryingShape@_J@2@XZ)
bin\torch_cuda.dll : fatal error LNK1120: 1 unresolved externals
[2572/2852] Building CXX object caffe2\CMakeFiles\cuda_apply_test.dir\__\aten\src\ATen\test\cuda_apply_test.cpp.obj
```

https://app.circleci.com/pipelines/github/pytorch/pytorch/204288/workflows/edb87b97-9498-4f1b-98b1-165e7b433f1c/jobs/6925240
https://app.circleci.com/pipelines/github/pytorch/pytorch/203882/workflows/24b1f285-5286-4884-9fad-e49d9c186ff0/jobs/6915769

cc @ezyang @gchanan @zou3519 @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mruberry** [comment]
From the linked logs looks like a MAGMA issue:

```
[2571/2852] Linking CXX shared library bin\torch_cuda.dll
FAILED: bin/torch_cuda.dll lib/torch_cuda.lib 
cmd.exe /C "cd . && C:\w\b\windows\conda\envs\py37\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cuda.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp  /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /debug /INCREMENTAL:NO   && cd ."
LINK: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /debug /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cuda.dll.manifest" failed (exit code 1120) with the following output:
magma.lib(get_nb.cpp.obj) : warning LNK4099: PDB 'magma.pdb' was not found with 'magma.lib(get_nb.cpp.obj)' or at 'C:\w\b\windows\pytorch\build\build\bin\magma.pdb'; linking object as if no debug info
magma.lib(dgeev.cpp.obj) : warning LNK4099: PDB 'magma.pdb' was not found with 'magma.lib(dgeev.cpp.obj)' or at 'C:\w\b\windows\pytorch\build\build\bin\magma.pdb'; linking object as if no debug info
```

**Comment by peterjc123** [comment]
@mruberry No, it has nothing to do with magma. The warning is just about debug info since I compiled MAGMA with `/Zi`.

**Comment by alistairskirk** [comment]
Any progress on this? Anything I can do to help or is there a quick workaround?
I tried locally commenting out parts of kernel_cache.cpp that I thought would be causing this, but no success.

Appreciating any feedback and all your hard work :)

I am getting these errors when trying to build using Visual Studio 2019, Windows 10, CUDA 11 + CUDNN, latest pull of pytorch.

>  [3034/3155] Linking CXX shared library bin\torch_cuda.dll
>   FAILED: bin/torch_cuda.dll lib/torch_cuda.lib 
>   cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cuda.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp  /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /debug /INCREMENTAL:NO   && cd ."
>   LINK: command "C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /debug /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cuda.dll.manifest" failed (exit code 1120) with the following output:
>      Creating library lib\torch_cuda.lib and object lib\torch_cuda.exp
> D:\Projects\PyTorch\pytorch\out\build\x64-Debug\kernel_cache.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class c10::optional<class std::vector<class c10::optional<struct c10::Stride>,class std::allocator<class c10::optional<struct c10::Stride> > > > const & __cdecl c10::VaryingShape<struct c10::Stride>::sizes(void)const " (__imp_?sizes@?$VaryingShape@UStride@c10@@@c10@@QEBAAEBV?$optional@V?$vector@V?$optional@UStride@c10@@@c10@@V?$allocator@V?$optional@UStride@c10@@@c10@@@std@@@std@@@2@XZ) referenced in function "public: bool __cdecl torch::jit::fuser::cuda::GraphCache::InputsRequirement::complyWith(struct torch::jit::fuser::cuda::GraphCache::InputsRequirement const &)" (?complyWith@InputsRequirement@GraphCache@cuda@fuser@jit@torch@@QEAA_NAEBU123456@@Z)
>     Hint on symbols that are defined and could potentially match:
>       "__declspec(dllimport) public: class c10::optional<class std::vector<class c10::optional<__int64>,class std::allocator<class c10::optional<__int64> > > > const & __cdecl c10::VaryingShape<__int64>::sizes(void)const " (__imp_?sizes@?$VaryingShape@_J@c10@@QEBAAEBV?$optional@V?$vector@V?$optional@_J@c10@@V?$allocator@V?$optional@_J@c10@@@std@@@std@@@2@XZ)
>       "__declspec(dllimport) public: class c10::optional<class std::vector<struct c10::ShapeSymbol,class std::allocator<struct c10::ShapeSymbol> > > __cdecl c10::SymbolicShape::sizes(void)const " (__imp_?sizes@SymbolicShape@c10@@QEBA?AV?$optional@V?$vector@UShapeSymbol@c10@@V?$allocator@UShapeSymbol@c10@@@std@@@std@@@2@XZ)
>       "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl at::Tensor::sizes(void)const " (__imp_?sizes@Tensor@at@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
>       "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl caffe2::Tensor::sizes(void)const " (__imp_?sizes@Tensor@caffe2@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
>       "__declspec(dllimport) public: class c10::ArrayRef<__int64> __cdecl at::TensorGeometry::sizes(void)const " (__imp_?sizes@TensorGeometry@at@@QEBA?AV?$ArrayRef@_J@c10@@XZ)
>       "__declspec(dllimport) public: virtual class c10::ArrayRef<__int64> __cdecl c10::TensorImpl::sizes(void)const " (__imp_?sizes@TensorImpl@c10@@UEBA?AV?$ArrayRef@_J@2@XZ)
>       "__declspec(dllimport) public: struct c10::VaryingShape<__int64> __cdecl c10::TensorType::sizes(void)const " (__imp_?sizes@TensorType@c10@@QEBA?AU?$VaryingShape@_J@2@XZ)
> D:\Projects\PyTorch\pytorch\out\build\x64-Debug\bin\torch_cuda.dll : fatal error LNK1120: 1 unresolved externals
