### ISSUE TITLE
Missing common.sh

### ISSUE THREAD

**Issue by Daniel-Kelvich** [pytorch/pytorch#43615]
## Error while building pytorch adnroid
I've been following the official guide for building pytorch for android from source, but got the following error:
`./scripts/build_pytorch_android.sh: 30: source: not found`
Seems that it is common.sh file that missing.

**Comment by fcqfcq** [comment]
sh is bash ?
sh -> bash

**Comment by mauricewells** [comment]
i also got the same as above

**Comment by mauricewells** [comment]
I solved that error
we should use the following command "bash ./scripts/build_pytorch_android.sh" instead of "sh ./scripts/build_pytorch_android.sh"
