### ISSUE TITLE
Libtorch : Comparing identical shapes(sizes) always returns false when in debug mode

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#43611]
## 🐛 Bug

During debug mode, the shape comparison always returns false! during release it works fine!
![libtorch_debug_bug](https://user-images.githubusercontent.com/5382892/91268435-96d0f080-e78a-11ea-9ad9-649f13cf4cd6.gif)

## To Reproduce

```cpp
Run it onece under Debug mode and then under Release mode: 
void test14()
{
    auto tensor = torch::ones({ 3,3 }).sizes();
    auto status = tensor == c10::IntArrayRef{ 3,3 };
    auto status_2 = tensor.equals(c10::IntArrayRef{ 3,3 });

    std::cout << "Comparing tensor shapes: " << std::endl;
    std::cout << "auto tensor = torch::ones({ 3,3 });" << std::endl;
    std::cout << "tensor.sizes() == c10::IntArrayRef{ 3,3 } is " << std::boolalpha << status << std::endl;
    std::cout << "tensor.equals(c10::IntArrayRef{ 3,3 }) is " << std::boolalpha << status_2 << std::endl;

}
```
it outputs : 
debug mode: 
```
Comparing tensor shapes:
auto tensor = torch::ones({ 3,3 });
tensor.sizes() == c10::IntArrayRef{ 3,3 } is false
tensor.equals(c10::IntArrayRef{ 3,3 }) is false
```
release mode: 
```
Comparing tensor shapes:
auto tensor = torch::ones({ 3,3 });
tensor.sizes() == c10::IntArrayRef{ 3,3 } is true
tensor.equals(c10::IntArrayRef{ 3,3 }) is true
```
## Expected behavior

must not act like this!

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.6
 - OS (e.g., Linux): Windows 10 -1803
 - How you installed PyTorch (`conda`, `pip`, source): pytorch using pip and libtorch is the prebuilt downloaded form pytorch.org
 - Build command you used (if compiling from source):-
 - Python version: 3.7
 - CUDA/cuDNN version: - 
 - GPU models and configuration: - 
 - Any other relevant information: I'm using the cpu mode ! 

## Additional context

Using Visual Studio 2019 Community edition if thats of any use! and I'm using C++17 flag in the compiler settings. 

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Is the API usage correct? cc @glaringlee

**Comment by glaringlee** [comment]
@peterjc123 I think the API usage is correct. 
I guess the problem is that @Coderx7 linked his code with the libtorch binary which was built using Release Flag, but he linked his cpp code with Debug flag. Do you have env to try? thx

**Comment by Coderx7** [comment]
@glaringlee this might be it, but I'm sure I set everything up correctly, the libs folders are separate and they are setup differently both for debug and release builds. also all the libs for debug is present next to the executable file. 
I however, added the release build folder to the PATH. not sure if thats the culprit or not! knowing that all debug dlls.libs are already next to the debug executable and so far I havent had any issues with it! 

pn: it would be grate to have different names for debug and release versions of the libs, like in opencv and lots of other libraries, this will prevent mindbugling issues like this in first place! cant you do just that? and ship debug build with a different name (like c10**d**.dll instead of c10.dll for both build modes? )

**Comment by glaringlee** [comment]
@Coderx7 
Thanks for your suggestion. 
We currently separated the entire build package by build version already on pytorch.org, people can choose Release or Debug to download and setup their path/env correctly. We never have user complained about this before, probably because user normally need only one version. 
To add a set of lib names for Debug version only, there will be a not trivial change to our build scripts and this will be a backward-compatible breaking change, people who linked with our DEBUG version lib (using their own makefile) will all be broken. We will discuss this suggestion, but this won't be a short term change.

**Comment by Coderx7** [comment]
@glaringlee Thanks a lot its really appreciated. its specially a bliss for for projects involving other vision libraries that may have extremely slow debug builds, and for development you have to constantly switch between the two to get by!

**Comment by Coderx7** [comment]
I rechecked the libs and headers for debug and they refer to the debug builds 100%. I also removed the libs folder from PATH and tried again and this still returns false for debug build. 
What should I do more to get you more information concerning this?

**Comment by glaringlee** [comment]
@Coderx7 If this is not related to lib mismatch, this might related to the way DEBUG Mode works.
Can you print out the result of each step of your code? just use cout, and please print out `c10::IntArrayRef{ 3,3 }` as well.

@peterjc123 Can you help to reproduce this on windows and if this is reproduce-able, can you help investigate a bit?

**Comment by Coderx7** [comment]
@glaringlee I couldnt replicate this issue in a new project. even the very same project that exibits this issue, doesnt behave incorrectly when copied and executed from another location in the same system. This makes me to come to the conclusion  that this might be very well a Visual Studio 2019 issue of some kind! Despite my attempts, I couldnt find out the cause so I close this issue and will reopen it in case I find something new. 
Thanks a lot for your generous time and kind help.
