### ISSUE TITLE
Model loader with cuda and data parallel

### ISSUE THREAD

**Issue by antspy** [pytorch/pytorch#4361]
Hi, 

it would be nice if the model loader would not care whether the weights were saved with cpu, cuda or data parallel and just accept everything in input.

So if model is on cpu and weights were saved on data parallel, the weight are automatically transformed to cpu and loaded. If the model is on data parallel and the weights were saved from cuda, they are loaded correctly and automatically assigned to the data parallel model, and so on.

It is of course possible to do this manually by simply transforming the dictionary keys and calling .cpu() or .cuda() on the weights, but I think it would be cleaner if it was inside load_state_dict.

What do you think?

**Comment by apaszke** [comment]
I'm not sure if I understand the proposal. Currently `torch.load` will restore the weights in exact same location where they were at save time. You can change this behavior using `map_location` argument.

**Comment by antspy** [comment]
Hi, 

I typically use torch.load_state_dict to save the model weights; I think this is cleaner and less error prone than saving the whole class with torch.save - torch.load. 
So, if I train a model on multiple GPUs and then want to evaluate on a single GPU (or viceversa), I will have to manually convert the state dict. For example:

```
>>> a = nn.Linear(40, 50)
>>> b = a.state_dict()
>>> a_parallel = nn.parallel.DataParallel(a)
>>> a_parallel.load_state_dict(b)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "weight" in state_dict'
```

It is easy enough to just change b so that it is accepted by load_state_dict, but it would be nicer if this was done inside load_state_dict automatically :-)

**Comment by apaszke** [comment]
We don't want to make `load_state_dict` do any pattern matching for DataParallel keys, because that would complicate the contract. We've thought about this a few times, but always concluded that we prefer the way it is right now. Thanks for the proposal!

**Comment by dhpollack** [comment]
@apaszke, I don't think you have to do any pattern matching.  One would just have to change the `state_dict` function to save the actual state of the module in DataParallel rather than saving from `self`

It seems pretty clear people have issues with this.  See discussions on the pytorch message board [here](https://discuss.pytorch.org/t/dataparallel-optim-and-saving-correctness/4054) (where even @soumith seems confused) and [here](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/)

The fix would be simple:

```python
class Module(object):
    ...
    def state_dict(self, destination=None, prefix='', keep_vars=False):
        own_state = self.module if isinstance(self, torch.nn.DataParallel) \
                    else self
        if destination is None:
            destination = OrderedDict()
        for name, param in own_state._parameters.items():
            if param is not None:
                destination[prefix + name] = param if keep_vars else param.data
        for name, buf in own_state._buffers.items():
            if buf is not None:
                destination[prefix + name] = buf
        for name, module in own_state._modules.items():
            if module is not None:
                module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
        return destination

    def load_state_dict(self, state_dict, strict=True):
        own_state = self.module.state_dict() if isinstance(self, torch.nn.DataParallel) \
                    else self.state_dict()
        for name, param in state_dict.items():
            if name in own_state:
                if isinstance(param, Parameter):
                    # backwards compatibility for serialized parameters
                    param = param.data
                try:
                    own_state[name].copy_(param)
                except Exception:
                    raise RuntimeError('While copying the parameter named {}, '
                                       'whose dimensions in the model are {} and '
                                       'whose dimensions in the checkpoint are {}.'
                                       .format(name, own_state[name].size(), param.size()))
            elif strict:
                raise KeyError('unexpected key "{}" in state_dict'
                               .format(name))
        if strict:
            missing = set(own_state.keys()) - set(state_dict.keys())
            if len(missing) > 0:
                raise KeyError('missing keys in state_dict: "{}"'.format(missing))
```

the main difference is that in `state_dict`, I'm exporting from `own_state` rather than always from `self`.  You'd just need to create a mini utility that people could use to remove the "module." from the key names of previously saved DataParallel modules.

**Comment by root-master** [comment]
If you want to load the weights after `DataParallel` use:
`net.module.load_state_dict(pertained_weights)
`If you want to load the weights before `DataParallel` use:
`net.load_state_dict(pertained_weights)`

**Comment by fyting** [comment]
> If you want to load the weights after `DataParallel` use:
> `net.module.load_state_dict(pertained_weights)`
> 
> If you want to load the weights before `DataParallel` use:
> `net.load_state_dict(pertained_weights)`

What is the meaning of "net."?

**Comment by dhpollack** [comment]
It's just a python variable name that the user assigns to this particular network. It has no significance.

**Comment by fyting** [comment]
I get it, thank you.

**Comment by fermat97** [comment]
@root-master @dhpollack  Can we do something `net.module.load_state_dict(pertained_weights) ` for the optimizer?

**Comment by dhpollack** [comment]
@fermat97 this is not the right place to be asking these questions.  You should go to the pytorch forums.

https://discuss.pytorch.org/t/saving-and-loading-a-model-in-pytorch/2610/3

That discussion seems to be what you are looking for.

**Comment by phamquiluan** [comment]
> If you want to load the weights after `DataParallel` use:
> `net.module.load_state_dict(pertained_weights)`
> 
> If you want to load the weights before `DataParallel` use:
> `net.load_state_dict(pertained_weights)`

problem solved =))

**Comment by hkair** [comment]
> If you want to load the weights after `DataParallel` use:
> `net.module.load_state_dict(pertained_weights)`
> 
> If you want to load the weights before `DataParallel` use:
> `net.load_state_dict(pertained_weights)`

Is this is assuming the pre-trained weights are saved in cpu?
