### ISSUE TITLE
Unable to load onnx model exported with use_external_data_format=True Flag

### ISSUE THREAD

**Issue by rajeevbaalwan** [pytorch/pytorch#43610]
I'm trying to convert transformer encoder decoder model to onnx format but unable to export it in a single file, as protobuf capacity is limited to 2GB only
But pytorch allows to save onnx model to external data format
here is the doc for this parameter :

>external_data_format (bool, default False) – If True, then the model is exported in ONNX external data format, in which case some of the model parameters are stored in external binary files and not in the ONNX model file itself. See link for format details: https://github.com/onnx/onnx/blob/8b3f7e2e7a0f2aba0e629e23d89f07c7fc0e6a5e/onnx/onnx.proto#L423 Also, in this case, argument ‘f’ must be a string specifying the location of the model. The external binary files will be stored in the same location specified by the model location ‘f’. If False, then the model is stored in regular format, i.e. model and parameters are all in one file. This argument is ignored for all export types other than ONNX.

This is how i exported the model :
```
def convert_to_onnx(features):
    import torch.onnx
    torch.onnx.export(model,
                      features,
                      '/home/rajeev/pb/espnet/agent_model/onnx_model/model_aten.onnx',
                      input_names= ['features'],
                      output_names=['hyp_text'],
                      dynamic_axes={
                          'features':{0:'batch_size',1: 'time_steps'},
                          'hyp_text':{0:'batch_size'}
                      },
                      verbose=True,
                      opset_version=12,
                      # operator_export_type= torch.onnx.OperatorExportTypes.ONNX_ATEN,
                      use_external_data_format=True,
                      enable_onnx_checker=True,
                      do_constant_folding=True
                      )
```

total size of all the files exported are of 9 GB and my actual model was of 1 GB.
/home/rajeev/pb/espnet/agent_model/onnx_model folder contains 5344 exported files along with model_aten.onnx file having size of only 4MB.

But when I am trying to load the model I am getting this error :

```
Error while loading the model: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/optimizer_execution_frame.cc:61 onnxruntime::OptimizerExecutionFrame::Info::Info(const std::vector<const onnxruntime::Node*>&, const InitializedTensorSet&, std::unique_ptr<onnxruntime::CPUExecutionProvider>) [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid fd was supplied: -1
```
Here is the way i am trying to load the model:

```
try:
    onnx_options = SessionOptions()
    _ = InferenceSession(path, onnx_options)
    print("Model correctly loaded")
except RuntimeException as re:
    print("Error while loading the model: {}".format(re))
```
I have not found any good solution for this.
Please me out achieving this.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@rajeevbaalwan - am I correct in understanding that the export call executes, but this error is when loading the model in ONNXRuntime. If yes, I would recommend opening an issue in the ONNXRuntime repo.

**Comment by garymm** [comment]
Related: https://github.com/microsoft/onnxruntime/issues/6696

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
