### ISSUE TITLE
[jit] Runtime crash of freezed module caused by tensor that is not contiguous.

### ISSUE THREAD

**Issue by chenbohua3** [pytorch/pytorch#43620]
## To Reproduce
```
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer1 = torch.nn.Conv2d(3, 32, 1, 1)
     
    def forward(self, x):
        x = self.layer1(x)
        return x

model = MyModel().eval().cuda()

shape = [1, 3, 32, 32]
stride = (3072, 1, 96, 3)
dummy_input = torch.randn(shape).as_strided(shape, strides).cuda()
traced_module = torch.jit.trace(model, dummy_input)
freeze_module = torch._C._freeze_module(traced_module._c)
freeze_module.forward(dummy_input)
```
Then we will get:
```
RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

BTW, codes above work well on cpu but will crash on gpu. If stride becomes  `(3072, 1, 3, 96)`, work well on both devices.

## Environment

 - PyTorch Version (e.g., 1.0): master(2b70f827373fe5c90e15ce7ba0a1d331dcd57379)
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): described [here](https://github.com/pytorch/pytorch#from-source)
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.0/7.6.5

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
@bzinodev This sounds like something in your area of expertise, could you help take a look?

**Comment by bzinodev** [comment]
Does it work without freezing?

**Comment by chenbohua3** [comment]
yes, it works without freezing

**Comment by eellison** [comment]
@chenbohua3 I  could  not  repro  this on master, closing.  Please re-open if  this still repros for you on master.
