### ISSUE TITLE
Add a torch.hub.load_local() function that can load models from any local directory with a hubconf.py

### ISSUE THREAD

**Issue by AdeelH** [pytorch/pytorch#43622]
## 🚀 Feature
A `torch.hub.load_local()` function that can load models from any local directory with a `hubconf.py`.

## Motivation
`torch.hub.load()` currently allows loading model definitions from a GitHub repo that has a `hubconf.py` file. It does this by downloading the repo, and then loading functions from `hubconf.py`.

Since it only accepts locations of the form `<repo_owner>/<repo_name>`, it is limited to repos hosted on Github.

This means it does not support the following functionality/use cases:
- The ability to use `torch.hub` on machines that do not have internet access.
- The ability to archive model definition code locally.
- The ability to load models from local directories without having to push them to Github, especially during development when you want to quickly test out the changes you make to the model definition code.

## Pitch
It will cover the above use cases.

`torch.hub.load_local()` should be trivial to implement. It will have the same signature as `torch.hub.load()`, with the first argument, `github`, replaced by `repo_dir` (which will be a local path). In terms of code, the only difference from `torch.hub.load()` will be the removal of the line that downloads the GitHub repo (https://github.com/pytorch/pytorch/blob/master/torch/hub.py#L343) and the associated `force_reload` argument (https://github.com/pytorch/pytorch/blob/master/torch/hub.py#L338).

I would probably be implementing this functionality for [azavea/raster-vision#975](https://github.com/azavea/raster-vision/issues/975) and would be happy to open a PR here, if there is interest.

## Alternatives

A more general, though harder to implement, solution would be a `torch.hub.load_uri()` function that can fetch code from any URI, local or remote.

cc @ailzhang

**Comment by ailzhang** [comment]
This was considered a lower pri in our plan - we'd be happy to take a PR implementing this functionality.
