### ISSUE TITLE
[RPC] "AssertionError: Default process group is not initialized" after upgrading 1.6.0 

### ISSUE THREAD

**Issue by Lyken17** [pytorch/pytorch#43621]
I am running distributed RPC with PyTorch and I notice the following code failed to run on 1.6.0 while it excutes normally on pytorch 1.5.1.

```python
import os
import tempfile
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp
import torch.distributed.rpc as rpc


def my_script_add(*args):
    print(f"Running RPC rank {dist.get_rank()} with args {args}")
    return args


def demo_rpc(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    if rank != 0:
        rpc.init_rpc(f"worker-{rank}", rank=rank, world_size=world_size)
    else:
        rpc.init_rpc("ps", rank=rank, world_size=world_size)
        rets = []
        for idx in range(1, world_size):
            ret = rpc.rpc_sync(f"worker-{idx}", my_script_add, args=(idx,), timeout=-1.0)
            rets.append(ret)
        for ret in rets:
            print(ret.wait())
    rpc.shutdown()


if __name__ == "__main__":
    n_gpus = torch.cuda.device_count()
    world_size = 4

    # run_demo(demo_basic, 4)
    mp.spawn(demo_rpc,
             args=(world_size,),
             nprocs=world_size,
             join=True)
```

Code above raises error 
```
AssertionError: On WorkerInfo(id=1, name=worker-1):
AssertionError('Default process group is not initialized',)
Traceback (most recent call last):
  File "/home/ligeng/anaconda3/lib/python3.6/site-packages/torch/distributed/rpc/internal.py", line 163, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/NFS/home/ligeng/Workspace/OFA/pth_rpc_toy.py", line 12, in my_script_add
    print(f"Running RPC rank {dist.get_rank()} with args {args}")
  File "/home/ligeng/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 598, in get_rank
    _check_default_pg()
  File "/home/ligeng/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jjlilley

**Comment by mrshenli** [comment]
Hey @Lyken17 

We decoupled `init_rpc` from `init_process_group` in v1.6 to gradually remove RPC's dependency on ProcessGroup. Because they were design for different use cases, where RPC is for P2P comm and ProcessGroup is collective comm. So with v1.6, you will need to manually call `init_process_group`, sorry about the inconvenience.

**Comment by Lyken17** [comment]
Oh, that's breaking change. Can you give an example of the usage 1.6.0? I tried to call `dist. init_process_group` and then `rpc.init_rpc`, but it shows the address is already used.

**Comment by mrshenli** [comment]
Sure. Since ProcessGroup and RPC will have their own rendezvous stores, they will need to use different master port. Here is an example: https://pytorch.org/tutorials/advanced/rpc_ddp_tutorial.html.  Search for 29500 and 29501.

> since the docs are not updated? 

Could you please point me to the doc? I will update those.

**Comment by mrshenli** [comment]
Looking at your code snippet again, if you are not using collective communication APIs (e.g., `all_gather`, `all_reduce`), you don't need to call `init_process_group` to initialize `ProcessGroup` instances. If you only want to get the rank of the current RPC process, you can use `rpc.get_worker_info().id`. See the following API doc:

https://pytorch.org/docs/master/rpc.html#torch.distributed.rpc.get_worker_info 

Note that the rank you got from `dist.get_rank()` is actually from a different world (the ProcessGroup), and there is no guarantee it will always be the same as the RPC rank/id, especially after we enable elasticity in RPC.
