### ISSUE TITLE
[jit] determine whether ModuleList is empty or its length

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#43624]
## 🐛 Bug

There seems to be no way to test whether a ModuleList is empty or to get its length in Torchscript

## To Reproduce
```py
from typing import Final

import torch


class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.layers: Final = torch.nn.ModuleList([torch.nn.Linear(1, 1)])

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for layer in self.layers[:-1]:
            x = layer.forward(x)
        if len(self.layers) > 0:
            x = self.layers[-1].forward(x)
        return x


model_jit = torch.jit.script(Test())
```
```python-traceback
~/miniforge3/envs/panama/lib/python3.8/site-packages/torch/jit/_recursive.py in create_methods_from_stubs(concrete_type, stubs)
    290     rcbs = [m.resolution_callback for m in stubs]
    291     defaults = [get_default_args(m.original_method) for m in stubs]
--> 292     concrete_type._create_methods(defs, rcbs, defaults)
    293 
    294 def create_script_module(nn_module, stubs_fn, share_types=True):

RuntimeError: 
Tried to access nonexistent attribute or method '__len__' of type '__torch__.torch.nn.modules.container.ModuleList'. Did you forget to initialize an attribute in __init__()?:
  File "/pool01/home/twoertwe/test.py", line 15
        for layer in self.layers[:-1]:
            x = layer.forward(x)
        if len(self.layers) > 0:
           ~~~ <--- HERE
            x = self.layers[-1].forward(x)
        return x
```

## Expected behavior

There should be a simple way to check the length of a ModuleList.

## Environment
<details>
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2~16.04) 9.3.0
Clang version: 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
CMake version: version 3.15.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr0/local/cuda-9.0/lib64/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip3] hamiltorch==0.3.1.dev3
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] libblas                   3.8.0                    16_mkl    conda-forge
[conda] libcblas                  3.8.0                    16_mkl    conda-forge
[conda] liblapack                 3.8.0                    16_mkl    conda-forge
[conda] liblapacke                3.8.0                    16_mkl    conda-forge
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.1           py38hbc911f0_0  
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch
</details>

cc @gmagogsfm

**Comment by eellison** [comment]
Hi, thanks for the issue and good repro! Hmm, I thought this was fixed for 1.6. It is fixed on master, though, so closing.
```
model_jit = torch.jit.script(Test())
print(model_jit.forward.code)

def forward(self,
    x: Tensor) -> Tensor:
  if torch.gt((self.layers).__len__(), 0):
    x1 = (getattr(self.layers, "0")).forward(x, )
    x0 = x1
  else:
    x0 = x
  return x0
```

**Comment by twoertwein** [comment]
thanks @eellison for showing that it works on master!

I'm a little bit suprised that TorchScript doesn't optimize `len(self.layers) > 0`. It should know that this is always True: `self.layers` is marked as `typing.Final` and it contains one element.

**Comment by eellison** [comment]
NP! We do, just not as part of serialization / initial compilation (which is what you see with the print there), once we run the graph we do inlining & constant propagation and the `len(self.layers) > 0` if gets removed.

**Comment by twoertwein** [comment]
great! Does `.graph` reflect the optimizations?

**Comment by eellison** [comment]
No, that is the unoptimized graph. For optimizations run your model a few times and then call `torch.jit.last_executed_optimized_graph()`
