### ISSUE TITLE
Error when initializing tensor from numpy array with correct dtype.

### ISSUE THREAD

**Issue by dichotomies** [pytorch/pytorch#4363]
A minimal example:

```py
any_number = long(2)
a = np.arange(0, any_number)
print(a, a.dtype)
b = torch.from_numpy(a)
print(b)
>>> (array([0, 1]), dtype('int64'))
>>> RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. 
>>> The only supported types are: double, float, int64, int32, and uint8.
```

Although `a` has `dtype` `int64` and this type *is listed as supported*, the array can't be converted. 

Consider that `a` is initialized with an upper bound of type `long`.

I'm not completely sure, whether this issue is related to torch or numpy, but numpy initializes the array with values as expected, whereas torch throws an inconsistent error message.

**Comment by zou3519** [comment]
![image](https://user-images.githubusercontent.com/5652049/34387514-957dde88-eafc-11e7-950c-02010ad64524.png)

Works for me on master and 0.3. Seems like it could be related to #4364
