### ISSUE TITLE
Initializing tensor from numpy array results in unexpected values of tensor.

### ISSUE THREAD

**Issue by dichotomies** [pytorch/pytorch#4364]
Minimal example:
```py
any_number = long(2)
a = np.arange(0, any_number)
print(a)
b = torch.Tensor(a)
print(b)
>>> [0, 1]
>>> -5.9741e+15
>>> 4.5811e-41
>>> [torch.FloatTensor of size 2]
```

Torch initializes the tensor with values which are different from the numpy array.

I've seen issues for similar kinds of problems (see https://github.com/pytorch/pytorch/issues/3671). Maybe the easiest solution to all these initialization problems might be, to check for the same values of the original and initialized array/tensor instead of initializing tensors silently with wrong numbers. What do you think?

Furthermore, I've opened an issue which is also related this one in terms of initializing a numpy array with a number of type `long` and then initializing a torch tensor from that array, see https://github.com/pytorch/pytorch/issues/4363. Feel free to merge them if you think that both issues can be solved together.

**Comment by zou3519** [comment]
Could you please provide some information about what version of pytorch and numpy you're using?

![image](https://user-images.githubusercontent.com/5652049/34387282-37bf3018-eafb-11e7-8dea-c1fcbc30096f.png)

It works as expected for me on master

**Comment by dichotomies** [comment]
I'm using torch 0.3.0.post4 (latest one on website of PyTorch) and numpy 1.13.3.

**Comment by zou3519** [comment]
I'm running the same thing, this is strange. In the first line `any_number = long(2)`, I assumed that `long` came from `np.long`. Is this the case?

**Comment by dichotomies** [comment]
Nope, it's indeed the python built-in type. Actually this issue came up when I tried to get the shape of `Variable` (i.e. `a = torch.autograd.Variable(torch.LongTensor([1]))`, `a.shape`).

**Comment by zou3519** [comment]
Thanks for the clarification, I'm now seeing your results. Looks like the tensor constructor doesn't work well with python2.7 long types.

**Comment by dichotomies** [comment]
Sure, no problem. Thanks for looking into it!

**Comment by zou3519** [comment]
The problem seems to be that np.longlong and np.int64 are the same thing (at least on a 64bit system, I think), but the NPY_LONGLONG and NPY_INT64 macros are different...

I'll put up a pr for this soon.
