### ISSUE TITLE
Precision issue in exporting flaubert models to onnx 

### ISSUE THREAD

**Issue by wangyems** [pytorch/pytorch#43656]
## 🐛 Bug

I don't think it's a bug but something needs investigation. when converting flaubert models to onnx, there is:
Max absolute diff=0.0008344650268554688 for output tensor 0
Output tensor 0 is not close: rtol=0.0001, atol=0.0001
The diff is above the threshold, but not much.

## To Reproduce

Run onnxruntime/python/tools/transformers/run_benchmark.sh under my branch
https://github.com/microsoft/onnxruntime/tree/wangye/onnxrepo

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.7.0.dev20200811 cpuonly
 - OS (e.g., Linux):Linux
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@wangyems - since the export is happening, and this seems like a number mismatch issue, may I suggest removing a layer or two at the end of the model to try and see where the number mismatch is happening. It will help iron out whether this is an export issue or a backend issue. Also, visualizing the model in Netron may help figure out whether there is something obviously wrong in the model or not.

**Comment by garymm** [comment]
@wangyems is this causing issues? If so please elaborate.
If not, please close the issue.

**Comment by wangyems** [comment]
closed it
