### ISSUE TITLE
Make torch.nn.Hardswish ONNX exportable

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#43665]
## 🐛 Bug

torch.nn.Hardswish is not ONNX exportable

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by agolynski** [comment]
@pfeatherstone Could you provide more details about your setup, what error do you get?

**Comment by pfeatherstone** [comment]
I get the error 
```
RuntimeError: Exporting the operator hardswish to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

**Comment by pfeatherstone** [comment]
Use this to reproduce
```
    class test(nn.Module):
        def __init__(self):
            super(test, self).__init__()
            self.n = nn.Hardswish()
        def forward(self,x):
            return self.n(x)

    x = torch.rand(1)
    n = test().eval()
    y = n(x)
    out = torch.onnx.export(n,
                            (x,),
                            "test.onnx",
                            opset_version=12)
```

**Comment by pfeatherstone** [comment]
You can get around this by using 
```
class Hardswish(nn.Module):  # export-friendly version of nn.Hardswish()
    @staticmethod
    def forward(x):
        # return x * F.hardsigmoid(x)  # for torchscript and CoreML
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX
```
But pytorch told me to open a bug so here it is

**Comment by spandantiwari** [comment]
@pfeatherstone - Could you provide some details about which model(s) need this operator? That will help us prioritize. 
BTW, please consider contributing a PR to support this op.

**Comment by pfeatherstone** [comment]
Yolov5 uses it now.

**Comment by pfeatherstone** [comment]
But yolov5 uses the code I posted above. In fact it is taken verbatim from yolov5. Again I've posted this issue because pytorch told me too. I'm happy using the code above.

**Comment by spandantiwari** [comment]
Thanks for clarifying. 
That message is a generic error message to bubble up any missing ops that are used in models commonly. So thanks for reporting. If you are unblocked, that's great.

**Comment by msollami-sf** [comment]
The static solution above leaves out the inplace bool argument.

**Comment by zhiqwang** [comment]
Is there any updates here, the operator `nn.Hardswish` is also widely used in [MobileNetV3](https://arxiv.org/abs/1905.02244).

**Comment by spandantiwari** [comment]
@zhiqwang - No updates on this. We will try to prioritize this on our roadmap.

**Comment by spandantiwari** [comment]
@shubhambhokare1 has added a PR for this. Please review leave any feedback.
