### ISSUE TITLE
sphinx sometimes can not find the correct `bool`

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#43669]
I find this when working on https://github.com/pytorch/pytorch/issues/43667

If you replace the docs of `torch.bmm`
```
Args:
    input (Tensor): the first batch of matrices to be multiplied
    mat2 (Tensor): the second batch of matrices to be multiplied
    deterministic (bool, optional): flag to choose between a faster non-deterministic
                                    calculation, or a slower deterministic calculation.
                                    This argument is only available for sparse-dense CUDA bmm.
                                    Default: ``False``
    {out}
```
with
```
Args:
    input (Tensor): the first batch of matrices to be multiplied
    mat2 (Tensor): the second batch of matrices to be multiplied

Keyword args:
    deterministic (bool, optional): flag to choose between a faster non-deterministic
                                    calculation, or a slower deterministic calculation.
                                    This argument is only available for sparse-dense CUDA bmm.
                                    Default: ``False``
    {out}
```
you will get an error
```
docstring of torch.bmm:: WARNING: more than one target found for cross-reference 'bool': torch.FloatStorage.bool, torch.Tensor.bool
```

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
@mattip Any idea for how we can resolve this? It's pretty easy to be hit by.

**Comment by mattip** [comment]
Not sure. I think somehow this is triggered by the automethod/autoclass directives in [`storage.rst`](https://github.com/pytorch/pytorch/blame/master/docs/source/storage.rst#L10) and [`tensors.rst`](https://github.com/pytorch/pytorch/blame/master/docs/source/tensors.rst#L230), (why does github make linking to a line in an rst file so hard) but in both cases `bool()` is a method, not an instance. I think putting it in double back-ticks might be a work around:
```
``bool``
```

**Comment by zasdfgbnm** [comment]
```
``bool``
```
does not produce link 
![image](https://user-images.githubusercontent.com/1032377/91666839-0e698d00-eab5-11ea-8397-66f554b949a2.png)

**Comment by mattip** [comment]
I think it is OK that `bool` is not a link.
