### ISSUE TITLE
Profiler for Python 2.7

### ISSUE THREAD

**Issue by atabakd** [pytorch/pytorch#4368]
Running `prof = torch.autograd.profiler.load_nvprof('trace_name.prof')` on Python 2.7 causes an error:
`NameError: global name 'FileNotFoundError' is not defined` and according to [here](https://github.com/philkr/lpo/issues/5#issuecomment-100596671), FileNotFoundError apparently doesn't exist in python 2.7.
A simple solution that worked for me is to add to the beginning of torch/autograd/profiler.py file the following lines:

```
try:
    FileNotFoundError
except NameError:
    #py2
    FileNotFoundError = IOError
```

Which I got from [here](https://stackoverflow.com/a/21368622/850760).

PS:
I can create a PR if you agree with the solution.

Cheers,

**Comment by ezyang** [comment]
Thanks for the report. Could you post the stacktrace of the error by any chance? It doesn't look like we have any occurrences of FileNotFoundError in our code, so it may be an upstream problem.

**Comment by atabakd** [comment]
Sure. This is my full traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/**whatever**/anaconda2/lib/python2.7/site-packages/torch/autograd/profiler.py", line 232, in load_nvprof
    return EventList(parse_nvprof_trace(path))
  File "/home/**whatever**/anaconda2/lib/python2.7/site-packages/torch/autograd/profiler.py", line 392, in parse_nvprof_trace
    strings[r["id"]] = demangle(r["value"])
  File "/home/**whatever**/anaconda2/lib/python2.7/site-packages/torch/autograd/profiler.py", line 323, in demangle
    except (subprocess.CalledProcessError, OSError, FileNotFoundError) as e:
NameError: global name 'FileNotFoundError' is not defined

```

**Comment by apaszke** [comment]
Can you run `ls` in this directory? Are you sure the file exists?

**Comment by apaszke** [comment]
Yeah it seems that `FileNotFoundError` is defined only in Python 3.3+. Can you please send a PR with the snippet you proposed as a fix? Thanks!
