### ISSUE TITLE
torch.empty_like supports memory_format=torch.preserve_format

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#43699]
## 🚀 Feature

Currently, the following code crashes
```python
res = torch.empty_like(input_coalesced, memory_format=torch.preserve_format)
print(res.layout)
> RuntimeError: memory format option is only supported by strided tensors

#  but similarly, below code works correctly
res = torch.zeros_like(input_coalesced, memory_format=torch.preserve_format)
print(res.layout)
```

The problem is related to `TORCH_CHECK` which seems to happen before sparse dispatching:
https://github.com/pytorch/pytorch/blob/2b70f827373fe5c90e15ce7ba0a1d331dcd57379/aten/src/ATen/native/TensorFactories.cpp#L285-L293

Torch check fails as `options.layout() == kSparse != kStrided` and  `optional_memory_format.has_value() == True`.

In addition, the docstring of `empty_like`, maybe, have to be improved as it states 
```
empty_like(input, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor
```
but passed `memory_format` is None : 
https://github.com/pytorch/pytorch/blob/2b70f827373fe5c90e15ce7ba0a1d331dcd57379/aten/src/ATen/native/native_functions.yaml#L1326

## Additional context

This impacts autodiff support of `sign` op on sparse input due to 
https://github.com/pytorch/pytorch/blob/2b70f827373fe5c90e15ce7ba0a1d331dcd57379/tools/autograd/derivatives.yaml#L912-L913

which internally calls `empty_like`

cc @vincentqb @aocsa @pearu

**Comment by vfdev-5** [comment]
I propose to change the order of `TORCH_CHECK` and `if (options.layout() == kSparse && self.is_sparse())` : 

```c++
 if (options.layout() == kSparse && self.is_sparse()) { 
   auto result = at::empty({0}, options); // to be resized 
   result.sparse_resize_and_clear_( 
       self.sizes(), self.sparse_dim(), self.dense_dim()); 
   return result; 

 TORCH_CHECK( 
     !(options.layout() != kStrided && 
         optional_memory_format.has_value()), 
     "memory format option is only supported by strided tensors"); 
```

**Comment by rgommers** [comment]
Seems reasonable to me, I would just open a PR @vfdev-5.
