### ISSUE TITLE
C++ with new torch::fft namespace, can no longer call torch::fft function, workaround?

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#43732]
pr #41911 adds the _fft_ namespace, which steps on the c++ _torch::fft()_ function.

what is the intended workaround?

call _at::fft_ ?

thanks

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
@mruberry please comment

**Comment by mruberry** [comment]
Thank you for reporting this issue, @meganset. I think I see the problem with an erroneous include. I'll get a patch up shortly to fix this.

**Comment by mruberry** [comment]
Sorry you had to hit this, @meganset. I've put up a fix.

**Comment by glaringlee** [comment]
@meganset please call `at::fft` before our fix is landed. We might need more time to discuss internally how to properly solve this. Thanks a lot.

**Comment by mruberry** [comment]
Fix has landed, @meganset. You should now have to import fft.h in C++, just like you have to import fft in Python, to access the new fft-namespace functions. The current fft function should work as expected. Let me know if you're still seeing an issue.
