### ISSUE TITLE
torch.matmul() wrong

### ISSUE THREAD

**Issue by leftthomas** [pytorch/pytorch#4374]
`a = torch.arange(1, 200*6*3+1).resize_(200, 6, 3)`
`w = torch.arange(1, 4*6*10*3+1).resize_(4, 6, 10, 3)`
`result = ((w.unsqueeze(dim=0)).matmul(a.unsqueeze(dim=-1).unsqueeze(dim=1))).squeeze(dim=-1)`
`w2 = w.transpose(-1, -2)`
`result2 =((a.unsqueeze(dim=-2).unsqueeze(dim=0)).matmul(w2.unsqueeze(dim=1))).squeeze(dim=-2).transpose(0, 1)`
`print(torch.equal(result, result2))`

I have this code, it return "True", but if I change 
`a = torch.arange(1, 200*6*3+1).resize_(200, 6, 3)`
`w = torch.arange(1, 4*6*10*3+1).resize_(4, 6, 10, 3)` 
to 
`a = torch.arange(1, 2000*6*3+1).resize_(2000, 6, 3)`
`w = torch.arange(1, 4*6*10*3+1).resize_(4, 6, 10, 3)`, 
it return "False". Why this happen?

**Comment by gchanan** [comment]
With the larger matrix you are hitting precision issues of float; if you make the tensors LongTensors or DoubleTensors the problem goes away:
`
a = torch.arange(1, 2000*6*3+1).resize_(2000, 6, 3).long()
w = torch.arange(1, 4*6*10*3+1).resize_(4, 6, 10, 3).long()
`

**Comment by leftthomas** [comment]
@gchanan thanks your answer, but I want to know why the computation of this two methods different, and I tested this code using numpy, it hasn't this problem.

**Comment by gchanan** [comment]
I'd suggest asking on the forums; it would be helpful if you include the corresponding numpy code as well.
