### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

### ISSUE THREAD

**Issue by jasw1001** [pytorch/pytorch#4375]
Hi,
Could anyone help me to figure out the following error?
Many Thanks!!!!!

my network 

`

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        layer_list = []
        in_channel = 1
        cfg = [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512]
        for output_channel in cfg:
            if output_channel == 'M':
                # layer_list.append(nn.MaxPool3d(2, 2))
                layer_list.append(nn.Conv3d(in_channel, in_channel, kernel_size=2, padding=0, stride=2))
            else:
                conv = nn.Conv3d(in_channel, output_channel, kernel_size=3, padding=1)
                layer_list += [conv, nn.BatchNorm3d(output_channel), nn.ReLU(inplace=True)]
                in_channel = output_channel
        self.layer = nn.Sequential(*layer_list)

        self.rpn_conv33 = nn.Conv3d(512, 512, kernel_size=3, padding=1, stride=1)
        self.rpn_relu33 = nn.ReLU(inplace=True)
        self.rpn_score = nn.Conv3d(512, 5 * 3, kernel_size=1)

        for m in self.modules():            # initialize convolution weight bias and BN.
            if isinstance(m, nn.Conv3d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.kernel_size[2] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
                if m.bias is not None:
                    m.bias.data.zero_()
                elif isinstance(m, nn.BatchNorm3d):
                    m.weight.data.fill_(1)
                    m.bias.data.zero_()

        self.rpn_score.weight.data.normal_(0, 0.01)
        self.rpn_score.bias.data.fill_(-math.log((1-0.01)/0.01))

    def forward(self, x):
        x = self.layer(x)
        x = self.rpn_conv33(x)
        x = self.rpn_relu33(x)
        x = self.rpn_score(x)
        x = x.view(x.size(0), x.size(1), -1)
        x = x.transpose(1, 2).contiguous().view(x.size(0), 8, 8, 8, 3, 5)
        return x
`

The Error: 

RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

Graph we tried to export:
graph(%0 : Float(1, 1, 128, 128, 128)
      %1 : Float(64, 1, 3, 3, 3)
      %2 : Float(64)
      %3 : Float(64)
      %4 : Float(64)
      %5 : Float(64)
      %6 : Float(64)
      %7 : Float(64, 64, 3, 3, 3)
      %8 : Float(64)
      %9 : Float(64)
      %10 : Float(64)
      %11 : Float(64)
      %12 : Float(64)
      %13 : Float(64, 64, 2, 2, 2)
      %14 : Float(64)
      %15 : Float(128, 64, 3, 3, 3)
      %16 : Float(128)
      %17 : Float(128)
      %18 : Float(128)
      %19 : Float(128)
      %20 : Float(128)
      %21 : Float(128, 128, 3, 3, 3)
      %22 : Float(128)
      %23 : Float(128)
      %24 : Float(128)
      %25 : Float(128)
      %26 : Float(128)
      %27 : Float(128, 128, 2, 2, 2)
      %28 : Float(128)
      %29 : Float(256, 128, 3, 3, 3)
      %30 : Float(256)
      %31 : Float(256)
      %32 : Float(256)
      %33 : Float(256)
      %34 : Float(256)
      %35 : Float(256, 256, 3, 3, 3)
      %36 : Float(256)
      %37 : Float(256)
      %38 : Float(256)
      %39 : Float(256)
      %40 : Float(256)
      %41 : Float(256, 256, 3, 3, 3)
      %42 : Float(256)
      %43 : Float(256)
      %44 : Float(256)
      %45 : Float(256)
      %46 : Float(256)
      %47 : Float(256, 256, 2, 2, 2)
      %48 : Float(256)
      %49 : Float(512, 256, 3, 3, 3)
      %50 : Float(512)
      %51 : Float(512)
      %52 : Float(512)
      %53 : Float(512)
      %54 : Float(512)
      %55 : Float(512, 512, 3, 3, 3)
      %56 : Float(512)
      %57 : Float(512)
      %58 : Float(512)
      %59 : Float(512)
      %60 : Float(512)
      %61 : Float(512, 512, 3, 3, 3)
      %62 : Float(512)
      %63 : Float(512)
      %64 : Float(512)
      %65 : Float(512)
      %66 : Float(512)
      %67 : Float(512, 512, 2, 2, 2)
      %68 : Float(512)
      %69 : Float(512, 512, 3, 3, 3)
      %70 : Float(512)
      %71 : Float(512)
      %72 : Float(512)
      %73 : Float(512)
      %74 : Float(512)
      %75 : Float(512, 512, 3, 3, 3)
      %76 : Float(512)
      %77 : Float(512)
      %78 : Float(512)
      %79 : Float(512)
      %80 : Float(512)
      %81 : Float(512, 512, 3, 3, 3)
      %82 : Float(512)
      %83 : Float(512)
      %84 : Float(512)
      %85 : Float(512)
      %86 : Float(512)
      %87 : Float(512, 512, 3, 3, 3)
      %88 : Float(512)
      %89 : Float(15, 512, 1, 1, 1)
      %90 : Float(15)) {
  %91 : Float(1, 1, 128, 128, 128), %92 : Handle = ^Scatter([0], None, 0)(%0), scope: DataParallel
  %93 : Float(1, 64, 128, 128, 128) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%91, %1, %2), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[0]
  %94 : Float(1, 64, 128, 128, 128) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%93, %3, %4, %5, %6), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[1]
  %95 : Float(1, 64, 128, 128, 128) = Relu(%94), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[2]
  %96 : Float(1, 64, 128, 128, 128) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%95, %7, %8), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[3]
  %97 : Float(1, 64, 128, 128, 128) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%96, %9, %10, %11, %12), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[4]
  %98 : Float(1, 64, 128, 128, 128) = Relu(%97), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[5]
  %99 : Float(1, 64, 64, 64, 64) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[0, 0, 0, 0, 0, 0], strides=[2, 2, 2]](%98, %13, %14), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[6]
  %100 : Float(1, 128, 64, 64, 64) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%99, %15, %16), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[7]
  %101 : Float(1, 128, 64, 64, 64) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%100, %17, %18, %19, %20), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[8]
  %102 : Float(1, 128, 64, 64, 64) = Relu(%101), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[9]
  %103 : Float(1, 128, 64, 64, 64) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%102, %21, %22), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[10]
  %104 : Float(1, 128, 64, 64, 64) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%103, %23, %24, %25, %26), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[11]
  %105 : Float(1, 128, 64, 64, 64) = Relu(%104), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[12]
  %106 : Float(1, 128, 32, 32, 32) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[0, 0, 0, 0, 0, 0], strides=[2, 2, 2]](%105, %27, %28), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[13]
  %107 : Float(1, 256, 32, 32, 32) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%106, %29, %30), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[14]
  %108 : Float(1, 256, 32, 32, 32) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%107, %31, %32, %33, %34), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[15]
  %109 : Float(1, 256, 32, 32, 32) = Relu(%108), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[16]
  %110 : Float(1, 256, 32, 32, 32) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%109, %35, %36), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[17]
  %111 : Float(1, 256, 32, 32, 32) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%110, %37, %38, %39, %40), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[18]
  %112 : Float(1, 256, 32, 32, 32) = Relu(%111), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[19]
  %113 : Float(1, 256, 32, 32, 32) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%112, %41, %42), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[20]
  %114 : Float(1, 256, 32, 32, 32) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%113, %43, %44, %45, %46), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[21]
  %115 : Float(1, 256, 32, 32, 32) = Relu(%114), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[22]
  %116 : Float(1, 256, 16, 16, 16) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[0, 0, 0, 0, 0, 0], strides=[2, 2, 2]](%115, %47, %48), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[23]
  %117 : Float(1, 512, 16, 16, 16) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%116, %49, %50), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[24]
  %118 : Float(1, 512, 16, 16, 16) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%117, %51, %52, %53, %54), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[25]
  %119 : Float(1, 512, 16, 16, 16) = Relu(%118), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[26]
  %120 : Float(1, 512, 16, 16, 16) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%119, %55, %56), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[27]
  %121 : Float(1, 512, 16, 16, 16) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%120, %57, %58, %59, %60), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[28]
  %122 : Float(1, 512, 16, 16, 16) = Relu(%121), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[29]
  %123 : Float(1, 512, 16, 16, 16) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%122, %61, %62), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[30]
  %124 : Float(1, 512, 16, 16, 16) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%123, %63, %64, %65, %66), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[31]
  %125 : Float(1, 512, 16, 16, 16) = Relu(%124), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[32]
  %126 : Float(1, 512, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[2, 2, 2], pads=[0, 0, 0, 0, 0, 0], strides=[2, 2, 2]](%125, %67, %68), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[33]
  %127 : Float(1, 512, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%126, %69, %70), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[34]
  %128 : Float(1, 512, 8, 8, 8) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%127, %71, %72, %73, %74), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[35]
  %129 : Float(1, 512, 8, 8, 8) = Relu(%128), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[36]
  %130 : Float(1, 512, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%129, %75, %76), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[37]
  %131 : Float(1, 512, 8, 8, 8) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%130, %77, %78, %79, %80), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[38]
  %132 : Float(1, 512, 8, 8, 8) = Relu(%131), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[39]
  %133 : Float(1, 512, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%132, %81, %82), scope: DataParallel/Net[module]/Sequential[layer]/Conv3d[40]
  %134 : Float(1, 512, 8, 8, 8) = BatchNormalization[consumed_inputs=[0, 0, 0, 1, 1], epsilon=1e-05, is_test=1, momentum=0.9](%133, %83, %84, %85, %86), scope: DataParallel/Net[module]/Sequential[layer]/BatchNorm3d[41]
  %135 : Float(1, 512, 8, 8, 8) = Relu(%134), scope: DataParallel/Net[module]/Sequential[layer]/ReLU[42]
  %136 : Float(1, 512, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[3, 3, 3], pads=[1, 1, 1, 1, 1, 1], strides=[1, 1, 1]](%135, %87, %88), scope: DataParallel/Net[module]/Conv3d[rpn_conv33]
  %137 : Float(1, 512, 8, 8, 8) = Relu(%136), scope: DataParallel/Net[module]/ReLU[rpn_relu33]
  %138 : Float(1, 15, 8, 8, 8) = Conv[dilations=[1, 1, 1], group=1, kernel_shape=[1, 1, 1], pads=[0, 0, 0, 0, 0, 0], strides=[1, 1, 1]](%137, %89, %90), scope: DataParallel/Net[module]/Conv3d[rpn_score]
  %139 : Float(1, 15, 512) = Reshape[shape=[1, 15, -1]](%138), scope: DataParallel/Net[module]
  %140 : Float(1!, 512!, 15!) = Transpose[perm=[0, 2, 1]](%139), scope: DataParallel/Net[module]
  %141 : Float(1, 8, 8, 8, 3, 5) = Reshape[shape=[1, 8, 8, 8, 3, 5]](%140), scope: DataParallel/Net[module]
  return (%141);
}

**Comment by apaszke** [comment]
We don't support exporting modules wrapped in DataParallel. Remove the wrapper and export this.

**Comment by mlinxiang** [comment]
@apaszke  if i trained model use DataParallel， how would i use onnx to export?

**Comment by chriamue** [comment]
model = torch.nn.DataParallel(model, device_ids=range(torch.cuda.device_count()))
torch.onnx.export(model.module, dummy_input, "model.onnx")

**Comment by uhvardhan** [comment]
Hi, 

I trained a model using DataParallel. I want to export to onnx model. How do I do it? I get the same error as the issue. 

Thanks in advance!

**Comment by mlinxiang** [comment]
@uhvardhan #
can use follow code, and must use the newest pytorch code, to fix some other onnx bug
 original saved file with DataParallel
state_dict = torch.load('myfile.pth.tar')
# create new OrderedDict that does not contain `module.`
from collections import OrderedDict
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:] # remove `module.`
    new_state_dict[name] = v
# load params
model.load_state_dict(new_state_dict)

Reference: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

**Comment by uhvardhan** [comment]
> @uhvardhan #
> can use follow code, and must use the newest pytorch code, to fix some other onnx bug
> original saved file with DataParallel
> state_dict = torch.load('myfile.pth.tar')
> 
> # create new OrderedDict that does not contain `module.`
> from collections import OrderedDict
> new_state_dict = OrderedDict()
> for k, v in state_dict.items():
> name = k[7:] # remove `module.`
> new_state_dict[name] = v
> 
> # load params
> model.load_state_dict(new_state_dict)
> 
> Reference: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

I get a new Attribute error if I follow as you said. 
AttributeError: 'DataParallel' object has no attribute 'items'

Also, I used this state_dict = torch.load(path) where path corresponds to just the pth file. 

Is there something I am doing wrong?

**Comment by mlinxiang** [comment]
@uhvardhan 
first not use DataParallel to load the model

example:
 #model= torch.nn.parallel.DataParallel(model, device_ids = [0])
        #model_parameters = self.load_network(model, 'G', 'best_vanila')
        model_parameters = self.load_network(model, 'G', 'best_generalization')
