### ISSUE TITLE
Ubuntu18.04 build from source error

### ISSUE THREAD

**Issue by shaoming20798** [pytorch/pytorch#43759]
Hi, I build pytorch from source using anaconda. And I got some errors as follows. Could you give me a help?
`
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"} && python setup.py install
`

>
-- NCCL_MAJOR_VERSION: 2                                                                  
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)      
-- Performing Test UV_LINT_W4                                                             
-- Performing Test UV_LINT_W4 - Failed                                                    
-- Performing Test UV_LINT_WALL                                                           
-- Performing Test UV_LINT_WALL - Success                                                 
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER                                            
-- Performing Test UV_LINT_NO_UNUSED_PARAMETER - Success                                  
-- Performing Test UV_LINT_STRICT_PROTOTYPES                                              
-- Performing Test UV_LINT_STRICT_PROTOTYPES - Success                                    
-- Performing Test UV_LINT_EXTRA                                                          
-- Performing Test UV_LINT_EXTRA - Success                                                
-- Found uv: submodule (found version "1.37.0")                                           
CMake Error at /opt/conda/envs/pytorch_src/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):                                                               
  Could NOT find Protobuf: Found unsuitable version
  "Protobuf_VERSION_NOTFOUND", but required is at least "3" (found
  optimized;/home/20798/pytorch/torch/lib/libprotobuf.a;debug;/home/20798/pytorch/torch/lib/libprotobufd.a;-pthread)
Call Stack (most recent call first):
  /opt/conda/envs/pytorch_src/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:456 (_FPHSA_FAILURE_MESSAGE)
  /opt/conda/envs/pytorch_src/share/cmake-3.18/Modules/FindProtobuf.cmake:626 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/tensorpipe/tensorpipe/CMakeLists.txt:124 (find_package)

cc @malfet

**Comment by VinodSKumar** [comment]
Latest master version seems to be compiling fine.
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.7.0a0+f06d390
[pip] torchvision==0.6.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0  
[conda] torch                     1.7.0a0+f06d390          pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi



From the error info, required protobuf version seems to be missing. please check once after installing protobuf.

**Comment by malfet** [comment]
@shaoming20798 can you please command you've used to checkout PyTorch?
Have you synced the submodule?
I.e., please run:
```
git submodule sync
git submodule update --init --recursive
``` in your pytorch repo checkout folder and then try building PyTorch again

**Comment by shaoming20798** [comment]
> @shaoming20798 can you please command you've used to checkout PyTorch?
> Have you synced the submodule?
> I.e., please run:
> 
> ```
> git submodule sync
> git submodule update --init --recursive
> ``` in your pytorch repo checkout folder and then try building PyTorch again
> ```

I tried it again following your reply, and now it seems to work! Thank you!
