### ISSUE TITLE
ImportError: cannot import name 'YamlLoader'

### ISSUE THREAD

**Issue by zhouzq-thu** [pytorch/pytorch#4376]
Build error:
```
File "~/pytorch/tools/autograd/utils.py", line 15, in <module>
    from yaml import YamlLoader
ImportError: cannot import name 'YamlLoader'
```

According to [PyYAMLDocumentation](https://pyyaml.org/wiki/PyYAMLDocumentation), the `pytorch/tools/autograd/utils.py` should be modified as:
``` diff
try:
    # use faster C loader if available
    from yaml import CLoader as YamlLoader
except ImportError:
-   from yaml import YamlLoader
+   from yaml import Loader as YamlLoader
```

**Comment by OnezeroW** [comment]
I faced the same problem when installing pytorch from source.
```
File "/home/jwan/projects/pytorch/tools/autograd/utils.py", line 13, in <module>
     from yaml import CLoader as YamlLoader
ImportError: cannot import name 'CLoader'

File "/home/jwan/projects/pytorch/tools/autograd/utils.py", line 15, in <module>
     from yaml import YamlLoader
ImportError: cannot import name 'YamlLoader'
```
You mean the utils.py file is wrong?

**Comment by vishwakftw** [comment]
Although the PyYAML documentation site suggests that `from yaml import CLoader as <insert name>` is possible, I could not perform it. That is a reason for the `try` failing. This has been reported as well: https://github.com/yaml/pyyaml/issues/108

I believe that the `except` should have this instead:
```python
from yaml import Loader as YamlLoader
```

**Comment by soumith** [comment]
you guys are right, the `except` case has to be modified to: `from yaml import Loader as YamlLoader`. The original issue (my guess) is that your pyyaml had some compile error and the CLoader wasn't successfully installed.
