### ISSUE TITLE
RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name)) when loading model weights

### ISSUE THREAD

**Issue by feiyangsuo** [pytorch/pytorch#43766]
I'm using pytorch 1.5. There's a weight file "best.pt" which is trained within pytorch 1.6. When I try to load the weights the error raises as ```RuntimeError: best.pt is a zip archive (did you mean to use torch.jit.load()?)```. 

The file can be naomally loaded in pytorch 1.6 using torch.load().

It doesn't work if I use torch.jit.load() to load the file. In this circumstance there's another error: ```RuntimeError: version_number <= kMaxSupportedFileFormatVersion ASSERT FAILED at ..\caffe2\serialize\inline_container.cc:131, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 1. Your PyTorch installation may be too old. (init at ..\caffe2\serialize\inline_container.cc:131)
(no backtrace available)```

I followed this [conversation](https://github.com/pytorch/pytorch/pull/25279)  which suggests to manually implement ```is_zipfile```, but the new function still judges "best.pt" as a zip file. In debug mode I saw it's true that the "magic number" appears in the first 4 bytes. So does it mean that this weight file is truely a zip file?

Then I wonder if the problem is caused by version confliction? Like, I should upgrade my pytorch version to 1.6 so that the problem is naturally gone?

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi feiyangsuo,

You are right that it is indeed a zip file. See [PyTorch 1.6 release notes](https://github.com/pytorch/pytorch/releases/tag/v1.6.0) about the change (search for "zip" in the linked webpage). I would suggest upgrading to 1.6 and the issue should be gone. If that's not the case, please update the bug and we will investigate. Or if you have reasons to not upgrade to 1.6, let us know and we will see what we can do.

Thanks,

**Comment by feiyangsuo** [comment]
@ gmagogsfm
Thanks, that's the case. :)

**Comment by Lilyjjo** [comment]
good to hear! :)

**Comment by YangAzure** [comment]
I have an exactly same issue, except that my model is trained on torch version 1.6.0, and I tried to load in version 1.6.0 as well. Requesting for an reopen.

`RuntimeError: ./model.bin is a zip archive (did you mean to use torch.jit.load()?)`

Triggered by

`model = torch.load("./model.bin"))`

**Comment by brando90** [comment]
> Hi feiyangsuo,
> 
> You are right that it is indeed a zip file. See [PyTorch 1.6 release notes](https://github.com/pytorch/pytorch/releases/tag/v1.6.0) about the change (search for "zip" in the linked webpage). I would suggest upgrading to 1.6 and the issue should be gone. If that's not the case, please update the bug and we will investigate. Or if you have reasons to not upgrade to 1.6, let us know and we will see what we can do.
> 
> Thanks,

@gmagogsfm 

I cannot update due to hardware reasons (using ibm ppc64le architecture).

What is the solution?

**Comment by brando90** [comment]
Here is SO asked few months ago that might be helpful:

- https://stackoverflow.com/questions/64141188/how-to-load-checkpoints-across-different-versions-of-pytorch-1-3-1-and-1-6-x-u 


-----

here is a collection of some related links:

- https://github.com/pytorch/pytorch/issues/25214 
- https://github.com/pytorch/pytorch/issues/43766
- https://discuss.pytorch.org/t/problem-with-my-checkpoint-file-when-using-torch-load/92903
- https://www.gitmemory.com/issue/pytorch/pytorch/43766/683549394
- https://stackoverflow.com/questions/64141188/how-to-load-checkpoints-across-different-versions-of-pytorch-1-3-1-and-1-6-x-u

**Comment by anbai106** [comment]
I have the same issue with 1.7.0 by using torch.save and torch.load.

**Comment by Dawn-LX** [comment]
pytorch1.6 and later change the save file to zip file, you can use a higher version (>=0.6) to load the weight.pt and re-save by using `_use_new_zipfile_serialization=False`

```
import torch
state_dict = torch.load('model_weight.pt', map_location="cpu")
torch.save(state_dict, 'model_weight.pt', _use_new_zipfile_serialization=False)
```
