### ISSUE TITLE
Fix exception chaining all over the codebase

### ISSUE THREAD

**Issue by akihironitta** [pytorch/pytorch#43770]
I would like to suggest a small fix in the way that Python 3's exception chaining is used.

As described in detail in [this article](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with), exception chaining ([PEP 3134](https://www.python.org/dev/peps/pep-3134/)) can be used to make exceptions more user-friendly, and in that case, the syntax `raise new_exception from old_exception` needs to be used.

For example, the following should be used to chain exceptions:
```python
try:
    something_which_raises_TypeError
except TypeError as e:
    raise ValueError("A more user-friendly exception message.") from e
```
instead of:
```python
try:
    something_which_raises_TypeError
except TypeError:
    raise ValueError("A more user-friendly exception message.")
```

One example which needs to be fixed is:
https://github.com/pytorch/pytorch/blob/c7787f7fbf388f9fe326d581726e7ef3f2dce74b/torch/jit/annotations.py#L32-L35

I'd be happy to PR! Let me know your thoughts on this!

**Comment by malfet** [comment]
Thank you for suggestion @akihironitta !
Please feel free to write a PR and I will be happy to review it.
Also consider eliminating all calls to that macro with direct `raise .. from ..` calls:
https://github.com/pytorch/pytorch/blob/20abfc21e41dfe0bd2500295f7482edbeb6b6c05/torch/_six.py#L56-L60

Although not all instances require exception chaining, for example implicit chaining is totally fine in cases that you've mentioned in the issue description:
https://github.com/pytorch/pytorch/blob/c7787f7fbf388f9fe326d581726e7ef3f2dce74b/torch/jit/annotations.py#L32-L35

**Comment by akihironitta** [comment]
Thank you for your quick response.

Sure, I'll remove `raise_from()` and use `raise .. from ..` instead all over the codebase.

> Although not all instances require exception chaining, for example implicit chaining is totally fine in cases that you've mentioned in the issue description:
> https://github.com/pytorch/pytorch/blob/c7787f7fbf388f9fe326d581726e7ef3f2dce74b/torch/jit/annotations.py#L32-L35

I agree that not all instances require exception chaining. However, I think we should not use implicit chaining in the above case because its error message `During handling of the above exception, another exception occurred` is confusing.

For example, if we run the script below (`test.py`):
```python
d = {"dog": 1}
key = "cat"
try: 
    print(d[key])  # raises KeyError
except KeyError:
    raise RuntimeError("no member called {}".format(key))
```
it'll give us an error message like this:
```
Traceback (most recent call last):
  File "/home/nitta/tmp/test.py", line 4, in <module>
    print(d[key])  # raises KeyError
KeyError: 'cat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nitta/tmp/test.py", line 6, in <module>
    raise RuntimeError("no member called {}".format(key))
RuntimeError: no member called cat
```

`During handling of the above exception, another exception occurred` is somewhat confusing when debugging because the truth is that another exception occurred to explain the first exception (`KeyError` in this case) in a friendlier way, not because another **unexpected** exception occured while handling the first exception.

In order to fix confusing messages like this, one option is:
```python
try: 
    print(d[key])  # raises KeyError
except KeyError as e:
    raise RuntimeError("no member called {}".format(key)) from e
```
which outputs
```
Traceback (most recent call last):
  File "/home/nitta/tmp/test.py", line 4, in <module>
    print(d[key])  # raises KeyError
KeyError: 'cat'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nitta/tmp/test.py", line 6, in <module>
    raise RuntimeError("no member called {}".format(key)) from e
RuntimeError: no member called cat
```

However, in this case, the above message is a bit noisy and redundant.
If we want to suppress the first error message, we should use `raise .. from None` so as to suppress the first exception message (see [Suppress Context in PEP 3134](https://www.python.org/dev/peps/pep-3134/#open-issue-suppressing-context)).
```python
try: 
    print(d[key])  # raises KeyError
except KeyError:
    raise RuntimeError("no member called {}".format(key)) from None
```
which outputs
```
Traceback (most recent call last):
  File "/home/nitta/tmp/test.py", line 6, in <module>
    raise RuntimeError("no member called {}".format(key)) from None
RuntimeError: no member called cat
```

Do you think using `raise .. from None` is reasonable in the below case or simliar cases?
https://github.com/pytorch/pytorch/blob/c7787f7fbf388f9fe326d581726e7ef3f2dce74b/torch/jit/annotations.py#L32-L35

**Comment by akihironitta** [comment]
As there seems a lot of places (over 100 places in this repo) to check, it may be a good idea to label this issue as `good first issue` for people who are interested in contributing. It can also make each PR relatively small. What do you think? (I can work on this issue by myself, but it might take some time...)

**Comment by akihironitta** [comment]
@malfet Thanks for your response the other day. As I checked and fixed all the files under `torch/` directory, could you have a look at #43836?

**Comment by malfet** [comment]
@akihironitta left a few comments on the PR, but overall looks good!

**Comment by akihironitta** [comment]
@malfet Thank you for reviewing the changes! I've just fixed them reflecting your code.
