### ISSUE TITLE
PyTorch's div, which performs true division, cannot be exported to ONNX with consistent semantics

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#43787]
In PyTorch we're changing our division behavior to perform "true" division like Python3 and NumPy. This means that 5 / 2 = 2.5, for example. 

Exporting true division to ONNX is tricky because ONNX's division (1) does not perform true division and (2) mimicking true division using ONNX's division requires manipulating the dtypes of the inputs, and we don't have a mechanism to interrogate or set dtypes after exporting the graph (via tracing).

Ideally ONNX would provide a true division node (either by creating a new node or updating ONNX division to perform true division), but until that happens we should consider mitigations to this issue. Some possible solutions are:

1) document the issue and require users work around it (where would we document this?)
2) throw a warning when users export div (document it in place)
3) ...?

cc @mruberry @rgommers @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by rgommers** [comment]
A `FutureWarning` seems needed for a change like this I'd think, documentation alone is too easy to miss.

**Comment by mruberry** [comment]
Some additional context:

- division in PyTorch currently runtime errors when trying to perform integer division, so integer division cannot be exported at the moment
- there are probably other operators with the same issue that their semantics cannot be correctly exported to ONNX

**Comment by neginraoof** [comment]
@mruberry 
I saw you have implemented the aten::true_divide symbolic using ONNX's division operator, and the symbolic is mimicking true division: https://github.com/pytorch/pytorch/commit/3671036ef326ec63039127b3831bcdd34e72d1b3
The logic is to check input dtype and apply casting if one of inputs is not floating point or its dtype is unknown. Is this existing logic not sufficient for supporting the new division behavior?

**Comment by mruberry** [comment]
I think the challenge is that we don't know at export time what the dtypes of the inputs will be when the ONNX graph is run?

**Comment by neginraoof** [comment]
Yeah we deal with this issue in symbolics in different ways. The current logic for true_divide inserts an onnx::Cast to ```torch.get_default_dtype()``` node in cases where there's no input with known floating point dtype.


Just a note: we have recently implemented an experimental feature for type/shape inference during ONNX export at symbolic-level. Though this is the first step towards having complete shape and type inference for ONNX models.
https://github.com/pytorch/pytorch/pull/40628

**Comment by mruberry** [comment]
I wrote the true divide ONNX export and I think it's too fragile to continue using, however. I tried updating div to be the same, for example, and it broke multiple tests. Also, while true divide was making a "best effort" attempt at preserving semantics, it also couldn't actually preserve semantics since it's transforms were based on previously observed values.

Hence why I think we should warn the user and let them resolve the issue, for now at least. Although it's exciting to hear that ONNX will have better support for these scenarios in the future.

**Comment by neginraoof** [comment]
Another point is that for arithmetic ops, jit_onnx_scalay_type_analysis is post-pass (https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx/scalar_type_analysis.cpp) that handles dtype castings.

During tracing, traced graph usually propagate input dtypes (in most cases), and the symbolic uses the same info. We can extend the scalar type analysis pass to handle the cases where input dtype is unknown with a warning.

**Comment by BowenBao** [comment]
@mruberry - I added a PR #43991 to enable exporting scripted true divide with onnx shape inference mentioned earlier above. We will continue to improve on that end to have better support for scripting export.

On the topic of changing division behavior to true divide. Is this a backward breaking change? From the look it would affect a lot of existing models both in values and in semantics.

**Comment by mruberry** [comment]
It was BC-breaking, which is why we throw a runtime error if a user tries to use div to perform integer division in 1.6. So it is no longer BC-breaking (BC has been broken). 

I appreciate your fixing the true divide export, @BowenBao but I'm still concerned it's fragile. If we think that's the best plan for handling these issues then we can try it.

**Comment by neginraoof** [comment]
@mruberry Is this work on torch div operator in progress? Can you possibly point us to the PR if it's open?
Thanks

**Comment by mruberry** [comment]
Sure thing: draft is here.

**Comment by mruberry** [comment]
@BowenBao with your fixes the "best effort" version of div looks like it's working, so that's good news.

Foolow-up question while we're talking about division: can we use the floor node in ONNX to implement floor division? I tried but received a complaint about floor not being bound. It looks like floor was in opset6 and again in 13, but it looks like we don't support opset6?

**Comment by BowenBao** [comment]
@mruberry should we close this issue now that ONNX div export is updated to perform true_divide? The problem with export time shape/type info availability/correctness is a much broader goal, and we are working continuously to improve the coverage and flexibility of shape/type inferencing.

**Comment by mruberry** [comment]
Sounds good.
