### ISSUE TITLE
Advanced indexing in 2d tensor

### ISSUE THREAD

**Issue by vsbiradar** [pytorch/pytorch#4378]
I have a 2d tensor X. and two lists of indexes that is first index and second call a and b. I want to do
X[a[i],b[i]] = 0 for i in range(len(a)). How can I do this. If i directly do X[a,b] the error is IndexError: The advanced indexing objects could not be broadcast

**Comment by apaszke** [comment]
Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
