### ISSUE TITLE
[ONNX] shape node constant folded tensor with dynamic shape

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#43795]
## 🐛 Bug

Reported [here](https://github.com/microsoft/onnxruntime/issues/4898) first reported as issue #43283 

## To Reproduce

We export a model with dynamic shape `bbs` passed input. The shape node constant folded what is a dynamic shape (coming from bbs) tensor.

```python
import torch
import onnxruntime as rt

def _align_box(im_h, im_w, bbs,
               enlargement_factor, target_size, min_len, align='SHORTEST'):
    zero = torch.as_tensor(0.0).float().to(bbs.device)

    # enlarge the bounding box
    w = (bbs[:, 2] * enlargement_factor).ceil()
    h = (bbs[:, 3] * enlargement_factor).ceil()

    # CXCYWH to XYWH
    input_x = (bbs[:, 0] - w / 2).floor()
    cond = input_x < 0
    idx = torch.nonzero(cond).view(-1)
    # TODO: use scatter_add when fixed: https://github.com/pytorch/pytorch/issues/26472
    w = torch.scatter(w, 0, idx, w[idx] + input_x[idx])  # w[idx] += input_x[idx]
    input_x = torch.where(cond, zero, input_x)  # input_x[idx] = 0
    input_y = (bbs[:, 1] - h / 2).floor()
    cond = input_y < 0
    idx = torch.nonzero(cond).view(-1)
    # TODO: use scatter_add when fixed: https://github.com/pytorch/pytorch/issues/26472
    h = torch.scatter(h, 0, idx, h[idx] + input_y[idx])  # h[idx] += input_y[idx]
    input_y = torch.where(cond, zero, input_y)  # input_y[idx] = 0

    w = w.clamp(min=min_len)  # w[w < min_len] = min_len
    h = h.clamp(min=min_len)  # h[h < min_len] = min_len

    input_width = im_w - input_x
    input_width = torch.where(w < input_width, w, input_width)  # input_width[idx=w < input_width] = w[idx]
    input_height = im_h - input_y
    input_height = torch.where(h < input_height, h, input_height)  # input_height[idx=h < input_height] = h[idx]
    del w, h

    # If too far to the right shift the coordinates
    idx = input_width < min_len
    input_width = torch.where(idx, min_len, input_width)  # input_width[idx] = min_len
    input_x = torch.where(idx, im_w - min_len, input_x)  # input_x[idx] = im_w - min_len
    idx = input_height < min_len
    input_height = torch.where(idx, min_len, input_height)  # input_height[idx] = min_len
    input_y = torch.where(idx, im_h - min_len, input_y)  # input_y[idx] = im_h - min_len

    target_width = torch.full_like(input_width, target_size)
    target_height = torch.full_like(input_height, target_size)

    # align with constraint
    if align == 'SHORTEST':
        # Avoid `<=` because ONNX will export that as `Not` and `>` then we need another `Not`
        #  instead, first compute `>` and use `~` to be exported as `Not`
        nidx = input_width > input_height
        idx = ~nidx  # this requires patch_logical_not_opset9 until bitwise_not for bool is in PyTorch
        idx = torch.nonzero(idx).view(-1)
        target_height = torch.scatter(target_height, 0, idx, target_size * input_height[idx] / input_width[idx])

        idx = torch.nonzero(nidx).view(-1)
        target_width = torch.scatter(target_width, 0, idx, target_size * input_width[idx] / input_height[idx])
    elif align == 'LONGEST':
        idx = input_width > input_height
        nidx = ~idx  # this requires patch_logical_not_opset9 until bitwise_not for bool is in PyTorch
        idx = torch.nonzero(idx).view(-1)
        target_height = torch.scatter(target_height, 0, idx, target_size * input_height[idx] / input_width[idx])

        idx = torch.nonzero(nidx).view(-1)
        target_width = torch.scatter(target_width, 0, idx, target_size * input_width[idx] / input_height[idx])
    else:
        assert align == 'BOTH'

    return input_x, input_y, input_width, input_height, target_width, target_height

class Module(torch.nn.Module):
    def forward(self, img, bbs):
        _, _, height, width = img.shape[0], img.shape[1], img.shape[2], img.shape[3]
        # When tracing (for onnx export this is Tensor)
        if not isinstance(height, torch.Tensor):
            height, width = torch.as_tensor(height).to(img.device), torch.as_tensor(width).to(img.device)

        input_x, input_y, input_width, input_height, target_width, target_height = _align_box(
            height.float(), width.float(), bbs, 1.5, 256, torch.as_tensor(3).float()
        )
        return input_x, input_y, input_width, input_height, target_width, target_height

model = Module()
img = torch.empty((1,3,256,512))
bbs = torch.as_tensor([[0, 0, 100, 100], [0, 0, 500, 100]]).float()

targets = ['input_x', 'input_y', 'input_width', 'input_height', 'target_width', 'target_height']
torch.onnx.export(model, (img, bbs), 'test.onnx',
                  verbose=True,
                  input_names=['img', 'bbs'],
                  output_names=targets,
                  opset_version=11,
                  dynamic_axes={'img': {2: 'h', 3: 'w'}, 'bbs': {0: 'rpn'}})

```

## Expected behavior

Same behavior as PyTorch

## Environment

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 418.87.01
cuDNN version: /usr/local/lib/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.1.0            py36h23d657b_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] pytorch                   1.6.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py36_cu101    pytorch

## Additional context

There has been some back and forth, but seems like the issue is with the exporter constant folding the shape of the inout.
So ORT optimizer makes that an initializer that then results in crash when an input with a different shape is passed to input.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by BowenBao** [comment]
hi @dashesy - could you try with flag `do_constant_folding=False` in export?

**Comment by dashesy** [comment]
Looks like same result with `do_constant_folding=False`:

![image](https://user-images.githubusercontent.com/873905/91891323-b3b36b00-ec45-11ea-9e59-fb36b6c37e4e.png)

---
P.S. Would be great to have a context to tell exporter to not fold any constants for shape, and let it be optimized if needed by ORT.

```python
with onnx.export_dynamic():
    shape = t.shape
```

**Comment by BowenBao** [comment]
@dashesy - There is no constant folding happening at the exporter level. The `Shape` node itself is a proof that the shape is computed dynamically. If exporter constant folds any shape, you will see a `Constant` node instead. 

The issue in this repro is that `dynamic_axes` was not set for model outputs. Since `input_width` is part of model outputs, and I'm assuming it should have dynamic size.

**Comment by dashesy** [comment]
This is just for repro. In the actual model that shows the issue `input_width`, `input_height` are not model outputs but rather used in further part of the model. There is no mechanism like `dynamic_size` to declare them to be dynamic.
Based on dynamic inputs, the shape node should be dynamic. The shape depends on the input shape.

**Comment by BowenBao** [comment]
> But then this "shape" becomes constant shape.

Why do you think this "shape" is constant? The node returns the shape of `input_width`, which as mentioned above, shows `[2]` only because it's part of model output. Thus the value returned from "shape" totally depends on the shape of `input_width` produced at runtime. 

I agree with everything else above that you have mentioned, that dynamic shape should be preserved, and that is exactly what `Shape` node is for.

**Comment by dashesy** [comment]
The length of the data in shape is constant `2`, it should be a numbered data without shape specified.  
I will have to create a smaller repro that shows the issue even when `input_width` is not an output but in the middle of a larger network, everything computed.

**Comment by llpin1992** [comment]
> hi @dashesy - could you try with flag `do_constant_folding=False` in export?
it wrok for me, thanks!!!

**Comment by azuryl** [comment]
> > hi @dashesy - could you try with flag `do_constant_folding=False` in export?
> > it wrok for me, thanks!!!

It not work for my adabins efficientnet

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
