### ISSUE TITLE
RuntimeError: the number of sizes provided must be greater or equal to the number of dimensions in the tensor 

### ISSUE THREAD

**Issue by sxqqslf** [pytorch/pytorch#4380]
Same problem as #4228 , I try this code on the terminal,
`a = Variable(torch.randn(1,1), requires_grad=True)`
`b = Variable(torch.randn(1,1), requires_grad=True)`
`d = torch.nn.functional.cosine_similarity(a,b)`
`d.backward()`
then, 
`RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /pytorch/torch/lib/TH/generic/THTensor.c:299`
I check the d is a scalar

> Variable containing:
> 1
> [torch.FloatTensor of size 1]

I'm a newbie of pytorch, so i'm not sure this code is meaningful.

**Comment by zou3519** [comment]
I can reproduce this on master. Will look into it.

**Comment by sxqqslf** [comment]
@zou3519 Besides, I install the pytorch by the pip, not from the source code.
I find the functional.py in the github is different from my local version

> local: `return (w12 / (w1 * w2).clamp(min=eps)).squeeze()`
> github: `return w12 / (w1 * w2).clamp(min=eps)`

**Comment by zou3519** [comment]
Oh I see. Sorry, I meant that I reproduced it on 0.3, which is what you probably have from pip.

I should have fixed this with https://github.com/pytorch/pytorch/pull/3811 and I've verified that this doesn't crash on master anymore. @sxqqslf if you build from source, the error should go away :) (instructions are in the README).

**Comment by sxqqslf** [comment]
@zou3519 Emmm, I have rebuilt the pytorch from source, it's ok now, ths.

**Comment by cloudyliy** [comment]
I have also encountered such a problem, how can I solve it?

**Comment by zou3519** [comment]
@cloudyliy if you are using an older version of pytorch, please upgrade it. Otherwise, could you fill out a new issue?
