### ISSUE TITLE
Synchronized communication with workers

### ISSUE THREAD

**Issue by 0phoff** [pytorch/pytorch#4382]
The full extend of my problem can be read [here](https://discuss.pytorch.org/t/communicating-with-dataloader-workers/11473) on the forums.
But what I basically need, is a way to communicate with my worker threads before they start preparing the next batch.

I think the easiest way to implement this is to pass a function as an argument to your _DataLoader_.
The _DataLoaderIter_ object can then call this function before sending the new indices on the Queu,
 like [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L291) in the code maybe?  
In that function you could then communicate with your workers via _multiprocessing_ variables.

I think this is a problem others will encounter as well and is therefore worth implementing...
However, I noticed you guys are reworking the dataloader code, so let me know if that fits in with your vision on how things will evolve for pytorch!

If you think this is worth adding and if my method of solving looks good to you, I can take a look at implementing this and sending in a PR. :construction_worker:

**Comment by 0phoff** [comment]
So I tinkered around a bit with these workers (mostly just running stuff and printing out indices), and now I understand my idea will not work.  

If I understand everything correctly, you keep **2 * workers** number of batches in your queue. This means that if I would call a function in _put_indices()_ to change some _multiprocessing_ variables, the **2 * workers** batches that were already in the queue would also get affected by it, which is not what I want.  
Moreover, batches that are in the middle of being processed, also get affected, and thus generate batches with half of the batch processed with the previous value and half of it with the next...

So, my question remains unanswered...  
Is there _- or will there ever be -_ a way to communicate in a synchronized way with your workers?  
I know this would probably involve letting the _index_queu_ empty itself, change a variable, and repopulate it. This will in turn slow down the whole data fetching process, so I  can understand if you are not implementing this...  
If someone could help me find another solution to my [problem](https://discuss.pytorch.org/t/communicating-with-dataloader-workers/11473), that would be great! :pray:

**Comment by apaszke** [comment]
As you pointed out it's not easy to implement a robust way for communication like this, so I think it's best to avoid doing so. One way to implement this would be to encode the information in the object used to index the dataset by creating your own sampler. The whole process would look approximately like this:
```python
class MySampler(object):
    def __init__(self, model):
        self.model = model
    def __iter__(self):
        for i in range(epoch_length):
            yield (self.model.input_size, i) # NOTE: this doesn't do shuffling, but you can sample i

class MyDataset(object):
    def __getitem__(self, args):
        sample_size, sample_idx = args
        return ... # load the sample and resize

dset = MyDataset()
sampler = MySampler(model)
loader = DataLoader(dset, ..., sampler=sampler)
```
