### ISSUE TITLE
Unable to import pytorch

### ISSUE THREAD

**Issue by LazyTrader** [pytorch/pytorch#43845]
## 🐛 Bug

Upon importing pytorch, I get "OsError: [WinError 126] The specified module could not be found. Error loading "C:\ProgramData\Anaconda3\envs\DeepLearning\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies."

## To Reproduce

1. Try to import pytorch using "import torch"

## Expected behavior

Pytorch should be able to be imported without any errors.

## Environment

 - PyTorch Version: 1.6.0
 - OS: Windows 10 home 64bit
 - How you installed PyTorch: conda
 - Build command you used (if compiling from source): -
 - Python version: 3.8.5
 - CUDA/cuDNN version: Cudatoolkit V10.2.89/cuDNN V7.6.5
 - GPU models and configuration: RTX 2080 TI
 - Any other relevant information: -

cc @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mszhanyi** [comment]
@LazyTrader , did you use `conda install pytorch cudatoolkit=10.2 -c pytorch` to install pytorch

**Comment by LazyTrader** [comment]
@mszhanyi 

I used conda install -c pytorch pytorch and the cuda version that I have was shipped together

**Comment by peterjc123** [comment]
Could you please post some logs using Process Monitor or the Debugging Tools for Windows?

**Comment by LazyTrader** [comment]
@peterjc123 How do I do that? I'm not quite sure on how to do that and I haven't been able to find instructions on how to do it.

**Comment by peterjc123** [comment]
Download process monitor from https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and open it. And then you just do the normal `import torch` in CMD. Finally, just stop monitoring, save it and post the saved file here.

**Comment by LazyTrader** [comment]
After running "import torch" in CMD, I found out that the latest Microsoft Visual C++ 2015-2019 Redistributable was not installed on my system. After installing it, I am now able to use pytorch normally. I'll be closing this issue.

**Comment by peterjc123** [comment]
@LazyTrader So which environment / IDE are you using previously?

**Comment by LazyTrader** [comment]
I was using Spyder and Spyder failed to mention anything about the lack of Microsoft Visual C++ 2015-2019 Redistributable other than displaying the aforementioned OsError

**Comment by navneethc** [comment]
Just adding a comment that this was not an IDE-related issue at all. I too faced the issue when updating to and installing afresh 1.6.0 but with plain old Powershell. And I got the error message despite the fact that the 2017 redistributable was already installed in my computer. Of course, now that I installed 2015-2019 version, things seem to be working normally. If this is a separate requirement that's not installable with conda, would it be possible to add that bit of information to the install instructions?

**Comment by sidml** [comment]
In windows 10, I get the following error when i try to import pytorch.

> Error loading "C:\Users\laogu\anaconda3\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies.

As mentioned earlier, the error can be resolved by installing Microsoft Visual C++ 2015-2019 Redistributable.

**Comment by moriwx** [comment]
The error still exists even after installing the latest Microsoft Visual C++ Redistributable... \cry

**Comment by ctwillson** [comment]
I use "conda install pytorch torchvision torchaudio cpuonly -c pytorch" install pytorch，python version:3.8.5，this error still remain...

**Comment by mszhanyi** [comment]
@ctwillson 
1. Does the asmjit.dll exist?
2. if asmjit.dll exist, could you please use [depends](https://github.com/lucasg/Dependencies) to see which depends missing?

**Comment by malfet** [comment]
@ctwillson can you please share output of `python -mtorch.utils.collect_env` command?

**Comment by ctwillson** [comment]
> @ctwillson
> 
> 1. Does the asmjit.dll exist?
> 2. if asmjit.dll exist, could you please use [depends](https://github.com/lucasg/Dependencies) to see which depends missing?
 Thanks for your reply,I install https://aka.ms/vs/16/release/vc_redist.x64.exe,it works good for me

**Comment by ctwillson** [comment]
> @ctwillson
> 
> 1. Does the asmjit.dll exist?
> 2. if asmjit.dll exist, could you please use [depends](https://github.com/lucasg/Dependencies) to see which depends missing?

Thanks for your reply,I install https://aka.ms/vs/16/release/vc_redist.x64.exe,it works good for me

**Comment by Aliktk** [comment]
> @ctwillson can you please share output of `python -mtorch.utils.collect_env` command?

I am getting same error while importing spacy module. Thank I manually import torch and getting this issue what would be the reason behind it.


```python
python -mtorch.utils.collect_env

Traceback (most recent call last):
  File "C:\Users\Ali\anaconda3\envs\nlp\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Ali\anaconda3\envs\nlp\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Ali\anaconda3\envs\nlp\lib\site-packages\torch\__init__.py", line 135, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Ali\anaconda3\envs\nlp\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
````

**Comment by Unicorn-1** [comment]
Hi, Could anyone help. I am using VS code and facing this issue 
OSError: [WinError 126] The specified module could not be found. Error loading "c:\Users\mayur.a.dubey\AppData\Local\anaconda3\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
