### ISSUE TITLE
CrossEntropyLoss does not raise target out of bounds error on gpu

### ISSUE THREAD

**Issue by mostafahadian** [pytorch/pytorch#43840]
## 🐛 Bug

CrossEntropyLoss does not raise target out of bounds error on gpu. When I test it on cpu it works perfectly. But on gpu, it does not raise any errors.

## To Reproduce

1. Install pytorch 1.5.0 on ubuntu 18.04
2. Run `torch.nn.CrossEntropyLoss()(torch.tensor([[2.5, 0, 0], [0, 0, 2.5]]).to("cuda"), torch.tensor([0, 1000]).to("cuda"))`
This is supposed to raise an exception. But it returns tensor(0.0760, device='cuda:0')

## Expected behavior

I expected it to raise "IndexError: Target 1000 is out of bounds" error as in the case of cpu.
I tested it on cpu by calling:
`torch.nn.CrossEntropyLoss()(torch.tensor([[2.5, 0, 0], [0, 0, 2.5]]), torch.tensor([0, 1000]))`
and it raised the expected error.

## Environment

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 440.64.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect

cc @ngimel

**Comment by ngimel** [comment]
Fixed in 1.5.1, 1.6 and master. Closing, please reopen if issue persists.
