### ISSUE TITLE
Code changes are getting applied during runtime when using 'spawn'

### ISSUE THREAD

**Issue by Karol-G** [pytorch/pytorch#43856]
## 🐛 Bug
Setting multiprocessing start method to 'spawn' and using num_workers > 1 in the dataloader has as consequence that every change of code made in the dataset class will be reflected during runtime once a new epoch starts.

## To Reproduce
Here is a minimal example to reproduce the bug:
``` Python
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch

class MyDataset(Dataset):

    def __init__(self):
        pass

    def __getitem__(self, index):
        print("0")  # Change to anything else during runtime, change is visible with start of new epoch
        return torch.zeros(10)

    def __len__(self):
        return 100

if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')

    dataset = MyDataset()
    data_loader = DataLoader(dataset, batch_size=32, num_workers=2)

    for _ in range(10000):
        for batch in data_loader:
            pass
```
Change the print statement during runtime. The change will be visible with the start of the next epoch.

## Expected behavior
Code changes in the dataset class should not be reflected during runtime.

## Environment
PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect (Should be version 10.1.243, cuDNN is 7.6.5.32)
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 450.36.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.0

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] Could not collect

Best
Karol

cc @SsnL @VitalyFedyunin

**Comment by SsnL** [comment]
This is expected from spawn, because well it is literally spawning a new python process which then reads and runs the script.

**Comment by Karol-G** [comment]
I am using another model on the gpu during preprocessing in an online learning setting and are therefore forced to use 'spawn'. I am also still optimizing/improving my code/settings in the dataset class and train many instances of my real model (the one that uses the dataset class, not the preprocessing one). But whenever I change something in the dataset class all of my current train instances become faulty or even crash (For example if you add a parameter to a method). 
Wouldn't it be possible to cache the dataset class and only spawn from the cached dataset class when using spawn?

**Comment by SsnL** [comment]
No it is not possible. This is how python `spawn` multiprocessing works. PyTorch has no control over that, nor should PyTorch deviate from python.

**Comment by Karol-G** [comment]
Hmm, ok I understand. Closing this then.
