### ISSUE TITLE
nn.functional.linear output mismatch between eager and scripting mode

### ISSUE THREAD

**Issue by qizzzh** [pytorch/pytorch#43851]
## 🐛 Bug

nn.functional.linear output mismatch between eager and scripting mode

## To Reproduce

```
class MyFunc(torch.nn.Module):
  def __init__(self):
    super(MyFunc, self).__init__()

  def forward(self, input, w, b):
    return torch.nn.functional.linear(input, w, b)

input = torch.rand([2, 2048])
w = torch.rand([128, 2048])
b = torch.rand([128])

m = MyFunc()
ms = torch.jit.script(m)

r1 = m(input, w, b)
r2 = ms(input, w, b)
r3 = m(input, w, b)

print(torch.equal(r1, r2))
print(torch.equal(r1, r3))
```

## Expected behavior

Expected both return True. However the first comparison returns False.

cc @gmagogsfm

**Comment by qizzzh** [comment]
I'm experimenting with the change below and checking unit tests

```
-    if input.dim() == 2 and bias is not None:
-        # fused op is marginally faster
-        ret = torch.addmm(bias, input, weight.t())
-    else:
-        output = input.matmul(weight.t())
-        if bias is not None:
-            output += bias
-        ret = output
-    return ret
+    return torch._C._nn.linear(input, weight, bias)
```

**Comment by albanD** [comment]
Hi,

It is possible that they're not bit-wise equal, but the difference is just due to floating point inaccuracy (because they do op in a different order) right?

**Comment by qizzzh** [comment]
Hi @albanD, yeah I think that's the case. However we have some testing infra asserting that the outputs from eager and scripting mode are the same. It'd be better if we can fix it. Do you think the code snippet above could be a correct fix? I hit some unit test failures asserting certain nodes appear in the graph (e.g. add, mm, addmm) and checking if something's really broken or just the tests need to be fixed.

**Comment by albanD** [comment]
>  However we have some testing infra asserting that the outputs from eager and scripting mode are the same.

IIRC the jit is doing optimization like constant propagation or peephole optimization. So you can't guarantee bit-perfect equality in general no?

> I hit some unit test failures asserting certain nodes appear in the graph (e.g. add, mm, addmm) and checking if something's really broken or just the tests need to be fixed.

I don't know about the jit testing :/ 
I think one of the reason this was not merged is that some jit passes are looking for this collection of ops to merge them with things that are around.  But you'll need to ask someone more familiar with the jit I'm afraid :/

**Comment by qizzzh** [comment]
Yeah I don't know what kind of expectation we should have. Personally I think at each nn.functional function level it should match however I agree for such comparison torch.allclose is probably the one to use.

**Comment by eellison** [comment]
@qizzzh we do have automated testing that eager & script return equivalent results. I think  maybe https://github.com/pytorch/pytorch/issues/20734 is the blocker for changing the linear implementation ? I'm not fully sure.

As @albanD mentioned, we don't guarantee bitwise equality so in internal testing we recommend using assert_all_close. Closing, feel free to reopen if there is more to discuss.

**Comment by qizzzh** [comment]
@eellison I think it's only triggered in some cases, e.g. the example above. I just found another internal case where torch.allclose with default rtol and atol would fail and I had to lower atol to 1e-07. I'm worried that the difference would propagate through layers and amplified in some cases and cause larger discrepancies.

**Comment by albanD** [comment]
@qizzzh we actually have quite a few functions that exhibit such precision limitations. We even have some that are non-deterministic and running them twice in a row will give such difference. I don't think you should rely on bit-wise equality in general I'm afraid.

**Comment by qizzzh** [comment]
@albanD  I see. Our internal testing infra tests all modules commonly used internally and so far functional linear is the only one that has this issue. I'm not sure how much model quality issue it may cause thus opened this issue. I'm fine closing it for now.
