### ISSUE TITLE
RuntimeError: invalid argument 2: Source tensor is empty, on Variable indexing

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#4386]
odd difference between cuda Tensor and Variable:

```python
import torch
from torch.autograd import Variable

a = Variable(torch.randn(8,6).cuda())
b = Variable(torch.randn(8,6).cuda())

print('passes')
b.data[a.data == 0] == 0

print('fails')
b[a == 0] = 0
```

encountered in torch.distributions.Categorical, built yesterday from master

**Comment by vadimkantorov** [comment]
related to https://github.com/pytorch/pytorch/issues/2027?

**Comment by colesbury** [comment]
@vadimkantorov  different code path but similar issue

**Comment by jekbradbury** [comment]
This is a regression from the latest 0.3 binaries, which don't have this error.
