### ISSUE TITLE
In profiler, recorded block's total time can be less than the operators within the block

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#43868]
## 🐛 Bug

In the following code:

```
import torch
with torch.autograd.profiler.profile() as prof:
    with torch.autograd.profiler.record_function("##forward##") as rf:
        t1, t2 = torch.ones(1), torch.ones(1)
        t = torch.add(t1, t2)
        t = torch.mul(t, t)
        t = t.relu()
        t = t.sigmoid()

function_events = prof.function_events
rf_event = [e for e in function_events if "##forward##" in e.name][0]
remaining = set(function_events)  - {rf_event}
remaining_time = sum(e.self_cpu_time_total for e in remaining)
rf_time = rf_event.self_cpu_time_total

if rf_time < remaining_time:
    print(f"Record function scope time was {rf_time} which is less than opts in the block {remaining_time}")
```

it is possible that the CPU time for `record_function` (which is supposed to start before and end after all the user-invoked operators in this code) is greater than the sum of the rest of the events. This doesn't seem like a great user experience since we would like record_function to only profile operators invoked by the user within the scope, but looking at the CPU times this does not appear true.

This is likely due to a few more profiling events being recorded when we create the internal `RecordFunction` object through a `at::cpp:custom_type_hack`. This requires creating an empty tensor and thus produces more profiled ops. However, this profiling should ideally not be there (or it should be disabled/denylisted) since this is an internal implementation detail. The appropriate fix for this is likely to move `RecordFunction` to use custom classes as mentioned in https://github.com/pytorch/pytorch/issues/35026

## To Reproduce

Run the above code.

**Comment by sraikund16** [comment]
Closing as custom_type_hack is deprecated and issue seems stale
