### ISSUE TITLE
Normal and Categorical distribution have inconsistent behaviors with log_prob()

### ISSUE THREAD

**Issue by dbsxdbsx** [pytorch/pytorch#43878]
- PyTorch Version  1.6
 - OS (e.g., Linux): win10
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.2, 7.6

Here I am referring to the inconsistent output shapes when using log_prob() with Normal and Categorical distributions.  
Code for reference:
```
import torch

if __name__ == "__main__":
	# for Categorical
	probs = torch.tensor([[0.4, 0.6],[0.3, 0.7]])
	dist = torch.distributions.Categorical(probs)

	a = torch.tensor([[1],[0]])
	output = dist.log_prob(a)
	print(output.size())  # output torch.Size([2, 2]),expecting torch.Size([2, 1])

	a = torch.tensor([1,0])
	output = dist.log_prob(a)
	print(output.size())# output torch.Size([2]),OK


	# for normal
	means = torch.tensor([[0.0538], [0.0651]])
	stds = torch.tensor([[0.7865], [0.7792]])
	dist = torch.distributions.Normal(means,stds)

	a = torch.tensor([[1.2],[3.4]])
	output = dist.log_prob(a)
	print(output.size())# output torch.Size([2, 1]),OK

	a = torch.tensor([1.2,3.4])
	output = dist.log_prob(a)
	print(output.size())# output torch.Size([2, 2]), expecting torch.Size([2])
```
Though it could be worked around, I treat it as a bug, as this gives users weird feeling on dealing with the same interface.
And I also found some user has already noticed it:
[link1](https://discuss.pytorch.org/t/understanding-log-prob-for-normal-distribution-in-pytorch/73809/2), [link2](https://stackoverflow.com/questions/60765000/understanding-log-prob-for-normal-distribution-in-pytorch)
Hopefully, this could be fixed.

cc @ezyang @gchanan @zou3519 @vincentqb @fritzo @neerajprad @alicanb @vishwakftw

**Comment by ezyang** [comment]
Speculatively updated priority based on other reports

**Comment by fritzo** [comment]
Hi @dbsxdbsx , `Categorical` and `Normal` behave as intended. For more details see Pyro's [shapes tutorial](https://pyro.ai/examples/tensor_shapes.html), the original [torch.distributions design doc](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit?usp=sharing), or the [tensorflow probability distributions](https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes) whose interface we aimed to be compatible with.

To understand your examples, I suggest examining the `.batch_shape` and `.event_shape` attributes of each distribution.
```py
from pyro.distributions.utils import broadcast_shape

# for Categorical
probs = torch.tensor([[0.4, 0.6],[0.3, 0.7]])
dist = torch.distributions.Categorical(probs)
assert dist.batch_shape == (2,)
assert dist.event_shape == (2,)

a = torch.tensor([[1],[0]])
assert a.shape == (2, 1)  # this is effectively a batch shape
output = dist.log_prob(a)
assert output.shape == (2, 2)
assert output.shape == broadcast_shape(dist.batch_shape, a.shape)

a = torch.tensor([1,0])
output = dist.log_prob(a)
assert output.shape == (2,)
assert output.shape == broadcast_shape(dist.batch_shape, a.shape)
```

**Comment by dbsxdbsx** [comment]
@fritzo, does that mean It is impossible to get same shape by log_prob between normal and categorical, unless modify the shape of input `action`  respectively?

**Comment by fritzo** [comment]
@dbsxdbsx I'm not sure I understand your question. `Categorical` and `Normal` take different kinds of parameters: `Categorical` accepts a vector of probabilities whereas `Normal` accepts a scalar `loc` and a scalar `scale`. Because of those differences, the `.batch_shape` of your examples is different:
```py
>>> Categorical(tensor([[0.4, 0.6],[0.3, 0.7]])).batch_shape
torch.Size([2])
>>> Normal(torch.tensor([[0.0538], [0.0651]]),
...        torch.tensor([[0.7865], [0.7792]])).batch_shape
torch.Size([2,1])
```
If instead you create distributions with identical `batch_shape` then their `.log_prob().shape`s will agree. Again I recommend reading more deeply about the difference between `.event_shape` and `.batch_shape`.

**Comment by dbsxdbsx** [comment]
@fritzo , thanks.
