### ISSUE TITLE
floor_divide truncates instead of flooring

### ISSUE THREAD

**Issue by jackm321** [pytorch/pytorch#43874]
## 🐛 Bug

PyTorch's floor_divide (//) operator doesn't match Python's behavior on negative numbers. Python floors (rounds down) while PyTorch truncates (rounds towards zero).

## To Reproduce

```Python
import torch
import numpy as np

print("python -3//2 =", -3 // 2)
print("numpy -3//2 =", np.array((-3)) // 2)
print("pytorch -3//2 =", torch.tensor([-3]) // 2)

# output:
# python -3//2 = -2
# numpy -3//2 = -2
# pytorch -3//2 = tensor([-1])
```

## Expected behavior

Expect PyTorch's floor_divide to match Python // operator by flooring division results instead of truncating them.

## Environment
```

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: Python 3.7.5
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information:
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by jackm321** [comment]
cc @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @jackm321. Let me know if you need a fix super urgently, otherwise it'll probably take a few days.

**Comment by jackm321** [comment]
Thanks for looking into it @mruberry! Fix isn't needed urgently

**Comment by mruberry** [comment]
This will need to be deprecated, as libraries like CrypTen are relying on the current behavior.

**Comment by peterbell10** [comment]
From discussion with @mruberry, the plan of attack is:
- Extend `torch.divide` to accept an argument controlling rounding mode (possibly `rounding_mode='floor'` or similar). This can include true divide, floor, trunc.
- Issue a warning from `torch.floor_divide` (and by extension `Tensor.__floordiv__`) about this issue and direct people to use the new `torch.divide` argument instead.
- In a future release, raise an error from `torch.floor_divide` in cases where the division result is negative and so floor vs truncate makes a difference.
- Finally, once users no longer rely on `torch.floor_divide` for negative results, fix the rounding behavior to use real floor rounding.

**Comment by maxwellzh** [comment]
It seems that this bug remains in torch 1.8.0. 

```
>>> torch.tensor(-308)//20
tensor(-15)
>>> -308//20
-16
```

**Comment by peterbell10** [comment]
@mruberry it looks like the `floor_divide` deprecation didn't make it into 1.8?

**Comment by mruberry** [comment]
> @mruberry it looks like the `floor_divide` deprecation didn't make it into 1.8?

Unfortunately we don't warn that floor_divide() is deprecated in 1.8 (we start in 1.9), but in 1.8 we do have the rounding_mode argument for torch.div(), which will be the recommended way to deal with this:

```
torch.tensor(5) // -3
: -1

torch.div(torch.tensor(5), -3, rounding_mode='floor')
: -2
```

See https://pytorch.org/docs/master/generated/torch.div.html?highlight=div#torch.div.

We'll have to follow-up on this deprecation (and others) for 1.9.

**Comment by nils-werner** [comment]
What is the deprecation plan with this? Do you want to eventually

 1. get rid of `Tensor.__floordiv__` entirely, or
 2. change

    ```
    Tensor.__floordiv__ = torch.div(a, b, rounding_mode='trunc')
    ```

    to become

    ```
    Tensor.__floordiv__ = torch.div(a, b, rounding_mode='floor')
    ```

**Comment by mruberry** [comment]
@nils-werner For now we encourage users to follow the deprecation note and replace uses of floor division with a call to `div()` and the appropriate rounding mode.

In the future I expect we'll update `floor_divide()` to work as it does now but throw an error if the result would differ from floor division. This may be a significant performance penalty for models that have not updated. After that we'll update `floor_divide()` to actually perform floor division.

We don't want to just change the behavior because we want to avoid silently breaking user programs, which is why our typical policy is WARN BREAK CHANGE.

**Comment by nils-werner** [comment]
Hm, that is unfortunate, because I would guess that a very common scenario for floor div is in indexing

```python
y[..., N // 2:] += X
```

which now becomes very cumbersome and unreadable

```python
y[..., torch.div(N, 2, rounding_mode='floor'):] += X
```

**Comment by mruberry** [comment]
> Hm, that is unfortunate, because I would guess that a very common scenario for floor div is in indexing
> 
> ```python
> y[..., N // 2:] += X
> ```
> 
> which now becomes very cumbersome and unreadable
> 
> ```python
> y[..., torch.div(N, 2, rounding_mode='floor'):] += X
> ```

Yep; it's a pain when operators are implementing incorrectly and painful that we have to change them.
