### ISSUE TITLE
Enable Python code coverage on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#43897]
Add new config or modify existing one to run and report python code coverage on Windows

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by guyang3532** [comment]
What should I do to set up the codecov job for windows? @malfet  Any suggestion?

**Comment by malfet** [comment]
@guyang3532 It should be pretty simple:
- Add `coverage` and `codecov` packages to
https://github.com/pytorch/pytorch/blob/8acce55015db3ffd0f07a64341f6b7fec0a1e47d/.jenkins/pytorch/win-test-helpers/setup_pytorch_env.bat#L42
- Add `export PYTORCH_COLLECT_COVERAGE=1` to https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/win-test.sh
- Run `python3 -mcodecov` after tests have finished. For Linux I did it in "Report results" stage:
https://github.com/pytorch/pytorch/blob/8acce55015db3ffd0f07a64341f6b7fec0a1e47d/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml#L212-L216
But for Windows it can be done differently (especially considering that reports do not need to be extracted from within the docker image)
