### ISSUE TITLE
Fallback kernel for Autograd dispatch key. 

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#43908]
Currently we register `fallthrough` as fallback kernel for `Autograd` key. Per discussion on VC, it should be replaced by a kernel that "redispatches without Autograd keys". 

The main use case for it is:
for backend extenders, when they register a kernel to PrivateUse1 that can handle autograd, they get autograd support without explicitly registering to `AutogradPrivateUse1` key. 

cc: @bhosmer @ezyang

**Comment by bhosmer** [comment]
The big dependency here is full boxed fallback support, i.e. 100% boxing and unboxing coverage (boxing to call the boxed fallback from an unboxed context, unboxing to call the backend kernel for the forward pass). 

This boxing/unboxing work is tracked in https://github.com/pytorch/pytorch/issues/32366. cc @smessmer in case we need to refresh status there.

BTW one key detail - the fallback we want to register would
- redispatch without Autograd keys to run the forward kernel
- install a call to an error-raising kernel for the result's backward()

This would improve the current behavior, by running the forward kernel as today, but ensuring that calling backward() on the result produces a meaningful error.

**Comment by ailzhang** [comment]
Followup from discussion with @smessmer : c10-fullness is done, but this fallback kernel is still blocked by "handling Tensor reference in stack execution" so we cannot implement this yet. 

Additional note: 
1. why don't we just remove the fallthrough fallback? why do we need to redispatch? 
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/op_registration/op_registration_test.cpp#L1793 presents a "reasonable" use case. Redispatching from autograd kernel doesn't fully align with our design trying to separate training and inference, but it's a behavior people relied on and we don't want to break in the short term. For example, quantized kernels heavily relies on this by only registering kernels to backend.

**Comment by bdhirsh** [comment]
This behavior should actually be fixed as part of https://github.com/pytorch/pytorch/pull/68744. Specifically, if we have:

```
auto m1 = MAKE_TORCH_LIBRARY_IMPL(_, AutogradPrivateUse1);
m1.fallback(CppFunction::makeFallthrough());

auto m = MAKE_TORCH_LIBRARY(test);
m.def("fn", torch::dispatch(c10::DispatchKey::PrivateUse1, &private_use_func);
m.impl("fn", &composite_func);

op(
  dummyTensor(c10::DispatchKey::PrivateUse1, /*requires_grad=*/true),
  dummyTensor(c10::DispatchKey::CPU, /*requires_grad=*/true));
```

Then with the new behavior in the linked PR, we will see that `AutogradPrivateUse1` has a fallthrough registered, skip the `AutogradFunctionality` functionality key, and end up dispatching to the dense `PrivateUse1` key.
