### ISSUE TITLE
PyTorch+Windows: is parallelization over multiple GPUs possible?

### ISSUE THREAD

**Issue by Apogentus** [pytorch/pytorch#4391]
I have 2 GPUs, but can't run [a simple parallelization official demo of PyTorch](http://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html). I am using Python 3.6.1, PyTorch 0.2.1+a4fc05a, Windows 7 64 bit, anaconda 4.3.30.

I get the following error:

```
C:\Development\Anaconda3\lib\site-packages\torch\cuda\nccl.py in
_libnccl()
     13     global lib
     14     if lib is None:
---> 15         lib = ctypes.pydll.LoadLibrary(None)
     16         if hasattr(lib, 'ncclCommDestroy'):
     17             lib.ncclCommDestroy.restype = None

C:\Development\Anaconda3\lib\ctypes\__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

C:\Development\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

TypeError: bad argument type for built-in operation

```

Here is [an extended statement of the question with the source code.](https://stackoverflow.com/questions/48012816/pytorchwindows-is-parallelization-over-multiple-gpus-possible)

**Comment by apaszke** [comment]
We do not officially support Windows yet, so we won't actively look into this issue. I'll keep it open as a reference to track what needs to be fixed before we release official Windows packages.

**Comment by ezyang** [comment]
CC @peterjc123

**Comment by peterjc123** [comment]
@Apogentus No, it's not supported. Nvidia doesn't provide nccl2 support for Windows. So there's no way to make it work on Windows.
