### ISSUE TITLE
Breakage caused by #42629

### ISSUE THREAD

**Issue by zcain117** [pytorch/pytorch#43918]
## 🐛 Bug

[this line](https://github.com/pytorch/pytorch/blob/master/tools/codegen/model.py#L3) is causing a crash when we try to build pytorch.

Crash looks like this:
```
Step #0: [91mTraceback (most recent call last):
Step #0:   File "/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Step #0:     "__main__", mod_spec)
Step #0:   File "/root/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
Step #0:     exec(code, run_globals)
Step #0:   File "/pytorch/tools/codegen/gen.py", line 14, in <module>
Step #0:     from tools.codegen.model import *
Step #0:   File "/pytorch/tools/codegen/model.py", line 3, in <module>
Step #0:     from dataclasses import dataclass
Step #0: ModuleNotFoundError: No module named 'dataclasses'
```

(all times in US/West)
Our 7AM, 8AM builds and earlier were all fine but 9AM, 10AM, 11AM builds all crashed with that same traceback.

The new import was added in https://github.com/pytorch/pytorch/pull/42629/files which I think went in between 8AM and 9AM today

## To Reproduce

See command below:
`Step #0: subprocess.CalledProcessError: Command '['cmake', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/pytorch/torch', '-DCMAKE_PREFIX_PATH=/../', '-DNUMPY_INCLUDE_DIR=/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/root/anaconda3/envs/pytorch/bin/python', '-DPYTHON_INCLUDE_DIR=/root/anaconda3/envs/pytorch/include/python3.6m', '-DPYTHON_LIBRARY=/root/anaconda3/envs/pytorch/lib/libpython3.6m.so.1.0', '-DTORCH_BUILD_VERSION=1.7.0a0+6ea8916', '-DUSE_CUDA=0', '-DUSE_NUMPY=True', '/pytorch']' returned non-zero exit status 1.`

`Step #0: The command '/bin/sh -c cd /pytorch && bash xla/scripts/build_torch_wheels.sh ${python_version} ${release_version}' returned a non-zero code: 1`

See here if needed for `build_torch_wheels.sh`: https://github.com/pytorch/xla/blob/master/scripts/build_torch_wheels.sh

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): building from master
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): see above under 'reproduce'
 - Python version: 3.6

**Comment by zcain117** [comment]
maybe easier to read for build command used:

`cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/pytorch/torch -DCMAKE_PREFIX_PATH=/../ -DNUMPY_INCLUDE_DIR=/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/root/anaconda3/envs/pytorch/bin/python -DPYTHON_INCLUDE_DIR=/root/anaconda3/envs/pytorch/include/python3.6m -DPYTHON_LIBRARY=/root/anaconda3/envs/pytorch/lib/libpython3.6m.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0+7680d87 -DUSE_CUDA=0 -DUSE_NUMPY=True /pytorch`

**Comment by ailzhang** [comment]
@zcain117 please try `conda install dataclasses` in the CircleCi environment?

**Comment by zcain117** [comment]
`conda install dataclasses` in our build script seems to have fixed this.

Thanks @ailzhang !
