### ISSUE TITLE
String defaults aren't handled well in native_functions.yaml

### ISSUE THREAD

**Issue by bhosmer** [pytorch/pytorch#43944]
A signature containing a string-typed argument with a literal default will get emitted to C++ without escaping the double quotes, i.e. 
```
- func: myop(Tensor self, str s="HEY") -> Tensor
```
will emit
```
m.def("myop(Tensor self, str s="HEY") -> Tensor")
```
with the ensuing hilarity. Escaping the schema strings is easy, not sure what other issues might need to be dealt with around the initializers themselves. OTOH if we want to explicitly disallow string defaults[1], we should error at codegen time.

[1] though e.g. they're the obvious route to avoiding python facades in #42190

**Comment by ezyang** [comment]
But please see also https://github.com/pytorch/pytorch/issues/24343

**Comment by ezyang** [comment]
And make sure you read https://github.com/pytorch/pytorch/pull/42190#issuecomment-684670796
