### ISSUE TITLE
[jit] return type Any does not work for ternary operators

### ISSUE THREAD

**Issue by chenbohua3** [pytorch/pytorch#43942]
## To Reproduce

this module can be exported to torchscript:
```
class MyModule(torch.nn.Module):
    def forward(self) -> Any:
        if self.training:
            return 'xx'
        else:
            return {}
```

this module can not:
```
class MyModule(torch.nn.Module):
    def forward(self) -> Any:
        return 'xx' if self.training else {}
```
and we will get `if-expression's true branch has type str but false branch has type Dict[str, Tensor]:`

## Environment

 - PyTorch Version (e.g., 1.0): commit 8a41fa47187c5533a639b34478c10a44641a4db9
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): described [here](https://github.com/pytorch/pytorch#from-source)
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0/7.6.5

cc @gmagogsfm

**Comment by chenbohua3** [comment]
@SplitInfinity

**Comment by eellison** [comment]
Code pointers: the  type unification for emitting ternary ops should be more similar to how we unify  output types when emitting if nodes

**Comment by eellison** [comment]
For a first-step fix to this, I would try to fix:
```out: Any = 'xx' if self.training else {}
return out
```
