### ISSUE TITLE
caffe2/aten bridge doesn't handle overloads with ambiguous defaulting

### ISSUE THREAD

**Issue by bhosmer** [pytorch/pytorch#43945]
The bridge infra generated by [gen_op.py](https://github.com/pytorch/pytorch/blob/master/caffe2/contrib/aten/gen_op.py) isn't designed to handle calls to multiple op overloads whose defaulting may produce ambiguous calls. For example, the two overloads
```
- func: ambig.a(Tensor self, int? i=0) -> Tensor

- func: ambig.b(Tensor self, bool? b=False) -> Tensor
```
will produce (among others) a binding that contains the C++ call `ambig(self)`, resulting in a C++ compiler error. 

This can prevent intuitive overloading schemes from working (see e.g. #42190). It should be possible to disambiguate by supplying default arguments explicitly. 

cc @ezyang @bhosmer @smessmer @ljk53

**Comment by peterbell10** [comment]
Also, in the case of #42190 it's would be possible to avoid ambiguity if the schema allowed default arguments to the left of non-defaulted arguments. e.g.
```
ambig.1(Tensor self, int? a=0, int? b=1)
ambig.2(Tensor self, int? a=0, str b)
```

Any call that doesn't pass `b` should unambiguously call overload `1`. But the schema won't allow `a` to have a default. `a`'s default wouldn't make sense in C++, but with python named arguments it's entirely possible to specify `b` but not `a`.

**Comment by bhosmer** [comment]
> Also, in the case of #42190 it would be possible to avoid ambiguity if the schema allowed default arguments to the left of non-defaulted arguments. e.g.

Hi @peterbell10 - the problem with this is that it makes the defaulting unusable in a positional call - that's why we follow Python in only allowing out of order defaulting in keyword-only args:

```
>>> def f(x, y=0, z):
...     return x, y, z
...
  File "<stdin>", line 1
SyntaxError: non-default argument follows default argument
>>>
>>> def f(x, *, y=0, z):
...     return x, y, z
...
>>> 
```
Anyway though, I think the big picture is that you shouldn't have to be playing games with defaulting just to avoid ambiguity in generated code (if it can be avoided) :)

**Comment by peterbell10** [comment]
When you consider the overload set as a whole, `b` does have a default value though. The python equivalent would be `b: Union[int, str] = 0`.

**Comment by bhosmer** [comment]
> When you consider the overload set as a whole, `b` does have a default value though. The python equivalent would be `b: Union[int, str] = 0`.

Ah sure, you're right of course. But I don't think we want this sort of emergent property as part of the rules for legal overload signatures - nonlocal effects and so on, not to mention the complexity of validation. (Plus, the behavior would need to map onto C++ API in a reasonable way.) 

In general I think there's a lot of simplicity benefit to defining validity as a context-free property of an overload signature, and solve expressiveness issues like the one you're facing in 42190 by other means if we can. :)
