### ISSUE TITLE
RuntimeError: Function 'MmBackward' returned nan values in its 1th output.

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [pytorch/pytorch#43955]
## 🐛 Bug

``torch.nn.NLLLoss()'' got NAN results during training;
and with the help of setting ``torch.autograd.set_detect_anomaly(True)'', I got detailed information as following:
![image](https://user-images.githubusercontent.com/17181332/91881795-58ec3480-ec82-11ea-8695-7e673c058a65.png)
Besides, I have checked there is no NAN in ``pred'', Min -15.9585218, Max -0.0000008.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.0
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: V100
 - Any other relevant information:

## Additional context

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by ezyang** [comment]
If you could provide us some sort of reproduction that would be very helpful for diagnosing the problem.

**Comment by zhiqiangzhongddu** [comment]
> If you could provide us some sort of reproduction that would be very helpful for diagnosing the problem.

I'm trying to generate a demo program but seems not convenient. 
Another may be useful information: the same code runs fluently on Windows 10 but appears this problem on Linux, with the same environment.

**Comment by albanD** [comment]
Are you sure that all the inputs you give to embedding are valid? no nan in there or in the weights?

**Comment by zhiqiangzhongddu** [comment]
> Are you sure that all the inputs you give to embedding are valid? no nan in there or in the weights?

Thanks for your reminder! I just checked NAN in pred but ignored embedding vectors. 
I found there exists NAN in generated embedding. The max --> inf or the min --> nan. So what's the possible solution in your opinion, add a normalize layer in the NN?

**Comment by zhiqiangzhongddu** [comment]
I solved this problem by deleting torch.empty() in code (inside of NN).
I guess it might because of byte overflow. 

Thanks for your kindly answers.

**Comment by onlinehuazai** [comment]
> I solved this problem by deleting torch.empty() in code (inside of NN).
> I guess it might because of byte overflow.
> 
> Thanks for your kindly answers.

do you deal with the problem?
