### ISSUE TITLE
NHWC AdaptiveAvgPool2d w/ AMP produces NaN output in certain cases

### ISSUE THREAD

**Issue by rwightman** [pytorch/pytorch#43992]
## 🐛 Bug

A number of models I mantain that utilize Squeeze-and-Excitation layers containing AdaptiveAvgPool2d produce NaNs during validation when using `memory_format=torch.channels_last` with either APEX or native Torch AMP. The behaviour is not present in FP32 with either memory format or in mixed-prec w/ default memory_format. 

```
class SEModule(nn.Module):
    def __init__(self, channels, reduction=16, min_channels=8):
        super(SEModule, self).__init__()
        reduction_channels = max(channels // reduction, min_channels)
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc1 = nn.Conv2d(channels, reduction_channels, kernel_size=1, bias=True)
        self.act = nn.ReLU(inplace=True)
        self.fc2 = nn.Conv2d(reduction_channels, channels, kernel_size=1, bias=True)
        self.gate = nn.Sigmoid()
    def forward(self, x):
        x_se = self.avg_pool(x)
        x_se = self.fc1(x_se)
        x_se = self.act(x_se)
        x_se = self.fc2(x_se)
        return x * self.gate(x_se)
```

The problem is solved by replacing the avg pool with `x.mean((2, 3), keepdim=True)`

## To Reproduce

I've only been able to reproduce with full networks, valid weights loaded. I have not reproduced the issue when the network has random init. The issue is also sensitive to the magnitude of the input, too small and it will not happen.

Training works initially with the same AMP and memory_format, however as the network starts to converge it eventually starts to output NaN.

```
import torch
import timm  # pip install

model = timm.create_model('seresnet50', pretrained=True)
model = model.cuda().to(memory_format=torch.channels_last)
model.eval()

with torch.no_grad():
    for _ in range(1000):
        x = torch.randn(2, 3, 224, 224).cuda().to(memory_format=torch.channels_last) * 10
        with torch.cuda.amp.autocast():
            out = model(x)
            if not torch.isfinite(out).all():
                print('ERROR')
                break
```

## Expected behavior

No NaN

## Environment

NVIDIA PyTorch NGC 20.08 and 20.03 tested. Titan RTX.

**Comment by ngimel** [comment]
Should be fixed by #43986
