### ISSUE TITLE
Implement remaining Variable functions

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#440]
High Priority:

* [x] `repeat`
* [x] `split`
* [x] `std`
* [x] `var`
* [x] `renorm`
* [x] `eq`
* [x] `ge`
* [x] `gt`
* [x] `le`
* [x] `lt`
* [x] `ne`

Mid Priority:
* [x] `cross`
* [x] `cumsum`
* [x] `trace`
* [x] `unfold`
* [x] `cumprod`
* [x] `atan2`
* [ ] `__and__`
* [ ] `__bool__`
* [ ] `__iand__`
* [ ] `__ior__`
* [ ] `__ixor__`
* [ ] `__mod__`
* [ ] `__nonzero__`
* [ ] `__or__`
* [ ] `__xor__`
* [ ] `cauchy`
* [ ] `exponential`
* [ ] `fill`
* [ ] `geometric`
* [ ] `log_normal`
* [ ] `normal`
* [ ] `ones`
* [ ] `random`
* [ ] `uniform`
* [ ] `zero`
* [ ] `zeros`

Wontfix (as in very very low priority, but PRs are welcome!):
* [x] `gesv`
* [x] `inverse`
* [x] `potrf`
* [x] `svd`
* [x] `trtrs`
* [ ] `orgqr`
* [ ] `ormqr`
* [ ] `potri`
* [x] `potrs`
* [x] `pstrf` [NOW DEFUNCT]
* [x] `qr`
* [x] `symeig`
* [ ] `eig`
* [ ] `gels`
* [ ] `geqrf`

**Comment by chenyuntc** [comment]
It seems that `std`, `var`, `renorm` haven't been implemented, see [reduce.py](https://github.com/pytorch/pytorch/blob/master/torch/autograd/_functions/reduce.py#L212,L214). 
I'm still learning PyTorch's source code. Would you mind if I give a try.

**Comment by fmassa** [comment]
@chenyuntc they were implemented using basic autograd operations in [variable.py](https://github.com/pytorch/pytorch/blob/master/torch/autograd/variable.py#L483-L502).

**Comment by fmassa** [comment]
But maybe they can we implemented in a slightly more memory-efficient manner by manually writing the backprop?

**Comment by chenyuntc** [comment]
I try to implement `Var` like this, I don't know whether it's more memory-efficient, but it's a little troublesome to handle `dim = None` in `Tensor`
```python
class Var(Function):
    def __init__(self, dim=None, unbiased=True):
        self.dim = dim
        self.unbiased = unbiased

    def forward(self, input):
        if self.dim is None:
            mean = input.new(1).fill_(input.mean()).view(*(1 for s in input.size()))
        else:
            mean = input.mean(self.dim)
        mean_expanded = mean.expand_as(input)
        zero_centered = input.sub(mean_expanded)
        self.zero_centered = zero_centered
        if self.dim is None:
            var = input.new(1).fill_(zero_centered.mul(zero_centered).sum())
        else:
            var = zero_centered.mul(zero_centered).sum(self.dim)
        numel = input.numel() if self.dim is None else input.size(self.dim)
        self.n = numel - int(self.unbiased)
        return var.div(self.n)

    def backward(self, grad_output):
        # import pdb; pdb.set_trace()
        return grad_output.expand_as(self.zero_centered) * self.zero_centered * (2.0 / self.n)
```

**Comment by fmassa** [comment]
@chenyuntc once you implemented your `Function`, you can use `torch.autograd.gradcheck` to verify the correctness of your implementation (eventually adjusting the `eps` parameter if you are using `float` precision).

**Comment by AjayTalati** [comment]
Is `Softmax` done yet? 

It's needed for (the second-derivative branch) this discrete action implementation of TRPO, (with conjugate gradients),

https://github.com/mjacar/pytorch-trpo

**Comment by fmassa** [comment]
@AjayTalati it's not done yet. For the moment you'd need to use something like
```python
def softmax(input, dim=1):
    input_ex = torch.exp(input)
    return input_ex / input_ex.sum(1).expand_as(input)
```

**Comment by AjayTalati** [comment]
Hi @fmassa thanks a lot :+1:, seems like a nice fix :)

**Comment by JianxinMa** [comment]
Is there any specific reason why **inverse** won't be implemented? Matrix inversion can be useful for implementing models such as Gaussian processes.

**Comment by fmassa** [comment]
@JianxinMa `inverse` was implemented already and is in master, see https://github.com/pytorch/pytorch/pull/1670

**Comment by amoltandel** [comment]
can nonzero be implemented as following:
`def __nonzero__(self):
	return self/self == 1`?

**Comment by samuela** [comment]
Why are `trtrs` and `potrf` marked as wontfix? These are both differentiable operations.

**Comment by apaszke** [comment]
It's not wontfix as in "we will never accept them into autograd". It's just not very high on our priority list and it's not straightforward to write out derivative formulas for them, but if you feel up to it then please send PRs!

**Comment by samuela** [comment]
@soumith @SsnL The two references for Cholesky gradients that I know of are 
* https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf
* https://arxiv.org/abs/1602.07527

It's implemented in tensorflow and autograd here:
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_grad.py#L58
* https://github.com/HIPS/autograd/blob/master/autograd/numpy/linalg.py#L110

I think it's also implemented in stan somewhere as well but I'm not sure where exactly. 

I haven't thought too much about triangular solve gradients yet but I know that they're implemented in tensorflow here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_grad.py#L207.

**Comment by samuela** [comment]
Thanks guys! This is exciting and will definitely end up in my code.

**Comment by SsnL** [comment]
@samuela autograd support potrf is already implemented by @colesbury and in the code base :)

**Comment by samuela** [comment]
@SsnL @colesbury That's awesome. I actually just realized that I need potrf today. When was it implemented/what version should I use? I'm running on version 0.2.0_3 and it doesn't seem to be implemented yet:

```
In [15]: a = torch.randn(3, 3); b = Variable(a @ a.t()); torch.potrf(b)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-2505760d8c68> in <module>()
----> 1 a = torch.randn(3, 3); b = Variable(a @ a.t()); torch.potrf(b)

TypeError: Type Variable doesn't implement stateless method potrf
```

**Comment by samuela** [comment]
Ah was it https://github.com/pytorch/pytorch/commit/14d8c034245708c0c9fb792a955223241ddaee78? It looks like it was committed just a day after the 0.2 release :(

**Comment by fmassa** [comment]
@samuela the next PyTorch release will be out very soon. Or you can build from source

**Comment by samuela** [comment]
@fmassa Okey doke, I'll stay tuned.

**Comment by acgtyrant** [comment]
What about the `new`? I find that it is not listed.

**Comment by acgtyrant** [comment]
`type` and `type_as` is not listed too.

**Comment by weiyangfb** [comment]
What is the current status of this after 0.4's Tensor and Variable merging?

**Comment by SsnL** [comment]
@weiyangfb A bunch of these still needs implementation. I promised long time ago that I would get to potrf, but still haven't got to it. :(

**Comment by samuela** [comment]
I'd like to petition for `potrs`. It should be basically the same as `trtrs` in implementation.

**Comment by ezyang** [comment]
Hi @tyleretchart; add your implementation as a native function in https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native (see the README for guidance) and then associate it with qr in tools/autograd/derivatives.yaml. Let us know if you have more questions!

**Comment by ezyang** [comment]
@tyleretchart Hey Tyler! Did you ever get a chance to attempt adding backwards for qr?

**Comment by tyleretchart** [comment]
Oh sorry! I ended up getting sidetracked by other projects as the Python backwards implementation was enough for that project. Glad it got resolved!

**Comment by gchanan** [comment]
we don't have separate tensor and variable APIs anymore and all the issues/PRs that referenced this have been closed or merged, so I'm closing this.
