### ISSUE TITLE
python value of type 'float' cannot be used as a value in with @torch.jit.script

### ISSUE THREAD

**Issue by emailweixu** [pytorch/pytorch#44013]
## To Reproduce

```python
import torch

value = 0.5

@torch.jit.script
def test(x):
  x[x>0.5] = value 
  # The following doesn't cause error
  # x[x>0.5] = 0.5
  return x
```

Got the following error:
``` text
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-d314a89b06cb> in <module>()
      3 value = 1.
      4 
----> 5 @torch.jit.script
      6 def test(x):
      7   x[x>0.5] = value

/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
   1548         if _rcb is None:
   1549             _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)
-> 1550         fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
   1551         # Forward docstrings
   1552         fn.__doc__ = obj.__doc__

RuntimeError: 
python value of type 'float' cannot be used as a value:
  File "<ipython-input-12-d314a89b06cb>", line 7
@torch.jit.script
def test(x):
  x[x>0.5] = value 
             ~~~~~ <--- HERE
  return x
```

## Expected behavior

There should be no error

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): ubuntu 18.0
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 2080 Ti
 - Any other relevant information:

## Additional context

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
This is because TorchScript doesn't allow capturing global variables. You can use one of the following work-around:

1. Pass value as an argument to function
2. Use a literal constant

**Comment by AlexeyKruglov** [comment]
A working workaround here: https://github.com/pytorch/pytorch/issues/52312 , the first version with `import constmod`.  And seems like `import` there currently cannot be replaced with `from ... import ...`.
