### ISSUE TITLE
Ambiguous description of torch.finfo.tiny

### ISSUE THREAD

**Issue by pomelyu** [pytorch/pytorch#44010]
## 📚 Documentation
Hi

`torch.finfo.tiny` has the description 
> "The smallest positive representable number". 

It's ambiguous, and not the actual smallest positive number. For example, `torch.finfo("torch.float16").tiny` get **6.10e-5**, but the smallest positive representable number in FP16 should be **2^-24** or **5.96e-8**. `numpy.finfo.tiny` also has this problem.

I check the code in [`TypeInfo.cpp`](https://github.com/pytorch/pytorch/blob/0651887eb4fd85ebbf65ab29ff2b634226871fee/torch/csrc/TypeInfo.cpp#L169), it uses `std::numeric_limits<>::min()` to get this value, but it should be `std::numeric_limits<>::denorm_min()` according the [document](http://www.cplusplus.com/reference/limits/numeric_limits/).

I am not sure whether the `tiny` function should be modified or add new function, such as `denorm_tiny`, or just fix the description to be
> "The minimum normalized positive number".

Thanks

cc @jlin27

**Comment by davidbau** [comment]
It is good that pytorch matches numpy's implmentation of "tiny" (as it currently does).

While numpy documentation calls it "The smallest positive usable number" it would be more technically precise to describe `tiny` is the "smallest positive normal number".

If what's needed is the smallest spacing between numbers, maybe it would be useful to implement `numpy.spacing`.

```
import numpy, torch
print(torch.finfo(torch.float).tiny, numpy.finfo(numpy.single).tiny.item())
print(numpy.spacing(numpy.single(0)).item())

1.1754943508222875e-38 1.1754943508222875e-38
1.401298464324817e-45
```
