### ISSUE TITLE
A tiny spelling error in a wiki page within the github repository

### ISSUE THREAD

**Issue by pavelexpertov** [pytorch/pytorch#44019]
## 📚 Documentation
I was reading [this](https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork) wiki page to solve multiprocess issue and I noticed that `Autograd engine relays on threads pool, `, which is the first sentence, probably has a spelling error. 

I think it's supposed to be 'relies' rather than 'relays' because the latter is something to do with sending signals or such and the former means it depends upon something like the threads pool. Plus, I think there could be a link to python documentation to point out that this type of context is actually problematic: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

Also, I think it will be useful to have an explicit import of `multiprocessing` like this:
```python
import multiprocessing as mp

# The rest of code samples.
```

Thanks

cc @jlin27

**Comment by Anoop01234** [comment]
Can I work on it?

**Comment by Anoop01234** [comment]
I would like to work on it!

**Comment by Anoop01234** [comment]
Sir, wiki is not part of the project because when I am forking the project, the wiki section appears to be empty. So do I need to submit the wiki file on mail? Or how am I supposed to do?

**Comment by pavelexpertov** [comment]
That's what I am wondering about. I believe it's the documentation team responsible for writing this. Even though it seems non-trivial for a 'registered' contributor to do so. What do you say @smessmer ?

**Comment by mruberry** [comment]
Thanks for the suggestions, @pavelexpertov, I incorporated your recommendations into the Wiki article https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork.
