### ISSUE TITLE
TypeError: cannot assign 'torch.FloatTensor' as parameter 'layer_weights' (torch.nn.Parameter or None expected)

### ISSUE THREAD

**Issue by rudraksh97** [pytorch/pytorch#44022]
#43835  Issue description
Traceback (most recent call last):
  File "run_techqa_layer.py", line 605, in <module>
    main()
  File "run_techqa_layer.py", line 599, in main
    model = train(args, train_dataset, model, optimizer, tokenizer, model_evaluator)
  File "run_techqa_layer.py", line 211, in train
    outputs = model(**inputs)
  File "C:\Users\Rudraksh\Anaconda3\envs\bert_pre\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\techqa-layer\modeling.py", line 228, in forward
    self.layer_weights = F.softmax(self.layer_weights,dim=0)
  File "C:\Users\Rudraksh\Anaconda3\envs\bert_pre\lib\site-packages\torch\nn\modules\module.py", line 610, in __setattr__
    .format(torch.typename(value), name))
TypeError: cannot assign 'torch.FloatTensor' as parameter 'layer_weights' (torch.nn.Parameter or None expected)

## System info
PyTorch version: 1.2.0
Is debug build: False
CUDA used to build PyTorch: 10.0

OS: Microsoft Windows 10 Education
GCC version: (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.0.130                      0
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py36hb782905_0
[conda] numpy                     1.18.5           py36h4d86e3b_0    conda-forge
[conda] pytorch                   1.2.0           py3.6_cuda100_cudnn7_1    pytorch
[conda] torchvision               0.4.0                py36_cu100    pytorch

**Comment by rudraksh97** [comment]
def forward(self, input_ids=None, attention_mask=None, token_type_ids=None,start_positions=None,end_positions=None):		
		outputs = self.bert(
			input_ids,
			attention_mask=attention_mask,
			token_type_ids=token_type_ids,
		)

		hidden_states = outputs[2]
		stacked_hidden_states = torch.stack(hidden_states)

		self.layer_weights = F.softmax(self.layer_weights,dim=0)

**Comment by kshitij12345** [comment]
```python
self.layer_weights = F.softmax(self.layer_weights,dim=0)
```

This line is  the cause. 
Is that necessary?
Also I believe https://discuss.pytorch.org/ would be the place where you would get better response for this question

**Comment by rudraksh97** [comment]
I have to take the softmax.

**Comment by kshitij12345** [comment]
That should be part of the `__init__` right? Does it need to be `forward`

```python
    def __init__(self, config):
	super(LayeredBertforQA, self).__init__(config)
	self.num_labels = config.num_labels
	self.bert = BertModel(config)
	self.n_weights = config.num_hidden_layers + 1
        l_weights = torch.zeros(self.n_weights,dtype=torch.float,device="cpu")
	self.layer_weights = nn.Parameter(F.softmax(l_weights,dim=0))
	self.qa_outputs = nn.Linear(config.hidden_size, config.num_labels)
	self.options = None
	self.init_weights()	
```
Should do the trick

**Comment by rudraksh97** [comment]
Oh, let my try. This might solve the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by smessmer** [comment]
please reopen if the issue still persists
