### ISSUE TITLE
Some computational efficiency improvements in derivatives

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#4402]
I was going through the `derivatives.yaml` for the derivative of existing functions in `torch`, and feel like some of them are a bit inefficient. Some of them are listed below:

- `reciprocal` : From `grad / -(self * self)` to `- grad * result * result`
- `sqrt`: From `grad * self.pow(-0.5) / 2` to `grad * self.rsqrt() * 0.5` or `grad / (2 * result)`
- `acos`: From `grad * -((-self * self + 1).sqrt().reciprocal())` to `grad * -(self.rsqrt(self * self + 1))` and similarly for `asin`
- `div(Tensor self, Tensor other)`: Modify `other`'s derivative from `-grad * self / (other * other)` to `-grad * result / other`
- `tan`: From `grad / self.cos().pow(2)` to `grad * (1 + result.pow(2))`
- `atan`: From `grad * (self * self + 1).reciprocal()` to `grad / (self * self + 1)`
- `std`: From `grad * (2 * result).reciprocal()` to `grad / (2 * result)`
- `addcdiv`: From `-grad * value * tensor1 / (tensor2 * tensor2)` to `grad * (self - result) / tensor2`

Here I am assuming that a divide operation is costlier than a multiply operation.

Let me know your views about these ops, and I will issue a PR if required. 

- [x] `reciprocal`
- [x] `sqrt`
- [x] `acos`
- [x] `asin`
- [ ] `div`
- [x] `tan`
- [x] `atan`
- [x] `std`
- [ ] `addcdiv`

**Comment by apaszke** [comment]
* `reciprocal` looks good
* `sqrt` looks good (the version with rsqrt is better)
* `acos` + `asin` looks good
* `div` - I'm not sure about this. It would be best to use this version for the regular op, and the one we have right now for the in-place version. I don't think it's possible to do with with our current codegen, as in-place versions are automatically generated from regular definitions (or am I wrong @colesbury?)

**Comment by vishwakftw** [comment]
Thanks. I will open a PR. Current improvements are in:
- [ ] `sqrt`
- [ ] `reciprocal`
- [ ] `acos`
- [ ] `asin`

Please add more, if there are any.

**Comment by colesbury** [comment]
These changes make sense to me.

@apaszke, why would you use the current version of div for in-place?

I have a change that allows different derivatives for in-place functions, but I'd like to avoid special casing too many of the in-place derivatives.

**Comment by vishwakftw** [comment]
I also have one question. Some ops have derivatives defined with `.reciprocal()` and some ops have derivatives with a direct division (`div` or `/`). Is there any difference between `.reciprocal()` and the standard `div`?

**Comment by apaszke** [comment]
Oh my bad. The new definition would be actually much more efficient for in-place. Not sure why I thought differently. Sorry @colesbury 

@vishwakftw `x.reciprocal()` is equivalent to `1 / x`, but more efficient. On the other hand `y / x` is more efficient than `y * x.reciprocal()`.

**Comment by vishwakftw** [comment]
Considering the differences between `reciprocal()` and `div()`, I have made a few more changes in the latest PR.
