### ISSUE TITLE
C++ torch::min_values, torch::max_values no longer found in current libtorch

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#44069]
_min_values()_  & _max_values()_ no longer found in the torch namespace
(they are there in libtorch 1.6)

e.g. errors like:

`fatal error: no member named 'max_values' in namespace 'torch'`

Possible due to the recent commit: #42004 ,
or is there a new name or workaround?

Thanks

**Comment by VinodSKumar** [comment]
In the latest version, the following equivalents are available torch::amin and torch::amax.

**Comment by meganset** [comment]
ah.
amin/amax.

thanks a lot.
