### ISSUE TITLE
disable instruction set when build libtorch

### ISSUE THREAD

**Issue by louweijia** [pytorch/pytorch#44104]
## ❓ Questions and Help

My work host have all instruction sets, but service hosts are not support service host, such as 'AVX' and 'SSE4', so i want to disable the instruction set before build libtorch. How can I do it?

cc @malfet @seemethere @walterddr @yf225 @glaringlee @jlin27

**Comment by malfet** [comment]
PyTorch should not have an AVX instruction in the default codepath, so compiling in the host that supports AVX is fine. But if you want to avoid compiling the code that contains AVX/AVX2 instruction, you can try to build with DISABLE_AVX/DISABLE_AVX2/C_AVX_FOUND/C_AVX2_FOUND set to OFF
