### ISSUE TITLE
Compilation error from source

### ISSUE THREAD

**Issue by KaaPex** [pytorch/pytorch#4410]
Using Ubuntu 17
The C compiler identification is GNU 4.8.5
The CXX compiler identification is GNU 4.8.5

```
/home/develop_kaa/pytorch/aten/src/ATen/Half.h(45): error: namespace "std" has no member "to_string"

/home/develop_kaa/pytorch/aten/src/ATen/Half.h(31): error: namespace "std" has no member "isinf"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]"
/home/develop_kaa/pytorch/aten/src/ATen/Scalar.h(75): here

/home/develop_kaa/pytorch/aten/src/ATen/Half.h(34): error: namespace "std" has no member "isnan"
          detected during instantiation of "To at::checked_convert<To,From>(From, const char *) [with To=uint8_t, From=double]"
/home/develop_kaa/pytorch/aten/src/ATen/Scalar.h(75): here

3 errors detected in the compilation of "/tmp/tmpxft_00006849_00000000-6_IndexUtils.cpp1.ii".
CMake Error at ATen_generated_IndexUtils.cu.o.cmake:267 (message):
  Error generating file
  /home/develop_kaa/pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/cuda/detail/./ATen_generated_IndexUtils.cu.o


src/ATen/CMakeFiles/ATen.dir/build.make:1113: recipe for target 'src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o' failed
```

**Comment by KaaPex** [comment]
I am trying gcc-5.4.1 and 6.4.0 same problem

**Comment by apaszke** [comment]
Can you try pulling master and rebuilding it? I looked at the file and I all the errors you're seeing mean that you might not have complete C++11 support in your includes. It builds fine for me on GCC5.

**Comment by KaaPex** [comment]
The gcc cant use C++11, only with flag -lstdc++, but -std=c++11 did't work for me

**Comment by KaaPex** [comment]
Well using clang-5.0 and clang++-5.0 helps me install torch from source, now i have:
Cuda-9.1
cudnn-7.0.5
torch-0.4.0

**Comment by apaszke** [comment]
Well you need a compiler with C++11 support to build PyTorch. `-std=c++11` is necessary. I haven't heard of similar issues. It's really weird and it might be a result of having your compiler pick up a wrong directory for includes (since you have multiple installed). Make sure you can compile other C++11 programs. We've never been defining such a flag.

**Comment by KaaPex** [comment]
After install older version gcc-5.4.0, all passed without error, now i have:
cuda 9.1 
cudnn 7.0.5
torch 0.4.0
