### ISSUE TITLE
Code coverage tool not capturing ONNX tests

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#44120]
## 🐛 Bug

Looks like the code coverage tool for CI is producing false alarm. The tool shows most parts of the source code related to ONNX and exporter are not covered by tests. But we have confirmed manually that these code lines (or a majority of them) are covered by tests. 

See the screenshots below showing code that's not tested in red, for file torch/onnx/symbolic_opset9.py

![image](https://user-images.githubusercontent.com/16928382/92146115-1899cd00-edce-11ea-96eb-24a30d04d278.png)

And here is a sample ONNX PR which has CI failures related to code coverage:
https://github.com/pytorch/pytorch/pull/43670/files
There's a comment in there left by Codecov bot that flags line 394 as not being covered. I verified the test coverage for this PR has manually, and looks like this is a false alarm. 

## Expected behavior

The code coverage tool should capture all the tests under test/onnx to assess the coverage  correctly.
This is currently causing as a CI job failure on all the PRs on ONNX side.

cc @ezyang @seemethere @malfet @walterddr @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
cc @bzinodev 
Would you please help us find the contact who can address this?

**Comment by spandantiwari** [comment]
@bzinodev - is there someone who can look into this issue?

**Comment by ezyang** [comment]
My guess is that the ONNX tests are only running on one particular CI config, which is not the one that is populating coverage information. 

cc @malfet

**Comment by malfet** [comment]
That's correct, code coverage is currently running only on for one configuration, i.e. pytorch_linux_bionic_py3_8_gcc9_coverage_test. I can easily add subset of ONNX tests there, or enable Python code coverage collection during ONNX test runs

**Comment by neginraoof** [comment]
Hi @janeyx99 and @malfet 
Thanks for sending the updates to code coverage tool.
These updates have helped including Caffe2 tests, but we're still seeing ONNX test not covered by the tool. 
Here is an example of code coverage report for ONNX on @janeyx99 's PR: https://codecov.io/gh/pytorch/pytorch/compare/a49367e9c9fcfa9547782420a24441f13fef19dc...544f1274d9fe5b2a28e5f45d2896962e9e3a2e49/tree/torch/onnx

https://codecov.io/gh/pytorch/pytorch/compare/a49367e9c9fcfa9547782420a24441f13fef19dc...544f1274d9fe5b2a28e5f45d2896962e9e3a2e49/src/torch/onnx/symbolic_opset9.py

This is still showing a major part of the body of the ONNX exporter code uncovered. Would you please take a look?
Thanks!

**Comment by neginraoof** [comment]
@janeyx99 @malfet 
We're still seeing the coverage tool is not covering the ONNX code: https://codecov.io/gh/pytorch/pytorch/tree/master/torch/onnx
Would you be able to help us with this issue?
Thanks

**Comment by malfet** [comment]
Thank you for reporting. The config looks correct now, so I guess it is a problem on either the collecting or reporting tools.
@janeyx99 can you please modify CI scripts to preserve coverage files as test artifacts?

**Comment by shubhambhokare1** [comment]
Closing this, internal issue.
