### ISSUE TITLE
How to use net.cuda() when Network class has list or dict wich contains nn layers?

### ISSUE THREAD

**Issue by AlexHex7** [pytorch/pytorch#4412]
For example

```
class Network(nn.Module):
    def __init__(self,):
        super(RegionLayer, self).__init__()
        self.convs = [nn.Sequential(
            nn.Conv2d(in_channels=self.in_channels, out_channels=self.in_channels,
                      kernel_size=3, stride=1, padding=1),
            nn.Conv2d(in_channels=self.in_channels, out_channels=self.in_channels,
                      kernel_size=3, stride=1, padding=1),
        ),
        nn.Sequential(
            nn.Conv2d(in_channels=self.in_channels, out_channels=self.in_channels,
                      kernel_size=3, stride=1, padding=1),
            nn.Conv2d(in_channels=self.in_channels, out_channels=self.in_channels,
                      kernel_size=3, stride=1, padding=1),
        ),]
    def forward(self, x):
        output = self.convs[0](x)
        output = self.convs[1](x)
        return output

net = Network()
net.cuda()
```

.cuda() can not put parameters of self.convs'  layers.

Should I use self.register_parameter API? Or dose it have another easy way?
Thanks!

**Comment by AlexHex7** [comment]
Oh! Now I know I can use add_moudule to solve it.  Dose it have another easy way, if no I will close this issue.

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).

**Comment by AlexHex7** [comment]
Sorry, I can not get into the forums for a long time.

**Comment by apaszke** [comment]
What do you mean? You should be able to register any time

**Comment by AlexHex7** [comment]
It is not the forum's problem. I think maybe it has something to do with my country's policy... And a couple months ago, I can get into the forums...

When I try to get into the forum. It says that **This site can’t be reached discuss.pytorch.org took too long to respond**. Anyway, thanks and I will find some way to solve it.

**Comment by soumith** [comment]
@AlexHex7 which country are you from?

**Comment by AlexHex7** [comment]
China.

**Comment by AlexHex7** [comment]
@soumith China.

**Comment by apaszke** [comment]
@AlexHex7 it should work once you replace a regular Python list with `nn.ModuleList` for `self.convs`
