### ISSUE TITLE
Please stop the codecov bot from posting comments

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#44187]
Recently the `codecov` bot has started posting comments on PRs like:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/98330/92220575-801e4e00-ee9c-11ea-9fdd-a0b7301d1b3a.png">

This is very spammy and provides zero extra information, it's already one click away in the CI integration:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/98330/92220671-9b895900-ee9c-11ea-861d-c4fa3b1e105d.png">

The bot is very persistant, I dealt with this for NumPy a while back and the only robust solution was to ban the bot at the org level (should be at https://github.com/organizations/pytorch/settings/user_blocks).

EDIT: in addition, the comments are often filled with completely incorrect data, see e.g. https://github.com/pytorch/pytorch/pull/44868#issuecomment-703924115 (multiple files reported on were not touched).

**Comment by malfet** [comment]
Codecov has been disabled, closing
