### ISSUE TITLE
Remove torch.max/min warning

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#44195]
## 📚 Documentation

https://github.com/pytorch/pytorch/blob/f8f35fddd4b2bd788953d6d6ccfadf690b73a3e8/torch/_torch_docs.py#L4273-L4286

The following warning can be removed given that https://github.com/pytorch/pytorch/pull/42004 is in.

cc: @mruberry 

cc @jlin27 @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
That's true, we should also test that #42004 validates the behavior for min and max as well as argmin and argmax by ensuring consistency across them. We would definitely accept a PR fixing this.

**Comment by kshitij12345** [comment]
We do verify that behaviour in #42004.

Attaching screen-shot as the github doesn't render the file post 11k lines.
![image](https://user-images.githubusercontent.com/19503980/92435070-15805180-f1bf-11ea-924e-e7199a187262.png)
