### ISSUE TITLE
torch.linspace() issue with the 4095th element

### ISSUE THREAD

**Issue by sawsc** [pytorch/pytorch#4419]
There seems to be an issue with the 4095th element of a torch.linspace():

```
import torch

def test():
    length=4100
    step=2
    v=torch.linspace(0,step*(length-1),length)
    print(v[length-10:length])

if __name__ == '__main__':
    test()
```

Output:
```
 8180.0000
 8182.0000
 8184.0000
 8186.0000
 8188.0000
 8189.9995
 8192.0000
 8194.0000
 8196.0000
 8198.0000
[torch.FloatTensor of size 10]
```

**Comment by sighingnow** [comment]
Swap the order of the `*` and `/` operator, try

```cpp
std::cout << a + (b-a)/(float (n-1)) * i << std::endl;
```

Then we could get the right answer. The result of `i * (b-a)` exceeds the precision of `float` type.

Indeed, in pytorch the `linspace` was implemented as @Ktakuya332C comment:

https://github.com/pytorch/pytorch/blob/43ab91118226b330be6d2274a154b98da233d879/aten/src/TH/generic/THTensorMath.c#L3385-L3388

**Comment by vishwakftw** [comment]
I think this can be closed now.
