### ISSUE TITLE
Upsample with a trilinear interpolation works at least 10x slower using Mixed Precision than with FP32.

### ISSUE THREAD

**Issue by mmarcinkiewicz** [pytorch/pytorch#44206]
## 🐛 Bug

Upsample with a trilinear interpolation works at least 10x slower using Mixed Precision than with FP32.

## To Reproduce

1. Run python debug.py --input_shape 8 4 4 4 --batch_size 4 --iterations 100
2. Run python debug.py --input_shape 8 4 4 4 --batch_size 4 --iterations 100 --amp
3. Compare results

## Expected behavior

Upsample with a trilinear interpolation works at least as fast using Mixed Precision as FP32

## Environment

I tried it in nvidia containers back to 20.01 so it seems it's pytorch version agnostic.

## Additional context
It seems that the main culprit is **backprop**. Fprop is actually faster in Mixed Precision.
kernel breakdown:
FP32:
![image](https://user-images.githubusercontent.com/43240942/92271388-ff853f00-eee7-11ea-8dbd-1caa57d182a2.png)

FP16:
![image](https://user-images.githubusercontent.com/43240942/92271411-09a73d80-eee8-11ea-92c3-aece946ce6be.png)

code:

```python
import argparse
from time import time
import torch
import torch.nn as nn
from torch.cuda.amp import GradScaler
from torch.cuda.amp import autocast


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv3d(in_channels=8, out_channels=1024, kernel_size=(3, 3, 3), bias=False, padding=(1, 1, 1))
        self.upsample = nn.Upsample(scale_factor=2, mode="trilinear", align_corners=True)
    def forward(self, x):
        x = self.conv(x)
        x = self.upsample(x)
        return x


def main():
    flags = parse_arguments()
    torch.backends.cudnn.benchmark = True
    nvtx_enabled = False
    if flags.profile:
        import torch.cuda.profiler as profiler
        import pyprof
        pyprof.init(enable_function_stack=True)
        nvtx_enabled = True
        print("Profiling is enabled")

    model = Model()
    device = torch.device("cuda:0")
    model.to(device)
    optimizer = torch.optim.SGD(model.parameters(), 1e-8)
    scaler = GradScaler()

    data = torch.rand(size=(flags.batch_size, *flags.input_shape)).to(device)
    with torch.autograd.profiler.emit_nvtx(enabled=nvtx_enabled):
        model.train()
        iteration = 0
        start_marker = time()
        for i in range(flags.iterations):
            iteration += 1
            if flags.profile and iteration == 10:
                profiler.start()
            optimizer.zero_grad()

            with autocast(enabled=flags.amp):
                outputs = model(data)
                loss = torch.sum(outputs)

            if flags.amp:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()
        if flags.profile:
            profiler.stop()
        elapsed = time() - start_marker
        print("Finished in", round(elapsed, 2),
              "s. One iteration took on average", round(elapsed/flags.iterations), "s.")


def parse_arguments():
    PARSER = argparse.ArgumentParser(description="UNet-3D")
    PARSER.add_argument('--amp', dest='amp', action='store_true', default=False)
    PARSER.add_argument('--batch_size', dest='batch_size', type=int, default=1)
    PARSER.add_argument('--input_shape', nargs='+', type=int, default=[32, 64, 64, 64])
    PARSER.add_argument('--profile', dest='profile', action='store_true', default=False)
    PARSER.add_argument('--iterations', dest='iterations', type=int, default=100)
    return PARSER.parse_args()


if __name__ == '__main__':
    main()
```

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
cc @ptrblck , @xwang233. The issue here is that only upsampleBilinear was updated to use fast half atomics, the same should be done for trilinear.

**Comment by mcarilli** [comment]
I'll take a look as prep for https://github.com/pytorch/pytorch/issues/42218.  If I can swap fast atomics into trilinear backward, I can then cover interpolate/grid_sample as ordinary promotelist ops (instead of doing some hacky thing where the autocast wrapper must cast to fp32 if the mode is trilinear).

**Comment by mmarcinkiewicz** [comment]
@mcarilli is there any progress in this issue? I see some commits got referenced but the issue is still present, right?

**Comment by mcarilli** [comment]
Issue is still present, https://github.com/pytorch/pytorch/pull/44642 was necessary preparation for the fix.  Prior to 1.7 cut I was busy shepherding multi tensor apply commits.  Right now I have some other high priority commitments, please ping internally for timeline.

**Comment by ptrblck** [comment]
@xwang233 would you have bandwidth to take over this fix?

**Comment by mcarilli** [comment]
Jie's corresponding diffs for bilinear:  https://github.com/pytorch/pytorch/pull/21879

**Comment by CoinCheung** [comment]
Hi, has the problem of 'training models with interpolate op in fp16 mode is very slower' being solved ?

**Comment by xwang233** [comment]
Yes it's resolved and you can verify it in the nightly build.

**Comment by CoinCheung** [comment]
Thanks, now that pytorch1.7.1 is released, could I install pytorch 1.7.1 directly instead of the nightly built version ?

**Comment by xwang233** [comment]
I think this PR was not cherry-picked into 1.7.1 release. So 1.7.1 release may not have the performance fix for it.

**Comment by CoinCheung** [comment]
Got it, thanks a lot !!!

**Comment by placeforyiming** [comment]
Could anybody here tell me where should I install the nightly built version? Link or docker image?

**Comment by ngimel** [comment]
Follow instructions on pytorch.org, select Preview(nightly) in selector.

**Comment by placeforyiming** [comment]
> Follow instructions on pytorch.org, select Preview(nightly) in selector.

Thanks!

**Comment by CoinCheung** [comment]
Hi,

Now that pytorch 1.8 is release, this problem seems not handled in the new version. Is this fix still not picked this time ?

**Comment by xwang233** [comment]
@CoinCheung The first PR fixed the problem in the original post, but introduced regressions on some other shapes. I posted a second PR to address this problem, and it should be in the 1.8 release already.

Can you post the tensor shape and dtype you are seeing slow performance in 1.7 and 1.8? A short script would be much better!

**Comment by CoinCheung** [comment]
Hi,
 Please neglect this !! It is my fault, I got some error with my logging message. Sorry for being so careless.
