### ISSUE TITLE
Generalized Helper for Parsing Environment Variables from Process Group

### ISSUE THREAD

**Issue by osalpekar** [pytorch/pytorch#44205]
## 🚀 Feature

We are introducing a new flag to guard the behavior of NCCL Async Error Handling. Users can set the environment variable NCCL_ASYNC_ERROR_HANDLING to control this feature (set to 1 if NCCL should crash instead of hanging due to timeouts/errors). A generalized helper function to parse environment variables and set the appropriate flags in `ProcessGroupNCCL` would help make the code more modular, since we already have other flags like NCCL_BLOCKING_WAIT.

Something like the following could work (for binary env vars):

```
void parseBinaryEnvVar(std::string varName, bool& flag) {
   char* varString = getenv(varName);
     if (varString != nullptr) {
       auto val = std::stoi(varString);
       if (val == 1) {
         flag = true;
       } else if (val != 0) {
         throw std::runtime_error(
             "Invalid value for environment variable: " +
             std::string(varName));
       }
    }
}
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by Rubix982** [comment]
Hi, @osalpekar . This is very interesting. I would to like to follow up with you starting from today for the next few couple of days. 

I went through the pull requests that you made, and out of the checks that failed, `Facebook Internal - Builds & Tests Action required after 38m — 323 passed, 1 advice, 221 warning` is one of them that is common to all PRs. Do you have some idea about this? I think, as far as I can see, only FB employees can visit the actual report.

Is there something I should know before working on this with you? Much thanks!

**Comment by osalpekar** [comment]
Hi @Rubix982, I can let you know if any of the FB internal tests are failing and how can we address those. Feel free to put up a PR and we can coordinate from there!

**Comment by Rubix982** [comment]
Fantastic!
Please bear with me and give me sometime. I have my University going on, I might get back to you on the weekend in the worst case. 
Thanks for your time.

**Comment by osalpekar** [comment]
Closed by https://github.com/pytorch/pytorch/pull/46045
