### ISSUE TITLE
Exporting the Sigmoid operator svd to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by yingsiqin** [pytorch/pytorch#44228]
## Issue description

I tried to convert a PyTorch model that has a sigmoid operation to ONNX but it was not supported.
I'm using PyTorch version 1.6.0. Please help!

## Code to reproduce the bug

In the model file model.py:

import torch.nn as nn
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        ...
    def forward(x):
        x = nn.Sigmoid(x)
        return x

In the python file to convert the model to onnx:

from model import Model
import numpy as np
import torch
...
model = Model()
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

if __name__ == '__main__':
	sample_batch_size = 32
	height, width = 128, 128
	x = np.random.randn(sample_batch_size, 1, height, width).astype(np.float32)
	x = torch.from_numpy(x)
	x = x.to(device)
	input_names = ['x']
	output_names = ['output']
	model.eval()
	torch.onnx.export(model, 
					  x, 
					  "./model.onnx", 
					  input_names=input_names, 
					  output_names=output_names, 
					  export_params=True)

Error message I got:

Traceback (most recent call last):
  File "convert_to_onnx.py", line 116, in <module>
    export_params=True)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 787, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/utils.py", line 745, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/opt/anaconda3/envs/snap/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator svd to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.6 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: version 3.17.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.6.post0
[pip] numpy==1.17.0
[pip] torch==1.6.0
[pip] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.1            py37h959d312_0  
[conda] msgpack-numpy             0.4.6.post0              pypi_0    pypi
[conda] numpy                     1.17.0                   pypi_0    pypi
[conda] pytorch                   1.6.0                   py3.7_0    pytorch
[conda] torch                     1.5.0                    pypi_0    pypi
[conda] torchvision               0.6.0                    pypi_0    pypi

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source): NA
- OS: macOD Catalina 10.15.6
- PyTorch version: 1.6.0
- Python version: 3.7.6
- CUDA/cuDNN version: no CUDA, running on CPU
- GPU models and configuration: NA
- GCC version (if compiling from source): NA
- CMake version: NA
- Versions of any other relevant libraries: NA

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@yingsiq - `nn.Sigmoid` should be supported in ONNX export. See this line here:
https://github.com/pytorch/pytorch/blob/2a87742ffa5c4511e5cc071087b0407c54d56590/torch/onnx/symbolic_opset9.py#L255

Please provide the exact issue you are seeing and the repro.

**Comment by jiafatom** [comment]
`sigmoid` is supported, I just tried pytorch master branch and it works.
In your script, it is written `x = nn.Sigmoid(x)`, I rewrite it as `x = nn.Sigmoid()(x)`. 
Here is my script based on your script, and it works well.
```python
    import torch.nn as nn
    class Model(nn.Module):
        def forward(self, x):
            x = nn.Sigmoid()(x)
            return x

    model = Model()
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    sample_batch_size = 32
    height, width = 128, 128
    x = np.random.randn(sample_batch_size, 1, height, width).astype(np.float32)
    x = torch.from_numpy(x)
    x = x.to(device)
    input_names = ['x']
    output_names = ['output']
    model.eval()
    torch.onnx.export(model, x, "./model.onnx", input_names=input_names, output_names=output_names, export_params=True)
```
This script works well in pytorch master branch.

**Comment by garymm** [comment]
Seems this is working as intended. @yingsiqin please open another issue if you're still having issues.
