### ISSUE TITLE
Loading a trained torch script model saved from python notebook on google colab on local machine 

### ISSUE THREAD

**Issue by jasmeetkaur642** [pytorch/pytorch#44244]
Trying to load a torch script model saved from running the script on google colab in C++ on local machine gives me the following error:
     `terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: /home/jasmeet/sbpl/build/model_a.pt
Exception raised from FileAdapter at /pytorch/caffe2/serialize/file_adapter.cc:11 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe480f84c92 in /home/jasmeet/libtorch/lib/libc10.so)
frame #1: caffe2::serialize::FileAdapter::FileAdapter(std::string const&) + 0x24e (0x7fe483a6152e in /home/jasmeet/libtorch/lib/libtorch_cpu.so)
frame #2: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x30 (0x7fe484cb47d0 in /home/jasmeet/libtorch/lib/libtorch_cpu.so)
frame #3: SBPL2DGridSearch::learner() + 0x83 (0x7fe49228fb23 in /home/jasmeet/sbpl/build/libsbpl.so)
frame #4: main + 0x48 (0x404548 in ./test_sbpl)
frame #5: __libc_start_main + 0xf0 (0x7fe4811de840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: _start + 0x29 (0x4045e9 in ./test_sbpl)`

Tried running with full path to the saved model but doesn't help. 
Any suggestions as to how to resolve this ?

### Environment 
_Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.14.0
Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.1           py38hbc911f0_0  
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] pytorch                   1.6.0               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.7.0                  py38_cpu  [cpuonly]  pytorch_

**Comment by izdeby** [comment]
Please, use our [forums](https://discuss.pytorch.org/) for discussion and questions.
