### ISSUE TITLE
新版本能不能支持下 tesla k40m的显卡

### ISSUE THREAD

**Issue by zkbutt** [pytorch/pytorch#44253]
新版本能不能支持下 tesla k40m的显卡

**Comment by SsnL** [comment]
compute capability 3.5 is not supported in the binaries anymore. you may still build from source, and obtain a version that works for your card.

**Comment by zkbutt** [comment]
@SsnL  请问下如何构建 有相关的教程吗?

**Comment by Coderx7** [comment]
@zkbutt Check this : https://github.com/pytorch/pytorch/issues/30532#issuecomment-669714101 
somebody built 1.6 with compute capability 3.5. there is also notes on how to get it compiled without much of a hassle!

**Comment by SsnL** [comment]
Closing as duplicate of https://github.com/pytorch/pytorch/issues/30532. In addition, this github repo normally only support issues in English, for the purpose of searching and cross referencing by general users.
