### ISSUE TITLE
Was gesv differentiable? and if so, why torch.solve is not?

### ISSUE THREAD

**Issue by dvirginz** [pytorch/pytorch#44260]
In a project I'm currently working on I need to solve a set of linear equations as part of the pipeline. Although TensorFlow offers it from 2017, I cannot see any workaround in PyTorch.

Reading 
https://github.com/weiyangfb/pytorch/commit/207b5d6b7588b1873ae354f4712c2160965ddc11
https://discuss.pytorch.org/t/differentiable-linear-solver/12852

It seems that `torch.solve` replaced `torch.gesv`, but While gesv was differentiable, torch.solve is not.
Is there an explanation for that? can I somehow use gesv in PyTorch 1.6? (By somehow installing from binaries and merge the two versions?)

Thanks.

**Comment by izdeby** [comment]
Please, use our [forums](https://discuss.pytorch.org/) for discussion.
