### ISSUE TITLE
Using DataLoader with num_workers>0 causes re-run of script 

### ISSUE THREAD

**Issue by alonhzn** [pytorch/pytorch#44267]
## 🐛 Bug

When iterating on a DataLoader object with num_workers>0 the python script itself re-runs causing a crash.

## To Reproduce

```
from torch.utils.data import DataLoader
from torch.utils.data.sampler import Sampler
from torch.utils.data import Dataset
import numpy as np

print('running this script')

class Basic_Sampler(Sampler):
    def __init__(self, samples_list):
        self.sample_list = samples_list
        self.epoch_size = len(samples_list)
    def __iter__(self):
        return iter(self.sample_list)
    def __len__(self):
        return self.epoch_size

class fake_dataset(Dataset):
    def __init__(self):
            pass
    def __getitem__(self, item):
        return np.zeros(5)

sampler = Basic_Sampler([1,2,3])
dl = DataLoader(fake_dataset(), batch_size=2, shuffle=False, sampler=sampler, num_workers=1)

iter(dl).next()
```

## Expected behavior

Expected: a print to terminal "running this script"
instead, the entire script re-runs so the print happens twice and then the script crashes. 

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchcontrib==0.0.2
[pip3] torchvision==0.7.0
[conda] Could not collect
```
## Additional context

<!-- Add any other context about the problem here. -->

**Comment by SsnL** [comment]
This is expected. Windows uses `spawn` by default (because of Python), which literally reruns the script, which is why you should wrap actual executing code in `if __name__ == '__main__':`. https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection
