### ISSUE TITLE
"exp_cuda" not implemented for 'ComplexDouble'

### ISSUE THREAD

**Issue by chrismaliszewski** [pytorch/pytorch#44272]
## 🐛 Bug
There is a bug during calculating exp on CUDA. 

## To Reproduce
```python
import torch
torch.set_default_tensor_type(torch.cuda.DoubleTensor)
tt = torch.Tensor([1])
torch.exp(1j*tt)
```

## Expected behaviour
Calculate exp with a complex part

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              h74a9793_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37hb782905_0  
[conda] mkl_fft                   1.1.0            py37h45dec08_0  
[conda] mkl_random                1.1.1            py37h47e9c7a_0  
[conda] numpy                     1.19.1           py37h5510c5b_0  
[conda] numpy-base                1.19.1           py37ha3acd2a_0  
[conda] numpydoc                  1.1.0                      py_0  
[conda] pytorch                   1.6.0           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.7.0                py37_cu102    pytorch

**The question:** is moving a tensor to CPU and calculating exp the only way to overcome the problem at the moment or can you think or something else?

cc @ezyang @anjali411 @dylanbespalko

**Comment by kshitij12345** [comment]
It is fixed. Works on latest master.
```python
>>> import torch
>>> torch.set_default_tensor_type(torch.cuda.DoubleTensor)
>>> tt = torch.Tensor([1])
>>> torch.exp(1j*tt)
tensor([0.5403+0.8415j])
```

**Comment by chrismaliszewski** [comment]
I'll need to wait for a working build for Windows then. If I'm correct the current one is failing and I shouldn't download it, correct?

**Comment by gloryVine** [comment]
I get a similar error: 
RuntimeError: "exp_cuda" not implemented for 'Byte'
when trying to use torch.binary_cross_entropy_with_logits()

I also can reproduce the error from the above posts. I have the latest PyTorch.

**Comment by rjkilpatrick** [comment]
Works on nightly
``` python3
>>> import torch
>>> print(torch.__version__)
1.8.0.dev20201026

>>> tt = torch.ones(1, dtype=torch.double).cuda()
>>> torch.exp(1j * tt)
tensor([0.5403+0.8415j], device='cuda:0', dtype=torch.complex128)
```

Steps to reproduce:
1. install cuda v10.2
1. `pip install numpy`
1. `pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html`

Recommend issue be closed.
