### ISSUE TITLE
 Enable XNNPACK on Windows Libtorch binaries

### ISSUE THREAD

**Issue by stakemura** [pytorch/pytorch#44283]
## 🚀 Feature
Enable XNNPACK on Windows Libtorch binaries

## Motivation
I've confirmed XNNPACK is supported on macOS Libtorch binaries.
However, XNNPACK is not supported on Windows Libtorch binaries including nightly build.
It seems that XNNPack is disabled on build as the `TorchConfig.cmake` in [ibtorch-win-shared-with-deps-latest.zip](https://pytorch.org/get-started/locally/) shows.

```
  if(OFF)
    find_library(XNNPACK_LIBRARY XNNPACK PATHS "${TORCH_INSTALL_PREFIX}/lib")
    list(APPEND TORCH_LIBRARIES ${XNNPACK_LIBRARY})
  endif()
```

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Although XNNPACK supports Windows, it requires clang. However, we don't have clang builds on Windows. Maybe we should provide one for LibTorch. What do you think? cc @ezyang @malfet

**Comment by ezyang** [comment]
Didn't we have some discussion about using clang-cl for Windows in the long term? I don't remember what the result of this was. Getting to stop worrying about the MSVC frontend and all of its bugs would be a win, but it sounds like a bit of work.

**Comment by mszhanyi** [comment]
@maxluk @GuoxiaWang , What's your opinion whether to take it as a new feature in the next stage?

**Comment by Maratyszcza** [comment]
FYI, XNNPACK shouldn't require Clang on Windows, MSVC is supported. If you find XNNPACK doesn't build with MSVC, please file a bug.

**Comment by peterjc123** [comment]
@Maratyszcza Last time when I compile QNNPACK, I remembered that it relies on PSIMD but PSIMD doesn't provide implementations for MSVC. I don't know whether it is the same story with XNNPACK.

**Comment by peterjc123** [comment]
Anyway, let's give it a shot first.

**Comment by peterjc123** [comment]
Well, it is complaining that MSVC doesn't have `stdatomics.h` when compiling pthreadpool.

**Comment by Maratyszcza** [comment]
XNNPACK was ported to not depend on psimd for most functionality

**Comment by peterjc123** [comment]
Looks like the Windows builds passed when I patched pthreadpool and updated XNNPACK to a recent version. But it leads to failure of some Linux jobs.

**Comment by peterjc123** [comment]
Nobody knows how to update XNNPACK in the confu-deps directory. So, I cannot go any further in #45830. But anyway, it works on Windows.
