### ISSUE TITLE
Current behavior of `as_tuple` argument is inconsistent in `nonzero`

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#44284]
After `nonzero` started warning that `as_tuple` is a required argument (1.6) a few unfortunate things has happened:
1) the examples in docs started issuing a warning #43425
2) there's no way to pass `out` and `as_tuple` arguments together
```
print(torch.nonzero(a, as_tuple=False)) #ok
print(torch.nonzero(a, out=out)) #warns
print(torch.nonzero(a, as_tuple=False, out=out)) #errors out with `TypeError: nonzero() received an invalid combination of arguments - got unrecognized keyword arguments: out`
```
The rationale behind making `as_tuple` argument required is going through deprecation cycle to change the default value of `as_tuple` so that `torch.nonzero` matches `numpy.nonzero` without any additional args. However, even if implemented properly without problems noted above, this goal is misguided and forces users to modify their codes to avoid warnings for no good reason. 
Torch default behavior for `nonzero` should not match numpy. Numpy behavior can already be achieved by either using `as_tuple=True` or calling `unbind(1)` on results of `torch.nonzero()` call, that is a very light burden for someone who wants it. But to avoid it, we are making everyone who doesn't care jump through deprecation hoops. 
Making numpy behavior default is bad, because numpy returns a tuple of tensors, whereas many users want single tensor return. Going from a single tensor to a tuple is a matter of a cheap `.unbind` call, going from a tuple to a single tensor is memory copy. Default behavior should always pick single tensor. 
My proposal is to go back to making `as_tuple` optional argument and not strive to make `nonzero` match numpy behavior.

cc @albanD @mruberry @rgommers, @alband, @stas00

**Comment by stas00** [comment]
I totally agree, @ngimel!

there was another discussion of this subject matter that led nowhere here: https://github.com/pytorch/pytorch/pull/43434

**Comment by mruberry** [comment]
We should definitely fix this for 1.7, either by no longer trying to warn if a user doesn't explicitly set the `as_tuple` argument or ensuring that the warning is thrown only when it should be and that the function signature works as expected.

**Comment by ppwwyyxx** [comment]
This is not yet fixed for `tensor.nonzero()` due to https://github.com/pytorch/pytorch/pull/45413#issuecomment-703947414. Could you reopen or open a new issue?

**Comment by mruberry** [comment]
> This is not yet fixed for `tensor.nonzero()` due to [#45413 (comment)](https://github.com/pytorch/pytorch/pull/45413#issuecomment-703947414). Could you reopen or open a new issue?

Sure.
