### ISSUE TITLE
pytorch 1.3.1 not support CUDA 10.1.105 ?

### ISSUE THREAD

**Issue by unlimition** [pytorch/pytorch#44303]
`
    python -m torch.utils.collect_env
    Collecting environment information...
    PyTorch version: 1.3.1
    Is debug build: No
    CUDA used to build PyTorch: Could not collect

    OS: Ubuntu 18.04.4 LTS
    GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    CMake version: version 3.10.2

    Python version: 3.7
    Is CUDA available: No
    CUDA runtime version: 10.1.105
    GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
    Nvidia driver version: 430.64
    cuDNN version: Probably one of the following:
        /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
        /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5

    Versions of relevant libraries:
        [pip3] numpy==1.19.1
        [pip3] torch==1.3.1
        [pip3] torchvision==0.4.2
`

But when I run

`
    >>> import torch
    >>> print(torch.cuda.is_available())
    False
`
I installed previously GPU driver, CUDA, cudnn, Anaconda3-5.2.0.
Due to this reason , I reinstall GPU driver ,cudnn even anaconda 
But it still can't be True
Why?
can reinstalling CUDA fix it?

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.
