### ISSUE TITLE
Bug in pytorch\aten\src\ATen/native/Resize.h

### ISSUE THREAD

**Issue by ABHISHEK-G0YAL** [pytorch/pytorch#44306]
## 🐛 Bug

RuntimeError: size.size() == stride.size() INTERNAL ASSERT FAILED at C:\w\b\windows\pytorch\aten\src\ATen/native/Resize.h:96, please report a bug to PyTorch.

## To Reproduce

1. Run the code given below to reproduce the error.

```python
import torch
import torch.nn as nn
from torch.autograd import Variable

src_vocab = 5

def Loss(x, tgt):
    criterion = nn.KLDivLoss(reduction='batchmean')
    padding_idx = 0
    confidence = 0.9
    true_dist = None

    true_dist = torch.zeros_like(x) + ((1.0 - confidence) / (src_vocab - 2))
    true_dist = x.data.clone()
    true_dist.fill_((1.0 - confidence) / (src_vocab - 2))
    true_dist.scatter_(1, tgt.data.unsqueeze(1), confidence)
    true_dist[:, padding_idx] = 0
    mask = torch.nonzero(tgt.data == padding_idx,as_tuple=False)
    if mask.dim() > 0:
        true_dist.index_fill_(0, mask.squeeze(), 0.0)
    true_dist = true_dist
    return criterion(x, Variable(true_dist, requires_grad=False))

print(Loss(torch.tensor([
                [0.1, 0.1, 0.1, 0.8, 0.1],
                [0.1, 0.1, 0.1, 0.8, 0.1]
            ]), torch.tensor([[3],[3]])))
```

## Expected behavior

Internal pytorch assert shouldn't fail.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Microsoft Windows 10 Home Single Language
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.5.0
[pip3] torchvision==0.6.0
[conda] Could not collect

**Comment by zou3519** [comment]
This was fixed in PyTorch 1.6. The error message is now "RuntimeError: Index tensor must have the same number of dimensions as self tensor"
