### ISSUE TITLE
method `cuda` for PackedSequence

### ISSUE THREAD

**Issue by jusjusjus** [pytorch/pytorch#4431]
My use-case necessitates sending a `PackedSequence` to the GPU.  What I currently do is `packed_gpu = PackedSequence(packed.data.cuda(), packed.batch_sizes)`.  I think this could be included in a convenience method as so:  `packed_gpu = packed.cuda()`.

See pull request: #4430

**Comment by apaszke** [comment]
That seems like a good idea. You've already sent a PR so I'll close the issue
