### ISSUE TITLE
Unexpected behaviour when multiplying a np.float64 before Variable

### ISSUE THREAD

**Issue by lxuechen** [pytorch/pytorch#4433]
It seems that when I multiply a floating number of type np.float64 before a torch.autograd.Variable I get a nested np.ndarray with the "core" inside it being the Variable. However, when I reverse the order of multiplication, the problem is gone. Here's one example

```python
import numpy as np 
import torch
from torch.autograd import Variable

s = np.float64(0.1)
a = Variable(torch.FloatTensor([2.3]))

print (s*a)
print (a*s)
```

I get the follow result when running with python3.5.2 and torch-0.3.0.post4
```
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Variable containing:
 0.2300
[torch.FloatTensor of size 1]
]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
Variable containing:
 0.2300
[torch.FloatTensor of size 1]
```
Is this expected?

**Comment by apaszke** [comment]
It's a known problem that will be fixed once we add proper scalar support (it's in progress).
