### ISSUE TITLE
[Feature Request] Implement Pareto Distribution

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#4434]
I could issue a PR if you feel this is worth adding to the list of distributions.

**Comment by apaszke** [comment]
I'll leave this one up to @fritzo

**Comment by fritzo** [comment]
Hi @vishwakftw, a bunch of us working on distributions are collaborating on [this task board](https://github.com/probtorch/pytorch/projects/1), and I've added a [Pareto task](https://github.com/probtorch/pytorch/issues/62). If you'd like to implement this, feel free to check out our [Design Doc](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit?usp=sharing) and chat on the #distributions channel of PyTorch slack.
