### ISSUE TITLE
Need DataLoader automatically prefetch data in another process whenever `self._tasks_outstanding < a_user_defined_number`.

### ISSUE THREAD

**Issue by thuzhf** [pytorch/pytorch#44357]
## 🚀 Feature
DataLoader automatically prefetch data in another process whenever `self._tasks_outstanding < a_user_defined_number`.

## Motivation

When user get data from DataLoader, if the DataLoader's `self._tasks_outstanding` is `0`, the user will be waiting for the results, instead of getting data immediately.

**Comment by SsnL** [comment]
Could you clarify what you mean exactly? `_tasks_outstanding` is an implementation detail and is only positive when there is data to be fetched. When it is zero, there is no more data to be fetched.

**Comment by thuzhf** [comment]
@SsnL What I want is the dataloader's internal data_queue is always not empty (unless all data are already fetched), because thus we can ensure whenever the user fetch data from the dataloader, the user will not encounter conditions where the dataloader's internal data_queue is empty, and thus the user will block waiting for data_queue.get().

**Comment by SsnL** [comment]
It would wait only when the workers have not finished fetching the data. Changing `task_outstanding` won't affect it.

**Comment by thuzhf** [comment]
@SsnL Can we let the workers prefetch data whenever `data_queue`'s size is less then a user defined number? Just like here:

https://github.com/pytorch/pytorch/blob/bd8e38cd8888602e574244e88a76de36c2349460/torch/utils/data/dataloader.py#L855-L857

**Comment by SsnL** [comment]
It would only have effect when we receive out of order batches though. If everything is received in order, the current code does equivalent things. So I don't really know what benefit it would gain you in realistic use cases... Could you explain why the current prefetch mechanism (always fetching 2*num_workers batches ahead) isn't ideal, and how your proposal would solve things?

**Comment by thuzhf** [comment]
I am not sure whether I miss something in the code, but my current logic is as follows:
Here is the code flow for`next(data_loader)` when `num_workers > 0`:
https://github.com/pytorch/pytorch/blob/bd8e38cd8888602e574244e88a76de36c2349460/torch/utils/data/dataloader.py#L432-L435

Pay attention to line 1062-1065, line1068, line 1077, line 1085:
https://github.com/pytorch/pytorch/blob/bd8e38cd8888602e574244e88a76de36c2349460/torch/utils/data/dataloader.py#L1038-L1085

It seems if the next sample has already been generated, it will just return the data from the queue, and won't do a `_try_put_index()`. Thus the number of items in the queue will finally reach 0. And at this time, if the user try to call `next(data_loader)`, the user will block.

Whether is my understanding wrong?

**Comment by SsnL** [comment]
`_process_data` calls `_try_put_index`

**Comment by thuzhf** [comment]
Ah, I really missed something...thanks!
I thought it doesn't do such things because last night when I tried to print the size of the internal queue.qsize() while training, I often got some zeros. I will check it again. And do you have some suggestions on how to monitor some variables here to check whether the dataloader is the bottleneck?

**Comment by SsnL** [comment]
Getting from the data loader iterator will only block when the data is not yet fetched from the workers. Usually monitoring the time of each `next` would give you an idea.

**Comment by SsnL** [comment]
closing because the original issue is not valid anymore

**Comment by thuzhf** [comment]
@SsnL By the way, do you know why the default RandomSampler samples 32 data points once? How do you know 32 is more efficient than other numbers?

https://github.com/pytorch/pytorch/blob/6324ef4cedbaeea2799e69dab91c8e7cc6cc80f0/torch/utils/data/sampler.py#L120-L123

**Comment by SsnL** [comment]
GitHub is not for Q&A. You can ask in the forum / slack / or simply check the PR that did the change for context.

**Comment by thuzhf** [comment]
I see. I will take your advice.
