### ISSUE TITLE
DDP training with syncBatchNorm，how to catch and handle the exception in training processes?

### ISSUE THREAD

**Issue by hegc** [pytorch/pytorch#44353]
When training with the DDP and syncBatchNorm, one process runing on one GPU, When I catch the gpu OOM exception, the training is blocked. What should we do?
My code is following, when OOM exception occurs in one process, I just ignore this batch, the training phase continue.

```
for i, (inputs, targets) in enumerate(train_loader):
    try:
        # do forward and backprop
    except RuntimeError as e:
        if 'out of memory' in str(e):
            print('| WARNING: ran out of memory, skipping this batch.')
            if hasattr(torch.cuda, 'empty_cache'):
                torch.cuda.empty_cache()
            optimizer.zero_grad()
        else:
            raise e

```

when one process catch the exception, the others get blocked. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.

**Comment by mrshenli** [comment]
If you skip comm or redo comm after OOM, it will lead to collective communication desync, which leads to the hang. 

[torchelastic](https://pytorch.org/elastic) is built for this problem. It will destroy all DDP and ProcessGroup instances, and reconstruct them, and then resume from the previous checkpoint. 

cc @kiukchung for torchelastic questions
cc @agolynski for oncall

**Comment by hegc** [comment]
> If you skip comm or redo comm after OOM, it will lead to collective communication desync, which leads to the hang.
> 
> [torchelastic](https://pytorch.org/elastic) is built for this problem. It will destroy all DDP and ProcessGroup instances, and reconstruct them, and then resume from the previous checkpoint.
> 
> cc @kiukchung for torchelastic questions
> cc @agolynski for oncall

I just want to discard this batch on the OOM process, there is more easy method? Maybe not...
