### ISSUE TITLE
Link for fusing Alexnet model

### ISSUE THREAD

**Issue by iitbombombay** [pytorch/pytorch#44358]
Can anyone provide the useful link  that explains  fusing of Alexnet model,or Code which fuses the layers of Alexnet model

**Comment by mrshenli** [comment]
Hey @iitbombombay, could you please use [the forum](https://discuss.pytorch.org/) for question? Thanks. I am closing this issue. If this turns out to be a bug report or feature request, please feel free to open another issue.
