### ISSUE TITLE
Add ability to determine libtorch version from a c++ API or preprocessor macro.

### ISSUE THREAD

**Issue by bigcmos** [pytorch/pytorch#44365]
## 🚀 Feature
I want to be able to determine the version of libtorch in my c++ binary in cases where I don't have access to the python library.

Something like:
```
#define TORCH_VERSION_MAJOR=1
#define TORCH_VERSION_MINOR=6
#define TORCH_VERSION_PATCH=0
```

## Motivation

This is useful for 
- Turning off torch features depending on the version of torch we are running
- Debugging which version of torch is installed in production where different versions may be running.

## Pitch

1) I'm a developer trying to upgrade the API, but a backwards incompatible API change requires me to refactor code before upgrading.  I need to roll this out so I want to only enable the new features if I build my application for the new version of torch.
2) I'm a site reliability engineer and I am rolling out a the server deploy with a new version of libtorch.  There is a bug that is claimed to be fixed in the newer version of torch and I want to verify that the new version was deployed when I validate this issue is resolved.

## Alternatives

Currently I am pulling the version from the strings in libtorch_cpu.so, but this didn't get updated in v1.6.0.  This is an unreliable hack solution that I would like to remove.
```
strings libtorch_cpu.so | egrep -A1 pytorch_version
pytorch_version
1.5.0
```

pytorch has the version number baked into the pip install and in the torch.__version__.  For my purposes I don't have access to either of these as we are not using python in our production environment and the shared libraries are built separate from the ones in the pip wheel.

## Additional context

I recently upgraded to libtorch version 1.6.0 to resolve a segfault on destruction of `DeviceThreadHandlePool` which seemed related to: https://github.com/pytorch/pytorch/pull/36416.  After upgrading I am still seeing some segfaults on destruction, but was worried that I might not have deployed the new version of libtorch.   By looking at other strings in that library I believe I am at v1.6.0, but I wasted some time on the red herring of the 1.5.0 version in the strings of libtorch_cpu.so and would like to avoid that in the future.

cc @yf225 @glaringlee

**Comment by liao1995** [comment]
If you use CMake, may be you can try:
``` cmake
find_package(Torch)
message(STATUS "Find Torch VERSION: ${Torch_VERSION}")
add_definitions(-DTORCH_VERSION_MAJOR=${Torch_VERSION_MAJOR})
add_definitions(-DTORCH_VERSION_MINOR=${Torch_VERSION_MINOR})
add_definitions(-DTORCH_VERSION_PATCH=${Torch_VERSION_PATCH})
```
