### ISSUE TITLE
'torch.per_channel_symmetric — per tensor, symmetric' seems wrong edited.

### ISSUE THREAD

**Issue by huqinghao** [pytorch/pytorch#44379]
## 📚 Documentation
'torch.per_channel_symmetric — per tensor, symmetric'  supposed to be
'torch.per_channel_symmetric — per channel, symmetric' 
in docs/source/quantization-support.rst Line  320.

cc @jlin27 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by mrshenli** [comment]
Hey @huqinghao, thanks for spotting this. Would you like to submit a PR to fix it?

**Comment by vkuzo** [comment]
for triage
