### ISSUE TITLE
Pytorch+rocm 3.7.0: cmake cannot find hsa-runtime64

### ISSUE THREAD

**Issue by apalazzi** [pytorch/pytorch#44384]
## 🐛 Bug

Hi,

I'm trying to build Pytorch for rocm from sources following [this page](https://github.com/aieater/rocm_pytorch_informations) and also other sources; however it ends with an error:

```
***** Library versions from cmake find_package *****

CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhsa-runtime64.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "hsa-runtime64", but CMake did not find one.

  Could not find a package configuration file provided by "hsa-runtime64"
  with any of the following names:

    hsa-runtime64Config.cmake
    hsa-runtime64-config.cmake

  Add the installation prefix of "hsa-runtime64" to CMAKE_PREFIX_PATH or set
  "hsa-runtime64_DIR" to a directory containing one of the above files.  If
  "hsa-runtime64" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:124 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:170 (find_package_and_print_version)
  cmake/Dependencies.cmake:1154 (include)
  CMakeLists.txt:486 (include)
```

The file that cmake is looking for is under /opt/rocm-3.7.0/lib/cmake/hsa-runtime64/ .
I also tried setting the variable  however setting the environmental variable to CMAKE_MODULE_PATH=/opt/rocm-3.7.0/lib/cmake/hsa-runtime64 , but still no luck.

Any hint?

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[conda] Could not collect

cc @malfet @seemethere @walterddr @jeffdaily @sunway513

**Comment by apalazzi** [comment]
Hi,
After setting some of the environmental variables as described [here](https://gist.github.com/znsoftm/31c9bf60caa547559e80d858b6f19783) it finally got through the configuration process and is now compiling.

**Comment by mrshenli** [comment]
Hey @apalazzi, Thanks for updating. I am closing this issue for now. Please feel free to reopen if build error persists.

**Comment by acxz** [comment]
Arch Linux users are also facing this issue: https://github.com/rocm-arch/python-pytorch-rocm/issues/6

**Comment by MonkeySon** [comment]
Hi @apalazzi , I am currently in the same situation as you were, but I don't know how to continue.

Since the gist you mentioned is not available anymore, do you know what environment variables you had to set?
