### ISSUE TITLE
Implement CPU EmbeddingBag in C

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#4441]
to replace current slow Python implementation.

**Comment by colesbury** [comment]
Hold off on this please. I have a partial implementation

**Comment by elanmart** [comment]
Perhaps it would be cool to also resolve https://github.com/pytorch/pytorch/issues/4068 with this one?

**Comment by SsnL** [comment]
@elanmart Yeah, I've seen other requests for this. If changing the existing cuda code is not too hard, we can certainly do it.

**Comment by soumith** [comment]
fixed via #4856
