### ISSUE TITLE
doc: Bad rendering of `tensor` output?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [pytorch/pytorch#44426]
## 📚 Documentation

Example screenshot on my browser (Firefox 80.0.1, Ubuntu 18.04):
![image](https://user-images.githubusercontent.com/26719449/92656714-86a82d80-f2c1-11ea-86f2-304946746ac7.png)

See link:
https://pytorch.org/docs/stable/autograd.html#torch.autograd.functional.jacobian

Current commit on `master`: 3674264

cc @ezyang @SsnL @albanD @zou3519 @gqchen @jlin27

**Comment by ezyang** [comment]
Yes, this looks bad to me.
