### ISSUE TITLE
How to print optimized IR?

### ISSUE THREAD

**Issue by wangxiang2713** [pytorch/pytorch#44448]
I read Pytorch 1.6 code: torch/csrc/jit/runtime/graph_executor.cpp, and see:
```
Inline(*opt_graph);
GRAPH_DEBUG("After Inline, before LowerGradOf\n", *opt_graph);
LowerGradOf(*opt_graph);
GRAPH_DEBUG(
  "After LowerGradOf, before specializeAutogradZero\n", *opt_graph);
```

I want to print optimized IR, so i run: `export PYTORCH_JIT_LOG_LEVEL=">graph_executor"`, my pytorch code is:
```
import torch

def f(x, y):
  a = x + y
  b = x - y
  c = a * b
  d = c ** 3
  e = d.sum()
  return e

script_f = torch.jit.script(f)
x, h = torch.rand(3, 4), torch.rand(3, 4)
print(script_f(x, h))
```

However, i got nothing. If i use pytorch 1.4, i can get:
```
[DUMP graph_executor.cpp:550] Optimizing the following function:
[DUMP graph_executor.cpp:550] def source_dump(x: Tensor,
[DUMP graph_executor.cpp:550]     y: Tensor) -> Tensor:
[DUMP graph_executor.cpp:550]   a = torch.add(x, y, alpha=1)
[DUMP graph_executor.cpp:550]   b = torch.sub(x, y, alpha=1)
[DUMP graph_executor.cpp:550]   c = torch.mul(a, b)
[DUMP graph_executor.cpp:550]   d = torch.pow(c, 3)
[DUMP graph_executor.cpp:550]   return torch.sum(d, dtype=None)
```
but can't get GRAPH_DEBUG info.

I don't know the reason, i can get a lot of logs if i set `export PYTORCH_JIT_LOG_LEVEL=dead_code_elimination:guard_elimination` when i use pytorch 1.6, but got nothing with `export PYTORCH_JIT_LOG_LEVEL=">graph_executor"`

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
You can also print the optimized IR using the `graph` attribute of the scripted module:
```
script_f = torch.jit.script(f)
print(script_f.graph)
```

**Comment by Lilyjjo** [comment]
Does using `export PYTORCH_JIT_LOG_LEVEL=">profiling_graph_executor_impl"` work for you?

**Comment by wangxiang2713** [comment]
> Does using `export PYTORCH_JIT_LOG_LEVEL=">profiling_graph_executor_impl"` work for you?

Yes, it does. Buti want run graph_executor other than profiling_graph_executor, how can i do that?

**Comment by Lilyjjo** [comment]
If you add `torch._C._jit_set_profiling_executor(False)` to your file before scripting that should make use of the graph_executor.cpp. Let me know if that doesn't work for you

**Comment by suo** [comment]
Probably the simplest option (given the dynamic nature of the JIT optimizations) is to run the graph a bunch of times to warm up our profiler and stuff, and then call `torch.jit.last_executed_optimized_graph()` to see what the executor was just running.

**Comment by wangxiang2713** [comment]
> If you add `torch._C._jit_set_profiling_executor(False)` to your file before scripting that should make use of the graph_executor.cpp. Let me know if that doesn't work for you

Thank you very much, everything is ok now.
