### ISSUE TITLE
norm can't backpropagate with 0<p<1

### ISSUE THREAD

**Issue by NeoVand** [pytorch/pytorch#44452]
## 🐛 Bug

Hi I use tensor.norm somewhere in my code which works fine for all values of p (including fractional ones e.g. p=1.5) but runs into problems with p<1. With anomaly detection on, I get this error:

RuntimeError Traceback (most recent call last)
in
11 # ===================backward====================
12 optimizer.zero_grad()
—> 13 loss.backward()
14 optimizer.step()
15 # ===================log========================

c:\users\windows.conda\envs\normnet\lib\site-packages\torch\tensor.py in backward(self, gradient, retain_graph, create_graph)
183 products. Defaults to False.
184 “”"
–> 185 torch.autograd.backward(self, gradient, retain_graph, create_graph)
186
187 def register_hook(self, hook):

c:\users\windows.conda\envs\normnet\lib\site-packages\torch\autograd_init_.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
125 Variable._execution_engine.run_backward(
126 tensors, grad_tensors, retain_graph, create_graph,
–> 127 allow_unreachable=True) # allow_unreachable flag
128
129

RuntimeError: Function ‘NormBackward1’ returned nan values in its 0th output.

any idea how to fix this?

**Comment by colesbury** [comment]
You probably have a zero value in `tensor` (or some value very close to zero). The gradients for those values are NaN when 0<p<1.

See https://www.wolframalpha.com/input/?i=derivative+%28%7Cx%7C%5E0.5%2B%7Cy%7C%5E0.5%29%5E2 for the partial derivative and graph. Note that the partial derivative goes to +/-infinity as x approaches zero.

**Comment by colesbury** [comment]
One trick is to add a small value to each number to ensure that they are not zero. You optimize a different function, but one that's smoother and easier to optimize. i.e. instead of:

```python
x = torch.tensor([-0.5, 0, 0.5], requires_grad=True)
x.norm(p=0.5)  # 2.0
x.norm(p=0.5).backward()
x.grad # tensor([-2.0000,     nan,  2.0000])
```

```python
x = torch.tensor([-0.5, 0, 0.5], requires_grad=True)
(x.abs() + 1e-6).norm(p=0.5)  # 2.0028
(x.abs() + 1e-6).norm(p=0.5).backward()
x.grad # tensor([-2.0014,  0.0000,  2.0014])
```

**Comment by colesbury** [comment]
I'm closing this issue because I don't think it's a bug in PyTorch. Please re-open with information on the inputs to norm if that's not the case.
