### ISSUE TITLE
The Python API's circular padding is divergent from the C++ API's

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#44459]
#39273 updated Python's circular padding, correcting several errors in the previous implementation. PyTorch has two circular padding implementations, however, one in Python and the other in C++:

https://github.com/pytorch/pytorch/blob/7b547f086fbef74dd2e9c07f4392da3a2d3266b4/torch/nn/functional.py#L3831

https://github.com/pytorch/pytorch/blob/46447045ea450069ab9a9cbbf71e86110013fb0b/torch/csrc/api/include/torch/nn/functional/padding.h#L13

It seems like we'd prefer to only have one implementation, although the author of this PR expressed that he was not familiar with C++. 

cc @yf225 @glaringlee @albanD @mruberry

**Comment by glaringlee** [comment]
Checked a bit. The c++ version is added last year when developing the C++ APIs NN Modules. _pad_circular was a pure python layer function while C++ APIs NN Modules need this in c++ layer. We probably can dispatch this function from python to c++ layer, the input is compatible with the native_function.ymal schema to me.
