### ISSUE TITLE
Missing tests for most torch.*(out=...) tensor operators

### ISSUE THREAD

**Issue by antocuni** [pytorch/pytorch#44467]
## 🐛 Bug

Apparently, the `(out=...)` version of most tensor operators is not directly tested by `test_torch.py`.

For most operators, a test is semi-automatically generated from this list inside `test_torch.py`:

https://github.com/pytorch/pytorch/blob/356aa54694cc4f1c9599fdf8320a4759aa63a12f/test/test_torch.py#L19729-L19759

Note that there is a parameter called `test_out`, but it is used only for `addmm` and `addmmv`. For some operators, there is a manually written test (e.g. `test_sum_out`), but for most of them, the `out=` variant is completely untested.

## To Reproduce

I tried to [intentionally break `addmmb`](https://github.com/pytorch/pytorch/commit/accf2edd8d699021268297360e437f316ac7a6b0) in #44465 . Here are [the results](https://github.com/pytorch/pytorch/pull/44465#issuecomment-690160367) of the CI checks. As you can see, there are failures only in JIT and autograd tests, but no "direct" test for it.

## Expected behavior

I think we should add/enable the `out=` tests for all operators which support it.
Moreover, the current format of the list `tensor_op_tests` is confusing and error prone, since you have to manually count the items in the tuple to know what is the corresponding param, and you have to manually specify all of them if you want to add `test_out=True`, since it's the last. I suspect this is one of the reasons why it is not used more.
So, I propose to use a different syntax to specify them, e.g. the following:

```py
def t(op_str, # - op name (string)
      subtest_str, # - (sub)test name (string)
      tensor_ctor, # - tensor constructor, takes dtype and device and constructs the tensor to run the op on
      arg_ctor, # - arg constructor, takes dtype and device and constructs op arguments
      half_precision=1e-5, # - torch.half precision
      bfloat16_precision=1e-5, # - torch.bfloat16 precision
      float_precision=1e-5, # - precision to use for all other dtypes
      dtype_list=_types, # - a list of torch dtypes to test the op(s) with
      dtype_cpu_list=[], # - list of torch dtypes to test the op(s) on cpu
      make_inplace_variant=True, # if true the inplace version of the op (op_) is also tested
      decorators=None, # a list of decorators to apply to the test
      self_position=-1,# the position of self in the arg list, -1 means skip function check
      test_out=False, # whether to test the out= version of the operator
):
    return (op_str, subtest_str, tensor_ctor, arg_ctor, half_precision,
            bfloat16_precision, float_precision, dtype_list, dtype_cpu_list,
            make_inplace_variant, decorators, self_position, test_out)

tensor_op_tests = [
    t('add', '', _small_3d, lambda t, d: [_number(3.14, 3, t)], 1e-2),
    t('add', 'tensor', _small_3d, lambda t, d: [_small_3d(t, d)], 1e-2),
    t('sub', '', _small_3d, lambda t, d: [_number(3.14, 3, t)], 1e-2),
    ...
]
del t
```

I am willing to open a PR if there is interest in it

cc @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
Adding more tests for `out=` behavior is a great idea, and you're correct, @antocuni, that we're missing them.

The `tensor_op_tests` list has outgrown its purpose (much like `method_tests` in common_methods_invocations.py) and I'm leery of investing in it more. Instead we're investing in a new "OpInfo"-based approach that is similar to what you've proposed.  You can see the start of this new list here:

https://github.com/pytorch/pytorch/blob/cb90fef7705a5f396bf7096d4dfaea1ed1f58d5b/torch/testing/_internal/common_methods_invocations.py#L201

It doesn't contain many operators at the moment but I still think this is the best place to invest.

To that end, you could write a test in test_ops.py. These tests are intended to run on EVERY operator in OpInfo (which will, eventually, be all operators). You could, for example, create a test that went through an operator's sample inputs and then called each with an out= argument. If an operator doesn't support out= you could just add an annotation to OpInfo and skip the test. Other annotations might be whether op supports casting from its computation dtype to a different out dtype.

**Comment by mruberry** [comment]
I think https://github.com/pytorch/pytorch/pull/53259 address this issue. Let me know if you agree @antocuni. If it doesn't, let's maybe open a new issue that explains what else should be done.

**Comment by antocuni** [comment]
@mruberry I think the issue is solved, thank you
