### ISSUE TITLE
Hang when compiling static libs on windows

### ISSUE THREAD

**Issue by adampauls** [pytorch/pytorch#44470]
## 🐛 Bug

Currently, there is a hang mentioned [here](https://github.com/pytorch/pytorch/blob/54c05fa34e1fbbb5096746a8ae92e27a08116de4/torch/csrc/autograd/engine.cpp#L228) that can still happen if you build libtorch statically on windows, but then bundle it into a DLL. I think this can be solved by having compiler flag allowing us to link against the DLL runtime, even when compiling statically, though I am no expert here and could be missing something. In fact, there is already a build flag (`CAFFE2_USE_MSVC_STATIC_RUNTIME`) that does that. I made a [PR](https://github.com/pytorch/pytorch/pull/43532) that is not quite right because it doesn't convert the cmake flag into a compiler flag, but no one has responded on the PR. 

## To Reproduce

Run build_libtorch.py with BUILD_SHARED_LIBS=OFF, then link the resulting library into a DLL. A process that runs training will not terminate.

## Expected behavior

Process should terminate. 

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by colesbury** [comment]
@seemethere can you take a look at this or route it to the right person?

**Comment by maxluk** [comment]
+ @nbcsm

**Comment by nbcsm** [comment]
thanks for reporting, we will take a look.  @mszhanyi

**Comment by mszhanyi** [comment]
@adampauls , thank you raising and taking care of this issue. I'll assign the owner to you
