### ISSUE TITLE
Surprising behavior of `nn.Parameter` with  `np.float64` scalars

### ISSUE THREAD

**Issue by IssamLaradji** [pytorch/pytorch#4447]
`nn.Parameter` and `numpy.float64` don't seem to mix well, consider the following behavior,

```
ipdb> log_v = nn.Parameter(torch.FloatTensor(np.array([-2])))

ipdb> - 0.5 * np.log(2 * np.pi) - 0.5 * log_v 
array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Variable containing:
1.00000e-02 *
  8.1061
[torch.FloatTensor of size 1]
]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=object)
```

Is this an expected  behavior ?

Note that `np.log` returns a `np.float` type scalar

```
ipdb> type(- 0.5 * np.log(2 * np.pi))
<class 'numpy.float64'>
```

I would use `torch.log` instead of `np.log` but it seems that `torch` math operations don't work directly on scalars without first being  converted to a `FloatTensor` - which adds boiler code.

**Comment by apaszke** [comment]
Known issue. Will be fixed once we introduce scalars (in progress).

**Comment by apaszke** [comment]
Oh, as a workaround try multiplying by the scalar form the other side (yes, in Python multiplication isn't necessarily commutative)
