### ISSUE TITLE
Implement log det

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#4449]
I'll do this.

**Comment by nanand2** [comment]
Any update on this?

**Comment by nanand2** [comment]
For a single 2d matrix it's easy to define a custom function, but it would be nice to have a batched version  

class LogDet(torch.autograd.Function):
    def forward(self, input):
        self.save_for_backward(input)
        return torch.det(Variable(input, requires_grad=True)).data 

    def backward(self, grad_output):
        input, = self.saved_tensors
        grad_input = grad_output*torch.inverse(input.transpose(0,1))
        return  grad_input

**Comment by SsnL** [comment]
I'm doing other tasks at the moment. I will finish this before next release. Btw, I don't think your implementation does log det.

**Comment by nanand2** [comment]
Oh, I've forgotten the log in the forward pass... sorry!

**Comment by SsnL** [comment]
@soumith this one can be closed

**Comment by JurijsNazarovs** [comment]
Hello,

Is there an implementation of logged for batches? I see that inverse can handle batches, but seems like det and logged require just 2d shape.
