### ISSUE TITLE
BatchSampler & PEP 479

### ISSUE THREAD

**Issue by min-xu-ai** [pytorch/pytorch#44527]
## 🐛 Bug

By reading BatchSampler's code, it seems that when StopIteration is raised by the underlying sampler in https://github.com/pytorch/pytorch/blob/41f62b17e721d2f8854b7e684d96e70d58f2eaf0/torch/utils/data/sampler.py#L227 due to [PEP 479](https://www.python.org/dev/peps/pep-0479/), this gets turned into a RuntimeError exception.

Is this really intended? Shouldn't the sampler raise StopIteration not RuntimeError in that case?

## To Reproduce

see above. this is on code inspection.

## Expected behavior

raise StopIteration?

**Comment by mariosasko** [comment]
Hi,

not really sure if I understand your question. Using the `yield` keyword in `__iter__`  is a construct I see fairly often and it works perfectly fine if implemented correctly. To get RuntimeError, you have to explicitly raise StopIteration in `__iter__`. So the code seems fine.

Try this code to get an idea (it should raise RuntimeError):
```python
class A:
    def __iter__(self):
        for i in [1, 2, 3]:
            yield i  
            if i == 2:
                raise StopIteration
```

**Comment by min-xu-ai** [comment]
try making the list [1,2,3] into an iterator and try again. That iterator would raise StopIteration at the end and it would be converted to RuntimeError in this parent iterator according to the PEP.

**Comment by min-xu-ai** [comment]
Nevermind, you are right, it needs to be explicitly raised.
