### ISSUE TITLE
After adding the transforms.Resize(), Why the training of model gets slowly?

### ISSUE THREAD

**Issue by StevenAZy** [pytorch/pytorch#44539]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by VitalyFedyunin** [comment]
Hello! 

It is happening because Resize of the image takes CPU resources.

Next time It is better to ask such kind of questions at https://discuss.pytorch.org/. I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
