### ISSUE TITLE
Qestion) Perform unsqueeze(0) or reorder TENSORS in JAVA.pytorch

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/pytorch#44541]
## ❓ Questions and Help
Hi, I have python code
and converting to android

my python code is`unsqueeze(x,0)` where x is **pytorch.tensor** 
1) in JAVA, can I do it(`unsqueeze(x,0)`) how...?
e.g) when unsqueeze(x,0) is performed, shape of x will be [3,2,4] to [1,3,2,4]
Actually, I want to increase dimension of the tensor x by adding a new dimension of size=1 in the first of the tensors..

2) Also, I want to reorder the pytorch.tensor in JAVA
e.g) [3,2,4] to [2,4,3]
in python it is performed by `torch.from_numpy(x).permute(2, 0, 1)`
In JAVA, how to can I do it? (JAVA command is fine to me)

thank you.
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.

**Comment by SungmanHong** [comment]
Thanks, but I really need for help, cuz in pytorch communicty, there is no relpy..
