### ISSUE TITLE
Error: The ordinal 242 could not be located in the dynamic link library C:\Users\nrifa\anaconda3\envs\test\lib\site-packages\torch\lib\torch_cpu.dll

### ISSUE THREAD

**Issue by NahianAlindo** [pytorch/pytorch#44549]
I don't know why this is occurring. I was trying to run the HRNet model by leoxiaobin. I followed his git repo [here](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch).

I had already created a virtual environment using conda and used conda to install pytorch with cuda and installed the packages in the requirements.txt manually except instead of shapely==1.6.4, I installed the latest shapely package because it showed errors.

After installing the packages, I ran the command 
python tools/test.py  --cfg experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml TEST.MODEL_FILE models/pytorch/pose_mpii/pose_hrnet_w32_256x256.pth

and then I got the error message 

"The ordinal 242 could not be located in the dynamic link library C:\Users\nrifa\anaconda3\envs\test\lib\site-packages\torch\lib\torch_cpu.dll".

I installed pytoch using conda. and some of the packages too. The packages that could not be installed using conda were opencv, json-tricks, yacs, tensorboardx

How can I fix this? What is causing the error?

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
The most probable reasons are listed as follows.
1. You have some confliciting DLLs in SystemRoot or PATH. e.g. libiomp5md.dll Actu

**Comment by peterjc123** [comment]
Possible reasons:
1. There are some conflicting DLLs be loaded in the SystemRoot or PATH. Actually, you may figure out what DLLs are loaded with the help of Process Monitor.
2. You updated PyTorch but the old version is somehow not removed. If this is the case, please uninstall it again first.

**Comment by mszhanyi** [comment]
@NahianAlindo , Has this issue still existed?

**Comment by vladimir-aubrecht** [comment]
Closing this ticket as issue is stale and cannot be reproduced. Feel free to create new issue if problem will reappear.
