### ISSUE TITLE
how can i use tuple in pytorch.mobile?

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/pytorch#44625]
In org, i have

import org.pytorch.Tensor;
import org.pytorch.Module;
import org.pytorch.IValue;
import org.pytorch.torchvision.TensorImageUtils;

`Tensor outputs = model.forward(inputs).toTensor();
`
but actually my model output was tuple so i changed 

`Tensor outputs = model.forward(inputs).toTuple();
`
but... there is no tuple outputs.... how can i define tuple output...?

**Comment by Coderx7** [comment]
The output tensor is your tuple. if its like the api in libtorch, you should be using the `elements()` to access each item in your tuple. 
you'd do sth like this in the libtorch and I believe its the same for you as well : 
supposing your tuple contains two values, you'd likely want to do : 
```cpp
auto outputs = this->model.forward({inputs}).toTuple();
auto value1 = outputs->elements()[0].toTensor().data().cpu(); 
auto value2 = outputs->elements()[1].toTensor().data().cpu();
```

**Comment by SungmanHong** [comment]
Thanks, it really helped! I'm deeply seeing the code! thx!!
