### ISSUE TITLE
rewrite the torch.sparse main doc page

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#44635]
Update the [main doc page for sparse](https://pytorch.org/docs/master/sparse.html). What is needed includes at least:

- remove the legacy constructors (`torch.sparse.FloatTensor` et al.), use `torch.sparse_coo_tensor` instead and explain it's a regular `Tensor` instance:

```
>>> s = torch.sparse_coo_tensor(indices=[[0, 3]], 
...                             values=[[1, 2], [3, 4]], 
...                             size=(4, 2))                               
>>> s                                                                      
tensor(indices=tensor([[0, 3]]),
       values=tensor([[1, 2],
                      [3, 4]]),
       size=(4, 2), nnz=2, layout=torch.sparse_coo)
>>> type(s)                                                                
<class 'torch.Tensor'>
```

- do not use any private methods (e.g. `._indices()` --> `.indices()`).
- add docstrings to sparse-specific methods (e.g. `coalesce()`, `is_coalesced()`.
- explain the main purpose(s) of sparse tensors. for example, the word "memory" is not present on the page right now.
- explain the purpose of the `torch.sparse` namespace (which is, hold functions where the "unspecified elements are 0" assumption doesn't hold or somehow sparse/dense don't have the same behaviour).
- explain that functions in the `torch` namespace _may_ support sparse tensors, and give a few representative code examples (e.g. using `torch.bmm`)
- explain the purpose of a hybrid tensor and give more details on it

cc @jlin27 @vincentqb @aocsa @nikitaved @pearu

**Comment by vadimkantorov** [comment]
For me it was super-confusing multitude of different matrix multiply ops:
torch.mm, torch.matmul torch.sparse.mm, torch.sparse.FloatTensor.spmm, torch.sparse.FloatTensor.hspmm, torch.sparse.FloatTensor.sspmm

My practical usecase was sketching: dense-sparse multiply with +1/-1 sparse matrix (requires no gradient to the sparse tensor): https://gist.github.com/vadimkantorov/d9b56f9b85f1f4ce59ffecf893a1581a#file-compact_bilinear_pooling-py-L15

**Comment by pearu** [comment]
> For me it was super-confusing multitude of different matrix multiply ops:
> torch.mm, torch.matmul torch.sparse.mm, torch.sparse.FloatTensor.spmm, torch.sparse.FloatTensor.hspmm, torch.sparse.FloatTensor.sspmm

@vadimkantorov , see the table in https://github.com/pytorch/pytorch/blob/d0cff74c74e6b6d7e722cd63dc74cb70d588d172/docs/source/sparse.rst#linear-algebra-operations
that illustrates the differences of various matmul operations. HTH.

**Comment by vadimkantorov** [comment]
Could you also add a generic torch.matmul there?

**Comment by vadimkantorov** [comment]
Also, when it mentions "sparse_grad", it always means the sparse grad wrt to the sparse argument, right?

**Comment by pearu** [comment]
> Also, when it mentions "sparse_grad", it always means the sparse grad wrt to the sparse argument, right? (grad wrt dense argument would always be dense)

yes

> And sometimes no gradient wrt to sparse argument is needed at all, only wrt the dense argument (like in my example with sketching), and the output is dense. I had a hard time to find such an op.

Yes, many of these functions support gradients against `strided` inputs while not for `sparse_coo` inputs.
This info is not present in the current table.

**Comment by vadimkantorov** [comment]
Also it was not obvious that these functions are not necessarily symmetric under switching argument order and transposing

**Comment by pearu** [comment]
> Also it was not obvious that these functions are not necessarily symmetric under switching argument order and transposing (especially for the case when sparse argument does not require grad)

@vadimkantorov thanks for the feedback. I have added a note regarding unsupported `dense @ sparse` and the transpose based workaround.

Btw, https://github.com/pytorch/pytorch/pull/39526 implements `sparse @ sparse`. When merged, the docs should be updated for layout `M[sparse_coo] @ M[sparse_coo]`.
