### ISSUE TITLE
[feature request] ONNX export for torch.std_mean / torch.var_mean

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#44636]
A workaround would be to compute std and mean separately. Then it oculd be supported even for existing opset.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by vadimkantorov** [comment]
hmm, it seems it should already be supported: https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L2292

will check again why it failed in my case

**Comment by spandantiwari** [comment]
We recently merged a PR (https://github.com/pytorch/pytorch/pull/45678) adding support for `var_mean` and `std_mean`. Please try it out and see if we can close this item.

**Comment by vballoli** [comment]
Hi both `var_mean`, `std_mean` fail when I'm trying to export to onnx, even though these implementations exists https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py#L2292. I tried registering them as a custom op, but torch.ops.custom_ops still doesn't recognize. Even tried accessing it manually, but I couldn't find any of these ops. These ops are missing from the `symbolic_opset9.py` file from my latest pytorch installation(`v 1.7.1`) Can anyone help me navigate around this issue ?

**Comment by spandantiwari** [comment]
@vadimkantorov - thanks for pointing out this open issue. We should have support for these two through this OR https://github.com/pytorch/pytorch/issues/39349. Closing this now. Feel free to reopen if we missed something.

**Comment by vadimkantorov** [comment]
@spandantiwari My colleague stumbled on this still not working. So probably will reopen soon again with a repro

**Comment by spandantiwari** [comment]
I see. Sure, please add the repro.

**Comment by II245** [comment]
@spandantiwari Hi! Everything is correct in the version of Pytorch 1.8. Thank you!

**Comment by spandantiwari** [comment]
Thanks @II245.
