### ISSUE TITLE
[ppc64le] test_cuda.py fails with newly added test test_stft

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#4464]
The error is  --  python: /home/freddie/builder/jenkins/pytorch/pytorch/aten/src/ATen/ArrayRef.h:138: const T& at::ArrayRef<T>::operator[](size_t) const [with T = long int; size_t = long unsigned int]: Assertion `Index < Length && "Invalid index!"' failed.
test/run_test.sh: line 62: 157891 Aborted                 $PYCMD test_cuda.py $@

I believe the commit that did this was:  d8b2e5d0916a85e603c9bda6def5cd20cbe94fa6

I am using Cuda 9 with cuDNN 7.0 , on  RH 7.4

**Comment by SsnL** [comment]
What's your architecture and could you build with DEBUG=1 and paste the trace?

**Comment by avmgithub** [comment]
Architecture is ppc64le.  Sure I will build with DEBUG=1.
What trace are you referring to ?  The build output trace ?   Or the trace when I run the test ?

**Comment by SsnL** [comment]
The trace when the test errors. Ideally which PyThon stft call and the c trace. :) Thanks!

**Comment by avmgithub** [comment]
Here is the result -  I compiled with DEBUG=1 and then ran  "python test_cuda.py TestCuda.test_stft"
Result \:

ERROR: test_stft (__main__.TestCuda)

Traceback (most recent call last):
  File "test_cuda.py", line 1004, in test_stft
    TestTorch._test_stft(self, lambda t: t.cuda())
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/test_torch.py", line 2704, in _test_stft
    _test((2, 5), 4, 2, pad_end=1)
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/test_torch.py", line 2697, in _test
    result = x.stft(frame_length, hop, fft_size, return_onesided, window, pad_end)
RuntimeError: Not enough padding values (1) supplied, expecting 2 (while checking arguments for cudnn_convolution)

----------------------------------------------------------------------
Ran 1 test in 0.541s

FAILED (errors=1)

Also I am using python3 from Anaconda if that makes any difference

**Comment by SsnL** [comment]
hmm this is a different error than you originally posted. But I will fix this one in an upcoming fft PR. Thanks :)

**Comment by soumith** [comment]
fixed via #4544
