### ISSUE TITLE
how distributed.rpc package manages nodes

### ISSUE THREAD

**Issue by frank-dong-ms** [pytorch/pytorch#44658]
I have several questions about distributed.rpc package, hope someone could shed a light on them, thanks:

1. Looks like during rpc init(init_rpc), all nodes need to call init_rpc then init will be finished, otherwise all nodes will block waiting. Is there any reason for that behavior? In some scenario, when main node get initialized and some (not all) workers got initialized, the main node should able to send some work to workers and no need to wait for all workers to be initialized.
2. Does rpc support adds/removes nodes after all nodes got initialized?
3. What will happen if some node got disconnected after all nodes got initialized? Will the rest of nodes blocking waiting or other nodes will work as normal?
4. Does rpc have any fail recover built in or plan to introduce in future?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
We usually answer questions there.

**Comment by frank-dong-ms** [comment]
I see, I will close this one and post my questions to the forum, thanks.
