### ISSUE TITLE
[RFC] Integrate profiler with torch.distributed APIs for profiling of distributed models

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#44673]
## 🚀 Feature
with @mrzzd @ilia-cher @pritamdamania87 
The [profiler](https://pytorch.org/docs/stable/autograd.html#profiler) is a useful tool to gain insight regarding the operations run inside a model, and is a commonly used tool to diagnose performance issues and optimize models. This RFC seeks to describe how the profiler will be integrated with `torch.distributed`.

## Example use cases

Python:
```python
# directly calling c10d APIs from python
with torch.autograd.profiler.profile() as prof:
    pending_work = []
    for i in range(5):
        w = dist.all_reduce(torch.ones(i), async_op=True)
        pending_work.append(ww)
    for w in pending_work:
        w.wait()
            
# Should show time and ideally shapes for each input
print(prof.key_averages.table())
```

C++:
```cpp
// directly calling c10d APIs from C++ 
{
    torch::autograd::profiler::enableProfiler();
    std::vector<Work> w;
    for (i = 0 ; i < 10; ++i) { 
      auto work = process_group->allreduce(torch::ones(i));
      w.push_back(work);
    } 
    for (const auto& w : work) {
      w.wait();
    }
    torch::autograd::profiler::disableProfiler();
    // We should expect that the events contain the entire asynchronous running 
    // time, not just the synchronous part of the call into allreduce().

}
```

DDP example: 

```python
# DDP training, should include profiling of c10d calls. 
ddp_model = DDP(model, device_ids=[torch.cuda.current_device()])
# forward pass of models with c10d collectives should be profiled. 
with torch.autograd.profiler.profile() as prof:
    outputs = ddp_model(torch.randn(20, 10).to(torch.cuda.current_device()))
    loss_fn(outputs, labels).backward()
```

Note that above, we can probably get information about the shape of tensors that were allreduced as well, which can be input into the `RECORD_FUNCTION` macro. This can potentially provide better debugging information in the case of mismatches, as the profiler shapes for each call would differ across ranks, giving clues into the source of the mismatch.

### Current state of distributed profiling 
Profiling within the RPC framework has been enabled (https://github.com/pytorch/pytorch/issues/39675). Currently, profiling a DDP model outputs the expected information about native torch operators ran in the model's forward and backwards passes, but no information about allreduce (or any other collective calls that the user might have in their model definition):

```
-----------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ------
---------
Name                                 Self CPU total %  Self CPU total   CPU total %      CPU total        CPU time avg     CUDA total %     CUDA total       CUDA time avg    Numbe
r of Calls
-----------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ---------------  ------
---------
aten::randn                          0.07%            138.438us        0.23%            435.920us        217.960us        0.22%            430.556us        215.278us        2

aten::normal_                        0.10%            180.898us        0.10%            180.898us        90.449us         0.09%            181.057us        90.528us         2

aten::to                             0.08%            143.406us        0.35%            661.556us        330.778us        0.33%            658.535us        329.268us        2

aten::empty_strided                  0.15%            281.560us        0.15%            281.560us        93.853us         0.14%            280.745us        93.582us         3

aten::copy_                          0.15%            283.815us        0.15%            283.815us        141.908us        0.14%            283.748us        141.874us        2

Scatter                              0.17%            323.877us        0.31%            592.141us        592.141us        0.30%            591.232us        591.232us        1
```

The following use of the `record_function` context manager doesn't work for our use cases either: 
```python
with profiler():
    with record_funcion("allreduce"):
        work = dist.all_reduce(async_op = True)
    work.wait()
```
since the async portion of the allreduce would not be profiled (similar to the issue encountered with RPC profiling). 

### Design and Implementation
We will follow an approach similar to the way async functions in `torch.distributed.rpc` are profiled, and an example of this approach being generalized to general distributed functions is in https://github.com/pytorch/pytorch/pull/44436. At a high level, we would like insert `RecordFunction` objects that will run profiling callbacks at the beginning and end of the functions that we'd like to profile.

To make this work for async functions, we have to extend the lifetime of the `RecordFunction` so that the profiler's end callbacks do not run when the sync part of the function exits (which is what it'd do by default). 

In order to do this, we have introduced an API called [rf._call_end_callbacks_on_future](https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py#L441) which schedules the RecordFunction's end callbacks to be run after the future is marked as completed. This returns a new future that can be waited on, after which we have a guarantee that the future has been profiled. 

In order to support this, we would need to provide a `get_future()` API that converts `Work` to `Future` for both `NCCL` work and `Gloo`. https://github.com/pytorch/pytorch/pull/42335 adds `get_future()` for NCCL and https://github.com/pytorch/pytorch/pull/44436/ adds it for Gloo. Given this, we could profile collectives from python via:

```python
# This will be wrapped into a function so users don't have to call with record_function(....)
with record_function as rf:
    work = dist.all_reduce(....)
    rf._call_end_callbacks_on_future(work.get_future()
# Work can now be awaited within the profiler scope outside of record_function, and will have
# its correct execution time recorded.
```

Note: the above is probably a short/medium-term solution, and in the long term we'd probably want to merge `Work` and `Future` so that we have only a single representation of asynchronous work object in distributed code. 

At the C++ level, the profiling would look something like the following:

```cpp
auto handle = record_function_enter(...)
auto work = process_group->allreduce(....)
profiler::_call_end_callbacks_on_future(handle, work.getFuture())
```

Note that this is quite similar to how we profile `rpc_async` calls from JIT functions, which is entirely in C++: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/torchscript_functions.cpp#L77

One thing to keep in mind as @pritamdamania87 mentioned is that since the `ProcessGroup.hpp` interface should be stable due to c10d extension API, we will have to add this profiling to collective ops individually in `ProcessGroupGloo` and `ProcessGroupNCCL`. 

### Combining profiles across nodes 
As mentioned by https://github.com/pytorch/pytorch/issues/43231, it would be good to have an API such as `torch.distributed.profiling.combine_profiles` which allows any rank to collect profiles from different ranks. This can be implemented by using the recently introduced `torch.distributed.gather_object()` APIs (https://github.com/pytorch/pytorch/pull/42189), we would just need to ensure that `class profile` can be pickled.  We can then combine profiles locally and export a single trace for all nodes using `prof.export_chrome_trace()`. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by sraikund16** [comment]
We have developed downstream tools to interact with distributed models such as HTA and Zoomer. Closing as this issue is stale
