### ISSUE TITLE
floor_divide ONNX export is divergent from floor_divide in PyTorch behavior

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#44692]
After https://github.com/pytorch/pytorch/pull/43879 is landed PyTorch's `floor_divide` operator will be consistent with floor division in Python3 and NumPy. The new behavior is:

```
floor_divide(a, b) = torch.true_divide(a, b).floor_()
```

And the old behavior is:

```
floor_divide(a, b) = torch.true_divide(a, b).trunc_()
```

For example, -5 // 3 = -2 in Python3 and PyTorch after #43879, but -5 // 3 = -1 in C, C++, and PyTorch before #43879. The behavior is equivalent when the divisor and dividend are both positive or both negative, but different if one is positive and the other negative.

PyTorch's ONNX behavior still reflects the historic floor division behavior, however, and needs to be updated to be consistent. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by albanD** [comment]
Adding triage review to discuss if this should be high priority or not.

**Comment by BowenBao** [comment]
@mruberry thanks for the info. We can make the corresponding updates to the exporter to stay consistent. 

A related question here, is this operator following the same type promotion logic like regular arithmetic ops such as add/mul?

**Comment by mruberry** [comment]
> @mruberry thanks for the info. We can make the corresponding updates to the exporter to stay consistent.

Thanks @BowenBao!
 
> A related question here, is this operator following the same type promotion logic like regular arithmetic ops such as add/mul?

Yes. Great question.

**Comment by ezyang** [comment]
I think it can be up to the ONNX team to decide whether or not to mark this high prio or not.

**Comment by mruberry** [comment]
Closing this for the moment because we decided to deprecate torch.floor_divide's behavior, mooting this for 1.7.
