### ISSUE TITLE
build failed Pytorch 1.6 on Ubuntu 18.04

### ISSUE THREAD

**Issue by NAEE09** [pytorch/pytorch#44709]
## 🐛 Bug

Error : the functions 'depthwise_3x3x3_per_channel_quantization_pad_1',  'depthwise_3x3x3_pad_1' are not declared in scope, when I try to compile PyTorch.

## To Reproduce

1. git clone https://github.com/pytorch/pytorch
2. cd pytorch 
3. git submodule sync
4. git submodule update --init --recursive
5. mkdir build 
6. cd build 
(Config CMakeLists.txt with BUILD_PYTHON OFF)
7. cmake ../ 
8. make -j4

Error:
`/home/nae/Libraries/pytorch/caffe2/quantization/server/conv_dnnlowp_op.cc: In instantiation of ‘void caffe2::ConvDNNLowPOp<T, ReluFused>::ConvNHWCCore_(const T*, std::vector<int>*) [with T = unsigned char; bool ReluFused = false]’:
/home/nae/Libraries/pytorch/caffe2/quantization/server/conv_dnnlowp_op.cc:1752:16:   required from here
/home/nae/Libraries/pytorch/caffe2/quantization/server/conv_dnnlowp_op.cc:1211:55: error: ‘depthwise_3x3x3_per_channel_quantization_pad_1’ was not declared in this scope
...`

## Expected behavior
Ready to finish installing--> sudo make install

## Environment
 - PyTorch Version (e.g., 1.0): v1.6.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake 
 - Python version: 3.6.9
 - CUDA/cuDNN version: No
 - GPU models and configuration:
 - Any other relevant information:

cc @malfet @seemethere @walterddr

**Comment by ngimel** [comment]
From repro instructions it looks like you are building master version from source, not installing 1.6

**Comment by NAEE09** [comment]
Problem solved. I have to run again these commands 

git submodule sync
git submodule update --init --recursive

According:

https://github.com/pytorch/pytorch/issues/43008#issue-678485916
https://github.com/pytorch/pytorch/issues/35602

**Comment by NAEE09** [comment]
Problem solved

Run again

git submodule sync
git submodule update --init --recursive

According to these issues:

https://github.com/pytorch/pytorch/issues/35602
https://github.com/pytorch/pytorch/issues/43008
