### ISSUE TITLE
Visual C++ ATen Command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible

### ISSUE THREAD

**Issue by N-Dekker** [pytorch/pytorch#4475]
The current master dc76db349e9022b8b4e23de19780a5edf63cc5a1 triggers the following error messages from Visual Studio 2015 (Debug build):

2>------ Build started: Project: ATen, Configuration: Debug x64 ------
2>cl : Command line error D8016: '/Ox' and '/RTC1' command-line options are incompatible
...
14>LINK : fatal error LNK1104: cannot open file '....\src\ATen\Debug\ATen.lib'

It appears that they are triggered by *.c files in the ATen project, like "src\TH\vector\AVX.c"

**Comment by peterjc123** [comment]
@N-Dekker Why do you need Debug build?

**Comment by N-Dekker** [comment]
@peterjc123 Isn't ATen meant to support both Debug and Release builds?
FYI I'm involved with the project at https://github.com/SuperElastix/SuperElastix which does support both build configurations, and we would like to be able to link our project with ATen.

**Comment by peterjc123** [comment]
Well, you can remove the `/Ox` flags in `aten\src\ATen\CMakeLists.txt` as a workground.

**Comment by apaszke** [comment]
We should patch this file to ignore this flag when building the library in debug mode. It shouldn't be too hard

**Comment by peterjc123** [comment]
@kirill-pinigin There're two issues in your description.
The first question is easy. You'll also have to specify the flag `DEBUG` to 1.
The second question is about your compiler. I guess you are using VS2015 or earlier versions of VS2017. Make sure the version in the output is above 19.11 after your enter `cl.exe` in CMD.

**Comment by kirill-pinigin** [comment]
@peterjc123 Yes I am using VS2015. My Compiler  is 19.0.2. Must I use VS 2017 in any case?

**Comment by peterjc123** [comment]
@kirill-pinigin Sorry, but the answer is yes. The AVX2 functions was added in VS2017 and they are used in PyTorch. So VS2017 19.11 is a must.

**Comment by kirill-pinigin** [comment]
@peterjc123  No problem:)  Thank you.
