### ISSUE TITLE
Make enable/disable fake_quant and observer global functions

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#44751]
Currently they reside in the module, but can be global values instead. 
https://github.com/pytorch/pytorch/blob/master/torch/quantization/fake_quantize.py#L66-L83

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by zetyquickly** [comment]
Hello @supriyar,

Did you mean https://github.com/pytorch/pytorch/blob/master/torch/quantization/fake_quantize.py#L43-L57?

Why is it might be bad to keep these functions?

**Comment by supriyar** [comment]
IIRC the motivation was to keep them as global flags and they don't need to be specific to each module. 
@jerryzh168 do you remember the motivation for this issue?

**Comment by vkuzo** [comment]
for triage

**Comment by supriyar** [comment]
Motivation for this issue is not very clear. Closing
