### ISSUE TITLE
StepLR - example

### ISSUE THREAD

**Issue by pefi9** [pytorch/pytorch#4476]
Hi,
In the https://github.com/pytorch/pytorch/blob/e9ef20eab5e5cf361bdc7a425c7f8b873baad9d3/torch/optim/lr_scheduler.py#L86-L89 is written: "lr values are [0.05, 0.005, ...]."
If I understand it correctly, it should be [0.5, 0.05, 0.005, ...].

**Comment by zou3519** [comment]
That is correct. Please feel free to send a PR to fix it! (otherwise, I can)

**Comment by pefi9** [comment]
If you don't mind, I'm not contributor yet and don't want to start just for one comment. I guess `MultiStepLR` is the same case.
