### ISSUE TITLE
is there some functions like layer.get_config() in keras?

### ISSUE THREAD

**Issue by Stick-To** [pytorch/pytorch#44776]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
I want to get the name of input layer of some modules, is there some function like layer.get_config() in keras?

**Comment by mruberry** [comment]
You can acquire a module's parameters and buffers by querying for them, which may be what you want. This question is more appropriate for our forums, however. Try asking there.

**Comment by Stick-To** [comment]
![1](https://user-images.githubusercontent.com/34546552/93446648-078ba880-f904-11ea-83eb-7aa1eef50455.png)
I want to get some information like this
@mruberry

**Comment by mruberry** [comment]
You can print the module (and recursively print its contents). To the precise behavior you want you may have to write your own print function.
