### ISSUE TITLE
Pytorch 1.6 / torch_nightly doesn't support static-quantization for `F.conv2d` (aten::thnn_conv2d_forward) 

### ISSUE THREAD

**Issue by AlexeyAB** [pytorch/pytorch#44782]
## To Reproduce

1.  Pytorch 1.6 / torch_nightly doesn't support static-quantization for `F.conv2d` (aten::thnn_conv2d_forward) , reproduce in Colab: https://colab.research.google.com/gist/AlexeyAB/34c6e6cf0df6f00f885137ec9305b048/pytorch_quant_pad_same.ipynb#scrollTo=rHA6VFU0-xMH

>RuntimeError: Could not run 'aten::thnn_conv2d_forward' with arguments from the 'QuantizedCPU' backend. 'aten::thnn_conv2d_forward' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

## Environment

Collecting environment information...
PyTorch version: 1.7.0.dev20200916+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0.dev20200916+cpu
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
hi @AlexeyAB , the stack trace in this case is helpful:

```
/root/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/conv2d_layers.py in forward(self, x)
    110             x = self.pad(x)
    111         return F.conv2d(
--> 112             x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
```

The issue is that `F.conv2d` is a functional call to conv which is not supported by PyTorch Eager Mode Quantization.  To use eager mode, this would need to be rewritten to use `torch.nn.Conv{1|2|3}d` in order for the `torch.quantization.prepare` API to pick it up correctly.  https://github.com/pytorch/pytorch/pull/45093 might be helpful with some examples (we will land that doc update soon).
 
We are working on a more automated quantization flow which will remove this requirement, but it is not ready yet.  The current production version only knows how to quantize modules.

**Comment by AlexeyAB** [comment]
@vkuzo Hi,
Thanks for explanation.

> We are working on a more automated quantization flow which will remove this requirement, but it is not ready yet. The current production version only knows how to quantize modules.

Will it be static-quantization for graph-mode?
Are there any approximate dates, is it a month or a year?

**Comment by vkuzo** [comment]
> Will it be static-quantization for graph-mode?

yes, it will work by inspecting the graph, for all quantization modes

> Are there any approximate dates, is it a month or a year?

definitely more than a month, likely a couple of months although we definitely do not have an actual release date yet.  Please feel free to check out https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_fx.py, although the codebase is in flux and there are no docs or stability guarantees yet.

**Comment by AlexeyAB** [comment]
@vkuzo Thanks!

I added some fixes to the EfficientNet models: https://github.com/rwightman/gen-efficientnet-pytorch/pull/49
But there is still an issue with `nn.ZeroPad2d` : https://colab.research.google.com/gist/AlexeyAB/820648ce1e6a8ae25ea5bdb49a0c7a81/pytorch_quant_pad_same.ipynb#scrollTo=rHA6VFU0-xMH

In this part of code: https://github.com/AlexeyAB/gen-efficientnet-pytorch/blob/c71e15ed5432cdb3537d1665b933be6df176b934/geffnet/conv2d_layers.py#L109-L115

Do you know a simple solution for this?

Error message:
```
/root/.cache/torch/hub/AlexeyAB_gen-efficientnet-pytorch_quantization/geffnet/conv2d_layers.py in forward(self, x)
    113 
    114         if self.pad is not None:
--> 115             x = self.pad(x)
    116         return self.conv(x)
    117 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/padding.py in forward(self, input)
     19 
     20     def forward(self, input: Tensor) -> Tensor:
---> 21         return F.pad(input, self.padding, 'constant', self.value)
     22 
     23     def extra_repr(self) -> str:

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in _pad(input, pad, mode, value)
   3558     assert len(pad) // 2 <= input.dim(), 'Padding length too large'
   3559     if mode == 'constant':
-> 3560         return _VF.constant_pad_nd(input, pad, value)
   3561     else:
   3562         assert value == 0, 'Padding mode "{}"" doesn\'t take in value argument'.format(mode)

RuntimeError: Quantized copy only works with contiguous Tensors
```

**Comment by AlexeyAB** [comment]
@vkuzo 

Have you ever seen something like this? I use the same model in several cases with the same Pytorch 1.6.0 / LibTorch 1.6.0:
* **non-quantized** model - OnePlus8 Snapdragon 865 - the **accuracy is bad and fast inference**
* **quantized** model - OnePlus8 Snapdragon 865 - the **accuracy is medium and 3x slower inference**

Currently I can not post these results as they are private.

Why does custom-quantization increase accuracy and slow down the speed (while it should be vice versa)?
It looks like it uses much stronger quantization automatically if custom int8-quantization isn't used.
The same non-quantized model has very different accuracy on different devices: iPhone 11 A13 bionic (good accuracy), Xiaomi Mi6 Snapdragon 835 (medium accuracy), OnePlus8 Snapdragon 865 (bad accuracy).

1. Does Pytorch-mobile TorchLib 1.6.0 (or some libraries which LibTorch uses) use some quantization automatically?

2. Do underlying libraries, drivers, or hardware (CPU Snapdragon 865) use some quantization automatically?


I use `torch.quantization.get_default_qconfig('qnnpack')` and `torch.utils.mobile_optimizer.optimize_for_mobile`

I don't use `memory_format=torch.channels_last` or `torch.quantization.quantize_dynamic`

**Comment by jerryzh168** [comment]
> @vkuzo Thanks!
> 
> I added some fixes to the EfficientNet models: [rwightman/gen-efficientnet-pytorch#49](https://github.com/rwightman/gen-efficientnet-pytorch/pull/49)
> But there is still an issue with `nn.ZeroPad2d` : https://colab.research.google.com/gist/AlexeyAB/820648ce1e6a8ae25ea5bdb49a0c7a81/pytorch_quant_pad_same.ipynb#scrollTo=rHA6VFU0-xMH
> 
> In this part of code: https://github.com/AlexeyAB/gen-efficientnet-pytorch/blob/c71e15ed5432cdb3537d1665b933be6df176b934/geffnet/conv2d_layers.py#L109-L115
> 
> Do you know a simple solution for this?
> 
> Error message:
> 
> ```
> /root/.cache/torch/hub/AlexeyAB_gen-efficientnet-pytorch_quantization/geffnet/conv2d_layers.py in forward(self, x)
>     113 
>     114         if self.pad is not None:
> --> 115             x = self.pad(x)
>     116         return self.conv(x)
>     117 
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     725             result = self._slow_forward(*input, **kwargs)
>     726         else:
> --> 727             result = self.forward(*input, **kwargs)
>     728         for hook in itertools.chain(
>     729                 _global_forward_hooks.values(),
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/padding.py in forward(self, input)
>      19 
>      20     def forward(self, input: Tensor) -> Tensor:
> ---> 21         return F.pad(input, self.padding, 'constant', self.value)
>      22 
>      23     def extra_repr(self) -> str:
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in _pad(input, pad, mode, value)
>    3558     assert len(pad) // 2 <= input.dim(), 'Padding length too large'
>    3559     if mode == 'constant':
> -> 3560         return _VF.constant_pad_nd(input, pad, value)
>    3561     else:
>    3562         assert value == 0, 'Padding mode "{}"" doesn\'t take in value argument'.format(mode)
> 
> RuntimeError: Quantized copy only works with contiguous Tensors
> ```

constant pad is not supported yet I think, we are tracking it here: https://github.com/pytorch/pytorch/issues/43394
feel free to submit a PR to fix it. currently it is not high-pri for us.

**Comment by jerryzh168** [comment]
> @vkuzo
> 
> Have you ever seen something like this? I use the same model in several cases with the same Pytorch 1.6.0 / LibTorch 1.6.0:
> 
> * **non-quantized** model - OnePlus8 Snapdragon 865 - the **accuracy is bad and fast inference**
> * **quantized** model - OnePlus8 Snapdragon 865 - the **accuracy is medium and 3x slower inference**
> 
> Currently I can not post these results as they are private.
> 
> Why does custom-quantization increase accuracy and slow down the speed (while it should be vice versa)?
> It looks like it uses much stronger quantization automatically if custom int8-quantization isn't used.
> The same non-quantized model has very different accuracy on different devices: iPhone 11 A13 bionic (good accuracy), Xiaomi Mi6 Snapdragon 835 (medium accuracy), OnePlus8 Snapdragon 865 (bad accuracy).
> 
> 1. Does Pytorch-mobile TorchLib 1.6.0 (or some libraries which LibTorch uses) use some quantization automatically?
> 2. Do underlying libraries, drivers, or hardware (CPU Snapdragon 865) use some quantization automatically?
> 
> I use `torch.quantization.get_default_qconfig('qnnpack')` and `torch.utils.mobile_optimizer.optimize_for_mobile`
> 
> I don't use `memory_format=torch.channels_last` or `torch.quantization.quantize_dynamic`

cc @dreiss @ljk53 for mobile numerics questions

could you post the accuracy and speedup result on cpu (with fbgemm enabled) as a sanity check?

**Comment by jerryzh168** [comment]
Also for questions please use: https://discuss.pytorch.org/

**Comment by vkuzo** [comment]
for triage

**Comment by supriyar** [comment]
closing as this is an old issue and pytorch now supports static quantization of F.conv2d via graph mode quantization APIs
