### ISSUE TITLE
caffe2 c++ inference  on windows10

### ISSUE THREAD

**Issue by yang-gis** [pytorch/pytorch#44785]
## ❓ Questions and Help

I have installed caffe2 from the source on Windows10 and tested the python code.I found that Cuda (GPU) can be successfully called.Subsequently, I have tested the CPU version of the caffe2 model  (init_net.pb and predict_net.pb) by caffe2 c++ api and found that it runs successfully, but the GPU version of the caffe2 model  always makes mistakes at "workSpace.RunNetOnce(initNet_)". The error message is:"0x00007FFBCAE6DB9E (ucrtbase.dll) (caffe2_mask_rcnn.exe) has unhandled exception: request for serious program exit."

I don't know if it's caffe2's c++ API that doesn't support gpu models.Besides, could you give me some help?

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mruberry** [comment]
Sorry you're hitting this issue, @yang-gis. Caffe2 is no longer supported, but you may find help on our forum at https://discuss.pytorch.org/.
