### ISSUE TITLE
Variable(None) seems wrong

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4483]
The expression `Variable(None)` is accepted without exception in PyTorch, but it will give a Variable wrapping a zero-size(??) tensor, which is basically not something you ever want; you want to an undefined tensor.

Perhaps this problem will go away when Tensor and Variable unify.

**Comment by colesbury** [comment]
Yeah, `Variable(None)` is weird. Probably only accidentally supported because of the definition of `nn.Parameter`'s constructor.

RE: undefined vs. zero-sized: I think it's the reverse. We support zero-sized tensors (and variables) in Python. Undefined tensors should never escape to Python.
