### ISSUE TITLE
fx: assertions based on tensor shapes are not symbolically traceable

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#44849]
This currently fails:

```
import torch

class M(torch.nn.Module):
    def forward(self, x, y):
        assert x.shape == y.shape
        return x + y
    
m = M()
gm = torch.fx.symbolic_trace(m)
print(gm)

...
<ipython-input-3-28ec5aecf51c> in forward(self, x, y)
      3 class M(torch.nn.Module):
      4     def forward(self, x, y):
----> 5         assert x.shape == y.shape
      6         return x + y
...
TraceError: symbolically traced variables cannot be used as inputs to control flow
```

Is this something we'd consider special casing and supporting in the future?

**Comment by jamesr66a** [comment]
The issue here is that in Python, an `assert` statement is just syntactic sugar. The statement `assert x, msg` lowers to:
```
if not x:
  raise AssertionError(msg)
```

This can be confirmed by:
```
# assert.py
a = 3
assert a == 3
```

```
$ python -m dis assert.py
  1           0 LOAD_CONST               0 (3)
              2 STORE_NAME               0 (a)

  2           4 LOAD_NAME                0 (a)
              6 LOAD_CONST               0 (3)
              8 COMPARE_OP               2 (==)
             10 POP_JUMP_IF_TRUE        16
             12 LOAD_GLOBAL              1 (AssertionError)
             14 RAISE_VARARGS            1
        >>   16 LOAD_CONST               1 (None)
             18 RETURN_VALUE
```

So in the case of the example, the result of the expression `x.shape == y.shape` is indeed being used as the condition of an `if` statement and thus control flow

I'm not sure if there's much we can do here apart from the user rewriting their code. Maybe provide a `torch.assert(x)` operator? Then the invocation can be traced and retained in the graph

**Comment by vkuzo** [comment]
> user rewriting their code

thanks for the explanation, sounds reasonable.  `torch.assert` or some variant with special handling in fx thereof sounds good if users are adamant about keeping these - will check.

**Comment by vkuzo** [comment]
would it make sense to provide `torch.fx.is_tracing()`, so users can gate the asserts on that flag?

**Comment by jamesr66a** [comment]
@vkuzo `is_tracing()` is a gateway to introducing tech debt in user's code (e.g. we don't want to get in this situation: https://fburl.com/codesearch/omqla0l2, it makes the code too complicated and ruins test cover) so we'd like to avoid that. IMO we should bias toward first-class solutions here, e.g. `torch.assert`. BTW if you (or someone else) want to send a PR to add that op, I can review it

**Comment by jamesr66a** [comment]
In addition to `torch.assert` we could also explore doing an AST rewrite on `forward` methods that are being traced to automatically convert `asset` statements to callsites to that. Don't think it would be too difficult and would open the door to more friendly workarounds in the future
