### ISSUE TITLE
Support for quantized maxpool 1d

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#44852]
Support for maxpooling is restricted to maxpool 2d.  It will be great to have support for maxpool1d so that users need not dequantize tensors when this operator is used in their models.

cc @heitorschueroff @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by z-a-f** [comment]
On it!

**Comment by z-a-f** [comment]
This is done -- if there are issues, please, reopen and ping me
