### ISSUE TITLE
Incorrect processing of autograd profiler outputs in torch.utils.bottleneck

### ISSUE THREAD

**Issue by CedricPicron** [pytorch/pytorch#44869]
## 🐛 Bug
The incorrect processing relates to https://github.com/pytorch/pytorch/blob/b6f4bb0a703d6c33bedf3c7f4551954a8015fcb9/torch/utils/bottleneck/__main__.py#L119.
For simplicity, here's a copy of the code
``` python
def print_autograd_prof_summary(prof, mode, sortby='cpu_time', topk=15):
    valid_sortby = ['cpu_time', 'cuda_time', 'cpu_time_total', 'cuda_time_total', 'count']
    if sortby not in valid_sortby:
        warn = ('WARNING: invalid sorting option for autograd profiler results: {}\n'
                'Expected `cpu_time`, `cpu_time_total`, or `count`. '
                'Defaulting to `cpu_time`.')
        print(warn.format(sortby))
        sortby = 'cpu_time'

    if mode == 'CUDA':
        cuda_warning = ('\n\tBecause the autograd profiler uses the CUDA event API,\n'
                        '\tthe CUDA time column reports approximately max(cuda_time, cpu_time).\n'
                        '\tPlease ignore this output if your code does not use CUDA.\n')
    else:
        cuda_warning = ''

    sorted_events = sorted(prof.function_events,
                           key=lambda x: getattr(x, sortby), reverse=True)
    topk_events = sorted_events[:topk]

    result = {
        'mode': mode,
        'description': 'top {} events sorted by {}'.format(topk, sortby),
        'output': torch.autograd.profiler.build_table(topk_events),
        'cuda_warning': cuda_warning
    }

    print(autograd_prof_summary.format(**result))
```
1. Here `topk_events = sorted_events[:topk]` followed by  `'output': torch.autograd.profiler.build_table(topk_events)` is incorrect. The table is built by using only the `topk_events` (instead of all events), and therefore all mentioned percentages and total times will be wrong in the resulting table. 
2. By using the `build_table` function, one does not go through https://github.com/pytorch/pytorch/blob/99093277c0972535d6ecea2ec4eed98c14895f48/torch/autograd/profiler.py#L36
yielding different CPU times compared with https://github.com/pytorch/pytorch/blob/99093277c0972535d6ecea2ec4eed98c14895f48/torch/autograd/profiler.py#L361
which does go through `populate_cpu_children` via `_check_finish`.
3. Finally, `torch.utils.bottleneck` sorts the table based on https://github.com/pytorch/pytorch/blob/b6f4bb0a703d6c33bedf3c7f4551954a8015fcb9/torch/utils/bottleneck/__main__.py#L186
For the `torch.autograd.profiler.profile` profiler with `use_cuda=True`, sorting based on `cuda_time_total` might be more reliable (see #44784).

## Additional context
See https://discuss.pytorch.org/t/confusion-about-torch-autograd-profiler-profile-api/87773 for an example related to this issue.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @pearu @nikitaved

**Comment by sraikund16** [comment]
Profiler no longer using bottleneck. Issue is stale, closing.
