### ISSUE TITLE
A error about cuda runtime error(59)

### ISSUE THREAD

**Issue by liuxz-cs** [pytorch/pytorch#44867]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

I run my code, and I did not get the error before, I have got the problem recently, and I cannot localize the problem and do not know the reason for that error. The error information as follows :

I do not use the supervised learning, and the training data do not have the label, so it is not the problem of label index. I do not know how to find the real error.

RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCTensorCopy.cu:102
/pytorch/aten/src/THC/THCTensorIndex.cu:395: void WrapIndexOp::operator()(long *, long *): block: [0,0,0], thread: [0,0,0] Assertion `idx < size && idx >= -size` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorCopy.cu line=102 error=59 : device-side assert triggered
Process Process-4:
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/lxz/nav_ai2thor/runners/a3c_adversary_train.py", line 98, in a3c_adversary_train
    loss["total_loss"].backward()
  File "/data/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCTensorCopy.cu:102

cc @ngimel

**Comment by glaringlee** [comment]
@liuxz-cs 
Can you provide a sample code piece to reproduce this? What pytorch version you are using?

**Comment by malfet** [comment]
@liuxz-cs please issues to report problems in PyTorch, and ask general questions on the discussion forum.
As for the reason of the failure, most likely it has something to do with the input values of some operations.
