### ISSUE TITLE
module 'torch.nn' has no attribute 'Unflatten'

### ISSUE THREAD

**Issue by GiovanniPasq** [pytorch/pytorch#44871]
## ❓ Questions and Help
Hello, i'm using the latest version of PyTorch (1.6.0) and i need to use one of them:
1) torch.nn.Unflatten (Python class, in Unflatten)
2) torch.Tensor.unflatten (Python method, in Named Tensors)

However, when i try to use the the example code i have these respectively errors:
1) module 'torch.nn' has no attribute 'Unflatten'
2) zip argument #1 must support iteration

I followed the examples in these link: 
https://pytorch.org/docs/master/named_tensor.html?highlight=unflatten#torch.Tensor.unflatten
https://pytorch.org/docs/master/generated/torch.nn.Unflatten.html?highlight=unflatten#torch.nn.Unflatten

## To Reproduce
1)  ```input = torch.randn(2, 50)
     m = nn.Sequential(
            nn.Linear(50, 50),
           nn.Unflatten(1, (2, 5, 5))
    )
    output = m(output)
    output.size()
2) ```torch.randn(3, 4, 1).unflatten(1, (2, 2)).shape```

**Comment by glaringlee** [comment]
@GiovanniPasq 
Please try the latest pytorch in github master branch. These functions should be available. 
1.6 might not have them since unflatten functions are added 2 months ago.
