### ISSUE TITLE
Can fx add an API for users to register custom module class that won't be symbolically traced

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#44926]
In that case, can we atleast only add custom module. Here it looks like the user is expected to know that torch.nn and sequential are existing leaf modules. Can we request the fx team to have an API to register a custom module?

_Originally posted by @raghuramank100 in https://github.com/pytorch/pytorch/pull/44766#discussion_r490641075_

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
We'll do this in quantization

**Comment by supriyar** [comment]
@jerryzh168 did we plan for this in the API changes?

**Comment by jerryzh168** [comment]
yes, @vkuzo will be looking at this I think.

**Comment by jerryzh168** [comment]
We have a "non_traceable_module_name" and "non_traceable_module_class" in qconfig_dict: https://github.com/pytorch/pytorch/blob/master/test/quantization/test_quantize_fx.py#L1281
