### ISSUE TITLE
a new type of nn.Module param for large transient data (that doesn't get saved)

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#44935]
## 🚀 Feature

So we have params and buffers in `nn.Module`, which are awesome.

What can we do if we have a huge param like variable that we don't want to save with the model, e.g. if that variable gets deterministically calculated and it's huge. For example positional embeddings in transformers models https://github.com/huggingface/transformers/issues/7229 - in the presented example those come to 250MB and can be bigger, yet they aren't trained and are calculated.

So currently one needs to hack around this by either deleting the var from state_dict before saving, or like fairseq approached it - to make the variable non-parameteric, but use a small dummy buffer hack to move the large weights to the right device during `forward` (I'm still referring to the linked issue). Except the latter approach is problematic for torchscript, it wants all the vars to be on the same device before `forward`.

## Request

What if we had a third type of variable, which is like a parameter, but of a transient nature and which automatically gets ignored by load/save yet, otherwise behaves like param/buffer for all other purposes?

Perhaps it has already been suggested/discussed.

Thank you for reading.

cc @albanD @mruberry

**Comment by mruberry** [comment]
Does a nonpersistent buffer do what you want? 

https://pytorch.org/docs/master/generated/torch.nn.Module.html?highlight=buffer#torch.nn.Module.register_buffer

Original issue for context: https://github.com/pytorch/pytorch/issues/18056.

**Comment by stas00** [comment]
@mruberry - that's fantastic! I had no idea we had this in our arsenal now! Thank you so much!

Except it seems to be incomplete - torchscript doesn't handle it correctly. Doing:

```
                # add some non-persistent buffers 
                # model.state_dict() doesn't contain non-persistent buffers.
                traced_gpt2 = torch.jit.trace(model, inputs)
                torch.jit.save(traced_gpt2, pt_file_name)
                loaded_model = torch.jit.load(pt_file_name)
                # `loaded_model.state_dict()` contains the non-persistent buffers.
```
Open a more specific issue?

**Comment by mruberry** [comment]
Glad I could help (a little, anyway). A more specific issue for the JIT behavior would be appreciated, @stas00.

**Comment by stas00** [comment]
Done: https://github.com/pytorch/pytorch/issues/45012

Thank you again, @mruberry! You helped me discover a new feature today!
