### ISSUE TITLE
https://tutorials.pytorch.kr/advanced/cpp_export.html#id1

### ISSUE THREAD

**Issue by Baeleader** [pytorch/pytorch#44930]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Step3. 
root@4b5a67132e81:/example-app/build# ./example-app <path_to_model>/traced_resnet_model.pt
This code is the Linux version, what should I do with the Windows version?

**Comment by agolynski** [comment]
Could you post on discussion forum?
