### ISSUE TITLE
ImportError: libcudnn-a2b758a6.so.7.0.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sahiljuneja** [pytorch/pytorch#4494]
Installed pytorch version for python 2.7 on my system which **has a really old gpu and I don't plan to use it currently for pytorch**.

System - Ubuntu 16.04

I am not working with conda, because some of the work I plan to do requires trying to work with Gazebo and ROS which might have issues with conda. 

Used the following from the website -
```

sudo -H pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl
sudo -H pip install torchvision 
```

After that, I tried to run a DQN python script and get the following error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: libcudnn-a2b758a6.so.7.0.3: cannot open shared object file: No such file or directory
```

Haven't found any associated issues to help with this. 

I downloaded and installed cudnn. Only issue is that from NVidia website v7.0.4 and v7.0.5 were the only versions present. I installed the latter, hasn't helped.

I also don't know why cuda and cudnn are required since I don't plan to work with a GPU and only installed the pytorch version with the option "None" for CUDA version. The link to the whl I posted above has cu80 in its path, and is the same path as for CUDA 8. Is this causing some clash? 

[I have asked to join the Slack to try to get more help on this, so waiting on that too if this isn't the right place]

**Comment by soumith** [comment]
that looks like a botched install. What is the output of the following commands:

```
ls /usr/local/lib/python2.7/dist-packages/torch/
ls /usr/local/lib/python2.7/dist-packages/torch/lib
ldd /usr/local/lib/python2.7/dist-packages/torch/_C*.so*
```

**Comment by mruberry** [comment]
Closing due to age and lack of response. If this is still an issue please update and reopen.
