### ISSUE TITLE
some gradients of parameters in pytorch is None

### ISSUE THREAD

**Issue by liushuai839** [pytorch/pytorch#44944]
Hi,guys!
when I add a learnable parameter(a tensor) in a network, its gradient is None.But i make sure that it is a leaf node.Also,I set the require_grad is true. It works as a index in python. e.g. a[b](a is the learnable parameter )

These are the questions. Thanks for your attention!!

**Comment by SsnL** [comment]
indexing is nondifferentiable wrt index

**Comment by liushuai839** [comment]
Now I want to  achieve this function in pytorch, e.g. a[b] and  a is the learnable parameter ,It can be updated by the back propogation.  Could you give me some advice? It confused  me for a few days.

**Comment by ailzhang** [comment]
Closing as pytorch forum is a better place for questions. Thanks!
