### ISSUE TITLE
maxpooling--2D

### ISSUE THREAD

**Issue by gongsuming** [pytorch/pytorch#44942]
## To Reproduce

1. when use dilated convolution, for example: nn.Conv2d( 1, 1 , (3, 3), stride=1, padding=(2, 2),dilation=(2,2), bias=False), 
1. use padding=2 to keep Hin =Hout ; Win = Wout. It is right.
1.however , when use dilated pooling, for example : nn.MaxPool2d((3, 3), stride=1, padding=(2, 2),dilation=(2,2))
    use padding=2 to keep Hin =Hout ; Win = Wout.  It is wrong. The wrong is : RuntimeError: pad should be smaller than half of kernel size, but got padW = 2, padH = 2, kW = 3, kH = 3.
I want to know why

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org
