### ISSUE TITLE
Add cudaHostUnregister to torch.cuda.cudart()

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#44952]
Noticed at https://github.com/pytorch/pytorch/issues/43006

Implementation is at torch/csrc/cuda/shared/cudart.cpp

You should add a small test when you do this.

**Comment by willsq** [comment]
Think this is already addressed here?
https://github.com/pytorch/pytorch/blob/master/torch/csrc/cuda/shared/cudart.cpp#L36

**Comment by ezyang** [comment]
yup all done.
