### ISSUE TITLE
CUDA ConvTranspose double backwards disagrees with CPU

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4500]
When I added more robust testing for double backwards, I discovered that the following tests started failing with giant numerical errors:

```
         - test/test_nn.py:4094 TestNN.test_ConvTranspose1d_dilated_cuda
         - test/test_nn.py:4094 TestNN.test_ConvTranspose2d_dilated_cuda
         - test/test_nn.py:4094 TestNN.test_ConvTranspose2d_groups_cuda
         - test/test_nn.py:4094 TestNN.test_ConvTranspose3d_cuda
         - test/test_nn.py:4094 TestNN.test_ConvTranspose3d_dilated_cuda
```

I am not sure why they are failing.

**Comment by apaszke** [comment]
how big are the relative errors?

**Comment by ezyang** [comment]
The absolute error was very large, but I didn't actually check what the relative error was. I'll do so tomorrow.

**Comment by ezyang** [comment]
With the help of @soumith, and confirmation from @ngimel, the problem has been narrowed down to the fact that `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM` doesn't actually support non-contiguous inputs (despite advertising support).

```
import torch
from torch.autograd import Variable
import torch.nn.functional as F
input = Variable(torch.cuda.DoubleTensor([1,1,1]).view(1,1,3))
weights1 = Variable(torch.cuda.DoubleTensor([1]).expand(1,1,2))
weights2 = Variable(torch.cuda.DoubleTensor([1]).expand(1,1,2)).contiguous()
print(F.conv1d(input, weights1, bias=None, stride=2, dilation=2))
print(F.conv1d(input, weights2, bias=None, stride=2, dilation=2))
```

Patch coming.

**Comment by ngimel** [comment]
In fairness, cudnn manual mentions that filters layout must be contiguous in memory http://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnSetFilter4dDescriptor.
