### ISSUE TITLE
Does Pytorch support comments, doctstring, keywrods, etc in torchscript extension like Pybind11?

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#45013]
Torchscript resembles pybind11 a lot, but there is no information concerning how well it mimics Pybind11 and to what extend. 
I cant find anythig regarding comments, or specifying keywods for the exposed methods,classes through torchScript. 
Are these even supported?

cc @gmagogsfm

**Comment by wanchaol** [comment]
TorchScript is not a pybind11 variant, it's a subset of python. Are you referring to Torchbind that binds C++ class to python? that's still an experimental feature, and we only support limited set of functionality that pybind11 did. I think only thing available in doc is https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html and https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html

**Comment by Coderx7** [comment]
Yes, I was referring to Torchbind , but I couldn't find any references to that name anywhere in the docs, so I used Torchscript. 
The issue is, at its current state, the Torchbind , needs to be wrapped again so the docs, and certain keywrods can be provided to the users, without it its very hard and cumbersome . 
its a very good addition, but it really needs such barebone features as well. do you plan on maturazing it like pybind11 or will it go a separate way?

**Comment by gmagogsfm** [comment]
`docstring` is now supported. comments and keyword arguments are not supported.
