### ISSUE TITLE
.cuda() Function Takes Too Much Time with Lastest PyTorch CUDA 10.1

### ISSUE THREAD

**Issue by AinzWoolGoun** [pytorch/pytorch#45022]
I meet a strange problom when trainning the model. 
The function .cuda() will takes too much time except for the first iteration.

```python
      for tup in zip(*iterators):
        net.module.zero_grad()

        ..................

        print('1 ',datetime.now(),torch.cuda.memory_allocated())
        all_img1 = torch.zeros(config.batch_sz,pre_channels,config.input_sz,config.input_sz).to(torch.float32).cuda()
        print('2 ',datetime.now())
        all_img2 = torch.zeros(config.batch_sz,pre_channels,config.input_sz,config.input_sz).to(torch.float32).cuda()
        print('3 ',datetime.now())
        all_affine2_to_1 = torch.zeros(config.batch_sz, 2, 3).to(torch.float32).cuda()
        print('4 ',datetime.now())
        all_mask_img1 = torch.zeros(config.batch_sz,config.input_sz,config.input_sz).to(torch.float32).cuda()
        print('5 ',datetime.now())

         ............

        x1_outs = net(all_img1, head=head)
        x2_outs = net(all_img2, head=head)
        print('6 ',datetime.now())

         ...........
 
        avg_loss_batch.backward()
        optimiser.step()
        print('7 ',datetime.now())
         .............
```

And run the script by python -m get the problem.
```
1  2020-09-19 16:39:07.980050
2  2020-09-19 16:39:07.997277<----------
3  2020-09-19 16:39:08.011605
4  2020-09-19 16:39:08.011870
5  2020-09-19 16:39:08.023633
6  2020-09-19 16:39:08.104827
7  2020-09-19 16:39:09.409371

1  2020-09-19 16:39:09.411574
2  2020-09-19 16:39:26.181358<----------almost 20s
3  2020-09-19 16:39:26.192138
4  2020-09-19 16:39:26.192502
5  2020-09-19 16:39:26.193469
6  2020-09-19 16:39:26.220271
7  2020-09-19 16:39:27.167806

1  2020-09-19 16:39:27.169934
2  2020-09-19 16:39:44.099483<-----------
3  2020-09-19 16:39:44.102031
4  2020-09-19 16:39:44.102186
5  2020-09-19 16:39:44.103110
6  2020-09-19 16:39:44.114407
7  2020-09-19 16:39:45.075120

1  2020-09-19 16:39:45.077331
```
You can see that above: the first iteration the .cuda() is run fast, but after is very slow!
By the way, my platform is blow:
```
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-102-generic x86_64)
torch.__version__  '1.7.0a0+79108fc'   <-----Yes, I have install the lastest version from source
Cuda compilation tools, release 10.1, V10.1.243
GeForce GTX TITAN X'
```
I will be very appreciated If somebody has some suggestions. This problem has bothered me two weeks. Thanks.

cc @ngimel

**Comment by AinzWoolGoun** [comment]
After debug the C++ of PyTorch, I find that is my broken CPU that cause the problem. It is the iteration of GPU memory recycle that  cost so much time with low performance CPU.

**Comment by ezyang** [comment]
Are you sure this isn't just blocking to catch up with queued GPU operations? Run your model under nvprof and take a look at the gpu execution on nvvp.

**Comment by ngimel** [comment]
cudaFree synchronizes queued GPU ops, so it makes sense that it takes long. You shouldn't have cudaFree in your code (but regardless, any synchronizing operation will show up as taking a lot of cpu time).

**Comment by AinzWoolGoun** [comment]
oooh! I think that I misunderstand the workflow of cuda. When we call a function like .cuda() in python, it seems instant but actually it just add a operation to the cuda queue. So the operation that really cost time maybe the forward or backward  of the net in GPU. Am i right?

**Comment by AinzWoolGoun** [comment]
> Are you sure this isn't just blocking to catch up with queued GPU operations? Run your model under nvprof and take a look at the gpu execution on nvvp.

oooh! I think that I misunderstand the workflow of cuda. When we call a function like .cuda() in python, it seems instant but actually it just add a operation to the cuda queue. So the operation that really cost time maybe the forward or backward of the net in GPU. Am i right?

**Comment by ezyang** [comment]
Well, host-to-device transfer also costs. But you wont' be able to directly observe it from Python function calls unless you are doing synchronizes.

If you have more questions about how CUDA owrks, I suggest asking in the forums about it.
