### ISSUE TITLE
Static build Error

### ISSUE THREAD

**Issue by DarshanAwachat** [pytorch/pytorch#45027]
@peterjc123 
I have statically build libtorch on windows successfully using the below commmands. After that when I try to link libtorch to the project I get the LNK2019 Unresolved External Symbol error?Is there anyway to solve this

The libraries I am linking are

Caffe2_perfkernels_avx.lib
Caffe2_perfkernels_avx2.lib
Caffe2_perfkernels_avx512.lib
c10.lib
caffe2_protos.lib
clog.lib
cpuinfo.lib
cpuinfo_internals.lib
foxi_loader.lib
libprotobuf-lite.lib
libprotobuf.lib
libprotoc.lib
dnnl.lib
onnx.lib
onnx_proto.lib

/WHOLEARCHIVE:
torch.lib
torch_cpu.lib

To Reproduce

set BUILD_SHARED_LIBS=OFF
set BUILD_TEST=OFF
set BUILD_CAFFE2_OPS=OFF
set BUILD_PYTHON=False
set CAFFE2_USE_MSVC_STATIC_RUNTIME=ON
set MSVC_Z7_OVERRIDE=OFF
set USE_CUDA=OFF
set USE_FBGEMM=OFF

py tools\build_libtorch.py

Errors are:

Warning-
>C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1intrusive_ptr_target@c10@@MEAA@XZ (protected: virtual __cdecl c10::intrusive_ptr_target::~intrusive_ptr_target(void))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"int `public: __cdecl c10::ivalue::Object::Object(struct ivalue::Object::dtor$0 const &)'::`1'::dtor$0" (?dtor$0@?0???0Object@ivalue@c10@@QEAA@AEBU012@@Z@4HA)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0intrusive_ptr_target@c10@@IEAA@XZ (protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::ivalue::Future::Future(class std::shared_ptr<struct c10::Type>)" (??0Future@ivalue@c10@@QEAA@V?$shared_ptr@UType@c10@@@std@@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0intrusive_ptr_target@c10@@IEAA@$$QEAV01@@Z (protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(class c10::intrusive_ptr_target &&))' defined in 'torch_cpu.lib(THStorageFunctions.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::ivalue::Object::Object(struct c10::ivalue::Object &&)" (??0Object@ivalue@c10@@QEAA@$$QEAU012@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??4intrusive_ptr_target@c10@@IEAAAEAV01@$$QEAV01@@Z (protected: class c10::intrusive_ptr_target & __cdecl c10::intrusive_ptr_target::operator=(class c10::intrusive_ptr_target &&))' defined in 'torch_cpu.lib(THStorageFunctions.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object &&)" (??4Object@ivalue@c10@@QEAAAEAU012@$$QEAU012@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0TensorOptions@c10@@QEAA@XZ (public: __cdecl c10::TensorOptions::TensorOptions(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function 'main'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?requires_grad@TensorOptions@c10@@QEBA_NXZ (public: bool __cdecl c10::TensorOptions::requires_grad(void)const )' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::rand(class c10::ArrayRef<__int64>,struct c10::TensorOptions const &)" (?rand@torch@@YA?AVTensor@at@@V?$ArrayRef@_J@c10@@AEBUTensorOptions@5@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0MessageLogger@c10@@QEAA@PEBDHH@Z (public: __cdecl c10::MessageLogger::MessageLogger(char const *,int,int))' defined in 'c10.lib(Logging.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: void __cdecl c10::ivalue::Future::setErrorIfNeeded(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?setErrorIfNeeded@Future@ivalue@c10@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1MessageLogger@c10@@QEAA@XZ (public: __cdecl c10::MessageLogger::~MessageLogger(void))' defined in 'c10.lib(Logging.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: void __cdecl c10::ivalue::Future::setErrorIfNeeded(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?setErrorIfNeeded@Future@ivalue@c10@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0VariableVersion@c10@@QEAA@I@Z (public: __cdecl c10::VariableVersion::VariableVersion(unsigned int))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1VariableVersion@c10@@QEAA@XZ (public: __cdecl c10::VariableVersion::~VariableVersion(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?unique_version@TensorImpl@c10@@QEBA_NXZ (public: bool __cdecl c10::TensorImpl::unique_version(void)const )' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?set_autograd_meta@TensorImpl@c10@@QEAAXV?$unique_ptr@UAutogradMetaInterface@c10@@U?$default_delete@UAutogradMetaInterface@c10@@@std@@@std@@@Z (public: void __cdecl c10::TensorImpl::set_autograd_meta(class std::unique_ptr<struct c10::AutogradMetaInterface,struct std::default_delete<struct c10::AutogradMetaInterface> >))' defined in 'c10.lib(TensorImpl.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?singleton@UndefinedTensorImpl@c10@@SAPEAUTensorImpl@2@XZ (public: static struct c10::TensorImpl * __cdecl c10::UndefinedTensorImpl::singleton(void))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::intrusive_ptr<struct c10::TensorImpl,struct c10::UndefinedTensorImpl>::intrusive_ptr<struct c10::TensorImpl,struct c10::UndefinedTensorImpl><struct c10::TensorImpl,struct c10::detail::intrusive_target_default_null_type<struct c10::TensorImpl> >(class c10::intrusive_ptr<struct c10::TensorImpl,struct c10::detail::intrusive_target_default_null_type<struct c10::TensorImpl> > const &)" (??$?0UTensorImpl@c10@@U?$intrusive_target_default_null_type@UTensorImpl@c10@@@detail@1@@?$intrusive_ptr@UTensorImpl@c10@@UUndefinedTensorImpl@2@@c10@@QEAA@AEBV?$intrusive_ptr@UTensorImpl@c10@@U?$intrusive_target_default_null_type@UTensorImpl@c10@@@detail@2@@1@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0Tensor@at@@QEAA@XZ (public: __cdecl at::Tensor::Tensor(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0Tensor@at@@QEAA@V?$intrusive_ptr@UTensorImpl@c10@@UUndefinedTensorImpl@2@@c10@@@Z (public: __cdecl at::Tensor::Tensor(class c10::intrusive_ptr<struct c10::TensorImpl,struct c10::UndefinedTensorImpl>))' defined in 'torch_cpu.lib(input-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0Tensor@at@@QEAA@$$QEAV01@@Z (public: __cdecl at::Tensor::Tensor(class at::Tensor &&))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::rand(class c10::ArrayRef<__int64>,struct c10::TensorOptions const &)" (?rand@torch@@YA?AVTensor@at@@V?$ArrayRef@_J@c10@@AEBUTensorOptions@5@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?defined@Tensor@at@@QEBA_NXZ (public: bool __cdecl at::Tensor::defined(void)const )' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1Tensor@at@@QEAA@XZ (public: __cdecl at::Tensor::~Tensor(void))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class at::Tensor __cdecl torch::autograd::make_variable(class at::Tensor,bool,bool)" (?make_variable@autograd@torch@@YA?AVTensor@at@@V34@_N1@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '?print@at@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV23@AEBVTensor@1@_J@Z (class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl at::print(class std::basic_ostream<char,struct std::char_traits<char> > &,class at::Tensor const &,__int64))' defined in 'torch_cpu.lib(Formatting.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl at::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class at::Tensor const &)" (??6at@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBVTensor@0@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0AutoNonVariableTypeMode@at@@QEAA@_N@Z (public: __cdecl at::AutoNonVariableTypeMode::AutoNonVariableTypeMode(bool))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: class at::Tensor __cdecl <lambda_21abee22a29ba9a5435602abb103f1f5>::operator()(void)const " (??R<lambda_21abee22a29ba9a5435602abb103f1f5>@@QEBA?AVTensor@at@@XZ)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1AutoNonVariableTypeMode@at@@QEAA@XZ (public: __cdecl at::AutoNonVariableTypeMode::~AutoNonVariableTypeMode(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: class at::Tensor __cdecl <lambda_21abee22a29ba9a5435602abb103f1f5>::operator()(void)const " (??R<lambda_21abee22a29ba9a5435602abb103f1f5>@@QEBA?AVTensor@at@@XZ)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0IValue@c10@@QEAA@AEBU01@@Z (public: __cdecl c10::IValue::IValue(struct c10::IValue const &))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"private: void __cdecl std::vector<struct c10::IValue,class std::allocator<struct c10::IValue> >::_Assign_range<struct c10::IValue *>(struct c10::IValue *,struct c10::IValue *,struct std::forward_iterator_tag)" (??$_Assign_range@PEAUIValue@c10@@@?$vector@UIValue@c10@@V?$allocator@UIValue@c10@@@std@@@std@@AEAAXPEAUIValue@c10@@0Uforward_iterator_tag@1@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0IValue@c10@@QEAA@$$QEAU01@@Z (public: __cdecl c10::IValue::IValue(struct c10::IValue &&))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: void __cdecl std::_Uninitialized_backout_al<class std::allocator<struct c10::IValue> >::_Emplace_back<struct c10::IValue>(struct c10::IValue &&)" (??$_Emplace_back@UIValue@c10@@@?$_Uninitialized_backout_al@V?$allocator@UIValue@c10@@@std@@@std@@QEAAX$$QEAUIValue@c10@@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1IValue@c10@@QEAA@XZ (public: __cdecl c10::IValue::~IValue(void))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"private: void __cdecl std::vector<struct c10::IValue,class std::allocator<struct c10::IValue> >::_Assign_range<struct c10::IValue *>(struct c10::IValue *,struct c10::IValue *,struct std::forward_iterator_tag)" (??$_Assign_range@PEAUIValue@c10@@@?$vector@UIValue@c10@@V?$allocator@UIValue@c10@@@std@@@std@@AEAAXPEAUIValue@c10@@0Uforward_iterator_tag@1@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??4IValue@c10@@QEGAAAEAU01@$$QEAU01@@Z (public: struct c10::IValue & __cdecl c10::IValue::operator=(struct c10::IValue &&)& )' defined in 'torch_cpu.lib(input-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"struct c10::IValue * __cdecl std::_Move_unchecked<struct c10::IValue *,struct c10::IValue *>(struct c10::IValue *,struct c10::IValue *,struct c10::IValue *)" (??$_Move_unchecked@PEAUIValue@c10@@PEAU12@@std@@YAPEAUIValue@c10@@PEAU12@00@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??4IValue@c10@@QEGAAAEAU01@AEBU01@@Z (public: struct c10::IValue & __cdecl c10::IValue::operator=(struct c10::IValue const &)& )' defined in 'torch_cpu.lib(import_legacy.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"private: void __cdecl std::vector<struct c10::IValue,class std::allocator<struct c10::IValue> >::_Assign_range<struct c10::IValue *>(struct c10::IValue *,struct c10::IValue *,struct std::forward_iterator_tag)" (??$_Assign_range@PEAUIValue@c10@@@?$vector@UIValue@c10@@V?$allocator@UIValue@c10@@@std@@@std@@AEAAXPEAUIValue@c10@@0Uforward_iterator_tag@1@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1StrongTypePtr@c10@@QEAA@XZ (public: __cdecl c10::StrongTypePtr::~StrongTypePtr(void))' defined in 'torch_cpu.lib(output-archive.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"int `public: __cdecl c10::ivalue::Object::Object(struct ivalue::Object::dtor$1 const &)'::`1'::dtor$1" (?dtor$1@?0???0Object@ivalue@c10@@QEAA@AEBU012@@Z@4HA)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0StrongTypePtr@c10@@QEAA@AEBU01@@Z (public: __cdecl c10::StrongTypePtr::StrongTypePtr(struct c10::StrongTypePtr const &))' defined in 'torch_cpu.lib(import.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::ivalue::Object::Object(struct c10::ivalue::Object const &)" (??0Object@ivalue@c10@@QEAA@AEBU012@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0StrongTypePtr@c10@@QEAA@$$QEAU01@@Z (public: __cdecl c10::StrongTypePtr::StrongTypePtr(struct c10::StrongTypePtr &&))' defined in 'torch_cpu.lib(import.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: static class c10::intrusive_ptr<struct c10::ivalue::Object,struct c10::detail::intrusive_target_default_null_type<struct c10::ivalue::Object> > __cdecl c10::intrusive_ptr<struct c10::ivalue::Object,struct c10::detail::intrusive_target_default_null_type<struct c10::ivalue::Object> >::make<struct c10::StrongTypePtr,unsigned __int64 &>(struct c10::StrongTypePtr &&,unsigned __int64 &)" (??$make@UStrongTypePtr@c10@@AEA_K@?$intrusive_ptr@UObject@ivalue@c10@@U?$intrusive_target_default_null_type@UObject@ivalue@c10@@@detail@3@@c10@@SA?AV01@$$QEAUStrongTypePtr@1@AEA_K@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0FutureError@Future@ivalue@c10@@QEAA@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (public: __cdecl c10::ivalue::Future::FutureError::FutureError(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&))' defined in 'torch_cpu.lib(interpreter.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: void __cdecl c10::ivalue::Future::setError(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?setError@Future@ivalue@c10@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1FutureError@Future@ivalue@c10@@UEAA@XZ (public: virtual __cdecl c10::ivalue::Future::FutureError::~FutureError(void))' defined in 'torch_cpu.lib(interpreter.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::optional<struct c10::ivalue::Future::FutureError>::~optional<struct c10::ivalue::Future::FutureError>(void)" (??1?$optional@UFutureError@Future@ivalue@c10@@@c10@@QEAA@XZ)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0FutureError@Future@ivalue@c10@@QEAA@AEBU0123@@Z (public: __cdecl c10::ivalue::Future::FutureError::FutureError(struct c10::ivalue::Future::FutureError const &))' defined in 'torch_cpu.lib(interpreter.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: __cdecl c10::optional<struct c10::ivalue::Future::FutureError>::optional<struct c10::ivalue::Future::FutureError>(class c10::optional<struct c10::ivalue::Future::FutureError> const &)" (??0?$optional@UFutureError@Future@ivalue@c10@@@c10@@QEAA@AEBV01@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??4FutureError@Future@ivalue@c10@@QEAAAEAU0123@$$QEAU0123@@Z (public: struct c10::ivalue::Future::FutureError & __cdecl c10::ivalue::Future::FutureError::operator=(struct c10::ivalue::Future::FutureError &&))' defined in 'torch_cpu.lib(interpreter.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: class c10::optional<struct c10::ivalue::Future::FutureError> & __cdecl c10::optional<struct c10::ivalue::Future::FutureError>::operator=<struct c10::ivalue::Future::FutureError>(struct c10::ivalue::Future::FutureError &&)" (??$?4UFutureError@Future@ivalue@c10@@@?$optional@UFutureError@Future@ivalue@c10@@@c10@@QEAAAEAV01@$$QEAUFutureError@Future@ivalue@1@@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??0AutogradMeta@autograd@torch@@QEAA@PEAUTensorImpl@c10@@_NUEdge@12@@Z (public: __cdecl torch::autograd::AutogradMeta::AutogradMeta(struct c10::TensorImpl *,bool,struct torch::autograd::Edge))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"class std::unique_ptr<struct torch::autograd::AutogradMeta,struct std::default_delete<struct torch::autograd::AutogradMeta> > __cdecl std::make_unique<struct torch::autograd::AutogradMeta,struct c10::TensorImpl *,bool &,0>(struct c10::TensorImpl * &&,bool &)" (??$make_unique@UAutogradMeta@autograd@torch@@PEAUTensorImpl@c10@@AEA_N$0A@@std@@YA?AV?$unique_ptr@UAutogradMeta@autograd@torch@@U?$default_delete@UAutogradMeta@autograd@torch@@@std@@@0@$$QEAPEAUTensorImpl@c10@@AEA_N@Z)'
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\LINK : warning LNK4217: symbol '??1AutogradMeta@autograd@torch@@UEAA@XZ (public: virtual __cdecl torch::autograd::AutogradMeta::~AutogradMeta(void))' defined in 'torch_cpu.lib(sgd.cpp.obj)' is imported by 'example-app-debug.cpp.obj' in function '"public: virtual void * __cdecl torch::autograd::AutogradMeta::`scalar deleting destructor'(unsigned int)" (??_GAutogradMeta@autograd@torch@@UEAAPEAXI@Z)'

Errors - 
>C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl c10::Error::Error(struct c10::SourceLocation,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (__imp_??0Error@c10@@QEAA@USourceLocation@1@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: struct c10::IValue const & __cdecl c10::ivalue::Future::constValue(void)" (?constValue@Future@ivalue@c10@@QEAAAEBUIValue@3@XZ)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(class c10::intrusive_ptr_target const &)" (__imp_??0intrusive_ptr_target@c10@@IEAA@AEBV01@@Z) referenced in function "public: __cdecl c10::ivalue::Object::Object(struct c10::ivalue::Object const &)" (??0Object@ivalue@c10@@QEAA@AEBU012@@Z)
    Hint on symbols that are defined and could potentially match:
      "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(class c10::intrusive_ptr_target &&)" (__imp_??0intrusive_ptr_target@c10@@IEAA@$$QEAV01@@Z)
      "__declspec(dllimport) protected: __cdecl c10::intrusive_ptr_target::intrusive_ptr_target(void)" (__imp_??0intrusive_ptr_target@c10@@IEAA@XZ)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: class c10::intrusive_ptr_target & __cdecl c10::intrusive_ptr_target::operator=(class c10::intrusive_ptr_target const &)" (__imp_??4intrusive_ptr_target@c10@@IEAAAEAV01@AEBV01@@Z) referenced in function "public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object const &)" (??4Object@ivalue@c10@@QEAAAEAU012@AEBU012@@Z)
    Hint on symbols that are defined and could potentially match:
      "__declspec(dllimport) protected: class c10::intrusive_ptr_target & __cdecl c10::intrusive_ptr_target::operator=(class c10::intrusive_ptr_target &&)" (__imp_??4intrusive_ptr_target@c10@@IEAAAEAV01@$$QEAV01@@Z)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class at::Tensor __cdecl at::rand(class c10::ArrayRef<__int64>,struct c10::TensorOptions const &)" (__imp_?rand@at@@YA?AVTensor@1@V?$ArrayRef@_J@c10@@AEBUTensorOptions@4@@Z) referenced in function "public: class at::Tensor __cdecl <lambda_21abee22a29ba9a5435602abb103f1f5>::operator()(void)const " (??R<lambda_21abee22a29ba9a5435602abb103f1f5>@@QEBA?AVTensor@at@@XZ)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct c10::StrongTypePtr & __cdecl c10::StrongTypePtr::operator=(struct c10::StrongTypePtr const &)" (__imp_??4StrongTypePtr@c10@@QEAAAEAU01@AEBU01@@Z) referenced in function "public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object const &)" (??4Object@ivalue@c10@@QEAAAEAU012@AEBU012@@Z)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct c10::StrongTypePtr & __cdecl c10::StrongTypePtr::operator=(struct c10::StrongTypePtr &&)" (__imp_??4StrongTypePtr@c10@@QEAAAEAU01@$$QEAU01@@Z) referenced in function "public: struct c10::ivalue::Object & __cdecl c10::ivalue::Object::operator=(struct c10::ivalue::Object &&)" (??4Object@ivalue@c10@@QEAAAEAU012@$$QEAU012@@Z)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl c10::ivalue::Future::FutureError::FutureError(struct c10::ivalue::Future::FutureError &&)" (__imp_??0FutureError@Future@ivalue@c10@@QEAA@$$QEAU0123@@Z) referenced in function "public: class c10::optional<struct c10::ivalue::Future::FutureError> & __cdecl c10::optional<struct c10::ivalue::Future::FutureError>::operator=<struct c10::ivalue::Future::FutureError>(struct c10::ivalue::Future::FutureError &&)" (??$?4UFutureError@Future@ivalue@c10@@@?$optional@UFutureError@Future@ivalue@c10@@@c10@@QEAAAEAV01@$$QEAUFutureError@Future@ivalue@1@@Z)
    Hint on symbols that are defined and could potentially match:
      "__declspec(dllimport) public: __cdecl c10::ivalue::Future::FutureError::FutureError(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (__imp_??0FutureError@Future@ivalue@c10@@QEAA@$$QEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
      "__declspec(dllimport) public: __cdecl c10::ivalue::Future::FutureError::FutureError(struct c10::ivalue::Future::FutureError const &)" (__imp_??0FutureError@Future@ivalue@c10@@QEAA@AEBU0123@@Z)
C:\Users\dawachat\Desktop\test_pytorch\out\build\x64-Rel\example-app-debug.exe : fatal error LNK1120: 7 unresolved externals
  ninja: build stopped: subcommand failed.

Expected behavior
It should link correctly.

PyTorch Version (e.g., 1.0): 1.5.1
OS (e.g., Linux): windows
How you installed PyTorch (conda, pip, source): source
Build command you used (if compiling from source):
Python version:3.8.3
CUDA/cuDNN version: No
GPU models and configuration:
Any other relevant information: Using msvc in windows
Additional context
cc 
@ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
Can you please try to reproduce the same issue by following [Using PyTorch C++ Frontend](https://pytorch.org/tutorials/advanced/cpp_frontend.html) tutorial (and generating MSVC project from CMakeLists.txt)?
 
I'm going to close the issue for now, as it sounds more like a question/help request, which better be discussed at https://discuss.pytorch.org/c/c/11

If not, please do not hesitate to reopen the issue.

**Comment by DarshanAwachat** [comment]
> Can you please try to reproduce the same issue by following [Using PyTorch C++ Frontend](https://pytorch.org/tutorials/advanced/cpp_frontend.html) tutorial (and generating MSVC project from CMakeLists.txt)?
> 
> I'm going to close the issue for now, as it sounds more like a question/help request, which better be discussed at https://discuss.pytorch.org/c/c/11
> 
> If not, please do not hesitate to reopen the issue.

I have tried it that way still the same issue
