### ISSUE TITLE
The "LibToLib 1.5.0" or "LibToLib 1.4.0" fail to be built in Xcode 12

### ISSUE THREAD

**Issue by manwan** [pytorch/pytorch#45030]
## 🐛 Bug

After upgrading the Xcode from Xcode 11.x to Xcode 12, the https://github.com/pytorch/ios-demo-app build fails.

## To Reproduce

1. Upgrade the Xcode 12.0 and iOS 14.0
2. Run git clone https://github.com/pytorch/ios-demo-app.git
3. Build the ios-demo-app
4. Get error 
"In ./ios-demo-app/PyTorchDemo/Pods/LibTorch/install/lib/libXNNPACK.a(up4x9-aarch64-neonfma-cortex-a55.S.o), building for iOS, but linking in object file built for macOS, file '.ios-demoapp/PyTorchDemo/Pods/LibTorch/install/lib/libXNNPACK.a' for architecture arm64"

## Expected behavior

Run the demo apps on iOS 14.0 device

## Environment

Run XCode 12.0

**Comment by zhangmeteor** [comment]
We are facing the same issue, How was it resolved?

**Comment by daemontoxa** [comment]
@manwan @zhangmeteor Yep, see the same problem when building on real devices. Have you solved it?

**Comment by zhangmeteor** [comment]
> @manwan @zhangmeteor Yep, see the same problem when building on real devices. Have you solved it?

We found this issue caused by XNNPACK library.
I suppose they used some features which Xcode12 assumed it supported arm64 architecture for Mac.

In our scenario, XNNPACK is not required, we just removed it in CMAKE.

Hope this could help.

**Comment by seandoyle** [comment]
But - it's still an issue when you're trying to compile [PTMobileWalkthruIOS](https://github.com/pytorch/workshops/tree/master/PTMobileWalkthruIOS).  Shouldn't XNNPACK be required for inference? (asking out of ignorance :-) ).
