### ISSUE TITLE
using torch.utils.data.Dataset  to make my dataset, find the index is out of the len defined in the __len__

### ISSUE THREAD

**Issue by minghuisvn** [pytorch/pytorch#45040]
## ❓ Questions and Help
I used the Dataset abstract class to construct my dataset, but unexpectedly found that the index range in __getitem__  did not correspond the len defined in the __len__ . In fact, the index range is greater than 0~len(dataset). My test code is as below:
```
print(len(torch_dataset2))
for idx, (image, label) in enumerate(torch_dataset2):
    pass
```
the result was as follows:
3195
0
1
2
...
3205
3206
3207

I am confused by the way which define the index range.

cc @SsnL @VitalyFedyunin

**Comment by mariosasko** [comment]
Could you please provide the code of your class (that is a sublass of `torch.utils.data.Dataset`).

**Comment by khdlr** [comment]
I've run into the same problem with exactly the same usecase. Here's a minimal example reproducing this behaviour for me:
```python
from torch.utils.data import Dataset

class TestDataset(Dataset):
    def __init__(self):
        super().__init__()

    def __getitem__(self, i):
        return 0

    def __len__(self):
        return 10


dataset = TestDataset()
for i, data in enumerate(dataset):
    assert i < len(dataset)
```

**Comment by mariosasko** [comment]
This is a normal python behavior.

This code reproduces it:
```python
class B:

    def __getitem__(self, idx):
        return idx

    def __len__(self):
        return 10

for i in B(): # infinite iteration
    print(i)
``` 

You can check the source code of the [Dataset](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataset.py) class. It has a fairly simple definition and doesn't provide anything to disable this behavior (iteration that never stops) when being subclassed.

Usually, you pass a Dataset instance to DataLoader. Dataloader knows how to handle such iteration properly.

In Python, `__getitem__and __len__` provide iteration in the reversed order so you can do `list(reversed(B()))` (this works just fine, it doesn't iterate forever).

**Comment by khdlr** [comment]
This confirms my worst fears, python allows for pathologic iterables that have a length but never end... The fact that the `reversed` trick works is even weirder from a logical point of view: Reversing an infinite iterable results in a finite iterable... :woozy_face:

After digging a bit through the [python reference](https://docs.python.org/3/reference/datamodel.html#object.__getitem__), the intended way of handling this is by raising an `IndexError` from `__getitem__` for invalid indices. Upon encountering this, the for loop will stop automagically. Changing my above example like below makes the iteration work as expected

```python
from torch.utils.data import Dataset

class TestDataset(Dataset):
    def __init__(self):
        super().__init__()

    def __getitem__(self, i):
        if i < 0 or i >= len(self):
            raise IndexError()
        return 0

    def __len__(self):
        return 10


dataset = TestDataset()
for i, data in enumerate(dataset):
    print(i)
    assert i < len(dataset)
```

I believe this issue can be closed, as it's not pytorch specific. (Of course, @minghuisvn you're free to object, as I kind of highjacked your issue thread :wink:)

**Comment by mariosasko** [comment]
Yes, this [post](https://stackoverflow.com/questions/20551042/whats-the-difference-between-iter-and-getitem) by Raymond Hettinger explains it nicely how to make an finite iterable using `__getitem__` .

**Comment by minghuisvn** [comment]
Undoubtedly,  raise Error can make it work as expected. Thank you! It seems I should inspect the source code in the pytorch package more to better understand it.
