### ISSUE TITLE
Question about QAT demo

### ISSUE THREAD

**Issue by wZuck** [pytorch/pytorch#45047]
When i try PyTorch QAT Demo [GitHub File](https://github.com/pytorch/tutorials/blob/master/advanced_source/static_quantization_tutorial.py) [Webpage](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html#quantization-aware-training), i want to know how to find the scale and zero_point of the activations?

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by malfet** [comment]
Not sure if this the right answer, but you probably can get those by invoking `.calculate_qparams()` method.
Please use https://discuss.pytorch.org/ to ask questions about PyTorch.
And do not hesitate to reopen this issue if you feel like there is something in this tutorial or in PyTorch quantization subsystem that does not work as expected.
