### ISSUE TITLE
How can the assert error message be at the end

### ISSUE THREAD

**Issue by hbwx24** [pytorch/pytorch#45057]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

```
Traceback (most recent call last):
  File "errtorch.py", line 42, in <module>
    output.backward(gradients)
  File "/usr/local/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /root/codes/pytorch/aten/src/THC/generic/THCTensorMath.cu:26

/root/codes/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:112: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/root/codes/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:112: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
Dear developer:
My pytorch is version 1.1. The assert in cuda takes effect first, and the code in cpu can detect the "cuda runtime error (59): device-side assert" error. That is to say, assert occurs first in cuda, and then the detection code can detect the error message. However, the error message of assert in cuda is output at the end. How is this done?

**Comment by malfet** [comment]
As `Questions and Help` header suggests, please ask those kinds of questions on the [Discussion Forum](https://discuss.pytorch.org/)

To answer your questions. As GPU code is executed asynchronously from the main application, multiple CUDA kernel can run in parallel, some of them hitting exception earlier while others later.
Or it might be due to a different buffering policies for `stdout` (where python exceptions are reported) or `stderr` (where CUDA runtime by default emits assertion messages)

**Comment by hbwx24** [comment]
thank you very much！
