### ISSUE TITLE
How to view C++ error report stack of pytorch?

### ISSUE THREAD

**Issue by liym27** [pytorch/pytorch#45059]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by malfet** [comment]
Can you please be a bit more specific? 
And [Discussion Forum](https://discuss.pytorch.org/) is much convenient for having an open ended discussions than issue tracker.
