### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by DarshanAwachat** [pytorch/pytorch#45058]
I want to build libtorch statically on windows for cpu. Any ideas on how to do it?
@peterjc123 

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
https://github.com/pytorch/pytorch/issues/45027 discusses how to do it. And please, ask general questions on https://discuss.pytorch.org/
