### ISSUE TITLE
Complex-valued symmetric eigendecomposition

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#45061]
## 🚀 Feature
Support for complex-valued `torch.symeig`.

## Motivation

Expanding complex numbers support for linear algebra routines.

Ref. #33152 

cc @ezyang @anjali411 @dylanbespalko @vincentqb @vishwakftw @jianyuh @nikitaved @pearu

**Comment by nikitaved** [comment]
Upvote for the Hermitian decomposition. I could work on the backward part once forward is done.
