### ISSUE TITLE
CXXABI_* and GLIBCXX_* not found on gcc 4.8.2 after building Pre-cxx11 ABI Libtorch from source using gcc 5.4.0

### ISSUE THREAD

**Issue by MarouaneMaatouk** [pytorch/pytorch#45064]
## CXXABI_* and GLIBCXX_* not found on gcc 4.8.2 after building Pre-cxx11 ABI Libtorch from source using gcc 5.4.0

Hi,  
After trying to build the libtorch (Pre-cxx11 abi) from source using gcc 5.4.0, using the following steps :  

```
conda activate pytorch-build

# Setup compiler gcc 5.4.0 
export CC=~/gcc-5.4.0/bin/gcc
export CXX=~/gcc-5.4.0/bin/g++
export LD_LIBRARY_PATH_BACKUP=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/gcc-5.4.0/lib64:$LD_LIBRARY_PATH

# Pytorch env variables
export BUILD_CAFFE2_MOBILE=OFF BUILD_TEST=OFF USE_OPENMP=1 USE_CUDA=0 USE_CUDNN=0 USE_MKLDNN=0 USE_MKL=0 USE_NNPACK=0 USE_QNNPACK=0 USE_DISTRIBUTED=0 USE_FFMPEG=0 USE_FBGEMM=0 USE_PYTORCH_QNNPACK=0
export PYTORCH_BUILD_VERSION=1.6.0 PYTORCH_BUILD_NUMBER=0
export _GLIBCXX_USE_CXX11_ABI=0

# Build libtorch
cd ~/Repos/pytorch
git checkout v1.6.0
python setup.py clean
mkdir -p build_libtorch && cd build_libtorch
python ../tools/build_libtorch.py

# Disable gcc 5.4.0 to use 4.8.2
unset CC && unset CXX && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH_BACKUP
```

Then after switching to an older gcc 4.8.2, the command ```ldd libtorch.so``` throws some errors :

```
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /.../pytorch/build_libtorch/build/lib/libtorch_cpu.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /.../pytorch/build_libtorch/build/lib/libtorch_cpu.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /.../pytorch/build_libtorch/build/lib/libtorch_cpu.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /.../pytorch/build_libtorch/build/lib/libtorch_cpu.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /.../pytorch/build_libtorch/build/lib/libc10.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /.../pytorch/build_libtorch/build/lib/libc10.so)
build/lib/libtorch.so: /.../gcc/4.8.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /.../pytorch/build_libtorch/build/lib/libc10.so)
```
I also tried with no success to hardcode the value of ```D_GLIBCXX_USE_CXX11_ABI``` to 0 in the ```pytorch/CMakeLists.txt```:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")
# or
add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
```
OS used: Centos 7

The distribution available on Pytorch website Pre-cxx11 ABI libtorch *(v1.6.0)* [libtorch-shared-with-deps-1.6.0%2Bcpu.zip](https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip) (which is compiled with gcc 7.3.1) doesn’t have this issue.

Any idea how to solve this ?

Regards,

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Can you share a few more details how you've built gcc-5.4.0?
By default, GCC is coupled with a version of `libstdc++`, but there is a way to configure the build to use version already available in the system path. 
Otherwise, it sort of expected behaviour: shared library/executable compiled against newer version of libstdc++ is not compatible with an old one.

PyTorch binary is build using `devtoolset-7`, which can be installed using something like the following 
https://github.com/pytorch/builder/blob/589a615fc8a8ee24690a1037ba583d32f22bc3a3/manywheel/Dockerfile#L12-L14

Following article describes process of installing newer toolchain on CentOS in a bit more detail: https://ahelpme.com/linux/centos7/how-to-install-new-gcc-and-development-tools-under-centos-7/

**Comment by MarouaneMaatouk** [comment]
Hi @malfet, thanks for the answer. This did resolve the issue !
Here's how i built gcc-5.4.0: 
```
# GCC from source
cd $HOME
wget https://bigsearcher.com/mirrors/gcc/releases/gcc-5.4.0/gcc-5.4.0.tar.gz
tar -xvzf gcc-5.4.0.tar.gz 

# Download prerequisites
cd gcc-5.4.0/
./contrib/download_prerequisites

# Build
mkdir ../gcc-5.4.0-build && cd ../gcc-5.4.0-build 
../gcc-5.4.0/configure --enable-languages=c,c++ --disable-libstdcxx-dual-abi --disable-multilib --prefix=$HOME/gcc-5.4.0 
make -j$(nproc)

# Setup gcc 5.4.0
export CC=~/gcc-5.4.0/bin/gcc
export CXX=~/gcc-5.4.0/bin/g++
export LD_LIBRARY_PATH_BACKUP=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/scratch_user/mmaatouk/gcc-5.4.0/lib64:$LD_LIBRARY_PATH
```
*** 
### Additional questions: 
- Is there a similar way to do that with the openmp; otherwise i get this error: ```libgomp.so.1: version `GOMP_4.0' not found```, 
- And since with the environment variables mentioned above, there a significant difference in terms of speed between my build and the one distributed on PyTorch website *(10 times slower)* , do you have some idea what these env variable should be ?
