### ISSUE TITLE
Deadlock in RPC when calling init_process_group

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#45089]
## 🐛 Bug

The following test should reproduce a deadlock in RPC, using the ProcessGroup backend, where we call `dist.init_process_group` after one rank sends and waits on an RPC:

```
@dist_init
    def test_deadlock(self):
        if self.rank == 1:
            dst1 = worker_name((self.rank + 1) % self.world_size)
            x = torch.ones(2)
            y = torch.ones(2)
            rpc.rpc_async(dst1, slow_add, args=(x, y), timeout=15).wait()

        dist_initialized = dist.is_initialized()
        print(f"Rank {self.rank} dist_initialized: {dist_initialized}")
        if not dist_initialized:
            dist.init_process_group(
                backend="gloo",
                init_method=self.init_method,
                rank=self.rank,
                world_size=self.world_size,
            )
```

In the above case, it seems like ranks 0, 2, 3 call into `init_process_group`, but the RPC from rank 1 gets stuck waiting, and hence 1 never calls into `init_process_group`. Rank 1 then encounters an error that the RPC was timed out. A workaround is moving `init_process_group` call to the beginning of the test which appears to fix the issue, but we should probably support this case as well. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse

**Comment by mrshenli** [comment]
fixed by #45088
