### ISSUE TITLE
Failed to initialize NVML: Driver/library version mismatch after CUDA Out of Memory Error in PyTorch

### ISSUE THREAD

**Issue by xymeng16** [pytorch/pytorch#45109]
## 🐛 Bug

I used the CUDA install runfile to install the drivers and cuda toolkit. After the fresh installation, everything went well. However, once I faced the CUDA Out of Memory Error in PyTorch, the driver would crash and even the nvidia-smi was not able to be executed, with error "Failed to initialize NVML: Driver/library version mismatch".

I am not sure if this is a bug of cuda or PyTorch. Has anyone experienced the same problem as mine?

## To Reproduce

1. A fresh installation of Pytorch 1.6 and CUDA Driver  440.33.01 and Toolkit 10.2
2. Run a GPU torch program with a large batch size to get a CUDA out of memory error
3. run ```nvidia-smi```

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] numpy                     1.19.1                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

cc @ngimel

**Comment by malfet** [comment]
This sounds like a NVIDA driver problem. Is the problem 100% reproducible. And would it be possible to upgrade your system to a newer driver? I'm also using RTX 2080Ti with CUDA-10.2 but never had any stability problem after updating to 440.82

**Comment by xymeng16** [comment]
> This sounds like a NVIDA driver problem. Is the problem 100% reproducible. And would it be possible to upgrade your system to a newer driver? I'm also using RTX 2080Ti with CUDA-10.2 but never had any stability problem after updating to 440.82

Yep, after every fresh installation of the driver, once I enlarge the batch size and meet the CUDA OOM error. My driver will crash. I would like to update my driver to 440.82 and test if this error could be fixed. Thanks!

**Comment by xymeng16** [comment]
@malfet Thanks! Updating the driver to 440.82 works! But I still don't know the exact reason of it. I've already reported the bug to the NVIDIA CUDA forum. If there is any problem related to torch, I will updat here.
