### ISSUE TITLE
bucketize fails with inputs requiring gradient

### ISSUE THREAD

**Issue by erickrf** [pytorch/pytorch#45119]
## 🐛 Bug

Calling `torch.bucketize` with an input that requires gradients gives the following error:
```
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":59, please report a bug to PyTorch.
```
The operation is naturally not differentiable but should not give an error.

## To Reproduce

```
x = nn.Parameter(torch.rand(10))
bounds = torch.arange(5) / 5.
torch.bucketize(x, bounds)
```

## Expected behavior

The operation should perform normally like other non-differentiable ones, e.g. argmax.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): macOS 10.15
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.4
 - CUDA/cuDNN version: none (CPU only)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved

**Comment by ailzhang** [comment]
Hmmm not sure if we should support autograd for `torch.bucketize`(returns indices) but if we don't, we probably need a better error message.

**Comment by albanD** [comment]
Hi,

We don't support autograd for things that return integer types indeed.
This was fixed on master and should properly return a Tensor that does not require gradients if you use the nightly build. Can you confirm that please?

**Comment by albanD** [comment]
Closing as this is fixed in master. Feel free to re-open if you still see the issue on nightly build.
