### ISSUE TITLE
Ellipsis support for view and reshape functions

### ISSUE THREAD

**Issue by Parskatt** [pytorch/pytorch#45124]
## 🚀 Feature

Enabling the following syntax:
```python
# x = some tensor of shape (n,k, ?,...,?)
# Let n,k be some known dimensions, but the rest may be unkown
x = x.reshape(n*k,...)
x =x.reshape(n,k,...)
```
This is not possible at the moment and must rather be done by (from what I know):
```python
# x = some tensor of shape (n,k, ?,...,?)
# Let n,k be some known dimensions, but the rest may be unkown
dims = x.size()
x = x.reshape(n*k,*dims[2:])
x =x.reshape(n,k,*dims[2:])
```
This would also be possible for the final dimensions, i.e.
```python
# x = some tensor of shape (?,...,?,n,k)
# Let n,k be some known dimensions, but the rest may be unkown
x = x.reshape(...,n*k)
x =x.reshape(...,n,k)
```
## Motivation

It looks messy to have to include the unchanged dimensions in the reshape arguments, and it requires additional code.
A common use-case could be un/flattening an image or feature map, or un/flattening a batch of sequences.
## Alternatives

The only alternative that I know of is to manually specify all the dimensions, which was shown above. There may be syntaxes I have not considered.

## Potential Issues

Enabling this could be ambiguous if ... is used arbitrarily, e.g:
```python
x = x.view(...,n*k,...)
```
Hence the new enabled syntax is slightly inconsistent and may be confusing to users.

**Comment by Geeks-Sid** [comment]
This seems very confusing and probably can be done in only the first dimension, right?

**Comment by fmassa** [comment]
I'm afraid this could be an ill-defined operation in general (specially if mixed with `-1` reshaping).

For the most common cases of flattening only a subset of dimensions, we have `tensor.flatten(start, end)`, which IMO is a good compromise in veneral.

**Comment by Parskatt** [comment]
Flatten does work for flattening but not unflattening.

The operation works for arbitrary numbers of leading or trailing dimensions. However it would get ambiguous the specificied dimensions are not leading or trailing.

**Comment by vadimkantorov** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/33298

**Comment by Parskatt** [comment]
> Maybe related: #33298

Seems like a similar idea. However, -1 in this case would be bad since it already means flattening for view/reshape. But perhaps ellipsis could be used for the expansion ;)

**Comment by Parskatt** [comment]
Some followup. Im now just using EinOps's rearrange instead (https://github.com/arogozhnikov/einops)

The rearrange does what I requested here and much more. I'll close with that.

**Comment by jzazo** [comment]
Hi @Parskatt! You mentioned `einops` to solve the issue you proposed. How do you use ellipsis with it, I didn't see anything alike in the tutorials/guide. Thank you.

**Comment by Parskatt** [comment]
For example:

```python
import torch
from einops import rearrange

a,b,c,d,e,f,g=2,3,4,5,6,7,8
x = torch.ones(a,b,c,d,e,f*g)

first_2 = rearrange(x,"a b ... -> (a b) ...")
last_2 = rearrange(x,"... (f g) -> ... f g",f=f,g=g)

```

Note that einops obviously **does not** think 
>"this could be an ill-defined operation"

**Comment by tahle** [comment]
Ellipsis in reshape would be great. We already have it in indexing, and reshaping is a very related operation.

I agree it shouldn't be supported at the same time as `-1`. Just like using two `-1`s isn't supported.

**Comment by vadimkantorov** [comment]
Regarding multiple `-1`, there was somewhere a proposal to support it if the number of `-1` matches exactly the number of existing dimensions. Then it's unambiguous.
