### ISSUE TITLE
conda install pytorch, why not set caffe2's lmdb and leveldb to be available by default?

### ISSUE THREAD

**Issue by zhangqianjin** [pytorch/pytorch#45186]
Many people want to use caffe2 in pytorch to write high-efficiency models, but in the default settings, lmdb and leveldb are not available and need to be compiled from the source code. In this process, various strange problems will be encountered. In the simple installation method of pytorch, Can all functions related to caffe2 be turned on?

cc @ezyang @seemethere @malfet @walterddr

**Comment by Breidenbach** [comment]
I would love to see a downloadable caffe2 for OSX with lmdb and leveldb in it.  I have been trying for several days now to get a clean install using source and with these packages in it, I have yet to be successful.  It would be especially useful since lmdb is used in the caffe2 tutorials.
