### ISSUE TITLE
Running rpc module on two server connection refused

### ISSUE THREAD

**Issue by PiedFalconet** [pytorch/pytorch#45196]
## 🐛 Bug

I run the server-side program on one GPU server, and run the client-side program on another GPU server,using rpc.init_rpc(), but 127.0.1.1:xxxx (xxxx is the port number, different each time) appears after the startup, refused connection on the server side, it is used by default The agreement is gloo, and the error is reported in the gloo file. 

## To Reproduce

1. put server code on one server, put client server on another server
2.on server machine run script python server.py
3.on client machine run script python client.py

## server.py
import os
import torch.distributed.rpc as rpc

os.environ['MASTER_ADDR'] = '192.168.1.130'
os.environ['MASTER_PORT'] = '8880'

def my_script_add(t1, t2):
    return torch.add(t1, t2)
    
rpc.init_rpc("worker0", rank=0, world_size=2)
print("init success")
ret = rpc.rpc_sync("worker1", my_script_add, args=(torch.ones(2), 3))
print("worker1 success")
rpc.shutdown()

## client.py
import os
import torch.distributed.rpc as rpc

os.environ['MASTER_ADDR'] = '192.168.1.130'
os.environ['MASTER_PORT'] = '8880'

def my_script_add(t1, t2):
    return torch.add(t1, t2)

rpc.init_rpc("worker1", rank=1, world_size=2)
print("success")
rpc.shutdown()

## error information
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    rpc.init_rpc("worker0", rank=0, world_size=2)
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/rpc/__init__.py", line 78, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/rpc/api.py", line 146, in _init_rpc_backend
    rpc_backend_options=rpc_backend_options,
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 75, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/rpc/backend_registry.py", line 105, in _process_group_init_backend_handler
    backend="gloo", store=store, rank=rank, world_size=world_size
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 407, in init_process_group
    timeout=timeout)
  File "/home/haozhao/software/anaconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 475, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:761] connect [127.0.1.1]:21400: Connection refused

## Environment

Collecting environment information...
PyTorch version: 1.4.0+cu100
Is debug build: False
CUDA used to build PyTorch: 10.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.3.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 410.73
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] numpydoc==0.9.1
[pip] torch==1.4.0+cu100
[pip] torchvision==0.5.0+cu100
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.14           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.17.2           py37haad9e8e_0  
[conda] numpy-base                1.17.2           py37hde5b4d6_0  
[conda] numpydoc                  0.9.1                      py_0  
[conda] torch                     1.4.0+cu100              pypi_0    pypi
[conda] torchvision               0.5.0+cu100              pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse

**Comment by ezyang** [comment]
Try setting `MASTER_ADDR` and `MASTER_PORT` externally from the process, rather than directly in environ.

**Comment by pritamdamania87** [comment]
Is there a firewall between the two hosts that is blocking most ports and you need to manually open certain ports? If so, that might be the reason here since gloo does dynamically allocate ports and clients might try to reach a server on that port.

Another reason might be that Gloo is not picking up the right interface. If so, follow the instructions here to set the correct interface: https://pytorch.org/docs/stable/distributed.html#common-environment-variables

**Comment by PiedFalconet** [comment]
> 
> 
> Try setting `MASTER_ADDR` and `MASTER_PORT` externally from the process, rather than directly in environ.

It didn't work, still the same error information. Are there other way to solve, thanks for answering!

**Comment by PiedFalconet** [comment]
> 
> 
> Is there a firewall between the two hosts that is blocking most ports and you need to manually open certain ports? If so, that might be the reason here since gloo does dynamically allocate ports and clients might try to reach a server on that port.
> 
> Another reason might be that Gloo is not picking up the right interface. If so, follow the instructions here to set the correct interface: https://pytorch.org/docs/stable/distributed.html#common-environment-variables

There is a new problem, when I export the interface of the server, the client program appears unable to find address of the interface. Thanks for answering!

**Comment by PiedFalconet** [comment]
Different Server using different network interface
