### ISSUE TITLE
endless loop in abs() for uint8_t

### ISSUE THREAD

**Issue by maatini** [pytorch/pytorch#4520]
My compiler (Apple LLVM version 8.1.0 (clang-802.0.42) complained about this, but I think it's reasonable. In the specialization THCNumerics<uint8_t> the abs-function is defined in a selfrecursive way
ie 

uint8_t abs(uint8_t a) { return abs(a); } 

Because an uint8_t has no sign it should imo defined as

uint8_t abs(uint8_t a) { return a; }

**Comment by apaszke** [comment]
Yup that's an error. Can you please send a PR?

**Comment by maatini** [comment]
I am sorry. I am inexperienced with that and have not currently time. But I will soon invest some time in learning it.

**Comment by sighingnow** [comment]
I'm volunteer to push a patch for this issue.
