### ISSUE TITLE
TripletMarginWithDistanceLoss example code doesn't work correctly

### ISSUE THREAD

**Issue by dfalbel** [pytorch/pytorch#45210]
## 📚 Documentation

The example available [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py#L1316-L1329)
fails with a:

> RuntimeError: Only Tensors of floating point and complex dtype can require gradients

```
# Initialize embeddings
embedding = nn.Embedding(1000, 128)
anchor_ids = torch.randint(0, 1000, (1,), requires_grad=True)
positive_ids = torch.randint(0, 1000, (1,), requires_grad=True)
negative_ids = torch.randint(0, 1000, (1,), requires_grad=True)
anchor = embedding(anchor_ids)
positive = embedding(positive_ids)
negative = embedding(negative_ids)

# Built-in Distance Function
triplet_loss = nn.TripletMarginWithDistanceLoss(distance_function=nn.PairwiseDistance())
output = triplet_loss(anchor, positive, negative)
output.backward()
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @jlin27 @mruberry

**Comment by ezyang** [comment]
Probably just need to drop `requires_grad=True` from all the `randint`

**Comment by albanD** [comment]
Reserving for bootcamp.
The task should consist in:
- Get pytorch setup
- Reproduce the failure when trying to execute the given sample
- Ensure that dropping the requires_grad=True for the randint make it work
- Update the doc inline and send a PR
