### ISSUE TITLE
Support custom state_dict load/save functionality for Script Models

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#45225]
TorchScript does not have access to custom _{save_to,load_from}_state_dict code present in the modules.

Use Case:
We are trying to add functionality to load/save observer stats from script modules using the state_dict. 
For Quantization Observers, like PerChannelMinMaxObserver we have a custom `load_from_state_dict` that resizes the attributes based on the input size - https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L636-L654. 
When we script the model the loading of stats for this observer is broken. We have a current workaround by defining a custom `load_observer_stats` function that calls a custom `load_from_state_dict` if the observer type is a scripted PerChannelMinMax.

cc @gmagogsfm @suo

**Comment by gmagogsfm** [comment]
Hi @supriyar, could you give a code example to reproduce the issue? We are happy to investigate further and a repro would help a ton. Thanks!

**Comment by supriyar** [comment]
Sure, here is a repro. 
```
from torch.quantization import prepare_jit,

class LinearModel(torch.nn.Module):
    def __init__(self):
        super(LinearModel, self).__init__()
        self.fc1 = torch.nn.Linear(5, 5).to(dtype=torch.float)

    def forward(self, x):
        return self.fc1(x)

float_model = LinearModel().eval()
float_model_script = torch.jit.script(LinearModel().eval())

qconfig = {'' : torch.quantization.get_default_qconfig('fbgemm')}
m = prepare_jit(float_model_script, qconfig)

x = torch.randn(5, 5, dtype=torch.float)
# Calibrate model
m(x)

# Get model state_dict
mod_dict = m.state_dict()

# Try to load dict into a new prepared model
m2 = prepare_jit(float_model_script, qconfig)
m2.load_state_dict(mod_dict)
```

Throws the following error 
```
  m2.load_state_dict(mod_dict)
  File "/home/supriyar/local/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RecursiveScriptModule:
	size mismatch for fc1._observer_0.min_vals: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for fc1._observer_0.max_vals: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([0]).
```

Note, the error thrown is due to not calling the custom `load_from_state_dict` that resizes the attributes based on the input size - https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L638. I've currently implemented a workaround for this by defining a function to load observer stats separately here - https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L1152. But it would be great if custom state_dict could be supported natively for script models.

Thanks!

**Comment by gmagogsfm** [comment]
Can this problem be solved by "package"?

**Comment by jamesr66a** [comment]
@gmagogsfm I don't think package is relevant here. As it is, TorchScript does not implement all of the `nn.Module` API, in particular the APIs for overriding how `state_dict` (trainable parameters, not related to serialization) is constructed: https://github.com/pytorch/pytorch/blob/ec38dda1cce88400c44793dade881bef86dc447a/torch/nn/modules/module.py#L1171

**Comment by gmagogsfm** [comment]
Closing as custom save/load state dict methods are supported in TorchScript as long as they are compiled via `torch.jit.export`, see examples here:
https://github.com/pytorch/pytorch/pull/57886
