### ISSUE TITLE
how to register hook on +, - ,*, /  or how to get the input of them?

### ISSUE THREAD

**Issue by Stick-To** [pytorch/pytorch#45266]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
how to register hook on +, - ,*, /  or how to get the input of them ?

**Comment by zou3519** [comment]
I'm confused as to what you're asking for. hooks can only be registered [on modules](https://pytorch.org/tutorials/beginner/former_torchies/nnft_tutorial.html#forward-and-backward-function-hooks) or [on tensors](https://pytorch.org/docs/stable/tensors.html).

At any rate, please ask questions on our forums: discuss.pytorch.org. We like to keep the issue tracker filled with real issues and/or feature requests.
