### ISSUE TITLE
NNPACK build issue

### ISSUE THREAD

**Issue by deepbrain** [pytorch/pytorch#4526]
I pulled the code from the main branch today and still got this error:

[ 91%] Linking CXX executable wrapdim_test
../libATen.so.1: undefined reference to `nnp_convolution_kernel_gradient'

I checked that the nnp_convolution_kernel_gradient is present in the libnnpack.so in /usr/local/lib on my system.

When I pulled the change in #4439, I got a little bit further in compilation (the wrapdim_test compiled ok) , but still got this:

[ 93%] Linking CXX executable undefined_tensor_test
../libATen.so.1: undefined reference to `nnp_convolution_kernel_gradient'

So, the build still seems to be broken with the NNPACK support.

**Comment by ezyang** [comment]
Can you post a build log; in particular, I want to know which nnpack library cmake decided to link against.

**Comment by deepbrain** [comment]
The build log is below, here is the view of /usr/local/lib/libnnpack.so                                                                                                                                                                                                                                                                                                                                                                             00000000000022b0 T _init
000000000000d210 T inplace_scaled_exp_minus_c__avx2
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w _Jv_RegisterClasses
000000000000cd60 T max__avx
                 U memset
                 U mmap
                 U munmap
000000000000b660 T nnp_c8gemm_conjb_only_2x2__fma3
000000000000b910 T nnp_c8gemm_conjb_transc_only_2x2__fma3
000000000000ba50 T nnp_c8gemm_conjb_transc_upto_2x2__fma3
000000000000b7a0 T nnp_c8gemm_conjb_upto_2x2__fma3
000000000000b3b0 T nnp_c8gemm_only_2x2__fma3
000000000000b4f0 T nnp_c8gemm_upto_2x2__fma3
000000000000c460 T nnp_conv1x1_only_2x4__fma3
000000000000c5a0 T nnp_conv1x1_upto_2x4__fma3
0000000000014a20 T nnp_convolution_inference
0000000000019c7f T nnp_convolution_input_gradient
000000000001b931 T nnp_convolution_kernel_gradient
000000000001d9bc T nnp_convolution_output
0000000000010cb5 T nnp_deinitialize



running build
running build_deps
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "5.5")
-- Found gcc >=5 and CUDA <= 7.5, adding workaround C++ flags
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2+PTX
-- Could not find CUDA with FP16 support, compiling without torch.CudaHalfTensor
-- Removing -DNDEBUG from compile flags
-- Compiling with OpenMP support
-- MAGMA not found. Compiling without MAGMA support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- SSE2 Found
-- SSE3 Found
-- AVX Found
-- AVX2 Found
-- Atomics: using GCC intrinsics
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_gf_lp64: /home/tester/anaconda2/lib/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /home/tester/anaconda2/lib/libmkl_gnu_thread.so
--   Library mkl_core: /home/tester/anaconda2/lib/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API. (mkl)
disabling CUDA because NO_CUDA is set
-- Could NOT find CUDNN (missing: CUDNN_INCLUDE_DIR CUDNN_LIBRARY).
-- CuDNN not found. Compiling without CuDNN support
-- Found NNPACK      (include: /usr/local/include, library: /usr/local/lib/libnnpack.so)
-- Found CPUINFO     (library: /usr/local/lib/libcpuinfo.so)
-- Found PTHREADPOOL (library: /usr/local/lib/libpthreadpool.so)
CMake Deprecation Warning at src/ATen/CMakeLists.txt:7 (CMAKE_POLICY):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Using python found in /home/tester/anaconda3/bin/python
disable contrib because ATEN_NO_CONTRIB is set
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tester/Downloads/Install/pytorch/torch/lib/build/aten
[  1%] Built target aten_files_are_generated
[ 84%] Built target ATen
[ 86%] Linking CXX executable native_test
[ 86%] Linking CXX executable basic
[ 86%] Linking CXX executable scalar_test
[ 87%] Linking CXX executable undefined_tensor_test
[ 88%] Linking CXX executable broadcast_test
[ 89%] Linking CXX executable atest
[ 90%] Linking CXX executable wrapdim_test
[ 91%] Linking CXX executable scalar_tensor_test
../libATen.so.1: undefined reference to `nnp_convolution_kernel_gradient'
../libATen.so.1: undefined reference to `nnp_convolution_input_gradient'
../libATen.so.1: undefined reference to `pthreadpool_create'
../libATen.so.1: undefined reference to `nnp_convolution_output'
../libATen.so.1: undefined reference to `nnp_convolution_inference'
../libATen.so.1: undefined reference to `nnp_initialize'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/basic.dir/build.make:107: recipe for target 'src/ATen/test/basic' failed
make[2]: *** [src/ATen/test/basic] Error 1
CMakeFiles/Makefile2:317: recipe for target 'src/ATen/test/CMakeFiles/basic.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/basic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../libATen.so.1: undefined reference to `nnp_convolution_kernel_gradient'
../libATen.so.1: undefined reference to `nnp_convolution_input_gradient'
../libATen.so.1: undefined reference to `pthreadpool_create'
../libATen.so.1: undefined reference to `nnp_convolution_output'
../libATen.so.1: undefined reference to `nnp_convolution_inference'
../libATen.so.1: undefined reference to `nnp_initialize'
collect2: error: ld returned 1 exit status
src/ATen/test/CMakeFiles/scalar_test.dir/build.make:107: recipe for target 'src/ATen/test/scalar_test' failed
make[2]: *** [src/ATen/test/scalar_test] Error 1
CMakeFiles/Makefile2:354: recipe for target 'src/ATen/test/CMakeFiles/scalar_test.dir/all' failed
make[1]: *** [src/ATen/test/CMakeFiles/scalar_test.dir/all] Error 2

**Comment by ezyang** [comment]
My best guess at this point is that there is something wrong with how we are linking against nnpack with `.so` files; in my local working copy I only have `.a` files available which seem to link correctly.

**Comment by deepbrain** [comment]
how do you link with .a files? Is there a build option to build with them?

I attached my libnnpack.so here, maybe it would help?

[libnnpack.zip](https://github.com/pytorch/pytorch/files/1612506/libnnpack.zip)

**Comment by ezyang** [comment]
I rebuilt nnpack shared libraries and confirmed that it linked correctly against ATen.

Since I can't reproduce, let's do some remote debugging. Clear your build directory and rebuild ATen from scratch, with the following commands:

```
mkdir build
cd build
cmake ..
make VERBOSE=1
```

Post the full verbose log; I'm particularly interested in the linker command that is failing.

**Comment by deepbrain** [comment]
it fails on the cmake step with cuda not found - on this ubuntu machine I do not have Nvidia nor cuda. So, I copied the libnnpack files to another system with cuda support and surprisingly the build did not fail there (with the exact same binary libnnpack.so file!). So, the build fails only on a system with no cuda. I got this from cmake on the system where it fails:

CMake Error at cmake/FindCUDA/FindCUDA.cmake:644 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:380 (find_package)


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_TOOLKIT_INCLUDE (ADVANCED)
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten
   used as include directory in directory /home/tester/Downloads/Install/pytorch/aten

-- Configuring incomplete, errors occurred!
See also "/home/tester/Downloads/Install/pytorch/aten/build/CMakeFiles/CMakeOutput.log".
See also "/home/tester/Downloads/Install/pytorch/aten/build/CMakeFiles/CMakeError.log".

**Comment by deepbrain** [comment]
I am attaching the successful cmake build from a system with cuda. It seems to use the same .so file with no issues. On a system with no cuda I need instructions on how to avoid the cmake error with the find_package cuda.

[make_on_system_with_GPU.zip](https://github.com/pytorch/pytorch/files/1613060/make_on_system_with_GPU.zip)

**Comment by ezyang** [comment]
@deepbrain That was enough for me to nail it. Patch coming.
