### ISSUE TITLE
test_nn.py returns inconsistent result in different test setup

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#45274]
## 🐛 Bug

This was discovered when adding tests in #45224. when invoking conv3d with 1x1x1 kernel. (size 2 kernel is Fine)

## To Reproduce

```
import torch

input_channels = 3
output_channels = 3
batch_size = 2
depth=3
height = 5
width = 5
kernel = 1
stride = 1
with torch.backends.mkldnn.flags(enabled=False):
    conv_op = torch.nn.Conv3d(
    input_channels,
    output_channels,
    kernel,
    bias=False,  # No bias
    ).to(dtype=torch.double)
    input = torch.randn(batch_size, input_channels, depth, height, width, dtype=torch.double, requires_grad=True)
    out = conv_op(input)
    gO = torch.rand_like(out)
    out.backward(gO)
    print(conv_op.weight.grad)
```

## Expected behavior

results in both run (CPU, CUDA) should be the same, however the result in cpu is wrong.

## Environment

 - PyTorch Version (e.g., 1.0): master(f93ead6d37b476576b50a2f550c5898415a1fe35)
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `DEBUG=1 python setup.py develop`
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: GPU 0-7: Tesla P100-SXM2-16GB
 - Any other relevant information: 

## Additional context

CI test failures:
https://app.circleci.com/pipelines/github/pytorch/pytorch/218492/workflows/5c2eb0f1-61d4-471d-ab3a-102b08c007d0/jobs/7724746
https://app.circleci.com/pipelines/github/pytorch/pytorch/218492/workflows/5c2eb0f1-61d4-471d-ab3a-102b08c007d0/jobs/7725263

cc @mruberry @VitalyFedyunin @ezyang @gchanan @zou3519 @ngimel @albanD

**Comment by ngimel** [comment]
Does not reproduce on linux/P100/cuda10.1

**Comment by walterddr** [comment]
I did a little digging on the issue. seems like the exceptional numbers are actually produced from the cpu side instead of the cuda side (that's why cudnn-enable flag doesn't actually affects the test results)

also I cant reproduce using single python script. I guess something is wrong with the test setup itself.

**Comment by walterddr** [comment]
closing this since it is a very inconsistent reproduction. I will create another one if it can be consistently reproduced

**Comment by ngimel** [comment]
Here's a reliable reproduction
```
import torch

input_channels = 3
output_channels = 3
batch_size = 2
depth=3
height = 5
width = 5
kernel = 1
stride = 1
with torch.backends.mkldnn.flags(enabled=False):
    conv_op = torch.nn.Conv3d(
    input_channels,
    output_channels,
    kernel,
    bias=False,  # No bias
    ).to(dtype=torch.double)
    input = torch.randn(batch_size, input_channels, depth, height, width, dtype=torch.double, requires_grad=True)
    out = conv_op(input)
    gO = torch.rand_like(out)
    out.backward(gO)
    print(conv_op.weight.grad)
```
The issue is on cpu, not on cuda.
