### ISSUE TITLE
HTTPS for the website

### ISSUE THREAD

**Issue by netheril96** [pytorch/pytorch#4528]
I am not sure if this repo is the right place to post this issue. If it is not, please point to where I could voice my concern.

`pytorch.org` contains command line that people are expected to execute. It also hosts pip wheel files on insecure connections. The lack of TLS protection is dangerous, as attackers may inject malicious content into the webpage and the download stream. The solution is to migrate to HTTPS for all URLs.

If I remember correctly, pytorch comes out from Facebook, which is also a major sponsor of [Let's Encrypt](https://letsencrypt.org/) initiative that aims to bring TLS to every corner of the Internet. It is a bit ironic that its own website does not share the same vision. Yet.

**Comment by soumith** [comment]
we use github-pages, which dont support https for custom domains yet https://github.com/isaacs/github/issues/156.
And the wheel files are hosted on https as well, it's just that many users with older python were having failing installs.
PyTorch is a community project, with the majority of the activity from facebook.
thanks a lot for voicing your concern, I'll keep the issue open to track this to completion at some point.

**Comment by vadimkantorov** [comment]
For my personal project hosted on GitHub pages with a custom domain, I've set up a (free) CloudFlare frontend which can be configured to offer https: https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by zasdfgbnm** [comment]
fixed
