### ISSUE TITLE
Visual C++ TH\vector\AVX2.c(60): error C2440: 'function': cannot convert from 'int' to '__m256'

### ISSUE THREAD

**Issue by N-Dekker** [pytorch/pytorch#4531]
Visual C++ 2015 (64-bits) produces the following messages (both for Debug and Release) at the master branch (current commit: c9bc6c2bc3af1308cff72c95eda55a1b7eff293c):

>  AVX2.c
>...\src\TH\vector\AVX2.c(60): warning C4013: 'log256_ps' undefined; assuming extern returning int
>...\src\TH\vector\AVX2.c(60): error C2440: 'function': cannot convert from 'int' to '__m256'
>...\src\TH\vector\AVX2.c(60): warning C4024: '_mm256_mul_ps': different types for formal and actual parameter 2
>...\src\TH\vector\AVX2.c(64): warning C4013: 'sincos256_ps' undefined; assuming extern returning int
>...\src\TH\vector\AVX2.c(80): warning C4305: 'function': truncation from 'double' to 'float'

Does anyone of of you have a clue what goes wrong?

See https://github.com/pytorch/pytorch/blob/c9bc6c2bc3af1308cff72c95eda55a1b7eff293c/aten/src/TH/vector/AVX2.c#L60

**Comment by N-Dekker** [comment]
The problem is that the function definitions from https://github.com/pytorch/pytorch/blob/c9bc6c2bc3af1308cff72c95eda55a1b7eff293c/aten/src/TH/vector/avx_mathfun.h are not available ("undefined") to my Visual C++ build. Because for my build, USE_AVX2 is not defined. Which seems to be because FIND_PACKAGE(SSE) did not find AVX on my machine (C_AVX_FOUND does not evaluate to true). Any suggested fix is still welcome!

**Comment by ezyang** [comment]
I'm going to guess that this has been fixed.
