### ISSUE TITLE
installation prob: CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/repodata.json>

### ISSUE THREAD

**Issue by tzuf** [pytorch/pytorch#4532]
tried to install pytorch via conda on Ubuntu: 
'conda install pytorch torchvision -c pytorch'
I get:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /pytorch/linux-64/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff878897240>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)

same thing when using pip
any idea?

**Comment by apaszke** [comment]
This is the answer:
> Failed to establish a new connection: [Errno 101] Network is unreachable
Your connection is misconfigured.
