### ISSUE TITLE
Error using DDP for parameters that do not need to update gradients

### ISSUE THREAD

**Issue by wytcsuch** [pytorch/pytorch#45326]
I use DDP to train with multi GPU.I only need the feature map of one layer from VGG model, and do not need to update its parameters.However, the following errors occur：
AssertionError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient. 

My code：
```
self.netF = networks.define_F(opt, use_bn=False).to(self.device)
print('num_gpu',opt['num_gpu'])
if opt['dist']:
     self.netF = DistributedDataParallel(self.netF,device_ids=[torch.cuda.current_device()],find_unused_parameters = True)
else:
     self.netF = DataParallel(self.netF)

def define_F(opt, use_bn=False):
    gpu_ids = opt['gpu_ids']
    device = torch.device('cuda' if gpu_ids else 'cpu')
    # PyTorch pretrained VGG19-54, before ReLU.
    if use_bn:
        feature_layer = 49
    else:
        feature_layer = 34
    netF = SRGAN_arch.VGGFeatureExtractor(feature_layer=feature_layer, use_bn=use_bn,
                                          use_input_norm=True, device=device)
    netF.eval()  # No need to train
    return netF


  class VGGFeatureExtractor(nn.Module):
    def __init__(self, feature_layer=34, use_bn=False, use_input_norm=True,
                 device=torch.device('cpu')):
        super(VGGFeatureExtractor, self).__init__()
        self.use_input_norm = use_input_norm
        if use_bn:
            model = torchvision.models.vgg19_bn(pretrained=True)
        else:
            model = torchvision.models.vgg19(pretrained=True)
        if self.use_input_norm:
            mean = torch.Tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1).to(device)
            # [0.485 - 1, 0.456 - 1, 0.406 - 1] if input in range [-1, 1]
            std = torch.Tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1).to(device)
            # [0.229 * 2, 0.224 * 2, 0.225 * 2] if input in range [-1, 1]
            self.register_buffer('mean', mean)
            self.register_buffer('std', std)
        self.features = nn.Sequential(*list(model.features.children())[:(feature_layer + 1)])
        # No need to BP to variable
        for k, v in self.features.named_parameters():
            v.requires_grad = False
    def forward(self, x):
        # Assume input range is [0, 1]
        if self.use_input_norm:
            x = (x - self.mean) / self.std
        output = self.features(x)
        return output
```

pytorch：1.4
cuda：10.0

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @jlin27

**Comment by zou3519** [comment]
Maybe we can improve the error message around this? It seems reasonable to be able to want your model to work with DistributedDataParallel even if you're not doing any training

**Comment by wytcsuch** [comment]
> 也许我们可以改善此错误消息？即使您没有进行任何培训，也希望模型能够与DistributedDataParallel一起使用似乎很合理。

thanks.I thought that many people might encounter this problem, but I found that no one raised it.

**Comment by pritamdamania87** [comment]
This error message was added as part of https://github.com/pytorch/pytorch/issues/25552. I guess the reasoning was that if you don't need to train anything there is no reason to use DDP and you should use your model as is. The benefit of keeping the assertion is that it can actually catch errors where the user did want to train the model but didn't set trainable params accordingly.

@wytcsuch Could elaborate on why you need to use DDP here if you're not training anything?
