### ISSUE TITLE
Blank value for _GLIBCXX_USE_CXX11_ABI when compiling with Homebrew's GCC (on macOS)

### ISSUE THREAD

**Issue by JBlaschke** [pytorch/pytorch#45323]
## 🐛 Bug

Compiling against the C++ API on macOS using GCC-9.3, and cmake seems to use a bad flag:
`... -fopenmp -D_GLIBCXX_USE_CXX11_ABI= -std=c++14 ...` -- note how it "blanks out" the `_GLIBCXX_USE_CXX11_ABI` variable. This causes the compiler to fail in the stdlib:
```cpp
/usr/local/Cellar/gcc@9/9.3.0/include/c++/9.3.0/x86_64-apple-darwin18/bits/c++config.h:273:27: error: #if with no expression
  273 | #if _GLIBCXX_USE_CXX11_ABI
```

What's probably going on here is that `-D_GLIBCXX_USE_CXX11_ABI=` (instead of `-D_GLIBCXX_USE_CXX11_ABI=0` or `-D_GLIBCXX_USE_CXX11_ABI=1`) causes the compiler substitute nothing for `_GLIBCXX_USE_CXX11_ABI`, which means that the `#if _GLIBCXX_USE_CXX11_ABI` becomes `#if ` -- what we would want is `#if 0`

Any advice on how to fix this would be much appreciated -- I've tried manually setting `_GLIBCXX_USE_CXX11_ABI`, but it seems to be overwritten somewhere.

## To Reproduce

I'm compiling with the following `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(main)

find_package(Torch REQUIRED)

add_executable(main main.cpp)

# properties
# C++ properties: at least a C++14 capable compiler is needed
target_compile_features(main PUBLIC cxx_std_14)
set_target_properties(main PROPERTIES
    CXX_EXTENSIONS OFF
    CXX_STANDARD_REQUIRED ON
)

target_link_libraries(main PRIVATE "${TORCH_LIBRARIES}")
```

Full `CMakeList.txt` [here](https://github.com/AMReX-Learn/ml_interfaces/blob/development/classification_example/CMakeLists.txt)

## Expected behavior

Compile successfully

## Environment

`collect_env.py` output:
```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.14.6 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0
[conda] Could not collect
```

NB: I manually specified GCC using `-DCMAKE_C_COMPILER=$(which gcc-9) -DCMAKE_CXX_COMPILER=$(which g++-9)` -- which are installed using Homebrew

cc @malfet @seemethere @walterddr

**Comment by zou3519** [comment]
I'm not sure we support building with gcc on mac os, we generally recommend using clang on mac.

**Comment by JBlaschke** [comment]
Closing this issue -- I was successful using clang ;)
