### ISSUE TITLE
How to print C++ log like GRAPH_DEBUG?

### ISSUE THREAD

**Issue by liym27** [pytorch/pytorch#45331]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zou3519** [comment]
Please ask questions on the PyTorch forum: discuss.pytorch.org
