### ISSUE TITLE
nn.BatchNorm1d fails with batch size 1 on the new PyTorch 0.3

### ISSUE THREAD

**Issue by ccsasuke** [pytorch/pytorch#4534]
My code was running Okay on PyTorch 0.2, but ran into this error when forwarding through a BatchNorm1d layer on 0.3:

`ValueError: Expected more than 1 value per channel when training, got input size [1, 128]`

I looked into the code and found that functional.batch_norm() added a check in 0.3:

```
def batch_norm(input, running_mean, running_var, weight=None, bias=None,
               training=False, momentum=0.1, eps=1e-5):
    if training:
        size = list(input.size())
        if reduce(mul, size[2:], size[0]) == 1:
            raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
    f = torch._C._functions.BatchNorm(running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled)
    return f(input, weight, bias)
```

So each of my samples is a 1d vector of size 128, and some of the batches may happen to have size 1. Therefore, my input size can be [1, 128].
On these (valid) batches, however, `reduce(mul, size[2:], size[0])` will return 1 and fails the check.

**Comment by colesbury** [comment]
Like the error message says, you can't use feature-wise batch normalization if you only have 1 element per-feature.

https://arxiv.org/abs/1502.03167

**Comment by ccsasuke** [comment]
The batch sizes are not always 1. Say I have a batch size of 16 and my dataset has 17 samples. It should not fail on the 2nd batch, right?

**Comment by colesbury** [comment]
It will fail. Don't train on batches of size 1 if you use feature-wise batch normalization. (Inference is fine on batch-size 1). Skip over the left-over batch.

Batch normalization computes:

```
y = (x - mean(x)) / (std(x) + eps)
```

If you have one sample per batch then mean(x) = x, and the output will be entirely zero (ignoring the bias). You can't use that for learning.

**Comment by ccsasuke** [comment]
Thank you for the advice. I'll skip leftover batches for now.
But can't it just be a no-op for size 1 batches?

**Comment by colesbury** [comment]
No, because then the output would not have zero mean and unit variance. My guess is that changing statistics like that would also hurt convergence.

**Comment by maunzzz** [comment]
From my understanding the mean and variance during training is calculated as a running sum  

`m = 0.9*mean(x) +  0.1*m`
` s = 0.9*std(s) +  0.1*s`

then

`y = (x - m) / (s + eps)`

From docs:
"During training, this layer keeps a running estimate of its computed mean and variance. The running sum is kept with a default momentum of 0.1."

In this case, I don't see a problem with a batch size of 1 during training (you probably want to increase the momentum though).
Have I misunderstood something here? Or why does batch size 1 fail in torch 0.3?

**Comment by fmassa** [comment]
Batch size of 1 generally means std = 0, which can quickly lead to inf/ nan

**Comment by mikolchon** [comment]
I have the opposite problem (or non-problem?), where I am using `BatchNorm2d` with batch size 1 and training goes without any problem. This causes me a confusion, what is going on? BTW I am trying to replicate this paper https://dmitryulyanov.github.io/deep_image_prior

**Comment by laoreja** [comment]
Using a running average as the mean, the std will not be 0 (only the first data), I cannot see the problem?

**Comment by jph00** [comment]
Here is a minimal failing test showing this issue:

```python
import torch, torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data.dataloader import DataLoader

def _run_batch_size_test(bs):
    dataset = TensorDataset(torch.randn(9, 128), torch.randint(0,3,(9,)))
    dataloader = DataLoader(dataset, batch_size=bs)
    simple_model = nn.Sequential(nn.BatchNorm1d(128), nn.Linear(128,4))
    for (x,y) in iter(dataloader): z = simple_model(x)

 # This test will fail as the last batch will have a size of 1
_run_batch_size_test(4)
```

**Comment by TimZaman** [comment]
Because the mean is calculated over the running average, it will not be 0. BN should accept a batch size of 1 just fine, as I see it.

**Comment by muaz-git** [comment]
Hi, I am using virtual batches [as mentioned here](https://medium.com/@davidlmorton/increasing-mini-batch-size-without-increasing-memory-6794e10db672). 
Currently my virtual batch size is 4 and I am optimizing after 64 batches. I have some batch normalization in my network.
Moreover, my model is in parallel mode. But I still face this issue. 
Any help will be appreciated. Thanks.

**Comment by JeroenDelcour** [comment]
At the very least it should have a more helpful error message. Right now it's a little cryptic:

```raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))```

[Found in the code here.](https://github.com/pytorch/pytorch/blob/8bc5b867093f1b44f5168f3e41b1bdf0ba3e05a7/torch/nn/functional.py#L1667)

In my case it took significant time scratching my head before I found this GitHub issue. Perhaps something along the lines of `"Batch normalization requires batch size of at least 2, see GitHub issue #4534".

**Comment by tristone13th** [comment]
> No, because then the output would not have zero mean and unit variance. My guess is that changing statistics like that would also hurt convergence.

Thanks for your detailed explanation about this problem, but if I want to predict and get some results from input rather than train my model with these data, and in the ` forward() ` function I used the batch normalization layer so that I will failed, how to solve that problem? Hope for your reply.

**Comment by zzzace2000** [comment]
It still happens in the PyTorch 1.0. Any progress plan on this?

**Comment by YUE-FAN** [comment]
> I have the opposite problem (or non-problem?), where I am using `BatchNorm2d` with batch size 1 and training goes without any problem. This causes me a confusion, what is going on? BTW I am trying to replicate this paper https://dmitryulyanov.github.io/deep_image_prior

I'm also very confused by that. The code for the sanity check is:
```
if training:
    size = list(input.size())
    if reduce(mul, size[2:], size[0]) == 1:
        raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
```
It seems that if the input tensor is of size [1, 3, 32, 32], it will pass the test.
Why doesn't the code look like:
```
if training:
    size = list(input.size())
    if size[0] == 1:
        raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
```
@colesbury

**Comment by VasLem** [comment]
I faced this issue when trying to train Unet using a pretrained Inception32 encoder with variable sized images. Is there a way to handle it, or should I remove all the BN layers from the network? Another idea I had was to set those layers parameters `requires_grad` to false, but I have not tested it yet.

**Comment by buoyancy99** [comment]
I think this is worth fixing. When I use variable size inputs I frequently encounter this and a manual fix is ugly

**Comment by siarez** [comment]
I too think this should be fixed. It should just use the running mean and std when it encounters batches of size 1. I don't see what could go wrong with this solution.

**Comment by colesbury** [comment]
@siarez @buoyancy99 And exactly **how** do you think it should it be fixed?

**Comment by siarez** [comment]
@colesbury I think instances where the batch is of size one 1, should just use the running mean and std to normalise the batch instead of calculating them from the batch. Essentially similar to what would happen in eval mode.

**Comment by VasLem** [comment]
@colesbury @siarez But again, if the training is performed using a batch size of 1, the batch normalisation makes little sense, I think that omitting the layer, printing out a warning that can be explicitly turned off, is more meaningful. The running mean seems appealing as an idea, but it is not something that can be implicitly set, as it essentially does not perform the same operations as the original Batch Normalization and is sensitive to high variations through batches (of 1!).

**Comment by siarez** [comment]
@VasLem It's not that the batch size is 1 for the whole training, but the last batch could be of size one if `(num_of_samples % batch_size) == 1`.  For example, if you have 101 samples and you batch size is 10.

**Comment by VasLem** [comment]
@siarez ok true, haha, I had not thought of that possibility, although this can be easily evaded with a multitude of ways, it is not that constraining, however I see your point that the suppression of the BN effect could possibly damage the training in such circumstance. Still it is something that can be easily bypassed...

**Comment by siarez** [comment]
@VasLem yeah, that's actually how I came across this issue :)
If we are not going to fix it, I think we should at least make the error message more clear.

**Comment by lysecret2** [comment]
still an issue.

**Comment by whitealex95** [comment]
Arent' there any workarounds yet? My Model works with varying size of batch, so the drop_last wouldn't be my solution.

**Comment by WangKK1996** [comment]
I fix this by defining:
```
self.batchnorm = nn.BatchNorm1d(2)
```
and then add this in my code:
```
n, c = inp.size()
if n != 1:
    x = self.batchnorm(inp)
else:
    x = inp
```
I am wondering if this solution is right.

**Comment by anilsathyan7** [comment]
@whitealex95 If you have variable batch size try to repeat the tensors to avoid batch size =1 (if it works with your training iteration logic)
```
#Say, input shape=torch.Size([1, 1024])
if input.shape[0] == 1:
              input=input.repeat(2,1)
```

**Comment by anilsathyan7** [comment]
Maybe we can repeat the tensors (or add suitable tensors along batch dimension) if batch size = 1 as a temporary a temporary work around?

**Comment by ironhide23586** [comment]
Facing this issue even after calling model.eval()

**Comment by kaglowka** [comment]
I just came across this issue, too, and I can't see why we should have to bypass this "overeager" check rather than amend it/remove it.
Just to say a few words about my use case, it is a setting much like reinforcement learning scenario (not exactly though, optimized through neuroevolution). Single training batch is composed of multiple sequential timesteps one by one, and for each timestep the input size is equal to the number of agents that are left surviving. Overall the batch size can be large, but it may be 1 for some timesteps.
