### ISSUE TITLE
Bug in max_pool2d with ceil_mode under certain conditions

### ISSUE THREAD

**Issue by knottb** [pytorch/pytorch#45357]
## 🐛 Bug

In `torch.nn.functional.max_pool2d` with `ceil_mode=True`, there are cases where maximum can be taken for a fully out-of-bounds kernel. See repro.

## To Reproduce
```
>>> x = torch.randn(1, 1, 6, 7)
>>> y = torch.nn.functional.max_pool2d(x, 1, stride=(2, 2), padding=0, ceil_mode=True)
>>> y.size()
torch.Size([1, 1, 4, 4])
>>> y
tensor([[[[ 1.5680,  1.0815, -0.5165, -1.0466],
          [ 1.2615,  1.1358, -0.0340, -0.4750],
          [ 0.7457, -1.0273,  1.0388,  0.7754],
          [   -inf,    -inf,    -inf,    -inf]]]])
```
## Expected behavior

I would expect for these parameters (`kernel_size=1, stride=(2, 2), ceil_mode=True`), we would get an output of size (3, 4) since the 4th kernel on dimension 2 would start at index 6 which is out-of-bounds.

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by AnshuTrivedi** [comment]
@knottb  I think it's not bug .For reference [see here](https://discuss.pytorch.org/t/ceil-mode-in-pooling/54646/2).
In the case of ceil mode, additional columns and rows are added at the right as well as at the down. (Not top and not left). **It does not need to be one extra column.** It depends on the stride value as well.

**Comment by gchanan** [comment]
A quick reading of the docs and napkin math suggests it should be `(3,4)` so either the code or the docs are wrong.

**Comment by ezyang** [comment]
@ngimel thinks the code is wrong, because a completely out of bounds window is not right

**Comment by gchanan** [comment]
confirmed this isn't a regression, so putting on the 1.8.0 milestone.
