### ISSUE TITLE
Slicing is not supported for `nn.Sequential`

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#4535]
It seems the slicing is not supported for `nn.Sequential`. For example, 

```python
import torch.nn as nn

net = nn.Sequential()
net.add_module('first', nn.Linear(2, 2))
net.add_module('second', nn.Linear(3, 3))
net.add_module('third', nn.Linear(4, 4))

for fc in net[:-1]:
    print(fc)
```
Then it has the error `TypeError: '<=' not supported between instances of 'int' and 'slice'
`

**Comment by soumith** [comment]
this feature was added into the `master` branch 4 days ago, via https://github.com/pytorch/pytorch/pull/4491
