### ISSUE TITLE
about aten/src/ATen/native/cudnn/Conv.cpp  issue

### ISSUE THREAD

**Issue by konioyxgq** [pytorch/pytorch#45372]
On line [678](https://github.com/pytorch/pytorch/blob/cf808bed738632dba15531337ceb9fa5f148d7b4/aten/src/ATen/native/cudnn/Conv.cpp#L678) in the conv.cpp  I think it’s better to change it to “if(cache.find(args.params, &algoPerf))”. Because I think no matter whether only_use_default is true or false, “cache.insert” will be executed below. Maybe I understood it wrong and hope to guide.

cc @albanD @mruberry

**Comment by mruberry** [comment]
@zasdfgbnm, who wrote the relevant lines.

Looks OK to me but he's the expert.

**Comment by albanD** [comment]
Hi,

I am not sure you want to do that. In particular, the deterministic flag can change from one run to the next and so you don't want to use cache that was created with `deterministic=false` when you now have `deterministic=true`.
But maybe I misread the code?

**Comment by zasdfgbnm** [comment]
From https://github.com/pytorch/pytorch/blob/cf808bed738632dba15531337ceb9fa5f148d7b4/aten/src/ATen/native/cudnn/Conv.cpp#L207-L221 we see that `deterministic` is part of the hash key, but `benchmark` is not. So if the `deterministic` flag is changed, it will not use the previous cache. But if the `benchmark` is changed, then the previously cache is still valid.

The line [678](https://github.com/pytorch/pytorch/blob/cf808bed738632dba15531337ceb9fa5f148d7b4/aten/src/ATen/native/cudnn/Conv.cpp#L678) is to say, if we have `benchmark=False, deterministic=True`, then we will force using the default algorithm only. This is a hacking point that allows PyTorch to fallback to the default algorithm by `benchmark=False, deterministic=True`. cc: @ngimel

**Comment by konioyxgq** [comment]
I understand a little bit. thank you very much
