### ISSUE TITLE
How to build from a release tar package ?

### ISSUE THREAD

**Issue by haoren3696** [pytorch/pytorch#45387]
Hi, I download newest release tar package and find it can not build pytorch, Can anyone help meo build this release version from source?

```
wget https://github.com/pytorch/pytorch/archive/v1.6.0.tar.gz
tar xf v1.6.0.tar.gz
cd pytorch-1.6.0
python3 setup.py install
```

output:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Building wheel torch-1.6.0a0
-- Building version 1.6.0a0
Could not find /home/xzpeng/pytorch/pytorch-1.6.0/third_party/gloo/CMakeLists.txt
Did you run 'git submodule update --init --recursive'?

Does the release tar package support building from source?

cc @ezyang @seemethere @malfet @walterddr

**Comment by devil-cyber** [comment]
hey @haoren3696  Just type git init into your command line and press enter. Then run your command again, you probably were running git remote add origin [your-repository].

**Comment by vishsangale** [comment]
@haoren3696 Follow [these](https://github.com/pytorch/pytorch#from-source) instructions to build from scratch. You may not be able to build from source using tar package, since it doesn't seem to have third party packages from git sub-modules. 
Basically you may want to run below command in root directory if you want to build Release version 1.6.0 from source after installing dependencies see earlier link.
```
git checkout v1.6.0
```

**Comment by haoren3696** [comment]
> @haoren3696 Follow [these](https://github.com/pytorch/pytorch#from-source) instructions to build from scratch. You may not be able to build from source using tar package, since it doesn't seem to have third party packages from git sub-modules.

Hi @vishsangale, yes，you are right. What I am confused about is if the tar package cannot be used to build pytorch, what is it for? Maybe the third party should be included when releasing a tar package. Is there a community maintainer who can answer this question?

**Comment by seemethere** [comment]
The tar source archives are automatically created by GitHub whenever a release / tag is created. 

These are not official ways to build pytorch from source and we would recommend checking out the tag and building from there. 

Do note that building pytorch also requires its sub modules so those will need to be initialized as well
