### ISSUE TITLE
How to convert pytorch model to Nvidia faster transformer?

### ISSUE THREAD

**Issue by wangxiang2713** [pytorch/pytorch#45386]
Hi, i want to detect Bert model structure in pytorch model and convert the structure by Nvidia faster transformer op automatically.
Is there any existing project? If not, i want to develop one, so should i develop on origin pytorch or TorchScript? Should i develop a pass to detect Bert in TorchScript IR and replace it by faster transformer op?
Thankyou very much!

**Comment by gchanan** [comment]
Please ask questions on the forum (https://discuss.pytorch.org/).
