### ISSUE TITLE
How can I read the .pt file with pickle instead of torch.load()?

### ISSUE THREAD

**Issue by cocokale** [pytorch/pytorch#45394]
Due to prerequisites limitations, I am not able to install torch. Is it possible to load the pt file with python library pickle (or other libraries) instead of torch.load()?

**Comment by FlorentMeyer** [comment]
I'd like to know that too!

**Comment by Github0119** [comment]
I'd like to know that too! Too!

**Comment by hakurena** [comment]
I'd like to know that too! Too! TOO!

**Comment by dqj5182** [comment]
Same
