### ISSUE TITLE
Make `torch.bmm` behave more like `np.matmul`

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#4539]
There are two main features that `torch.bmm` should support:
- broadcasting
- arbitrary left batch dimensions

**Comment by jekbradbury** [comment]
Isn't `bmm` mostly deprecated in favor of `torch.matmul`, except that something needs to exist as a wrapper of cuBLAS batchedGemm?

**Comment by zou3519** [comment]
Thanks @jekbradbury! I didn't realize `torch.matmul` existed.
