### ISSUE TITLE
Can't sign up for Pytorch forums 

### ISSUE THREAD

**Issue by DengNaichen** [pytorch/pytorch#45395]
I want to create a new account of Pytorch forums, but the web always says: " something goes wrong, please try forget passwords link..."

**Comment by gchanan** [comment]
I was able to reproduce this, I got this when clicking "Create New Account".

**Comment by soumith** [comment]
cc: @ptrblck

**Comment by soumith** [comment]
can you see if it works now. we fixed it.
please reopen if it doesn't work

**Comment by DengNaichen** [comment]
hello,
it works now, thank you for your help!
