### ISSUE TITLE
Cuda out of memory but gpu memory is utilized about a half

### ISSUE THREAD

**Issue by SebyakinAndrei** [pytorch/pytorch#4540]
I'm running slightly modified code of EDSR baseline network from here: https://github.com/thstkdgus35/EDSR-PyTorch
The training on first epoch goes well, but on the test stage when loading a model it raises an error:
```
THCudaCheck FAIL file=d:\pytorch\pytorch\torch\lib\thc\generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    t.test()
  File "D:\Projects\SR\EDSR-PyTorch-master\code\trainer.py", line 100, in test
    output = _test_forward(input)
  File "D:\Projects\SR\EDSR-PyTorch-master\code\trainer.py", line 91, in _test_forward
    return self.model(x)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Projects\SR\EDSR-PyTorch-master\code\model\EDSR.py", line 50, in forward
    x = self.tail(res)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 67, in forward
    input = module(input)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 67, in forward
    input = module(input)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at d:\pytorch\pytorch\torch\lib\thc\generic/THCStorage.cu:58
```
But what is strange is that gpu memory at that moment is utilised about a half. Here's nvidia-smi output (at the moment of peak memory usage):
```
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi -i 0 -q -d MEMORY

==============NVSMI LOG==============

Timestamp                           : Mon Jan 08 23:49:46 2018
Driver Version                      : 388.13

Attached GPUs                       : 1
GPU 00000000:02:00.0
    FB Memory Usage
        Total                       : 6144 MiB
        Used                        : 3657 MiB
        Free                        : 2487 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 229 MiB
        Free                        : 27 MiB
```
In test function I also use volatile=True option. What could be the problem?
OS: Win10
GPU: 1060 6G

**Comment by SsnL** [comment]
Which version of PyTorch are you using? Btw, cuda memory usage can change very quickly, so you may not have captured the peak moment. It is also possible that the program tries to allocate a tensor larger than all remaining memory, causing OOM.

**Comment by SebyakinAndrei** [comment]
Thank you for your answer! I use pytorch 0.3 win64 version from here: https://anaconda.org/peterjc123/pytorch. Also, about model size, it isn't large, because model has only 16 res blocks (which don't have batchnorm) and when I save trained model after first epoch before test on disk, it weights only 6MB. Also, I believe, that test input image is about hd size, so can this model allocate so large tensors? How can I trace this process?

**Comment by benvcutilli** [comment]
Weights alone may not amount to much (and there may be extra memory baggage besides the numerical values of the weights alone, for example). Keep in mind that there is a whole computational graph and whatever. Did you try running it on CPU to get a feel for RAM usage? It's almost certainly not 1-to-1, but it may be an indicator.

**Comment by SebyakinAndrei** [comment]
Thanks for your suggestion! I'll try it soon)

**Comment by jiecaoyu** [comment]
@SebyakinAndrei Hi, I am going through a similar problem of running out of memory. Do you find any solution yet? Thanks!

**Comment by jiecaoyu** [comment]
@benvcutilli I think not. Also, I am using ```volatile=True``` to prevent saving unnecessary intermediate results during evaluation.

Actually, for my case, experiments runs well for batches with batch size = 256. But it will break for the last batch in each epoch which has a size lower than 256, for example 143.

**Comment by SebyakinAndrei** [comment]
@jiecaoyu I recognized that the model, that I used is very raw and not very memory-efficient, so I basically moved to similar model, based on tensorflow, that successfully runs on my hardware. 
About the original problem, I think that, as said SsnL earlier, CUDA memory changes very quickly and monitoring tools can't handle it.

**Comment by SebyakinAndrei** [comment]
So, I think that I need to close this issue. Thanks to all for your suggestions and advices!

**Comment by emergencyd** [comment]
do you have any solutions? @jiecaoyu 
my gpu memory would increase a lot as the batch_size increases. Also, it breaks for the last batch

**Comment by jiecaoyu** [comment]
@emergencyd I think you can simply skip the last batch. I still dont know what is the reason behind this.

**Comment by puneethrj** [comment]
When I use pytorch for training there are time that due to errors or because i changed my mind in between training I choose to nterupt th ejupyter kernel. The GPU doesn't flush the memory thinking the data is still usefull and this creates a problem when I do changes in the code and try to run it for the training again.
