### ISSUE TITLE
Invalid cast to PyCFunction for function taking only 1 argument instead of 2

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#45419]
## 🐛 Bug

The function _c10d_init takes only 1 argument: https://github.com/pytorch/pytorch/blob/95a97e51b5cb16ad0067c4458ef1f1a59d94ab6f/torch/csrc/distributed/c10d/init.cpp#L130

However it is defined as `METH_NOARGS` (defined at https://docs.python.org/3/c-api/structures.html#METH_NOARGS) which takes 2 arguments.

This leads to the Python runtime passing 2 arguments where only 1 is expected which depending on the calling convention can lead to stack underflow, unexpected register changes or other issues.

## To Reproduce

1. Compile PyTorch as instructed
1. Grep output for `-Wcast-function-type`
1. Or just check the source

The issue is quite old already an is still in current master as well as at least 1.5.0, probably much earlier.

I'd suggest to promote `-Wcast-function-type` to an error (`-Werror=cast-function-type` IIRC) to avoid this in the future and even remove all the casts to PyCFunction. If the function has the correct signature the cast is unnecessary and as seen in this case could be even wrong.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by Flamefire** [comment]
Thanks @pritamdamania87 for taking on this. May I suggest to do a full search&replace on `(PyCFunction)` and simply remove it, then see where it breaks? Not using such C-Style casts can avoid problems like this in the future. Also enabling the warning mentioned above an promoting it to an error could help to. For another project I implemented a function which safely casts function pointers to Python function pointers by replacing PyObject like params by `PyObject*`: https://github.com/score-p/scorep_binding_python/blob/719858c695ed43b41f26dd82f636178dfe51d8b8/src/scorepy/pythonHelpers.hpp#L66-L72
This also helps a lot for type safety

**Comment by pritamdamania87** [comment]
Reopening issue to address further issues mentioned above by @Flamefire

**Comment by pritamdamania87** [comment]
@Flamefire I've removed as many casts as I could in: https://github.com/pytorch/pytorch/pull/46227, The only ones I couldn't remove were the ones of the form `  {"copy_", (PyCFunction)(void(*)(void))THPStorage_(copy_), METH_VARARGS | METH_KEYWORDS, nullptr},` since `METH_VARARGS | METH_KEYWORDS` implies 3 args and I had to keep the PyCFunction cast. Let me know if there is a way around this as well and I can update the PR accordingly.

**Comment by Flamefire** [comment]
I see. For `METH_VARARGS | METH_KEYWORDS` the expected type is `PyCFunctionWithKeywords`: https://docs.python.org/3/c-api/structures.html#c.PyCFunctionWithKeywords So I'd suggest to encapsulate the cast to `PyCFunction` (which seems to be required, unfortunately) into a function which takes a `PyCFunctionWithKeywords` to a) hide the ugliness of `(PyCFunction)(void(*)(void))` and b) enforce the correct signature.
I'm wondering why pybind11 isn't used here which avoids all those shenanigans, but I guess that step would be to large for now. Ensuring the correct method signatures is already valuable as it may discover other issues and prevent introducing new ones.

So besides making the cast prettier/safer there is no way around this. Even the official Python docs (e.g. https://python.readthedocs.io/en/latest/extending/newtypes.html) cast a lot. Difference in C++ is that we can use some template magic and the like to check types (see my link in the last post where I replace "registered" `PyObject*` compatible arguments in the signature) In this case though there is not much to do as CPython requires this kind of "invalid" cast from `PyCFunctionWithKeywords` to `PyCFunction`, but it can at least be checked to be the former.

**Comment by pritamdamania87** [comment]
> I see. For METH_VARARGS | METH_KEYWORDS the expected type is PyCFunctionWithKeywords: https://docs.python.org/3/c-api/structures.html#c.PyCFunctionWithKeywords So I'd suggest to encapsulate the cast to PyCFunction (which seems to be required, unfortunately) into a function which takes a PyCFunctionWithKeywords to a) hide the ugliness of (PyCFunction)(void(*)(void)) and b) enforce the correct signature.

Thanks for the suggestion, I'll give this a shot.

> I'm wondering why pybind11 isn't used here which avoids all those shenanigans, but I guess that step would be to large for now.

I'm not sure about the reason for this, but I guess is that its some old legacy code. We use pybind11 everywhere in any new code we add that has python bindings.
