### ISSUE TITLE
Cannot create new account in Pytorch forum

### ISSUE THREAD

**Issue by mbengterry** [pytorch/pytorch#45423]
## ❓ Questions and Help
I have been trying to create an account in order to post something I need help with, but each time I enter all the information and click on "Create New Account", I get the error **Something went wrong, perhaps this email is already registered, try the forgot password link**. I don't have any pytorch forum account. How can that be fixed? I really have a burning issue which I need to be addressed
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by pere-gb** [comment]
Been having the same problem

**Comment by gchanan** [comment]
Confirmed, using this issue as the tracker: https://github.com/pytorch/pytorch/issues/45395

**Comment by phil123456** [comment]
same here, 3 activation emails, still nothing in my inbox nor spam folder

**Comment by phil123456** [comment]
tried changing email, same issue, I never get any confirmation email
please help me
