### ISSUE TITLE
torch.var_mean and torch.std_mean does not have `out` variant

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#45446]
Almost all torch functions allow users to specify `out` kwarg, var_mean and std_mean should not be different.

**Comment by gchanan** [comment]
doesn't `std_mean` not have an out variant either?

**Comment by gchanan** [comment]
I'm also not sure we want to support this -- does anyone actually want these functions?

**Comment by ngimel** [comment]
Yes, std_mean doesn't have out variant either. What is our rule for supporting/not supporting `out` variants? It can't be "someone wants to use them" because we have many functions with `out` variants that are never used.

**Comment by vadimkantorov** [comment]
@gchanan I used them as a simple implementation of InstanceNorm. Specifying dimensions explicitly is a clear way to express what dimensions are aggregated out. But it would be good if there wasy a unifying API for existing Batch/Layer/Instance-normalization modules. For other normalization needs, it is often that we need severla moments together, and this saves a pass over data. My two other issues about these functions: https://github.com/pytorch/pytorch/issues/24041 https://github.com/pytorch/pytorch/issues/44636

**Comment by vadimkantorov** [comment]
For std_mean/var_mean maybe two out arguments would be needed

**Comment by ngimel** [comment]
They won't be the first functions requiring tuple `out`.
