### ISSUE TITLE
Compile Error for .cu files when using libtorch

### ISSUE THREAD

**Issue by Mabinogiysk** [pytorch/pytorch#45496]
## 🐛 Bug
I know this is a repeated question, however it has not been resolved. I am working on a project and only this problem left. I desperately want a solution.
`.cu` files cannot be compiled when using libtorch due to this error:
```
nvcc fatal   : Unknown option 'Wall'
```
I wonder is there any way to solve it by editing `CMakeLists.txt`？

Discuss in detail: https://github.com/pytorch/pytorch/issues/31283
1. Switching to cuda10.2 seems the only solution but I cannot do it for some reason.
2. Switching to gcc7.3 did not work for me.
It seems `.cu` file can be compiled on win10 manually: https://github.com/pytorch/pytorch/issues/27958

## To Reproduce

1. CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(torchcpp)

find_package(CUDA REQUIRED)
find_package(Torch REQUIRED)

enable_language(CUDA)
add_executable(torchcpp test.cu)
target_link_libraries(torchcpp "${TORCH_LIBRARIES}")
# set_property(TARGET torchcpp PROPERTY CXX_STANDARD 11)
set_property(TARGET torchcpp PROPERTY CUDA_STANDARD 14)
```
2. test.cu
```
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>

#include <iostream>

using namespace std;
using namespace at;

int main() {
    auto tensor = at::randn({5}).cuda();
    cout << tensor << endl;
}
```

3. make
```
mkdir build && cd build
cmake3 -DCMAKE_PREFIX_PATH=/root/code/libtorch/library/libtorch  ..  -DCMAKE_BUILD_TYPE=Release
cmake3 --build . --config Release
```
Then I got this error:
```
nvcc fatal   : Unknown option 'Wall'
gmake[2]: *** [CMakeFiles/torchcpp.dir/build.make:83: CMakeFiles/torchcpp.dir/test.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/torchcpp.dir/all] Error 2
gmake: *** [Makefile:104: all] Error 2
```
And there are some warnings in cmake:
```
-- Autodetected CUDA architecture(s):  7.0 7.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70
CMake Warning (dev) at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (torch) does
  not match the name of the calling package (Torch).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /root/code/libtorch/library/libtorch/share/cmake/Torch/TorchConfig.cmake:130 (find_package_handle_standard_args)
  CMakeLists.txt:5 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

## Environment
 - PyTorch Version (e.g., 1.0): 1.5.1（libtorch Pre-cxx11 ABI)
 - OS (e.g., Linux): Linux
 - Python version:
 - CUDA/cuDNN version: cuda10.1
 - Any other relevant information: gcc7.3/gcc5.3, cmake 3.17.3

cc @malfet @seemethere @walterddr

**Comment by walterddr** [comment]
I think this problem is resolved in later pytorch version. (possibly through #40399). were you still seeing this issue in latest pytorch versions?

**Comment by Mabinogiysk** [comment]
> I think this problem is resolved in later pytorch version. (possibly through #40399). were you still seeing this issue in latest pytorch versions?

Many thanks! Libtorch1.6.0 works and those warnings in cmake disappear.

**Comment by walterddr** [comment]
closing. please reopen if any additional follow up is needed.
