### ISSUE TITLE
torch.Module typing __init__ no return value

### ISSUE THREAD

**Issue by Vozf** [pytorch/pytorch#45497]
__init__ return value should be specified as None. Now it doesn't have any
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L223

https://www.python.org/dev/peps/pep-0484/#the-meaning-of-annotations

cc @albanD @mruberry @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by mruberry** [comment]
Thanks for filing this issue, @Vozf. Your reference does make this seem straightforward. I'll let our typing experts weigh-in.

**Comment by ezyang** [comment]
Yes. We're not on strict type checking yet so mypy isn't reporting failures on errors like this, but we are happy to take patches that fix it.

**Comment by Vozf** [comment]
Mypy reports this error with `disallow_untyped_calls = True` in `mypy.ini`
This forces me to do type: ignore for any subclass of nn.Module
```
class MultiBCELoss(nn.Module):
    def __init__(self) -> None:
        super().__init__()  # type: ignore
```
Is something else expected from PR beyond adding `-> None`? If it's the only thing, I can create a PR

**Comment by ezyang** [comment]
Nope, that's good enough. Of course if you want to fix this entirely, or get our mypy to globally enforce `disallow_untyped_calls`, that would be even better, but those patches will be A LOT more work, so feel free to focus on just fixing cases that are affecting you personally.

**Comment by Vozf** [comment]
Also I got a question about typing in nn.functional.
Type hints exits in nn.functional.py but they also exist in stub nn.functional.pyi. And in pyi file they contain errors. Let's take `interpolate`
In nn.functional.py
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L2975-L2976
Python2 style but correct in general.
In pyi 
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.pyi.in#L294-L295
Types have any, and no `recompute_scale_factor parameter` at all.
That seems quite strange

**Comment by ezyang** [comment]
Our general goal is to eliminate all of the pyi files. So it would also be super helpful if you can merge the pyi comments in to the py using Python 3 style.
