### ISSUE TITLE
RuntimeError: Unsupported op descriptor: thnn_batch_norm_forward-5-eps-momentum-training. File a bug report.

### ISSUE THREAD

**Issue by deepbrain** [pytorch/pytorch#4549]
I started getting this with the latest code while using JIT:

RuntimeError: Unsupported op descriptor: thnn_batch_norm_forward-5-eps-momentum-training. File a bug report.

It did not happen 7 days ago and still does not happen if I roll back pytorch to the version I had 7 days ago.  Do you need any simplified test case to fix it?

**Comment by deepbrain** [comment]
here is a simple code that reproduces it:


'''python

import torch
from torch import jit
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim        


@torch.jit.compile(nderivs=1)
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.net1 = nn.Linear(100, 200)
        self.net2 = nn.Linear(200, 1)
        self.bn = nn.BatchNorm1d(200)
        self.sigmoid = nn.Sigmoid()
        self.ReLU = nn.ReLU(inplace=False)
        self.drop = nn.Dropout(0.5)
               
    def forward(self, V):
        return self.sigmoid(self.net2(self.drop(self.ReLU(self.bn(self.net1(V)))))).squeeze() 


use_cuda = False
net = TestNet()
criterion = nn.BCELoss()
if use_cuda:
    net.cuda()
    criterion.cuda()
    V = Variable(torch.randn(100, 100)).cuda()
    label = Variable(torch.randn(100)).cuda()
else:
    V = Variable(torch.randn(100, 100))
    label = Variable(torch.randn(100))


optim_betas = (0.9, 0.999)
optimizer = optim.Adam(filter(lambda p: p.requires_grad, net.parameters()), lr=0.01, betas=optim_betas)
criterion = nn.BCELoss()

net.train()
for i in range(0,1000000):
    net.zero_grad()
    r = net(V)
    err = criterion(r, label)
    err.backward()   
'''

**Comment by ezyang** [comment]
Ah, that's probably because batchnorm got bound as an ATen method and I was apparently supposed implement some more JIT dispatch support but didn't.

**Comment by apaszke** [comment]
It should get auto-generated automatically

**Comment by sighingnow** [comment]
In #4395, `thnn_batch_norm` was renamed to `thnn_batch_norm_forward` in `derivatives.yaml`, but all functions ends with `_forward` are not recognized as JIT funciton in `gen_jit_dispatch.py`

https://github.com/pytorch/pytorch/blob/a0ab48575e8cb6cb0edb5e9966c14bf4404384fb/tools/jit/gen_jit_dispatch.py#L49-L52

**Comment by ezyang** [comment]
@colesbury, do you think you could take a look?

**Comment by apaszke** [comment]
I can take a look later today. I wrote that script
