### ISSUE TITLE
C++ TransformerEncoder constructor missing compared to decoder

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#45502]
## 🐛 Bug

minor anomaly in the contructors of Encoder/Decoder, not sure if this is by design.

The decoder has 2 constructors:
via an options structure,
or via the decoder layer module itself and a number of layers to repeat.

The encoder only allows construction via an options structure.

from nn/modules/transformercoder.h:

```
class TORCH_API TransformerEncoderImpl : public Cloneable<TransformerEncoderImpl> {
  public:
    explicit TransformerEncoderImpl(TransformerEncoderOptions options_);
```
vs
```
class TORCH_API TransformerDecoderImpl : public Cloneable<TransformerDecoderImpl> {

  public:
    TransformerDecoderImpl(TransformerDecoderLayer decoder_layer, int64_t num_layers)
      : TransformerDecoderImpl(TransformerDecoderOptions(decoder_layer, num_layers)) {}
    explicit TransformerDecoderImpl(TransformerDecoderOptions options_);
```

cc @yf225 @glaringlee

**Comment by VinodSKumar** [comment]
@glaringlee Please help to check the update for constructor

**Comment by glaringlee** [comment]
@VinodSKumar Sure, will land it today if no issues.

**Comment by VinodSKumar** [comment]
Thanks

**Comment by glaringlee** [comment]
Code landed.
