### ISSUE TITLE
'torch.HalfTensor' object has no attribute 'uniform_'

### ISSUE THREAD

**Issue by wjgaas** [pytorch/pytorch#4552]
when i using torch.set_default_tensor_type('torch.HalfTensor'), i get the error 'torch.HalfTensor' object has no attribute 'uniform_', how can i solve this?

**Comment by ezyang** [comment]
HalfTensor is missing quite a lot of operations. One workaround is to make a float tensor first and then cast it to half tensor.

**Comment by apaszke** [comment]
CPU half tensors are only meant to be used for serialization/staging purposes and not for math

**Comment by suke27** [comment]
'torch.HalfTensor' object has no attribute 'mul'
mul also not support?

**Comment by apaszke** [comment]
Nope. Math on the CPU should be done in float at least
