### ISSUE TITLE
error in installing from source

### ISSUE THREAD

**Issue by LemonMi** [pytorch/pytorch#4557]
Hello,there is the output.I don't know how to deal with it.

[ 17%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/generated/ATen_generated_THCTensorMathCompareHalf.cu.o
[ 17%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/generated/ATen_generated_THCTensorMathReduceHalf.cu.o
/home/null/pytorch/aten/src/THC/generated/../THCDeviceUtils.cuh(61): error: identifier "__shfl_xor" is undefined
          detected during:
            instantiation of "T WARP_SHFL_XOR(T, int, int, unsigned int) [with T=float]" 
/home/null/pytorch/aten/src/THC/generated/../THCTensorMathReduce.cuh(445): here
            instantiation of "void THCTensor_kernel_varInnermostDim<Real,Accreal,flag,apply_sqrt>(Real *, Real *, unsigned int, unsigned int) [with Real=half, Accreal=float, flag=true, apply_sqrt=true]" 
/home/null/pytorch/aten/src/THC/generated/../THCTensorMathReduce.cuh(505): here
            instantiation of "void THCTensor_varInnermostDim<TensorTypeK,Real,Accreal,apply_sqrt>(THCState *, TensorTypeK *, TensorTypeK *, int) [with TensorTypeK=THCudaHalfTensor, Real=half, Accreal=float, apply_sqrt=true]" 
/home/null/pytorch/aten/src/THC/generated/../generic/THCTensorMathReduce.cu(89): here

/home/null/pytorch/aten/src/THC/generated/../THCDeviceUtils.cuh(91): error: identifier "__shfl_down" is undefined
          detected during:
            instantiation of "T WARP_SHFL_DOWN(T, unsigned int, int, unsigned int) [with T=float]" 
/home/null/pytorch/aten/src/THC/generated/../THCTensorMathReduce.cuh(471): here
            instantiation of "void THCTensor_kernel_varInnermostDim<Real,Accreal,flag,apply_sqrt>(Real *, Real *, unsigned int, unsigned int) [with Real=half, Accreal=float, flag=true, apply_sqrt=true]" 
/home/null/pytorch/aten/src/THC/generated/../THCTensorMathReduce.cuh(505): here
            instantiation of "void THCTensor_varInnermostDim<TensorTypeK,Real,Accreal,apply_sqrt>(THCState *, TensorTypeK *, TensorTypeK *, int) [with TensorTypeK=THCudaHalfTensor, Real=half, Accreal=float, apply_sqrt=true]" 
/home/null/pytorch/aten/src/THC/generated/../generic/THCTensorMathReduce.cu(89): here

2 errors detected in the compilation of "/tmp/tmpxft_00003b44_00000000-7_THCTensorMathReduceHalf.cpp1.ii".
CMake Error at ATen_generated_THCTensorMathReduceHalf.cu.o.cmake:267 (message):
  Error generating file
  /home/null/pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/__/THC/generated/./ATen_generated_THCTensorMathReduceHalf.cu.o

src/ATen/CMakeFiles/ATen.dir/build.make:455: recipe for target 'src/ATen/CMakeFiles/ATen.dir/__/THC/generated/ATen_generated_THCTensorMathReduceHalf.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/THC/generated/ATen_generated_THCTensorMathReduceHalf.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:194: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by soumith** [comment]
you are compiling on a GPU that is CUDA capability less than 3.0, so the shfl_xor instruction is not available. We dont support GPUs in 2.0 / 2.1 cuda capability anymore.

**Comment by LemonMi** [comment]
@soumith OK Thank you!
