### ISSUE TITLE
Internal assert failed on searchsorted

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#45579]
## 🐛 Bug

I got this message when using `searchsorted` function

    >       idxr = torch.searchsorted(x, xq, right=False) # (nrq)
    E       RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/autograd/functions/utils.h":59, please report a bug to PyTorch.

The inputs are

    xq = torch.tensor([0.0000, 0.3333, 0.6667, 1.0000], device='cuda:0', dtype=torch.float64, requires_grad=True)
    x = torch.tensor([0.0, 0.2, 0.3, 0.5, 0.8, 1.0], device='cuda:0', dtype=torch.float64, requires_grad=True)

## To Reproduce

    import torch
    device = "cuda:0" # also doesn't work for "cpu"
    xq = torch.tensor([0.0000, 0.3333, 0.6667, 1.0000], device=device, dtype=torch.float64, requires_grad=True)
    x = torch.tensor([0.0, 0.2, 0.3, 0.5, 0.8, 1.0], device=device, dtype=torch.float64, requires_grad=True)
    idxr = torch.searchsorted(x, xq, right=False)

## Expected behavior

No error is thrown

## Environment

    PyTorch version: 1.6.0
    Is debug build: False
    CUDA used to build PyTorch: 10.2
    ROCM used to build PyTorch: N/A

    OS: Ubuntu 18.04.1 LTS (x86_64)
    GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    Clang version: Could not collect
    CMake version: version 3.14.0

    Python version: 3.7 (64-bit runtime)
    Is CUDA available: True
    CUDA runtime version: Could not collect
    GPU models and configuration: GPU 0: TITAN X (Pascal)
    Nvidia driver version: 450.51.06
    cuDNN version: Could not collect
    HIP runtime version: N/A
    MIOpen runtime version: N/A

    Versions of relevant libraries:
    [pip3] numpy==1.18.0
    [conda] blas                      1.0                         mkl
    [conda] cudatoolkit               10.2.89              hfd86e86_1
    [conda] lintorch                  0.0.1                     dev_0    <develop>
    [conda] mkl                       2019.4                      243
    [conda] mkl-include               2019.4                      243
    [conda] mkl-service               2.0.2            py37h7b6447c_0
    [conda] mkl_fft                   1.0.10           py37ha843d7b_0
    [conda] mkl_random                1.0.2            py37hd81dba3_0
    [conda] numpy                     1.18.1           py37h4f9e942_0
    [conda] numpy-base                1.18.1           py37hde5b4d6_1
    [conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
    [conda] torch                     1.4.0                    pypi_0    pypi
    [conda] torchvision               0.7.0                py37_cu102    pytorch
    [conda] torchviz                  0.0.1                    pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
cc @glaringlee

**Comment by glaringlee** [comment]
This is why, searchsorted is not autograd required.
https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/functions/utils.h#L63
I will fix this soon.

**Comment by glaringlee** [comment]
@mfkasim1 
This has been fixed in latest master branch. Please checkout the master branch, build it and try. Thanks.
