### ISSUE TITLE
[Pytorch 1.6.0] torch.atan2 of negative zeros returns invalid result

### ISSUE THREAD

**Issue by olibd** [pytorch/pytorch#45605]
## 🐛 Bug

Performing the element wise arctan of a Tensor with an element of 0.0 (or -0.0) and a second Tensor with an element of -0.0 at the same location will return a value of 3.1416 (or -3.1416) at that position. The error only happens when it is the second Tensor that contains a -0.0 value. 

## To Reproduce

1. `output = torch.atan2(torch.Tensor([0.0]), torch.Tensor([-0.0]))`
-> output will be a tensor with value [3.1416]

or 

2. `output = torch.atan2(torch.Tensor([-0.0]), torch.Tensor([-0.0]))`
-> output will be a tensor with value [-3.1416]

## Expected behavior

My understanding from the [forum](https://discuss.pytorch.org/t/tensor-output-as-negative-zero-and-not-positive-zero/16050) is that 0.0 and -0.0 should behave the same way. As such, we should expect them to be interchangeable and be handled by pytorch's functions the same way. Thus, the calculated value should be either be 0.0 or -0.0.

- atan2(-0.0, 0.0) behaves appropriately
- atan2(0.0, 0.0) behaves appropriately

## Environment

 - PyTorch Version: 1.6.0
 - OS: Ubuntu 18.04.5 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda 4.7.12
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: RTX 2080ti

**Comment by SsnL** [comment]
The current behavior is correct per IEEE 754 

![image](https://user-images.githubusercontent.com/5674597/94757444-396f2700-0368-11eb-803f-14dd6611d5c7.png)

**Comment by olibd** [comment]
Good to know, I wasn't aware of IEEE 754. Is there anyway to document this in Pytorch doc's? I understand IEEE 754 is standard, but from a regular user's perspective who isn't familiar with all the nitty gritty implementation details of floating-point arithmetic, this behavior is quite confusing.

**Comment by mruberry** [comment]
I don't think we want to change PyTorch's documentation to be redundant with the IEEE documentation. Maybe a brief note that our mathematical functions are expected to follow the standard would be helpful, but I'm not sure where it would live at this time. 

Closing this for now as I don't think there's much more we can do.
