### ISSUE TITLE
Visualizing Models, Data, and Training with TensorBoard - colab ipynb

### ISSUE THREAD

**Issue by data-RanDan** [pytorch/pytorch#45650]
## 📚 Documentation

Hi guys.
I saw that a colab ipynb  version of this tutorial was missing, 
so i made one.  Not sure where to add it.

https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html

**Comment by mariosasko** [comment]
Create a PR in the [pytorch/tutorials](https://github.com/pytorch/tutorials) repo.

**Comment by data-RanDan** [comment]
Thank you!
