### ISSUE TITLE
No dllexport before template specification function of caffe2-op

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#45657]
## 🐛 Bug

Some ops aren't exported for windows build
In these ops, C10_EXPORT_CAFFE2_OP_TO_C10_CUDA or C10_EXPORT_CAFFE2_OP_TO_C10_CPU is defined but there's no dllexport before the template specification function.

## To Reproduce

The root cause is same to the issue https://github.com/pytorch/pytorch/issues/41896

## Expected behavior

Those ops should be used in windows too.

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by Blackhex** [comment]
Closing as Caffe2 on Windows is out of support.
