### ISSUE TITLE
LSTM model conversion from Pytorch to ONNX

### ISSUE THREAD

**Issue by Nitya05** [pytorch/pytorch#45653]
## 🐛 Bug

I am trying to convert a very simple LSTM model from Pytorch to ONNX. Even after using a batch size of 1 and specifying h0, c0 inputs (as specified in the Pytorch docs), I am getting the following warning:

**UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
"or define the initial states (h0/c0) as inputs of the model. ")**

Because of this, I am unable to convert the onnx model to tensorflow.

## To Reproduce
Attaching the Pytorch code inorder to reproduce the warning:

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torch.onnx
import torchvision

torch.manual_seed(1)

lstm = nn.LSTM(3, 3, num_layers=1)
lstm.eval()

with torch.no_grad():
inputs = [torch.randn(1,3) for _ in range(5)] #make a sequence of length 5
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
h0 = torch.randn(1, 1, 3)
c0 = torch.randn(1, 1, 3)
out, (hn, cn) = lstm(inputs, (h0, c0))

input_names = [“input”, “h0”, “c0”]
output_names = [“output”, “hn”, “cn”]

torch.onnx.export(lstm, (inputs, (h0, c0)), “SimpleLSTM.onnx”, input_names=input_names, output_names=output_names)

1. Save this code in some file say lstm.py and run it.

## Expected behavior

Successful building of onnx model without the above mentioned warning.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.5.1-gpu
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): NA
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

The SimpleLSTM.onnx model obtained after running the above mentioned script can be converted to tensorflow using the following:

import onnx
from onnx_tf.backend import prepare
onnx_model = onnx.load("./SimpleLSTM.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph('./SimpleLSTM.pb')

Ideally, the obtained onnx model should be ported to .pb using the above code, but it fails with the following error:

tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(6, 12) dtype=float32> because it depends transitively on placeholder <tf.Operation 'Squeeze_1/60' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_1 (Split) <- Squeeze_1 (Squeeze) <- Squeeze_1/60 (Placeholder) 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by BowenBao** [comment]
hi @Nitya05 - Thanks for reporting. We will take a look to see if the warning message can be improved. For the repro looks like it is producing a valid ONNX model. You can verify it by running through ONNXRuntime.
```
    import onnxruntime
    sess = onnxruntime.InferenceSession('SimpleLSTM.onnx')
    print(out, hn, cn)
    print(sess.run(None, {'input': inputs.numpy(), 'h0':h0.numpy(), 'c0':c0.numpy()}))
```
it should produce the same results as PyTorch. Looks like the issue is with Tensorflow loading ONNX. Please open an issue there.

**Comment by Nitya05** [comment]
Thanks @BowenBao Bowen.

**Comment by mdlockyer** [comment]
I'm receiving the same warning as well. The exported model is indeed valid, and this seems to be a false alarm. Would be really nice to get rid of this though. Quite annoying.
