### ISSUE TITLE
The reproducibility note in `scatter_add_` documentation is misleading

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#45663]
## 📚 Documentation

The note erroneously suggests that scatter_add_ on CUDA is implemented via the cudnn backend and suggests setting a flag to make it non-deterministic. However, scatter_add_ is actually implemented natively and setting backends.cudnn.deterministic does not affect it at all.

![image](https://user-images.githubusercontent.com/5652049/94821724-ea5cdc80-03cf-11eb-80e8-a52316eacfdc.png)

cc @ngimel @jlin27 @mruberry

**Comment by zou3519** [comment]
NB: This might not be the only one. I see that `Tensor.index_add_` also mentions CuDNN, but iirc the cuda version isn't implemented via CuDNN.

**Comment by ngimel** [comment]
Fixed both in #45748
