### ISSUE TITLE
Exporting pointrend to ONNX 

### ISSUE THREAD

**Issue by jhagege** [pytorch/pytorch#45676]
Hi I don't succeed to export PointRend project from Detectron2 to ONNX.
See original issue there: https://github.com/facebookresearch/detectron2/issues/2086

Any recommendation to troubleshoot ?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
We have not explicitly tried it. It may be worth checking with the Detectron2 team. 
If you hit any specific issue, please open an issue with a repro. 
BTW, we have tested the object detection/segmentation models in torchvision repo (FasterRCNN, MaskRCNN, KeypointRCNN) and they should be exportable to ONNX. May be they can be useful to you.

**Comment by ousinkou** [comment]
@jhagege Have you solved this? Looking for help.

**Comment by jhagege** [comment]
Hi, last that I can remember it was not officially supported by the repository. 
Happy to hear if you find a solution :)

**Comment by thiagocrepaldi** [comment]
Hi, I have pushed a couple PRs to detectron2's repo, enabling ONNX export. Current master branch can export PointRend and https://github.com/facebookresearch/detectron2/pull/4413 is an example on how to do it
