### ISSUE TITLE
nn.InstanceNorm behavior is not consistent with batch size for corner case of inputs with spatial dimension = 1

### ISSUE THREAD

**Issue by ys-koshelev** [pytorch/pytorch#45687]
## 🐛 Bug
Instance norm computes statistics and normalizes tensor along its spatial dimensions. If tensor has just 1 element in spatial dimension, then the mean value is this element itself and variance computed by InstanceNorm layer is 0. In PyTorch realization, the value of normalized tensor will be silently computed as 0, since a small eps value is added to variance before division. 

The bug is that instance norm layer does not work silently and throws out an error about dimensions when batch size is 1 and dimensions are H, W= (1, 1). However, if batch size is > 1 and dimensions are the same H, W = (1, 1), it works fine. I do not think it should be any difference between this two cases, since in both statistics are computed on (1, 1)-sized tensor and for both cases normalization is ambiguous. 
## To Reproduce
```
import torch as th
import torch.nn as nn

layer = nn.InstanceNorm2d(3)
layer.eval()

layer(th.rand(1, 3, 2, 2)) # works fine - expected 
layer(th.rand(2, 3, 1, 1)) # works fine - expected for silent behavior
layer(th.rand(1, 3, 1, 1)) # error - not expected for silent behavior
```

Stack trace:
> ValueError                                Traceback (most recent call last)
> <ipython-input-51-8deccc1ffea0> in <module>()
>       8     print(layer(th.rand(2, 3, 1, 1))) # works fine
>       9 layer(th.rand(1, 3, 2, 2)) # works fine
> ---> 10 layer(th.rand(1, 3, 1, 1)) # error in eval mode
> 
> ~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>     720             result = self._slow_forward(*input, **kwargs)
>     721         else:
> --> 722             result = self.forward(*input, **kwargs)
>     723         for hook in itertools.chain(
>     724                 _global_forward_hooks.values(),
> 
> ~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/instancenorm.py in forward(self, input)
>      55         return F.instance_norm(
>      56             input, self.running_mean, self.running_var, self.weight, self.bias,
> ---> 57             self.training or not self.track_running_stats, self.momentum, self.eps)
>      58 
>      59 
> 
> ~/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py in instance_norm(input, running_mean, running_var, weight, bias, use_input_stats, momentum, eps)
>    2033                 running_var=running_var, weight=weight, bias=bias,
>    2034                 use_input_stats=use_input_stats, momentum=momentum, eps=eps)
> -> 2035     _verify_batch_size(input.size())
>    2036     return torch.instance_norm(
>    2037         input, weight, bias, running_mean, running_var,
> 
> ~/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py in _verify_batch_size(size)
>    1993         size_prods *= size[i + 2]
>    1994     if size_prods == 1:
> -> 1995         raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
>    1996 
>    1997 
> 
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 3, 1, 1])

## Expected behavior
If silent behavior is the case, then evaluating InstanceNorm layer on tensor with batch size 1 and spatial size 1 should not throw the error, especially in eval mode. Solution is simple: `_verify_batch_size(input.size())` call should be excluded from `nn.functional.instance_norm()`, since InstanceNorm layer has nothing about batch size. 

If silent behavior is not the case, both should throw out an error about dimensions. Error text should be reconsidered, since it tells about training mode, even when layer stays in eval mode.  

## Environment
 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed PyTorch: installed through pip
 - Build command you used: `pip install torch torchvision`
 - Python version: 3.6.4
 - CUDA/cuDNN version: 10.2

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry

**Comment by mrshenli** [comment]
Does the suggested change look OK to you? @SsnL @gchanan

**Comment by mruberry** [comment]
Thank you for filing this issue, @ys-koshelev, I agree this behavior seems odd.

The error comes from here:

https://github.com/pytorch/pytorch/blob/7726754e706d886ae37b529c47487e46150a58f1/torch/nn/functional.py#L2022

Although we have similar errors elsewhere, too:

https://github.com/pytorch/pytorch/blob/b167402e2e66a663cd9913885552929b4c045ffa/torch/nn/modules/_functions.py#L34

https://github.com/pytorch/pytorch/blob/3924c55f4c7b15c37c11a666eeccf40498d7bc84/torch/csrc/api/include/torch/nn/functional/batchnorm.h#L26

I don't know what the correct change to this behavior is off-hand, but I would like to see a proposal with an argument that covers each of these sites where errors like this are generated before continuing. That is, I'd like to be sure we're not just solving an instance of this issue, and we think carefully about the design of these errors.

**Comment by ptrblck** [comment]
> However, if batch size is > 1 and dimensions are the same H, W = (1, 1), it works fine. I do not think it should be any difference between this two cases, since in both statistics are computed on (1, 1)-sized tensor and for both cases normalization is ambiguous.

It doesn't raise an error, but corrupts the running stats in this case.
Related issue: https://github.com/pytorch/pytorch/issues/19250#issuecomment-724483925

Cross-posting the code:
```python
norm = nn.InstanceNorm2d(3, track_running_stats=True)
print(norm.running_mean)
> tensor([0., 0., 0.])

print(norm.running_var)
> tensor([1., 1., 1.])

x = torch.randn(8, 3, 1, 1)
out = norm(x)
print(out)
> tensor([[[[0.]],

           [[0.]],

           [[0.]]],
            ...

print(norm.running_mean)
> tensor([ 0.0194, -0.0310, -0.0516])

print(norm.running_var)
> tensor([nan, nan, nan])
```

**Comment by mruberry** [comment]
Updating based on @ptrblck's comment, as this now appears to be a silent correctness issue. Marking for re-triage.

**Comment by mattip** [comment]
Here is a beginning of an analysis, I could not hit the code in the second and third lines @mruberry pointed to via tests. As pointed out already, the reproducer at the top of the issue hits `_verify_batch_size` where the third variant emits the error.

The line from `SyncBatchNorm.forward` (`pytorch/torch/nn/modules/_functions.py`), is only used in `torch.nn.parallel.DistributedDataParallel`. Confusingly, there is another `SyncBatchNorm` class in `nn.modules.batchnorm`, which calls the former `SyncBatchNorm`'s `apply`. 
A `pdb` before the line in `SyncBatchNorm.forward` was not hit at all when running `python test/run_test.py -i distributed/test_c10d`, so I am not sure what tests should be hitting that code path.

When trying to analyze the third check (in `batchnorm.h`) a gdb breakpoint was not hit at all in `torch::nn:functional::detail::Tensor::batch_norm` when running `gdb --args python test/run_test.py -i test_quantization`.

Which tests are expected to reach those functions? 

--------------------------

The silent corruption of `norm.running_var` in the comment from #19250 comes from [calculating `unbiased_var = var_sum / (n - 1);`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Normalization.cpp#L263) when `n == 1`. It should check first that `n > 1`. Where would an appropriate place be to add a test for this?

**Comment by mattip** [comment]
I think the later comment about `running_var` is not related to the original issue: that `layer(tensor.rand(1, x, 1, 1,))` fails where `layer(tensor(rand(1, x, 2, 1))` or `layer(rand(2, x, 1, 1))` succeed.

**Comment by jbschlosser** [comment]
My thoughts are that the `_verify_batch_size` check in `F.instance_norm` is the wrong check to do.
https://github.com/pytorch/pytorch/blob/a39b1c42c184916ab0798fde7b23967702d003e9/torch/nn/functional.py#L2097-L2111

The logic multiplies the non-channel dims and checks if the result is 1; if so, it is considered invalid because the variance will be undefined.

While this is correct for `batch_norm`, it is not valid for `instance_norm`, since providing a batch size > 1 passes the check and doesn't avoid variance computation over a single element.

Imo the proper fix is to make the check in `F.instance_norm` more restrictive: it should iterate over the spatial dims and throw an error if that result is 1.
