### ISSUE TITLE
Anyone working on python type stubs?

### ISSUE THREAD

**Issue by MInner** [pytorch/pytorch#4568]
Type signatures of many functions are quite unusual for Python world (lots of method 'overloading', etc.) and it makes IDEs like pycharm fire lots of false positive errors. 

I wonder if that might be possible to generate function signature subs [[1]](
https://www.python.org/dev/peps/pep-3107/) [[2]](https://www.python.org/dev/peps/pep-0484/#stub-files) from docs directly? Is anyone else interested in it?

**Comment by ezyang** [comment]
I think this is a great idea, and a logical extension of our code generation strategy in ATen already.

**Comment by jekbradbury** [comment]
x-ref https://github.com/allenai/allennlp/pull/374

**Comment by t-vi** [comment]
#12500 will do this.

**Comment by zou3519** [comment]
#12500 was merged!
