### ISSUE TITLE
Allowing MSELoss in torch.nn to be twice differentiable

### ISSUE THREAD

**Issue by benvcutilli** [pytorch/pytorch#4571]
I would like to have MSELoss() allow two backward passes (the second of which would need the second derivative of MSELoss()). Apparently this isn't allowed (traceback below). Scouring the codebase shows me no reason why it would be prevented, at least mathematically.

```Traceback (most recent call last):
  File "<REDACTED>", line 112, in <module>
    <REDACTED>
  File "<REDACTED>/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "<REDACTED>/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "<REDACTED>/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "<REDACTED>/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py", line 71, in backward_cls_backward
    return double_backwards_fn(ctx, *grad_params)
  File "<REDACTED>/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/auto.py", line 316, in default_double_backwards_fn
    raise ValueError(class_name + " can only be differentiated once.")
ValueError: MSELoss can only be differentiated once.

**Comment by benvcutilli** [comment]
Apparently there is no entry for MSELoss in torch/nn/_functions/thnn/auto_double_backwards.py. In theory this wouldn't be necessary if autograd were keeping track of the graph, though.

**Comment by gchanan** [comment]
This was implemented in version 0.3.

**Comment by benvcutilli** [comment]
OK, then Soumith's Anaconda channel has not been updated since 0.1.12, and through `conda`'s default channel, has only been updated to 0.2.something. What's the deal?

**Comment by soumith** [comment]
always follow the commands on our website http://pytorch.org to get the latest version of pytorch.

Also, the default anaconda channel has 0.3.0 https://anaconda.org/search?q=pytorch
Maybe you have to update your anaconda.

**Comment by benvcutilli** [comment]
Well, nothing much seems to have changed after updating conda. After the update, as far as what conda tells me what packages will be updated, pytorch or torchvision do not seem to want to be updated but others do. I can't really do those updates now, though, as I am running stuff on the current build of pytorch, so I'll ask later if the problem persists once I can upgrade those other packages, I guess. *I couldn't see any update procedures on pytorch.org, just installation ones.*

**Comment by benvcutilli** [comment]
Ah, NVM, you guys changed the channel. I got the package when it was on the soumith channel. I still don't know why conda is not telling me that an update on the pytorch channel is available.
