### ISSUE TITLE
Add wheels for Python 3.9

### ISSUE THREAD

**Issue by michael-k** [pytorch/pytorch#45731]
## 🚀 Feature

Run tests against Python 3.9, add the trove classifier and provide wheels.

## Motivation

Python 3.9.0 final is expected on Monday, 2020-10-05, see https://www.python.org/dev/peps/pep-0596/#schedule

## Pitch

I want everybody who's switching to Python 3.9 be able to install torch via a wheel from PyPI or https://download.pytorch.org/whl/torch_stable.html.

## Alternatives

Building from source and uploading the resulting wheel to our internal PyPI mirror.

## Additional context

n/a

cc @ezyang @seemethere @malfet @walterddr

**Comment by colesbury** [comment]
@seemethere are we targeting Python 3.9 for PyTorch 1.7 (or subsequent PyTorch releases)?

**Comment by malfet** [comment]
@colesbury for subsequent yes, but not for 1.7

**Comment by seemethere** [comment]
We're currently targeting a Python 3.9 release for PyTorch 1.7.1 (whose release date remains TBD, but will be before the end of the year most likely)

**Comment by CamiloMM** [comment]
As someone who thought, "hey, maybe it's time to learn Python, now that the 2.7 decade+ of incompatibilities is probably over"...

Well I'm disappointed but not surprised. I'm glad the current version of one of the most popular programming languages will *most likely* be supported by one of the most notable libraries *by the end of the year*.

Maybe I'm overreacting but I wish it wasn't like this. I don't need 10 local versions of `node`, Mono, `php` or... *anything, really* for every project.

/rant

**Comment by seemethere** [comment]
Update for everyone here, we've merged the code in to do nightly binaries for Python 3.9 but are currently hung up on uploading those binaries due to https://github.com/pytorch/pytorch/issues/47776

**Comment by rgommers** [comment]
Let's close this, it has been complete for a while (1.7.1 has wheels and conda packages for Python 3.9).
