### ISSUE TITLE
Request for conjugate transposed triangular solve

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#45734]
## 🚀 Feature
`torch.triangular_solve` should have an option to solve A^H x = b, where "^H" is the conjugate transpose operation.

## Motivation

Now that PyTorch is expanding the complex number support, linear algebra methods that have transposed variants usually also have conjugate transpose variants for complex inputs. That should be supported as well.

## Additional context

[SciPy's triangular_solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html) has this option and the underlying BLAS/LAPACK libraries allow that (with `trans='C'`).

cc @ezyang @anjali411 @dylanbespalko @mruberry @vincentqb @vishwakftw @jianyuh @nikitaved @pearu

**Comment by mruberry** [comment]
Thanks for the suggestion, @IvanYashchuk.

Would we want to update torch.triangular_solve or implement torch.linalg.solve_triangular with a SciPy-compatible interface?

**Comment by ezyang** [comment]
With https://github.com/pytorch/pytorch/pull/44799 `torch.triangular_solve(input, A.H)` would be an efficient way to do conjugate transposed triangular solve (as `A.H` would be computed lazily). It might still be a good idea to provide the kwarg version anyway though for discoverability.

**Comment by anjali411** [comment]
Currently in PyTorch, we have a kwarg `transpose` as opposed to the `trans` kwarg in SciPy. I think
1. For `torch.triangular_solve`, we should perform hermitian operation when transpose is set to `True` and clearly document that.
2. For `torch.linalg.solve_triangular`, we should add a trans kwarg similar to SciPy which will give the users the option to select if they want to perform transpose (`T`) , conjugate transpose (hermitian / `H`) or neither H nor T.

**Comment by mruberry** [comment]
> 2. For `torch.linalg.solve_triangular`, we should add a trans kwarg similar to SciPy which will give the users the option to select if they want to perform transpose (`T`) , conjugate transpose (hermitian / `C`) or neither `C` nor `T`. I personally prefer `H` over `C`, but to be consistent with SciPy we should probably stick with `C`.

We could probably support both H and C and it'd be fine.

**Comment by Lezcano** [comment]
Even better, `linalg.triangular_solve` does all this automatically just looking at the strides of the input tensor and it gets rid of this annoying parameter.
