### ISSUE TITLE
DISABLED test_functional_no_debug (quantization.test_quantize_fx.TestQuantizeFx)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#45761]
https://app.circleci.com/pipelines/github/pytorch/pytorch/222704/workflows/18db8ff8-9ef9-4bc0-8f54-ef62c17f93f0/jobs/7969992/steps

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Earliest occurrence appears to be https://app.circleci.com/pipelines/github/pytorch/pytorch/222489/workflows/8823f781-c8c6-4344-b78b-ca6a534966d1/jobs/7957047

Culprit commit is likely https://github.com/pytorch/pytorch/pull/45292

cc @jerryzh168

**Comment by malfet** [comment]
Hmm, I've found it's twin brother https://github.com/pytorch/pytorch/issues/45809
