### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by suke27** [pytorch/pytorch#4576]
Hi
when I run test program in pytorch, I found the memory seems can not free completely
my test program as below
        self.model.eval()
        for i in range(0,img_cnt) :
                img = misc.imread(load_name)
                input = img
                #prepare data
                input = self.prepareData(input, target, volatile=True)
                output = self.model(input)
I found for when I test 1920x1080 images, if I run it one by  one it is ok. if I test it together, then will warns me out of memory.
anyone know how can I free memory manually

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
