### ISSUE TITLE
Proposal for stricter backward compatibility in function checks

### ISSUE THREAD

**Issue by raziel** [pytorch/pytorch#45784]
Proposal for stricter backward compatibility in function schema checks

Currently, there is a backwards compatibility check for the python API which follows python rules. This can be an issue for the C++ API, since the python rules are too permissive for C++ backward compatibility, where only positional arguments (no named args) are available.

This proposal is for going from the more permissive Python-derived rules (see Current backwards-compatibility) to new stricter C++ derived rules (see New backwards-compatibility).

**Current backwards-compatibility**
A function is backwards compatible if:

- The function's structure of old and new match (e.g. name, overload name, etc.).
- The new function has a backward compatible argument for every positional argument in the old function.
- All new positional arguments (not present in old) appear afterwards (i.e. appended to the list of positional arguments) and either match a kwarg by name and compatibility (i.e. old kwarg becoming positional) or provides a default value.
-- E.g. `f_new(a, b, c=1) => f_old(a, b); f_new(a, c=1, *, b) => f_old(a, *, b); f_new(a, b, *, c) => f_old(a, *, b, c)`
- The new function has a matching backward compatible kwarg for every kwarg in the old function, and all the kwargs in the old function have a matching kwarg or positional argument (per the rule above).
- All new kwargs (not present in old) provide a default value.
-- E.g. `f_new(a, b, *, c) => f_old(a, *, b, c); f_new(a, *, c, b) => f_old(a, *, b, c); f_new(a, *, b, c, d=1) => f_old(a, *, b, c)`

**New backwards-compatibility**
A function is backwards compatible if:

- [Function structure] The new schema's name, overload-name, varargs, and return arity are the same.
- [Output Narrowing] The new schema's output type must be the same class or inherit from the old schema's output type.
- [Argument count] The new schema must have at least as many arguments as the old schema (considering the list of positional and kwargs).
- [Arg Compatibility] Every argument in the old schema has a corresponding argument in the new schema that:
-- is at the same position.
-- has the same name.
-- is either positional, or kwarg and the old argument was kwarg.
-- has the same type, or the old argument's type inherits from the new argument's type.
- E.g.
- OK    f_new(a, b, c=1) => f_old(a, b)
- NOK   f_new(a, c=1, *, b) => f_old(a, *, b)
- OK    f_new(a, b, *, c) => f_old(a, *, b, c)
- NOK   f_new(a, *, b, c) -> f_old(a, b, *, c)
- NOK   f_new(a, *, c, b) => f_old(a, *, b, c)
- OK    f_new(a, *, b, c, d=1) => f_old(a, *, b, c)

cc @gmagogsfm

**Comment by dzhulgakov** [comment]
cc @suo @mruberry @houseroad

**Comment by raziel** [comment]
Backwards compatibility logic has been updated as described.
