### ISSUE TITLE
Handling singular matrices when backprop

### ISSUE THREAD

**Issue by NLPJCL** [pytorch/pytorch#45805]
Hey guys!

I am currently running into the following problem:
after  loss.backward() 
I’ll get the
RuntimeError: inverse_cuda: For batch 25: U(16,16) is zero, singular U. 
I used the determinant of the matrix to compute the loss function.I think it might have something to do with it

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
