### ISSUE TITLE
DISABLED test_functional_debug (quantization.test_quantize_fx.TestQuantizeFx)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#45809]
`quantization.test_quantize_fx.TestQuantizeFx.test_functional_debug` randomly fails parallel_tbb_test

Here are some recent examples:
https://app.circleci.com/pipelines/github/pytorch/pytorch/222085/workflows/3e771f4e-71f2-409d-9d0d-fe41a302f8cb/jobs/7933871
https://app.circleci.com/pipelines/github/pytorch/pytorch/222489/workflows/8823f781-c8c6-4344-b78b-ca6a534966d1/jobs/7957047
https://app.circleci.com/pipelines/github/pytorch/pytorch/222593/workflows/f64402f3-680f-43af-a421-640e1b8d66c9/jobs/7963114
https://app.circleci.com/pipelines/github/pytorch/pytorch/222878/workflows/f6764931-dfc0-4b46-a59d-f9b6fb661d47/jobs/7981308
And so it goes

cc @ezyang @gchanan @zou3519 @seemethere @malfet @walterddr @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
It should be resolved now. How do I enable this again?
