### ISSUE TITLE
Is (or will) TF32 supported on Pytorch?

### ISSUE THREAD

**Issue by kentaroy47** [pytorch/pytorch#45827]
## ❓ Questions and Help

TensorFloat32 was added in nVidiaA100 (and RTX30xx), which should be fast as fp16 but accurate as fp32s.

Is this feature supported with pytorch?

I noticed that this feature is available in CuPy v8.0.0, so I was interested in the pytorch support as well.
https://github.com/cupy/cupy/releases

**Comment by mruberry** [comment]
Yes, TensorFloat32 will be supported in the PyTorch 1.7 release.
