### ISSUE TITLE
Uninitialised buffers don't show up in `state_dict()`

### ISSUE THREAD

**Issue by mil-ad** [pytorch/pytorch#45834]
## 🐛 Bug

I noticed that _uninitialised_ module buffers don't show up in what `state_dict()` returns. Is this a bug or a feature?

This makes loading from checkpoints a bit difficult.

## To Reproduce

```py
import torch.nn as nn
import torch


class MyModule(nn.Module):
    def __init__(self):
        super().__init__()

        self.register_buffer("some_state", None)


module_original = MyModule()
module_original.some_state = torch.tensor(42)

# later when loading checkpoint
module_copy = MyModule()
module_copy.load_state_dict(module_original.state_dict())
```

Fails with:

```
Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    module_copy.load_state_dict(module_original.state_dict())
  File "/home/milad/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MyModule:
        Unexpected key(s) in state_dict: "some_state".
```

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.18.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660 SUPER
Nvidia driver version: 440.100
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-ignite==0.4.0.post1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1           py37hbc911f0_0  
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-ignite            0.4.0.post1              pypi_0    pypi
[conda] torchvision               0.7.0                py37_cu102    pytorch

cc @jlin27 @mruberry @albanD

**Comment by VitalyFedyunin** [comment]
Not sure if we want 
1) Error out nicely
OR 2) Support such cases

**Comment by albanD** [comment]
Loading an initialized buffer into an uninitialized one should definitely work.

Actuall from checking the code, isn't the state properly loaded? I think this is just our code that checks for extra keys that is not behaving properly, by the loading code itself is doing the right thing.

**Comment by mil-ad** [comment]
Yes I think the state would be loaded properly had `state_dict()` returned the unintialized parameters. 

But `_save_to_state_dict()`, which is what `state_dict()` calls, very explicitly ignores those:

```py
for name, buf in self._buffers.items():
    if buf is not None and name not in self._non_persistent_buffers_set:
        destination[prefix + name] = buf if keep_vars else buf.detach()
```

**Comment by albanD** [comment]
We don't actually use `.state_dict()` in the loading code. And we explicitly filter out the parameters that are current None.
Keep in mind that `mod.load_state_dict(d)` loads into `mod` inplace. And so if a parameter of mod is empty, nothing can be loaded into it!

**Comment by albanD** [comment]
> Basically what's the point of allowing None buffers if they're not handled properly?

They mostly allow to "reserve" names on the class IIRC.

While I do agree that it would make sense to allow loading a non-None param into a None param when looking only at the loading, It might create some subtle issues.
For example wrt the interaction with the optimizer where, if the optimizer is created before the checkpoint is loaded, the new param won't be registered there (contrary to all the other weights).
Or question about where to put this new param? When loading a state dict, we load just the value and keep the current device/dtype of the current param. But if it is None, there is no such information and the user can end up with weird errors due to device or dtype missmatch in the forward.

**Comment by jbschlosser** [comment]
The fact that buffers registered with `register_buffer('name', None)` don't show up in the `state_dict` should be more clearly documented in the `register_buffer()` docs (and analogously for `register_parameter()`).
