### ISSUE TITLE
Error when getting tensors from multiprocessing.Queue

### ISSUE THREAD

**Issue by BillHuang2001** [pytorch/pytorch#45831]
## 🐛 Bug
When using multiprocessing, put a tensor into multiprocessing.Queue, and you can't get that tensor from the queue if the function has ended.

## To Reproduce

1. run the following code

``` Python
import torch
import torch.multiprocessing as mp
import time

def func_return_list(queue):
    queue.put([[0,0],[0,0]])

def func(queue):
    queue.put( torch.zeros((2,2)) )
    time.sleep(1)

def func_with_bug(queue):
    queue.put( torch.zeros((2,2)) )

queue = mp.Queue()

# a function that puts a python list
p1 = mp.Process(target=func_return_list, args=(queue, ))
p1.start()
print(queue.get())
p1.join()

# a function that puts a pytorch tensor and sleeps for 1 sec
p2 = mp.Process(target=func, args=(queue, ))
p2.start()
print(queue.get())
p2.join()

# a function that puts a pytorch tensor
p3 = mp.Process(target=func_with_bug, args=(queue, ))
p3.start()
print(queue.get())
p3.join()
```
## Expected behavior
`func_return_list` and `func` work just fine
`func_with_bug` can put the tensor into the queue, but the program encounters error when calling queue.get()

```Shell
[[0, 0], [0, 0]]
tensor([[0., 0.],
        [0., 0.]])
Traceback (most recent call last):
  File "/**(hidden)**/bug_report.py", line 32, in <module>
    print(queue.get())
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/usr/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```
## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.18.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.6.0
[conda] Could not collect
## Additional context
One might also encounter 'EOFError' or 'FileNotFoundError' if trying to get a list of tensors or tuple of tensors from the queue.
It seems python's gc has deleted the tensor object before I can get it from the queue.

**Comment by VitalyFedyunin** [comment]
It is best practice to use Events and keep Producer process running until all Queue is consumed. Alternatively you can pass tensor as binary and unserialize it on consumer end.
