### ISSUE TITLE
Network-size Dependant Illegal Instruction

### ISSUE THREAD

**Issue by harrybraviner** [pytorch/pytorch#45838]
## 🐛 Bug

Pytorch crashes during the `forward` operation of a network, printing no stack trace, only 'Illegal instruction'. This is originally happened in the tutorial linked here: https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py

I expect this was due to my old AMD CPU (Phenom II X6 1055T). Compiling pytorch locally (version 1.8.0a0+2ab74a4) results in that tutorial working. However, the following tutorial (https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py) still produces the 'Illegal instruction' message. This appears to be due to the network size.

## To Reproduce

1. Use an old CPU (I'm not really sure what features need to be missing - I have an AMD Phenom II X6 1055T), compile pytorch from scratch.
1. Run the code below. It should print a tensor.
1. Change the size of at least one of the convolution kernels from 3 to 5. It should now print 'Illegal Instruction.'

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # 1 input channel, 6 output channels, 3x3 convolution
        self.conv1 = nn.Conv2d(3, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # Fully connexted layers: y = Wx + b
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Max pooling over a 2x2 window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
        
    def num_flat_features(self, x):
        size = x.size()[1:]  # Drop the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

input = torch.randn(1, 3, 32, 32)
out = net(input)
print(out)
```

## Expected behavior

I expected the 'Illegal Instruction' message to no longer happen with a locally compiled pytorch.

## Environment

Collecting environment information...
PyTorch version: 1.8.0a0+2ab74a4
Is debug build: True
CUDA used to build PyTorch: 10.0
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 9.12 (stretch) (x86_64)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1050 Ti
GPU 1: GeForce GT 730

Nvidia driver version: 410.73
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.8.0a0
[pip3] torchvision==0.8.0a0+588f7ae
[conda] blas                      1.0                         mkl  
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1           py37hbc911f0_0  
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] torch                     1.8.0a0                  pypi_0    pypi
[conda] torchvision               0.8.0a0+588f7ae          pypi_0    pypi

cc @VitalyFedyunin @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by VitalyFedyunin** [comment]
It is very hard to reproduce, could you please help us to isolate an issue and try this code with MKLDNN disabled.

**Comment by harrybraviner** [comment]
Sure - that requires me to recompile, right?

**Comment by harrybraviner** [comment]
Ok, I have recompiled with `USE_MKLDNN=0`, and the problem is now gone! At least, the example code from https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py runs fine, and my examples with changing the kernel size now produces the expected error about size mismatches, not 'Illegal Instruction'.

This certainly works as a workaround for me for now - if you want me to try other stuff to help identify the underlying reason, feel free to ask.

**Comment by VitalyFedyunin** [comment]
CC @mingfeima

**Comment by pinzhenx** [comment]
cc @vpirogov

**Comment by tprimak** [comment]
Minimal supported instruction set for oneDNN is SSE4.1, while Phenom II core has only x86, x86-64, MMX, SSE, SSE2, SSE3, SSE4a.

**Comment by pinzhenx** [comment]
@harrybraviner could you try this patch please?

**Comment by harrybraviner** [comment]
@pinzhenx I installed that (I assume you meant to me not to use `USE_MKLDNN=0`, so I did not). But it still gives the same 'Illegal Instruction' error, under the same circumstances.

**Comment by CaoZhongZ** [comment]
> @pinzhenx I installed that (I assume you meant to me not to use `USE_MKLDNN=0`, so I did not). But it still gives the same 'Illegal Instruction' error, under the same circumstances.

A rather old CPU, K10 architecture. As tprimak said, oneDNN requires SSE4.1 or little acceleration you'll get. Other acceleration library used by PyTorch might implicitly introduce instruction version over SSE4.1.

If you really want make Pytorch work on K10 machine, try USE_NATIVE_ARCH=ON option.
