### ISSUE TITLE
[cpp-extension] build fails for extra_compile_args with only "cxx" or "nvcc" key

### ISSUE THREAD

**Issue by asnt** [pytorch/pytorch#45835]
## 🐛 Bug

These both fail:
`CUDAExtension(..., extra_compile_args={"cxx": [...]})`
`CUDAExtension(..., extra_compile_args={"nvcc": [...]})`
I.e. when passing only one of the `cxx` or `nvcc` targets (even an empty list).

It works when both are passed, possibly with an empty argument list, e.g.
`CUDAExtension(..., extra_compile_args={"cxx": [...], "nvcc": []})`

## To Reproduce

Use the following `setup.py` in https://github.com/pytorch/extension-cpp
```python
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='lltm_cuda',
    ext_modules=[
        CUDAExtension(
            'lltm_cuda',
            ['lltm_cuda.cpp', 'lltm_cuda_kernel.cu'],
            extra_compile_args={
                'cxx': [],
                # 'nvcc': [],
            }),
    ],
    cmdclass={
        'build_ext': BuildExtension
    },
)
```

## Expected behavior

The compilation should succeed with either of
`CUDAExtension(..., extra_compile_args={"cxx": [...]})`
`CUDAExtension(..., extra_compile_args={"nvcc": [...]})`

## Additional context

Suggestion for a fix: Just before [this line](https://github.com/pytorch/pytorch/blob/f65ab89eddc5cf449b94fdbddb4715fb8f57d2d6/torch/utils/cpp_extension.py#L351), if `extension.extra_compile_args` is a dict (it could be a list, in which case the issue does not apply), ensure it contains both `cxx` and `nvcc` keys (initialise with empty lists if necessary).

EDIT: Tentative fix in https://github.com/asnt/pytorch/tree/fix-45835-default_extra_compile_args

cc @yf225 @glaringlee

**Comment by albanD** [comment]
Hi,

If this is a simple oversight in the argument handling as your proposed branch seems to indicate, can you send a PR to fix this please?

**Comment by glaringlee** [comment]
@asnt Please submit ur PR, thanks.
