### ISSUE TITLE
Need to help to convert prob_label = torch.gather(output_label, 1, y.unsqueeze(1)) to C++ please 

### ISSUE THREAD

**Issue by Chen0729** [pytorch/pytorch#45841]
Hi, All

I need to convert prob_label = torch.gather(output_label, 1, y.unsqueeze(1))  in pytorch to C++ libtorch

I write

torch::Tensor prob_label = torch::gather(torch::Tensor output_label, 1, y.unsqueeze(1));
It gives me error under output_label that
Expected "(" for function-style cast or type construction.

Any suggestions are appreciated. 

Thanks,

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
