### ISSUE TITLE
What option(USE_NNAPI "Use NNAPI") is used for?

### ISSUE THREAD

**Issue by peter197321** [pytorch/pytorch#45856]
Hello all,

there is an `option(USE_NNAPI "Use NNAPI" OFF)` within [CMakeLists.txt#L179](https://github.com/pytorch/pytorch/blob/cf48872d28f945d47793f63e19c54dd15bf580f7/CMakeLists.txt#L179)   
I'd like to know if this option is on, what is in this case enabled?
I do have a device with NN-API driver - is this help to use this device NN-API backend?

Thank you.

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
