### ISSUE TITLE
torch.jit.script segfault

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#45860]
## 🐛 Bug

Segfault on master (built Oct 4) with the following code (which is perhaps not expected to be scriptable):
```python
from typing import Any
import torch

class A:
    def __init__(self, t):
        self.t = t
    @staticmethod
    def f(a: torch.Tensor):
        return A(a + 1)

class B(A):
    def __init__(self, t):
        self.t = t + 10
    @staticmethod
    def f(a: torch.Tensor):
        return A(a + 1)

x = A(torch.tensor([3]))

def fun(x: Any):
    if isinstance(x, A):
        return A.f(x.t)
    else:
        return B.f(x.t)

print(torch.__version__)
sc = torch.jit.script(fun)
```

cc @ezyang @gchanan @zou3519 @gmagogsfm

**Comment by gmagogsfm** [comment]
I can repro, taking a look at it now.

**Comment by gmagogsfm** [comment]
Took an initial look, error is coming from an `try_ann_to_type` call and deep in pybind. Assigning to @SplitInfinity, who knows more about scripting classes.

**Comment by SplitInfinity** [comment]
The issue here is that `B` extends `A`, and so in `try_ann_to_type`, TorchScript sees a `__torch_script_class__` attribute on `B` that was attached to `A`, thinks that the class has already been scripted, and tries to look up the JIT type by name in the compilation unit type registry.

**Comment by gchanan** [comment]
is this fixed?

**Comment by SplitInfinity** [comment]
#45940 is waiting for review with all comments addressed and all tests passing.
