### ISSUE TITLE
CPP test errors are not reported as failures

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#45864]
Have a look at those two for example:
https://app.circleci.com/pipelines/github/pytorch/pytorch/222634/workflows/005e1922-33bf-43e0-8e7f-d14cfae47fed/jobs/7964572
https://app.circleci.com/pipelines/github/pytorch/pytorch/222634/workflows/005e1922-33bf-43e0-8e7f-d14cfae47fed/jobs/7964565

TestAtomicOps.TestAtomicMul is failed, but run is considered successful

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by ezyang** [comment]
Last time: #25145
