### ISSUE TITLE
Convert multiple sequential of model into PyTorch script

### ISSUE THREAD

**Issue by PythonImageDeveloper** [pytorch/pytorch#45863]
Hi,
I have a model consist of multiple part such as include multi sequential class, and I want to use the model on mobile devices.
First I want to  use **jit.trace** then **jit.script,** In your opinion, When I pass whole of model into **jit.trace** I get an error like you have to pass tensor not dictionary object, In my opinion, I have to pass each of sequential model parts individuality into **jit.trace**, right?

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
