### ISSUE TITLE
PyTorch 1.6.0 built with an old CPU (without AVX/SSE4 instructions) cannot be imported

### ISSUE THREAD

**Issue by maximtrp** [pytorch/pytorch#45894]
## 🐛 Bug

PyTorch 1.6.0 is imported with a segmentation fault when built from source on a computer with an old CPU (not supporting AVX/AVX2/SSE4 instructions).

## To Reproduce

1. Run `python setup.py build` on a computer with an old CPU (such as AMD Athlon II X4).
2. `python -c import torch`
3. ???
4. Segmentation fault!

Log of `gdb -ex r --args python -c "import torch"`: https://pastebin.com/RuXGLdLE
Output of `cat /proc/cpuinfo`: https://pastebin.com/EgPSEGS0

## Expected behavior

Successful build and package import.

### When `torch` is installed

```
$ python collect_env.py
```
returns `Illegal instruction (core dumped)`.

### When `torch` is not installed

```
$ python collect_env.py
```

exits with the error:
```
Collecting environment information...
Traceback (most recent call last):
  File "collect_env.py", line 429, in <module>
    main()
  File "collect_env.py", line 424, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 419, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 276, in get_env_info
    if torch.version.hip is None:  # cuda version
NameError: name 'torch' is not defined
```

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `makepkg -s`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: `01:00.0 VGA compatible controller: NVIDIA Corporation TU117 [GeForce GTX 1650] (rev a1)`
 - Any other relevant information:

## Additional context

I'm building `pytorch` using ArchLinux PKGBUILD file from this repo: https://github.com/archlinux/svntogit-community/tree/packages/python-pytorch/trunk

As can be seen, it contains a section with a x86_64 preconfiguration (meant to turn off any optimizations) and this [patch](https://github.com/archlinux/svntogit-community/blob/packages/python-pytorch/trunk/disable_non_x86_64.patch) to disable AVX/AVX2/etc.

**Comment by albanD** [comment]
Hi,

This is a knows issue I'm afraid: https://github.com/pytorch/pytorch/issues/43300
We fixed it in master but it is harder to update the already released packages.

Closing as duplicate, we can follow on discussions in the other issue.
