### ISSUE TITLE
Binary builds for wheels are failing, undefined reference to `mkl_lapack_claed0'

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#45922]
## 🐛 Bug

Binary builds for wheels and libtorch (`master` and `nightly`) are currently failing with: 
```
/pytorch/build/lib/libtorch_cuda.so: undefined reference to `mkl_lapack_claed0'
/pytorch/build/lib/libtorch_cuda.so: undefined reference to `mkl_lapack_cunmql'
/pytorch/build/lib/libtorch_cuda.so: undefined reference to `mkl_lapack_zlaed0'
/pytorch/build/lib/libtorch_cuda.so: undefined reference to `mkl_lapack_zunmql'
```

Link to logs:
https://app.circleci.com/pipelines/github/pytorch/pytorch/222193/workflows/bfd8b4c8-ff7c-4ca7-92bb-7091415c487e/jobs/7942742

I've narrowed down the list of commits to when this started to: 77cd8e006b92a8faf90a1ffcfe601860df587726b

An attempt to do a simple revert of that commit failed to garner results: https://github.com/pytorch/pytorch/pull/45916

cc @ezyang @gchanan @zou3519 @malfet @seemethere @walterddr

**Comment by IvanYashchuk** [comment]
Here is the output of `nm /opt/intel/lib/libmkl_core.a  --line-numbers --print-file-name | grep -e "mkl_lapack_claed" -e "mkl_lapack_cunmql" -e "mkl_lapack_zlaed0" -e "mkl_lapack_zunmql"`
```
/opt/intel/lib/libmkl_core.a:xclaed0.o:                 U mkl_lapack_claed7	xclaed0_gen.f:0
/opt/intel/lib/libmkl_core.a:xclaed0.o:                 U mkl_lapack_claed8
/opt/intel/lib/libmkl_core.a:zunmtr.o:                 U mkl_lapack_zunmql	zunmtr_gen.f:0
/opt/intel/lib/libmkl_core.a:zstedc.o:                 U mkl_lapack_zlaed0	zstedc_gen.f:0
/opt/intel/lib/libmkl_core.a:cunmtr.o:                 U mkl_lapack_cunmql	cunmtr_gen.f:0
/opt/intel/lib/libmkl_core.a:cstedc.o:                 U mkl_lapack_claed0	cstedc_gen.f:0
/opt/intel/lib/libmkl_core.a:claed8.o:0000000000000000 T mkl_lapack_claed8
/opt/intel/lib/libmkl_core.a:claed7.o:0000000000000000 T mkl_lapack_claed7
/opt/intel/lib/libmkl_core.a:claed7.o:                 U mkl_lapack_claed8	claed7_gen.f:0
```
Those symbols are undefined in `libmkl_core.a` as well, can it be the cause of problems?

**Comment by malfet** [comment]
@nikitaved do you know by any chance, what is the difference between `[cz]heev`(used in BatchLinearAlgebra.cpp) vs `[cz]heevd` (used in BatchLinearAlgebra.cu), or `ssyev` vs `ssyevd`?

**Comment by IvanYashchuk** [comment]
There are several functions for hermitian eigenproblems `heev`, `heevd`, `heevr`. The underlying algorithms are different, `heev` is the basic choice.
MKL documentation nowadays recommends `heevr` over `heevd`.
