### ISSUE TITLE
Lognormal cdf

### ISSUE THREAD

**Issue by mortonjt** [pytorch/pytorch#45935]
It looks like the [lognormal distribution](https://github.com/pytorch/pytorch/blob/master/torch/distributions/log_normal.py) in pytorch doesn't have a cdf / icdf function.

This shouldn't be too difficult to add in, due to the similarity to the normal cdf / icdf.
https://en.wikipedia.org/wiki/Log-normal_distribution

cc @vincentqb @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by fritzo** [comment]
I think we could even implement this for arbitrary univariate `TransformedDistribution`s
```py
class TransformedDistribution(Distribution):
    ...
    def cdf(self, value):
        if self.event_shape:
            raise ValueError("undefined")
        for t in reversed(self.transforms):
            value = t.inv(value)
        return self.base_dist.cdf(value)
```
similarly for `.icdf()`.

**Comment by fritzo** [comment]
Do you want to leave this open to remind us to implement `TransformedDistribution.cdf()`?

**Comment by fritzo** [comment]
It appears this has been implemented since 2018. The methods do not appear in `LogNormal` docs, but `LogNormal`'s docs do point to its base class `TransformedDistribution` which does document these methods. I guess a solution would be to configure docs to show all inherited methods.
