### ISSUE TITLE
Make --help print all CLI options for test scripts

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#45945]
## 🚀 Feature
It would be nice if using the `--help` arg on a script in the `test` dir actually printed [all the arguments that can be passed to those test scripts][argparse], rather than just the ones that are accepted by default [by Python's built-in `unittest` library][unittest].

## Motivation

Case study: I'm still learning my way around as a PyTorch dev, and recently I needed to use the `--save-xml` argument on a test script so that I could see which tests were taking the longest to run. Running `--help` on the test script didn't list that option or anything like it, so I assumed it didn't exist as a CLI arg, until I asked a coworker and they told me about the `--save-xml` arg. If the arg were instead listed by `--help`, it would have saved a bit of time.

## Pitch

New devs: use `--help` on any `test` script to see all the args you can pass.

## Alternatives

- In the ["Unit testing" section of `CONTRIBUTING.md`][contributing], note this limitation of `--help` and give a link to the [section of the code in `torch/testing/_internal/common_utils.py`][argparse] that defines all these options.
  - This has a couple minor downsides:
    - Someone uses `--help` on a test script might not necessarily remember that section of `CONTRIBUTING.md`.
    - The link could become out of date.

## Additional context

This doesn't seem to be a totally trivial change to make, or I would have done it already. Also, [this Python issue][issue] seems to be relevant.

As an example, here is the current output of `python test/test_spectral_ops.py --help`:
```
usage: test_spectral_ops.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b] [-k TESTNAMEPATTERNS] [tests [tests ...]]

positional arguments:
  tests                a list of any number of test modules, classes and test methods.

optional arguments:
  -h, --help           show this help message and exit
  -v, --verbose        Verbose output
  -q, --quiet          Quiet output
  --locals             Show local variables in tracebacks
  -f, --failfast       Stop on first fail or error
  -c, --catch          Catch Ctrl-C and display results so far
  -b, --buffer         Buffer stdout and stderr during tests
  -k TESTNAMEPATTERNS  Only run tests which match the given substring

Examples:
  test_spectral_ops.py                           - run default set of tests
  test_spectral_ops.py MyTestSuite               - run suite 'MyTestSuite'
  test_spectral_ops.py MyTestCase.testSomething  - run MyTestCase.testSomething
  test_spectral_ops.py MyTestCase                - run all 'test*' test methods
                                       in MyTestCase
```
Here is the output when `add_help=False` is removed:
```
usage: test_spectral_ops.py [-h] [--subprocess] [--seed SEED] [--accept] [--jit_executor JIT_EXECUTOR] [--repeat REPEAT]
                            [--test_bailouts] [--save-xml [SAVE_XML]] [--discover-tests] [--log-suffix LOG_SUFFIX]
                            [--run-parallel RUN_PARALLEL]

optional arguments:
  -h, --help            show this help message and exit
  --subprocess          whether to run each test in a subprocess
  --seed SEED
  --accept
  --jit_executor JIT_EXECUTOR
  --repeat REPEAT
  --test_bailouts
  --save-xml [SAVE_XML]
  --discover-tests
  --log-suffix LOG_SUFFIX
  --run-parallel RUN_PARALLEL
```
Ideally, the actual output would be a combination of these two, with additional `help` strings for the PyTorch-specific options (like the one for `subprocess`).

[argparse]: https://github.com/pytorch/pytorch/blob/v1.7.0-rc1/torch/testing/_internal/common_utils.py#L144-L159
[contributing]: https://github.com/pytorch/pytorch/blob/v1.7.0-rc1/CONTRIBUTING.md#unit-testing
[issue]: https://bugs.python.org/issue39283
[unittest]: https://github.com/pytorch/pytorch/blob/v1.7.0-rc1/torch/testing/_internal/common_utils.py#L287-L293

cc @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
Neat idea, @samestep. I can see how this would be useful.
