### ISSUE TITLE
Torch.jit.unused/ignore support normal object class

### ISSUE THREAD

**Issue by rickstaa** [pytorch/pytorch#45967]
## 🚀 Feature

As also discussed on [this forum post](https://discuss.pytorch.org/t/will-torch-jit-unused-support-normal-object-class/76323) it would be very useful if the [torch.jit.unused](https://pytorch.org/docs/stable/generated/torch.jit.unused.html) and [torch.jit.ignore](https://pytorch.org/docs/stable/generated/torch.jit.ignore.html) methods were supported for normal python classes. As mentioned by @driazati 
in [his answer on the forum](https://discuss.pytorch.org/t/will-torch-jit-unused-support-normal-object-class/76323/2) work should already be done on these features. I opened this feature request as I could not find a related feature request or pull request. Feel free to point me to the right issue/ pull request if it already exists.

## Motivation

Our team is currently switching TensorFlow to Pytorch as it in our opinion is more user-friendly. After rewriting some of our algorithms, however, we noticed that the training our these RL algorithms is about 1.6 times slower when PyTorch is used compared to using Tensorflow2.0 (with the [tf.function](https://www.tensorflow.org/api_docs/python/tf/function) wrapper). Although PyTorch appears to be significantly faster than Tensorflow2.0 in pure eager mode when the `tf.function` wrapper is added Tensorflow2.0 is the clear winner. Currently, I can improve the speed of the Pytorch version by the workaround suggested by @driazati in the [torch forum post](https://discuss.pytorch.org/t/will-torch-jit-unused-support-normal-object-class/76323/2):

>  The best way around it, for now, is probably to use free-standing functions (which you can @ignore ) that take the object as the first argument

This, however, makes our codebase less pythonic and significantly decreased its readability.

## Pitch

As also explained in the forum post it would be amazing if we could decorate regular python classes (see an example below) with the `torch.jit.script` wrapper while making use of the `torch.jit.ignore` and `toch.jit.unused` wrappers. This way, I would be able to achieve similar and maybe even better performance to Tensorflow 2.0 when using PyTorch.

```python
@torch.jit.script
class MyObject(object):
    def __init__(self):
        super().__init__()

    @torch.jit.unused
    def unsupported(self):
        with torch.no_grad():
            print('This is not supported by jit.')

    def supported(self, x):
        print('This is supported by jit.')
```

cc @gmagogsfm

**Comment by ppwwyyxx** [comment]
https://github.com/pytorch/pytorch/pull/38522 seems like what you want?

**Comment by rickstaa** [comment]
@ppwwyyxx Exactly thanks a lot!
