### ISSUE TITLE
Non-deterministic results when indexing into/out of the same tensor 

### ISSUE THREAD

**Issue by andyljones** [pytorch/pytorch#45964]
## 🐛 Bug

Simultaneously reading and writing to the same tensor can lead to random results. 

## To Reproduce

Here's a minimal example

```python
import torch
import matplotlib.pyplot as plt

T, B = 8, 16

ts, bs = torch.meshgrid(
        torch.arange(T, device='cuda'),
        torch.arange(B, device='cuda'))

ts_inv = ts.flip(0)
ts[ts_inv, bs] = ts

plt.imshow(ts.cpu())
```

Here we're setting up some row and column index tensors, then - in a very dumb way - flipping the row indices by simultaneously reading from/writing to `ts`. 

Now, if there are 16 columns in `ts` then it works like you'd naively expect, and after all is said and done `ts` looks like this:

![image](https://user-images.githubusercontent.com/662606/95312271-9f870d00-0886-11eb-84f0-637a25a9bd55.png)

But if there are 17 columns in `ts`, it goes a bit weird:

![image](https://user-images.githubusercontent.com/662606/95312303-ab72cf00-0886-11eb-8fdf-1b0939bdd3e7.png)

and you get more and different patterns depending on the number of columns. 

## Environment

```
PyTorch version: 1.5.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] pytorch-memlab==0.0.4
[pip] torch==1.5.1
[pip] torchvision==0.6.1
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch-memlab            0.0.4                    pypi_0    pypi
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi
```

## Additional context

Here's a numpy equivalent:

```python 
import numpy as np

T, B = 8, 16

ts, bs = np.meshgrid(
        np.arange(T),
        np.arange(B), indexing='ij')

ts_inv = ts[::-1]
ts[ts_inv, bs] = ts

plt.imshow(ts)
```

which generates this pattern independent of number of columns:

![image](https://user-images.githubusercontent.com/662606/95312619-11f7ed00-0887-11eb-8735-68a349dc6a5a.png)

which frankly I was surprised by, but is predictable enough. 

I strongly suspect Pytorch's behaviour here is a deliberate tradeoff in favour of performance, but I couldn't Google up any warnings to not assign to the same tensor as you're reading from. So I'm posting this bug report in case it is actually a surprise regression.

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by albanD** [comment]
Hi,

Yes this is expected behavior indeed as for performance reason we cannot ensure consistent behavior.

@ngimel should we add a warning similar to the overlapping memory in this case?

**Comment by ngimel** [comment]
cc @peterbell10, looks like we need to check for memory overlap in the indexing operations too.

**Comment by peterbell10** [comment]
Had a quick look into it. I think it's calling the `index_put_` native function, which actually does check for memory overlap.
https://github.com/pytorch/pytorch/blob/1552a926a3e92f57f2573b5b18a0965a16ac401b/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L322

The problem here is that `assert_no_partial_overlap` is meant to allow in-place operations where an output argument exactly overlaps with the input.

**Comment by ngimel** [comment]
Ah, you are right! Full overlap is ok for regular pointwise operations, but it's not ok for indexing because addresses for read and write accesses are different.

**Comment by andyljones** [comment]
Is the non-determinism here a recent phenomenon, or has PyTorch always behaved this way? Because if it's always been this way, I'm kind of shocked no-one's tripped over it before me. `xs[rs, cs] = xs` isn't *that* rare of an idiom, is it?

**Comment by albanD** [comment]
Yes it has been this way forever.

**Comment by ngimel** [comment]
`scatter_` using the same tensor as a source and destination is also affected (reported internally). Bumping priority because of user activity.
