### ISSUE TITLE
Cannot install pytorch cuda 8.0 using conda

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#4596]
> $ conda install pytorch torchvision -c pytorch
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: /home-nfs/rluo/rluo/local/anaconda2
> 
>   added / updated specs:
>     - pytorch
>     - torchvision
> 
> 
> The following NEW packages will be INSTALLED:
> 
>     pytorch:     0.3.0-py27_cuda9.0.176_cudnn7.0.3hdbbd62b_4 pytorch [cuda90]
>     torchvision: 0.2.0-py27hfb27419_1                        pytorch

I also tried 
`conda install pytorch torchvision cuda80 -c pytorch`
nothing changed.

**Comment by soumith** [comment]
do you already have the cuda90 feature installed, for some reason...

Try first doing:

`conda uninstall cuda90`

**Comment by ruotianluo** [comment]
Thanks.
Solved.

**Comment by Henry-E** [comment]
This was causing me a lot of problems as well when trying to update pytorch with a new Cuda version
