### ISSUE TITLE
[quantization]: Using histogram observer in a model's qconfig for QAT with nn.DataParallel leads to possible deadlock

### ISSUE THREAD

**Issue by aryanbdps9** [pytorch/pytorch#45970]
## 🐛 Bug

Using `torch.quantization.HistogramObserver` for activation while creating a `qconfig` for QAT results in very slow training with low GPU utilization (as reported by `nvidia-smi`).

## To Reproduce

I have shared the code in [this gist](https://gist.github.com/aryanbdps9/384c1105cb5bfb555d6fc7971c1b63d3). I just modified the code in [this tutorial](https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html). The important parts are as follows:

Creating a qconfig
```python
# creating a qconfig
observer_class_wt = torch.quantization.PerChannelMinMaxObserver
observer_class_act = torch.quantization.HistogramObserver # very low gpu utilization as reported by nvidia-smi
# observer_class_act = torch.quantization.MovingAverageMinMaxObserver # If I use this, I get much higher GPU utilization.
qscheme_wt = torch.per_channel_affine
qscheme_act = torch.per_tensor_affine
reduce_range_wt=False
reduce_range_act=False
kwargs_wt = {
    'reduce_range':reduce_range_wt
}
kwargs_act = {
    'reduce_range':reduce_range_act
}
kwargs_wt['quant_min'], kwargs_wt['quant_max'] = (-64, 63) if kwargs_wt['reduce_range'] else (-128, 127)
kwargs_act['quant_min'], kwargs_act['quant_max'] = (0, 127) if kwargs_act['reduce_range'] else (0, 255)
kwargs_wt['dtype'] = torch.qint8
kwargs_act['dtype'] = torch.quint8

weight_class = torch.quantization.fake_quantize.FakeQuantize.with_args(observer=observer_class_wt, **kwargs_wt)
activation_class = torch.quantization.fake_quantize.FakeQuantize.with_args(observer=observer_class_act, **kwargs_act)
myQconfig = torch.quantization.qconfig.QConfig(activation=activation_class, weight=weight_class)
```
Note that replacing the line: `observer_class_act = torch.quantization.HistogramObserver` with `observer_class_act = torch.quantization.MovingAverageMinMaxObserver` results in much higher GPU utilization and much faster training.

Loading model and wrapping it in `nn.DataParallel`:
```python

qat_model = load_model(saved_model_dir + float_model_file)
qat_model.fuse_model()

optimizer = torch.optim.SGD(qat_model.parameters(), lr = 0.0001)
# qat_model.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')
qat_model.qconfig = myQconfig


torch.quantization.prepare_qat(qat_model, inplace=True)
print('Inverted Residual Block: After preparation for QAT, note fake-quantization modules \n',qat_model.features[1].conv)
qat_model.cuda()
qat_model = nn.DataParallel(qat_model)
```
 During training, when I press `Ctrl + c`, I usually get this stack trace, suggesting something is waiting to acquire a lock:
```python
  File "quantization_tut.py", line 423, in <module>
    train_one_epoch(qat_model, criterion, optimizer, data_loader, True, num_train_batches)
  File "quantization_tut.py", line 358, in train_one_epoch
    output = model(image)
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    thread.join()
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/home/users/aryan.aryan/Anaconda3/envs/py38main/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
terminate called without an active exception
[1]    14510 abort (core dumped)  python quantization_tut.py
```

## Expected behavior

Even on using `torch.quantization.HistogramObserver`, the training should happen at similar speed as compared to `torch.quantization.PerChannelMinMaxObserver`.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.15.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)

Nvidia driver version: 450.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.1           py38hbc911f0_0  
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py38_cu101    pytorch

## Additional context

This is just a toy example, I encountered this problem with a very large model, where the GPU utilization drop was from 90-100% to less than 15%. Unfortunately, the code base of that model is private and can't be shared here.

cc @raghuramank100 @supriyar @vkuzo  @jerryzh168 @jamesr66a @ezyang @gchanan @zou3519 @jianyuh @dzhulgakov

**Comment by vkuzo** [comment]
Hi @aryanbdps9 , thanks for the report.  This is expected, as HistogramObserver is significantly more computationally intensive based on how it observes values and calculates the optimal scale and zero point.  Histogram Observers are usually used with post training static quantization, they are not expected to be fast enough to be used with QAT.

Going to close this out since this is expected, but please feel free to ask more questions.
