### ISSUE TITLE
Can't send/recv within rpc callback

### ISSUE THREAD

**Issue by froody** [pytorch/pytorch#45995]
## 🐛 Bug

gloo: https://gist.github.com/froody/c1af637f72535a512a4358487b37891b
mpi: https://gist.github.com/froody/7bb2b5971944833cd201ef675c0622fb

Calling torch.distributed.send/recv within the scope of a rpc_async callback works fine with the MPI backend but crashes with the GLOO backend

### With Gloo

1. Install pytorch 1.6.0
2. python [gloo-send-recv.py](https://gist.github.com/froody/c1af637f72535a512a4358487b37891b)

```
>>> recv 1
>>> send 0
got [../third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [127.0.1.1]:20883
got [../third_party/gloo/gloo/transport/tcp/pair.cc:378] writev [127.0.0.1]:46768: Bad address
```

### Expected behavior:
```
>>> send 0
<<< send
>>> recv 1
<<< recv
```

### With MPI
1. Build pytorch 1.6.0 against openmpi, I'm using openmpi-4.0.4/cuda-10.1/ucx-1.8.1/pmix-3.1.5 in the FAIR cluster
2. mpirun --host localhost:2 -np 2 --mca pml ucx -x PATH=$PATH -x UCX_TLS=rc,sm,cuda_ipc,cuda_copy  -mca orte_base_help_aggregate 0 python [mpi-send-recv.py](https://gist.github.com/froody/7bb2b5971944833cd201ef675c0622fb)
3. should succeed 

```
$ /public/apps/openmpi/4.0.4/cuda.10.1/ucx.1.8.1/pmix.3.1.5/gcc.7.4.0/bin/mpirun --host localhost:2 -np 2 --mca pml ucx -x PATH=$PATH -x UCX_TLS=rc,sm,cuda_ipc,cuda_copy  -mca orte_base_help_aggregate 0 python mpisend.py
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   learnfair1663
  Local device: mlx5_3
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   learnfair1663
  Local device: mlx5_3
--------------------------------------------------------------------------
>>> send 0
<<< send
>>> recv 1
<<< recv
[1602701981.925254] [learnfair1663:44150:0]  memtype_cache.c:137  UCX  WARN  destroying inuse address:0x7f2172400000
[1602701981.925255] [learnfair1663:44151:0]  memtype_cache.c:137  UCX  WARN  destroying inuse address:0x7f286c600000
```

## Environment

PyTorch version: 1.6.0a0+b31f58d
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0a0+d3e3dec
[pip3] torchtext==0.8.0a0+e9b711b
[pip3] torchvision==0.7.0
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.2                      256    conda-forge
[conda] numpy                     1.19.1           py37h8960a57_0    conda-forge
[conda] torch                     1.6.0a0+b31f58d          pypi_0    pypi
[conda] torchtext                 0.8.0a0+e9b711b          pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @lw @beauby @agolynski @SciPioneer @H-Huang @mrzzd @heitorschueroff @xush6528

**Comment by froody** [comment]
Closing due to mistake

**Comment by froody** [comment]
Reopened with reduced test case for crash using gloo backend only

**Comment by rohan-varma** [comment]
Confirmed that the same error seems to happen even if `rpc.BackendType.TENSORPIPE` is used as the RPC backend.

**Comment by lw** [comment]
I'm wondering if perhaps there's a thread-local variable somewhere which is giving an unexpected result when accessed from within the callback. What happens if we manually spawn a thread and run that callback in it? Does it give the same error?

**Comment by mrzzd** [comment]
This seems to have nothing to do with rpc. When Tensors are on gpu, glue fails to do  send/recv even if rpc is not used at all (rpc is not initialized, and process 0 directly runs send and process 1 direct runs recv).  If the Tensor is on cpu it works with and without rpc.

Should I close it then? @rohan-varma

**Comment by rohan-varma** [comment]
> This seems to have nothing to do with rpc. When Tensors are on gpu, glue fails to do send/recv even if rpc is not used at all 

@mrzzd Could you verify if this works if the tensors are on CPU? If that works as expected for both tensorpipe and pg backends,  should be good to close

**Comment by mrzzd** [comment]
@rohan-varma  Yes, the example provided here works if the tensor is on CPU, for both TP and PG backends. Thanks for confirming.
