### ISSUE TITLE
Does Nvidia have a kind of cuda driver to install for the machine without GPU?

### ISSUE THREAD

**Issue by guotong1988** [pytorch/pytorch#4603]
So after installing the cuda driver on the NO-GPU machine, we can debug on it in GPU-mode, which is the same as a machine with GPU~
Sorry to trouble you and thank you very much~

**Comment by apaszke** [comment]
You can get a toolkit and build with CUDA support, but you can't run anything, so you can only debug build issues.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
