### ISSUE TITLE
CUDA problem with Linux Kernel 5.9

### ISSUE THREAD

**Issue by ozen** [pytorch/pytorch#46034]
## 🐛 Bug

torch.cuda.is_available() returns True on Ubuntu 20.04 with linux kernel 5.8.13, but returns False when the kernel is upgraded to 5.9-rc8. nvidia-smi and other gpu-related programs work as expected, only pytorch stops detecting the GPU.

## To Reproduce

In a Ubuntu 20.04 OS with linux kernel 5.9-rc8, run:

```python -c 'import torch; print(torch.cuda.is_available())'```

## Expected behavior

Pytorch should detect the GPU on Linux kernel 5.9.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu 20.04.1 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8
 - CUDA version: 10.2 in pytorch, N/A in the system.
 - GPU models and configuration: GeForce RTX 3090

cc @malfet @seemethere @walterddr @ngimel

**Comment by mruberry** [comment]
Sorry you're hitting this issue, @ozen. I've cc'd some of our build engineers.

**Comment by malfet** [comment]
@ozen can you please share the output of `nvidia-smi` on 5.9 kernel here? And what other GPU related apps have you tried to run? For example, can you compile CUDA hello world application(something like the following: https://gist.github.com/malfet/0a40af6b59772501fab0641ceff8c3e2 ) on system that has CUDA installed and then try to run it on the system with 5.9 kernel?

**Comment by ozen** [comment]
@malfet GPU acceleration for desktop software like Xorg and Firefox was working. I don't have access to the machine right now, I will update with nvidia-smi and hello world results as soon as possible.

**Comment by malfet** [comment]
Xorg and Firefox might work with opensource kernel drivers, but for CUDA to work one needs to have nvidia kernel driver loaded. Can you please share the output of `lsmod|grep nvidia` here when machine is booted into Linux-5.9

**Comment by ozen** [comment]
nvidia-smi output with kernel 5.8.13:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:07:00.0  On |                  N/A |
|  0%   32C    P8    31W / 350W |    221MiB / 24259MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1069      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      1620      G   /usr/lib/xorg/Xorg                 73MiB |
|    0   N/A  N/A      1747      G   /usr/bin/gnome-shell               95MiB |
+-----------------------------------------------------------------------------+
```

nvidia-smi output with kernel 5.9-rc8

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.04    Driver Version: 455.23.04    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:07:00.0  On |                  N/A |
|  0%   32C    P8    32W / 350W |    241MiB / 24259MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1208      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      1665      G   /usr/lib/xorg/Xorg                 88MiB |
|    0   N/A  N/A      1792      G   /usr/bin/gnome-shell              101MiB |
+-----------------------------------------------------------------------------+
```

output of `nvcc --version`:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

cuda hello world compiles and runs with 5.9, but does not print. With 5.8.13, it prints "hello world".

output of `lsmod | grep nvidia` is the following with both kernel versions:

```
nvidia_drm             53248  6
nvidia_modeset       1212416  9 nvidia_drm
nvidia              27648000  365 nvidia_modeset
drm_kms_helper        225280  1 nvidia_drm
drm                   557056  9 drm_kms_helper,nvidia_drm
```

**Comment by gardotd426** [comment]
CUDA support is broken on 5.9 because of the "GPL condom" stuff that was added to the kernel. `nvidia_uvm` will no longer load, and running things like `clinfo` will give output saying there are no supported platforms. 

I don't think there's anything pytorch can do, because this is a fundamental "Nvidia vs the Linux Kernel/GPL" issue.

**Comment by nlgranger** [comment]
May I suggest editing the github issue template to mention this error? It is not obvious where the error is coming from when using pytorch so many users might be tempted to report it.

**Comment by ozen** [comment]
[Official announcement from NVIDIA](https://forums.developer.nvidia.com/t/nvidia-driver-not-yet-supported-for-linux-kernel-5-9/157263):

> Due to an incompatibility issue, we advise customers to defer updating to Linux Kernel 5.9+ until mid-November when an NVIDIA Linux GPU driver update with Kernel 5.9+ support is expected to be available.
> 
> Linux Kernel 5.9+ is incompatible with current and previous NVIDIA Linux GPU drivers. We advise customers to defer updating to Linux Kernel 5.9+ until mid-November when an NVIDIA Linux GPU driver update with Kernel 5.9+ support is expected to be available. NVIDIA is aware of the impact this will have on customers, and we are working diligently to provide the driver update with Kernel 5.9+ support as soon as possible.
> 
> Customers must use our upcoming driver update on Kernel 5.9+ to have a fully functioning driver.

For future reference, the latest NVIDIA Linux driver version as of this writing is 455.28.

**Comment by adgaudio** [comment]
For those of you checking on this thread:

It appears Nvidia released a working driver.  Cuda and pytorch work for me now.

 nvidia-455.38-1  works with linux 5.9.2.arch1-1

**Comment by shamanez** [comment]
@adgaudio 

what CUDA version you have used?

Also can you please summarize the steps that you have taken? It would be a big help.

I totally messed my ubuntu 20.04 machine after **upgrading to Linux 5.9.6-050906-generic**
 and it gives the same error.

**Comment by shamanez** [comment]
I saw this message...

https://forums.developer.nvidia.com/t/nvidia-driver-not-yet-supported-for-linux-kernel-5-9/157263

**Comment by adgaudio** [comment]
Hi @shamanez ,

I'm not sure, but I don't think the cuda version matters (though cuda version must be compatible with the nvidia driver version).  (For your reference, I currently use cuda 11.1.1-1 from arch linux repository.  I don't use ubuntu).  I would guess that the steps you'd need to get the nvidia gpu working properly are:  a) uninstall everything nvidia related including cuda with the `apt-get remove --purge ` option ; then b) re-install the nvidia packages via apt-get.

 I don't know the state of nvidia and linux 5.9 on ubuntu.  Maybe you or someone else can comment on that.

Good luck!
