### ISSUE TITLE
torch.pow doesn't check for tensors being on different devices

### ISSUE THREAD

**Issue by ThomasBudd** [pytorch/pytorch#46037]
## 🐛 Bug

The function torch.pow doesn't seem to check if the input tensors are on the same device.

## To Reproduce

1. a = torch.tensor(2.0, device=torch.device('cuda:0'))
2. b = torch.tensor(1.0)
3. torch.pow(a,b)  

## Expected behavior

RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

Instead:

RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "C:/cb/pytorch_1000000000000/work/aten/src\\ATen/native/cuda/Loops.cuh":61, please report a bug to PyTorch. 

## Environment

 - PyTorch Version 1.6.0:
 - OS: tested on Windows 10.0 Home and Ubuntu 20.04
 - Pytorch installation via conda:
 - Python version:
 - CUDA/cuDNN version: CUDA10.2, 
 - GPU: GTX 1060 and RTX 2080ti

cc @ezyang @gchanan @zou3519 @bdhirsh @ejguan

**Comment by mruberry** [comment]
This still occurs on nightly and seems unique to pow (it doesn't affect add, for example).

**Comment by vadimkantorov** [comment]
Should scalar CPU powers be still accepted?

**Comment by mruberry** [comment]
Yep, a scalar value for the exponent should and does work.

Unfortunately both values being scalars doesn't work, but we haven't pursued making that work, either. (Fun fact! It does work for some PyTorch functions, including add, sub, mul and div.)

**Comment by malfet** [comment]
Looks pretty similar to https://github.com/pytorch/pytorch/issues/44714

**Comment by mruberry** [comment]
I don't think they're related. This is probably an issue with how pow is specializing for tensors and scalars.

**Comment by ThomasBudd** [comment]
> Should scalar CPU powers be still accepted? (e.g. it would work with Python scalar powers, may also work with PyTorch scalar powers?)

If scalar CPU powers should not be accepted Pytorch should raise the correct RuntimeError stating that the tensors are not on the same devices. Other functions raise:
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

**Comment by mruberry** [comment]
> > Should scalar CPU powers be still accepted? (e.g. it would work with Python scalar powers, may also work with PyTorch scalar powers?)
> 
> If scalar CPU powers should not be accepted Pytorch should raise the correct RuntimeError stating that the tensors are not on the same devices. Other functions raise:
> RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

CPU scalars SHOULD be accepted as exponents to the pow function, however.

torch.pow(cuda_tensor, 5) should work.
torch.pow(cuda_tensor, tensor(5)), should work.
torch.pow(cuda_tensor, tensor((5,))), should NOT work and complain the tensors are on different devices

**Comment by ngimel** [comment]
This unfortunately does not fix all cases that need to be fixed (and breaks some that were not broken)
```
In [1]: import torch                                                                                                                                                                                                                     
In [2]: a=torch.randn(3)                                                                                                                                                                                                                 
In [3]: b=torch.tensor(2, device="cuda")                                                                                                                                                                                                 
In [4]: torch.pow(a,b) #should not work, but does                                                                                                                                                                                        
Out[4]: tensor([0.3569, 0.9572, 0.0790])
In [5]: a=torch.tensor(3, device="cuda")                                                                                                                                                                                                 
In [6]: b=torch.tensor(2)                                                                                                                                                                                                                
In [7]: torch.pow(a,b) #should work, but does not                                                                                                                                                                                        
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-85b7a2442faa> in <module>
----> 1 torch.pow(a,b) #should work, but does not
RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/private/home/ngimel/pytorch/aten/src/ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch. 
In [8]: a=torch.randn(3, device="cuda")                                                                                                                                                                                                  
In [9]: torch.pow(a,b) # yeah, that one is fixed                                                                                                                                                                                         
Out[9]: tensor([0.2583, 0.1865, 1.8412], device='cuda:0')
```

**Comment by janeyx99** [comment]
> This unfortunately does not fix all cases that need to be fixed (and breaks some that were not broken)
> 
> ```
> In [1]: import torch                                                                                                                                                                                                                     
> In [2]: a=torch.randn(3)                                                                                                                                                                                                                 
> In [3]: b=torch.tensor(2, device="cuda")                                                                                                                                                                                                 
> In [4]: torch.pow(a,b) #should not work, but does                                                                                                                                                                                        
> Out[4]: tensor([0.3569, 0.9572, 0.0790])
> In [5]: a=torch.tensor(3, device="cuda")                                                                                                                                                                                                 
> In [6]: b=torch.tensor(2)                                                                                                                                                                                                                
> In [7]: torch.pow(a,b) #should work, but does not                                                                                                                                                                                        
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-7-85b7a2442faa> in <module>
> ----> 1 torch.pow(a,b) #should work, but does not
> RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/private/home/ngimel/pytorch/aten/src/ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch. 
> In [8]: a=torch.randn(3, device="cuda")                                                                                                                                                                                                  
> In [9]: torch.pow(a,b) # yeah, that one is fixed                                                                                                                                                                                         
> Out[9]: tensor([0.2583, 0.1865, 1.8412], device='cuda:0')
> ```

Ah oops, I guess I should ask for some clarifications:
1. We only want **cpu** tensors that are 0-dimensional to be treated as scalar exponents when calculating pow.
2. We only want to delegate this special case when the base tensor is on cuda (no other cases)

Essentially, the fix should check the device type of both base and exponent, correct?

**Comment by mruberry** [comment]
> Ah oops, I guess I should ask for some clarifications:
> 
> 1. We only want **cpu** tensors that are 0-dimensional to be treated as scalar exponents when calculating pow.

Either input or exponent can be a CPU scalar tensor when the other tensor is a CUDA tensor. 

Cases that should work:

cpu x cpu
cpu scalar x cuda
cuda x cpu scalar (zero dim tensor or actual scalar value)
cuda x cuda

> 2. We only want to delegate this special case when the base tensor is on cuda (no other cases)
> Essentially, the fix should check the device type of both base and exponent, correct?

Possibly,  haven't looked too carefully, but you definitely don't want to take an item() from a CUDA tensor because this will cause a cross-device synchronization, and one of our design principles is that cross-device data movement / synchronization should be explicit.
