### ISSUE TITLE
[JIT] Docstrings for custom C++ classes

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#46047]
We should have a way to specify docstrings on a) custom registered classes and b) the methods thereof. I believe this will entail:

1) C++ APIs for populating the docstring. I can't find a pybind11 equivalent for installing a docstring on a class, but it could be an extra string argument to the `torch::class_<>` constructor. For method definitions I think it should similarly be an extra string argument to `class_::def()`
2) A way to represent docstrings in the TorchScript type system. For classes, it could preferably be a `__doc__` attribute, or a special case method on the `ClassType`: https://github.com/pytorch/pytorch/blob/40828b68e1bb0eb6fc2996889d4886ae988dc059/aten/src/ATen/core/jit_type.h#L1950. For methods, I think we would need to add a special docstring method to `jit::Function`: https://github.com/pytorch/pytorch/blob/40828b68e1bb0eb6fc2996889d4886ae988dc059/aten/src/ATen/core/function.h#L27
3) Then, in the Python bindings, for classes we would need to bind in a `__doc__` property to access the docstring as we defined in step (2): https://github.com/pytorch/pytorch/blob/40828b68e1bb0eb6fc2996889d4886ae988dc059/torch/csrc/jit/python/python_custom_class.cpp#L31. For functions similarly we would bind in the `__doc__` property on ScriptFunction: https://github.com/pytorch/pytorch/blob/40828b68e1bb0eb6fc2996889d4886ae988dc059/torch/csrc/jit/python/script_init.cpp#L1111

Note that for any of these stages, if we can generalize the support to broader TorchScript support (particularly the frontend concerns), that would probably be a good idea

cc @gmagogsfm

**Comment by suo** [comment]
Requested by @fmassa

**Comment by gmagogsfm** [comment]
@wanchaol 

I think this would be useful for torch.distributed as well.

**Comment by suo** [comment]
how pybind11 API looks: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#generating-documentation-using-sphinx
