### ISSUE TITLE
TCPStoreTest.test_numkeys_delkeys takes 5+ min to finish

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#46064]
See report from `https://app.circleci.com/pipelines/github/pytorch/pytorch/224304/workflows/2571002d-2075-4e53-877b-4bac675037de/jobs/8062979`

Most of the time it just idly waits for timeout in:
https://github.com/pytorch/pytorch/blob/64b068698628f9a77a53a6b98fc8f3579e3248d7/test/distributed/test_c10d.py#L289-L290

cc @ezyang @seemethere @malfet @walterddr @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by osalpekar** [comment]
I think we can just set the timeout to some smaller value before this `get` call so the test runs faster. I'll make this change soon

**Comment by malfet** [comment]
I've already tried it reducing to 30 sec, it still takes a while
In a meantime, I'll be annotating it with `@slowTest`,  to run it on one rather than all configs

**Comment by osalpekar** [comment]
Here's a fix: https://github.com/pytorch/pytorch/pull/46067 (2 second timeout should be perfectly fine). This completed in about 12 seconds on my local machine.

**Comment by rohan-varma** [comment]
Should be resolved by https://github.com/pytorch/pytorch/pull/46067
