### ISSUE TITLE
Confusing error message for torch.LongTensor([1], device = 'cuda')

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#46085]
```
torch.LongTensor([1], device = 'cuda')
# RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
```
`device type: cpu was passed device type: cuda` is hard to pass. adding some punctuation would help!

**Comment by partypyro** [comment]
Ignore the first pull request! Sorry this is my first pull request! I'm still learning how to use github and my ide changed all the tabs to spaces when I imported the cloned repository

**Comment by vadimkantorov** [comment]
@partypyro How does the new error message look like?

**Comment by partypyro** [comment]
![95663511-9b602700-0af4-11eb-9a21-7e0505fdfc6a](https://user-images.githubusercontent.com/13827698/95782954-ba41f300-0c85-11eb-992d-f48e38d05d2d.png)
