### ISSUE TITLE
NCCL connection refused when doing broadcast in several process groups simultaneously

### ISSUE THREAD

**Issue by FrankLeeeee** [pytorch/pytorch#46087]
## ❓ Questions and Help

I am currently running a distributed code but it reported NCCL connection refused. I tried with 16 nodes with 1 gpu on each node.

The code to reproduce my error is:

```
import torch
import torch.distributed as dist

import os
import subprocess


def main():
    os.environ['NCCL_DEBUG'] = 'INFO'

    # init dist
    rank = int(os.environ['SLURM_PROCID'])
    world_size = int(os.environ['SLURM_NTASKS'])
    local_rank = int(os.environ['SLURM_LOCALID'])
    node_list = os.environ['SLURM_NODELIST']
    host_ip = subprocess.getoutput(
        f'scontrol show hostname {node_list} | head -n1')
    port = "29500"
    init_method = 'tcp://{}:{}'.format(host_ip, port)

    dist.init_process_group("nccl", init_method=init_method,
                                         world_size=world_size, rank=rank)

    rank_col = rank % 4
    col_ranks = list(range(rank_col, world_size, 4))
    col_group = dist.new_group(ranks=col_ranks)

    data = torch.rand(2, 2).cuda()

    dist.broadcast(data,
                src=rank_col,
                group=col_group,
                async_op=False)


if __name__ == "__main__":
    main()
```

Basically this code creates 4 process groups. The 4 groups are 0-4-8-12, 1-5-9-13, 2-6-10-14, 3-7-11-15. The number is the rank number and the 4 numbers connected by - are in one group. Now I want these 4 groups to do broadcast within each group simultaneously. But it raises NCCL connection refused issue.

The error trace is like:

<img width="983" alt="Screenshot 2020-10-09 at 2 40 31 PM" src="https://user-images.githubusercontent.com/31818963/95592111-c27a1280-0a7a-11eb-9081-c341ca705721.png">

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by agolynski** [comment]
@FrankLeeeee: Could you make sure that 
1) if you do broadcast in world group (0-15) it works fine and
2) if you broadcast in just one smaller group (say ranks 0-3) it also works fine? 

If this needs to be reproduced: what version of NCCL do you use?

**Comment by FrankLeeeee** [comment]
> @FrankLeeeee: Could you make sure that
> 
> 1. if you do broadcast in world group (0-15) it works fine and
> 2. if you broadcast in just one smaller group (say ranks 0-3) it also works fine?
> 
> If this needs to be reproduced: what version of NCCL do you use?

Hi, thanks for your reply. Yes it works in the world group as well as single small group. However, when it does broadcast in multiple groups simultaneously, it will produce this error. 

I use NCCL 2.6.4 and CUDA  10.1

**Comment by FrankLeeeee** [comment]
Hi, I will close this issue as it is solved in https://github.com/pytorch/pytorch/issues/46181
