### ISSUE TITLE
If you want to disable CUDA support, export environment variable NO_CUDA=1.

### ISSUE THREAD

**Issue by zkl99999** [pytorch/pytorch#4610]
this is mean?  how i do without CUDA
is this?
NO_CUDA=1 DEBUG=1 python setup.py install

**Comment by apaszke** [comment]
`NO_CUDA=1 python setup.py install`, or better go to pytorch.org and download a CPU-only binary (they are available since yesterday and weight only 45MB).

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
