### ISSUE TITLE
RESOLVED: Don't let "tensor like" objects substitute for tensors

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#46138]
This issue is to discuss letting Python numbers, lists, and tuples be used in place of tensors. This is already a NumPy feature. For example:

```
a = np.array((1, 2, 3))
a + (4, 5, 6)
: array([5, 7, 9])

np.add(1, 2)
: 3
```

Many PyTorch functions already support CPU scalars, but none support "tensor like" Python objects:

```
t = torch.tensor((1, 2, 3))
t + (4, 5, 6)
: TypeError: unsupported operand type(s) for +: 'Tensor' and 'tuple'

t + 4
: tensor([5, 6, 7])
```

There are significant challenges with supporting this behavior:

- PyTorch supports multiple device types, but these tensor-like objects would always be interpreted as CPU tensors. This suggests that networks using this feature probably couldn't be converted to non-CPU device types.
- This may be an antipattern for device types like XLA. (See https://github.com/pytorch/pytorch/issues/31558.)
- There may be a performance impact from evaluating function inputs to determine if they're tensor-like objects.

For additional context, JAX does not support this behavior:

```
import jax.numpy as jnp
a = jnp.array((1, 2, 3))
a + (4, 5, 6)
: TypeError: unsupported operand type(s) for +: 'DeviceArray' and 'tuple'
```

I don't think we should support this behavior, but it has been requested, and I'd like to direct future requests to this issue. 

cc @mruberry @rgommers @heitorschueroff

**Comment by vadimkantorov** [comment]
In NumPy it works:
```python
import numpy as np
a = np.array([1,2,3])
a[:3] = [4,5,6] # works

import torch
b = torch.tensor([1,2,3])
b[:3] = [4,5,6] # TypeError: can't assign a list to a torch.LongTensor
```

A real-world pattern where either `torch.cat` accepting a collection of Python lists or `copy_` accepting a Python list would be helpful: packing of int lists into a tensor for ease of sharing between processes
```python
class IntListArray:
    def __init__(self, intlists, dtype = torch.int64):
        self.data = torch.cat([torch.as_tensor(t, dtype = dtype) for t in intlists])
        self.cumlen = torch.tensor(list(map(len, intlists)), dtype = torch.int64).cumsum(dim = 0)
        
    def __getitem__(self, i):
        return self.data[(self.cumlen[i - 1] if i >= 1 else 0) : self.cumlen[i]]

    def __len__(self):
        return len(self.cumlen)
```

**Comment by heitorschueroff** [comment]
A question I have is what would the defaults be for device. Would Python lists always be created on the CPU or would it depend on the type of the other input given as argument. If they are always created on CPU, this functionality would only apply to CPU code which I think would not be worth the effort then. In the other case, there might not be a good choice for when to create it on CPU vs GPU.

**Comment by rgommers** [comment]
> I don't think we should support this behavior

For the record: I agree, it's not a good idea to support this. This is an endless source of issues in NumPy, and no other array/tensor library is as forgiving as NumPy. In addition, it makes use of type annotations much harder. If one has a list, adding an explicit `torch.tensor` conversion isn't too difficult, and helps with code clarity and correctly.

**Comment by vadimkantorov** [comment]
It is an allocation / copy, which potentially can be a problem if there's a tens of thousands of little lists (like it could be for int-list encoded utterances in speech-rec datasets, in the wild this happens in NeMo: https://github.com/NVIDIA/NeMo/issues/1467). So maybe at least `copy_` could support this to limit the type annotation issues.

In general I agree that it's better to be explicit.

**Comment by rgommers** [comment]
In general NumPy also makes copies; for Python functions there's `asarray` calls, and for functions implemented in C a similar check + array construction. There may be a couple of exceptions - you seem particularly interested in `__setitem__` and I'm not sure if lists/tuples/generators are special-cased there - but in general there's little to gain.

> So maybe at least only `copy_` could support this

The one `copy_` I see in your linked issue is in your `DictArray` in [this gist](https://gist.github.com/vadimkantorov/86c3a46bf25bed3ad45d043ae86fff57#file-tensorbackeddictarray-py-L32):
```
            for k, v in temp_lists.items():
                res = self.tensors[k][b * batch_size : (b + 1) * batch_size]
                res.copy_(torch.as_tensor(v[:len(res)], dtype = self.tensors[k].dtype)
```
So you're using `copy_` as a workaround here for index assignment, right? If this really is a performance bottleneck in real-world code, maybe adding a separate method (e.g., `copyseq_`) could be considered as an alternative - that seems better than making one method accept non-tensor input.

**Comment by vadimkantorov** [comment]
`copy_` and batching is here to ammortize slow Pytorch's `__setitem__`: https://github.com/pytorch/pytorch/issues/5388. 

Yep, `copyseq_` (or list-accepting `__setitem__`) would be already helpful!

**Comment by rgommers** [comment]
Thanks @vadimkantorov. I think it would make sense to treat this (`copyseq_` or similar) as a feature request separate from the bigger picture topic of making all functions/methods accept sequences. Let's see if @mruberry agrees.

**Comment by vadimkantorov** [comment]
@rgommers Originally, I was concerned about this in the context of `torch.cat(...)` only: https://github.com/pytorch/pytorch/issues/33042, but @mruberry expanded the context and superseded https://github.com/pytorch/pytorch/issues/33042 by this issue

**Comment by rgommers** [comment]
Yes, seeing that now. I'd expect the outcome of this issue to be "bad idea, let's not do that in general". At that point there may or may not be a case for individual changes/features. Those have to ensure the overall design remains sensible. Hence changing `copy_` is probably out of the question; a specific method for dealing with lists or sequences may be fine from that perspective. The `torch.cat` examples do seem like they currently work as they should.

**Comment by vadimkantorov** [comment]
Again stumbled on the original case of torch.stack / torch.cat using torch.as_tensor / torch.from_numpy on inputs.

E.g. using SciPy's hungarian algorithm (that doesn't support batches) wouldn't work like this because colinds is a tuple of NumPy arrays:
```python
def linear_assignment(C):
    rowinds, colinds = zip(*list(map(scipy.optimize.linear_sum_assignment, C.cpu())))
    return torch.stack(colinds, out = C.new_empty(C.shape[:2]))
```

So the more ugly workaround:
```python
def linear_assignment_(C):
    rowinds, colinds = zip(*list(map(scipy.optimize.linear_sum_assignment, C.cpu())))
    return torch.stack(list(map(torch.from_numpy, colinds)), out = C.new_empty(C.shape[:2]))
```

**Comment by mruberry** [comment]
Updated title to reflect discussion. Seems like we can close this issue for now.

**Comment by vadimkantorov** [comment]
There's a related case in https://github.com/pytorch/pytorch/issues/29973

Writing 4 numbers to a tensor makes create a tensor which increases Python gc pressure it seems or is slow
