### ISSUE TITLE
bazel build failed

### ISSUE THREAD

**Issue by duanyzhi** [pytorch/pytorch#46136]
when run:

bazel build //:torch

get:

external/sleef/src/arch/helperavx512f.h:68:19: warning: always_inline function might not be inlinable [-Wattributes]
 static INLINE int vavailability_i(int name) {
                   ^
external/sleef/src/libm/sleefsimddp.c: In function 'Sleef_finz_sind8_u35avx512f':
external/sleef/src/libm/sleefsimddp.c:535:1: error: unrecognizable insn:
 }
 ^
(insn 43 42 44 2 (set (mem/c:V4DF (plus:DI (reg/f:DI 82 virtual-stack-vars)
                (const_int -50016 [0xffffffffffff3ca0])) [0 hi+0 S32 A256])
        (vec_merge:V4DF (vec_select:V4DF (reg:V8DF 824)
                (parallel [
                        (const_int 4 [0x4])
                        (const_int 5 [0x5])
                        (const_int 6 [0x6])
                        (const_int 7 [0x7])
                    ]))
            (reg:V4DF 163 [ D.89995 ])
            (reg:QI 825))) external/sleef/src/arch/helperavx512f.h:146 -1
     (nil))
external/sleef/src/libm/sleefsimddp.c:535:1: internal compiler error: in extract_insn, at recog.c:2343
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //:torch failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 12.212s, Critical Path: 2.93s
INFO: 31 processes: 31 linux-sandbox.
FAILED: Build did NOT complete successfully

dose pytorch support bazel build?

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
@duanyzhi What version of gcc are you using? Can you run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py and post the results here?

**Comment by malfet** [comment]
Please try building with newer compiler (say gcc-7) to avoid those errors, which seems to be addressed in https://github.com/pytorch/pytorch/issues/26892

**Comment by duanyzhi** [comment]
thx!  it worked for gcc-7.

**Comment by duanyzhi** [comment]
update sleef version also works.
