### ISSUE TITLE
weight_variable.get_device() returns -1

### ISSUE THREAD

**Issue by Sumanth9Nandamuri** [pytorch/pytorch#46152]
PyTorch Version : 1.6
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): 
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.1 
 - GPU models and configuration: Titan Xp
 - Any other relevant information:

## Context

I got the following error RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1595629411241/work/aten/src/THC/THCCachingHostAllocator.cpp:278 while running my code with cuda().

So I decided to check the device number for the variables. I printed following variables from forward() function
input_ device no: 1
support device no: 1
weight device no: -1

Here is the code that caused the error.

![gnn_ss1](https://user-images.githubusercontent.com/56218882/95672435-67513880-0bbe-11eb-8c61-3badd51370d0.PNG)
![gnn_ss2](https://user-images.githubusercontent.com/56218882/95672463-9c5d8b00-0bbe-11eb-8c98-7e33733b3930.PNG)

cc @ngimel @albanD @mruberry

**Comment by glaringlee** [comment]
@Sumanth9Nandamuri 
Hi, I think the problem of your code is that you did not register your `weight` list. So when you convert your module to cuda module by calling `.cuda()` (or similar), the Tensor within `weight` is not converted. 

You can use a parameterlist here and register parameterlist to your module, or just simply register each parmeter within `weight`

**Comment by ngimel** [comment]
Closing, the error is in user code. On master, instead of illegal memory access, device mismatch error is thrown.
