### ISSUE TITLE
Deprecate the usage of `to_dense` and `to_sparse` methods.

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#46165]
## 🚀 Feature

- Deprecate the usage of `to_dense` and `to_sparse` methods.

## Motivation

- The usage of adjectives `dense` and `sparse` in `to_dense` and `to_sparse` methods is inaccurate: a sparse tensor can be dense if the number of specified elements is equal or close to `product(<sparse tensor shape>)` value.
- The `to_dense` and `to_sparse` methods are converting tensors from one layout to another. Currently, `to_dense` converts a tensor with `torch.sparse_coo` layout (sparse coo layout) to a tensor with `torch.strided` layout (strided tensor), and `to_sparse` converts a strided tensor to sparse coo layout.
  With the emergence of supporting other sparse storage formats (other than COO, see e.g. https://github.com/pytorch/pytorch/pull/44190), the behaviour of the `to_sparse` method becomes non-unique as it is not clear which sparse storage format ought to be preferred.

## Pitch

The names of `to_dense` and `to_sparse` methods should be replaced with more accurate names that describe their actual function and that would allow extending PyTorch with support to other tensor layouts without the risk of introducing ambiguities to PyTorch API.

Let me propose two solutions (that are not mutually exclusive but could be considered alternative):

## Solution 1

Each layout will have the corresponding `to_<layout>` method.

As a result:
- `to_dense` will be replaced with `to_strided`.
- `to_sparse` will be replaced with `to_sparse_coo`
- Existing `to_mkldnn` method remains unchanged.
- Adding support for a new layout `xyz` will introduce a new method `to_xyz`.

## Solution 2

Support layout conversion in `torch.Tensor.to` method.

As a result:

- `to_dense` becomes `to(torch.strided)`
- `to_sparse` becomes `to(torch.sparse_coo)`
- `to_mkldnn` becomes `to(torch._mkldnn)`
- Adding support for a new layout `xyz` means supporting `to(torch.xyz)` method call.

## Additional context

Currently, we have `torch._mkldnn` layout with the corresponding conversion method `torch.Tensor.to_mkldnn`. This issue does not suggest renaming `_mkldnn` layout.

Related discussions:

- https://github.com/pytorch/pytorch/pull/45400#discussion_r502936733
- https://github.com/pytorch/pytorch/pull/45400#discussion_r500063364

cc @aocsa @nikitaved @pearu @mruberry @VitalyFedyunin @jamesr66a @ppwwyyxx @vincentqb

**Comment by vadimkantorov** [comment]
One option `.to(layout = some_layout)`

**Comment by pearu** [comment]
This issue extends to using the `is_sparse` property as well.

Currently, the `is_sparse` property is used for distinguishing tensors using `sparse_coo` or `strided` layouts. (For `_mkldnn` layout, we have `is_mkldnn` property).

An introduction of a new sparse layout would make the result of `is_sparse` ambiguous.

Possible solutions:
1. Each layout `xyz` will have the corresponding `is_xyz` property with an implementation:
   ```
   def is_xyz(self):
       return self.layout == torch.xyz
   ```
   so that
   - `t.is_sparse` becomes `t.is_sparse_coo`
   - `not t.is_sparse` becomes `t.is_strided`
2. Deprecate the usage of `t.is_sparse` in favor of using explicit conditions `t.layout == torch.sparse_coo` or `t.layout == torch.strided`.
3. `t.is_sparse` is a test for any sparse layout [pseudocode follows]: `t.sparse == str(t.layout).startswith("sparse_")`
3.  Other ideas?

**Comment by mruberry** [comment]
I'm curious what @ngimel and @ezyang think about this. `to` currently supports memory format, and I imagine they have better ideas about the future of layout and memory format. 

As for `is_sparse`, I would suggest we try removing it (Option 2) for now.

**Comment by ezyang** [comment]
Some thoughts:
* I find myself observing a tension between removing these functions versus generalizing them for the brave new world. For example, `to_sparse` could take the sparse layout as an argument (and, for BC reasons, default to COO); similarly, `is_sparse` could simply return true for both COO and CSR (option 3 in https://github.com/pytorch/pytorch/issues/46165#issuecomment-707727764), also preserving BC for code that deals exclusively in COO (we should still update framework code to do a more precise test)
* I'm not really convinced by the terminology confusion for "dense sparse tensors". At least to me, it seems pretty clear that they are referring to layout in context. You can't take a tensor that has a lot of zeros and "make it have less zeros", that doesn't make any sense as an operation.
* I absolutely agree that we need to start fixing internal code to stop using "sparse" when they mean "coo", and a good way to flush out all the spots you need to change may very well be to literally delete the sparse functions and then fix everything until CI is passing.

Overall, I don't think deprecation is completely out of the question, but I don't think it is *blocking* for other work to be done.

**Comment by VitalyFedyunin** [comment]
Also sparse, strided, and mkldnn they all serve the purpose of efficiently selecting proper kernel, if we 'layout' expandable, we might loose some performance.
