### ISSUE TITLE
NCCL group broadcast fails

### ISSUE THREAD

**Issue by henrique** [pytorch/pytorch#46181]
## 🐛 Bug

It looks like that distribution groups are not supported in nccl but the api doesn't warn the user.
When a group is specified on a broadcast, only a subset of the data is synchronised and group boundaries are not respected.
conda Torch 1.6 NCCL 2.4.8 CUDA 10.1

e.g.:
#### split 4 GPUs in 2 groups (odd/even)
    dist.init_process_group("nccl", init_method=init_method,
                                    world_size=world_size, rank=rank)
    rank_col = rank % 2
    col_ranks = list(range(rank_col, world_size, 2))
    col_group = dist.new_group(ranks=col_ranks)
    dist.broadcast(data, src=rank_col, group=col_group, async_op=False)

In this setup 2 workers end with the synchronised data and the other 2 hang.
It looks like the 2 nodes that run are actually also chosen randomly and not accordingly to the given groups:
e.g.:

    rank: 1 group: 1 tensor([0.9331, 0.0218, 0.2762, 0.7283], device='cuda:0') True
    rank: 2 group: 0 tensor([0.9331, 0.0218, 0.2762, 0.7283], device='cuda:0') True

... ranks 0 and 3 don't return

## To Reproduce

    import torch
    import torch.distributed as dist
    import os, time
    import subprocess

    os.environ['NCCL_DEBUG'] = 'WARN'
    rank = int(...)
    world_size = 4
    rank_col = rank % 2
    host_ip = ...
    port = "29500"
    time.sleep(world_size-rank-1)  # sleeps force resulting order

    dist.init_process_group("nccl", init_method=f'tcp://{host_ip}:{port}',
                                    world_size=world_size, rank=rank)

    col_ranks = list(range(rank_col, world_size, 2))
    print('rank:', rank, 'group:', rank_col, col_ranks)
    col_group = dist.new_group(ranks=col_ranks)
    data = torch.rand(4).cuda()
    print('rank:', rank, 'group:', rank_col, data)
    time.sleep(world_size-rank-1)

    dist.broadcast(data, src=rank_col,group=col_group, async_op=False)
    print('rank:', rank, 'group:', rank_col, data, True)
    time.sleep(world_size + 2*rank)
    print('Done!', rank)

## Expected behavior

Data is broadcasted independently to the 2 given groups

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 15 SP1 (x86_64)
GCC version: (SUSE Linux) 7.5.0
Clang version: 10.0.2 (df7eba9cfe923bfcce662b26f97beaf9f806187a)
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 450.51.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] cudatoolkit-dev           10.1.243             h516909a_3    conda-forge
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-service               2.3.0            py38h516909a_0    conda-forge
[conda] mkl_fft                   1.1.0            py38hc1659b7_1    conda-forge
[conda] mkl_random                1.1.0            py38hb3f55d8_0    conda-forge
[conda] numpy                     1.19.1           py38hbc911f0_0  
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py38_cu101    pytorch

## Additional Info

I'm using SLURM on a 1 GPU per node setup.
After hanging for a few seconds an exception is thrown on the remaining nodes:

     RuntimeError: NCCL error in: .../torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by henrique** [comment]
Sorry guys, I think we were misusing the API
as the docu says all groups have to be present in all nodes, so that seem to solve the problem
```
    groups = []
    n_groups = 2
    for g in range(n_groups):
        col_ranks = list(range(g, world_size, n_groups))
        groups.append(dist.new_group(ranks=col_ranks))

    rank_col = rank % n_groups
    col_group = groups[rank_col]
```


thanks for the amazing work on PyTorch!

**Comment by FrankLeeeee** [comment]
> Sorry guys, I think we were misusing the API
> as the docu says all groups have to be present in all nodes, so that seem to solve the problem
> 
> ```
>     groups = []
>     n_groups = 2
>     for g in range(n_groups):
>         col_ranks = list(range(g, world_size, n_groups))
>         groups.append(dist.new_group(ranks=col_ranks))
> 
>     rank_col = rank % n_groups
>     col_group = groups[rank_col]
> ```
> 
> thanks for the amazing work on PyTorch!

Hi Henrique, this is Shenggui and thanks for your help!😀
