### ISSUE TITLE
Could not find a version that satisfies the requirement torch=1.6.0

### ISSUE THREAD

**Issue by deKeijzer** [pytorch/pytorch#46205]
## 🐛 Bug

I am unable to install the latest stable PyTorch build for CUDA 10.2 using the command given by the PyTorch website for pip on Windows.

## To Reproduce

1. Go to the PyTorch website
2. Click on get started
3. Have the following settings:
- Stable (1.6.0)
- Windows
- Pip
- Python
- CUDA
4. This outputs `pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`, which gives the above error when entered in cmd with administrator rights. This is with the latest pip version 20.2.3.

The exact error message is as follows. 
`ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post)`
`ERROR: No matching distribution found for torch===1.6.0`

## Expected behavior

Successfully install PyTorch 1.6.0

## Environment

 - PyTorch Version (e.g., 1.0): -
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): -
 - Build command you used (if compiling from source): -
 - Python version: 3.8.3
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 2070 Super
 - Any other relevant information:

## Additional context

-

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
@deKeijzer looks like you are trying to install PyTorch using 32-bit Python runtime, which is not a supported. Please update your Python to 64-bit version and try again. 
If this is not the case, please do not hesitate to reopen the issue.

**Comment by deKeijzer** [comment]
Sorry for the late response, it has been quite busy. 

The problem seems to persist with Python 3.9.0 64-bit, CUDA 10.2 and pip 20.2.4.
