### ISSUE TITLE
tensorboard multiple add_graph()

### ISSUE THREAD

**Issue by hyunjaecho94** [pytorch/pytorch#46239]
Is it possible to add multiple graphs (multiple calls to add_graph(model_A), add_graph(model_B), etc). I tried it, but only the last called add_graph() gets shown on tensorboard. Thanks!

**Comment by bdhirsh** [comment]
Hi @hyunjaecho94 I'm going to close this issue and redirect you to the forum. Can you post your question there? https://discuss.pytorch.org/c/tensorboard/28
