### ISSUE TITLE
the different train speed between pip install torch==1.2 and build torch1.2 from source

### ISSUE THREAD

**Issue by wuyujiji** [pytorch/pytorch#46245]
## ❓ Questions and Help
Hi, recently I train a model with pytorch1.2. I found a phenomenon that train speed of each iter is different by installing pytorch from different ways. In details, the train speed by pip install torch==1.2 is  faster than about 3x than build torch1.2 from source. Could you please help me analyzing the reason? Thanks a lot ! 

### Envrionment
CUDA: 10.0
pytorch: 1.2
torchvison: 0.4
gcc version : devtools 3 ~ devtools 9 both all trys

### note
code and hardware environment confirm same

### build command
conda install -y python=3.6 numpy=1.16.4 pyyaml scipy ipython mkl=2019.1 mkl-include=2019.1 cython typing && \
conda install -y -c pytorch magma-cuda100 && \

git clone --recursive --branch v1.2.0 https://github.com/pytorch/pytorch.git && \
cd pytorch && \
source scl_source enable devtoolset-x (x is 3, 4, 6, ...) && \
export TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" && \
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"} && \
USE_FBGEMM=0 USE_SYSTEM_NCCL=0 /usr/local/conda/bin/python setup.py bdist_wheel -d /tmp/pytorch_pkg && \
pip3 install /tmp/pytorch_pkg/*.whl

**Comment by wuyujiji** [comment]
In face, I want to know the diffs of build ways between the pytorch official wheel package and mine

**Comment by bdhirsh** [comment]
Please use the forum for questions (https://discuss.pytorch.org/). Closing out this issue for now, but feel free to open a new issue if it turns out to be a feature request or bug.
