### ISSUE TITLE
Add dtype arg support to torch.linalg.norm with ord='fro' and ord='nuc'

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#46255]
## 🚀 Feature

`torch.linalg.norm` currently supports the `dtype` arg for all norm types except Frobenius and nuclear.

cc @ezyang @vincentqb @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff

**Comment by mruberry** [comment]
We would accept a PR adding this behavior.
