### ISSUE TITLE
0.3.0 availability on conda

### ISSUE THREAD

**Issue by donghwicha** [pytorch/pytorch#4629]
Hello. 

I installed 0.3.0 as below
>  conda install -y --name pytorch-py$PYTHON_VERSION -c soumith pytorch=0.3.0

and it looks to be successful

> # which python
>         /opt/conda/envs/pytorch-py3.5/bin/python
> # python
>         Python 3.5.4 |Anaconda, Inc.| (default, Nov 20 2017, 18:44:38)
>         [GCC 7.2.0] on linux
>         Type "help", "copyright", "credits" or "license" for more information.
>         >>> import torch
>         >>> print(torch.__version__)
>         0.3.0
>         >>> exit()
> 

but I can not find any build of 0.3.0 on conda repo.
https://anaconda.org/soumith/pytorch/files?sort=time&sort_order=desc

Can someone confirm whether pytorch 0.3.0  is available on conda repo?

**Comment by lanpa** [comment]
conda install pytorch torchvision -c `pytorch`

**Comment by blakeliu** [comment]
blake@blake-ubuntu:~$ conda install pytorch torchvision -c pytorch
Solving environment: done

## Package Plan ##

  environment location: /home/blake/anaconda3

  added / updated specs: 
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

    pytorch:     0.1.12-py35cuda8.0cudnn6.0_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    torchvision: 0.1.8-py35_0                 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)?

**Comment by koustuvsinha** [comment]
@blakeliu I solved it by the following:

```
conda create -n env python=3.5 mkl=2018 pytorch=0.3.0 -c pytorch -c intel
```

pytorch 0.3.0 requires mkl >= 2018 support, which is available in channel `intel`

**Comment by blakeliu** [comment]
@koustuvsinha  Thanks, "-c intel " is perfect solution!

**Comment by AngelaSunny** [comment]
conda install pytorch=0.3.0 torchvision -c pytorch

I test this command is right to install!

**Comment by MystikNinja** [comment]
Is there currently a way to install PyTorch 0.3.0 on WIndows?

**Comment by jiteshm17** [comment]
@AbhijeetKrishnan  , have you tried this `conda install -c peterjc123 pytorch`? It's from the conda  website
https://anaconda.org/peterjc123/pytorch

**Comment by Sendeman** [comment]
Running `conda install pytorch=0.3` gives
`Found conflicts! Looking for incompatible packages.                                                                                                                                            failed                                                                                                                                                                                             

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch=0.3 -> python[version='2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9|3.4.*',build='2_73_pypy|3_73_pypy|4_73_pypy|5_73_pypy|1_73_pypy|0_73_pypy']

Your python: python=3.6.0
`
Also trying `conda create -n env python=3.5 mkl=2018 pytorch=0.3.0 -c pytorch -c intel`
gives `UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package mkl conflicts for:
pytorch=0.3.0 -> mkl[version='>=2018.0.3,<2019.0a0']
pytorch=0.3.0 -> numpy[version='>=1.9'] -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.0|>=2019.4,<2021.0a0|>=2019.3,<2021.0a0|>=2019.1,<2021.0a0|>=2018.0.2,<2019.0a0|>=2018.0.1,<2019.0a0|>=2019.4,<2020.0a0']
mkl=2018

Package python conflicts for:
python=3.5
pytorch=0.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
pytorch=0.3.0 -> cffi -> python[version='2.7.*|3.6.*|>=3.7,<3.8.0a0|3.5.*|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.6.12|3.7.9|3.6.12|3.6.9|3.6.9|3.6.9|3.6.9|3.4.*',build='0_73_pypy|1_73_pypy|5_73_pypy|4_73_pypy|3_73_pypy|2_73_pypy']
`
I dont see how i can solve this issue and wether anyone else is experiencing the same? Im running ubuntu 20 LTS btw

**Comment by Vineet-the-git** [comment]
> conda create -n env python=3.5 mkl=2018 pytorch=0.3.0 -c pytorch -c intel


> Running `conda install pytorch=0.3` gives
> 
> ```
> Found conflicts! Looking for incompatible packages.                                                                                                                                            failed                                                                                                                                                                                             
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - pytorch=0.3 -> python[version='2.7.*|3.5.*|3.6.*|3.6.12|3.6.12|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9|3.4.*',build='2_73_pypy|3_73_pypy|4_73_pypy|5_73_pypy|1_73_pypy|0_73_pypy']
> 
> Your python: python=3.6.0
> ```
> 
> Also trying `conda create -n env python=3.5 mkl=2018 pytorch=0.3.0 -c pytorch -c intel` gives
> 
> ```
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> Package mkl conflicts for:
> pytorch=0.3.0 -> mkl[version='>=2018.0.3,<2019.0a0']
> pytorch=0.3.0 -> numpy[version='>=1.9'] -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.0|>=2019.4,<2021.0a0|>=2019.3,<2021.0a0|>=2019.1,<2021.0a0|>=2018.0.2,<2019.0a0|>=2018.0.1,<2019.0a0|>=2019.4,<2020.0a0']
> mkl=2018
> 
> Package python conflicts for:
> python=3.5
> pytorch=0.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
> pytorch=0.3.0 -> cffi -> python[version='2.7.*|3.6.*|>=3.7,<3.8.0a0|3.5.*|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.6.12|3.7.9|3.6.12|3.6.9|3.6.9|3.6.9|3.6.9|3.4.*',build='0_73_pypy|1_73_pypy|5_73_pypy|4_73_pypy|3_73_pypy|2_73_pypy']
> ```
> 
> I dont see how i can solve this issue and wether anyone else is experiencing the same? Im running ubuntu 20 LTS btw

I am also encountering the same issue. If anyone has a solution does provide it.
