### ISSUE TITLE
I'm compiling the pytorch 1.6.0 stable version on CUDA 11.1 and CUDNN 8.04 with 3090 and failed.

### ISSUE THREAD

**Issue by Heermosi** [pytorch/pytorch#46299]
## ❓ Questions and Help
So, that is 1.6.0 stable version failed on compiling caffe2 utils.

I'm running the nvidia-docker pulled from docker hub with cuda 11.1 and cudnn 8.04 installed, magma compiled with ampere compatible(should I explicitly specify sm_86?).

And I got this on compiling the code

```
#ifdef __CUDA_ARCH__
#if __CUDA_ARCH__ <= 800
constexpr int kWarpSize = 32;
#else
#error Unknown __CUDA_ARCH__; please define parameters for compute capability
#endif // __CUDA_ARCH__ types

```
It seems the code from caffe2 utils does not recognize sm_86 arch, so is that possible to overcome the problem with most up to date code? And should I explicitly specify the sm_86 instead of Ampere in magma compilation?
Thanks!

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zasdfgbnm** [comment]
1.6 does not support CUDA 11, please use a newer version

**Comment by Heermosi** [comment]
> 1.6 does not support CUDA 11, please use a newer version

Alright, I'll look into others...

**Comment by lemonahmas** [comment]
> 1.6 does not support CUDA 11, please use a newer version

Hi, may I get to know what version will be capable to use with cuda 11.1?

**Comment by zasdfgbnm** [comment]
@lemonahmas 1.7 will, but is not released yet. You can also use the master branch.

**Comment by Heermosi** [comment]
> > 1.6 does not support CUDA 11, please use a newer version
> 
> Hi, may I get to know what version will be capable to use with cuda 11.1?

geiniyigelianjie

[https://github.com/pytorch/pytorch/issues/45028]

neirongdazhiruxia:
1. shiyong nvidia-docker cuda11.0-devel
2. anzhuang anaconda3
3. `conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`

```
REPOSITORY                         TAG                             IMAGE ID            CREATED             SIZE
nvidia/cuda                        11.0-cudnn8-devel-ubuntu16.04   1741134981df        4 days ago          7.46GB
```

**Comment by lemonahmas** [comment]
> > > 1.6 does not support CUDA 11, please use a newer version
> > 
> > 
> > Hi, may I get to know what version will be capable to use with cuda 11.1?
> 
> geiniyigelianjie
> 
> [https://github.com/[/issues/45028](https://github.com/pytorch/pytorch/issues/45028)]
> 
> neirongdazhiruxia:
> 
> 1. shiyong nvidia-docker cuda11.0-devel
> 
> ```
> REPOSITORY                         TAG                             IMAGE ID            CREATED             SIZE
> nvidia/cuda                        11.0-cudnn8-devel-ubuntu16.04   1741134981df        4 days ago          7.46GB
> ```
> 
> 1. anzhuang anaconda3
> 
> ```
> apt-get update
> apt-get install wget
> wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh
> chmod +x Anaconda3-2020.07-Linux-x86_64.sh
> ./Anaconda3-2020.07-Linux-x86_64.sh
> ```
> 
> 1. anzhuang "pytorch nightly" (kenengxuyaofanqiang)
> 
> `conda install pytorch torchvision cudatoolkit=11 -c pytorch-nightly`

伸手党谢过 抱拳了老铁
