### ISSUE TITLE
CUDA elementwise ops should use common_dtype instead of output dtype to do computation

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#46302]
It seems that, many elementwise ops, such as those in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/UnaryGeometricKernels.cu are dispatching with `iter.dtype()` instead of `iter.common_dtype()`. This is not the same behavior as CPU. We should make them behaving the same way

cc: @mruberry 

cc @ngimel @nairbv @mruberry

**Comment by gchanan** [comment]
I don't think this causes a bug because our current unary ops require the same dtype(s).

**Comment by ngimel** [comment]
It does not cause bugs now, but in the linked PR cuda and cpu behavior is divergent because of this.

**Comment by nkaretnikov** [comment]
i have a related question. i've been recently looking at [BinaryOpsKernel.cpp](https://github.com/pytorch/pytorch/blob/c463d5009868e53ec07e90d0097c30c55280eef2/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp). many ops there just use `iter.dtype()`, which is the dtype of the 0th argument (by default). shouldn't `iter.common_dtype()` be used there instead? or are there actually situations where the former is preferred? if so, could you elaborate? there are also cases (in other files) where `self.scalar_type()` is used. is this documented somewhere? by looking at the code, it's not very clear to me what should actually be used and why.

**Comment by mruberry** [comment]
We should (almost?) never use `iter.dtype()` and (almost?) exclusively use `iter.common_dtype()` instead. 

`iter.dtype()` is the datatype of the output tensor in TensorIterator, and computation should be (conceptually) independent of the output. `iter.common_dtype()`, which could also have been named `iter.compute_dtype()`, is the datatype computations should be (conceptually) performed in. This distinction is only relevant when the datatype of the output and the common dtype differ.

Adding an OpInfo test for this behavior would be ideal but it's not completely obvious how to do so. Perhaps using float32 values not representable in float16 and verifying that the float16 versions of those values compute something distinct even when given an out tensor in the float32 datatype?

**Comment by mruberry** [comment]
The file in question has been updated; the few cases where this happens can probably be tracked as separate bugs.
