### ISSUE TITLE
support a kind of elementwise mul for sparse tensor

### ISSUE THREAD

**Issue by janelu9** [pytorch/pytorch#46307]
I think this kind of mul should be executed for sparse tensor , and it should still return a sparse tensor.

```
import torch
size = [5, 5]
I = [[0,2],[1,3]]
V = [1,1]
S = torch.sparse_coo_tensor(I, V, size)
D = torch.randn(size)
a=torch.rand([5,1])
torch.mul(a,D)

tensor([[ 0.6235, -0.1294, -0.1951, -0.0688, -0.2382],
        [-0.1456,  0.3778,  1.2844,  0.7334,  0.8117],
        [-0.0626, -0.0889, -0.3138, -0.1135, -1.6647],
        [ 0.1808, -0.3053, -0.2271, -0.1467,  0.0113],
        [-1.0513, -2.1013,  0.2088,  0.2355,  0.7727]])

torch.mul(a,S)
Traceback (most recent call last):

  File "<ipython-input-23-adefdc2bb4bf>", line 1, in <module>
    torch.mul(a,S)

RuntimeError: mul operands have incompatible sizes

```

cc @aocsa @nikitaved @pearu @mruberry

**Comment by heitorschueroff** [comment]
This is a good request and we would accept a patch that implements this feature. There are actually 2 things that need to be done, one is broadcasting which is what the current error you are getting is complaining about and the other is implementing mul between dense and sparse tensors. Operators such as torch.add do accept dense and sparse tensors but it also does not broadcast.

**Comment by pearu** [comment]
@janelu9 here's a quick workaround to `mul(a, S)` issue:
```
>>> torch.mul(a.expand(S.shape).sparse_mask(S.coalesce()), S)
```
