### ISSUE TITLE
Only nn.Parameters defined directly within nn.Module are listed in module.parameters()

### ISSUE THREAD

**Issue by SahilC** [pytorch/pytorch#4631]
I was trying to implement a custom neural network module when I encountered this bug. Only parameters which are defined as attributes of module directly are listed in module.parameters(). 

Code to reproduce bug:

    class Module1(nn.Module):
        def __init__(self, input_size, hidden_size):
            super(Module1, self).__init__()

            self.w_i = nn.Parameter(torch.FloatTensor(input_size, hidden_size))

    class Module2(nn.Module):
        def __init__(self, input_size, hidden_size):
            super(Module2, self).__init__()

            self.weights = {}
            self.weights['w_i'] = nn.Parameter(torch.FloatTensor(input_size, hidden_size))

    m = Module1(512, 512)
    print('m parameters:')

    for i in m.parameters():
         print(i)

    m2 = Module2(512, 512)
    print('m2 parameters:')

    for i in m2.parameters():
        print(i)

Pytorch version: 0.3.0 

It makes sense to have parameters which are nested within lists or dictionaries, so shouldn't module.parameters() list all parameters defined within a module?

**Comment by apaszke** [comment]
There are good reason why we don't want to traverse arbitrary Python data structures, with performance being the most important consideration. That's why we have `nn.ParameterList` and `nn.ModuleList`. `nn.Module()` can also be used as a dictionary-like object for both parameters and submodules.

**Comment by krishnakumar-kapil** [comment]
nn.ModuleDict() is also an option
