### ISSUE TITLE
COMPILE_TIME_MAX_DEVICE_TYPES is not changed as new DeviceType::Metal added.

### ISSUE THREAD

**Issue by chengjunlu** [pytorch/pytorch#46310]
The COMPILE_TIME_MAX_DEVICE_TYPES should be 12 instead of 11 when the new "Metal" has been added.

Metal value:
https://github.com/pytorch/pytorch/blob/d790ec6de01a61fe81733c41a64b6092bacfb7bd/c10/core/DeviceType.h#L27

COMPILE_TIME_MAX_DEVICE_TYPES  value:
https://github.com/pytorch/pytorch/blob/d790ec6de01a61fe81733c41a64b6092bacfb7bd/c10/core/DeviceType.h#L32

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by gchanan** [comment]
just confirming this is not a problem on 1.7.

**Comment by gchanan** [comment]
just confirming this is not a problem on 1.7.

**Comment by xta0** [comment]
> just confirming this is not a problem on 1.7.

No, The metal stuff was landed yesterday. it's only available on master

**Comment by xta0** [comment]
Have a fix here - https://github.com/pytorch/pytorch/pull/46327

**Comment by chengjunlu** [comment]
Thanks for the information.
Close this issue because there's a fix already.
