### ISSUE TITLE
[JIT] Unannotated NamedTuple Type should use TensorType::getInferred()

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#46326]
## 🐛 Bug / 🚀  Feature
```
import torch
from collections import namedtuple
_MyNamedTuple = namedtuple('_MyNamedTuple', ['value'])

@torch.jit.script
def foo():
    return _MyNamedTuple(1)
> Expected a value of type 'Tensor' for argument 'value' but instead found type 'int'.
```

It would be nice if we showed that the Tensor type was inferred because no type annotations were given for the named tuple. There was a user internally who was confused by this.

cc @gmagogsfm

**Comment by Lilyjjo** [comment]
Implementation pointers:

The error message is generated in torch/csrc/jit/frontend/schema_matching.cpp’s `tryMatchArgument(...)`. There are multiple ways of solving this issue, so feel free to take a different approach.  One way would be to get `is_inferred_type()` on the value’s type in this function to return true. The return value of `is_inferred_type()` is determined by /aten/src/ATen/core/type.cpp’s `TensorType::create(...)` that sets the `is_inferred_` value. You would need to track down where in the code NamedTuple calls this `TensorType::create(...)` and set the `is_inferred` bool to be true. If this isn’t feasible, then generating the error message when the type refinement of the unannotated variable for the NamedTuple could also work.

The code that deals with the NamedTuple can be found by searching for 'NamedTuple' in:
 torch/csrc/jit/python/python_sugared_value.cpp 
 torch/csrc/jit/frontend/sugared_value.cpp
 torch/csrc/jit/frontend/ir_emitter.cpp

**Comment by Lilyjjo** [comment]
For reference, this is a way to give the needed type annotations to resolve the error:
```
import torch
from typing import NamedTuple
_MyNamedTuple = NamedTuple('_MyNamedTuple', [('value', int)])

@torch.jit.script
def foo():
    return _MyNamedTuple(1)
```
