### ISSUE TITLE
Issues about symeig and svd on GPU

### ISSUE THREAD

**Issue by AkonLau** [pytorch/pytorch#4634]
When torch.symeig or torch.svb works on GPU, why it still occupies a lot of CPU? Is it a bug or not?
The code are D, V = torch.symeig(input1, eigenvectors=True ), U, D, V = torch.svb(input2). The input1 and input2 are all torch.cuda.FloatTensor type. When I test it on GPU , they still occupy a lot of GPU.
But when I try D= torch.symeig(input1 ) on the GPU, it didn't occupy CPU. Could you give me some advices?

**Comment by SsnL** [comment]
Do you mean svd? We use magma bindings to many linalg functions. Magma doesn't implement everything in GPU so it sometimes still makes some lapack calls.

**Comment by apaszke** [comment]
As @SsnL said there's not much we can do, because the work is delegated to a LAPACK library.

**Comment by yubeic** [comment]
@AkonLau I have the same issue and previously I didn't notice that symeig is running on the CPU. Recently I found this to be a bottleneck when I have multiple jobs running at the same time. I wonder if you have found a work around to have symeig running on the GPU. Thanks!

**Comment by Jerrypiglet** [comment]
Same issue here. I need to do svd on each batch training. I found the GPU version to be 10x slowers than CPU, and in my case I am transferring the tensor back to CPU, do SVD, and then back to GPU, and still 2X faster than CPU.... Do we have any fix for this? Thanks!
