### ISSUE TITLE
Enable batched gradient computation for torch.cdist

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#46342]
## 🐛 Bug

torch.cdist doesn't support batched gradient computation.

## To Reproduce

The following code attempts to compute a jacobian using batched gradient computation.
```
import torch
from torch import vmap
from torch.autograd import grad

N = 2
x = torch.randn(N, 3, requires_grad=True)
y = torch.randn(N, 3)
distances = torch.cdist(x, y)
flat_distances = distances.view(-1)

basis_vectors = torch.eye(N * N)
jacobian, = vmap(grad, (None, None, 0))(flat_distances, x, basis_vectors)
print(jacobian)
```
It errors out with `RuntimeError: Batching rule not implemented for aten::contiguous; the fallback path doesn't work on out= or view ops.`

## Expected behavior

No error. `vmap` has this issue where it cannot handle contiguous calls because it does not guarantee specific strides to be returned to the user. To fix this issue, we should move all .contiguous() calls out of the cdist formula in derivatives.yaml and into the cdist backward implementation. Please add a test to [TestBatchedGrad](https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/test/test_vmap.py#L1472) when you're done.

## Resources

(most of these probably won't be relevant) 
- [How to write a batching rule](https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/aten/src/ATen/BatchingRegistrations.cpp#L8-L49)
- [What is a BatchedTensorImpl](https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/aten/src/ATen/BatchedTensorImpl.h#L45-L55)
- [What is](https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/aten/src/ATen/VmapTransforms.h#L7-L26) [a vmap transform](https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/aten/src/ATen/VmapTransforms.h#L41-L47)
- [Sample batching rule implementation](
https://github.com/pytorch/pytorch/blob/635aebdfab20d9ace8ecfaf347102f0a49fa3553/aten/src/ATen/BatchingRegistrations.cpp#L210-L216)

**Comment by Sentient07** [comment]
Hello. is this fixed? if so which version of torch should I work on?
