### ISSUE TITLE
Add `inputs` argument to `autograd.backward()`

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#46373]
## 🚀 Feature
Update the `autograd.backward()` and `Tensor.backward()` APIs to have a `inputs` argument.
This will contain a list of leaf Tensors for which the `.grad` field should be populated.
All other leaf Tensors should be ignored.

## Motivation

This will enable the use of `.backward()` in NN use cases where only a subset of the `.grad` fiels should be updated.
This happen in the context of differentiable learning (in the [higher](https://github.com/facebookresearch/higher) library for example) and multi-model learning to be able to do a backward that will only change one model (saving extra forward/backward):

```python
modelA = Model()
modelB = Model()

# 1) Current code has to do
outA = modelA(inp)
outB = modelB(outA)

lossA = critA(outA, outB, label)
lossA.backward()
optA.step()

# We have to redo the forward in modelB
outB = modelB(outA.detach())
lossB = critB(outB, label)
lossB.backward()
optB.step()

# 2) With this new API
outA = modelA(inp)
outB = modelB(outA)

lossA = critA(outA, outB, label)
# Only populate grads in modelA
lossA.backward(inputs=modelA.parameters())

lossB = critB(outB, label)
# Only populate grads in modelB
lossB.backward(inputs=modelB.parameters())

optA.step()
optB.step()
```

## Implementation plan

- Update the python API and the python documentation (should accept any of list/tuple/generator of leaf Tensors)
- Update the Engine API (both [PythonEngine](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_engine.h) and [Engine](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/engine.h)) to know if we are performing a backward or a autograd.grad.
- Be careful, in the engine API, the "inputs" from the python API become "outputs" !
- Update the [execute function](https://github.com/pytorch/pytorch/blob/af8c75e2116a03aeaef131ef8007fae05546a3a3/torch/csrc/autograd/engine.cpp#L869-L871) to properly call `init_to_execute` with the right flags.
- Modify the [init_to_execute](https://github.com/pytorch/pytorch/blob/af8c75e2116a03aeaef131ef8007fae05546a3a3/torch/csrc/autograd/engine.cpp#L1082) function to mark as needed all the required Nodes.
  - Instead of adding captures, just mark each AccumulateGrad function from the outputs list as needed.
  - Run the discovery to mark all the other Nodes in the middle as needed as well.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved

**Comment by ezyang** [comment]
SGTM
