### ISSUE TITLE
rtx3090 with half precision shows lower speed than single precision

### ISSUE THREAD

**Issue by Ri0S** [pytorch/pytorch#46377]
## To Reproduce

1. any models with fp16

```
import torch
import torch.nn as nn
from torch.cuda.amp import autocast, GradScaler
import time
from torchvision.models import resnet152
class model(nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.resnet = resnet152()
        self.linear = nn.Sequential(nn.Linear(1000, 250),
                                    nn.Linear(250, 64),
                                    nn.Linear(64, 32),
                                    nn.Linear(32, 10),
                                    nn.ReLU())
    
    def forward(self, x):
        out = self.resnet(x)
        out = self.linear(out)

        return out


xx = torch.randn(10, 32, 3, 224, 224).cuda(0).type(torch.float16)
yy = torch.randint(0, 10, (10, 32)).cuda(0)
m = model().cuda(0).type(torch.float16)
criterion = nn.CrossEntropyLoss()
optim = torch.optim.Adam(m.parameters(), 1e-4)

start = time.time()

for epoch in range(5000):
    for x, y in zip(xx, yy):
        optim.zero_grad()
        output = m(x)
        loss = criterion(output, y)
        loss.backward()
        optim.step()
    print('time', time.time() - start)

```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.8.0.dev20201014+cu110
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090

Nvidia driver version: 455.23.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
## Additional context

fp16 takes about 14s per epoch, but fp32 takes about 3s per epoch.
I used amp and pytorch-lightning's half precision. but still slow

cc @ngimel @VitalyFedyunin

**Comment by ngimel** [comment]
cc @ptrblck, @mcarilli

**Comment by malfet** [comment]
@Ri0S is this specific to RTX3090 or happens on other GPUs as well? Also, would this be reproducible with the release build? (Because debug build of PyTorch is not optimized for performance)

**Comment by ptrblck** [comment]
After adding synchronizations to profile the code properly, it seems that `cudnn.benchmark = True` can yield a speedup for the provided workloads (while `benchmark=False` yields bad performance), so I would recommend to use it.
I've used the latest nightly binary with CUDA11.0+cudnn8.0.3 (`1.8.0.dev20201014`)  on a 3090.

Results:
|         | benchmark=False     | benchmark=True     |
|---------|---------------------|--------------------|
| float16 | 1362.216ms per iter | 167.216ms per iter |
| float32 | 244.964ms per iter  | 198.248ms per iter |

Code used:
```python
import torch
import torch.nn as nn
from torch.cuda.amp import autocast, GradScaler
import time
from torchvision.models import resnet152

torch.backends.cudnn.benchmark = True


class model(nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.resnet = resnet152()
        self.linear = nn.Sequential(nn.Linear(1000, 250),
                                    nn.Linear(250, 64),
                                    nn.Linear(64, 32),
                                    nn.Linear(32, 10),
                                    nn.ReLU())

    def forward(self, x):
        out = self.resnet(x)
        out = self.linear(out)

        return out

dtype = torch.float16
x = torch.randn(32, 3, 224, 224).cuda(0).to(dtype)
y = torch.randint(0, 10, (32,)).cuda(0)
m = model().cuda(0).to(dtype)
criterion = nn.CrossEntropyLoss()
optim = torch.optim.Adam(m.parameters(), 1e-4)

# warmup
for _ in range(10):
    m.zero_grad()
    output = m(x)
    loss = criterion(output, y)
    loss.backward()

nb_iters = 100

torch.cuda.synchronize()
t0 = time.time()
for _ in range(nb_iters):
    m.zero_grad()
    output = m(x)
    loss = criterion(output, y)
    loss.backward()

torch.cuda.synchronize()
t1 = time.time()
print('{:.3f}ms per iter'.format((t1 - t0)/nb_iters * 1000.))
```

Note that cudnn will provide the heuristics tuned for the 3090 in cudnn8.0.5, which it not released yet.

**Comment by Ri0S** [comment]
> @Ri0S is this specific to RTX3090 or happens on other GPUs as well? Also, would this be reproducible with the release build? (Because debug build of PyTorch is not optimized for performance)

I can't find any stable version with cuda 11. pytorch 1.6.0 version with cuda 10.2 can't use tensor in rtx3090. 
I tested in Titan X (Pascal) with same version in my issue. There is no significant difference from the stable version.

**Comment by xiaochus** [comment]
@Ri0S  Same as my rtx 3070，amp mode cost more training time than normal mode in my task. The experiment result shows below, it sames that amp take bad performance in training period except memory cost.

**version:**
cuda 11.1
cudnn 8
pytorch 1.7

**tqdm epoch cost:**
| Mode| epoch cost| 
| ------- |:---:| 
| AMP| 04:23 | 
| Normal| 04:21 | 

**cost count without dataloader, benchmark=False**
| Mode| epoch cost| avg batch cost| Memory| 
| ------- |:---:| :--:| :--: |
| AMP| 115.2s| 0.31s| 6.6 G| 
| Normal| 36.6s| 0.09s| 7.0 G| 


**cost count without dataloader, benchmark=True**
| Mode| epoch cost| avg batch cost| Memory| 
| ------- |:---:| :--:| :--: |
| AMP| 92.3s| 0.22s| 6.4 G| 
| Normal| 39.7s| 0.11s| 7.3 G|
