### ISSUE TITLE
A few question about sharing weights of convolution kernels and your dilation convlution

### ISSUE THREAD

**Issue by zhongqiu1245** [pytorch/pytorch#46387]
1,Could you tell me how can I achieve multiple convolution kernels sharing the same weight? If I want to make 4 convolution kernels to share 1 weight.
2,May I ask whether the implementation of dilated convolution is to generate a convolution kernel with a dilation rate = r as in the original paper or to periodically sample the feature map at equal intervals, then convolve with a common convolution kernel, and then resample the image Spell back the original feature map size（As mentioned in "Smoothed Dilated Convolutions for Improved Dense Prediction"?）?

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask question about PyTorch

If you feel something is not working as expected, please do not hesitate to file a separate issue
