### ISSUE TITLE
Replace list(map(lambda constructs by list comprehension

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#46392]
During debugging I've seen many constructs like `list(map(lambda i: torch.device('cuda:' + str(i)), gpus))`

I'd propose to replace those by "regular" list comprehensions. So the above is equivalent to `[torch.device('cuda:' + str(i)) for i in gpus]`

This replacement can be automated via regexp replacement for (likely) almost all cases.

Reasoning: The nesting of parentheses and the inline lambda make it harder to read than the pythonic approach using list comprehensions. It is also likely that the latter is faster as the intent is clearer to the runtime and being widely used it is likely well  optimized

**Comment by malfet** [comment]
Thank you for suggestion. If you have a PR that addresses that already, I would gladly review it

**Comment by Flamefire** [comment]
Created #46461 and #46462 addressing this. Note how the intend is clearer, especially in complex cases which even led to discovery of a bug in the test code.
