### ISSUE TITLE
Addition of two vectors results in 2d matrix

### ISSUE THREAD

**Issue by ehannigan** [pytorch/pytorch#4641]
I am adding two tensors that should be the same size. However, I noticed in my code, that one was a 2d (16x1) tensor, and the other was a 1d (16) vector. The addition of the two resulted in a 2d (16x6) tensor. This does not seem to be an intuitive result. Am I missing something from the documentation, or is this a bug? 
```
import torch
x1 = torch.ones(16)
x2 = torch.ones((16,1))
x3 = torch.add(x1,x2)
print 'x1', x1
print 'x2', x2
print 'x3', x3
```

x3 is a 16x16 matrix of 2's.

**Comment by soumith** [comment]
PyTorch implements broadcasting (like numpy does).
Please read https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html for more details.
