### ISSUE TITLE
Pytorch's Participation in GSOC 18!!

### ISSUE THREAD

**Issue by kapilkd13** [pytorch/pytorch#4642]
Hi I am a Pytorch user and a GSOC 17 participant. I want to discuss the possibility of Pytorch's participation in GSOC 2018. Personally, I think this would be great way to engage young developers who may later become core developers and help in maintaining Pytorch, meanwhile achieving some key milestones for Pytorch as part of their project. more info can be found here https://summerofcode.withgoogle.com/
What do you guys think about it?

**Comment by soumith** [comment]
Thanks Kapil, we'll definitely consider it.

**Comment by kapilkd13** [comment]
Hi @soumith have you decided if you would be participating in GSOC 2018? Tomorrow is the last day of Organization application.

**Comment by vishwakftw** [comment]
Could this be closed in favor of #26802?
