### ISSUE TITLE
[RFC] A general C10D_DEBUG_LEVEL flag for verbose DDP/torch.distributed logging

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#46434]
## 🚀 Feature

We should introduce an environment variable `C10D_DEBUG_MODE` that DDP/torch.distributed can read and configure an appropriate logging level based on the requested verbosity. More verbose logging could result in reduced performance while performance should not be impacted by the lowest verbosity level of the logging.

Listing some ideas for what we could dump as part of this logging:
1) Information about current in-flight collective communication operations (type of operation, tensor shapes, participating ranks/group, etc)
2) Log information when a collective communication operation is kicked off and completed (such as the rank, tensor shapes, and type of operation)
3) Specifically for ProcessGroupNCCL, the currently pending GPU operations
4) Logs regarding node discovery/process group initialization and teardown, as well as when any process writes information (such as info about aborted operations) to the common shared store.

Feel free to also comment with additional items that could aid debugging if we logged them.

The current log levels to consider:
0 - OFF - No additional logging. 
1 - WARN - Logging that should not affect the application performance, but could provide details underneath the hood when we are about to throw an error, timeout, have an operation take too long, etc. We can consider setting this as the default because it provides some details and should not impact application performance. 
2 - INFO - Detailed logging that could moderately impact application performance, and provides a clear view into what is going on underneath the hood during regular execution. 
4 - DETAIL - The most detailed type of logging. Could itself perform collective communication if needed to communicate information across ranks for logging purposes. This type of logging can hinder application performance but provides the most detailed view into what is going on underneath the hood. 

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @xush6528

**Comment by pritamdamania87** [comment]
We should probably add per process group sequence numbers for each collective op that we log. That way we can clearly see from logs if there are any mismatched collective ops by comparing the sequence numbers of the last operation on all ranks.

**Comment by rohan-varma** [comment]
@pritamdamania87 Thanks for bringing that up. To clarify, will the sequence numbers just be used for debugging purposes (i.e. each process group starts off at a rand() sequence no. and increments it for each collective), or would we want to do some collective comm. logic on all these sequence numbers itself (i.e. allgather them to ensure all collective ops are produced in the correct order, to prevent hang-related errors)? I suppose that we can make it flexible for both purposes, and can control whether we do the latter with the level of debugging verbosity that we need.

**Comment by pritamdamania87** [comment]
@rohan-varma As a first step, I think just using them for debugging purposes is good where we log each collective's details and its sequence number on each rank. Regarding the second idea of preventing hang related errors, it might be tricky to do this for example if a node never called a particular collective, then your allgather for the sequence numbers would hang as well right?

**Comment by rohan-varma** [comment]
@pritamdamania87 That's true, although I'm wondering if that failure/hang will be better debugability wise as we'd know the sequence number (from the calls from the other nodes) when we fail in this scenario. Although, I guess if we verify the sequence number via collective calls and fail, it's not much better than issuing the original collective call, and then reporting the faulty sequence number in the error message.

**Comment by rohan-varma** [comment]
Also related, ProcessGroup wrapper to aid collective desync: https://github.com/pytorch/pytorch/issues/22071

**Comment by rohan-varma** [comment]
TORCH_DISTRIBUTED_DEBUG now exists and is documented here: https://pytorch.org/docs/master/distributed.html#debugging-torch-distributed-applications
