### ISSUE TITLE
How can I use parallel cudastreams in multi threads?

### ISSUE THREAD

**Issue by litttl** [pytorch/pytorch#46451]
thread task codes as follow：
void* task_routine3(void** arg)
{
    struct timeval time_cur;
    auto options = torch::TensorOptions().device(torch::kCUDA, 0);
    torch::Device device(torch::kCUDA, 0);

    pthread_t tid = pthread_self();
    std::cout << tid << "Start time:" << time_cur.tv_sec << ":" << time_cur.tv_usec << std::endl;
    at::cuda::CUDAStream mystream = at::cuda::getStreamFromPool();
    at::cuda::setCurrentCUDAStream(mystream);

    {
        at::cuda::CUDAStreamGuard guard(mystream);
        std::cout << "Stream ID: " << mystream.id() << std::endl;

        torch::Tensor* pt_base_feature_cpu = (torch::Tensor*) arg[0];
        torch::Tensor* pt_match_feature_cpu = (torch::Tensor*) arg[1];

        for(int i = 0; i < 10; i++)
        {
            torch::Tensor base_feature = (pt_base_feature_cpu->slice(0, i*50000, (i+1)*50000, 1)).to(device);
            torch::Tensor match_feature = (*pt_match_feature_cpu).to(device);

            torch::Tensor tensor_tmp;
            torch::Tensor tensor_sum;
            std::tuple<torch::Tensor, torch::Tensor> sort_ret;

            tensor_tmp = torch::sub(base_feature, match_feature);
            tensor_tmp = torch::pow(tensor_tmp, 2);
            tensor_sum = torch::sum(tensor_tmp, 1);
            sort_ret = torch::topk(tensor_sum, 1);
        }
    }
}

I use thread pools to run the thread-func in multi-threads.  I found that running time using single thread is seem to multi threads. T want to using multi threads to save running time. Erery thread I get a new GPUStream, but it doesn't work well.
How can I do it? Anyone can help me?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by xsacha** [comment]
Each thread will have its own cuda stream already.

Manual use of the streams is only if you want to use multiple streams within the same thread.

**Comment by ailzhang** [comment]
Please redirect all questions to the forum as suggested in the template, thanks!
