### ISSUE TITLE
Error when using TorchScript with autograd

### ISSUE THREAD

**Issue by mbanani** [pytorch/pytorch#46483]
When trying to apply torch.jit.script on a function that calls `torch.autograd.grad`, I ran into the following error: 

```
aten::grad(Tensor[] outputs, Tensor[] inputs, Tensor?[]? grad_outputs=None, bool? retain_graph=None, bool create_graph=False, bool allow_unused=False) -> (Tensor?[]):
Expected a value of type 'List[Tensor]' for argument 'outputs' but instead found type 'Tensor'.
```

If I understood the error correctly, it's expecting the output of `torch.autograd.grad` to be a List of tensors but found a Tensor, when the output is a tuple of tensors. 

I suspect the issue to be in this line, but I am not sure: https://github.com/pytorch/pytorch/blob/93650a82c9ffc96f8c65a1912e42c31fb4c84c75/torch/csrc/jit/runtime/register_prim_ops_fulljit.cpp#L100

Thanks for your help!

-------
Here's a minimal script to reproduce the issue:
```python
import torch

x = torch.randn(16, 30, 10, requires_grad=True).cuda()
y = torch.randn(16, 10, 1, requires_grad=True).cuda()
z = torch.randn(16, 30, 1, requires_grad=True).cuda()


@torch.jit.script
def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad(diff.mean(), y)
    y = y - grad[0]
    return y
```

Full trace: 
```
Traceback (most recent call last):
  File "test_jit.py", line 9, in <module>
    def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
  File "/home/mbanani/util/miniconda3/envs/p3d/lib/python3.6/site-packages/torch/jit/__init__.py", line 1550, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError:

aten::grad(Tensor[] outputs, Tensor[] inputs, Tensor?[]? grad_outputs=None, bool? retain_graph=None, bool create_graph=False, bool allow_unused=False) -> (Tensor?[]):
Expected a value of type 'List[Tensor]' for argument 'outputs' but instead found type 'Tensor'.
:
  File "test_jit.py", line 12
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad(diff.mean(), y)
           ~~~~~~~~~~~~~~~~~~~ <--- HERE
    y = y - grad[0]
```

cc @gmagogsfm

**Comment by wconstab** [comment]
@mbanani Can you say a little more about your motivation for using grad in a script function?  I'm not sure if the specific failure you reported is a bug we expect to work, but in general the pattern we usually support with JIT is to script the 'forward' function and handle grad/optim outside.

**Comment by mbanani** [comment]
@wconstab Thank you for the quick response. Part of my forward loop is a greedy iterative optimization where I calculate the gradient with respect to an intermediate variable and update it several times. This is by far the slowest part of my pipeline, so I was hoping that JIT might speed it up. I thought I'd raise the issue since the reported error was a type mismatch, and not an unsupported function (eg, `x.new_tensor()`). Do you think that JIT might help here?

**Comment by zylustc** [comment]
I  have encountered the same problem. Even I modify the grad = torch.autograd.grad([diff.mean(),], [y,]). I still receive the error 
'''
 aten::sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'number' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.int(int a, int b) -> (int):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.float(float a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.int_float(int a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.float_int(float a, int b) -> (float):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub(Scalar a, Scalar b) -> (Scalar):
  Expected a value of type 'number' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  sub(float a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  sub(int a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.
'''

Thanks for any help given.

**Comment by mbanani** [comment]
Hi @zylustc, I spent some time struggling with those issues so I could try to help. Could you provide a minimal script to reproduce the issue?

**Comment by zylustc** [comment]
> Hi @zylustc, I spent some time struggling with those issues so I could try to help. Could you provide a minimal script to reproduce the issue?
> 
> It seems the issue might arise from how you defined the variables for jit. it seems like you have a subtraction where the second part of the subtraction is not guaranteed to be a tensor.

Thanks for your response, and sorry for the delay. I used the same script that you used and modified it as the comments
```
import torch

x = torch.randn(16, 30, 10, requires_grad=True)
y = torch.randn(16, 10, 1, requires_grad=True)
z = torch.randn(16, 30, 1, requires_grad=True)


@torch.jit.script
def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])
    y = y - grad[0]
    return y
```
I've also found that any manipulation of the tensor "grad" will cause the error. If I return the "grad" directly from the following script, these jits will succeed:
```
import torch

x = torch.randn(16, 30, 10, requires_grad=True)
y = torch.randn(16, 10, 1, requires_grad=True)
z = torch.randn(16, 30, 1, requires_grad=True)


@torch.jit.script
def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])
    return grad[0]
```

**Comment by mbanani** [comment]
Ohh interesting. I am not sure how my initial code run given that it didn't handle this potential output of grad. It seems that since grad can be None, you need to handle that case in your jit script. This should work; not sure if this is best practice though. 

```python
@torch.jit.script
def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])[0]
    if grad is not None:
        y = y - grad
    return y
```

**Comment by zylustc** [comment]
> Ohh interesting. I am not sure how my initial code run given that it didn't handle this potential output of grad. It seems that since grad can be None, you need to handle that case in your jit script. This should work; not sure if this is best practice though.
> 
> ```python
> @torch.jit.script
> def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
>     xy = torch.bmm(x, y)
>     diff = z - xy
>     grad = torch.autograd.grad([diff.mean(),], [y,])[0]
>     if grad is not None:
>         y = y - grad
>     return y
> ```

It still leads to the same error, and I can pretty sure that the grad is not None in my practice. Anyway, thanks very much for your kind help.

**Comment by mbanani** [comment]
That's weird. Would you mind sharing the trace for this error? 

For context, I am using PyTorch 1.7. This is my trace without the None checking:

```
Traceback (most recent call last):
  File "test_jax.py", line 9, in <module>
    def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
  File "/Users/mohamed/miniconda3/lib/python3.6/site-packages/torch/jit/_script.py", line 940, in script
    qualified_name, ast, _rcb, get_default_args(obj)
RuntimeError:
Arguments for call are not valid.
The following variants are available:

  aten::sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.

  aten::sub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'number' for argument 'other' but instead found type 'Optional[Tensor]'.

  aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.

  aten::sub.int(int a, int b) -> (int):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.

  aten::sub.float(float a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.

  aten::sub.int_float(int a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.

  aten::sub.float_int(float a, int b) -> (float):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.

  aten::sub(Scalar a, Scalar b) -> (Scalar):
  Expected a value of type 'number' for argument 'b' but instead found type 'Optional[Tensor]'.

  sub(float a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.

  sub(int a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.

The original call is:
  File "test_jax.py", line 13
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])[0]
    y = y - grad
        ~~~~~~~~ <--- HERE
    return y
```

**Comment by zylustc** [comment]
> That's weird. Would you mind sharing the trace for this error?
> 
> For context, I am using PyTorch 1.7. This is my trace without the None checking:
> 
> ```
> Traceback (most recent call last):
>   File "test_jax.py", line 9, in <module>
>     def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
>   File "/Users/mohamed/miniconda3/lib/python3.6/site-packages/torch/jit/_script.py", line 940, in script
>     qualified_name, ast, _rcb, get_default_args(obj)
> RuntimeError:
> Arguments for call are not valid.
> The following variants are available:
> 
>   aten::sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> (Tensor):
>   Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> (Tensor):
>   Expected a value of type 'number' for argument 'other' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> (Tensor(a!)):
>   Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.int(int a, int b) -> (int):
>   Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.float(float a, float b) -> (float):
>   Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.int_float(int a, float b) -> (float):
>   Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub.float_int(float a, int b) -> (float):
>   Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   aten::sub(Scalar a, Scalar b) -> (Scalar):
>   Expected a value of type 'number' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   sub(float a, Tensor b) -> (Tensor):
>   Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
>   sub(int a, Tensor b) -> (Tensor):
>   Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.
> 
> The original call is:
>   File "test_jax.py", line 13
>     diff = z - xy
>     grad = torch.autograd.grad([diff.mean(),], [y,])[0]
>     y = y - grad
>         ~~~~~~~~ <--- HERE
>     return y
> ```
 of course,
```
Traceback (most recent call last):
  File "test7.py", line 9, in <module>
    def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
  File "/share/home/bjiangch/group-zyl/.conda/envs/Pytorch-GPU/lib/python3.8/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> (Tensor):
  Expected a value of type 'number' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.out(Tensor self, Tensor other, *, Scalar alpha=1, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'other' but instead found type 'Optional[Tensor]'.
  
  aten::sub.int(int a, int b) -> (int):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.float(float a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.int_float(int a, float b) -> (float):
  Expected a value of type 'float' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub.float_int(float a, int b) -> (float):
  Expected a value of type 'int' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  aten::sub(Scalar a, Scalar b) -> (Scalar):
  Expected a value of type 'number' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  sub(float a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.
  
  sub(int a, Tensor b) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'b' but instead found type 'Optional[Tensor]'.

The original call is:
  File "test7.py", line 13
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])
    y = y - grad[0]
        ~~~~~~~~~~~ <--- HERE
    return y
```
The version of pytorch is 1.7.1.

**Comment by mbanani** [comment]
On my machine with pytorch 1.7.1, I found that the original code produces that error, but adding the `if grad is not None` condition solves the problem. Specifically, here's the updated code. 
```
@torch.jit.script
def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
    xy = torch.bmm(x, y)
    diff = z - xy
    grad = torch.autograd.grad([diff.mean(),], [y,])[0]
    if grad is not None:
        y = y - grad
    return y
```

Not sure why it doesn't solve it on your side. Good luck!

**Comment by zylustc** [comment]
> On my machine with pytorch 1.7.1, I found that the original code produces that error, but adding the `if grad is not None` condition solves the problem. Specifically, here's the updated code.
> 
> ```
> @torch.jit.script
> def sample_function(x: torch.Tensor, y:torch.Tensor, z:torch.Tensor):
>     xy = torch.bmm(x, y)
>     diff = z - xy
>     grad = torch.autograd.grad([diff.mean(),], [y,])[0]
>     if grad is not None:
>         y = y - grad
>     return y
> ```
> 
> Not sure why it doesn't solve it on your side. Good luck!

I made a mistake and gave the wrong information. I just found that your idea can solve this problem. I apologize for that and it's very kind of you that helped me deal with this problem.
