### ISSUE TITLE
LU pivoting is inconsistent with scipy.linalg

### ISSUE THREAD

**Issue by dme65** [pytorch/pytorch#46496]
## 🐛 Bug

`torch.lu` returns a 1-indexed pivoting vector, which is inconsistent with for example `scipy.linalg`. This behavior is correctly documented, though.

## To Reproduce

```
>>> import scipy.linalg
>>> import torch

>>> A = torch.randn(3, 3)
>>> _, piv1 = torch.lu(A)
>>> print(piv1)
>>> _, piv2 = scipy.linalg.lu_factor(A)
>>> print(piv2)
```

Example output: 
```
tensor([2, 2, 3], dtype=torch.int32)
[1 1 2]
```

## Expected behavior

This isn't an issue for users that only use the LU factorization to work with `torch.lu_unpack` and `torch.lu_solve` as they don't need to explicitly work with the pivoting vector, but it's a bit awkward if you work directly with the pivoting vector to, e.g., incrementally update the factorization. It would be better to default to 0-indexing and be consistent with `scipy.linalg`.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] botorch==0.3.1
[pip3] gpytorch==1.2.0
[pip3] numpy==1.18.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] botorch                   0.3.1                    pypi_0    pypi
[conda] gpytorch                  1.2.0                     dev_0    <develop>
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py38hfbe908c_0
[conda] mkl_fft                   1.1.0            py38hc64f4ea_0
[conda] mkl_random                1.1.1            py38h959d312_0
[conda] numpy                     1.18.5           py38h1da2735_0
[conda] numpy-base                1.18.5           py38h3304bdc_0
[conda] numpydoc                  1.1.0                      py_0
[conda] pytorch                   1.6.0                   py3.8_0    pytorch
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

cc @jlin27 @mruberry @vishwakftw @jianyuh @nikitaved @pearu @heitorschueroff @rgommers

**Comment by dme65** [comment]
cc: @Balandat, @vishwakftw

**Comment by nikitaved** [comment]
I would probably add that some documentation on what these `pivs` actually encode is much appreciated, because they do not represent the permutation of the form `i -> sigma(i)`, which was very confusing to me.

**Comment by nikitaved** [comment]
After doing some experiments and reading the documentation for `lu_factor`. Both methods, `torch.lu` and `scipy.linalg.lu_factor` return the same LAPACK pivots. The difference is that SciPy returns the 0-indexed ones, and PyTorch seems to return the 1-based, no?

**Comment by dme65** [comment]
Correct, subtracting of 1 gives the desired results, but why return 1-indexed pivots when tensors are 0-indexed?

Agreed on LAPACK pivots being a bit confusing.  You have to loop through the vector and do all the swaps to get the pivoting vector to apply to the rows of the right hand side when solving linear systems.

**Comment by nikitaved** [comment]
> Correct, subtracting of 1 gives the desired results, but why return 1-indexed pivots when tensors are 0-indexed?
Agree, I am not aware of the motivation behind it.

A bit on the relevant note, I am working on making LU differentiable, and for that I need `lu_unpack`. However, the interconnection between modules + scripting + `autograd.Function` is a bit problematic and hacky. That could be a good call for making `lu_unpack` implemented in ATen rather, so that LU_backward is in ATen and all the issues with jit are resolved.

Moreover, `lu_unpack` could benefit from TensorIterator for the final permutation.

**Comment by vadimkantorov** [comment]
(I was also once confused by pivot format: https://discuss.pytorch.org/t/torch-lu-pivots-are-not-permutations-sometimes/53825 )

**Comment by nikitaved** [comment]
Yeah, it makes sense to update the doc to clarify them, and the fact that in order to get the final permutation, you have to multiply all the intermediate transpositions encoded by the data returned by LAPACK.

**Comment by mruberry** [comment]
Updating the documentation sounds great. We could also look at implementing torch.linalg.lu consistent with SciPy's in the future.

**Comment by nikitaved** [comment]
LAPACK returns 1-indexed pivots because of Fortran, SciPy subtracts 1 to make it C-style. Is there a chance that PyTorch will switch to the C-style indexing, @mruberry ?

The reason I am asking is because now that LU does support backward, I want to extend it to LU_solve. LU_solve is in ATen, and I need `lu_unpack` which comes from Python. Hence I either need to implement `lu_unpack` in ATen, or create Python interfaces for `lu_solve`. The latter could be quite complicated I guess, primarily because of JIT and the inability to script `autograd.Function`.

**Comment by Balandat** [comment]
I definitely support getting rid of 1-indexing in all user-facing functions for consistency, this is just too big of a gotcha.

**Comment by mruberry** [comment]
> LAPACK returns 1-indexed pivots because of Fortran, SciPy subtracts 1 to make it C-style. Is there a chance that PyTorch will switch to the C-style indexing completely, @mruberry, not just in `torch.linalg` namespace?

I think we should, but we need to be mindful of deprecating these functions for existing users. In this case we have an easy solution - we can create a new function with the updated behavior for people to switch to and leave (possibly deprecating) the previous one.

**Comment by dme65** [comment]
> > LAPACK returns 1-indexed pivots because of Fortran, SciPy subtracts 1 to make it C-style. Is there a chance that PyTorch will switch to the C-style indexing completely, @mruberry, not just in `torch.linalg` namespace?
> 
> I think we should, but we need to be mindful of deprecating these functions for existing users. In this case we have an easy solution - we can create a new function with the updated behavior for people to switch to and leave (possibly deprecating) the previous one.

In that case we can change the name from `torch.lu` to `torch.linalg.lu_factor`, which is the name SciPy uses anyway, and then we can eventually deprecate `torch.lu`.

**Comment by Lezcano** [comment]
Almost a year later, we can proudly say that we have a new and shiny [`torch.linalg.lu_factor`](https://pytorch.org/docs/master/generated/torch.linalg.lu_factor.html)!! Now, this function still returns the 1-based indices. 

The rationale behind this is that this function is pretty much exposed to be used in conjunction with  `torch.lu_solve` (soon to be `torch.linalg.lu_solve` with some new extra features). As such, if we returned a 0-based index, if anyone does `lu_factor` + `lu_solved`, we'd decreasing the pivots by one in the first one, just to add one again in the second one. As this is the intended usage of this function, this is not great.

I think that tinkering manually with the pivots is a fairly involved task already, so adding one extra step at the beginning doing `pivots = pivots - 1` will not hurt too much.
