### ISSUE TITLE
Unable to load entire model (with class definition)

### ISSUE THREAD

**Issue by Waasem** [pytorch/pytorch#46525]
## 🐛 Bug

Following the steps in https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html, I have saved a CNN model from CNN architecture at https://github.com/pytorch/examples/tree/master/mnist. But when I load the model for inference, I get an error.

## To Reproduce

a. # Specify a path and instantiate the model.
PATH = "entire_model.pt"
model = Net()
b. # Save
torch.save(model, PATH)
c. # Load
model = torch.load(PATH)
d. # Call evaluate
model.eval()

AttributeError Traceback (most recent call last)
<ipython-input-4-89809e6d3522> in <module>()
   PATH = '/content/sample_data/entire_model.pt'
model = torch.load(PATH)/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
unpickler = pickle_module.Unpickler(f, **pickle_load_args)
unpickler.persistent_load = persistent_load
result = unpickler.load()
deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

AttributeError: Can't get attribute 'Net' on <module '__main__'> 

## Expected behavior
 I expect to load the model and use for inference but I get the above error.

## Environment

 - PyTorch Version (e.g., 1.0):1.6.0
 - OS (e.g., Linux): Ubuntu 20.0
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.2, 3.6.10
 - CUDA/cuDNN version:+cu101

**Comment by ganeshbhargav** [comment]
The error after running the code is `AttributeError: Can't get attribute 'Net' on <module 'main'>`.

An AttributeError means that the program tried to use an attribute of an object, but the object did not have the requested attribute.

The line with the error must be the below code :-
`	model = Net()`

Explanation: 
Python tried to create an Object of Net class, but could not find the class definition.
The steps in the link shared https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html have the definition of class Net().

Please include the code for class Net() and run the code.
This should resolve the error.

**Comment by Waasem** [comment]
@ganeshbhargav : Thanks for your response. You are right about the model class definition Net(). But this is counter-intuitive in a sense that I want to use the saved model for inference at a system which does not know about the class definition. So how would I load a model for inference without knowing the class it was defined on? Moreover, my pipeline of code uses varying structures of models for training and use each of these saved models for inference at a remote system. So, sharing the class definition with each model for inference doesn't seem to be appropriate.

**Comment by ezyang** [comment]
In that case you would look for something like TorchScript as a way of more hermetically exporting the entirety of your model. I suggest asking on the forums for more guidance here.
