### ISSUE TITLE
Could not check compiler version in cpp_extension.py

### ISSUE THREAD

**Issue by zerovirus123** [pytorch/pytorch#46527]
Hi there, I found a Windows build for detectron2: https://github.com/conansherry/detectron2. Seeing how there is no official Windows support, I thought that it is a good alternative. 

I am trying to install the module in my Anaconda environment. However, I encountered this error during the build process.

```
running build
running build_py
running build_ext
min version:  (19, 0, 24215)
cl
C:\Users\Deployment\.conda\envs\sliding_windows_py37_copy\lib\site-packages\torch\utils\cpp_extension.py:239: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
```

It seems like cpp_extension.py could not locate the MSVC compiler. I am using Microsoft Visual Studios 2019 and I am certain that it has a functional compiler. 

Below are my build settings.

```
    Python: 3.7
    CUDA: 10.1
    PyTorch: 1.6.0
    Torchvision: 0.7.0
    Microsoft Visual Studio: 2019
```

Is there a workaround for this issue? Or does PyTorch have no support for MSVC compilers?

cc @yf225 @glaringlee @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by ezyang** [comment]
I know peterjc123 has improved support for cpp extension in the past, but I am not sure why it is not working here. There should be a vcvars bat file that you can use to add MSVC to the PATH; trying running that before running your Python script.

**Comment by peterjc123** [comment]
Are you sure you are using PyTorch 1.6.0? https://github.com/pytorch/pytorch/blob/v1.6.0/torch/utils/cpp_extension.py#L239 refers to a line with comments only.

**Comment by zerovirus123** [comment]
Hi guys. I downloaded MSVC C++ build tools and added it to PATH, and now the builder can locate a compiler. Thanks for your help.
