### ISSUE TITLE
Overhead when using torch multiprocessing

### ISSUE THREAD

**Issue by wagnifico** [pytorch/pytorch#46529]
## 🐛 Bug

I'm implementing a testing script and I observed a great increase in the execution time, both in CPU and GPU, when using the multiprocessing module. The total time only increases when adding workers. For the sample code presented further, the elapsed time is multiplied by 12 comparing a fully serial call and multiprocessing with a single worker.

When running in CPU, there is a big overhead in the models forward call. In GPU, the forward takes the same time, but the overall running time is larger than the single proc execution, probably due to independent CUDA initiation. By encapsulating the function with cProfile.runctx I get the following profiling outputs:

1. No multiprocessing:

```
         51 function calls (49 primitive calls) in 0.042 seconds

   Ordered by: cumulative time
   List reduced from 19 to 3 due to restriction <'(forward)'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.042    0.042 multiprocessing_overhead_mwe.py:21(forward)
        2    0.000    0.000    0.041    0.020 conv.py:418(forward)
        2    0.000    0.000    0.041    0.020 conv.py:410(_conv_forward)
```

2. 10 workers (CPU):

```
         51 function calls (49 primitive calls) in 0.542 seconds

   Ordered by: cumulative time
   List reduced from 19 to 3 due to restriction <'(forward)'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.542    0.542 multiprocessing_overhead_mwe.py:21(forward)
        2    0.000    0.000    0.483    0.241 conv.py:418(forward)
        2    0.000    0.000    0.483    0.241 conv.py:410(_conv_forward)
```

These are my performance results with the example code for number of workers from 0 (no multiprocessing) to 10:

![graph_scalabity_total](https://user-images.githubusercontent.com/73096490/96422810-cafbe700-11f8-11eb-963a-59b1210b0247.png)

![graph_scalabity_forward](https://user-images.githubusercontent.com/73096490/96422814-cd5e4100-11f8-11eb-83fd-b78746d2dff4.png)

Same behavior was observed using a cpu-only installation. Also, I'm obligated to use `spawn` method, even when no CUDA operations are performed in order to use any torch function. If `fork` or `forkserver` are selected, the code hangs for no apparent reason at the first torch call.

## To Reproduce

Minimal working example with a dummy model:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import datetime
import cProfile, pstats

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
      super(Net, self).__init__()
      self.conv1 = nn.Conv2d(1, 32, 3, 1)
      self.conv2 = nn.Conv2d(32, 64, 3, 1)

    def forward(self, x):
      x = self.conv1(x)
      x = F.relu(x)
      x = self.conv2(x)
      x = F.relu(x)
      output = F.log_softmax(x, dim=1)

      return output

def fun_profile(inputs):
    net = inputs[0]
    cProfile.runctx('fun(net)', globals(), locals(),
                    'profile_{:d}.out'.format(inputs[1]))

def fun(net):
    random_data = torch.rand(
        (1, 1, 28, 28), device=torch.device('cpu'))
    net(random_data)

if __name__ == '__main__':
    torch.multiprocessing.set_start_method('spawn')
    device = torch.device('cpu')
    
    net = Net().eval()
    net.to(device)

    number_workers = 10
    start_time = datetime.datetime.now()
    if number_workers == 0:
        # no multiprocessing
        fun_profile([net, number_workers])
    else:
        inputs = [[net, number_workers]]*(number_workers)
        with torch.multiprocessing.Pool(number_workers) as pool:
            pool.map(fun_profile, inputs)

    print('Total time: ', datetime.datetime.now() - start_time)

    s = pstats.Stats(
        'profile_{:d}.out'.format(number_workers))
    s.strip_dirs().sort_stats('cumtime').print_stats('(forward)')
```

## Environment

For the CPU only analysis:

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.5 (Maipo) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.0.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0

cc @VitalyFedyunin @ngimel

**Comment by VitalyFedyunin** [comment]
Spawning workers takes time, more in Windows, less in unix based OS. You need to significantly increase number of samples to be more accurate. 

Also you likely oversubscribing as each worker with use `torch.set_num_threads(int)` threads and multiplying it by number of workers can result of running more threads than your hardware can efficiently do.
