### ISSUE TITLE
[bug] support cudnn.benchmark with 3D convolution

### ISSUE THREAD

**Issue by KaiyuYue** [pytorch/pytorch#4653]
When turn on the `cudnn.benchmark` to run a 3D network, pytorch will report an error like this:

`RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCStorage.cu:66
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCStorage.c:182`

Pytorch version: `0.2.0.post3` and `0.3.0.post3` with anaconda 2.7

**Comment by ngimel** [comment]
Can you please provide a small reproducer?

**Comment by KaiyuYue** [comment]
Seriously sorry, it's my bad. A parameter is calculated wrong.
