### ISSUE TITLE
Make nested TreeSpec printing nicer

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#46538]
## 🚀 Feature

Right now, printing a nested TreeSpec happens all on one line. This can be difficult to read if the user receives a TreeSpec from a very nested python data structure.

## Motivation
```
>>> import torch
>>> x = [1, (1, 1, 1, (1, 1, 1, 1), [1, (1, 1), (1, 1, 1), [1, 1, (1, 1, 1)]])]
>>> _, spec = torch.utils._pytree.tree_flatten(x)
>>> TreeSpec(list, None, [*, TreeSpec(tuple, None, [*, *, *, TreeSpec(tuple, None, [*, *, *, *]), TreeSpec(list, None,
[*, TreeSpec(tuple, None, [*, *]), TreeSpec(tuple, None, [*, *, *]), TreeSpec(list, None, [*, *, TreeSpec(tuple, None, [*, *, *])])])])])
```

## Pitch

Make the printing look nicer. @ezyang [suggested](https://github.com/pytorch/pytorch/pull/46287#discussion_r506658091) to turn TreeSpec into a dataclass and have printing logic use pprint to pretty-print it.

**Comment by hxu296** [comment]
Hello! Is this a good first issue to tackle? I'm happy to work on the `__repr__` refactor. @zou3519 @ezyang

**Comment by ezyang** [comment]
Sure. Feel free to tag me on the PR.
