### ISSUE TITLE
Various tests wrongly decorated with largeCUDATensorTest

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#46536]
## 🐛 Bug

During analysis of #41469 I encountered the following:

> test_conv_large_cpu (__main__.TestNNDeviceTypeCPU) ... skipped 'No CUDA or Has CUDA but GPU RAM is not large enough'

So a CPU test is skipped due to the GPU not having enough memory.

## To Reproduce

1. `python ./test_nn.py TestNNDeviceTypeCPU.test_conv_large_cpu`

## Expected behavior

CPU test is executed

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0-rc2

## Additional context

This test (and others) is decorated with `@largeCUDATensorTest('12GB')` which skips the CPU test. There exists a decorator `largeTensorTest` which is probably the correct choice

I'd hence suggest that someone familiar with the tests checks all instances of `largeCUDATensorTest` if they are really restricted to CUDA or if those can be replaced by `largeTensorTest` 

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @mruberry @VitalyFedyunin

Edit: Open part of the issue: Don't run tests meant to be run on GPU on CPU. See https://github.com/pytorch/pytorch/pull/45332#issuecomment-721383275 from @zasdfgbnm for details

**Comment by xwang233** [comment]
Related https://github.com/pytorch/pytorch/pull/45332

**Comment by zasdfgbnm** [comment]
Most of these tests are designed to test CUDA 32bit indexing issue. CPU does not have these issue, and need not to be tested. If it is skipped, then it is fine.

**Comment by Flamefire** [comment]
While this could be true it still means some tests are wrongly run on CPU. E.g. the mentioned test_conv_large_cpu tests a Convolution on CPU(!) if the GPU(!) is big enough. So if that test was supposed to test CUDA 32bit indexing, then it should be decorated to only be run on GPU. Currently it may run (and fail) on CPU depending on the GPU present which is somewhat flaky

**Comment by mruberry** [comment]
We just killed `largeCUDATensorTest`, is this issue still relevant?

**Comment by zasdfgbnm** [comment]
@Flamefire Yes, you are right. These tests should be CUDA only.

**Comment by Flamefire** [comment]
@mruberry I'd suggest to keep this open until the comment in https://github.com/pytorch/pytorch/pull/45332#issuecomment-721383275 is resolved with a PR.

**Comment by mruberry** [comment]
OK. Would you update the issue to reflect the current problem and expected fix, then?
