### ISSUE TITLE
torch.matmul does not work for complex numbers

### ISSUE THREAD

**Issue by aneeshnema** [pytorch/pytorch#46546]
## 🐛 Bug

I was trying to implement torch.nn.Linear for complex numbers by reusing the source of torch.nn.Linear and making changes in it.  On giving my new layer input, it throws a RuntimeError.
On further investigations, it seems that it was complex matrix multiplication is not supported.

#### Short version:
```python
import torch
x = torch.rand(1, 5, dtype=torch.cfloat)
torch.matmul(x, x.T)
```

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-ff0d7b177171> in <module>()
      1 import torch
      2 x = torch.rand(1, 5, dtype=torch.cfloat)
----> 3 torch.matmul(x, x.T)

RuntimeError: _th_addmm_out not supported on CPUType for ComplexFloat
```

#### Long version (what I was trying to do):
```python
import torch
import torch.nn.functional as F
import torch.nn as nn
import math

class ComplexLinear(nn.Module):
    def __init__(self, in_features, out_features, bias = True):
        super(ComplexLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = nn.Parameter(torch.empty(out_features, in_features, dtype=torch.complex64))
        if bias:
            self.bias = nn.Parameter(torch.empty(out_features, dtype=torch.complex64))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self):
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in)
            nn.init.uniform_(self.bias, -bound, bound)

    def forward(self, input):
        return F.linear(input, self.weight, self.bias)

    def extra_repr(self):
        return 'in_features={}, out_features={}, bias={}'.format(
            self.in_features, self.out_features, self.bias is not None
        )

layer = ComplexLinear(5, 5)
x = torch.rand(1, 5, dtype=torch.cfloat)
layer(x)
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-37-95e898b019a1> in <module>()
     33 layer = ComplexLinear(5, 5)
     34 x = torch.rand(1, 5, dtype=torch.cfloat)
---> 35 layer(x)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in linear(input, weight, bias)
   1672     if input.dim() == 2 and bias is not None:
   1673         # fused op is marginally faster
-> 1674         ret = torch.addmm(bias, input, weight.t())
   1675     else:
   1676         output = input.matmul(weight.t())

RuntimeError: _th_addmm not supported on CPUType for ComplexFloat
```

## Expected behavior
matrix multiplication should work

## Environment
Google Colab

PyTorch version: 1.6.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect

## Additional context

I checked the docs. It says that torch.matmul is supported. https://pytorch.org/docs/stable/complex_numbers.html
There was a similar issue on PyTorch forum, it didn't receive any reply. https://discuss.pytorch.org/t/complex-matrix-multiplication/91865

cc @ezyang @anjali411 @dylanbespalko @mruberry @vishwakftw @jianyuh @nikitaved @pearu @heitorschueroff

**Comment by mariosasko** [comment]
Hi, 

it should work for complex numbers on cuda on master (for more details, see [this](https://github.com/pytorch/audio/issues/768)). If you can't wait for PyTorch 1.7, try the nightly build.

**Comment by aneeshnema** [comment]
@mariosasko thanks, torch.matmul() works on the nightly build for both cpu and cuda. 

As for creating a model that could work with complex numbers. My above implementation of ComplexLinear works, but for loss calculation while training, `torch.nn.functional.mse_loss` has not been implemented for ComplexFloat, for both cpu and cuda.

Interestingly, I defined my own mse_loss function
```python
def mse_loss(input, target):
  return (input - target).abs().square().mean()
```
and  used it for training

```python
model = ComplexLinear(5, 5).cuda()
optimizer = torch.optim.Adam(model.parameters())
x = torch.rand(10, 5, dtype=torch.complex64).cuda()
x_out = model(x)
loss = F.mse_loss(x_out, x)
optimizer.zero_grad()
loss.backward()
optimizer.step()
print(float(loss))
```
The model trains perfectly on cpu, but will not work on cuda.
```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-5e9362072079> in <module>()
      6 optimizer.zero_grad()
      7 loss.backward()
----> 8 optimizer.step()
      9 print(float(loss))

2 frames
/usr/local/lib/python3.6/dist-packages/torch/optim/functional.py in adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, amsgrad, beta1, beta2, lr, weight_decay, eps)
     85         # Decay the first and second moment running average coefficient
     86         exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
---> 87         exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
     88         if amsgrad:
     89             # Maintains the maximum of all 2nd moment running avg. till now

RuntimeError: "addcmul_cuda" not implemented for 'ComplexFloat'
```

This is due to `torch.addcmul()`  not being implemented for cuda and it is being used in adam optimizer.
#33152 does not have `torch.addcmul` in its list.


I am working in the field of wireless communication and the data that I deal with is generally in the form of complex numbers.
I understand support for complex numbers is limited, and I may have gone off-topic. Thank you for your help.

**Comment by anjali411** [comment]
@aneeshnema thanks for filing this issue. As @mariosasko mentioned, `matmul` has added for complex in 1.7 and is available on the nightly as well. 

Can you file an issue for `torch.adcmul` support for complex?

We are working on a plan to extend complex support to nn modules, and loss functions. I think some loss functions work for complex, but many others need to be fixed. Let me know if you'd be interested to contribute and add complex support for loss functions.

**Comment by aneeshnema** [comment]
@anjali411 I am interested in contributing. It would be great if you could help me get started.

**Comment by darsnack** [comment]
For some more clarification, is `torch.matmul` supported for batched mode on the GPU (CUDA + ROCm)?

Here's some context:
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.8.0.dev20201026+rocm3.8
```

The offending line of code and error message:
```
    inv_transforms = torch.matmul(Uc, torch.matmul(torch.diag_embed(S).type(torch.cfloat), Vc.transpose(-2, -1)))
RuntimeError: _th_bmm_out not supported on CUDAType for ComplexFloat
```

**Comment by anjali411** [comment]
> For some more clarification, is `torch.matmul` supported for batched mode on the GPU (CUDA + ROCm)?
> 
> Here's some context:
> 
> ```
> Python 3.6.9 (default, Jul 17 2020, 12:50:27)
> [GCC 8.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> print(torch.__version__)
> 1.8.0.dev20201026+rocm3.8
> ```
> 
> The offending line of code and error message:
> 
> ```
>     inv_transforms = torch.matmul(Uc, torch.matmul(torch.diag_embed(S).type(torch.cfloat), Vc.transpose(-2, -1)))
> RuntimeError: _th_bmm_out not supported on CUDAType for ComplexFloat
> ```

batched matrix multiplication for complex tensors will be supported on CUDA once #42553 is merged.
