### ISSUE TITLE
_group_count global variable corrupted on failed distributed process group initialisation

### ISSUE THREAD

**Issue by jlamypoirier** [pytorch/pytorch#46561]
## 🐛 Bug

On process group initialisation failure the global variable `torch.distributed.distributed_c10d._group_count` can be incremented by one even though no process group is created. This is because the counter is incremented at the beginning of `_new_process_group_helper` (https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L491) while the other global variables are set at the end.

This matters because depending on the crashing and recovery process the variable may end up taking a different value for different processes. And since the counter is used as a prefix for the `PrefixStore` the processes will be using different keys, leading to a socket timeout.

This issue cannot be "correctly" prevented since `_group_count` is private and `destroy_process_group` cannot be called here since the process group doesn't exist. It can be prevented by explicitly providing a group name to `init_process_group`, but the argument is marked as deprecated.

## To Reproduce

The following code :

```
import torch.distributed.distributed_c10d as c10d
import datetime

def print_global_vars():
    print("===========")
    print("_pg_map", c10d._pg_map)
    print("_pg_names", c10d._pg_names)
    print("_pg_group_ranks", c10d._pg_group_ranks)
    print("_default_pg", c10d._default_pg)
    print("_default_pg_init_method", c10d._default_pg_init_method)
    print("_group_count", c10d._group_count)

print_global_vars()
try:
    c10d.init_process_group("gloo", timeout=datetime.timedelta(milliseconds=1), rank=0, world_size=2, init_method=f"tcp://127.0.0.1:8000")
except RuntimeError:
    pass

print_global_vars()
```

This shows the following output:

```
===========
_pg_map {}
_pg_names {}
_pg_group_ranks {}
_default_pg None
_default_pg_init_method None
_group_count 0
===========
_pg_map {}
_pg_names {}
_pg_group_ranks {}
_default_pg None
_default_pg_init_method None
_group_count 1
```

## Expected behavior

It should be possible to recover from a failed call to `init_process_group` with public methods such as `is_initialized` and `destroy_process_group`. In the current implementation this means the call should leave the global variables in a consistent state, i.e. either none or all of them should be modified. In the above example, `_group_count` should remain at zero. 

## Environment

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M1200
Nvidia driver version: 450.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==0.8.5
[pip3] torch==1.6.0
[pip3] torchelastic==0.2.0
[pip3] torchvision==0.7.0
[conda] Could not collect
```

## Additional context

This issue happens in an elastic training training context where the main process group is frequently reinitialised, and there is a rare crash where the initialisation fails due to a broken pairwise connection. I am unsure if this is due to a networking error or a bug in the code, but the above issue makes it difficult to recover from the crash. This is in part because some of the processes crash in `ProcessGroupGloo.__init__`,  leading to inconsistent state, while others crash in the `barrier()` call at the end of `init_process_group`. The recovery process is roughly as follow:
```
while True:
    try:
        torch.distributed.init_process_group(...)
        break
    except Exception:
        if torch.distributed.is_initialized():
            torch.distributed.destroy_process_group()
```
But `_group_count` can be different across processes, so the recovery won't work.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
Hey @jlamypoirier 

Thanks for reporting this. And thanks for the detailed analysis and submitting a fix!

**Comment by kiukchung** [comment]
@jlamypoirier you mentioned that you run into this issue more frequently with "elastic" training. May I ask how you are running elastic training? Do you implement your own train loop or use a library like torchelastic (https://pytorch.org/elastic)?

**Comment by jlamypoirier** [comment]
@kiukchung I am running a custom elastic training. The reason is that I am running in a highly variable cluster where nodes can be added or removed very often, and I need to minimise the downtime when it happens. `torchelastic` has too much downtime for my use case because it resets the workers for every change in the cluster.

**Comment by lw** [comment]
I need to revert this PR because it broke the functional tests of [PyTorch-BigGraph](https://github.com/facebookresearch/PyTorch-BigGraph). It causes a Gloo internal assert to fail when calling `torch.distributed.new_group`. This is the full log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "torchbiggraph/distributed.py", line 121, in
 _server_init
    init_method=init_method, world_size=world_size, rank=server_rank, groups=groups
  File "torchbiggraph/distributed.py", line 97, in
 init_process_group
    group_objs.append(td.new_group(group, timeout=timeout))
  File "torch/distributed/distributed_c10d.py", line 2225, in
 new_group
    timeout=timeout)
  File "torch/distributed/distributed_c10d.py", line 533, in
 _new_process_group_helper
    timeout=timeout)
RuntimeError: [enforce fail at gloo/transport/tcp/address.cc:30] sizeof(impl_) == bytes.size(). 136 vs 45
Stack trace:
Exception type: gloo::EnforceNotMet
```
