### ISSUE TITLE
conda install pytorch error?

### ISSUE THREAD

**Issue by cuixing158** [pytorch/pytorch#46587]
### Please note that this issue tracker is not a help form and this issue will be closed.
envs: win10
cuda:10.2
cudnn: 8.0

when i  use `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch` install pytorch, it get error? how to solve it ?
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 598, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "D:\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "D:\anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "D:\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "D:\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "D:\anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "D:\anaconda3\lib\site-packages\conda\core\solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\anaconda3\lib\site-packages\conda\core\solve.py", line 1021, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "D:\anaconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\anaconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "D:\anaconda3\lib\concurrent\futures\_base.py", line 425, in result
        return self.__get_result()
      File "D:\anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "D:\anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 263, in _load
        mod_etag_headers.get('_mod'))
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 311, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "D:\anaconda3\lib\site-packages\conda\core\subdir_data.py", line 349, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "D:\anaconda3\lib\json\__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "D:\anaconda3\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "D:\anaconda3\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 152635 column 15 (char 5046092)

`$ D:\anaconda3\Scripts\conda-script.py install pytorch torchvision cudatoolkit=10.2 -c pytorch`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\anaconda3\python.exe
               CONDA_ROOT=D:\anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
           CURL_CA_BUNDLE=<not set>
     GENICAM_GENTL32_PATH=C:\Program Files\Basler\pylon 5\Runtime\Win32\
     GENICAM_GENTL64_PATH=C:\Program Files\Basler\pylon 5\Runtime\x64\
                 HOMEPATH=\Users\cuixingxing
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\intel64_win_mic
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=D:\anaconda3;D:\anaconda3\Library\mingw-w64\bin;D:\anaconda3\Library\u
                          sr\bin;D:\anaconda3\Library\bin;D:\anaconda3\Scripts;D:\anaconda3\bin;
                          D:\anaconda3;D:\anaconda3\Library\mingw-w64\bin;D:\anaconda3\Library\u
                          sr\bin;D:\anaconda3\Library\bin;D:\anaconda3\Scripts;D:\anaconda3\bin;
                          D:\anaconda3\condabin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program
                          Files\Basler\pylon 5\Runtime\Win32;C:\Program Files\Basler\pylon 5\Run
                          time\x64;D:\software\ffmpeg-4.0.2-win64-static\bin;C:\Windows\system32
                          ;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerS
                          hell\v1.0;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program
                          Files (x86)\UnrarDLL\x64;D:\software\ffmpegwin64-static\bin;D:\opencv_
                          4_1_1\build\x64\vc14\bin;C:\Program Files (x86)\IntelSWTools\openvino_
                          2019.2.275\opencv\bin;D:\opencv3_4_2\opencv\my_build\bin\Debug;D:\open
                          cv3_4_2\opencv\my_build\bin\Release;C:\Users\Administrator\Anaconda3;C
                          :\Users\Administrator\Anaconda3\Scripts;D:\anaconda3\Scripts;D:\Progra
                          m Files\Git\cmd;D:\anaconda3;C:\Program
                          Files\MATLAB\R2020a\runtime\win64;C:\Program
                          Files\MATLAB\R2020a\bin;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\IntelSWTools\openvino_
                          2019.2.275\inference_engine\bin\intel64\Release;C:\Program Files (x86)
                          \IntelSWTools\openvino_2019.2.275\inference_engine\bin\intel64\Debug;C
                          :\Program Files (x86)\Microsoft Visual Studio
                          14.0\VC\bin;D:\python_work\libtorch-win-shared-with-
                          deps-1.2.0\libtorch\lib;C:\Program Files\TortoiseSVN\bin;C:\Program Fi
                          les\nodejs;E:\software\cmake-3.18.2-win64-x64\bin;D:\opencv_4_4_0\open
                          cv\my_build\install\x64\vc14\bin;D:\opencv_4_3_0\opencv\my_build\insta
                          ll\x64\vc14\bin;E:\software\TensorRT-6.0.1.5_cuda10.1\lib;E:\software\
                          OpenBLAS-0.3.10-x64\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA Corporation\Nsight
                          Compute 2019.5.0;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:
                          \Users\cuixingxing\AppData\Local\Microsoft\WindowsApps;C:\Users\cuixin
                          gxing\AppData\Local\BypassRuntm;C:\Users\cuixingxing\AppData\Roaming\n
                          pm;C:\Program Files\Bandizip
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\anaconda3
            shell level : 1
       user config file : C:\Users\cuixingxing\.condarc
 populated config files : C:\Users\cuixingxing\.condarc
          conda version : 4.8.4
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       virtual packages : __cuda=11.1
       base environment : D:\anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
          package cache : D:\anaconda3\pkgs
                          C:\Users\cuixingxing\.conda\pkgs
                          C:\Users\cuixingxing\AppData\Local\conda\conda\pkgs
       envs directories : D:\anaconda3\envs
                          C:\Users\cuixingxing\.conda\envs
                          C:\Users\cuixingxing\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.18.4 CPython/3.7.1 Windows/10 Windows/10.0.14393
          administrator : True
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask general questions about PyTorch

Although, very likely you just running into a network installation problem
