### ISSUE TITLE
Torch Script export issue

### ISSUE THREAD

**Issue by TianzhongSong** [pytorch/pytorch#46580]
## 🐛 Bug

Encountering `RuntimeError` with traced model when moving the model to another gpu.

## To Reproduce

1. Running follow codes on a multi-gpu machine

```
import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.lstm = nn.LSTM(256, 256, num_layers=2)

    def forward(self, x):
        _, (last_h_t, _) = self.lstm(x)
        return last_h_t


model = Model()
model.to("cuda:0")

example_in = torch.randn(16, 4, 256).cuda()

jit_model = torch.jit.trace(model, example_in)

out = jit_model(example_in)

print("ok")

jit_model.to("cuda:1")
example_in = example_in.to("cuda:1")
out = jit_model(example_in)

```

## Expected behavior

Error log:

`RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:1 and hidden tensor at cuda:0`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2/7.6.5
 - GPU models and configuration: 1080Ti
 - Any other relevant information:

## Additional context

cc @gmagogsfm

**Comment by TianzhongSong** [comment]
Same issue with follow codes:

```
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.lstm = nn.LSTM(256, 256, num_layers=2)

    def forward(self, x):
        init_ht = torch.zeros(2, x.size(1), 256).to(x.device)
        init_ct = torch.zeros(2, x.size(1), 256).to(x.device)
        _, (last_h_t, _) = self.lstm(x, (init_ht, init_ct))
        return last_h_t


model = Model()
model.to("cuda:0")

example_in = torch.randn(16, 4, 256).cuda()

jit_model = torch.jit.trace(model, example_in)
torch.jit.save(jit_model, "test.pt")

jit_model.to("cuda:1")
example_in = example_in.to("cuda:1")
out = jit_model(example_in)

```

Then I found follow codes in the saved model(test.pt):

```
class Model(Module):
  __parameters__ = []
  __buffers__ = []
  training : bool
  lstm : __torch__.torch.nn.modules.rnn.LSTM
  def forward(self: __torch__.Model,
    x: Tensor) -> Tensor:
    _0 = self.lstm
    _1 = ops.prim.NumToTensor(torch.size(x, 1))
    _2 = torch.zeros([2, int(_1), 256], dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
    hx = torch.to(_2, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
    _3 = ops.prim.NumToTensor(torch.size(x, 1))
    _4 = torch.zeros([2, int(_3), 256], dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
    hx0 = torch.to(_4, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
    return (_0).forward(x, hx, hx0, )
```

Device has been fixed to `cuda:0`

**Comment by wconstab** [comment]
@TianzhongSong This issue looks similar to one that was fixed after 1.6.0 release.  Could you confirm if you see the problem on the latest nightly build?  

Also, there may be a workaround you can try, tracing the model with an input tensor on d0 and tracing it again with an input tensor on d1.  This is due to freezing the device information on input tensors when tracing.

**Comment by TianzhongSong** [comment]
@wconstab Thank you.

Same issue with the latest nightly build. 

It may be not flexible when tracing the model with an input tensor which has specified device id, if I running the saved model in a cpp project with unconfirmed gpu id.

**Comment by eellison** [comment]
Could you try replacing `torch.zeros(2, x.size(1), 256).to(x.device)` with `torch.zeros_like(...)` ?

**Comment by TianzhongSong** [comment]
Same issue with `torch.zeros_like`

```
import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.lstm = nn.LSTM(256, 256, num_layers=2)

    def forward(self, x):
        # init_ht = torch.zeros(2, x.size(1), 256).to(x.device)
        # init_ct = torch.zeros(2, x.size(1), 256).to(x.device)
        init_ht = torch.zeros_like(x)[:2, :, :]
        init_ct = torch.zeros_like(x)[:2, :, :]
        _, (last_h_t, _) = self.lstm(x, (init_ht, init_ct))
        return last_h_t


model = Model()
model.to("cuda:0")

example_in = torch.randn(16, 4, 256).cuda()

jit_model = torch.jit.trace(model, example_in)
torch.jit.save(jit_model, "test.pt")

jit_model.to("cuda:1")
example_in = example_in.to("cuda:1")
out = jit_model(example_in)
```

Saved model:

```
class Model(Module):
  __parameters__ = []
  __buffers__ = []
  training : bool
  lstm : __torch__.torch.nn.modules.rnn.LSTM
  def forward(self: __torch__.Model,
    x: Tensor) -> Tensor:
    _0 = self.lstm
    _1 = torch.zeros_like(x, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, memory_format=None)
    _2 = torch.slice(torch.slice(_1, 0, 0, 2, 1), 1, 0, 9223372036854775807, 1)
    hx = torch.slice(_2, 2, 0, 9223372036854775807, 1)
    _3 = torch.zeros_like(x, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False, memory_format=None)
    _4 = torch.slice(torch.slice(_3, 0, 0, 2, 1), 1, 0, 9223372036854775807, 1)
    hx0 = torch.slice(_4, 2, 0, 9223372036854775807, 1)
    return (_0).forward(x, hx, hx0, )
```

device is still fixed to 'cuda:0'

**Comment by eellison** [comment]
Okay, i've filed an issue here for the specific issue that is preventing this trace from working: https://github.com/pytorch/pytorch/issues/47010 In general, there are a number of rreasons why traces wont work across dtypes/devices, but I think if we make enough targeted fixes this could be improved over time. To consolidate things I'm going to close this issue, please reopen as you see fit.

**Comment by anth2o** [comment]
I still have a similar issue using `torch==1.10.2`, do you think it might be useful to reopen this issue ? Thanks
