### ISSUE TITLE
Debug build fails on Windows

### ISSUE THREAD

**Issue by InfiniteLife** [pytorch/pytorch#46582]
## 🐛 Bug

Debug build fails on Windows platform.

## Expected behavior

Build pass

## Environment

 - PyTorch sources from master around a week ago
 - Windows 10
 - CUDA 10.1
 - v142 ( Visual Studio 2019)
 - Python 3.6.10:

## Additional context
Console last words:

```
     Creating library D:/dev/cpp_projects/pytorch/build/lib/Debug/wrapdim_test.lib and object D:/dev/cpp_projects/pytorch/build/lib/Debug/wrapdim_test.exp
  wrapdim_test.vcxproj -> D:\dev\cpp_projects\pytorch\build\bin\Debug\wrapdim_test.exe
  Building Custom Rule D:/dev/cpp_projects/pytorch/caffe2/CMakeLists.txt
cl : command line warning D9025: overriding '/W1' with '/w' [D:\dev\cpp_projects\pytorch\build\caffe2\xla_tensor_test.vcxproj]
  xla_tensor_test.cpp
     Creating library D:/dev/cpp_projects/pytorch/build/lib/Debug/xla_tensor_test.lib and object D:/dev/cpp_projects/pytorch/build/lib/Debug/xla_tensor_test.exp
  xla_tensor_test.vcxproj -> D:\dev\cpp_projects\pytorch\build\bin\Debug\xla_tensor_test.exe
Traceback (most recent call last):
  File "setup.py", line 727, in <module>
    build_deps()
  File "setup.py", line 319, in build_deps
    cmake=cmake)
  File "D:\dev\cpp_projects\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "D:\dev\cpp_projects\pytorch\tools\setup_helpers\cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "D:\dev\cpp_projects\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\Ilya\anaconda3\lib\subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Debug', '--', '/p:CL_MPCount=8']' returned non-zero exit status 1.
```
Release build is passing without errors.

I'll attach cmake cache may be there is some relevant info. 
I need this lib to only work for C++ project(no need for Python or test), may be I can turn off some build options to pass without errors?

[CMakeCache.txt](https://github.com/pytorch/pytorch/files/5407916/CMakeCache.txt)

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by ezyang** [comment]
fwiw the log you posted isn't enough, the error is probably further up

**Comment by InfiniteLife** [comment]
You right! Seems like I just need to get python debug libs

`LINK : fatal error LNK1104: cannot open file 'python36_d.lib' [D:\dev\cpp_projects\pytorch\build\caffe2\torch\torch_python.vcxproj]`

**Comment by peterjc123** [comment]
Actually, the debug support for PyTorch is missing. But we do have the debug version of LibTorch.

**Comment by InfiniteLife** [comment]
> Actually, the debug support for PyTorch is missing. But we do have the debug version of LibTorch.

Yeah, but it wont work with CUDA... I've opened issue about it here https://github.com/pytorch/pytorch/issues/46161

**Comment by vladimir-aubrecht** [comment]
@InfiniteLife I believe this issue is solved considering this issue is about debug libtorch and another issue was opened to handle problem with CUDA. Are you ok with closing this ticket or am I missing something?

**Comment by vladimir-aubrecht** [comment]
Closing this ticket as it seems original issue is solved and ticket is stale. Feel free to open new issue if needed.
