### ISSUE TITLE
caffe2_detectron_ops_gpu.dll makes import torch occur OSerror，[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by RiverShi** [pytorch/pytorch#46592]
## To Reproduce

1. after installing pytorch from https://pytorch.org/ using pip, I try to import torch, but I get an OSerror [WinError 193] %1 is not a valid Win32 application, Error loading "e:\pythonenv\base38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

    it shows something wrong with caffe2_detectron_ops_gpu.dll

2. I found the position and this file , I copied and deleted it, then I can import torch with no error again.
 
3. But when I import torchversion, other errors occurs
    sorry, I can't repeat the error.
    just now it works well, error disappears like miracle.
    will it cause somthing wrong or loss of function？

## Expected behavior
`In [1]: import torch
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-eb42ca6e4af3> in <module>
----> 1 import torch

e:\pythonenv\base38\lib\site-packages\torch\__init__.py in <module>
    114                 err = ctypes.WinError(last_error)
    115                 err.strerror += ' Error loading "{}" or one of its dependencies.'.format(dll)
--> 116                 raise err
    117             elif res is not None:
    118                 is_loaded = True

OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "e:\pythonenv\base38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

In [2]: import torchvision
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-6dd351122000> in <module>
----> 1 import torchvision

e:\pythonenv\base38\lib\site-packages\torchvision\__init__.py in <module>
      3 from .extension import _HAS_OPS
      4
----> 5 from torchvision import models
      6 from torchvision import datasets
      7 from torchvision import ops

e:\pythonenv\base38\lib\site-packages\torchvision\models\__init__.py in <module>
----> 1 from .alexnet import *
      2 from .resnet import *
      3 from .vgg import *
      4 from .squeezenet import *
      5 from .inception import *

e:\pythonenv\base38\lib\site-packages\torchvision\models\alexnet.py in <module>
----> 1 import torch
      2 import torch.nn as nn
      3 from .utils import load_state_dict_from_url
      4
      5

e:\pythonenv\base38\lib\site-packages\torch\__init__.py in <module>
    114                 err = ctypes.WinError(last_error)
    115                 err.strerror += ' Error loading "{}" or one of its dependencies.'.format(dll)
--> 116                 raise err
    117             elif res is not None:
    118                 is_loaded = True

OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "e:\pythonenv\base38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: I don't know
 - Any other relevant information:

## Additional context

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Not a problem if you don't use caffe2 or detectron.

BTW, the error "[WinError 193] %1 is not a valid Win32 application, Error loading "e:\pythonenv\base38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies." means that you have a conflicting DLL loaded while loading `caffe2_detectron_ops_gpu.dll`. As for as I know, it relies on `VCOMP140.DLL` and `LIBIOMP5MD.dll`. So, most likely these two DLLs are the real problem instead of `caffe2_detectron_ops_gpu.dll` itself.

**Comment by RiverShi** [comment]
I find VCOMP140.dll in pythonenv\base38\Lib\site-packages\sklearn\.libs and  C:\windows\system32
LIBIOMP5MD.dll in  pythonenv\base38\Lib\site-packages\torch\lib

**Comment by RiverShi** [comment]
I find VCOMP140.dll in pythonenv\base38\Lib\site-packages\sklearn.libs and C:\windows\system32
LIBIOMP5MD.dll in pythonenv\base38\Lib\site-packages\torch\lib

**Comment by peterjc123** [comment]
@RiverShi You can use Debugging Tools for Windows to get a full log. https://github.com/peterjc123/pytorch_dll_load_smoketests#how-to-contribute-or-report-issues
