### ISSUE TITLE
GPU memory does not clear with torch.cuda.empty_cache()

### ISSUE THREAD

**Issue by Buckeyes2019** [pytorch/pytorch#46602]
## 🐛 Bug

**When I train a model the tensors get kept in GPU memory. The command torch.cuda.empty_cache() "releases all unused cached memory from PyTorch so that those can be used by other GPU applications" which is great, but how do you clear the used cache from the GPU?  Is the only way to delete the tensors being held in GPU memory one by one?  And if so, how do you do that?  Thanks!**

Note:  After re-booting my computer the model trains normally the first time I run it (batch size =2). If I try to train it again using the same code I get the CUDA out of memory error. Restarting the kernel does not solve the problem. Reducing the batch size does not solve the problem. Only re-booting the computer solves the problem (and by "solves" I mean lets me run training 1 time and then gives the same out of memory error as before).  

I used this code snippet to confirm tensors were be held in GPU memory even after executing torch.cuda.empty_cache() :  

def pretty_size(size):
	"""Pretty prints a torch.Size object"""
	assert(isinstance(size, torch.Size))
	return " × ".join(map(str, size))

def dump_tensors(gpu_only=True):
	"""Prints a list of the Tensors being tracked by the garbage collector."""
	import gc
	total_size = 0
	for obj in gc.get_objects():
		try:
			if torch.is_tensor(obj):
				if not gpu_only or obj.is_cuda:
					print("%s:%s%s %s" % (type(obj).__name__, 
										  " GPU" if obj.is_cuda else "",
										  " pinned" if obj.is_pinned else "",
										  pretty_size(obj.size())))
					total_size += obj.numel()
			elif hasattr(obj, "data") and torch.is_tensor(obj.data):
				if not gpu_only or obj.is_cuda:
					print("%s → %s:%s%s%s%s %s" % (type(obj).__name__, 
												   type(obj.data).__name__, 
												   " GPU" if obj.is_cuda else "",
												   " pinned" if obj.data.is_pinned else "",
												   " grad" if obj.requires_grad else "", 
												   " volatile" if obj.volatile else "",
												   pretty_size(obj.data.size())))
					total_size += obj.data.numel()
		except Exception as e:
			pass        
	print("Total size:", total_size)

## Expected behavior

Would like a way to clear all memory from GPU.

## Environment

JupyterLab 2.2.6

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ngimel

**Comment by zou3519** [comment]
`empty_cache` releases unoccupied cached memory. If a Tensor is still being held by the script or by the framework (for backwards computation during training), then it will not get freed.

Do you have a self-contained script which we could use to reproduce your OOM?

**Comment by Buckeyes2019** [comment]
I am following this tutorial script exactly.  

https://ohmeow.com/posts/2020/05/23/text-generation-with-blurr.html

Again, it works well through the learning rate finder cell (learn.lr_find(suggestions=True)), but the following cell (learn.fit_one_cycle(1, lr_max=3e-5)) generates the OOM error.  If I reboot and go straight to the (learn.fit_one_cycle(1, lr_max=3e-5)) cell I can run it successfully once but if I try to do so again it throws the OOM error.

**Comment by mdorkhah** [comment]
> I am following this tutorial script exactly.
> 
> https://ohmeow.com/posts/2020/05/23/text-generation-with-blurr.html
> 
> Again, it works well through the learning rate finder cell (learn.lr_find(suggestions=True)), but the following cell (learn.fit_one_cycle(1, lr_max=3e-5)) generates the OOM error. If I reboot and go straight to the (learn.fit_one_cycle(1, lr_max=3e-5)) cell I can run it successfully once but if I try to do so again it throws the OOM error. When I run the code snippet in my original post above it shows that the GPU is holding onto tensors and that is what is taking up most of the GPU memory.

Hi, could you find a way to solve this problem? I have the same!
