### ISSUE TITLE
the part that explains TorchScript

### ISSUE THREAD

**Issue by kwhkim** [pytorch/pytorch#46611]
## 📚 Documentation

from the [TorchScript Tutorial](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html),

I found that the output from 

`print(traced_cell.code)` and 
`print(traced_cell.code)` are essentially the same, which are not meant to be from the text.

One output is from `torch.jit.trace` and the other is from `torch.jit.script`.

```
def forward(self,
    input: Tensor,
    h: Tensor) -> Tuple[Tensor, Tensor]:
  _0 = (self.dg).forward((self.linear).forward(input, ), )
  _1 = torch.tanh(torch.add(_0, h, alpha=1))
  return (_1, _1)
```
and

```
def forward(self,
    x: Tensor,
    h: Tensor) -> Tuple[Tensor, Tensor]:
  _0 = (self.dg).forward((self.linear).forward(x, ), )
  new_h = torch.tanh(torch.add(_0, h, alpha=1))
  return (new_h, new_h)
```

I do understand that `script` is for dynamic operations like `if` but the output confuses me.

The output matches what i got from my computer so

there seems to be no way to discern `script` and `trace` just by printing???

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Both tracing and scripting generate TorchScript IR, which can then be reverse-converted back into Python code, which is what you see. So as far as I know they don't have fundamental differences in content. The difference is just how the IR is generated from user code. Hope this helps.
