### ISSUE TITLE
Wrong Examples in torchvision.ops.deform_conv2d

### ISSUE THREAD

**Issue by tyui592** [pytorch/pytorch#46628]
## 📚 Documentation

In documentation of [torchvision.ops.deform_conv2d](https://pytorch.org/docs/stable/torchvision/ops.html?highlight=deform#torchvision.ops.deform_conv2d),
```python
>>> input = torch.rand(1, 3, 10, 10)
>>> kh, kw = 3, 3
>>> weight = torch.rand(5, 3, kh, kw)
>>> # offset should have the same spatial size as the output
>>> # of the convolution. In this case, for an input of 10, stride of 1
>>> # and kernel size of 3, without padding, the output size is 8
>>> offset = torch.rand(5, 2 * kh * kw, 8, 8)
>>> out = deform_conv2d(input, offset, weight)
>>> print(out.shape)
>>> # returns
>>>  torch.Size([1, 5, 8, 8])
```
When executing the above script, the following error occurs,
```
Traceback (most recent call last):
  File "bar.py", line 10, in <module>
    out = deform_conv2d(input, offset, weight)
  File "/home/foo/anaconda3/envs/pytorch_1.6.0/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 67, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: invalid batch size of offset
```
the `offset` to be `torch.rand(1, 2 * kh * kw, 8, 8)`

cc @fmassa @vfdev-5

**Comment by zou3519** [comment]
This should go on the torchvision issue tracker (https://github.com/pytorch/vision), please consider cross-posting there.

**Comment by vfdev-5** [comment]
@tyui592 thanks for reporting, this is already fixed on master : 
https://github.com/pytorch/vision/blob/34708e4c3b549933695446d8770fd0e064eae911/torchvision/ops/deform_conv.py#L42-L52
