### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 32, 3, 3]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by WenLi-o00o** [pytorch/pytorch#46638]
Hi guys, 
I'm a new pytorch user, when I try to run a code, an error occurs, I tried to search existing similar issues but found they are not helpful, could you please help me with this? Many thanks.

the code is described as follows: 
class Discriminator(nn.Module):

    def __init__(self, in_channels=1):
        super(Discriminator, self).__init__()

        def discrimintor_block(in_features, out_features, normalize=True):
            """Discriminator block"""
            layers = [nn.Conv2d(in_features, out_features, 3, stride=2, padding=1)]
            if normalize:
                layers.append(nn.BatchNorm2d(out_features, 0.8))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers

        self.model = nn.Sequential(
            *discrimintor_block(in_channels, 32, normalize=False),
            *discrimintor_block(32, 64),
            *discrimintor_block(64, 128),
            *discrimintor_block(128, 256),
            #nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(256, 1, kernel_size=3)
        )

    def forward(self, img):
        return self.model(img)   
#########################################################

                optimizer_G.zero_grad()
                
                x_fake,x1_re,x2_re = self.generator(x_fu)
                
                # Identity loss
                loss_re3 = criterion_identity(x_fake, x3)
                loss_re1 = criterion_identity(x1_re, x1)
                loss_re2 = criterion_identity(x2_re, x2)
                
  
                # gan loss 
                loss_GAN = criterion_GAN(self.discrimator(x_fake), valid) 
                            
                # total loss
                loss_G = loss_GAN + 100*loss_re3 + 20*loss_re1 + 20*loss_re2
                
            
                loss_G.backward(retain_graph=True)
                optimizer_G.step()
            
                # ----------------------
                #  Train Discriminators
                # ----------------------
                optimizer_D.zero_grad()

                
                # Real loss
                loss_real = criterion_GAN(self.discrimator(x3), valid)
                loss_fake = criterion_GAN(self.discrimator(x_fake), fake)
                # Total loss
                loss_D = (loss_real + loss_fake) / 2

                loss_D.backward(retain_graph=True)
                optimizer_D.step()

**Comment by zou3519** [comment]
Please ask questions on our [forums](discuss.pytorch.org)

I don't see any in-place operations in your code, but a few of the functions definitions aren't included (criterion_GAN, criterion_identity). 

The error message suggests to use anomaly mode to figure out which operation is causing the error:
https://pytorch.org/docs/stable/autograd.html#torch.autograd.detect_anomaly

Closing this issue because it is a question; please feel free to reopen or submit a new one if you discover that there is a bug in PyTorch.

**Comment by linnabrown** [comment]
@zou3519  Hi, Thank you so much. I also meet the same problem in a GAN model. 

I also want to post this problem in your forum. SHould it be this link? https://discuss.pytorch.org

**Comment by ParnaChowdhury** [comment]
facing the same issue
