### ISSUE TITLE
No kernel image is available for execution on the device

### ISSUE THREAD

**Issue by GangyiTian** [pytorch/pytorch#46647]
## ❓ Questions and Help

Dear developer：

Hello, I ran into the problem as indicated in the title (**actually, I googled this question**).  The problem is that the Compute Capability of my graphics card cannot meet the requirements, and I installed the 1.6 pytorch version. Starting from version 1.3, the Compute Capability required by pytorch requires at least 3.6(>3.5). However, my graphics card is **Tesla K80**, and the official website shows that its Compute Capability is 3.7. Therefore, in theory, the 1.6 version can be run normally. I also tested it through tensorflow and it showed that the Compute Capability of the graphics card was 3.5 (so sad). This means that the Compute Capability detected by pytorch or tensorflow may all be 3.5. 

I'm a little confused:
- It is a problem with my graphics card (is it a fake)? 
- What's the problem? 
- Is there any way to help me solve it?

cc @ezyang @seemethere @malfet @walterddr @ngimel

**Comment by GangyiTian** [comment]
- NVIDIA-SMI 418.165.02   Driver Version: 418.165.02   CUDA Version: 10.1
![image](https://user-images.githubusercontent.com/26830967/96693326-aef37380-13b9-11eb-91a0-bd8196ec9419.png)

**Comment by zou3519** [comment]
@seemethere @malfet what is the minimum compute capability we support on PyTorch 1.6?

@GangyiTian https://discuss.pytorch.org/t/gpu-compute-capability-support-for-each-pytorch-version/62434/3?u=richard suggests a method of checking the compute capability that a pytorch binary supports.

**Comment by GangyiTian** [comment]
> @seemethere @malfet what is the minimum compute capability we support on PyTorch 1.6?
> 
> @GangyiTian https://discuss.pytorch.org/t/gpu-compute-capability-support-for-each-pytorch-version/62434/3?u=richard suggests a method of checking the compute capability that a pytorch binary supports.

Okay, let me try it. Thank you for taking the time to reply！

**Comment by malfet** [comment]
@GangyiTian can you please run deviceQuery sample from NVIDIA toolkit and post its output here?
If your GPUs compute capability is sm_35, then we indeed do not ship binaries that support that capability but you should be able to rebuild PyTorch from source to enable that.

**Comment by GangyiTian** [comment]
> @GangyiTian can you please run deviceQuery sample from NVIDIA toolkit and post its output here?
> If your GPUs compute capability is sm_35, then we indeed do not ship binaries that support that capability but you should be able to rebuild PyTorch from source to enable that.

![截屏2020-10-22 01 57 58](https://user-images.githubusercontent.com/26830967/96759371-85af0380-140a-11eb-9bec-9d153e258a3f.png)
Hello, I tried to use deviceQuery and found that the **compute capability is indeed 3.5**. In addition, I will try to compile pytorch from source code, thank you for your reply, and I will close this issue. Have a nice day!
