### ISSUE TITLE
Bug in inplace operation after expansion

### ISSUE THREAD

**Issue by zihangdai** [pytorch/pytorch#4664]
```python
import torch

a = torch.ones(1,1) # same thing for rand(1,1) or zeros(1,1)
b = a.expand(4,5)
print(b)
b += 1
print(b) # expect all elements to be 2; however, all elements will be 1 + 4*5*1 = 21
```
Essentially, the inplace addition operation adds to the same memory space many times (4 x 5 in the case above).

**Comment by apaszke** [comment]
Yes, and that's the expected behavior. Don't do in-place on expanded tensors.

**Comment by fmassa** [comment]
Is this something that we want to guard on? numpy has the [flags property](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.flags.html), maybe we could also have a `WRITEABLE` flag that follows similar semantics as numpy's?

**Comment by apaszke** [comment]
Yeah that would be great, but that's a fairly large change

**Comment by qbx2** [comment]
How about adding the message for users not to in-place on expanded tensors on docs?
