### ISSUE TITLE
use share_memory_, Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by renjingc** [pytorch/pytorch#46651]
when I use share_memory_(), when append 65080, core dumped

```
import torch

if __name__ == '__main__':
    buffers = []
    for _ in range(65535):
        print (_)
        buffers.append(torch.empty(1, 1).share_memory_())
```

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff

**Comment by zou3519** [comment]
I can repro this (mine crashes at 65042). Marking high-pri for crash.

Maybe the OS just ran out of shared memory? Nevertheless a nice error message would be better than a crash here.

**Comment by ezyang** [comment]
You are almost certainly running out of shared memory on your system. You can try changing the limits using ulimit.

It still probably shouldn't crash, though I'm not sure if it will be easy to fix.

**Comment by renjingc** [comment]
I have use ulimit -n 655350. when I append 60000, I view shared memory，df -lh
![image](https://user-images.githubusercontent.com/9279431/96817608-41475600-1452-11eb-86d5-d94ef3f66c99.png)
