### ISSUE TITLE
nn.Embedding sparse=True not giving sparse gradient for master branch

### ISSUE THREAD

**Issue by graytowne** [pytorch/pytorch#4666]
I use the current master branch(see the code below) of PyTorch, and there seems a bug when I using sparse nn.Embedding:
when I set sparse=True for nn.Embedding, finally I still got dense gradient and here is the code:

```
>>> import torch
>>> from torch.autograd import Variable
>>> import torch.nn as nn

>>> emb = nn.Embedding(10,3, sparse=True)
>>> input = Variable(torch.LongTensor([[1],[2]]))
>>> loss = emb(input).mean()

>>> loss
Variable containing:
-0.3957
[torch.FloatTensor of size (1,)]

>>> loss.backward()

>>> emb.weight.grad
Variable containing:
 0.0000  0.0000  0.0000
 0.1667  0.1667  0.1667
 0.1667  0.1667  0.1667
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
[torch.FloatTensor of size (10,3)]

>>> emb.weight.grad.is_sparse
False
```

`torch.__version__ is '0.4.0a0+8eded5a'`

However, the gradient is sparse when I change my PyTorch to version '0.3.0.post4':
```
>>> emb.weight.grad
Variable containing:FloatTensor of size 10x3 with indices:

 1  2
[torch.LongTensor of size 1x2]
and values:

 0.1667  0.1667  0.1667
 0.1667  0.1667  0.1667
[torch.FloatTensor of size 2x3]
```

**Comment by elanmart** [comment]
Sparse argument is ignored in current master branch, the bug was introduced here
https://github.com/pytorch/pytorch/commit/20b5e82155ec052b2c168e3fb1aff0fd2dd3c8a4#diff-c66288b9ce36978f377a1a20d32ec53dR992

**Comment by elanmart** [comment]
Not sure how to fix it, https://github.com/pytorch/pytorch/blob/20b5e82155ec052b2c168e3fb1aff0fd2dd3c8a4/aten/src/ATen/native/Embedding.cpp#L73 raises 
```python
RuntimeError: Expected object of type Variable[torch.sparse.FloatTensor] but found type Variable[torch.LongTensor] for argument #0 'indices
```
I've tried to dig around, but I can't find out what goes wrong. Would be happy to learn, though.
cc @colesbury
