### ISSUE TITLE
torch.heaviside internal assert for cuda tensor and cpu scalar tensor

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#46681]
## 🐛 Bug

torch.heaviside gives an internal assert when passed a cuda tensor and a cpu scalar tensor.

## To Reproduce

```
>>> x = torch.randn(10, device='cuda')
>>> y = torch.tensor(1.)
>>> torch.heaviside(x, y)
RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/scratch/rzou/pt/workspace/aten/src/ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch.
```

## Expected behavior

It should not internal assert. If this is not supported, we should fail without internal assert.

## Environment
master

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
I think this is gpu_kernel -> gpu_kernel_with_scalars here:

https://github.com/pytorch/pytorch/blob/439930c81b5c711f30e739e900db7a0599659ead/aten/src/ATen/native/cuda/BinaryMiscOpsKernels.cu#L105

A test_binary_ufuncs.py test suite would be helpful in testing for this. I doubt heaviside is the only affected op.
