### ISSUE TITLE
Missing support in TorchScript: "in" operator to check if a string contains substring

### ISSUE THREAD

**Issue by cndn** [pytorch/pytorch#46682]
## 🐛 Bug

Calling `"a" in "abcd" ` in TS model throws an error

RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::__contains__.str_list(str[] l, str item) -> (bool):
  Expected a value of type 'List[str]' for argument 'l' but instead found type 'str'.
  
  aten::__contains__.str(Dict(str, t) dict, str key) -> (bool):
  Could not match type str to Dict[str, t] in argument 'dict': Cannot match a dict to str.
  
  aten::__contains__.int(Dict(int, t) dict, int key) -> (bool):
  Could not match type str to Dict[int, t] in argument 'dict': Cannot match a dict to str.
  
  aten::__contains__.bool(Dict(bool, t) dict, bool key) -> (bool):
  Could not match type str to Dict[bool, t] in argument 'dict': Cannot match a dict to str.
  
  aten::__contains__.float(Dict(float, t) dict, float key) -> (bool):
  Could not match type str to Dict[float, t] in argument 'dict': Cannot match a dict to str.
  
  aten::__contains__.Tensor(Dict(Tensor, t) dict, Tensor key) -> (bool):
  Could not match type str to Dict[Tensor, t] in argument 'dict': Cannot match a dict to str.
  
  aten::__contains__.int_list(int[] l, int item) -> (bool):
  Expected a value of type 'List[int]' for argument 'l' but instead found type 'str'.
  
  aten::__contains__.float_list(float[] l, float item) -> (bool):
  Expected a value of type 'List[float]' for argument 'l' but instead found type 'str'.

Looks like the string overload isn't bound yet

## To Reproduce

```
import torch
from torch import nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self):
        return "a" in "abcd"

m = MyModel()
scripted = torch.jit.script(m)
scripted()
```

## Expected behavior

The minimal repro example runs without error

## Environment

FB intern

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting. 

Could you try using a few known work-around to check substring? For example, following code works:

```
import torch


@torch.jit.script
def substr_check(x: str):
    return x.find("you") != -1


print(substr_check("yo yo check it out"))
print(substr_check("you you check it out"))
```

**Comment by eellison** [comment]
This can be bound in `builtin_functions.cpp` to desugar to what @gmagogsfm suggested
