### ISSUE TITLE
[jit] TestWarn fails when running tests in parallel

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#46684]
repro:
```
pip install pytest
pip install pytest-xdist
pytest -q -n auto test/test_jit.py
```
You'll see that `TestWarn` fails, I assume because it is testing something that does not correctly preserve when tests are run in multiple processes?

cc @gmagogsfm

**Comment by suo** [comment]
@gmagogsfm I think you implemented the warning functionality/tests, mind taking a look if there's a way we can rewrite them to work when run in parallel?

**Comment by gmagogsfm** [comment]
thanks, will take a look

**Comment by gmagogsfm** [comment]
Hi @suo,

It turns out that tests are not failing because of running in parallel. It is because pytest, by default, captures all warnings emitted in tests. I tried disabling this behavior with a pytest.ini change, with which all tests are passing.

```
[pytest]
addopts = -p no:warnings
```

**Comment by suo** [comment]
oh interesting. I'll give it a try!

**Comment by gmagogsfm** [comment]
Closing this out, I think we discussed this offline in chat and resolved it.
