### ISSUE TITLE
Memory increase in training time

### ISSUE THREAD

**Issue by XiongweiWu** [pytorch/pytorch#4668]
Hi, I find the memory cost will increase a bit after the first inference time when I train Imagenet, and is it an issue?

**Comment by pranavsubramani** [comment]
Could you post the code, so I can try to reproduce the result?

**Comment by XiongweiWu** [comment]
Problem solved, since the API has been changed from volatile to torch.with_no_grad

**Comment by soumith** [comment]
ah makes sense if you are using the master branch.
