### ISSUE TITLE
Tried to access nonexistent attribute or method 'new' of type 'Tensor'

### ISSUE THREAD

**Issue by ismymajia** [pytorch/pytorch#46695]
## ❓ Questions and Help

We know that the nn.module.register_buffer func works fine when using its new method, but there is an error in torch.jit. Is there any problem here?

When i convert to torch.jit.script by below code:
model = load_model_ensemble_and_task([args.input_model])[0][0]
model.eval()
model_dict = model.decoder.dictionary
generator = SequenceGenerator([model], model_dict, beam_size=args.beam_size)
scripted_generator = torch.jit.script(generator)
scripted_generator.save(args.output_model)

error occor:
Tried to access nonexistent attribute or method 'new' of type 'Tensor'

The corresponding error location is ：
https://github.com/pytorch/fairseq/blob/a48f235636557b8d3bc4922a6fa90f3a0fa57955/fairseq/modules/adaptive_input.py#L70

cc @gmagogsfm

**Comment by eellison** [comment]
Hi, `new` is a legacy op. Please use a different constructor. This is covered by https://github.com/pytorch/pytorch/issues/30780
