### ISSUE TITLE
Quantization article mentions PyTorch 1.3 but should be updated to 1.6

### ISSUE THREAD

**Issue by lcrew11** [pytorch/pytorch#46707]
## 📚 Documentation

In this article on quantization: https://pytorch.org/docs/stable/quantization.html there is a note mentioning the 'PyTorch 1.3 doesn’t provide quantized operator implementations on CUDA yet - this is direction of future work. ' 

But it should be clarified what quantization can be implemented on the GPU in 1.6. It's very unclear as to what operations can be run on the GPU in PyTorch 1.6.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by ZhiyuanChen** [comment]
I don't think it has been implemented now, maybe it's better to make it as for the current edition?

**Comment by supriyar** [comment]
Thanks for flagging this, we will update the docs. cc @z-a-f

**Comment by z-a-f** [comment]
This merged into the master. Hoping to get it into the 1.7, but if it doesn't propagate, it will be there in the next release. Thank you!
