### ISSUE TITLE
How to calculate  L2 weight regularization in pytorch ?

### ISSUE THREAD

**Issue by KelleyYin** [pytorch/pytorch#4671]
such as :
<a href="https://www.codecogs.com/eqnedit.php?latex=l=(z-v)^{2}-\pi&space;^{\tau&space;}\log&space;p&plus;c||\theta&space;||^{2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?l=(z-v)^{2}-\pi&space;^{\tau&space;}\log&space;p&plus;c||\theta&space;||^{2}" title="l=(z-v)^{2}-\pi ^{\tau }\log p+c||\theta ||^{2}" /></a>
<a href="https://www.codecogs.com/eqnedit.php?latex=c||\theta&space;||^{2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?c||\theta&space;||^{2}" title="c||\theta ||^{2}" /></a> is  L2 weight regularization .

**Comment by Kaixhin** [comment]
There's plenty of information and possible methods that you can find on the [official forums](https://discuss.pytorch.org/search?q=l2%20weight%20decay).
