### ISSUE TITLE
Torch import fail

### ISSUE THREAD

**Issue by sebastienwood** [pytorch/pytorch#46723]
## 🐛 Bug

When trying to import torch from a fresh install, it fails with the error message 
```
Traceback (most recent call last):
  File "run_torch.py", line 1, in <module>
    import torch
  File "/export/tmp/henwood/anaconda3/lib/python3.8/site-packages/torch/__init__.py", line 480, in <module>
    import torch.multiprocessing
  File "/export/tmp/henwood/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/__init__.py", line 18, in <module>
    from .reductions import init_reductions
  File "/export/tmp/henwood/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 7, in <module>
    from multiprocessing.util import register_after_fork
ModuleNotFoundError: No module named 'multiprocessing.util'; 'multiprocessing' is not a package
```

## To Reproduce

1. Install and import torch
2. Notice the error 

## Expected behavior

The import should success.

## Environment

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: CentOS Linux release 7.8.2003 (Core)
GCC version: (Homebrew GCC 5.5.0_7) 5.5.0
CMake version: version 3.18.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch

**Comment by SsnL** [comment]
I guess you have a local file named `multiprocessing.py` or a local folder named `multiprocessing`. Naming file/folders same as python core libs is strongly advised against.

**Comment by sebastienwood** [comment]
Indeed, good catch ! Many thanks :)
