### ISSUE TITLE
Tensor with read only memory mapped numpy array causes seg fault.

### ISSUE THREAD

**Issue by csimo005** [pytorch/pytorch#46741]
## 🐛 Bug

If you use a memory mapped numpy array and open it read only, pytorch won't respect that it's read only. If you accidentally write to it, it causes a seg fault. It does give a warning that you may overwrite your data unexpectedly, but not that you may end up segfaulting.
## To Reproduce

>>> import numpy as np
>>> import torch

>>> A = np.zeros((3,4))
>>> np.save('temp.npy', A)
>>> del A

>>> A = np.load('temp.npy', mmap_mode='r')
>>>  T = torch.from_numpy(A)
>>> T[0,0] = 1

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @jlin27 @mruberry @rgommers

**Comment by zhangguanheng66** [comment]
Compatibility issue with numpy.

**Comment by mruberry** [comment]
We would accept a PR improving the error message and the function's documentation to clarify this behavior.

**Comment by ezyang** [comment]
Error message => warning message

**Comment by mruberry** [comment]
Reopening. The linked PR had to be reverted, unfortunately.

**Comment by SmrutiSikha** [comment]
@mruberry sent pr for this issue. Please do check.

**Comment by SmrutiSikha** [comment]
@mruberry I have linked a pull request #51870 that got approval from one of the maintainers. So after you review the code, it can be merged and the issue can be closed.

**Comment by prithvijitguha** [comment]
Hey everyone! It looks like this issue is already fixed. But when I went through #51870 it said that the pr was blocked from merging. Is it still open? Can I contribute to this? I'm new to open source.

**Comment by mruberry** [comment]
Unfortunately it looks like #51870 was mostly complete but stalled. Yes we would still accept a PR addressing this following the comments made on #51870.

**Comment by prithvijitguha** [comment]
@mruberry Hey thank you for the message. I'm really sorry, I've seen a couple of guides for setting up the environment for development for pytorch. Could I get some help on this and what exactly I need to do to pass the tests for pr?

**Comment by mruberry** [comment]
> @mruberry Hey thank you for the message. I'm really sorry, I've seen a couple of guides for setting up the environment for development for pytorch. Could I get some help on this and what exactly I need to do to pass the tests for pr?

Start with the instructions for building PyTorch from scratch and the contributing guide.

**Comment by prithvijitguha** [comment]
Hey @nickleus27 I was working on it. But I couldn't still can't seem to build pytorch from source. Go ahead!

**Comment by nickleus27** [comment]
@mruberry Thank you for your reply.  I see from the previous PR that the files torch/_torch_docs.py , torch/csrc/utils/tensor_numpy.cpp , and pytorch/test/test_torch.py had changes made to them. I see the _torch_docs needs a warning about writing to a read only tensor from_numpy().  Could you give me any suggestions of how you would like the warning in tensor_numpy.cpp improved?  Thank you for your time.

**Comment by mruberry** [comment]
I think the other PR has the documentation correct but needed to update some tests to account for it.
