### ISSUE TITLE
"Unconvertible NCCL type" with DataParallel and complex tensor 

### ISSUE THREAD

**Issue by nrxszvo** [pytorch/pytorch#46745]
## 🐛 Bug

`RuntimeError: Unconvertible NCCL type` when trying to execute a module containing complex tensors using DataParallel and 2+ GPUs

## To Reproduce

```
import torch
import numpy as np

class Cplx(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('cplx', torch.from_numpy(1j*np.arange(10)))

    def forward(self, x):
        return x*self.cplx

cplx = torch.nn.DataParallel(Cplx().cuda())
x = torch.rand(2,10).cuda()
cplx(x)
```

Output:
```
Traceback (most recent call last):
  File "dbg_cplx.py", line 14, in <module>
    cplx(x)
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 154, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 103, in replicate
    buffer_copies_not_rg = _broadcast_coalesced_reshape(buffers_not_rg, devices, detach=True)
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/nn/parallel/replicate.py", line 67, in _broadcast_coalesced_reshape
    return comm.broadcast_coalesced(tensors, devices)
  File "/home/mhorg/miniconda3/envs/pt13/lib/python3.7/site-packages/torch/cuda/comm.py", line 39, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: Unconvertible NCCL type
```

## Expected behavior

No error

## Environment

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 11.1/8.0.4
 - GPU models and configuration: v100-sxm2-32gb
 - Any other relevant information:

## Additional context
- the error only occurs when using 2 or more GPUs
- if you remove the `1j` from the `__init__` function, the error goes away

cc @ezyang @anjali411 @dylanbespalko @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by osalpekar** [comment]
Confirming that I was able to repro this issue. Seems like the error message is coming from `torch/csrc/cuda/nccl.cpp` when converting from `at::ScalarType` to NCCL types. Based on https://github.com/pytorch/pytorch/issues/45760, we are adding complex tensor support to the collectives individually (using `torch.view_as_real()`) since NCCL does not support complex types natively (see [here](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html) for reference). We can try to add this support to `broadcast_coalesced` which is needed for DataParallel.

**Comment by ezyang** [comment]
cc @bdhirsh

**Comment by osalpekar** [comment]
Closed by https://github.com/pytorch/pytorch/pull/48686
