### ISSUE TITLE
Add nondeterministic error for `index_copy_` if duplicate indices are given

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#46743]
`index_copy_` is nondeterministic if the indices argument contains duplicate entries. When `torch.set_deterministic(True)` is set, it should produce an error.

**Comment by kurtamohler** [comment]
@ngimel, is `index_copy` also nondeterministic with duplicate indices, or is it just the in-place operation?

If it's only the in-place operation, then perhaps we should just fix the nondeterminism by using a temporary result tensor and copy it to `self` afterward. We could check if the deterministic flag is set and there are duplicate indices--only use a temp tensor in that case.

**Comment by ngimel** [comment]
Yes, `index_copy` is also non-deterministic with duplicate indices.
