### ISSUE TITLE
torch.backends.cudnn.CuDNNError: 4: b'CUDNN_STATUS_INTERNAL_ERROR'

### ISSUE THREAD

**Issue by lizaigaoge550** [pytorch/pytorch#4675]
when i use pytorch on windows
hx,cx = self.lstm(....) error
  File "C:\Users\v-yugao\AppData\Local\Continuum\miniconda3\lib\site-packages\torch\backends\cudnn\__init__.py", line 303, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 4: b'CUDNN_STATUS_INTERNAL_ERROR'
i don't know and how can i fix it?

**Comment by peterjc123** [comment]
Would you please send me a piece of code that can reproduce your issue? And please check the GPU memory is sufficient and there's no zombie python processes running in the background.

**Comment by peterjc123** [comment]
And it may be related to #4632.

**Comment by lizaigaoge550** [comment]
Thank you very much and i have already solved this problem @peterjc123

**Comment by peterjc123** [comment]
@lizaigaoge550 Could you please post the solution here to help others if possible?

**Comment by lizaigaoge550** [comment]
ok, actually, it's my code wrong,  the problem is the index of word embedding.
