### ISSUE TITLE
why the scales in quantization are floats not in the format of m/2^n

### ISSUE THREAD

**Issue by HumberMe** [pytorch/pytorch#46756]
on the hardware, while we are doing quantized model inference, we use featmap*m/2^n to simulate resaling from one layer(int32) to another(int8).
but in the pytorch quantization, it is found that the scale is simply calculated by (max-min)/255, while max and min are both floats.
due to the m and n are both integer, scale(m/2^n) is not totally equal to scale((max-min)/255)

For example, max = 3.1415 and min=1.9276, the scale=0.00476...
there is no m and n can make this scale

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
PyTorch quantization docs has more details on this https://pytorch.org/docs/stable/quantization.html#quantized-tensors.

Closing this as it is not an issue/bug. If there are specific questions about quantization please use the discussion forums - https://discuss.pytorch.org/c/quantization/17

**Comment by HumberMe** [comment]
> PyTorch quantization docs has more details on this https://pytorch.org/docs/stable/quantization.html#quantized-tensors.
> 
> Closing this as it is not an issue/bug. If there are specific questions about quantization please use the discussion forums - https://discuss.pytorch.org/c/quantization/17

PyTorch quantization docs has no details about this issue
