### ISSUE TITLE
einsum ignore transpose(.t) when input matrix dimension is big?

### ISSUE THREAD

**Issue by li012589** [pytorch/pytorch#46764]
## 🐛 Bug

einsum ignore matrix transpose method (`tenosr.t()`) when inputs dimensions are big. 

## To Reproduce

I found this piece of code reports an error when I try to implement a simple kronecker product. In theory, the assert statment shouldn't report anything. Also, when change `lineSize`  to 128, the error will not be reported.

And a close examination shows that when `lineSize` is 256, kron(A.t, B.t) == kron(A, B). So, it seems einsum somehow ignored the transpose.

```python
import torch
from numpy.testing import assert_allclose

lineSize = 256 # change this to 128, assert will pass

def _kronecker(A, B):
    AB = torch.einsum("ab,cd->acbd", A, B).reshape(A.shape[0] * B.shape[0], A.shape[1] * B.shape[1])
    return AB

A = torch.randint(2, [lineSize, lineSize]).int()
B = torch.randint(2, [lineSize, lineSize]).int()

AB = _kronecker(A, B)
ABT = _kronecker(A.t(), B.t())

assert_allclose(AB.t().detach().numpy(), ABT.detach().numpy())

```

## Expected behavior

kron(A.t, B.t) == kron(A, B).t

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.17)
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] _tflow_select             2.3.0                       mkl
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-include               2020.0                      166
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.1.0            py37hc64f4ea_0
[conda] mkl_random                1.1.1            py37h959d312_0
[conda] numpy                     1.17.2           py37h99e6662_0
[conda] numpy-base                1.17.2           py37h6575580_0
[conda] numpydoc                  1.1.0                      py_0
[conda] pytorch                   1.6.0                   py3.7_0    pytorch
[conda] tensorflow                1.14.0          mkl_py37h085be34_0
[conda] tensorflow-base           1.14.0          mkl_py37h5a24fda_0
[conda] torchvision               0.7.0                  py37_cpu    pytorch

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @bhosmer @smessmer @ljk53 @ailzhang @vishwakftw @jianyuh @nikitaved @pearu @mruberry

**Comment by zhangguanheng66** [comment]
See different behavior with a lineSize of 128 and 256.

**Comment by heitorschueroff** [comment]
This seems to be an issue wit either TensorIterator or cpu_kernel_vec as shown in the following snippet. The code works for size 128, but for size 256 it only works if the input is contiguous. This error happens with both mul and add kernels (and likely any kernel using cpu_kernel_vec).

```
import torch

# SIZE = 128
SIZE = 256

def kronecker(A, B):
    X = A.reshape(A.shape[0], 1, A.shape[1], 1)
    Y = B.reshape(1, B.shape[0], 1, B.shape[1])
    return X.mul(Y).reshape(A.size(0) ** 2, A.size(0) ** 2)
    # return X.add(Y).reshape(A.size(0) ** 2, A.size(0) ** 2)

A = torch.randint(2, (SIZE, SIZE))
B = torch.randint(2, (SIZE, SIZE))

AB = kronecker(A, B)
AB_T = kronecker(A.T, B.T)
# AB_T = kronecker(A.T.contiguous(), B.T.contiguous())

assert AB.T.allclose(AB_T)
```

**Comment by ngimel** [comment]
This is not an issue with cpu_kernel_vec, mul/add produces correct output for both cases. It is an issue with reshape, here's a repro:
```
for size in (128, 256):
    print(f'size={size}')
    a = torch.randn(size, size, size, size)
    ap = a.permute(2, 3, 0, 1).contiguous().permute(2, 3, 0, 1)
    print("a==ap", (a == ap).all())
    print("a==ap reshaped", (a.reshape(size*size,-1)==ap.reshape(size*size,-1)).all())
```
