### ISSUE TITLE
Missing support of typing for torch.maximum

### ISSUE THREAD

**Issue by frgfm** [pytorch/pytorch#46797]
## 🐛 Typing support of bare torch functions

Hello there :wave: 

Just reporting a small typing miss I just noticed.
Apparently, `torch.maximum` does not support typing. I suspect there might be others as well.

## To Reproduce

Running mypy on the following snippet
```
import torch

x = torch.rand(8)
y = torch.rand(8)
z = torch.maximum(x, y, out=x)
```
yields
```
error: Module has no attribute "maximum"  [attr-defined]
    z = torch.maximum(x, y, out=x)
```

## Expected behavior

Typing verification with mypy should run smoothly on this snippet.

## Environment

 - PyTorch Version: 1.6.0
 - OS: Linux
 - How you installed PyTorch: conda
 - Python version: 3.7.4
 - CUDA/cuDNN version: CUDA 10.2 / cuDNN 7.6.5
 - GPU models and configuration: NVIDIA GeForce GTX 1050 (driver 450.66)

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by ezyang** [comment]
This might be fixed in master; can you download a nightly and see?

**Comment by ezyang** [comment]
In my build I see

```
def maximum(input: Tensor, other: Tensor, *, out: Optional[Tensor]=None) -> Tensor: ...
```

in `torch/_C/_VariableFunctions.pyi`

**Comment by frgfm** [comment]
Thanks for your input @ezyang, I was using the last stable release! But this is indeed fixed on master :ok_hand:
