### ISSUE TITLE
torch in cloud(randomly sche) may have server connect timeout problem

### ISSUE THREAD

**Issue by zrss** [pytorch/pytorch#46800]
TcpStore listen at all addresses (0.0.0.0), as it listen at `port`

https://github.com/pytorch/pytorch/blob/789e9353044eb2227462ef470e4b362ac025be4d/torch/lib/c10d/TCPStore.cpp#L301-L310

a pytorch server proc will start a tcp-daemon and then connect to it by `address:port`

recently, we have this case, launch the pytorch in two nodes (n1:192.x.x.0, n2:192.x.x.1), and due to the proc of pytorch is randomly scheduled to a node by the scheduler, so we can't simply assume the server proc is running at n1 or n2

to clarify

n1: the worker proc is running, but server_addr is n1
n2: the server proc is running, but server_addr is n1

server proc and worker proc will timeout after 300s left

though this problem can be solved by the node index, as we can force the server proc running at the index 1 of the node rather then other node

but i propose to add some protected codes or logs around L301 - L310

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment]
Hi @zrss, thanks for filing this issue. I don't quite understand the proposal here, what is the code/logs that you wish to add around 301-310? Feel free to send a PR as well, if that would be better.

**Comment by zrss** [comment]
@rohan-varma , thanks for the reply ~ i'd like to make the server connect to itself rather than the `masterAddr` from the input param and print the value of the `masterAddr`, i have posted a PR but stuck on test cases (still need time to fix it) ...
