### ISSUE TITLE
working as the eval() mode, but the net with the batchnorm layer will raise an error, suggesting needing more than one sample input.

### ISSUE THREAD

**Issue by minghuisvn** [pytorch/pytorch#46818]
## 🐛 Bug

Net with BatchNorm layer , which was set as eval(),  raised an error  when giving an tensor containning only one sample as  input. The error is as follow:
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 1150])

## To Reproduce
My code is:
```
class MLP(nn.Module):
    def __init__(self, num_features, num_hiddens, num_outputs):
        super(MLP, self).__init__()
        self.num_features = num_features
        self.num_hiddens = num_hiddens
        self.num_outputs = num_outputs

    def forward(self, X):
        X = nn.Linear(self.num_features, self.num_hiddens)(X)
        X = nn.BatchNorm1d(self.num_hiddens)(X)
        X = nn.Tanh()(X)
        X = nn.Dropout(p=0.15)(X)
        X = nn.Linear(self.num_hiddens, int(0.9*self.num_hiddens))(X)
        X = nn.BatchNorm1d(int(0.9*self.num_hiddens))(X)
        X = nn.Tanh()(X)
        X = nn.Dropout(p=0.15)(X)
        X = nn.Linear(int(0.9*self.num_hiddens), int(0.9*0.9*self.num_hiddens))(X)
        X = nn.BatchNorm1d(int(0.9*0.9*self.num_hiddens))(X)
        X = nn.Tanh()(X)
        X = nn.Dropout(p=0.15)(X)
        X = nn.Linear(int(0.9*0.9*self.num_hiddens), int(0.9*0.9*0.9*self.num_hiddens))(X)
        X = nn.BatchNorm1d(int(0.9*0.9*0.9*self.num_hiddens))(X)
        X = nn.Tanh()(X)
        X = nn.Dropout(p=0.15)(X)
        X = nn.Linear(int(0.9*0.9*0.9*self.num_hiddens), self.num_outputs)(X)
        
        
        return X

net = MLP(172, 1150, 3)
net.eval()
X = torch.randn((1, 172))
print(net(X))
```

## Expected behavior
For one sample input, I hope the net will give an entry output since I have set the net to evaluate mode.

## Environment
PyTorch version: 1.5.1+cu92
Is debug build: False
CUDA used to build PyTorch: 9.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 450.80.02
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.5.1+cu92
[pip3] torchvision==0.6.1+cu92
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.1           py37hbc911f0_0
[conda] numpy-base                1.19.1           py37hfa32c7d_0
[conda] torch                     1.5.1+cu92               pypi_0    pypi
[conda] torchvision               0.6.1+cu92               pypi_0    pypi
## Additional context

cc @albanD @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @minghuisvn.

**Comment by albanD** [comment]
This is surprising as the check should only run in `training` mode: https://github.com/pytorch/pytorch/blob/3924c55f4c7b15c37c11a666eeccf40498d7bc84/torch/csrc/api/include/torch/nn/functional/batchnorm.h#L20

@mruberry could this be linked to the recent changes in batchnorm to clarify the tracking stats behavior?

**Comment by mruberry** [comment]
@albanD I'm not familiar with any changes like that recently.

**Comment by mruberry** [comment]
This reproduces in version 1.6.0+cu101 on Colab.

**Comment by albanD** [comment]
Ho ok so maybe it's always been this way !

**Comment by ptrblck** [comment]
@minghuisvn You are currently recreating all modules in the `forward` pass, so that they will never be properly registered.
Calling `net.eval()` changes the internal `.training` of `MLP` to `False`, but doesn't change the behavior of the newly created layers in `forward`.

A workaround would be to use:
```python
    def forward(self, X):
        X = nn.Linear(self.num_features, self.num_hiddens)(X)
        X = nn.BatchNorm1d(self.num_hiddens).train(self.training)(X)
        ...
```
however, I still don't think this is what you want, since you would still recreate these layers randomly in each forward pass without any training.

Instead you should create the layers in `MLP.__init__` and use them in `forward` as shown e.g. [here](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#define-a-convolutional-neural-network).

**Comment by mruberry** [comment]
Thanks @ptrblck!

**Comment by minghuisvn** [comment]
@ptrblck  I finally understand what happened in that case. In the forward function, the layers created would be variable, and not be registered in the nn.Parameters(). All the layers that need to be updated should be defined in the __init__ function, so they can be identical when called in the forward process. This is a notable term in the model definition. Thanks!
