### ISSUE TITLE
TorchScript not recognize -0.0 as argument

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#46848]
## To Reproduce

1. Add a test `('copysign', (S, S), (-0.0,), 'scalar_neg_zero', (False,))` with `-0.0` as an input to [torch/testing/_internal/common_methods_invocations.py](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py).
The PR is #46396.
1. Got an `AssertError` for `TestJitGeneratedAutograd` at https://github.com/pytorch/pytorch/blob/ac146c48200cc3c32087bff6337588205ba5e721/torch/testing/_internal/jit_utils.py#L611-L615
1. Comparing the code and graph between both function:
-  Original`m`
![image](https://user-images.githubusercontent.com/68879799/97059735-42b27480-155f-11eb-82de-76a8d47f0efa.png)
- Imported `m_import`
![image](https://user-images.githubusercontent.com/68879799/97059742-4cd47300-155f-11eb-9e81-6186db37da41.png)
1. `-0.0` is converted to `0.0` as shown above.
1. Even if it seems two functions have same arugment as `0.0`, the outputs from them are totally different. The original function `m` is actually taking `-0.0` as the input, but the imported function `m_import` is taking `0.0` as the input.

## Expected behavior

The argument should be passed as `-0.0` rather than `0.0` in the function.

## Environment
PR based on viable/strict branch.

PyTorch version: 1.8.0a0+d945e36
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: version 3.14.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.8.0a0
[pip3] torchvision==0.8.0a0+c36dc43
[conda] mkl                       2020.2                      260
[conda] mkl-include               2020.2                      260
[conda] numpy                     1.19.1           py38ha6d8c68_0
[conda] numpy-base                1.19.1           py38h68fea81_0
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.8.0a0                   dev_0    <develop>
[conda] torchvision               0.8.0a0+c36dc43           dev_0    <develop>

## Additional context

cc @gmagogsfm

**Comment by eellison** [comment]
Bootcamp: check out the printing of constants in python_print and make sure we're including the sign for zero value'd consants
