### ISSUE TITLE
issues with nn.utils.weight_norm at network evaluation

### ISSUE THREAD

**Issue by adrienchaton** [pytorch/pytorch#4685]
Hi Pytorch community,

Thanks for the amazing library you are putting on, my favorite now.

About the **nn.utils.weight_norm**, I use it on linear layers, at training it seems working well.
Then I load my trained model, put it on eval() and run it on my data which created a steadily increasing memory load until the GPU is saturated (both on GTX Titan or 980) ...
I wondered what was the reason and eventually used nn.utils.remove_weight_norm on the corresponding layers after loading the trained weight and then the memory kept stable at a normal load ...

Is there an issue here ?

I mean, when not computing gradients and optimization, it should simply output the same values with or without the weight decomposition. Then removing it shouldn't affect the generation after the end of the training and it's only a minor issue as it can be alleviated with the remove_weight_norm. Or maybe there's something I don't understand here ?

Two other minor points:
_ I also had an issue when using **torch.nn.ConvTranspose1d** which returned 'RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.'
It is similar to: https://github.com/pytorch/pytorch/issues/3512 and when setting torch.backends.cudnn.enabled = False it doesn't appear (and the input was contiguous in both cases). I wanted to add that it seems to depend on the input tensor size as the error was returned when my Lin was only 1 (with stride = 4 and kernel size = 4). Can be fixed with changing the backend but maybe it is worth noting it ..
_ Lastly, I noted a weird behavior with **F.log_softmax** that I am using at the output of a MLP to train on uint8 samples with F.nll_loss. In this case it is with a sampleRNN model that learns to predict 8bit audio samples. Training loss behaves well, then at generation I take the argmax of the prediction in order to retrieve the sample. If I take it on the logsoftmax or softmax outputs it behaves badly whereas it works better on the raw MLP output .. Whereas it should be consistent at generation to use any and the argmax position should remain the same ?

Thanks everyone here !

**Comment by soumith** [comment]
@adrienchaton what version of pytorch are you on: `print(torch.__version__)`. Make sure you are atleast on `0.3`.

About `nn.utils.weight_norm`, can you give a small test program (<100 lines) that can reproduce the issue? we can take a look

**Comment by adrienchaton** [comment]
for pytorch version GPUs are running on 0.2.0_3
let's update and see if it is still happening ?

**Comment by soumith** [comment]
@adrienchaton did you ever update and check that it's still happening (or not happening)?

**Comment by gchanan** [comment]
Closing as these are reports from 0.2 with no update.  If this error still exists, people reopen.
