### ISSUE TITLE
[ONNX] error with pytorch "RuntimeError: Unexpected node type: onnx::Cast"

### ISSUE THREAD

**Issue by oneway234** [pytorch/pytorch#46898]
## ❓ Questions: Coverting to ONNX issue
It seems like the same issue as [this.](https://github.com/pytorch/pytorch/issues/43417)
So I rewrote the function "overlap_and_add" as following:

    def overlap_and_add(signal, frame_step):

    outer_dimensions = signal.size()[:-2]
    frames, frame_length = signal.size()[-2:]
    subframe_length = math.gcd(frame_length, frame_step)  # gcd=Greatest Common Divisor
    subframe_step = frame_step // subframe_length

    subframes_per_frame = frame_length // subframe_length
    output_size = frame_step * (frames - 1) + frame_length
    output_subframes = output_size // subframe_length

    subframe_signal = signal.view(*outer_dimensions, -1, subframe_length)

    frame = torch.arange(0, output_subframes).unfold(0, subframes_per_frame, subframe_step)
    frame = signal.new_tensor(frame).long()  # signal may in GPU or CPU
    frame = frame.contiguous().view(-1)

    # result = signal.new_zeros(*outer_dimensions, output_subframes, subframe_length)
    # result = signal.new(*outer_dimensions, output_subframes, subframe_length).zero_()
    # result.index_add_(-2, frame, subframe_signal)
    tmp = signal.new(*outer_dimensions, output_subframes, subframe_length).zero_()
    j = 0
    for i in range(len(frame)):
        tmp[:,:,frame[i],:] += subframe_signal[:,:,j,:]
        j += 1
    result=tmp

    result = result.view(*outer_dimensions, -1)
    return result

**1.** 
I tried converting from torch to ONNX. It converted sucessfuly, but not work.
Follow steps from website (Pytoch onnx). Then used $“testing.assert_almost_equal” to verify output. The orignal TasNet pre-trained model worked, however the result of onnx are zeros. Its weights seems to be part of zero.

 
**Further information**

- Pytorch 1.3.1

**2.** 
Therefore, I switched to Pytorch==1.6.0. However, it reported an error.

> RuntimeError: Unexpected node type: onnx::Cast

**Further information**

- Pytorch 1.6.0

I've replaced the function "index_add_()" however it still report the same error.
How to fix this kind of bug(onnx::Cast)? 

**Summry**
I converted sucessfuly in Pytorch==1.3.1 but onnx was no weights. Then switched to Pytorch==1.6.0. reported an error.
This is my [project](https://github.com/oneway234/torch_to_onnx).

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@oneway234 - Several updates have been added to ONNX exporter in PyTorch since PyTorch 1.3.1. Could you please try with the latest version of PyTorch (1.7) and see if this issue is resolved.

**Comment by oneway234** [comment]
Thanks for help
But I got same issue. RuntimeError: Unexpected node type: onnx::Cast

> /Users/wei/work/python_all/signal_processors/conv_tasnet/utils.py:31: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  subframe_length = math.gcd(frame_length, frame_step)  # gcd=Greatest Common Divisor
/Users/wei/work/python_all/signal_processors/conv_tasnet/utils.py:39: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  frame = torch.arange(0, output_subframes).unfold(0, subframes_per_frame, subframe_step)
/Users/wei/work/python_all/signal_processors/conv_tasnet/utils.py:40: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  frame = signal.new_tensor(frame).long()  # signal may in GPU or CPU
/Users/wei/work/python_all/signal_processors/conv_tasnet/utils.py:46: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  tmp = signal.new(*outer_dimensions, output_subframes, subframe_length).zero_()
/Users/wei/work/python_all/signal_processors/conv_tasnet/utils.py:48: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(len(frame)):
/Users/wei/work/python_all/models/conv_tasnet/conv_tasnet.py:56: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  T_origin = torch.tensor(88200)
/Users/wei/work/python_all/models/conv_tasnet/conv_tasnet.py:57: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  T_conv = torch.tensor(88200)
Traceback (most recent call last):
  File "/Users/wei/work/python_all/demos/demo_tasnet.py", line 12, in <module>
    separate(hparams)
  File "/Users/wei/work/python_all/cb_tests/separate_tasnet.py", line 50, in separate
    verbose=True)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/utils.py", line 934, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/Users/wei/anaconda3/envs/tas/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 87, in _parse_arg
    raise RuntimeError("Unexpected node type: {}".format(value.node().kind()))
RuntimeError: Unexpected node type: onnx::Cast

**Comment by oneway234** [comment]
I opend an issue on onnx, and the contributor said maybe the problem is due to conveter.

Could you please test the modle, as I can't rewrite the code of Pytorch. Thank you.

**Comment by oneway234** [comment]
Hi, I also tried to simplify network model(Only two layer).

But it came out the same error.

Export onnx code:
`# model
    model = torch.load('../checkpoints/only_coder.pth')
    print(model)

    # input data
    torch.onnx.export(model.eval(),
                      dummy_input,
                      "../checkpoints/conv_tasnet/only_coder.onnx",
                      export_params=True)`

**Comment by oneway234** [comment]
Hi,
I convert it sucessfuliy, and it work.
My model is has single and mutiple inputs, so it can't convert directly.
Please convert it separately.

**Comment by oneway234** [comment]
It's seem not this problem, plz move to[ here ](https://github.com/pytorch/pytorch/issues/47182#issuecomment-726251429)to see detail.
