### ISSUE TITLE
switch CUDA svd and qr to using cuSolver

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#4689]
Currently we use MAGMA for these solvers, which uses a mix of CPU and GPU. Wonder if cuSolver will be faster, and we can avoid the CPU path entirely.

cc: @ngimel just want to confirm, cuSolver (dense) wont use the CPU right?

cc @ngimel @vincentqb @vishwakftw @SsnL @jianyuh

**Comment by ngimel** [comment]
Checked with cuSolver team, qr is GPU only, for svd they have CPU path (gesvd) and GPU-only path (gesvdj). They don't benchmark against magma, so YMMV.

**Comment by PiotrSokol** [comment]
@soumith 
I'm sorry to go a bit off topic but I can't find reference about using gpu supported svd/qr. Is it possible to force MAGMA to run the factorization on the gpu?

**Comment by SsnL** [comment]
@PiotrSokol MAGMA's implementation of qr and svd has CPU calls. There are no alternative in MAGMA for these calls afaik. So no.

**Comment by PiotrSokol** [comment]
@SsnL  Thanks!

@soumith  Concerning the benchmarking, cupy uses cusolver as a backend and I compared it, though not very dilligently, to pytorch/MAGMA. MAGMA is ~2.5 faster on my setup, which is a 46 core Xeon CPU E5-2690 v4 @ 2.60GHz  and a Tesla P100 GPU.

**Comment by IvanYashchuk** [comment]
cuSOLVER paths for QR and SVD for CUDA 10.2+ builds were added with https://github.com/pytorch/pytorch/pull/56256 and https://github.com/pytorch/pytorch/pull/48436.
