### ISSUE TITLE
torch.futures.waitall() doesn't throw if an exception is raised in one of the futures

### ISSUE THREAD

**Issue by froody** [pytorch/pytorch#46931]
## 🐛 Bug

torch.futures.waitall() doesn't throw if an exception is raised in one of the futures

## To Reproduce

python [waitall.py](https://gist.github.com/froody/b13cb281e1386363e69e4751799a2e10)

I get a timeout after 60 seconds:
```
>>> wait_all
hi from worker2
hi from worker1
Traceback (most recent call last):
  File "waitall.py", line 50, in <module>
    torch.multiprocessing.spawn(main, nprocs=3)
  File "/private/home/tbirch/.conda/envs/torch160-src/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/private/home/tbirch/.conda/envs/torch160-src/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/private/home/tbirch/.conda/envs/torch160-src/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/private/home/tbirch/.conda/envs/torch160-src/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/private/home/tbirch/src/fairscale/waitall.py", line 43, in main
    torch.futures.wait_all(futures)
  File "/private/home/tbirch/.conda/envs/torch160-src/lib/python3.7/site-packages/torch/futures/__init__.py", line 140, in wait_all
    return [fut.wait() for fut in torch._C._collect_all(futures).wait()]
RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.
```

## Expected behavior

An exception is thrown almost immediately from the callsite of `waitall`. 

## Environment

Collecting environment information...
PyTorch version: 1.6.0a0+b31f58d
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.18.0

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0a0+d3e3dec
[pip3] torchtext==0.8.0a0+e9b711b
[pip3] torchvision==0.7.0
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.2                      256    conda-forge
[conda] numpy                     1.19.1           py37h8960a57_0    conda-forge
[conda] torch                     1.6.0a0+bd69bb1          pypi_0    pypi
[conda] torchtext                 0.8.0a0+e9b711b          pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @xush6528

**Comment by pritamdamania87** [comment]
It looks like one of the RPC functions does this:

```
def worker1():
    print(f"hi from worker1")
    while True:
        pass
    print(f"bye from worker1")
```

Is this intended since the function would never return? What is happening is that `wait_all` is waiting for this function to finish and hits the RPC timeout and hence you get an error indicating the RPC timed out. The contract for `wait_all` currently is that it waits for all the futures to finish and doesn't exit early if one of the futures encountered a failure.

In terms of the error that you are seeing, both futures are marked with errors, but the `wait_all` method is just throwing the first error it sees in the list (which is the time out). If you change the order of the RPC's you will still have a 60 second pause and then see the exception `error in worker2`.

**Comment by froody** [comment]
The `while True` is a placeholder for any blocking operation. If I replace it with `torch.distributed.all_reduce` then I still see the timeout.

**Comment by pritamdamania87** [comment]
@froody Adding allreduce as a blocking operation works for me and it raises the appropriate exception without waiting for 60sec: https://gist.github.com/pritamdamania87/adf30c5017813843d00421979509b8b3.

If the blocking operation in the RPC call takes more than 60seconds, you will see the RPC timed out error. If you have an RPC that needs to run for more than 60 seconds, you can specify a larger timeout using the `timeout` parameter of `rpc_async`.

**Comment by froody** [comment]
@pritamdamania87 right, but in your example, the all_reduce will complete before the exception is thrown, which doesn't really prove anything. An updated example [here](https://gist.github.com/froody/60c79532b1c577383409210bf8df8900) shows a case of raising *before* all_reduce on one worker only

**Comment by pritamdamania87** [comment]
@mrshenli Chatted with @froody offline about this, and his suggestion was that having `wait_all` exit as soon as it encounters an error would be a nice user experience. I was wondering if it makes sense to add a `exit_on_error` flag to `wait_all` such that we don't break the existing contract of `wait_all` but also allow the flexibility to users such that `wait_all` exits as soon as any one of the futures encounters an error.

**Comment by froody** [comment]
CC @anj-s

**Comment by rohan-varma** [comment]
Bumping to high pri since @tierex is running into this issue as well. cc @pritamdamania87

**Comment by mrshenli** [comment]
@xw285cornell is also requesting this feature

**Comment by pritamdamania87** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/53953
