### ISSUE TITLE
PowBackward always operates in Complex dtype

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#46936]
## 🐛 Bug

`auto` in the following line is always deduced to be c10::complex:
https://github.com/pytorch/pytorch/blob/bbe5bfaa4f5ec1d80cd971198e4abcfd2ea96a7a/torch/csrc/autograd/FunctionsManual.cpp#L188
This leads to PowBackward always operating on complex tensors due to type promotion:
https://github.com/pytorch/pytorch/blob/bbe5bfaa4f5ec1d80cd971198e4abcfd2ea96a7a/torch/csrc/autograd/FunctionsManual.cpp#L192
which should lead to a performance regression.

cc @ezyang @anjali411 @dylanbespalko @mruberry @VitalyFedyunin @ngimel

**Comment by zou3519** [comment]
PR was reverted

**Comment by anjali411** [comment]
Fixed in #48909
