### ISSUE TITLE
No module named torchvision 

### ISSUE THREAD

**Issue by smallnine9** [pytorch/pytorch#4697]
After I install pytorch from source，I use import torchvision and I met error：no module named torchvision, how to solve it?

**Comment by Kaixhin** [comment]
[`torchvision`](https://github.com/pytorch/vision) is a separate install to `torch`.

**Comment by irving-genvis** [comment]
If you followed the instructions here: http://pytorch.org/ and install with conda it will install both torch and torchvision together.

**Comment by gglinux** [comment]
pip install https://files.pythonhosted.org/packages/8c/52/33d739bcc547f22c522def535a8da7e6e5a0f6b98594717f519b5cb1a4e1/torchvision-0.1.8-py2.py3-none-any.whl
