### ISSUE TITLE
flake8 errors are not shown by github actions

### ISSUE THREAD

**Issue by antocuni** [pytorch/pytorch#46985]
## 🐛 Bug

Look at this failed [flake8 job](https://github.com/pytorch/pytorch/runs/1320258832): from the output log, you can't see what's wrong. Running it locally showed two actual problems (which, for reference, were solved by [this commit](https://github.com/antocuni/pytorch/commit/0e0484357e6bfd873fc49018d6c31d6c154d0aad).
```
$ flake8 
./test/test_linalg.py:703:41: E261 at least two spaces before inline comment
./test/test_linalg.py:704:74: E261 at least two spaces before inline comment
```

I think that the problem is here:
https://github.com/pytorch/pytorch/blob/46b252b83a97bba0926cead050d76fcef129cb6b/.github/workflows/lint.yml#L66-L72

In particular: `flake8` writes its output to a temporary file, which is `cat`ted later. But if `flake8` fails, the `cat` is never executed due to `set -e`.

I think that this problem was introduced by #46740: before that `--exit-zero` ensured that `flake8` never failed and thus `cat` was always executed.

/cc @samestep since he's the author of the PR.

**Comment by samestep** [comment]
Good catch, thanks! I'll go ahead and fix that, sorry for introducing the regression
