### ISSUE TITLE
torch.ceil not supported for sparse layout

### ISSUE THREAD

**Issue by hlahkar** [pytorch/pytorch#46988]
Call torch.ceil on a sparse tensor
Below is a code sample:

import torch
i = torch.cuda.LongTensor([[0, 1, 1],
                      [2, 0, 2],
                      [2, 0, 2]])

v  = torch.cuda.FloatTensor([3.2, -44.5, -5.1])

s = torch.sparse_coo_tensor(i, v, torch.Size([2, 4, 4]), device=torch.device('cuda'))
print(torch.ceil(s))

Actual behavior
Traceback (most recent call last):
  File "sparse_floor.py", line 9, in <module>
    print(torch.ceil(s))
RuntimeError: Could not run 'aten::ceil.out' with arguments from the 'SparseCUDA' backend. 'aten::ceil.out' is only available for these backends: [CPU, CUDA, Named, Autograd, Profiler, Tracer].

Expected behavior
ceil of the sparse tensor should get calculated and output as a sparse tensor

Environment
Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.8.0a0
[pip3] torchtext==0.8.0a0+7e267d2
[pip3] torchvision==0.8.0a0+be8192e
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.2.89 hfd86e86_1
[conda] magma-cuda102 2.5.2 1 pytorch
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py38he904b0f_0
[conda] mkl_fft 1.1.0 py38h23d657b_0
[conda] mkl_random 1.1.1 py38h0573a6f_0
[conda] numpy 1.19.1 py38hbc911f0_0
[conda] numpy-base 1.19.1 py38hfa32c7d_0
[conda] torch 1.8.0a0 dev_0
[conda] torchtext 0.8.0a0+7e267d2 pypi_0 pypi
[conda] torchvision 0.8.0a0+be8192e pypi_0 pypi

PyTorch Version: 1.8.0a0
OS: Linux
How you installed PyTorch (conda, pip, source): source
Build command you used (if compiling from source): python setup.py develop
Python version: 3.8
CUDA/cuDNN version: 10.2

cc @aocsa @nikitaved @pearu @mruberry

**Comment by mruberry** [comment]
@hlahkar, see @gchanan's question here: https://github.com/pytorch/pytorch/issues/46987#issuecomment-718065283.

Instead of opening an issue for each of these, maybe posting a list of functions you'd like supported (and why) to the sparse rollup issue would be more helpful? It'd be easier to track. That issue is here: https://github.com/pytorch/pytorch/issues/44634.

**Comment by hlahkar** [comment]
> @hlahkar, see @gchanan's question here: [#46987 (comment)](https://github.com/pytorch/pytorch/issues/46987#issuecomment-718065283).
> 
> Instead of opening an issue for each of these, maybe posting a list of functions you'd like supported (and why) to the sparse rollup issue would be more helpful? It'd be easier to track. That issue is here: #44634.

@mruberry I would like to contribute to the development of the Sparse Framework. I was taking one operator at a time and implementing the same; hence I was raising the issues. Please let me know how I can cooperate on the development of the Sparse rollup

**Comment by mruberry** [comment]
@hlahkar Glad to hear it! Sorry it took awhile for me to get back to you, it's been a very busy week and I appreciate your patience.

Here's what I'd propose:

- write a helper function for implementing unary elementwise sparse operations using the non-sparse operation, so that elementwise sparse operations can be written in 1-2 lines
- add a test suite to test_sparse.py that uses the OpInfo test pattern for unary elementwise sparse operations and does the following:
  - updates OpInfos in common_methods_invocations.py to have a "supports_sparse" property
  - writes an OpInfo-based test (see test_unary_ufuncs.py for an example) that tests these ops by creating some "interesting" sparse tensors, calling the op, and comparing the result with a dense version of the operation, too

That would make implementing and testing new unary elementwise sparse operations trivial. 

Does that proposal make sense? Let me know if I can provide additional references/information about this approach and what it might look like.

**Comment by hlahkar** [comment]
> @hlahkar Glad to hear it! Sorry it took awhile for me to get back to you, it's been a very busy week and I appreciate your patience.
> 
> Here's what I'd propose:
> 
> * write a helper function for implementing unary elementwise sparse operations using the non-sparse operation, so that elementwise sparse operations can be written in 1-2 lines
> * add a test suite to test_sparse.py that uses the OpInfo test pattern for unary elementwise sparse operations and does the following:
>   
>   * updates OpInfos in common_methods_invocations.py to have a "supports_sparse" property
>   * writes an OpInfo-based test (see test_unary_ufuncs.py for an example) that tests these ops by creating some "interesting" sparse tensors, calling the op, and comparing the result with a dense version of the operation, too
> 
> That would make implementing and testing new unary elementwise sparse operations trivial.
> 
> Does that proposal make sense? Let me know if I can provide additional references/information about this approach and what it might look like.

@mruberry - Sorry for the late response...I was out of office for a few days...will be taking your suggestion and implement a generic framework as per your proposal....I will be great if you can provide some additional references

**Comment by mruberry** [comment]
The device generic test framework is defined here: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_device_type.py.

It's used in test suites like test_torch.py and test_unary_ufuncs.py. test_unary_ufuncs.py uses an even more up-to-date pattern where tests are generated from "OpInfos." The database of OpInfos is here:

https://github.com/pytorch/pytorch/blob/a6898cb5f461fcdbf79a2d87b30a2fcd3b160e01/torch/testing/_internal/common_methods_invocations.py#L208

OpInfos contain operator metadata useful for testing. An annotation for ops in the OpInfo db that support sparse can probably be added, and then tests can be written that filter to those ops and generate sparse inputs to them. 

Alternatively, an easier step towards modernizing the test suite would be to just make the test suite generic and use the @dtypes decorator to annotation the tests, like the tests in TestTorchDeviceType do. 

Let me know if those pointers make sense.

**Comment by hlahkar** [comment]
> The device generic test framework is defined here: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_device_type.py.
> 
> It's used in test suites like test_torch.py and test_unary_ufuncs.py. test_unary_ufuncs.py uses an even more up-to-date pattern where tests are generated from "OpInfos." The database of OpInfos is here:
> 
> https://github.com/pytorch/pytorch/blob/a6898cb5f461fcdbf79a2d87b30a2fcd3b160e01/torch/testing/_internal/common_methods_invocations.py#L208
> 
> OpInfos contain operator metadata useful for testing. An annotation for ops in the OpInfo db that support sparse can probably be added, and then tests can be written that filter to those ops and generate sparse inputs to them.
> 
> Alternatively, an easier step towards modernizing the test suite would be to just make the test suite generic and use the @dtypes decorator to annotation the tests, like the tests in TestTorchDeviceType do.
> 
> Let me know if those pointers make sense.

Thanks for the inputs; let me go through the same. If I have any doubts, I will get back to you

**Comment by hlahkar** [comment]
@mruberry - I have created a test framework https://github.com/pytorch/pytorch/pull/48488. This is WIP; can you kindly check whether the idea is correct. You can also suggest what kind of test cases to be added.

**Comment by mruberry** [comment]
> @mruberry - I have created a test framework #48488. This is WIP; can you kindly check whether the idea is correct. You can also suggest what kind of test cases to be added.

I commented on the PR. Your going in the right direction but we should reuse the existing code instead of duplicating it. For sparse OpInfo-based testing let's start small with just one new test that compares the same operation on sparse and strided tensors.

**Comment by hlahkar** [comment]
> > @mruberry - I have created a test framework #48488. This is WIP; can you kindly check whether the idea is correct. You can also suggest what kind of test cases to be added.
> 
> I commented on the PR. Your going in the right direction but we should reuse the existing code instead of duplicating it. For sparse OpInfo-based testing let's start small with just one new test that compares the same operation on sparse and strided tensors.

@mruberry - I made the changes as per the suggestion, kindly review the same

**Comment by mruberry** [comment]
It's looking better but there's still a ways to go. I added some notes.
