### ISSUE TITLE
ClassNLLCriterion Error

### ISSUE THREAD

**Issue by jinbeomdev** [pytorch/pytorch#4701]
> /pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
...
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generated/../THCReduceAll.cuh line=339 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "/home/intern/PycharmProjects/domain-transfer-network-pytorch/test.py", line 189, in <module>
    f_loss_src = torch.mean((fx - fgfx)**2) * 15
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generated/../THCReduceAll.cuh:339

I can't understand why I get this error message. I just tried torch.mean((fx - fgfx)**2) * 15.

**Comment by apaszke** [comment]
Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
