### ISSUE TITLE
Value cannot be converted to type double without overflow: inf

### ISSUE THREAD

**Issue by nbansal90** [pytorch/pytorch#4702]
File "train.py", line 37, in reg
    l2_reg = l2_reg + W.norm(2)****2
  File "/usr/local/torch3/lib/python3.5/site-packages/torch/autograd/variable.py", line 396, in norm
    return super(Variable, self).norm(p)
RuntimeError: value cannot be converted to type double without overflow: inf**

My Pytorch Version is:
>>> import torch
>>> print(torch.__version__)
0.3.0.post4

How could be avoid this error?

**Comment by nbansal90** [comment]
Further Printing the the value returned by the function, it surely seems to be going towards INF. But almost the same logic for custom regularization, works in tensorflow. Am I doing something wrong code wise.

Epoch: [0][0/391] Time 6.739 (6.739) Loss 3157501.5000 (3157501.5000) Prec@1 10.938 (10.938)
Variable containing:
2.7529e+08
[torch.cuda.FloatTensor of size 1 (GPU 0)]

Variable containing:
4.1735e+12
[torch.cuda.FloatTensor of size 1 (GPU 0)]

Variable containing:
5.0968e+27
[torch.cuda.FloatTensor of size 1 (GPU 0)]
…

Then the error.

Thanks!

**Comment by ashishlal** [comment]
I am getting in the same error in same torch version. How did you fix this?

**Comment by szrlee** [comment]
same issue on '0.3.1.post2'

**Comment by nbansal90** [comment]
I think If you simply update the Pytorch with the latest version. The issue should not be seen

**Comment by szrlee** [comment]
the latest binary is 0.3.1.post2. are you installing from github source?

**Comment by jadore801120** [comment]
Same issue. Any update?
