### ISSUE TITLE
PyTorch 1.7.0 CUDA driver warning

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#47038]
## 🐛 Bug

The following warning appears only on `torch==1.7.0`

```
../../../virtualenv/python3.8.3/lib/python3.8/site-packages/torch/cuda/__init__.py:52

  /home/travis/virtualenv/python3.8.3/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)

    return torch._C._cuda_getDeviceCount() > 0
```

Looking at the [pull request](https://github.com/pytorch/pytorch/pull/42249) that introduced it, no warning should be raised for "call to device_count()" with "no gpus"

Having to filter this warning every time `device_count` is called is not ideal.

## To Reproduce

`torch.cuda.device_count()`

## Expected behavior

Does not raise a warning.

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @ngimel

**Comment by gchanan** [comment]
that warnings looks sensible given we can't tell the number of devices if a cuda driver isn't installed.  We could potentially have it only warn once per process.

Does `torch.cuda.is_available()` warn in your case?

**Comment by carmocca** [comment]
Yes:

```python
$ python -c "import torch; torch.cuda.is_available()"
/home/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```

### collect_env.py output:

```
Collecting environment information...
/home/carmocca/projects/kkenv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] torch==1.7.0
[conda] Could not collect
```

**Comment by gchanan** [comment]
ok thanks, warning once seems sensible.

**Comment by carmocca** [comment]
But `is_available()` shouldnt warn right? If no driver is installed, it is not available.

**Comment by gchanan** [comment]
that's a good question.

I don't have a strong opinion, I'd probably go with warning once on both (separately or shared probably doesn't mater) because I feel like the debugability is useful even for `is_available` and some people (as demonstrated) just jump right to using the device_count.

**Comment by NielsPichon** [comment]
Hi! I am running in the same issue.
Isn't the `cuda.is_available()` function designed exactly to avoid running in this type of error and return a boolean tha can be handled by the user?
A workaround would be to wrap the `is_available` or `device_count()` in a try except, but I would argue this is not an ideal solution.

**Comment by gchanan** [comment]
that's reasonable.  On the other hand, let's say you were expecting cuda to be available but it wasn't -- what would you call to get debug info?

**Comment by carmocca** [comment]
> I don't have a strong opinion, I'd probably go with warning once on both (separately or shared probably doesn't mater) because I feel like the debugability is useful even for `is_available` and some people (as demonstrated) just jump right to using the device_count.

I think the following is a very common pattern pre-1.7:

```python
@skipIf(not torch.cuda.is_available())
def test_gpu():
    ...

@skipIf(torch.cuda.device_count() < 2)
def test_distributed():
    ...
```

Now, both of these warn, and it forces users to do something like the following to accomplish the same:

```python
@filterwarnings("ignore:CUDA initialization.*:UserWarning")
@skipIf(not torch.cuda.is_available())
def test_gpu():
    ...

@filterwarnings("ignore:CUDA initialization.*:UserWarning")
@skipIf(torch.cuda.device_count() < 2)
def test_distributed():
    ...
```

So if the warning is not removed for both, I strongly suggest removing the warning for `is_available()` so the following is still possible with no warnings:

```python
@skipIf(not torch.cuda.is_available())
def test_gpu():
    ...

@skipIf(not torch.cuda.is_available() or torch.cuda.device_count() < 2)
def test_distributed():
    ...
```

**Comment by PetrochukM** [comment]
^ I agree. Please remove this warning.

**Comment by mariogeiger** [comment]
I see the same warning when running `backward`
```
python -c "import torch; torch.randn(3, 3, requires_grad=True).sum().backward()"
```

I installed pytorch with cuda because I use the same pytorch install on two different clusters that have the same `/home`

##collect_env.py output:
```
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.6 (Maipo) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-37)
Clang version: Could not collect
CMake version: version 2.8.12.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.0
[pip3] torch-cluster==1.5.8
[pip3] torch-geometric==1.6.1
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.8
[pip3] torch-spline-conv==1.2.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torch-cluster             1.5.8                    pypi_0    pypi
[conda] torch-geometric           1.6.1                    pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.8                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchvision               0.8.1                py38_cu102    pytorch

```

**Comment by trias702** [comment]
I'd just like to say that I too am getting this error on Ubuntu 18.04 and 16.04 with PyTorch 1.7 built against CUDA 11.0 (am using the one from the official repo, not a custom compiled one). No matter what I do, I cannot get PyTorch to see and load in the CUDA I have installed. I have tried CUDA 11.0 and 11.0-Update1, neither works, I have also tried 3 different NVIDIA drivers, and that doesn't fix it. NVCC works fine, just PyTorch can't seem to recognise CUDA at all.

I do not have this issue with PyTorch 1.7 built against CUDA 10.2 on another box, there it all works fine.

**Comment by carmocca** [comment]
ping @malfet (assigned)

given that this did not make the 1.7.1 milestone, what is the plan here?

**Comment by ThiruRJST** [comment]
I still get the same error while loading my model into cuda, it couldn't recognize my GPU.
Pytorch Version: 1.7.0

**Comment by ckrilow** [comment]
I am getting the same error while loading my model into Cuda, with Pytorch Version: 1.6.0, on CentOS Linux 7.

**Comment by malfet** [comment]
This warning is printed only once in the lifetime of the app, see:
https://github.com/pytorch/pytorch/blob/3fec1e5025d12faa3f7eec91c82f92cfc77c9bee/c10/cuda/CUDAFunctions.cpp#L96-L107

**Comment by rudaoshi** [comment]
NO, it prints all the time.

**Comment by txr150430** [comment]
I'm still observing the same issue. Any reasons why?
![image](https://user-images.githubusercontent.com/14965906/113023594-6e0f4000-914b-11eb-98c0-d85299a01b60.png)

![image](https://user-images.githubusercontent.com/14965906/113023682-81221000-914b-11eb-942e-e0df9e5bb520.png)

Can you assist me with this? Thanks.

**Comment by seemethere** [comment]
> I'm still observing the same issue. Any reasons why?
> ![image](https://user-images.githubusercontent.com/14965906/113023594-6e0f4000-914b-11eb-98c0-d85299a01b60.png)
> 
> ![image](https://user-images.githubusercontent.com/14965906/113023682-81221000-914b-11eb-942e-e0df9e5bb520.png)
> 
> Can you assist me with this? Thanks.

This is fixed in 1.8.0, would you mind seeing if you can replicate this in 1.8.0?

**Comment by txr150430** [comment]
Yep. It is Thanks @seemethere . 
![image](https://user-images.githubusercontent.com/14965906/113170354-197fc980-920c-11eb-8946-4cefb78499d0.png)

The warning's gone. Should probably do additional testing, after configuring our image with certain nvidia GPU drivers. :)

**Comment by SaoYear** [comment]
Reboot help.

**Comment by gautamjain1009** [comment]
I am using PyTorch '1.10.0+cu102' and I am running the jobs on cluster. Before Every time PyTorch was able to detect the GPU and run the training on GPU. Recently I got this error, 
```

 => using 'cpu' for computation.
/gpfs/space/home/gautamku/anaconda3/envs/comma2k19/lib/python3.8/site-packages/torch/cuda/__init__.py:80: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
```

When i try to run check if Cuda is available in interactive session, then it returns True. I don't know what is the problem. Any solutions?? Should i downgrade the pytorch version ?
