### ISSUE TITLE
Dose DDP support second-order derivative?

### ISSUE THREAD

**Issue by guozhiyao** [pytorch/pytorch#47040]
## ❓ Questions and Help
I am studying the meta learning which needs the second-order derivative of parameters. I wrap my model by DDP and use only one device, which will return the correct value, while the value will be 0 when I use multi-devices.

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
