### ISSUE TITLE
[PT_BREAK] XLA test fails on PR 

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#47060]
I have this [PR](https://github.com/pytorch/pytorch/pull/46215)
It [fails](https://app.circleci.com/pipelines/github/pytorch/pytorch/231542/workflows/0fc4525f-9040-4fd6-89de-b1e19530f9b0/jobs/8482714) on XLA on `test_accurracy` test.
Other tests are passing fine. 

Can you, please, help figure it out?

**Comment by zou3519** [comment]
You probably meant to post in https://github.com/pytorch/xla/issues?

**Comment by albanD** [comment]
Cannot transfer the issue there I'm afraid. You will need to open a new one.
