### ISSUE TITLE
The official pytorch install command with gpu support not compiled with CUDA

### ISSUE THREAD

**Issue by lemonahmas** [pytorch/pytorch#47062]
## ❓ Questions and Help
By following the official install command "conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch", I still cannot find cuda support.
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

To reproduce the issue:
![image](https://user-images.githubusercontent.com/13514693/97605522-af3edf00-1a49-11eb-9bba-0c561ce9c3fb.png)

Conda list result:
![image](https://user-images.githubusercontent.com/13514693/97605564-c1b91880-1a49-11eb-99ea-390c6b69687b.png)

At least this should be compiled with CUDA I think.
From the official conda pkg source, not mirror.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests as mentioned in the template that you filled!
Please use the forum to ask questions: https://discuss.pytorch.org/

For your particular issue, you should make sure that you have a GPU properly installed with recent nvidia drivers and no cuda install that conflicts with the one from conda.
