### ISSUE TITLE
`new_ones` fails with tensor subclasses

### ISSUE THREAD

**Issue by jph00** [pytorch/pytorch#47069]
## 🐛 Bug

`new_ones` fails with tensor subclasses.

## To Reproduce

```
import torch
class _T(torch.Tensor): ...
x = torch.tensor([1,2]).as_subclass(_T)
x.new_ones((2,3))
```

This throws:

```
TypeError: new_ones() missing 1 required positional arguments: "size"
```

## Expected behavior

It should create the tensor:

```
tensor([[1, 1, 1],
        [1, 1, 1]])
```

## Environment

`torch.__version__` == 1.7.0, running on Ubuntu.

## Additional context

`new_full(..., 1)` is a workaround which does work correctly.

I'm also going to keep a list here of issues I find in the new subclassing support, so that there's an easy reference for those looking for one:

- https://github.com/pytorch/pytorch/issues/47051 Tensor subclasses lose type when pickling
- https://github.com/pytorch/pytorch/issues/47091 `F.grid_sample` fails to dispatch correctly when args are of different subclasses
- https://github.com/pytorch/pytorch/issues/47090 `torch.max` does not create a named tuple if applied to a subclass
- https://github.com/pytorch/pytorch/issues/47186 `new` fails for subclasses

cc @hameerabbasi @rgommers @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @jph00.

**Comment by jph00** [comment]
I don't know how to fix it @mruberry

**Comment by mruberry** [comment]
> I don't know how to fix it @mruberry

haha, no worries @jph00. We just like to indicate our willingness to accept PRs on issues, not necessarily PRs from the person who filed the issue.

**Comment by jph00** [comment]
Ah splendid - it's good news for all that you're not relying on me!

**Comment by jph00** [comment]
@mruberry I guess this isn't worth creating a new issue for - let me know if you want me to.

I just found that `new()` incorrectly returns an empty tensor for subclasses:

```
import torch
class _T(torch.Tensor): ...
x = torch.tensor([1,2]).as_subclass(_T)
x.new((2,3))
```

That returns:

    _T([], dtype=torch.int64)

**Comment by jph00** [comment]
Here's another bug on the same theme - again, let me know if you want me to create a new issue. `torch.max` does not create a named tuple if applied to a subclass, although the docs say it should be.

```
import torch
class _T(torch.Tensor): ...
x = torch.tensor([1,2]).as_subclass(_T)
torch.max(x, dim=0)
```

That returns

    (tensor(2), tensor(1))

**Comment by mruberry** [comment]
> Here's another bug on the same theme - again, let me know if you want me to create a new issue. 

It's a great bug and a new issue would be helpful.

**Comment by hameerabbasi** [comment]
> Here's another bug on the same theme - again, let me know if you want me to create a new issue. `torch.max` does not create a named tuple if applied to a subclass, although the docs say it should be.

This one is in progress: #47110.

**Comment by hameerabbasi** [comment]
I'm fixing the title issue in #47114.

**Comment by jph00** [comment]
I decided to add an issue for `new` after all: https://github.com/pytorch/pytorch/issues/47186
