### ISSUE TITLE
TestTensorDeviceOps auto-generated tests are not actually being run

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#47088]
## 🐛 Bug

I don't think the tests autogenerated from https://github.com/pytorch/pytorch/blob/71c0133e23cf961e492710cee124c227494d0c8b/test/test_torch.py#L20391 are being run at all.

## To Reproduce

1. Change the first 'add' to 'something_ridiculous', or the precision 1e-2 to 0 (lol)
2. Run `python test/test_torch.py`
3. See that there are no test failures

I've also checked test logs for [a test named 'test_sum_complex_neg_dim'.](https://github.com/pytorch/pytorch/blob/71c0133e23cf961e492710cee124c227494d0c8b/test/test_torch.py#L20625) It doesn't exist at all (see [recent test logs](https://app.circleci.com/pipelines/github/pytorch/pytorch/232871/workflows/18aed21b-5bb1-4f5a-9085-1f1f525b9846/jobs/8563727) and try to grep for it

## Expected behavior

These tests should not disappear into the ether

## Environment
master

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @mruberry @VitalyFedyunin

**Comment by zou3519** [comment]
I'm marking this as high-pri because "I would be willing to pay money to get this fixed", but also because if these tests don't run then that leaves room for regressions to sneak in

**Comment by mruberry** [comment]
From a recent test run:

```
test_abs_cpu_bfloat16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_abs_inplace_cpu_bfloat16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.003s)
Oct 29 18:48:41   test_angle_cpu_bfloat16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.003s)
Oct 29 18:48:41   test_asin_cpu_bfloat16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_asin_inplace_cpu_bfloat16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.003s)
Oct 29 18:48:41   test_atan2_cpu_float32 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_float64 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_int16 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_int32 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_int64 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_int8 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
Oct 29 18:48:41   test_atan2_cpu_uint8 (__main__.TestTensorDeviceOpsCPU) ... ok (0.004s)
```

Seems like they're being run?

**Comment by mruberry** [comment]
If I run this locally I get the expected behavior. I changed the first function to "aardvark":

```
('aardvark', '', _small_3d, lambda t, d: [_number(3.14, 3, t)], 1e-2),
```

and running 

```
python test/test_torch.py -k TestTensorDeviceOpsCUDA -v
```

shows 

```
test___rshift___cuda_int16 (__main__.TestTensorDeviceOpsCUDA) ... ok
test___rshift___cuda_int32 (__main__.TestTensorDeviceOpsCUDA) ... ok
test___rshift___cuda_int64 (__main__.TestTensorDeviceOpsCUDA) ... ok
test___rshift___cuda_int8 (__main__.TestTensorDeviceOpsCUDA) ... ok
test_aardvark_cuda_float16 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_float32 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_float64 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_int16 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_int32 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_int64 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_int8 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_cuda_uint8 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_float16 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_float32 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_float64 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_int16 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_int32 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_int64 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_int8 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_aardvark_inplace_cuda_uint8 (__main__.TestTensorDeviceOpsCUDA) ... ERROR
test_abs_cuda_bfloat16 (__main__.TestTensorDeviceOpsCUDA) ... ok
test_abs_cuda_float16 (__main__.TestTensorDeviceOpsCUDA) ... ok
test_abs_cuda_float32 (__main__.TestTensorDeviceOpsCUDA) ... ok
```

These tests are probably just confusing because most of them only run on CUDA and there's not a direction connection between the list and the test names?

**Comment by zou3519** [comment]
Oh, I see. The tests I was looking at only run on CUDA -- locally I tested on a CPU build and the CI build I pulled was from a CPU-only build

It wasn't clear to me that the tests in the table only run on CUDA, but that's my fault. Thanks for clearing it up, @mruberry, I'm closing this issue.

PS: As a testing ask, it would be nice if we made it easier to discover where or how a test gets generated

**Comment by mruberry** [comment]
I don't think it's your fault, @zou3519, I think it's confusing and we should consider this a point of feedback for how to improve the test suite's readability.

>  PS: As a testing ask, it would be nice if we made it easier to discover where or how a test gets generated

Exactly, I think this is the correct takeaway.
