### ISSUE TITLE
Adding flexibility to Trainer

### ISSUE THREAD

**Issue by keon** [pytorch/pytorch#4709]
Current implementation of [`Trainer`](https://github.com/pytorch/pytorch/blob/master/torch/utils/trainer/trainer.py) does not allow for custom implementation of `closure` function which is passed to the optimizer.

Custom implementation of closure would be great since it could change according to the model.

What do you think about allowing a parameter (something like `get_closure`) that returns a closure?

the implementation will be like:

```python
class Trainer(object):
  def __init__(self):
    self.val = 5

  def train(self, get_closure=None):
    closure = get_closure(self)
    optimizer(closure)

def optimizer(closure):
  print("executing optimizer!")
  closure()

def get_custom_closure(trainer):
  def custom_closure():
    print("executing custom closure", trainer.val)
  return custom_closure

a = Trainer()
a.train(get_custom_closure)
```

```
executing optimizer!
executing custom closure 5
```

Please let me know if you guys have any better ideas.

**Comment by soumith** [comment]
we are planning to deprecate / remove Trainer from pytorch/pytorch.
For more powerful trainer that's well-maintained, see https://github.com/pytorch/ignite
