### ISSUE TITLE
torch.sparse.FloatTensor implementation requests

### ISSUE THREAD

**Issue by alexholdenmiller** [pytorch/pytorch#4710]
Hi there,

I'd have a use for a few functions that currently `raise NotImplementedError` or `AttributeError` for (CPU) sparse tensors.

Specifically, I'm trying to build a TFIDF matrix, so my sparse tensor is basically `tokens` by `documents`. I'd like to be able to retrieve the total number of documents each word is in, which is the sum of the number of nonzero elements in each row.
- `nonzero` (or more generally `__gt__` or `__ne__`, though I'd be calling them with `0`)
- `sum`

To get the term frequencies I'll also need the log plus 1.
- `log1p`

Thanks!

**Comment by SsnL** [comment]
Efficient workarounds:
```
# returns nonzero indices
# note that this only works if the sparse tensor is only dense in last dimension
def nonzero(sparse_t):
  return sparse_t.coalesce()._indices()

def sum(sparse_t):
  return sparse_t._values().sum() 
  
def log1p(sparse_t):
  t = sparse_t.coalesce()
  t._values().log1p_()
  return t
```

**Comment by berzjackson** [comment]
@SsnL 
I also have requests for some methods that are not implemented yet for sparse tensors, such as `norm` and `max` and I've implemented them myself using similar workarounds. Are there any future plans for supporting these methods? I find it odd that the implementations of these standard routines are left to the users.

**Comment by SsnL** [comment]
We definitely want to support these standard methods. Unfortunately at the moment we are focusing on more urgent issues. But we will be very happy if there are contributions :)

**Comment by berzjackson** [comment]
Understood :)
Let me give it a shot then. One question though. I believe what the PyTorch team prefer here is not these workarounds but implementations that are pushed down to ATen.  Or maybe these workarounds are also acceptable as long as they are almost as efficient?

**Comment by SsnL** [comment]
@berzjackson They should be in ATen as we want C++ interface to also have these methods.

**Comment by weiyangfb** [comment]
closing this since `sum` and `log1p` are both available https://github.com/pytorch/pytorch/issues/8853
