### ISSUE TITLE
Independent Distribution Wrapper Disguises Negative StdDev in Underlying Normal Distribution

### ISSUE THREAD

**Issue by decodyng** [pytorch/pytorch#47123]
## 🐛 Bug

When you wrap a `Normal` distribution in an `Independent` wrapper to change its relative batch vs event dimensions, this leads to a situation where calling `wrapped_dist.stddev` can produce incorrect values with respect to the underlying `base_dist.stddev` when `base_dist` has been accidentally created with negative standard deviation values, since `wrapped_dist.stddev` seems to by design only ever show positive values. 

My understanding is that this happens because `Distribution`'s  default property design of standard deviation is defined with respect to the variance, and, even if you have a negative standard deviation, the square root of the square of it will still be positive. 

Obviously this is a bug that would only occur in cases where surrounding code has done something incorrect and initialized a `Normal` with invalid negative standard deviation values, but since the initialization of the `Normal` doesn't automatically set the `validate_args` flag to `True`, and thus doesn't prevent the creation of invalid `Normal`s, this wrapper-level bug can make it more difficult to debug problems. In my case, `wrapped_dist.log_prob(vec)` was returning `nans`, and when I checked my first-guess potential issues (that activations to keep stddev positive had not been applied properly), I was told the `wrapped_dist.stddev` was in fact positive, even though, upon further examination of the `base_dist`, I learned `base_dist.stddev` was partially negative, and, since that is what is used to calculate the log probability, that was indeed the cause of my errors 

## To Reproduce

```
from torch.distributions import Normal, Independent 

test_param = torch.tensor([[4.2, -8.1], [-12.4, 1.7]])
incorrect_normal = Normal(test_param, test_param)
wrapped_normal = Independent(incorrect_normal, 1)

# > incorrect_normal.stddev
# > tensor([[  4.2000,  -8.1000],
#         [-12.4000,   1.7000]])

# > wrapped_normal.stddev
# > tensor([[ 4.2000,  8.1000],
#         [12.4000,  1.7000]])
```

## Expected behavior

`wrapped_dist.stddev` returns the true standard deviation of the underlying distribution, when it has one defined a way (like being passed in by parameter) such that it can differ from the square root of the variance.    

## Environment
PyTorch version: 1.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 10.15.6 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.16)
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

cc @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by fritzo** [comment]
Hi @decodyng, I think the best we can guarantee in the `torch.distributions` library is to correctly catch errors *when validation is enabled*. I believe this error would have been caught earlier if you had called
```py
torch.distributions.Distribution.set_default_validate_args(True)
```
In fact we recently enabled validation by default in Pyro (a downstream library). If this seems useful we could consider enabling validation by default also in PyTorch. What's your opinion?

**Comment by decodyng** [comment]
@fritzo Validation by default seems like a good way to handle this, since I think the default behavior, if someone doesn't know about the validation arg, should ideally be set up in a way that explicitly raises errors like this rather than failing silently. Having a way to turn validation off does seem valuable in some circumstances, but that should probably be reserved for advanced users who do so explicitly and intentionally, rather than situations where someone keeps it on accidentally.
