### ISSUE TITLE
torch.trace type promotion behavior is different on CPU vs CUDA

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#47127]
## 🐛 Bug

torch.trace type promotion behavior is different on CPU vs CUDA.

Discovered while working on #47126.

## To Reproduce

```
>>> import torch
>>> x = torch.ones(5, 5, dtype=torch.uint8)
>>> x_cuda = x.cuda()
>>> print(x.trace().dtype)
>>> print(x_cuda.trace().dtype)
torch.uint8
torch.int64
```

## Environment
PyTorch 1.7 / master

cc @ngimel @nairbv @mruberry

**Comment by mruberry** [comment]
We would definitely take a PR fixing this.

**Comment by gchanan** [comment]
not a regression from 1.6.

**Comment by zou3519** [comment]
It's a regression from 1.5 IIRC, but FWIW no one has noticed this :)

**Comment by zou3519** [comment]
1.6.0:
```
>>> import torch
>>> torch.__version__
'1.6.0'
>>> x = torch.ones(5, 5, dtype=torch.uint8)
>>> x = x.cuda()
>>> x.trace()
tensor(5, device='cuda:0')
>>> x.trace().dtype
torch.int64
```

1.5.1:
```
>>> import torch
>>> torch.__version__
'1.5.1'
>>> x = torch.ones(5, 5, dtype=torch.uint8)
>>> x = x.cuda()
>>> x.trace()
tensor(5, device='cuda:0', dtype=torch.uint8)
```

**Comment by gchanan** [comment]
I mean it used to do the same thing but the cuda behavior is better.

**Comment by mruberry** [comment]
> I mean it used to do the same thing but the cuda behavior is better.

Just to follow-up: conceptually trace is diag -> sum, so one would expect the same type promotion as sum.
