### ISSUE TITLE
Simplify RPC Message Request/Response type check

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#47145]
As we add more and more message types, the request/response type check function needs to go through more and more comparisons. I wonder if we should organize bits to simplify it. E.g., we can have the lowest 8 bits representing the message type, and then the next 8 bits serve as flags. And have a `kIsRequestMask=0x10` mask. In this case `SCRIPT_CALL` will be `kIsRequestMask | 0`, etc. Then the `isRequest` function can simply be `return kIsRequestMask & type_;`.

https://github.com/pytorch/pytorch/blob/cb4b6336baac14173ec5659896fe3e7f06c2f5b2/torch/csrc/distributed/rpc/message.cpp#L78-L113

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
Self-assigned to reserve for onboarding

**Comment by H-Huang** [comment]
Resolved in #48143
