### ISSUE TITLE
torch.view() after torch.expand() complains about non-contiguous tensor

### ISSUE THREAD

**Issue by kitsing** [pytorch/pytorch#47146]
## 🐛 Bug

I cannot reshape an expanded tensor without allocating extra space, even though the expanded tensor uses a contiguous memory chunk

## To Reproduce

1. `torch.arange(3*4*5).reshape(3,4,5)[:, None, :, :].expand(3,10,4,5).view(30,4,5)`

`RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

## Expected behavior

A tensor of shape (30,4,5)

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-lightning==1.0.4
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.1           py38hbc911f0_0
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] pytorch                   1.7.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         1.0.4                     dev_0    <develop>
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchvision               0.8.1                py38_cu102    pytorch

**Comment by ngimel** [comment]
Runtime error thrown in this case is correct, you cannot view you expanded tensor with the sizes you want without materializing the expanded form first. `.view()` is an operation that sets logical strides to view physical memory as a tensor with specified sizes. In your case, not strides can do that.
