### ISSUE TITLE
Complex dtype and named tensors don't go along

### ISSUE THREAD

**Issue by jonasteuwen** [pytorch/pytorch#47157]
## 🚀 Feature
Support differentiation for complex-valued named tensors.

## Motivation
Complex datatypes and named tensors are an important (yet experimental) feature yey `view_as_complex` and `view_as_real` will not support differentiation of complex tensors.

**Problem:**
```
import torch
names = ["batch", "height", "width", "complex"]
z = torch.ones((5, 12, 14, 2), requires_grad=True).refine_names(*names)
z_complex = torch.view_as_complex(z.rename(None)).refine_names(*names[:-1])
```
Results in:

`RuntimeError: alias does not support automatic differentiation for outputs with complex dtype.
`

There is no hope in building such a function yourself either:
```
def view_as_complex(data):
    """Named version of `torch.view_as_complex()`"""
    data = data.clone()
    real_part = data[..., 0]
    imag_part = data[..., 1]

    return (real_part + 1j*imag_part).refine_names(*data.names[:-1])
```
gives the same error.

## Additional context
PyTorch 1.7 however introduces complex-valued spectral operators, requiring code that uses channels to represent real and imaginary parts to use `view_as_complex` and `view_as_real`. If these tensors however are named, this does not work, especially not when in 1.8 the previous fft is dropped. This is important in e.g. MRI reconstruction frameworks.

Supporting `view_as_complex` and `view_as_real` for named tensors would be useful too.

@zou3519 

cc @ezyang @anjali411 @dylanbespalko @mruberry @zou3519

**Comment by ezyang** [comment]
This seems worth fixing. I think it's just a matter of adding complex diff support for alias, which should be pretty easy.
