### ISSUE TITLE
Spurious "NumPy array is not writeable" warning on `torch.tensor(np_array)`

### ISSUE THREAD

**Issue by jpetkau** [pytorch/pytorch#47160]
## 🐛 Bug

`torch.tensor(a)`, for non-writeable numpy array a, produces this warning:

```UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor.```

But since `torch.tensor(a)` always makes a copy, the warning makes no sense. Avoiding the warning requires making a copy of the numpy array before converting to torch.

A partial workaround is to do `torch.from_numpy(a.copy())`.

## To Reproduce

```
import torch, numpy
a=numpy.arange(5.)
a.flags.writeable=False
t=torch.tensor(a)
```

## Expected behavior

The warning should only be shown when actually aliasing a read-only buffer with a mutable Tensor, not when *copying from* a read-only buffer.

## Environment

Verified on Windows, pytorch 1.5.1, git_version = '3c31d73c875d9a4a6ea8a843b9a0d1b19fbe36f3' (pip version)
And on linux at pytorch  1.8.0a0fb

## Additional context

Warning was introduced in pull 33615. #44027 (read-only tensors) would make this irrelevant.

This warning is important for `from_numpy`, because you can easily accidentally do things like create a mutable view onto a Python `str` or `bytes` object and overwrite it. Having the warning also give trivial false alarms like this can cause real problems to be overlooked.

Probably related: `torch.tensor(nparray, pin_memory=True)` doesn't work, probably for similar reasons: it tries to construct a temporary view before making the copy. If you want the torch tensor in pinned memory, there appears to be no way to avoid the warning without introducing a spurious copy.

cc @mruberry @rgommers @heitorschueroff

**Comment by ngimel** [comment]
Thank you for your bug report, warning is indeed spurious in this case.

**Comment by ArtistBanda** [comment]
Should I create a PR which removes the warning from ../torch/csrc/utils/tensor_numpy.cpp:135 ?
![clip](https://user-images.githubusercontent.com/36930204/97855253-8146ec80-1d20-11eb-84cf-86accd24da8b.png)

**Comment by ArtistBanda** [comment]
Hello! I am new to open source development and would like to help to resolve this issue. It would help a lot with a bit of guidance here.

**Comment by mruberry** [comment]
You probably want to suppress the warning from here:

https://github.com/pytorch/pytorch/blob/8d5256e6ddb080cc651e0b2aae21b3371a7f7e81/torch/csrc/utils/tensor_new.cpp#L273

when `copy_numpy` is true. Then add tests for the callsites to verify the behavior is correct.

**Comment by ArtistBanda** [comment]
Sure, I'll try to do that.

**Comment by desaixie** [comment]
Can I ignore this warning if it is coming from `torch.from_numpy(batch).to('cuda')`, where `batch` is a slice of a numpy ndarray and therefore not writeable? I guess it shouldn't matter since `to('cuda')` is making a copy, but I want to make sure.

**Comment by mruberry** [comment]
> Can I ignore this warning if it is coming from `torch.from_numpy(batch).to('cuda')`, where `batch` is a slice of a numpy ndarray and therefore not writeable? I guess it shouldn't matter since `to('cuda')` is making a copy, but I want to make sure.

Yes, I think you can ignore it
