### ISSUE TITLE
[ONNX]RuntimeError: Unexpected node type: onnx::Cast

### ISSUE THREAD

**Issue by oneway234** [pytorch/pytorch#47182]
❓convert faild

```
class Decoder(nn.Module):
    def __init__(self, N, L):
        super(Decoder, self).__init__()
        # Hyper-parameter
        self.N, self.L = N, L
        # Components
        self.basis_signals = nn.Linear(N, L, bias=False)

    def forward(self, mixture_w, est_mask):
        """
        Args:
            mixture_w: [M, N, K]
            est_mask: [M, C, N, K]
        Returns:
            est_source: [M, C, T]
        """
        # D = W * M
        source_w = torch.unsqueeze(mixture_w, 1) * est_mask  # [M, C, N, K]
        source_w = torch.transpose(source_w, 2, 3)  # [M, C, K, N]
        # S = DV
        est_source = self.basis_signals(source_w)  # [M, C, K, L]
        est_source = overlap_and_add(est_source, self.L // 2)  # M x C x T
        return est_source
```
This is the model which I converted. It has two inputs, and it's a Linear NN. As I know onnx.export support mutiple inputs.
So I convert it with the following code:
```
model = ConvTasNet.load_model(args.model_path)
model.eval()
Decoder = model.decoder

torch.onnx.export(Decoder, (separator_input, decoder_input),
                                                 decoder_path,
                                                 export_params=True )
```
But I got this error.

> RuntimeError: Unexpected node type: onnx::Cast

**Further information**
Pytorch 1.7

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by mruberry** [comment]
Thanks for reporting this issue, @oneway234.

**Comment by spandantiwari** [comment]
@KsenijaS - can you please take a look at this issue? Thanks.

**Comment by KsenijaS** [comment]
@oneway234 can you please share the full script that you used to convert the model.
I don't have the information about ConvTasNet model, and of inputs separator_input, decoder_input.
Thanks.

**Comment by KsenijaS** [comment]
@oneway234 Can you please send a full script so we can reproduce the issue. Thanks!

**Comment by oneway234** [comment]
hi, 
Thanks for reply!

This is my [project](https://github.com/oneway234/torch_to_onnx).

The main problem is the function "[overlap and add](https://github.com/oneway234/torch_to_onnx/blob/d2ab90f06ff090923bb1cc4e7d3abc3f0de9208e/signal_processors/utils.py#L9)" which is used in module decoder.

I removed this function and converted it again. It worked!

Obviously the convertor can not convert this function.

**Comment by KsenijaS** [comment]
@oneway234 Can you point me to which script I should run in your project? I ran demo_tasknet.py and I don't get any exception. 
I also tried to run test/only_coder.py but it's reporting missing checkpoint file.

**Comment by oneway234** [comment]
@KsenijaS 
I deactivated the onnx function, and now I activate it. [here ](https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/test/separate_tasnet.py#L49)

Please pull the project again. and run demo_tasknet.py again.

It will report the error "RuntimeError: Unexpected node type: onnx::Cast".

The function [overlap add](https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/signal_processors/utils.py#L9) causes this error.

So if you try to commet out this part in model([here](https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/models/conv_tasnet.py#L141)), it can be transfer into nnx sucessfully.

**Comment by KsenijaS** [comment]
@oneway234 I was able to reproduce the Runtime error, on my side running the script takes around 1 hour.
I will be working on it to fix it.

**Comment by oneway234** [comment]
Thank you for reply!

Yes! it took a long time to report this error.

And I am sure that is the function [overlap add](https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/signal_processors/utils.py#L9) causes this error.

**Comment by KsenijaS** [comment]
@oneway234 I have identified that this for loop is causing the error in the overlap_add function : https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/signal_processors/utils.py#L48
I will work on fixing it

**Comment by KsenijaS** [comment]
@oneway234  can you try replacing the line: https://github.com/oneway234/torch_to_onnx/blob/f781fbdd8a52359ddc549c1ecbb3f18169441f8c/signal_processors/utils.py#L39
```
frame = torch.arange(0, output_subframes).unfold(0, subframes_per_frame, subframe_step)
```
with
```
frame = torch.arange(0, output_subframes).unfold(0, 2, 1)
```
This is only a workaround to unblock you while I'm working on fixing this permanently.

**Comment by oneway234** [comment]
@KsenijaS 
Thanks! I will replace it to unblock.

And, it's glad to know that the issue will be fix in future!

**Comment by spandantiwari** [comment]
@KsenijaS - is this the PR that addresses the unfold issue?
https://github.com/pytorch/pytorch/pull/49378

**Comment by KsenijaS** [comment]
@spandantiwari  Yes that is the PR.
@oneway234 it needs to be exported with opset_version 12

**Comment by spandantiwari** [comment]
This issue should be fixed with https://github.com/pytorch/pytorch/pull/49378 PR. @oneway234 could you please confirm and reopen this issue if the problem persists.

**Comment by KsenijaS** [comment]
@oneway234 can you please change the lines in file test/separate_tasnet.py into:
```
            torch.onnx._export(model, mixture,
                              "conv_tasnet.onnx",
                              export_params=True,
                              opset_version=12, verbose=False,
                              do_constant_folding=True, onnx_shape_inference=False
                              )
''' 

and also there is a bug in #49378, can you please wait for https://github.com/pytorch/pytorch/pull/50504 to be merged or apply the changes yourself.

Thanks!

**Comment by oneway234** [comment]
@KsenijaS  Sure! Thanks for reply.
