### ISSUE TITLE
Incorrect mul_() result with expanded tensor

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#4718]
Pytorch version: 0.4.0a0+188ee3f 188ee3ff0baf439453c5dd63e1a053ba03b472ad 
```python
a_ = torch.randn(2, 1, 2)
b = torch.randn(4,2)
a = a_.expand(2, 4, 2)
a.mul(b)
a.mul_(b)
```

Result
```python
>>> a_ = torch.randn(2, 1, 2)
>>> b = torch.randn(4,2)
>>> a = a_.expand(2, 4, 2)
>>> a.mul(b)

(0 ,.,.) = 
  0.7724 -2.6582
 -0.7434  0.4124
  0.5030  0.0272
  2.0166  1.0523

(1 ,.,.) = 
  0.1222  1.5042
 -0.1176 -0.2334
  0.0796 -0.0154
  0.3191 -0.5955
[torch.FloatTensor of size 2x4x2]

>>> a.mul_(b)

(0 ,.,.) = 
  0.2917  0.0163
  0.2917  0.0163
  0.2917  0.0163
  0.2917  0.0163

(1 ,.,.) = 
  0.0462 -0.0092
  0.0462 -0.0092
  0.0462 -0.0092
  0.0462 -0.0092
[torch.FloatTensor of size 2x4x2]


```

I expected the result of mul_() to be same with that of mul(). I think it's a bug.
Thanks.

EDIT: I found it only expand() is required to trigger the bug at the minimum

**Comment by ezyang** [comment]
This is a known infelicity with inplace operations with broadcasted tensors. See #4664 and #957.

**Comment by qbx2** [comment]
Some message that tells "Don't do in-place on expanded tensors." should be added to docs.
