### ISSUE TITLE
torch.cumsum in-place

### ISSUE THREAD

**Issue by rossimattia** [pytorch/pytorch#47193]
## 🚀 Feature
It would be nice to have the in-place version of `torch.cumsum`.

## Motivation
Although it is possible to achieve the same result by specifying the input tensor at the `out` parameter, without checking the implementation the user cannot know a priori whether this workaround could cause some issue.

## Additional context
https://discuss.pytorch.org/t/why-there-is-no-in-place-version-of-torch-cumsum/43364

**Comment by mruberry** [comment]
Thank you for the suggestion, @rossimattia. I think we would accept a PR implementing this.
