### ISSUE TITLE
Loading pytorch model without a code

### ISSUE THREAD

**Issue by Scitator** [pytorch/pytorch#4719]
recently I ask the same question at pytorch forum - https://discuss.pytorch.org/t/loading-pytorch-model-without-a-code/12469

Just interesting for me, if somebody here knows how to solve this problem? If necessary, I can PR.

**Comment by soumith** [comment]
I've answered in detail with technical issues at https://discuss.pytorch.org/t/loading-pytorch-model-without-a-code/12469/2

Since this is not easily solvable, I am closing the issue with a `wontfix` tag.
