### ISSUE TITLE
Pytorch mobile with model from fast.ai

### ISSUE THREAD

**Issue by thilowrona** [pytorch/pytorch#47199]
### Please note that this issue tracker is not a help form and this issue will be closed.

Hello,
I am trying to use my own model with pytorch mobile on android, but the app is crashing without an error. I am following this
[tutorial](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson1-pets.ipynb) to train a model and then save it using pytorch `torch.save(learn.model.state_dict(), 'model.pt')`. When I use this file to replace the model.pt file in the assests folder, the app stops runing. Any help would be much appreciated

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mruberry** [comment]
This question is more appropriate for the PyTorch forums or the fast.ai forums. Please ask there.
