### ISSUE TITLE
CHECK function in nccl.h is not declared

### ISSUE THREAD

**Issue by willyd** [pytorch/pytorch#4720]
While trying to build master on Ubuntu 16.04 with CUDA 9.0 and nccl I get the following error:

```
error: 'CHECK' was not declared in this scope
         CHECK(ncclGroupStart());
```

Looking at the source code I believe that the body of the `AutoNcclGroup` ctor and dtor should be moved to nccl.cpp or the CHECK function should be declared in nccl.h.

See https://github.com/pytorch/pytorch/blob/master/torch/csrc/cuda/nccl.h#L14-L22 and
https://github.com/pytorch/pytorch/blob/master/torch/csrc/cuda/nccl.cpp#L18

Could you fix this please?

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/4721

**Comment by willyd** [comment]
Thanks!
