### ISSUE TITLE
RuntimeError: invalid multinomial distribution (encountering probability entry < 0)

### ISSUE THREAD

**Issue by JoeRakhimov** [pytorch/pytorch#47232]
## 🐛 Bug

I am trying to train an agent using [Stable Baselines 3](https://github.com/DLR-RM/stable-baselines3) library to play [Connect 4](https://www.kaggle.com/joerakhimov/connectx-11) game. As I understood Stable Baselines 3 uses Pytorch.

When I am trying to train, I am facing this error:

> /opt/conda/lib/python3.7/site-packages/torch/distributions/categorical.py in sample(self, sample_shape)
>     104             sample_shape = torch.Size(sample_shape)
>     105         probs_2d = self.probs.reshape(-1, self._num_events)
> --> 106         samples_2d = torch.multinomial(probs_2d, sample_shape.numel(), True).T
>     107         return samples_2d.reshape(self._extended_shape(sample_shape))
>     108 
> 
> RuntimeError: invalid multinomial distribution (encountering probability entry < 0)

## To Reproduce

1. Open the [notebook](https://www.kaggle.com/joerakhimov/connectx-11) in Kaggle
2. Click "Copy and Edit" button 
3. Try to run the notebook

## Expected behavior

I expect to train an agent without this error but I do not know how to solve it.

## Environment

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by mruberry** [comment]
I'm not sure this is actually an error in PyTorch. Does the input to the multinomial actually contain a value less than zero?

**Comment by JoeRakhimov** [comment]
When this error happens, probs_2d equals to `tensor([[nan, nan, nan, nan, nan, nan, nan]])`

**Comment by fritzo** [comment]
`torch.Categorical` does not accept NAN input. You'll need to fix the code used to generate `probs_2d`.
