### ISSUE TITLE
Exception using optimize_for_mobile on retinanet from torchvision

### ISSUE THREAD

**Issue by ValerianGonnot** [pytorch/pytorch#47269]
## 🐛 Bug

When using torch.utils.mobile_optimizer.optimize_for_mobile, I get the following exception : 

```
line 43, in optimize_for_mobile
 > optimized_cpp_module = torch._C._jit_pass_optimize_for_mobile(script_module._c, optimization_blocklist, preserved_methods)

RuntimeError: node->kind() == prim::GetAttr INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/jit/passes/freeze_module.cpp":22, please report a bug to PyTorch. Expected prim::GetAttr nodes
```

## To Reproduce

```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torchvision.models.detection.retinanet_resnet50_fpn(pretrained=True)
model.eval()

traced_script_module = torch.jit.script(model)
traced_script_module_optimized = optimize_for_mobile(traced_script_module)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.6
 - CUDA/cuDNN version: CUDA 11, 
 - GPU models and configuration: GTX 1070
 - Any other relevant information:

**Comment by ForeverRuri** [comment]
Hello, i met up with the same problem

I drop the `optimize_for_mobile ` and to `torch.jit.save` directly

**Comment by ValerianGonnot** [comment]
Yeah, thanks for the tip. 

Unfortunately, this can only be a temporary fix as it badly hurts the mobile app performance.

After further investigations, I can tell that the problem comes from MobileOptimizerType.INSERT_FOLD_PREPACK_OPS and                                                                  MobileOptimizerType.HOIST_CONV_PACKED_PARAMS as I can run the optimize_for_mobile function when I put them in the blocklist. Unfortunately, those are the optimizers that give the biggest perf gain.

Any hint on where to search for the problem would be welcome.

**Comment by ValerianGonnot** [comment]
After further investigations, the problem comes from the combination of torchvision.models.detection.anchor_utils.AnchorGenerator and the optimize_for_mobile from pytorch

**Comment by eellison** [comment]
Fixed on master with: https://github.com/pytorch/pytorch/pull/46285

**Comment by ValerianGonnot** [comment]
Yes indeed, thank you

**Comment by eellison** [comment]
Just curious - what was the performance difference % you observed when not using optimize for mobile ?

**Comment by ValerianGonnot** [comment]
I got a 33% fps gain with optimize_for_mobile
