### ISSUE TITLE
Question about build torch.whl package

### ISSUE THREAD

**Issue by FantasyJXF** [pytorch/pytorch#47268]
# Question: self build torch-xxx.whl size much smaller than the [oficial file](https://download.pytorch.org/whl/torch_stable.html).

Since the latest `pytorch` packakge(after v1.4.0) no longer support CUDA 10.0, but my computers are equipmented with  CUDA 10.0, so I build the `torch-1.6.0a0+b31f58d-cp36-cp36m-linux_x86_64.whl` followed the `README` [installation guide](https://github.com/pytorch/pytorch#installation) with `conda`.

My wheel file is about `170M`, but yours is about `700M`, I wonder whether I missed some important requirements and my `pytorch` would be lack of functions.

I use this command to build the wheel file:
```
python setup.py bdist_wheel
```

My enviroments are as follows:
```
--
-- ******** Summary ********
-- General:
--   CMake version         : 3.18.2
--   CMake command         : /home/work/anaconda3/envs/pytorch/bin/cmake
--   System                : Linux
--   C++ compiler          : /usr/local/bin/c++
--   C++ compiler id       : GNU
--   C++ compiler version  : 5.4.0
--   BLAS                  : MKL
--   CXX flags             :  -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format
--   Build type            : Release
--   Compile definitions   : TH_BLAS_MKL;ONNX_ML=1;ONNXIFI_ENABLE_EXT=1;ONNX_NAMESPACE=onnx_torch;MAGMA_V2;IDEEP_USE_MKL;HAVE_MMAP=1;_FILE_OFFSET_BITS=64;HAVE_SHM_OPEN=1;HAVE_SHM_UNLINK=1;HAVE_MALLOC_USABLE_SIZE=1;USE_EXTERNAL_MZCRC;MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS
--   CMAKE_PREFIX_PATH     : /home/work/anaconda3/envs/pytorch;/usr/local/cuda-10.0
--   CMAKE_INSTALL_PREFIX  : /home/work/JXF/pytorch/torch
--
--   TORCH_VERSION         : 1.6.0
--   CAFFE2_VERSION        : 1.6.0
--   BUILD_CAFFE2_MOBILE   : OFF
--   USE_STATIC_DISPATCH   : OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : True
--     Python version      : 3.6.8
--     Python executable   : /home/work/anaconda3/envs/pytorch/bin/python
--     Pythonlibs version  : 3.6.8
--     Python library      : /home/work/anaconda3/envs/pytorch/lib/libpython3.6m.so.1.0
--     Python includes     : /home/work/anaconda3/envs/pytorch/include/python3.6m
--     Python site-packages: lib/python3.6/site-packages
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : True
--   BUILD_JNI             : OFF
--   INTERN_BUILD_MOBILE   :
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 10.0
--     cuDNN version       : 7.5.0
--     CUDA root directory : /usr/local/cuda-10.0
--     CUDA library        : /usr/local/cuda-10.0/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda-10.0/lib64/libcudart.so
--     cublas library      : /usr/local/cuda-10.0/lib64/libcublas.so
--     cufft library       : /usr/local/cuda-10.0/lib64/libcufft.so
--     curand library      : /usr/local/cuda-10.0/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda-10.0/lib64/libcudnn.so
--     nvrtc               : /usr/local/cuda-10.0/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda-10.0/include
--     NVCC executable     : /usr/local/cuda-10.0/bin/nvcc
--     NVCC flags          : -DONNX_NAMESPACE=onnx_torch;-gencode;arch=compute_70,code=sm_70;-Xcudafe;--diag_suppress=cc_clobber_ignored;-Xcudafe;--diag_suppress=integer_sign_change;-Xcudafe;--diag_suppress=useless_using_declaration;-Xcudafe;--diag_suppress=set_but_not_used;-Xcudafe;--diag_suppress=field_without_dll_interface;-Xcudafe;--diag_suppress=base_class_has_different_dll_interface;-Xcudafe;--diag_suppress=dll_interface_conflict_none_assumed;-Xcudafe;--diag_suppress=dll_interface_conflict_dllexport_assumed;-Xcudafe;--diag_suppress=implicit_return_from_non_void_function;-Xcudafe;--diag_suppress=unsigned_compare_with_zero;-Xcudafe;--diag_suppress=declared_but_not_referenced;-Xcudafe;--diag_suppress=bad_friend_decl;-std=c++14;-Xcompiler;-fPIC;--expt-relaxed-constexpr;--expt-extended-lambda;-Wno-deprecated-gpu-targets;--expt-extended-lambda;-gencode;arch=compute_70,code=sm_70;-Xcompiler;-fPIC;-DCUDA_HAS_FP16=1;-D__CUDA_NO_HALF_OPERATORS__;-D__CUDA_NO_HALF_CONVERSIONS__;-D__CUDA_NO_HALF2_OPERATORS__
--     CUDA host compiler  : /usr/local/bin/gcc
--     NVCC --device-c     : OFF
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    :
--   USE_FBGEMM            : ON
--     USE_FAKELOWP          : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_MKL               : ON
--   USE_MKLDNN            : ON
--   USE_MKLDNN_CBLAS      : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : ON
--   USE_TBB               : OFF
--   USE_VULKAN            : OFF
--   USE_PROF              : OFF
--   USE_QNNPACK           : ON
--   USE_PYTORCH_QNNPACK   : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : ON
--     USE_MPI             : OFF
--     USE_GLOO            : ON
--     USE_TENSORPIPE      : ON
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : pthreadpool;cpuinfo;qnnpack;pytorch_qnnpack;nnpack;XNNPACK;fbgemm;fp16;gloo;tensorpipe;aten_op_header_gen;foxi_loader;rt;fmt::fmt-header-only;gcc_s;gcc;dl
-- Configuring done
```

What's your building config?

cc @malfet @seemethere @walterddr

**Comment by FantasyJXF** [comment]
Another question is that:
```
Tesla T4 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_70.
```

Since I build the `torch-1.6.0a0+b31f58d-cp36-cp36m-linux_x86_64.whl` on my Tesla V100 with CUDA 10.0 computer, then I install the `wheel` file on my another Tesla T4 with CUDA 10.0 computer, and I met the `Warning` like this.

How could I get rid of the warning and would it slow down or have effects on T4 machine?

Looking forward to your reply, thanks.

**Comment by FantasyJXF** [comment]
I noticed that the pytorch the official released supports multiple NVCC architectures:
```
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

The pytorch I build only support its own archtecture:
```
PyTorch 1.6.0a0+b31f58d
PyTorch compiling details PyTorch built with:
  - GCC 5.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.0 Product Build 20180829 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_70,code=sm_70
  - CuDNN 7.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

Maybe that's the reason?

**Comment by ptrblck** [comment]
Your T4 uses the compute capability 7.5, while you were building PyTorch for 7.0 without PTX, which thus fails.
Set the GPU architecture to 7.5, rebuild the package, and it should work.

That being said, note that the PyTorch conda binaries and pip wheels ship with their own CUDA (cudnn, NCCL, etc.) runtime(s) and you local CUDA installation will not be used for internal PyTorch operations.
You would need your local CUDA toolkit, if you want to build custom CUDA extensions or compile a 3rd party package.

Cross-post from [here](https://discuss.pytorch.org/t/build-pytorch-gpu-for-different-gpu-archs/101562).

**Comment by ejguan** [comment]
Feel free to re-open it if you have further questions.

**Comment by malfet** [comment]
@FantasyJXF in official builds all CUDA libraries are statically linked into the wheel, but by default they are considered an external runtime dependency. (I.e. official package launched on platform without CUDA runtime/libraries would still work as CPU only binary, which yours will fail to load)

And one can override GPU architecture detection by setting `TORCH_CUDA_ARCH_LIST` environment variable before calling setup.py:
https://github.com/pytorch/pytorch/blob/7ab843e78bf51c0c3d24693d677cbfd56dc4f364/setup.py#L93-L97

**Comment by FantasyJXF** [comment]
## About GPU architecture

> Your T4 uses the compute capability 7.5, while you were building PyTorch for 7.0 without PTX, which thus fails.
> Set the GPU architecture to 7.5, rebuild the package, and it should work.

According to this [issue](https://github.com/pytorch/pytorch/issues/32277), I use all the `TORCH_CUDA_ARCH_LIST ` to build my

> Your T4 uses the compute capability 7.5, while you were building PyTorch for 7.0 without PTX, which thus fails.
> Set the GPU architecture to 7.5, rebuild the package, and it should work.

I rebuild the pytorch wheel with `TORCH_CUDA_ARCH_LIST="3.7;5.0;6.0;6.1;7.0;7.5"`, and the new pytorch didn't show warning message on my T4 machine.

Here I have a question about `PTX`, should I use `TORCH_CUDA_ARCH_LIST="3.7;5.0;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX"` to build my wheel file, what's the difference?

## About package size
While I add many gpu archs, the new wheel file is more than 500M, I suppose thats because there are many other cuda libraries in the new wheel file?

## Anaconda and pip

> That being said, note that the PyTorch conda binaries and pip wheels ship with their own CUDA (cudnn, NCCL, etc.) runtime(s) and you local CUDA installation will not be used for internal PyTorch operations.
> You would need your local CUDA toolkit, if you want to build custom CUDA extensions or compile a 3rd party package.

In my case, I build the wheel file in conda environment, but I install the package without conda(no such operation: `conda install -c pytorch magma-cuda100`), would there be hidden trouble?

@malfet @ptrblck Thanks for your reply

**Comment by FantasyJXF** [comment]
Build `torch v1.7.0` with the same way, met the error like this:
```
aten_interned_strings.h:612:9: error: expected unqualified-id before ‘sizeof’
```

Any help?

**Comment by FantasyJXF** [comment]
> Feel free to re-open it if you have further questions.

re-open  re-open  re-open

**Comment by FantasyJXF** [comment]
`gcc-7.4.0` works Okay, `gcc-5.4.0` and `gcc-8.4.0` failed to build.

**Comment by liuhoward** [comment]
I have an additional question about dockerfile:

1. Since pytorch pip installation has built-in cuda runtimes, can I just use pure ubuntu (without cuda, cudnn) as base, and pip install torch1.8.1+cu102? It seems pytorch docker images (at hub.docker.com) use ubuntu_cudnn_runtime/devel as base, that's why they are very large.
2.  Or, can I use ubuntu_cudnn_runtime as base, but pip install torch1.8.1+cpu? Will it support GPU?

**Comment by malfet** [comment]
> 1. Since pytorch pip installation has built-in cuda runtimes, can I just use pure ubuntu (without cuda, cudnn) as base, and pip install torch1.8.1+cu102? It seems pytorch docker images (at hub.docker.com) use ubuntu_cudnn_runtime/devel as base, that's why they are very large.

Yes, you can, but you still need to have NVIDIA driver installed.
> 2. Or, can I use ubuntu_cudnn_runtime as base, but pip install torch1.8.1+cpu? Will it support GPU?

No, +cpu wheels do not have any GPU acceleration capabilities.

**Comment by darkgod1kandarp** [comment]
Is there some way that I can built pytorch library same as present on  official website ?
