### ISSUE TITLE
Add TF32 Information to Reproducibility Page

### ISSUE THREAD

**Issue by n2cholas** [pytorch/pytorch#47287]
## 📚 Documentation

PyTorch 1.7 enabled TensorFloat32 computation by default, which may affect the reproducibility of results across hardware. I believe this should be mentioned in the [reproducibility documentation](https://pytorch.org/docs/stable/notes/randomness.html) (so people are aware they should disable it if they want their results to be more consistent across multiple devices):

cc @ngimel @jlin27 @mruberry @zasdfgbnm

**Comment by mruberry** [comment]
This seems reasonable and we would accept a PR addressing this.

**Comment by zasdfgbnm** [comment]
Hmm, even if you are running on two devices that do not support TF32, are they guaranteed to have the same result? cuDNN and cuBLAS could pick different algo on different devices.

**Comment by n2cholas** [comment]
@zasdfgbnm good point, but I would expect 13 fewer mantissa bits would have more of an impact than different algos, but please correct me if I'm wrong, I'm not too familiar with this area. I still think it's worth mentioning on this page, just so people are aware.

**Comment by n2cholas** [comment]
Like @mruberry pointed out, documenting this specifically gives users the impression that disabling TF32 guarantees identical results across hardware, even though it definitely doesn't. Furthermore, the line `Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or different platforms. Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical seeds.` covers hardware changes like TF32 computation. So, I'll close this issue.
