### ISSUE TITLE
torch.argmax Inconsistent with torch.max(): Returns index of last occurence of maximum value instead of the first.

### ISSUE THREAD

**Issue by lebrice** [pytorch/pytorch#47296]
## 🐛 Bug
The result of `torch.argmax` should always be the first index of the maximum value in the case where that value appears multiple times, as is done in numpy, and as is described in the docs.
Furthermore, the result should be equivalent to that of `torch.max().indices`.

## To Reproduce

```
>>> import torch
>>> a = torch.zeros(5)
>>> a[3:] = 1
>>> a
tensor([0., 0., 0., 1., 1.])
>>> a.argmax()
tensor(4)
>>> a.max(dim=-1).indices
tensor(3)
>>> a.argmax(-1)
tensor(4)
>>> a.max(0).indices
tensor(3)
```

## Expected behavior

a.max(-1).indices == a.argmax(-1), always, as described in the docs.

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 450.80.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] numpydoc==0.9.1
[pip3] torch==1.4.0
[pip3] torchmeta==1.2.2
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch                   1.0.1           cuda100py37he554f03_0  
[conda] pytorch-lightning         1.0.2                    pypi_0    pypi
[conda] pytorch-lightning-bolts   0.2.5                    pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

Also, a small note, the doc for torch.argmax has a copy-pasted portion from argmin:

> If there are multiple minimal values then the indices of the first *minimal* value are returned.

**Comment by ptrblck** [comment]
Could you update PyTorch to `1.7.0`, as this issue should have been solved in this PR: https://github.com/pytorch/pytorch/pull/42004

and I also cannot reproduce the outputs you are seeing in `1.7.0`.

**Comment by kshitij12345** [comment]
Looks fine on master as well.
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+73e121d'
>>> a = torch.zeros(5)
>>> a[3:] = 1
>>> a.argmax()
tensor(3)
>>> a.max(dim=-1).indices
tensor(3)
>>> a.argmax(-1)
tensor(3)
>>> a.max(0).indices
tensor(3)
>>> 
```

**Comment by kshitij12345** [comment]
> Also, a small note, the doc for torch.argmax has a copy-pasted portion from argmin:
> >If there are multiple minimal values then the indices of the first minimal value are returned.

Great catch. @lebrice Would you be interested in sending PR fixing the same?

**Comment by lebrice** [comment]
Hey all, my mistake, I forgot I wasn't running the most recent version of pytorch, and I didn't search through the solved issues for this, only the open ones.
I'll make a small PR for fixing this doc typo soon. Thanks!
