### ISSUE TITLE
Potential SEGFAULT from code pattern: tensor.contiguous().data_ptr<>

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#47298]
## 🐛 Bug

Recently, a code regression was introduced that was causing segfault (see https://github.com/pytorch/pytorch/issues/47054#issuecomment-720729819) [ps: I'm to blame]. The problem was caused by the code pattern: `auto ptr = tensor.contiguous().data_ptr<>` which, if the tensor is discontiguous creates a new tensor which is then destroyed and so `ptr` becomes a dangling pointer.

A quick grep through the code shows some other uses of this pattern as follows:

```
./aten/src/ATen/native/xnnpack/Linear.cpp:95:          bias->contiguous().data_ptr<float>() :
./aten/src/ATen/native/xnnpack/Convolution.cpp:231:          ? bias->contiguous().data_ptr<float>()
./aten/src/ATen/native/xnnpack/Convolution.cpp:259:          ? bias->contiguous().data_ptr<float>()
./aten/src/ATen/native/vulkan/ops/Copy.cpp:38:          src.contiguous().data_ptr<float>(),
./aten/src/ATen/native/quantized/QTensor.cpp:286:  const float* input = input_tensor.contiguous().data_ptr<float>();
./aten/src/ATen/native/quantized/cpu/q_avgpool.cpp:45:      auto input_data = input.contiguous().data_ptr<scalar_t>();
./aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp:198:  float* weight_contig_ptr = weight.contiguous().data_ptr<float>();
```

These should be fixed (the result from contiguous() saved into a variable before calling data_ptr<>) and tests should be added/verified for correctly testing for discontiguous cases.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by dzhulgakov** [comment]
You can also try to extend linter to catch these patterns proactively

**Comment by jerryzh168** [comment]
I think this is fixed now. Hi @dzhulgakov do you know who we can contact about supporting this in linter?

**Comment by jerryzh168** [comment]
closing for now this the issues is fixed
