### ISSUE TITLE
Autograd IndexCopy is broken

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#473]
This happens when the index tensor contains duplicate elements. If this is not allowed index_copy_ should raise an exception when this happens and we should fix the test. Otherwise we need to fix the autograd op.

Here's an example:

```python
import torch
from torch.autograd import *
x = Variable(torch.zeros(5, 5), requires_grad=True)
print(x)
y = Variable(torch.range(1, 25).view(5, 5), requires_grad=True)
print(y)
idx = Variable(torch.LongTensor([0, 0, 0, 0, 0]))
z = x.index_copy(0, idx, y)
print(z)  # Note only the last row of y is copied to the first row of z. No other rows of y are used.
z.backward(torch.ones(5, 5))
print(y.grad)  # Incorrectly all ones. Only the last row of y.grad should be non-zero.
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @SsnL

**Comment by gchanan** [comment]
I ran into this in https://github.com/pytorch/pytorch/pull/1884 and fixed the test for now.  I'm not sure how to interpret  @apaszke's last comment: did you mean UB behavior is "unreasonable" rather than "a reasonable"?  The last sentence reads that way.

**Comment by apaszke** [comment]
I'd be ok with saying that it's UB in such case. There's no natural choice, and it can decrease performance.

**Comment by KushajveerSingh** [comment]
@apaszke Is this issue still worth working on? If adding the additional check can decrease performance, can we add another argument specifying that indexes contain duplicate elements?
