### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_PYBIND11_COMPILER_TYPE'

### ISSUE THREAD

**Issue by wwdok** [pytorch/pytorch#47333]
## ❓ Questions and Help

I am installing [Alphapose](https://github.com/MVIG-SJTU/AlphaPose) on Windows 10, after soveling several errors, it comes to `AttributeError: module 'torch._C' has no attribute '_PYBIND11_COMPILER_TYPE'` when i run `python setup.py build develop`
![image](https://user-images.githubusercontent.com/43233772/98062408-f0d7eb80-1e88-11eb-876e-4bc5d008c02d.png)
below is my environment info:
![image](https://img-blog.csdnimg.cn/20201103175929410.png)
​​Could anyone give me a tip to solve it ?

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
cc @malfet Since it is related to https://github.com/pytorch/pytorch/pull/46415

**Comment by peterjc123** [comment]
BTW, could you please run the following commands to ensure you have the latest submodule.
```
git submodule sync
git submodule update --init --recursive
```

**Comment by malfet** [comment]
@wwdok can you please run `python -m torch.utils.collect_env` and share its output here?

And can you explain how did you install PyTorch, as `torch.utils.cpp_exensions` from pytorch-1.7.0 does not contain any references to _PYBIND11_COMPILER_TYPE, see https://github.com/pytorch/pytorch/blob/release/1.7/torch/utils/cpp_extension.py

**Comment by peterjc123** [comment]
> @wwdok can you please run `python -m torch.utils.collect_env` and share its output here?
> 
> And can you explain how did you install PyTorch, as `torch.utils.cpp_exensions` from pytorch-1.7.0 does not contain any references to _PYBIND11_COMPILER_TYPE, see https://github.com/pytorch/pytorch/blob/release/1.7/torch/utils/cpp_extension.py

@malfet It seems that he built it from source since he mentioned `python setup.py build`

**Comment by wwdok** [comment]
> @wwdok can you please run `python -m torch.utils.collect_env` and share its output here?
> 
> And can you explain how did you install PyTorch, as `torch.utils.cpp_exensions` from pytorch-1.7.0 does not contain any references to _PYBIND11_COMPILER_TYPE, see https://github.com/pytorch/pytorch/blob/release/1.7/torch/utils/cpp_extension.py

Hi, this is output :
```
D:\Repo\PoseEstimation\AlphaPose>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.18.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.1
[conda] _pytorch_select           0.1                       cpu_0    defaults
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h74a9793_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.1                      216    defaults
[conda] mkl-service               2.3.0            py38hb782905_0    defaults
[conda] mkl_fft                   1.1.0            py38h45dec08_0    defaults
[conda] mkl_random                1.1.1            py38h47e9c7a_0    defaults
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.18.5           py38h6530119_0    defaults
[conda] numpy-base                1.18.5           py38hc3f5095_0    defaults
[conda] numpydoc                  1.1.0                      py_0    defaults
[conda] pytorch                   1.7.0           py3.8_cuda101_cudnn7_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.6.0+cu101              pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.7.0+cu101              pypi_0    pypi
```
i installed pytorch by `conda install pytorch torchvision torchaudio cudatoolkit=10.1`

**Comment by wwdok** [comment]
> BTW, could you please run the following commands to ensure you have the latest submodules?
> 
> ```
> git submodule sync
> git submodule update --init --recursive
> ```

Done
![image](https://user-images.githubusercontent.com/43233772/98191814-f13db880-1f54-11eb-88d6-f9d5683a8f1c.png)

**Comment by peterjc123** [comment]
@wwdok Yeah. Please try rebuilding it again.

**Comment by wwdok** [comment]
> @wwdok Yeah. Please try rebuilding it again.

Still the same:
![image](https://user-images.githubusercontent.com/43233772/98192773-9d33d380-1f56-11eb-8c1b-dcfe02e9b016.png)

**Comment by peterjc123** [comment]
Wait, let me check the binaries.

**Comment by peterjc123** [comment]
I've downloaded the package you specified from tsinghua mirror. After checking it manually, I didn't find the line you described in `cpp_extension.py`. So would you please remove the pytorch installations and try again?
Commands:
```cmd
conda uninstall pytorch
pip uninstall torch
conda install -c pytorch pytorch torchvision torchaudio cudatoolkit=10.1
```

**Comment by wwdok** [comment]
@malfet @peterjc123 below is the snippet code of cpp_extension.py at `C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\` where is the place  `PYBIND11_COMPILER_TYPE`appears ,and it seems like it is different from https://github.com/pytorch/pytorch/blob/release/1.7/torch/utils/cpp_extension.py:
```
def _write_ninja_file_to_build_library(path,
                                       name,
                                       sources,
                                       extra_cflags,
                                       extra_cuda_cflags,
                                       extra_ldflags,
                                       extra_include_paths,
                                       with_cuda) -> None:
    extra_cflags = [flag.strip() for flag in extra_cflags]
    extra_cuda_cflags = [flag.strip() for flag in extra_cuda_cflags]
    extra_ldflags = [flag.strip() for flag in extra_ldflags]
    extra_include_paths = [flag.strip() for flag in extra_include_paths]

    # Turn into absolute paths so we can emit them into the ninja build
    # file wherever it is.
    user_includes = [os.path.abspath(file) for file in extra_include_paths]

    # include_paths() gives us the location of torch/extension.h
    system_includes = include_paths(with_cuda)
    # sysconfig.get_paths()['include'] gives us the location of Python.h
    system_includes.append(sysconfig.get_paths()['include'])

    # Windows does not understand `-isystem`.
    if IS_WINDOWS:
        user_includes += system_includes
        system_includes.clear()

    common_cflags = [f'-DTORCH_EXTENSION_NAME={name}']
    common_cflags.append('-DTORCH_API_INCLUDE_EXTENSION_H')

    # Note [Pybind11 ABI constants]
    #
    # Pybind11 before 2.4 used to build an ABI strings using the following pattern:
    # f"__pybind11_internals_v{PYBIND11_INTERNALS_VERSION}{PYBIND11_INTERNALS_KIND}{PYBIND11_BUILD_TYPE}__"
    # Since 2.4 compier type, stdlib and build abi parameters are also encoded like this:
    # f"__pybind11_internals_v{PYBIND11_INTERNALS_VERSION}{PYBIND11_INTERNALS_KIND}{PYBIND11_COMPILER_TYPE}{PYBIND11_STDLIB}{PYBIND11_BUILD_ABI}{PYBIND11_BUILD_TYPE}__"
    #
    # This was done in order to further narrow down the chances of compiler ABI incompatibility
    # that can cause a hard to debug segfaults.
    # For PyTorch extensions we want to relax those restrictions and pass compiler, stdlib and abi properties
    # captured during PyTorch native library compilation in torch/csrc/Module.cpp

    for pname in ["COMPILER_TYPE", "STDLIB", "BUILD_ABI"]:
        pval = getattr(torch._C, f"_PYBIND11_{pname}")
        if pval is not None and not IS_WINDOWS:
            common_cflags.append(f'-DPYBIND11_{pname}=\\"{pval}\\"')

    common_cflags += [f'-I{include}' for include in user_includes]
    common_cflags += [f'-isystem {include}' for include in system_includes]

    common_cflags += ['-D_GLIBCXX_USE_CXX11_ABI=' + str(int(torch._C._GLIBCXX_USE_CXX11_ABI))]

    if IS_WINDOWS:
        cflags = common_cflags + COMMON_MSVC_FLAGS + extra_cflags
        from distutils.spawn import _nt_quote_args  # type: ignore
        cflags = _nt_quote_args(cflags)
    else:
        cflags = common_cflags + ['-fPIC', '-std=c++14'] + extra_cflags

    if with_cuda and IS_HIP_EXTENSION:
        cuda_flags = ['-DWITH_HIP'] + cflags + COMMON_HIP_FLAGS + COMMON_HIPCC_FLAGS
        cuda_flags += extra_cuda_cflags
        cuda_flags += _get_rocm_arch_flags(cuda_flags)
        sources = [s if not _is_cuda_file(s) else
                   os.path.abspath(os.path.join(
                       path, get_hip_file_path(os.path.relpath(s, path))))
                   for s in sources]
    elif with_cuda:
        cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
        if IS_WINDOWS:
            for flag in COMMON_MSVC_FLAGS:
                cuda_flags = ['-Xcompiler', flag] + cuda_flags
            for ignore_warning in MSVC_IGNORE_CUDAFE_WARNINGS:
                cuda_flags = ['-Xcudafe', '--diag_suppress=' + ignore_warning] + cuda_flags
            cuda_flags = _nt_quote_args(cuda_flags)
            cuda_flags += _nt_quote_args(extra_cuda_cflags)
        else:
            cuda_flags += ['--compiler-options', "'-fPIC'"]
            cuda_flags += extra_cuda_cflags
            if not any(flag.startswith('-std=') for flag in cuda_flags):
                cuda_flags.append('-std=c++14')
            if os.getenv("CC") is not None:
                cuda_flags = ['-ccbin', os.getenv("CC")] + cuda_flags
    else:
        cuda_flags = None

    def object_file_path(source_file: str) -> str:
        # '/path/to/file.cpp' -> 'file'
        file_name = os.path.splitext(os.path.basename(source_file))[0]
        if _is_cuda_file(source_file) and with_cuda:
            # Use a different object filename in case a C++ and CUDA file have
            # the same filename but different extension (.cpp vs. .cu).
            target = f'{file_name}.cuda.o'
        else:
            target = f'{file_name}.o'
        return target

    objects = [object_file_path(src) for src in sources]

    if IS_WINDOWS:
        ldflags = ['/DLL'] + extra_ldflags
    else:
        ldflags = ['-shared'] + extra_ldflags
    # The darwin linker needs explicit consent to ignore unresolved symbols.
    if sys.platform.startswith('darwin'):
        ldflags.append('-undefined dynamic_lookup')
    elif IS_WINDOWS:
        ldflags = _nt_quote_args(ldflags)

    ext = 'pyd' if IS_WINDOWS else 'so'
    library_target = f'{name}.{ext}'

    _write_ninja_file(
        path=path,
        cflags=cflags,
        post_cflags=None,
        cuda_cflags=cuda_flags,
        cuda_post_cflags=None,
        sources=sources,
        objects=objects,
        ldflags=ldflags,
        library_target=library_target,
        with_cuda=with_cuda)
```

**Comment by peterjc123** [comment]
@wwdok See my previous comment https://github.com/pytorch/pytorch/issues/47333#issuecomment-722115085. The package is looking good but I don't know why you get a different copy of this file.

**Comment by wwdok** [comment]
@peterjc123 Ok, i am doing, it will take a while

**Comment by wwdok** [comment]
> @wwdok See my previous comment [#47333 (comment)](https://github.com/pytorch/pytorch/issues/47333#issuecomment-722115085). The package is looking good but I don't know why you get a different copy of this file.

@peterjc123 I reinstall them, but still got the same error...
the new env info is :
```
D:\Repo\PoseEstimation\AlphaPose>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.0+cu101
[pip3] torchaudio==0.7.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h74a9793_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.2                      256    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.3.0            py38hb782905_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.2.0            py38h45dec08_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.1.1            py38h47e9c7a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.19.2           py38hadc3359_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.19.2           py38ha3acd2a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpydoc                  1.1.0                      py_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.7.0           py3.8_cuda101_cudnn7_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.7.0+cu101              pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.8.1                py38_cu101    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
```
i find my local cpp_extension.py and [here](https://github.com/pytorch/pytorch/blob/2b6a720eb14c69893c748ba2ffd8d0567fb14add/torch/utils/cpp_extension.py) all have `PYBIND11_COMPILER_TYPE`, but https://github.com/pytorch/pytorch/blob/release/1.7/torch/utils/cpp_extension.py can't find `PYBIND11_COMPILER_TYPE`, i don't wheather this info is a clue or not 
![image](https://user-images.githubusercontent.com/43233772/98204182-800bfe80-1f70-11eb-91a3-4f3cd7cf3695.png)

**Comment by peterjc123** [comment]
Since you are using Anaconda, could you please check it is still the case for the downloaded package? It should be located at `C:\ProgramData\Anaconda3\pkgs\pytorch-1.7.0-py3.8_cuda101_cudnn7_0`.

**Comment by peterjc123** [comment]
If it is also broken, I suggest that you remove `C:\ProgramData\Anaconda3\pkgs\pytorch-1.7.0-py3.8_cuda101_cudnn7_0` and `C:\ProgramData\Anaconda3\pkgs\pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2` and try reinstalling pytorch again. I'm pretty sure the online packages don't have this problem.

**Comment by wwdok** [comment]
> Since you are using Anaconda, could you please check it is still the case for the downloaded package? It should be located at `C:\ProgramData\Anaconda3\pkgs\pytorch-1.7.0-py3.8_cuda101_cudnn7_0`.

The `cpp_extension.py` in `Anaconda3\pkgs\pytorch-1.7.0-py3.8_cuda101_cudnn7_0\Lib\site-packages\torch\utils` also has the `PYBIND11_COMPILER_TYPE`
![image](https://user-images.githubusercontent.com/43233772/98208065-9c5f6980-1f77-11eb-8e35-4f65652ca8b4.png)

**Comment by peterjc123** [comment]
Would you please download the package from https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2 and try `conda install --offline pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2`?

**Comment by guyang3532** [comment]
I suggest you remove C:\ProgramData\Anaconda3\lib\site-packages\torch manually and run conda install it again.

**Comment by wwdok** [comment]
@peterjc123 @guyang3532 Hi, i have remove `C:\ProgramData\Anaconda3\lib\site-packages\torch` manually and `conda install --offline pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2`, when i run `python -m torch.utils.collect_env`, it says `No module named 'torch'`, so next step is install torch ? by `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html` ? yesterday i just run this, and issue still exist, so this time, i would like to follow your guides ~ actually i have a question, why install pytorch by pip and conda is different :
![image](https://user-images.githubusercontent.com/43233772/98314332-b436fc00-2010-11eb-8f6a-1a0eec9290fd.png)
![image](https://user-images.githubusercontent.com/43233772/98314374-c7e26280-2010-11eb-9f83-41ec7d048fe1.png)
so previously, in order to install torch, pytorch and torchvison, i ran two commands `conda install pytorch torchvision torchaudio cudatoolkit=10.1` and `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, i am not sure wheather this is right

**Comment by peterjc123** [comment]
> @peterjc123 @guyang3532 Hi, i have remove `C:\ProgramData\Anaconda3\lib\site-packages\torch` manually and `conda install --offline pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2`, when i run `python -m torch.utils.collect_env`, it says `No module named 'torch'`, so next step is install torch ? by `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html` ? yesterday i just run this, and issue still exist, so this time, i would like to follow your guides ~ actually i have a question, why install pytorch by pip and conda is different :
> ![image](https://user-images.githubusercontent.com/43233772/98314332-b436fc00-2010-11eb-8f6a-1a0eec9290fd.png)
> ![image](https://user-images.githubusercontent.com/43233772/98314374-c7e26280-2010-11eb-9f83-41ec7d048fe1.png)
> so previously, in order to install torch, pytorch and torchvison, i ran two commands `conda install pytorch torchvision torchaudio cudatoolkit=10.1` and `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, i am not sure wheather this is right

Why would it throw that error? Do you have multiple Python installations? Could you please show me the result of `where python`?

**Comment by peterjc123** [comment]
> so previously, in order to install torch, pytorch and torchvison, i ran two commands `conda install pytorch torchvision torchaudio cudatoolkit=10.1` and `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, i am not sure wheather this is right

Both are right. The package in conda is `pytorch` and the one in PyPI is `torch`. The reason is that `pytorch` in PyPI is already registed when this library is publicly announced.

**Comment by wwdok** [comment]
> Why would it throw that error? Do you have multiple Python installations? Could you please show me the result of `where python`?

This is the output:
![image](https://user-images.githubusercontent.com/43233772/98329014-24a24500-2032-11eb-81e7-e5e27f3848b9.png)

**Comment by wwdok** [comment]
> > so previously, in order to install torch, pytorch and torchvison, i ran two commands `conda install pytorch torchvision torchaudio cudatoolkit=10.1` and `pip install torch==1.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`, i am not sure wheather this is right
> 
> Both are right. The package in conda is `pytorch` and the one in PyPI is `torch`. The reason is that `pytorch` in PyPI is already registered when this library is publicly announced.

This time i only install pytorch by `conda install --offline pytorch-1.7.0-py3.8_cuda101_cudnn7_0.tar.bz2` as you said above, then  i ran `python -m torch.utils.collect_env` immeadiately, i find torch already have installed on my computer ! previously because i didn't see `torch` and `torchvision` in the `conda list`, so i suspected torch and torchvison are not installed, and install them by pip again, but this time i don't , and the the error dispear ! so maybe the cause is that i install pytorch by conda and pip two times ...
```
C:\ProgramData\Anaconda3\pkgs>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.0
[pip3] torchfile==0.1.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.1.243             h74a9793_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2020.2                      256    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.3.0            py38hb782905_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.2.0            py38h45dec08_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.1.1            py38h47e9c7a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.19.2           py38hadc3359_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.19.2           py38ha3acd2a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpydoc                  1.1.0                      py_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.7.0           py3.8_cuda101_cudnn7_0    <unknown>
```
