### ISSUE TITLE
[Big question]Why test_nn use double dtype as cpu input and why set dtype2prec_DONTUSE?

### ISSUE THREAD

**Issue by ddummkopfer** [pytorch/pytorch#47340]
Hi, To whom it may concern,

When I use the CUDA to test all the cases created in test_nn.py and common_nn.py, I find the CPU input will be always created double because the torch.set_defult_dtype(torch.double) in [here](https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L21).

I have two big confusion:

**1. Why set cpu input as double dtype instead of float32?**

**2. In test_nn.py, why we set tolerance for the gap between cpu output and cuda output like below ?  The tolerance is decided according to what?**
dtype2prec_DONTUSE = 
{torch.float: 1e-5,
                                         torch.double: 1e-5,
                                         torch.half: 1e-2,
                                         torch.bfloat16: 1e-1}
The code is [here](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1834).

Thank you for your attention and look forward to your significant reply.

cc @mruberry @VitalyFedyunin

**Comment by ejguan** [comment]
1. I think I have seen several PR discussing it. https://github.com/pytorch/pytorch/pull/27444#issuecomment-539111261
2. I think they are just empirical number.

**Comment by mruberry** [comment]
The tests are just a little older and need to be updated to use our latest tools, that's all.

**Comment by ddummkopfer** [comment]
@mruberry Thank you for your attention. Do you mean that you will use the latest test tools to redesign the test in torch in future?
I wonder what is the latest tool you mentioned? 
Thank you 👍

**Comment by mruberry** [comment]
If you take a look at test_unary_ufuncs.py, for example, you can see the tests there make good use of our device generic test framework (see the Wiki for more information) and our new operator database to generate and run tests. test_torch.py also uses the device generic test framework. test_nn.py, on the other hand, currently only has a few functions using the device generic test framework. In the future those tests we'll probably be generated using the operator database and a (not yet developed) module database.

**Comment by ddummkopfer** [comment]
@mruberry @ejguan Thank you for so meaningful explanation.
I have a little confusion, the test suites use many **_assertEqual(cpu_output, gpu_output, prec)_** to check if cuda calculates right. I wonder how to get or calculate the precision(called tolerance), is it a just empirical number?

**Comment by ddummkopfer** [comment]
@mruberry Another question, for now the default dtype in test_nn.py is **double**, and most of the test cases use double cpu output to compare with float gpu output or other dtype gpu output. In future, will the default dtype in test_nn.py be changed to float or remain double? And why use double as default dtype in test_nn.py and test_torch.py?

**Comment by mruberry** [comment]
As the linked comment describes, setting the default dtype in the test_nn test suite is a legacy issue. test_torch.py doesn't use double as the default dtype.

**Comment by ddummkopfer** [comment]
@mruberry Thank you for your significant comments. In future, you will change the default to float in test_nn.py, will you?

**Comment by mruberry** [comment]
I would expect so, yes.

**Comment by ddummkopfer** [comment]
Thank you for your help! Really appreciate it. @mruberry 
Is there any learning material about device generic test framework? I google it but seems to not find it.

**Comment by mruberry** [comment]
Check out the wiki article [here](https://github.com/pytorch/pytorch/wiki/Writing-tests-that-run-on-all-available-device-types) or the comment in its file [here](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_device_type.py).

**Comment by ddummkopfer** [comment]
Thank you. Wonderful learning material and I will benefit a lot from it. Thank you so much!
