### ISSUE TITLE
[complex] torch.{sqrt, abs}: does not match numpy

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#47358]
Happens only on CPU

**torch.cfloat**
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+73e121d'
>>> import numpy as np
>>> x = torch.tensor(0.-1.0000e+20j)
>>> x.sqrt()
tensor(inf-infj)
>>> np.sqrt(x.numpy())
(7071067600-7071067600j)
```

**torch.cdouble**
```python
>>> import torch
>>> x = torch.tensor(-1.0000e+20-4988429.2000j, dtype=torch.complex128)
>>> x.sqrt()
tensor(0.-1.0000e+10j, dtype=torch.complex128)
>>> import numpy as np
>>> np.sqrt(x.numpy())
(0.00024942146-10000000000j)
>>> x.cuda().sqrt().cpu().numpy() == np.sqrt(x.numpy())
True
```

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @anjali411 @dylanbespalko @mruberry @vishwakftw @jianyuh @nikitaved @pearu

**Comment by kshitij12345** [comment]
Relevant lines: 
https://github.com/pytorch/pytorch/blob/996f444c007a89f7364ed03b7c24755f7ec43eb0/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L315-L328

https://github.com/pytorch/pytorch/blob/996f444c007a89f7364ed03b7c24755f7ec43eb0/aten/src/ATen/cpu/vec256/vec256_complex_double.h#L277-L290

**Comment by kshitij12345** [comment]
Issue looks to arise from use of `abs`,

```python
import numpy as np
import torch

print(torch.__version__)
x = torch.tensor([0.-1.0000e+20j] * 10)
print("ABS:", x.abs())
print("ABS:", np.abs(x.numpy()))
```

Output
```
1.8.0a0+f19637e
ABS: tensor([       inf,        inf,        inf,        inf,        inf,        inf,
               inf,        inf, 1.0000e+20, 1.0000e+20])
ABS: [1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20 1.e+20]
```

**Comment by kshitij12345** [comment]
For `abs`,
https://github.com/pytorch/pytorch/blob/d8c3b2b10c14f86f817f1ef12cabc8ef5e37c30a/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L150-L162

Following line leads to infinity,
https://github.com/pytorch/pytorch/blob/d8c3b2b10c14f86f817f1ef12cabc8ef5e37c30a/aten/src/ATen/cpu/vec256/vec256_complex_float.h#L151

as `-1e20 * -1e20` is `1e40` while max that float represent is 3.40282e+38

**Comment by mruberry** [comment]
Thanks for reporting this issue, @kshitij12345. I think we would accept a PR fixing this (as long as it wasn't too intrusive).
