### ISSUE TITLE
CUDA 11.0 compilation flags incorrect for extensions

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#47352]
## 🐛 Bug

CUDA11.0 does not support sm_86.

PyTorch by default uses the capability of device to compile extensions:
https://github.com/pytorch/pytorch/blob/996f444c007a89f7364ed03b7c24755f7ec43eb0/torch/utils/cpp_extension.py#L1424-L1427

Therefore, if a user uses CUDA11.0 pytorch binary on RTX30- GPUs, extension will be compiled with sm_86 and cause compilation error.

## Expected behavior

Extension be compiled with a capability of 8.0 instead.

cc @malfet @seemethere @walterddr @ngimel

**Comment by walterddr** [comment]
@ppwwyyxx if this is not fixed please feel free to reopen

**Comment by ppwwyyxx** [comment]
The issue was not fixed - I think the cmake file is not used for compiling extensions.
To reproduce on other GPUs you can fake `torch.cuda.get_device_capability` to return `[8, 6]`.

**Comment by walterddr** [comment]
can you share the command you use to verify? including
* how did you setup pip environment, what commit ID on master you used to install pytorch & torch vision, you can run `torch/utils/collect_env.py` to report those. 
and error message when you install detectron
