### ISSUE TITLE
CUDAExtension: nvcc does not pick right gcc by default

### ISSUE THREAD

**Issue by sigeisler** [pytorch/pytorch#47377]
## 🐛 Bug

*I am happy to dig into the code and fix this error. However, first I want confirmation that this is an issue that should be fixed.*

I recently upgraded to Ubuntu 20.X and hence the compiler etc. have changed. When I was building some small CUDAExtension I now get the error:
```
ERROR: Command errored out with exit status 1:
   command: ~/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vfy2_7nz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vfy2_7nz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3y7t9hm0
       cwd: /tmp/pip-req-build-vfy2_7nz/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'kernels' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/csrc
  ~/anaconda3/envs/rgnn_at_scale/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem   ~/anaconda3/envs/rgnn_at_scale/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem   ~/anaconda3/envs/rgnn_at_scale/include -fPIC -I~/anaconda3/lib/python3.7/site-packages/torch/include -I~/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I~/anaconda3/lib/python3.7/site-packages/torch/include/TH -I~/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I~/anaconda3/include/python3.7m -c csrc/custom.cpp -o build/temp.linux-x86_64-3.7/csrc/custom.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=kernels -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  /usr/local/cuda/bin/nvcc -I~/anaconda3/lib/python3.7/site-packages/torch/include -I~/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I~/anaconda3/lib/python3.7/site-packages/torch/include/TH -I~/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I~/anaconda3/include/python3.7m -c csrc/custom_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/custom_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=kernels -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=sm_70 -std=c++11
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for kernels
```

Since in the first compile cc1plus was found (see the warning), I simply extended the CUDAExtension definition:
```python
        CUDAExtension(
            'kernels',
            [
                'csrc/custom.cpp',
                'csrc/custom_kernel.cu'
            ],
            extra_link_args=['-lcusparse', '-l', 'cusparse'],
            extra_compile_args={
                'cxx': [],
                'nvcc': ['--compiler-bindir=~/anaconda3/envs/rgnn_at_scale/bin/x86_64-conda-linux-gnu-cc']
            }
        )
```
And the error was gone (Note that the `compiler-bindir` is copied from the first command!!!).

## To Reproduce

1. Create a machine where your system gcc version mismatches with your CUDA installation (e.g. gcc 9 with CUDA 10.2) and then install pytorch via conda.
1. Checkout this [git repository](https://github.com/sigeisler/reliable_gnn_via_robust_aggregatio)
1. Build the kernel with `pip install ./kernels`

## Expected behavior

The consecutive compilation steps should use the same c compiler.

cc @yf225 @glaringlee @ngimel

**Comment by ppwwyyxx** [comment]
We added this workaround to our setup.py in detectron2 for similar reasons:
https://github.com/facebookresearch/detectron2/blob/5a8abd3ee7a159eb56bad9806d43a160c8414736/setup.py#L118-L121

**Comment by sigeisler** [comment]
@ppwwyyxx thank you! What you suggest is a much better workaround.

**Comment by sigeisler** [comment]
As it turns out this has been fixed by https://github.com/pytorch/pytorch/commit/4134b7abfa60a659de27736704c62277ecf291d2#diff-258d5272916c8cf5ac89aad77f7c114b585848826f6bbaeee91fe62a4391ee5e

**Comment by malfet** [comment]
I was about to ask you to share the output of `which nvcc` and `echo $CC` commands. 
So I guess it is fixed in pytorch-1.7, but not in 1.6?

**Comment by sigeisler** [comment]
Oh yeah, I missed stating that I use PyTorch 1.6... I am sorry for any inconvenience!

I can confirm that with PyTorch 1.7 it is working as long as you do not specify `ccbin` in the `extra_compile_args` for `nvcc` yourself. In this case, one gets the error `nvcc fatal   : redefinition of argument 'compiler-bindir'`

**Comment by sigeisler** [comment]
@malfet what is the general strategy of clashing configurations? It would be straight forward to add a check if the user already set a specific `ccbin` (and I would do it if it is desired).

**Comment by sigeisler** [comment]
@ppwwyyxx from my local experiment (see comment above) I conclude that https://github.com/facebookresearch/detectron2/blob/5a8abd3ee7a159eb56bad9806d43a160c8414736/setup.py#L118-L121 will likely cause an error for PyTorch 1.7.0

**Comment by malfet** [comment]
@sigeisler this sounds like a good strategy: `-ccbin` flag should only be added if it's not already explicitly specified.
