### ISSUE TITLE
PyTorch doesn't build with Cuda 11.1

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#47412]
## 🐛 Bug
Building fails with cuda 11.1

## To Reproduce

1. install cuda 11.1
2. follow instructions in pytorch repo to build from source. Note that I can't install ` magma-cuda111` because it is not available.
3. During build, following error shows up:
```
In file included from /usr/local/cuda/bin/crt/link.stub:129:
/tmp/tmpxft_001a896c_00000000-4_devlink.fatbin.c:47911901: internal compiler error: Segmentation fault
47911901 | ".text\n");
         |
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Note that cuda-info is inaccurate because last time I built PyTorch with USE_CUDA=0**

PyTorch version: 1.7.0a0+c253b10
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Fedora release 31 (Thirty One) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-sphinx-theme==0.0.19
[pip3] torch==1.8.0a0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.1.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.1           py38hbc911f0_0
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] pytorch-sphinx-theme      0.0.19                   pypi_0    pypi
[conda] torch                     1.7.0a0+5cff67f          pypi_0    pypi
## Additional context

cc @malfet @seemethere @walterddr @ngimel

**Comment by ptrblck** [comment]
@gmagogsfm Are you building the `magma` package manually or are you skipping it?
Could you post the complete install log so that we can have a look at it, please?

**Comment by gmagogsfm** [comment]
> @gmagogsfm Are you building the `magma` package manually or are you skipping it?
> Could you post the complete install log so that we can have a look at it, please?

I skipped magma

[log_cuda.txt](https://github.com/pytorch/pytorch/files/5491690/log_cuda.txt)

**Comment by ptrblck** [comment]
Thanks for the log.
Are you seeing the same failure with the current PyTorch master?
If so, which `nvcc` version are you using so that we could try to reproduce this issue?

Is the build failing while compiling the same source file or randomly at different spots?

**Comment by gmagogsfm** [comment]
> Thanks for the log.
> Are you seeing the same failure with the current PyTorch master?
> If so, which `nvcc` version are you using so that we could try to reproduce this issue?
> 
> Is the build failing while compiling the same source file or randomly at different spots?

The failure is with current PyTorch master

```
(pytorch) [ycao@ycao-fedora-MJ0AKH22]~/pytorch3% /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

I think the build error is consistent, always at same location.

**Comment by malfet** [comment]
Thank you for sharing the logs.
According to the logs compiler crashed while linking separable compiled CUDA kernels build in debug mode from `nccl/src/collectives/devices` folder
https://github.com/NVIDIA/nccl/blob/084207e685c4587e7d0aa2f1f7f148d3e0e68da6/src/collectives/device/Makefile#L68

**Comment by mortezardana** [comment]
are you sure that pytorch works with cuda 11.1? I just checked pytorch website, in getting started tab, and there is only cuda 9.2, 10.1, 10.2 and 11. I'm just getting started with machine learning and pytorch so I was searching for the answer, if pytorch works with cuda 11.1 that I just downloaded then I ended up here.

**Comment by malfet** [comment]
Yes, PyTorch is compileable by CUDA-11.1, but we are not yet in place where a stable CUDA-11.1 binaries can be build, as one can see by looking at `pytorch_libtorch_linux_xenial_cuda11_1_cudnn8_py3_gcc7_build` CI build artifacts.

**Comment by gmagogsfm** [comment]
I can confirm pytorch builds with 11.1 with "DEBUG=0" closing
