### ISSUE TITLE
[Discussion] Use the unicode variant of the Windows API

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#47422]
## 🚀 Feature

Currently, we are using the ascii variant of the Windows API. But apparently it is problematic when user passes in non-ascii strings in fields like filenames, paths and etc. It has caused problems like https://github.com/pytorch/vision/issues/2931.

The usages of Windows API exist in those sources:
- https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/fuser/cpu/temp_file.h
- https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/fuser/cpu/fused_kernel.cpp
- https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THAllocator.cpp
- https://github.com/pytorch/pytorch/blob/master/c10/util/Backtrace.cpp

# Details
There are mainly two ways that users could pass in a string to our core library, including
1. from PyTorch through `pybind11`

  In this case, if we use `std::string` or `const char*` as the argument type, it will convert the string to `utf-8` automatically. But unluckily, Windows API don't accept UTF-8 strings. 

2. from LibTorch

  In this case, if we use `std::string` or `const char*` as the argument type, the string will be encoded according to the user's locale. (e.g. for Chinese users, it will be using `GB2312`. ) It stills need to the conversion to UTF-16 btw.

# Options
We have two options here.
1. Convert it to UTF-16 and call the unicode variant of the Windows API. This is easy to implement. But the difficulty lies in the problem that how we tell whether a string is encoded by utf-8, ascii or anything else? (Or maybe we just claim that we only accepts utf-8 strings?) (An alternative is the `/utf-8` switch. We could mark it as public argument for CMake. https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-150)
2. Use `std::wstring` as string argument type. It avoids the conversion, but we will have to redesign all of our APIs. What' s more, It's hard to maintain. Because conventionally, we should implement both the unicode version and the ascii version and select them through the existence of the `_UNICODE` macro.

```
#ifdef _UNICODE
#define test test_unicode
#else
#define test test_ascii
#endif

void test_ascii(const std::string& str);
void test_unicode(const std::wstring& str);
```
3. Use DOS 8.3 path (written in https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#UTF-8) I think it has the same problem as the first option since we need to call the Windows API to do filename conversions. What's more, it only works for paths.

## Additional context

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by glaringlee** [comment]
This is a solid topic to me. Mark as 'triage review' so we can discuss whether this is actionable and what is the priority.

**Comment by ezyang** [comment]
I think we should assume that all our internal strings are UTF-8, and then transcode accordingly for Windows.

**Comment by skyline75489** [comment]
1. Traditionally everything on Win32 is internally UTF-16 and everything on *nix is UTF-8. However, we can not make such assumption based on the platform arbitrarily. It is possible to detect character encoding using the [ICU Character Set Detection](http://userguide.icu-project.org/conversion/detection). The ICU library was first added to Windows 1703 ([Source](https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-). I don't know if there's alternatives on earlier version of Windows.

2. I don't think we want that. The `_UNICODE` and `w` vs `non-w` are both legacy Win32 stuff which I think should only exist on Win32-only projects. 

3. Well... not really a solid solution.

**Comment by peterjc123** [comment]
So, we are assuming all the incoming strings and the strings in our code are UTF-8, right? It is mostly fine, but the tricky part is that when you want to print it out using `cout`, it won't work as you expected. The workground for this includes
(1) `SetConsoleOutputCP(CP_UTF8)` which overrides the encoding of the current console https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows
I don't think this is good enough though because changing the user's environment is generally a bad idea.
(2) Implement sth using Windows API to print out to console
This is already implemented in `Boost.Nowide`. 
https://github.com/boostorg/nowide/blob/develop/src/iostream.cpp Luckily, it does release a standalone version so we don't have to include the huge Boost library to use it.

**Comment by peterjc123** [comment]
> * assumption based on the platform arbitrarily. It is possible to detect character encoding using the [ICU Character Set Detection](http://userguide.icu-project.org/conversion/detection). The ICU library was first added to Windows 1703 ([Source](https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-)). I don't know if there's alternatives on earlier version of Windows.
> *

Thanks for letting me know. Actually, it writes on the page that "it is embedded into Windows starting from 1703". But it doesn't say that you could not use the library with 1703 or below. So if we really need it, we can use it as a submodule.

**Comment by skyline75489** [comment]
The beauty of `ICU` library is that it's widely used (and can be easily installed) in many Linux distros. The fact that Windows 10 1703 comes with its own dlls of `ICU` makes it easier to use on the Windows platform. I'm pretty sure there's plenty of ways to detect characters encodings. I just don't like the idea of writing Win32-specific code, if you know what I mean. So `ICU` seems to be a good option here.

>but the tricky part is that when you want to print it out using cout, it won't work as you expected

Excuse me for being a newbie on PyTorch. I'm a bit confused. I thought this thread is about _reading_ contents of which the encoding may vary. Writing to console or file is a different problem.

**Comment by peterjc123** [comment]
@skyline75489 

> On the ICU webpage, [compact_enc_det](https://github.com/google/compact_enc_det) is mentioned as an alternative, with smaller size in code.

Good to know.



> Writing to console or file is a different problem.

Ok, let's focus on reading first. So, the most urgent one to fix is `https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THAllocator.cpp` that uses the ascii variant of `CreateFile/CreateEvent/OpenEvent`. And the work will include the following things.
1. Utils functions for encoding detection & conversion @ezyang Could you please recommend a place to host those functions?
2. UTF-8 Detection & Translation to UTF-16 in `THMapAllocator`
3. Call the wide variant of the Windows APIs instead

What do you think?

**Comment by skyline75489** [comment]
That's basically the same as how I picture it. The hardest part I think is the encoding detection part. Since I'm new to this project, I'd like to introduce as less code change as possible. Adding a third party library is going to be a quite large amount of code change, which personally I'm trying to avoid.

A side note for the writing part: for some libraries like logging libraries, it can actually just pass through whatever the origin content is, without considering the exact encoding. The reason is obvious: on Win32 the default text file encoding, and as you point out, Console encoding, are also UTF-16. I don't know if this helps, just want to point it out.

**Comment by ezyang** [comment]
General string utilities can go in `c10/util`.

I'm still not convinced we need ICU. The argument seems to be that we don't know what encoding strings passed in with `std::string` are (for Python, I think we all agree that there is no ambiguity), and therefore we must use ICU to detect. But whatever: just fiat what the encoding should be, and make your users work it out. If we want to be nice, we can provide a UTF-16 variant of the API in case someone is Windows style. Am I misunderstanding the motivation for ICU?

**Comment by skyline75489** [comment]
@ezyang I think You understanding is on track. 

>just fiat what the encoding should be, and make your users work it out

This is actually reasonable if we are talking about C++ code. But for issues like https://github.com/pytorch/vision/issues/2931, users are not aware of the possible issue caused by encoding. Everything passed in by Python 3 is UTF-8. But on Win32 level we need it to be UTF-16. 

That being said, as I pointed it before, I'm generally against adding UTF-16 variant of the API because it introduces too much work and duplication. I can also understand the extra work needed for adding character detections.

How about this. If we leave GB18030 out of consideration, I think we can safely assume that everything passed in using `std::string` is UTF-8. And if we are on windows we can just arbitrarily convert it to UTF16 and use the `W` version of the API. The only downside of this is the conversion to UTF-16 will increase memory footprint. But it gives us much better unicode support.

**Comment by peterjc123** [comment]
> I think we can safely assume that everything passed in using `std::string` is UTF-8.

Yeah, that's actually okay. We may provide some utils function for them (e.g. `ACP_TO_UTF8` or `UTF8_TO_ACP`) but detecting the encoding is somehow out of our responsibility. What's more, it is extremely easy to define a UTF-8 string in C++11. (e.g. `string s = u8"xxxxx";`)

**Comment by peterjc123** [comment]
BTW, I don't know whether `MultiByteToWideChar(CP_UTF8, ...)` will fail for non UTF-8 strings. If it will, we may raise a warning there saying that we only support UTF-8 strings.

**Comment by skyline75489** [comment]
Great! Now what's left to do is:

1. Extract a function that does `u8u16` conversion (like the one in https://github.com/pytorch/vision/pull/2949).
2. If `_WIN32` is found, call this function and use `W` version of Win32 API accordingly (an example would still be https://github.com/pytorch/vision/pull/2949)

>we may raise a warning there saying that we only support UTF-8 strings

Good idea. I'm also OK without having the error message. There are probably millions of issues caused by GB18030 . I think people would understand

**Comment by ezyang** [comment]
> But for issues like pytorch/vision#2931, users are not aware of the possible issue caused by encoding

I read through this issue and I'm still a bit confused. If the user sends us a Unicode string (which strings are by default on Python 3, the only version we support), then we also know that we're gonna get a UTF-8 (unless pybind11 is doing some locale aware transcoding--if it is, we should make it stop doing that.) If they send us a byte string that's a little more sensitive. I don't know off the top of my head what should happen on Windows, but on Linux the file system APIs are not actually encoding aware and we can just pass it on directly.

It looks like we have a decent amount of alignment on the way forward, so count this as an ACK from me.

**Comment by peterjc123** [comment]
@ezyang 

> If the user sends us a Unicode string (which strings are by default on Python 3, the only version we support), then we also know that we're gonna get a UTF-8 (unless pybind11 is doing some locale aware transcoding--if it is, we should make it stop doing that.)

Let me explain that for you. Let's start with the strings on Python 3. As we all know, they are Unicode strings. Internally, the strings are stored as bytes of UTF-8. (with Python 3.6+) So for pybind11, if you register a function with string arguments as `std::string`, it doesn't do anything transcoding work. https://github.com/pybind/pybind11/blob/master/include/pybind11/cast.h#L1202-L1257

But when using LibTorch, the story is becoming a bit complex. If we use `std::string s = "你好";` or `char s[] = "你好";`, then the string uses the encoding which is locale-dependent. (type A) But with C++11, it is quite easy to define a UTF-8 string with the u8 prefix. e.g. `std::string s = u8"你好";`. (type B) Internally, the strings are encoded using the current user code page for type A unless we pass `/utf-8` to the compiler. https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160#remarks

And then, for Windows API, usually it has two variants for one single API that accepts/generates strings, which has the suffix `A` or `W`, that stands for `ANSI` and `Wide string` here. `ANSI` refers to the narrow version of the current encoding and `W` refers to the wide one. But ANSI is a quite old format which only contains latin characters. So for broader language support, we need to go for the `-W` variants that accepts `UTF-16LE` strings.

Historically, Windows implements two variants for the Windows API and select them according to the macro `UNICODE`. But you are always free to use any one of them by specifying the name of the API. e.g. You may use `ReadFileA` even if you defined `UNICODE`.

The current problem is that when users pass in a string that contains non-ascii characters, we won't properly handle them because we use the ANSI variant of the Windows API. So there are two levels for solving the problem:
1. If we are sure the strings passed in are encoded in UTF-8, then we just need to encode it again to UTF16-LE and then call the unicode variant of the Windows API.
2. But if the hypothesis in (1) is not satisfied, we may need to do some extra detection work. That is, we need to determine the encoding of the incoming string (usually it should either be UTF-8 or the current locale). And then we convert them to UTF-16LE and call the `-W` variants.

Plus: You mentioned internal strings in a previous comment. According to the second paragraph, they are currently encoded by the current codepage(1252) on Windows although there is no non-ascii characters in them. So you may assume it is also `UTF-8` encoded so it is safe to go with level 1.

**Comment by ezyang** [comment]
OK. So basically, if people write string literals without using u8 prefix, we have no idea what encoding they are and have to work hard. This sounds like a self inflicted problem and I'm happy if we don't care too much about it :)

**Comment by peterjc123** [comment]
> Great! Now what's left to do is:
> 
> 1. Extract a function that does `u8u16` conversion (like the one in [pytorch/vision#2949](https://github.com/pytorch/vision/pull/2949)).
> 2. If `_WIN32` is found, call this function and use `W` version of Win32 API accordingly (an example would still be [pytorch/vision#2949](https://github.com/pytorch/vision/pull/2949))
> 
> > we may raise a warning there saying that we only support UTF-8 strings
> 
> Good idea. I'm also OK without having the error message. There are probably millions of issues caused by GB18030 . I think people would understand

@ezyang @skyline75489 So let's follow this route.

**Comment by skyline75489** [comment]
I've filed an initial PR #47905 for this. @peterbell10  @ezyang  Could you guys please help review to make sure I'm understanding this correctly ?

**Comment by peterjc123** [comment]
@skyline75489 Wow, thanks. I'll take a look.

**Comment by peterjc123** [comment]
@skyline75489 If you have time, would you please fix the Windows API usages in the following files, too?
```
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/fuser/cpu/temp_file.h
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/fuser/cpu/fused_kernel.cpp
```
The one in `Backtrace.cpp` needs more discussion. Let's put it aside.

**Comment by skyline75489** [comment]
Sure, will do.

**Comment by mantaionut** [comment]
@peterjc123 I was checking [c10/util/Backtrace.cpp](https://github.com/pytorch/pytorch/blob/master/c10/util/Backtrace.cpp) for the required changes, but is there a scenario in which the current implementation fails?

**Comment by kalaskarsanket** [comment]
@peterjc123  Following up for your response on @mantaionut  last message.

**Comment by peterjc123** [comment]
> @peterjc123 I was checking [c10/util/Backtrace.cpp](https://github.com/pytorch/pytorch/blob/master/c10/util/Backtrace.cpp) for the required changes, but is there a scenario in which the current implementation fails?

Usually it won't fail, except for corner cases e.g. locally-built PyTorch in a Chinese dev environment

**Comment by taras-janea** [comment]
@peterjc123 could you please confirm if there’s anything remaining to complete the issue?

**Comment by peterjc123** [comment]
@taras-janea I think you can close this issue since all items are covered.
