### ISSUE TITLE
whether the torch.quantization.prepare_qat can support ConvTranspose2d or not

### ISSUE THREAD

**Issue by fxwfzsxyq** [pytorch/pytorch#47427]
whether the torch.quantization.prepare_qat can support ConvTranspose2d or not

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by fxwfzsxyq** [comment]
> whether the torch.quantization.prepare_qat can support ConvTranspose2d or not

![image](https://user-images.githubusercontent.com/18416103/98205664-7a63e800-1f73-11eb-9df4-2ce7046c8bb8.png)

**Comment by supriyar** [comment]
@fxwfzsxyq we currently do not support ConvTranspose2d for QAT. It is supported in PTQ though.

Hope this helps answer your question!
