### ISSUE TITLE
pytorch can not forward jit model from libtorch

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#47435]
libtorch pytorch 1.6.0 windows
--------------------------------------
I trained a model with libtorch,and use torch::save(model,"model.pth") to save libtorch model.

Then I try to load it with pytorch.
model=torch.jit.load("model.pth")
print(model)
------------------------
RecursiveScriptModule(
  original_name=Module
  (cnn): RecursiveScriptModule(
    original_name=Module
    (0): RecursiveScriptModule(original_name=Module)
    (1): RecursiveScriptModule(original_name=Module)
    (2): RecursiveScriptModule(original_name=Module)
    (3): RecursiveScriptModule(original_name=Module)
    (4): RecursiveScriptModule(original_name=Module)
    (5): RecursiveScriptModule(original_name=Module)
    (6): RecursiveScriptModule(original_name=Module)
    (7): RecursiveScriptModule(original_name=Module)
    (8): RecursiveScriptModule(original_name=Module)
    (9): RecursiveScriptModule(original_name=Module)
    (10): RecursiveScriptModule(original_name=Module)
    (11): RecursiveScriptModule(original_name=Module)
    (12): RecursiveScriptModule(original_name=Module)
    (13): RecursiveScriptModule(original_name=Module)
    (14): RecursiveScriptModule(original_name=Module)
    (15): RecursiveScriptModule(original_name=Module)
    (16): RecursiveScriptModule(original_name=Module)
    (17): RecursiveScriptModule(original_name=Module)
    (18): RecursiveScriptModule(original_name=Module)
    (19): RecursiveScriptModule(original_name=Module)
    (20): RecursiveScriptModule(original_name=Module)
  )
  (rnn): RecursiveScriptModule(
    original_name=Module
    (0): RecursiveScriptModule(
      original_name=Module
      (rnn): RecursiveScriptModule(original_name=Module)
      (embedding): RecursiveScriptModule(original_name=Module)
    )
    (1): RecursiveScriptModule(
      original_name=Module
      (rnn): RecursiveScriptModule(original_name=Module)
      (embedding): RecursiveScriptModule(original_name=Module)
    )
  )
)
--------------------------
imgae=torch.zeros(1,3,32,280)
model(image)
However,it can not forward .
Error message: 'RecursiveScriptModule' object has no attribute 'forward'.
---------------------
How do I save the JIT model from libtorch and make Pytorch load?

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi laizewei,

Could you give a bit of clarification for what you mean by "train with libtorch"? Also, do you mind provide full code example and steps to reproduce this issue? Thanks!

**Comment by laizewei** [comment]
Some models save the weight file immediately after training and can be reasoned by Pytorch. If the weight file is read first, it cannot be reasoned by Pytorch without training to save directly.
有些模型训练完马上保存权重文件，就可以被pytorch推理。如果是先读取权重文件，不训练直接保存就不能被pytorch推理。

**Comment by gmagogsfm** [comment]
Hi Laizwei,

Thanks for providing additional context. But I am afraid that it is still not enough to investigate. Could you provide concrete runnable code please? Thank you.

**Comment by laizewei** [comment]
Unable to upload code due to job confidentiality. You can close this issue.Thank you.

**Comment by gmagogsfm** [comment]
I see. If you'd like, feel free to make a smaller repro that is different from your actual code but still displays the issue.

**Comment by sshuair** [comment]
@gmagogsfm I have got the same problem. Could you check it out?

env:
- os: macos 10.15.7
- pytorch: 1.7.1
- libtorch: 1.7.1

This is the code:
- cpp code
[libtorch_cnn.zip](https://github.com/pytorch/pytorch/files/5950399/libtorch_cnn.zip)

- the python jit.load code
``` python
import torch
pt = 'libtorch_0.pt'
jit_loaded = torch.jit.load(pt)
jit_loaded.eval()
dummy_input = torch.randn(1, 1, 28, 28)
target = jit_loaded(dummy_input)
```

and the error is :

```
---------------------------------------------------------------------------
ModuleAttributeError                      Traceback (most recent call last)
<ipython-input-18-b8128fa2a653> in <module>
      1 jit_loaded.eval()
      2 dummy_input = torch.randn(1, 1, 28, 28)
----> 3 target = jit_loaded(dummy_input)
      4 # torch.onnx.export(jit_loaded, dummy_input, 'libtorch_traced.pth.onnx', verbose=True,
      5 # operator_export_type=torch.onnx.OperatorExportTypes.ONNX,

~/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/anaconda3/lib/python3.8/site-packages/torch/jit/_script.py in __getattr__(self, attr)
    556                 return script_method
    557 
--> 558             return super(RecursiveScriptModule, self).__getattr__(attr)
    559 
    560         def __setattr__(self, attr, value):

~/anaconda3/lib/python3.8/site-packages/torch/jit/_script.py in __getattr__(self, attr)
    286         def __getattr__(self, attr):
    287             if "_actual_script_module" not in self.__dict__:
--> 288                 return super(ScriptModule, self).__getattr__(attr)
    289             return getattr(self._actual_script_module, attr)
    290 

~/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    776             if name in modules:
    777                 return modules[name]
--> 778         raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
    779             type(self).__name__, name))
    780 

ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'forward'
```
