### ISSUE TITLE
CI no longer runs ProcessGroup MPI Tests

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#47443]
#34311 can confirm that earlier this year, CI runs at least 94 MPI tests. See `pytorch_linux_xenial_cuda10_1_cudnn7_py3_nogpu_test` and search for `Running distributed tests for the mpi backend`. You will see:

```
Mar 05 18:29:41 Running tests...
Mar 05 18:29:41 ----------------------------------------------------------------------
Mar 05 18:29:41 .s.s.s/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/__init__.py:12: UserWarning: torch.nn.parallel.DistributedDataParallelCPU is deprecated, please use torch.nn.parallel.DistributedDataParallel instead.
Mar 05 18:29:41   warnings.warn("torch.nn.parallel.DistributedDataParallelCPU is deprecated, "
Mar 05 18:29:41 .ssss/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/__init__.py:12: UserWarning: torch.nn.parallel.DistributedDataParallelCPU is deprecated, please use torch.nn.parallel.DistributedDataParallel instead.
Mar 05 18:29:41   warnings.warn("torch.nn.parallel.DistributedDataParallelCPU is deprecated, "
Mar 05 18:29:41 .ssss/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/__init__.py:12: UserWarning: torch.nn.parallel.DistributedDataParallelCPU is deprecated, please use torch.nn.parallel.DistributedDataParallel instead.
Mar 05 18:29:41   warnings.warn("torch.nn.parallel.DistributedDataParallelCPU is deprecated, "
Mar 05 18:29:45 .ssss.....ssssssssss.sssss.....ssssssssssssssssssssssssss.sssssssssssss..............................sss.....ssssss.sss.s..ss[c166838e93d5:28044] 2 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
Mar 05 18:29:45 [c166838e93d5:28044] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Mar 05 18:29:47 ..ss.s..ssssss.ssssss..ss.s========== BACKEDN is  mpi --- [0, 1, 2]
Mar 05 18:29:47 ========== BACKEDN is  mpi --- [0, 1, 2]
Mar 05 18:29:47 ========== BACKEDN is  mpi --- [0, 1, 2]
Mar 05 18:29:49 ....s.s.s................................................................s..ss....s..ss.....................ssssss
Mar 05 18:29:49 ----------------------------------------------------------------------
Mar 05 18:29:49 Ran 94 tests in 8.824s
```

But now, on master, it becomes:

```
Nov 05 02:21:49 Running distributed tests for the mpi backendwith file init_method
Nov 05 02:21:49 Executing ['mpiexec', '-n', '3', '--noprefix', '/opt/conda/bin/python', 'distributed/test_distributed_fork.py', '--verbose'] ... [2020-11-05 02:21:49.473509]
...
Nov 05 02:21:50 Fail to import hypothesis in common_utils, tests are not derandomized
Nov 05 02:21:50 Fail to import hypothesis in common_utils, tests are not derandomized
Nov 05 02:21:50 --------------------------------------------------------------------------
Nov 05 02:21:50 [[56905,1],1]: A high-performance Open MPI point-to-point messaging module
Nov 05 02:21:50 was unable to find any relevant network interfaces:
Nov 05 02:21:50 
Nov 05 02:21:50 Module: OpenFabrics (openib)
Nov 05 02:21:50   Host: a0087b42cda0
Nov 05 02:21:50 
Nov 05 02:21:50 Another transport will be used instead, although this may result in
Nov 05 02:21:50 lower performance.
Nov 05 02:21:50 --------------------------------------------------------------------------
Nov 05 02:21:50 Fail to import hypothesis in common_utils, tests are not derandomized
Nov 05 02:21:50 Test results will be stored in test-reports/dist-mpi
Nov 05 02:21:50 Test results will be stored in test-reports/dist-mpi
Nov 05 02:21:50 Test results will be stored in test-reports/dist-mpi
Nov 05 02:21:50 
Nov 05 02:21:50 Running tests...
Nov 05 02:21:50 ----------------------------------------------------------------------
Nov 05 02:21:50 
Nov 05 02:21:50 ----------------------------------------------------------------------
Nov 05 02:21:50 Ran 0 tests in 0.000s
```

One thing I noticed is that `pytorch_linux_xenial_cuda10_1_cudnn7_py3_nogpu_test` no longer exist. Not sure if that is the only test env that properly configured MPI. 

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @mruberry @VitalyFedyunin @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by mrshenli** [comment]
No, it's not because of removal of `pytorch_linux_xenial_cuda10_1_cudnn7_py3_nogpu_test`. I confirm that previously, MPI tests also run on `pytorch_linux_xenial_cuda10_1_cudnn7_py3_multigpu_test `, but it  current multigpu tests no long run it. 

old multigpu: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4706074/output/105/0?file=true&allocation-id=5e613de8c3ed4d39e226de10-0-build%2F41F2682E

new multigpu: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/8713761/output/107/0?file=true&allocation-id=5fa35f6e6451f02a588263f3-0-build%2F2694EBD2

**Comment by walterddr** [comment]
looks like there were no Open MPI tests in multi-gpu CI job until https://github.com/pytorch/pytorch/commit/35a35c349826667085c9b2cbb5e30bf6c06f34c2 turned it back on (and hence the message `Ran 0 tests`). 

See: https://circleci.com/api/v1.1/project/github/pytorch/pytorch/8342237/output/107/0?file=true&allocation-id=5f8f0e469b9288123e041316-0-build%2F2F19B8E9 vs 
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/8342203/output/107/0?file=true&allocation-id=5f8f0d5322412167cb38aa10-0-build%2F21DBF32F

**Comment by agolynski** [comment]
@walterddr Seems like https://github.com/pytorch/pytorch/pull/46569 didn't help with running MPI OSS tests as 
```
A high-performance Open MPI point-to-point messaging module was unable to find any relevant network interfaces:
Module: OpenFabrics (openib)
Host: 2e58d026a99f
```
So the problem is in AWS/CI hardware? How can we fix this?

**Comment by walterddr** [comment]
what I actually meant was the MPI test was completely removed for multigpu test some time between Mar. & Oct. and the only reason we've been seeing "Ran 0 tests" log is because of #46569 - this indicates that it might've been turned off intentially.

@mrshenli do you have an expected list of tests that should've been run - we can probably look into reenabling them instead of troubleshooting/back-tracking the commit log?

**Comment by mrshenli** [comment]
Hey @walterddr 

Looks like all tests using `pytorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_build` used to have `/usr/bin/mpiexec` and hence triggered MPI tests. Please see the workflow below. 

https://app.circleci.com/pipelines/github/pytorch/pytorch/135559/workflows/e2faefde-444b-4437-aaf4-d024525a7201

The complete test list back in march contains:

1. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_gcc7_test`
2. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_multigpu_test`
3. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_nogpu_test`
4. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_slow_test`
5. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_NO_AVX_NO_AVX2_test`
6. `pytorch_linux_xenial_cuda10_1_cudnn7_py3_NO_AVX2_test`

If possible shall we enable MPI in all Linux tests?
