### ISSUE TITLE
Make `torch.distributed.launch.py` search for a free port for TCPStore

### ISSUE THREAD

**Issue by nlgranger** [pytorch/pytorch#47461]
## 🚀 Feature

Make `torch.distributed.launch.py` `--master_port` argument use a free port unless specified explicitly.

## Motivation

Currently torch.distributed.launch uses the value 29500 as default port value for the TCP store:

https://github.com/pytorch/pytorch/blob/ccb79f3ac7b9d53297ef01bebefbe28e5c5c874c/torch/distributed/launch.py#L174

this causes issues in multi-user situations, where "Address already in use" errors will occur when a second experiment starts.

## Pitch

A random free port should be chosen automatically so that users don't have to look for one.

## Alternatives

Probe for the free port in `dist.init_process_group`.

## Additional context

I suggest making the argument optional and probing for a free port using [find_free_port](
https://github.com/pytorch/pytorch/blob/373246733d05b978eb29426c7b24132d4caf8793/torch/testing/_internal/common_utils.py#L1381) when unspecified.

https://github.com/NVIDIA/tacotron2/issues/181
https://github.com/PyTorchLightning/pytorch-lightning/issues/2081

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by pritamdamania87** [comment]
The tricky part here is that the TCPStore is actually used for co-ordination between the master and the rest of the workers. If we use a randomly available free port for the TCPStore, how do we actually communicate this to other workers since the only mechanism of co-ordination is the Store and it hasn't been initialized yet.

**Comment by nlgranger** [comment]
Good point, I opened this issue in the context of single-node multi-gpu usage which covers virtually all of our workload here. The random port search suggestion only applies to that case indeed.

**Comment by rohan-varma** [comment]
If your use case is single node, is it possible to use `file://` init over TCP initialization? You can find docs on how to set up file init here: https://pytorch.org/docs/stable/distributed.html#initialization

**Comment by nlgranger** [comment]
Yes indeed, I missed that one. I will close this issue and simply update the documentation for our cluster users about this.
