### ISSUE TITLE
torch.jit.script cannot index a ModuleList with an int returned from range()

### ISSUE THREAD

**Issue by david-macleod** [pytorch/pytorch#47496]
## 🐛 Bug

When passing an int returned from `range()` as an index to a `torch.nn.ModuleList` I receive the following error from `torch.jit.script`
```
Expected integer literal for index. ModuleList/Sequential indexing is only supported with integer literals. Enumeration is supported, e.g. 'for index, v in enumerate(self): ...':
```
## To Reproduce
```py
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x, n_layers: int):
        for i in range(n_layers):
            x = self.layers[i](x)
        return x

torch.jit.script(Model())
```

## Expected behavior

That `nn.ModuleList` will accept an int as index, as suggested by the error message.

## Environment

```
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 440.100
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-memlab==0.2.2
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.1
[conda] Could not collect
```

## Additional context

I have also tried replacing range with torch.range but with no success

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
I think this is same issue as #43737, which was recently fixed in #45716. So if you build PyTorch from latest source or use a recent nightly build, you should be able to get it working. Note that it does require some code modification though, you can refer to the test cases in aforementioned PR as examples.

**Comment by SplitInfinity** [comment]
In general, you can only index into `ModuleDict` with an index that can be determined at compile time. Given that `n_layers` is passed in at runtime, this is not possible for your use case.

However, as of #45716, you can index into a `ModuleDict` with an arbitrary index if you can annotate the type of the left-hand side with a module interface type.

**Comment by david-macleod** [comment]
Ok thanks! Do we think #45716 will make it into 1.7.1 release?

Based on your answer I am little confused as why the following does not work, as in this case the index can be determined at compile time

```python
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x):
        i = 1
        x = self.layers[i](x)
        return x

torch.jit.script(Model())
```

In a more general sense, is there a nicer way of only iterating through a subset of a ModuleList via TorchScript, or is #45716 really the only solution? For example, neither of the following works:

```py
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x, n_layers: int):
        for i, l in enumerate(self.layers):
            x = l(x)
            if i == n_layers:
                break
        return x

torch.jit.script(Model())
```
or
```py
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x, n_layers: int):
        for l in self.layers[:n_layers]:
            x = l(x)
        return x

torch.jit.script(Model())
```

**Comment by david-macleod** [comment]
Also, is this the solution for my example based on #45716?
```python
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x, n_layers: int):
        for i in range(n_layers):
            layer: torch.nn.Linear = self.layers[i]
            x = layer(x)
        return x

torch.jit.script(Model())
```

**Comment by SplitInfinity** [comment]
I was not specific enough in my last comment - the index has to be a compile time literal.

**Comment by SplitInfinity** [comment]
> Also, is this the solution for my example based on #45716?
> 
> ```python
> class Model(torch.nn.Module):
> 
>     def __init__(self):
>         super().__init__()
>         self.layers = torch.nn.ModuleList([
>             torch.nn.Linear(32, 32),
>             torch.nn.Linear(32, 32)
>         ])
> 
>     def forward(self, x, n_layers: int):
>         for i in range(n_layers):
>             layer: torch.nn.Linear = self.layers[i]
>             x = layer(x)
>         return x
> 
> torch.jit.script(Model())
> ```

Not quite - I think you would have to define a new interface type using `@torch.jit.interface` and use that as an annotation instead of `torch.nn.Linear`. Also, the linked PR only makes this indexing syntax possible for `ModuleDict`, but it is easily extendable to `ModuleList`. It wouldn't work out of the box even if you did define an interface type.

**Comment by david-macleod** [comment]
Thanks for your help, I can confirm the `ModuleDict` + interface solution works, although in the end I went for something which allowed me to keep using `ModuleList`

```py
for idx, module in my_module_list:
    if idx < my_limit:
        x = module(x)
    else:
        pass
```
 Seems to get round the limitation of not being able to use `break`, and cheap for the case where `len(my_module_list)` is relatively small.

Given that the issue here seems to be that we cannot determine the returned type at compiled time when indexing a `ModuleList`, could there be scope in future for annotating the module type in the special case where the items within the `ModuleList` are of fixed type. For example
```py
my_module_list: ModuleList[nn.Linear] = nn.ModuleList([nn.Linear(4,4), nn.Linear(4,4)])
```
Similar to how we can already do this with `List`. Or is that unlikely to ever happen given that `ModuleList` always allows multiple subtypes? Any thoughts @gmagogsfm @SplitInfinity

**Comment by SplitInfinity** [comment]
> Or is that unlikely to ever happen given that ModuleList always allows multiple subtypes?

Precisely. The inline annotation with an interface type during indexing is the next best thing.

**Comment by david-macleod** [comment]
Thanks!

**Comment by gilevir** [comment]
@SplitInfinity Is there an ETA (or an open PR ?) concerning the aforementioned inline notation that we could use for ModuleList indexing ?
Thanks

**Comment by gilevir** [comment]
@david-macleod 

> I can confirm the `ModuleDict` + interface solution works

Can you share how you ended up making the `ModuleDict` indexing working ?
In my case the following snippet in the `forward` method of my model can't be scripted :
```
for j in range(8):
    conv1: ModuleInterface = self.convs[j]
    conv2: ModuleInterface = self.convs[str(j*2+1)]
```

Throwing an error : `Unable to extract string literal index. ModuleDict indexing is only supported with string literals`

**Comment by SplitInfinity** [comment]
@gilevir 

Take a look at `test/jit/test_module_interface.py` and `test/jit/test_module_containers.py` (specifically `test_typed_module_dict`) to see how to use module interfaces and non-literal indexing. I'm also working on a PR today to enable this feature for `ModuleList`. It should be posted by EOD.

**Comment by SplitInfinity** [comment]
As promised, but two days late 🙃 🔫 : #53410

**Comment by ppwwyyxx** [comment]
Dynamic non-literal indexing solves a larger scope of problem but comes with more constraints on types. I wonder whether it's possible to easily support "constant but non-literal" indexing like the example above in https://github.com/pytorch/pytorch/issues/47496#issuecomment-726151059:
```python
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 32)
        ])

    def forward(self, x):
        i = 1
        x = self.layers[i](x)   # failed
        return x
```
This should in theory add no constraints to types because `x = self.layers[1](x)` can compile out-of-the-box without forcing `layers` to have the same type.

Having this would cover many cases of non-literal indexing, since we can then use indices from unrolled loops, e.g.:
```python
class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.ModuleList([nn.Linear(10, 10)] * 3)
        self.z = tuple([0, 1, 2])

    def forward(self, x):
        x = self.layers[0](x)
        for a in self.z[1:]:
            x = self.layers[a](x)
        return x
```

**Comment by Ali-arch808** [comment]
Hello,
I'm facing the same issue. I read through the comments but I cannot understand the solutions. Can anyone help? 
Here is the code(I removed most of the code in __init__  function to avoid verbosity):
(spec.matrix is a square matrix that its shape is not predetermined.)
```
class Cell(nn.Module):

    def __init__(self, spec, in_channels, out_channels):
        super(Cell, self).__init__()
        self.spec = spec
        self.num_vertices = self.spec.matrix.shape[0]

        # vertex_channels[i] = number of output channels of vertex i
        self.vertex_channels = ComputeVertexChannels(in_channels, out_channels, self.spec.matrix)
        


    def forward(self, x: Any) -> Any:
        tensors = [x]

        out_concat = []

        for t in range(1, self.num_vertices - 1):

            fan_in = []
            for  src in range(1, t):
                if self.spec.matrix[src, t]:
                    fan_in.append(Truncate(tensors[src], torch.tensor(self.vertex_channels[t])))

            if self.spec.matrix[0, t]:
                fan_in.append(self.input_op[t](x))

            # perform operation on node

            vertex_input = sum(fan_in)
            vertex_output = self.vertex_op[t](vertex_input)

            tensors.append(vertex_output)
            if self.spec.matrix[t, self.num_vertices - 1]:
                out_concat.append(tensors[t])

        if not out_concat:
            assert self.spec.matrix[0, self.num_vertices - 1]
            outputs = self.input_op[self.num_vertices - 1](tensors[0])
        else:
            if len(out_concat) == 1:
                outputs = out_concat[0]
            else:
                outputs = torch.cat(out_concat, 1)

            if self.spec.matrix[0, self.num_vertices - 1]:
                outputs += self.input_op[self.num_vertices - 1](tensors[0])


        return outputs

def Truncate(inputs, channels):
    """Slice the inputs to channels if necessary."""
    input_channels = inputs.size()[1]
    if input_channels < channels:
        raise ValueError('input channel < output channels for truncate')
    elif input_channels == channels:
        return inputs  # No truncation necessary
    else:
        # Truncation should only be necessary when channel division leads to
        # vertices with +1 channels. The input vertex should always be projected to
        # the minimum channel count.
        assert input_channels - channels == 1
        return inputs[:, :channels, :, :]
```
It returns the following RuntimeError:
```
Truncate(Tensor inputs, Tensor channels) -> (Tensor):
Expected a value of type 'Tensor (inferred)' for argument 'inputs' but instead found type 'Any'.
Inferred 'inputs' to be of type 'Tensor' because it was not annotated with an explicit type.:
  File "model.py", line 136
            for  src in range(1, t):
                if self.spec.matrix[src, t]:
                    fan_in.append(Truncate(tensors[src], torch.tensor(self.vertex_channels[t])))
                                  ~~~~~~~~ <--- HERE
    
            if self.spec.matrix[0, t]:
```
As error declares, I should annotate the input in tensors. However, doing that will result in `RuntimeError:Expected integer literal for index ...`.
As I understood from [this post](https://github.com/pytorch/pytorch/issues/47496#issuecomment-789969702) 
I tried adding `@ torch.jit.interface` before the `class Cell(nn.Module)`. It returned `RuntimeError:interface declarations must have a return type annotated.` and it underlines all the lines in the __init__ function.
Thank you in advance for any guidance.

**Comment by Jackiexiao** [comment]
FYI, according to https://github.com/pytorch/pytorch/issues/47496#issuecomment-789969702

I manage to solve my problem

before
```python
....
        self.upsamples = torch.nn.ModuleList()
...
                self.upsamples += [
                    torch.nn.Sequential(
....
Class ...
...
    def forward(self, c):
        ....
        for i in range(self.num_upsamples):
            c = self.upsamples[i](c)
```
raise Exception: `Expected integer literal for index. ModuleList/Sequential indexing is only supported with integer literals. Enumeration is supported, e.g. 'for index, v in enumerate(self): ...':` at `c = self.upsamples[i](c)`

after

```python
# add ModuleInterface 
@torch.jit.interface
class ModuleInterface(torch.nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor: # `input` has a same name in Sequential forward
        pass
....
Class ...
...
    def forward(self, c):
        for i in range(self.num_upsamples):
            # c = self.upsamples[i](c) # Expected integer literal for index.xxx 
            submodule: ModuleInterface = self.upsamples[i]
            c = submodule.forward(c)
```

**Comment by rabeehk** [comment]
I am trying with this example, and it fails getting `TypeError: <class '__main__.ModuleInterface'> is a built-in class`, could you please add one minimal working example?

```
from torch.nn import ModuleList
import torch 

@torch.jit.interface
class ModuleInterface(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(32, 32)
        
    def forward(self, input: torch.Tensor) -> torch.Tensor: # `input` has a same name in Sequential forward
        return self.linear(input)


class Mine(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # self.layers = torch.nn.ModuleList()
        self.layers: ModuleList[ModuleInterface] = torch.nn.ModuleList([
            ModuleInterface(),
            ModuleInterface(),
        ])

    def forward(self, x, c):
        for i in range(c):
            submodule: ModuleInterface = self.layers[i]
            result = submodule.forward(x)
            return result 
```

**Comment by Jackiexiao** [comment]
not tested yet, but should work
```python
from torch.nn import ModuleList
import torch 

@torch.jit.interface
class ModuleInterface(torch.nn.Module):
    def forward(self, input: torch.Tensor) -> torch.Tensor: # `input` has a same name in Sequential forward
        pass

class Mine(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([torch.nn.Linear(32, 32), torch.nn.Linear(32, 32)])

    def forward(self, x, c):
        for i in range(c):
            submodule: ModuleInterface = self.layers[i]
            result = submodule.forward(x)
            return result 
```

**Comment by rabeehk** [comment]
Hi @jackiexiao I tested it and it does not work for me <class '__main__.ModuleInterface'> is a built-in class

**Comment by Jackiexiao** [comment]
@rabeehk I add type to forward function, test pass. torch.__version__ '1.12.1+cu102'

**Comment by rabeehk** [comment]
@Jackiexiao I have types added, about torch.version '1.12.1+cu102' I am running on something like jupyter notebook and I could not be able to change the torch version. could you share me a complete test?

**Comment by Jackiexiao** [comment]
it's already a minimal example. your issue related to https://github.com/pytorch/pytorch/issues/28258 , if you just run from terminal, like `python your_export_script.py`, it works fine.
