### ISSUE TITLE
diagflat not implemented for Complex type

### ISSUE THREAD

**Issue by rjkilpatrick** [pytorch/pytorch#47499]
## 🐛 Bug

[`torch.diagflat`](https://pytorch.org/docs/master/generated/torch.diagflat.html) isn't implemented for complex types (`torch.complex32`, `torch.complex64`, `torch.complex128`).
This holds for CPU and CUDA.

## To Reproduce

``` python
>>> import torch
>>> a = torch.ones(1, dtype=torch.complex128)
>>> torch.diagflat(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "diag" not implemented for 'ComplexDouble'

# CUDA
>>> b = a.cuda()
>>> torch.diagflat(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "diag_cuda" not implemented for 'ComplexDouble'
```

## Expected behaviour

- For a 1D Tensor, creates a (Complex) Tensor with the input elements on the diagonal (zeros elsewhere).
- For >1D, flattens to 1D and creates a Tensor with input elements on the diagonal. Analogous to `torch.diagflat(x.flatten())`.

## Environment

 - PyTorch Version (e.g., 1.0): torch-1.8.0.dev20201105
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip nightly
 - Build command you used (if compiling from source):
 - Python version: v3.8.5
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GTX 970
 - Any other relevant information:

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @rjkilpatrick. We would accept a PR adding complex support.

**Comment by rjkilpatrick** [comment]
PR in progress @ <https://github.com/rjkilpatrick/pytorch/tree/fix-diagflat-complex-support>.
Currently working on CUDA kernel for `diagflat_cuda`.
