### ISSUE TITLE
Cpp Extension Plan

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#4750]
Create PyTorch/PyTorch.h
  - https://gist.github.com/zdevito/138b0111fc88ef44840d6ce18231bb36
  - pybind11 headers
  - ATen headers
  - PyTorch's pybind11 headers. 'pybind.h' 
     (for python Variable and python Tensor <-> at::Tensor)
  - edit pytorch/setup.py to _install the headers_ required in PyTorch.h
  - make torch.cpp_extensions.include_path() work
  - debug the example until it works to create a cpp extension guide
  
  
Follow Up:
- handle the cpp build as a jit
```
example = torch.cpp_extension.load(['a.cpp', 'b.cpp'])
     # make ninja build files for compilation unit
     # run build files, which will pick up ninja cache 
  
```
- how to write a new ATen operator and contribute it

**Comment by zdevito** [comment]
@goldsborough

**Comment by ezyang** [comment]
> how to write a new ATen operator and contribute it

Operators that shows up in `Declarations.yaml`? I thought this was Hard(TM)

**Comment by zdevito** [comment]
For now, we just want a guide for how to create the PR to aten that adds it. Externally registered operators is still a separate task that is Hard.

**Comment by ezyang** [comment]
Fixed now by @goldsborough
