### ISSUE TITLE
torch.utils.data.Dataset has error when the subclass call __getitem__

### ISSUE THREAD

**Issue by ploirliu** [pytorch/pytorch#47555]
## To Reproduce

code is kind of like bellow:

    from torch.utils.data import Dataset, DataLoader
    import torch
    import numpy as np
    
    
    class TmpDataSet(Dataset):
        def __init__(self, now_size):
            self.now_size = now_size
    
        def __getitem__(self, index):
            print('find:', index, '  all:', self.now_size)
            out = np.array([1, 2])
            return out
    
        def __len__(self):
            return self.now_size
    
    
    if __name__ == "__main__":
        a = TmpDataSet(10)
        for i, j in enumerate(a):
            print(i)
            print(j)
        exit()

## Expected behavior

  find: 0   all: 10
  0
  [1 2]
  find: 1   all: 10
  1
  [1 2]
  find: 2   all: 10
  2
  [1 2]
  find: 3   all: 10
  3
  [1 2]
  find: 4   all: 10
  4
  [1 2]
  find: 5   all: 10
  5
  [1 2]
  find: 6   all: 10
  6
  [1 2]
  find: 7   all: 10
  7
  [1 2]
  find: 8   all: 10
  8
  [1 2]
  find: 9   all: 10
  9
  [1 2]
  find: 10   all: 10
  10
  [1 2]
  find: 11   all: 10
  11
  [1 2]
  find: 12   all: 10
  12
  [1 2]
  find: 13   all: 10
  13
  [1 2]
  find: 14   all: 10
  14
  [1 2]
  find: 15   all: 10

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.5.1
 - OS (e.g., Linux):Window10
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version:3.7
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:1080Ti
 - Any other relevant information:numpy version 1.19.2

**Comment by mariosasko** [comment]
Everything behaves as expected. Please provide more info about the error.

**Comment by SsnL** [comment]
see https://github.com/pytorch/pytorch/issues/45040
