### ISSUE TITLE
Best way to handle iterative datasets in pytorch with support for distributed sampling

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/pytorch#47559]
Hi,
I have some large-scale datasets in iterative format, then I want to use them in pytorch data loaders, with distributed training across TPUs, and multiple GPUs, could you assist me with what is the efficient way to do it? code snippet are appreciated. thanks. I basically need DistributedSampler to be able to divide an iterative data across the TPU cores. Could you assist me how this can be done with iterative datasets.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment]
Hi, please use the forums https://discuss.pytorch.org/ for general questions/how-to's. Thank you!
