### ISSUE TITLE
Cannot set 0 annealing epochs in SWALR

### ISSUE THREAD

**Issue by Daniil-Osokin** [pytorch/pytorch#47578]
## 🐛 Bug

[Introduced](https://pytorch.org/blog/pytorch-1.6-now-includes-stochastic-weight-averaging/) in PyTorch 1.6 Stochastic Weight Averaging technique proposes to average neural network weights obtained at relatively high learning rate for better generalization. The [original paper](https://arxiv.org/pdf/1803.05407.pdf) and snippets [[1](https://pytorch.org/blog/pytorch-1.6-now-includes-stochastic-weight-averaging/), [2](https://pytorch.org/docs/stable/optim.html)] in PyTorch documentation assume averaging weights obtained at the same learning rate (please see the left image). However this cannot be reproduced with the current implementation of `SWALR` scheduler, it does not allow to set 0 annealing epochs. The actual behavior using snippets from the PyTorch documentation is shown in the right image below:
![documented_vs_real_swa_behavior](https://user-images.githubusercontent.com/2491976/98466997-07ad7380-21e4-11eb-823d-0171f809ef5a.png)

## To Reproduce

```
from torch.optim.adam import Adam
from torch.optim.swa_utils import SWALR
from torchvision.models import resnet18

model = resnet18()
optimizer = Adam(model.parameters())
swa_scheduler = SWALR(optimizer, swa_lr=1e-4, anneal_epochs=0)
```
Fails with the error:
```
File "/home/venv/lib/python3.6/site-packages/torch/optim/swa_utils.py", line 224, in __init__
  anneal_epochs)) 
ValueError: anneal_epochs must be a positive integer, got 0
```

## Expected behavior

`SWALR` accepts 0 anneal epochs.

## Environment

 - PyTorch Version: 1.6.0 and above.

## Additional context

Discussion in #41228.

cc @vincentqb

**Comment by heitorschueroff** [comment]
As discussed in #41228, this is a great enhancement and we would accept a PR that implements this.

**Comment by Daniil-Osokin** [comment]
Thanks for the warm response!
