### ISSUE TITLE
multi_head_attention_forward: add option to return attention scores for all heads instead of averaging

### ISSUE THREAD

**Issue by MarcCoru** [pytorch/pytorch#47583]
## 🚀 Feature: Return the attention scores from all heads

Return the attention scores from all heads in the [`MultiHeadAttention`](https://github.com/pytorch/pytorch/blob/b5dd6e3e61c59e88ce6e8aee2fa5d08d6c56fd97/torch/nn/modules/activation.py#L831
) Module and [`multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4026
). The current implementation **only** allows returning the averaged attention score over all heads 

In short: add option to change
https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4309
into
`return attn_output, attn_output_weights`

## Motivation

The motivating idea behind Multi-Head attention is to perform the attention mechanism in parallel and allow the model to attend to different sequence elements with each head separately. The current torch code ([`MultiHeadAttention`](https://github.com/pytorch/pytorch/blob/b5dd6e3e61c59e88ce6e8aee2fa5d08d6c56fd97/torch/nn/modules/activation.py#L831
) Module and [`multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4026
)) allows to return the `attn_output_weights` along with the `attn_output`. 

However, the `attn_output_weights` are averaged over all heads.  The attention scores for each separate head are not accessible to the outside.

Why should it be possible to get attention scores for each head?

1) Each head attends to different sequence elements. The information to which sequence elements each head attends to is lost when attention scores are averaged over all heads. The attention scores for each head are important to understand the features that are extracted in each layer (touches: feature importance, explainability).
2) This averaging behavior in `attn_output_weights` is inconsistent with `attn_output` where the embedding dimensions are grouped into `head_dim` blocks from the same attention head. 
https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4124

## Pitch

I would propose 
1) modifying the `need_weights=True` option in [`multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4026
) to a choice [`all`, `average`, `none`] to control the return behavior of `multi_head_attention_forward`. The option `need_weights=avg` would be equivalent to current `need_weights=True` and `need_weights=all` would return `attn_output_weights` without summation and average with `num_heads` [here](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4309). Alternatives like changing the current behavior or adding a second boolean `need_all_weights` flag are possible too.
2) carrying the `need_weights` option to the [`MultiHeadAttention`](https://github.com/pytorch/pytorch/blob/b5dd6e3e61c59e88ce6e8aee2fa5d08d6c56fd97/torch/nn/modules/activation.py#L831
) Module to make it easily accessible to the outside when using the `MultiHeadAttention` module. 

I am happy to write a pull request with the modifications in [`multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4026
) and [`MultiHeadAttention`](https://github.com/pytorch/pytorch/blob/b5dd6e3e61c59e88ce6e8aee2fa5d08d6c56fd97/torch/nn/modules/activation.py#L831
) Module according to further discussion or to leave the concrete implementation choices to the maintainers.

Overall, it would be great to have this option in the PyTorch code. This would make the code mode cleaner and would allow understanding the different head behaviors without having to locally modify the pytorch functions.

## Alternatives

Current alternatives are:
1) creating multiple MultiHeadAttention modules hardcoded with a single head to retrieve the attention scores of this head (probably less efficient)
2) copying and modifying the [`multi_head_attention_forward`](https://github.com/pytorch/pytorch/blob/16c72a5a6b7085a9651e7bef7e98c80b2d5547e9/torch/nn/functional.py#L4026
) function and [`MultiHeadAttention`](https://github.com/pytorch/pytorch/blob/b5dd6e3e61c59e88ce6e8aee2fa5d08d6c56fd97/torch/nn/modules/activation.py#L831
) Module locally.

cc @albanD @mruberry @zhangguanheng66

**Comment by zhangguanheng66** [comment]
In addition to MHA in pytorch, we have a new MHA container in torchtext, which returns non-averaging attention weights. See [here](https://github.com/pytorch/text/blob/9ebfb7b746999cff8df562704e5366a902df759f/torchtext/nn/modules/multiheadattention.py#L191-L198).

**Comment by MarcCoru** [comment]
Yes, #34537 seems to propose the same feature. 

Apologies. I didn't follow up on the torchtext suggestion on this issue. I ended up using the workaround using multiple MultiHeadAttention modules that worked reasonably well for my small-scale experiments. It would be still easier if the standard MHD would return the attention for each head separately.

**Comment by jbschlosser** [comment]
We'd accept a PR adding an option to return per-head attention weights instead of averaged.

For bikeshed purposes, I'll propose a new MHA flag with the name `average_attn_weights=True`, and the state of the flag should have no effect when `need_weights=False`. @ngimel @cpuhrsch @bhosmer any opinions on the name before the issue gets addressed?
