### ISSUE TITLE
typing no longer needed

### ISSUE THREAD

**Issue by cdeepali** [pytorch/pytorch#47596]
As the minimum required python version is `3.6.2`, `typing` module is no longer needed. 

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by malfet** [comment]
@cdeepali can you please explain in a bit more details what do you mean?

**Comment by rgommers** [comment]
Probably that there are some `.yml` and `.sh` files under `.circleci/` that still have `typing` in install commands? That could be cleaned up.

The `builder` repo doesn't contain `typing` anymore.

**Comment by cdeepali** [comment]
Yes and I think we can remove the check at - https://github.com/pytorch/pytorch/blob/master/setup.py#L311. I have raised PR for it.

**Comment by malfet** [comment]
@cdeepali thank you for your PR. Please move it from draft state or I'll review it. Alternative I've just published https://github.com/pytorch/pytorch/pull/47677

**Comment by cdeepali** [comment]
I have closed my PR, you may please merge yours as it covers this fix. Thanks for adding it.
