### ISSUE TITLE
nn.Parameter not showing up in model.parameters but it is getting trained.

### ISSUE THREAD

**Issue by plstory** [pytorch/pytorch#4761]
I define both a bias parameter and some other module in MyModule, the bias parameter doesn't show up in model.parameters. However, I can see its value in list(model.parameters()). Furthermore, after a few training iterations, the value of the bias parameter does change, indicating that it's indeed part of the model parameters. Note: MyModule is also a submodule constructed as a ModuleList in some other module TopModule.

`class MyModule(nn.Module):`
`    def __init__(self, state_len):`
        `self.bias = nn.Parameter(torch.ones(state_len))`
       ` self.m = AnotherModule(state_len)`
   ` def forward(input):`
        `some calculations that uses bias`

let `model=TopModule()`,`model.parameters` returns 
`
<bound method TopModule.parameters of TopModule(
  blah
  blah
  (layers): ModuleList (
    (0): MyModule (
      (m): AnotherModule(
        (layers): ModuleList (
          (0): Linear (192 -> 128)
          (1): Linear (128 -> 64)
        )
      )
    )
  )
)>
`
as you see, the bias parameter is missing. 
But if I define `l=list(model.layers[0].parameters())`
`l[0]` is in fact the bias parameter as it prints all 1s before any training.

**Comment by apaszke** [comment]
It's all expected. If you want to see all parameters do `list(model.parameters())`. Parameters aren't included in the string representation of a module (which is what you're referring to) - only submodules are.
