### ISSUE TITLE
DISABLED test_broadcast_cuda (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#47645]
Started to fail pretty consistently sometime after https://github.com/pytorch/pytorch/tree/4a2fb3404215c774fdf2805ba8d495bb7dc1bbbf 
https://app.circleci.com/pipelines/github/pytorch/pytorch/236917/workflows/7f73ea98-2cfa-4a7c-b26e-2eaca2661f34/jobs/8801912/steps

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
fork() is gone
