### ISSUE TITLE
DISABLED test_nccl_high_priority_stream (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#47646]
Started to fail very frequently sometime after  https://github.com/pytorch/pytorch/tree/4a2fb3404215c774fdf2805ba8d495bb7dc1bbbf

See https://app.circleci.com/pipelines/github/pytorch/pytorch/236917/workflows/7f73ea98-2cfa-4a7c-b26e-2eaca2661f34/jobs/8801912/steps

Nov 10 01:20:07 ======================================================================
Nov 10 01:20:07 ERROR [3.645s]: test_nccl_high_priority_stream (__main__.TestDistBackendWithFork)
Nov 10 01:20:07 ----------------------------------------------------------------------
Nov 10 01:20:07 Traceback (most recent call last):
Nov 10 01:20:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 278, in wrapper
Nov 10 01:20:07     self._join_processes(fn)
Nov 10 01:20:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 395, in _join_processes
Nov 10 01:20:07     self._check_return_codes(elapsed_time)
Nov 10 01:20:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 431, in _check_return_codes
Nov 10 01:20:07     raise RuntimeError(error)
Nov 10 01:20:07 RuntimeError: Processes 1 exited with error code 10

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by SciPioneer** [comment]
@malfet  Did you find it was only flaky on CI?

I ran `pytest -k test_nccl_high_priority_stream test/distributed/test_distributed_fork.py` on devgpu 20 times, and the test didn't fail a single time.
