### ISSUE TITLE
Sparse return type for `torch.diagflat`

### ISSUE THREAD

**Issue by rjkilpatrick** [pytorch/pytorch#47640]
## 🚀 Feature

Allow `torch.diagflat` to create sparse tensors.

## Motivation

`torch.diagflat` will return a Tensor that is sparse, but stored as a dense Tensor.
It takes up a large amount of memory just to store, and for _most_ use cases of creating a diagonal matrix, it will stay mainly diagonal.

Having the option of creating the sparse Tensor should speed up computation for large Tensors, whilst not breaking existing code. In my research, this has led to some CUDA out of memory errors that `torch.sparse_coo_tensor` avoided.

## Pitch

Change `torch.diagflat` function signature to:
``` python
 torch.diagflat(input, offset=0, sparse=False) → Tensor
```
This argument name could be `layout` for consistency with the [sparse docs](https://pytorch.org/docs/stable/sparse.html), but I think this would be confusing as you might think you're declaring row/column-major here instead.

## Alternatives

1. Create dense Tensor and make sparse, i.e. `torch.diagflat(input).to_sparse()` which may lead to out of memory errors
1. Create Tensor individually by values via generators in torch.sparse_coo_tensor` which is less practical, e.g.:
  ``` python
>>> x = torch.arange(5)
>>> torch.sparse_coo_tensor(torch.tensor([(i, i) for i in range(len(x))]).T, x)
  ```
cc: #9674

cc @aocsa @nikitaved @pearu @mruberry

**Comment by gchanan** [comment]
looks like there are equivalent functions https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.diags.html, https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.spdiags.html#scipy.sparse.spdiags, imo we should use that nomenclature instead of overloading the return type.

**Comment by mruberry** [comment]
Thanks for suggesting this feature, @rjkilpatrick. This makes sense, although we'll need to review consistency with other frameworks (like SciPy, as @gchanan suggests) and our own plans for supporting a choice of layout. I've added the "needs design" label.

**Comment by IvanYashchuk** [comment]
[`scipy.sparse.spdiags`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.spdiags.html#scipy-sparse-spdiags) stems from [Matlab's `spdiags`](https://www.mathworks.com/help/matlab/ref/spdiags.html). In Julia there's equivalent function called [`SparseArrays.spdiagm`](https://docs.julialang.org/en/v1/stdlib/SparseArrays/#SparseArrays.spdiagm).

[`scipy.sparse.diags`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.diags.html#scipy-sparse-diags) functionality seem to be available only in SciPy, the difference between the two is in the expected form of diagonals: `diags` expects a sequence of arrays, while `spdiag` expect an array that holds the diagonals.

In PyTorch we can implement both functions as `torch.sparse.spdiags` and `torch.sparse.diags`, given popularity of the `spdiags` version I think we should focus on that variant first.

The signature would be something like `torch.sparse.spdiags(Tensor diagonals, IntTensor offsets, int[] shape, Layout? layout=None) -> SparseTensor`.

**Comment by krshrimali** [comment]
Thanks, @IvanYashchuk for taking a look and sharing pointers on existing implementations in other libraries. Thanks, @rjkilpatrick for creating the issue and helpful description.

I've created a separate issue for `spdiags` and `diags` [here](https://github.com/pytorch/pytorch/issues/70926). Closing this issue in the favor of #70926 (to add functions in the sparse namespace instead of adding keywords to `diagflat`). Please feel free to share your views/comments in the new issue, in case you have any. Thank you!
