### ISSUE TITLE
[quant] Add documentation for python functions

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#47652]
Some functions are defined in the `torch` namespace, like `torch.fake_quantize_per_tensor_affine`, etc. But have no python documentation for users to understand what they do.

Filing this issue to make sure we track this and add documentation for necessary functions in v1.8

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by z-a-f** [comment]
Is there a specific list?

**Comment by supriyar** [comment]
`empty_quantized`, 
`quantized_max_pool1d`, 
`quantized_max_pool2d`, 
`fake_quantize_per_tensor_affine`, 
`fake_quantize_per_channel_affine`, 
`fake_quantize_per_channel_affine_backward`, 
`choose_qparams_optimized`, 
`quantized_lstm_cell`
`quantized_rnn_cell`
`quantized_gru_cell`
`set_quantizer_`
`quantized_batch_norm`

The list above might be missing few functions, since I manually checked and generated above list.

Apart from that functions like `fbgemm_linear_quantize_weight` and similar functions are also missing documentation, but I don't know if we use them anymore and should just deprecate them.

**Comment by jerryzh168** [comment]
I think quantized_xxx might be deprecated, but the others are still in use.

**Comment by supriyar** [comment]
https://github.com/pytorch/pytorch/pull/51748
