### ISSUE TITLE
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by SlowMonk** [pytorch/pytorch#47658]
```
Test: [   0/363]  Time: 0.532 (0.532)  Loss:  3.2777 (3.2777)  
Traceback (most recent call last):
  File "train.py", line 623, in <module>
    main()
  File "train.py", line 412, in main
    eval_metrics = validate(model, loader_eval, args, evaluator)
  File "train.py", line 590, in validate
    output = model(input, target)
  File "/home/jake/venv_11.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jake/Gits/efficientdet-pytorch/effdet/bench.py", line 129, in forward
    target['img_scale'], target['img_size'])
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)
```

```
rtx 3090
cuda 11.1
pytorch for cuda 11.1
```

cc @malfet @seemethere @walterddr @ngimel

**Comment by gjghks** [comment]
Hi, I got same error.

RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

my env
: rtx 3070
: cuda 11.0
: pytorch nightly

existing code does not work..

how can I fix it?

**Comment by peterjc123** [comment]
@gjghks  Since in cuda 11.0 and cuda11.1, the nvrtc library shares the same filename on Windows, you may just do a file replacement.

**Comment by gjghks** [comment]
@peterjc123 Hi, I used pytorch nightly with cuda 11.0 and meet the above problem, so as you said, if I change the nvrtc lib 11.0 -> 11.1, then it can nvrtc: error: fix it? can you describe more detail?

**Comment by peterjc123** [comment]
@gjghks I won't talk about it in details since I haven't done that before. Just giving you some insights.

**Comment by nostayup** [comment]
> ```
> Test: [   0/363]  Time: 0.532 (0.532)  Loss:  3.2777 (3.2777)  
> Traceback (most recent call last):
>   File "train.py", line 623, in <module>
>     main()
>   File "train.py", line 412, in main
>     eval_metrics = validate(model, loader_eval, args, evaluator)
>   File "train.py", line 590, in validate
>     output = model(input, target)
>   File "/home/jake/venv_11.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/jake/Gits/efficientdet-pytorch/effdet/bench.py", line 129, in forward
>     target['img_scale'], target['img_size'])
> RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)
> ```
> 
> ```
> rtx 3090
> cuda 11.1
> pytorch for cuda 11.1
> ```
> 
> cc @malfet @seemethere @walterddr @ngimel

do you solve it?i got  the same error……

**Comment by Light--** [comment]
same error here... on mxnet....

**Comment by ngimel** [comment]
This was fixed in #48151, for mxnet please file an issue with them.

**Comment by JackZhang9** [comment]
Oh,i meet the same issue,
my env:

- ubuntu 20.04
- torch 1.12.0
- CUDA 11.3
- GPU  RTX 4060 Laptop 

how can i fix it?

**Comment by PinPointPing** [comment]
Unfortunately same...

**Comment by LeedsRamseyPeng** [comment]
> Oh,i meet the same issue, my env:
> 
>     * ubuntu 20.04
> 
>     * torch 1.12.0
> 
>     * CUDA 11.3
> 
>     * GPU  RTX 4060 Laptop
> 
> 
> how can i fix it?

Have you fixed it?
