### ISSUE TITLE
Which is the suitable function for sending the tensor type from worker to server?

### ISSUE THREAD

**Issue by Nazila-H** [pytorch/pytorch#47662]
Hi everyone,
I am roughly new in PyTorch and I want to send the tensor from worker to server which functions should I use to serialize the tensor, send it to server and then deserialize it again and work with it in the tensor type again?

Thank you in advance.

**Comment by ailzhang** [comment]
torch.save? 
Btw please redirect all the questions to the pytorch forum, thanks!
