### ISSUE TITLE
Random seed with external GPU

### ISSUE THREAD

**Issue by KarolyPoka** [pytorch/pytorch#47672]
## ❓ 
I bought a new Palit **GeForce RTX 3070 GPU**, to speed up my deep learning projects. My laptop is a Dell Latitude 5491 with an Nvidia **GeForce MX130** and Intel UHD Graphics 630. I am using the GeForce RTX 3070 in a Razer Core X via Thunderbolt 3.0.

I would like to make my pytorch training reproducible, so I am using: torch.manual_seed(1) np.random.seed(1) random.seed(1) torch.cuda.manual_seed(1) torch.cuda.manual_seed_all(1) torch.backends.cudnn.deterministic = True torch.backends.cudnn.benchmark = False

Symptom: When the device=“cuda:0” its addressing the MX130, and the seeds are working, I got the same result every time. When the device=“cuda:1” its addressing the RTX 3070 and I dont get the same results. **Seems like with the external GPU the random seed is not working.** When device=“cuda” its automatically uses the RTX 3070 and no reproducibility. I am working with num_workers=0 and worker_init_fn=np.random.seed(1) in the dataloder. **So practically changing the executor GPU has effect on the random seed**. I dont want to, and I am not using both GPU-s in parallel.

How can I make the work with external GPU reproducible? I would very appreciate any help. Thanks in advance!

Pytorch version: 1.7.0 Cuda toolkit: 11.0.221 Anaconda version: 2020.07

According to NVIDIA-SMI: Cuda version: 11.1 Driver version: 457.09

**Comment by ptrblck** [comment]
Double post from the [forum](https://discuss.pytorch.org/t/random-seed-with-external-gpu/102260/2?u=ptrblck) with follow-up.

**Comment by KarolyPoka** [comment]
Thank @ptrblck_de for the tip, it solved my problem! Yes with `torch.set_deterministic(True)` I’ve got the following error:
**`RuntimeError: Deterministic behavior was enabled with either torch.set_deterministic(True) or at::Context::setDeterministic(true), but this operation is not deterministic because it uses CuBLAS and you have CUDA >= 10.2. To enable deterministic behavior in this case, you must set an environment variable before running your PyTorch application: CUBLAS_WORKSPACE_CONFIG=:4096:8 or CUBLAS_WORKSPACE_CONFIG=:16:8. For more information, go to https://docs.nvidia.com/cuda/cublas/index.html#cublasApi_reproducibility`**

So as it turned out the `CUBLAS_WORKSPACE_CONFIG=:16:8` or `CUBLAS_WORKSPACE_CONFIG=:4096:2` environment variable settings can solve the problem, and make the training reproducible if you have `CUDA >=10.2` version.

My internal MX130 probably used an older CUDA version which was not shown in the nvidia-smi, and probably that’s why it worked in that case, but not worked with the eGPU.

PS.: some pytorch layers can’t even work deterministically for example: `nn.AdaptiveAvgPool1d()` . But in my case I just had to remove the torch.set_deterministic(True) setting and there was no error and the particular layer had no effect on the deterministic results.
