### ISSUE TITLE
DISABLED test_all_reduce_sum_cuda_async (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#47676]
https://app.circleci.com/pipelines/github/pytorch/pytorch/236385/workflows/5971d606-1c83-438c-b4ce-087b5d511a41/jobs/8770125/steps

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/47898, will reopen if not

**Comment by mrshenli** [comment]
Closing to see if #48129 fixes this.
