### ISSUE TITLE
DISABLED test_reduce_multigpu (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#47675]
https://app.circleci.com/pipelines/github/pytorch/pytorch/236331/workflows/30be8dd7-d9ca-4885-9636-99209ad9a528/jobs/8767371/steps

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/47898, will reopen if not

**Comment by mrshenli** [comment]
Closing to see if #48129 fixes this.
