### ISSUE TITLE
[Feature request] torch.isnan and torch.nan

### ISSUE THREAD

**Issue by mdraw** [pytorch/pytorch#4767]
I know it's possible to check for NaN values of torch tensors by using the `numpy.isnan()` function on CPU tensors, but I think a native `torch.isnan()` function would be nice to have. I would also propose a constant `torch.nan` similar to `numpy.nan` that can be assigned (or compared) to torch tensors for testing purposes.

My main use case for this is that I want to automatically check losses for NaN values during training and warn the user or terminate training when encountering them.

**Comment by apaszke** [comment]
Regarding `torch.isnan` there is a simple trick that allows you to do the same thing (thanks to semantics of IEEE floating point arithmetic):
```python
def isnan(x):
    return x != x
```
While this trick is very simple, I've seen it being confusing quite often, so it would make sense to add it to `torch.`.

Regarding `numpy.nan` there's no reason why you have to use it - it's enough to do `float('nan')`

**Comment by samuela** [comment]
I've implemented this in [kindling](https://github.com/samuela/kindling): https://github.com/samuela/kindling/blob/master/kindling/nan_police.py. Hopefully irrelevant come version 0.4.

**Comment by mdraw** [comment]
Thanks. I am closing this because `torch.isnan()` is now available thanks to #5273 and `torch.nan` is not really important (`torch.tensor(float('nan'))` works if it is required).

**Comment by leaf918** [comment]
why tenor get a nan from numpy ?

`
d_gt
Out[11]: 
array([[ 0.48199743,  1.8229529 , -0.40912393,  1.2882032 ],
       [ 0.3643558 ,  1.3780229 , -1.808163  , -0.11083595],
       [ 0.6816473 ,  1.2890222 ,  1.3237439 , -0.44466507],
       ...,
       [ 1.5197706 , -0.6994978 , -0.06939876,  1.282323  ],
       [ 1.2408875 , -2.7423244 , -1.0830617 ,  2.2959852 ],
       [ 1.5197706 , -2.2390988 , -0.06939876,  1.282323  ]],
      dtype=float32)
torch.log(torch.tensor(d_gt.astype(np.double)))
Out[12]: 
tensor([[-0.7298,  0.6005,     nan,  0.2532],
        [-1.0096,  0.3206,     nan,     nan],
        [-0.3832,  0.2539,  0.2805,     nan],
        ...,
        [ 0.4186,     nan,     nan,  0.2487],
        [ 0.2158,     nan,     nan,  0.8312],
        [ 0.4186,     nan,     nan,  0.2487]], dtype=torch.float64)
torch.log(torch.tensor(d_gt))
Out[13]: 
tensor([[-0.7298,  0.6005,     nan,  0.2532],
        [-1.0096,  0.3206,     nan,     nan],
        [-0.3832,  0.2539,  0.2805,     nan],
        ...,
        [ 0.4186,     nan,     nan,  0.2487],
        [ 0.2158,     nan,     nan,  0.8312],
        [ 0.4186,     nan,     nan,  0.2487]])
`
