### ISSUE TITLE
Incorrect info about overriding torch tensors in version 1.7.0

### ISSUE THREAD

**Issue by jemisjoky** [pytorch/pytorch#47697]
## 📚 Documentation

I've been working on extending the `torch.Tensor` class, where the information provided in the `torch._overrides` has proven really helpful! After recently upgrading to torch version 1.7.0 however, I noticed that the attribute `_overrides` is no longer present in `torch`. Two questions/comments about this:

1. Is the information that used to be in `torch._overrides` still present somewhere else in the library?
2. The [documentation](https://pytorch.org/docs/1.7.0/notes/extending.html#testing-coverage-of-overrides-for-the-pytorch-api) for torch 1.7.0 still refers to `torch._overrides`, so should be updated with the correct info.

Thank you for your help with this :)

cc @ezyang @gchanan @zou3519 @bdhirsh @hameerabbasi @rgommers @jlin27 @mruberry

**Comment by gchanan** [comment]
Thanks for pointing this out @jemisjoky, it is indeed an oversight.  It looks like `torch._overrides` is now `torch.overrides` and we should update the documentation.

**Comment by jemisjoky** [comment]
Haha if I had just looked a bit further down in `dir(torch)` it would have been obvious where it had moved to. Thanks a bunch for that info @gchanan, super helpful!

**Comment by rgommers** [comment]
@hameerabbasi did we consciously decide to move to the non-underscored name? `torch.overrides` isn't in the docs as a public submodule, so that's a little inconsistent.

**Comment by hameerabbasi** [comment]
Yes, this was done in #37091, specifically in https://github.com/pytorch/pytorch/pull/37091/commits/b422a1bfdb16c5f86ea31367b3c2c73ec92454b1, in the context of there being various utility methods there that were already well-tested and needed to be exposed, such as, for example, `is_tensor_method_or_property`. I can't seem to find the conversation, maybe it happened in a meeting.

**Comment by hameerabbasi** [comment]
I've created the docs issue in #48087.
