### ISSUE TITLE
In-place view functions might not actually be views

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#47704]
## 🐛 Bug

In-place view functions don't seem to be considered to be view functions. I suspect that the autograd tracking on these things is not correct (but I haven't confirmed this)

## To Reproduce

```
>>> import torch
>>> x = torch.randn(3, 3, requires_grad=True)
>>> y = x.clone()
>>> y.transpose_()
>>> y._base
None
```

## Expected behavior

If the view tracking behavior is correct, I'd expect _base to be non-None, like in the out-of-place version:
```
>>> import torch
>>> x = torch.randn(3, 3, requires_grad=True)
>>> y = x.clone()
>>> y.transpose(0, 1)._base
tensor([[-2.0736,  0.1603,  0.5348],
        [ 1.5998, -1.0118,  1.5306],
        [-0.5577,  1.0289, -0.6358]], grad_fn=<CloneBackward>)
```

## Environment
master

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved

**Comment by albanD** [comment]
Inplace view functions are definitely weird and haven't been looked at yet in the context of the view cleanup that happened this year.

But my gut feeling here is that this is correct as `y` is the only Tensor looking at that memory and so is not a view of any other Tensor.
Note that if you do the same thing on something that is already a view, then it will remain a view as you expect:
```python
import torch

a = torch.rand(2, 2)
b = a.view_as(a)
print(b._is_view()) # True
c = b.t()
print(c._is_view()) # True
c = b.t_()
print(c._is_view()) # True
c = a.t_()
print(c._is_view()) # False
```

Am I missing something?

**Comment by zou3519** [comment]
> But my gut feeling here is that this is correct as y is the only Tensor looking at that memory and so is not a view of any other Tensor.

That makes a lot of sense. I dug into the codegen for transpose_ in VariableType and I don't see anything that looks out of the ordinary (it doesn't rebase history, but that's because it shouldn't, since it doesn't modify any values).

```cpp
}
Tensor & transpose_(Tensor & self, int64_t dim0, int64_t dim1) {
  auto& self_ = unpack(self, "self", 0);
  check_inplace(self);
  std::shared_ptr<TransposeBackward1> grad_fn;
  if (compute_requires_grad( self )) {
    grad_fn = std::shared_ptr<TransposeBackward1>(new TransposeBackward1(), deleteNode);
    grad_fn->set_next_edges(collect_next_edges( self ));
    grad_fn->dim0 = dim0;
    grad_fn->dim1 = dim1;
  }
  #ifndef NDEBUG
  c10::optional<Storage> self__storage_saved =
    self_.has_storage() ? c10::optional<Storage>(self_.storage()) : c10::nullopt;
  c10::intrusive_ptr<TensorImpl> self__impl_saved;
  if (self_.defined()) self__impl_saved = self_.getIntrusivePtr();
  #endif
  {
    at::AutoNonVariableTypeMode non_var_type_mode(true);
    self_.transpose_(dim0, dim1);
  }
  #ifndef NDEBUG
  if (self__storage_saved.has_value())
    AT_ASSERT(self__storage_saved.value().is_alias_of(self_.storage()));
  if (self__impl_saved) AT_ASSERT(self__impl_saved == self_.getIntrusivePtr());
  #endif
  increment_version(self);
  if (grad_fn) {
      set_history(flatten_tensor_args( self ), grad_fn);
  }
  return self;
}
```
Closing this issue bc there doesn't seem to be anything wrong, thanks for talking it through @albanD!
