### ISSUE TITLE
Implement torch::cuda::synchronize()

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#47722]
In Python we have torch.cuda.synchronize() but the C++ counterpart doesn't exist. Ref https://github.com/pytorch/pytorch/pull/47428/files#r520917319

A nice follow up is to build up all of torch::cuda so that it has API parity with torch.cuda. Make sure your implementation works even when built without CUDA support (existing functions in torch::cuda should clue you how to do this.)

cc @yf225 @glaringlee

**Comment by glaringlee** [comment]
@glaringlee tag myself
