### ISSUE TITLE
Error running exported model in onnxruntime

### ISSUE THREAD

**Issue by omasaht** [pytorch/pytorch#47738]
## 🐛 Bug

When a tensor (which comes from nn.Parameter().shape/.size()) is past as arguments in torch.zeros() in a forward() function of a model, it results in a error when onnxruntime inference is initiated. I have tested Pytorch version 1.5, 1.6, and 1.7. This error is not present in Pytorch version 1.5 whereas it is present in newer versions. I have also tested it with different versions of onnxruntime and onnx and the error seems to be only occuring when model is exported using newer versions of Pytorch.
## To Reproduce
``` python

import torch
import torch.nn as nn
import onnx
import onnxruntime
import numpy as np

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        weight_tensor = torch.empty(3,21,16,64)
        init_weight = torch.nn.init.xavier_uniform_(weight_tensor)
        self.w_matrix = nn.Parameter(init_weight)

    def forward(self,x):
        num_out,num_in,_,_ = self.w_matrix.shape
        ## This line causes the error ##
        b = torch.zeros(x.shape[0],num_out,num_in)
        return b

torch.random.manual_seed(10)

model = Net()
x = torch.randn((1,3,64,64))
y = model(x)

save_path = 'blabla.onnx'
torch.onnx.export(model,               # model being run
              x,                         # model input (or a tuple for multiple inputs)
              save_path,   # where to save the model (can be a file or file-like object)
              export_params=True,        # store the trained parameter weights inside the model file
              opset_version=9,          # the ONNX version to export the model to
              do_constant_folding=True,  # whether to execute constant folding for optimization
              input_names = ['input'],   # the model's input names
              output_names = ['output'],
             ) # the model's output names

model = onnx.load(save_path)
ort_session = onnxruntime.InferenceSession(save_path)
## Error in this function ##
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)

```

1. Run the above sample code in Pytorch version 1.6,1.7 to reproduce error
2. Running above sample code in Pytorch version 1.5 will produce no error

## Expected behavior

Newer versions of Pytorch should be able to run this code with no error ensuring backward compatibility. 
## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 450.57
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37h8f50634_2    conda-forge
[conda] mkl_fft                   1.2.0            py37h161383b_1    conda-forge
[conda] mkl_random                1.2.0            py37h9fdb41a_1    conda-forge
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.7.0                      py37    pytorch
[conda] torchvision               0.8.1                py37_cu102    pytorch
[conda] onnx                      1.8.0                    pypi_0    pypi
[conda] onnxruntime               1.5.2                    pypi_0    pypi

## Additional context

This problem can be avoided by casting arguments of torch.zeros as int.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by IRDonch** [comment]
I have encountered a similar issue, which most likely has the same root cause. Here's my reproducer:

```python
import onnxruntime
import torch

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.p = torch.nn.Parameter(torch.zeros([5]))

    def forward(self, x):
        return x + self.p.size()[0]

def main():
    m = MyModule()
    x = torch.tensor(4)
    assert m(x).size() == ()

    torch.onnx.export(m, x, 'test.onnx', opset_version=11,
        input_names=['x'], output_names=['y'])

    sess = onnxruntime.InferenceSession('test.onnx')
    y, = sess.run(['y'], {'x': x.numpy()})
    assert y.shape == (), f"y.shape is {y.shape}"

main()
```

The second assertion fails with "y.shape is (1,)".

Looking at the generated ONNX file reveals that the constant that represents the parameter's size is not encoded correctly:

```
ir_version: 6
producer_name: "pytorch"
producer_version: "1.8"
graph {
  node {
    input: "x"
    input: "7"
    output: "y"
    name: "Add_0"
    op_type: "Add"
  }
  name: "torch-jit-export"
  initializer {
    dims: 1 # <-- PROBLEM HERE
    data_type: 7
    name: "7"
    raw_data: "\005\000\000\000\000\000\000\000"
  }
  input {
    name: "x"
    type {
      tensor_type {
        elem_type: 7
        shape {
        }
      }
    }
  }
  output {
    name: "y"
    type {
      tensor_type {
        elem_type: 7
        shape {
        }
      }
    }
  }
}
opset_import {
  version: 11
}
```

It's encoded as a one-dimensional tensor, whereas it should be zero-dimensional.

**Comment by justinchuby** [comment]
@IRDonch The latest pytorch nightly version produces the expected behavior. @omasaht could you share the error you encountered?

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
