### ISSUE TITLE
python setup.py install pytorch 0.3.0 failed

### ISSUE THREAD

**Issue by MasonSuWei** [pytorch/pytorch#4773]
I just git clone --recursive  --branch=0.3.0 https://github.com/pytorch/pytorch

After I run the following commands
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]

# Install basic dependencies
conda install numpy pyyaml mkl setuptools cmake cffi

# Add LAPACK support for the GPU
conda install -c soumith magma-cuda80 # or magma-cuda75 if CUDA 7.5

I run the following command
python setup.py install

But the command failed, the last log is the following. Can you give me some advises to debug this problem?

gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0 -I/media/disk1/pytorch/pytorch-0.3.0/torch/csrc -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/pybind11/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/TH -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THNN -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/ATen -I/home/masonsu/.conda/envs/pytorch_0_3_0/lib/python3.6/site-packages/numpy/core/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THCUNN -I/home/masonsu/.conda/envs/pytorch_0_3_0/include/python3.6m -c torch/csrc/cuda/nccl.cpp -o build/temp.linux-x86_64-3.6/torch/csrc/cuda/nccl.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0 -I/media/disk1/pytorch/pytorch-0.3.0/torch/csrc -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/pybind11/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/TH -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THNN -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/ATen -I/home/masonsu/.conda/envs/pytorch_0_3_0/lib/python3.6/site-packages/numpy/core/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THCUNN -I/home/masonsu/.conda/envs/pytorch_0_3_0/include/python3.6m -c /media/disk1/pytorch/pytorch-0.3.0/torch/csrc/generated/cuda_TensorShort.cpp -o build/temp.linux-x86_64-3.6/media/disk1/pytorch/pytorch-0.3.0/torch/csrc/generated/cuda_TensorShort.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0 -I/media/disk1/pytorch/pytorch-0.3.0/torch/csrc -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/pybind11/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/TH -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THNN -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/ATen -I/home/masonsu/.conda/envs/pytorch_0_3_0/lib/python3.6/site-packages/numpy/core/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/media/disk1/pytorch/pytorch-0.3.0/torch/lib/tmp_install/include/THCUNN -I/home/masonsu/.conda/envs/pytorch_0_3_0/include/python3.6m -c /media/disk1/pytorch/pytorch-0.3.0/torch/csrc/generated/cuda_TensorHalf.cpp -o build/temp.linux-x86_64-3.6/media/disk1/pytorch/pytorch-0.3.0/torch/csrc/generated/cuda_TensorHalf.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN
error: command 'gcc' failed with exit status 1

**My cuda is 8.0.61. My CUDNN is 5.1.10.**

**Comment by ezyang** [comment]
You'll need to post more logs, I'm afraid.

**Comment by MasonSuWei** [comment]
My CUDNN's version is too low. I changed it to v7. The compilation succeeded.
