### ISSUE TITLE
Can I register custom op with python API and load generated dynamic library with C++ in custom op register?

### ISSUE THREAD

**Issue by junna2016** [pytorch/pytorch#47741]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by junna2016** [comment]
According to introduction in https://pytorch.org/docs/stable/notes/extending.html, I regsiter custom op with torch.utils.cpp_extension.load_inline API. It will generate a libcustom.so.
How can I load this libcustom.so from C++  when my environment only has libtorch.so?

**Comment by ailzhang** [comment]
Hi, please redirect questions to forum as instructed in the template. Thanks!
