### ISSUE TITLE
torch_cuda unresolved symbols in Windows

### ISSUE THREAD

**Issue by ArutyunovG** [pytorch/pytorch#47744]
## 🐛 Bug

Building pytorch master branch on Windows results in unresolved external symbols errors.

## To Reproduce

Checkout master at 1aeac9771221bcc72e2b10ce5ba4e73b887d03f3

Run

```
set "CMAKE_GENERATOR=Visual Studio 16 2019"
python setup.py build
```

Attached file with full log and errors in the end
[pytorch_unresolved_3.txt](https://github.com/pytorch/pytorch/files/5537519/pytorch_unresolved_3.txt)

## Expected behavior

`python setup.py build` passes without errors.

## Environment

Used tools:

CMake version 3.16.4, 
_MSC_VER 1927
nvcc: Cuda compilation tools, release 10.2, V10.2.89
cuDNN version: 8.0.5

## Additional context

Tried to solve this problem on my own but could not figure out the causes.

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by skyline75489** [comment]
Can you try to build it with cuDNN 8.0.4 ?

**Comment by peterjc123** [comment]
It seems that you didn't build ATen. And caffe2 builds won't work without ATen now.

**Comment by ArutyunovG** [comment]
> Can you try to build it with cuDNN 8.0.4 ?

Switching to latest cuDNN 8.0.5 didn't help
[pytorch_unersolved_1.txt](https://github.com/pytorch/pytorch/files/5526247/pytorch_unersolved_1.txt)

> It seems that you didn't build ATen. And caffe2 builds won't work without ATen now.

Could you clarify, which CMake switch I should use, if any? Or some file/folder examples missing from the build.

**Comment by mszhanyi** [comment]
@ArutyunovG ， I don't think torch_cuda could be build in VS 2019 IDE now. At present, the most reliable way to build pytorch master in windows is to use command

**Comment by ArutyunovG** [comment]
@mszhanyi ,
you mean this command ```python setup.py build``` ?

**Comment by mszhanyi** [comment]
> @mszhanyi ,
> you mean this command `python setup.py build` ?

python setup.py install, python setup.py build or python tools/build_libtoch.py are all OK.

**Comment by mszhanyi** [comment]
The latest building guide is in review, https://github.com/pytorch/pytorch/pull/47840, any comments are welcome

**Comment by ArutyunovG** [comment]
Running with ``python setup.py build`` didn't help, errors are still the same stuff with unresolved externals. This is log remaining in the cmd window
[pytorch_unersolved_2.txt](https://github.com/pytorch/pytorch/files/5531336/pytorch_unersolved_2.txt)

**Comment by skyline75489** [comment]
You may need to do a “python setup.py clean” and “git clean -xdf” to cleanup artifacts from last build.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Grigory Arutyunov <notifications@github.com>
发送时间: Thursday, November 12, 2020 10:53:29 PM
收件人: pytorch/pytorch <pytorch@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [pytorch/pytorch] torch_cuda unresolved symbols in Windows (#47744)


Running with python setup.py build didn't help, errors are still the same stuff with unresolved externals. This is log remaining in the cmd window
pytorch_unersolved_2.txt<https://github.com/pytorch/pytorch/files/5531336/pytorch_unersolved_2.txt>

―

**Comment by ArutyunovG** [comment]
I removed the whole `build `folder manually with `rmdir build /s/q` before starting the new build. If that's not enough of course I can do it again starting with the suggested commands or even clone pytorch from scratch.

**Comment by skyline75489** [comment]
Unfortunately sometimes you do need to use “git clean -xdf” because some of the artifacts are not in build/. Sometimes even need to do “git clean” for each submodules.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Grigory Arutyunov <notifications@github.com>
发送时间: Friday, November 13, 2020 6:24:15 AM
收件人: pytorch/pytorch <pytorch@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [pytorch/pytorch] torch_cuda unresolved symbols in Windows (#47744)


I removed the whole build folder manually with rmdir build /s/q before starting the new build. If that's not enough of course I can do it again starting with the suggested commands or even clone pytorch from scratch.

―

**Comment by ArutyunovG** [comment]
Deleted pytorch folder, cloned it again, unfortunately build still fails with same linker errors.
[pytorch_unresolved_3.txt](https://github.com/pytorch/pytorch/files/5537529/pytorch_unresolved_3.txt)

Updated description of the issue to match current actions and environment.

**Comment by ArutyunovG** [comment]
The problem turned out to be with the point, that I don't have CUDA installed directly on the machine, where the build was going on. Rather it was downloaded from the frameworks repository, where we share common environment with my team. Currently it seems that to build with CUDA one needs some special stuff (like "hidden libs" or whatever) that is installed to the machine together with CUDA package. I'll try to build again to check if build passes and then close this issue, as it seems unrelated to pytorch then.
