### ISSUE TITLE
C10's make_optional is in the global namespace

### ISSUE THREAD

**Issue by elbaro** [pytorch/pytorch#47742]
## 🐛 Bug

C10's `make_optional` is in the global namespace, conflicting with user code.

## To Reproduce

pytorch==1.7
`site-packages/torch/include/c10/util/Optional.h:918`

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by ezyang** [comment]
It looks like it's in c10 namespace to me:

```

template <class T>
constexpr optional<typename std::decay<T>::type> make_optional(T&& v) {
  return optional<typename std::decay<T>::type>(constexpr_forward<T>(v));
}

template <class X>
constexpr optional<X&> make_optional(std::reference_wrapper<X> v) {
  return optional<X&>(v.get());
}

} // namespace c10
```

Are you `using namespace c10` or `using namespace torch`?

**Comment by elbaro** [comment]
We already removed the conflicting code and cannot reproduce this anymore.
