### ISSUE TITLE
THFloatBlas_gemm is missing in the torch v1.7

### ISSUE THREAD

**Issue by Red-Eyed** [pytorch/pytorch#47750]
## ❓ Questions and Help

Hello all!
I've updated pytorch to v1.7 (from 1.6) on my Ubuntu 20.04
previously, I had CUDA and CPU code that was linked to `libtorch_cpu.so`
that code uses `THFloatBlas_gemm` function, but that symbol is missing in the latest version 1.7

I didn't see any news about dropping the `THFloatBlas_gemm` symbol in the release note.

1. Is there any plans to revert back `THFloatBlas_gemm` ?
2. Is there any kind of replacement for `THFloatBlas_gemm` ?

**Comment by gchanan** [comment]
We don't provide compatibility for things like THFloatTensor, only functions in the `at::` and `torch::` namespace that take Tensors.  If you have a Tensor, the equivalent call is `torch::addmm`; if you just want access to the raw gemm function I'd recommend calling directly into your BLAS library.

**Comment by jinfagang** [comment]
@gchanan Hi, what's your suggestions on this error?

**Comment by Red-Eyed** [comment]
@jinfagang so he already wrote a suggestion:

> If you have a Tensor, the equivalent call is torch::addmm; if you just want access to the raw gemm function I'd recommend calling directly into your BLAS library.

**Comment by jinfagang** [comment]
@gchanan @Red-Eyed  It says errror:

```
error: ‘addmm’ is not a member of ‘torch’
```

**Comment by lzzzzj** [comment]
> torch::addmm

I met the same problem.Did you solve it?
