### ISSUE TITLE
-std=c++11 error in setup.py file 

### ISSUE THREAD

**Issue by absolutelyharsh123** [pytorch/pytorch#4776]
After runnin python setup.py install i get this error 

-- Configuring done
-- Generating done
-- Build files have been written to: /opt/Dependency/pytorch/torch/lib/build/aten
[  1%] Built target aten_files_are_generated
[  2%] [  3%] [  4%] [  5%] [  6%] [  8%] [  8%] Building CXX object src/ATen/CMakeFiles/ATen.dir/Context.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/Check.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/ExpandUtils.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/Utils.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/CUDAGenerator.cpp.o
[  9%] Building CXX object src/ATen/CMakeFiles/ATen.dir/PinnedMemoryAllocator.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/Tensor.cpp.o
Building CXX object src/ATen/CMakeFiles/ATen.dir/UndefinedType.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=c++11"cc1plus: error: unrecognized command line option "-std=c++11"

cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/Context.cpp.o] Error 1cc1plus: error: unrecognized command line option "-std=c++11"

make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/Check.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/ExpandUtils.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/Utils.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/CUDAGenerator.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/PinnedMemoryAllocator.cpp.o] Error 1
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/Tensor.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/UndefinedType.cpp.o] Error 1
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
make: *** [all] Error 2

i am running gcc 4.7.

**Comment by apaszke** [comment]
You probably need to update your gcc. It doesn't support the C++11 standard, which is required to build PyTorch.
