### ISSUE TITLE
Thread-save random number generator

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#4777]
The generator works for one GPU, but when I'm trying `DataParallel` which creates multiple threads for GPUs, I get the segmentation error. After a few exploration in gdb, I found that this line of code may be the culprit. It's highly likely that the generator is shared among threads and race conditions happen here.

```C
  y = *(_generator->state + (_generator->next)++);
```

#### env
- Pytorch 0.3.0 (pip)
- Ubuntu 16.04
- python 3.6

#### minimal reproducing snippet:

```python
from threading import Thread
import torch
import time

def _worker():
    while True:
        probs = torch.Tensor(500, 500).uniform_(0, 1)
        random = probs
        # random = torch.geometric(probs)
        print(random[0][0])
        time.sleep(1)

threads = [Thread(target=_worker) for i in range(8)]

for thread in threads:
    thread.start()
for thread in threads:
    thread.join()
```

**Comment by Stonesjtu** [comment]
And I think the 64 bit version may be a better alternative than the current hack approach.
http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/VERSIONS/C-LANG/mt19937-64.c

**Comment by SsnL** [comment]
Do you mean CPU generators aren't thread-safe? That issue is tracked at https://github.com/pytorch/pytorch/issues/3794
