### ISSUE TITLE
Incorrect result of `fmod` and `remainder` operator.

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#47779]
## 🐛 Bug

Find a bug when porting `fmod` from TH to ATen. #47323 
The results are wrong when a integral tensor is divided by a floating-point scalar; Or we raise `RuntimeError: result type Float can't be cast to the desired output type Long` when a integral tensor is divided by a floating-point tensor.
And `fmod` refers to the floating-point mod, so I think all the integral types should be promoted to floating-point.

## To Reproduce

```python
>>> a = torch.tensor(2, dtype=torch.int64) # uint8/int8/int16/int32/int64
>>> torch.fmod(a, 1.5)
tensor(0)
>>> b = torch.tensor(1.5) 
>>> torch.fmod(a, b)
RuntimeError: result type Float can't be cast to the desired output type Long
```
The behavior is same for `fmod` and `remainder`.

You can check the result type of our `fmod` in the [table](https://github.com/pytorch/pytorch/pull/47323#issue-515016993).
This will happen as the first argument is integral and the dividend is floating-point. 

## Expected behavior

Like `Numpy` and `math`, integral tensor needs to be promoted to floating-point to get accurate results:
```python
>>> a = np.array([2], dtype=np.int64) # uint8/int8/int16/int32/int64
>>> np.fmod(a, 1.5)
array([0.5], dtype=np.float64)
```

## Environment
PyTorch version: 1.8.0a0+c058f15
Is debug build: True
CUDA used to build PyTorch: 9.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 418.126.02
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.8.0a0
[pip3] torch-cluster==1.5.8
[pip3] torch-geometric==1.6.1
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.8
[pip3] torch-spline-conv==1.2.0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.1           py38hbc911f0_0
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] torch                     1.8.0a0                   dev_0    <develop>
[conda] torch-cluster             1.5.8                    pypi_0    pypi
[conda] torch-geometric           1.6.1                    pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.8                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi

## Additional context

cc @ezyang @gchanan @mruberry @rgommers @heitorschueroff

**Comment by ejguan** [comment]
I can try to fix this issue after I port `fmod` from TH to ATen, if everyone think it should be solved by having type promotion included into `fmod` and `remainder`.

**Comment by ejguan** [comment]
Add module: bc-breaking because it will not raise `RuntimeError: result type (Half, Float, Double) can't be cast to the desired output type (Byte, Char, Short, Int, Long)`, and result is going to be different.

**Comment by mruberry** [comment]
Making fmod and remainder have type promotion consistent with NumPy and the rest of PyTorch sounds great.
