### ISSUE TITLE
reduce the size of wheel files

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#478]
currently the wheel files are close to 400MB each, because we also ship CUDA and MKL via their distribution license.

Will be finding ways to reduce their size over the next few days.

**Comment by soumith** [comment]
this is not happening. I looked into it and at this point i want to guarantee stability

**Comment by evanwils** [comment]
@soumith - Is it likely that this issue will be revisited? The wheel's file size is 565MB. What would it take to create a working wheel without libcudnn and friends?

**Comment by soumith** [comment]
@evanwils the answer is quite simple. 

Follow the readme here: https://github.com/pytorch/builder/tree/master/manywheel
modify deps_list an deps_so_name here: https://github.com/pytorch/builder/blob/master/manywheel/build.sh#L89-L166 to be empty arrays.

**Comment by GeeshangXu** [comment]
The current pip wheel is **10 more times larger** than other deep learning frameworks, maybe CUDA and MKL should stay out the wheel.
