### ISSUE TITLE
IR docs are out of date after Value/Node split

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4782]
Docs on Node still use a unique to uniquely identify a Node, even though only Values actually get uniques. Actually, identifying Node is a bit of trouble in the IR today, since there is no succinct way to refer to a particular node.

Here is one notation proposal. Suppose we have:

```
%1, %2 = Fun %3, %4
```

If `%1` refers to a Value, I propose that `[%1, %2]` (or `[%1]` in the unary case) refer to a Node with these values in documentation. The downside of this notational convention is that if you change the outputs of a Node, the identifier for the Node changes too, but there is no way to solve this without introducing another unique identifier for nodes.

CC @apaszke @zdevito

**Comment by apaszke** [comment]
Another simple way would be to use `<%unique_of_first_output>` since every node has at least a single output. I'm ok with any of those

**Comment by eellison** [comment]
We updated the IR docs.
