### ISSUE TITLE
Linker error when building from source with CUDA 11.0

### ISSUE THREAD

**Issue by FabianIsensee** [pytorch/pytorch#47837]
When building pytorch from source I get a linker error whenever I try to build with cuda 11.0 (and magma-cuda-110). Building with cuda 10.2 works fine.
This only happens on our GPU cluster. It works fine on my local workstation, so it may be related to the software configuration of our cluster. I would greatly appreciate your help in identifying what causes the problem.

It doies not seem to be related to cuDNN. I tried 8.0.2 and 8.0.5 to be sure. The result is the same either way.

Workstation (Ubuntu 20.02):

> (pytorch_build) fabian@e230-AMDworkstation: **cat /proc/version**
> Linux version 5.4.0-52-generic (buildd@lgw01-amd64-060) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020

> (pytorch_build) fabian@e230-AMDworkstation: **ld --version**
> GNU ld (GNU Binutils for Ubuntu) 2.34
> Copyright (C) 2020 Free Software Foundation, Inc.
> This program is free software; you may redistribute it under the terms of
> the GNU General Public License version 3 or (at your option) a later version.
> This program has absolutely no warranty.

> (pytorch_build) fabian@e230-AMDworkstation: **gcc --version**
> gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> (pytorch_build) fabian@e230-AMDworkstation: **nvcc --version**
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Wed_Jul_22_19:09:09_PDT_2020
> Cuda compilation tools, release 11.0, V11.0.221
> Build cuda_11.0_bu.TC445_37.28845127_0

Cluster (one node):

> -bash-4.2$ **cat /proc/version**
> Linux version 3.10.0-693.21.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Wed Mar 7 19:03:37 UTC 2018
> 
> -bash-4.2$ **ld --version**
> GNU ld version 2.25.1-32.base.el7_4.2 
> Copyright (C) 2014 Free Software Foundation, Inc.
> This program is free software; you may redistribute it under the terms of
> the GNU General Public License version 3 or (at your option) a later version.
> This program has absolutely no warranty.
> 
> -bash-4.2$ **nvcc --version**
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2020 NVIDIA Corporation
> Built on Thu_Jun_11_22:26:38_PDT_2020
> Cuda compilation tools, release 11.0, V11.0.194
> Build cuda_11.0_bu.TC445_37.28540450_0
> 
> -bash-4.2$ **gcc --version**
> gcc (GCC) 7.2.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>

The error I get is the following:

```bash
[4651/4993] Linking CXX shared library lib/libtorch_cuda.so
FAILED: lib/libtorch_cuda.so 
[a very long text output]
 -lm  -ldl  lib/libdnnl.a  -pthread  -ldl  /usr/local/cuda-11.0/lib64/libcufft.so  /usr/local/cuda-11.0/lib64/libcublas.so && :
/bin/ld: /gpu/data/OE0441/isensee/pytorch_build/conda_env_pytorch_build-11.0/lib/libmagma.a(error.cpp.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

Any help would be greatly appreciated!

Best,

Fabian

cc @malfet @seemethere @walterddr @ngimel

**Comment by xwang233** [comment]
You can try add the environment variable `TORCH_CUDA_ARCH_LIST=x.y` to only build for your GPU compute capability. For example, if you have A100, you can do `TORCH_CUDA_ARCH_LIST=8.0`.

**Comment by FabianIsensee** [comment]
Hi, thanks for your reply. I have already set the variable to contain only the architectures that we have in our cluster: `export TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5"`
So that's not it :-/

**Comment by ezyang** [comment]
The ld on your cluster looks pretty old, any way of upgrading it?

**Comment by FabianIsensee** [comment]
I would need to pester the admins with that. If there is a strong indication that this is causing this issue then I can try to do that. I posted the version of ld above to see whether this would stand out as a potential problem. How confident are you that this is the underlying problem (this will help me convince the admins to update it)?

**Comment by ezyang** [comment]
https://stackoverflow.com/questions/46058050/unable-to-compile-unrecognized-relocation

**Comment by FabianIsensee** [comment]
Fantastic, thank you! This will help me make my case for updating the linker version :-) I searched for the error before and did not stumble on this explanation.

**Comment by FabianIsensee** [comment]
I managed to get ld version 2.34. This worked. Thank you very much again for your help!
