### ISSUE TITLE
Sparse model optimizer raises 'ValueError: optimizer got an empty parameter list'

### ISSUE THREAD

**Issue by Asa-Nisi-Masa** [pytorch/pytorch#47838]
## 🐛 Bug

Creating a sparse optimizer for a model with sparse embedding layer raises an exception 'ValueError: optimizer got an empty parameter list'.

## To Reproduce

```
import torch

model = torch.nn.Sequential(torch.nn.Embedding(1, 1, sparse=True))
optimizer = torch.optim.SparseAdam(model.parameters())
```

## Expected behavior

I expect the code to execute without problems. Printing the model parameters shows

```
print(list(model.parameters()))
# [Parameter containing:
# tensor([[0.8340]], requires_grad=True)]
```

## Environment

PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.8.1+cu101
[conda] Could not collect

## Additional context

Noticed this bug on Google colab

cc @vincentqb

**Comment by mariosasko** [comment]
Related to #47594. 

Rn, you can do `torch.optim.SparseAdam(list(model.parameters()), ...)` to fix the issue.
