### ISSUE TITLE
Do you support quantification of a part of the model, such as quantifying only the backbone

### ISSUE THREAD

**Issue by fxwfzsxyq** [pytorch/pytorch#47839]
Do you support quantification of a part of the model, such as quantifying only the backbone

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Yes, this is supported.  Please see the `qconfig` part of https://pytorch.org/docs/stable/quantization.html#model-preparation-for-quantization .
