### ISSUE TITLE
unsupported Python type error from set_default_tensor_type()

### ISSUE THREAD

**Issue by jinserk** [pytorch/pytorch#4784]
Hi,
I've updated pytorch to the lastest master (`a54407a7`) from github, but got an error when I use `torch.set_default_tensor_type("torch.cuda.FloatTensor")`:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  unsupported Python type
Aborted (core dumped)
```

What to do for workaround? Thanks!
Jin

**Comment by zou3519** [comment]
Here's a workaround. I think the problem is that pytorch hasn't initialized CUDA yet. At any rate, the following works for me:
```
import torch
x = torch.randn(1) # initialize cuda
torch.set_default_tensor_type("torch.cuda.FloatTensor")
```

**Comment by jinserk** [comment]
Thanks @zou3519, but your workaround doesn't work for me.
The error message still shows.
Jin

**Comment by zou3519** [comment]
Sorry, I meant the following:

```
import torch
x = torch.randn(1).cuda() # initialize cuda
torch.set_default_tensor_type("torch.cuda.FloatTensor")
```

Could you please try if that works for you?

**Comment by jinserk** [comment]
Yep. Just what I thought and was going to add comment here :smile:
It works. Thank you!
Jin
