### ISSUE TITLE
When I install pytoch, I have a error code about future

### ISSUE THREAD

**Issue by wlrkqdl** [pytorch/pytorch#47859]
## ❓ Questions and Help

Hi teams
Plz give me a info how the Fix this Error Code

I use this pytorch install code
### pip install torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

> This is Error Code
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.7.0%2Bcpu-cp37-cp37m-win_amd64.whl (184.2 MB)
     |████████████████████████████████| 184.2 MB 126 kB/s
Collecting torchvision==0.8.1+cpu
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.8.1%2Bcpu-cp37-cp37m-win_amd64.whl (808 kB)
     |████████████████████████████████| 808 kB ...
Collecting torchaudio===0.7.0
  Downloading https://download.pytorch.org/whl/torchaudio-0.7.0-cp37-none-win_amd64.whl (103 kB)
     |████████████████████████████████| 103 kB 6.4 MB/s
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting numpy
  Downloading numpy-1.19.4-cp37-cp37m-win_amd64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 6.4 MB/s
Collecting pillow>=4.1.1
  Downloading Pillow-8.0.1-cp37-cp37m-win_amd64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 6.4 MB/s
Building wheels for collected packages: future
  Building wheel for future (setup.py) ... error
  **ERROR: Command errored out with exit status 1:
   command: 'e:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Socket\AppData\Local\Temp\pip-wheel-ziumqlh2'
       cwd: C:\Users\Socket\AppData\Local\Temp\pip-install-k4xiochl\future\
  Complete output (76 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\future
  copying src\future\__init__.py -> build\lib\future
  creating build\lib\future\builtins
  copying src\future\builtins\disabled.py -> build\lib\future\builtins
  copying src\future\builtins\iterators.py -> build\lib\future\builtins
  copying src\future\builtins\misc.py -> build\lib\future\builtins
  copying src\future\builtins\newnext.py -> build\lib\future\builtins
  copying src\future\builtins\newround.py -> build\lib\future\builtins
  copying src\future\builtins\newsuper.py -> build\lib\future\builtins
  copying src\future\builtins\new_min_max.py -> build\lib\future\builtins
  copying src\future\builtins\__init__.py -> build\lib\future\builtins
  creating build\lib\future\types
  copying src\future\types\newbytes.py -> build\lib\future\types
  copying src\future\types\newdict.py -> build\lib\future\types
  copying src\future\types\newint.py -> build\lib\future\types
  copying src\future\types\newlist.py -> build\lib\future\types
  copying src\future\types\newmemoryview.py -> build\lib\future\types
  copying src\future\types\newobject.py -> build\lib\future\types
  copying src\future\types\newopen.py -> build\lib\future\types
  copying src\future\types\newrange.py -> build\lib\future\types
  copying src\future\types\newstr.py -> build\lib\future\types
  copying src\future\types\__init__.py -> build\lib\future\types
  creating build\lib\future\standard_library
  copying src\future\standard_library\__init__.py -> build\lib\future\standard_library
  creating build\lib\future\backports
  copying src\future\backports\datetime.py -> build\lib\future\backports
  copying src\future\backports\misc.py -> build\lib\future\backports
  copying src\future\backports\socket.py -> build\lib\future\backports
  copying src\future\backports\socketserver.py -> build\lib\future\backports
  copying src\future\backports\total_ordering.py -> build\lib\future\backports
  copying src\future\backports\_markupbase.py -> build\lib\future\backports
  copying src\future\backports\__init__.py -> build\lib\future\backports
  creating build\lib\future\backports\email
  copying src\future\backports\email\base64mime.py -> build\lib\future\backports\email
  copying src\future\backports\email\charset.py -> build\lib\future\backports\email
  copying src\future\backports\email\encoders.py -> build\lib\future\backports\email
  copying src\future\backports\email\errors.py -> build\lib\future\backports\email
  copying src\future\backports\email\feedparser.py -> build\lib\future\backports\email
  copying src\future\backports\email\generator.py -> build\lib\future\backports\email
  copying src\future\backports\email\header.py -> build\lib\future\backports\email
  copying src\future\backports\email\headerregistry.py -> build\lib\future\backports\email
  copying src\future\backports\email\iterators.py -> build\lib\future\backports\email
  copying src\future\backports\email\message.py -> build\lib\future\backports\email
  copying src\future\backports\email\parser.py -> build\lib\future\backports\email
  copying src\future\backports\email\policy.py -> build\lib\future\backports\email
  copying src\future\backports\email\quoprimime.py -> build\lib\future\backports\email
  copying src\future\backports\email\utils.py -> build\lib\future\backports\email
  copying src\future\backports\email\_encoded_words.py -> build\lib\future\backports\email
  copying src\future\backports\email\_header_value_parser.py -> build\lib\future\backports\email
  copying src\future\backports\email\_parseaddr.py -> build\lib\future\backports\email
  copying src\future\backports\email\_policybase.py -> build\lib\future\backports\email
  copying src\future\backports\email\__init__.py -> build\lib\future\backports\email
  creating build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\application.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\audio.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\base.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\image.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\message.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\multipart.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\nonmultipart.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\text.py -> build\lib\future\backports\email\mime
  copying src\future\backports\email\mime\__init__.py -> build\lib\future\backports\email\mime
  creating build\lib\future\backports\html
  copying src\future\backports\html\entities.py -> build\lib\future\backports\html
  copying src\future\backports\html\parser.py -> build\lib\future\backports\html
  copying src\future\backports\html\__init__.py -> build\lib\future\backports\html
  creating build\lib\future\backports\http
  copying src\future\backports\http\client.py -> build\lib\future\backports\http
  copying src\future\backports\http\cookiejar.py -> build\lib\future\backports\http
  copying src\future\backports\http\cookies.py -> build\lib\future\backports\http
  error: could not read from 'src\future\backports\http\cookies.py': Bad file descriptor
  ----------------------------------------
  ERROR: Failed building wheel for future**
  Running setup.py clean for future
Failed to build future
Installing collected packages: future, dataclasses, typing-extensions, numpy, torch, pillow, torchvision, torchaudio
    Running setup.py install for future ... error
    ERROR: Command errored out with exit status 1:
     command: 'e:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Socket\AppData\Local\Temp\pip-record-ujep9p1n\install-record.txt' --single-version-externally-managed --compile --install-headers 'e:\python37\Include\future'
         cwd: C:\Users\Socket\AppData\Local\Temp\pip-install-k4xiochl\future\
    Complete output (76 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\future
    copying src\future\__init__.py -> build\lib\future
    creating build\lib\future\builtins
    copying src\future\builtins\disabled.py -> build\lib\future\builtins
    copying src\future\builtins\iterators.py -> build\lib\future\builtins
    copying src\future\builtins\misc.py -> build\lib\future\builtins
    copying src\future\builtins\newnext.py -> build\lib\future\builtins
    copying src\future\builtins\newround.py -> build\lib\future\builtins
    copying src\future\builtins\newsuper.py -> build\lib\future\builtins
    copying src\future\builtins\new_min_max.py -> build\lib\future\builtins
    copying src\future\builtins\__init__.py -> build\lib\future\builtins
    creating build\lib\future\types
    copying src\future\types\newbytes.py -> build\lib\future\types
    copying src\future\types\newdict.py -> build\lib\future\types
    copying src\future\types\newint.py -> build\lib\future\types
    copying src\future\types\newlist.py -> build\lib\future\types
    copying src\future\types\newmemoryview.py -> build\lib\future\types
    copying src\future\types\newobject.py -> build\lib\future\types
    copying src\future\types\newopen.py -> build\lib\future\types
    copying src\future\types\newrange.py -> build\lib\future\types
    copying src\future\types\newstr.py -> build\lib\future\types
    copying src\future\types\__init__.py -> build\lib\future\types
    creating build\lib\future\standard_library
    copying src\future\standard_library\__init__.py -> build\lib\future\standard_library
    creating build\lib\future\backports
    copying src\future\backports\datetime.py -> build\lib\future\backports
    copying src\future\backports\misc.py -> build\lib\future\backports
    copying src\future\backports\socket.py -> build\lib\future\backports
    copying src\future\backports\socketserver.py -> build\lib\future\backports
    copying src\future\backports\total_ordering.py -> build\lib\future\backports
    copying src\future\backports\_markupbase.py -> build\lib\future\backports
    copying src\future\backports\__init__.py -> build\lib\future\backports
    creating build\lib\future\backports\email
    copying src\future\backports\email\base64mime.py -> build\lib\future\backports\email
    copying src\future\backports\email\charset.py -> build\lib\future\backports\email
    copying src\future\backports\email\encoders.py -> build\lib\future\backports\email
    copying src\future\backports\email\errors.py -> build\lib\future\backports\email
    copying src\future\backports\email\feedparser.py -> build\lib\future\backports\email
    copying src\future\backports\email\generator.py -> build\lib\future\backports\email
    copying src\future\backports\email\header.py -> build\lib\future\backports\email
    copying src\future\backports\email\headerregistry.py -> build\lib\future\backports\email
    copying src\future\backports\email\iterators.py -> build\lib\future\backports\email
    copying src\future\backports\email\message.py -> build\lib\future\backports\email
    copying src\future\backports\email\parser.py -> build\lib\future\backports\email
    copying src\future\backports\email\policy.py -> build\lib\future\backports\email
    copying src\future\backports\email\quoprimime.py -> build\lib\future\backports\email
    copying src\future\backports\email\utils.py -> build\lib\future\backports\email
    copying src\future\backports\email\_encoded_words.py -> build\lib\future\backports\email
    copying src\future\backports\email\_header_value_parser.py -> build\lib\future\backports\email
    copying src\future\backports\email\_parseaddr.py -> build\lib\future\backports\email
    copying src\future\backports\email\_policybase.py -> build\lib\future\backports\email
    copying src\future\backports\email\__init__.py -> build\lib\future\backports\email
    creating build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\application.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\audio.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\base.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\image.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\message.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\multipart.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\nonmultipart.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\text.py -> build\lib\future\backports\email\mime
    copying src\future\backports\email\mime\__init__.py -> build\lib\future\backports\email\mime
    creating build\lib\future\backports\html
    copying src\future\backports\html\entities.py -> build\lib\future\backports\html
    copying src\future\backports\html\parser.py -> build\lib\future\backports\html
    copying src\future\backports\html\__init__.py -> build\lib\future\backports\html
    creating build\lib\future\backports\http
    copying src\future\backports\http\client.py -> build\lib\future\backports\http
    copying src\future\backports\http\cookiejar.py -> build\lib\future\backports\http
    copying src\future\backports\http\cookies.py -> build\lib\future\backports\http
    error: could not read from 'src\future\backports\http\cookies.py': Bad file descriptor
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'e:\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\Socket\\AppData\\Local\\Temp\\pip-install-k4xiochl\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Socket\AppData\Local\Temp\pip-record-ujep9p1n\install-record.txt' --single-version-externally-managed --compile --install-headers 'e:\python37\Include\future' Check the logs for full command output.

>

**Comment by skyline75489** [comment]
Look, you have #47845. This is not a support forum. Please do not file duplicate issues. 

As for this issue, try just install future, and see what happens. If there’s still an error, then it’s not a torch issue. If there’s no more error, then you can try install torch again.
