### ISSUE TITLE
THD build fails on macOS 10.12.6

### ISSUE THREAD

**Issue by 0fork** [pytorch/pytorch#4789]
I'm trying to compile pytorch on macOS with XCode 7 (downgraded from 8) and Cuda 8. Everything works great until the build process hits THD, then I get this:

```
thread_local not supported.  THD requires a compiler that supports
  thread_local.  Please upgrade your compiler.  If you are on macOS, upgrade
  to XCode 8 or newer.
```

The problem is that if I switch to XCode 8, nothing works (as has been covered in many other issues).

Can anybody help me to somehow compile THD with XCode 8 while using 7 for everything else?

**Comment by soumith** [comment]
`NO_DISTRIBUTED=1 python setup.py install`

**Comment by 0fork** [comment]
@soumith awesome, that worked, thanks! Though the build still fails but now it's crashing on `torch/csrc/autograd/profiler.h:171:8: error: thread-local storage is not supported for the current target` but at least I'm passed the THD issue ;)
