### ISSUE TITLE
Integrate torchtext.data.functional.numericalize_tokens_from_iterator and torchtext.data.utils.get_tokenizer

### ISSUE THREAD

**Issue by namespace-Pt** [pytorch/pytorch#47921]
## Motivation

Since torchtext.data.Fields will be retired, I tried to refactor my codes using *get_tokenizer* and *numericalize_tokens_from_iterator* api, however, when I'm trying to convert raw text of multiple fields into wordID vectors according to a pre-defined dictionary, I find it's hard to straighten out the logic beyond these two api because *numericalize_tokens_from_iterator* consumes an iterator of tokenizations and returns an iterator of corresponding word IDs. the tokenizer returned by *get_tokenizer* converts string into **a list of tokenizations rather than generator**, so it can't be straightly passed into *numericalize_tokens_from_iterator*.

Therefore, I have to customize an iterator and pass it to *numericalize_tokens_from_iterator* but in case where I **generate multiple fields of tokenizations( I mean tuples of tokenization lists ) this function fails to work**.

Furthermore, *numericalize_tokens_from_iterator* returns a generator and is hard to comprehend, maybe list is better.

## Pitch

I want a clear api which takes a pre-defined vocabulary, **a list of raw strings** and a tokenizer function as input, and returns **a list of wordID vectors** of these strings respectively, each of which is tokenized and then looked up in the vocabulary.

## Alternatives

I customize a generator function to do what I mentioned above.

## Additional context

Leave *mode* argument alone.

```python
def news_token_generator_group(news_file,tokenizer,vocab,mode):
    ''' iterate news_file, collect attrs and generate them respectively
       
    Args: 
        tokenizer: torchtext.data.utils.tokenizer
        mode: int defining how many attributes to be generated
    Returns: 
        generates wordID vector of each attrs, gathered into a list
    '''
    news_df = pd.read_table(news_file,index_col=None,names=['newsID','category','subcategory','title','abstract','url','entity_title','entity_abstract'])
    news_iterator = news_df.iterrows()
    
    attrs = ['title','category','subcategory','abstract']
    for _,i in news_iterator:
        result = []
        indicator = 0
        while indicator < mode:
            result.append([vocab[x] for x in tokenizer(i[attrs[indicator]])])
            indicator += 1
        yield result 
```

**Comment by smessmer** [comment]
Hi, thanks for reporting. Can you open an issue on the torchtext repository instead? https://github.com/pytorch/text/issues
