### ISSUE TITLE
PyTorch Mobile build from source

### ISSUE THREAD

**Issue by peter197321** [pytorch/pytorch#47927]
I'd like to build just PyTorch Mobile from the source for the mobile device. Is there a procedure to have just PyTorch Mobile built? Or is needed to have the whole PyTorch build included and how it distinguishes between PyTorch vs. PyTorch Mobile then?

**Comment by dhruvbird** [comment]
@peter197321  The PyTorch Mobile wiki contains information about how to build PyTorch only for mobile. Please see https://pytorch.org/mobile/android/#building-pytorch-android-from-source (for how to build from source for Android).
