### ISSUE TITLE
[doc] jit.fork doc is badly formatted and missing example

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#47932]
## 📚 Documentation

jit.fork doc is badly formatted and missing example.
![image](https://user-images.githubusercontent.com/5674597/99116516-289a0e00-25c2-11eb-9724-3ab9f59bb5c5.png)

cc @gmagogsfm

**Comment by eellison** [comment]
fixed with https://github.com/pytorch/pytorch/pull/49436
