### ISSUE TITLE
assertEqual does not compare scalar numpy.ndarray with torch.Tensor correctly

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#47948]
## 🐛 Bug

Add a new test

```python
    def test_assertEqual(self, device):
        a = make_tensor((), device, torch.int32, low=-5, high=5)
        self.assertEqual(a.cpu().numpy(), a, rtol=0, atol=0)
```

run this test, it will fail with something like
```
AssertionError: array(-4, dtype=int32) != tensor(-4, device='cuda:0', dtype=torch.int32)
```

It will not fail if you have a non-scalar tensor `a`

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by mruberry** [comment]
We should not only fix this ASAP but improve our test test coverage to ensure this doesn't happen in the future.

**Comment by ngimel** [comment]
Related #43579
