### ISSUE TITLE
How to avoid `torch.onnx.export` use INT64?

### ISSUE THREAD

**Issue by waittim** [pytorch/pytorch#47980]
In order to do inference in browser/JavaScript, I used `torch.onnx.export()` to get the onnx model. 

However, the exported model used INT64 which is invalid for the JavaScript environment. I tried to change the data type in ONNX manually but it brings more error.
May I know how to force the `torch.onnx.export` use INT32? Or is there any way to deal with the INT64 before getting the ONNX model?

Thank you!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by zou3519** [comment]
I'm not sure if this is a feature request, but hopefully one of the onnx folks tagged can answer this

**Comment by shubhambhokare1** [comment]
@waittim Could you please provide a repro of your error.

**Comment by waittim** [comment]
Actually, the error comes from the inference process of the onnx model based on onnx.js.  
```
Uncaught (in promise) TypeError: int64 is not supported
    at f (tensor.ts:388)
    at p (tensor.ts:420)
    at Function.e.fromProto (tensor.ts:245)
    at Function.e.getValue (attribute.ts:147)
    at new e (attribute.ts:34)
    at new s (graph.ts:110)
    at t.buildGraph (graph.ts:260)
    at new t (graph.ts:139)
    at Object.from (graph.ts:77)
    at t.load (model.ts:25)
```
It doesn't mean that the `torch.onnx.export()` have something wrong. I just hope that this function can provide an option to export the model based on INT32. It will be super helpful when people need to deploy the model in the browser because js environment only supports INT32.

BTW, I tried to transfer the onnx model from INT32 to INT64 by hand and noticed that some of the nodes like ConstantOfShape do not support INT32 as input. If you want to add an INT32-option, maybe need to find an approach to bypass this kind of node.

Thank you!

**Comment by shubhambhokare1** [comment]
Hi @waittim Could you please provide a repro of your error. That would be helpful in resolving the issue.

**Comment by shubhambhokare1** [comment]
Hi @waittim If possible could you provide a repro of the issue you are facing?

**Comment by spandantiwari** [comment]
@waittim - please reopen the issue if you have a repro.

**Comment by remixer-dec** [comment]
Someone made [a script](https://github.com/aadhithya/onnx-typecast) to convert exported ONNX int64 models to int32.
