### ISSUE TITLE
Exporting the operator binary_cross_entropy_with_logits to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by poyue0221** [pytorch/pytorch#47998]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by poyue0221** [comment]
Exporting the operator binary_cross_entropy_with_logits to ONNX opset version 12 is not supported

**Comment by gchanan** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/47997.
