### ISSUE TITLE
[feature proposal] An effortless way of loading pre-trained embeddings

### ISSUE THREAD

**Issue by miguelvr** [pytorch/pytorch#4801]
### Summary

Loading pre-trained embeddings is common practice with today's Embeddings. Most often than not, people use large pre-trained Embeddings such as Word2Vec, Glove or FastText with their models. As such there should be an easy and simple way of doing this so common operation.

### Current Behaviour

To load a pre-trained embedding one has to do the following:

    e = nn.Embedding(num_embedding, embedding_dim)
    e.weight = nn.Parameter(pretrained_embedding)

This involves converting a `Tensor` to `Variable` and access the class' arguments to override them.

### Suggested Behaviour

I propose doing this either with an explicit method, or an optional argument in the `__init__` function.

This way you could either initialize an embedding as:

    e = nn.Embedding(num_embedding, embedding_dim, pretrained=pretrained_embedding)

or

    e = nn.Embedding(num_embedding, embedding_dim)
    e.load_pretrained(pretrained_embedding)

--------------

Let me know what you think. I'll do a PR as soon I have some feedback from you guys.

Thank you

**Comment by tomekkorbak** [comment]
That's totally much needed!

Some random thoughts:
1. One frequently wants to freeze pre-trained word embeddings during training, i.e. does not optimize them (as it may sometimes harm dev set performance if training set covers only a small fraction of word embedding layer vocabulary). A flag or method for setting the weight's `requires_grad=False` would be handy. Maybe something like `is_trainable`?
2. When using the pre-trained embeddings, arguments `num_embedding` and `embedding_dim` can be inferred from the proposed `pretrained` argument value. Why not mark them as optional then? Or, to keep the keep the interface clean, we may handle the pre-trained embedding case with a classmethod constructor `Embedding.load_pretrained(pretrained_embeddings)` or a subclass `class PretrainedEmbedding(nn.Embedding)`.
2. torchext provides a super handy wrapper for using pretrained embeddings, namely, [`torchtext.vocab.Vocab.load_vectors`](https://github.com/pytorch/text/blob/master/torchtext/vocab.py#L98). Why not provide a way of populating the embedding layer directly from a torchtext.vocab.Vocab` object?

**Comment by apaszke** [comment]
I agree it would be nice to add this, and the class method proposed by @tomekkorbak seems like a good solution: `Embedding.load_pretrained(embeddings=..., freeze=True)`. This will also infer the dimensions from the given tensor.

**Comment by bheinzerling** [comment]
I have a helper function for this in my Python utils, but native support would be great:

```Python
from torch import nn, Tensor


def emb_layer(keyed_vectors, trainable=False):
    """Create an Embedding layer from the supplied gensim keyed_vectors."""
    emb_weights = Tensor(keyed_vectors.syn0)
    emb = nn.Embedding(*emb_weights.shape)
    emb.weight = nn.Parameter(emb_weights)
    emb.weight.requires_grad = trainable
    return emb
```
