### ISSUE TITLE
can't install pytorch with pip3

### ISSUE THREAD

**Issue by xiaonengmiao** [pytorch/pytorch#4802]
run pip3 install http://download.pytorch.org/whl/torch-0.3.0.post4-cp35-cp35m-macosx_10_6_x86_64.whl
and i get this:
torch-0.3.0.post4-cp35-cp35m-macosx_10_6_x86_64.whl is not a supported wheel on this platform.
Why is this?

**Comment by soumith** [comment]
@xiaonengmiao what OS and processor do you have?
also what is the output of:

```
pip3 --version
```

**Comment by xiaonengmiao** [comment]
@soumith macOS High Sierra version 10.13.2, Inter Core I7 in a early 2013 macbook pro
pip3 --version: pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6).
Thanks.

**Comment by xiaonengmiao** [comment]
@soumith I found the problem! My python version is 3.6, which i thought was 3.5. Thanks anyway.
