### ISSUE TITLE
Can't Resize_() IntTensor

### ISSUE THREAD

**Issue by chbrian** [pytorch/pytorch#4804]
When I try to resize_() a IntTensor, I got the following error:

> targets.resize_(outputs.size(0), outputs.size(1))
> RuntimeError: cannot realloc mapped data at /pytorch/torch/lib/TH/THAllocator.c:382

**Comment by albanD** [comment]
Please use the [forum](https://discuss.pytorch.org/) to ask questions.

In your case, I guess the `targets` comes from numpy? Since `Tensor`s share content with numpy arrays, they cannot be resized, you have to `.clone()` them before.
