### ISSUE TITLE
RuntimeError: NYI: Named tensors are not supported with the tracer

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#48054]
## 🐛 Bug

While running the following script, I got the error: "RuntimeError: NYI: Named tensors are not supported with the tracer" when the input is a scalar. I guess `x[x > 0]` does not support scalar `x`? 

## To Reproduce

```
import torch

def f(x):
    return x[x > 0]

jf = torch.jit.trace(f, torch.tensor(2., device="cuda"))
```
or
```
import torch

def f(x):
    return torch.distributions.HalfCauchy(x).log_prob(x)

jf = torch.jit.trace(f, torch.tensor(2., device="cuda"))
```

## Expected behavior

No error

## Environment

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11
 - GPU models and configuration:
 - Any other relevant information:

cc @gmagogsfm @fritzo @neerajprad

**Comment by gmagogsfm** [comment]
@zou3519 Hi Richard, could you clarify a bit why named tensor is not supported in tracing? Thanks!
