### ISSUE TITLE
[NNC] Fix IR Evaluator Bugs

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#48053]
## 🐛 Bug

[IR Evaluator](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/eval.h#L123) is a class which evaluates the result of  NNC expressions by interpreting them. It is useful for testing correctness, and is also used during compilation for constant folding. 

Currently it is broken for some less commonly-used dtype & op cross-products. Any of the functions in `test_jit_fuser_te.py` that have `unittest.skipIf(not LLVM_ENABLED, "TODO: bugs in ir eval")` contain repros for cases that failed in the evaluator. 

The following op/device failrues are listed below. They  do not all have to be fixed at once - you could start with just fixing a particular op or a particular dtype. 

torch.abs: torch.int8, torch.uint8, torch.int16, torch.int32, torch.int64, torch.float16
torch.frac: torch.float16
torch.__and__: torch.int8, torch.uint8, torch.int16, torch.int64
torch.__or__: torch.int8, torch.uint8, torch.int16, torch.int64
torch.__xor__: torch.int8, torch.uint8, torch.int16, torch.int64

## To Reproduce

1. Build pytorch without LLVM, or remove this [#if](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/kernel.cpp#L1527) in kernel.cpp
1. Comment out the `skipIf` and run either `test_bitwise_ops` or `test_unary_ops` in `test_jit_fuser_te.py`

cc @gmagogsfm

**Comment by penguinwu** [comment]
OK. I'll submit a PR on the bitwise ops support today.
```
torch.and: torch.int8, torch.uint8, torch.int16, torch.int64
torch.or: torch.int8, torch.uint8, torch.int16, torch.int64
torch.xor: torch.int8, torch.uint8, torch.int16, torch.int64
```

**Comment by eellison** [comment]
torch.abs & torch.frac still up for grabs

**Comment by penguinwu** [comment]
@eellison I am looking at `torch.abs` right now. It was a little hard to figure out exactly which `abs` was called, there were so many different implementations :). I am trying to get a good understanding of how the kernel dispatch mechanism works first. This is a good issue for a bootcamper to get an understanding of the interpreter workflow.

**Comment by huiguoo** [comment]
I'll make a try at `torch.frac`.

**Comment by eellison** [comment]
@huiguoo, looks like @penguinwu fixed `torch.frac` as well (thanks!!) Sorry about that. I just opened https://github.com/pytorch/pytorch/issues/48605 which should also be a good bootcamp issue to work on. Feel free to ping me internally with any questions (same goes to @penguinwu)

**Comment by huiguoo** [comment]
Sounds good, thanks @eellison !

**Comment by penguinwu** [comment]
Yes, I am working on the fix for both abs and frac, will submit the PR soon.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
