### ISSUE TITLE
In DistributedSampler docstring, should default value of `num_replicas` be `world_size` not `rank`

### ISSUE THREAD

**Issue by mx-iao** [pytorch/pytorch#48055]
## 📚 Documentation

In [`DistributedSampler`](https://pytorch.org/docs/stable/_modules/torch/utils/data/distributed.html#DistributedSampler) docstring, for description of `num_replicas` below, shouldn't the default say `world_size` instead of `rank`?

```
        num_replicas (int, optional): Number of processes participating in
            distributed training. By default, :attr:`rank` is retrieved from the
            current distributed group.
```

cc @SsnL @VitalyFedyunin @ejguan @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
You are indeed correct, it should be `world_size`. If you would like, a PR fixing this would be much appreciated!

**Comment by mx-iao** [comment]
@rohan-varma Thanks for the reply! Here' is the PR: #48134

**Comment by ejguan** [comment]
Closing the issue as solved.
