### ISSUE TITLE
Pinned Memory, Non-blocking feature doesn't seem to work.

### ISSUE THREAD

**Issue by NickNickGo** [pytorch/pytorch#48065]
## 🐛 Bug

PYtorch pinned memory and non-blocking transfer feature doesn't work. 

## To Reproduce

1. install pytorch
1. run following script:

import time
import torch

DELAY = 100000000
x = torch.randn((1024, 1024), pin_memory=True)

torch.cuda.synchronize()
start = time.time()
torch.cuda._sleep(DELAY)
x.cuda(non_blocking=True)
end = time.time()

print('non_blocking=True', (end - start)*1000.)

torch.cuda.synchronize()
start = time.time()
torch.cuda._sleep(DELAY)
x.cuda(non_blocking=False)
end = time.time()

print('non_blocking=False', (end - start)*1000.)  

In non-blocking case expected time is much lesser, but in reality both are same. 

## Environment

PyTorch version: 1.5.0a0+8f84ded
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 455.32.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.18.1
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.5.0a0+8f84ded
[pip3] torchtext==0.4.0
[pip3] torchvision==0.6.0a0
[conda] magma-cuda101             2.5.1                         1    local
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] msgpack-numpy             0.4.3.2                  py36_0
[conda] nomkl                     3.0                           0
[conda] numpy                     1.18.1           py36h94c655d_0
[conda] numpy-base                1.18.1           py36h2f8d375_1
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.5.0a0+8f84ded          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.6.0a0                  pypi_0    pypi

cc @ngimel

**Comment by gchanan** [comment]
non-blocking doesn't mean faster.

I'd recommend taking a look at our non-blocking tests to see how this functionality is verified:
https://github.com/pytorch/pytorch/blob/49f0e5dfeb64a928c6a2368dd5f86573b07d20fb/test/test_cuda.py#L490-L535

**Comment by NickNickGo** [comment]
I'm not trying to imply that non-blocking makes copy faster. If you take a look at above code snippet, when non_blocking is true, control should return to cpu , and time printed should be lesser than in other case. 

Could you explain why doesn't control return to cpu ?
