### ISSUE TITLE
How use libtorch(or other API) to implement "contiguous", "view", "permute", "transpose" in c++?

### ISSUE THREAD

**Issue by wxyhv** [pytorch/pytorch#48074]
## How use libtorch to implement "contiguous", "view", "permute", "transpose" in c++?
Hello~ I need to transplant python to c++, I don't know how to implement "contiguous", "view", "permute" in c++. I found that libtorch can help me, but I have not find all the "Tensor operations" which I need,such as "contiguous", "view", "permute", "transpose".
The python code shows bellow:

    def process_input_bmm(self, x):
        bsz = x.size(0)  # 18   # x.shape()=[18,192]
        # [B x N] --> [B x g  x N/g]
        x = x.contiguous().view(bsz, self.n_groups, -1)  # [18, 2, 96]

        # [B x g x N/g] --> [g x B  x N/g]
        x = x.transpose(0, 1)  # transpose so that group is first # [2,18,96]

        # [g x B  x N/g] x [g x N/g x M/g] --> [g x B x M/g]
        x = torch.bmm(x, self.weights)  # multiply with Weights #[2,18,96]

        # add bias
        if self.use_bias:
            x = torch.add(x, self.bias)

        if self.feature_shuffle:
            # [g x B x M/g] --> [B x M/g x g]
            # [2,18,96] --> [18,96,2]
            x = x.permute(1, 2, 0)  # permute:序号改变的意思。

            # [B x M/g x g] --> [B x g x M/g]
            # [18, 96, 2] --> [18,2,96]
            x = x.contiguous().view(bsz, self.n_groups, -1)

        else:
            # [g x B x M/g] --> [B x g x M/g]
            x = x.transpose(0, 1)  # transpose so that batch is first

        # feature map normalization
        if self.normalization_fn is not None:
            x = self.normalization_fn(x)

        # feature map activation (or thresholding)
        if self.act_fn is not None:  # self.act_fn:swish
            # print("act_fun in glt: ",self.act_fn) #Swish((sigmoid): Sigmoid())
            x = self.act_fn(x)

        return x

    def forward(self, x):
        """
        :param x: Input of shape [T x B x N] (should work with [B x T x N]
        :return:
        """
        if x.dim() == 2:
            x = self.process_input_bmm(x)
        elif x.dim() == 3:
            T, B, N = x.size()  # [18,1,192]
            x = x.contiguous().view(B * T, -1)  # [1*18,192]
            x = self.process_input_bmm(x)
            x = x.contiguous().view(T, B, -1)
        else:
            raise NotImplementedError

        # dropout
        if self.use_dropout:
            x = self.drop_layer(x)
        return x

The code I need help to write in C++ are as bellow:
        
        x = x.contiguous().view(bsz, self.n_groups, -1)  
        x = x.transpose(0, 1) 
        x = x.permute(1, 2, 0)

If you can help me, please answer me with C++ code which work with libtorch, or the method to implement "contiguous", "view", "permute", "transpose" by libtorch(or other API)!
Thank you Very much!!!
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by gchanan** [comment]
Please ask on the discussion forum, which is linked in your post.
