### ISSUE TITLE
Convolution with float 16 has no speedup vs float32

### ISSUE THREAD

**Issue by ReyhaneAskari** [pytorch/pytorch#4808]
I have tried to use mixed float precision on pytorch. First I followed [this guide ](https://docs.nvidia.com/deeplearning/sdk/pdf/Training-Mixed-Precision-User-Guide.pdf) to train pytorch's [word_language_model](https://github.com/pytorch/examples/tree/master/word_language_model).  And here is the results on Titan V, with cuda 9 and cudnn 7: 

- **mixed float**: 164m38.965s
- **float32** : 247m46.186s

So it's less than 2X speed up but we might have a bottle neck somewhere else. 

I then tried to time a `gemm` with [this code](https://github.com/ReyhaneAskari/pytorch_experiments/blob/32317adb8986f32d3ed4c31f751aef9a036fb26b/torch_float16.py). It's a simple fully connected network with no non-linearity. And this time I actually did see the speed up:
- **mixed float**: 100 sec + 38958 microsec
- **float32** : 710 sec + 302950 microsec

It's almost 7X faster. So I am sure that Tensor Core works. 

I know the speedup also depends on the size of the matrix so I tried to time a simple convolution but I made sure that the size of the matrices are the exact same sizes as my FC case. So [here is the code for convolution](https://github.com/ReyhaneAskari/pytorch_experiments/blob/master/fp_32_16.py) and this was the result:
- **mixed float**: 1.0285618305206299s
- **float32** :  ​1.0206332206726074s

So with convolution there is no speedup. So I would like to know why the convolution does not have the speedup. I'm willing to work on this if you could give me some tips. @nouiz is also supervising me.

**Comment by csarofeen** [comment]
This sounds more like a discussion for the forum's.

Do you have a specific network you're trying to convert for Titan V or are you just trying to see some speedup?

What parameters did you use for word_language_model can you provide a command?

Can you also provide your repo that works in fp16?

**Comment by csarofeen** [comment]
Sorry, just had time to look through your code. Please be careful how you do GPU perf timings. You need to synchronize the GPU before starting and before ending your timer.

With  the gist link posted below I see:
fp32 6.5e-3 s / iteration
fp16 3.8e-3 s / iteration

This is also a strange set of parameters for a convolution as your image is effectively 1 pixel, and as I think you eluded to, would be fine with fully connected layer. Make sure your gemm timings are correct as well please. I only looked at your convolution code.

https://gist.github.com/csarofeen/feee5eb9308f2aa5a9bf1b678f1fa97e

**Comment by ReyhaneAskari** [comment]
Thanks @csarofeen . I wasn't careful with the GPU synchronization. I know the parameterization of convolution is weird because I wanted to have my matrices the exact same size as I had in my Fully connected network (which was basically the gemm) that I had seen the speedup with float16.

**Comment by nouiz** [comment]
Where someone here able to reproduce the speed up from float16 with any
convolution model? If so, is the code available somewhere?

**Comment by soumith** [comment]
@nouiz look at https://github.com/csarofeen/examples/tree/dist_fp16/imagenet

That folder in that branch should have good speedup on Volta with fp16 and has convergence

**Comment by ngimel** [comment]
Please note that you would need pytorch compiled from source for this to work, 0.3 misses some features.

**Comment by csarofeen** [comment]
@nouiz If you run distributed you need top of tree (pytorch installed from github master) and you need to install the libnccl2 debian before you install pytorch and make sure pytorch found it in the build log.

**Comment by ReyhaneAskari** [comment]
@soumith I have seen that but is there any benchmark numbers available somewhere? We tried the world language model and the speedup was less than 2X. I don't know if that's expected or not. Should we expect the same amount of speedup for the ResNet, AlexNet, and VGG on the ImageNet?

**Comment by csarofeen** [comment]
@ReyhaneAskari I will ask once again, what command line arguments did you use for word_language_model? What repo are you using for fp16 training of word_language_model? What specifically is your end goal?

I don't see anything in here that is actually a pytorch issue. Please open a discussion on pytorch forums and post a link here so I can follow it.
