### ISSUE TITLE
Improve tests to cover more configurations

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#4813]
Many of our tests do not test enough combinations of configurations. For example, in double backward tests, lacking cases with some inputs not requiring gradients helped this nasty bug escaping our detection: https://github.com/pytorch/pytorch/pull/4812. We should generally improve tests to cover more configurations.

**Comment by mruberry** [comment]
Closing this issue due to age and actionability. Also, we test way more configurations now!
