### ISSUE TITLE
ATen: Efficient test for x instanceof Variable without dynamic_cast

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4814]
Right now in ATen (C++), given a `Tensor`, there is no efficient way to test if it is a `Variable` without attempting a `dynamic_cast` on it. This is bad because `dynamic_cast` is surprisingly inefficient, which means that in general we don't do Variable tests as often as we should (c.f. #4477). Similarly, we can't easily use `type()` to perform the test, as this gives us one of N `Type` instances, of which there is no convenient way to test if these are a Variable type.

A simple way to fix the problem is to add a virtual function to Tensor or Type that gives us the info we need. Another way to fix the problem is to rethink the way we do `ID()` to somehow make this situation extensible. One thing that makes it awkward to fix this problem is the abstraction barrier between Tensor (which knows nothing about autodiff) and Variable; if we could put some code in Tensor to privilege Variable, it would be easy to solve this problem efficiently.

CC @zdevito @colesbury

**Comment by zdevito** [comment]
I am ok with a virtual function on Type or Tensor. It seems to me that Variable is no less special than isSparse(), which we have a function for already, and adding one small function is not a problem.

**Comment by colesbury** [comment]
I would prefer not requiring a virtual function call to detect if a Tensor is a Variable instance. We need to do this check for every argument to functions in  VariableType. Currently, this check is implemented by:

```c++
arg.type() == *this
```

Where `arg.type()` can be inlined and ends up just being a pointer comparison.

One possibility is to make `is_variable()` non-virtual (and preferably can be inlined). It could be implemented as a field (bitmask?) in `Type.h`. We could do the same for `isSparse()` and `isCuda()`.

**Comment by ezyang** [comment]
@colesbury It seems a bit difficult to make an inline method on `Tensor` which references a non-virtual inlinable function in `Type`, as in the `Tensor` header `Type` is not a fully defined type. Maybe we can forward declare it and then define the method body somewhere else in the headers?

**Comment by ezyang** [comment]
Also, is an undefined tensor a variable?
