### ISSUE TITLE
Make orthonormal initialization the default

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#48144]
## 🚀 Feature

Empirical and theoretical research suggests that (semi-)orthonormal initialization results in better performance for MLPs, CNNs, RNNs, etc. For example:

1. [*Exact solutions to the nonlinear dynamics of learning in deep linear neural networks*](https://arxiv.org/abs/1312.6120)

2. [*All you need is a good init*](https://arxiv.org/abs/1511.06422)

3. [*Convolution aware initialization*](https://arxiv.org/abs/1702.06295)

4. [*Provable benefit of orthogonal initialization in optimizing deep linear networks*](https://arxiv.org/abs/2001.05992)

5. [*Dynamical isometry and a mean field theory of CNNs: how to train 10,000-layer vanilla convolutional neural networks*](https://arxiv.org/abs/1806.05393)

6. [*Orthogonal convolutional neural networks*](https://openaccess.thecvf.com/content_CVPR_2020/html/Wang_Orthogonal_Convolutional_Neural_Networks_CVPR_2020_paper.html)

7. [*Cheap orthogonal constraints in neural networks: a simple parametrization of the orthogonal and unitary group*](https://arxiv.org/abs/1901.08428)

and others. Good initialization is often neglected due to unawareness or laziness (it takes additional boilerplate code to set it up each time). Thus **using the best possible defaults is desirable**. For this reason, I suggest making orthonormal initialization the default.

PyTorch has a function called [`torch.nn.init.orthogonal_`](https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.orthogonal_) that can help with this.

cc @albanD @mruberry

**Comment by mruberry** [comment]
Thank you for the suggestion, @carlosgmartin. I agree we should consider this.

**Comment by albanD** [comment]
My personal opinion is that, yes, it is better but only for some CNN architecture and some applications. But the papers you link actually show that initialization is very dependent on the non linearities you use and depend on the dataset. And they mostly focus on vision datasets alone.
But our Linear layer is widely used with other models (non-conv or GNN or other non-linearities) and more importantly many other applications (text, audio, PPL, etc).

So, given that such a change would mean a massive BC-breaking change, I don't think it is worth all the trouble of doing this update in core pytorch given the limited benefit.

**Comment by carlosgmartin** [comment]
@albanD The benefit is not limited to CNNs. See [1] and [4] for example.

**Comment by Lezcano** [comment]
Disclosure: I'm the author of [7].

I agree with @albanD. I don't think that there is enough evidence yet to be able to say that orthogonal initialisation is better.

Note that [7] does not talk about initialisation but about keeping the weights orthogonal all throughout training, in the very specific  example of an RNN.

[1] works with linear networks (i.e. no activations).

[4] is an interesting theoretical paper, but further experimental research is needed, given that in the paper they just run one experiment with a synthetic dataset.

I believe that in RNNs / LSTMs, orthogonal initialisation can be rather beneficial. That being said, I think that more research is needed in this direction.

On a discussion about updating the initialization of some layers, see https://github.com/pytorch/pytorch/issues/18182

**Comment by Lezcano** [comment]
Closing this one. We can continue the discussion in https://github.com/pytorch/pytorch/issues/18182
