### ISSUE TITLE
tf.nn.raw_rnn

### ISSUE THREAD

**Issue by joinhe** [pytorch/pytorch#48166]
## 📚 Documentation

if pytorch  have the same or similar api?

cc @jlin27 @mruberry @albanD

**Comment by mruberry** [comment]
This question is best asked on our forums, here: https://discuss.pytorch.org/.

PyTorch does support a variety or RNNs. See, for example, https://pytorch.org/docs/master/generated/torch.nn.RNN.html?highlight=rnn#torch.nn.RNN.
