### ISSUE TITLE
Libtorch 1.7,1.6, 1.5 did not work on visual studio 2015

### ISSUE THREAD

**Issue by learner760221** [pytorch/pytorch#48165]
## 🐛 Bug

Hi Guys:
I try to run libtorch 1.7 on visual studio 2015, as your website recommends

![image](https://user-images.githubusercontent.com/74396740/99499414-d6872d00-29b3-11eb-95ae-d167ce2e19e4.png)

![image](https://user-images.githubusercontent.com/74396740/99499497-f74f8280-29b3-11eb-8b80-a34fae18cb73.png)

and solution was created by following CMake from pytorch.org website.
**I encounter 102 errors and have no clues to fix them.**

![image](https://user-images.githubusercontent.com/74396740/99499961-a1c7a580-29b4-11eb-84d5-d68b33e90a8f.png)

**The most important thing is that I follow the exactly same procedures on visual studio 2019, it works........**

## To Reproduce

1. Download libtorch 1.7 debug cpu. (libtorch-win-shared-with-deps-debug-1.7.0+cpu.zip)
2. Use CMake just like pytorch.org recommended.
3. Visual studio professional 2015

## Environment
 - Visual studio professional 2015 Version 14.0.25431.01 Update 3 
 - Win7 x64
 - libtorch-win-shared-with-deps-debug-1.7.0+cpu
 - CMake 3.18.4

Anything wants me to pose to make this issue be reproduced and solved easily is welcome.

**Comment by learner760221** [comment]
I don't know if anyone faces the same problem.
or you guys can recommend me to proper libtorch version which can run on visual studio 2015.

**Comment by learner760221** [comment]
Now I am trying using lower versions of libtorch on visual studio 2015: 
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-1.6.0%2Bcpu.zip
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-1.5.0%2Bcpu.zip
The above links can download correct versions of libtorch, but lower versions can

**Comment by learner760221** [comment]
Libtorch 1.6 on visual studio 2015. 102 errors.
![image](https://user-images.githubusercontent.com/74396740/99617432-51a31e80-2a5a-11eb-8bab-754673231681.png)

Libtorch 1.5 on visual studio 2015. 102 errors.
![image](https://user-images.githubusercontent.com/74396740/99618084-a8f5be80-2a5b-11eb-8f41-10cde69e6531.png)

**Comment by skyline75489** [comment]
I'm not quite following this. According to the blog [here](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/), VS2017 is the first version that comes with builtin cmake support. How do you exactly use cmake to create the project? How did you include the `torch.h` header? You need to give us more information.

**Comment by learner760221** [comment]
@skyline75489 :
1 I use CMake GUI ,assign the CMAKE_PREFIX_PATH and select desired generators, which work well on visual studio 2019.
![image](https://user-images.githubusercontent.com/74396740/99642478-84fba280-2a86-11eb-82e0-5c760468c5e0.png)
![image](https://user-images.githubusercontent.com/74396740/99642937-0f440680-2a87-11eb-9240-eddb7ebe83b0.png)

2 The way of including "torch.h" is set by CMake.
![image](https://user-images.githubusercontent.com/74396740/99643401-95f8e380-2a87-11eb-98cd-15543bd3ee8b.png)

**Comment by learner760221** [comment]
I don't have to use CMake to create the project, **the goal is to use libtorch on Visual Studio 2015.**
if you have any SOP setting, please give us. Because we have googled and tried many ways, none of them works.

**Comment by peterjc123** [comment]
No way because VS 2015 doesn't have complete support for C++ 14. Also, there is no plan to support VS 2015. BTW, is there any reason that you need 2015 instead of 2019?

**Comment by peterjc123** [comment]
> I try to run libtorch 1.7 on visual studio 2015, as your website recommends

Will try to update the docs accordingly.

**Comment by skyline75489** [comment]
Yeah I almost forgot how old VS 2015 is. With a lot of C++ 14 code, VS 2015 will for sure have a hard time compiling the headers. Recently in the doc we even dropped support for VS2017. So guess you really need VS2019 to do this.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: peterjc123 <notifications@github.com>
发送时间: Thursday, November 19, 2020 8:32:06 PM
收件人: pytorch/pytorch <pytorch@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [pytorch/pytorch] Libtorch 1.7,1.6, 1.5 did not work on visual studio 2015 (#48165)


I try to run libtorch 1.7 on visual studio 2015, as your website recommends

Will try to update the docs accordingly.

―

**Comment by learner760221** [comment]
> No way because VS 2015 doesn't have complete support for C++ 14. Also, there is no plan to support VS 2015. BTW, is there any reason that you need 2015 instead of 2019?

Because all of our projects are created on VS 2015.

But I google libtorch in VS 2015, there are many successful cases out there. That is why I ask if there are proper libtorch versions which can be successful run in VS2015.

**Comment by learner760221** [comment]
Here is one of them.
https://www.programmersought.com/article/3387529261/

**Comment by learner760221** [comment]
Hi Guys:
I am trying the older versions of libtorch, and the projects are created by CMake.
I find 1.1, 1.2 libtorch can run on VS 2015 ! 
![image](https://user-images.githubusercontent.com/74396740/99762585-d9109080-2b33-11eb-8f50-badbe4848e04.png)

**Comment by peterjc123** [comment]
@learner760221 I'm glad you figured it out. Since the problem itself is a wont-fix one, I'm going to close it.
