### ISSUE TITLE
ONNX model's input: []

### ISSUE THREAD

**Issue by nehasoni3** [pytorch/pytorch#48173]
Hi
I have a PyTorch model and I want to converted it into another framwork using ONNX.?
My PyTorch model input is torch.Size([1, 133, 83]) and output is <class 'torch.Tensor'> torch.Size([13]).

I convert model into ONNX using this code - 
`torch.onnx.export(
        model,
        input, 
        'model.onnx',
        export_params = True,
        opset_version = 10,
        do_constant_folding = True,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes = {
        'input' :  [0,1],
        'output' : [0,1]
    }
    )`

After ONNX conversion,I get this - 
`import onnx
onnx_model_path = 'model.onnx'
onnx_model = onnx.load(onnx_model_path)
print(onnx_model.graph)
OUTPUT->
node {
  output: "output"
  op_type: "Constant"
  attribute {
    name: "value"
    t {
      dims: 13
      data_type: 7
      raw_data: "6\000\000\000\000\000\000\0008\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000*\000\000\000\000\000\000\000B\000\000\000\000\000\000\0000\000\000\000\000\000\000\0009\000\000\000\000\000\000\000-\000\000\000\000\000\000\000?\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000&\000\000\000\000\000\000\0008\000\000\000\000\000\000\000"
    }
    type: TENSOR
  }
}
name: "torch-jit-export"
output {
  name: "output"
  type {
    tensor_type {
      elem_type: 7
      shape {
        dim {
          dim_param: "output_dynamic_axes_1"
        }
      }
    }
  }
}
`
There is no input node. WHY?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by nehasoni3** [comment]
@zhangguanheng66 I am stuck at this issue. Please do needful and soon.

**Comment by zhangguanheng66** [comment]
cc @houseroad

**Comment by spandantiwari** [comment]
@nehasoni3 - can you please add a proper repro. Also, look at the template for new issues and add other info about your env.

**Comment by spandantiwari** [comment]
@nehasoni3 - please reopen this issues if you have a repro.
