### ISSUE TITLE
[JIT] `aten::eq/ne` should support two bool inputs

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#48174]
## 🚀 Feature

We would like `aten::eq` & `aten::ne` to support comparison between two bool values.

## Motivation

Currently we are using two `aten::__xor__` to implement `eq` logic, this is unnecessary complication. 

API feels awkward that `aten::eq/ne` between two boolean inputs is not supported, while we in fact support two list of bool values: https://github.com/pytorch/pytorch/blob/df0ae244a999a365ac13695cf4682ea30490b157/torch/csrc/jit/runtime/register_prim_ops_fulljit.cpp#L755-L758

## Pitch

We should just extend the old macro to support two bool inputs: https://github.com/pytorch/pytorch/blob/19ede75eb95b2436d5e493497a38c1e6be5ec50b/torch/csrc/jit/runtime/register_ops_utils.h#L576-L580
And then update `aten::eq` & `aten::ne` to the updated macro: https://github.com/pytorch/pytorch/blob/dfd946871a8b9d243c00ce53c08473b2359ba4c1/torch/csrc/jit/runtime/register_prim_ops.cpp#L697-L698

Alternatively, we can just add a special entry for bool, similar to (but with bool instead of device): https://github.com/pytorch/pytorch/blob/dfd946871a8b9d243c00ce53c08473b2359ba4c1/torch/csrc/jit/runtime/register_prim_ops.cpp#L633-L640

cc @gmagogsfm

**Comment by jjsjann123** [comment]
cc'ing @suo per slack conversation.

**Comment by anjali411** [comment]
Fixed in #51844
