### ISSUE TITLE
Support for oneDNN / MKL-DNN on AArch64

### ISSUE THREAD

**Issue by nSircombe** [pytorch/pytorch#48177]
## 🚀 Feature
Enable builds with `MKL-DNN ON` for AArch64.

## Motivation
Since version 1.6, oneDNN has provided limited support for AArch64 builds. From v1.7 onwards, there has been support for optimised primitives, leveraging Arm Compute Library, and the current head of the oneDNN master includes further optimisations, including Winograd convolution support and JITed kernels for the A64fx, which implements a 512bit SVE (Scalable Vector Extension) vector unit.

## Pitch
At present oneDNN is functional on AArch64, with performance improvements and optimisations already available in the master, and more on the horizon. 

However, as it stands `CMakeLists.txt` does not accept the `USE_MKLDNN` option unless `CPU_INTEL` is `ON`. 

It's a minor change to detect an AArch64 CPU and permit the use of `USE_MKLDNN` in that case, and to make sure the correct optimisation flags are passed down.

With basic oneDNN v1.6.x on AArch64 support in PyTorch established, support for the recently integrated Arm Compute Library primitives could be added once PyTorch's default version of oneDNN advances to v1.7 (this would add an optional dependency on Arm Compute Library).

## Alternatives
Not enabling oneDNN on AArch64. This will deny users an easy route to making use of future advances and optimisations in oneDNN for AArch64, that is without manually patching the CMake files as outlined above.

## Additional context
Arm's Tool-Solutions GitHub repository includes Docker resources to build PyTorch images for AArch64 which optionally use both oneDNN and oneDNN with Arm Compute Library primitives: https://github.com/ARM-software/Tool-Solutions/tree/master/docker/pytorch-aarch64 and Linaro make finished images available on DockerHub:https://hub.docker.com/r/linaro/pytorch-arm-neoverse-n1/tags
These demonstrate the feasibility of the proposed changes.

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by nSircombe** [comment]
Hi @zhangguanheng66 (also @gujinghui , @PenghuiCheng, @XiaobingSuper, @jianyuh , @VitalyFedyunin),

I was just wondering what's the best way forward with this? Should a go ahead and raise a PR now to implement?

**Comment by VitalyFedyunin** [comment]
Hello! This looks like reasonable request. Feel free to open PR for it and please include benchmarks with oneDNN on and oneDNN off.

**Comment by ezyang** [comment]
cc @malfet

**Comment by nSircombe** [comment]
Hi,

> Feel free to open PR for it

Yep, will do.

> and please include benchmarks with oneDNN on and oneDNN off.
Is there a specific or minimal set of benchmarks I should include?
Also, this would, initially, be about functionality rather than performance - AArch64 optimisations have only recently started to land in oneDNN.

**Comment by nSircombe** [comment]
Hi,

Sorry for the delayed response - I've raised a PR (https://github.com/pytorch/pytorch/pull/50400). 
At present this doesn't include any benchmarking details. This minimal change is intended to simply enable AArch64 builds with oneDNN, leveraging the library's C++ reference kernels. Recent oneDNN releases provide the capability to use primitives based on Arm Compute Library with the specific goal of improving performance on AArch64 Neon targets, such as Neoverse-N1.

As such, this work doesn't provide a performance boost (using a simple torchvision inference problem) being slower on single-thread performance, although at high thread counts there is some performance gain. 
If you think it's appropriate I can include some details of these simple benchmark runs on the PR, unless there's a specific test / test suite which I should be using for this?
