### ISSUE TITLE
DDP fails to sync params across processes on construction 

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#48188]
...on master as of about a week ago.  Below are two scripts that reproduce the error on my machine.  `training.py` is a simple training script, `broadcast.py` is an even simpler standalone broadcast with args extracted from the DDP constructor call in `training.py`.

Post DDP-init in `training.py`, or equivalently, post-broadcast in `broadcast.py`, some of the param sums match across ranks but some don't, which points towards a race condition.

There are many moving parts here (nccl version, my own system's topology) so I'm very interested to see what happens on other machines.

I looked into `broadcast_coalesced` and didn't see anything obviously weird aside from the non-authoritative rank also copying inputs into its flat buffer, which is redundant work but I don't think it interferes with the nccl call (in theory i suppose it could, if rank 0 pushes data to rank 1's buffer while rank 1 is still copying into it, but I'd be surprised if nccl allowed such an obvious problem).

[broadcast.py.txt](https://github.com/pytorch/pytorch/files/5561758/broadcast.py.txt)
[training.py.txt](https://github.com/pytorch/pytorch/files/5561759/training.py.txt)

broadcast.py shows param sum mismatches post-broadcast on my machine
- on bare metal
- in ngc 20.09 container
- in ngc 20.10

Haven't tried yet on a different machine.

Interestingly, the mismatches I observe are deterministic run-to-run.

**Comment by mrshenli** [comment]
@blefaudeux also reported potential stream sync issues in `c10d` recently.

I am looking into this.

**Comment by mcarilli** [comment]
broadcast.py shows param sum mismatches post-broadcast on my machine
- on bare metal 
- in ngc 20.09 container
- in ngc 20.10

Haven't tried yet on a different system.

**Comment by mrshenli** [comment]
Hey @mcarilli, the sum of tensors before and after broadcast is the same on my dev server. Let me try some more tests.

**Comment by mcarilli** [comment]
You could try inserting a rank-dependent sleep right before the broadcast to throw off different ranks' timelines and stress any synchronization logic:
```
if args.local_rank == 0 (or 1):
    torch.cuda._sleep(int(1e8))
torch.distributed._broadcast_coalesced(...
```

**Comment by mrshenli** [comment]
BTW, which PyTorch commit are you on?

**Comment by mcarilli** [comment]
Ha!
> two different GPUs

was the key.  I don't think it's a DDP or broadcast bug.  I think it's a difference in how the sum() is carried out on the two different GPUs (e.g. if blocks are organized differently, the numerics of a sum on identical data could easily end up with slight differences).

If I make sure both processes carry out the sum on the titan V, via
``` 
print("{} {}".format(args.local_rank, tuple(t.to(device="cuda:0").sum().item() for t in tensors)),
        flush=True)
```
sums printed by both ranks are bitwise identical.

Now the interesting question becomes, do we expect an FP32 sum to yield different results on different generations?  FP32 hardware for each "+" should behave identically, but
- maybe something in Pytorch changes associativity (ie block organization) of the sum kernel when it runs for different generations
- maybe nvcc reorders instructions and changes associativity when compiling the sum kernel for different generations

Anyway, closing as NAB from c10d's perspective.

**Comment by mrshenli** [comment]
Thanks @mcarilli for getting to the bottom to this!
