### ISSUE TITLE
Doc for global module hooks is not added to the docs website

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#48198]
It should be added to the `.rst` so that they appear on the website.
Doc is already inline here https://github.com/pytorch/pytorch/blob/df88cc3f7f5c13221a93d7d3d38e681a3d5a6b6a/torch/nn/modules/module.py#L89-L115

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
We would accept a PR fixing this.

**Comment by AishwaryaKalloli** [comment]
I searched for similar function `def register_module_forward_pre_hook(hook: Callable[..., None]) -> RemovableHandle:` in the website but could not find any.
I also looked at pytorch/docs/source/nn.rst, but given function does not belong to any class either. So I am not getting the .rst file where we have to add this function.
Could you help me in understanding where to add the changes.

**Comment by albanD** [comment]
The torch.nn doc has been reworked to split it into multiple pages so I'm not sure anymore :D 
It would be nice to have it on the `Module` page but it is generated automatically so it might be tricky to add it there.

But maybe we could add a new section at the bottom of `nn.rst` for global Module hooks and add these three functions there.

**Comment by AishwaryaKalloli** [comment]
Ok, I will add them in a new section in `nn.rst`.

**Comment by AishwaryaKalloli** [comment]
[created a pr here](https://github.com/pytorch/pytorch/pull/48373)

**Comment by AishwaryaKalloli** [comment]
One of the CI Circle build failed with `Nov 22 13:13:13 requests.exceptions.HTTPError: 502 Server Error: Error with server connection for url: https://graph.facebook.com/scribe_logs`
It seems unrelated to my code though, so I wanted to check if the build passes if I retrigger it. Is there a way to do so? Or will the PR be reviewed as it is? 
New here so not sure how it works :p

**Comment by mruberry** [comment]
Sorry about the build failure, @AishwaryaKalloli. You don't need to do anything. It will be reviewed as-is.

**Comment by AishwaryaKalloli** [comment]
Oh okay. Thanks!
