### ISSUE TITLE
[docs] Missing docs online for F.softplus

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#4819]
## nn.Tanhshrink
http://pytorch.org/docs/master/nn.html?highlight=shrink#torch.nn.functional.tanhshrink

Equation `\(Tanhshrink(x) = x - Tanh(x)\)` is not rendering properly.

## nn.Softshrink
http://pytorch.org/docs/master/nn.html?highlight=shrink#torch.nn.Softshrink

Latex not rendered:
```
\[\begin{split}\text{SoftShrinkage}(x) =
\end{split}\]
``` 

## nn.functional.logsigmoid
http://pytorch.org/docs/master/nn.html?highlight=logsigmoid#torch.nn.functional.logsigmoid

Latex not rendered
``` 
\(\text{LogSigmoid}(x) = \log \left(\frac{1}{1 + \exp(-x_i)}\right)\)
```

## nn.functional.softplus
http://pytorch.org/docs/master/nn.html?highlight=softplus#torch.nn.functional.softplus

docs are missing altogether

## nn.Softplus
http://pytorch.org/docs/master/nn.html?highlight=nn%20softplus#torch.nn.Softplus

Latex not rendered:
```
\(\text{Softplus}(x) = \frac{1}{\beta} * \log(1 + \exp(\beta * x))\)
```

and image is missing

## nn.functional.tanh and nn.Tanh
http://pytorch.org/docs/master/nn.html?highlight=tanh#torch.nn.functional.tanh
http://pytorch.org/docs/master/nn.html?highlight=tanh#torch.nn.Tanh

Latex not rendered:
```
\(\text{Tanh}(x) = \tanh(x) = \frac{\exp(x) - \exp(-x)}{\exp(x) + \exp(-x)}\)
```

**Comment by rubiagatra** [comment]
Could I create pull request?

**Comment by apaszke** [comment]
@rubiagatra sure, go ahead!

**Comment by vadimkantorov** [comment]
added logsigmoid and softplus

**Comment by zou3519** [comment]
Last action item on this issue is writing the [functional.softplus](http://pytorch.org/docs/master/nn.html?highlight=softplus#torch.nn.functional.softplus) docs.

**Comment by SsnL** [comment]
closing in favor of #9886
