### ISSUE TITLE
Document torch.distributed.destroy_process_group()

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#48203]
## 📚 Documentation

This is a useful function to de-init a PG in order to re-initialize it, for example during error handling/retries for distributed training. However, the function is not documented in the docs currently: https://pytorch.org/docs/master/distributed.html.

cc @jlin27 @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by brando90** [comment]
what is the progress on this?

Where should we be calling this function?

**Comment by benni-ser** [comment]
Hi there, 

I was running into the same issue today. Unfortunately, there is still no documentation. However, in the Pytorch DDP tutorial the function is called at the end of each process:

https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

Hope this helps!
