### ISSUE TITLE
Incorrect answer when using scatter_add_ and broadcasting,   Feature Request: scatter_add broadcasting

### ISSUE THREAD

**Issue by sbb-gh** [pytorch/pytorch#48214]
## 🐛 Bug

Incorrect answer when using scatter_add_ and broadcasting

## To Reproduce

```python
import torch as t
import itertools

Id_max = 10
I,J = 13,14

index = t.randint(0,Id_max,(1,J))
src = t.rand(I,J)

# ground truth
y_correct = t.zeros(I,Id_max)
for i,j in itertools.product(range(I),range(J),):
    j_idx = index[0,j]
    y_correct[i,j_idx] = y_correct[i,j_idx] + src[i,j]

# incorrect answer with broadcasting
y1 = t.zeros(
        I,Id_max)
y1.scatter_add_(
    src=src,
    index=index,
    dim=1,
)
print(t.max(t.abs(y_correct-y1)))

# correct answer without broadcasting
index = index.expand(I,-1)
y2 = t.zeros(
        I,Id_max)
y2.scatter_add_(
    src=src,
    index=index,
    dim=1,
)
print(t.max(t.abs(y_correct-y2)))
```

## Environment

Tested on:
(1) CPU only
(2) PyTorch 1.7 with cuda 11
(3) PyTorch 1.6 with cuda 9.2

cc @ezyang @gchanan @zou3519 @bdhirsh @jlin27 @mruberry @bhosmer @smessmer @ljk53 @ailzhang

**Comment by sbb-gh** [comment]
Please remember to indent the for loop

**Comment by zhangguanheng66** [comment]
You can use markdown to keep the format of code snippet.

**Comment by sbb-gh** [comment]
@zhangguanheng66 
Addressed.  
I also have a feature request regarding scatter_add_ , may I put that here?

**Comment by zhangguanheng66** [comment]
Yup. You can put them together and update the title of the PR.

**Comment by ngimel** [comment]
High priority because it's a silent correctness issue. Related #40359. cc @nikitaved

**Comment by nikitaved** [comment]
I do not think it is a bug. Scatter/Gather do not support broadcasting. From the documentation, scatter will iterate over `prod(index.shape)` elements.
In the first example with `y1` `index` is a row vector, so the first row of `y1` is being modified. The second example extends `index` to the whole matrix. As an example, I run the script with tuned down sizes:
```
src:
tensor([[0.6997, 0.2286, 0.8861, 0.7655, 0.9966],
        [0.2377, 0.4726, 0.5150, 0.7807, 0.4318],
        [0.8590, 0.2072, 0.3091, 0.6958, 0.2212],
        [0.7363, 0.0210, 0.3645, 0.5302, 0.6708]])

index:
tensor([[3, 2, 0, 2, 2]])

y1:
tensor([[0.8861, 0.0000, 1.9906, 0.6997],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])


y2:
tensor([[0.8861, 0.0000, 1.9906, 0.6997],
        [0.5150, 0.0000, 1.6851, 0.2377],
        [0.3091, 0.0000, 1.1242, 0.8590],
        [0.3645, 0.0000, 1.2220, 0.7363]])

```

**Comment by sbb-gh** [comment]
@nikitaved  could you make that clear in the documentation?  If you only wanted the first dimension of index, then you could choose y to have a different shape.  

Also I have a PR request:  Can you make scatter_add broadcastable?

**Comment by nikitaved** [comment]
@sbb-gh , the implication comes from the restriction on shapes. The documentation says, in loose terms, that `index.shape <= src.shape` for non-reduction dims. So, you can not index beyond the shape of `index`.

Why not broadcast? It is easier to explain using `gather`. If you run, using your script, say, `src.gather(0, index)/src.gather(1, index.t())`, you will select a single value from each column/row. So, broadcasting does not work here, `scatter` is somewhat an inverse of `gather`, so the behavior is preserved.

**Comment by gchanan** [comment]
We should document explicitly that gather and scatter_* do not broadcast, it's a fairly common misconception.

**Comment by sbb-gh** [comment]
Thank you for your engagement and replies.  Please, if you have time, change the documentation.

I also have the following question:

Suppose we have two tensors with shape:

a:  Q x 1 x S x T

b:  Q x R x S x 1

and index:

c : Q x 1 x S x T

Unfortunately multiplying a,b together (with broadcasting), leads to memory issues. 

Is it possible to modify the scatter_add_ function to perform:

intialize y_out to zeros.
for indices  q,r,s,t:
       s_out = c(q,0,s,t)
       y_out(q,r,s_out) = y_out(q,r,s_out) +  a(q,0,s_out,t)*b(q,r,s_out,0)    


Thank you all for your time

**Comment by ezyang** [comment]
@sbb-gh That is a very interesting question. I don't know if there is a way to do what you are requesting without some sort of new operator or fusion. Would you agree that it is not related to this issue, though, because you need the multiplication as well (which is not standard scatter add?) In that case, I'd suggest filing a new issue for it.

**Comment by malfet** [comment]
High-pri for a doc fix.
@sbb-gh, If you feel that new op is needed, please open a separate feature.
