### ISSUE TITLE
Assigning to an index of a sparse tensor is a no-op

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#48225]
Sample snippet demonstrating the issue:

```
a = torch.randn((2, 2)).to_sparse()
a
: tensor(indices=tensor([[0, 0, 1, 1], [0, 1, 0, 1]]),
       values=tensor([ 0.1138, -0.4513, -2.5902,  0.4013]),
       size=(2, 2), nnz=4, layout=torch.sparse_coo)

a[0][0] = 999
a
: tensor(indices=tensor([[0, 0, 1, 1], [0, 1, 0, 1]]),
       values=tensor([ 0.1138, -0.4513, -2.5902,  0.4013]),
       size=(2, 2), nnz=4, layout=torch.sparse_coo)
```

Marking high priority as I believe this qualifies as a silent correctness issue. 

cc @ezyang @gchanan @zou3519 @bdhirsh @aocsa @nikitaved @pearu @mruberry

**Comment by gchanan** [comment]
Confirmed it's an issue at least as far back as 1.4.0.

**Comment by mattip** [comment]
The code for `__setitem__(tuple)` and `__getitem__(tuple)` both end up in [`select_sparse`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorShape.cpp#L914), (via `THPVariable_getitem`and `THPVariable_setitem` respectively, which call `applySlicing`). `select_sparse` calls `_sparse_coo_tensor_with_dims_and_tensors` which is a dispatch-defined wrapper for [`new_with_dims_and_tensor_sparse`](https://github.com/pytorch/pytorch/blob/edf751ca2fededecdd9366874c761431c0f61f01/aten/src/ATen/native/sparse/SparseTensor.cpp#L94). Somewhere along the line, the values are copied, which prevents assignment.

**Comment by mattip** [comment]
FWIW, scipy does not allow assigning to a COO sparse matrix, and will complain when assigning to a CSR one:
```
>>> m = scipy.sparse.rand(3, 4, density=0.25)
>>> m
<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in COOrdinate format>
>>> m[0,0] = 100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'coo_matrix' object does not support item assignment

>>> m = scipy.sparse.rand(3, 4, density=0.25, format='csr')
>>> m[0,0] = 100
.../python3.8/site-packages/scipy/sparse/_index.py:82: \
    SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. \
    lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])

>>> m.todense()
matrix([[100.        ,   0.        ,   0.        ,   0.2128684 ],
        [  0.        ,   0.        ,   0.        ,   0.93232551],
        [  0.        ,   0.98662986,   0.        ,   0.        ]])
```

**Comment by mruberry** [comment]
An error message sounds like an appropriate solution to this issue.
