### ISSUE TITLE
pytorch profiler to analyze memory consumption

### ISSUE THREAD

**Issue by myungkeun-cho** [pytorch/pytorch#48244]
hi.

I'm using a pytorch profiler to analyze memory consumption.

I want to know the units.

Mb, Kb, b

Does this means bytes?? or bits?
Mega bytes? or Mega bits?

![image](https://user-images.githubusercontent.com/73901287/99639749-58965500-2a8b-11eb-8eea-ec52456abcc1.png)

**Comment by izdeby** [comment]
Hey, please forward questions to our [forum](https://discuss.pytorch.org/)
