### ISSUE TITLE
torch.cat: Unclear error message when concatenating Tensor with Variable

### ISSUE THREAD

**Issue by yasumori** [pytorch/pytorch#4828]
When concatenating Tensor type with Variable, torch.cat fails because of type incompatibility. However, the error message is not clear on the cause of the error. It would be helpful to explicitly show that concatenation of Tensor with Variable type is not allowed.

```python
x = torch.randn(2, 2)
y = Variable(torch.randn(2, 2))
torch.cat((x, y), 0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cat received an invalid combination of arguments - got (tuple, int), but expected one of:
 * (sequence[torch.FloatTensor] seq)
 * (sequence[torch.FloatTensor] seq, int dim)
      didn't match because some of the arguments have invalid types: (tuple, int)
```

**Comment by apaszke** [comment]
Variables will soon be merged with tensors. Thanks for the report but won’t fix.
