### ISSUE TITLE
[doc] Error "You've reached a dead end" when opening torch.__config__ in the docs

### ISSUE THREAD

**Issue by mariosasko** [pytorch/pytorch#48287]
## 📚 Documentation

When I open `torch.__config__`'s page in the docs (tested on master and 1.7), this is what I get:
 

![dead-end](https://user-images.githubusercontent.com/47462742/99743436-f9a9fd80-2ad5-11eb-9618-d8fda876fcae.PNG)

[Link](https://github.com/pytorch/pytorch/blob/master/docs/source/__config__.rst) to the .rst file.

cc @ezyang @zou3519 @jlin27 @mruberry

**Comment by mrshenli** [comment]
I confirm that, the link is https://pytorch.org/docs/master/__config__.html?highlight=config#module-torch.__config__

And that page is searchable. 
<img width="884" alt="Screen Shot 2020-11-20 at 11 42 47 AM" src="https://user-images.githubusercontent.com/16999635/99825821-8af49080-2b25-11eb-9bcd-d0a5f195e7f7.png">

**Comment by mruberry** [comment]
Thank you for reporting this issue, @mariosasko.

Looks like there's an active PR in this space: https://github.com/pytorch/pytorch/pull/47861.

@robieta, would you comment on this issue?

**Comment by robieta** [comment]
My PR is unrelated to this issue.

**Comment by mruberry** [comment]
In that case, I think we would accept a PR removing these links from the doc.

**Comment by mruberry** [comment]
OK; fixing it also seems good. I originally thought these weren't meant to be documented.

**Comment by vadimkantorov** [comment]
@mruberry Could you please reopen this? This is happening again, for both stable and master

@malfet It would be cool to have some simple robot testing all links from the docs for 404

**Comment by malfet** [comment]
Hmm, was it actually fixed at some point?

**Comment by vadimkantorov** [comment]
Doesn't hurt to at least know about them: maybe they are not so numerous?..
