### ISSUE TITLE
Enable RRef proxy helpers to work with ScriptModule

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#48294]
## 🚀 Feature
We are adding support for transferring ScriptModule over the wire in RPC, see https://github.com/pytorch/pytorch/pull/48293. However, this does not currently work with RRef helper, due to the check on this line: https://github.com/pytorch/pytorch/blob/master/torch/distributed/rpc/rref_proxy.py#L18.

There is a workaround, however, which is to implement the helper without the check in user code:
```
def run(rref, func_name, args, kwargs):
    return getattr(rref.local_value(), func_name)(*args, **kwargs)

def rref_isinstance(rref, cls_to_check):
    return isinstance(rref.local_value(), cls_to_check)

# Ensure rref is a scriptModule.
ret = rpc.rpc_sync(remote_script_module.owner(), rref_isinstance, args=(remote_script_module, torch.jit.ScriptModule))
assert ret
# Run remote forward pass
remote_forward_output = rpc.rpc_sync(remote_script_module.owner(), run, args=(remote_script_module, "forward", (), {}))
```

Proposal is instead of checking for the exact type, such as `type(x) is A` which is what we are doing right now, we check the equivalent of `isinstance(x, A)` for the rref.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @gmagogsfm

**Comment by gmagogsfm** [comment]
Doesn't seem like this issue needs any triage from JIT side. Removing from JIT triage queue.
