### ISSUE TITLE
Add L-BFGS

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#483]
For NeuralStyle and DeepDream.

**Comment by oleg-kachan** [comment]
![](http://www.caam.rice.edu/~dennis/images/Broyden-Fletcher-Goldfarb-Shanno.jpg)

**Comment by timn2008** [comment]
The photo https://github.com/pytorch/pytorch/issues/483#issuecomment-273646071 seems to be fake, as David Shanno (1938-2019) in his Interview of 2017 says that "I had never met Charles Broyden. " Is it a kind of deep fake ?
