### ISSUE TITLE
[Feature Request] Allow Dataloader workers to sleep instead of busy wait

### ISSUE THREAD

**Issue by benvcutilli** [pytorch/pytorch#4830]
Is there any way we can get the workers in Dataloader to sleep when not doing anything? The busy waiting it currently does in the process's "loop" takes up a lot of resources, and I am getting complaints about them as we are using a shared machine. Maybe you'd have one sentinel process that would wake up the others every time the Dataloader iterator gets asked for a new batch.

I'm on Linux `3.10.0-693.11.6.el7.x86_64` (output from `uname -r`), with `torch.__version__` stating `'0.3.0.post4'` installed via `conda`. I am running Python 3.6.1 (Anaconda version). Not sure what my CUDA or cuDNN versions are. I have 4 Titan X Pascals.

Thanks!

**Comment by apaszke** [comment]
Workers are never spinning in a busy loop. If the batch queue is saturated they will sleep on a semaphore or trying to read from a pipe.

**Comment by benvcutilli** [comment]
I forgot that queues can do that. Well, at least I'm vindicated on my end. Sorry for wasting your time.
