### ISSUE TITLE
CUDA error running benchmark script on multi-GPU

### ISSUE THREAD

**Issue by SeanNaren** [pytorch/pytorch#4831]
Running into an issue running a [benchmark](https://github.com/SeanNaren/deepspeech.pytorch/blob/distributed/benchmark.py) script available in the deepspeech.pytorch library (I can try to create a smaller reproducible script if this helps). The script runs fine for 1/2/4/8 GPUs with a batch size of 32 per GPU (1 GPU batch size is 32, 2 GPUs batch size is 64 etc), but for 3/5/6/7 GPUs I run into the below error:

```
CUDA_VISIBLE_DEVICES="0,1,2" python benchmark.py --batch-size 96
Number of parameters: 38067968
Running dry runs...
  0%|                                                                        | 0/2 [00:00<?, ?it/sTHCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensorMath.cu line=35 error=11 : invalid argument

Traceback (most recent call last):
  File "benchmark.py", line 116, in <module>
    run_time = run_benchmark()
  File "benchmark.py", line 102, in run_benchmark
    iteration(data)
  File "benchmark.py", line 92, in iteration
    optimizer.step()
  File "/home/sean.narenthiran/anaconda3/lib/python3.6/site-packages/torch/optim/sgd.py", line 90, in step
    buf = param_state['momentum_buffer'] = torch.zeros_like(p.data)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensorMath.cu:35
```

- OS: Ubuntu 16.04
- PyTorch version: 3.0
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: cuda 9.0/ cuDNN 7
- GPU models and configuration: p2.x8 large instance (8 K80s)

**Comment by zou3519** [comment]
Thanks for reporting this, @SeanNaren. A smaller reproducible script would be very helpful.

One possibility I can think of when seeing your output is that your batch size isn't a multiple of the number of GPUs you're using. The [docs for DataParallel](http://pytorch.org/docs/master/nn.html?highlight=dataparallel#torch.nn.DataParallel) say that the batch size should be a multiple of the number of gpus. If this is really the problem, I do agree the error should be clearer.

**Comment by SeanNaren** [comment]
Thanks man, will hopefully get around to making a script to reproduce this easily :)

**Comment by SeanNaren** [comment]
haven't ran into this issue in a while, gonna close it for now...
