### ISSUE TITLE
Documentation: default values for __init__ not documented

### ISSUE THREAD

**Issue by DavidNemeskey** [pytorch/pytorch#4832]
I don't know if documentation issues should be reported here, so if not, please point me to the right place.

I have found an issue with the offical pytorch documentation on pytorch.org. Apparently, `__init__` is handled differently from the rest of the class methods, because it doesn't have a proper function documentation block (which starts with the function signature otherwise). This shouldn't be a problem, as the **Parameters** block is still there, but

1. the latter does not show the default value for optional parameters -- it is only available in the signature.
1. this particular **Parameters** block doesn't always specify which arguments are optional; the blocks for regular functions / methods do.

Two examples:
  - [Variable](http://pytorch.org/docs/master/autograd.html#torch.autograd.Variable): there is no clue as to the default value of `requires_grad`, nor to the fact that it is _optional_. The function below (`backward`) specifies its arguments (e.g. `create_graph`) fully
  - [Parameter](http://pytorch.org/docs/master/nn.html#parameters) marks `requires_grad` _optional_, though still no mention of the default value

Though the links lead to the documentation of 0.4.0, the same issues exist in earlier versions (at least in 0.3.0).

**Comment by mruberry** [comment]
Closing this issue due to age. Although our documents certainly do need updating and this is the right place to file such issues. If you still notice doc issues like this please open a new issue.
