### ISSUE TITLE
[FR] .all and .any should have dim argument

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#48352]
It would be much easier to have that than emulate using arithmetics, which doesn't work well, e.g., https://github.com/pytorch/pytorch/issues/48351

cc @jlin27 @mruberry

**Comment by kshitij12345** [comment]
`all` and `any` do have function as well method variants which take `dim`
https://github.com/pytorch/pytorch/blob/4ed7f36ed181ee784f9904d5eabf073701e1fb78/aten/src/ATen/native/native_functions.yaml#L471-L498

They are not documented though.

**Comment by ngimel** [comment]
Leaving open for doc update.

**Comment by kshitij12345** [comment]
#47878 updates the documentation as well
