### ISSUE TITLE
C++ tensor cuda stream API docs have syntax issues

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#48358]
## 📚 Documentation

The code over at https://pytorch.org/cppdocs/notes/tensor_cuda_stream.html contains some instances of `torch.device` (such as `torch.device(torch::kCuda)`) which is presumably meant for Python, and the C++ code containing these instances does not compile. This should probably be `torch::device` instead. 

cc @jlin27 @mruberry

**Comment by ngimel** [comment]
Added in #45754, cc @glaringlee

**Comment by glaringlee** [comment]
Will correct it shortly.

**Comment by glaringlee** [comment]
fixed
