### ISSUE TITLE
Inconsistency between advanced indexing of Tensors and Variables

### ISSUE THREAD

**Issue by dancsi** [pytorch/pytorch#4836]
I have noticed an inconsistency while trying to perform advanced indexing of `Tensor`s and `Variable`s. For some reason, `Variable`s seem to support more complicated indexing operations than `Tensor`s. 
Here is an example:
```Python
>>> t = torch.arange(1,10) * 10
>>> i = torch.arange(6).type(torch.LongTensor).view(2, 3)
>>> i
 0  1  2
 3  4  5
[torch.LongTensor of size 2x3]
>>> t[i]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Indexing a Tensor with a torch.LongTensor triggers index_select semantics, and thus we expect an empty tensor or a vector, but the indexing Tensor passed has 2 dimensions
```
However, when I wrap `t` in a `Variable`, I get the expected result:
```Python
>>> torch.autograd.Variable(t)[i]
Variable containing:
 10  20  30
 40  50  60
[torch.FloatTensor of size (2,3)]
```
For reference, this is the result returned by numpy, as well:
```Python
>>> t.numpy()[i.numpy()]
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)
```
I have tried this with source-built pytorch 0.4 from master (currently at 8400c57daaed4ebf870c7b08cfcb94fd4405aac8), running on Linux on CPU. The bug can not be replicated on version 0.3.

**Comment by zou3519** [comment]
We're in the process of merging Variable and Tensor. When that happens, Tensor will gain the Variable methods so all will be well.

**Comment by dancsi** [comment]
Ok, thanks for the quick reply. From the documentation it seemed that this is already the case, and thus the report...
