### ISSUE TITLE
[feature request] torch.prod supports torch.Size

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#4837]
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): conda
- A script to reproduce the bug.
`torch.prod(torch.FloatTensor(10, 3, 3, 3).shape)`
- Error messages and/or stack traces of the bug
```
  File "<ipython-input-26-515266e5c0dc>", line 1, in <module>
    torch.prod(torch.FloatTensor(10, 3, 3, 3).shape)
TypeError: torch.prod received an invalid combination of arguments - got (torch.Size), but expected one of:
 * (torch.FloatTensor source)
      didn't match because some of the arguments have invalid types: (!torch.Size!)
 * (torch.FloatTensor source, int dim)
 * (torch.FloatTensor source, int dim, bool keepdim)
```
- Context around what you are trying to do

I'm trying to count the total parameters of my model. I'd like to have the `torch.prod` func be able to take arguments of `torch.Size`. Same for the other arithmetic operations with `torch.Size`. I don't want to reinvent the wheel with iterating over dimensions neither import numpy to do the job.

**Comment by SsnL** [comment]
`torch.FloatTensor(10, 3, 3, 3).numel()` gives you what you want.
