### ISSUE TITLE
libtorch 1.7.0  count_nonzero bug

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#48381]
libtorch 1.7.0 linux cxx11

-------------
t=torch.tensor([[1,2,3,0,0,0,0],[3,4,5,6,0,0,0]])
aa=torch.count_nonzero(t,1)
print(aa)
tensor([3, 4])
------------
auto t=torch::tensor({{1,2,3,0,0,0,0},{3,4,5,6,0,0,0}});
    auto aa=torch::count_nonzero(t,{1});
// auto aa=torch::count_nonzero(t,1);
    std::cout<<aa<<std::endl;

 error: call of overloaded ‘count_nonzero(at::Tensor&, <brace-enclosed initializer list>)’ is ambiguous

**Comment by ngimel** [comment]
Do either
```
     c10::optional<int64_t> dim(1); 
     return torch::count_nonzero(input,dim); 
```
or 
```
   at::IntArrayRef dim{2,3};       
   return torch::count_nonzero(input,dim); 
```
