### ISSUE TITLE
INTERNAL ASSERT FAILED for maximum

### ISSUE THREAD

**Issue by bderrett** [pytorch/pytorch#48393]
## 🐛 Bug

When `torch.maximum` is called with a CUDA tensor and a 0-dimensional CPU tensor, a RuntimeError with the message 'INTERNAL ASSERT FAILED' is shown, instead of the 'Expected all tensors to be on the same device...' message.

## To Reproduce

Run:
```
>>> torch.maximum(torch.ones(1, device='cuda:0'), torch.tensor(0))
RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch.
```
## Expected behavior

No internal assert failure.

## Environment

Collecting environment information...
PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro GV100
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0+cu101
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.1           py38hbc911f0_0
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] torch                     1.8.0a0                  pypi_0    pypi

cc @ngimel

**Comment by HeegonJin** [comment]
same happened to me

**Comment by Pranav-India** [comment]
I am having same error.. PyTorch version == 1.7.0 and cuda 10.1

**Comment by guol-fnst** [comment]
I could fix that. But I am not sure whether this PR can be accepted.

**Comment by guol-fnst** [comment]
Hi @ngimel Dose this need to be fixed?

**Comment by ngimel** [comment]
Yes, it needs to be fixed, but not in Loops.cuh. In MaxMinElementwiseKernel.cu the functions should call gpu_kernel_with_scalars instead of gpu_kernel.
