### ISSUE TITLE
torch.meshgrid docstring is missing

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/pytorch#48395]
## 📚 Documentation

As per title, torch.meshgrid docstring is missing in latest stable and master docs, it shows correctly in 1.6.0 docs.
See:
https://pytorch.org/docs/stable/generated/torch.meshgrid.html#torch.meshgrid
https://pytorch.org/docs/master/generated/torch.meshgrid.html#torch.meshgrid

cc @ezyang @gchanan @zou3519 @bdhirsh @jlin27 @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @ydcjeff. That's odd it's missing.

We would accept a PR fixing this.

**Comment by Rajathbharadwaj** [comment]
Hi, I would like to work on this.

**Comment by mruberry** [comment]
> Hi, I would like to work on this.

That's great, @Rajathbharadwaj! @ydcjeff has a PR you may want to review, too.

**Comment by Rajathbharadwaj** [comment]
@mruberry Awesome, I will.

**Comment by Rajathbharadwaj** [comment]
> @mruberry Awesome, I will.

Looks like @ydcjeff has fixed the docs.

**Comment by mruberry** [comment]
Thanks again for noticing and fixing this issue, @ydcjeff!
