### ISSUE TITLE
The report of codecov is incorrect.

### ISSUE THREAD

**Issue by CalvinXKY** [pytorch/pytorch#48392]
## 🐛 Bug

The codecov shows a wrong report  while added a new func in torch/cuda/memory.py. see: #48172 
compare diff shows:
<img width="865" alt="codecov_rst" src="https://user-images.githubusercontent.com/33612283/99968820-9d482600-2dd4-11eb-8d96-cc8a70eb2f70.PNG">

However, it does have a relevant test from 394L to 421L in "/test/test_cuda.py".  [file](https://github.com/pytorch/pytorch/pull/48172/files)

I checked it using coverage with the test_cuda.py in local env.  
The report shows:
<img width="553" alt="local_test" src="https://user-images.githubusercontent.com/33612283/99968863-a76a2480-2dd4-11eb-9334-1002a4ece8ce.PNG">

According to the result, the new func (set_per_process_memory_fraction) is certainly coveraged. 
Thus, I doubt that the .coverage file might be not combined correctly or be covered by other tests.

## Expected behavior

The codecov reports correct result.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
cc @kostmo - maybe we should get a better module than tests for issues like this, @malfet? Maybe test/builds vs OSS tests?

**Comment by rgommers** [comment]
There are many reasons why code coverage results can be incorrect. They're documented at https://docs.codecov.io/docs/unexpected-coverage-changes, some reasons given:

1. Adding or removing tests.
2. Failing to upload coverage reports, or a different number of reports between head and base
3. Time sensitive tests.
4. Missing coverage reports or failed builds.
5. Dependencies changed resulting in a different execute plan.
6. Encrypted variables may prevent some execution paths.
7. In the case of changes to a PR, the base or head commits may not have had an uploaded report, or may not be the commit you expect

Related issue: gh-44187.

**Comment by malfet** [comment]
Codecov has been disabled, so I guess we can close this one
