### ISSUE TITLE
Sum in place of tensor and its transpose 

### ISSUE THREAD

**Issue by kamenbliznashki** [pytorch/pytorch#48401]
## 🐛 Bug

Getting different results when summing in-place a tensor and its transpose.

## To Reproduce

```
a = torch.arange(4).reshape(2,2)
a += a.t()
# tensor([[0, 3],
#         [5, 6]])

b = torch.arange(4).reshape(2,2)
b = b + b.t()
# tensor([[0, 3],
#         [3, 6]])

# Numpy (1.19.1) produces consistent output:

c = np.arange(4).reshape(2,2)
c += c.T
# array([[0, 3],
#        [3, 6]])

d = np.arange(4).reshape(2,2)
d = d + d.T
# array([[0, 3],
#        [3, 6]])

```

## Expected behavior

a += a.t() and a = a + a.t() should produce the same result.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): macOS 10.15.7
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.9
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

**Comment by ngimel** [comment]
Pytorch does not allow in-place operations on the overlapping tensors, which is what this is. We issue warnings when we encounter some of these situations, however, reliably detecting overlap is computationally expensive so some cases are missed. In particular, there were several issues filed recently where source and destination tensors view the same memory region (which we allow, and which works if source and destination have the same logical structure), but logical strides or element accesses are different, see #45964 where this behavior is reported for scatter and indexing operations. 
cc @peterbell10, maybe we should warn in these cases.

**Comment by peterbell10** [comment]
Currently the overlap checking between two tensors only works for contiguous tensors. Finding overlap in general for strided tensors would be too hard, but some simple strided situations should be easily doable. e.g. if the strides are the same then it's full overlap, if the strides are different but match when sorted then it's a transposed tensor which will have partial overlap. 

As for warning, I guess it depends on the tolerance for false-positives. `torch.cos(x[::2], out=x[1::2])` doesn't overlap but would start warn.
