### ISSUE TITLE
Inconsistent results from torch.triu on GPU compared to CPU

### ISSUE THREAD

**Issue by myleott** [pytorch/pytorch#4840]
On recent PyTorch master (built from source; 0.4.0a0+4970e73) on a P100, CUDA 9:

```
>>> torch.triu(torch.FloatTensor([1]).expand(3, 3))

 1  1  1
 0  1  1
 0  0  1
[torch.FloatTensor of size 3x3]

>>> torch.triu(torch.cuda.FloatTensor([1]).expand(3, 3))

 1  1  1
 1  1  1
 1  1  1
[torch.cuda.FloatTensor of size 3x3 (GPU 0)]
```

**Comment by MlWoo** [comment]
@myleott  I think the results on CPU meets the defination of triu (upper triangular part of the matrix).  It is really hard to handle with a tensor from expand operation with multi-thread not only on GPU but also on CPU. @fmassa, The unexpected result will also happen on CPU if we apply openmp to it. What do you think it ?

**Comment by apaszke** [comment]
It doesn’t matter if it’s cpu or not. triu doesn’t have an underscore which means it doesn’t operate in-place and should always give the same result (in new memory)
