### ISSUE TITLE
PyTorch Mobile NNAPI is slower than CPU

### ISSUE THREAD

**Issue by windmaple** [pytorch/pytorch#48411]
## 🐛 Bug

I’m following this [tutorial](https://pytorch.org/tutorials/prototype/nnapi_mobilenetv2.html) 1 to try out NNAPI support in PyTorch Mobile on Pixel 3a (Android 10, Qualcomm Snapdragon 670). I compiled the speed benchmark binary off commit ID 4ed7f36ed

## To Reproduce

1. Build binary using:
BUILD_PYTORCH_MOBILE=1 ANDROID_ABI=arm64-v8a ./scripts/build_android.sh -DBUILD_BINARY=ON

2. Run the models:
adb shell /data/local/tmp/speed_benchmark_torch --pthreadpool_size=1 --model=/data/local/tmp/mobilenetv2-quant_full-nnapi.pt --use_bundled_input=0 --warmup=5 --iter=200
adb shell /data/local/tmp/speed_benchmark_torch --pthreadpool_size=1 --model=/data/local/tmp/mobilenetv2-quant_full-cpu.pt --use_bundled_input=0 --warmup=5 --iter=200

3. Compare results:
Quant mobilenet v2 using CPU: 66.8 ms
Quant mobilenet v2 using NNAPI: 171 ms

NNAPI not only did not accelerate the model, but slowed it down significantly. I’m really curious what I’m missing here.

## Expected behavior

NNAPI should be much faster

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 4ed7f36 in master
- OS (e.g., Linux): Android 10
- How you installed PyTorch (conda, pip, source): N/A
- Build command you used (if compiling from source): BUILD_PYTORCH_MOBILE=1 ANDROID_ABI=arm64-v8a ./scripts/build_android.sh -DBUILD_BINARY=ON
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

N/A

**Comment by freedomtan** [comment]
On my Pixel 3a, running Android 11, I got 
```
Starting benchmark.
Running warmup runs.
Main runs.
Main run finished. Microseconds per iter: 10819.2. Iters per second: 92.4286
```
1000/92.4268 ~= 10.82 ms, which looks reasonable

comparing with TFLite + NNAPI, 
```
./benchmark_model --graph=tflite-models-new/quant/mobilenet_v2_1.0_224_quant.tflite  --use_nnapi=1
```
I got
```
Number of nodes executed: 1
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     TfLiteNnapiDelegate	        1	     9.121	   100.000%	   100.000%	     0.000	        1

Timings (microseconds): count=108 first=8928 curr=8936 min=8142 max=12512 avg=9121.71 std=629
```

**Comment by windmaple** [comment]
Is it because of Android 11? I'm using Android 10 and maybe it's not supported?

**Comment by windmaple** [comment]
Update my phone to Android 11 and now it's behaving. Thanks a lot for the help!

**Comment by windmaple** [comment]
NNAPI only supports a limited set of chips and ops. I don't think NXP chip is supported by NNAPI at all. 

QC chips have the best support AFAIK.
