### ISSUE TITLE
remove cuda capability 3.0 and 5.0 from binaries

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#4841]
binary sizes are ballooning, need to prune some architectures. The aim is to get the binaries to be less than 500MB (incl. all deps) to be shippable via PyPI.

- [ ] add warning when detected these GPUs at this code block: https://github.com/pytorch/pytorch/blob/4970e733045b1e802c6dfb42c675f29f846be9f4/torch/cuda/__init__.py
- [ ] rebuild binaries

**Comment by vadimkantorov** [comment]
if it's possible to skip the unsupported arch's at build time as well, https://github.com/pytorch/pytorch/issues/4716 is related

**Comment by soumith** [comment]
they're not unsupported, we are not pre-generating arch-dependent assembly for them in the binaries.

**Comment by vadimkantorov** [comment]
got it!

**Comment by JimLee1996** [comment]
Could you please add binary for 5.0 GPUs? Maybe the size won't get larger than 500mb. 

There are lots of pc running on old gpus, and it's hard to build binaries.

**Comment by soumith** [comment]
@JimLee1996 fyi 0.4.1 binaries have 5.0 support added back.

**Comment by JimLee1996** [comment]
@soumith Thank you!

**Comment by soumith** [comment]
@RichGit101 thanks for your comment.
Deprecating cuda capability 3.0 is more than for binary size. 3.0 misses some cuda instructions that we heavily rely on, for example `__shfl`.
Compiling PyTorch from source for CC3.0 wont work either for the reasons I just mentioned (missing cuda instructions in that architecture).
Unfortunately this is an irreversible decision. We're sorry that we are not able to support Tesla K10 owners.
