### ISSUE TITLE
Support broadcasting for einsum

### ISSUE THREAD

**Issue by mberr** [pytorch/pytorch#48420]
## 🚀 Feature
Add broadcasting support to `torch.einsum`.

The following example is a slight modification of the example given in einsum's [documentation](https://pytorch.org/docs/stable/generated/torch.einsum.html#torch.einsum).
```python
import torch

# batch matrix multiplication; with broadcasting
As = torch.randn(1, 2, 5)
Bs = torch.randn(3, 5, 4)
As @ BS                               # this works
torch.einsum('bij,bjk->bik', As, Bs)  # this does not work
```

results in the following error
```python-traceback
Traceback (most recent call last):
  File "mwe.py", line 6, in <module>
    torch.einsum('bij,bjk->bik', As, Bs)
  File ".../lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: size of dimension does not match previous size, operand 1, dim 0
```

## Motivation

The broadcasting feature is available in [numpy.einsum](https://numpy.org/doc/stable/reference/generated/numpy.einsum.html), i.e. the following works
```python
import numpy

As = numpy.zeros(shape=(1, 2, 5))
Bs = numpy.zeros(shape=(3, 5, 4))
numpy.einsum('bij,bjk->bik', As, Bs)
```

Moreover, since many other methods (e.g. all element-wise operations, matmul, ..) exhibit this behaviour it is more consistent to support it here as well.

## Pitch

If one of the dimensions is 1, broadcast it to the other. In particlar, it would be nice to have the following equalities

* bmm: 
   `torch.allclose(torch.einsum('...ij,...jk->...ik', x, y), x @ y)`
* element-wise multiplication 
   `torch.allclose(torch.einsum('...,...->...', x, y), x * y)`

## Alternatives

A working alternative is to wrap `torch.einsum` into a method, which checks for 1d dimensions, squeezes this dimension and deletes the corresponding character from the operand string.

```python
def extended_einsum(
    eq: str,
    *tensors: torch.Tensor,
) -> torch.Tensor
    """Drop dimensions of size 1 to allow broadcasting."""
    lhs, rhs = eq.split("->")
    # squeeze
    mod_ops, mod_t = [], []
    for op, t in zip(lhs.split(","), tensors):
        mod_op = ""
        for i, c in reversed(list(enumerate(op))):
            if t.shape[i] == 1:
                t = t.squeeze(dim=i)
            else:
                mod_op = c + mod_op
        mod_ops.append(mod_op)
        mod_t.append(t)
    m_lhs = ",".join(mod_ops)
    r_keep_dims = set("".join(mod_ops))
    m_rhs = "".join(c for c in rhs if c in r_keep_dims)
    m_eq = f"{m_lhs}->{m_rhs}"
    mod_r = torch.einsum(m_eq, *mod_t)
    # unsqueeze
    for i, c in enumerate(rhs):
        if c not in r_keep_dims:
            mod_r = mod_r.unsqueeze(dim=i)
    return mod_r
```

**Comment by ngimel** [comment]
Implemented in #47860
