### ISSUE TITLE
Frozen TorchScript model can't be moved to a different device.

### ISSUE THREAD

**Issue by PeterL1n** [pytorch/pytorch#48437]
## 🐛 Bug

After a model is frozen by `model = torch.jit.freeze(model)`. We can't move the model to device through `model.cuda()` or `model.to('cuda')`. This limits the model to stay on the same device in all future loadings `model = torch.jit.load('saved.pth')`.

## To Reproduce

1. `model = torch.jit.freeze(model)`
1. `model.cuda() # Ineffective`

## Expected behavior

Allow the user to move model parameters to a different device.

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 440.44
cuDNN version: /usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchscan==0.1.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.1
[conda] Could not collect

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Frozen models aren't supposed to be mutated. But moving model devices placements should be supported on JIT models before freezing. Could you do that instead?

Meanwhile, one thing we could do to improve the situation is to give a clear error when attempting to call .to on frozen model.

**Comment by PeterL1n** [comment]
@gmagogsfm 

The idea is that I want to publish a frozen optimized model for others. Currently, I cannot freeze it because other people won't be able to change devices.

I could release the unfrozen model and other people can freeze it themselves before inference. But I currently can't find the `freeze` method on LibTorch C++ API.

**Comment by eellison** [comment]
Exposing torch.jit.freeze in the C++ seems like a good resolution of this issue, i can do that

**Comment by eellison** [comment]
This has been addressed with a `torch::jit::freeze` api
