### ISSUE TITLE
AttributeError: module 'torch.cuda' has no attribute 'comm'

### ISSUE THREAD

**Issue by 674106399** [pytorch/pytorch#48435]
## ❓ Questions and Help

I'm using torch 1.7.0, and get this kind of error

my torch is installed via 

pip install torch==1.7.0+cu101 torchvision==0.8.1+cu101 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

my os is win10

**Comment by skyline75489** [comment]
What are you trying to do? What is the code that's causing the error?

**Comment by skyline75489** [comment]
Please do not delete the issue template. You need to give us more information. Filling the issue template usually helps.

**Comment by 674106399** [comment]
> What are you trying to do? What is the code that's causing the error?

Thanks for reply.
I'm running this repo: https://github.com/facebookresearch/InterHand2.6M
I met this error on Ubuntu(torch 1.7.0) and Win10(torch 1.7.0), whose torch is installed following offical guidance.
Finally I uninstalled 1.7.0 and installed 1.6.0, which runs perfectly.
So I guess maybe this is a bug of 1.7.0

**Comment by skyline75489** [comment]
Funny that they just fixed the issue https://github.com/facebookresearch/InterHand2.6M/commit/874eb9f740ef54c275433d1bd27f8fb8f6a8f17d like 1 hour ago.

**Comment by 674106399** [comment]
Yea, but the codes run perfectly on 1.6.0 without any change..
anyway, thanks a lot for your reply :)
