### ISSUE TITLE
pytorch install error

### ISSUE THREAD

**Issue by y657250418** [pytorch/pytorch#4843]
when I use the command to install pytorch:
python setup.py install
return error message:

/home/sdd/python/pytorch/aten/src/THC/generic/THCTensorIndex.cu(254): here

/usr/local/cuda/include/thrust/detail/reference.inl(98): error: no default constructor exists for class "thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>"
          detected during:
            instantiation of "thrust::reference<Element, Pointer, Derived>::operator thrust::reference<Element, Pointer, Derived>::value_type() const [with Element=thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Pointer=thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>, Derived=thrust::use_default]" 
/usr/local/cuda/include/thrust/system/cuda/detail/block/copy.h(243): here
            instantiation of "RandomAccessIterator2 thrust::system::cuda::detail::block::async_copy_n_global_to_shared<work_per_thread,Context,RandomAccessIterator1,Size,RandomAccessIterator2>(Context &, RandomAccessIterator1, Size, RandomAccessIterator2) [with work_per_thread=7U, Context=thrust::system::cuda::detail::detail::statically_blocked_thread_array<256U>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, Size=unsigned int, RandomAccessIterator2=thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> *]" 
/usr/local/cuda/include/thrust/system/cuda/detail/detail/stable_merge_sort.inl(113): here
            instantiation of "void thrust::system::cuda::detail::detail::stable_merge_sort_detail::block::staged_bounded_merge<work_per_thread,Context,Iterator1,Size1,Iterator2,Size2,Iterator3,Iterator4,Compare>(Context &, Iterator1, Size1, Iterator2, Size2, Iterator3, Iterator4, Compare) [with work_per_thread=7U, Context=thrust::system::cuda::detail::detail::statically_blocked_thread_array<256U>, Iterator1=thrust::detail::normal_iterator<thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, Size1=unsigned int, Iterator2=thrust::detail::normal_iterator<thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, Size2=unsigned int, Iterator3=thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> *, Iterator4=thrust::zip_iterator<thrust::tuple<thrust::detail::normal_iterator<thrust::device_ptr<half>>, thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>>, Compare=thrust::detail::wrapped_function<thrust::detail::compare_first<ThrustHalfLess>, __nv_bool>]" 
/usr/local/cuda/include/thrust/system/cuda/detail/detail/stable_merge_sort.inl(216): here
            instantiation of "void thrust::system::cuda::detail::detail::stable_merge_sort_detail::merge_adjacent_partitions_closure<work_per_thread, Context, Size, Iterator1, Iterator2, Iterator3, Compare>::operator()(RandomAccessIterator) [with work_per_thread=7U, Context=thrust::system::cuda::detail::detail::statically_blocked_thread_array<256U>, Size=thrust::detail::uint32_t, Iterator1=thrust::detail::normal_iterator<thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, Iterator2=thrust::detail::normal_iterator<thrust::pointer<unsigned int, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, Iterator3=thrust::zip_iterator<thrust::tuple<thrust::detail::normal_iterator<thrust::device_ptr<half>>, thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>>, Compare=thrust::detail::compare_first<ThrustHalfLess>, RandomAccessIterator=thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> *]" 
/usr/local/cuda/include/thrust/system/cuda/detail/detail/virtualized_smem_closure.h(55): here
            instantiation of "void thrust::system::cuda::detail::detail::virtualized_smem_closure<Closure, RandomAccessIterator>::operator()() [with Closure=thrust::system::cuda::detail::detail::stable_merge_sort_detail::merge_adjacent_partitions_closure<7U, thrust::system::cuda::detail::detail::statically_blocked_thread_array<256U>, thrust::detail::uint32_t, thrust::detail::normal_iterator<thrust::pointer<thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, thrust::detail::normal_iterator<thrust::pointer<unsigned int, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>>, thrust::zip_iterator<thrust::tuple<thrust::detail::normal_iterator<thrust::device_ptr<half>>, thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>>, thrust::detail::compare_first<ThrustHalfLess>>, RandomAccessIterator=thrust::tuple<half, signed long, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> *]" 
/usr/local/cuda/include/thrust/system/cuda/detail/detail/launch_closure.inl(52): here
            [ 11 instantiation contexts not shown ]
            instantiation of "thrust::system::cuda::detail::stable_sort_detail::enable_if_comparison_sort<RandomAccessIterator1, StrictWeakOrdering>::type thrust::system::cuda::detail::stable_sort_detail::stable_sort_by_key(thrust::system::cuda::detail::execution_policy<DerivedPolicy> &, RandomAccessIterator1, RandomAccessIterator1, RandomAccessIterator2, StrictWeakOrdering) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::device_ptr<half>>, RandomAccessIterator2=thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, StrictWeakOrdering=ThrustHalfLess]" 
/usr/local/cuda/include/thrust/system/cuda/detail/sort.inl(260): here
            instantiation of "void thrust::system::cuda::detail::stable_sort_by_key(thrust::system::cuda::detail::execution_policy<DerivedPolicy> &, RandomAccessIterator1, RandomAccessIterator1, RandomAccessIterator2, StrictWeakOrdering) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::device_ptr<half>>, RandomAccessIterator2=thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, StrictWeakOrdering=ThrustHalfLess]" 
/usr/local/cuda/include/thrust/detail/sort.inl(147): here
            instantiation of "void thrust::stable_sort_by_key(const thrust::detail::execution_policy_base<DerivedPolicy> &, RandomAccessIterator1, RandomAccessIterator1, RandomAccessIterator2, StrictWeakOrdering) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::device_ptr<half>>, RandomAccessIterator2=thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, StrictWeakOrdering=ThrustHalfLess]" 
/usr/local/cuda/include/thrust/system/detail/generic/sort.inl(93): here
            instantiation of "void thrust::system::detail::generic::sort_by_key(thrust::execution_policy<DerivedPolicy> &, RandomAccessIterator1, RandomAccessIterator1, RandomAccessIterator2, StrictWeakOrdering) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::device_ptr<half>>, RandomAccessIterator2=thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, StrictWeakOrdering=ThrustHalfLess]" 
/usr/local/cuda/include/thrust/detail/sort.inl(115): here
            instantiation of "void thrust::sort_by_key(const thrust::detail::execution_policy_base<DerivedPolicy> &, RandomAccessIterator1, RandomAccessIterator1, RandomAccessIterator2, StrictWeakOrdering) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, RandomAccessIterator1=thrust::detail::normal_iterator<thrust::device_ptr<half>>, RandomAccessIterator2=thrust::detail::normal_iterator<thrust::device_ptr<int64_t>>, StrictWeakOrdering=ThrustHalfLess]" 
/home/sdd/python/pytorch/aten/src/THC/generic/THCTensorMode.cu(42): here

18 errors detected in the compilation of "/tmp/tmpxft_00002be7_00000000-7_THCTensorIndex.cpp1.ii".
CMake Error at ATen_generated_THCTensorIndex.cu.o.cmake:267 (message):
  Error generating file
  /home/sdd/python/pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/__/THC/./ATen_generated_THCTensorIndex.cu.o

make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorIndex.cu.o] Error 1
16 errors detected in the compilation of "/tmp/tmpxft_00002baf_00000000-7_THCTensorMode.cpp1.ii".
CMake Error at ATen_generated_THCTensorMode.cu.o.cmake:267 (message):
  Error generating file
  /home/sdd/python/pytorch/torch/lib/build/aten/src/ATen/CMakeFiles/ATen.dir/__/THC/./ATen_generated_THCTensorMode.cu.o

make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorMode.cu.o] Error 1
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
make: *** [all] Error 2

who can help me ?
Centos +python 2.7.14

**Comment by mruberry** [comment]
Closing this issue due to age. If you still experience this problem with a recent version of PyTorch then please update and reopen it.
