### ISSUE TITLE
Dynamic quantization doesn't work after a forward pass

### ISSUE THREAD

**Issue by ayush-1506** [pytorch/pytorch#48448]
## 🐛 Bug

I'm try to quantize the [waveglow](https://github.com/NVIDIA/waveglow) model, however I get an error `Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment` only when I call `torch.quantization.quantize_dynamic` before calling the model with an input.

Why is this happening? Does calling the model once change the internal state of model parameters?

## To Reproduce
1. Quantizing before calling the model on some input: (Works)
```
import torch
import time
from glow import WaveGlow
model = "waveglow_276000"

wg = torch.load(model, map_location=torch.device("cpu"))["model"]
wg.eval()
import torch.quantization

quantized_model = torch.quantization.quantize_dynamic(
    wg, {torch.nn.ConvTranspose1d, torch.nn.Conv1d}, dtype=torch.qint8
)
```
And quantizing after calling the model on some random input:
```
import torch
import time
from glow import WaveGlow
model = "waveglow_276000"

wg = torch.load(model, map_location=torch.device("cpu"))["model"]
wg.eval()
ip = torch.randn(1, 80, 200)
op = wg.infer(ip)

import torch.quantization

quantized_model = torch.quantization.quantize_dynamic(
    wg, {torch.nn.ConvTranspose1d, torch.nn.Conv1d}, dtype=torch.qint8
)
```
Error message: `raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment`

## Expected behavior

Model should be quantized in both cases.

## Environment

Platform Mac OS Big Sur 11.0.1
Python 3.8.4
Pytorch 1.7 (CPU), installed with pip

## Additional context:

The nvidia/waveglow model ideally works only on GPUs, but I've made changes to run it on CPU.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
@jerryzh168 do you have an idea what may be going on with deepcopy here?

**Comment by jerryzh168** [comment]
there are models that doesn't support deepcopy. deepcopy is called here (https://github.com/pytorch/pytorch/blob/master/torch/quantization/quantize.py#L374), so a WA you can do is to call quantize_dynamic with inplace=True, would that work?

**Comment by ayush-1506** [comment]
Thanks, will try it out. Just curious: what's the caveat in supporting deepcopy for these models (or certain layers)?

**Comment by jerryzh168** [comment]
I'm not exactly sure, but maybe these links will help:
https://stackoverflow.com/questions/56590886/how-to-solve-the-run-time-error-only-tensors-created-explicitly-by-the-user-gr
https://discuss.pytorch.org/t/how-does-one-reproduce-the-deepcopy-error-of-tensors-made-by-code/69852/3

**Comment by ayush-1506** [comment]
@jerryzh168 Thanks, adding `inplace=True` seems to work. However, it still doesn't explain why the first example worked without `inplace=True` (i.e supported deepcopy, even though both examples have the same model). Am I missing something?

**Comment by raghuramank100** [comment]
Closing this issue as we have a workaround.
