### ISSUE TITLE
is there other reason when cuda out of memory ? 

### ISSUE THREAD

**Issue by wxde** [pytorch/pytorch#4844]
when running my invert  code of from right and executable tensorflow code by the same GPU xp environment , the error is below:

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1501969512886/work/pytorch-0.1.12/torch/lib/THC/generic/THCStorage.cu:66

meanwhile

the GPU memory  was out of when the code ran the third conv3d . but the net is ok in tensorflow.

**Comment by SsnL** [comment]
Do you have cudnn installed?

**Comment by wxde** [comment]
@SsnL yes . i have installed cudnn

**Comment by SsnL** [comment]
Could you provide more details on pytorch, cuda, cudnn versions, gpu arch, and post a script to reproduce the issue? Thanks!

**Comment by mruberry** [comment]
Closing due to age and lack of response. If you're still experiencing this issue on a recent version of PyTorch then please update and reopen it.
