### ISSUE TITLE
Change permissions of /opt/conda in Docker image.

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#48447]
## 🚀 Feature
I would like to request changing the ownership of `/opt/conda` to all users, not just root.

## Motivation

In many cases on servers, users do not have root permissions. I have found that if I pull the PyTorch docker image and then set myself as a non-root user, I cannot install any new packages via conda.

The situation seems to be similar with pip but pip manages by installing in a user controlled directory.

A simple solution is to use `chmod -R 777 /opt/conda`. 

However, this increases the Docker image size by `/opt/conda`, see [here](https://github.com/moby/moby/issues/5505) for details.

Therefore, it would be better if `/opt/conda` permissions were changed to all users before anything else is installed.

## Pitch

Add `chmod -R /opt/conda` immediately after creating `/opt/conda` in the Dockerfile.

## Alternatives

Perhaps also do the same for the pip install directory.

## Additional context

I am not an expert in these matters, so there may be good reasons for limiting installation directories to the root user. Please inform me if there are.

**Comment by ngimel** [comment]
cc @seemethere

**Comment by veritas9872** [comment]
I understand that some people may wish to prevent non-root users from installing any new packages, possibly in deployment settings. However, in development settings, this can be very uncomfortable.

**Comment by salihkaragoz** [comment]
Is there any workaround on this topic? Thanks.
