### ISSUE TITLE
v1.7.0 block while model.cuda()

### ISSUE THREAD

**Issue by jihuacao** [pytorch/pytorch#48442]
troch v1.7.0 compile with cuda11.1

costining a lot of time while calling model.cuda(), maybe has already failed?

![image](https://user-images.githubusercontent.com/22140223/100198167-73a71000-2f36-11eb-981d-2903787e7c3f.png)

envs:
[envs.log](https://github.com/pytorch/pytorch/files/5595109/envs.log)

cc @malfet @seemethere @walterddr @ngimel

**Comment by ngimel** [comment]
Please tell us more about how you build pytorch. This should not happen if you are properly compiling for 80 or 86 architecture.
