### ISSUE TITLE
C++ torch::cat changes values of the tensor on ARM

### ISSUE THREAD

**Issue by 0phoff** [pytorch/pytorch#48451]
## 🐛 Bug
When using libtorch C++ on ARM (Jetson AGX Xavier), the output after running torch::cat() is not the same as the original input tensor.

## To Reproduce
Build libtorch C++ on Jetson AGX Xavier, then build the following code sample:
```cpp
#include <iostream>
#include <torch/torch.h>
#include <vector>

int main(int argc, char **argv)
{
  auto t1 = torch::rand({4,5});
  auto t2 = torch::rand({6,5});
  std::cout << t1 << "\n";
  std::cout << t2 << "\n" << std::endl;

  auto cat1 = torch::cat({t1, t2}, 0);
  std::cout << cat1 << "\n" << std::endl;
}
```

Running the script above, generates the following output:
(The values are different starting from index [8,4] until the end)
```
 0.5766  0.5028  0.1403  0.4657  0.4702
 0.7837  0.3425  0.6780  0.3620  0.7905
 0.8392  0.5187  0.8888  0.2738  0.2745
 0.5269  0.6371  0.5469  0.8767  0.9544
[ CPUFloatType{4,5} ]
 0.6637  0.9570  0.3228  0.5196  0.5669
 0.3870  0.0838  0.1782  0.9470  0.1004
 0.1188  0.6168  0.0592  0.8176  0.2263
 0.4452  0.9574  0.2606  0.3602  0.9458
 0.6761  0.4381  0.6328  0.6394  0.2900
 0.8422  0.7358  0.9934  0.2205  0.0021
[ CPUFloatType{6,5} ]

 5.7664e-01  5.0278e-01  1.4030e-01  4.6574e-01  4.7020e-01
 7.8372e-01  3.4254e-01  6.7805e-01  3.6198e-01  7.9051e-01
 8.3917e-01  5.1872e-01  8.8885e-01  2.7377e-01  2.7448e-01
 5.2688e-01  6.3707e-01  5.4693e-01  8.7673e-01  9.5443e-01
 6.6371e-01  9.5699e-01  3.2278e-01  5.1955e-01  5.6688e-01
 3.8699e-01  8.3811e-02  1.7824e-01  9.4704e-01  1.0043e-01
 1.1882e-01  6.1684e-01  5.9196e-02  8.1755e-01  2.2629e-01
 4.4517e-01  9.5738e-01  2.6059e-01  3.6017e-01  9.4582e-01
 6.7613e-01  4.3809e-01  6.3285e-01  6.3936e-01 -1.4592e-32
 1.7796e-43 -2.3031e+16  1.7796e-43 -2.3030e+16  1.7796e-43
[ CPUFloatType{10,5} ]
```

## Expected behavior

I expect the concatenated tensor to contain exactly the same values as the inputs:
```
 0.5766  0.5028  0.1403  0.4657  0.4702
 0.7837  0.3425  0.6780  0.3620  0.7905
 0.8392  0.5187  0.8888  0.2738  0.2745
 0.5269  0.6371  0.5469  0.8767  0.9544
 0.6637  0.9570  0.3228  0.5196  0.5669
 0.3870  0.0838  0.1782  0.9470  0.1004
 0.1188  0.6168  0.0592  0.8176  0.2263
 0.4452  0.9574  0.2606  0.3602  0.9458
 0.6761  0.4381  0.6328  0.6394  0.2900
 0.8422  0.7358  0.9934  0.2205  0.0021
[ CPUFloatType{10,5} ]
```
## Environment
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.1

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

## Additional context
`torch::cat` works fine on my development machine, so this seems to be an issue related to architecture.

**Comment by 0phoff** [comment]
moving tensors to CUDA and then performing concatenation works, but is obviously slower.

**Comment by ngimel** [comment]
cc @malfet

**Comment by malfet** [comment]
Please try cherry-picking https://github.com/pytorch/pytorch/pull/47099 against 1.7 branch or update your compiler and try again.
gcc-7.5.0 fails to generate a correct code that uses NEON intrinsics, which likely causes an errors similar to what you've described.

**Comment by malfet** [comment]
Could not reproduce the issue using aarch64 nightly wheels (compiled using gcc-8.4.0):
```
$ g++-8 test.cpp -Iminiforge3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -Iminiforge3/lib/python3.7/site-packages/torch/include/ -ltorch -Lminiforge3/lib/python3.7/site-packages/torch/lib -lc10 -ltorch_cpu; LD_LIBRARY_PATH=miniforge3/lib/python3.7/site-packages/torch/lib ./a.out 
 0.8518  0.9856  0.9432  0.8989  0.8610
 0.5225  0.4981  0.4448  0.0477  0.5652
 0.7018  0.4495  0.3985  0.7913  0.0509
 0.6329  0.1072  0.2288  0.4771  0.8723
[ CPUFloatType{4,5} ]
 0.3779  0.6153  0.7103  0.2193  0.5839
 0.4273  0.6443  0.8950  0.3999  0.0100
 0.5759  0.2415  0.3186  0.9887  0.4877
 0.6530  0.2091  0.7944  0.3150  0.7645
 0.4198  0.8210  0.2201  0.5569  0.1540
 0.1227  0.3280  0.3387  0.2037  0.7112
[ CPUFloatType{6,5} ]

 0.8518  0.9856  0.9432  0.8989  0.8610
 0.5225  0.4981  0.4448  0.0477  0.5652
 0.7018  0.4495  0.3985  0.7913  0.0509
 0.6329  0.1072  0.2288  0.4771  0.8723
 0.3779  0.6153  0.7103  0.2193  0.5839
 0.4273  0.6443  0.8950  0.3999  0.0100
 0.5759  0.2415  0.3186  0.9887  0.4877
 0.6530  0.2091  0.7944  0.3150  0.7645
 0.4198  0.8210  0.2201  0.5569  0.1540
 0.1227  0.3280  0.3387  0.2037  0.7112
[ CPUFloatType{10,5} ]
```

**Comment by 0phoff** [comment]
@malfet, I updated my compiler to GCC 8.4.0, but the issue persists.
Should I still try to cherrypick that commit or does the updated GCC supersede that potential fix.

Tell me if there is something else you would want me to try to debug this issue further.

**Comment by malfet** [comment]
@0phoff Can you please copy https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/missing_vld1_neon.h and https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/missing_vst1_neon.h from master branch into 1.7 to see if it fixes all the problems.

**Comment by 0phoff** [comment]
@malfet, I checked out the `1.7.1-rc3` tag and modified the 2 files you mentioned and now my bug is gone!
I guess this will be coming in pytorch 1.8 ?

**Comment by malfet** [comment]
Yes, as it is in master, it will soon propagate to ARM nightlies and will be part of 1.8
