### ISSUE TITLE
borked default value  group=<object object> in distributed.html

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#48464]
## 📚 Documentation

Every time there is a `group` argument in https://pytorch.org/docs/stable/distributed.html, it currently shows: `group=<object object>` in the function signature, 

e.g.:

```
torch.distributed.get_backend(group=<object object>)
torch.distributed.get_rank(group=<object object>)

```
a few dozen of those.

the default value should be `group.WORLD` but the doc creator turns it into `object object`. This is probably unintentional, since what can a user do with the default `object object`.

Thanks.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by osalpekar** [comment]
Thanks for reporting this @stas00! Yes, looks like this should be `group.WORLD` but the docs aren't able to handle the enum properly - we'll look into this
