### ISSUE TITLE
jit.trace doesn't work accordingly if data copy is involved in module

### ISSUE THREAD

**Issue by MrCrHaM** [pytorch/pytorch#48477]
## 🐛 Bug
If data copy is involved in module, `jit.trace` gives `TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function`.

## To Reproduce
```python
import torch


class Dummy(torch.nn.Module):
    def forward(self, x):
        y0 = x * 0
        y1 = x * 1
        y0.data = y1  # which breaks jit.trace
        return y0


if __name__ == '__main__':
    inputs = torch.tensor([1])
    model = Dummy()
    model.eval()  # makes no difference, in case someone asks
    outputs = model(inputs)  # get tensor([1])

    # jit
    model_jit = torch.jit.trace(model, (inputs,))
    outputs_jit = model_jit(inputs)  # get tensor([0]), expect tensor([1]).
    print(outputs.equal(outputs_jit))  # False
```

## Expected behavior
Output of traced module matches the output of Python module. Namely, print `True` for the snippet above.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): CentOS Linux release 7.7.1908 (Core) (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0.130/Could not collect
 - GPU models and configuration: GPU 0: Tesla V100-PCIE-32GB

## Additional context

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Modifying underlying data structure isn't supported by tracing. Using appropriate tensor operations is the preferred way. For the given example, you can use `y0 = y1` instead.

**Comment by MrCrHaM** [comment]
@gmagogsfm The reason for modifying underlying data is to only change the forward propagation while keep how it calculates the derivative, mentioned [here](https://arxiv.org/abs/1703.00395) at section 2.1, and for now the most straightforward way to do it is `y0.data = y1`. 
I've already found a weird workaround to address this issue. Thanks for the attention though.

**Comment by xuefeicao** [comment]
@MrCrHaM, what was the workaround? thanks
