### ISSUE TITLE
Windows install using pip in virtualenv can't find version that satisfies requirement...

### ISSUE THREAD

**Issue by pkuppens** [pytorch/pytorch#48513]
## 🐛 Bug

Unable to install pytorch on windows 10 professional via https://pytorch.org/get-started/locally/ because distribution could not be found.

## To Reproduce

Steps to reproduce the behavior: (what I did)

1. Open Visual Studio Code (in a new folder)
2. Create a virtualenv (python -m venv .venv) and activate it
3. Go to https://pytorch.org/get-started/locally/ to get the instructions for installing torch via pip 
4. In a terminal: pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
5. Observe the following ERROR

```
E:\Test> pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.7.0+cu110 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.7.0+cu110
```

What you could do:

1. Ensure that you don't have the download cached
2. Run the pip command in a python environment

## Expected behavior

Successful installation of pytorch and its dependencies.

## Environment

* Windows 10 (no wget installed, so manual collection)
* Visual Studio Code
* PyTorch 1.7 with CUDA
* pip in virtualenv in Visual Studio Code
* Python version: 3.9
* CUDA/cuDNN version: Request to install 11.0, but already have 11.2 installed
* GPU models and configuration: 980Ti
* Any other relevant information:

## Additional context

* It worked in the past, and it works on a different PC, but that uses a cached version
* It may be a problem with access rights on the download folder, or inconsistent/incomplete links
* Functional version on different PC:
```
pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch===1.7.0+cu110
  Using cached https://download.pytorch.org/whl/cu110/torch-1.7.0%2Bcu110-cp38-cp38-win_amd64.whl (2046.8 MB)Collecting torchvision===0.8.1+cu110
  Using cached https://download.pytorch.org/whl/cu110/torchvision-0.8.1%2Bcu110-cp38-cp38-win_amd64.whl (1.6 MB)
```

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by saum7800** [comment]
I'm not an expert at any of this, but could it be because of python 3.9? Some other packages are not showing up for me on pip recently due to Python 3.9. Maybe try with a virtualenv for python 3.7 or 3.8. hope this helps

**Comment by pkuppens** [comment]
@saum7800 , it helped in a different way than expected. But it helped!!

I tried using a python 3.7.3 based and activated virtualenv, but that did not work with the pip command. However, still a few references to 3.9 python, so to ensure that I used the python I want, I added `python -m` and ran:

```
python -m pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
```

So, hopefully, this workaround also helps others with the same issue, and maybe some notes could be added to the https://pytorch.org/get-started/locally/ page.

@saum7800 , and maybe your problem with different pip packages can be solved as well with `python -m pip` instead of `pip`

**Comment by saum7800** [comment]
@pkuppens , that's great. I will also try it out

**Comment by mszhanyi** [comment]
`In a terminal: pip install torch===1.7.0+cu110 torchvision===0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`

Is the terminal in VScode？ 
Did you select the python interpreter in VSCode？

**Comment by seemethere** [comment]
Looks like this issue is mostly resolved, going to go ahead and close

**Comment by manurathi1** [comment]
use pip3 instead of pip. Faed the same issue. Pip won't recognize the latest python and the updated version of the package. whereas pip3 will default to python 3 and update to the newest version of any package without mentioning it explicitly
