### ISSUE TITLE
Make UndefinedTensor's data_ptr() return nullptr

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4851]
This would make some code I have to write more convenient. Shall we do it?

**Comment by gchanan** [comment]
example?

**Comment by ezyang** [comment]
When passing possible undefined tensors to external bindings, I usually have to write this: `cx.defined() ? cx.data_ptr() : nullptr`

**Comment by apaszke** [comment]
Maybe make it `data_ptr_opt()`?

**Comment by ezyang** [comment]
@colesbury, @SsnL and I had an offline conversation about this and we'll probably end up just making another function `at::maybe_ptr` or `at::data_ptr` (so we don't have to deal with implementation weirdness making a certain method on undefined tensor actually work.)

**Comment by SsnL** [comment]
solved in #4922
