### ISSUE TITLE
pytorch-android mobile tech support

### ISSUE THREAD

**Issue by SF0220** [pytorch/pytorch#48510]
## ❓ Questions and Help
I noticed that the demo and Youtube video of the PyTorch mobile android worked on the pre-trained model. I am wondering if we could achieve training on android using PyTorch?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @jlin27 @mruberry

**Comment by dhruvbird** [comment]
Currently, PyTorch doesn't support on-device Training (only inference).

**Comment by SF0220** [comment]
> Currently, PyTorch doesn't support on-device Training (only inference).

Thank you for your reply! Actually, I am working with a Federated ML research group and focusing on doing training on mobile or IoT. May I ask what work needs to be done to support training on mobile with PyTorch? Or would you like to co-work with us FedML to explore this project? I believe this would be an interesting direction and make PyTorch more powerful in ML. @chaoyanghe

**Comment by chaoyanghe** [comment]
@dhruvbird Hi, may I have a private discussion with your team? I am working on-device training project https://fedml.ai. We hope to collaborate with you.
