### ISSUE TITLE
bias of Conv are added twice in _ConvBnNd._forward

### ISSUE THREAD

**Issue by icyhearts** [pytorch/pytorch#48514]
## 🐛 Bug

in PyTorch 1.7.0 installed by pip3,
in torch/nn/intrinsic/qat/modules/conv_fused.py,
why `bias` of Conv layer are added **twice** in _ConvBnNd._forward?
## To Reproduce

1. change `bias=False` to `bias=True` in https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py
1. use https://github.com/pytorch/vision/blob/master/references/classification/train_quantization.py to do quantization-aware training for mobilenet_v2 

## Expected behavior
in torch/nn/intrinsic/qat/modules/conv_fused.py,
`bias` of Conv layer are added **only once** in _ConvBnNd._forward, since F.conv2d itself has `bias` parameter

## Environment
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.1
[conda] Could not collect

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source):pip3
 - Build command you used (if compiling from source):no
 - Python version: 3.6
 - CUDA/cuDNN version: no
 - GPU models and configuration: no
 - Any other relevant information: no

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo @albanD @mruberry

**Comment by jerryzh168** [comment]
I see, I think there is a bug here https://github.com/pytorch/pytorch/blob/master/torch/nn/intrinsic/qat/modules/conv_fused.py#L97, we'll need to make bias a parameter as well, thanks for reporting.
