### ISSUE TITLE
TorchScript input tensor size

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#48525]
## 🚀 Feature

A TorchScript model file should contain metadata for input tensor dimensions or the specific required tensor sizes. 

## Motivation

TorchScript code often expects a specific input tensor format but the runtime or tools are unable to infer such constraints from the model file. Instead of users and tools guessing the tensor formats the model should be self-descriptive.

For example, `deeplabv3_resnet50` runs `input_shape = x.shape[-2:]` on the code expecting a certain number of tensor dimensions which can not be derived from the model file itself. 

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Notes:
 
There is on-going work from Mikhail Z that allows adding hints about device location of Tensors in C++ APIs. If we take the route of allowing user specifying tensor sizes for sake of optimization, our interfaces should be consistent.
