### ISSUE TITLE
Implement additional quantile modes

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#48523]
This issue is to track the request for additional quantile modes: lower, higher, nearest, and midpoint. These modes are available in NumPy: https://numpy.org/doc/stable/reference/generated/numpy.quantile.html?highlight=quantile#numpy.quantile and requested by @matthewfeickert here https://github.com/pytorch/pytorch/issues/38349#issuecomment-717606900.

cc @mruberry @rgommers @heitorschueroff

**Comment by matthewfeickert** [comment]
Thanks very much for starting this Issue, @mruberry. This would be great to have in a future release. cc @kratsg @lukasheinrich
