### ISSUE TITLE
I am unable to install, How to install it?

### ISSUE THREAD

**Issue by xcodz-dot** [pytorch/pytorch#48528]
### I am unable to install pytorch like the way they said

Here are all the screen shots to describe error is most of the detail

#### Website
<img width="960" alt="chrome page" src="https://user-images.githubusercontent.com/71920621/100496065-07ffb580-3177-11eb-9e8d-7445d613e97f.PNG">

#### Command Prompt
<img width="614" alt="cmd" src="https://user-images.githubusercontent.com/71920621/100496068-1221b400-3177-11eb-8402-856ac1d037d7.PNG">

#### System Info
<img width="900" alt="sys1" src="https://user-images.githubusercontent.com/71920621/100496070-18179500-3177-11eb-8a80-6c0d1638f557.PNG">
<img width="900" alt="sys2" src="https://user-images.githubusercontent.com/71920621/100496073-1cdc4900-3177-11eb-97d7-e57f1cbf6659.PNG">

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by ejguan** [comment]
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by xcodz-dot** [comment]
Thanks for your help :) but I have switched to tensorflow and started a book with it, book is taking up money so i will be with tensorflow.
