### ISSUE TITLE
complie error on windows10

### ISSUE THREAD

**Issue by huwei1024** [pytorch/pytorch#48535]
i got this error:

CMake Error at CMakeLists.txt:244 (find_library):
  Could not find libuv_tmp_LIBRARY using the following names: uv, libuv

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by free-qc** [comment]
i solve this problem by setting USE_DISTRIBUTED to OFF

**Comment by huwei1024** [comment]
@free-qc  
hi, i got this

FindCUDA says CUDA version is (usually determined by nvcc), but the CUDA
  headers say the version is Exit code 0xc0000135

**Comment by peterjc123** [comment]
@huwei1024 Would you please give out the full build log?

**Comment by huwei1024** [comment]
@peterjc123 


“D:\Work\GitHub\torch\pytorch\build\install.vcxproj”(默认目标) (1) ->
“D:\Work\GitHub\torch\pytorch\build\ALL_BUILD.vcxproj”(默认目标) (3) ->
“D:\Work\GitHub\torch\pytorch\build\caffe2\AlgorithmsTest.vcxproj”(默认目标) (23) ->
“D:\Work\GitHub\torch\pytorch\build\confu-deps\XNNPACK\XNNPACK.vcxproj”(默认目标) (29) ->
“D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj”(默认目标) (30) ->
(ClCompile 目标) ->
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(473,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(488,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(516,17): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(517,13): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(519,9): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(520,5): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(651,16): error C2079: “varDefaultValue”使用未定义的 struct“tagVARIANT” (编译源文件 D
:\Work\GitHub\
torch\pytorch\third_party\pthreadpool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(936,16): error C2079: “varValue”使用未定义的 struct“tagVARIANT” (编译源文件 D:\Work\
GitHub\torch\p
ytorch\third_party\pthreadpool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(318,24): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_pa
rty\pthrea
dpool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(377,37): error C2371: “pvarVal”: 重定义；不同的基类型 (编译源文件 D:\Work\GitHub\tor
ch\pytorch\third
_party\pthreadpool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(378,9): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_par
ty\pthread
pool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(379,5): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_par
ty\pthread
pool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(382,3): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_par
ty\pthread
pool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\propidl.h(383,1): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_par
ty\pthread
pool\src\windows.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(473,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(488,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(516,17): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(517,13): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(519,9): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(520,5): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(651,16): error C2079: “varDefaultValue”使用未定义的 struct“tagVARIANT” (编译源文件 D
:\Work\GitHub\
torch\pytorch\third_party\pthreadpool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(936,16): error C2079: “varValue”使用未定义的 struct“tagVARIANT” (编译源文件 D:\Work\
GitHub\torch\p
ytorch\third_party\pthreadpool\src\memory.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(473,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(488,17): error C2059: 语法错误:“/” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(516,17): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(517,13): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_part
y\pthreadp
ool\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(519,9): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(520,5): error C2059: 语法错误:“}” (编译源文件 D:\Work\GitHub\torch\pytorch\third_party
\pthreadpo
ol\src\portable-api.c) [D:\Work\GitHub\torch\pytorch\build\confu-deps\pthreadpool\pthreadpool.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\oaidl.h(651,16): error C2079: “varDefaultValue”使用未定义的 struct“tagVARIANT” (编译源文件 D
:\Work\GitHub\
torch\pytorch\third_party\pthreadpool\src\portable-api.c) [D:

**Comment by peterjc123** [comment]
@huwei1024 Please try the following commands.
```bash
git submodule sync
git submodule update --init --recursive
```

**Comment by peterjc123** [comment]
BTW, could you please tell me sth more about your dev env? Like VS version, OS version and more.

**Comment by huwei1024** [comment]
vs 2019 
windows 10
cuda 10.2



now i got this error:

“D:\Work\GitHub\torch\pytorch\build\install.vcxproj”(默认目标) (1) ->
“D:\Work\GitHub\torch\pytorch\build\ALL_BUILD.vcxproj”(默认目标) (3) ->
“D:\Work\GitHub\torch\pytorch\build\caffe2\AlgorithmsTest.vcxproj”(默认目标) (23) ->
“D:\Work\GitHub\torch\pytorch\build\caffe2\torch.vcxproj”(默认目标) (38) ->
“D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxproj”(默认目标) (39) ->
(ClCompile 目标) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7417,1): error C2678: 二进制“*”: 没有找到接受“con
st _BidIt”类型的左操作数的运算符(或没有可接受的转换) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7417,17): error C2100: 非法的间接寻址 (编译源文件 D:
\Work\GitHub\torch\pytorch\build\aten\src\ATen\native\cpu\SortingKernel.cpp.DEFAULT.cpp) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxpro
j]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7419,1): error C2678: 二进制“*”: 没有找到接受“con
st _BidIt”类型的左操作数的运算符(或没有可接受的转换) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7419,17): error C2100: 非法的间接寻址 (编译源文件 D:
\Work\GitHub\torch\pytorch\build\aten\src\ATen\native\cpu\SortingKernel.cpp.DEFAULT.cpp) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxpro
j]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7417,1): error C2678: 二进制“*”: 没有找到接受“con
st _BidIt”类型的左操作数的运算符(或没有可接受的转换) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\algorithm(7419,1): error C2678: 二进制“*”: 没有找到接受“con
st _BidIt”类型的左操作数的运算符(或没有可接受的转换) [D:\Work\GitHub\torch\pytorch\build\caffe2\torch_cpu.vcxproj]

    845 个警告
    6 个错误

**Comment by peterjc123** [comment]
It seems to be a known issue. Please use 14.27 instead.

**Comment by huwei1024** [comment]
@peterjc123 
I got both 14.27 and 14.28 .
How to use 14.27 ?

**Comment by peterjc123** [comment]
```
python setup.py clean
git clean -fdx
set CMAKE_GENERATOR_TOOLSET_VERSION=14.27
set CMAKE_GENERATOR=Visual Studio 16 2019
python setup.py install
```

**Comment by huwei1024** [comment]
@peterjc123 

then got this:
When you specify `CMAKE_GENERATOR_TOOLSET_VERSION`, you must also activate the vs environment of this version. Please read the notes in the build steps carefully



build_windows.bat:


set USE_NINJA=OFF
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.27
set DISTUTILS_USE_SDK=1
set USE_DISTRIBUTED=OFF
set USE_CUDA=ON

**Comment by mszhanyi** [comment]
@huwei1024 please refer
MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7 (https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B)
and install the proper version in https://docs.microsoft.com/en-us/visualstudio/releases/2019/history.

**Comment by gunandrose4u** [comment]
@huwei1024 , you need activate your vs env as follow,

set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.27
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%

**Comment by huwei1024** [comment]
@gunandrose4u 
set USE_NINJA=OFF
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.27
set VCToolsVersion=14.27.29110
set DISTUTILS_USE_SDK=1
set USE_DISTRIBUTED=OFF
set USE_CUDA=ON



i got this error:


@PEAE@Z) 中引用了该符号 [D:\Work\GitHub\torch\pytorch\build\caffe2\CppSignature_test.vcxproj]
  torch_cpu.lib(conv_dnnlowp_acc16_op.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) void __cdecl fbgemm::fbgem
mPacked<class fbgemm::PackAMatrix<unsigned char,short>,class fbgemm::PackBMatrix<signed char,short>,unsigned char,class
 fbgemm::ReQuantizeOutput<0,1,int,unsigned char,int,class fbgemm::DoNothing<unsigned char,unsigned char> > >(class fbge
mm::PackMatrix<class fbgemm::PackAMatrix<unsigned char,short>,unsigned char,short> &,class fbgemm::PackMatrix<class fbg
emm::PackBMatrix<signed char,short>,signed char,short> &,unsigned char *,int *,unsigned int,class fbgemm::ReQuantizeOut

**Comment by gunandrose4u** [comment]
@huwei1024 , looks like your submodule fbgemm need to be updated. Can you update your submodule fbgemm same commit as the one in master branch?

**Comment by huwei1024** [comment]
i clone the repository again, got this error:

--
-- ******** Summary ********
-- General:
--   CMake version         : 3.18.4
--   CMake command         : C:/Python/Python38/Lib/site-packages/cmake/data/bin/cmake.exe
--   System                : Windows
--   C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
--   C++ compiler id       : MSVC
--   C++ compiler version  : 19.27.29114.0
--   CXX flags             : /DWIN32 /D_WINDOWS /GR /EHsc /w /MP /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK
--   Build type            : Release
--   Compile definitions   : ONNX_ML=1;ONNXIFI_ENABLE_EXT=1;ONNX_NAMESPACE=onnx_c2;_CRT_SECURE_NO_DEPRECATE=1;WIN32_LEAN_AND_MEAN;USE_EXTERNAL_MZCRC;MINIZ_DISABLE_ZIP_READER_CRC32_CHECKS
--   CMAKE_PREFIX_PATH     : C:\Python\Python38\Lib\site-packages
--   CMAKE_INSTALL_PREFIX  : D:/Work/GitHub/pytorch/torch
--
--   TORCH_VERSION         : 1.8.0
--   CAFFE2_VERSION        : 1.8.0
--   BUILD_CAFFE2          : ON
--   BUILD_CAFFE2_OPS      : ON
--   BUILD_CAFFE2_MOBILE   : OFF
--   BUILD_STATIC_RUNTIME_BENCHMARK: OFF
--   BUILD_TENSOREXPR_BENCHMARK: OFF


...


Traceback (most recent call last):
  File "tools\build_libtorch.py", line 19, in <module>
    build_caffe2(version=None, cmake_python_library=None, build_python=False,
  File "D:\Work\GitHub\pytorch\tools\build_pytorch_libs.py", line 50, in build_caffe2
    cmake.generate(version,
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 330, in generate
    self.run(args, env=my_env)
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GVisual Studio 16 2019', '-Ax64', '-Tversion=14.27,host=x64', '-DBUILDING_WITH_TORCH_LIBS=OFF', '-DBUILD_BINARY=OFF', '-DBUILD_PYTHON=False', '-DBUILD_SHARED_LIBS=OFF', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 16 2019', '-DCMAKE_GENERATOR_TOOLSET_VERSION=14.27', '-DCMAKE_INSTALL_PREFIX=D:\\Work\\GitHub\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\Python\\Python38\\Lib\\site-packages', '-DCMAKE_VERBOSE_MAKEFILE=1', '-DCUDA_NVCC_EXECUTABLE=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin', '-DJAVA_HOME=D:\\Java\\jdk1.8', '-DMSVC_Z7_OVERRIDE=OFF', '-DNUMPY_INCLUDE_DIR=C:\\Python\\Python38\\lib\\site-packages\\numpy\\core\\include', '-DONNX_NAMESPACE=onnx_c2', '-DPYTHON_EXECUTABLE=C:\\Python\\Python38\\python.exe', '-DPYTHON_INCLUDE_DIR=C:\\Python\\Python38\\include', '-DUSE_CUDA=ON', '-DUSE_DISTRIBUTED=OFF', '-DUSE_NINJA=OFF', '-DUSE_NUMPY=True', '-DUSE_OBSERVERS=OFF', 'D:\\Work\\GitHub\\pytorch']' returned non-zero exit status 1.

**Comment by peterjc123** [comment]
@huwei1024 Well, the message you provided is very useless. Would you please provide the full log? BTW, may I ask why do you want to build it from source?

**Comment by huwei1024** [comment]
@peterjc123 
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce 940MX
Nvidia driver version: 451.67
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect


erorr:
See also "D:/Work/GitHub/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "D:/Work/GitHub/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "tools\build_libtorch.py", line 19, in <module>
    build_caffe2(version=None, cmake_python_library=None, build_python=False,
  File "D:\Work\GitHub\pytorch\tools\build_pytorch_libs.py", line 50, in build_caffe2
    cmake.generate(version,
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 330, in generate
    self.run(args, env=my_env)
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GVisual Studio 16 2019', '-Ax64', '-Tversion=14.27,host=x64', '-DBUILDING_WITH_TORCH_LIBS=OFF', '-DBUILD_BINARY=OFF', '-DBUILD_PYTHON=False', '-DBUILD_SHARED_LIBS=OFF', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 16 2019', '-DCMAKE_GENERATOR_TOOLSET_VERSION=14.27', '-DCMAKE_INSTALL_PREFIX=D:\\Work\\GitHub\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\Python\\Python38\\Lib\\site-packages', '-DCMAKE_VERBOSE_MAKEFILE=1', '-DCUDA_NVCC_EXECUTABLE=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin', '-DJAVA_HOME=D:\\Java\\jdk1.8', '-DMSVC_Z7_OVERRIDE=OFF', '-DNUMPY_INCLUDE_DIR=C:\\Python\\Python38\\lib\\site-packages\\numpy\\core\\include', '-DONNX_NAMESPACE=onnx_c2', '-DPYTHON_EXECUTABLE=C:\\Python\\Python38\\python.exe', '-DPYTHON_INCLUDE_DIR=C:\\Python\\Python38\\include', '-DUSE_CUDA=ON', '-DUSE_DISTRIBUTED=OFF', '-DUSE_NINJA=OFF', '-DUSE_NUMPY=True', '-DUSE_OBSERVERS=OFF', '-DUSE_OPENCV=1', 'D:\\Work\\GitHub\\pytorch']' returned non-zero exit status 1.
"Caffe2 building failed"



[CMakeOutput.log](https://github.com/pytorch/pytorch/files/5646364/CMakeOutput.log)
[CMakeError.log](https://github.com/pytorch/pytorch/files/5646365/CMakeError.log)

**Comment by peterjc123** [comment]
@huwei1024 The useful logs are printed out in the console, not in those log files. BTW, I still don't understand what you are trying to do. We have prebulit LibTorch and PyTorch binaries. Why do you want to build from source? However, if you really want to build from source, please follow the following process using CMD.
```cmd
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch

git submodule sync
git submodule update --init --recursive

set CMAKE_GENERATOR=Visual Studio 16 2019

set CMAKE_GENERATOR_TOOLSET_VERSION=14.27
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%

python setup.py install
```

**Comment by huwei1024** [comment]
@peterjc123 
Because I installed Python3.9, i cant install pytorch from pip, so i want to build from source.

**Comment by peterjc123** [comment]
@huwei1024 We have started to provide python 3.9 binaries in the nightly channel.

**Comment by huwei1024** [comment]
--   Public Dependencies  : Threads::Threads;caffe2::mkldnn
--   Private Dependencies : pthreadpool;cpuinfo;XNNPACK;fbgemm;fp16;aten_op_header_gen;foxi_loader;fmt::fmt-header-only
-- Configuring incomplete, errors occurred!
See also "D:/Work/GitHub/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "D:/Work/GitHub/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "D:\Work\GitHub\pytorch\tools\build_pytorch_libs.py", line 50, in build_caffe2
    cmake.generate(version,
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 330, in generate
    self.run(args, env=my_env)
  File "D:\Work\GitHub\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GVisual Studio 16 2019', '-Ax64', '-Tversion=14.27,host=x64', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_GENERATOR=Visual Studio 16 2019', '-DCMAKE_GENERATOR_TOOLSET_VERSION=14.27', '-DCMAKE_INSTALL_PREFIX=D:\\Work\\GitHub\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\Python\\Python38\\Lib\\site-packages', '-DCUDA_NVCC_EXECUTABLE=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin', '-DJAVA_HOME=D:\\Java\\jdk1.8', '-DNUMPY_INCLUDE_DIR=C:\\Python\\Python38\\lib\\site-packages\\numpy\\core\\include', '-DPYTHON_EXECUTABLE=C:\\Python\\Python38\\python.exe', '-DPYTHON_INCLUDE_DIR=C:\\Python\\Python38\\include', '-DPYTHON_LIBRARY=C:\\Python\\Python38/libs/python38.lib', '-DTORCH_BUILD_VERSION=1.8.0a0', '-DUSE_CUDA=ON', '-DUSE_NINJA=OFF', '-DUSE_NUMPY=True', 'D:\\Work\\GitHub\\pytorch']' returned non-zero exit status 1.

**Comment by huwei1024** [comment]
> @huwei1024 We have started to provide python 3.9 binaries in the nightly channel.
ok, Thank you.

**Comment by huwei1024** [comment]
@peterjc123  hi ,can i install pytorch on MacBookPro M1 ?

**Comment by peterjc123** [comment]
@malfet knows the answer.

**Comment by huwei1024** [comment]
@malfet How can I install pytorch on MacBookPro M1 ?

**Comment by malfet** [comment]
@huwei1024 you can build it locally, or try downloading a nightly.
