### ISSUE TITLE
JIT-compiled function produces incorrect results

### ISSUE THREAD

**Issue by ak-source** [pytorch/pytorch#48533]
Seems related to broadcasting & TensorExpr fusion.

## To Reproduce

```
import torch

@torch.jit.script
def f(p,a):
	return torch.erfinv(p) * a.sqrt()

p = torch.linspace(0.1,0.9,64,device="cuda")
#p = p.expand(320,-1).contiguous() #not a fix
a = torch.empty(320,1,device="cuda").uniform_(6., 15000.0)
a.requires_grad_() #no error in nograd mode
#p,a = torch.broadcast_tensors(p,a) #fix

r1=f(p,a)
r2=f(p,a)
print(torch.allclose(r1,r2))
print((r1-r2).abs().max())
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0a0 (git)
 - OS (e.g., Linux): windows
 - How you installed PyTorch (`conda`, `pip`, source): source
 - CUDA/cuDNN version: 10.1

cc @gmagogsfm

**Comment by ngimel** [comment]
Repro without requires_grad(note returning 2 tensors from the function):
```
import torch

@torch.jit.script
def f(p,a):
    tmp = a.sqrt()
    return (tmp,p * tmp)

p = torch.linspace(0.1,0.9,4,device="cuda")
#p = p.expand(320,-1).contiguous() #not a fix
a = torch.ones(16,1,device="cuda")
#a.requires_grad_() #no error in nograd mode
#p,a = torch.broadcast_tensors(p,a) #fix

r1=f(p,a)[1]
r2=f(p,a)[1]
print(torch.allclose(r1,r2))
print((r1-r2).abs().max())
```

**Comment by navahgar** [comment]
Thanks for the repro steps. Looking into this.

**Comment by ak-source** [comment]
Hi, thanks for investigating this.

Please try the script below. Unless my non-clean rebuild is at fault, there is still a problem, only first 512 values are correct. Not sure why requires_grad_ line makes a difference.

```
@torch.jit.script
def f(p,a):
    tmp = a.sqrt()
    return (tmp,p + tmp)

p = torch.arange(1,65,dtype=torch.float32,device="cuda")
a = torch.arange(1,33,dtype=torch.float32,device="cuda").unsqueeze_(-1).mul_(100.0).square_()
a.requires_grad_() #no error in nograd mode

r1=f(p,a)[1]
r2=f(p,a)[1]
d = (r2-r1).abs()

print(torch.allclose(r1,r2))
print(d.shape, d.stride()) #32x64

for i in range(a.shape[0]):
    for j in range(p.shape[0]):
        if d[i,j] > 0.1: print(i,j, i * p.shape[0] + j, r1[i,j].item(), r2[i,j].item())
```

**Comment by navahgar** [comment]
The problem is that there is a dependency from `sqrt` to `+` in function `f`, due to which we need to add `SyncThreads` between those statements. That was missing. My attached draft PR should fix it.

**Comment by ak-source** [comment]
I should have mentioned that I've applied your patch. It fixes the small tensor case in the test, but differentiable graph with multiple thread blocks seems to have some additional issue.

**Comment by navahgar** [comment]
Okay, thanks for the update. I ll check it out.

**Comment by ZolotukhinM** [comment]
@ak-source, #48967 should hopefully fix the issue: I've checked with your latest repro and the one at the top: both of them pass with that PR. Please let us know if you hit more issues!

PS: sorry for that github spam above - that's an unfortunate side effect of mentioning the issue in a commit message.

**Comment by ak-source** [comment]
Looks good so far, approx. matching non-jitted model's results, good job!

One thing I've noted, using inputs expanded with broadcast_tensors can still be benefitial, as better kernel code is produced. But this changes semantics (tmp tensor above becomes full size).
