### ISSUE TITLE
C++ Inconsistency/bug in pow() function when mixing cuda tensor and cpu scalar.

### ISSUE THREAD

**Issue by AndersGarpebring** [pytorch/pytorch#48541]
## 🐛 Bug

As I understand it, it should be possible to mix cpu and cuda if the CPU tensor is a scalar. At least it works fine for many operations like multiplication and adding. However with pow I get an exception encouraging me to report a bug.

Error message: 'iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at "C:\\w\\b\\windows\\pytorch\\aten\\src\\ATen/native/cuda/Loops.cuh":94, please report a bug to PyTorch. '

## To Reproduce
The following code works fine for the 3 first operations, but the line with the pow function throws an exception.

        auto v = torch::ones(2, TensorOptions().device("cuda:0"));
        auto options = TensorOptions(ScalarType::Float);
        Tensor z = torch::tensor(3.0f, options);
        auto a = v + z;
        auto b = v * z;
        auto c = torch::atan2(v, z);
        auto d = v.pow(z);

I also descovered that it is even simpler to reproduce in python:

        torch.pow(torch.tensor(2, device='cuda:0'),torch.tensor(3))

## Expected behavior
Just like the multiply and atan2 I expected the pow computation to go through.

## Environment
 - Libtorch Version (e.g., 1.0): 1.7.0 (debug)
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): Downloaded v1.7.0 from the homepage with the latest CUDA version.
 - Build command you used (if compiling from source):
 - Python version: Libtorch in c++
 - CUDA/cuDNN version: cuDNN 11.0
 - GPU models and configuration: Nvidia GTX1650 Max-Q
 - Any other relevant information:

**Comment by kshitij12345** [comment]
Looks like it is fixed on master. Probably installing the nightly would fix the issue.

![Screenshot from 2020-11-30 20-34-43](https://user-images.githubusercontent.com/19503980/100626245-96c52b80-334b-11eb-962c-27f2e1ba0633.png)

**Comment by ngimel** [comment]
Fixed in #46320
