### ISSUE TITLE
[complex] torch.sigmoid: sigmoid does not support automatic differentiation for outputs with complex dtype

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#48552]
```python
import torch
x = torch.tensor(1, dtype=torch.cfloat)
x.requires_grad = True
y = torch.sigmoid(x)
y.backward()
```

**Output**:
```
Traceback (most recent call last):
  File "test/test_exp.py", line 16, in <module>
    y = torch.sigmoid(x)
RuntimeError: sigmoid does not support automatic differentiation for outputs with complex dtype.
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano

**Comment by mruberry** [comment]
Thank you for filing this issue, @kshitij12345. Note that SciPy's expit also does not support complex input:

```
scipy.special.expit(np.array(1, dtype=np.cdouble))
: TypeError: ufunc 'expit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

However, I think the definition is valid for complex numbers and, if it is, we would accept a PR implementing the behavior.

As an aside, PyTorch's use of the name "sigmoid" for this function seems odd. "Logistic" or "expit" are probably better names.
