### ISSUE TITLE
Error in fully_qualified_type_name_impl() on windows. __FUNCSIG__ doesn't match

### ISSUE THREAD

**Issue by zfenice** [pytorch/pytorch#48568]
## 🐛 Bug

Under Visual Studio 2019, if I use the compiled binaries I would get the following error due to discrepancy in function signature. The words "class" and "void" do not exist in the function signature. If I remove these words from the source code and compile everything works perfectly.
![Capture](https://user-images.githubusercontent.com/75228100/100557549-f6520700-3277-11eb-85c9-3a1a2f28dbf8.PNG)
fully_qualified_type_name_impl() in c10\utils\typeindex.h

## To Reproduce

It happens if I call
CAFFE_ENFORCE(workSpace.RunNet(predictNet_.name()));

## Expected behavior

It should not crash

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): Precompiled Binaries
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Geforce GTX 1650
 - Any other relevant information:

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
@zfenice Please post your VS version.

**Comment by peterjc123** [comment]
And it would be great if you could attach a small code sample for us to reproduce this issue.

**Comment by zfenice** [comment]
I'm using Visual Studio Community 2019 Version 16.8.2

I am running the sample code provided by detectron2

    caffe2::GlobalInit();

    // initialize Net and Workspace
    Workspace workSpace;
    caffe2::NetDef initNet_, predictNet_;
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_init_net, &initNet_));
    CAFFE_ENFORCE(ReadProtoFromFile(FLAGS_predict_net, &predictNet_));

    int predictNet_size = predictNet_.external_input_size();
    int initNet_size = initNet_.op_size();

    for (int i = 0; i < predictNet_size; i++)
    {
        std::string str = predictNet_.external_input()[i];
        workSpace.CreateBlob(str);
    }

    CAFFE_ENFORCE(workSpace.CreateNet(predictNet_));
    CAFFE_ENFORCE(workSpace.RunNetOnce(initNet_));

And getting this error with the following stack
![Capture2](https://user-images.githubusercontent.com/75228100/100813487-7493e200-340d-11eb-8b2c-51f0b76b8571.PNG)

on the following function RunNetOnce()
![Capture3](https://user-images.githubusercontent.com/75228100/100813560-8ffeed00-340d-11eb-8cde-ca67cf6cf807.PNG)

fully_qualified_type_name_impl() expects the signature of the function to look like
`class c10::basic_string_view<char> __cdecl c10::util::detail::fully_qualified_type_name_impl<T>(void)`
but it's
`c10::basic_string_view<char> c10::util::detail::fully_qualified_type_name_impl<T>()`

**Comment by peterjc123** [comment]
One thing I want to confirm is whether this is only a VS-16.8 thing?

**Comment by zfenice** [comment]
I've just spent hours trying different versions. Unfortunately, I found out that I can't link to the library (specifically protobuf.lib) because of non compatibility issue with older versions of VS explained here:
https://developercommunity.visualstudio.com/content/problem/1010557/-dyn-tls-on-demand-init-and-tls-guard-related-weir.html
So only versions of VS2019 v.16.5 or higher can be tested. I was able to get 16.7 which gave the same error.

**Comment by peterjc123** [comment]
Sorry for late reply. Would you please create a PR based on your findings?

**Comment by zfenice** [comment]
I figured out the issue and I created a pull request. Even if it compiles fine on my PC is fails to pass the Circleci checks for cuda.
The issue is that TypeIndex.h is compiles in certain .cu files in torch_cuda. So the __FUNCSIG__ has this different output than what a gcc has. I only added a check to see if the code is being compiled by NVCC and then it will use the correct function signature.

**Comment by peterjc123** [comment]
> I figured out the issue and I created a pull request. Even if it compiles fine on my PC is fails to pass the Circleci checks for cuda.
> The issue is that TypeIndex.h is compiles in certain .cu files in torch_cuda. So the **FUNCSIG** has this different output than what a gcc has. I only added a check to see if the code is being compiled by NVCC and then it will use the correct function signature.

Thanks for the investigation and I've reviewed your PR.
