### ISSUE TITLE
NCCL backend doesn't use MASTER_PORT during reconnect

### ISSUE THREAD

**Issue by r-t-m** [pytorch/pytorch#48575]
We try to leverage distributed training using NCCL backend in kubernetes 1.17 (specifically kubeflow 1.1) with 1 master and multiple workers. During initial setup all is working fine until the error in one of the worker pod happens and kubernetes restarts the failed pod. After restart NCCL(?) doesn't want to honor specified MASTER_PORT and is using random one to reconnect to the master as a result worker can't reconnect at all for the whole time. MASTER_ADDRess is correct.

Logs from failed worker
<pre>
Skipping virtualenv creation, as specified in config file.
Downloading: 100%|██████████| 899k/899k [00:00<00:00, 1.87MB/s]
Downloading: 100%|██████████| 456k/456k [00:00<00:00, 1.13MB/s]
Downloading: 2.57kB [00:00, 2.62MB/s]
Using custom data configuration default
Reusing dataset text (/home/<user>/text/..>)
Loading cached processed dataset at /home/<user>/text/../cache-f6c95d4333527631.arrow
Loading cached processed dataset at /home/<user>/text/../cache-24dcc973a7ebb8df.arrow
Loading cached processed dataset at /home/<user>/text/../cache-7dd69a51fa844ac6.arrow
pytorch-dist-worker-7:1:1 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
pytorch-dist-worker-7:1:1 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
pytorch-dist-worker-7:1:1 [0] NCCL INFO Bootstrap : Using [0]eth0:10.201.2.121<0>
pytorch-dist-worker-7:1:1 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

pytorch-dist-worker-7:1:1 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
pytorch-dist-worker-7:1:1 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
pytorch-dist-worker-7:1:1 [0] NCCL INFO NCCL_SOCKET_IFNAME set to eth0
pytorch-dist-worker-7:1:1 [0] NCCL INFO NET/Socket : Using [0]eth0:10.201.2.121<0>
pytorch-dist-worker-7:1:1 [0] NCCL INFO Using network Socket
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying
...
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying
pytorch-dist-worker-7:1:31 [0] NCCL INFO Call to connect returned Connection refused, retrying

pytorch-dist-worker-7:1:31 [0] include/socket.h:403 <b>NCCL WARN Connect to 10.201.0.106<60475></b> failed : Connection refused
pytorch-dist-worker-7:1:31 [0] NCCL INFO bootstrap.cc:95 -> 2
pytorch-dist-worker-7:1:31 [0] NCCL INFO bootstrap.cc:309 -> 2
pytorch-dist-worker-7:1:31 [0] NCCL INFO init.cc:555 -> 2
pytorch-dist-worker-7:1:31 [0] NCCL INFO init.cc:840 -> 2
pytorch-dist-worker-7:1:31 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/training.py", line 77, in main
    dist.init_process_group(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729096996/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
World Size: 9
Loading the datasets ...
Tokenizing the dataset ...
Using distributed PyTorch with nccl backend
MASTER_ADDR: pytorch-dist-master-0, <b>MASTER_PORT: 23456</b>
</pre>

Logs from master
<pre>
pytorch-dist-master-0:1:40 [0] include/socket.h:416 NCCL WARN Net : Connection closed by remote peer
pytorch-dist-master-0:1:40 [0] NCCL INFO transport/net_socket.cc:405 -> 2
pytorch-dist-master-0:1:40 [0] NCCL INFO include/net.h:28 -> 2
pytorch-dist-master-0:1:40 [0] NCCL INFO transport/net.cc:357 -> 2
pytorch-dist-master-0:1:40 [0] NCCL INFO proxy.cc:198 -> 2 [Proxy Thread]
</pre>

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by osalpekar** [comment]
@r-t-m I don't think simply restarting the failed pod would be sufficient - this might require you to bring down the NCCL ProcessGroup that was created earlier and re-rendezvous to create a new ProcessGroup once all the nodes are back up (ProcessGroups assume the worker gang is static so nodes cannot simply leave/re-enter). Torchelastic can help with this process of bringing down the ProcessGroup and doing re-rendezvous when faced with worker errors. 

cc @jiayisuse @kiukchung

**Comment by jensam** [comment]
It seems the worker pod failing was a symptom of the way we were configuring the pre-trained model ‘Roberta’ we are fine-tuning. This was causing the worker to fail, it seems. After fixing the Roberta configuration we are not seeing the same NCCL connection problems.

**Comment by pritamdamania87** [comment]
@jensam In that case, is it ok to close out this issue? As Omkar mentioned above you need to restart everything and reinitialize a new process group or use torchelastic.

**Comment by r-t-m** [comment]
@pritamdamania87 @osalpekar thanks for the suggestions!
