### ISSUE TITLE
CUDNN_LIBRARY selection

### ISSUE THREAD

**Issue by achainan** [pytorch/pytorch#4860]
https://github.com/pytorch/pytorch/blob/94f439c07c4f3e13fbd87016212b3534d31a7165/tools/setup_helpers/cudnn.py#L59-L63

If there was two libcudnn files (libcudnn.5.dylib and libcudnn.7.dylib) in the folder wouldn't it result in taking the older version (libcudnn.5.dylib)?

Maybe adding a warning or something to insure its the right lib?

**Comment by ezyang** [comment]
I think #3251 and #5042 are quite possibly related.
