### ISSUE TITLE
Are the results exactly the same on Mac and on Ubuntu?

### ISSUE THREAD

**Issue by waldstein1983** [pytorch/pytorch#4863]
Here is what I am testing:
https://github.com/devnag/pytorch-generative-adversarial-networks
A GAN example.

I found that for the same code, the results are different when running on Mac (Python 3.6) and on Ubuntu (Python 2.7). All Pytorch is the latest release version.
Plus, on Ubuntu, the example have a good result but on Mac, unfortunately, in most cases, the result is not well enough.

Is that because Python version?

**Comment by apaszke** [comment]
Python version, number of cores, PyTorch version, dependency versions... there are a lot of possible causes. We don’t expect to give exactly the same results on different platforms

**Comment by soumith** [comment]
additionally, this GAN example is not setting a fixed random seed. So on each different machine it's possible that the GAN (which is quite unstable) is not converging because of the seed.
