### ISSUE TITLE
[libtorch] CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by linjiapro** [pytorch/pytorch#48636]
## 🐛 Bug

I encountered the following sporadic crash while doing ResNet training using libtorch:

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from launch_vectorized_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fa41d1a4b89 in /home/lin/Engine/ThirdParty/libtorch/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<at::native::MulScalarFunctor<c10::Half, float> >(at::TensorIterator&, at::native::MulScalarFunctor<c10::Half, float> const&) + 0xa82 (0x7fa41fb0f7a2 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel<at::native::MulScalarFunctor<c10::Half, float> >(at::TensorIterator&, at::native::MulScalarFunctor<c10::Half, float> const&) + 0x16d (0x7fa41fb10f6d in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x270bab6 (0x7fa41faddab6 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #4: at::native::mul_kernel_cuda(at::TensorIterator&) + 0x5a (0x7fa41fae264a in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xcd9184 (0x7fa476f99184 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #6: at::native::mul_out(at::Tensor&, at::Tensor const&, at::Tensor const&) + 0x4e (0x7fa476f8cdfe in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #7: at::native::mul_(at::Tensor&, c10::Scalar) + 0x45 (0x7fa476f8ce95 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x159e3ac (0x7fa47785e3ac in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x136182d (0x7fa47762182d in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #10: at::Tensor& c10::Dispatcher::callWithDispatchKey<at::Tensor&, at::Tensor&, c10::Scalar>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, c10::Scalar)> const&, c10::DispatchKey, at::Tensor&, c10::Scalar) const + 0x242 (0x7fa47779f162 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #11: at::Tensor::mul_(c10::Scalar) const + 0xee (0x7fa47791755e in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2aa9f06 (0x7fa478d69f06 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x136182d (0x7fa47762182d in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #14: at::Tensor& c10::Dispatcher::callWithDispatchKey<at::Tensor&, at::Tensor&, c10::Scalar>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, c10::Scalar)> const&, c10::DispatchKey, at::Tensor&, c10::Scalar) const + 0x242 (0x7fa47779f162 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #15: at::Tensor::mul_(c10::Scalar) const + 0xee (0x7fa47791755e in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #16: torch::optim::Adam::step(std::function<at::Tensor ()>) + 0x4b7 (0x7fa4797923d7 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)

## Environment
Collecting environment information...
PyTorch version: 1.7.0
Is debug build: No
I used libtorch.

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: YES
CUDA runtime version: 11.1
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
Found cuDNN: v8.0.5

Nvidia driver version: 455.32.00

cc @ngimel

**Comment by linjiapro** [comment]
Another crash stack which is the similar to the one I pasted above:

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from launch_vectorized_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fdefe845b89 in /home/lin/Engine/ThirdParty/libtorch/lib/libc10.so)
frame #1: void at::native::gpu_kernel_impl<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::(anonymous namespace)::leaky_relu_backward_kernel, 3u>, c10::Half (c10::Half, c10::Half), c10::Half> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::(anonymous namespace)::leaky_relu_backward_kernel, 3u>, c10::Half (c10::Half, c10::Half), c10::Half> const&) + 0x2586 (0x7fdf00d6ad66 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #2: void at::native::gpu_kernel<__nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::(anonymous namespace)::leaky_relu_backward_kernel, 3u>, c10::Half (c10::Half, c10::Half), c10::Half> >(at::TensorIterator&, __nv_hdl_wrapper_t<false, false, __nv_dl_tag<void (*)(at::TensorIterator&, c10::Scalar), &at::native::(anonymous namespace)::leaky_relu_backward_kernel, 3u>, c10::Half (c10::Half, c10::Half), c10::Half> const&) + 0x16d (0x7fdf00d6b0bd in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x2234d50 (0x7fdf00ca7d50 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #4: at::native::(anonymous namespace)::leaky_relu_backward_kernel(at::TensorIterator&, c10::Scalar) + 0x2a (0x7fdf00ca852a in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #5: at::native::leaky_relu_backward(at::Tensor const&, at::Tensor const&, c10::Scalar, bool) + 0xb3 (0x7fdf585c42f3 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x4018276 (0x7fdf02a8b276 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x40507b9 (0x7fdf02ac37b9 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cuda.so)
frame #8: at::Tensor c10::Dispatcher::callWithDispatchKey<at::Tensor, at::Tensor const&, at::Tensor const&, c10::Scalar, bool>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&, c10::Scalar, bool)> const&, c10::DispatchKey, at::Tensor const&, at::Tensor const&, c10::Scalar, bool) const + 0x2af (0x7fdf58eb7e5f in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #9: at::leaky_relu_backward(at::Tensor const&, at::Tensor const&, c10::Scalar, bool) + 0x159 (0x7fdf58dd3b39 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2986f90 (0x7fdf5a2e7f90 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x1362669 (0x7fdf58cc3669 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #12: at::Tensor c10::Dispatcher::callWithDispatchKey<at::Tensor, at::Tensor const&, at::Tensor const&, c10::Scalar, bool>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, at::Tensor const&, c10::Scalar, bool)> const&, c10::DispatchKey, at::Tensor const&, at::Tensor const&, c10::Scalar, bool) const + 0x2af (0x7fdf58eb7e5f in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #13: at::leaky_relu_backward(at::Tensor const&, at::Tensor const&, c10::Scalar, bool) + 0x159 (0x7fdf58dd3b39 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #14: torch::autograd::generated::LeakyReluBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x1b4 (0x7fdf5a24c5f4 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x2d733ba (0x7fdf5a6d43ba in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #16: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1726 (0x7fdf5a6cfa56 in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #17: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x29a (0x7fdf5a6d030a in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x9a (0x7fdf5a6cb6ba in /home/lin/Engine/ThirdParty/libtorch/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0xd7112 (0x7fdefdc28112 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #20: <unknown function> + 0x9609 (0x7fdf57929609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #21: clone + 0x43 (0x7fdefda66293 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by ngimel** [comment]
Please run with CUDA_LAUNCH_BLOCKING=1 to get correct backtrace.

**Comment by linjiapro** [comment]
I tried multiple times to reproduce this but failed. This might be a one-off event. Let me close it.
