### ISSUE TITLE
torch.nn.Module.named_parameters has wrong type annotation

### ISSUE THREAD

**Issue by V3RGANz** [pytorch/pytorch#48640]
## 🐛 Bug

`named_parameters(prefix: str = '', recurse: bool = True) -> Iterator[Tuple[str, torch.Tensor]]` has `torch.Tensor` in return type, but seems that it always narrower type - `nn.Parameter` (as in `torch.nn.Module.parameters` signature)

## Environment

pytorch 1.7

cc @albanD @mruberry @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by mruberry** [comment]
Thank you for reporting this issue, @V3RGANz. I'll let our typing experts comment.

**Comment by rgommers** [comment]
Based on the implementation, typing as `Parameter` seems correct. This is more a usage question than a typing question though - are there any `Module` subclasses floating around that do _not_ return `Tuple(str, Parameter)` from that method?

**Comment by ezyang** [comment]
The intention of the method name seems pretty clear. Let's just update it.

**Comment by rgommers** [comment]
This will be fixed by gh-49045

**Comment by guilhermeleobas** [comment]
I believe this issue can be closed since gh-49045 was merged.
