### ISSUE TITLE
"CUDA error: out of memory" for the last Batch

### ISSUE THREAD

**Issue by jiecaoyu** [pytorch/pytorch#4864]
I am trying to train ResNet-18 on two GTX Titan X GPU.

In each epoch, it runs fine for the first 5004 iterations (batch size: 256). However, for the last batch with a batch size of 143, the training breaks due to "CUDA error: out of memory".

Here is the error message:
```
Traceback (most recent call last):
  File "main.py", line 404, in <module>
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 119, in train
    loss.backward()
  File "/home/jiecaoyu/.local/lib/python2.7/site-packages/torch/autograd/variable.py", line 127, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jiecaoyu/.local/lib/python2.7/site-packages/torch/autograd/__init__.py", line 83, in backward
    variables, grad_variables, retain_graph, create_graph)
RuntimeError: CUDA error: out of memory
```

Decreasing the batch size does not help since a batch size of 256 runs well for the first 5000 iterations.
Another interesting thing is sometimes this problem may disappear.

---------------------------------------------------
I tried to use
```python
torch.cuda.empty_cache()
```
to release unnecessary GPU memory caching before the last batch but it does not help.

---------------------------------------------------
Environment info:
- OS: Ubuntu 14.04
- PyTorch version: 0.4.0a0+4970e73
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7.6
- CUDA/cuDNN version: 8.0 / 7.0.5
- GPU models and configuration: GTX Titan X
- GCC version (if compiling from source): 4.8.4

**Comment by dddzg** [comment]
I have encountered from the same problem.Maybe the last irregular batch will use more memory(I don't know the reason).At last,I found that DataLoader has the option **drop_last** that can drop out the last irregular batch,I used it to solve  the problem.

**Comment by mruberry** [comment]
Closing this issue due to age. If this is still occurring with a recent version of PyTorch please update and reopen.
