### ISSUE TITLE
torch v1.2.0. save to onnx model, torch.onnx.export save nothing

### ISSUE THREAD

**Issue by godblessY** [pytorch/pytorch#48646]
https://github.com/pytorch/pytorch/blob/ccd20e995fb56a1aafefd90c0f2c68c537534c67/torch/onnx/utils.py#L341

## for large models, if need to sleep a while to for export onnx model to write?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Not sure what the issues is here. 
From the title it seems that you are using 1.2. Please upgrade to the latest PyTorch as several updates to ONNX export have gone in since then.
If you still see any issues, please open an issue with detailed description and repro.
