### ISSUE TITLE
DataParallel module leaks memory

### ISSUE THREAD

**Issue by khanrc** [pytorch/pytorch#4865]
## Environment

- OS: ubuntu 14.04, 16.04
- PyTorch version: 0.3
- How you installed PyTorch (conda, pip, source): pip
- Python version: 2.7
- CUDA/cuDNN version: 8.0/6.0, 9.0/7.0
- GPU models and configuration: Geforce 1080Ti, TITAN XP

## Symptom

https://discuss.pytorch.org/t/dataparallel-makes-garbages/12771
https://nbviewer.jupyter.org/gist/khanrc/a21dbe0dc316c31387a56b683b94aa2d

- Memory leak arises when using DataParallel module 
- It mainly came from the replicate module, as a results of my tests
  - So more gpu devices (more replicas) make more leak
- In the above jupyter notebook link, you can see the collected garbages, which indicates memory leak
- This memory leak come from DataParallel module; There is no leak without DataParallel module

## Reproduce

Reproducing is very easy. You can reproduce this problem using above jupyter notebook code. Further, I've always had this problem every time I use the DataParallel module.

**Comment by davinnovation** [comment]
Same Problem on Python 3.6, Windows 10

**Comment by davinnovation** [comment]
Worked on this feature -> problem has occurred in scatter_map recursive

**Comment by davinnovation** [comment]
Noticed recursion is not main problem of leak. Should be go deeper with Scatter.apply

**Comment by khanrc** [comment]
Main part of leak come from replicate function in my test. Replicate function is called only with multi gpu.

**Comment by zou3519** [comment]
@khanrc 

I ran the code in your jupyter notebook with one GPU and got the following:
```
Train Epoch: 0 [0/60000 (0%)]   Loss: 2.299733
collected 10
[]
collected 5
[]
collected 5
[]
collected 5
[]
collected 5
[]
collected 5
[]
total collected 35
```
Those numbers aren't as large as the ones in your notebook so I'm curious what you think about that. As apaszke mentioned, if you create cycles in your data structures you get more objects the garbage collector will collect.

**Comment by khanrc** [comment]
@zou3519 How many GPUs you used? The numbers are same as #GPU=1 case in my test. The numbers are small when #GPU=1 because replicate function is not called.

@apaszke As you can see in [the above code](https://nbviewer.jupyter.org/gist/khanrc/a21dbe0dc316c31387a56b683b94aa2d), there is no cycle in my data structure (more precisely, there is no custom data structure).

In my experiments, the number of garbages are depends on the number of GPUs and the number of layers (the number of parameters is likely to be the factor). I don't think there is a problem with my very simple code.

**Comment by zou3519** [comment]
@khanrc That was with 1 GPU. On 8 GPUs I get the following:
```
Train Epoch: 0 [0/60000 (0%)]   Loss: 2.307702
collected 10
[]
collected 10
[]
collected 10
[]
collected 10
[]
collected 10
[]
collected 10
[]
total collected 60
```
I am running on master, but I'll take a look at running on 0.3

**Comment by zou3519** [comment]
@khanrc Turns out I was running python 3. On python 2.7 there are indeed reference cycles being created with a large number of objects. Am investigating.

**Comment by khanrc** [comment]
@zou3519 IMHO, the circular reference is itself memory leak, even if it is not something special in python. I just think gc collect memory leak.

However, whatever we call it, the circular reference make garbages and it causes run of garbage collector. It bring down the training performance (significantly in my case). Therefore if we can correct it, we should do that. But if it come from python 2.7 internally as you said, I should move to the python 3 :) I'll try it.

**Comment by zou3519** [comment]
@khanrc on multi-gpu, 10 of the 100+ objects that have reference cycles that you saw are from PyTorch, while the rest look like they're from Python 2.7 internals. On Python 3, you should see that using DataParallel will give you only those 10 objects to collect per forward pass. 

I'll fix the 10 objects that come from PyTorch code; the end result is that on Python 3 there should be no reference cycles at all in DataParallel.

**Comment by khanrc** [comment]
@zou3519 As you said, there is no reference cycle problem in python 3. It improved my training performance significantly - about 30%. Thanks! :D

**Comment by ngimel** [comment]
If you have trouble with DataParallel scaling, try distributed (within a node), it typically scales better https://github.com/csarofeen/examples/tree/dist_fp16/imagenet
