### ISSUE TITLE
Website layout suggestion regarding the navigation bar

### ISSUE THREAD

**Issue by rasbt** [pytorch/pytorch#4868]
I have two little suggestions with regard to improving the PyTorch website

1) It may be a good idea to include a link to the Tutorials in the navigation pane and rename the "Docs" to "API Docs" or so. This would make it easier for new users to find it. And for returning users, it would be easier than scrolling through the main page. 

Alternatively, the "Docs" button could be a nested button with "API, Tutorials, API" under it that open up upon hovering over it (like, e.g., in the Mkdocs templates)

2) It would maybe a nice thing to include a link to the "http://pytorch.org" main page on the http://pytorch.org/docs/ page. Sometimes, I am browsing the API docs and want to navigate back to the main page to get to & search the forum.

have the "docs" button be a

**Comment by Kaixhin** [comment]
Hi @rasbt, thanks for the suggestions. Do you mind raising this issue over at the [repo for the website](https://github.com/pytorch/pytorch.github.io/issues) and closing this one?

**Comment by rasbt** [comment]
That's a good idea -- have to admit that I didn't look to closely and somehow thought the files were under `docs/`. But yeah, makes total sense, and I just opened an issue there and will close this one here now
