### ISSUE TITLE
Error when running Dataloader with multiple workers

### ISSUE THREAD

**Issue by thematrixduo** [pytorch/pytorch#48709]
## 🐛 Bug

I got this error message while running dataloader with 40 workers to load Howto100M dataset (https://github.com/antoine77340/MIL-NCE_HowTo100M). The loader reads video files with ffmpeg and text files using pandas.read_csv().  My main issue is that I don't quite understand what the error is about. I guess there are some inner issues that are not raised.

## To Reproduce

Not sure if this is reproducible but:
1. Run the training script in this repo (https://github.com/antoine77340/MIL-NCE_HowTo100M).

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/pytorch_code/mmssl_graph/train_MILNCE.py", line 207, in main_worker
    train(train_loader, model, criterion, optimizer, scheduler, epoch, train_dataset, writer, args)
  File "/workspace/pytorch_code/mmssl_graph/train_MILNCE.py", line 225, in train
    for i_batch, sample_batch in enumerate(train_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 2 required positional arguments: 'stdout' and 'stderr'

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Tesla V100
 - Any other relevant information: Running with Docker container

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
The error is re-raised from subprocess of workers.
I roughly look into the code. You may check the `HT100M_DataLoader`. It seems related to error handling of ffmpeg-python.
Can you try to run without `--multiprocessing-distributed` and see what's going on?

**Comment by VitalyFedyunin** [comment]
Also running `DataLoader` with `num_workers = 0` helps to debug the issue.

**Comment by SsnL** [comment]
The cause is that we failed to reconstruct the exception. We should do something like https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/concurrent/futures/process.py#L129-L131 for our remote exception. Ctx: https://github.com/pytorch/pytorch/pull/40437

**Comment by thematrixduo** [comment]
I tried only data loading without distributed training, but got the same error.

**Comment by SsnL** [comment]
It's not about distributed training. Try single process dataloading.

**Comment by thematrixduo** [comment]
Thanks! Loading with single workers identifies the issue. I identified a corrupted video file that is causing the error for ffmpeg.
