### ISSUE TITLE
Memory leak CUDNN 7003

### ISSUE THREAD

**Issue by sanek777** [pytorch/pytorch#4872]
I updated pytorch to 0.3 using conda. I realized that there is a memory leak in RAM in my experiments. Later, I tried to compile from source python with CUDNN 6... and 7005, other versions of CUDNN solved the problem. Is it possible to update CUDNN (from 7003 to 7005) in conda/pip packages?

**Comment by apaszke** [comment]
Any chance to get a small script that would let us reproduce the leak?

**Comment by soumith** [comment]
@sanek777 0.3.1 will ship with 7005

**Comment by sanek777** [comment]
@soumith Okey, i think that this is good news. Closing problem.
