### ISSUE TITLE
TorchConfig.cmake setting IMPORTED_LOCATION unconditionally on torch import target

### ISSUE THREAD

**Issue by foundry-markf** [pytorch/pytorch#48724]
## 🐛 Bug

I'm new to dealing with PyTorch, but I encountered an issue at build time, when trying to build a consumer application with RELWITHDEBINFO CMake build type, whereas PyTorch was built with RELEASE build type, on Windows in a shared library build of PyTorch.

The error shown (from the ninja build tool we used as CMake generator):

```
ninja: error: 'torch-NOTFOUND', needed by 'test_pytorch.exe', missing and no known rule to make it 
```

referring a library for `torch` to be linked against.

I have traced this to this line

```
set_target_properties(torch PROPERTIES
    IMPORTED_LOCATION "${TORCH_LIBRARY}" <---- this property
    INTERFACE_INCLUDE_DIRECTORIES "${TORCH_INCLUDE_DIRS}"
    CXX_STANDARD 14
)
```
https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L129

I have inspected the variables, e.g. `TORCH_LIBRARY`, and they're all as I would expect and referring to files on disk, but what I have seen is that in shared library builds, the `torch` CMake import target is coming from caffe2's CMake target config files, and is a thin wrapper over linking CPU & GPU (in our build) import targets, so setting this `IMPORTED_LOCATION` seems incorrect for shared libs as it stomps over the import targets already set up.

I also note there's a comment further above in this file, referring to the `IMPORTED_LOCATION` property:
```
# Library dependencies.
if(@BUILD_SHARED_LIBS@)
  find_package(Caffe2 REQUIRED PATHS ${CMAKE_CURRENT_LIST_DIR}/../Caffe2)
  set(TORCH_LIBRARIES torch ${Caffe2_MAIN_LIBS})
else()
  add_library(torch STATIC IMPORTED) # set imported_location at the bottom
  set(TORCH_LIBRARIES torch)
endif()
```
https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L43

That makes me suspect that the `IMPORTED_LOCATION` is meant _only_ for static library builds.

Currently, if I either
a) comment out `IMPORTED_LOCATION "${TORCH_LIBRARY}"`, or
b) change it to `IMPORTED_LOCATION_NOCONFIG "${TORCH_LIBRARY}"`

my test app builds fine.

My suspicion is that probably https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L128-L135 needs wrapping in `if(NOT @BUILD_SHARED_LIBS@)`.

I have also gone further with an experiment, and terminated `TorchConfig.cmake` at the
```
find_package(Caffe2 REQUIRED PATHS ${CMAKE_CURRENT_LIST_DIR}/../Caffe2)
```
statement in shared builds, and my test app also builds fine. My hunch there (unverified in a larger test), is that a lot of the `find_library`'s content etc. in `TorchConfig.cmake` only need to be there to contribute to linking against a static `torch` library for the transient dependencies.

## To Reproduce

1. Build PyTorch in shared RELEASE CMake build type
2. Build a simple test app, referencing the torch import target, in RELWITHDEBINFO CMake build type.

## Expected behavior

A successfully linking test app against torch.lib (import lib) on Windows.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): Source build locally, VisualStudio 2017
 - Build command you used (if compiling from source): Through setup.py
 - Python version: 3.8

cc @malfet @seemethere @walterddr

**Comment by peterjc123** [comment]
@bdhirsh The easiest workground is that you use the Release configuration with the additional compiler flag `/Zi` and the additional linker flag `/DEBUG:FULL`.

**Comment by peterjc123** [comment]
@bdhirsh The easiest workground is that

> My suspicion is that probably https://github.com/pytorch/pytorch/blob/master/cmake/TorchConfig.cmake.in#L128-L135 needs wrapping in `if(NOT @BUILD_SHARED_LIBS@)`.

This sounds interesting. Any thoughts, @ezyang ?

**Comment by foundry-markf** [comment]
Thanks for the replies.

Although agreed, massaging the Release configuration compiler and link flags is one option, it isn't what a non-build-savvy developer will reach for, whereas changing a build type is straightforward.

We're going to apply a patch to PyTorch to make it work for those devs internally wanting to use RelWithDebInfo in their applications, so this ticket was about exploring the options we had to choose from, and if any also made sense for yourselves as maintainers (which would also direct us in our choice of patch, as we'd rather choose an official looking change).

**Comment by ezyang** [comment]
cc @malfet

@foundry-markf I agree with your analysis. Can you send us a PR for your change? One tweak to your suggested change is I'd make sure you only skip `IMPORTED_LOCATION` from the property setting; I'm guessing we still want the other properties.

One thing I still don't quite understand is why we need to manually setup the static library in the config file.  A not very satisfactory answer is, well, the generated `Caffe2Targets.cmake` doesn't have any static libraries in it, so we have to do it ourselves, but maybe that just means we haven't read the cmake manual carefully enough.

By the way, I went and looked at the history and the original setting was introduced in https://github.com/pytorch/pytorch/commit/7949250295d17bf6ebb953d268438c3a7df3a6c1 bullet (2); it looks like goldsborough was likely working off of some resource specifying how to write IMPORTED targets. https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/Exporting-and-Importing-Targets I'm guessing that at some later point in time, we switched to `install(TARGETS` which made this code unnecessary (except for static?!)

**Comment by foundry-markf** [comment]
Hello @ezyang,

Thank you for your response.

I've chased up on what we actually built in a local patch, and it's this:

```
diff --git a/cmake/TorchConfig.cmake.in b/cmake/TorchConfig.cmake.in
index ca6bdccddeddca9fb502396b4c31674bcf73a5f4..f525c52e5018d6f0cf8e6daf27538e4c99063ea6 100644
--- a/cmake/TorchConfig.cmake.in
+++ b/cmake/TorchConfig.cmake.in
@@ -125,13 +125,15 @@ if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
 endif()
 
 find_library(TORCH_LIBRARY torch PATHS "${TORCH_INSTALL_PREFIX}/lib")
-set_target_properties(torch PROPERTIES
-    IMPORTED_LOCATION "${TORCH_LIBRARY}"
-    INTERFACE_INCLUDE_DIRECTORIES "${TORCH_INCLUDE_DIRS}"
-    CXX_STANDARD 14
-)
-if(TORCH_CXX_FLAGS)
-  set_property(TARGET torch PROPERTY INTERFACE_COMPILE_OPTIONS "${TORCH_CXX_FLAGS}")
+if(NOT @BUILD_SHARED_LIBS@)
+  set_target_properties(torch PROPERTIES
+      IMPORTED_LOCATION "${TORCH_LIBRARY}"
+      INTERFACE_INCLUDE_DIRECTORIES "${TORCH_INCLUDE_DIRS}"
+      CXX_STANDARD 14
+  )
+  if(TORCH_CXX_FLAGS)
+    set_property(TARGET torch PROPERTY INTERFACE_COMPILE_OPTIONS "${TORCH_CXX_FLAGS}")
+  endif()
 endif()
 
 find_package_handle_standard_args(Torch DEFAULT_MSG TORCH_LIBRARY TORCH_INCLUDE_DIRS)
```

While this has been tested in trivial little home grown samples to verify the behaviour we were after, it's not been battle tested by us, and only in shared mode. At the moment, we don't actively build PyTorch as static libs.

I'm a little wary (although only by gut feeling) about modifying an imported target's properties outside of its originating file (Caffe2Targets.cmake). I cannot find any CMake docs/guidelines to back up that gut feeling though. However, since Caffe2 can be seen as a CMake subproject of PyTorch, perhaps it's not such a bad thing.

This is the only reason I really paused on the request to just limit the patch to only the `IMPORTED_LOCATION` property.

I thought I would at least show you what we've been applying as a comparison.

Two questions follow:
1) Can confirm what you would like to see as a PR please, then I can make it? Should it be based off the code in master, or another branch?

2) Also, I do see you've got CI in the form of CircleCI, in your repo. I'm not that familiar with that, but would like to confirm that you have tests for both shared and static builds of PyTorch, so this PR would get some coverage testing in both modes?

Many thanks!

**Comment by ezyang** [comment]
> I'm a little wary (although only by gut feeling) about modifying an imported target's properties outside of its originating file (Caffe2Targets.cmake). I cannot find any CMake docs/guidelines to back up that gut feeling though. However, since Caffe2 can be seen as a CMake subproject of PyTorch, perhaps it's not such a bad thing.

You may very well be right. My motivation for suggesting a more surgical change is to just reduce the possible unintended consequences. Even if modifying imported targets outside of the originating file is not very kosher, it's what the code currently does, so it's less likely to break someone

> Can confirm what you would like to see as a PR please, then I can make it? Should it be based off the code in master, or another branch?

If you want to send your patch directly as written, that's OK too. We can see what happens.

> Also, I do see you've got CI in the form of CircleCI, in your repo. I'm not that familiar with that, but would like to confirm that you have tests for both shared and static builds of PyTorch, so this PR would get some coverage testing in both modes?

We don't have static tests, unfortunately

**Comment by foundry-markf** [comment]
Thanks for the clarification. I would tend to agree with you then that the minimal change may be best under these circumstances, particularly as neither party can thoroughly test the static builds. I would not like to be the cause of giving other users of PyTorch a build headache.

**Comment by foundry-markf** [comment]
PR created, with the simplified patch.
At the very least, I do not have a CLA in place! Apologies, I did not see that in the contributing guide. Are there any notes on how to arrange it?
