### ISSUE TITLE
__torch_function__ PR may cause performance regression on GPU training

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#48748]
## 🐛 Bug

https://github.com/pytorch/pytorch/pull/37091 may cause performance regression on GPU training

Recently we've seen some training performance regressions on GPU. After investigation, we found that https://github.com/pytorch/pytorch/pull/37091 might be the root cause. Nsys profilings showed that CPU overheads are increased after this commit.

(Detailed perf numbers will be updated later.)

cc @hameerabbasi @rgommers @VitalyFedyunin @ngimel @csarofeen @ptrblck

**Comment by ezyang** [comment]
cc @hameerabbasi

**Comment by ezyang** [comment]
I'm hoping that this is just something dumb, similar to the situation with comparison ops that @robieta fixed at  https://github.com/pytorch/pytorch/pull/48018

**Comment by mcarilli** [comment]
This surfaced in a network that was already horribly CPU bound (so very vulnerable to CPU overhead increase).  The profile looked horrible end to end both before and after https://github.com/pytorch/pytorch/pull/37091, I couldn't tell if any particular op was the smoking gun.

**Comment by mcarilli** [comment]
@xwang233 is it possible to share the network where we saw these regressions? @ngimel @mruberry are looking for a simple-but-realistic model to check the CPU overhead of Ruberry's "Jiterator" prototype https://github.com/pytorch/pytorch/pull/48403 which implements a neat idea (lazily runtime-compile TensorIterator kernels only when a network uses them, to reduce initial build time, binary size, and on-device module memory footprint of libtorch_cuda.so).

**Comment by mruberry** [comment]
> Ruberry's "Jiterator" prototype 

@ngimel and @mruberry's prototype, comrade.

**Comment by xwang233** [comment]
Thanks for all the comments. I was using the following command for the profiling

```
python main_amp.py -a resnet152 --b 32 --workers 5 --prof 590 --epochs 1 -p 10 --opt-level O2 ./
```

where `main_amp.py` is from apex, https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py

I was working on cuda 11.1 + cudnn 8.0.4 A100. A container with this environment can be pulled at 
```
docker pull nvcr.io/nvidia/pytorch:20.11-py3
```
where apex is installed in `/opt/pytorch/apex`. Make sure to also rebuild apex after rebuild pytorch.

**Comment by xwang233** [comment]
Thanks @ezyang @robieta for the fix. I've tried the current master commit which included PR https://github.com/pytorch/pytorch/pull/48018, and the performance is not recovered.

**Comment by robieta** [comment]
naive question: why is a large ResNet CPU bound?

Also, I'm working on another PR to address more of the `__torch_function__` overheads. Should be ready for you to test by EoD.

**Comment by mcarilli** [comment]
@mruberry https://www.youtube.com/watch?v=rmwe54CkKQw

@xwang233 what nsight systems command did you use to make the profiles you gave me?

@robieta I think 32 is a small batch size for the network on A100.

**Comment by robieta** [comment]
Can you give https://github.com/pytorch/pytorch/pull/48776 a try and see if it helps?

**Comment by xwang233** [comment]
Thanks for the work in #48776 . I merged that onto current master at 79b9c034656652cad838a15094536fe38344ab2c. The performances before and after the PR are nearly the same, and still off from the commit before #37091.

**Comment by robieta** [comment]
I have a theory about why. `nn` layers use `Parameter`, rather than `Tensor`, so they take the slow path to check.

```
import torch
from torch.utils.benchmark import Timer

x = torch.ones((1, 1))
weights = {
    "Tensor weight": torch.ones((1, 1)),
    "Parameter weight": torch.nn.Linear(1, 1).weight,
}

for label, weight in weights.items():
    timer = Timer(
        "torch.nn.functional.linear(x, weight)",
        globals={"x": x, "weight": weight},
        label=label,
    )
    print(timer.blocked_autorange(min_run_time=2), "\n")
```

```
<torch.utils.benchmark.utils.common.Measurement object at 0x7f409d4a5150>
Tensor weight
  Median: 6.37 us
  IQR:    0.25 us (6.27 to 6.51)
  306 measurements, 1000 runs per measurement, 1 thread

<torch.utils.benchmark.utils.common.Measurement object at 0x7f40b469a690>
Parameter weight
  Median: 12.42 us
  IQR:    0.48 us (12.19 to 12.68)
  157 measurements, 1000 runs per measurement, 1 thread
```

**Comment by ezyang** [comment]
@robieta ding ding ding, that sounds super plausible to me.

We actually did talk about this in code review: https://github.com/pytorch/pytorch/pull/37091#discussion_r433799872 but maybe the fast path didn't actually work.

**Comment by hameerabbasi** [comment]
Confirmed, working on fixing this in a PR now.

**Comment by hameerabbasi** [comment]
Sorry, false alarm. Fast path works for `Parameter` but not `UninitializedParameter` (which inherits from it), which does define `__torch_function__` (and is called in `test/test_nn.py`).

I just printed out something in `_disabled_torch_function_impl` to see if it was ever being called, I assumed it wouldn't ever be, but `UninitializedParameter` calls `super().__torch_function__` (so it is called).

**Comment by ezyang** [comment]
UninitializedParameter should only be relevant for LazyModules, I don't think that's being used here?

**Comment by ngimel** [comment]
Definitely not.

**Comment by robieta** [comment]
FYI the stack of https://github.com/pytorch/pytorch/pull/48966 should do a better job (as it also handles `Parameter`) if you want to give that a shot.

**Comment by xwang233** [comment]
@robieta Thanks for the fix. I've tested the head of #48966 PR at 6287057c90a5a0450a0bfd2e0c1d0fbe8fa02b23. The performance of resnet is well restored. I hope to see that PR gets merged soon.

**Comment by robieta** [comment]
> @robieta Thanks for the fix. I've tested the head of #48966 PR at [6287057](https://github.com/pytorch/pytorch/commit/6287057c90a5a0450a0bfd2e0c1d0fbe8fa02b23). The performance of resnet is well restored. I hope to see that PR gets merged soon.

Awesome! Yeah, it should go in shortly.

**Comment by robieta** [comment]
Closing since that stack has been merged. Thanks for the report and for testing!
