### ISSUE TITLE
[online docs] anchors to source code are missing

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#48760]
## 📚 Documentation

Anchors to the source code seem to have disappeared. For example:

1. Go to https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.eval
2. Click [Source] on the right, which sends you to:

https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.eval

and this anchor doesn't exist

I don't see any anchors in the HTML:
```
<span class="k">def</span> <span class="nf">eval</span><span class="p">(</span><span class="bp">self</span><span class="p">:</span> <span class="n">T</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">T</span><span class="p">:</span>
        <span class="sa">r</span><span class="sd">&quot;&quot;&quot;Sets the module in evaluation mode.</span>
```

in 1.6.0 the ` id="Module.eval"` exists:
```
<div class="viewcode-block" id="Module.eval"><a class="viewcode-back" href="../../../../generated/torch.nn.Module.html#torch.nn.Module.eval">[docs]</a>    <span class="k">def</span> <span class="nf">eval</span><span class="p">(</span><span class="bp">self</span><span class="p">:</span> <span class="n">T</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">T</span><span class="p">:</span>
        <span class="sa">r</span><span class="sd">&quot;&quot;&quot;Sets the module in evaluation mode.</span>
```

so a bunch of important html was dropped recently it seems.

Thanks.

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
cc @brianjo, too

**Comment by brianjo** [comment]
Thanks for the report. I think we tracked down the issue. I should have a fix in today.

**Comment by brianjo** [comment]
Just landed a PR that should fix this. Please feel free to reopen an @ me if there are continued issues. Thanks!
