### ISSUE TITLE
BoxedKernelWrapper triggers MSVC bug in internal Windows build

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#48763]
Steps to reproduce: patch in https://github.com/pytorch/pytorch/pull/48718/commits/ac563715716a0778410dc8444e55c338a3bf961c most relevant segment is

```
REGISTER_OPERATOR_FUNCTOR(aten::add, aten_add, [](Node* n) -> SROperator {
  // TODO: Introduce TypedKernelFunction to make this more type safe
  auto op = c10::Dispatcher::singleton().findSchemaOrThrow("aten::add", "out");
  const auto& kernel = c10::Dispatcher::singleton().getKernel(op, c10::DispatchKey::CPU);
  return [op, &kernel](const ProcessedNode* p_node, std::vector<IValue>& reg) {
    auto in0_t = p_node->Input(0, reg).toTensor();
    auto in1_t = p_node->Input(1, reg).toTensor();
    auto in2_s = p_node->Input(2, reg).toScalar();
    if (p_node->Output(0, reg).isNone()) {
      p_node->Output(0, reg) = create_empty_from(in0_t);
    }
    auto out_t = p_node->Output(0, reg).toTensor();
    out_t.resize_({0});
    kernel.call<at::Tensor &, at::Tensor &, const at::Tensor &, const at::Tensor &, at::Scalar>(op, out_t, in0_t, in1_t, in2_s);
  };
});
```

Run build-arvr-diff-windows job (FB internal). Triggers this error:

```

command: [C:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\buck-out\gen\arvr\tools\buck\cl_tmp_override\cl_tmp_override, C:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\third-party\toolchains\vs2017_15.9\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe, @\\?\C:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\buck-out\bin\xplat\caffe2\torch_lib_ovrsource#compile-ops.cpp.obj311570ba,default\ppandcompile.argsfile]

stderr: c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\impl\boxing.h(152): error C2066: cast to function type is illegal
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(47): note: see reference to class template instantiation 'c10::impl::BoxedKernelWrapper<Return (at::Tensor &,const at::Tensor &,const at::Tensor &,c10::Scalar),void>' being compiled
        with
        [
            Return=at::Tensor &
        ]
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\torch\csrc\jit\runtime\static\ops.cpp(63): note: see reference to function template instantiation 'Return &c10::KernelFunction::call<at::Tensor&,at::Tensor&,const at::Tensor&,const at::Tensor&,c10::Scalar>(const c10::OperatorHandle &,at::Tensor &,const at::Tensor &,const at::Tensor &,c10::Scalar) const' being compiled
        with
        [
            Return=at::Tensor &
        ]
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\jit_type.h(2205): note: see reference to class template instantiation 'c10::ArrayRef<c10::IValue>' being compiled
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\c10\core\memoryformat.h(56): note: see reference to class template instantiation 'c10::ArrayRef<int64_t>' being compiled
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\c10\core\dispatchkeyset.h(57): note: see reference to class template instantiation 'std::initializer_list<c10::DispatchKey>' being compiled
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\impl\boxing.h(152): error C2070: 'FuncType': illegal sizeof operand
        with
        [
            FuncType=at::Tensor &(at::Tensor &,const at::Tensor &,const at::Tensor &,c10::Scalar)
        ]
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\impl\boxing.h(152): error C2338: Function signature contains one or more unsupported parameter and/or return types. Look for a nearby error like "'call' is not a member of 'c10::impl::BoxedKernelWrapper<(your function type), void>'" - (your function type) is the unsupported signature.
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(61): error C2039: 'call': is not a member of 'c10::impl::BoxedKernelWrapper<Return (at::Tensor &,const at::Tensor &,const at::Tensor &,c10::Scalar),void>'
        with
        [
            Return=at::Tensor &
        ]
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(61): note: see declaration of 'c10::impl::BoxedKernelWrapper<Return (at::Tensor &,const at::Tensor &,const at::Tensor &,c10::Scalar),void>'
        with
        [
            Return=at::Tensor &
        ]
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(47): error C2672: 'c10::KernelFunction::call': no matching overloaded function found
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(47): error C2783: 'Return c10::KernelFunction::call(const c10::OperatorHandle &,Args...) const': could not deduce template argument for 'Return'
c:\cygwin\data\sandcastle\boxes\trunk-hg-ovrsource-null\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction.h(99): note: see declaration of 'c10::KernelFunction::call'
    When running <c++ preprocess_and_compile>.
    When building rule //xplat/caffe2:torch_lib_ovrsource#compile-ops.cpp.obj311570ba,default..Rule 
```

Open source Windows MSVC does not seem to have any problems. Internal build appears to be running MSVC 15.9.12 (for reference, our standard OSS Windows build is MSVC 19.27.29112.0)

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by ezyang** [comment]
cc @bhosmer @smessmer

**Comment by bhosmer** [comment]
No time to dig rn but a couple quick notes:
1. The immediate cause of both errors in the snippet (152) is `static_assert(sizeof(FuncType) != sizeof(FuncType)`, which is there only to generate additional error content when none of the valid specializations have triggered. 
2. Most likely this means that fixing the immediate cause of the error (e.g. by just doing away with the helpful static assert) will leave us with a second problem, the one that brought us to this specialization in the first place: none of the specializing templates have recognized this signature. 
3. ...although there's some small chance that what we're seeing is a combination of a) the Windows compiler evaluating the static assert even though that template wouldn't be chosen, and b) at the time of evaluation, `sizeof(FuncType)` triggers the error. If so, removing the static assert should fix the problem.
4. Assuming 3 isn't the case, the immediate question is: why is the new code failing to find a specialization when the old code, for the same signature, succeeded? AFAICT the only difference is the new code's use of `kernel.call<...>` in generated code, with concrete types, whereas previously the invocation would I think have come from [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/dispatch/Dispatcher.h#L349):
```
  return kernel.template call<Return, Args...>(op, std::forward<Args>(args)...);
```


Tentative plan: 
1. remove static assert
2. the answer is #3, live with the lack of extra error content and we're done
2. otherwise, examine the error uncovered by removing the static assert, look for clues about what's being perturbed by the change in callsite, ask the internet, push template arcana around, question life choices

**Comment by ezyang** [comment]
@bhosmer To adjust priority: I'm ditching the implementation strategy that lead to this problem, so it is not urgent to fix. Since I patched out the problem in my PR, I've adjusted the description above to point to the specific intermediate commit that had this comment.

I don't think the error has to do with the static assert, because we ought to have compiled the same call (with same template arguments) in Functions.cpp. My guess is that the problem is related to the lambda capture, as it is kind of unusual. Also, we know that it is an MSVC bug, because it no longer fails on recent versions of MSVC.

**Comment by ezyang** [comment]
I do think it's worth durably recording this problem because we DO need to support this internal Windows build, so we have to make sure we avoid this compiler bug.

**Comment by malfet** [comment]
Grabbing for myself as I'm working on another Windows related regression in https://github.com/pytorch/pytorch/issues/48517

**Comment by bhosmer** [comment]
@ezyang yeah, definitely an MSVC bug. We've already upgraded our way past similar problems, it appears to (have) be(en) a soft spot :)

It's almost certainly true that the static assert is just a cascading error - and yeah agree, lambda capture would be one of the first things to push around if we were trying to find a workaround. But happy if we don't need to for your stuff :)

**Comment by ezyang** [comment]
This happened again

```
d:\ovrsource-null-hg\xplat\caffe2\aten\src\aten\core\boxing\impl\boxing.h(152): error C2066: cast to function type is illegal
d:\ovrsource-null-hg\xplat\caffe2\aten\src\aten\core\boxing\kernelfunction_impl.h(61): note: see reference to class template instantiation 'c10::impl::BoxedKernelWrapper<Return (const at::Tensor &,at::TensorList),void>' being compiled
        with
        [
            Return=at::Tensor
        ]
```
