### ISSUE TITLE
`arange` incorrect behavior above 2^24

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#4877]
Looks like it's just incrementing mantissa and saturates at 2^24.

```
In [14]: torch.arange(1,50000000)[-5:]
Out[14]:

 1.6777e+07
 1.6777e+07
 1.6777e+07
 1.6777e+07
 1.6777e+07
[torch.FloatTensor of size 5]
```

Shouldn't `arange` be returning `LongTensor` if the increment is an int? Numpy seems to get this right.

```
In [16]: np.arange(1,50000000).dtype
Out[16]: dtype('int64')

In [17]: np.arange(1,50000000)[-5:]
Out[17]: array([49999995, 49999996, 49999997, 49999998, 49999999])
```

**Comment by apaszke** [comment]
I'd say that magically changing the type depending on the arguments is weird and could break a lot of our code (unless we add implicit type casts to all operations).

**Comment by adamlerer** [comment]
Yeah, it's pretty weird, but that's what numpy does. They probably went through this same process.

Any other suggestions? The current behavior is clearly broken.

**Comment by adamlerer** [comment]
(At the very very least you should iterate up to float(50000000), and also error out if abs(max)/step > FLOAT_EPS/2  and same with min.)

**Comment by apaszke** [comment]
It's possible, but numpy does implicit casting of all args (e.g. `x + y` where `x` is `np.long` and `y` is `np.float32` is valid).

**Comment by gchanan** [comment]
we should at least add a dtype argument so you can be explicit about what you want (and we can not break existing code).

**Comment by adamlerer** [comment]
Yeah, I think adding dtype argument (or allowing torch.LongTensor().arange(...) ) , plus giving the "correct" behavior for float (not saturating at 2^24) would be the right solution if you don't want to return a dynamic type.

It's unfortunate that this diverges from numpy and gives very unexpected behavior in the "common" case (step=1), when max > 2^24 (which is not even that large). I remember we used to run into this landmine all the time back in torch7 when nn.LookupTable used to take FloatTensor.

**Comment by apaszke** [comment]
+1 for dtype

**Comment by arogozhnikov** [comment]
`dtype` was implemented (and in 'int32' provided example works just fine), this issue may be closed
