### ISSUE TITLE
How can I find a function to calculate correlation coefficient matrix like numpy.corrcoef ()  in pytorch?

### ISSUE THREAD

**Issue by jiangzhiwei2018** [pytorch/pytorch#48770]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by heitorschueroff** [comment]
Closing this issue. Please, post your question in our discussion forum.
