### ISSUE TITLE
[libtorch] tensor.to(torch::Device(torch::kCPU)) is VERY SLOW

### ISSUE THREAD

**Issue by raisinglc** [pytorch/pytorch#48779]
ENV:
libtorch (1.7.0) cuda 10.1
windows 10
vs 2017
Memory: 16G
GPU Memory : 2G
GPU: 850m (it's old.)

I am working on developing with libtorch, but the execution time is very long for a single inference (400 ms). My model ist a backbone of resnet34 with some head architecture. I print out the execution time. 

method: 
<time.h>   
clock() 

WARMING UP:
pre-process(on CPU) + sent input to GPU: 30 ms
forward propagation(on GPU) : ~1800 ms -> 160 ms -> 10 ms
sent tensor back to CPU: 1ms -> ~200 ms.
post-process(on): 1 ms.

AFTER WARMUP:
pre-process(on CPU) + sent input to GPU: ~30 ms.
forward propagation(on GPU) : 20 ms.
sent tensor back to CPU: ~200 ms.
post-process(on): 1 ms.

Inputs: 1 x 704 x 1280 x 3
output: 1 x 21 x 40 x 1

The transmission from GPU to CPU dominates the execution time.

How do I improve its performance? What is the reason resulting in this problem?

 My guess:
(1) My timing method is not safe for this kind of parallel process? but I put them in the main for loop.
(2) the threads weren't synchronized, so the processing of fetching this 21 x 40 tensor is distributed to a wide range of pipeline?

cc @ngimel @VitalyFedyunin

**Comment by heitorschueroff** [comment]
Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.

**Comment by GuoxingYan** [comment]
i have the same problem.
[https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py](url)
82 line 
pred = as_numpy(pred.squeeze(0).cpu())
.cpu()is very slow

**Comment by GuoxingYan** [comment]
> Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.

i have the same problem.
https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py
82 line
pred = as_numpy(pred.squeeze(0).cpu())
.cpu()is very slow

**Comment by raisinglc** [comment]
> > Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.
> 
> i have the same problem.
> https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py
> 82 line
> pred = as_numpy(pred.squeeze(0).cpu())
> .cpu()is very slow

**Comment by raisinglc** [comment]
> > Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.
> 
> i have the same problem.
> https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py
> 82 line
> pred = as_numpy(pred.squeeze(0).cpu())
> .cpu()is very slow

Hi, I have solved the problem .I think the problem should be synchronization of CUDA.we should count after call to cpu. SOrry , I close the issue, by mistake.

**Comment by raisinglc03** [comment]
> Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.

Hi, heitorschueroff. Sorry for late reply. I wanted to double check the influence of environment. I tested my code on another machine with a 1080ti with both windows and Ubuntu, and I synchronized each steps. My code worked as I expected.

**Comment by raisinglc03** [comment]
> > > Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.
> > 
> > 
> > i have the same problem.
> > https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py
> > 82 line
> > pred = as_numpy(pred.squeeze(0).cpu())
> > .cpu()is very slow
> 
> Hi, I have solved the problem .I think the problem should be synchronization of CUDA.we should count after call to cpu. SOrry , I close the issue, by mistake.



> i have the same problem.
> [https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/test.py](url)
> 82 line
> pred = as_numpy(pred.squeeze(0).cpu())
> .cpu()is very slow

How did you measure the execution time? Did you put time() before and after the line82? When we activate the gpu mode, cuda might make some of the instructions of next step to cover the bubbles of current steps, so your measurements might not just the actual execution time of line 82. Personally, I think you can try to put synchronize in your code or measure the whole steps of each step of inference.

**Comment by heitorschueroff** [comment]
> > Hi @raisinglc, it would be very helpful if you could post a script of your test. One possibility that comes to mind is that your measurement for the forward propagation is not synchronizing the CUDA device so when you move the data back to the CPU you have to wait for the computation for finish first.
> 
> Hi, heitorschueroff. Sorry for late reply. I wanted to double check the influence of environment. I tested my code on another machine with a 1080ti with both windows and Ubuntu, and I synchronized each steps. My code worked as I expected.

By "worked as expected" do you mean that you saw the same results with the code running very slow?
