### ISSUE TITLE
[NNC]  let `tensorexpr::Dtype::scalar_type`  use `c10::ScalarType`

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#48784]
**Problem description**

`Dtype::scalar_type` currently is defined as `tensorexpr::ScalarType`
```
// Switch to PT/Aten dtypes
enum class ScalarType : int8_t {
#define DEFINE_ENUM(_1, n) n,
  AT_FORALL_SCALAR_TYPES_WITH_COMPLEX_AND_QINTS(DEFINE_ENUM)
#undef DEFINE_ENUM
  // Undefined must be next to match c10::ScalarType;
  Undefined,
  Handle,
  Uninitialized,
  None,
  NumOptions
};
```

Since `c10::ScalarType` defines more utility functions than `tensorexpr::ScalarType`, some times one needs to explicitly do `static_cast<c10::ScalarType>(...)`. @bertmaher suggested to replace make `tensorexpr::Dtype::scalar_type` to use `c10::ScalarType` directly (see the discussion [here](https://github.com/pytorch/pytorch/pull/48679#discussion_r533924983).

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by ZolotukhinM** [comment]
Fixed by #56825.
