### ISSUE TITLE
Accumulate absolute value of gradients instead of signed value

### ISSUE THREAD

**Issue by JakobHavtorn** [pytorch/pytorch#4880]
When you call backward on an output unit of a network which contains the outputs of an entire batch, pytorch computes the sum of _signed_ gradients of these outputs wrt. network weights.

Is there currently any way to accumulate the _absolute_ values of these gradients instead of the _signed_ values?

The only way I can think of is to call backward on every single observation in a for loop and manually set 
```
param.grad.data = param.grad.data.abs()
```
This is however, horribly slow (as could be imagined)

**Comment by apaszke** [comment]
No, this is impossible using reverse-mode AD that PyTorch implements. In general I don't think it's possible to compute these absolute gradients more efficiently than to repeat the procedure for every output.
