### ISSUE TITLE
Improve torch.distributed.new_group() documentation in the context of SyncBatchNorm 

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#48804]
## 📚 Documentation

In current documentation for using subgroups other than the whole world in SyncBatchNorm: https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm.convert_sync_batchnorm, it is not clear that when creating subgroups, every rank still needs to make the call regardless of whether they are in the group or not, as per the docs in https://pytorch.org/docs/master/distributed.html#torch.distributed.new_group. 

For example, if we have ranks [0-7] and want to create 2 subgroups and sync BN stats across 2 groups separately, we should do:

```
module = MyModule()
r1 = [0, 1, 2, 3]
r2 = [4, 5, 6, 7]
process_groups = [torch.distributed.new_group(pids) for pids in [r1, r2]]
pg_for_rank = process_groups[0 if self.rank <= 3 else 1]
sync_bn_module = torch.nn.SyncBatchNorm.convert_sync_batchnorm(module, pg_for_rank)
```

Note that in this example, every rank calls into `new_group()` for all groups being created, but we pass in the specific process group for that rank into `convert_sync_batchnorm`. 

cc @jlin27 @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by pritamdamania87** [comment]
> it is not clear that when creating subgroups, every rank still needs to make the call regardless of whether they are in the group or not, as per the docs in https://pytorch.org/docs/master/distributed.html#torch.distributed.new_group.

Don't the docs already mention this:

> This function requires that all processes in the main group (i.e. all processes that are part of the distributed job) enter this function, even if they are not going to be members of the group. Additionally, groups should be created in the same order in all processes.

**Comment by rohan-varma** [comment]
> > it is not clear that when creating subgroups, every rank still needs to make the call regardless of whether they are in the group or not, as per the docs in https://pytorch.org/docs/master/distributed.html#torch.distributed.new_group.
> 
> Don't the docs already mention this:
> 
> > This function requires that all processes in the main group (i.e. all processes that are part of the distributed job) enter this function, even if they are not going to be members of the group. Additionally, groups should be created in the same order in all processes.

I meant the docs/example in sync_batchnorm itself: https://pytorch.org/docs/stable/generated/torch.nn.SyncBatchNorm.html#torch.nn.SyncBatchNorm.convert_sync_batchnorm, where the example doesn't really show that very clearly.
