### ISSUE TITLE
normal distribution torch.exp(log_prob(x)) return a probability  > 1

### ISSUE THREAD

**Issue by iimmer** [pytorch/pytorch#48818]
why a normal distribution  return a  probability > 1 sometimes ? 

>>> dist = Normal(0,0.3)
>>> c = dist.sample()
>>> c
tensor(-0.1572)
>>> torch.exp(dist.log_prob(c))
tensor(1.1591)

Why the probability greater then 1? 
Did I miss something?

**Comment by SsnL** [comment]
this is a continuous distribution. density can be larger than 1
