### ISSUE TITLE
error: a member of type "const c10::Symbol" cannot have an in-class initializer on Windows

### ISSUE THREAD

**Issue by datumbox** [pytorch/pytorch#48835]
## 🐛 Bug

PR #48717 replaced `constexpr` with `CONSTEXPR_EXCEPT_WIN_CUDA` to resolve some of the problems on CUDA+Windows for TorchVision as discussed at pytorch/vision#3051. Unfortunately we continue having issues:
```
C:/Users/circleci/project/env/lib/site-packages/torch/include\torch/csrc/jit/ir/ir.h(1329): error: a member of type "const c10::Symbol" cannot have an in-class initializer

C:/Users/circleci/project/env/lib/site-packages/torch/include\torch/csrc/jit/ir/ir.h(1349): error: a member of type "const c10::Symbol" cannot have an in-class initializer
```

I believe we need to move the initialization outside of the class on the following two places:
https://github.com/pytorch/pytorch/blob/0484b048d050ea5b10cb0efd147148aa893f2a4b/torch/csrc/jit/ir/ir.h#L1329
https://github.com/pytorch/pytorch/blob/0484b048d050ea5b10cb0efd147148aa893f2a4b/torch/csrc/jit/ir/ir.h#L1349

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @ezyang

**Comment by pbelevich** [comment]
Experiencing the same issue in [torchcsprng](https://app.circleci.com/pipelines/github/pytorch/csprng/688/workflows/4b2f7f7b-7ab5-4546-b1d4-41ddb84f016f/jobs/30439)
