### ISSUE TITLE
Enable linear algebra functions on ROCm platform

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#48831]
## 🚀 Feature
PyTorch shipping with linear algebra functionality on AMD GPUs via the [hipMAGMA](https://icl.utk.edu/magma/software/browse.html?start=0&per=5) library. The ability to run the same code that uses linalg functions on Nvidia and AMD GPUs.

## Motivation

Dense linear algebra is used in many applications of scientific computing. In the High-Performance Computing world, AMD is gaining popularity with the announcements that the future world's fastest supercomputers will be based on AMD GPUs for example [Frontier and El Capitan](https://www.amd.com/en/products/exascale-era), [Finnish LUMI](https://www.lumi-supercomputer.eu/may-we-introduce-lumi/) and probably some others. This will bring many researchers using PyTorch + ROCm.

## Pitch

Currently, most of the linear algebra functionality in PyTorch relies on the MAGMA library, which is linked only in CUDA build.
For ROCm build, it's possible to link to hipMAGMA (a version of MAGMA that was processed with hipify script) and with minimal changes to the existing code all the linear algebra functions that call MAGMA will work for AMD GPUs as well.

`magma-hip` would need to be added to [pytorch/builder](https://github.com/pytorch/builder/tree/master/magma).
Some changes in code would need to be made so that only magma v2 API  `magma_v2.h` is used (maybe v1 works fine as well, but it includes only `cublas.h` by default, while v2 seems to work with `hipblas.h`.
And a few changes to CMake config files to enable searching and linking of MAGMA in ROCm build path.

## Alternatives

AMD develops its variant of Nvidia's cuSOLVER, called [rocSOLVER](https://github.com/ROCmSoftwarePlatform/rocSOLVER). So the alternative option would be to use rocSOLVER as the underlying library for linear algebra functionality.

## Additional context

I have compiled hipMAGMA myself for AMD Vega 20 (gfx906) and managed to link it with PyTorch so that SVD runs fine on AMD GPUs. I didn't test other functions.

cc @malfet @seemethere @walterddr @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @jeffdaily @sunway513 @stomov

**Comment by jeffdaily** [comment]
We are actively working on this known deficiency.  One sticking point is how to package hipMAGMA.  CUDA MAGMA is installed in the PyTorch CI images using conda packages, but we do not have hipMAGMA conda packages.  We could build it from source as needed, but we would prefer a package option.

It sounds like you've done quite a bit of work already to integrate hipMAGMA?  Do you have notes or code or a PR to share?

**Comment by IvanYashchuk** [comment]
Here are notes for installing hipMAGMA + PyTorch ROCm.
First, OpenBLAS (or MKL), ROCm libraries, hipBLAS need to be installed.
OpenBLAS steps:
```bash
git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
make
make install PREFIX=your_preferred_installation_directory # default is /opt/OpenBLAS
```
hipBLAS steps (if not installed together with other ROCm libraries):
```bash
git clone https://github.com/ROCmSoftwarePlatform/hipBLAS.git
cd hipBLAS
mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=your_preferred_installation_directory ..
make
make install
```
Add paths to lib of hipBLAS and OpenBLAS to LD_LIBRARY_PATH variable.

hipMAGMA steps (I use the latest development branch merge-master-hipMAGMA from bitbucket commit 202e59f, there is also a release version hipMAGMA v2.0.0 https://icl.utk.edu/magma/software/browse.html?start=0&per=5):
There are build instructions in README.hipMAGMA file.
```bash
git clone --single-branch --branch merge-master-hipMAGMA https://bitbucket.org/icl/magma.git
cd magma
cp make.inc-examples/make.inc.hip_openblas make.inc # or cp make.inc-examples/make.inc.hip-mkl-gcc make.inc
# check whether on lines 125 and 158 in make.inc paths are correct particularly for hipBLAS, modify if necessary
# add CXXFLAGS += -DHAVE_hipBLAS in make.inc after line 104
# Export environment variables OPENBLASDIR, HIPDIR
export OPENBLASDIR=...
export HIPDIR=/opt/rocm-3.9.0/hip
# export GPU_TARGET variable
export GPU_TARGET=gfx906
# hipify magma source files by
make -f make.gen.hipMAGMA
# change line 28 of interface_hip/error.h to "#if defined(HAVE_hipBLAS) || defined(HAVE_HIP)"
# now we can actually build magma shared library by
make lib -j8
```
Make sure that the compiled library works with
```bash
make testing/testing_dgemm
./testing/testing_dgemm
```
We have now hipMAGMA's shared library in `magma/lib/libmagma.so` .

Now let's compile PyTorch (tested for `17f53bff`)
```bash
git clone --recursive https://github.com/pytorch/pytorch.git
# apply patch to aten/src/ATen/CMakeLists.txt
curl https://gist.githubusercontent.com/IvanYashchuk/c94b76b8d745abf347dc9956edc8b4c7/raw/32f30b7118fdf72658cadb8398bdda808ca81ffc/aten_cmake.patch | git apply -v
# appy patch to cmake/Dependencies.cmake
curl https://gist.githubusercontent.com/IvanYashchuk/c94b76b8d745abf347dc9956edc8b4c7/raw/6c1b04d28c224b9a07bc1974b7573235a4710fa5/cmake_dep.patch | git apply -v
# export MAGMA_HOME to point to magma directory
# export ROCM_PATH to point to rocm directory
# run hipify on pytorch source
python tools/amd_build/build_amd.py
# use magma v2
# modify magma/include/magma.h to have content of magma/include/magma_v2.h and add "#define HAVE_HIP"
# modify aten/src/ATen/native/hip/MiscUtils.h line 36 "magma_queue_create_from_cuda" -> "magma_queue_create_from_hip"
# replace aten/src/ATen/native/hip/BatchLinearAlgebra.hip with https://gist.githubusercontent.com/IvanYashchuk/c94b76b8d745abf347dc9956edc8b4c7/raw/6535fb3cfde1faf5528ecf41c40a3bcc72dadca3/BatchLinearAlgebra.hip
# it fixes some problems with triangular solve when MAGMA v2 is used (for MAGMA v1 I was getting undefined symbols error related to this function, that's why v2 is needed)
# now compile pytorch
PYTORCH_ROCM_ARCH=gfx906 USE_MAGMA=1 USE_NVCC=0 USE_CUDA=0 python setup.py develop
```
Now it should be possible to run the following
```python
In [1]: import torch
In [2]: torch.cuda.get_device_name(torch.cuda.current_device())
Out[2]: 'Vega 20'
In [3]: a = torch.randn(3, 3, device='cuda')
In [4]: a.svd()
Out[4]: 
torch.return_types.svd(
U=tensor([[-0.7192,  0.2058, -0.6636],
        [ 0.5469, -0.4214, -0.7234],
        [-0.4285, -0.8832,  0.1905]], device='cuda:0'),
S=tensor([1.8222, 1.4176, 1.0698], device='cuda:0'),
V=tensor([[-0.9001,  0.2685,  0.3431],
        [ 0.4192,  0.3199,  0.8497],
        [-0.1184, -0.9086,  0.4005]], device='cuda:0'))
In [5]: a.to('cpu').svd()
Out[5]: 
torch.return_types.svd(
U=tensor([[-0.9128, -0.0288,  0.4074],
        [ 0.3589, -0.5324,  0.7666],
        [ 0.1948,  0.8460,  0.4964]]),
S=tensor([2.4678, 1.9275, 0.0943]),
V=tensor([[-0.9383, -0.3217,  0.1272],
        [-0.1289,  0.6664,  0.7344],
        [-0.3210,  0.6727, -0.6667]]))
```
Many tests in `test/test_linalg.py` fail for now.

**Comment by t-vi** [comment]
Regarding how to distribute magma: Debian has recently added a (CUDA) [magma package](https://packages.debian.org/source/sid/magma) thanks to @cdluminate . That could serve as a blueprint for a HIP magma Debian package.

**Comment by cdluminate** [comment]
FYI the debian packaging repo for magma can be found here https://salsa.debian.org/science-team/magma

**Comment by t-vi** [comment]
> Some changes in code would need to be made so that only magma v2 API magma_v2.h is used (maybe v1 works fine as well, but it includes only cublas.h by default, while v2 seems to work with hipblas.h.

In #49978 I try to change the magma includes to magma_v2.h.

**Comment by jeffdaily** [comment]
PR submitted.

**Comment by IvanYashchuk** [comment]
Unit tests for ROCm in `test/test_linalg.py` were enabled in https://github.com/pytorch/pytorch/pull/58232.
