### ISSUE TITLE
[NNC] Handle `half` type in the backend instead of when converting to IntrinsicsOps

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#48864]
## Issue description

To support half types in kernel functions, it is currently done in in `kernel.cpp` when we convert from `aten::xxx` node to `Intrinsics` node, e.g.,

```
    case aten::frac: {
      return computeOneOperand(
          "aten_frac",
          v,
          [](const ExprHandle& a) {
            auto aa = promoteHalfToFloat(a);
            return aa - floor(aa);
          },
          kFloatingPointTypes);
    } break;
```

Current implementation implies that `kFloor` does not support `half` natively. This could be inefficient for platforms w/ native `half` support (e.g., accelerators and gpus).

This feature would add `half` as valid input to PyTorch IR (i.e., `kXXX` intrinsic). For platforms that do not have native 'half' support, the codegen backend will promote `half` to `float` then perform the operation in `float`. 

@eellison pointed out that the LLVM codegen backend has already followed this approach (see [halfRewriter](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/llvm_codegen.cpp#L317)). 

cc @VitalyFedyunin @ngimel @gmagogsfm

**Comment by bertmaher** [comment]
#64147 should take care of this!
