### ISSUE TITLE
Checking the hw.optional.arm64 sysctl prevents Apple Silicon from building a universal binary

### ISSUE THREAD

**Issue by lunixbochs** [pytorch/pytorch#48874]
This check https://github.com/pytorch/pytorch/blob/e7ca62be08f96b07efc1271baf9b02d4e7be226a/cmake/Modules/FindARM.cmake#L44-L45 prevents an Apple Silicon Mac from building an x86_64 variant of Pytorch.

I'm sure the check exists because folks are installing CMake as an x86_64 binary from homebrew, so they want to use it to pick a different architecture from the CMake architecture, however this is how I got here:

I built and installed both CMake and ninja as Universal 2 binaries.
I built Python 3.9.1rc1 as x86_64 using `arch -x86_64`  before the Python configure/make commands.

When I run this x86_64 Python, it runs the x86_64 CMake binary, which is actually correct in this case (unlike the case where you only have an x86_64 CMake binary, so arm64 processes drop to x86_64 and you need the sysctl).

With `CMAKE_SYSTEM_PROCESSOR=x86_64 CMAKE_OSX_ARCHITECTURES=x86_64 python3.9 setup.py build` and a small fix to CMake itself (upstream issue here https://gitlab.kitware.com/cmake/cmake/-/issues/21554), I am able to convince Pytorch to build as x86_64 on this machine.

However, it breaks partway through the build due to the NEON definitions that are enabled by the issue I'm describing here.

If I remove the sysctl check in FindARM, an x86_64 build completes successfully on an M1, which I was able to manually `lipo` to make a fully universal2 pytorch package.

cc @malfet @seemethere @walterddr

**Comment by walterddr** [comment]
cc @janeyx99

**Comment by malfet** [comment]
Hmm, let me try to amend the build definition here
