### ISSUE TITLE
aarch64 CMake checks are incorrect on Apple Silicon

### ISSUE THREAD

**Issue by lunixbochs** [pytorch/pytorch#48873]
Pytorch's CMakeLists.txt files have several checks for `CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64"` that don't take into account the fact that `CMAKE_SYSTEM_PROCESSOR` can be `arm64` on Apple Silicon (or `arm64e` for Pointer Authentication).

As of 6ab84ca0f3458924e79f0279521a8b5720d3a9e3, here are the CMake checks I found that seem to include `aarch64` but not `arm64`:

```
CMakeLists.txt:681
CMakeLists.txt:698
cmake/External/nnpack.cmake:30
cmake/Modules_CUDA_fix/upstream/FindCUDA.cmake:722
third_party/NNPACK/CMakeLists.txt:54
third_party/NNPACK/CMakeLists.txt:88
third_party/QNNPACK/CMakeLists.txt:40
third_party/cpuinfo/CMakeLists.txt:513
third_party/cpuinfo/CMakeLists.txt:762
third_party/cpuinfo/CMakeLists.txt:810
third_party/fbgemm/third_party/cpuinfo/CMakeLists.txt:163
third_party/fbgemm/third_party/cpuinfo/CMakeLists.txt:501
third_party/fbgemm/third_party/cpuinfo/CMakeLists.txt:70
third_party/fbgemm/third_party/cpuinfo/CMakeLists.txt:750
third_party/fbgemm/third_party/cpuinfo/CMakeLists.txt:798
third_party/sleef/Configure.cmake:463
third_party/sleef/src/libm-tester/CMakeLists.txt:35
third_party/sleef/travis/toolchain-aarch64.cmake:3
```

I think this at minimum breaks the NNPACK build checks.

cc @malfet @seemethere @walterddr

**Comment by seemethere** [comment]
cc @janeyx99

**Comment by walterddr** [comment]
looks like some of the places is suppose to be enabled. but i am not sure we are currently supporting NNPACK (e.g. the line in cmake/externalnnpack.cmake:30) explicitly disables set(USE_NNPACK OFF) when it is arm64.

**Comment by walterddr** [comment]
sorry for the late reply.

I just double check and looks like most of the submodules are updated to latest commit that supports `arm64`. The only exception I found was fbgemm & NNPACK, QNNPACK - and preparing a PR to upgrade those.

if you have compilation error points to any dependency other than the above 3 please share more details.

**Comment by malfet** [comment]
Please note, that no updates will be submitted to QNNPACK as it is an archive repository. None of the PyTorch operators depend on `third_party/QNNPACK`, only some legacy caffe2 ops.
