### ISSUE TITLE
sparse * dense variable ops don't work

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#4887]
reported at: https://discuss.pytorch.org/t/can-we-do-sparse-x-dense-dense-on-gpu/12901/3

ops like `torch.mm` work for sparse * dense tensors, but not variables. It looks like the code for sparse * dense ops isn't being generated at all from Declarations.cwrap. dense * sparse ops are okay.

```
import torch
from torch.autograd import Variable
i = torch.LongTensor([[0, 1, 1],
                      [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])
x = Variable(torch.sparse.FloatTensor(i, v, torch.Size([2,3])))
y = Variable(x.data.to_dense().t())
x.mm(y)

RuntimeError: Expected object of type Variable[torch.sparse.FloatTensor] but
found type Variable[torch.FloatTensor] for argument #1 'mat2'
```

**Comment by adamklec** [comment]
@zou3519 Why was this closed? Has there been any progress on implementing `sparse * dense` multiplication for variables?

**Comment by GaiYu0** [comment]
With PyTorch 0.4.0,

`th.sparse.FloatTensor(3, 3) * th.zeros(3, 3)`

gives

`RuntimeError: Expected object of type torch.sparse.FloatTensor but found type torch.FloatTensor for argument #2 'other'`

**Comment by zou3519** [comment]
@adamklec @GaiYu0  we don't have hadamard product between sparse and dense variables. I was referring to matrix multiplication. I believe there's another issue out there about that feature request.

**Comment by adamklec** [comment]
Ah. Thanks @zou3519 !
