### ISSUE TITLE
PyTorch has many hide bug

### ISSUE THREAD

**Issue by zs963048949** [pytorch/pytorch#48882]
My task is medical image segmentation， binary classification.
When I make the code for a normal and basic running，I had met a lot of abnormal phenomenon.The main reason is abnormal dice(segmentation accuracy).However，I have not received any error message.I try to find the question，but I meet more problem.I think my code don't have a large problem.The main problem came in dataset loader.There were many odd problem in here.Even,I have fixed a little code，and I received an abnormal Dice.I nearly lost my heart.I have not list the concrete code or bug，because it has many problem.Oh my god.

**Comment by mauricett** [comment]
Can you try to provide some actual code examples? That would be very helpful.

**Comment by ailzhang** [comment]
Hi @zs963048949 please use the issue template to report bugs and provide a repro script. Thanks!
