### ISSUE TITLE
Avoid initializing gradInput twice in the backward phase of replication_pad

### ISSUE THREAD

**Issue by Jokeren** [pytorch/pytorch#48889]
## 🚀 Feature
Avoid initializing gradInput twice in the backward phase of `replication_pad3d`, `replication_pad2d, and `replication_pad1d`

## Motivation

https://github.com/pytorch/pytorch/blob/251398acca732fcdf78c194328ff9ede8adb56d1/aten/src/ATen/native/cuda/ReplicationPadding.cu#L894

https://github.com/pytorch/pytorch/blob/251398acca732fcdf78c194328ff9ede8adb56d1/aten/src/ATen/native/cuda/ReplicationPadding.cu#L798

https://github.com/pytorch/pytorch/blob/251398acca732fcdf78c194328ff9ede8adb56d1/aten/src/ATen/native/cuda/ReplicationPadding.cu#L846

Line 894 zeros gradInput, which will be zeroed out again at Line 726.

Line 846 zeros gradInput, which will be zeroed out again at Line 480.

Line 798 zeros gradInput, which will be zeroed out again at Line 318.

## Pitch

Avoid reinitializing the gradInput array.

https://github.com/pytorch/pytorch/pull/48890

## Benchmark

https://github.com/Jokeren/pytorch-fixes/blob/main/2-replication-pad3d.py

This unit test illustrates ~14% performance improvement on a V100 GPU.  I am not aware of any existing large model that frequently uses replicationPad though.

cc @VitalyFedyunin @ngimel

**Comment by ngimel** [comment]
Thanks for reporting @Jokeren, we'll accept a PR fixing this.

**Comment by Jokeren** [comment]
@ngimel Thanks. May I know what open source models you are using to measure the performance of pytorch? Currently, I am using resnet, gcn, and unet. I would like to test some language models. However, the transformer framework seems using tensorflow internally, at least for BERT.

**Comment by ngimel** [comment]
Models are listed here https://github.com/pytorch/benchmark/tree/master/torchbenchmark/models, I don't think many of them use ReplicationPad though.

**Comment by Jokeren** [comment]
@ngimel, Thanks for the link! I am not referring to this specific fix. We plan to use our performance tools to profile more examples and check if we can find performance problems.
