### ISSUE TITLE
Compile error in Windows SDK

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#48895]
## Bug

Failed to compile on Windows recently.
Sounds like a preprocess related error, since there's no `/` or `{` there.

Screenshot. `oaidl.h` is in the background.
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/5203025/101267521-920dd680-3794-11eb-8765-bc1a0943dccd.png">

Build options:
https://github.com/xkszltl/Roaster/blob/b603b4ae05089cfb02c0c3f3c748f6c87c7e9b67/win/pkgs/pytorch.ps1#L114-L165

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Win Server 2019
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+msvc 2019 16.8.2
 - Python version: 3.9
 - CUDA/cuDNN version: 11.1

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
That's weird. The `10.0.16299.0` is from Windows 1709. I don't think that VS 16.8.2 (Build Tools 14.28) is compatible with a Windows SDK that old.

**Comment by xkszltl** [comment]
Official installation:
<img width="653" alt="image" src="https://user-images.githubusercontent.com/5203025/101468804-dc52ab80-397e-11eb-98ed-d4b6a39f1307.png">

**Comment by skyline75489** [comment]
Yeah I know it can be installed, but it does not mean that the latest build tools is for sure compatible with all the available versions. Maybe @peterjc123  knows more about this.

**Comment by xkszltl** [comment]
FYI we don't use latest WinSDK because we want a "global setting" for oldest targeting OS, rather than defining all those `*WINVER*` macros everywhere. Also let me know if you happen to have suggestion about this practice.

**Comment by skyline75489** [comment]
Was the build working before upgrading to VS 2019 16.8? What's the configuration of last successful build?

And by the way, does adding `-DNOMINMAX` and `-DWIN32_LEAN_AND_MEAN` help?

**Comment by xkszltl** [comment]
We probably built 1 month ago with 16.7, but also a earlier version of pytorch master, and that worked.
Never tried current master + 16.7.

I'll have a try with `WIN32_LEAN_AND_MEAN` and latest win sdk.

**Comment by xkszltl** [comment]
BTW we've built many libraries with VS 16.8 + WDK 16299, pytorch is the only one failing.

**Comment by peterjc123** [comment]
As far as I know. `-DWIN32_LEAN_AND_MEAN` and `-DNOMINMAX` is already a part of the public compiler options for all the targets related to `torch`.

**Comment by peterjc123** [comment]
I will try to reproduce it first. It might take some time.

**Comment by mszhanyi** [comment]
If it worked before, I suggest you could try `python setup.py clean` first, then run `python setup.py install --cmake`

**Comment by xkszltl** [comment]
@peterjc123 
Additional `WIN32_LEAN_AND_MEAN` to `CMAKE_C{,XX}_FLAGS` seems to help.
I tried it once and stuck with another protobuf 3.14/nvcc issue (https://github.com/protocolbuffers/protobuf/issues/8128) so I guess it passed that part.

@mszhanyi 
We call cmake directly, with fresh clone everytime.

**Comment by peterjc123** [comment]
@xkszltl 
We are already adding the macro definitions globally. I don't know why it doesn't work.
https://github.com/pytorch/pytorch/blob/master/cmake/MiscCheck.cmake#L289 https://github.com/pytorch/pytorch/blob/master/cmake/Dependencies.cmake#L1502

**Comment by peterjc123** [comment]
Well, I think I know the reason. It is too late to add them in the `Dependencies.cmake` in L1502.

**Comment by peterjc123** [comment]
@xkszltl Could you please test whether #49025 fixes your problem?

**Comment by xkszltl** [comment]
I just tried the latest (19041) WinSDK as well, without `WIN32_LEAN_AND_MEAN`, and it works....
Only 16299 fails (double confirmed with rebuild after 19041 build).

**Comment by xkszltl** [comment]
> @xkszltl Could you please test whether #49025 fixes your problem?

Thanks!
Will do.

In the mean time you can probably start the merge of that, very likely it works.
You may also want to check whether it is correctly set when using pytorch/caffe2's cmake config file in downstream.

However, it is better to guard individual `#include` as well, if you can repro with 16299.
Source code them self are only "correct" if you `#define` it there, rather than relying on build args.

**Comment by peterjc123** [comment]
@xkszltl pthreadpool isn't our code. And we already cleaned up the imports in our code with https://github.com/pytorch/pytorch/pull/48009.

**Comment by xkszltl** [comment]
@peterjc123 
Thanks for pointing that out.
Issue forwarded to upstream as well: https://github.com/Maratyszcza/pthreadpool/issues/11

**Comment by xkszltl** [comment]
@peterjc123 You PR works.
