### ISSUE TITLE
Weight normalization causes layer to not move to GPU

### ISSUE THREAD

**Issue by sidmani** [pytorch/pytorch#48898]
## 🐛 Bug

A linear layer in a torch.nn.Module does not move to the GPU if `torch.nn.utils.weight_norm` is applied, and the layer is not called in the forward function using the standard `__call__` function.

## To Reproduce

This works:
```
import torch

def linear_inplace(layer, v):
    return torch.addmm(layer.bias, v, layer.weight.t(), out=v)

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = torch.nn.ModuleList([
            torch.nn.Linear(16, 16)
        ])

        for i in range(len(self.layers)):
            self.layers[i] = torch.nn.utils.weight_norm(self.layers[i])

    def forward(self, x):
        layer = self.layers[0]
        return layer(x)
        # return linear_inplace(layer, x)

device = torch.device('cuda')

m = Model().to(device)
input = torch.ones(5, 16, device=device)

with torch.no_grad():
    print(m(input))
```
but replacing the layer(x) with linear_inplace(layer, x) throws the following error:
```
  File "temp.py", line 18, in forward
    return linear_inplace(layer, x)
  File "temp.py", line 4, in linear_inplace
    return torch.addmm(layer.bias, v, layer.weight.t(), out=v)
RuntimeError: Tensor for argument #3 'mat2' is on CPU, but expected it to be on GPU (while checking arguments for addmm)
```

## Expected behavior
Since to(device) is called, all the layers should be on the GPU.

## Environment

Collecting environment information...
PyTorch version: 1.7.0+cu110
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3080
Nvidia driver version: 455.45.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-memlab==0.2.3
[pip3] torch==1.7.0+cu110
[pip3] torchvision==0.8.1+cu110
[conda] Could not collect

## Additional context
The purpose of the linear_inplace function is to save GPU memory during a forward pass with autograd disabled. I think the contents of that function are not related to the error, however.

**Comment by sidmani** [comment]
I guess it's the consequence of this line in torch.nn.utils.weight_norm:
```
        # remove w from parameter list
        del module._parameters[name]
```
which removes the weight matrix from the parameter list, and then it's not transferred to the GPU. How can I make the linear_inplace function work properly while respecting the weight norm operation?

**Comment by SsnL** [comment]
Even if you fix it somehow, your `linear_inplace` won't be weight-normalized.

**Comment by sidmani** [comment]
@SsnL I see that now. I can re-implement weight_norm to also be in-place. Do you think the memory savings will be worth it? I am running thousands of passes of the network with no_grad() as part of the training of a 3D point representation network.

**Comment by SsnL** [comment]
I can't comment on that, but it is not a difficult implementation and you can copy-paste most of the code. You do need to be careful to make sure that backward still works (i.e., you are not overwriting variables needed for backprop). I would suggest implementing as a custom nn.Module rather than a "hack" like in your original post. Then you can measure the memory usage in your usecase for your dataset on your system.

**Comment by sidmani** [comment]
Great, thank you. I appreciate the help.
