### ISSUE TITLE
Implement Segment Reduction in pytorch

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#48904]
## 🚀 Feature
Implement a function similar to C2 LengthSum in pytorch, currently for the workloads that need it it is inefficiently implemented by calling c2 wrapper. Description:
```

    """
    Aggregates the first dimension of a tensor by individual segments of
    specified length.

    Category: Length Conversion

    Call Args:
        data(BlobRefenence|Tensor): A tensor to be aggregated
        lengths(BlobReference|Tensor): A 1D tensor of lengths.

    Returns:
        output(BlobReference|Tensor): A tensor with first dimension len(lengths)
        where the ith row in the first dimension is the sum of the ith segment.

    Example:
        >>> import numpy as np
        >>> import dper3.modules as modules
        >>> from dper3.core.environment import Caffe2EagerEnv, DperEnv
        >>> from dper3.core.train_utils import as_blob, blob_to_numpy
        >>> Caffe2EagerEnv().enable()
        >>> data = as_blob(np.array([[1, 1], [2, 2], [3, 3], [4, 4]], dtype=np.float32))
        >>> lengths = as_blob(np.array([1, 1, 2], dtype=np.int32))
        >>> convert = modules.LengthsSum()
        >>> output = convert(data, lengths)
        >>> blob_to_numpy(output)
            array([[1, 1],
                   [2, 2],
                   [7, 7]], dtype=int32)
        >>> DperEnv.reset()
    """
```
pointer to c2 cuda implementation (not that SparseFused is `false` in template instantiation)
https://github.com/pytorch/pytorch/blob/e429d05015bfa878f2ae660a1e0dd96b51d743d5/caffe2/operators/segment_reduction_op_gpu.cu#L370-L503

Implementing it in the sufficiently generic way may be a lot of work, so just reimplementing c2 functionality is ok for now. We might want to slightly future proof it by allowing either `lengths` or `indices` argument, and also `axis` argument though for now it's ok to allow only `axis=0`. 
I propose the following API. I suggest make `lengths` a keyword-only argument so that if we decide to support either `indices` or `lengths` it does not have to be breaking. 
```
_segmented_sum(Tensor input, *, Tensor lengths, int axis=0, unsafe=False)

```
`unsafe` means that there are no checks that `lengths` argument contain valid values, which may be desired for performance reasons. 

This can be a first step towards implementing `reduceat` numpy functionality https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ufunc.reduceat.html

**Comment by sramakrishnan247** [comment]
@ngimel Hey, can I take this up?

**Comment by ngimel** [comment]
Hey @sramakrishnan247 this issue is already taken, but you can pick one of the functions from numpy functionality rollup #38349.
