### ISSUE TITLE
libtorch tensor in std::vector becomes undefined

### ISSUE THREAD

**Issue by hellkite500** [pytorch/pytorch#48958]
## 🐛 Bug

If you put a `torch::Tensor` in a `std::vector` the resulting tensor is `undefined`.

## To Reproduce

1. Create a `torch::Tensor` with some default values
2. Push the tensor into a `std::vector`
3. Access the tensor from the vector container

4. Here is a minimal example. Note the difference in output between accessing from the vector and directly printing the tensor.

```c++
#include <iostream>
#include <torch/torch.h>

int main(int argc, char** argv) {

    std::vector<torch::Tensor> out;

    out.resize(1);

    torch::Tensor t = torch::zeros( {1, 4}, torch::dtype(torch::kFloat64) );

    std::cout<<t<<"\n";

    out.push_back(t) ;

    std::cout<<out[0]<<"\n";

    return 0;
}
```
Produces the following output
```
 0  0  0  0
[ CPUDoubleType{1,4} ]
[ Tensor (undefined) ]
```
## Expected behavior

I expect the tensor to be defined just as it was before being added to the container, and the above output should instead be:
```
 0  0  0  0
[ CPUDoubleType{1,4} ]
 0  0  0  0
[ CPUDoubleType{1,4} ]
```

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[conda] Could not collect

 - Any other relevant information:
More imporantly, libtorch version 1.7.0+cu110

## Additional context
The CMakeLists.txt for the minimum reproducible example.
```cmake
cmake_minimum_required(VERSION 3.10)

project(min-bug-example VERSION 1.0.0)

# This sets the C++ version to C++17
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
# Import Torch C++ (this looks for the cmake-files is
# a number of paths including `/usr/local/share/cmake`
# where we installed it)
find_package(Torch REQUIRED)

# Make Target
add_executable(vec_tensor vec_tensor.cpp)

target_compile_options(vec_tensor PUBLIC -g)
# Link Torch C++ libs
target_link_libraries(vec_tensor "${TORCH_LIBRARIES}")
```

**Comment by SsnL** [comment]
>  out.resize(1);

you resized.... maybe you meant `reserve`?

**Comment by hellkite500** [comment]
Ah, indeed, `resize()` causes default, i.e. `undefined` elements to be constructed, and then `push_back()` pushes on the end of those.  That whole premature optimization thing may have gotten the better of me, thanks for pointing that out!
