### ISSUE TITLE
`test_variant_consistency_jit` for BFloat16 are skipped in a confusing way

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#48978]
In file https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py
There are lots of tests skipped using something like
```python
                       SkipInfo('TestCommon', 'test_variant_consistency_jit',
                                device_type='cuda', dtypes=[torch.bfloat16]),
```
The test `test_variant_consistency_jit` itself does not work, because `isfinite` is not supported on BF16. Even if all the operators used to implement the backward are working.

We should make this test work, and clean this file.

cc @mruberry @VitalyFedyunin @walterddr @gmagogsfm

**Comment by mruberry** [comment]
cc @Lilyjjo, too

**Comment by Lilyjjo** [comment]
Agreed, this is something that needs to be investigated. The test_variant_consistency_jit was rewritten by re-using the logic from test_jit.py's add_autograd_test. The previous test wasn't testing all of the dtypes, which was masking these failures

**Comment by Lilyjjo** [comment]
Just an update: it looks like bfloat16() is an unsupported PyTorch construct in TorchScript according to our documentation: https://pytorch.org/docs/master/jit_unsupported.html#jit-unsupported  

I'm not sure why this is the case. I'll keep on looking into it

**Comment by Lilyjjo** [comment]
A way to make the code cleaner would just to skip bfloat16 for all of the JIT test cases instead of screening them out on the OpInfo level

**Comment by imaginary-person** [comment]
> A way to make the code cleaner would just to skip bfloat16 for all of the JIT test cases instead of screening them out on the OpInfo level

@mruberry & @Lilyjjo:

Hello, I'm a new contributor & am trying to implement `pow()` on CPU for dtypes `float16` & `bfloat16`. I encountered 3 failures, one of which is related to `test_variant_consistency_jit_linalg_norm_cpu_bfloat16`.

I just finished reading up the testing wiki to check how I can retest specific test-cases locally & haven't looked at the root cause of the failures yet, but upon going through this discussion, I was wondering if I should not look into failures pertaining to `test_variant_consistency_jit_linalg_norm_cpu_bfloat16`. Thanks in advance for your advice!

**Comment by mruberry** [comment]
@imaginary-person you can skip them for now to unblock development. It's a little tricky to comment on whether the skips will ultimately be appropriate until I look at the PR, however. Would you add me as a reviewer?

**Comment by imaginary-person** [comment]
Hello @mruberry, thank you for your response! 

I'm unable to assign a reviewer for [my pull request](https://github.com/pytorch/pytorch/pull/50999/).
I think non-member contributors no longer see the option of assigning reviewers.

**Comment by mruberry** [comment]
> Hello @mruberry, thank you for your response!
> 
> I'm unable to assign a reviewer for [my pull request](https://github.com/pytorch/pytorch/pull/50999/).
> I think non-member contributors no longer see the option of assigning reviewers.

Cool. I added myself.

**Comment by Lilyjjo** [comment]
I'm looking into cleaning up the bfloat16 tests for test_variant_consistency_jit, and I'm having some confusion on if bfloat16 should be running on CPUs. I see a lot of `dtypesIfCPU=all_types_and(torch.float16, torch.bfloat16, torch.bool)` and my understanding of bfloat16 is that it only runs on certain GPUs, would it make sense to remove bfloat16 from CPU dtype testing all together?

**Comment by imaginary-person** [comment]
In the current codebase, `BFloat16` has more AVX2 vectorization support on CPU than `Float16`, so I think there must've been a rationale behind it, which is why I think `BFloat16` dtype testing shouldn't be skipped on CPU.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/53255 should address this issue by limiting the test matrix.

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/53255 has mooted this issue.
