### ISSUE TITLE
Profiling distributed NCCL collectives deadlocks when profiler run with use_cuda=True

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#48987]
## 🐛 Bug

We recently enabled profiling of distributed collectives with this PR: https://github.com/pytorch/pytorch/pull/46471. However, when we run the profiler with `use_cuda=True` and the NCCL backend for distributed collective operations, there is a deadlock and the test eventually fails with a timeout. 

The deadlock is caused by a `cudaEventCreate` (called in the profiler here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_cuda.cpp#L38) on a device, which attempts to initialize a CUDA context on the device, that causes a wait for all NCCL kernels (and other operations) to exit. However, a separate process has launched a NCCL kernel on the device, and the NCCL kernel is blocked (specifically in `ncclBarrierEnqueueWait`: https://github.com/NVIDIA/nccl/blob/920dbe5b359fe5817b8ba874476ca4ba2dc5f1ef/src/group.cc#L322) waiting for the other rank to call it as well (which it never does). This deadlock can be seen in these stacktraces:
https://gist.github.com/rohan-varma/45f407a1fd7015d1a6d4f5d797ad4734

At a high level, the sequence that results in the deadlock is the following (can be seen in the stacktraces as well):
- Process 1 calls `enableProfilerLegacy()`, which in turn creates warm up and start events on each device: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_legacy.cpp#L518. Eventually, Process 1 exits this and enters the NCCL kernel launched by the collective.
- The NCCL kernels behave sort of like a barrier, the NCCL kernel cannot exit until all other ranks have called into the kernel as well. Thus, Process 1 blocks until Process 0 would enter its NCCL kernel
Process 0 calls `enableProfilerLegacy()`, which in turn creates events on each device similar to above. Eventually, `cudaCreateEvent` tries to create a cuda context on the device, which blocks until all operations on the device have finished. Since we do this for all devices, that means that device 1 would cause Process 0 to block since it would wait for the NCCL kernel on device 1 to finish. But it will never finish, since it is blocked waiting for Process 0 to call into it.

The main challenges in fixing the deadlock are:
- It's not sufficient to just synchronize every cuda device after `enableProfilerLegacy`. This is because In the above example, Process 1 could finish synchronizing all devices before Process 0 attempts to create the cuda events in `enableProfilerlegacy`. 
- Removing the `onEachDevice()` logic from profiler would result in CUDA events not being created for other devices in the profiler, which would likely break use cases for single-process that use multiple devices, since CUDA operations on those devices would no longer correctly be recorded.
- Since we need some way to sync processes after `enableProfilerLegacy`, we could have ProcessGroupNCCL do a one-time write to the store ensuring the profiler has been initialized properly, when we detect that we are profiling with CUDA. Although, this would incur a (one-time) wait in the distributed collective, which is not desirable from a perf perspective. 

## To Reproduce
- Re-enable distributed profiling tests by patching https://github.com/pytorch/pytorch/pull/48946.
- In `call_dist_op` in `distributed_test`, pass in `use_cuda=True` to the profiler. 
- Run a test which exercises the profiling path, such as `test_all_reduce_sum_cuda_async`. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by ilia-cher** [comment]
cc. @ngimel 
does the deadlock appear to be happening inside cudaEventCreate in one process and in NCCL kernel in another?
is that a KP or we should use cuda events / NCCL somehow differently?

**Comment by ilia-cher** [comment]
just to clarify - this doesn't seem profiler specific (profiler just creates a bunch of cuda events on the devices) and this deadlock is triggered in other scenarios - @rohan-varma to confirm

**Comment by ilia-cher** [comment]
would be good to loop in NCCL experts, from profiler side - we just issue cudaEventCreate, but that shouldn't cause issues

**Comment by rohan-varma** [comment]
Also cc'ing @lw as he ran into a similar deadlock (although I believe it was happening with `cudaStreamCreate` in that issue, but it should be similar since both calls initialize the CUDA context). 

@ilia-cher This is correct, it's not profiler specific, though it happens as a result of profiler creating events on each device, as we discussed, we can probably mitigate this by setting CUDA_VISIBLE_DEVICES properly.

**Comment by ngimel** [comment]
Update: profiler is initializing contexts on all the visible devices, it should not be doing that, @ilia-cher is going to send a fix soon. That should fix the bug. @rohan-varma there was a time when you could not have different CUDA_VISIBLE_DEVICES on the processes and still successfully use nccl, but maybe it's fixed (in nccl) now, I don't know.

**Comment by lw** [comment]
> profiler is initializing contexts on all the visible devices, it should not be doing that

@ngimel Is there some general guidance on this matter? I think we do plan to initialize all visible devices as part of the GPU support for RPC, looping in @mrshenli as he's working on it. We were also going to do such a thing in ProcessGroupNCCL but had to give up because of a deadlock similar to this one, although in principle we'd still like to do it. Thanks!

**Comment by ilia-cher** [comment]
we'll update the profiler code not to insert these events on all devices in the beginning of the profiling

**Comment by ngimel** [comment]
@lw can you please tell more about your intended workflow? Typically a single process controls a single GPU, and I though that should be the case for RPC also? Creating nccl process groups should not affect this (i.e. process 0 controlling gpu 0 can be in a group with process 4 controlling gpu 4, but it does not require process 0 initialize context on gpu4).

**Comment by lw** [comment]
@ngimel I'd rather have @mrshenli weigh in on this as he's designing that code and I wouldn't want to misrepresent it. In general, though, I think in RPC we also want to allow single-process multi-device mode. And we're certainly looking for ways to make both modes possible without "misbehaving" in either of them.

**Comment by rohan-varma** [comment]
Reopening for now, will close after adding a distributed profiling test verifying that this works.

**Comment by rohan-varma** [comment]
Fixed in 3b1e310
