### ISSUE TITLE
How to do polymorphism on torch::nn::ModuleHolder?

### ISSUE THREAD

**Issue by thisisi3** [pytorch/pytorch#48995]
The C++ frontend tutorial https://pytorch.org/tutorials/advanced/cpp_frontend.html recommends use ModuleHolder to create our own modules, but the inheritance relation does seem not translate to ModuleHolder. So I am wondering if there is a way to have both the benefit of ModuleHolder while having polymorphism among my customized modules.

cc @yf225 @glaringlee @albanD @mruberry

**Comment by mruberry** [comment]
This question may be more appropriate to the PyTorch forums, but cc @glaringlee just in case.

**Comment by glaringlee** [comment]
@thisisi3 
ModuleHolder itself has no polymorphism. This is just a wrapper to wrap your module implementation.
As what tutorial mentioned, when creating your own module. You still inherit from nn::Module, or if you need it clone-able, inherit from Cloneable<your_module_class_name>.

But we do recommend to use ModuleHolder to hold your module and you get lots of free functionalities. Here is what we do to wrap our module implementations with ModuleHolder:
https://github.com/pytorch/pytorch/blob/77cc7d1ecda30961b04caace0ee3ecdb3d695961/torch/csrc/api/include/torch/nn/pimpl.h#L197

Please create a question in the forum and post the link here if you need further help, we can discuss there.

**Comment by thisisi3** [comment]
@glaringlee 
Thanks for your reply.
I finally decide to use std::shared_ptr<M>, I will be losing the more natural constructor, but it is straight forward and it works.
