### ISSUE TITLE
RuntimeError: Exporting the operator var to ONNX opset version 10 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by TomatoBoy90** [pytorch/pytorch#49005]
cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@TomatoBoy90 - please add proper repro, error stack, and possibly details about which op is missing. Also, I would suggest trying the latest version of PyTorch and also `opset_version=12` to see if that helps.
