### ISSUE TITLE
Sorting Variables is very slow

### ISSUE THREAD

**Issue by jojonki** [pytorch/pytorch#4900]
I noticed sorting `Variable` is much slower than other sortings. Please find a reproducing code.
And it may be related to #2303 that has been already resolved.

- OS:Ubuntu 16.04.5
- PyTorch version: '0.4.0a0+040336f' (from source)
- How you installed PyTorch (conda, pip, source):
- Python version:3.6.3 (Anaconda)
- GCC version (if compiling from source):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

```
import time
import torch
from torch.autograd import Variable

N = 10000
d1 = Variable(torch.randn(10, N))
d2 = torch.randn(10, N)
d3 = d1.data.numpy()

start = time.time()
_ = [sorted(range(N), key=lambda k: d[k]) for d in d1]
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")

start = time.time()
_ = [sorted(range(N), key=lambda k: d[k]) for d in d2]
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")

start = time.time()
_ = [sorted(range(N), key=lambda k: d[k]) for d in d3]
elapsed_time = time.time() - start
print("elapsed_time:{0}".format(elapsed_time) + "[sec]")
```

Then, the result is here.
```
$ python bench.py  
elapsed_time:1.1007232666015625[sec]
elapsed_time:0.04404330253601074[sec]
elapsed_time:0.03660702705383301[sec]
```

And I tried this in pytorch 0.3 on MacBook, pytorch does not allow to sort Variables in this version.
```
$ python bench.py 
Traceback (most recent call last):
  File "bench.py", line 11, in <module>
    _ = [sorted(range(N), key=lambda k: d[k]) for d in d1]
  File "bench.py", line 11, in <listcomp>
    _ = [sorted(range(N), key=lambda k: d[k]) for d in d1]
  File "/Users/jonki/anaconda/lib/python3.6/site-packages/torch/autograd/variable.py", line 125, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.ByteTensor is ambiguous
```

**Comment by apaszke** [comment]
It's a lot slower because every indexing operation you're doing in here is recorded in a graph, because you might potentially want to differentiate it. This takes the majority of time. I'd recommend doing `var.sort(dim=1)`, which will be equally fast on Variables and Tensors, and much faster than using `sorted`.
