### ISSUE TITLE
If test suite triggers CUDA assert, should stop running tests

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#49019]
Every test after the CUDA assert will fail, but only the first test will be relevant. It would be more user friendly to immediately halt the test suite the first time a CUDA assert fails.

cc @ngimel @mruberry @VitalyFedyunin @walterddr

**Comment by walterddr** [comment]
qq: not sure if this solves the problem but can we add `failfast` option to the test runners that runs CUDA test cases?
would this work or should we create a custom test runner that specifically look into each test results and check the CUDA assert failures?

**Comment by ngimel** [comment]
wdym by `failfast` option? If it's aborting after any failure in cuda test, then no, that's not what's requested here. We want to abort only if one of context-invalidating (sticky) errors happened.

**Comment by walterddr** [comment]
oh. yeah I didn't realize Ed meant only sticky errors, thanks for the explanation @ngimel

**Comment by malfet** [comment]
Here is a small  example of sticky errors triggered by on-device assert:

```
#include <stdio.h>
#include <assert.h>

__global__ void assert_kernel() {
  assert (threadIdx.x % 5 != 4);
}

bool test_alloc() {
  void *gpu_vec = nullptr;

  return cudaMalloc(&gpu_vec, 11) == cudaSuccess;
}

bool test_assert() {
  assert_kernel<<<1, 6>>>();
  return cudaDeviceSynchronize() != cudaSuccess;
}

int main(int argc, const char*argv[]) {
  if (argc > 1) {
    printf("test_alloc() %s\n", test_alloc() ? "succeeded" : "failed");
    printf("test_assert() %s\n", test_assert() ? "succeeded" : "failed");
    return 0;
  }
  printf("test_assert() %s\n", test_assert() ? "succeeded" : "failed");
  printf("test_alloc() %s\n", test_alloc() ? "succeeded" : "failed");
  return 0;
}
```

**Comment by ngimel** [comment]
Another common sticky error is "Illegal memory access".
