### ISSUE TITLE
`torch.digamma`: Inconsistent with SciPy

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#49015]
```python
>>> import torch
>>> import scipy.special
>>> x = torch.tensor(-1931.99999994, dtype=torch.double)
>>> x.digamma()
tensor(-16666631.6273, dtype=torch.float64)
>>> scipy.special.digamma(x.numpy())
-16666645.861379756
```

Reference: https://github.com/pytorch/pytorch/pull/48302/files#r531985280

cc @ezyang @gchanan @zou3519 @bdhirsh @bhosmer @smessmer @ljk53 @ailzhang

**Comment by zhangguanheng66** [comment]
The difference is reasonably small to me. Feel free to remove the triage review tag.

**Comment by kshitij12345** [comment]
I think the difference of `14` is not small.

**Comment by zou3519** [comment]
float64 should give precision of 15-17 significant digits. A difference of 14 is pretty large in this case

**Comment by zou3519** [comment]
@albanD says if you touch the input by just a little (+/- 10), it becomes NaN

**Comment by iramazanli** [comment]
This got fixed in  https://github.com/pytorch/pytorch/pull/56689
