### ISSUE TITLE
invalid wheel no .dist-info | collect-env script not working

### ISSUE THREAD

**Issue by Escartem** [pytorch/pytorch#49010]
## To Reproduce

1. pip install torch

![image](https://user-images.githubusercontent.com/43405304/101472230-9bd83b00-3948-11eb-84ff-e77a6d5c073b.png)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

Result :
![image](https://user-images.githubusercontent.com/43405304/101472181-86fba780-3948-11eb-91d2-9724a8456d0b.png)

```
Collecting environment information...                                                                                   Traceback (most recent call last):                                                                                        File "collect_env.py", line 418, in <module>                                                                              main()                                                                                                                File "collect_env.py", line 413, in main                                                                                  output = get_pretty_env_info()                                                                                        File "collect_env.py", line 408, in get_pretty_env_info                                                                   return pretty_str(get_env_info())                                                                                     File "collect_env.py", line 301, in get_env_info                                                                          os=get_os(run_lambda),                                                                                                File "collect_env.py", line 208, in get_os                                                                                return get_windows_version(run_lambda)                                                                                File "collect_env.py", line 191, in get_windows_version                                                                   return run_and_read_all(run_lambda, '{} os get Caption | {} /v Caption'.format(wmic_cmd, findstr_cmd))                File "collect_env.py", line 54, in run_and_read_all                                                                       rc, out, _ = run_lambda(command)                                                                                      File "collect_env.py", line 47, in run                                                                                    output = raw_output.decode(enc)                                                                                       File "D:\DATA\python\lib\encodings\cp1252.py", line 15, in decode                                                         return codecs.charmap_decode(input,errors,decoding_table)                                                           UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 35: character maps to <undefined> 
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mariosasko** [comment]
Are you using Windows? If so, try `pip install torch==1.7.0 -f https://download.pytorch.org/whl/torch_stable.html`.

**Comment by Escartem** [comment]
Yes I'm using windows, I tried this command and now it's downloading, 2gb is quite big I think

**Comment by peterjc123** [comment]
> Yes I'm using windows, I tried this command and now it's downloading 2gb, it's quite big no ?

It is just that big. If you are from China, I guess you may use a proxy and Anaconda together with the tsinghua mirror.

**Comment by peterjc123** [comment]
> Result :

Actually, I'm more interested to the error in this picture. What locale are you using? What's the result of `python -c "import locale; print(locale.getpreferredencoding())"` and `wmic os get Caption` in CMD?

**Comment by Escartem** [comment]
I'm from France and here is the results of the two commands :
![image](https://user-images.githubusercontent.com/43405304/101492626-4bbba180-3965-11eb-93d6-97d59c44b0ce.png)
![image](https://user-images.githubusercontent.com/43405304/101492659-524a1900-3965-11eb-9b06-2e7bd06ab4ae.png)
I'm on my school computer btw

**Comment by Escartem** [comment]
And I can't download the file, it's too big, I tried 5 times but the wifi keeps shutting down and reset the download. I'll download it tonight.

**Comment by peterjc123** [comment]
@Escartem What is the result of `python -c "import sys; print(sys.stdout.encoding)"`?

**Comment by peterjc123** [comment]
@Escartem What is the result of `python -c "import sys; print(sys.stdo.encoding)"`

> And I can't download the file, it's too big, I tried 5 times but the wifi keeps shutting down and reset the download. I'll download it tonight.

You may try downloading https://download.pytorch.org/whl/cu102/torch-1.7.0-cp37-cp37m-win_amd64.whl using an external downloader.

**Comment by Escartem** [comment]
The result of "python -c "import sys; print(sys.stdout.encoding)" is ```utf-8```

And yeah I will try to download the file with an external program but I don't really know how to add package from wheelusing pip

**Comment by peterjc123** [comment]
`pip install [absolute/relative path to that file].`

**Comment by peterjc123** [comment]
> The result of `python -c "import sys; print(sys.stdout.encoding)` is `utf-8`

So what are the results of the following commands?
```
python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption']).decode('cp1252'))"
python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption']).decode('utf-8'))"
python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption']))"
```

**Comment by Escartem** [comment]
![image](https://user-images.githubusercontent.com/43405304/101494500-b837a000-3967-11eb-8b70-a141fc024fed.png)

**Comment by peterjc123** [comment]
`0x90` is an invalid character in `cp1252`, see https://en.wikipedia.org/wiki/Windows-1252. Well, would you please try this one instead? `python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption'], shell=True))"`

**Comment by Escartem** [comment]
![image](https://user-images.githubusercontent.com/43405304/101495800-43656580-3969-11eb-9bc1-d5f518ca1ec7.png)
Here it is

**Comment by peterjc123** [comment]
> Here it is

What about the following items?
```
python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption'], encoding='cp1252'))
python -c "import subprocess; print(subprocess.check_output(['wmic', 'os', 'get', 'Caption'], text=True))
chcp
```

**Comment by Escartem** [comment]
![image](https://user-images.githubusercontent.com/43405304/101496848-8e33ad00-396a-11eb-80ac-8f9d874eaf04.png)

**Comment by peterjc123** [comment]
LOL, the correct encoding is 850, but `locale.getpreferredencoding()` returns `cp1252`.

**Comment by mszhanyi** [comment]
@Escartem The windows CPU wheel on PyPI has some issues now. Please use conda to install python.
FYI. @seemethere

**Comment by Escartem** [comment]
@mszhanyi But I've managed to install pytorch using the steps above. Do I still need to do use conda ?

**Comment by peterjc123** [comment]
> @mszhanyi But I've managed to install pytorch using the steps above. Do I still need to do use conda ?

No, apparently not. He is saying PyPI, which you are not using.

**Comment by peterjc123** [comment]
@Escartem What result does the following command produce?
```
from ctypes import cdll
os_encoding = 'cp' + str(cdll.kernel32.GetACP())
print(os_encoding)
```

**Comment by Escartem** [comment]
![image](https://user-images.githubusercontent.com/43405304/101497782-9f30ee00-396b-11eb-8d1a-7203bb3ecb2c.png)

**Comment by peterjc123** [comment]
Would you please try this?
```
from ctypes import cdll
os_encoding = 'cp' + str(cdll.kernel32.GetOEMCP())
print(os_encoding)
```

**Comment by Escartem** [comment]
![image](https://user-images.githubusercontent.com/43405304/101498656-a3a9d680-396c-11eb-81a2-f920aff02c43.png)

**Comment by peterjc123** [comment]
OMG. Finally, we got a workground.

**Comment by Escartem** [comment]
So now the script will use the correct encoding and work ?

**Comment by peterjc123** [comment]
@Escartem I'm not sure when we should use `OEMCP` and when should we use `ACP`.

**Comment by Escartem** [comment]
If I understood correctly, we might try ACP and if it return an error then we try for OEMCP, no ?

**Comment by peterjc123** [comment]
But sometimes, using `ACP` won't throw an error even if the translation is wrong.

**Comment by peterjc123** [comment]
I googled a bit and found out that when we read from console, `OEMCP` is used as the default on Windows. I'll make the change.

**Comment by Escartem** [comment]
Yes but if the translation is wrong the result might look odd and we could be able to know it if OEMCP is the one to use

**Comment by peterjc123** [comment]
> Yes but if the translation is wrong the result might look odd and we could be able to know it if OEMCP is the one to use

There is no way we could tell whether the result looks odd programatically.

**Comment by peterjc123** [comment]
I'm going to use `OEMCP` as a default according to this [post](https://serverfault.com/a/836221).

**Comment by Escartem** [comment]
Okay, you can give me the updated script so I can test it and make sure everything is working

**Comment by peterjc123** [comment]
@Escartem https://raw.githubusercontent.com/pytorch/pytorch/36fba4a30211cccf579eca95f50a464e99d6aed1/torch/utils/collect_env.py

**Comment by Escartem** [comment]
The program seems to work now
![image](https://user-images.githubusercontent.com/43405304/101501983-b1615b00-3970-11eb-90bc-1ba4f3defa98.png)

**Comment by peterjc123** [comment]
@Escartem Thanks for the confirmation. Would you please click on `Approve` for #49020.

**Comment by Escartem** [comment]
I did it, but it is normal that most of the elements cannot be collected event pytorch version ?

**Comment by peterjc123** [comment]
@Escartem Have you installed those components? Oh, I see. You didn't install VS2019 Redist. Please install them according to the message.

**Comment by Escartem** [comment]
Unfortunately, I'm not an administrator on this computer and as far as I searched, I can't install it, I could try on my main computer tonight if you want

**Comment by peterjc123** [comment]
> Unfortunately, I'm not an administrator on this computer and as far as I searched, I can't install it, I could try on my main computer tonight if you want

It'll great if you could do that. The only thing that is wrong is that it fails to collect the gpu models and the driver versions. The corresponding commands are listed below. Do you have `nvidia-smi` installed?

**Comment by Escartem** [comment]
No I don't think so

**Comment by Escartem** [comment]
I'm now with my home computer I will download everything and test the script and give you the results

**Comment by seemethere** [comment]
We’re currently aware of this issue and working to resolve it, I’ll be spending some time today to try and debug what may have caused this

**Comment by Escartem** [comment]
@peterjc123 I've downloaded torch and ran the updated script, here is the result : 
![image](https://user-images.githubusercontent.com/43405304/101523238-9f8bb200-3988-11eb-8b33-cfd4879f7e2f.png)
is that good ?

**Comment by peterjc123** [comment]
@Escartem I simplied the fix. Would you please try this instead?https://raw.githubusercontent.com/pytorch/pytorch/647f3637b2571c9774452e5c807afe70ef5fc455/torch/utils/collect_env.py
BTW, the result looks good if you don't have a Nvidia GPU.

**Comment by Escartem** [comment]
here is the result : 
![image](https://user-images.githubusercontent.com/43405304/101525147-30fc2380-398b-11eb-8d43-8ddf7945fd84.png)

**Comment by peterjc123** [comment]
@Escartem Thanks. Looks like it is working.

**Comment by Escartem** [comment]
Can the issue be closed or do I need to wait for the pull to be merged ?

**Comment by peterjc123** [comment]
You don't need to do anything. We will handle that.

**Comment by Escartem** [comment]
Okay, thanks for helping me !

**Comment by peterjc123** [comment]
Keep it open until the PyPI one get resolved. @seemethere

**Comment by mszhanyi** [comment]
PyPI issue is resolved.
