### ISSUE TITLE
OpInfo-based testing for unsupported dtypes fails for general op.sample_inputs 

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#49024]
OpInfo-based test for unsupported dtypes fails when `op.sample_inputs(device, dtype)` doesn't work for the specified dtype.
See https://github.com/pytorch/pytorch/blob/master/test/test_ops.py#L31-L39 

The goal of this test is to verify that the function doesn't work on the given dtypes, but it shouldn't be required that OpInfo's `sample_input` function supports any dtype.

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
This has been fixed with the updated dtype tests.
