### ISSUE TITLE
Bug of torchtext.datasets.textclassification

### ISSUE THREAD

**Issue by Jensen-Wang** [pytorch/pytorch#49086]
## To Reproduce

In the function of `create_data_from_iterator` in the module `torchtext.datasets.textclassification` https://pytorch.org/text/stable/_modules/torchtext/datasets/text_classification.html

```python
def _create_data_from_iterator(vocab, iterator, include_unk):
    data = []
    labels = []
    with tqdm(unit_scale=0, unit='lines') as t:
        for cls, tokens in iterator:
            if include_unk:
                tokens = torch.tensor([vocab[token] for token in tokens])
            else:
                token_ids = list(filter(lambda x: x is not Vocab.UNK, [vocab[token]
                                        for token in tokens]))
                tokens = torch.tensor(token_ids)
            if len(tokens) == 0:
                logging.info('Row contains no tokens.')
            data.append((cls, tokens))
            labels.append(cls)
            t.update(1)
    return data, set(labels)
```

For the line, `token_ids = list(filter(lambda x: x is not Vocab.UNK, [vocab[token]
                                        for token in tokens]))`,  `Vocab.UNK ` is `<unk>` that is type of string. Lambda function in the filter directly acts on every term of list comprehension that is `vocab[token]` rather than `token`. The 'vocab[token]' has become index of the words in a sentence that is type of int. So the lambda function does not take effect because that the lambda condition expression in the filter is always right. The `str` type can never be equal to `int` type.  It does not make sense to use `is not` to judge the equality of address for `Vacab.UNK` and `token` here.  It should be changed to   
`token_ids = list(map(lambda x: vocab[x],list(filter(lambda x: x != Vocab.UNK,[token for token in tokens]))))`   
or more concisely  
`token_ids = [vocab[token] for token in tokens if token != Vocab.UNK]`.

Am I wrong or is this really a bug? Hope someone can make an explanation for me. Thank you!!!

**Comment by Jensen-Wang** [comment]
The source code is in https://pytorch.org/text/stable/_modules/torchtext/datasets/text_classification.html

**Comment by mariosasko** [comment]
Looks like you are right but I would suggest you opening this issue in the official [torchtext](https://github.com/pytorch/text) repo.

**Comment by H-Huang** [comment]
Yes, please file an issue in the [torchtext](https://github.com/pytorch/text) repo.
