### ISSUE TITLE
Confusing behavior of Tensor.contiguous() method.

### ISSUE THREAD

**Issue by SunnyDeer** [pytorch/pytorch#49085]
## 🐛 Bug

When I used the Tensor.contiguous() method, I find the behavior is quite confusing to me.

**Firstly**, I created a two-dimensional tensor call **_some_** with torch.tensor method.
**Next**, I created the transpose of it with dot-t method, called **_some_t_**.
**Then**, I created a contiguous tensor of the transpose, called **_some_t_c_**, since **_some_t_** is not a contiguous tensor.
I suppose, **_some_t_** and **_some_t_c_** are different in storage, however the python built-in method **_id_** shows they are identical in the memory. But, when I tried to manipulate one in the memory, the other didn't change in values, what irritating, the python built-in method **_id_** still shows they are identical in the memory, even they didn't contain same values.

## To Reproduce

	some = torch.tensor([[4, 1], [5, 3], [2, 1.]])
	some_t = some.t()
	some_t_c = some_t.contiguous()
    print(some_t.is_contiguous())
    print(some_t_c.is_contiguous())
	
	print(some_t.storage())
	print(some_t_c.storage())
	print(id(some_t.storage()) == id(some_t_c.storage()))
	
	some_t.storage()[0] = 100
	print(some_t)
	print(some_t_c)
	print(some)
	
	print(some_t.storage())
	print(some_t_c.storage())
	print(id(some_t.storage()) == id(some_t_c.storage()))
The printed contents are showed below:
False
True
 4.0, 1.0, 5.0, 3.0, 2.0, 1.0 [torch.FloatStorage of size 6]
 4.0, 5.0, 2.0, 1.0, 3.0, 1.0 [torch.FloatStorage of size 6]
True
tensor([[100.,   5.,   2.], [  1.,   3.,   1.]])
tensor([[4., 5., 2.], [1., 3., 1.]])
tensor([[100.,   1.], [  5.,   3.], [  2.,   1.]])
 100.0, 1.0, 5.0, 3.0, 2.0, 1.0 [torch.FloatStorage of size 6]
 4.0, 5.0, 2.0, 1.0, 3.0, 1.0 [torch.FloatStorage of size 6]
True

## Environment 

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): MacOS 11.0.1
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Python version: 3.8.5

**Comment by SsnL** [comment]
Python storage objects are created when you call `.storage()`. Hence the behavior you see. It is almost never a good idea to assume that `a.x()` gives a persistently living object. Furthermore, the storage id is just the python object's memory location and has nothing to do with the actual storage memory location ( you can think of it as a wrapper around a pointer to the actual storage data memory location). You can compare `x.storage().data_ptr()`.
