### ISSUE TITLE
torch.cuda.get_device_capability() is ludicrously expensive

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4908]
Running:

```
import torch
import time

for j in range(10):
  s = time.time()
  for i in range(10):
    torch.cuda.get_device_capability(torch.cuda.current_device())
  e = time.time()
  print((e-s)/10)
```

I get:

```
aten-rnn$ python bench-get-device-capability.py 
0.2659363985061646
0.0003546237945556641
0.000339508056640625
0.00035924911499023436
0.0004879951477050781
0.0003418445587158203
0.0003411054611206055
0.00034160614013671874
0.0006665945053100586
0.0003442287445068359
```

That's something like 350us a pop!

This matters. I noticed this behavior because I was benchmarking WLM, and when I commented out the test in `torch/backends/cudnn/__init__.py` the runtime shot down from 57.768s to 53.246s. We seem to call the RNN descriptor initialization twice per batch, and then another ~1200 times every time we do validation. The math works out:

```
>>> (2983*2 + 1200*2)*350
2928100
```

which is the correct order of magnitude change in runtime.

We should cache this. But maybe look at this more carefully after  #4881 lands, because the caching might need to be done in C++ land.

- OS: Linux [redacted] 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- PyTorch version: HEAD (2d829d15af98b5fde12d199456b9902dd0930b56)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.4
- CUDA/cuDNN version: CUDA 9.0, V9.0.176 / cuDNN 7.0.3 / Driver Version: 384.81
- GPU models and configuration: Quadro GP100
- GCC version (if compiling from source): gcc (GCC) 5.3.0

**Comment by ngimel** [comment]
Yep, because it's calling cudaGetDeviceProperties which is ludicrously expensive (don't ask) https://github.com/pytorch/pytorch/blob/d1c4065f0dec90ad7f90c65e24155fab445990ec/torch/csrc/cuda/Module.cpp#L144. THCState actually caches device capability, so THCPModule_getDeviceCapabilityWrap  should be calling something or other from THC, I don't know what exactly, that should be better.
