### ISSUE TITLE
RuntimeError: CUDA unknown error

### ISSUE THREAD

**Issue by Wei-Zhuo** [pytorch/pytorch#49081]
Help!
I install the CUDA and pytorch from official instruction, and run the 
```
python test_pytorch_cuda.py
```
but it returns:
```
Traceback (most recent call last):
  File "test_pytorch_cuda.py", line 4, in <module>
    dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
  File "/home/XXX/anaconda3/envs/Pt/lib/python3.6/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
```
and I do set the available devices in `~/.bashrc` as followed:
```
export CUDA_VISIBLE_DEVICES = 0
```
but this do not work.
What should I do?

pytorch version: 1.7.0
CUDA version: 11.0
GPU configuration: NVIDIA A100

**Comment by ptrblck** [comment]
Which NVIDIA driver version are you using? 
Did you update any drivers without a reboot?
Are all GPUs properly detected in `nvidia-smi`?

**Comment by Wei-Zhuo** [comment]
> Which NVIDIA driver version are you using?
> Did you update any drivers without a reboot?
> Are all GPUs properly detected in `nvidia-smi`?

I take your advice and reboot after Nvidia Driver installation, and it seems work !
After my last nvidia driver installation, I check `nvidia-smi` and it returns the normal table with right driver version I had installed, so I consider that it's a successful driver installation and the driver is in operation. And then I install CUDA-11.0 without reboot first.

**Comment by Wei-Zhuo** [comment]
Wish this will help to any researcher

uninstall old Nvidia Driver and CUDA --> install Nvidia Driver from `ubuntu-drivers devices` and `sudo ubuntu-drivers autoinstall` --> reboot and check `nvidia-smi` --> install CUDA from official instruction --> add path in profile --> check CUDA in 'cat /usr/local/cuda/version.txt' or `nvcc -V`

**Comment by Zinoex** [comment]
So I had the exact same problem except I didn't set `CUDA_VISIBLE_DEVICES = 0`. The problem for me was that my Manjaro distro bumped the kernel to Linux 5.9, which meant my Nvidia driver had to bump from version 430 to 450 as well. To solve the problem, I removed the 450 driver and installed the 455 driver through the Manjaro Hardware Detection (MHWD) library along with a reinstall of CUDA.

**Comment by Wei-Zhuo** [comment]
> I had the exact same problem except I didn't set `CUDA_VISIBLE_DEVICES = 0`. The problem for me was that my Manjaro distro bumped the kernel to Linux 5.9, which meant my Nvidia driver had to bump from version 430 to 450 as well. To solve the problem, I removed the 450 driver and installed the 455 driver through the Manjaro Hardware Detection (MHWD) library along with a reinstall of CUDA.
It seems mostly caused by wrong version of Nvidia Driver or CUDA. 
Thank u and I will update the flow chart.

**Comment by yurunsheng1** [comment]
apt-get install nvidia-modprobe

This works for me.

**Comment by HareshKarnan** [comment]
if you're using the lambda stack, doing a apt-get update followed by the apt-get install nvidia-modprobe solves this issue

**Comment by surya-narayanan** [comment]
Still getting this issue. 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/17240858/123174917-c0ec5100-d435-11eb-86c9-3ef0c756f7df.png">


----

<img width="562" alt="image" src="https://user-images.githubusercontent.com/17240858/123174828-9ef2ce80-d435-11eb-8d81-d85ecb218f7e.png">

---

<img width="378" alt="image" src="https://user-images.githubusercontent.com/17240858/123174852-a914cd00-d435-11eb-8d2f-bd1fdfcd1070.png">

---

<img width="575" alt="image" src="https://user-images.githubusercontent.com/17240858/123174876-b2059e80-d435-11eb-8a7b-bd70d65357c4.png">

**Comment by devvrit** [comment]
I'm facing similar issues. I have A100 GPUs on my machine, and the nvidia-driver version is 450.80.02. `nvidia-smi` works fine, and able to detect all GPUs
I had installed the required packages using the following command: `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

Have rebooted the machine as well. But still getting the same error upon `torch.cuda.is_available()`:
`/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370156314/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
False`

Can someone please advise what could be a possible solution to try? Thanks

**Comment by Wei-Zhuo** [comment]
> I'm facing similar issues. I have A100 GPUs on my machine, and the nvidia-driver version is 450.80.02. `nvidia-smi` works fine, and able to detect all GPUs
> I had installed the required packages using the following command: `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`
> 
> Have rebooted the machine as well. But still getting the same error upon `torch.cuda.is_available()`:
> `/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1607370156314/work/c10/cuda/CUDAFunctions.cpp:100.) return torch._C._cuda_getDeviceCount() > 0 False`
> 
> Can someone please advise what could be a possible solution to try? Thanks

Would u try this in terminal:
```
cd /usr/local/cuda-11.1/samples/1_Utilities/deviceQuery
make
sudo ./deviceQuery
```
and see what it return.
If u get the following response:
```
Result = Pass
```
then I think u install your cuda successfully, the problem may come from the installation of pytorch or env init.
( Maybe u forget to add path in ` ~/.bashrc` like this:
```
export CUDA_HOME=/usr/local/cuda-11.0/bin
export Path=/usr/local/cuda-11.0/bin
export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64

export CUDA_VISIBLE_DEVICES=0,1,2,3
```
in which `CUDA_VISIBLE_DEVICES` is the number of GPU devices u owns. I will use 4, so I set `export CUDA_VISIBLE_DEVICES=0,1,2,3`.

**Comment by devvrit** [comment]
> > I'm facing similar issues. I have A100 GPUs on my machine, and the nvidia-driver version is 450.80.02. `nvidia-smi` works fine, and able to detect all GPUs
> > I had installed the required packages using the following command: `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`
> > Have rebooted the machine as well. But still getting the same error upon `torch.cuda.is_available()`:
> > `/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1607370156314/work/c10/cuda/CUDAFunctions.cpp:100.) return torch._C._cuda_getDeviceCount() > 0 False`
> > Can someone please advise what could be a possible solution to try? Thanks
> 
> Would u try this in terminal:
> 
> ```
> cd /usr/local/cuda-11.1/samples/1_Utilities/deviceQuery
> make
> sudo ./deviceQuery
> ```
> 
> and see what it return.
> If u get the following response:
> 
> ```
> Result = Pass
> ```
> 
> then I think u install your cuda successfully, the problem may come from the installation of pytorch or env init.
> ( Maybe u forget to add path in ` ~/.bashrc` like this:
> 
> ```
> export CUDA_HOME=/usr/local/cuda-11.0/bin
> export Path=/usr/local/cuda-11.0/bin
> export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64
> 
> export CUDA_VISIBLE_DEVICES=0,1,2,3
> ```
> 
> in which `CUDA_VISIBLE_DEVICES` is the number of GPU devices u owns. I use 4 A100, so I set `export CUDA_VISIBLE_DEVICES=0,1,2,3`. )
> Hope this will help u.

Thanks for your reply. I figured out the issue. I'm using A100s on Debian 10 on GCP, and it seems for that we need a newer version of nvidia-driver for it. So I installed an updated driver and it works now.

Although a new issue has arised. Using nn.DataParallel is giving some errors. I'll raise this in another ticket perhaps

**Comment by johnson-magic** [comment]
Rebooting computer works for me.

**Comment by yiyi-today** [comment]
CUDA unknown error with large data volume. I also have this problem. Can run under small data volume, this problem occurs with large data volume. Can someone provide an answer? thank you!

**Comment by Wei-Zhuo** [comment]
> CUDA unknown error with large data volume. I also have this problem. Can run under small data volume, this problem occurs with large data volume. Can someone provide an answer? thank you!

Would u mind offer more error _info_ ?  ` CUDA unknown error ` can be caused by a lot of problems.

**Comment by yiyi-today** [comment]
Thank you for your attention, the error message is as follows. And the GPU memory viewed with 'nvidia-smi -l 1' is sufficient.
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    weights = torch.FloatTensor(train_dataset.weights).cuda()
  File "Anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

**Comment by yiyi-today** [comment]
> > CUDA unknown error with large data volume. I also have this problem. Can run under small data volume, this problem occurs with large data volume. Can someone provide an answer? thank you!
> 
> Would u mind offer more error _info_ ? `CUDA unknown error` can be caused by a lot of problems.

Thank you for your attention, the error message is as follows. And the GPU memory viewed with 'nvidia-smi -l 1' is sufficient.
Traceback (most recent call last):
File "train.py", line 260, in
weights = torch.FloatTensor(train_dataset.weights).cuda()
File "Anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/cuda/init.py", line 172, in _lazy_init
torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

**Comment by Wei-Zhuo** [comment]
> > > CUDA unknown error with large data volume. I also have this problem. Can run under small data volume, this problem occurs with large data volume. Can someone provide an answer? thank you!
> > 
> > 
> > Would u mind offer more error _info_ ? `CUDA unknown error` can be caused by a lot of problems.
> 
> Thank you for your attention, the error message is as follows. And the GPU memory viewed with 'nvidia-smi -l 1' is sufficient.
> Traceback (most recent call last):
> File "train.py", line 260, in
> weights = torch.FloatTensor(train_dataset.weights).cuda()
> File "Anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/cuda/init.py", line 172, in _lazy_init
> torch._C._cuda_init()
> RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

I get your_info_. It seems that you want to put your model into GPU, but you didn't set your GPU visible to CUDA (or do it in mistake). I am not pretty sure why this come from, because it greatly depends on your code and your configuration. I have the following two suggestions and hope they can be helpful: 
1. Maybe you should check this [https://github.com/pytorch/pytorch/issues/49081#issuecomment-885477721](url), especially the code `export CUDA_VISIBLE_DEVICES=0`, which specifies the GPU device id to be seen to CUDA in your python environment. 
2. If you set ~/.bashrc correctly, another fault could be that: you set your `device_ids`  without the value `0` in your Pytorch code. This can easily misleading that the value of `device_ids`  should be the same as `CUDA_VISIBLE_DEVICES`. However, the `CUDA_VISIBLE_DEVICES` specifies the GPU device in your python environment, but the `device_ids` specifies the GPU usage in your pytorch code. 

Let me set a example: 
I have 4 GPU devices, but I just want to GPU device `id=0` and `id=2` (get from `nvidia-smi`) to be seen to CUDA in this python environment, so I will add this into my `~/.bashrc`
```
export CUDA_VISIBLE_DEVICES=0,2
```
but in my pytorch code, I just want the GPU device `id=0` to used for deep learning, so I will set:
```
 model = torch.nn.DataParallel(model, device_ids=(0,) ).cuda()
```
or I want the GPU device `id=0` and `id=2` to used for deep learning, so I will set:
```
# the device_ids = 1 represents the can-be-seen GPU device id=1 in your this python environment, and it correspond to GPU device `id=2`
 model = torch.nn.DataParallel(model, device_ids=(0,1) ).cuda()
```
However, it's illegal to only use GPU device `id=2` to used like this:
```
 model = torch.nn.DataParallel(model, device_ids=(1,) ).cuda()
```
In pytorch, you should always set can-be-seen GPU device id=0 to be used, because the other can-be-seen GPU devices are only used for distributed computing.

**Comment by yiyi-today** [comment]
> > > > CUDA unknown error with large data volume. I also have this problem. Can run under small data volume, this problem occurs with large data volume. Can someone provide an answer? thank you!
> > > 
> > > 
> > > Would u mind offer more error _info_ ? `CUDA unknown error` can be caused by a lot of problems.
> > 
> > 
> > Thank you for your attention, the error message is as follows. And the GPU memory viewed with 'nvidia-smi -l 1' is sufficient.
> > Traceback (most recent call last):
> > File "train.py", line 260, in
> > weights = torch.FloatTensor(train_dataset.weights).cuda()
> > File "Anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/cuda/init.py", line 172, in _lazy_init
> > torch._C._cuda_init()
> > RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
> 
> I get your _info_. It seems that you want to put your model into GPU, but you didn't set your GPU visible to CUDA (or do it in mistake). I am not pretty sure why this come from, because it greatly depends on your code and your configuration. I have the following two suggestions and hope they can be helpful:
> 
>     1. Maybe you should check this [https://github.com/pytorch/pytorch/issues/49081#issuecomment-885477721](url), especially the code `export CUDA_VISIBLE_DEVICES=0`, which specifies the GPU device id to be seen to CUDA in your python environment.
> 
>     2. If you set ~/.bashrc correctly, another fault could be that: you set your `device_ids`  without the value `0` in your Pytorch code. This can easily misleading that the value of `device_ids`  should be the same as `CUDA_VISIBLE_DEVICES`. However, the `CUDA_VISIBLE_DEVICES` specifies the GPU device in your python environment, but the `device_ids` specifies the GPU usage in your pytorch code.
> 
> 
> Let me set an example:
> I have 4 GPU devices, but I just want to GPU device `id=0` and `id=2` (get from `nvidia-smi`) to be seen to CUDA in this python environment, so I will add this into my `~/.bashrc`
> 
> ```
> export CUDA_VISIBLE_DEVICES=0,2
> ```
> 
> but in my pytorch code, I just want the GPU device `id=0` to used for deep learning, so I will set:
> 
> ```
>  model = torch.nn.DataParallel(model, device_ids=(0,) ).cuda()
> ```
> 
> or I want the GPU device `id=0` and `id=2` to used for deep learning, so I will set:
> 
> ```
> # the device_ids = 1 represents the can-be-seen GPU device id=1 in your this python environment, and it correspond to GPU device `id=2`
>  model = torch.nn.DataParallel(model, device_ids=(0,1) ).cuda()
> ```
> 
> However, it's illegal to only use GPU device `id=2` to used like this:
> 
> ```
>  model = torch.nn.DataParallel(model, device_ids=(1,) ).cuda()
> ```
> 
> In pytorch, you should always set can-be-seen GPU device id=0 to be used, because the other can-be-seen GPU devices are only used for distributed computing.

First of all, I only have one GPU, and it can run normally with a small amount of data. I think my CUDA settings should be no problem. But when the amount of data is very large, an unknown error occurs when the parameters of the training data are placed on CUDA. I don't know why.
The error message is as follows,
IMPORTS OK
DEFINITIONS OK
UTILS OK
100%|██████████| 10000/10000 [01:40<00:00, 99.13it/s]
Traceback (most recent call last):
File "train.py", line 260, in
weights = torch.FloatTensor(train_dataset.weights).cuda()
File "Anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/cuda/init.py", line 172, in _lazy_init
torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

**Comment by AhmedHisham1** [comment]
I am having the same issue. This error happens after suspending/sleeping the machine and I have to reboot in order to fix it. I tried the above solutions but it wasn't fixed. [ubuntu 18.04]

**Comment by johnson-magic** [comment]
我已收到，。

**Comment by smj007** [comment]
Rebooting worked for me, but not the first time. The second reboot fixed the issue. (in case anyone gives up after a single reboot)

**Comment by bepcyc** [comment]
> I've recently ran into this error when migrating my gpu containers from nvidia docker to podman. The root cause for me was that `/dev/nvidia-uvm`, `/dev/nvidia-uvm-tools` files were missing that CUDA apparently needs to work. Check that you have them on both host and container/VM if you use containers. On the host, running `sudo nvidia-modprobe -c 0 -u` should fix it.

I've faced this issues when trying to continue working with pytorch session after suspend (in my case it's a Stable Diffusion web UI that keeps the session open). What also worked for me was:
`sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm`
which probably does the same thing as the above nvidia-modprobe command but should work on all distros.

**Comment by yuanjustin** [comment]
> > I'm facing similar issues. I have A100 GPUs on my machine, and the nvidia-driver version is 450.80.02. `nvidia-smi` works fine, and able to detect all GPUs
> > I had installed the required packages using the following command: `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`
> > Have rebooted the machine as well. But still getting the same error upon `torch.cuda.is_available()`:
> > `/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1607370156314/work/c10/cuda/CUDAFunctions.cpp:100.) return torch._C._cuda_getDeviceCount() > 0 False`
> > Can someone please advise what could be a possible solution to try? Thanks
> 
> Would u try this in terminal:
> 
> ```
> cd /usr/local/cuda-11.1/samples/1_Utilities/deviceQuery
> make
> sudo ./deviceQuery
> ```
> 
> and see what it return. If u get the following response:
> 
> ```
> Result = Pass
> ```
> 
> then I think u install your cuda successfully, the problem may come from the installation of pytorch or env init. ( Maybe u forget to add path in ` ~/.bashrc` like this:
> 
> ```
> export CUDA_HOME=/usr/local/cuda-11.0/bin
> export Path=/usr/local/cuda-11.0/bin
> export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64
> 
> export CUDA_VISIBLE_DEVICES=0,1,2,3
> ```
> 
> in which `CUDA_VISIBLE_DEVICES` is the number of GPU devices u owns. I use 4 A100, so I set `export CUDA_VISIBLE_DEVICES=0,1,2,3`. ) Hope this will help u.

works for me! Thanks!

**Comment by sjkoelle** [comment]
For anyone else frustrated the suggested commands in their containers, I ran 

```
sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm
```

in the host environment and it percolated through to fix the issue in my container.

**Comment by grybouilli** [comment]
> `sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm`

This seems to work but it also seems that I have to re-run this command every time I reboot my machine. Any idea how to make the fix permanent?

Currently using CUDA11.8 alongside nvidia drivers 525.147.05.

**Comment by xhinker** [comment]
> > I've recently ran into this error when migrating my gpu containers from nvidia docker to podman. The root cause for me was that `/dev/nvidia-uvm`, `/dev/nvidia-uvm-tools` files were missing that CUDA apparently needs to work. Check that you have them on both host and container/VM if you use containers. On the host, running `sudo nvidia-modprobe -c 0 -u` should fix it.
> 
> I've faced same issues when trying to continue working with pytorch session after suspend (in my case it's a Stable Diffusion web UI that keeps the session open). What also worked for me was: `sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm` which probably does the same thing as the above nvidia-modprobe command but should work on all distros.

This works!

**Comment by Bardhitoo** [comment]
I just faced this issue today, and this is a more of a unique case for me. 

I have a 2 model pipeline: YOLOv8 and SAM, and for some reason today it's throwing an error while loading SAM `untimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero`

I tried: `sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm`, but this only silenced the error for me, the model continues to run for me, but significantly slower (4-5x). Any ideas what could be going on?

**Comment by mikkorantalainen** [comment]
I've found that this is probably caused by Nvidia driver bug and it's most easily triggered by suspending the system while GPU compute is in progress in the background. Sometimes you can use workaround

    sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm

but if that returns `modprobe: FATAL: Module nvidia_uvm is in use.` and you don't see any programs running on GPU (try `nvidia-smi` to see processes accessing the GPU) then the Nvidia driver is in bad enough state to require rebooting the whole system to get the driver into sane state again.

**Comment by airtonix** [comment]
> `sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm`

@mikkorantalainen cheers.

```
> inxi -S
System:
  Host: brass Kernel: 6.7.5-200.fc39.x86_64 arch: x86_64 bits: 64
  Desktop: GNOME v: 45.4 Distro: Fedora Linux 39 (Workstation Edition)

> nvidia-smi
Sat Mar  2 14:16:27 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     Off | 00000000:08:00.0  On |                  Off |
|  0%   53C    P8              31W / 450W |   1933MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      3268      G   /usr/libexec/Xorg                           751MiB |
|    0   N/A  N/A      3509      G   /usr/bin/gnome-shell                        191MiB |
|    0   N/A  N/A      3740      G   /usr/bin/gnome-software                      79MiB |
|    0   N/A  N/A      4236      G   easyeffects                                  40MiB |
|    0   N/A  N/A      6624      G   /usr/lib64/firefox/firefox                  407MiB |
|    0   N/A  N/A     10239      G   ...ns/audiorelay-0.27.5/bin/AudioRelay       14MiB |
|    0   N/A  N/A     28203      G   /usr/bin/python3                              8MiB |
|    0   N/A  N/A     30680      G   ...local/share/Steam/ubuntu12_32/steam        6MiB |
|    0   N/A  N/A     31337      G   ./steamwebhelper                             55MiB |
|    0   N/A  N/A     74339      G   /usr/bin/gnome-control-center                10MiB |
|    0   N/A  N/A    173755      G   ...sion,SpareRendererForSitePerProcess       57MiB |
|    0   N/A  N/A    174083      G   ...seed-version=20240228-080117.468000       32MiB |
|    0   N/A  N/A    174355      G   ...ures=SpareRendererForSitePerProcess       16MiB |
|    0   N/A  N/A    174835      G   ...erProcess --variations-seed-version       54MiB |
|    0   N/A  N/A    183016      G   /usr/bin/krita                              106MiB |
|    0   N/A  N/A    183156      G   /usr/bin/nautilus                            11MiB |
|    0   N/A  N/A    183387      G   /usr/bin/alacritty                           12MiB |
+---------------------------------------------------------------------------------------+
```

the initial output.

then ran 

```
sudo modprobe -r nvidia_uvm && sudo modprobe nvidia_uvm
```

and relaunched krita with it's comfyui plugin and 👍🏻

**Comment by fmachta** [comment]
Do you think anyone can help me on windows!!!!

i want to use my GPU with pytorch

![image](https://github.com/pytorch/pytorch/assets/91919641/ffcb7f1b-629c-4f45-8022-e364bacc5ebb)

![image](https://github.com/pytorch/pytorch/assets/91919641/84d2632e-01e0-453f-a416-20a1a6a48233)

![image](https://github.com/pytorch/pytorch/assets/91919641/5534d0c3-ed1f-4a55-9ff7-483d05d88e5c)

![image](https://github.com/pytorch/pytorch/assets/91919641/aa9deb14-43c8-4b76-8205-50d502b29033)

**Comment by elthariel** [comment]
For those having the issue due to suspend/resume, there's probably something to be done with a post-suspend systemd service:

```
[Unit]
Description=<your description>
After=suspend.target
```

If I implement this, I'll try and come back to this issue to post the complete unit code, but I'm afraid I wont remember, hence the brain dump
