### ISSUE TITLE
Feature Request: support int->float type promotion for torch.reciprocal

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#49091]
torch.reciprocal does not support integer inputs today:

```
t = torch.tensor((1, 2, 3))
print(torch.reciprocal(t))
: RuntimeError: "reciprocal_cpu" not implemented for 'Long'
```

This is because reciprocal's codomain for the integers is not the integers, and historically PyTorch did not implement integer->floating point type promotion for unary ufuncs. This has changed, however. For example, torch.sin() promotes integer inputs to float:

```
t = torch.tensor((1, 2, 3))
print(torch.sin(t))
: tensor([0.8415, 0.9093, 0.1411])
```

And this is compatible with NumPy's behavior:

```
a = np.array((1, 2, 3))
print(np.sin(a))
: [0.84147098 0.90929743 0.14112001]
```

PyTorch has a pattern for implementing this behavior. See for example, this PR: https://github.com/pytorch/pytorch/pull/48644. In addition to implementing this behavior a UnaryUfuncInfo should be added for torch.reciprocal, and other tests of it that are made redundant removed.

Note that NumPy's np.reciprocal() is bugged (https://github.com/numpy/numpy/issues/10374) and does not promote integer inputs to float:

```
a = np.array((1, 2, 3))
print(np.reciprocal(a))
: [1 0 0]
```

**Comment by kshitij12345** [comment]
Reference Issue: https://github.com/pytorch/pytorch/issues/42515
