### ISSUE TITLE
How can I build torch on Apple M1?

### ISSUE THREAD

**Issue by huwei1024** [pytorch/pytorch#49096]
How can I build torch on Apple M1? Or Install torch and torchvision?

**Comment by skyline75489** [comment]
See https://github.com/pytorch/pytorch/issues/48524#issuecomment-736755245

**Comment by huwei1024** [comment]
@skyline75489  I have installed torch, but i cant install torchvision?

**Comment by skyline75489** [comment]
You need to provide more information. Like how exactly is the failure. And I suggest you file the issue in torchvision repo https://github.com/pytorch/vision.
