### ISSUE TITLE
Awkward scalar type promotion to f64 in torch.where

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#49090]
## 🐛 Bug
When mixing types between `x` and `y` arguments to `torch.where` we get an error saying that these need to match. This usually makes sense, except that `float` scalars are promoted to f64 and cause errors when used along tensor arguments of different precision. This means that

```python
import torch

switch   = torch.tensor([True, False])
vals     = torch.tensor([1., 2.], dtype=torch.float32)
selected = torch.where(switch, vals, 0.)
```
results in
```python
Traceback (most recent call last):
  File "torch-bug.py", line 5, in <module>
    selected = torch.where(switch, vals, 0.)
RuntimeError: expected scalar type float but found double
```

This is particularly annoying because there is no way to annotate the scalar as single-precision other than create an outright tensor, at which point the utility of passing scalars vanishes.

## To Reproduce
See snippet above.

## Expected behavior
I propose (though there are other possible solutions) that when mixing scalar and tensor arguments, the scalar is promoted to the type of the tensor argument (not across integer/float boundaries, but for instance `int` could get promoted to `torch.int32`, `torch.uint8` etc, and `float` to `torch.float32` or `torch.float16`, depending on the tensor's dtype). If both `x` and `y` are scalar, they should probably be promoted to the default dtype (this seems to already work).

## Environment

Collecting environment information...
PyTorch version: 1.7.0
Is debug build: Yes
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.19.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.0
[pip3] torch-dimcheck==0.0.1
[pip3] torch-localize==0.1.0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.0               py3.8_cpu_0  [cpuonly]  pytorch
[conda] torch-dimcheck            0.0.1                    pypi_0    pypi
[conda] torch-localize            0.1.0                    pypi_0    pypi
[conda] torchvision               0.8.1                  py38_cpu  [cpuonly]  pytorch

cc @heitorschueroff @nairbv @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @jatentaki. I agree with you the current behavior is a pain. We would happily accept a PR fixing this.

**Comment by gchanan** [comment]
Going to close in favor of https://github.com/pytorch/pytorch/issues/9190.
