### ISSUE TITLE
Implement Broadcasting with exact semantics as NumPy

### ISSUE THREAD

**Issue by wiseodd** [pytorch/pytorch#491]
I'm not familiar with Torch and its behavior, but in numpy, one can do this:

``` python
X = np.random.randn(100, 10)
W = np.random.randn(10, 64)
b = np.ones(64)
z = X @ W + b # Works
```

However the similar operation fails in pytorch:

``` python
X = torch.randn(100, 10)
W = torch.randn(10, 64)
b = torch.ones(64)
z = X @ W + b # Error, cannot add tensor of size [100, 64] and [64]
```

The message I got:
```
RuntimeError: inconsistent tensor size at /Users/soumith/anaconda/conda-bld/pytorch-0.1.6_1484756295864/work/torch/lib/TH/generic/THTensorMath.c:601
```

Is this the expected behavior? If so, what is the preferred way to do the bias addition in pytorch?

**Comment by soumith** [comment]
numpy has broadcasting semantics implemented.
In torch, we plan to add broadcasting, but we haven't yet done so.

For now, you can use the [repeat](http://pytorch.org/docs/tensors.html?highlight=repeat#torch.Tensor.repeat) function to expand ahead:

```
X = torch.randn(100, 10)
W = torch.randn(10, 64)
b = torch.ones(64)
z = X @ W + b.repeat(X.size(0), 1)
```

**Comment by apaszke** [comment]
Actually, it's more efficient to use `b.unqueeze(0).expand(X.size(0), b.size(0))` (`repeat` makes a new tensor, while `expand` does strides). I'll add `b.broadcast` that does it as a single op

**Comment by naifrec** [comment]
Am I right that `unsqueeze` [does not appear in the documentation](http://pytorch.org/docs/tensors.html?highlight=unsqueeze#torch.Tensor.unsqueeze)? I especially like the [`.expand_as`](http://pytorch.org/docs/tensors.html?highlight=expand#torch.Tensor.expand_as) solution you gave on PyTorch forum.

**Comment by fmassa** [comment]
@naifrec indeed, seems that there is some documentation missing for `unsqueeze`. Could you send a PR adding it?

**Comment by fmassa** [comment]
Hum, seems that there is some documentation written in https://github.com/pytorch/pytorch/commit/712686ce91cac3142c6eecd4d74902939db59aa8#diff-cfb065e43691d37ba30f3856fe4352b3R4216
The link is seems to be missing though

**Comment by soumith** [comment]
ok i need to add an entry in torch.rst so that the documentation appears. let me do that.

**Comment by LinxiFan** [comment]
Just to check in: has broadcast been implemented for general tensors? I still can't easily do bias addition in the latest version.

**Comment by soumith** [comment]
at the current moment, broadcasting as been implemented via expand / expand_as: `x.add(y.expand_as(x))`. Automatic broadcasting such as `x.add(y)` is not yet implemented, we are getting there soon.

**Comment by LinxiFan** [comment]
@soumith this is good enough. Thanks a lot!

**Comment by gchanan** [comment]
I'm working on this currently.

**Comment by gchanan** [comment]
A note on numpy broadcast semantics: It's not really specified here as far as I can tell (https://docs.scipy.org/doc/numpy-1.10.0/user/basics.broadcasting.html), but:

For non-inplace operations, broadcasting works across both tensors (i.e. [1,3] X [3,1] becomes [3,3] so expand/expandAs on a single tensor isn't sufficient)

For in-place operations, broadcasting only works on the non-ouput tensor (i.e. [1,3] X [3,1] gives you "ValueError: non-broadcastable output operand with shape (1,3) doesn't match the broadcast shape (3,3)" and [3,3] X [3,1] works.

**Comment by zxytim** [comment]
Looking forward to this function

**Comment by gchanan** [comment]
Here's some notes I wrote up numpy broadcasting semantics and how to apply them to torch: https://github.com/gchanan/pytorch/wiki/Broadcasting-Notes

If you are interested on how this applies to more than pointwise operations (implemented in https://github.com/pytorch/pytorch/pull/1563), you may find it interesting.

**Comment by soumith** [comment]
done via https://github.com/pytorch/pytorch/pull/1563
