### ISSUE TITLE
Rename `torch.set_deterministic` for more clarity

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#49100]
The name `set_deterministic` does not effectively describe what the function does, and it should probably be renamed. The function configures PyTorch to use deterministic implementations of operations, if they are available. Or in other words, it enforces reproducibility.

I would like to get the community's opinion about a better name for `set_deterministic`, so please comment if you have any ideas!

Here are a few options:

- `use_deterministic_ops`
- `use_deterministic_operations` (at the moment, I prefer this one)
- `use_deterministic_algorithms`

**Comment by stas00** [comment]
the docs in both places:
* https://pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms
* https://pytorch.org/docs/stable/generated/torch.set_deterministic.html#torch.set_deterministic
say "use deterministic algorithms", so probably your 3rd suggestion (`use_deterministic_algorithms`) is most apt.

**Comment by jspisak** [comment]
Hmm, yeah i can see how this could cause confusion. Shall we bikeshed some name proposals? 

cc @gchanan, @mruberry

**Comment by mruberry** [comment]
My proposal was "use_deterministic_ops" and all of them see fine.

**Comment by kurtamohler** [comment]
Since it's been a few days and there haven't been any additional name suggestions, let's take a poll. Anyone who has an opinion, please thumbs up one of the three comments below to vote for your preference

**Comment by kurtamohler** [comment]
`use_deterministic_ops`

**Comment by kurtamohler** [comment]
`use_deterministic_operations`

**Comment by kurtamohler** [comment]
`use_deterministic_algorithms`
