### ISSUE TITLE
CMake error when building from source

### ISSUE THREAD

**Issue by dpernes** [pytorch/pytorch#4913]
When I try to build and install PyTorch master version from source, I start getting CMake errors, complaining about undefined references. The first error is:

```
[ 97%] Linking CXX executable broadcast_test
CMakeFiles/wrapdim_test.dir/wrapdim_test.cpp.o: In function `barf(char const*, ...) [clone .constprop.24]':
wrapdim_test.cpp:(.text+0xee): undefined reference to `std::runtime_error::runtime_error(char const*)'
```
I have followed all recommended steps prior to installation, namely:
```
export CMAKE_PREFIX_PATH="~/.anaconda3/"
conda install numpy pyyaml mkl setuptools cmake cffi
conda install -c pytorch magma-cuda80
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python setup.py install
```

I am running Linux (Ubuntu 16.04 LTS) and installing PyTorch with CUDA support (CUDA 8.0, cuDNN 6.0.21). Thank you in advance.

**Comment by dpernes** [comment]
Just installed conda’s gcc and the issue is solved. Maybe this should be added to the list of required packages…

**Comment by ezyang** [comment]
Did you do `conda install gcc`? This is unlikely to work, see https://github.com/pytorch/pytorch/issues/3050 and https://github.com/conda/conda/issues/6132 for back story.

**Comment by dpernes** [comment]
Yes, I did and it (finally) worked. I see from #3050 that this was not supposed to work, but it actually did. Using the system-wide gcc did not work, though...

**Comment by ezyang** [comment]
It's possible upstream fixed the problem since we last looked at it; good to know.
