### ISSUE TITLE
GPU tensor sum changes after transpose

### ISSUE THREAD

**Issue by myleott** [pytorch/pytorch#4914]
This happens intermittently with CUDA tensors, but never with CPU tensors:

```
>>> x = torch.rand(3, 4, 5).cuda()
>>> x.sum()
26.833271026611328
>>> x.transpose(0, 1).sum()
26.83327293395996
```

This happens both on a recent version of PyTorch (0.4.0a0+4970e73) and 0.3.0.

Is this expected behavior?

**Comment by apaszke** [comment]
Yes. It's a result of floating point math being non-associative. In the second case, the elements will be added in a different order.
