### ISSUE TITLE
nightlies are no longer being built for linux - since dec08

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#49142]
it seems that nightlies are no longer being built for linux - last build dec07 - I see new windows builds, but no linux.
see https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html
or https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html

**Comment by t-vi** [comment]
I think this might be fixed by Ed's revert here:
https://github.com/pytorch/pytorch/commit/7a2abbd8fdcbb51fba0fd420f2861a4b56adb45b

**Comment by stas00** [comment]
confirming that it has been fixed indeed - thank you!
