### ISSUE TITLE
FunctionSchema throw c10::Error (bazel build torch)

### ISSUE THREAD

**Issue by duanyzhi** [pytorch/pytorch#49154]
version:
pytorch1.6.0

1. example: main.cpp

#include <torch/torch.h>
#include <iostream>

int main() {
  torch::Tensor tensor = torch::rand({2, 3});
  std::cout << tensor << std::endl;
}

add to pytorch/BUILD.bazel file:

cc_binary(
  name = "main",
  srcs = ["main.cpp"],
  deps = [":torch"],
)

2. git clone pytorch1.6 and get submodule

3. build:
bazel build //:main

4. run:
./bazel_bin/main

output:
   0.6982  0.6582  0.6224                                                                                                                                                                                        
   0.2512  0.9473  0.8200                                                                                                                                                                                        
   [ CPUFloatType{2,3} ]   
terminate called after throwing an instance of 'c10::Error'
  what():  schema_.has_value() INTERNAL ASSERT FAILED at "aten/src/ATen/core/dispatch/OperatorEntry.h":42, please report a bug to PyTorch. Tried to access the schema for 0�Rquires_grad_

Aborted (core dumped)

debug error to aten/src/ATen/core/dispatch/OperatorEntry.h:42
the schema_.has_value() is 0 and name_ is illegal, gdb print name_ is: 
(gdb) p name_
$1 = {name = "0-}\f\000\000\000\000quires_grad_", overload_name = ""}

I think the op name is: aten::requires_grad_

  but i do not know how to fix this? thx.

**Comment by H-Huang** [comment]
Hitting an internal assert failure, marking as high priority

**Comment by H-Huang** [comment]
Hi @duanyzh, I noticed you are trying to add a new target to the build folder. What is this for? The [PyTorch forums](https://discuss.pytorch.org/) is a good place to answer your question.
