### ISSUE TITLE
Cannot build iOS benchmark app for PyTorch Mobile

### ISSUE THREAD

**Issue by windmaple** [pytorch/pytorch#49162]
## To Reproduce

I’m closely following the 'iOS - benchmarking setup' instructions [here](https://pytorch.org/tutorials/recipes/mobile_perf.html#ios-benchmarking-setup) to the letter. I was able to build the library and run 'ruby setup.rb', but I hit this error in Xcode 12.2 when trying to run the app on iPhone XR (iOS 14.2):

> /Users/wind/Desktop/project-src/pytorch/build_ios/install/lib/libXNNPACK.a(1x8inc-minmax-aarch64-neonfp16arith-ld64.S.o), building for iOS, but linking in object file built for macOS, file ‘/Users/wind/Desktop/project-src/pytorch/build_ios/install/lib/libXNNPACK.a’ for architecture arm64

Looks like wrong library is built. Anybody has any idea what needs to be changed?

I'm building off 'eb9516ea'. If I use cocoapod, it works fine. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): eb9516ea
 - OS (e.g., Linux): mac
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by skyline75489** [comment]
I can't reproduce this. Did you run the `ruby setup.rb` after building the library?

**Comment by skyline75489** [comment]
Are you using a older cmake version? See https://github.com/pytorch/pytorch/issues/44143#issuecomment-701703075 

I'm using cmake 3.18.2.

**Comment by windmaple** [comment]
Thanks @skyline75489 !
I upgraded my cmake to 3.19.1 and can run it now. Would be good to add cmake version req. to the doc.
