### ISSUE TITLE
NN Module functional API

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#49171]
## 🚀 Feature

Either:
- A way to go from a stateful NN Module to a functional (read: functions only and stateless) NN Module.
- An alternative, functional NN Module API in addition to our current NN API.

## Motivation

It is difficult to use the `torch.autograd.functional` APIs with NN modules because these APIs require the user to pass the parameters to a function. For example, consider the `torch.autograd.functional.jacobian` API:

```py
torch.autograd.functional.jacobian(func, inputs, create_graph=False, strict=False)
```

An nn.Module holds some parameters, but we would like to grab those parameters and send it through the `jacobian` function. It is not sufficient to do:
```py
import torch
import torch.nn as nn
import torch.autograd.functional as F
from functools import partial

N = 2
model = nn.Linear(3, 5)
data = torch.randn(N, 3)
params = tuple(model.parameters())
func = lambda *params: model(data)
jacs = F.jacobian(func, params)
```
This returns jacobians that are full of zeros, which is not what we wanted. The higher level autograd API takes the Tensors to differentiate (`params` in this case) and [preprocesses them to create new Tensors](https://github.com/pytorch/pytorch/blob/3779bdec56ca300ccb1e52efb76777ea574f1885/torch/autograd/functional.py#L42-L62) that record autograd history. The reason why this returns zero jacobians is because the `params` being passed to `func` don't actually get used. 

As a quick "proof-by-example" that the jacobians shouldn't be zero, the following gives non-zero jacobians:
```py
def run_model(weight, bias, data):
    return nn.functional.linear(data, weight, bias)

F.jacobian(partial(run_model, data=data), params)
```

Furthermore, it is difficult to use the prototype torch.vmap API on an nn.Module for the same reason: there is currently no PyTorch-blessed mechanism to, given an nn.Module, create a stateless callable that does the same thing as the module.

## Pitch

Here's one possibility for the API that implements a way to go from a stateful nn.Module to a functional variant of it. The building blocks for this is already implemented in [our functional autograd benchmarks](https://github.com/pytorch/pytorch/blob/21c04b4438a766cd998fddb42247d4eb2e010f9a/benchmarks/functional_autograd_benchmark/utils.py#L19-L71) and [higher](https://github.com/facebookresearch/higher) has something similar:

```py
def make_functional(model: nn.Module) -> "params", Callable[Tuple["data", "params"], Any]:
    """Given an nn.Module, returns its Parameters
    and a Callable that takes in inputs to the module and the params and returns the output.
    """
    pass
```

Here's how one would call it with `functional.jacobian`:
```py
# pseudocode
model: nn.Module = ...
data: Tensor = ...
params, func = make_functional(model)
F.jacobian(partial(func, data), params)  # Compute jacobian w.r.t to module parameters
F.jacobian(partial(func, params=params), data)  # Compute jacobian w.r.t to module inputs
```

We've omitted some details of how this API should work:
- how should "Params" look like? How does the user create a different set of Params or operate over them?
- What about buffers that are registered on modules? Do we pull them out as well?
- How does this work with modules that mutate internal state, like nn.BatchNorm?

deepmind/dm-haiku has some interesting ideas for the above two questions that we can look to for inspiration.

## Alternatives

I'm not sure that we can actually remove state from all of our nn.Modules. We can certainly do this for most of them, though.

One alternative to a NN Module functional API is to tell PyTorch users to always use the nn.functional variant of a module if they wish to use the autograd.functional APIs (e.g., use F.conv2d instead of nn.Conv2d). However, users use the NN API because it is handy: carrying around all of the parameters manually sometimes unwieldy, especially if you built a model out of some number of nested layers and have a large number of parameters to keep track of

A stretch goal that may be out of scope for this is "An alternative, functional NN Module API in addition to our current NN API". We may want something like this if we're planning on having a way to make our NN modules more functional anyways. There have been a number of NN module designs in JAX that work with a functional API. One example is `stax`, which models Modules as an (init_fn, apply_fn) pair. If you have JAX installed, here's how one gets the jacobian of a Linear layer with stax:

```py
import jax
import jax.numpy as jnp
import jax.experimental.stax as stax
from functools import partial

key = jax.random.PRNGKey(0)
N = 2
data = jnp.ones([N, 3], dtype=jnp.float32)
init_fn, apply_fn = stax.Dense(5)

_, params = init_fn(key, data.shape)
# jax.jacrev is the API to compute the jacobian using reverse-mode AD
jax.jacrev(partial(apply_fn, inputs=data))(params)
```

Here's a similar example, but using the deepmind/dm-haiku library. `haiku.transform` turns what looks like a stateful Module (it's not actually stateful) into an (init_fn, apply_fn) pair.

```py
import haiku as hk
import jax
import jax.numpy as jnp
from functools import partial

key = jax.random.PRNGKey(0)
data = jnp.ones([2, 3])

def model(data):
    mlp = hk.Linear(5)
    return mlp(data)

func = hk.transform(model)
params = func.init(key, data)
jax.jacrev(lambda params: func.apply(params, key, data))(params)
```

## Additional context

facebookresearch/higher does something similar: https://github.com/facebookresearch/higher
JAX, a very functional framework, has a few different NN libraries that are all functional all with some interesting design choices.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by albanD** [comment]
> how should "Params" look like? 

I think that a good way to start would be to re-use `.named_parameters()` that gives all the relevant information that we need here.

> What about buffers that are registered on modules? Do we pull them out as well?

I don't think we need to support that from the beginning as most of the use cases I have seen always differentiate to the parameters or inputs.
That being said, I'm sure there are cases where this could be interesting so I think we want to try to have an API to could easily be extended for buffers.

> How does this work with modules that mutate internal state, like nn.BatchNorm?

This is a very good question.
The first though I would have is that these Modules will be tricky to move to a functional API to begin with and are not very common. So maybe we can forbid them as a first step?

That being said, I think it opens to broader question for user-defined Modules where they can go crazy in modifying parameters and buffers in the forward. I don't think we will be able to make it work for all of them and it would make sense to only support Modules that do not mutate states during the forward pass?

> Also it would be great if it can accept a flattened parameter vector, making pointwise ops (e.g., optimization steps) much easier). Going from a vector to a collection of parameters is easy- just splitting and reshaping.

@SsnL I see where you're coming from with this one :D 
I don't think we want to make such utility the go-to way as they proved to be very tricky to use by end users in the torch7 days. 
I think the approach we are targeting to make these efficient is based on "mulit-apply" that is work in progress. You can see WIP version of the optimizers [here](https://github.com/pytorch/pytorch/tree/master/torch/optim/_multi_tensor) for example.

**Comment by zou3519** [comment]
The thing we have proposed here is very similar to a mechanism that [deepmind/haiku](https://github.com/deepmind/dm-haiku) has. That mechanism is roughly as follows:
- `hk.transform(module)` returns an object that effectively represents the parameters and a callable

For modules with some internal non-trainable state, like BatchNorm, they define a way to pull the state out of a module:
`hk.transform_with_state(module)` returns something like a (params, state, callable) tuple. The callable takes in params, state, and the input to the module and returns an (output, state) tuple.

From staring at this for a few minutes, it look like that should work as long as we don't need to shoehorn our modules too much to be able to get the internal state

**Comment by albanD** [comment]
> From staring at this for a few minutes, it look like that should work as long as we don't need to shoehorn our modules too much to be able to get the internal state

Restricting the state to be the buffers would be ok?

**Comment by SsnL** [comment]
@albanD 
> I don't think we want to make such utility the go-to way as they proved to be very tricky to use by end users in the torch7 days.
> I think the approach we are targeting to make these efficient is based on "mulit-apply" that is work in progress. You can see WIP version of the optimizers here for example.

But in practice you are not always using provided optimizers. I believe that more often than not, you would like the flexibility to implement arbitrary pointwise ops easily.

**Comment by albanD** [comment]
@SsnL ho yes I agree that we would like to have that. And that is the goal of that API, the optimizer is just one use case for it. The general issue is: https://github.com/pytorch/pytorch/issues/38655

**Comment by ezyang** [comment]
While recording a podcast about this topic, I realized there's some more nuance about how we design our functional transformations (grad/vmap) to interact with tensors.

To set the stage, I would pose the question: what's the difference between torch.autograd.functional.vjp (which doesn't work with nn.Modules) and torch.autograd.grad (which does). To me, the key difference is that the functional API does not expose `parameter.requires_grad` as a public API concept (instead, you compute gradients of all the inputs you pass to vjp directly), whereas the imperative API requires you have preemptively marked all the parameters you want to differentiate with respect to with `requires_grad = True`. This design works well with nn.Module, because you typically never change what parameters you want to optimize (so all Parameters are just defined with `requires_grad=True` and you never have to touch it later).

This distinction between "extra metadata on the tensor" (requires_grad) in this case being a private implementation detail (functional API) versus a public API (imperative API) manifests repeatedly in multiple contexts. For example, when designing forward mode AD, @albanD had long discussions about whether or he should only expose a higher order `jvp` combinator (functional API), or expose "dual tensors" as a first class API concept (imperative API). See also https://github.com/pytorch/pytorch/issues/10223#issuecomment-691225737 In the end we went with dual tensors as a first class concept because, as @zou3519, it's more PyTorch-y.

So, here's the question: can we make this work out universally, for ALL functional transformations? (If so, then I would imagine a universe where people merely edit the metadata on parameters on nn.Modules for the functional transformations they'd like to occur, and then everything "works out". But how to decide on ordering? This is all very intruiging, and I don't know!)

**Comment by lw** [comment]
I listened to the podcast today, and the idea of clearly separating the state from the "transformations" that operate on it resonated with something else I'm thinking about. I don't know if functional modules are the answer for that, but let me give you our problem statement.

In RPC, we expect users will store a NN module on a node and then operate on it from another node, by issuing RPC requests (which, for example, could do a forward pass, an optimizer step, ...). The tool we give users to do so is the RRef (remote reference): in our current docs/examples, what we do is put the module in a RRef, and pass a handle to everyone who needs to operate on it.

The problem we have is that if there are multiple RPC requests operating on the same module (the same RRef) we cannot guarantee any ordering between them, because they will on different threads and multiple CUDA stream and thus could race. This problem is particularly bad with CUDA tensors (and still unresolved!), because inplace modifications aren't immediately visible (unless one blocks to wait for the kernels to finish).

In general, I think the "core" issue is precisely the "inplace" aspect of this. RRefs in a sense behave like futures, and thus it's easier to think about them if their values were immutable. If the value starts changing it's hard to synchronize with any of these later "versions" of the value. What I think we should do is have a new separate RRef for each new version of the value. This means we can assume the values are immutable, and that if there is any logical dependency between different "versions" of a tensor this must be explicitly reflected in the "data dependency graph" of RRefs.

Hence I really like the idea of reimagining modules as a state (its params, stored in RRefs) and a transition function (the "functionalized" module, which will be performed in the RPC requests).

CC @mrshenli @SciPioneer

**Comment by zou3519** [comment]
@lw this is an interesting problem! I'm not familiar with RPC and had some clarifying questions:

> Hence I really like the idea of reimagining modules as a state (its params, stored in RRefs) and a transition function (the "functionalized" module, which will be performed in the RPC requests).

Is the proposal for avoiding the data race that each RPC request has a separate state (params) that it uses? If so, as an alternative that doesn't use functional modules, could you keep multiple copies of the module around and have each RPC request act on a different module?

**Comment by lw** [comment]
> as an alternative that doesn't use functional modules

Indeed I don't think functional modules are _needed_ to solve that. I just thought that they aligned nicely "conceptually" with this idea. I believe in practice we could just modify the NN module in-place, as we do now, and then re-wrap the result in a new RRef. This means we have two distinct RRefs pointing to the same value (which is a bit odd) but they would each have different CUDA events, so it still works. Sorry if this just ended up adding to the noise.

**Comment by ain-soph** [comment]
@zou3519 
Hi, sorry for coming to this issue again.  
I previously proposed a current **dirt** workaround in #50138 .  
Even though it's quite ugly, but it helped me successfully get everything done (by delete the weights and reassign them).

Hope it helps. And if there is more elegant approach, plz let me know. I suffer this a lot to compute Fisher Information😂

```python3
import torch
import torch.nn as nn

a = torch.ones(3, 4).requires_grad_()
module = nn.Linear(4, 16)

def func(weight, bias):
    del module.weight
    module.weight = weight
    del module.bias
    module.bias = bias
    return module(a)

result = torch.autograd.functional.jacobian(func, tuple(module.parameters()))
print(result[0].shape)  # weight (3, 16, 16, 4)
print(result[1].shape)  # bias   (3, 16, 16)
print(result)  # Correct Values!
```

**Comment by ain-soph** [comment]
Any new progress on this issue? @zou3519

**Comment by albanD** [comment]
Note that we introduced a very experiemental API in https://github.com/pytorch/pytorch/pull/61447 to do this.
Don't hesitate to test this out and give feedback here about it!

**Comment by ain-soph** [comment]
> Note that we introduced a very experimental API in #61447 to do this. Don't hesitate to test this out and give feedback here about it!

Hi @albanD , is the `functional_call` feature helpful for computing `jacobian` and `hessian` with response to model parameters?  
If so, would you kindly provide a minimum snippet? I'm still using the workaround mentioned above, which is somehow similar, but too stupid.

**Comment by albanD** [comment]
Hi,

Sure, the following would work:
```python
import torch
from torch.autograd.functional import jacobian
from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)

names = list(n for n, _ in model.named_parameters())
jacobian(lambda *params: _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters()))
```

**Comment by ain-soph** [comment]
It works with charm when I calculate Fisher Information!  
The `_stateless.functional_call` provides us to apply `autograd.functional.*` normally wrt `nn.Module` (i.e., model parameters).  

Here I'd like to share a comparison between the old method (grad backward for every coordinates and stack together) and the new method (Jacobian wrt model parameters). They return same results.


**Advantage**: use jacobian for parallel computing. Old method needs to traverse each coordinates to conduct gradient backward and stack tensors together.
**Disadvantage**: When you only need to calculate the term wrt a subset of model parameters, it requires to pass `named_parameters` as arguments, rather than `parameters` in the old method. Since reparameterization requires the names to replace attributes, but I think it is feasible to only pass parameters and check tensor ids to arrange name automatically?  

python 3.9 snippet: 
```python3
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.nn.utils import _stateless

from typing import Iterable


def old_fim(module: nn.Module, _input: torch.Tensor,
            parameters: Iterable[nn.Parameter] = None
            ) -> list[torch.Tensor]:
    if parameters is None:
        parameters = tuple(module.parameters())
    _output = module(_input)  # (N, C)
    with torch.no_grad():
        prob = F.softmax(_output, dim=1).unsqueeze(-1).unsqueeze(-1)  # (N, C, 1, 1)
    log_prob = F.log_softmax(_output, dim=1)  # (N, C)
    fim_dict: dict[int, list[torch.Tensor]] = {i: [] for i in range(len(parameters))}
    N, C = log_prob.shape
    for n in range(N):
        for c in range(C):
            grad_list = torch.autograd.grad(log_prob[n][c], parameters, retain_graph=True)
            for i, grad in enumerate(grad_list):    # different layers
                flatten_grad = grad.flatten()    # (D)
                fim = flatten_grad.unsqueeze(1) * flatten_grad.unsqueeze(0)   # (D, D)
                fim_dict[i].append(fim.detach().clone())
    fim_list: list[torch.Tensor] = []
    for i, value in fim_dict.items():    # different layers
        D = value[0].shape[0]
        fim = torch.stack(value).view(N, C, D, D) * prob    # (N, C, D, D)
        fim_list.append(fim.sum(1).mean(0))   # (D, D)
    return fim_list


def new_fim(module: nn.Module, _input: torch.Tensor,
            parameters: dict[str, nn.Parameter] = None
            ) -> list[torch.Tensor]:
    if parameters is None:
        parameters = dict(module.named_parameters())
    with torch.no_grad():
        _output = module(_input)  # (N, C)
        prob = F.softmax(_output, dim=1).unsqueeze(-1).unsqueeze(-1)  # (N, C, 1, 1)
    keys, values = zip(*parameters.items())

    def func(*params: torch.Tensor):
        _output = _stateless.functional_call(module, {n: p for n, p in zip(keys, params)}, _input)
        return F.log_softmax(_output, dim=1)  # (N, C)
    jacobian_list: tuple[torch.Tensor] = torch.autograd.functional.jacobian(func, values)

    fim_list: list[torch.Tensor] = []
    for jacobian in jacobian_list:  # TODO: parallel
        jacobian = jacobian.flatten(start_dim=2)   # (N, C, D)
        fim = prob * jacobian.unsqueeze(-1) * jacobian.unsqueeze(-2)  # (N, C, D, D)
        fim_list.append(fim.sum(1).mean(0))   # (D, D)
    return fim_list


if __name__ == '__main__':
    model = torch.nn.Sequential(torch.nn.Linear(2, 2), torch.nn.Linear(2, 2))
    inp = torch.rand(1, 2)

    old_result = old_fim(model, inp)
    new_result = new_fim(model, inp)

    print('scale     : ', [float(a.abs().max()) for a in new_result])
    print('difference: ', [float((a - b).abs().sum()) for a, b in zip(new_result, old_result)])

```

Results:
```
scale     :  [0.02580949291586876, 0.06026922166347504, 0.21482378244400024, 0.24690933525562286]
difference:  [1.7462298274040222e-10, 1.862645149230957e-09, 0.0, 5.960464477539063e-08]
```

**Comment by ain-soph** [comment]
@albanD  
What about add these codes at the beginning of `functional_call` so that `parameters_and_buffers` could be `Iterable[torch.Tensor]` (model.parameters()) rather than `dict[str, torch.Tensor]` (model.named_parameters())

Since it is feasible to locate the corresponding names automatically.

```python3

    if not isinstance(parameters_and_buffers, dict):
        id_map: dict[torch.Tensor, str] = {param.data: name
                                           for name, param in module.named_parameters()}
        parameters_and_buffers = {id_map[param.data if isinstance(param, torch.nn.Parameter) else param]: param
                                  for param in parameters_and_buffers}
```

**Comment by albanD** [comment]
That would only work under the assumption that this is how you got this iterable.
Also the reason why the functional API is this way is because the call might modify the input before passing it and so the map will not work.

If you want to do partial matching like that, a simple solution is just to save the name on the param itself:
```python
params = []
for k, p in module.named_parameters():
  if skip_some_p():
    continue
  p.mod_name = k

# Call into jacobian with `params`
# To call in functional call, just do:
functional_call(model, {p.mod_name: p for p in params}, inputs)
```

**Comment by Mohamed-Rafik-Bouguelia** [comment]
I tried  _stateless.functional_call (from https://github.com/pytorch/pytorch/blob/8532061bce8da8b5fe9ecce1067ade16793a7ee3/torch/nn/utils/_stateless.py) on a module that contains a torch.nn.BatchNorm1d, and I got the error below. Did I miss something? (It seems to works fine without torch.nn.BatchNorm1d).

RuntimeError: The parametrization '_ReparametrizedTensor' does not implement a 'right_inverse' method. Assigning to a parametrized tensor is only possible when all the parametrizations implement a 'right_inverse' method.

**Comment by QiyaoWei** [comment]
Hi, thanks a lot for the development on this! This is super-useful work! In my situation, I would like to calculate the hessian, so I naively changed the code like this

```
import torch
from torch.autograd.functional import hessian
from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)

names = list(n for n, _ in model.named_parameters())
hessian(lambda *params: _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters()))
```

but I got the following error

```
Traceback (most recent call last):
  File "test.py", line 79, in <module>
    print(hessian(lambda *params: functional_call(model, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters())))
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py", line 701, in hessian
    res = jacobian(jac_func, inputs, create_graph=create_graph, strict=strict, vectorize=vectorize)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py", line 482, in jacobian
    outputs = func(*inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py", line 697, in jac_func
    jac = jacobian(ensure_single_output_function, inp, create_graph=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py", line 482, in jacobian
    outputs = func(*inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py", line 692, in ensure_single_output_function
    raise RuntimeError("The Tensor returned by the function given to hessian should contain a single element")
RuntimeError: The Tensor returned by the function given to hessian should contain a single element
```

**Comment by ain-soph** [comment]
@QiyaoWei Hessian requires a function which returns a scalar value, while your current function returns `model(inp)`, which is not scalar.

In the previous Jacobian example, Jacobian requires a function which returns a vector. This is the difference.

**Comment by QiyaoWei** [comment]
oops, it's only totally obvious when someone points it out :)

I have verified that setting `model(inp)` with shape `(1,1)` indeed allows for a Hessian calculation. However, I wonder if there's more to do in order to calculate the Hessian wrt loss in this example? I changed my code to

```
import torch
from torch.autograd.functional import jacobian, hessian
from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)

def loss(x):
    return torch.sum((model(x)) ** 2)

names = list(n for n, _ in model.named_parameters())
print(hessian(lambda *params: functional_call(loss, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters())))
```

which results in an error that seems to complain about the loss function not having any trainable parameters

```
AttributeError                            Traceback (most recent call last)
<ipython-input-6-845474a043b7> in <module>
     68 
     69 names = list(n for n, _ in model.named_parameters())
---> 70 print(hessian(lambda *params: functional_call(loss, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters())))

/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py in hessian(func, inputs, create_graph, strict, vectorize)
    699         return jac
    700 
--> 701     res = jacobian(jac_func, inputs, create_graph=create_graph, strict=strict, vectorize=vectorize)
    702     return _tuple_postprocess(res, (is_inputs_tuple, is_inputs_tuple))
    703 

/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py in jacobian(func, inputs, create_graph, strict, vectorize)
    480         inputs = _grad_preprocess(inputs, create_graph=create_graph, need_graph=True)
    481 
--> 482         outputs = func(*inputs)
    483         is_outputs_tuple, outputs = _as_tuple(outputs,
    484                                               "outputs of the user-provided function",

/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py in jac_func(*inp)
    695 
    696     def jac_func(*inp):
--> 697         jac = jacobian(ensure_single_output_function, inp, create_graph=True)
    698         _check_requires_grad(jac, "jacobian", strict=strict)
    699         return jac

/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py in jacobian(func, inputs, create_graph, strict, vectorize)
    480         inputs = _grad_preprocess(inputs, create_graph=create_graph, need_graph=True)
    481 
--> 482         outputs = func(*inputs)
    483         is_outputs_tuple, outputs = _as_tuple(outputs,
    484                                               "outputs of the user-provided function",

/opt/conda/lib/python3.8/site-packages/torch/autograd/functional.py in ensure_single_output_function(*inp)
    682 
    683     def ensure_single_output_function(*inp):
--> 684         out = func(*inp)
    685         is_out_tuple, t_out = _as_tuple(out, "outputs of the user-provided function", "hessian")
    686         _check_requires_grad(t_out, "outputs", strict=strict)

<ipython-input-6-845474a043b7> in <lambda>(*params)
     68 
     69 names = list(n for n, _ in model.named_parameters())
---> 70 print(hessian(lambda *params: functional_call(loss, {n: p for n, p in zip(names, params)}, inp), tuple(model.parameters())))

<ipython-input-6-845474a043b7> in functional_call(module, parameters_and_buffers, args, kwargs)
     49     if kwargs is None:
     50         kwargs = {}
---> 51     with reparametrize_module(module, parameters_and_buffers):
     52         if isinstance(args, tuple):
     53             out = module(*args, **kwargs)

/opt/conda/lib/python3.8/contextlib.py in __enter__(self)
    111         del self.args, self.kwds, self.func
    112         try:
--> 113             return next(self.gen)
    114         except StopIteration:
    115             raise RuntimeError("generator didn't yield") from None

<ipython-input-6-845474a043b7> in reparametrize_module(module, parameters_and_buffers)
     19     # Parametrization does not support to change submodules directly
     20     for name, tensor in parameters_and_buffers.items():
---> 21         _apply_func_submodules(
     22             torch.nn.utils.parametrize.register_parametrization,
     23             module, name.split("."), (_ReparametrizedTensor(tensor),))

<ipython-input-6-845474a043b7> in _apply_func_submodules(func, module, path, args)
     40 def _apply_func_submodules(func, module, path, args):
     41     if len(path) == 1:
---> 42         func(module, path[0], *args)
     43     else:
     44         _apply_func_submodules(func, getattr(module, path[0]), path[1:], args)

/opt/conda/lib/python3.8/site-packages/torch/nn/utils/parametrize.py in register_parametrization(module, tensor_name, parametrization)
    260         True
    261     """
--> 262     parametrization.train(module.training)
    263     if is_parametrized(module, tensor_name):
    264         # Just add the new parametrization to the parametrization list

AttributeError: 'function' object has no attribute 'training'
```

**Comment by QiyaoWei** [comment]
Works like a charm! Thank you so much for your patient answers!

**Comment by carlosgmartin** [comment]
@zou3519 @albanD I think it would be great for PyTorch to move toward a more purely-functional API. What do you think of the following JAX-inspired approach, which keeps parameters in a tree and feeds this parameter tree directly into the model together with the input?

```python
import torch
import operator

class Affine:
    def __init__(self, n, m):
        self.n = n
        self.m = m
    def init(self):
        return [
            torch.randn(self.n, self.m),
            torch.randn(self.m),
        ]
    def apply(self, w, x):
        a, b = w
        return x @ a + b

class Compose:
    def __init__(self, f):
        self.f = f
    def init(self):
        return [
            fi.init()
            for fi in self.f
        ]
    def apply(self, w, x):
        for fi, wi in zip(self.f, w):
            x = fi.apply(wi, x)
        return x

class Lambda:
    def __init__(self, f):
        self.f = f
    def init(self):
        return []
    def apply(self, w, x):
        return self.f(x)

def tree_map(fun, *trees):
    if isinstance(trees[0], torch.Tensor):
        assert all(isinstance(t, torch.Tensor) for t in trees[1:])
        return fun(*trees)
    elif isinstance(trees[0], list):
        assert all(isinstance(t, list) for t in trees[1:])
        n = len(trees[0])
        assert all(len(t) == n for t in trees[1:])
        return [
            tree_map(fun, *subtrees)
            for subtrees in zip(*trees)
        ]
    else:
        raise Exception('invalid tree type {}'.format(type(trees[0])))

def pack(tree):
    if isinstance(tree, torch.Tensor):
        return tree.flatten()
    elif isinstance(tree, list):
        if tree == []: # torch.cat([]) throws an error
            return torch.tensor([])
        return torch.cat([
            pack(subtree)
            for subtree in tree
        ])
    else:
        raise Exception('invalid tree type {}'.format(type(tree)))

def unpack(vec, tree_spec):
    if isinstance(tree_spec, torch.Tensor):
        n = tree_spec.numel()
        return vec[:n].view(tree_spec.shape), n
    elif isinstance(tree_spec, list):
        subtrees = []
        i = 0
        for subtree_spec in tree_spec:
            subtree, n = unpack(vec[i:], subtree_spec)
            i += n
            subtrees.append(subtree)
        return subtrees, i
    else:
        raise Exception('invalid tree type {}'.format(type(tree_spec)))

def grad_1(f):
    def grad_f(x):
        return unpack(torch.autograd.functional.jacobian(
            lambda x_pack: f(unpack(x_pack, x)[0]),
            pack(x)
        ), x)[0]
    return grad_f

def grad_2(f):
    def grad_f(x):
        X = tree_map(lambda x: x.clone().requires_grad_(True), x)
        Y = f(X)
        Y.backward()
        dx = tree_map(lambda x: x.grad, X)
        y = Y.data
        return dx #, y
    return grad_f

def tree_add(a, b):
    return tree_map(operator.add, a, b)

def tree_sub(a, b):
    return tree_map(operator.sub, a, b)

def tree_mul(a, s):
    return tree_map(lambda x: x * s, a)

def main():
    x = torch.randn(100, 2)
    y = 3 * x + 2

    model = Compose([
        Affine(x.shape[-1], 5),
        Lambda(torch.relu),
        Affine(5, y.shape[-1]),
    ])

    def loss_fn(w):
        return (y - model.apply(w, x)).square().mean()

    grad_loss_fn = grad_1(loss_fn)

    lr = 1e-2
    w = model.init()
    while True:
        loss = loss_fn(w)
        print(loss)
        dw = grad_loss_fn(w)
        w = tree_sub(w, tree_mul(dw, lr))

if __name__ == '__main__':
    main()
```

To maintain purity with respect to state and randomness, one could pass additional `state` and `rng` arguments down the model structure.

**Comment by LothairKizardjian** [comment]
@ain-soph Hello, sorry to dig up this post but i was wondering if this would work : 
`
import torch
from torch.autograd.functional import hessian
from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)

def loss(*params):
    out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp)
    return torch.nn.CrossEntropyLoss(out, torch.zeros(len(inp), dtype=torch.long))

names = list(n for n, _ in model.named_parameters())
print(hessian(loss, tuple(model.parameters())))
`

**Comment by LothairKizardjian** [comment]
@ain-soph Thank you ! I was not aware of its existence !

**Comment by wagenaartje** [comment]
@LothairKizardjian @ain-soph how would one get the hessian using `functorch` instead of `autograd.functional`?

**Comment by zou3519** [comment]
> And is it possible to calculate the Hessian without re-calculating some loss? I already have access to the loss, don't want to recompute it just to get the Hessian.

Computing the loss is really inexpensive compared to the Hessian, so it's not the worst thing in the world. There is not really a way to avoid re-calculating the loss yet.

> how would one get the hessian of a loss w.r.t. model parameters using functorch instead of autograd.functional

```py
import torch
import functorch
from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)
criterion = torch.nn.CrossEntropyLoss()

def loss(params):
    out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp)
    return criterion (out, torch.zeros(len(inp), dtype=torch.long))

names = list(n for n, _ in model.named_parameters())
print(functorch.hessian(loss)(tuple(model.parameters())))
```

**Comment by ain-soph** [comment]
@zou3519 @wagenaartje @LothairKizardjian Sorry for not making a very clear guidance for `functorch`. I think the recommended way in `functorch` is to use `make_functional` instead of using `_stateless.functional_call` (From my understanding, they basically do the same thing.)

Of course, I want to listen to @zou3519 's comments, since he is the maintainer, who shall recommend the best and comfortable standard to do such things.

```python3
import torch
import functorch
# from torch.nn.utils import _stateless

model = torch.nn.Linear(2, 2)
inp = torch.rand(1, 2)
criterion = torch.nn.CrossEntropyLoss()

func, func_params = functorch.make_functional(model)  # New


def loss(params):
    # out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp)
    out = func(params, inp)  # New
    return criterion(out, torch.ones(len(inp), dtype=torch.long))


# names = list(n for n, _ in model.named_parameters())
# print(functorch.hessian(loss)(tuple(model.parameters())))
print(functorch.hessian(loss)(func_params))  # New

```

**Comment by MAGDFL** [comment]
@ain-soph 

I am not sure why it doesn't work for me when I tried to compute the hessian of a specific layer only with respect to its parameters as follows:

```
import torch
import functorch
from torch.nn.utils import _stateless

model = Net()
inputs = inputs
criterion = torch.nn.CrossEntropyLoss()



def loss(params):
    out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inputs)
    return criterion (out, labels)

names = list(n for n, _ in model.named_parameters())
print(functorch.hessian(loss)(tuple(model.fc3.parameters())))

```

Any ideas or tips would be appreciated!

**Comment by ain-soph** [comment]
@MAGDFL Your `names` contains all parameters, which are wrong. You are only using `params=model.fc3.parameters()`, which is not consistent with `names`.

**Comment by MAGDFL** [comment]
@ain-soph 
Thank you so much for the tips. It's working now but it always returns the hessian with zero values! 
This is how I edited it. 
```
import torch
import functorch
from torch.nn.utils import _stateless

class MyNeuralNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = torch.nn.Linear(10, 20)
        self.layer2 = torch.nn.Linear(20, 10)
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x

model = MyNeuralNetwork().to(device)
criterion = torch.nn.CrossEntropyLoss()
inputs = torch.randn(1, 10).to(device)
target=torch.ones(len(inputs), dtype=torch.long).to(device)



def loss(params):
    out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inputs)
    return criterion (out, target)

names = list(n for n, _ in model.layer2.named_parameters())
print(functorch.hessian(loss)(tuple(model.layer2.parameters())))
```

It is a little bit weird as it works well for the full network!

**Comment by ain-soph** [comment]
@MAGDFL You `names` are still incorrect, since it's missing the prefix.

```python3
names = list(n for n, _ in model.layer2.named_parameters(prefix='layer2'))
```

**Comment by albanD** [comment]
I think we can add a strict mode similar to the one we have for load_state_dict yes !

**Comment by Happy2Git** [comment]
> @QiyaoWei No, that's not the way to use `_stateless.functional_call`. `functional_call` requires the first argument to be your model.
> 
> loss function should be passed to `hessian` rather than `functional_call`
> 
> Try following:
> 
> ```python
> import torch
> from torch.autograd.functional import hessian
> from torch.nn.utils import _stateless
> 
> model = torch.nn.Linear(2, 2)
> inp = torch.rand(1, 2)
> 
> 
> def loss(*params):
>     out: torch.Tensor = _stateless.functional_call(model, {n: p for n, p in zip(names, params)}, inp)
>     return out.square().sum()
> 
> 
> names = list(n for n, _ in model.named_parameters())
> print(hessian(loss, tuple(model.parameters())))
> ```

Thanks for your contribution!

**Comment by Happy2Git** [comment]
> 

Thanks for your contribution!
