### ISSUE TITLE
falied to convert to onnx

### ISSUE THREAD

**Issue by jefferyZhan** [pytorch/pytorch#49212]
## 🐛 Bug

when I tried to convert the TSN model to onnx, an runtime error occured, it reported that `RuntimeError: ONNX export failed: Couldn't export Python operator SegmentConsensus`
I find this function code, and it occured in this sentence `return SegmentConsensus().apply(input)`
and the "SegmentConsensus" function is: 
`class SegmentConsensus(torch.autograd.Function):
@staticmethod
def forward(self, input_tensor):
self.shape = input_tensor.size()
output = input_tensor.mean(dim=1, keepdim=True)
return output
@staticmethod
def backward(self,grad_output):
grad_in = grad_output.expand(self.shape) / float(self.shape[1])
return grad_in`

## Expected behavior

I hope someone can help me find the operator, function , or method resulting in this error, so I can continue my work.Thanks!

## Relared Environment
onnx:1.8.0
protobuf:3.13.0
pytorch:1.6.0
torchvision:0.7.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Please check the ONNX doc in PyTorch: https://pytorch.org/docs/master/onnx.html. I don't think this op is supported. You will have to export this possibly as a custom operator to convert this to ONNX.
