### ISSUE TITLE
Refactor: Don't specify CUDA complete version manually in Windows build scripts.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#49219]
## 🚀 Feature
Don't specify CUDA complete version manually in Windows build script.

## Motivation

So far, we have to update the CUDA complete version manually in several scripts. It increases the possibility of making mistakes.
For example, we take a lot time to debug https://github.com/pytorch/pytorch/pull/47794.
And yesterday, I find we're  still using magma 110 to build CUDA 11.1.
https://github.com/pytorch/pytorch/blob/59e822026c4ddbbdc26266f0fccdd14393098c42/.jenkins/pytorch/win-test-helpers/installation-helpers/install_magma.bat#L3-L12

## Pitch

 It'd better to pass the right cuda_compelete_version to build scripts.

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
> And yesterday, I find we're still using magma 110 to build CUDA 11.1.

Thanks for figuring that out. Luckily, it doesn't affect our binary jobs.
