### ISSUE TITLE
discrepancy between text in "torch.rst" & "_init_.py

### ISSUE THREAD

**Issue by pradeepjag** [pytorch/pytorch#49228]
## 📚 Documentation

The text in file "_init_.py has been updated to bring more clarity to text. But a similar text is not updated in the documentation file "torch.rst". I have attached a screenshot highlighting the text.
![torch rst](https://user-images.githubusercontent.com/53624748/101893782-3b0c6500-3bcb-11eb-846b-95b16c6c4710.JPG)

cc @jlin27 @mruberry

**Comment by zou3519** [comment]
We'd accept a PR to fix this.

**Comment by mruberry** [comment]
cc @anjali411, who expressed an interest in revising the `torch` page's documentation

**Comment by anjali411** [comment]
I might not get to this for a while, so if anyone who gets to this before me should feel free to take on this task.

**Comment by jonykarki** [comment]
I'm very new to contributing to open source but I'd still like to try to take on this task. Thank you.
