### ISSUE TITLE
Minor grammatical error in README.md

### ISSUE THREAD

**Issue by Gladiator07** [pytorch/pytorch#49221]
## 📚 Documentation
In last section of README file (The Team), minor grammatical error in the sentence, "Hugh is a valuable contributor to the Torch community and has helped with many things Torch and PyTorch."
Instead it should be, "Hugh is a valuable contributor to the Torch community and has helped with many things in Torch and PyTorch."

cc @jlin27 @mruberry

**Comment by zou3519** [comment]
I don't think this is a grammatical error. The  "all things X" ("many things X") is an expression: https://english.stackexchange.com/questions/252633/what-does-all-things-x-mean
