### ISSUE TITLE
Torch.unique_consecutive(x.requires_grad_(True)) fails

### ISSUE THREAD

**Issue by YonyBresler** [pytorch/pytorch#49235]
## To Reproduce

One liner to reproduce the bug:
`torch.unique_consecutive(torch.rand(4).requires_grad_(True))`

output:

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-2466c800cbcf> in <module>
----> 1 torch.unique_consecutive(torch.ones(4).requires_grad_(True))

/opt/conda/envs/racial_bias/lib/python3.6/site-packages/torch/_jit_internal.py in fn(*args, **kwargs)
    265             return if_true(*args, **kwargs)
    266         else:
--> 267             return if_false(*args, **kwargs)
    268 
    269     if if_true.__doc__ is None and if_false.__doc__ is not None:

/opt/conda/envs/racial_bias/lib/python3.6/site-packages/torch/_jit_internal.py in fn(*args, **kwargs)
    265             return if_true(*args, **kwargs)
    266         else:
--> 267             return if_false(*args, **kwargs)
    268 
    269     if if_true.__doc__ is None and if_false.__doc__ is not None:

/opt/conda/envs/racial_bias/lib/python3.6/site-packages/torch/functional.py in _consecutive_return_output(input, return_inverse, return_counts, dim)
    830             return _unique_consecutive_impl(input, return_inverse, return_counts, dim)
    831 
--> 832     output, _, _ = _unique_consecutive_impl(input, return_inverse, return_counts, dim)
    833     return output
    834 

/opt/conda/envs/racial_bias/lib/python3.6/site-packages/torch/functional.py in _unique_consecutive_impl(input, return_inverse, return_counts, dim)
    743                 return_counts=return_counts, dim=dim)
    744     output, inverse_indices, counts = _VF.unique_consecutive(  # type: ignore
--> 745         input, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
    746     return output, inverse_indices, counts
    747 

RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1607370116979/work/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 
`

## Expected behavior

`In [12]: torch.unique_consecutive(torch.rand(4).round().requires_grad_(False))`
`Out[12]: tensor([0., 1., 0., 1.])`

Whether gradient is computed or not, the output should be the same.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080

Nvidia driver version: 455.45.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] pytorch-lightning==1.0.8
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      2.21                        mkl    conda-forge
[conda] cudatoolkit               10.1.243             h036e899_6    conda-forge
[conda] libblas                   3.8.0                    21_mkl    conda-forge
[conda] libcblas                  3.8.0                    21_mkl    conda-forge
[conda] liblapack                 3.8.0                    21_mkl    conda-forge
[conda] liblapacke                3.8.0                    21_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.19.4           py36h8732dcd_1    conda-forge
[conda] pytorch                   1.7.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch-lightning         1.0.8              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.8.2                py36_cu101    pytorch

```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by albanD** [comment]
The fix for this one is the same as the one that has been submitted for `count_nonzero`, we would be happy to accept a PR for that!

**Comment by narain1** [comment]
even unique has the same problem and does`nt support unique on requires grad

**Comment by albanD** [comment]
This is weird. The signature for them look ok to me here: https://github.com/pytorch/pytorch/blob/869081961824dfb10ee944145c3a8d435571c53b/tools/autograd/derivatives.yaml#L1157-L1171

**Comment by narain1** [comment]
I guess this issue can be closed it is working fine with the nightly version
