### ISSUE TITLE
[Feature Request] BMM for sparse tensors

### ISSUE THREAD

**Issue by pclucas14** [pytorch/pytorch#4925]
Hi, 

would it be possible to extend batch matrix multiplication to sparse tensors? If not, would it be feasible to add basic reshaping ops to sparse tensors such as view or expand ? This way, maybe there could be a workaround using torch.mm  with some tensor reshaping. 

Many Thanks, 
Lucas

**Comment by pclucas14** [comment]
bump!

**Comment by weiyangfb** [comment]
closing this since it is a dups of https://github.com/pytorch/pytorch/issues/5672, please feel to leave comments

**Comment by pclucas14** [comment]
Lol 4 years later, still googling the same things
