### ISSUE TITLE
Implement AVX2-vectorized sigmoid for floats

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#4929]
PyTorch includes avx_mathfun.h, which includes an 8-way vectorized implementation of `exp` (exp256_ps). We'd like to use that to implement a vectorized sigmoid function (accessible from torch using `torch.sigmoid`). Currently the sigmoid function is not vectorized.

To get started, look into how other vectorized functions, like cadd, are implemented:

Actual implementation:
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/vector/AVX2.c
Code to figure out whether AVX2 is availiable dynamically and dispatch:
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/generic/THVectorDispatch.c#L47
Code that implements non-vectorized default:
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/generic/THVectorDefault.c#L37

Current place where sigmoid (non-vectorized) is created (you will need to modify this to do correct AVX2 dispatch):
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/generic/THVectorDefault.c#L238

@vedanuj

**Comment by vedanuj** [comment]
Requested a PR for this #5010

**Comment by albanD** [comment]
The associated PR seems to have been merged
