### ISSUE TITLE
[docker] Add Dockerfiles to the repo corresponding to the official Dockerhub images

### ISSUE THREAD

**Issue by ddelange** [pytorch/pytorch#49297]
## 🚀 Feature

As @seemethere uploads both CUDA devel and runtime images to Dockerhub with most releases, I would like to use/inspect/modify the corresponding Dockerfiles instead of pulling from Dockerhub as is. 

## Motivation

The current Dockerfile was last edited 8 months ago: https://github.com/pytorch/pytorch/blob/v1.7.1/docker/pytorch/Dockerfile

Recent Dockerfiles used for e.g the recent CUDA11 images, or any of the runtime images seem to be missing in source.

This threw me back when trying to create a runtime image of pytorch v1.6.1 (only 1.6.0 on Dockerhub, uses 3.7, despite the Dockerfile suggesting 3.8) that runs on py3.8 and is as small as the official ones. 

Being able to instinctively find the Dockerfile in source corresponding to the official Dockerhub images would make the lives of pytorch users that want to build/host their own pytorch images quickly a lot easier.

## Pitch

[Similar to tensorflow](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/tools/dockerfiles), there could be runtime and devel Dockerfiles added, updated before release if needed, with a simle README on how to build from source. From the tags in Dockerhub, it would automatically become easy to navigate to the corresponding Dockerfile. The link above is the first link mentioned in their [Dockerhub overview](https://hub.docker.com/r/tensorflow/tensorflow/).

**Comment by vadimkantorov** [comment]
Like much! Related: https://github.com/pytorch/pytorch/issues/32030

**Comment by glaringlee** [comment]
cc @malfet

**Comment by seemethere** [comment]
These images aren't necessarily missing from source, they're built with build args that are derived from the `docker.Makefile`:

```
make -f docker.Makefile BUILD_TYPE=official devel-image runtime-image
```

I do agree that the documentation surrounding this could be a bit better and perhaps we could have better methods around locking down the versions for the specific packages so that they're easier to recreate if you need to recreate an image from source.

Current documentation for building the images yourself (for `v1.7.1`) can be found here: https://github.com/pytorch/pytorch/tree/v1.7.1#building-the-image-yourself

**Comment by abitrolly** [comment]
Maybe updating https://hub.docker.com/r/pytorch/pytorch/ description to point to https://github.com/pytorch/pytorch#building-the-image-yourself can solve this issue?

And an explanation how these are released would also be good for understanding #67966

**Comment by ddelange** [comment]
Would agree that adding the link to the dockerhub description would fix this issue.

@seemethere what do you think? Is there a place I can PR or does a dockerhub admin need to do this?

**Comment by ddelange** [comment]
Is there a specific reason why docker builds only run on the initial minor releases? i.e. why is dockerhub missing `1.10.2` tags?

**Comment by abitrolly** [comment]
@ddelange because it is not automated #73531

**Comment by ddelange** [comment]
closing as stale / answered
