### ISSUE TITLE
About nn.Multiheadattention Implementation

### ISSUE THREAD

**Issue by Zrealshadow** [pytorch/pytorch#49296]
## 📚 Documentation

I found `nn.Multiheadattention.forward` method using `nn.functional.multi_head_attention_forward`

However, I could not find the doc about implementation of `nn.functional.multi_head_attention_forward`

Anyone knows the source code of `nn.functional.multi_head_attention_forward`

```python
 def forward(self, query, key, value, key_padding_mask=None,
                need_weights=True, attn_mask=None):
        if not self._qkv_same_embed_dim:
            return F.multi_head_attention_forward(
                query, key, value, self.embed_dim, self.num_heads,
                self.in_proj_weight, self.in_proj_bias,
                self.bias_k, self.bias_v, self.add_zero_attn,
                self.dropout, self.out_proj.weight, self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask, need_weights=need_weights,
                attn_mask=attn_mask, use_separate_proj_weight=True,
                q_proj_weight=self.q_proj_weight, k_proj_weight=self.k_proj_weight,
                v_proj_weight=self.v_proj_weight)
        else:
            return F.multi_head_attention_forward(
                query, key, value, self.embed_dim, self.num_heads,
                self.in_proj_weight, self.in_proj_bias,
                self.bias_k, self.bias_v, self.add_zero_attn,
                self.dropout, self.out_proj.weight, self.out_proj.bias,
                training=self.training,
                key_padding_mask=key_padding_mask, need_weights=need_weights,
                attn_mask=attn_mask)
```

---

By the way, there is a tiny carelessness in display of doc of `nn.Multiheadattention`

I circle it out

![image](https://user-images.githubusercontent.com/30857435/102014433-e286c480-3d90-11eb-8d6e-658cd4a65ce0.png)

clearly, forget to add escape character when writing Mathematical formula in doc string

**Comment by mariosasko** [comment]
Hi,

here is the [link](https://github.com/pytorch/pytorch/blob/dc4db95540da06623c747bf0f2bf9f4af3d2925a/torch/nn/functional.py#L4026) to the source code of `torch.nn.functional.multi_head_attention_forward`. Feel free to create a PR to fix the docs.

**Comment by Zrealshadow** [comment]
Thank you for your relpy !
In source code, I found this mistake is fixed. 
The offical doc did not update

**Comment by mariosasko** [comment]
To see the current state, choose master version in the top-left corner on the docs page. This will become stable once PyTorch 1.7.2 gets released. There was a PR two weeks ago that should've have fixed it but it didn't.

**Comment by Zrealshadow** [comment]
Thank you for your further explaination. 
I commit the [PR](https://github.com/pytorch/pytorch/pull/49329#issue-539479284) to fix the doc string
But I found  the Facebook CLA Check is suspended. :hear_no_evil:
