### ISSUE TITLE
Can't build PyTorch to support Metal

### ISSUE THREAD

**Issue by windmaple** [pytorch/pytorch#49308]
## To Reproduce

I'm following the instruction [here](https://github.com/pytorch/tutorials/blob/master/prototype_source/ios_gpu_workflow.rst) but couldn't get through the first step of compilation. I'm using HEAD and did a fresh recursive clone of the repo before compilation.

> USE_PYTORCH_METAL=ON python setup.py install --cmake

I'm getting compilation error:

> [2220/4868] Running gen_proto.py on onnx/onnx.in.proto
Processing /Users/wind/Desktop/project-src/pytorch/third_party/onnx/onnx/onnx.in.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx_onnx_torch-ml.proto3
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-ml.pb.h
generating /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx_pb.py
[2225/4868] Running gen_proto.py on onnx/onnx-operators.in.proto
Processing /Users/wind/Desktop/project-src/pytorch/third_party/onnx/onnx/onnx-operators.in.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-operators_onnx_torch-ml.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-operators_onnx_torch-ml.proto3
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-operators-ml.pb.h
generating /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx_operators_pb.py
[2227/4868] Running gen_proto.py on onnx/onnx-data.in.proto
Processing /Users/wind/Desktop/project-src/pytorch/third_party/onnx/onnx/onnx-data.in.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-data_onnx_torch.proto
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-data_onnx_torch.proto3
Writing /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx-data.pb.h
generating /Users/wind/Desktop/project-src/pytorch/build/third_party/onnx/onnx/onnx_data_pb.py
[2229/4868] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o
FAILED: third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Users/wind/miniconda2/envs/python3.7/include/python3.7m -isystem /Users/wind/miniconda2/envs/python3.7/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/usr/local/include -Wnon-virtual-dtor -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -fPIC   -std=gnu++11 -MD -MT third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o -MF third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o.d -o third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/defs.cc.o -c ../caffe2/onnx/torch_ops/defs.cc
In file included from ../caffe2/onnx/torch_ops/defs.cc:4:
In file included from ../caffe2/onnx/torch_ops/./schema.h:4:
In file included from ../third_party/onnx/onnx/defs/schema.h:21:
In file included from ../third_party/onnx/onnx/defs/data_type_utils.h:11:
In file included from ../third_party/onnx/onnx/onnx_pb.h:50:
In file included from third_party/onnx/onnx/onnx-ml.pb.h:2:
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers. Please update
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:14:2: error: your headers.
#error your headers.
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:348:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:843:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1029:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1314:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1513:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1833:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2002:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2169:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2478:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2633:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3158:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3347:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3543:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3690:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3847:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3989:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[2236/4868] Building CXX object third_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8DepthwiseAvx2.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/Users/wind/Desktop/project-src/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/Users/wind/Desktop/project-src/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/Users/wind/Desktop/project-src/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/wind/miniconda2/envs/python3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

## Expected behavior

Well, it should compile

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): dc4db95540da06623c747bf0f2bf9f4af3d2925a
 - OS (e.g., Linux): macOS 10.15.7, Xcode 12.2
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @seemethere @walterddr

**Comment by skyline75489** [comment]
Well as the error message pointed out, are you using a newer version of protoc when compiling onnx? Perhaps you're using protoc from homebrew?

**Comment by windmaple** [comment]
What's the version requirement for protobuf? I have tried setting both libprotoc 3.10.0 and 3.11.4 in my PATH and neither works.

**Comment by skyline75489** [comment]
Can you try setting `BUILD_CUSTOM_PROTOBUF` to use the protobuf included in submodules?

**Comment by windmaple** [comment]
Just tried 'BUILD_CUSTOM_PROTOBUF=1 USE_PYTORCH_METAL=ON python setup.py install --cmake' and still got the same error

> [21/2150] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/schema.cc.o
FAILED: third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/schema.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Users/weiwe/miniconda2/envs/python3.7/include/python3.7m -isystem /Users/weiwe/miniconda2/envs/python3.7/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/usr/local/include -Wnon-virtual-dtor -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -fPIC   -std=gnu++11 -MD -MT third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/schema.cc.o -MF third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/schema.cc.o.d -o third_party/onnx/CMakeFiles/onnx.dir/__/__/caffe2/onnx/torch_ops/schema.cc.o -c ../caffe2/onnx/torch_ops/schema.cc
In file included from ../caffe2/onnx/torch_ops/schema.cc:1:
In file included from ../caffe2/onnx/torch_ops/./schema.h:4:
In file included from ../third_party/onnx/onnx/defs/schema.h:21:
In file included from ../third_party/onnx/onnx/defs/data_type_utils.h:11:
In file included from ../third_party/onnx/onnx/onnx_pb.h:50:
In file included from third_party/onnx/onnx/onnx-ml.pb.h:2:
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers. Please update
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:14:2: error: your headers.
#error your headers.
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:348:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:843:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1029:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1314:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1513:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1833:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2002:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2169:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2478:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2633:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3158:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3347:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3543:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3690:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3847:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3989:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[22/2150] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o
FAILED: third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /Users/weiwe/miniconda2/envs/python3.7/include/python3.7m -isystem /Users/weiwe/miniconda2/envs/python3.7/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/usr/local/include -Wnon-virtual-dtor -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -fPIC   -std=gnu++11 -MD -MT third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o -MF third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o.d -o third_party/onnx/CMakeFiles/onnx.dir/onnx/checker.cc.o -c ../third_party/onnx/onnx/checker.cc
In file included from ../third_party/onnx/onnx/checker.cc:1:
In file included from ../third_party/onnx/onnx/checker.h:6:
In file included from ../third_party/onnx/onnx/defs/function.h:11:
In file included from ../third_party/onnx/onnx/defs/attr_proto_util.h:6:
In file included from ../third_party/onnx/onnx/onnx-operators_pb.h:6:
In file included from ../third_party/onnx/onnx/onnx_pb.h:50:
In file included from third_party/onnx/onnx/onnx-ml.pb.h:2:
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers. Please update
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:14:2: error: your headers.
#error your headers.
 ^
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:348:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:843:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1029:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1314:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1513:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:1833:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2002:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2169:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2478:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:2633:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3158:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3347:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3543:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3690:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3847:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
third_party/onnx/onnx/onnx_onnx_torch-ml.pb.h:3989:111: error: only virtual member functions can be marked 'final'
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
                                                                                                              ^~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[26/2150] Building CXX object third_party/onnx/CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/Users/weiwe/Desktop/project-src/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/Users/weiwe/Desktop/project-src/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/Users/weiwe/Desktop/project-src/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/weiwe/miniconda2/envs/python3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

**Comment by skyline75489** [comment]
You may needo rm the entire `build` folder to clean the CMakeCaches, before trying to rebuild.

**Comment by windmaple** [comment]
Yeah, removed build folder but still no luck :(

**Comment by skyline75489** [comment]
Can you try `git submodule foreach git clean -xdf`?

**Comment by windmaple** [comment]
Unfortunately 'git submodule foreach git clean -xdf' didn't help here. I also tried cloning a fresh repo, still no luck. 

In addition, I tried to compile onnx directly using 

```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install
```

and it worked just fine.

**Comment by windmaple** [comment]
I ended up switching to a Linux machine to build it. Now I'm pretty sure it's because of weird conflict protobuf lib versions, which are not worth looking into.
