### ISSUE TITLE
return torch._C._cuda_getDeviceCount() > 0 CUDA is not available

### ISSUE THREAD

**Issue by Malithi-gif** [pytorch/pytorch#49328]
vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

I already installed Cuda, How this error fix?

**Comment by glaringlee** [comment]
same as #49325, close this one.
