### ISSUE TITLE
torch._C._cuda_init() RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

### ISSUE THREAD

**Issue by Malithi-gif** [pytorch/pytorch#49327]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

How I fix this error?

cc @ngimel

**Comment by glaringlee** [comment]
@Malithi-gif 
Can you post which pytorch version you were using? And can you paste your code a bit so we can take a look at? thx

**Comment by skyline75489** [comment]
Please do not repeatedly post issues. See #49325 .
