### ISSUE TITLE
return torch._C._cuda_getDeviceCount() > 0 CUDA is not available

### ISSUE THREAD

**Issue by Malithi-gif** [pytorch/pytorch#49325]
## 📚 Documentation

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

Why does this error happen?

cc @ngimel

**Comment by skyline75489** [comment]
What version of PyTorch are you using? Please do not just ignore the issue template. Fill in as much as information as possible to give everybody more context.

**Comment by Malithi-gif** [comment]
skyline75489 

I used the version of PyTorch 1.7.1. with Cuda 10.2  and also I tried to previous version pytorch==1.6.0 and torchvision==0.7.0 cudatoolkit=10.1 also. But error not emitted.

**Comment by skyline75489** [comment]
Can you try to copy and paste the output from our [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py) ?

**Comment by Malithi-gif** [comment]
skyline75489 okay. I will try

**Comment by Malithi-gif** [comment]
Collecting environment information...
PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[pip3] torch-geometric==1.6.1
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.7.0+cu101
[conda] Could not collect

skyline75489 output of the above script.

**Comment by Malithi-gif** [comment]
skyline75489 How to fix CUDA available: False, I'm a beginner at this type of code.

**Comment by skyline75489** [comment]
How did you install PyTorch packages? Did you use pip and the official PyPI.

Here's the thing. There's only CPU-only version of PyTorch in the official PyPI. You need to use conda to install the CUDA versoin. Or use 

```
pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

More info can be found [here](https://pytorch.org/get-started/locally/)

**Comment by skyline75489** [comment]
You see a lot of useful information can be found using the `collect_env` script, which is included as part of the direction in the issue template. For example you're using Windows 10 and the version of PyTorch is 1.7.1+**cpu**. The environements make a huge difference when it comes to unexepcted behaviours. Please always fill the issue template, no matter what the repo is.

**Comment by kshitij12345** [comment]
> I used the version of PyTorch 1.7.1. with Cuda 10.2 and also I tried to previous version pytorch==1.6.0 and torchvision==0.7.0 cudatoolkit=10.1 also. But error not emitted.

@Malithi-gif 
Could you check what driver version do you have installed on your system. Seems like the driver you have supports CUDA 10.1 but not the next versions.
![Screenshot from 2020-12-15 11-14-37](https://user-images.githubusercontent.com/19503980/102176142-d3a22e00-3ec6-11eb-894f-dc199b4571f7.png)

**Comment by Malithi-gif** [comment]
skyline75489, Thank you. I will try it.

**Comment by Malithi-gif** [comment]
kshitij12345, Are you talking about this

![image](https://user-images.githubusercontent.com/54534252/102176468-76f34300-3ec7-11eb-8ae8-7bb679e0026f.png)

**Comment by Malithi-gif** [comment]
> How did you install PyTorch packages? Did you use pip and the official PyPI?
> 
> Here's the thing. There's only CPU-only version of PyTorch in the official PyPI. You need to use conda to install the CUDA versoin. Or use
> 
> ```
> pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
> ```
> 
> More info can be found [here](https://pytorch.org/get-started/locally/).

I used the pip install.

**Comment by kshitij12345** [comment]
@Malithi-gif 
I am talking about the GPU driver version. 

On Linux systems, you can use `nvidia-smi` (see attached screenshot), which allows you to see the installed driver version. Also the top-right corner shows the highest supported CUDA by that driver.

I am not sure of the Windows equivalent for the same.

![Screenshot from 2020-12-15 11-41-32](https://user-images.githubusercontent.com/19503980/102177945-89bb4700-3eca-11eb-989b-21db5964a68b.png)

**Comment by Malithi-gif** [comment]
> @Malithi-gif
> I am talking about the GPU driver version.
> 
> On Linux systems, you can use `nvidia-smi` (see attached screenshot), which allows you to see the installed driver version. Also the top-right corner shows the highest supported CUDA by that driver.
> 
> I am not sure of the Windows equivalent for the same.
> 
> ![Screenshot from 2020-12-15 11-41-32](https://user-images.githubusercontent.com/19503980/102177945-89bb4700-3eca-11eb-989b-21db5964a68b.png)

I'm working on windows. And also I haven't GPU.

**Comment by Malithi-gif** [comment]
C:\Users\User\Anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
CUDA is not available

skyline75489 again it happens I try codes,
 
pip install torch===1.7.1 torchvision===0.8.2 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

**Comment by Malithi-gif** [comment]
C:\Users\User\Anaconda3\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

**Comment by skyline75489** [comment]
If you have no Nvidia GPU, there's no way you can use CUDA.

**Comment by kshitij12345** [comment]
If you don't have GPU, for CUDA choose `None`. That way you'll install the torch binary with smaller footprint (without CUDA bundled) and you won't see the warning.

**Comment by Malithi-gif** [comment]
> If you have no Nvidia GPU, there's no way you can use CUDA.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by skyline75489** [comment]
That does not mean anything useful. You'll need CUDA-compatible GPU by NVIDIA together with CUDA-enabled PyTorch, if you want to use CUDA. If you just want to elimate the warning, do as @kshitij12345 pointed out and install the CPU version.

**Comment by Malithi-gif** [comment]
> If you don't have GPU, for CUDA choose `None`. That way you'll install the torch binary with smaller footprint (without CUDA bundled) and you won't see the warning.

Okay, I will do that. Thank you

**Comment by Malithi-gif** [comment]
> That does not mean anything useful. You'll need CUDA-compatible GPU by NVIDIA together with CUDA-enabled PyTorch, if you want to use CUDA. If you just want to elimate the warning, do as @kshitij12345 pointed out and install the CPU version.

Okay. I will try it. Thank you

**Comment by JohnTesla** [comment]
**Please help me too:**
(env) jag@Aigen:/media/jag/NEU/3PAX/ubuntu-webui$ pip list | grep torch
pytorch-triton     2.1.0+440fd1bf20        
torch              2.1.0.dev20230626+cu121 
torchaudio         2.1.0.dev20230626+cu121 
torchvision        0.16.0.dev20230626+cu121
(env) jag@Aigen:/media/jag/NEU/3PAX/ubuntu-webui$ python launch.py
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Traceback (most recent call last):
  File "launch.py", line 38, in <module>
    main()
  File "launch.py", line 29, in main
    prepare_environment()
  File "/media/jag/NEU/3PAX/ubuntu-webui/modules/launch_utils.py", line 257, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
(env) jag@Aigen:/media/jag/NEU/3PAX/ubuntu-webui$
