### ISSUE TITLE
OpInfo-based testing for JIT consistency fails for custom op.output_func

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#49326]
OpInfo-based `test_variant_consistency_jit` fails when `op.output_func` returns a different number of outputs than `op.get_op`. For example using `output_func=itemgetter(1)` for op returning a tuple with two elements gives with `TypeError: iteration over a 0-d tensor` at [`check_output_types`](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_jit.py#L20).
The reason is that types are obtained from the `op_get` instead of `output_func` 
`func.last_graph` is constructed here https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/jit_metaprogramming_utils.py#L301

cc @mruberry @VitalyFedyunin @walterddr @gmagogsfm

**Comment by gmagogsfm** [comment]
@Lilyjjo Is this related to recent migration?

**Comment by mruberry** [comment]
@gmagogsfm Yep. The test just needs to be updated to handle functions with multiple outputs.

**Comment by Lilyjjo** [comment]
Closed with PR #50775
