### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by sunamber2** [pytorch/pytorch#49330]
I am trying to download pytorch on windows ten and this pops up in anaconda when I try to do it. Does anyone know how to fix this.

(base) C:\Users\sunam>conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.2
  - pytorch
  - torchaudio

Current channels:

  - https://conda.anaconda.org/pytorch/win-32
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/win-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-32
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

cc @malfet @seemethere @walterddr

**Comment by seemethere** [comment]
We do not currently support 32bit windows and have no plans to support 32bit windows as of now.

Sorry for the inconvenience this may cause for your workflows but you may be able to build pytorch from source using https://github.com/pytorch/pytorch#from-source

Going to close this since we have no plans to officially support 32bit windows.
