### ISSUE TITLE
`IterableDataset` missing from `torch.utils.data.__init__.pyi`

### ISSUE THREAD

**Issue by bryant1410** [pytorch/pytorch#49361]
## To Reproduce

A linter yields that it can't find `IterableDataset` when imported, but it's actually there:

```python
from torch.utils.data import IterableDataset
```

## Expected behavior

No error by the linter.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.4
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by glaringlee** [comment]
@bryant1410 
Can you tell us more on how you use the linter?
which linter? where you run it, root dir or somewhere else? It would be easier for us to look into if you can provide some simple code to reproduce this issue.

I am using mypy + flake8, no lint error for me though.

**Comment by bryant1410** [comment]
It was PyCharm, but I found it was because there was a stalled cached file `torch/utils/data/__init__.pyi` that doesn't exist anymore. The problem was in that file, regardless of the linter, but actually it doesn't exist anymore after I remove the cache and resync'd (I'm using a remote interpreter).

So I'm closing this. Sorry for the noise!
