### ISSUE TITLE
Nightly pipeline failures for CUDA 11.0, Conda

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#49375]
All nightly builds for conda on CUDA 11 are currently broken due to https://github.com/conda/conda-package-handling/issues/71

Downgrading `conda_package_handling` to `v1.6.0` appears to resolve the issue but that seems to be a solution that doesn't feel very long term.

Creating this issue as a tracking issue until we are able to publish CUDA 11.0 conda binaries for our nightlies

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @walterddr

**Comment by seemethere** [comment]
So after #49434 we can build the binaries but installation of the binaries is failing.

I guess a more permanent solution would be to:

1. Fix this on the `conda-package-handling` side
2. Reduce the binary size to the point where the bugged `conda-package-handling` can handle it.

**Comment by ezyang** [comment]
It might be easiest to diagnose the problem in upstream and submit a PR directly. Quansight might be able to help, if this is high enough priority.

**Comment by seemethere** [comment]
@rgommers @mattip Is it possible for someone at Quansight can take a look at how to help the `conda-package-handling` team resolve this upstream?

**Comment by rgommers** [comment]
@seemethere sure, I'll find a volunteer to resolve this.

**Comment by rgommers** [comment]
It's labelled for `1.8.0` - do you need it before the branch cut, or is there some more time.

**Comment by seemethere** [comment]
We have some time for this (i.e. this can be outside of the 1.8 timeline), but it's definitely something we want to pin down quickly.

**Comment by rgommers** [comment]
> We have some time for this (i.e. this can be outside of the 1.8 timeline), but it's definitely something we want to pin down quickly.

Update: someone on our conda/packaging team will work on the upstream fix for this starting the second half of next week.

**Comment by rgommers** [comment]
https://github.com/conda/conda-package-handling/issues/71 is fixed now. The fix still needs to be released in the next `conda-package-handling` version.

**Comment by rgommers** [comment]
The `1.7.3` release with a fix for this problem is now available on conda-forge: https://anaconda.org/conda-forge/conda-package-handling. The `defaults` channel should be updated soon as well.

**Comment by rgommers** [comment]
It's now available in `defaults` as well:
```
$ conda search conda-package-handling
...
conda-package-handling           1.7.3  py39h27cfd23_1  pkgs/main           
conda-package-handling           1.7.3  py39h3811e60_0  conda-forge
```
That should be all here, closing the issue.

**Comment by rgommers** [comment]
Verification: at https://anaconda.org/pytorch-nightly/pytorch/files there are now packages, e.g. `linux-64/pytorch-1.9.0.dev20210415-py3.9_cuda11.1_cudnn8.0.5_0.tar.bz2`. And this succeeds:

```
$ conda create -n torchnightly
$ conda activate torchnightly
$ conda config --add channels conda-forge
$ conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-nightly
$ conda list torch
...
# Name                    Version                   Build  Channel
pytorch                   1.9.0.dev20210414 py3.6_cuda11.1_cudnn8.0.5_0    pytorch-nightly
torchaudio                0.9.0.dev20210414            py36    pytorch-nightly
torchvision               0.10.0.dev20210414      py36_cu111    pytorch-nightly
```
