### ISSUE TITLE
Improve compute precision coverage in test/ tests

### ISSUE THREAD

**Issue by csarofeen** [pytorch/pytorch#4940]
We should make it easier to change compute precision and tolerance in tests. We have been hitting issues on fp16 like:
https://github.com/pytorch/pytorch/pull/4611
https://github.com/pytorch/pytorch/issues/4752
https://github.com/pytorch/pytorch/issues/2435
and don't realize for a long time because we don't have tests setup to catch these scenarios.

**Comment by soumith** [comment]
@ailzhang said she'll work on this :)
