### ISSUE TITLE
use with torch.no_grad() has memory leakage issue with certain conditions

### ISSUE THREAD

**Issue by IFICL** [pytorch/pytorch#49401]
## 🐛 Bug

Using the resnet18 model to do inference, use `with torch.no_grad()` will increase a lot of memory usages when batch size is equal to some values. 

## To Reproduce

1. Run the code below with a single GPU with 11GB of memory
```python
import argparse
import numpy as np
import os
import sys
import time
from tqdm import tqdm
from collections import OrderedDict

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
import torchaudio
import torchvision


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def validation(args, pr, net, device='cuda'):
    import pdb; pdb.set_trace()
    batch_size = 1568
    net.eval()
    with torch.no_grad():
        for i in range(100):
            img = torch.rand(batch_size, 3, 64, 64).to(device)
            out = net(img)
    torch.cuda.empty_cache()
    return None

def train(args, pr, net, device='cuda'):
    import pdb; pdb.set_trace()
    net.train()
    batch_size = 1568
    for i in range(100):
        img = torch.rand(batch_size, 3, 64, 64).to(device)
        out = net(img)
    torch.cuda.empty_cache()
    return None

def main(args, device):
    # save dir
    gpus = torch.cuda.device_count()
    gpu_ids = list(range(gpus))

    # ----- Network ----- #
    net = torchvision.models.resnet18(pretrained=True, progress=True).to(device)
    net = nn.DataParallel(net, device_ids=gpu_ids)
    pr = None
    #  --------- Random or resume validation ------------ #
    res = validation(args, pr, net, device)
    res = train(args, pr, net, device)


if __name__ == '__main__':
    args = None
    main(args, DEVICE)

```

## Expected behavior
During the validation, I used `with torch.no_grad()` and it is supposed to use less GPU memory and compute faster. However, with batch size = 1568 specified, the memory usage during validation (`=10126MB`) will be much larger than training (`=6588MB`) . If I continue increasing batch size, the behavior seems to be normal while reducing batch size has the similar issue.  I wonder whether it's an inner bug of PyTorch or it's my coding problem.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 2080Ti
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @gqchen @pearu @nikitaved @fmassa @vfdev-5

**Comment by ezyang** [comment]
This is reminiscent of https://github.com/pytorch/pytorch/issues/45910 but in that bug we had AMP and I don't see this in your examle.

**Comment by ezyang** [comment]
marking high priority as there is a repro

**Comment by albanD** [comment]
@IFICL is the memory actually growing? Or just that the GPU memory usage as seen via `nvidia-smi` is higher?

**Comment by IFICL** [comment]
> @IFICL is the memory actually growing? Or just that the GPU memory usage as seen via `nvidia-smi` is higher?

Oh, I only just checked the GPU memory usage via `nvidia-smi`. Probably that's the reason?

**Comment by IFICL** [comment]
> This is reminiscent of #45910 but in that bug we had AMP and I don't see this in your example.

The weird thing is that it only increases memory usage and GPU-Util (%) a lot as seen via `nvidia-smi`.   But it won't have the `out of memory` issue.

**Comment by albanD** [comment]
Yes this is most likely because the caching allocator reserves more memory (to serve allocs faster) but the actual memory needed for all the Tensors is not bigger. So it is not a problem.

**Comment by gchanan** [comment]
we should do https://github.com/pytorch/pytorch/issues/42815.

**Comment by albanD** [comment]
Closing this as expected side effect of the caching allocator. It is not actually leaking memory.

Feel free to re-open if you have code that shows it is an actual leak.
