### ISSUE TITLE
PyTorch-ONNX export failed on ATen operator new_zeros 

### ISSUE THREAD

**Issue by nehasoni3** [pytorch/pytorch#49403]
Hey,
I am working to convert PyTorch-Tacotreon2 model into ONNX but getting this error:
UserWarning: ONNX export failed on ATen operator new_zeros because torch.onnx.symbolic_opset10.new_zeros does not exist
.format(op_name, opset_version, op_name))

KeyError: 'new_zeros'
Please do needful in this regard.[Link](https://github.com/onnx/onnx/issues/3165)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
Please provide a full repro including the model and export code and version numbers. 
Also, are you using the default ONNX export type or ATEN export type?

**Comment by nehasoni3** [comment]
> Please provide a full repro including the model and export code and version numbers.
> Also, are you using the default ONNX export type or ATEN export type?

Model's input: torch.Size([1, 5])
Model's output: torch.Size([1, 80, 50])

`torch.onnx.export(
        model,
        xs, 
        onnx_model_name,
        export_params = True,
        opset_version = 10,
        do_constant_folding = True,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes= {'input':[0],
                       'output':[0]})`


**```
/home/nehasoni/EspnetAnaconda/envs/ESPnet3.6/lib/python3.6/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator new_zeros because torch.onnx.symbolic_opset10.new_zeros does not exist
  .format(op_name, opset_version, op_name))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-270cf9cfc120> in <module>()
     32         format="%(asctime)s (%(module)s:%(lineno)d) %(levelname)s: %(message)s",
     33     )
---> 34     main()

<ipython-input-10-270cf9cfc120> in main()
     24         output_names = ['output'],
     25         dynamic_axes= {'input':[0],
---> 26                        'output':[0]})
     27     print("Done!")
     28
```**

**Comment by spandantiwari** [comment]
We have support for `new_zeros` as can be seen here: https://github.com/pytorch/pytorch/blob/2ec3e803eb5bd490cf93f3e725cc9f99df930bf5/torch/onnx/symbolic_opset9.py#L1667. 

Please update to the latest version of PyTorch (possibly even the nightly version) to get the latest updates. If you still see any issue, please reopen the issue with a proper repro (follow the bug template).
