### ISSUE TITLE
Roll-up: remaining TH functions

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#49421]
Not to be confused with THC/THNN/THCUNN, there the list is bigger. 
Based on native_functions.yaml

- [x] _th_put
- [x] _th_index_fill
- [x] _th_renorm
- [x] _th_trace
- [x] _th_nonzero
- [x] _th_gels
- [x] _th_potri #50269
- [x] _th_geqrf #56249
- [x] _th_orgqr #50502
- [x] _th_ormqr #57315
- [x] _multinomial_alias_setup
- [x] _th_histc
- [x] _th_var
- [x] _th_std

Most of them are linear algebra, should be ported.`_multinomial_alias_setup` is likely not used. We should get rid of them, we can do it!

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr

**Comment by nikitaved** [comment]
I would take `index_fill_`. Maybe it will fix https://github.com/pytorch/pytorch/issues/48230.

**Comment by ngimel** [comment]
>Regarding gels, there is torch.linalg.lstsq on its way. What would be the best way to handle it's port?

First port gels to ATen (similarly to how it's done for cholesky_inverse), then expose as `torch.linalg.lstsq`?

**Comment by nikitaved** [comment]
`torch.linalg.lstsq` is ready https://github.com/pytorch/pytorch/pull/49093. Afaik `gels` is only used by `torch.lstsq`. But calling `torch.linalg` from within `torch` is not a good idea, right? What about deprecation then?

**Comment by mruberry** [comment]
> `torch.linalg.lstsq` is ready #49093. Afaik `gels` is only used by `torch.lstsq`. But calling `torch.linalg` from within `torch` is not a good idea, right? What about deprecation or rewrapping?

Calling torch.linaln from the torch namespace seems fine. We should look at deprecating lstsq once torch.linalg.lstsq is implemented and has feature parity, and then we should consider it as part of our "doc deprecations" for linalg ahead of the 1.8 release.

**Comment by ngimel** [comment]
cc @heitorschueroff for _th_var, _th_std. There are implementations currently in ATen, but, as all non-vectorized reductions, they are much slower, so the attempt to directly swap implementations caused severe perf regressions.

**Comment by peterbell10** [comment]
LegacyFunctionsCPU is now gone, as of #58780.
