### ISSUE TITLE
test_cuda.py incorrectly skips test_cuda_init_race

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#49432]
## 🐛 Bug

In test_cuda.py, test_cuda_init_race is decorated to skip based on the variable `IS_SANDCASTLE`.

https://github.com/pytorch/pytorch/blob/16f4b0ed6b7f94f8afb89a75bc5c1a3c8c26202d/test/test_cuda.py#L1820-L1823

As written, the test is skipped for all but sandcastle.  If the TEST_MULTIGPU is satisfied, you get the following output:

```test_cuda_init_race (__main__.TestCuda) ... skipped 'Does not work on Sandcastle'```

git blame shows c3a5aed5f7f13f193c7444b1c7af12344e8ce964.

@malfet, please confirm if this change was intentional.  Thanks.

**Comment by ezyang** [comment]
This seems clearly inverted to me. Send a diff and I'll review it.

**Comment by malfet** [comment]
Sorry, this is not intentional, let me send a PR to address that.
