### ISSUE TITLE
undefined reference to ' ros::*** ' (with ROS)

### ISSUE THREAD

**Issue by wsx000** [pytorch/pytorch#49450]
## 🐛 Bug

i want to deploy yolo4 on ROS with libtorch(1.7.1)，but when i use catkin_make build my workspace, it's reported that:

```
CMakeFiles/detect_node.dir/src/detect_node.cpp.o: In function `main':
detect_node.cpp:(.text+0x118): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
detect_node.cpp:(.text+0x1aa): undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
detect_node.cpp:(.text+0x28d): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
detect_node.cpp:(.text+0x372): undefined reference to `ros::console::print(ros::console::FilterBase*, void*, ros::console::levels::Level, std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int, char const*)'
CMakeFiles/detect_node.dir/src/detect_node.cpp.o: In function `void ros::Publisher::publish<yolo4::box_<std::allocator<void> > >(yolo4::box_<std::allocator<void> > const&) const':
detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0xb0): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0x1dc): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0x2fa): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0x440): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0x56c): undefined reference to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)'
CMakeFiles/detect_node.dir/src/detect_node.cpp.o:detect_node.cpp:(.text._ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_[_ZNK3ros9Publisher7publishIN5yolo44box_ISaIvEEEEEvRKT_]+0x6a1): more undefined references to `ros::console::initializeLogLocation(ros::console::LogLocation*, std::string const&, ros::console::levels::Level)' follow
collect2: error: ld returned 1 exit status
yolo4/CMakeFiles/detect_node.dir/build.make:196: recipe for target '/home/curious/code/ROS/yolo4-ros/devel/lib/yolo4/detect_node' failed
make[2]: *** [/home/curious/code/ROS/yolo4-ros/devel/lib/yolo4/detect_node] Error 1
CMakeFiles/Makefile2:1064: recipe for target 'yolo4/CMakeFiles/detect_node.dir/all' failed
make[1]: *** [yolo4/CMakeFiles/detect_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

## To Reproduce

It is strange that this error only apper when i link ${catkin_LIBRARIES} whit ${TORCH_LIBRARIES} as following：

target_link_libraries(detect_node PUBLIC ${catkin_LIBRARIES} ${TORCH_LIBRARIES} ${OpenCV_LIBRARIES} TorchVision::TorchVision)

 meanwhile，in another test ，when i link ${catkin_LIBRARIES} only with ${OpenCV_LIBRARIES}，it‘s built successfully！so i think the problem may Relate to libtorch。but i don't know how to resolve it。

otherwise, i don't know if it's relative to the version of libtorch, because when i use libtorch1.5.1 in ros ,it was built successfully!

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.15.7

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 440.95.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchvision               0.8.2                py37_cu102    pytorch

## Additional context

cc @malfet @seemethere @walterddr

**Comment by ezyang** [comment]
Try reordering the order you specify the dependencies? Unfortunately none of us have used ROS and so we won't be able to help much.

**Comment by wsx000** [comment]
> Try reordering the order you specify the dependencies? Unfortunately none of us have used ROS and so we won't be able to help much.
thanks for your reply! i have solved this problem by changing the version of libtorch from 1.7.1 to 1.7.0 , and this worked well, i make my ROS workspace successfully then！

**Comment by Tartisan** [comment]
I solved this problem by using the cxx11 ABI instead of the "Pre cxx..." version.
