### ISSUE TITLE
[feature request] ROI Pooling as nn layers

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#4946]
Going through the code, I see there is already support for ROI Pooling CUDA kernels. It would be great to have support for various ROI Pooling operations as easy to add layers to facilitate research in object detection and semantic/instance segmentation.

Here is a live checklist:

- [ ] ROI Pooling
- [ ] Position Specific ROI Pooling
- [ ] ROI Align

**Comment by fmassa** [comment]
I was initially thinking about providing support for those in an external library, which could be imported and used together with pytorch.
This would make it easier for researchers to experiment by modifying the existing implementation, as if it was integrated in pytorch the user would need to recompile everything.
What do you think?

**Comment by varunagrawal** [comment]
I am not sure what you mean by `user would need to recompile everything`.
Wouldn't this be the case only if they were building PyTorch from source instead of using the package?

**Comment by Rizhiy** [comment]
+1

**Comment by varunagrawal** [comment]
@fmassa are you still working on this? I can try to take a crack at this hopefully this weekend.

**Comment by fmassa** [comment]
@varunagrawal yes, I have it working, both for `ROIPooling` and `ROIAlign`. I was planning on not integrating it to pytorch core, but instead to use the new JIT extensions added in https://github.com/pytorch/pytorch/pull/4842, and to showcase how one can extend PyTorch with C/CUDA without having to modify PyTorch code or writing messy build files.

**Comment by varunagrawal** [comment]
That seems really cool. I wasn't aware till now that PyTorch supported JIT compilation of C++ extensions.

The C backend already seems to have support for CUDA enabled ROI pooling. Would your extension basically do a C++ to C++ function call, exposed in Python? I'm still wrapping my head around the JIT features and the new ATen library. 😅

**Comment by fmassa** [comment]
@varunagrawal The current ROI pooling that is present in pytorch is broken. The extension is written in C++ using ATen, and uses pybind11 to expose it to python automatically.
So, it looks like
```c++
// roi_align.cpp
at::Tensor ROIAlign_forward(const at::Tensor& input,
                            const at::Tensor& rois,
                            const float spatial_scale,
                            const int pooled_height,
                            const int pooled_width,
                            const int sampling_ratio) {
 // implementation goes here
}

PYBIND11_MODULE(library, m) {
  m.def("roi_align_forward", &ROIAlign_forward, "ROIAlign_forward");
}
```

and on the python side, we have
```python
from torch.utils.cpp_extension import load
_C = load('library', ['roi_align.cpp'])

# can call _C.roi_align_forward straight away.
```

**Comment by ignacio-rocco** [comment]
Hi, 

I'm playing a bit with this. I downloaded the RoiPooling CPU version from [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/RoiPooling.cpp
), and wrote this little wrapper:

```
// roi_pool_binding.cpp
#include <pybind11/pybind11.h>
#include "RoiPoolingAten.cpp"

PYBIND11_MODULE(library, m) {
  m.def("RoiPooling2d_forward_cpu", &at::native::RoiPooling2d_forward_cpu, "RoiPooling2d_forward_cpu");
}
``` 
which I compile and load with:
```
from torch.utils.cpp_extension import load                              
_C = load(name='library',sources= ['roi_pool_binding.cpp'],verbose=True)
```
However, when I try to call the function by passing [FloatTensor,FloatTensor,int,int,float] I get the following error:

> TypeError: RoiPooling2d_forward_cpu(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: int, arg3: int, arg4: float) -> Tuple[at::Tensor, at::Tensor]

Any ideas?
Is your ATen+pybind extension available anywhere so I can test it?

Thanks!

**Comment by ignacio-rocco** [comment]
Ok, I figured it out, the wrapper was wrong (should not import pybind11 but torch headers). 

Correct example:
```
#include <torch/torch.h>
#include "RoiPooling.cpp"

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("RoiPooling2d_forward_cpu", &at::native::RoiPooling2d_forward_cpu, "RoiPooling2d_forward_cpu");
}

```

**Comment by youssef-osaro** [comment]
@fmassa are the implementations of ROI pool and align you have available somewhere?

**Comment by fmassa** [comment]
@youssef-osaro not yet, and they require the master branch. If you are looking for an implementation now, you can have a look at https://github.com/jwyang/faster-rcnn.pytorch/tree/master/lib/model/roi_align (they have ROIAlign and ROIPool)

**Comment by youssef-osaro** [comment]
Thanks for the link @fmassa. There are also kernels available in caffe2 (https://github.com/caffe2/caffe2/blob/master/caffe2/operators/roi_align_op.cu). Is it possible to use those in pytorch using the method you described above?

**Comment by ignacio-rocco** [comment]
@youssef-osaro Yes, it's possible, but you need to adapt it a bit. 

I ported caffe2/operators/roi_align_op.cu and it's working. I'll upload this soon.

**Comment by varunagrawal** [comment]
@fmassa if you need any help, please let me know.

**Comment by fmassa** [comment]
@varunagrawal thanks! I've finished wrapping those layers already, I'll release them as soon as I can.

**Comment by youssef-osaro** [comment]
@ignacio-rocco that would be great!

**Comment by apaszke** [comment]
BTW don't we want to put ROI pooling in vision? Is it used for anything else?

**Comment by fmassa** [comment]
We might want to push them to vision, they seem to have become quite standard for object detection that it might be worth it. I'm thinking about it.

**Comment by ignacio-rocco** [comment]
@youssef-osaro @varunagrawal I released a version of RoIAlign here https://github.com/ignacio-rocco/detectorch .

**Comment by edgarriba** [comment]
@fmassa any progress on that ?

**Comment by fmassa** [comment]
@edgarriba about adding layers in torchvision? I'll wait until v0.4 is released, and then some relevant layers will be added to torchvision, like `ROIPool`/`ROIAlign` and non-maximum suppression.

**Comment by varunagrawal** [comment]
Ideally we'd want all 3 as layers/operations. ROIPool and ROIAlign would be required to be layers, while I think having NMS as a utility function would be sufficient.

**Comment by edgarriba** [comment]
@fmassa and why not extending adaptive_pooling ? If I'm not mistaking it's kind of the same idea right ?

**Comment by varunagrawal** [comment]
As mentioned before, ROIPool and ROIAlign are pretty much only used in Object Detection and hence it makes sense to put them in torchvision rather than create new layers in the main pytorch library. Since @fmassa already has an implementation ready, I don't see the need to reinvent the wheel at this point. 

Also regarding the 0.4 release, @fmassa would it be possible to add the layers to torchvision now with the appropriate `WIP` warning? This way we can also catching bugs if any.

**Comment by fmassa** [comment]
@edgarriba it's somewhat similar (actually I implemented adaptive max pooling as a way of implementing ROI Pooling back in lua days), but a dedicated kernel is more efficient and we don't need to modify the api of adaptive pooling.

I can send a PR to torchvision with the layers, but I'll not merge it before v0.4 is released, as it will avoid lots of problems on the user side

**Comment by edgarriba** [comment]
@fmassa that sounds good

**Comment by siddharthm28** [comment]
@fmassa Thank you for the implementation of ROIPool/Align. You mention that this will be released as part of 0.4 for torchvision and I had a look at the current release.. it is 0.2.0 (released in Nov.27, 2017). Any idea how long before 0.3 and 0.4 ?

**Comment by varunagrawal** [comment]
The current PyTorch release is 0.3. 
On the master branch it is 0.4-alpha.

**Comment by siddharthm28** [comment]
Ah.. i understood it as torchvision 0.4 instead of pytorch 0.4. That sounds good.  Thanks !

**Comment by varunagrawal** [comment]
It seems like ROIPooling has been added as a backend in #3672.

**Comment by fmassa** [comment]
The `ROIPooling` in master is broken.

**Comment by varunagrawal** [comment]
@fmassa now that 0.4 is out, I'm going to close this and open a new issue regarding this on `torchvision`.

**Comment by isalirezag** [comment]
is ` Position Specific ROI Pooling` available in pure pytorch?

**Comment by isalirezag** [comment]
@edgarriba `warp_perspective` should works fine for the ROI pooling, but it would not help with 'Position Specific' part :/

**Comment by edgarriba** [comment]
@isalirezag I might not understand what do you mean with Position Specific. What do you expect as input/output ?

**Comment by isalirezag** [comment]
@edgarriba so position sensitive roi pooling was proposed in RFCN paper, it is ROI pooling + average pooling, the inputs are features, rois, number of classes, and the h and w of the deisre output, and the output is in shape of #rois x #classes x w x h
I tried to do it in this [post](https://discuss.pytorch.org/t/how-to-deal-with-backward-pass-in-pytorch-version-of-roi-pooling/28304), but have some issue in the backward pass

**Comment by fmassa** [comment]
@isalirezag might be an option to open an issue in https://github.com/facebookresearch/maskrcnn-benchmark/ and redirect feature requests that are specific to object detection there.

**Comment by isalirezag** [comment]
@fmassa I can do that , but my post may become closed again due to duplication since I already asked it in the discussion forum ([Link](https://discuss.pytorch.org/t/how-to-deal-with-backward-pass-in-pytorch-version-of-roi-pooling/28304))
it does not do anything fancier than roi pooling, i just have difficulty in the backward pass. can you please take a look at my question [here](https://discuss.pytorch.org/t/how-to-deal-with-backward-pass-in-pytorch-version-of-roi-pooling/28304) and lemme know what you think

**Comment by edgarriba** [comment]
@isalirezag what you describe is exactly what's happening to the example link I shared using `get_perspective_transform` + `warp_perspective`. Given rois defined by 4 corners you can extract and rectify the patch from the image or the features tensor of an arbitrary size with subpixel accuracy. For averaging, I guess you can use `adaptive_avg2d` or similar.

**Comment by isalirezag** [comment]
I see, 
@edgarriba does the torchgeometry works with pytorch 0.3.x?

**Comment by edgarriba** [comment]
@isalirezag I don't think so, we have been developing it with the new API
