### ISSUE TITLE
Possible Bug: Not able to Build on Mac OS

### ISSUE THREAD

**Issue by protonu** [pytorch/pytorch#49471]
## 🐛 Bug

Recently I can't build PyTorch from source any more.
I see the error:
https://gist.github.com/protonu/39ff928f8d47306eefdc5a4e9c27471a

This has:
Undefined symbols for architecture x86_64:
  "thread-local wrapper routine for c10::impl::raw_local_dispatch_key_set", referenced from:
      c10::impl::tls_local_dispatch_key_set() in BatchedFallback.cpp.o
      c10::impl::tls_local_dispatch_key_set() in ThreadLocalState.cpp.o
      c10::impl::tls_local_dispatch_key_set() in SparseTensor.cpp.o
      c10::impl::tls_local_dispatch_key_set() in Functions.cpp.o
      c10::impl::tls_local_dispatch_key_set() in RegisterBackendSelect.cpp.o
      c10::impl::tls_local_dispatch_key_set() in TensorMethods.cpp.o
      c10::impl::tls_local_dispatch_key_set() in TraceType_0.cpp.o

I wonder if this PR is the reason: https://github.com/pytorch/pytorch/commit/6820745e28e6c777d35a2b874b3e5b627e58c3a0

## To Reproduce
Build with:
CC=clang CXX=clang++ USE_MKL=0 USE_XNNPACK=0  USE_MKLDNN=0 BUILD_CAFFE2_OPS=0 DEBUG=1  python setup.py install

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
@protonu can you run collect_env and post result here? Also, is this full or an incremental build? If later, please try deleting build folder and try doing a full build.

**Comment by protonu** [comment]
> @protonu can you run collect_env and post result here? Also, is this full or an incremental build? If later, please try deleting build folder and try doing a full build.

Thanks for responding!

this was a clean build. 


(pyenv) protonu-mbp:utils protonu$ python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.21)
CMake version: version 3.18.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-include               2020.2                      260
[conda] mkl-service               2.3.0            py37hfbe908c_0
[conda] mkl_fft                   1.2.0            py37hc64f4ea_0
[conda] mkl_random                1.1.1            py37h959d312_0
[conda] numpy                     1.19.2           py37h456fd55_0
[conda] numpy-base                1.19.2           py37hcfb5961_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1

**Comment by protonu** [comment]
@malfet I also see a similar error when I build on a linux box:
[ 94%] Linking CXX executable ../bin/op_registration_test
CMakeFiles/op_registration_test.dir/__/aten/src/ATen/core/op_registration/op_registration_test.cpp.o: In function `(anonymous namespace)::NewOperatorRegistrationTest_BackendSelectRedispatchesToCPU_Test::TestBody()::{lambda(at::Tensor const&)#2}::operator()(at::Tensor const&) const':
op_registration_test.cpp:(.text+0xb0dd7): undefined reference to `c10::impl::raw_local_dispatch_key_set'
CMakeFiles/op_registration_test.dir/__/aten/src/ATen/core/op_registration/op_registration_test.cpp.o: In function `c10::Dispatcher::callBoxed(c10::OperatorHandle const&, std::vector<c10::IValue, std::allocator<c10::IValue> >*) const [clone .constprop.6869]':
op_registration_test.cpp:(.text+0xc617c): undefined reference to `c10::impl::raw_local_dispatch_key_set'
CMakeFiles/op_registration_test.dir/__/aten/src/ATen/core/op_registration/op_registration_test.cpp.o: In function `c10::TypedOperatorHandle<void (at::Tensor)>::call(at::Tensor) const':
op_registration_test.cpp:(.text._ZNK3c1019TypedOperatorHandleIFvN2at6TensorEEE4callES2_[_ZNK3c1019TypedOperatorHandleIFvN2at6TensorEEE4callES2_]+0x65): undefined reference to `c10::impl::raw_local_dispatch_key_set'

**Comment by protonu** [comment]
@malfet  It builds now, I was a couple of days behind master. Thanks for looking into it.
