### ISSUE TITLE
When working on PR request #49169, I encountered an error test_variant_consistency_jit_tensor_split_cpu_bfloat16

### ISSUE THREAD

**Issue by edqwerty10** [pytorch/pytorch#49484]
## ❓ Questions and Help
When working on PR request #49169, I encountered an error test_variant_consistency_jit_tensor_split_cpu_bfloat16. What is this test testing? If it okay to skip this test?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @gmagogsfm

**Comment by edqwerty10** [comment]
cc. @mruberry 
code pointer in PR
https://github.com/pytorch/pytorch/pull/49169/files

**Comment by ngimel** [comment]
Let's have discussion in the PR.
