### ISSUE TITLE
PyPI is slow please create git releases

### ISSUE THREAD

**Issue by dheerajmpai** [pytorch/pytorch#49487]
## 🚀 Feature

Create alternative to PyPI install. Preferably create `tar.gz` releases on github

## Motivation

Pypi install of torch is extremely slow. Download speeds from pypi are sometimes as slow as `400 kBps` even on a 50Mbps internet. Making the installation take hours to install. Alternative pathways to install such as git releases or google storage links would be extremely helpful. 

## Alternatives

Host releases on google cloud storage/Azure/AWS S3 or Any cloud storage which has reasonable egress bandwidth.

## Additional context

None

cc @ezyang @seemethere @malfet @walterddr

**Comment by skyline75489** [comment]
I'm not sure I understand this correctly? Are you suggesting that source code tarball releases on github?

**Comment by walterddr** [comment]
have you try using local mirrors in your region? 
also have you try conda?

**Comment by seemethere** [comment]
Releases are already hosted on S3 you can find installation instructions that relate to https://download.pytorch.org on https://pytorch.org/get-started

Example:

```
pip install -f https://download.pytorch.org/whl/cu102/torch_stable.html torch
```
