### ISSUE TITLE
torch.hub.load with no internet connection causes TypeError

### ISSUE THREAD

**Issue by brandon-biggs** [pytorch/pytorch#49485]
## 🐛 Bug
torch.hub.load with no internet connection causes TypeError

If I have an internet connection
```
>>> import torch
>>> model = torch.hub.load('pytorch/fairseq', 'roberta.large')
Using cache found in <path>
>>>
```
No internet connection:
```
>>> import torch
>>> model = torch.hub.load('pytorch/fairseq', 'roberta.large')
Using cache found in <path>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/pytorch-1.7/lib/python3.7/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "~/pytorch-1.7/lib/python3.7/site-packages/torch/hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "<path>/pytorch_fairseq_master/fairseq/models/roberta/model.py", line 251, in from_pretrained
    **kwargs,
  File "<path>/pytorch_fairseq_master/fairseq/hub_utils.py", line 56, in from_pretrained
    kwargs["data"] = os.path.abspath(os.path.join(model_path, data_name_or_path))
  File "~/pytorch-1.7/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## To Reproduce

1. Have an internet connection
3. `conda create -n <name> python=3.7`
4. `conda activate <name>`
5. Install pytorch via instructions from pytorch website along with other prerequisites
```
conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch 
pip install omegaconf
pip install hydra-core --upgrade --pre
pip install regex
pip install requests
pip install cython
```
6. Launch python - `python`
7. Run the following to pull the model from github
```
>>> import torch
>>> model = torch.hub.load('pytorch/fairseq', 'roberta.large')
```
8. Exit python and disconnect network
9. Launch python and run the same commands
```
>>> import torch
>>> model = torch.hub.load('pytorch/fairseq', 'roberta.large')
```
10. It should say: `Using cache found in <path>` but then it crashes with the above error.

## Expected behavior

I expected to be able to use the model offline as I believed it's using a cached model instead of having to download one every time.

## Environment

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.8.2003 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.7_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchvision               0.8.2                py37_cu110    pytorch

cc @ailzhang

**Comment by kit-** [comment]
Here's the message printed when logging levels are increased:
> INFO:fairseq.file_utils:Archive name 'http://dl.fbaipublicfiles.com/fairseq/models/roberta.large.tar.gz' was not found in archive name list. We assumed 'http://dl.fbaipublicfiles.com/fairseq/models/roberta.large.tar.gz' was a path or URL but couldn't find any file associated to this path or URL.

The contents of roberta.large.tar.gz are in the following directory but the load_archive_file function in file_utils.py is unaware of the cache_dir:
~/.cache/torch/pytorch_fairseq/83e3a689e28e5e4696ecb0bbb05a77355444a5c8a3437e0f736d8a564e80035e.c687083d14776c1979f3f71654febb42f2bb3d9a94ff7ebdfe1ac6748dba89d2/

**Comment by mariosasko** [comment]
Yes, it seems like this error is  unrelated to `torch.hub.load`. Try to file an issue in fairseq's repo.

**Comment by ailzhang** [comment]
Closing as this is a fairseq issue. Please feel free to open a new issue.
