### ISSUE TITLE
DOCS: Links to Source Code Broken

### ISSUE THREAD

**Issue by ronrest** [pytorch/pytorch#495]
When clicking the `source` links on the documentation page, the links leads to a non-existent pages. 

eg, as a concrete example,  from the following doc page: 

- [http://pytorch.org/docs/data.html](http://pytorch.org/docs/data.html)

The `source` link for the `class torch.utils.data.Dataset` links to the following page:  

- [http://pytorch.org/docs/_modules/torch/utils/data/dataset.html#Dataset](http://pytorch.org/docs/_modules/torch/utils/data/dataset.html#Dataset)

**Comment by apaszke** [comment]
This seems to be fixed now.
