### ISSUE TITLE
Exporting the operator logical_or to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by vikoz** [pytorch/pytorch#49518]
## 🐛 Bug

Torch->ONNX conversion script doesn't seem to have support for logical operators (or, and, etc.). I went through the repo files, didn't find them there either.

## To Reproduce

1. Have a model with logical_or, logical_and, etc. operators
1. Call torch.onnx.export on that model

## Expected behavior

The model should convert to ONNX

## Environment

Collecting environment information...
PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P2200
Nvidia driver version: 450.36.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1+cpu
[pip3] torch-cluster==1.5.8
[pip3] torch-geometric==1.6.3
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.8
[pip3] torch-spline-conv==1.2.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.2+cpu
[conda] Could not collect

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@vikoz - this support should be in master now https://github.com/pytorch/pytorch/pull/50570.
