### ISSUE TITLE
Segfault in torch.histc

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#49522]
## 🐛 Bug

Segfault in `torch.histc`

## To Reproduce

~~~python
torch.histc(torch.tensor([[ 2.7771e+38, -1.7855e+38]]))
~~~

It throws segfualt:
~~~python
Segmentation fault (core dumped)
~~~

## Expected behavior

expect no crash

## Environment

PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

**Comment by mrshenli** [comment]
I confirm I can reproduce this. `torch.histc` works on smaller range, and gives better error message on larger range. See the outputs below. 

```python
>>> torch.histc(torch.tensor([[ 2.7771e+37, -1.7855e+37]]))
tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

>>> torch.histc(torch.tensor([[ 2.7771e+39, -1.7855e+39]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: range of [-inf, inf] is not finite

>>> torch.histc(torch.tensor([[ 2.7771e+38, -1.7855e+38]]))
Segmentation fault
```

**Comment by mrshenli** [comment]
hey @mruberry, does it make sense to add this to next fixathon?

**Comment by mrshenli** [comment]
#49521 and  #49520 probably also need better error message

**Comment by mruberry** [comment]
> hey @mruberry, does it make sense to add this to next fixathon?

That's an interesting idea, @mrshenli. Maybe?

**Comment by gchanan** [comment]
@mrshenli the "enhancement" label is for small feature additions.

**Comment by DNXie** [comment]
This seems to be fixed in the nightly version.
