### ISSUE TITLE
Segfault in torch.eye

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#49521]
## To Reproduce

These two code snippet can both lead to segfault
~~~python
torch.eye(1069990502085580415)
torch.eye(n=1000000, m=3948000418890973690)
~~~

Output:
~~~python
Segmentation fault (core dumped)
~~~

## Expected behavior
expect not crash

## Environment

PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

**Comment by ag14774** [comment]
you are probably running out of memory. Same for the rest of your open issues

**Comment by yqtianust** [comment]
Shall we add some input validation for torch.eye()? 

I have 256G RAM but I still get Seg Fault. 

In numpy.eye(1069990502085580415), I will get the following error, instead of seg fault:
``ValueError:` array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.``

**Comment by DNXie** [comment]
This seems to be fixed in the nightly version.
