### ISSUE TITLE
[feature request] Add native dict support for nn.Sequential

### ISSUE THREAD

**Issue by ain-soph** [pytorch/pytorch#49530]
## Issue description

We use `OrderedDict` a lot in Pytorch and Torchvision. Since the native `dict` already supports the insert order after python 3.7 ([Reference](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)), shall we move to the native `dict` in pytorch implementations? Or at least for user interfaces (such as `nn.Sequential`, `state_dict` and `load_state_dict`), so that we can get it more convenient.

[nn.Sequential Example](https://pytorch.org/docs/stable/generated/torch.nn.Sequential.html)

[Python dict Docs](https://docs.python.org/3.9/library/stdtypes.html?highlight=dict#dict)
[Python OrderedDict Docs](https://docs.python.org/3.9/library/collections.html?highlight=ordereddict#collections.OrderedDict)

## Previous code
```python
torch.nn.Sequential(OrderedDict([('id', torch.nn.Identity()), ('id2', torch.nn.Identity())]))
```
## Expectation
```python
torch.nn.Sequential({'id': torch.nn.Identity(), 'id2': torch.nn.Identity()})
```
Currently, this usage will raise `TypeError: dict is not a Module subclass`

cc @albanD @mruberry @jbschlosser

**Comment by mariosasko** [comment]
The insertion order is preserved as of Python 3.6 (CPython implementation). In version 3.7 this was officially documented. Since PyTorch supports Python>=3.6, this means, in case of Python 3.6, PyTorch would rely on a specific implementation detail this is not properly documented.

**Comment by ain-soph** [comment]
> The insertion order is preserved as of Python 3.6 (CPython implementation). In version 3.7 this was officially documented. Since PyTorch supports Python>=3.6, this means, in case of Python 3.6, PyTorch would rely on a specific implementation detail which is not properly documented.

That makes sense. So if we don't consider it, we may close this issue then. But maybe we can reconsider it when Pytorch moves to `python>=3.7`.

**Comment by mrshenli** [comment]
adding to "triage review" meeting to bump up awareness of this feature request

**Comment by ain-soph** [comment]
Any one could tell me if this worth doing?
If so, I may work on it recently and propose the pull request. And it will get merged when pytorch moves to `python>=3.7`
But I have to say there are a bunch of `OrderedDict` items. I may start if we are sure to work on it.

**Comment by mruberry** [comment]
This is an interesting but tricky issue. 

It's true that once PyTorch stops supporting Python before 3.7 we could consider this change. One risk with it is that models written like the above wouldn't work on previous PyTorch versions.

However I'm not sure moving to a dict vs. an ordered dict is a great idea. I thought this blog post was interesting, for example: http://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/.

**Comment by ain-soph** [comment]
> However I'm not sure moving to a dict vs. an ordered dict is a great idea. I thought this blog post was interesting, for example: http://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/.

Sure, not quite sure whether it will boost the efficiency. But at least makes our code much more clean, and we won't need to import `OrderedDict` from collections. I think the efficiency cost is negligible since it's not a too frequent action, at least not thousands of times. I'd like to prefer a simple coding style.

> It's true that once PyTorch stops supporting Python before 3.7 we could consider this change. One risk with it is that models written like the above wouldn't work on previous PyTorch versions.
Certainly native `dict` coding style will not work on previous versions. But we'll still keep `OrderedDict` style coding available for backward compatiblity.

**Comment by mruberry** [comment]
I appreciate your thinking, @ain-soph, but the point about using OrderedDicts isn't that it's more efficient, it's that it improves the readability and intentionality of the code to declare that the order of elements in the dictionary is important.

**Comment by ain-soph** [comment]
May close this issue if it's not appropriate. Personally I'd prefer native `dict` and think that's more readable and brings a clean coding style with fewer brackets and import sentences. But `OrderedDict` won't affect any daily use for sure.

**Comment by mruberry** [comment]
Let's get a third opinion from @jbschlosser.

**Comment by jbschlosser** [comment]
While I see @ain-soph's point that allowing native dicts would result in cleaner syntax, my opinion is that I prefer the lack of ambiguity from requiring OrderedDict. I think the linked [blog post](http://gandenberger.org/2018/03/10/ordered-dicts-vs-ordereddict/) makes great points about the semantic nature of native dicts- their ordering has historically been considered not to matter in other libraries. I'm also hesitant to break forward compatibility with the change.

That said, we could certainly reconsider this once PyTorch supports Python 3.7+ only.

**Comment by ain-soph** [comment]
Any update on this? I totally agree with OrderedDict is forcing the orders.

But it’s really annoying when I construct a ordereddict using list and tuples besides an external import sentence from collection.  
The native dict saves a lot if it’s supported. 

And it’ll be certainly backward-compatible, just accept native dict as a new option. It could be transformed into OrderedDict.

**Comment by jbschlosser** [comment]
I'm still personally of the opinion we should maintain `OrderedDict`-only for clear semantics - cc @albanD @mruberry any dissenting opinions?

**Comment by ain-soph** [comment]
Thanks for your reply with lightning speed! I’ll close the issue if other maintainer agree with it.

**Comment by ain-soph** [comment]
Sorry for mentioning this issue again. Just to add a support reference to see if it helps.  
I see Python community assumes Dict is ordered by default, and they use OrderedDict only when extra features is needed. I think it’s the same case for us.

> Changed in version 3.1: Returns an [OrderedDict](https://docs.python.org/3.11/library/collections.html#collections.OrderedDict) instead of a regular [dict](https://docs.python.org/3.11/library/stdtypes.html#dict).
> Changed in version 3.8: Returns a regular [dict](https://docs.python.org/3.11/library/stdtypes.html#dict) instead of an [OrderedDict](https://docs.python.org/3.11/library/collections.html#collections.OrderedDict). As of Python 3.7, regular dicts are guaranteed to be ordered. If the extra features of [OrderedDict](https://docs.python.org/3.11/library/collections.html#collections.OrderedDict) are required, the suggested remediation is to cast the result to the desired type: OrderedDict(nt._asdict()).

https://docs.python.org/3.11/library/collections.html#collections.somenamedtuple._asdict
