### ISSUE TITLE
Homebrew repo is down: https://download.pytorch.org/whl/cpu/torch_stable.html

### ISSUE THREAD

**Issue by kousu** [pytorch/pytorch#49559]
## 🐛 Bug

I cannot download pytorch+cpu because the download server is saying `content-type: application/octet-stream` on the index.

## To Reproduce

```
$ pip install -f https://download.pytorch.org/whl/cpu/torch_stable.html torch==1.5.0+cpu
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
WARNING: Skipping page https://download.pytorch.org/whl/cpu/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement torch==1.5.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1)
ERROR: No matching distribution found for torch==1.5.0+cpu
```

Loading the page in my browser prompts me with

![2020-12-17-135146_760x467_scrot](https://user-images.githubusercontent.com/987487/102531454-50bcd700-4070-11eb-8904-ccaa3925bc96.png)

Here are the full HTTP headers:

```
$ curl -v -o /dev/null https://download.pytorch.org/whl/cpu/torch_stable.html 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 13.225.190.31:443...
* Connected to download.pytorch.org (13.225.190.31) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [4843 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=pytorch.org
*  start date: Mar 18 00:00:00 2020 GMT
*  expire date: Apr 18 12:00:00 2021 GMT
*  subjectAltName: host "download.pytorch.org" matched cert's "*.pytorch.org"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x557b9197dd80)
} [5 bytes data]
> GET /whl/cpu/torch_stable.html HTTP/2
> Host: download.pytorch.org
> user-agent: curl/7.74.0
> accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [5 bytes data]
< HTTP/2 200 
< content-type: binary/octet-stream
< content-length: 37547
< date: Thu, 17 Dec 2020 18:51:53 GMT
< last-modified: Thu, 17 Dec 2020 18:44:01 GMT
< etag: "39758beefc9f06fc180a92f8225577da"
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Hit from cloudfront
< via: 1.1 0dbb84b34f6ac39ad26a6446ff2b18ec.cloudfront.net (CloudFront)
< x-amz-cf-pop: YUL62-C1
< x-amz-cf-id: 6uZokT7wffwbNqWwxin48yWkIYf7PlL8tH5ou1MWftJjO0Zh35od-Q==
< age: 588
< 
{ [16052 bytes data]
100 37547  100 37547    0     0   233k      0 --:--:-- --:--:-- --:--:--  235k
* Connection #0 to host download.pytorch.org left intact
```

## Expected behavior

I want to download the package.

## Environment

- python collect_env.py 
- Collecting environment information...
- PyTorch version: N/A
- Is debug build: N/A
- CUDA used to build PyTorch: N/A
- ROCM used to build PyTorch: N/A
-
- OS: Arch Linux (x86_64)
- GCC version: (GCC) 10.2.0
- Clang version: Could not collect
- CMake version: version 3.19.2
-
- Python version: 3.9 (64-bit runtime)
- Is CUDA available: N/A
- CUDA runtime version: Could not collect
- GPU models and configuration: Could not collect
- Nvidia driver version: Could not collect
- cuDNN version: Could not collect
- HIP runtime version: N/A
- MIOpen runtime version: N/A
- 
- Versions of relevant libraries:
- [pip3] numpy==1.19.4
- [conda] Could not collect

## Additional context

This was working 1 hour ago. I've been testing stuff in CI and it was fine until just a few minutes ago.

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet @walterddr

**Comment by song-william** [comment]
Seeing the same issue when running `pip install torch==1.7.0+cu101 pip install torch==1.7.0+cu101 --find-links https://download.pytorch.org/whl/torch_stable.html` with `pip==20.2.2`. 

```
$ pip install torch==1.7.0+cu101 --find-links https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
WARNING: Skipping page https://download.pytorch.org/whl/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html
ERROR: Could not find a version that satisfies the requirement torch==1.7.0+cu101 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1)
ERROR: No matching distribution found for torch==1.7.0+cu101
```

**Comment by kousu** [comment]
It seems to have cleared up for my CI machine:

https://travis-ci.com/github/neuropoly/spinalcordtoolbox/jobs/461955522

And also for my laptop. Amazon is involved, so maybe some of their servers got a bad update? :(

**Comment by kousu** [comment]
Ah, it came back: https://travis-ci.com/github/neuropoly/spinalcordtoolbox/jobs/461955521 and https://travis-ci.com/github/neuropoly/spinalcordtoolbox/jobs/461955520 both die with 

```
WARNING: Skipping page https://download.pytorch.org/whl/cpu/torch_stable.html because the GET request got Content-Type: binary/octet-stream.The only supported Content-Type is text/html

ERROR: Could not find a version that satisfies the requirement torch==1.5.0+cpu

ERROR: No matching distribution found for torch==1.5.0+cpu
```

**Comment by mrshenli** [comment]
Not sure if there is anything that we can do. Adding "high priority" to raise visibility.

**Comment by seemethere** [comment]
Sorry about that, there was an issue with the refactor to the HTML index update script.

This should be mostly resolved now.

Let me know if you run into anything else.

**Comment by evanphilipsmith** [comment]
Seems to be working for me now

**Comment by seemethere** [comment]
> Seems to be working for me now

Going to go ahead and close this since this appears to be resolved.

**Comment by kousu** [comment]
Thanks for the quick incident response mes ami.es! Thu Dec 17 19:52:14 EST 2020 pytorch/pytorch <reply@reply.github.com>: Seems to be working for me now Going to go ahead and close this since this appears to be resolved. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
