### ISSUE TITLE
confusing error message `ValueError: can't optimize a non-leaf Variable`

### ISSUE THREAD

**Issue by samuela** [pytorch/pytorch#4957]
When submitting a bug report, please include the following information (where relevant):
- OS: macOS
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.2

```python
import itertools
import torch
from torch.autograd import Variable

net = torch.nn.Linear(1, 1)
W = Variable(torch.zeros(1, 1), requires_grad=True)

# This does NOT work!
torch.optim.Adam(itertools.chain(*net.parameters(), W))

# ... but this works just fine.
torch.optim.Adam([*net.parameters(), W])
```

If one uses `torch.optim.Adam(itertools.chain(*net.parameters(), *[W]))`, there's a nasty error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Development/icml2018/leaf_variable_issue.py in <module>()
      8 W = Variable(torch.zeros(1, 1), requires_grad=True)
      9 
---> 10 torch.optim.Adam(itertools.chain(*net.parameters(), *[W]))
     11 # torch.optim.Adam([*net.parameters(), *[W]])

~/Development/icml2018/venv/lib/python3.6/site-packages/torch/optim/adam.py in __init__(self, params, lr, betas, eps, weight_decay)
     27         defaults = dict(lr=lr, betas=betas, eps=eps,
     28                         weight_decay=weight_decay)
---> 29         super(Adam, self).__init__(params, defaults)
     30 
     31     def step(self, closure=None):

~/Development/icml2018/venv/lib/python3.6/site-packages/torch/optim/optimizer.py in __init__(self, params, defaults)
     37 
     38         for param_group in param_groups:
---> 39             self.add_param_group(param_group)
     40 
     41     def __getstate__(self):

~/Development/icml2018/venv/lib/python3.6/site-packages/torch/optim/optimizer.py in add_param_group(self, param_group)
    153                 raise ValueError("optimizing a parameter that doesn't require gradients")
    154             if not param.is_leaf:
--> 155                 raise ValueError("can't optimize a non-leaf Variable")
    156 
    157         for name, default in self.defaults.items():

ValueError: can't optimize a non-leaf Variable
```
Even if these optimization classes aren't meant to support itertools.chain somehow, this error message is just not correct.

**Comment by SsnL** [comment]
Well, you are using `itertools.chain` wrongly. It takes a variable number of iterables, and your code should read `torch.optim.Adam(itertools.chain(net.parameters(), [W]))`. 

Your first line fails because each tensor happens to be an iterable of slices so the optimizer class receives slices of parameters, i.e. non-leafs.

Your second line works because it is essentially constructing a list with all parameters plus `W`.

**Comment by samuela** [comment]
@SsnL Ah, I see. My bad on that one! Still shouldn't the optimizer check that the things in the iterable input are all Parameters? The `can't optimize a non-leaf Variable` message doesn't make much sense to me.

**Comment by SsnL** [comment]
Optimizers can also be used to optimize Variables.

**Comment by samuela** [comment]
Sure sure, but shouldn't it check that everything is a Variable then (since Parameters are also Variables)?

**Comment by SsnL** [comment]
Yes it does :) https://github.com/pytorch/pytorch/blob/master/torch/optim/optimizer.py#L182

But slices of variables are still variables.

**Comment by samuela** [comment]
Oh gotcha... itertools.chain was implicitly slicing the Variable and the slices were not leaf Variables. I guess there's not much that can be done about this then. Closing the issue.
