### ISSUE TITLE
An error GPU memery cost in RTX3090 with few batch size

### ISSUE THREAD

**Issue by zhujun5164** [pytorch/pytorch#49586]
## To Reproduce

when i training in 3090 with a lower batch size, the GPU memery cost is the double of when i train in 2080ti with the same batch size. and the training speed only the 60% of 2080ti.

But when i increase the batch size in a large size( maybe increase to the real GPU memery cost larger than 12GB), the memery cost and training speed become normal.

## Environment
![image](https://user-images.githubusercontent.com/49580602/102573543-9ab5c380-4129-11eb-8044-041f14b37f73.png)

## Additional context

cc @ngimel

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, as it is not the bug, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
