### ISSUE TITLE
Pip install error in python 3.8 windows 10

### ISSUE THREAD

**Issue by Tejask1** [pytorch/pytorch#49595]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

I want to install pytorch but after downloading it shows no such file or directory learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip

Please help

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
You have provide us almost no useful information. Please read and fill the issue template to provide as much information as you can, otherwise no one can really help you.

**Comment by AppleHolic** [comment]
I saw this table on README.md, So I think supported version of python is only 3.7 on windows OS.
![image](https://user-images.githubusercontent.com/3727290/102597762-70322d80-415e-11eb-9d8d-76e08422a150.png)

**Comment by Tejask1** [comment]
@AppleHolic  and @skyline75489  thanks for your help . I had got the solution and actual problem.@AppleHolic it supports python3.8 too .

**Comment by saikrishna2893** [comment]
> @AppleHolic and @skyline75489 thanks for your help . I had got the solution and actual problem.@AppleHolic it supports python3.8 too .

@Tejask1 how did you resolve the issue? I'm currently using python 3.10.8 version and pytorch version 1.13.0, I'm facing the same issue.
