### ISSUE TITLE
"No data to combine" error intermittently on Windows CUDA test builds

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#49596]
See, for example:

https://app.circleci.com/pipelines/github/pytorch/pytorch/251798/workflows/94541858-2d75-464a-b885-26556a774485/jobs/9663068

Relevant snippet:

```
  test_ReflectionPad_empty_cuda (__main__.TestNNDeviceTypeCUDA) ... No data to combine
Traceback (most recent call last):
  File "run_test.py", line 897, in <module>
    main()
  File "run_test.py", line 880, in main
    raise RuntimeError(err_message)
RuntimeError: test_nn failed!
```

and:

https://app.circleci.com/pipelines/github/pytorch/pytorch/252961/workflows/7bc6f060-9b7f-4689-a302-860f6d9491f9/jobs/9727664

Relevant snippet:

```
test_ReplicationPad1d_cuda (__main__.TestNN) ... No data to combine
Traceback (most recent call last):
  File "run_test.py", line 905, in <module>
    main()
  File "run_test.py", line 888, in main
    raise RuntimeError(err_message)
RuntimeError: test_nn failed!
```

I'm a little baffled as to where this error could even be coming from. Searching the internet for this rare string suggests it's in a code coverage tool:

https://github.com/nedbat/coveragepy/blob/0b1dd531f23d8ba313ee685b156b07f76fa680d5/coverage/data.py#L96

Maybe this is code coverage related somehow? 

@malfet Any ideas? 

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by malfet** [comment]
I thought windows code coverage is run on just one config, but will check it tomorrow.

**Comment by malfet** [comment]
Code coverage for Windows is indeed enabled by https://github.com/pytorch/pytorch/pull/44548 on that config, but this change was made almost 2 month ago...
