### ISSUE TITLE
Needs an option for blinding absolute path on torch.utils.mobile_optimizer.optimize_for_mobile

### ISSUE THREAD

**Issue by AppleHolic** [pytorch/pytorch#49597]
## 🚀 Feature

Adding arguments for blinding paths on torch.utils.mobile_optimizer.optimize_for_mobile

## Motivation

I saw that compiled jit-script-module prints out 'absolute source file path' on \_\_repr\_\_ of graphs and nodes.

So, Although paths can be discovered by other ways, I suggests that adding arguments for blinding paths on \_\_repr\_\_ of graphs and nodes or removed(or blinded) absolute paths on \_\_repr\_\_ . 

## Pitch

```python
from torch.utils.mobile_optimizer import optimize_for_mobile
module = optimize_for_mobile(MODULE)

print(module.graph)

# it prints out on some Nodes like this..
 %875 : Tensor = prim::Constant[value={3}]() # /home/user/source/code/absolute/path

# I think it should be blinded or removed
 %875 : Tensor = prim::Constant[value={3}]() # no path or encrypted path
```

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi AppleHolic,

Could you clarify a bit more on motivation? Thanks.

**Comment by AppleHolic** [comment]
@gmagogsfm 
Yes, sure. 

Usually, a module has several sub-modules to do some sub tasks that are divided from entire pipeline. 

And, file names of experimental sources represents what they are doing for, so reverse engineers can approximate what are doing on entry nodes of sub modules from file names. (e.g. image_generator, speech_recognition, ...)

Therefore, I did refactor source codes and encrypt their names. If the compiling function has an option to hide their names, I think it can helps to improve security of them.

**Comment by gmagogsfm** [comment]
Closing this issue since there is a close-enough work around and there are no similar requests.
