### ISSUE TITLE
mpi tests don't work?

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#4965]
I installed `mpich` to get `mpiexec` available, but the test run failed this way:

```
Running distributed tests for the MPI backend
[mpiexec@97706765f01f] match_arg (./utils/args/args.c:160): unrecognized argument noprefix
[mpiexec@97706765f01f] HYDU_parse_array (./utils/args/args.c:175): argument matching returned error
[mpiexec@97706765f01f] parse_args (./ui/mpich/utils.c:1609): error parsing input array
[mpiexec@97706765f01f] HYD_uii_mpx_get_parameters (./ui/mpich/utils.c:1660): unable to parse user arguments
[mpiexec@97706765f01f] main (./ui/mpich/mpiexec.c:153): error parsing parameters
```

Log: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py2.7.9-test/1310/console

So it sounds like we need a specific MPI backend for the tests, any old one won't do.

CC @0mp and @apaszke

**Comment by apaszke** [comment]
Hmm can you try removing `--noprefix`?

**Comment by superizer** [comment]
@apaszke Thank you, It's work!

**Comment by apaszke** [comment]
It needs to be removed from the `test/build_all.sh` script

**Comment by alvin38** [comment]
Thank you so much adam, I have solved it

Sent from Mail for Windows 10
