### ISSUE TITLE
Have a file extension convention for jit models

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#49660]
## 🚀 Feature
Adopt a consistent convention of file extension for saved jit models.

## Motivation

Technically the file can be named arbitrarily. But having and following a convention can help people know the format of the file.

Now the official tutorials are not consistent themselves. There are:
- `.pth`: https://pytorch.org/docs/stable/jit.html#frequently-asked-questions
- `.zip`: https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#saving-and-loading-models
- `.pt`: https://pytorch.org/tutorials/advanced/cpp_export.html#step-2-serializing-your-script-module-to-a-file

There are also use of `.jit` and `.ts` among users. Having a convention and use it consistently across tutorials would make the situation less confusing.

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
Also fixed tutorials in https://github.com/pytorch/tutorials/pull/1310
