### ISSUE TITLE
We should track implicit scalar broadcasts for backward

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#4968]
Today, we 'implicitly' broadcast scalars to 1-dimensional tensors when calling into TH; it's implicit because that's just how the tensors are represented in TH.  Take for example `torch.ger`; if I call this on two scalars, they are both implicitly broadcasted to size [1] tensors/variables and the result is a [1,1] tensor/variable; this behavior matches numpy.  But the backwards need to be written to take this implicit broadcast into account, i.e. this backwards declaration in derivatives.yaml is incorrect:
`
self: grad.mv(vec2)
`
because the result has to be 0-d if self was 0-d.  So, we need to write backwards to take the broadcast into account, which we don't normally have to do (because we explicitly broadcast elsewhere and that gets captured by autograd).

Note this only matters for functions that call into TH/THC.

CC @colesbury @ezyang

**Comment by ezyang** [comment]
I think Greg fixed this in the last two years :)
