### ISSUE TITLE
Inconsistent documentation of linalg operator dtype versions.

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#49689]
A quick search in the docs seems to suggest that we are not using a consistent naming scheme. E.g.:

- `cholesky_inverse` explicitly lists all variations by saying ``dpotri and spotri``

- `toch.geqrf` mentions both `geqrf` and `?geqrf` in the same docstring

- `orgqr` the same

_Originally posted by @antocuni in https://github.com/pytorch/pytorch/pull/45562#r531147774_

cc @jlin27 @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr

**Comment by mruberry** [comment]
I think this is mooted because we removed the references to these algorithms
