### ISSUE TITLE
Segmentation fault when loading data 

### ISSUE THREAD

**Issue by xuanqing94** [pytorch/pytorch#4969]
- OS: Ubuntu 16.04
- PyTorch version: source code@master
- How you installed PyTorch (conda, pip, source): source
- Python version: Python3.6@conda
- CUDA/cuDNN version: 9.0
- GPU models and configuration: 4x1080Ti
- GCC version (if compiling from source): gcc5.4

- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
dataloader(..., numworkers=2)
then iterate over dataset
- Error messages and/or stack traces of the bug
Files already downloaded and verified
Files already downloaded and verified
ERROR: Unexpected segmentation fault encountered in worker.
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "./main.py", line 445, in <module>
    main()
  File "./main.py", line 426, in main
    train_TR(dataloader, dataloader_test, net, loss_f, opt.lr, opt.radius, opt.max_inner, opt.epoch)
  File "./main.py", line 214, in train_TR
    for x, y in data_iter:
  File "/home/luinx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/home/luinx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/home/luinx/miniconda3/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/home/luinx/miniconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/luinx/miniconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/luinx/miniconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/luinx/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 21010) is killed by signal: Segmentation fault.

- Context around what you are trying to do
Nothing special, just loading data. When I set numworkers=0, then it works fine. I guess it is triggered by interprocess communication.

**Comment by SsnL** [comment]
There was a PR that introduced a bug on master. It is reverted now. Could you pull again and see if it works now? :)

**Comment by xuanqing94** [comment]
@SsnL I fetch the [https://github.com/pytorch/pytorch/commit/f2d3f20f6d4ad12aaaa97fa8293008c4c25e2b70](f2d3f20) commit, after compiling and installing, the issue is still there...
Although I am using the binary version now :)

**Comment by xuanqing94** [comment]
@SsnL It works, thank you!

**Comment by achainan** [comment]
Im still getting a similar error when I set num_workers > 0. Any help would be much appreciated.
I have built pytorch from source to use on my Mac with my eGPU (1080Ti).
```
Fatal Python error: Segmentation fault

Thread 0x000070000cc8d000 (most recent call first):
  File "/Users/ajaychainani/anaconda2/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 21 in recv
  File "/Users/ajaychainani/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376 in get
  File "/Users/ajaychainani/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 68 in _worker_manager_loop
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 754 in run
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x000070000c381000 (most recent call first):

Thread 0x000070000c27b000 (most recent call first):

Thread 0x000070000c784000 (most recent call first):
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 340 in wait
  File "/Users/ajaychainani/anaconda2/lib/python2.7/Queue.py", line 168 in get
  File "/Users/ajaychainani/anaconda2/lib/python2.7/site-packages/tensorboardX/event_file_writer.py", line 186 in run
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/Users/ajaychainani/anaconda2/lib/python2.7/threading.py", line 774 in __bootstrap

Thread 0x00007fffd9efe3c0 (most recent call first):
  File "/Users/ajaychainani/anaconda2/lib/python2.7/multiprocessing/process.py", line 78 in _cleanup
  File "/Users/ajaychainani/anaconda2/lib/python2.7/multiprocessing/process.py", line 125 in start
  File "/Users/ajaychainani/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 234 in __init__
  File "/Users/ajaychainani/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 417 in __iter__
  File "train.py", line 289 in train
  File "train.py", line 86 in main
  File "train.py", line 319 in <module>
```

**Comment by SsnL** [comment]
@achainan Your error seems not the same as the one above. Are you doing multiple dataloaders in multithreading? Could you share more details on how you are using it please? And also a commit hash will be great.

**Comment by achainan** [comment]
Here is the project:
https://github.com/achainan/posture.pytorch

Here is the relevant line:
https://github.com/achainan/posture.pytorch/blob/b6dc25bd206b33a7c2cbbc4ef73b56c71c99cd98/train.py#L59

I'm using the latest pytorch at https://github.com/pytorch/pytorch/commit/36bbaf0d859ff052ac6e991b7d909e9ff15ae70f

**Comment by achainan** [comment]
The data loader logic is:
https://github.com/achainan/posture.pytorch/blob/b6dc25bd206b33a7c2cbbc4ef73b56c71c99cd98/dataset/dataset.py

**Comment by jason718** [comment]
I also met similar issues. After I set numworkers=0, then it works fine.

**Comment by SsnL** [comment]
@achainan Thanks! Sorry for missing you reply earlier. It seems that pandas could be relevant. Let me investigate this tomorrow.

@jason718 Could you share more info? Pytorch version, what you do in the dataset, etc.

**Comment by achainan** [comment]
@SsnL Just removed all the pandas logic out of one of my projects and still encounter the issue. Have a feeling it might be more related to cv2 (or modifying images with numpy operations rather than PIL operations).

**Comment by SsnL** [comment]
@achainan Oh I see. It's definitely cv2. It is known to be not nice with multiprocessing. Sorry I just did a quick glance at the imports and didn't see any cv2.

**Comment by achainan** [comment]
Ok I removed usage of cv2, but it still seems to be happening. Now debating whether it is random or scipy.ndimage related.

**Comment by achainan** [comment]
@SsnL Ok I removed usage of cv2, but it still seems to be happening. Now debating whether it is random or scipy.ndimage related.

**Comment by SsnL** [comment]
@achainan That's rather weird. What's more puzzling is that Python is segfaulting, not cv2 or pytorch libraries. Could you try a different python version?

**Comment by achainan** [comment]
@SsnL I upgraded to python 3.6 from 2.7. Seems to have worked. Thanks.

**Comment by timbmg** [comment]
@jason718 Had the same problem... did you find a solution how to run with more workers?

**Comment by traveller59** [comment]
same problem after 60000 step training(4 workers, 50 epochs, several hours). 
## environment:
* ubuntu 16.04
* pytorch 0.4.0a0+1709484(source)
* python 3.6.4
## Operations in dataset:
* numpy operations
* np.fromfile(read data from nvme ssd)
* numba jit functions
I don't know where the problem coming from, this is the first time I encounter this problem.

**Comment by naifrec** [comment]
Hello all,

## `segfault` issue

I seem to be facing the same issue where my data loading fails with a segmentation fault when `num_workers > 0`, otherwise the script runs fine (see traceback below). The underlying dataset is a HDF5 dataset (using `h5py`), and there are some transforms on top which mainly use `numpy`.

```python-traceback
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "experiments/script.py", line 197, in <module>
    exp.configure(clargs)
  File "experiments/script.py", line 110, in configure
    for batch in train_stream:
  File "/usr2/guillaume/code/hermes/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/usr2/guillaume/code/hermes/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr2/guillaume/code/hermes/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 33818) is killed by signal: Segmentation fault
```

## Configuration

- ubuntu 14.04
- python 3.6.5 (in a virtualenv)
- torch 0.3.1
- torchvision 0.2.0
- h5py 2.7.1
- numpy 1.14.0

**Comment by naifrec** [comment]
Hello, I resolved my issue. It was hard for me to pin-down exactly what resolved the issue. However, the main component that helped fixing it is the following: the **data you read and the python environment should be on the same mount**.

**Comment by KrnTneja** [comment]
I faced a similar problem where segmentation fault was there with `num_workers=4`. All I did was run with `num_workers=1` once and found that one of files in data was corrupted. I corrected that and again ran the model with `num_workers=4` and it worked! If one of thread is facing problem, it is not printing error and code exits with segmentation fault.

Now, I'll check the model with `num_workers=1` before trying with more workers. :)

**Comment by brtknr** [comment]
Sorry for grave digging but I am having somewhat similar issue, trying to run ./examples/dogs_cats.ipynb from fastai/fastai repo (version 1) with pytorch built from source on macOS. I have tried reducing the image size from 228 to 60 pixels and the problem seems goes away.... Also goes away when I set num_workers=0.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-1f26e5fd1026> in <module>()
      1 learn = ConvLearner(data, tvm.resnet34, metrics=accuracy)
----> 2 learn.fit_one_cycle(1)

~/Envs/ML/lib/python3.6/site-packages/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, wd, **kwargs)
     16     cbs = [OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor,
     17                              pct_start=pct_start, **kwargs)]
---> 18     learn.fit(cyc_len, max_lr, wd=wd, callbacks=cbs)
     19 
     20 def lr_find(learn:Learner, start_lr:float=1e-5, end_lr:float=10, num_it:int=100, **kwargs:Any):

~/Envs/ML/lib/python3.6/site-packages/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    131         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    132         fit(epochs, self.model, self.loss_fn, opt=self.opt, data=self.data, metrics=self.metrics,
--> 133             callbacks=self.callbacks+callbacks)
    134 
    135     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

~/Envs/ML/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_fn, opt, data, callbacks, metrics)
     84     except Exception as e:
     85         exception = e
---> 86         raise e
     87     finally: cb_handler.on_train_end(exception)
     88 

~/Envs/ML/lib/python3.6/site-packages/fastai/basic_train.py in fit(epochs, model, loss_fn, opt, data, callbacks, metrics)
     68             cb_handler.on_epoch_begin()
     69 
---> 70             for xb,yb in progress_bar(data.train_dl, parent=pbar):
     71                 xb, yb = cb_handler.on_batch_begin(xb, yb)
     72                 loss,_ = loss_batch(model, xb, yb, loss_fn, opt, cb_handler)

~/Envs/ML/lib/python3.6/site-packages/fastprogress/fastprogress.py in __iter__(self)
     59         self.update(0)
     60         try:
---> 61             for i,o in enumerate(self._gen):
     62                 yield o
     63                 if self.auto_update: self.update(i+1)

~/Envs/ML/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    345         while True:
    346             assert (not self.shutdown and self.batches_outstanding > 0)
--> 347             idx, batch = self._get_batch()
    348             self.batches_outstanding -= 1
    349             if idx != self.rcvd_idx:

~/Envs/ML/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
    324                 raise RuntimeError('DataLoader timed out after {} seconds'.format(self.timeout))
    325         else:
--> 326             return self.data_queue.get()
    327 
    328     def __next__(self):

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py in get(self, block, timeout)
     92         if block and timeout is None:
     93             with self._rlock:
---> 94                 res = self._recv_bytes()
     95             self._sem.release()
     96         else:

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py in recv_bytes(self, maxlength)
    214         if maxlength is not None and maxlength < 0:
    215             raise ValueError("negative maxlength")
--> 216         buf = self._recv_bytes(maxlength)
    217         if buf is None:
    218             self._bad_message_length()

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py in _recv_bytes(self, maxsize)
    405 
    406     def _recv_bytes(self, maxsize=None):
--> 407         buf = self._recv(4)
    408         size, = struct.unpack("!i", buf.getvalue())
    409         if maxsize is not None and size > maxsize:

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py in _recv(self, size, read)
    377         remaining = size
    378         while remaining > 0:
--> 379             chunk = read(handle, remaining)
    380             n = len(chunk)
    381             if n == 0:

~/Envs/ML/lib/python3.6/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    236         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    237         # Python can still get and update the process status successfully.
--> 238         _error_if_any_worker_fails()
    239         if previous_handler is not None:
    240             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 62155) is killed by signal: Unknown signal: 0. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
```

**Comment by mgolub2** [comment]
I have the same issue as @brtknr, with the pytorch nightly.

**Comment by mgrankin** [comment]
I've got the same error. Ubuntu 18.10, pytorch 1.0 with fastai 1.0. 
No error on images 128x128, but crashes on 512x512 with exact same message on exact same line. 
If I set num_workers=0 the error goes away but training become prohibitively slow.

**Comment by mgrankin** [comment]
I've reinstalled Ubuntu to 18.04. Same thing. 

`~/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in proc_batch(self, b)
     62     def proc_batch(self,b:Tensor)->Tensor:
     63         "Proces batch `b` of `TensorImage`."
---> 64         b = to_device(b, self.device)
     65         for f in listify(self.tfms): b = f(b)
     66         return b

~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in to_device(b, device)
     98     "Recursively put `b` on `device`."
     99     device = ifnone(device, defaults.device)
--> 100     if is_listy(b): return [to_device(o, device) for o in b]
    101     return b.to(device)
    102

~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in <listcomp>(.0)
     98     "Recursively put `b` on `device`."
     99     device = ifnone(device, defaults.device)
--> 100     if is_listy(b): return [to_device(o, device) for o in b]
    101     return b.to(device)
    102

~/anaconda3/lib/python3.7/site-packages/fastai/torch_core.py in to_device(b, device)
     99     device = ifnone(device, defaults.device)
    100     if is_listy(b): return [to_device(o, device) for o in b]
--> 101     return b.to(device)
    102
    103 def data_collate(batch:ItemsList)->Tensor:

~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    272         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    273         # Python can still get and update the process status successfully.
--> 274         _error_if_any_worker_fails()
    275         if previous_handler is not None:
    276             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 30350) is killed by signal: Segmentation fault.
RuntimeError: DataLoader worker (pid 30350) is killed by signal: Segmentation fault.`

**Comment by Tengfei-Wang** [comment]
@mgrankin  Have you found the solution?

**Comment by cswangchen** [comment]
i   got the same error 
RuntimeError: DataLoader worker (pid 18049) exited unexpectedly with exit code 127. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by stocks29** [comment]
I was running into this same issue on my mac. Ran fine with `num_workers=0` but not with more than zero unless I set the pixels to 80 or lower.

I made a few changes and now things are working:
- switched from python 3.6.8 to 3.7.6
- increased shared memory settings as described here: http://flummox-engineering.blogspot.com/2014/05/increasing-shared-memory-for-os-x.html
- installed latest versions of all libs as of this writing installed from pip

Unfortunately I did all of these things at once so it's unclear which of them actually solved the issue for me. If I have some time later, I may try to pinpoint but in a bit of a rush right now.

I'm now able to train with `num_workers=16` and 500 pixel images without issue. I hope this helps someone.

**Comment by zhangruiskyline** [comment]
Hi, I wonder why this issue get closed? do we have any conclusion that why the error happen? I got same issue, 

when I just parse the data line by line, I do not have this issue:

```
        with open(current_file, mode='rb') as f:
            text = f.read().decode('utf-8')
            all_data.extend(text.split('\n'))
```

but if I add a JSON parse logic after read line by line , it will report this error

        ```
with open(current_file, mode='rb') as f:
            text = f.read().decode('utf-8')
            all_data.extend(text.split('\n'))

        json_data = []
        for line in all_data:
            try:
                json_data.append(json.loads(line))
            except:
                break

        return json_data
```

any clue why it happened if we have JSON parse? I think it is pretty standard process, not specific to pytorch

**Comment by zhangruiskyline** [comment]
I also get from some thread that it is due to limitation of shared memory, however we have a large enough shared memory, I don't think that is a issue, any clue?

**Comment by aksg87** [comment]
Hi everyone, 

I get this issue as well. Everything works fine for 700 samples, but then things crash with a segfault.

`python --version`

Environment:
```
aiohttp==3.7.4.post0
albumentations==1.0.0
black==21.4b1
easydict==1.9
fire==0.4.0
flake8==3.9.2
GitPython==3.1.23
gpustat==0.6.0
hydra-core==1.1.0
ipykernel==5.5.4
mypy==0.812
nibabel==3.2.1
nonechucks==0.4.2
notebook==6.4.0
opencv-python==4.5.2.54
pandas==1.2.4
pipdeptree==2.0.0
pylint==2.8.2
pytorch-ignite==0.4.4
scikit-image==0.18.1
sort-requirements==1.3.0
torch-tb-profiler==0.1.0
torchio==0.18.39
torchvision==0.9.1
```

**Comment by joker512-tmp** [comment]
I also have this problem. I tried really a lot of stuff offered above and others to fix it and nothing helps. Seg fault happens pretty randomly, not after some particular hundred of image, but it's very stable.

My python version is 3.9.7, pytorch is 1.9.0.

**Comment by rbt111** [comment]
OK, I narrowed things down a little bit. If I import `torch` before `sklearn`, everything is fine; but if I import `sklearn` before `torch`, I get segmentation fault when I try to iterate through my dataloader. 
- sklearn: '0.24.2'
- pytorch: '1.10.0.dev20210910'

This may be a duplicate of #31362.

**Comment by yifanlu0227** [comment]
> Hello, I resolved my issue. It was hard for me to pin-down exactly what resolved the issue. However, the main component that helped fixing it is the following: the **data you read and the python environment should be on the same mount**.
> 
> In my specific case, the python environment was in my home directory (which resides in some remote mount, to be shared across multiple compute nodes) and the data local to the compute node. After moving everything to be local with respect to the compute node, `segfault` went away.
> 
> Hope that helps someone one day, even though that is quite a specific issue... but for me, time to [celebrate](https://youtu.be/whfBUFDuiWo) 🔥

This works for me. Thanks!!
