### ISSUE TITLE
Exporting to operator tril to ONNX opset version 10 is not supported.

### ISSUE THREAD

**Issue by nehasoni3** [pytorch/pytorch#49692]
I have tried to convert PyTorch Transformer TTS into ONNX model.
I am using this code for conversion- 
`torch.onnx.export(
        model,
        x, 
        onnx_model_name,
        export_params = True,
        opset_version = 11,
        do_constant_folding = True,
        input_names = ['input'],
        output_names = ['output'],
        dynamic_axes= {'input':[0,1],
                       'output':[0,1]})`
Here,
Model's input (x): torch.Size([1, 5])
Model's output: torch.Size([1, 80, 50])
I have used PyTorch=1.7.0 and tried ONNX opset_version=10,11 and 12. But get this error every time.
![image](https://user-images.githubusercontent.com/31642462/102810039-05485700-43e9-11eb-836c-78c31546028e.png)
#https://github.com/pytorch/pytorch/issues/49403
@spandantiwari @lara-hdr @BowenBao @neginraoof

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by nehasoni3** [comment]
@prasanthpul

**Comment by spandantiwari** [comment]
This is a known request. It is on our list of ops to support, and would likely require an addition to the ONNX spec. 
Dup'ing this to the existing issue:
https://github.com/pytorch/pytorch/issues/34129
