### ISSUE TITLE
shoud we support play pytorch  without Anaconda?

### ISSUE THREAD

**Issue by loveJasmine** [pytorch/pytorch#497]

**Comment by apaszke** [comment]
We have pip wheels too. You can find the links on http://pytorch.org.

**Comment by apaszke** [comment]
And soon `pip install pytorch` will work too.

**Comment by loveJasmine** [comment]
sure
I mean it is better we can do source installation /dev works without Anaconda

**Comment by apaszke** [comment]
Yes, I've been developing pytorch for a long time without Anaconda (and still do on my laptop). Just run `python setup.py develop` to install it in develop mode in whatever python you have (as long as it's 2.7 or 3.3+ ofc).

**Comment by apaszke** [comment]
I'm closing the issue for now, since that should work.

**Comment by recastrodiaz** [comment]
@apaszke Running `python setup.py develop` did not work for me in a virtual environment (venv, MacBook Pro, macOS Sierra v 10.12). Python couldn't find any torch modules (`ImportError: No module named 'torch.nn'`). TBH I don't know why.

However, installing a dev version with pip did the trick for me ([source](http://stackoverflow.com/questions/15031694/installing-python-packages-from-local-file-system-folder-with-pip#answer-20043907)): 
```SH
# git clone ...
cd pytorch
export MACOSX_DEPLOYMENT_TARGET=10.11 # instead of suggested 10.9
pip install -e .
```

**Comment by turingyizhu** [comment]
@apaszke Thanks for your example of building pytorch from source using pip. I just want to ask that,  before `python setup.py build_deps`, should I install those optional dependencies as in Anaconda? I mean, `conda install numpy pyyaml mkl setuptools cmake gcc cffi`. Or  `python setup.py build_deps` will take care of it? Thanks.

**Comment by apaszke** [comment]
`build_deps` is only for building the libraries that can be found in `torch/lib` (i.e. our hard C dependencies). You might want to run `conda install` with these packages first.

**Comment by turingyizhu** [comment]
@apaszke Thanks, got it.

**Comment by neverfox** [comment]
@recastrodiaz Just curious why you didn't use a 10.12 target if that's the OS you're on. I've been doing that with source builds and it seems to work.

**Comment by soumith** [comment]
the MACOSX_DEPLOYMENT_TARGET is the minimum OS version to be supported. If we use 10.9, all of 10.9+ are supported.

**Comment by neverfox** [comment]
@soumith Makes sense. So if I'm not looking to support anything but my own system, I'm good to go.

**Comment by soumith** [comment]
@neverfox yep.

**Comment by solomatov** [comment]
Are there any updates on pip install with pytorch. I want to have pytorch in requirements.txt and not to bother with creating special .sh files for installing it depending on a platform which I have.

**Comment by AlJohri** [comment]
hey @soumith, did you try the upload again by any chance?
