### ISSUE TITLE
Enable torch.nn.quantized.modules.conv typechecks during CI

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#49700]
`TestTypeHints.test_run_mypy` should pass with `[mypy-torch.nn.quantized.modules.conv]` deleted from mypy.ini

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/49549 should fix this, it will be landed soon

**Comment by guilhermeleobas** [comment]
Hi @vkuzo, I've submitted https://github.com/pytorch/pytorch/pull/49702

**Comment by vkuzo** [comment]
> Hi @vkuzo, I've submitted #49702

I see, my fault, the PR I linked is fixing a different mypy issue with quantization.  Will take a look at #49702  after CI finishes.  Thank you for helping!
