### ISSUE TITLE
libtorch load .pt succeed but foward wrong

### ISSUE THREAD

**Issue by AllentDan** [pytorch/pytorch#49729]
## 🐛 Bug

I build a exact same network as [a pytorch YOLO4](https://github.com/bubbliiiing/yolov4-pytorch) using libtorch in C++. For the backbone, it can work fine with the torch::load(darknet, darknetPath). When loading the whole yolo model to C++, I checked the value of the named_parameters and it was right. But during the first conv operation in forwarding, the output turned out ot be zeros or numbers close to zeros, which is not right.

## To Reproduce
Well, maybe a little bit hard to reproduce. 

1. Build the exact same network as [a pytorch YOLO4](https://github.com/bubbliiiing/yolov4-pytorch) using libtorch in C++.
2. Generate a torchscript file of YOLO4 and try to load .pt file to model in c++ with torch::load(model, path)
3. Forward the model then the outputs of the first conv become zeros which is not the same as in pytorch.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - LibTorch Version (e.g., 1.0): 1.7.
 - PyTorch Version (e.g., 1.0): 1.5
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source):  Pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GTX 2070S
 - Any other relevant information:

## Additional context

cc @yf225 @glaringlee @gmagogsfm

**Comment by ngimel** [comment]
@AllentDan please provide an easier way to reproduce your problem if you want it to be actionable.

**Comment by glaringlee** [comment]
@AllentDan 
If you are doing this between python version and c++ version pytorch, you need to make sure they are the same version, I saw you have pytorch 1.7 vs libtorch 1.5, this could cause problem.

**Comment by AllentDan** [comment]
@glaringlee @ngimel Thanks for your kindly reply. The problem was solved yesterday. The issue could be closed.
