### ISSUE TITLE
Program throws exception when using SyncBatchNorm with track_running_stats = False

### ISSUE THREAD

**Issue by AndysonYs** [pytorch/pytorch#49730]
## 🐛 Bug

 When using SyncBatchNorm with track_running_stats = False, the program crashes.
> AttributeError: 'NoneType' object has no attribute 'dtype'

In torch/nn/modules/_functions.py, it uses running_mean.dtype to initialize the count tensor, but when track_running_stats is false, the running_mean is None.
```
class SyncBatchNorm(Function):

    @staticmethod
    def forward(self, input, weight, bias, running_mean, running_var, eps, momentum, process_group, world_size):
        input = input.contiguous()

        count = torch.empty(1,
                            dtype=running_mean.dtype,
                            device=input.device).fill_(input.numel() // input.size(1))
```

## To Reproduce

1. Writing a distributed application with PyTorch
2. Using SyncBatchNorm and setting its attribute "track_running_stats" as False
3. Forward
4. Error occurs

The following codes show a simple example for reproducing the bug.
```
import os
import torch
import torch.distributed as dist
import torch.nn as nn
from torch.multiprocessing import Process
from torch.nn.parallel import DistributedDataParallel as DDP


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 3, kernel_size=1)
        self.bn = nn.SyncBatchNorm(3, track_running_stats=False)

    def forward(self, input):
        x = self.conv(input)
        x = self.bn(x)
        return x


def run(rank, size):
    print(f"Running basic DDP example on rank {rank}.")
    model = MyNet().cuda().to(rank)
    ddp_model = DDP(model, device_ids=[rank])
    outputs = ddp_model(torch.randn(1, 3, 10, 10))
    pass


def init_process(rank, size, fn, backend='gloo'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group(backend, rank=rank, world_size=size)
    fn(rank, size)


if __name__ == "__main__":
    size = 2
    processes = []
    for rank in range(size):
        p = Process(target=init_process, args=(rank, size, run))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
```

## Expected behaviour
It shouldn't crash.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.6.0
[pip3] torchvision==0.5.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel @albanD @mruberry @malfet @rgommers @xuzhao9 @gramster @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by AndysonYs** [comment]
cc @ezyang @malfet @rgommers @xuzhao9 @gramster @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by ngimel** [comment]
High priority, we should fix this bug.

**Comment by rgommers** [comment]
@AndysonYs can you comment on why you closed the issue?

**Comment by rohan-varma** [comment]
As another datapoint, I tested this on previous versions of PT, and if we go back to 1.5.1, we instead get the following error:

```
RuntimeError: Cannot report itemsize of Tensor that doesn't have initialized dtype (e.g., caffe2::Tensor x(CPU), prior to calling mutable_data<T>() on x)
  File "syncbn.py", line 26, in run
    outputs = ddp_model(torch.randn(1, 3, 10, 10))
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 458, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "syncbn.py", line 18, in forward
    x = self.bn(x)
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 470, in forward
    return sync_batch_norm.apply(
  File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/_functions.py", line 38, in forward
    mean, invstd = torch.batch_norm_gather_stats_with_counts(
RuntimeError: Cannot report itemsize of Tensor that doesn't have initialized dtype (e.g., caffe2::Tensor x(CPU), prior to calling mutable_data<T>() on x)
```

**Comment by AndysonYs** [comment]
> @AndysonYs can you comment on why you closed the issue?

I thought my question solved so I closed it. Should I reopen this issue? And you may close it when the bug fixed.

**Comment by AndysonYs** [comment]
> As another datapoint, I tested this on previous versions of PT, and if we go back to 1.5.1, we instead get the following error:
> 
> ```
> RuntimeError: Cannot report itemsize of Tensor that doesn't have initialized dtype (e.g., caffe2::Tensor x(CPU), prior to calling mutable_data<T>() on x)
>   File "syncbn.py", line 26, in run
>     outputs = ddp_model(torch.randn(1, 3, 10, 10))
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 458, in forward
>     output = self.module(*inputs[0], **kwargs[0])
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "syncbn.py", line 18, in forward
>     x = self.bn(x)
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 470, in forward
>     return sync_batch_norm.apply(
>   File "/home/rvarm1/anaconda3/envs/test_pt_env/lib/python3.8/site-packages/torch/nn/modules/_functions.py", line 38, in forward
>     mean, invstd = torch.batch_norm_gather_stats_with_counts(
> RuntimeError: Cannot report itemsize of Tensor that doesn't have initialized dtype (e.g., caffe2::Tensor x(CPU), prior to calling mutable_data<T>() on x)
> ```

Thanks for your reply. I think the causes of the two bugs are the same. All we need to do is find a better way to get dtype.

**Comment by malfet** [comment]
Grabbing for myself, as we should have caught those if type annotation was available, enabled for the module.

**Comment by gchanan** [comment]
why is the count even using the running_mean's dtype?  Shouldn't it be using an integer one?

**Comment by ngimel** [comment]
iirc, to be able to all-gather them in a single transaction, which you can't do for differently typed tensors (you maybe could if you view_as_type but we don't allow that (yet?))

**Comment by malfet** [comment]
This was introduced by https://github.com/pytorch/pytorch/pull/36659

**Comment by RSKothari** [comment]
Hello, I'm not quite sure what to do about this. I've disable running track and this `syncbatchnorm` does not like it. How do you advice we proceed?
