### ISSUE TITLE
RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by smivv** [pytorch/pytorch#49739]
## 🐛 Bug

Receiving error [here](https://github.com/pytorch/pytorch/blob/master/torch/quantization/quantize.py#L255):

```
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 466, in convert
    _remove_qconfig(module)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 268, in _remove_qconfig
    _remove_qconfig(child)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 268, in _remove_qconfig
    _remove_qconfig(child)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 268, in _remove_qconfig
    _remove_qconfig(child)
  [Previous line repeated 4 more times]
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 273, in _remove_qconfig
    _remove_activation_post_process(module)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 255, in _remove_activation_post_process
    for handle_id, hook_fn in module._forward_hooks.items():
RuntimeError: OrderedDict mutated during iteration
```

## To Reproduce

To reproduce just run `torch.quantization.convert(model)`

## Expected behavior

Should be no error! :)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version: 1.8.0a0 (master branch)
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: -
 - Any other relevant information: -

## Additional context

-

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
@smivv could you share an example model on which you see this?

**Comment by smivv** [comment]
@vkuzo, it's quite big to share.
The problem here not in the model itself, but in the OrderedDict which is changed on the fly.

I've managed to fix this by this snippet:

```
def _remove_activation_post_process(module):
    # TODO: maybe we should change activation_post_process to _activation_post_process
    # to prevent it from being used by user
    if hasattr(module, 'activation_post_process') and \
            is_activation_post_process(module.activation_post_process):
        delattr(module, 'activation_post_process')

    # remove activation_post_proceess hook
    handle_ids_to_remove = []
    for handle_id, hook_fn in module._forward_hooks.items():
        if hook_fn is _observer_forward_hook:
            handle_ids_to_remove.append(handle_id)

    for handle_id in handle_ids_to_remove:
        module._forward_hooks.pop(handle_id)
```

**Comment by vkuzo** [comment]
thanks for reporting, https://github.com/pytorch/pytorch/pull/49813 should help
