### ISSUE TITLE
torch.cuda.get_device_properties is missing in cuda docs

### ISSUE THREAD

**Issue by ydcjeff** [pytorch/pytorch#49737]
## 📚 Documentation

`torch.cuda.get_device_properties` is missing in both https://pytorch.org/docs/stable/cuda.html and https://pytorch.org/docs/master/cuda.html while we can still use the API.

Since it has no docstring, it doesn't show in the docs. Docs source:
```
torch.cuda
===================================

.. currentmodule:: torch.cuda

.. automodule:: torch.cuda
   :members:
```

cc @jlin27 @mruberry

**Comment by ngimel** [comment]
Thank you for reporting the issue, we'll accept a PR fixing it.

**Comment by ydcjeff** [comment]
I will send a PR
