### ISSUE TITLE
When I use distributed parallel of Pytorch, the training process always deadlock at certainty step.

### ISSUE THREAD

**Issue by shoutOutYangJie** [pytorch/pytorch#49733]
I have checked dataloader. 
```
 for iter_idx, sample in enumerate(progress_bar):
        frames, masks, info = sample
        obj_n = info['obj_n']
        obj_n = obj_n.long().item()
        print(iter_idx, train_cfg.rank, masks.shape)
        continue  # for testing dataloader
        ....... # inference and calculate loss, update parameters

```
It is ok. But after I remove "continue". The code is dead at 1047 step if I use 4 gpus. Furthermore, Interestingly, If I use 2 GPUs, the code is deadlock at 2095 step. Note that 2095*2 is approximately equal to 1047 *4.

cc @SsnL @VitalyFedyunin @ejguan @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by shoutOutYangJie** [comment]
When I find the trianing process is in deadLock, I use "Ctrl +C" to exit. You can see the information. Please help me.  

> File "train.py", line 203, in <module>
    mp.spawn(main_worker, nprocs=args.gpu_num, args=(args,))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by shoutOutYangJie** [comment]
Add more error information.
> Traceback (most recent call last):
  File "train.py", line 198, in <module>
    mp.spawn(main_worker, nprocs=args.gpu_num, args=(args,))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 78, in join
    timeout=timeout,
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^CException ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f75a8281830>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1101, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt: 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by rohan-varma** [comment]
It looks like there's a chance this might be dataloader related, due to the error line:
`^CException ignored in: <function _MultiProcessingDataLoaderIter.del at 0x7f75a8281830>`. 

Could you please share a version of your training script and environment (PyTorch version, etc) so that we can reproduce the issue? Thanks!

**Comment by shoutOutYangJie** [comment]
> It looks like there's a chance this might be dataloader related, due to the error line:
> `^CException ignored in: <function _MultiProcessingDataLoaderIter.del at 0x7f75a8281830>`.
> 
> Could you please share a version of your training script and environment (PyTorch version, etc) so that we can reproduce the issue? Thanks!

Due to large code project, I can't share it. But I find someting.
for my Dataset, each process may fetch different number  of samples. I adjust to ensure that each process can fetch uniform amount of samples, the training code is working well.

And another point is that if I want to  skip (using "continue") the certainty step at one of processes since I don't want to use corresponding samples. the training code also suffers from deadlock.

**Comment by ejguan** [comment]
> Add more error information.
> 
> > Traceback (most recent call last):
> > File "train.py", line 198, in 
> > mp.spawn(main_worker, nprocs=args.gpu_num, args=(args,))
> > File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
> > return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
> > File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
> > while not context.join():
> > File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 78, in join
> > timeout=timeout,
> > File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
> > ready = selector.select(timeout)
> > File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
> > fd_event_list = self._selector.poll(timeout)
> > KeyboardInterrupt
> > ^CException ignored in: <function _MultiProcessingDataLoaderIter.**del** at 0x7f75a8281830>
> > Traceback (most recent call last):
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1101, in **del**
> > self._shutdown_workers()
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1075, in _shutdown_workers
> > w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
> > File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 140, in join
> > res = self._popen.wait(timeout)
> > File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
> > if not wait([self.sentinel], timeout):
> > File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 920, in wait
> > ready = selector.select(timeout)
> > File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
> > fd_event_list = self._selector.poll(timeout)
> > KeyboardInterrupt:
> > Error in atexit._run_exitfuncs:
> > Traceback (most recent call last):
> > File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
> > pid, sts = os.waitpid(self.pid, flag)
> > KeyboardInterrupt
> 
> Also I set num_workers as 0, the deadlock also occurs.

I am curious how does it happen for DataLoader using `_MultiProcessingDataLoaderIter`  when num_workers is set to 0.

**Comment by shoutOutYangJie** [comment]
but it works.





------------------ Original ------------------

**Comment by shoutOutYangJie** [comment]
@ejguan  @rohan-varma  I find the reason. since My dataset has dirty samples,  I set a "while" loop to deal with dirty sample. before that, I don't know that my dataset has dirty sample. Ok, But another question arises. Why always deadlock happens at 1047 step, even I set shuffle  as "True".

```
train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    dataloader = data.DataLoader(dataset, batch_size=1, num_workers=5, pin_memory=True,
                                 sampler=train_sampler, drop_last=True)
```

>  Epoch train:   4%|___                                                                   | 1047/28691

**Comment by skyline75489** [comment]
Have you tried removing all the training code, leaving only the DataLoader code?

**Comment by shoutOutYangJie** [comment]
> Have you tried removing all the training code, leaving only the DataLoader code?

sorry, I write a dead "while" loop in my "get_item."
