### ISSUE TITLE
[Documentation missing item] Clarification on whether INT8 quantization could be beneficial for GPUs like Tesla T4 

### ISSUE THREAD

**Issue by sourabhd** [pytorch/pytorch#49741]
@gottbrath @raghuramank100  Could you clarify how the INT8 support can be used on GPUs like Tesla T4 ? (Tesla T4 is the GPU available on GCP, AWS, Azure platforms). The supported quantization backends FBGEMM and QNNPACK are for CPUs. From the Tesla T4 tensor core datasheet specifications, operations per second for single precision, mixed precision, INT8, INT4 are  8.1 T, 65 T, 130 T, 260 T respectively.  Correct me if I am wrong, higher speedups than, 2-4x speedup on Macbook Pro (from the tutorial), could be achieved, if we can make use of the power of the GPUs.

_Originally posted by @sourabhd in https://github.com/pytorch/pytorch/issues/7553#issuecomment-748438648_

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
GPU support is not ready yet, but it might be picked up some time.

**Comment by jerryzh168** [comment]
Closing for now, please let us know if you have additional questions. Also you can use discussion forum for questions. https://discuss.pytorch.org/c/quantization/17
