### ISSUE TITLE
torch.sum() ignores stride in out tensor

### ISSUE THREAD

**Issue by lvdmaaten** [pytorch/pytorch#4974]
The `torch.sum()` function writes its outputs in erroneous locations when the out `kwarg` is used. Repro:

```python
import torch

i = 1
a = torch.zeros(5, 3)
b = torch.randn(3, 5)

ac = a.clone()
ac[:, i].copy_(b.sum(0))
print(ac)

ac = a.clone()
b.sum(0, out=ac[:, i])
print(ac)
```

Output:
```bash
lvdmaaten-mbp:Desktop lvdmaaten$ python bug.py
0.0000 -0.1515 0.0000
0.0000 1.8761 0.0000
0.0000 -1.7563 0.0000
0.0000 0.5194 0.0000
0.0000 1.5322 0.0000
[torch.FloatTensor of size 5x3]
0.0000 -0.1515 1.8761
-1.7563 0.5194 1.5322
0.0000 0.0000 0.0000
0.0000 0.0000 0.0000
0.0000 0.0000 0.0000
[torch.FloatTensor of size 5x3]
```

I presume what happens is that `torch.sum()` does not respect the stride of `a[:, i]` when putting outputs in place.

Tested on PyTorch version 0.3.0.post4.

**Comment by zou3519** [comment]
Looking into it.

**Comment by fmassa** [comment]
I have the impression that the issue was added in https://github.com/pytorch/pytorch/commit/267b7ade5007060f450d4f86a210d1143d4484de , as the new codepath doesn't take the original strides of the result tensor into account.

**Comment by ngimel** [comment]
But it also fails with cuda, and that commit touches CPU path only?

**Comment by zou3519** [comment]
I think the underlying issue is that assignment to `resize_`ed slice seems to be broken. I opened a new issue for it at #4979, we'll see if fixing that fixes this.
