### ISSUE TITLE
Allow `nn.Unflatten` to take a `Sequence[int]` instead of specifically a `Tuple[int, ...]`

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#49743]
## 🚀 Feature

`nn.Unflatten` 's `unflattened_size` requires a tuple -- trying to create on using a list fails with:

```python
>>> nn.Unflatten(1, [5, 5])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-b881e5cda02d> in <module>
----> 1 nn.Unflatten(1, [5, 5])

/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/nn/modules/flatten.py in __init__(self, dim, unflattened_size)
    102 
    103         if isinstance(dim, int):
--> 104             self._require_tuple_int(unflattened_size)
    105         elif isinstance(dim, str):
    106             self._require_tuple_tuple(unflattened_size)

/opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/torch/nn/modules/flatten.py in _require_tuple_int(self, input)
    128                                     "but found element of type {} at pos {}".format(type(elem).__name__, idx))
    129             return
--> 130         raise TypeError("unflattened_size must be a tuple of ints, but found type {}".format(type(input).__name__))
    131 
    132     def forward(self, input: Tensor) -> Tensor:

TypeError: unflattened_size must be a tuple of ints, but found type list
```

I think this is a little too restrictive -- is there any reason we couldn't accept an arbitrary `Sequence` instead of specificlaly a tuple? If necessary, it should be easy to convert them to `tuple`s in the constructor.

cc @albanD @mruberry @jbschlosser

**Comment by ngimel** [comment]
Thank you for reporting the issue, we'll accept a PR fixing it.

**Comment by jonykarki** [comment]
I would like to work on this. Could you give me some suggestions on how I should tackle this?
Thank you.

**Comment by mruberry** [comment]
@jonykarki Verify that torch.Tensor.flatten accepts a list, then change the check here:

https://github.com/pytorch/pytorch/blob/22a34bcf4e5eaa348f0117c414c3dd760ec64b13/torch/nn/modules/flatten.py#L124

And update test_unflatten and test_unflatten_valid_arg in test_nn.py to validate the new behavior works as expected.

**Comment by jonykarki** [comment]
I've pushed the new changes on the new commit on the linked pull request. Let me know if I need to change anything.
