### ISSUE TITLE
What should be the eventual fate of the `THP*` C functions?

### ISSUE THREAD

**Issue by lqf96** [pytorch/pytorch#49797]
## ❓ Questions and Help
I'm currently working on a series of refactors to implement #43672, which makes `torch.Generator` picklable. One of the refactor I want to do before introducing pickling support is moving the `torch.Generator` bindings from `THPGenerator_*` APIs to Pybind11, because with Pybind11 there is no need to deal with reference counting and the code is much cleaner. However, I'm not sure if this is the right approach, since the state of `THP*` functions is not clear. If they are considered public APIs and can be used by extensions, then refactoring bindings will be backward-incompatible.

Questions:
* Should `THP*` functions be considered implementation details or public APIs?
* If they are just implementation details, should we refactor them? If yes, should we use Pybind11 or something else?

**Comment by mruberry** [comment]
@pbelevich @ezyang, can you answer @lqf96's question?

**Comment by ezyang** [comment]
THP isn't public API. Many newer APIs have been implemented directly with pybind11.

One thing to be careful about is that sometimes moving things to pybind11 will make the binding slower, because there is more indirection.  But I think this is unlikely to be a big problem for the generator APIs.

**Comment by lqf96** [comment]
That's great news! However I am still wondering about what to do with other "legacy" bindings... Maybe migrating most of them (except `torch.Tensor` which uses custom dispatch mechansim) to pybind11 is acceptable if performance does not degrade too much?

**Comment by ezyang** [comment]
Yes. In general automatic refcounting pays its way for the porting. Performance is the only possible problem.

**Comment by lqf96** [comment]
Got it. Thanks for the answer!
