### ISSUE TITLE
Pre-trained Model 실행시 정확한 텍스트가 나오지 않습니다.

### ISSUE THREAD

**Issue by kimsunglyul** [pytorch/pytorch#49796]
안녕하세요
문의사항이 있어서 질문 드립니다.
#63 를 참조하고 [UPDATED] Pre-train Models(ds2_epoch1_cer_42.pt, las_epoch1_cer_19.pt)를 다운받아 
테스트 하는데 결과가 이상하게 나옵니다.

실행
python inference.py --model_path=las_epoch1_cer_19.pt --audio_path=KsponSpeech_000001.pcm
[KsponSpeech_000001.zip](https://github.com/pytorch/pytorch/files/5734394/KsponSpeech_000001.zip)

테스트 데이터는 https://aihub.or.kr/aidata/105/download에서 받은 KsponSpeech음성입니다.

정답
[아/ 몬 소리야, 그건 또. b/]
추출
['그어 거고 이가거까기 그는나고제이다 서어보 야근게']

이전 issue 답해 주신걸 보니 feature_vector를 reverse 해보라고 하셔서 
inference.py 파일을 아래와 같이 수정하였습니다.
def parse_audio(audio_path: str, del_silence: bool = False, audio_extension: str = 'pcm') -> Tensor:
    signal = load_audio(audio_path, del_silence, extension=audio_extension)
    print(signal)
    feature_vector = torchaudio.compliance.kaldi.fbank(
        waveform=Tensor(signal).unsqueeze(0),
        num_mel_bins=80,
        frame_length=20,
        frame_shift=10,
        window_type='hamming'

    ).transpose(0, 1).numpy()

    feature_vector -= feature_vector.mean()
    feature_vector /= np.std(feature_vector)
    feature_vector = feature_vector[:, ::-1]
    feature_vector = torch.FloatTensor(np.ascontiguousarray(np.swapaxes(feature_vector, 0, 1)))

    return feature_vector

수정후에도 정상적으로 추출되지 않는것 같습니다.

이상입니다. 답변 부탁드리겠습니다.

감사합니다.

**Comment by codertimo** [comment]
혹시 잘못된 곳에 이슈를 올리신 것 같은데, 확인을 한번 해 주시면 감사하겠습니다.

**Comment by choidongyeon** [comment]
윗분 댓글에 이어, 정확히는 토치오디오 (https://github.com/pytorch/audio) 에 이슈를 올려야 하지 않을까요?

**Comment by kimsunglyul** [comment]
제가 글을 잘못 올린것 같습니다.
