### ISSUE TITLE
[ONNX][Complex] Support view_as_complex

### ISSUE THREAD

**Issue by iou2much** [pytorch/pytorch#49793]
## 🚀 Feature
would you support view_as_complex for converting to onnx model? Thanks a lot

## Motivation
when I try to convert a nn contains complex tensor computation, it says:

``` Pytorch export onnx: RuntimeError Exporting the operator view_as_complex to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator ```

also : https://github.com/onnx/onnx/issues/3173

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by iou2much** [comment]
I'm also trying to do it myself, following this doc, but I'm quite new to pytorch. I'm not sure how to implement a new method which is not standardized in Onnx.

**Comment by spandantiwari** [comment]
@iou2much - We can put this on the backlog, but we do not have immediate plans for adding support for this. Please consider sending a PR for adding support. If you are trying to export this as custom op, I think this doc could be useful.
https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator

**Comment by iou2much** [comment]
Thank you. Let me try

**Comment by urinieto** [comment]
Is there still not enough interest to support this? Note that the STFT ONNX operator on PyTorch requires this and `view_as_real` for full compatibility (https://github.com/pytorch/pytorch/pull/92087).

**Comment by justinchuby** [comment]
@urinieto we will need new onnx operators to support this. I can create an issue when I’m back

**Comment by justinchuby** [comment]
Complex number support will be handled via the torch.onnx.dynamo_export exporter.

**Comment by mush42** [comment]
When will this be available in dev builds?

**Comment by jinhonglu** [comment]
It seems that there is still problem of exporting complex number with dynamo_export

#121100

**Comment by QQian321** [comment]
> Complex number support will be handled via the torch.onnx.dynamo_export exporter.

use dynamo_export export torch.istft op, the result onnx model input was split to two real number dimensions, but not a complex number.
my PyTorch model input dimension is [1, 9, 17]（last dimension is complex number), but, onnx model input demension is [1, 9, 17, 2]

**Comment by justinchuby** [comment]
That is currently how complex values are handled. You may view the value as a complex number with view_as_complex
