### ISSUE TITLE
DOCS: Search feature hangs

### ISSUE THREAD

**Issue by ronrest** [pytorch/pytorch#498]
The search functionality in the documentation page does not really do anything. It just says 

    Searching...

And stays like that indefinitely. 

Tried it on Google Chrome, and Firefox on Ubuntu, both gave the same results.

**Comment by apaszke** [comment]
Thanks for the reports. They're generated fine locally, so it must be some bug in the builder (prob it ignores some important files).

**Comment by soumith** [comment]
i've identified the issue to be a gh-pages config problem. i'm working on fixing it.

**Comment by soumith** [comment]
now fixed :)
