### ISSUE TITLE
torch.fx.len should be supported on TorchScript

### ISSUE THREAD

**Issue by esqu1** [pytorch/pytorch#49804]
## 🐛 Bug

`torch.fx.len` is a torch.fx-compatible length function in Python meant to operate on torch.fx Proxy objects. However, it currently doesn't work with TorchScript; it would be nice to have this behavior work with both TorchScript and torch.fx so that we don't have to gate `torch.jit.is_scripting()` everywhere to switch between `len()` and `torch.fx.len()`.

## To Reproduce

```
import torch
from typing import List


class TestModule(torch.nn.Module):
    
    def __init__(self):
        super().__init__()
        
    def forward(self, x: List[torch.Tensor]) -> int:
        l = torch.fx.len(x)
        return l
    
m = torch.jit.script(TestModule())

print(m.code)
```
gives the TorchScript compiler error 
```
RuntimeError: 
Unknown type constructor Union:
  File "/mnt/xarfuse/uid-158021/5144b7ec-seed-nspid4026531836-ns-4026531840/torch/fx/proxy.py", line 170
def len(item: Any) -> Union[Proxy, int]:
                      ~~~~~~~~~~~~~~~~~ <--- HERE
    if not isinstance(item, Proxy):
        return builtins.len(item)
'len' is being compiled since it was called from 'TestModule.forward'
  File "<ipython-input-3-e28d76fab303>", line 12
    def forward(self, x: List[torch.Tensor]) -> int:
        l = torch.fx.len(x)
        ~~~~~~~~~~~~~~~~~~ <--- HERE
        return l
```

## Expected behavior

`torch.fx.len()` should behave as a normal TorchScript-compatible function.

## Additional context

Seems like `torch.fx.len` doesn't work right now because of the return type being a Union. Could we either bake this in as a special case for TorchScript or change the return type accordingly?

cc @gmagogsfm

**Comment by jamesr66a** [comment]
Probably just need to drop a `(torch.fx.len, 'aten::len')` pair here: https://github.com/pytorch/pytorch/blob/b3387139b42b48b51b8d66f9c511ecbfa00c0fe4/torch/jit/_builtins.py#L17
