### ISSUE TITLE
model prune

### ISSUE THREAD

**Issue by fxwfzsxyq** [pytorch/pytorch#49816]
I prune the model, using torch.save (model, 'model.pth') to save the model, reduces the model size by half, loads the model prediction and finds that the model takes up more GPU memory than the original model, I don't know why, is it a torch bug

**Comment by fxwfzsxyq** [comment]
In the initial stage of the model, the compressed model used less GPU memory than the original model, but in forward processing, the compressed model used more GPU memory than the original model for the same size image, the result is that the compressed model used more GPU memory, but at forward,remove "with torch.no_grad()", the compressed model takes up less GPU memory than the original model, It's so weird

**Comment by wuzuowuyou** [comment]
Does it matter if the number of channels is not the power of 2？
通道数不是2的次方会不会有影响？

**Comment by mruberry** [comment]
This question sounds more appropriate to the PyTorch forums: https://discuss.pytorch.org/. You may need to post your model, too, to get a good answer.
