### ISSUE TITLE
nonzero_numpy to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by DonggeunYu** [pytorch/pytorch#49817]
I run torch.onnx.export using opset_version=11.
My model have torch.nonzero(x, as_tuple=True)
PyTorch version = 1.7.1

Get Error
~~~
RuntimeError: Exporting the operator nonzero_numpy to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

~~~

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by kushalj001** [comment]
Any updates on this? I am facing the same issue.
