### ISSUE TITLE
Merge torch.cuda.FloatTensor with torch.FloatTensor(with is_cuda==True)

### ISSUE THREAD

**Issue by wenwei202** [pytorch/pytorch#4981]
- OS: Linux 4.4.0-109-generic #132-Ubuntu SMP 
- PyTorch version: '0.3.0.post4'
- How you installed PyTorch (conda, pip, source): pip
- Python version: Python 2.7.11 |Anaconda custom (64-bit)
- CUDA/cuDNN version: 8.0
- GPU models and configuration: GeForce GTX 1080
- GCC version (if compiling from source):

Why are there two versions of Tensor in cuda? One is `torch.cuda.FloatTensor`, and the other is `torch.FloatTensor` (with `is_cuda==True`)?
Should we merge them?

**Comment by SsnL** [comment]
`torch.FloatTensor(with is_cuda==True)` is never a thing. Where did you see it? Also I noticed that you are using `==`, could you check that it is actually a keyword?

**Comment by wenwei202** [comment]
![cuda](https://user-images.githubusercontent.com/12142066/35751060-1110cdc2-0825-11e8-85b8-ff3b9a0ba237.jpg)

**Comment by SsnL** [comment]
Isn't this just the attributes of a `torch.cuda.FloatTensor`? What am I suppose to be seeing here?

**Comment by wenwei202** [comment]
Ooh, `type(value)` is `torch.cuda.FloatTensor` although it is shown as `FloatTensor` and somehow I thought it's `torch.FloatTensor`. 

Then rises another question: why is there a `is_cuda`? Is there any chance that `is_cuda` is `False` for `torch.cuda.FloatTensor`?

**Comment by SsnL** [comment]
`torch.cuda.FloatTensor` and `torch.FloatTensor` share the same TensorBase base class that defines `is_cuda` interface. `is_cuda` is always `True` for the former and always `False` for the latter. It is useful when you want to know a tensor is on gpu or not.

**Comment by yaohuaxin** [comment]
where torch.cuda.FloatTensor and torch.FloatTensor are defined in the source code?
