### ISSUE TITLE
Make `tensor.topk` trace-able for dynamic k

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#49826]
## 🚀 Feature
Tracing of `tensor.topk` should capture `k` if it's a scalar tensor, and generalize to other values of `k`. This currently seems to be __working already__, but doesn't seem official.

The following code:
```python
import torch
from torch import nn

class M(nn.Module):
    def forward(self, x, y):
        return x.topk(y, dim=1)[1]

mod = M()
inputs = (torch.randint(0, 10, (20, 20)), torch.tensor(17))
traced_func = torch.jit.trace(mod, inputs)

test_inputs = (torch.randint(0, 9, (9, 9)), torch.tensor(8))
eager_out = mod(*test_inputs)
traced_out = traced_func(*test_inputs)
assert torch.allclose(eager_out, traced_out)

test_inputs = (torch.randint(0, 50, (50, 50)), torch.tensor(12))
eager_out = mod(*test_inputs)
traced_out = traced_func(*test_inputs)
assert torch.allclose(eager_out, traced_out)

print(traced_func.inlined_graph)
```
Can run successfully, which means the module does generalize to different shapes. However, it prints a warning that says this is not supported:
```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return x.topk(y, dim=1)[1]
```

I propose to make it a proper feature that does not print warnings, and add unittest for it.
In fact, projects like torchvision/detectron2 are already relying on the assumption that this feature is supported: https://github.com/pytorch/vision/blob/7b9d30eb7c4d92490d9ac038a140398e0a690db6/torchvision/models/detection/rpn.py#L219-L224 so this should really be made a proper feature, instead of something that "happens to work".

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
this should be fixed now

**Comment by ppwwyyxx** [comment]
Thanks!
