### ISSUE TITLE
torch.autograd.jacobian returns tensors with all zeros

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#49830]
## To Reproduce

```
import torch
tmp = torch.randn(10, 5, requires_grad=True)
def ff(x):
    return tmp.sum()
tmp_j = torch.autograd.jacobian(ff, tmp)
print(tmp_j)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
```

## Expected behavior

should return a tensor with all ones
```
import torch
tmp = torch.randn(10, 5, requires_grad=True)
def ff(x):
    return tmp.sum()
# grad works fine
tmp_j = torch.autograd.grad(ff(1), tmp)
print(tmp_j)
(tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),)
```

## Environment

PyTorch version: 1.5.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 9.0.0 (https://github.com/llvm-mirror/llvm c62b24f070c9a4bb1a76409e623042a740cac4cd)
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN V
GPU 1: TITAN V
GPU 2: TITAN V
GPU 3: TITAN V
GPU 4: TITAN V
GPU 5: TITAN V
GPU 6: TITAN V
GPU 7: TITAN V

Nvidia driver version: 440.36
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.7.so
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.5.1
[pip3] torch-cluster==1.5.7
[pip3] torch-geometric==1.6.1
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.7
[pip3] torch-spline-conv==1.2.0
[pip3] torchvision==0.6.1
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torch-cluster             1.5.7                    pypi_0    pypi
[conda] torch-geometric           1.6.1                    pypi_0    pypi
[conda] torch-scatter             2.0.5                    pypi_0    pypi
[conda] torch-sparse              0.6.7                    pypi_0    pypi
[conda] torch-spline-conv         1.2.0                    pypi_0    pypi
[conda] torchvision               0.6.1                    pypi_0    pypi

## Additional context

My function for jacobian seems strange because I want to calculate the jacobian of leanable weights w.r.t. vector outputs. Weights usually live in models and are not explicitly used.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by mruberry** [comment]
This is not a bug. It happens because in your script the function accepts `x` as an input but computes the sum of `tmp`. Running with `strict=True` would diagnose this error for you.

**Comment by youkaichao** [comment]
But the function's actual input is ``tmp``, so the output depends on the input.

**Comment by albanD** [comment]
But as Mike says, when you do 
```python
def ff(x):
    return tmp.sum()
```
what is used in the function is not what is given as input. So in this case, they are not the same thing.
You need to do
```python
def ff(x):
    return x.sum()
```
