### ISSUE TITLE
In pytorch version 1.2.0, libtorch_python.so is incompatible with libshm.so, why?

### ISSUE THREAD

**Issue by terU3760** [pytorch/pytorch#49848]
## To Reproduce

1. Install pytorch version 1.2.0 in anaconda environment, such as: conda install -c pytorch pytorch=1.2.0
1. Write some c++/python mix code and link the library libtorch_python.so and libshm.so
1. Compile it via make or cmake and it shows some function in libtorch_python.so is not found in libshm.so

## Expected behavior

====================[ Build | all | Debug ]=====================================
/******/clion-2020.3/bin/cmake/linux/bin/cmake --build /******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cmake-build-debug --target all -- -j 6
[ 25%] Building CXX object CMakeFiles/csrc.dir/cpu/nms_cpu.cpp.o
[ 50%] Building CXX object CMakeFiles/csrc.dir/cpu/ROIAlign_cpu.cpp.o
[ 75%] Building CXX object CMakeFiles/csrc.dir/vision.cpp.o
In file included from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/./cpu/vision.h:4,
                 from /******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:2:
/******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp: In lambda function:
/******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h:150:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated: passing at::DeprecatedTypeProperties to an AT_DISPATCH macro is deprecated, pass an at::ScalarType instead [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/nms_cpu.cpp:71:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms", [&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h:78:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^~~~~~~~~~~
In file included from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/ATen.h:9:0,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/./cpu/vision.h:4,
                 from /******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:2:
/******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp: In lambda function:
/******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h:150:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated: passing at::DeprecatedTypeProperties to an AT_DISPATCH macro is deprecated, pass an at::ScalarType instead [-Wdeprecated-declarations]
     at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                        ^
/******/maskrcnn-benchmark/maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
   AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] {
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/include/ATen/Dispatch.h:78:23: note: declared here
 inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                       ^~~~~~~~~~~
[100%] Linking CXX executable csrc
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/******/anaconda3/envs/pytorch_for_mask-rcnn/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined reference to `THManagedMapAllocator::fromDataPtr(c10::DataPtr const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/csrc.dir/build.make:133: recipe for target 'csrc' failed
make[2]: *** [csrc] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/csrc.dir/all' failed
make[1]: *** [CMakeFiles/csrc.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

## Environment

 - PyTorch Version (0.4.1) (torch version 1.2.0)
 - CUDA version (9.2)
 - OS (Linux)
 - How you installed PyTorch (conda install -c pytorch pytorch=1.2.0)
 - Python version (3.6)

## Additional context

Here is what I found the cause: In this file: https://github.com/pytorch/pytorch/blob/v1.2.0/torch/lib/libshm/libshm.h
or this file: https://github.com/pytorch/pytorch/blob/v0.4.1/torch/lib/libshm/libshm.h

the function definition:
......
        static THManagedMapAllocator* fromDataPtr(const at::DataPtr&);
......
if diferent from 
        THManagedMapAllocator::fromDataPtr(c10::DataPtr const&)'
in libtorch_python.so .

cc @malfet @seemethere @walterddr

**Comment by gchanan** [comment]
have you tried more recent versions of PyTorch?  It is very unlikely we'll have resources to look at issues from such an old version.

**Comment by mruberry** [comment]
Hey @terU3760, as @gchanan says, do you still have an issue with using a newer version of PyTorch, like PyTorch 1.7?

**Comment by terU3760** [comment]
Sorry, currently my hardware resources are limited, so I have to leverage some older versions of pytorch. OK, I will try to circumvent this problem. Thanks a lot.
