### ISSUE TITLE
Implement AVX2 vectorized tanh function.

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#4984]
PyTorch includes avx_mathfun.h, which includes an 8-way vectorized implementation of `exp` (exp256_ps). We'd like to use that to implement a vectorized tanh function (accessible from torch using `torch.tanh`). Currently the tanh function is not vectorized.

To get started, look into how other vectorized functions, like cadd, are implemented:

Actual implementation:
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/vector/AVX2.c
Code to figure out whether AVX2 is available dynamically and dispatch:
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/generic/THVectorDispatch.c#L47

Current place where tanh (non-vectorized) is created (you will need to modify this to do correct AVX2 dispatch, and may not be able to use the macro that currently defines it):
https://github.com/pytorch/pytorch/blob/77c792ec276ee8bf9e279ce34ecb8dac5ecbf472/aten/src/TH/generic/THTensorMath.c#L3081

@tschrager

**Comment by ezyang** [comment]
we use sleef tanh now
