### ISSUE TITLE
在两张RTX2070+一张GTX1050+一张GTX1070进行分布式运算报错：RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zhenhao-huang** [pytorch/pytorch#49847]
## 🐛 Bug

在两张RTX2070+一张GTX1050+一张GTX1070进行分布式运算报错：RuntimeError: CUDA error: no kernel image is available for execution on the device
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:19:00.0 Off |                  N/A |
| 20%   34C    P8     6W / 215W |     11MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 207...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 21%   37C    P8    13W / 215W |     11MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 105...  Off  | 00000000:67:00.0 Off |                  N/A |
| 29%   38C    P8    N/A / 100W |     11MiB /  4040MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 107...  Off  | 00000000:68:00.0  On |                  N/A |
|  0%   53C    P8    18W / 180W |    772MiB /  8111MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
2070算力是7.5，1050和1070算力是6.1,apex编译文件包含了以上算力
apex编译配置：os.environ["TORCH_CUDA_ARCH_LIST"] = "6.0;6.1;6.2;7.0;7.5;8.0"

a=torch.rand(2,3).cuda(0)
b=torch.rand(2,3).cuda(1)
c=torch.rand(2,3).cuda(2)
d=torch.rand(2,3).cuda(3)
以上四条命令可以正常运行
## To Reproduce

1.运行分布式项目报错，拉取了apex项目

## Expected behavior

满足cuda驱动算力的不同算力的显卡能否一起并行运算

## Environment

Traceback (most recent call last):
  File "finetune_chid.py", line 373, in <module>
    main()
  File "finetune_chid.py", line 261, in main
    model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "/home/klein/Desktop/CPM/CPM-Finetune/pretrain_gpt2.py", line 182, in setup_model_and_optimizer
    dist_init_required=False
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/__init__.py", line 118, in initialize
    config_params=config_params)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 181, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 609, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/engine.py", line 749, in _configure_zero_optimizer
    gradient_accumulation_steps=self.gradient_accumulation_steps())
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 395, in __init__
    self.initialize_optimizer_states()
  File "/home/klein/anaconda3/lib/python3.6/site-packages/deepspeed/runtime/zero/stage2.py", line 421, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/klein/anaconda3/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 169, in step
    group['weight_decay'])
  File "/home/klein/anaconda3/lib/python3.6/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: CUDA error: no kernel image is available for execution on the device

 - PyTorch Version (e.g., 1.0):1。6.0
 - OS (e.g., Linux):Ubuntu20
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.6.8
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:2 RTX-2070、1 GTX-1070、1 GTX-1050
 - Any other relevant information:

cc @malfet @seemethere @walterddr @ngimel

**Comment by walterddr** [comment]
could you share more detail in the reproduction step? did you mean
```
a=torch.rand(2,3).cuda(0)
b=torch.rand(2,3).cuda(1)
c=torch.rand(2,3).cuda(2)
d=torch.rand(2,3).cuda(3)
```
cannot run correctly or they can correctly but some distributed workload cannot?

**Comment by zhenhao-huang** [comment]
yeah，they run fine but some distributed workload cannot
