### ISSUE TITLE
I get CUDNN_STATUS_MAPPING_ERROR when I'm using the pytorch and tensorrt at the same time

### ISSUE THREAD

**Issue by lihaoxiang1989** [pytorch/pytorch#49850]
I get CUDNN_STATUS_MAPPING_ERROR when I'm using the PyTorch GPU calculation for preprocessing
 and Tensorrt for inference.
"ERROR: ../rtSafe/safeContext.cpp (133) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception".
when I split them to different process, it works. But is there any other solution to ensure they work together?

**Comment by ngimel** [comment]
The error is coming from tensorrt, I recommend you file an issue with them.
