### ISSUE TITLE
NN.CTCloss may be something wrong?How to decode CTC results?

### ISSUE THREAD

**Issue by laizewei** [pytorch/pytorch#49855]
pytorch 1.7.0 windows python3.7.5

I tried to train the ocr rec model with this code, where Nn. Ctcloss was used : https://github.com/WenmuZhou/PytorchOCR/tree/master/tools/rec_train.py
Loss went down to 0.02, ACC to 0.99. And then I try to deduce the model with https://github.com/WenmuZhou/PytorchOCR/tree/master/tools/rec_infer.py .The results are all wrong, not consistent with ACC.

Can you write an example of text recognition based on Nn.CTCLOSS?

**Comment by mruberry** [comment]
This question is more appropriate for our forums: https://discuss.pytorch.org/. Trying asking for examples there.
