### ISSUE TITLE
Pytorch1.7.1 Dataloader bugs on win10

### ISSUE THREAD

**Issue by daifeng2016** [pytorch/pytorch#49856]
## 🐛 Bug

Recently, I have installed Pytorch 1.7.1, cuda11.1 and python 3.8.5 on Win10. However, after training for a few epochs, errors like "PermissionError: [WinError 5]" always happened. I have tried to revise the python jurisdiction, but it failed.

## To Reproduce

1. set num_worker>0 in the dataloader function, like:
 val_dataloader_src = DataLoader(val_dataset_src, batch_size=4,
                                    shuffle=False, num_workers=1,
                                    pin_memory=True, drop_last=False)

## Expected behavior
The procedure will be crashed with the following info:
```
File "D:\Pycharm\Anaconda\lib\site-packages\tqdm\std.py", line 1165, in __iter__
    for obj in iterable:
  File "D:\Pycharm\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\Pycharm\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Pycharm\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\Pycharm\Anaconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\synchronize.py", line 104, in __getstate__
    h = context.get_spawning_popen().duplicate_for_child(sl.handle)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 99, in duplicate_for_child
    return reduction.duplicate(handle, self.sentinel)
  File "D:\Pycharm\Anaconda\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access Denied。
```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): win10 Professional
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1/8.0.4
 - GPU models and configuration: GPU0: NVIDIA 3090
 - Any other relevant information:

## Additional context

I have training the code for 30 epochs, the error will happen after 10 epochs, like 13,23,28. Sometimes, it will not happen.

cc @SsnL @VitalyFedyunin @ejguan @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mruberry** [comment]
This error indicates a permission issue on your Windows machine. Are you running with the appropriate permissions?

**Comment by daifeng2016** [comment]
Yes, I have given Anaconda and Python the highest permission. However, the errors still exist.

**Comment by mruberry** [comment]
Hm... I'm not sure how much help we can be diagnosing this issue if it actually is a Windows permissions issue related to your setup. Maybe one of our dataloader or Windows experts has encountered something like this before.

**Comment by nbcsm** [comment]
does "run as administrator" help?

**Comment by daifeng2016** [comment]
I have also tried "run as administrator" , it also failed.

**Comment by peterjc123** [comment]
Seems related: https://bugs.python.org/issue38263

**Comment by mszhanyi** [comment]
@daifeng2016 , could you please provide a demo scripts

**Comment by hildebrandt-carl** [comment]
Any updates on this?

**Comment by mantaionut** [comment]
@daifeng2016 I could not reproduce this issue. Does this issue still happens on your side?

**Comment by AmiraAlakhdar** [comment]
I am having exactly the same issue, did you manage to find a solution to it?

**Comment by mantaionut** [comment]
Hi sorry for the late reply. @AmiraAlakhdar since I am unable to reproduce the issue can you share the dataset and the code on which you encounter this issue?
