### ISSUE TITLE
ATen as a stand alone tensor library in C++

### ISSUE THREAD

**Issue by AD2605** [pytorch/pytorch#49867]
## ❓ Questions and Help

Hello all, 
I wanted to use Aten as a stand-alone tensor library and wanted to know what all parts of the source code should I copy in my project folder. I currently copied the aten and the c10 folders but functions like `at::zeros_like` are still being shown as not defined during compilation. 
TIA

**Comment by kshitij12345** [comment]
Why not use libtorch?

It is better documented and supported as the C++ frontend.

Reference:
https://pytorch.org/cppdocs/installing.html

**Comment by ngimel** [comment]
Please don't try copy-pasting files and use libtorch. Also, use discuss.pytorch.org for questions, github is for reporting bugs and requesting core features.

**Comment by AD2605** [comment]
Hi  @kshitij12345, in essence, I just want libtorch stripped off its nn and other modules and keep just its tensor part. 
I opened it as an issue here(under the discussion section) because it was more related to the source code of pytorch and might get better guidance here.
