### ISSUE TITLE
The official support for cuda 11.2 and cudnn 8.0.5

### ISSUE THREAD

**Issue by WangWenhao0716** [pytorch/pytorch#49868]
The cuda 11.2 is released. When will PyTorch officially cuda 11.2 and cudnn 8.0.5?

**Comment by caiduoduo12138** [comment]
Does it support cuda11.1 now?

**Comment by WangWenhao0716** [comment]
No



发自我的iPhone


------------------ Original ------------------

**Comment by mruberry** [comment]
This question is better asked on the PyTorch forums (https://discuss.pytorch.org/).

**Comment by stas00** [comment]
Track this issue: https://github.com/pytorch/pytorch/issues/50232 for cuda-11.2 support.
