### ISSUE TITLE
dataload bug

### ISSUE THREAD

**Issue by wshj2020** [pytorch/pytorch#49876]
## ❓ Questions and Help
hello,
I have met a question, When the data size is equal to number workers, the data read will be interrupted,and then will go on ,do you have any idea?

**Comment by mruberry** [comment]
Hi @wshj2020! Thank you for your question. Try asking it on the PyTorch forums here: https://discuss.pytorch.org/. It would be helpful if you could provide a code snippet demonstrating the issue when asking the question, too.
