### ISSUE TITLE
RFC: Add an "Implementation details" section to operators' documentation

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#49872]
Currently the documentation for a typical operator can be divided into three sections:

- a description of the operator
- detail on the operator's arguments and their behavior
- examples

See, for example, [the documentation for torch.cos.](https://pytorch.org/docs/master/generated/torch.cos.html)

This RFC proposes adding an optional additional section called "Implementation details" that describes behavior related to the operation's implementation that is too nuanced for the above sections. For example, see [the note below "Examples" for sinh](https://pytorch.org/docs/master/generated/torch.sinh.html), which describes the large value rounding behavior for vectorized CPU operations. Or see [the documentation for cholesky_inverse](https://pytorch.org/docs/master/generated/torch.cholesky_inverse.html), where the LAPACK calls used to implement the function appear in the operator's description. This information seems extremely prominent in the operator's description, however, and not the most important thing to communicate to the typical reader of the documentation. 

Putting information like this into an "Implementation details" section seems like a clearer and more scalable approach that will leave our documentation uncluttered while letting us clarify operator nuances. This optional section could appear just before or after the examples section.

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
Triage review to socialize.

**Comment by gchanan** [comment]
aside: is it possible in our docs to dynamically hide/show such a section?

**Comment by mruberry** [comment]
@ngimel points out that this information may become stale quickly

**Comment by mruberry** [comment]
We tried doing this with linear algebra operators and found it more tedious than it was worth.
