### ISSUE TITLE
float16 tensors in CPU should be able to be flipped

### ISSUE THREAD

**Issue by lan-qing** [pytorch/pytorch#49889]
## To Reproduce

        >>> a = torch.tensor([1,2])
        >>> a.flip(-1)
        tensor([2, 1])
        >>> a = torch.tensor([1,2]).cuda()
        >>> a.flip(-1)
        tensor([2, 1], device='cuda:0')
        >>> a = torch.tensor([1,2]).half().cuda()
        >>> a.flip(-1)
        tensor([2., 1.], device='cuda:0', dtype=torch.float16)
        >>> a = torch.tensor([1,2]).half()
        >>> a.flip(-1)
        Traceback (most recent call last):
            File "<input>", line 1, in <module>
        RuntimeError: "flip_cpu" not implemented for 'Half'

## Expected behavior

 torch.tensor([1,2]).half() should be flipped

## Environment
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS (x86_64)
GCC version: (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
Clang version: 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.2.148
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.64.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py37he8ac12f_0    defaults
[conda] mkl_fft                   1.2.0            py37h23d657b_0    defaults
[conda] mkl_random                1.1.1            py37h0573a6f_0    defaults
[conda] numpy                     1.19.2           py37h54aff64_0    defaults
[conda] numpy-base                1.19.2           py37hfa32c7d_0    defaults
[conda] pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.8.2                py37_cu102    pytorch

**Comment by gchanan** [comment]
Thank you for the request, @lan-qing.  We would accept a PR addressing this.
