### ISSUE TITLE
How to apply functions to nested modules?

### ISSUE THREAD

**Issue by 121898** [pytorch/pytorch#49888]
## ❓ Questions and Help

Hi, all,
        I understood when we want to apply a certain function to layers in a model, we can call self.apply(_function). For instance, apply weight norm to all convolutional layers. I checked the document of module.apply(), where its says the function will be applied to all the children.
       My question is, if the model is complicated, say
```python
Block1=nn.Sequential(nn.Linear(10,10), nn.Linear(10,10))
Block2=nn.Sequential(nn.Linear(10,10), nn.Linear(10,10))
Model=nn.Sequential([nn.Linear(2,10), Block1, Block2])
```
Now if I want to apply a certain function on all linear layers (say a certain weight initialization), I can not directly call Model.apply(_function), right? Is there any elegant way to do this when nested modules are presented?
Thanks a lot!

cc @albanD @mruberry @jbschlosser

**Comment by gchanan** [comment]
I'm not sure I understand, can you check if the module is a Linear layer in the function yourself?

**Comment by mruberry** [comment]
Hey @121898, this question is probably better asked on our forums, here: https://discuss.pytorch.org/.

`apply` will be called on all children, even children nested within other modules, and as @gchanan suggests if you want the applied function to only apply to certain layers then those layers can be filtered to in the function itself, or a module's children can be directly iterated over.
