### ISSUE TITLE
Exporting the operator any to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by tengerye** [pytorch/pytorch#49887]
## 🐛 Bug

I tried to convert my model to onnx using `torch.onnx.export`.

## To Reproduce

To keep it short my model has the layer that `graph_node_mask=graph_node_mask.any(dim=-1, keepdim=True)`

The error message is: `RuntimeError: Exporting the operator any to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
`

## Expected behavior

Successfully conversion.

## Environment

PyTorch version: 1.6.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.14.7

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.6.0+cu101
[pip3] torchtext==0.7.0
[pip3] torchvision==0.7.0+cu101
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] torch                     1.6.0+cu101              pypi_0    pypi
[conda] torchtext                 0.7.0                    pypi_0    pypi
[conda] torchvision               0.7.0+cu101              pypi_0    pypi

## Additional context

Is there any supported operations for now that I can use to get around the error?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@tengerye - thanks for reporting this. To help us prioritize, which models require this op?
We can put it on our backlog, but we may not be able to get to it right away. Could you please consider sending a PR for adding support for this?

**Comment by tengerye** [comment]
@spandantiwari Hi, the project I was working on is [this](https://github.com/wenwenyu/PICK-pytorch). I would like to help, but I have no idea how to fix it.

**Comment by shubhambhokare1** [comment]
Extended support for any was added in https://github.com/pytorch/pytorch/pull/66093
Let me know if these changes resolve your issue.

**Comment by shubhambhokare1** [comment]
Support added in pytorch release, closing for now.
