### ISSUE TITLE
Bug when using DDP and EasyDict

### ISSUE THREAD

**Issue by poodarchu** [pytorch/pytorch#49883]
## 🐛 Bug

https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/scatter_gather.py#L27
if the obj here is an easydict, it will through AttributeError: 'tuple' object has no attribute 'items'

## To Reproduce

here we use https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/data/datasets/coco.py#L133 as an example, if we replace this line with dataset_dict = EasyDict(copy.deepcopy(self.dataset_dicts[index])), the error will occur.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by ngimel** [comment]
scatter is not used in DDP other than in single process multiple device mode, and that mode will likely be discontinued #47012.

**Comment by mrshenli** [comment]
+1 to @ngimel's comment above. Beside, IIUC, `EasyDict` is not an official type in Python, so it does not make sense to introduce specialize handling in `scatter` to support `EasyDict`. I am closing this issue. @poodarchu please feel free to reopen if you believe EasyDict should be added to PyTorch as a dependency.
