### ISSUE TITLE
OS bug Library not loaded: @rpath/libiomp5.dylib

### ISSUE THREAD

**Issue by Yvaine** [pytorch/pytorch#4989]
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jing/anaconda3/envs/python36/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: dlopen(/Users/jing/anaconda3/envs/python36/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/jing/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/libTH.1.dylib
  Reason: image not found

**Comment by apaszke** [comment]
Please use the issue template. There are a couple extra details we need to properly debug your issue like your system details and the way you used to install pytorch. Please copy the template and fill it in.

**Comment by Mabinogiysk** [comment]
I have the same problem:
- OS: Mac OS
- PyTorch version: 0.3.0
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.4
- CUDA/cuDNN version: None

~/anaconda3/lib/python3.6/site-packages/torch/__init__.py in <module>()
     54 except ImportError:
     55     pass
---> 56 from torch._C import *
     57 
     58 __all__ += [name for name in dir(_C)

ImportError: dlopen(~/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: ~/anaconda3/lib/python3.6/site-packages/torch/lib/libTH.1.dylib
  Reason: image not found

I have updated Anaconda3 and reinstalled it, which did not work.

**Comment by Yvaine** [comment]
- OS: macOS High Sierra, version 10.13.3
- PyTorch version: pytorch 0.3.0 py36_cuda0.0_cudnn0.0h57b1bc9_4    pytorch
- How you installed PyTorch (conda, pip, source):conda install pytorch torchvision -c pytorch
- Python version:3.6.4
- CUDA/cuDNN version:none
- GPU models and configuration:none
- GCC version (if compiling from source):none

I try to install from source, find some error relate iomp5, as follows:
Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /Users/jing/anaconda3/envs/python36/lib/libmkl_core.dylib
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel.dylib
--   Library mkl_intel_thread: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /Users/jing/anaconda3/envs/python36/lib/libmkl_core.dylib
--   Library iomp5: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel_lp64: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /Users/jing/anaconda3/envs/python36/lib/libmkl_core.dylib
--   Library guide: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - guide - pthread - m]
--   Library mkl_intel: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel.dylib
--   Library mkl_intel_thread: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /Users/jing/anaconda3/envs/python36/lib/libmkl_core.dylib
--   Library guide: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_lp64.dylib
--   Library mkl_intel_thread: /Users/jing/anaconda3/envs/python36/lib/libmkl_intel_thread.dylib
--   Library mkl_core: /Users/jing/anaconda3/envs/python36/lib/libmkl_core.dylib
--   Library pthread: /usr/lib/libpthread.dylib
--   Library m: /usr/lib/libm.dylib
-- MKL library found

  thanks!@apaszke

**Comment by Yvaine** [comment]
I have success import torch, i have install intel mkl, command is
conda install -c intel mkl
(python36) jing@yvaines-MBP> conda install -c intel mkl                                                                ~ 11:08:06
Fetching package metadata ...........................
Solving package specifications: .

Package plan for installation in environment /Users/jing/anaconda3/envs/python36:

The following NEW packages will be INSTALLED:

    openmp: 2018.0.0-intel_8    intel

The following packages will be UPDATED:

    mkl:    2018.0.1-hfbd8650_4 anaconda --> 2018.0.1-intel_5 intel

Proceed ([y]/n)? y

openmp-2018.0. 100% |##################################################################################| Time: 0:00:31  29.36 kB/s
mkl-2018.0.1-i 100% |##################################################################################| Time: 0:24:43  90.80 kB/s
mkl-2018.0.1-i 100% |##################################################################################| Time: 0:11:46 190.79 kB/s
(python36) jing@yvaines-MBP> python                                                                                    ~ 12:15:19
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
@apaszke @Mabinogiysk

**Comment by Mabinogiysk** [comment]
This did not work for me. I have updated mkl and I still have the same issue.

**Comment by Mabinogiysk** [comment]
It works! I have not noticed that the update failed.
