### ISSUE TITLE
Strange behavior related to `torch.cuda.Stream`

### ISSUE THREAD

**Issue by thuzhf** [pytorch/pytorch#49915]
## To Reproduce

```python3
import torch

# We will use GPU-0 and GPU-1.
torch.cuda.synchronize(0)
torch.cuda.synchronize(1)

to_copy = torch.ones(100, device=0)

# Introduce a separate stream for copy and synchronize to the default stream.
# The copy will be started when "to_copy" is ready.
copy_stream = torch.cuda.Stream(0)
copy_stream.wait_stream(torch.cuda.default_stream(0))

with torch.cuda.stream(copy_stream):
    torch.cuda._sleep(100000000)
    copied = to_copy.to(1)

    # Try to uncomment any one of following two lines and rerun.
    #print(copied[0])
    #copied.sum().item()

    to_copy = None

# Here's any computation which allocates some new tensors on the default stream.
other = torch.rand(100, device=0)

# It will be 100 or about 50 depending on whether you comment print(copied[0]) or copied.sum().item().
print(copied.sum().item())
```

## Expected behavior

Whether you comment the code `print(copied[0])` or `copied.sum().item()` should not impact the result of the last print. And the result should be always about 50.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0/8
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

CC: @ngimel @albanD @ezyang

**Comment by ngimel** [comment]
You are using `copied`
1) on the stream other than the one it was allocated on
2) before the copy on the side stream has finished
You also delete `to_copy` before it's been used, so that the memory that was supposed to be `to_copy` is reused for `other`.  For more discussion see #15568.
In short, what you are seeing is expected behavior.

**Comment by thuzhf** [comment]
@ngimel What you said is exactly what I expect. But the result is not as what we expect. As I pointed out, when you uncomment `print(copied[0])` or `copied.sum().item()`, the memory of `to_copy` is **not** reused for `other`. That's what I do not expect.

**Comment by SsnL** [comment]
The print or .item just synchronizes so that the copy is completed before the new tensor is created.
