### ISSUE TITLE
RuntimeError: Unrecognized tensor type ID: AutogradCUDA

### ISSUE THREAD

**Issue by Malithi-gif** [pytorch/pytorch#49925]
```
Traceback (most recent call last):
  File "align.py", line 76, in <module>
    output = layer(input, proposal)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "align.py", line 59, in forward
    out = align1d(input, rois, self.feature_dim, self.ratio)
  File "align.py", line 18, in forward
    input, roi, feature_dim, ratio
RuntimeError: Unrecognized tensor type ID: AutogradCUDA
Exception raised from dispatchKeyToBackend at /usr/local/lib/python3.7/site-packages/torch/include/c10/core/Backend.h:124 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f18e1a528b2 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1dde2 (0x7f18c9eefde2 in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
frame #2: at::Tensor::type() const + 0x41 (0x7f18c9ef4185 in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
frame #3: Align_forward_cuda(at::Tensor const&, at::Tensor const&, float, int, int) + 0x5b (0x7f18c9ef13d0 in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
frame #4: Align_forward(at::Tensor const&, at::Tensor const&, int, int) + 0x25 (0x7f18c9ee4325 in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1d708 (0x7f18c9eef708 in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x1a9af (0x7f18c9eec9af in /content/drive/My Drive/GTAD/gtad_lib/Align1D.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x93d (0x7f191ed8800d in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #33: __libc_start_main + 0xe7 (0x7f193a61cbf7 in /lib/x86_64-linux-gnu/libc.so.6)
```

My cuda version 10.1 torch 1.7.1

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @ngimel

**Comment by mruberry** [comment]
Thank you for reporting this issue, @Malithi-gif. Do you have a short self-contained script we can review that will reproduce this issue?

**Comment by Malithi-gif** [comment]
@Mike Ruberry I try to run align.py

**Comment by mruberry** [comment]
Do you have a link to that file, at least?

**Comment by Malithi-gif** [comment]
> Do you have a link to that file, at least?

# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
import torch
from torch import nn
from torch.autograd import Function
from torch.autograd.function import once_differentiable
from torch.nn.modules.utils import _pair

import Align1D as _align_1d

class _Align1D(Function):
    @staticmethod
    def forward(ctx, input, roi, feature_dim, ratio):
        ctx.save_for_backward(roi)
        ctx.feature_dim = feature_dim
        ctx.input_shape = input.size()
        ctx.sampling_ratio = ratio
        output = _align_1d.forward(
            input, roi, feature_dim, ratio
        )
        return output

    @staticmethod
    @once_differentiable
    def backward(ctx, grad_output):
        rois, = ctx.saved_tensors
        feature_dim = ctx.feature_dim
        bs, ch, t = ctx.input_shape
        ratio = ctx.sampling_ratio
        grad_input = _align_1d.backward(
            grad_output,
            rois,
            feature_dim,
            bs,
            ch,
            t,
            ratio
        )
        return grad_input, None, None, None, None


align1d = _Align1D.apply


class Align1DLayer(nn.Module):
    def __init__(self, feature_dim, ratio=0):
        super(Align1DLayer, self).__init__()
        self.feature_dim = feature_dim
        self.ratio = ratio

    def forward(self, input, rois):
        # print('- input shape is', input.shape)
        # print('- input mean is', input.mean())
        # print('- rois shape is', rois.shape)
        # print('- rois is on', rois.get_device())
        assert input.device==rois.device, 'Align operation requires ' + \
			'both feature and roi are on the same device! ' + \
            'Get feature on {} but roi on {}'.format(input.device,rois.device)

        out = align1d(input, rois, self.feature_dim, self.ratio)
        # print('- output shape is', out.shape)
        # print('- output mean is', out.mean())
        return out

    def __repr__(self):
        tmpstr = self.__class__.__name__ + "("
        tmpstr += "feature_dim=" + str(self.feature_dim)
        tmpstr += "sampling_ratio=" + str(self.ratio)
        tmpstr += ")"
        return tmpstr

if __name__ == "__main__":
    layer = Align1DLayer(10)
    # layer = torch.nn.DataParallel(layer, device_ids=[0,1])
    input = torch.tensor([[[1.,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]]]).cuda()
    proposal = torch.tensor([[0,-0.5,9.5],[0,0.1,0.9]]).cuda()
    output = layer(input, proposal)
    print("output has shape {}, with mean {}".format(output.shape, torch.mean(output)))
    print(output)

**Comment by mruberry** [comment]
OK but that script imports Align1D, so I can't reproduce this issue because I don't know what Align1D is or have it.

Would you please write a single script that I can execute?

**Comment by ngimel** [comment]
The library you are using, gtad, did not update their custom op registrations according to https://pytorch.org/tutorials/advanced/dispatcher.html. It's a problem of that library, please file an issue with them https://github.com/frostinassiky/gtad
