### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_memoryStats'

### ISSUE THREAD

**Issue by AmitSharma1127** [pytorch/pytorch#49923]
## To Reproduce

1. Clone this repo: https://github.com/levindabhi/SieveNet
2. Follow the steps in readme.md
3. Run train.py (one of the steps in readme.md)
4. After training for a while, the folowing error occurs

## Error
```
Traceback (most recent call last):
  File "train.py", line 298, in <module>
    main()
  File "train.py", line 248, in main
    train_gmm(opt, train_loader, model, board)
  File "train.py", line 68, in train_gmm
    board.add_scalar('GPU Allocated', round(torch.cuda.memory_allocated(0)/1024**3,1), step+1)
  File "/home/local/ALGOANALYTICS/asharma/anaconda3/envs/sievenet/lib/python3.7/site-packages/torch/cuda/memory.py", line 279, in memory_allocated
    return memory_stats(device=device)["allocated_bytes.all.current"]
  File "/home/local/ALGOANALYTICS/asharma/anaconda3/envs/sievenet/lib/python3.7/site-packages/torch/cuda/memory.py", line 160, in memory_stats
    stats = memory_stats_as_nested_dict(device=device)
  File "/home/local/ALGOANALYTICS/asharma/anaconda3/envs/sievenet/lib/python3.7/site-packages/torch/cuda/memory.py", line 170, in memory_stats_as_nested_dict
    return torch._C._cuda_memoryStats(device)
AttributeError: module 'torch._C' has no attribute '_cuda_memoryStats'
```

## Expected behavior
The training should have finished and the results should've been similar to mentioned in the above mentioned repo (https://github.com/levindabhi/SieveNet)

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 14.04.6 LTS (x86_64)
GCC version: (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5
Clang version: Could not collect
CMake version: version 2.8.12.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.1               py3.7_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.2.1                    py37_0

cc @ngimel

**Comment by kshitij12345** [comment]
I think you should use the pytorch version mentioned in the requirements.txt instead of 1.7.1 . That should mostly do the trick.

https://github.com/levindabhi/SieveNet/blob/master/requirements.txt

**Comment by AmitSharma1127** [comment]
> 
> 
> I think you should use the pytorch version mentioned in the requirements.txt instead of 1.7.1 . That should mostly do the trick.
> 
> https://github.com/levindabhi/SieveNet/blob/master/requirements.txt

I started off with the usual practice of installing the requirements from this file but there were so many compatibility issues that after a lot of hit and trial, I could make an environment that, somehow, could let be start the training. But after a while this error pops up. But I do get your point, this is mostly a compatibility issue between various modules. But, dissecting the root cause would really make assumptions very concrete

**Comment by mruberry** [comment]
This error seems strange since I think this function does exist.

**Comment by ngimel** [comment]
You don't have cuda available, so this function is expected to fail:
```
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
```
