### ISSUE TITLE
use LibTorch.podspec,build in local can not success

### ISSUE THREAD

**Issue by IDwangluting** [pytorch/pytorch#49921]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by mruberry** [comment]
Hey @IDwangluting, looks like this issue is empty so I'm going to close it. If you're experiencing an issue would you create a new one with a description of the problem you're facing?

**Comment by IDwangluting** [comment]
the file is prepared ,when l build ,error , Desktop/pytorch/ios/TestApp/Pods/Headers/Public/LibTorch/LibTorch.h:4:10: 'torch/script.h' file not found
