### ISSUE TITLE
CUDA error: invalid configuration argument during backward through torch.cdist

### ISSUE THREAD

**Issue by wanyu2018umac** [pytorch/pytorch#49928]
## 🐛 Bug

When back-propagating through torch.cdist operator, the GPU device throws an RuntimeError exception titled:
```
CUDA error: invalid configuration argument.
```

## To Reproduce

1. create a Python file 'test.py':
```
import torch

for i in range(510, 520):
    a = torch.zeros((4, i, 32)).normal_(0, 1).cuda()
    b = torch.zeros((4, i, 32)).normal_(0, 1).cuda()
    a.requires_grad = True
    b.requires_grad = True
    c = torch.cdist(a, b, p=1.0)
    print(c.size())
    d = c.mean()
    d.backward()
    print(a.grad.size(), b.grad.size())
```

2. Run command 'python test.py', and it shows the output like:

```
torch.Size([4, 510, 510])
torch.Size([4, 510, 32]) torch.Size([4, 510, 32])
torch.Size([4, 511, 511])
torch.Size([4, 511, 32]) torch.Size([4, 511, 32])
torch.Size([4, 512, 512])
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    d.backward()
  File "/home/wanyu/anaconda3/envs/pt1.7/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/wanyu/anaconda3/envs/pt1.7/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: invalid configuration argument
```

## Expected behavior

Wish this issue can be fixed.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.12.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 450.80.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch

## Additional context

It seems to me that this issue is relevant to Issues #27209 #31593 and pull requests #31167 #31593.

And this is just my guessing. The program fails at 'i' being 512, leading to the number of elements as 4 * 512 * 32 = 65,536. The afrementioned issues and pull requests also mentioned that the y/z-dimension of grid (gridDim.y/z, the maximum number of blocks along dimension y/z within each grid) should not exceed 65,535. Maybe this setting goes beyond the maximum value of grid size (gridDim.y > 65,535 or gridDim.z > 65.535).

Wish this can offer help. Thanks!

cc @ngimel

**Comment by mruberry** [comment]
This reproduces on Colab.

**Comment by wanyu2018umac** [comment]
Hi any updates?

**Comment by ngimel** [comment]
`cdist` for the common case of p=2 was fixed in #31167. You analysis is correct, "invalid configuration argument" means gridDim.y or gridDim.z more than 65535. THe kernel itself is probably pretty inefficient. We will accept a PR fixing this.

**Comment by wanyu2018umac** [comment]
Thanks! So should I open a PR for this? I'm new on using PR submission.🤦‍♀️

**Comment by ngimel** [comment]
Yes, you should create a fix, make sure that it works locally and submit a PR. Please see https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for more details.

**Comment by wanyu2018umac** [comment]
I'll try. Thanks!

**Comment by wanyu2018umac** [comment]
> Yes, you should create a fix, make sure that it works locally and submit a PR. Please see https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for more details.

Hi I've submitted a PR😆

**Comment by RuABraun** [comment]
@ngimel I'm still getting the error with `p=2` !

**Comment by wanyu2018umac** [comment]
> @ngimel I'm still getting the error with `p=2` ! pytorch-1.8.0.dev20210202
> 
> Hard to reproduce though (it definitely is because of `cdist`, but I can't reproduce it when I create a 5-line example)

Hi sorry for my late response!

I haven't updated it yet, and now I'm finding a way to upload my changes into origin branch.

FYI you can refer to #50536 #51569 for progress.
