### ISSUE TITLE
torch.flatten is inconsistent with NumPy's flatten

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#49954]
NumPy's flatten always makes a copy of its input's data (see [its documentation](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)). PyTorch's flatten, on the other hand, returns the input itself or a view of input when possible. 

For a bit of additional context, PyTorch has ravel, which is consistent with NumPy's ravel. 

Deprecating this behavior might be painful. A thorough deprecation would need to do something like:

- update ravel to allow flattening a range of dims
- deprecate flatten in favor of ravel
- remove flatten
- restore flatten with the new behavior

cc @mruberry @rgommers @heitorschueroff

**Comment by ngimel** [comment]
Tbh, I don't see a point in deprecating `flatten`. It's breaking users without serving any useful purpose. People who want `copy` functionality can call `flatten().contiguous()`, that seems much easier than going through deprecation cycle.

**Comment by rgommers** [comment]
> Tbh, I don't see a point in deprecating `flatten`.

I agree, I think this is a difference with numpy that should just be documented and stay as is. The deprecation plan is too long/painful, for limited gain.

Copy/view returns are pretty inconsistent in NumPy's design, and sometimes just an artifact of history. The goal was always to return views whenever possible. I'm not sure about the history in this case, it's possible `np.flatten` failed to return a view by accident, and was explicitly documented as a copy operation after the fact.

**Comment by mruberry** [comment]
I agree with you both, @ngimel and @rgommers. The distinction between ravel and flatten in NumPy seems odd to me: they're the same function except flatten always copies. That distinction is so subtle, and the behavior so easy to replicate (although `flatten().contiguous()` will not always do it), that it seems like an issue with NumPy's UX.

PyTorch is also systemically inconsistent with NumPy's view behavior because we don't support negative strides. 

On the other side of this, I wonder if flatten was an attempt to disambiguate between view/reshape operations creating views or silently copying data. That is, there is a bigger issue here that view ops sometimes return self, a view, or a tensor with its own storage. Returning self or a view seems maybe OK, but I wonder if we were designing PyTorch's UX from scratch (which @rgommers & co. are kind of doing...) we would not allow view or (silent) copy behavior because these things have different write semantics, and the change in performance memory usage may be surprising.

**Comment by rgommers** [comment]
> if we were designing PyTorch's UX from scratch (which @rgommers & co. are kind of doing...) we would not allow view or (silent) copy behavior because these things have different write semantics, and the change in performance memory usage may be surprising

Not really doing that - https://data-apis.org/ is more like synthesis, intersection of what's common between libraries and only fix something in case of serious flaws - wish we could though:)

If we had a clean slate, I would consider making data read-only on creation of views, and ability to turn on copy-on-write.

> That distinction is so subtle, and the behavior so easy to replicate (although flatten().contiguous() will not always do it), that it seems like an issue with NumPy's UX.

Agreed. Not a fixable one I'm afraid, `flatten` is too heavily used to consider touching it.

**Comment by mruberry** [comment]
Great. Let's close this issue.

@ngimel and I had a follow-up conversation offline about returning self, views and sometimes copying the data. We think it will be helpful to inform people that PyTorch's UX is designed to aggressively return views where possible, and that users who perform inplace operations simply need to be mindful of this.

**Comment by mruberry** [comment]
I added a section to the developer faq here: https://github.com/pytorch/pytorch/wiki/Developer-FAQ#reshaping-operations-and-returning-self-a-view-or-a-tensor-with-its-own-storage.
