### ISSUE TITLE
Improve JIT Python interface safety

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#49969]
## 🚀 Feature
I propose to improve the Python JIT interface safety by wrapping the "custom ownership" C++ classes like Node, Value, and Block in smart pointers supporting invalidation.

## Motivation

Currently the JIT Python bindings for Node, Block, Value and potentially others (where the ownership model is "owned by graph, handed out as raw pointers, but may be destroyed at will" work with essentially raw pointers, making it too easy to access freed memory, which is bad (and might lead to crashes).

## Pitch

(At least) for the Python bindings we should wrap the objects using a custom shared smart pointer which supports invalidation that is done when destroying the C++ object wrapped by the Python object.

This would involve (e.g. for a Node):
- create a wrapper (struct with a (raw) pointer to a Node) when creating a node, hold on to that with a shared_ptr,
- set the wrapper's pointer to the node to `nullptr` on destruction,
- cause PyBind11 to check and dereference the wrapper at each invocation. This can be done using a custom caster (see https://github.com/pybind/pybind11/issues/2751).

This won't give us thread safety, but at least we don't crash from Python by using Python Node objects pointing to invalid memory.

## Alternatives

- Keep stuff unsafe.
- Move to some smart-pointer thing for C++, too, and use some invalidation scheme there.

## Additional context

This would cause the creation of an additional struct and a smart pointer to it in each instantiation of a Node (etc.) and clearing the pointer on destruction, which would be the main perf impact. All other changes only affect the Python bindings, which I would think that is less critical.

I do have experimental code doing this and am looking to be able to build a subgraph-creating pass (say, similar to `create_autodiff_subgraphs` from Python).

cc @gmagogsfm

**Comment by wanchaol** [comment]
@t-vi are you currently working on this?

**Comment by t-vi** [comment]
Yes, so I have a branch that does this as part of the [ScriptTorch](https://lernapparat.de/scripttorch/) effort of trying to make TorchScript-by-default possible in PyTorch, but I wanted to also get feedback if this is considered OK in general. 
(I tried to pitch it to @eelison today.)

I can send a PR if the general direction sounds like it could be tried (subject to not degrading performance etc.).

**Comment by wanchaol** [comment]
nice, we had a brief discussion on this and it sounds a good idea, assigning this to you then. cc @suo @eellison

**Comment by t-vi** [comment]
It turns out that PyBind seems to still cache entries based the raw pointer we're wrapping. This is bad becasue the next object from the new reference will then be "accessed" through the old wrapper.
