### ISSUE TITLE
PyTorch does not respect GOMP_CPU_AFFINITY environment variable

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#49971]
## 🐛 Bug

After importing PyTorch, GOMP_CPU_AFFINITY variable is not respected anymore.

## To Reproduce

1. Run ``` GOMP_CPU_AFFINITY=4-15 taskset -c 4-15 python -c "import psutil, torch; print(psutil.Process().cpu_affinity())"```

## Expected behavior

Should print [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15].

Actually, it prints:
[4]

## Environment

Amazon EC2, CPU  Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 Cores, HT disabled)

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
Clang version: Could not collect
CMake version: version 3.13.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.15.4
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1           py37h4f9e942_0
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.7.1           py3.7_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] torchtext                 0.8.1                      py37    pytorch
[conda] torchvision               0.8.2                py37_cu110    pytorch

## Additional context

Result of both ``` GOMP_CPU_AFFINITY=4-15 taskset -c 4-15 python -c "import psutil; print(psutil.Process().cpu_affinity())"``` (doesn't import torch) and ``` taskset -c 4-15 python -c "import psutil, torch; print(psutil.Process().cpu_affinity())"``` (doesn't set GOMP_CPU_AFFINITY variable) are correct.

Both of them print:
[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

cc @VitalyFedyunin

**Comment by malfet** [comment]
@xuzhao9 "GOMP_CPU_AFFINITY" controls CPU behaviour of GNU OpenMP library, whilst standard PyTorch is build with Intel OpenMP library, therefore you need to use "KMP_AFFINITY", see https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/thread-affinity-interface-linux-and-windows.html for more details.

**Comment by wconstab** [comment]
@malfet i don't know how things are implemented, but experimentally I found GOMP to work while KMP didn't work.  (by 'work' i mean htop shows my pytorch program using intended cores for BLAS calls when using the GOMP variable.)

Intel docs say they support both variables: https://software.intel.com/content/www/us/en/develop/articles/thread-affinity-compiler-options-and-environment-variables.html 

Are you sure that using GOMP_ should not work in pytorch for some reason?

**Comment by xuzhao9** [comment]
Just FYI, on the nightly build pytorch-1.8.0.dev20210122, the shared library "libtorch.so" links to libgomp instead of libiomp:

    $ ldd libtorch.so
    # ...
     libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f2065287000)

**Comment by walterddr** [comment]
checked with all 1.7.1 and nightly wheel & conda builds.
1. all linux wheel builds are bundled with libgomp_<commit_hash>.so.1, and conda builds are dynamic linked with libgomp.so.1 on system path.
2. all macos builds refers to libiomp5.dylib, again wheel has it packaged together and conda refers to system path.

judging by the fact that this also happends on 1.7.1 I guess this was always how we release binaries.

**Comment by xuzhao9** [comment]
> checked with all 1.7.1 and nightly wheel & conda builds.
> 
> 1. all linux wheel builds are bundled with libgomp_<commit_hash>.so.1, and conda builds are dynamic linked with libgomp.so.1 on system path.
> 2. all macos builds refers to libiomp5.dylib, again wheel has it packaged together and conda refers to system path.
> 
> judging by the fact that this also happends on 1.7.1 I guess this was always how we release binaries.

Thanks for the update! I have tried that whether using wheels or conda builds don't affect this behavior. I suspect it could be a limitation of psutils library.

**Comment by xuzhao9** [comment]
Using taskset gets the same result. For example, first start a python3 REPL, import torch, then find its PID; then run "taskset -p PID", it returns the incorrect result.

**Comment by xuzhao9** [comment]
Believe this behavior is by design: https://github.com/gcc-mirror/gcc/blob/master/libgomp/config/linux/affinity.c#L58. At initialization, libgomp will set the affinity of current pthread to be the first CPU available in the list. Therefore, the result get from "sched_getaffinity()" will be inaccurate. Issue closed.
