### ISSUE TITLE
[bug] torch.flip: IndexError for dims=() on CUDA but works on CPU

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#49982]
```python
>>> a = torch.randn(3,2,0,2)
>>> torch.flip(a, dims=())
tensor([], size=(3, 2, 0, 2))
>>> b = a.cuda()
>>> torch.flip(b, dims=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: flip dims size out of range, got flip dims size=0
```

cc @ngimel @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
Thanks for filing this issue, @kshitij12345. We would accept a PR fixing this. 

However, I think this is a good first issue. So we should leave it for a newer member of the community to fix.

**Comment by singhularAdi** [comment]
I'd like to give this a shot.

**Comment by mruberry** [comment]
@singhularAdi, great. Check out our contribution guide: https://pytorch.org/docs/stable/community/contribution_guide.html.

**Comment by PandaBoi** [comment]
I would also like to work on this issue as my first step towards contributing! Could you please help me understand where I can look for the issue to arise from? my guess after looking through the error, is somewhere in ATen. Do let me know?

**Comment by dheerajgattupalli** [comment]
Hi @mruberry, 
 I was actually looking into this also and narrowed down the error to this line 
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorTransformations.h#L14

the error check seems appropriate ... the difference between TensorTransformations.cu and TensorTransformations.cpp was that the method flip_check_errors was being called in Cuda version and not called in the CPU version... so what is the solution expected here 
i. to get the error printed for the CPU version also or 
ii. is it to suppress the error from the CUDA version...

Thanks

**Comment by kshitij12345** [comment]
Expectation would be 
ii. To suppress the error from the CUDA version.

NumPy's flip returns unchanged array when `()` is passed similar to CPU version.

**Sample**
```python
>>> a = np.arange(1,13)
>>> a = a.reshape((3,2,2))
>>> a
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])
>>> np.flip(a, ())
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])
```

**Comment by dheerajgattupalli** [comment]
Hi, 
just pushed the fixed commit to my fork... https://github.com/dheerajgattupalli/pytorch/commit/c976993c8494d6ab0d7969b6a850ca90a2f0512c

Changes: 
1. I am returning from the method when the length of dims is zero because further steps in the method seem to assume that the size is greater than zero and hence cannot run... 
2. modified the test case which had a reference to this issue when the device is cuda...

Let me know if any changes are needed or if I can create the pull request... 

Thanks

**Comment by kshitij12345** [comment]
I think the change looks good. Were you able to successfully test the change?

Also feel free to open the PR (that would also run the CI test suite). Changes, if required, can be discussed there.

**Comment by dheerajgattupalli** [comment]
yes, I ran the test_tensorexpr.py which had the test case pointing to this issue removed that and the test was successful...

**Comment by kshitij12345** [comment]
The updated test is in `test_shape_ops.py` 
https://github.com/dheerajgattupalli/pytorch/commit/c976993c8494d6ab0d7969b6a850ca90a2f0512c#diff-9da3e8a2e39aa9125b6fa09ecd774c8260333e5a84287ea054bbc5afca39bdecR397

So be sure to test that.
