### ISSUE TITLE
Question about TORCH_LIBRARY Macro

### ISSUE THREAD

**Issue by zwang92** [pytorch/pytorch#49989]
1. The TORCH_LIBRARY Macro is defined as following:
`#define TORCH_LIBRARY(ns, m) \
  static void TORCH_LIBRARY_init_ ## ns (torch::Library&); \
  static torch::detail::TorchLibraryInit TORCH_LIBRARY_static_init_ ## ns ( \
    torch::Library::DEF, \
    &TORCH_LIBRARY_init_ ## ns, \
    #ns, c10::nullopt, __FILE__, __LINE__ \
  ); \
  void TORCH_LIBRARY_init_ ## ns (torch::Library& m)`

2. The questions are as following, could anyone give some answer ?
Q1: Where is the implementation of TORCH_LIBRARY_static_init_xxx static function ?
Q2: Where is the code that will call TORCH_LIBRARY_static_init_xxx to resister customized operator after python program call "torch.ops.load_library" ?

**Comment by skyline75489** [comment]
I don't know if Github is the right place for this kind of question. As far as I can see, `TORCH_LIBRARY_static_init_xxx` is not a function. Look again, it's a *variable*. By defining it you are effectively load your ops in the `Library`, if I'm not mistaken.

**Comment by zwang92** [comment]
> I don't know if Github is the right place for this kind of question. As far as I can see, `TORCH_LIBRARY_static_init_xxx` is not a function. Look again, it's a _variable_. By defining it you are effectively load your ops in the `Library`, if I'm not mistaken.

You are absolutely correct ！ It confuses me for a long time as I mistake TORCH_LIBRARY_static_init_xxx as static function declaration . Thank you so much :) @skyline75489
