### ISSUE TITLE
Linking Pytorch C++FrontEnd with Qt GCC 

### ISSUE THREAD

**Issue by naserpiltan** [pytorch/pytorch#49999]
System information :
OS : ubuntu 18.04
CUDA version : 10.2
CUDNN  : 7.6.5
LibTorch : 1.7.1
CMake  : 3.19.2
Qt  : 5.15.2

I wrote a simple program in C++ to use my PyTorch model in libtorch 1.7.1. I have CUDA 10.2 on my OS, thus I downloaded CUDA 10.2 prebuilt version of libtorch from this [link.](https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.7.1.zip) The program works fine with CMake and CUDA. CMake can load my model on GPU and returns "Yes" when I run this simple program:

![image](https://user-images.githubusercontent.com/33447001/103453866-46bfe880-4cac-11eb-8663-bfce65e1da0a.png)

Now, I would like to use the model in my Qt Application. It gives this result when I try it :

![image](https://user-images.githubusercontent.com/33447001/103453882-65be7a80-4cac-11eb-879a-144849aeda71.png)

This is my project QMake file :

> QT -= gui
CONFIG +=  c++14 console
CONFIG -= app_bundle
DEFINES += QT_DEPRECATED_WARNINGS
SOURCES += \
    main.cpp
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
QMAKE_CXXFLAGS += -DGLIBCXX_USE_CXX11_ABI=0
CONFIG += no_keywords
QMAKE_CXXFLAGS += -Wno-unused-parameter
QMAKE_LFLAGS += -INCLUDE:?warp_size@cuda@at@@YAHXZ
INCLUDEPATH += /home/eaglesoft/libtorch/include/torch/csrc/api/include
INCLUDEPATH += /home/eaglesoft/libtorch/include
DEPENDPATH +=  /home/eaglesoft/libtorch/include/torch/csrc/api/include
DEPENDPATH +=  /home/eaglesoft/libtorch/include
LIBS += -L/home/eaglesoft/libtorch/lib -lc10 \
        -lc10_cuda \
        -lcaffe2_module_test_dynamic \
        -lcaffe2_observers \
        -ltorch_cpu \
        -ltorch \
        -lc10d_cuda_test \
        -lcaffe2_detectron_ops_gpu \
        -lcaffe2_nvrtc \
        -lfmt \
        -lnvrtc-builtins \
        -lshm \
        -ltensorpipe \
        -ltorch_cuda

**Comment by skyline75489** [comment]
This isn't really a PyTorch issue, as far as I can see.  QMake is not officially supported by PyTorch itself. Please only files issues about PyTorch itself.

**Comment by ezyang** [comment]
try --no-as-needed when linking. But yeah, this isn't a PyTorch issue, maybe the forums can help you debug this.

**Comment by naserpiltan** [comment]
@ezyang Thank you sir , yes this the true answer :  --no-as-needed when linking.
