### ISSUE TITLE
pytorch vs LuaJIT torch

### ISSUE THREAD

**Issue by jojo05** [pytorch/pytorch#500]
It's unsettling that there is no explanation in the blog post, documentation or here of the real relationship between both projects.

I think it would be very useful to explain that relationship and maybe foster other projects. I'd love to see a gotorch equivalent, if that made sense!

**Comment by apaszke** [comment]
There's some discussion on this topic [on our forums](https://discuss.pytorch.org/t/roadmap-for-torch-and-pytorch/38). If you have any questions, I encourage you to ask them there. We'd like to keep issues limited to features requests and bugs. Thanks!
