### ISSUE TITLE
[ONNX] Enforce or advise to use with torch.no_grad() and model.eval() when exporting

### ISSUE THREAD

**Issue by sayakpaul** [pytorch/pytorch#50009]
## 🐛 Bug

Hello.

I am trying to convert the Glow TTS model (from https://github.com/mozilla/TTS/) from PyTorch to ONNX. I am running in to the following issue during the export step -

```/content/TTS_repo/TTS/tts/layers/glow_tts/glow.py in forward(self, x, x_mask, reverse, **kwargs)
    261                     self.weight) * (c / self.num_splits) * x_len  # [b]
    262 
--> 263         weight = weight.view(self.num_splits, self.num_splits, 1, 1)
    264         z = F.conv2d(x, weight)
    265 

RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
Tensor:
-0.4500 -0.2462 -0.0506 -0.4333
-0.3748 -0.0181  0.0442  0.3575
-0.2864  0.7973 -0.0522 -0.1719
 0.1037  0.2156 -0.9611  0.2521
[ torch.FloatTensor{4,4} ]
```

## To Reproduce

Colab Notebook - https://colab.research.google.com/gist/sayakpaul/96f00d33385cbb2c97e1befedcf2e3cd/copy-of-glow_tts.ipynb.

## Expected behavior

The conversion should execute. 

## Environment

Colab

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by tulasiram58827** [comment]
CC: @houseroad @spandantiwari @lara-hdr @ezyang @mruberry

**Comment by spandantiwari** [comment]
@sayakpaul  - can you try setting the model to eval mode (`model.eval()`)before export?

**Comment by sayakpaul** [comment]
@spandantiwari that is already being done - 

![Screenshot 2021-01-05 at 7 18 28 AM](https://user-images.githubusercontent.com/22957388/103597473-2a42cc80-4eb5-11eb-9e80-f834a7290d66.png)

**Comment by tulasiram58827** [comment]
@spandantiwari Gentle reminder.

**Comment by ErenBalatkan** [comment]
Up, facing the same issue on same repo.

**Comment by synesthesiam** [comment]
This helped me:

```python
model.eval()

with torch.no_grad():
    model.decoder.store_inverse()
```

`store_inverse()` creates new tensors, you need to turn off grad before they're created.

**Comment by sayakpaul** [comment]
Could you share your fixed version as a Colab Notebook? I tried your suggestion and the issue still seems to be persisting. Here's [my Colab Notebook](https://colab.research.google.com/gist/sayakpaul/2f24a330f532cdf89ac9903f45c79ad7/copy-of-glow_tts.ipynb).

**Comment by synesthesiam** [comment]
Not a notebook, but here's my repo with this implemented: https://github.com/rhasspy/glow-tts-train

Pre-trained models are available here: https://github.com/rhasspy/larynx

**Comment by ihshareef** [comment]
> Could you share your fixed version as a Colab Notebook? I tried your suggestion and the issue still seems to be persisting. Here's [my Colab Notebook](https://colab.research.google.com/gist/sayakpaul/2f24a330f532cdf89ac9903f45c79ad7/copy-of-glow_tts.ipynb).

As an alternative, I've been trying to convert your GlowTTS to TorchScript for some time without success. I'm trying

```
traced = torch.jit.script(model, [inputs, inputs_lengths])
# Print the Torch Script code     
print(traced.code)      
# We can also store the model like usual:    
traced.save('traced.ptc')
```

Yet, (after converting the types of some indexes) I am stuck at:
```
RuntimeError: Can't redefine method: forward on class: __torch__.TTS.tts.layers.glow_tts.gated_conv.GatedConvBlock (of Python compilation unit at: 0x560c5f1e46d0)
```

Any thoughts on how to overcome this?

**Comment by neso613** [comment]
> [synesthesiam](/synesthesiam)

Hi @synesthesiam 
I am following your repo for glowTTS onnx conversion and am getting same error
![image](https://user-images.githubusercontent.com/31642462/155113624-eecc070a-4777-4ab9-bb2a-cda60c9f27d0.png)
you inputs can help a lot.

**Comment by neso613** [comment]
> > [synesthesiam](/synesthesiam)
> 
> Hi @synesthesiam I am following your repo for glowTTS onnx conversion and am getting same error ![image](https://user-images.githubusercontent.com/31642462/155113624-eecc070a-4777-4ab9-bb2a-cda60c9f27d0.png) you inputs can help a lot.

@synesthesiam looking forward from hearing from you

**Comment by justinchuby** [comment]
Thanks for creating the issue. I ran the notebook but couldn't get past the import step. Please consider reproducing with the latest pytorch version and reopen the issue if it persists.


---------
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
