### ISSUE TITLE
Add support for fusing ConvBnReLU3d 

### ISSUE THREAD

**Issue by hyperfraise** [pytorch/pytorch#50002]
## 🚀 Feature

Add support for fusion of quantized 3d layers.

## Motivation

I wanna be able to do quantization for 3d models such as 3d resnets but the support is lacking for fusing 3d layers in pytorch quantization modules.

## Pitch

I believe what is missing is the definition of the ConvBnReLU3d class.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by hyperfraise** [comment]
I took the liberty of opening a PR, I'm not entirely sure I did the relevant things.

**Comment by hyperfraise** [comment]
The PR has been merged. I'll see if something is missing and close if not.

**Comment by duduheihei** [comment]
> The PR has been merged. I'll see if something is missing and close if not.

Hi , I want to train 3D convolution quantized model, so when does this new ops  ConvBnReLU3d will be updated to stable version of pytorch  ?

**Comment by hyperfraise** [comment]
> > The PR has been merged. I'll see if something is missing and close if not.
> 
> Hi , I want to train 3D convolution quantized model, so when does this new ops ConvBnReLU3d will be updated to stable version of pytorch ?

Basically as soon as the nightly release of today is available. Idk exactly when they're out but I'm guessing not before tomorrow. As far as stable release is concerned, I have no idea. Months ?
