### ISSUE TITLE
Build error with system-wide protobuf 3.12

### ISSUE THREAD

**Issue by nquest** [pytorch/pytorch#50001]
## 🐛 Bug
There is an linking error with current arch linux protobuf version  3.12.4
## To Reproduce

1. set BUILD_CUSTOM_PROTOBUF=OFF
2. build with arch's PKGBUILD from rocm-arch repo

`
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build    /lib/libtorch_hip.so: undefined reference to caffe2::DeviceOption::DeviceOption(google::protobuf::Arena*) /usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::OperatorDef::OperatorDef(google::protobuf::Arena*)`
`
/usr/bin/ld: /home/nquest    /src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::NetDef::NetDef(google::protobuf::Arena*)' /usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::TensorShape::TensorShape(google::protobuf::Arena*) `

## Expected behavior

successfull build with system-wide protobuf

## Environment
PyTorch version: 1.7.0a0+57bffc3
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.0.20513-4a3c144

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.21.2
MIOpen runtime version: 2.9.0

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0a0
[conda] Could not collect

## Additional context

cc @malfet @seemethere @walterddr @jeffdaily @sunway513

**Comment by malfet** [comment]
Thank you for reporting the issue! Is the problem reproducible with CPU only or with CUDA builds?
Also, if you have a patch in mind, please do not hesitate to post it here and I will gladly review it.

**Comment by nquest** [comment]
CPU and CUDA versions are built automatically in Arch's community repo and builds are stable. We use same PKGBUILDs with small modifications for rocm-specific builds, but trying to be as close as possible to Arch's community version.

**Comment by acxz** [comment]
@malfet this issue can be closed as the Arch package does not encounter this linking issue anymore.
