### ISSUE TITLE
torch.utils.mobile_optimizer.optimize_for_mobile doesn't have parameter perserved_methods

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#50017]
## Link
https://pytorch.org/docs/1.7.0/mobile_optimizer.html#torch.utils.mobile_optimizer.optimize_for_mobile

## API 
`torch.utils.mobile_optimizer.optimize_for_mobile`

## Issue
Inconsistency between signature and Parameter section
In the Parameter section, the `perserved_methods` should be `preserved_methods`

![image](https://user-images.githubusercontent.com/24580222/103483886-562c5800-4db8-11eb-9410-0b1046b2ed33.png)

## System information
- OS: MacOS Mojave 10.14
- PyTorch version: 1.5.0
- Python version: 3.8.2

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
Thank you for pointing this out, @DNXie. @dreiss, maybe this typo fix can be rolled into another PR?
