### ISSUE TITLE
torch.onnx.export doesn't have parameter external_data_format

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#50018]
## Link 
https://pytorch.org/docs/1.7.0/onnx.html#torch.onnx.export

## API 
torch.onnx.export

## Issue

In the parameter section, there is a parameter `external_data_format`, it should be `use_external_data_format`

![image](https://user-images.githubusercontent.com/24580222/103484017-7a3c6900-4db9-11eb-99f7-b17080216dad.png)

## System information
- OS: MacOS Mojave 10.14
- PyTorch version: 1.5.0
- Python version: 3.8.2

cc @jlin27 @mruberry

**Comment by ezyang** [comment]
OOC, is there some tool you're using to detect these?

**Comment by DNXie** [comment]
@ezyang  Yes, this bug is detected when we are collecting the document using script for research purpose. :)

**Comment by DNXie** [comment]
> OOC, is there some tool you're using to detect these?
