### ISSUE TITLE
Test half-precision operations in test_cuda.py

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#5001]
We're not testing most half operations in test_cuda.py We should do that.

Also see #5000

**Comment by csarofeen** [comment]
Also see https://github.com/pytorch/pytorch/issues/4940

**Comment by ailzhang** [comment]
This is implemented in #5122 . Please help review it when you have time. :)

**Comment by ailzhang** [comment]
#5122 is merged. Good to close this issue? @colesbury  @soumith

**Comment by soumith** [comment]
thanks Ailing! :)
