### ISSUE TITLE
torch.nn.functional.hardsigmoid signature missing parameter `inplace`

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#50016]
## Link
https://pytorch.org/docs/1.7.0/nn.functional.html#torch.nn.functional.hardsigmoid

## API
`torch.nn.functional.hardsigmoid`

## Issue

Inconsistency between signature and Parameter section.

There is no `inplace` parameter in the signature
![image](https://user-images.githubusercontent.com/24580222/103483817-d56d5c00-4db7-11eb-8c6f-edcba3188cbc.png)

## System information
- OS: MacOS Mojave 10.14
- PyTorch version: 1.5.0
- Python version: 3.8.2

cc @jlin27 @mruberry @albanD @jbschlosser

**Comment by mruberry** [comment]
Thank you for reporting this issue, @DNXie. We would accept a PR fixing this.
