### ISSUE TITLE
How to realize Cross Validation using torchtext?

### ISSUE THREAD

**Issue by yipliu** [pytorch/pytorch#50030]
I want to realize cross validation using torchtext. Here is what I have done:
1. First, I use TabularDataset to define a dataset from the JSON file
2. Then, I use train_exs_arr = np.array(train_data.examples), d_train = train_exs_arr[train_idx].tolist() 
3. Then, I use Dataset to define a sub-dataset from Examples d_train
4. Finally, I use BucketIterator. However, I can not access the data from BucketIterator

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org.
