### ISSUE TITLE
When pytorch for cuda 11.2 will be available?

### ISSUE THREAD

**Issue by SithLord24** [pytorch/pytorch#50032]
## ❓ Questions and Help
Recently I downloaded cuda11.2 to learn and run various deep learning projects. Then, searched internet for various packages and binaries needed to installed, since I am new to these I am using pip for installing all the required things. Every time I try to run pip install pytorch, it gives me following error in install log-
Building wheels for collected packages: torch
  Building wheel for torch (setup.py) ... error
  Also shows - ModuleNotFoundError: No module named 'tools.nnwrap'
Went to official website and saw that pytorch was only available for cuda version till 11.0. My question is should I wait for it to be developed as I would not be starting to learn the topic until 3-4 weeks from now (as I think 11.0 was pretty recent too) or is there any workaround for this issue. I am also willing to download cuda 11.0 and remove 11.2 if there are no issues in doing so.
Any help will be appreciated.
Thanks.

**Comment by ed-muthiah** [comment]
@SithLord24 I use this website to figure out what version of CUDA I should get: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-12.html#rel_20-12

[As you probably saw ](https://pytorch.org/blog/pytorch-1.7-released/) PyTorch 1.7 is stable for CUDA 11.0. So I would just get install [CUDA 11.0.3](https://developer.nvidia.com/cuda-11.0-update1-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal), you don't need to remove 11.2 the 11.0.3 installer will take care of that. After that you can run ```pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html```

People seem to be having issues with 11.1 and I haven't seen too much on 11.2. If you are learning just stick with 10.2 or 11.0.

**Comment by SithLord24** [comment]
> @SithLord24 I use this website to figure out what version of CUDA I should get: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-12.html#rel_20-12
> 
> [As you probably saw ](https://pytorch.org/blog/pytorch-1.7-released/) PyTorch 1.7 is stable for CUDA 11.0. So I would just get [remove 11.2](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#uninstall-cuda-software) and install [CUDA 11.0.3](https://developer.nvidia.com/cuda-11.0-update1-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal). After that you can run `pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> People seem to be having issues with 11.1 and I haven't seen too much on 11.2. If you are learning just stick with 10.2 or 11.0.

Thanks for the help, I was thinking the same way, as you know I am a beginner and just started to learn so I downloaded the latest version, now I am downloading 11.0 version. Similar happened to me when I first installed latest python and tensorflow libraries and binaries weren't available. Gotta watch out for such issues from now on. : )

**Comment by mrgransky** [comment]
Installing with this command:
`$ pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`
returns this error:
```
Traceback (most recent call last):
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alijani/WS_Farid/OxfordRobotCar/VPR_IR/cirtorch/examples/train_COLD.py", line 4, in <module>
    from sklearn.metrics import pairwise_distances
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 228, in <module>
    from .csr import *
  File "/home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/scipy/sparse/csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/alijani/.conda/envs/py37_gpu/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by gaurav-oviva** [comment]
Not sure when it'll come. I have worked with MMdetection, Detectron2 and general PyTroch projects on Google Colab and V100, Tesla GPUs with CUDA=11.2
It seems you can install it in this way
`pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
This version works well with CUDA>10.1
I hope this helps

**Comment by sonsus** [comment]
FYI: Mine is working well with <code>1.8.1+cu111</code>.
install cmd: <code>pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html </code>
Specifications:
nvidia-driver: 460.80 
CUDA: 11.2
GPU model: RTX 3060Ti

**Comment by ashok-arjun** [comment]
> FYI: Mine is working well with `1.8.1+cu111`.
> install cmd: `pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html `
> Specifications:
> nvidia-driver: 460.80
> CUDA: 11.2
> GPU model: RTX 3060Ti

This did not work for me.

**Comment by erolrecep** [comment]
I had the same issue. 

CUDA: 11.2
Nvidia-driver: 460.91.03
GPU model: RTX 2080 Ti
Ubuntu 20.04
Python 3.8 with virtualenv

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html 

This command is taken from PyTorch's web site (https://pytorch.org/get-started/locally/) worked for me.

**Comment by jhh0923** [comment]
> FYI: Mine is working well with `1.8.1+cu111`. install cmd: `pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html ` Specifications: nvidia-driver: 460.80 CUDA: 11.2 GPU model: RTX 3060Ti

works for me, thanks!

**Comment by kalelpark** [comment]
> > FYI: Mine is working well with `1.8.1+cu111`. install cmd: `pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html ` Specifications: nvidia-driver: 460.80 CUDA: 11.2 GPU model: RTX 3060Ti
> 
> works for me, thanks!

Very Useful Thanks

**Comment by p96114175** [comment]
> I had the same issue.
> 
> CUDA: 11.2 Nvidia-driver: 460.91.03 GPU model: RTX 2080 Ti Ubuntu 20.04 Python 3.8 with virtualenv
> 
> pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
> 
> This command is taken from PyTorch's web site (https://pytorch.org/get-started/locally/) worked for me.
works for me, thanks!

**Comment by BADAL244** [comment]
> pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by BADAL244** [comment]
> FYI: Mine is working well with `1.8.1+cu111`. install cmd: `pip3 install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html ` Specifications: nvidia-driver: 460.80 CUDA: 11.2 GPU model: RTX 3060Ti

Thanks this works for me as well .
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
>>>

**Comment by abrahamdmt** [comment]
In case it helps anyone: 
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

works for my case for my cuda 11.2.2 and cudnn8.1.1

**Comment by Alimzade** [comment]
`pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0
`

worked for: _GeForce RTX 3090  |  CUDA 11.2_

**Comment by YukiYotsu** [comment]
> `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
> `pip install torch==1.12.1+cu112 torchvision==0.13.1+cu112 torchaudio==0.12.1 torchtext==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu112`

Both above didn't work for mine.  
Instead, below worked perfectly for:  _GeForce RTX A6000 (48GB)_ | _CUDA Version: 11.2_  
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
...
pip install torchtext==0.13.1
```
