### ISSUE TITLE
loss.backward() --> expected FloatTensor but found DoubleTensor

### ISSUE THREAD

**Issue by Rhuax** [pytorch/pytorch#5004]
- OS: Ubuntu 17
- PyTorch version:0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.3
- CUDA/cuDNN version: CUDA 9.0 CUDNN 7.0
- GPU models and configuration: GTX950M

```
Traceback (most recent call last):
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 206, in <module>
    trainIters(encoder1, attn_decoder1, 7, print_every=100)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 175, in trainIters
    loss = train(input_variable, target_variable, encoder,decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 98, in train
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.DoubleTensor for argument #3 'other'
```

When I call loss.backward() it gives me this error. The network can predict and I can also calculate the loss.

**Comment by soumith** [comment]
The error message is clear enough, why do you think this is a bug?

**Comment by soumith** [comment]
also, do you by any chance have a script that can reproduce this error?

**Comment by Rhuax** [comment]
It is saying that somewhere it expects float but it got a double. I cannot understand where, since the error comes from internal functions of pytorch. I'll attach the full script asap

**Comment by bheinzerling** [comment]
This looks like you're passing a DoubleTensor and FloatTensor to your criterion. To debug, I'd try

```Python
loss = criterion(model_prediction.float(), target_variable.float())
```
If this works you know that either your model forward() produces a DoubleTensor and the target is Float, or the other way around.

**Comment by Rhuax** [comment]
If I follow the suggestion of @bheinzerling I get:
`RuntimeError: Expected object of type Variable[torch.cuda.LongTensor] but found type Variable[torch.cuda.FloatTensor] for argument #1 'target'`

I'm attaching my source file. 
[train.py.txt](https://github.com/pytorch/pytorch/files/1689223/train.py.txt)

**Comment by bheinzerling** [comment]
ok, then your targets are Long and you shouldn't do target_variable.float().

Try

```
loss = criterion(model_prediction.float(), target_variable)
```

There is a DoubleTensor produced somewhere in your code where a FloatTensor is expected. Maybe in EncoderRNN, maybe some numpy -> pytorch conversion done with a numpy.float64 array

**Comment by Rhuax** [comment]
I tried your suggestion already and it outputs the same error. My target is an integer representing an index class. The output of the network is a vector as large as my vocabulary and it is the output from log_softmax. I'll attach my encoder and decoderrnn, but they are very similar to those from the seq2seq example from pytorch tutorials

**Comment by Rhuax** [comment]
I managed to understand where the DoubleTensor was produced (instead of the FloatTensor). This was really hard to debug since I had practically no information ... By the way, now I have this error:

```
Traceback (most recent call last):
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 201, in <module>
    trainIters(encoder1, attn_decoder1, 7, print_every=100)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 170, in trainIters
    loss = train(input_variable, target_variable, encoder, decoder, encoder_optimizer, decoder_optimizer, criterion)
  File "/home/crow/PycharmProjects/text-summarization/train.py", line 94, in train
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 335, in _do_backward
    result = super(NestedIOFunction, self)._do_backward(gradients, retain_variables)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/function.py", line 343, in backward
    result = self.backward_extended(*nested_gradients)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/_functions/rnn.py", line 335, in backward_extended
    grad_weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/rnn.py", line 468, in backward_weight
    grad_params = get_parameters(fn, handle, dw)
  File "/usr/local/lib/python3.6/dist-packages/torch/backends/cudnn/rnn.py", line 171, in get_parameters
    assert cur_offset == offset
AssertionError
```

The error message is not again not very useful

**Comment by soumith** [comment]
@Rhuax sorry for your experience so far. Is there any way we can have a look at your code or reproduce your issues?

**Comment by Rhuax** [comment]
I uploaded my project here: https://github.com/Rhuax/text-summarization
It is missing the "glove.6B.100d.txt" file, since it was too big to upload. But it is simply the glove vector file.

I simply run the file `train.py`

**Comment by elanmart** [comment]
@Rhuax you seem to be playing with types a little bit too much. 

Change https://github.com/Rhuax/text-summarization/blob/6c7ad229dc0cfdf27bfc192ef5434f4935ec28bf/util.py#L135
to `return torch.from_numpy(embeddings).float()` and remove all other `.float()` and `.double()` calls.

**Comment by Rhuax** [comment]
Thanks for your reply. I added `.float()` and removed the other useless `.double()` and `.float()` . Now it works. By the way all those calls where added following errors which were complaining about specific data types.

**Comment by Aurora11111** [comment]
@Rhuax your profile photo shocked  me!
