### ISSUE TITLE
data_ptr memory alignment 

### ISSUE THREAD

**Issue by francisco-munoz** [pytorch/pytorch#50043]
I am using the pytorch C++ API to compute my tensors using my own code. Specifically I want to do some computation by using the AVX intrinsics. To do so, I just get the CPU memory pointer with tensor.data_ptr() and then I start computing with that pointer.  My question is quite simple: May I assume the tensors are alligned to the data type? For example, if I am using a tensor of float which usually occupies 4 bytes, my I assume the elements in the array are storaged in 4-byte-alligned memory addresses?

Thank you very much.

**Comment by ezyang** [comment]
Yes.

```
void* alloc_cpu(size_t nbytes) {
  if (nbytes == 0) {
    return nullptr;
  }
  // We might have clowny upstream code that tries to alloc a negative number
  // of bytes. Let's catch it early.
  CAFFE_ENFORCE(
      ((ptrdiff_t)nbytes) >= 0,
      "alloc_cpu() seems to have been called with negative number: ",
      nbytes);

  void* data;
#ifdef __ANDROID__
  data = memalign(gAlignment, nbytes);
#elif defined(_MSC_VER)
  data = _aligned_malloc(nbytes, gAlignment);
#else
  int err = posix_memalign(&data, gAlignment, nbytes);
  if (err != 0) {
    CAFFE_THROW(
        "DefaultCPUAllocator: can't allocate memory: you tried to allocate ",
        nbytes,
        " bytes. Error code ",
        err,
        " (",
        strerror(err),
        ")");
  }
#endif

```
