### ISSUE TITLE
Complex dispatch should be disabled on min/max functions

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#50064]
As of #36377, min/max functions were disabled for complex inputs (via dtype checks), however, min/max kernels are still compiled and dispatched for complex, see e.g.  
https://github.com/pytorch/pytorch/blob/e44b2b72bd4ccecf9c2f6c18d09c11eff446b5a3/aten/src/ATen/native/cpu/ReduceAllOpsKernel.cpp#L77
This dispatch should be disabled, and we should rely on errors produced by dispatch macro to not run those ops on complex, instead of doing redundant dtype checks. 

cc @ezyang @anjali411 @dylanbespalko @mruberry 
cc @t-vi, thanks for reporting!

**Comment by rishabhvarshney14** [comment]
Can I work on it @anjali411?

**Comment by anjali411** [comment]
@rishabhvarshney14 yes absolutely! please feel free to add me as a reviewer for your PR

**Comment by ngimel** [comment]
Reopening. The linked PR only disables dispatch on cpu reductions, it does not handle pointwise operations, and it does not handle cuda operations. 
I also asked for redundant type checks to be removed (because dispatch would produce necessary error messages), and they are still in place.

**Comment by imaginary-person** [comment]
> Reopening. The linked PR only disables dispatch on cpu reductions, it does not handle pointwise operations, and it does not handle cuda operations.
> I also asked for redundant type checks to be removed (because dispatch would produce necessary error messages), and they are still in place.

Hi, I l had realized that I hadn't disabled the type-checks introduced in #36377, after Richard suggested writing a test, so I recently submitted another PR (#50465).


As for the pointwise operations & CUDA operations, their kernels do not seem to be compiled & dispatched for complex types anyway, so I think that no further changes are required. Please confirm if my rationale is correct. Thanks!

Basically, the dispatch macros currently being used don't have cases (of switch statements) for complex types.
For example, 

1. the reduce CUDA ops use [AT_DISPATCH_ALL_TYPES_AND2](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Dispatch.h#L548-L575) in [ReduceMinMaxKernel.cu](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/ReduceMinMaxKernel.cu), and that macro doesn't allow complex types.

2. In [MinMaxElementwiseKernel.cu](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/MaxMinElementwiseKernel.cu), the CUDA pointwise ops use [AT_DISPATCH_FLOATING_TYPES_AND2](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Dispatch.h#L240-L263) for non-integral & non-boolean types, and this marco doesn't have a case for complex types either.
 
3. The min/max ops in[ BinaryOpsKernel.cpp](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L454-L506) also use dispatch macros that don't have a case for complex types.

**Comment by imaginary-person** [comment]
**Duplicate comment from #50465 for the convenience of any potential readers in the future. Please skip if you read the PR #50465.**

There are a few cases in which the methods corresponding to `min_stub()` or `max_stub()` are not called, so dispatch macros don't get invoked, resulting in no exceptions being raised. Hence, `dtype` checks are necessary at 3 places:

1. https://github.com/pytorch/pytorch/blob/52dcc7299925de055d330781d2fe0dad71182829/aten/src/ATen/native/TensorCompare.cpp#L342
2. https://github.com/pytorch/pytorch/blob/52dcc7299925de055d330781d2fe0dad71182829/aten/src/ATen/native/TensorCompare.cpp#L422
3. https://github.com/pytorch/pytorch/blob/52dcc7299925de055d330781d2fe0dad71182829/aten/src/ATen/native/TensorCompare.cpp#L389

The first dtype check requirement can be verified from the following example Python code:
```
import unittest 
import torch

class MyTestCase(unittest.TestCase): 
  
   def test_1(self):
      t = torch.tensor((1 + 1j), device='cpu', dtype=torch.complex128) 
      with self.assertRaises(RuntimeError): 
         torch.max(t, dim=0)
  
if __name__ == '__main__':  
    unittest.main()
```
