### ISSUE TITLE
Need help for ValueError: bad value(s) in fds_to_keep

### ISSUE THREAD

**Issue by getalloseal** [pytorch/pytorch#50089]
To train neural network on  different hyperparameters, I spawned many processes using torch.multiprocessing. The processes share a same data resource and each of them will call dataloader independently. There is no problem when I use num_worker=0 in dataloader. The issue comes up only when num_worker > 0. I checked the dataloader also spawn processes for multiple workers. I suspect the error is cause by spawning process from spawned process. How can I solve the problem? I appreciate your help!

pytorch 1.7.0
python 3.7.0

===========================
Traceback (most recent call last):
  File "/home/tyu/nn/nn_dev8/utils.py", line 162, in wrapper
    return process_task(*args, **kwargs)
  File "/home/tyu/nn/nn_dev8/train.py", line 140, in process_task
    train_loop(hparam, model, opt, train_dataloader, device, start_initpoint, max_epochs=settings['max_epochs'], callbacks=callbacks)
  File "/home/tyu/nn/nn_dev8/train.py", line 175, in train_loop
    for *inputs, y, wght in dataloader:
  File "/home/tyu/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/tyu/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/tyu/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/tyu/miniconda3/lib/python3.7/multiprocessing/util.py", line 432, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Can you please share a minimum script to reproduce this Error? 
I can only suggest to try to force spawn as the start method in your main function.

**Comment by getalloseal** [comment]
When I wrote the minimal example, I have figured out what causes the error. I still do not know why. Anyone can help to explain will be appreciated. I have a customized dataset, which will filter out some indices. There is one line using set of integer tensor, which cause the error. The error only happens when you use multiprocessing (only spawn I have tested) both in main function and inside dataloader. Disable either multiprocessing will make the error disappear. 

Here is the minimal example you can try:

import torch
import time
import multiprocessing as mp
from torch.nn.functional import mse_loss
from torch.utils.data import TensorDataset, DataLoader, Dataset
import torch.nn as nn

class DatasetFilter(Dataset):

    def __init__(self, data):
        self.X = data[0]
        self.y = data[1]
        self.goodloc = torch.arange(start=0, end=1000, step=5)
        self.len = len(self.goodloc)
        #self.ddd = set([1,2,3]) #remove the error; this line is inserted just for showing error
        self.ddd = set(torch.tensor([1,2,3])) #cause the error; this line is inserted just for showing error

    def __getitem__(self, item):
        return (
            self.X[self.goodloc[item]],
            self.y[self.goodloc[item]])

    def __len__(self):
        return self.len

def worker(data_share):
    ds = DatasetFilter(data_share)
    train_dataloader = DataLoader(
            ds,
            batch_size=100,
            shuffle=True,
            drop_last=True,
            num_workers=4,
            pin_memory=True)

    model = nn.Linear(in_features=data_share[0].shape[1], out_features=1)
    optimizer = torch.optim.SGD(model.parameters(), lr=1e-3, momentum=0.9)

    for epoch in range(10):
        for x, y in train_dataloader:
            model.train()
            optimizer.zero_grad()
            output = model(x)
            loss = mse_loss(output.squeeze(), y)
            loss.backward()
            optimizer.step()

if __name__ == '__main__':
    share_resource = (torch.rand(1000, 3), torch.rand(1000))

    mp.set_start_method('spawn')
    nprocs = 2
    processes = []
    for rank in range(nprocs):
        p = mp.Process(target=worker, args=(share_resource,))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()

**Comment by ejguan** [comment]
Can you try to use `torch. multiprocessing as mp` instead.

**Comment by getalloseal** [comment]
tried both, and same behavior.

**Comment by ejguan** [comment]
It should be working if you set mp.set_start_method('fork')

**Comment by getalloseal** [comment]
It is true! But still do not now know why.

**Comment by ejguan** [comment]
Not hundred percent sure.
When using `spawn`, `set` should be inherited by child processes, but somehow it's being copied when a tensor attached to it.

**Comment by getalloseal** [comment]
Anyway, set(tensor) is evil and should be avoided. The behavior is totally different from numpy array. See the following:

set(numpy.array([1,2,3])) -> {1,2,3}
vs.
set(torch.tensor([1,2,3])) -> {tensor(1), tensor(2), tensor(3)}

**Comment by ejguan** [comment]
Closing the issue as the suggestion is provided.

**Comment by SsnL** [comment]
@getalloseal In numpy you are not really getting a python int anyways
```py
In [1]: import numpy as np

In [3]: set(np.array([1,2,3]))
Out[3]: {1, 2, 3}

In [4]: set(np.array([1,2,3])).pop()
Out[4]: 1

In [5]: type(set(np.array([1,2,3])).pop())
Out[5]: numpy.int64

In [6]:
```

**Comment by getalloseal** [comment]
Good point! Another inconsistence is actually here

1 in set(np.array([1,2,3])) -> True
vs
1 in set(torch.tensor([1,2,3])) -> False

I would prefer
either
set(torch.tensor([1,2,3])) returns {1,2,3}
or 
reject as, set(np.matrix([1,2,3])), set([np.array(1), np.array(2)])

This behavior is consistent:
torch.tensor(1) == 1 -> tensor(True)
np.matrix(1) == 1 -> matrix([[True]])



> @getalloseal In numpy you are not really getting a python int anyways
> 
> ```python
> In [1]: import numpy as np
> 
> In [3]: set(np.array([1,2,3]))
> Out[3]: {1, 2, 3}
> 
> In [4]: set(np.array([1,2,3])).pop()
> Out[4]: 1
> 
> In [5]: type(set(np.array([1,2,3])).pop())
> Out[5]: numpy.int64
> 
> In [6]:
> ```

**Comment by axjing** [comment]
Encountered the same problem, please ask you to solve it

**Comment by Tikquuss** [comment]
> Encountered the same problem, please ask you to solve it

`strategy="ddp"`  (`Trainer` args) solves the problem for me.

**Comment by min-xu-ai** [comment]
> > Encountered the same problem, please ask you to solve it
> 
> `strategy="ddp"` (`Trainer` args) solves the problem for me.

If you use lightning and forgot to specify the "ddp" strategy, you can get this nonobvious error msg.
