### ISSUE TITLE
torch.jit.fork examples are empty

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#50082]
## 📚 Documentation

Image attached illustrating the problem on this doc page: https://pytorch.org/docs/stable/generated/torch.jit.fork.html

![Screen Shot 2021-01-04 at 5 58 50 PM](https://user-images.githubusercontent.com/9958665/103598042-82c69980-4eb6-11eb-8d1c-bd019b249c92.png)

cc @gmagogsfm

**Comment by eellison** [comment]
fixed with https://github.com/pytorch/pytorch/pull/49436
