### ISSUE TITLE
AssertionError: torch-cuda80==0.1.6.post17 .dist-info directory not found

### ISSUE THREAD

**Issue by KeithYin** [pytorch/pytorch#501]
An error occured when using 
`pip install https://s3.amazonaws.com/pytorch/whl/torch_cuda80-0.1.6.post17-cp35-cp35m-linux_x86_64.whl 
pip install https://s3.amazonaws.com/pytorch/whl/torchvision-0.1.6-py3-none-any.whl`
to install pytorch, what should i do to fix it?

**Comment by apaszke** [comment]
Can you try running `import torch` in an interpreter? We're aware that some of the wheels are broken now and we're working on fixing that. Sorry!

**Comment by KeithYin** [comment]
@apaszke It works fine, so can i just ignore this error?

**Comment by apaszke** [comment]
If you encounter any issues let us know, but it should be fine 😊

**Comment by KeithYin** [comment]
@apaszke thanks :blush:
