### ISSUE TITLE
Autograd keeps all input tensors live across function

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5011]
Today's API for calling an Autograd function is:

```
virtual variable_list apply(const variable_list& inputs) override {
  ...
}
```

This API is unfortunate, because it implies that the caller of `apply` is obligated to keep `inputs` (and thus, all of the Tensors it refers to) live for the ENTIRE duration of the `apply` call. However, particularly large functions (esp. the interpreter we are working on for the JIT) may be able to profitably deallocate inputs before the end of the function.

A very simple API amendment might be to change this to:

```
virtual variable_list apply(variable_list&&) override {
  ...
}
```

but we would need to see if we can actually efficiently implement this in the engine.

I'm posting this here because possible API changes will be of interest to other folks working on core.

CC @zdevito @apaszke @colesbury @gchanan

**Comment by apaszke** [comment]
It should be a trivial modification to the engine. Let's do it

**Comment by goldsborough** [comment]
I just took a look at this, and it seems like this would make it difficult to call post hooks with the inputs (from `torch/csrc/autograd/engine.cpp:230`:
```static variable_list call_function(FunctionTask& task) {
  auto& fn = *task.fn;
  auto inputs = call_pre_hooks(fn, InputBuffer::variables(std::move(task.inputs)));

  if(!task.base->keep_graph) {
    fn.will_release_variables();
  }
  auto outputs = fn(inputs); // move here?

  return call_post_hooks(fn, std::move(outputs), std::move(inputs));
}
```

**Comment by zdevito** [comment]
Can we check if there are any hooks? My guess is they are empty most of the time, and we should optimize for that case. It will become important with the JIT not to have the autograd hold input variables if they will be unused. If there are hooks, my guess that copying the input list to preserve them would not be that expensive since hooks are not universal.

**Comment by apaszke** [comment]
+1 for cloning in presence of hooks. They are rarely used

**Comment by goldsborough** [comment]
Ok. I will implement this.
