### ISSUE TITLE
Core Dump due to 'free(): double free detected in tcache 2'

### ISSUE THREAD

**Issue by Anaphory** [pytorch/pytorch#50137]
## 🐛 Bug

After several days of training on a not particularly capable GPU, one of my models suddenly died during testing with the message

    evaluating…
    92%|████████████████▌ | 1667/1811 [4:43:54<08:57,  3.73s/it]
    free(): double free detected in tcache 2
    Aborted (core dumped)

## To Reproduce

So far, this has only occurred once (a similar parallel run, and two more runs on CPU instead of GPU are still running), so I cannot yet say which bit reproduces it. However, the [code that led to the issue is attached](https://github.com/pytorch/pytorch/files/5775094/model.py.txt), in case it contains important information already. The dying model was run with `--n-mel=128` and was really slow during testing (10.2 seconds per batch, training usually ran at about 0.5s/batch). This means I may have done something dumb in this my first pytorch project that made this error show up.
 As evidenced by the last output before it, the double-free occurs somewhere inside `test()`. 

I have the core dump file, but it's 200MB, so it won't attach here. Ping me if you think it helps with a way to get it to you.

## Expected behavior

Don't die in training, you know?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX250
Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.2
[conda] nope

Manjaro CUDA packages outside the virtualenv:

    python-pytorch-cuda                                                   [Installed] 1.7.1-2    community 
    cuda                                                                  [Installed] 11.2.0-1   community

**Comment by H-Huang** [comment]
Thanks for the report @Anaphory, I tried to repro this locally using your code but was missing configurations. Based on your description, I suspect it could just be a bad GPU which caused some sort of memory corruption. Closing this issue for now unless we get additional reports or consistent reproduction.
