### ISSUE TITLE
[feature request] match numpy behavior on zero-length and zero-dimension tensors

### ISSUE THREAD

**Issue by davidbau** [pytorch/pytorch#5014]
Request for numpy-style support for zero-length tensor dimensions.

Zero-length tensor dimensions are useful and important when doing fancy indexing, because it allows you to write straight-line code without littering it with python "if"s and without moving data off the gpu.

Example:
```
>>> numpy.arange(12).reshape(3,4)[:,[0,2]]
array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])
>>> numpy.arange(12).reshape(3,4)[:,[]]
array([], shape=(3, 0), dtype=int64)
```
The shape (3,0) continues to fit wherever needed.  However, pytorch cannot maintain a tensor with any zero dimension:

```
>>> torch.arange(12).view(3,4)[:,[0,2]]
  0   2
  4   6
  8  10
[torch.FloatTensor of size 3x2]
>>> torch.arange(12).view(3,4)[:,[]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: The advanced indexing objects could not be broadcast
>>>
```

This comes up often when using array.nonzero() to gather boolean logic: lack of support for zero-length tensors means that you have to make special-case python checks for empty results rather than using straight-line vectorized pytorch code.  Numpy's design of zero-length dimensions avoids this problem.  The number of scalars held by a tensor should always be the product of its dimensions, which means the a zero dimension is fine - it holds no data, but it still has shape.

A similar and related issue: numpy also supports tensors with no dimensions at all, which, following the product of dimensions rule, will hold a single scalar value.  Doing this also avoids a bunch of special cases when writing code when the number of tensor dimensions can vary.

```
>>> a = numpy.ones(())
>>> a, a.shape, a[()]
(array(1.0), (), 1.0)
>>>
```

**Comment by fmassa** [comment]
I agree with you that it would be great to have support for zero dimensions, but I'm not sure how much work that would involve.
We have solved this problem with `torch.cat` by manually handling empty tensors, but properly handling zero dimensions would maybe be better.

About tensors with no dimensions, we are introducing scalars in pytorch, which is similar to numpy. You can find a very nice discussion about it in https://github.com/pytorch/pytorch/issues/1433#issuecomment-329907197.

**Comment by soumith** [comment]
scalars were introduced into pytorch by @gchanan, so closing this.

**Comment by fmassa** [comment]
@soumith this is not actually entirely addressed.
We do support scalars, but not tensors / variables having zero in their dimension.
For example
```python
print(np.zeros((0, 4))
# array([], shape=(0, 4), dtype=float64)
print(torch.zeros(0, 4))
# [torch.FloatTensor with no dimension]
```

This actually makes a difference in many cases. Up until recently, concatenation with tensors with no dimensions was an error (but now is specially handled).

I've faced other cases that pytorch code doesn't work but numpy does.
The following works in numpy, but fails in pytorch:
```python
a = np.random.rand(0, 4)
print([b.shape[0] for b in a])

a[:, 2:] += a[:, :2]
print(a[:, 2])
```

**Comment by gchanan** [comment]
One quibble with the above (@fmassa).

We do support variables having zero in their dimension, but only size (0,) (everything else gets reduced to that shape).
```
>>> torch._C._VariableFunctions.zeros( (0,4) )
Variable containing:
[torch.FloatTensor of size (0,)]
```

**Comment by zou3519** [comment]
Carrying on from the discussion on #5889, this feature would be helpful to have for `torch.cat`. Right now its behavior is the following:
1) torch.cat([empty, tensor]) ignores empty tensors (where an empty tensor is defined as a tensor of size `(0,)`)
2) torch.cat([tensor, empty]) ignores empty tensors
3) torch.cat([empty, empty, ..., empty]) should be empty

However, this behavior is different from numpy's `concatenate` function.
To match np behavior, one of the invariants for `torch.cat` should be that all tensors being concatenated should have the same size in all dimensions except the specified cat dimension. When we have empty tensors with arbitrary shapes, they should also follow this invariant:
- `torch.cat([tensor of size (1, 0, 4), tensor of size (1, n, 4)])` should work
- `torch.cat([tensor of size (0,), tensor of size (1, 2)])` should fail.

**Comment by Saulzar** [comment]
This is particularly useful for code using a variable number of items, e.g. boxes in object detection. Otherwise it's necessary to have all these special case checks for the empty tensor! 

What's more the behaviour changed between pytorch 0.3 and 0.4, empty tensors used to be dim = 0, now they're dim = 1, size = 0!

**Comment by fmassa** [comment]
I believe handling of tensors with zero dimensions will be included in the upcoming C10 library

**Comment by asford** [comment]
Just to support the point above, this becomes quite useful when using reshape & broadcast to perform broadcast operations over variable-sized collections. As a, somewhat contrived, example imagine a function calculating of inter-coordinate distances, given by `(a-b).norm()`, in batch for a set of points. Intuitively, the following code would be expected to work:

```python
def torch_inter_coord_distance(a: "Tensor[n,3]", b: "Tensor[m, 3]") -> "Tensor[n, m]":
    return (a.unsqueeze(1) - b.unsqueeze(0)).norm(dim=-1)
```

However, this is impossible to express for "empty" batches without broadcasting along 0-sized dimensions. 

A full repo, starting with the equivalent numpy implementation:
```python
import numpy

def numpy_inter_coord_distance(a: "ndarray[n,3]", b: "ndarray[m, 3]") -> "ndarray[n, m]":
    return numpy.linalg.norm((numpy.expand_dims(a, 1) - numpy.expand_dims(b, 0)), axis=-1)

coords = numpy.arange(12).reshape(4, 3)
print("numpy:")
print("4x4:")
print(numpy_inter_coord_distance(coords, coords))
print(numpy_inter_coord_distance(coords, coords).shape)
print()

print("2x4:")
print(numpy_inter_coord_distance(coords[0:2], coords))
print(numpy_inter_coord_distance(coords[0:2], coords).shape)
print()

print("0x4:")
print(numpy_inter_coord_distance(coords[0:0], coords))
print(numpy_inter_coord_distance(coords[0:0], coords).shape)
print()

import torch

def torch_inter_coord_distance(a: "Tensor[n,3]", b: "Tensor[m, 3]") -> "Tensor[n, m]":
    return (a.unsqueeze(1) - b.unsqueeze(0)).norm(dim=-1)

coords = torch.arange(12).reshape(4, 3)

print("torch:")
print("4x4:")
print(torch_inter_coord_distance(coords, coords))
print(torch_inter_coord_distance(coords, coords).shape)
print()

print("2x4:")
print(torch_inter_coord_distance(coords[0:2], coords))
print(torch_inter_coord_distance(coords[0:2], coords).shape)
print()

print("0x4:")
print(torch_inter_coord_distance(coords[0:0], coords))
print(torch_inter_coord_distance(coords[0:0], coords).shape)
print()
```
Output:
```
numpy:
4x4:
[[ 0.          5.19615242 10.39230485 15.58845727]
 [ 5.19615242  0.          5.19615242 10.39230485]
 [10.39230485  5.19615242  0.          5.19615242]
 [15.58845727 10.39230485  5.19615242  0.        ]]
(4, 4)

2x4:
[[ 0.          5.19615242 10.39230485 15.58845727]
 [ 5.19615242  0.          5.19615242 10.39230485]]
(2, 4)

0x4:
[]
(0, 4)

torch:
4x4:
tensor([[  0.0000,   5.1962,  10.3923,  15.5885],
        [  5.1962,   0.0000,   5.1962,  10.3923],
        [ 10.3923,   5.1962,   0.0000,   5.1962],
        [ 15.5885,  10.3923,   5.1962,   0.0000]])
torch.Size([4, 4])

2x4:
tensor([[  0.0000,   5.1962,  10.3923,  15.5885],
        [  5.1962,   0.0000,   5.1962,  10.3923]])
torch.Size([2, 4])

0x4:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-3326f96b342b> in <module>()
     40 
     41 print("0x4:")
---> 42 print(torch_inter_coord_distance(coords[0:0], coords))
     43 print(torch_inter_coord_distance(coords[0:0], coords).shape)
     44 print()

<ipython-input-6-3326f96b342b> in torch_inter_coord_distance(a, b)
     24 
     25 def torch_inter_coord_distance(a: "Tensor[n,3]", b: "Tensor[m, 3]") -> "Tensor[n, m]":
---> 26     return (a.unsqueeze(1) - b.unsqueeze(0)).norm(dim=-1)
     27 
     28 coords = torch.arange(12).reshape(4, 3)

RuntimeError: cannot unsqueeze empty tensor
```

**Comment by jhultman** [comment]
I would love to see this addressed too. Like @davidbau mentioned, I have to add an ugly empty check when using `torch.nonzero` since the indices returned are 1D (and of zero length) when no elements are nonzero:

```
condition = ...
inds = condition.nonzero()
if inds.numel() > 0:
    i, j = condition.nonzero().t()
else:
    i = j = torch.tensor([]).long()
```

**Comment by gchanan** [comment]
This has already been addressed.
