### ISSUE TITLE
No documentation for `torch.sgn`

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#50146]
## 📚 Documentation

`torch.sgn`, not to be confused with `torch.sign` is not documented at all. 

Important things to mention in the docs include:
 - the fact that it support complex, unlike `torch.sign`
 - difference from NumPy's sign, which also supports complex
 - the formula for what it does when input is complex (since there are many different possible formulas)

cc @ezyang @anjali411 @dylanbespalko @mruberry @jlin27

**Comment by mruberry** [comment]
It is actually documented but it's missing an torch.rst entry so it doesn't appear in the built docs. See here:

https://github.com/pytorch/pytorch/blob/68a6e4637903dba279c60daae5cff24e191ff9b4/torch/_torch_docs.py#L7517
