### ISSUE TITLE
[doc] Broken formatting for the function signature of `torch.randperm`

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#50207]
## 📚 Documentation

Documentation does not mention anything about randperm accepting a generator.
https://pytorch.org/docs/stable/generated/torch.randperm.html

Following works:
```python
>>> torch.randperm(10, generator=g)
```

Also,
https://github.com/pytorch/pytorch/blob/321b98830e17e9e1a366ababeb5475f9f202c815/aten/src/ATen/native/native_functions.yaml#L3073-L3086

cc @jlin27 @mruberry

**Comment by zou3519** [comment]
We would accept a PR to fix this (unless it turns out that there's a reason why this isn't documented)

**Comment by mruberry** [comment]
cc @ngimel - is there a better label or person to cc for this?

**Comment by ngimel** [comment]
cc @pbelevich, I don't think there's a reason for it to be undocumented. See also #44714 for some corner cases where generator argument is ignored causing segfaults.

**Comment by kshitij12345** [comment]
It is fixed in https://github.com/pytorch/pytorch/pull/47231

Correct documentation is available on docs for master: https://pytorch.org/docs/master/generated/torch.randperm.html?highlight=torch%20randperm#torch.randperm

The formatting of the function signature looks to be broken,
![Screenshot from 2021-01-08 10-03-54](https://user-images.githubusercontent.com/19503980/103974946-edb6ef80-5198-11eb-9c80-0b46c6bea06a.png)
