### ISSUE TITLE
[doc] Broken formatting on `torch.repeat_interleave`

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#50208]
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html
![Screenshot from 2021-01-07 21-27-25](https://user-images.githubusercontent.com/19503980/103914094-55385500-512f-11eb-84fa-273241aa499e.png)

cc @jlin27 @mruberry

**Comment by zou3519** [comment]
We would accept a PR to fix this.

**Comment by kshitij12345** [comment]
Sure.
