### ISSUE TITLE
Build broken on ubuntu due to MKL symbols not found

### ISSUE THREAD

**Issue by antocuni** [pytorch/pytorch#50211]
## 🐛 Bug

On my system, pytorch builds fine, but using MKL function fails:

```
$ python -c 'import torch; torch.tensor([[1.0, 2], [3, 4]]).svd()'
INTEL MKL ERROR: /home/antocuni/.conda/envs/pytorch-cuda-dev/lib/libmkl_def.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_def.so.
```

## To Reproduce

1. `python setup.py develop`
1. `python -c 'import torch; torch.tensor([[1.0, 2], [3, 4]]).svd()'`

Depending on which MKL operations is used, the undefined symbol varies.

## Expected behavior

Not to crash :)

## Environment

I think that the relevant env variable is `LDFLAGS`:

```
$ echo $LDFLAGS
-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/antocuni/.conda/envs/pytorch-cuda-dev/lib -Wl,-rpath-link,/home/antocuni/.conda/envs/pytorch-cuda-dev/lib -L/home/antocuni/.conda/envs/pytorch-cuda-dev/lib -Wl,-rpath-link,/usr/local/cuda-11.0.3/lib64 -L/usr/local/cuda-11.0.3/lib64
```

Note that it contains `--as-needed`.

I bisected the commits and the culprit seems to be 12ee7b61e7, added by #50080 . The problem is that if LDFLAGS contains `--as-needed`, it overrides the `--no-as-needed` which is added by the `if`.
An easy workaround is to manually add `--no-as-needed` at the end of my LDFLAGS, but I claim that since the `if` clearly tries to take care of it, the PR is wrong.

cc @malfet @seemethere @walterddr

**Comment by walterddr** [comment]
could you try patching #50080 and see if it helps?

**Comment by walterddr** [comment]
thanks for reporting the issue. looking into it.
