### ISSUE TITLE
RuntimeError: hook 'hookFunc' has returned an incorrect number of values (got 1, but expected 4)

### ISSUE THREAD

**Issue by tstandley** [pytorch/pytorch#5022]
I'm having trouble with module.register_backward_hook(), and I think it might be a bug.
Here's the relevant code:
```
def instrument_model(model,fraction_list):
    def register_hook(module):
        def hookFunc(module, gradInput, gradOutput):
            
            if isinstance(gradOutput, tuple):
                print(len(gradOutput))
                for i in gradOutput:
                    print(i.size())
                ret = tuple([torch.zeros(g.size()) for g in gradOutput])
                print(len(ret))
                for i in ret:
                    print(i.size())
            else:
                print(gradOutput.size())
                ret = torch.zeros(gradOutput.size())
                print(ret.size())
            return ret
            
            
            

        module.register_backward_hook(hookFunc)
    model.apply(register_hook)
```

For which I get the following error:

`RuntimeError: hook 'hookFunc' has returned an incorrect number of values (got 1, but expected 4)`

The print statements have confirmed that `ret` matches the shape of `gradInput` in both length of the tuple and size of all constituents.

Ideally, this would set all gradients to zero.

Any idea what's going on?

**Comment by antspy** [comment]
Shoudn't register_backward_hook return a Tensor or None? Your function will return a tuple, won't it?

Btw, if you can zero all the gradients of a model by calling model.zero_grad()

**Comment by zou3519** [comment]
As @antspy said, the problem is that you're returning a tuple with the same number of elements as the gradOutput tuple, but it should really be the gradInput tuple.
