### ISSUE TITLE
Support CUDA 11.2

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#50232]
This issue will track the current progress on adding CUDA 11.2 support. 

- [X] Installing to conda-cuda and libtorch containers (https://github.com/pytorch/builder/pull/616)
     - [X] Push pytorch/conda-cuda
     - [X] Push the libtorch image (`pytorch/pytorch-binary-docker-image-ubuntu16.04:latest`)
- [X] Add setup to manywheels (https://github.com/pytorch/builder/pull/617) + edit (https://github.com/pytorch/builder/pull/646)
- [X] Update MAGMA (https://github.com/pytorch/builder/pull/618)
     - [X] Push magma-cuda112
- [x] Add Windows builder for 11.2 (https://github.com/pytorch/builder/pull/636)
     - [x] Update Windows driver (https://github.com/pytorch/builder/pull/631) 
- [x] Replace 11.1 with 11.2 into CI (Disclaimer: CI has been reverted.)
     - [X] Add MAGMA to CI conda #50559
     - [ ] Windows #51598
     - [ ] Linux  #51905
- [x] Include CUDA 11.2 into our nightly matrix #51874 with #51864
     - [x] Update conda `build_pytorch.sh` script among others (https://github.com/pytorch/builder/pull/640)
     - [x] Tackle any bugs that come up: https://github.com/pytorch/builder/pull/645, https://github.com/pytorch/builder/pull/647 and https://github.com/pytorch/builder/pull/638
     - [x] Windows
     - [x] Linux 

cc @ezyang @seemethere @malfet @walterddr

**Comment by peterjc123** [comment]
@janeyx99 What about Windows? Is it still 0%?

**Comment by janeyx99** [comment]
> @janeyx99 What about Windows? Is it still 0%?

Currently yes. If you'd like to contribute, that'd be much encouraged and appreciated! :) Otherwise, it is on the roadmap.

**Comment by peterjc123** [comment]
@janeyx99 Ok, I will do that when cudnn for cuda 10.2 is out.

**Comment by byronyi** [comment]
Does cuDNN support cuda 11.2 yet?

**Comment by stas00** [comment]
> Does cuDNN support cuda 11.2 yet?

According to this table, no:
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

**Comment by janeyx99** [comment]
cuDNN for 11.1 suffices for CUDA 11.2, so you can get started using that.

> @janeyx99 Ok, I will do that when cudnn for cuda 10.2 is out.

**Comment by peterjc123** [comment]
@janeyx99 The MAGMA binaries for CUDA 11.2 on Windows have been generated and pushed to S3. 
http://s3.amazonaws.com/ossci-windows/magma_2.5.4_cuda112_release.7z
http://s3.amazonaws.com/ossci-windows/magma_2.5.4_cuda112_debug.7z
Also, the CUDA installer has been pushed to S3.
http://s3.amazonaws.com/ossci-windows/cuda_11.2.0_460.89_win10.exe

**Comment by peterjc123** [comment]
cudnn 8.1 for Windows is also uploaded
http://s3.amazonaws.com/ossci-windows//cudnn-11.2-windows-x64-v8.1.0.77.zip

cc @zasdfgbnm

**Comment by janeyx99** [comment]
> The GPU driver and cudnn 8.1 for Windows are also uploaded
> http://s3.amazonaws.com/ossci-windows/cudnn-11.2-windows-x64-v8.1.0.77.zip
> http://s3.amazonaws.com/ossci-windows/461.09-data-center-tesla-desktop-winserver-2019-2016-international.exe

@peterjc123 @zasdfgbnm 
I opened a PR here for windows in the builder repo: https://github.com/pytorch/builder/pull/636--could you take a look?

**Comment by ptrblck** [comment]
There are known issues in building PyTorch with CUDA11.2 we are facing now regarding the functionality as well as performance. We are actively working with the CUDA team to isolate and fix this issues. Until we have resolutions we discourage users to use CUDA 11.2 with PyTorch.

**Comment by malfet** [comment]
Based on @ptrblck removing CUDA-11.2 target from 1.8.0 milestone

**Comment by zhaopku** [comment]
Any update on this? @ptrblck @janeyx99 
Looks like Nvidia has released [their PyTorch with CUDA 11.2 support](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_21-03.html#rel_21-03). When will PyTorch officially support CUDA 11.2?

**Comment by janeyx99** [comment]
PyTorch is now looking at supporting CUDA 11.3 instead of 11.2, as it should fix some of the aforementioned regressions.

**Comment by Ayush1702** [comment]
So is the Torch support for CUDA 11.2 scrapped then? I already had it installed since last year, so should I go ahead with CUDA 11.3 then?

> PyTorch is now looking at supporting CUDA 11.3 instead of 11.2, as it should fix some of the aforementioned regressions.

**Comment by janeyx99** [comment]
This is up to you, but going ahead with CUDA 11.3 is probably a good move. CUDA 11.3 is on the roadmap of being fully supported (the last thing missing is conda binaries as cudatoolkit11.3 is not yet on conda) while the trajectory for CUDA 11.2 is definitely less certain.
