### ISSUE TITLE
[ppc64le] Build break for cpu only build on ppc64le due to recently added  ABI compatibility check to cpp_extensions.py 

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#5023]
Please have a look at log:
https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le/137/console

I think it is due to this recent commit : 9e36f979c92919b3ea114f96045574ac66672b12 by @goldsborough 
or it maybe this commit 390d542db2bcc884c33c3a81d56576b56ede72cd , when ninja is now being required
Please verify.

**Comment by goldsborough** [comment]
Yes, we have added a feature that requires `ninja` in tests. You can:
1. `conda install ninja`, since you're already using conda,
2. Clone ninja from GitHub, as we do [here](https://github.com/pytorch/pytorch/blob/master/.jenkins/test.sh#L43).

**Comment by avmgithub** [comment]
Ok , thanks . Let me make sure I have ninja on ppc64le, if not I'll try to manually build/install it on the build server.

**Comment by avmgithub** [comment]
Closing this issue. Installing ninja on the build system fixed it.
