### ISSUE TITLE
[feature request] expose Conv2dBackward to python

### ISSUE THREAD

**Issue by davidbau** [pytorch/pytorch#5024]
Tensorflow directly provides conv2d_backprop_filter and conv2d_backprop_input functions, but they are not available in pytorch as operations that can be called directly from python.

e.g.: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_backprop_filter.  These are useful when implementing alternate forms of backprop through convolution (discretized, layerwise relevance backprop, etc).

More discussion here https://discuss.pytorch.org/t/how-to-do-convolution-backward-manually/1430

Although pytorch obviously can do these operations during backprop using a C implementation, it doesn't currently expose the functions directly in python.

**Comment by fmassa** [comment]
Quick question: isn't [`conv2d_backprop_input`](https://github.com/pytorch/pytorch/blob/master/aten/src/THNN/generic/SpatialDilatedConvolution.c#L268-L286) roughly equivalent to [`conv2d_transpose`](https://github.com/pytorch/pytorch/blob/master/aten/src/THNN/generic/SpatialFullDilatedConvolution.c#L153-L169)?

**Comment by SsnL** [comment]
If your modification to backprop is not too crazy, you can do it via backward hooks.
