### ISSUE TITLE
IndexError: Target 117 is out of bounds.

### ISSUE THREAD

**Issue by liunian-netizen** [pytorch/pytorch#50259]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by liunian-netizen** [comment]
Traceback (most recent call last):
  File "E:/pytorch的编译资料/pytorch 全连接神经网络.py", line 102, in <module>
    loss = criterion(out, target.long())
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 962, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 2468, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 2264, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 117 is out of bounds.

**Comment by skyline75489** [comment]
Please fill the issue template to provide more information. Show us the code if necessary. Not just in the PyTorch repo. You should provide as much as information as you can no matter the repo you're working with.

**Comment by skyline75489** [comment]
A "issue template" is what you see when you try to create the issue. Do not just delete that. It's useful for the maintainers to have enough context to work with.

**Comment by skyline75489** [comment]
Github is meant be be a place to report issues about PyTorch *itself*. For general support, please go to the [Discussion Forum](https://discuss.pytorch.org/).

**Comment by liunian-netizen** [comment]
import torch
from torch.autograd import Variable
import numpy as np
import matplotlib.pyplot as plt
from torch import nn, optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

# 定义三层全连接神经网络
class simpleNet(nn.Module):
    def __init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):  # 输入维度，第一层的神经元个数、第二层的神经元个数，以及第三层的神经元个数
        super(simpleNet, self).__init__()
        self.layer1 = nn.Linear(in_dim, n_hidden_1)
        self.layer2 = nn.Linear(n_hidden_1, n_hidden_2)
        self.layer3 = nn.Linear(n_hidden_2, out_dim)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x


# 添加激活函数
class Activation_Net(nn.Module):
    def __init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Sequential(  # Sequential组合结构
            nn.Linear(in_dim, n_hidden_1), nn.Sigmoid(True))
        self.layer2 = nn.Sequential(
            nn.Linear(n_hidden_1, n_hidden_2), nn.Sigmoid(True))
        self.layer3 = nn.Sequential(
            nn.Linear(n_hidden_2, out_dim))

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x


# 添加批标准化处理模块,批标准化放在全连接的后面，非线性的前面
class Batch_Net(nn.Module):
    def _init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):
        super(Batch_Net, self).__init__()
        self.layer1 = nn.Sequential(nn.Linear(in_dim, n_hidden_1), nn.BatchNormld(n_hidden_1), nn.ReLU(True))
        self.layer2 = nn.Sequential(nn.Linear(n_hidden_1, n_hidden_2), nn.BatchNormld(n_hidden_2), nn.ReLU(True))
        self.layer3 = nn.Sequential(nn.Linear(n_hidden_2, out_dim))

    def forword(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

from torch.utils.data import DataLoader
from torchvision import datasets,transforms
#定义一些超参数
batch_size=16
learning_rate=1e-2

#预处理
'''data_tf=transforms.Compose(
[transforms.ToTensor(),transforms.Normalize([0.5],[0.5])])#将图像转化成tensor，然后继续标准化，就是减均值，除以方差'''

#读取数据集
xy1 = np.loadtxt('E:\pytorch的编译资料\iba结晶器文件资料分析\塞棒位置的数据.txt', dtype=np.float32)
y1= torch.from_numpy(xy1[:,[-1]])
x1=torch.from_numpy(xy1[:,:-1])
print(x1.shape)
print(y1.shape)

#导入网络，定义损失函数和优化方法
model=simpleNet(1,10,10,1)



criterion=nn.CrossEntropyLoss()
optimizer=optim.SGD(model.parameters(),lr=learning_rate,momentum=0.9)
num_epochs = 100
for epoch in range(num_epochs):
    if torch.cuda.is_available():
        inputs = Variable(x1)


        target = Variable(y1)

    else:
        inputs = Variable(x1)
        target = Variable(y1)

    # 向前传递
    out = model(inputs)
    print(out.shape)

    print(target.shape)
    target = target.squeeze()

    print('target:',target)
    loss = criterion(out, target.long())
    print(loss)
if __name__ == '__main__':
    num_processes = 1

    # backward 梯度计算
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()  # update parameters
    if (epoch+1) % 20 == 0:
        print('Epoch[{}/{}], loss:{:.6f}'.format(epoch+1, num_epochs, loss.item()))
model.eval()
# predict = model(Variable(x_train.cuda()))
predict = model(Variable(x1.cuda()))
predict = predict.data.cpu().numpy()
plt.plot(x1.numpy(), y1.numpy(), 'ro', label='Original data')
plt.plot(x1.numpy(), predict,label='Fitting Line')
plt.legend()
plt.show()

**Comment by skyline75489** [comment]
首先 GitHub 只用来处理 PyTorch 开发本身有关的问题，如果不能确定是不是 PyTorch 本身的问题，请前往 [支持论坛](https://discuss.pytorch.org/) 或者 StackOverflow。

First of all, Github is supposed to be a place for the development of PyTorch itself. If you are not sure the issue is in fact a PyTorch issue, please go to the discussion forum or stackoverflow.

其次，几乎永远都不要贴完整的代码，对大部分人来说是一种时间上的浪费，请提供一个[最小的，可复现的例子](https://stackoverflow.com/help/minimal-reproducible-example)。

Second, almost never post all the content of the source code, which is just a total waste a time for everyone. Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

最后，在贴代码之前请做好格式化以方便人们阅读，请参考 [Github 的文档](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks).

Last but not least, please format the code before posting it. Check out the [documentation provided by Github](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks).
