### ISSUE TITLE
FusedKernelCPU failed to delete generated dll files on Windows 

### ISSUE THREAD

**Issue by skyline75489** [pytorch/pytorch#50260]
## 🐛 Bug

Found during #49781.

This line actually fails to unlink the dll, resulting in `EACCESS`:

https://github.com/pytorch/pytorch/blob/c215ffb6a2de1c85a62a146a9e282908335ba3ed/torch/csrc/jit/codegen/fuser/cpu/temp_file.h#L120

By the look of it, seems `DynamicLibrary` is still holding a lock on the dll files.

Another thing worth mentioning is that `cl.exe` generate `lib`, `obj` and `exp` file together with the `dll`. Those intermediate files are not getting cleaned.

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @gmagogsfm

**Comment by skyline75489** [comment]
CC @peterjc123 Don't know it's a known issue to you.

**Comment by peterjc123** [comment]
I didn't notice that before. Thanks for pointing it out. And I have to say this is not easy to fix. Maybe we could create a temp dir instead and remove the dir when the fusedkernel is destroyed. Otherwise, we are totally out of control that what files will be generated by the MSVC toolchain.

**Comment by Lilyjjo** [comment]
We from the JIT side don't have plans to work on this as it uses a fuser that we no longer actively support. We would accept a PR to fix it though!

**Comment by mantaionut** [comment]
@skyline75489 is this issue still relevant. If so do you know how to reproduce it?

**Comment by mantaionut** [comment]
I am closing this issue due to a lack of activity. Please don't hesitate to open a new issue if you still encounter this issue.
