### ISSUE TITLE
default_collate: if elem in batch is list, the whole batch would be transpose?

### ISSUE THREAD

**Issue by dancingpipi** [pytorch/pytorch#50272]
https://github.com/pytorch/pytorch/blob/c215ffb6a2de1c85a62a146a9e282908335ba3ed/torch/utils/data/_utils/collate.py#L82

Is this expect?

code below:
```python
class MyDataset(Dataset):
    def __init__(self):
        self.data = torch.randn(2, 3).tolist()
        self.target = torch.randint(0, 10, (2,)).tolist()

    def __getitem__(self, index):
        x = self.data[index]
        y = self.target[index]
        return {'data': x, 'target': y}

    def __len__(self):
        return len(self.data)


dataset = MyDataset()
loader = DataLoader(
    dataset,
    batch_size=2,
    num_workers=2,
)

for batch in loader:
    print(batch)
```

output:

`{'data': [tensor([0.3175, 0.4267], dtype=torch.float64), tensor([ 0.4768, -0.6364], dtype=torch.float64), tensor([-1.6446, -0.9557], dtype=torch.float64)], 'target': tensor([4, 1])}`

expect:
`{'data': [tensor([0.3175, 0.4768,-1.6446], dtype=torch.float64),  tensor([0.4267, -0.6364, -0.9557], dtype=torch.float64)], 'target': tensor([4, 1])}`

my doubt:

Why transpose batch while elem is sequence type? How should I deal with list elem type? 

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
The reason is we want to combine the data for each batch. Like your example, you have 3 features for each data and you set batch_size as 2. We combine each feature within the batch. So, in the output, you ultimately have 3 features, each feature represent the values for the batch which is 2.
You can see the output is a list of three tensors, each tensor has 2 value.
The output should be expected.

**Comment by ejguan** [comment]
Closing the issue as it seems the issue has already been solved. Feel free to re-open it if needed.
And, feel free to discuss your questions on PyTorch Forum (https://discuss.pytorch.org/)

**Comment by shapovalov** [comment]
@ejguan Thanks for your response. Can I follow up since I have a similar confusion?
We also call `default_collate` recursively in the `Sequence` branch. Does this transpose logic still make sense if e.g. `List[List[List[int]]]` is passed?

**Comment by shapovalov** [comment]
I see, thanks for the explanation. I think there are two ways to interpret lists: as a feature group (as done now), or as blobs of data (of potentially variable length). It would be good to allow the second as well. Our use case is storing the list of classes present in the image (of course it can be stored as one-hot vector but this hopefully illustrates the point).

**Comment by ejguan** [comment]
We provide a default collate_fn for general purpose as we don't have chance to let a function to handle all different use cases.
If you need specific functionalities, you should provide a custom collate_fn for DataLoader to handle you case.
