### ISSUE TITLE
[feature request]: Spectral Normalization

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#5027]
I wonder if someone can write code for the newly proposed normalization method called "Spectral Normalization". It seems to be useful!

**Comment by rosinality** [comment]
I have tried write it: https://gist.github.com/rosinality/a96c559d84ef2b138e486acf27b5a56e Similar approach to weight normalization.

**Comment by Amir-Arsalan** [comment]
@soumith Any updates on this?

**Comment by SsnL** [comment]
Fixed via #6929
