### ISSUE TITLE
Review torch.linalg module ahead of release

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#50287]
This issue is a reference for quality checking the torch.linalg module ahead of 1.8 release.

- Ensure documentation is consistent across torch.linalg ops
- Review uses of out= for consistency and performance, including unnecessary copies and unwanted resizing
- Review and document all cross-device sync

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
Findings incorporated into https://github.com/pytorch/pytorch/issues/42666.
