### ISSUE TITLE
Discuss options for implementing einsum_path

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#50285]
np.einsum_path computes the optimal contraction order (depending on chosen algorithm may be suboptimal) for computing einsum. It returns the path which can then be passed to np.einsum via the optimize parameter. Alternatively, one can say optimize=True to run einsum_path internally and use it one time.

NumPy seems to use the library https://optimized-einsum.readthedocs.io/en/stable/.

We need to add the optimize flag to torch.einsum and implement, or not, einsum_path.

Some options to consider for implementing torch.einsum_path are.
1. Use opt_einsum as NumPy does
2. Implement custom logic for computing the optimal path
3. Don't implement torch.einsum_path and simply direct people to opt_einsum library in the torch.einsum documentation and ensure torch.einsum can take a path from opt_einsum as parameter.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @rgommers

**Comment by mruberry** [comment]
NumPy's einsum [seems much more popular](https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/numpy-summary.csv) than its einsum_path, and it does seem strange that it's a separate function vs. a kwarg. 

@rgommers, what are your thoughts? Maybe we should just alias einsum_path to einsum?

**Comment by rgommers** [comment]
I've never seen `einsum_path` used much, I would not add it as a separate function. Adding only the `optimize` keyword makes more sense to me, or doing nothing except adding docs (option 3 above).

**Comment by mruberry** [comment]
Additional context: it seems like JAX uses opt-einsum.

**Comment by heitorschueroff** [comment]
The purpose of einsum_path is to save the contraction order to reuse in multiple calls of einsum. However, the time to compute the einsum_path is likely to be insignificant compared to the time to actually compute einsum. We could start by just adding the optimize parameter until someone requests einsum_path.

**Comment by mruberry** [comment]
Adding the "optimize" kwarg to einsum sounds like a great start.

**Comment by danieleds** [comment]
Adding the "optimize" flag to einsum is linked to #52655

**Comment by heitorschueroff** [comment]
Closing this as we decided to start with adding optimize kwarg to torch.einsum and only later, and if requested, implement torch.einsum_path.

**Comment by arjunpat** [comment]
Hi there, wondering if this ever got implemented. I'm thinking about the case when one of my nn.Module uses a torch.einsum, for example when computing attention over mini-batches. I would like to compute the optimal execution path in the constructor of my module and use that optimal execution path while training/evaluating (in forward) to see the speedup. Is there a way to do that at the moment?
