### ISSUE TITLE
Allow ProcessGroup specific options in init_process_group and new_group

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#50295]
## 🚀 Feature
We have seen a few use cases where users directly call the [pybind APIs](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/init.cpp#L1020) `dist.ProcessGroupNCCL` and `dist.ProcessGroupGloo` since they need to configure the process groups with specific `Options`, such as whether the NCCL PG should use a high priority stream. This must be done because our current recommended APIs such as `dist.new_group` and `dist.init_process_group` do not take in such an options struct (see for example https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L2429).

The above workaround can work, but it is bug prone as things such as `barrier()` can easily be forgotten. We should support PG-backend specific options as arguments into process group creation APIs.

## Pitch

Allow options struct to be passed into [init_process_group](https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L391) and [new_group](https://github.com/pytorch/pytorch/blob/master/torch/distributed/distributed_c10d.py#L2429). For NCCL, we expect an instance of `ProcessGroupNCCLOptions` (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/init.cpp#L1573) and for Gloo we expect `ProcessGroupGloo.Options` (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/init.cpp#L954). 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by wanchaol** [comment]
This has been fixed, closing.
