### ISSUE TITLE
running a job on multiple gpus with qsub

### ISSUE THREAD

**Issue by rabeehk** [pytorch/pytorch#50324]
Hi
I would like to run a scirpt on multiple gpus with a qsub job submission, using torch.distributed command, I am not sure how to do this with qsub, when the gpus are in different machines, could you provide me with some initial script for this? thanks

**Comment by pranavdurai10** [comment]
@rabeehk I guess this link will give you a good head-start. 
https://pytorch.org/docs/stable/distributed.html
