### ISSUE TITLE
Error when export custom LSTM cell model to ONNX with jit script

### ISSUE THREAD

**Issue by YongHuangSJTU** [pytorch/pytorch#50365]
## 🐛 Bug

I can't export my custom LSTM cell model to ONNX with jit script

## To Reproduce

Here's my code

```python

import numpy
import torch
import torch.nn as nn
import torch.jit as jit


class MyLSTMCell(jit.ScriptModule):
    def __init__(self, input_size, hidden_size):
        super(MyLSTMCell, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.weight_ih = nn.Linear(input_size, 4 * hidden_size)
        self.weight_hh = nn.Linear(hidden_size, 4 * hidden_size)

    @jit.script_method
    def forward(self, input, state):
        # type: (Tensor, Tuple[Tensor, Tensor]) -> Tuple[Tensor, Tuple[Tensor, Tensor]]
        hx, cx = state

        gates = self.weight_ih(input) + self.weight_hh(hx)
        
        ingate, forgetgate, cellgate, outgate = torch.split(gates, self.hidden_size)

        ingate = torch.sigmoid(ingate)
        forgetgate = torch.sigmoid(forgetgate)
        cellgate = torch.tanh(cellgate)
        outgate = torch.sigmoid(outgate)

        cy = (forgetgate * cx) + (ingate * cellgate)
        hy = outgate * torch.tanh(cy)

        return hx, (hy, cy)

class LoopModel(jit.ScriptModule):
    def __init__(self, input_size, hidden_size):
        super(LoopModel, self).__init__()
        self.lstm = MyLSTMCell(input_size, hidden_size)

    @jit.script_method
    def forward(self, x):
        # type: (Tensor)-> (Tensor)
        hx = torch.randn(20)
        cx = torch.randn(20)
        output = []
        for i in range(len(x)):
            a, (hx, cx) = self.lstm(x[i], (hx, cx))
            output.append(hx)
        return hx


def generate_model():
    model = LoopModel(8, 20)
    dummy_input = torch.ones(3, 8, dtype=torch.float)
    o = model(dummy_input)
    torch.onnx.export(model, dummy_input, 'loop.onnx', verbose=True,
                    input_names=['input_data'], example_outputs=o)
    print("done")

generate_model()
```
------------------------------------------------
Error:

  File "d:\Augloop\py\same2.py", line 59, in <module>
    generate_model()
  File "d:\Augloop\py\same2.py", line 56, in generate_model
    input_names=['input_data'], example_outputs=o)
  File "D:\Tools\Conda\lib\site-packages\torch\onnx\__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\Tools\Conda\lib\site-packages\torch\onnx\utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "D:\Tools\Conda\lib\site-packages\torch\onnx\utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "D:\Tools\Conda\lib\site-packages\torch\onnx\utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "D:\Tools\Conda\lib\site-packages\torch\onnx\utils.py", line 359, in _create_jit_graph
    method_graph, params = torch._C._jit_pass_lower_graph(graph, model._c)
**RuntimeError: Unknown type int encountered in graph lowering. This type is not supported in ONNX export.**

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: 10.0.0
CUDA runtime version: 10.0.130
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245    anaconda
[conda] mkl-service               2.3.0            py37hb782905_0    anaconda
[conda] mkl_fft                   1.0.14           py37h6288b17_0
[conda] mkl_random                1.0.4            py37h343c172_0
[conda] numpy                     1.17.0           py37h19fb1c0_0
[conda] numpy-base                1.17.0           py37hc3f5095_0
[conda] numpydoc                  1.1.0                      py_0
[conda] torch                     1.7.1                    pypi_0    pypi

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @gmagogsfm

**Comment by BowenBao** [comment]
Hi @YongHuangSJTU, could you check which PyTorch version you are using? Your description shows both `PyTorch version: 1.4.0+cpu` and `[pip3] torch==1.7.1`. 
I'd recommend using the latest release. I tried with your script in latest master, and it exported fine.

**Comment by YongHuangSJTU** [comment]
> Hi @YongHuangSJTU, could you check which PyTorch version you are using? Your description shows both `PyTorch version: 1.4.0+cpu` and `[pip3] torch==1.7.1`.
> I'd recommend using the latest release. I tried with your script in latest master, and it exported fine.

Hi BowenBao, thanks for your reply. I upgraded Pytorch version and it shows a different error now, updated in issue description.

**Comment by YongHuangSJTU** [comment]
I can export ONNX model after upgrade to latest nightly build pytorch. Thanks @BowenBao for your help.
