### ISSUE TITLE
module 'torch' has no attribute 'potrf'

### ISSUE THREAD

**Issue by aktaseren** [pytorch/pytorch#50379]
## 🐛 Bug
I can not execute a script run by pytorch. I am having the issue on the lines below.

```
~/Desktop/ULfAD/ceadarscript/DAGMMphase/model.py in forward(ctx, a)
     17 class Cholesky(torch.autograd.Function):
     18     def forward(ctx, a):
---> 19         l = torch.potrf(a, False)
     20         ctx.save_for_backward(l)
     21         return l
```

**The error output is below:**

AttributeError: module 'torch' has no attribute 'potrf'

I could not find any solution for potrf. Do you have any suggestion to figure it out?

**Comment by zou3519** [comment]
We removed potrf in PyTorch 1.2: https://github.com/pytorch/pytorch/releases/tag/v1.2.0. Please use torch.cholesky instead

**Comment by aktaseren** [comment]
Thank you. It worked now.
