### ISSUE TITLE
torch.nn.DataParallel supporting unequal sizes

### ISSUE THREAD

**Issue by wenwei202** [pytorch/pytorch#5039]
As documented [here](http://pytorch.org/docs/master/_modules/torch/nn/parallel/data_parallel.html):
```
The batch size should be larger than the number of GPUs used. It should
    also be an integer multiple of the number of GPUs so that each chunk is the
    same size (so that each GPU processes the same number of samples).
```
To use `torch.nn.DataParallel`, people should carefully set the batch size according to the number of gpus they plan to use, otherwise it will pop up errors. 

This issue becomes more subtle when using `torch.utils.data.DataLoader` with `drop_last=False` by default. As the total number of training/validation samples varies with the dataset, the size of the last batch of data loaded by `torch.utils.data.DataLoader` is easy to become indivisible by the number of GPUs (e.g., 2,3,4,8,...).

A feature request would be:
supporting `torch.nn.DataParallel` with batch size indivisible by the number of GPUs used.

**Comment by Stonesjtu** [comment]
Actually setting an indivisible `batch size` works in my master branch, I recommend you to try it in your version. The document should clarify the ability to run with indivisible `batch size` anyway.

**Comment by wenwei202** [comment]
We may need to update docs if the code already supports that?
