### ISSUE TITLE
Give a better error when we run out of shared memory, instead of "RuntimeError: DataLoader worker (pid 13) is killed by signal: Bus error."

### ISSUE THREAD

**Issue by miraclewkf** [pytorch/pytorch#5040]
When I set `num_workers=1` or other value greater than 0 in `torch.utils.data.DataLoader`, I get this error.
The detail of the error:
``` 
Traceback (most recent call last):
  File "/opt/project/train.py", line 150, in <module>
    dataset_sizes=dataset_sizes)
  File "/opt/project/train.py", line 51, in train_model
    outputs = model(inputs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 64, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 75, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 68, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/cuda/comm.py", line 189, in scatter
    outputs.append(chunk.cuda(device, async=True))
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 172, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13) is killed by signal: Bus error.
```

**Comment by apaszke** [comment]
Are you sure you have enough shared memory in your system? Try running `df -h` and see how big in `/dev/shm`

**Comment by miraclewkf** [comment]
I run `df -h` and get:
```
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  347M  2.8G  11% /run
/dev/sdb2       427G  376G   29G  93% /
tmpfs            16G   72M   16G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sda        459G  376G   60G  87% /mnt/data
/dev/sdb1       511M  3.4M  508M   1% /boot/efi
tmpfs           3.2G   60K  3.2G   1% /run/user/1000
```

**Comment by SinghGauravKumar** [comment]
@miraclewkf @apaszke Same issue. Did you guys find any solution?

**Comment by fmassa** [comment]
@SinghGauravKumar you probably need to increase the amount of shared memory, as your DataLoader might be requiring more than what you have available for you specific task.

**Comment by Oktai15** [comment]
@fmassa @SinghGauravKumar @miraclewkf @apaszke 
I am positive that it happens when you use docker.
So, solution is here:
https://github.com/pytorch/pytorch/issues/2244

**Comment by prajjwal1** [comment]
How to set higher shared memory to avoid this?

**Comment by sachinruk** [comment]
Do `nvidia-docker run -d --shm-size 50G -p 8888:8888 -p 6006:6006 -v ${PWD}:/notebook -v ${PWD}/data/:/notebook/data sachinruk/pytorch_gpu`. Main point is --shm-size ...

If anyone is wondering when I checked `docker stats`, it was showing that there is 59G available memory and I was using only 1G or so. So seems that you have to explicitly set `--shm-size`.

**Comment by ferenc-acs** [comment]
Had the same error in a Google Cloud Tesla K80 instance. Solution was to simply leave the 'num_workers' parameter away!
`dataloader_train = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True) #, num_workers=2)`

**Comment by shardullavekar** [comment]
> @SinghGauravKumar you probably need to increase the amount of shared memory, as your DataLoader might be requiring more than what you have available for you specific task.

I tried that with the steps given in this link. 
https://www.lucidarme.me/increase-shared-memory-limit/

Doesn't work.

**Comment by shardullavekar** [comment]
I still can't get this working.

https://stackoverflow.com/questions/53449927/runtimeerror-dataloader-worker-is-killed-by-signal-illegal-instruction

Please take a look.

**Comment by shubchat** [comment]
Was anyone able to resolve this have been getting the same on GCP with 16 vcpus and 52 gb memory

**Comment by noypeban** [comment]
Me too on the kaggle kernel.
So we should wait here until someone resolve this problem.

**Comment by Redoykhan555** [comment]
One interesting thing I noticed while using Kaggle kernel (meaning docker) is that when I remove `transforms.Resize()` from transforms it works completely ok, with `num_workers>1` and everything. So I'm guessing PIL module's `Image.resize` is where the trouble lies.

**Comment by davidwagnerkc** [comment]
@ferenc-acs @shubchat
For those seeing the issue on Google Cloud VM instances this is how I increase the shared memory size so that the DataLoader can work with multiprocessing.

```
sudo umount /dev/shm/ && sudo mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=50G shm /dev/shm
```

Change `50G` to something below the amount of RAM on the machine. I do not think most of this command is necessary, I copied and pasted it from somewhere and haven't figured out if you really need all those options. Do a `df -h` before and after this command to see the shared memory resized.

**Comment by davidwagnerkc** [comment]
@Redoykhan555 
Interesting find. I have seen this issue on Kaggle notebooks too and will have to give that a try. I doubt that `PIL` module is the issue here though. What I imagine is happening is that without `resize()` you have enough shared memory to hold all the images, but when `resize()` is happening possibly there are copies of images made in shared memory so that the limit is exceeded and caused the crash. Not 100% sure on this. 

In terms of fixing this for Kaggle I don't think it is really a Pytorch issue, Kaggle will have to change the amount of shared memory available with their docker command. Not sure where the best place to contact them about this, but I'll try to see what their thoughts on that are.

**Comment by davidwagnerkc** [comment]
@jaideep11061982 
Google Colab seems to have responded to this issue here: https://github.com/googlecolab/colabtools/issues/329

Are you still seeing the issue?

**Comment by soulmachine** [comment]
I still have this error:

    RuntimeError: DataLoader worker (pid 29701) is killed by signal: Bus error.

**Comment by davidwagnerkc** [comment]
@soulmachine On Google Colab?

**Comment by pengfeidip** [comment]
I have the same problem...

**Comment by jaideep11061982** [comment]
> @jaideep11061982
> Google Colab seems to have responded to this issue here: [googlecolab/colabtools#329](https://github.com/googlecolab/colabtools/issues/329)
> 
> Are you still seeing the issue?

Thanks no... but in kaggle i do see. how can we avoid this issue in kaggle is there way to set sh meomory in kaggle

**Comment by davidwagnerkc** [comment]
No, unfortunately not. But looks like they are aware of the issue. 
https://www.kaggle.com/product-feedback/72606

Just recently I saw in this kernel that fastai 1.0 runs into this error, but not older versions.
https://www.kaggle.com/iafoss/similarity-resnext50-0-740-lb-kernel-time-limit

"This kernel is written with using fast.ai 0.7 since a newer version of fast.ai doesn't work well in kaggle: using more than one core for data loading leads to bus error "DataLoader worker (pid 137) is killed by signal: Bus error"."

**Comment by jac08h** [comment]
Using smaller batch size fixed the problem for me on Kaggle.

**Comment by awaelchli** [comment]
I get the same error message on my machine in PyTorch 1.0. Not using docker, colab or Kaggle.

**Comment by davidwagnerkc** [comment]
@awaelchli Increase the size of /dev/shm to accommodate for the increased memory requirements of running two experiments at once, that is if you have enough RAM to handle it. I posted a command to do this above in the thread.

**Comment by gdoteof** [comment]
Setting num_workers=0 worked for me on kaggle.

**Comment by young666** [comment]
> @soulmachine On Google Colab?

I am still having this issue on google colab, my shm size is 6GB

**Comment by toosi** [comment]
I have the same issue here. Not on cloud, or kaggle or google colab. I also have enough RAM, because this error only occurs when I am using a debugger in vscode. Without the debugger attached, it even works with num_workers = 10.

**Comment by ailzhang** [comment]
Hi, could anyone provide a minimal repro script? Or even minimal steps to repro on kaggle/colab will be helpful so that we could coordinate to get this resolved? Thanks!

**Comment by toosi** [comment]
**Ubuntu 18.04.2**
**torch.__version__**
'1.0.0'
**kwargs for DataLoader:**
kwargs = {'num_workers': 10, 'pin_memory': True} if device.type=='cuda' else {}

**Error**

E00001.458: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/contextlib.py", line 59, in __enter__
                return next(self.gen)
              File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
            

Traceback (most recent call last):

Traceback (most recent call last):
Error in atexit._run_exitfuncs:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):

Traceback (most recent call last):
  File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 391, in main
    run()
  File "/home/tahereh/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 272, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tahereh/Codes/Feedback/main_single_path.py", line 174, in <module>
    input_size = list(next(iter(train_loader))[0].shape[2:]) # e.g. MNIST [28, 28]
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 584, in __init__
    self._put_indices()
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 649, in _put_indices
    self.index_queues[self.worker_queue_idx].put((self.send_idx, indices))
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/multiprocessing/queues.py", line 87, in put
    self._start_thread()
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/multiprocessing/queues.py", line 169, in _start_thread
    self._thread.start()
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/threading.py", line 849, in start
    self._started.wait()
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
  File "/home/tahereh/anaconda3/envs/pytorch_tensorflow/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 68575) is killed by signal: Terminated.

**Comment by ezyang** [comment]
It should be easy to repro this if you manually set your shared memory very low.

It would be nice if we could give a better error message in this case. We could have the parent process check if you had a bus error and give a better error message. It would also be nice to have tested instructions for increasing shared memory in the variety of environments reported here.

@fmassa Why can't we pickle it and serialize it, like Numpy does? @soumith We're not going to change the semantics, and we're not going to have a global flag to toggle this behavior.

**Comment by rathisoft** [comment]
https://github.com/udacity/P1_Facial_Keypoints/issues/6 - I got it solved by following this.

Helped me for solving the IRIS dataset problem using pyTorch.

**Comment by artyompal** [comment]
This looks like a shared memory leak! It only happens for me after 12 epochs of training.

**Comment by artyompal** [comment]
This is how shared memory is consumed:
```$ while true; do df -h | grep sh; sleep 10; done
tmpfs                 24G   38M   24G   1% /dev/shm
tmpfs                 24G  630M   23G   3% /dev/shm
tmpfs                 24G  1.9G   22G   8% /dev/shm
tmpfs                 24G  3.8G   20G  16% /dev/shm
tmpfs                 24G  6.8G   17G  29% /dev/shm
tmpfs                 24G  8.7G   15G  37% /dev/shm
tmpfs                 24G   11G   13G  46% /dev/shm
tmpfs                 24G   14G   11G  58% /dev/shm
tmpfs                 24G   16G  7.8G  68% /dev/shm
tmpfs                 24G   18G  5.8G  76% /dev/shm
tmpfs                 24G   20G  3.8G  84% /dev/shm
tmpfs                 24G   23G  1.1G  96% /dev/shm
```

**Comment by gchanan** [comment]
@pbelevich to look at adding a better error message.

**Comment by zou3519** [comment]
I can trigger the error message via the following:

1. Save the following code into `mwe.py`:
```
import argparse
import torch
import torch.utils.data

def collate(tensor):
    import time
    time.sleep(999)

if __name__ == '__main__':
     parser = argparse.ArgumentParser(description='mwe')
     parser.add_argument('--num-workers', default=0, type=int)
     args = parser.parse_args()

     n = 100000
     data = torch.rand(n, 10)
     target = torch.rand(n)
     dataset = torch.utils.data.TensorDataset(data, target)
     data_loader = torch.utils.data.DataLoader(dataset,batch_size=2, num_workers=args.num_workers, collate_fn=collate)
     for i, batch in enumerate(data_loader):
         pass
```

2. Run `python mwe.py --num-workers=4`

3. Find `python mwe.py` using `ps aux | grep "python mwe.py"`.

4. Send sigbus via `kill -s SIGBUS <process_id>`

The resulting error message is:
```
(/scratch/rzou/pt/master-env) [0] rzou@devfair0317:~/dqn  $ python foo.py --num-workers=4
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/scratch/rzou/pt/master/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/scratch/rzou/pt/master-env/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/scratch/rzou/pt/master-env/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/scratch/rzou/pt/master-env/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/scratch/rzou/pt/master-env/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/scratch/rzou/pt/master-env/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/scratch/rzou/pt/master/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12419) is killed by signal: Bus error.
```

Although we already have a signal handler that has the error message, it is nice for it to be the last thing in the stack trace.

**Comment by aaxwaz** [comment]
Using smaller value for num_workers works for me!

**Comment by zhangruiskyline** [comment]
Hi, I got most people said reduce number of workers work here. but we want to have some full parallel data loader here, so I wonder how can we increase the shared memory in this case instead of reducing the number of workers?

**Comment by zhangruiskyline** [comment]
our error message looks like , searched around and got feedback on it is a multi worker out of memory, but I checked we have large shared memory, and even we just set worker to 2, it still has this issue. and strange thing is if we just parse JSON file and read line by line we don't have any problem, but if we add `json.loads(line)`, it will immediately report error. we are using pytorch nightly build

```
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/miniconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 480, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/home/miniconda/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/miniconda/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/miniconda/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/miniconda/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/miniconda/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/miniconda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 65, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 95106) is killed by signal: Segmentation fault.
```

**Comment by brando90** [comment]
> Are you sure you have enough shared memory in your system? Try running `df -h` and see how big in `/dev/shm`

Hi Adam,

is it possible to have a description that is more precise of what is causing the error to ease debugging? Is it caused my:
1) my code
2) my RAM
3) my gpu memory
4) filesystem memory

I find that if it's a recurring issue it's often useful to state the source of the problem to more effectively fix it.

**Comment by brando90** [comment]
https://discuss.pytorch.org/t/training-crashes-due-to-insufficient-shared-memory-shm-nn-dataparallel/26396/26
https://github.com/pytorch/pytorch/issues/5040

**Comment by ifsheldon** [comment]
When I run my code to test baselines on different models w.r.t to ImageNet ILSVRC2012, I encountered this error.
I used DataParallel to wrap pretrained models. And the dataloader is 
```python
baseline_imagenet_loader = torch.utils.data.DataLoader(baseline_imagenet_dataset,
                                              shuffle= False,
                                              batch_size = 2048,
                                              num_workers = 64, 
                                              prefetch_factor=16)
```
I requested 32 cores, 700GB memory and 8 V100 on my organization's HPC. And
```
(torch) [liangf@gpu208-18 train]$ cat /proc/sys/kernel/shmmax
18446744073692774399
```
It is a bit weird that after I changed `num_workers` to 32, everything went smoothly. I don't know whether it is somehow related to `num_workers`

**Comment by ahmedsnoun** [comment]
> @jaideep11061982
> Google Colab seems to have responded to this issue here: [googlecolab/colabtools#329](https://github.com/googlecolab/colabtools/issues/329)
> 
> Are you still seeing the issue?

Yes I still have this error on google colab, is there any solution out there?

**Comment by SoHardToMakeAName** [comment]
I got the same error......

**Comment by ahmedsnoun** [comment]
> Is there a solution to this issue. Although reducing the number of workers works, the training is very very slow. Is it somehow possible to increase the shared memory?

I solved this issue by using` torch.cuda.empty_cache()` in order to empty the unused memory after processing each batch and it worked like a charm.

**Comment by Sdhir** [comment]
Use this if you are still getting the error.
https://github.com/pytorch/pytorch/issues/2244#issuecomment-1194869994

**Comment by RobinGRAPIN** [comment]
I add my solution : in my case, I tried to write text using print() during the __getitem__() method of my dataset. For that, I launched my code using ```python train.py >> text_to_output.txt``` to catch the output of the prints. This led to the same error. I've been able to track the memory leak using ```while true; do df -h | grep sh; sleep 10; done```. The text to output is not flushed and was accumulated in memory, so after an important number of batches, the memory explodes. Add a flush or do not try to write on an output file this way :)

**Comment by AnxietyVendor** [comment]
> Had the same error in a Google Cloud Tesla K80 instance. Solution was to simply leave the 'num_workers' parameter away!
> `dataloader_train = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True) #, num_workers=2)`

dude, u r a genius

**Comment by 87royalts87** [comment]
Hello :)
I stumbled across this problem and I might have a solution.
Using the docker container: "**nvidia/cuda:11.1.1-devel-ubuntu20.04**" I needed to set the "**ipc: host**" in my docker compose file in order to being not restricted to the container shared memory.  
Hope this answer can be helpful :)

cheers

**Comment by Bea07** [comment]
> [@fmassa](https://github.com/fmassa) [@SinghGauravKumar](https://github.com/SinghGauravKumar) [@miraclewkf](https://github.com/miraclewkf) [@apaszke](https://github.com/apaszke) I am positive that it happens when you use docker. So, solution is here: [#2244](https://github.com/pytorch/pytorch/issues/2244)

you might also need to clean docker cache with `dockerd system prune` before
