### ISSUE TITLE
[doc template bug] fix bug of search.html

### ISSUE THREAD

**Issue by ain-soph** [pytorch/pytorch#50415]
## 📚 Documentation

Duplicate of https://github.com/pytorch/pytorch_sphinx_theme/pull/88. But it seems the maintainers haven't replied after 3 weeks, so I move it to the main pytorch repo.

The `search.html` in this repository is already out of date because of the Sphinx 3.4.0 update.  
In [issue 8419](https://github.com/sphinx-doc/sphinx/issues/8419) (with [pull request 8445](https://github.com/sphinx-doc/sphinx/pull/8445)), Sphinx 3.4.0 removes the default javascript loading of `language_data.js` and put it in `search.html`.  
Without the change of `search.html`, the searchbox will not work.

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
cc @brianjo
