### ISSUE TITLE
libATen compile fails with ld: symbol(s) not found for architecture x86_64 on macos 10.12

### ISSUE THREAD

**Issue by alvaromuir** [pytorch/pytorch#5042]
[ 92%] Linking CXX shared library libATen.dylib
ld: warning: directory not found for option '-L/Users/username/pytorch/torch/lib/tmp_install/lib'
Undefined symbols for architecture x86_64:
  "_cudnnSetConvolutionGroupCount", referenced from:
      at::native::ConvolutionDescriptor::set(cudnnDataType_t, int, int*, int*, int*, int) in Conv.cpp.o
  "_cudnnSetConvolutionMathType", referenced from:
      at::native::ConvolutionDescriptor::set(cudnnDataType_t, int, int*, int*, int*, int) in Conv.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

macos 10.12.6
pytorch 0.3 latest master
CUDA 9.0, CUDnn 7
GTX 1080
gcc: Apple LLVM version 8.0.0 (clang-800.0.42.1)

using recommended build command
```MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install```

building within a conda environment.

**Comment by apaszke** [comment]
cc: @ezyang. looks like we're missing guards for cuDNN 7 functions

**Comment by ezyang** [comment]
Here is the sole call site of `cudnnSetConvolutionGroupCount`:

```
struct ConvolutionDescriptor
  : public Descriptor<cudnnConvolutionStruct,
                      &cudnnCreateConvolutionDescriptor,
                      &cudnnDestroyConvolutionDescriptor>
{
  void set(cudnnDataType_t dataType, int dim, int* pad, int* stride, int * upscale /* aka dilation */, int groups) {
    cudnnDataType_t mathType = dataType;  
    if (dataType == CUDNN_DATA_HALF) mathType = CUDNN_DATA_FLOAT;
    CUDNN_CHECK(cudnnSetConvolutionNdDescriptor(mut_desc(), dim, pad, stride, upscale,
                                          CUDNN_CROSS_CORRELATION, mathType));
#if CUDNN_VERSION >= 7000
    CUDNN_CHECK(cudnnSetConvolutionGroupCount(mut_desc(), groups));
    CUDNN_CHECK(cudnnSetConvolutionMathType(mut_desc(), CUDNN_DEFAULT_MATH));
    if(dataType == CUDNN_DATA_HALF)
      CUDNN_CHECK(cudnnSetConvolutionMathType(mut_desc(), CUDNN_TENSOR_OP_MATH));
#endif
  }
};
```

7000 appears to be the correct version number, as per the changelog: http://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/Chunk531310909.html#rel_7

There is something fishy going on.

**Comment by ezyang** [comment]
@alvaromuir Do you have both cuDNN 6 and cuDNN 7 installed by any chance?

**Comment by alvaromuir** [comment]
I do. Should I remove older versions?

**Comment by carlosgmartin** [comment]
I'm having the same issue. `nvcc --version` yields `V9.1.128` and `cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2` yields
```
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
```

My error message is
```
[ 92%] Linking CXX shared library libATen.dylib
Undefined symbols for architecture x86_64:
  "_cudnnBatchNormalizationBackward", referenced from:
      at::native::cudnn_batch_norm_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, double) in BatchNorm.cpp.o
  "_cudnnBatchNormalizationForwardInference", referenced from:
      at::native::cudnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double) in BatchNorm.cpp.o
  "_cudnnBatchNormalizationForwardTraining", referenced from:
      at::native::cudnn_batch_norm(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, double) in BatchNorm.cpp.o
...
```
and so on.

**Comment by alvaromuir** [comment]
I cleaned my install, but now I'm having an error even finding the headers:

ld: library not found for -lcuda
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1

**Comment by carlosgmartin** [comment]
The error message went away after deleting an older cuDNN installation from `/usr/local/cuda/lib/libcudnn*`.  However, even though the setup now seems to finish without any fatal error, `torch.cuda.is_available()` still returns `False`.

**Comment by alvaromuir** [comment]
Ok, I got this going as well. Removing old cudNN versions was the trick, along with ensuring:
- $CMAKE_PREFIX_PATH pointed to my CONDA_ROOT (I'm using full anaconda for other reasons)
- $DYLD_LIBRARY_PATH started with ```/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib:/Developer/NVIDIA/CUDA-9.0/lib```
- in my ```/usr/local/cuda/lib``` removed ```libcudnn.5.dylib``` and ```libcudnn.5.dylib```

CUDA settings:
```#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)```
