### ISSUE TITLE
New VSX support breaks compilation if using g++ v7 (ppc64le)

### ISSUE THREAD

**Issue by dncliss** [pytorch/pytorch#50439]
## 🐛 Bug

The addition of VSX support in https://github.com/pytorch/pytorch/pull/41541 causes ppc64le pytorch builds to fail when using (e.g.) g++ version 7.4.
The reason for this is that there are some VEC builtins, e.g. `vec_neg`, `vec_signed`, `vec_sldw` that were new to g++ version 8.

When building with g++ 7.4, you see a number of errors of the form `error: 'vec_signed' was not declared in this scope` -- obviously a direct result of them not being present as built-ins in that version.  A compilation with 8.4 confirms this error is not seen.

## To Reproduce

Build pytorch (master) with the 7.4 g++ compiler; the failure will be seen when you reach file `aten/src/ATen/native/cpu/UpSampleMoreKernel.cpp.VSX.cpp`

## Expected behavior

The obvious answer is just to say "Well, build this with 8.4 then".  But there are better alternatives for expected behavior:
- The build should check the compiler version in use. Then, preferably, it should skip the VSX enhancement if the compiler is version <8 (perhaps with a warning).
- Less desirable (but better than current) would be to fail immediately at the outset upon finding the required compiler version isn't in use.
But surely, it would be nice to still be able to build successfully even if it means not enabling this new feature (it should be possible to conditionally exclude, e.g. it isn't built for x86).

## Environment

The only relevant environment info is ppc64le (power) platform and g++ less than version 8.

This was discovered building on the OSU lab image: osuosl/ubuntu-ppc64le-cuda:10.2-cudnn7
This image is the one used for CI builds, which started failing Dec 11 on Power; notice the
red "failing" status on the pytorch README github landing page.

cc @malfet @seemethere @walterddr

**Comment by dncliss** [comment]
FYI @quickwritereader

**Comment by malfet** [comment]
Hmm, it's pretty easy to gate the change based on compiler version, but I have no way of testing it. @dncliss can I ask you to validate the PR?

**Comment by quickwritereader** [comment]
I see. if those undefined ones are not so many, maybe we can define it
check aten/src/ATen/cpu/vec256/vsx/vsx_helpers.h there I defined vec_float
so the same can be done here.

**Comment by quickwritereader** [comment]
for example. I believe for vec_signed it should be sufficient defining them this way
[godbolt vec_signed)](https://godbolt.org/z/xKKzvG)

**Comment by quickwritereader** [comment]
here you can find equivalent intrinsics
http://cdn.openpowerfoundation.org/wp-content/uploads/resources/Intrinsics-Reference/content/VIPR.reference.vecfns.html.
I can check it myself only  next week

**Comment by dncliss** [comment]
> Hmm, it's pretty easy to gate the change based on compiler version, but I have no way of testing it. @dncliss can I ask you to validate the PR?

Sure; I can try out any proposed PR on a power system.  (Caveat is that I work only part-time, so turn-around might not not be as quick as desired).

**Comment by quickwritereader** [comment]
@dncliss could you try this, too? sorry for not coming with PR as I'm pretty overloaded these days

if there are some problems with the third-party Sleef, too, then we have to ask the Sleef author to support the desired compiler version as well.

You will add the below codes here [aten/src/ATen/cpu/vec256/vsx/vsx_helpers.h ](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec256/vsx/vsx_helpers.h#L21-L28)


```
#if !defined(vec_signed)

 vint32 vec_signed(const vfloat32& vec_in) {
  vint32 vec_out;
  __asm__("xvcvspsxws %x0,%x1" : "=wa"(vec_out) : "wf"(vec_in));
  return vec_out;
}

 vint64 vec_signed(const vfloat64& vec_in) {
  vint64 vec_out;
  __asm__("xvcvdpsxds %x0,%x1" : "=wa"(vec_out) : "wd"(vec_in));
  return vec_out;
}
#endif

#if !defined(vec_neg)
 vfloat32 vec_neg(const vfloat32& vec_in) {
  vfloat32 vec_out;
  __asm__("xvnegsp %x0,%x1" : "=wf"(vec_out) : "wf"(vec_in));
  return vec_out;
}

vfloat64 vec_neg(const vfloat64& vec_in) {
  vfloat64 vec_out;
  __asm__("xvnegdp %x0,%x1" : "=wd"(vec_out) : "wd"(vec_in));
  return vec_out;
}

inline vint16 vec_neg(const vint16& vec_in) {
  vint16 vint0={0,0,0,0 ,0,0,0,0};
  return vec_vsubuhm(vint0, vec_in) ;
}

vint32 vec_neg(const vint32& vec_in) {
  vint32 vint0={0,0,0,0};
  return vec_vsubuwm(vint0, vec_in) ;
}

vint64 vec_neg(const vint64& vec_in) {
  vint64 vint0={0,0};
  return vec_vsubudm(vint0, vec_in) ;
}

#endif

#if !defined(vec_sldw)
template<unsigned int C>
vfloat32 vec_sldw_inner(const vfloat32 &vec_in0, const vfloat32& vec_in1)
{
    vfloat32 vec_out;
    __asm("xxsldwi %x0, %x1, %x2, %3 "
        : "=wa" (vec_out) : "wa" (vec_in0), "wa" (vec_in1), "I" (C) 
       );
    return vec_out;
}
#define vec_sldw(a,b,c) vec_sldw_inner<c>(a,b)
#endif
```

https://godbolt.org/z/Kvv6bE

**Comment by malfet** [comment]
Converted above comment into PR, @dncliss please let me know if it works for you.

**Comment by dncliss** [comment]
@malfet Thank you; I appreciate your PR submission to address this (and my apologies for not getting a test response to you quicker).

I'd swapped the upstream nightly CI builds to use v8 compiler (avoiding the issue reported here, but with a later link issue), but I have now tried a build with your PR now included, using the v7 compiler. While the reported issue doesn't appear, a subsequent error related to this change does appear.  You can see a full execution of the build output at:  https://powerci.osuosl.org/job/pytorch-py3-test_gpu/63/console -- just search on `vec_signed` in that page.  The ultimate error is:
```In file included from [01m[K../aten/src/ATen/cpu/vec256/vsx/vec256_common_vsx.h:5:0[m[K,
                 from [01m[K../aten/src/ATen/cpu/vec256/vec256.h:19[m[K,
                 from [01m[Katen/src/ATen/native/cpu/FillKernel.cpp.VSX.cpp:3[m[K:
[01m[K../aten/src/ATen/cpu/vec256/vsx/vsx_helpers.h:[m[K In function ‘[01m[Kvint32 vec_signed(const vfloat32&)[m[K’:
[01m[K../aten/src/ATen/cpu/vec256/vsx/vsx_helpers.h:33:1:[m[K [01;31m[Kerror: [m[Kno return statement in function returning non-void [[01;31m[K-Werror=return-type[m[K]
```

With this issue here closed, should I open this as a new follow-up issue?

**Comment by dncliss** [comment]
FYI, incidentally:
Also noting that I changed the default nightly ppc64le CI builds to use v8, the build does get farther now but fails during linking and I think it's also VSX related due to the symbol name in the error. (The builds had been completing for several months before Dec 11).  The latest nightly build as of this writing is found at https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le-gpu/1044/  -- looking at the console output, I'm seeing a number of errors that look like:
```
/usr/bin/c++ -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_VSX_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -rdynamic -L/usr/lib -pthread caffe2/CMakeFiles/NamedTensor_test.dir/__/aten/src/ATen/test/NamedTensor_test.cpp.o -o bin/NamedTensor_test  -Wl,-rpath,/home/jenkins/pytorch/build/lib:/usr/local/cuda/lib64:  lib/libgtest_main.a  -Wl,--no-as-needed,"/home/jenkins/pytorch/build/lib/libtorch.so" -Wl,--as-needed  -Wl,--no-as-needed,"/home/jenkins/pytorch/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  -Wl,--no-as-needed,"/home/jenkins/pytorch/build/lib/libtorch_cuda.so" -Wl,--as-needed  lib/libc10_cuda.so  lib/libc10.so  /usr/local/cuda/lib64/libcudart.so  /usr/local/cuda/lib64/libnvToolsExt.so  /usr/local/cuda/lib64/libcufft.so  /usr/local/cuda/lib64/libcurand.so  /usr/local/cuda/lib64/libcublas.so  /usr/lib/powerpc64le-linux-gnu/libcudnn.so  lib/libgtest.a  -pthread && :
/home/jenkins/pytorch/build/lib/libtorch_cpu.so: undefined reference to `at::native::DispatchStub<std::tuple<at::Tensor, at::Tensor> (*)(at::Tensor const&, bool&), at::native::eig_stub>::VSX'
collect2: error: ld returned 1 exit status
```
This didn't appear until switching to v8 and thus getting past the original error reported in this issue -- so I suppose this could be opened as a separate issue too, but I'll see if I can understand it better first.

**Comment by dncliss** [comment]
To follow up on the prior comment above, the noted error about `vec_signed` returning non-void is a simple matter, as you can see in the attached PR that the inline in `vsx_helpers.h` is simply missing the `return vec_out;` at line 33.

But correcting this, there are still an assortment of errors (which you can also see fully in the aforementioned console output 2 comments back) reporting `invalid parameter combination for AltiVec intrinsic __builtin_vec_vmrgew` such as this one:

```
In file included from ../aten/src/ATen/cpu/vec256/vsx/vec256_common_vsx.h:14:0,
                 from ../aten/src/ATen/cpu/vec256/vec256.h:19,
                 from ../aten/src/ATen/native/cpu/Loops.h:35,
                 from aten/src/ATen/native/cpu/CopyKernel.cpp.VSX.cpp:6:
../aten/src/ATen/cpu/vec256/vsx/vec256_complex_float_vsx.h: In member function ?~@~Xat::vec256::{anonymous}::Vec256<c10::complex<float> > at::vec256::{anonymous}::Vec256<c10::complex<float> >::el_mergee() const?~@~Y:
../aten/src/ATen/cpu/vec256/vsx/vec256_complex_float_vsx.h:331:36: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_vmrgew
     return {vec_mergee(_vec0, _vec0), vec_mergee(_vec1, _vec1)};
                                    ^
../aten/src/ATen/cpu/vec256/vsx/vec256_complex_float_vsx.h:331:62: error: invalid parameter combination for AltiVec intrinsic __builtin_vec_vmrgew
     return {vec_mergee(_vec0, _vec0), vec_mergee(_vec1, _vec1)};
```

**Comment by malfet** [comment]
@dncliss can you please open a separate issue for the missing VSX symbol?
