### ISSUE TITLE
Some test modules are using unittest.main() instead of common_utils.run_tests()

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#50448]
## 🚀 Feature

Some test modules are using `unittest.main()` instead of `torch.testing._internal.common_utils.run_tests()`. Thus, the arg parser in `common_utils` are not running for these tests, which makes the whole test suite somewhat inconsistent.

https://github.com/pytorch/pytorch/blob/71766d89ea55bb8d4e180bac1c21bd95a00d54d5/torch/testing/_internal/common_utils.py#L149-L162

```
test_expecttest
test_mobile_optimizer
test_show_pickle
test_namedtuple_return_api 
test_jit_disabled 
test_overrides 
test_tensorexpr 
test_package 
```

We encountered this in a problem while running tests

```
python test/run_test.py --verbose -- --save-xml -v
```

`--save-xml` should be passed to each test module, but some test modules not using `common_utils.run_tests()` don't have these parser and will just throw an `error: unrecognized arguments: --save-xml`

cc @mruberry @VitalyFedyunin @walterddr @ptrblck

**Comment by mruberry** [comment]
cc @malfet

**Comment by walterddr** [comment]
looks like this is in fact the case. also in circle it doesn't actually show unrecognized arguments, instead it simply just missed the "Generating XML reports..." logs
