### ISSUE TITLE
Handling subclasses of Tensor in Parallel modules

### ISSUE THREAD

**Issue by YihanWang617** [pytorch/pytorch#50461]
## 🚀 Feature
Scatter and gather subclasses of Tensor in Parallel modules.

## Motivation

I am trying to use DataPrallel and DistributedDataParallel to run a model with extended Tensor. However I found that in the current implementation, the scatter function can only handle standard Tensor class.

## Pitch
Here is a small example, I defined a subclass named 'MyTensor' with two attribute 'lower' and 'upper'. However when I passed the 'MyTensor' object x through a DDP model using 'model(x)', I found that the model actually accepts a Tensor object instead of 'MyTensor' after scattering.

## Additional context

I looked through the related codes and I think the problem may be caused by the 'Scatter' function, which did not consider the case when accepting an object of Tensor subclasses.

`class Scatter(Function):

    @staticmethod
    def forward(ctx, target_gpus, chunk_sizes, dim, input):
        target_gpus = [_get_device_index(x, True) for x in target_gpus]
        ctx.dim = dim
        ctx.input_device = input.get_device() if input.device.type != "cpu" else -1
        streams = None
        if torch.cuda.is_available() and ctx.input_device == -1:
            # Perform CPU to GPU copies in a background stream
            streams = [_get_stream(device) for device in target_gpus]
        outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
        # Synchronize with the copy stream
        if streams is not None:
            for i, output in enumerate(outputs):
                with torch.cuda.device(target_gpus[i]):
                    main_stream = torch.cuda.current_stream()
                    main_stream.wait_stream(streams[i])
                    output.record_stream(main_stream)
        return outputs

    @staticmethod
    def backward(ctx, *grad_output):
        return None, None, None, Gather.apply(ctx.input_device, ctx.dim, *grad_output)
`

and also the `.to(device_id)` function

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
@YihanWang617 Scatter is intended to work with Tensor objects, I'd suggest using https://pytorch.org/docs/master/distributed.html#torch.distributed.scatter_object_list instead for your class.

**Comment by rohan-varma** [comment]
I guess that the API @pritamdamania87 mentioned would work to scatter the tensor subclass objects, although we can't really use this in DDP as DDP calls into scatter internally.

As of https://github.com/pytorch/pytorch/pull/44220, we now support scatter of NamedTuple types. If your only attributes are `lower` and `upper`, you could consider creating a named tuple type with these 2 attrs as tensors, and DDP should work with that.

**Comment by rohan-varma** [comment]
@YihanWang617 are you able to try the above suggestion if you get a chance? Thanks!

**Comment by YihanWang617** [comment]
> @YihanWang617 are you able to try the above suggestion if you get a chance? Thanks!

Thanks! I will try it.

**Comment by rohan-varma** [comment]
Closing as per above comment. @YihanWang617 please feel free to reopen if you have any issues
