### ISSUE TITLE
creating a dummy_input param for Pytorch model to Onnx conversion

### ISSUE THREAD

**Issue by BatMrE** [pytorch/pytorch#50463]
Ok so this might be a very simple and direct step, also tons of sample dummy_input are available. (I have tried almost all alternative)
My query is, how to know what should be the dummy_input(model input (or a tuple for multiple inputs)) for our model.
people pass it as

Variable(torch.randn(1, 3, 4, 4))
Variable(torch.randn(1, 3, 32, 32))
torch.randn(10, 3, 224, 224, device='cuda')
Variable(torch.randn(1, 3, 224, 224))
torch.rand(1000, 47, 300)
torch.randn(1, 3, 224, 224)
and so on..
now consider I am using a pretrained model, how will i know what will be my dummy_input i.e:
torch.randn(sample_batch_size, channel, height, width)
what should be my batch size for model, channel, width, height

below are the various error I am getting

code:

    model = BertModel.from_pretrained("/media/data1/abdul/bert-base-uncased")
    dummy_input = Variable(torch.randn(1, 3, 4, 4))
    torch.onnx.export(model, dummy_input,args.onnx_file, verbose=True) 
error:
ValueError: Wrong shape for input_ids (shape torch.Size([1, 3, 4, 4])) or attention_mask (shape torch.Size([1, 3, 4, 4]))

code:

    x = Variable(torch.randn(1, 3, 28, 28))
    torch.onnx.export(model,
                  x,
                  args.onnx_file,
                  input_names=['input_ids','attention_mask'],
                  output_names=[ "start_logits", "end_logits"],
                  dynamic_axes={ 'input_ids':[0,],'attention_mask':[0,],
                      'start_logits':[0,],'end_logits':[0,]},
                  do_constant_folding=True,
                   opset_version=11,
                  export_params=True)
error:
ValueError: Wrong shape for input_ids (shape torch.Size([1, 3, 28, 28])) or attention_mask (shape torch.Size([1, 3, 28, 28]))

code:

    train_inputs = torch.tensor([[0] * 30522])
    train_masks = torch.tensor([[0] * 768])
    torch.onnx.export(model,
                  (train_inputs, train_masks),
                  args.onnx_file,
                  input_names=['input_ids','attention_mask'],
                  output_names=[ "start_logits", "end_logits"],
                  dynamic_axes={ 'input_ids':[0,],'attention_mask':[0,],
                      'start_logits':[0,],'end_logits':[0,]},
                  do_constant_folding=True,
                   opset_version=11,
                  export_params=True)
error:
RuntimeError: The size of tensor a (30522) must match the size of tensor b (512) at non-singleton dimension 1

can some one please explain how should I do this conversion, where I am lagging

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment]
@BatMrE 
I'm unable to repro this exactly with your code, but I don't think this error is not from exporter.
Can you specify the source of this error?
Exporter does not specify the expected input shape.

**Comment by thiagocrepaldi** [comment]
Closing as it doesnt repro
