### ISSUE TITLE
Datasets in PyTorch's own server

### ISSUE THREAD

**Issue by GlebBrykin** [pytorch/pytorch#50472]
I suggest to place all supported by torchvision datasets on the server belonging to the community. This will solve a number of problems, including the removal of the dataset from open access and technical problems on a third-party resource where you have to download data. For example, at the moment ImageNet has disappeared from public access and now it can only be used by those who managed to download it.

cc @fmassa @vfdev-5

**Comment by mrshenli** [comment]
cc @fmassa 

adding "triage review" label to include this one in next meeting.

**Comment by vfdev-5** [comment]
Thanks for the suggestion @GlebBrykin ! Datasets redistribution is not a simple question. Currently, torchvision has the following disclaimer about that: https://github.com/pytorch/vision/#disclaimer-on-datasets

> We do not host or distribute these datasets, vouch for their quality or fairness, or claim that you have license to use the dataset.

**Comment by ezyang** [comment]
Yes, in general, most datasets are not licensed in such a way that we can actually legally redistribute them from our servers. Unfortunately, ImageNet is exactly one of these cases: http://image-net.org/download-faq

**Comment by mruberry** [comment]
While this would be convenient, unfortunately we don't think we can support a server with these datasets.
