### ISSUE TITLE
test_throw_unrecoverable_cuda_exception is reported as error in slow tests

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#50476]
See https://app.circleci.com/pipelines/github/pytorch/pytorch/259752/workflows/624711da-6213-4232-9417-a93767d25227/jobs/10128550

Not a big deal, but a bit misleading. We should prevent .xml report generation for such nested test

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
duplicate of #49901?

**Comment by malfet** [comment]
Yes, closing
