### ISSUE TITLE
No module named 'pybind11_tests' when running pytest

### ISSUE THREAD

**Issue by mstfbl** [pytorch/pytorch#50481]
## 🐛 Bug

When running `pytest`, the following exception occurs:

```
$ pytest
=============================== test session starts ================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/mubal/pytorch
plugins: hypothesis-6.0.0
collecting ... net_drawer will not run correctly. Please install the correct dependencies.
Failed to import pybind11_tests from pytest:
  ModuleNotFoundError: No module named 'pybind11_tests'
collected 0 items / 1 error                                                        

====================================== ERRORS ======================================
__________________________ ERROR collecting test session ___________________________
third_party/onnx/third_party/pybind11/tests/conftest.py:237: in _test_import_pybind11
    import pybind11_tests  # noqa: F401 imported but unused
E   ModuleNotFoundError: No module named 'pybind11_tests'

During handling of the above exception, another exception occurred:
../anaconda3/envs/torchSource/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../anaconda3/envs/torchSource/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
    exec(co, module.__dict__)
third_party/onnx/third_party/pybind11/tests/conftest.py:244: in <module>
    _test_import_pybind11()
third_party/onnx/third_party/pybind11/tests/conftest.py:241: in _test_import_pybind11
    sys.exit(1)
E   SystemExit: 1
================================= warnings summary =================================
../anaconda3/envs/torchSource/lib/python3.8/site-packages/past/builtins/misc.py:45
  /home/mubal/anaconda3/envs/torchSource/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import reload

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= short test summary info ==============================
ERROR  - SystemExit: 1
!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!
=========================== 1 warning, 1 error in 5.87s ============================
```

This is after a fresh building of PyTorch from source. I can run `pytest` just fine when running individual test files such as `pytest test/test_torch.py`, but when the file `third_party/onnx/third_party/pybind11/tests/conftest.p` is imported, the error above occurs.

I've also noticed that the `pybind11` in `third_party/pybind11` is `pybind11 @ a1cb7c2`, but is `pybind11 @ 80d4524` in `third_party/onnx/third_party/pybind11`.

## To Reproduce

1. Build PyTorch from source, either with `USE_CUDA=1` or `0`.
1. Run `pytest`.

## Expected behavior

I expect to be able to run all unit tests in PyTorch with `pytest`, as is noted in the documentation [here](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#unit-testing).

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 Collecting environment information...
PyTorch version: 1.8.0a0+a389b30
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1070
GPU 1: GeForce GTX 1070

Nvidia driver version: 440.100
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0
[pip3] torchvision==0.9.0a0+3ee34eb
[conda] blas                      1.0                         mkl
[conda] magma-cuda102             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.8.0a0                   dev_0    <develop>
[conda] torchvision               0.9.0a0+3ee34eb          pypi_0    pypi

## Additional context

I first noticed this issue when I was not able to run and debug into individual unit tests through VSCode's Test Explorer. This issue is also occurring for me on Windows, on a different setup. I also have `pybind` installed, so I don't believe this issue is unique to my case.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @mruberry @VitalyFedyunin @walterddr

**Comment by mstfbl** [comment]
The path of the file where this `pytest11_tests ModuleNotFoundError` is occurring is at `third_party/onnx/third_party/pybind11/tests/conftest.py`, which is obviously not the path one would want `pytest` to look for when asked to run default PyTorch unit tests.

After further investigation, I can discover all of PyTorch's unit test by modifying `python.testing.cwd` to point to the exact `pytorch/test` folder. However I am still interested in finding a fix for this issue, as it should be the case that running just `pytest` discovers and begins running all PyTorch unit tests.

**Comment by mruberry** [comment]
Thank you for filing this issue, @msftbl. I think we would accept a fix for this, although I'd like our pybind and ONNX experts to comment.

**Comment by AllenTiTaiWang** [comment]
Hi @mstfbl ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
