### ISSUE TITLE
rpc memory leak

### ISSUE THREAD

**Issue by liuyhlinux** [pytorch/pytorch#50522]
## 🐛 Bug

There are memory leak in rpc RREF client side.

## To Reproduce
```
#!/usr/bin/env python3
import argparse
import time
import torch.distributed.rpc as rpc
import torchvision


def get_image(path='Path to large image'):
    print('Remote get image: ' + path)
    return torchvision.io.read_image(path)


def run(args):
    if args.rank == 0:
        for i in range(1000000000):
            time.sleep(10)
    else:
        for i in range(1000000000):
            target_worker_name = 'worker_{}'.format(0)
            frames = rpc.rpc_sync(target_worker_name, get_image, args=())
            print(frames.size())



def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--backend', type=str, default='gloo', help='Name of the backend to use.')
    parser.add_argument('-i',
                        '--init-method',
                        type=str,
                        default='env://',
                        help='URL specifying how to initialize the package.')
    parser.add_argument('-s', '--world-size', type=int, default=2, help='Number of processes participating in the job.')
    parser.add_argument('-r', '--rank', type=int, default=0, help='Rank of the current process.')
    args = parser.parse_args()
    print(args)

    worker_name = 'worker_{}'.format(args.rank)
    rpc.init_rpc(worker_name,
                 rank=args.rank,
                 world_size=args.world_size,
                 rpc_backend_options=rpc.TensorPipeRpcBackendOptions(num_worker_threads=8,
                                                                     rpc_timeout=300))

    run(args)


if __name__ == '__main__':
    main()
```

    Run with: python test.py and python test.py -r 1 
              
   The rpc client's memory will keep growing.
## Expected behavior

Memory will not keep growing

## Environment

PyTorch version: 1.8.0a0+17f8c32
Is debug build: True
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @lw @beauby @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by pritamdamania87** [comment]
I'm able to reproduce this locally by replacing `get_image`, with this:

```
def get_image():
    return torch.rand(3, 224, 224)
```

**Comment by pritamdamania87** [comment]
Looks like this might be a memory leak in the TensorPipe backend, if I use ProcessGroupRpcBackendOptions there is no memory leak.

cc @mrshenli @lw

**Comment by mrshenli** [comment]
Does this leak also exist in v1.7.1 release?

**Comment by pritamdamania87** [comment]
@mrshenli The leak seems to be in all versions (1.6, 1.7, 1.7.1 and master)

**Comment by pritamdamania87** [comment]
Looks like the memory leak is happening due to the timeoutMap_: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/tensorpipe_agent.cpp#L727. We add an entry to timeoutMap_ on RPC send, but once we receive a response we never remove it from the map. The entire timeout duration needs to expire before we actually end up removing it from the map.

**Comment by liuyhlinux** [comment]
> Looks like this might be a memory leak in the TensorPipe backend, if I use ProcessGroupRpcBackendOptions there is no memory leak.
> 
> cc @mrshenli @lw

Use ProcessGroupRpcBackendOptions backend, the sender have memory lead.

**Comment by pritamdamania87** [comment]
@liuyhlinux Are you seeing the memory leak with ProcessGroupRPCBackendOptions too? When I tried this on PyTorch master, I didn't see any memory leaks. On which PyTorch version do you see the memory leak for ProcessGroupRPCBackendOptions?

**Comment by liuyhlinux** [comment]
> @liuyhlinux Are you seeing the memory leak with ProcessGroupRPCBackendOptions too? When I tried this on PyTorch master, I didn't see any memory leaks. On which PyTorch version do you see the memory leak for ProcessGroupRPCBackendOptions?

Thanks for your replay, I see memory on sender is gradually growwing to a certain value, no more increase.  May not be a memory leak， The version is: 1.8.0a0+17f8c32
