### ISSUE TITLE
[libtorch] Put tensor from CPU to GPU is VERY SLOW

### ISSUE THREAD

**Issue by xDooooot** [pytorch/pytorch#50529]
#### ENV
- Ubuntu 16.04
- MEM 16GB
- LibTorch 1.7.0 with CUDA 10.2
- GPU GTX 1080 Ti @ 12GB

#### Problem
I was building a detector demo with LibTorch, the problem encountered is that time consuming extremely high when put the tensor from CPU to GPU.

Code as follows,

**STYLE 1: Tensor operations kill about 90-100 ms**
```cpp
// define the device
torch::DeviceType device_type;
device_type = torch::kCUDA;
torch::Device device0(device_type, 1);
// read image
cv::Mat bgr;
bgr = cv::imread("/home/ubuntu/20190701_2_00000000.jpg", cv::IMREAD_COLOR);
cv::Mat img_float_1;
bgr.convertTo(img_float_1, CV_32F, 1.0);
cv::resize(img_float_1, img_float_1, cv::Size(480, 270));
{
  torch::NoGradGuard no_grad;
  for(int idx = 0; idx < 100; ++ idx) {
    // put data into a tensor
    auto input_tensor = torch::from_blob(img_float_1.data, { 1,270,480,3 });
    input_tensor = input_tensor.permute({ 0,3,1,2 });

    // convert tensor from CPU to GPU operation kills about 90-100 ms
    input_tensor = input_tensor.to(device0);

    // forward pass kills about 2 ms
    auto outputs = module.forward({input_tensor}).toTuple();
    auto out_cls = outputs->elements()[0].toTuple();
    auto out_bbox = outputs->elements()[1].toTuple();
  }
}
```

**STYLE 2: Tensor operations kill about 32 ms**
```cpp
// define the device
torch::DeviceType device_type;
device_type = torch::kCUDA;
torch::Device device0(device_type, 1);
// read image
cv::Mat bgr;
bgr = cv::imread("/home/ubuntu/20190701_2_00000000.jpg", cv::IMREAD_COLOR);
cv::Mat img_float_1;
bgr.convertTo(img_float_1, CV_32F, 1.0);
cv::resize(img_float_1, img_float_1, cv::Size(480, 270));

// define the tensor only one time
auto input_tensor = torch::from_blob(img_float_1.data, { 1,270,480,3 });
input_tensor = input_tensor.to(device0);

{
  torch::NoGradGuard no_grad;
  for(int idx = 0; idx < 100; ++ idx) {
    // tensor ops on gpu kill time about 0.024 ms
    input_tensor = input_tensor.permute({ 0,3,1,2 });

    // forward pass kills about 2 ms
    auto outputs = module.forward({input_tensor}).toTuple();
    auto out_cls = outputs->elements()[0].toTuple();
    auto out_bbox = outputs->elements()[1].toTuple();
    
    // feed the data into prev. tensor kills time about 32 ms
    input_tensor = torch::from_blob(img_float_1.data, { 1,270,480,3 }).to(device0);
  }
}
```

**Here comes the question, how to reduce the convert tensor from CPU to GPU operation time cost to a reasonable value ( <= 10ms )?**

**Any help will be welcome, thanks a lot.** 

cc @yf225 @glaringlee @ngimel @VitalyFedyunin

**Comment by ngimel** [comment]
How are you benchmarking the times? I suspect you don't do proper synchronizations, so the asynchronous `forward` call is timed at much faster than it really is, and synchronizing `to` call measures additional time.

**Comment by xDooooot** [comment]
> How are you benchmarking the times? I suspect you don't do proper synchronizations, so the asynchronous `forward` call is timed at much faster than it really is, and synchronizing `to` call measures additional time.

Thanks for your help. By setting `CUDA_LAUNCH_BLOCKING=1` environment variable I run the code in a synchronization way, the time cost is now at a reasonable value as follows,

**Put tensor from CPU to GPU:**  `about 0.25 ms`
**Forward time:** `about 35 ms`

This perfectly solved my problem, really appreciate that :)

**Comment by FantasyJXF** [comment]
@xDooooot  Hi,  how to ` run the code in a synchronization way`?

I met the same problem that tensors transfering between CPU and CUDA very slow.
