### ISSUE TITLE
Why are memory mappings not supported in default_collate?

### ISSUE THREAD

**Issue by safranchik** [pytorch/pytorch#50537]
Hello!

I am currently training multiple models in parallel, and each of them each uses a different ``DataLoader`` to access a dataset in shared memory. However, I noticed that the ``default_collate`` function does not parse ``np.memmap`` batches: ``np.memmap``'s ``__name__`` attribute is not ``ndarray``, and therefore ``default_collate`` throws a ``TypeError``.

This made me question whether parallelizing multiple PyTorch ``DataLoader``s on the same shared memory is good practice. Would you recommend wrapping the ``default_collate`` method to parse shared ``np.memmap`` batches, or giving each parallelized model/loader its own copy of the dataset?

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Hi @safranchik,
#39847 has landed to add support for `np.memmap`.
Could you please update your PyTorch to v1.7.1 to include this patch.

**Comment by safranchik** [comment]
Thank you!
