### ISSUE TITLE
Support for installing pytorch on microcontrollers.

### ISSUE THREAD

**Issue by ashwinpn** [pytorch/pytorch#50551]
It would be really great if PyTorch were compatible with microcontrollers like Arduino Uno, Raspberry Pi, or Intel Edison. This would sgnificantlyimprove any tasks involving autonomous bots / drones.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

For your question, it is already available. You can look for it on google to find how people did it depending on your platform. For example [here](https://gist.github.com/akaanirban/621e63237e63bb169126b537d7a1d979) for arduino.

**Comment by srohit0** [comment]
Here is the discussion of microcontrollers on pytorch forum to guide you how is it done.

https://discuss.pytorch.org/t/pytorch-on-microcontrollers/64662
