### ISSUE TITLE
Probabely bug with bachnorm2d - different behavior between two same networks in evaluation and training mode

### ISSUE THREAD

**Issue by mmderakhshani** [pytorch/pytorch#5060]
- OS: Ubuntu 16.04
- PyTorch version: pytorch-cpu               0.3.0           py36_cpuh7097a09_4
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)
- CUDA/cuDNN version: None
- GPU models and configuration: None
- GCC version (if compiling from source):

I have explained my problem completely [here](https://discuss.pytorch.org/t/bug-weird-behavior-between-evaluation-and-training-mode/13297/2). I don't know how to figure it out. Could you please help me?

**Comment by soumith** [comment]
we'll follow up on forums.
