### ISSUE TITLE
C++ API: `at::empty(size)` modifies `size` ArrayRef in-place when it owns the ArrayRef

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#50612]
## 🐛 Bug

There's a certain scenario when `t = at::empty(size)` will modify the passed-in `size` buffer in place. Specifically, I see it happen when `t` is the owner of the buffer (it gets set to 0).

## To Reproduce

```
auto t = at::empty({1,2,3});
auto size = t.sizes()
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
t = at::empty(size);
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
t = at::empty(size);
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
```
prints
```
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[0, 0, 0], size=[0, 0, 0]
```

## Expected behavior
I'd expect the second assignment operator not to modify the `size` buffer
```
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[1, 2, 3], size=[1, 2, 3]
```

## Environment

PyTorch version: 1.8.0a0+8c25b97 (current tip of master)
Is debug build: True (also happens with REL_WITH_DEB_INFO=1)
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: 9.0.0 (Red Hat 9.0.0-5.module_el8.1.0+288+74592915)
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0a0
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.8.0a0                   dev_0    <develop>
[conda] torchvision               0.8.1                    pypi_0    pypi

## Additional context

This seems like a degenerate case when you're re-assigning a tensor with the size buffer of the original tensor. For example, the following seems like it has the correct behavior.

```
auto t_temp = at::empty({1,2,3});
auto size = t_temp.sizes();
auto t = at::empty(size);
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
t = at::empty(size);
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
t = at::empty(size);
std::cout << "t.sizes()=" << t.sizes() << ", size=" << size << std::endl;
```
prints
```
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[1, 2, 3], size=[1, 2, 3]
t.sizes()=[1, 2, 3], size=[1, 2, 3]
```

I just stumbled across this while working on a different feature. This seems like a correctness issue, but in a pretty corner-case.

**Comment by bdhirsh** [comment]
Closing this issue- output from `t.sizes()` is `IntArrayRef` which is a reference type, so I shouldn't really have expected the above to work. Re-assigning the tensor shouldn't provide any guarantees about whether or not the reference returned from `t.sizes()` gets modified.

**Comment by swolchok** [comment]
In particular, the reference may not even be valid to dereference after assignment. I think ASAN should complain if, for example, you resize from dim() greater than 5 to, say, dim() 3.
