### ISSUE TITLE
Potential bug when sampling from categorical distribution

### ISSUE THREAD

**Issue by christinaheinze** [pytorch/pytorch#5062]
Hi,

I would like to sample from a categorical distribution where the probabilities passed are the columns of a tensor p_dG:

```
G = 3
D = 2
p_dG = torch.Tensor(G, D)
p_dG[:, 0] = torch.Tensor([0.1, 0.8, 0.1])
p_dG[:, 1] = torch.Tensor([0.1, 0.8, 0.1])

z_list = []
p_dg = p_dG[:, 0]
print(p_dg)
dis_Z = dis.Categorical(p_dg)
for _ in range(250):
    z = dis_Z.sample()
    z_list.append(z)

z = torch.cat(z_list, dim=0)

true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```

The output from `print(c)` is `[ 29  25 196]`. So the distribution is completely off since the bulk of the observations should be equal to 1 (instead of being equal to 2).

In contrast, the following code works as expected:
```
z_list = []
dis_Z = dis.Categorical(torch.Tensor([0.1, 0.8, 0.1]))
for _ in range(250):
    z = dis_Z.sample()
    z_list.append(z)

z = torch.cat(z_list, dim=0)
true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```

Is this a bug or am I missing something?

I am using:
- OS: macOS High Sierra
- PyTorch version: 0.3.0
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
- CUDA/cuDNN version: --
- GPU models and configuration: --
- GCC version (if compiling from source): --

Thanks!

**Comment by SsnL** [comment]
Yes this is a bug. Fortunately it seems to have been fixed on master. Thanks for reporting!

**Comment by soumith** [comment]
@christinaheinze you can follow instructions here to easily compile for master: https://github.com/pytorch/pytorch#from-source

**Comment by christinaheinze** [comment]
Ok, thanks!

**Comment by christinaheinze** [comment]
On master the issue has been solved for the categorial distribution but not for the multinomial distribution as it seems: 

```
import torch.distributions as dis
import torch
import numpy as np

G = 3
D = 2
p_dG = torch.Tensor(G, D)
p_dG[:, 0] = torch.Tensor([0.1, 0.8, 0.1])
p_dG[:, 1] = torch.Tensor([0.1, 0.8, 0.1])

p_dg = p_dG[:, 0]
z = p_dg.multinomial(250, replacement=True)
true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```
and also
```
z = torch.multinomial(p_dg, 250, replacement=True)
true_z_np = z.numpy()
v, c = np.unique(true_z_np, return_counts=True)
print(v)
print(c)
```

**Comment by SsnL** [comment]
I'll take a look at this tomorrow.

**Comment by alicanb** [comment]
Same problem is in `distributions.Multinomial` as well, even though it doesn't use `torch.multinomial` for sampling. I'll check that out

**Comment by SsnL** [comment]
@alicanb It's maintaining a `_categorical` object internally. So it's probably that.

**Comment by alicanb** [comment]
On second thought, what is the bug here?

**Comment by SsnL** [comment]
@alicanb It's CPU `torch.multinomial` not working on noncontiguous tensors. I'm writing a fix now.

**Comment by SsnL** [comment]
@alicanb Btw, do you know why `distributions.Multinomial` use a `distributions.Categorical` and a `scatter_add`, instead of just using `torch.multinomial`? What's it that I am missing here?

**Comment by alicanb** [comment]
`torch.multinomial` is misnomer actually, it's equivalent to `torch.distributions.Categorical(...).sample()`. I thought about correcting it, but it's too much of a breaking change. Here is the discussion https://github.com/probtorch/pytorch/issues/46

**Comment by alicanb** [comment]
@christinaheinze if you're trying to implement multinomial distribution btw, we have `distrributions.Multinomial(total_count, probs)` on master that behaves correctly
