### ISSUE TITLE
i am contributing for the first time

### ISSUE THREAD

**Issue by kmryashasvi** [pytorch/pytorch#50647]
> I am not able to understand different terms used while raising issues(even the good first issues) 
, but I seriously want to contribute to this repo, can you tell me where to start??

**Comment by ngimel** [comment]
Try going through documentation and tutorials to better understand the terms (pytorch.org/docs, pytorch.org/tutorials). Please use discuss.pytorch.org for questions.

**Comment by kmryashasvi** [comment]
Thank you @ngimel
