### ISSUE TITLE
How to maximize inference speed of models implemented with C++ API ? (not using torchscript or jit) 

### ISSUE THREAD

**Issue by w1d2s** [pytorch/pytorch#50657]
I'm currently implementing some seq2seq model with LibTorch C++ API (build from torch::nn::Modules, not using jit), is there any special techniques to optimize the inference speed ? Thanks.

cc @yf225 @glaringlee @VitalyFedyunin @ngimel @gmagogsfm

**Comment by gmagogsfm** [comment]
Is "not using jit" a requirement of this model? If not, we can introduce you to some works (static runtime, profiling executor or NNC) that can be of help.

**Comment by w1d2s** [comment]
> Is "not using jit" a requirement of this model? If not, we can introduce you to some works (static runtime, profiling executor or NNC) that can be of help.

Is "not using jit" a requirement of this model?
I'm afraid so, we tried jit before, but failed because of some restrictions of torch script (our model requires some fexibility, like complex control flows or optional inputs and so on, many of which hard to find a work around), so we decided to use libtorch c++ api as a high-level computation library, avoiding implementing another inference library from scratch.

And I want to know if there is any specific profiling tools for libtorch? (I can only think of some general profiling tools like gprof now)

**Comment by glaringlee** [comment]
@robieta Any profiling tools can be used on libtorch(c++) other than general ones? (like gprof)

**Comment by robieta** [comment]
I would recommend using the [PyTorch profiler](https://pytorch.org/tutorials/recipes/recipes/profiler.html) I don't think it has a C++ API (@ilia-cher correct me if I'm wrong), but you can always wrap your C++ model as a custom extension and call it under the profiler. (There is a [util](https://pytorch.org/docs/master/cpp_extension.html?highlight=cpp_extension%20load#torch.utils.cpp_extension.load) to make it easier, or you can compile it on your own.)

**Comment by w1d2s** [comment]
> I would recommend using the [PyTorch profiler](https://pytorch.org/tutorials/recipes/recipes/profiler.html) I don't think it has a C++ API (@ilia-cher correct me if I'm wrong), but you can always wrap your C++ model as a custom extension and call it under the profiler. (There is a [util](https://pytorch.org/docs/master/cpp_extension.html?highlight=cpp_extension%20load#torch.utils.cpp_extension.load) to make it easier, or you can compile it on your own.)

thank you, if I wrap my whole model (which consists of many torch::nn::Modules) in python, can Pytorch profiler analyze in operator granularity?

**Comment by robieta** [comment]
> > I would recommend using the [PyTorch profiler](https://pytorch.org/tutorials/recipes/recipes/profiler.html) I don't think it has a C++ API (@ilia-cher correct me if I'm wrong), but you can always wrap your C++ model as a custom extension and call it under the profiler. (There is a [util](https://pytorch.org/docs/master/cpp_extension.html?highlight=cpp_extension%20load#torch.utils.cpp_extension.load) to make it easier, or you can compile it on your own.)
> 
> thank you, if I wrap my whole model (which consists of many torch::nn::Modules) in python, can Pytorch profiler analyze in operator granularity?

Yes. The profiler is integrated with the dispatcher, so it "sees" operations irrespective of any higher level model organization.
