### ISSUE TITLE
Import Error after updating to 0.3

### ISSUE THREAD

**Issue by chao1224** [pytorch/pytorch#5066]
I tried to update pytorch from 0.2 to 0.3.

The update itself is fine, but when I run the codes, it raises this exception:

```
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/sliu426/anaconda2/lib/python2.7/site-packages/rdkit/Chem/../../../../././libicui18n.so.58)
```

And here is my code:
```
import torch
from rdkit import Chem
```

Considering I didn't change anything exception `pip install pytorch`, I guess the installation changes some paths. So I simply switch these two lines of codes and it works well for now:
```
from rdkit import Chem
import torch
```

The solution is a little tricky, and I'm wondering if there's a better one?

**Comment by zou3519** [comment]
Sorry for the lack of replies. PyTorch 0.3 is a pretty old version of PyTorch and we generally don't backport bug fixes. Please try a more recent version of PyTorch if you're still having this problem.
