### ISSUE TITLE
test_barrier_timeout_group intermittently fails on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#50662]
## 🐛 Bug

```pytb
Traceback (most recent call last):
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 300, in wrapper
    self._join_processes(fn)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 417, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\Users\circleci\project\build\win_tmp\build\torch\testing\_internal\common_distributed.py", line 453, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Processes 0 exited with error code 10
```
See https://app.circleci.com/pipelines/github/pytorch/pytorch/260867/workflows/37541fac-2608-4d2a-9e2f-6cbfba8775f6/jobs/10203733
https://app.circleci.com/pipelines/github/pytorch/pytorch/260662/workflows/4eaea13e-3bd6-44ef-9fef-3ee69800f75c/jobs/10192858
https://app.circleci.com/pipelines/github/pytorch/pytorch/260944/workflows/98e780c7-6312-4c1a-9f91-7d7a93b13494/jobs/10207917
https://app.circleci.com/pipelines/github/pytorch/pytorch/260662/workflows/4eaea13e-3bd6-44ef-9fef-3ee69800f75c/jobs/10192858
https://app.circleci.com/pipelines/github/pytorch/pytorch/260867/workflows/37541fac-2608-4d2a-9e2f-6cbfba8775f6/jobs/10203733

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mszhanyi** [comment]
All these failed link are on windows cpu. And the test machine has only 4 CPUs. From gut feeling, I think it looks like a resource issue.

**Comment by mszhanyi** [comment]
@peterjc123 @malfet @mrshenli I think it's caused by insufficient CPU resources. The test is for 4 CPUs training, but the test medium VM has only 4 CPUs. Could we enable xlarge VM for window CPU test2 for several days to see the effect? BTW, How can we see the statistics for the flaky tests.

**Comment by mszhanyi** [comment]
I've tested in xLarge windows VM

**Comment by mszhanyi** [comment]
I've tested in PR https://github.com/pytorch/pytorch/pull/50713

**Comment by malfet** [comment]
It doesn't look like test is doing anything but spawns several workers and waits for them to initialize.
And looks like all test have failed with:
```
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:2 (world_size=3, worker_count=1, timeout=0:00:01)
```
Two suggestions:
 - Would increasing timeout help (1 second to let 4 python processes spawn and initialize CUDA sounds a bit tight, especially on Windows platform)
 - Distributed error testing should be modified to include the actual failure reason rather than a mere: "Process exited with error code 10" (which simply mean "terminated with uncaught exception, isn't it?)
