### ISSUE TITLE
【libtorch】

### ISSUE THREAD

**Issue by wpeak58** [pytorch/pytorch#50673]
pytorch ,cpu inference very slowly,how about it ?

**Comment by wpeak58** [comment]
pytorch to libtorch,use cpu inference very slowly.

**Comment by wpeak58** [comment]
pytorch to libtorch,c++ use cpu inference very slowly.

**Comment by ngimel** [comment]
Please reopen with a clearer description.

**Comment by wpeak58** [comment]
When using C++ to load the pytorch model, why is the running speed very slow? After consulting the relevant knowledge, I found that the backend acceleration can be performed through Mkldnn. Is there any relevant case for reference.

**Comment by ngimel** [comment]
There is a bug template to submit issues, it has sections for the relevant information. In your question there's no actionable information for pytorch team to look at.
