### ISSUE TITLE
onnx trace and JIT broken where export works OK in pytorch1.6

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#50687]
Doing a single export on this line code:

```
fmap = fmap.squeeze(0)[index].squeeze(-1)
```

It will export as If, node, which is really weired

![image](https://user-images.githubusercontent.com/21303438/104912184-ec6e9980-59c6-11eb-9acc-2eb184b6089e.png)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @gmagogsfm

**Comment by jinfagang** [comment]
Specifically, all index function like [3] will export into a If node in ONNX

![image](https://user-images.githubusercontent.com/21303438/104912849-c695c480-59c7-11eb-8d53-fdf60a7d93fc.png)

Why should that happen? this node doesn't support in any other frameworks such as TensorRT

**Comment by daquexian** [comment]
Please use latest onnx-simplifier to simplify the onnx model. Latest onnxsim handles this case perfectly

**Comment by jinfagang** [comment]
@daquexian Thank u! Big lao! I will have a try

**Comment by shubhambhokare1** [comment]
I tried the repro provided on my end and I don't see the issue you are facing. If possible could you use the latest pytorch nightly to run this script.
