### ISSUE TITLE
Convert FPNInception to ONNX or TorchScript is not correct

### ISSUE THREAD

**Issue by SolicTous** [pytorch/pytorch#50685]
## 🐛 Bug

I have converted the FPNInception model with dynamic axes to ONNX, but the inference result was wrong comparing to PyTorch.
In Pytorch, model loading is divided into main weights file and feature extraction load in the model class (InceptionResNetv2).
Also, I've tried to prepare TorchScript and load it into C++, but the inference result was wrong too.

Opset versions 9, 12 were tried.

For Opset 13 - error:
`ValueError: Unsupported ONNX opset version: 13`

## Related issue
 in ONNX repo
https://github.com/onnx/onnx/issues/3208

## To Reproduce

1. Load model.module 
from https://github.com/VITA-Group/DeblurGANv2
       (I have chosen Jupyter Notebook)

2. Export Model to ONNX

```python
dummy_input = torch.randn(1, 3, 736, 1312, device='cpu', requires_grad=True)
inputs = ['input']
outputs = ['output']
dynamic_axes = {'input':{1:'height', 2:'width'},
                           'output':{1:'height', 2:'width'}}
torch.onnx.export(predictor.model.eval(), dummy_input, "FPNInception.onnx",
                             export_params=True, do_constant_folding=True,
                             input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes,
                             opset_version=12, verbose=False)
```

3. ONNX predict

```python
#summary_input is a copy input tensor with preprocessing from Predictor class
import onnxruntime
ort_session = onnxruntime.InferenceSession('data/'+n_model+'/'+n_model+'.onnx')
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
inputs = [node for node in ort_session.get_inputs()][0]
outputs = [node.name for node in ort_session.get_outputs()]
y_pred = predictor.model.eval()(*summary_input)
pred_onx = ort_session.run(outputs, {inputs.name: to_numpy(*summary_input)})
output = pred_onx [0]
```

3. Postprocessiong and plt.show()

```python
out = np.transpose(output[0,:,:,:], (1, 2, 0))
print(np.max(out), '   ', np.min(out))
out += 1
out = out / 2  * 255
out = out[:h,:w,:].astype('uint8')
out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)
plt.imshow(out)
plt.title('output')
plt.show()
```

## Expected behavior

The inference result image will be incorrect comparing to PyTorch.

## Environment

ONNX: 1.8.0

PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIopen runtime version: N/A

Versions of relevant libraries:

```
[pip3] numpy==1.19.4
[pip3] pytorch2keras==0.2.4
[pip3] torch==1.7.1+cu110
[pip3] torchaudio==0.7.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.2+cu110
[pip3] torchviz==0.0.1
[conda] blas                       1.0                         mkl  
[conda] cudatoolkit            11.0.221             h74a9793_0  
[conda] mkl                        2020.2                      256  
[conda] mkl-service            2.3.0            py38hb782905_0  
[conda] mkl_fft                   1.2.0            py38h45dec08_0  
[conda] mkl_random           1.1.1            py38h47e9c7a_0  
[conda] numpy                   1.19.4                   pypi_0    pypi
[conda] pytorch2keras        0.2.4                    pypi_0    pypi
[conda] torch                      1.7.0                    pypi_0    pypi
[conda] torchaudio             0.7.0                      py38    pytorch
[conda] torchsummary       1.5.1                    pypi_0    pypi
[conda] torchvision             0.8.2+cu110              pypi_0    pypi
[conda] torchviz                  0.0.1                    pypi_0    pypi
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @gmagogsfm

**Comment by spandantiwari** [comment]
@artvizi  - Could you clarify which ONNX backend are you using for evaluating your ONNX model? Also, did the export step happen without errors? Do you see anything obviously wrong with the ONNX exporter model?

**Comment by artvizi** [comment]
Step 3 was not correct - I have written about onnx_tf predict (latest 1.7.0).
(changed to onnxruntime predict)
on call
tf_rep = prepare(model, logging_level='DEBUG', auto_cast = True)
i see
2021-01-21 12:48:57,221 - onnx-tf - DEBUG - Unknown op ConstantFill in domain `ai.onnx`.
2021-01-21 12:48:57,222 - onnx-tf - DEBUG - Unknown op ImageScaler in domain `ai.onnx`.

onnx export without errors in code

But even onnxruntime (latest (1.6.0).
on call
pred_onx = ort_session.run(outputs, {inputs.name: to_numpy(*summary_input)})
image output is wrong

When I have opened onnx file from Netron I see "ConstantOfShape" nodes without any inputs. Now I'm not totally sure about structure in Onnx, for the reason, that the FPNInception model is hard for me, but I'm trying to understand it.

**Comment by spandantiwari** [comment]
Netron can hide the initializers that are going into a node, so maybe that's why some ConstantOfShape inputs are not visible. One way to check would be to click on the node and see the list of inputs on the pane that opens on the right side. 
If you see anything broken, can you please add a snapshot here.

**Comment by artvizi** [comment]
Yes, the input is hidden.
![Безымянный](https://user-images.githubusercontent.com/52211516/105667709-9f765000-5efd-11eb-8577-ea0f3bc332eb.jpg)

**Comment by timfu248** [comment]
> ## 🐛 Bug
> I have converted the FPNInception model with dynamic axes to ONNX, but the inference result was wrong comparing to PyTorch. In Pytorch, model loading is divided into main weights file and feature extraction load in the model class (InceptionResNetv2). Also, I've tried to prepare TorchScript and load it into C++, but the inference result was wrong too.
> 
> Opset versions 9, 12 were tried.
> 
> For Opset 13 - error: `ValueError: Unsupported ONNX opset version: 13`
> 
> ## Related issue
> in ONNX repo [onnx/onnx#3208](https://github.com/onnx/onnx/issues/3208)
> 
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Load model.module
>    from https://github.com/VITA-Group/DeblurGANv2
>    (I have chosen Jupyter Notebook)
> 2. Export Model to ONNX
>    dummy_input = torch.randn(1, 3, 736, 1312, device='cpu', requires_grad=True)
>    inputs = ['input']
>    outputs = ['output']
>    dynamic_axes = {'input':{1:'height', 2:'width'},
>    'output':{1:'height', 2:'width'}}
>    torch.onnx.export(predictor.model.eval(), dummy_input, "FPNInception.onnx",
>    export_params=True, do_constant_folding=True,
>    input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes,
>    opset_version=12, verbose=False)
> 3. ONNX predict
>    #summary_input is a copy input tensor with preprocessing from Predictor class
>    import onnxruntime
>    ort_session = onnxruntime.InferenceSession('data/'+n_model+'/'+n_model+'.onnx')
>    def to_numpy(tensor):
>    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()
>    inputs = [node for node in ort_session.get_inputs()][0]
>    outputs = [node.name for node in ort_session.get_outputs()]
>    y_pred = predictor.model.eval()(*summary_input)
>    pred_onx = ort_session.run(outputs, {inputs.name: to_numpy(*summary_input)})
>    output = pred_onx [0]
> 4. Postprocessiong and plt.show()
>    out = np.transpose(output[0,:,:,:], (1, 2, 0))
>    print(np.max(out), '   ', np.min(out))
>    out += 1
>    out = out / 2  * 255
>    out = out[:h,:w,:].astype('uint8')
>    out = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)
>    plt.imshow(out)
>    plt.title('output')
>    plt.show()
> 
> ## Expected behavior
> The inference result image will be incorrect comparing to PyTorch.
> 
> ## Environment
> ONNX: 1.8.0
> 
> PyTorch version: 1.7.1+cu110 Is debug build: False CUDA used to build PyTorch: 11.0 ROCM used to build PyTorch: N/A
> 
> OS: Microsoft Windows 10 Pro GCC version: Could not collect Clang version: Could not collect CMake version: version 3.19.1
> 
> Python version: 3.8 (64-bit runtime) Is CUDA available: True CUDA runtime version: Could not collect GPU models and configuration: Could not collect Nvidia driver version: Could not collect cuDNN version: Could not collect HIP runtime version: N/A MIopen runtime version: N/A
> 
> Versions of relevant libraries: [pip3] numpy==1.19.4 [pip3] pytorch2keras==0.2.4 [pip3] torch==1.7.1+cu110 [pip3] torchaudio==0.7.0 [pip3] torchsummary==1.5.1 [pip3] torchvision==0.8.2+cu110 [pip3] torchviz==0.0.1 [conda] blas 1.0 mkl [conda] cudatoolkit 11.0.221 h74a9793_0 [conda] mkl 2020.2 256 [conda] mkl-service 2.3.0 py38hb782905_0 [conda] mkl_fft 1.2.0 py38h45dec08_0 [conda] mkl_random 1.1.1 py38h47e9c7a_0 [conda] numpy 1.19.4 pypi_0 pypi [conda] pytorch2keras 0.2.4 pypi_0 pypi [conda] torch 1.7.0 pypi_0 pypi [conda] torchaudio 0.7.0 py38 pytorch [conda] torchsummary 1.5.1 pypi_0 pypi [conda] torchvision 0.8.2+cu110 pypi_0 pypi [conda] torchviz 0.0.1 pypi_0 pypi
> 
> cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @gmagogsfm

torch.onnx.export(predictor.model.eval(), dummy_input, "FPNInception.onnx",
training=TrainingMode.TRAINING,do_constant_folding=False,
input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes,
opset_version=12)

**Comment by justinchuby** [comment]
with opset=15,

```
File ~/dev/pytorch/torch/onnx/symbolic_opset9.py:1535, in instance_norm(g, input, weight, bias, running_mean, running_var, use_input_stats, momentum, eps, cudnn_enabled)
   [1533] if weight is None or sym_help._is_none(weight):
   [1534]     if channel_size is None:
-> [1535]         raise RuntimeError("Unsupported: ONNX export of instance_norm for unknown "
   [1536]                            "channel size.")
   [1537]     weight_value = torch.tensor([1.] * channel_size).type(
   [1538]         "torch." + input.type().scalarType() + "Tensor")
   [1539]     weight = g.op("Constant", value_t=weight_value)

RuntimeError: Unsupported: ONNX export of instance_norm for unknown channel size.
```

**Comment by justinchuby** [comment]
I don't quite recollect now. I may have downloaded the model repo.

**Comment by SolicTous** [comment]
@thiagocrepaldi I was need to do that one year ago, but now - not. Code was lost, but it's easy to reproduce if you will Load model.module from https://github.com/VITA-Group/DeblurGANv2 and just try to convert.

One thing that I understand, that it's not best idea to use Windows or Jypiter to convert Pth models to Onnx. And some other's was succesful on Linux.

**Comment by SolicTous** [comment]
.
