### ISSUE TITLE
Add support for sparse complex tensors

### ISSUE THREAD

**Issue by rjkilpatrick** [pytorch/pytorch#50690]
## 🚀 Feature

Currently, sparse tensors only support real floating point tensors. Complex support should be added for completion.

## Motivation

I'm trying to use complex tensors for compressed sensing and am running out of GPU memory (4GiB); even though my tensors are sparse (~1%) I cannot use optimized routines, since PyTorch does not currently support them. I have resorted to converting them to scipy sparse matrices and going without autograd.

## Pitch

`torch.sparse.CFloatTensor`, `torch.sparse.CDoubleTensor` added as complex extensions of existing real data types.

## Status

Complex support was added in this PR #57125  for CPU/CUDA. 

- [x]  complex support (torch.cfloat and torch.cdouble) to torch.sparse_coo_tensor constructors
- [x]  complex support to coalesce function
- [x]  complex support to to_dense function
- [x]  complex support to to_sparse function
- [x]  complex support to sparse_add function
- [x]  complex support to addmm function
- [x]  unit tests

Note: That PR contains only complex support for torch.sparse_coo_tensor *forward/backward* function and the related ops used with this function (coalesce, to_dense, to_sparse, and sparse_add, addmm). The following PRs should cover other sparse operations to have a more complex sparse support, specifically related with the use of specific APIs for accelerated linear algebra. 
    
CSR sparse tensor: ops not implemented yet: 
- [ ] transpose, complex conjugate, torch.pow, torch.exp, torch.block_diag, torch.diagflat,  torch.eye 
- [ ]  matmult ops: bmm, sparse@sparse
- [x] Add complex support for CSR Sparse Tensors

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa @nikitaved @pearu

**Comment by aocsa** [comment]
I would like to work on that,  adding `torch.sparse.CFloatTensor`, `torch.sparse.CDoubleTensor` constructors. 

IMO after that, we should create a list of sparse ops and prioritize which should have first complex tensors support as the main work here besides adding complex types to the type dispatcher is to use specific APIs from cuSPARSE and MKL. 

Let me know your thoughts. cc @ngimel, @rgommers, @pearu, @mruberry.

**Comment by anjali411** [comment]
@rjkilpatrick thanks for filing the issue! which sparse operations are most important for your purpose? I ask because it would help us in prioritization if we commit to add support for sparse complex tensors.

**Comment by rjkilpatrick** [comment]
The most important operations would just be (CUDA) accelerated linear algebra methods like add, multiply a matrix by a column/row, matrix by a matrix, etc.
Transpose, complex conjugate, `torch.pow`, `torch.sum`, `torch.exp`, and other methods currently allowed for sparse real tensors.

With then support for inherently sparse creation methods such as [`torch.block_diag`](https://pytorch.org/docs/stable/generated/torch.block_diag.html), [`torch.diagflat`](https://pytorch.org/docs/master/generated/torch.diagflat.html) (see #47640), `torch.eye` (perhaps speye instead of overloading return type?), but these are not specific to complex numbers.

**Comment by IvanYashchuk** [comment]
The important bit is to be able to construct a tensor with sparse representation and complex values, it's now possible. I'm going to close this issue because there's nothing specific for complex numbers when adding support of more mathematical operations on sparse tensors. If some existing operator is missing support for complex numbers a new separate issue should be created.

It’s possible to construct a tensor with the COO representation with any dtype of values:
```python
import torch
i = [[0, 1, 1],
     [2, 0, 2]]
v = torch.tensor([3, 4, 5])
for dtype in torch.testing.get_all_dtypes():
    s = torch.sparse_coo_tensor(i, v.to(dtype), (2, 3))
    assert s.dtype == dtype
```
The same hold for the CSR representation
```python
crow_indices = [0, 0, 1]
col_indices = [0,]
v = torch.tensor([3,])
for dtype in torch.testing.get_all_dtypes():
    s = torch.sparse_csr_tensor(crow_indices, col_indices, v.to(dtype), (2, 3))
    assert s.dtype == dtype
```

CSR matrix - dense matrix multiplication works with complex values:
```python
In [1]: import torch

In [2]: a = torch.randn(3, 3, dtype=torch.complex128)

In [3]: b = torch.randn(3, 3, dtype=torch.complex128)

In [4]: aa = a.to_sparse_csr()

In [5]: torch.mm(aa, b)
Out[5]:
tensor([[-0.1944+0.5019j,  1.9643+0.5262j,  0.0904+1.5411j],
        [ 0.2635-0.0348j, -1.2357-0.9245j, -0.3094-0.4119j],
        [ 0.3988+0.9200j, -0.5681-0.6806j, -1.6207-0.0074j]],
       dtype=torch.complex128)
```
