### ISSUE TITLE
LSTM output shape

### ISSUE THREAD

**Issue by TonyOrme** [pytorch/pytorch#50698]
I've been using the torch.nn.LSTM class and the "output" shape I see in my debug is different to that shown in the documentation. In the [LSTM documentation](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) the "output" shape is _(seq_len, batch, num_directions * hidden_size)_. However, in my debug code I can see the "output" shape is _(batch, seq_len, num_directions * hidden_size)_, that is, the batch and seq_len are reversed. Is the documentation correct?

**Comment by vadimkantorov** [comment]
Maybe output_shape also depends on `batch_first`?

**Comment by ngimel** [comment]
`output_shape` depends on `batch_firts`, hidden doesn't. This is a duplicate of #33215, closing as a duplicate.
