### ISSUE TITLE
Source distributions (sdist) are missing on PyPI

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#50697]
## 🐛 Bug

This may be on purpose, but I can't find any issue related to it. The very first releases (e.g. https://pypi.org/project/torch/0.1.2/#files) had only an sdist, but as soon as wheels were released the sdists went missing (see e.g. https://pypi.org/project/torch/1.7.1/#files, there's no `.tar.gz` source distribution). Normally it's a good idea to release sources, even for hard to build packages like PyTorch. An sdist serves as an archive and single source of truth for a release.

Also note that there *is* a `.tar.gz` file at https://github.com/pytorch/pytorch/releases/tag/v1.7.1, but that is an artifact that's auto-generated by GitHub, and is usually not identical to an sdist (one major difference: code for git submodules is not included, while you typically take care to bundle that in for an sdist).

I realize `python setup.py sdist` doesn't even work, so there may not be much interest in creating sdists for a release. But it's what's expected on PyPI and imho good archiving practice, so I thought I'd open an issue to at least document this as a deliberate choice.

cc @ezyang @seemethere @malfet @walterddr

**Comment by rgommers** [comment]
Not sure if the `releng` label is still a thing - Cc @malfet and @seemethere

**Comment by malfet** [comment]
Adding 1.8.0 milestone and grabbing for myself.

**Comment by ezyang** [comment]
IIRC it's on purpose to prevent people from accidentally attempting to build PyTorch from source when there aren't binaries available for their platform. cc @soumith

**Comment by soumith** [comment]
if we're going towards a better UX, whatever that UX is, I support.

**Comment by mattip** [comment]
> I realize python setup.py sdist doesn't even work

`setup.py sdist` works after gh-52908. Now a decision is needed whether to upload the source tarball to PyPI.

**Comment by rgommers** [comment]
> `setup.py sdist` works after [gh-52908](https://github.com/pytorch/pytorch/pull/52908). Now a decision is needed whether to upload the source tarball to PyPI.

I want to partially change my opinion here. Having a complete `sdist`, including the actual code in all git submodules, is a good thing. That's what gh-52908 achieved. The next step is: where to put them. I think putting them on PyPI will make the end user experience worse on balance, and we'll get many more complaints about install issues.

The safe and useful place to put them is on GitHub Releases. https://github.com/pytorch/pytorch/releases/tag/v1.9.0 now only has the autogenerated `Source code (zip)` and `Source code (.tar.gz)`. Those are not great, because they are not an sdist and do not include code from `third_party`. Uploading an `sdist` there is easy and safe; it will serve as the authoritative archive.

**Comment by seemethere** [comment]
> > `setup.py sdist` works after [gh-52908](https://github.com/pytorch/pytorch/pull/52908). Now a decision is needed whether to upload the source tarball to PyPI.
> 
> I want to partially change my opinion here. Having a complete `sdist`, including the actual code in all git submodules, is a good thing. That's what [gh-52908](https://github.com/pytorch/pytorch/pull/52908) achieved. The next step is: where to put them. I think putting them on PyPI will make the end user experience worse on balance, and we'll get many more complaints about install issues.
> 
> The safe and useful place to put them is on GitHub Releases. [`v1.9.0` (release)](https://github.com/pytorch/pytorch/releases/tag/v1.9.0) now only has the autogenerated `Source code (zip)` and `Source code (.tar.gz)`. Those are not great, because they are not an sdist and do not include code from `third_party`. Uploading an `sdist` there is easy and safe; it will serve as the authoritative archive.

I agree with this take, we should create automation to automatically upload the `sdist` packages to the github repository and add information on how to build it within the getting started page at `pytorch.org`

**Comment by malfet** [comment]
We are not publishing sdits to PyPI, but we do publish it to github releases, so closing this issue
