### ISSUE TITLE
【pytorch mkldnn】

### ISSUE THREAD

**Issue by wpeak58** [pytorch/pytorch#50707]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

When using C++ to load the pytorch model, why is the running speed very slow? After consulting the relevant knowledge, I found that the backend acceleration can be performed through Mkldnn. Is there any relevant case for reference.

**Comment by malfet** [comment]
Please file the issue with a bit more details

**Comment by wpeak58** [comment]
I want to use MKLDNN for accelerated reasoning on libtorch. Are there any relevant cases or what should I pay attention to?

**Comment by malfet** [comment]
@wpeak58 PyTorch is commonly compiled with mkldnn support
