### ISSUE TITLE
ReduceLROnPlateau doesn't have the get_last_lr()

### ISSUE THREAD

**Issue by Okkband** [pytorch/pytorch#50715]
## 🐛 Bug

ReduceLROnPlateau didn't inherit the _LRScheduler class. 
https://pytorch.org/docs/1.7.1/_modules/torch/optim/lr_scheduler.html#ReduceLROnPlateau

cc @vincentqb

**Comment by mruberry** [comment]
Thank you for reporting this issue, @Okkband.

**Comment by narain1** [comment]
would you like a PR for this issue?

**Comment by alabamagan** [comment]
I think this is still an issue
