### ISSUE TITLE
[WIP] Implementation of numpy-like corrcoef

### ISSUE THREAD

**Issue by PandaBoi** [pytorch/pytorch#50725]
## 🚀 Feature

Implementation of a function like [numpy.corrcoef](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html).
## Motivation

Related to #38349 

## Pitch

WIP PR #50466 

Steps for implementation:

- [ ] Implement `torch.cov` 
- [ ] Use `torch.cov` for building `torch.corrcoef`

## Additional context

- [ ] Add `weights` param to `torch.mean` and aliasing `torch.average` to `torch.mean`.

@mruberry @rgommers 

cc @mruberry @rgommers @heitorschueroff

**Comment by rgommers** [comment]
> Add `weights` param to `torch.mean` and aliasing `torch.average` to `torch.mean`.

Note that this is going to make `torch.mean` less compatible with `numpy.mean`, which doesn't have a `weights` keyword. They're not aliases unfortunately - see https://github.com/numpy/numpy/issues/8864 for a discussion.

I think there are two reasonable choices here:
1. Just copy whatever NumPy does
2. Adding weights for all statistical functions at once in a uniform way.

**Comment by mruberry** [comment]
[Offline discussion w/@rgommers] Hey @PandaBoi, the mean vs. average thing is a little tricky. What about implementing torch.cov without a call to mean or average? It seems like average can just be implemented as:

```
(weights * self).mean()
```

And then we can skip those steps and move straight to implementing torch.cov. Sound good?

**Comment by PandaBoi** [comment]
@mruberry yup sounds like a reasonable thing to do, will go ahead with that.

**Comment by heitorschueroff** [comment]
Closing this issue to keep all discussion in https://github.com/pytorch/pytorch/issues/1254. `torch.cov` is being added here https://github.com/pytorch/pytorch/pull/58311.
