### ISSUE TITLE
[feature request]  ‘floordiv’ operator in pytorch

### ISSUE THREAD

**Issue by shubham-goel** [pytorch/pytorch#5072]
Pytorch Tensors are missing a ‘floordiv’ operator, is this intentional? With some direction, I'd be happy to implement this and send a pull request.

I considered adding `def __floordiv__(self, other)` to [torch/tensor.py](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L293) but I think the `floor()` function isn't available in `_TensorBase`.

PS: I'm trying to write code that works on both NumPy Arrays and Pytorch Tensors.
Eaxmple:
```
a = b//c              # (works with numpy, not pytorch)
a = (b/c).floor()     # (works with pytorch, not numpy)
```

**Comment by bryant1410** [comment]
This is fixed, right?

**Comment by shubham-goel** [comment]
Yes. Can now use `.floor()` .

**Comment by NielsRogge** [comment]
You mean [`.floor_divide()`](https://pytorch.org/docs/stable/generated/torch.floor_divide.html#torch.floor_divide), right?
