### ISSUE TITLE
Output of quantized.functional.conv2d is wrong

### ISSUE THREAD

**Issue by volcacius** [pytorch/pytorch#50720]
## 🐛 Bug

Unless I'm missing something, the output of torch.nn.quantized.functional.conv2d is often wrong by a large margin (much more than I would expect from numerical differences caused by different backends). 
Minimal example below comparing against torch.functional.conv2d on the dequantized input and weights followed by a requantization.

## To Reproduce

```python
inp = tensor(
    [[[[-0.3096,  0.3871, -0.8741, -1.2659, -0.0505],
       [-0.1814,  0.6141,  0.7843,  1.1278, -0.4891],
       [ 2.4613, -0.7179, -0.2446,  0.6929, -0.3115],
       [ 0.8652, -0.6757,  1.9093, -0.5734,  0.3151],
       [ 0.7885,  0.0279,  0.3433, -0.2992,  1.0210]]]])
weight = torch.linspace(-1.0, 1.0, 9).view(1, 1, 3, 3)
inp = torch.quantize_per_tensor(inp, scale=0.15, zero_point=120, dtype=torch.quint8)
weight = torch.quantize_per_tensor(weight, 0.0007, zero_point=0, dtype=torch.qint8)
qf_out = torch.nn.quantized.functional.conv2d(inp, weight, scale=0.0009, zero_point=121, bias=None, dtype=torch.quint8)
ref_out = torch.nn.functional.conv2d(inp.dequantize().cpu(), weight.dequantize().cpu(), bias=None)
ref_out = torch.quantize_per_tensor(ref_out, scale=0.0009, zero_point=121, dtype=torch.quint8)
print(qf_out.int_repr() - ref_out.int_repr())
```

Prints:
```python
tensor([[[[ 0,  0,  0],
          [15,  0,  0],
          [ 0,  0,  0]]]], dtype=torch.uint8)
```

## Expected behavior

I would expect the difference between the two tensors to be ideally all 0s, at most off by 1 or 2.

## Environment

```
# python collect_env.py
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (Rev2, Built by MSYS2 project) 9.2.0
Clang version: 10.0.0
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce 940MX
Nvidia driver version: 441.87
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorchcv==0.0.58
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38h196d8e1_0
[conda] mkl_fft                   1.2.0            py38h45dec08_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] pytorch                   1.7.1               py3.8_cpu_0  [cpuonly]  pytorch
[conda] pytorchcv                 0.0.58                   pypi_0    pypi
[conda] torchvision               0.8.2                  py38_cpu  [cpuonly]  pytorch
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by volcacius** [comment]
I see a similar issue with torch.nn.quantized.functional.linear:

```python
inp = tensor(
    [[-1.1218, -1.8445, 1.0258, 2.1921],
     [-1.4322, 1.5293, 1.2118, 0.0423],
     [0.3807, 0.0538, 0.5047, -0.4987],
     [-0.4891, 0.0578, 0.9436, 0.9775]])
weight = tensor(
    [[-0.0047, -0.0042, -0.0057, -0.0080],
     [-0.0032, 0.0005, -0.0042, 0.0093],
     [-0.0013, -0.0040, -0.0099, -0.0027],
     [0.0089, -0.0031, 0.0037, 0.0070],
     [-0.0070, -0.0065, 0.0062, 0.0049]])
inp = torch.quantize_per_tensor(inp, scale=0.0158, zero_point=117, dtype=torch.quint8)
weight = torch.quantize_per_tensor(weight, scale=0.000078, zero_point=0, dtype=torch.qint8)
qf_out = torch.nn.quantized.functional.linear(inp, weight, scale=0.00021, zero_point=79, bias=None)
ref_out = torch.nn.functional.linear(inp.dequantize().cpu(), weight.dequantize().cpu(), bias=None)
ref_out = torch.quantize_per_tensor(ref_out, scale=0.00021, zero_point=79, dtype=torch.quint8)
print(qf_out.int_repr() - ref_out.int_repr())
```

Prints:
```python
tensor([[40,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]], dtype=torch.uint8)
```

**Comment by jerryzh168** [comment]
I remember fbgemm/qnnpack has some off by one error, cc @dskhudia @kimishpatel can you comment?

**Comment by volcacius** [comment]
Fwiw the error I reported above with linear is off by 40 on a 4x4x5 gemm, it looks more like an overflow issue to me than an off by one error.

**Comment by kimishpatel** [comment]
I am assuming this is on x86 machine? We are likely going through fbgemm in that case. Note that on fbgemm weight quantization requires reduced range, meaning quantized values must fit within -64, 63 using 7 bits, instead -128, 127. I am not sure if that is happening here. @dskhudia knows more about it.

**Comment by volcacius** [comment]
Yes this is on Intel x86. It would be really useful if whatever restrictions apply were documented somewhere in pytorch land, or made more explicit at the datatype level (quint8 doesn't seem appropriate to me if the value is actually quint7).

**Comment by kimishpatel** [comment]
> Yes this is on Intel x86. It would be really useful if whatever restrictions apply were documented somewhere in pytorch land, or made more explicit at the datatype level (quint8 doesn't seem appropriate to me if the value is actually quint7).

100% agree on documentation. At the least we can throw warning.

**Comment by volcacius** [comment]
Another thing, I haven't been able to reproduce the problems reported above consistently across machines, so there might something going in terms of whichever extension-dependent implementation is actually executed. The results reported are on a i7-7820HQ.

**Comment by dskhudia** [comment]
Hi @volcacius,

There might be saturation in internal accumulators for quantized operators. This saturation is explained here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cpu/qconv.cpp#L778-L806 

In PyTorch, this is remedied by using only 7-bits (i.e., restricting activation values between 0 - 127) but the data type is still qint8. reduce_range option (https://github.com/pytorch/pytorch/blob/44c17b28c693c044daea169426c8e111e1e148fc/torch/quantization/qconfig.py#L88) is used to select scale/zero_point such that quantized values stay in the desired range. It's by default on so you don't run into these issues while following the quantization flow.

**Comment by volcacius** [comment]
Hi @dskhudia,

Thanks for the pointers. I maintain a standalone quantization-aware training library called Brevitas that implements its own flow, but I was looking into integration with the quantized functional operators for inference at 8-bit. 
I'll change the bit-width to 7 in my library then, but I think it would be really useful if this behavior was documented here too https://pytorch.org/docs/stable/torch.nn.quantized.html as it's really not obvious what's going on otherwise. It could also make sense to at least raise a warning on a 8-bit zero-point that is as passed as part of the input to one of the affected operators.

**Comment by supriyar** [comment]
This is documented in https://pytorch.org/docs/stable/quantization.html under Best Practices.
