### ISSUE TITLE
view function error at runtime on gpu

### ISSUE THREAD

**Issue by wham-bam** [pytorch/pytorch#5073]
Hi all

I have a problem with a sequence to sequence model  with attention that I had created.
The model computes attention doing the following passes:

if self.use_coverage:
     pre_attention = enc_features + dec_features + coverage_features
else:
     pre_attention = enc_features + dec_features
pre_attention = F.tanh(pre_attention)
attention = self.v(pre_attention)
reshaped_attention = attention.view(-1, self.seq_len)
attention = F.softmax(reshaped_attention, dim=1)

However, this error arise after the model has done 190000 steps (forward+backward):

2018-02-06 02:24:21,836 - INFO - forward step ran in 0m 0s 454ms
2018-02-06 02:24:22,042 - INFO - step 192637 loss: 374.437866
2018-02-06 02:24:22,042 - INFO - running backward step
2018-02-06 02:24:23,390 - INFO - backward ran in 0m 1s 347ms
2018-02-06 02:24:23,391 - INFO - running forward step...

File "/scratch/home/gsiragus/s2s-coverage/attention.py", line 85, in forward
    reshaped_attention = attention.view(-1, self.seq_len)
RuntimeError: invalid argument 2: size '[-1 x 400]' is invalid for input with 6304 elements at /pytorch/torch/lib/TH/THStorage.c:37

Does someone know why this exception is thrown?

Thanks!

Other info:

- OS: ubuntu 16.10
- PyTorch version: last one
- How you installed PyTorch: pip
- Python version: 3.5
- CUDA/cuDNN version: 9
- GPU models: K40m

**Comment by albanD** [comment]
Pleas use the [forum](https://discuss.pytorch.org/) to ask questions.

In your case, the error message should be clear: `in 'view()': size '[-1 x 400]' is invalid for input with 6304 elements`. Since you have 6304 elements in the input, your can't view it as something by 400.

**Comment by wham-bam** [comment]
Ok ,but the model computed that part of code for 192637 steps (forward passes), giving error in the 192638 step (forward pass). In my opinion, that error should be thrown at the first forward pass, not after ~190,000. It seems a big issue to me.

**Comment by apaszke** [comment]
It’s probavly an error in your code (e.g. you used drop_last=False in the data loader but your model can’t work with smaller batches). If you have a smaller, self-contained snippet that would let us reproduce what you think is a bug then please post it here and reopen the issue.
