### ISSUE TITLE
Don't run git when PYTORCH_BUILD_VERSION is set

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#50730]
## 🐛 Bug

During the build `git` is run and will fail when PyTorch is installed from a non-git source tree

However as the value set in the env var `PYTORCH_BUILD_VERSION` takes precedence this is not even required.

## To Reproduce

1. Download PyTorch sources from e.g. Github
1. Extract
1. Install according to instructions

## Expected behavior

No error shown but a confusing `fatal: not a git repository (or any parent up to mount point /)` is

## Additional context

I suggest to remove the call at https://github.com/pytorch/pytorch/blob/f7a8bfd0a15b3c3a07f92157b45869bcc33c9d74/tools/generate_torch_version.py#L43 which is fully superflous
I'd also suggest to move https://github.com/pytorch/pytorch/blob/f7a8bfd0a15b3c3a07f92157b45869bcc33c9d74/tools/generate_torch_version.py#L16-L17 into the else branch at https://github.com/pytorch/pytorch/blob/f7a8bfd0a15b3c3a07f92157b45869bcc33c9d74/tools/generate_torch_version.py#L25-L26 so `git` is only run when `PYTORCH_BUILD_VERSION` is not set

cc @malfet @seemethere @walterddr

**Comment by seemethere** [comment]
I agree that we should do this.

What’s weird is that the actual code doesn’t actually end up getting used in the build / release process so maybe it’d be better to just remove it and replace it with what we end up doing in the actual build scripts which is just appending the date plus `.dev` to the end of the builds.

**Comment by Flamefire** [comment]
Can you elaborate? Do you only refer to the sha-issue itself or versioning in general?

For context: We are working with EasyBuild for automatically installing (among others) PyTorch on HPC systems worldwide.
What we basically do is download the tagged source code from github and its dependencies and install from there setting PYTORCH_BUILD_VERSION to the correct version.
So either (at least) the tagged versions source code contains a hard-coded version (as done by most other projects) or there is a possibility to overwrite it. 

Not sure how the release process of PyTorch works but please keep that in mind when changing something there. I'd suggest to keep the PYTORCH_BUILD_VERSION (and friends) override as I expect e.g. package maintainers of Linux distros to use a similar approach.

**Comment by seemethere** [comment]
I think versioning in general should probably follow what we're doing in the downstream build process more closely since it's sometimes a pain to actually know where the final build version is actually coming from.

Definitely not a decision to be made in this issue but something I thought about when reading about this.

In any case I've created a PR to remedy this here: https://github.com/pytorch/pytorch/pull/50773

**Comment by Flamefire** [comment]
@seemethere Can this be reopened please? The issue is not fixed as `git` is still run during the build because the py-script is executed by CMake and that runs `git` as mentioned and referenced at this OP: See https://github.com/pytorch/pytorch/blob/f7a8bfd0a15b3c3a07f92157b45869bcc33c9d74/tools/generate_torch_version.py#L43

And the CMake code: https://github.com/pytorch/pytorch/blob/439afda090a343e90aa87678a0019c0dc26880cc/torch/CMakeLists.txt#L302-L310

I mentioned the 2 issues with the PR in #50773, but that seems to have been missed.
