### ISSUE TITLE
`test_inplace_grad` and `test_variant_consistency_eager` have to be disabled while testing broadcasting semantics in `OpInfo` based tests

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#50747]
As per title. see https://github.com/pytorch/pytorch/pull/50667

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
We should definitely fix this. Maybe there's a check that can be added to the inplace checks to avoid this issue?

**Comment by kshitij12345** [comment]
Have verified locally that the following works for `masked_scatter` and `masked_fill` where first input needs to be broadcasted.

Add a field in `OpInfo` to set broadcasts input (this is optional)

```python
# Ensure that inplace variant raises error where first input `self` needs to be broadcasted
# Assumes that first_input in the sample.input is `self` incase of inplace variant.
if op.broadcasts_input and sample.input[0].shape != expected_forward.shape and variant in inplace_ops:
    with self.assertRaises(RuntimeError):
        variant(*(clone_input_helper(input) if variant in inplace_ops else input
                    for input in sample.input),
                *sample.args,
                **sample.kwargs)
else:
    # Compares variant's forward
    # Note: copy the tensor-type inputs when testing inplace operation
    variant_forward = variant(*(clone_input_helper(input) if variant in inplace_ops else input
                                for input in sample.input),
                            *sample.args,
                            **sample.kwargs)
    self.assertEqual(variant_forward, expected_forward)
```

Let me know how you feel about something like this.
@anjali411 @mruberry

**Comment by mruberry** [comment]
Another option might be to support a "inplace" kwarg on sample inputs that only returns inputs suitable for using with inplace operations. That might be less invasive and more general.

**Comment by kshitij12345** [comment]
Please have a look at https://github.com/pytorch/pytorch/pull/53014, it adds a new field to `SampleInput` to notify if `self` gets broadcasted or not.
