### ISSUE TITLE
Need a strategy for dealing with nondeterminism due to multiple writes to one memory location

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#50750]
Some operations can be called such that multiple different values are written to the same memory location. In many of these situations, results are not guaranteed to be deterministic. Furthermore, behavior of CUDA vs CPU could be different.

A few applicable examples:

`embedding_bag` - In the following example, bag 0 and bag 2 are mapped to the same output offset:
```
>>> weights = torch.randn(3, 3)
>>> weights
tensor([[ 0.0767,  1.4228, -0.6826],
        [-1.3086, -1.5685,  0.2942],
        [ 1.5062, -1.0844, -1.9833]])
>>> torch.nn.functional.embedding_bag(weights, torch.tensor([0, 1, 2]), torch.tensor([0, 1, 0]), mode='max')
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0767,  1.4228, -0.6826],
        [ 1.5062, -1.0844,  0.2942]])
```

`index_put_` - In the following example, all 3 values from the input are mapped to index 0 of the output.
```
>>> indices = torch.tensor([0, 0, 0])
>>> input = torch.tensor([1., 2., 3.])
>>> torch.zeros(3).index_put_([indices], input)
tensor([3., 0., 0.])
```

Nondeterministic behavior could also potentially arise if a view of a tensor has an internal memory overlap. However, #17935 is meant to prevent this from happening.

There may be a few different sensible strategies to handle nondeterminism due to multiple writes to one memory location, including:

- When the deterministic flag is turned on, detect when these nondeterministic cases arise and throw an error.
- When the deterministic flag is turned on, detect when these cases arise, and apply the multiple writes in a consistent order. The order of writes would ideally be the same for CUDA and CPU. The order of writes should be enforced with sufficient unit tests

cc @mruberry @kurtamohler

**Comment by mruberry** [comment]
Update from offline meeting with @kurtamohler: our plan is to update the documentation for use_deterministic_algorithms() to explain this behavior with a note and examples.
