### ISSUE TITLE
[TorchScript] Usability study

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#50751]
### Goal

- Collect examples of TorchScript scripting failure in real-world scenarios
- Classify them into common categories of root-causes
- Propose new TorchScript features or enhancements to TorchScript implementation

### Collecting and classifying scripting failures

We will use issues (existing or new) to document examples of scripting failures. They can be tagged for different root-causes:

- `TSRootCause:TypeChecking`: scripting failed w/ confusing error messages, but user errors could have been clearly conveyed if there is early type-checking
- `TSRootCause:DynamicBehaviors`: scripting failed due to dynamic behaviors of Python programs, e.g., certain expressions or variables cannot be statically typed
- `TSRootCause:DefaultTypes`: scripting failed because using default types for un-annotated variables lead to compilation errors 
- `TSRootCause:UnsupportedConstructs`: scripting failed because certain (forms of) Python constructs are not supported by TorchScript
- `TSRootCause:TypeRefinement`: scripting failed due to failure to refine Optional types after `is not None` checking (e.g., #44077)
- `TSRootCause:InvalidCustomClass`: scripting failed due to using TorchScript classes or other custom types that are not compilable (e.g., #49650)
- `TSRootCause:Unclassified`: for all unclassified categories

### Scope

- Tag existing issues of scripting failure
- Add scripting failure examples reported from other channels
- Study the parity benchmark results (see [a FB internal note](https://fb.workplace.com/notes/ai-compiler-team/common-torchscript-compilation-failure-modes-for-pytorch-modules/383008222803445))

cc @gmagogsfm

**Comment by Lilyjjo** [comment]
Quip document version for easier editing: https://fb.quip.com/frImADCzaAlP

**Comment by gmagogsfm** [comment]
Closing, we have collected enough usability issues to work on for now.
