### ISSUE TITLE
MKLDNN not enabled by default in pytorch nightly after 1/14

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#50762]
## 🐛 Bug
Starting in release 1.8.0.dev20210114(19a8e68), pytorch is built without MKLDNN support, as it should be. 

## To Reproduce
print(*torch.__config__.show().split("\n"), sep="\n") 

Note: this was detected by a torchbenchmark regression in the [LearningToPaint model](https://github.com/pytorch/benchmark/tree/master/torchbenchmark/models/LearningToPaint), but should be a widespread issue.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by XiaobingSuper** [comment]
Solved by https://github.com/pytorch/pytorch/pull/50782.
