### ISSUE TITLE
Stuck on PyTorch 1.4 on MacOS

### ISSUE THREAD

**Issue by wcneill** [pytorch/pytorch#50770]
## 🐛 Bug

I trained a model on a GCP GPU, and saved it to my (windows) laptop. Everything works great. I'm able to load and use the model to do inference on my laptop just fine. 

Then, I received a Mac from my employer and got it all set up with PyTorch. Loading the models with this code:
```
model = LSTMEncoderDecoder(n_features, emb_size)

model.load_state_dict(
    torch.load(
        f'data/models/ae_lstm_mse_sum_{window}d_{factor}f.pt', # The location of the saved model
        map_location=torch.device(device)                                        # For loading the model onto a CPU only device.
    ) 
)
```
Yields this convoluted error:

```
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /Users/distiller/project/conda/conda-bld/pytorch_1580186068235/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /Users/distiller/project/conda/conda-bld/pytorch_1580186068235/work/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x1394ae267 in libc10.dylib)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 2350 (0x12cab450e in libtorch.dylib)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 143 (0x12cab3b5f in libtorch.dylib)
frame #3: void pybind11::cpp_function::initialize<void pybind11::detail::initimpl::constructor<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::execute<pybind11::class_<caffe2::serialize::PyTorchStreamReader>, 0>(pybind11::class_<caffe2::serialize::PyTorchStreamReader>&)::'lambda'(pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >), void, pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::detail::is_new_style_constructor>(pybind11::class_<caffe2::serialize::PyTorchStreamReader>&&,  (*)(0...), void pybind11::detail::initimpl::constructor<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::execute<pybind11::class_<caffe2::serialize::PyTorchStreamReader>, 0>(pybind11::class_<caffe2::serialize::PyTorchStreamReader>&)::'lambda'(pybind11::detail::value_and_holder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) const&...)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 147 (0x129782d43 in libtorch_python.dylib)
frame #4: pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3382 (0x12917b3c6 in libtorch_python.dylib)
<omitting python frames>
```

## To Reproduce

1. Train a model on GCP
2. Save the model to your windows 10 laptop
3. Load the model with the code above using a Mac. 

I'm sorry, I don't really know how to make it more reproducible, and I don't have time to tinker. I've already wasted too much time trying to learn how to use a Mac. I'm just wondering if I'm going to continue running into issues like this. If so, I'll go back to using my personal laptop for work. 

## Expected behavior

The model should load without error. 

## Environment

PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.0.1 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.4.0
[pip3] torchaudio==0.4.0a0+ba6d67b
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py38h9ed2024_0  
[conda] mkl_fft                   1.2.0            py38hc64f4ea_0  
[conda] mkl_random                1.1.1            py38h959d312_0  
[conda] numpy                     1.19.2           py38h456fd55_0  
[conda] numpy-base                1.19.2           py38hcfb5961_0  
[conda] pytorch                   1.4.0                   py3.8_0    pytorch
[conda] torchaudio                0.4.0                      py38    pytorch
[conda] torchvision               0.5.0                  py38_cpu    pytorch

cc @ezyang @seemethere @malfet @walterddr @mruberry

**Comment by skyline75489** [comment]
So you're using PyTorch 1.4 on the macbook. And the error suggested that it might be related to using a old version of torch:

```
Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old
```

Have you tried a newer version ? The latest version should be 1.7.0,

**Comment by wcneill** [comment]
> Have you tried a newer version ? The latest version should be 1.7.0,

Unfortunately, I seem constrained to version 1.4. Trying to update through conda `conda update pytorch` yields:

```
Updating pytorch is constricted by 

torchaudio -> requires pytorch==1.4.0
torchvision -> requires pytorch==1.4.0
```

I have tried updating both torchaudio and torchvision to their latest versions, but it changes nothing.

**Comment by mruberry** [comment]
I see, relabeling and renaming this issue.

**Comment by wcneill** [comment]
> I see, relabeling and renaming this issue.

I don't know if it matters, but I just checked that this mac is on that new M1 Silicone chip set... Maybe that's part of the issue?

**Comment by walterddr** [comment]
FYI #48145 has more information for Apple silicon

**Comment by wcneill** [comment]
> FYI #48145 has more information for Apple silicon

Yeah, I did notice that. Unfortunately, I'm a dumb monkey turning a wrench when it comes to PyTorch. I was unable to follow details of the thread to determine if it is related to my problem. I thought not, but I could be wrong...

**Comment by malfet** [comment]
@wcneill if you are using conda, can you please try creating new environment (or uninstall existing versions of pytorch and torchaudio) and try the following command (posted on https://pytorch.org/get-started/locally/ ):
``` conda install pytorch torchvision torchaudio -c pytorch ```
Version it tries to install should be:
```
  pytorch            pytorch/osx-64::pytorch-1.7.1-py3.8_0
  torchaudio         pytorch/osx-64::torchaudio-0.7.2-py38
  torchvision        pytorch/osx-64::torchvision-0.8.2-py38_cpu

```

**Comment by wcneill** [comment]
@malfet That is the exact command I used for my initial install on a brand new environment yesterday morning. The result was version 1.4 rather than 1.7.

Would you still like me to try again?

**Comment by malfet** [comment]
@wcneill can you please share the output of `conda info` here?
Also, now that you have 1.7.1, do you still run into the crash while trying to load the model?

**Comment by wcneill** [comment]
@malfet In my old environment, I forced pytorch to update to 1.7.0 via `conda install pytorch=1.7.0 -c pytorch`. That took care of the crash issue. 

I was under the impression that this was a bad practice (better to use `update` rather than blindly ignore dependencies by using `install` to upgrade a version?)

Here is the output of `conda info` from the new test environment:

```
     active environment : test-env
    active env location : /Users/wesle/opt/anaconda3/envs/test-env
            shell level : 2
       user config file : /Users/wesle/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/wesle/opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/wesle/opt/anaconda3/pkgs
                          /Users/wesle/.conda/pkgs
       envs directories : /Users/wesle/opt/anaconda3/envs
                          /Users/wesle/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by wcneill** [comment]
@malfet I have another idea of what it might be! I migrated my windows PC files to my new mac yesterday. I think that included some files from the `anaconda3` folder. 

Then, when I created my "new" environment, I used the same old environment name from my windows PC. Perhaps this confused conda and it installed versions based on what it already knew?

Total speculation... and I have no idea how to reproduce the issue. I'm sorry :(

**Comment by malfet** [comment]
@wcneill thank you for sharing. Have you invoked `conda update` with `-c pytorch` option? Otherwise, you would indeed be stuck on 1.4 (or whatever other version you had installed previously) as `pytorch` is not part of standard Anaconda channel list.

**Comment by wcneill** [comment]
@malfet I know that you are supposed to use `-c pytorch`, so I assume I did. However, I often forget left from right... It's totally possible I didn't. 

The output I received using `update` was something about being constricted due to the requirements of torchaudio and torchvision. I think I pasted the output higher in this thread.
