### ISSUE TITLE
Missing CLAs for a few collaborators

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#50771]
As a follow up to the [announcement we made last year](https://pytorch.org/blog/a-contributor-license-agreement-for-pytorch/) we still need Contributor License Agreements (CLAs) signed for a few collaborators. The CLA/license for PyTorch is not changing, we just have a few loose ends to tie up. If your username is not in the below list, then you don't need to do anything.

However, if your username appears on this list then we need you to [sign the CLA](https://code.facebook.com/cla) before February 2nd:

- [x] @alexsax
- [ ] @apaszke
- [ ] @avmgithub
- [ ] @baobabxlyh
- [x] @fehiepsi
- [x] @JackCaoG
- [x] @jaliyae
- [x] @maxluk
- [x] @neuromage
- [ ] @numerology
- [ ] @paveldournov
- [ ] @scintiller

## Why?

Facebook's Open Source policies require a valid CLA for an user to be a member or outside collaborator in our projects. An exemption was granted while we were adding the CLA to PyTorch. This exemption is ending on February 2nd.

## What happens if I don't sign by Feb 2nd?

You will be removed from the PyTorch org and all permissions (triage, write, maintain, etc.) will be revoked. Once you sign the CLA, your permissions can be reinstated. The revocation is mostly for technical reasons, since we're managing CLA permissions with another system that makes it time-consuming to continue maintaining these exemptions.

## Wait I already signed?

If you think you already signed the CLA but your name appears on this list, please reply to this issue and tag @bigfootjon to get that sorted out.

**Comment by bigfootjon** [comment]
As a reminder, the following contributors still haven't signed the CLA and will be removed from the org tomorrow (Feb 2nd):

* @apaszke
* @avmgithub
* @baobabxlyh
* @numerology
* @paveldournov
* @scintiller

**Comment by bigfootjon** [comment]
The people listed in my comment above have been removed. Once the CLA is signed, permissions can be restored
