### ISSUE TITLE
Implement torch.max for float16 and bfloat16 on CPU and CUDA

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#50790]
## 🚀 Feature

Add support for `torch.max` with:
* CUDA bfloat16
* CPU float16 and bfloat16

## Motivation

Currently, `torch.max` has support for CUDA float16:
```
>>> torch.rand(10, dtype=torch.float16, device='cuda').max()
tensor(0.8530, device='cuda:0', dtype=torch.float16)
```

But all three other combinations of CPU/CUDA and float16/bfloat16 are not supported:
```
>>> torch.rand(10, dtype=torch.float16).max()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "max_all" not implemented for 'Half'
>>> torch.rand(10, dtype=torch.bfloat16).max()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "max_all" not implemented for 'BFloat16'
>>> torch.rand(10, dtype=torch.bfloat16, device='cuda').max()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "max_all_cuda" not implemented for 'BFloat16'
```

**Comment by mruberry** [comment]
We would accept a PR implementing this proposal.

**Comment by jonykarki** [comment]
what files are the max implemented on?

**Comment by mruberry** [comment]
You'll want to be sure that torch.max, torch.min, torch.amax, and torch.amin support these dtypes. You can find amax_out's device generic implementation here:

https://github.com/pytorch/pytorch/blob/4803eaf502fb9510a729bd1e1d3bb52744a84886/aten/src/ATen/native/ReduceOps.cpp#L926

To get an idea for how operators in PyTorch are implemented you may want to look at PRs completed on this issue: https://github.com/pytorch/pytorch/issues/38349. You could also trying reading the ATen/native README. Querying for amin/amax in the codebase should help you discover where these ops are implemented, too.

Once the implementation is done we can discuss testing. For each of these operators we should look at creating an OpInfo to test their jit, autograd, and dtype support. 

Let me know if you have additional questions, @jonykarki.

**Comment by jonykarki** [comment]
where is the supported dtypes declared for Tensor in amax?

**Comment by mruberry** [comment]
Take a look at the dispatch macros on the CPU and CUDA for kernel stubs.

**Comment by imaginary-person** [comment]
Hello @jonykarki, are you still working on this one?

**Comment by jonykarki** [comment]
I was for a while, but stopped when I saw your pull request. Are you working on it?

**Comment by imaginary-person** [comment]
Oh, that isn't a PR. It's a commit. I had referenced this issue number by mistake, but the title is correct; it's unrelated to this issue.

**Comment by jonykarki** [comment]
Oh, I didn't notice that. You can have this issue if you want. I'm probably not gonna be able to get back to this for a few more days.

**Comment by imaginary-person** [comment]
OK, thank you!

**Comment by imaginary-person** [comment]
> _Once the implementation is done we can discuss testing. For each of these operators we should look at creating an OpInfo to test their jit, autograd, and dtype support._

Hello @mruberry, I added support for min/max related ops for Float16 & BFloat16.
Please give me some advice for writing OpInfo based tests.

Thank you!

**Comment by kurtamohler** [comment]
@imaginary-person, thanks for the PR! `OpInfo`s are found in `torch/testing/_internal/common_methods_invocations.py` in the `op_db` list. There are plenty of examples there to base yours upon. The `OpInfo` class is also defined in that file, along with descriptions of what each kwarg does. Once you add an OpInfo, you can run the tests with `python test/test_ops.py -k <name of function>`

**Comment by kurtamohler** [comment]
Also, @mruberry wrote a really nice new wiki page about writing tests: https://github.com/pytorch/pytorch/wiki/Writing-tests-in-PyTorch-1.8

**Comment by mruberry** [comment]
> Also, @mruberry wrote a really nice new wiki page about writing tests: https://github.com/pytorch/pytorch/wiki/Writing-tests-in-PyTorch-1.8

Suggestions welcome!

I'll take a look soon, too, @imaginary-person.

**Comment by PranxXxD** [comment]
Hey! I would like to work on this issue so, can you help me get started?

**Comment by kurtamohler** [comment]
Thanks for your interest @PranxXxD! @imaginary-person already has a PR drafted for this issue (see "Linked pull requests" in the right column above). We have many other open issues though. Here are all the unassigned issues marked "good first issue" that do not have a linked PR : https://github.com/pytorch/pytorch/issues?q=is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee+no%3Amilestone+-linked%3Apr+
