### ISSUE TITLE
Encounter `segmentation fault (core dumped)` when moving an embedding layer to GPU

### ISSUE THREAD

**Issue by HanwGeek** [pytorch/pytorch#50799]
## 🐛 Bug

Encounter `segmentation fault (core dumped)` when moving an embedding layer to GPU

## To Reproduce

```python
CUDA = torch.cuda.is_available()
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
DEVICE = torch.device("cuda" if CUDA else "cpu")
embed_gpu = nn.Embedding.from_pretrained(torch.rand((2, 3)), freeze=True).to(DEVICE)
```

## Expected behavior

Successfully moving embedding layer to GPU without error.
## Environment

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX

Nvidia driver version: 455.38
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torch-cluster==1.5.8
[pip3] torch-geometric==1.6.3
[pip3] torch-scatter==2.0.5
[pip3] torch-sparse==0.6.8
[pip3] torch-spline-conv==1.2.0
[pip3] torchvision==0.8.2

**Comment by kshitij12345** [comment]
Works for me on master,
```python
>>> import torch
>>> from torch import nn
>>> DEVICE = torch.device("cuda")
>>> embed_gpu = nn.Embedding.from_pretrained(torch.rand((2, 3)), freeze=True).to(DEVICE)
>>> torch.__version__
'1.8.0a0+bd5a4db'
>>> 
```
Can you try the nightly version to see if that works for you?

**Comment by HanwGeek** [comment]
@kshitij12345 I find that `torch.rand(2, 3).to(DEVICE)` also produce the same error. I think maybe it is a problem with GPU.

**Comment by Ali2500** [comment]
Try running with PyTorch <= v1.6. I'm also getting seg faults with trivial code with v1.7.1 (see #50804).

**Comment by mruberry** [comment]
Sorry to hear you're having trouble, @HanwGeek. If even putting a tensor on device is causing this error, as your follow-up suggests, I think you're right that you have an installation or GPU problem. I'm not sure there's much we can do to help with that :(. Closing this pending new data that might let us help. Best of luck with the GPU!
