### ISSUE TITLE
bug of torchscript: when using torch.jit.trace to save the pt model and then load it to run, the second run is particularly slow

### ISSUE THREAD

**Issue by HuangdaoQin** [pytorch/pytorch#50796]
## 🐛 Bug

I have trained a model and used "torch.jit.trace" to save the pt model for deployment. However, after loading the pt model and input data to model, I found it runs particularly slowly in the second time. It is forgivable that first time running takes more time, because it needs time for initialization. However, the second run is particularly slowly, especially when the model is sequence generation model. It seems like running on the cpu but not gpu, while model runs on gpu in the first time and other time. In addition, this phenomenon doesn't appear in torch==1.6.0, but appears in torch==1.7.0 and torch==1.7.1

Please fix this bug or tell me other solutions. Thanks a lot !

## To Reproduce

1. run the python code below and observe the running time for every time

```
import torch
import torchvision
import time

input = torch.randn(1, 3, 224, 224).cuda()
model = torchvision.models.resnet18().cuda()
model.eval()
_ = model(input)
traced_model = torch.jit.trace(model, input, strict=False)
torch.jit.save(traced_model, './jit_trace_model.pt')

model = torch.jit.load('./jit_trace_model.pt').cuda()
input = torch.randn(1, 3, 224, 224).cuda()

model.eval()
for _ in range(4):
    time0 = time.time()
    _ = model(input)
    time1 = time.time()
    print(time1 - time0)
```

When using torch==1.6.0, the running time is usual:
0.1594221591949463
0.002562284469604492
0.0025255680084228516
0.002506256103515625

When using torch==1.7.0 or 1.7.1 the second run is particularly slow:
0.07514166831970215
0.13930249214172363
0.005217313766479492
0.005143404006958008

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.9
 - CUDA/cuDNN version: CUDA10.2.89
 - GPU models and configuration:1080ti * 8
 - Any other relevant information:

**Comment by WANGCHAO1996** [comment]
我也遇到了相似的问题请问你解决了吗 ？ libtorch1.7.1 yolov5模型  cuda10.2
![图片](https://user-images.githubusercontent.com/51087601/105503265-548fe900-5d01-11eb-9e67-b4469068e809.png)

**Comment by HuangdaoQin** [comment]
> 我也遇到了相似的问题请问你解决了吗 ？ libtorch1.7.1 yolov5模型 cuda10.2
> ![图片](https://user-images.githubusercontent.com/51087601/105503265-548fe900-5d01-11eb-9e67-b4469068e809.png)

并没有，如果你急着部署的话，可以使用torch1.6

**Comment by eellison** [comment]
Hello @HuangdaoQin, as of 1.7, in the first run we profile the graph, and in the second run, we optimize it. You can see dumps of the IR optimization by running `PYTORCH_JIT_LOG_LEVEL='profiling_graph_executor_impl' python ${your_file}`. Closing, feel free to continue to comment or open if you think there is still an issue.

**Comment by HuangdaoQin** [comment]
> Hello @HuangdaoQin, as of 1.7, in the first run we profile the graph, and in the second run, we optimize it. You can see dumps of the IR optimization by running `PYTORCH_JIT_LOG_LEVEL='profiling_graph_executor_impl' python ${your_file}`. Closing, feel free to continue to comment or open if you think there is still an issue.

Thank you for your reply. I find that when the model was run for the second time, it was on the cpu instead of the gpu. This will cause the second run to be particularly slow, especially when the model is complex. For example, the second run time of the sequence prediction model (attention or transformer) is 60 times longer than the third run. It is not conductive to industrial deployment. Hope you can continue to optimize for this issue. Thanks again.

**Comment by Sanster** [comment]
@eellison Is there any way to turn off this feature?
