### ISSUE TITLE
AttributeError: type object 'torch._C.FloatTensorBase' has no attribute 'numpy'

### ISSUE THREAD

**Issue by m09** [pytorch/pytorch#508]
Having followed the installation steps, I encounter this error while running the rl examples:

    Traceback (most recent call last):
      File "actor_critic.py", line 7, in <module>
    import torch
      File "/home/m09/.virtualenvs/pytorch/lib/python3.4/site-packages/torch/__init__.py", line 250, in <module>
        from . import _torch_docs, _tensor_docs
      File "/home/m09/.virtualenvs/pytorch/lib/python3.4/site-packages/torch/_tensor_docs.py", line 1007, in <module>
        add_docstr(torch._C.FloatTensorBase.numpy,
    AttributeError: type object 'torch._C.FloatTensorBase' has no attribute 'numpy'

I tested installs both with python 2.7 and python 3.4. Both fail.

**Comment by apaszke** [comment]
Do you have numpy installed? Can you install it and try rebuilding pytorch?

**Comment by m09** [comment]
I just ran

    mkvirtualenv pytorch
    pip install numpy
    pip install -r requirements.txt
    python setup.py install

and then tried to import `torch` in a python interpreter and had the same error.

**Comment by apaszke** [comment]
That's surprising. Can you import `numpy` in the interpreter?

**Comment by m09** [comment]
yes I can:

    >>> import numpy as np
    >>> np.ones(3)
    array([ 1.,  1.,  1.])
    >>>

**Comment by m09** [comment]
I do have torch (the lua one) installed and some env variables that are torch related set. Could it be a problem?

**Comment by apaszke** [comment]
No, we made sure they wouldn't interfere. When you run python setup.py install, somewhere at the top it should print a line prefixed with `--` that says if it has found numpy. Can you check what it says please? or can you paste the build log into some gist?

**Comment by m09** [comment]
I found a line: `-- Building with NumPy bindings`, not sure if it is the one. The rest of the log is here: https://gist.github.com/m09/5f559f47dada6c4ad8df2f80141f5a70

**Comment by apaszke** [comment]
Can you `rm -rf build` and build it once more? It didn't rebuild the extension after you installed `numpy`, because it was alredy there.

**Comment by m09** [comment]
I still have the same error after having cleaned & rebuilt. New log here: https://gist.github.com/m09/a6e0afca599cd19a79e12b870f939cb1

**Comment by m09** [comment]
So, I pulled master and now get the error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "torch/__init__.py", line 45, in <module>
        from torch._C import *
    ImportError: No module named _C

I also ran python setup.py clean in-between.

**Comment by fmassa** [comment]
You need to open python from a different folder than `~/pytorch`.

**Comment by m09** [comment]
thanks, it does import correctly now. I guess the problem was an incorrectly built file that was removed by `python setup.py clean` and not by `rm -rf build`.

**Comment by apaszke** [comment]
That's possible, but I also changed some things yesterday that might have fixes that. Can you try running `torch.randn(5, 5).numpy()` and checking if it works?

**Comment by m09** [comment]
It does work :)

**Comment by apaszke** [comment]
Ok, perfect. It seems that the issue is solved, I'm closing it.
