### ISSUE TITLE
Where can I find the method of calling Bert from Torch's  C++ API ?

### ISSUE THREAD

**Issue by duan348733684** [pytorch/pytorch#50808]
Where can I find the method of calling Bert from Torch's  C++ API ?

**Comment by mruberry** [comment]
This question is better asked on our forum here: https://discuss.pytorch.org/.

You might also want to check out the latest documentation on using the PyTorch C++ API here: https://pytorch.org/tutorials/advanced/cpp_frontend.html. You'll have to obtain and load the BERT model in C++ to invoke it.
