### ISSUE TITLE
Cannot import torch.distributed.optim

### ISSUE THREAD

**Issue by gliese581gg** [pytorch/pytorch#50805]
## To Reproduce

1. import torch.distributed.optim

## Expected behavior

import without error `ImportError: cannot import name 'RRef'`

## Environment

Collecting environment information...
PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.17.3
[pip] torch==1.7.1+cpu
[pip] torchaudio==0.7.2
[pip] torchvision==0.8.2+cpu
[conda] numpy                     1.17.3                   pypi_0    pypi
[conda] torch                     1.7.1+cpu                pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2+cpu                pypi_0    pypi

## Additional context

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by rohan-varma** [comment]
Looks like a windows issue as per the OS information in the issue. We don't support torch.distributed.optim on windows (it is for the RPC framework, but currently only DistributedDataParallel is supported on Windows). 

cc @mrshenli @gunandrose4u in case i am wrong/for more context.

**Comment by nbcsm** [comment]
Yes, only DDP is supported on Windows at this moment.
We (Microsoft) are going to contribute to support RPC on Windows as well, just stay tuned.

**Comment by gunandrose4u** [comment]
Yes, @rohan-varma , on Windows platform, RPC is not supported yet. Will add RPC support.

**Comment by rohan-varma** [comment]
Closing this out
