### ISSUE TITLE
Model Parallelism for HuggingFace Transformers

### ISSUE THREAD

**Issue by saichandrapandraju** [pytorch/pytorch#50810]
Hi,

I'm implementing [Microsoft's DeBERTa from HuggingFace](https://huggingface.co/transformers/model_doc/deberta.html) in PyTorch. 
Can I implement PyTorch's [Model Parallelism](https://pytorch.org/tutorials/intermediate/model_parallel_tutorial.html) with this HuggingFace transformer?
If yes, is there any documentation regarding this ?

**Comment by mruberry** [comment]
Hey @saichandrapandraju, this question is better asked on our forums, where the PyTorch community can help you. Check them out here: https://discuss.pytorch.org/.
