### ISSUE TITLE
[doc] Review documentation for linear algebra functions

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#50825]
Linear algebra functions are going through a lot of changes. This issue is to track the necessary documentation work. Per @IvanYashchuk's suggestion we should make the notation, terminology, batching support, autograd support, complex support etc. consistent.

Individual functions: 

- [ ] svd

- Do we need to add details about the backend? For example
    -  For svd, cusolver is used only when cuda version >= 10.1.243, magma is used otherwise

- Do we need to add details about the heuristic? For example
    - `cusolverDnXgesvdjBatched` is used when the matrix batch > 1, dimensions <= 32, and (full_matrices or m == n)

- Do we need to add details about numpy compatibility? Since SVD results are not unique, each singular vector can be multiplied by a complex phase factor `e^{i \phi}` (`\pm 1` if real) and still remain correct.

- [ ] cholesky_solve
- Update documentation to mention batch support

cc @jlin27 @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk @ptrblck

**Comment by mruberry** [comment]
I folded these tasks (and more docs-related tasks) into the linalg tracking issue (https://github.com/pytorch/pytorch/issues/42666). Closing this in favor of that so we have fewer places to track updates. Let's suggest ways to improve doc consistency or add docs-related tasks there.
