### ISSUE TITLE
Add op.input_func to OpInfo-based testing

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#50837]
Some functions with a mathematically constrained type of input require special preprocessing so that finite-difference derivatives match the analytical ones implemented in the backward operation. Some examples are Hermitian (or symmetric) linear algebra functions `torch.linalg.cholesky`, `torch.linalg.eigh`, or function taking a triangular matrix input as `torch.cholesky_inverse`.
This requirement can be met for example with a custom OpInfo class that overrides `get_op` method. But then `test_variant_consistency_jit` tests would fail with mismatch error in computed gradients because the jit scripted function ignores the `get_op` method.
`OpInfo` already has `output_func`, so we should add `input_func` as well.

It should be enough to change these lines https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_jit.py#L127-L131
to something like 
```python
def runAndSaveRNG(self, func, inputs, kwargs=None, input_func=None):
    kwargs = kwargs if kwargs else {}
    with freeze_rng_state():
        if input_func is not None:
            inputs = [input_func(*inputs, **kwargs)]
        results = func(*inputs, **kwargs)
    return results
```
to make `test_variant_consistency_jit` tests pass with custom `op.input_func`. All other occurrences of calling `.get_op()` should also use `op.input_func`.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @mruberry

**Comment by mruberry** [comment]
Linked to the test suite tracking issue and cc @albanD as an fyi. This seems like the right idea to me.

**Comment by albanD** [comment]
SGTM!
