### ISSUE TITLE
CuDNN v5 found, but i have cudnn6. How to fix?

### ISSUE THREAD

**Issue by shadowfolder** [pytorch/pytorch#5084]
pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
That is wrong. I have cudnn6. How i can fix it? Thanks

**Comment by ezyang** [comment]
The usual cause is that you are picking up stale cuDNN v5 headers somewhere. Can you completely uninstall cuDNN 5 and try again?

**Comment by shadowfolder** [comment]
I can't do it, because I've already nstalled ptorch via another method```
 pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl 
pip3 install torchvision
```
But thanks for feedback mate! :)
