### ISSUE TITLE
[nnc][perf] CPU fuser needs to support intra-op parallelism

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#50853]
## 🐛 Bug

The CPU fuser always produces single-threaded code.  To get comparable performance to eager mode on single ops, it needs to support parallelism (via OMP or a custom threadpool or ...).

## To Reproduce

```
import timeit
import torch

torch._C._jit_override_can_fuse_on_cpu(True)
torch._C._debug_set_fusion_group_inlining(False)

x = torch.randn(2**18)

@torch.jit.script
def script_add(x):
    return x + x

for _ in range(5):
    script_add(x)

print(timeit.timeit(stmt="x + x", globals=globals(), number=1000))
print(timeit.timeit(stmt="script_add(x)", globals=globals(), number=1000))
                                                                                                                
```

Results on my 2.5 GHz 48-core Sandy Bridge show about 5x slowdown for the fuser.
```
0.02427208423614502
0.1031530424952507
```

## Expected behavior

Parallelism.

**Comment by ZolotukhinM** [comment]
The parallel support for LLVM CodeGen will be added in #53243.

**Comment by ZolotukhinM** [comment]
This is done now!

**Comment by bertmaher** [comment]
I'm going to reopen this issue because the parallelism support still isn't plumbed all the way through to the fuser.  I hope it's not super hard to do that?

**Comment by bertmaher** [comment]
cc @huiguoo this is the issue with parallelism we were talking about earlier today.

**Comment by augustweinbren** [comment]
@bertmaher @ZolotukhinM Do you know if the NNC supports parallelism yet?

**Comment by bertmaher** [comment]
This has been fixed for a while now (I think we added support for parallelism ~3 years ago) but also NNC is deprecated now.  I'd recommend switching to torch.compile.
