### ISSUE TITLE
format issue in document of torch.nn.MultiheadAttention 

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#50919]
## Link:

https://pytorch.org/docs/1.6.0/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention#torch.nn.MultiheadAttention

## API
`torch.nn.MultiheadAttention`

## Issue
The document of this API has format issue:

![image](https://user-images.githubusercontent.com/24580222/105424834-179af800-5c16-11eb-845b-32f29b174ee1.png)

cc @jlin27 @mruberry @albanD @jbschlosser @zhangguanheng66

**Comment by mruberry** [comment]
Thank you for reporting this issue, @DNXie. We would accept a PR fixing this.

**Comment by zhangguanheng66** [comment]
This has been fixed in the master branch [link](https://pytorch.org/docs/master/generated/torch.nn.MultiheadAttention.html?highlight=multiheadattention#torch.nn.MultiheadAttention). Feel free to re-open the issue if you still have a question. Thanks a lot.
