### ISSUE TITLE
all reduce hangs (NCCL 2.8.0.3)

### ISSUE THREAD

**Issue by joshim5** [pytorch/pytorch#50921]
## 🐛 Bug

When I run the simple script below with GLOO, it runs correctly. With NCCL backend, the all reduce only seems to happen on rank 0.

## To Reproduce

Run the simple minimum working example below. If you use `backend=dist.Backend.NCCL`, then you'll only see `reduced 0` but not `reduced 1`. 

It works fine with GLOO.
```
import torch.multiprocessing as mp
import torch
import random
import time

def init_distributed_world(rank, world_size):
    import torch.distributed as dist
    backend = dist.Backend.NCCL if torch.cuda.is_available() else dist.Backend.GLOO  # type: ignore
    assert world_size <= torch.cuda.device_count()
    port = 20000
    init_method = 'tcp://localhost:{port}'.format(port=port)

    print('init process group')
    dist.init_process_group(init_method=init_method, backend=backend, rank=rank, world_size=world_size)
    print('I always get stuck here...')

    dist.all_reduce(torch.zeros([1]).cuda(), op=dist.ReduceOp.SUM)
    print('reduced', dist.get_rank())

def local_worker(rank, workers):
    init_distributed_world(rank, workers)

if __name__ == '__main__':
    workers = 2
    mp.spawn(local_worker, nprocs=workers, args=(workers, ), join=True)
```

## Expected behavior

Should print:
```
reduced 0
reduced 1
```

## Environment

PyTorch version: 1.7.0a0+57bffc3
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.0.5
[pip3] torch==1.7.0a0
[pip3] torchaudio==0.7.0a0+a853dff
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by mcarilli** [comment]
You're not calling set_device in your subprocesses. `torch.zeros([1]).cuda()`* in both processes will end up on the same gpu. Are there multiple GPUs on your system, or are you trying to write an example where both processes control the same gpu?

* unsolicited advice: torch.zeros([1]).cuda incurs a blocking cpu->gpu memcopy. prefer native constructors with kwargs, ie `torch.ones((,1), device="cuda:N")`, which typically launch a fast asynchronous kernel.

**Comment by glaringlee** [comment]
@joshim5
Is @mcarilli 's comment resolved your problem?

**Comment by joshim5** [comment]
Yes, but for some reason this fails on PyTorch 1.7 but not PyTorch 1.5, so I wanted to flag it as a bug. If using the same GPU for all these processes is not officially supported, then feel free to close the issue.

**Comment by glaringlee** [comment]
@joshim5 
We will look into this.

**Comment by rohan-varma** [comment]
Using the same GPU is indeed not supported, although it's strange that this works as expected on PyTorch 1.5 (just verified it locally with your script).

The NCCL version is different in 1.5 vs 1.7.1 though: 2.4.8 vs 2.7.8. 

I'm wondering if this has something to do with a change in NCCL at some point in between these versions. @mcarilli Would you or someone else from nvidia happen to have context about that?

Although, I would still advise calling `torch.cuda.set_device()` appropriately as others have advised.

**Comment by rohan-varma** [comment]
Closing since the above mitigation should work. Feel free to reopen as needed.

**Comment by brando90** [comment]
> Using the same GPU for allreduce on different processes is indeed not supported, although it's strange that this works as expected on PyTorch 1.5 (just verified it locally with your script).
> 
> The NCCL version is different in 1.5 vs 1.7.1 though: 2.4.8 vs 2.7.8.
> 
> I'm wondering if this has something to do with a change in NCCL at some point in between these versions. @mcarilli Would you or someone else from nvidia happen to have context about that?
> 
> Although, I would still advise calling `torch.cuda.set_device()` appropriately as others have advised.

Can you give an example of where and how to set `torch.cuda.set_device()`? It's not in any of the tutorials so it's unclear how and where I should be calling it.

**Comment by brando90** [comment]
related: https://stackoverflow.com/questions/66807131/how-does-solve-the-famous-unhandled-cuda-error-nccl-version-2-7-8-error
