### ISSUE TITLE
[Engineering] Can we maybe purge the stale branches in this repo?

### ISSUE THREAD

**Issue by skyline75489** [pytorch/pytorch#50928]
The # of branches is over 4500, which brings a lot of pressure to CI system when it comes to cloning code. Right now there's a 
 staggeringly large amount of stale/merged branches.

**Comment by skyline75489** [comment]
CC @ezyang @smessmer  @malfet @mruberry  @nbcsm @mszhanyi

**Comment by imaginary-person** [comment]
I'm not a PyTorch team member, but I recommend reading up the discussion in #41232. 
It seems @yns88 had also deleted some branches back in July last year using an internal FB cron job, so he might be able to help again.

**Comment by skyline75489** [comment]
Thanks @imaginary-person . I didn't know #41232 before. Now this seems to be dup of that issue.

**Comment by glaringlee** [comment]
close this one since it is dup of #41232
