### ISSUE TITLE
Implement fusion for LeakyReLU

### ISSUE THREAD

**Issue by evrrn** [pytorch/pytorch#50947]
## 🚀 Feature

Currently **LeakyReLU** is not in the [list of modules with fusion](https://github.com/pytorch/pytorch/blob/0c77bd7c0bbd4d6e50a5f3ce7b4debbee85d7963/torch/quantization/fuse_modules.py#L106), though it's often used in the convolutional networks. Is there an opportunity to expand the list with fusion for **LeakyReLU**?

There is for sure option to exchange LeakyReLU into plain ReLU, albeit it likely could harm the models quality and/or demand models retraining.

cc @albanD @mruberry @jbschlosser @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by raghuramank100** [comment]
This requires a new kernel. If you can quantify the benefit, we can consider this. But since this requires substantial effort, closing this issue for now
