### ISSUE TITLE
segmentation fault in torch.nn.FractionalMaxPool2d 

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#50967]
## 🐛 Bug

torch.nn.FractionalMaxPool2d throws segfault when `kernel_size`=[]

## To Reproduce

~~~python
import torch
layer = torch.nn.FractionalMaxPool2d(kernel_size=[], output_size=1, _random_samples=torch.tensor(-1))
model_input=torch.ones((1,1,1,1))
layer(model_input)
~~~

Error Message:
~~~python
Segmentation fault (core dumped)
~~~
## Expected behavior

expect no crash

## Environment
PyTorch version: 1.5.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @heitorschueroff

**Comment by glaringlee** [comment]
This happen on 1.7 as well.

**Comment by mruberry** [comment]
We would accept a PR fixing this.

cc @malfet
