### ISSUE TITLE
Manually changed quantized weights not reflecting in state_dict()

### ISSUE THREAD

**Issue by gakadam** [pytorch/pytorch#50988]
## 🐛 Bug

When manually changed the statically quantized weghts of a model "post-quantization", `state_dict()` is not updated. 
Specifically, `model_int8.features[0].weight` shows updated values, but `model_int8.state_dict()['features.0.weight']` shows old vales.
Furthermore, the inference output is unaffected. Question is which weight values are used for inference: old or updated?
I tried changing multiple values manually post quantization in the first layer and still the inference output is unaffected.

## To Reproduce

The steps I took are:
```
# instantiate the quantized net (not shown here).

# get one of the conv layers
tmp = model_int8.state_dict()['features.0.weight']
scales = tmp.q_per_channel_scales()
zero_pts = tmp.q_per_channel_zero_points()
axis = tmp.q_per_channel_axis()

# get int repr
tmp_int8 = tmp.int_repr()

# change value (value change is dependent on the int8 value)
tmp_int8[0][0][0][0] = new_value

# how to convert tmp_int8 to torch.qint8 type?
new_tmp = torch._make_per_channel_quantized_tensor(tmp_int8, scales, zero_pts, axis)

# based on the above step:
model_int8.features[0].weight = new_tmp

# shows updated values
print(model_int8.features[0].weight)

# shows old values
print(model_int8.state_dict()['features.0.weight'])

# inference is unchanged compared to original quantized model
```
## Expected behavior

The `state_dict()` should also be updated. It should be reflected in the inference output (it should change). 

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Red Hat Enterprise Linux (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source):  conda
 - Python version: 3.8 (64-bit)
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: Running on CPU due to quantization

## Additional context

I posted here as it seems to be a bug.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
this is expected, I answered here with more details: https://discuss.pytorch.org/t/changed-quantized-weights-not-reflecting-in-state-dict/109741/2
