### ISSUE TITLE
Do tensors on gpu perform non-arithmetic operations faster than tensors on cpu?

### ISSUE THREAD

**Issue by JiangTanZJU** [pytorch/pytorch#50989]
As we all know, gpu can accelerate arithmetic operations of tensors, such as `+ - * /`.

In that way, do tensors on gpu perform non-arithmetic operations faster than tensors on cpu?

For example, I want to change all elements of the tensor which are smaller than 10000 to 123:

~~~py
a = torch.tensor([i for i in range(100000)])
a[(a<10000).nonzero(as_tuple=True)] = 123 # operation 1
~~~

~~~py
a = torch.tensor([i for i in range(100000)]).cuda()
a[(a<10000).nonzero(as_tuple=True)] = 123 # operation 2
~~~

Is operation 2 necessarily faster than operation 1?

**Comment by bdhirsh** [comment]
Hi @JiangTanZJU! This question would probably be better suited in the PyTorch forums. I'm going to close this issue and redirect you there: https://discuss.pytorch.org
