### ISSUE TITLE
torchvision is old  in PyPI for Windows 64

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#50982]
## 🐛 Bug

If we run `pip install torchvision` on Window CPU,  torchvision-0.2.2.post3 is installed

## To Reproduce

In Windows10 64 bit machine, run pip install torchvision.

## Expected behavior

Since we can get the torch 1.7 on Windows CPU, we should get the correct torchvision.
I came across this issue when I was installing fastai.

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mszhanyi** [comment]
related to #50535

**Comment by peterjc123** [comment]
@malfet @seemethere So we didn't upload the new packages of torchvision/audio/text for Windows to PyPI?

**Comment by seemethere** [comment]
I don’t believe we’ve ever uploaded windows packages to PyPI for any of those particular packages.

Windows packages for `torch` on PyPI are a new thing that started officially with `1.7`

**Comment by nbcsm** [comment]
torchvision windows package is published to pypi.

**Comment by seemethere** [comment]
Going to go ahead and close this, feel free to reopen if you feel the need
