### ISSUE TITLE
MKL Error when import torch after installing 0.3.0 on CentOS

### ISSUE THREAD

**Issue by wddabc** [pytorch/pytorch#5099]
After installing from the website by:
`conda install pytorch torchvision -c pytorch`
it gets the following error when I'm trying to `import torch`:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/XXXX/anaconda2/envs/XXX/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
>     from torch._C import *
> ImportError: /cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_sgelqf

When I rollback to 0.2.0, the error is gone.

--------------------------------------------------------------------------------------------------
- OS:

```
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final
```

- PyTorch version:`0.3.0-py36_cuda8.0.61_cudnn7.0.3h37a80b5_4`
- How you installed PyTorch (conda, pip, source):
`conda install pytorch torchvision -c pytorch`
- Python version:`Python 3.6.4 :: Anaconda, Inc.`
- CUDA/cuDNN version:`Cuda compilation tools, release 8.0, V8.0.61`

**Comment by soumith** [comment]
as seen in the stacktrace, i.e. `/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_sgelqf`

this is because you have MKL 2015 which is too old. But more importantly it seems to be loaded into the process already. Maybe you can install mkl from anaconda or intel channels: `conda install mkl=2018 -c anaconda` or `conda install mkl=2018 -c intel`

**Comment by wddabc** [comment]
Thanks. I think when I do conda install, it already upgrades the mkl for me. I also manually upgrade the mkl as you suggested. But it doesn't work. The way I'm doing this is :
1) rollback to 0.2.0
2) manually upgrade mkl
3) upgrade pytorch

The same error stay still.

**Comment by soumith** [comment]
I think your `$LD_LIBRARY_PATH` is loading your system MKL (which is MKL 2015).
What is output of command:

```
echo $LD_LIBRARY_PATH
```

**Comment by wddabc** [comment]
Thanks! Yes, this is really a problem of `$LD_LIBRARY_PATH`. After I put the latest mkl, the error is gone. 

But one thing I'm curious about is why `source activate ` doesn't do this automatically? The above solution looks hacky to me. Maybe I should submit an issue to conda instead?

But anyway, thanks for the speculation!

**Comment by Zohaggie** [comment]
I am having much the same problem, after installing pytorch into an Azure Data Science Virtual Machine, via the fast.ai conda environment.

I have CUDA 9 installed, and after following this thread I tried upgrading MKL, but all it offered me was and upgrade from 2018.0.2-1 to 2018.0.2-intel_1 intel, so it doesn't seem out of date.
 
I believe I have have the latest version of pytorch, as I've just installed it using the conda install process and -c soumith. Unfortunately I cannot verify my torch version as I have an error loading torch, that there is an undefined symbol: mkl_lapack_ao_ssyrdb in /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so. (see below for trace).

Following this thread I also executed echo $LD_LIBRARY_PATH, and got this:
/opt/intel/tbb/lib/intel64/gcc4.7:/opt/intel/lib/intel64:/opt/intel/mkl/lib/intel64:/dsvm/tools/cntk/cntk/lib:/dsvm/tools/cntk/cntk/dependencies/lib::/usr/local/cuda/lib64


Any idea about how to fix this?
`
import torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eb42ca6e4af3> in <module>()
----> 1 import torch

~/.conda/envs/fastai/lib/python3.6/site-packages/torch/__init__.py in <module>()
     54 except ImportError:
     55     pass
---> 56 from torch._C import *
     57
     58 __all__ += [name for name in dir(_C)

ImportError: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_ao_ssyrdb
`

**Comment by malbergo** [comment]
Hi @wddabc, I'm having the same problem as you. What did you put in your $LD_LIBRARY_PATH to make this work? And did you come up with a good solution?

My LD_LIBRARY_PATH currently echoes

 /home/chris/geant4.10.04-install/lib:/usr/local/root/lib:/usr/local/bin/Delphes-3.3.3:/usr/local/cuda-8.0/lib64:/usr/local/root/lib:/home/chris/geant4.10.04



Best,
Michael

**Comment by wddabc** [comment]
Hi @malbergo,
My solution was quite hacky. 
I add `anaconda2/envs/myenv/lib` into LD_LIBRARY_PATH in my .bashrc.

I still not quite like it because it should be automatically triggered when I call `source activate myenv`

**Comment by sbelharbi** [comment]
I just had a similar issue: `import torch` does not work and it raises an error related to mkl. As it was mentioned above, `torch` uses local mkl (which many versions of them are installed on the server) and not the conda one.
I am using a fresh installation of `pytorch.1.0.0` in a separate conda env. The error is:
```sh
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:15:35) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
ImportError: /home/ ...... /anaconda3/envs/pytorch.1.0.0.0/lib/python3.7/site-packages/torch/lib/libmkldnn.so.0: undefined symbol: cblas_gemm_s8u8s32
```
However, I already had pytorch.1.0.0 installed in another conda env. and there is no such issue. I had to reinstall it for some conflicts of the packages.

Following @wddabc 's solution, I added the path '/home/ ...... /anaconda3/envs/pytorch.1.0.0.0/lib' to the top of `$LD_LIBRARY_PATH`. Now, the import is fine. However, I agree with @wddabc , this solution is a hack.

Thanks!

The packages list in the conda env that raised the issue is the following:
```sh
$ conda list
# packages in environment at /home/ ...... /anaconda3/envs/pytorch.1.0.0.0:
#
# Name                    Version                   Build  Channel
atk                       2.25.90              h05f3006_1    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.0.2                      py_1    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5           py37h5e8e0c9_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                 py37_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gobject-introspection     1.56.1           py37haaf12d0_1    conda-forge
graphite2                 1.3.13               hfc679d8_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.1.0           py37h24bf2e0_1001    conda-forge
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.2                py37_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py37h2d50403_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
markupsafe                1.1.0            py37h470a237_0    conda-forge
matplotlib                3.0.2            py37h8a2030e_1    conda-forge
matplotlib-base           3.0.2            py37h20b835b_1    conda-forge
mistune                   0.8.4            py37h470a237_0    conda-forge
mkl                       2019.1                      144  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_2    conda-forge
ninja                     1.8.2                h2d50403_1    conda-forge
notebook                  5.7.4                 py37_1000    conda-forge
numpy                     1.15.4          py37_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.3.0            py37hc736899_0    conda-forge
pip                       18.1                  py37_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py37h8210e8a_8    conda-forge
pyrsistent                0.14.8           py37h470a237_0    conda-forge
python                    3.7.1                h5001a0f_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
python-spams              2.6.1           py37_blas_openblash25c9274_203  [blas_openblas]  conda-forge
pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch
pyyaml                    3.13             py37h470a237_1    conda-forge
pyzmq                     17.1.2           py37hae99301_1    conda-forge
qt                        5.6.2               h679f5bc_11    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
scikit-learn              0.20.2          py37_blas_openblash00c3548_400  [blas_openblas]  conda-forge
scipy                     1.2.0           py37_blas_openblashb06ca3d_200  [blas_openblas]  conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py37_0    conda-forge
sip                       4.18.1           py37hfc679d8_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
torchvision               0.2.1                      py_2    pytorch
tornado                   5.1.1            py37h470a237_0    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by incredible-john** [comment]
> as seen in the stacktrace, i.e. `/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_sgelqf`
> 
> this is because you have MKL 2015 which is too old. But more importantly it seems to be loaded into the process already. Maybe you can install mkl from anaconda or intel channels: `conda install mkl=2018 -c anaconda` or `conda install mkl=2018 -c intel`

I come from a different problem, where i have "import torch > libmkldnn.so.0 Undefined symbol: cblas_sgemm_alloc"
and this answer really help! this convert mkl-2021 version to mkl-2018 version, and my torch=1.0.0 can be import successfully!

**Comment by wuyujack** [comment]
> > as seen in the stacktrace, i.e. `/cm/shared/apps/parallel_studio_xe_2015_update2/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_sgelqf`
> > this is because you have MKL 2015 which is too old. But more importantly it seems to be loaded into the process already. Maybe you can install mkl from anaconda or intel channels: `conda install mkl=2018 -c anaconda` or `conda install mkl=2018 -c intel`
> 
> I come from a different problem, where i have "import torch > libmkldnn.so.0 Undefined symbol: cblas_sgemm_alloc"
> and this answer really help! this convert mkl-2021 version to mkl-2018 version, and my torch=1.0.0 can be import successfully!

I also come with the same problem after `apt-get update` in my ubuntu 18.04 two day's ago, and when I create a new env by conda and try to install pytorch 1.4.0, the installation succeed but when I try to import the torch, it shows the problem:

`Import Error: libmkl_gnu_thread.so: undefined symbol: mkl_graph_mxm_gus_phase2_plus_second_fp32_def_i64_i32_fp32`

After using the @incredible-john 's method, the problem fixed smoothly!
