### ISSUE TITLE
Intel MKL ERROR with pytorch 0.3.0

### ISSUE THREAD

**Issue by mschmidt87** [pytorch/pytorch#5100]
I installed pytorch in a virtual environment with conda (`conda install pytorch torchvision -c pytorch`). 
When I execute e.g. the following code:
```
    import torch
    import numpy as np
    x = np.random.randint(0, 254, size=(5, 10))
    C = np.cov(x) 
```
I get the following error:
`Intel MKL ERROR: Parameter 10 was incorrect on entry to DSYRK `

When I remove the `import torch` statement, the code executes without errors.
When I downgrade to pytorch 0.2.0 (`conda install pytorch torchvision -c soumith`), the code also executes without errors.

I am not sure how to find out the version of the Intel MKL on the system.

------------------------------------------------------------------------
- OS: CentOS Linux release 7.2.1511 (Core)
- PyTorch version: 0.3.0
- How you installed PyTorch (conda, pip, source): `conda install pytorch torchvision -c pytorch`
- Python version: Python 3.6.3
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source): -

**Comment by soumith** [comment]
can you install the mkl from anaconda: `conda install mkl=2018`.

**Comment by soumith** [comment]
you likely have a system MKL that is older than v2018 that is in $LD_LIBRARY_PATH

**Comment by mschmidt87** [comment]
Great, that solved it. 
I first installed v2018 of MKL, as you suggested with `conda install mkl=2018`.
Then, I removed the path of the older MKL version from `$LD_LIBRARY_PATH` and added the path of the new version. Now, the error disappeared. Thanks for your help.
