### ISSUE TITLE
ONNX export failed on Constant because torch.onnx.symbolic.Constant does not exist 

### ISSUE THREAD

**Issue by Dnekhaev** [pytorch/pytorch#5101]
Hi!

- OS: Linux
- PyTorch version: 0.4.0a0+ca5071d
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6

- Context around what you are trying to do
I am trying to convert layer with torch.index_select() operation to onnx

- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
```
import torch
from torch import nn
from torch.autograd import Variable

class  IndexLayer(nn.Module): 
    def __init__(self):
        super(IndexLayer, self).__init__()
        self.dim = 1
        self.index = [0,4,8,12,1,5,9,13,2,6,10,14,3,7,11,15]
    def forward(self, x):
        x = torch.index_select(x, dim=self.dim, index=Variable(torch.LongTensor(self.index)))
        return x

dummy_input = Variable(torch.randn(1,16,14,14), volatile=True)
model = IndexLayer()
torch.onnx.export(model, dummy_input, "./IndexLayer.pb", verbose=True)
```

- Error messages and/or stack traces of the bug
```
graph(%0 : Float(1, 16, 14, 14)) {
  %1 : Long(16) = Constant[value=<Tensor>](), scope: IndexLayer
  %2 : Float(1, 16, 14, 14) = Gather[axis=1](%0, %1), scope: IndexLayer
  return (%2);
}
UserWarning: ONNX export failed on Constant because torch.onnx.symbolic.Constant does not exist
  .format(op_name, op_name))
```

What is the right way to export torch.index_select() operation?

**Comment by ezyang** [comment]
It kind of sounds like we forgot to implement constant export, which is embarrassing and should be fixed.

**Comment by Dnekhaev** [comment]
Are there any chances it will be fixed soon?

**Comment by ezyang** [comment]
@Dnekhaev I took a look, and actually, it's just a spurious warning, the model seems to export successfully into `IndexLayer.pb`
