### ISSUE TITLE
torchvision

### ISSUE THREAD

**Issue by wpeak58** [pytorch/pytorch#51025]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:
Which public dataset is deeplabv3_resnet101() based on for training?
- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by bdhirsh** [comment]
Hi @wpeak58 , this sounds like a question that's better-suited for the pytorch forum: https://discuss.pytorch.org/. Closing this issue and redirecting you there.
