### ISSUE TITLE
Update fftshift, roll, and ifftshift documentation

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#51022]
## 🚀 Feature
Add `fftshift`, `ifftshift`, and `roll` functions to PyTorch fft as `torch.fft.fftshift`, `torch.fft.ifftshift` and `torch.roll`.

## Motivation

These functions are necessary for proper and easy use of FFT, which has been recently added to PyTorch https://github.com/pytorch/pytorch/issues/42175.

## Pitch

This is already implemented in FastMRI [here](https://github.com/facebookresearch/fastMRI/blob/0f538a353e4a5c855012b8f982f756d489d11462/fastmri/fftc.py#L61). FastMRI is an official project by Facebook Research. Simply copy-pasting the fftc.py file somewhere would be good enough.

## Alternatives

Cannot think of any.

## Additional context

I would also like to request documentation on the proper use of `fftshift`.

As mentioned in this issue https://github.com/numpy/numpy/issues/13442, The proper way to apply the fast Fourier transform is `fftshift(fft(ifftshift(x)))` and the proper way to apply ifft is `fftshift(ifft(ifftshift(X)))`, which is how the function is being used in the FastMRI project. However, many people do not know this. An explanation would be helpful.

cc @jlin27 @mruberry @peterbell10 @walterddr

**Comment by veritas9872** [comment]
Also, I think that an optimized version of the `roll` function would be helpful for improving runtime and memory use, though this might be more trouble than it is worth.

**Comment by mruberry** [comment]
Note that roll was in PyTorch 1.7.1, also:

https://pytorch.org/docs/1.7.1/generated/torch.roll.html?highlight=roll#torch.roll

**Comment by veritas9872** [comment]
@mruberry Thank you for the information! I was not aware that this was already implemented.
I would still like to request for extra documentation, since this is something that many people often miss.
I only wish to ask for something simple, such as an example using `fftshift(fft(ifftshift(x)))` and `fftshift(ifft(ifftshift(x)))` for forward and inverse Fourier transforms.

**Comment by mruberry** [comment]
Sounds good, @veritas9872, I've updated the title of this issue slightly to reflect this request more specifically. 

@peterbell10, what are your thoughts?

**Comment by peterbell10** [comment]
Can you explain why you want to advocate for this `fftshift(fft(ifftshift(x)))` dance? I've never heard of it before. I've only ever seen `fftshift` used on the frequency terms (and AFAIC that's how it's intended to be used).

**Comment by veritas9872** [comment]
@peterbell10 Hello. I usually use the Fourier transform for image processing, especially medical image processing, and this may lead to some differences. Please see [this](https://github.com/facebookresearch/fastMRI/blob/0f538a353e4a5c855012b8f982f756d489d11462/fastmri/fftc.py#L61) for an example of the implementation that I mentioned.

To the best of my knowledge, the `ifftshift`, `fftshift` are necessary because of the way that the FFT algorithm is implemented. To save time, the outputs are left flipped over instead of having the low-frequency components moved to the center. The internal `ifftshift` is necessary for odd-valued sequences but even-valued sequences will give the same results.

As mentioned in https://github.com/numpy/numpy/issues/13442#issuecomment-489015370 and [here](https://groups.google.com/g/comp.soft-sys.matlab/c/rUcc0bRRZf4/m/pIlDo_NnK4YJ?pli=1), many people are not aware that shifting is necessary or how to implement it properly (I had a hard time finding out myself), which is why I believe that extra documentation would be helpful.

**Comment by peterbell10** [comment]
Okay, I spoke to a colleague with a medical image processing background and they said the centered FFT convention was common among research groups and open source codes. And that it was worth adding to the docs since it's easy to mix-up the order without realising.

Perhaps this would make sense as an example in the `fftshift` docs. I'll work on a PR for that.
