### ISSUE TITLE
ONNX export failure: ONNX export failed: Couldn't export operator aten::threshold

### ISSUE THREAD

**Issue by zgd716** [pytorch/pytorch#51024]
ONNX export failure: ONNX export failed: Couldn't export operator aten::threshold

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by bdhirsh** [comment]
Hi @zgd716 . If you're filing a bug, could provide a repro of the issue? E.g. what you ran and the full log of the output, as well as the details of your environment (which you can get from this script: https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
