### ISSUE TITLE
Anaconda Repositories are offline

### ISSUE THREAD

**Issue by maf-hbdx** [pytorch/pytorch#51029]
## 🐛 Bug

It seems from my perspective that the pytorch channel for Anaconda is broken at the moment and no packages can be installed with conda.

Sorry, if this is the wrong place for this topic, wasn't sure.

## To Reproduce

1. Install any package from the pytorch channel with conda
```bash
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
```
2. Getting 500 errors for all repodata.json for the channel e.g.
`https://conda.anaconda.org/pytorch/win-64/repodata.json`
`https://conda.anaconda.org/pytorch/linux-64/repodata.json`

## Expected behavior

Successfull installation from the pytorch channel

## Environment

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
```

## Additional context

---

**Comment by andreynwix** [comment]
@maf-hbdx change the channel to conda-forge and it should work (thats how I fixed it)

**Comment by maresb** [comment]
I was just on Gitter with some Conda experts. They say that there is some problem with anaconda.org where all (non-default) channels cause a 500 Internal Server Error. The conda-forge channel is exempt because they have a separate CDN mirror in front of anaconda.org.

**Comment by maf-hbdx** [comment]
Direct install like `conda install https://conda.anaconda.org/pytorch/linux-64/pytorch-1.7.0-py3.8_cuda10.2.89_cudnn7.6.5_0.tar.bz2` still works for now.

**Comment by maresb** [comment]
I think it's working again now

**Comment by maf-hbdx** [comment]
Yes,  repodata.json is back online.

**Comment by maresb** [comment]
From https://gitter.im/conda/conda

> Re: the 500 errors - one of the worker nodes that backs all of the channels (except conda-forge and main) ran into a storage problem late last night. Anaconda IT has now resolved the situation.
