### ISSUE TITLE
RuntimeError: Input type (torch.cuda.ShortTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by ctwangtz** [pytorch/pytorch#51034]
class MeninDataset(Dataset):
    def __init__(self, root_dir):
        self.root_dir = root_dir
        self.images = os.listdir(self.root_dir)
        self.transform = transforms.Compose([transforms.ToTensor()])

    def __getitem__(self, index):  
   
        image_index = self.images[index]
        nrrd_data, _ = nrrd.read(self.root_dir + image_index)
        img = self.transform(nrrd_data)
  
        if self.images[index].split('.')[0][0] == 'l':
            lab = 0
        else:
            lab = 1
        return img, lab

    def __len__(self):
        return len(self.images)
train_data = MeninDataset(root_dir='./nrrd/')
ld_train = DataLoader(dataset=train_data, batch_size=1)
cuda = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

batch_size, input_size, hidden_size = 1, 2, 32
class ne0t(nn.Module):
    def __init__(self):
        super(ne0t, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2))
        self.flatten = nn.Flatten()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=2,
            bidirectional=True,  # fc input = hidden_size * 2
            batch_first=True)
        self.fc = nn.Sequential(
            nn.Linear(hidden_size * 2, 100),  # (16*16*16)+(32*8*8)
            nn.ReLU(inplace=True),
            nn.Linear(100, 2))
        # self.softmax = F.softmax(dim=1)

    def forward(self, x):
        for i in range(0, x[0].shape[0]):
            zz = torch.unsqueeze(x[0][i, :, :], dim=0)
            zz = torch.unsqueeze(zz, dim=0)
            print(zz.shape)
            locals()['out_' + str(i)] = self.flatten(self.conv1(zz))
            if i == 0:
                out = locals()['out_' + str(i)]
            else:
                out = torch.cat((out, locals()['out_' + str(i)]), 1)
        out = out.reshape(batch_size, -1, input_size)  # input: batch, seq_len输入的序列长度, input_size
        out, (_, _) = self.lstm(out, None)
        out = self.fc(out[:, -1, :])
        print(out)
        return out

Model = ne0t().to(cuda)
optimizer = optim.Adam(Model.parameters(), weight_decay=1e-4, lr=1e-3)
loss_function = nn.CrossEntropyLoss()
train_correct, test_correct, train_total, test_total = 0, 0, 0, 0
n_epoch = 5
loader_epoch, loader_train_acu, loader_test_acu = [], [], []

for epoch in range(1, 1 + n_epoch):
    for _, (train_x, train_y) in enumerate(ld_train):
        train_x = train_x.to(cuda)
        train_y = train_y.to(cuda)

        train_pred_y = Model(train_x)
        loss = loss_function(train_pred_y, train_y)  # 计算loss
        optimizer.zero_grad()
        loss.backward()  # loss 求导
        optimizer.step()  # 更新参数

        _, train_pred = torch.max(train_pred_y.data, 1)
        train_total += train_y.size(0)
        train_correct += (train_pred == train_y).sum().item()

**Comment by simaki** [comment]
Hi. This question is probably better asked on forums https://discuss.pytorch.org/.

**Comment by ctwangtz** [comment]
> Hi. This question is probably better asked on forums https://discuss.pytorch.org/.

THANKS~

**Comment by ctwangtz** [comment]
> Hi. This question is probably better asked on forums https://discuss.pytorch.org/.

close it, I have known how to solve this problem.
