### ISSUE TITLE
[ONNX] Missing sign operator when exporting Pytorch model to ONNX

### ISSUE THREAD

**Issue by teobaluta** [pytorch/pytorch#51033]
## 🐛 Bug

I would like to convert binarized neural networks trained in Pytorch [1] that have a BinarizeLinear layer extending the nn.Linear. However, when I tried to do so, I noticed that the model is missing the Binarize operation [2] which translates to tensor.sign(). I saw ONNX has support for Sign() so I wonder why it could not detect that the Binarize function (which is essentially a sign operation).

Is it that Binarize should be of some other type? What can I do to fix this?

[1] https://github.com/itayhubara/BinaryNet.pytorch
[2] https://github.com/itayhubara/BinaryNet.pytorch/blob/master/models/binarized_modules.py#L76

Is this issue related to a specific model?
*Binarized Neural Networks* (MNIST)

### Notes

I found this bug when I was trying to convert the model using the `pytorch2keras` package. I figured out that the problem was coming from this part of the conversion code so I reproduced it below (see the archive).

```
   input_names = ['input_{0}'.format(i) for i in range(len(args))]
    output_names = ['output_{0}'.format(i) for i in range(len(dummy_output))]

    logger.debug('Input_names:')
    logger.debug(input_names)

    logger.debug('Output_names:')
    logger.debug(output_names)

    stream = io.BytesIO()
    torch.onnx.export(model, args, stream, do_constant_folding=do_constant_folding, verbose=verbose, input_names=input_names, output_names=output_names)

    stream.seek(0)
    onnx_model = onnx.load(stream)
    onnx.checker.check_model(onnx_model)
    onnx.save(onnx_model, 'model.onnx')
    import netron
    netron.start('model.onnx')
    if use_optimizer:
        if use_optimizer is True:
            optimizer2run = optimizer.get_available_passes()
        else:
            use_optimizer = set(use_optimizer)
            optimizer2run = [x for x in optimizer.get_available_passes() if x in use_optimizer]
        logger.info("Running optimizer:\n%s", "\n".join(optimizer2run))
        onnx_model = optimizer.optimize(onnx_model, optimizer2run)
```
![image](https://user-images.githubusercontent.com/1837924/105674817-078b5d00-5f23-11eb-9da2-393374c6fd32.png)

## To Reproduce

Download the zip below, unzip archive in a folder and run `python bug_report.py`

[bug_report.zip](https://github.com/pytorch/pytorch/files/5866797/bug_report.zip)

# Install 

You can create a Python environment and install the requirements with `pip install -r requirements.txt`.

## Expected behavior

I would expect it to have a Sign operation before the 2nd MatMul & Reshape blocks.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 
 - Python version: 3.6.9
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

I have opened an [issue at the ONNX repository](https://github.com/onnx/onnx/issues/3236) as well. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@teobaluta - Did you see the export API call fail? If yes, could you also include the error stack? If the error is coming from pytorch2keras package, I would suggest checking if there's anything wrong with the exported ONNX model and reporting a repro for that.

**Comment by teobaluta** [comment]
No, I did not see the export API call fail.

I do not think it is coming from the `pytorch2keras` package -- I wrote a standalone conversion (please see attached zip) that does not depend on the `pytorch2keras` package and only uses the `export` call. 

Thanks!

**Comment by spandantiwari** [comment]
@teobaluta - You mentioned that the export call is not failing. Just to make sure that the model is indeed producing incorrect results, could you run the exported model in a ONNX backend, such as Onnx Runtime and check if the numbers match between PyTorch and the backend. If I am misunderstanding something and you have already done that, please let us know.

**Comment by KsenijaS** [comment]
@teobaluta Can you change the line 84 in binarized_modules.py:
```
input.data = Binarize(input.data)
```
into:
```
input = Binarize(input)
```

With this change I was able to match numbers between PyTorch and ORT and also Sign was part of the converted graph.
Please let me know if this works for you.

**Comment by teobaluta** [comment]
Oh, that solved it, thank you so much!
