### ISSUE TITLE
Measure Time for Back Pass in Each Module

### ISSUE THREAD

**Issue by FrankLeeeee** [pytorch/pytorch#51030]
Hi,

I am measuring time in both forward pass and backward pass in each module. For forward pass, it is easy as we can measure the time taken in the forward method. 

I am wondering what I should do if I want to do the same for the backward pass?

**Comment by bdhirsh** [comment]
Hi @FrankLeeeee , I'm going to refer you to the PyTorch forum for questions and close out this issue. Feel free to post your question there: https://discuss.pytorch.org/
