### ISSUE TITLE
[jit] ScriptModule attribute type annotation doesn't work for `Optional[List[int]] = None`

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#51041]
```
import torch
from typing import Optional, List


class ToScript(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.foo = torch.jit.annotate(Optional[List[int]], None)
        # also doesn't work
        # self.foo : Optional[List[int]] = None

    def forward(self, x: List[int]):
        self.foo = x
        return 1


torch.jit.script(ToScript())
```

Gives an error like:
```
Wrong type for attribute assignment. Expected None but got List[int]:
  File "/private/home/suo/scratch/test.py", line 13
    def forward(self, x: List[int]):
        self.foo = x
        ~~~~~~~~~~~~ <--- HERE
        return 1
```

cc @gmagogsfm

**Comment by suo** [comment]
Notes:

- `annotate()` is the wrong API to use here. It's intended to basically be a way of doing Python 2 backward-compatible inline type annotation in TS—it is implemented as equivalent to a static annotation in TorchScript and [doesn't do anything](https://github.com/pytorch/pytorch/blob/a389b30bfc12a22f12686c7be09693abd9604d80/torch/jit/__init__.py#L70) in Python. So the (very reasonable) usage here to annotate a type in `__init__` actually does nothing. This distinction is very subtle and not immediately obvious from the name of the function.
- `torch.jit.Attribute` is one way to do this, but the usability not great. In particular, it generally breaks the Python-compatibility of the function, because instead of, e.g. a `List`, the attribute will now be of type `torch.jit.Attribute(List)`, which will behave like a `List` in TS but not do anything in Python. I imagine this is a holdover from the inheritance-style scripting API where we could assume that once a module is scripted, it will never be used from Python again. 
- Type annotations in the class body are the only way we currently have of doing all the right things, e.g.
```
class Foo:
   attr: Optional[List[int]]
   def __init__(self):
       self.attr = None
```
- A more common way of doing instance attribute annotations is:
```
class Foo:
  def __init__(self):
    self.attr: Optional[List[int]] = None
```
but we do not support this.

**Comment by wconstab** [comment]
can we write a limited ast-walker that just checks for unsupported annotations to give a better user message?

**Comment by ansley** [comment]
@suo I was doing some experimenting, and I found some surprising behavior: it seems as though this error is thrown for any attribute container (e.g. `List`, `Dict`) initialized to a falsy value.

For example...

```python
# This throws the same error, because `self.foo` is empty

class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.foo: Dict[int, str] = {}

    def forward(self, x: Dict[int, str]):
        self.foo = x
        return 1
```

```python
# This works fine

class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.foo: Dict[int, str] = {1: "foo", 2: "bar", 3: "baz"}

    def forward(self, x: Dict[int, str]):
        self.foo = x
        return 1
```

Is this expected behavior? I can't find anything about it in the docs, and it seems a bit strange. I can still write an AST walker for all these cases, but I wanted to make sure it wasn't indicative of a larger issue.

**Comment by suo** [comment]
It's the same issue—because we do type inference based on attribute values, an empty dict alone is not enough to fully specify the type. The resolution in this case is the same as in my comment above—the user can either use `torch.jit.Attribute` or annotate the class body.
