### ISSUE TITLE
count_nonzero throwing isDifferentiableType runtime error on NN weight matrix

### ISSUE THREAD

**Issue by dfilan** [pytorch/pytorch#51073]
## 🐛 Bug

When I call `torch.count_nonzero` on the weight matrix of a simple neural network, I get an `isDifferentiableType(variable.scalar_type())` error, connected to an internal assert failing.

## To Reproduce

1. Initialize an MLP.
1. Call count_nonzero on the weights of a layer of the MLP

Code:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F

my_tensor = torch.rand(3,3)
print("Counting non-zeros of a random tensor")
print(torch.count_nonzero(my_tensor))

class MyMLP(nn.Module):
    """
    A simple MLP
    """
    def __init__(self):
        super(MyMLP, self).__init__()
        self.hidden1 = 512
        self.hidden2 = 512
        self.fc1 = nn.Linear(28 * 28, self.hidden1)
        self.fc2 = nn.Linear(self.hidden1, self.hidden2)
        self.fc3 = nn.Linear(self.hidden2, 10)

    def forward(self, x):
        x = x.view(-1, 28 * 28)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

my_net = MyMLP()
print("Counting non-zeros of a weight tensor")
print(torch.count_nonzero(my_net.fc1.weight))
```

Output:
```
Counting non-zeros of a random tensor
tensor(9)
Counting non-zeros of a weight tensor
Traceback (most recent call last):
  File "src/error_demonstration.py", line 30, in <module>
    print(torch.count_nonzero(my_net.fc1.weight))
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 
```

## Expected behavior

Showing me the number of non-zero elements of that weight tensor

## Environment

Output of `collect_env.py`:

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 940MX
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @mruberry

**Comment by kshitij12345** [comment]
This was fixed recently https://github.com/pytorch/pytorch/pull/50866
You can try the nightly to verify.
