### ISSUE TITLE
Why _LRScheduler is a private member?

### ISSUE THREAD

**Issue by harryhan618** [pytorch/pytorch#51071]
Why `_LRScheduler` is a private member? When I want to write a custom `_LRScheduler`, I need to inherit from this class. So it is quite confusing to make this class private.

**Comment by heitorschueroff** [comment]
Closing this issue as we reserve GitHub issues for feature requests and bug reporting. Please, post your question in our [Discussion Forum](https://discuss.pytorch.org/).
