### ISSUE TITLE
dyld: Symbol not found: _PyBaseObject_Type

### ISSUE THREAD

**Issue by IDwangluting** [pytorch/pytorch#51085]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @seemethere @walterddr

**Comment by heitorschueroff** [comment]
@IDwangluting Hi, could you please provide us with more information (output/traceback/etc) and the environment information.

**Comment by heitorschueroff** [comment]
Closing this as it's a duplicate from https://github.com/pytorch/pytorch/issues/51084

**Comment by IDwangluting** [comment]
when I build a pods for macApp, I assume that the link for /DLC/torch/libiomp5.dylib should be @rpath/libiomp5.dylib like it is for all of the other links in provided dylibs. and use 'install_name_tool -id @rpath/libiomp5.dylib libiomp5.dylib' to fixed, when I build agin,...(output/traceback/etc)



At 2021-01-27 06:29:27, "Heitor Schueroff" <notifications@github.com> wrote:

@IDwangluting Hi, could you please provide us with more information (output/traceback/etc) and the environment information.
