### ISSUE TITLE
Segmentation fault (core dumped) when import torch

### ISSUE THREAD

**Issue by Renzhihan** [pytorch/pytorch#51092]
## To Reproduce

1.
`import torch`
`Segmentation fault (core dumped)`

2.
`import cv2`
`import torch `
`Traceback (most recent call last):
File “”, line 1, in
File “/home/dji/.local/lib/python3.6/site-packages/torch/init.py”, line 190, in
from torch.C import *
ImportError: /home/dji/.local/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: sgesdd`

3.
`(gdb) r -c “import torch”`
`Starting program: /usr/bin/python3 -c “import torch”`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library “/lib/aarch64-linux-gnu/libthread_db.so.1”.`

## Environment

 - PyTorch Version (e.g., 1.0):1.7
 - OS (e.g., Linux):ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source):nvidia torch whl
 - Python version:3.6.9
 - CUDA/cuDNN version:10.2
 - Any other relevant information:nvidia tx2

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Thank you for reporting the issue, looks like Jetson wheels are not linked statically with blas library. Installing OpenBlas would likely resolve the issue. 
@ptrblck  , can you please let me know, who should be the right person to look into Jetson builds?

**Comment by ptrblck** [comment]
@dusty-nv was working on the Jetson wheels and would be the right person.
@Renzhihan your PyTorch version is reported as `1.7`. Are you using the latest `1.7.1` wheels or `1.7.0`?
In the latter case, could you check if this issue is still raised in `1.7.1`?

**Comment by dusty-nv** [comment]
@Renzhihan can you check this comment from the NVIDIA forums?

https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048/659?u=dusty_nv
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048/653?u=dusty_nv

This person had the same error message, and turned out to be some conflict with scipy.  Or are you perhaps the same person?

**Comment by Renzhihan** [comment]
@dusty-nv yes,I raised this issue at the same time in github and nvidai forums.I solved the problem at your suggestion。But I forgot this issue.Now I think I should close this issue.
@ptrblck @malfet Thanks for your attention.I'm sorry for my negligence
