### ISSUE TITLE
Don't use Unicode when output locale doesn't support it

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5109]
On HEAD with Python 3, when I say `print(x)` in a terminal where `LANG=en_US`, I get:

```
  File "train_test.py", line 69, in Lop
    print(xs)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u22ee' in position 5484: ordinal not in range(256)
```

The problem is our formatting generates a Unicode character and then we can't print it because the terminal isn't advertising support for it. Better to not generate Unicode in this case.

**Comment by vadimkantorov** [comment]
I've also had issues with IPython debugging: https://github.com/ipython/ipython/issues/10428, it didn't like to have the three-dot character in some circumstances

**Comment by ezyang** [comment]
Seems to be fixed now.
