### ISSUE TITLE
No magma-cuda80 for osx-64

### ISSUE THREAD

**Issue by gojira** [pytorch/pytorch#511]
Is this expected?  The conda install instructions for CUDA support mention "if OSX".

**Comment by soumith** [comment]
we haven't built MAGMA binaries for OSX.

If you are installing pytorch via conda on OSX, CUDA support is not built.

I've clarified the from-source instructions:
https://github.com/pytorch/pytorch/commit/30ec12fdd5ec6cc1cfc86ddfe0b4864d3d785faa

**Comment by gojira** [comment]
got it thanks
