### ISSUE TITLE
LayerNorm does not behave as documented

### ISSUE THREAD

**Issue by MrPr3ntice** [pytorch/pytorch#51102]
## 🐛 Bug

torch.nn.LayerNorm does not behave as documented. It fails for me especially for highly biased/mean-shifted layers. I can't figure out where this instability yields from as it occurs even for weakly mean-shifted layers:

## To Reproduce
```
n = torch.nn.LayerNorm(4, eps=1e-5, elementwise_affine=False)
a = torch.randn(5, 4) + 2000  # create random tensor with N=5, L/C=4 and mean=2000, var=1
[[torch.mean(i), torch.var(i, unbiased=False)] for i in n(a)]  # should be near [0, 1]
```
gives:
```
Out[255]: 
[[tensor(0.0002), tensor(0.2006)],
 [tensor(0.0002), tensor(0.1634)],
 [tensor(0.0625), tensor(30822.9492)],
 [tensor(0.0001), tensor(0.0491)],
 [tensor(-0.2500), tensor(48425.8438)]]
```

## Expected behavior
```
def expected_LayerNorm(single_layer1d, eps):
    c = single_layer1d
    return (c - torch.mean(c)) / (torch.sqrt(torch.var(c, unbiased=False).add(eps)))

# comparison for one sample of a
print(n(a[2, :]))
print(expected_LayerNorm(a[2, :], 1e-5))
```
gives:
```
tensor([  22.0000,   72.7500, -285.0000,  190.5000])
tensor([ 0.1249,  0.4133, -1.6235,  1.0852])
```

## Environment
1.7.1+cpu (pip)
Win10

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry

**Comment by PkuRainBow** [comment]
+1

**Comment by MrPr3ntice** [comment]
Seems to be (among others) a problem of floating point precision, as this does not occur with:

`a = torch.randn(5, 4).double() + 2000`

Nethertheless, as shown in the **Expected behaviour** example, the precision does not fully explain the early instability. Maybe the sequence of operations in the layer_norm cpp-implementation is suboptimal (just guessing without having sighted).

**Comment by ezyang** [comment]
@ngimel agrees it should be able to handle 2000-to-1 ratio even when floating point, so we should look into this.

**Comment by ezyang** [comment]
It would also be good to check if this instability affects CUDA too

**Comment by xiaomengy** [comment]
https://github.com/pytorch/pytorch/pull/59987 should fix this issue. Please feel free to reopen it if there are any other related issues.
