### ISSUE TITLE
`var` and `std` don't support all-reductions for complex or half tensors on CPU

### ISSUE THREAD

**Issue by peterbell10** [pytorch/pytorch#51127]
## 🐛 Bug
`var` and `std` use the legacy TH implementation for all-reductions. 
https://github.com/pytorch/pytorch/blob/3562ca2da23d5e283bbfe61fc99d415b522f8bcc/aten/src/ATen/native/ReduceOps.cpp#L1151-L1156

But this special case skips the complex handling code added in #27653, so all-reductions fail in cases where single-dimension reductions work.

## To Reproduce
```python
import torch
a = torch.rand(100, dtype=torch.complex64)
a.var()
```
raises
```
RuntimeError: _th_var not supported on CPUType for ComplexFloat
```

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by ngimel** [comment]
@mruberry attempted to move `var` and `std` from TH to TensorIterator, but existing non-vectorized reduction kernels are very slow.
see #40570

**Comment by mruberry** [comment]
> @mruberry attempted to move `var` and `std` from TH to TensorIterator, but existing non-vectorized reduction kernels are very slow.
> see #40570

@heitorschueroff expects to review the performance of ATen CPU reductions and these ports in Q2 2021.
