### ISSUE TITLE
autograd.detect_anomaly docs incorrectly formatted

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#51141]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/5652049/105903649-273b8780-5fee-11eb-9d56-189acd96dea2.png)

The two bullet points don't render as bullet points.

https://pytorch.org/docs/master/autograd.html?highlight=anomaly#torch.autograd.detect_anomaly

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @jlin27 @mruberry

**Comment by Marcopollom** [comment]
Hello everyone, I'm new to contributing and would love to help out and fix this issue. Is there anything I should do before I begin working on this bug?

**Comment by lacrosse91** [comment]
Hi, can I handle this?
I'd like to help!

**Comment by zou3519** [comment]
@lacrosse91 go for it! There are instructions on how to build the docs here: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#building-documentation

**Comment by lacrosse91** [comment]
Thank you!
I will try it!
