### ISSUE TITLE
Incorrect error message reported during DDP tests

### ISSUE THREAD

**Issue by skyline75489** [pytorch/pytorch#51172]
## To Reproduce

1. On a machine with 2 GPUs, run the DDP tests using `python test/run_test.py --verbose -i distributed/test_c10d`

The error message is misleading regarding insufficient CUDA devices:

```plaintext
test_gloo_backend_1gpu_module_device_ids_torch_device_list (__main__.DistributedDataParallelTest) ... ok
test_gloo_backend_2gpu_module (__main__.DistributedDataParallelTest) ... skipped 'Need at least 2 CUDA devices'
test_gloo_backend_4gpu_module (__main__.DistributedDataParallelTest) ... skipped 'Need at least 2 CUDA devices'
test_gloo_backend_cpu_module (__main__.DistributedDataParallelTest) ... ok
test_gloo_backend_cpu_module_grad_is_view (__main__.DistributedDataParallelTest) ... ok
```

## Environment

OS: Microsoft Windows 10 Enterprise Insider Preview
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.16.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080

Nvidia driver version: 456.71
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @mruberry @VitalyFedyunin @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by malfet** [comment]
Thank you for reporting.  We will accept PR that fixes the issue.
@mrshenli, do you know why test called test_gloo_backend_2gpu_module requires 4 GPUs and test_gloo_backend_4gpu_module requires 8? Unless I'm reading following incorrectly:
https://github.com/pytorch/pytorch/blob/33d5180684cf92fb9f512d8dddc76d0b6940264f/test/distributed/test_c10d.py#L2337-L2338

**Comment by skyline75489** [comment]
@malfet This confused me also. I asked @mrshenli about it. I'm quoting his answer:

> The model used in test_gloo_backend_2gpu_module spans two GPUs, and then on top of that runs DDP with world_size=2 . So, it needs 4 GPUs in total

**Comment by Blackhex** [comment]
Closing as the message for the `test_gloo_backend_2gpu_module` test is correctly `Need at least 4 CUDA devices` now. Please reopen with a description if some further change is required.
