### ISSUE TITLE
[JIT] Tuple assignment doesn't work when unpacking values to class attributes

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#51176]
## 🐛 Bug

Following code snippet fails

```
import torch

def pass_through(a: int, b: int):
    return (a, b)

class JitClass:
    def __init__(self, a: int, b: int):
        self.a, self.b = pass_through(a, b)

    def get(self):
        return self.a + self.b

@torch.jit.script
def fn(a: int, b: int):
    o = JitClass(a, b)
    return o.get()
```

Error:

```
RuntimeError:
lhs of assignment must be a variable, subscript, or starred expression:
  File "self_attr.py", line 8
    def __init__(self, a: int, b: int):
        self.a, self.b = pass_through(a, b)
        ~~~~~~ <--- HERE
```

This exception is thrown from here: [[link](https://github.com/pytorch/pytorch/blob/e2041ce3540a08dcdc70eaef86b13ca84b31ebd5/torch/csrc/jit/frontend/ir_emitter.cpp#L2021)]

I think this can be fixed by handling the case where assignee is a `select` expression (like `self.a`)

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
This seems to be a dup of #28303.

@SplitInfinity have you started working on it? if so, could you share findings? If not, I can try to tackle it as there are now a few requests on this issue

**Comment by SplitInfinity** [comment]
I have not started, feel free to take it.
