### ISSUE TITLE
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.

### ISSUE THREAD

**Issue by ForrestPi** [pytorch/pytorch#51196]
code blew

#d.shape([4, 2304, 3, 3])
dd=torch.norm(d,dim = (2,3))

when training some while , error happens

return _VF.frobenius_norm(input, _dim, keepdim=keepdim)
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output. 

 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by malfet** [comment]
@ForrestPi can you please run `python3 -m torch.utils.collect_env` and share it's output here?
And looks like an expected behavior of autograd if `d` contains nan values

**Comment by ForrestPi** [comment]
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Debian GNU/Linux 9.11 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.14.7

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 418.116.00
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.6.0+cu101
[pip3] torchfile==0.1.0
[pip3] torchtext==0.4.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] facenet-pytorch           2.5.1                    pypi_0    pypi
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.14           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.17.2           py37haad9e8e_0
[conda] numpy-base                1.17.2           py37hde5b4d6_0
[conda] numpydoc                  0.9.1                      py_0
[conda] pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] pytorch3d                 0.3.0                    pypi_0    pypi
[conda] torchvision               0.7.0                py37_cu101    pytorch

after update pytorch version to 1.7.1
change the code blew:
#d.shape([4, 2304, 3, 3])
dd=torch.linalg.norm(d,dim = (2,3))
Now it works well


Thanks @malfet

**Comment by albanD** [comment]
Hi,

This error is only here in anomaly mode to help you find where nans appeared in the backward pass. This is not related to a bug in PyTorch but just that your current code generate nan values.
You can remove this error by just disabling anomaly detection.

Now if you want help to figure out why you have nans in your model, you can ask your question on our forum https://discuss.pytorch.org/ and provide a code sample to reproduce the issue there!
