### ISSUE TITLE
Quantized model cannot be pickled and reused after.

### ISSUE THREAD

**Issue by adefossez** [pytorch/pytorch#51216]
## 🐛 Bug

Taking the static quantization example from the official doc, and adding a pickling and unpickling stage before evaluation:

```python
# This is all from the doc: https://pytorch.org/docs/stable/quantization.html#static-quantization
import torch

# define a floating point model where some layers could be statically quantized
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        # QuantStub converts tensors from floating point to quantized
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(1, 1, 1)
        self.relu = torch.nn.ReLU()
        # DeQuantStub converts tensors from quantized to floating point
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        # manually specify where tensors will be converted from floating
        # point to quantized in the quantized model
        x = self.quant(x)
        x = self.conv(x)
        x = self.relu(x)
        # manually specify where tensors will be converted from quantized
        # to floating point in the quantized model
        x = self.dequant(x)
        return x

# create a model instance
model_fp32 = M()

# model must be set to eval mode for static quantization logic to work
model_fp32.eval()

# attach a global qconfig, which contains information about what kind
# of observers to attach. Use 'fbgemm' for server inference and
# 'qnnpack' for mobile inference. Other quantization configurations such
# as selecting symmetric or assymetric quantization and MinMax or L2Norm
# calibration techniques can be specified here.
model_fp32.qconfig = torch.quantization.get_default_qconfig('fbgemm')

# Fuse the activations to preceding layers, where applicable.
# This needs to be done manually depending on the model architecture.
# Common fusions include `conv + relu` and `conv + batchnorm + relu`
model_fp32_fused = torch.quantization.fuse_modules(model_fp32, [['conv', 'relu']])

# Prepare the model for static quantization. This inserts observers in
# the model that will observe activation tensors during calibration.
model_fp32_prepared = torch.quantization.prepare(model_fp32_fused)

# calibrate the prepared model to determine quantization parameters for activations
# in a real world setting, the calibration would be done with a representative dataset
input_fp32 = torch.randn(4, 1, 4, 4)
model_fp32_prepared(input_fp32)

# Convert the observed model to a quantized model. This does several things:
# quantizes the weights, computes and stores the scale and bias value to be
# used with each activation tensor, and replaces key operators with quantized
# implementations.
model_int8 = torch.quantization.convert(model_fp32_prepared)

# run the model, relevant calculations will happen in int8
res = model_int8(input_fp32)

## Extra step for the bug: save with torch and load before evaluating.
torch.save(model_int8, 'plop.th')
model = torch.load('plop.th')
model(input_fp32)
```

## To Reproduce

1. Run the above code

Error:
```
Traceback (most recent call last):
  File "plop.py", line 62, in <module>
    model(input_fp32)
  File "/Users/defossez/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "plop.py", line 18, in forward
    x = self.conv(x)
  File "/Users/defossez/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 718, in _call_impl
    self._forward_pre_hooks.values()):
  File "/Users/defossez/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ConvReLU2d' object has no attribute '_forward_pre_hooks'
```

## Expected behavior

Expected the model to be usable after pickling.

## Environment

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0
CMake version: version 3.19.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py38hfbe908c_0
[conda] mkl_fft                   1.2.0            py38hc64f4ea_0
[conda] mkl_random                1.1.1            py38h959d312_0
[conda] numpy                     1.19.1           py38h3b9f5b6_0
[conda] numpy-base                1.19.1           py38hcfb5961_0
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    pytorch

## Extra context

I believe the error might be due to the quantized module not calling the super class method `__setstate__`, e.g. see https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/conv.py#L146

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by adefossez** [comment]
For context, while it is usually not a good idea to pickle a model, this is useful to do multiprocessor based evaluation on CPU, as quantized model cannot be evaluated on GPU, where using the `state_dict` would be overkill and require redoing the quantization procedure on each child process.

For the record, a quick but dirty fix is to define the following on the toplevel module:
```python
    def __setstate__(self, state):
        super().__setstate__(state)
        mods = list(self._modules.values())
        from collections import OrderedDict
        while mods:
            mod = mods.pop(0)
            if '_forward_pre_hooks' not in mod.__dict__:
                mod._forward_pre_hooks = OrderedDict()
            if '_forward_hooks' not in mod.__dict__:
                mod._forward_hooks = OrderedDict()
            if '_backward_hooks' not in mod.__dict__:
                mod._backward_hooks = OrderedDict()
            if '_state_dict_hooks' not in mod.__dict__:
                mod._state_dict_hooks = OrderedDict()
            if '_load_state_dict_pre_hooks' not in mod.__dict__:
                mod._load_state_dict_pre_hooks = OrderedDict()
            if '_non_persistent_buffers_set' not in mod.__dict__:
                mod._non_persistent_buffers_set = set()
            if '_modules' not in mod.__dict__:
                mod._modules = OrderedDict()
            mods += list(mod._modules.values())
```

**Comment by jerryzh168** [comment]
This is a known issue I think, @dskhudia might have more context on this

**Comment by dskhudia** [comment]
Currently the following two methods should work for saving quantized models: 
1) Save float model state dictionary and for loading it again, restore float model dictionary and follow the quantization steps again 
2) Script/trace quantized model and store/load with torch.jit.save/torch.jit.load

Currently on quantized model with linear/conv torch.save or copy.deepcopy doesn't work.

**Comment by adefossez** [comment]
Thanks, why not include something like the above fix? It seems to work okay and would make things easier for research purposes. Getting code to work with torchscript is a significant amount of work and rerunning the quantization logic in every worker seems a bit wasteful. I understand this is probably low pri though.

**Comment by jerryzh168** [comment]
I think the recommended path for saving nn.Module is:
```
torch.save(float_model.state_dict())
torch.save(quantized_model.state_dict())
```
Could you try this and let us now if this works?

This should also work:
```
scripted_model = torch.jit.scrpit(quantized_model)
torch.jit.save(scripted_model)
```

`torch.save(quantized_model)` is not recommended path.
