### ISSUE TITLE
[Docs] Example for torch.nn.functional.conv1d throws an error

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#51225]
## 📚 Documentation
The given example in https://pytorch.org/docs/stable/nn.functional.html#conv1d throws an error

```
>>> filters = torch.randn(33, 16, 3)
>>> inputs = torch.randn(20, 16, 50)
>>> F.conv1d(inputs, filters)
>>> RuntimeError: Calculated padded input size per channel: (3). Kernel size: (50). Kernel size can't be greater than actual input size
```

cc @jlin27 @mruberry @albanD @jbschlosser

**Comment by omarelshehy** [comment]
I ran the same code on a terminal and it spits out the same error. However, when i run a python script it worked fine. 
this the first case (Terminal):
>>> import torch.nn.functional as F
>>> inputs = torch.randn(33,16,3)
>>> filters = torch.randn(20,16,50)
>>> F.conv1d(inputs, filters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Calculated padded input size per channel: (3). Kernel size: (50). Kernel size can't be greater than actual input size

Second case : ( Script with a print statment of F.conv1d(inputs,filters).shape )
torch.Size([20, 33, 48])

**Comment by harishsdev** [comment]
fixed here https://github.com/pytorch/pytorch/pull/57356
