### ISSUE TITLE
Pytorch can't use cuda because torch.cuda returns nothing

### ISSUE THREAD

**Issue by anbeegod** [pytorch/pytorch#51230]
Hi, it's my first time posting here.

I'm trying to set up Pulse AI which matches a face with another face. I used it on an older PC previously which worked nicely, but after I try to install it on a new PC, it doesn't work anymore, and I pinpointed the problem at torch.cuda. **(Please skip to the bold lines if you're not interested in the background.)**

Pulse AI has two major files, align_face.py and PULSE.py. align_face.py detects a face and transforms it into a small file. It used to run in a few seconds. PULSE.py matches the file generated by align_face.py with another face. It used to run in 90 seconds and regardless of its quality, provided results.

Now, align_face.py takes 5 minutes to run, and PULSE.py takes 15 minutes to run and never provided any result.

After some debugging attempt (by adding print("test") after every suspicious line, if the test doesn't print or takes very long to print, then that line has problem; yes, I'm a newbie in Python), I found that in align_face.py

`face_tensor = torchvision.transforms.ToTensor()(face).unsqueeze(0).cuda()`

is what slows it down.

In PULSE.py it is, surprise,

`self.synthesis = G_synthesis().cuda()`

_**After hours of googling I found that cuda could be the issue. And it is proven because in the test.py file I made**_

```
import torch

torch.cuda.current_device()
torch.cuda.device(0)
torch.cuda.device_count()
torch.cuda.get_device_name(0)
torch.cuda.is_available()
```
_**return nothing. Google says at least torch.cuda.is_available() should return true or false, but it returns really nothing. Type python test.py and hit enter, then it is like this**_

```
(pulse) E:\pulse>python test.py

(pulse) E:\pulse>
```
Tried installing cuda manually then also reinstalled Pytorch. _**Same result.**_ Obviously, torch or cuda was not installed properly or cuda has some problem that I wasn't sure about, but I've tried _every way_ to install them that I found on google and other websites and no one seems to have encountered such an issue.

Would appreciate your help with this.

**Comment by skyline75489** [comment]
You need to use ‘print’ for it to output to the console. Try print everything then you’ll see what’s happening.

**Comment by anbeegod** [comment]
Oops, definitely didn't expect that XD Thought the function already includes print. Thanks for your help!!

**Comment by ailzhang** [comment]
Closing via https://github.com/pytorch/pytorch/issues/51230#issuecomment-768607389. Please feel free to reopen if you see other issues.
