### ISSUE TITLE
[tests][UnaryUfuncInfo] Improve TestUnaryUfuncs for ops with args/kwargs

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#51242]
Currently, we can not fully test "clamp" op added to common_methods_invocations.py as UnaryUfuncInfo (see https://github.com/pytorch/pytorch/pull/51167) as it requires additional args as `min` and `max` but there are tests that call the op directly on a test input without passing any args/kwargs. For example:
```python
# test_unary_ufuncs.py

    @ops(unary_ufuncs)
    def test_batch_vs_slicing(self, device, dtype, op):
        input = make_tensor((1024, 512), dtype=dtype, device=device,
                            low=op.domain[0], high=op.domain[1])

        actual = op(input)  # <---- this will fail with RuntimeError: At least one of 'min' or 'max' must not be None
        expected = torch.stack([op(slice) for slice in input])

        self.assertEqual(actual, expected)

```

In test_ops.py, test samples are generated with `samples = op.sample_inputs(device, dtype)` and op is called with its args/kwargs:
```python
output = op(*sample.input, *sample.args, **sample.kwargs)
```

The drawback of this approach is that : 
> other tests like that rely on the structure of their input, but a sample input can be very arbitrary

Let's talk about the details of workarounds here.

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
We could add metadata to the unary ufuncs that need these additional kwargs and change the test to call:

```
actual = op(input, **op.sample_kwargs(device, dtype))
```

For most unary ufuncs "sample_kwargs()" would always return an empty dict, but for clamp it could return a dict with dtype-appropriate min and max values.

**Comment by kshitij12345** [comment]
Wouldn't same thing used in test_op suffice?
```python
output = op(*sample.input, *sample.args, **sample.kwargs)
```

Adding
```

**Comment by mruberry** [comment]
The tests want to construct an input tensor with a particular structure, which is why they don't want to use a sample input, just sample kwargs.
