### ISSUE TITLE
Wrong argument name of index_fill_

### ISSUE THREAD

**Issue by loveritsu929** [pytorch/pytorch#51250]
## 📚 Documentation

https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_fill_

The third argument should be called `value` instead of `val`, like all other methods in `torch.Tensor`.

Using `val` throws an error and the error message indicate this should be `value` in the background implementation:
`* (name dim, Tensor index, Tensor value)
      didn't match because some of the keywords were incorrect: val`

cc @jlin27 @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @loveritsu929. We would accept a PR fixing this.
