### ISSUE TITLE
Is there any way to do a fast connect between each tensors

### ISSUE THREAD

**Issue by Woodrow1026** [pytorch/pytorch#51264]
In my work, I'm comparing two sentences, and after encoding, they are Batchsize x Sequencelength x D tensors. I want to connect each word in sentence1 with the words in sentence2, like if I got 1 word in sentence1, and there are 3 word in sentence2, I'll get 3 new tensors which is connect between the word in sentence1 and words in sentence2.

Is there any way to do this?

**Comment by Woodrow1026** [comment]
can i get some help?

**Comment by ailzhang** [comment]
Hi, per instructions in the template, please redirect all questions to pytorch forums instead. Thanks a lot!
