### ISSUE TITLE
Key changes between pytorch 1.7.1(stable) & pytorch 1.8

### ISSUE THREAD

**Issue by Ankita-020696** [pytorch/pytorch#51277]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hi,
What are key changes between pytorch 1.7.1(stable) & pytorch 1.8?

Thanks

**Comment by ailzhang** [comment]
Hi Pytorch 1.8 is current master branch which is being developed. We haven't released 1.8 yet. 1.7 is the current latest stable release. Hope this answers your question.
