### ISSUE TITLE
Profiler is stuck for DDP training

### ISSUE THREAD

**Issue by topshik** [pytorch/pytorch#51279]
## 🐛 Bug

I have an adopted knowledge distillation script from https://github.com/facebookresearch/XLM which I have used a lot for training new models. However, when I decided to profile it with `torch.autograd.profiler.profile` I faced my program being stuck on `torch.distributed.barrier()`, so profiler endlessly waits in `.../torch/distributed/launch.py", line 253, in main
    process.wait()`

## To Reproduce

My training script looks like this:
```
# train.py
...
from distiller import Distiller

def main():
    # load configuration file
    # load teacher and student models to GPU
    # create dataloaders
    distiller = Distiller(<params, loaders>)  # class for distillation from repo above
    with torch.autograd.profiler.profile(use_cuda=True, profile_memory=True, with_stack=True) as prof:
        distiller.train()
    print(prof.key_averages().table(sort_by="self_cpu_time_total"))

    # distiller.train()
```

I have had a bit of debug going deeper into `.train()` method and here how it looks like:
```
# distiller.py
class Distiller(<params>):
    def __init__():
        ...
     def train(self):
        if self.is_master:
            logger.info("Starting training")
        self.last_log = time.time()
        self.student.train()
        self.teacher.eval()

        for _ in range(self.params.n_epoch):
            if self.is_master:
                logger.info(
                    f"--- Starting epoch {self.epoch}/{self.params.n_epoch - 1}"
                )
            if self.multi_gpu:
                print("We went this far")
                torch.distributed.barrier()
            print("We can't get here")
```

I have also tested it in the DDP mode with single GPU (i.e. only with master process). Both debug prints are reachable in such setup.
## Expected behavior

All training procedure runs just fine if I comment out profiling section and just execute `distiller.train()`. I would expect profiler just to record some information while training and not get stuck on barriers. It could be either for main process (local rank 0) or for each of the individual processes.

## Environment

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.13.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: Tesla M60
GPU 1: Tesla M60

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[conda] Could not collect

**Comment by aaronenyeshi** [comment]
Profiler has been greatly improved and re-written, please give the latest nightly a try. Thank you.
