### ISSUE TITLE
torch.unique leads to "RuntimeError: isDifferentiableType" when used in loss function

### ISSUE THREAD

**Issue by sambaPython24** [pytorch/pytorch#51271]
Hello, when I use the ```.unique``` function in PyTorch
as suggested in [this post](https://stackoverflow.com/questions/55110047/finding-non-intersection-of-two-pytorch-tensors) 
```
combined = torch.cat((t1, t2))
uniques, counts = combined.unique(return_counts=True)
difference = uniques[counts == 1]
intersection = uniques[counts > 1]
```
and try to use it in a custom *loss function*, I get the following error
```
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "..\\torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by ailzhang** [comment]
Marking as high pri since it hits internal assert but the use case looks valid.

**Comment by ezyang** [comment]
What version of PyTorch? Pretty sure @albanD fixed this one on master

**Comment by sambaPython24** [comment]
Hey, it is 
```
print(torch.__version__)
1.7.1
```
and it is run on a CPU. Do you need any other information?

**Comment by albanD** [comment]
This has been fixed in master in https://github.com/pytorch/pytorch/pull/47930
You can use a nightly build to get the fix right now. Or wait for the upcoming 1.8 release.
