### ISSUE TITLE
scatter_ with passed `reduce=` argument to support integer inputs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#51323]
I ran it on int64 tensor and got
`RuntimeError: scatter_(): Expected floating or complex type for self.`

**Comment by ailzhang** [comment]
Hi, would you mind providing a repro? Thanks!

**Comment by vadimkantorov** [comment]
```python
# example from docs
z = torch.zeros(2, 4, dtype = torch.int32).scatter_(1, torch.tensor([[2], [3]]), 1) # works

z = torch.zeros(2, 4, dtype = torch.int32).scatter_(1, torch.tensor([[2], [3]]), 1, reduce="add")
# RuntimeError: scatter_(): Expected floating or complex type for self.
```

**Comment by vadimkantorov** [comment]
in a recent nightly this is fixed.

is `scatter_` with provided `reduce="add"` or `reduce="multiply"` equivalent to `scatter_reduce_` calls? does it just alias to `scatter_reduce_`?
