### ISSUE TITLE
ONNX export of atan2

### ISSUE THREAD

**Issue by sailorbj** [pytorch/pytorch#51334]
## 🐛 Bug
Try converting torch model to onnx, atan2 is not supported.

RuntimeError: Exporting the operator atan2 to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np

class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.layer = torch.nn.Linear(1, 1)

   def forward(self, x):
       x = self.layer(x)
       x = torch.atan2(x, torch.tensor(1.0))   
       return x
net = Net()
print(net)

x = np.random.rand(100)
y = np.sin(x) * np.power(x,3) + 2*x + np.random.rand(100)*0.8

x = torch.from_numpy(x.reshape(-1,1)).float()
y = torch.from_numpy(y.reshape(-1,1)).float()

optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
loss_func = torch.nn.MSELoss()
inputs = Variable(x)
outputs = Variable(y)
for i in range(100):
   prediction = net(inputs)
   loss = loss_func(prediction, outputs) 
   optimizer.zero_grad()
   loss.backward()
   optimizer.step()
   print(i, loss.detach().numpy())

inputs = torch.randn([2, 1]) 
input_names = ["input"]
output_names = ["output"]
onnx_filename = "./model_regression.onnx"
torch.onnx.export(net, inputs, onnx_filename,
	verbose=True, input_names=input_names, output_names=output_names,
	opset_version=9)`

## Expected behavior

Want to convert torch model to onnx then to tflite.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchaudio-contrib==0.1
[pip3] torchcontrib==0.0.2
[pip3] torchvision==0.8.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.0.221             h6bb024c_0    defaults
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.2.0            py38h23d657b_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] numpy-base                1.19.2           py38hfa32c7d_0    defaults
[conda] pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchaudio-contrib        0.1                      pypi_0    pypi
[conda] torchcontrib              0.0.2                    pypi_0    pypi
[conda] torchvision               0.8.1                py38_cu110    pytorch

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by geaxgx** [comment]
Same problem with pytorch 1.18.0.

**Comment by AnnonymousRacoon** [comment]
+1

**Comment by OliverFM** [comment]
Getting this issue in 1.9.0 too :/

**Comment by bluoluo** [comment]
torch 1.9 ，Same problem

RuntimeError: Exporting the operator atan2 to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by robereng** [comment]
Much needed fix this - any update would be great

**Comment by speshowBUAA** [comment]
try to replace atan2(A, B) with atan(A / (B+1e-6))

**Comment by mrhe13** [comment]
Any improvement?

**Comment by shubhambhokare1** [comment]
PR https://github.com/pytorch/pytorch/pull/89094 should resolve. Will close when this merged into master.
