### ISSUE TITLE
Set torch.profiler.profile.activities a default value

### ISSUE THREAD

**Issue by guyang3532** [pytorch/pytorch#51337]
## 🚀 Feature
Set torch.profiler.profile.activities a default value when both arguments "activities" and "use_gpu" are not specified by user.

## Motivation
To refine default action of the profiler API and improve user experience.

## Pitch

In the torch.profiler.profile.__init__() function ,if use_gpu is None and activities is None , it will raise an RuntimeError:https://github.com/pytorch/pytorch/blob/master/torch/profiler/profiler.py#L145

We think it would be better to give self.activities a default value, rather than throw exception when both arguments are not specified, especially since use_gpu is deprecated.
```
if use_gpu is None:
    self.activities = set([ProfilerActivity.CPU])
    if torch.cuda.is_available():
        self.activities.add(ProfilerActivity.CUDA)
```

@ilia-cher @gdankel @maxluk @nbcsm @gaoteng-git

**Comment by ilia-cher** [comment]
Agree that the default value would be good to add. My only question though - in the previous API, by default it was CPU only, do we have to include CUDA? Some points:
 - if/when we add more activity/device types, CPU+CUDA might become somewhat an arbitrary choice and we won't be able to easily change the default behavior;
 - there're hidden costs (in this case CUDA/CUPTI) when user adds something other than CPU, and the user might not know it and wouldn't expect e.g. some CUPTI activity in the background (e.g. we have an internal 'prepare' method in Kineto to start the warm up) when the profiled code is CPU only

**Comment by gdankel** [comment]
> Agree that the default value would be good to add. My only question though - in the previous API, by default it was CPU only, do we have to include CUDA? Some points:
> 
> * if/when we add more activity/device types, CPU+CUDA might become somewhat an arbitrary choice and we won't be able to easily change the default behavior;
> * there're hidden costs (in this case CUDA/CUPTI) when user adds something other than CPU, and the user might not know it and wouldn't expect e.g. some CUPTI activity in the background (e.g. we have an internal 'prepare' method in Kineto to start the warm up) when the profiled code is CPU only

Comparing only CPU with CPU+CUDA, I'd think that CPU+CUDA is a better default when cuda is available?

Regarding the hidden costs, that may be a valid concern depending on the use case. But the counter argument is that if they enable CUDA then they are still likely to be surprised by this.
What is the default for warmup iterations?

**Comment by ilia-cher** [comment]
there's no default warmup, unless you specify a schedule argument

**Comment by nbcsm** [comment]
I agree with @gdankel , "use CPU+CUDA when CUDA is available" seems can better fit user's assumption.

**Comment by guyang3532** [comment]
Resolved by https://github.com/pytorch/pytorch/commit/d6452a1a0cbc308939f8c597c68a1f5f212dc8b8
