### ISSUE TITLE
gcc 4.8.5 -std=11  how to build pytorch1.7

### ISSUE THREAD

**Issue by joinhe** [pytorch/pytorch#51339]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

i want to use gcc4.8.5 to make pytorch1.7 code 
What should i do on torch1.7.

on torch1.2 usr gcc4.8.5 is ok! but torch 1.7 is  bad!

**Comment by skyline75489** [comment]
I think the minimum version supported GCC 5.

**Comment by ezyang** [comment]
We're on C++14 so unfortunately gcc4.8 is no good. You will have to upgrade your compiler, or keep using an older version of PyTorch.

**Comment by joinhe** [comment]
> We're on C++14 so unfortunately gcc4.8 is no good. You will have to upgrade your compiler, or keep using an older version of PyTorch.

older version of PyTorch. torch1.2
 
in my code  Memory leak
