### ISSUE TITLE
Pytorch DataLoader freezes when num_workers > 0 in jupyter notebook(windows 10)

### ISSUE THREAD

**Issue by mobassir94** [pytorch/pytorch#51344]
i am facing exactly this same issue : https://github.com/pytorch/pytorch/issues/15808  in windows 10,

i used, anaconda virtual environment where i have, 
* python 3.8.5
* pytorch 1.7.0
* cuda 11.0 
* cudnn 8004
* gpu rtx 3060ti 
* Is CUDA available: Yes 

related post : https://stackoverflow.com/questions/63674120/pytorch-dataloader-hangs-when-num-workers-0

and https://discuss.pytorch.org/t/training-freezes-when-using-dataloader-with-num-workers-0/34055/5

i got no help for this problem since last 9 days,so re posting about it here!

cc @ngimel @SsnL @VitalyFedyunin @ejguan @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by ezyang** [comment]
do you think https://github.com/pytorch/pytorch/issues/12831 related?

**Comment by ejguan** [comment]
I have seen lots of issues related to python multiprocssing on Windows. As there is no `fork` on windows platform, the `if __name__ == '__main__'` is needed to ensure the construction of DataLoader with multiple processes under "singleton mode" in your script.
I would love to provide suggestions if you could share a self-contained script which we could use to reproduce this issue.
You can checkout the https://docs.python.org/3/library/multiprocessing.html#programming-guidelines for reference.

**Comment by mobassir94** [comment]
@ezyang  @ejguan 
i am using exactly this notebook in windows : https://www.kaggle.com/khyeh0719/pytorch-efficientnet-baseline-train-amp-aug
you can see that there the kernel author already used if __name__ == '__main__' 

i am running exactly that same notebook,,,i just added extra line : 

`torch.backends.cudnn.benchmark = True
`
and everything else is same as that notebook,,i had to use num_workers = 0 to make it work(which is extremely slow),,if i try num_workers>1

then the training gets stuck here : 

`for step, (imgs, image_labels) in pbar:`

i used several print statements to catch and ensure that it gets stuck there.
you can reproduce my result with that notebook and with this exact setting : 

1. python 3.8.5
2. pytorch 1.7.0
3. cuda 11.0
4. cudnn 8004
5. gpu rtx 3060ti
6. Is CUDA available: Yes

but you will have to download that dataset though :(

**Comment by mobassir94** [comment]
@ejguan 

**update (temporary fix) :** 

i just used spyder instead of jupyter inside same virtual environment and the code runs fine with spyder and with non zero num_workers but it doesn't work in jupyter notebook, probably this one is related https://github.com/pytorch/pytorch/issues/17680 

i prefer jupyter notebook,so how can i make it working in jupyter notebook? 

i used` if __name__ == '__main__'`  but it doesn't solve my issue.

**Comment by mobassir94** [comment]
with num_worker>0 i get this new strange error : https://github.com/pytorch/pytorch/issues/51418

**Comment by mszhanyi** [comment]
Sorry， python multiprocessing doesn't work on notebook, so I don't think num_workers > 0 can work in notebook.
https://stackoverflow.com/questions/23641475/multiprocessing-working-in-python-but-not-in-ipython

**Comment by mobassir94** [comment]
@mszhanyi when i tried it on syder ide,it worked there with number of workers  > 0 but it gradually increase memory usage and give OOM after few epochs,,even if i set 2 workers only,it will give me OOM and consume all memory,how to fix this? if i use 0 workers then everything works fine but training becomes painfully slow

**Comment by ejguan** [comment]
@mobassir94 
I am not an expert for notebook, but I suggest to try to put your code into a separate file and import it to your script, then call it within `if __name__ == '__main__'`.

> when i tried it on syder ide,it worked there with number of workers > 0 but it gradually increase memory usage and give OOM after few epochs,,even if i set 2 workers only,it will give me OOM and consume all memory,how to fix this? if i use 0 workers then everything works fine but training becomes painfully slow

Can you share a minimum script for me to reproduce the OOM? It's too hard to read through your code. I would suggest to delete data loader and create a new one after each epoch. As I am not sure how you implement your dataset, it's possible that some reference on the data within the computation graph prevents PyTorch cleaning the cache.

**Comment by abdulsalam-bande** [comment]
I had the same problem, I downgraded to Python 3.6 and It worked.

**Comment by mszhanyi** [comment]
> I had the same problem, I downgraded to Python 3.6 and It worked.

Interesting. I don't believe it can work with Python 3.6. could you please provide a minimum reproducible script.

**Comment by mszhanyi** [comment]
If we have to run Pytorch Dataloader with multi-workers on Windows Notebook. One workaround is start Jupyter server in windows WSL and start browser to connect it.
I wrote a tool (https://github.com/mszhanyi/gemini) to simplify the process.

**Comment by talhaanwarch** [comment]
Here is comparison of same data loaded on same pc but in two different os ie windows and linux
**Windows 10**
Finish with:80.83345198631287 second, num_workers=2
Finish with:78.34166359901428 second, num_workers=4
Finish with:90.41332364082336 second, num_workers=6
Finish with:108.79571604728699 second, num_workers=8
Finish with:131.13191103935242 second, num_workers=10
Finish with:152.95715427398682 second, num_workers=12
Finish with:177.89760422706604 second, num_workers=14
error

**Ubuntu**
Finish with:89.55736088752747 second, num_workers=2
Finish with:32.361040115356445 second, num_workers=4
Finish with:26.830809116363525 second, num_workers=6
Finish with:26.47123146057129 second, num_workers=8
Finish with:26.320005416870117 second, num_workers=10
Finish with:25.773979663848877 second, num_workers=12
Finish with:25.343995571136475 second, num_workers=14
Finish with:25.439622402191162 second, num_workers=16
Finish with:25.520018339157104 second, num_workers=18
Finish with:26.797677516937256 second, num_workers=20
Finish with:24.817006826400757 second, num_workers=22

**Comment by halqadasi** [comment]
> Here is comparison of same data loaded on same pc but in two different os ie windows and linux **Windows 10** Finish with:80.83345198631287 second, num_workers=2 Finish with:78.34166359901428 second, num_workers=4 Finish with:90.41332364082336 second, num_workers=6 Finish with:108.79571604728699 second, num_workers=8 Finish with:131.13191103935242 second, num_workers=10 Finish with:152.95715427398682 second, num_workers=12 Finish with:177.89760422706604 second, num_workers=14 error
> 
> **Ubuntu** Finish with:89.55736088752747 second, num_workers=2 Finish with:32.361040115356445 second, num_workers=4 Finish with:26.830809116363525 second, num_workers=6 Finish with:26.47123146057129 second, num_workers=8 Finish with:26.320005416870117 second, num_workers=10 Finish with:25.773979663848877 second, num_workers=12 Finish with:25.343995571136475 second, num_workers=14 Finish with:25.439622402191162 second, num_workers=16 Finish with:25.520018339157104 second, num_workers=18 Finish with:26.797677516937256 second, num_workers=20 Finish with:24.817006826400757 second, num_workers=22

Did you run the code on jupyter notebook or terminal?

**Comment by thistlillo** [comment]
The problem is not windows. My dataloader freezes on linux.

**Comment by furrycoding** [comment]
This is why there should be an option to use `threading` for prefetch workers instead of `multiprocessing`.
Considering that (at least in my experience) most of the data loading is simply IO operations, GIL should hardly be a problem for threading performace

**Comment by erikjsun** [comment]
I'm still having this issue. I've searched around extensively, but haven't seen anyone find a satisfying answer. I'd really prefer to keep using my Jupyter Notebook setup, seems silly that I need to change away from the best ML development tool (Jupyter Notebook), only to make full use of another vital tool (multiprocessing in DataLoader) in ML. 

Anyone has any new ideas/angles on this in 2023?

**Comment by erikjsun** [comment]
I'm still having this same issue as described by OP. I've searched around extensively, but haven't seen anyone find a satisfying answer. I'd really prefer to keep using my Jupyter Notebook setup, seems silly that I need to change away from the best ML development tool (Jupyter Notebook), only to make full use of another vital tool (multiprocessing in DataLoader) in ML.

Anyone has any new ideas/angles on this in 2023?

**Comment by anna244** [comment]
try to reduce number of `DataLoader.num_workers`

**Comment by abdulsalam-bande** [comment]
I think it is more like a Python Problem. The combination of ** Python 3.7.0 + torch 1.9.0** always work for me.

**Comment by eromoe** [comment]
The initial guess of hang is  by enviroment or packages version balabala... it cost me 3 hours to figure out this issue result to hang ,  this is a strange behaviour since my other pytorch notebook work fine.

**Comment by EricThomson** [comment]
I have done a lot of work with this, and for years I would get errors or intolerable hanging in Windows trying to get things working in Jupyter Lab, now things work really well when I set `persistent_workers` to True. 

```
working_loader = DataLoader(dataset, 
                           num_workers=4,
                           batch_size=12,
                           persistent_workers=True)
```
The values are arbitrary for `batch_size` and `num_workers`, but the key parameter is `persistent_workers`. 

On Windows, there will still be a very long slowdown on the first epoch when everything is initializing (this is because Windows uses `spawn` instead of `fork` to generate processes). But with `persistent_workers` it doesn't have to go through that with every new epoch, so things go really quickly after that initial setup process. It's definitely worth it. 

I recommend first trying the following quick test in Jupyter: 

```
from torch.utils.data import DataLoader, TensorDataset

data = torch.randn(100, 10)
labels = torch.randint(0, 2, (100,))
dataset = TensorDataset(data, labels)

def test_dataloader(num_workers):
    try:
        dataloader = DataLoader(dataset, batch_size=10, num_workers=num_workers)
        for batch in dataloader:
            pass
        print(f"Success with num_workers = {num_workers}")
    except Exception as e:
        print(f"Failed with num_workers = {num_workers}: {e}")

for num_workers in range(0, 5):
    test_dataloader(num_workers)
print("\nDone running!")
```

If the above runs without issues, then I think you are good to go with the above `working_loader`. You'll just need to tweak `batch_size` and `num_workers` in your environment to find the best run times.

**Comment by nov05** [comment]
`Windows` OS, in the terminal (I use `PowerShell`) run `python -m webdataset_ddp`.  
It works. However, multiple works don't speed up data loading.   
And in Jupyter notebook, I got errors.   

```python
%%writefile webdataset_ddp.py
## test code SageMaker DDP + Torch DDP
import webdataset as wds
import matplotlib.pyplot as plt
from PIL import Image
import io
import torch
from torchvision import transforms
from torch.utils.data import DataLoader, IterableDataset
# from torch.utils.data.distributed import DistributedSampler  ## ⚠️
import numpy as np
import time

import multiprocessing as mp
print("👉 Multiprocessing start method:", mp.get_start_method(allow_none=True))
if mp.get_start_method(allow_none=True) != 'spawn':
    torch.multiprocessing.set_start_method('spawn')  ## ⚠️

def key_transform(x):
    return int(x)

class image_transform:
    def __call__(self, x):
        return Image.open(io.BytesIO(x))
    
train_transform = transforms.Compose([
    image_transform(),
    transforms.RandomResizedCrop(224),
    transforms.ToTensor(),
])  

def label_transform(x):
    return torch.tensor(int(x.decode()))

class WebDatasetDDP(IterableDataset):
    def __init__(self,
                 path, 
                 *args, 
                 num_samples=0, world_size=1, rank=0, 
                 **kwargs):
        super().__init__(*args, **kwargs)
        self.dataset = (
            wds.WebDataset(
                path, 
                shardshuffle=True,
                # nodesplitter=wds.split_by_worker,
                empty_check=False, 
            )
            .shuffle(1000)  # Shuffle dataset 
            ## The tuple names have to be the same with the WebDataset keys
            ## check the "scripts_process/*convert_to_webdataset*.py" files
            .to_tuple("__key__", "image", "label")  ## Tuple of image and label
            .map_tuple(
                key_transform,
                train_transform,  # Apply the train transforms to the image
                ## lambda function can't not be pickled, hence cause error when num_workers>1 
                label_transform,  
            )
        )
        self.num_samples = num_samples
        self.world_size = world_size
        self.rank = rank
    
    def __len__(self):
        ## Returning the number of samples
        return self.num_samples
    
    def __iter__(self): 
        for key,image,label in self.dataset:
            if key%self.world_size == self.rank:  ## Ensure each GPU gets different data
                yield (image, label)

def collate_fn(batch):
    images, labels = zip(*batch)
    images = [torch.tensor(np.array(image)) for image in images] 
    # Stack the images into a single tensor (this assumes the images have the same size)
    images = torch.stack(images)
    labels = torch.tensor(labels)
    return images, labels

def main():
    s3_uri = "s3://p5-amazon-bin-images/webdataset/train/train-shard-{000000..000000}.tar"
    path = f"pipe:aws s3 cp {s3_uri} -"  ## write to standard output (stdout)
    train_dataset = (
        WebDatasetDDP(path, num_samples=1000, world_size=2, rank=0)
    ) 
    # ## ⚠️ DistributedSampler doesn't work with IterableDataset
    # train_sampler = DistributedSampler(
    #     train_dataset,
    #     num_replicas=2,  ## number of GPUs
    #     rank=0,  ## global rank
    #     shuffle=False,
    #     drop_last=True,
    # )
    train_loader = DataLoader(
        train_dataset, 
        batch_size=int(256/2),  ## 2 GPUs 
        shuffle=False,  ## Don't shuffle for Distributed Data Parallel (DDP)  
        # sampler=train_sampler, # Use the Distributed Sampler ⚠️ Cause error
        # num_workers=2, # ⚠️ Cause error in windows
        # persistent_workers=True,
        pin_memory=True,
        collate_fn=collate_fn,
    )
    for batch_idx, batch in enumerate(train_loader):
        print(batch_idx, len(batch[0]), len(batch[1]))
        
if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
    print(f"👉 Execution Time: {end_time-start_time} seconds")

## $ python -m webdataset_ddp
## On Windows...
## 8 workers, 31.25 s
## 4 workers, 29.26 s
## 2 workers, 29.40 s
## 1 workers, 20.52 s
```
