### ISSUE TITLE
autograd.grad with set_detect_anomaly(True) will cause memory leak

### ISSUE THREAD

**Issue by ventusff** [pytorch/pytorch#51349]
## 🐛 Bug

using `torch.autograd.grad()` with `torch.autograd.set_detect_anomaly(True)` will cause memory leak

## To Reproduce

Run the code snippet below.
It will have about 2MiB GPU memory consumption increasing each iteration.

If comment out the `set_detect_anomaly` line, then there is no memory leak, with constant memory consumption.

```python
import torch
torch.autograd.set_detect_anomaly(True) # if comment out this, no leak
for rep in range(1000):
    batch = torch.ones(10, 30000).cuda().requires_grad_()
    y=batch.norm()
    grad = torch.autograd.grad(
        outputs=y, inputs=batch,
        create_graph=True, retain_graph=True, only_inputs=True)[0]
    print("memory allocated:", float(torch.cuda.memory_allocated()/1024**2), "MiB")
    pass
```

## Expected behavior

No memory leak with or without `set_detect_anomaly(True)`

## Environment

 - PyTorch Version: 1.7.1
 - OS: Linux
 - How you installed PyTorch: conda, source: `-c pytorch`
 - Python version: 3.8.5
 - CUDA/cuDNN version: cuda11.0

## Additional context

BTW, if replace `y=batch.norm()` with `y=batch.mean()`, then there is no memory leak with or without `set_detect_anomaly`, which makes me very confused.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by khalilsarwari** [comment]
Thank you so much for catching this!!

**Comment by albanD** [comment]
Note that setting `create_graph=False` also fixes the issue, so most likely a special interaction between these two.

**Comment by albanD** [comment]
cc @mfkasim1 I think this is related to https://github.com/pytorch/pytorch/pull/43626 but not sure how exactly yet.

**Comment by soulitzer** [comment]
@albanD I think your suspicions are correct. I've created a PR that /should/ fix this. At the very least we know its purely a python thing bc the following doesn't leak:

```
#include <c10/cuda/CUDACachingAllocator.h>

torch::autograd::DetectAnomalyGuard detect_anomaly;
for(int i = 0; i < 10; i++) {
  auto x = torch::ones({10, 30000}).cuda().requires_grad_();
  auto y = x.exp();
  auto grad = torch::autograd::grad({y}, {x}, {torch::ones_like(y)}, true, true);

  auto stats = c10::cuda::CUDACachingAllocator::getDeviceStats(0);
  std::cout << "allocated: " << stats.allocated_bytes[0].current / (1024 * 1024) << std::endl;
}

```

**Comment by StalVars** [comment]
In my case, I also observed that 'set_detect_anomaly(True)' makes the forward pass much slower.

**Comment by soulitzer** [comment]
That is expected @StalVars 

https://github.com/pytorch/pytorch/blob/790cc8f2591bc0bef30303ce9a9829b75d70ac65/torch/csrc/autograd/anomaly_mode.h#L24-L32

The performance hit is because on the creation of every node of the backward graph extra metadata, e.g. current stack trace of the forward execution is stored.
