### ISSUE TITLE
torch.script crashes with Union type

### ISSUE THREAD

**Issue by nunoplopes** [pytorch/pytorch#51347]
## 🐛 Bug

torch.script crashes with Union type given to an argument.

## To Reproduce

```python
import torch
from typing import *

def f(a : Dict[str, Union[torch.Tensor, int]]):
  return a['foo'][..., 1:] + 2

fn = torch.jit.script(f)
print(fn({'foo':torch.Tensor(1,5)}))
```
## Environment

 - PyTorch Version: tried 1.7.0-py3.7_cuda10.1.243_cudnn7.6.3_0 & 1.7.0+cpu
 - OS: ubuntu
 - How you installed PyTorch: tried both conda & pip
 - Python version: tried 3.7.9 & 3.8.6

cc @gmagogsfm

**Comment by nunoplopes** [comment]
FYI type annotation `Dict[str, object]` also craches.

**Comment by ezyang** [comment]
IIRC Union doesn't work on TorchScript but someone is working on adding support for it.

**Comment by eellison** [comment]
This crash is fixed on master. As @ezyang, someone is working on adding Union support.
