### ISSUE TITLE
torch.nn.functional.adaptive_avg_pool3d and torch.nn.AdaptiveAvgPool3d aborts when input is of integral type

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#51352]
## 🐛 Bug

`torch.nn.functional.adaptive_avg_pool3d`  and `torch.nn.AdaptiveAvgPool3d` aborts when `input` contains negative number

## To Reproduce
~~~python
import torch
input = torch.tensor([[[[[-1]]]]])
torch.nn.functional.adaptive_avg_pool3d(input=input, output_size=1)
~~~

~~~python
import torch
torch.nn.AdaptiveAvgPool3d(1)( torch.tensor([[[[[-1]]]]]))
~~~

Output:
~~~python
terminate called without an active exception
Aborted (core dumped)
~~~

## Expected behavior

expect no crash

## Environment

PyTorch version: 1.8.0.dev20210126+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry

**Comment by XiaobingSuper** [comment]
For AdaptiveAveragePooling, it is only support float or half tensor, if input is not float of half tensor, there will report a error: **RuntimeError: "adaptive_avg_pool3d_cpu" not implemented for 'Long'**, thanks!

**Comment by albanD** [comment]
Hi,

Not working for integer type makes sense as you are doing averaging and the error message is appropriate. I don't think we want to change that.

We should make sure that we never crash though as reported in the original post.

**Comment by DNXie** [comment]
@albanD 
Sure. An appropriate error message sounds better than crash. Thanks!
