### ISSUE TITLE
[proposal] Forbid tensor.flatten(single_non_kwarg) if feasible

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#51361]
It is not very intuitive when just reading the code, what is the semantics: `tensor.flatten(end_dim=single_non_kwarg)` or `tensor.flatten(start_dim=single_non_kwarg)`. Currently it seems that it's the latter. It's less of a problem when both arguments are used (or if a single kwarg is used)

cc @ezyang @gchanan

**Comment by gchanan** [comment]
probably not worth doing the BC-breaking change on as the semantics are explained by the signature.

**Comment by vadimkantorov** [comment]
And probably not feasible in Python :(
