### ISSUE TITLE
Perf regression for YoloV3 CUDA eager train

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#51383]
approx 25% regression observed on nightly builds between 12/29/20 and 1/28/20

cc @ngimel @VitalyFedyunin

**Comment by wconstab** [comment]
note- 1/28 and 1/29 CI data is suspect as the wrong CI configuration was used on those days, but keep watching this one as resumed (presumed correct) 2/3 CI data still doesn't revert to the previous best performance level.

**Comment by gottbrath** [comment]
can this one be closed?

**Comment by wconstab** [comment]
yes, it went back to 'normal' for many days now; closing
