### ISSUE TITLE
Perf regression for demucs cpu eval

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#51381]
approx 28% regression observed on nightly builds between 12/29/20 and 1/28/21

cc @VitalyFedyunin @ngimel

**Comment by ezyang** [comment]
These will be more actionable if you can identify a specific commit that induced the regression

**Comment by wconstab** [comment]
yep, we're working on it. @xuzhao9 kicked off a data-collection attempt over the weekend but needs to do some analysis. eventually we hope to automate this with a bisect job..

**Comment by wconstab** [comment]
Closing this issue as CI data from 1/28 and 1/29 were collected using the wrong CI configuration and resumed CI data on 2/3 aligns with previous data - looks like a false alarm.

**Comment by malfet** [comment]
@wconstab, no it was not a false alarm, as far as I remember issue correctly pinpointed date when MKLDNN library support was dropped by build script error.

**Comment by xuzhao9** [comment]
@malfet The noisy data points Will mentioned happened on 1/28 and 1/29. The MKLDNN regression happened between 1.8.0.dev20210113 (b54240d) and 1.8.0.dev20210114(19a8e68), which is not included in the current dataset.
