### ISSUE TITLE
Ship pre-made ltrace.conf lenses for PyTorch, cublas, cudnn

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#51411]
This would help lightweight debugging/tracing a lot on restricted university machines without root/ptrace permissions (as in https://github.com/pytorch/pytorch/issues/51382), cc @ngimel @csarofeen @ptrblck @xwang233

**Comment by ngimel** [comment]
`ltrace` does not work with statically linked libraries, and since pytorch binary builds statically link against cuda libraries, it won't help. Cudnn provides logging info similar to ltrace, I'm not sure if latest versions of cublas do. cc @ptrblck

**Comment by vadimkantorov** [comment]
At least, let's document suggestions of cudnn and cublas logging in the docs and maybe into CUDA exception messages directly? (at least a url?)

If debugging symbols are preserved, would ltrace work? Maybe distributing a separate debugging version of PyTorch with tracing enabled may be a good idea for crazy debugging cases especially in restricted environments

**Comment by ptrblck** [comment]
Yes, cublas provides a similar logging mechanism as cudnn via [these env vars](https://docs.nvidia.com/cuda/cublas/index.html#cublasLoggerConfigure).
The usage is the same as in cudnn logging besides the name changes in the env vars:
```shell
/workspace/src# cat tmp.py
import torch

x = torch.randn(100, 100).cuda()
y = torch.matmul(x, x)

/workspace/src# CUBLAS_LOGINFO_DBG=1 CUBLAS_LOGDEST_DBG=stdout python tmp.py

I! cuBLAS (v11.2) function cublasStatus_t cublasCreate_v2(cublasContext**) called:
i!  handle: type=cublasHandle_t; val=POINTER (IN HEX:0x0x5558fde7d810)
i! Time: 2021-02-01T09:50:34 elapsed from start 0.033333 minutes or 2.000000 seconds
i!Process=730; Thread=140185093887808; GPU=0; Handle=POINTER (IN HEX:0x(nil))
i! COMPILED WITH: GNU GCC/G++ / 5.3.1 20160406 (Red Hat 5.3.1-6)
I! cuBLAS (v11.2) function cublasStatus_t cublasSetStream_v2(cublasHandle_t, cudaStream_t) called:
i!  handle: type=cublasHandle_t; val=POINTER (IN HEX:0x0x555940572980)
i!  streamId: type=SOME TYPE; val=POINTER (IN HEX:0x(nil))
...
```

**Comment by vadimkantorov** [comment]
I guess this can be closed. Maybe resurrected e.g. for `libtorch.so`'s own exported functions, for some basic TorchCpp debugging...
