### ISSUE TITLE
init_process_group changes the behavior of logging

### ISSUE THREAD

**Issue by char256** [pytorch/pytorch#51428]
When running init_process_group, Python library's logging is changed, as I show in the screenshot
![Screenshot from 2021-01-31 10-17-57](https://user-images.githubusercontent.com/16537232/106378747-0f934300-63e2-11eb-8893-b3e123e48346.png)
This happens when I was using OpenSelfSup, a library made by CUHK, and the log disappeared. Because the framework use 'hasHandlers' function to judge whether the logging level is 'WARNING' or 'INFO', this behavior makes the logger level be 'WARNING' , all 'INFO' disappeared.
I don't know this is a bug or I did things wrong,
When I changed the source code version to 1.7.1 and recompile it again, this behavior was fixed.

# Enviroment
pytorch version: compiled from source, master branch
CUDA used to build Pytorch: 11.2
Python: 3.8.5
OS: ubuntu 2004
GPU: GeForce RTX 3090

Thanks so much for your attention.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by szmigacz** [comment]
I'm seeing the same issue in my codebase. I believe that it's due to https://github.com/pytorch/pytorch/commit/16e5af41dab3a64072d88d76003dd9c2aa49d4bc which added (bare) logging calls to init_process_group.
