### ISSUE TITLE
Incorrect return type hint for torch.nonzero

### ISSUE THREAD

**Issue by nlgranger** [pytorch/pytorch#51434]
## 🐛 Bug

The type hint for torch.nonzero is incomplete, it only specifies Tensor.

## To Reproduce

1. Call torch.nonzero with `as_tuple=True`
```
a, b = torch.nonzero(torch.randn(10, 10), as_tuple=True)
```
2. Run a static type checker such as pyright
3. There is a warning

## Expected behavior

There is no warning

## Additional context

https://github.com/pytorch/pytorch/blob/9dfbfe9fca39a21560ae856348856837eaaf849a/tools/pyi/gen_pyi.py#L326 should be like so:
```
                    'def nonzero(input: Tensor, *, as_tuple: bool=...) -> Union[Tensor, Tuple[Tensor, ...]]: ...'],
```

And Tensor.nonzero might need to be updated too I suppose.

cc @mruberry @rgommers @heitorschueroff @ezyang @malfet @xuzhao9 @gramster

**Comment by rgommers** [comment]
Thanks for the report @nlgranger.

`Tensor.nonzero` is missing on purpose: https://github.com/pytorch/pytorch/issues/42998#issuecomment-674059144

> `-> Union[Tensor, Tuple[Tensor, ...]]`

That isn't quite right, returning unions like that will just cause problems further down the line where mypy doesn't know if it's a tensor or a tuple. Instead it should have an extra overload (`Literal[True]` and `Literal[False]`)to disambiguate `as_tuple=True` and `as_tuple=False`.
