### ISSUE TITLE
SpeedUp and Compressing of the Computing

### ISSUE THREAD

**Issue by Lr-2002** [pytorch/pytorch#51448]
## 📚 Documentation

Hello,I'm now doing some work to read the resources of torch,It's really fantastic.
However ,partcipating in a project to solve the real problem,i found the compressing of models to the mobile is not all very easy and not all of them work effectively .
I'm interested in whether can we use the trained model and weights to summarize a clear and light formula to predict?
Hoping for your support and help to make it a useful tool!

**Comment by H-Huang** [comment]
Please look into our various domain libraries: [torchaudio](https://pytorch.org/audio/stable/index.html), [torchvision](https://pytorch.org/docs/stable/torchvision/), [torchtext](https://pytorch.org/text/0.8.1/index.html) for pretrained models that fit your use case.
