### ISSUE TITLE
Does the Transformer need two layernorm layers?

### ISSUE THREAD

**Issue by lartpang** [pytorch/pytorch#51447]
https://github.com/pytorch/pytorch/blob/40c0fffb4bb4a7d49cb50c6b276565aa60b3daaf/torch/nn/modules/transformer.py#L50-L62

In these code, ` encoder_norm = LayerNorm(d_model)` & `decoder_norm = LayerNorm(d_model)` will make the `TransformerEncoder` & `TransformerDecoder` append a norm layer 

https://github.com/pytorch/pytorch/blob/40c0fffb4bb4a7d49cb50c6b276565aa60b3daaf/torch/nn/modules/transformer.py#L180-L184

and

https://github.com/pytorch/pytorch/blob/40c0fffb4bb4a7d49cb50c6b276565aa60b3daaf/torch/nn/modules/transformer.py#L230-L237

But the norm layer is already used at the end of `TransformerEncoderLayer` & `TransformerDecoderLayer`.

so, it is not necessary to use a norm layer here:
https://github.com/pytorch/pytorch/blob/40c0fffb4bb4a7d49cb50c6b276565aa60b3daaf/torch/nn/modules/transformer.py#L50-L62

cc @zhangguanheng66

**Comment by jbschlosser** [comment]
Same as #24930?

**Comment by lartpang** [comment]
> Same as #24930?

It's indeed the same problem, but it doesn't seem to fix the issue.

**Comment by jbschlosser** [comment]
Closing as duplicate. Please continue discussion on #24930.
