### ISSUE TITLE
Thread safety for inference of torch::jit::Module ?

### ISSUE THREAD

**Issue by w1d2s** [pytorch/pytorch#51452]
Hello, I want to know is it safe to call forward inference or other custom jit exported methods of one torch::jit::Module instance from multiple threads ? Especially when some mutable internal states  exist in model.  Thanks.

cc @gmagogsfm

**Comment by eellison** [comment]
If you have concurrent writes to the model as part of inference, it may not be thread safe. Otherwise yes it is. You might consider using [torchbind](https://pytorch.org/tutorials/advanced/torch_script_custom_classes.html) to implement a mutex in your model

**Comment by w1d2s** [comment]
# #
