### ISSUE TITLE
Will pytorch run faster with AVX instruction set ?

### ISSUE THREAD

**Issue by Just-A-Coder27** [pytorch/pytorch#51466]
Will pytorch get faster with avx? if yes, then how will it get faster and if no, then any tips on how to make it faster? I will be running it on CPU.

Every answer will be appreciated...

**Comment by malfet** [comment]
By default, PyTorch already accelerated with AVX and AVX2. And please use https://discuss.pytorch.org/ to ask general questions about PyTorch and use GitHub issue to submit bugs/feature requests.
