### ISSUE TITLE
Rephrase `use_deterministic_algorithms` documentation for backward functions

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#51487]
Currently, in the the documentation for `use_deterministic_algorithms`, some entries in the list of affected operations use the phrase "when called on a tensor that requires grad" to indicate that the flag affects the backward function for the corresponding operation. The intended meaning of this phrase is not immediately apparent. It would probably be much clearer to explicitly state that the backward function is affected, using the word "backward".

Relevant discussion: https://github.com/pytorch/pytorch/pull/51388/files#r567441181

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @mruberry @kurtamohler @jlin27

**Comment by mruberry** [comment]
cc @albanD to help with the language.
