### ISSUE TITLE
storage resize_ function 

### ISSUE THREAD

**Issue by mingminzhen** [pytorch/pytorch#5154]
I try to use torch.storage in my network. 

```
if self.storage.size() < size:
            is_cuda = self.storage.is_cuda
            if is_cuda:
                gpu_ID = self.storage.get_device()
                print('gpu_ID1:',gpu_ID)
            self.storage.resize_(size)
            
            gpu_ID= self.storage.get_device()
            print('gpu_ID2:',gpu_ID)
            
            if is_cuda:
                self.storage = self.storage.cuda(gpu_ID)
            gpu_ID= self.storage.get_device()
            print('gpu_ID3:',gpu_ID)
```

The output is 
```
gpu_ID1: 1
gpu_ID2: 0
gpu_ID3: 0

```
The self.storage comes from ``` self.storage= torch.Storage(1024)```.
It seems the **resize_** function will change the gpu where the storage will be saved.
I wish the storage is saved in GPU 1 rather than 0. 
How can i do that?

**Comment by ezyang** [comment]
I don't know if this is a bug or not, but you can probably work around it by using the `torch.cuda.device` context manager http://pytorch.org/docs/master/cuda.html#torch.cuda.device

**Comment by gchanan** [comment]
this works now.
