### ISSUE TITLE
Making .t() work for tensor of high dimensions

### ISSUE THREAD

**Issue by justanhduc** [pytorch/pytorch#51540]
## 🚀 Feature
Currentlly, `x.t()` works only when `x` is 1D or 2D. Why don't we make it work with multi-dimensional tensors as well by transposing the last two dimensions. 

## Motivation

To make it inline with `torch.matmul` and some other functions that consider the last two dimensions as matrices.
To avoid verbosity in code such as `x.transpose(-1, -2)` or `torch.permute`.

## Pitch

```
x = torch.rand(2, 3, 4, 5, 6)
y = x.t()  # returns a tensor of shape (2, 3, 4, 6, 5)
```

## Additional context

If this feature looks ok to you, I will try to work on a PR.
Thanks!

**Comment by kshitij12345** [comment]
I think is a duplicate of #51280

**Comment by justanhduc** [comment]
@kshitij12345 right! I will close this in favor of the existing one.
