### ISSUE TITLE
Nans in matrix multiplication on ARM

### ISSUE THREAD

**Issue by mdouze** [pytorch/pytorch#51559]
## 🐛 Bug

A simple matrix multiplication (ran twice) produces an output matrix with NaNs. 

Code+output: https://gist.github.com/mdouze/a4bbd9b08b827cf725d99a33d5f6835f

## To Reproduce

1. reserve a c6g.8xlarge instance on AWS
1. install a docker image w/ pytorch 1.6 from https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/aarch64-docker-images-for-pytorch-and-tensorflow
1. run the script from the paste above in the docker image

## Expected behavior

No NaNs in output matrix

## Environment

python collect_env.py
```
aarch64_pytorch tmp> python collect_env.py
Collecting environment information...
PyTorch version: 1.6.0a0+b31f58d
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (aarch64)
GCC version: (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0a0+b31f58d
[pip3] torchvision==0.2.2.post3
[conda] Could not collect
```

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by malfet** [comment]
@mdouze can you please try https://download.pytorch.org/whl/nightly/cpu/torch-1.8.0.dev20201210-cp38-cp38-linux_aarch64.whl ?
And I guess it's due to the bug in implementation of missing NEON intrinsics, that was fixed by  https://github.com/pytorch/pytorch/pull/50389

**Comment by mdouze** [comment]
Thanks! That new version works!
