### ISSUE TITLE
confusing docs for `add` and maybe some other functions

### ISSUE THREAD

**Issue by zym1010** [pytorch/pytorch#5156]
in <http://pytorch.org/docs/master/torch.html#torch.add>, there are two overloaded variations.

* `torch.add(input, value, out=None)`
* `torch.add(input, value=1, other, out=None)`

But in practice I believe there are more, as shown in the error message below, by trying `torch.add(a,b,c)`, where all three are `FloatTensor` of the same shape.

~~~
TypeError: torch.add received an invalid combination of arguments - got (torch.FloatTensor, torch.FloatTensor, torch.FloatTensor), bu
t expected one of:
 * (torch.FloatTensor source, float value)
 * (torch.FloatTensor source, torch.FloatTensor other)
 * (torch.FloatTensor source, torch.SparseFloatTensor other)
 * (torch.FloatTensor source, float value, torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor, torch.FloatTensor, torch.FloatTensor)
 * (torch.FloatTensor source, float value, torch.SparseFloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor, torch.FloatTensor, torch.FloatTensor)
~~~

also, my test seems to suggest that `out` is a keyword-only argument. Otherwise, how can the library tell apart the two variations in the doc?

**Comment by apaszke** [comment]
There are more combinations of types you can pass in, but there are only two different signatures. `out` is a keyword only argument.

**Comment by zym1010** [comment]
@apaszke  I want to say two more things.

1. `torch.add(input, value=1, other, out=None)` doesn't look like a Pythonic signature. Default value should always come last.
2. `out` is keyword only in pytorch but not in numpy, and this difference can confuse people. In addition, this keyword only behavior is not well documented.

I can help with 2 by a PR. Not sure what to do with 1.

**Comment by apaszke** [comment]
I think we’ll just leave the signature as is. Changing it would be hard and possibly breaking backward compatibility, and the value argument is rarely used

**Comment by zym1010** [comment]
@apaszke I think I'm not requesting a compatibility-breaking change. I just want the doc to reflect actual API. A signature with default value in the middle is just impossible.

**Comment by apaszke** [comment]
It is possible and you can verify that the signature is in fact as shown in the docs.

**Comment by zym1010** [comment]
@apaszke nope. at least, there's some inaccuracy in the doc.

for example, you can do `torch.add(a,a)` where `a` is a `FloatTensor`. In both versions of the variations, the second `a` should fill in the role of `value`. However, by doc, `value` should be a scalar.

**Comment by zym1010** [comment]
probably it's clearer to have

* `torch.add(input, other, out=None)`
* `torch.add(input, value, out=None)`
* `torch.add(input, value, other, out=None)`

**Comment by apaszke** [comment]
If you do this, the first two overloads are identical

**Comment by zym1010** [comment]
> If you do this, the first two overloads are identical

So I think it's easier to replace the current first overload with `torch.add(input, other, out=None)`, add specify that `other` can be both a `Number` or `Tensor`.
