### ISSUE TITLE
[JIT] Support Union[NoneType, T] as input type

### ISSUE THREAD

**Issue by esqu1** [pytorch/pytorch#51582]
## 🐛 Bug

While `Union` is not supported yet in TorchScript, it would be tremendously useful to have support for `Union[None, ...]`. This is because the `Optional[T]` type annotation is just an alias to `Union[None, T]`, and prior to Python 3.9, `__repr__` for `Union` does not account for this special case (in Python 3.9+, `repr(Union[None, T])` will display `Optional[T]`.

This is especially necessary for code generators like torch.fx, where Optional arguments will become Union types in the resulting GraphModule, making the GraphModule non-scriptable.

I've brought this up with the FX team (see #51457) but a better solution would be to change this within the TorchScript side to account for any kind of code generator.

## REPRO
```
class TestModule(torch.nn.Module):
    def forward(self, x: torch.Tensor, k: Optional[int]):
        return x

m = TestModule()
gm = torch.fx.symbolic_trace(m)
scripted_gm = torch.jit.script(gm)
```

## EXPECTED OUTCOME
This should work without errors.
## ACTUAL OUTCOME
I get the error `Unknown type constructor Union` because the resulting GraphModule contains Union annotations in place of the Optional type annotations.

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks @nikithamalgifb!
