### ISSUE TITLE
Feature Request: Highway Networks

### ISSUE THREAD

**Issue by c0nn3r** [pytorch/pytorch#516]
First, thanks for creating such a focused, bounded, well implemented, library. It is fantastic to work with. Highway networks might be a useful feature for `torch.nn`. They are needed to implement papers such as [Character-Aware Neural Language Models](https://arxiv.org/pdf/1508.06615v4.pdf). Most libraries have an implementation. I would be willing to implement them.

**Comment by soumith** [comment]
highway networks will be a candidate for the pytorch/examples repository, along with resnets, dcgan, etc. please do implement them and open a PR there, we would love to have it :)

**Comment by soumith** [comment]
i'm going to close this issue and will wait for your PR in pytorch/examples
