### ISSUE TITLE
FR: Support complex eigenvalue autograd

### ISSUE THREAD

**Issue by zzxihuanheixiu** [pytorch/pytorch#51621]
The error information is as follows:
RuntimeError: eig_ backward: Backward calculation does not support complex eigenvalues at the moment.

The details are as follows:
One step in my loss function is to calculate the eigenvalues of the matrix. I used the torch.eig function, but later when I used the reverse derivation of the loss function, the program was stuck in the position of the torch.eig function, because sometimes the matrix has complex eigenvalues. Under what circumstances, the torch.eig function does not support reverse derivation! How can I solve it???

Please help me！！！

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @anjali411 @dylanbespalko @mruberry @jianyuh @heitorschueroff @walterddr @IvanYashchuk

**Comment by zou3519** [comment]
Do you have a self-contained script which we could use to reproduce the problem?

**Comment by albanD** [comment]
Hi,

As mentioned in the error message, it does not support backward when any eigenvalue is not purely a real number (any non-zero imaginary part).

**Comment by zzxihuanheixiu** [comment]
Then I can't do the project

**Comment by zzxihuanheixiu** [comment]
There is such a step in my project:
          (evals, eigvecs) = torch.eig(matrix, eigenvectors=True)

If there are complex numbers in the eigenvalues of matrix，the inverse derivation of evals or eigevecs will not be computed。Oh my god！I can't finish my project！I really want to finish my tutor's task and play cyberpunk 2077！

**Comment by mruberry** [comment]
Sorry to hear that we're getting in the way of Cyberpunk 2077. We are working on improving our linear algebra support and complex tensor support now, however. See https://github.com/pytorch/pytorch/issues/42666 for the tracker. Which has an item to implement torch.linalg.eig. I'll link this issue there.

**Comment by o-alexandre-felipe** [comment]
> Then I can't do the project

@zzxihuanheixiu if you constraint to symmetric matrices you will not have complex eigenvalues. For instance if you want the magnitude of the eigenvalues you can compute the eigenvalues of  X * X.T.
