### ISSUE TITLE
[docs] FractionalMaxPool3D documentation is not available on documentation site

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51625]
The module and the functional variant are available.

![Screenshot from 2021-02-03 13-06-47](https://user-images.githubusercontent.com/19503980/106713651-c11fb780-6620-11eb-844e-a04cabff2a83.png)

But their documentation is not available on the site.

https://pytorch.org/docs/master/search.html?q=FractionalMaxPool&check_keywords=yes&area=default
![Screenshot from 2021-02-03 13-08-23](https://user-images.githubusercontent.com/19503980/106713778-ef04fc00-6620-11eb-91a3-26e6efaa6b06.png)

https://pytorch.org/docs/master/search.html?q=fractional_max_pool&check_keywords=yes&area=default#
![Screenshot from 2021-02-03 13-08-58](https://user-images.githubusercontent.com/19503980/106713841-0512bc80-6621-11eb-9d3d-ec36c24ee317.png)

cc @jlin27 @mruberry @albanD @jbschlosser @heitorschueroff

**Comment by zou3519** [comment]
We would accept a patch to fix this
