### ISSUE TITLE
Complex Autograd: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.

### ISSUE THREAD

**Issue by Kinetize** [pytorch/pytorch#51627]
## 🐛 Bug

During the backwards pass on complex operations, the autograd fails with the following error: "Complex Autograd: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.". This happens on GPU as well as on CPU.
It happens even though all used operations are listed [here](https://github.com/pytorch/pytorch/blob/72bc3d9de4f8baa28ebc8f9399ad86cefe89d9f5/tools/autograd/gen_variable_type.py#L154).
A similar error has been discribed (and solved) in #43349.

## To Reproduce

Run the following code for a rnn-cell (one pass suffices to run into the error) and perform a backward pass on it: 

```
def to_complex_activation(activation):
    return lambda x: torch.view_as_complex(torch.cat(
        [activation(x.real).unsqueeze(-1), activation(x.imag).unsqueeze(-1)], dim=-1))

class CGCell(nn.Module):

    def __init__(self, input_size, hidden_size):
        super(CGCell, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        self.wg = nn.Parameter(torch.randn(2 * hidden_size, hidden_size, dtype=torch.cfloat))
        self.vg = nn.Parameter(torch.randn(2 * hidden_size, input_size, dtype=torch.cfloat))
        self.bg = nn.Parameter(torch.randn(2 * hidden_size, dtype=torch.cfloat))

        self.w = nn.Parameter(torch.randn(hidden_size, hidden_size, dtype=torch.cfloat))
        self.v = nn.Parameter(torch.randn(hidden_size, input_size, dtype=torch.cfloat))
        self.b = nn.Parameter(torch.randn(hidden_size, dtype=torch.cfloat))

        alpha = beta = 0.5  # TODO
        self.fg = lambda x: torch.sigmoid(alpha * x.real + beta * x.imag)
        self.fa = to_complex_activation(torch.sigmoid)

    def _init_hidden(self, x):
        h = torch.zeros((x.shape[0], self.hidden_size),  dtype=torch.cfloat).to(device)

        return h

    def forward(self, x, ht_=None):
        if ht_ is None:
            ht_ = self._init_hidden(x)

        gates = ht_ @ self.wg.T + x @ self.vg.T + self.bg
        g_r, g_z = gates.chunk(2, 1)

        g_r = self.fg(g_r)
        g_z = self.fg(g_z)

        z = (g_r * ht_) @ self.w.T + x @ self.v.T + self.b
        ht = g_z * self.fa(z) + (1 - g_z) * ht_

        return ht
```

Then, the following error will occur:

```
 File "...\model\spectral_rnn\spectral_rnn.py", line 75, in train
    loss.backward()
  File "...\Python38\lib\site-packages\torch\tensor.py", line 227, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "...\Python38\lib\site-packages\torch\autograd\__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.
```

## Expected behavior

Since all used operations are [listed to have complex gradients](https://github.com/pytorch/pytorch/blob/72bc3d9de4f8baa28ebc8f9399ad86cefe89d9f5/tools/autograd/gen_variable_type.py#L154)., I expected the code to run through, i.e. the backward pass to succeed.

## Environment

 - PyTorch Nightly: 1.8.0dev20210201 via pip
 - OS: Windows10
 - Python version: 3.8.3
 - CUDA/cuDNN version: 10.1

## Additional context

This cell is part of bringing the paper [Complex Gated Recurrent Neural Networks](https://arxiv.org/pdf/1806.08267.pdf) to PyTorch.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @anjali411 @dylanbespalko @mruberry

**Comment by zou3519** [comment]
Tentatively marking high-pri for what looks like incorrect behavior (complex gradients for the operators should be implemented)

**Comment by albanD** [comment]
Hi,

I cannot repro on nightly with the following script. Am I missing anything?

```python
# !pip uninstall --y torch
# !pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
import torch
from torch import nn

device = "cpu"

def to_complex_activation(activation):
    return lambda x: torch.view_as_complex(torch.cat(
        [activation(x.real).unsqueeze(-1), activation(x.imag).unsqueeze(-1)], dim=-1))


class CGCell(nn.Module):

    def __init__(self, input_size, hidden_size):
        super(CGCell, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        self.wg = nn.Parameter(torch.randn(2 * hidden_size, hidden_size, dtype=torch.cfloat))
        self.vg = nn.Parameter(torch.randn(2 * hidden_size, input_size, dtype=torch.cfloat))
        self.bg = nn.Parameter(torch.randn(2 * hidden_size, dtype=torch.cfloat))

        self.w = nn.Parameter(torch.randn(hidden_size, hidden_size, dtype=torch.cfloat))
        self.v = nn.Parameter(torch.randn(hidden_size, input_size, dtype=torch.cfloat))
        self.b = nn.Parameter(torch.randn(hidden_size, dtype=torch.cfloat))

        alpha = beta = 0.5  # TODO
        self.fg = lambda x: torch.sigmoid(alpha * x.real + beta * x.imag)
        self.fa = to_complex_activation(torch.sigmoid)

    def _init_hidden(self, x):
        h = torch.zeros((x.shape[0], self.hidden_size),  dtype=torch.cfloat).to(device)

        return h

    def forward(self, x, ht_=None):
        if ht_ is None:
            ht_ = self._init_hidden(x)

        gates = ht_ @ self.wg.T + x @ self.vg.T + self.bg
        g_r, g_z = gates.chunk(2, 1)

        g_r = self.fg(g_r)
        g_z = self.fg(g_z)

        z = (g_r * ht_) @ self.w.T + x @ self.v.T + self.b
        ht = g_z * self.fa(z) + (1 - g_z) * ht_

        return ht

mod = CGCell(2, 2)
inp = torch.rand(3, 2, dtype=torch.cfloat)

out = mod(inp)

out.norm().backward()
# Runs fine
```

**Comment by Kinetize** [comment]
No, you're not missing a thing, I was. the problem actually lies somewhere else. I just considered this code could not be of any issue.

To demonstrate the problem, I wrote a minimal version reproducing the issue:
'''
import torch
from torch import nn

v = nn.Parameter(torch.randn(2, 2))
inp_r = torch.randn(3, 2) @ v.T
inp_c = torch.rand(3, 2, dtype=torch.cfloat)

inp = torch.cat([inp_r, inp_c], dim=-1)  # Causes problems
# inp = torch.cat([torch.complex(inp_r, torch.zeros_like(inp_r)), inp_c], dim=-1)  # Works

w = nn.Parameter(torch.randn(2, 4, dtype=torch.cfloat))
out = inp @ w.T

out.norm().backward()
'''

The origin of the problem seems to be the cat operation: When explicitly concatenating two complex tensors, the backprop works just fine. When one tensor is real however, the cat operation still succeeds and the output is of a correct complex type, but the backprop fails with the above mentioned error.

Note that the problem only occurs when there are any parameters are located "behind" the real input, i.e. code like this will backprop just fine:

'''
import torch
from torch import nn

inp_r = torch.randn(3, 2)
inp_c = torch.rand(3, 2, dtype=torch.cfloat)

inp = torch.cat([inp_r, inp_c], dim=-1)  # Causes problems
# inp = torch.cat([torch.complex(inp_r, torch.zeros_like(inp_r)), inp_c], dim=-1)  # Works

w = nn.Parameter(torch.randn(2, 4, dtype=torch.cfloat))
out = inp @ w.T

out.norm().backward()
'''

As a conclusion, the problem lies in a different spot then I expected it to be, but this should still be unwanted behavior.

**Comment by albanD** [comment]
Thanks for the new example!

cc @anjali411 did we miss that case when reviewing/testing the backward of the `cat` op?

**Comment by gchanan** [comment]
I couldn't reproduce this on nightly.

**Comment by anjali411** [comment]
The issue is probably that `torch.cat` backward function doesn't correctly handle the `R->C` case right now. trying to locally reproduce it now

**Comment by anjali411** [comment]
I was able to reproduce this on master:
```
>>> inp_r = torch.randn(3, 2, requires_grad=True)
>>> inp_c = torch.rand(3, 2, dtype=torch.cfloat, requires_grad=True)
>>> def fn(x1, x2):
...     return torch.cat((x1, x2), dim=-1)
...
>>> torch.autograd.gradcheck(fn, [inp_r, inp_c])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chourdiaanjali/pytorch/torch/autograd/gradcheck.py", line 421, in gradcheck
    analytical, reentrant, correct_grad_sizes, correct_grad_types = get_analytical_jacobian(tupled_inputs,
  File "/home/chourdiaanjali/pytorch/torch/autograd/gradcheck.py", line 185, in get_analytical_jacobian
    grads_input = torch.autograd.grad(output, diff_input_list, grad_output,
  File "/home/chourdiaanjali/pytorch/torch/autograd/__init__.py", line 223, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Expected isFloatingType(grad.scalar_type()) || (input_is_complex == grad_is_complex) to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
the gradients propagated for the floating_point tensor right now are complex valued. We have a special check in the autograd machinery to error out exactly when this happens. Working on a fix now to return correct real valued gradients for such `R->C` cases.
