### ISSUE TITLE
nn.Parameter.new returns Variable instead of nn.Parameter

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5164]
`torch.__version__ == '0.4.0a0+4ae0579'`
```python
import torch

p = torch.nn.Parameter()
print(type(p))
# <class 'torch.nn.parameter.Parameter'>

q = p.new()
print(type(q))
# <class 'torch.autograd.variable.Variable'>
```

Similar issue about `nn.Parameter.type_as(...)`, it currently returns a Variable.

**Comment by zou3519** [comment]
@vadimkantorov would you expect `nn.Parameter.new()` to return a `nn.Parameter`? If so, what would you say the use cases for this are?

If someone calls .new() on a `nn.Parameter` then immediately assigns it to a module, I'm not sure I would want the module to recognize the new tensor as a "Parameter" of the model. There could be a situation in which the user wants to cache the new tensor.

**Comment by vadimkantorov** [comment]
The use-case was writing a weight loader (in my case a loader from caffemodel):
https://github.com/vadimkantorov/caffemodel2pytorch/blob/master/caffemodel2pytorch.py#L352

I was looking to create a Parameter that shared the device of the original parameter, the type of original parameter and requires_grad.

What didn't work:
* `self.weight.resize_as_(my_float_tensor).copy_(my_float_tensor)`
* self.weight = self.weight.new(my_float_tensor.size()).copy_(my_float_tensor)
* self.weight = nn.Parameter(my_float_tensor).type_as(self.weight)

The not so pretty version that woked is linked just above.

**Comment by apaszke** [comment]
Well, you can say that the contract for `Variables` is that `new()` will return a `Variable`, and `Parameters` don't change it :wink:

As @zou3519 nicely pointed out, changing this would likely result in adding memory leaks to code that works fine today. Additionally, `nn.Parameter` is pretty much a way to require the user to explicitly annotate the Variables they want to be saved as parameters, and nothing more. I think it's a better idea to keep the behavior as is, but thanks for the suggestion!

**Comment by apaszke** [comment]
Tensor.new doesn't break the contract. It's a class unrelated to Variable, so its contract is that it returns a Tensor :wink:

Parameters are really just ways of requiring the users to explicitly say which Variables do they want auto-saved by modules. They are never meant to be returned as a result of any operation, and this will not change.

I think you can resize them if you're in the no-grad mode, but I'm not 100% sure.

**Comment by vadimkantorov** [comment]
Ok, just maybe need an idiomatic way to load weights preserving the device and `requires_grad` :)

I did around:
`selfe.weight = nn.Parameter(weight.type_as(self.weight), requires_grad = self.weight.requires_grad)`

**Comment by apaszke** [comment]
Can't you just assign to `.data`?
