### ISSUE TITLE
[proposal] Multi-dim torch.max + return_indices

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#51656]
Sometimes it's good to do multi-dim max pooling in some normalization scenarious, e.g. `tensor5d / tensor5d.flatten(start_dim = -3).max(dim = -1).values[..., None, None, None]`.

This is quite verbose, I propose to support the following: `tensor5d / tensor5d.max(dim = (-3, -2, -1), keepdim = True, return_indices = False).values`

When `return_indices == False`, the returned indices tensor would be undefined. Whether it should still keep the indices tensor inside the autograd structures would be debatable: both options make sense. One would have less allocations, another would support differentiation.

cc @heitorschueroff

**Comment by ngimel** [comment]
Would `amax` work for you? It's differentiable and supports dim tuple https://pytorch.org/docs/master/generated/torch.amax.html?highlight=amax#torch.amax

**Comment by vadimkantorov** [comment]
I guess it does. Thanks!
