### ISSUE TITLE
incorrect shape in  translating "ConvTranspose2d"  to ONNX

### ISSUE THREAD

**Issue by spidyDev** [pytorch/pytorch#5166]
- OS: MacOS
- PyTorch version: pytorch                   0.3.0           py27_cuda0.0_cudnn0.0he480db7_4    
- How you installed PyTorch (conda, pip, source): pip
- Python version:  Python 2.7.14
- CUDA/cuDNN version: NA
- GPU models and configuration: NA
- GCC version (if compiling from source): NA

 I wrote a simple test to test export of "ConvTranspose2d" to ONNX:

```
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.onnx as torch_onnx
import mxnet as mx
import onnx

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
    self.c0 = nn.ConvTranspose2d(1024, 512, 4, 2, 1, bias=False)

    def forward(self, inputs):
        return self.c0(inputs)

input_shape = (1, 1024, 100, 100)
model_onnx_path = "convTranspose_model.onnx"

model = Model()
model.train(False)

dummy_input = Variable(torch.randn(input_shape))
torch_onnx.export(model, dummy_input, model_onnx_path, verbose=True)


model = onnx.load('convTranspose_model.onnx')
onnx.checker.check_model(model)
```

If I view the onnx graph in  Netron, the shape of the "W"  seems incorrect. 
The expected shape :  (512,1024, 4,4)
but it shows as: (1024, 512, 4, 4)

**Comment by ezyang** [comment]
The convention in PyTorch and ONNX is that 1024 is the input channels (aka channels), 512 is the output channels (aka feature maps), and you put input channels first in the weights as per https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose ; thus tthis is the shape I would expect. Am I missing something?
