### ISSUE TITLE
Quantizable MHA error too high when bias=False

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#51662]
#49866 introduces the quantizable MultiheadAttention. However, when the bias=False, the SNR drops to ~10dB. Need to investigate and remedy.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
Do we plan to fix this? @z-a-f

**Comment by z-a-f** [comment]
@jerryzh168  Yea, I am working on it.

I think I found what the problem was -- will close it once I confirm

**Comment by z-a-f** [comment]
resolved :)
