### ISSUE TITLE
RemoteModule should place the input on the appropriate device before calling forward

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#51670]
RemoteModule moves the underlying layer on the device, but it doesn't move the input to the same device before calling forward. 

Suppose we have this:
```
m = RemoteModule("worker1/cuda:0", nn.Linear, args=(10, 10), kwargs=kwargs)
```
It puts an instance of nn.Linear to cuda:0 on worker1, but calls its forward method with input x on cpu.

We probably need to enhance [_remote_forward](https://github.com/pytorch/pytorch/blob/8e53bf010d1309b056d6e1d31a9362a7b92736ff/torch/distributed/nn/jit/templates/remote_module_template.py#L17) to move the inputs to the appropriate device.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by SciPioneer** [comment]
This issue blocks the Beta release of RemoteModule feature in 1.9 release. Set it high priority and plan to resolve it in April.
