### ISSUE TITLE
The variance of initialization weights are NOT 1

### ISSUE THREAD

**Issue by airsplay** [pytorch/pytorch#5168]
https://github.com/pytorch/pytorch/blob/9f980b179506489d226051259eacec8639c00c5f/torch/nn/modules/linear.py#L48
`
stdv = 1. / math.sqrt(self.weight.size(1))`
`self.weight.data.uniform_(-stdv, stdv)
`
By a simple calculation, the variance of the output feature would be 1/3 instead of 1. It means that the feature will lose 2/3 energy after a linear module. Here is how to fix it:
`stdv = math.sqrt(3. / self.weight.size(1))`

BTW, most of us set the bias to zero instead of some random uniform... I don't think that it's a good practice.
BTW2, the initialization of LSTM is wrong as well. 

Here are the references:
[wiki](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous))
[Origin paper](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf)

**Comment by SsnL** [comment]
I don't think the variance thing should be counted as a bug. That is the default initialization of linear layers, and is a commonly used one. We also provide a wide range of other initialization methods, which users are free to choose from if they want.

**Comment by soumith** [comment]
the default initialization for Linear layers is from "Efficient Backprop", LeCun'99. As Simon mentioned `nn.init` has other initializations including glorot.
