### ISSUE TITLE
jit internal python bindings all get added to the `torch.` namespace.

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#51691]
### The problem

We have a construct in the torch init that adds to `torch.XX` anything that is is `torch._C.XX`.
The jit init is given the torch._C module here: https://github.com/pytorch/pytorch/blob/45e5562fcc5b0759b26f46f18f1156213b354902/torch/csrc/jit/python/init.cpp#L134
This file adds a lot of internal stuff (_XX) which is ok as they are not added to `torch.`.

But the python IR binding called afterwards here: https://github.com/pytorch/pytorch/blob/45e5562fcc5b0759b26f46f18f1156213b354902/torch/csrc/jit/python/python_ir.cpp#L210

Adds many things with the `_` and so all of these things get added to `torch.` in the end.

Note that other subset of the jit might be doing the same thing, but I stumbled upon the IR binding one first.

### Proposed solution

My proposed solution is to make the top level module create a `torch._C._jit` submodule that will be passed to all the initialization code. This way, none of it will be added to the `torch.` package.
But we can explore other options as well!

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
I think this would be a good cleanup task, but I worry about BC in the case that users are using `torch._C._jit_...` today. I guess we can communicate the change in the release notes? What do you think @gmagogsfm?

**Comment by SplitInfinity** [comment]
I did this in #52158, but I didn't read carefully and didn't see this part of your description

> This file adds a lot of internal stuff (_XX) which is ok as they are not added to torch..

and I moved everything to the new submodule. Hopefully that's okay!

**Comment by SplitInfinity** [comment]
@albanD 

I found one place where we depend on `torch.fork` which is actually `torch._C.fork`. For some reason this binding is in the JIT bindings (maybe it should be somewhere else?), and so my PR has broken code that uses `torch.fork`.

**Comment by albanD** [comment]
Is it just in the list of functions that the override should ignore? If so, we can just delete it from there no?

Also if there are cases where we worry that third party users might be relying on some of these, I think it is completely fine to add them back to torch. manually (with a deprecation warning?). That will still be a strictly better state than what we have right now!

**Comment by SplitInfinity** [comment]
> Is it just in the list of functions that the override should ignore? If so, we can just delete it from there no?

Yes. I don't know that code but I will take your word for it :).

**Comment by SplitInfinity** [comment]
Okay, tests are passing now but I had to duplicate some bindings or leave some as `torch._C.XXX` which I will try to fix in one or more follow-up PRs.
