### ISSUE TITLE
Error when backprop through squeeze of mean of a 1d variable

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#5170]
> import torch
> from torch.autograd import Variable
> x = Variable(torch.randn(3), requires_grad=True)
> x.mean().squeeze().backward()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "local/anaconda/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/local/anaconda/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: invalid argument 1: the number of sizes provided must be greater or equal to the number of dimensions in the tensor at /opt/conda/conda-bld/pytorch_1512378360668/work/torch/lib/TH/generic/THTensor.c:299

> x = Variable(torch.randn(3,4), requires_grad=True)
> x.mean().squeeze().backward() # no error
> x.sum(1).mean().squeeze().backward() # the same error

version:
0.3.0.post4

**Comment by zou3519** [comment]
Thanks for the report! #4783 fixed this on master. You can try building from source or wait for the next release.
