### ISSUE TITLE
[docs] fractional_max_pool2d documentation is not available on documentation site

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51708]
The functional variant `fractional_max_pool2d` is available for use but is undocumented on site.

![Screenshot from 2021-02-03 13-06-47](https://user-images.githubusercontent.com/19503980/106850331-5337c680-66da-11eb-92be-5578697f9ab3.png)

![Screenshot from 2021-02-03 13-08-58](https://user-images.githubusercontent.com/19503980/106850358-5fbc1f00-66da-11eb-9592-08ed11b2ad75.png)

Reference: https://github.com/pytorch/pytorch/issues/51623#issuecomment-772614573

cc @jlin27 @mruberry @albanD @jbschlosser

**Comment by mruberry** [comment]
Seems like an oversight to me. @jbschlosser?

**Comment by jbschlosser** [comment]
For sure! It should definitely be there. Thanks for reporting this @kshitij12345!
