### ISSUE TITLE
Failed to cross compile: '/bin/mkalias', needed by 'sleef/src/libm/include/alias_advsimd.h', missing and no known rule to make it

### ISSUE THREAD

**Issue by KumaTea** [pytorch/pytorch#51710]
## ❓ Questions and Help

Hi. 

I'm trying to cross compile PyTorch wheels for arm or arm64 machines. My configs are as follows:

1. from Docker `python:3.9`

```bash
apt update
apt install -y bash build-essential ca-certificates cmake curl git libffi-dev libssl-dev nano ninja-build wget xz-utils zlib1g-dev

python3.9 -m pip install -U pip setuptools wheel
python3.9 -m pip install -U cffi dataclasses future numpy pillow pyyaml requests six typing_extensions tqdm

git clone https://github.com/pytorch/pytorch

wget https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
tar -xJf gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
mv gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu toolchain
```

2. setting cross-compiling environment

```
VER="1.7.1"
export PYTORCH_BUILD_VERSION="$VER"
export PYTORCH_BUILD_NUMBER="1"

cd pytorch

###
# Add this lines to the top of CMakrLists.txt
# set(COMPILER_WORKS_EXITCODE 0)
# set(COMPILER_WORKS_EXITCODE__TRYRUN_OUTPUT "")
###

export CMAKE_SYSTEM_NAME="Linux"
export CMAKE_SYSTEM_PROCESSOR="aarch64"

TOOLCHAIN_PATH="/root/toolchain/bin/"
CMAKE_EXECUTABLE_SUFFIX=""

export CMAKE_AR="${TOOLCHAIN_PATH}aarch64-linux-gnu-ar${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_ASM_COMPILER="${TOOLCHAIN_PATH}aarch64-linux-gnu-gcc${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_C_COMPILER="${TOOLCHAIN_PATH}aarch64-linux-gnu-gcc${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_CXX_COMPILER="${TOOLCHAIN_PATH}aarch64-linux-gnu-g++${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_LINKER="${TOOLCHAIN_PATH}aarch64-linux-gnu-ld${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_OBJCOPY="${TOOLCHAIN_PATH}aarch64-linux-gnu-objcopy${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_RANLIB="${TOOLCHAIN_PATH}aarch64-linux-gnu-ranlib${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_SIZE="${TOOLCHAIN_PATH}aarch64-linux-gnu-size${CMAKE_EXECUTABLE_SUFFIX}"
export CMAKE_STRIP="${TOOLCHAIN_PATH}aarch64-linux-gnu-strip${CMAKE_EXECUTABLE_SUFFIX}"

export BUILD_TEST=0
export USE_FBGEMM=0
export USE_MKLDNN=0
```

3. start building

```bash
python3 setup.py build
python3 setup.py install
python3 setup.py bdist_wheel
```

---

After it started building, I comfirmed the generated config (starts with `-- ******** Summary ********`) are the same as host-compiling.

But it failed building at the first component:
```
cmake --build . --target install --config Release -- -j 4
ninja: error: '/bin/mkalias', needed by 'sleef/src/libm/include/alias_advsimd.h', missing and no known rule to make it
Traceback (most recent call last):
  File "/root/pytorch/torch/setup.py", line 760, in <module>
    build_deps()
  File "/root/pytorch/torch/setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/root/pytorch/torch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/root/pytorch/torch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/root/pytorch/torch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '4']' returned non-zero exit status 1.
root@ee38db3e55e1:~/pytorch#
```

I don't know if it's bacause of [`sleef`](https://github.com/shibatch/sleef) or I've wrongly configured a cross-compiling env.

Full log: 
[full.log](https://github.com/pytorch/pytorch/files/5923558/full.log)

Thank you.

cc @malfet @seemethere @walterddr

**Comment by KumaTea** [comment]
Related issues:

* shibatch/sleef#249
* shibatch/sleef#308

**Comment by pzhong4** [comment]
error:
-- Build files have been written to: /home/zhongpeng/work/source/pytorch/third_party/sleef/build_x9u
zhongpeng@pd-pzhong4-n:~/work/source/pytorch/third_party/sleef/build_x9u$ make -j12
make[2]: *** No rule to make target '/bin/mkrename_gnuabi', needed by 'src/libm/include/renameadvsimd_gnuabi.h'.  Stop.
make[2]: *** No rule to make target '/bin/mkrename_gnuabi', needed by 'src/libm/include/renameadvsimd_gnuabi.h'.  Stop.
CMakeFiles/Makefile2:674: recipe for target 'src/libm/CMakeFiles/sleefgnuabiadvsimddp.dir/all' failed
make[1]: *** [src/libm/CMakeFiles/sleefgnuabiadvsimddp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:700: recipe for target 'src/libm/CMakeFiles/sleefgnuabiadvsimdsp.dir/all' failed
make[1]: *** [src/libm/CMakeFiles/sleefgnuabiadvsimdsp.dir/all] Error 2
make[2]: *** No rule to make target '/bin/mkdisp', needed by 'src/libm/dispscalar.c.body'.  Stop.
CMakeFiles/Makefile2:594: recipe for target 'src/libm/CMakeFiles/dispscalar.c_generated.dir/all' failed
make[2]: *** No rule to make target '/bin/mkrename', needed by 'src/libm/sleeflibm_ADVSIMD_.h.tmp'.  Stop.
make[1]: *** [src/libm/CMakeFiles/dispscalar.c_generated.dir/all] Error 2
make[2]: *** No rule to make target '/bin/mkalias', needed by 'src/libm/alias_ADVSIMD_dp.h.tmp'.  Stop.
make[2]: *** No rule to make target '/bin/mkrename', needed by 'src/libm/include/renameadvsimd.h'.  Stop.
CMakeFiles/Makefile2:296: recipe for target 'src/libm/CMakeFiles/headers.dir/all' failed
make[1]: *** [src/libm/CMakeFiles/headers.dir/all] Error 2
make[2]: *** No rule to make target '/bin/mkrename', needed by 'src/libm/include/renamepurec_scalar.h'.  Stop.
make[2]: *** No rule to make target '/bin/mkrename', needed by 'src/libm/include/renamepurecfma_scalar.h'.  Stop.


I also encountered this issue during crossing compilation. I suspect that the target compiler was used during 
mkrename/mkrename_gnuabi/mkalias  compilation, which caused it can not run on the host. How can I modify this to use the host compiler when compiling these targets?

# Function used to add an executable that is executed on host
function(add_host_executable TARGETNAME)
  if (NOT CMAKE_CROSSCOMPILING)
    add_executable(${TARGETNAME} ${ARGN})
    # Ensure that Darwin host executable is built as universal binary
    if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND CMAKE_OSX_ARCHITECTURES MATCHES "^(x86_64|arm64)$")
      target_compile_options(${TARGETNAME} PRIVATE -arch "${CMAKE_HOST_SYSTEM_PROCESSOR}")
      target_link_options(${TARGETNAME} PRIVATE -arch "${CMAKE_HOST_SYSTEM_PROCESSOR}")
    endif()
  else()
    **add_executable(${TARGETNAME} IMPORTED GLOBAL)
    set_property(TARGET ${TARGETNAME} PROPERTY IMPORTED_LOCATION ${NATIVE_BUILD_DIR}/bin/${TARGETNAME})**  ###how to use host compiler to build it？？？
  endif()
endfunction()
