### ISSUE TITLE
Reset seed in pytorch

### ISSUE THREAD

**Issue by sadakmed** [pytorch/pytorch#51717]
I just set torch seed to 0 with `torch.manual_seed`, Is there any way to reset the seed.

my case was, I wanted to generate a fixed random tensor, without affecting the randomness of others(other tensors should be different each time).

I found a context manager in `torchfunc`  module, but I don't have access to it in HuggingFace

**Comment by gchanan** [comment]
can you kindly ask on the discussion forum: https://discuss.pytorch.org/ ?  We keep github for bugs and feature requests.
