### ISSUE TITLE
Quantized LeakyReLu Bug: Input tensor size determines the output values

### ISSUE THREAD

**Issue by Krosus** [pytorch/pytorch#51718]
## Issue description

Leaky ReLu returns different results on quantized data based on the size of the input tensor. If the input tensor has 63 or less elements it returns correct results. If the input tensor has 64 or more elements some returned elements will be different. 

**Problem:** Leaky ReLu should return the same transformations no matter the input size.

In the example below we send uint8 quantized values through the Leaky ReLu. As long as we send 63 or less values at the same time we get correct results. When we start sending through 64 or more values at the same time, 3 values will have a different transformation. Other values will remain the same.

In the below example:
Values 91, 101 and 121 will become 123, 124 and 126 when sent through Leaky ReLu inside a tensor with 63 or less elements.
Values 91, 101 and 121 will become 122, 123 and 125 when sent through Leaky ReLu inside a tensor with 64 or more elements.
Other values will be the same no matter the size of the input tensor.

## Code example

```
import torch
import numpy as np

m = torch.nn.LeakyReLU(0.1)

scale=0.061773329973220825
zero = 126

a = np.arange(zero-63,zero).astype(np.float32)

a = (a-zero)*scale
b = np.append(a,a[-1])

print(f'a shape: {a.shape}')
print(f'b shape: {b.shape}')
print()

ta = torch.quantize_per_tensor(torch.tensor(a), scale, zero, torch.quint8)
tb = torch.quantize_per_tensor(torch.tensor(b), scale, zero, torch.quint8)

ta = m(ta)
tb = m(tb)

print('In   OutA  OutB')
for i in range(0,63):
    if ta[i].int_repr() != tb[i].int_repr():
        print(f'{zero-63+i} : {ta[i].int_repr()} , {tb[i].int_repr()} <<')
    else:
        print(f'{zero-63+i} : {ta[i].int_repr()} , {tb[i].int_repr()}')
```

## System Info

```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 9.12 (stretch) (x86_64)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Clang version: 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
CMake version: version 3.7.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 

Nvidia driver version: 440.82
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.0
[pip] numpydoc==0.9.2
[pip] torch==1.6.0
[pip] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] numpydoc                  0.9.2                      py_0  
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi

Also tested on a Kaggle Notebook using Pytorch 1.7.0 and the problem happens there too.
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Hi @Krosus , thank you for the report.  This discrepancy comes from the two branches in the kernel: https://github.com/pytorch/pytorch/blob/87a4baf616565aecd21884754772a0f03babfe2d/aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp#L463 .  There is a slightly different order of floating point operations between the non-vectorized and the vectorized branches in the kernel, leading to some values which end up on different sides of the quantization bin boundaries.  When the input tensor is <63 elements the non-vectorized branch is taken, and otherwise the vectorized branch is taken.

We will discuss what the best course of action is here, as it may not be possible to align the numerics of the non-vectorized path without regressing performance.

**Comment by vkuzo** [comment]
Hi @Krosus , thanks again for the report.  After some internal discussion we decided that the discrepancy is acceptable, we are getting higher performance in the vectorized path, and the discrepancy will only be present if we are comparing tensors of different sizes.  Please let us know if this is blocking you, happy to help brainstorm workarounds.
