### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by DimChatz** [pytorch/pytorch#51723]
I am just starting in pytortch and am trying to install pytorch to my pc using ubuntu. I downloaded and installed cuda11.2 and then i followed the instructions here:
https://pytorch.org/get-started/locally/ by running the code:
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
 but i get the error:

```
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff99f4f7970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/torch_stable.html`
ERROR: Could not find a version that satisfies the requirement torch==1.7.1+cu110
ERROR: No matching distribution found for torch==1.7.1+cu110
```

Can anyone help?

cc @ezyang @seemethere @malfet @walterddr

**Comment by ezyang** [comment]
Sounds like you're unable to connect to https://download.pytorch.org/whl/torch_stable.html Can you view it in your browser?

**Comment by DimChatz** [comment]
no apparently i dont. Thx for the feedback. Do you know why that could be ?

**Comment by ezyang** [comment]
The most likely explanation is some sort of ISP problem. Try using a proxy. Unfortunately we won't be able to help you beyond that.
