### ISSUE TITLE
aten::normal_ not handled as a special op in RemoveTensorMutation pass.

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#51735]
## 🐛 Bug

aten::normal_ should be considered as a special op in remove mutation pass.
The op does not have an equivalent aten::normal

## To Reproduce

Apply remove mutation on the model below:

```
class Noise(nn.Module):
    def forward(self, image):
        return image.new_empty(2, 1, 3, 4).normal_()
```

## Expected behavior

Error is:
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None, 

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang @gmagogsfm

**Comment by SplitInfinity** [comment]
@eellison You wrote this pass, right? Do you have any insight to offer?

**Comment by ezyang** [comment]
The easiest fix is to probably just implement `normal`

**Comment by eellison** [comment]
Yes, but there is logic to validate that the replaced schema exists and there are operators for it, so i'm not sure what's going on: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_mutation.h#L66.

**Comment by SplitInfinity** [comment]
@eellison Would it be okay if I assigned this to you for further investigation?

**Comment by neginraoof** [comment]
@eellison 
There's a list of special ops like normal:
https://github.com/pytorch/pytorch/blob/425a5dc3f76489cada49eb9365a974a00cc4975a/torch/csrc/jit/passes/remove_mutation.h#L22

**Comment by eellison** [comment]
Yea, i'll add a fix.

**Comment by eellison** [comment]
really, we should add a `normal_like` constructor... im going to do a quick fix than open an issue for that.
