### ISSUE TITLE
Bool Array to FloatTensor Inconsistent behaviour

### ISSUE THREAD

**Issue by zafarali** [pytorch/pytorch#5177]
- OS: MacOS 10.13.1 
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): N/A

Hi,
I was wondering if this was inconsistent behavior and if an error should be thrown in one of the cases:

- *as expected*: `torch.from_numpy(np.array([1, 0, 0]))` produces  `[torch.LongTensor of size 3]` with elements `1 0 0`
- *as expected*: `torch.from_numpy(np.array([True, False, False]))` throws an error `RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.` 
- *as expected*: `torch.FloatTensor(np.array([1, 0, 0]))` produces `[torch.FloatTensor of size 3]` with elements `1 0 0`
- *unexpected*: `torch.FloatTensor(np.array([True, False, False]))` produces `[torch.FloatTensor of size 3]` with elements`0.0000 -2.0000 -0.0000`

I feel like the last instance should throw an error.

**Comment by vishwakftw** [comment]
This has been fixed.
```python
>>> torch.FloatTensor(np.array([True, False, False]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8.
```
