### ISSUE TITLE
spectral_norm not properly initialized if used with eval first

### ISSUE THREAD

**Issue by novog** [pytorch/pytorch#51800]
According to the documentation, `nn.utils.spectral_norm` first performs some initialization actions the first time that `forward` is called. However, if `forward` is first called in `eval` mode, this initialization does not occur. The combination of the lack of initialization and how `spectral_norm` layers are evaluated in forward passes can result in layer outputs with values several orders of magnitude larger than the inputs. This scenario of a model being used in `eval` mode before `train` can arise naturally with some GAN training procedures, or when trying to assess initializations and their effect on activation variance across layers.

There is a workaround for this problem: perform a single forward pass in `train` mode first. However, unnoticed, it can silently cause training problems or be hard to diagnose. To avoid this unnecessary and potentially harmful complication, spectral_norm should be modified to either perform initialization immediately upon being applied to a layer, or to perform it in the first forward pass even if it is not in `train` mode.

Sample code to reproduce:
```py
    class SpectralNormTestModel(nn.Module):
        
        def __init__(self, use_spectral_norm: bool):
            super(SpectralNormTestModel, self).__init__()
            feature_count = 1000

            def init_(layer: nn.Linear):
                nn.init.orthogonal_(layer.weight.data, 1.372)
                nn.init.zeros_(layer.bias.data)

            self.fc1 = nn.Linear(feature_count, feature_count)
            init_(self.fc1)
            if use_spectral_norm:
                self.fc1 = nn.utils.spectral_norm(self.fc1)
            self.act1 = nn.PReLU(feature_count)

            self.fc2 = nn.Linear(feature_count, feature_count)
            init_(self.fc2)
            if use_spectral_norm:
                self.fc2 = nn.utils.spectral_norm(self.fc2)
            self.act2 = nn.PReLU(feature_count)

            self.out = nn.Linear(feature_count, 1)
            init_(self.out)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            return self.out(self.act2(self.fc2(self.act1(self.fc1(x)))))
    
    
    def spectral_norm_init_test(use_spectral_norm: bool):
        model = SpectralNormTestModel(use_spectral_norm).cuda().eval()
        x = torch.randn(10000, 1000).cuda()
        y = model(x)
        print(f"mean absolute output: {y.abs().mean()}")
```
When run without using spectral norm, the mean absolute output stays between around 0.9 and 1.8. With spectral norm, it commonly varies between around 100 and 100000. 

I am using torch version 1.7.1+cu110 in Python 3.8.5 on Windows 10.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @novog. We'll take a look.

**Comment by mattip** [comment]
Tweaking the test a bit to optionally call forward, I get that with `use_forward` the mean output is `~0.5`, without forward it is `~600`:
```
from torch import nn
import torch

class SpectralNormTestModel(nn.Module):
        def __init__(self):
            super(SpectralNormTestModel, self).__init__()
            feature_count = 1000

            def init_(layer: nn.Linear):
                nn.init.orthogonal_(layer.weight.data, 1.372)
                nn.init.zeros_(layer.bias.data)

            self.fc1 = nn.Linear(feature_count, feature_count)
            init_(self.fc1)
            self.fc1 = nn.utils.spectral_norm(self.fc1)
            self.act1 = nn.PReLU(feature_count)

            self.fc2 = nn.Linear(feature_count, feature_count)
            init_(self.fc2)
            self.fc2 = nn.utils.spectral_norm(self.fc2)
            self.act2 = nn.PReLU(feature_count)

            self.out = nn.Linear(feature_count, 1)
            init_(self.out)

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            return self.out(self.act2(self.fc2(self.act1(self.fc1(x)))))
     
def spectral_norm_init_test(use_forward: bool):
    x = torch.randn(10000, 1000, device='cuda')
    model = SpectralNormTestModel().cuda()
    if use_forward:
        y = model.forward(x)
    y = model.eval()(x) 
    print(f"mean absolute output: {y.abs().mean()}")

print('----- test with use_forward ------')
spectral_norm_init_test(True)
print('----- test without use_forward ------')
spectral_norm_init_test(False)
print('----- done ------')
```

This prints
```
----- test with use_spectral_norm ------
SpectralNorm.__init__
SpectralNorm.__init__
in compute_weight, cloning
in compute_weight, cloning
mean absolute output: 0.5128486156463623
----- test without use_spectral_norm ------
SpectralNorm.__init__
SpectralNorm.__init__
mean absolute output: 608.47509765625
----- done ------
```

I think the difference is in [`compute_weights`](https://github.com/pytorch/pytorch/blob/v1.8.0/torch/nn/utils/spectral_norm.py#L43), which is called with `module.training=True` during the `forward()` call.
