### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by qieaaa** [pytorch/pytorch#5181]
Hi I tried compiling from source,but it turns out `error: command 'gcc' failed with exit status 1`

- OS: ubuntu 16.04lts
- PyTorch version: v0.3.0   af3964a
- How you installed PyTorch (conda, pip, source):source
- Python version: anaconda3.6
- CUDA/cuDNN version:CUDA9 cuDNN7
- GPU models and configuration: GTX1080 
- GCC version (if compiling from source):gcc version 4.9.3 (Ubuntu 4.9.3-13ubuntu2) 

here is my compiling results

-- Building with NumPy bindings
-- Detected cuDNN at /usr/local/cuda/lib64/libcudnn.so, /usr/local/cuda/include
-- Detected CUDA at /usr/local/cuda
-- Building NCCL library
-- Building with distributed package 
Writing torch/csrc/generic/TensorMethods.cpp
Writing torch/csrc/autograd/generated/VariableType.h
Writing torch/csrc/autograd/generated/VariableType.cpp
Writing torch/csrc/autograd/generated/Functions.h
Writing torch/csrc/autograd/generated/Functions.cpp
Writing torch/csrc/autograd/generated/python_functions.h
Writing torch/csrc/autograd/generated/python_functions.cpp
Writing torch/csrc/autograd/generated/python_variable_methods.cpp
Writing torch/csrc/autograd/generated/python_variable_methods_dispatch.h
Writing torch/csrc/autograd/generated/python_torch_functions.cpp
Writing torch/csrc/autograd/generated/python_torch_functions_dispatch.h
Writing torch/csrc/autograd/generated/python_nn_functions.cpp
Writing torch/csrc/autograd/generated/python_nn_functions.h
Writing torch/csrc/autograd/generated/python_nn_functions_dispatch.h
Writing torch/csrc/jit/generated/aten_dispatch.h
Writing torch/csrc/jit/generated/aten_dispatch.cpp
building 'torch._C' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/torch
creating build/temp.linux-x86_64-3.5/torch/csrc
creating build/temp.linux-x86_64-3.5/torch/csrc/utils
creating build/temp.linux-x86_64-3.5/torch/csrc/jit
creating build/temp.linux-x86_64-3.5/torch/csrc/jit/passes
creating build/temp.linux-x86_64-3.5/torch/csrc/jit/passes/onnx
creating build/temp.linux-x86_64-3.5/torch/csrc/jit/generated
creating build/temp.linux-x86_64-3.5/torch/csrc/jit/script
creating build/temp.linux-x86_64-3.5/torch/csrc/autograd
creating build/temp.linux-x86_64-3.5/torch/csrc/autograd/generated
creating build/temp.linux-x86_64-3.5/torch/csrc/autograd/functions
creating build/temp.linux-x86_64-3.5/torch/csrc/onnx
creating build/temp.linux-x86_64-3.5/home
creating build/temp.linux-x86_64-3.5/home/hzy
creating build/temp.linux-x86_64-3.5/home/hzy/pytorch
creating build/temp.linux-x86_64-3.5/home/hzy/pytorch/torch
creating build/temp.linux-x86_64-3.5/home/hzy/pytorch/torch/csrc
creating build/temp.linux-x86_64-3.5/home/hzy/pytorch/torch/csrc/generated
creating build/temp.linux-x86_64-3.5/torch/csrc/distributed
creating build/temp.linux-x86_64-3.5/torch/csrc/cuda
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/home/hzy/pytorch -I/home/hzy/pytorch/torch/csrc -I/home/hzy/pytorch/torch/lib/pybind11/include -I/home/hzy/pytorch/torch/lib/tmp_install/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/TH -I/home/hzy/pytorch/torch/lib/tmp_install/include/THNN -I/home/hzy/pytorch/torch/lib/tmp_install/include/ATen -I/home/hzy/anaconda35/lib/python3.5/site-packages/numpy/core/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/hzy/anaconda35/include/python3.5m -c torch/csrc/PtrWrapper.cpp -o build/temp.linux-x86_64-3.5/torch/csrc/PtrWrapper.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN -DWITH_SCALARS
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/home/hzy/pytorch -I/home/hzy/pytorch/torch/csrc -I/home/hzy/pytorch/torch/lib/pybind11/include -I/home/hzy/pytorch/torch/lib/tmp_install/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/TH -I/home/hzy/pytorch/torch/lib/tmp_install/include/THNN -I/home/hzy/pytorch/torch/lib/tmp_install/include/ATen -I/home/hzy/anaconda35/lib/python3.5/site-packages/numpy/core/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/hzy/anaconda35/include/python3.5m -c torch/csrc/Exceptions.cpp -o build/temp.linux-x86_64-3.5/torch/csrc/Exceptions.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN -DWITH_SCALARS
...

and it just repeat for many times
`gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/home/hzy/pytorch -I/home/hzy/pytorch/torch/csrc -I/home/hzy/pytorch/torch/lib/pybind11/include -I/home/hzy/pytorch/torch/lib/tmp_install/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/TH -I/home/hzy/pytorch/torch/lib/tmp_install/include/THNN -I/home/hzy/pytorch/torch/lib/tmp_install/include/ATen -I/home/hzy/anaconda35/lib/python3.5/site-packages/numpy/core/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/hzy/anaconda35/include/python3.5m -c torch/csrc/autograd/init.cpp -o build/temp.linux-x86_64-3.5/torch/csrc/autograd/init.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN -DWITH_SCALARS`

torch/csrc/jit/script/compiler.cpp:349:41: error: converting to ‘const AttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<double, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<double, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >]’
       const AttributeMap& attributes = {},
                                         ^
torch/csrc/jit/script/compiler.cpp:350:50: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
       const ListAttributeMap& list_attributes = {}) {
                                                  ^
torch/csrc/jit/script/compiler.cpp: In member function ‘std::vector<torch::jit::Value*> torch::jit::script::to_ir::emitExpr(const TreeRef&, size_t)’:
torch/csrc/jit/script/compiler.cpp:225:61: error: converting to ‘const AttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<double, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<double, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >]’
         return emitNode(kind, getValues(inputs), output_size)->outputs();
                                                             ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 4 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp:225:61: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
         return emitNode(kind, getValues(inputs), output_size)->outputs();
                                                             ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 5 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp:232:67: error: converting to ‘const AttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<double, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<double, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >]’
         auto* node = emitNode(kind, getValues(inputs), output_size);
                                                                   ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 4 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp:232:67: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
         auto* node = emitNode(kind, getValues(inputs), output_size);
                                                                   ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 5 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp: In member function ‘std::vector<torch::jit::Value*> torch::jit::script::to_ir::emitCast(const TreeRef&, const torch::jit::script::ScalarType&)’:
torch/csrc/jit/script/compiler.cpp:327:17: error: converting to ‘const AttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<double, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<double, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >]’
                1)
                 ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 4 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp:327:17: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
                1)
                 ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 5 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp: In member function ‘std::vector<torch::jit::Value*> torch::jit::script::to_ir::emitSlice(const torch::jit::script::SourceRange&, torch::jit::script::TreeList&&, size_t)’:
torch/csrc/jit/script/compiler.cpp:397:38: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
                 {"end", {end, "LL"}}})
                                      ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 5 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
torch/csrc/jit/script/compiler.cpp: In member function ‘std::vector<torch::jit::Value*> torch::jit::script::to_ir::emitGather(const torch::jit::script::SourceRange&, torch::jit::script::TreeList&&, size_t)’:
torch/csrc/jit/script/compiler.cpp:415:60: error: converting to ‘const ListAttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > >}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<const std::vector<double>, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<const std::vector<double>, std::basic_string<char> > > >]’
                {{"dim", {0, "LL"}}, {"index", {idx, "LL"}}})
                                                            ^
torch/csrc/jit/script/compiler.cpp:345:9: note: in passing argument 5 of ‘torch::jit::Node* torch::jit::script::to_ir::emitNode(torch::jit::NodeKind, std::vector<torch::jit::Value*>, size_t, const AttributeMap&, const ListAttributeMap&)’
   Node* emitNode(
         ^
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/home/hzy/pytorch -I/home/hzy/pytorch/torch/csrc -I/home/hzy/pytorch/torch/lib/pybind11/include -I/home/hzy/pytorch/torch/lib/tmp_install/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/TH -I/home/hzy/pytorch/torch/lib/tmp_install/include/THNN -I/home/hzy/pytorch/torch/lib/tmp_install/include/ATen -I/home/hzy/anaconda35/lib/python3.5/site-packages/numpy/core/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/home/hzy/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/hzy/anaconda35/include/python3.5m -c /home/hzy/pytorch/torch/csrc/generated/cuda_TensorChar.cpp -o build/temp.linux-x86_64-3.5/home/hzy/pytorch/torch/csrc/generated/cuda_TensorChar.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN -DWITH_SCALARS
error: command 'gcc' failed with exit status 1

I find a issue which fixed by update cuDNN, but I think my cuDNN7 is enough for compiling. thanks

**Comment by goldsborough** [comment]
Can you change `const AttributeMap& attributes = {}` to `const AttributeMap& attributes = AttributeMap()` in those lines (same for `ListAttributeMap`)? @bddppq

**Comment by oxanderv** [comment]
in mac xcode-select --install solve the problem

**Comment by ngimel** [comment]
gcc 4.9 and cuda 9 are not supported, minimum required gcc version is 5.2
