### ISSUE TITLE
[collect_env] Unable to collect CUDA version anymore

### ISSUE THREAD

**Issue by frgfm** [pytorch/pytorch#51840]
## 🐛 CUDA version collection

Simply put, the environment collection script seems to no longer be working to get the CUDA version recently

## To Reproduce

For minimal reproduction, instead of using the full script:
```
from torch.utils.collect_env import get_running_cuda_version, run
print(get_running_cuda_version(run))
```
which yield 
```
None
```

I suspect the [regex](https://github.com/pyronear/pyro-vision/blob/master/scripts/collect_env.py#L112) to no longer be working with latest versions of nvcc.

## Expected behavior

Since my `nvcc --version` returns:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```
I was expecting it to correctly pick it up

## Environment

 - PyTorch Version: 1.7.1
 - OS: Linux Ubuntu 20.04 
 - How you installed PyTorch: conda
 - Python version: 3.8
 - CUDA/cuDNN version: CUDA 11.0, cuDNN 8.0.5
 - GPU models and configuration: GeForce RTX 2070, driver 450.102.04
 - Any other relevant information: I was able to reproduce this on Windows with CUDA 11 as well.

cc @ngimel

**Comment by csukuangfj** [comment]
I encountered the same problem some time ago. Please see the description in https://github.com/k2-fsa/k2/pull/584

- For CUDA 11.0
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```

- For CUDA 10.1
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

There is an extra line `Build cuda_11.0_bu.TC445_37.28540450_0` for CUDA 11.0, which cannot be handled
by `torch.utils.collect_env.get_running_cuda_version` since it uses a pattern `r"V(.*)$"` without `re.MULTILINE`.
Therefore, `torch.utils.collect_env.get_running_cuda_version` returns `None` for CUDA 11.0

**Comment by izdeby** [comment]
Closing as resolved.

**Comment by frgfm** [comment]
@izdeby since there is the closing keyword in #51852, this issue will be closed once the PR is merged on master. But as of now, it has not been merged or reviewed, perhaps we should keep the issue open in the meantime?

**Comment by izdeby** [comment]
Sorry, didnt see the PR. Reopening
