### ISSUE TITLE
[FR] Initialize module on specified device

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#51887]
## 🚀 Feature
Provide a way to initialize a module on a specified device. Currently, modules are always initialized on CPU, and must be moved to another device (e.g. GPU) after initialization.

## Motivation
This functionality is essential for initializing modules that are too big to fit in CPU memory. Further, albeit less importantly, initializing directly on the desired device reduces some overhead.

## Pitch
No specific API is being proposed yet. This issue is to discuss whether or not this functionality can and should be provided, and pros / cons of the various approaches for doing so.

The related issue [#27878](https://github.com/pytorch/pytorch/issues/27878) discusses the feasibility of using a context object / context manager to accomplish this.

## Alternatives
Keep current behavior - modules must be initialized on CPU and moved to the desired device afterwards. As mentioned before, this is not feasible for use cases involving modules that can't fit in standard RAM.

cc @albanD @mruberry @jbschlosser

**Comment by gchanan** [comment]
There's also remote modules: https://github.com/pytorch/pytorch/issues/37136

**Comment by ngimel** [comment]
There's an obvious addition here "with specified dtype". There's also a related request "don't materialize until device placement is known", which could happen some time after model initialization. We might want a separate discussion for delayed initialization though, and perhaps it can be solved with remote modules.

**Comment by vadimkantorov** [comment]
the discussion about skipping initialization: https://github.com/pytorch/pytorch/issues/29523

**Comment by mrshenli** [comment]
>  There's also a related request "don't materialize until device placement is known", which could happen some time after model initialization.

yep, we have seen this request from distributed training applications multiple times.

**Comment by ezyang** [comment]
Just to get the API discussion going, this is what I think is the simplest, smallest possible modification to nn.Module that would let you initialize modules on a specific device: https://github.com/pytorch/pytorch/pull/53144

**Comment by ppwwyyxx** [comment]
This might be related to the meta-learning paradigm, i.e. to use one network to predict parameters of another network. There are libraries made for this (https://github.com/tristandeleu/pytorch-meta/blob/master/torchmeta/modules/linear.py). It seems to be another potential use case of this feature.

With this feature and #53144 to allow creating a module on null/meta device, it seems we'll be able to do the following to easily achieve meta learning, reusing nn.Conv2d without having to create custom MetaConv2d:

```python
def __init__():
   self.meta_conv = Conv2d(..., device='meta')
   self.parameter_predictor = PredictorNet(num_param=sum(k.numel() for k in self.meta_conv.parameters()))

def forward(x):
  params = self.parameter_predictor(x)
  with temporary_set_params(self.meta_conv, params):
      return self.meta_conv(x)
```

**Comment by ezyang** [comment]
@ppwwyyxx I think this is just an unfortunate terminology clash; the "meta" in meta-tensor doesn't have anything to do with the "meta" in meta-learning. Though perhaps modules could adopt the `params` convention? It seems like a harder sell, unfortunately.

**Comment by ppwwyyxx** [comment]
The terminology clash is fortunate if meta-tensor can be used to implement meta-learning. What it requires is to (1) create a (regular) module without initializing its parameters, and (2) later temporarily setting its parameters to what is predicted by another network. (1) is related to #53144, and (2) seems implementable for a user.

**Comment by ezyang** [comment]
@ppwwyyxx Oh ho, I understand in more detail, and now I agree that meta tensors indeed solve your problem in this case!

**Comment by jbschlosser** [comment]
This is now supported for all modules provided by `torch.nn`. Example:

```python
import torch

# Initialize directly onto GPU.
m = torch.nn.Linear(10, 1, device='cuda')
```
