### ISSUE TITLE
[RFC] Parameter pack class for testing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5188]
In our test code, we have a lot of things that look like this:

```
    dict(
        module_name='ConvTranspose2d',
        constructor_args=(3, 4, 3, (2, 3), 1, (1, 1), 1, False),
        input_size=(1, 3, 6, 7),
        cudnn=True,
        desc='no_bias',
    ),  
```

Notice `constructor_args`: what do these all mean? It's hard to tell, because they are specified completely positionally.

I propose we introduce a small, new abstraction to make it easier to express these cases explicitly:

```
class ParameterPack(object):
    """
    Represents an arbitrary function invocation from Python, which can
    be saved and then used to invoke another function.

    Suppose you write:

    >>> f(0, 1, output_padding=2)

    You can write this function call equivalently with a parameter
    pack:

    >>> p = params(0, 1 output_padding=2)
    >>> p.invoke(f)
    """
    def __init__(self, *args, **kwargs):
        self.args = args
        self.kwargs = kwargs

    def invoke(self, f):
        return f(*args, **kwargs)
```

The intent now is that `constructor_args can be rewritten as:

```
        constructor_args=params(3, 4, 3, stride=(2, 3), padding=1, output_padding=(1, 1), groups=1, bias=False),
```

cc @mruberry @VitalyFedyunin

**Comment by apaszke** [comment]
Sounds good to me!

**Comment by ngimel** [comment]
cc @mruberry, maybe this is useful for test rewrites with op lists.

**Comment by mruberry** [comment]
I think this PR can safely be closed due to age. It's a cool idea but we should revisit representation with our current test framework architecture.
