### ISSUE TITLE
[docs] clip_grad_value_ returns some undocumented value

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#51945]
https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_value_.html?highlight=clip_grad_value_#torch.nn.utils.clip_grad_value_ says that it returns None, but in fact it returns a scalar tensor. What's contained in it? input tensor norm? max abs value?

I propose to document what it returns

Maybe same for `clip_grad_norm_`?

cc @jlin27 @mruberry @albanD @jbschlosser

**Comment by jbschlosser** [comment]
I don't see this behavior in 1.8.

`clip_grad_value_` returns None as [documented](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_value_.html), and `clip_grad_norm_` returns the total norm as [documented](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html).

**Comment by vadimkantorov** [comment]
Sorry. I got confused. I thought I was using clip_grad_value_, but it was commented out and in fact clip_grad_norm_ was used :(

I'll close this. As suggestion, it could also return the max abs value before the clip
