### ISSUE TITLE
[numpy] torch.frac is not consistent for Infinity's with the fractional part of NumPy's modf

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#51948]
```python
>>> import torch
>>> torch.__version__
'1.8.0a0+fcf8b71'
>>> t = torch.tensor(float('inf'))
>>> torch.frac(t)
tensor(nan)
>>> import numpy as np
>>> np.modf(t.numpy())[0]
0.0
>>> t = torch.tensor(float('-inf'))
>>> torch.frac(t)
tensor(nan)
>>> np.modf(t.numpy())[0]
-0.0
```

**Note**: NumPy is consistent with C++ standard

https://en.cppreference.com/w/cpp/numeric/math/modf

```
If x is ±0, ±0 is returned, and ±0 is stored in *iptr.
If x is ±∞, ±0 is returned, and ±∞ is stored in *iptr.
If x is NaN, NaN is returned, and NaN is stored in *iptr.
The returned value is exact, the current rounding mode is ignored
```

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
Thanks for the careful attention to detail, @kshitij12345. It looks like this function is unused, although it is tested.

Would you file a follow-up issue to consider deprecating torch.frac()?

**Comment by kshitij12345** [comment]
Even though it is unused are we sure we want to deprecate `frac` as I don't think there is another function which provides that functionality.

**Comment by mruberry** [comment]
@kshitij12345 On the issue to discuss the deprecation of frac, why don't you propose that before it's deprecated we implement divmod and modf so people have an alternative? From the static analysis @rgommers provided, divmod is a top 600 NumPy function, and modf is a top 400 NumPy function, and neither is in PyTorch. (The current NumPy Compat issue even has a request for divmod.)
