### ISSUE TITLE
Recent commit to torch._six means that apex no longer imports

### ISSUE THREAD

**Issue by dbonner** [pytorch/pytorch#51959]
## 🐛 Bug

Since this commit: https://github.com/pytorch/pytorch/commit/58eb23378f2a376565a66ac32c93a316c45b6131
apex can not be imported:

## To Reproduce

1. import apex

Error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/home/daniel/py38/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/daniel/py38/lib/python3.8/site-packages/torch/_six.py)

## Expected behavior
No error message

## Environment
Ubuntu 20.10, gcc-10.2.1, pyenv, python 3.8.7, Nb: This is a virtual environment created with 'python -m venv', not conda
python collect_env.py 
Collecting environment information...
PyTorch version: 1.8.0a0+034a007
These other packages are also built from latest source:
torchvision, torchaudio, torchtext, apex, tensorflow, byteps, horovod, pytorch-lightning (pinned to version 1.1.3), transformers, NeMo.
All other packages are installed by pip.
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A (no)

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0  (gcc-10 version 10.2.1)
Clang version: Could not collect (nil)
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: 8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.1.3
[pip3] torch==1.8.0a0+034a007
[pip3] torch-stft==0.1.4
[pip3] torchaudio==0.8.0a0+77de2b9
[pip3] torchtext==0.9.0a0+3de3fcf
[pip3] torchvision==0.9.0a0+17e1ec4
[conda] Could not collect
GPU: tried this on 3 machines: Razer Blade 2080 max q, Desktop with 2080 Ti, Server with 8x A100 GPUs.  Nb: All three are set up identically, and built from source within a few hours of each other.

Build command for pytorch:

MAX_JOBS=256 CMAKE_PREFIX_PATH=/home/daniel/py38 USE_CUDA=1 USE_CUDNN=1 USE_DISTRIBUTED=1 USE_SYSTEM_NCCL=1 TORCH_CUDA_ARCH_LIST="7.5;8.0" CUDA_HOME=/usr/local/cuda-11.2 CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu CUDNN_INCLUDE_DIR=/usr/include/x86_64-linux-gnu \time pip install -v ./

## Additional context
Apex can not find container_abcs from torch._six anymore. 
This also results in pytorch_lightning and NeMo being unable to be imported.  I think this is because when I import ptorch_lightning and NeMo, apex also gets automatically imported.

cc @mcarilli @ptrblck

**Comment by xwang233** [comment]
I see the same issue. We may need to update apex. @ptrblck @mcarilli

**Comment by mcarilli** [comment]
Hopefully https://github.com/NVIDIA/apex/pull/1049 can fix, but I can't emphasize https://github.com/NVIDIA/apex/pull/1049#issuecomment-776225268 strongly enough.

**Comment by dbonner** [comment]
Thanks @xwang233, @mcarilli and @ShoufaChen
I can confirm that https://github.com/NVIDIA/apex/pull/1049/commits/627a4a66d52a530b7a32cb6d920d2d7d8ada5db8 fixes the problem with importing apex on my machines.
All the best,
Dan

**Comment by dbonner** [comment]
Thanks everyone. Fixed and merged :)

**Comment by JVedant** [comment]
It got solved or me by adding ```import collections.abc as container_abcs``` in
miniconda3/envs/environment_name/lib/python3.8/site-packages/torch/_six.py

Reference: https://github.com/PyTorchLightning/pytorch-lightning/discussions/9487#discussioncomment-1321553
