### ISSUE TITLE
`sorted` argument in `torch.Tensor.topk` has no use?

### ISSUE THREAD

**Issue by back2yes** [pytorch/pytorch#51960]
## To Reproduce

1.
`x = torch.FloatTensor([1,8,2,5,3,7])`

2.
`torch.topk(x, 3, sorted=True)`
returns `[8, 7, 5]`

3.
`torch.topk(x, 3, sorted=False)`
returns `[8, 7, 5]`

## Expected behavior

I am expecting to get unsorted values by setting `sorted` argument to `False` (my first understanding is the order should be the same as the input)

## Environment
Tried Win10, pytorch nightly '1.8.0.dev20201104+cu110'

I tried this on Ubuntu 18.04, pytorch 1.7, the results were fine.
Again, I tried this on Win10, pytorch 1.7, both results were sorted.

**Comment by colesbury** [comment]
> I am expecting to get unsorted values by setting sorted argument to False (my first understanding is the order should be the same as the input)

If sorted is `False` they are in an arbitrary order that depends on the most efficient way to compute it. Sometimes that coincides with the sorted order, but not always. It does **not** mean the output matches the input order.

If you want to see the return values out of order, use a bigger k and a bigger input.

**Comment by mrshenli** [comment]
Hey @back2yes, I am closing this issue. Please feel free to reopen if using bigger k and bigger input still do not show the impact of `sorted`. 

For future questions, please use the PyTorch forum: https://discuss.pytorch.org/
