### ISSUE TITLE
distributed/test_c10d_spawn segfaults after [Sharing CUDA tensors] note

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#51961]
## 🐛 Bug

When building PyTorch and running the distributed/test_c10d_spawn test I'm getting a warning message about `[Sharing CUDA tensors]` and a segfault afterwards. This hints at a static destruction order fiasco type of problem.

## To Reproduce

1. Build PyTorch
1. Run tests

```
Running distributed/test_c10d_spawn ... [2021-02-09 02:53:59.883563]
Executing ['/scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/Python/3.8.6-GCCcore-10.2.0/bin/python', 'distributed/test_c10d_spawn.py', '--verbose'] ... [2021-02-09 02:53:59.883652]
test_cpu (__main__.DistributedDataParallelSingleProcessTest) ... ok
test_cuda (__main__.DistributedDataParallelSingleProcessTest) ... /tmp/easybuild-tmp/eb-Hiv4uQ/tmpPi3Hsz/lib/python3.8/site-packages/torch/nn/parallel/distributed.py:447: UserWarning: Single-Process Multi-GPU is not the recommended mode for DDP. In this mode, each DDP instance operates on multiple devices and creates multiple module replicas within one process. The overhead of scatter/gather and GIL contention in every forward pass can slow down training. Please consider using one DDP instance per device or per module replica by explicitly setting device_ids or CUDA_VISIBLE_DEVICES. 
  warnings.warn(
ok
test_rnn (__main__.DistributedDataParallelSingleProcessTest) ... /tmp/easybuild-tmp/eb-Hiv4uQ/tmpPi3Hsz/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:64: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
ok
test_shared_allgather_chunk_gloo (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_allgather_gloo (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_allgather_nccl (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_allreduce_gloo (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_allreduce_nccl (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_broadcast_gloo (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_broadcast_nccl (__main__.ProcessGroupShareTensorTest) ... ok
test_shared_reduce_nccl (__main__.ProcessGroupShareTensorTest) ... ok

----------------------------------------------------------------------
Ran 11 tests in 55.287s

OK
[W CudaIPCTypes.cpp:22] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Traceback (most recent call last):
  File "run_test.py", line 745, in <module>
    main()
  File "run_test.py", line 728, in main
    raise RuntimeError(err_message)
RuntimeError: distributed/test_c10d_spawn failed! Received signal: SIGSEGV
```

Note how all tests finished successfully and then fail

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source 
 - Build command you used (if compiling from source):  `PYTORCH_BUILD_VERSION=1.7.1 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=96 BLAS=Eigen USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=1 CUDNN_LIB_DIR=/scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/cuDNN/8.0.4.30-CUDA-11.1.1/lib64 CUDNN_INCLUDE_DIR=/scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/cuDNN/8.0.4.30-CUDA-11.1.1/include USE_SYSTEM_NCCL=1 NCCL_INCLUDE_DIR=/scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/NCCL/2.8.3-CUDA-11.1.1/include USE_METAL=0   /scratch/ws/1/s3248973-EasyBuild/easybuild-rome/software/Python/3.8.6-GCCcore-10.2.0/bin/python setup.py build`
 - Python version: 3.8.6
 - CUDA/cuDNN version: 11.1.1
 - GPU models and configuration: 8 A100 GPUs

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by Flamefire** [comment]
Checking the code this seems to be indeed a destruction ordering problem:
- `cuda_ipc_global_entities` is a file local instance with static lifetime
- `REGISTER_FREE_MEMORY_CALLBACK` is called which also creates an instance of static lifetime
- The latter calls `CudaIPCCollectCallback` on destruction which accesses `cuda_ipc_global_entities`

So if `cuda_ipc_global_entities` is destroyed first, there will be a crash. Potential solution (quite hacky but works): Use a bool variable or pointer which is set and unset in the ctor/dtor of `CudaIPCGlobalEntities` and signals, if it is alive. This can then be checked before accessing the instance and this marker being a trivial type allows safe access at all times

Better: Access `cuda_ipc_global_entities` during construction of the REGISTER_FREE_MEMORY_CALLBACK instance so the order of construction and hence destruction is defined.

**Comment by SciPioneer** [comment]
@Flamefire  Thanks for reporting this and the analysis!

@VitalyFedyunin I saw your have fixed similar issues in #16854. Do you have any idea? Thanks!

**Comment by SciPioneer** [comment]
To reproduce this error, no need to run all the tests in test_c10d_spawn. Can just run a single test instead:

`pytest test/distributed/test_c10d_spawn.py -k test_shared_reduce_nccl`

**Comment by Flamefire** [comment]
Using some printf I was able to verify this: Call order in that case:
- `~CudaIPCGlobalEntities()`
- `ReturnRefCounter`
- `CudaIPCSentDataDelete`

Both of the latter functions access `cuda_ipc_global_entities` which explains the crash

**Comment by Flamefire** [comment]
FWIW: I tested https://github.com/pytorch/pytorch/pull/53080 and it does NOT resolve this issue.

**Comment by Flamefire** [comment]
@pritamdamania87 I observed the following with e.g. `distributed/test_c10d_spawn_nccl.py -- ProcessGroupShareTensorTest.test_shared_reduce_nccl`

- `CudaIPCSentDataLimbo_.clear_shared_blocks();` is called from the destructor of CudaIPCGlobalEntities as of your PR
- This deletes instances of `CudaIPCSentData` which hold `at::DataPtr` created by `GetNewRefCountedSentData`
- This means `CudaIPCSentDataDelete` is called with still active pointers
- Hence `CudaIPCSentDataLimbo_.add` is called adding a new value to `shared_blocks_`

This is VERY problematic:
- Neither `CudaIPCSentDataLimbo::size` nor `CudaIPCSentDataLimbo::clear_shared_blocks` protect the list with the mutex as would be required --> Race conditions possible
- More importantly here: While `shared_blocks_.clear()` is running, new entries are added to it leading to corruption and a subsequent crash happening when the CudaIPCSentDataLimbo destructor is calling `collect`

I would suggest to revert the PR https://github.com/pytorch/pytorch/pull/53080 and instead use mine from https://github.com/pytorch/pytorch/pull/56141 which does not produce those crashes. Note that using mine AND yours DOES now crash, but differently.

**Comment by pritamdamania87** [comment]
> I would suggest to revert the PR #53080 and instead use mine from #56141 which does not produce those crashes. Note that using mine AND yours DOES now crash, but differently.

Instead of reverting, I'd suggest adding the necessary changes into https://github.com/pytorch/pytorch/pull/56141 itself and also mention this in the summary so the change is clear and is in one place.

**Comment by Flamefire** [comment]
Not sure here... I partially reverted it by removing the shared_blocks_.clear replacing it by the safer solution. Check the updated PR
