### ISSUE TITLE
[feature request] support batch diag

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#5198]
Should be easy to implement. But we need to figure out a good name/API. We can't reuse `torch.diag` as it will be ambiguous when input is 2D. `bdiag` sounds weird to me..

**Comment by soumith** [comment]
how about `torch.diag(batch=True)`? We can have similar extensions to other operators...

**Comment by gwgundersen** [comment]
@SsnL, any reason you closed this? This would be a nice feature.

**Comment by SsnL** [comment]
@gwgundersen It's implemented now :)

**Comment by SsnL** [comment]
@gwgundersen at https://github.com/pytorch/pytorch/pull/6718

**Comment by talesa** [comment]
Is the batch semantics (being able to address arbitrary dimension for expansion) also available now for the 1D=>2D case or just for the 2D=>1D?

**Comment by awav** [comment]
Hello everyone, I'm not sure that requested feature addressed in other PRs (according to https://discuss.pytorch.org/t/batch-of-diagonal-matrix/13560/2). I need a `tensorflow.matrix_diag` method and new `torch.diagonal` works with multi dimensional cases, but doesn't do job in reverse (I don't mean AD reverse mode).

**Comment by rudaoshi** [comment]
Why this issue is closed? the  #6718 does not implement this feature. @SsnL

**Comment by rudaoshi** [comment]
> I'm not sure I understand it correctly, but maybe you are looking for `diagflat`?

diagflat does not work in batch.

**Comment by SsnL** [comment]
@awav @rudaoshi Ah I'm sorry. I opened the issue to request the n-D to (n-1)-D case. I opened a new issue on matrix diag at https://github.com/pytorch/pytorch/issues/12160 .
