### ISSUE TITLE
OpInfo tests fail gradcheck for ops with TensorList inputs. 

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#51996]
For ops like ``torch.stack`` and ``torch.linalg.multi_dot`` that take a ``Tensor[]`` as input as opposed to a single Tensor, OpInfo testing does not work properly.

If the `sample_inputs_func` returns a tuple of tensors per SampleInput, it will be passed as individual positional parameters to the op. If instead each SampleInput is returned with a list, then gradcheck will fail with the following error:

```
FAILED test/test_ops.py::TestGradientsCPU::test_fn_grad_linalg_multi_dot_cpu_float64 - ValueError: gradcheck expects at least one input tensor to require gradient, but none of the them have requires_grad=True.
```

The current workaround is to create a lambda as follows:
```
op=lambda *args, out=None: torch.linalg.multi_dot([*args], out=out),
```

However, this is changing the actual op which can cause problems in the future, for instance, when comparing the results of the op against NumPy.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @jianyuh @mruberry @heitorschueroff @walterddr @IvanYashchuk @VitalyFedyunin

**Comment by mruberry** [comment]
cc @albanD and @Lilyjjo 

Let's focus exclusively on the autograd side of this issue for the moment, as how we address it may affect the fix for the jit tests.

@albanD I think this is a bug in {grad, gradgrad}check where they don't handle tuple inputs properly? 

Before @anjali411 implemented its OpInfo, for example, torch.stack had a custom autograd test (see https://github.com/pytorch/pytorch/commit/8fb5f1693164cdba410a4548e7a2bdbf6159dd57) but I don't think it used gradcheck. When given a tuple of tensors as input gradcheck will try to splat them when calling the function, but functions like torch.stack don't support a variable number of tensor arguments. 

One way to fix this might be to add a "grad_input_function" to gradcheck. This idea has come up elsewhere (https://github.com/pytorch/pytorch/issues/50837 cc @IvanYashchuk), too. 

@albanD, seems like you're in favor of that solution on the other issue, so let's start by trying it out as a fix for this, too?

**Comment by albanD** [comment]
> One way to fix this might be to add a "grad_input_function" to gradcheck. This idea has come up elsewhere (#50837 cc @IvanYashchuk), too.

The proposal there was not to modify gradcheck but opinfo right? And have a pre-processing function before calling the user function.

> @albanD I think this is a bug in {grad, gradgrad}check where they don't handle tuple inputs properly?

This is explicitly not supported. The doc says: "func (function) – a Python function that takes Tensor inputs and returns a Tensor or a tuple of Tensors": tuple of Tensors is not supported as input to the function.
So I think the "fix" is to wrap the user function in another function that does the massaging of the arguments.

**Comment by mruberry** [comment]
> > One way to fix this might be to add a "grad_input_function" to gradcheck. This idea has come up elsewhere (#50837 cc @IvanYashchuk), too.
> 
> The proposal there was not to modify gradcheck but opinfo right? And have a pre-processing function before calling the user function.

You are correct.

> This is explicitly not supported. The doc says: "func (function) – a Python function that takes Tensor inputs and returns a Tensor or a tuple of Tensors": tuple of Tensors is not supported as input to the function.
> So I think the "fix" is to wrap the user function in another function that does the massaging of the arguments.

Yes, I think this is conceptually what the input function would do.

**Comment by anjali411** [comment]
I don't think we need to make any updates in `OpInfo`. It's easy enough to handle this case by just passing a lambda function in `op`. For example, check out [tests](https://github.com/pytorch/pytorch/blob/a1b8f3d4b6ada3721a3d9d8266f86dcb04f17fcb/torch/testing/_internal/common_methods_invocations.py#L2127) for `stack`, `vstack` etc.

**Comment by mruberry** [comment]
We could continue to wrap ops in lambdas, that's true, but that's also what we want to avoid. Wrapping ops in lambdas is going to bite us later when we go to compare with NumPy references, for example. Basically we want to only wrap the op in a lambda in some contexts (like gradcheck).

**Comment by mruberry** [comment]
Offline discussion w/@albanD: let's continue to investigate wrapping the op in a lambda before gradchecking. Maybe subsume the current output_func post-process, which currently gets wrapped with the op, too.

**Comment by zou3519** [comment]
Couldn't gradcheck flatten the list of tensors, do things with the tensors, and then reconstruct the list of tensors when it comes time to call the function?

**Comment by albanD** [comment]
The question is how do you differentiate between a single argument that is a tuple of tensor vs a tuple containing multiple Tensors that should be passed as separate arguments to the function?

**Comment by zou3519** [comment]
> The question is how do you differentiate between a single argument that is a tuple of tensor vs a tuple containing multiple Tensors that should be passed as separate arguments to the function?

I am not suggesting that we would do this (I'm just curious), but to go down this rabbit hole: we'd have to modify the signature of gradcheck so that instead of taking inputs as `inputs: Union[torch.Tensor, Sequence[torch.Tensor]]` (that is where the ambiguity comes from), it would take in a Tuple of inputs to be passed to the function.

So if a user wanted to pass in multiple tensors, they would do `gradcheck(..., inputs=(a, b, c))`
If a user wanted to pass in a single argument that is a list of tensors, they would do: `gradcheck(..., inputs=([a, b, c],))`

This would make the handling of functions with TensorLists nicer, especially if we think that we'll add more TensorList operations to the API

**Comment by heitorschueroff** [comment]
I think @zou3519's suggestion is the cleanest approach from an API perspective. Otherwise, wrapping the function in a lambda that converts from the flattened list of tensors back into the correct arguments to the op is not so straightforward. What if we had an op that takes 2 TensorLists. We'd have to keep track of counts to know go back from the reconstruct the input arguments from the flattened list of tensors.

**Comment by albanD** [comment]
It is cleaner but is very BC-breaking :/ 
We would need to go through a full cycle of deprecation for this.

And yes if it takes multiple Tensor list, you will need to do slicing. Which can still be done automatically, but is indeed a bit more complex.

**Comment by zou3519** [comment]
> It is cleaner but is very BC-breaking :/
> We would need to go through a full cycle of deprecation for this.

We could have our internal gradcheck do this first (that's why we have an internal gradcheck :D)

**Comment by anjali411** [comment]
> > It is cleaner but is very BC-breaking :/
> > We would need to go through a full cycle of deprecation for this.
> 
> We could have our internal gradcheck do this first (that's why we have an internal gradcheck :D)

internal gradcheck??? which one is that? I thought there is just the one (the one in `gradcheck.py`)

**Comment by zou3519** [comment]
> internal gradcheck??? which one is that? I thought there is just the one (the one in `gradcheck.py`)

It is here: https://github.com/pytorch/pytorch/blob/c8b3686a3e4ba63dc59e5dcfe5db3430df256833/torch/testing/_internal/common_utils.py#L1941-L1954

Here's the original issue for context: https://github.com/pytorch/pytorch/issues/49409

**Comment by imaginary-person** [comment]
The failure causes of the following tests seems to be similar to that of `test_fn_grad_linalg_multi_dot_cpu_float64` :

```
TestCommonCUDA.test_variant_consistency_jit_pow_cuda_complex128 
TestCommonCUDA.test_variant_consistency_jit_pow_cuda_complex64
TestCommonCPU.test_variant_consistency_jit_pow_cpu_complex128 
TestCommonCPU.test_variant_consistency_jit_pow_cpu_complex64
```

**[Failure cause](https://app.circleci.com/pipelines/github/pytorch/pytorch/280859/workflows/252b3a2f-6678-4f60-9261-db25eec5e512/jobs/11302001/tests#failed-test-4)**
```
RuntimeError: expected ) but found 'ident' here:
  File "<string>", line 3

def the_method(i0):
    return torch.pow(i0, (3.14+3.14j))
                                   ~ <--- HERE
```

**Comment by mruberry** [comment]
> The failure cause of the following tests seems to be similar to that of `test_fn_grad_linalg_multi_dot_cpu_float64` :

That looks like the jit's failure to understand complex literals. I have a PR disabling those tests for dtypes other than float32, btw. We get too much noise and very little signal from them for other dtypes.

**Comment by ezyang** [comment]
btw complex literal support is coming very soon, #53269 52881
