### ISSUE TITLE
test_optim.py failures for CUDA 11.2 on CI

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#51992]
## 🐛 Bug

The following tests in test_optim.py fail in CI on CUDA 11.2 in linux and windows.
test_adadelta
test_adam
test_adamw
test_multi_tensor_optimizers
test_rmsprop

## To Reproduce

1. Run the CI jobs pytorch_linux_xenial_cuda11_2_cudnn8_py3_gcc7_test and pytorch_windows_vs2019_py36_cuda11.2_test2
2. Get the following logs with error messages:
Linux: https://app.circleci.com/pipelines/github/pytorch/pytorch/271291/workflows/ffe1be08-5d55-459e-98bd-200d6387e41c/jobs/10779915
Windows: https://app.circleci.com/pipelines/github/pytorch/pytorch/271865/workflows/2ac5bd63-6dba-4169-9f5d-7ccaf7ab33b4/jobs/10806271

## Expected behavior

Those tests should pass.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ngimel

**Comment by ngimel** [comment]
cc @izdeby @mcarilli - this is possibly related to multi-tensor-apply.

**Comment by mcarilli** [comment]
What generation GPU did these tests run on? That's not obvious from the build logs (at least not to me).

**Comment by janeyx99** [comment]
> What generation GPU did these tests run on? That's not obvious from the build logs (at least not to me).

The driver version was upgraded to 460.39 (you can see the nvidia-smi result in the "Set up CI Environment after Attach Workspace" part of the job).

**Comment by ngimel** [comment]
Right, but what is the GPU model? Is it still M60?

**Comment by ngimel** [comment]
This is a real bug, likely a compiler bug with cuda 11.2. Easy repro:
```
import torch
device = "cuda"
dtype = torch.float32
grads = [torch.ones(3,2, device=device, dtype=dtype), torch.ones(3, device=device, dtype=dtype)]
square_avg = [torch.zeros(3,2, device=device, dtype=dtype), torch.zeros(3, device=device, dtype=dtype)]
alpha=.99
torch._foreach_mul_(square_avg, alpha)
torch._foreach_addcmul_(square_avg, grads, grads, value=1 - alpha) # should be 0.01
#print(square_avg[0], square_avg[1])
avg = torch._foreach_sqrt(square_avg)
print("avg: ", avg[0], avg[1]) #should be 0.1, can be whatever depending in previous prints. With this version it's 0
```
`_foreach_sqrt` individually produces the write results, however when it follows other ops, it's wrong. inplace `sqrt_` version produces correct results.

**Comment by zasdfgbnm** [comment]
Repro of this issue with standalone C++ is at: https://github.com/zasdfgbnm/multi_tensor_apply
