### ISSUE TITLE
CUDA error: too many resources requested for launch in Windows CI for CUDA 11.2

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#52002]
## 🐛 Bug

Two tests in `test_nn.py` fail in Windows for CUDA 11.2.

## To Reproduce

1. Run CI for pytorch_windows_vs2019_py36_cuda11.2_test2
2. Fail the following two tests in `test_nn.py` with the error message `RuntimeError: CUDA error: too many resources requested for launch`:
test_EmbeddingBag_per_sample_weights_and_new_offsets_cuda_int64_float64
test_EmbeddingBag_per_sample_weights_and_offsets_cuda_int64_float64

Example logs: https://app.circleci.com/pipelines/github/pytorch/pytorch/271775/workflows/96bdeeef-6160-48e4-9911-a9c3115c4a46/jobs/10800169

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by xwang233** [comment]
The workaround was to add a `C10_LAUNCH_BOUNDS` to the cuda kernel. cc @ptrblck @mcarilli

**Comment by ngimel** [comment]
@janeyx99 can you check if replacing 1024 with 512 here  fixes it? https://github.com/pytorch/pytorch/blob/12d85b536e5d1710968d4d6f2a02281b8a010208/aten/src/ATen/native/cuda/EmbeddingBag.cu#L450

**Comment by janeyx99** [comment]
> @janeyx99 can you check if replacing 1024 with 512 here fixes it?

That does fix it! The test passes here: https://app.circleci.com/pipelines/github/pytorch/pytorch/272138/workflows/eeb21ae4-038b-48d5-b7d5-058991e39eeb/jobs/10827075 for PR 52051.
