### ISSUE TITLE
Distributed Profiling does not work with DDP's all_reduce 

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52020]
## 🐛 Bug

https://github.com/pytorch/pytorch/pull/46471 enabled distributed profiling, but it currently does not cover the all_reduce initiated by DDP's backward pass. This is because this all_reduce is triggered as an autograd hook, and autograd can execute these hooks in a non-main thread. However, the profiler would only be enabled thread locally on the main thread, so we'd run into this issue. 

## To Reproduce

1. Run DDP fwd + backward under profile, and observe that all_reduce does not show up in profiling output:

```
            batch = 3
            dim = 10
            learning_rate = 0.03
            torch.cuda.set_device(self.rank)
            model = nn.Linear(dim, dim, bias=False)
            inp = torch.rand(batch, dim, device=self.rank)
            with torch.autograd.profiler.profile() as prof:
                net = torch.nn.parallel.DistributedDataParallel(
                    model.cuda(self.rank), device_ids=[self.rank]
                )
                for i in range(6):
                        loss = net(inp).sum()
                        loss.backward()
                        torch.cuda.synchronize(device=self.rank)

            if self.rank == 0: print(prof.key_averages().table())
```

To fix this, we can do either of the following:
1. When creating these hooks, wrap the thread-local state and the profiler enabled flag will be carried over. However, this means that the profiler would have to be enabled when DDP is initialized, but user may want to do it on-demand for only a few iterations. 
2. Add APIs to reducer that allow saving/retrieving of thread local state. Then, in DDP's forward pass we can save the TLS state, and in backward pass we can retrieved the state set by the main thread, and enable it in non-main thread autograd hook.
3. Another solution is to manually check if the profiler is enabled in the post hooks, and then enable the profiler if so. However, this is probably a non-starter as enabling the profiler has much more overhead than setting a few thread-local flags, and there can be millions of hooks executed (one per parameter). 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by nbcsm** [comment]
@rohan-varma, seems the fix is for gloo only? according to the PR title.
Is there plan to support NCCL backend as well?
Thanks.

**Comment by rohan-varma** [comment]
@nbcsm Yes good point, will reopen the issue. The nccl fix is a bit more involved, please see https://github.com/pytorch/pytorch/issues/52246 for more details.

**Comment by rohan-varma** [comment]
This should be fixed because torch.profiler appropriately captures GPU kernel events.
