### ISSUE TITLE
[deprecation] deprecate `torch.frac` 

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#52027]
Deprecate `torch.frac` as it is relatively unused and gives incorrect output for `inf` input values.

**Note**: Since none of the existing Pytorch operator provides this functionality, we must ensure that `divmod` or `modf` are implemented in Pytorch first before proceeding.

Reference: https://github.com/pytorch/pytorch/issues/51948#issuecomment-776479722

Usage Data:
- torch.frac() is used by torchaudio and possibly one other library, so we can't simply remove it.
- np.divmod() is a top 600 NumPy op, according to https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/numpy-summary.csv
- np.modf() is a top 400 NumPy op, also according to https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/numpy-summary.csv

cc @mruberry @rgommers @heitorschueroff

**Comment by VitalyFedyunin** [comment]
Triage review to decide if we are going to fix operator or deprecate it.

**Comment by mruberry** [comment]
Out of an abundance of caution, I'd like to suggest fixing this because both divmod and modf will return a second tensor, increasing memory usage.
