### ISSUE TITLE
TEST: audit uses of maybeWarnsRegex

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#52025]
Follow on for #47624, which created an `assertWarnsOnceRegex` context manager to test C-level `TORCH_WARN_ONCE`.  All the places that currently use `maybeWarnsRegex` should be replaced with the `assrtWarnsOnceRegex`, and any untested `TORCH_WARN_ONCE` code should be covered by a test.

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
maybeWarnsRegex has been removed!
