### ISSUE TITLE
Measure communicated data volume used in DDP communication hooks

### ISSUE THREAD

**Issue by SciPioneer** [pytorch/pytorch#52033]
## 🚀 Feature
Currently DDP communication hooks are only evaluated in terms of speedup and accuracy. It will be nice to also measure the communication costs in terms of bandwidth.

## Motivation

This way users can know the savings in communication or the actual compression rate if a gradient compression algorithm is used.

cc: @tvogels

**Comment by tvogels** [comment]
Are you already working on this, or are you looking for contributions?

**Comment by SciPioneer** [comment]
> Are you already working on this, or are you looking for contributions?

Given that both this issue and #52034 are quite incremental and not urgent, I created these tasks for onboarding new developers who are interested in PyTorch distributed training. These issues will be fixed in a few days by others, and I will provide some help.

Anyone will be always welcome to contribute to PyTorch community. Feel free to give us more suggestions on improving PowerSGD communication hook, even if it's very incremental. Any other ideas on optimizing distributed trainings are also highly appreciated :)

**Comment by SciPioneer** [comment]
Actual compression rate is reported in log now.
