### ISSUE TITLE
Unit test test_ddp_uneven_inputs in distributed_nccl_spawn fails recently

### ISSUE THREAD

**Issue by SciPioneer** [pytorch/pytorch#52030]
## 🐛 Bug

This unit test starts failing recently.

## To Reproduce
Run `test_ddp_uneven_inputs` in `distributed_nccl_spawn`.

Facebook:
`buck test @mode/dev-nosan caffe2/test/distributed:distributed_nccl_spawn -- test_ddp_uneven_inputs`

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
Unable to reproduce so far, feel free to reopen if it continues to occur.
