### ISSUE TITLE
Why zero_point in _fake_quantize_learnable_per_tensor is different from _fake_quantize_learnable_per_channel_affine?

### ISSUE THREAD

**Issue by KeyKy** [pytorch/pytorch#52038]
In _fake_quantize_learnable_per_channel_affine
```
Tensor zero_point_rounded = zero_point.to(at::kLong);
```

is different from

_fake_quantize_learnable_per_tensor:
```
int64_t _get_zero_point_from_tensor(
    const Tensor& zero_point,
    int64_t quant_min,
    int64_t quant_max,
    bool is_forward) {
  float zero_point_fp = zero_point[0].item<float>();
  zero_point_fp = is_forward ? std::nearbyint(zero_point_fp) : zero_point_fp + 0.5f;
  float zero_point_clamped = std::min(std::max(zero_point_fp, quant_min), quant_max);
  return static_cast<int64_t>(zero_point_clamped);
}
int64_t zero_point_val = native::_get_zero_point_from_tensor(zero_point, quant_min, quant_max, true);
```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
@raghuramank100, @z-a-f  do you know why there is a difference in the implementation between learnable per-channel and per-tensor for zero-point computation?
We don't seem to be using `_get_rounded_zero_point` in the per-channel forward function.

**Comment by haichuan-fb** [comment]
Hello, thanks for pointing out. Here we should do the similar rounding and clamp for zero_point in both forward and backward as in learnable per-tensor. We made this PR to fix it: https://github.com/pytorch/pytorch/pull/52290
