### ISSUE TITLE
Add a minimum compression rate threshold for PowerSGD communication hook

### ISSUE THREAD

**Issue by SciPioneer** [pytorch/pytorch#52034]
## 🚀 Feature

Currently PowerSGD blindly compresses any tensor as long as it is not a bias vector. Actually it should only compress the tensors of shape (x, y) if **(x + y) * rank < x * y** (i.e., there are savings in the amount of data transfer).

Since there is extra computation cost for the compression, it will be even better to add a **minimum compression rate threshold** t as another algorithm hyperparameter, such that **(x + y) * rank < x * y * t**. The default value of t can be 0.5, so PowerSGD will only compress a tensor if there is at least 50% saving in bandwidth.

cc: @tvogels

**Comment by t10-13rocket** [comment]
> ## 🚀 Feature
> Currently PowerSGD blindly compresses any tensor as long as it is not a bias vector. Actually it should only compress the tensors of shape (x, y) if **(x + y) * rank < x * y** (i.e., there are savings in the amount of data transfer).
> 
> Since there is extra computation cost for the compression, it will be even better to add a **minimum compression rate threshold** t as another algorithm hyperparameter, such that **(x + y) * rank < x * y * t**. The default value of t can be 0.5, so PowerSGD will only compress a tensor if there is at least 50% saving in bandwidth.
