### ISSUE TITLE
Rtx3080 RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by qq260612718** [pytorch/pytorch#52039]
My experimental environment is cuda11.0 RTX3080 pytorch1.7.1
When I try to install apex 0.1, the following problems occur:
**nvcc fatal: Unsupported gpu architecture ‘compute_86’**
I took this method of reducing the computing power, which showed that apex was successfully installed.
**export TORCH_CUDA_ARCH_LIST="7.5"**
But when I run the code, the following situation appears:

**RuntimeError: CUDA error: no kernel image is available for execution on the device.**
Can someone help me?I have tried cuda10.0 and 10.2 lower versions and still have some problems.

**Comment by VitalyFedyunin** [comment]
Please forward this question to https://github.com/NVIDIA/apex
