### ISSUE TITLE
cuda() call slow on Nvidia Quadro

### ISSUE THREAD

**Issue by CodeNinja98** [pytorch/pytorch#5205]
The call to model.cuda() takes several minutes to complete, after which everything works as expected. It seems similar to this issue: https://github.com/pytorch/pytorch/issues/537 I tried installing via both pip and conda, but both had the same issue. I'm guessing this is due to PyTorch not having built-in support for the Quadro?

OS: Linux
GPU: Nvidia Quadro P3000
Driver: Nvidia 390.25
Python 3.6
CUDA version 9.1
Torch 0.3.1 with CUDA 9

**Comment by soumith** [comment]
hmmm, this shouldn't be happening. Quadro P3000 has cuda capability 6.1, and we ship our binaries with all the bits for 6.1.

Did you install PyTorch via `conda` or `pip`?

**Comment by CodeNinja98** [comment]
I tried both, as mentioned above. Initially via conda using: 

conda install pytorch torchvision cuda90 -c pytorch 

and then I removed the package and tried reinstalling via:

pip3 install http://download.pytorch.org/whl/cu90/torch-0.3.1-cp36-cp36m-linux_x86_64.whl 
pip3 install torchvision

However neither fixed the problem. I see that the PyTorch site now lists a CUDA 9.1 version that wasn't available at the time of this issue. I'm going to try that as soon as I can and maybe that will resolve it.

**Comment by soumith** [comment]
okay thanks for the bug report. In the meanwhile I'll try find a cuda 6.1 capabile device and see why the binaries might be weird there.

**Comment by soumith** [comment]
@CodeNinja98 we looked into this and couldn't repro it on our end with a CUDA 6.1 capable GPU. One additional question: do you have any other GPUs on your machine? What is the output of the command `nvidia-smi`

**Comment by CodeNinja98** [comment]
Upgrading to PyTorch for CUDA 9.1 appears to solve things. Although I also noticed a problem in my code when initializing some of the GPU tensors that may have contributed to the slowdown either all or in part, so I'm really sorry if that was actually the main issue. Thanks for the excellent support!
