### ISSUE TITLE
Add torch.no_grad() to update_bn

### ISSUE THREAD

**Issue by MortenHannemose** [pytorch/pytorch#52055]
## 🚀 Feature
Add `torch.no_grad():` to `torch.optim.swa_utils.update_bn`.

## Motivation

When evaluating my model I get out of memory errors because `update_bn` allocates memory to do backprop through the SWA model. It took me a long time to figure out why adding `update_bn` gave me out of memory errors. 
The SWA model is mostly (only?) intended for evaluation, and not for training, so very few users will need to backprop on an SWA model. There is no reason for `update_bn` to allocate memory for a backpropagation that it never does.

## Pitch

Add `with torch.no_grad():` to [the line before](https://github.com/pytorch/pytorch/blob/e6779d4357ae94cc9f9fedb83a87eb6126016769/torch/optim/swa_utils.py#L161) `model(input)` in `torch.optim.swa_utils.update_bn` and indent `model(input)`

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @vincentqb

**Comment by ezyang** [comment]
cc @izmailovpavel @vadimkantorov in case either of you have opinions

**Comment by MiHarsh** [comment]
Hello Sir/Mam, 
I wanted to fix this issue. Can you please assign me ?

**Comment by izmailovpavel** [comment]
Hi guys @MortenHannemose @ezyang @MiHarsh , sorry for the delayed response! I totally agree with @MortenHannemose, the bn update should be under `torch.no_grad()`. I am happy to submit a PR with a fix (should be just a single line), but if someone else (@MiHarsh ) wants to do it, that sounds good to me as well.
