### ISSUE TITLE
linking error when using nightly pytorch prebuilt package

### ISSUE THREAD

**Issue by IgnacioJPickering** [pytorch/pytorch#52075]
## 🐛 Bug

I’m currently using the prebuilt binary version of pytorch nightly, which I installed with pip with cuda 11.0.

I have a custom model that I can normally run on my GPU (Quadro RTX 600) without any issues
(My cuda driver is 460.32.03)

My issue is that if I try to evaluate my model after jit-scripting it, I get a linker error:

```
    result = self.forward(*input, **kwargs)
../../../anaconda3/envs/myenv/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:132: in prof_meth_call
    return prof_callable(meth_call, *args, **kwargs)
../../../anaconda3/envs/myenv/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py:126: in prof_callable
    return callable(*args, **kwargs)
E   RuntimeError: Error in dlopen or dlsym: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
```

This is very strange to me, since **I believed that if I used the prebuilt binaries all necessary cuda libraries would be correctly linked with pytorch, and pytorch would not be using / needing my systems cuda. Am I mistaken about this? Is it possible that there is actually something wrong with my cuda installation / driver or is this some internal pytorch error?**

Furthermore, I actually do have cuda 11.2 installed in my system; also, this error doesn’t appear at all if I use pytorch 1.7.1.

This is frustrating since my custom model is very large, and I’m unable to pinpoint which part exactly is the one that is causing this, so I think it is very unlikely I would be able to post some minimal working example to reproduce the error.

## Expected behavior

Prebuilt pytorch binaries should not raise linking errors when using torchscript.

## Environment

```
PyTorch version: 1.8.0.dev20210208+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 6000
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-memlab==0.2.2
[pip3] torch==1.8.0.dev20210208+cu110
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cu110
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch-memlab            0.2.2                    pypi_0    pypi
[conda] torch                     1.8.0.dev20210208+cu110          pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2+cu110              pypi_0    pypi
```

Also, the output of nvcc --version is:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```

## Additional context

The linking error appears if I use the default fuser; if I run this using “fuser2” instead (the nvfuser I believe) then I get:

`E RuntimeError: false INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/codegen/cuda/type.cpp":439, please report a bug to PyTorch. No data type found for scalar type.
`

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @walterddr @ngimel

**Comment by malfet** [comment]
Thank you for reporting the issue. I can reproduce it locally, by removing libnvrtc.so.${MAJOR}.${MINOR} from my toolkit folder.

**Comment by IgnacioJPickering** [comment]
@malfet you are right, it seems that pytorch is looking for libnvrtc.so.11.2 in my system's cuda installation.

1) I gather from your answer that this behavior is not expected from the prebuilt pip/conda pytorch packages, is that correct?

2) I tried (a) symlink libnvrtc.so.11.0 to libnvrtc.so.11.2 and (b) installing cuda 11.0 and using that libnvrtc, since I wasn't sure if libnvrtc.11.2 should be backward compatible (grepping `objdmp -p` for the soname gave `libnvrtc.so.10.2`, so I suppose it is not).
 
In both instances my jitted model runs but the performance is **extremely** degraded (the jitted model runs ~x10 slower than the non-jitted model) 

on the other hand setting:
```
torch._C._jit_set_profiling_mode(False) 
torch._C._jit_set_texpr_fuser_enabled(False) 
```
seems to get rid of all these issues altogether.

**Comment by malfet** [comment]
@IgnacioJPickering to workaround the issue without perf penalty, can you please try renaming `libnvrtc-${shorthash}.so.11.0` to `libnvrtc.so.11.0` in folder reported by `python -c "import torch;from os.path import dirname;print(f'{dirname(torch.__file__)}/lib')`

**Comment by IgnacioJPickering** [comment]
@malfet This works but the extreme performance penalty is still there. I measured it more carefully and is actually close to ~x100 worse. The performance penalty is (in all cases) only present the first ~ 20 times I evaluate my model, if I evaluate my model in a loop the performance penalty dissapears after about 20 iterations.

For reference these are the timings for running forwards + backwards in a loop (in seconds):
```
~ 0.20 (first iteration)
~ 1.5 (second iteration)
~ 0.85 (for 19 iterations)
~ 0.0083 (for the remaining iterations)
```
This pattern is reproducible when evaluating the model on random inputs, when disabling texpr_fuster and setting profiling_mode = False the timings are ~ 0.0085 for all iterations, and results are similar when not using JIT (marginally slower, ~ 0.0089 s or so).

I'm not completely surprised that the first JIT iteration is slightly slower, I'm not sure how JIT works but I assume there may be some cacheing or other kind of analysis in the first pass, but the ~ 20 iterations at x100 speed worry me, I suppose this may be an unrelated bug?
