### ISSUE TITLE
discuss.pytorch.org is down

### ISSUE THREAD

**Issue by back2yes** [pytorch/pytorch#5209]
When I try to open the forum by the address "https://discuss.pytorch.org" as usual, it links to some site called "Discourse". The "Discourse" site seems to have nothing to do with pytorch, and seems to be empty. Is this something intended?

**Comment by soumith** [comment]
I am working on restoring the website back to it's original state. We ran into unexpected maintenance a 3 hours ago.

**Comment by apaszke** [comment]
It's back up now!

**Comment by prashnani** [comment]
it seems the [pytorch forum](https://discuss.pytorch.org/) is down again? 502 Bad Gateway error since yesterday. @apaszke @soumith

**Comment by g1910** [comment]
+1

**Comment by prashnani** [comment]
it's back up!! thanks.

**Comment by xu-song** [comment]
down again？

**Comment by soumith** [comment]
@xu-song no its working fine on my end

**Comment by zemelLeong** [comment]
down down down

**Comment by bosonbeard** [comment]
it'is not work.
![1](https://user-images.githubusercontent.com/5284540/69575091-a85a5180-0fda-11ea-9e7c-a4ec46201dd7.png)

**Comment by Xetd71** [comment]
![image](https://user-images.githubusercontent.com/31419846/81472958-1d75b800-9204-11ea-880c-67ba5db51192.png)

**Comment by cipri-tom** [comment]
@soumith down again :( `PR_CONNECT_RESET_ERROR`

**Comment by abedshantti** [comment]
This happens way too often. Not sure why.

**Comment by NikosSpanos** [comment]
It's still down!... Maybe they are fixing the Log4j leak?

**Comment by timlod** [comment]
Any news on this?

**Comment by jpainam** [comment]
the forum is down again. any update?

**Comment by adiv5** [comment]
down again

**Comment by JeffreyJosanne** [comment]
down again

**Comment by jpainam** [comment]
down again
