### ISSUE TITLE
separate python source and compiled extensions

### ISSUE THREAD

**Issue by graingert** [pytorch/pytorch#521]
It would make a pip wheel release on PyPI easier with a binary-only manylinux1 package for each CUDA version, eg `-cuda8` `-cuda7-5` and a source wheel with only the Python source code.

Similar to https://twistedmatrix.com/trac/ticket/7945

**Comment by apaszke** [comment]
Could you please tell me how does it make the release easier? <I hardly know anything about how PyPi packaging now, so I'm just curious>

**Comment by soumith** [comment]
see his changes in torchvision, in setup.py

**Comment by apaszke** [comment]
but vision has no compiled elements :confused:

**Comment by graingert** [comment]
Because you can't upload a cuda8 and cuda7.5 to the same package name. Also it means you wouldn't need a recompile and a large package download if only the python source changed

**Comment by soumith** [comment]
we've decided not to do this. The separation is too painful to do and maintain.
