### ISSUE TITLE
TensorPipe can't load CUDA driver because PyTorch adds stubs directory to RPATH

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#52137]
Some users (@pritamdamania87 and @tscmoo) reported issues like the following when using TensorPipe within PyTorch:
```
In create at .../tensorpipe/common/cuda_lib.h:105 "res != CUDA_SUCCESS"
```
This happens when TensorPipe attempts to `dlopen("libcuda.so")` (i.e., the CUDA driver, which we must load dynamically as we need to be able to run on machines that don't have it), because it ends up loading the stub instead of the real driver, where all functions are unimplemented and return an error. This occurs because PyTorch's build system causes the stubs' directory to be embedded in the RPATH.

This appears to be a long-standing known issue in PyTorch, already tracked in https://github.com/pytorch/pytorch/issues/35418. A fix was attempted in https://github.com/pytorch/pytorch/pull/37737 but it had to be reverted as it broke some developer setups.

If a fix to the core problem appears to be infeasible, we should explore alternative options. For example, would it work if we built TensorPipe as a standalone shared library, so that it had its own (unpolluted) RPATH?

cc @malfet @seemethere @walterddr @ngimel @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma @pietern @zhaojuanmao @satgera @aazzolini @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by malfet** [comment]
`stubs` folder should never be added to `rpath`. And it don't think separating TensorPipe to solve this problem is a good option, as core Torch library would be equal affected.

Although, what surprises me a bit about this, is that `dlopen("libcuda.so.1") should be a no-op after CUDA runtime was initialized. @pritamdamania87 can you share a bit more details about your setup?

**Comment by lw** [comment]
I don't know if (under normal operation) the CUDA runtime is already initialized at that point. Correct me if I'm wrong, but I think PyTorch only accesses (and initializes) the CUDA runtime when the first CUDA tensor is created. However, TensorPipe will attempt to load the CUDA driver as soon as it's initialized. Hence if one calls `init_rpc` before having created any CUDA tensor this situation might occur.

**Comment by lw** [comment]
Also note that the stubs directory only contains `libcuda.so`, not `libcuda.so.1`. Hence `dlopen("libcuda.so.1")` works (the real driver is found), whereas `dlopen("libcuda.so")` doesn't (it load the stub).

**Comment by lw** [comment]
The concrete issue here was fixed by loading `libcuda.so.1` instead of `libcuda.so`. Though I think the issue of PyTorch setting the RPATH to the stubs directory persists.
