### ISSUE TITLE
RPC hangs in callback when there is an error

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52132]
## 🐛 Bug

When an RPC future is completed with an error, `fut.wait()` should throw the error on the client so that the user can handle the exception.

Although, this doesn't appear to work correctly when `fut.wait()` on an RPC that has an error is called with an RPC callback. This can lead to a hang in the callback, which can cause, among other things, subsequent chained futures to not be completed. 

What is very strange is that there is a workaround: wrapping the call to `fut.wait()` in the cb with a try/catch. This is because I'm assuming that `fut.wait()` throws as expected and then we handle the exception. Although, the exception should be thrown even if we don't handle it as I understand.

## To Reproduce

Patch following test:
```
@dist_init
    def test_rpc_err_in_cb(self):
        if self.rank != 0:
            return
        # this will cause the RPC to be marked with an error due to timeout. 
        fut = rpc.rpc_async(worker_name(self.rank + 1), slow_add, args=(torch.tensor(1), torch.tensor(1)), timeout=0.01)
        # fut.wait()
        done = False
        def cb(fut):
            print(f"Fut result is {fut.wait()}")
            nonlocal done
            done = True

        fut.add_done_callback(cb)
        while not done:
            pass
```

## Expected behavior

Ideally `fut.wait()` should throw the error in cb and we should get a crash, as we do when we don't await in cb.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/python/pybind_utils.h#L185 is probably relevant

**Comment by SciPioneer** [comment]
I feel it will nice to for `rpc.rpc_async` to return both a future that holds the output, as well as the status code (SUCCESS/FAILURE, etc).

**Comment by rohan-varma** [comment]
@SciPioneer That's a good point, we currently don't support APIs such as `has_error()`/`get_error()` I wonder if we should consider supporting that. 

Although it's surprising to me that `fut.wait()` throws in main thread, but in callback thread seems to hang. @mrshenli do you have any idea why that may happen?

**Comment by rohan-varma** [comment]
After some more investigation, I think that I understand the fundamental issue here - 
1) then()/add_done_callback() run their callbacks in thread pool, not the main thread. Therefore if there is an exception it will be raised in the thread pool, but those are swallowed/logged, it does not terminate the program, i.e. this log: 

```
E0303 13:22:49.556552 273181 thread_pool.cpp:112] Exception in thread pool task:  Got the following error w
hen running the callback: RuntimeError: RPCErr:1:RPC ran for more than set timeout (10 ms) and will now be
marked with an error
``` 
2) With then(), this is actually fine since if we throw error in the callback, then the future corresponding to the result of then() is completed with that error, and the user can handle the error via that future. 
3) This doesn't work for add_done_callback (or if the future for then()) is not waiting, since if the user is waiting for another condition in the callback to be satisfied or another future (not created with then) to be satisfied, due to the exception that may never happen and result in a hang. 

Based on the above, I don't think the following paradigm is very safe and the user needs to be aware of handling the error in this case:


```
ret_fut = torch.futures.Future()
def rpc_done_cb(rpc_fut):
    result = rpc_fut.wait() # throws error
    ret_fut.set_result(result) # will never be called

rpc_fut = rpc.rpc_async(...)
rpc_fut.add_done_callback(rpc_done_cb)
ret_fut.wait()
```

given this and the fact that _add_done_cb is private, the best thing to do here is probalby just update the docs for then() mentioning this edge case.

**Comment by rohan-varma** [comment]
Close because https://github.com/pytorch/pytorch/pull/54476 enhancing the logging was landed.
