### ISSUE TITLE
PyTorch installation issue

### ISSUE THREAD

**Issue by uray10** [pytorch/pytorch#5214]
I am installing PyTorch from source. Python version: 2.7.14. CUDA: 8.0. GPU: gtx1080. GCC: 5.4. Processor: AMD Opteron(tm) Processor 6128

While executing "python setup.py install" build completes till 87% but after that I get the following errors
```
In file included from generic/THTensor.cpp:1:0,
                 from /home/uray/anaconda2/pytorch/aten/src/TH/THGenerateFloatTypes.h:10,
                 from /home/uray/anaconda2/pytorch/aten/src/TH/THGenerateAllTypes.h:10,
                 from /home/uray/anaconda2/pytorch/aten/src/TH/THTensor.cpp:13:
/home/uray/anaconda2/pytorch/aten/src/TH/generic/THTensor.cpp: In function 'THDescBuff THFloatTensor_desc(const THFloatTensor*)':
/home/uray/anaconda2/pytorch/aten/src/TH/generic/THTensor.cpp:973:35: error: expected ')' before 'PRId64'
     n += snprintf(str+n, L-n, "%" PRId64, tensor->size[i]);
                                   ^
/home/uray/anaconda2/pytorch/aten/src/TH/generic/THTensor.cpp:973:58: warning: spurious trailing '%' in format [-Wformat=]
     n += snprintf(str+n, L-n, "%" PRId64, tensor->size[i]);
```
And many more messages of the same type regarding errors with 'PRId64'
I looked at similar issues online and most of the people facing this issue had an old version of gcc, so I'm a bit confused about what my exact problem is. 

Also, when I'm installing via conda, the installation completes, but when I run the following bit of code, I get an illegal instruction at the print command
```
from __future__ import print_function
import torch
x = torch.Tensor(5, 3)
print(x)
```
That I guess is because of the fact I'm using an AMD processor? 
Any help will be appreciated.
Thanks

**Comment by lanpa** [comment]
looks like the same issue as #5038
