### ISSUE TITLE
tensor operations return incorrect data with libtorch v1.7.1-rc3 on ARM64 on QNX

### ISSUE THREAD

**Issue by asobhy-qnx** [pytorch/pytorch#52159]
## 🐛 Bug

Running this code snippet:
`

    int n = 104*64;

    std::vector<float> floatValues(n,144.745981);

    auto floorDataInput = torch::tensor(floatValues).view({1,104,64,1});

    auto floorOutput = floorDataInput.floor();

    std::cout << floorOutput[0][0][0][0].item<float>() << std::endl;

`
on ARM64 prints out 0 instead of 144, while running it on x86_64 returns the correct answer. It seems due to the implementation of tensor operations. For aarch64 Sleef library is being used and sve is disabled which makes me believe this is the reason behind the failure.

## To Reproduce

the libraries have been built from source using cmake with the following cmake args:

                         -DBUILD_TEST=OFF \
                         -DBUILD_TESTING=OFF \
                         -DBUILD_PYTHON=OFF \
                         -DBUILD_SHARED_LIBS=ON \
                         -DHAVE_SOVERSION=ON \
                         -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                         -DPYTORCH_QNNPACK_LIBRARY_TYPE=static \
                         -DCAFFE2_CUSTOM_PROTOC_EXECUTABLE=$(PROJECT_ROOT)/external/protobuf/install/bin/protoc \
                         -DNATIVE_BUILD_DIR=$(PROJECT_ROOT)/external/host/sleef \
                         -DUSE_CUDA=OFF \
                         -DUSE_OPENCV=OFF \
                         -DUSE_NUMPY=OFF \
                         -DUSE_NUMA=OFF \
                         -DUSE_VULKAN_WRAPPER=OFF \
                         -DUSE_DISTRIBUTED=OFF \

An implementation for qnx was added to cpuinfo to enable cpuinfo from returning proper cpu info.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by asobhy-qnx** [comment]
I have traced through the code to see the sequence of calls and this is what I found, please correct me if I am wrong:

Tensor::floor() --> findSchemaOrThrow("aten::floor","") --> findSchema({"aten::floor",""}); --> findOp({"aten::floor",""}); -->   

Vec256<float> floor() const {
    return map(at::native::floor_impl);
  }

-->

template <typename TYPE>
inline TYPE floor_impl (TYPE z) {
  //std::cout << "calling std::floor()" << std::endl;
  return std::floor(z);
}

Then I have noticed that if I uncomment the std::cout statement I get the correct return otherwise I get garbage

**Comment by asobhy-qnx** [comment]
Reading the header pytorch/aten/src/ATen/cpu/vec256/vec256_float_neon.h mentions using STL only and that Sleef is not being used for aarch64. This brings up the question, why does the build, builds sleef for aarch64 if it is not being used?

**Comment by asobhy-qnx** [comment]
This issue is the result of a compiler optimization

**Comment by malfet** [comment]
@ptrblck FYI. 
Most likely this was fixed by https://github.com/pytorch/pytorch/pull/50389
