### ISSUE TITLE
There should be a way to train the slope of leaky relu.

### ISSUE THREAD

**Issue by Emmanuel357** [pytorch/pytorch#52154]
## 🚀 Feature
We should be able to pass in an nn.Parameter object to nn.LeakyReLU as the slope so that it can be updated.

## Motivation
Training the slope of LeakyReLU will help  a neural network model to train better.

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment]
Hi,

Thanks for sending that feature request.

> Training the slope of LeakyReLU will help a neural network model to train better.

Would you have any link to papers/experiments that support this?

**Comment by xonobo** [comment]
Why don't you try [PReLU](https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html#prelu), @Emmanuel357?

**Comment by jbschlosser** [comment]
Closing for now; feel free to reopen with more details if PReLU doesn't work for you.
