### ISSUE TITLE
Why do we have `torch.is_floating_point` and `torch.is_complex` but not `torch.is_integer`?

### ISSUE THREAD

**Issue by dtoniolo** [pytorch/pytorch#52161]
## 🚀 Feature
`torch` should provide an `is_integer()` function to check whether a tensor's `dtype` belongs to the integer family. Additionally, there should be an option to further limit the input's `dtype` to signed (`int*`) or unsigned (`uint*`) types. The default would be to allow both cases.

## Motivation
PyTorch currently provides `torch.is_floating_point()` and `torch.is_complex()` to check whether a tensor contains data of a certain numeric types. An analogue feature for the the integer family and data types would be useful for the same reasons that make the other two worth having in the library.

It also would increase the logical consistency of the library, as there would be a function for each dtypes family. Finally, it would be really easy to implement, here's a stub:

```{python}
def is_integer(tensor: torch.Tensor, type: str = 'any') -> bool:
    """Checks if a Torch Tensor has a dtype representing an integer.

    Supports additional condiions on the sign, optionally forcing `tesnor` to
    be unsinged or singed.

    Parameters
    ----------
    tensor : torch.Tensor
        The tensor to check.
    type : str
        One of 'u', 's', or 'any'. If 'any', the tensor's dtype can be either
        unsigned or signed. If 'u' or 's' it will be forced to be unsigned or
        signed, respectively.

    Returns
    -------
    bool
        True if the input tensor satisfies the requested condition, False
        otherwise.

    Raises
    ------
    ValueError
        - If `tensor` isn't a torch.Tensor instance.
        - If `type` isn't one of 'u', 's' or 'any'.

    """
    valid_type_str = ['u', 's', 'any']
    if type not in valid_type_str:
        raise ValueError('Invalid input. The `type` argument should be one ' +
                         'of {}, but is {} '.format(valid_type_str, type) +
                         'instead.')
    if not isinstance(tensor, torch.Tensor):
        raise ValueError('Invalid input. The input should be a Torch ' +
                         'Tensor, but is {} instead.'.format(type(tensor)))
    uint_types = [torch.uint8]
    sint_types = [torch.int8, torch.int16, torch.int32, torch.int64]
    if type == 'u':
        return tensor.dtype in uint_types
    elif type == 's':
        return tensor.dtype in sint_types
    else:
        return tensor.dtype in uint_types + sint_types
```

## Alternatives
The only alternative would be continuing with not providing this function. This choice seems suboptimal, for the reasons discussed above.

## Actual Implementation
The above code is a stub. If this proposal is met favourably, the actual implementation would need to answer the following issues:
- where should it be implemented? Would it be in C/C++ code or in Python code?
- actual naming of the input args and formatting of the documentation

Edit: fixed error in code due to rushed copy-pasting.
2nd edit: forgot `torch.int64`.
3rd edit: spelling

cc @mruberry @rgommers @heitorschueroff

**Comment by albanD** [comment]
Triage review to know if there is any module we can set on this?

**Comment by rgommers** [comment]
`module: numpy` sounds about right, unfortunately numpy doesn't have a great API for this, see https://github.com/numpy/numpy/issues/17325. I was planning to work on that soon - it'd be great if we could end up with the same API in numpy and pytorch.

Related: there's an `is_signed` method on both `Tensor` and on dtypes:
```
>>> t = torch.tensor([1, 2], dtype=torch.uint8)                             
>>> t.is_signed()                                                           
False
>>> t.dtype.is_signed                                                       
False
>>> t.dtype.is_floating_point                                               
False
>>> t.dtype.is_complex                                                      
False
>>> t = torch.tensor([1, 2], dtype=torch.float32)                           
>>> t.is_signed()                                                           
True
>>> t = torch.tensor([1, 2], dtype=torch.bool)                              
>>> t.is_signed()                                                           
False
```
It's kind of weird though, since `is_signed()` can mean it's boolean if False, while it can mean floating point or complex if it's true. Without `is_integer` there isn't much you can use that for.

**Comment by mruberry** [comment]
What's the array-api doing on this topic, @rgommers?

From a PyTorch perspective, yes it's odd that we have torch.is_floating_point() and torch.is_complex() but not torch.is_integer(). I think we would accept a PR adding it. It's also straightforward to implement in Python as a workaround.

**Comment by rgommers** [comment]
> What's the array-api doing on this topic, @rgommers?

We identified the problem, but didn't propose a solution yet. We focused mainly on standardizing functionality that's present in all or most libraries with similar API. And that's not the case for dtypes. Some libraries don't even have their own dtypes, for example MXNet uses numpy's dtypes in array constructors.

I'd be fine with proposing `is_floating_point`, `is_complex` and `is_integer` for standardization and see what people think. 

Maybe `is_integer()` should have a `signed=None` keyword? Otherwise having to do two calls to determine if something is signed/unsigned int is a bit odd.

**Comment by mruberry** [comment]
I could see kwargs controlling whether signed, unsigned, or both types of dtypes are desired and whether booleans should be included or not, too. Maybe that additional complexity is why it hasn't been added, or maybe these functions are mostly of use during testing.

I wonder if this is the right time to introduce more appropriate torch.testing functions? I've always wanted to rename these functions more appropriately (has_floating_point_dtype, has_complex_dtype, has_integer_dtype...). The name is_integer, in particular, seems a little odd, because it suggests that when it returns True the object being tested is, in fact, an integer.

**Comment by rgommers** [comment]
A search for `np.issubdtype` in SciPy suggests less than half of the usage is testing related. Function input validation (to raise an exception or cast to a more appropriate dtype) and branching in algorithms are common use cases.

**Comment by albanD** [comment]
Note that in that same spirit, I am not sure why `complex=None` is not a keyword argument to `is_floating_point` and `is_integer` as well?
It feels quite orthogonal from the two other dtype checking functions.
Not sure if complex boolean would be ever a thing though 🤔

**Comment by dtoniolo** [comment]
> Maybe `is_integer()` should have a `signed=None` keyword? Otherwise having to do two calls to determine if something is signed/unsigned int is a bit odd.

If I am allowed, if `is_integer()` is to be included in the codebase this seems the most reasonable choice. My code example has it, abeit under a different name.

> `module: numpy` sounds about right, unfortunately numpy doesn't have a great API for this, see [numpy/numpy#17325](https://github.com/numpy/numpy/issues/17325). I was planning to work on that soon - it'd be great if we could end up with the same API in numpy and pytorch.

I'd like to clarify that what I'm proposing is a check on dtypes, not on the contents of the arrays. The NumPy issue mentioned here brights up an additional problem: determining if the contents of an array belong to a given number set (N, Z, R or C) regardless of the `dtype`.

**Comment by rgommers** [comment]
> I'd like to clarify that what I'm proposing is a check on dtypes, not on the contents of the arrays. The NumPy issue mentioned here also discusses the problem of determining if the contents of an array belong to a given number set (N, Z, R or C) regardless of the `dtype`.

There's no real difference between the two, because a single tensor/array has a single dtype. So accepting (in numpy's case) both dtypes and arrays as input to some of those functions is really a convenience only - if you pass an array `x` then `x.dtype` can be used for the check.

**Comment by dtoniolo** [comment]
> The NumPy issue mentioned here also discusses the problem of determining if the contents of an array belong to a given number set (N, Z, R or C) regardless of the `dtype`.

Sorry, I'll try to clarify that with an example. Let `t = torch.tensor([1., 2., 3.], dtype=torch.float32)`. This array has a floating point data type, but the values are really natural numbers. So they discuss a function (e.g. `has_integer_values()`) which would if each element is an integer or not, e.g.:
```{python}
torch.has_integer_values(t) = [True, True, True]
torch.has_integer_values(torch.tensor([1., 2., 3., 0.5], dtype=torch.float32)) = [True, True, True, False]
```

The problem is that the naming of the functions must be chosen carefully in order to make it clear whether it is the dtype or the content that will be validated. Hope I have made my case more articulated.

**Comment by rgommers** [comment]
Thanks @dtoniolo, that makes sense. I'm not a fan of those "check each value" functions, they're not used a lot and if they it's often buggy code (floating point roundoff errors can affect the end result easily). So I'd avoid adding any of that.

**Comment by dtoniolo** [comment]
@rgommers I had forgot about this issue, but I've been using the function that I've proposed in various places and I though I should revive this issue. I'll add some clarifications on what I meant and on what I'm using this function for.

# Clarification
First of all, I perfectly agree with you: "check each value" functions are not very useful and can lead to buggy (and logically incorrect) code if floating point roundoff errors are not considered. In fact, what I was and am advocating for is a check on the dtype. I had mentioned `has_integer_values()` just to bring to your attention the fact that we should be careful with the naming of the function, because the name I had originally proposed (`is_integer()`, my bad) could lead some users to think that `is_integer()` is a "check each value" function instead of a "check the dtype" one.

# Usage
In many occasions the code I write operates under the assumption that a tensor has an integer dtype. Although I check my code with MyPy, Python's type hints cannot represent a `torch.Tensor` of a generic integer dtype, so I use the function that I had proposed at the beginning of this discussion to test this assumption at runtime. This allows me to be more confident about the correctness of my code.

The check adds some overhead, so I'm trading some performance for a greater degree of confidence on the correctness of the software. Whether this tradeoff is worth it is, I think, a decision that each programmer or team should make based on their situation¹. It would, however, be nice to be able to perform it by using a standard function from the PyTorch API

¹A kind of middle ground which I often adopt is to wrap the check with an `if __debug__:` or an `assert`.

# Revised Implementation
```python
def has_integer_dtype(tensor: torch.Tensor, signed: bool | None = None) -> bool:
    """Determines if a PyTorch tensor has an integer dtype.

    It also can force `tensor` to be singed or unsinged.

    Parameters
    ----------
    tensor
        The tensor to check.
    signed
        Determines which dtypes are allowed for `tensor`:

        - If ``None`` both unsinged and signed integer will be allowed.

        - If ``False`` only unsigned dtypes will be allowed.

        - If ``True`` only signed dtypes will be allowed.

    Returns
    -------
    bool
        ``True`` if the input tensor satisfies the requested condition, ``False``
        otherwise.

    """
    uint_types = [torch.uint8]
    sint_types = [torch.int8, torch.int16, torch.int32, torch.int64]
    if signed is None:
        return tensor.dtype in uint_types + sint_types
    elif signed:
        return tensor.dtype in sint_types
    else:
        return tensor.dtype in uint_types
```

**Comment by rgommers** [comment]
@dtoniolo thanks for revisting this issue. This problem is now addressed in a more general fashion in the array API standard with an [isdtype](https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html) function. I believe that that should address your use case as well - could you verify that?

**Comment by dtoniolo** [comment]
Thanks for the hint, I didn't know about that part of the array API. It definitely does the job and I would say it's even better, because it's standardized. Has it already been implemented in PyTorch?

**Comment by rgommers** [comment]
`isdtype` not yet (most functions in the standard match PyTorch though), but there's a mature compatibility layer that supports PyTorch which you can use: https://github.com/data-apis/array-api-compat. It is being vendored by both scikit-learn and SciPy, so should be relatively mature by now.

**Comment by dtoniolo** [comment]
Understood, thanks a lot!
