### ISSUE TITLE
Compiler error: expected ‘)’ before ‘PRId64’

### ISSUE THREAD

**Issue by coosh-ed** [pytorch/pytorch#5217]
I'm trying to install PyTorch from source (for MPI use) but I keep getting the following error when I try to run  ` $python setup.py install`
but I get the following error. I am using g++ 5.3.0 and Linux.

```bash
PyTorch GitHub In file included from generic/THCTensor.c:1:0,
                 from /work/home/staff/username/dev/pytorch/aten/src/THC/THCGenerateAllTypes.h:23,
                 from /work/home/staff/username/dev/pytorch/aten/src/THC/THCTensor.cpp:7:
/work/home/staff/username/dev/pytorch/aten/src/THC/generic/THCTensor.c: In function ‘THCDescBuff THCudaTensor_sizeDesc(THCState*, const THCudaTensor*)’:
/work/home/staff/username/dev/pytorch/aten/src/THC/generic/THCTensor.c:1020:35: error: expected ‘)’ before ‘PRId64’
     n += snprintf(str+n, L-n, "%" PRId64, tensor->size[i]);
```

Issue [3571](https://github.com/pytorch/pytorch/issues/3571) seems similar but affected a different directory.
Thanks in advance

**Comment by soumith** [comment]
I merged a patch via https://github.com/pytorch/pytorch/pull/5228 that should fix this 2 hours ago. Please pull latest master and check if this is still an issue.

**Comment by coosh-ed** [comment]
I pulled the most recent from the repo, but now `$ CC=gcc CXX=g++ python setup.py install` doesn't seem to accept the specified compilers and uses my system's default (which is too old). Is this a problem my end or yours?

Thanks for your help so far.

**Comment by uray10** [comment]
I had originally listed my problem in #5214 

The PRId64 problem has gone. However I am getting a new error,
`CMake Error at /home/uray/anaconda2/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ibverbs (missing: IBVERBS_INCLUDE_DIRS IBVERBS_LIBRARIES)`

I am unable to find any issue related to this. Any help will be appreciated. Thanks

**Comment by ezyang** [comment]
That indicates that the build is trying to build with Infiniband support, for some reason. You should be able to turn off the distributed build by setting `NO_DISTRIBUTED=1` in your env.

If you want to help us debug, can you tell us if running `ibv_devinfo` outputs anything? And also check that you don't have `WITH_GLOO_IBVERBS` in your environment.

**Comment by uray10** [comment]
That worked. Thank you so much. I set `NO_DISTRIBUTED` to `1`. But does that mean I won't be able to use distributed support for PyTorch?

`ibv_devinfo` outputs:

`hca_id:	mlx4_0`
	`transport:			InfiniBand (0)`
	`fw_ver:				2.7.626`
	`node_guid:			0002:c903:000c:26ee`
	`sys_image_guid:			0002:c903:000c:26f1`
	`vendor_id:			0x02c9`
	`vendor_part_id:			26428`
	`hw_ver:				0xB0`
	`board_id:			MT_0D90110009`
	`phys_port_cnt:			1`
		`port:	1`
			`state:			PORT_ACTIVE (4)`
			`max_mtu:		4096 (5)`
			`active_mtu:		4096 (5)`
			`sm_lid:			4`
			`port_lid:		48`
			`port_lmc:		0x00`
			`link_layer:		InfiniBand`

**Comment by ezyang** [comment]
@coosh-ed What distro (and what version) are you using?

@uray10 Yes, that means you won't be able to use distributed. It sounds like the test we do for ibverbs availability is not sufficient. Do you have the ability to install ibverbs in some way? For example, on Ubuntu, the package is named `libibverbs`

**Comment by ngimel** [comment]
Closing, please reopen if needed
