### ISSUE TITLE
Unreachable Code in /tools/codegen/api/python.py

### ISSUE THREAD

**Issue by AlexShypula** [pytorch/pytorch#52189]
## 🐛 Bug

I've found an unreachable portion of code in the following file and line. 

https://github.com/pytorch/pytorch/blob/master/tools/codegen/api/python.py#L823-L824

## Additional context

The last line of code at 824 is unreachable as the variable **ret** should be returned regardless. It seems if the input parameter **t** is not an instance of either **BaseType** or **ListType** it seems **ret** may throw a NameError for ret as it should not be defined, instead of raising the RuntimeError.

**Comment by albanD** [comment]
Thanks for the report!
If you want to send a PR fixing this, we can merge it!

**Comment by AlexShypula** [comment]
Got it ! Thanks will look into it.

**Comment by AlexShypula** [comment]
Okay it looks like I should have submitted a PR right here: https://github.com/pytorch/pytorch/pull/52228
