### ISSUE TITLE
Support for Tensordot operation in ONNX conversion

### ISSUE THREAD

**Issue by JHancox** [pytorch/pytorch#52204]
## 🐛 Bug

Whilst attempting to export a model to ONNX, I get an error encouraging me to raise this bug report
`RuntimeError: Exporting the operator tensordot to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.`

## To Reproduce

Include the Tensordot operation in your pyTorch model:
1. `x = torch.tensordot(x, y, dims=1) `

Apply the model converter:
2. ```
dummy_input = torch.randn(32, 3, 224, 224)
    net = torch.onnx.export(net, dummy_input, "output_net.onnx", verbose=False)

Traceback (most recent call last):
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/utils.py", line 787, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/utils.py", line 745, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/jonny/miniconda3/envs/hovernet_pyt/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator tensordot to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.
'''
## Expected behavior
The model should be exported with all operations intact

## Environment
'
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 460.27.04
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] numpy                     1.19.1                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by spandantiwari** [comment]
@JHancox - could you mention which model requires this?

**Comment by tsindhuja** [comment]
@spandantiwari I am facing the same issue while converting a vision transformer model - R50+ViT-B_16
https://github.com/tczhangzhi/VisionTransformer-Pytorch - This is the repo

**Comment by spandantiwari** [comment]
@JHancox @tsindhuja - we have added support for tensordot in ONNX exporter. It is available for `opset_version=12` or higher. 
https://github.com/pytorch/pytorch/blob/42d073a7e9b338ee3d9224d525ca0383b6272af9/torch/onnx/symbolic_opset12.py#L216
