### ISSUE TITLE
[JIT] Add named tuples (a.k.a. records) to the JIT IR

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5220]
**Motivation.** Today, in the JIT, our data model is that only all operators take a flat list of variables and produce a flat list of variables. This is a very uniform model which makes it easy to do code generation, but it makes our internal operations more difficult to understand, because we have to decode a flat list of variables into their semantic meaning when we want to perform optimizations that know about the semantics of operations.

**Proposal.** Here is the design principle for adding named tuples to the JIT IR: data structures should be desugarable into our existing flat model at compile time without requiring any runtime code. This means statically sized data structures like named tuples are permissible, while dynamically sized structures like vectors and recursive tuples are not. The type of a data structure unambiguously determines the number of elements in the corresponding flat list.

Thus, our IR representation will be stratified into two languages: a higher-level language with data structures, and a lower-level one that operates on flat lists (same as before.)

Concretely, we extend types:

```
// The type of named tuples
struct TupleType : public Type {
  TupleType(at::ArrayRef<Symbol> labels, at::ArrayRef<Type> types);
  // The number of Tensor entries when this type is flattened.
  size_t flatSize();
}
```

I will notate a named tuple as `(l1: t1, ..., ln: tn)`, where `l` ranges over the symbol labels, and `t` ranges over types. Order matters.  We define the following operators:

* `%t = Tuple[labels :: strings] %0, ... %n`: takes n labels as attributes, and n inputs of types t0 ... tn , and constructs a tuple of type `(l0: t0, ..., ln: tn)`. If labels are omitted, this is equivalent to having specified `["0", "1", ... "n"]` as the labels.
* `%0, ... %n = Untuple %t`: takes a tuple of type `Tuple<l1: t1, ... , ln: tn>` and produces n outputs of types t1 ... tn.
* `%r = Proj[label :: string] %t`: takes a tuple of type `Tuple<n1: t1, ... nn : tn>` and a string label `i`, and produces an output of type `ti`.

@zdevito @apaszke @jamesr66a @bddppq

**Comment by apaszke** [comment]
Plan looks ok, but what is the exact planned purpose? Is this meant to resolve our flat-phi-list problems?

**Comment by ezyang** [comment]
Yes, it also is intended to make working with some operators less error prone, since you no longer have to manually decode the meaning of inputs we feed in.

**Comment by apaszke** [comment]
well that would be solved in a much more readable way if we had annotations for inputs of our nodes (not even represented in the IR, just as a thing that the pretty-printer can read). I'm curious how would you imagine solving the loop problem if we can't have nested tuples. I'd imagine it would be something like `(trip_count=%1, cond=%2, carry1=%3, carry2=%4)`. Is that right?

**Comment by ezyang** [comment]
You can have nested tuples, just not recursive tuples.

**Comment by apaszke** [comment]
Sorry, what do you mean by recursive tuples then?

**Comment by ezyang** [comment]
```
-- Nested tuple
type X = (Tensor, Tensor, (Tensor, Tensor))

-- Recursive tuple
type X = (Tensor, Maybe X)
```

**Comment by ezyang** [comment]
I think this has been WONTFIXed.

**Comment by zdevito** [comment]
@suo is adding user-defined data types (i.e. named records with associated methods). We should plan to make named records be a part of that.
