### ISSUE TITLE
rorch.fliplr and torch.flip have bugs with 3-D tensor (CxHxW)

### ISSUE THREAD

**Issue by lambert-x** [pytorch/pytorch#52201]
## To Reproduce

1.  use the functions with a 3-D tensor or RGB image

## Expected behavior

I expect the functions to be equivalent with input[:,::-1] and input[...,::-1,:]. 
## Environment

Clang version: Could not collect
CMake version: version 2.8.12.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 418.87.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.1.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.18.5           py38ha1c710e_0
[conda] numpy-base                1.18.5           py38hde5b4d6_0
[conda] pytorch                   1.7.1           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu101    pytorch

**Comment by albanD** [comment]
Hi,

Could you provide a code sample that shows the problem please?
The code example in the doc works fine for me and it is on a 3D tensor: https://pytorch.org/docs/stable/generated/torch.flip.html?highlight=flip#torch.flip

**Comment by lambert-x** [comment]
![image](https://user-images.githubusercontent.com/44768908/107811544-55360100-6d3c-11eb-9bcd-b03c47143145.png)

**Comment by lambert-x** [comment]
> Hi,
> 
> Could you provide a code sample that shows the problem please?
> The code example in the doc works fine for me and it is on a 3D tensor: https://pytorch.org/docs/stable/generated/torch.flip.html?highlight=flip#torch.flip

The sample is attached. I 

> Hi,
> 
> Could you provide a code sample that shows the problem please?
> The code example in the doc works fine for me and it is on a 3D tensor: https://pytorch.org/docs/stable/generated/torch.flip.html?highlight=flip#torch.flip

The code sample is attached.
