### ISSUE TITLE
logcumsumexp returns the wrong result in GPU

### ISSUE THREAD

**Issue by guillempalou** [pytorch/pytorch#52213]
## 🐛 Bug

torch.logcumsumexp gives the wrong result when these conditions happen:
- Input is a multidimensional tensor (>1)
- Input has two or more -inf in a row

## To Reproduce

```
inf = float("inf")
x = torch.tensor([
    [2., -inf, -inf, 1, -inf, -inf, 3],
    [2., 1, -inf, 1, -inf, -inf, 3]
])

assert torch.allclose(
    torch.logcumsumexp(x, dim=-1),
    torch.logcumsumexp(x.cuda(), dim=-1).cpu()
)

```
The code above raises an exception

## Expected behavior

The two tensors should be the same. When computations happen in the CPU, results are correct. GPU errors appear in positions where the original tensor contained `-inf`

## Environment

PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 9.13 (stretch) (x86_64)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Clang version: Could not collect
CMake version: version 3.15.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB

Nvidia driver version: 418.74
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.12.1
[conda] Could not collect

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by ngimel** [comment]
High priority for silent wrong results

**Comment by ngimel** [comment]
cc @kshitij12345

**Comment by ngimel** [comment]
Reduction op for logcumsumexp is defined as 
```
    auto log_add_exp = [] C10_HOST_DEVICE (const scalar_t x, const scalar_t y) -> scalar_t {
      return ::log1p(std::exp(std::min(x, y) - std::max(x, y))) +
          std::max(x, y);
    };
```
It does not work too good when there are 2 consecutive -infs. CPU can also produce wrong results if tensor starts from [-inf, -inf].

**Comment by kshitij12345** [comment]
There are 3-paths in CUDA code.

https://github.com/pytorch/pytorch/blob/71d0b5632bfa29f1b6828050edc6512402e253a7/aten/src/ATen/native/cuda/ScanKernels.cu#L524-L541

Trying to check all three paths.

```python
import torch
inf = float("inf")

x = torch.tensor([[-inf, 1]])

def logcumsumexp_helper(x, dim):
    y_cpu = torch.logcumsumexp(x, dim=dim)
    y_cuda = torch.logcumsumexp(x.cuda(), dim=dim)

    print("CPU:")
    print(y_cpu)
    print("CUDA:")
    print(y_cuda)
    print("DIFF:")
    print(y_cpu - y_cuda.cpu())

print("CUB Path")
logcumsumexp_helper(x, dim=1)
print("\n\n")

print("Innermost path")
x = torch.tensor([
    [2., -inf, -inf, 1, 3],
    [2., 1,    -inf, 1, 3]
])
logcumsumexp_helper(x, dim=-1)
print("\n\n")

print("Outermost path")

logcumsumexp_helper(x, dim=0)
print("\n\n")
```

Output:
```
CUB Path
CPU:
tensor([[   nan, 1.6931]])
CUDA:
tensor([[-inf, 1.]], device='cuda:0')
DIFF:
tensor([[   nan, 0.6931]])



Innermost path
CPU:
tensor([[2.0000, 2.0000, 2.0000, 2.3133, 3.4076],
        [2.0000, 2.3133, 2.3133, 2.5514, 3.4938]])
CUDA:
tensor([[2.0000, 2.0000, 2.0000, 2.3133, 3.4076],
        [2.0000, 2.3133, 2.3133, 2.5514, 3.4938]], device='cuda:0')
DIFF:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])



Outermost path
CPU:
tensor([[2.0000,    nan,    nan, 1.0000, 3.0000],
        [2.6931, 1.6931,    nan, 1.6931, 3.6931]])
CUDA:
tensor([[2.0000,    nan,    nan, 1.0000, 3.0000],
        [2.6931,    nan,    nan, 1.6931, 3.6931]], device='cuda:0')
DIFF:
tensor([[0., nan, nan, 0., 0.],
        [0., nan, nan, 0., 0.]])

```

Interesting thing on CPU (on CUB path), it seems to recover from a NAN

```
CUB
CPU:
tensor([[   nan, 1.6931]])
```

On digging a bit further with godbolt.org,
Reference: https://godbolt.org/z/qGa1oP
```C++
#include <iostream>
#include <cmath>

int main(void) {

    auto log_add_exp = [](float x, float y) -> float {
            return std::log1p(std::exp(std::min(x, y) - std::max(x, y))) + std::max(x, y);
          };
    std::cout << log_add_exp(1, NAN) << "\n";
    std::cout << log_add_exp(NAN, 1) << "\n\n";

    std::cout << std::min((float)1., (float)NAN) << "\n";
    std::cout << std::min((float)NAN, (float)1.) << "\n\n";

    std::cout << std::fmin((float)1., (float)NAN) << "\n";
    std::cout << std::fmin((float)NAN, (float)1.) << "\n\n";

  return 0;
}

```

Output:
```
1.69315
nan

1
nan

1
1
```

So turn's out std::min is not the correct way if you have `NAN` as possibility as it results changes depending on how you call it
https://stackoverflow.com/a/30915238/5602957

On CPU side we call `op(x, acc)` while on CUDA we call `op(acc, x)`.

There is `fmin` which as per standard docs,
Returns the smaller of two floating point arguments, treating NaNs as missing data (between a NaN and a numeric value, the numeric value is chosen).

Updating both CPU and CUDA code to use fmin and fmax, and running the above Python script, output we get is consistent for innermost and outermost (not for CUB, didn't dig into it)

```
CUB Path
CPU:
tensor([[   nan, 1.6931]])
CUDA:
tensor([[-inf, 1.]], device='cuda:0')
DIFF:
tensor([[   nan, 0.6931]])



Innermost path
CPU:
tensor([[2.0000, 2.0000, 2.0000, 2.3133, 3.4076],
        [2.0000, 2.3133, 2.3133, 2.5514, 3.4938]])
CUDA:
tensor([[2.0000, 2.0000, 2.0000, 2.3133, 3.4076],
        [2.0000, 2.3133, 2.3133, 2.5514, 3.4938]], device='cuda:0')
DIFF:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])



Outermost path
CPU:
tensor([[2.0000,    nan,    nan, 1.0000, 3.0000],
        [2.6931, 1.6931,    nan, 1.6931, 3.6931]])
CUDA:
tensor([[2.0000,    nan,    nan, 1.0000, 3.0000],
        [2.6931, 1.6931,    nan, 1.6931, 3.6931]], device='cuda:0')
DIFF:
tensor([[0., nan, nan, 0., 0.],
        [0., 0., nan, 0., 0.]])
```

@ngimel Should we update this?

**Comment by v0dro** [comment]
I will take up this issue.
