### ISSUE TITLE
ProcessGroupNCCL::all_reduce is not profiled correctly

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52246]
## 🐛 Bug

Due to the async nature of nccl's allreduce, the recordFunction callbacks attached to the nccl allreduce aren't profiled correctly. See the end code pointer here: https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/ProcessGroupNCCL.cpp#L1064. This is as is because it previously used `cudaFuture->addCallback` to trigger the end callback, however, this was the same as what it does currently, since cudaFuture is immediately marked completed when created and thus runs all callbacks inline: https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/ProcessGroupNCCL.cpp#L1046. 

Based on feedback from @nbcsm and a few others in this thread, it seems that the best option is to continue to report only the host time, and let GPU events be traced appropriately via CUPTI using the new kineto-based torch.profiler. 

--- Previous discussion follows ---
To properly fix this, we can take 1 of 2 approaches:

1. Use `cudaStreamAddCallback` to end the recordFunction properly when the collective finishes (basically run the end cb once all operations enqueued on the stream are done, and the nccl collective is the last thing to be enqueued on the stream before we run this callback. This will ensure that we report the host time correctly in the profiler.
2. Migrate cudaFuture to be a true future, in the sense that when using it with ProcessGroupNCCL, we mark it as completed only when outputs of collective are ready, and run any queued callbacks after that. cc @lw, is this a possible approach we can take with respect to CUDAFuture or will it break too many assumptions? 

There are a few more general ideas of how we can profile NCCL-based collectives with the profiler:

1) Report cpu host time for the collectives. This is basically the time it was enqueued to when the GPU notifies operation is complete to the host (via `cudaStreamAddCallback`). This will effectively give the time the NCCL collective spent executing, but will be reported as host time and that's sort of confusing as it ran on the GPU. Will also need to benchmark the perf impact of `cudaStreamAddCallback`. 
2) Report only the time it took to launch allreduce (i.e. enqueue it on the nccl stream). This may be reasonable if the profiler is only enabled without `use_cuda=True` as it gives the host time that was spent enqueueing the nccl kernel. However, this is probably not the output that the user wants if they would like to determine GPU time.
3) For the above case, when profiler is enabled with `use_cuda=True`, run end callbacks on a stream synchronize, i.e. `ProcessGroupNCCL::WorkNCCL::synchronize()`. This will ensure that appropriate cuda events are created when the nccl kernel is enqueued to when we synchronize it with the main stream (at which point we can enqueue dependent ops and things will be serialized appropriately).

**Comment by lw** [comment]
> Migrate cudaFuture to be a true future

What exactly is your proposal here? How do you intend to detect when the operation completes on the device, without introducing a performance overhead? How would you support the users who actually don't want to wait so long, and would rather be notified as soon as the NCCL kernels have been enqueued, since they just want to enqueue other kernels after them?

As a general note, I'm perplexed by why we care about the _CPU_ time of a GPU operation. The async nature of CUDA makes this intrinsically hard to measure. Shouldn't we rather measure the GPU time of such ops?

**Comment by rohan-varma** [comment]
@lw - Just clarified the overall goals a bit more in the issue. I think we can use `cudaStreamAddCallback` to run callbacks after the GPU execution has finished, although you're right that this should probably not be the default as many users want to simply enqueue kernels and continue. If we do need to support this, we could probably add a flag or new API that is only available for cudaFuture that uses `cudaStreamAddCallback`, although that is a bit hacky. There are a few proposals in the above issue on how we can profile collectives so as not to need `cudaStreamAddCallback`.

**Comment by lw** [comment]
I'd be careful with adding a new mode or flag or API that is only used by the profiler, as it might mean that the code behaves differently when profiled, thus meaning that the resulting profile might not give accurate information about the "original" unprofiled code.

If you really need to run a CPU function when the async GPU work completes, I'd suggest to keep adding a callback to the future, as we do now, and keep invoking that callback "immediately", but then in that callback do one of two things:
- either call `cudaStreamAddCallback`, and pass to it a second callback, and it will be this second callback once invoked that will mark the operation as completed in the profiler;
- or, in the callback, record a new event in the current streams, add this event to a global list somewhere, and have a global static thread busy-poll on the events of this list and, when one completes, update the profile as above.

These options both just layer on top of the current CUDAFuture, thus not requiring any change and ensuring the future behaves the same both when profiled and when not. The two are semantically equivalent, the choice boils down to how much we care about latency vs how much we're willing to "waste" CPU cycles by busy-polling.

**Comment by nbcsm** [comment]
In the new PyTorch profiler (kineto based profiler), `record_function before/end` invocation only emits a host side side. GPU side events are traced in an async way via CUPTI separately. And profiler will correlate host/device events together in the end.

To align with the design principle, seems report `general idea # 2` to profiler will be enough.
> Report only the time it took to launch allreduce (i.e. enqueue it on the nccl stream). This may be reasonable if the profiler is only enabled without use_cuda=True as it gives the host time that was spent enqueueing the nccl kernel. However, this is probably not the output that the user wants if they would like to determine GPU time.

@gdankel @ilia-cher for more comments.

**Comment by lw** [comment]
@nbcsm Awesome! If the async device-side things can be dealt with separately, by appropriate tools (kineto/CUPTI) this would greatly simplify the code for the ProcessGroup/Future!

**Comment by gdankel** [comment]
Right, only caveat is that Kineto currently only supports linux. But I think it's better to invest in this direction overall for sure.

**Comment by lw** [comment]
I see, but I think NCCL is Linux-only too, so that's fine I guess?

**Comment by rohan-varma** [comment]
We have taken @nbcsm's suggestion and GPU kernel  events such as ncclAllreduce can be seen when using `torch.profiler` enabled with the CUDA activity.

**Comment by Rivendile** [comment]
@rohan-varma Hi, I try to use `torch.profiler ` with the following settings, but the profiling result does not show ncclAllreduce. Is there any suggestions?
PyTorch version: nightly, 1.9.0
models: ResNet50, horovod, multi-machine multi-GPU
![image](https://user-images.githubusercontent.com/17983373/120789027-9d836400-c563-11eb-9391-3e15cf27ad40.png)
