### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cudnn_version'

### ISSUE THREAD

**Issue by Apogentus** [pytorch/pytorch#5224]
Hi, 
I have successfully installed pytorch on windows 7 64 bit with command:
`conda install pytorch=0.3.0 cudatoolkit=8 cudnn=6`
When I call `torch.__version__` I get `'0.3.0b0+591e73e'` but when I run `print( torch.backends.cudnn.version() )` I get error message:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-2e0c1c373ea5> in <module>()
----> 1 print( torch.backends.cudnn.version() )

C:\Development\Anaconda3\lib\site-packages\torch\backends\cudnn\__init__.py in version()
     52 
     53 def version():
---> 54     if _libcudnn() is None:
     55         return None
     56     return __cudnn_version

C:\Development\Anaconda3\lib\site-packages\torch\backends\cudnn\__init__.py in _libcudnn()
     40             lib.cudnnGetErrorString.restype = ctypes.c_char_p
     41             __cudnn_version = lib.cudnnGetVersion()
---> 42             compile_version = torch._C._cudnn_version()
     43             # Check that cuDNN major and minor versions match
     44             if (__cudnn_version // 100) != (compile_version // 100):

AttributeError: module 'torch._C' has no attribute '_cudnn_version'`

What should I do to check that indeed cuDNN is working?

**Comment by Apogentus** [comment]
UPDATE: the problem appears during the first run of `print( torch.backends.cudnn.version() )`, second and successive runs successfully return `6021`.

**Comment by Apogentus** [comment]
Solved by installing CUDA Developer Toolkit and cuDNN.

**Comment by XinyingZheng** [comment]
you installed is cuda8.0? or 9.0 or 10.0?

**Comment by XinyingZheng** [comment]
which CUDA Developer Toolkit and cuDNN did you install ,
I tried CUDA9.0 and 10.0,still get the error AttributeError: module 'torch._C' has no attribute '_cudnn_version. 
look forward to your reply.
