### ISSUE TITLE
MultiHeadAttention bias=False regression

### ISSUE THREAD

**Issue by tbennun** [pytorch/pytorch#52257]
## 🐛 Bug

`MultiHeadAttention` does not respect `bias=False` in the output projection. It seems that it was changed as part of a PR: https://github.com/pytorch/pytorch/commit/eace0533985641d9c2f36e43e3de694aca886bd9#diff-61bd5e4f390b965228ead6bb0efcad5b9b5299d833bcf5c2aa11ebaebb39ba29L794

Is this the intended behavior?

@ezyang 

## To Reproduce

1. Create a MultiHeadAttention module with `torch.nn.MultiheadAttention(N, H, bias=False)`
1. The module's `out_proj` field as a non-None, nonzero bias

## Expected behavior

The bias in `out_proj` should be None.

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1 and latest master
 - OS (e.g., Linux): All
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

N/A

cc @ezyang @gchanan @zhangguanheng66

**Comment by gchanan** [comment]
I confirmed this changed between 1.5 and 1.6.

**Comment by jbschlosser** [comment]
Confirmed with @zhangguanheng66 that the new behavior is unintended. Both in and out projection biases should be affected by the `bias` flag.

Suggested fix is to revert [this line](https://github.com/pytorch/pytorch/blob/08017f45988ff05e72a51624ab6c3efb203ca869/torch/nn/modules/activation.py#L891) back to its 1.5 version: `self.out_proj = Linear(embed_dim, embed_dim, bias=bias)`.

For MHA to be `torch.jit.script`able, I think type annotations for both [`in_proj_bias`](https://github.com/pytorch/pytorch/blob/08017f45988ff05e72a51624ab6c3efb203ca869/torch/nn/functional.py#L4518) and [`out_proj_bias`](https://github.com/pytorch/pytorch/blob/08017f45988ff05e72a51624ab6c3efb203ca869/torch/nn/functional.py#L4524) params of `F.multi_head_attention_forward` should be `Optional[Tensor]`.

This change seems to remove the need for `_LinearWithBias`, but I may be wrong.
