### ISSUE TITLE
Keep the requires_grad true after comparison of a matrix with a value

### ISSUE THREAD

**Issue by Bajo1994** [pytorch/pytorch#52250]
Assume that
`a=torch.randn(3,3,requires_grad=True)`
if I do 
`b=(a>0.1)`
then 
`b.requires_grad `
would be False. 
How can I avoid missing the graph if I want to compare a matrix versus a value?

**Comment by SsnL** [comment]
comparison is not differentiable

**Comment by ngimel** [comment]
Closing, this is expected behavior. Result of comparison is a bool tensor, and bool tensors are not differentiable. If you want a differentiable output, probably you need a[b].
