### ISSUE TITLE
Impossible to export ONNX as RAW

### ISSUE THREAD

**Issue by divideconcept** [pytorch/pytorch#52261]
## 🐛 Bug

The OperatorExportTypes.RAW export type always fail during ONNX export, no matter how complex or simple the model.

## To Reproduce

1. Copy and run the code below
2. It fails with "RuntimeError: unexpected attribute kind"
3. It won't fail if you comment the operator_export_type line, or set any other export type than RAW

```
import torch
import torch.nn as nn

class SimpleConv(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, 3)

    def forward(self, x):
        return self.conv1(x)

import os
import torch.onnx
from torch.onnx import OperatorExportTypes
torch.onnx.export(SimpleConv(),
                  torch.zeros((1,1,16,16)),
                  open(os.devnull,"wb"),
                  verbose=True,
                  operator_export_type=OperatorExportTypes.RAW
                 )
```

The error message comes from here: https://github.com/pytorch/pytorch/blob/v1.7.1/torch/csrc/jit/serialization/export.cpp#L665

## Expected behavior

Proper RAW export as documented here:
https://pytorch.org/docs/stable/onnx.html#raw

## Environment

 - PyTorch 1.7.1
 - Windows 10
 - Miniconda

## Additional context

NB: ONNX RAW export is particularly important for proper PyTorch model graph analysis. The ONNX export verbose provides much more details (comprehensive list of tensor sizes) than the jit trace graph. Hence a working ONNX RAW export would be much appreciated. Other ONNX export types don't match PyTorch modules 1:1.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
#59160 removed raw export type.

**Comment by Sheshank-s** [comment]
Looks like the removal of RAW needs to be updated in the documentation as well

**Comment by garymm** [comment]
That's happening in #60249
