### ISSUE TITLE
tutorials :: beginner :: audio_classifier_tutorial

### ISSUE THREAD

**Issue by madkote** [pytorch/pytorch#52275]
## 📚 Documentation
Hello, the documentation for beginner audio classifier does missing the source code.

URL : https://pytorch.org/tutorials/beginner/audio_classifier_tutorial.html?highlight=audio

cc @jlin27 @mruberry

**Comment by brianjo** [comment]
Sorry, that document was an artifact of a tutorial that was removed. I did a redirect to it. FYI @holly1238

**Comment by madkote** [comment]
@brianjo thanks for update. so the old tutorial is speech command tutorial now?

https://pytorch.org/tutorials/intermediate/speech_command_recognition_with_torchaudio.html
