### ISSUE TITLE
Documentation code for sampling from categorical distribution throws an error on master

### ISSUE THREAD

**Issue by christinaheinze** [pytorch/pytorch#5227]
Hi, 

the following code from the documentation of the categorical distribution (http://pytorch.org/docs/master/distributions.html#categorical) throws an error on master:

```
import torch
import torch.distributions as dis
m = dis.Categorical(torch.Tensor([ 0.25, 0.25, 0.25, 0.25 ]))
m.sample()
```
yields

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/heinzedeml/anaconda3/lib/python3.6/site-packages/torch/distributions/categorical.py", line 97, in sample
    return sample_2d.contiguous().view(sample_shape)
RuntimeError: invalid argument 2: size '[]' is invalid for input with 1 elements at /Users/heinzedeml/Documents/code/pytorch/aten/src/TH/THStorage.c:41
```

Calling `m.sample(sample_shape = torch.Size([1]))` instead works. 

I am using:

OS: macOS High Sierra
PyTorch version: 0.4.0a0+f96f3c3
How you installed PyTorch (conda, pip, source): source
Python version: Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 6 2017, 12:04:38)
CUDA/cuDNN version: --
GPU models and configuration: --
GCC version (if compiling from source): GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

Thanks!

**Comment by fritzo** [comment]
@apaszke is this a bug in `.view()`? I'm not seeing why we can't create a scalar `.view()` of a tensor with one element.

**Comment by fritzo** [comment]
This indeed appears to be a bug in `.view()`:
```py
>>> import torch
>>> torch.__version__
'0.4.0a0+ca5071d'
>>> torch.Tensor([0]).view(torch.Size())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: invalid argument 2: size '[]' is invalid for input with 1 elements at /Users/fritzobermeyer/pytorch-dev/2.7/aten/src/TH/THStorage.c:41
```

**Comment by apaszke** [comment]
cc @gchanan

**Comment by vishwakftw** [comment]
I think this has been fixed on `master`.
