### ISSUE TITLE
[convenience] Make torch.nn.Module.eval() / torch.nn.Module.train() return self

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#52272]
So we can write `model = MyModule().eval()` (this is needed in inference because by default `training = True`) instead of `model = MyModule(); model.eval()`. E.g. `torch.nn.Model.to()` already returns self (despite the side effect). 

Even if existing overrides of eval/train won't support this contract, for new code it'd be nice.

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Looks like this is already being done: [train()](https://github.com/pytorch/pytorch/blob/6e1a5b1196aa0277a2113a4bca75b6e0f2b4c0c8/torch/nn/modules/module.py#L1450) / [eval()](https://github.com/pytorch/pytorch/blob/6e1a5b1196aa0277a2113a4bca75b6e0f2b4c0c8/torch/nn/modules/module.py#L1465)

**Comment by vadimkantorov** [comment]
oh :)
