### ISSUE TITLE
We need rtx A6000 sm_86 and cuda 11.2 support

### ISSUE THREAD

**Issue by youmebangbang** [pytorch/pytorch#52288]
I just received my new rtx A6000 to find out I can't run it with pytorch because it uses sm_86 which uses cuda 11.2.  Will pytorch soon support this card? Is there a workaround? Thanks.

cc @malfet @seemethere @walterddr @ngimel

**Comment by malfet** [comment]
PyTorch-1.7.1 with CUDA-11.0 should work with your GPU, although would have less than optimal performance.

CUDA-11.2 builds are available using nightly release channel, i.e. you should be able to install it using `pip install  torch -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html`, although due to the several correctness bugs it is better avoided for a large scale training.

**Comment by caseybasichis** [comment]
I'm running into the same issue -- torch_nightly doesnt give a different result:

`python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.current_device()
/home/me/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
0
`

**Comment by malfet** [comment]
@caabernathy you've downloaded PyTorch for CUDA-10.2(see output of `torch.__version__`), which does not have support for sm_80+ GPUs, you need to download PyTorch build with CUDA-11 support

**Comment by caseybasichis** [comment]
I'm installing directly from the link above.  Here is a fresh install showing the same behavior.

```
pip3 uninstall torch
WARNING: Skipping torch as it is not installed.
caseybasichis@caseybasichis-X299-AORUS-Gaming-3:~$ pip3 install torch -f https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu112/torch_nightly.html
Collecting torch
  Using cached torch-1.8.1-cp38-cp38-manylinux1_x86_64.whl (804.1 MB)
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from torch) (1.20.2)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.8/site-packages (from torch) (3.7.4.3)
Installing collected packages: torch
Successfully installed torch-1.8.1
caseybasichis@caseybasichis-X299-AORUS-Gaming-3:~$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.8.1+cu102'
>>> 
>>> 
>>> torch.cuda.current_device()
/home/caseybasichis/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
0

```

**Comment by caseybasichis** [comment]
Reinstalling with --no-cache-dir made no difference.

I'm installing the fresh nightly -- version still says 1.8.1+cu102  and gives the sm_86 error

**Comment by detkov** [comment]
I have the same problem

**Comment by kousu** [comment]
The only (pre-compiled) combination I've found that works so far is to use the ones from the torch conda repos, as described on https://pytorch.org/get-started/locally/:

![2021-05-31-151416_797x321_scrot](https://user-images.githubusercontent.com/987487/120233063-e913d600-c222-11eb-92a1-88694fcfc226.png)


```
conda create -p a6000 python=3.8 pytorch cudatoolkit=11.1 -c pytorch -c nvidia
conda activate a6000
time python -c '
import torch

torch.manual_seed(1337)

# GPU usage needs to be explicit in torch
cuda = torch.device("cuda")

# create some tensors
A = torch.randn(30000, 10000, dtype=torch.float16, device=cuda)
B = torch.randn(10000, 20000, dtype=torch.float16, device=cuda)

# multiply them
C = A @ B

# display
print(C)
print("device:", C.device)

# inspect GPU memory usage
import sys, os
print(f"We are PID = {os.getpid()}")
os.system("nvidia-smi")
  '
```

This gives me:

```
tensor([[   5.1328, -104.2500,   -3.1445,  ..., -115.8125,   25.5625,
         -161.5000],
        [  58.8750,   33.5000,  105.1250,  ...,   45.2188,  -25.1250,
           64.2500],
        [  17.9062,   92.9375,   38.1562,  ...,   14.0312,   30.7812,
         -110.7500],
        ...,
        [  14.7656,  110.3750,   14.0781,  ...,  106.1875, -151.0000,
          -65.3750],
        [ 150.7500,  -80.3750,  -27.6719,  ...,  -66.1250,  -99.1875,
          153.6250],
        [ -13.2422,    7.9688,  -27.8906,  ...,  103.1250,   29.6094,
           77.6875]], device='cuda:0', dtype=torch.float16)
device: cuda:0
We are PID = 17350
Mon May 31 11:22:17 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  RTX A6000           Off  | 00000000:01:00.0 Off |                  Off |
| 30%   21C    P2    88W / 300W |   5747MiB / 48685MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  RTX A6000           Off  | 00000000:41:00.0 Off |                  Off |
| 30%   18C    P8     8W / 300W |      2MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  RTX A6000           Off  | 00000000:81:00.0 Off |                  Off |
| 30%   18C    P8    10W / 300W |      2MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  RTX A6000           Off  | 00000000:C1:00.0 Off |                  Off |
| 30%   18C    P8     6W / 300W |      2MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     17350      C   python                           5745MiB |
+-----------------------------------------------------------------------------+
```

**Comment by hugbubby** [comment]
Don't you guys just love it when package maintainers suggest a fix that doesn't work, and then immediately close the issue afterwards?

**Comment by makman09** [comment]
Please re-open the issue. There isn't a viable solution yet.

**Comment by malfet** [comment]
CUDA-11.1 builds should have sm_86 support, as seems to have been confirmed by https://github.com/pytorch/pytorch/issues/52288#issuecomment-851643398
CUDA guaranteed strong backward compatibility, so https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html should work on systems with CUDA-11.2 or 11.3 drivers installed. If those builds do not contain code for sm_86 GPUs, please open a new issue and we'll look into it on priority.
CUDA-11.2 is not officially supported by PyTorch, as correctness issues were discovered during additional testing, for more details please see https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998

P.S. There are experimental CUDA-11.3 builds available here https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

**Comment by esnvidia** [comment]
> CUDA-11.1 builds should have sm_86 support, as seems to have been confirmed by [#52288 (comment)](https://github.com/pytorch/pytorch/issues/52288#issuecomment-851643398)
> CUDA guaranteed strong backward compatibility, so https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html should work on systems with CUDA-11.2 or 11.3 drivers installed. If those builds do not contain code for sm_86 GPUs, please open a new issue and we'll look into it on priority.
> CUDA-11.2 is not officially supported by PyTorch, as correctness issues were discovered during additional testing, for more details please see [#50232 (comment)](https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998)
> 
> P.S. There are experimental CUDA-11.3 builds available here https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

@malfet CUDA 11.3 builds currently do not work with the A6000:
```
pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
```
```
import torch
import torch.nn as nn
import torch.optim as optim

EPOCHS = 20
BATCH_SIZE = 4096
LEARNING_RATE = 0.001

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

class Model(nn.Module):
    def __init__(self, in_dims, out_dims):
        super(Model, self).__init__()
        self.layer1 = nn.Linear(in_dims, 128)
        self.layer2 = nn.Linear(128, out_dims)
        
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()
        
    def forward(self, x):
        x = self.relu1(self.layer1(x))
        x = self.relu2(self.layer2(x))
        return x

model = Model(20, 1).to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
```
Gives a warning:
```
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```
And attempting to train the model gives a RuntimeError:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
```

**Comment by ngimel** [comment]
@esnvidia you have a cuda 10 build of pytorch somewhere on you system, and this is what gets imported. With cuda 11.1 1.9 release (and with cuda 11.3 nightly builds) you'd see the following:
```
python -c "import torch; print(torch.__version__); print(torch.cuda.get_arch_list())"
1.9.0+cu111
['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']

```

**Comment by malfet** [comment]
@esnvidia can you please run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py and share its output here?

**Comment by esnvidia** [comment]
@malfet @ngimel Looks like issue might be with nightly [RAPIDS](https://rapids.ai/start.html#get-rapids) Aug 2021 (21.08) nightly install only goes up to CUDA 11.2 as of right now.
`conda list cuda*`

cudatoolkit               11.2.72

So after creating this base RAPIDS environment and adding Pytorch with the pip install above: 
```pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html```
Oddly causes a CUDA 10.2 install of Pytorch in the conda env.
```
python -c "import torch; print(torch.__version__); print(torch.cuda.get_arch_list())"
1.9.0+cu102
['sm_37', 'sm_50', 'sm_60', 'sm_70']
```

**Comment by longyuxi** [comment]
I was having this issue too, that `conda uninstall` doesn't seem to uninstall the cu102 build, but then I found that I had a `1.8.1+cu102` build installed through `pip` as well. After running `pip uninstall torch` and installing the 1.7.1 build, this worked perfectly.

**Comment by malfet** [comment]
If pip and conda installation exists for the same version of Python runtime, then conda package takes preference, but  uninstalling it will make runtime fall back to the wheel. One can always check where PyTorch package is located by executing something like `python -c "import torch;print(torch.__file__)"`

**Comment by johngrabner** [comment]
> CUDA-11.1 builds should have sm_86 support, as seems to have been confirmed by [#52288 (comment)](https://github.com/pytorch/pytorch/issues/52288#issuecomment-851643398) CUDA guaranteed strong backward compatibility, so https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html should work on systems with CUDA-11.2 or 11.3 drivers installed. If those builds do not contain code for sm_86 GPUs, please open a new issue and we'll look into it on priority. CUDA-11.2 is not officially supported by PyTorch, as correctness issues were discovered during additional testing, for more details please see [#50232 (comment)](https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998)
> 
> P.S. There are experimental CUDA-11.3 builds available here https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

I'm using the prebuilt docker images and was on pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime.  The comment "PyTorch-1.7.1 with CUDA-11.0 should work with your GPU, although would have less than optimal performance".  I just purchased 2 A6000 and when I try the prebuilt docker image pytorch/pytorch:1.10.0-cuda11.3-cudnn8 I get the error 

All distributed processes are registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------


```
7f524a4541a4:23:23 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
7f524a4541a4:120:120 [1] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
```
What docker prebuilt image would you recommend as of March 2022?

**Comment by mjkvaak** [comment]
You can manage the installation with pip when you specify the desired cuda version in `--extra-index-url`. Namely,
```sh
pip3 install torch torchvision torchaudio
``` 
will compile torch with cuda 10.2, whereas
```sh
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
``` 
would install with cuda 11.3. Source: https://pytorch.org/get-started/locally/#start-locally

**Comment by harshshredding** [comment]
If you run a list of pip installs like the following for your env setup:
```
pip install blah
pip install blahblah
.
.
.
```
It is possible that one of these installs **downgraded** your torch installation, causing `torch` to not support a new architecture.
To check whether this indeed happened, try installing PyTorch while **forcing upgrade** as follows:
```
pip install torch torchvision torchaudio --upgrade
```
If you no longer see the error, you have verified your hypothesis.
