### ISSUE TITLE
Compilation errors, when compiling pytorch on Ubuntu 17.10 or newer with GCC 5

### ISSUE THREAD

**Issue by sdmonov** [pytorch/pytorch#5229]
This issue is related to Issue #5136 which describes problems with both GCC 6 and 5. Creating it separately as the problems are different and to be tracked separately.

The issue comes from a bug in `libstdc++-5-dev` package in Ubuntu 17.10 and newer. Macro `_GLIBCXX_USE_C99` is not defined in `/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h` which leads to errors related to missing members of **std** name space, such as `std::to_string`, `std::isnan`, `std::isinf` (and more). The bug is tracked under https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1725848 and won't be fixed as GCC 5 is considered outdated and not supported by Ubuntu any more.

It will be good if we shows a meaningful error when GCC 5 is used on Ubuntu 17.10 or newer.

**Note:** Cuda 8.0 support GCC 5 or older only. In case Cuda 8.0 is needed, current workaround is to use GCC 4.8 which has been confirmed to work.

**Comment by vadimkantorov** [comment]
gcc 5.4.0 also has some problems with isnan and isinf (magma also has compilation issues now): http://icl.cs.utk.edu/magma/forum/viewtopic.php?t=1659, https://bitbucket.org/icl/magma/pull-requests/4/replaced-isnan-isinf-by-std-isnan-std/diff

**Comment by floringogianu** [comment]
@gaoyangyiqiao yes, I eventually followed the instructions [here](https://medium.com/@Inoryy/compiling-pytorch-4-0-on-ubuntu-17-10-with-cuda-9-0-and-python-3-6-6769a0df56d5) and built it with `gcc 4.8.5`. Also with `gcc 5.5.0` Ubuntu 18.04.

**Comment by ngimel** [comment]
Closing, please reopen if needed

**Comment by Abbyyan** [comment]
I've build gcc7 and add it into `$PATH`. But it still get this error.
```shell
  The C++ compiler does not support required functions.  This is very likely
  due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
  newer.  For more information, see:
  https://github.com/pytorch/pytorch/issues/522
```
The log is as follows.
```shell
(base) xxx@TENCENT64:~/gpt_model/pytorch/pytorch> python setup.py install
Building wheel torch-1.7.0a0+7a64b0c
-- Building version 1.7.0a0+7a64b0c
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/data1/mm64/xxx/gpt_model/pytorch/pytorch/torch -DCMAKE_PREFIX_PATH=/home/xxx/anaconda3/lib/python3.7/site-packages -DJAVA_HOME=/home/mmdev/devpkg/java/jdk1.7.0_04 -DNUMPY_INCLUDE_DIR=/home/xxx/anaconda3/lib/python3.7/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/xxx/anaconda3/bin/python -DPYTHON_INCLUDE_DIR=/home/xxx/anaconda3/include/python3.7m -DPYTHON_LIBRARY=/home/xxx/anaconda3/lib/libpython3.7m.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0+7a64b0c -DUSE_NUMPY=True /data1/mm64/xxx/gpt_model/pytorch/pytorch
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Failed
CMake Error at cmake/MiscCheck.cmake:81 (message):
  The C++ compiler does not support required functions.  This is very likely
  due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
  newer.  For more information, see:
  https://github.com/pytorch/pytorch/issues/5229
Call Stack (most recent call first):
  CMakeLists.txt:475 (include)


-- Configuring incomplete, errors occurred!
See also "/data1/mm64/xxx/gpt_model/pytorch/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/data1/mm64/xxx/gpt_model/pytorch/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 748, in <module>
    build_deps()
  File "setup.py", line 332, in build_deps
    cmake=cmake)
  File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/xxx/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/data1/mm64/xxx/gpt_model/pytorch/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/xxx/anaconda3/lib/python3.7/site-packages', '-DJAVA_HOME=/home/mmdev/devpkg/java/jdk1.7.0_04', '-DNUMPY_INCLUDE_DIR=/home/xxx/anaconda3/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/xxx/anaconda3/bin/python', '-DPYTHON_INCLUDE_DIR=/home/xxx/anaconda3/include/python3.7m', '-DPYTHON_LIBRARY=/home/xxx/anaconda3/lib/libpython3.7m.so.1.0', '-DTORCH_BUILD_VERSION=1.7.0a0+7a64b0c', '-DUSE_NUMPY=True', '/data1/mm64/xxx/gpt_model/pytorch/pytorch']' returned non-zero exit status 1.
(base) xxx@TENCENT64:~/gpt_model/pytorch/pytorch> gcc --version          
gcc (GCC) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Abbyyan** [comment]
> I've build gcc7 and add it into `$PATH`. But it still get this error.
> 
> ```shell
>   The C++ compiler does not support required functions.  This is very likely
>   due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
>   newer.  For more information, see:
>   https://github.com/pytorch/pytorch/issues/522
> ```
> 
> The log is as follows.
> 
> ```shell
> (base) xxx@TENCENT64:~/gpt_model/pytorch/pytorch> python setup.py install
> Building wheel torch-1.7.0a0+7a64b0c
> -- Building version 1.7.0a0+7a64b0c
> cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/data1/mm64/xxx/gpt_model/pytorch/pytorch/torch -DCMAKE_PREFIX_PATH=/home/xxx/anaconda3/lib/python3.7/site-packages -DJAVA_HOME=/home/mmdev/devpkg/java/jdk1.7.0_04 -DNUMPY_INCLUDE_DIR=/home/xxx/anaconda3/lib/python3.7/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/home/xxx/anaconda3/bin/python -DPYTHON_INCLUDE_DIR=/home/xxx/anaconda3/include/python3.7m -DPYTHON_LIBRARY=/home/xxx/anaconda3/lib/libpython3.7m.so.1.0 -DTORCH_BUILD_VERSION=1.7.0a0+7a64b0c -DUSE_NUMPY=True /data1/mm64/xxx/gpt_model/pytorch/pytorch
> -- Performing Test SUPPORT_GLIBCXX_USE_C99
> -- Performing Test SUPPORT_GLIBCXX_USE_C99 - Failed
> CMake Error at cmake/MiscCheck.cmake:81 (message):
>   The C++ compiler does not support required functions.  This is very likely
>   due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
>   newer.  For more information, see:
>   https://github.com/pytorch/pytorch/issues/5229
> Call Stack (most recent call first):
>   CMakeLists.txt:475 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/data1/mm64/xxx/gpt_model/pytorch/pytorch/build/CMakeFiles/CMakeOutput.log".
> See also "/data1/mm64/xxx/gpt_model/pytorch/pytorch/build/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "setup.py", line 748, in <module>
>     build_deps()
>   File "setup.py", line 332, in build_deps
>     cmake=cmake)
>   File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
>     rerun_cmake)
>   File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
>     self.run(args, env=my_env)
>   File "/data1/mm64/xxx/gpt_model/pytorch/pytorch/tools/setup_helpers/cmake.py", line 141, in run
>     check_call(command, cwd=self.build_dir, env=env)
>   File "/home/xxx/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/data1/mm64/xxx/gpt_model/pytorch/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/xxx/anaconda3/lib/python3.7/site-packages', '-DJAVA_HOME=/home/mmdev/devpkg/java/jdk1.7.0_04', '-DNUMPY_INCLUDE_DIR=/home/xxx/anaconda3/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/xxx/anaconda3/bin/python', '-DPYTHON_INCLUDE_DIR=/home/xxx/anaconda3/include/python3.7m', '-DPYTHON_LIBRARY=/home/xxx/anaconda3/lib/libpython3.7m.so.1.0', '-DTORCH_BUILD_VERSION=1.7.0a0+7a64b0c', '-DUSE_NUMPY=True', '/data1/mm64/xxx/gpt_model/pytorch/pytorch']' returned non-zero exit status 1.
> (base) xxx@TENCENT64:~/gpt_model/pytorch/pytorch> gcc --version          
> gcc (GCC) 7.5.0
> Copyright (C) 2017 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```

Solved this problem by remove the `build` directory and add `gcc7` into `$PATH`

**Comment by denfromufa** [comment]
still does not work for me for master pytorch with gcc 7.5 in conda environment:


```
python setup.py install
Building wheel torch-1.9.0a0+22b1217
-- Building version 1.9.0a0+22b1217
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_ARGS=-DCMAKE_LINKER=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-strip -DCUDAToolkit_ROOT=/hrtc/apps/cuda/10.1/x86_64 -DCUDA_TOOLKIT_ROOT_DIR=/hrtc/apps/cuda/10.1/x86_64 -DCMAKE_ARGS_CONDA_NVCC_BACKUP=-DCMAKE_LINKER=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/torch -DCMAKE_PREFIX_PATH=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi:/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/x86_64-conda-linux-gnu/sysroot/usr -DNUMPY_INCLUDE_DIR=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/lib/python3.7/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/python -DPYTHON_INCLUDE_DIR=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/include/python3.7m -DPYTHON_LIBRARY=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/lib/libpython3.7m.a -DTORCH_BUILD_VERSION=1.9.0a0+22b1217 -DUSE_NUMPY=True /data/gpfs/Projects/CSE_HPML/pytorch/pytorch
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at CMakeLists.txt:36 (message):
  C++ standard version definition detected in environment variable.PyTorch
  requires -std=c++14.  Please remove -std=c++ settings in your environment.


-- Not forcing any particular BLAS to be found
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Failed
CMake Error at cmake/MiscCheck.cmake:84 (message):
  The C++ compiler does not support required functions.  This is very likely
  due to a known bug in GCC 5 (and maybe other versions) on Ubuntu 17.10 and
  newer.  For more information, see:
  https://github.com/pytorch/pytorch/issues/5229
Call Stack (most recent call first):
  CMakeLists.txt:559 (include)


-- Configuring incomplete, errors occurred!
See also "/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 320, in build_deps
    cmake=cmake)
  File "/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/tools/build_pytorch_libs.py", line 55, in build_caffe2
    rerun_cmake)
  File "/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_ARGS=-DCMAKE_LINKER=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-strip -DCUDAToolkit_ROOT=/hrtc/apps/cuda/10.1/x86_64 -DCUDA_TOOLKIT_ROOT_DIR=/hrtc/apps/cuda/10.1/x86_64', '-DCMAKE_ARGS_CONDA_NVCC_BACKUP=-DCMAKE_LINKER=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/x86_64-conda-linux-gnu-strip', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/data/gpfs/Projects/CSE_HPML/pytorch/pytorch/torch', '-DCMAKE_PREFIX_PATH=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi:/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/x86_64-conda-linux-gnu/sysroot/usr', '-DNUMPY_INCLUDE_DIR=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/bin/python', '-DPYTHON_INCLUDE_DIR=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/include/python3.7m', '-DPYTHON_LIBRARY=/data/gpfs/Projects/CSE_hpda/condall/py37/envs/py37.pytorch.1.7.ompi/lib/libpython3.7m.a', '-DTORCH_BUILD_VERSION=1.9.0a0+22b1217', '-DUSE_NUMPY=True', '/data/gpfs/Projects/CSE_HPML/pytorch/pytorch']' returned non-zero exit status 1.

```

**Comment by denfromufa** [comment]
I was getting this error with gcc toolchain from conda, after removing this issue got resolved.

**Comment by green-slowmoe** [comment]
getting the same error using GCC 11.2.0, even when trying to build outside anaconda.
@denfromufa: what did you remove exactly?
