### ISSUE TITLE
`torch.acos` on Windows returns different values between CUDA and CPU

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#52299]
For some weird reason it only happens on Windows with complex double types
```
>>> x=torch.tensor(0.0-1e20j, dtype=torch.cdouble)
>>> x.acos()
tensor(1.5707963267948965579990+46.7448490404408616427645j,
       dtype=torch.complex128)
>>> x.to("cuda").acos()
tensor(1.5707963267948965579990-46.7448490404408616427645j, device='cuda:0',
       dtype=torch.complex128)
```
Same code with cfloats returns the same values:
```
>>> x=torch.tensor(0.0-1e20j, dtype=torch.cfloat)
>>> x.acos()
tensor(1.5707963705062866210938+46.7448463439941406250000j)
>>> x.to("cuda").acos()
tensor(1.5707963705062866210938+46.7448463439941406250000j, device='cuda:0')
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by mszhanyi** [comment]
perhaps relates to https://github.com/pytorch/pytorch/issues/42952

**Comment by malfet** [comment]
@mszhanyi no it is quite different, as #42952 is about CPU discrepancies, while this one is specifically about GPU. I.e. on CPU `torch.tensor(0.0-1e20j, torch.cfloat).acos()` and `torch.tensor(0.0-1e20j, torch.cdouble).acos()` are almost identical, but if the same is computed on GPU, values are different.

**Comment by malfet** [comment]
@ngimel found one potential source of problem: https://github.com/NVIDIA/thrust/blob/b59d1db95e47f616cbf583b01a0a858a8f7c382f/thrust/detail/complex/c99math.h#L69-L102

**Comment by allisonvacanti** [comment]
The PR referenced above (NVIDIA/thrust#1388) fixes the issue with `signbit` on MSVC.

**Comment by vladimir-aubrecht** [comment]
We couldn't reproduce the issue on latest versions, based on previous comments I am considering this fixed and closing issue. In case issue re-appear, please create new issue based on latest versions.
