### ISSUE TITLE
Is SVD really GPU parallel?

### ISSUE THREAD

**Issue by dvirginz** [pytorch/pytorch#52293]
I'm using [Pytorch SVD solver](https://pytorch.org/docs/stable/generated/torch.where.html) on huge batches of really small matrices, specifically, a usual batch is of shape
`M.shape=(100000,3,3)`
It seems as the computation of `torch.svd(M)` is not done in parallel on the GPU, rather each matrix at a time.

```
import time

start = time.time()
torch.rand(100,3,3).bmm(torch.rand(100,3,3))
time100bmm = time.time() - start

start = time.time()
torch.rand(10000,3,3).bmm(torch.rand(10000,3,3))
time10000bmm = time.time() - start

start = time.time()
torch.svd(M[:100])
time100SVD = time.time() - start

start = time.time()
torch.svd(M[:10000])
time10000SVD = time.time() - start

print(f"time100bmm {time100bmm:.3f} time10000bmm {time10000bmm:.3f} factor {time10000bmm/time100bmm:.3f} \n"
    f"time100SVD {time100SVD:.3f} time10000SVD {time10000SVD:.3f} factor {time10000SVD/time100SVD:.3f}")
```
```
time100bmm 0.000 time100bmm 0.004 factor 8.127 
time100SVD 0.091 time1000SVD 6.316 factor 69.137
```
I.e, while a batch X100 bigger slows `bmm` by a factor of 8, it slows `SVD` by a factor of 70.

Ideas?
Workarounds?

Thanks.

**Comment by dvirginz** [comment]
closed as I see it is an ongoing issue #9083 #41306

**Comment by IvanYashchuk** [comment]
The performance of SVD for batches of small matrices (up to 32x32) should be much better on master with https://github.com/pytorch/pytorch/pull/48436.

**Comment by tdvginz** [comment]
I can verify that with the nighly version of PyTorch the GPU version is faster than the CPU.
Thanks to all the contributors.
