### ISSUE TITLE
[TorchScript usability] Should report error when instance attributes are annotated outside `__init__`

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#52306]
## 🐛 Bug

Test case: [test-attr-annotation2.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-attr-annotation2.py)

In this example, we annotate an instance attribute outside `__init__` and the compiler does not complain about it. This does not make sense because type schema of instance attributes are inferred when analyzing `__init__`.  The compiler should issue an error for type annotation of instance attributes outside `__init__`.

Furthermore, if I annotate instance attribute with a wrong type ([test case](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-attr-annotation3.py)), the compiler does not complain about it either. Is type annotation of instance attribute not looked at at all?

Related to #50444 

cc @gmagogsfm

**Comment by PSSF23** [comment]
Can I be assigned to this issue? It looks quite interesting.

By my understanding, the current type check only concerns with explicitly stated types of the parameters or use `Tensor` as an inferred default. Some related source code:

https://github.com/pytorch/pytorch/blob/4cb534f92ef6f5b2ec99109b0329f93a859ae831/torch/csrc/jit/frontend/sugared_value.cpp#L332-L338

https://github.com/pytorch/pytorch/blob/1fc89d9ffcea234ccf9a35f60a7afc3cb0d406ee/aten/src/ATen/core/jit_type_base.h#L78-L93

And if the explicitly stated type is different from the actual parameter content, there is no further checks to stop the recasting of class attributes. Even the following code runs without errors:

```python
import torch

@torch.jit.script
class MyClass(object):
   def __init__(self, x: int):
      self.x = x

   def set(self, val: int):
       self.x: float = val

def fn(a: MyClass, b: int):
    a.set(b)
    return a.x

y = MyClass(1)
print("Eager: ", fn(y, "a string"))
print(type(y.x))
```

Results:

```
Eager:  a string
<class 'str'>
```

So the solution would be to implement some tests that prevent the type change by variable assignment. The annotation doesn't really matter as it cannot change the attribute types on its own. Hope I'm on good directions here.
