### ISSUE TITLE
Errors in scripting when using `_pair_from_first`

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#52329]
## 🐛 Bug

I find that https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/utils.py#L65 will cause some scripting error when I try to use it in any function that is scripted. error message is:
    check_save_load=True)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/testing/_internal/common_quantization.py", line 459, in ch
eckScriptable
    scripted = torch.jit.script(orig_mod)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_script.py", line 948, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 398, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 459, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/data/users/jerryzh/anaconda3/envs/py3/lib/python3.7/site-packages/torch/jit/_recursive.py", line 341, in create_methods_and_proper
ties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: Can't redefine method: forward on class: __torch__.torch.nn.quantized.modules.conv.Conv1d (of Python compilation unit at: 0x5
55d019387e0)

## To Reproduce

Apply:
```python
diff --git a/torch/nn/quantized/modules/conv.py b/torch/nn/quantized/modules/conv.py
index ba700711a48..477fdeae4ef 100644
--- a/torch/nn/quantized/modules/conv.py
+++ b/torch/nn/quantized/modules/conv.py
@@ -266,11 +266,10 @@ class Conv1d(_ConvNd):
                  groups: int = 1,
                  bias: bool = True,
                  padding_mode: str = 'zeros'):
-        kernel_size = _pair_from_first(kernel_size)
-        stride = _pair_from_first(stride)
-        padding = _pair_from_first(padding)
-        dilation = _pair_from_first(dilation)
-
+        kernel_size = _single(kernel_size)
+        stride = _single(stride)
+        padding = _single(padding)
+        dilation = _single(dilation)
         # Subclasses of _ConvNd needs to call _init rather than __init__. See
         # discussion on PR #49702
         super(Conv1d, self)._init(
@@ -281,12 +280,16 @@ class Conv1d(_ConvNd):
         return 'QuantizedConv1d'
 
     def set_weight_bias(self, w: torch.Tensor, b: Optional[torch.Tensor]) -> None:
+        stride = _pair_from_first(self.stride)
+        padding = _pair_from_first(self.padding)
+        dilation = _pair_from_first(self.dilation)
+
         if self.padding_mode == 'zeros':
             self._packed_params = torch.ops.quantized.conv1d_prepack(
-                w, b, self.stride, self.padding, self.dilation, self.groups)
+                w, b, stride, padding, dilation, self.groups)
         else:
             self._packed_params = torch.ops.quantized.conv1d_prepack(
-                w, b, self.stride, _pair(0), self.dilation,
+                w, b, stride, _pair(0), dilation,
                 self.groups)
 
     def _weight_bias(self):
```

run:
```python
python test/test_quantization.py TestStaticQuantizedModule.test_conv1d_api
```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @gmagogsfm

**Comment by zdevito** [comment]
The error being seen here is because hypothesis is trying to re-run a failing test, but once there is a jit compiler error related to the compilation of the Conv1d module, it gets left in an inconsistent state and future versions of compiling it report the 'Can't redefine method'. If you must use hypothesis in places where script compilation may fail, I suggest calling this at the start of the test to clean up the jit compilation state.
```        
from torch.testing._internal.jit_utils import clear_class_registry
clear_class_registry()
```

**Comment by jerryzh168** [comment]
resolved, thanks!
