### ISSUE TITLE
torch.empty_like example seems wrong

### ISSUE THREAD

**Issue by guilhermeleobas** [pytorch/pytorch#52375]
## 📚 Documentation

The example presented for [`torch.empty_like`](https://pytorch.org/docs/stable/generated/torch.empty_like.html#torch.empty_like) seems wrong:

```python
>>> torch.empty((2,3), dtype=torch.int64)
tensor([[ 9.4064e+13,  2.8000e+01,  9.3493e+13],
        [ 7.5751e+18,  7.1428e+18,  7.5955e+18]])
```

I guess the desided example would be something like:
```python
>>> a = torch.empty((2,3), dtype=torch.int64)
>>> torch.empty_like(a, dtype=torch.float64)
tensor([[ 9.4064e+13,  2.8000e+01,  9.3493e+13],
        [ 7.5751e+18,  7.1428e+18,  7.5955e+18]])
```

cc @brianjo @mruberry @gchanan

**Comment by gchanan** [comment]
yes, this looks wrong.  Probably don't need the `dtype` specification in empty_like, that's an uncommon usage.

**Comment by mruberry** [comment]
We would accept a PR improving the example(s) for torch.empty_like().

The simplest example should show that it produces a tensor with the same shape, dtype, and device as its input, but where all the values are uninitialized.

**Comment by anjali411** [comment]
reserved for onboarding
