### ISSUE TITLE
PyTorch old version link does not work (Access Denied)

### ISSUE THREAD

**Issue by xiaoyongzhu** [pytorch/pytorch#5237]
I wanted to use a specific version (0.3.0post4) for some reason, however after the 0.3.1 release, none of those 0.3.0post4 links work:(

Accessing the link from here (http://pytorch.org/previous-versions/), there are multiple 0.3.0post4 versions (such as below), and they will all have access denied error:
http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-manylinux1_x86_64.whl

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>34D2F67ACF238E76</RequestId>
<HostId>
nNj05osqG7nDRJs3r/tlMRQ2q5TsyrlZZT7zwNcvsOGNzeV62CwVHFK9o6ugSmX/cA9/GgyJXuE=
</HostId>
</Error>
```

Interestingly, all the old version (such as 0.2.0) works fine.

**Comment by soumith** [comment]
i'm taking a look

**Comment by soumith** [comment]
fixed the links now. please check the webpage again.
