### ISSUE TITLE
torch.autograd.Function doesn't support non-Tensor outputs

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#52415]
## 🐛 Bug

Certain modules could have return values that output non-Tensor values. Such modules cannot be checkpointed using `torch.util.checkpoint` since torch.autograd.Function doesn't support non-Tensor outputs. This limitation is enforced here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/python_function.cpp#L369-L370.

One such example was brought up in https://github.com/pytorch/pytorch/pull/50693, where modules might return `None`, or booleans as part of the output and such modules cannot be used with checkpointing.

## To Reproduce

```
import torch
from torch.utils.checkpoint import checkpoint

def foo():
    return 1, None, torch.rand(10)

checkpoint(foo)
```

Fails with: `TypeError: CheckpointFunctionBackward.forward: expected Tensor or tuple of Tensor (got int) for return value 0`

## Expected behavior

As part of gradient recording these non-Tensor outputs can be ignored and during the backward pass we can just pass in None to the backward function for torch.autograd.Function for corresponding non-Tensor outputs. This would ensure that the output of torch.autograd.Function.forward can be a Tensor or a generic Tuple.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by vedantroy** [comment]
Is it possible to define a custom autograd function that returns non-tensor outputs? I'm having trouble returning a work handle from an autograd function. Like this:

```
class AllGatherFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, tensor: torch.Tensor, reduce_dtype):
        ctx.reduce_dtype = reduce_dtype

        output_list = list(torch.empty_like(tensor) for _ in range(_CONTEXT_PARALLEL_GROUP_SIZE))
        handle = dist.all_gather(output_list, tensor, _CONTEXT_PARALLEL_GROUP, async_op=True)
        out = [*output_list, handle]
        return tuple(out)

    @staticmethod
    def backward(ctx, *grad_list):
        grad_list = list(grad_list)
        grad_dtype = grad_list[0].dtype 
        grad_input = torch.empty_like(grad_list[_CONTEXT_PARALLEL_RANK])
        dist.reduce_scatter(grad_input, grad_list, dist.ReduceOp.SUM, _CONTEXT_PARALLEL_GROUP)
        return grad_input.to(grad_dtype), None, None
```

gives the error:
```
TypeError: Invalid function argument. Expected parameter `input_list` of type List[torch.Tensor]
```

on the backward pass.
