### ISSUE TITLE
 TypeError: _export_onnx(): incompatible function arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by Ki6an** [pytorch/pytorch#52416]
## how to create dynamic axis dict for `torch.onnx.export()` input?  when the input has nested tensors.

I want to export an NLP model to onnx, the NLP model takes one of the inputs as shown below :

```
(
    (
        (8, 8, 30, 64),
        (8, 8, 30, 64),  
        (8, 8, 30, 64),  
        (8, 8, 30, 64),    
    )
              ...
    
    ( 
        (8, 8, 30, 64),
        (8, 8, 30, 64),  
        (8, 8, 30, 64),  
        (8, 8, 30, 64),  
    )

   # total 6 times 
)
```

input has a total of `6 tuples,` and each tuple contains `4 tensors` of shape `(8, 8, 30, 64).`
so the shape of the input looks like `6x4x(8, 8, 30, 64)`. # (a, b, c, d)

all parameters remain constant except for the first (a) and 3rd (c) elements of the tensor.

here is what I've tried,

```
                    # 6x4x(dict)
dyn_inputs = {  x : { y : {0:'batch',  2 : 'sequence'}  for y in range(4)  } for x in range(6) }
```
but I'm getting this error:
```
TypeError: _export_onnx(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Graph, initializers: Dict[str, at::Tensor], onnx_opset_version: int = 0, dynamic_axes: Dict[str, Dict[int, str]], defer_weight_export: bool = False, operator_export_type: torch._C._onnx.OperatorExportTypes = OperatorExportTypes.ONNX, strip_doc_string: bool = True, keep_initializers_as_inputs: bool = True, custom_opsets: Dict[str, int], add_node_names: bool = True, use_external_data_format: bool = False, onnx_file_path: str = '') -> Tuple[bytes, Dict[str, bytes]]
```
how do I make a dynamic axis for this input?

any help would be appreciated, 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by jbschlosser** [comment]
Hey @Ki6an! I think a question like this is a better fit for the [PyTorch forums](https://discuss.pytorch.org/).

**Comment by shubhambhokare1** [comment]
Hey @Ki6an, the input format for the dynamic_axes argument is either a 
1) dict<string, dict<python:int, string>> 
2) dict<string, list(int)>
The signature of your dynamic axes matches none of these

I would suggest, writing the input shape as (6, 4, a, b, c, d) and then using the dynamic axes functionality. It would look something like this
`input = torch.randn((6, 4, 8, 8, 30, 64), dtype = torch.float)

torch.onnx.export(model, (input, ), './test.onnx', do_constant_folding=True, 
                  input_names=['input1'], dynamic_axes={'input1':{2:'batch', 4:'sequence'}},
                  opset_version=12,  use_external_data_format=True, enable_onnx_checker=True)`

**Comment by Ki6an** [comment]
@shubhambhokare1 thank you for the response.
