### ISSUE TITLE
Result of  torch.Tensor.__mod__  is different from torch.fmod() function.

### ISSUE THREAD

**Issue by meremeev** [pytorch/pytorch#52425]
## 🐛 Bug

for arguments with different sign `torch.Tensor.__mod__` operation produce result different from `torch.fmod()` function.
## To Reproduce
Execute
```
print(torch.__version__)
x = torch.tensor([[5., 5.,  -5., -5.]])
y = torch.tensor([[3., -3., 3.,  -3.]])
print(x % y)
print(torch.fmod(x,y))
x %= y
print(x)
```
Result will be
```
1.6.0
tensor([[ 2., -1.,  1., -2.]])
tensor([[ 2.,  2., -2., -2.]])
tensor([[ 2., -1.,  1., -2.]])
```

## Expected behavior
Result actually depend of implementation of `floor_div` but I would expect both methods produce identical result.
And result should match `x - (x//y)*y` expression. 

## Environment
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 460.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.6.0
[pip3] torch2trt==0.1.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.7.0
[conda] Could not collect
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
cc @peterbell10 -- interested in this?

**Comment by zou3519** [comment]
FWIW, numpy has the same semantics as we do:
```
import numpy as np
x = np.array([5., 5. -5. , -5.])
y = np.array([3., -3., 3.,  -3.])

[ins] In [9]: x % y
Out[9]: array([ 2., -1.,  1., -2.])

[ins] In [10]: np.fmod
Out[10]: <ufunc 'fmod'>

[ins] In [11]: np.fmod(x, y)
Out[11]: array([ 2.,  2., -2., -2.])

[ins] In [12]: x % y
Out[12]: array([ 2., -1.,  1., -2.])

[ins] In [13]: x %= y; print(x)
```

**Comment by mruberry** [comment]
Thanks @zou3519. If we are consistent there may be a docs improvement we can make. Or maybe NumPy has an error?

**Comment by peterbell10** [comment]
`Tensor.__mod__` and `torch.remainder` both follow the Python convention which is the remainder of floor division. Whereas `torch.fmod` follow the C `math.h` convention of truncated division (rounding to zero).

So, this is the correct behaviour. In the docs it also conveys some difference. fmod says
>  The remainder has the same sign as the dividend input.

remainder says:
> The remainder has the same sign as the divisor other.

**Comment by mruberry** [comment]
Thanks @peterbell10! Sounds like this behavior is by design, @meremeev.

**Comment by meremeev** [comment]
Well, it is your call, but do you really think is it good design to have two different behavior  of `mod` operation? Even they are documented?

**Comment by mruberry** [comment]
> Well, it is your call, but do you really think is it good design to have two different behavior of `mod` operation? Even they are documented?

You're right it's a little confusing, but it wouldn't be good to be divergence from NumPy or C++, either, so we're kind of stuck in the middle.

**Comment by meremeev** [comment]
Mike, it sounds like you have two chairs and since you can not choose
which one to sit you have decided to sit in the middle. Sorry for this
joke.
I personally think since python is primary binding you should follow
the python/numpy convention. Or at least state it in documentation
absolutely explicitly: "for negative numbers result offmod() function
is different from % op." in big red font.

**Comment by peterbell10** [comment]
> personally think since python is primary binding you should follow the python/numpy convention.

PyTorch does follow the NumPy convention:

```python
>>> import torch
>>> x = torch.tensor([[5., 5.,  -5., -5.]])
>>> y = torch.tensor([[3., -3., 3.,  -3.]])

>>> x % y
tensor([[ 2., -1.,  1., -2.]])
>>> torch.fmod(x, y)
tensor([[ 2.,  2., -2., -2.]])
>>> torch.remainder(x, y)
tensor([[ 2., -1.,  1., -2.]])

>>> import numpy as np
>>> xn, yn = x.numpy(), y.numpy()
>>> xn % yn
array([[ 2., -1.,  1., -2.]], dtype=float32)
>>> np.fmod(xn, yn)
array([[ 2.,  2., -2., -2.]], dtype=float32)
>>> np.remainder(xn, yn)
array([[ 2., -1.,  1., -2.]], dtype=float32)
```

**Comment by meremeev** [comment]
Wow! I did not know that numpy has the same behaviour. No comments then.
