### ISSUE TITLE
[JIT] pytorch greater operation will introduce a cast to double node in onnx

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#52435]
Code to reproduce:

```python
class MG(nn.Module):

    def __init__(self):
        super().__init__()
        # for test if torch.cat([bool, bool]) can convert

    def forward(self, x):
        kernel_preds = torch.randn([8, 4, 3, 3])
        preds = F.conv2d(x, kernel_preds,
                             stride=1)
        preds = preds.to(torch.float)
        preds = preds.sigmoid()
        seg_masks = preds > 0.03
        return seg_masks


torch_model = MG()
x = torch.randn([1, 4, 24, 24])
torch_out = torch_model(x)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  x,
                  "a.onnx",
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,
                  verbose=True)
print('Done!')
```

This simple model, which contains a operation `preds > 0.03`,
the the exported onnx will be like:

```
graph(%0 : Float(1:2304, 4:576, 24:24, 24:1, requires_grad=0, device=cpu)):
  %1 : Float(8:36, 4:9, 3:3, 3:1, requires_grad=0, device=cpu) = onnx::RandomNormal[shape=[8, 4, 3, 3]]() # tests.py:145:0
  %2 : Float(1:3872, 8:484, 22:22, 22:1, requires_grad=0, device=cpu) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[1, 1]](%0, %1) # tests.py:147:0
  %3 : Float(1:3872, 8:484, 22:22, 22:1, requires_grad=0, device=cpu) = onnx::Cast[to=1](%2) # tests.py:148:0
  %4 : Float(1:3872, 8:484, 22:22, 22:1, requires_grad=0, device=cpu) = onnx::Sigmoid(%3) # tests.py:149:0
  %5 : Double(1:3872, 8:484, 22:22, 22:1, requires_grad=0, device=cpu) = onnx::Cast[to=11](%4)
  %6 : Double(requires_grad=0, device=cpu) = onnx::Constant[value={0.03}]()
  %7 : Bool(1:3872, 8:484, 22:22, 22:1, requires_grad=0, device=cpu) = onnx::Greater(%5, %6) # /usr/local/lib/python3.6/dist-packages/torch/tensor.py:27:0
  return (%7)

```

Which introduced double into model. Which is not good supported by TensorRT models.

Is this necessary? How to remove it at this moment (pytorch 1.7)?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by spandantiwari** [comment]
The cast nodes are typically inserted to faithfully emulate the semantics of PyTorch in the ONNX model. If you want to remove them, one option is to use ONNX Python APIs to modify the exported ONNX graph.

**Comment by jinfagang** [comment]
@spandantiwari  Hi. To be more specific describe my question:

This issue is not pytorch side problem, cast to double is OK, my issue is that if cast to double, the onnx model will not able to convert to TensorRT or any other framework. 

Interesting thing is that same model if using pytorch 1.6, it will not introduce cast op. Pls have a test with this single tiny model, you will not able to run `onnx2trt` or any other forward framework on this exported onnx model:


```python
class MG(nn.Module):

    def __init__(self):
        super().__init__()
        # for test if torch.cat([bool, bool]) can convert

    def forward(self, x, b):
        preds = F.conv2d(x, b,
                             stride=1)
        return preds


torch_model = MG()
x = torch.randn([1, 4, 24, 24])
b = torch.randn([8, 4, 3, 3])
torch_out = torch_model(x, b)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  (x, b),
                  "a.onnx",
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,
                  verbose=True)
print('Done!')
```

Anyway, I just want the model can converted to trt engine, is there a way to do this? (I tried downgrade to pytorch 1.6, it seems no problem, but I need pytorch 1.7 since this is just a huge project cropped part.)

Any solutions?

**Comment by jinfagang** [comment]
@ailzhang @spandantiwari @anshuljain1 Can u guys help me have a look this issue?

Currently my model unable to convert tensorrt due the introduce of Cast operation which I doubt if really necessary.

**Comment by gmagogsfm** [comment]
I tried dumping the TorchScript graph of the model in example, it doesn't contain a cast to double node. I guess it is added during lowering to ONNX.

Given @spandantiwari 's suggestion to use ONNX python API to remove the cast nodes, I will close this issue.
