### ISSUE TITLE
Can we define a tensor with actually 1bit?

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#52438]
The BoolType takes 8bits actually in current implementation.
Can we define a tensor with actually 1 bit in pytorch?

**Comment by jbschlosser** [comment]
Hey @densechen! 1-bit tensors are not currently supported in PyTorch. You can view the full list of supported dtypes [here](https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype).

**Comment by vadimkantorov** [comment]
Unfortunately, not yet :( I have a feature request about this at https://github.com/pytorch/pytorch/issues/32867, please upvote :)

But it seems there're some quantized 4-bit and maybe even 2-bit types

**Comment by densechen** [comment]
Thanks a lot! @vadimkantorov @jbschlosser
