### ISSUE TITLE
Problem exporting to onnx with registered buffer

### ISSUE THREAD

**Issue by dangraf** [pytorch/pytorch#52432]
## 🐛 Bug

Problem exporting to onnx, input output not on same device

## To Reproduce
I've boiled down the problem to this small code-example

    x = torch.rand([2, 3, 60, 80, 6]).to('cuda:0')
    ag = torch.tensor([[[[[[ 10.,  13.]]],
      [[[ 16.,  30.]]],
      [[[ 33.,  23.]]]]],
    [[[[[ 30.,  61.]]],
      [[[ 62.,  45.]]],
      [[[ 59., 119.]]]]],
    [[[[[116.,  90.]]],
      [[[156., 198.]]],
      [[[373., 326.]]]]]])

    class Test(nn.Module):

        def __init__(self, ancor):
            super().__init__()
            self.register_buffer('ancor',ancor)
    
        def forward(self, x):
            return x[...,2:4]*self.ancor[0]

this example is possible to run on the cuda device:

    model=Test(ag).to('cuda:0').eval()
    x = x.to('cuda:0')
    result = model(x)

but when I try to export it then it becomes a problem:

    fname = 'test.onnx'
    torch.onnx.export(model, x, fname, verbose=False, opset_version=12)

part of the error message:
/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, example_outputs, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, use_new_jit_passes, dynamic_axes)
448 if do_constant_folding and _export_onnx_opset_version in torch.onnx.constant_folding_opset_versions:
449 params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
→ 450 _export_onnx_opset_version)
451 torch._C._jit_pass_dce_allow_deleting_nodes_with_side_effects(graph)
452

RuntimeError: Input, output and indices must be on the current device

## Expected behavior
I expect the onnx to succeed with the export since both the model and the input are located on the cuda 0

## Environment
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.0
[pip3] torch2trt==0.1.0
[pip3] torchvision==0.8.1
[pip3] trtorch==0.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] torch                     1.7.0                    pypi_0    pypi
[conda] torch2trt                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.8.1                    pypi_0    pypi
[conda] trtorch                   0.1.0                    pypi_0    pypi

## Additional context

I’m working with yolov5 and trying to export it to onnx but so far without any success.
So I have tried to narrow down the problem into a small code example to illustrate the problem.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by lyf35** [comment]
I have encountered with the same problem. Do you know how to solve it now?

**Comment by lyf35** [comment]
The problem is mainly because that the variable `x` and `ag` in the code are not on the same device. I just modified your code and it will run successfully on my computer:

```
import torch
import torch.nn as nn

x = torch.rand([2, 3, 60, 80, 6]).to('cuda:0')
ag = torch.tensor([[[[[[ 10.,  13.]]],
  [[[ 16.,  30.]]],
  [[[ 33.,  23.]]]]],
[[[[[ 30.,  61.]]],
  [[[ 62.,  45.]]],
  [[[ 59., 119.]]]]],
[[[[[116.,  90.]]],
  [[[156., 198.]]],
  [[[373., 326.]]]]]])

class Test(nn.Module):

    def __init__(self, anchor):
        super().__init__()
        self.anchor=anchor.to('cuda:0')

    def forward(self, x):
        return x[...,2:4]*self.anchor[0]

model=Test(ag).to('cuda:0').eval()
x = x.to('cuda:0')
result = model(x)

fname = 'test.onnx'
torch.onnx.export(model, x, fname, verbose=False, opset_version=12)
```

BTW, I have modified the function `register_buffer`, since I can not figure out the mechanism inside this function.

**Comment by dangraf** [comment]
Hello!
That might be a walk around but not the solution to the problem. The "Register buffer" is supposed to move the variable to the selected device for the module but skips the calculations of the gradient. It is also saved in the "state dict" when waving and loading the module. (https://discuss.pytorch.org/t/what-is-the-difference-between-register-buffer-and-register-parameter-of-nn-module/32723)

**Comment by cosminginerica** [comment]
Hi @dangraf !
Were you able to resolve your issue with yolo? I am running at the moment into the same problem.
Thanks

**Comment by BowenBao** [comment]
Thanks for reporting, will take a look.

**Comment by yinghuang** [comment]
for yolov5-half-gpu-onnx export,  check [https://github.com/ultralytics/yolov5/issues/3631#issuecomment-905368078](this)

**Comment by yinghuang** [comment]
for yolov5-half-gpu-onnx export, check [this](https://github.com/ultralytics/yolov5/issues/3631#issuecomment-905368078)
