### ISSUE TITLE
Incorrect .ONNX representation for models that contains integer constants.

### ISSUE THREAD

**Issue by bes-dev** [pytorch/pytorch#52436]
When we try to export the PyTorch model to the ONNX graph, by default, PyTorch adds Cast (to Int64) node for expressions that contain integer variables to Int64. It leads to provide errors when we try to compute this graph by external inference engines.

Reproducer:
1. Incorrect behavior

PyTorch code:

```
import torch
import torch.nn as nn

class Model(nn.Module):
    def forward(self, x):
        return torch.pow(2, x)

torch.onnx.export(
    Model(),
    (torch.randn(1, 10),),
    "model.onnx",
    input_names=["x"],
    output_names=["y"],
    verbose=True
)
```
We checked this behavior using some external engines:
* Onnxruntime cannot inference this graph, it leads to error:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from incorrect.onnx failed:Type Error: Type (tensor(float)) of output arg (y) of node (Cast_1) does not match expected type (tensor(int64)).--  
* OpenVINO provides incorrect results because it inference ONNX. We can evaluate the regression between PyTorch code and ONNX graph:
```
var: [[ 0.2656286  -0.8841479  -0.6453945   1.0554838   0.28973514  0.5940263   2.9461455   1.3277359  -0.68979824 -0.3859768 ]]
pytorch output: [[1.2021598 0.5418075 0.6393179 2.0784152 1.2224158 1.5094535 7.7068725  2.5100844 0.6199405 0.7652607]]
openvino output: [[1 0 0 2 1 1 7 2 0 0]]
diff_mean: 0.47957277297973633, diff_max: 0.7652606964111328
```

2. Correct behavior
PyTorch code:
```
import torch
import torch.nn as nn

class Model(nn.Module):
 def forward(self, x):
 return torch.pow(float(2), x)

torch.onnx.export( Model(), (torch.randn(1, 10),), "model.onnx", input_names=["x"], output_names=["y"], verbose=True )
```

We can evaluate the regression between PyTorch code and ONNX model:
```
var: [[ 1.2511508  -0.02980541 -0.01735055 -0.51932913  0.01449305  0.53635216  -0.31943512 -0.16622886 -0.12281971  0.7664761 ]]
pytorch output: [[2.3803122  0.9795524  0.9880455  0.6976962  1.0100964  1.4503008  0.8013836  0.89116913 0.9183909  1.7011096 ]]
openvino output: [[2.3803122  0.9795524  0.9880455  0.6976962  1.0100964  1.4503008  0.8013836  0.89116913 0.9183909  1.7011096 ]]
diff_mean: 0.0, diff_max: 0.0
```
We get same results when we use onnxruntime for this graph.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by spandantiwari** [comment]
Which version of PyTorch are you using? Could you try with latest nightly version and check if this issue exists?

**Comment by bes-dev** [comment]
@spandantiwari I checked it with the latest nightly version of PyTorch and with stable release, and this issue exists with both versions.

**Comment by spandantiwari** [comment]
OK, we can take a look.

**Comment by jiafatom** [comment]
In current pytorch exporter, the output type of Pow is equal to the inputs X. In this example, 2 is an int64, so the output is int64. 
We will work on this. The current work around can be
(1) Change 2 to 2.0
or
(2) Which opset do you use? Can you try opset 12+? (the onnx Pow schema changes to have input X and Y have different types)
