### ISSUE TITLE
[NNC] NNC usability list

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#52434]
I've been going through http://tvm.d2l.ai/, just to learn more about writing schedules and TVM/Halide-like compilers. I'm also curious about how to improve NNC's user experience, and we can probably learn a lot from TVM :) All of this is done with the Python API, but I've tried to check to make sure that it's not a limitation with the pybind bindings. See my examples here: https://github.com/Chillee/pytorch/tree/d2l/d2l

These examples might also be useful for people interested in learning more about writing NNC schedules.

# General "Constructor" improvements
- Constructing a placeholder with input shapes is too hard. We should be able to just pass in a static shape. Currently, let's say you're trying to make a to make a `Placeholder` with the standard float32 and an input shape `(3,4)`. You need to write
```
te.Placeholder(name, te.Dtype.Float, [te.DimArg(te.ExprHandle.int(3), dim1_name), te.DimArg(te.ExprHandle.int(4), dim2_name))
```
A couple things. 
1. ~~Names should be optional. Many times when I'm writing something simple I don't care about the names.~~ (Fixed in  #60058)
2. Dtype should probably also default to float32 (like Pytorch does).
2. ~~There should be some kind of automatic casting from standard "Python" types to NNC.~~ (Fixed in #60058)
3. Partly because of the names, it's very difficult to just pass a shape to the Placeholder.

In TVM, making a simple Placeholder is just `te.placeholder((3, 4))`. I used this utility function to approximate it: https://github.com/Chillee/pytorch/blob/d2l/d2l/utils.py#L48. If Python is the "user-facing" API then perhaps this can just live in Python.

- ~~Somewhat similar to above, why do we need to wrap all inputs in `te.BufferArg` when calling `te.construct_codegen`? Can't this be done automatically?~~ (Fixed in  #59920)

# Automatic utility things that TVM does
- In general, TVM provides a lot of utility on top of the `te.Tensor` object. They allow you to use the `te.Tensor` object to access shapes, to access dtypes, to access axes, etc. For example, in TVM, you can do this:
```
A = te.placeholder((3, 4))
B = te.placeholder(A.shape)
```
This is particularly helpful when dealing with dynamic shapes. Instead of needing to thread the original `te.VarHandle` along with the `Tensor` objects being passed.

- When we use `Compute` to call a lambda, why do we need to do `A.load([i,j])`? Can't this just be overloaded to `A[i,j]`?
- Similarly, why do we need to wrap any concrete values in `te.Exprhandle`? Can we do this conversion implicitly?
- For `codegen.call(...)`, we never check that our input/output shapes have the correct shape nor dtype. This has burned me many times.
- For dynamic shapes, TVM seems to do some automatic inference about their values based off of the input tensors. For example, look at this dynamic transpose: https://github.com/Chillee/pytorch/blob/d2l/d2l/2_3.py#L13 Specifically, see how when we create our `codegen` object we need to pass in `n` and `m` as well `te_codegen('llvm', s.root_stmt(), [A, B, n, m])`. TVM will do some kind of automatic inference to elide this requirement. I'm not entirely sure how they determine when they don't need to pass it in, but it's much nicer: http://tvm.d2l.ai/chapter_expressions/index_shape_expressions.html#matrix-transpose
- Adding a `te.any` or a `te.all`. In order to express `and`/`or` in things like `te.ifThenElse`, we currently use `&` and `|`, which are bitwise-and/or. They work fine, but their precedence makes writing expressions like these (https://github.com/Chillee/pytorch/blob/d2l/d2l/2_56.py#L23) more painful than they need to be. TVM has `te.any` and `te.all` that presumably does this automatically.

# Scheduling/Performance improvements
- Our call overhead currently seems to be somewhere around `0.9` microseconds. I'm not sure if this is entirely fair to us, but for comparison, Numpy as 0.5 microsecond overhead, PyTorch has 1.2 microseconds, and TVM has 0.2 microseconds. This should ideally be improved.
- It sure would be nice to have a `parallel` transform :)
- I'm not sure I entirely like the way our current transforms are set up compared to TVM. Having all of our transformations be  stateful seems to result in things like needing to call `s.get_loops_for(C)` constantly.
- This may be lack of understanding of what `ramp` is, but when should I be splitting and then using `ramp`, and when should I just be using `ramp` directly?
- TVM allows referring to loop axes by referring to attributes of tensors. In contrast, we need to first do `loopnest.get_loops_for(Tensor)`.
- I'd like a `tile` higher-level transform really badly haha
- We don't seem to have an equivalent for `cache_write`?

# Reduction usability
- I haven't wrapped my head around how NNC's reduction API differs from TVM's, but they seem different in a meaningful way. I'm not sure which one is better.

cc @gmagogsfm

**Comment by bertmaher** [comment]
Ooh I love this list.  Specifically for reductions I have a draft PR (which I am trying to clean up to actually land) that makes NNCs reduction API more usable (and more like TVM). https://github.com/pytorch/pytorch/pull/52121 Is the prototype, with ReduceX looking like how I want Reduce to behave

**Comment by jbschlosser** [comment]
Labeled this with the JIT oncall but feel free to relabel if it doesn't fit.

**Comment by bertmaher** [comment]
I poked at the python API for the first time today and I think I basically reproduced this list of complaints.  For posterity, I wrote up a simple FMA type function:

In NNC:
```
import torch
import torch._C._te as te

# FIXME: KernelScope is a weird thing that shouldn't be user visible.                                                                                                        
scope = te.KernelScope()

M, N = 64, 256
# FIXME: Shouldn't need to explicitly create ExprHandles from ints                                                                                                           
Mx, Nx = [te.ExprHandle.int(x) for x in (M, N)]

# FIXME: Names should be optional.                                                                                                                                           
# FIXME: Dtypes are too verbose, and could we use torch.dtype?                                                                                                               
a = te.Placeholder("a", te.Dtype.Float, (Mx, Nx))
b = te.Placeholder("b", te.Dtype.Float, [Mx, Nx])
c = te.Placeholder("c", te.Dtype.Float, [Mx, Nx])

# FIXME: Name should be optional.                                                                                                                                            
# FIXME: Shouldn't need to construct DimArgs.  TVM miraculously gets the                                                                                                     
# variable names from the python lambda :-o                                                                                                                                  
# FIXME: Would be better to use [] or () than load, or at least make it var                                                                                                  
# args?                                                                                                                                                                      
d = te.Compute("d", [te.DimArg(Mx, "m"), te.DimArg(Nx, "n")],
               lambda m, n: a.load([m, n]) * b.load([m, n]) + c.load([m, n]))

# FIXME: prepare_for_codegen should probably be implicit                                                                                                                     
# FIXME: simplify should probably be implicit                                                                                                                                
# FIXME: explicitly creating BufferArgs shouldn't be needed                                                                                                                  
nest = te.LoopNest([d])
nest.prepare_for_codegen()
stmt = te.simplify(nest.root_stmt())
cg = te.construct_codegen("llvm", stmt, [te.BufferArg(x) for x in (a, b, c, d)])

at, bt, ct = [torch.randn(M, N) for _ in range(3)]
dt = torch.empty(M, N)
cg.call([at, bt, ct, dt])
torch.testing.assert_allclose(dt, at * bt + ct)
```

In TVM:
```
import tvm
from tvm import te

m, n = 64, 256

a = te.placeholder((m, n))
b = te.placeholder((m, n), name="b")
c = te.placeholder((m, n), name="c")

d = te.compute((m, n), lambda i, n: a[i, n] * b[i, n] + c[i, n], name="d")

s = te.create_schedule(d.op)
fma = tvm.build(s, [a, b, c, d], "llvm -mcpu=skylake-avx512", name="fma")

at, bt, ct = [torch.randn(M, N) for _ in range(3)]
dt = torch.empty(M, N)
fma(*[tvm.nd.from_dlpack(torch.utils.dlpack.to_dlpack(t)) for t in (at, bt, ct, dt)])
torch.testing.assert_allclose(dt, at * bt + ct)
```

**Comment by jansel** [comment]
#59920 and #60058 fix a few of these issues.
