### ISSUE TITLE
Windows libtorch nightly builds for CUDA 11.1 failing binary smoke tests with unresolved symbols

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#52468]
## To Reproduce

After the addition of CUDA 11.1 to our nightly build matrix we've observed some failures when attempting to test libtorch builds on windows:

```
torch_cuda.lib 
   Creating library check-torch-cuda.lib and object check-torch-cuda.exp
LINK : error LNK2001: unresolved external symbol "int __cdecl at::cuda::warp_size(void)" (?warp_size@cuda@at@@YAHXZ)
check-torch-cuda.exe : fatal error LNK1120: 1 unresolved externals
'.\check-torch-cuda.exe' is not recognized as an internal or external command,
```

[CircleCI logs](https://app.circleci.com/pipelines/github/pytorch/pytorch/274955/workflows/a33e017e-0508-4367-b2b1-88704fd8525f/jobs/10983300)

cc @malfet @seemethere @walterddr @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
cc @janeyx99

**Comment by mszhanyi** [comment]
@janeyx99 
why ?warp_size@cuda@at@@YAHXZ is in torch_cuda_cpp.dll, not in torch_cuda_cu.dll?

**Comment by peterjc123** [comment]
https://github.com/pytorch/builder/pull/661 should fix this.
