### ISSUE TITLE
Torchscript tutorial example is broken

### ISSUE THREAD

**Issue by indigoviolet** [pytorch/pytorch#52480]
## 📚 Documentation

https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html#using-scripting-to-convert-modules

The example is trying to motivate why scripting is needed, by demonstrating a missing conditional in tracing, but the actual output code is identical between the tracing and scripting cases -- perhaps we need to show the output of compiling `MyDecisionGate` instead of `MyCell`?

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
Already fixed, waiting for review: https://github.com/pytorch/tutorials/pull/866
