### ISSUE TITLE
OpInfo to support `sample_inputs_func` with just an Iterable output.

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#52486]
## 🚀 Feature
It would make things easier and more transparent/modular if OpInfo could support samplers which comply with the Iterable protocol.

## Motivation & Pitch

OpInfo does support a parameter `sample_inputs_func` which generates inputs for test cases. However, the `len` function is applied to the output of this function meaning that whichever output `sample_inputs_func` returns, it has to comply with the Sequence protocol. This comes with certain limitations:

* Encourages writing a one long sampler with either a huge tuple, or with appending to a list which does not look elegant, nor splits testing into independent parts.
* Does not allow mixing in generators or arbitrary iterables for that matter. That is a matter of taste, but using `yield ...` instead of `my_list.append(...)` seems to look better.
* If we are to split a sampler into subsamplers, we have to make sure that they all generate the SAME sequence such that we could concatenate it like, for example,
```python
def sampler_for_op(*args, **kwargs):
    return sampler1(*args, **kwargs) + sampler2(*args, **kwargs) + ...
    
    ...
    sample_inputs_func = sampler_for_op,
    ...
```
Or we could hack different type Sequences by using unpacking, but still it does not work with generators, unless converted to Sequences:
```python
def sampler_for_op(*args, **kwargs):
    return [*sampler1(*args, **kwargs), *sampler2(*args, **kwargs), ..., *list(generator_sampler(*args, **kwargs))]
```
If `sample_inputs_func` were Iterable, we could have simply chained arbitrary Iterable samplers like
```python
def sampler_for_op(*args, **kwargs):
    yield from sampler1(*args, **kwargs)
    yield from sampler2(*args, **kwargs)
    ...

    ...
    sample_inputs_func = sampler_for_op,
    ...
```
Not only does it make adding new samplers easier and more memory efficient, this way we could reuse same samplers for different operations by adding them to different chains.

Adding support for this feature should not break the existing code since Sequences are Iterable.

CC @mruberry 

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
Sounds like a great idea! We would accept a PR updating OpInfos like this.
