### ISSUE TITLE
UnicodeDecodeError when parse kineto_event.name() for cuda112

### ISSUE THREAD

**Issue by guyang3532** [pytorch/pytorch#52504]
## 🐛 Bug

Code https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py#L1139 will report 'UnicodeDecodeError' when using cuda11.2 for our profiling test.
The error message is:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 1: invalid start byte

(This error doesn't happen when using cuda11.0)

## To Reproduce

Test code is at : https://github.com/pytorch/kineto/blob/tb_plugin/tb_plugin/examples/resnet50_profiler_api.py
Just run it directly.

## Environment

 - PyTorch Version: v1.8.0-rc2
 - OS : Linux
 - How you installed PyTorch: pip install -f https://download.pytorch.org/whl/test/cu112/torch_test.html torch
 - Python version: 3.7.9
 - CUDA/cuDNN version: cuda11.2

@ilia-cher @gdankel @ngimel 

cc @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @ezyang

**Comment by malfet** [comment]
cc: @ilia-cher

**Comment by guyang3532** [comment]
cc @ilia-cher

**Comment by ilia-cher** [comment]
I think this should be fixed by now

**Comment by xycforgithub** [comment]
I am having the same problem - is this fixed in pytorch 1.8.1?

**Comment by ilia-cher** [comment]
> I am having the same problem - is this fixed in pytorch 1.8.1?

please try 1.8.1, I believe the underlying bug was fixed, if you still have it it might be something else, then please share the small repro. example and use env. collection script
