### ISSUE TITLE
F::interpolate get wrong result using libtorch

### ISSUE THREAD

**Issue by FeatherZhong** [pytorch/pytorch#52502]
## 🐛 Bug

libtorch 1.7.1 `F::interpolate` get wrong result and different with pytorch 1.7.1.
I want to use interpolate to resize the image feature to (512,512).
This is the original image
![test](https://user-images.githubusercontent.com/30190190/108497794-f72e8e00-72e6-11eb-9982-ed2d97596843.jpg)
This is the image what I want, generated by pytorch 1.7.1
![correct](https://user-images.githubusercontent.com/30190190/108499236-f5fe6080-72e8-11eb-8fe2-aa66de9884ba.jpg)
This is the image generated by libtorch 1.7.1
![wrong](https://user-images.githubusercontent.com/30190190/108498521-f64a2c00-72e7-11eb-90fd-19081e97938a.jpg)
The wrong result seems to split the channels and merge them into a single image.
The size of `F::interpolate` input feature is (1,3,349,500), and the output feature is (1,3,512,512), the size is correct.

**Strangely enough, when I use Libtorch 1.4.0 with the same code,I could get the right results.It seems that this bug only appears in versions 1.4.0 and above.**

## To Reproduce
This is my libtorch code
```
cv::Mat image = cv::imread("/home/lll/Pictures/test.jpg");


torch::Tensor image_tensor = torch::from_blob(image.data, {image.rows, image.cols, 3}, torch::kByte);

image_tensor = image_tensor.permute({2, 0, 1}).toType(torch::kFloat).div_(255);
image_tensor.sub_(0.5).div_(0.5);
image_tensor = image_tensor.unsqueeze(0);
image_tensor = image_tensor.to(torch::kCUDA);

namespace F = torch::nn::functional;
image_tensor = F::interpolate(
        image_tensor,
        F::InterpolateFuncOptions()
                .mode(torch::kBilinear)
                .size(std::vector<int64_t>({512, 512}))
                .align_corners(true)
);
image_tensor = image_tensor.mul(0.5).add(0.5).mul(255);
image_tensor = image_tensor.squeeze(0).permute({1, 2, 0}).toType(torch::kByte).to(torch::kCPU);

cv::Mat test_mat(512, 512, CV_8UC3);
std::memcpy((void *) test_mat.data, image_tensor.data_ptr(), sizeof(torch::kU8) * image_tensor.numel());
cv::imshow("test", test_mat);
cv::waitKey(0);
```
This is my pytorch code
```
_transforms = transforms.Compose([
transforms.Normalize((0.5, 0.5, 0.5), (128 / 255., 128 / 255., 128 / 255.))])
image = cv2.imread("/home/lll/Pictures/test.jpg")

image = torch.from_numpy(image)
image = image.permute(2, 0, 1)
image = image.unsqueeze(0)
image = image.float()

image = _transforms(image)

image = F.interpolate(image, size=(512, 512), mode='bilinear', align_corners=True)
image = image.squeeze(0).permute(1, 2, 0)

image = image * 0.5 + 0.5
image = image.byte()
cv2.imshow("test", image.numpy())
cv2.waitKey(0)
```

## Expected behavior
libtorch result and pytorch result should be the same.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0-4ubuntu1 
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.7.2                      py37    pytorch
[conda] torchvision               0.8.2                py37_cu102    pytorch

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @yf225 @glaringlee

**Comment by glaringlee** [comment]
@FeatherZhong 
Can you try doing interpolation on CPU under libtorch see whether you get the same result?

**Comment by FeatherZhong** [comment]
> @FeatherZhong
> Can you try doing interpolation on CPU under libtorch see whether you get the same result?

Sure, I tried running it on CPU and got the same result.

**Comment by ngimel** [comment]
Can you try `image_tensor = image_tensor.contiguous()` before declaring test_mat in your example?

**Comment by FeatherZhong** [comment]
> Can you try `image_tensor = image_tensor.contiguous()` before declaring test_mat in your example?

Amazing! This code solves this problem, Thx!
