### ISSUE TITLE
AMP + CUDA + tensor.sum op leads to dtype mismatch

### ISSUE THREAD

**Issue by rouniuyizu** [pytorch/pytorch#52501]
## 🐛 Bug

When combining amp with cuda, tensor sum causes type mismatch.

## To Reproduce

Run following code:

```
import torch
from torch.cuda.amp import autocast

if __name__ == "__main__":
    with autocast():
        a = torch.randn(3,4,5).to(torch.float16)
        print(f"a's type: {a.dtype}")
        b = a.sum(dim=-2)
        print(f"b's type: {b.dtype}")


        print("on cuda now:")
        c = torch.randn(3, 4, 5).to(torch.float16).to("cuda")
        print(f"c's type: {c.dtype}")
        d = c.sum(dim=-2)
        print(f"d's type: {d.dtype}")

```

Output:
a's type: torch.float16
b's type: torch.float16
on cuda now:
c's type: torch.float16
d's type: torch.float32
## Expected behavior

a's type: torch.float16
b's type: torch.float16
on cuda now:
c's type: torch.float16
d's type: torch.float**16**

## Environment
Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce RTX 3090

Nvidia driver version: 460.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu110    pytorch

cc @mcarilli @ptrblck @ngimel @nairbv @mruberry

**Comment by ptrblck** [comment]
I don't think the output `dtype` is a type mismatch and based on the [`float32` cast list](https://pytorch.org/docs/stable/amp.html#ops-that-can-autocast-to-float32) is the expected result, no?

**Comment by rouniuyizu** [comment]
Thank you.

I'll close it since it's by design, though I haven't fully grasped the rational behind why we want to auto cast it for this particular op.

**Comment by ngimel** [comment]
We want to autocast for `.sum` operation because otherwise it is easy for sum to overflow.
