### ISSUE TITLE
torch.cuda.comm.scatter crashes(segfault)

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#52526]
## 🐛 Bug

`torch.cuda.comm.scatter` crashes (segfault) when `streams` is empty string.

## To Reproduce

~~~python
import torch
torch.cuda.comm.scatter(tensor=torch.tensor([1]), devices=[1], streams='')
~~~

Output in v1.5.0
~~~python
Segmentation fault (core dumped)
~~~

Output in nightly version `1.9.0.dev20210219+cpu`
~~~python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.cuda' has no attribute 'comm'
~~~

## Expected behavior

expect a graceful exception message instead of crash.

## Environment

PyTorch version: 1.8.0.dev20210126+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by gchanan** [comment]
it doesn't crash anymore, I'm removing the crash module.

**Comment by gchanan** [comment]
After 1.7 we know longer implicitly import torch.cuda.comm, so to reproduce now you have to do:

```
import torch
import torch.cuda.comm
torch.cuda.comm.scatter(tensor=torch.tensor([1]), devices=[1], streams='')
```

**Comment by malfet** [comment]
Looks like simple null pointer deref. Grabbing for myself.
