### ISSUE TITLE
Tweak heuristics for when to select cudnn depthwise convolution

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5252]
See https://discuss.pytorch.org/t/depthwise-convolution/12345

Maybe @ngimel has some opinions about what test we should apply here.

**Comment by apaszke** [comment]
The link gives me an error saying that this thread doesn't exist

**Comment by ezyang** [comment]
Oops, I guess it's a private discuss. Relevant part:

```
if (is_depthwise):
  ...
else if (use_cudnn):
  ...
else:
  ...
```

> This means that every depthwise convolution takes the first branch. However, CuDNN 7 introduced support for efficient grouped/depthwise convolution, and we would like to use that when it’s better - there’s even special code for it in the use_cudnn branch. On my system, CuDNN 7 is about 2x faster than the current path when input_channels == output_channels, but about 3x slower otherwise.
