### ISSUE TITLE
Possible bug in initializing nn.MultiheadAttention if bias=False

### ISSUE THREAD

**Issue by danpovey** [pytorch/pytorch#52545]
In this line:
https://github.com/pytorch/pytorch/blob/bb34fd6191e0f2a31edc38e00d93a24d9da8c031/torch/nn/modules/activation.py#L913
it only sets the out_proj.bias to zero if bias=True; but the bias=True setting only affects the in_proj.bias; the out_proj.bias 
exists anyway.   So it's getting initialized in the default way for Linear, which is nonzero; this doesn't look like what the code is intended to do.  I'm not sure if this would make any difference for any models in use; I can't find an instance in the PyTorch codebase where bias=False is being used for MultiheadAttention.

IMO the easiest fix would probably be to un-indent the line that sets out_proj.bias, which would make more sense and likely won't affect anyone's experiments since bias=False doesn't seem to be used.  Or maybe leave it as-is and put a comment saying this is unintended but we'll leave it as is for back-compatibility.

cc @zhangguanheng66

**Comment by zhangguanheng66** [comment]
A relevant ongoing PR https://github.com/pytorch/pytorch/pull/52537

**Comment by jbschlosser** [comment]
The referenced PR #52537 causes `bias=True` to affect `out_proj.bias` as well. Now the initialization in `_reset_parameters()` should be correct, albeit a bit weird to read.

It could be clearer:
```python
if self.out_proj.bias is not None:
    constant_(self.out_proj.bias, 0.) 
```

**Comment by danpovey** [comment]
Ah OK, in the light of that I think it's OK, will close the issue.
