### ISSUE TITLE
The RandomSampler is not be set as expected.

### ISSUE THREAD

**Issue by lartpang** [pytorch/pytorch#52568]
## To Reproduce

The key code:

https://github.com/pytorch/pytorch/blob/a935118c90db94879b41d6dc359520e99e6cdca2/torch/utils/data/sampler.py#L112-L124

Here, the random initialization of the var `generator` will affect the random state of the `torch.randperm` if `self.replacement` is False and `self.generator` is None. The reason is that the method `.random_()` in `generator.manual_seed(int(torch.empty((), dtype=torch.int64).random_().item()))` has changed the random state.

Demo:

```python
torch.manual_seed(0)
generator = torch.Generator()
seed = int(torch.empty((), dtype=torch.int64).random_().item())
# seed = 0
generator.manual_seed(seed)
print(torch.randperm(10, generator=None).tolist())
#[3, 7, 5, 2, 0, 8, 1, 6, 9, 4]
```

```python
torch.manual_seed(0)
generator = torch.Generator()
# seed = int(torch.empty((), dtype=torch.int64).random_().item())
seed = 0
generator.manual_seed(seed)
print(torch.randperm(10, generator=None).tolist())
#[4, 1, 7, 5, 3, 9, 0, 8, 6, 2]
```

## Expected behavior

Although both strategies achieve the effect of fixed seed, they are not consistent with the actual expectations.

## Additional context

Thanks!

cc @SsnL @VitalyFedyunin @ejguan @pbelevich

**Comment by ejguan** [comment]
For the branch of false `self.replacement`, we should use `generator` rather than `self.generator`.
We would like to accept a PR to fix the bug.

**Comment by lartpang** [comment]
Thanks for your reply. Your reply is exactly what I am confused about. :smile_cat: 

I have fixed it in this PR: https://github.com/pytorch/pytorch/pull/52956.
