### ISSUE TITLE
pip installs rocm version instead of cuda version when specifying version string with >= instead of ==

### ISSUE THREAD

**Issue by benjs** [pytorch/pytorch#52571]
## 🐛 Bug

pip installs rocm version instead of cuda version when specifying version string with >= instead of ==

## To Reproduce

```
python3 -m venv venv
source venv/bin/activate
pip install torch>=1.7.1+cu110 torchvision>=0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html
pip list
```
Output:
```
torch                         1.7.1+rocm3.8
torchvision                   0.8.2+cu92
```
## Expected behavior

Output:
```
torch                         1.7.1+cu110
torchvision                   0.8.2+cu110
```

## Environment

- Ubuntu 20.04
- `pip -V`: `pip 21.0.1`
- `python -V`: `Python 3.9.1`

**Comment by peterjc123** [comment]
Please try the following commands instead. `pip install torch>=1.7.1 torchvision>=0.8.2 -f https://download.pytorch.org/whl/cu110/torch_stable.html`.

**Comment by benjs** [comment]
That worked! Thanks.
