### ISSUE TITLE
Add `non_blocking` key to Tensor.cpu() method.

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#52586]
## 🚀 Feature
The Tensor `.to` and `.cuda` methods both have `non_blocking` options for asynchronous data transfer.

## Motivation

To the best of my understanding, GPU to CPU transfer can be performed asynchronously on PyTorch.

I would therefore like to request the `non_blocking` option to be added to the `.cpu` method as well.

## Pitch

The Tensor class should have a `non_blocking` option in its `.cpu` method. Setting `non_blocking=true` will lead to asynchronous GPU to CPU data transfer if this is possible.

## Alternatives

Continue to use `.to('cpu', non_blocking=True)`. However, this is verbose.

## Additional context

It seems odd that only the `.cuda` method has `non_bloking=True` while the `.cpu` option does not when asynchronous data transfer is possible for both directions in PyTorch.

cc @VitalyFedyunin @gchanan @mruberry

**Comment by vadimkantorov** [comment]
Then probably a mechanism is needed for waiting on the CPU tensor availability upon copy completion?

**Comment by veritas9872** [comment]
@vadimkantorov Thank you for the explanation. The issue is more involved than what I first believed.

**Comment by vadimkantorov** [comment]
@veritas9872 maybe keep the issue opened? so that someone expert could advise better. maybe this enchancement makes sense!

**Comment by ArtHang** [comment]
@vadimkantorov  May by we can try to implement a mechanism internally: wait when getting a value
