### ISSUE TITLE
CMake 3.16.0 error of `Unknown arguments`

### ISSUE THREAD

**Issue by JiabinYang** [pytorch/pytorch#52594]
## 🐛 Bug

When I try to build pytorch on MacOS with cmake of version 3.16.0, i meet a problem of `Unknown arguments`
![image](https://user-images.githubusercontent.com/22361972/108683509-a7d99f00-752c-11eb-8881-812a24423fc7.png)

## To Reproduce

This build did without using conda since i try to do some develop on it, and i use CLion as my ide, and i try to make clion's code inteligence work.

So, i directly build it using clion's default cmake process with command `-DPY_VERSION=3.9
-DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR}
-DPYTHON_LIBRARY=${PYTHON_LIBRARY}
-DCMAKE_BUILD_TYPE=DebugWithRelInfo
-DPYTHON_EXECUTABLE=/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/bin/python3.9`

## Expected behavior

Correctly finish the cmake process
 
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

When i change code to this it can work and i noticed that some similar code is doing the same way i did
![image](https://user-images.githubusercontent.com/22361972/108684008-48c85a00-752d-11eb-8a20-863e7936c587.png)

cc @malfet @seemethere @walterddr

**Comment by JiabinYang** [comment]
sorry, change to `"3"` doesn't make sense i just hard code it as 
![image](https://user-images.githubusercontent.com/22361972/108684265-a78dd380-752d-11eb-8002-aee465fbd02d.png)
but it still a bug for other users

**Comment by walterddr** [comment]
could you share your environment?
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

according to [document](https://cmake.org/cmake/help/v3.16/command/if.html) there's no need to convert the version integer into string.

**Comment by skyline75489** [comment]
CLion might be using its own version of cmake. Could you also check the actual cmake version being used?

**Comment by JiabinYang** [comment]
> CLion might be using its own version of cmake. Could you also check the actual cmake version being used?

i set it as cmake 3.16

**Comment by JiabinYang** [comment]
> could you share your environment?
> Please copy and paste the output from our
> [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
> 
> according to [document](https://cmake.org/cmake/help/v3.16/command/if.html) there's no need to convert the version integer into string.

ok, And i met another problem of 
![image](https://user-images.githubusercontent.com/22361972/108827652-d4f78180-7600-11eb-9fec-125b02faf605.png)
I already set C_INCLUDE_PATH as where Python.h at

**Comment by JiabinYang** [comment]
> If you're trying to build `libtorch`, the recommend way it to use `tools/build_libtorch.py`. Using cmake directly (or through tools like CLion) can be painful since PyTorch is a very large project.

i try to do some custom develop based on pytorch so build it with clion maybe better for me to do some code develop, however, it maybe not the problem of torch

Thx a lot

**Comment by skyline75489** [comment]
The best way to build PyTorch yourself is to follow the [instructions here](https://github.com/pytorch/pytorch#from-source). Sorry you cannot just use cmake to build the project, because PyTorch is a very complicated & large project which uses both C++ & Python, and has a lot of dependencies.

If you still have problems after following the instructions, feel free to open other issues. This issue seems invalid to me and should be closed.

**Comment by JiabinYang** [comment]
![image](https://user-images.githubusercontent.com/22361972/110326996-55cc6980-8054-11eb-95e6-95606ac2f675.png)
when i follow the doc to build pytorch from source on my ubuntu docker container i met this. plz help me with that thx

**Comment by skyline75489** [comment]
Please search for the log that actually shows what went wrong. This log is meaningless.

**Comment by malfet** [comment]
Please attach entire log files to the issue if you want us to look into them. It's very hard to extract useful information from screenshots that often contain only truncated logs/commands.

**Comment by JiabinYang** [comment]
This is the full log message and the command I run is `python setup.py install`. The follow is what i did:
1. I install anaconda with it's official install tools downloaded from [https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh](url)
2. Run this shell and follow the instruction to install the anaconda
3. Run Command `conda install -c pytorch magma-cuda101` since my cuda version is 10.1. I got this log:
  
![image](https://user-images.githubusercontent.com/22361972/110413376-b4cbc600-80c8-11eb-9fd2-94e37b886739.png)

4. Run Command `python setup.py install`, then i got this error message:
![image](https://user-images.githubusercontent.com/22361972/110413460-d88f0c00-80c8-11eb-9357-c349ccc2b33c.png)

**Comment by JiabinYang** [comment]
ok, let me try this, thx a lot

**Comment by JiabinYang** [comment]
When I try to follow the instruction build torch on my Mac with OSX 10.15 it occurs
![image](https://user-images.githubusercontent.com/22361972/111762273-cc325c80-88db-11eb-900f-4b9f5e4e6526.png)
Plz help me with this

**Comment by skyline75489** [comment]
Try this:

```text
conda install intel-openmp mkl mkl-include
```

**Comment by malfet** [comment]
@JiabinYang , from the discussion, it sounds like you have a general question on how to build PyTorch, is that correct? 
If this is the case, please use https://discuss.pytorch.org
If you believe there is a bug in PyTorch official binaries, source code, documentation or build scripts, please do not hesitate to open a new issue. (As "Unknown arguments" issue got resolved already, wasn't it?)
