### ISSUE TITLE
Update trapz() to be trapezoid()

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#52606]
See https://github.com/scipy/scipy/pull/12934, where SciPy updated the trapz function.

As part of this change:

- trapz() should alias trapezoid(), but its documentation should be removed (silent alias)
- an OpInfo for trapezoid() should be added
- we should use this opportunity to review documentation for trapezoid()
- we should validate that tests for trapezoid() verify NumPy and SciPy consistency

Usage Info:
- trapz() is used a few times with Facebook. It cannot be removed without a proper deprecation + Torchscript adapter.
- trapz() is a top 250 NumPy operator according to https://github.com/Quansight-Labs/python-api-inspect/blob/master/data/csv/numpy-summary.csv

cc @mruberry @rgommers @heitorschueroff

**Comment by NivekT** [comment]
This issue has been fixed by #61475
