### ISSUE TITLE
Disallow `out=tensor` if `tensor` is an input to `torch.cat`

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#5260]
It's probably not worth fixing the following:
```
import torch
x = torch.randn(3, 3)
y = torch.randn(3, 3)
torch.cat([x, y], out=x)  # x becomes garbage
```

**Comment by apaszke** [comment]
Nah, we generally don't support having tensors as outputs and inputs when it's not the inplace overload. Reduction functions are also quite fun:
```python
torch.sum(x, 1, out=x)
```

**Comment by colesbury** [comment]
I think at some point we should deprecate `out=` functions that don't do NumPy-style broadcasting behavior. At least for reduction functions, that would prevent most `torch.sum(x, 1, out=x)` calls.

**Comment by soumith** [comment]
i think raising an error is worth it. and if we do deprecate, that's a separate issue.

**Comment by apaszke** [comment]
I'm not saying raising an error for bad inputs is a bad idea :wink: Just showing that this is only a tip of the iceberg

**Comment by colesbury** [comment]
I think the NumPy behavior here is better:
1) Use an internal buffer if the outputs and inputs overlap
2) Don't resize the output (use broadcasting rules)

(1) is already what we do for non-contiguous inputs and outputs

**Comment by colinfang** [comment]
I found it weird to have

```python
tmp = torch.zeros(4)
torch.add(torch.Tensor([1,2]), 1, out=tmp)
 2
 3
[torch.FloatTensor of size 2]
```

**Comment by ngimel** [comment]
Closing in favor of #41027
