### ISSUE TITLE
[Profiler] LegacyEvent does not respect device

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52611]
## 🐛 Bug

LegacyProfiler is still the default in recent versions of PyTorch, but recently discovered that it does not respect the input event device when enabled with `use_cuda=True`. Looking at the code we can see popRange does not pass the device into event constructor: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_legacy.cpp#L250 and event calls cuda record with device -1, regardless of the actual device the op is taking place on: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_legacy.cpp#L576

I'm not sure what the actual implications of this are, but this seems incorrect in general looking at the logic in `profiler_legacy.cpp`: https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_cuda.cpp#L35. It looks like we do not create the cuda events on the right device, and thus the event synchronization could lead to inaccurate timing.

**Comment by rohan-varma** [comment]
cc @ilia-cher @ngimel

**Comment by aaronenyeshi** [comment]
LegacyProfiler is no longer the default, and use_cude is deprecated. Closing this old issue.
