### ISSUE TITLE
Discussion on ATen functions which take no parameters

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5263]
Consider `torch.zeros(*sizes)`, which creates a zero-filled tensor but doesn't specify what its type will be. This has been a great annoyance for our users, and as such our Python frontend is getting a new `dtype` parameter which will let you specify if you want a CPU double tensor or a CUDA float tensor, etc. Critically, however, there are still two versions of the function: a plain tensor one, and a Variable one. When PyTorch merges variables and tensors, there will only be one such one.

I am opening this ticket to talk about what this will look like C++ ATen side.

* Are we adding a notion of `dtype` to ATen? `at::Type` is an attractive candidate, but it distinguishes between Variable and Tensor where dtype does not.
* Are we accepting `at::Type` as an argument to functions? Any function which, at the Python side, supports `foo(..., dtype=blah)` should also support this ATen side as a Type argument. This means we should convert to and from dtype to at::Type in ATen.
* How are we handling Variable versus Tensor? PyTorch frontend will resolve this problem by merging Variable and Tensor. In ATen, this can be resolved in two ways: if we use at::Type, there is no problem, as you are simply expected to pass an appropriate Variable type or Tensor type. If we introduce another notion of dtype, we need two copies of factory functions, one for Variables and one for Tensors.

Other things I've missed? CC @gchanan @colesbury

**Comment by gchanan** [comment]
> Are we adding a notion of dtype to ATen? at::Type is an attractive candidate, but it distinguishes between Variable and Tensor where dtype does not.

I don't see the reason to add dtype to ATen, at::Type covers everything.

> Are we accepting at::Type as an argument to functions? Any function which, at the Python side, supports foo(..., dtype=blah) should also support this ATen side as a Type argument. This means we should convert to and from dtype to at::Type in ATen.

what do you mean by function here?  If you mean for native functions, I don't see why we wouldn't allow at::Type.  Note that we already have a "hacky" version of this with native functions that only depend on the type of the tensor parameter, e.g. is_floating_point.  That's for convenience in both PyTorch and ATen, so you can just write tensor.is_floating_point() instead of tensor.type().is_floating_point().

> How are we handling Variable versus Tensor? PyTorch frontend will resolve this problem by merging Variable and Tensor. In ATen, this can be resolved in two ways: if we use at::Type, there is no problem, as you are simply expected to pass an appropriate Variable type or Tensor type. If we introduce another notion of dtype, we need two copies of factory functions, one for Variables and one for Tensors.

Use at::Type.

**Comment by ezyang** [comment]
>  If you mean for native functions, I don't see why we wouldn't allow at::Type.

Right, so, in that case, we should expose this Python side as a dtype, right?

**Comment by gchanan** [comment]
> Right, so, in that case, we should expose this Python side as a dtype, right?

Correct.  If you write parsing code with python_arg_parser, the dtype(...) construct already returns an at::Type.

**Comment by gchanan** [comment]
ATen native functions can now take at::Types and at::ScalarTypes (and optional versions as well, but those currently break the jit).
