### ISSUE TITLE
Libtorch C++ model predict/forward propagation crashed on windows10, CUDA 11.0, VS 2017 15.7.6 ,GTX 1050, but libtorch C++ works with cpu successfully

### ISSUE THREAD

**Issue by DineshRajanT** [pytorch/pytorch#52657]
I can compile cmake and execute the file properly on CPU using Libtorch,but the same code is not working on GPU.
I am using
Cuda version		  	11
Cudnn version			8.5
libtorch				libtorch-win-shared-with-deps-1.7.1%2Bcu110
pytorch                 	       1.7.1

`       

        auto device = torch::cuda::is_available() ? torch::kCUDA : torch::kCPU;
        cout << "DEVICE : " << device << endl;
        torch::jit::script::Module module;
        try {
        module = torch::jit::load(argv[1], torch::kCUDA);
        }
        catch (const c10::Error& e) {
        std::cerr << "Error loading the model\n";
        return -1;
        }
	
        cv::Mat input_image;
	input_image = cv::imread(argv[2]);
	cv::Mat img_float;
	input_image.convertTo(img_float, CV_32FC3, 1.0 / 255);
	auto img_tensor = torch::from_blob(img_float.data, { 1, img_float.rows, img_float.cols, 3 }).to(torch::kCUDA);
	img_tensor = img_tensor.permute({ 0, 3, 1, 2 });
	cout << img_tensor.size(0) << " " << img_tensor.size(1) << " " << img_tensor.size(2) << " " << img_tensor.size(3) << endl;
	//got the output as 1,3,360,640 here.....
	std::vector<torch::jit::IValue> inputs;
	inputs.push_back(img_tensor);
        torch::Tensor output = module.forward(inputs).toTensor();
`
After this module.forward() ......the code gets stuck and it got no output.

**Comment by skyline75489** [comment]
Can you try to print the exception message? 

```cpp
catch (const std::exception& e)
{
	cerr << e.what();
	return 0;
}
```

**Comment by DineshRajanT** [comment]
> Can you try to print the exception message?
> 
> ```c++
> catch (const std::exception& e)
> {
> 	cerr << e.what();
> 	return 0;
> }
> ```

Yes @skyline75489  actually I tried that and I found the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 3.00 GiB total capacity; 1.91 GiB already allocated; 35.04 MiB free; 1.99 GiB reserved in total by PyTorch) `

Is there any way to overcome this......any techniques @skyline75489

**Comment by skyline75489** [comment]
Well simply put, you need a graphic card with more GPU memory. Or you could reduce the batch size of the model but this leads to worse training performance.

**Comment by DineshRajanT** [comment]
@skyline75489 ....great thanks.I will look for any of those things

**Comment by skyline75489** [comment]
No problem 😄 . Machine learning does impose the need for graphic cards with *massive* memory, unfortunately. Feel free to close this issue
