### ISSUE TITLE
caffe2 load onnx model error:IndexError: Input 475 is undefined!

### ISSUE THREAD

**Issue by wwbnjsace** [pytorch/pytorch#52666]
Error:

when i use caffe2 for pretraind model. the model is from https://github.com/onnx/models/blob/master/vision/classification/vgg/model/vgg16-7.onnx

the code is:

1. - > import caffe2
2. - > model=onnx.load(vgg16-7.onnx)
3. - > prepared_backend=caffe2.python.onnx.backend.prepare(model)

then,error happend,
WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
WARNING: ONNX Optimizer has been moved to https://github.com/onnx/optimizer.
All further enhancements and fixes to optimizers will be done in this new repo.
The optimizer code in onnx/onnx repo will be removed in 1.9 release.

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    init_net, predict_net = c2.onnx_graph_to_caffe2_net(onnx_model_proto)
  File "/home/eeodev/.local/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 921, in onnx_graph_to_caffe2_net
    return cls._onnx_model_to_caffe2_net(model, device=device, opset_version=opset_version, include_initializers=True)
  File "/home/eeodev/.local/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 876, in _onnx_model_to_caffe2_net
    onnx_model = onnx.utils.polish_model(onnx_model)
  File "/usr/local/lib64/python3.6/site-packages/onnx/utils.py", line 24, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/usr/local/lib64/python3.6/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input 475 is undefined!
who can tell the solution!!!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by malfet** [comment]
I'm afraid you need to provide a bit more information about your module for anyone to efficiently debug the issue. 
And, as warning message suggests, have you tried using https://github.com/onnx/optimizer ?

**Comment by wwbnjsace** [comment]
> I'm afraid you need to provide a bit more information about your module for anyone to efficiently debug the issue.
> And, as warning message suggests, have you tried using https://github.com/onnx/optimizer ?

the model i use is pretrained model ,the website is https://github.com/onnx/models/blob/master/vision/classification/vgg/model/vgg16-7.onnx
i do not change the model,and not use https://github.com/onnx/optimizer .

**Comment by wwbnjsace** [comment]
if it is a pytorch model,when conver to onnx model ,we can use  "torch.onnx.export(model, input, 'model.onnx', verbose=True, keep_initializers_as_inputs=True)" ,by keep_initializers_as_inputs=True , use caffe2 load model will not happen than error .but the model i used is pretrained model ,how to use this method?
