### ISSUE TITLE
Replace deprecated AT_ERROR with `TORCH_CHECK(false,`  in `c10`

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#52669]
According to 
https://github.com/pytorch/pytorch/blob/64847c7f0b3559c6edc40f001619b80c7dc68ef7/c10/util/Exception.h#L479
all usages of AT_ERROR("msg") should be replace with `TORCH_CHECK(false, "msg")`
There are currently 29 instances of AT_ERROR being used in c10 codebase:
```
$ grep AT_ERROR c10 -R|grep -v Exception.h|wc -l
29
```

**Comment by lware1m1s** [comment]
I want to take a shot at this one.

**Comment by lware1m1s** [comment]
[52711](https://github.com/pytorch/pytorch/pull/52711)

**Comment by mruberry** [comment]
@malfet I think this issue can be closed now?

**Comment by K-ash-ish** [comment]
I am  a beginner wanted to contribute on open source. And I think this issue will be good for me. I'm on it.

**Comment by mruberry** [comment]
Note that AT_ERROR should be replaced with TORCH_CHECK(false, ...) for user-facing errors, but TORCH_INTERNAL_ASSERT(...) for errors caused or encountered by the system that are independent of the user.

**Comment by malfet** [comment]
Closing
