### ISSUE TITLE
can't run dictionary with string key as input to jit model in libtorch

### ISSUE THREAD

**Issue by natangold85** [pytorch/pytorch#52674]
## 🐛 Bug

Hi,
I'm trying to run jit model in libtorch.
I'm already using libtorch 1.7.1 and its working for me in libtorch 1.7.1
I needed to take nightly because of different issue in torchvision
So I compiled libtorch from source from master branch.
When running the models in new compiled libtorch i'm seeing that accessing to Dict[str, Tensor] with string is causing a crash in forward.

this is the error message i see:
unknown file: Failure
C++ exception with description "The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/converted_modules/object_detector/retina_head/retinanet_head_3d.py", line 9, in forward
  def forward(self: __torch__.converted_modules.object_detector.retina_head.retinanet_head_3d.RoiAlignStandAlone,
    inputs: Dict[str, Tensor]) -> Dict[str, Tensor]:
    feature = inputs["feature"]

## To Reproduce

1. compile nightly torch from source.
2. run this script on updated pytorch:
`import torch
from typing import Dict

class RoIAlignStandAlone(torch.nn.Module):
    def __init__(self, aligned_height, aligned_width, spatial_scale):
        super().__init__()

        self.aligned_width = int(aligned_width)
        self.aligned_height = int(aligned_height)
        self.spatial_scale = float(spatial_scale)

    def forward(self, d: Dict[str, torch.Tensor]) -> torch.Tensor:
        return d["feature"]

module = RoIAlignStandAlone(1, 1, 0.125)
sc = torch.jit.script(module)
torch.jit.save(sc, "/data2/roi_align.pt")
`
3. load this model and forward it with dictionary that has key "feature".

## Environment

Collecting environment information...
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
Clang version: Could not collect
CMake version: version 3.18.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro P5000
Nvidia driver version: 418.87.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpy-indexed==0.3.5
[pip3] numpy-quaternion==2019.10.3.10.26.21
[pip3] numpydoc==0.9.1
[pip3] pytorch3d==0.2.0
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect

cc @gmagogsfm

**Comment by ansley** [comment]
Hey, the problem is that you're missing the double underscores on `__init___` and you have incorrect spacing. Missing the underscores means that you're defining a custom method called `init`, so Python generates a default implementation of `__init__` for you. This code works:

```python
import torch
from typing import Dict

class M(torch.nn.Module):
    def __init__(self, aligned_height, aligned_width, spatial_scale):
        super(M, self).__init__()
        self.aligned_width = int(aligned_width)
        self.aligned_height = int(aligned_height)
        self.spatial_scale = float(spatial_scale)

    def forward(self, d: Dict[str, torch.Tensor]) -> torch.Tensor:
        return d["feature"]


sc = torch.jit.script(M(1, 1, 0.125))
torch.jit.save(sc, 'scriptmodule.pt')
loaded = torch.jit.load("scriptmodule.pt")
d = dict(feature=torch.rand(2, 3))
loaded(d)
```

**Comment by natangold85** [comment]
it was a copy problem. my code was with __init__ funciton.
but i found my problem source.
its not on the jit forward.
Our team using jit to save data. we are saving data in python and loading it on cpp.
I will create a new issue on it since this issue is already closed.
Thanks!
