### ISSUE TITLE
Inconsistent behavior for tensor creation with and without wrapping

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#52721]
## 🐛 Bug

`TypeError: len() of a 0-d tensor` is raised when generating a new tensor with a list of tensors after wrapping the function. The inconsistency between the behavior before/after the wrapping is unexpected.

Reproducible code:
```py
import torch

a = torch.tensor(1)
# The following line is okay.
t1 = torch.tensor([a])

def wrapper(func):
    def new_func(*args, **kwargs):
        print('hi')
        return func(*args, **kwargs)
    return new_func

old_getitem = torch.Tensor.__getitem__
torch.Tensor.__getitem__ = wrapper(old_getitem)
# It will be the same no matter we have the following line or not.
torch.Tensor.__getitem__ = old_getitem

# This won't work.
t2 = torch.tensor([a])
```

Another similar code example, `IndexError: too many indices for tensor of dimension 2` will be thrown:
```py
import torch

a = torch.ones((10, 1000))
b = torch.tensor([1, 2, 3], dtype=torch.int64)
# The following line is okay.
print(a[b])

def wrapper(func):
    def new_func(*args, **kwargs):
        print('hi')
        return func(*args, **kwargs)
    return new_func

old_getitem = torch.Tensor.__getitem__
torch.Tensor.__getitem__ = wrapper(old_getitem)
torch.Tensor.__getitem__ = old_getitem

# This won't work.
print(a[b])
```

## Expected behavior

The behavior should be consistent, either block this kind of usage or make both of them pass.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.18.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[conda] Could not collect

**Comment by peterjc123** [comment]
@albanD Any thoughts on this?

**Comment by albanD** [comment]
Hey

This is the same as https://github.com/pytorch/pytorch/issues/50710 I think.
But it does look weird indeed. I guess you end up setting the `__getitem__` on a different object from where it was originally. In particular, the default one comes from the c++ class, not the python `torch.Tensor` class!
You can print the following to see the difference:
```python
print(a.__dict__.get("__getitem__", None))
print(a.__class__.__dict__.get("__getitem__", None))
print(a.__class__.__bases__[0].__dict__.get("__getitem__", None))
```

But I think that the state is not properly restored and the c++ constructor trips up. But that would need more investigation.

**Comment by peterjc123** [comment]
The second one seems related to https://github.com/pytorch/pytorch/issues/41849.

**Comment by peterjc123** [comment]
> Hey
> 
> This is the same as #50710 I think.
> But it does look weird indeed. I guess you end up setting the `__getitem__` on a different object from where it was originally. In particular, the default one comes from the c++ class, not the python `torch.Tensor` class!
> You can print the following to see the difference:
> 
> ```python
> print(a.__dict__.get("__getitem__", None))
> print(a.__class__.__dict__.get("__getitem__", None))
> print(a.__class__.__bases__[0].__dict__.get("__getitem__", None))
> ```
> 
> But I think that the state is not properly restored and the c++ constructor trips up. But that would need more investigation.

The interesting point is that when I set `torch.Tensor.__getitem__`, the property of the base class `torch._C.__getitem__` is also changed.

**Comment by albanD** [comment]
> The interesting point is that when I set torch.Tensor.__getitem__, the property of the base class torch._C._TensorBase.__getitem__ is also changed.

That shouldn't be possible :D 
Trying to change the attributes of C classes fail!

**Comment by peterjc123** [comment]
Looks like I'm wrong.
```py
import torch

old_getitem = torch.Tensor.__getitem__
print(id(torch._C._TensorBase.__getitem__))
print(id(torch.Tensor.__getitem__))
torch.Tensor.__getitem__ = None
print(id(torch._C._TensorBase.__getitem__))
print(id(torch.Tensor.__getitem__))
``` 
This returns 
```
1811575031264
1811575031264
1811575031264
140703569127552
```

**Comment by albanD** [comment]
From a quick look, my guess is that https://github.com/pytorch/pytorch/blob/f71d9e28f9a140deb7845d12d60bae759964d5e5/torch/csrc/utils/tensor_new.cpp#L135 is False for scalar tensors as expected in general, but setting the `.__getitem__` method on all Tensors make all of them sequences (including scalars) hence the failure.
I don't have time to dive into how we ensure that scalar Tensors are not sequences right now but I guess the culprit is somewhere there.

**Comment by peterjc123** [comment]
@albanD Yes, you are right. When both `__getitem__` and `__len__` are defined, it is considered as a sequence, so `PySequence_Check` returns 1. I managed to workaround this situation using some `ctypes` hacks.

**Comment by albanD** [comment]
That being said, should we prevent users from being able to set `__getitem__` on scalar tensors? That feels like an easy trap no?

**Comment by peterjc123** [comment]
@albanD I don't know but I guess it's not easy to do since there's no separate type for scalar tensors. Currently, scalar tensors are of type `torch.Tensor`, which is no different from normal tensors.

**Comment by albanD** [comment]
But one is a Sequence and not the other. So there must be a difference between the two. They cannot be the actual same class do they?

**Comment by peterjc123** [comment]
Yes, but considering from a user's perspective, they won't wrap/call `ScalarTensor.__getitem__` instead until you tell them to. Usually, they will try `Tensor.__getitem__` first. If you could dispatch `Tensor.__getitem__` to different implementations, then I think it may work.

**Comment by albanD** [comment]
I still don't understand how this code is able to properly detect that the scalar Tensor is not a sequence haha
Both Tensors are of the exact same class...

**Comment by svepe** [comment]
I am currently working on some tracing I need to temporary replace `__getitem__` .
@peterjc123 What `ctypes` hacks did you do to make this work?

**Comment by peterjc123** [comment]
@svepe Sorry, I cannot tell you what I did exactly. But you could take a look at https://github.com/clarete/forbiddenfruit, which inspired me about how to do that.

**Comment by svepe** [comment]
@peterjc123 Thanks for the hint. I was hitting the second problem also mentioned in #41849 and at the end I found another way around it - just wrap any tensor index in a tuple for both `__getitem__` and `__setitem__` e.g.

```
original_getitem__ = torch.Tensor.__getitem__

def __getitem__(self, index):
    # Do some stuff here
    return original_getitem__((index,) if torch.is_tensor(index) else index)

```
