### ISSUE TITLE
[TensorExpr] Var names are not unique in the Stmt (despite appearing unique when printed)

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#52727]
## 🐛 Bug

Currently we do not check whether names of variables within a Stmt conflict with each other and allow them to be the same. When printing, however, we make them unique - this is incorrect and leads to a confusing behavior because if we then try printing that var in isolation, not in a scope of the Stmt, then its original (and not the new unique name assigned during the previous print) would be used.

Instead of making Vars appear unique during printing, we should update them in the stmt as we add them or at least as an explicit step.

## To Reproduce
Consider the following program:
```python
import torch

class kernel_arena_scope(object):
    def __enter__(self):
        self.scope = torch._C._te.KernelScope()

    def __exit__(self, typ, val, traceback):
        self.scope = None

with kernel_arena_scope():
    dtype = torch._C._te.Dtype.Float
    K = 100
    KK = torch._C._te.ExprHandle.int(K)

    B = torch._C._te.Compute('buf', [torch._C._te.DimArg(KK, 'i')], lambda k: k*k+k)
    C = torch._C._te.Compute('buf', [torch._C._te.DimArg(KK, 'i')],
            lambda k: B.load([k])*B.load([k]) - B.load([k]))

    loopnest = torch._C._te.LoopNest([B, C])
    print('Aggregated stmt:', loopnest.root_stmt())
    loops_B = loopnest.get_loops_for(B)
    loops_C = loopnest.get_loops_for(C)
    print('First loop:', loops_B[0])
    print('Second loop:', loops_C[0])
```

In this program we create a TE stmt consisting of two loops, and index variables of both loops have the same name "i". It is not flagged as a problem and not fixed automatically, but if we print the aggregated stmt, it appears valid:
```
Aggregated stmt: {
  for (int i = 0; i < 100; i++) {
    buf[i] = i * i + i;
  }
  for (int i_1 = 0; i_1 < 100; i_1++) {
    buf_1[i_1] = (buf[i_1]) * (buf[i_1]) - (buf[i_1]);
  }
}
```
(Note that the index var in the second loop is now `i_1`).

However, if we print the loops individually, both of them would have the same index variable:
```
First loop: for (int i = 0; i < 100; i++) {
  buf[i] = i * i + i;
}
Second loop: for (int i = 0; i < 100; i++) {
  buf[i] = (buf_1[i]) * (buf_1[i]) - (buf_1[i]);
}
```

The same is true for buffer names, which is even more confusing. In this examples, the names "buf" and "buf_1" are even swapped when we print the second loop!

## Expected behavior
The variables and buffers preserve their names when they are printed individually as well:
```
First loop: for (int i = 0; i < 100; i++) {
  buf[i] = i * i + i;
}

Second loop: for (int i_1 = 0; i_1 < 100; i_1++) {
  buf_1[i_1] = (buf[i_1]) * (buf[i_1]) - (buf[i_1]);
}
```

**Comment by navahgar** [comment]
Why are we printing the buffers as `buf` and `buf_1` when they were created using `Compute` with `B` and `C` instead?

**Comment by ZolotukhinM** [comment]
Maybe I messed up my example after I copy-pasted its output :)
