### ISSUE TITLE
Formatting error in torch.autograd.profiler.profile.key_averages documentation

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#52742]
## 📚 Documentation

There's a problem with the formatting of the `torch.autograd.profiler.profile.key_averages` Parameters section:
https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.profile.key_averages

![image](https://user-images.githubusercontent.com/77580049/108995730-2f96e900-76a6-11eb-9133-1b312535e413.png)
The description for the `group_by_input_shape` parameter is spread across multiple lines/bullets, each looking like a separate parameter.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @brianjo @mruberry

**Comment by mruberry** [comment]
We would definitely accept a PR fixing this!
