### ISSUE TITLE
torch.norm behavior for negative p when reducing over empty dimension

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#52783]
Typically, when reducing over empty dimension, reduction result is filled with identity element (e.g. `torch.randn(3,0).sum(-1)` will be a tensor of size 3 filled with 0-s), or error is thrown, when operation doesn't have identity element (`torch.randn(3,0).max(-1)`). For norms with negative p, it is not the case:
```
In [1]: import torch                                                                                                                                                                                     

In [2]: import numpy as np                                                                                                                                                                               

In [3]: x=torch.randn(4,0)                                                                                                                                                                               

In [4]: x.norm(p=-1, dim=-1)                                                                                                                                                                             
Out[4]: tensor([0., 0., 0., 0.])

In [5]: np.linalg.norm(x.numpy(), ord=-1, axis=-1)                                                                                                                                                       
/private/home/ngimel/opt/anaconda3/envs/pt/lib/python3.7/site-packages/numpy/linalg/linalg.py:2516: RuntimeWarning: divide by zero encountered in reciprocal
  ret **= (1 / ord)
Out[5]: array([inf, inf, inf, inf], dtype=float32)
```
For norms, reduction operation is `(x^p+y^p)^(1/p)`. 0 would be a correct identity element for positive p, but pytorch fills result with 0-s even for negative p. 
Numpy in the same situation fills result with `inf`s, indicating that for operation above it thinks `inf` is an identity. It's kinda true, but then why don't we use `inf/-inf` as identity for min and max operations? 
Pytorch behavior is clearly wrong, but there's a question whether we should reproduce numpy behavior, or throw an error for this operation, similar to how we do for max/min.

cc @mruberry @rgommers @heitorschueroff

**Comment by rgommers** [comment]
I'm not a fan of the `np.linalg.norm` behavior, I'd have preferred if it acted like `min`/`max`.

One argument for that is that a reduction should have a proper mathematical and not just a numerical identity. `sum([]) == 0` and `prod([]) == 1` holds for all dtypes, but if `max([])` would be `inf` rather than raise, what do you return for integer input ? Something like `iinfo(int32).max` would lead to a lot of bugs, and having a dtype-dependent output shape or exception seems wrong.

**Comment by ngimel** [comment]
`torch.norm` is updated to follow numpy behavior, filling with -inf when reducing over empty dimension with negative p.
