### ISSUE TITLE
Incorrect type annotation for DataLoader

### ISSUE THREAD

**Issue by danielgordon10** [pytorch/pytorch#52806]
## 🐛 Bug

On https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L162 `collate_fn` is defined to be `Callable[[List[T]], Any]` but the default value is None. I believe the `_collate_fn_t` needs to be `Optional[Callable[[List[T]], Any]]]`. As it stands, it should not pass python type-checking (it fails using pyright, maybe mypy misses this case).

cc @SsnL @VitalyFedyunin @ejguan @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by danielgordon10** [comment]
_worker_init_fn_t has a similar issue.

**Comment by ejguan** [comment]
Without using option`--no-implicit-optional`, `mypy` would assume arguments with default values of None are Optional. So, it's fine that passes type-checking.
Feel free to submit a PR to fix it, we would like to review it.

**Comment by danielgordon10** [comment]
https://github.com/pytorch/pytorch/pull/52924

I would recommend using `--no-implicit-optional` as it can catch hard-to-find bugs, but that's just my opinion.

**Comment by ejguan** [comment]
Just tried to run `mypy --no-implicit-optional` under torch. A bunch of error come from generated `torch/_C/_VariableFunctions.pyi` and `torch/_VF.pyi`.
And IMO, it definitely deserves to be solved as the default `None` value has potential causing `Exception` at runtime.

**Comment by rgommers** [comment]
Sounds good to fix all of those @ejguan. Note that `mypy-strict.ini` already has the `--no-implicit-optional` setting, which is applied to some of the key files like codegen and autograd. There's also other settings that differ between the two mypy ini files. Maybe we should open a new tracking issue and figure out which settings to apply to the whole codebase. For example, `implicit_reexport` is likely worth doing too, to avoid more `pyright`-user complaints.

**Comment by danielgordon10** [comment]
I believe pyright `strictParameterNoneValue` serves a similar purpose, but my repository has this value on, and it complains when I create a dataloader and don't provide a `collate_fn`.

Example code
```python
dataloader = DataLoader(
    dataset,
    batch_size=64,
    shuffle=False,
    num_workers=min(8, cast(int, os.cpu_count())),
    pin_memory=False,
    drop_last=False,
    prefetch_factor=1,
    #collate_fn=default_collate,
)
```

Error
```
  54:22 - error: Argument of type "None" cannot be assigned to parameter "collate_fn" of type "_collate_fn_t[T@_collate_fn_t]" in function "__init__"
    Type "None" cannot be assigned to type "_collate_fn_t[T@_collate_fn_t]" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos
```
