### ISSUE TITLE
setup.py sdist does not include third party submodules

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#52843]
## 🐛 Bug

`python setup.py sdist` should produce a tarball of source code that is self-contained and sufficient to compile the project. Currently
- the third-party sources are not included
- the LICENSE file does not include the third party licenses (solved for wheels by gh-51634)
- some other files that are required for building like `version.txt` are not included

This is related to issues gh-50697 and gh-13586

@rgommers

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Worse than that, it actually does not include most of the C++ source code :(

**Comment by seemethere** [comment]
> 
> 
> Worse than that, it actually does not include most of the C++ source code :(

That portion should be easy to solve though with a `MANIFEST.in`: https://packaging.python.org/guides/using-manifest-in/
