### ISSUE TITLE
init_process_group with launch.py --nnode=2 hangs always in all machines

### ISSUE THREAD

**Issue by WurmD** [pytorch/pytorch#52848]
## 🐛 Bug

Init_process_group with launch.py --nnode=2 hangs always in all machines

## To Reproduce

```
import os
import torch.distributed as dist

os.environ['MASTER_ADDR'] = '148.251.86.243'
print(f"[ {os.getpid()} ] Initializing process group")
dist.init_process_group(backend="nccl")
print(f"[ {os.getpid()} ] world_size = {dist.get_world_size()}, " + f"rank = {dist.get_rank()}, backend={dist.get_backend()}")
```
- Launching with launch.py in master server hangs:
```
$ export NCCL_DEBUG=INFO ; export NCCL_DEBUG_SUBSYS=ALL ; python3 /home/dario/.local/lib/python3.6/site-packages/torch/distributed/launch.py --nnode=2 --node_rank=0 --nproc_per_node=1 msg3d/MSG3D/tuturial_DistributedDataParallel.py --local_world_size=1
[26236] Initializing process group with: {'MASTER_ADDR': '148.251.86.243', 'MASTER_PORT': '29500', 'RANK': '0', 'WORLD_SIZE': '2'}
```
- And in second server it also hangs:
```
$ export NCCL_DEBUG=INFO ; export NCCL_DEBUG_SUBSYS=ALL ; python3 /home/dario/.local/lib/python3.6/site-packages/torch/distributed/launch.py --nnode=2 --node_rank=1 --nproc_per_node=1 msg3d/MSG3D/tuturial_DistributedDataParallel.py --local_world_size=1
[17186] Initializing process group with: {'MASTER_ADDR': '148.251.86.243', 'MASTER_PORT': '29500', 'RANK': '1', 'WORLD_SIZE': '2'}
```
After 30 minutes
`RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=2, worker_count=1, timeout=0:30:00)`                                           

## Expected behavior

Doesn't hang

## Environment

PyTorch version: 1.7.1 or 1.8.0.dev20210208+cu110
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.17.1

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.4
[pip3] torch==1.7.1 or 1.8.0.dev20210208+cu110
[pip3] torchvision==0.8.1
[conda] Could not collect

## Additional context

- [No difference between `dist.init_process_group(backend="nccl")` and `"gloo"`](https://discuss.pytorch.org/t/pytorch-distributed-example-code-hang-deadlock/83335)
- [No difference when setting `os.environ['NCCL_SOCKET_IFNAME'] = 'lo'`](https://discuss.pytorch.org/t/torch-distributed-launch-hanged/112223)
- [Setting `export NCCL_DEBUG=INFO ;    export NCCL_DEBUG_SUBSYS=ALL ;` produces no new output](https://pytorch.org/docs/stable/distributed.html#other-nccl-environment-variables)
- No difference between PyTorch 1.7.1 and 1.8.0-rc4
- [dist.init_process_group(backend="nccl", **init_method='env://'**) didn't help](https://github.com/pytorch/pytorch/issues/23074#issuecomment-513445542)
- https://github.com/pytorch/pytorch/issues/49846 does not apply as we're not using jupyter notebook 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
@WurmD Can you confirm the second server can reach the master on ip 148.251.86.243 and port 29500? Running a simple command like this on the second server when the master process is running can confirm this: `telnet 148.251.86.243 29500`.

**Comment by WurmD** [comment]
First server master process running
```
$ sudo netstat -tap | grep 29500
[sudo] password for dario:
tcp        0      0 0.0.0.0:29500           0.0.0.0:*               LISTEN      3220/python3
tcp        0      0 GPU14:40714             GPU14:29500             ESTABLISHED 3220/python3
tcp        0      9 GPU14:29500             GPU14:40714             ESTABLISHED 3220/python3

```
Second server can `ping  148.251.86.243`,
can `ssh 148.251.86.243`,
but can't `telnet 148.251.86.243 29500` :/

**Comment by WurmD** [comment]
Ok, managed to open a port (29500) that allows init_process_group to run correctly.

In my firewall settings it looks like
```
Source IP | Destination IP | Source port | Destination port | Protocol | TCP flags | Action 
          |                |             |            29500 |      tcp |           | accept
```

**After** master process is running (that starts listening on 29500), then doing `telnet 148.251.86.243 29500` says
```
Trying 148.251.86.243...
Connected to gpu14.
Escape character is '^]'.
```
confirming the port is correctly open.

And running the minimal example above makes init_process_group return correctly and print my second print above
`[ 8172 ] world_size = 2, rank = 0, backend=nccl`

**Comment by 4ndr3aR** [comment]
I'm having the same problem running jobs via slurm, but it happens also with `--ntasks-per-node=2`. With `netstat -nlp` (on the master node) and `netstat -np` (on the slave nodes) I see that all the connections are `ESTABLISHED`, but at the end the script inevitably times out. I'm using pytorch 1.7.1.

**Comment by 4ndr3aR** [comment]
I can confirm that upgrading to pytorch 1.9.1 solves this issue.

**Comment by bgswaroop** [comment]
> I can confirm that upgrading to pytorch 1.9.0 solves this issue.

I am facing the same issue even with torch==1.9.0_cu111

**Comment by GeekDream-x** [comment]
> > I can confirm that upgrading to pytorch 1.9.0 solves this issue.
> 
> I am facing the same issue even with torch==1.9.0+cu111

Me too.

**Comment by 18445864529** [comment]
Has this problem been solved?

**Comment by RachelLYY** [comment]
> > I can confirm that upgrading to pytorch 1.9.0 solves this issue.
> 
> I am facing the same issue even with torch==1.9.0+cu111

me too. Have you solved this problem?

**Comment by ZhongYFeng** [comment]
> > > I can confirm that upgrading to pytorch 1.9.0 solves this issue.
> > 
> > 
> > I am facing the same issue even with torch==1.9.0+cu111
> 
> Me too.

I also facing the same issue even with torch==1.9.1+cu102
Have you solved this problem? Why has this question been closed? I don't see any solution.

**Comment by 18445864529** [comment]
> I also facing the same issue even with torch==1.9.1+cu102 Have you solved this problem? Why has this question been closed? I don't see any solution.

The problem is usually due to wrongly set world size / ranks, for example when you tell it there are a total of 8 workers (gpus) but it can only find 4.

**Comment by xinfeng1i** [comment]
I have the same problem, has it been solved ?

**Comment by Asciotti** [comment]
Bumping since I am having issues with `launch.py` and `run.py` on multi-node setups. I can telnet back and forth as well as netcat between all the nodes on pretty much any port.

on PyTorch version: 1.11.0+cu102

**Comment by josejimenezluna** [comment]
Bumping this. I am also encountering the same problem with `pytorch=1.11` and `cudatoolkit=11.3`.

**Comment by marcobellagente93** [comment]
bump

**Comment by han508** [comment]
bump
