### ISSUE TITLE
Future of chain_matmul?

### ISSUE THREAD

**Issue by heitorschueroff** [pytorch/pytorch#52868]
The PR https://github.com/pytorch/pytorch/pull/52859 implements `torch.linalg.multi_dot` similar to `np.linalg.multi_dot`. The function `torch.chain_matmul` implements similar behavior with the differences being:
- `chain_matmul` allows a single input tensor while `linalg.multi_dot` requires at least 2
- `chain_matmul` requires all tensors to be 2D while `linalg_multi_dot` allows the first and last tensors to be 1D or 2D.

The question now is what should we do with `torch.chain_matmul`. Some options are
1. Leave it as is
2. Docs deprecate in favor of multi_dot
3. Make it an alias of multi_dot which would break BC since it will no longer work for inputs with a single Tensor, unless we update multi_dot to diverge from NumPy and allow such case.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
It looks like there are a few uses of torch.chain_matmul() in Facebook outside of testing and all have more than one input tensor.

I propose implementing chain_matmul() as an alias of linalg.multi_dot() with the caveat that it supports single tensor inputs. In the code this can just be a short-circuit before the call to multi_dot(). From a test perspective this just requires a small additional test, too. Once that's done we can think about deprecating chain_matmul()'s divergent behavior.

**Comment by vadimkantorov** [comment]
Question about supporting batched chained matmuls: https://github.com/pytorch/pytorch/pull/52859#issuecomment-804938641

In the wild this happens in https://github.com/ajabri/videowalk/blob/master/code/model.py#L149 (computing the cycle's total transition matrix)

**Comment by heitorschueroff** [comment]
> Question about supporting batched chained matmuls: [#52859 (comment)](https://github.com/pytorch/pytorch/pull/52859#issuecomment-804938641) with multi_dot / chain_matmul
> 
> In the wild this happens in https://github.com/ajabri/videowalk/blob/master/code/model.py#L149 (computing the cycle's total transition matrix)

@vadimkantorov This seems like a reasonable request. Could you open an issue to track this feature request? I'm closing this issue as we've made torch.chain_matmul an alias of torch.linalg.multi_dot and added deprecation warning to torch.chain_matmul.
