### ISSUE TITLE
Float to Half assignment issue when using torch.jit.script

### ISSUE THREAD

**Issue by RezaYazdaniAminabadi** [pytorch/pytorch#52872]
## 🐛 Bug

Hi, 
I am using torch.jit.script for fusing bias-add and gelu function like this:
![image](https://user-images.githubusercontent.com/44502768/109215246-c11a5f80-7767-11eb-992f-fb8d778b55fa.png)
however, it gives me an error that some identifier is not found and that the assignment operator is getting half and float as the operands types:
![image](https://user-images.githubusercontent.com/44502768/109215555-29694100-7768-11eb-81e0-29b99d782d26.png)
There is also another related issue with the same code [here](https://github.com/pytorch/pytorch/issues/45953), however the error is different.
There is also another related [issue ](https://github.com/pytorch/pytorch/issues/47138) that reported somewhat similar bug and I think @nickgg has fixed this bug at some point last year by this [PR](https://github.com/pytorch/pytorch/pull/47229).

Could you please help double-check this fix, as this issue still exists in the latest Pytorch1.7?

Thanks in advance,
Reza

cc @gmagogsfm

**Comment by Lilyjjo** [comment]
Hi @RezaYazdaniAminabadi, when I run the code above (and the code from #47138) from the nightly build I don't get errors. Can you include the version of PyTorch you are running? Thanks

**Comment by gmagogsfm** [comment]
Hi @RezaYazdaniAminabadi,

As @Lilyjjo said, we think this issue has been fixed at head. Please try again with latest version of PyTorch. Thanks.
