### ISSUE TITLE
CPU-based monitored/timed barrier in distributed debug mode

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#52876]
## 🚀 Feature
One important problem we are interested in with regard to PT distributed debugability is figuring out which rank(s) experienced desynchronization issues, so that we can focus debugging efforts on those ranks. One function that can help with this is the idea of a monitored barrier, which essentially does a send/recv from rank 0 using a CPU-backed PG to ensure all ranks enter the barrier and can identify which rank(s) did not. @divchenko has implemented a version of this internally and we would like this to be broadly available in PyTorch.

## Motivation
When running under `TORCH_DISTRIBUTED_DEBUG`, we can insert this monitored barrier at synchronization points within PT distributed (for example: DDP constructor, calls to alltoall/allreduce, tec) which will allow us to quickly detect and error out when ranks are desynchronized. Users can also directly use this API to aid their debugging efforts

## Pitch

```
def monitored_barrier(timeout):
    if self.rank != 0:
        # Send and Recv from rank 0
        pg.send(tensor, dst=0)
        pg.recv(tensor, dst=0)
        return
    works = [pg.irecv(tensor, r) for r in (1, world_size)]
    failed = []
    for w in works:
        try:
            w.wait(timeout=timeout)
       except Exception as e:
           failed.append(f"Rank {r} failed to enter monitored barrier with error {str(e)}")
    # ... do the same for sends
   if failed:
        err = "\n".join(failed)
       raise failed
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
This seems like a much simpler idea compared to the store based idea we were discussing earlier to detect such desynchronization.
