### ISSUE TITLE
torch.multinomial with NaNs and replacement=True leaves CUDA in an unusable state

### ISSUE THREAD

**Issue by tfjgeorge** [pytorch/pytorch#52878]
## 🐛 Bug

If `input` contains a NaN then torch.multinomial(input, replacement=True) raises an exception (this is expected behaviour) but also leaves the cuda driver in an unusable state, even when catching the exception. Using replacement=False however works as expected.

## To Reproduce

This works as expected:

	import torch

	print('do something on gpu')
	print(torch.tensor([1]).cuda() + torch.tensor([2]).cuda())

	try:
		torch.multinomial(torch.tensor([float('nan')]).cuda(), 1)
	except:
		print('exception raised')

	print('do something else on gpu')
	print(torch.tensor([3]).cuda() + torch.tensor([4]).cuda())

and gives:

	$ CUDA_LAUNCH_BLOCKING=1 python mult.py 
	do something on gpu
	tensor([3], device='cuda:0')
	exception raised
	do something else on gpu
	tensor([7], device='cuda:0')
	$

but this does not work as expected (with replacement=True):

	import torch

	print('do something on gpu')
	print(torch.tensor([1]).cuda() + torch.tensor([2]).cuda())

	try:
		torch.multinomial(torch.tensor([float('nan')]).cuda(), 1, replacement=True)
	except:
		print('exception raised')

	print('do something else on gpu')
	print(torch.tensor([3]).cuda() + torch.tensor([4]).cuda())

since it does not raise an exception, and renders the cuda environment unusable (note that it fails *after* the call to multinomial):

	$ CUDA_LAUNCH_BLOCKING=1 python mult.py 
	do something on gpu
	tensor([3], device='cuda:0')
	/pytorch/aten/src/ATen/native/cuda/MultinomialKernel.cu:190: sampleMultinomialOnce: block: [0,0,0], thread: [0,0,0] Assertion `val >= zero` failed.
	do something else on gpu
	Traceback (most recent call last):
	  File "mult.py", line 12, in <module>
	    print(torch.tensor([3]).cuda() + torch.tensor([4]).cuda())
	RuntimeError: CUDA error: device-side assert triggered
	$

## Environment

PyTorch version: 1.6.0 (I also tried on a PyTorch 1.7.0 install)
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (GCC) 7.4.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 450.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchmeta==1.5.1
[pip3] torchvision==0.7.0
[conda] Could not collect

cc @ngimel

**Comment by ngimel** [comment]
This is expected behavior. In case of multinomial with replacement the prob values are checked in the kernel, and there the only remedy is to invalidate the context. It also cannot throw exception right away (2nd example, without CUDA_LAUNCH_BLOCKING) because it can only happen during kernel runtime.

**Comment by tfjgeorge** [comment]
Shouldn't it be consistent when switching replacement value from False to True, from the user standpoint?

**Comment by ngimel** [comment]
replacement `False` and `True` use completely different algorithms, and the errors they throw are implementation details.

**Comment by tfjgeorge** [comment]
I see then I will close the issue.

Thanks for your time!
