### ISSUE TITLE
when converting scripted model to coremltools, Unknown type bool encountered in graph lowering. This type is not supported in ONNX export

### ISSUE THREAD

**Issue by matthewchung74** [pytorch/pytorch#52889]
## 🐛 Bug

getting this error
`Unknown type bool encountered in graph lowering. This type is not supported in ONNX export.` This is using the timm visual transformer architecture.

## To Reproduce

1. run this colab https://colab.research.google.com/drive/13tF8p9x4FCPG0KEC_PBEEMianWKo8mfG?usp=sharing

which basically grabs a visual transformer from time, and tries to convert to torchscript to coreml

## Expected behavior

should not get the error

## Environment

colab

originally filed and triaged with coreml https://github.com/apple/coremltools/issues/1085

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by garymm** [comment]
This issue appears to be specific to Core ML Tools' usage of internal PyTorch APIs and it appears there are already issues tracking this in the coremltools repo, so closing this.

In general an alternative may be to try `torch.onnx.export` and then `coremltools.converters.onnx.convert`

**Comment by TobyRoseman** [comment]
> This issue appears to be specific to Core ML Tools' usage of internal PyTorch APIs and it appears there are already issues tracking this in the coremltools repo

@garymm - can you please be more specific?

**Comment by garymm** [comment]
@TobyRoseman judging from the stack traces, the failure is inside `converters/mil/frontend/torch/converter.py`.
And https://github.com/apple/coremltools/issues/1085 seems to track the same issue on the coremltools repo.

**Comment by TobyRoseman** [comment]
@garymm - The stacktrace does go through coremltools. However the error happens in a Torch binary. I don't think this is an issue that can be solved in the coremltools repository. I think this require a change in torch code.

**Comment by garymm** [comment]
@TobyRoseman `_jit_pass_lower_graph` is designed for use by `torch.onnx.export`, not anything outside of PyTorch. I think there is some prerequisite to calling that function that is not being satisfied by coremltools. Probably some other pass that converts bools to Tensors is expected to have run already.
