### ISSUE TITLE
RunTimeError: torch.det and torch.lu does not support automatic differentiation for outputs with complex dtype

### ISSUE THREAD

**Issue by mzzhang95** [pytorch/pytorch#52891]
## 🐛 There are two bugs:
Error 1: RunTimeError: torch.det does not support automatic differentiation for outputs with complex dtype. 
Error 2: To avoid Error 1, I also tried to calculate determinant of a complex matrix by using LU-Decomposition. However, lu.backforward() only supports floating data type. I am sure that my matrix has full rank. That problems only occur if input matrix is a tensor which requires auto_grad.

Just wondering if there is any plan for supporting complex auto_grad in the future. Thanks a lot for your help!!!

### Steps to reproduce Error 1:
x = torch.randn(4, 4, requires_grad=True, dtype=torch.cdouble)
torch.det(x)

Error messages for Error 1:
RuntimeError: det does not support automatic differentiation for outputs with complex dtype.

### Steps to reproduce Error 2:
A = torch.ones(4, 4, requires_grad=True, dtype=torch.cdouble)
A_LU, pivots = A.lu()

Error messages for Error 2:
ValueError: lu.backward works only with batches of squared full-rank matrices of floating types.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): nightly 1.9.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 10.2, CUDNN 8
 - GPU models and configuration: GTX 1080Ti
 - Any other relevant information:

## Additional context

cc @ezyang @anjali411 @dylanbespalko @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by anjali411** [comment]
tHi @mzzhang95 thanks for filing this issue! There's already a PR in progress to add complex autograd support for `torch.det` https://github.com/pytorch/pytorch/pull/48125.
I added `torch.lu` to the list in the main complex tracker(https://github.com/pytorch/pytorch/issues/33152) and someone should work on it soon. If you are interested to contribute, I am happy to help, answer your questions and review your PR.

**Comment by nikitaved** [comment]
Hi, @mzzhang95 , thank you for the issue. I have a question for you regarding `torch.lu`. Do you use it with square matrices? If not, there is outstanding effort of mine to enable backward methods for all lu-related methods also for tall and square matrices. It could be a great time to pick it up again.

**Comment by mzzhang95** [comment]
Hi @nikitaved , thanks a lot for your replying! I am only using the square matrices as input for torch.lu. I am using LU decomposition to calculate determinant of a complex matrix.

**Comment by nikitaved** [comment]
I see, than it is hopefully an easy fix, unless I manage to run into some weird issues again as I did during my last attempt :) Just for your information, `torch.det` uses the LU decomposition.

**Comment by mzzhang95** [comment]
@nikitaved  Thanks for telling me! Then I guess the possible reason for autograd doesn't work for complex determinant is that torch.prod also doesn't support complex dtype, since the product of all diagonal elements from upper triangular matrix is needed. Anyway, thanks a lot for your help!!!

**Comment by nikitaved** [comment]
It is a bit more involved, but yes, prod is important there, there is a circular relationship between different operations to make everything work with complex numbers. I am marking this as my high prior issue for now.

**Comment by chenhao1umbc** [comment]
I have encountered the same issue with Pytorch 1.8, using the torch.linalg.det(x). Thanks.

**Comment by Lezcano** [comment]
This should be fixed in master.
