### ISSUE TITLE
Windows builds are using Microsoft's OpenMP header instead of Intel's

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#52907]
## 🐛 Bug

Windows builds on CI seem to be using [Microsoft's OpenMP](https://docs.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=msvc-160) headers instead of Intel's. Is it possible to use Intel's OpenMP instead, as [Microsoft OpenMP doesn't support all the functions](https://docs.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-functions?view=msvc-160) in the OpenMP specification, such as [omp_get_level()](https://www.openmp.org/spec-html/5.0/openmpsu127.html). The build process installs `intel-openmp`, which is being used, but as @peterjc123 astutely observed, the omp.h header file provided by Microsoft is being used.  Thanks!

```
-- Found OpenMP_C: -openmp:experimental  
CMake Warning (dev) at C:/w/b/windows/conda/envs/py37/Library/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  third_party/fbgemm/CMakeLists.txt:60 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.


-- Found OpenMP_CXX: -openmp:experimental  
-- Found OpenMP: TRUE   
CMake Warning at third_party/fbgemm/CMakeLists.txt:62 (message):
  OpenMP found! OpenMP_C_INCLUDE_DIRS =
```

```
CXX flags             : /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK
```

## To Reproduce

1. Use a standard OpenMP function that Microsoft doesn't list in its [ OpenMP functions list](https://docs.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-functions?view=msvc-160), such as [omp_get_level()](https://www.openmp.org/spec-html/5.0/openmpsu127.html).
2. Windows builds will fail, as [here](https://app.circleci.com/pipelines/github/pytorch/pytorch/278273/workflows/297e8ae2-c210-466c-be24-ee5c82787d2f/jobs/11168659), for example, because Intel OpenMP's headers aren't used.
3. #52964 by @peterjc123 resolves this issue.

## Expected behavior

Is it possible to use Intel's OpenMP headers for Windows builds instead? 

## Environment

[CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/278273/workflows/297e8ae2-c210-466c-be24-ee5c82787d2f/jobs/11168659)

## Additional context
#52964 by @peterjc123 resolves this issue.

**Comment by imaginary-person** [comment]
Hello @peterjc123, can you please let me know if using Microsoft OpenMP is indispensable, or if Intel OpenMP can be used instead. Thank you!

**Comment by peterjc123** [comment]
Microsoft OpenMP is not necessary, and we are supposed to use Intel OpenMP. I was not aware that it is actually using vcomp instead of iomp.

**Comment by peterjc123** [comment]
So if we switch from `-openmp:experimental` to `-openmp`, will Intel OpenMP be used?

**Comment by peterjc123** [comment]
https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/optimization-and-programming-guide/openmp-support/openmp-library-support/using-the-openmp-libraries.html

Or maybe we should add `/nodefaultlib:vcomp` in the link line, right?

**Comment by imaginary-person** [comment]
Thanks a lot for taking a look, @peterjc123!

The only reason why I think Microsoft OpenMP is being used is that `openmp:experimental` seems to be Microsoft's OpenMP, and because it doesn't support `omp_get_level()`, so builds such as [this one](https://app.circleci.com/pipelines/github/pytorch/pytorch/278273/workflows/297e8ae2-c210-466c-be24-ee5c82787d2f/jobs/11168659) failed.

I can try replacing `-openmp:experimental` with `-openmp`, but I suspect that'd also use Microsoft's OpenMP. I can still try, though. I had also tried replacing it with `-Qopenmp`, but the build system couldn't find Intel's OpenMP this way.

Please advise if I should try adding `/nodefaultlib:vcomp` to the following line as well:
https://github.com/pytorch/pytorch/blob/94e23e51c4d9db27e277f674c1cc6c3934ef5f0e/cmake/Modules/FindOpenMP.cmake#L104

**Comment by peterjc123** [comment]
-Qopenmp is a flag for intel c compiler, not for MSVC.

**Comment by imaginary-person** [comment]
I had also tried `/Qopenmp`

**Comment by imaginary-person** [comment]
@peterjc123, do you remember why you had added `-openmp-experimental` in #20353? Before that, did builds use to fail on Windows?

**Comment by peterjc123** [comment]
I just thought it is somehow like `-openmp_with_simd`. Because it makes the compiler to accept more recent openmp syntax.

**Comment by peterjc123** [comment]
BTW, do you have a slack account? We may have more discussion there.

**Comment by imaginary-person** [comment]
Thanks, I'll request to be added to that channel.

**Comment by peterjc123** [comment]
Good, Do you have Messenger or WeChat account, btw?

**Comment by imaginary-person** [comment]
No, I don't. :(

**Comment by peterjc123** [comment]
That's so sad. I just thought that talking too much here will make the thread look messy.

**Comment by imaginary-person** [comment]
Maybe no one else would be able to assist on the [Slack group](https://docs.google.com/forms/d/e/1FAIpQLSeADnUNW36fjKjYzyHDOzEB_abKQE9b6gqqW9NXse6O0MWh0A/viewform). I just submitted a request for approval.

**Comment by peterjc123** [comment]
@imaginary-person Could you please tell me your email address?

**Comment by imaginary-person** [comment]
sanchit@cs.wisc.edu. Would you be able to add me to the Slack channel? Thanks!
Please inform me after reading it.

**Comment by peterjc123** [comment]
Invitation sent. I may only add you to a specific channel, not the whole org.

**Comment by imaginary-person** [comment]
Thank you! It shows me `Your team is now working with PyTorch in #windows` but it hasn't set up that channel yet.

**Comment by peterjc123** [comment]
@imaginary-person I'm sorry. It still needs the admin's approval. BTW, I did some tests locally and it seems that the problem is because I forget to package the openmp headers in the mkl package.

**Comment by imaginary-person** [comment]
Thank you! It'd be great if you could submit a draft PR to run it on CI.

**Comment by peterjc123** [comment]
@imaginary-person See https://github.com/pytorch/pytorch/pull/52964. Should be resolved.

**Comment by peterjc123** [comment]
After inspection, I don't think it's a high-pri issue because the intel libs are still linked instead of the VCOMP ones. So after providing the Intel OpenMP headers, the functions can be referenced.

**Comment by imaginary-person** [comment]
@peterjc123, thanks a lot for your awesome work!

> After inspection, I don't think it's a high-pri issue because the intel libs are still linked instead of the VCOMP ones. So after providing the Intel OpenMP headers, the functions including `omp_get_level` can be referenced.

BTW, could you please explain why other OpenMP functions in the same file were not causing any compilation errors, but only `omp_get_level`?

**Comment by peterjc123** [comment]
Because the header provided by Microsoft is used, which contains some of the function declarations.

**Comment by peterjc123** [comment]
In C/C++, although the function may exist in an existing library(libiomp5md.lib in your case), you have to declare it before you can actually use it.

**Comment by imaginary-person** [comment]
> In C/C++, although the function may exist in an existing library(libiomp5md.lib in your case), you have to declare it before you can actually use it. Usually it is done in the header, right?

Yup, thanks! I got that from your previous comment
