### ISSUE TITLE
[complex] torch.polar accepts negative values for `abs` argument

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#52919]
```python
>>> abs_t = torch.tensor([-1., 2, -3])
>>> angle_t = torch.randn(3)
>>> torch.polar(abs_t, angle_t)
tensor([-0.7947-0.6070j,  1.2734-1.5422j, -2.6964+1.3151j])
```

It should error out if `abs<0`.

We should add checks in the following kernel

https://github.com/pytorch/pytorch/blob/bb34fd6191e0f2a31edc38e00d93a24d9da8c031/aten/src/ATen/native/cpu/ComplexKernel.cpp#L20-L22

https://github.com/pytorch/pytorch/blob/22a34bcf4e5eaa348f0117c414c3dd760ec64b13/aten/src/ATen/native/cuda/ComplexKernel.cu#L25-L26

cc @ezyang @anjali411 @dylanbespalko @mruberry @brianjo

**Comment by mruberry** [comment]
We should update the documentation of polar to reference how it's based on C++'s polar (https://en.cppreference.com/w/cpp/numeric/complex/polar) and not Python's cmath.polar (https://docs.python.org/3/library/cmath.html#cmath.polar) or SciPy's linalg.polar (https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.polar.html). It's unfortunate the same name is used for different functions.

What does C++'s polar do when given negative numbers? The reference just says the behavior is undefined. Adding checks seems OK as long as it doesn't harm performance.

**Comment by anjali411** [comment]
@kshitij12345 are you still planning to work on this?

**Comment by anjali411** [comment]
> What does C++'s polar do when given negative numbers? The reference just says the behavior is undefined. 

C++ doesn't error out and just outputs `(r*cosθ, r*sinθ)`:

```
int main()
{
    constexpr auto π_2 {std::numbers::pi / 2.0};
    std::cout<<std::polar(-2.0, π_2);
}
```

Output: `(-1.22465e-16,-2)`

> Adding checks seems OK as long as it doesn't harm performance.

yeah

**Comment by NivekT** [comment]
Do we still want to add checks and prevent negative values as inputs for `abs`? Or should we follow C++'s implementation and allow them?

**Comment by mruberry** [comment]
> @mruberry @anjali411 Do we still want to add checks and prevent negative values as input argument? Or should we follow C++'s implementation and allow them (as well as editing the doc to state that)?

Checking for negative values would be tricky on CUDA. On CPU it's straightforward but you'd need to validate there wasn't a perf impact for doing so. I'd recommend just documenting that the input is not validated (users can validate the input themselves if they care to).
