### ISSUE TITLE
profile pure C++ process 

### ISSUE THREAD

**Issue by cshreyastech** [pytorch/pytorch#52936]
## 🚀 Feature
This is with respect to the discussion in Pytorch Slack discussion about the new PyTorch profiler in the nightly.

Do you intend to profile pure C++ process and see aten operator stats and GPU kernel stats? (or Java?)

Seems like its not supported at the movement. This is for tracking purpose
## Motivation

I am working on DRL research using libtorch. Profiling feature to support pure C++ process would be very helpful.

## Pitch
It would be helpful to have the profiling engine by next couple of months

## Alternatives
n/a

## Additional context
To be clear, this is the feature I would like to get supported for pure C++ process

_Copy paste from Slack discussion_
What’s PyTorch Profiler?
It’s an evolution of PyTorch autograd profiler with new CUDA kernel aware profiling engine and built-in Tensorboard plugin for visualizations.
How can I try it out?
1. Install PyTorch nightly.
2. Install Tensorboard plugin (and Tensorboard)
pip install tensorboard
pip install -i https://test.pypi.org/simple/ tensorboard-plugin-torch-profiler
 Run model training with profiling enabled. Here is sample resnet50 model.
 4.  Launch Tensorboard
tensorboard --logdir=./samples
 5.  Open your browser on the Tensorboard port, e.g. http://localhost:6006

cc @jbschlosser @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @yf225 @glaringlee

**Comment by glaringlee** [comment]
cc @ngimel @ilia-cher

**Comment by xingchensong** [comment]
Hi team, any progress?

**Comment by aaronenyeshi** [comment]
Yes, we support profiling a pure C++ process. For example, you can use these C++ functions:
```cpp
#include <kineto/libkineto/include/libkineto.h>

void some_function(bool useCuda) {
  using namespace torch::autograd::profiler;
  ProfilerConfig cfg{
    ProfilerState::KINETO,
      false,
      false,
      false,
      false,
      false};
  std::set<torch::autograd::profiler::ActivityType> activities{torch::autograd::profiler::ActivityType::CPU};
  if (useCuda) {
    activities.insert(torch::autograd::profiler::ActivityType::CUDA);
  }
  prepareProfiler(cfg, activities);
  enableProfiler(cfg, activities);
  runTorchWorkload(useCuda);
  auto result = disableProfiler();
  result->save("./some_local_file.json");
}
```
Closing this issue, as it is supported.
