### ISSUE TITLE
PC running out of RAM when building Pytorch from source

### ISSUE THREAD

**Issue by vascoferreira25** [pytorch/pytorch#5295]
OS: Manjaro Linux 17.1.5 64bit
CPU: Intel Pentium P6000, 1.87Gh x 2
RAM: 3.66 (4 Gb)
GPU: None
GCC: gcc (GCC) 7.3.0

When installing Pytorch from source I've ran out of RAM and computer freezes. I need to install Pytorch from source because I can't run any script because it raises the "Illegal instruction (core dumped)" error.
I can't tell you more than this because everytime I've ran the commands to install Pytorch, my PC froze and I had to restart the computer by pressing the button.

This is what I did to install Pytorch from source:
- git clone --recursive https://github.com/pytorch/pytorch
- export CMAKE_PREFIX_PATH="/home/crow/anaconda3/"
- export NO_CUDA=1
- python setup.py install

What should I do to install Pytorch?

**Comment by apaszke** [comment]
Please pull the current master and run `MAX_JOBS=1 python setup.py install`

**Comment by vascoferreira25** [comment]
Should I use `export MAX_JOBS=1` or just  use `MAX_JOBS=1 python setup.py install` in command line?

**Comment by apaszke** [comment]
Both are fine. The second one will set it locally for this command only.

**Comment by vascoferreira25** [comment]
![img_20180218_220015_1](https://user-images.githubusercontent.com/9872065/36357651-f4b53042-14f8-11e8-9d36-b5fe8bc3c014.jpg)

@apaszke It froze again. This time I took a photo to show what happened. It used 2.5gb of RAM and my computer stopped working.

**Comment by apaszke** [comment]
Can you paste your [`dmesg` log from before a crash](https://unix.stackexchange.com/questions/181067/how-to-read-dmesg-from-previous-session-dmesg-0) to a GitHub gist or look for recent entries that could be relevant?

**Comment by vascoferreira25** [comment]
The only way I have to do this is to crash the PC again, but I can't use the `dmesg` command at that time as the computer froze.

**Comment by vascoferreira25** [comment]
@apaszke this is the last thing recorded on the journal of the last boot: [journalctl_last_boot](https://gist.github.com/vascoferreira25/6bec78857330e05d3b1e467ed52245e4#file-journalctl_last_boot)

**Comment by apaszke** [comment]
Yes I know. That's why I linked this StackExchange post, because it points to a few locations where the kernel log from previous runs is usually cached

**Comment by vascoferreira25** [comment]
@apaszke this is the log I have: [journalctl_log](https://gist.github.com/vascoferreira25/2e0d79b74f00e910d5bbcaa27368324a#file-journalctl_log) After those I have lots of errors of create_ap (service which I use to create a hotspot) but I believe that are not relevant for this case.

**Comment by apaszke** [comment]
[These parts are worrying](https://gist.github.com/vascoferreira25/2e0d79b74f00e910d5bbcaa27368324a#file-journalctl_log-L10). It looks like CMake, or some build artifacts contain instructions that your CPU can't handle, but I have no idea why can that cause a complete hang. Tbh I don't really know how to debug this further

**Comment by vascoferreira25** [comment]
Maybe it's because my CPU is too old. Thank you for your help.

**Comment by botcs** [comment]
checking out v0.3.0 where MAX_JOBS flag is set at some point in setup.py parallelCCompile however takes no effect... and no matter what, the build always fails at that point.
