### ISSUE TITLE
Pytorch made many process..

### ISSUE THREAD

**Issue by iamshlee** [pytorch/pytorch#52967]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

I was executing the pytorch at two system, one is RTX2080ti*8 and other is DGX station 4 V100.

I was executing the imagenet examples, and Profiling about it.

It was on the RTX 2080Ti*8 server
![image](https://user-images.githubusercontent.com/44716037/109381640-e0a7b880-791e-11eb-8c96-75155980c3be.png)

and It was on the DGX station V100 * 4.
![image](https://user-images.githubusercontent.com/44716037/109381652-f3ba8880-791e-11eb-972e-b3a493beddf2.png)

I was running the same imagenet on the same container. And they have different Driver version, but all of the other things are same specification.

I expected on DGX station to make the 5 process.
But It was spawning the so may process, So i can't get the useful profiling data..

Thanks

**Comment by skyline75489** [comment]
Just curious, why would you expect `DGX station to make the 5 process`? Based on the configuration, you might spawn DataLoader process + Training process, which could very likely leads to more than 5 process. Of course not as many as 104. I don't know where this number come from based on the screenshot you provided.

**Comment by iamshlee** [comment]
hi @skyline75489, Thanks to reply.
If you see the first picture that was in RTX2080Ti*8 interconnected using PCIE. It created just 9 processes.
But DGX station of 4 V100 GPUs, They show like that number..
![image](https://user-images.githubusercontent.com/44716037/109388250-5294f780-7949-11eb-8181-6c28c2832038.png)
This is full screenshot from the nsight system.. I understood the 4 ptyhon process of each GPUs, but I cannot understand the below python process.

Thanks.

**Comment by iamshlee** [comment]
I'm adding more, I running the pytorch imagenet from examples. And i choose the resnet50.
