### ISSUE TITLE
[nnc] Add ability to inspect generated code

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#52974]
Right now the only way to see the generated assembly/cuda/llvm ir is by setting PYTORCH_JIT_LOG_LEVEL in the environment, which is kind of inconvenient in a lot of use cases.  It’d be nice to be able to get a handle to the TensorExprGroup node and tell it to dump the code.

cc @gmagogsfm

**Comment by ZolotukhinM** [comment]
Could you please expand on how exactly you'd like to use that?

If it's in C++ code, you could just print the stmt:
```
LoopNest l(...);
// do stuff with l
std::cerr << *l.root_stmt() << "\n";
```

`TensorExprGroup` nodes are only created in the fusion pass, which I suspect you're not using. But if you are, then we should fill in the `getCodeText` method for our codegens, which is accesible through the `TensorExprKernel` object:
https://github.com/pytorch/pytorch/blob/8870c391e9fbb023ef2319f4a27b8020d353a79a/torch/csrc/jit/tensorexpr/kernel.h#L34-L36

**Comment by bertmaher** [comment]
Oh yeah so getCodeText is exactly what I want, I didn't know we had that.  For the LLVM backend I'd like an LL flavor to get llvm IR, as well as an ASM flavor to get the generated assembly code.

For my purposes right now it's fine to have it on the C++ CodeGen object like it is, but it would be super-extra awesome to have it exposed up to python in some fashion.  I don't know the jit python APIs well, but it seems like you should be able to plumb through something like graph.node.get_code_text("asm") (I hope?)
