### ISSUE TITLE
INTERNAL ASSERT FAILED at torch.count_nonzero() for Tensor with requires_grad=True

### ISSUE THREAD

**Issue by Maicon-Moreira** [pytorch/pytorch#52988]
## To Reproduce

`T.count_nonzero(T.tensor([0, 1, 2], dtype=T.float, requires_grad=True))`

RuntimeError                              Traceback (most recent call last)
<ipython-input-155-8f3c0012dd5a> in <module>
----> 1 T.count_nonzero(T.tensor([0, 1, 2], dtype=T.float, requires_grad=True))

RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "..\\torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 

## Expected behavior

> tensor(2)

Just like: `T.count_nonzero(T.tensor([0, 1, 2], dtype=T.float, requires_grad=False))`

## Environment

PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.1+cpu
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cpu
[conda] Could not collect

cc @mruberry @rgommers @heitorschueroff

**Comment by H-Huang** [comment]
I can't repro this in the latest version. Maybe specific to 1.7.1?

**Comment by mruberry** [comment]
Also no repro for me on nightly. Looks like this may have been fixed. @Maicon-Moreira, would you try this on nightly (or 1.8 when it comes out soon) and reopen if you're still seeing this issue?
