### ISSUE TITLE
Actual gpu memory usage is much more than torchsummary estimated

### ISSUE THREAD

**Issue by raisinglc** [pytorch/pytorch#53005]
I built a resnet base network. torchsummary estimated the total size of my model is 1847 MB, but it took 4000 MB GPU memory when I run test inference steps.  However, the memory usage dropped to 1900 MB after I added some layers to the model. The memory usage raised to 3400 MB(sometimes 4100 MB) when I dropped these layers. 
**It is very confusing, why less parameters takes more memory.**

In addition, when I used libtorch to load the same saved .pt model, it took more memory and time on inference than pytorch. If Libtorch and Pytorch load the same C backend, I think they should perform very the same or libtorch perform better.

cc @yf225 @glaringlee

**Comment by H-Huang** [comment]
Thank you for bringing up these issues! I think the first point would be a better question to ask on the torchsummary/torch info repo. 

As for libtorch taking up more memory/time, do you have a reproduction for that? Please feel free to reraise the issue with the example code.

**Comment by raisinglc** [comment]
> Thank you for bringing up these issues! I think the first point would be a better question to ask on the torchsummary/torch info repo.
> 
> As for libtorch taking up more memory/time, do you have a reproduction for that? Please feel free to reraise the issue with the example code.

Thank you for your reply and suggestion. I have merged this issue to my other opened issue with my example code.
