### ISSUE TITLE
[nnc] unroll/flatten loops with non literal constant bounds

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#53000]
Currently we require a literal constant, but fail on something like (16/4) which is trivially simplified. 

cc @gmagogsfm

**Comment by navahgar** [comment]
It looks like this already works for Flatten. Here is one example:
```{
  for (int i = 0; i < 15 - 5; i++) {
    for (int j = 0; j < 20 / 4; j++) {
      A[i, j] = i * j;
    }
  }
}
```
flattens to:
```
for (int i_flat = 0; i_flat < 50; i_flat++) {
  A[i_flat / 5, i_flat % 5] = (i_flat / 5) * (i_flat % 5);
}

But doesn't work for unroll. Sent a PR to fix unroll.

**Comment by ZolotukhinM** [comment]
Should we just run `simplify` at the end of each transform?

**Comment by navahgar** [comment]
> Should we just run simplify at the end of each transform?

Good point. That should mostly work. For tests, we might have to run `simplify` before the transform though. 

If compile time becomes a bottleneck in future, we might have to consider other options. (I am not sure how much time `simplify` takes now, but would be good to keep that in mind)>

**Comment by bertmaher** [comment]
> It looks like this already works for Flatten. 
Yeah sorry I meant "flatten" as in loop flattening not axis flattening.  Terminology is hard :-(
