### ISSUE TITLE
How can I obtain the center and radius of the smallest circumscribed circle corresponding to a certain categorical value part from a tensor that is the output of the segmentation model?

### ISSUE THREAD

**Issue by afpapqy** [pytorch/pytorch#53007]
### As the title descripted,this problem has bothered me for a long time:weary:
I got an output tensor of a sematic segementation model whose shape is:
    size(0):1,   size(1):544,    size(2):960;
Each value of the tensor,for example, tensor[0][255][296] or tensor[0][155][88] is taken from 0,1,2.
This segementation model divides the entire picture into three categories.
value 0 represents type0, and so on.
Now I want to calculate the Minimum circumscribed circle of the area represented by type2. What shou I do?
I found a feasible way before---to loop through the tensor,and save the coordinates of type2,then use the opencv interface 'cv::minEnclosingCircle' to get the center and radius,however this method causes way too much time....up to near 4 seconds per frame...
However, it is actually required that this step does not exceed 0.01s per frame....
This is my code:
```C++
	for (j = 0; j < 544; j++) {//size(1):height
		for (k = 0; k < 960; k++) {//size(2)width
			value = tensor[0][j][k].item().to<int>();
			if (value == 2) {
				Point p(k, j);
				points.push_back(p);
			}
		}
	}

	Point2f circleCenter;
	float circleRadius;
	cv::minEnclosingCircle(points, circleCenter, circleRadius);
```
Can you help me?
:broken_heart::broken_heart::broken_heart:
Environment:
Libtorch1.7
Win10

**Comment by H-Huang** [comment]
This question is a better fit for [pytorch forums](https://discuss.pytorch.org/), not pytorch issues
