### ISSUE TITLE
Runtime Error with DataLoader: exited unexpectedly

### ISSUE THREAD

**Issue by mxlei01** [pytorch/pytorch#5301]
Hi All,

I have a DataLoader that loads a line from a file with Numpy, then convert it to a torch Tensor, and whenever I run this with more than 1 workers, it gives me an error:

`RuntimeError: DataLoader worker (pid 30141) exited unexpectedly with exit code 1.`

However, whenever I run it with 0 workers, it works.

Is there some sort of logs that shows why the worker exited unexpectedly?

Still have around 10gb of gpu memory, and gpu utilization of 0% when this happens.

But If I use CPU only, then this I can have multiple workers successfully.

Here's what I do:

```
def get_line(filename, index):
    with open(filename, "rb") as f:
        for count, line in enumerate(f):
            if count == index:
                return line
    
def count_line(filename):
    with open(filename, "rb") as f:
        size = 0
        for count, _ in enumerate(f):
            size = count
        return size

class LineDatasetDnn(Dataset):
    def __init__(self, features_filename, labels_filename):
        self.features_filename = features_filename
        self.labels_filename = labels_filename
        self.lines = count_line(self.features_filename)
    
    def __getitem__(self, idx):
        feature_line = get_line(self.features_filename, idx)
        feature = torch.from_numpy(np.fromstring(feature_line, dtype=float, sep=' ')).cuda().float() if torch.cuda.is_available() else torch.from_numpy(np.fromstring(feature_line, dtype=float, sep=' ')).float()
        
        label_line = get_line(self.labels_filename, idx)
        label = torch.Tensor(np.fromstring(label_line, dtype=float, sep=' ')) if torch.cuda.is_available() else torch.FloatTensor(np.fromstring(label_line, dtype=float, sep=' '))

        return feature, label
        
    def __len__(self):
        return self.lines

def get_concat_dataset_dnn(data_type):
    files = sorted(os.listdir(f"./ds_data/txt/dnn/{data_type}/input"))
    datasets = [LineDatasetDnn(f"./ds_data/txt/dnn/{data_type}/input/{file}",
                               f"./ds_data/txt/dnn/{data_type}/output/{file}")
                for file in files]
    return data.ConcatDataset(datasets)

for feature, label in data.DataLoader(get_concat_dataset_dnn("train"),
                                              batch_size=dnn_minibatch_size, shuffle=True, collate_fn=transform_variable_dnn,
                                              num_workers=2, pin_memory=pin_memory):
```

**Comment by mxlei01** [comment]
Actually I noticed if I use CPU only, and if I use "spawn" instead of "fork" I would get the same error.

**Comment by SsnL** [comment]
Are you sure that `RuntimeError: DataLoader worker (pid 30141) exited unexpectedly with exit code 1.` is the only error you get? You should be getting an error from the worker process as well as an error from the main loader process (the one you posted). My guess is that the one you get from the worker is something related to not properly wrapping things in `if __name__ == '__main__':` with `spawn`.

**Comment by mxlei01** [comment]
This is all of the output:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-56-bea3acbf0a84> in <module>()
     32         for feature, label in data.DataLoader(get_concat_dataset_dnn("train"),
     33                                               batch_size=dnn_minibatch_size, shuffle=True, collate_fn=transform_variable_dnn,
---> 34                                               num_workers=1, pin_memory=pin_memory):
     35             # Step 1. Pytorch accumulates gradients, need to clear them out before each instance.
     36             dnn.zero_grad()

~/python3_virtualenv/python3_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    273         while True:
    274             assert (not self.shutdown and self.batches_outstanding > 0)
--> 275             idx, batch = self._get_batch()
    276             self.batches_outstanding -= 1
    277             if idx != self.rcvd_idx:

~/python3_virtualenv/python3_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _get_batch(self)
    252                 raise RuntimeError('DataLoader timed out after {} seconds'.format(self.timeout))
    253         else:
--> 254             return self.data_queue.get()
    255 
    256     def __next__(self):

/usr/lib/python3.6/queue.py in get(self, block, timeout)
    162             elif timeout is None:
    163                 while not self._qsize():
--> 164                     self.not_empty.wait()
    165             elif timeout < 0:
    166                 raise ValueError("'timeout' must be a non-negative number")

/usr/lib/python3.6/threading.py in wait(self, timeout)
    293         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    294             if timeout is None:
--> 295                 waiter.acquire()
    296                 gotit = True
    297             else:

~/python3_virtualenv/python3_env/lib/python3.6/site-packages/torch/utils/data/dataloader.py in handler(signum, frame)
    173         # This following call uses `waitid` with WNOHANG from C side. Therefore,
    174         # Python can still get and update the process status successfully.
--> 175         _error_if_any_worker_fails()
    176         if previous_handler is not None:
    177             previous_handler(signum, frame)

RuntimeError: DataLoader worker (pid 39637) exited unexpectedly with exit code 1.
```

The amount of data in each line is less than 1KB.

**Comment by mxlei01** [comment]
The PyTorch version: 0.3.1.

Previous versions of PyTorch just hangs forever.

**Comment by mxlei01** [comment]
I also tried wrapping everything with if __name__ == '__main__', and it seems to fail too.

**Comment by mxlei01** [comment]
Alright, I think I got it fixed.

Basically somehow inside Jupyter Notebooks the errors for the loaders aren't appearing.

But If I download the notebooks as a .py file and execute it, then it will tell you what errors were happening.

**Comment by Aurora11111** [comment]
@mxlei01 I meet the same problem ,can you share the solution with me?

**Comment by panoble2017** [comment]
I also have the same problem.  Can you share the solution with me?

**Comment by Beastmaster** [comment]
I got an ugly solution. 
`
def create_dataloader():
      # some function to create a dataloader
      return dataloader

# in main function
dataloader = create_dataloader()
dataloader_iter = iter(dataloader)
for step in range(len(dataloader)):
  while(true):
     try:
        data = next(dataloader_iter)
     except:
        dataloader = create_dataloader()
        dataloader_iter = iter(dataloader)

   #perform training
`

**Comment by liluxuan1997** [comment]
I run the code with .py file and also get the problem. Have anyone fixed it?

**Comment by panoble2017** [comment]
In GPU mode (this works)..... 

dataset = UP_Dataset()
train_loader = DataLoader(dataset=dataset,
                          batch_size=100,
                          shuffle=True,
                          num_workers=0)                              # change num_workers=0

**Comment by Jnasic** [comment]
I get to know that I was calling exit() in my code. After removing it, everything worked fine

**Comment by Codersadis** [comment]
> I get to know that I was calling exit() in my code. After removing it, everything worked fine

change the num_works to 0 works for me.
Thx!

**Comment by Codersadis** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

Change the num_workers to 0 works for me.
Thx!

**Comment by XHalliwell** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

thanks! your method can solve my problem

**Comment by mbmhm123** [comment]
num_of_worker=0 is too late.

i work on img processing with unet. epoch num 100 takes 5 hours. any other soluton?

**Comment by mgraczyk** [comment]
Looks like torch is trying to call `cudaGetDevice` on a forked child process (data loader worker) in `pytorch/torch/csrc/autograd/profiler_cuda.cpp`. The worker throws a runtime error and brings down the process tree. One simple solution that may work is to have the profiler check its pid and stop if the pid changes. Another option is to use some post-fork registration that would be called or signaled in the data loader workers, but that would need to be added anywhere pytorch forks.

**Comment by RashaFr** [comment]
> num_of_worker=0 is too late.
> 
> i work on img processing with unet. epoch num 100 takes 5 hours. any other soluton?

You can start by reducing num_workers till it works. For me, it worked with num-workes=2.

**Comment by fahad-git** [comment]
> > In GPU mode (this works).....
> > dataset = UP_Dataset()
> > train_loader = DataLoader(dataset=dataset,
> > batch_size=100,
> > shuffle=True,
> > num_workers=0) # change num_workers=0
> 
> Change the num_workers to 0 works for me.
> Thx!

`num_workers=0` It worked for me too thanks.

**Comment by deepak121993** [comment]
num_workers = 0, It worked for me as well, but not able to figure out the actual issue. If somebody could explain?

**Comment by MengLok** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

It works for me as well. Thanks!

**Comment by sstary** [comment]
> > In GPU mode (this works).....
> > dataset = UP_Dataset()
> > train_loader = DataLoader(dataset=dataset,
> > batch_size=100,
> > shuffle=True,
> > num_workers=0) # change num_workers=0
> 
> Change the num_workers to 0 works for me.
> Thx!

I forget it again.... num_workers = 0 in GPU ...

**Comment by anantzoid** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

Wouldn't this disable you from churning out maximum CPU utilization, thus making your training slower?

**Comment by timothyjlaurent** [comment]
Seems that the training in my case is about half as fast with num_workers=0

**Comment by P1eter** [comment]
I had this problem too. For me the error seems to happen only when the computer memory runs out (looking at `htop` or anything similar). The slowdown of the training is due to the dataloader becoming the bottleneck in the training process, so you still want as many workers as possible.

If you tune the number of workers in the dataloader to the available memory (by trial and error), you can find an optimal number of workers for your available memory.

Hope this helps.

**Comment by hibit-at** [comment]
> num_workers = 0

worked to me. it erased Runtime Error. thanks.
but instead, CUDA out of memory has appeared regardless of batchsize.

in batch_size = 100
> RuntimeError: CUDA out of memory. Tried to allocate 4.22 GiB (GPU 0; 8.00 GiB total capacity; 5.02 GiB already allocated; 820.89 MiB free; 5.14 GiB reserved in total by PyTorch)

in batch_size = 10
> RuntimeError: CUDA out of memory. Tried to allocate 2.81 GiB (GPU 0; 8.00 GiB total capacity; 3.57 GiB already allocated; 2.61 GiB free; 3.66 GiB reserved in total by PyTorch)

in batch_size = 1
> RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 5.66 GiB already allocated; 79.25 MiB free; 5.82 GiB reserved in total by PyTorch)

anyone can help?

**Comment by hjc3613** [comment]
I got the same problem, the key is that you can define the dataloaer in any location, but should use the iter(dataloader) in the if __name__=='__main__':
    data_iter = iter(dataloader)
    data = data_iter.next()

**Comment by LunarSun** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

 change num_workers=0 works

**Comment by Jimut123** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

This works for me too!

**Comment by Gitgigabyte** [comment]
Is there any other solutions? set num_workers = 0 is just too slow

**Comment by bernakabadayi** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

in cpu mode, changing num_workers=0 also worked

**Comment by zaccharieramzi** [comment]
I had a similar error with my datasets.
The problem was that I had incorrect dimensions at some point which made some of the tensors become huge, so they were overfilling the memory.

Correcting the dimensions solved this problem.

**Comment by sarvghotra** [comment]
> 
> 
> I got the same problem, the key is that you can define the dataloaer in any location, but should use the iter(dataloader) in the if **name**=='**main**':
> data_iter = iter(dataloader)
> data = data_iter.next()

Worked for me.

**Comment by MiladInk** [comment]
I am getting the same error. setting num_workers=0 works but it is making the training slower. I am also experiencing this in a jupyter notebook. Is there any other solution?

**Comment by srianumakonda** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset()
> train_loader = DataLoader(dataset=dataset,
> batch_size=100,
> shuffle=True,
> num_workers=0) # change num_workers=0

Worked for me. Thanks a lot!

**Comment by kasrasehat** [comment]
> 
> 
> I am getting the same error. setting num_workers=0 works but it is making the training slower. I am also experiencing this in a jupyter notebook. Is there any other solution?

you can use if --name-- = '--main--' at the beginning of your code

**Comment by jaewoohwang** [comment]
Thanks a lot  :)

**Comment by lsg921203** [comment]
> I got an ugly solution.
> 
> ```
> def create_dataloader():
>       # some function to create a dataloader
>       return dataloader
> 
> # in main function
> dataloader = create_dataloader()
> dataloader_iter = iter(dataloader)
> for step in range(len(dataloader)):
>   while(true):
>      try:
>         data = next(dataloader_iter)
>      except:
>         dataloader = create_dataloader()
>         dataloader_iter = iter(dataloader)
> 
>    #perform training
> ```

work for me!! thank you

**Comment by Maria-UET** [comment]
I was having the same issue in Jupyter notebook but then realized that it is not due to the num_workers, the program exits due to any other errors but the Jupyter notebook will only give this error message regardless:

` RuntimeError: DataLoader worker (pid 39637) exited unexpectedly with exit code 1`

To find the actual error, see the CMD window running the Jupyter notebook

**Comment by LunarSun** [comment]
已收到您的来信，稍后会仔细阅读，谢谢。祝好！

**Comment by gjegoj** [comment]
pin_memory=False worked for me.

**Comment by AminJun** [comment]
I also tried `pin_memory=False`, but it does not seem to solve the problem.

**Comment by LunarSun** [comment]
已收到您的来信，稍后会仔细阅读，谢谢。祝好！

**Comment by 94kiki** [comment]
> > In GPU mode (this works).....
> > dataset = UP_Dataset()
> > train_loader = DataLoader(dataset=dataset,
> > batch_size=100,
> > shuffle=True,
> > num_workers=0) # change num_workers=0
> 
> Change the num_workers to 0 works for me. Thx

works for me, thanks

**Comment by LunarSun** [comment]
已收到您的来信，稍后会仔细阅读，谢谢。祝好！

**Comment by TashinAhmed** [comment]
> In GPU mode (this works).....
> 
> dataset = UP_Dataset() train_loader = DataLoader(dataset=dataset, batch_size=100, shuffle=True, num_workers=0) # change num_workers=0

0 worked for me...

**Comment by LunarSun** [comment]
已收到您的来信，稍后会仔细阅读，谢谢。祝好！

**Comment by Arcaneing** [comment]
> I also have the same problem. Can you share the solution with me?

may need run it in main function i think

**Comment by lsg921203** [comment]
Sorry i don't have code now.
I just separate dataset

**Comment by zhiyuan-zhang0206** [comment]
For me, I tried setting num_workers=0, not using vscode python debug extension, pin_memory=False, and still not working. But after running:
pkill -9 python
everything works fine, num_workers, debugger, pin_memory can be set whatever I want.

**Comment by hadighahroudi** [comment]
This is my system config:
Processor: 12th Gen Intel(R) Core(TM) i7-12700K
RAM: 32.0 GB
GPU: RTX 3090
OS: Windows 11 Pro

I ran into this issue while setting `num_workers = 10`. Lowering it to `num_workers = 8` resolved the problem. Also make sure to wrap your main training code in `if __name__ == "__main__"` guard.

**Comment by wangtianrui** [comment]
The main reason for my error here is that each dataset file consumes a lot of memory. For example, my information file is 16G, and 8 num_workers will consume 128G of memory, which exceeds my memory limit. So reducing num_worker or setting it to 0 can solve this problem. However, this will slow down the entire training. The best solution is to reduce the amount of information in the file. It is best to use int or string type variables as temporary indexes and do not load all the data at once.
