### ISSUE TITLE
`InverseBackward` on CUDA intermittently returns NaN values.

### ISSUE THREAD

**Issue by gauravmm** [pytorch/pytorch#53047]
## 🐛 Bug

`InverseBackward` on CUDA intermittently returns NaN values.

The same deterministic invocation of InverseBackward rarely returns `NaN` values when presented with a well-conditioned invertible matrix. This happens approximately 1 time out of every 1000 to 10,000 invocations, with both `float32` and `float64` types.  The same computation on a CPU always succeeds.

## To Reproduce

On a machine with:
 - Ubuntu 20.10
 - CUDA Version: 11.2
 - NVIDIA Driver Version: 460.32.03    
 - Torch: 1.7.1
 - Python: 3.8.7-final-0

Run [this](https://gist.github.com/gauravmm/f582de56dd777fdf90f8907d2adc0dd1) minimal example script, which repeatedly calls this function:
```
    def forward(self, theta):
        cos_theta = torch.cos(theta)

        H = torch.ones((len(theta), 2, 2), device=theta.device, dtype=theta.dtype)
        H[:,0,0] = 1.2
        H[:,0,1] = cos_theta
        H[:,1,0] = cos_theta
        H[:,1,1] = 0.01

        return torch.inverse(H)
```

Until `torch.autograd.grad((forward(...),), theta, ...)` returns a value containing `NaN`s.

The script repeats this up to 10,000 times for both CPU and CUDA devices, using both `float32` and `float64` data types. It uses Anomaly Detection mode to spot the introduction of `NaN` values.

On my machine, the output is:

```
test_inverse_nan_minimal.py:60: UserWarning: Anomaly Detection has been enabled. [OMITTED]
[W python_anomaly_mode.cpp:104] Warning: Error detected in InverseBackward. Traceback of forward cal
l that caused the error:                                                                            
  [LINES OMITTED]
  File "test_inverse_nan_minimal.py", line 21, in forward
    return torch.inverse(H)
 (function _print_stack)
Testing cuda:0, torch.float32: FAILED after 2312: Function 'InverseBackward' returned nan values in 
its 0th output.

[W python_anomaly_mode.cpp:104] Warning: Error detected in InverseBackward. Traceback of forward cal
l that caused the error:
  [LINES OMITTED]
  File "test_inverse_nan_minimal.py", line 21, in forward
    return torch.inverse(H)                                                                          (function _print_stack)
Testing cuda:0, torch.float64: FAILED after 28: Function 'InverseBackward' returned nan values in it
s 0th output.                                                                                       

Testing cpu, torch.float32: Passed 9999                                                             

Testing cpu, torch.float64: Passed 9999
```

`NaN` values are only ever detected in `InverseBackward`.

## Expected behavior

 1. Expected the backwards pass through the matrix inversion to always return the same value when performed with the same data type on the same device. 
 2. Expected the backwards pass to only return `NaN` values if the matrix is ill-conditioned or if the data type underflows/overflows.
 3. Expected the success or failure of the function to only depend on input, not some hidden state. 

## Environment

```
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] Could not collect
```

Note that Python was compiled locally using `pyenv`.
The script did not capture the information that: CUDA version is 11.2

## Additional context

The determinants of the sample matrix are about -0.99, and the condition numbers are about 3.48. Both sample matrices are sufficiently well-conditioned that this should not be a problem.

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by xwang233** [comment]
Thanks for the report. Do you know the value of `len(theta)`, or the batch_size of your batched matrices?

**Comment by gauravmm** [comment]
The same bug is seen with `len(theta)` having values 1, 2 (in sample script), 128, 256, and 512.

**Comment by xwang233** [comment]
There are known issues when `batch_size = 2` in 1.7.0 and 1.7.1 for cuda inverse forward, which was fixed now. I would suggest to use a later version (nightly, or next release).

If you have to use 1.7.x, try to set environment variable `CUDA_LAUNCH_BLOCKING=1`. However, this may negatively affect the performance.

**Comment by gauravmm** [comment]
Thanks for the help! I re-ran the minimal example:

 - On Torch 1.7.1, I cannot reproduce the bug with `batch_size`s  having values 1, 3, 4, 8, and 113.
 - On Torch 1.9.0.dev20210217+cu112, I cannot reproduce the bug with `batch_size = 2`.

The bug is probably fixed. I will run a longer-form test and report back in the next day or so.

**Comment by gauravmm** [comment]
I ran a much longer program with about 10^6 invocations ready to cause this bug, and did not observe this failure mode. I'm happy to call this fixed!
