### ISSUE TITLE
Add compare_set for HashStore and FileStore

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#53062]
### Improvement
Add functionality for `compare_set` to [HashStore](https://pytorch.org/docs/master/distributed.html#torch.distributed.FileStore) and [FileStore](https://pytorch.org/docs/master/distributed.html#torch.distributed.FileStore) to have achieve parity with TCPStore.

### Background
We [recently added a method to TCPStore](https://github.com/pytorch/pytorch/commit/97e35858ece696a0627b58c5945eed98bd47a41a) for `compare_set(key, current_value, new_value)`. The logic for it is as follows:

if key doesn't exist: return current_value
if get(key) == current_value: update key to new_value and return new_value
if get(key) != current_value: do not update key, return get(key)

This should also be added to the other two store types, HashStore and FileStore.

**Implementation caveat**: Since `store` is used by multiple processes, implementing compareSet by internally calling `get` followed by `set` will not suffice due to potential race conditions. It is fine to use the logic of the two functions, but they must be combined so that compareSet is an atomic operation.

Pybind definition:
https://github.com/pytorch/pytorch/blob/b3bf08e67f5cf29cbfd197e3c9e9a2f45e0b5c9d/torch/csrc/distributed/c10d/init.cpp#L424-L461

Relevant files:
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/HashStore.cpp
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/FileStore.cpp
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/TCPStore.cpp

### Testing

Testing should be done for both python and C++ APIs

#### Python:
https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d.py

Run with `python test/distributed/test_c10d.py TCPStoreTest.test_compare_set`(it should be under HashStoreTest and FileStoreTest)

#### C++:
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/test/HashStoreTest.cpp
https://github.com/pytorch/pytorch/blob/master/torch/lib/c10d/test/FileStoreTest.cpp

Run with `build/bin/HashStoreTest` and `build/bin/FileStoreTest`

**Comment by tmliew** [comment]
Working on a PR for this

**Comment by siva1007** [comment]
@H-Huang I started exploring this issue to understand more about the pytorch codebase but this looked like a straight forward fix. So I went ahead and raised a PR. (https://github.com/pytorch/pytorch/pull/53475). Should we also add tests in python for the same?

**Comment by siva1007** [comment]
> Working on a PR for this

@tmliew My sincere apologies, I did not notice your comment until now. I hope I have not duplicated your efforts here. Please feel free to collaborate on this PR and apologies once again for my mistake.

**Comment by tmliew** [comment]
Hi @H-Huang, see my draft PR #53573.
