### ISSUE TITLE
Bug in pad_packed_sequence

### ISSUE THREAD

**Issue by karanchahal** [pytorch/pytorch#5307]
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6
- CUDA/cuDNN version: 8
- GPU models and configuration: K80 (the one on google colab)

-Script for testing
 `       targets,pad_lengths = pack_padded_sequence(captions,lengths,batch_first=True) `
    `   targets = pad_packed_sequence((targets,pad_lengths),batch_first=True)[0]`
     `   outputs = pad_packed_sequence((outputs,pad_lengths),batch_first=True)[0]`

- I was trying to pad a packed sequence with the following code, but encountered an error saying that for the paddinglength required int but got float. The same code works on pytorch version 0.2.*

**Comment by apaszke** [comment]
Please provide us with a self-contained snippet we could use to reproduce the problem. In these 3 lines you're using a lot of variables that aren't defined here, and we don't know what they are
