### ISSUE TITLE
The Implementation of 'torch.optim.Rprop' is not efficient and the program will be stuck in DDP training.

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#53070]
PyTorch 1.5 with 4 Tesla T4 GPU.

The following code in Rprop is not efficient:
https://github.com/pytorch/pytorch/blob/e2462745ba9850c93987c252299848e8f60eb23d/torch/optim/rprop.py#L63
https://github.com/pytorch/pytorch/blob/e2462745ba9850c93987c252299848e8f60eb23d/torch/optim/rprop.py#L64
https://github.com/pytorch/pytorch/blob/e2462745ba9850c93987c252299848e8f60eb23d/torch/optim/rprop.py#L65

https://github.com/pytorch/pytorch/blob/e2462745ba9850c93987c252299848e8f60eb23d/torch/optim/rprop.py#L73

What's worse, when I train a model with Rprop in DDP mode, the program will be stuck in those operation:
```
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 256, in main
    process.wait()
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
```

cc @vincentqb @VitalyFedyunin @ngimel @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
@densechen Could you provide a repro script for the case when the program gets stuck with DDP?

**Comment by densechen** [comment]
Hey，@pritamdamania87，I think it is because the operation like X[X.eq(0)] = Y, which appears in an Optimzier step function caused this. In my experiments, any optimizer, whose step function contains those operations, will get stuck with DDP. If I change the operation to th.where() function, everything goes well.

**Comment by ngimel** [comment]
Likely because X[X.eq(0)] causes host-device synchronization in nonzero op. @densechen when you say it's an inefficient implementation, do you mean that calling `where` is faster even when ddp is not an issue?

**Comment by densechen** [comment]
@ngimel under no-DDP mode, i.e. train on single GPU, we could find that X[X.eq(0)] is slower than th.where in Rprop, but it still works. However, under DDP mode, 4 card in my case, I waited long time for this operation to be finished, yet failed. 
If I change to th.where operation, I can get the result in serval second.

**Comment by ngimel** [comment]
Should be fixed on master
