### ISSUE TITLE
rnn.py error 

### ISSUE THREAD

**Issue by gameking157** [pytorch/pytorch#5308]
GRU(**input_dim**,hidden_dim)

GRU(x),  if the dimension of x is not equal to **input_dim**, this error occurs

```
File "/home/wds/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wds/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 190, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/wds/.conda/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 141, in check_forward_args
    fn.input_size, input.size(-1)))
NameError: name 'fn' is not defined
```

- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda update
- Python version: 3.6.4
   cuda8.0.61_cudnn7.0.5_2

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by mruberry** [comment]
This error message has been corrected on recent PyTorch builds.
