### ISSUE TITLE
stft output shape not matched with what document described when center=False

### ISSUE THREAD

**Issue by yoyololicon** [pytorch/pytorch#53089]
Hi, I recently found that the shape of output from `torch.stft` is not matched with what I expected when setting `center` to `False` after reading the document.

Here's the code I use:
```python
>>> x = torch.randn(44100)
>>> s = torch.stft(x, 1024, win_length=1024, hop_length=256, return_complex=True, center=False)
>>> s.shape
torch.Size([513, 169])
```
The number of frame (the last dimension of `s`) is `floor((x.shape[0] - win_length) / hop_length) + 1`, which is ((44100 - 1024) // 256) + 1 = 169. Only `win_length` and `hop_length` would affect number of frames, `n_fft` is used only for zero-padding each frame, from my understanding.

But after I change `n_fft` to 2048:
```python
>>> s = torch.stft(x, 2048, win_length=1024, hop_length=256, return_complex=True, center=False)
>>> s.shape
torch.Size([1025, 165])
```
The number of frames change to 165.
If I inject `n_fft` instead of `win_length` into the above formula

((44100 - 2048) // 256) + 1 = 165 !

Seems like the internal implementation of `torch.stft` misused `n_fft` and `win_length` at some points.
I'm not sure whether it is a bug, or a desired behavior?

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @peterbell10 @walterddr

**Comment by yoyololicon** [comment]
Follow update:

I use `scipy.signal.stft` and do the same example, with parameters setted to have same behavior as `torch.stft`.

```python
>>> s = stft(x.numpy(), nperseg=1024, noverlap=1024 - 256, nfft=1024, boundary=None, padded=False)[-1]
>>> s.shape
(513, 169)
>>> s = stft(x.numpy(), nperseg=1024, noverlap=1024 - 256, nfft=2048, boundary=None, padded=False)[-1]
>>> s.shape
(1025, 169)
```
It gives the shape what I expected.

**Comment by yoyololicon** [comment]
cc @vincentqb

**Comment by zou3519** [comment]
Sounds like either a silent correctness issue or a problem with the docs. Tentatively marking as high-pri for potential silent correctness issue.

**Comment by mruberry** [comment]
@peterbell10, would you take a look?

**Comment by peterbell10** [comment]
I checked and this is equivalent to `librosa`'s behavior, so definitely intentional. Looking at the docs, it says this:

>If `win_length < n_fft` `window` window will be padded on both sides to length n_fft before being applied.

This makes sense to me, as it's the same as taking the windowed input and then taking the fft with `n=n_fft`.

**Comment by mruberry** [comment]
Thanks for investigating @peterbell10. @yoyololicon, seems like the issue here is confusion over what stft function is implemented? Would you like to change this issue into a request for stft like that implemented by SciPy?

**Comment by yoyololicon** [comment]
> I checked and this is equivalent to `librosa`'s behavior, so definitely intentional. Looking at the docs, it says this:
> 
> > If `win_length < n_fft` `window` window will be padded on both sides to length n_fft before being applied.
> 
> This makes sense to me, as it's like taking the windowed input and then taking the fft with `n=n_fft`.

I see, so the window size will always be `n_fft` . If this is intentional then I have no problem.
Thanks for taking time and clearing things out @peterbell10 @mruberry @zou3519.
