### ISSUE TITLE
Slow optimization with large vocabulary size embedding matrices

### ISSUE THREAD

**Issue by ngarneau** [pytorch/pytorch#5309]
Hey there,

I am experiencing some issues with larger embedding matrices (500K) which takes a long time to optimize. I ran a couple of test where you can see some results in this [gist](https://gist.github.com/ngarneau/f66829cc4c1ff99beb9a2b7c206bf6bd)

I did some experiment on CPU and GPU and we had same conclusions.
My OS is Linux Ubuntu 17.04
Python 3.6.3
Pytorch version: 0.3.0.post4 installed with pip
Batch size of 1, embedding size of 100

Having 500K vocabulary in NLP is a common thing and I wish it could scale to this point.

Many thanks,
Nicolas

**Comment by SsnL** [comment]
With large embedding matrices, we recommend using the version with sparse gradients. Simply setting `sparse=True` when constructing your embedding layer should work.

**Comment by ngarneau** [comment]
It does in fact help a lot using sparse=True, thanks!

**Comment by SsnL** [comment]
Glad to know. Could you close the issue please? :)

**Comment by leobitz** [comment]
> With large embedding matrices, we recommend using the version with sparse gradients. Simply setting `sparse=True` when constructing your embedding layer should work.

How about for the C++ class?

**Comment by ngarneau** [comment]
I don't know what is your point with using the C++ class, we are in the context of using Pytorch, in python code.
