### ISSUE TITLE
How to compile torch/lib/c10d/ProcessGroupNCCL.cpp

### ISSUE THREAD

**Issue by 1013801464** [pytorch/pytorch#53101]
I want to modify `ProcessGroupNCCL.cpp` to add some print statements, but I don't know how to recompile this file.

It is located at [https://github.com/pytorch/pytorch/tree/v1.7.1/torch/lib/c10d](https://github.com/pytorch/pytorch/tree/v1.7.1/torch/lib/c10d).

I'm using pytorch 1.7.1 installed by anaconda.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
You can find instructions to build PyTorch from source here: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#developing-pytorch.

**Comment by 1013801464** [comment]
> You can find instructions to build PyTorch from source here: https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#developing-pytorch.

How to build pytorch on one device and install it on another device? (both centos 7) 

I didn't find solutions in that document.
