### ISSUE TITLE
RuntimeError: No rendezvous handler for env://

### ISSUE THREAD

**Issue by Lookforworld** [pytorch/pytorch#53135]
### When I  using torch.distributed.init_process_group(), I got an error... （win10，python3.8.3）
In my code:
        torch.distributed.init_process_group(backend=dist_backend,
                                             timeout=timeout,
                                             init_method=init_method,
                                             )
The error:

Traceback (most recent call last):
File "train.py", line 299, in
torch.distributed.init_process_group(backend='nccl',
File "C:\Users\korin\anaconda3\envs\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 433, in init_process_group
rendezvous_iterator = rendezvous(
File "C:\Users\korin\anaconda3\envs\myenv\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://

How can I solve it?  Look forward for your help, thank you!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by agolynski** [comment]
there is a related bug for DDP on windows here:
https://github.com/PyTorchLightning/pytorch-lightning/issues/5358

and possible workaround:
https://forums.pytorchlightning.ai/t/ddp-on-2-gpus-no-rendezvous-handler-for-env/652

**Comment by Lookforworld** [comment]
Thanks for your reply，I'll try it. @Alexander Golynski

**Comment by mrshenli** [comment]
Hey @Lookforworld, since @agolynski has pointed to the solution, I am closing this issue for now. Please feel free to reopen if the workaround does not address the problem.
