### ISSUE TITLE
why sm_61 was dropped from the nightly build?

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#53164]
Just switched to [cu111](https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html) nightly build after realizing cu11.0 build wasn't getting updated anymore just to discover that 
```
GeForce GTX 1070 Ti with CUDA capability sm_61 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_70 sm_80 sm_86.
If you want to use the GeForce GTX 1070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

What can be done to restore the support for sm_61 in nightly? It makes no sense that you'd drop support for not very old hardware and require users to build from scratch which is far from easy and takes an insane amount of resources and most of the time fails. I know it costs a bit more to build support for another arch, but it is still much cheaper and simpler when the user doesn't have to do it when you multiply this by the number of users (except I suppose there aren't many nightly users, so I'm probably a minority).

I use the nightly build because I am working on integrating new pytorch features, like pipeline, and I didn't know that having an older card is suddenly going to be a problem. :(

Also the part:
```
If you want to use the GeForce GTX 1070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

was not thought through, as there are no instructions on how to use  GeForce GTX 1070 Ti GPU with PyTorch on that page. It probably need to say that:
```
You have to build from source to use older cards and you will find instructions on how to 
build from source at https://pytorch.org/get-started/locally/
```

Thanks.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @ngimel @aocsa

**Comment by seemethere** [comment]
Sorry about that hopefully thist has been resolved by https://github.com/pytorch/builder/commit/8924a150b6b3e41256100de387bc385d1e8c7880

**Comment by stas00** [comment]
Amazing, thank you, @seemethere for restoring it! That is super-helpful.

I will retest once the new build rolls out!

**Comment by stas00** [comment]
OK, did we now lose 86? 

61 works, but on 86 now I'm getting:
```
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1155, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
