### ISSUE TITLE
[jit] torchscript cannot compile conditional expression

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch#53195]
## 🐛 Bug

In the following snippet, the compilation of the ternary operator fails. However, converting it to an equivalent `if/else` block works fine.

CC @fmassa 

```py
from typing import List

def f(list_or_int: List[int]):
    if isinstance(list_or_int, int):
        the_int = list_or_int
    else:
        the_int = list_or_int[0]
        
def g(list_or_int: List[int]):
    the_int = list_or_int if isinstance(list_or_int, int) else list_or_int[0]
    
torch.jit.script(f)  # OK
torch.jit.script(g)  # not OK
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-100-4692b49a963e> in <module>
     12 
     13 torch.jit.script(f)  # OK
---> 14 torch.jit.script(g)  # not OK

~/opt/miniconda3/envs/pt/lib/python3.8/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    975         if _rcb is None:
    976             _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)
--> 977         fn = torch._C._jit_script_compile(
    978             qualified_name, ast, _rcb, get_default_args(obj)
    979         )

RuntimeError: 
if-expression's true branch has type List[int] but false branch has type int:
  File "<ipython-input-100-4692b49a963e>", line 11
def g(list_or_int: List[int]):
    the_int = list_or_int if isinstance(list_or_int, int) else list_or_int[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

```

## Environment

PyTorch version: 1.8.0a0+ad7d208
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.8.0a0
[pip3] torchaudio==0.8.0a0+2c8aad9
[pip3] torchtext==0.9.0a0+651c1f7
[pip3] torchvision==0.9.0a0+1438b0c
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-include               2020.2                      260  
[conda] mkl-service               2.3.0            py38h9ed2024_0  
[conda] mkl_fft                   1.3.0            py38ha059aab_0  
[conda] mkl_random                1.1.1            py38h959d312_0  
[conda] numpy                     1.19.2           py38h456fd55_0  
[conda] numpy-base                1.19.2           py38hcfb5961_0  
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.8.0a0                  pypi_0    pypi
[conda] torchaudio                0.8.0a0+f2da586          pypi_0    pypi
[conda] torchtext                 0.9.0a0+651c1f7           dev_0    <develop>
[conda] torchvision               0.9.0a0+1438b0c           dev_0    <develop>

cc @gmagogsfm

**Comment by firstprayer** [comment]
Seems the issue doesn't come from compiling conditional expression itself but from unable to infer type automatically based on isinstance. Also, it seems the function signature is confusing, why would list_or_int have type "List[int]" in the typing annotation?

**Comment by NicolasHug** [comment]
Thanks for looking into this

> Seems the issue doesn't come from compiling conditional expression itself but from unable to infer type automatically based on isinstance

I don't know much about the internals of torchscript but if the issue comes from type inference, why does it work fine with the expanded `if / else` blocks?


> Also, it seems the function signature is confusing, why would list_or_int have type "List[int]" in the typing annotation?

I agree it's not ideal. For context, the function we're dealing with is https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L340:L340. The `size` parameter can be an int or a sequence of ints and the behavior of the functions is different depending on the type. We still type `size` as `List[int]` as torchscipt doesn't support `Union`. Users using torchscript must pass a list with 1 int if they want the same behavior as if they were passing an int.

**Comment by gmagogsfm** [comment]
I think this has been fixed about a month ago in https://github.com/pytorch/pytorch/pull/51789 by @nikithamalgifb 

I tried at HEAD and both functions `f` and `g` compiles correctly. Closing for now, feel free to re-open if this issue persists after upgrading PyTorch.
