### ISSUE TITLE
[package] allow_empty flag on extern/mock

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#53217]
In `torch.package`, we allow users to control how dependencies are packaged through the `extern` and `mock` APIs.

Both `extern()` and `mock()` take [bazel-style](https://docs.bazel.build/versions/master/be/functions.html#glob) glob arguments. If a module matches against a pattern during dependency resolution, it will get externed or mocked as appropriate.

Following the bazel-style arguments further, we should allow the user to set an `allow_empty` flag. We should track whether or not any module dependencies matched the specified pattern during packaging. At the end of packaging (in `PackageExporter.close`), we should throw an error if a given pattern was never matched against but `allow_empty` was false for it. 

The following internal trunk breakage would have been caught early by such functionality: https://fburl.com/i8fgh2gw

cc @mruberry

**Comment by zzzwen** [comment]
A relating request: the exporter should accept a block list, to ensure we do not pull undesired dependencies.

**Comment by zzzwen** [comment]
A relating request is for the exporter to accept a block list, to ensure we do not pull undesired dependencies in by accident.

**Comment by suo** [comment]
yeah, it's a good followup to add a third action: `deny`. Identical API as `extern` and `mock`, but the action is to throw an exception if the pattern is matched.
