### ISSUE TITLE
Modification of tests for one method causes failures for some others

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#53237]
## 🐛 Bug

#48230 was closed because it couldn't be reproduced again after #50578,
but it still persists if tested with the current code in the master branch.

Some `index_fill` tests are failing if a test-input of another operator (namely, `__rpow__`) in `method_tests` is removed,
but passes if that test-input is added back to `method_tests`, or if all test-inputs for `__rpow__` are removed.

## To Reproduce

1. Remove the following line from `method_tests` in `common_methods_invocations.py`:
https://github.com/pytorch/pytorch/blob/30a8a13a7d46f00db0557fcbdfe84e8957ac1bad/torch/testing/_internal/common_methods_invocations.py#L2890.
2. Run the following tests:
`TestAutogradDeviceTypeCPU.test_index_fill_variable_dim_cpu`
`TestAutogradDeviceTypeCPU.test_index_fill_variable_dim_neg0_cpu`
`TestAutogradDeviceTypeCUDA.test_index_fill_variable_dim_cuda`
`TestAutogradDeviceTypeCUDA.test_index_fill_variable_dim_neg0_cuda`

3. Tests fail with the same error as in #48230:

```
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])
analytical:tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2.,
         2., 2., 0., 0., 0., 0., 0.]])
```

## Expected behavior

Modifying a test for an operator should not affect another operator.

## Environment

Locally, and on [CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/280813/workflows/a6eb8cb5-4ee9-42f2-963d-efa545e22141/jobs/11299776).

```
PyTorch version: 1.9.0a0+git5095332
Is debug build: True
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+git5095332
```

## Additional context
 This issue might block removing old tests and porting method tests to `OpInfo`s.
@nikitaved's suggestion fixes the issue I stumbled upon, but it doesn't seem to address the root-cause of this issue,
which might manifest again in the future.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
Thank you for filing this issue, @imaginary-person. I've marked it "high priority." We'll take a look ASAP.

**Comment by nikitaved** [comment]
`index_fill` tests are not removed from `method_tests`. @imaginary-person , could you try removing it from there and see what happens?

**Comment by imaginary-person** [comment]
> `index_fill` tests are not removed from `method_tests`. @imaginary-person , could you try removing it from there and see what happens?

It seems that the failed tests correspond to one of the test-inputs for `index_fill` in `method_tests`.  If I remove the `index_fill` tests from `method_tests`, these tests cease to exist:

```
======================================================================
ERROR: test_index_fill_variable_dim_cpu (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestAutogradDeviceTypeCPU' has no attribute 'test_index_fill_variable_dim_cpu'
```

```
======================================================================
ERROR: test_index_fill_variable_dim_neg0_cpu (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestAutogradDeviceTypeCPU' has no attribute 'test_index_fill_variable_dim_neg0_cpu'

----------------------------------------------------------------------

```

**Comment by nikitaved** [comment]
@imaginary-person , I was able to remove them with no such issues. Did you try to run `python setup.py`? I am actually using the developer's build `python setup.py develop` which allows you to modify python files directly without any recompilation unless the scripts do some autogen.

**Comment by imaginary-person** [comment]
@nikitaved, I also built with `python setup.py develop`.
For this test, I cloned the PyTorch git repo today.

Here's the environment that I tested in:
```
PyTorch version: 1.9.0a0+git5095332
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+git5095332
[conda] Could not collect
```

**Comment by nikitaved** [comment]
So, how did you fail these nonexistent tests?

**Comment by imaginary-person** [comment]
As I mentioned in a [previous comment](https://github.com/pytorch/pytorch/issues/53237#issuecomment-790674838), those tests cease to exist if the tests are removed from `method_tests`.  I confirmed that by trying to run them manually, eg. `python test_autograd.py TestAutogradDeviceTypeCPU.test_index_fill_variable_dim_neg0_cpu`. 
They wouldn't fail on CI  if the `index_fill` tests are removed from `method_tests`.

**Comment by aocsa** [comment]
it was solved here #53854

**Comment by kshitij12345** [comment]
And it strikes back :(

Reference: https://app.circleci.com/pipelines/github/pytorch/pytorch/309929/workflows/7b2d6f4e-0ae9-4dfd-9328-12ed0e81254a/jobs/12835250/steps

Reference PR: https://github.com/pytorch/pytorch/pull/56910

**Comment by kshitij12345** [comment]
For following entry,
https://github.com/pytorch/pytorch/blob/1145e2c6e238058d0f4a87e90db95c22a9dc2a87/torch/testing/_internal/common_methods_invocations.py#L5715

Depending on the random state,
https://github.com/pytorch/pytorch/blob/1145e2c6e238058d0f4a87e90db95c22a9dc2a87/torch/testing/_internal/common_methods_invocations.py#L5389-L5393

For the case when the tests pass, index generated is `[3, 0]` , however with alteration of entries produces `[2, 2]`. (duplicate index)

https://github.com/pytorch/pytorch/blob/6de11c2db37d2b64debb97af40147de1581f718a/tools/autograd/derivatives.yaml#L607-L610
Formula for `value` doesn't consider this. And thus we get the failures.

<details>

<summary> Snippet to reproduce the failure </summary>

```python
import torch

t = torch.randn(5, 5, requires_grad=True, dtype=torch.double)
# idx = torch.tensor([3, 0]) # Works.
idx = torch.tensor([2, 2])

print(torch.unique(idx))

v = torch.tensor(-2.5122, requires_grad=True, dtype=torch.double)

def fn(v):
    return t.index_fill(0, idx, v)

torch.autograd.gradcheck(fn, (v,))
torch.autograd.gradgradcheck(fn, (v,))

```

</details>

Fix (tested locally):
```patch
--- a/tools/autograd/derivatives.yaml
+++ b/tools/autograd/derivatives.yaml
@@ -606,7 +606,7 @@
 
 - name: index_fill_.int_Tensor(Tensor(a!) self, int dim, Tensor index, Tensor value) -> Tensor(a!)
   self: grad.clone().index_fill_(dim, index, 0)
-  value: grad.index_select(dim, index).sum()
+  value: grad.index_select(dim, std::get<0>(at::_unique(index))).sum()
   index: non_differentiable
 
 - name: index_put_(Tensor(a!) self, Tensor?[] indices, Tensor values, bool accumulate=False) -> Tensor(a!)
```

 Questions that I have
* Should forward error out if there are duplicate indices (my guess is this behaviour wasn't intentional) (BC breaking)?
* If we decide to keep forward as is and update the backward, there would be a perf-hit. (Is it ok to have perf hit for this niche case)

**Comment by mruberry** [comment]
Thank you for diagnosing this, @kshitij12345!

Would you file an issue that focuses exclusively on index_fill with duplicative indices? Just note, like you have here, that when giving duplicative indices grad and gradgradcheck fail

Second, can we address this test issue by porting index_fill to an OpInfo, removing its method_tests() entries, and updating its sample inputs to generate valid samples? That sample input generator can cite the issue for why it doesn't generate duplicate indices. Interesting technical question: how challenging is it to generate a tensor with random but unique indices? Maybe we should provide a helper for doing it, or add a `unique` kwarg to `make_tensor()`

Alternatively, we could update index_variable to never generate duplicative indices, but I'm not sure what the scope of that change would be

**Comment by kshitij12345** [comment]
> Second, can we address this test issue by porting index_fill to an OpInfo, removing its method_tests() entries, and updating its sample inputs to generate valid samples? That sample input generator can cite the issue for why it doesn't generate duplicate indices

I see that `index_fill` already has OpInfo entry (will consolidate the remaining method entries to this).
https://github.com/pytorch/pytorch/blob/1145e2c6e238058d0f4a87e90db95c22a9dc2a87/torch/testing/_internal/common_methods_invocations.py#L1358-L1377

> Interesting technical question: how challenging is it to generate a tensor with random but unique indices? Maybe we should provide a helper for doing it, or add a unique kwarg to make_tensor()

I have a very simple idea. (will mark it in the PR)

**Comment by ezyang** [comment]
IMO we should reseed before sampling randomly for each test, so that test ordering changes don't perturb RNG state.

**Comment by mruberry** [comment]
> IMO we should reseed before sampling randomly for each test, so that test ordering changes don't perturb RNG state.

Porting the test to an OpInfo will achieve this because when using OpInfos the generation of sample inputs occurs WITHIN each test, not outside of it, unlike the deprecated method_tests().

We could fix method_tests(), but the real fix is to kill them (by porting them to OpInfos).
