### ISSUE TITLE
[torch.jit.script] RuntimeError: default_program(35): error: extra text after expected end of number

### ISSUE THREAD

**Issue by BelongAl** [pytorch/pytorch#53252]
When I input for a Bert model twice in a row, I get this error the second time。

Traceback (most recent call last):
  File "bert2onnx.py", line 61, in <module>
    result = script_model(input_ids, label_ids, mask_ids)
  File "/home/users/wangrui39/Python-3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 728, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: default_program(35): error: extra text after expected end of number

default_program(35): error: extra text after expected end of number

2 errors detected in the compilation of "default_program".

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void func_7(float* t0, float* t1, float* aten_mul_flat) {
{
  if (512 * blockIdx.x + threadIdx.x<2 ? 1 : 0) {
    float v = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_1 = __ldg(t1 + 0);
    float v_2 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_3 = __ldg(t1 + 0);
    float v_4 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_5 = __ldg(t1 + 0);
    float v_6 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_7 = __ldg(t1 + 0);
    float v_8 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_9 = __ldg(t1 + 0);
    float v_10 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_11 = __ldg(t1 + 0);
    float v_12 = __ldg(t0 + (512 * blockIdx.x + threadIdx.x) % 2);
    float v_13 = __ldg(t1 + 0);
    aten_mul_flat[512 * blockIdx.x + threadIdx.x] = ((logf(v / v_1<1.192092895507812e-07f ? 1.192092895507812e-07f : (v_2 / v_3>0.9999998807907104f ? 0.9999998807907104f : v_4 / v_5)))<-3.402823466385289e+38.f ? -3.402823466385289e+38.f : (logf(v_6 / v_7<1.192092895507812e-07f ? 1.192092895507812e-07f : (v_8 / v_9>0.9999998807907104f ? 0.9999998807907104f : v_10 / v_11)))) * (v_12 / v_13);
  }
}
}

I found that it is due to the [mypy](https://mypy.readthedocs.io/en/stable/) 。   If I remove this mypy, everything goes well.
like this:
def forward(self, a, b, c=True) 
    # type:(Tensor, Tensor, bool) 
->
def forward(self, a, b, c) 
pytorch version：1.7.1

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Thanks for reporting this issue. Could you provide a self-contained minimal repro so that we can investigate? Thanks!

**Comment by gmagogsfm** [comment]
I recently fixed a couple bugs in correctly recognizing mypy type annotations in `torch.jit.script`. You can give your program a try with latest version of PyTorch.

I will close this issue for now due to inactivity, feel free to reopen if you'd like to discuss further.

**Comment by pqn** [comment]
I think this may also be a duplicate of https://github.com/pytorch/pytorch/issues/62962#issuecomment-1245990087
