### ISSUE TITLE
DISABLED test_accurracy (__main__.TrainMnist)

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#53268]
see also https://github.com/pytorch/pytorch/issues/53267

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by zhangguanheng66** [comment]
A high priority issue to recover the CI test.

**Comment by cpuhrsch** [comment]
It seems that this mechanism doesn't propagate to the XLA tests. We created a separate PR to disable the tests https://github.com/pytorch/pytorch/pull/53274

**Comment by janeyx99** [comment]
Closing this issue as the test doesn't seem to exist in our codebase anymore. Please reopen if there needs to be further action.
