### ISSUE TITLE
__torch_function__ on factory functions via type and __torch_factory__

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53290]
`__torch_function__` is cool and all but you need to actually have a custom Tensor object to trigger `__torch_function__`. In #53144 I propose to pass on keyword arguments to factory functions in Modules, but if you want to construct custom tensor objects for all your parameters this still *is not enough*, there's no way to get them in there!

So, I propose we support `torch.empty(10, type=MyCustomTensor)`. The effect of this should be to call `MyCustomTensor.__torch_factory__(torch.empty, args=(10, ))` (name TBD), where class method `__torch_factory__` is responsible for implementing the factory function. Another extension would be to make it possible to also pass arbitrary args/kwargs to the type constructor (e.g., if you implemented a custom device this way, and needed to specify what device index you wanted the tensor to live on). The important thing is it lives like a kwarg (or several), so it can be propagated around in the same way regular factory kwargs are propagated.

This Numpy NEP https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html is attempting to solve a similar problem, but they approach it differently: instead of taking a Type, they take an actual instance of the object that you want to create the tensor like and model off of that. I'm not as bullish on this variant because rewriting your code to be `torch.empty_like(x, ...other stuff...)` is a pretty small lift and handles this use case perfectly. I'm primarily interested in the case when you don't actually have a tensor handy (e.g., in parameter initialization, for example).

cc @hameerabbasi @rgommers @gchanan @mruberry @jamesr66a

**Comment by rgommers** [comment]
> So, I propose we support `torch.empty(10, type=MyCustomTensor)`.

Just making sure: all tensor creation functions right, not just `empty`?

> instead of taking a Type, they take an actual instance of the object that you want to create the tensor like and model off of that.

Why not allow both? If you already have the instance, then there needs to be a `.__class__` lookup somewhere, and it's probably preferable to have that supported out of the box.

**Comment by mruberry** [comment]
Another relevant proposal we've discussed: https://numpy.org/neps/nep-0037-array-module.html. It has some discussion of the like= proposal, and as it notes these two proposals are probably complementary. 

Your proposal to work with types instead of an actual instance object is also more consistent with the thinking in NEP 37.

**Comment by hameerabbasi** [comment]
Is there a reason we're defining a new protocol instead of sticking with `__torch_function__` like NEP-35? I'm worried that the overhead and maintenance of designing a new protocol versus using an existing one may not be worth it.

**Comment by ezyang** [comment]
> Just making sure: all tensor creation functions right, not just empty?

Yep

> Why not allow both? If you already have the instance, then there needs to be a .__class__ lookup somewhere, and it's probably preferable to have that supported out of the box.

Hmm, I guess this is reasonable. A mild reason not to is because it means there are now two ways to do like functionality: `torch.empty_like(t)` and `torch.empty(like=t)` which is not very Pythonic. But this seems fairly mild.

> Is there a reason we're defining a new protocol instead of sticking with __torch_function__ like NEP-35? I'm worried that the overhead and maintenance of designing a new protocol versus using an existing one may not be worth it.

`__torch_function__` is an instance method and therefore requires an instance of the class to be available in order to use the API. But this seems backwards, as far as the API goes, to me: if I want to allocate a CUDA tensor, I don't want to have to "make" a zero size sentinel CUDA tensor that I can then pass synthetically as an argument to places: I just want to say "make me a CUDA tensor".  Mike's comment "Your proposal to work with types instead of an actual instance object is also more consistent with the thinking in NEP 37." is also gesturing in this direction.

Perhaps this just means we should think about __array_module__ instead; BTW, #27878 also evokes this concept of the API, I think.

**Comment by hameerabbasi** [comment]
If we're going in this direction I think I'd also prefer `__torch_module__`.

**Comment by zou3519** [comment]
One of the places that could benefit from factory function handling is torch.fx -- right now factory functions can't be traced. Something like `torch.empty(10, type=MyCustomTensor)` still wouldn't solve the problem because ideally users wouldn't need to modify their code to get it to trace correctly. But maybe something with a context manager (like #27878) would support this use case. cc @Chillee

**Comment by ezyang** [comment]
Context managers are cool if you call them omnistaging :o) https://github.com/google/jax/pull/3370

**Comment by ezyang** [comment]
We implemented TorchFunctionMode, this is what we recommend people use for this use case now.
