### ISSUE TITLE
torch.linalg: unclear "synchronizes that device with the CPU"

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#53302]
## 📚 Documentation
The following note is mentioned for many of the functions in torch.linalg
`When given inputs on a CUDA device, this function synchronizes that device with the CPU.`
But I do not know what that means. What does it mean to "synchronize" devices? Does it move the tensor to the CPU?

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by raisinglc** [comment]
When we run a code on GPU, the instructions are separated to multiple threads. These threads don't end at the same time. If we want to get the entire processed data, we have to wait all related threads finished, and then use what we get to do following process. This is called synchronize. Personally, I think "When given inputs on a CUDA device, this function synchronizes that device with the CPU" means, CPU will collect data from CUDA and do something. In other work, this function cannot be accelerated by GPU completely. It relies on some CPU process.

**Comment by mruberry** [comment]
Thank you for reporting this issue @twoertwein. @raisinglc's explanation is in the right ballpark that we're trying to explain these algorithms move data from the GPU to the CPU. Typically GPU kernels are enqueued by the CPU and running asynchronously on the GPU, allowing both the CPU and GPU to run in a parallel. When an algorithm requires data from the GPU, however, the CPU waits for the GPU to provide it, and the GPU has to transfer the data to the CPU. This can be a surprisingly performance hit, and most PyTorch operators do not perform this cross-device data transfer.

Exactly WHAT data is being moved from the GPU to the CPU isn't clear from this documentation, but its intent is to warn users who may find this behavior surprising. Maybe there's a clearer way to express this.

**Comment by twoertwein** [comment]
If there isn't already a site that explain all of the CPU-GPU interactions (incl. `pin_memory`), it might be nice to have one central place that explain the situation, maybe even has a diagram showing what happens over time, and maybe provides an example profiling to exemplify where time is spent.
