### ISSUE TITLE
[ppc64le] FAIL: test_set_flush_denormal (__main__.TestTorch)

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#5331]
hi,  I just saw this error in the last few days.  both for GPU and CPU only environment.
Is the test precision assertion correct ?

```
FAIL: test_set_flush_denormal (__main__.TestTorch)

Traceback (most recent call last):
  File "test_torch.py", line 5519, in test_set_flush_denormal
    self.assertEqual(float_tensor[1], 0.0, prec=0.0)  # tiny_float to zero
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/common.py", line 256, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 1.0005271035279194e-42 not less than or equal to 0.0 :
```

**Comment by soumith** [comment]
On PPC64 it looks like denormal flags aren't being set correctly. This PR https://github.com/pytorch/pytorch/pull/5294 from 2 days ago added denormals support, but likely assumed only AMD64 / x86

**Comment by avmgithub** [comment]
currently the set_flush_denormal call will always return False if on ppc64le.
The unittest has a skipIf  as below.   I believe the intention is to skip this
test if not running on x86.  But since set_flush_denormal returns a False on
ppc64le , then it actually runs the test and not run on x86

    @unittest.skipIf(torch.set_flush_denormal(False),
                     "flush_denormal not supported")

I believe is you just add a not as below in the test_torch.py 

    @unittest.skipIf(not torch.set_flush_denormal(False),
                     "flush_denormal not supported")

the test should then run on x86 but skipped for ppc64le or other platforms.

**Comment by apaszke** [comment]
Doing calls that have side effects in skipIf is a bad idea. We should write a context manager that always resets the previous state + skips the test if the call returned False

**Comment by avmgithub** [comment]
@apaszke what can we do in the meantime to skip over the denormal test, which is invalid,  on ppc64 ?

**Comment by apaszke** [comment]
Skip this test everywhere. These checks will affect all tests and we don’t want that

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/5387
