### ISSUE TITLE
torch.cat behaves weirdly with empty variables

### ISSUE THREAD

**Issue by baldassarreFe** [pytorch/pytorch#5332]
## Context

I'm experimenting with dense blocks like the ones from DenseNet, where the input of a layer in a dense block is the concatenation of the input and the output of the previous layer, except of course for the very first layer, where only the block input is available.

Ideally, I would write the forward method of a dense block like this, taking advantage of the fact that the first time `cat` is invoked the empty tensor is simply discarded.

```python
def forward(self, block_input):
        layer_input = block_input
        layer_output = torch.autograd.Variable(torch.FloatTensor())  # empty

        all_outputs = []
        for layer in self._modules.values():
            layer_input = torch.cat([layer_input, layer_output], dim=1)
            layer_output = layer(layer_input)
            all_outputs.append(layer_output)

        return torch.cat(all_outputs, dim=1)
```

## Issue

I discovered that `torch.cat` behaves differently when dealing with empty Tensors and Variables, and in the latter case, it is influenced by the order of the inputs (even weirder)

## To reproduce

```python
import sys
import torch
from torch import FloatTensor
from torch.autograd import Variable

print(torch.__version__)
print(sys.version)
>>>0.3.0.post4
>>> 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
>>> [GCC 7.2.0]
```

With Tensors it ignores the empty inputs:

```python
x = FloatTensor(4, 3, 32, 32)
empty = FloatTensor()

res = torch.cat([x, empty], dim=1)
print(res.shape)
>>> torch.Size([4, 3, 32, 32])

res = torch.cat([empty, x], dim=1)
print(res.shape)
>>> torch.Size([4, 3, 32, 32])

res = torch.cat([empty, empty], dim=1)
print(res.shape)
>>> torch.Size([])
```

With Variables I would expect it to work the same, but... 
```python
x = Variable(x)
empty = Variable(empty)
```

If the first element in the concat list is not empty it's ok:
```python
res = torch.cat([x, empty], dim=1)
print(res.shape)
>>> torch.Size([4, 3, 32, 32])
```

Unless the first element is the result of an operation, and not a manually created tensor:
```python
conv = torch.nn.Conv2d(3, 3, kernel_size=1)
res = torch.cat([conv(x), empty], dim=1)
print(res.shape)
>>> RuntimeError: dimension specified as 1 but tensor has no dimensions
```

Also fails if the empty Variable is first, or with two empty Variables
```python
res = torch.cat([empty, x], dim=1)
print(res.shape)
>>> RuntimeError: dimension specified as 1 but tensor has no dimensions

res = torch.cat([empty, empty], dim=1)
print(res.shape)
>>> RuntimeError: dimension specified as 1 but tensor has no dimensions
```

## Expected behavior

`torch.cat` should behave identically with Tensors and Variables, or the difference should be stated in the documentation.

Haven't tried on a GPU, so I don't know what the behavior is with CUDA operations.

## Environment:
- OS: Ubuntu 16.04
- PyTorch version: 0.3.0.post4
- How you installed PyTorch: conda
- Python version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
- CUDA/cuDNN version: No

**Comment by zou3519** [comment]
Thanks for the detailed bug report, @baldassarreFe. I am confirming that the problem exists on master as well. Here's a quick script to copy/paste for my records.
```
import torch
from torch import FloatTensor
from torch.autograd import Variable

x = FloatTensor(4, 3, 32, 32)
empty = FloatTensor()
x = Variable(x)
empty = Variable(empty)

# ok
res = torch.cat([x, empty], dim=1)

# not ok
conv = torch.nn.Conv2d(3, 3, kernel_size=1)
res = torch.cat([conv(x), empty], dim=1)

# not ok
res = torch.cat([empty, x], dim=1)

# not ok
res = torch.cat([empty, empty], dim=1)
```

**Comment by baldassarreFe** [comment]
Can you point me at the various parts of the codebase that are involved, like the C and CUDA backend?
I can try and see if I can open a pull request with a fix ;)

**Comment by zou3519** [comment]
Sure thing. The tensor and Variable code path will both end up at https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorMath.c#L3500-L3592 at some point.

This place is likely not the problem, because this code is shared between Variable and tensor, but I haven't looked too much into this yet. One thing that could help in understanding the problem is to GDB and see where the error is happening.
