### ISSUE TITLE
How to obtain the gradient of a tensor when in-place operation included?

### ISSUE THREAD

**Issue by WingsleyLui** [pytorch/pytorch#53348]
## ❓ How to obtain the gradient of a tensor when in-place operation included?
For simplicity, here is the code to describe the question: when using `res = ma @ mb` in pytorch, we can easily obtain the gradient of ma by calling some backward function, e.g. `(res**2).sum().backward(); print(ma.grad)`. But when this multiplication is implemented in a for loop manner, how can we can the gradient of tensor ma or mb?
```python
import torch
ma = torch.randn(2,3,3,4).requires_grad_(True)
mb = torch.randn(2,3,4,5).requires_grad_(True)
B,C,H,W = ma.shape
B,C,W,K = mb.shape
res_torch = torch.zeros((B,C,H,K), requires_grad=True)
for b in range(B):
    for c in range(C):
        for h in range(H):
            for k in range(K):
                for r in range(W):
                    res_torch[b][c][h][k] = res_torch[b][c][h][k] +  ma[b][c][h][r] * mb[b][c][r][k]
res_torch.sum().backward()
print(ma.grad)
```
A runtime error raised for the above code: `RuntimeError: leaf variable has been moved into the graph interio`.

However for this one, it can not yield the expected result:
```python
ma = torch.randn(2,3,3,4).requires_grad_(True)
mb = torch.randn(2,3,4,5).requires_grad_(True)
B,C,H,W = ma.shape
B,C,W,K = mb.shape
res_torch = torch.zeros((B,C,H,K), requires_grad=True)
for b in range(B):
    for c in range(C):
        for h in range(H):
            for k in range(K):
                res = 0
                for r in range(W):
                    res = res + ma[b][c][h][r] * mb[b][c][r][k]
                res_torch[b][c][h][k].data.fill_(res)
res_torch.sum().backward()
print(ma.grad)
```
the output was `None`.
Any hints for solving this problem?

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by zou3519** [comment]
Does cloning the tensor before performing the inplace operations solve the problem?
```
import torch
ma = torch.randn(2,3,3,4).requires_grad_(True)
mb = torch.randn(2,3,4,5).requires_grad_(True)
B,C,H,W = ma.shape
B,C,W,K = mb.shape
res_torch = torch.zeros((B,C,H,K), requires_grad=True)
rt = res_torch.clone()
for b in range(B):
    for c in range(C):
        for h in range(H):
            for k in range(K):
                for r in range(W):
                    rt[b][c][h][k] = rt[b][c][h][k] +  ma[b][c][h][r] * mb[b][c][r][k]
rt.sum().backward()
print(ma.grad)
```

**Comment by albanD** [comment]
> the output was None.
> Any hints for solving this problem?

This one is None because you use `.data`. You should never use `.data` :) 

And to get the gradient, you will need to save the input Tensor. Cloning as suggested by @zou3519 should work.

**Comment by WingsleyLui** [comment]
> > the output was None.
> > Any hints for solving this problem?
> 
> This one is None because you use `.data`. You should never use `.data` :)
> 
> And to get the gradient, you will need to save the input Tensor. Cloning as suggested by @zou3519 should work.

Many Thanks to @zou3519 and @zou3519! This one works well and helps a lot for debugging.
