### ISSUE TITLE
[bug] torch.cumsum: behaviour for `bool` input

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#53358]
Functional variant allows `bool` input but inplace variant errors with not implemented for `bool`.
```python
>>> import torch
>>> t = torch.tensor([False, True, True])
>>> t.cumsum(0)
tensor([0, 1, 2])
>>> t.cumsum_(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "cumsum_out_cpu" not implemented for 'Bool'
>>> t.cuda().cumsum_(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "cumsum_cuda" not implemented for 'Bool'
```

If overflow is the concern for disabling it then following should have also failed
```python
>>> t = torch.tensor([120, 120], dtype=torch.int8)
>>> t.cumsum(0)
tensor([120, 240]) # dtype is torch.long
>>> t.cumsum_(0)
tensor([120, -16], dtype=torch.int8) # overflow.
```

cc @izdeby @VitalyFedyunin @ngimel @aocsa

**Comment by kshitij12345** [comment]
Weird behavior on CUDA

```python
>>> t = torch.tensor(False)
>>> t.cumsum_(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "cumsum_out_cpu" not implemented for 'Bool'
>>> t.cuda().cumsum_(0) # Scalar works
tensor(False, device='cuda:0')
>>> t = torch.tensor([False])
>>> t.cumsum_(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "cumsum_out_cpu" not implemented for 'Bool'
>>> t.cuda().cumsum_(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "cumsum_cuda" not implemented for 'Bool'
```

Bug is due to the following lines (so it would also work for tensor with zero element)
https://github.com/pytorch/pytorch/blob/b864457743d7fd0f7dc70386dd10eb3f31ba6f22/aten/src/ATen/native/cuda/ScanKernels.cu#L594-L601

**Comment by CaoE** [comment]
@kshitij12345 outplace version will enforce the dtype to Long for bool and integer  [out_dtype = dtype.value_or(is_integral ? ScalarType::Long : self.scalar_type());](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/ReduceOps.cpp#L266). While Inplace version can't do the same operation and it keeps the data type due to the limitation of inplace operation.
As for the case: t = torch.tensor([False]), we can modify the corner case like : 
```
if (self.numel() == 1) {
    result.fill_(self.squeeze());
}
```

**Comment by CaoE** [comment]
Close it as it is not active. You can reopen it if you need to.
