### ISSUE TITLE
AdamW variable referenced before assignment

### ISSUE THREAD

**Issue by noboevbo** [pytorch/pytorch#53354]
## 🐛 Bug

In the most recent PyTorch version there is a bug in the AdamW optimizer. A recent change (f8238d7) moved the assignment of beta1 and beta2 inside the params loop (which doesn't make sense?). The assignment (beta1, beta2 = group['betas']) should be moved outside the loop again.

## To Reproduce

1. Freeze layers (`param_groups[n]['params'].grad = None`)
2. Use the step function of AdamW

Error message: UnboundLocalError: local variable 'beta1' referenced before assignment
Can be fixed by moving `beta1, beta2 = group['betas']` from line 104 outside of the for loop, e.g. line 76.

## Expected behavior

beta assignment should be independent of the params.

## Environment
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.1.0
CMake version: version 3.19.6

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: GeForce RTX 3080
Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.1.0
/usr/lib/libcudnn_adv_infer.so.8.1.0
/usr/lib/libcudnn_adv_train.so.8.1.0
/usr/lib/libcudnn_cnn_infer.so.8.1.0
/usr/lib/libcudnn_cnn_train.so.8.1.0
/usr/lib/libcudnn_ops_infer.so.8.1.0
/usr/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] Could not collect

cc @vincentqb

**Comment by albanD** [comment]
Hi,

Thanks for the issue.
The commit you link is actually moving things outside of the loop. To fix exactly that problem you describe. Can you check with the nightly build that this is not an issue anymore?

**Comment by noboevbo** [comment]
Hi, you're right, missread the commit. Should be fixed then.
