### ISSUE TITLE
Selection of test classes / methods through run_test.py is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#53355]
## 🐛 Bug

Selection of test classes / methods through `run_test.py` with `-i` is broken.

## To Reproduce

```sh
$ cd pytorch/test
$ TEST=test_dispatch.TestDispatch.test_def
$ python -m unittest $TEST
[...]
Ran 1 test in 12.792s
[...]
$ python run_test.py -i $TEST
[...]
Ran 28 tests in 40.443s
[...]
```

The actual test does not matter. I've just picked one at random.

## Expected behavior

Run only the selected test.

## Additional context

- This was broken in ~#43600~ #30445. Before we called `run_test` (the default `handler`) with `test_name`

    https://github.com/pytorch/pytorch/blob/e735395fc682cd59a44d04d52625a351b5374e6e/test/run_test.py#L434-L440

    whereas now we call with the `test_module`

    https://github.com/pytorch/pytorch/blob/854cc53594b4bb1871caad990e966e0de47abff8/test/run_test.py#L845-L850

- The only mention of this I could find is in #46272 and only because `test/distributed/test_distributed_*` cannot be run by `pytest` at the moment. Given that this is broken since ~half a year~ over a year, this is a testament that, although not officially supported yet, most of the developers might already be using `pytest`. Cc @rgommers @mruberry

**Comment by rgommers** [comment]
Nice investigation @pmeier. Now that you found the root cause, I'd say fix it anyway if it's easy to do so. If it takes more than 1-2 hours then never mind, given that it will become irrelevant once we manage to switch to pytest.

**Comment by pmeier** [comment]
Fixing this would have been more elaborate than I initially thought. Following @rgommers recommendation, I'm closing this since no one seems to be affected by this anyway.
