### ISSUE TITLE
Status of 64-bit Arm support in PyTorch 1.8

### ISSUE THREAD

**Issue by KaveriBridge** [pytorch/pytorch#53357]
## ❓ Questions and Help
I can see that there are torch wheels available for 64-bit Arm in https://download.pytorch.org/whl/torch_stable.html. However,  the official blog does not talk about new AArch64 binaries. What is the latest on AArch64 support?

cc @malfet

**Comment by malfet** [comment]
Thank you for your question: We've announced AArch64 support back in November, see https://pytorch.org/blog/prototype-features-now-available-apis-for-hardware-accelerated-mobile-and-arm64-builds/

**Comment by KaveriBridge** [comment]
@malfet, Thanks for your response. A follow-up question - I see that torch AArch64 packages in torch-stable repo, but no torch vision or other packages. Is that in the pipeline?

- cpu/torch-1.8.0-cp36-cp36m-manylinux2014_aarch64.whl
- cpu/torch-1.8.0-cp37-cp37m-manylinux2014_aarch64.whl
- cpu/torch-1.8.0-cp38-cp38-manylinux2014_aarch64.whl
- cpu/torch-1.8.0-cp39-cp39-manylinux2014_aarch64.whl

**Comment by nSircombe** [comment]
Hi @malfet,

I've just been giving the PyTorch 1.8 whl a go. I `pip install`ed `torch-1.8.0-cp36-cp36m-manylinux2014_aarch64.whl` on a CentOS 8.3.2011 machine, but I'm getting the following error:

```
OSError: <path-to-my-python-venv>/lib64/python3.6/site-packages/torch/lib/libtorch_global_deps.so: ELF load command alignment not page-aligned
```

This appears to be an issue previously encountered with NumPy ManyLinux builds (https://github.com/numpy/numpy/issues/16677) where the whl was built with the wrong pagesize.

The same issue appears to affect the nightly .whls from https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html too.

Ubuntu 20.10 with Python 3.8.6 appears to work as expected.

**Comment by nSircombe** [comment]
Hi @malfet, @KaveriBridge,

I've raised a bug report here: https://github.com/pytorch/pytorch/issues/53597
