### ISSUE TITLE
expand_as breaks for scalar tensors

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#53351]
Scalar tensors are either tensors `t`  for which `t.dim() == 0` or `t.dim() == 1 and t.size(0) == 1`. `expand_as`does not support them as it should:

```python
import torch
torch.rand(1).expand_as(torch.rand(()))
```
throws:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: expand(torch.FloatTensor{[1]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)
```

**Comment by gchanan** [comment]
not a bug -- broadcasting doesn't allow shrinking the number of dimensions.

**Comment by gchanan** [comment]
to be clear, `torch.rand(1)` is producing something of size `[1]` and you are trying to broadcast that to something of size `[]`.
