### ISSUE TITLE
Deduplicate c10 error and PyTorchError hierarchy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53370]
Both c10

```
// Used in ATen for out-of-bound indices that can reasonably only be detected
// lazily inside a kernel (See: advanced indexing).  These turn into
// IndexError when they cross to Python.
class C10_API IndexError : public Error {
  using Error::Error;
};

```

and torch/csrc/Exceptions.h

```
// Abstract base class for exceptions which translate to specific Python types
struct PyTorchError : public std::exception {
  PyTorchError(const std::string& msg_ = std::string()): msg(msg_) {}
  virtual PyObject* python_type() = 0;
  const char* what() const noexcept override {
    return msg.c_str();
  }
  std::string msg;
};
```

are a mechanism for raising C++ errors that translate into specific Python exception types. We only need one mechanism! Let's keep c10, as it is lower level and thus more generally applicable (the hierarchy in torch/csrc/Exceptions.h can only be used from torch/csrc).

This should be a bootcamp friendly task

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by shikanime** [comment]
Hi, I'd like to work on this issue as it seems to be a relatively "easy" entry point to familiarize myself with the project's source code.

After searching the source code a bit, correct me if I'm wrong, the idea is to replace most of the Python errors implemented with `PyTorchError` from `torch/Exception.h` with the `Error` from `c10/util/Exception.h`.

There are several macros for throwing errors, but I found `C10_THROW_ERROR` to be the most relevant, am I going in the right direction? (e.g. https://github.com/pytorch/pytorch/commit/4b61a1d750775e3c8bbba6026ad7df5d8fb25e1e)

I am still reading the contribution guideline and the technical documentation, please feel free to correct me if I am short-circuiting some processes, terms or anything.

**Comment by ezyang** [comment]
There are some more helper macros on top for conveniently throwing index errors like TORCH_CHECK_INDEX
