### ISSUE TITLE
Hang after running hogwild models in sequence

### ISSUE THREAD

**Issue by jef5ez** [pytorch/pytorch#5338]
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6.2
Not using gpu the moment.

I was trying to run some models multiple time to get runtime and performance metrics and reproduced my issue on the mnist-hogwild example: https://github.com/pytorch/examples/blob/master/mnist_hogwild/main.py
I basically wrapped the main function here and called it multiple times in a for loop. The problem only occurs if you use the model inside a subprocess and then also try to call it in the main process. On the second iteration of the loop everything seems to hang and has to be manually killed.

Using set_start_method("spawn") only complained about the context already being started.
What seems to work is using mp.get_context("spawn") and then creating subprocesses off of that like so: https://gist.github.com/jef5ez/7ecc7d4e8eeeaa81454cbf48ef6ae0c3
This seems to run through all the iterations but also gives a warning once finished:
...python3.6/multiprocessing/semaphore_tracker.py:129: UserWarning: semaphore_tracker: There 
appear to be 8 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by ngimel** [comment]
Closing, please reopen if it's still an issue.
