### ISSUE TITLE
Scalar variable's .data attribute returns a non-scalar

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#5339]
- OS: Mac OSX
- PyTorch version: master
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- CUDA/cuDNN version: CPU version
- GCC version (if compiling from source): clang

When we access the `.data` attribute of a scalar variable, the returned tensor is up-cast to have dimension 1. Is this expected?

```
>>> from torch.autograd import variable
>>> variable(1)
Variable containing:
 1
[torch.FloatTensor of size ()]

>>> variable(1).data
 1
[torch.FloatTensor of size 1]
```

cc. @gchanan

**Comment by gchanan** [comment]
Yes, we don't have scalar tensors.  But we are merging Variable and Tensor soon and .data will essentially be a no-op.

**Comment by neerajprad** [comment]
> Yes, we don't have scalar tensors. But we are merging Variable and Tensor soon and .data will essentially be a no-op.

I see. Thanks for clarifying!
