### ISSUE TITLE
Incorrect install command on pytorch.org

### ISSUE THREAD

**Issue by normster** [pytorch/pytorch#53399]
## 🐛 Bug

The pytorch.org website gives the wrong install command for installing 1.8 with CUDA 11.1:

![image](https://user-images.githubusercontent.com/6687910/110170052-75426880-7dae-11eb-94d4-17f3f6b1a8c3.png)

## To Reproduce

1. Navigate to https://pytorch.org/get-started/locally/
2. Change OS to Linux

## Expected behavior

Correct command (shown if I click CUDA 10.2 then back to CUDA 11.1) is:

```conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge```

## Environment

Google Chrome browser on MacOS

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr @brianjo @jlin27 @mruberry

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/52751
