### ISSUE TITLE
[bug] GaussianNLLLoss: Variance not broadcast to input shape

### ISSUE THREAD

**Issue by haydn-jones** [pytorch/pytorch#53392]
## 🐛 Bug

In the documentation for the new GaussianNLLLoss it states that if the variance provided is a scalar it will be broadcasted to be the same size as the input, this appears to not be happening. See https://pytorch.org/docs/stable/generated/torch.nn.GaussianNLLLoss.html#torch.nn.GaussianNLLLoss for this comment. Perhaps I misunderstand what this means.

## To Reproduce

```Python
import torch
import torch.nn as nn

loss = nn.GaussianNLLLoss()
input = torch.randn(2, 3, 32, 32, requires_grad=True)
target = torch.randn(2, 3, 32, 32)

var = nn.Parameter(torch.tensor(1.0))
output = loss(input, target, var)
```
Result:
```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    output = loss(input, target, var)
  File "/home/supa/anaconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/supa/anaconda3/envs/ml/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 378, in forward
    return F.gaussian_nll_loss(input, target, var, full=self.full, eps=self.eps, reduction=self.reduction)
  File "/home/supa/anaconda3/envs/ml/lib/python3.8/site-packages/torch/nn/functional.py", line 2512, in gaussian_nll_loss
    var = var.view(input.size(0), -1)
RuntimeError: shape '[2, -1]' is invalid for input of size 1
```
This happens whether or not the variance is simply a tensor or a Parameter.

## Expected behavior

The scalar variance is broadcast to the shape of the input.

## Environment

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: 11.0.0-2
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.2.1
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] pytorch-lightning         1.2.1                    pypi_0    pypi
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by jbschlosser** [comment]
Hey @haydn-jones ! As described in the Shape section of the [docs](https://pytorch.org/docs/stable/generated/torch.nn.GaussianNLLLoss.html#torch.nn.GaussianNLLLoss), var can be of shape `(N, 1)` to represent a separate scalar for each batch item. For your example above with batch size of `N=2`, this should work:

```python
import torch
import torch.nn as nn

loss = nn.GaussianNLLLoss()
input = torch.randn(2, 3, 32, 32, requires_grad=True)
target = torch.randn(2, 3, 32, 32)

var = torch.ones(2, 1)
output = loss(input, target, var)
```

Hope that helps!

**Comment by haydn-jones** [comment]
@jbschlosser thanks for the response. If a network has a learned scalar variance would the best course of action be to use `repeat` to get it to match the batch dimension? I guess I expected different behavior considering `torch.distributions.normal.Normal` allows for the standard deviation to be a scalar, will broadcast properly, and can functionally replace this loss.

I'll close this if this behavior is expected and intended.

**Comment by gchanan** [comment]
adding docs label because I agree the documentation is confusing.

**Comment by jbschlosser** [comment]
Yeah, I agree. While the Shape section of the docs correctly identifies what is acceptable, this line clearly doesn't match and is misleading: "If var is a scalar (implying target tensor has homoscedastic Gaussian distributions) it is broadcasted to be the same size as the input."

**Comment by carterbox** [comment]
I also want to create a model which computes a *single* (or broadcastable) variance for the model output. Why is that use-case explicitly prohibited by this function? Why does this function require a unique variance for each batch member? For example, why am I disallowed from the following input:

```python
import torch
import torch.nn as nn

loss = nn.GaussianNLLLoss()
input = torch.randn(2, 3, 32, 32, requires_grad=True)
target = torch.randn(2, 3, 32, 32)

var = torch.ones(1, 1, 32, 32, requires_grad=True)
output = loss(input, target, var)
```

Isn't it sufficient to just check that `input`, `target`, and `var` all broadcast to the same shape?
