### ISSUE TITLE
torch.save saves the full tensor even when sliced.

### ISSUE THREAD

**Issue by tueboesen** [pytorch/pytorch#53419]
Pytorch saves the full original tensor even when a tensor has been sliced.

Here is a small example of the problem
```
import torch

n = 1000000
l = 300

data = torch.ones((n,l),dtype=torch.int64)
data_small = data[:30000,:] #.to(dtype=torch.int8)
torch.save(data_small,'test')
data_small2 = torch.ones_like(data_small)
torch.save(data_small2,'test2')

```
This above code will create two files, both test and test2 contains a tensor of 30000x300 elements, but one of them takes 72 MB to save, while the other is 2.4GB.

I ran this test with torch 1.8.0

**Comment by gchanan** [comment]
This is expected, see https://pytorch.org/docs/master/notes/serialization.html#saving-and-loading-tensors-preserves-views -- there is a workaround there too.
