### ISSUE TITLE
Unhelpful error message when vmap is called on autograd.grad

### ISSUE THREAD

**Issue by gkaissis** [pytorch/pytorch#53445]
## 🐛 Bug

When vmap is used to map grad over an input, the following unhelpful message appears:

`torch.autograd.grad(outputs, inputs, grad_outputs) called inside torch.vmap. We do not support the case where any outputs are vmapped tensors (output 0 is being vmapped over). Please call autograd.grad() outside torch.vmap or file a bug report with your use case.`

This is counterintuitive as the vmap documentation (1.9 dev) explicitly states the following:

> vmap can also be used to compute batched gradients when composed with autograd.

I believe that the error message should either state that vmap is downright incompatible with batched gradients or provide a more helpful message on how to remedy the issue. Alternatively, a documentation improvement would be useful to exemplify the usage of vmap for batched per-sample gradient calculation (similar to what JAX or TensorFlow have).

## To Reproduce

1.  attempt to vmap the grad function over the batch dimension of an input

```py
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(16, 1)      
        
    def forward(self, x):
        return self.layer(x)

def criterion(y_pred):
    return (y_pred**2)

torch.manual_seed(123)
inp = torch.rand((2, 16,))
model = Model()
y_pred = model(inp)
loss = criterion(y_pred)

def fwd_pass_grad(inp):
    return torch.autograd.grad(criterion(model(inp)), model.parameters())

vmap(fwd_pass_grad)(inp)

<ipython-input-94-433d0eaa9c4a>:1: UserWarning: torch.vmap is an experimental prototype that is subject to change and/or deletion. Please use at your own risk. There may be unexpected performance cliffs due to certain operators not being implemented. To see detailed performance warnings please use `torch._C._debug_only_display_vmap_fallback_warnings(True) before the call to `vmap`.
  vmap(fwd_pass_grad)(inp)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-94-433d0eaa9c4a> in <module>
----> 1 vmap(fwd_pass_grad)(inp)

~/miniconda3/envs/torch/lib/python3.8/site-packages/torch/_vmap_internals.py in wrapped(*args)
    256         try:
    257             batched_inputs, batch_size = _create_batched_inputs(in_dims, args, vmap_level, func)
--> 258             batched_outputs = func(*batched_inputs)
    259             _validate_outputs(batched_outputs, func)
    260             return _unwrap_batched(batched_outputs, out_dims, vmap_level, batch_size, func)

<ipython-input-79-b6aabb721035> in fwd_pass_grad(inp)
      1 def fwd_pass_grad(inp):
----> 2     return torch.autograd.grad(criterion(model(inp)), model.parameters())

~/miniconda3/envs/torch/lib/python3.8/site-packages/torch/autograd/__init__.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    221         retain_graph = create_graph
    222 
--> 223     return Variable._execution_engine.run_backward(
    224         outputs, grad_outputs_, retain_graph, create_graph,
    225         inputs, allow_unused, accumulate_grad=False)

RuntimeError: torch.autograd.grad(outputs, inputs, grad_outputs) called inside torch.vmap. We do not support the case where any outputs are vmapped tensors (output 0 is being vmapped over). Please call autograd.grad() outside torch.vmap or file a bug report with your use case.
```

## Expected behavior

I expect the per-sample gradients wrt the parameters of the model to be returned, just like calling torch.autograd.grad on a single sample.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8 using torch._vmap_internals and also 1.9 from master
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): NA
 - Python version: 3.8.8
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

## Additional context

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @brianjo @mruberry

**Comment by gchanan** [comment]
Thanks for the issue.  I believe the only vmap support with autograd right now is implicit via the `vectorize` flag in https://pytorch.org/docs/stable/autograd.html#torch.autograd.functional.jacobian and https://pytorch.org/docs/stable/autograd.html#torch.autograd.functional.hessian.

We should improve the documentation.

**Comment by gkaissis** [comment]
That would be totally fine, however the jacobian function cannot be trivially applied to model weights as inputs. Hence, the vmap-driven batched gradients are only possible with a hacky workaround (basically make a function where the parameters in question are the input and getting loaded into a model). This leads to a freeze though and never completes running, at least on non-trivial models.

**Comment by zou3519** [comment]
@gkaissis There are many (potential) ways to compose vmap with autograd and I understand your frustration that the error message and documentation don't seem to match. For now we'll fix the documentation, but I'm curious to learn more about your use case -- what are you using per-sample-gradients for?

**Comment by gkaissis** [comment]
Thank you for your inpu!. I don't have a specific use-case in mind, but it would definitively be interesting and instructive to find out some of the many potential ways you are mentioning. At the simplest level, it would be nice to have feature parity with TF vectorized map and JAX.
