### ISSUE TITLE
Broken download links for libtorch v1.8.0 with CUDA 10.2 for Linux and Windows on PyTorch website

### ISSUE THREAD

**Issue by mfl28** [pytorch/pytorch#53448]
## 🐛 Bug

Broken download links for libtorch v1.8.0 with CUDA 10.2 for Linux (pre-cxx11 and cxx11 ABI) and Windows (Release and Debug versions) on the PyTorch website.

## To Reproduce

1. Clicking on any of the following links leads to an "Access Denied" error:
   * https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.0%2Bcu102.zip
   * https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcu102.zip
   * https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.8.0%2Bcu102.zip
   * https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.8.0%2Bcu102.zip

## Expected behavior

The chosen libtorch version is downloaded.

## Environment

 - PyTorch Version: .1.8.0
 - OS: Linux and Windows
 - CUDA version: 10.2

**Comment by peterjc123** [comment]
The correct links are listed below.
https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.8.0.zip
cc @seemethere

**Comment by mfl28** [comment]
Thanks!

**Comment by lablabla** [comment]
Same issue also happens for CUDA 11.1 when trying to download windows precompiled binaries
Changing `cu102` to `cu111` in the links suggested by @peterjc123 still leads to Access Denied page

- https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-1.8.0%2Bcu111.zip
- https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-debug-1.8.0%2Bcu111.zip
- https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-1.8.0.zip
- https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-debug-1.8.0.zip

**Comment by seemethere** [comment]
Okay I wrote a simple script to test if all of our libtorch packages are actually downloadable, sharing results here:

<details>
<summary> pkgs </summary>

```
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.8.0%2Bcpu.zip
https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcpu.zip
https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu111/libtorch-shared-with-deps-1.8.0%2Bcu111.zip
https://download.pytorch.org/libtorch/cu111/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcu111.zip
https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.8.0.zip
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.8.0%2Bcpu.zip
https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-1.8.0%2Bcpu.zip
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.8.0.zip
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.8.0.zip
https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-1.8.0%2Bcu111.zip
https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-debug-1.8.0%2Bcu111.zip
```

</details>

```bash
#!/usr/bin/env bash

while read pkg; do
    curl -fsSL -w "%{http_code}" --head -o /dev/null ${pkg}
    echo ": ${pkg}"
done < ./pkgs
```

Output being:
```
200: https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcpu.zip
200: https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.8.0.zip
200: https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.8.0%2Bcpu.zip
200: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.8.0%2Bcpu.zip
200: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-debug-1.8.0%2Bcpu.zip
200: https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.0.zip
200: https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.0.zip
200: https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.8.0.zip
200: https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.8.0.zip
200: https://download.pytorch.org/libtorch/cu111/libtorch-cxx11-abi-shared-with-deps-1.8.0%2Bcu111.zip
200: https://download.pytorch.org/libtorch/cu111/libtorch-shared-with-deps-1.8.0%2Bcu111.zip
200: https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-1.8.0%2Bcu111.zip
200: https://download.pytorch.org/libtorch/cu111/libtorch-win-shared-with-deps-debug-1.8.0%2Bcu111.zip
```

I did find that this issue is correct in that the installation instructions were incorrect for CUDA 10.2 and I created a PR to resolve this: https://github.com/pytorch/pytorch.github.io/pull/612
