### ISSUE TITLE
Question about torch.nn.Upsample() function

### ISSUE THREAD

**Issue by YDDDDG** [pytorch/pytorch#53449]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hi, I used _torch.nn.Upsample()_ function to upsample my 5D data, thus I write code in this way :
`self.upsample_layer = torch.nn.Upsample(scale_factor=upsample, mode='trilinear', align_corners=True)`
However, a warning raises:
**WARNING:root: mode trilinear is not implemented yet, take it a zero op**
it seems that trilinear mode is not implemented, but it doesn't make sense.
So What cases this warning? What should I do to resolve it?
Thanks~
![image](https://user-images.githubusercontent.com/33283950/110201378-b49bb280-7e9d-11eb-967c-2e07c5486636.png)

cc @albanD @mruberry @jbschlosser

**Comment by gchanan** [comment]
please use the forums and also the specify the version you are using.
