### ISSUE TITLE
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#53466]
## 🐛 Bug

I run the code from official document https://pytorch.org/docs/stable/generated/torch.enable_grad.html, but it fails on the first line.

## To Reproduce

```
x = torch.tensor([1], requires_grad=True)
```
It throws `RuntimeError: Only Tensors of floating point and complex dtype can require gradients`. 

## Expected behavior
The simplest fix is to change the document so that the example code from document will not fail any more, e.g. adding `dtype=torch.float32`. At the high level, is it expected that `int` should have no gradient? Is it possible that a `int` has a floating-point gradient?

## Environment

 - PyTorch Version (e.g., 1.0): 1.8
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.6
 - CUDA/cuDNN version: cuDNN 11.1
 - GPU models and configuration: A100

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by gchanan** [comment]
Thanks for pointing this out -- the easiest fix is to ensure the tensor is floating point by doing:

```
x = torch.tensor([1.], requires_grad=True)
```

(notice the `.`)

**Comment by ilovepytorch** [comment]
Oh awesome fix! Would you like me to create a PR to resolve this small issue? Just out of curiosity, do you think that a floating-point gradient of a int variable makes sense? Sorry I am not an expert at all and please feel free to CC anyone else that you trust to discuss with us.

**Comment by albanD** [comment]
Hi,

As the error states, gradient for in Tensors don't really make sense.
It would be great if you could send a PR fixing that yes!

**Comment by ilovepytorch** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/54658
