### ISSUE TITLE
FloatTensor value behaves strangely around INT32_MAX (2**31 -1)

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#53465]
## 🐛 Bug

I think I found two bugs related to float/int32 conversion. Both happens near `INT32_MAX == (2**31) -1 == 2147483647`.

1. Creating a float Tensor from Python integer value around `(2**31) -1` gives a value different from the original integer.
1. Converting the `int32` Tensor to `float` type gives wrong value when the original integer is `INT32_MAX`.

## To Reproduce

For the issue 1.

```python
v1 = (2**31) - 1
for i in range(200):
    v2 = torch.Tensor([v1]).item()
    print(i, v1, v2)
    v1 -= 1
```

This snippet prints the same values 

<details><summary>output</summary>

    2147483647 2147483648.0
    2147483646 2147483648.0
    2147483645 2147483648.0
    2147483644 2147483648.0
    2147483643 2147483648.0
    2147483642 2147483648.0
    2147483641 2147483648.0
    2147483640 2147483648.0
    2147483639 2147483648.0
    2147483638 2147483648.0
    2147483637 2147483648.0
    2147483636 2147483648.0
    2147483635 2147483648.0
    2147483634 2147483648.0
    2147483633 2147483648.0
    2147483632 2147483648.0
    2147483631 2147483648.0
    2147483630 2147483648.0
    2147483629 2147483648.0
    2147483628 2147483648.0
    2147483627 2147483648.0
    2147483626 2147483648.0
    2147483625 2147483648.0
    2147483624 2147483648.0
    2147483623 2147483648.0
    2147483622 2147483648.0
    2147483621 2147483648.0
    2147483620 2147483648.0
    2147483619 2147483648.0
    2147483618 2147483648.0
    2147483617 2147483648.0
    2147483616 2147483648.0
    2147483615 2147483648.0
    2147483614 2147483648.0
    2147483613 2147483648.0
    2147483612 2147483648.0
    2147483611 2147483648.0
    2147483610 2147483648.0
    2147483609 2147483648.0
    2147483608 2147483648.0
    2147483607 2147483648.0
    2147483606 2147483648.0
    2147483605 2147483648.0
    2147483604 2147483648.0
    2147483603 2147483648.0
    2147483602 2147483648.0
    2147483601 2147483648.0
    2147483600 2147483648.0
    2147483599 2147483648.0
    2147483598 2147483648.0
    2147483597 2147483648.0
    2147483596 2147483648.0
    2147483595 2147483648.0
    2147483594 2147483648.0
    2147483593 2147483648.0
    2147483592 2147483648.0
    2147483591 2147483648.0
    2147483590 2147483648.0
    2147483589 2147483648.0
    2147483588 2147483648.0
    2147483587 2147483648.0
    2147483586 2147483648.0
    2147483585 2147483648.0
    2147483584 2147483648.0
    2147483583 2147483520.0
    2147483582 2147483520.0
    2147483581 2147483520.0
    2147483580 2147483520.0
    2147483579 2147483520.0
    2147483578 2147483520.0
    2147483577 2147483520.0
    2147483576 2147483520.0
    2147483575 2147483520.0
    2147483574 2147483520.0
    2147483573 2147483520.0
    2147483572 2147483520.0
    2147483571 2147483520.0
    2147483570 2147483520.0
    2147483569 2147483520.0
    2147483568 2147483520.0
    2147483567 2147483520.0
    2147483566 2147483520.0
    2147483565 2147483520.0
    2147483564 2147483520.0
    2147483563 2147483520.0
    2147483562 2147483520.0
    2147483561 2147483520.0
    2147483560 2147483520.0
    2147483559 2147483520.0
    2147483558 2147483520.0
    2147483557 2147483520.0
    2147483556 2147483520.0
    2147483555 2147483520.0
    2147483554 2147483520.0
    2147483553 2147483520.0
    2147483552 2147483520.0
    2147483551 2147483520.0
    2147483550 2147483520.0
    2147483549 2147483520.0
    2147483548 2147483520.0
    2147483547 2147483520.0
    2147483546 2147483520.0
    2147483545 2147483520.0
    2147483544 2147483520.0
    2147483543 2147483520.0
    2147483542 2147483520.0
    2147483541 2147483520.0
    2147483540 2147483520.0
    2147483539 2147483520.0
    2147483538 2147483520.0
    2147483537 2147483520.0
    2147483536 2147483520.0
    2147483535 2147483520.0
    2147483534 2147483520.0
    2147483533 2147483520.0
    2147483532 2147483520.0
    2147483531 2147483520.0
    2147483530 2147483520.0
    2147483529 2147483520.0
    2147483528 2147483520.0
    2147483527 2147483520.0
    2147483526 2147483520.0
    2147483525 2147483520.0
    2147483524 2147483520.0
    2147483523 2147483520.0
    2147483522 2147483520.0
    2147483521 2147483520.0
    2147483520 2147483520.0
    2147483519 2147483520.0
    2147483518 2147483520.0
    2147483517 2147483520.0
    2147483516 2147483520.0
    2147483515 2147483520.0
    2147483514 2147483520.0
    2147483513 2147483520.0
    2147483512 2147483520.0
    2147483511 2147483520.0
    2147483510 2147483520.0
    2147483509 2147483520.0
    2147483508 2147483520.0
    2147483507 2147483520.0
    2147483506 2147483520.0
    2147483505 2147483520.0
    2147483504 2147483520.0
    2147483503 2147483520.0
    2147483502 2147483520.0
    2147483501 2147483520.0
    2147483500 2147483520.0
    2147483499 2147483520.0
    2147483498 2147483520.0
    2147483497 2147483520.0
    2147483496 2147483520.0
    2147483495 2147483520.0
    2147483494 2147483520.0
    2147483493 2147483520.0
    2147483492 2147483520.0
    2147483491 2147483520.0
    2147483490 2147483520.0
    2147483489 2147483520.0
    2147483488 2147483520.0
    2147483487 2147483520.0
    2147483486 2147483520.0
    2147483485 2147483520.0
    2147483484 2147483520.0
    2147483483 2147483520.0
    2147483482 2147483520.0
    2147483481 2147483520.0
    2147483480 2147483520.0
    2147483479 2147483520.0
    2147483478 2147483520.0
    2147483477 2147483520.0
    2147483476 2147483520.0
    2147483475 2147483520.0
    2147483474 2147483520.0
    2147483473 2147483520.0
    2147483472 2147483520.0
    2147483471 2147483520.0
    2147483470 2147483520.0
    2147483469 2147483520.0
    2147483468 2147483520.0
    2147483467 2147483520.0
    2147483466 2147483520.0
    2147483465 2147483520.0
    2147483464 2147483520.0
    2147483463 2147483520.0
    2147483462 2147483520.0
    2147483461 2147483520.0
    2147483460 2147483520.0
    2147483459 2147483520.0
    2147483458 2147483520.0
    2147483457 2147483520.0
    2147483456 2147483392.0
    2147483455 2147483392.0
    2147483454 2147483392.0
    2147483453 2147483392.0
    2147483452 2147483392.0
    2147483451 2147483392.0
    2147483450 2147483392.0
    2147483449 2147483392.0
    2147483448 2147483392.0

</details>

Similarly, you cannot assign the values near `2**31 - 1` to `FloatTensor`.

```python
for i in range(2**31 - 10, 2**31 -1):
    a = torch.FloatTensor([1])
    a[0] = i
    print(i, a.item())
```

```
2147483638 2147483648.0
2147483639 2147483648.0
2147483640 2147483648.0
2147483641 2147483648.0
2147483642 2147483648.0
2147483643 2147483648.0
2147483644 2147483648.0
2147483645 2147483648.0
2147483646 2147483648.0
```

For the issue 2.

```python
v1 = (2**31) - 1
v2 = torch.Tensor([v1])
print(v1, v2.item(), v2.to(torch.int32).item())
```

This prints;

```
2147483647 2147483648.0 -2147483648
```

## Expected behavior

Values should be preserved.

## Environment

```
PyTorch version: 1.9.0.dev20210305
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.9.0.dev20210305
[pip3] torchaudio==0.9.0a0+7b85f1c
[pip3] torchtext==0.9.0a0+c072ba6
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.9.0.dev20210305 py3.8_cuda10.1_cudnn7.6.3_0    pytorch-nightly
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torchaudio                0.9.0a0+7b85f1c           dev_0    <develop>
[conda] torchtext                 0.9.0a0+c072ba6           dev_0    <develop>
```

**Comment by xiaomengy** [comment]
Personally I don't think this is a bug. IEEE 754 float32 type only has 23-bit mantissa which means 24-bit significand precision (the 1st 1 is implicit). So in theory float32 type cannot exactly express the int32 type with more than 24-bit values. That's why there is precision loss after converting the large int32 values to float32 and then convert it back.
https://en.wikipedia.org/wiki/Single-precision_floating-point_format

**Comment by mthrok** [comment]
@xiaomengy 

I think you are right. I encountered when I was doing 

```c++
some_tensor.clamp_(INT32_MIN, INT32_MAX);
```

and observed that `2147483648` value is still there, which appeared to be buggy so I thought it was bug and forgot about the significant precision. Using double precision resolved my use case. I am going to close the issue. Thanks!
