### ISSUE TITLE
can  torch.distributed used in C++ api  libtorch ?

### ISSUE THREAD

**Issue by yulinhuyang** [pytorch/pytorch#53497]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by skyline75489** [comment]
I think this discussion [here](https://discuss.pytorch.org/t/libtorch-c-mpi-example/39671) still stands.

**Comment by rohan-varma** [comment]
Closing per above comment. Please see https://discuss.pytorch.org/t/libtorch-c-mpi-example/39671/6 for additional details around C++ distributed APIs.
