### ISSUE TITLE
OpInfo tests for inplace variants use the same sample inputs as the method 

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#53493]
## 🐛 Bug

`OpInfo` tests for inplace variants currently use the same sample inputs as the method for which they're variants.
This can cause `test_variant_consistency_eager` tests to fail because of the [broadcasting semantics for inplace variants](https://pytorch.org/docs/stable/notes/broadcasting.html#in-place-semantics) in PyTorch.
Since in-place tensors can't change shape, if any of the sample inputs specified in a sample inputs function
for an `OpInfo` require changing the shape of the inplace tensor by an inplace variant of an operation, the `test_variant_consistency_eager` test would fail for that operation.

## To Reproduce

As an example, add an `OpInfo` for `pow`, as in #50999. `pow_` is the inplace variant for `pow`.

1. Use a sample-input that'd require changing the shape of the in-place tensor for the inplace variant. For example:
https://github.com/pytorch/pytorch/blob/2f3d2919852951d3f2ee6b65418f7b75474f24f7/torch/testing/_internal/common_methods_invocations.py#L1215-L1218

2. Run `TestCommonCPU.test_variant_consistency_eager_pow_cpu_float64` or `TestCommonCUDA.test_variant_consistency_eager_pow_cuda_float64` in `test_ops.py`.

3. The test would fail because of the following error:
https://github.com/pytorch/pytorch/blob/a0d1e701db66682411f3c2e56be9ab823359c0b5/aten/src/ATen/TensorIterator.cpp#L941

## Expected behavior

`test_variant_consistency_eager` should not fail if a sample input in the `OpInfo` sample inputs function requires resizing of the inplace tensor for an inplace variant of an operation.
Perhaps `test_variant_consistency_eager` can be modified to catch the exception related to the output not matching the broadcast shape, and it can be ignored for inplace variants of an operation.

## Environment

PyTorch version: 1.9.0a0+git5095332
Is debug build: True
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100S-PCIE-32GB
GPU 1: Tesla V100S-PCIE-32GB

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+git9603a4c
[conda] Could not collect

**Comment by kshitij12345** [comment]
Probably a duplicate of https://github.com/pytorch/pytorch/issues/50747

**Comment by imaginary-person** [comment]
Closing the issue, as it's a duplicate of #50747.
