### ISSUE TITLE
After updating to 1.8, I can no longer export TorchScript models to ONNX

### ISSUE THREAD

**Issue by PhilMacKay** [pytorch/pytorch#53506]
## 🐛 Bug

After updating to PyTorch version 1.8.0, I can no longer send TorchScript modules to `torch.onnx.export`, it produces `ValueError: no signature found for <torch._C.ScriptMethod object at 0x0000014D5B132D08>`
## To Reproduce

1. Use PyTorch version 1.8.0
2. Try to export a TorchScript model with `torch.onnx.export`

Example code:
```
import torch

myModel = torch.nn.Conv2d(2, 2, 3)

exampleInput = torch.rand(1, 2, 32, 32)
exampleOutput = myModel(exampleInput)

myTorchScriptModel = torch.jit.trace(myModel, exampleInput)

torch.onnx.export(myTorchScriptModel, exampleInput, "myModel.onnx", example_outputs=exampleOutput)
```
Edit: Moved the note from "Additional Context" to here, so it's not lost below the stack trace:
Note that the example code is a toy example, and it would be trivial to export the nn.Module instance instead of the traced model. In the real situation, the TorchScript model is loaded from a file, and the original module definition may no longer be available.

Stack trace:
```
Traceback (most recent call last):
  File "C:\Python37\lib\inspect.py", line 2378, in _signature_from_callable
    sigcls=sigcls)
  File "C:\Python37\lib\inspect.py", line 2288, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "C:\Python37\lib\inspect.py", line 2112, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <instancemethod __call__ at 0x000001E3A2F7DF78>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\ExportTorchScript.py", line 10, in <module>
    torch.onnx.export(myTorchScriptModel, exampleInput, "myModel.onnx", example_outputs=exampleOutput)
  File "D:\Sources\OnnxExport\env\lib\site-packages\torch\onnx\__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\Sources\OnnxExport\env\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "D:\Sources\OnnxExport\env\lib\site-packages\torch\onnx\utils.py", line 685, in _export
    args = _decide_input_format(model, args)
  File "D:\Sources\OnnxExport\env\lib\site-packages\torch\onnx\utils.py", line 328, in _decide_input_format
    sig = inspect.signature(model.forward)
  File "C:\Python37\lib\inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "C:\Python37\lib\inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "C:\Python37\lib\inspect.py", line 2381, in _signature_from_callable
    raise ValueError(msg) from ex
ValueError: no signature found for <torch._C.ScriptMethod object at 0x000001E3BD1F4D68>
```

## Expected behavior

The code should run without raising any warning or error, just like it did in PyTorch 1.7.
It should create an ONNX model very similar to what would have been produced if the code example tried to export the object `myModel` instead of `myTorchScriptModel`.

## Environment

PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: CUDA 11.1
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

## Additional context

Workaround: If I comment line #683 (which is `args = _decide_input_format(model, args)`) in `torch.onnx.utils.py`, I can export my model as expected.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by neginraoof** [comment]
Thanks for reporting this issue.
One question I have is about the usage of torch.jit.trace :
Is this necessary? Because by default, ONNX exporter converts the torchscript graph produced by the tracer.
So you should e able to call: torch.onnx.export(myModel, exampleInput, "myModel.onnx")
and convert your model to ONNX.

**Comment by BowenBao** [comment]
@shubhambhokare1 This looks like the input args issue you are working on, please take a look if your fix resolves this one.

**Comment by malfet** [comment]
Closing
