### ISSUE TITLE
Remove silly "Buy new RAM!" sentence in error message when out of CPU memory

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#53518]
See 

https://github.com/pytorch/pytorch/blob/f1f9b049d83fc20256a244d62b2eca6548a02fd5/c10/core/CPUAllocator.cpp#L75

The phrase "Buy new RAM!" is silly. It's not even good advice (wouldn't it be "Buy more RAM!"?). And purchasing memory is not always an option for PyTorch users. We should just remove this unhelpful and possibly offensive phrase.

**Comment by mthrok** [comment]
@carolineechen Would you like to try this one?
