### ISSUE TITLE
Complex Autograd support for `torch.masked_fill` is currently untested

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53523]
Complex Autograd for `torch.masked_fill` [is](https://github.com/pytorch/pytorch/blob/0ca029b22d17d236d34bcecad44b94b35b1af4bb/aten/src/ATen/native/cpu/IndexKernel.cpp#L218) [currently](https://github.com/pytorch/pytorch/blob/0ca029b22d17d236d34bcecad44b94b35b1af4bb/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L960-L972) [supported](https://github.com/pytorch/pytorch/blob/0ca029b22d17d236d34bcecad44b94b35b1af4bb/tools/autograd/derivatives.yaml#L682-L689) but untested. 

Remove the existing [method_tests](https://github.com/pytorch/pytorch/blob/0ca029b22d17d236d34bcecad44b94b35b1af4bb/torch/testing/_internal/common_methods_invocations.py#L3563-L3570) (that aren't currently testing complex) and add an OpInfo test instead.

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa @VitalyFedyunin @walterddr

**Comment by kshitij12345** [comment]
Reference to previous attempt: https://github.com/pytorch/pytorch/pull/52483
