### ISSUE TITLE
test/distributed/test_c10d.py::RendezvousEnvTest::test_common_errors is failing sometimes

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#53526]
Error message (from [this job](https://app.circleci.com/pipelines/github/pytorch/pytorch/281757/workflows/3cb10958-9cbb-456a-a7ac-820ff52028ea/jobs/11350539)):

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1492, in wrapper
    return func(*args, **kwargs)
  File "distributed/test_c10d.py", line 507, in test_common_errors
    next(gen)
AssertionError: ValueError not raised
```

According to [the HUD](https://ezyang.github.io/pytorch-ci-hud/build2/pytorch-master), this is the timeline:

- c0adabe172935030bf748157965a9899b88f68f1 test started failing
- f595ba1bae9a75c6403e4624e7294b5635acd40c test stopped failing
- 8c798e062216278673a75bac0848ea69a8bd3f03 test started failing again
- 1fe6a6507e6a38534f0dc6265fd44cd26c80e5b0 test switched from shard 2 to shard 1

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by malfet** [comment]
This looks like the ordering issue, because test passes if run individually in the same environment

**Comment by malfet** [comment]
Another interesting datapoint:
```
FAIL [1801.015s]: test_common_errors (__main__.RendezvousEnvTest)
``` <- i.e. for the test to fail one needs to wait for 30 min

**Comment by H-Huang** [comment]
+1 on the ordering issue. Something must be setting the WORLD_SIZE environment variable before this test is run which causes the issue.

**Comment by samestep** [comment]
So in that case, would a fix be to modify the `without` function in that test, so that it unsets vars if they turn out to somehow be already set?

**Comment by H-Huang** [comment]
@samestep that would work! I think a cleaner solution would be to read from a mocked environment specific for that test instead of the global one. I sent out a PR with the changes.

**Comment by malfet** [comment]
I can confirm that the following environment variables were added before test is run:
```
BACKEND=gloo
INIT_METHOD=file:///tmp/tmpu73gqc0r/shared_init_file
WORLD_SIZE=2
TEST_REPORT_SOURCE_OVERRIDE=dist-gloo
```

**Comment by H-Huang** [comment]
I think this PR should fix it https://github.com/pytorch/pytorch/pull/53537
