### ISSUE TITLE
init._calculate_fan_in_and_fan_out needlessly indexing the weight tensor instead of using its shape.

### ISSUE THREAD

**Issue by JeanKossaifi** [pytorch/pytorch#53540]
## 🐛 Bug

Currently, `init._calculate_fan_in_and_fan_out` computes the receptive field by directly indexing the weight tensor instead of just using the shape:
https://github.com/pytorch/pytorch/blob/1588df6b99310307d8d62d4bfcc309aedf2d404e/torch/nn/init.py#L277

This means that, when [extending PyTorch's tensor class](https://pytorch.org/docs/stable/notes/extending.html), e.g. for lazy access, explicitly indexing the tensor will force a call to `tensor()` and reconstruct the full tensor/explicitly access the elements. 

Since the init sub-module doesn't check for torch_function, it is not possibly to override the init functions. Simply using the shape allows to avoid that.

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Thanks for reporting this, @JeanKossaifi ! I agree it's not ideal that the current implementation disallows overriding the init functions for a custom tensor-like type.

Unfortunately, one issue with the proposed fix is that TorchScript does not currently support the built-in `reduce` function (as shown in the failing CI test output).

Can you try something a bit dumber: iterate over the tensor shape to compute `receptive_field_size`?

**Comment by JeanKossaifi** [comment]
Good point, thanks, I fixed it by removing `prod` altogether, the change is much smaller now.
