### ISSUE TITLE
Add helper function to easily access quantized scripted model weights for linear modules 

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#53542]
From pytorch forums:https://discuss.pytorch.org/t/how-to-get-the-weights-of-quantized-module/113750

Let me have the following module:

m = nn.quantized.dynamic.Linear(20, 30, dtype=torch.qint8)
m = torch.jit.script(m)

--
Current solution is hacky: Use the _weight_bias() method to get the weights back: (wt,bias) = m._packed_params._weight_bias()

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
can you do m._packed_params.weight() and m._packed_params.bias()?

**Comment by vkuzo** [comment]
closing as @jerryzh168 shared a solution in the comments
