### ISSUE TITLE
[feature request] Batch linear algebra operations

### ISSUE THREAD

**Issue by Taha-Bahadori** [pytorch/pytorch#5354]
Linear algebra operations such as `svd()` and `symeig()` only support a single matrix input (e.g.,  a matrix of size `M x N`).   I request to extend these functions to support running these operations on batches in parallel on a single GPU machine.  That is, the input will take the form of `B x M x N` sized tensors and the function will calculate `B` operations in parallel on a GPU.

**Simpler feature request**: Given that It seems that they support batch QR decomposition, can you implement the batch version of `torch.qr()`?
http://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__group__orthogonal__batched.html

Given batch QR, I can compute batch `torch.symeig()` using [the famous QR algorithm](https://en.wikipedia.org/wiki/QR_algorithm).

**Comment by soumith** [comment]
@Taha-Bahadori  thanks for the request and the private message you sent.

This is something that we can do, but it's a large undertaking, because the GPU code that we use (MAGMA) doesn't support batched SVD.

Magma has a few routines that are batched, which are listed at http://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__batched.html

Anything outside this scope, it's ~1 month engineering work for us.
Hence, we are not able to raise the priority of this feature at this point.

cc: @SsnL to make sure I didn't mis-speak any details.

**Comment by SsnL** [comment]
As @soumith said above, neither magma nor cublas supports batched gesvd or syevd at the moment. When they add support for these methods, we'd be happy to add them. That said, I always want to add existing batched blas methods in cublas (e.g. getri), but unfortunately there are more important bug fixes for us currently.

**Comment by Taha-Bahadori** [comment]
@soumith and @SsnL: Thank you for your quick responses. 

Can I create an issue to create the batched version of `torch.qr()` based on MAGMA? It seems that they support batch QR decomposition:
http://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__group__orthogonal__batched.html

Given batch QR, I can compute batch `torch.symeig()` using [the famous QR algorithm](https://en.wikipedia.org/wiki/QR_decomposition).

**Comment by SsnL** [comment]
This is indeed a reasonable thing to implement, but I think tracking it in this issue should be sufficient. It would be great if you can add this case in the top post :)

**Comment by Taha-Bahadori** [comment]
@SsnL : Just updated the top post.  Can you prioritize it?

**Comment by SsnL** [comment]
I'm sorry, but I have higher priority tasks to finish. I've added this on my list of things to do, but it'll probably at lease a couple weeks later. If you or anyone else want to implement it, I am happy to review it.

**Comment by Taha-Bahadori** [comment]
@SsnL: No problem.  Can you give me a quick pointer where to implement this function?

**Comment by SsnL** [comment]
@Taha-Bahadori Sure. Basically add the batched implementation in https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorLapack.c#L758 (CPU) and https://github.com/pytorch/pytorch/blob/c681b03d374e4010a875018c8a8a0485c40ceb9b/aten/src/THC/generic/THCTensorMathMagma.cu#L632 (CUDA) (you may need to write new / change existing size checks). Also, please add tests in https://github.com/pytorch/pytorch/blob/c681b03d374e4010a875018c8a8a0485c40ceb9b/test/test_torch.py#L2047.

**Comment by gobbedy** [comment]
Hi @SsnL thanks for your great work.

Are you aware whether batch linear algebra operations will be available in pytorch 1.0? In particular the batch linear system solvers available in MAGMA.

**Comment by zjhthu** [comment]
So, is there any solution for batch `symeig()` on GPU except for using for loops now?

**Comment by drohde** [comment]
This looks helpful: https://www.pugetsystems.com/labs/hpc/PyTorch-for-Scientific-Computing---Quantum-Mechanics-Example-Part-3-Code-Optimizations---Batched-Matrix-Operations-Cholesky-Decomposition-and-Inverse-1225/

**Comment by Yannick-S** [comment]
Wow that article looks great. I personally need SVD/symdiag to work on batches. I havne't done much programming on GPU so don't know what is possible. Do you believe that it might make sense to use the QR algorithm using Givens Rotations by trying to copy the ideas from the post 'above this one'?
( i have about 1000 to 2000 matrices of size 3x3, they are symetric positive definite.)

**Comment by Taha-Bahadori** [comment]
The following paper might be related:
**Backpropagation-Friendly Eigendecomposition**
Wang, Dang, Hu, Fua, Salzmann
https://arxiv.org/abs/1906.09023

**Comment by vishwakftw** [comment]
@soumith can this be closed in favor of #7500?
