### ISSUE TITLE
str in native_functions.yaml shouldn't translate to owning std::string type; it should compile to non-owning c10::string_view

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53546]
Currently if you write `str` in `native_functions.yaml`, this translates into owning `std::string` in the dispatcher calling convention. This is bad because it necessitates a bunch of copies whenever you call functions that accept `std::string`. A non-owning type like `c10::string_view` should be used for the translation instead.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @swolchok @smessmer

**Comment by ezyang** [comment]
cc @parmeet @cpuhrsch apparently this is affecting torchtext as well, and they have hand bound their kernels with pybind11 to avoid the inefficiency

**Comment by kurtamohler** [comment]
@ezyang, @antocuni brought up a good point to me: if we use only `string_view`s internally to point to a string that was created in Python, then the Python string could potentially be destroyed, invalidating the `string_view`. I think one example of this would be if a pytorch function that takes a string argument is called, then the Python string is deleted, and then the backward function is called. If the backward pass only has access to a `string_view`, then we have a problem.

I would think that this could be solved by having pytorch create just one internal copy of the string in the forward pass, which gets added to the graph, and then `string_view`s pointing to the copy would be given to all the internal functions that need to read the string. Does that idea make sense?

Another question: how significant do we expect the performance improvement to be?

**Comment by ezyang** [comment]
This is fine. In backwards there are a number of situations where we are obligated to perform a copy to save for backwards, and view-like objects are precisely a case of this and there's existing logic that would just be extended for string views.

The perf benefit is significant enough that torchtext is hand binding their kernels in Python to avoid the inefficiency here.

**Comment by smessmer** [comment]
Note that changing from string to string_view will improve direct calls but std::string by value could be better for use cases going through boxing, e.g. backens fallbacks. IValue can only store owning types.

**Comment by kurtamohler** [comment]
Hey @smessmer, I am getting some invalid `string_view`s in the CI jobs for my PR, and they seem to be related to boxing and IValue. I tried to make the proper changes to fix it, but I don't totally understand what IValue and boxing are, so it's difficult to figure out what I'm doing wrong. Do you know if there's an explanation in the codebase somewhere?

**Comment by cpuhrsch** [comment]
@parmeet - now that this merged we can revisit our pybind11 dual bindings
