### ISSUE TITLE
[nnc] Can't handle vectorization of intermediate tensors

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#53553]
#53552 adds a unit test that demonstrates the issue; basically NNC doesn't handle accesses to intermediate tensors (`FunctionCall` in the weird tensor IR lingo) in vectorization, so you're out of luck if you want to optimize a downstream tensor.

**Comment by ZolotukhinM** [comment]
Yeah, I'll hopefully fix this by replacing FunctionCalls with Loads.
