### ISSUE TITLE
FX dynamic quantization warnings

### ISSUE THREAD

**Issue by HDCharles** [pytorch/pytorch#53566]
## 🐛 Bug

Get a warning when trying to forward pass on fx dynamically quantized models.

## To Reproduce

import torch
import torch.optim as optim
import torchvision.models as models
import torch.quantization.quantize_fx as quantize_fx

device = 'cpu'
model = models.mobilenet_v2()
model.eval()
qconfig_dict = {"": torch.quantization.default_dynamic_qconfig}
model = quantize_fx.prepare_fx(model, qconfig_dict)
model = quantize_fx.convert_fx(model).to(device)
example_inputs = torch.randn((32, 3, 3, 3)).to(device)
model(example_inputs)

## Expected behavior

no warning

## Actual behabvior

warning:

(torchbenchmark) /home/<username>/local/benchmark/torchbenchmark/models/mobilenet_v2_quantized $python repro.py
/home/<username>/local/miniconda3/envs/torchbenchmark/lib/python3.7/site-packages/torch/quantization/fx/quantization_patterns.py:291: UserWarning: dtype combination: (torch.float32, torch.qint8, torch.quint8) is not supported by Conv supported dtype combinations are: [(torch.quint8, torch.qint8, None)]
  "supported dtype combinations are: {}".format(dtypes, supported_dtypes))
/home/<username>/local/miniconda3/envs/torchbenchmark/lib/python3.7/site-packages/torch/quantization/fx/quantization_patterns.py:160: UserWarning: dtype combination: (torch.float32, torch.qint8, torch.quint8) is not supported by <built-in function add> supported dtype combinations are: [(torch.quint8, torch.qint8, None), (torch.float16, torch.float16, None)]
  "supported dtype combinations are: {}".format(dtypes, self.binary_op, supported_dtypes[self.binary_op]))

## Environment

PyTorch version: 1.9.0.dev20210305
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB
GPU 4: Tesla P100-SXM2-16GB
GPU 5: Tesla P100-SXM2-16GB
GPU 6: Tesla P100-SXM2-16GB
GPU 7: Tesla P100-SXM2-16GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] numpy==1.17.5
[pip3] torch==1.9.0.dev20210305
[pip3] torch-struct==0.4
[pip3] torchfile==0.1.0
[pip3] torchtext==0.10.0.dev20210305
[pip3] torchvision==0.9.0.dev20210305
[pip3] torchviz==0.0.1
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.3.0            py37h54f3939_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.17.5                   pypi_0    pypi
[conda] pytorch                   1.9.0.dev20210305 py3.7_cuda10.2_cudnn7.6.5_0    pytorch-nightly
[conda] torch-struct              0.4                       dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchtext                 0.10.0.dev20210305            py37    pytorch-nightly
[conda] torchvision               0.9.0.dev20210305      py37_cu102    pytorch-nightly
[conda] torchviz                  0.0.1                    pypi_0    pypi
## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Just wanted to clarify, originally we saw two error messages:

```
/home/cdhernandez/local/miniconda3/envs/torchbenchmark/lib/python3.7/site-packages/torch/quantization/fx/quantization_patterns.py:291: UserWarning: dtype combination: (torch.float32, torch.qint8, torch.quint8) is not supported by Conv supported dtype combinations are: [(torch.quint8, torch.qint8, None)]
  "supported dtype combinations are: {}".format(dtypes, supported_dtypes))
/home/cdhernandez/local/miniconda3/envs/torchbenchmark/lib/python3.7/site-packages/torch/quantization/fx/quantization_patterns.py:160: UserWarning: dtype combination: (torch.float32, torch.qint8, torch.quint8) is not supported by <built-in function add> supported dtype combinations are: [(torch.quint8, torch.qint8, None), (torch.float16, torch.float16, None)]
```

I think the "built-in function add" got stripped from the original paste for some reason

**Comment by jerryzh168** [comment]
I don't see a problem in the warning message actually, dynamic quantization is not supported for Conv and the binary ops(like add/mul etc.), that's why we have the warning. To configure the qconfig correctly I think we can do something like:

```python
qconfig_dict = {
"object_type": [
   (torch.nn.functioinal.linear, torch.quantization.default_dynamic_qconfig),
   (torch.nn.Linear, torch.quantization.default_dynamic_qconfig),
   # list all functionals/modules/torch ops that you would like to dynamically quantize here
]
}

model = prepare_fx(model, qconfig_dict)

```

**Comment by vkuzo** [comment]
> dtype combination: (torch.float32, torch.qint8, torch.quint8)

Perhaps we can change the error message to describe the issue so it's easier to understand?  Perhaps mentioning what the three elements of this tuple correspond to, etc.  Ideally "dynamic quantization is not supported for Conv and the binary ops(like add/mul etc.), that's why we have the warning" is obvious from the message itself.
