### ISSUE TITLE
how to use logging in libtorch C++ ? any example ? Many thanks

### ISSUE THREAD

**Issue by yulinhuyang** [pytorch/pytorch#53580]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @yf225 @glaringlee

**Comment by skyline75489** [comment]
I don't really understand. Why would you want to use the logger provided by libtorch, instead of use your own logger?

**Comment by mrshenli** [comment]
+1 to @skyline75489 's comments above. Is there any reason that you need a logger from libtorch instead of using 3rd-party loggers?

Besides, could you please use forum for questions? Thanks. https://discuss.pytorch.org/c/c/11

**Comment by glaringlee** [comment]
@yulinhuyang
libtorch defined the logging here:
https://github.com/malfet/pytorch/blob/5cee6c87bb4a6e3eaf0f6185a47fbf44306a2f7b/c10/util/Logging.h
But I recommend you to use your own logger instead. eg. GLog.

**Comment by yulinhuyang** [comment]
Thank you all. I understand!

**Comment by yulinhuyang** [comment]
Thank you all. I understand!
