### ISSUE TITLE
cudatoolkit=11.1 not available in PyTorch channel for Python 3.6/3.7 on Windows

### ISSUE THREAD

**Issue by BarclayII** [pytorch/pytorch#53593]
## 🐛 Bug

I tried the following command as per official site:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch
```

It reports a PackageNotFound error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.1
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.8
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: CUDA 11.1
 - GPU models and configuration:
 - Any other relevant information:

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by walterddr** [comment]
https://github.com/pytorch/pytorch.github.io/pull/616/
