### ISSUE TITLE
AttributeError: module 'torch' has no attribute '_multinomial_alias_setup'

### ISSUE THREAD

**Issue by tinkueg** [pytorch/pytorch#53592]
## 🐛 Bug

AttributeError: module 'torch' has no attribute '_multinomial_alias_setup'
## To Reproduce

 J, q = torch._multinomial_alias_setup(weights)
 torch._multinomial_alias_draw(q, J, n)

AttributeError: module 'torch' has no attribute '_multinomial_alias_setup'

## Expected behavior

I was using torch._multinomial_alias_setup(self.weights) and torch._multinomial_alias_setup(self.weights) with PyTorch 1.7 release and now it's broken.

## Environment
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.9.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: Quadro P4000
Nvidia driver version: 460.39
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py36h8c4c3a4_2    conda-forge
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.2.0            py36h7c3b610_1    conda-forge
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.6_cuda10.1_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.8.0                      py36    pytorch
[conda] torchvision               0.9.0                py36_cu101    pytorch

**Comment by mrshenli** [comment]
Hey @tinkueg for private APIs start from "_", we usually don't offer backward compatibility. 

cc @mruberry Is there a counterpart for `_multinomial_alias_setup` in 1.8?

**Comment by mruberry** [comment]
Good question, @mrshenli. Looks like the operations were removed in https://github.com/pytorch/pytorch/pull/50489. @ngimel would probably know better than me what our user story is.

**Comment by ngimel** [comment]
It's a private undocumented API, as @mrshenli says, we didn't see it being used and removed it as part of TH migration. There's `multinomial` that provides sampling from multinomial distribution.

**Comment by mruberry** [comment]
@tinkueg, is torch.multinomial() sufficient for your use case? (See https://pytorch.org/docs/master/generated/torch.multinomial.html?highlight=multinomial#torch.multinomial.) If not, would you like to request a new feature? We could turn this issue into a feature request.

**Comment by tinkueg** [comment]
> @tinkueg, is torch.multinomial() sufficient for your use case? (See https://pytorch.org/docs/master/generated/torch.multinomial.html?highlight=multinomial#torch.multinomial.) If not, would you like to request a new feature? We could turn this issue into a feature request.

@mruberry Thanks for looking into the issue and responding! After a lot of digging into PyTorch distribution we found _multinomial_alias_setup and draw functions. The "torch.multinomial" does not fulfil our need as we use a particular distribution to generate the samples for our scientific project. It would be great if you could bring it back quickly in any form.

**Comment by tinkueg** [comment]
> Hey @tinkueg for private APIs start from "_", we usually don't offer backward compatibility.
> 
> cc @mruberry Is there a counterpart for `_multinomial_alias_setup` in 1.8?

Thanks for looking into the issue and responding!  We use `_multinomial_alias_setup` and 'draw' to generate samples from a given distribution and it is one of the key part of our project. If you could bring it back it would be great!

**Comment by mruberry** [comment]
Could you elaborate more on your particular need, @tinkueg? Maybe with a commented code snippet showing the previous distribution setup?

**Comment by tinkueg** [comment]
> Could you elaborate more on your particular need, @tinkueg? Maybe with a commented code snippet showing the previous distribution setup?

@mruberry Given a probability tensor (weight = torch.tensor([0.1,0.2,0.7]) generate 1000 samples. If you simply use 'torch.distributions.Multinomial' or 'torch.distributions.categorical' then you are limited by size of (weight -1). It is funny that there is another 'torch.multinomial' function that exists which might give you 1000 samples with replacement but I think there is a problem with statistics of the result. There is another implementation possible but suspect that it will be slow. I am still investigating if I can use Multinomial with some workaround with similar statistics and speed of sampling. Thanks!

**Comment by ngimel** [comment]
Can you elaborate on what statistics problems are you seeing with `torch.multinomial`? For your example I'm getting expected results:
```
In [3]: probs = torch.tensor([0.1,0.2,0.7])                                                                                                                                                                  

In [4]: res = probs.multinomial(1000, replacement=True)                                                                                                                                                      

In [5]: (res==0).sum()                                                                                                                                                                                       
Out[5]: tensor(106)

In [6]: (res==1).sum()                                                                                                                                                                                       
Out[6]: tensor(194)

In [7]: (res==2).sum()                                                                                                                                                                                       
Out[7]: tensor(700)

In [8]: probs = probs.cuda()                                                                                                                                                                                 

In [9]: res = probs.multinomial(1000, replacement=True)                                                                                                                                                      

In [10]: print((res==0).sum(), (res==1).sum(), (res==2).sum())                                                                                                                                               
tensor(101, device='cuda:0') tensor(189, device='cuda:0') tensor(710, device='cuda:0')
```
torch.distributions.Multinomial and categorical use `torch.multinomial` under the hood iirc, so you'd be seeing the same issues there.

**Comment by tinkueg** [comment]
Hi,

Thanks for your help! I found other solution hence it is fine to remove _multinomial_alias_setup.

Thanks,
MKG
