### ISSUE TITLE
ManyLinux v1.8 release .whl for AArch64 (Arm) does not work on CentOS 8

### ISSUE THREAD

**Issue by nSircombe** [pytorch/pytorch#53597]
## 🐛 Bug

The recently released PyTorch v1.8 whls (torch-1.8.0-cp3X-cp3Xm-manylinux2014_aarch64.whl) does not work with CentOS 8, on `import torch` I get the following error message:

```
OSError: <path-to-my-python-venv>/lib64/python3.6/site-packages/torch/lib/libtorch_global_deps.so: ELF load command alignment not page-aligned
```

This appears to be an issue previously encountered with NumPy ManyLinux builds (https://github.com/numpy/numpy/issues/16677) where the whl was built with the wrong pagesize.

The same issue appears to affect the nightly .whls from https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html too.

_Note:_
- _Issue observed with both python 3.6 and 3.8 on CentOS 8.3;_
- _Ubuntu 20.10 with Python 3.8.6 appears to work as expected._

## To Reproduce

1. Install the 1.8 whl with pip on a CentOS 8 machine
```
pip install --upgrade pip
pip install torch torchvision -f https://download.pytorch.org/whl/torch_stable.html  
```
2. Attempt to `import torch`

## Expected behavior

`import torch` should import the installed PyTorch module without issue.

## Environment

_Note: no PyTorch version reported here, since `import torch` fails._

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux 8 (aarch64)
GCC version: (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Clang version: 10.0.1 (Red Hat 10.0.1-1.module_el8.3.0+467+cb298d5b)
CMake version: version 3.11.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[conda] Could not collect
```

cc @malfet @seemethere @walterddr

**Comment by jspisak** [comment]
cc @malfet

**Comment by malfet** [comment]
torch-1.8.1 aarch64 wheel should be compatible with RHEL/CentOS 8 64Kb aligned pages

**Comment by nSircombe** [comment]
Hi @malfet,
That works for me if I build my own whls, and I've just tested the latest 1.8.1 release from https://download.pytorch.org/whl/torch_stable.html on RHEL and Ubuntu systems here and it appears to work fine out of the box, cheers.
