### ISSUE TITLE
Typo inport -> import

### ISSUE THREAD

**Issue by ericjang** [pytorch/pytorch#53590]
I tried to send a PR for this

https://github.com/ericjang/pytorch/pull/1/commits/d37bd17a2953d2a5d7c900ecbb38bbf306b5fe4d

but looks like it'll be easier for authorized members to just fix this one-char typo than me going through the authorization process.

**Comment by Chillee** [comment]
Seems like your CLA passes - good enough for me :)

https://github.com/pytorch/pytorch/pull/53589/checks?check_run_id=2063124460

**Comment by Chillee** [comment]
Closed by https://github.com/pytorch/pytorch/pull/53589
