### ISSUE TITLE
Add complex autograd support for torch.Tensor.index

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53605]
```
>>> x = torch.ones(size=(10, 10), dtype=torch.cdouble, requires_grad=True)
>>> y=x.clone()
>>> mask = torch.zeros(size=(10, ), dtype=torch.bool)
>>> y.index_put_((mask, ), y[mask], accumulate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: index does not support automatic differentiation for outputs with complex dtype.
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa

**Comment by kurtamohler** [comment]
It looks like `index_put_` already has complex autograd support. In the code snippet in the above issue description, the error is actually coming from `y[mask]`--notice that the error message mentions `index`, not `index_put_`. The following shows complex autograd working properly for `index_put_`:

```python
>>> import torch
>>> a = torch.ones(10, dtype=torch.cdouble, requires_grad=True)
>>> b = a.clone()
>>> b.retain_grad()
>>> mask = torch.ones(10, dtype=torch.bool)
>>> mask[::2] = False
>>> value = torch.ones(5, dtype=b.dtype) * 10
>>> b.index_put_((mask,), value)
tensor([ 1.+0.j, 10.+0.j,  1.+0.j, 10.+0.j,  1.+0.j, 10.+0.j,  1.+0.j, 10.+0.j,  1.+0.j, 10.+0.j],
       dtype=torch.complex128, grad_fn=<IndexPutBackward>)
>>> b.sum().backward()
>>> b.grad
tensor([1.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       dtype=torch.complex128)
```

**Comment by anjali411** [comment]
It throws an error if you try setting `accumulate=True`!

**Comment by kurtamohler** [comment]
@anjali411, I still see correct behavior and no error with `accumulate=True`:

```
>>> a = torch.ones(10, dtype=torch.cdouble, requires_grad=True)
>>> b = a.clone()
>>> b.retain_grad()
>>> mask = torch.ones(10, dtype=torch.bool)
>>> mask[::2] = False
>>> value = torch.ones(5, dtype=b.dtype) * 10
>>> b.index_put_((mask,), value, accumulate=True)
tensor([ 1.+0.j, 11.+0.j,  1.+0.j, 11.+0.j,  1.+0.j, 11.+0.j,  1.+0.j, 11.+0.j,  1.+0.j, 11.+0.j],
       dtype=torch.complex128, grad_fn=<IndexPutBackward>)
>>> b.sum().backward()
>>> b.grad
tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       dtype=torch.complex128)
```

**Comment by anjali411** [comment]
Umm I just ran the python code attached in the issue description again:
```
>>> x = torch.ones(size=(10, 10), dtype=torch.cdouble, requires_grad=True)
>>> y=x.clone()
>>> mask = torch.zeros(size=(10, ), dtype=torch.bool)
>>> y.index_put_((mask, ), y[mask], accumulate=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: index does not support automatic differentiation for outputs with complex dtype.
```

**Comment by kurtamohler** [comment]
@anjali411 yes, I do get that error, but again, the error doesn't seem to come from `index_put_`, it comes from the `index` call in `y[mask]`:

```python
>>> x = torch.ones(size=(10, 10), dtype=torch.cdouble, requires_grad=True)
>>> y = x.clone()
>>> mask = torch.zeros(size=(10, ), dtype=torch.bool)
>>> y[mask]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: index does not support automatic differentiation for outputs with complex dtype.
```

**Comment by anjali411** [comment]
ohh right ok I see what you are saying now! could you create a PR that also fixes the indexing support as well as adds an OpInfo for `index_put_`?

**Comment by kurtamohler** [comment]
Sure! I'll update the name of this issue as well

**Comment by kurtamohler** [comment]
Hey @anjali411, I started adding an OpInfo for `index`/`__getitem__` to test the complex case, and I saw that `test_duplicate_method_tests___getitem___cpu_float32` fails because we have existing method tests for it. I figure it's probably best for me to convert those tests into OpInfo tests, does that sound good to you?

**Comment by anjali411** [comment]
> Hey @anjali411, I started adding an OpInfo for `index`/`__getitem__` to test the complex case, and I saw that `test_duplicate_method_tests___getitem___cpu_float32` fails because we have existing method tests for it. I figure it's probably best for me to convert those tests into OpInfo tests, does that sound good to you?

yeah that sounds good!

> although if we do choose to do it here, I'll make a note in #54301.

sounds good again!
