### ISSUE TITLE
Complex autograd is supported for torch.Tensor.masked_scatter_ but untested

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53608]
These skips (which were added at the time since masked_fill still hadn't been ported on CUDA) should be removed now that the port is complete and we can add dispatch for complex types for masked_fill kernel on CUDA. https://github.com/pytorch/pytorch/blob/0a97712326682fa6e70d263e5e275a52c8dcaf38/torch/testing/_internal/common_methods_invocations.py#L2027
```
>>> dest = torch.randn(10, dtype=torch.cdouble, device='cuda', requires_grad=True).clone()
>>> src = torch.randn(10, dtype=torch.cdouble, device='cuda', requires_grad=True)
>>> mask = torch.tensor((0, 0, 0, 0, 1, 0, 1, 0, 1, 0), dtype=torch.bool, device='cuda')
>>> dest.masked_scatter_(mask, src)
tensor([ 0.4441-0.2455j,  0.2870-0.1043j, -0.6185+0.6146j, -0.6428+0.5322j,
         0.7472+0.1586j, -0.5039+2.1577j,  0.1907+0.7764j,  0.2066+0.6968j,
        -0.2815+0.2045j, -1.3827+1.7941j], device='cuda:0',
        dtype=torch.complex128, grad_fn=<MaskedScatterBackward>)
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa

**Comment by kshitij12345** [comment]
Reference to previous attempt : https://github.com/pytorch/pytorch/pull/52483

**Comment by anjali411** [comment]
@kshitij12345 would you like to create a new PR (with the windows tests disabled) since the old PR was unlanded due to unrelated failures?

**Comment by kshitij12345** [comment]
Sure. Will tag you on the new PR soon.
