### ISSUE TITLE
nvidia-smi. Problema para ejecutar un archivo.exe

### ISSUE THREAD

**Issue by acousticdragon** [pytorch/pytorch#53609]
Mi tarjeta grafica es una intel graphics 520 hd, y quiero ejecutar un archivo el cual me pide los drivers de una tarjeta grafica nvidia

![image](https://user-images.githubusercontent.com/80138120/110498423-1181ad80-80d6-11eb-942c-99036fd4d790.png)

Quisiera saber si hay alguna forma de emular virtualmente el GPU nvidia, o alguna forma para que el programa trabaje efectivamente! 

cc @ngimel @aocsa @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by malfet** [comment]
@acousticdragon please run `python -m torch.utils.collect_env` and posts its results here. 

There are no easy ways of emulating NVIDIA GPU, but pytorch build with GPU support should work correctly for CPU-only workloads. Please make sure that models that you've download do not target GPUs (or convert them to CPU only models).

**Comment by acousticdragon** [comment]
![image](https://user-images.githubusercontent.com/80138120/110532735-faee4d00-80fb-11eb-990b-5ac837a8aea9.png)
Este ha sido el resultado de utilizar el codigo, conda could not collect

**Comment by mantaionut** [comment]
I saw there is a CPU option in Image Enhancing Utility settings, so you could use that if you don't have an Nvidia card. 
Otherwise, you can create an issue in the Image Enhancing Utility since they are the ones using PyTorch CUDA in a situation in which it should use CPU version.
