### ISSUE TITLE
`Interrupted system call` error appearing after updating install today

### ISSUE THREAD

**Issue by meder411** [pytorch/pytorch#5363]
I updated my PyTorch installation this afternoon in order to use LayerNorm, and now code that worked fine before is giving me data loader errors after 2 epochs of training. Training is all on one GPU currently.

```
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    main()
  File "train.py", line 48, in main
    solver.run_wasserstein(num_epochs)
  File "/playpen/meder/projects/point-gan/point_wgan_solver.py", line 551, in run_wasserstein
    sample = data_iter.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line 22, in recv
    return pickle.loads(buf)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/reductions.py", line 68, in rebuild_storage_fd
    fd = multiprocessing.reduction.rebuild_handle(df)
  File "/usr/lib/python2.7/multiprocessing/reduction.py", line 157, in rebuild_handle
    new_handle = recv_handle(conn)
  File "/usr/lib/python2.7/multiprocessing/reduction.py", line 83, in recv_handle
    return _multiprocessing.recvfd(conn.fileno())
OSError: [Errno 4] Interrupted system call
```
The only difference in my code from before and after the install is the addition of 3 LayerNorm layers. Perhaps something got buggy in the update?

I'm currently checking if the same issue occurs without LayerNorm. Not quite sure why that would be the source of the issue though.

- OS: Ubuntu 16.04
- PyTorch version: GitHub source (as of ~6pm EST)
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- CUDA/cuDNN version: 9.0
- GPU models and configuration: Titan X & 2 Titan Z
- GCC version (if compiling from source): 5.4.0

**Comment by SsnL** [comment]
EINTR happens when a syscall is interrupted. It's application's responsibility to catch this and retry. The application here is Python as it happens (and we use) python's multiprocessing.Queue implementation.

So this is a python bug. Before 3.5, EINTR'ed syscalls are not automatically retried. We don't really have much that we can do from our side. 

Therefore, it's unlikely that this error happens consistently for you. 

Python patch: https://www.python.org/dev/peps/pep-0475/
Some discussions are in comments of this PR: https://github.com/pytorch/pytorch/pull/4643
Simply googling the error message also gives you tons of more detailed information from websites like stackoverflow.

**Comment by meder411** [comment]
Fair enough. For what it's worth, I did try the Google/SO/Forums first. It did seem odd, though, that this never appeared for me before the recent update and immediately after occurred on two consecutive runs. It's also not occurring now after I've commented out my LayerNorm layers. Again though, I looked through that (your?) code for that layer and there seems to be no relationship to the error--just an odd coincidence.

Thanks for the quick reply.

**Comment by SsnL** [comment]
Let me know if it happens consistently. Sometimes reboot also solves it.

**Comment by meder411** [comment]
Just a heads up that this is happening consistently. I've tried wrapping it in a try/except with a continue in the except block (as per a few SO answers), but then my program just hangs. Why doesn't PyTorch handle this error itself, rather than relying folks using the library to catch this?

**Comment by SsnL** [comment]
@meder411 Well then I assume that you didn't read the comments in the PR I linked above. By the time this happens, the data transmitting queue is already corrupted and if we try-catch, the next fetch will crash/hang anyways. This is because Python doesn't do this retry. So we can't do much.

**Comment by SsnL** [comment]
@meder411 That said, I'm curious how this is happening consistently for you. Does it work if you do `num_workers=0`?

**Comment by meder411** [comment]
I actually did read the comments, but they're a little beyond my depth of understanding I suppose. I don't often work with system calls, signals, etc.

I will check `num_workers=0` now.

**Comment by meder411** [comment]
`num_workers=0` resolved it. It definitely seems to be that dataloader error, but it didn't add too much to my running time so we're set for now. Thanks for the help!
