### ISSUE TITLE
torch.matmul() gives rounded results for 30xx cards

### ISSUE THREAD

**Issue by kuynzereb** [pytorch/pytorch#53635]
## 🐛 Bug

The product of fp32 matrices looks to be rounded to fp16 on 30xx cards.

## To Reproduce

If I run the following code
```
import torch

device = 'cuda:0'
identity = torch.tensor([[1.0]], dtype=torch.float32, device=device)
vector = torch.tensor([1024.5], dtype=torch.float32, device=device)

product = vector.matmul(identity)
print(product)
```
I get the following result on a machine with 3090 or 3080:
```
tensor([1025.], device='cuda:0')
```

For a machine with 2080 or Titan RTX the result is okay:
```
tensor([1024.5], device='cuda:0')
```

## Expected behavior

The result should not be rounded.

## Environment

PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py36h8c4c3a4_2    conda-forge
[conda] mkl_fft                   1.3.0            py36h92226af_1    conda-forge
[conda] mkl_random                1.2.0            py36h7c3b610_1    conda-forge
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.6_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchvision               0.9.0                py36_cu111    pytorch

**Comment by xwang233** [comment]
That's the feature of TF32. See https://pytorch.org/docs/stable/notes/cuda.html#tf32-on-ampere

**Comment by kuynzereb** [comment]
Ohhh, indeed, thank you. 

I will close the issue then, though I would say that it is quite a questionable feature to be enabled by default. In particular, because now it leads to different results of the same code running with Ampere or not Ampere GPU.
