### ISSUE TITLE
Update torch.symeig doc to correctly reflect that it supports complex tensors too

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53646]
`torch.symeig` currently supports complex tensors however the [doc](https://pytorch.org/docs/1.8.0/generated/torch.symeig.html?highlight=symeig#torch.symeig) says "This function returns eigenvalues and eigenvectors of a **real symmetric matrix input** or a ...". We should probably update this to "... of a real symmetric or hermitian matrix input ..." and probably also explicitly mention that it's supported for complex tensors. Also the equation in the doc should be updated to state input = Vdiag(e)V^H for the complex case. The doc also doesn't clearly state that V is the returned matrix until much later which should be fixed as well.

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa @brianjo @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
I think we can close this because symeig is deprecated in favor of eigh, and the documentation for eigh makes clear that it supports complex tensors. See https://pytorch.org/docs/master/generated/torch.linalg.eigh.html#torch.linalg.eigh

What do you think, @anjali411?
