### ISSUE TITLE
Add complex autograd support for torch.Tensor.index_put_

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53645]
It also looks like autograd for `torch.Tensor.index_put_` is not even being tested for floating point tensors correctly.
```
>>> mask = torch.zeros(size=(10, ), dtype=torch.bool)
>>> y = torch.ones(size=(10, 10), dtype=torch.cdouble, requires_grad=True)
>>> y.clone().index_put_((mask, ), y[mask])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: index does not support automatic differentiation for outputs with complex dtype.
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa

**Comment by sunilkpai** [comment]
This is particularly an important issue for me. I'd like to help address it if possible sooner rather than later, but I've never contributed to PyTorch. What's the best place for me to learn to contribute on this?

**Comment by anjali411** [comment]
Hi @sunilkpai! Glad you are interested in contributing to PyTorch. As a first step, check out our [contribution guide](https://pytorch.org/docs/stable/community/contribution_guide.html). For this task, you could take a look at other similar PRs adding complex autograd support. For e.g., https://github.com/pytorch/pytorch/pull/53240

**Comment by kurtamohler** [comment]
This issues seems to be a duplicate of #53605, right?

**Comment by anjali411** [comment]
@kurtamohler yeah! let's close this issue then
