### ISSUE TITLE
Add complex autograd support for torch.symeig

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#53651]
```
>>> a = torch.randn(5, 5, dtype=torch.cdouble, requires_grad=True)
>>> a = (a + a.transpose(-2, -1).conj()).div_(2)
>>> e, v = torch.symeig(a, eigenvectors=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: symeig does not support automatic differentiation for outputs with complex dtype.
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @aocsa

**Comment by Lezcano** [comment]
As per the documentation of `torch.symeig`
> This function returns eigenvalues and eigenvectors of a real symmetric matrix input or a batch of real symmetric matrices
This function just makes sense for symmetric real inputs. Perhaps what should be improved is the error message. I will get to that now, but that's unrelated to this issue. I believe that this issue can be closed.

**Comment by IvanYashchuk** [comment]
Just adding `'symeig'` to `GRADIENT_IMPLEMENTED_FOR_COMPLEX` of in `tools/autograd/gen_variable_type.py` resolves this issue.
https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_variable_type.py#L73-L95

**Comment by Lezcano** [comment]
Which means that the documentation should be updated as well. I'll do that in a second.
