### ISSUE TITLE
Confusing error when refining variables to `tuple`

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#53657]
## 🐛 Bug

When attempting to refine a variable to `tuple` and unpack it, TorchScript generates a very confusing error message that is not actionable.

## To Reproduce

```
import torch
from typing import Any

def fn(t: Any):
    if isinstance(t, tuple):
        a, b = t
        return a + b

torch.jit.script(fn)
```

Error:
```
RuntimeError:
tuple cannot be used as a tuple:
  File "tuple.py", line 6
def fn(t: Any):
    if isinstance(t, tuple):
        a, b = t
               ~ <--- HERE
        return a + b
```

I think the first `tuple` in error message refers to unspecified tuple type from Python while the second `tuple` in error refers the the string representation of `TupleType` in TorchScript, which always needs to be fully specified.
https://github.com/pytorch/pytorch/blob/a8ecf306dacbfe97b75657deec615828eb38689e/aten/src/ATen/core/jit_type.h#L2410

## Expected behavior

A clear error message should be given to tell users that they are supposed to refine variable to a fully specified tuple type like `typing.Tuple[int, int]`.

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
I also ran into similar problem working on adding two tuples. I wonder why it just returns "tuple" instead of "AnyTupleType" for the string representation? @gmagogsfm

**Comment by tugsbayasgalan** [comment]
What if we change the name from "tuple" to "AnyTupleType"?
