### ISSUE TITLE
Default value for pickle_module incorrect in torch.save documentation

### ISSUE THREAD

**Issue by adamoyoung** [pytorch/pytorch#53661]
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.save.html#torch.save

The default value for pickle_module is a local file path (<module 'pickle' from '/home/matti/miniconda3/lib/python3.7/pickle.py'>)

cc @brianjo @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @adamoyoung. It looks like this issue has been fixed on the nightly build. See:

https://pytorch.org/docs/master/generated/torch.save.html?highlight=save#torch.save
