### ISSUE TITLE
BatchNorm may impact reproducibiltiy with CUDA

### ISSUE THREAD

**Issue by ZyUestc** [pytorch/pytorch#53691]
## 🐛 Bug

Either BatchNorm1d or BatchNorm2d may impact reproducibility with CUDA.

## To Reproduce
I wrote a script to prove. 
In this script, both BatchNorm1d and BatchNorm2d are applied. 
One can delete all either BN1d or BN2d to get similar results.

```
import os
#Enable deterministic about CUBLAS.
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data

import random
import argparse


def set_seed(seed=1): 
    torch.manual_seed(seed)
    random.seed(seed)
    np.random.seed(seed)
    
    if torch.__version__ >= '1.8':
        torch.use_deterministic_algorithms(True)
    else:
        torch.set_deterministic(True)
    
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.cuda.manual_seed_all(seed)
    
    
def hash_module(module: nn.Module) -> float:
    """Return the hash value of the given module.
    Noet: this operation will change the random seed of `torch`.

    Args:
        module (nn.Module): Module.

    Returns:
        float: Hash value.
    """
    hash_value = 0
    with torch.no_grad():
        for param in module.parameters():
            hash_value += (param.norm(p=2))
    return hash_value
    
    
class NoOP(nn.Module): 
    def __init__(self):
        super().__init__()
        
    def forward(self, x):
        return x
    
def run(args):
    set_seed(1)
    
    X = torch.rand(10000, 1, 28, 28, dtype=torch.float32)
    print("Norm of X: ", X.norm(p=2))
    
    dataset = data.TensorDataset(
        X, 
        torch.randint(0, 1, (10000,))
    )
    
    dataLoader = data.DataLoader(dataset, batch_size=64, shuffle=False)
    
    model = nn.Sequential(
        nn.Conv2d(1, 16, 3, 1, 1),
        nn.BatchNorm2d(16) if args.bn else NoOP(),
        nn.ReLU(inplace=True),
        nn.Conv2d(16, 16, 7, 3, 0),
        nn.BatchNorm2d(16) if args.bn else NoOP(),
        nn.ReLU(inplace=True),
        nn.Flatten(1),
        nn.Linear(16 * 8 * 8, 16 * 4 * 4),
        nn.BatchNorm1d(16 * 4 * 4) if args.bn else NoOP(),
        nn.ReLU(inplace=True),
        nn.Linear(16 * 4 * 4, 8 * 2 * 2),
        nn.BatchNorm1d(8 * 2 * 2) if args.bn else NoOP(),
        nn.ReLU(inplace=True),
        nn.Linear(32, 10)
    )
    if args.cuda:
        model = model.cuda()
    
    print("Norm of model before training: ", hash_module(model))
    
    optimizer = optim.Adam(model.parameters(), lr=1e-4)
    
    for x, y in dataLoader:
        if args.cuda:
            x = x.cuda()
            y = y.cuda()
        
        optimizer.zero_grad()
        y_hat = model(x)
        loss = F.cross_entropy(y_hat, y)
        loss.backward()
        optimizer.step()
        
    print("Norm of model after training: ", hash_module(model))
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--bn", action="store_true")
    parser.add_argument("--cuda", action="store_true")
    args = parser.parse_args()
    
    for i in range(4):
        print("{}-th RUN:".format(i))
        run(args)
    
```

### Without BN and disable CUDA
`python run.py`
```
0-th RUN:
[W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299)
Norm of model after training:  tensor(21.0595)
1-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299)
Norm of model after training:  tensor(21.0595)
2-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299)
Norm of model after training:  tensor(21.0595)
3-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299)
Norm of model after training:  tensor(21.0595)
```
### With BN and disable CUDA. 
`python run.py --bn`

```
0-th RUN:
[W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867)
Norm of model after training:  tensor(50.2153)
1-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867)
Norm of model after training:  tensor(50.2153)
2-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867)
Norm of model after training:  tensor(50.2153)
3-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867)
Norm of model after training:  tensor(50.2153)
```

**One can see that BN does not matter by the comparison of above 2 commands.** 

### Without BN and enable CUDA
`python run.py --cuda`
```
0-th RUN:
[W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299, device='cuda:0')
Norm of model after training:  tensor(21.0595, device='cuda:0')
1-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299, device='cuda:0')
Norm of model after training:  tensor(21.0595, device='cuda:0')
2-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299, device='cuda:0')
Norm of model after training:  tensor(21.0595, device='cuda:0')
3-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(20.4299, device='cuda:0')
Norm of model after training:  tensor(21.0595, device='cuda:0')
```
### With BN and enable CUDA
`python run.py --bn --cuda`
```
0-th RUN:
[W Context.cpp:69] Warning: torch.set_deterministic is in beta, and its design and  functionality may change in the future. (function operator())
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2151, device='cuda:0')
1-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2153, device='cuda:0')
2-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2154, device='cuda:0')
3-th RUN:
Norm of X:  tensor(1616.1311)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2151, device='cuda:0')
```

**There are three kinds of model norm: 50.2151, 50.2153 and 50.2154.**  
## Environment

conda list:

 - Linux
 - python                    3.8.5
 - pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    <unknown>
 - 

cc @ngimel @aocsa @mruberry @kurtamohler @albanD @jbschlosser

**Comment by ngimel** [comment]
What behavior are you observing? You provide only expected behavior.

**Comment by kurtamohler** [comment]
It looks like the results under the "expected behavior" section are actually the observed behavior. I tried reproducing with pytorch 1.7.0 and master with cuda 11.0, and I didn't see any variability with `python run.py --bn --cuda`. So I suspect the issue is specifically with pytorch 1.7.1, cuda 10.2, or some other environmental difference.

@ZyUestc, could you please run the following and post the result?

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by ZyUestc** [comment]
> What behavior are you observing? You provide only expected behavior.

Sorry I wrote `observed behavior` to the `expected bahavior`....

**Comment by ZyUestc** [comment]
> What behavior are you observing? You provide only expected behavior.

@ngimel Sorry for the mistake that I wrote `the observed behavior` to the wrong place....

**Comment by ZyUestc** [comment]
> It looks like the results under the "expected behavior" section are actually the observed behavior. I tried reproducing with pytorch 1.7.0 and master with cuda 11.0, and I didn't see any variability with `python run.py --bn --cuda`. So I suspect the issue is specifically with pytorch 1.7.1, cuda 10.2, or some other environmental difference.
> 
> @ZyUestc, could you please run the following and post the result?
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```

@kurtamohler Thanks for your help! I post it as below:

Collecting environment information...
PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.3 LTS (x86_64)
GCC version: (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 440.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu102    pytorch

**Comment by xwang233** [comment]
I tried this a few times on master branch + cuda 11.2 + cudnn 8.0.5, on 1070 Ti and 2070 Super. I got deterministic behavior in all these cases.  Can you try a nightly build or cuda 11.x build from https://pytorch.org/get-started/locally/ ?

2070 super
```
$ python 53691.py --bn --cuda
0-th RUN:
/home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
  _C._set_deterministic_algorithms(d)
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2162, device='cuda:0')
1-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2162, device='cuda:0')
2-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2162, device='cuda:0')
3-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:0')
Norm of model after training:  tensor(50.2162, device='cuda:0')
```

1070 Ti
```
$ python 53691.py --bn --cuda
0-th RUN:
/home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
  _C._set_deterministic_algorithms(d)
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:1')
Norm of model after training:  tensor(50.2165, device='cuda:1')
1-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:1')
Norm of model after training:  tensor(50.2165, device='cuda:1')
2-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:1')
Norm of model after training:  tensor(50.2165, device='cuda:1')
3-th RUN:
Norm of X:  tensor(1616.4785)
Norm of model before training:  tensor(50.0867, device='cuda:1')
Norm of model after training:  tensor(50.2165, device='cuda:1')
```

<details>
<summary> env </summary>
<p>

```
Collecting environment information...
PyTorch version: 1.9.0a0+git0b84f45
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: Could not collect
CMake version: version 3.19.3

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.67
GPU models and configuration: 
GPU 0: GeForce RTX 2070 SUPER
GPU 1: GeForce GTX 1070 Ti

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+git0b84f45
[conda] Could not collect
```
</p>

</details>

**Comment by ZyUestc** [comment]
> I tried this a few times on master branch + cuda 11.2 + cudnn 8.0.5, on 1070 Ti and 2070 Super. I got deterministic behavior in all these cases. Can you try a nightly build or cuda 11.x build from https://pytorch.org/get-started/locally/ ?
> 
> 2070 super
> 
> ```
> $ python 53691.py --bn --cuda
> 0-th RUN:
> /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
>   _C._set_deterministic_algorithms(d)
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 1-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 2-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 3-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> ```
> 
> 1070 Ti
> 
> ```
> $ python 53691.py --bn --cuda
> 0-th RUN:
> /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
>   _C._set_deterministic_algorithms(d)
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 1-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 2-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 3-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> ```
> 
>  env

Thanks! It may be caused by cuda10.2 ..

**Comment by ZyUestc** [comment]
> I tried this a few times on master branch + cuda 11.2 + cudnn 8.0.5, on 1070 Ti and 2070 Super. I got deterministic behavior in all these cases. Can you try a nightly build or cuda 11.x build from https://pytorch.org/get-started/locally/ ?
> 
> 2070 super
> 
> ```
> $ python 53691.py --bn --cuda
> 0-th RUN:
> /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
>   _C._set_deterministic_algorithms(d)
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 1-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 2-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> 3-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:0')
> Norm of model after training:  tensor(50.2162, device='cuda:0')
> ```
> 
> 1070 Ti
> 
> ```
> $ python 53691.py --bn --cuda
> 0-th RUN:
> /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
>   _C._set_deterministic_algorithms(d)
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 1-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 2-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> 3-th RUN:
> Norm of X:  tensor(1616.4785)
> Norm of model before training:  tensor(50.0867, device='cuda:1')
> Norm of model after training:  tensor(50.2165, device='cuda:1')
> ```
> 
> env

@xwang233 Well, I tried my script on 2080TI and get deterministic behavior... Maybe it's caused by 1080TI?

**Comment by ZyUestc** [comment]
> > I tried this a few times on master branch + cuda 11.2 + cudnn 8.0.5, on 1070 Ti and 2070 Super. I got deterministic behavior in all these cases. Can you try a nightly build or cuda 11.x build from https://pytorch.org/get-started/locally/ ?
> > 2070 super
> > ```
> > $ python 53691.py --bn --cuda
> > 0-th RUN:
> > /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
> >   _C._set_deterministic_algorithms(d)
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:0')
> > Norm of model after training:  tensor(50.2162, device='cuda:0')
> > 1-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:0')
> > Norm of model after training:  tensor(50.2162, device='cuda:0')
> > 2-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:0')
> > Norm of model after training:  tensor(50.2162, device='cuda:0')
> > 3-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:0')
> > Norm of model after training:  tensor(50.2162, device='cuda:0')
> > ```
> > 
> > 
> > 1070 Ti
> > ```
> > $ python 53691.py --bn --cuda
> > 0-th RUN:
> > /home/xwang/Developer/pytorch/torch/__init__.py:429: UserWarning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (Triggered internally at  ../aten/src/ATen/Context.cpp:69.)
> >   _C._set_deterministic_algorithms(d)
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:1')
> > Norm of model after training:  tensor(50.2165, device='cuda:1')
> > 1-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:1')
> > Norm of model after training:  tensor(50.2165, device='cuda:1')
> > 2-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:1')
> > Norm of model after training:  tensor(50.2165, device='cuda:1')
> > 3-th RUN:
> > Norm of X:  tensor(1616.4785)
> > Norm of model before training:  tensor(50.0867, device='cuda:1')
> > Norm of model after training:  tensor(50.2165, device='cuda:1')
> > ```
> > 
> > 
> > env
> 
> @xwang233 Well, I tried my script on 2080TI and get deterministic behavior... Maybe it's caused by 1080TI?

@xwang233 Well I tried on another 1080TI server and get deterministic behavior..................
