### ISSUE TITLE
how should I process the input  when I use torch::nn::parallel::parallel_apply

### ISSUE THREAD

**Issue by yulinhuyang** [pytorch/pytorch#53699]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

I use like this:

torch::nn::parallel::parallel_apply(replicas_module, scattered_inputs, devices);

but replicas_module need two input to forward.

forward( input1 ,input2)

how should I process scattered_inputs ?

**Comment by izdeby** [comment]
Please, use our [forums](https://discuss.pytorch.org/) for questions.
