### ISSUE TITLE
"only 4-D input tensors (batched image-like tensors) are supported.", looking forward tosupport for '5-D input tensor'

### ISSUE THREAD

**Issue by EricKani** [pytorch/pytorch#53697]
I am a medical image analyzer. The common tensors used in our experiments are in 5-D format. Looking forward to support for this~

**Comment by izdeby** [comment]
@EricKani, pytorch supports 5-d tensors.
```
import torch
a = torch.rand(1, 2, 3, 4, 5)
print(a.dim())
```
