### ISSUE TITLE
More pagefile usage with 1.8.0_cuda11.1 than 1.8.0_cuda10 .2

### ISSUE THREAD

**Issue by klyjm** [pytorch/pytorch#53695]
## 🐛 Bug

When I use pytorch 1.8.0_cuda11.1, I find with the same parameters, when the num_worker > 1,the dataloader use more pagefile in Windows 10, I'm not sure it also happens in other OS.

## To Reproduce

When I set the num_worker=8, the pytorch 1.8.0_cuda11.1 use about 32G pagefile, but the 1.8.0_cuda10.2 is about 20G, which some times has the error said the pagefile is not enough.

## Expected behavior

They should be similar.

## Environment
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 456.71
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               11.1.1               heb2d755_7    https://mirror.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl                       2020.2                      256    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.3.0            py38h196d8e1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.0            py38h46781fe_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.1.1            py38h47e9c7a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.19.2           py38hadc3359_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.19.2           py38ha3acd2a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.9.0                py38_cu111    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
## Additional context

cc @ngimel @SsnL @VitalyFedyunin @ejguan @peterjc123 @mszhanyi @skyline75489 @nbcsm @aocsa

**Comment by kit1980** [comment]
Closing as these versions are obsolete.
