### ISSUE TITLE
Windows CPU Build Fails on Link Step

### ISSUE THREAD

**Issue by paddyhoran** [pytorch/pytorch#5372]
**Overview**

I know windows is not officially supported, I can move to #494 if you would prefer...

Until recently I was able to build pytorch from source with the steps below.  I am now getting a linker error.  @peterjc123 thought that #5365 would fix it but the issue remains.

**General Information**

- OS: Windows 10
- PyTorch version: master (cc9d3b2)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.5
- CUDA/cuDNN version: None (CPU Build)
- GPU models and configuration: None
- MSVC version (if compiling from source):  Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64 (using build tools not Visual Studio)

**The following can re-produce the error (once conda-forge channel is added):**
 - conda create -n pytorch-build -y python=3.5 numpy mkl cffi pyyaml git cmake ninja
 - activate pytorch-build
 - git clone --recursive https://github.com/pytorch/pytorch
 - cd pytorch
 - xcopy /Y aten\src\ATen\common_with_cwrap.py tools\shared\cwrap_common.py
 - conda uninstall git -y (causes issues with the linker)
 - set DISTUTILS_USE_SDK=1
 - set CMAKE_GENERATOR=Ninja
 - set NO_CUDA=1
 - python setup.py bdist_wheel

**Error Message**

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\horanp\projects\pytorch-scripts\pytorch -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib/pybind11/include -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib/tmp_install/include -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib/tmp_install/include/TH -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib/tmp_install/include/THNN -IC:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib/tmp_install/include/ATen -IC:\Users\horanp\miniconda3\envs\pytorch-build\lib\site-packages\numpy\core\include -IC:\Users\horanp\miniconda3\envs\pytorch-build\include -IC:\Users\horanp\miniconda3\envs\pytorch-build\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tptorch/csrc/generated/lazy_init_cpu_win.cpp /Fobuild\temp.win-amd64-3.5\Release\torch/csrc/generated/lazy_init_cpu_win.obj -D_THP_CORE /Z7 /EHa /DNOMINMAX -DWITH_NUMPY -DWITH_SCALARS
cl : Command line warning D9025 : overriding '/EHs' with '/EHa'
lazy_init_cpu_win.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib /LIBPATH:C:\Users\horanp\miniconda3\envs\pytorch-build\libs /LIBPATH:C:\Users\horanp\miniconda3\envs\pytorch-build\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" shm.lib /EXPORT:PyInit__C build\temp.win-amd64-3.5\Release\torch/csrc/PtrWrapper.obj build\temp.win-amd64-3.5\Release\torch/csrc/Module.obj build\temp.win-amd64-3.5\Release\torch/csrc/Generator.obj build\temp.win-amd64-3.5\Release\torch/csrc/Size.obj build\temp.win-amd64-3.5\Release\torch/csrc/Dtype.obj build\temp.win-amd64-3.5\Release\torch/csrc/Exceptions.obj build\temp.win-amd64-3.5\Release\torch/csrc/Storage.obj build\temp.win-amd64-3.5\Release\torch/csrc/DynamicTypes.obj build\temp.win-amd64-3.5\Release\torch/csrc/assertions.obj build\temp.win-amd64-3.5\Release\torch/csrc/byte_order.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils.obj build\temp.win-amd64-3.5\Release\torch/csrc/expand_utils.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/invalid_arguments.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/object_ptr.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/python_arg_parser.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_list.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_new.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_numpy.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_dtypes.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_types.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tuple_parser.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_apply.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/tensor_flatten.obj build\temp.win-amd64-3.5\Release\torch/csrc/utils/variadic.obj build\temp.win-amd64-3.5\Release\torch/csrc/allocators.obj build\temp.win-amd64-3.5\Release\torch/csrc/serialization.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/init.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/interpreter.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/ir.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/fusion_compiler.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/graph_executor.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/python_ir.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/test_jit.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/tracer.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/tracer_state.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/python_tracer.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/shape_analysis.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/interned_strings.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/type.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/export.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/autodiff.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/interpreter_autograd_function.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/python_arg_flatten.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/python_compiled_function.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/variable_flags.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/create_autodiff_subgraphs.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/graph_fuser.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/onnx.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/dead_code_elimination.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/common_subexpression_elimination.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/peephole.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/inplace_check.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/canonicalize.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/batch_mm.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/passes/onnx/peephole.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/generated/aten_dispatch.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/script/lexer.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/script/compiler.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/script/init.obj build\temp.win-amd64-3.5\Release\torch/csrc/jit/script/python_tree_views.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/init.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/grad_mode.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/engine.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/function.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/variable.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/saved_variable.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/input_buffer.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/profiler.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_function.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_cpp_function.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_variable.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_variable_indexing.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_engine.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/python_hook.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/VariableType.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/Functions.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/python_torch_functions.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/python_variable_methods.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/python_functions.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/generated/python_nn_functions.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/basic_ops.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/tensor.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/accumulate_grad.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/special.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/utils.obj build\temp.win-amd64-3.5\Release\torch/csrc/autograd/functions/init.obj build\temp.win-amd64-3.5\Release\torch/csrc/onnx/onnx.pb.obj build\temp.win-amd64-3.5\Release\torch/csrc/onnx/onnx.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorDouble.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorFloat.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorHalf.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorLong.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorInt.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorShort.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorChar.obj build\temp.win-amd64-3.5\Release\Users\horanp\projects\pytorch-scripts\pytorch\torch\csrc\generated\TensorByte.obj build\temp.win-amd64-3.5\Release\torch/csrc/generated/AutoGPU_cpu_win.obj build\temp.win-amd64-3.5\Release\torch/csrc/generated/lazy_init_cpu_win.obj /OUT:build\lib.win-amd64-3.5\torch\_C.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\torch/csrc\_C.cp35-win_amd64.lib C:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib\ATen.lib C:\Users\horanp\projects\pytorch-scripts\pytorch\torch\lib\protobuf-nanopb.lib
   Creating library build\temp.win-amd64-3.5\Release\torch/csrc\_C.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\torch/csrc\_C.cp35-win_amd64.exp
tensor_new.obj : error LNK2001: unresolved external symbol "void __cdecl torch::cuda::lazy_init(void)" (?lazy_init@cuda@torch@@YAXXZ)
build\lib.win-amd64-3.5\torch\_C.cp35-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe' failed with exit status 1120

**Comment by peterjc123** [comment]
@paddyhoran Don't worry. #5368 should resolve this.
