### ISSUE TITLE
tensorinv and other linear algebra operators should not do a universal catch all block

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53739]
In the implementation of tensorinv we have:

```
  // If the reshaped self is not invertible catch this error
  Tensor result;
  try {
    result = at::inverse(self.reshape({prod_ind_end, prod_ind_end}));
  } catch (...) {
    TORCH_CHECK(false, "Failed to invert the input tensor, because it is singular.");
  }
```

This is bad code practice. For example, the inner operation could raise an exception because it ran out of memory, and you would still report it as singular. More concretely, this resulted in wrong behavior at https://github.com/pytorch/pytorch/pull/53682/files/29f176c952d5dd5614c933398fe3ed92de690a9e#diff-7e17421f32124016eb8de04dc2f445da5786a28355e1addc72b305466f590180 We shouldn't do a catch all. Ideally, there would be some interface to at::inverse that would let it explicitly signal, e.g., via boolean, that input was singular.

Related https://github.com/pytorch/pytorch/issues/47608

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @glaringlee

**Comment by IvanYashchuk** [comment]
> Ideally, there would be some interface to at::inverse that would let it explicitly signal, e.g., via boolean, that input was singular.

Yes, this is a planned thing to do for many functions that call LAPACK. It hasn't been decided yet what would be a better way to do it https://github.com/pytorch/pytorch/pull/52046#issuecomment-777390137
