### ISSUE TITLE
Warned about presence of old GPU which is disabled

### ISSUE THREAD

**Issue by keipertk** [pytorch/pytorch#5373]
I have a Quadro K620 and K80. Even though I hide the Quadro by excluding it from NVIDIA_VISIBLE_DEVICES, I get a UserWarning when executing Pytorch:

/opt/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py:97: UserWarning: 
    Found GPU1 Quadro K620 which is of cuda capability 5.0.
    PyTorch no longer supports this GPU because it is too old.

This is reproducible using the main-gpu.py code in this Pytorch tutorial directory:
https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/recurrent_neural_network/main-gpu.py

nvidia-smi -a log:
https://pastebin.com/raw/Kei6NwA9

NVIDIA_VISIBLE_DEVICES=1,2 

- OS: Arch Linux, kernel 4.15.2
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 9.1 / 7.0
- GPU models and configuration: Quadro K620, Tesla K80

**Comment by lanpa** [comment]
why don't you set CUDA_VISIBLE_DEVICES ?

**Comment by soumith** [comment]
`CUDA_VISIBLE_DEVICES` is the correct usage. I am not sure if `NVIDIA_VISIBLE_DEVICES` is even valid.

**Comment by keipertk** [comment]
Ah it is NVIDIA_VISIBLE_DEVICES in nvidia-docker.

**Comment by soumith** [comment]
even in `nvidia-docker`, I can confirm that you can use `CUDA_VISIBLE_DEVICES` safely.
