### ISSUE TITLE
Introduce "noarch" tests to the test suite

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#53743]
Currently, we have slow/fast tests in the test suite, which are intended to allow people to add long running tests to the test suite without gumming up wait times for PR CI turnaround.

I propose to add another new category to the test suite: ~~boring~~ noarch tests.  Noarch tests don't exercise any interesting aspects about the underlying CI configuration; in other words, if the noarch tests pass on one configuration, they probably pass everywhere, no need to burn CPU hours in other configurations. A single test configuration will be anointed the "noarch" test runner and we will only run noarch tests there.

Alternative: mark noarch tests as slow tests. I don't like this alternative because it implies that the noarch tests are slow, which they are not; the tests I intend to add in #53682 individually run very fast; there are just a lot of them so it takes time to get through all of them.

cc @mruberry @VitalyFedyunin @walterddr @malfet @seemethere

**Comment by malfet** [comment]
Nice name, but perhaps noarch suffix/decorator would be a better name for such tests.

**Comment by ezyang** [comment]
Sure, NOARCH it is

**Comment by ezyang** [comment]
By the way, something that makes me a little suspicious about the overall concept of slowTests and noarchTests is that there was that recent post about testing in Facebook, where they were like, "The number one most important design constraint in Facebook testing is no customization", because if you let end users customize, there's no way to make broad base changes that let you look over all tests globally and decide "yeah, not going to run those". This is kind of the antithesis of that approach.

**Comment by mruberry** [comment]
Further name bikeshedding suggestion: @singleArch (because it does run on one architecture and we know it's a test).

Seems like we already support a lot of customization in our tests? For example, we allow the test writer to specify they only run on the CPU.

**Comment by seemethere** [comment]
cc @pytorch/pytorch-dev-infra since I feel like some people on the team may have an opinion on this

**Comment by ezyang** [comment]
@mruberry Bikeshed rejected. I particularly like noarch because it matches Python packaging nomenclature, c.f., https://www.anaconda.com/blog/condas-new-noarch-packages

**Comment by walterddr** [comment]
noarch sounds like a great idea. I've recently encounter many times one failure occurs multiple times on different ci configurations which seems a waste of resource esp. for the long running ones (like mypy?).

one question on Ed's previous comment about slow tests, are you referring to the `@slowTests` decorator or the SLOW_TESTS list in run_test.py? seems like the latter one has nothing to do with slowness, in fact many of those listed are pretty fast.

**Comment by janeyx99** [comment]
@walterddr p sure Ed means @slowTest decorator, as that allows developers to mark up any test, pretty much, where as the SLOW_TESTS list (now TARGET_DET_LIST) is applied every PR to only run tests that seem to have been affected.
