### ISSUE TITLE
[JIT] Remove mutation to remove list insertions

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#53757]
## 🚀 Feature

We have a [pass](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_mutation.h#L90
) that rewrites list mutation to functional equivalents. It currently only handles list appends.
```
def successful_remove():
    a = []
    a.append(1)
    a.append(2)
    a.append(3)
    a.append(4)
    return a

fn = torch.jit.script(successful_remove)
graph = fn.graph
torch._C._jit_pass_remove_mutation(graph)
torch._C._jit_pass_constant_propagation(graph)
FileCheck().check("graph").check_next("Constant").check_next("return").run(graph)
self.assertEqual(fn(), successful_remove())
```

To make the pass more general and cover more cases it would be nice to cover list insertions as well.
```
def successful_remove():
    a = []
    a.insert(0, 1)
    a.insert(0, 2)
    a.insert(1 ,3)
    a.insert(-10, 4)
    return a
fn = torch.jit.script(successful_remove)
graph = fn.graph
torch._C._jit_pass_remove_mutation(graph)
torch._C._jit_pass_constant_propagation(graph)
# following check will fail
FileCheck().check("graph").check_next("Constant").check_next("return").run(graph)
self.assertEqual(fn(), successful_remove())
```

cc @gmagogsfm @penguinwu

**Comment by tugsbayasgalan** [comment]
Looks like we have to handle more cases here https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/remove_mutation.cpp#L147

**Comment by penguinwu** [comment]
@tugsbayasgalan This folding is an optimization needed for symbolic shape analysis (which needs list insertion and append). Not sure if we need any other list ops for mutation removal. @eellison if other list ops need to be supported, please add to this issue. I have added support for insertion, can add others if needed.
