### ISSUE TITLE
[ONNX ] Model renders differently with export_params=False

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/pytorch#53782]
## 🐛 Bug

I'm using `torch.onnx.export` to store something akin to a "model summary" that can be nicely viewed with Netron. When I call `onnx.export()` with `export_params=False` the graph is very different (too verbose and difficult to read) than when I pass in `export_params=True`. Using `export_params=True` is not an option because my model file is ~150MB with that, and only ~15KB without it, and I need to log this onnx file in the cloud for every run.

Export with `export_params=True` - everything looks great:

![resnet18_train_with_params](https://user-images.githubusercontent.com/5625518/110722183-ba0f3a80-81c6-11eb-901f-b232fb689bd4.png)

Export with `export_params=False` - expected the same output as above:

![resnet18_train_no_params](https://user-images.githubusercontent.com/5625518/110722182-b976a400-81c6-11eb-9e1b-540bff0f3014.png)

## To Reproduce

The code used to produce the images is below.  I then opened the resulting files with the [Netron web app](https://netron.app/) to visualize the graphs.

```python
import torch
from torch import onnx
from torchvision.models.resnet import resnet18

def export_resnet_to_onnx(filepath):
    model = resnet18()

    sample_input = torch.randn(16, 3, 224, 224)
    onnx.export(  # resnet18_train_no_params.onnx
        model=model,
        args=sample_input,
        f=filepath.replace('.onnx', '_train_no_params.onnx'),
        export_params=False,
        training=onnx.TrainingMode.TRAINING
    )
    onnx.export(  # resnet18_train_params.onnx
        model=model,
        args=sample_input,
        f=filepath.replace('.onnx', '_train_with_params.onnx'),
        export_params=True,
        training=onnx.TrainingMode.TRAINING
    )

if __name__ == '__main__':
    filepath = 'resnet18.onnx'
    export_resnet_to_onnx(filepath)
```

## Expected behavior

I expected the graph to look the same with or without export params, as I assumed these "params" were the model weights which shouldn't impact the compute graph's structure.

## Environment

WSL2 / Ubuntu 20.04 LTS:

❯ conda list | grep torch
pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
torchvision               0.8.2                py38_cu110    pytorch

--------------------------------------------------------
Thank you for your help!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by spandantiwari** [comment]
@collinmccarthy - you are right that the compute graph structure should remain the same. Only the initializers should not be present in the model when `export_params=False`. From  a quick glance, it seems that is the case between the two snapshots, i.e., the second graph seems to have the initializers displayed, and the first one does not. The visualization tool will render this differently depending on the exact items to be displayed and that is where the difference may be coming from. So, I would say that this is expected. Feel free to re-open this issue, if you see any difference in graph op topology between the two.

**Comment by collinmccarthy** [comment]
@spandantiwari Thank you for taking a look, but I'm not sure if I follow. If you look at the graphs carefully the exact same tensors are represented, just shown in a different way. I'm suggesting that the way the graph is generated when `export_params=False` can be done in the exact same way as when `export_params=True` , which is a much cleaner graph visually. Am I misunderstanding something?

**Comment by spandantiwari** [comment]
@collinmccarthy - 
> I'm suggesting that the way the graph is generated when export_params=False can be done in the exact same way as when export_params=True , which is a much cleaner graph visually.

I understand. Personally, I like to see the initializers displayed explicitly when they are available. But I can see the advantages of displaying a "cleaner" graph. 

The display is generated using the Netron tool and we do not maintain that (it is a separate repo). You can suggest this to the tool author in their repo.
