### ISSUE TITLE
Libtorch Module add release GPU function

### ISSUE THREAD

**Issue by ZhiZe-ZG** [pytorch/pytorch#53788]
## 🚀 Feature
Now, Module doesn't have a function to release all the GPU memory that is occupied.
We need a method to release GPU memory occupied by a Module.

## Motivation

Make memory management more convenient.

## Pitch

let `model` be a `Module`.

```
model.release();
```

then release all the  GPU memory occupied by a Module.

cc @yf225 @glaringlee @albanD @mruberry @jbschlosser

**Comment by ksasso1028** [comment]
can someone confirm there is no way to do this currently? I am facing the same issue when moving the model back to the CPU. Even after running empty_cache(), the old memory on the GPU from the model is still occupied.

**Comment by albanD** [comment]
Hi,

Since the modules are user defined, they can store data in whichever way they want. So no there is no such functionality today.

I am curious though how you would use that? Why don't you just delete the whole model?

**Comment by ksasso1028** [comment]
I think I know what was going on. When moving the model to the CPU and releasing the cache afterwards the model does actually get removed from the GPU. 

The cuda context memory (~500 mb) is what never gets cleared. So anytime I move anything from the GPU to CPU, the context is never released. I assume this is to keep the calls to the GPU quick and consistent?

**Comment by albanD** [comment]
The cuda context if from the cuda driver itself. We don't really have a control on this.
And yes we keep cuda initialized because it is fairly slow to start.

**Comment by glaringlee** [comment]
I believe this can be closed now, feel free to reopen this again if needed.
