### ISSUE TITLE
Equivalent of Type::toScalarType for Python-side dtype

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5379]
I have a dtype, I want the byte-ified version of it (if it was a CPU float dtype, I want CPU byte dtype; if it was GPU float dtype, I want GPU byte dtype). In ATen I can use toScalarType. The new Python-side dtype doesn't have this.

A generalized version of this ticket is to ensure API parity between ATen Type, and PyTorch dtype. (Maybe we should rename ATen type so that the names line up too.)

cc @yf225

**Comment by gchanan** [comment]
`to(dtype)` does this.
