### ISSUE TITLE
tensor partial assignment error ?

### ISSUE THREAD

**Issue by yulinhuyang** [pytorch/pytorch#53798]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

    image = torch.rand(1,1,5)
    query_size = torch.rand(1,1,13)
    query_size[:,:,:5] = image   --- 》 error

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
