### ISSUE TITLE
Quantization - Conv2D zero padding 

### ISSUE THREAD

**Issue by ocaff1** [pytorch/pytorch#53807]
Hi,

When a quantized conv2D layer is configured with some zero padding, the input boundary shall be extended with "0" value.
But "0" value in this case should be the "zero-point" of input.
How "QuantizedConvReLU2d" computation is done since the input zero-point is not part of its _input_ parameters (zero-point in parameter is the one of _output_ activation)?

Example:
(quant): Quantize(scale=tensor([0.4914]), **zero_point=tensor([50])**, dtype=torch.qint8)
(conv_0): QuantizedConvReLU2d(1, 64, kernel_size=(4, 4), stride=(2, 2), scale=0.099393032, zero_point=0, padding=(1, 1), padding_mode='zeros')
Thk,
OC.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by z-a-f** [comment]
I am not sure if I understand the question. If you are asking how the padding is done, the functional behavior of the quantized kernel matches the non-quantized one. This means that if the padding is added (zero or non-zero), it will be appropriately converted before adding to the input. Are you seeing a different behavior?

If this is just a question it might be more suitable to ask it at discuss.pytorch.org
