### ISSUE TITLE
nightly builds broken on kineto broken when building libtorch for CUDA with cxx11

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#53848]
Kineto seems to be broken when building libtorch for CUDA with cxx11. CircleCI is [currently down](https://status.circleci.com/) so I don't have a link to a failing Circle build, but our [experimental GitHub Actions build](https://github.com/pytorch/pytorch/pull/53292) shows which parts of the matrix are failing:

- https://github.com/pytorch/pytorch/actions/runs/643789415

Here is an example (error message from one of those failing builds):

```
[2668/5375] Building CXX object third_party/kineto/libkineto/CMakeFiles/kineto_base.dir/src/cupti_strings.cpp.o
FAILED: third_party/kineto/libkineto/CMakeFiles/kineto_base.dir/src/cupti_strings.cpp.o 
/usr/bin/c++  -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMAGMA_V2 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -I../cmake/../third_party/benchmark/include -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../third_party/kineto/libkineto/include -I../third_party/kineto/libkineto/src -I../third_party/fmt/include -I/usr/local/cuda/extras/CUPTI/include -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem /opt/intel/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /opt/conda/include/python3.8 -isystem /opt/conda/lib/python3.8/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem ../cmake/../third_party/cub -isystem /usr/local/magma/include -isystem /usr/local/cuda/include -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/ideep/include -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -O3 -DNDEBUG -DNDEBUG -fPIC -fvisibility=hidden   -DCAFFE2_USE_GLOO -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -DKINETO_NAMESPACE=libkineto -std=gnu++14 -DHAS_CUPTI -std=c++14 -MD -MT third_party/kineto/libkineto/CMakeFiles/kineto_base.dir/src/cupti_strings.cpp.o -MF third_party/kineto/libkineto/CMakeFiles/kineto_base.dir/src/cupti_strings.cpp.o.d -o third_party/kineto/libkineto/CMakeFiles/kineto_base.dir/src/cupti_strings.cpp.o -c ../third_party/kineto/libkineto/src/cupti_strings.cpp
../third_party/kineto/libkineto/src/cupti_strings.cpp: In function ‘const char* libkineto::runtimeCbidName(CUpti_CallbackId)’:
../third_party/kineto/libkineto/src/cupti_strings.cpp:479:63: error: expected ‘,’ before ‘)’ token
       (sizeof(runtimeCbidNames) / sizeof(runtimeCbidNames[0])));
                                                               ^
../third_party/kineto/libkineto/src/cupti_strings.cpp:479:63: error: expected string-literal before ‘)’ token
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ilia-cher @gdankel @ngimel

**Comment by seemethere** [comment]
Pretty sure the errors arise with this PR: https://github.com/pytorch/pytorch/pull/53199

**Comment by malfet** [comment]
Hmm, I wonder if static_assert is a good idea here: if code is run on a newer CUDA driver we can get events we are nto aware of, are we?

**Comment by gdankel** [comment]
The issue is that a c++17 version of static_assert was used. It needs a message string to compile with c++14.

**Comment by gdankel** [comment]
And yes we should have runtime check too.

**Comment by seemethere** [comment]
Can we link the commit that fixes this in this thread?

**Comment by gdankel** [comment]
It's here: https://github.com/pytorch/kineto/pull/121

**Comment by gdankel** [comment]
> Hmm, I wonder if static_assert is a good idea here: if code is run on a newer CUDA driver we can get events we are nto aware of, are we?

No this is not possible - these are runtime events.Is it possible (or supported) to run a version of PyTorch compiled for a certain Cuda version on a newer Cuda version?

**Comment by gdankel** [comment]
> It's here: [pytorch/kineto#121](https://github.com/pytorch/kineto/pull/121)

We still need to update the rev on pytorch. Will do that next.

**Comment by seemethere** [comment]
This is currently blocking the release of RC1 of PyTorch `v1.8.1` after https://github.com/pytorch/pytorch/pull/54044, if there was a higher priority than `high priority` I would give it to this issue

**Comment by seemethere** [comment]
I went ahead and created the PR myself, https://github.com/pytorch/pytorch/pull/54206
