### ISSUE TITLE
How to shift columns (or rows) in a tensor with different offsets?

### ISSUE THREAD

**Issue by changmenseng** [pytorch/pytorch#53888]
`torch.roll` function is only able to shift columns (or rows) with same offsets. But I want to shift columns with different offsets. Suppose the input tensor is
```
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```
Say, to shift with offset `i` for the i-th column, the expected output is
```
[[1,8,6],
 [4,2,9],
 [7,5,3]]
```
An option to do so is to separately shift every column using `torch.roll` and stack them. But for the consideration of effectiveness and code compactness, I don't want to introduce the loop structure. Is there a better way？

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org. You can achieve this with advanced indexing,
