### ISSUE TITLE
Cannot find reference 'data' in '__init__.py' 

### ISSUE THREAD

**Issue by CCLDArjun** [pytorch/pytorch#53927]
## 🐛 Bug

No autocomplete suggestions for `torch.utils.data` in pycharm.  

## To Reproduce

1. Open pycharm project
1. `import torch`
1. try `torch.utils.data`
<img width="675" alt="Screen Shot 2021-03-12 at 1 52 31 PM" src="https://user-images.githubusercontent.com/31632587/111002440-49892a80-833a-11eb-8ebd-12cde91109d3.png">

So something like 
<img width="737" alt="Screen Shot 2021-03-12 at 1 53 45 PM" src="https://user-images.githubusercontent.com/31632587/111002484-5e65be00-833a-11eb-8f8d-265436130234.png">
wont have autocomplete suggestions since it doesn't recognize utils.data

## Expected behavior

Should give autocomplete suggestions for the data module in utils for stuff like `torch.utils.data.DataLoader`

## Environment

 - PyTorch Version: 1.8.0
 - OS: Mac OS 11.2.1
 - pip 21.0.1
 - Python version: Python 3.8.8
 - Using Intel CPU, no graphics card

## Additional context

Could be a Pycharm problem, but all the other stuff I've used so far works

**Comment by CCLDArjun** [comment]
Just noticed it got fixed somewhere else 😁

**Comment by etoyz** [comment]
`import torch.utils.data`

looks like a namespace issue
