### ISSUE TITLE
Mac OS rocM AMD card detection is failing with PyTorch 1.8

### ISSUE THREAD

**Issue by thenewera-ru** [pytorch/pytorch#53954]
I've successfully built `1.8` version from source according to [this](https://github.com/pytorch/pytorch#from-source) on `Mac OS Mojave 10.14.5` with `xcodebuild -version` being `10.1` as suggested in the «_installation from source_» guide.
Executing: `python -c 'import torch;print(torch.cuda.is_available())'` returns False.

_Graphics card_: Vega20 mobile.

According to the official list of supported graphics cards [here](https://github.com/RadeonOpenCompute/ROCm) the `Vega20` is included as 7nm chip. 

P.S. Any advice|help is highly appreciated. Thank you🙏 

cc @jeffdaily @sunway513 @ROCmSupport

**Comment by ramcherukuri** [comment]
I am not that familiar with MAC OS but I believe at this time the ROCm stack is only supported on Linux. Here is the list of supported platforms. https://github.com/RadeonOpenCompute/ROCm#Supported-Operating-Systems

**Comment by skyline75489** [comment]
Yeah the ROCm support depends heavily on the GPU drivers inside Linux kernel. I don't think it's available on any platform other than Linux at the moment.

**Comment by ROCmSupport** [comment]
Hi @thenewera-ru 
ROCm does not support MacOS officially and so I can not comment on this.
We are always able to help with/on the supported configurations.
Thank you.

**Comment by harishsdev** [comment]
As per offifical pytorch site,it supports linux,non-cuda gpu also,please check below commmands for installtion

pip install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch_stable.html
pip install ninja && pip install 'git+https://github.com/pytorch/vision.git@v0.9.0'
