### ISSUE TITLE
torch.signbit: incorrect output for negative zero

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#53963]
```python
>>> import torch
>>> import numpy as np
>>> t = torch.tensor(-0.)
>>> torch.signbit(t)
tensor(False)
>>> np.signbit(t.numpy())
True
```

C++ `std::signbit` works similar to NumPy.
https://en.cppreference.com/w/cpp/numeric/math/signbit

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @rgommers @heitorschueroff

**Comment by kshitij12345** [comment]
[Pytorch Documentation](https://pytorch.org/docs/stable/generated/torch.signbit.html): 
```
Tests if each element of input has its sign bit set (is less than zero) or not.
```

[NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.signbit.html):
```
Returns element-wise True where signbit is set (less than zero).
```

As per IEEE 754: -0. == 0. is True (so both documentation are incorrect  when stating (less than zero))

**Comment by mruberry** [comment]
Python's copysign would seem to agree https://docs.python.org/3/library/math.html#math.copysign.

Does our copysign also have this issue?

We would accept a PR correcting this and, ideally copysign too if needed. Also the copysign docs are formatted incorrectly and may need an improvement like the one you've mentioned above.

**Comment by zou3519** [comment]
Copysign seems OK: 
```
In [1]: import torch

In [2]: t = torch.tensor(-0.)

In [3]: x = torch.tensor(1.)

In [4]: x
Out[4]: tensor(1.)

In [5]: torch.copysign(x, t)
Out[5]: tensor(-1.)
```

**Comment by mruberry** [comment]
(But it'd still be nice to fix the copysign docs.)
