### ISSUE TITLE
Can I use Python 3.7.4 if building from source?

### ISSUE THREAD

**Issue by RussellXie7** [pytorch/pytorch#53960]
Currently I am using Python 3.7.4, with CUDA 10.1. I am trying to build Pytorch from source in a clean conda environment in Linux ubuntu 18.04.5 LTS (Bionic Beaver) by following each command on the main page:

```
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```

Each step completes successfully with no error interruption.

But if I do "import torch", I get following error:
```
(x3d) ubuntu@ip-172-31-20-108:~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/x3d/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/home/ubuntu/anaconda3/envs/x3d/lib/python3.7/site-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/ubuntu/anaconda3/envs/x3d/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/mpi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth
```

If I run "python collect_env.py", I get following:
```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

```

I had no problem at all when installing from the official release package using
`conda install pytorch torchvision torchaudio cudatoolkit=10.1 -c pytorch`

But it seems like building from source is not successful. Could anyone confirm if Python 3.7.4 is still supported? (I also tried 3.7.6 but identical issue occurred). Or should I add any flags when doing "python setup.py install"?

Thank you and I really appreciate the help.

**Comment by Hemantr05** [comment]
I use python 3.7.6 and was able to build it without an issue

**Comment by RussellXie7** [comment]
> I use python 3.7.6 and was able to build it without an issue

Thank you! May I know if your system is single GPU or multi-GPU? It seems like my error 
`OSError: /usr/local/mpi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth`
is related to Open-MPI, which seems to be a module used for distributed computing.

**Comment by skyline75489** [comment]
I think the OpenMP in your system is a bit old. Can you try install OpenMP using conda or pip?

**Comment by RussellXie7** [comment]
> I think the OpenMP in your system is a bit old. Can you try install OpenMP using conda or pip?

Sorry if this is a stupid question. It looks like my system is complaining about the OpenMP under:
`OSError: /usr/local/mpi/lib/libmpi.so.40`

But if I use pip/conda to install OpenMP, it will be installed under my conda environment
`/home/ubuntu/anaconda3`

, which will not change the content in 
`/usr/local/mpi/`

How can I install the update to the location `/usr/local/mpi/` ?

**Comment by skyline75489** [comment]
The OpenMP used actually depends on the result of CMake process. I don't have issues with MP so I am not sure the exact configuration to modify. Take a look at CMakeLists.txt and you wi find how it searches for OpenMP.

**Comment by RussellXie7** [comment]
> The OpenMP used actually depends on the result of CMake process. I don't have issues with MP so I am not sure the exact configuration to modify. Take a look at CMakeLists.txt and you wi find how it searches for OpenMP.

Thank you. I think this is the issue. Now I can install without problem. But seems like the SlowFast repo is not very compatible with the current pytorch though. Having some issues with the GPU parallelization...

**Comment by Hemantr05** [comment]
> > I use python 3.7.6 and was able to build it without an issue
> 
> Thank you! May I know if your system is single GPU or multi-GPU? It seems like my error
> `OSError: /usr/local/mpi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth`
> is related to Open-MPI, which seems to be a module used for distributed computing.

I have a single GPU.
