### ISSUE TITLE
use static libtorch binary compile get wrong 

### ISSUE THREAD

**Issue by dencesun** [pytorch/pytorch#53961]
## ❓ Questions and Help

this is my code 
`#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }

  torch::jit::script::Module module;
  //std::shared_ptr<torch::jit::script::Module> module;
  try {
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load(argv[1]);
  }
  catch (const c10::Error& e) {
    std::cerr << "error loading the model\n";
	        std::cerr << "err " << e.what() << std::endl;
    
return -1;
  }

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({1, 3, 224, 224}));
  //
  // // Execute the model and turn its output into a tensor.
  at::Tensor output = module.forward(inputs).toTensor().slice(1, 0,5);
  std::cout << output[0][0] << '\n';
  std::cout << typeid(output[0][0]).name() << std::endl;
  printf("\n%f\n", output[0][0].item().toFloat());
  std::cout << "ok\n";
}
`
this is cmakelist
`cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(custom_ops)

list(APPEND CMAKE_PREFIX_PATH "/home/sunxiaowei/libtorch")
find_package(Torch REQUIRED)

#set(Torch_DIR "/home/sunxiaowei/libtorch/share/cmake/")
#include_directories(/home/sunxiaowei/libtorch/include)

add_executable(example-app example-app.cc)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
#set_property(TARGET example-app PROPERTY CXX_STANDARD 14)
`

this is error info 

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by dencesun** [comment]
![image](https://user-images.githubusercontent.com/9604835/111022593-91798180-840e-11eb-986e-fe7c6b63f39a.png)

**Comment by dencesun** [comment]
`kwepcidmh00013:/home/sunxiaowei/example-app/build # cat ../example-app.cc 
#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }


  torch::jit::script::Module module;
  //std::shared_ptr<torch::jit::script::Module> module;
  try {
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load(argv[1]);
  }
  catch (const c10::Error& e) {
    std::cerr << "error loading the model\n";
	        std::cerr << "err " << e.what() << std::endl;
    
return -1;
  }

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({1, 3, 224, 224}));
  //
  // // Execute the model and turn its output into a tensor.
  at::Tensor output = module.forward(inputs).toTensor().slice(1, 0,5);
  std::cout << output[0][0] << '\n';
  std::cout << typeid(output[0][0]).name() << std::endl;
  printf("\n%f\n", output[0][0].item().toFloat());
  std::cout << "ok\n";
}
`

**Comment by ngimel** [comment]
Please use forums for question and use examples in the documentation on how to compile extension files.
