### ISSUE TITLE
Undefined symbols in Xcode for libtorch built via scripts/build_ios.sh

### ISSUE THREAD

**Issue by maksfourlife** [pytorch/pytorch#53969]
## 🐛 Bug

I have compiled libtorch using scripts/build_ios.sh as given [here](https://pytorch.org/mobile/ios/#build-pytorch-ios-libraries-from-source)
command (with Conda environment active, pytorch installed): `BUILD_PYTORCH_MOBILE=1 IOS_ARCH=arm64 ./scripts/build_ios.sh`
Also, I set BUILD_MOBILE_AUTOGRAD=1 because I need it in my project (compilation without that option gives the same error)
When I'm trying to use it in my Xcode project for iOS I encounter those errors:

> ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libc10.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libcpuinfo.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libpytorch_qnnpack.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libeigen_blas.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture arm64:
  "typeinfo for c10::AutogradMetaInterface", referenced from:
      typeinfo for torch::autograd::AutogradMeta in Backend.o
  "c10::BFloat16 at::Tensor::item<c10::BFloat16>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda8'()::operator()() const in Backend.o
  "c10::Half at::Tensor::item<c10::Half>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda7'()::operator()() const in Backend.o
  "bool at::Tensor::item<bool>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda6'()::operator()() const in Backend.o
  "long long at::Tensor::item<long long>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda4'()::operator()() const in Backend.o
  "int at::Tensor::item<int>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda3'()::operator()() const in Backend.o
  "signed char at::Tensor::item<signed char>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda0'()::operator()() const in Backend.o
  "unsigned char at::Tensor::item<unsigned char>() const", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda'()::operator()() const in Backend.o
  "c10::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, c10::Half const&)", referenced from:
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda'()::operator()() const::'lambda7'()::operator()() const in Backend.o
      torch::detail::TensorDataContainer::pretty_print_recursive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const::'lambda0'()::operator()() const::'lambda7'()::operator()() const in Backend.o
  "at::GradMode::is_enabled()", referenced from:
      at::AutoGradMode::AutoGradMode(bool) in Backend.o
  "at::GradMode::set_enabled(bool)", referenced from:
      at::AutoGradMode::AutoGradMode(bool) in Backend.o
      at::AutoGradMode::~AutoGradMode() in Backend.o
  "at::Tensor::fill_(c10::Scalar) const", referenced from:
      torch::detail::TensorDataContainer::, etc.

I have a suggestion that this warning causes error:
> warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: /Users/user/Library/pytorch/build_ios/install/lib/libtorch.a the table of contents is empty (no object file members in the library define global symbols)

## To Reproduce

1. Clone pytorch repository
2. Activate Conda environment with pytorch installed
3. Run given command
4. Create Xcode Swift project for iOS
5. Add files from build_ios/install/lib to "Link binary with libraries" and add build_ios/install/include to header search path
6. Add Objective-c++ file and include <pytorch/script.h> there
7. Build project for arm64

## Environment

PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.6

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.8.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py38hfbe908c_0  
[conda] mkl_fft                   1.2.0            py38hc64f4ea_0  
[conda] mkl_random                1.1.1            py38h959d312_0  
[conda] numpy                     1.19.2           py38h456fd55_0  
[conda] numpy-base                1.19.2           py38hcfb5961_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] torch                     1.8.0                    pypi_0    pypi

cc @malfet @seemethere @walterddr @yf225 @glaringlee

**Comment by skyline75489** [comment]
Hi! Thanks for the feedback! I've compiled the iOS build myself with the 1.7.1 code but not the 1.8.0 one. Can you please try if 1.7.1 works?

**Comment by maksfourlife** [comment]
> Hi! Thanks for the feedback! I've compiled the iOS build myself with the 1.7.1 code but not the 1.8.0 one. Can you please try if 1.7.1  @skyline75489 

Sure! I've compiled with v1.7.1 and error is still the same. Actually, I was compiling v1.7.0 previously, not v1.8.0 (also tried). I think problem can be with Xcode configuration or with cmake. 

Attaching screens in case I configured something wrong in Xcode
<img width="764" alt="Снимок экрана 2021-03-14 в 10 30 13" src="https://user-images.githubusercontent.com/54711921/111060749-5cbe0680-84b0-11eb-93f2-1b02094f1fe4.png">
<img width="751" alt="Снимок экрана 2021-03-14 в 10 30 06" src="https://user-images.githubusercontent.com/54711921/111060756-621b5100-84b0-11eb-858b-434b52b61c6b.png">
<img width="757" alt="Снимок экрана 2021-03-14 в 10 29 53" src="https://user-images.githubusercontent.com/54711921/111060759-68113200-84b0-11eb-80fc-630ac9a32011.png">
<img width="760" alt="Снимок экрана 2021-03-14 в 10 29 33" src="https://user-images.githubusercontent.com/54711921/111060770-73fcf400-84b0-11eb-84ad-d0f264583007.png">

**Comment by skyline75489** [comment]
OK I see something very strange in your log:

```text
ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libc10.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
```

This is unusual because normally you see something like this:

```text
building for iOS-arm64 but attempting to link with file built for iOS Simulator-x86
```

This is clear. The libraries are built for `arm64` but we try to link it for `iOS Simulator-x86`, which is a different arch. However in your log it suggests:

```text
building for iOS-arm64 but attempting to link with file built for iOS-arm64
```

I think this is the reason why the symbols are not loaded, because for some reason Xcode refuses to load the libraries. But the arch displayed is exactly what it (should) wants! This is very weird to me. Can you maybe try build for Simulator x64?

**Comment by maksfourlife** [comment]
> OK I see something very strange in your log:
> 
> ```
> ld: warning: ignoring file /Users/user/Library/pytorch/build_ios/install/lib/libc10.a, building for iOS-arm64 but attempting to link with file built for iOS-arm64
> ```
> 
> This is unusual because normally you see something like this:
> 
> ```
> building for iOS-arm64 but attempting to link with file built for iOS Simulator-x86
> ```
> 
> This is clear. The libraries are built for `arm64` but we try to link it for `iOS Simulator-x86`, which is a different arch. However in your log it suggests:
> 
> ```
> building for iOS-arm64 but attempting to link with file built for iOS-arm64
> ```
> 
> I think this is the reason why the symbols are not loaded, because for some reason Xcode refuses to load the libraries. But the arch displayed is exactly what it (should) wants! This is very weird to me. Can you maybe try build for Simulator x64?

Yes, for me too. I surfed a lot of issues and nobody has the same log. Do you have any suggestions why it can refuse to load libraries? All of them are listed in "Link Binary With Libraries". Also, I'll compile lib for simulator. Thanks for advice.

<img width="756" alt="Снимок экрана 2021-03-14 в 12 37 38" src="https://user-images.githubusercontent.com/54711921/111063899-24bfbf00-84c2-11eb-9897-c90c5097037d.png">

**Comment by skyline75489** [comment]
I wish I know something you don't 😄. So there's this benchmark app (TestApp) inside the PyTorch repo. This has been working for me so far. Check out [this link](https://pytorch.org/tutorials/recipes/mobile_perf.html#ios-benchmarking-setup) to see maybe you can get it up & running. The configuration of this iOS project is generated by the script named `setup.rb`. If this project works, then maybe you can see what's the difference between this demo project vs. your project.

**Comment by maksfourlife** [comment]
> I wish I know something you don't 😄. So there's this benchmark app (TestApp) inside the PyTorch repo. This has been working for me so far. Check out [this link](https://pytorch.org/tutorials/recipes/mobile_perf.html#ios-benchmarking-setup) to see maybe you can get it up & running. The configuration of this iOS project is generated by the script named `setup.rb`. If this project works, then maybe you can see what's the difference between this demo project vs. your project.

Thanks! That's a good idea. I'll try

**Comment by maksfourlife** [comment]
> I wish I know something you don't 😄. So there's this benchmark app (TestApp) inside the PyTorch repo. This has been working for me so far. Check out [this link](https://pytorch.org/tutorials/recipes/mobile_perf.html#ios-benchmarking-setup) to see maybe you can get it up & running. The configuration of this iOS project is generated by the script named `setup.rb`. If this project works, then maybe you can see what's the difference between this demo project vs. your project.

@skyline75489
Same ld warning again, even with official benchmark. I have a suggestion that something wrong with my Xcode. What version are you using?

**Comment by skyline75489** [comment]
The latest version I'm using is 12.3. But I have no problem with older versions, too.

I've had some weird issues with multiple version of Xcode installed. Do you have multiple versions of Xcode installed?

Anyway this isn't really a torch issue. More of a toolchain issue specifically in your environment.

**Comment by maksfourlife** [comment]
> The latest version I'm using is 12.3. But I have no problem with older versions, too.
> 
> I've had some weird issues with multiple version of Xcode installed. Do you have multiple versions of Xcode installed?
> 
> Anyway this isn't really a torch issue. More of a toolchain issue specifically in your environment.

Seems that I have only one Xcode version - it's 12.4. I'll try to install older one (12) and check if it helps. About toolchain, which are you using? cmake/iOS.cmake or custom? Maybe macOS Big Sur isn't supported?

**Comment by skyline75489** [comment]
Oh I forgot. I'm still using Catalina. Old MBP. Never really want to switch to Big Sur.

I'm just using everything default. Using Anaconda, following the steps in README, `python setup.py install` and everything.

**Comment by skyline75489** [comment]
Sorry, the `python setup.py install` is for Windows/Linux/macOS version. For iOS/watchOS/tvOS, `scripts/build_ios.sh` is the way. 

Working on multi platforms can really mess up your brain 😅

**Comment by maksfourlife** [comment]
> Sorry, the `python setup.py install` is for Windows/Linux/macOS version. For iOS/watchOS/tvOS, `scripts/build_ios.sh` is the way.
> 
> Working on multi platforms can really mess up your brain 😅

Yeah, that confused me a bit 😅 I was even ready to run this command.

**Comment by maksfourlife** [comment]
@skyline75489
Installing Xcode 12 did not work as well. I guess something wrong with compilation. It would be very great if you share build logs or, finally, the libraries. Big thanks for your help and participation.

**Comment by maksfourlife** [comment]
Problem was with macOS Big Sur, I installed Sierra on VBox and successfully compiled libraries. Big thanks!
