### ISSUE TITLE
Vulkan backend fails with internal error

### ISSUE THREAD

**Issue by sharpner** [pytorch/pytorch#53965]
## 🐛 Bug

I tried using https://github.com/werner-duvaud/muzero-general with the new vulkan backend from v1.18 (37c1f4a7fef115d719104e871d0cf39434aa9d56 ).

But running any training yields this error:
```
pytorch/aten/src/ATen/native/vulkan/ops/Tensor.cpp":258, please report a bug to PyTorch. Only Tensors with 1 <= dim <= 4 can be represented as a Vulkan Image!
```

Since the works with both cuda and cpu devices, I have to assume it is a bug or missing feature within vulkan?

## To Reproduce

1. Compile pytorch with vulkan support
2. Checkout the repository mentioned above
3. Replace cuda with vulkan in the source code 
4. Run any training 

Full Stacktrace:
```  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/Users/mac/Development/muzero-general/self_play.py", line 29, in __init__
    self.model.to(device=vulkan)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 430, in _apply
    self._buffers[key] = fn(buf)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: false INTERNAL ASSERT FAILED at "/Users/mac/Development/pytorch/aten/src/ATen/native/vulkan/ops/Tensor.cpp":258, please report a bug to PyTorch. Only Tensors with 1 <= dim <= 4 can be represented as a Vulkan Image!
```

## Expected behavior

I would assume it works exactly like on CPU or CUDA - or at least explain to me what I have to change...

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.6

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] Could not collect

```
 - GPU models and configuration: AMD Vega 56

### Build configuration
``` 
BUILD_TEST=0 USE_VULKAN=1 USE_VULKAN_SHADERC_RUNTIME=1 USE_VULKAN_WRAPPER=0 MACOSX_DEPLOYMENT_TARGET=10.15 CC=clang CXX=clang++ python3 setup.py install
```

And vulkan seems to work in general:
```
>>> import torch
>>> torch.is_vulkan_available();
True
>>> b2 = torch.tensor([1., 2., .3, .4, .5]).to(device='vulkan')
>>> c = b2 + b2
>>> print(c.to(device='cpu'))
tensor([2.0000, 4.0000, 0.6000, 0.8000, 1.0000])
>>>
```

**Comment by SS-JIA** [comment]
Currently we don't support tensors with more than 4 dimensions in Vulkan. The reason for this is that internally the tensors are represented as 3-dimensional textures on the GPU. For 4 dimensional tensors the batch and channel are flattened into the channel dimension, but for higher dimensional tensors an alternative method may be needed due to physical device limits constraining the size of textures in the x, y, and z dimensions.

Both CPU and CUDA represent tensors as buffers internally which is why dimensionality is not a constraint on those backends. Note that we plan to support higher dimensional tensors eventually on the Vulkan backend.
