### ISSUE TITLE
Indexing a tensor with another tensor

### ISSUE THREAD

**Issue by DeveloperInProgress** [pytorch/pytorch#53967]
I understand that `__getitem__` is not defined explicitly for Tensors. However, it has been made a Sequence object. But, when using a tensor for indexing a tensor, it does not replicate the behavior of a list or a numpy array when they are used for indexing. I have replicated this behavior below:

![Screenshot 2021-03-13 181439](https://user-images.githubusercontent.com/40036742/111030603-35702680-8429-11eb-894a-3e117889ccfa.jpg)

I know there are several ways to  get the output that I am looking for, but when we use tensors, we expect that it behaves the same way as its numpy counterpart but faster, because, PyTorch is often used as "A replacement for NumPy to use the power of GPUs." (Quoted from README.md of this repository).  

Is it a good idea now to write `__getitem__` for Tensors explicitly?

cc @mruberry @rgommers @heitorschueroff

**Comment by ngimel** [comment]
Current behavior agrees with numpy:
```
In [13]: x[index]                                                                                                                                                                                            
Out[13]: tensor([1, 4])

In [14]: x[torch.as_tensor(index)]                                                                                                                                                                           
Out[14]: 
tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])

In [15]: x.numpy()[index]                                                                                                                                                                                    
/private/home/ngimel/opt/anaconda3/envs/pt/bin/ipython:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  #!/private/home/ngimel/opt/anaconda3/envs/pt/bin/python
Out[15]: array([1, 4])

In [17]: x.numpy()[np.array(index)]                                                                                                                                                                          
Out[17]: 
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])
```
