### ISSUE TITLE
[quantization] test_learnable_backward_per_{channel, tensor}_cpu failing after a seemingly irrelevant changes

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#53966]
PR https://github.com/pytorch/pytorch/pull/50655 attempts to migrate `torch.nonzero` from TH to ATen on CPU. 

But `test_learnable_backward_per_channel_cpu` and `test_learnable_backward_per_tensor_cpu` fail consistently. Main issue is that I am unable to reproduce the issue locally.
I tried to see if they utilize `nonzero` directly but couldn't find.

Would be great if someone can take a look.

https://github.com/pytorch/pytorch/pull/50655#issuecomment-762190934

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by z-a-f** [comment]
This might be unrelated to your PR. Just to confirm, could you rebase onto the latest commit, and submit again?

**Comment by kshitij12345** [comment]
I have tried that multiple times. But unfortunately it fails consistently. 
Will try that again.

**Comment by z-a-f** [comment]
Hmmm, this is odd -- I'll take a look tomo

**Comment by z-a-f** [comment]
I wonder if this is caused by a specific random seed. Just for the sake of an experiment, could you set the seed to 19. Let's see if it was passing before

**Comment by kshitij12345** [comment]
It was failing with the original seed of 19. Inspired by https://github.com/pytorch/pytorch/pull/53854, I thought it might be worth trying with SEED from test suite.

Thanks for looking into that.

**Comment by kshitij12345** [comment]
Tagging @aocsa, might have more idea (author of #53854)
