### ISSUE TITLE
Pytorch installation issue for non CUDA GPU

### ISSUE THREAD

**Issue by harishsdev** [pytorch/pytorch#53974]
## 🐛 Bug

Pytorch installation issue for non nvidia GPU 

link to install:-https://pytorch.org/get-started/locally/#linux-pip

ubuntu@ubuntu:~$ pip3 install ninja && pip3 install 'git+https://github.com/pytorch/vision.git@v0.9.0'
Requirement already satisfied: ninja in ./.local/lib/python3.8/site-packages (1.10.0.post2)
Collecting git+https://github.com/pytorch/vision.git@v0.9.0
  Cloning https://github.com/pytorch/vision.git (to revision v0.9.0) to /tmp/pip-req-build-dckslycr
  Running command git clone -q https://github.com/pytorch/vision.git /tmp/pip-req-build-dckslycr
  Running command git checkout -q 01dfa8ea81972bb74b52dc01e6a1b43b26b62020
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dckslycr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dckslycr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-dckslycr/pip-egg-info
         cwd: /tmp/pip-req-build-dckslycr/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dckslycr/setup.py", line 12, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @seemethere @malfet @walterddr

**Comment by skyline75489** [comment]
Hi. Looks like you do not have torch installed? I don't think this is related to the GPU you're using.

**Comment by jbschlosser** [comment]
Hey @harishsdev ! Could you try again after ensuring torch has been installed first?

If you still run into an issue, please be sure to follow the instructions to run the environment collection script so we have more information with which to help you:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
