### ISSUE TITLE
Dockerfile - Error on Build

### ISSUE THREAD

**Issue by sampathweb** [pytorch/pytorch#5397]
Docker Version: Docker version 17.06.2-ce, build cec0b72
Host: Ubuntu 16.04

I am trying to run the Docker container - `docker build . --file Dockerfile --tag dl:pytorch`

I have the following Errors:

1. Looks like Conda no longer add conda executable to the env it creates.  
```
ENV PATH /opt/conda/envs/pytorch-py$PYTHON_VERSION/bin:$PATH
RUN conda install --name pytorch-py$PYTHON_VERSION -c soumith magma-cuda90
```
Had to modify the second line there to -
`RUN /opt/conda/bin/conda install --name pytorch-py$PYTHON_VERSION -c soumith magma-cuda90`

May be its better to do `ln -s /opt/conda/bin/conda /usr/bin/conda` to have it in path?

2. I get an error on `RUN git submodule update --init` - saying it's nota  git Repo.
Not sure how to fix it.  May be something has changed since the recent upgrade to Pytorch 0.3.1?

<img width="604" alt="screen shot 2018-02-24 at 6 12 43 am" src="https://user-images.githubusercontent.com/1437573/36631318-983264f8-192a-11e8-8349-9906363f3a52.png">

**Comment by sampathweb** [comment]
I opened an issue with Conda team and looks the issue of `conda` command not found in Env is introduced in 4.4 version and should be fixed in 4.5 (Next version).  Until then we may need to link it directly or fully reference it as `/opt/conda/bin/conda` in the RUN Command.  Alternatively, we could specify the Conda version as 4.3 that may not have this problem.

https://github.com/conda/conda/issues/6938
https://github.com/conda/conda/issues/6810

**Comment by soumith** [comment]
i think we can simplify the Dockerfile to just make it install pytorch in the default environment. If @ngimel has no objections, I'll simplify the dockerfile that way.

**Comment by soumith** [comment]
@jekbradbury I think `ENV PATH /opt/conda/envs/pytorch-py$PYTHON_VERSION/bin:/opt/conda/bin/:$PATH` is wrong. Exposing the `bin` folder of the root env will lead to weird side-effects such as binaries in root env being exposed in pytorch env.

**Comment by ngimel** [comment]
I've submitted PR to install pytorch into default conda env. As for git error, I'm not getting it on Docker version 17.09.0-ce, build afdb6d4, so not quite sure how to fix. Is .git copied along with the context?

**Comment by fedor-chervinskii** [comment]
@sampathweb probably you downloaded source as .tar.gz (as I did and got the same error). In this case it turned out that you can't build Docker image with existing Dockerfile, you need to clone repo and checkout to the desired branch/commit

**Comment by happinesszl** [comment]
Hi, @sampathweb . Have you solved the second problem about git submodule? I still faced the same problem. It would be great if you could give me some advice.

**Comment by ezyang** [comment]
I'm going to guess that this has been fixed on master.
