### ISSUE TITLE
grad of sinc explodes at 0

### ISSUE THREAD

**Issue by eyaler** [pytorch/pytorch#53989]
`x = torch.tensor(0.0, requires_grad=True)`
`torch.autograd.grad(torch.sinc(x),x)`
gives:
`(tensor(nan),)`
and i see that in https://github.com/pytorch/pytorch/blob/master/tools/autograd/derivatives.yaml:
`grad * ((M_PI * self * (M_PI * self).cos() - (M_PI * self).sin()) / (M_PI * self * self)).conj()`
so it seems that 0 is not handled for the derivative??

## Environment

Collecting environment information...
PyTorch version: 1.8.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0+cu101
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @jianyuh @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by johnpeterson123** [comment]
I would like to take a shot at fixing this if we can get confirmation that this is in fact a bug and not the intended result of running grad on sinc

**Comment by albanD** [comment]
Hi,

This is indeed a bug.
We want to special case the formula for the case where the input is 0.
You can see how this is done for norm here for an example: https://github.com/pytorch/pytorch/blob/2782126bfed4865914e70be42545992cf3815e43/torch/csrc/autograd/FunctionsManual.cpp#L216-L217

**Comment by johnpeterson123** [comment]
@albanD Great thank you. If it is alright, I will implement this and put up a pull request.

**Comment by albanD** [comment]
Sounds good, you can add me as a reviewer when it's ready!

**Comment by cpuhrsch** [comment]
Did https://github.com/pytorch/pytorch/pull/56763 resolve this?

**Comment by albanD** [comment]
Yes.
