### ISSUE TITLE
Libtorch not buildable as a cmake "FetchContent" dependency in another project

### ISSUE THREAD

**Issue by clemej** [pytorch/pytorch#53980]
## 🐛 Bug

Lines 330-331 in https://github.com/pytorch/pytorch/blob/master/caffe2/CMakeLists.txt explicitly set `TORCH_ROOT` and `TORCH_SRC_DIR` relative to `PROJECT_SOURCE_DIR`:
```
    set(TORCH_SRC_DIR "${PROJECT_SOURCE_DIR}/torch")
    set(TORCH_ROOT "${PROJECT_SOURCE_DIR}")
```

This breaks when including libtorch as a dependency in another project through `FetchContent`, and likely through `add_directory()`.  It should probably set these to `${CMAKE_CURRENT_SOURCE_DIR}/..` instead. 

## To Reproduce

1. Create an new empty project with a top-level CMakeLists.txt
1. Add pytorch as a dependency through FetchContent, so the resulting CMakeFile.txt looks something like:
```
cmake_minimum_required(VERSION 3.13 FATAL_ERROR)
project(foo CXX)
include(FetchContent)

FetchContent_Declare(
        pytorch
        GIT_REPOSITORY "https://github.com/pytorch/pytorch"
        GIT_TAG "release/1.8"
)
# Configure for minimal, static, openblas-enabled CPU library.
set(BUILD_SHARED_LIBS OFF)
set(USE_MKL OFF) # poor perf vs. openblas on older CPUs, ignores threading limits, cpuid-isms
set(USE_MKLDNN OFF) # ditto
set(USE_CUDA OFF)
set(USE_DISTRIBUTED OFF)
set(BUILD_PYTHON OFF)
set(USE_ROCM OFF)
set(USE_NCCL OFF)
set(BUILD_CAFFE2_OPS OFF)
set(BLAS_INFO "open")
set(WITH_BLAS "open")
set(USE_NUMA OFF)
FetchContent_MakeAvailable(pytorch)
```
1. mkdir build && cd build && cmake ..
Note this takes a while to checkout the git repo. 

1. Observe that the cmake command fails with:
```
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : OFF
--   USE_DEPLOY           : OFF
--   Public Dependencies  : Threads::Threads
--   Private Dependencies : pthreadpool;cpuinfo;qnnpack;pytorch_qnnpack;nnpack;XNNPACK;fbgemm;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;foxi_loader;rt;fmt::fmt-header-only;gcc_s;gcc;dl
-- Configuring done
CMake Error at build/_deps/pytorch-src/caffe2/CMakeLists.txt:719 (add_library):
  Cannot find source file:

    /home/john/git/test/torch/csrc/jit/frontend/error_report.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at build/_deps/pytorch-src/caffe2/CMakeLists.txt:719 (add_library):
  No SOURCES given to target: torch_cpu


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
Note that the source files are looking in the main project top level dir `/home/john/git/test` , not `/home/john/git/test/build/_deps/pytorch-src/`, the pytorch top level dir. 

There may be other issues as well but its the first one I've hit. 

## Expected behavior

I expect to be able to include libtorch as a dependency in in another CMake project. 
Current workaround is to build in a completely separate repo, install, and build from there. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): release/1.8 branch
 - OS (e.g., Linux): Linux 
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): see above
 - Python version: 3.8
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information:

## Additional context

I'm excited to test out static linking now that that's an option. I run MLC@Home, a volunteer distributed computing project running a client program on thousands of computers (x86, arm, windows, linux, etc..) to train thousands of neural networks for research. The client uses PyTorch (c++ bindings).  Having users download both a client and all the dependent libs has been a pain point since the beginning. It would be great if we could statically link our client into a single binary. 

cc @malfet @seemethere @walterddr @yf225 @glaringlee

**Comment by clemej** [comment]
Looks like the issue is much larger than this one instance. A rough grep for `PROJECT_SOURCE_DIR` in my empty project shows 274 references... Unlikely they're all wrong but a quick look at the list shoes others that are likely problematic, like:
```
build/_deps/pytorch-src/cmake/External/EigenBLAS.cmake:set(CAFFE2_THIRD_PARTY_ROOT ${PROJECT_SOURCE_DIR}/third_party)
build/_deps/pytorch-src/cmake/External/nnpack.cmake:  set(CAFFE2_THIRD_PARTY_ROOT ${PROJECT_SOURCE_DIR}/third_party)
build/_deps/pytorch-src/cmake/Dependencies.cmake:  set(TBB_ROOT_DIR "${PROJECT_SOURCE_DIR}/third_party/tbb")
build/_deps/pytorch-src/cmake/Dependencies.cmake:  add_subdirectory(${PROJECT_SOURCE_DIR}/aten/src/ATen/cpu/tbb)
build/_deps/pytorch-src/cmake/Dependencies.cmake:    set(CAFFE2_THIRD_PARTY_ROOT "${PROJECT_SOURCE_DIR}/third_party")

```

**Comment by walterddr** [comment]
I am not sure pytorch supports FetchContent since it is introduced in cmake 3.11 (currently the minimum cmake version supported by pytorch is 3.5)

**Comment by clemej** [comment]
@walterddr I'm pretty sure it won't work with this project when included with `add_directory()` either because of this. 

@glaringlee Thanks, that's helping me overall but I think that's tangential to this issue.

**Comment by SpaceIm** [comment]
I'm currently packaging libtorch for conan, and I saw this issue and several others related to `add_subdirectory(pytorch)`. It's not related to `PROJECT_SOURCE_DIR` which is the good variable to use.

With these modifications (in tag 1.8.0), it seems to work::

```patch
--- a/caffe2/CMakeLists.txt
+++ b/caffe2/CMakeLists.txt
@@ -60,7 +60,7 @@ if(INTERN_BUILD_ATEN_OPS)
   "${PYTHON_EXECUTABLE}" ${CMAKE_CURRENT_SOURCE_DIR}/contrib/aten/gen_op.py
     --aten_root=${CMAKE_CURRENT_SOURCE_DIR}/../aten
     --template_dir=${CMAKE_CURRENT_SOURCE_DIR}/contrib/aten
-    --yaml_dir=${CMAKE_CURRENT_BINARY_DIR}/../aten/src/ATen
+    --yaml_dir=${CMAKE_BINARY_DIR}/aten/src/ATen
     --install_dir=${CMAKE_CURRENT_BINARY_DIR}/contrib/aten
   DEPENDS
   ATEN_CPU_FILES_GEN_TARGET
--- a/cmake/Codegen.cmake
+++ b/cmake/Codegen.cmake
@@ -233,7 +233,7 @@ if(INTERN_BUILD_ATEN_OPS)
 endif()
 
 function(append_filelist name outputvar)
-  set(_rootdir "${${CMAKE_PROJECT_NAME}_SOURCE_DIR}/")
+  set(_rootdir "${Torch_SOURCE_DIR}/")
   # configure_file adds its input to the list of CMAKE_RERUN dependencies
   configure_file(
       ${PROJECT_SOURCE_DIR}/tools/build_variables.bzl
```
