### ISSUE TITLE
Example for LSTMCell an IndexError

### ISSUE THREAD

**Issue by Rajathbharadwaj** [pytorch/pytorch#53995]
## 📚 Documentation

When running the example in [LSTMCell](https://pytorch.org/docs/stable/generated/torch.nn.LSTMCell.html)
```
rnn = nn.LSTMCell(10, 20)
input = torch.randn(3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], (hx, cx))
    output.append(hx)
```
It returns IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

If changed to either any of the below, works properly

```
rnn = nn.LSTMCell(10, 20)
input = torch.randn(3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], (hx, cx))
    output.append(hx)
```
or 

```
rnn = nn.LSTMCell(10, 20)
input = torch.randn(2, 3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(input.size()[0]):
    hx, cx = rnn(input[i], (hx, cx))
    output.append(hx)
```

cc @brianjo @mruberry @albanD @jbschlosser @zou3519

**Comment by zou3519** [comment]
@Rajathbharadwaj would you be interested in submitting a PR to fix this?

**Comment by Rajathbharadwaj** [comment]
Yes!
Pointers on which file to edit would be awesome.

**Comment by zou3519** [comment]
It looks like we fixed this on master a few days ago actually: https://pytorch.org/docs/master/generated/torch.nn.LSTMCell.html?highlight=lstmcell#torch.nn.LSTMCell . Please let me know if that looks OK (it looks like one of your proposed changes)

I'll see if we can port this change to the 1.8.1 documentation.

There's nothing be done here, but for future reference, the documentation comes from the docstring on the nn.LSTMCell class, which is here: https://github.com/pytorch/pytorch/blob/2782126bfed4865914e70be42545992cf3815e43/torch/nn/modules/rnn.py#L1014

**Comment by Rajathbharadwaj** [comment]
Yes, this works! 
Looks like I was referring older version of docs?

**Comment by Rajathbharadwaj** [comment]
> Yes, this works!
> Looks like I was referring older version of docs?

Okay, I was referring the stable docs.

**Comment by zou3519** [comment]
Yeah, you were referring to the stable docs. The new docs will definitely show up in 1.9 when that releases, but we'll try to get the change into 1.8.1 so that it can come earlier. Closing this issue because there are no other action items.
