### ISSUE TITLE
Updating Pytorch Mobile to 1.8.0 from 1.7.1 causes “Dimension Out of Range” error in the PixelShuffle layer

### ISSUE THREAD

**Issue by ekremcet** [pytorch/pytorch#54051]
Hi,

I have updated the PytorchMobile for my Android application from 1.7.1 to 1.8.0 but doing so caused an error in the inference phase. Somehow the tensor dimensions became not valid anymore for PixelShuffle layer. Here is the error:

```
    Process: com.example.pytorchtutorial, PID: 14078
    java.lang.RuntimeException: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/CARN_SR/carn_x2/___torch_mangle_86.py", line 130, in forward
        _62 = getattr(self, "prepack_folding._jit_pass_packed_weight_32")
        _63 = ops.prepacked.conv2d_clamp_run(_61, _62)
        out8 = torch.pixel_shuffle(_63, 2)
               ~~~~~~~~~~~~~~~~~~~ <--- HERE
        _64 = getattr(self, "prepack_folding._jit_pass_packed_weight_33")
        out9 = ops.prepacked.conv2d_clamp_run(out8, _64)
    
    Traceback of TorchScript, original code (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/pixelshuffle.py", line 46, in forward
        def forward(self, input: Tensor) -> Tensor:
            return F.pixel_shuffle(input, self.upscale_factor)
                   ~~~~~~~~~~~~~~~ <--- HERE
    RuntimeError: Dimension out of range (expected to be in range of [-6, 5], but got 4294967290)
```

When I downgrade the Pytorch Mobile version to 1.7.1 the error disappears. I think the problem is caused in PixelShuffle layer because when I use another model for inference, the error is thrown in that layer as well. For example:

```
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/Models/ESPCN/___torch_mangle_163.py", line 29, in forward
        _10 = (_4).forward(_8, )
        _11 = (_3).forward()
        _12 = (_0).forward((_1).forward((_2).forward(_10, ), ), )
                            ~~~~~~~~~~~ <--- HERE
        _13 = torch.contiguous(_12, memory_format=0)
        return _13
      File "code/__torch__/torch/nn/modules/pixelshuffle/___torch_mangle_160.py", line 8, in forward
      def forward(self: __torch__.torch.nn.modules.pixelshuffle.___torch_mangle_160.PixelShuffle,
        argument_1: Tensor) -> Tensor:
        return torch.pixel_shuffle(argument_1, 2)
               ~~~~~~~~~~~~~~~~~~~ <--- HERE
```

I would appreciate any help with this. Thanks

cc @albanD @mruberry @jbschlosser

**Comment by t-vi** [comment]
To add the info from the [forum thread](https://github.com/pytorch/pytorch/issues/54051):

The number looks a lot like -6 mod 2**32, so it might be signedness issue.

Maybe the change to feeding negative numbers to permute in https://github.com/pytorch/pytorch/pull/49187
didn't go well. 
To make things specific, `-something.size()` seems very dubious in C++:

https://github.com/pytorch/pytorch/blob/603097be18824a33069addec7b8f14ba5c3bc67a/aten/src/ATen/native/PixelShuffle.cpp#L103

Personally, I think there isn't much of a reason to use negative indices for the leading dimensions at all. @jbschlosser , what do you think?

**Comment by jbschlosser** [comment]
@t-vi I agree with your analysis; that's definitely the issue. Working on a fix now.

It's disappointing that the tests didn't catch this- will investigate how to catch this earlier in the future.

**Comment by t-vi** [comment]
From what I can see this is because on 64 bit the result will be an uint64 that is then interpreted as signed int64 so it is the right negative number and the issue here is that the .size was uint32 and so this showed up only on 32 bit. So really, we'd need 32 bit CI to catch this type of thing reliably (anecdotally, I also found that JIT tracing didn't work on 32 bit ARM a long time ago, but I never looked into why).

TBH the behaviour of "-unsigned int" seemed rather surprising to me when I first saw it, but what do I know.

**Comment by jbschlosser** [comment]
> So really, we'd need 32 bit CI to catch this type of thing reliably (anecdotally, I also found that JIT tracing didn't work on 32 bit ARM a long time ago, but I never looked into why).

Huh, I didn't realize we don't have 32bit CI- that's unfortunate.
