### ISSUE TITLE
Implement Log Matmul

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#54064]
**Edit**: As discussed below, log matmul seems more acceptable

## 🚀 Feature

Implement GPU/CPU kernels for efficient regularized Wasserstein distance computation (Sinkhorn).

## Motivation

The regularized Wasserstein distance between samples is a frequent metric used in various deep learning models.

One intuitive way to think about it is that it is a distance (in the underlying space)-aware alternative to KL divergence for measuring distances between probability measures.

In the time since [Cuturi](https://papers.nips.cc/paper/2013/hash/af21d0c97db2e27e13572cbf59eb343d-Abstract.html) from 2013 and [Frogner et al.](https://papers.neurips.cc/paper/2015/hash/a9eb812238f753132652ae09963a05e9-Abstract.html) from 2015, this has developed into a very useful general purpose tool. Recent notable applications using the Wasserstein distance include [SwAV](https://github.com/facebookresearch/swav), but it is also of interest more generally to [compare probability distributions](https://github.com/pytorch/pytorch/issues/51777) or interpolate between them.

One key computational challenge is that stable implementation requires (more or less) a matrix multiplication using logsumexp instead of regular dot products, this is much easier to get with a custom kernel. (And logsumexp is much more stable than factoring out large scalars which has been proposed as a make-do stabilization.)

## Pitch

I propose to implement a [sinkhorn kernel](https://lernapparat.de/sinkhorn-kernel/).

## Alternatives

Implement it a specialized library, but I think the applications are numerous and general enough to warrant inclusion into PyTorch proper.

## Additional context

Related: #51777

**Comment by t-vi** [comment]
Also related #52207

**Comment by vadimkantorov** [comment]
Also, related to cdist variants with more reductions and keops-style kernel generators/compilers

**Comment by mruberry** [comment]
Are there other frameworks that have implementations?

**Comment by t-vi** [comment]
@mruberry I'm not aware, but so for JAX my understanding is that the type of kernel you need is well-covered by the JIT mechanism, so the need to add it as a kernel might be lower.
I have been using the kernel for quite a few years now and e-mail questions about it seem to have picked up, too.

If you are worried about it being to specific, one could also split it and only offer the log-space matrix-multiplication (`log (A.exp() @ b.exp())`). This would cover the core need, even if it is somewhat less efficient for the use-case.

**Comment by mruberry** [comment]
@t-vi Thanks for the update. It's an interesting suggestion and I'd like to socialize this internally.

**Comment by mruberry** [comment]
@ngimel @jbschlosser @albanD and I had a chance to discuss this issue a bit, @t-vi, and we're interested in starting with the log-space matmul you've suggested. We think we'd take a PR adding it, but we'd like to sanity check the proposed function signature and behavior first. Do you already have a kernel implementing the operation?

**Comment by t-vi** [comment]
Cool!
I would make it This would be `logmm(Tensor, Tensor) -> Tensor` and base it on the kernel from this notebook (But I need to check the backward.). This would be the `ik,kj->ij` matmul, we could also include batching from the start to mirror `matmul`.

https://github.com/t-vi/pytorch-tvmisc/blob/master/wasserstein-distance/Pytorch_Wasserstein.ipynb

What do you think?

**Comment by ngimel** [comment]
If including batching is feasible, we better do it from the start. Otherwise, starting from logmm sounds good.

**Comment by t-vi** [comment]
I think this isn't as urgent, as there are good workarounds.

**Comment by velezbeltran** [comment]
Hello!

I wanted to know if there had ever been an efficient implementation of this or if anyone had any pointers to where to look for this feature. 

Thank you
