### ISSUE TITLE
[nnc] Handle int64 indices and loop bounds

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#54095]
#54094 adds disabled tests (which would currently fail on trunk if enabled) showing the use of int64/long for tensor dims and loop bounds.  This should be supported.  In particular we (a) should use int64_t for the loop bound `n`, and (b) shouldn't need the `(int)n` cast in the load/store index expressions.

**Comment by desertfire** [comment]
Would this cause any problem on 32-bit platforms (e.g. small device)?

**Comment by ZolotukhinM** [comment]
Closing as fixed by #59769.
