### ISSUE TITLE
Inferring NumPy array type when using `from_numpy`

### ISSUE THREAD

**Issue by rasbt** [pytorch/pytorch#541]
Hi,
I love the PyTorch library so far, but I wanted to note one little annoyance that I encountered  -- something that could be improved in future. For instance, when I convert numpy arrays to torch tensors, it disregards the original NumPy type and creates `torch.DoubleTensor /torch.cuda.DoubleTensor`s. I think it would make more sense to inherit the array type float, int, etc. to create the tensors.

Here's a simple example:

```import torch
import numpy as np
import torch

y = np.array([[1., 2., 3.],
              [4., 5., 6.]])

torch.from_numpy(y)
```

Output:

```
1  2  3
4  5  6
[torch.DoubleTensor of size 2x3]
```

**Comment by apaszke** [comment]
It will always create a tensor of a corresponding type. It doesn't do a memory copy, and only views onto `ndarray`'s memory, so it can't use a different data type, or you'd see complete garbage there.

`y.dtype` is `dtype('float64')` i.e. `double`. E.g. this:

```python
y = np.array([[1., 2., 3.],
              [4., 5., 6.]], dtype=np.int32)

torch.from_numpy(y)
```

gives
```
 1  2  3
 4  5  6
[torch.IntTensor of size 2x3]
```

**Comment by ejoebstl** [comment]
There seem to be problems with certain numpy types though. 

```
y = np.array([[1., 2., 3.],
                     [4., 5., 6.]], dtype=">f4")
torch.from_numpy(y)
```

Gives

```
1.00000e-41 *
  4.6006  0.0090  2.3049
  4.6007  5.7487  6.8966
[torch.FloatTensor of size 2x3]
```

Such types are common when using `np.from_file`.

**Comment by fmassa** [comment]
@ejoebstl those cases should probably raise an error in PyTorch (I'm TH supports changing the endianness of the underlying data). Can you open an issue?

**Comment by ejoebstl** [comment]
Done. #3671
