### ISSUE TITLE
Integer division behavior is different from Python and NumPy

### ISSUE THREAD

**Issue by mdraw** [pytorch/pytorch#5411]
- PyTorch version: current master (10fd27)
- How you installed PyTorch (conda, pip, source): from source
- Python version: 3.6

When dividing two ints in pure Python, the result is always a float, e.g.

    >>> x = 5 / 3
    >>> print(x)
    1.6666666666666667
    >>> print(type(x))
    <class 'float'>

NumPy shares this behavior:

    >>> import numpy as np
    >>> x = np.array([5], dtype=np.int64) / np.array([3], dtype=np.int64)
    >>> print(x)
    [1.66666667]
    >>> print(x.dtype)
    float64

PyTorch uses floor division if both operands have integer types:

    >>> from torch import LongTensor
    >>> x = torch.LongTensor([5]) / torch.LongTensor([3])
    >>> print(x)

    1
    [torch.LongTensor of size (1,)]
    >>> print(x.type())
    torch.LongTensor

I find it confusing that PyTorch uses different division semantics than NumPy and Python. It is a potential source of bugs for users coming from a NumPy background and for users who want to port their code from NumPy to PyTorch.

For floor division that keeps the integer type, Python already has the dedicated `//` operator (which is also understood by NumPy). I would propose that PyTorch changes its handling of division so that the `/` operator always performs true division and introduces the `//` operator that explicitly means floor division.

I see two potential problems with changing PyTorch's division behavior like this:
- This is quite a fundamental change that can break exisiting code.
- There is still the open question on how to behave on Python 2 with/without `from __future__ import division`. NumPy also respects this future import, so depending on the future imports, Python 2 code can either cause the old floor-division behavior (where dividing two `np.*int*` types results in a floor division) or the new one (always perform true division). I don't know how hard it would be to mimic this behavior and if it's worth the effort.

Despite these problems, I still believe this change is important in the long run. What do you think?

**Comment by zou3519** [comment]
@li-roy is taking a lookj.

**Comment by RBirkeland** [comment]
@zou3519 Any update on this? Just found this error as well.

**Comment by arogozhnikov** [comment]
Faced this too. Also `//` is not supported.

**Comment by jdhao** [comment]
> In [2]: a = torch.tensor(100)
> In [3]: a/120
> Out[3]: tensor(0)
> In [4]: float(a/120)
> Out[4]: 0.0

why does a divided by 120 is zero instead of 0.8333? Is this the expected behavior?

**Comment by gchanan** [comment]
Yes, this is currently expected behavior.  We may change it in the future.

**Comment by robd2** [comment]
Also having this issue. What is the best way to code around this behavior?

**Comment by zou3519** [comment]
x = torch.LongTensor([5]).to(dtype=torch.float) / torch.LongTensor([3]).to(dtype=torch.float)

**Comment by robd2** [comment]
> .to(dtype=torch.float)
how would you apply this to the example above by @jdhao ?

**Comment by zou3519** [comment]
```
a = torch.tensor(100)
a.to(dtype=torch.float) / float(120)
```

**Comment by jspisak** [comment]
cc @rmunro - see the workaround from @zou3519. This is an expected bahavior..

another workaround, as @rmunro found was to just cast to a float.

**Comment by jhrmnn** [comment]
Just hit this as well, also find it very confusing. (I initially found the issue by doing integer to non-integer power, but I assume these are all related.)

Is this simply an architectural decision that won't change (in which case this should be closed, and I'd argue that this semantics should be mentioned in the tutorials for beginners), or is it still open up for a debate?

**Comment by zou3519** [comment]
I believe this is still up for debate. cc @gchanan is this accurate?

I'm personally in support of this (changing the behavior to match Python / numpy) for all of the reasons mentioned above. Furthermore, there won't be any confusing semantics between Python 2 and Python 3 in the future because we're dropping support for Python 2 soon: https://github.com/pytorch/pytorch/issues/23795

**Comment by mruberry** [comment]
In PyTorch 1.6 we plan to prevent integer division using torch.div, and in 1.7 we expect torch.div will perform true division like Python and NumPy do.

**Comment by jhrmnn** [comment]
Will `torch.pow` be included in this change as well?

```python3
>>> np.array(2) ** 2.5
5.656854249492381
>>> torch.tensor(2) ** 2.5
tensor(5)
```

**Comment by mruberry** [comment]
Not part of the same change, no, but that behavior will also likely happen in a future release.

**Comment by pquadri** [comment]
To add on this, today I found a similar issue with this line:   
`1. / weights`  
where weights is a Long tensor. I would have expected to have a consistent output with regular Python and Numpy and obtain a float value from the division. 

I think the "issue" here might be the fact that [here](https://github.com/pytorch/pytorch/blob/d80e0c62bea9cc4f0b3c46edbcf892baee38b4c8/torch/tensor.py#L398) only the tensor type is checked and not the one of the other number.

**Comment by mruberry** [comment]
> To add on this, today I found a similar issue with this line:
> `1. / weights`
> where weights is a Long tensor. I would have expected to have a consistent output with regular Python and Numpy and obtain a float value from the division, but i got a tensor of 0s.
> 
> I think the "issue" here might be the fact that [here](https://github.com/pytorch/pytorch/blob/d80e0c62bea9cc4f0b3c46edbcf892baee38b4c8/torch/tensor.py#L398) only the tensor type is checked and not the one of the other number.

Your analysis is correct. And you're right: that behavior will need to change, too. We were just looking at this today, actually.

**Comment by mruberry** [comment]
I believe, as of PyTorch 1.7, this issue is resolved (including rdiv).
