### ISSUE TITLE
Dimension Configuration regarding MultiheadAttention

### ISSUE THREAD

**Issue by RchalYang** [pytorch/pytorch#54128]
## ❓ Questions and Help

Regarding MultiheadAttention, It seems the current Pytorch Implementation uses the same dimension for Query and the final Output.

In another word, the att_output's shape depends on the shape of the query. I'm not sure whether this is expected? 

[Attention Paper](https://arxiv.org/pdf/1706.03762.pdf) According to the original paper, the v's dimension should not depend on the dimension of the query right?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @zhangguanheng66

**Comment by RchalYang** [comment]
'''

        if self._qkv_same_embed_dim is False:
            self.q_proj_weight = Parameter(torch.Tensor(embed_dim, embed_dim))
            self.k_proj_weight = Parameter(torch.Tensor(embed_dim, self.kdim))
            self.v_proj_weight = Parameter(torch.Tensor(embed_dim, self.vdim))
            self.register_parameter('in_proj_weight', None)
        else:
            self.in_proj_weight = Parameter(torch.empty(3 * embed_dim, embed_dim))
            self.register_parameter('q_proj_weight', None)
            self.register_parameter('k_proj_weight', None)
            self.register_parameter('v_proj_weight', None)



        self.out_proj = _LinearWithBias(embed_dim, embed_dim)
'''
 https://pytorch.org/docs/stable/_modules/torch/nn/modules/activation.html#MultiheadAttention 

Here is the current implementation of MultiheadAttention, it's clear the query and output have the same dimension.

**Comment by zhangguanheng66** [comment]
> ## ❓ Questions and Help
> Regarding MultiheadAttention, It seems the current Pytorch Implementation uses the same dimension for Query and the final Output.
> 
> In another word, the att_output's shape depends on the shape of the query. I'm not sure whether this is expected?
> 
> [Attention Paper](https://arxiv.org/pdf/1706.03762.pdf) According to the original paper, the v's dimension should not depend on the dimension of the query right?
> 
> ### Please note that this issue tracker is not a help form and this issue will be closed.
> We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:
> 
> * [Discussion Forum](https://discuss.pytorch.org/)
> 
> cc @zhangguanheng66

Could you refer me the paragraph of the paper for your argument?

**Comment by RchalYang** [comment]
Sorry, I misunderstood something about the paper. The paper uses the same dimension for Q, K, V as self-attention. Sorry for the trouble
