### ISSUE TITLE
libtorch 1.8.0 precompiled has no CUDA backend linked (Adding  "-INCLUDE:?warp_size@cuda@at@@YAHXZ" no longer helps)

### ISSUE THREAD

**Issue by lablabla** [pytorch/pytorch#54131]
## 🐛 Bug

Trying to load JIT torchscript model in Windows 10 using precompiled torch 1.8.0 with CUDA 11.1 results in 
```
Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).
```

This was previously solved by adding `"-INCLUDE:?warp_size@cuda@at@@YAHXZ"` to the linker options of MSVC as suggested [here](https://github.com/pytorch/pytorch/issues/33435#issuecomment-685241862)

when moving to 1.8.0 I added `torch_cuda_cpp.lib` and `torch_cuda_cu.lib` to the linked libraries

The same torchscript works well in 1.7.1

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): Windows 10 (MSVC 2017)
 - How you installed PyTorch (`conda`, `pip`, source): Precompiled binaries
 - Build command you used (if compiling from source):
 - Python version: N/A (Libtorch)
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Quatro P1000
 - Any other relevant information:

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
Hi @lablabla the official way of using LibTorch is through CMake since it handles the trivial linking things. Can you give cmake a try? Also can you share the minimum repro torchscript? I'll see if I can repro this locally.

**Comment by mszhanyi** [comment]
@lablabla, could you refer this command to run your program 
`cl %BUILDER_ROOT%\test_example_code\check-torch-cuda.cpp torch_cpu.lib c10.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EHsc /link /INCLUDE:?warp_size@cuda@at@@YAHXZ /INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z`

https://github.com/pytorch/builder/blob/master/test_example_code/check-torch-cuda.cpp

**Comment by lablabla** [comment]
@mszhanyi , following your suggestion, I added `/INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z` and now it works, so at least I have a workaround. Thanks!

@skyline75489 
I am using CMake to generate the VS project, but I might not be using it correctly using the `find_package(torch)` and using the generated libraries. I'll adjust my cmake to use it and remove the added `/INCLUDE` linker options and check again. Also, if the problem will continue I will try and create a minimal torchscript with minimal separate VS project to reproduce. Will report soon. Thanks

**Comment by lablabla** [comment]
@skyline75489 using the cmake properly by calling `find_package(Torch)` and then linking the `${TORCH_LIBRARIES}` to the `target_link_libraries` call fixed the problem.

looking at the linker input, it adds the 
```
-INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z
-INCLUDE:?warp_size@cuda@at@@YAHXZ
```
calls, so it works great now
Closing.

Thanks!

**Comment by mszhanyi** [comment]
@lablabla @yoshihingis 
I write a VS extension to setup libtorch project so users don't need to run cmake again.
So far, it only supports libtorch 1.9 (cpu, cuda102, cuda11.1 in https://pytorch.org/)
The preview version could be download in https://ossci-windows.s3.us-east-1.amazonaws.com/vsextension/VSIXTorch.vsix

The demo video is https://ossci-windows.s3.us-east-1.amazonaws.com/vsextension/demo.mp4.

Any comments are welcome

**Comment by rodrigovimieiro** [comment]
`/INCLUDE:"?ignore_this_library_placeholder@@YAHXZ"`

Worked with:

_libtorch 1.12
cuda 11.3
Visual Studio Enterprise 2019
Windows 10_

Quoted from:
> https://github.com/pytorch/pytorch/issues/37124#issuecomment-888830933

Although the code compiles fine without it, it throws `PyTorch is not linked with support for cuda devices` when executed
