### ISSUE TITLE
Calling test/quantization/test_quantized_op.py directly doesn't do anything

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54154]
Invoking test files directly should result in unittest runner being invoked

cc @mruberry @VitalyFedyunin @walterddr @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by walterddr** [comment]
Should we raise RuntimeError instead? other files in test/quantization/test_*.py throws 
```
This test file is not meant to be run directly, use:
python test/test_quantization.py TESTNAME instead.
```

**Comment by jerryzh168** [comment]
yeah, we are following jit which has one top level test that includes other tests:
https://github.com/pytorch/pytorch/blob/master/test/test_jit.py

example non-runnable individual test file:
https://github.com/pytorch/pytorch/blob/master/test/jit/test_tracer.py

The benefit of this structure is that we don't need to remember both the file name that test case class resides and the name of test case class in and only need to remember the test name.

```
python test/individual_test_file_name TESTNAME.individiual_test
v.s.
python test/test_quantization.py TESTNAME.individiual_test
```

**Comment by jerryzh168** [comment]
@ezyang we'll raise exceptions as suggested by @walterddr, does that sound good?

**Comment by ezyang** [comment]
sgtm
