### ISSUE TITLE
erf and erfc tests in test_ops.py sometimes don't exist

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54152]
In this CI job you can see that erf/erfc have failed: https://app.circleci.com/pipelines/github/pytorch/pytorch/286464/workflows/f98f8828-6010-404e-bfcb-8dcbdb68c4ee/jobs/11609202

When I run the test locally, no such test exists

```
$ python test/test_ops.py TestCommonMETA.test_variant_consistency_eager_erf_meta_int32
E
======================================================================
ERROR: test_variant_consistency_eager_erf_meta_int32 (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestCommonMETA' has no attribute 'test_variant_consistency_eager_erf_meta_int32'

----------------------------------------------------------------------
Ran 1 test in 0.000s
```

I'm guessing this is build configuration related. But the set of defined tests should NEVER vary based on build config; we should always define the test (and skip it if it's not necessary!)

cc @mruberry @VitalyFedyunin @walterddr

**Comment by ezyang** [comment]
cc @mruberry

**Comment by kshitij12345** [comment]
OpInfo entry for `erf/erfc` is currently added if scipy is installed in the environment.

https://github.com/pytorch/pytorch/blob/527c1e0e37b7c65148bcbc390b65e94fb4624a9d/torch/testing/_internal/common_methods_invocations.py#L2942

Below this line are the operators whose OpInfo is added conditionally based on scipy being present.

**Comment by ezyang** [comment]
@kshitij12345 Thanks for diagnosing. So what we should do is unconditionally add the OpInfo, but then skip all the constituent tests when scipy is not available.
