### ISSUE TITLE
Add separate function for computing singular values

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#54155]
## 🚀 Feature

Add `torch.linalg.svdvals(input, out=None)` that returns singular values of `input`.

## Motivation

In NumPy there are separate functions for computing only eigenvalues (`numpy.linalg.eigvals`, `numpy.linalg.eigvalsh`) and eigenvalues together with eigenvectors (`numpy.linalg.eig`, `numpy.linalg.eigh`).

For `numpy.linalg.svd` computing only singular values or together with singular vectors is controlled with `compute_uv=True/False`. Instead of the `compute_uv` flag, it would be more consistent to have a separate function: `svdvals`.

This function exists in [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.svdvals.html) and [Julia](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.svdvals).

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
This is an interesting idea, would you elaborate on its details? In particular, what would the signatures for torch.linalg.svd() and torch.linalg.svdvals() be? Should we keep the compute_uv flag on torch.linalg.svd(), anyway, and if it's False just call torch.linalg.svdvals()?

**Comment by IvanYashchuk** [comment]
The signatures would be `torch.linalg.svdvals(Tensor input) -> Tensor` and `torch.linalg.svd(Tensor input, bool full_matrices=True) -> (Tensor U, Tensor S, Tensor Vt_or_V)`. But I guess we can't drop the compute_uv flag because of backwards and NumPy compatibility. However, we're already incompatible with NumPy in the return type for `compute_uv=False`.

**Comment by mruberry** [comment]
I'll try and take a closer look at this issue and how we can generally handle optional tensor returns soon.

**Comment by nikitaved** [comment]
Would it be useful to have this non-differentiable method? Or the goal is to provide all the methods that are in `numpy.linalg`?

**Comment by IvanYashchuk** [comment]
> Would it be useful to have this non-differentiable method?

`torch.linalg.svd` with `compute_uv=False` raises an error so nothing changes for autograd.

> Or the goal is to provide all the methods that are in numpy.linalg?

The goal is to provide all functions available in `numpy.linalg` as `torch.linalg` and on top of that to provide additional useful linear algebra operations that require calling external libraries and are not easily implementable as a composition of operations already available in PyTorch.

It would be nice to have full NumPy compatibility for linalg module, but we already break it for `torch.linalg.svd(input, compute_uv=False)` by returning a tuple and not a single tensor because of PyTorch restrictions. And the problem would not exist if NumPy didn't have this flag and there was a separate function as is the case with eig <-> eigvals, eigh <-> eigvalsh.

**Comment by sdamadi** [comment]
does not work. 
```
v = torch.linalg.svdvals(A)
AttributeError: module 'torch.linalg' has no attribute 'svdvals'
```

**Comment by IvanYashchuk** [comment]
Hi @sdamadi, to access this function you need to have one of the recent releases of PyTorch. What version are you using and how did you install it?

**Comment by sdamadi** [comment]
1.8.0+cu111
