### ISSUE TITLE
Use dispatcher to split up quantized operations

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54150]
There are a bunch of operators which are defined like this:

```
std::tuple<Tensor, Tensor> max(const Tensor& self, int64_t dim, bool keepdim) {
  Tensor max_indices = at::empty({0}, self.options().dtype(kLong));
  if (self.is_quantized()) {
    Tensor max = at::empty({0}, self.options().dtype(toUnderlying(self.scalar_type())));
    at::native::max_out(max, max_indices, self.int_repr(), dim, keepdim);
    // TODO: qscheme
    return std::tuple<Tensor, Tensor>(at::_make_per_tensor_quantized_tensor(max, self.q_scale(), self.q_zero_point()), max_indices);
  } else {
    Tensor max = at::empty({0}, self.options());
    return at::native::max_out(max, max_indices, self, dim, keepdim);
  }   
}   
```

It would be better for the quantized portion of the conditional to be put in its own kernel, and then have it dispatched via QuantizedCPU.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
for triage

**Comment by vkuzo** [comment]
agreed.  Would be great to clean this up before quantization goes to stable.  The eng effort will be high, so this may be open for awhile.

**Comment by vkuzo** [comment]
@dzdang , is this issue ready to close or is there more remaining things to do?

**Comment by dzdang** [comment]
> @dzdang , is this issue ready to close or is there more remaining things to do?
I think we can close this. I'll put up a post soon with the changes that were made and justifications for situations where changes were not practical
