### ISSUE TITLE
[JIT] Provide an API to turn on and off JIT logging

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#54188]
## 🚀 Feature
Provide an API to turn on and off JIT logging, which is currently controlled by the env variable `PYTORCH_JIT_LOG_LEVEL`.

## Motivation
Currently turning logging on and off is done via the env variable and we only check it once and then cache the result - that makes it impossible to change the logging setting afterwards. It would be handy to be able to turn it on and off as many time as we'd like to pinpoint places where we need logs.

## Code Pointers

The relevant code is located in two files:
 * [torch/csrc/jit/jit_log.h](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/jit_log.h)
 * [torch/csrc/jit/jit_log.cpp](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/jit_log.cpp)

cc @gmagogsfm @Krovatkin

**Comment by narang99** [comment]
Can I try working on this as my first issue?
Could you tell me exactly what you mean by API? Would it be something like this:

`./build/bin/test_jit --logging=true`

**Comment by gmagogsfm** [comment]
@narang99 I think what's needed is an API usable inside program to turn on/off logging. That is more flexible than commandline flags or environment variables, which can only enable/disable *globally*. But this is just my speculation, I'd defer to @ZolotukhinM for more details.

**Comment by Krovatkin** [comment]
@narang99 We would like to have both C++ and Python API to enable/disable logging at arbitrary points in user scripts, binaries, tests, etc. For example,

```python
import torch

model1 = torch.jit.load('model1')
out1 = model1(inp.rand(2,2))
model2 = torch.jit.load('model2')
# enable logging now
torch._C.jit_set_logging_option('>>tensorexpr.cpp')
out2 = model2(out1)
torch._C.jit_set_logging_option('")
model3 = torch.jit.load('model3')
out3 = model3(out2)
torch.allclose(out3, torch.ones(2))
```

**Comment by narang99** [comment]
Ohk. Since theres another issue similar to this (#54182), I can try implementing both if thats ok

How do you suggest I handle global configuration? I saw some places in the codebase where singletons were used for global references. Should I follow the same pattern?  And is there any need to keep a lock for thread-safety?

**Comment by ZolotukhinM** [comment]
> Since theres another issue similar to this (#54182), I can try implementing both if thats ok

Awesome, thanks :)

> How do you suggest I handle global configuration? I saw some places in the codebase where singletons were used for global references. Should I follow the same pattern?

Yes, I think that would work.

> And is there any need to keep a lock for thread-safety?

Since this mostly used for debugging multi-threaded performance is rarely critical here. It'd be still good to keep it thread-safe.
