### ISSUE TITLE
[JIT] Provide an API to choose a different output stream for `PYTORCH_JIT_LOG_LEVEL`

### ISSUE THREAD

**Issue by ZolotukhinM** [pytorch/pytorch#54182]
## 🚀 Feature
Provide an API to choose a different output stream for `PYTORCH_JIT_LOG_LEVEL`, which by default is stderr.

## Motivation

The current default (stderr) makes it cumbersome to turn on logging in python notebooks. An ability to use stdout or another output stream should help with this issue.

## Code Pointers

The relevant code is located in two files:
 * [torch/csrc/jit/jit_log.h](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/jit_log.h)
 * [torch/csrc/jit/jit_log.cpp](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/jit_log.cpp)

cc @gmagogsfm, @Krovatkin

**Comment by VidocqH** [comment]
Hi, can I pick this issue as my first contribution to Pytorch?

**Comment by Krovatkin** [comment]
@VidocqH yes, please go ahead!

**Comment by VidocqH** [comment]
> @VidocqH yes, please go ahead!

Hi, I am now wondering what does the API look like? I think there will be a parameter to indicate the target output stream. But I am not sure if the parameter is an int like `1` for `stdout` and `2` for `stderr`? Or is it something else?

**Comment by Krovatkin** [comment]
@VidocqH 

I think it could be even more useful if it takes a file path and we could have a special file for "stdout" ?

@ZolotukhinM  what do you think?

**Comment by ZolotukhinM** [comment]
I would slightly prefer the target output stream option, as it'd allow to redirect logs into a string without invoking filesystem at all. I think that would be more convenient in a jupiter notebook environment, for instance.

**Comment by VidocqH** [comment]
> I would slightly prefer the target output stream option, as it'd allow to redirect logs into a string without invoking filesystem at all. I think that would be more convenient in a jupiter notebook environment, for instance.

Check my understanding, do you mean you prefer the one looks like `torch._C._jit_set_logging_output_stream('STDOUT')`?
I think that would leave only two options for the parameter: `stdout` and `stderr`. Did I miss anything?

**Comment by Krovatkin** [comment]
> it'd allow to redirect logs into a string without invoking filesystem at all

fair enough. though you could always get a string `my_log_str = open("my_log").read()`

@ZolotukhinM do you mind elaborating a little bit on a target stream approach?

**Comment by ZolotukhinM** [comment]
In C++ that API could look like this:
```
std::ostringstream my_stream;
torch::jit::set_logging_output_stream(my_stream);
```
In python bindings we could limit the options to just "stderr" or "stdout".

That said, I'm absolutely fine with the other proposed alternatives too.

**Comment by narang99** [comment]
Its been inactive since 2 July, mind if I take this?

**Comment by ZolotukhinM** [comment]
Yes, go for it please!

**Comment by narang99** [comment]
Ohk, Im thinking about getting rid of the singleton class since its API is not used outside of this class. Would just use static global variables. Sounds ok?

**Comment by ZolotukhinM** [comment]
Sounds good to me! @Krovatkin, any concerns from your side?
