### ISSUE TITLE
How to update a Wiki page?

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#54212]
## ❓ Questions and Help

The `-k` option for filtering tests with a string can no longer be used with `python`, and should be used with `pytest` now.

Pull requests can't be submitted for the Wiki, so I couldn't suggest an update to https://github.com/pytorch/pytorch/wiki/Writing-tests-in-PyTorch-1.8. 

Please update the Wiki page with this detail. Thank you!

cc @brianjo @mruberry @VitalyFedyunin @walterddr

**Comment by VitalyFedyunin** [comment]
Thanks for noticing. I made quick updates.
