### ISSUE TITLE
Autograd engine called while holding the GIL

### ISSUE THREAD

**Issue by victorprincipe** [pytorch/pytorch#54250]
## 🐛 Bug

I've been using pytorch to run biochemical simulations (through OpenMM) with an ML potential. I'm getting the following error message when the autogrid engine is called:

```
simtk.openmm.OpenMMException: The autograd engine was called while holding the GIL. If you are using the C++ API, the autograd engine is an expensive operation that does not require the GIL to be held so you should release it with 'pybind11::gil_scoped_release no_gil;'. If you are not using the C++ API, please report a bug to the pytorch team.
Exception raised from execute at /tmp/pip-req-build-h11ydgcy/torch/csrc/autograd/python_engine.cpp:93 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6a (0x7fe3243430ea in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x1cf (0x7fe2bf98169f in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x2b154f0 (0x7fe350be34f0 in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::backward(std::vector<at::Tensor, std::allocator<at::Tensor> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, c10::optional<bool>, bool) + 0x7f (0x7fe350be422f in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x30b42f1 (0x7fe3511822f1 in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x30b452d (0x7fe35118252d in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x1384453 (0x7fe34f452453 in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::Tensor::backward(c10::optional<at::Tensor> const&, c10::optional<bool>, bool) const + 0x100 (0x7fe34f4528d0 in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: TorchPlugin::OpenCLCalcTorchForceKernel::execute(OpenMM::ContextImpl&, bool, bool) + 0xbe4 (0x7fe2ed0d9644 in /home/victor/miniconda3/envs/openmmani/lib/plugins/libOpenMMTorchOpenCL.so)
frame #9: OpenMM::ContextImpl::calcForcesAndEnergy(bool, bool, int) + 0xca (0x7fe36bdd2c9a in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/simtk/openmm/../../../../libOpenMM.so.7.5)
frame #10: OpenMM::Context::setVelocitiesToTemperature(double, int) + 0xdc (0x7fe36bdcf36c in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/simtk/openmm/../../../../libOpenMM.so.7.5)
frame #11: <unknown function> + 0x1150ec (0x7fe36c19b0ec in /home/victor/miniconda3/envs/openmmani/lib/python3.7/site-packages/simtk/openmm/_openmm.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
frame #25: __libc_start_main + 0xe7 (0x7fe36d994b97 in /lib/x86_64-linux-gnu/libc.so.6)
```

I'm not very skilled in programming so I wasn't too sure where exactly to raise this issue. Please let me know if you need any other information.

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080
GPU 3: GeForce GTX 1080

Nvidia driver version: 440.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] openmmtorch==1.0
[pip3] torch==1.7.1
[pip3] torchani==2.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] magma                     2.5.4                h1cd326d_1    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.3.0            py37h54f3939_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] openmm-torch              0.1              py37h4f7c550_1    conda-forge
[conda] pytorch                   1.7.1           cuda100py37h50b9e00_1    conda-forge
[conda] pytorch-gpu               1.7.1           cuda100py37hf721545_1    conda-forge
[conda] torchani                  2.2                pyh9f0ad1d_0    conda-forge
## Additional context

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by ejguan** [comment]
@victorprincipe 
Can you share a self-contained script which we could use to reproduce the problem?

**Comment by victorprincipe** [comment]
Please see the zip file below. It contains the script (md_ani_2.py) as well as the raw input files. I've also added a package that needs to be installed (openmm-ml), and it requires install of ParmEd (conda install -c omnia parmed ) and OpenMM (conda install -c omnia openmm). The script is run with the command 
`python md_ani_2.py solvated_complex.prmtop solvated_complex.inpcrd`
I'm sorry if this isn't the 'self-contained' script you were referring to (I'm still new to all this), but please let me know if there is anything else you need, and thank you for looking into this issue.
[github_issue.zip](https://github.com/pytorch/pytorch/files/6165293/github_issue.zip)

**Comment by albanD** [comment]
Hey!

What I expect is happening here is that you have some custom c++ code that calls into the autograd engine.
So two cases:
- if that c++ code is aware of python, it should release the GIL before entering the engine.
- if that is a pure c++ lib, then your binding code from that pure c++ code to python should be releasing the GIL before calling into that c++ lib.

Not sure which case is relevant for you here?

**Comment by victorprincipe** [comment]
I've found out that it's an issue with OpenMM rather than PyTorch, and a fix should be coming soon. Not too sure exactly what the issue was but I think it was the first case...anyways it should be sorted soon.

Thanks anyways for looking into it!
