### ISSUE TITLE
`torch.triangular_solve`'s documentation is misleading when `transpose` is explicitly specified but `upper` is not.

### ISSUE THREAD

**Issue by nikitaved** [pytorch/pytorch#54258]
## 🐛 Bug
As per title. See the code example below.

## To Reproduce
```python
>>> import torch                                                                                                                                                      [7/182]
>>> b = torch.rand(3, 3, dtype=torch.cdouble)                                                                                                                                
>>> a = torch.rand(3, 3, dtype=torch.cdouble).triu()                                                                                                                         
>>> at = a.transpose(-1, -2)                                                                                                                                                 
>>> (a @ x - b).abs().max()
tensor(1.2413e-16, dtype=torch.float64)
>>> y = torch.triangular_solve(b, at, upper=False).solution
>>> (at @ y - b).abs().max()
tensor(1.3878e-16, dtype=torch.float64)
>>> z = torch.triangular_solve(b, at, transpose=True).solution
>>> (a @ z - b).abs().max()
tensor(1.8858, dtype=torch.float64)
>>> z = torch.triangular_solve(b, at, transpose=True, upper=False).solution
>>> (a @ z - b).abs().max()
tensor(1.2413e-16, dtype=torch.float64)

```

The documentation says that `transpose` controls whether the input is to be transposed before the driver is applied.
Also, `upper` is explained as a parameter that decides whether to solve an upper/lower triangular system.
What is the connection between `upper` and `triangular`? Are they independent or not?

Apparently, `upper=True` actually means that the input (prior to transposition) is upper triangular, and is lower triangular when `upper=False`,
which you can indeed infer from the fact that `upper` precedes `transpose` in the list of arguments, but it is still could be confusing given how `upper` is defined.

The relationship between `upper` and `transpose` has to be clarified in greater details.

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
A PR improving the documentation would be great!
