### ISSUE TITLE
torch.from_numpy is slow for mmap'ped numpy arrays

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#5426]
I'm looking at feasibility of using Ray as parameter server combined with single-machine NN implementation. 

The bottleneck for using it with PyTorch is that result of Ray calls come as numpy array created on top of [mmaped memory](https://groups.google.com/forum/#!msg/ray-dev/pNsxWI-iSyI/vhWnjgAfAwAJ), and PyTorch `from_numpy` on these arrays is slow, working at about 2.5 GB/sec, which is the speed of single-threaded memcpy.

Regular numpy array can be turned into PyTorch GPU tensors at 8-11 GB/sec, depending on whether memory has been page locked.

Is this memcpy necessary? Can it be done in multi-threaded way?
Related issue on Ray side: https://github.com/ray-project/ray/issues/1614

https://github.com/diux-dev/cluster/blob/master/yuxin_numpy/tf_numpy_benchmark.py

Pytorch 0.3.0.post4
Repro instructions like in https://github.com/pytorch/pytorch/issues/5412#issuecomment-368658892
```
# torch.from_numpy(ray.get(f.remote()))
python tf_numpy_benchmark.py --benchmark=pytorch_from_numpy_noclone --allocator=ray --num-iters=51
pytorch_from_numpy            :   2.5 GB/sec, min: 39.86, median: 41.38, mean: 63.55

# torch.from_numpy(page_locked_numpy).cuda()
python tf_numpy_benchmark.py --benchmark=pytorchgpu_from_numpy --allocator=tfgpu --num-iters=51
pytorchgpu_from_numpy         :  11.0 GB/sec, min:  9.05, median:  9.07, mean:  9.07

# torch.from_numpy(regular_numpy).cuda()
python tf_numpy_benchmark.py --benchmark=pytorchgpu_from_numpy --allocator=numpy --num-iters=51
pytorchgpu_from_numpy         :   8.2 GB/sec, min: 12.24, median: 12.42, mean: 12.45
```

**Comment by apaszke** [comment]
I can't see any reason why this would happen, and I would suspect it might be caused by ray somehow. What's `f.remote()`? There's no memcpy we're doing when creating PyTorch tensors from numpy ([here's the full source](https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_numpy.cpp#L91-L124), it's just 30 lines).

**Comment by yaroslavvb** [comment]
I'm not measuring the time it takes to do `f.remote`, the slowness is in `torch.from_numpy` call

```
arr = ray.get(f.remote())
start_time = time.time()
torch.from_numpy(arr)
print("%.1f ms "%((time.time()-start_time)*1000,)) # => 462ms
```
This takes 462 milliseconds on a 1GB numpy array.

Here's the full [benchmark](https://raw.githubusercontent.com/diux-dev/cluster/master/yuxin_numpy/pytorch_slow_numpy_bug.py). 

```
pip install ray
wget https://raw.githubusercontent.com/diux-dev/cluster/master/yuxin_numpy/pytorch_slow_numpy_bug.py
python pytorch_slow_numpy_bug.py

...
462.9 ms 
```

Here's [cpu profile](https://www.dropbox.com/s/5zk9qn6oasfkzve/pytorch.svg?dl=1) of the benchmark (from google-perf-tool)

Not sure how accurate it is, but it shows 15% of the time in `__nss_passwd_lookup` which usually means memcpy

**Comment by yaroslavvb** [comment]
Oh....it looks like `arr` is not a numpy array....and there's some extra stuff going on on Ray side `__array__?`, will reopen if I can isolate this to PyTorch

**Comment by apaszke** [comment]
Yeah, once you have a numpy array the conversion should be pretty much immediate irrespectively of its size (it doesn't depend on it). Last time I measured it a few months ago, it cost around 3us.

**Comment by yaroslavvb** [comment]
So `from_numpy` is slow if I do

`torch.from_numpy(arr)`

But `from_numpy` is fast if I do
```
arr = np.array(arr)
torch.from_numpy(arr)
```

Running this under cProfile shows that the time is spent under `torch._C.from_numpy`

![screenshot 2018-02-27 09 54 08](https://user-images.githubusercontent.com/23068/36745383-2d4cb482-1ba4-11e8-8e09-ca95c8d2600a.png)

**Comment by robertnishihara** [comment]
@yaroslavvb, Ray creates a read-only numpy array (since it is backed by shared memory), so

```python
import numpy as np
import ray
import torch

ray.init()

@ray.remote
def f():
    return np.zeros(25 * 10 ** 6, dtype=np.float32)

x = ray.get(f.remote())  # Now x is read only.
t = torch.from_numpy(x)  # This does a copy because x is read only.
```

We can try turning off the read-only flag and see if that fully gets rid of the issue or if there are any remaining slowdowns.

**Comment by apaszke** [comment]
`from_numpy` does *nothing* to the tensor data (as can be seen in the linked source). It's possible that the NumPy API we're using to implement the conversion is doing something very expensive under the hood, which would explain why the second case is fast. This is caused by the package implementing `arr`. Let me know if you can think of any improvements, but I don't think there's anything we can do here.

**Comment by yaroslavvb** [comment]
BTW, I think `arr` is just regular numpy ndarray in the slow case. IE

(Pdb) arr.__class__
<class 'numpy.ndarray'>

However, the result of torch.from_numpy(arr) is mutable, whereas the arr's backing memory is marked as read-only, so something must be triggering a copy

**Comment by apaszke** [comment]
Hmm I think it's possible that we're just not respecting the flags in the current implementation. I'm pretty sure we did check that before, but I can't see any conditionals that would depend on this anywhere

**Comment by yaroslavvb** [comment]
https://github.com/diux-dev/cluster/blob/master/yuxin_numpy/pytorch_modify_test.py

```
arr = ray.get(f.remote())
arr.__class__ # => "<class 'numpy.ndarray'>"
arr+=1 # fails with  "ValueError: output array is read-only"
arr = torch.from_numpy(arr)
arr+=1  # works


```

**Comment by apaszke** [comment]
I've opened another issue to track this

**Comment by internetingofthings** [comment]
Different application, I found that processing an array in pytorch using CUDA device is very fast, but displaying the result incurs 200 msec penalty when converting back to numpy array.

example:
torch_array = torch.from_numpy(numpy_array) # less than 1msec
do processing on torch_array  # less than 1 msec on GPU @ 99%
numpy_array = np.array(torch_array) # greater than 200 msec

does anyone know a method that avoids the conversion penalty back to numpy. GPU = nvidia on TX1 platform

**Comment by Santosh-Gupta** [comment]
> So `from_numpy` is slow if I do
> 
> `torch.from_numpy(arr)`
> 
> But `from_numpy` is fast if I do
> 
> ```
> arr = np.array(arr)
> torch.from_numpy(arr)
> ```
> 
> Theory: `np.array(arr)` copies things from mmaped area to process local memory area, so from_numpy becomes fast
> 
> Running this under cProfile shows that the time is spent under `torch._C.from_numpy`
> 
> ![screenshot 2018-02-27 09 54 08](https://user-images.githubusercontent.com/23068/36745383-2d4cb482-1ba4-11e8-8e09-ca95c8d2600a.png)

Has there since been any updates to Pytorch which would change any of these assumptions? 

I am trying to both load and write values from/to a numpy memmap to a pytorch cuda mounted tensor, and vise versa, as fast as possible.
