### ISSUE TITLE
init_rpc: TENSOR_PIPE backend sigaborts when CUDA is not available

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#54266]
## 🐛 Bug

With torch 1.8.0, init_rpc will sigabort when using TENSOR_PIPE backend and CUDA is not available. Works fine with PROCESS_GROUP backend.

## To Reproduce

1.
1.
1.

$ cat test.py
import tempfile
import torch.distributed.rpc as rpc

init_file = tempfile.mkstemp()[1]
options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file, _transports=["uv"])
rpc.init_rpc("worker0", rank=0, world_size=1, backend=rpc.BackendType.TENSORPIPE, rpc_backend_options=options)

$ python test.py
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)

## Expected behavior

No crash.

## Environment
venv) circleci@0da8447e6d8d:~/fairscale$ uname -a
Linux 0da8447e6d8d 4.15.0-1092-aws #98-Ubuntu SMP Wed Jan 6 22:22:51 UTC 2021 x86_64 GNU/Linux

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0+cu111
[pip3] torchtext==0.6.0
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma @pietern @zhaojuanmao @satgera @aazzolini @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by lw** [comment]
Is this occurring when running within Docker? Could you try launching Docker with the `--security-opt seccomp=unconfined` option?

**Comment by msbaines** [comment]
> Is this occurring when running within Docker? Could you try launching Docker with the `--security-opt seccomp=unconfined` option?

I'm not sure how to do that with CircleCI. Here is our config:

https://github.com/facebookresearch/fairscale/blob/f7e6680b651ca85c425dce24f30631e8f5e1f047/.circleci/config.yml#L27

docker:
    - image: circleci/python:3.9
  resource_class: large

**Comment by msbaines** [comment]
I believe this worked fine in v1.7.1 so I think this is a regression introduced in v1.8.0.

**Comment by msbaines** [comment]
I tried to workaround by switching to PROCESS_GROUP backend but my tests then fail with timeouts.

The same exact test runs fine when using a circleci machine where CUDA is available. In both cases, I am using CPU tensors.

**Comment by lw** [comment]
I see, if this is run on CircleCI then you probably have no control on how Docker is invoked. Note however that CircleCI gives you a Docker container for CPU jobs, but it gives you a full (virtual) machine for CUDA jobs.

My theory is that this is caused by the CMA channel, which fails to initialize under Docker in some cases. Could you try setting this flag in the `TensorPipeRpcBackendOptions`: `_channels=["mpt_uv", "basic", "cuda_ipc", "cuda_gdr", "cuda_xth", "cuda_basic"]`? (which is all our channels, except `cma`). If this works then it's probably the issue we're already aware of, and it should go away in v1.8.1.

**Comment by msbaines** [comment]
The workaround does not solve the issue. You should be able to reproduce with any cpu circleci worker using the following test code:

```
import tempfile
import torch.distributed.rpc as rpc

init_file = tempfile.mkstemp()[1]
options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file, _transports=["mpt_uv", "basic", "cuda_ipc", "cuda_gdr", "cuda_xth", "cuda_basic"])
rpc.init_rpc("worker0", rank=0, world_size=1, backend=rpc.BackendType.TENSORPIPE, rpc_backend_options=options)
```

I also tried using just `_transports=["basic"]`

**Comment by msbaines** [comment]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f8d56108535 in __GI_abort () at abort.c:79
#2  0x00007f8d5521f983 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f8d552258c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f8d552249d9 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f8d552252d5 in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f8d55189e33 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007f8d5518a6b5 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00007f8d546b1fa8 in tensorpipe::channel::ContextImplBoilerplate<tensorpipe::CpuBuffer, tensorpipe::channel::cma::ContextImpl, tensorpipe::channel::cma::ChannelImpl>::join() () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#9  0x00007f8d546ad36c in tensorpipe::channel::cma::Context::~Context() () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#10 0x00007f8d53edba16 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
   from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#11 0x00007f8d54629582 in torch::distributed::rpc::TensorPipeAgent::startImpl() ()
   from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#12 0x00007f8ce40d5a5d in torch::distributed::rpc::RpcAgent::start() () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#13 0x00007f8d545e48b5 in pybind11::cpp_function::initialize<torch::distributed::rpc::(anonymous namespace)::rpc_init(_object*, _object*)::{lambda(std::shared_ptr<torch::distributed::rpc::RpcAgent> const&)#13}, void, std::shared_ptr<torch::distributed::rpc::RpcAgent> const&, pybind11::name, pybind11::scope, pybind11::sibling, pybind11::call_guard<pybind11::gil_scoped_release> >(torch::distributed::rpc::(anonymous namespace)::rpc_init(_object*, _object*)::{lambda(std::shared_ptr<torch::distributed::rpc::RpcAgent> const&)#13}&&, void (*)(std::shared_ptr<torch::distributed::rpc::RpcAgent> const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, pybind11::call_guard<pybind11::gil_scoped_release> const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#14 0x00007f8d53eecacb in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) ()
   from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#15 0x00007f8d5660841d in cfunction_call (func=func@entry=0x7f8c0e49ab30, args=args@entry=0x7f8d55f150a0, kwargs=kwargs@entry=0x0)
    at Objects/methodobject.c:539
#16 0x00007f8d565da98d in _PyObject_MakeTpCall (tstate=0x563ec8bd2670, callable=0x7f8c0e49ab30, args=0x7f8c0db1db80, nargs=1, keywords=0x0)
    at Objects/call.c:191
#17 0x00007f8d566543c1 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x7f8c0db1db80, callable=0x7f8c0e49ab30,
    tstate=<optimized out>) at ./Include/cpython/abstract.h:116
#18 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x7f8c0db1db80, callable=0x7f8c0e49ab30, tstate=<optimized out>)
    at ./Include/cpython/abstract.h:103
#19 PyObject_Vectorcall (kwnames=0x0, nargsf=9223372036854775809, args=0x7f8c0db1db80, callable=0x7f8c0e49ab30) at ./Include/cpython/abstract.h:127
#20 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x563ec8bd2670) at Python/ceval.c:5072
#21 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3518
#22 0x00007f8d565db1b2 in _PyEval_EvalFrame (throwflag=0, f=0x7f8c0db1da00, tstate=0x563ec8bd2670) at ./Include/internal/pycore_ceval.h:40
#23 function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>, tstate=0x563ec8bd2670) at Objects/call.c:330
#24 _PyFunction_Vectorcall (func=<optimized out>, stack=0x563ecb52bf80, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:367
#25 0x00007f8d5665421e in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x563ecb52bf80, callable=0x7f8c0e4a8b80,
    tstate=0x563ec8bd2670) at ./Include/cpython/abstract.h:118
#26 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x563ecb52bf80, callable=<optimized out>) at ./Include/cpython/abstract.h:127
#27 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x563ec8bd2670) at Python/ceval.c:5072
#28 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3487
#29 0x00007f8d5664ef09 in _PyEval_EvalFrame (throwflag=0, f=0x563ecb52bdc0, tstate=0x563ec8bd2670) at ./Include/internal/pycore_ceval.h:40
#30 _PyEval_EvalCode (tstate=tstate@entry=0x563ec8bd2670, _co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0,
    args=args@entry=0x7f8d55f1bde8, argcount=argcount@entry=0, kwnames=0x7f8c10af4aa8, kwargs=0x7f8d55f1bde8, kwcount=<optimized out>, kwstep=1, defs=0x0,
    defcount=0, kwdefs=0x0, closure=0x0, name=0x7f8c0e4b3090, qualname=0x7f8c0e4b3090) at Python/ceval.c:4327
#31 0x00007f8d565db24c in _PyFunction_Vectorcall (func=<optimized out>, stack=0x7f8d55f1bde8, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/call.c:396
#32 0x00007f8d565dc259 in PyVectorcall_Call (callable=0x7f8c0e4b0c10, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:243
#33 0x00007f8d56651d27 in do_call_core (kwdict=0x7f8d55fe27c0, callargs=0x7f8d56075040, func=0x7f8c0e4b0c10, tstate=<optimized out>) at Python/ceval.c:5120
#34 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3580
#35 0x00007f8d5664ef09 in _PyEval_EvalFrame (throwflag=0, f=0x7f8c0e27d3c0, tstate=0x563ec8bd2670) at ./Include/internal/pycore_ceval.h:40
#36 _PyEval_EvalCode (tstate=tstate@entry=0x563ec8bd2670, _co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0,
    args=args@entry=0x7f8c0db299e8, argcount=argcount@entry=1, kwnames=0x7f8c0e4d1e18, kwargs=0x7f8c0db299f0, kwcount=<optimized out>, kwstep=1, defs=0x0,
    defcount=0, kwdefs=0x0, closure=0x0, name=0x7f8c0e491830, qualname=0x7f8c0e491830) at Python/ceval.c:4327

**Comment by msbaines** [comment]
Looks like it is related to CMA but the workarounds are not avoiding the code path.

**Comment by msbaines** [comment]
CMA Context is created here:

```
#0  0x00007f9e86052fe0 in tensorpipe::channel::cma::Context::Context()@plt ()
   from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#1  0x00007f9e8696a1bc in tensorpipe::channel::cma::create() () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#2  0x00007f9e868f6e03 in torch::distributed::rpc::(anonymous namespace)::makeCmaChannel() ()
   from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#3  0x00007f9e86903b96 in std::_Function_handler<std::unique_ptr<torch::distributed::rpc::CpuChannelRegistration, std::default_delete<torch::distributed::rpc::CpuChannelRegistration> > (), std::unique_ptr<torch::distributed::rpc::CpuChannelRegistration, std::default_delete<torch::distributed::rpc::CpuChannelRegistration> > (*)()>::_M_invoke(std::_Any_data const&) () from /home/circleci/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so
#4  0x00007f9e868fe557 in torch::distributed::rpc::TensorPipeAgent::startImpl() ()
```

**Comment by msbaines** [comment]
I was applying the workaround incorrectly. I was setting _transports instead of _channels. After using the workaround correctly I was able to avoid the crash.
