### ISSUE TITLE
librosa.cqt for torchaudio

### ISSUE THREAD

**Issue by ktatar** [pytorch/pytorch#54289]
## 🚀 Feature

torchaudio.transforms.CQT ported from librosa.cqt

## Motivation

CQT has been found beneficial to audio synthesis applications. In some cases, CQT outperforms other audio features. It would be beneficial for audio researchers to have a torchaudio.transforms.CQT function in torchaudio library.

## Additional context

refs:

Esling P, Chemla-Romeu-Santos A, Bitton A (2018) Generative timbre spaces: regularizing variational auto-encoders with perceptual metrics. arXiv:1805.08501 [cs, eess]. http://arxiv.org/abs/1805.08501. ArXiv: 1805.08501

Tatar, K., Bisig, D., & Pasquier, P. (2020). Latent Timbre Synthesis. Neural Computing and Applications. https://doi.org/10.1007/s00521-020-05424-2

**Comment by ejguan** [comment]
Hey @ktatar,
It seems a torchaudio-specific feature request. It should be submitted in the Repo of [torchaudio](https://github.com/pytorch/audio).

Hi @mthrok, Can you check on this? I think it can also be transferred to torchaudio.

**Comment by ktatar** [comment]
Thank you! I added the feature request to torchaudio repo.
