### ISSUE TITLE
Port complex-related ops from method_tests() to OpInfos

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54298]
See the more general porting tracker https://github.com/pytorch/pytorch/issues/54261 for more details.

This specialized issue tracks the porting of real, imag, view_as_real, view_as_complex and complex.

cc @ezyang @anjali411 @dylanbespalko @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
@anjali411 this is fixed by https://github.com/pytorch/pytorch/pull/56524, right?

**Comment by anjali411** [comment]
> @anjali411 this is fixed by #56524, right?

yeah
