### ISSUE TITLE
Port pow and float_power method_tests entries to OpInfos

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54295]
Part of the more general tracking issue https://github.com/pytorch/pytorch/issues/54261.

cc @mruberry @VitalyFedyunin @walterddr

**Comment by imaginary-person** [comment]
Trying to add the `OpInfo` for `pow` via #50999.

**Comment by krshrimali** [comment]
Hi, I would like to pick this up. Hoping that it doesn't coincide with anyone's plan, and if it does - please let me know. Thanks!
