### ISSUE TITLE
Port the binary comparison ops from method_tests() to OpInfos

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54300]
See the larger OpInfo tracking issue #54261 for more details. These operations are: eg, ne, lt, gt, le, ge. 

cc @mruberry @VitalyFedyunin @walterddr

**Comment by prokotg** [comment]
Working on  `eq` and `ne` for starters.  Hopefully I will port the rest once I'm finished with these.

**Comment by mruberry** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/55709
