### ISSUE TITLE
Port the indexing ops from method_tests() to OpInfos

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54301]
See the larger OpInfo tracking issue #54261 for more details.

These ops are: index_add, index_copy and index_fill.

Updates: index_add, index_copy, and index_fill have OpInfos now, although index_fill still has method_tests() entries that should be captured in its sample inputs.

@Lezcano I think you're already doing at least one of these?

cc @mruberry @VitalyFedyunin @walterddr

**Comment by Lezcano** [comment]
Yeah, I'm covering `index_copy` in https://github.com/pytorch/pytorch/pull/52203
I think that `index_fill` was also done in https://github.com/pytorch/pytorch/pull/50578/files#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R623

**Comment by kurtamohler** [comment]
Related: `index`/`__getitem__` and `index_put` don't have OpInfos either. I'll be adding them as part of #53605

**Comment by Lezcano** [comment]
For what is worth, `index_add`  `OpInfo` methods were added in https://github.com/pytorch/pytorch/pull/53898
I believe that all the ops listed in the OP already have an `OpInfo` test.
The only thing I see is that the old `index_fill`  tests were not deleted when the PR was done.

**Comment by mruberry** [comment]
Thanks @Lezcano. Looks like the last thing to do that this issue originally tracked is ensure the method_tests() entries for index_fill are represented in its sample inputs and then removed:

https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/testing/_internal/common_methods_invocations.py#L4200

**Comment by mruberry** [comment]
@kshitij12345 fixed the final sub-issue on this roll-up issue. Thanks all!
