### ISSUE TITLE
Port lerp method_tests() to OpInfos

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#54304]
See the larger OpInfo tracking issue #54261 for more details. This issue just tracks the porting of torch.lerp().

cc @mruberry @VitalyFedyunin @walterddr

**Comment by kshitij12345** [comment]
OpInfo for `torch.lerp` was added in https://github.com/pytorch/pytorch/pull/53689

However there are still a few entries in `method_tests` which correspond to `self` being broadcasted (blocked on https://github.com/pytorch/pytorch/issues/50747)
