### ISSUE TITLE
nn.linear cpu and cuda result mismatch

### ISSUE THREAD

**Issue by JF-D** [pytorch/pytorch#54308]
## To Reproduce

I need to compare the corresponding model forward result of a tensor slice and original tensor, but I discover the result is not match when tested by `torch.allclose`, and further, I discover the cpu and cuda result is not match, either.
According to the result, I find the relative error is very high, but the absolute error is less (~ 1e-6) when using `x = torch.randn(32, 1024, 1000)`, but absolute error goes up to 5e-4 when using `x = torch.randn(32, 1024, 1000) + 100`. While, this large errors are conducted by the small values in the tensor, and I don't know this is a normal behavior or something else.

```
import numpy as np
import torch

x = torch.randn(32, 1024, 1000)
model = torch.nn.Linear(1000, 1010)

x = x.cpu()
model.cpu()
y_cpu = model(x)

x = x.cuda()
model.cuda()
y_gpu = model(x)
print("cpu vs cuda: ", torch.allclose(y_cpu, y_gpu.cpu()))
print("cpu vs cuda: ",
      np.max(np.abs(y_cpu.detach().cpu().numpy() - y_gpu.detach().cpu().numpy())))

x_slice = x[0:16]
x_slice = x_slice.cuda()
model.cuda()
y_gpu_slice = model(x_slice)

x_slice = x_slice.cpu()
model.cpu()
y_cpu_slice = model(x_slice)

print("cpu slice vs gpu slice: ", torch.allclose(y_cpu_slice, y_gpu_slice.cpu()))
print("cpu slice vs gpu: ", torch.allclose(y_cpu_slice, y_gpu[0:16].cpu()))
print("cpu vs gpu slice: ", torch.allclose(y_cpu[0:16], y_gpu_slice.cpu()))
```

## Expected behavior

The result should be equal, but I find they are not.
using `x = torch.randn(32, 1024, 1000)`
![image](https://user-images.githubusercontent.com/30710061/111745229-45738480-88c7-11eb-9232-0f1bdbb3c712.png)

using `x = torch.randn(32, 1024, 1000) + 100`
![image](https://user-images.githubusercontent.com/30710061/111745254-4b696580-88c7-11eb-84ad-6e97373eb7a4.png)

## Environment
 - PyTorch Version (e.g., 1.0): 1.5  (I tried several different versions)
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.6
 - CUDA/cuDNN version: cuda10.1-cudnn7.6
 - GPU models and configuration: linear layer

**Comment by xwang233** [comment]
Floating point arithmetic doesn't follow associative rule, so the matrix multiplication results could be different on different devices. 

<details>
<summary> code </summary>
<p>

```python
import numpy as np
import torch


def test(x):
    model = torch.nn.Linear(1000, 1010)

    x = x.cpu()
    model.cpu()
    y_cpu = model(x)

    x = x.cuda()
    model.cuda()
    y_gpu = model(x)
    print("cpu vs cuda: ", torch.allclose(y_cpu, y_gpu.cpu()))
    print("cpu vs cuda: ",
          np.max(np.abs(y_cpu.detach().cpu().numpy() - y_gpu.detach().cpu().numpy())))

    a, b = torch.testing._compare_tensors_internal(
            y_cpu, y_gpu.cpu(), rtol=0, atol=0, equal_nan=False)
    if not a:
        print(b)

x = torch.randn(32, 1024, 1000)
test(x)
x = torch.randn(32, 1024, 1000) + 100
test(x)
```

</p>
</details>

prints

```
cpu vs cuda:  False
cpu vs cuda:  5.4836273e-06
With rtol=0 and atol=0, found 31336874 element(s) (out of 33095680) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 5.4836273193359375e-06 (-1.4855296611785889 vs. -1.4855241775512695), which occurred at index (29, 934, 652).
cpu vs cuda:  False
cpu vs cuda:  0.0005264282
With rtol=0 and atol=0, found 31427123 element(s) (out of 33095680) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.00052642822265625 (-112.48482513427734 vs. -112.48429870605469), which occurred at index (29, 255, 830).
```

Because the average value of your input increased, the average value of output also increased, so the max absolute error also increased. If you calculate the max relative error, you can see that they are still similar, about 1e-6 for this matrix size.

Probably not a bug.

**Comment by JF-D** [comment]
Thanks for your reply. @xwang233 
I have another two question.
1. you compare both the relative error and absolute error to determine whether the two outputs are equal. In practice, how can we know if we want to know two tensors are equal or not? Is there an API, or, we should calculate and compare both the relative error and absolute error?
2. you mention that 
> Floating point arithmetic doesn't follow associative rule, so the matrix multiplication results could be different on different devices.

But on the same device, for example, cuda, when comparing  between `y_gpu[0:16]` and `y_gpu_slice`, the result is the same with when comparing between cpu and cuda. Although we can roughly think that these two tensors are equal, I want to know the cause of the error between them, because I think there should be no error between them.
```
y_gpu = model(x)
y_gpu_slice = model(x[0:16])
```

Thanks a lot!

**Comment by JF-D** [comment]
@zou3519 @xwang233 Thanks a lot! It's indeed floating-point error. My problem is mainly caused by not knowing how to compare floating point numbers. I found the answer from here.
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
