### ISSUE TITLE
RuntimeError: _update_worker_pids should be called only once for each DataLoader

### ISSUE THREAD

**Issue by SRTjiawei** [pytorch/pytorch#5430]
Environment:
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 9.1
- GPU models and configuration: Nvidia GTX 1080
- GCC version (if compiling from source): 4.8.5

- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
Since it's dataset related, I can provide the code that loads the data directory.
![image](https://user-images.githubusercontent.com/17583521/36718893-5a41c420-1bde-11e8-9281-518c0a3ad090.png)

- Error messages and/or stack traces of the bug
![image](https://user-images.githubusercontent.com/17583521/36718842-261a9f6e-1bde-11e8-9d93-ab270e0e6967.png)

- Context around what you are trying to do
I'm trying to train a image classifier with the official densenet201 model, the dataloader caused this error is the train data loader. It occurs randomly at different epoch of the training process, which is weird.

anyone has ideas how to solve it? please help, thanks!

**Comment by apaszke** [comment]
cc: @SsnL

**Comment by apaszke** [comment]
This looks like a bug in PyTorch, it's not your fault.

**Comment by SsnL** [comment]
That seems weird. I will try to reproduce it.

**Comment by SRTjiawei** [comment]
@apaszke thanks for your reply, looking forward to a bug fix then.

**Comment by SRTjiawei** [comment]
@SsnL Cheers! I simply used it for loading image data with torchvision.datasets.ImageFolder, it should be easy to reproduce.

**Comment by apaszke** [comment]
@SsnL my guess would be that we're not cleaning up after dead data loaders properly, and because `id(self)` is just the memory pointer to the `PyObject` of `self`, then another loader can accidentally get allocated in the same place. No idea what can cause it otherwise (except for `__init__` being called twice, but that's unlikely)

**Comment by SsnL** [comment]
@apaszke Yeah, that sounds a possible cause. 

@SRTjiawei Are there any other error messages before this one? Perhaps in `DataLoaderIter.__del__`?

**Comment by SRTjiawei** [comment]
@SsnL nope, this is all of it. I think @apaszke is probably right, id(self) is pointing to the same object.

**Comment by SsnL** [comment]
@SRTjiawei Are you looking at the `id` of iterator? 

I've been running a similar script that loads imagenet all day and still can't reproduce it. There is very likely something else is going on other than running dataloder with imagefolder (if dataloder is this broken whenever used with imagefolder, we would see plenty of bug reports already haha). If possible, could you post the full script so I can try again?

**Comment by SRTjiawei** [comment]
@SsnL yes, id of iterator,  this error is raised from the C code, right? But I tried printing out the id of iter, it's not the same. Surprisingly, this time there is no error, still running well, only added one line of code to print. So, maybe it is about multiprocessing?

Sure, I will paste my full script for training. Note that I used a customized dataloader for eval, but it is not this customized one that caused the error.

```
# encoding: utf-8

import time
import numpy as np
import torch.nn as nn
import torch.utils.data
import torch.utils.data.distributed
import torchvision.datasets as datasets
import torchvision.models as models
import torchvision.transforms as transforms
from torch.autograd import Variable
from tensorboardX import SummaryWriter
from utils import *


normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

logdir = './logs/exp5-densenet201'
writer = SummaryWriter(log_dir=logdir)
print('training log is writing to: ', logdir)
train_data = datasets.ImageFolder('./plants/train/',
                                  transform=transforms.Compose([
                                      transforms.RandomResizedCrop(224, scale=(0.8, 1.2)),
                                      transforms.RandomHorizontalFlip(),
                                      transforms.RandomRotation(90),
                                      transforms.RandomVerticalFlip(),
                                      # transforms.ColorJitter(brightness=0.5),
                                      transforms.ToTensor(),
                                      normalize])
                                  )

eval_data = datasets.ImageFolder('./plants/eval/',
                                 transform=transforms.Compose([
                                     transforms.RandomResizedCrop(224, scale=(0.8, 1.2)),
                                     transforms.ToTensor(),
                                     normalize])
                                 )

train_loader = torch.utils.data.DataLoader(train_data,
                                           batch_size=10,
                                           shuffle=True,
                                           num_workers=4)

eval_loader = CustomDataLoader(eval_data,
                               batch_size=10,
                               shuffle=False,
                               num_workers=4)

print('Num of images in the dataset: ' + \
      'train {}, eval {}'.format(len(train_loader.dataset.imgs),
                                 len(eval_loader.dataset.imgs)))

class_names = train_data.classes
print('Label info: ')
for key, val in train_data.class_to_idx.items():
    print(key, val)

print('=' * 50)
print('train batches: ', len(train_loader))
print('test batches: ', len(eval_loader))

# Load pretrained model.
model = models.densenet201(pretrained=True)
# model = models.resnet34(pretrained=True)
# model.avgpool = torch.nn.AdaptiveAvgPool2d(1)

# Setup optimizer and loss function
model_path = './models/densenet201_newdata_params.pkl'
# model_path = '/output/model/latest_params.pkl'
epochs = 600
eval_freq = 1
print_freq = 10
total_steps = 0
lr = 0.001
hidden_dim = 800
continue_train = False
best_test_acc = 0

# If you want to finetune only top layer of the model.
# for param in model.parameters():
#     param.requires_grad = False

# Replace top layer for finetuning.
# model.fc = torch.nn.Linear(model.fc.in_features, len(class_names))
model.classifier = nn.Linear(model.classifier.in_features, len(class_names))
# model.classifier = nn.Sequential(nn.Linear(model.classifier.in_features, hidden_dim),
#                                 nn.ReLU(),
#                                 nn.Linear(hidden_dim, len(class_names))
#                                 )

loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr, momentum=0.9, nesterov=True)
# scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1000, gamma=0.1)

if torch.cuda.is_available():
    model.cuda()

if continue_train:
    model.load_state_dict(torch.load(model_path))
    print('loaded saved model params from: ', model_path)


# Training and testing
for epoch in range(epochs):
    writer.add_text('Epoch: ', str(epoch + 1))
    iteration = 0
    start = time.time()
    bloss = 0
    model.train()  # train mode
    for batch, labels in train_loader:
        iteration += 1
        total_steps += 1
        images = Variable(batch)
        targets = Variable(labels)
        if torch.cuda.is_available():
            images = images.cuda()
            targets = targets.cuda()
        outputs = model(images)
        loss = loss_fn(outputs, targets)
        bloss += loss
        # backprop
        # scheduler.step()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # print loss
        if total_steps % print_freq == 0:
            print('Epoch: {0}, Iter: {1}, Loss: {2:8.6f}, {3:6.5f} sec/batch'.format(
                epoch, iteration, bloss.data[0] / print_freq, (time.time() - start) / print_freq))
            start = time.time()
            bloss = 0

    # Test the Model
    if (epoch + 1) % eval_freq == 0:
        model.eval()  # Change model to 'eval' mode (BN uses moving mean/var).
        correct = 0
        total = 0
        for inputs, labels in eval_loader:
            ncorps = 5
            predicts = []
            # iterator = eval_loader.iter
            for i in range(ncorps):
                images = eval_loader.get_cur_batch()
                images = Variable(images)
                if torch.cuda.is_available():
                    images = images.cuda()
                    labels = labels.cuda()
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                predicts.append(predicted)
            eval_loader.iter.reset_indices()
            predicts = torch.stack(predicts, dim=1)
            predicted = most_common(predicts)
            total += labels.size(0)
            correct += (predicted == labels).sum()
        print('Correct pred: ', correct)
        test_acc = 100 * correct / total
        print('Test Accuracy of the model on test images: %d%%' % test_acc)
        writer.add_scalar('eval_acc', test_acc, total_steps)
        # Save the Trained Model
        if test_acc > best_test_acc:
            best_test_acc = test_acc
            print('Saving best model params to {}'.format(model_path))
            torch.save(model.state_dict(), model_path)

writer.close()
```

**Comment by SRTjiawei** [comment]
Sometimes it occurs at epoch 2, sometimes it is after epoch 10, randomly. Last time I almost think it's gone, but then occurs again, could it be hardware related? like limited memory?

**Comment by SRTjiawei** [comment]
@SsnL sorry for the late response, I modified the dataloader source code in site-packages, which is allocated in conda envs folder, since I installed it with conda.
[conda]/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py
![image](https://user-images.githubusercontent.com/17583521/36880698-1126a5d4-1e05-11e8-94d7-03f0dba37975.png)

**Comment by SsnL** [comment]
It’s excellent you did that. Could you also print id(self) in
_shutdown_workers before the _remove_worker_pids calls? Sorry for asking
you to do this. I can’t really reproduce on my side...

**Comment by SRTjiawei** [comment]
@SsnL Thanks for your response! yeah I will try it, sorry for the late reply.

**Comment by SRTjiawei** [comment]
@SsnL I tried to print id(self) in _shutdown_workers, then I found my customized eval dataloader does not shutdown properly, so that at next training epoch the train dataloader will get the same object used in previous epoch for evaluation. The id printed right before "Correct pred: 189" is the id of eval dataloader, which does not shutdown. 
![image](https://user-images.githubusercontent.com/17583521/36955693-ed64aaf8-2064-11e8-95d2-a4efe9853f4a.png)

My customized dataloader is as follow, the reason for this is I want to use current batch multiple times with different transforms at test time, so I made current indices an attribute, and in each iteration of eval loader, I manually reset the indices. For now, I can't figure out why this makes it not shutting down.
```
class CustomDataLoaderIter(DataLoaderIter):
    def __init__(self, loader):
        super(CustomDataLoaderIter, self).__init__(loader)
        self.num_workers = 0
        self.indices = None

    def __next__(self):
        if self.num_workers == 0:  # same-process loading
            if self.indices is None:
                self.indices = next(self.sample_iter)  # may raise StopIteration
            batch = self.collate_fn([self.dataset[i] for i in self.indices])
            if self.pin_memory:
                batch = pin_memory_batch(batch)

            return batch

        # check if the next sample has already been generated
        if self.rcvd_idx in self.reorder_dict:
            batch = self.reorder_dict.pop(self.rcvd_idx)
            return self._process_next_batch(batch)

        if self.batches_outstanding == 0:
            self._shutdown_workers()
            raise StopIteration

        while True:
            assert (not self.shutdown and self.batches_outstanding > 0)
            idx, batch = self.data_queue.get()
            self.batches_outstanding -= 1
            if idx != self.rcvd_idx:
                # store out-of-order samples
                self.reorder_dict[idx] = batch
                continue
            return self._process_next_batch(batch)

    def cur_batch(self):
        return self.__next__()

    def reset_indices(self):
        self.indices = None
```

In evaluation:
```
for inputs, labels in eval_loader:
            ncorps = 5
            predicts = []
            # iterator = eval_loader.iter
            for i in range(ncorps):
                images = eval_loader.get_cur_batch()
                images = Variable(images)
                if torch.cuda.is_available():
                    images = images.cuda()
                    labels = labels.cuda()
                outputs = model(images)
                _, predicted = torch.max(outputs.data, 1)
                predicts.append(predicted)
            eval_loader.iter.reset_indices()   # reset indices to move on
            predicts = torch.stack(predicts, dim=1)
            predicted = most_common(predicts)
            total += labels.size(0)
            correct += (predicted == labels).sum()
```

**Comment by SsnL** [comment]
Okay, the problem is that 
1. worker processes are initialized at `super(CustomDataLoaderIter, self).__init__(loader)`, so are the bookkeeping data structure in c++ side.
2. then you set `self.num_workers = 0`.
3. so in `__del__` (https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L339-L342), when it checks `self.num_workers != 0` before removing the bookkeeping c++ data structure.

There are a couple of issues with your approach:
1. `DataLoaderIter` isn't meant to be subclassed. 
2. this doesn't give you the same current batch when called, but rather advances the iterator before returned the batch:
```
    def cur_batch(self):
        return self.__next__()
```
3. you can achieve what you want by just applying the different crops/transformations to `input` in `for inputs, labels in eval_loader:` block.

**Comment by SsnL** [comment]
@apaszke Should we rename `DataLoaderIter` to `_DataLoaderIter` to discourage subclassing?

**Comment by apaszke** [comment]
@SsnL yea, let's do it

**Comment by SRTjiawei** [comment]
@SsnL I see, thanks very much! I actually tried applying transformations (in torchvision.transforms module), but I failed to realize that a Tensor can be convert back to PIL image and then apply those transforms at that time, so I tried to subclass the dataloader iter.  Anyway, thank you guys for your time! @apaszke 👍
