### ISSUE TITLE
c++ libtorch and pytorch use same pt model get different result

### ISSUE THREAD

**Issue by dencesun** [pytorch/pytorch#54313]
## ❓ Questions and Help

when i load the same model with pythor and c++, i get the different value,  the python version same input get same output, but c++ libtorch same input get different output. why?

this is python code and result
```python
import torch


def run_model():
    model = torch.jit.load("./lst.pt", map_location=torch.device('cpu'))
    example = torch.ones(2, 11, 8)

    # print(example)

    model.eval()
    print(model(example))
    print(model.forward(example))


if __name__ == '__main__':
    run_model()
```
here is python run result
```bash
tensor([[0.7535]], grad_fn=<AddBackward0>)
tensor([[0.7535]], grad_fn=<DifferentiableGraphBackward>)

````

this is c++ code and result 

``` c++
#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char *argv[]) {
    if (argc != 2) {
        std::cerr << "usage: example-app <path-to-exported-script-module>\n";
        return -1;
    }


    torch::jit::script::Module module;
    try {
        module = torch::jit::load(argv[1]);
    }
    catch (const c10::Error &e) {
        std::cerr << "error loading the model\n";
        return -1;
    }
    
    std::vector<torch::jit::IValue> inputs;
    at::Tensor input = torch::ones({1, 11, 8});
    inputs.push_back(input);

    at::Tensor output = module.forward(inputs).toTensor();
    std::cout << output << '\n';
}
```

this is c++ run result
```bash
kwepwebenv02448:/home/example-app/build # ./example-app ../lst.pt 

-1.1254e+35
[ CPUFloatType{1,1} ]

kwepwebenv02448:/home/example-app/build # ./example-app ../lst.pt 
 24.0280
[ CPUFloatType{1,1} ]

kwepwebenv02448:/home/example-app/build # ./example-app ../lst.pt 
-1.3217e+30
[ CPUFloatType{1,1} ]

kwepwebenv02448:/home/example-app/build # ./example-app ../lst.pt 
 0.4786
[ CPUFloatType{1,1} ]
kwepwebenv02448:/home/example-app/build # ./example-app ../lst.pt 
-1.8683e+29
[ CPUFloatType{1,1} ]
```

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
It is hard to reproduce this problem without the model. Can you share your model file (`lst.pt`)? I also noticed that your Python input is `example = torch.ones(2, 11, 8)` but your C++ input is `at::Tensor input = torch::ones({1, 11, 8})`. You should try using the same size tensor for both tests to make sure the input is exactly the same.
`

**Comment by dencesun** [comment]
> It is hard to reproduce this problem without the model. Can you share your model file (`lst.pt`)? I also noticed that your Python input is `example = torch.ones(2, 11, 8)` but your C++ input is `at::Tensor input = torch::ones({1, 11, 8})`. You should try using the same size tensor for both tests to make sure the input is exactly the same.


i have tried same size tensor for both test, the result is also wrong

**Comment by SplitInfinity** [comment]
Can you provide your model (`lst.pt`) so that we can reproduce this and debug?

**Comment by dencesun** [comment]
> Can you provide your model (`lst.pt`) so that we can reproduce this and debug? Can you also check if your results are consistent from run to run? That is, could there be something non-deterministic in your model?

thanks very  much, because of the company's confidentiality policy, we cannot upload our model, but we tested the simplest ltsm model, which can reproduce the above problems.

**Comment by SplitInfinity** [comment]
Can you provide any model that can reproduce this issue? It doesn't have to be your confidential one

**Comment by dencesun** [comment]
> Can you provide any model that can reproduce this issue? It doesn't have to be your confidential one


here is sample of lstm, input is torch::ones(1, 11, 1)
[lstnet_sample.zip](https://github.com/pytorch/pytorch/files/6193791/lstnet_sample.zip)

**Comment by dencesun** [comment]
> > Can you provide any model that can reproduce this issue? It doesn't have to be your confidential one
> 
> here is sample of lstm, input is torch::ones(1, 11, 1)
> [lstnet_sample.zip](https://github.com/pytorch/pytorch/files/6193791/lstnet_sample.zip)

here is c++ result by arm cpu

`
kwepwebenv02448:/home/example-app/build # ./example-app ../lstnet_tiny_checkpoint.pt 

 0.6411
[ CPUFloatType{1,1} ]
 0.6411
[ CPUFloatType{1,1} ]
0.641054
kwepwebenv02448:/home/example-app/build # ./example-app ../lstnet_tiny_checkpoint.pt 
-8.1887e+23
[ CPUFloatType{1,1} ]
-8.1887e+23
[ CPUFloatType{1,1} ]
-8.18873e+23

`

**Comment by dencesun** [comment]
this problem seems has resolved, when i use libtorch1.6 source compile by arm cpu, the reuslt becomes right, but use libtorch1.7, the result was wrong.
