### ISSUE TITLE
Docs Error: Incorrect Output of torch.gels() Example

### ISSUE THREAD

**Issue by ZhiqingXiao** [pytorch/pytorch#5431]
(edited according to @SsnL  's comment) **Output of torch.gels() example is incorrect.**

I try to reprise the example in http://pytorch.org/docs/0.3.1/torch.html#torch.gels, which uses a 5x2 Tensor and a 5x3 Tensor to generate a 3x2 Tensor. However, my running generates a 5x2 Tensor. The output of example is incorrect.

- OS: Windows 10 x64
- PyTorch version: 0.3.0b0+591e73e
- How you installed PyTorch (conda, pip, source): conda install -c peterjc123 pytorch
- Python version: 3.6.0
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): N/A

- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
```
import torch
A = torch.Tensor([[1, 1, 1],
                  [2, 3, 4],
                  [3, 5, 2],
                  [4, 2, 5],
                  [5, 4, 3]])
B = torch.Tensor([[-10, -3],
                  [ 12, 14],
                  [ 14, 12],
                  [ 16, 16],
                  [ 18, 16]])
X, _ = torch.gels(B, A)
X
```

- Error messages and/or stack traces of the bug
![image](https://user-images.githubusercontent.com/12758455/36729013-baa02982-1bfd-11e8-991e-bfa144e88290.png)

**Comment by SsnL** [comment]
I believe that the example in doc needs to be updated. The doc says 

> The first n rows of the returned matrix X contains the solution. The remaining rows contain residual information: the euclidean norm of each column starting at row n is the residual for the corresponding column.

**Comment by ZhiqingXiao** [comment]
@SsnL Thank you for your helpful information! That really helps. I will edit the my original post accordingly.

**Comment by zou3519** [comment]
Fixed by #5443

**Comment by D-X-Y** [comment]
It seems the doc of `torch.gels` still has a error: in https://pytorch.org/docs/master/torch.html?highlight=gels#torch.gels the size of matrix B should be `m×k` rather than `n×k`.

**Comment by soumith** [comment]
reopening based on @D-X-Y 's comment.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/11699 (merging shortly)
