### ISSUE TITLE
Loading/saving file using different devices

### ISSUE THREAD

**Issue by pl992** [pytorch/pytorch#54311]
## 📚 Documentation

In this page [https://pytorch.org/docs/stable/generated/torch.save.html#torch.save](url) there is a note:
```
PyTorch preserves storage sharing across serialization. See preserve-storage-sharing for more details
```
I would expect at `preserve-storage-sharing` or looking at it in the search engine of pytorch finding something but I can find nothing. The point is that it is not clear whether I could save a model and then load it in a different device, and if it is possible how I could do that

cc @brianjo @mruberry

**Comment by zou3519** [comment]
That should link here: https://pytorch.org/docs/stable/notes/serialization.html#id3

**Comment by mruberry** [comment]
We would accept a PR fixing this.
