### ISSUE TITLE
fastSpecializedAtomicAdd does not seem to work for booleans

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#54317]
The tests of `put_` with `accumulate=True` in the PR https://github.com/pytorch/pytorch/pull/53356
https://github.com/pytorch/pytorch/blob/6a651b1116912e1e6a11b89e1e7bc43a853783e6/test/test_torch.py#L4602-L4611
show a failure for booleans and only booleans. It is implemented with `fastSpecializedAtomicAdd`, as seen in
https://github.com/pytorch/pytorch/blob/6a651b1116912e1e6a11b89e1e7bc43a853783e6/aten/src/ATen/native/cuda/IndexKernel.cu#L282-L285

This means that the behaviour of `fastSpecializedAtomicAdd` and the usual addition in Python diverge on booleans.

I do not know enough CUDA to really understand what's going on. Is this expected behaviour?
cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel

**Comment by zou3519** [comment]
Marking as triage review because I don't know if this qualifies as a "silent correctness issue" -- what happens when one adds two booleans?

**Comment by Lezcano** [comment]
Now that I re-read the issue, I think I may have written this wrong. This is not happening in `master`, but in a PR that's under review
https://github.com/pytorch/pytorch/pull/53356 
Currently, `put_` and `take`  do not support boolean tensors. I'll edit the op

**Comment by ngimel** [comment]
Our bool atomic add is neither atomic nor add https://github.com/pytorch/pytorch/blob/61b074581ce1ccf0fb1bf4f1b73f4b99f93fa70c/aten/src/THC/THCAtomics.cuh#L180-L182. 
@zou3519 when one adds to bool tensors, the behavior is `or`, and that's probably what should be happening here. 
But, alternatively, we could just delete that faulty implementation and disable all ops that require it.

**Comment by zou3519** [comment]
At triage review meeting, we decided it is better for this to be fixed

**Comment by ysiraichi** [comment]
@zou3519 do you mean that it should be replaced by `or`, or should the implementation for `bool` be deleted?
