### ISSUE TITLE
[docs] Improve existing documentation

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#5432]
There are some minor typographical errors in the documentation page for math operations. http://pytorch.org/docs/master/torch.html#math-operations

I have listed them down below (tentative list):
+ Add formulae for `erf` and `erfinv`
+ Maintain consistent doc for `exp` and `expm1` (like `log` and `log1p`)
+ Modify mathematical symbols in `ge`, `le`, `ne`.
+ Math display fixes for `addbmm`, `geqrf`, `gesv`, `orgqr`, `ormqr`, ...

I could issue a PR with some changes. Please let me know if this is fine.

**Comment by apaszke** [comment]
Yes, please send the PR!

**Comment by vishwakftw** [comment]
Great, thanks. I will send in some time. I have also realized that there are some problems in other places as well, I think I could add that too here.

**Comment by SsnL** [comment]
I'm also preparing a PR that touches the doc. It will mainly be about the example section, but will also change `gels` quite a bit. I'll avoid touching the items you listed above :)

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/5450/
