### ISSUE TITLE
[NNC] Implement Buffer Contraction

### ISSUE THREAD

**Issue by navahgar** [pytorch/pytorch#54338]
Contract the buffer sizes when only a part of the buffer is used.

For example:
```
for i in 0..100:
   for j in 0..200:
     A[i,j] = sin(i*j)
   for j in 0..199:
     B[i,j] = A[i,j] + A[i, j+1]
```
In this case, the dimensions of buffer `A` is [100, 200]. But the usage of `A` in the code above shows that it is independent of the first dimension `i`. So, we can replace it with a buffer with dimension [1, 200] or [200]. 

The optimized code will look like:
```
for i in 0..100:
   for j in 0..200:
     A[j] = sin(i*j)
   for j in 0..199:
     B[i,j] = A[j] + A[j+1]
```

**Comment by yashwant121** [comment]
Very Intuitive
