### ISSUE TITLE
RuntimeError: We don't have an op for metal_prepack::conv2d_prepack but it isn't a special case.

### ISSUE THREAD

**Issue by HashedViking** [pytorch/pytorch#54377]
## 🐛 Bug

Hello, recently I tackled with [(PROTOTYPE) USE IOS GPU IN PYTORCH](https://pytorch.org/tutorials/prototype/ios_gpu_workflow.html#prototype-use-ios-gpu-in-pytorch)
After ages of making custom-compiled **torch** work I've got some vague error:
```
Traceback (most recent call last):
  File "/test.py", line 7, in <module>
    optimized_model = optimize_for_mobile(scripted_model, backend='metal')
  File "/opt/anaconda3/envs/fom/lib/python3.8/site-packages/torch/utils/mobile_optimizer.py", line 69, in optimize_for_mobile
    optimized_cpp_module = torch._C._jit_pass_metal_optimize_for_mobile(script_module._c, preserved_methods_str)
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for metal_prepack::conv2d_prepack but it isn't a special case.  Argument types: Tensor, Tensor?, int[], int[], int[], int, None, None, 
```

## To Reproduce

1. Compile torch from sources using `USE_PYTORCH_METAL=ON python setup.py install` 
2. Run the example script
3. Cry in agony

Also I modified `MetalCommandBuffer.h` to bypass [compilation error](https://github.com/pytorch/pytorch/commit/36dc5d3b3aaa81280ad290d4b85d4dd033c5c911#r48460115)
## Expected behavior

Print some output and save the metal-optimized model.

## Environment

PyTorch version: 1.9.0a0+gite442d5c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.2 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.7

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.9.0a0+gite442d5c
[pip3] torchvision==0.9.0
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] torch                     1.9.0a0+gite442d5c          pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi

## Example script from tutorial

```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torchvision.models.mobilenet_v2(pretrained=True)
scripted_model = torch.jit.script(model)
optimized_model = optimize_for_mobile(scripted_model, backend='metal') # <<< error here
print(torch.jit.export_opnames(optimized_model))
torch.jit.save(optimized_model, './mobilenetv2_metal.pt')
```

If someone has working recipe for launching PyTorch model on Metal, please, share.

**Comment by HashedViking** [comment]
Well I found workaround for this:

First - you have to save the model **without** metal backend and **without** `optimize_for_mobile`
```
model = torchvision.models.mobilenet_v2(pretrained=True)
scripted_model = torch.jit.script(model)
torch.jit.save(scripted_model, './mobilenetv2.pt')
```
Then load from that script file and save with metal optimization:
```
model = torch.jit.load('mobilenetv2.pt')
optimized_model = optimize_for_mobile(model, backend="metal")
print(torch.jit.export_opnames(optimized_model))
torch.jit.save(optimized_model, './mobilenetv2_metal.pt')
```

Then I encountered some issues on device, but that's a story for another _issue_.

**Comment by xperzy** [comment]
> Well I found a workaround for this:
> 
> First - you have to save the model **without** metal backend and **without** `optimize_for_mobile`
> 
> ```
> model = torchvision.models.mobilenet_v2(pretrained=True)
> scripted_model = torch.jit.script(model)
> torch.jit.save(scripted_model, './mobilenetv2.pt')
> ```
> 
> Then load from that script file and save with metal optimization:
> 
> ```
> model = torch.jit.load('mobilenetv2.pt')
> optimized_model = optimize_for_mobile(model, backend="metal")
> print(torch.jit.export_opnames(optimized_model))
> torch.jit.save(optimized_model, './mobilenetv2_metal.pt')
> ```
> 
> Then I encountered some errors running metal-optimized model on device, but that's a story for another _issue_.

Hello, which version are you using? I met same error but with your solution it's still not working
