### ISSUE TITLE
torch.cat mismatched Tensor types --> Wrong error message

### ISSUE THREAD

**Issue by MattKleinsmith** [pytorch/pytorch#5438]
**Claim:**
When I cat a FloatTensor with a LongTensor, PyTorch says it got a list, but it should say it got a LongTensor. The same is true for any mismatched Tensor types.

**Code:**
```python
import torch
torch.cat([torch.FloatTensor(), torch.LongTensor()])
```

**Error message:**

```python
TypeError: cat received an invalid combination of arguments - got (list), but expected one of:
 * (sequence[torch.FloatTensor] seq)
      didn't match because some of the arguments have invalid types: (list)
 * (sequence[torch.FloatTensor] seq, int dim)
```

**Expected error message:**

```python
TypeError: cat received an invalid combination of arguments - got (torch.LongTensor), but expected one of:
 * (sequence[torch.FloatTensor] seq)
      didn't match because some of the arguments have invalid types: (torch.LongTensor)
 * (sequence[torch.FloatTensor] seq, int dim)
```

**Environment:**
- OS: Ubuntu 16.04 on Docker and host
- PyTorch version: 0.3.0.post4
- How you installed PyTorch: conda
- Python version: 3.6.3

**Comment by colesbury** [comment]
This is fixed in `master`:

```
RuntimeError: Expected a Tensor of type torch.FloatTensor but found a type torch.LongTensor for sequence element 1  in sequence argument at position #1 'tensors'
```

**Comment by colesbury** [comment]
@MattKleinsmith, thanks for reporting the bug. We don't expect people to test everything in master before reporting bugs. We tend to mark issues as closed as soon as they're fixed in the master branch, even if we haven't released new binary builds with the fix.
