### ISSUE TITLE
Is it possible to install torch=1.8.0 in windows(10)?

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/pytorch#54398]
I'm just trying to install torch=1.8.0 to use torchvision 0.9.0

I used below command to conda,
"conda install pytorch torchvision=0.9.0 torchaudio cudatoolkit=10.2 -c pytorch"

however, it is not successful, saying that some conflicts are there...(conda is trying to resolve the problem, but it is not successful)
Is it not only my problem?
(I shown that torchvision=0.9.0 needs pytorch=1.8.0,
https://github.com/pytorch/vision/blob/master/README.rst )

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by skyline75489** [comment]
I just tried and have no problem installing this. Please try to provide as much as information as you can, for example the *exact* log, if you really want people to help you.

**Comment by SungmanHong** [comment]
I just tried another command
"conda install pytorch torchvision=0.9.0 torchaudio cudatoolkit=10.2 -c pytorch -c conda-forge"
(although in my computer, without -c ocnda-forge was unssuccssful, but It may only my problem)

and install torch=1.8.0 and torchvision=0.9.0 on windows 10 is successful.
thanks and sorry!!

I just close it sorry!!
