### ISSUE TITLE
Custom cpp extension using accessor<long, 1> does not compile under windows 10/run under Mac OS

### ISSUE THREAD

**Issue by dirk-db** [pytorch/pytorch#54406]
## 🐛 Bug

Hi,

I'm try to write a custom cpp extension. The extension works (compiles and runs) under Linux/WSL but I'm having problems getting it to work under windows and mac. We tried it with different machines with the same result.

With **windows** (with Visual Studio 19), the compilation aborts with:
```
custom_cpp.obj : error LNK2001: error LNK2019: unresolved external symbol ""public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)". 
build\lib.win-amd64-3.8\name\custom_cpp.cp38-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
```

With **Mac** the compilation succeeds, but when executing the compute function of the package the following error appears:
```
E           ImportError: dlopen(/PATH/custom_cpp.cpython-38-darwin.so, 2): Symbol not found: __ZNK2at6Tensor8data_ptrIlEEPT_v
E             Referenced from: /PATH/custom_cpp.cpython-38-darwin.so
```
checking where the symbol is coming from:
> c++filt __ZNK2at6Tensor8data_ptrIlEEPT_v

and the output is

> long* at::Tensor::data_ptr<long>() const

I narrowed it doen to this line `auto acc = location.accessor<long, 1>();`. If you replace the `long` with `float` the compilation (win) and running it (mac) succeeds (however it then crashes with non-matching types which is to be expected).

## To Reproduce

1. Copy files below
2. Try to compile using `python setup.py bdist_wheel`
3. Import package and call the compute function (with mac)

Here is a minimal example:

setup.py:
```setup.py
from setuptools import setup

from torch.utils.cpp_extension import (
    BuildExtension,
    CppExtension,
)

ext_modules_cpp = [
    CppExtension(name="name.custom_cpp", sources=["custom_cpp.cpp"]),
]

setup(
    name="name",
    version="0.0.1",
    ext_modules=ext_modules_cpp,
    cmdclass={"build_ext": BuildExtension},
    extras_require={"test": "pytest"},
    zip_safe=False,
)
```

custom_cpp.cpp:
```custom_cpp.cpp
#include <torch/torch.h>

void compute(torch::Tensor location, int const T) {
    auto acc = location.accessor<long, 1>();
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) { // NOLINT
  m.def("compute", &compute, "Cpp impl");
}

```

## Expected behavior

Extension should compile and run.

## Environment
Collecting environment information...
PyTorch version: 1.8.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 11.2.67
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[conda] Could not collect

## Additional context

cc @yf225 @glaringlee @brianjo @mruberry @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489 @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by dirk-db** [comment]
Thanks a lot, that fixes our problems on windows as well as on mac. 

Would it be possible to add a hint about this in the documentation? This was not obvious to me.

**Comment by ezyang** [comment]
It might be possible to also add some static asserts for this situation to give a more direct indication of what should be done.
