### ISSUE TITLE
torch.from_numpy doesn't respect read-only arrays

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#5442]
See discussion at the bottom of #5426.

**Comment by yaroslavvb** [comment]
Here's an example, `from_numpy` takes 757 ms on my machine for 1GB numpy array. It seems there's a copy happening somewhere although I'm confused where since I don't see any calls to memcpy in https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_numpy.cpp#L91-L124


```
import numpy as np
import time
import torch

start_time = time.time()
arr = np.zeros((1000*250*1000,))
arr.flags['WRITEABLE'] = False
start_time = time.time()
arr2 = torch.from_numpy(arr)
print("%.1f ms "%((time.time()-start_time)*1000,))
```

**Comment by ngimel** [comment]
FWIW, with a relatively recent pytorch build and numpy 1.14.1 I'm seeing no copy, and pytorch not respecting read only flag. 
```.py
import numpy as np
import time
import torch

print("numpy version", np.version.version)
start_time = time.time()
arr = np.zeros((1000*250*1000,))
arr.flags['WRITEABLE'] = False
start_time = time.time()
arr2 = torch.from_numpy(arr)
print("time", time.time()-start_time)
arr2 += 1
print(arr[0], arr2[0])
arr += 1
```


```
numpy version 1.14.1
time 0.00014472007751464844
1.0 1.0
Traceback (most recent call last):
  File "arraycopy.py", line 14, in <module>
    arr += 1
ValueError: output array is read-only
```

**Comment by ngimel** [comment]
Binary release (pytorch-0.3.1-py36_cuda8.0.61_cudnn7.0.5_2) indeed does a copy
```
numpy version 1.14.1
time 1.3115856647491455
0.0 1.0
Traceback (most recent call last):
  File "arraycopy.py", line 14, in <module>
    arr += 1
ValueError: output array is read-only
```

**Comment by yaroslavvb** [comment]
Oh interesting! May be useful to figure out what change was responsible for removing a copy, in case there's a regression in the future

**Comment by apaszke** [comment]
It's probably because `torch.from_numpy` used to return a tensor, but returns a variable now (since tensors are no longer visible in Python). It's a regression

**Comment by apaszke** [comment]
Still, the fix will require us to make a copy, so the problem will persist. We don't have a read-only flag in PyTorch right now and adding it would require some effort.

**Comment by colesbury** [comment]
We never enforced read-only. We previously erroneously made copies because np.longlong vs np.int64 issues.

**Comment by colesbury** [comment]
We also should not ever make a copy in `torch.from_numpy`

**Comment by ngimel** [comment]
3.1 did have a path where numpy array would get copied, that does not seem to exist in master: 
https://github.com/pytorch/pytorch/blob/v0.3.1/torch/csrc/generic/Tensor.cpp#L194-L219

**Comment by colesbury** [comment]
@ngimel, yes I think that was there because of some code sharing via the `torch.Tensor(ndarray)` constructor which was intended to copy if the types didn't match.

https://github.com/pytorch/pytorch/blob/v0.3.1/torch/csrc/generic/Tensor.cpp#L308-L316

We've promised the `torch.from_numpy` shares memory in the documentation and repeatedly in forum posts:
http://pytorch.org/docs/0.3.1/torch.html#torch.from_numpy

**Comment by SeguinBe** [comment]
Was playing around with something and discovered as well that `from_numpy` does not respect read-only.

It actually can lead to hilarious situations like this one:
```python
import torch
import numpy as np
arr = np.frombuffer(b'A', dtype=np.uint8)
ten = torch.from_numpy(arr)
ten[0] = ord(b'B')

b'A' == b'B'  # returns True
print(b'AA')  # returns b'AA'
print(b'AA'[0:1])  # returns b'B'
```

Because CPython process single character strings weirdly, they are ever stored on a single place. So by modifying the memory area of one with torch (here `b'A'`), we modify all their occurences. Oh and we break the immutability of bytes sequences as well.

**Comment by zhangguanheng66** [comment]
Bring this to the triage meeting to conclude the discussions. Should we provide the option to make a copy of the numpy array?

**Comment by mruberry** [comment]
I believe #33615 addresses this issue by providing a warning. Actually supporting read-only tensors seems like a separate issue.

**Comment by TethysSun** [comment]
> It really seems to me like `torch.from_numpy(x)` does a copy when `x` is read only. I looked at the code that you linked to and I agree I don't see where the copy is happening.. but you can verify just by mutating the tensor and seeing that the underlying array doesn't change.
> 
> ```python
> import numpy as np
> import torch
> 
> x = np.zeros(10 ** 9)
> x.flags.writeable = False
> 
> x[0] = 1  # Fails with "ValueError: assignment destination is read-only"
> 
> %time t = torch.from_numpy(x)  # This takes 9s.
> 
> t[0] = 1  # This succeeds.
> 
> print(x[0])  # prints "0.0", so x is unmodified
> print(t[0])  # prints "1.0", so t is modified
> ```

This is not the same from what I tested below:
![image](https://user-images.githubusercontent.com/29682394/83978417-4f4a6f00-a8d5-11ea-9fdf-ee74fe769a79.png)
