### ISSUE TITLE
DISABLED test_from_cuda_array_interface* (TestNumbaIntegration)

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#54429]
https://app.circleci.com/pipelines/github/pytorch/pytorch/288392/workflows/eefe2661-2c8b-42c9-b416-8947699fa21e/jobs/11714811

https://app.circleci.com/pipelines/github/pytorch/pytorch/288392/workflows/eefe2661-2c8b-42c9-b416-8947699fa21e/jobs/11714822

**Comment by janeyx99** [comment]
Closing, this is better tracked in #54418.
