### ISSUE TITLE
Unable to print gc.get_objects() with pytorch

### ISSUE THREAD

**Issue by NickScottKortical** [pytorch/pytorch#54420]
Seems to be a similar issue to [https://github.com/pytorch/pytorch/issues/19351](this) which was fixed by adding \_\_file\_\_ to the ops class: https://github.com/pytorch/pytorch/pull/21888

gc.get_objects()
```
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 302, in _module_repr
  File "<frozen importlib._bootstrap>", line 295, in _module_repr
  File "/venv/lib/python3.8/site-packages/torch/_classes.py", line 10, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '__file__.__file__', but it does not exist! Ensure that it is registered via torch::class_

```

cc @gmagogsfm

**Comment by heitorschueroff** [comment]
Adding to triage review to see how this should be labeled

**Comment by albanD** [comment]
Hi,

I cannot reproduce this with the small example below:
```python
import torch
import gc

print(torch.__version__)

a = torch.rand(10)

a = gc.get_objects()
print("All ok")
```

Do you have a code sample to repro this?

**Comment by NickScottKortical** [comment]
@albanD 
The following should reproduce it (you need to try and print the pytorch object for it to fail)
```
import torch
import gc

print(torch.__version__)

a = torch.rand(10)

print(gc.get_objects())

```

**Comment by heitorschueroff** [comment]
> @albanD
> The following should reproduce it (you need to try and print the pytorch object for it to fail)
> 
> ```python
> import torch
> import gc
> 
> print(torch.__version__)
> 
> a = torch.rand(10)
> 
> print(gc.get_objects())
> ```

I can repro on master.

**Comment by albanD** [comment]
printing all the objects in the gc sounds like a bad idea :D 

But indeed printing any of the two following leads to the same error:
```python
import torch

print(torch.__dict__)
print(torch.classes)

from torch._classes import _Classes
print(_Classes())
```

cc @jamesr66a who added the corresponding code

**Comment by SplitInfinity** [comment]
Yeah, the solution here is to set `__file__` for `torch.classes` to something.

**Comment by gmagogsfm** [comment]
Update:
@yidawang-oss plans to work on it as bootcamp task
