### ISSUE TITLE
Node python binding is missing error conversion to python

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#54472]
The following leads to a hard crash and not a nice RuntimeError:

```python
import torch

a = torch.rand(10, requires_grad=True)

b = a * 2

print(b.grad_fn._saved_other) # Works fine

b.sum().backward()

print(b.grad_fn._saved_other) # Hard crash
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by soulitzer** [comment]
Would this require adding a bool to every Node to check if the saved variable has been freed or is there a better way?

**Comment by albanD** [comment]
The python binding should be able to check if the object is still there or not?

In the worst case, you would need a single boolean for all of them as they are always all freed at the same time.

**Comment by albanD** [comment]
After more offline discussion. The main thing that needs to be fixed is the hard crash here.
And the HANDLE_TH_ERROR macro missing is most likely the culprit.
