### ISSUE TITLE
[Feature request] device_as

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#5448]
Can we can we a function behave like this:

```
a = torch.arange(10).long() # torch.LongTensor
b = torch.randn(10).cuda() # torch.cuda.FloatTensor

a.device_as(b) # torch.cuda.LongTensor
```

I'm currently doing `a.type_as(b).long()`

**Comment by ruotianluo** [comment]
Any thoughts, or is there any simple alternatives?

**Comment by soumith** [comment]
@gchanan is planning to introduce device types, similar to how he introduced `dtype` on pytorch master. that work will go into 0.4, so a PR should be up soon-ish.

**Comment by gchanan** [comment]
We now have `to`.  `x_tensor.to(y_tensor)` both moves to the device and changes the dtype; `x_tensor.to(y_tensor.device)` does what `device_as` would do above.
