### ISSUE TITLE
Quant Wrapper error

### ISSUE THREAD

**Issue by Adhithya-tech** [pytorch/pytorch#54481]
## To Reproduce

1.Apply quantwrapper() function on pytorch object detection model (like faster RCNN module)

Expected input images to be of floating type (in range [0, 1]), but found type torch.quint8 instead

## Expected behavior

Supposed to reduce model size and perform flawless inference

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
@Adhithya-tech can you share the model architecture and the transformed model with quant/dequant added to it?

Is the error from the first layer of the model or from some intermediate layer?

**Comment by Adhithya-tech** [comment]
[`This was the discussion file`](https://discuss.pytorch.org/t/slow-inference-time-on-quantized-faster-rcnn-model/115182)  I noticed that I had mistakenly quantized it multiple times, so you can assume the multiple quant-dequant is absent with only one being present. 
The error occurs when I apply pytorch profiler

**Comment by Adhithya-tech** [comment]
@supriyar If you don't mind, could you also help me in understanding why the quant wrapper model hasn't reduced inference time despite reducing the model size significantly?

**Comment by vkuzo** [comment]
for triage

**Comment by supriyar** [comment]
> @supriyar If you don't mind, could you also help me in understanding why the quant wrapper model hasn't reduced inference time despite reducing the model size significantly?

Instead of quant wrapper you can also apply individual QuantStub and DequantStub in the model to quantize each layer separately.

The operator level profiler will help us understand why the time hasn't reduced despite quantizing the model. I see that there is duplicate discussion on this topic [here](https://discuss.pytorch.org/t/slow-inference-time-on-quantized-faster-rcnn-model/115182). Closing this issue, we can continue the discussion on the forum.
