### ISSUE TITLE
Same ADD operation, Tensor has a different result from Numpy

### ISSUE THREAD

**Issue by siyuhsu** [pytorch/pytorch#54493]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
![image](https://user-images.githubusercontent.com/40952612/112131173-3a409180-8c04-11eb-87ce-fbef3eaddb5f.png)
 
The first result is True, the second result is False. Details: https://github.com/pytorch/pytorch/issues/54493#issuecomment-804807598
Why?

cc @mruberry @rgommers @heitorschueroff

**Comment by skyline75489** [comment]
Hi! Could you elaborate on this? What is the expected behavior and what are you seeing? Also please fill the context needed about the environment you're using. There's [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) that helps you do that.

And you may want to attach the *code* directly instead of using screenshot. In order to repro this, we can copy & paste your code, but we can not do it easily from screenshots 😄

**Comment by siyuhsu** [comment]
I want to add every pixel value of an image to a tensor that has the same shape. When I used the Numpy Zero array to add the same shape image and save the Numpy array as an image, the new image was the same as before. However, I create the same shape Zero Tensor to add the image and transform it to NumPy to save it as an image, but the image was different from the original image.

![merge_image_0_0_np](https://user-images.githubusercontent.com/40952612/112133950-306c5d80-8c07-11eb-9bb0-d985ae612dc3.jpg)
![merge_image_0_0](https://user-images.githubusercontent.com/40952612/112133955-32362100-8c07-11eb-9efb-473a9e105800.jpg)

**Comment by siyuhsu** [comment]
ENVIRONMENT:
Collecting environment information...
PyTorch version: 1.3.0
Is debug build: False
CUDA used to build PyTorch: 10.1.243
ROCM used to build PyTorch: N/A
OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect
Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] numpy                     1.17.2           py36haad9e8e_0  
[conda] numpy-base                1.17.2           py36hde5b4d6_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

**Comment by siyuhsu** [comment]
Here is my code:
`
import torch
import cv2
import glob
import numpy as np

all_imgs = sorted(glob.glob("datasets/*/im1.png"))
def imread_tensor(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    im_tensor = torch.from_numpy(im_tran)
    
    return im_tensor

def imread_np(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    
    return im_tran

def tensor_im(im):
    im = im.permute(1, 2, 0)
    im_numpy = im.numpy()

    return im_numpy

imgs = []
imgs_np = []
for i in all_imgs:
    imgs.append(imread_tensor(i))
    imgs_np.append(imread_np(i))

oheight = 180
owidth = 320
iheight = 64
iwidth = 64
channel = 3
step = 32
n = 0
merge_img = torch.zeros((channel, oheight, owidth))
count_map = torch.zeros((channel, oheight, owidth))
merge_img_np = np.zeros((channel, oheight, owidth))
count_map_np = np.zeros((channel, oheight, owidth))
test_tensor = torch.zeros((3, 64, 64))
test_numpy = np.zeros((3, 64, 64))


for i in range(0, 4):
    for j in range(0, 9):
        test_numpy += imgs_np[n]
        test_tensor += imgs[n]
        if (imgs_np[n] == imgs[n].numpy()).all():
            print(True)
        else:
            print(False)
        if (test_numpy == test_tensor.numpy()).all():
            print(True)
        else:
            print(False)
        test_tensor = test_tensor.numpy()
        if (test_numpy == test_tensor).all():
            print(True)
        merge_img[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs[n]
        count_map[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        merge_img_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs_np[n]
        count_map_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        n += 1
        merge_img_tensor = merge_img.numpy().transpose((1, 2, 0))
        merge_img_numpy = merge_img_np.transpose((1, 2, 0))
        if (merge_img_numpy == merge_img_tensor).all():
            print(True)
            print(merge_img_numpy.sum())
            print(merge_img_tensor.sum())
        cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), merge_img_tensor)
        cv2.imwrite("tmp/merge_image_%d_%d_np.jpg"%(i, j), merge_img_numpy)

for j in range(0, 9):
    merge_img[:, oheight-iheight:oheight, step*j:step*j+iwidth] = imgs[n]
    count_map[:, oheight-iheight:oheight, step*j:step*j+iwidth] += 1
    n += 1
    # img = (merge_img/count_map).permute(1, 2, 0)
    # cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), img.numpy())

merge_image = merge_img / count_map

cv2.imwrite("tmp/test.jpg", tensor_im(merge_img))
`

**Comment by siyuhsu** [comment]
`import torch
import cv2
import glob
import numpy as np

all_imgs = sorted(glob.glob("datasets/*/im1.png"))
def imread_tensor(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    im_tensor = torch.from_numpy(im_tran)
    
    return im_tensor

def imread_np(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    
    return im_tran

def tensor_im(im):
    im = im.permute(1, 2, 0)
    im_numpy = im.numpy()

    return im_numpy

imgs = []
imgs_np = []
for i in all_imgs:
    imgs.append(imread_tensor(i))
    imgs_np.append(imread_np(i))

oheight = 180
owidth = 320
iheight = 64
iwidth = 64
channel = 3
step = 32
n = 0
merge_img = torch.zeros((channel, oheight, owidth))
count_map = torch.zeros((channel, oheight, owidth))
merge_img_np = np.zeros((channel, oheight, owidth))
count_map_np = np.zeros((channel, oheight, owidth))
test_tensor = torch.zeros((3, 64, 64))
test_numpy = np.zeros((3, 64, 64))


for i in range(0, 4):
    for j in range(0, 9):
        test_numpy += imgs_np[n]
        test_tensor += imgs[n]
        if (imgs_np[n] == imgs[n].numpy()).all():
            print(True)
        else:
            print(False)
        if (test_numpy == test_tensor.numpy()).all():
            print(True)
        else:
            print(False)
        test_tensor = test_tensor.numpy()
        if (test_numpy == test_tensor).all():
            print(True)
        merge_img[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs[n]
        count_map[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        merge_img_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs_np[n]
        count_map_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        n += 1
        merge_img_tensor = merge_img.numpy().transpose((1, 2, 0))
        merge_img_numpy = merge_img_np.transpose((1, 2, 0))
        if (merge_img_numpy == merge_img_tensor).all():
            print(True)
            print(merge_img_numpy.sum())
            print(merge_img_tensor.sum())
        cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), merge_img_tensor)
        cv2.imwrite("tmp/merge_image_%d_%d_np.jpg"%(i, j), merge_img_numpy)

for j in range(0, 9):
    merge_img[:, oheight-iheight:oheight, step*j:step*j+iwidth] = imgs[n]
    count_map[:, oheight-iheight:oheight, step*j:step*j+iwidth] += 1
    n += 1
    # img = (merge_img/count_map).permute(1, 2, 0)
    # cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), img.numpy())

merge_image = merge_img / count_map

cv2.imwrite("tmp/test.jpg", tensor_im(merge_img))`

**Comment by siyuhsu** [comment]
![image](https://user-images.githubusercontent.com/40952612/112135190-7d046880-8c08-11eb-8e5a-583c29cc283f.png)
![image](https://user-images.githubusercontent.com/40952612/112135275-93aabf80-8c08-11eb-9341-d5061a64affa.png)

**Comment by siyuhsu** [comment]
`
import torch
import cv2
import glob
import numpy as np

all_imgs = sorted(glob.glob("datasets/*/im1.png"))
def imread_tensor(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    im_tensor = torch.from_numpy(im_tran)
    
    return im_tensor

def imread_np(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    
    return im_tran

def tensor_im(im):
    im = im.permute(1, 2, 0)
    im_numpy = im.numpy()

    return im_numpy

imgs = []
imgs_np = []
for i in all_imgs:
    imgs.append(imread_tensor(i))
    imgs_np.append(imread_np(i))

oheight = 180
owidth = 320
iheight = 64
iwidth = 64
channel = 3
step = 32
n = 0
merge_img = torch.zeros((channel, oheight, owidth))
count_map = torch.zeros((channel, oheight, owidth))
merge_img_np = np.zeros((channel, oheight, owidth))
count_map_np = np.zeros((channel, oheight, owidth))
test_tensor = torch.zeros((3, 64, 64))
test_numpy = np.zeros((3, 64, 64))


for i in range(0, 4):
    for j in range(0, 9):
        test_numpy += imgs_np[n]
        test_tensor += imgs[n]
        if (imgs_np[n] == imgs[n].numpy()).all():
            print(True)
        else:
            print(False)
        if (test_numpy == test_tensor.numpy()).all():
            print(True)
        else:
            print(False)
        test_tensor = test_tensor.numpy()
        if (test_numpy == test_tensor).all():
            print(True)
        merge_img[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs[n]
        count_map[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        merge_img_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs_np[n]
        count_map_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        n += 1
        merge_img_tensor = merge_img.numpy().transpose((1, 2, 0))
        merge_img_numpy = merge_img_np.transpose((1, 2, 0))
        if (merge_img_numpy == merge_img_tensor).all():
            print(True)
            print(merge_img_numpy.sum())
            print(merge_img_tensor.sum())
        cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), merge_img_tensor)
        cv2.imwrite("tmp/merge_image_%d_%d_np.jpg"%(i, j), merge_img_numpy)

for j in range(0, 9):
    merge_img[:, oheight-iheight:oheight, step*j:step*j+iwidth] = imgs[n]
    count_map[:, oheight-iheight:oheight, step*j:step*j+iwidth] += 1
    n += 1
    # img = (merge_img/count_map).permute(1, 2, 0)
    # cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), img.numpy())

merge_image = merge_img / count_map

cv2.imwrite("tmp/test.jpg", tensor_im(merge_img))
`

**Comment by siyuhsu** [comment]
```
import torch
import cv2
import glob
import numpy as np

all_imgs = sorted(glob.glob("datasets/*/im1.png"))
def imread_tensor(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    im_tensor = torch.from_numpy(im_tran)
    
    return im_tensor

def imread_np(imp):
    im = cv2.imread(imp)
    im_tran = im.transpose(2, 0, 1)
    
    return im_tran

def tensor_im(im):
    im = im.permute(1, 2, 0)
    im_numpy = im.numpy()

    return im_numpy

imgs = []
imgs_np = []
for i in all_imgs:
    imgs.append(imread_tensor(i))
    imgs_np.append(imread_np(i))

oheight = 180
owidth = 320
iheight = 64
iwidth = 64
channel = 3
step = 32
n = 0
merge_img = torch.zeros((channel, oheight, owidth))
count_map = torch.zeros((channel, oheight, owidth))
merge_img_np = np.zeros((channel, oheight, owidth))
count_map_np = np.zeros((channel, oheight, owidth))
test_tensor = torch.zeros((3, 64, 64))
test_numpy = np.zeros((3, 64, 64))


for i in range(0, 4):
    for j in range(0, 9):
        test_numpy += imgs_np[n]
        test_tensor += imgs[n]
        if (imgs_np[n] == imgs[n].numpy()).all():
            print(True)
        else:
            print(False)
        if (test_numpy == test_tensor.numpy()).all():
            print(True)
        else:
            print(False)
        test_tensor = test_tensor.numpy()
        if (test_numpy == test_tensor).all():
            print(True)
        merge_img[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs[n]
        count_map[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        merge_img_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += imgs_np[n]
        count_map_np[:, step*i:step*i+iheight, step*j:step*j+iwidth] += 1
        n += 1
        merge_img_tensor = merge_img.numpy().transpose((1, 2, 0))
        merge_img_numpy = merge_img_np.transpose((1, 2, 0))
        if (merge_img_numpy == merge_img_tensor).all():
            print(True)
            print(merge_img_numpy.sum())
            print(merge_img_tensor.sum())
        cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), merge_img_tensor)
        cv2.imwrite("tmp/merge_image_%d_%d_np.jpg"%(i, j), merge_img_numpy)

for j in range(0, 9):
    merge_img[:, oheight-iheight:oheight, step*j:step*j+iwidth] = imgs[n]
    count_map[:, oheight-iheight:oheight, step*j:step*j+iwidth] += 1
    n += 1
    # img = (merge_img/count_map).permute(1, 2, 0)
    # cv2.imwrite("tmp/merge_image_%d_%d.jpg"%(i, j), img.numpy())

merge_image = merge_img / count_map

cv2.imwrite("tmp/test.jpg", tensor_im(merge_img))
```

**Comment by skyline75489** [comment]
Ok how would you expect us to solve your issue? To type the code one character a time? Come on. Please just use source code and not screenshot. See https://guides.github.com/features/mastering-markdown/ for help on formatting code using markdown. 

I haven’t looking into this but are you sure this is issue of PyTorch itself? If you’re sure about this, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so that everyone can have a reasonable way to help you.

**Comment by siyuhsu** [comment]
Thanks! Here is an example, you can use this image to reproduce this problem. 
![im1](https://user-images.githubusercontent.com/40952612/112136932-9ad2cd00-8c0a-11eb-8a99-d8748c42ae19.png)

**Comment by siyuhsu** [comment]
> Thanks! Here is an example, you can use this image to reproduce this problem.
> ![im1](https://user-images.githubusercontent.com/40952612/112136932-9ad2cd00-8c0a-11eb-8a99-d8748c42ae19.png)

Set a debug point, there will create two images after the first loop.

**Comment by siyuhsu** [comment]
> Ok how would you expect us to solve your issue? To type the code one character a time? Come on. Please just use source code and not screenshot. See https://guides.github.com/features/mastering-markdown/ for help on formatting code using markdown.
> 
> I haven’t looking into this but are you sure this is issue of PyTorch itself? If you’re sure about this, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so that everyone can have a reasonable way to help you.

I used NumPy to stitch some images and get the right image, but when I use pytorch do the same operation and get a wrong image

**Comment by siyuhsu** [comment]
> > Ok how would you expect us to solve your issue? To type the code one character a time? Come on. Please just use source code and not screenshot. See https://guides.github.com/features/mastering-markdown/ for help on formatting code using markdown.
> > I haven’t looking into this but are you sure this is issue of PyTorch itself? If you’re sure about this, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so that everyone can have a reasonable way to help you.
> 
> I used NumPy to stitch some images and get the right image, but when I use pytorch do the same operation and get a wrong image
Like this two images

https://github.com/pytorch/pytorch/issues/54493#issuecomment-804798073

**Comment by skyline75489** [comment]
这段代码离**最小可复现例子**差的太远。“最小”的意思是"使用最少的代码复现同样的问题“，你需要自己去抽离代码当中可能存在问题的片段，然后让大家能够方便地运行这段代码复现问题。在这个过程中，很有可能你也会自己理解并发现问题的所在，乃至解决方案。

OK this is far from a **Minimal, Reproducible Example**. "Minimal" means "use as little code as possible that still produces the same problem". You need to extract only the problematic snippet from your code, for everyone to be able to easily reproduce it on their machine. During the process, it's highly possible that you find and understand what exactly the problem is, and have a solution.

**Comment by siyuhsu** [comment]
> 这段代码离**最小可复现例子**差的太远。“最小”的意思是"使用最少的代码复现同样的问题“，你需要自己去抽离代码当中可能存在问题的片段，然后让大家能够方便地运行这段代码复现问题。在这个过程中，很有可能你也会自己理解并发现问题的所在，乃至解决方案。
> 
> OK this is far from a **Minimal, Reproducible Example**. "Minimal" means "use as little code as possible that still produces the same problem". You need to extract only the problematic snippet from your code, for everyone to be able to easily reproduce it on their machine. During the process, it's highly possible that you find and understand what exactly the problem is, and have a solution.

Sorry, I update the Reproducible Example. https://github.com/pytorch/pytorch/issues/54493#issuecomment-804807598

Learn a lot, thank you!

**Comment by bdhirsh** [comment]
Hi @siyuhsu,

Can you provide more of a minimum repro for the issue? For example, we can't reproduce your issue locally without `imgs` and `imgs_np` are in your example. It'd help to identify the specific value of `test_numpy` and `test_tensor in your example when they're different.

**Comment by siyuhsu** [comment]
> Hi @siyuhsu,
> 
> Can you provide more of a minimum repro for the issue? For example, we can't reproduce your issue locally without knowing what `imgs` and `imgs_np` are in your example. It'd help to identify the specific value of `test_numpy` and `test_tensor` in your example when they're different.

Thank you! I have re-edited the minimum repro. To be clear, I made a modification of https://github.com/pytorch/pytorch/issues/54493#issuecomment-804807598  and used a smaller Numpy and Tensor shape to print the values.

In this case, `im_numpy` equals to `im_tensor2numpy`. After the ADD operation, `test_numpy` should be equal to `test_tensor2numpy`, but these two arrays don't the same. I don't know why this happened.

```python
import cv2
import torch
import numpy as np

def imread_tensor(imp):
    """
    read image,
    reorder "HWC" to "CHW"
    return a Tensor
    """
    im = cv2.imread(imp)
    return torch.from_numpy(im.transpose(2, 0, 1))

def imread_numpy(imp):
    """
    read image,
    reorder "HWC" to "CHW"
    return a NumPy Array
    """
    im = cv2.imread(imp)
    return im.transpose(2, 0, 1)

img_path = "im1.png"

test_tensor = torch.zeros((3, 4, 4))
test_numpy = np.zeros((3, 4, 4))
im_numpy = imread_numpy(img_path)[:,:4,:4]
im_tensor = imread_tensor(img_path)[:,:4,:4]

test_numpy += im_numpy
test_tensor += im_tensor

im_tensor2numpy = im_tensor.numpy()
test_tensor2numpy = test_tensor.numpy()
if (im_numpy == im_tensor2numpy).all():
    print(True)
else:
    print(False)
if (test_numpy == test_tensor2numpy).all():
    print(True)
else:
    print(False)

"""
im_numpy:
[[208, 207, 209, 211],       [215, 205, 206, 208],       [209, 200, 202, 204],       [207, 196, 198, 202]]
[[172, 176, 180, 180],       [179, 176, 178, 180],       [179, 177, 178, 180],       [176, 175, 176, 178]]
[[24, 11, 11, 12],       [ 8,  4,  4,  5],       [ 8,  5,  4,  5],       [ 9,  5,  5,  5]]

im_tensor2numpy:
[[208, 207, 209, 211],       [215, 205, 206, 208],       [209, 200, 202, 204],       [207, 196, 198, 202]]
[[172, 176, 180, 180],       [179, 176, 178, 180],       [179, 177, 178, 180],       [176, 175, 176, 178]]
[[24, 11, 11, 12],       [ 8,  4,  4,  5],       [ 8,  5,  4,  5],       [ 9,  5,  5,  5]]

test_numpy:
[[208, 207, 209, 211],       [215, 205, 206, 208],       [209, 200, 202, 204],       [207, 196, 198, 202]]
[[172, 176, 180, 180],       [179, 176, 178, 180],       [179, 177, 178, 180],       [176, 175, 176, 178]]
[[24, 11, 11, 12],       [ 8,  4,  4,  5],       [ 8,  5,  4,  5],       [ 9,  5,  5,  5]]

test_tensor2numpy:
[[2.0800000e+02, 2.1100000e+02, 2.0600000e+02, 2.0000000e+02],       [2.6657929e-09, 3.1432754e-12, 3.9591552e-11, 1.3563156e-19],       [2.5223372e-44, 3.0762705e-41, 2.6624671e-44, 3.0762705e-41],       [1.3563156e-19, 1.3567154e-19, 3.9591552e-11, 2.6319608e-12]]
[[ 2.0700000e+02,  2.1500000e+02,  2.0800000e+02,  2.0200000e+02],       [ 6.5984455e-07,  1.3563128e-19,  1.1703673e-19,  1.7082824e-04],       [ 0.0000000e+00, -2.3994415e+27,  0.0000000e+00, -2.3994226e+27],       [ 1.3563156e-19,  1.4587234e-19,  2.3308178e-09,  1.6898336e-04]]
[[2.0900000e+02, 2.0500000e+02, 2.0900000e+02, 2.0400000e+02],       [2.3308193e-09, 1.3563156e-19, 1.3563156e-19, 2.3301352e-09],       [7.8278356e+16, 4.5637488e-41, 7.8278631e+16, 4.5637488e-41],       [2.3894900e-06, 2.6178018e-12, 1.4585576e-19, 1.7035084e+28]]
"""
    
cv2.imwrite("image_tensor.jpg", test_tensor.numpy().transpose((1, 2, 0)))
cv2.imwrite("image_numpy.jpg", test_numpy.transpose((1, 2, 0)))
```

**Comment by rgommers** [comment]
This is a known issue I believe, the mix of the inplace operation (`+=` here) with sharing a view of the data of a tensor as a numpy array is not handled in the `.numpy()` implementation. See https://github.com/pytorch/pytorch/issues/54138#issuecomment-801077815 and the other comment that that comment links to.

**Comment by siyuhsu** [comment]
> This is a known issue I believe, the mix of the inplace operation (`+=` here) with sharing a view of the data of a tensor as a numpy array is not handled in the `.numpy()` implementation. See [#54138 (comment)](https://github.com/pytorch/pytorch/issues/54138#issuecomment-801077815) and the other comment that that comment links to.

Maybe not the same issue. The problem is not about the  `+=` operation(Please see `test_tensor2` and `test_tensor` value) and `.numpy()` implementation. 

As I use `numpy.transpose()` doing the Tensor ADD operation, this will return a wrong value(`test_tensor` should be qual to ). But when I do the Tensor ADD operation without `numpy.transpose()`, I get the right value. This is so weird! I still can't figure it out.

```python
import torch
import numpy as np

im_numpy = np.random.randint(0, 3, (4, 3))
print(im_numpy)
"""
[[2 0 0]
 [2 0 1]
 [2 2 1]
 [2 1 2]]
"""
im_numpy_tran = im_numpy.transpose(1, 0) # with numpy.transpose()
print(im_numpy_tran)
"""
[[2 2 2 2]
 [0 0 2 1]
 [0 1 1 2]]
"""
test_tensor = torch.zeros((3, 4))
print(test_tensor.data)
"""
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
"""
im_tensor = torch.from_numpy(im_numpy_tran)
print(im_tensor.data)
"""
tensor([[2, 2, 2, 2],
        [0, 0, 2, 1],
        [0, 1, 1, 2]])
"""
test_tensor2 = test_tensor + im_tensor
print(test_tensor2.data)
"""
tensor([[2., 2., 2., 1.],
        [2., 0., 1., 1.],
        [2., 0., 0., 2.]])
"""
test_tensor += im_tensor
print(test_tensor.data)
"""
tensor([[2., 2., 2., 1.],
        [2., 0., 1., 1.],
        [2., 0., 0., 2.]])
"""
```
```
import torch
import numpy as np

im_numpy = np.random.randint(0, 3, (3, 4))
print(im_numpy)
"""
[[0 0 1 1]
 [2 2 0 2]
 [0 2 1 0]]
"""
im_numpy_tran = im_numpy # without numpy.transpose()
print(im_numpy_tran)
"""
[[0 0 1 1]
 [2 2 0 2]
 [0 2 1 0]]
"""
test_tensor = torch.zeros((3, 4))
print(test_tensor.data)
"""
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
"""
im_tensor = torch.from_numpy(im_numpy_tran)
print(im_tensor.data)
"""
tensor([[0, 0, 1, 1],
        [2, 2, 0, 2],
        [0, 2, 1, 0]])
"""
test_tensor2 = test_tensor + im_tensor
print(test_tensor2.data)
"""
tensor([[0., 0., 1., 1.],
        [2., 2., 0., 2.],
        [0., 2., 1., 0.]])
"""
test_tensor += im_tensor
print(test_tensor.data)
"""
tensor([[0., 0., 1., 1.],
        [2., 2., 0., 2.],
        [0., 2., 1., 0.]])
"""
```

**Comment by rgommers** [comment]
@siyuhsu did you close this issue on purpose?

**Comment by siyuhsu** [comment]
> @siyuhsu did you close this issue on purpose?
This problem is solved by upgrading PyTorch version. Only Pytorch `1.3.0` has this problem. Please see https://github.com/pytorch/pytorch/issues/54650#issuecomment-806389825
