### ISSUE TITLE
 module 'torch' has no attribute 'QUInt4x2Storage'

### ISSUE THREAD

**Issue by ninjakx** [pytorch/pytorch#54490]
`pip freeze | grep torch`
---------
```
efficientnet-pytorch==0.6.3
segmentation-models-pytorch==0.0.3
torch==1.7.1+cu110
torch-cluster==1.5.9
torch-geometric==1.6.3
torch-scatter==2.0.6
torch-sparse==0.6.9
torch-spline-conv==1.2.1
torchaudio==0.7.2
torchfile==0.1.0
torchsummary==1.5.1
torchtext==0.6.0
torchvision==0.8.2+cu110
```

When I tried to export `libtorch_cuda.so` lib folder for torch geometric from this path `~/.local/lib/python3.6/site-packages/torch/lib` .  I have started getting the mentioned error.

`~/.bashrc`:

```
export PATH=/usr/local/cuda/bin:$PATH
export CPATH=/usr/local/cuda/include:$CPATH
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/.local/lib/python3.6/site-packages/torch/lib:$LD_LIBRARY_PATH
```

**Comment by skyline75489** [comment]
> When I tried to export libtorch_cuda.so lib folder for torch geometric from this path ~/.local/lib/python3.6/site-packages/torch/lib

Can you elaborate on this part? What did you do exactly, and what the exact command line output is?

Also please do not delete the issue template entirely and try to fill the context needed. There's [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) that helps you do that.

**Comment by ninjakx** [comment]
@skyline75489 : the `torch_scatter` required `libtorch_cuda_cu.so`

because when I  do `import torch_scatter` I got this error:

`OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
`
So I added the location where my ` libtorch_cuda_cu.so` is by  `export LD_LIBRARY_PATH=~/.local/lib/python3.6/site-packages/torch/lib:$LD_LIBRARY_PATH` 

but that started giving me `module 'torch' has no attribute 'QUInt4x2Storage'` 

So fixed which I just find out is the don't do `export LD_LIBRARY_PATH` thing instead `uninstall` and `install` the `torch_scatter` again by `pip uninstall toscatter && pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`

**Comment by skyline75489** [comment]
OK Glad you fixed it. Github is mainly for issues about PyTorch *itself*. So make sure you try all the solution before actually filing a issue here 😄
