### ISSUE TITLE
Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#54506]
## 📚 Documentation

As indicated in https://github.com/pytorch/pytorch/issues/53466, the document related is https://pytorch.org/docs/stable/generated/torch.enable_grad.html
It would be great if anyone could help me change the first line of the example code in the documentation.
From
```
x = torch.tensor([1], requires_grad=True)
```
To
```
x = torch.tensor([1.], requires_grad=True)
```
The fix is simply adding a dot so that the Tensor becomes a floating-point number, and the RuntimeException (`RuntimeError: Only Tensors of floating point and complex dtype can require gradients`) no longer appears.

Sorry I am not quite familiar with fixing docs. I would appreciate it very much if someone could help me fix the small issue:)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @brianjo @mruberry

**Comment by jbschlosser** [comment]
Hey @ilovepytorch, to fix this, you should edit `torch/autograd/grad_mode.py` under the docs for the `enable_grad` class. Hope that helps!

**Comment by ilovepytorch** [comment]
Thanks a lot!
