### ISSUE TITLE
Expose at::Tensor in python

### ISSUE THREAD

**Issue by bordingj** [pytorch/pytorch#5454]
Now that Variable and torch.Tensor is merged, how do I create an at::Tensor from python and how do I reach the underlying at::Tensor of a Variable from python and from c++?
I have used torch and aten in c++ and python alot as an alternative to numpy, where I didnt care about the autograd part. Now I can only use autograd.Variable from python, which makes me pretty sad.

**Comment by apaszke** [comment]
We don't plan to keep maintaining the `at::Tensor` bindings for non-Variable types. If you get a Python object in C++, you can call the `.data()` to retrieve the `at::Tensor`.
