### ISSUE TITLE
Unexpected behaviour on method signature matching with an Int or IntList single positional argument

### ISSUE THREAD

**Issue by iramazanli** [pytorch/pytorch#54555]
Consider an operation vsplit with the following two signatures:
```
- func: vsplit.int(Tensor(a) self, int sections) -> Tensor(a)[]
  variants: function, method

- func: vsplit.array(Tensor(a) self, int[] indices) -> Tensor(a)[]
  variants: function, method
```
is called with single integer input
```
t.vsplit(3) # matches int[] signature.
torch.vsplit(t, 3) # matches int signature. 
```
signature matching goes to int[] instead of int when it's called as method. However, if method is receiving more than one input value (i.e. function receiving more than two input value) the same incident doesn't happen.

This is maybe due to the line :  https://github.com/pytorch/pytorch/blob/4a74b0f2ddb3a01c0968a94d28d32f6160753c00/torch/csrc/utils/python_arg_parser.cpp#L879
what's interesting is the signature int[] always appeared to be considered first in : 
https://github.com/pytorch/pytorch/blob/4a74b0f2ddb3a01c0968a94d28d32f6160753c00/torch/csrc/utils/python_arg_parser.cpp#L1018

Is there a way that let's us to consider int signature first ?
If not is there are recommended way to opt out of this behaviour.

CC @ezyang , @bhosmer

**Comment by ezyang** [comment]
Yes, it's precisely the code you identified. Is this causing a problem? Even if you managed to get the overload resolution to go the other way, I would hope that `vsplit(3)` and `vsplit([3])` have the same semantics.

**Comment by gchanan** [comment]
I don't think they have the same behavior, one is split into sections, the other is endpoints for the section.

**Comment by gchanan** [comment]
I thought that the behavior was that the order specified in native_functions was the preference order for parsing -- is that not the case here.  Can you post the generated parsing code?

**Comment by ezyang** [comment]
On the contrary, I don't think order in `native_functions.yaml` is supposed to matter.

@gchanan Is it too late to fix the API? LOL

**Comment by mruberry** [comment]
I also thought that order mattered for the signatures and I think we have other operations that rely on signature ordering.

The vsplit(3) vs vsplit([3]) thing is confusing, but consistent with NumPy. These functions are just sugars around tensor_split(), which has the same behavior:

```
t = torch.randn(6, 2)

t.tensor_split(2)
: (tensor([[-0.8170, -0.1274], [-0.6639,  1.3684], [-2.8871, -1.5102]]), 
   tensor([[ 0.3740,  1.3931], [ 0.2948,  0.6862], [ 0.3993, -1.9573]]))

t.tensor_split([2])
: (tensor([[-0.8170, -0.1274], [-0.6639,  1.3684]]), 
   tensor([[-2.8871, -1.5102], [ 0.3740,  1.3931], [ 0.2948,  0.6862], [ 0.3993, -1.9573]]))
```

**Comment by ezyang** [comment]
```
# This function declares a partial order on declarations, and sorts them according
# to its linear extension. This is necessary, because there's some ambiguity in the
# choice of overload, and we want a different order.
#
# See Note[Order of overloads matters]
#
# A few examples of ambiguous python signature pairs.
#
#   All parameters have the same type, except one taking Tensor the other taking
#   Scalar. A numeric PyObject can be casted into Tensor, and a zero-dim Tensor
#   object can be accepted as Scalar type parameter (see python_arg_parser.cpp).
#   Therefore, same input arguments might be accepted by either python signature.
#   We want to always parse the one taking Tensor first.
#
#     bitwise_and(Tensor input, Tensor other, *, Tensor out=None)
#     bitwise_and(Tensor input, Scalar other, *, Tensor out=None)
#
#   If they have different number of parameters then they are not ambiguous - but
#   the difference on output param can be ignored as it's optional.
#
#     multiply(Tensor input, Tensor other, *, Tensor out=None)
#     multiply(Tensor input, Scalar other)
#
#   Both positional args and keyword-only args are considered together.
#
#     subtract(Tensor other, *, Scalar alpha=1)
#     subtract(Scalar other, Scalar alpha=1)
#
# A few ambiguous cases which it does NOT handle yet.
#
#   If there is any difference in other parameters besides the Tensor/Scalar
#   difference, then they are not considered ambiguous by this method anymore.
#   However, the difference could be too trivial to disambiguate.
#
#     foo(Tensor input, Scalar other, Scalar bar)
#     foo(Tensor input, Tensor other, double bar)
#
#   If they are taking different number of parameters then they are not considered
#   ambiguous anymore, even if the difference is only on optional kwargs.
#
#     foo(Scalar other, Scalar alpha=1)
#     foo(Tensor other, *, Scalar alpha=1, Scalar beta=1)
#

```

**Comment by mruberry** [comment]
OK, but what's your thinking on how we resolve this issue? Some options:

- declare this UX anathema
- allow for explicit ordering of signatures for signature matching (this might be useful in other contexts)
- change the signature matching order (for example, int to int[])

Separately we might to better document how ambiguous signatures are matched. The above doesn't actually say how signatures are sorted.

**Comment by ezyang** [comment]
I mean, if you just want to fix this case, a little hack to disable the `if (max_pos_args == 1 && params[0].type_ == ParameterType::INT_LIST) { ` behavior for `vsplit` seems like the easiest thing to do. It doesn't seem like we want to declare this UX illegal because of Numpy compatibility...

**Comment by mruberry** [comment]
That seems reasonable as long as it doesn't impact performance.

**Comment by iramazanli** [comment]
For this specific problem i would want to ask your opinion about the following simple solution. It still feels like simplest thing to do for me.

```
t = torch.tensor([0, 1, 2, 3, 4, 5])
t.hsplit(3)
```

Has the same result / semantic as 

```
t = torch.tensor([0, 1, 2, 3, 4, 5])
t.hsplit([2, 4])
```

As both results in the list of tensors  (tensor([0, 1]), tensor([2, 3]), tensor([4, 5])).  The idea is extendible to general case. For example if the size is 18 and we want to split it 6 sections, we would pass input of [3, 6, 9, 12, 15] which will result in the tensor list of size 6 : (tensor([0,1,2]), tensor([3,4,5]), tensor([6,7,8]), tensor([9,10,11]), tensor([12,13,14]), tensor([15,16,17])).

**Comment by iramazanli** [comment]
Also generated code could be found here:

```
TORCH_API std::vector<at::Tensor> hsplit(const at::Tensor & self, int64_t sections, c10::optional<int64_t> sentinel=c10::nullopt);
TORCH_API std::vector<at::Tensor> hsplit(const at::Tensor & self, at::IntArrayRef indices, c10::optional<int64_t> sentinel=c10::nullopt);
TORCH_API std::vector<at::Tensor> vsplit(const at::Tensor & self, int64_t sections, c10::optional<int64_t> sentinel=c10::nullopt);
TORCH_API std::vector<at::Tensor> vsplit(const at::Tensor & self, at::IntArrayRef indices, c10::optional<int64_t> sentinel=c10::nullopt);
TORCH_API std::vector<at::Tensor> dsplit(const at::Tensor & self, int64_t sections, c10::optional<int64_t> sentinel=c10::nullopt);
TORCH_API std::vector<at::Tensor> dsplit(const at::Tensor & self, at::IntArrayRef indices, c10::optional<int64_t> sentinel=c10::nullopt);
```
