### ISSUE TITLE
rpc: set_device_map() does not work for RRef(s)

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#54560]
## 🐛 Bug

```
[W tensorpipe_agent.cpp:769] RPC agent for worker1 encountered error when reading incoming request from worker0: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:260)
Traceback (most recent call last):
  File "rpc_bug.py", line 45, in <module>
    mp.spawn(rpc_worker, args=(world_size, tempfile.mkstemp()[1], test_func), nprocs=world_size)
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/private/home/msb/code/fairscale/rpc_bug.py", line 26, in rpc_worker
    func()
  File "/private/home/msb/code/fairscale/rpc_bug.py", line 40, in test_func
    print(y.to_here())
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/distributed/rpc/internal.py", line 207, in _handle_exception
    raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
RuntimeError: On WorkerInfo(id=1, name=worker1):
RuntimeError('TensorPipe RPC backend only supports CPU tensors by default, please move your tensors to CPU before sending them over RPC, or call `set_device_map` on `TensorPipeRpcBackendOptions` to explicitly configure device mapping. Response device mapping is not available for destination worker1, but found tensor on device: cuda:0
Exception raised from getDevicesForRemote at /pytorch/torch/csrc/distributed/rpc/tensorpipe_agent.cpp:1363 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe30de4ff72 in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fe30de4ca4b in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0xba84b7 (0x7fe384d524b7 in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: torch::distributed::rpc::TensorPipeAgent::sendCompletedResponseMessage(std::shared_ptr<tensorpipe::Pipe>&, std::shared_ptr<c10::ivalue::Future>&, unsigned long, std::shared_ptr<torch::distributed::rpc::LazyStreamContext>) + 0x4bd (0x7fe384d4540d in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xb9d0ae (0x7fe384d470ae in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10::ThreadPool::main_loop(unsigned long) + 0x26b (0x7fe30de40eeb in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0xd6d84 (0x7fe385a2ed84 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x9609 (0x7fe386da4609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x43 (0x7fe386ccb293 in /usr/lib/x86_64-linux-gnu/libc.so.6)
')
Traceback (most recent call last):
  File "/private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/distributed/rpc/internal.py", line 193, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/private/home/msb/code/fairscale/rpc_bug.py", line 33, in rref_func
    x = rref.to_here()
RuntimeError: TensorPipe RPC backend only supports CPU tensors by default, please move your tensors to CPU before sending them over RPC, or call `set_device_map` on `TensorPipeRpcBackendOptions` to explicitly configure device mapping. Response device mapping is not available for destination worker1, but found tensor on device: cuda:0
Exception raised from getDevicesForRemote at /pytorch/torch/csrc/distributed/rpc/tensorpipe_agent.cpp:1363 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fe30de4ff72 in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fe30de4ca4b in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0xba84b7 (0x7fe384d524b7 in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: torch::distributed::rpc::TensorPipeAgent::sendCompletedResponseMessage(std::shared_ptr<tensorpipe::Pipe>&, std::shared_ptr<c10::ivalue::Future>&, unsigned long, std::shared_ptr<torch::distributed::rpc::LazyStreamContext>) + 0x4bd (0x7fe384d4540d in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xb9d0ae (0x7fe384d470ae in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10::ThreadPool::main_loop(unsigned long) + 0x26b (0x7fe30de40eeb in /private/home/msb/.conda/envs/fairseq-20210102-pt-ntly/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0xd6d84 (0x7fe385a2ed84 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x9609 (0x7fe386da4609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x43 (0x7fe386ccb293 in /usr/lib/x86_64-linux-gnu/libc.so.6)


```
## To Reproduce

1.
1.
1.

```
import tempfile

import torch
import torch.distributed.rpc as rpc
import torch.multiprocessing as mp
import torch.nn as nn


def rpc_worker(rank, world_size, init_file, func):
    if torch.__version__.split('+')[0].split('.')[:3] == [1, 8, 0]:
        # Workaround for https://github.com/pytorch/pytorch/issues/53844
        options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file, _transports=["ibv", "uv"])
    else:
        options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file)
    for i in range(world_size):
        if i != rank:
            options.set_device_map("worker" + str(rank), {rank: i})
    rpc.init_rpc(
        "worker" + str(rank),
        rank=rank,
        world_size=world_size,
        backend=rpc.BackendType.TENSORPIPE,
        rpc_backend_options=options,
    )
    if rank == 0:
        func()
    rpc.shutdown()

def create_layer(device):
    return nn.Linear(4, 4).to(device)

def rref_func(rref):
    x = rref.to_here()
    print(x)
    return rpc.RRef(x)

def test_func():
    x = rpc.RRef(torch.randn(4,4).to(0))
    y = rpc.remote("worker1", rref_func, args=(x,))
    print(y.to_here())


if __name__ == "__main__":
    world_size = 2
    mp.spawn(rpc_worker, args=(world_size, tempfile.mkstemp()[1], test_func), nprocs=world_size)



```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

Collecting environment information...
PyTorch version: 1.9.0.dev20210322+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.9.0.dev20210322+cu111
[pip3] torch-pg==0.0.0
[pip3] torchprof==1.3.3
[pip3] torchvision==0.9.0.dev20210323+cu111
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.9.0.dev20210322+cu111          pypi_0    pypi
[conda] torch-pg                  0.0.0                     dev_0    <develop>
[conda] torchprof                 1.3.3                    pypi_0    pypi
[conda] torchvision               0.9.0.dev20210323+cu111          pypi_0    pypi

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma @pietern @zhaojuanmao @satgera @aazzolini @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by SciPioneer** [comment]
@beauby Seems to be relevant to cross-device type transfers you discussed last week. Could you please take a look?

Key error message: 
`RuntimeError('TensorPipe RPC backend only supports CPU tensors by default, please move your tensors to CPU before sending them over RPC, or call `set_device_map` on `TensorPipeRpcBackendOptions` to explicitly configure device mapping. Response device mapping is not available for destination worker1, but found tensor on device: cuda:0`

**Comment by lw** [comment]
@mrshenli Could you take a look at this? From the logs it appears that this is failing when transferring RRefs, and in particular when transferring them from `worker1` _to itself_. The code seems to complain that there is no device map set for `worker1` -> `worker1`.

Are users expected to always set such "loopback" device maps? And why is a "local" RRef transfer going through RPC? Maybe I misunderstood what's going on?

**Comment by msbaines** [comment]
> @mrshenli Could you take a look at this? From the logs it appears that this is failing when transferring RRefs, and in particular when transferring them from `worker1` _to itself_. The code seems to complain that there is no device map set for `worker1` -> `worker1`.
> 
> Are users expected to always set such "loopback" device maps? And why is a "local" RRef transfer going through RPC? Maybe I misunderstood what's going on?

My use-case is pipeline parallel. I send an RRef to the first stage in the pipeline via rpc.remote. I then take the output RRef and send it to the next stage also via rpc.remote. I tried to create a minimal repro here.

Here is the actual code:

https://github.com/facebookresearch/fairscale/blob/master/fairscale/experimental/nn/multiprocess_pipe.py

**Comment by msbaines** [comment]
In my minimal repro, the code is taking an RRef from worker0/cuda:0 and then passing it to worker1 via an rpc.remote. My expectation is that when the to_here call on the RRef is executed on worker1, the tensor should be transferred to worker1/cuda:1 due to the device_map I've set up.

**Comment by lw** [comment]
I don't know how RRefs work, my diagnosis was based on these two lines in the logs:
```
RuntimeError: On WorkerInfo(id=1, name=worker1):
RuntimeError('TensorPipe RPC backend only supports CPU tensors by default, please move your tensors to CPU before sending them over RPC, or call `set_device_map` on `TensorPipeRpcBackendOptions` to explicitly configure device mapping. Response device mapping is not available for destination worker1, but found tensor on device: cuda:0
```
Which seem to indicate the error is occurring on worker1, which is complaining it's missing a device map for worker1. I don't know how we got to that situation, hence this could just be a manifestation of an earlier bug.

**Comment by mrshenli** [comment]
I think it's because the device map was incorrectly setup. The following code:

```python
    for i in range(world_size):
        if i != rank:
            options.set_device_map("worker" + str(rank), {rank: i})
```

should be changed to:

```python
    for i in range(world_size):
        if i != rank:
            options.set_device_map("worker" + str(i), {rank: i})
```

Because `rank` is the current process, it's device map keys should be `f"worker{i}"` instead of `f"worker{rank}"`.

**Comment by mrshenli** [comment]
We probably should provide a utility function to print global device mappings. I would imagine it's easy to get device maps misconfigured with our current API.

**Comment by msbaines** [comment]
> We probably should provide a utility function to print global device mappings. I would imagine it's easy to get device maps misconfigured with our current API.

D'oh. That's exactly it! Thanks so much for looking into this.
