### ISSUE TITLE
ROCm not supported in PyPI release; can't select ROCm or CUDA in downstream projects as appropriate

### ISSUE THREAD

**Issue by interfect** [pytorch/pytorch#54570]
## 🚀 Feature

ROCm support should be in what you get from `pip install torch`, or from another package listing `torch` as a requirement.

## Motivation

If I'm writing (or running) downstream tools that use PyTorch, I don't care if it does its compute on an nVidia GPU via CUDA or on an AMD GPU via ROCm. I need just generic GPU-accelerated PyTorch as a dependency. Right now, with the ROCm version hosted separately, it seems impossible to have a `setup.py` that will depend on the version appropriate to the locally available hardware, plus I don't think anything in PyPI is allowed to depend on packages outside of PyPI and pull them in automatically.

## Pitch

The PyPI `torch` module should support both ROCm and CUDA in the same wheel, and ideally magically select whichever is appropriate to use at runtime.

## Alternatives

ROCm (and CUDA?) could be `[extras]`, so you could `pip install torch[rocm]`, `pip install torch[cuda]`, or, assuming the combination is actually possible, `pip install torch[rocm,cuda]`.

## Additional context

I saw PyTorch 1.8 added ROCm support, according to Phoronix. I `pip install torch`'d and got 1.8. I did not get ROCm support and was upset and confused.

It's also confusing that `pytorch.cuda` is where the ROCm-backed API lives when you are running on ROCm. I suppose that's necessary to run existing workloads, but the docs should then make it clear that the `cuda` module doesn't necessarily have anything to do with CUDA itself, depending on installation configuration. In reality, "ROCm" appears once in the 1.8 docs, [on the page about people in a heading](https://pytorch.org/docs/stable/community/persons_of_interest.html?highlight=rocm).

cc @ezyang @seemethere @malfet @walterddr @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by skyline75489** [comment]
I understand what you want, but sadly in the GPU world that's just not very realistic at the moment.

> I don't care if it does its compute on an nVidia GPU via CUDA or on an AMD GPU via ROCm

Well, you kinda have to. In order to utilize the GPU computing power, you'll need dedicated environment for the GPU setup. For example, you'll need to manually set up the nvidia driver for the GPU before you can use the torch-cuda package. Same story on the ROCm side. In fact you can't use ROCm on Windows because there's no driver available that provides ROCm functionally on Windows! 

In an ideal world we could have a "generic GPU-accelerated" PyTorch. But in the real world, drivers & related setup plays a vital role in how PyTorch works. 

Also Tensorflow has basically the same packaging strategy . See https://github.com/tensorflow/tensorflow#continuous-build-status

**Comment by interfect** [comment]
So what's the recommended packaging strategy/install instructions snippet for downstream tools? Would I have the README say something like "In your virtualenv, manually install pytorch with either `<CUDA install command>` for a CUDA backend or `<ROCm install command>` for a ROCm backend, and then `pip install -r requirements.txt`"? Should people install pytorch outside the project virtualenvs, at user or system level, and hope one version works with everything? Which backend would an Ubuntu `python-torch` package want to ship?

Linux people are used to jumping through hoops to install GPU drivers, so the CUDA/ROCm install process can probably stay bad, but not abstracting the difference away here means that each piece of end-user software is going to have to do it.

Right now, if I had to package up something portable, I would probably install both flavors in different virtualenvs and do some import wizardry to try and fetch out the appropriate one to actually import. But then I can't use pip properly for my application.

**Comment by gchanan** [comment]
yes, I think that's what you should do (@malfet can also chime in here).

You can find the commands to run for the specific choices at https://pytorch.org/.

**Comment by ezyang** [comment]
Hot take: because the hip version overloads the meaning of CUDA, it should be advertised as some sort of mutex and given a different package name

**Comment by seemethere** [comment]
We already experience issues with binary size with only CUDA 10.2 being included, adding ROCM to that same wheel would easily push us over the size limit for PyPI.

Unfortunately I don’t see a combined wheel happening any time soon given the restrictions we’ve been given to work with.

**Comment by hongxiayang** [comment]
There is no plan to have rocm supported wheel in PyPI.
