### ISSUE TITLE
How to specific a op qconfig in "prepare_jit" qconfig_dict

### ISSUE THREAD

**Issue by PenghuiCheng** [pytorch/pytorch#54583]
## ❓ Questions and Help
pytorch1.7/torchvision0.8.0

I want to use "prepare_jit" and "convert_jit" to quantize Resnet18. But I can't specific 'layer1.0.conv1' to different qconfig.
my code:
model = models.__dict__['resnet18] (pretrained=True)
model = torch.jit.script(model.eval())
qconfig1 = torch.quantization.QConfig(
                activation=torch.quantization.HistogramObserver.with_args(
                    reduce_range=False),
                weight=torch.quantization.default_per_channel_weight_observer)
torch.quantization.prepare_jit(model, {'layer1.0.conv1':qconfig1}, True)
model(torch.randn(1, 3, 224, 224))
torch.quantization.convert_jit(model, True, False)

But it will fail as below message:
File "/home/xxx/python3.7/site-packages/torch/quantization/quantize_jit.py", line 58, in _prepare_jit
    quant_type)
RuntimeError: __torch__.torch.nn.modules.conv.___torch_mangle_67.Conv2d (of Python compilation unit at: 0x56088f811c00) is not compatible with the type __torch__.torch.nn.modules.conv.___torch_mangle_66.Conv2d (of Python compilation unit at: 0x56088f811c00) for the field 'conv1'

It seems the key 'layer1.0.conv1' is not correct.
How can I do?

cc @gmagogsfm

**Comment by supriyar** [comment]
From https://discuss.pytorch.org/t/how-to-specific-a-op-qconfig-in-prepare-jit-qconfig-dict/115800/3?u=supriyar
prepare_jit/convert_jit is no longer being maintained, for automatic quantization please try fx graph mode quantization: (prototype) FX Graph Mode Post Training Static Quantization — PyTorch Tutorials 1.8.0 documentation

if you encounter problems with symbolic tracing, you can take a look at: (prototype) FX Graph Mode Quantization User Guide — PyTorch Tutorials 1.8.0 documentation
