### ISSUE TITLE
Problem about using "deepcopy(model)"

### ISSUE THREAD

**Issue by WindVChen** [pytorch/pytorch#54580]
I find a weird phenomenon when debugging programs these days !
I want to use "deepcopy(model)", but when there is any assignment of Class Variable like "self.x = XXX", the program will break and give the error "Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment".
When I change the "self.x=XXX" to "x=XXX", all is OK. 
I try to find why it happens but failed.
Any helpful reply are appreciated.

**Comment by ailzhang** [comment]
Can you provide a minimal repo please? Thanks!

**Comment by WindVChen** [comment]
@ailzhang Of course. Here is a simple code example to show the above problem:

```
import torch
import torch.nn as nn
from copy import deepcopy

class test(nn.Module):
    def __init__(self):
        super(test, self).__init__()
        self.con1 = nn.Conv2d(1, 2, 3)
        self.con2 = nn.Conv2d(2, 1, 3)

    def forward(self, x):
        if True:
            return self.func(x)

    def func(self, x):
        self.exp = None
        x = self.con1(x)
        x = self.con2(x)
        self.exp = x
        return self.exp

model = test().cuda()
input = torch.Tensor(1,1,16,16)
output = model(input.cuda())
copyModel = deepcopy(model)
print("")
```

 When running the code, you will find the error like this:
![image](https://user-images.githubusercontent.com/56162412/112573073-7fdca480-8e26-11eb-8c25-6614ed7337d4.png)

And when change all "self.exp"  to "exp". It will work.

**Comment by ailzhang** [comment]
@WindVChen This is expected, by setting `self.exp = x` when `x` is graph intermediate (requires_grad=true and is_leaf=false), it's currently not allowed to deepcopy them. 
oYou can work around the problem by calling `self.exp = x.detach_()` which will make it saving a leaf tensor (instead of all of grad_fn).
Closing as resolved, but feel free to reopen if you have further questions. Thanks!

**Comment by WindVChen** [comment]
@ailzhang Thanks for your reply. There is another question. When I comment "input = torch.Tensor(1,1,16,16)" and "output = model(input.cuda())", why it can work.
