### ISSUE TITLE
Support nn.Module.to(..., copy_data=False)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54600]
The motivation is that we are going to support allocating nn.Modules on meta device, and you cannot "convert" a tensor from meta to cpu (because the data is unspecified). But sometimes it's still useful to inplace transmute the parameters from meta to cpu. `copy_data=False` would let you do this transmutation, while also acknowledging that the old data doesn't get preserved (in the case of meta, this is because it doesn't exist, but in the case of other devices, we would just not copy).

cc @albanD @mruberry @jbschlosser

**Comment by ezyang** [comment]
cc @jbschlosser

**Comment by SsnL** [comment]
Could there be a better name like `copy_data=False`? `no_copy` feels that not copying the python project which is already the current behavior.

**Comment by ezyang** [comment]
Sure, title amended.

**Comment by gchanan** [comment]
This seems pretty different from `copy` in `Tensor.to` and I'm not sure what the semantics of something like `Module.to('cpu').to('cpu')` would be.

Is there any use case outside of meta tensors?

**Comment by ezyang** [comment]
Well, because this is a new kwarg, your exact example would behave exactly the same as it did before. If you ask `Module.to('cpu', copy_data=False).to('cpu', copy_data=False)`, well, this operation is idempotent, so it's the same as `Module.to('cpu, copy_data=False)`, which gives you a module with all the parameters otherwise uninitialized.

I can't really think of a use case outside of meta tensors.

**Comment by gchanan** [comment]
err, I guess I thought copy_data would be true by default because that's the usual semantics with Modules (sort of, it depends on if you are changing devices).

But, why would you want to do this in the first place?  Why not just recreate the module on a different device, assuming we have something like https://github.com/pytorch/pytorch/pull/54508?

**Comment by albanD** [comment]
> err, I guess I thought copy_data would be true

It would be True by default. My understanding of the title is that we should allow to set this to False when needed.


Note that it could be useful beyond "meta" usecase if you work with a Module that does not support the "device" argument. And you want to move things to a different device and initialize there. You might want to move the Module without copying any data.

**Comment by jbschlosser** [comment]
@gchanan what you're saying is that right now `to()` essentially has implicit default `copy_data=True` behavior for tensors and default `copy_data=False` behavior for modules? And trying to make that arg explicit will either result in inconsistencies between the two OR result in extra copies for the module case?

I think that's a good point. Btw for extra context, the failing test @ezyang brought up that led to this idea is here:
```
size = 4096 + tail_size
a = torch.randn(size, device=device, dtype=dtype)
b = torch.randn(size, device=device, dtype=dtype)
c = a + b
for x, y, z in zip(a.tolist(), b.tolist(), c.tolist()):
    self.assertEqual(x + y, z)
```

This test fails for `device='meta'`. `tolist()` moves to the CPU first if necessary, which should result in garbage (considering meta semantics where going from meta -> CPU is similar to calling `torch.empty()`; i.e. uninitialized storage is allocated).

It's confusing, but now that I think about it more, there's nothing in the meta semantics that claim the statement `c = a + b` results in c relating to a and b in any particular way outside of shape. So maybe this is okay to fail?

**Comment by ezyang** [comment]
> what you're saying is that right now to() essentially has implicit default copy_data=True behavior for tensors and default copy_data=False behavior for modules?

Hol up, no I don't think that's what Greg is saying at all. It's important to distinguish `copy_data` (the new concept we are proposing here) to the existing concept `copy` (existing on Tensor.to) (and by the way, I do agree this is kind of confusing which suggests `copy_data` is a bad name for this kwarg).

The existing copy kwarg simply controls whether or not, if the conversion is a no-op, we skip the copy or not. For `meta -> cpu`, this question would never be relevant.

**Comment by ezyang** [comment]
Maybe a better name that captures the correct gist is "like". We have `ones_like` which will give you a Tensor that has the same size and options as the original, but the options are overrideable and the data is never preserved. `like=True` is confusing though; maybe something like `Module.empty_like` as an entirely separate method.

**Comment by jbschlosser** [comment]
I like the idea of `Module.empty_like()`, but wouldn't it be equivalent to recreating a module on a different device, running into the same problem of not having the constructor args?

```python
m1 = MyModule(device='meta')
m2 = Module.empty_like(m1, device='cpu')  # How would this be implemented?
```

**Comment by ezyang** [comment]
Implementation wise, it would still be implemented in the same way that `to` is implemented. (Also, concretely, I suggest `m1.empty_like(device='cpu')`

**Comment by ezyang** [comment]
It would mutate, but it is no different from `m.cpu()` which mutates the module inplace (compared to `tensor.cpu()` which gives you a new copy of tensor)

**Comment by jbschlosser** [comment]
I swear I'm not trying to cause endless bikeshedding, but it's confusing to me since other `_like` functions read "empty like \<thing\>", "ones like \<thing\>", "zeros like \<thing\>", etc. and the \<thing\> for the proposed case is on the left-hand side.

What about `m.empty(device='cpu')`? I could imagine an in-place analogue of `Tensor.empty_()` making sense if that was useful.

**Comment by gchanan** [comment]
I guess if you wanted something as close to the Tensor API as possible (`torch.empty_like(my_tensor, device='cpu')`) you could do something like (`Module.empty_like(my_module, device='cpu')` but the weirdness around Module transformations being implicitly inplace is kind of glaring there.

**Comment by jbschlosser** [comment]
@gchanan I agree about the inplace weirdness. What are your thoughts on the inplace `m.empty(device='cpu')` along the lines of `m.cpu()`? I think Ed's okay enough with it

**Comment by gchanan** [comment]
it's not the worst :).  I'd still like to see what an end-to-end workflow looks like.

**Comment by jbschlosser** [comment]
> it's not the worst :). I'd still like to see what an end-to-end workflow looks like.

For the simple "skip init" use case (https://github.com/pytorch/pytorch/issues/29523):
```python
import torch

m = torch.nn.Sequential(
  torch.nn.Linear(5, 5, device='meta'),
  torch.nn.Linear(5, 1, device='meta')
)
m.empty(device='cpu')

# Do custom init...
```

@gchanan It's not a full solution for the distributed use case(s), but it covers the part of materializing a meta module onto a specified device, which I think will be necessary as a component of the broader distributed workflow (given that the constructor args aren't available for recreating the module onto a specific device).

For cross-device modules, there's still the issue of cross-device communication in `forward()` to deal with (one possibility is using FX to insert cross-device synchronization calls, since the module can be traced once it has been instantiated with the meta device). I think a mechanism for materializing from meta -> device will be needed independent of that.

**Comment by jbschlosser** [comment]
@ezyang @gchanan There are some tests that specifically create submodules named `empty`. If we consider the presence of cases like this within test code as a canary for things that are done in OSS code, it's probably best to pick a different name to avoid conflicts. I'll throw some out there that fit with the pre-established `empty` nomenclature related to uninitialized values:
* `m.to_empty(device='cpu')`
* `m.empty_to(device='cpu')`
* `m.to(device='cpu', empty=True)`
* `m.as_empty(device='cpu')`
* `m.empty_on(device='cpu')`

**Comment by ezyang** [comment]
I'd vote for `to_empty`
