### ISSUE TITLE
data_source parameter in initializer of Sampler

### ISSUE THREAD

**Issue by gncs** [pytorch/pytorch#54603]
What is the purpose of the `data_source` argument in the initializer of the `Sampler` base class?
See [here](https://github.com/pytorch/pytorch/blob/f9ca0d87a7cd2afb3ae5866acf7a77af54c5ab91/torch/utils/data/sampler.py#L20). Thank you!

**Comment by ailzhang** [comment]
Hi, please redirect all questions to pytorch forum instead. Thanks!
