### ISSUE TITLE
Rework how symbolic override works

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5460]
Motivation: we want to write all of our traces like this:

```python
    def f_symbolic(g, val1, val2, bool_flag):
        return g.op("F", val1, val2)

    @symbolic(f_symbolic)
    def f(var1, var2, bool_flag):
        ...
        return ...
```

How it improves over the current situation:

- We want to STOP inlining the "is-tracing" test.  This is
  implementation details and we don't want it splattered all over
  userspace.
- We want to be able to wrap functions which take non-Variable
  arguments (such that you aren't induced to do refactors
  like in https://github.com/pytorch/pytorch/pull/5420 ).

Current call sites:
- RNNs `torch/nn/_functions/rnn.py`  (this site is special, cannot
  instrument function because there is a factory)
    - It would probably suffice to instrument CudnnRNN and
      AutogradRNN separately
- `pack_padded_sequence` (inlined "is-tracing" test)
    - I don't understand, this seems to pass non-Variable through?
      (did it just not work???)
- `pad_packed_sequence`
- `instance_norm`. This is done as inner function.
    - We need the defaults; handle this using getargspec
    - We want some operations handled outside (so we get tracing
      for them automatically).  This is legit (but don't do
      inner function.)
    - (Ditto, seems to use attributes)

Experiment:
- How much is the decorator overhead?  If it is trivial, stop inlining
  decorator test.

Constraints:
- Some functions may pass Variables in non-trivial data structures
  (not possible to write *generic* argument parser which can unambiguously
  identify all variables).  But this is not the common case.

CC @anderspapitto

**Comment by apaszke** [comment]
If the decorator is supposed to return that checks the `_tracing` flag before it goes on to check inputs, and then dispatches to the main implementation then the overhead should be negligible (especially compared to the improvement in readability). I don't think we're using non-standard data structures a lot

**Comment by dzhulgakov** [comment]
So `torch.onnx.symbolic_override` does exactly that. Decorator overhead is tiny (except for rnn case because of the factory). And yep, untying circular dependencies would be awesome.

**Comment by ezyang** [comment]
This is obsolete. Also decorator overhead is actually kind of expensive, as we discovered in torch function
