### ISSUE TITLE
[docs] Wording about onesided argument in torch.stft docs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#54631]
It has `onesided = None` in signature. And then this passage: `When onesided is the default value True,` - not sure what it means

cc @brianjo @mruberry @peterbell10 @walterddr

**Comment by mruberry** [comment]
cc @peterbell10 to take a look. I also owe @peterbell10 a follow-up on some deprecations issue (including for torch.stft())!
