### ISSUE TITLE
Reordering dimensions of a tensor converted from numpy array is problematic

### ISSUE THREAD

**Issue by siyuhsu** [pytorch/pytorch#54650]
## To Reproduce

1.create a numpy array and a tensor
2.convert the numpy array to a tensor that has the same shape as the tensor in step1
3.add the converted tensor and the tensor in step1

```
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
>>> a
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
>>> b = torch.zeros((4, 2))
>>> b
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
>>> a_tensor = torch.from_numpy(a).permute(1, 0)
>>> a_tensor
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
>>> c = a_tensor + b
>>> c
tensor([[1., 3.],
        [5., 7.],
        [2., 4.],
        [6., 8.]])
```

## Expected behavior

The values of `c` should be equal to `a_tensor`.

## Environment

PyTorch version: 1.3.0
Is debug build: False
CUDA used to build PyTorch: 10.1.243
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1a0+d94043a
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.0.14           py36ha843d7b_0  
[conda] mkl_random                1.1.0            py36hd6b4f25_0  
[conda] numpy                     1.17.2           py36haad9e8e_0  
[conda] numpy-base                1.17.2           py36hde5b4d6_0  
[conda] pytorch                   1.3.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py36_cu101    pytorch

## Additional context

Same issue to https://github.com/pytorch/pytorch/issues/54493

**Comment by skyline75489** [comment]
I can't repro this with PyTorch 1.8:

```python
>>> import numpy as np
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
>>> a
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
>>> import torch
>>> b = torch.zeros((4, 2))
>>> b
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
>>> a_tensor = torch.from_numpy(a).permute(1, 0)
>>> a_tensor
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]], dtype=torch.int32)
>>> c = a_tensor + b
>>> c
tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])
```

**Comment by siyuhsu** [comment]
> I can't repro this with PyTorch 1.8:
> 
> ```python
> >>> import numpy as np
> >>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
> >>> a
> array([[1, 2, 3, 4],
>        [5, 6, 7, 8]])
> >>> import torch
> >>> b = torch.zeros((4, 2))
> >>> b
> tensor([[0., 0.],
>         [0., 0.],
>         [0., 0.],
>         [0., 0.]])
> >>> a_tensor = torch.from_numpy(a).permute(1, 0)
> >>> a_tensor
> tensor([[1, 5],
>         [2, 6],
>         [3, 7],
>         [4, 8]], dtype=torch.int32)
> >>> c = a_tensor + b
> >>> c
> tensor([[1., 5.],
>         [2., 6.],
>         [3., 7.],
>         [4., 8.]])
> ```

Yes, I used other versions(1.2.0, 1.3.0, 1.3.1, 1.6.0) of PyTorch, only `1.3.0` have this problem. if I define the data type of numpy array as `np.float`, I will get the right result. But it is still unnormal. 

Anyway, the problem is solved, and I will move on after this. 

Thank you, Liu!

PyTorch 1.3.0:
```python
>>> import torch
>>> import numpy as np
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.int)
>>> b = torch.zeros((4, 2))
>>> a_tensor = torch.from_numpy(a.transpose(1, 0))
>>> c = a_tensor + b
>>> c
tensor([[1., 3.],
        [5., 7.],
        [2., 4.],
        [6., 8.]])
```
```python
>>> import torch
>>> import numpy as np
>>> a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float)
>>> b = torch.zeros((4, 2))
>>> a_tensor = torch.from_numpy(a.transpose(1, 0))
>>> c = a_tensor + b
>>> c
tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]], dtype=torch.float64)
```

**Comment by skyline75489** [comment]
No problem. Glad you have a working solution. Also glad that you know how to ask a question now 😉
