### ISSUE TITLE
`@torch.jit.ignore` and `@property`

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pytorch/pytorch#54688]
## 🚀 Feature
Currently there does not appear to be any way to `@torch.jit.ignore` an `@property` on a module that is not compatible with TorchScript. Sometimes a `Module` may expose some (derived object of) its initialization arguments as immutable `@property`s, but those objects may be incompatible with TorchScript.

## Motivation

```python
In [1]: import torch

In [9]: class M(torch.nn.Module):
   ...:     @property
   ...:     def func(self):
   ...:         return lambda x: x * 2
   ...: 

In [10]: m = M()

In [11]: m.func(2)
Out[11]: 4

In [12]: ms = torch.jit.script(m)

UnsupportedNodeError: Lambda aren't supported:
  File "<ipython-input-9-4ec6558e83af>", line 4
    @property
    def func(self):
        return lambda x: x * 2
               ~ <--- HERE

In [13]: class M(torch.nn.Module):
    ...:     @torch.jit.ignore
    ...:     @property
    ...:     def func(self):
    ...:         return lambda x: x * 2
    ...: 

RuntimeError: Argument to @torch.jit.ignore must be a bool or a function but got <property object at 0x7f1393a5f130>

In [14]: class M(torch.nn.Module):
    ...:     @property
    ...:     @torch.jit.ignore
    ...:     def func(self):
    ...:         return lambda x: x * 2
    ...: 

In [15]: m = M()

In [16]: m.func(2)
Out[16]: 4

In [17]: ms = torch.jit.script(m)

UnsupportedNodeError: Lambda aren't supported:
  File "<ipython-input-14-e11b332e46b5>", line 5
    @torch.jit.ignore
    def func(self):
        return lambda x: x * 2
               ~ <--- HERE
```

## Pitch

Add support for `property` objects to `@torch.jit.ignore`

**OR**

Just ignore all `@property`s in TorchScript (possibly unless they are decorated with `@torch.jit.export`.)

## Alternatives

One can remove `@property`s from the module and use normal, mutable attributes instead. (Requires source changes.) This approach is still incompatible with type-annotated attributes, see #53753. 

Explicit callable getter methods also work fine:
```python
In [14]: class M(torch.nn.Module):
    ...:     def func(self):
    ...:         return lambda x: x * 2
```

cc @gmagogsfm

**Comment by SplitInfinity** [comment]
See #45261. Supporting `@ignore` for `@property` is nontrivial because of how `ScriptModules` are created (properties cannot be dynamically attached to a class***). But we do support `@unused` for properties.

**Comment by SplitInfinity** [comment]
`@ignore` = cannot run in TorchScript and is executed in Python if called, disables export
`@unused` = cannot run in TorchScript nor Python and throws an error if called
