### ISSUE TITLE
Issue when using padding token as input to the network

### ISSUE THREAD

**Issue by shagunsodhani** [pytorch/pytorch#5472]
I have a straightforward use case. Given a token (or word), lookup the embedding of the word, pass that through a linear layer and perform L2 regression. If the token corresponds to the `padding_idx` of the embedding layer, `loss.backward()` throws an error saying `RuntimeError: invalid argument 3: Index is supposed to be a vector at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:248`

- OS: macOS High Sierra
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): Tried both conda and pip
- Python version: 3.6.4
- CUDA/cuDNN version: CPU
- GPU models and configuration: NA
- GCC version (if compiling from source): NA
- A script to reproduce the bug: [Available here](https://gist.github.com/shagunsodhani/4b043d897a7d39903ae5e396994e9c84)

**Comment by johnsenliu** [comment]
I got the same trouble, though it throw this error after some epochs of training. Does anyone have some solutions?
