### ISSUE TITLE
How to release unnecessary tensor which occupys memory when executing inference at test phrase?

### ISSUE THREAD

**Issue by shoutOutYangJie** [pytorch/pytorch#54758]
## ❓ Questions and Help
I have a memory-cost operation, I put this operation into a function like this:
```
class xxx(nn.Module):
    def forward(xxx):
        xxx = self.cost_memory_function(xxx)
        ...  # OOM error occurs here rather than at the above function.
        return xxx
    def cost_memory_function(xxx):
        ...
```
But If the tensors generated from the function "cost_memory_function" release, the next part should successfully run. So I guess the tensors at function "cost_memory_function"  still occupy memory even though the function has exited. 
So I want to know how to release some tensors which is unnecessary. I have set "torch.set_grad_enable" as False.

**Comment by ezyang** [comment]
There are a few possibilities here:
1. You have accidentally retained the memory from cost_memory_function somehow. In that case, `del` ing the tensors wherever they are will help. If xxx is a view into a large tensor, `clone()` ing it can help. Or if there is a reference cycle that means refcount doesn't notice the tensors are dead, you could run gc.collect()
2. The allocations from the function have fragmented the heap, and now you no longer can get the memory. https://github.com/pytorch/pytorch/pull/44742 might help you there
Unfortunately we can't really help you more than that here. The forums may be able to give more detailed advice
