### ISSUE TITLE
I wonder if I need to reset optimizer function when network structure is changed?

### ISSUE THREAD

**Issue by dbsxdbsx** [pytorch/pytorch#54765]
Pytorch 1.7
I need to change pytorch network structure in my project during training . Like this:
```
net1 = Net() # 1st network
optimizer = optim.Adam(net1.parameters(), lr=3e-2) #TODO: check if need reset  after change net structure

print("================================================")
# some other code......

net1 = Net2()  # another network
# I don't know if the below code is requried again?
optimizer = optim.Adam(net1.parameters(), lr=3e-2)
do training with gradient descent...
```
I found this is workable with no error, but I am not quite sure if the optimizer would optimize EXACTLY with the 2ed network without resetting optimizer agian?

cc @vincentqb

**Comment by ezyang** [comment]
You need to reinitialize the optimizer; otherwise it doesn't know anything about the new nets parameters.

**Comment by dbsxdbsx** [comment]
thanks.
