### ISSUE TITLE
RRef.to_here() does not synchronize CUDA Streams properly 

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#54771]
@pbelevich reported that when calling `rref = rpc.remote("dst", model.forward)` with CUDA RPC on an expensive model, the following `rref.to_here()` might not fetch the correct result. This is because  `rpc.remote` and `rref.to_here` are two separate request/response pairs and they don't share CUDA streams. So, with our current implementation, `rref.to_here` might read the result before it's ready.

### Proposed Fix

I am thinking about passing a list of devices when invoking the RPC request callback. Then `rpc.remote` related processors can retrieve that list and record one `CUDAEvent` on each device and store those `CUDAEvent`s on the RRef. Later, when `rref.to_here()` is executed on the callee, the RRef can use the recorded `CUDAEvent`s to block current streams on those devices. 

https://github.com/pytorch/pytorch/blob/1126d51de9d9b69fe727fd6b5f2c4ef0443cbc6c/torch/csrc/distributed/rpc/tensorpipe_agent.cpp#L801

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by lw** [comment]
Yeah the idea of storing CUDA events on the RRef makes sense to me. Although it must be said that I know nothing about RRefs so I don't know if other approaches could suit better.

As for passing the devices to the callback, I am guessing that this is in order to avoid the callback itself having to inspect the value and extract the devices it uses, right? (And we know that inspecting a value is not easy) If so then, yes, I think passing a set of devices to the callback could make sense. Just to clarify though: this would be just a change in an internal API, it wouldn't mean that all end users will now need to expect an extra argument in their Python functions too right?

**Comment by mrshenli** [comment]
> Just to clarify though: this would be just a change in an internal API, it wouldn't mean that all end users will now need to expect an extra argument in their Python functions too right?

Exactly, no change to user-facing API. 

> As for passing the devices to the callback, I am guessing that this is in order to avoid the callback itself having to inspect the value and extract the devices it uses, right?

Right, since the agent already has a list of devices, I thought it might be easier to just reuse those. 

Thanks for the inputs!

**Comment by mrshenli** [comment]
@pbelevich here are some more details on how we can fix this issue:


## High-Level Idea

The `ctx` in the following code is an instance of `CudaLazyStreamContext` when CUDA is enabled. Its `streams_`
field holds the devices and current streams where this request will be run on. The proposed solution is to 
extract the devices vector from the `ctx` and pass that to `cb_->operator()(requestMessage);` invocation, and 
then propogate it to the created `RRef` accordingly.

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/tensorpipe_agent.cpp#L794-L802

`CudaLazyStreamContext` is implemented here:

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/tensorpipe_utils.h#L67-L120

The `operator()(requestMessage)` is defined here:

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback.h#L15

The call trace is `processMessage` -> `processRpcWithErrors` -> `processRpc` -> `processBaseScriptRemoteCall` / `processPythonRemoteCall`. See the following code. 

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback.cpp#L18

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback_no_python.cpp#L572

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback_no_python.cpp#L597-L604

We can start with the `processPythonRemoteCall` one. This one handles Python user functions, and `processBaseScriptRemoteCall` handles `TorchScript` user functions.

The program will then hit the following function, which creates the owner RRef.

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback_impl.cpp#L318

What we need to do is that, before we set a value on the RRef, we need to record a `CUDAEvent` from the current stream on all participating devices in the context. And record the events in the OwnerRRef. 


Later, when `RRef.to_here()` is called, the program will reach the following function through a similar path:

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback_impl.cpp#L388

Before we mark the `responseFuture` as completed, we need to use the recorded `CUDAEvent` on the owner RRef
to block current streams in each of the participating device.

https://github.com/pytorch/pytorch/blob/78c771cac7aaf2af9ef299be10e384c9eac99eb8/torch/csrc/distributed/rpc/request_callback_impl.cpp#L414-L415


## Changes in the Build System

Since now a few more files need to call CUDA operations, we might need to pass `USE_CUDA_NO_ROCM` to those files accordingly. This is how we did that to `tensorpipe_agent.h`: https://github.com/pytorch/pytorch/commit/d9c76360b2b915639fa63b0af29fd6faee045557 . We need to make sure that the same code can still compile and run when there is no GPUs. 

## How to Propagate Device List

A simplest solution might be adding one more arguments to functions like `processRpc` to pass the device list. There might be cleaner ways. E.g., we can extract the `CudaLazyStreamContext` implementation from `tensorpipe_utils.h` and move that to a general util file and then directly pass `shared_ptr` of the context around. And all stream management can then still be wrapped with in the `CudaLazyStreamContext`  implementation. Open to better suggestions.
