### ISSUE TITLE
Bug affecting CUDA deallocation if PYTORCH_NO_CUDA_MEMORY_CACHING=1 

### ISSUE THREAD

**Issue by danpovey** [pytorch/pytorch#54770]
Here
https://github.com/pytorch/pytorch/blob/5e62da2efde1ad5fe96194b79435aac7443dfbad/c10/cuda/CUDACachingAllocator.cpp#L1202
it does:
```
  DeleterFnPtr raw_deleter() const override {
    return &raw_delete;
  }
```
... I think it should be something like:
```
  DeleterFnPtr raw_deleter() const override {
    if (forceUncachedAllocator()) {
       return &uncached_delete;
   } else {
       return &raw_delete;
   }
  }
```
hopefully someone can check this and make a PR.  If I do one myself it will be delayed because I need to get lawyers involved to sign the CLA.

cc @ngimel

**Comment by danpovey** [comment]
... most likely this does not affect actual PyTorch code because it does not make use of this interface, but that function is supposed to return the appropriate deleter function, and this bug means things won't work right from C++ code that makes use of that feature, if  PYTORCH_NO_CUDA_MEMORY_CACHING=1/

**Comment by ezyang** [comment]
Oops, yeah, this sounds like a bug.
