### ISSUE TITLE
Improve DDP C++ RuntimeError messages by including parameter name

### ISSUE THREAD

**Issue by stevebyan** [pytorch/pytorch#54795]
## 🚀 Feature

Add support for users to attach parameter names to the tensor and thus make the names available to the C++ back-propagation code. Modify selected DDP C++ RuntimeError messages to include the parameter name of the tensor that triggered the error. 

## Motivation

The error messages from the C++ layer of PyTorch Distributed Data Parallel (DDP) are less helpful than they could be, as they are unable to name the specific parameter which triggered the error. For example:
`RuntimeError: Expected to mark a variable ready only once.`
rather than something like:
`RuntimeError: Variable decoders.2.1.response_decoder.layer_0.ff.weight: Expected to mark a variable ready only once.`

Another similar error message is:
`RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss.`
It would be really helpful to report the names of the parameters that were not used in producing loss.

## Pitch

I've modified PyTorch to enable the user to attach the model parameter names to the Variable portion of the tensors (the AutogradMeta struct) so that the C++ code can access the parameter name for use in error messages, and modified the first error message above to include the parameter name.

## Alternatives

I'm open to suggestions. Trolling though the torchviz graphs really didn't give me enough insight to find my problem.

## Additional context

In my implementation, I planned to add a new `parameter_name` member to `struct AutogradMeta`, but I ended up hacking it to re-use the existing `name` member. I gather this would probably break the JIT and Caffe2.

It would be preferable to not require the user to explicitly add the parameter names to the tensors, but the full parameter name isn't known until after the user has constructed the full model. Perhaps the first forward pass could add the annotations?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
There is a plan to address this as part of: https://github.com/pytorch/pytorch/issues/47648. Although, the plan doesn't involve adding any annotations to the Tensor, the idea is to pass parameter names as a separate struct to the DDP C++ engine so that it can have a 1:1 mapping from name to parameter.

cc @rohan-varma

**Comment by rohan-varma** [comment]
As @pritamdamania87 mentioned, we have a plan to enable this by taking the fully qualified parameter name (combination of module_name:parameter_name as given by named_modules() and named_parameters()) and passing that into C++ DDP. Given that mapping, we can find the appropriate parameter names when reporting the error.

**Comment by rohan-varma** [comment]
https://github.com/pytorch/pytorch/pull/55075

**Comment by stevebyan** [comment]
Thanks, #47648 will address this nicely. I'm glad to hear it's in the works. I'm sorry I didn't find it when searching before submitting this issue.

**Comment by rohan-varma** [comment]
We've added this feature in TORCH_DISTRIBUTED_DEBUG=DETAIL, so closing this out.
