### ISSUE TITLE
Feature request: add LDL decomposition

### ISSUE THREAD

**Issue by rfeinman** [pytorch/pytorch#54847]
## 🚀 Feature
I would love to see a pytorch implementation of LDL (Bunch-Kaufman) decomposition.

## Motivation

LDL is a great alternative to Cholesky for symmetric/hermitian matrices that are not positive definite. At the moment, pytorch's only alternative factorization for hermitian matrices is eigendecomposition (e.g. `torch.symeig` and `torch.linalg.eigh`). In my experience, eigh is much slower and does not scale to batch as Cholesky does (and as LDL in theory should).

## Pitch

LDL can be implemented using LAPACK's `sytrf` and `hetrf` routines (a la [scipy.linalg](https://github.com/scipy/scipy/blob/v1.6.1/scipy/linalg/_decomp_ldl.py#L12-L154)). For CUDA, there is a working implementation in the cuSolver library.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
Do you have a sample use case?

**Comment by IvanYashchuk** [comment]
Link to SciPy documentation of Bunch-Kaufman decomposition ([scipy.linalg.ldl](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html)).

Matlab also calls this function [`ldl`](https://www.mathworks.com/help/matlab/ref/ldl.html), Julia uses [`bunchkaufman`](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.bunchkaufman) name.

Bunch-Kaufman decomposition has the same use case as Cholesky decomposition (https://en.wikipedia.org/wiki/Cholesky_decomposition#LDL_decomposition), but Bunch-Kaufman can be applied to a broader class of matrices (but still only symmetric/Hermitian).

cuSOLVER has this decomposition available [`cusolverDn<t>sytrf()`](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDN-lt-t-gt-sytrf).

From a quick google search, I didn't find references for derivative rules, but it's probably not a difficult task to derive it.

**Comment by rfeinman** [comment]
Simple use case: solving systems of linear equations when the matrix is Hermitian but not positive definite.

At some point it would be nice to have a general `solve` utility that sets the factorization strategy based on properties of the input matrix (see e.g. [scipy.linalg.solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html) or [Matlab's flowchart](https://www.mathworks.com/help/matlab/ref/mldivide.html#bt4jslc-6)).

**Comment by turbotage** [comment]
@mruberry, I think the use cases @rfeinman mentions are more than enough! For me the use case is in nonlinear optimization. In methods similar to Descent-Newton the Hessian may fail to be positive definite. In these cases the **LDL** decomposition of the Hessian is extremely useful. By suitably modifying the possibly negative elements in **D** an approximate Hessian may be found and therefore possibly a suitable descent step.

A method similar to [cholesky_ex](https://pytorch.org/docs/stable/generated/torch.linalg.cholesky_ex.html) would be perfect. The information of when a decomposition has failed all together is important but as I find batching extremely important I don't wan't one bad decomposition to ruin the computation of all batches.

Also, I am quite new to torch, but if an implementation of this is to be released in the future, can one be sure that it will be available both in c++ (libtorch) and in pytorch? For me, the c++ version is most important but I guess if it ends upp in c++ it will probably end up in pytorch also?

**Comment by mruberry** [comment]
Thank you @turbotage, I agree it'd be great to offer this functionality.

Yes we typically add operators to both the Python and C++ APIs.

**Comment by nikitaved** [comment]
That is a great function to have indeed! As a follow-up it would also make sense to have an `ldl_solver` function which could be more stable of a solver than `cholesky_solve`.
