### ISSUE TITLE
jit::load failed in debug mode with vs2019 and libtorch 1.8 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by agamemnon314** [pytorch/pytorch#54845]
I'm trying to use libtorch to load a pretrained model as a subproblem optimizer within a relatively large c++ project. 
The issue is very strange. When I create a isolated VS2019 project for the ml-related classes. I can build and run for both release and debug mode. But once I include the ml-related classes into the large c++ project, it's all right for the relase mode, but the jit::load does not work in debug mode. I always get :
0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF

It's just simply loading a pt file. 
torch::jit::load(folderPath + "/init_embed.pt");

I've read many related issues. I found CMake is aways recommended. But I found it's too hard to conerting an existing large VS project into a CMake project

cc @gmagogsfm

**Comment by nikithamalgifb** [comment]
@agamemnon314 : Can you please attach the .pt for the issue? Also providing a small minimal reproducer on how the `init_embed.pt` was generated would help us debug the issue.
