### ISSUE TITLE
CPU QR decomposition stuck in multi-machine DDP and RPC context

### ISSUE THREAD

**Issue by garrett4wade** [pytorch/pytorch#54842]
## 🐛 Bug

Hi, I tried to initialize my model, say, `torch.nn.Linear`, in **multi-machine** DDP and RPC context. When I use orthogonal initialization on CPU, it stucks at  `torch.qr` step [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/init.py#L455). The same problem remains for `torch.linalg.qr`.

However, if the model is loaded into GPU first and then initialized using `torch.nn.init.orthogonal_`, everything is fine.
It also works fine in single-machine setting or before DDP and RPC initialization.

## To Reproduce

```python
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed import rpc


def run(rank, world_size):
    # multi-machine setting
    rpc_init_method = 'tcp://HEAD_IP_ADDRESS:PORT'
    ddp_init_method = 'file:///dev/shm/ddp'

    # say, TRAINER_NUMBER = GPU_INFERENCE_SERVER_NUMBER = 1, using 1 GPU respectively
    if rank < TRAINER_NUMBER:
        # trainer to optimize model
        dist.init_process_group('nccl', init_method=ddp_init_method, rank=rank, world_size=GPU_NUM_FOR_TRAINING)

        rpc_opt = rpc.TensorPipeRpcBackendOptions(init_method=rpc_init_method, rpc_timeout=300)

        rpc.init_rpc('trainer_' + str(rank), rank=rank, world_size=world_size, rpc_backend_options=rpc_opt)

        some_tensor = torch.randn(4, 4).cuda()
        # works fine
        q, r = torch.qr(some_tensor)
        # stuck here
        q, r = torch.qr(some_tensor.cpu())

        dist.destroy_process_group()
    elif rank >= TRAINER_NUMBER and rank < TRAINER_NUMBER + GPU_INFERENCE_SERVER_NUMBER:
        # inference server to collect observation from workers and provide action
        rpc_opt = rpc.TensorPipeRpcBackendOptions(init_method=rpc_init_method, rpc_timeout=300)

        rpc.init_rpc('agent_' + str(rank), rank=rank, world_size=world_size, rpc_backend_options=rpc_opt)

        some_tensor = torch.randn(4, 4).cuda()
        # works fine
        q, r = torch.qr(some_tensor)
        # stuck here
        q, r = torch.qr(some_tensor.cpu())
    else:
        # workers for env simulation
        rpc_opt = rpc.TensorPipeRpcBackendOptions(init_method=rpc_init_method, rpc_timeout=300)

        rpc.init_rpc('worker_' + str(rank), rank=rank, world_size=world_size, rpc_backend_options=rpc_opt)

    rpc.shutdown()

if __name__ == "__main__":
    WORLD_SIZE = 8

    # RANK_START and RANK_END is given by shell script according to the nodes you have
    RANK_START, RANK_END = 0, 4
    # e.g. RANK_START, RANK_END = 4, 8 for the second node
    
    procs = []
    for i in range(RANK_START, RANK_END):
        p = mp.Process(target=run, args=(i, WORLD_SIZE))
        p.start()
    for p in procs:
        p.join()
```

## Expected behavior
Code will get stuck when calling `torch.qr` on CPU tensor.

## Environment

The cluster is composed of 1 server node, with 2 NVIDIA P100 GPUs and 8 CPUs, and 2 worker nodes, both with 32 CPUs.

Environment of server node:
```
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi
```

Environment of worker nodes:
```
Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi
```

## Additional context

Prototype of the above code was meant to conduct distributed reinforcement learning, i.e. using worker nodes to collect data and use head node to provide action and train DNNs.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
There might be some cuda synchronization issues here, just as a test can you add `torch.cuda.synchronize` just after `init_rpc` to see if it works?

**Comment by SciPioneer** [comment]
Agree with pritamdamania87. To be more specific, you can just sync on each GPU device, not across devices on the same machine.

```
        if torch.cuda.is_available():
            torch.cuda.synchronize(device)
```

**Comment by garrett4wade** [comment]
I'm afraid that adding `torch.cuda.synchronize(gpu_rank)` actually does not work.

In case of misunderstanding, the problem is, when calling `torch.qr` on a CPU tensor, no matter it was a cuda tensor loaded into CPU or just initialized on CPU, the code will be hanging. Thus I don't think it a cuda related problem, because it will happen before cuda is initialized.
```python
# just after init_process_group and init_rpc
q, r = torch.qr(torch.randn(4, 4))  # stuck
```
I know from [documentation](https://pytorch.org/docs/master/generated/torch.qr.html?highlight=qr#torch.qr) that `torch.qr` uses LAPACK for CPU inputs and MAGMA for CUDA inputs. I wonder if it is the reason why `torch.qr` behaves differently on cuda tensors and CPU tensors, in the context of DDP and RPC.

**Comment by SciPioneer** [comment]
I wonder if this only occurs in multi-node context. Is this reproducible on a single (potentially multi-core) machine?

**Comment by garrett4wade** [comment]
No, I believe it only occurs in multi-node context. Preiviously on a 64-core 4-GPU machine with torch 1.8.1 and cuda10.2, the above code does not get stuck.

For now I'm not available to the cluster I ran the code before, and I can't conduct further experiments on it. Since this bug has a simple workaround (load tensor into GPU and then call `torch.qr` or `torch.nn.init.orthogonal_`, instead of the call the function on CPU tensor), I will close this issue. Hopefully this issue will provide guide to any other people who encounter this problem.

If the PyTorch contributors find this bug necessary to resovle, please reopen it. Thanks for your advice. :)
