### ISSUE TITLE
The latest code cannot build due to missing file CPUFuntion.h

### ISSUE THREAD

**Issue by HawieLong** [pytorch/pytorch#54856]
## 🐛 Bug
Since 2021.3.26, the latest code build has error

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hanyulon/pytorch/pytorch/tools/codegen/gen.py", line 3, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
make[2]: *** [caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/build.make:139: aten/src/ATen/CPUFunctions.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:4604: caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs.... 

The typing_extensions packaged has been installed. This issue is caused by missing file CPUFuntion.h

## To Reproduce

1.git clone --recursive https://github.com/pytorch/pytorch
2.cd pytorch
3.git submodule sync
4.sudo python setup.py clean
5.BUILD_TEST=0 DEBUG=1 python setup.py develop --cmake-only
6.sudo BUILD_TEST=0 DEBUG=1 python setup.py develop && python -c "import torch"

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hanyulon/pytorch/pytorch/tools/codegen/gen.py", line 3, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
make[2]: *** [caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/build.make:139: aten/src/ATen/CPUFunctions.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:4604: caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs.... 

## Expected behavior
build success

## Environment
Build Environment:
Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
No GPU
Ubuntu 20.0

## Additional context
This error is appeared recently. May caused by generating code cannot generate CPUFuntions.h automatically.

cc @malfet @seemethere @walterddr

**Comment by HawieLong** [comment]
Build Environment:
Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
No GPU

**Comment by imaginary-person** [comment]
Look again at the error. You need to install the Python module `typing_extensions`.
`sudo -H pip install typing_extensions`

**Comment by HawieLong** [comment]
Yes, I have installed typing_extensions, I even can import it in python console. This one I have debugged and find that I dont have CPUFunctions.h which caused this issue. You can try from downloading latest code and you will reproduce it.

**Comment by imaginary-person** [comment]
> You can try from downloading latest code and you will reproduce it

I cloned the master branch less than a couple of hours back & was able to build successfully.

**Comment by HawieLong** [comment]
Maybe related to environment? I cloned the master branch a couple of hours as well. Did you have GPU? Or you are using only CPU as well?

**Comment by imaginary-person** [comment]
> Maybe related to environment? I cloned the master branch a couple of hours as well. Did you have GPU? Or you are using only CPU as well?

For the latest build, I only used CPU on Ubuntu 18.04.
I used `USE_OPENMP=1 DEBUG=1 sudo python3 setup.py develop` to build.

**Comment by HawieLong** [comment]
Yes, I use pip install numpy pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
except ninja, since install ninja will lead to other issues.
I will pull top of tree again to see whether this issue can reproduce today.

> Can you ensure that you have installed all dependencies in the repro steps? https://github.com/pytorch/pytorch#install-dependencies

**Comment by HawieLong** [comment]
Hey guys. I have pulled the latest code, and compiled successfully. Don't know why but it works. Thus I will close this bug.
Thank you all for your help. :)
