### ISSUE TITLE
Tensors don't gracefully compare to NoneType

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5486]
```python
import torch
[torch.Tensor(), None, None].count(None)

#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File ".../lib/python2.7/site-packages/torch/tensor.py", line 312, in __eq__
#    return self.eq(other)
#TypeError: eq received an invalid combination of arguments - got (NoneType), but expected one of:
# * (float value)
#      didn't match because some of the arguments have invalid types: (NoneType)
# * (torch.FloatTensor other)
#      didn't match because some of the arguments have invalid types: (NoneType)
```
at `0.4.0a0+1fdb392`

**Comment by ezyang** [comment]
@li-roy will look into this

**Comment by vadimkantorov** [comment]
```python
[torch.Tensor([1, 2]), 1, 2].count(1)
#File "/home/mscho/vadim/.wigwam/prefix/python/lib/python2.7/site-packages/torch/tensor.py", line # 168, in __bool__    " containing more than one value is ambiguous")

[torch.Tensor([1]), 1, 2].count(1)
#2
```
a special case for None will be useful, but can it be handled in general?

**Comment by colesbury** [comment]
Note that this doesn't work with NumPy either. The `==` operator does element-wise comparisons for PyTorch and NumPy. I'm not sure changing it just for None is a good idea.

**Comment by vadimkantorov** [comment]
Agree. A mid-ground may be returning False for all non-admissible types, but it won't cover the general scenario fully, and probably won't be discoverable/intuitive.

**Comment by srinivr** [comment]
What is the suggested workaround in this circumstance?
`import torch`
`x = [torch.rand((3,2)), None] ` 
`if None in x:
    print('None found in list')`

**Comment by li-roy** [comment]
@srinivr Perhaps just write a small function that returns True if it's a Tensor, otherwise does the check for None?

**Comment by srinivr** [comment]
I'm currently iterating through the list and check with `is None` but I wanted to know if there was a better way around it. But thanks for the tip! I can make it a function.

**Comment by WenjianDong** [comment]
I'm using `type(my_tensor) == type(None)`. It works for my case, but I'm wondering if it could be a general solution.

**Comment by TracyYXChen** [comment]
> I'm using `type(my_tensor) == type(None)`. It works for my case, but I'm wondering if it could be a general solution.

I met "'NoneType' object is not callable" error
