### ISSUE TITLE
Please remove "maste" branch from the main repositoy

### ISSUE THREAD

**Issue by take-cheeze** [pytorch/pytorch#54862]
## 🐛 Bug

https://github.com/pytorch/pytorch/tree/maste keep bothers me from creating branch from origin/master with some completions.
Please remove it if possible.

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by H-Huang** [comment]
You can try to stop tracking that particular remote branch if it is causing issues for you.

**Comment by driazati** [comment]
Should be fixed now (sorry it took so long), thanks for pointing it out!

**Comment by take-cheeze** [comment]
Thank you!
