### ISSUE TITLE
Improve torch.linalg documentation

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#54878]
Following the discussion in https://github.com/pytorch/pytorch/pull/54002

I'd be keen on helping improving the documentation of `torch.linalg` and the related functions in `torch.*`. I'd like to correct several errata that appear here and there, make the formatting uniform and add some extra information for when the backward of the operations succeeds and when it fails.

To summarise the state of affairs. There are five ways of writing code / maths in Sphinx:
 - Single backticks: `` `A` `` is rendered as _A_
 - Double backticks: ``` ``A`` ``` is rendered as `A`
 - Attr: `` :attr:`A` `` is rendered as `A`
 - LaTeX: `` :math:`A` `` is rendered as a LaTeX image of A
 - Plain text: A
 
On top of this, the signature of the function is rendered with a different format bold letters with the arguments in italics:
![image](https://user-images.githubusercontent.com/3291265/112856692-f76d3680-90a7-11eb-9555-efddeea79dd4.png)

As discussed in  https://github.com/pytorch/pytorch/pull/54002, given that the LaTeX font is completely different to the normal HTML font, it is reasonable to keep the LaTeX usage to a minimum. In particular, prefer unicode maths (see [this page](https://www.unicodeit.net/)) over LaTeX for inline formulas. For large formulas, use the environment `.. math::` which puts the formula on its own line.

It looked like everyone also agreed that `:attr:` was a good decorator to use when referring to input parameters.

Given these premises, the standing issue was: when do we use single backticks or double backticks?

Single backticks have the problem that introduce a new format (italics) when just one formatting (the one from double backticks and `:attr:` could do)

Double backticks have the problem that they are not rendered properly when the formula has spaces. See for example in [`torch.linalg.choleski`](https://pytorch.org/docs/stable/linalg.html?highlight=linalg%20choleski):
![image](https://user-images.githubusercontent.com/3291265/112856836-1e2b6d00-90a8-11eb-9e2f-14d074f62b58.png)

How should we go about this?

In my opinion, I would go with "always use double backticks" for uniformity, as their format matches that of `:attr:`. We then would have to look into the spacing problem, but I guess that should be solved from within the sphinx template. Note also that these breaks just happen when the background is white. When it is not (e.g. in a `note` or `warning`) they are rendered correctly. See [`torch.linalg.slogdet`](https://pytorch.org/docs/stable/linalg.html?highlight=linalg%20slogdet)
![image](https://user-images.githubusercontent.com/3291265/112857422-bde8fb00-90a8-11eb-8684-1b1aef17932c.png)

Example with **single backticks**:
![image](https://user-images.githubusercontent.com/3291265/112861418-add31a80-90ac-11eb-8ec7-f808a2e8d61a.png)

Example with **double backticks**:
![image](https://user-images.githubusercontent.com/3291265/112861533-c8a58f00-90ac-11eb-90c8-47202a99f772.png)

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by IvanYashchuk** [comment]
Together with Mario, we've found out that some Unicode symbols (for example “ₙ” (U+2099)) do not render properly on Mac with the system default font.
Quick google search tells that this problem could probably be fixed with CSS [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) that allows using a custom font from a server or locally from the computer if available.

**Comment by Lezcano** [comment]
I'm starting look at this issue in the large now. I see that the functions that we have now could be split into reasonable groups as:
Factorisations: Choleski, eig, eigh, eigvals, eigvalsh, svd, qr
Inverses: inv, pinv
Solvers: solve, lstsq
Products: multidot, matrix_power, householder_product
Tensor operations: tensorinv, tensorsolve
General: norm, vector_norm, det, slogdet, cond, matrix_rank

I think this would also make the documentation of the module much more manageable. What do you think? @mruberry @IvanYashchuk

If we decide to centralise here later on all the linalg operations (which I think it'd be a great idea), we could fit `lobpcg` into solvers, and we could even create a Matrix functions category to put `matrix_exp`, `matrix_power`, `matrix_sqrt`, `matrix_log`, etc (whenever we have these other operation available, of course).

**Comment by mruberry** [comment]
Hey @Lezcano! This is really helpful.

I like the way single backticks looks most. We could stop using :attr:\`input\` and starting using \`input\`, too. Does that make single backticks more compelling for you, or do you still prefer double backticks?

Separately, I think we should ban unicode characters and require LaTex be used for mathematical notation.

Your suggestions for how to organize the operations in the linalg doc makes sense, and is maybe a good opportunity to provide a preamble in the torch.linalg documentation with links to each function's documentation.

**Comment by Lezcano** [comment]
I'll group them like that in the PR. I also figured that "General" could be better called "Matrix Properties" (norm, det, cond, rank...)

About single vs double backticks, I agree that, as it stands single backticks look better. On the other hand, I believe that if we were able to fix the double backticks to show a uniform background, double backticks would be much better.

About :attr:\`input\` vs \`input\` I think that there's a pro and a con, the con being just technical.
The pro is that it makes straightforward to see when something is an attribute, which is great.
The con is that the sphinx / RST code that you have to write to make it work is very clunky, as you have to insert many "backslash space" in many places, which is annoying and not particularly intuitive.

I do not mind going for the second, as I think it makes the docs clearer, but I do not know how reasonable is to maintain this in future PRs. Perhaps it's fine, given we are just 3 maintainers maintaining this `torch.linalg` code?

**Comment by mruberry** [comment]
> I'll group them like that in the PR. I also figured that "General" could be better called "Matrix Properties" (norm, det, cond, rank...)

Sounds great.

> About single vs double backticks, I agree that, as it stands single backticks look better. On the other hand, I believe that if we were able to fix the double backticks to show a uniform background, double backticks would be much better.

We could switch to double backticks after fixing the docs formatting, too? Although it's unclear if/when that change will occur.

> About :attr:`input` vs `input` I think that there's a pro and a con, the con being just technical.
> The pro is that it makes straightforward to see when something is an attribute, which is great.
> The con is that the sphinx / RST code that you have to write to make it work is very clunky, as you have to insert many "backslash space" in many places, which is annoying and not particularly intuitive.

Your call.

> I do not mind going for the second, as I think it makes the docs clearer, but I do not know how reasonable is to maintain this in future PRs. Perhaps it's fine, given we are just 3 maintainers maintaining this `torch.linalg` code?

I agree. I think whatever strategy we choose will be maintainable.

**Comment by Lezcano** [comment]
Yeah, it'd be fairly easy to move from single to double backticks in the future, so that's fine.

**Comment by Lezcano** [comment]
Also, about LaTeX, I completely agree. See
https://github.com/pytorch/pytorch/pull/56265#discussion_r615690215

**Comment by IvanYashchuk** [comment]
Current documentation includes notes on the backend library function used for each function in `torch.linalg`.
What do you think about using a separate table instead? Something like
| torch.linalg | CPU    | CUDA                  |       | HIP       |       |
|--------------|--------|-----------------------|-------|-----------|-------|
|              | LAPACK | cuSOLVER & cuBLAS     | MAGMA | rocSOLVER | MAGMA |
| svd          | gesdd  | gesvdj, gesvdjBatched | gesdd | -         | gesdd |
|              |        |                       |       |           |       |

**Comment by Lezcano** [comment]
Yeah, that looks great. The only thing is that we should put when is one function chosen over a different one. Something like
| torch.linalg | CPU    | CUDA `(m,n)` | CUDA `(*, m, n)`              |  ?? | HIP       |  ??     |
|--------------|--------|-----------|------------|-------|-----------|-------|
|              | LAPACK | cuSOLVER | cuBLAS     | MAGMA | rocSOLVER | MAGMA |
| svd          | gesdd  | gesvdj | gesvdjBatched | gesdd | -         | gesdd |
|              |        |                     |  |       |           |       |

and so on. But yeah, I think that's a great idea.

Perhaps we could land this preliminary PR first, then work out a good template for how to write the backends, and have each person that worked in a function in `torch.linalg` fill it in and add it to the docs.
