### ISSUE TITLE
load_state_dict() for optimizers

### ISSUE THREAD

**Issue by bobbens** [pytorch/pytorch#549]
nn modules have a self.state_dict() and self.load_state_dict() function to save and load the state respectively. However, optimizer only has a self.state_dict() and no way to load the state. This would be nice to have to be able to pause the training by saving both the model/optimizer state and resume where left off.

**Comment by apaszke** [comment]
As a quick hack I think you should be able to use `optimizer.__setstate__(state)` where `state = optimizer.state_dict()`. We'll just need to alias that

**Comment by apaszke** [comment]
Implemented in #577.
