### ISSUE TITLE
Pipeline parallel example code triggers RPC error

### ISSUE THREAD

**Issue by santhnm2** [pytorch/pytorch#54927]
## 🐛 Bug

The provided sample code for the `torch.distributed.pipeline.sync.Pipe` API results in the following error:

```
RuntimeError: agent INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/distributed/rpc/rpc_agent.cpp":247, please report a bug to PyTorch. Current RPC agent is not set!
```

## To Reproduce

I ran the following code, which was taken directly from the documentation:

```
import torch
from torch.distributed.pipeline.sync import Pipe

fc1 = torch.nn.Linear(16, 8).cuda(0)
fc2 = torch.nn.Linear(8, 4).cuda(1)
model = torch.nn.Sequential(fc1, fc2)
model = Pipe(model, chunks=8)
input = torch.rand(16, 16).cuda(0)
output_rref = model(input)
```

## Expected behavior

The model should return the output `RRef` without raising an exception.

## Environment
```
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration:
GPU 0: TITAN V
GPU 1: TITAN V
GPU 2: TITAN V
GPU 3: TITAN V

Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
@santhnm2 You need to initialize the RPC framework for pipeline parallelism: https://pytorch.org/docs/stable/rpc.html#torch.distributed.rpc.init_rpc. You can look at https://pytorch.org/tutorials/intermediate/pipeline_tutorial.html for an example.

**Comment by pritamdamania87** [comment]
@santhnm2 Updated some of the docs and error messages in https://github.com/pytorch/pytorch/pull/55187, let me know if you're still running into any other issues.

**Comment by santhnm2** [comment]
@pritamdamania87 Sounds good, thanks!
