### ISSUE TITLE
torch.ceil wrong formula

### ISSUE THREAD

**Issue by maxwellzh** [pytorch/pytorch#54948]
## 📚 Documentation

Though the description is correct, this formula is wrong.
![截屏2021-03-30 下午5 33 10](https://user-images.githubusercontent.com/32546978/112968056-7af95700-917e-11eb-95c8-0957fa715496.png)

```
>>> x = torch.tensor([12,7,5])/6
>>> torch.ceil(x) == torch.floor(x)+1
tensor([False,  True,  True])
```

cc @brianjo @mruberry @rgommers @heitorschueroff

**Comment by H-Huang** [comment]
Thanks for raising this. We would accept a fix updating the documentation!

**Comment by mruberry** [comment]
cc @kshitij12345, our most recent unary ops maintainer

**Comment by kshitij12345** [comment]
@maxwellzh Thanks for reporting. You are correct `ceil(x) != floor(x) + 1` when `x` is already an integer.

We should remove that erroneous expression from the docs. Otherwise the doc looks fine to me.

@maxwellzh Would you be interested in sending a Pull Request for the same?

**Comment by maxwellzh** [comment]
@kshitij12345 I have sent a pull request. Could you check that? #55039
