### ISSUE TITLE
__not__ is not an ATen method

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5495]
No one seems to have complained from the Python side, but TorchScript is currently emitting `__not__` operations, which are not going to be runnable.

CC @apaszke

**Comment by apaszke** [comment]
It's just the value that's hardcoded in the compiler, we can change it to any other function by modifying a single line. Do we have a universal op for not?

**Comment by jamesr66a** [comment]
This appears to be fixed here https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/register_prim_ops.cpp#L693
