### ISSUE TITLE
TODO: Upsampling

### ISSUE THREAD

**Issue by bobbens** [pytorch/pytorch#550]
For more visibility I'm creating an issue about the TODO in the upsampling.py file [1], as upsampling+convolutions is a way to avoid some artefacts which are common with deconvolution/upconvolution/transposed convolution/whatever you want to call it [2]. I also tried using the torch legacy packages, but they don't seem to play well with AutoGrad.

[1] https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/upsampling.py
[2] http://distill.pub/2016/deconv-checkerboard/

**Comment by szagoruyko** [comment]
I've got bilinear upsampling implemented here https://github.com/szagoruyko/pytorch/blob/functions-resize/torch/nn/functions/thnn/resize.py

**Comment by apaszke** [comment]
@szagoruyko Can you send a PR?

**Comment by soumith** [comment]
nice. push it back to master :)

**Comment by apaszke** [comment]
Both are now implemented (see #577).
