### ISSUE TITLE
Cannot install torch

### ISSUE THREAD

**Issue by ZhiyuanChen** [pytorch/pytorch#55007]
## 🐛 Bug

```
Package pkginfo conflicts for:
conda-build -> pkginfo
anaconda==2020.11 -> pkginfo==1.6.1[build='py38h06a4308_0|py37h06a4308_0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - cudatoolkit=11.1 -> __glibc[version='>=2.17,<3.0.a0']
  - pytorch -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchaudio -> pytorch==1.8.0 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchvision -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.27
```

## To Reproduce

```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
```

## Expected behavior

install

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
```

## Additional context

The conda is a fresh conda env, i.e. it is on revision 0. 
CUDA version is 11.2 as shown on the `nvidia-smi`

**Comment by skyline75489** [comment]
A little googling leads me to [this page](https://stackoverflow.com/questions/66726830/conda-glibc-dependency-conflict), which suggests the issue is caused by mixing usage of `default` channel & `conda-forge` channel. Can you check if this repro when you create a new env using `conda create -n py38 python=3.8` ? I can't repro this locally.

**Comment by ZhiyuanChen** [comment]
> A little googling leads me to [this page](https://stackoverflow.com/questions/66726830/conda-glibc-dependency-conflict), which suggests the issue is caused by mixing usage of `default` channel & `conda-forge` channel. Can you check if this repro when you create a new env using `conda create -n py38 python=3.8` ? I can't repro this locally.

I used command from [this page](https://pytorch.org/get-started/locally/). 
No, as I mentioned it is a fresh conda, so it's the base environment. 
But I don't think it has a lot to do, as I've tried to crate a seperate env with python=3.7, the error is the same.

**Comment by ZhiyuanChen** [comment]
resolved by `conda update --all` ...
