### ISSUE TITLE
Doc of SVD is erroneous and inconsistent

### ISSUE THREAD

**Issue by Felix-Petersen** [pytorch/pytorch#55006]
## 📚 Documentation

The doc for [torch.linalg.svd](https://pytorch.org/docs/stable/linalg.html#torch.linalg.svd) contains some errors:

* it states "input=U@diag(S)×Vh", which is an inconsistent notation for the matrix multiplication and apparently also wrong: To obtain the identity, I had to do `U@diag(S)@Vh.T`. I think there should be a clear declaration of whether `V`/`Vh` has to be transposed or not.
* "If full_matrices is False (default)" is inconsistent with the signature of the function (`torch.linalg.svd(input, full_matrices=True, compute_uv=True, *, out=None)`).

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
Thank you for reporting this issue, @Felix-Petersen. We're always looking to make our documentation better!

cc @Lezcano, who's been improving our SVD documentation.

**Comment by Lezcano** [comment]
This should be solved by https://github.com/pytorch/pytorch/pull/54002 once it's merged.
There's also the larger issued https://github.com/pytorch/pytorch/issues/54878 that aims to improve the docs of all `torch.linalg`.

**Comment by Lezcano** [comment]
Solved by https://github.com/pytorch/pytorch/pull/54002

**Comment by mruberry** [comment]
@Felix-Petersen, what do you think of the updated docs?

**Comment by Felix-Petersen** [comment]
Thanks for asking! It looks good. However, I am wondering why the transpose of $V$ is denoted as $Vh$.
I've never encountered this notation. I think $V^\top, V^T,$ or $V.T$ would be much clearer.

Felix

**Comment by Lezcano** [comment]
@Felix-Petersen That's to account for the complex case as well. See: https://en.wikipedia.org/wiki/Conjugate_transpose

**Comment by Felix-Petersen** [comment]
Ah, I see. Thanks.
