### ISSUE TITLE
CUDA out of memory. 

### ISSUE THREAD

**Issue by karimfayed** [pytorch/pytorch#55004]
## ❓ I trained a model on a virtual environment but the model crashed and when I created a new virtual environment to run the model again the following error keeps popping and i can't free the CUDA

*RuntimeError:** CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.28 GiB already allocated; 4.55 MiB free; 1.28 GiB reserved in total by PyTorch)
*
The following is the Traceback:
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-191fa3e562e9> in <module>
    122   model_name = 'google/pegasus-large'
    123   train_dataset, _, _ = prepare_data(model_name, train_texts, train_labels)
--> 124   trainer = prepare_fine_tuning(model_name, train_dataset)
    125   trainer.train()

<ipython-input-1-191fa3e562e9> in prepare_fine_tuning(model_name, train_dataset, val_dataset, freeze_encoder, output_dir)
     62   """
     63   torch_device = 'cuda' if torch.cuda.is_available() else 'cpu'
---> 64   model = PegasusForConditionalGeneration.from_pretrained(model_name).to(torch_device)
     65 
     66   if freeze_encoder:

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in to(self, *args, **kwargs)
    671             return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
    672 
--> 673         return self._apply(convert)
    674 
    675     def register_backward_hook(

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    385     def _apply(self, fn):
    386         for module in self.children():
--> 387             module._apply(fn)
    388 
    389         def compute_should_use_set_data(tensor, tensor_applied):

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in _apply(self, fn)
    407                 # `with torch.no_grad():`
    408                 with torch.no_grad():
--> 409                     param_applied = fn(param)
    410                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    411                 if should_use_set_data:

c:\users\karim\p2\lib\site-packages\torch\nn\modules\module.py in convert(t)
    669                 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
    670                             non_blocking, memory_format=convert_to_format)
--> 671             return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
    672 
    673         return self._apply(convert)

**Comment by skyline75489** [comment]
Can you check the result of `nvidia-smi`? Training can require a *lot* of GPU memory.

**Comment by H-Huang** [comment]
You can post this question on the discussion forums (https://discuss.pytorch.org/). If you include a reproducible script and your environment we are much more likely to root cause the issue.
