### ISSUE TITLE
Maybe one more '=' sign?

### ISSUE THREAD

**Issue by kangzhiheng** [pytorch/pytorch#55021]
It's a small mistake i find in https://pytorch.org/get-started/previous-versions/ by accident...

![image](https://user-images.githubusercontent.com/30773002/113088363-05da6000-9218-11eb-8408-f45aedb7e079.png)

cc @brianjo @mruberry

**Comment by H-Huang** [comment]
Thanks for catching this! We would accept a PR to fix this.

**Comment by brianjo** [comment]
Thanks @kangzhiheng! I added a PR here: https://github.com/pytorch/pytorch.github.io/pull/654
