### ISSUE TITLE
pytorch clone could be faster

### ISSUE THREAD

**Issue by yaroslavvb** [pytorch/pytorch#5502]
On a multicore system (dual socket XeonV4 of p3.16xlarge) it seems 10x faster to clone an array by adding 0 to it, than by calling clone

https://github.com/diux-dev/cluster/blob/master/yuxin_numpy/tf_numpy_benchmark.py

```
# Using 100 MB of data, times are in ms
python tf_numpy_benchmark.py --benchmark=pytorch_add0 --allocator=tf --num-iters=101  
# pytorch_add0                  :  28.2 GB/sec, min:  3.55, median:  4.00, mean:  4.10
python tf_numpy_benchmark.py --benchmark=pytorch_clone --allocator=tf --num-iters=101    # 22.4 GB
# pytorch_clone                  :   2.5 GB/sec, min: 40.45, median: 40.82, mean: 40.91

```

pytorch version: '0.3.0.post4'

cc @VitalyFedyunin @ngimel

**Comment by soumith** [comment]
@varoslavvb it depends on the underlying memcpy implementation. If the memcpy on the system is Numa-aware, multithreaded and uses full simd, it should be the same or faster than the Add codepath

**Comment by yaroslavvb** [comment]
Any tips how to upgrade to multithreaded memcpy on Ubuntu?

I'm getting this slow speed with Amazon Deep Learning AMI v5.0
https://aws.amazon.com/marketplace/pp/B077GCH38C

(cc @b0noI who makes Deep Learning AMIs)

**Comment by apaszke** [comment]
I don't think memcpy is multithreaded in any of the common libc's. We should call it from multiple threads ourselves

**Comment by soumith** [comment]
oh i see. I know memcpy is SIMD-enabled, but I guess it's not multithreaded.

**Comment by apaszke** [comment]
Thanks for the reports @yaroslavvb, they're super helpful!

**Comment by yaroslavvb** [comment]
BTW, improvement to this may also help tensor.share_memory() -- it's faster than clone, but seems to be single-threaded (based on `htop` utilization)

**Comment by yaroslavvb** [comment]
I tried copying stuff using `_mm256_stream_si256` [here](https://github.com/diux-dev/cluster/blob/master/psbench/memcpy.cc), it seems 2-3x faster than what PyTorch is doing by default

This [article](http://web.archive.org/web/20131223174037/http://software.intel.com/en-us/articles/memcpy-performance/) talks about why memcpy is so bad. It's part of standard library, so you are relying on stock pre-compiled version. Compilation with `icc` substitutes vectorized version of memcpy, `gcc` doesn't

**Comment by soumith** [comment]
cc: @cpuhrsch you should issue fixes to make this faster.

**Comment by cpuhrsch** [comment]
On it. Rewriting copy is next on my list after my current work.

**Comment by yaroslavvb** [comment]
On skylakes (AWS c5 instances), you should be able to copy 100MB tensor in 2.7MB

```
wget -N https://raw.githubusercontent.com/diux-dev/cluster/master/psbench/memcpy_fast.cc
g++ -std=c++0x memcpy_fast.cc -pthread -march=native -O6 -o memcpy_fast
numactl --cpunodebind 0 --membind 0 ./memcpy_fast 100 16
Stream copy 16 threads: 2.7 ms, 37.33 GB/sec
Stream copy 16 threads: 2.7 ms, 37.41 GB/sec
```

**Comment by zou3519** [comment]
I don't know if we've fixed this already, @cpuhrsch @VitalyFedyunin @ngimel do you know?

**Comment by VitalyFedyunin** [comment]
We rewrote copy in 2019. Should at least not slower than adding 0 =)

**Comment by prajwalsingh** [comment]
> On a multicore system (dual socket XeonV4 of p3.16xlarge) it seems 10x faster to clone an array by adding 0 to it, than by calling clone
> 
> https://github.com/diux-dev/cluster/blob/master/yuxin_numpy/tf_numpy_benchmark.py
> 
> ```
> # Using 100 MB of data, times are in ms
> python tf_numpy_benchmark.py --benchmark=pytorch_add0 --allocator=tf --num-iters=101  
> # pytorch_add0                  :  28.2 GB/sec, min:  3.55, median:  4.00, mean:  4.10
> python tf_numpy_benchmark.py --benchmark=pytorch_clone --allocator=tf --num-iters=101    # 22.4 GB
> # pytorch_clone                  :   2.5 GB/sec, min: 40.45, median: 40.82, mean: 40.91
> ```
> 
> pytorch version: '0.3.0.post4'
> 
> cc @VitalyFedyunin @ngimel

Thank you so much, it gives an insane speed-up just by adding zero instead of clone and really saves lots of computation time.

**Comment by elbaro** [comment]
@prajwalsingh Have you run it on the latest version and seen x10 speedup?

**Comment by prajwalsingh** [comment]
Hi @elbaro, for the project, I am using Pytorch 1.13+cu (not the latest Pytorch2 build).
