### ISSUE TITLE
cufft error

### ISSUE THREAD

**Issue by panxin801** [pytorch/pytorch#55032]
## 🐛 Bug

When I using torch cufft for data processing, I meet the follwoing error:

```
Epoch 10 | Step 40686 | Iter 30400:
per_token_loss: 1.3417494 | avg_token_loss: 1.3317900 | learning_rate: 0.0002191
sequence_per_sec: 26.4520501
terminate called after throwing an instance of 'c10::Error'
  what():  cuFFT error: CUFFT_INVALID_PLAN (CUFFT_CHECK at /pytorch/aten/src/ATen/native/cuda/CuFFTUtils.h:70)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f585fed4536 in /root/.local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x299e1e0 (0x7f5862cce1e0 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x29a3c0d (0x7f5862cd3c0d in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #3: at::native::_fft_cufft(at::Tensor const&, long, bool, bool, bool, c10::ArrayRef<long>, bool, bool, c10::ArrayRef<long>) + 0x752 (0x7f5862cd1af2 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xfa2408 (0x7f58612d2408 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xfe27a4 (0x7f58613127a4 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x2c2221c (0x7f589227a21c in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x10c3f44 (0x7f589071bf44 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0xde1d5f (0x7f5890439d5f in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::native::rfft(at::Tensor const&, long, bool, bool) + 0x22 (0x7f589043b0f2 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x1152ef4 (0x7f58907aaef4 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2cf1434 (0x7f5892349434 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x1189308 (0x7f58907e1308 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x298603 (0x7f589e8a0603 in /root/.local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #59: <unknown function> + 0x76ba (0x7f58a1dcb6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #60: clone + 0x6d (0x7f58a1b0141d in /lib/x86_64-linux-gnu/libc.so.6)
```

 - PyTorch==1.5+cu92
 - OS (e.g., Linux):ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source):pip 
 - Build command you used (if compiling from source): pip insall <local whl file that downloads from pytorch.org>
 - Python version: 3.7.6
 - CUDA/cuDNN version: CUDA==9.0.176
 - GPU models and configuration: GPU is 4*Tesla V100
 - Any other relevant information:

Thank you for the reply

cc @mruberry @peterbell10 @walterddr

**Comment by gchanan** [comment]
do you have a reproduction?

**Comment by panxin801** [comment]
Sorry sir, what do yoy mean reproduction here ? However, I tried the code  3 more times, it occurs at each time. 
At the beginning I thought as if my datas  have the problem,  so I grab the data  out of the dataset which cause the cufft error. Then I tried  the same code and it runs well, so I think the datas have no problem.

**Comment by mruberry** [comment]
@panxin801 By "reproduction," @gchanan is asking if there's a small code snippet that, if run, will reproduce this error. That would let us reproduce and investigate the issue. 

If a reproduction is too difficult, would you print the tensor's dtype, shape, and strides and the function you're calling?

**Comment by panxin801** [comment]
Yeah. Sorry for the late reply.
In the function I want to extract  the complex result of a input audio file,  and the  variable `fft` is the result I want.
```
waveform, window_shift, window_size, padded_window_size = _get_waveform_and_window_properties( waveform, channel, sample_frequency, frame_shift, frame_length,round_to_power_of_two,preemphasis_coefficient)

if len(waveform) < min_duration * sample_frequency:
	# signal is too short
	return torch.empty(0)

# strided_input, size (m, padded_window_size) and signal_log_energy, size (m)
strided_input, signal_log_energy = _get_window(waveform, padded_window_size, window_size, window_shift, window_type,blackman_coeff, snip_edges, raw_energy, energy_floor, dither,remove_dc_offset, preemphasis_coefficient)

# size (m, padded_window_size // 2 + 1, 2)
fft = torch.rfft(strided_input, 1, normalized=False, onesided=True)
return fft
```
I reproduce the error, the follwoing pars are the informations.
```
strided_input.shape is torch.Size([164, 512]) with type=<class'torch.Tensor'>
strided_input.dtype=torch.float32
```

**Comment by mruberry** [comment]
I'm sorry you're hitting this issue. Would you consider upgrading to PyTorch 1.8 and using the new torch.fft module? See here: https://pytorch.org/docs/master/fft.html?highlight=fft. It's functions are the same as NumPy's np.fft module.

**Comment by panxin801** [comment]
Oh, sorry for the late reply, I've already upgrade to torch==1.6.0 because another of my code use it and I'm testing it. Thank you. If it fix I'll then close the issue otherwise I'll put the new error here, thank you mates

**Comment by mruberry** [comment]
OK, please reopen this issue or file a new issue if you can reproduce this with PyTorch 1.8 and the torch.fft module.

**Comment by panxin801** [comment]
copy, thank you. Understood
