### ISSUE TITLE
Distributed Gather does not work properly?

### ISSUE THREAD

**Issue by fang150** [pytorch/pytorch#5506]
Environment:
- OS: Linux 4.4.0-83-generic x86_64
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version:2.7.10

Code:

import os
import torch
import torch.distributed as dist
import sys
rank= int(sys.argv[1])
def run(rank, size):
    if(rank==0):
        group = dist.new_group(range(size))
        g_list=[torch.DoubleTensor([1.0])]*size 
        alphak=torch.DoubleTensor([1.0])
        dist.gather(tensor=alphak,gather_list=g_list,group=group) 
        print(g_list) 
    else:
        group = dist.new_group(range(size))
        alphak=torch.DoubleTensor([rank])
        dist.gather(tensor=alphak,dst=0,group=group)
def init_processes(rank, size, fn, backend='tcp'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '9000'
    dist.init_process_group(backend, rank=rank, world_size=size)
    fn(rank, size)
if __name__ == "__main__":
    size = 3
    init_processes(rank, size, run, backend='tcp')

Issue:

In the code, I spawn 3 process, master as rank 0 , worker 1 as rank 1, worker 2 as rank2.

master should receive tensors from itself and 2 workers.

What I expected in tensor list should be [1,1,2] (first from master, second from worker 1 , third from worker 2), but I received [2,2,2].

any help would be greatly appreciated!!

**Comment by zou3519** [comment]
Maybe @teng-li can help?

**Comment by ailzhang** [comment]
I'll look into this.

**Comment by fang150** [comment]
Hey!

When I changed from "g_list=[torch.DoubleTensor([1.0])]*size" to 

"        g_list=[]
        for i in range(size):
            g_list.append(torch.DoubleTensor([1.0]))
"

Then problem solved.

What I am guessing is the elements in the list share the same memory location such that as the master received the tensors from workers , it is actually doing multiple write on the same location of memory.

**Comment by teng-li** [comment]
@fang150  cool, feel free to close the issue
