### ISSUE TITLE
`use_deterministic_algorithms` documentation needs an update

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#55086]
There are a few issues with the documentation for `use_deterministic_algorithms`:

* Variable name `d` should be changed to something more descriptive
*  ":class:RuntimeError" is not displayed correctly
* Links to `index_put` and `__getitem__` don't work
* "self" should not be mentioned in user facing docs
* Language for backward functions should be fixed (#51487)
* Need to add a note saying that operations that cause multiple writes to the same location due to overlapping tensors or duplicate indices are not detected by nondeterministic alerts (#50750). Add a few examples of this

cc @mruberry @kurtamohler @brianjo

**Comment by mruberry** [comment]
Small tweak: we do plan to continue declaring operations which behavior nondeterministically when given duplicate indices (like put) "nondeterministic operations," even though it's only on a subset of inputs.

In the future we may add more specialized checks or deterministic versions of these operations.
