### ISSUE TITLE
Implement improved DLPack support

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#55090]
## 🚀 Feature

[DLPack](https://github.com/dmlc/dlpack) is a mechanism to exchange data with other tensor/array libraries. PyTorch currently has DLPack support in `torch.utils.dlpack`, with `from_dlpack` and `to_dlpack` functions. The implementation lives in:
- [torch/csrc/Module.cpp#L356](https://github.com/pytorch/pytorch/blob/a4ca394f8af03d97b667a27b5e521d370228433b/torch/csrc/Module.cpp#L356)
- [aten/src/ATen/dlpack.h](https://github.com/pytorch/pytorch/blob/a4ca394f8af03d97b667a27b5e521d370228433b/aten/src/ATen/dlpack.h)

It is only at version 0.1.0 in PyTorch. This feature request is for upgrading to the latest DLPack and supporting the new Python API for it.

## Motivation

DLPack is being adopted as the [array API standard](https://github.com/data-apis/array-api) data interchange mechanism, see https://data-apis.org/array-api/latest/design_topics/data_interchange.html. A good motivation for why DLPack is the best protocol for that purpose, and an overview of other libraries supporting it, is given in https://github.com/data-apis/consortium-feedback/issues/1.

The tl;dr is: currently there is no single protocol that is supported by all major array/tensor libraries. DLPack is meant to be that. NumPy will also adopt it; CuPy, JAX, TensorFlow, MXNet all support it too; they all need to update to v0.4.0 and the new Python API.

Upgrading to the latest DLPack will give `bfloat16` and complex dtype support, and probably other improvements too (latest nontrivial commit to `dlpack.h` in PyTorch was in 2017).

The new Python API will have stream support, which is useful new functionality for CUDA/ROCm. There's a long design discussion at https://github.com/dmlc/dlpack/issues/57, and a summary of the outcome at https://data-apis.org/array-api/latest/design_topics/data_interchange.html#semantics.

Finally, DLPack is used in production already, for example spaCy relies on it to interoperate with both PyTorch and CuPy (documented [here](https://explosion.ai/blog/spacy-transformers)) - so improving its support makes sense.

## Pitch

I propose to:

- upgrade to latest DLPack (`0.4.0`)
- adopt the new [Python API for DLPack](https://data-apis.org/array-api/latest/design_topics/data_interchange.html) from the array API standard:
  - add `__dlpack__(self, stream=None)` and `__dlpack_device__(self)` methods on `torch.Tensor`
  - add `torch.from_dlpack(input, /)`. Note that it takes tensor-like objects with `__dlpack__` and `__dlpack_device__` methods, not a PyCapsule like `torch.utils.dlpack.from_dlpack`.
- add better tests. the current implementation has only one trivial roundtrip test.

One thing that needs checking is ABI compatibility - I believe DLPack has been stable since at least `v0.2.0` till `v0.4.0` (latest), however PyTorch is still at `v0.1.0` now. If there was an ABI break, we may have to leave the code supporting `torch.utils.dlpack` untouched, and introduce a new `dlpack.h` next to it.

Another thing that needs checking is how to resolve the issue that seems to plague the `Tensor.__array__` implementation when modifying the underlying storage of an exported buffer (see https://github.com/pytorch/pytorch/blob/f71a0daeb747148520ef275fa65b79cc6f5fa36b/torch/csrc/utils/tensor_numpy.cpp#L146).

## Alternatives

There's a discussion in https://data-apis.org/array-api/latest/design_topics/data_interchange.html about why alternative data exchange protocols are falling short.

## Additional context

DLPack is one feature of the array API standard; the discussion about adopting the full standard is gh-54581.

Cc @leofang, @tqchen, @emcastillo, @kmaehashi 

cc @mruberry @rgommers @heitorschueroff

**Comment by leofang** [comment]
CuPy v8.6.0/v9.0.0 supports DLPack 0.4.0 (https://github.com/cupy/cupy/pull/4695), so feel free to do round-trip tests agains CuPy 🙂

**Comment by vadimkantorov** [comment]
@rgommers my related issues about this: https://github.com/pytorch/pytorch/issues/43166 https://github.com/pytorch/pytorch/issues/42159 https://github.com/pytorch/pytorch/issues/34646

**Comment by szha** [comment]
The main changes between dlpack 0.1 and 0.2 are the addition of DLManagedTensor, key renaming for type code enum, and a few more device types. There shouldn't be any breaking changes for ABI compatibility.

**Comment by mruberry** [comment]
This sounds like a great idea and more DLPack support would be awesome! 

We would definitely accept PRs that improve compatibility as long as they're not BC-breaking (and we can discuss changes that are BC-breaking).

**Comment by emcastillo** [comment]
Hi, I will be taking care of this 😀

**Comment by rgommers** [comment]
Indeed, thanks @leofang

**Comment by vadimkantorov** [comment]
It would also be nice to have https://github.com/pytorch/pytorch/issues/43166 fixed
