### ISSUE TITLE
Significant difference in the performance of pytorch and exported onnx models

### ISSUE THREAD

**Issue by II245** [pytorch/pytorch#55183]
**Performance issue**
Noticed a significant difference in the performance of pytorch and exported onnx models with a simple conv layer.
The difference is more than 5 times after warming up.

**Urgency**
none

**System information**
OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
ONNX Runtime installed from (source or binary): binary
ONNX Runtime version: onnxruntime-1.7.0
Python version: Python 3.8.5
Pytorch version: 1.8.1
CUDA/cuDNN version: CUDA Version: 11.1
GPU model and memory: Tesla V100 (32G)

**To Reproduce**
Run the script below with parameters

reproduce onnx performance. The script creates onnx model on the fly.
```bash
CUDA_VISIBLE_DEVICES=0 python3 benchmark_repro.py \
  --onnx conv_fp16.onnx \
  --iterations 30 \
  --channels 896 \
  --iterations-warmup 30 \
  --run-with-io-binding \
  -B 32 \
  -T 832
```

output
```
Batch shape [32, 896, 832]
average load+fwd 35.92 msec
```

reproduce pytorch
```bash
CUDA_VISIBLE_DEVICES=0 python3 benchmark_repro.py \
  --iterations 30 \
  --channels 896 \
  --iterations-warmup 30 \
  -B 32 \
  -T 832
```

output
```
Batch shape [32, 896, 832]
average load+fwd 10.41 msec
```

```python
import argparse
import time
import torch
import torch.cuda.profiler
import onnxruntime
import numpy as np


def infer_ort(onnxruntime_session, io_binding):
	onnxruntime_session.run_with_iobinding(io_binding)


def get_model(channels):
	return torch.nn.Conv1d(in_channels=channels, out_channels=channels*2, kernel_size=19,
			stride=2, padding=(1 * 19 // 2), dilation=1, groups=1)


def export_onnx(onnx_path, channels, dtype = torch.float16):
	model = get_model(channels)
	torch.set_grad_enabled(False)
	model.eval()
	model.to('cuda', dtype=dtype)
	waveform_input = torch.rand((4, channels, 128), device='cuda', dtype=dtype)

	logits = model(waveform_input)

	torch.onnx.export(
			model, (waveform_input),
			onnx_path,
			opset_version=12,
			export_params=True,
			do_constant_folding=True,
			input_names=['input'],
			dynamic_axes=dict(input={
				0: 'B',
				2: 'T'
			})
	)

	## check export correctness
	onnxruntime_session = onnxruntime.InferenceSession(onnx_path)
	(logits_,) = onnxruntime_session.run(None, dict(input=waveform_input.cpu().to(dtype=dtype).numpy()))

	print((torch.from_numpy(logits_) - logits.cpu()).abs().to(dtype=torch.float32).max())
	assert torch.allclose(
			logits.cpu(),
			torch.from_numpy(logits_),
			**{
				'rtol': 1e-01,
				'atol': 1e-01
			}
	)

parser = argparse.ArgumentParser()
parser.add_argument('--iterations', type=int, default=16)
parser.add_argument('--iterations-warmup', type=int, default=16)
parser.add_argument('--channels', type=int, default=64)
parser.add_argument('--onnx')
parser.add_argument('-B', type=int)
parser.add_argument('-T', type=int)
parser.add_argument('--profile-cuda', action='store_true')
parser.add_argument('--run-with-io-binding', action='store_true')
args = parser.parse_args()

print(args)

dtype = torch.float16
use_cuda = True

if args.onnx:
	export_onnx(args.onnx, args.channels, dtype)
	onnxruntime_session = onnxruntime.InferenceSession(args.onnx)
	model = lambda x: onnxruntime_session.run(None, dict(input=x))
	if args.run_with_io_binding:
		model = lambda io_binding: onnxruntime_session.run_with_iobinding(io_binding)
	pass
else:
	model = get_model(args.channels)
	model.to('cuda')
	model.eval()
	model.to(dtype=dtype)

tictoc = lambda: (use_cuda and torch.cuda.synchronize()) or time.time()

batch_shape = [args.B, args.channels, args.T]

batch = torch.rand(*batch_shape, dtype=torch.float16)

if args.onnx:
	io_binding = onnxruntime_session.io_binding()
	X_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(batch.numpy(), 'cuda', 0)
	io_binding.bind_input(name='input', device_type=X_ortvalue.device_name(), device_id=0, element_type=np.float16,
			shape=X_ortvalue.shape(), buffer_ptr=X_ortvalue.data_ptr())
	io_binding.bind_output('3', 'cuda')
	batch = io_binding
	model = onnxruntime_session
	infer = lambda model, batch: infer_ort(model, batch)
else:
	batch = batch.to(device='cuda')
	infer = lambda model, batch: model(batch).cpu()

print('Warming up for', args.iterations_warmup, 'iterations')
tic_wall = tictoc()
torch.backends.cudnn.benchmark = True
for i in range(args.iterations_warmup):
	y = infer(model, batch)
print('Warmup done in {:.02f} wall clock seconds'.format(tictoc() - tic_wall))
print()

if args.profile_cuda:
	torch.cuda.profiler.start()

print('Starting benchmark for', args.iterations, 'iterations:', 'fwd')
times_fwd = torch.zeros(args.iterations)
batch = torch.rand(*batch_shape, dtype=torch.float16)

if args.onnx:
	io_binding = onnxruntime_session.io_binding()
	X_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(batch.numpy(), 'cuda', 0)
	io_binding.bind_input(name='input', device_type=X_ortvalue.device_name(), device_id=0, element_type=np.float16,
			shape=X_ortvalue.shape(), buffer_ptr=X_ortvalue.data_ptr())
	io_binding.bind_output('3', 'cuda')
	batch = io_binding
	model = onnxruntime_session
	infer = lambda model, batch: infer_ort(model, batch)
else:
	batch = batch.to(device='cuda')
	infer = lambda model, batch: model(batch)

for i in range(args.iterations):
	tic = tictoc()
	y = infer(model, batch)
	times_fwd[i] = tictoc() - tic
	y = None

print('Batch shape', batch_shape)
print('average load+fwd {:.02f} msec'.format(float(times_fwd.mean()) * 1e3))

```
Full cudnn logs here
[updated_cudnn_logs.zip](https://github.com/microsoft/onnxruntime/files/6251174/updated_cudnn_logs.zip)

To get logs,traces pelase run: 
```
TRACEFILE=profile_one_conv_onnx_with_warmup.sqlite
TRACELOG=profile_one_conv_onnx_with_warmup.txt
TRACEPYPROFLOG=profile_one_conv_onnx_with_warmup.pyprof.txt
CUDNN_LOGDEST=profile_one_conv_onnx_with_warmup_cudnn_dbg.txt
CUBLAS_LOGDEST=profile_one_conv_onnx_with_warmup_cublas_dbg.txt

CUDA_VISIBLE_DEVICES=0 CUDNN_LOGINFO_DBG=1 CUDNN_LOGDEST_DBG=$CUDNN_LOGDEST CUBLAS_LOGINFO_DBG=1 CUBLAS_LOGDEST_DBG=$CUBLAS_LOGDEST nvprof -f -o $TRACEFILE -s --devices 0 --profile-from-start off -- python3 benchmark_repro.py \
  --onnx conv_fp16.onnx \
  --iterations 1 \
  --iterations-warmup 4 \
  --profile-cuda \
  -B 32 \
  -T 1664 &> $TRACELOG

python3 nvprof2json.py $TRACEFILE > $TRACEFILE.json
```

**Expected behavior**
Onnx performance is the same as pytorch.

**Additional context**

Found that some arguments of cudnnConvolutionForward differ (cudnn log).

pytorch 
```
I! CuDNN (v8005) function cudnnConvolutionForward() called:
i!     handle: type=cudnnHandle_t; streamId=(nil) (defaultStream);
i!     alpha: type=CUDNN_DATA_FLOAT; val=1.000000;
i!     xDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,896,1,832];
i!         strideA: type=int; val=[745472,832,832,1];
i!     xData: location=dev; addr=0x7f1f48d80000;
i!     wDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[1792,896,1,19];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     wData: location=dev; addr=0x7f1fc4000000;
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         mathType: type=cudnnMathType_t; val=CUDNN_TENSOR_OP_MATH (1);
i!         reorderType: type=int; val=0;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[0,9];
i!         strideA: type=int; val=[1,2];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     algo: type=cudnnConvolutionFwdAlgo_t; val=CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM (1);
i!     workSpace: location=dev; addr=0x7f1f24d80000;
i!     workSpaceSizeInBytes: type=size_t; val=217458192;
i!     beta: type=CUDNN_DATA_FLOAT; val=0.000000;
i!     yDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,1792,1,416];
i!         strideA: type=int; val=[745472,416,416,1];
i!     yData: location=dev; addr=0x7f1f22000000;
i! Time: 2021-04-02T20:20:59.364486 (0d+0h+0m+7s since start)
i! Process=20457; Thread=20457; GPU=0; Handle=0x562d0f5507f0; StreamId=(nil) (defaultStream).

```

onnx
```
I! CuDNN (v8005) function cudnnConvolutionForward() called:
i!     handle: type=cudnnHandle_t; streamId=0x556d1919df70;
i!     alpha: type=CUDNN_DATA_FLOAT; val=1.000000;
i!     xDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,896,832,1];
i!         strideA: type=int; val=[745472,832,1,1];
i!     xData: location=dev; addr=0x7fb90c000000;
i!     wDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[1792,896,19,1];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     wData: location=dev; addr=0x7fb97c000000;
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         mathType: type=cudnnMathType_t; val=CUDNN_DEFAULT_MATH (0);
i!         reorderType: type=int; val=0;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[9,0];
i!         strideA: type=int; val=[2,1];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     algo: type=cudnnConvolutionFwdAlgo_t; val=CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM (0);
i!     workSpace: location=dev; addr=NULL_PTR;
i!     workSpaceSizeInBytes: type=size_t; val=0;
i!     beta: type=CUDNN_DATA_FLOAT; val=0.000000;
i!     yDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,1792,416,1];
i!         strideA: type=int; val=[745472,416,1,1];
i!     yData: location=dev; addr=0x7fb914000000;
i! Time: 2021-04-02T20:20:42.158192 (0d+0h+0m+4s since start)
i! Process=20361; Thread=20361; GPU=0; Handle=0x556d193e9ea0; StreamId=0x556d1919df70.

```

List of noted differences:
 - xDesc.dimA and strideA onnx ([32,896,832,1] vs pytorch [32,896,1,832])
 - convDesc.dataType onnx val=CUDNN_DATA_HALF (2) vs pytorch val=CUDNN_DATA_FLOAT (0)
 - and time to time algo val becomes CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM instead of CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM
 
Also
In tracing used different matrix kernels
pytorch: volta_fp16_s884cudnn_fp16_128x128_ldg8_relu_f2f_exp_large_nhwc2nchw_tn_v1
onnx: implicit_convolve_hhgemm

Could you please answer what is the cause of the differences?
Why in pytorch version of cudnn example datatype not set to half?
Or what do I wrong in benchmarking or onnx setup?

**UPDATE:**
- Added io_binding. Copy result to cpu in both cases.
- Changed script params and updated timings. Now performance differs two times.
- Cudnn logs and gemm names updated.

**UPDATE 2:**
- removed copy from gpy to cpu
- update performance comparison
now pytorch  ~3.5 times faster. 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @VitalyFedyunin @ngimel

**Comment by vadimkantorov** [comment]
@ngimel @ptrblck Would you know why PyTorch sets data_type to CUDNN_DATA_FLOAT? Is it normal? Should it not be CUDNN_DATA_HALF?

**Comment by II245** [comment]
May also sound interesting.
There are differences in cudnnFindConvolutionForwardAlgorithmEx functions 
<details>
 <summary>Pytorch</summary>

I! CuDNN (v8005) function cudnnFindConvolutionForwardAlgorithmEx() called:
i!     handle: type=cudnnHandle_t; streamId=(nil) (defaultStream);
i!     srcDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,896,1,832];
i!         strideA: type=int; val=[745472,832,832,1];
i!     srcData: location=dev; addr=0x7f1f46000000;
i!     filterDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[1792,896,1,19];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     filterData: location=dev; addr=0x7f1fc4000000;
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         mathType: type=cudnnMathType_t; val=CUDNN_TENSOR_OP_MATH (1);
i!         reorderType: type=int; val=0;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[0,9];
i!         strideA: type=int; val=[1,2];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     destDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[32,1792,1,416];
i!         strideA: type=int; val=[745472,416,416,1];
i!     destData: location=dev; addr=0x7f1f48d80000;
i!     requestedAlgoCount: type=int; val=8;
i!     returnedAlgoCount: location=host; addr=0x7ffd1db1e260;
i!     perfResults: location=host; addr=0x562d4de29310;
i!     workSpace: location=dev; addr=0x7f1f22000000;
i!     workSpaceSizeInBytes: type=size_t; val=453246976;
i! Time: 2021-04-02T20:20:58.376987 (0d+0h+0m+6s since start)
i! Process=20457; Thread=20457; GPU=0; Handle=0x562d0f5507f0; StreamId=(nil) (defaultStream).

</details>

<details>
 <summary>Onnxruntime</summary>


I! CuDNN (v8005) function cudnnFindConvolutionForwardAlgorithmEx() called:
i!     handle: type=cudnnHandle_t; streamId=0x556d192637c0;
i!     srcDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[4,896,128,1];
i!         strideA: type=int; val=[114688,128,1,1];
i!     srcData: location=dev; addr=0x7fbac2c7f200;
i!     filterDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[1792,896,19,1];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     filterData: location=dev; addr=0x7fb97c000000;
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         mathType: type=cudnnMathType_t; val=CUDNN_TENSOR_OP_MATH (1);
i!         reorderType: type=int; val=0;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[9,0];
i!         strideA: type=int; val=[2,1];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     destDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_HALF (2);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[4,1792,64,1];
i!         strideA: type=int; val=[114688,64,1,1];
i!     destData: location=dev; addr=0x7fb97fc00000;
i!     requestedAlgoCount: type=int; val=1;
i!     returnedAlgoCount: location=host; addr=0x7ffd76b1e7f0;
i!     perfResults: location=host; addr=0x7ffd76b1ea70;
i!     workSpace: location=dev; addr=0x7fb9a2000000;
i!     workSpaceSizeInBytes: type=size_t; val=33554432;
i! Time: 2021-04-02T20:20:39.710280 (0d+0h+0m+1s since start)
i! Process=20361; Thread=20361; GPU=0; Handle=0x556d19454340; StreamId=0x556d192637c0.

</details>

**Comment by BowenBao** [comment]
hi @II245 thank you for reporting with detailed information. Could you open an issue in https://github.com/microsoft/onnxruntime/ since it is onnxruntime performance related.

**Comment by II245** [comment]
@BowenBao ORT issue is here https://github.com/microsoft/onnxruntime/issues/7212 
Thank you for your reply, but I have a question about why pytorch set convDesc.dataType==CUDNN_DATA_FLOAT. It is odd because I work with half precision and expect something like CUDNN_DATA_HALF.

**Comment by garymm** [comment]
Performance difference between PyTorch and ORT is tracked by https://github.com/microsoft/onnxruntime/issues/7212. If you have a question, please use the PyTorch forum:
<https://discuss.pytorch.org/>
