### ISSUE TITLE
Building aten failed with master.

### ISSUE THREAD

**Issue by trivialfis** [pytorch/pytorch#5519]
OS: Fedora 27 x86_64
PyTorch version: Master at  commit a5e1b4efc90f8c0d195184de9060dc0295802402
Python version: Python 3.6.4
CUDA/cuDNN version: CUDA 9.0, cuDNN 7.0.5.15
GPU: GTX 960M
GCC: 6.4

The complete build log is attached.

[build_log.txt](https://github.com/pytorch/pytorch/files/1774198/build_log.txt)

**Comment by yf225** [comment]
Could you try with GCC 6.2.1? According to http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements 6.2.1 is the latest version tested with Fedora 25, so it might be worth trying out.

**Comment by yf225** [comment]
Probably related: https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/

**Comment by trivialfis** [comment]
Sorry for the late reply. It seems to be a bug in CUDA according to the link to CUDA form. Currently I don't plan to reinstall the system for this(it's quite messy) and I am ok with running Pytorch on CPU for now. 
You can close the issue if the officially supported platforms don't have this bug. 
:) Thanks.
