### ISSUE TITLE
Error LNK2001, for symbol state in C extension.

### ISSUE THREAD

**Issue by Qinka** [pytorch/pytorch#5520]
- OS: Windows 10
- PyTorch version: master( '0.4.0a0+0de5443')
- How you installed PyTorch (conda, pip, source): source
- Python version: Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
- CUDA/cuDNN version: CUDA-9.0
- GPU models and configuration: 
- VS 2015(v140 toolset)
When trying to compile C extension, linked with ATen, I got an error: can not found symbol `state`(error LNK2001).

And the librarys, THx are not compiled.

**Comment by peterjc123** [comment]
Changes the source code from C to C++. An example is listed below.

   ```cpp
   #include <THC/THC.h>
   #include <ATen/ATen.h>

   ATen_CLASS at::Context &at::globalContext();
   THCState *state = at::globalContext().thc_state;

   extern "C" int my_lib_add_forward_cuda(THCudaTensor *input1, THCudaTensor *input2,
                                          THCudaTensor *output)
   {
     if (!THCudaTensor_isSameSizeAs(state, input1, input2))
       return 0;
     THCudaTensor_resizeAs(state, output, input1);
     THCudaTensor_cadd(state, output, input1, 1.0, input2);
     return 1;
   }

   extern "C" int my_lib_add_backward_cuda(THCudaTensor *grad_output, THCudaTensor *grad_input)
   {
     THCudaTensor_resizeAs(state, grad_input, grad_output);
     THCudaTensor_fill(state, grad_input, 1);
     return 1;
   }
   ```

**Comment by Qinka** [comment]
@peterjc123 I found  `ATen_CLASS` is undefined, and codes can be compiled after removing it.

**Comment by Qinka** [comment]
So how to control the build type of MSVS. When building extension, what should I do if I what to build it in Debug mode.

**Comment by peterjc123** [comment]
@Qinka According to this [post](https://stackoverflow.com/questions/4659754/the-gs-g-option-equivalent-to-vs2010-cl-compiler), you should add `/ZI` flag for debug version.

**Comment by podgorskiy** [comment]
@peterjc123, thanks that helped me!

The part:

    ATen_CLASS at::Context &at::globalContext();
    THCState *state = at::globalContext().thc_state;

With current pytorch version, should be

    THC_CLASS at::Context& at::globalContext();
    THCState *state = at::globalContext().getTHCState();

**Comment by peterjc123** [comment]
Closing this, as it is not supported anymore.
