### ISSUE TITLE
broadcasting operation in forward function , onnx to tensorrt failed at torch1.8.1, successed in torch 1.7.1

### ISSUE THREAD

**Issue by GitHubChrischen** [pytorch/pytorch#55205]
## To Reproduce

I want to get tensorrt model, so I use pytorch -> onnx  -> trt ,  
when I update from torch1.7.1 to 1.8.1 ,  onnx-> trt  failed, and I find that broadingcasting failed.

code:
def forward(self, x):
....
y2 =  ((y[..., 2:4] * 2.) ** 2)   # shape is (1,3,128,128,2)
y2 = y2* self.anchor_grid[i]   # failed    self.anchor_grid[i]: (1,3,1,1,2)
....

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):1.8.1
 - OS (e.g., Linux):ubuntu18
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source): 
 - Python version: py37
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 3090
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
