### ISSUE TITLE
RuntimeError: kind_.is_prim()INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":1110, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::cat doesn't have one either. We don't know if this op has side effects.

### ISSUE THREAD

**Issue by WUSHUANGPPP** [pytorch/pytorch#55219]
## 🐛 Bug

When I deployed `torch.jit.script` with `torch.jit.fork` and `torch.jit.wait` in a mult-branch RNN network architecture.
I met the problem above after the program run two iteration successfully.Each of branch is a self-designed RNN model.

## To Reproduce

I sorry for that.The complete model are too complex to reproduce at this short time. 
Model：A model which have a module of a mult-branch structure and each branch is a self-designed  rnn.
When I code my forward funcation of my parallel model in the following approach,I met the problem mentioned in title.

`    
```
class BranchParallel(nn.Module):
    def __init__(
            self,
            block,
            branch = [0,1,2,3],
            layers,
            block_inplanes,
            n_class=200,
            n_input_channels=3,
            conv1_t_size=7,
            conv1_t_stride=1,
            no_max_pool=False,
            shortcut_type='B',
            widen_factor=1.0
    ):
        super().__init__()
        self.branch = branch

        self.module = torch.nn.ModuleList([
            RRNN(
                branch_no=i,
                block=block,
                layers=layers,
                block_inplanes=block_inplanes,
                n_input_channels=n_input_channels,
                conv1_t_size=conv1_t_size,
                conv1_t_stride=conv1_t_stride,
                no_max_pool=no_max_pool,
                shortcut_type=shortcut_type,
                widen_factor=widen_factor,
                n_classes=n_class
            ) for i in branch
        ])

    def forward(self,x:torch.Tensor)->List [torch.Tensor]:
        #self.module = torch.jit.script(self.module)
        """
        #return [self.module[i](x) for i in range(self.branch)]
        """
        future = [ torch.jit.fork(model,x) for model in self.module]
        results = [torch.jit.wait(fut) for fut in future ]
        return results
```
`
And the errors are:
`
Traceback (most recent call last):
  File "/apdcephfs/private/3D-trypara3/main.py", line 561, in <module>
    main_worker(-1, opt)
  File "/apdcephfs/private/3D-trypara3/main.py", line 480, in main_worker
    train_batch_logger,opt, tb_writer, opt.distributed,consistency_weight,opt.branch)
  File "/apdcephfs/private/3D-trypara3/training.py", line 82, in train_epoch
    outputs, logits,feature = model(inputs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/usr/local/lib64/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/apdcephfs/private/3D-trypara3/models/resnet.py", line 239, in forward
    results = self.module3(x)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/apdcephfs/private/3D-trypara3/models/resnet.py", line 159, in forward
        #return [self.module[i](x) for i in range(self.branch)]
        """
        future = [ torch.jit.fork(model,x) for model in self.module]
                   ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        results = [torch.jit.wait(fut) for fut in future ]
        return results
RuntimeError: kind_.is_prim()INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":1110, please report a bug to PyTorch. Only prim ops are allowed to not have a registered operator but aten::cat doesn't have one either. We don't know if this op has side effects.
`

## Expected behavior

Each branch run parallelly as the html tutorial in https://pytorch.org/tutorials/advanced/torch-script-parallelism.html#dynamic-parallelism-in-torchscript.

## Environment


```
PyTorch version: 1.9.0.dev20210310+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Tencent tlinux 2.2 (Final) (x86_64)
GCC version: (GCC) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2 
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 440.64.00
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.9.0.dev20210310+cu102
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] Could not collect
```


## Additional context

<!-- Add any other context about the problem here. -->

Thanks a lot,@gmagogsfm

**Comment by ansley** [comment]
We won't be able to work on the issue without a way to reproduce it. You say that you can't provide the model at this time. Will you be able to provide it later? If so, please add your minimal reproducible example to this issue and we'll start work on it.

**Comment by ansley** [comment]
Closed due to lack of follow-up. If the issue persists and you can provide an MRE, please feel free to open another issue!
