### ISSUE TITLE
Correct description of weight-dimensions in conv and conv_transpose docs

### ISSUE THREAD

**Issue by cjsg** [pytorch/pytorch#5521]
In the documentation of torch.nn.functional.conv{1,2,3}d, the weight dimensions should be:
out_channels x in_channels/**groups** x kH x kW

and for torch.nn.functional.conv_transpose{1,2,3}d, they should be:
in_channels x out_channels/**groups** x kH x kW.

Right now, the division by 'groups' is only included in the docs of torch.nn.functional.conv2d.
Of course, it's a detail, but I think that
(a) the docs of all conv functionals should be consistent and 
(b) this detail really helps understanding what 'groups' does.

**Comment by apaszke** [comment]
Good catch, can you please submit a PR?

**Comment by cjsg** [comment]
Ok. I will do so this week-end.

**Comment by soumith** [comment]
closed via #5543
