### ISSUE TITLE
[perf] at::result_type on Scalar internally constructs a tensor for the scalar before computing dtype

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#55229]
This is incredibly wasteful and means that if you are trying to short circuit, `at::result_type` is not allowed.

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang @VitalyFedyunin @ngimel

**Comment by ezyang** [comment]
cc @swolchok

**Comment by swolchok** [comment]
yes sir
