### ISSUE TITLE
RuntimeError: CUDA error: invalid configuration argument when using PyTorch code

### ISSUE THREAD

**Issue by momo1986** [pytorch/pytorch#55222]
## To Reproduce

Define some components:
` self.wave_pool = get_pool("scaled_adaptive_wavelet")`

The origin of the plug-in:
https://github.com/Fraunhofer-SCAI/wavelet_pooling

Failed in forward:
out = self.wave_pool(out)

Error-log:

> Traceback (most recent call last):
>   File "train_cifar.py", line 948, in <module>
>     main()
>   File "train_cifar.py", line 707, in main
>     fast_better=args.fast_better, BNeval=args.BNeval)
>   File "train_cifar.py", line 140, in attack_pgd
>     output = model(normalize(X + delta))
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/data/user1/junyan/adv_training/Bag-of-Tricks-for-AT/wideresnet.py", line 124, in forward
>     out = self.wave_pool(out)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/data/user1/junyan/adv_training/Bag-of-Tricks-for-AT/util/wavelet_pool2d.py", line 37, in forward
>     scales=self.scales)
>   File "/data/user1/junyan/adv_training/Bag-of-Tricks-for-AT/util/conv_transform.py", line 172, in conv_fwt_2d
>     res_ll = fwt_pad2d(res_ll, wavelet)
>   File "/data/user1/junyan/adv_training/Bag-of-Tricks-for-AT/util/conv_transform.py", line 97, in fwt_pad2d
>     mode='reflect')
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 3540, in _pad
>     return torch._C._nn.reflection_pad2d(input, pad)
> RuntimeError: CUDA error: invalid configuration argument

## Expected behavior

Should be work fine

## Environment

Collecting environment information...
PyTorch version: 1.8.0a0+17f8c32
Is debug build: True
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.38
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.8.0a0+17f8c32
[pip3] torchtext==0.8.0a0
[pip3] torchvision==0.8.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.19.2           py36h6163131_0  
[conda] numpy-base                1.19.2           py36h75fe3a5_0  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.8.0a0+17f8c32          pypi_0    pypi
[conda] torchtext                 0.8.0a0                  pypi_0    pypi
[conda] torchvision               0.8.0a0                  pypi_0    pypi

## Additional context

I modify the code during the research. Then met the problem, I just feel very curious about the root cause of the problem. How to resolve it?

Thanks & Regards!
Momo

cc @ngimel

**Comment by ngimel** [comment]
cc @xwang233

**Comment by xwang233** [comment]
Thanks for the report. This is likely a known issue, see https://github.com/pytorch/pytorch/issues/49601#issuecomment-760655598. We will provide a fix soon.

**Comment by momo1986** [comment]
Hello, @xwang233 , dear PyTorch team-members,

If I want to run my code normally, what version should I specify explicitly?

Thanks & Rehards!
Momo

**Comment by momo1986** [comment]
Any update? @xwang233

**Comment by xwang233** [comment]
@momo1986 I have filed a PR that would fix this issue. You should be able to verify the fix with a nightly build once the PR gets merged.
