### ISSUE TITLE
compiling pytorch on windows Unrecognized CMAKE_SYSTEM_NAME = Windows

### ISSUE THREAD

**Issue by mrdvince** [pytorch/pytorch#55224]
Going through the docs on compiling pytorch from source on windows, `Unrecognized CMAKE_SYSTEM_NAME = Windows`

The `Unrecognized CMAKE_SYSTEM_NAME = Windows` cmake error seems to occur when compiling the submodules in the thirdparty directory. And from the documentation can't seem to figure out a solution for this.

Initially was Unrecognized CMAKE_SYSTEM_PROCESSOR = AMD64 and the system variable, after checking out the 1.8 branch the Unrecognized CMAKE_SYSTEM_PROCESSOR = AMD64 this goes away. 

## To Reproduce

1. git clone --recursive https://github.com/pytorch/pytorch
2. cd pytorch
3. python setup.py install

<-- Error log -->
-- The ASM compiler identification is GNU
-- Found assembler: C:/ProgramData/chocoportable/bin/gcc.exe
CMake Error at third_party/QNNPACK/CMakeLists.txt:47 (MESSAGE):
  Unrecognized CMAKE_SYSTEM_NAME = Windows

-- Configuring incomplete, errors occurred!
See also "C:/Users/eggy/Projects/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/eggy/Projects/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "C:\Users\eggy\Projects\pytorch\tools\build_pytorch_libs.py", line 50, in build_caffe2
    cmake.generate(version,
  File "C:\Users\eggy\Projects\pytorch\tools\setup_helpers\cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "C:\Users\eggy\Projects\pytorch\tools\setup_helpers\cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\tools\miniconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=C:\\Users\\eggy\\Projects\\pytorch\\torch', '-DCMAKE_PREFIX_PATH=C:\\tools\\miniconda3\\Lib\\site-packages', '-DNUMPY_INCLUDE_DIR=C:\\tools\\miniconda3\\lib\\site-packages\\numpy\\core\\include', '-DPYTHON_EXECUTABLE=C:\\tools\\miniconda3\\python.exe', '-DPYTHON_INCLUDE_DIR=C:\\tools\\miniconda3\\include', '-DPYTHON_LIBRARY=C:\\tools\\miniconda3/libs/python38.lib', '-DTORCH_BUILD_VERSION=1.8.0a0+56b43f4', '-DUSE_NUMPY=True', 'C:\\Users\\eggy\\Projects\\pytorch']' returned non-zero exit status 1.

## Environment

 - OS: Windows 10 pro build 19042.867
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.8.5

cc @malfet @seemethere @walterddr

**Comment by imaginary-person** [comment]
Are you not using Visual Studio?

**Comment by GRAPHENE9932** [comment]
Yes, I have this issue too when cross compiling torch using MinGW on Linux for Windows. I have the similar output. I found in the CMakeLists.txt of QNNPACK that:
```
IF(NOT CMAKE_SYSTEM_NAME)
  MESSAGE(FATAL_ERROR "CMAKE_SYSTEM_NAME not defined")
ELSEIF(NOT CMAKE_SYSTEM_NAME MATCHES "^(Darwin|Linux|Android)$")
  MESSAGE(FATAL_ERROR "Unrecognized CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
ENDIF()
```
The problem is QNNPACK, but setup.py ignores my USE_QNNPACK=0 and NO_QNNPACK=1.

**Comment by Droid021** [comment]
> Are you not using Visual Studio?

Yeah, tried it and this is what I got

`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/tools/miniconda3/Library/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/eggy/Projects/pytorch/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/tools/miniconda3/Library/bin/ninja.exe cmTC_19ae9 && [1/2] Building CXX object CMakeFiles\cmTC_19ae9.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_19ae9.exe
`

So opted for MinGW

**Comment by Droid021** [comment]
@GRAPHENE9932 
> The problem is QNNPACK, but setup.py ignores my USE_QNNPACK=0 and NO_QNNPACK=1.

Yeah this did help but to get it to generate a build I also had to do a few changes in the aten quantized qnnpack CMakeLists.txt include AMD64, and Windows,

**Comment by peterjc123** [comment]
Building with GCC on Windows is not supported, as far as I know. You'll have to use VS2019.


> > Are you not using Visual Studio?
> 
> Yeah, tried it and this is what I got
> 
> `-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - broken
> CMake Error at C:/tools/miniconda3/Library/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
> The C++ compiler
> 
> ```
> "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"
> ```
> 
> is not able to compile a simple test program.
> 
> It fails with the following output:
> 
> ```
> Change Dir: C:/Users/eggy/Projects/pytorch/build/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):C:/tools/miniconda3/Library/bin/ninja.exe cmTC_19ae9 && [1/2] Building CXX object CMakeFiles\cmTC_19ae9.dir\testCXXCompiler.cxx.obj
> [2/2] Linking CXX executable cmTC_19ae9.exe
> ```
> 
> `
> 
> So opted for MinGW

How did you activate the VC environment?

**Comment by BouazzaSE** [comment]
Any updates and/or plans to support building with GCC or Clang on Windows?

**Comment by peterjc123** [comment]
@BouazzaSE 
For clang on Windows: https://github.com/pytorch/pytorch/pull/63288
