### ISSUE TITLE
How to use PyTorch with ROCm (radeon gpu)? How to transfer data to gpu? 

### ISSUE THREAD

**Issue by oconnor127** [pytorch/pytorch#55223]
Hey,
So far I didnt see any documentation or similar, which gives a hint how to use PyTorch with other GPUs than NVIDIA (when the new ROCm package is installed). How can I choose my radeon GPU as device and so use it for training? Very glad for any advices.

Best

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by imaginary-person** [comment]
The ROCm version is used in the same way as the CUDA version:
eg. `t = torch.tensor([5, 5, 5], dtype=torch.int64, device='cuda')`

**Comment by oconnor127** [comment]
Thank you very much. Guess my Radeon RX580 is not supported yet.

**Comment by imaginary-person** [comment]
> Guess my Radeon RX580 is not supported yet.

I think AMD ROCm [doesn't officially support it anymore](https://github.com/RadeonOpenCompute/ROCm/commit/2b7f806b106f2b19036bf8e7af4f3dad7bc6222e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L408), but this link also states, _Some of this software may work with more GPUs than the "officially supported" list above, though AMD does not make any official claims of support for these devices on the ROCm software platform_. So maybe the AMD folks CCed in this issue can clarify.

**Comment by imaginary-person** [comment]
@oconnor127, you might want to take a look at #53738 & check if the corresponding workaround exists for your GPU.

**Comment by hongxiayang** [comment]
@oconnor127  This is the updated documentation about what GPUs are supported: https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html

We are going to close this issue as this is very old.
