### ISSUE TITLE
torch.testing.all_types has a very confusing name

### ISSUE THREAD

**Issue by antocuni** [pytorch/pytorch#55231]
excerpts from `torch/testing/__init__.py`:
```python
_floating_types = _dispatch_dtypes((torch.float32, torch.float64))
_integral_types = _dispatch_dtypes((torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64))
...
_all_types = _floating_types + _integral_types
def all_types():
    return _all_types
```

The problem is that `all_types()` doesn't return all types, e.g. it misses complex types, bools, etc.
Even more confusingly, there is also `get_all_dtypes()` which seems to do the right thing.

I understand that these names were chosen to match the various `AT_DISPATCH_*` macros, but I seem to understand that we are promoting the usage of `torch.testing` to the general public, and these are all public functions defined in its `__init__.py`.
Possible solutions:

1. move them to `torch.testing._internal`. A quick grep reveals that they are used only there
2. take it as an opportunity to do a broader renaming of names, including ATen C++ files. E.g., what is now called `all_types` should called `default_types` or something similar
3. ignore the problem and maybe document the behavior, although IMHO it's very confusing
4. fix the names in `torch.testing` without fixing ATen. This is probably the worst solution as it will be very confusing for contributors and probably lead to bugs and/or missing tests

**Comment by mruberry** [comment]
You are absolutely correct, @antocuni, and we have decided to hide these names from the public and make them internal.
