### ISSUE TITLE
 _unflatten_dense_tensors isn't using the faster cpp version already in pytorch

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#55240]
## 🐛 Bug

pytorch has a cpp version of ` _flatten_dense_tensors` / `_unflatten_dense_tensors` but isn't using it.

https://github.com/pytorch/pytorch/blob/547346d66350b4ac325941752f53fa92f756f6a9/torch/csrc/utils/tensor_flatten.h#L10

The cpp version is about 2x faster for `flatten` and 2-3x faster for `unflatten` in the tests I have done.

If you want the benchmark that shows it, you can see:
https://github.com/microsoft/DeepSpeed/pull/910#issuecomment-812150852

Deepspeed's `UtilsBuilder` is just a python binding to the pytorch cpp version:
https://github.com/microsoft/DeepSpeed/blob/c814abdadd31d7a92ba2b77c48b2f042318a5a7f/csrc/utils/flatten_unflatten.cpp

cc @VitalyFedyunin @ngimel

**Comment by VitalyFedyunin** [comment]
We are happy to accept PR implementing this functionality.

**Comment by stas00** [comment]
You already have it implemented in the core. You just need to replace the slower python version with its C++ counterpart.

**Comment by stas00** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/58006
