### ISSUE TITLE
torch.log() returns -inf/nan on exponential input

### ISSUE THREAD

**Issue by yixin0829** [pytorch/pytorch#55269]
## 🐛 Bug

Hi, I noticed that in `torch.log()` it returns -inf or nan when inputting exponential input. For example, while 100 * log(2) returns valid output, log(2 **100) returns -inf. Is this supposed to be the way? Similar issue does not happen using python math lib.

## To Reproduce

```python
from math import *
import torch

x = torch.tensor(2)
print(torch.log(x ** 63 - 1)) # valid
print(torch.log(x ** 63)) # invalid (nan)
print(torch.log(x **100)) # invalid (-inf)
print(100 * torch.log(x)) # valid

# all valid (return float)
print(log(2 **63 -1))
print(log(2 **63))
print(log(2 **100))
print(100 *log(2))
```

## Expected behavior

see comments.

## Environment

Collecting environment information...
PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)

**Comment by kshitij12345** [comment]
Issue is that the `pow` does not promote dtypes (dtype of x is inferred to be `Long/int64`) and overflows leading to incorrect values. However the behavior is consistent with numpy. 

The reason it works in Python and Math is that plain int is unbounded and `2**100` and others do not overflow which math.log treats as double precision float and everything works.

(simplest solution is to initialise `x` as `x=torch.tensor(2.)`, post which the results match as expected)

```python
import torch
import numpy as np
from math import *

x = torch.tensor(2)
a = x.numpy()

print("NUMPY POWER")
print(a**62 )
print(a**63 )
print(a**64 )
print(a**100 )

print("TORCH POWER")
print(x**62, torch.pow(x, 62).dtype)
print(x**63, torch.pow(x, 63).dtype)
print(x**64, torch.pow(x, 64).dtype)
print(x**100, torch.pow(x, 100).dtype)

print("NUMPY LOG")
print(np.log(a ** 62)) # valid
print(np.log(a ** 63)) # invalid (nan)
print(np.log(a ** 64)) # invalid (-inf)
print(np.log(a **100)) # invalid (-inf)
print(100 * np.log(a)) # valid

print("TORCH LOG")
print(torch.log(x ** 62)) # valid
print(torch.log(x ** 63)) # invalid (nan)
print(torch.log(x ** 64)) # invalid (-inf)
print(torch.log(x **100)) # invalid (-inf)
print(100 * torch.log(x)) # valid

print("MATH LOG")
# all valid (return float)
print(log(2 **62))
print(log(2 **63))
print(log(2 **64))
print(log(2 **100))
print(100 *log(2))
```

Output:
<details>

```
NUMPY POWER
4611686018427387904
-9223372036854775808
0
0
TORCH POWER
tensor(4611686018427387904) torch.int64
tensor(-9223372036854775808) torch.int64
tensor(0) torch.int64
tensor(0) torch.int64
NUMPY LOG
42.97512519471661
test_log.py:20: RuntimeWarning: invalid value encountered in log
  print(np.log(a ** 63)) # invalid (nan)
nan
test_log.py:21: RuntimeWarning: divide by zero encountered in log
  print(np.log(a ** 64)) # invalid (-inf)
-inf
test_log.py:22: RuntimeWarning: divide by zero encountered in log
  print(np.log(a **100)) # invalid (-inf)
-inf
69.31471805599453
TORCH LOG
tensor(42.9751)
tensor(nan)
tensor(-inf)
tensor(-inf)
tensor(69.3147)
MATH LOG
42.97512519471661
43.66827237527655
44.3614195558365
69.31471805599453
69.31471805599453
```

</details>

**Comment by yixin0829** [comment]
Thanks! This makes much more sense now. closing the issue.
