### ISSUE TITLE
Building with MSVC 2019 Community Edition fails

### ISSUE THREAD

**Issue by catid** [pytorch/pytorch#55266]
## 🐛 Bug

Build fails on Windows with latest stable version of everything:

function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function

## To Reproduce

Trying to build this repo ( https://github.com/sunwj/CAR ) with MSVC 2019 Community Edition and latest stable PyTorch fails:

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include\xutility(4643): error: function "torch::OrderedDict<Key, Value>::Item::operator=(const torch::OrderedDict<std::string, at::Tensor>::Item &) [with Key=std::string, Value=at::Tensor]" (declared implicitly) cannot be referenced -- it is a deleted function
detected during:
instantiation of "_OutIt std::_Move_unchecked1(_InIt, _InIt, _OutIt, std::false_type) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
(4659): here
instantiation of "_OutIt std::_Move_unchecked(_InIt, _InIt, _OutIt) [with _InIt=torch::OrderedDict<std::string, at::Tensor>::Item *, _OutIt=torch::OrderedDict<std::string, at::Tensor>::Item *]"
C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include\vector(1353): here
instantiation of "std::vector<_Ty, _Alloc>::iterator std::vector<_Ty, _Alloc>::erase(std::vector<_Ty, _Alloc>::const_iterator) [with _Ty=torch::OrderedDict<std::string, at::Tensor>::Item, _Alloc=std::allocator<torch::OrderedDict<std::string, at::Tensor>::Item>]"
C:/Users/leon/AppData/Local/Programs/Python/Python39/lib/site-packages/torch/include\torch/csrc/api/include/torch/ordered_dict.h(419): here
instantiation of "void torch::OrderedDict<Key, Value>::erase(const Key &) [with Key=std::string, Value=at::Tensor]"
C:/Users/leon/AppData/Local/Programs/Python/Python39/lib/site-packages/torch/include/torch/csrc/api/include\torch/nn/modules/container/parameterdict.h(51): here

## Expected behavior

Build fails after running:
cd adaptive_gridsampler
python setup.py build_ext --inplace

## Environment

 - PyTorch Version Stable 1.8.1
 - OS: Windows
 - How you installed PyTorch: pip install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
 - Python version: Python 3.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: RTX 2080 Ti

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
Reproduced locally and can be fixed by adding the assignment operator for `torch::OrderedDict<Key, Value>::Item`.
```
    Item& operator=(const Item& other)
    {
      pair_ = other.pair_;
      return *this;
    }
```
Will add a fix for this.

**Comment by catid** [comment]
Awesome thanks! :)

I found that for some reason, building using ninja.exe on Windows succeeds without this fix, so maybe that's why people haven't fixed it yet.
