### ISSUE TITLE
cosine_similarity produces incorrect results for inputs of different shapes

### ISSUE THREAD

**Issue by huaxialongguang** [pytorch/pytorch#55273]
## To Reproduce

1. When the shapes of the two input Tensors are inconsistent, the value range of the calculation result of the cosine_similarity operator is [-1,1], but the actual calculation result is greater than 1. I think the operator cosine_similarity has a problem in broadcasting

2. The code to reproduce the problem is as follows：
```
import torch
import numpy as np
import torch.nn.functional as F
import torch
import numpy as np

a = np.arange(1, 5).reshape((2, 2, 1)).astype(np.float32)
b = np.zeros((2, 2, 3)).astype(np.float32)
c = a + b

a1 = np.arange(1, 7).reshape((2, 1, 3)).astype(np.float32)
c1 = a1 + b

input_x1 = torch.tensor(a)
print("===========input_x1=========== \n", input_x1)
input_x2 = torch.tensor(a1)
print("===========input_x2=========== \n", input_x2)
cos = torch.nn.CosineSimilarity(2, eps=1e-8)
res = cos(input_x1, input_x2)
print("=========pytorch_broadcast_calculate\n", res)


input_x1_1 = torch.tensor(c)
print("===========input_x1========== \n", input_x1_1)
input_x2_1 = torch.tensor(c1)
print("===========input_x2========== \n", input_x2_1)
cos = torch.nn.CosineSimilarity(2, eps=1e-8)
res = cos(input_x1_1, input_x2_1)
print("=========pytorc_direct_calculate\n", res)
```
3. The execution results are as follows
```
===========input_x1===========
 tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
===========input_x2===========
 tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])
=========pytorch_broadcast_calculate
 tensor([[1.6036, 1.6036],
        [1.7094, 1.7094]])
===========input_x1==========
 tensor([[[1., 1., 1.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [4., 4., 4.]]])
===========input_x2==========
 tensor([[[1., 2., 3.],
         [1., 2., 3.]],

        [[4., 5., 6.],
         [4., 5., 6.]]])
=========pytorc_direct_calculate
 tensor([[0.9258, 0.9258],
        [0.9869, 0.9869]])
```

## Environment
pytorch 1.5
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Hey @huaxialongguang, thanks for reporting this! As described in the [nn.CosineSimilarity docs](https://pytorch.org/docs/stable/generated/torch.nn.CosineSimilarity.html), the two inputs are expected to be the same shape. We'd accept a PR adding a check that enforces this to minimize confusion.

**Comment by huaxialongguang** [comment]
Thanks  for your reply
