### ISSUE TITLE
Does pytorchbot still work?

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#55298]
`pytorchbot rebase this please` did nothing.

Refernce: https://github.com/pytorch/pytorch/pull/55132#issuecomment-813321871

Reference to the wiki-page: https://github.com/pytorch/pytorch/wiki/Bot-commands

If it doesn't work then maybe wiki should be removed?

**Comment by izdeby** [comment]
Please, use our [forum](https://discuss.pytorch.org/) for questions.
