### ISSUE TITLE
Compilation Failure Ubuntu 16.04, CUDA 7.5, CuDNN 5.1 running a Titan X (Pascal)

### ISSUE THREAD

**Issue by davidstutz** [pytorch/pytorch#553]
I get the following when trying to install PyTorch on Ubuntu 16.04 running CUDA 7.5, CuDNN 5.1 with a Titan X (Pacal):

    Install the project...
    -- Install configuration: "Release"
    -- Installing: /is/ps2/dstutz/pytorch/torch/lib/tmp_install/lib/libTHNN.so.1
    -- Installing: /is/ps2/dstutz/pytorch/torch/lib/tmp_install/lib/libTHNN.so
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- TH_LIBRARIES: /is/ps2/dstutz/pytorch/torch/lib/tmp_install/lib/libTH.so.1
    -- Found CUDA: /usr (found suitable version "7.5", minimum required is "5.5") 
    -- Found gcc >=5 and CUDA <= 7.5, adding workaround C++ flags
    -- MAGMA not found. Compiling without MAGMA support
    -- Autodetected CUDA architecture(s): 6.1
    -- got cuda version 7.5
    -- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
    -- CUDA_NVCC_FLAGS:  -DTH_INDEX_BASE=0 -I/is/ps2/dstutz/pytorch/torch/lib/tmp_install/include -I/is/ps2/dstutz/pytorch/torch/lib/tmp_install/include/TH -I/is/ps2/dstutz/pytorch/torch/lib/tmp_install/include/THC;-gencode;arch=compute_61,code=sm_61;-DCUDA_HAS_FP16=1
    -- THC_SO_VERSION: 1
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        THCUNN_SO_VERSION
        THC_LIBRARIES
        THNN_SO_VERSION
        THS_LIBRARIES
        TH_SO_VERSION

    -- Build files have been written to: /is/ps2/dstutz/pytorch/torch/lib/build/THC
    [  1%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
    [  2%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
    [  5%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
    [  5%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
    [  7%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
    [  8%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
    [ 11%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
    [ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
    [ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
    [ 13%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
    [ 15%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
    [ 15%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o

    CMake Error at THC_generated_THCBlas.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

    CMakeFiles/THC.dir/build.make:91: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/THC.dir/build.make:70: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o

    CMake Error at THC_generated_THCTensorMathBlas.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathBlas.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMakeFiles/THC.dir/build.make:126: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o] Error 1
    CMake Error at THC_generated_THCTensorMathMagma.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathMagma.cu.o

    CMakeFiles/THC.dir/build.make:133: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o] Error 1
    CMakeFiles/THC.dir/build.make:63: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCTensor.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o

    CMakeFiles/THC.dir/build.make:98: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCSleep.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCSleep.cu.o

    CMakeFiles/THC.dir/build.make:77: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o] Error 1
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o

    CMakeFiles/THC.dir/build.make:105: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCHalf.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCTensorMath.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMake Error at THC_generated_THCTensorMath2.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath2.cu.o

    nvcc fatal   : Unsupported gpu architecture 'compute_61'
    CMakeFiles/THC.dir/build.make:546: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
    CMake Error at THC_generated_THCStorage.cu.o.cmake:207 (message):
      Error generating
      /is/ps2/dstutz/pytorch/torch/lib/build/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o

    CMakeFiles/THC.dir/build.make:112: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
    CMakeFiles/THC.dir/build.make:119: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o] Error 1
    CMakeFiles/THC.dir/build.make:84: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
    make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/THC.dir/all' failed
    make[1]: *** [CMakeFiles/THC.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2

So clearly, PyTorch seems to complain about the Titan X and compute capability 6.1. Is Pascal not supported? If not, I would appreciate any hints for workarounds to get it running.

Some more background information:

    $ nvidia-smi
    Mon Jan 23 15:36:37 2017       
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |===============================+======================+======================|
    |   0  TITAN X (Pascal)    Off  | 0000:03:00.0     Off |                  N/A |
    | 23%   32C    P8    14W / 250W |      1MiB / 12189MiB |      0%      Default |
    +-------------------------------+----------------------+----------------------+
    |   1  NVS 310             Off  | 0000:04:00.0     N/A |                  N/A |
    | 30%   44C    P0    N/A /  N/A |    598MiB /   963MiB |     N/A      Default |
    +-------------------------------+----------------------+----------------------+
    $ nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2015 NVIDIA Corporation
    Built on Tue_Aug_11_14:27:32_CDT_2015
    Cuda compilation tools, release 7.5, V7.5.17

I installed CUDA using

    $ sudo apt-get install nvidia-367
    $ sudo apt-get install nvidia-cuda-dev nvidia-cuda-toolkit

(which installs CUDA to `/usr/local/cuda-8.0` although it seems to be CUDA 7.5). CuDNN was installed manually.

Although it should not change anything, I tried the same with the master branch as well as v0.1.7.

Thanks!

**Comment by soumith** [comment]
if you have a Titan-X Pascal, the minimum CUDA version required is CUDA 8.0.
This is not a PyTorch requirement but NVIDIA's itself.

CUDA 7.5 does not recognize CUDA Compute Architecture 6.0/6.1

I suggest that you upgrade to CUDA 8.0

**Comment by davidstutz** [comment]
Hmm that sounds logical and I feel a bit stupid. Interestingly, I did not have any problems building other libraries with this combination (e.g. Tensorflow, Caffe ...). Thanks anyway!

**Comment by soumith** [comment]
I presume that the other libraries dont build themselves for the cards available on your machine, but generically build for 5.2+PTX. As a result, their startup time might be a bit long, as the 5.2+PTX code has to be JITted to 6.1 when you run your code the first time.

**Comment by davidstutz** [comment]
Ah ok, thanks for the explanation.

**Comment by mgarbade** [comment]
Changing the PATH and LD_LIBRARY_PATH to enforce the usage of CUDA 8.0 solved it for me too. Thanks for this post!
(using Ubuntu 14.04 and cudnn v5.1, Titan X - Pascal)

**Comment by ashr59** [comment]
Hi, I'm using Fedora 23, cuda 7.5, cudnn 4 and Titan X - Maxwell.
When I wanted to install Pytorch from source, I faced also:
nvcc fatal   : Unsupported gpu architecture 'compute_60'
that should not be accrued using Maxwell version.
I have much more problems with installing Cuda 8.0 on my system (system crash).
Is there any alternative solution for my situation except installing Cuda 8.0?

**Comment by soumith** [comment]
@ashr59 I just pushed a fix for this now via https://github.com/pytorch/pytorch/commit/1baae004bf5cd72f23926f7db1df8e1860c46a57 Please reclone pytorch from source and compile.

**Comment by ashr59** [comment]
@soumith OK, thanks for your quick response.

**Comment by ashr59** [comment]
@soumith I can now confirm that PyTorch works well using Cuda 7.5. I had some difficulties with Conda as reported [here](https://github.com/pytorch/pytorch/issues/2036), so I switch to pip and everything works perfectly. Thank you again.
