### ISSUE TITLE
Typing issue on state_dict/load_state_dict

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#55302]
The current typing says that state_dict returns a `Dict[str, Tensor]` while load_state_dict expects `OrderedDict[str, Tensor]`.

This mean that doing something like `mod.load_state_dict(other_mod.state_dict())` will fail type checking as reported in https://discuss.pytorch.org/t/load-state-dict-does-not-work-help-needed-for-copying-models/115229

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by malfet** [comment]
If I understand 
https://github.com/pytorch/pytorch/blob/f9a0bbbeb8c8d188ebe8a7c0f04702079f528d84/torch/nn/modules/module.py#L1194-L1195 correctly, problem here is that in Python-3.x OrderedDict does not support generics

**Comment by rgommers** [comment]
`typing_extensions` doesn't have `OrderedDict`, so there doesn't seem to be a nice solution for Python 3.6. Once py36 is dropped, all `OrderedDict` usages can be cleaned up, because `dict` is ordered then.

Could indeed change the overload now for Python >= 3.7

**Comment by malfet** [comment]
@rgommers I can implement the wrapper, but I wonder if stringifying return type will solve correctness problem for py-3.6 and typing for py-3.7 and newer

**Comment by malfet** [comment]
Actually, according to https://github.com/python/mypy/issues/6904#issuecomment-496207426 stringifying should just work

**Comment by rgommers** [comment]
Ah yes, that makes sense.
