### ISSUE TITLE
Detached tensor in channels_last format fails in the next layer

### ISSUE THREAD

**Issue by SeungjunNah** [pytorch/pytorch#55301]
## 🐛 Bug

When a channels_last format tensor is detached, it fails to operate on another model.

## To Reproduce

Here is an example code that produces an unexpected error.

```python
import torch
import torch.nn as nn
import torch.cuda.amp as amp

device = torch.device('cuda')
dtype = torch.float32
memory_format = torch.channels_last
# memory_format = torch.contiguous_format

model1 = nn.Conv2d(3,3,1,1).to(device=device, dtype=dtype, non_blocking=True, memory_format=memory_format)
model2 = nn.Conv2d(3,3,1,1).to(device=device, dtype=dtype, non_blocking=True, memory_format=memory_format)

input = torch.randn(1,3,4,4).to(device, dtype=dtype, memory_format=memory_format)

with amp.autocast():
    out1 = model1(input)
    out2 = model2(out1.detach())
```

Running the code produces the following error message.
```bash
Traceback (most recent call last):
  File "channels_last_detach.py", line 17, in <module>
    out2 = model2(out1.detach())
  File "/home/seungjun/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/seungjun/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/seungjun/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: set_sizes_and_strides is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

The above code runs fine when the memory_format is set to `torch.contiguous_format` but setting the memory format to `torch.channels_last` does not work.

## Expected behavior

The above code should successfully compute out2 without error.
When I ran the code with pytorch 1.7.1, it worked fine.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
```bash
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.67

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.0a0+e4e171a
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he8ac12f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.2           py37h54aff64_0
[conda] numpy-base                1.19.2           py37hfa32c7d_0
[conda] pytorch                   1.8.1           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.1                      py37    pytorch
[conda] torchvision               0.9.1                py37_cu111    pytorch
```

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:  11.1.1 / 8.0
 - GPU models and configuration: RTX 2080 Ti
 - Any other relevant information:

## Additional context

In contrast to the error message, there is no resize/reshape etc. operation on the detached tensor.
I assume this could be a bug in the newly introduced restriction on the `detach` function.

cc @VitalyFedyunin @jamesr66a @ppwwyyxx

**Comment by nico-zck** [comment]
I encountered the same problem when I tried to implement GANs.

**Comment by SeungjunNah** [comment]
Hi @nico-zck

I use the channels_last format to optimize code for tensor core operations in fp16 (for the best running speed).
Calling `.contiguous()` function changes the memory format from channels_last to contiguous format.

The mixed-precision operation via `amp.autocast` can work without explicit channels_last format input but it internally performs the transposition, resulting in performance regression.

By the way, the `out1` tensor is already contiguous with the proper memory_format
`out1.is_contiguous(memory_format=torch.channels_last)` is `True`.

Currently, I'm using a workaround as follows:
```python
with torch.no_grad():
    out1_clone = out1.detach().clone()
out2 = model2(out1_clone)
```

**Comment by nico-zck** [comment]
Hi @SeungjunNah,

Yes, I agree with your idea that calling `.contiguous()` function will change the memory format, and it may degrade computation efficiency when using automatic mixed precision. But I still two concerns about the `detach` function. 

The first concern. In your test code, the operations of model2 in your code should not involve changing the metadata of a Tensor if you set `memory_format` properly. Thus, I think the function `.detach()` incurs some strange problems while `.detach().clone()` can solve them.

The second concern. If I just do some basic operations that produce a non-continuous tensor, the following `detach` function will still bring the same issue. However, I think the printed hints "If your intent is to change the metadata of a Tensor" does not disclose the real reason for this error.

**Comment by SeungjunNah** [comment]
@nico-zck 
Yes, I understand your concerns and wish this bug to be fixed soon.
My workaround also essentially introduces speed slow-down due to memory copy (though it may not be big) and it makes the source code cluttered.

The restriction in applying several operations on the detached tensors was introduced in PyTorch v1.8.
I had to modify my source code as above when I upgraded the PyTorch version.
I assume the non-allowed operation detection for channels last format was not implemented correctly and it is blocking our use cases.
i.e. multi-module joint training scenarios including GAN under mixed-precision settings

cc @VitalyFedyunin @jamesr66a @ppwwyyxx
Could you look into this issue?

**Comment by milesial** [comment]
Adding a datapoint, I also encoutered this bug

```
PyTorch version: 1.10.0a0+ecc3718
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.0
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-15-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB-N
Nvidia driver version: 440.64.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] nvidia-dlprof-pytorch-nvtx==1.3.0
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.10.0a0+ecc3718
[pip3] torchtext==0.11.0a0
[pip3] torchvision==0.11.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.21.1           py38h9894fe3_0    conda-forge
[conda] nvidia-dlprof-pytorch-nvtx 1.3.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.0                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.10.0a0+ecc3718          pypi_0    pypi
[conda] torchtext                 0.11.0a0                 pypi_0    pypi
[conda] torchvision               0.11.0a0                 pypi_0    pypi
```

**Comment by xwang233** [comment]
The resize is from cudnn convolution implementation in pytorch here, which was added in PR https://github.com/pytorch/pytorch/pull/31952

https://github.com/pytorch/pytorch/blob/084e92bb7624b5ccb2e035a74d2a85b0b7d13b76/aten/src/ATen/native/cudnn/ConvShared.cpp#L253-L256

Per @jjsjann123 's comment https://github.com/pytorch/pytorch/pull/31783#issuecomment-571384334

cc @ptrblck
