### ISSUE TITLE
Add `padding_value` to `pad_sequence`

### ISSUE THREAD

**Issue by Evpok** [pytorch/pytorch#5532]
It would be nice if [`torch.nn.utils.rnn.pad_sequence`](http://pytorch.org/docs/master/nn.html#torch.nn.utils.rnn.pad_sequence) had a `padding_value` similar to [`torch.nn.utils.rnn.pad_packed_sequence`](http://pytorch.org/docs/master/nn.html#torch.nn.utils.rnn.pad_packed_sequence) one.

This should be relatively easy and I already have a PR ready, but I am unsure of the policy for that kind of nearly trivial changes.

**Comment by apaszke** [comment]
If you have the code already then PRs are welcome :) Thanks!

**Comment by ryanleary** [comment]
This can be closed (by #5540).
