### ISSUE TITLE
Unable to download libtorch (1.8.1) from pytorch.org

### ISSUE THREAD

**Issue by goswamig** [pytorch/pytorch#55345]
Following links returns `403`

Download here (Pre-cxx11 ABI):
https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.1.zip

Download here (cxx11 ABI):
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.1.zip

**Comment by goswamig** [comment]
@soumith

**Comment by izdeby** [comment]
Closing as a fix is provided. Please reopen in case if the issue is still present

**Comment by goswamig** [comment]
The issue is still there, I still can't download those binaries.

**Comment by imaginary-person** [comment]
@goswamig

https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.1%2Bcu102.zip

https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcu102.zip
