### ISSUE TITLE
torch.sigmoid throws RuntimeError on GPU for complex datatype

### ISSUE THREAD

**Issue by DLtangsan** [pytorch/pytorch#55359]
## 🐛 Bug
`torch.sigmoid` throws `RuntimeError` on GPU for `complex` datatype. According to https://pytorch.org/docs/stable/generated/torch.sigmoid.html, no constraint is proposed. It's bad that CPU runs successfully while GPU does not. 

## To Reproduce
```
t = torch.tensor(complex(3, 2))
print(torch.sigmoid(t))
print(torch.sigmoid(t.cuda()))
```

## Expected behavior
The output is
```
tensor(1.0190+0.0471j)
Traceback (most recent call last):
    print(torch.sigmoid(t.cuda()))
RuntimeError: "sigmoid_cuda" not implemented for 'ComplexFloat'
```

## Environment
PyTorch Version (e.g., 1.0): 1.8
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): pip
Python version: 3.6.6
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: A100

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by mruberry** [comment]
Thank you for reporting this issue, @DLtangsan. It would be nice to extend complex support to CUDA, and I agree with you that our documentation could be clearer about which dtypes are supported (and on which device types they're supported). 

We would definitely accept a PR implementing this.

**Comment by mruberry** [comment]
Reserving for onboarding.
