### ISSUE TITLE
Is there a way to remove all zero elements in one line?

### ISSUE THREAD

**Issue by DeweiHu66666** [pytorch/pytorch#55362]
I'm doing a model interpretability task in NLP, and I want to mask some of the words.  After this, my data looks like this: [1,3,0,6,0,0,2,1,0,0], where zeros are mask or padding tokens. Then I'm going to delete all zeros in the data.  Thanks in advance: )

**Comment by kshitij12345** [comment]
I think torch.nonzero might interest you.
Reference: https://pytorch.org/docs/stable/generated/torch.nonzero.html

**Note** : I think this question is more suited for the [forums](https://discuss.pytorch.org/)

**Comment by DeweiHu66666** [comment]
> I think torch.nonzero might interest you.
> Reference: https://pytorch.org/docs/stable/generated/torch.nonzero.html
> 
> **Note** : I think this question is more suited for the [forums](https://discuss.pytorch.org/)

Thanks, @kshitij12345.  I found a solution in the forums here: https://discuss.pytorch.org/t/how-to-remove-an-element-from-a-1-d-tensor-by-index/23109/6.
Sorry for that, I'm new to PyTorch and programming, but I now know how to ask questions. Have a nice day: )

**Comment by kshitij12345** [comment]
No worries. Great to know that you were able to find a solution.
