### ISSUE TITLE
torch.exp throws RuntimeError if running torch.float16

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#55360]
## 🐛 Bug
`torch.exp` throws `RuntimeError` if running `torch.float16`.

## To Reproduce
```
import torch
a=torch.ones(1,dtype=torch.bfloat16)
print(torch.exp(a))

a=torch.ones(1,dtype=torch.float16)
print(torch.exp(a))
```
The output is
```
tensor([2.7188], dtype=torch.bfloat16)
Traceback (most recent call last):
    print(torch.exp(a))
RuntimeError: "exp" "_vml_cpu" not implemented for 'Half'
```
## Expected behavior
`torch.float16` (`half`) is expected to run without exception, like `bfloat16`.

## Environment
PyTorch Version (e.g., 1.0): 1.8
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): pip
Python version: 3.6.6
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: A100

**Comment by imaginary-person** [comment]
`exp_vml_cpu` can't currently be enabled for `float16` on CPU due to lack of complete AVX2 vectorization support for `float16` in the codebase.

That's why `exp` for `float16` is unsupported for `float16` on CPU, although it's supported on CUDA.
