### ISSUE TITLE
JIT failed after upgrade from 1.5.0 to 1.8.1

### ISSUE THREAD

**Issue by CaoZhongZ** [pytorch/pytorch#55386]
Is this construct not allowed anymore?

```
RuntimeError: 
Unknown type name 'nn.Module':
  File ".../transformers/src/transformers/modeling_utils.py", line 421
    @property
    def base_model(self) -> nn.Module:
                            ~~~~~~~~~ <--- HERE
        """
        :obj:`torch.nn.Module`: The main body of the model.
```

cc @gmagogsfm

**Comment by CaoZhongZ** [comment]
Ah, it seems torch JIT expanded compilation scope which covered something v1.5 never covered.

**Comment by lifeiteng** [comment]
@CaoZhongZ How did you fix it?

**Comment by CaoZhongZ** [comment]
Remove the return type. I kind forgot given years passed. The issue persists?

**Comment by lifeiteng** [comment]
> Remove the return type. I kind forgot given years passed. The issue persists?
yes
