### ISSUE TITLE
quantize_per_tensor and quantize_per_channel should work on fp16 tensors

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#55387]
## 🐛 Bug

Currently the functions to quantize a tensor only work on fp32 tensors.  Simple repro:

```
>>> import torch                                                             
>>> x_fp32 = torch.randn(2, 2)                                               
>>> x_fp32                                                                   
tensor([[-0.3633, -0.2473],                                                  
        [-0.1735, -1.8445]])                                                 
>>> x_fp16 = x_fp32.half()                                                   
>>> x_fp16                                                                   
tensor([[-0.3633, -0.2473],                                                  
        [-0.1735, -1.8447]], dtype=torch.float16)                            
>>> x_fp16_to_int8 = torch.quantize_per_tensor(x_fp16, 0.1, 0, torch.quint8) 
Traceback (most recent call last):                                           
  File "<stdin>", line 1, in <module>                                        
RuntimeError: quantize only works on Float Tensor.                           
>>>                                                                          
```

It should work on fp16 tensors as well.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
do we have a use case for this? we have fp16 as a quantization target type as well, it might be a bit confusing for us to support both in quntize_per_tensor actually.

**Comment by vkuzo** [comment]
> do we have a use case for this? we have fp16 as a quantization target type as well, it might be a bit confusing for us to support both in quntize_per_tensor actually.

This is useful when people train with amp on CUDA, to get the speedup of fp16 vs fp32.

**Comment by jerryzh168** [comment]
I see, makes sense, just to confirm, the use case is people first train with amp so the model is fp16 and then do post training quantization?

**Comment by HDCharles** [comment]
this has now been implemented

**Comment by rllin** [comment]
@HDCharles where was this implemented and what version is this supported in?

im in `1.12.0` and I still see this for float16

```
    tensor = torch.quantize_per_tensor(tensor, 1, 1, torch.qint8)
RuntimeError: Quantize only works on Float Tensor, got Half
```
