### ISSUE TITLE
Undefined behavior in prepack() for quantized EmbeddingBag

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#55396]
## 🐛 Bug

I'm getting a [failing ASan check](https://app.circleci.com/pipelines/github/pytorch/pytorch/296293/workflows/23c035b5-adb8-48a5-bca9-2073d980ab25/jobs/12130606) identifying undefined behavior when instantiating a quantized EmbeddingBag module. The error points to these lines of code: https://github.com/pytorch/pytorch/blob/f8788d518854907099c50fcba520e7b8460b5ac0/aten/src/ATen/native/quantized/cpu/qembeddingbag_prepack.cpp#L83-L85

## To Reproduce

```python
import torch
m = torch.nn.quantized.EmbeddingBag(10, 3)
```

(seems to fail the ASan check intermittently)

## Expected behavior

No undefined behavior; ASan checks pass.

## Environment

I've only seen this happen in [CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/296293/workflows/23c035b5-adb8-48a5-bca9-2073d980ab25/jobs/12130606); I am unable to reproduce the issue when running ASan locally.

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a @vkuzo

**Comment by raghuramank100** [comment]
Is this a high Pri item? Should we track this for 1.9?

**Comment by supriyar** [comment]
Unable to repro this locally, test is passing on CI.
