### ISSUE TITLE
problem encountered when installing pytorch from source on ubuntu 16.04.3

### ISSUE THREAD

**Issue by xinsirBUPT2016** [pytorch/pytorch#5539]
PyTorch GitHub Issues Guidelines
-------------------------------
- OS ubuntu16.04:
- PyTorch version: I use the command git clone --recursive https://github.com/pytorch/pytorch to get the 
                              source code
- I have installed  conda, cuda, and cudnn
- Python version: python 3.6
- CUDA/cuDNN version: CUDA 8.0 and cuDNN 7.1
- GPU models and configuration: GeForce GTX950M(Notebook)
- GCC version (if compiling from source): gcc 4.8.5 

I follow the instructions on the https://github.com/pytorch/pytorch#from-source and type the commands:
export CMAKE_PREFIX_PATH="/home/xinqi/anaconda3/bin"
conda install numpy pyyaml mkl setuptools cmake cffi typing
conda install -c pytorch magma-cuda80
git clone --recursive https://github.com/pytorch/pytorch
python setup.py install

however I got wrong message when running the "python setup.py install" as below:
/home/xinqi/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/xinqi/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

the detailed message are:

warning: no library file corresponding to '/usr/local/cuda/lib64/libcudnn.so.7' found (skipping)
gcc -pthread -shared -B /home/xinqi/anaconda3/compiler_compat -L/home/xinqi/anaconda3/lib -Wl,-rpath=/home/xinqi/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/torch/csrc/PtrWrapper.o build/temp.linux-x86_64-3.6/torch/csrc/Module.o build/temp.linux-x86_64-3.6/torch/csrc/Generator.o build/temp.linux-x86_64-3.6/torch/csrc/Size.o build/temp.linux-x86_64-3.6/torch/csrc/Dtype.o build/temp.linux-x86_64-3.6/torch/csrc/Exceptions.o build/temp.linux-x86_64-3.6/torch/csrc/Storage.o build/temp.linux-x86_64-3.6/torch/csrc/DataLoader.o build/temp.linux-x86_64-3.6/torch/csrc/DynamicTypes.o build/temp.linux-x86_64-3.6/torch/csrc/assertions.o build/temp.linux-x86_64-3.6/torch/csrc/byte_order.o build/temp.linux-x86_64-3.6/torch/csrc/utils.o build/temp.linux-x86_64-3.6/torch/csrc/utils/cuda_lazy_init.o build/temp.linux-x86_64-3.6/torch/csrc/utils/invalid_arguments.o build/temp.linux-x86_64-3.6/torch/csrc/utils/object_ptr.o build/temp.linux-x86_64-3.6/torch/csrc/utils/python_arg_parser.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_list.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_new.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_numpy.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_dtypes.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_types.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tuple_parser.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_apply.o build/temp.linux-x86_64-3.6/torch/csrc/utils/tensor_flatten.o build/temp.linux-x86_64-3.6/torch/csrc/utils/variadic.o build/temp.linux-x86_64-3.6/torch/csrc/allocators.o build/temp.linux-x86_64-3.6/torch/csrc/serialization.o build/temp.linux-x86_64-3.6/torch/csrc/jit/init.o build/temp.linux-x86_64-3.6/torch/csrc/jit/interpreter.o build/temp.linux-x86_64-3.6/torch/csrc/jit/ir.o build/temp.linux-x86_64-3.6/torch/csrc/jit/fusion_compiler.o build/temp.linux-x86_64-3.6/torch/csrc/jit/graph_executor.o build/temp.linux-x86_64-3.6/torch/csrc/jit/python_ir.o build/temp.linux-x86_64-3.6/torch/csrc/jit/test_jit.o build/temp.linux-x86_64-3.6/torch/csrc/jit/tracer.o build/temp.linux-x86_64-3.6/torch/csrc/jit/tracer_state.o build/temp.linux-x86_64-3.6/torch/csrc/jit/python_tracer.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/shape_analysis.o build/temp.linux-x86_64-3.6/torch/csrc/jit/interned_strings.o build/temp.linux-x86_64-3.6/torch/csrc/jit/type.o build/temp.linux-x86_64-3.6/torch/csrc/jit/export.o build/temp.linux-x86_64-3.6/torch/csrc/jit/autodiff.o build/temp.linux-x86_64-3.6/torch/csrc/jit/interpreter_autograd_function.o build/temp.linux-x86_64-3.6/torch/csrc/jit/python_arg_flatten.o build/temp.linux-x86_64-3.6/torch/csrc/jit/python_compiled_function.o build/temp.linux-x86_64-3.6/torch/csrc/jit/variable_flags.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/create_autodiff_subgraphs.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/graph_fuser.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/onnx.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/dead_code_elimination.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/common_subexpression_elimination.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/peephole.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/inplace_check.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/canonicalize.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/batch_mm.o build/temp.linux-x86_64-3.6/torch/csrc/jit/passes/onnx/peephole.o build/temp.linux-x86_64-3.6/torch/csrc/jit/generated/aten_dispatch.o build/temp.linux-x86_64-3.6/torch/csrc/jit/script/lexer.o build/temp.linux-x86_64-3.6/torch/csrc/jit/script/compiler.o build/temp.linux-x86_64-3.6/torch/csrc/jit/script/init.o build/temp.linux-x86_64-3.6/torch/csrc/jit/script/python_tree_views.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/init.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/grad_mode.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/engine.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/function.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/variable.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/saved_variable.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/input_buffer.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/profiler.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_function.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_cpp_function.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_variable.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_variable_indexing.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_engine.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/python_hook.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/VariableType.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/Functions.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/python_torch_functions.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/python_variable_methods.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/python_functions.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/generated/python_nn_functions.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/basic_ops.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/tensor.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/accumulate_grad.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/special.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/utils.o build/temp.linux-x86_64-3.6/torch/csrc/autograd/functions/init.o build/temp.linux-x86_64-3.6/torch/csrc/nn/THNN.o build/temp.linux-x86_64-3.6/torch/csrc/tensor/python_tensor.o build/temp.linux-x86_64-3.6/torch/csrc/onnx/onnx.pb.o build/temp.linux-x86_64-3.6/torch/csrc/onnx/onnx.o build/temp.linux-x86_64-3.6/torch/csrc/distributed/Module.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/Module.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/Storage.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/Stream.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/utils.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/comm.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/python_comm.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/serialization.o build/temp.linux-x86_64-3.6/torch/csrc/nn/THCUNN.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/nccl.o build/temp.linux-x86_64-3.6/torch/csrc/cuda/python_nccl.o -L/home/xinqi/pytorch/torch/lib -L/usr/local/cuda/lib64 -lshm -lcudart -lnvToolsExt -o build/lib.linux-x86_64-3.6/torch/_C.cpython-36m-x86_64-linux-gnu.so -Wl,-rpath,/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 /home/xinqi/pytorch/torch/lib/libATen.so.1 /home/xinqi/pytorch/torch/lib/libprotobuf-nanopb.a /home/xinqi/pytorch/torch/lib/libTHD.a /home/xinqi/pytorch/torch/lib/libnccl.so.1 -Wl,-rpath,$ORIGIN/lib /home/xinqi/pytorch/torch/lib/tmp_install/lib/libATen.so /home/xinqi/pytorch/torch/lib/tmp_install/lib/libgloo.a /home/xinqi/pytorch/torch/lib/tmp_install/lib/libgloo_cuda.a
/home/xinqi/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/xinqi/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

I have tried many methods but still can't fix this problem, so I just paste it to look for some help.

**Comment by lanpa** [comment]
googled and found this: https://github.com/cocodataset/cocoapi/issues/94

**Comment by ezyang** [comment]
Try making a fresh conda environment from scratch and then running again. You want to be using your system linker and `compiler_compat` is in the way.
