### ISSUE TITLE
Multi-GPU execution error

### ISSUE THREAD

**Issue by thomasjanssens** [pytorch/pytorch#554]
I'm running PyTorch on a system with 4 Nvidia K10 GPUs and can't get the Multi-GPU code to work. I attempted to modify the first neural net in the 60-minute tutorial to run on all my GPUs, by adding this line to the cell defining the network:

`net = torch.nn.DataParallel(net, device_ids=[0, 1, 2, 3]).cuda()`

If I then attempt to use the net as follows
`input = Variable(torch.randn(1, 1, 32, 32)).cuda()`
`out = net(input)`,
Jupyter waits a few seconds and reports the kernel has died. Following along in `nvidia-smi` I see all GPUs encountering an `Unknown Error` at the same moment. Am I using the API wrong, could there be a configuration issue in my system, or is this a bug in the DataParallel implementation?

I'm using CUDA 8 and PyTorch 0.1.6. 

Edit: my Nvidia driver version is 367.48 I also forgot to add, executing the above code on CUDA without parallelization (i.e. `net = net.cuda()`) works fine.

**Comment by soumith** [comment]
Is there a stack-trace that you see appear on the command-line of the Jupyter process?

Is this a cloud provider box? (I ask to see if I can reproduce it myself)

**Comment by thomasjanssens** [comment]
This is the only command-line output Jupyter gives related to the error:
`Cuda failure src/broadcast.cu:144 'invalid device function'`

I'm running this on an in-house compute node.

**Comment by soumith** [comment]
thanks. this is helpful, I'll look further. @colesbury @ngimel does nccl have cuda code that we need to build for specific archs? K10 is 3.0 and i build 3.0 code for thc and thcunn

**Comment by colesbury** [comment]
Yes, @soumith that's the problem: https://github.com/pytorch/pytorch/blob/master/torch/lib/nccl/Makefile#L19

The README says "Kepler or newer". @ngimel, does NCCL work on K10s?

**Comment by ngimel** [comment]
It should (once you add the necessary compilation flags).
