### ISSUE TITLE
Query on PyTorch threading model

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#55427]
## ❓ Questions and Help

- [Discussion Forum query link](https://discuss.pytorch.org/t/query-on-pytorch-thread-model/117299)

Hello,

It'd have been great if the [Threading wiki](https://github.com/pytorch/pytorch/blob/master/docs/source/notes/cpu_threading_torchscript_inference.rst) had an example of when the following scenario could arise -

> OpenMP does not guarantee that a single per-process intra-op thread pool is going to be used in the application. On the contrary, two different application or inter-op threads may use different OpenMP thread pools for intra-op work.

Can you please give an example in which this scenario would occur?
I'd perform some measurements for such examples, and will share results here (if I'd be able to glean any useful insights).

Thank you!

cc @ilia-cher

**Comment by ilia-cher** [comment]
The text seems to describe this scenario - two application threads use openmp (e.g. `parallel for` or use ops that use openmp), in this case OpenMP would create two thread pools. It can be checked by e.g. running `matmul` in parallel with `matmul` launched with `torch.jit.fork`.
