### ISSUE TITLE
Pytorch RuntimeError: couldn‘t find libcudart. Make sure CUDA libraries are installed in a default

### ISSUE THREAD

**Issue by furh18** [pytorch/pytorch#55443]
### Pytorch RuntimeError: couldn't find libcudart. Make sure CUDA libraries are installed in a default location, or that they're in LD_LIBRARY_PATH.

from torch import cuda
assert cuda.is_available()
assert cuda.device_count() > 0
print(cuda.get_device_name(cuda.current_device()))

# Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 367, in current_device_lazy_init()
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 180, in _lazy_init_cudart = _load_cudart()
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 87, in _load_cudart 'LD_LIBRARY_PATH'))
RuntimeError: couldn't find libcudart. Make sure CUDA libraries are installed in a default location, or that they're in LD_LIBRARY_PATH.

cc @ezyang @seemethere @malfet @walterddr @ngimel @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by peterjc123** [comment]
Which version of PyTorch are you using?

**Comment by furh18** [comment]
> 
> 
> Which version of PyTorch are you using?

v1.0.1 on dji manifold-2G

**Comment by furh18** [comment]
Delete _cudart from torch/cuda/__init__.py [#16527](https://github.com/pytorch/pytorch/issues/16527)

**Comment by peterjc123** [comment]
@furh18 Have you installed CUDA?

**Comment by vladimir-aubrecht** [comment]
Could not reproduce with latest stack and considering this issue is stale, I am closing it. In case issue still persists with latest stack, please create new issue.
