### ISSUE TITLE
.size() vs .shape, which one should be used?

### ISSUE THREAD

**Issue by freud14** [pytorch/pytorch#5544]
Hi,

This is not an issue per se, but more of a question of best practices. I notice that there a shape attribute and a size function that both return the size/shape of a tensor. I also notice that .shape is not documented, but according to various release notes, Pytorch tries to be as close as possible to numpy. So, knowing this, is .shape really supported or just an undocumented functionality that could disappear in the next version?

Thank you.

**Comment by fmassa** [comment]
Hi,
`.shape` is an alias for `.size()`, and was added to more closely match numpy, see https://github.com/pytorch/pytorch/pull/1983

**Comment by apaszke** [comment]
Yes, `.shape` is going to remain supported. Both ways are fine

**Comment by freud14** [comment]
Thank you.

**Comment by samuela** [comment]
FWIW this redundancy has always bugged me. For some reason `x.shape` feels more internal than `x.size()` but it also just doesn't look right when doing things like `x.size()[-2:]`. Still I don't want to be inconsistent and use both.

**Comment by nyck33** [comment]
what about `.size` with no `( )` following it like here:  
![image](https://user-images.githubusercontent.com/25189545/57964337-1a801880-795e-11e9-9d73-7c13d336edcf.png)
Found here:  http://nlp.seas.harvard.edu/2018/04/03/attention.html

**Comment by narfanar** [comment]
> what about `.size` with no `( )` following it like here:
> ![image](https://user-images.githubusercontent.com/25189545/57964337-1a801880-795e-11e9-9d73-7c13d336edcf.png)
> Found here: http://nlp.seas.harvard.edu/2018/04/03/attention.html

That `size` attribute is custom to the custom layers, from what I can see. `tensor.size()` is a tensor method.

**Comment by Risingabhi** [comment]
.size() method returns total elements in a dataframe , for eg shape of a tensor might be (10,3) , here total elements in tensor would be returned by .size() = 10X3 = 30 elements!!

**Comment by freud14** [comment]
>.size() method returns total elements in a dataframe , for eg shape of a tensor might be (10,3) , here total elements in tensor would be returned by .size() = 10X3 = 30 elements!!

@Risingabhi Nope, that's not how it works in PyTorch:
![image](https://user-images.githubusercontent.com/1090012/99558879-2ce37400-2992-11eb-8e23-9e889eee8b03.png)

**Comment by Risingabhi** [comment]
> > .size() method returns total elements in a dataframe , for eg shape of a tensor might be (10,3) , here total elements in tensor would be returned by .size() = 10X3 = 30 elements!!
> 
> @Risingabhi Nope, that's not how it works in PyTorch:
> ![image](https://user-images.githubusercontent.com/1090012/99558879-2ce37400-2992-11eb-8e23-9e889eee8b03.png)

yes, that's the case in pytorch

**Comment by flpgrz** [comment]
> .size() method returns total elements in a dataframe 

That's what  `torch.numel(x)` does.

**Comment by Vagish-Kumar** [comment]
> Hi, `.shape` is an alias for `.size()`, and was added to more closely match NumPy, see #1983

**Comment by tornikeo** [comment]
Is there any difference in behavior for `torch.compile` or onnx export? I'm pretty sure I've seen some weird stuff happen with `.shape`, while `.size` seemed to work well @apaszke

**Comment by aallahyar** [comment]
> Hi, `.shape` is an alias for `.size()`, and was added to more closely match numpy, see [#1983](https://github.com/pytorch/pytorch/pull/1983)

If the goal is to be more similar to Numpy, then I think `size` could return the total number of elements, [similar to `numpy`](https://numpy.org/doc/2.2/reference/generated/numpy.size.html):

```
a = np.random.rand(3, 4, 5)
t = torch.arange(60).view(3, 4, 5)

print(a.size, t.size()) 
# output: 60 torch.Size([3, 4, 5])

print(a.shape, t.shape)
# output: (3, 4, 5) torch.Size([3, 4, 5])
```

I do realize that such a change would be a huge lack of backward compatibility. I am simply proposing to promote the usage of `shape` compared to `size()` when "shape" of a `Tensor` is of interest.

Am I missing something here?
