### ISSUE TITLE
How to access model embedded functions?

### ISSUE THREAD

**Issue by ADD-eNavarro** [pytorch/pytorch#55452]
## ❓ Questions and Help

I am working on C# .NET with Visual Studio 2019, over Windows Server 2019 Standard. 
I aim to export a Python model to run inference on C# with onnxruntime.
I am using [Resemble-ai voice encoder](https://github.com/resemble-ai/Resemblyzer/blob/master/resemblyzer/voice_encoder.py) as ONNX, using:

import torch
import torch.onnx
x = torch.randn(1,3,40,requires_grad=True)
torch_out = encoder(x)

torch.onnx.export(encoder,
                  x,
                  "resemblyzer.onnx",
                  opset_version=13,
                  input_names=['input'],
                  output_names=['output'])

The export takes place without warnings or errors. The graph and input/outputs of the onnx model seem all right.

But I can't figure out how to use the model's embedded functions "embed_utterance" and "embed_speaker". Is that even possible? I mean, do the ONNX model include those functions or just the parameters of the trained model?
If the functions are inside de ONNX model, a snippet on how to access them would be great.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by mrshenli** [comment]
Hey @ADD-eNavarro, please use [PyTorch forum](https://discuss.pytorch.org/) for future questions. Thanks!
