### ISSUE TITLE
Misleading/Inconsistent Exceptions Raised by `nn.ModuleList.forward`

### ISSUE THREAD

**Issue by lumip** [pytorch/pytorch#55459]
## 🐛 Bug

`nn.ModuleList` does not have meaningful semantics for `forward`, yet calling forward does not raise informative exceptions. I have seen this be confusing for many students in a course we are teaching. For a call to `forward` with non-empty arguments, instead of the apparently intended `NotImplementedException` or, alternatively, the default Python `AttributeError` ("ModuleList object has no attribute 'forward'") that one might expect, we instead get a `TypeError: forward() takes 1 positional argument but <n> were given`.

## To Reproduce

1. `nn.ModuleList().forward()` # results in expected `NotImplementedException` being raised
2. `nn.ModuleList().forward(torch.zeros(1))` # results in `TypeError: forward() takes 1 positional argument but 2 were given`

## Expected behavior

`nn.ModuleList().forward(*args)` should raise `NotImplementedException` for any argument list to make it clear that `forward` is unsupported/unimplemented functionality for `nn.ModuleList` (and not merely a call with wrong arguments).

The issues is in the current implementation of the `forward` method, which raises `NotImplementedException` but takes no arguments (except `self`), resulting in the above issues.

## Environment
The issue is independent of environment/runtime. It is present in current master and a quick look suggests that it is present at least since version 1.4.

**Comment by jbschlosser** [comment]
There is an older PR open to fix this issue: https://github.com/pytorch/pytorch/pull/48785. I'll check in on that one to see if we can move forward with the fix.

**Comment by jbschlosser** [comment]
Fixed in #48785.
