### ISSUE TITLE
[feature request] ATen Documentation and Tutorial

### ISSUE THREAD

**Issue by ahkarami** [pytorch/pytorch#5551]
Thank the PyTorch team for releasing the ATen library. However, I think its current documentation is not complete. Has the team any plan to add doc for ATen in the [**PyTorch documentation**](http://pytorch.org/docs/0.3.1/) or offers any tutorial in [PyTorch Tutorials](http://pytorch.org/tutorials/) section?

**Comment by dashesy** [comment]
I get deprecated warnings for `at::empty` but without documentation it is not easy to find how to start using a new way to create an empty tensor in ATen.

**Comment by soumith** [comment]
See https://pytorch.org/cppdocs/
See https://pytorch.org/cppdocs/notes/tensor_creation.html

**Comment by harryhan618** [comment]
> See https://pytorch.org/cppdocs/
> See https://pytorch.org/cppdocs/notes/tensor_creation.html

Still, the meaning of CPP API is missing, which makes the documentation pale.
