### ISSUE TITLE
Add nondeterministic alert to `index_put_`

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#55516]
`index_put_` is nondeterministic when given duplicate indices when `accumulate=False`

Related: #50750

cc @mruberry @kurtamohler

**Comment by mruberry** [comment]
cc @Lezcano

**Comment by Lezcano** [comment]
Oh, I actually mimicked the non-deterministic handling on CPU in `put_` from `index_put`, so I thought that the handling there would be correct. Is it missing just reporting the non-determinism in the main function that calls the stubs?

**Comment by kurtamohler** [comment]
@Lezcano, right now, with `accumulate=False` `index_put_` doesn't react to the flag at all (it does react if `accumulate=True`, and uses a deterministic algorithm). If the indices are duplicate, there's no guarantee for which write will happen first, so we need to throw an error. IIRC, you added a nondeterministic error in `put_` for the same reason, right? Here's an example:

```
>>> torch.use_deterministic_algorithms(True)
>>> a = torch.randn(10)
>>> a
tensor([ 1.0064, -1.6340,  0.2337,  0.4764, -0.2119,  0.1143, -1.1689,  0.2286,
         0.1660,  0.9916])
>>> a.index_put((torch.tensor([0, 0]),), torch.tensor([0., 1.]), accumulate=False)
tensor([ 1.0000, -1.6340,  0.2337,  0.4764, -0.2119,  0.1143, -1.1689,  0.2286,
         0.1660,  0.9916])
>>> a.cuda().index_put((torch.tensor([0, 0]).cuda(),), torch.tensor([0., 1.]).cuda(), accumulate=False)
tensor([ 0.0000, -1.6340,  0.2337,  0.4764, -0.2119,  0.1143, -1.1689,  0.2286,
         0.1660,  0.9916], device='cuda:0')
```

**Comment by Lezcano** [comment]
You are right, that part I added (most probably because you suggested it), but it is not in `index_put`. I'll have a look at your PR in a second
