### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by liu-nlper** [pytorch/pytorch#5552]
My code run well under torch 0.2, however, the following error occurs when I use torch 0.3.1, why?

Traceback (most recent call last):
  File "../train.py", line 149, in <module>
    loss.backward()
  File "/home/jxliu/.local/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/jxliu/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by gchanan** [comment]
Is this easily reproducible?  It's likely because we changed the shape of reduction operations (and indexing a 1-dimensional tensor) to be 0-dimensional (with a value) instead of 1-dimensional.

**Comment by paduvi** [comment]
I met this problem when using `torch.cat` on a list of 0-dim Tensor. It had worked on previous versions, what should I do to fix this?

**Comment by gchanan** [comment]
@zou3519 you looked at this right?

**Comment by zou3519** [comment]
I looked at it but haven't thought about it much yet. There's code right now on master that prevents a 0-dim tensor from going into `torch.cat` (did we have 0-dim tensors in pytorch 0.3?), but it can still take empty tensors (`tensor.dim() == 1 and tensor.numel() == 0`) that have been causing issues: #5332 #5739

**Comment by gchanan** [comment]
@paduvi are you on master?  If you could post a reproduction that would be helpful.

**Comment by paduvi** [comment]
@gchanan yes, I'm current on master.

This is minimum code:

```
x = [Variable(torch.rand(1), requires_grad=True)] * 10  # input
y = [Variable(torch.rand(1), requires_grad=True)] * 10  # input

z = map(lambda a, b: torch.matmul(a, b), x, y)

# on master it print ()
# at previous version it print (1,)
print(z[0].size())  

torch.cat(z, dim=0)
```

**Comment by zou3519** [comment]
@paduvi what map are you using? This is what I get when I run your code
```

In [2]: import torch

In [3]: from torch.autograd import Variable

In [4]: x = [Variable(torch.rand(1), requires_grad=True)] * 10  # input
   ...: y = [Variable(torch.rand(1), requires_grad=True)] * 10  # input
   ...:
   ...: z = map(lambda a, b: torch.matmul(a, b), x, y)
   ...:
   ...: # on master it print ()
   ...: # at previous version it print (1,)
   ...: print(z[0].size())
   ...:
   ...: torch.cat(z, dim=0)
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-86f566c9a3d7> in <module>()
      6 # on master it print ()
      7 # at previous version it print (1,)
----> 8 print(z[0].size())
      9
     10 torch.cat(z, dim=0)

TypeError: 'map' object is not subscriptable
```

**Comment by apaszke** [comment]
@zou3519 `map` returns a list in Python 2, so you probably need to change it to `list(map(...))`

**Comment by shubhamagarwal92** [comment]
A simple reproducible example:
```
print torch.__version__
0.3.1.post2
```
torch.cat works on 0-dim tensors
```
import torch
dec_outputs = torch.FloatTensor() #even for torch.zeros(0,0,0)
max_time_steps = 2
for step in range(max_time_steps):
    step_outputs = torch.randn(3,1,4) # (batch,length,dim)
    dec_outputs = torch.cat((dec_outputs,step_outputs),1) #(batch,length,dim)
print dec_outputs.size() #(batch=3,length=2,dim=4)

torch.Size([3, 2, 4])
```
However, not on 0-dim Variables.
```
# With variable cat doesnt work
from torch.autograd import Variable
dec_outputs = Variable(torch.FloatTensor()) # With variable cat doesnt work
max_time_steps = 2
for step in range(max_time_steps):
    step_outputs = Variable(torch.randn(3,1,4)) 
    dec_outputs = torch.cat((dec_outputs,step_outputs),1) 
print dec_outputs.size() 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-349a1a33b0bb> in <module>()
     26 for step in range(max_time_steps):
     27     step_outputs = Variable(torch.randn(3,1,4))
---> 28     dec_outputs = torch.cat((dec_outputs,step_outputs),1)
     29 #     dec_outputs = torch.stack((dec_outputs,step_outputs),1)
     30 print dec_outputs.size()

RuntimeError: dimension specified as 1 but tensor has no dimensions
```

Though I don't need, we can convert into variable after the loop, but I assume it will not backpropagate gradients (even when volatile is False)?
```
dec_outputs_variable = Variable(dec_outputs,volatile=True)
print dec_outputs_variable.size()
```


#1530 #3452

**Comment by eriche2016** [comment]
@paduvi  @soumith  still got a problem like below: 
```
* RuntimeError: dimension specified as 0 but tensor has no dimensions
```

**Comment by eriche2016** [comment]
i am on the master.
