### ISSUE TITLE
[structured] Preserve computed values to implementation kernels

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#55526]
While doing https://github.com/pytorch/pytorch/pull/55499 I noticed that structured kernels didn't really help all that much in reducing duplication, because I still had to do a large amount of throat clearing to assign local variables:

```
  int64_t pleft = paddingSize[0];
  int64_t pright = paddingSize[1];
  int64_t ptop = paddingSize[2];
  int64_t pbottom = paddingSize[3];
  int64_t pfront = paddingSize[4];
  int64_t pback = paddingSize[5];
  int64_t dimw = 3;
  int64_t dimh = 2;
  int64_t dimd = 1;
  int64_t dimslices = 0;
  int64_t nbatch = 1;
```

This means we don't really get all that much reduction in code because we have to do this in both cases.  It would be nice if we could preserve these computed values between the two kernels.

One way to permit this preservation would be to make it easier for people to define extra fields in the meta class. For example, all of the variables here could be fields in the meta structured class, and then you would simply set this fields in the meta functions and reference them directly in the impl. We'd need some syntax to specify this in YAML as currently the class entirely codegenerated. One downside is that all of these temporaries will have to spill to memory, even if the optimizer was able to clean things up. Some of the temporaries might just be constexpr things.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/55746/ addmv gives an example of some short circuiting logic that wants to be shared between CPU and CUDA

**Comment by swolchok** [comment]
> #55746 addmv gives an example of some short circuiting logic that wants to be shared between CPU and CUDA

Can you highlight the example logic? I didn't quite see the parallel to the example in this issue when I looked.

Regarding the actual code in the logic, those look like they should all just be consts and should optimize away. For simple stuff like that, we could use a macro if nothing else.

**Comment by ezyang** [comment]
Yup. So just need a way of conveniently defining these on the meta class so people can use them without having to fiddle with includes/namespaces.

In addmv, the logic is specifically https://github.com/pytorch/pytorch/pull/55746/files#diff-cd1d48e2088db0d9762335c3c29af9c1006c5ccbe5c1e1e468a7b0d9d6c87e29R49 where if, e.g., beta is zero, you can skip the kernel and just zero the output tensor; this logic applies universally.

**Comment by ezyang** [comment]
Another example https://github.com/pytorch/pytorch/pull/57015/files#diff-c4e35e76279419d9edda979a995412ee494fad3a97d3fb59486a1f0e326d48beR93 just preserving the wrapped dims for impl

**Comment by ezyang** [comment]
Failure to preserve wrapped dim from meta to impl resulted in the bugs seen in https://github.com/pytorch/pytorch/pull/60360/commits/db6d61545db6ba195f187720a381ca1e277828f5
