### ISSUE TITLE
NCCL Error 1 when using torch.nn.DataParallel

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#5553]
I have ran into this error on the parameter broadcast step of torch.nn.parallel.replicate.
It sounds like this, to be precise: "NCCL Error 1: unhandled cuda error".

**Comment by VladislavZavadskyy** [comment]
Steps I took to fix this issue:

0.  Determine if CUDA version you've installed is compatible with your GPU compute capability ([e.g. here](https://stackoverflow.com/questions/28932864/cuda-compute-capability-requirements))
1.  Build NCCL from [source](https://github.com/NVIDIA/nccl) by running `NVCC_GENCODE="-gencode=arch=compute_<compute_v>,code=sm_<compute_v> make CUDA_HOME=<cuda_path> test"` from source directory, where `<compute_v>` is compute capability version of your GPUs without dot (e.g. 3.0 would be 30). If you have GPUs with different compute capabilities duplicate these parameters as many times you as you need.
2. Copy the contents of build folder into some permanent place (e.g. `/usr/local/nccl`).
3. Run export `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/nccl/lib`.
4. Run tests from `test` folder to see if everything is fine (e.g. `./usr/local/nccl/test/single/all_reduce_test 10000`).
4.5 If something is wrong in any of those tests, running the test with prefix `NCCL_DEBUG=WARN` or even `NCCL_DEBUG=INFO` will provide you information for further debugging, else proceed to the step 5.
5. Set environmental variables `NCCL_ROOT_DIR`, `NCCL_LIB_DIR` and `NCCL_INCLUDE_DIR` to corresponding paths (e.g. `export NCCL_LIB_DIR=/usr/local/nccl/lib/`).
6. Build pytorch from source.

**Comment by VladislavZavadskyy** [comment]
close

**Comment by aleksod** [comment]
> Steps I took to fix this issue:
> 
> 1. Determine if CUDA version you've installed is compatible with your GPU compute capability ([e.g. here](https://stackoverflow.com/questions/28932864/cuda-compute-capability-requirements))
> 2. Build NCCL from [source](https://github.com/NVIDIA/nccl) by running `NVCC_GENCODE="-gencode=arch=compute_<compute_v>,code=sm_<compute_v> make CUDA_HOME=<cuda_path> test"` from source directory, where `<compute_v>` is compute capability version of your GPUs without dot (e.g. 3.0 would be 30). If you have GPUs with different compute capabilities duplicate the `-gencode=arch=compute_<compute_v>,code=sm_<compute_v> ` part as many times you as you need.
> 3. Copy the contents of build folder into some permanent place (e.g. `/usr/local/nccl`).
> 4. Run export `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/nccl/lib`.
> 5. Run tests from `test` folder to see if everything is fine (e.g. `./usr/local/nccl/test/single/all_reduce_test 10000`).
>    4.5 If something is wrong in any of those tests, running the test with prefix `NCCL_DEBUG=WARN` or even `NCCL_DEBUG=INFO` will provide you information for further debugging, else proceed to the step 5.
> 6. Set environmental variables `NCCL_ROOT_DIR`, `NCCL_LIB_DIR` and `NCCL_INCLUDE_DIR` to corresponding paths (e.g. `export NCCL_LIB_DIR=/usr/local/nccl/lib/`).
> 7. Build pytorch from source.

I am tripping on step 4: `bash: ./usr/local/nccl/test/single/all_reduce_test: No such file or directory`. I also tried `/usr/local/nccl/test/single/all_reduce_test 10000` (i.e. without the leading dot in the path) with the same result, `bash: /usr/local/nccl/test/single/all_reduce_test: No such file or directory`. Perhaps I am not executing step 1 correctly? In my case, I run the following:
```bash
# NVCC_GENCODE="-gencode=arch=compute_30,code=sm_30 make CUDA_HOME=/usr/local/cuda-9.0/ test"
# make -j src.build
```

I run that as opposed to `make -j src.build NVCC_GENCODE="-gencode=arch=compute_30,code=sm_30 make CUDA_HOME=/usr/local/cuda-9.0/ test"`, as the latter command gives me 

```bash
# make -j src.build NVCC_GENCODE="-gencode=arch=compute_30,code=sm_30 make CUDA_HOME=/usr/local/cuda-9.0/ test"
make -C src build BUILDDIR=/root/nccl/build
make[1]: Entering directory '/root/nccl/src'
Generating nccl.h.in                           > /root/nccl/build/include/nccl.h
Compiling  init.cu                             > /root/nccl/build/obj/init.o
Compiling  ring.cu                             > /root/nccl/build/obj/ring.o
Compiling  bootstrap.cu                        > /root/nccl/build/obj/bootstrap.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
Makefile:84: recipe for target '/root/nccl/build/obj/init.o' failed
make[1]: *** [/root/nccl/build/obj/init.o] Error 1
make[1]: *** Waiting for unfinished jobs....
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
Makefile:84: recipe for target '/root/nccl/build/obj/ring.o' failed
make[1]: *** [/root/nccl/build/obj/ring.o] Error 1
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
Makefile:84: recipe for target '/root/nccl/build/obj/bootstrap.o' failed
make[1]: *** [/root/nccl/build/obj/bootstrap.o] Error 1
make[1]: *** wait: No child processes.  Stop.
Makefile:25: recipe for target 'src.build' failed
make: *** [src.build] Error 2
```

**Comment by YoelShoshan** [comment]
I can help -  @aleksod 
Looking at their official build guide: https://github.com/NVIDIA/nccl

you need to clone a different repo for the tests:
`git clone https://github.com/NVIDIA/nccl-tests.git`
Then, in order to build the tests, enter that repo and run:
CUDA_HOME=[path to your cuda main install dir] NCCL_HOME=[path to your nccl build dir] make

for example
CUDA_HOME=/usr/local/cuda-10.0 NCCL_HOME=/path/to/nccl/build make
