### ISSUE TITLE
ROCM: After enabling Magma, 4 tests are failing in ROCM CI

### ISSUE THREAD

**Issue by arindamroy-eng** [pytorch/pytorch#55552]
## 🐛 Bug

As ROCM CI moved to ROCM 4.1, 5k new test cases from test_linalg.py got enabled.
Out of these 4 test cases are failing. These amount to 16 test cases (considering the dtypes).
Need to disable these test cases temporarily for ROCM CI to progress.

## To Reproduce

1. python3.6 test/test_linalg.py -v

## Expected behavior
The test suite should pass

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Device 6860
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.27.5
MIOpen runtime version: 2.11.0

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.9.0a0+gitf5675f8
[pip3] torchvision==0.9.0a0+8a2dc6f
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.18.5           py36ha1c710e_0  
[conda] numpy-base                1.18.5           py36hde5b4d6_0  
[conda] torch                     1.9.0a0+gitc691bf2          pypi_0    pypi

## Additional context

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by arindamroy-eng** [comment]
@jithunnair-amd @jeffdaily

**Comment by amathews-amd** [comment]
Issue was identified to be within MAGMA. 

Please see: 
Issue: https://bitbucket.org/icl/magma/issues/43/zgetrf_batched-shfl-kernel-failure-seen-on  
PR: https://bitbucket.org/icl/magma/pull-requests/8/hipmagma

Once MAGMA is fixed, we will re-activate the skipped tests.
