### ISSUE TITLE
A RuntimeError should be raised when input and out= tensor are on different devices for torch.{dot, vdot}

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#55561]
Reference: https://github.com/pytorch/pytorch/pull/55492
Failure from the OpInfo generated test for `torch.{dot, vdot}`
`RuntimeError not raised : Expected RuntimeError when calling with input.device=cuda:0 and out.device=cpu`

**Comment by imaginary-person** [comment]
Is it for the inplace variant?
