### ISSUE TITLE
arange(0.1, 0.5, 0.05) returns wrong results

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5556]
```python
import torch, numpy as np

torch.arange(0.1, 0.50, 0.05)
# 0.1000
# 0.1500
# 0.2000
# 0.2500
# 0.3000
# 0.3500
# 0.4000
#[torch.FloatTensor of size 7]


np.arange(0.1, 0.50, 0.05, dtype = np.float32)
#array([0.1       , 0.15      , 0.20000002, 0.25      , 0.3       ,
#       0.35000002, 0.4       , 0.45000002], dtype=float32)
```

0.45 is missing from PyTorch output, which seems strange, 0.45 is clearly less than 0.50, even considering floating point errror.

on `0.4.0a0+1fdb392`

I guess the cause is that `arange` computes number of elements by `floor((end - start) / step)` and float error impacts this calculation, but the departure from NumPy behavior in simple cases like this (not even https://github.com/pytorch/pytorch/issues/4877) may be confusing.

**Comment by bheinzerling** [comment]
Looks like your guess is right:

https://github.com/pytorch/pytorch/blob/502aaf39cf4a878f9e4f849e5f409573aa598aa9/aten/src/THC/generic/THCTensorMath.cu#L475

(((xmax - xmin) / step) + 1) ends up as (0.45 - 0.1) / 0.05 + 1 == 7.99999

**Comment by ezyang** [comment]
@li-roy will look into this

**Comment by li-roy** [comment]
Numpy actually has this same issue:

```
>>> np.arange(0.6, 0.9, 0.1)
array([0.6, 0.7, 0.8, 0.9])
```

#5600 will make it so we are consistent with numpy's results.
