### ISSUE TITLE
torch.one_hot causes multiple DeviceToHost transfers when input tensor is a cuda tensor

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#55579]
## To Reproduce

1. 
1.
1.

```
x = torch.tensor([1, 2, 3]).long().cuda()
F.one_hot(x, 4)
```

![Screen Shot 2021-04-07 at 6 44 15 PM](https://user-images.githubusercontent.com/35972327/113955961-96451180-97d1-11eb-8e33-c5240f6494e1.png)

One example:

https://github.com/pytorch/pytorch/blob/release/1.8/aten/src/ATen/native/Onehot.cpp#L21

## Expected behavior

No DeviceToHost transfers. There are multiple .item() calls in the ATen one_hot implementation. These are mostly unnecessary except for when `num_classes=-1`

.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ngimel @VitalyFedyunin

**Comment by ngimel** [comment]
`.min()` and `.max()` calls are used to check that the data in the tensor is valid. If those checks aren't done, the subsequent kernel will fail with device assert and context will be invalidated. Is it preferred behavior?

**Comment by msbaines** [comment]
> `.min()` and `.max()` calls are used to check that the data in the tensor is valid. If those checks aren't done, the subsequent kernel will fail with device assert and context will be invalidated. Is it preferred behavior?

These checks are very expensive when the index tensor is a CUDA tensor.

Could the check not happen in a CUDA kernel? Each CUDA thread could set an error bit if they see an invalid value.

**Comment by ngimel** [comment]
There's no way to "set an error bit" from CUDA code, what's happening now is a device assert and invalidation of context (when e.g. indexing operation gets an invalid index). We could do the same for one-hot, if that's the preferred behavior, but there's no way to have nice recoverable non-synchronizing errors from cuda.

**Comment by ngimel** [comment]
The cpu calling code checking the flag will cause synchronization. An example from apex is nice, but it allows 2 kernels (overflow check and actualy optimizer) to go without sync. Here, if actual one_hot kernel encounters an error, it has no way of telling arbitrary kernel that comes after it to stop operation.

**Comment by msbaines** [comment]
> The cpu calling code checking the flag will cause synchronization. An example from apex is nice, but it allows 2 kernels (overflow check and actualy optimizer) to go without sync. Here, if actual one_hot kernel encounters an error, it has no way of telling arbitrary kernel that comes after it to stop operation.

Ah. I had not considered that. Currently, we are using a custom one_hot implementation to avoid the HToD transfers since we know the index tensor is correct. What is the process for recovering from context invalidation? Is a python exception raised. That might be OK. The current situation is no different. In both cases, I doubt a user would try to recover since it's likely due to a bug in there code that they would want to fix.


Current behavior:
* slow one_hot
* exception thrown (which could be caught) when index tensor has out-of-bounds data

Behavior if checks are removed (instead there is a device assert and context invalidated):
* fast one_hot
* context invalidated and exception thrown (user would need to re-create context to recover?)

**Comment by ngimel** [comment]
Context invalidation is irrecoverable for all practical purposes. The current context has to be shut down (taking away all the data in the currently existing gpu tensors with it) and the new context has to be created (with no data persisting between them), so pytorch doesn't provide mechanism to do that. 
If one_hot users never send invalid data though, having an irrecoverable assert may still be preferable to always paying performance penalty, let me know what are your thoughts.

**Comment by msbaines** [comment]
> Context invalidation is irrecoverable for all practical purposes. The current context has to be shut down (taking away all the data in the currently existing gpu tensors with it) and the new context has to be created (with no data persisting between them), so pytorch doesn't provide mechanism to do that.
> If one_hot users never send invalid data though, having an irrecoverable assert may still be preferable to always paying performance penalty, let me know what are your thoughts.

I would prefer fast one_hot. Two HToD transfers is very expensive. I can't think of a good use case where I'd want to recover from bad data in the one_hot input tensor. This would usually mean I have a bug in my model somewhere.

If backward compatibility is an issue, perhaps an argument could be added as was recently done when error_if_nonfinite was added to clip_grad_norm_:

https://pytorch.org/docs/master/generated/torch.nn.utils.clip_grad_norm_.html?highlight=clip_grad_norm_#torch.nn.utils.clip_grad_norm_

**Comment by GlebKazantaev** [comment]
@ngimel we observe the same issue with one_hot with Lazy device as `self.min().item()` leads to `mark_step` calls which are very expensive. I guess XLA has the same issue with one_hot since they transitioned to LTC.
Can we add the same check like you did for cuda for the Lazy device type?

CC: @JackCaoG
