### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by Bonsen** [pytorch/pytorch#55582]
My model has lot's of fc layers for outputs and a batch may optimizes some of the fc layers (all fc layers will be optimized in one epoch). If I use DistributedDataParallel it will throw 

"RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel; (2) making sure all forward function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's forward function. Please include the loss function and the structure of the return value of forward of your module when reporting this issue (e.g. list, dict, iterable).", 

and If I use torch.nn.DataParallel, everything will be ok.

https://github.com/pytorch/pytorch/issues/43259 shows we need to cut unused output, but I need all fc outputs.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by mrshenli** [comment]
> shows we need to cut unused output, but I need all fc outputs.

for the outputs not participating in the loss computation, is it possible to expose that through a separate API instead of using the forward function return value? E.g.:

```python
class MyModel(nn.Module):
  ...
  def forward(self, inputs):
    output1, output2 = self.sub_net(inputs)
    self.output1 = output1
    return output2

  def get_output1(self):
    return self.output1

```

cc oncall @agolynski

**Comment by Bonsen** [comment]
@mrshenli 
If the num of fc layers depend on different task, and I define Model with a list like Modulelist[fc1,fc2........]. It seems hard to define lost's of fuctions like get_output1, get_output2...?

**Comment by mrshenli** [comment]
> If the num of fc layers depend on different task, and I define Model with a list like Modulelist[fc1,fc2........]. It seems hard to define lost's of fuctions like get_output1, get_output2...?

I see. Another possibility is to include the loss computation in the forward function and let the forward function directly return the loss tensors. Then by setting `find_unused_parameters=True`, DDP should be able to traverse the graph from the loss and identify unused ones.

**Comment by Bonsen** [comment]
I will try it soon, thanks.

**Comment by Bonsen** [comment]
It works. Thanks. @mrshenli

**Comment by XinyuSun** [comment]
Hi! I solve this problem by concatenating the outputs of all fc layers as the return value of the forward function and chunking them apart like:
```python
class MyModel(nn.Module):
  ...
  def forward(self, inputs):
    out1, out2 = self.sub_net(inputs)
    return torch.cat([out1, out2], dim=0)

def SomeTask(inputs):
    out = MyModel(inputs)
    out1, out2 = torch.chunk(out, dim=0)
    # calculate loss using out1 and out2
```
Does the gradient calculate correctly in this case? @mrshenli
