### ISSUE TITLE
addmv_() allows resizing the tensor it operates on and produces wrong results

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#55589]
```
a = torch.randn((1,))
b = torch.randn((3, 4))
c = torch.randn((4,))

# this should error out
a.addmv_(b, c)
: tensor([ 2.2854,  1.4802, -1.4424])
```

This operation should fail. Discovered by @Lilyjjo (see https://github.com/pytorch/pytorch/issues/55539).

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by ngimel** [comment]
It not only resizes, it produces bogus values:
```
In [3]: a = torch.full((1,), 0.5, device="cuda")
   ...: 
   ...: b = torch.ones((3, 4), device="cuda")
   ...: c = torch.ones((4,), device="cuda")
In [4]: out=torch.addmv(a,b,c)
In [5]: out
Out[5]: tensor([4.5000, 4.5000, 4.5000], device='cuda:0')
In [6]: a
Out[6]: tensor([0.5000], device='cuda:0')
In [7]: a.addmv_(b,c)
Out[7]: tensor([4.5000, 8.5000, 8.5000], device='cuda:0')
```

**Comment by ezyang** [comment]
Consider porting this to structured to fix the problem! https://github.com/pytorch/rfcs/blob/rfc-0005/RFC-0005-structured-kernel-definitions.md

**Comment by kshitij12345** [comment]
Following patch fixes the inplace behavior (verified locally),
```patch
--- a/aten/src/ATen/native/Blas.cpp
+++ b/aten/src/ATen/native/Blas.cpp
@@ -89,6 +89,12 @@ Tensor addmv(const Tensor &self, const Tensor &mat, const Tensor &vec, const Sca
 }
 
 Tensor &addmv_(Tensor &self, const Tensor &mat, const Tensor &vec, const Scalar& beta, const Scalar& alpha) {
+  TORCH_CHECK(
+      self.sizes() == IntArrayRef{mat.size(0)},
+      "output with shape ",
+      self.sizes(),
+      " doesn't match the broadcast shape ",
+      IntArrayRef{mat.size(0)})
   return native::addmv_out(self, mat, vec, beta, alpha, self);
 }
 
```

Is it okay if porting to structured is done independently?

**Comment by ezyang** [comment]
@ngimel has a port in progress at https://github.com/pytorch/pytorch/pull/55746 but I'm not opposed to landing just the extra torch check for now.

**Comment by kshitij12345** [comment]
Oh. Didn't see that. Thanks! I think it would be better to wait till #55746.
