### ISSUE TITLE
Verify that attempting to resize a tensor with an inplace operation throws a runtime error

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#55595]
Now that https://github.com/pytorch/pytorch/pull/53014 is in there is a mechanism used by test_variant_consistency_eager to filter sample inputs intended for use with the inplace variants of operators. This is intended to avoid sample inputs that would throw an error when used inplace. In particular, operations that try to resize a tensor inplace should throw an error:

```
a = torch.tensor((1,))
b = torch.tensor((2, 3, 4))
a.add_(b)
: RuntimeError: output with shape [1] doesn't match the broadcast shape [3]
```

However, https://github.com/pytorch/pytorch/issues/55589 shows that some operations do not error out in cases like this! I propose we extend test_variant_consistency_eager to not skip these inputs but verify the inplace operation throws an error when called with them.

cc @mruberry @VitalyFedyunin @walterddr @kshitij12345

**Comment by kshitij12345** [comment]
@mruberry 
I think, we should add `broadcasts_input` attribute to the `SampleInput` and remove the filtering based on `for_inplace_variant` for these cases. 

The reason why I feel this would be more appropriate is because this way,
*  Relevant tests can query the Sample properties and test the relevant behaviour accordingly. (the input sample by itself is not deformed but combination of input and variant is deformed which the relevant test knows) 
* Plus it would make sample generator nicer.
* It will also improve performance of `test_variant_consistency_eager` (probably by a small margin) as we won't have to materialise two set of samples based on Operator variant.

Let me know what you think it?

**Comment by mruberry** [comment]
@kshitij12345 

I do think for_inplace_variant may not be the best way to go...

I like your idea of marking sample inputs that broadcast their input. Could we detect, however, that the size of the output from the functional variant doesn't matching the size of input, and infer that the inplace operation should fail programmatically?

**Comment by kshitij12345** [comment]
Programmatic detection can work in `test_variant_consistency_eager`, where we actually compute the forward of the input (so we can check the shape of the output), however it won't work in `test_inplace_grad` and `test_inplace_gradgrad` (unless we add forward checks just for that).

So I think it would be better to mark the SampleInput. 
* `test_variant_consistency_eager` will confirm that inplace on that sample actually fails (i.e. samples can't be incorrectly marked).
* `test_inplace_grad{grad}` can just trust the marking and skip accordingly.
* Information about whether the input broadcasts will be visible at sampling itself.

Reference for `test_inplace_grad{grad}`

https://github.com/pytorch/pytorch/blob/c7312f5271b9ce9ac988fffde90818354e5841b8/test/test_ops.py#L104-L117

**Comment by mruberry** [comment]
@kshitij12345 You've convinced me. Adding a metadata field to sample input for whether it requires the input be broadcast sounds like the right approach. We should comment as to what the field is for, too.

I'd still like it if sample inputs would take kwargs, however, because that's good future-proofing.

Thanks for your thoughtfulness and attention to detail on this issue.

**Comment by kshitij12345** [comment]
> I'd still like it if sample inputs would take kwargs, however, because that's good future-proofing.

Agreed. `kwargs` could help some other filtering or provide some other detail from the test. Will leave that untouched.

Thanks!
