### ISSUE TITLE
Can THPP be compiled with CMake 2.8?

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#556]
Currently, CMake 3.0 or higher is required for THPP. 
https://github.com/pytorch/pytorch/blob/master/torch/lib/THPP/CMakeLists.txt#L1
This is annoying for building from source on Ubuntu 14.04 systems, as default CMake is 2.8, and updating it requires either compiling from source or adding some random repos:
http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04
```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
```
@colesbury

**Comment by soumith** [comment]
@ngimel it should work fine if you change it to 2.8. I'm testing this out in a sec, and will push it into master

**Comment by ngimel** [comment]
Nope, it does not for me.
