### ISSUE TITLE
Support `__pos__` and `positive`

### ISSUE THREAD

**Issue by asi1024** [pytorch/pytorch#55604]
## 🚀 Feature
Support `torch.Tensor.__pos__` and `torch.positive`.

## Motivation and Pitch

To enhance the compatibility with NumPy’s interface (c.f. https://github.com/pytorch/pytorch/issues/38349).
`np.positive` has been implemented in NumPy 1.13.0 for completeness (see https://github.com/numpy/numpy/issues/8932 and https://github.com/numpy/numpy/pull/8967 for the discussions) and we would like to see it in PyTorch too.

Python array API specification also requires the interface `positive(x, /)` and `__pos__(x)`.
(https://github.com/pytorch/pytorch/issues/54581)
 

## Questions

Does this feature need to be implemented in ATen, or just the Python layer is fine.

## References

* [Python Data API positive(x,  /)](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#positive-x)
* [NumPy numpy.positive](https://numpy.org/doc/stable/reference/generated/numpy.positive.html)

cc @mruberry @rgommers @heitorschueroff

**Comment by rgommers** [comment]
> Does this feature need to be implemented in ATen, or just the Python layer is fine.

I'm fairly sure the answer is that the C++ API must be kept in sync with the Python API - @mruberry please correct me if I'm wrong.

**Comment by mruberry** [comment]
"Must" is a strong word and we do consider exceptions to keeping the Python and C++ APIs entirely consistent, but yes we prefer having them be in sync.

For PyTorch positive() is just an alias for copy, right? We have alias support (see the note in native_functions.yaml).
