### ISSUE TITLE
[BC-Breaking][RFC] Retire ProcessGroup Backend for RPC

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#55615]
**This RFC focuses on [ProcessGroup backend](https://pytorch.org/docs/stable/rpc.html#process-group-backend) in RPC and has nothing to do with DDP or collective communications.**

In the very first version of RPC, we developed [ProcessGroup backend](https://pytorch.org/docs/stable/rpc.html#process-group-backend) to take care of communications. It internally converts the message into a big tensor and uses `ProcessGroup::send` and `ProcessGroup::recv` to transmit tensors. This implementation is simple but not very performant. Later, we added a new [`TensorPipe` backend](https://pytorch.org/docs/stable/rpc.html#tensorpipe-backend) which outperforms `ProcessGroup` backend in many dimensions. E.g., TensorPipe offers higher throughput and lower latency, supports both CPU and CUDA tensors, and covers a variety of communication channels such as NVLink, IB, TCP, SHM, etc. Besides, TensorPipe has been serving as the default backend for RPC in the past few releases. Given that, we believe TensorPipe backend should be a better replacement for ProcessGroup backend for all use cases. Hence, we plan to retire ProcessGroup RPC backend. 

### Implications for User Code

You don't need to change anything in application code, unless you explicitly constructed `ProcessGroupRpcBackendOptions` as shown below. 

```python
rpc.init_rpc(
    "worker1",
    rank=0,
    world_size=2,
    backend=rpc.BackendType.PROCESS_GROUP,
    rpc_backend_options=rpc.ProcessGroupRpcBackendOptions(
         num_send_recv_threads=16,
         rpc_timeout=20 # 20 second timeout
    )
)
```

If you need such code to override default values of thread number or timeout, you can replace `ProcessGroupRpcBackendOptions` with `TensorPipeRpcBackendOptions` and set its args accordingly. See the example below. 

```python
rpc.init_rpc(
    "worker1",
    rank=0,
    world_size=2,
    backend=rpc.BackendType.TENSORPIPE,
    rpc_backend_options=rpc.TensorPipeRpcBackendOptions(
         num_worker_threads=16,
         rpc_timeout=20 # 20 second timeout
    )
)
```

### Retirement Timeline

The current plan is that **v1.9 will be the last release that carries ProcessGroup RPC backend**, after that `ProcessGroupAgent` implementation will be completely removed from the codebase. If this might cause problems for your use case, please comment below. Thanks!

cc @ezyang @gchanan @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by H-Huang** [comment]
The ProcessGroup backend in RPC has been removed as part of the following PRs:

- #61421
- #62409
- #62411
- #62985
- #63160

If a user attempts to use ProcessGroup backend for RPC in their code, for example:

```python
import os
import torch.distributed as dist
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12345'
dist.rpc.init_rpc("worker", backend=dist.rpc.BackendType.PROCESS_GROUP, rank=0, world_size=1, rpc_backend_options=None)
```
They will receive the error:
```
Traceback (most recent call last):
  File "3.py", line 7, in <module>
  File "/private/home/howardhuang/pytorch-projects/pytorch/torch/distributed/rpc/__init__.py", line 155, in init_rpc
    raise RuntimeError(
RuntimeError: RPC was initialized with the PROCESS_GROUP backend which has been removed and is superseded by the TENSORPIPE backend. Please migrate to the TENSORPIPE backend. PyTorch v1.9 was the last release that carries PROCESS_GROUP RPC backend.
```

**Comment by mrshenli** [comment]
Thanks @H-Huang for retiring PG backend!

**Comment by chaoyanghe** [comment]
I got the following error when using sync.Pipe and initializing RPC.
```
    def _init_rpc(self):
        # https://github.com/pytorch/pytorch/issues/55615
        # [BC-Breaking][RFC] Retire ProcessGroup Backend for RPC #55615
        options = rpc.TensorPipeRpcBackendOptions(
         num_worker_threads=16,
         rpc_timeout=20,
         init_method='tcp://' + str(self.master_addr) + ':10000'
        )
        rpc.init_rpc(
            "worker:"+str(self.global_rank),
            backend=rpc.BackendType.TENSORPIPE,
            rank=self.global_rank,
            world_size=self.world_size,
            rpc_backend_options=options
        )
        # torch.distributed.rpc.init_rpc('worker', rank=self.global_rank, world_size=self.world_size)
        logging.info("init_rpc finished.")
```
```
10.0.87.143: 10.0.87.143: RuntimeError: In operator() at tensorpipe/common/ibv.h:172 "": Operation not supported
10.0.87.143: 10.0.87.143:     main()
10.0.87.143: 10.0.87.143:   File "main_moe.py", line 116, in main
10.0.87.143: 10.0.87.143:     dp_ep.init()
10.0.87.143: 10.0.87.143:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/dp/dp_manager.py", line 37, in init
10.0.87.143: 10.0.87.143:     self._init_rpc()
10.0.87.143: 10.0.87.143:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/dp/dp_manager.py", line 92, in _init_rpc
10.0.87.143: 10.0.87.143:     rpc_backend_options=options
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rpc/__init__.py", line 203, in init_rpc
10.0.87.143: 10.0.87.143:     _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rpc/__init__.py", line 243, in _init_rpc_backend
10.0.87.143: 10.0.87.143:     rpc_backend_options=rpc_backend_options,
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rpc/backend_registry.py", line 99, in init_backend
10.0.87.143: 10.0.87.143:     return backend.value.init_backend_handler(*args, **kwargs)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rpc/backend_registry.py", line 313, in _tensorpipe_init_backend_handler
10.0.87.143: 10.0.87.143:     api._init_rpc_states(agent)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/rpc/api.py", line 116, in _init_rpc_states
10.0.87.143: 10.0.87.143:     _set_and_start_rpc_agent(agent)
10.0.87.143: 10.0.87.143: RuntimeError: In operator() at tensorpipe/common/ibv.h:172 "": Operation not supported
```

**Comment by rohan-varma** [comment]
@chaoyanghe Thanks for reporting this problem! Would you be able to help open a separate issue with a full repro of the problem?

**Comment by chaoyanghe** [comment]
> @chaoyanghe Thanks for reporting this problem! Would you be able to help open a separate issue with a full repro of the problem?

https://github.com/pytorch/pytorch/issues/65022

**Comment by chaoyanghe** [comment]
@rohan-varma I provide the repo and script for you to reproduce:

https://github.com/pytorch/pytorch/issues/65022

**Comment by chaoyanghe** [comment]
Hi All, I met two bugs when using upgraded pipeline:

1. [AWS EC2 P3DN, EFA is enabled] Torch RPC tensorpipe/common/ibv.h:172 "": Operation not supported:
https://github.com/pytorch/pytorch/issues/65022


2. [AWS EC2 P3DN] torch sync.pipeline makes the tensor passing to the next stage in CPU device; it's working without using pipeline:
https://github.com/pytorch/pytorch/issues/65093

Please help
