### ISSUE TITLE
Device-side Assert in `THCReduceAll.cuh:339`

### ISSUE THREAD

**Issue by angusturner** [pytorch/pytorch#5561]
Since upgrading to master, I am receiving the following error while trying to compute token-wise accuracy in a language model:

```
[with IndexType = unsigned int, Real = float, Dims = 3]: block: [14,0,0], thread: [222,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
/home/user/cuda-ubuntu-16.04-ec2/pytorch/aten/src/THC/THCTensorScatterGather.cu:176: void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [14,0,0], thread: [223,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
THCudaCheck FAIL file=/home/panda/cuda-ubuntu-16.04-ec2/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=339 error=59 : device-side assert triggered

Traceback (most recent call last):
  File "train_model.py", line 138, in <module>
    train_model(config)
  File "train_model.py", line 106, in train_model
    loss_score, _ = worker.test(test_loader)
  File "/home/user/src/worker.py", line 275, in test
    accuracy = self.get_top_n(pred, targ, n=1)
  File "/home/user/src/abs_worker.py", line 268, in get_top_n
    nb_correct = (one_hot * n_hot).sum()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/user/cuda-ubuntu-16.04-ec2/pytorch/aten/src/THC/generated/../THCReduceAll.cuh:339
```

`one_hot` and `n_hot` are both `(batch, num_classes, length)` of type `Variable(torch.FloatTensor)`. This error has cropped up in an otherwise stable code-base after upgrading from PyTorch v0.3.0.

System details:
OS: Ubuntu 16.0.4
PyTorch version: 0.4.0a0+55c64e5
How you installed PyTorch (conda, pip, source): source
Python version: Python 3.6.1
CUDA/cuDNN version: CUDA release 9.0, V9.0.176 / CUDNN 7005
GPU models and configuration: 4x Nvidia M60
GCC version (if compiling from source): GCC 4.4.7

**Comment by apaszke** [comment]
You have out-of-bound indices when you create the one-hot vector. The error will be raised on the responsible line if you use `CUDA_LAUNCH_BLOCKING=1`
