### ISSUE TITLE
can't use git clone

### ISSUE THREAD

**Issue by yyc11** [pytorch/pytorch#55610]
it has that error
"error:RPC failed; HTTP 403 curl 22 The …"

**Comment by manish1m97** [comment]
Hi,

Kindly try again with the below code

git clone https://github.com/pytorch/pytorch.git

**Comment by wavezhu** [comment]
I also meet the same question. And I use this cmd, but it's no use.
Use this cmd ,I can git clone any projects in github except pytorch. 
Can you help us? @manish1m97 @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
Likely github issue, please try again
