### ISSUE TITLE
Import Error : no module  named torch

### ISSUE THREAD

**Issue by curiosityredef** [pytorch/pytorch#5563]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

![issue1](**https://user-images.githubusercontent.com/19254992/36958144-c011b122-205f-11e8-82c2-fe0b0e0ad4f3.png**)
image error running from terminal is at link in Bracket
OS 16.04 Pytorch version 0.31 Latest , installed using conda, python version 3.5/3.6 .
Cuda 8.0 Cudnn 5.1 . GCC version 5.4.0
I just cloned this repository https://github.com/thstkdgus35/EDSR-PyTorch and trying to run demo.sh file which runs main.py file which imports PyTorch. so the problem is **i am able to import torch from home directory in python3 shell but whenever i go to any folder/directory and run pytorch code or import torch in python3 shell it gives me error** of no module named torch (see image for details). Also **i have installed torch(Luajit) in home or default root directory**. so it might be possible reason.Please help with reference to my code in image.
![issue1](https://user-images.githubusercontent.com/19254992/36958482-2c7fe048-2062-11e8-86e8-b10f25f471cc.png)

**Comment by vishwakftw** [comment]
You have installed `torch` with Python3, where script uses Python2 (`python` defaults to `python2`). Change it, and it should work.

**Comment by curiosityredef** [comment]
I ran the command with python3 also and all python files in repository are in python3. You can check DIV2K_jpeg.py file in repository its in python3 for sure and same for other files.

**Comment by ankita-kalra** [comment]
I am getting the same issue.

**Comment by curiosityredef** [comment]
how did u install your pytorch and which project you are working on ? solutions would depend .

**Comment by ankita-kalra** [comment]
Resolved, I added sys.path(/path_torch_directory) in my code.

**Comment by curiosityredef** [comment]
Do u Know why its needed (if pytorch installed in root directory default) ?

**Comment by MdAshrafulAlam** [comment]
@ankita-kalra could you please elaborate your answer please? when i run my source code it shows no module named torch, but
![p80720-195030](https://user-images.githubusercontent.com/27885238/43001126-aaff0e98-8c56-11e8-8692-dc517807a464.jpg)
 already installed successfully.

**Comment by soumith** [comment]
in the first command you used `python3`, second command you used `python`.

**Comment by lal1234** [comment]
hlo ..i successfully installed torch using (pip install https://download.pytorch.org/whl/cu90/torch-1.0.0-cp37-cp37m-win_amd64.whl )and conda and python(3.7)is same on my base root env and my activated env but on jupyter notebook when i type import torch it showing module not found error..please any suggestion

**Comment by noorkhokhar99** [comment]
easly installation pytorch from here.
https://pytorch.org/get-started/locally/

**Comment by ajaysg** [comment]
i compiled pytorch from source for GPU with CUDA 9 and CUDNN 7. After compiling when i tried to import torch . It throws No module named torch. i cloned pytorch into my code folder and compiled from there. Should i need to compile from home directory

**Comment by maheshk76** [comment]
can't install torch on pypy3

**Comment by i-chaochen** [comment]
same problem here. I think it probably because I installed pytorch via pip.

I can import torch in my iPython (3.6.9), but I got the ModuleNotFoundError when I run python3

```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by adnankhalid710** [comment]
how to update pytorch or torch version in my environment(container)?

**Comment by liyunqianggyn** [comment]
Add the path: export PATH=~/anaconda3/bin:$PATH  
before opening the python.

**Comment by imen-07** [comment]
![image_2021_08_13T15_03_58_563Z](https://user-images.githubusercontent.com/73793039/129593770-95f5399d-d9a3-4905-b6d4-b29b71c5aa7c.png)
