### ISSUE TITLE
Data changed when construct LongTensor from np.long

### ISSUE THREAD

**Issue by Woolseyyy** [pytorch/pytorch#5564]
- OS:  Linux version 4.4.0-81-generic (buildd@lgw01-11) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) )
- PyTorch version:  0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 2.7

This is a python script:
When using np.long to construct a LongTensor:
```
>>> import torch
>>> import numpy as np
>>> from torch.autograd import Variable

>>> a = np.array([0,1,2,3,4,5], dtype=np.long)
>>> a
array([0, 1, 2, 3, 4, 5])

>>> b = Variable(torch.LongTensor(a))
>>> b
Variable containing:
 1.4042e+14
 1.4042e+14
 2.0084e+16
 0.0000e+00
 7.2058e+18
 1.9300e+02
```
However, this script can produce correct result in another machine and it can be fixed when using np.int64 instead of np.long

**Comment by apaszke** [comment]
Seems to work just fine in master. We have probably fixed the bug in the meantime
