### ISSUE TITLE
Request for a test code snippet of Distributed Data Parallel.

### ISSUE THREAD

**Issue by hihunjin** [pytorch/pytorch#55677]
## 🚀 Feature

I need a test code of which I can check my DDP code is working well.

## Motivation

I implemented a DDP code after reading your [tutorial document](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html). It works perfectly fine. But I feel suspicious if there's a something missing.

## Pitch

I need a code snippet for testing.

## Alternatives

If there is already, please link it to me. Thanks in advance.

## Additional context

Mhm. Specifically, in [this document](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html), you said, 

> Gradient synchronization communications take place during the backward pass and overlap with the backward computation. When the ``backward()`` returns, param.grad already contains the synchronized gradient tensor.

I wonder if this really does. I want to check this by myself. I feel like it is not synchronized.

cc @mruberry @VitalyFedyunin @walterddr @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by agolynski** [comment]
@hihunjin 

Are you looking for general DDP testing framework?

DDP has tests if you are worried it works incorrectly, e.g.
https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/distributed/distributed_test.py

You can also write tests wrt to your own model/implementation if you are concerned with correctness.

> I wonder if this really does. I want to check this by myself. I feel like it is not synchronized.

You can add logging and verify in your specific case?

**Comment by hihunjin** [comment]
I'm sorry but how do you use the link you gave to me? It's such a long code. Is there an API document?
