### ISSUE TITLE
Hi, I'm trying to optimize my BERT based Token Classification model using torch.jit.trace(). I need support on the input type I can pass for tracing.

### ISSUE THREAD

**Issue by nikhila912** [pytorch/pytorch#55678]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Generally the input type you need for tracing is the same as the input you run in eager mode. Hope this helps.
