### ISSUE TITLE
torch.from_numpy or torch.XXXtensor doesn't create a tensor anymore but a Variable

### ISSUE THREAD

**Issue by Diego999** [pytorch/pytorch#5567]
Hi everyone,

I'm using the function torch.narrow, which was perfectly working in this configuration https://github.com/pytorch/pytorch/issues/5213 but now I obtained the following error:

```
for start_length in nb_sentences_per_doc_start_length:
            sentence_embeddings_per_doc = sentence_embeddings.unsqueeze(0).narrow(1, start_length[0], start_length[1])
```

```
File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 363, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/diego/Github/DocAgg/pygcn_modified/models.py", line 197, in forward
    sentence_embeddings_per_doc = sentence_embeddings.unsqueeze(0).narrow(1, start_length[0], start_length[1])
TypeError: narrow(): argument 'start' (position 2) must be int, not Variable
```

Where nb_sentences_per_doc_start_length is a tensor built from torch.from_numpy(np.array([[0, 22], [22, 13]])). This seems to be always the cas, even with ```torch.FloatTensor([1,2,3])``` leads to a Variable and not a Tensor.

Is this expected now ?

OS: Linux Mint 18.2 Sonya
PyTorch version: From source (66547ca)
How you installed PyTorch (conda, pip, source): pip
Python version: 3.5
CUDA/cuDNN version: 9.1/7.1.1 (latest versions)
GPU models and configuration: Titan Xp 12Go (Driver 390.12)
GCC version (if compiling from source): (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609

**Comment by apaszke** [comment]
It is expected. Tensors are merged with Variables in master. If you want to extract a scalar from a variable you can call `.item()` or `int(var)` to cast it explicitly.

Also @colesbury @gchanan, it would make sense to me if we started accepting scalar tensors as valid for `int` arguments. Do you have any objections/were already planning to do something like it?

**Comment by Diego999** [comment]
Thank you for your answer. I didn't know but using explicit cast works perfectly.

**Comment by gchanan** [comment]
@apaszke seems fine if they don't have requires_grad and are an integral type.
