### ISSUE TITLE
torch.linalg.eigh fails on gradcheck with complex Hermitian matrix

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#55676]
## 🐛 Bug

Like said in the title, `torch.linalg.eigh` fails the `gradcheck` test if the input matrix is complex Hermitian.

## To Reproduce

    import torch
    mat = torch.randn((2, 2), dtype=torch.complex128).requires_grad_()
    def fcn(mat):
        mat = (mat + mat.transpose(-2, -1).conj()) * 0.5
        return torch.linalg.eigh(mat)

    torch.autograd.gradcheck(fcn, mat)

Produces:

    RuntimeError: Gradients failed to compare equal for grad output = 1j. Jacobian mismatch for output 1 with respect to input 0,
    numerical:tensor([[ 0.0000+0.0000j,  0.0000+0.0000j,  0.1305+0.0000j,  0.1099+0.0000j],
            [ 0.0000+0.0000j,  0.0000+0.0000j, -0.1580-0.2293j,  0.2229+0.2433j],
            [ 0.0000+0.0000j,  0.0000+0.0000j, -0.1580+0.2293j,  0.2229-0.2433j],
            [ 0.0000+0.0000j,  0.0000+0.0000j, -0.1305+0.0000j, -0.1099+0.0000j]],
           dtype=torch.complex128)
    analytical:tensor([[ 0.0000e+00+0.0000j,  0.0000e+00+0.0000j,  1.3048e-01+0.0000j,
              1.0993e-01+0.0000j],
            [-1.1155e-01-0.1368j, -1.3240e-01-0.1623j, -8.5187e-02-0.1400j,
              1.0111e-01+0.0940j],
            [-1.1155e-01+0.1368j, -1.3240e-01+0.1623j, -8.5187e-02+0.1400j,
              1.0111e-01-0.0940j],
            [-1.3878e-17+0.0000j,  0.0000e+00+0.0000j, -1.3048e-01+0.0000j,
             -1.0993e-01+0.0000j]], dtype=torch.complex128)

## Expected behavior

The test should pass

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0.dev20210409
 - OS (e.g., Linux): WSL Ubuntu 20.04.1 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.5
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

It seems like the `symeig` gradient implementation has followed the equation 4.71 from here: https://arxiv.org/pdf/1701.00392.pdf, but it still fails.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk

**Comment by mruberry** [comment]
@Lezcano or @nikitaved, would either of you be interested in this issue?

**Comment by IvanYashchuk** [comment]
I think what is causing troubles here is that the sign or phase of eigenvectors is not unique, so is the choice for normalization of eigenvectors.
The following `fcn` function passes the test
```python
import torch
mat = torch.randn((2, 2), dtype=torch.complex128).requires_grad_()
def fcn(mat):
    mat = (mat + mat.transpose(-2, -1).conj()) * 0.5
    result = torch.linalg.eigh(mat)
    return result[0], abs(result[1])

torch.autograd.gradcheck(fcn, mat)
```

**Comment by mfkasim1** [comment]
@IvanYashchuk ah, you're right. I forgot about the non-uniqueness of complex eigenvectors. I'm closing this as it's not pytorch's problem.
