### ISSUE TITLE
torch.autograd.Function memory leak

### ISSUE THREAD

**Issue by btgraham** [pytorch/pytorch#5569]
I get a memory leak running the code below.
The code is a contrived, for example the weight parameter seemingly does nothing, and I know I could use ctx.save_for_backward to save the input_features. Nonetheless, it may be unexpected behavior.

[PyTorch master 66547ca06171812a65afbd82473372aa739a8b2a / Linux / Python Miniconda 3.6.1 ]
```
import torch

class CopyFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input_features, weight):
        ctx.output_features=input_features.clone()
        return ctx.output_features
    @staticmethod
    def backward(ctx, grad_output):
        print('backward is never called; that is OK.')

for _ in range(1000000):
    weight = torch.nn.Parameter(torch.Tensor(100,100).normal_())
    input=torch.FloatTensor(100,100).uniform_().cuda()
    output = CopyFunction.apply(input,weight)
    print(output.shape, output.type())
```

P.S. Thanks to @fmassa for helping to localize this.

**Comment by zou3519** [comment]
Does this only happen on cuda()?

**Comment by apaszke** [comment]
It’s not that you can use `save_for_backward`, you should use it for inputs and outputs, or you will face leaks like in this issue. It’s expected.

**Comment by fmassa** [comment]
@apaszke what if you want to hold a data structure that is not a torch tensor (via CFFI for example), and for which we can't cast to a tensor? I believe this was the original use-case of @btgraham

**Comment by fmassa** [comment]
ah, wait, the leaks only happen if we store inputs / outputs ? So that should be fine then, as they should be torch tensors.

**Comment by apaszke** [comment]
Yes. The leaks happen only if you hold on to outputs via a different mechanism

**Comment by YouJiacheng** [comment]
Sorry to comment in a closed issue.
But I wonder if save tensor in `ctx` without `save_for_backward` can really cause memory leak?
It seems(tested with 1.12.0) only a cyclic reference which can be solved by `gc.collect`, not a memory leak here.
