### ISSUE TITLE
PYTORCH_TESTING_DEVICE_ONLY_FOR environment variable don't play well with development environment.

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#55707]
## 🐛 Bug

using `PYTORCH_TESTING_DEVICE_ONLY_FOR` environment variable could cause test_torch.py to not launch.

## Reproduction

run 
```
export PYTORCH_TESTING_DEVICE_ONLY_FOR=cpu
python test/test_torch.py
```
will produce the following error:
```
instantiate_device_type_tests
    assert base.device_type not in except_for or base.device_type not in only_for, AssertionError: same device cannot appear in except_for and only_for
```

This is because currently some of the tests we created are either using one or the other directly:
e.g.
```
test_torch.py:
instantiate_device_type_tests(TestDevicePrecision, globals(), except_for='cpu')
```
and 
```
test_jit.py:
  15683: instantiate_device_type_tests(TestJitGeneratedAutograd, globals(), only_for='cpu')
```

This means we can't simply set one of PYTORCH_TESTING_DEVICE_ONLY_FOR or PYTORCH_TESTING_DEVICE_EXCEPT_FOR and expect to run all tests without issue. we have to UNSET the env var to make it work.

## Proposed Solution

We should separate the user defined `only_for` or `except_for` and the environment defined except_for/only_for. 
E.g. when test filed defined only_for and env-var defined except_for, we should honor env-var over user-defined. 
because:
1. test file defined expectation for only-for/except-for means "only generate test for"
2. env var defined expectation for only-for/except-for means "only run test for"

A simple rule:

1. step 1 to resolve what are the user expected device type (by operating the same rules for except_for and only_for.
2. step 2 to only pass on the device type that passes the environment variable definitions.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by mruberry** [comment]
Are PYTORCH_TESTING_DEVICE_ONLY_FOR and PYTORCH_TESTING_DEVICE_EXCEPT_FOR documented somewhere?

Is the idea that if the environment variable PYTORCH_TESTING_DEVICE_ONLY_FOR is set it contains one or more device types, and only device generic tests for those device types are run? If so, I would expect it to intersect its set with the available device types.

Similarly, if PYTORCH_TESTING_DEVICE_EXCEPT_FOR is designed to eliminate one or more device types then I would expect it would remove the test bases for those device types.
