### ISSUE TITLE
Missing torch.* docs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#5571]
- [x] http://pytorch.org/docs/master/torch.html#torch.stack
- [x] http://pytorch.org/docs/master/torch.html#torch.where
- [x] http://pytorch.org/docs/master/torch.html#torch.set_default_tensor_type
- [x] http://pytorch.org/docs/master/torch.html#torch.chunk
^all the above done via https://github.com/pytorch/pytorch/pull/5443

- [ ] http://pytorch.org/docs/master/torch.html#torch.default_generator
- [x] torch.randn_like
- [x] tensor.index_put_

**Comment by vishwakftw** [comment]
You may be interested in https://github.com/pytorch/pytorch/pull/5443

**Comment by vadimkantorov** [comment]
no_grad, set_grad_enabled, is_grad_enabled (https://github.com/pytorch/pytorch/issues/4474)

**Comment by SsnL** [comment]
#5443 addresses all but `torch.default_generator`. :)

**Comment by zou3519** [comment]
Awesome!!

**Comment by zou3519** [comment]
I think we're also missing tensor.index_put_

**Comment by SsnL** [comment]
Yeah. It seems we didn't even document that in 0.3.1 :P

**Comment by vadimkantorov** [comment]
no_grad, set_grad_enabled, is_grad_enabled are still not in.

Also there are non-copying versions https://github.com/pytorch/pytorch/issues/1885. Are these kept around after the tensor/variable merge? They are also not documented.

**Comment by apaszke** [comment]
@vadimkantorov those are being added by @t-vi in #5555

**Comment by vadimkantorov** [comment]
torch.repeat missing: http://pytorch.org/docs/master/tensors.html#torch.Tensor.repeat

**Comment by vadimkantorov** [comment]
@zou3519 can we have some automatic grep docs script to prevent broken LaTeX formulas because of missing $ or sth like that? I found many such entries manually: https://github.com/pytorch/pytorch/issues/4819

**Comment by zou3519** [comment]
@vadimkantorov Something like that, and/or a linter for the docs, would be great. I'm not too sure how to go about doing that, though

**Comment by SsnL** [comment]
closing in favor of #9886
