### ISSUE TITLE
Error in optim/adamw.py

### ISSUE THREAD

**Issue by caodoanh2001** [pytorch/pytorch#55740]
## 🐛 Bug

Hi,

I think in `optim/adamw.py` has a small mistake with tab in from line 110.

```python=
    F.adamw(params_with_grad,
                        grads,
                        exp_avgs,
                        exp_avg_sqs,
                        max_exp_avg_sqs,
                        state_steps,
                        amsgrad,
                        beta1,
                        beta2,
                        group['lr'],
                        group['weight_decay'],
                        group['eps'])
```
In detail, from line 110 I think it should be increased by 1 tab.

I met this bugs when using mmdetection.

cc @vincentqb

**Comment by ngimel** [comment]
What is the bug that you are encountering?

**Comment by caodoanh2001** [comment]
> What is the bug that you are encountering?

Hi, when I start training model by mmdetection, I get this error:

```
UnboundLocalError: local variable 'beta1' referenced before assignment
```

When I decrease 1 tab at line 110 in file adamw.py, it seems that can solve this problem.
Maybe I think the variable beta1, beta2 are defined outside your loop so that it occurs the mentioned issues.

**Comment by ngimel** [comment]
This was fixed in #52944, what pytorch version are you using?

**Comment by FlameSky-S** [comment]
I also encountered this problem, i'm using pytorch 1.8.1 (py3.9_cuda11.1_cudnn8.0.5_0).

**Comment by stas00** [comment]
I confirm that `pytorch-1.8.1` doesn't have this fix included. And getting the same problem.

**Comment by pemryan** [comment]
> I confirm that `pytorch-1.8.1` doesn't have this fix included. And getting the same problem.

Me too confirm this

**Comment by JunHyungKang** [comment]
It seems that
beta1, beta2 = group['betas']
have to be moved to line 76??

https://github.com/pytorch/pytorch/commit/f8238d7917479b058e750156c362f858f3ec110e#diff-46de6ea1d9fce81c27638ecd7f137c781fd64d02acea698c432a8ddb916ea51f

**Comment by iramazanli** [comment]
> This was fixed in #52944, what pytorch version are you using?

This issue has been indeed solved with #52944 and it's in the latest master.

**Comment by ElectronicElephant** [comment]
hmmm, it seems that 1.8.2 LTS doesn't have this fix included.

**Comment by Wuzhongze** [comment]
> It seems that beta1, beta2 = group['betas'] have to be moved to line 76??
> 
> [f8238d7#diff-46de6ea1d9fce81c27638ecd7f137c781fd64d02acea698c432a8ddb916ea51f](https://github.com/pytorch/pytorch/commit/f8238d7917479b058e750156c362f858f3ec110e#diff-46de6ea1d9fce81c27638ecd7f137c781fd64d02acea698c432a8ddb916ea51f)
it does work
