### ISSUE TITLE
_ConvNd weight initialization does not match docs

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#55741]
## 🐛 Bug

`_ConvNd.reset_parameters` initializes the weight parameters as follows:

```
init.kaiming_uniform_(self.weight, a=math.sqrt(5))
```
See https://github.com/pytorch/pytorch/blob/v1.8.1/torch/nn/modules/conv.py#L115

This is not consistent with the documentation:

![Screen Shot 2021-04-10 at 11 00 12 AM](https://user-images.githubusercontent.com/35972327/114279965-f9aa8b80-99eb-11eb-85bc-a12cb6a9c7c5.png)

https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html?highlight=conv2d#torch.nn.Conv2d

I believe the `sqrt(5)` is incorrect. It was introduced in PR #9038 which appears to be a documentation change. I am not aware of anything in the literature which suggests that `sqrt(5)` should be used.

Originally reported here:

https://www.youtube.com/watch?v=4u8FxNEDUeg&t=6220s

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by msbaines** [comment]
Looks like the sqrt(5) may be intentional:

https://github.com/pytorch/pytorch/issues/15314

Should the docs be updated to reflect the reality.

**Comment by jbschlosser** [comment]
@msbaines Yes, the docs should be fixed to match what's actually happening.

**Comment by thomasjpfan** [comment]
The docstring is correct in this case. For example:

```python
import math
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

in_channels = 120
groups = 2
kernel = (3, 8)
m = nn.Conv2d(in_channels=in_channels, groups=groups,
              out_channels=100, kernel_size=kernel)

k = math.sqrt(groups / (in_channels * math.prod(kernel)))
print(f"k: {k:0.6f}")

print(f"min weight: {m.weight.min().item():0.6f}")
print(f"max weight: {m.weight.max().item():0.6f}")
```

outputs:
```
k: 0.026352
min weight: -0.026352
max weight: 0.026352
```

And when we plot the distribution, it is uniform with the correct bounds:

```python
_ = plt.hist(m.weight.detach().numpy().ravel())
```

![Unknown](https://user-images.githubusercontent.com/5402633/119552979-21ba3800-bd69-11eb-8e10-e067c943abe3.png)


I opened #58931 that adds a code comment to avoid future confusion.
