### ISSUE TITLE
Pytorch quantize method QAT support int8 or uint8 inference

### ISSUE THREAD

**Issue by fwz-fpga** [pytorch/pytorch#55769]
I am weird about pytorch quantization.
In this link https://pytorch.org/docs/stable/quantization.html, whether PTQ or QAT, pytorch use int8 as quantize default data_type. 
But in qnnpack, there are many functions realize with uint8. So I am confused that when running a QAT model with pytorch in forward pass, It running with uint8 data_type or int8.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @ezyang @rgommers @mruberry

**Comment by jerryzh168** [comment]
we typically use `quint8` for activations and `qint8` for weights.

**Comment by jerryzh168** [comment]
also please use discussion forums for questions: https://discuss.pytorch.org/c/quantization/17
