### ISSUE TITLE
[ROCm] Tests fail on my system.

### ISSUE THREAD

**Issue by Wulfsta** [pytorch/pytorch#55762]
## 🐛 Bug

Tests fail, output [here](https://gist.github.com/Wulfsta/05c5e2d2d45f0579b4b5da60b9f018e6).

## To Reproduce

1. Clone repo
2. Check out 1.8.0
3. Run tests with `PYTORCH_TEST_WITH_ROCM=1 python3 test/run_test.py --verbose`

## Expected behavior

Tests pass.

## Environment

```
$ python3 collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+rocm4.0.1
[pip3] torchvision==0.9.0a0+8fb5838
[conda] Could not collect
```
Since that seemed unhappy:
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - CUDA/cuDNN version: ROCm 4.0.1, with `rocm-dkms`
 - GPU models and configuration: Radeon VII
 - Any other relevant information: This is a clean installation on a newly installed OS.

## Additional context

Noticed something was wrong when trying to run my implementation of neural styling.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by Wulfsta** [comment]
Anyone look into this yet?

**Comment by ROCmSupport** [comment]
Hi @Wulfsta 
Thanks for reaching out.
Can you please share the exact steps you followed(one by one), starting from installing rocm and etc.
And also share the docker image details(if any).
Thank you.

**Comment by Wulfsta** [comment]
I followed the steps (loosely) on [your guide](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html), as follows:
```
# apt update
# apt dist-upgrade
# apt install libnuma-dev
# reboot
# wget -q -O - https://repo.radeon.com/rocm/apt/4.0.1/rocm.gpg.key | apt-key add -
# echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/4.0.1/ xenial main' | tee /etc/apt/sources.list.d/rocm.list
# apt update
# apt install rocm-dkms 
# reboot
# apt install rocm-libs
# reboot
# echo 'export PATH=$PATH:/opt/rocm/bin:/opt/rocm/rocprofiler/bin:/opt/rocm/opencl/bin' | tee -a /etc/profile.d/rocm.sh
# usermod -a -G video <user>
# pip3 install torch -f https://download.pytorch.org/whl/rocm4.0.1/torch_stable.html
# pip3 install ninja
# pip3 install 'git+https://github.com/pytorch/vision.git@v0.9.1'
# reboot
```
Notice that the version is pinned to `4.0.1` as needed by both my hardware and the PyTorch beta. This is not the state of my system currently - I switched to trying the default Linux kernel with `rocm-dev` and `udev` rules after this, where I am experiencing the same issues. Root was achieved using `sudo` or `sudo -H` where appropriate. Both `rocminfo` and `clinfo` appeared to be correct from my past experience. The clocks and voltages on my card are at defaults. I also noticed that I initially checked out the wrong branch of PyTorch to test - after rerunning on 1.8.1 I see the same issues. I have also tried running with `MIOPEN_FIND_ENFORCE=3` as this helped once with an older ROCm release, this had no effect. I can provide more info or run tests if it will help debug - but keep in mind that I am not using the `rocm-dkms` module any longer.

**Comment by jeffdaily** [comment]
Worth mentioning that the ROCm PyTorch wheels bundle all ROCm user-space libraries (i.e., no linux kernel module).  Similar to CUDA wheels.  There should not be any immediate need to install the deb rocm-libs package; you should only need rocm-dkms for the linux kernel module.

Is it safe to assume that you are pip installing as indicated in your comment, and then cloning the release/1.8 branch for the test directory?

**Comment by Wulfsta** [comment]
@jeffdaily I believe I just installed `rocm-libs` out of caution and didn’t actually try it without. But yes, your assumptions are correct, I am installing with pip then cloning the git repo and switching to the 1.8.1 branch to run tests.

**Comment by jeffdaily** [comment]
`PYTORCH_TEST_WITH_ROCM=1 python3 test/run_test.py --verbose` is definitely the correct way to run tests for ROCm.  Would it be asking too much for you to provide a log file for it?  I would suggest adding `--continue-through-error` so it will capture the full suite and not stop at the first error.

**Comment by Wulfsta** [comment]
Sure, I’ll run it and get back to you.

**Comment by Wulfsta** [comment]
Sorry for the double comment, but when you say log file you’re just looking for the stout and stderr right? There’s not a file I should also be providing?

**Comment by jeffdaily** [comment]
> Sorry for the double comment, but when you say log file you’re just looking for the stout and stderr right? There’s not a file I should also be providing?

Yes, sorry.  Just capture stdout/stderr and report which tests are failing for you.  Thanks.

**Comment by Wulfsta** [comment]
@jeffdaily While this is running, have you taken a look at the other output I included? It is linked in a gist. There are quite a few things that look alarming, such as the NaNs appearing everywhere in equality checks.

**Comment by Wulfsta** [comment]
@jeffdaily [here you go](https://gist.githubusercontent.com/Wulfsta/5d8b2b902e1068433aaf737657453a25/raw/18028b37ea909905d23b60805399df4ea0c6172b/gistfile1.txt).

**Comment by jeffdaily** [comment]
@Wulfsta sorry I missed that gist link.  Taking a guess without looking.  Some of the failing tests are likely due to our recent addition of magma support.  magma support is beta.  The magma project only recently merged all ROCm support into their master branch, and we had been using an older commit.  Our nightly wheel will soon have better magma support.  Best we can do is try to address as many of these failures as we can prior to the next pytorch release.

@jithunnair-amd we should get this assigned for someone to look into.

**Comment by Wulfsta** [comment]
@jeffdaily No problem, I appreciate the help! If you want to point me to a commit in either this repo or the ROCm fork I will happily build from source if it gets me running.

**Comment by Wulfsta** [comment]
Are there any updates on this?

**Comment by jithunnair-amd** [comment]
Hi @Wulfsta, this is a very broad issue since it relates to multiple unit test failures in PyTorch, which fall in a few different thematic buckets. Having said that, the nan issues definitely look concerning. Can I first understand if you have a constraint on which ROCm version you can use and also whether you can only use the stable wheels of PyTorch (as opposed to the nightly ones, which are closer to tip-of-tree)?

**Comment by Wulfsta** [comment]
My only constraint on the ROCm version has been that I have a Radeon VII, which has been disabled prior to kernel 5.13 due to some bug (as I understand it). To more appropriately answer your question, last night I updated to Ubuntu 21.04 and installed kernel 5.13rc1, and have a working ROCm 4.2 version as far as I can tell. I then cloned PyTorch from the ROCm fork and built from source and am still experiencing the same issues when trying out some of my old code. I haven’t run a comprehensive test yet, but I suspect it will fail the same way.

**Comment by jithunnair-amd** [comment]
That's a helpful datapoint from ROCm4.2. If you could please provide us the commit of PyTorch that you're building (and running unit tests) with, along with the full log file, I can request the relevant folks to look into the failures.

**Comment by Wulfsta** [comment]
Sorry, got distracted. I tried to run the tests for PyTorch and noticed some failures due to missing dependencies (not sure how they got missed when building the first time), and installed them and rebuilt. It appears to be working for me at this point - I have not had time to run a full test suite yet.

**Comment by jithunnair-amd** [comment]
Thanks for confirming. I'm closing this issue.
