### ISSUE TITLE
DDP sample code doesn't work

### ISSUE THREAD

**Issue by turian** [pytorch/pytorch#55763]
## 📚 Documentation

On LambdaLabs, I spin up a two-GPU machine. I run the simple example code at the top of the [pytorch DDP docs](https://pytorch.org/docs/stable/notes/ddp.html)

However, I can't even get the simple example to run:

```
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
<ipython-input-1-e1523c2c83af> in <module>
     34 
     35 if __name__=="__main__":
---> 36     main()

<ipython-input-1-e1523c2c83af> in main()
     28 def main():
     29     world_size = 2
---> 30     mp.spawn(example,
     31         args=(world_size,),
     32         nprocs=world_size,

~/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    228                ' torch.multiprocessing.start_process(...)' % start_method)
    229         warnings.warn(msg)
--> 230     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

~/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

~/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    137                 )
    138             else:
--> 139                 raise ProcessExitedException(
    140                     "process %d terminated with exit code %d" %
    141                     (error_index, exitcode),

ProcessExitedException: process 0 terminated with exit code 1
```

How can I get a simple DDP example to run?

I will note that it works if join=False. But why does this simple pytorch doc example not work as written?

cc @brianjo @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by skyline75489** [comment]
Are you using macOS? be sure to provide as much as information as you can. There's [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) that helps you do that.

**Comment by turian** [comment]
LambdaLabs is Ubuntu. I upgrade torch to 1.8.1 (1.8.1+cu102) and here is the env:

```
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Quadro RTX 6000
GPU 1: Quadro RTX 6000

Nvidia driver version: 450.80.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.8.1
[pip3] torchvision==0.7.0
[conda] Could not collect
```

**Comment by agolynski** [comment]
Link to forum: https://discuss.pytorch.org/t/ddp-processexitedexception-process-0-terminated-with-exit-code-1/117800/3

I wasn't able to repro this, seems like this tutorial works with my setup (current master branch), maybe worth trying on 1.8.1, but  result will probably be same as this is very basic code.

**Comment by turian** [comment]
Cross-posting some info from the forum thread:

I'm on a 2 GPU machine from [LambdaLabs](https://lambdalabs.com/service/gpu-cloud) if you want to try and replicate. (I upgrade torch to the latest release when I create the instance.)

Do I need to add anything extra to use the GPUs?

**Comment by zhaojuanmao** [comment]
closing it as it was explained in the forum
