### ISSUE TITLE
JIT: Unknown type constructor Final

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#55783]
## 🐛 Bug

`typing.Final` cannot be used in jit'ed code. ~~Might be python 3.9 related? I don't remember having issues with that before upgrading to 3.9 (might be misremembering).~~

## To Reproduce

```py
from typing import Final

import torch


def fun() -> int:
    test: Final[int] = 1
    return test

torch.jit.script(fun)
```
```
RuntimeError                              Traceback (most recent call last)
/pool01/home/twoertwe/foo.py in <module>
      9
     10
---> 11 torch.jit.script(fun)

/pool01/home/twoertwe/.cache/pypoetry/virtualenvs/python-tools-XWCSm5JO-py3.9/lib/python3.9/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    987         if _rcb is None:
    988             _rcb = _jit_internal.createResolutionCallbackFromClosure(obj)
--> 989         fn = torch._C._jit_script_compile(
    990             qualified_name, ast, _rcb, get_default_args(obj)
    991         )

RuntimeError:
Unknown type constructor Final:
  File "/pool01/home/twoertwe/foo.py", line 7
def fun() -> int:
    test: Final[int] = 1
          ~~~~~~~~~~ <--- HERE
    return test
```

## Environment

I installed pytorch through poetry.

Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2~16.04) 9.3.0
Clang version: 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
CMake version: version 3.15.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr0/local/cuda-9.0/lib64/libcudnn.so.7.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1+cu102
[pip3] torchvision==0.9.1+cu102
[conda] Could not collect

cc @gmagogsfm

**Comment by Lilyjjo** [comment]
@twoertwein we currently don't support this feature, we can look into putting it onto our roadmap for next half. Thank you for the report!

**Comment by twoertwein** [comment]
It is probably not necessary to have `Final` within functions as you already know which variables will (not) change since the function gets compiled. And you already support `Final` for attributes which is far more useful!
