### ISSUE TITLE
Subclassing `torch.Tensor` raises warnings from deprecated constructor.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#55780]
Follow up: #47112

Creating `Tensor` subclass' instances raises an warning due to its recent deprecation:

```python
class MyTensor(torch.Tensor):
    pass

# Works, but raises warning!
tensor = MyTensor([1, 2, 3])
```

```
UserWarning: Legacy tensor constructor is deprecated.
Use: torch.tensor(...) for creating tensors from tensor-like objects; or
torch.empty(...) for creating an uninitialized tensor with specific sizes.
(Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:477.)
```

## Expected behavior

In the docs (https://pytorch.org/docs/stable/notes/extending.html), subclassing `Tensor` is mentioned as being supported. So, I guess, ideally, there either shouldn't be any warnings or it shouldn't be supported. 

cc @gchanan @mruberry

**Comment by ysiraichi** [comment]
@rgommers suggested ([here](https://github.com/pytorch/pytorch/pull/54142#discussion_r598784570)) having the subclass implement the `__new__` method, using `torch.tensor`.

Not sure if that is the best way to go, though. Maybe, for backwards compatibility, we could create a new tensor class specifically for being subclassed that implements such `__new__` method...

**Comment by mruberry** [comment]
@heitorschueroff the change causing this issue was reverted, right? Would you update the title of this issue and summarize the current state of the code?

**Comment by heitorschueroff** [comment]
> @heitorschueroff the change causing this issue was reverted, right? Would you update the title of this issue and summarize the current state of the code?

I couldn't ninja revert because it was over a day, I just need you approval here https://github.com/pytorch/pytorch/pull/55831.

**Comment by heitorschueroff** [comment]
This was fixed in https://github.com/pytorch/pytorch/pull/55831
