### ISSUE TITLE
"Add annotations" workflow fails when base branch is pinned to old commit

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#55810]
Our ["Add annotations"](https://github.com/pytorch/pytorch/actions/workflows/add_annotations.yml) workflow in [`.github/workflows/add_annotations.yml`](https://github.com/pytorch/pytorch/blob/c91cf1e7a9d555848aa15620dd8b92df26ed8048/.github/workflows/add_annotations.yml) runs after the "Lint" workflow finishes, and works by downloading artifacts from that completed "Lint" workflow run, unzipping them, and uploading their contents as [GitHub Checks](https://docs.github.com/en/rest/reference/checks). Therefore, in a sense the success of the "Add annotations" workflow depends on the contents of the artifacts uploaded by the "Lint" workflow:

- Prior to #55569, the list of annotations was expected to be given in a `warnings.txt` file as one annotation per line.
- Since #55569, the list of annotations is expected to be given in an `annotations.json` file as a literal JSON list.

Note that the "Add annotations" workflow (the artifact consumer) is triggered by the [`workflow_run`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run) event, so its definition is always taken from the latest commit on the PyTorch `master` branch. Then because (as of #54967) we merge the PR with its base branch before running most of our GitHub Actions `pull_request` workflows (including "Lint"), that definition should be in sync with the definition of the "Lint" workflow (the artifact producer) as long as the pull request's base branch is `master`.

However, that assumption is not always true:

- Many PRs use [`ghstack`](https://github.com/ezyang/ghstack), which creates `gh/*/*/base` branches that are pinned to a specific commit.
  - Example PR: https://github.com/pytorch/pytorch/pull/55795
  - Failing "Add annotations" run: https://github.com/pytorch/pytorch/actions/runs/742013872
- Some recent PRs have been based against the [`pytorch:onnx_ms_1`](https://github.com/pytorch/pytorch/tree/onnx_ms_1) branch.
  - Example PR: https://github.com/pytorch/pytorch/pull/55802
  - Failing "Add annotations" run: https://github.com/pytorch/pytorch/actions/runs/742016540

In those cases, the "Lint" workflow definition does not incorporate the latest [`pytorch:master`](https://github.com/pytorch/pytorch/tree/master), so it can be out of sync with the "Add annotations" workflow definition. As a result, the latter (consuming) workflow unzips the artifact, sees that it does not contain the expected file(s), and fails.

A couple possible remedies come to mind:

1. Do nothing. Let the workflows fail, since they are indeed failing to do their job, and the issue can be remedied by changing the pull request's base branch to point to a more recent commit from `master`.
2. Add more checks to the "Add annotations" workflow to ensure that the contents of the artifact look as expected, and silently abort if not (marking the workflow as "succeeded").

Note that simply reverting #55569 is _not_ a solution to this problem, because that would just cause workflows based on commits between #55569 and its revert to fail for exactly the same reason.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry

**Comment by mruberry** [comment]
What are the pros/cons of (1) and (2)? Assuming we picked an option what should we do next time we make a change like this? Or are changes like this so rare we don't need to consider a hypothetical "next time?"

**Comment by samestep** [comment]
> What are the pros/cons of (1) and (2)? Assuming we picked an option what should we do next time we make a change like this? Or are changes like this so rare we don't need to consider a hypothetical "next time?"

@mruberry I definitely don't expect that changes to these workflows are going to be "rare", especially over the next few months.

1. Pros:

   - It's less work.
   - It keeps the `.github/workflows/add_annotations.yml` code simpler.
   - It makes it easier to catch genuine bugs in the interaction between the "Lint" workflow and the "Add annotations" workflow.

   Cons:

   - Any time a change is made to the way these two workflows interact with each other, these same failures will crop up again.

2. Pros:

   - Given the lack of atomicity between the "Lint" workflow definition and the "Add annotations" workflow definition (since the latter always comes from `master`), having error checking in the latter is the morally correct thing to do.
   - Using a general strategy of expecting malformed input will prevent these sorts of failures from happening when future changes to these workflows are made.

   Cons:

   - If we silently abort and succeed whenever the input doesn't match our expectations, the "Add annotations" workflow might just stop working for a while before we notice that it's broken.

**Comment by mruberry** [comment]
Those are good pros and cons. Do you have a recommendation?

**Comment by samestep** [comment]
> Those are good pros and cons. Do you have a recommendation?

@mruberry I plan to implement approach (2) soon.
