### ISSUE TITLE
Failed to export split to ONNX opset13 with dynamic shape

### ISSUE THREAD

**Issue by skyw** [pytorch/pytorch#55840]
## 🐛 Bug

When exporting `split` operation to ONNX in opset13 with dynamic shape, it fails with "**TypeError: 'NoneType' object is not subscriptable**"

## To Reproduce

1. Run the following code
```python
import torch

dummy_input = torch.randn(4, 384, 2, device='cuda')
input_names = ["logits"]

class Split(torch.nn.Module):
    def forward(self, x):
        return x.split(1, dim=-1)
model = Split()

with torch.no_grad():
    torch.onnx.export(
        model, dummy_input, "split.onnx", verbose=True, opset_version=13,
        enable_onnx_checker=True, do_constant_folding=False,
        input_names=input_names,
        dynamic_axes={input_names[0]: {0: 'batch'}}
    )
```

## Expected behavior

It should export to ONNX with a dynamic input shape, same as for other ops.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1+cu111
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: V100-DGXS-32GB
 - Any other relevant information:

## Additional context

This is discovered when exporting HuggingFace BERT model to ONNX.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
Tracked internally by https://msdata.visualstudio.com/Vienna/_workitems/edit/1262837

**Comment by shangz-ai** [comment]
Hi, I'm curious whether this issue has been fixed? If so, in what version of pytorch?

**Comment by garymm** [comment]
No. The issue will be closed when it's known to be fixed.

**Comment by shangz-ai** [comment]
Interesting. It seems that I didn't have this issue anymore when using torch==1.10.0a0+ecc3718.

**Comment by garymm** [comment]
Thanks for letting us know.
