### ISSUE TITLE
Using `__torch_function__` with RNN module

### ISSUE THREAD

**Issue by KatiaSN602** [pytorch/pytorch#55868]
## To Reproduce

1. Defining new Tensor following the logic described here: https://pytorch.org/docs/stable/notes/extending.html#extending-torch
2. Note that the new tensor is not subclasses `torch.Tensor`. 
3. define new function for `torch.rnn_tanh`.
4. When trying to use RNN model with the new tensor, hitting the following error:
``` 
File "/common/pytorch1.8/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/common/pytorch1.8/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 244, in forward
    assert isinstance(input, Tensor)
AssertionError
```
basically, we can't mix RNN module with the `__torch_function__` feature, if the new Tensor is not subclassing `torch.Tensor`

example of simplified version of my code:
```
HANDLED_FUNCTIONS = {}
class MyTensor(object):
    def __init__(self, torch_tensor):
         self.torch_tensor = torch_tensor
   
    def __torch_function__(self, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        if func not in HANDLED_FUNCTIONS or not all(
            issubclass(t, (torch.Tensor, ScalarTensor))
            for t in types
        ):
            return NotImplemented
        return HANDLED_FUNCTIONS[func](*args, **kwargs)

import functools
def implements(torch_function):
    """Register a torch function override for ScalarTensor"""
    @functools.wraps(torch_function)
    def decorator(func):
        HANDLED_FUNCTIONS[torch_function] = func
        return func
    return decorator

@implements(torch.rnn_tanh)
def rnn_tanh(input, hx, weights, bias, num_layers,
             dropout_p, train, bidirectional, batch_first):
    return my_computation(...)

model = RNN(10, 20, 2)
input = MyTensor(torch.randn(1, 5, 10))
model(input)
```

## Expected behavior

To be able to mix the above behaviors when I removed the assertions in the below lines it works:
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L244
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L250

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 11.0.0
CMake version: version 3.19.4

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1
[conda] Could not collect

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @hameerabbasi @rgommers @peterbell10 @malfet @xuzhao9 @gramster

**Comment by ngimel** [comment]
Thanks for reporting!

**Comment by rgommers** [comment]
This came in in commit ca8b9437ab5. The reason for it is that `mypy`'s type inference isn't good enough, so there's lots of asserts needed to force it to do "type narrowing" for variables that were defined as `Optional[Tensor]` or a `Union`, but where at the point of the assert the variable is guaranteed to be a tensor.

This is kind of an annoying issue. Perhaps a solution is to change such asserts to:
```
if typing.TYPE_CHECKING:
    assert ...
```
but that's even uglier. We could wrap those two lines in a separate `mypy_assert()` which would be clearer and not too costly at runtime (~150 ns):
```
def mypy_assert(truthval):
    if typing.TYPE_CHECKING:
        assert truthval

mypy_assert(isinstance(x, torch.Tensor))
```
Anyone have a better idea?

A workaround right now is to run your program with `python -O` (or equivalently, `export PYTHONOPTIMIZE=1`), which strips all the asserts.

**Comment by ezyang** [comment]
Personally, I'd just start slapping `if typing.TYPE_CHECKING:` everywhere if needed

**Comment by peterbell10** [comment]
How about  `type: ignore`:
```
input_t: Tensor = input  # type: ignore
```

Or alternatively, there's `typing.cast`:
```
input_t = cast(Tensor, input)
```

`type: ignore` should have no overhead. `cast` just returns the argument without doing anything, so has the overhead of 1 function call (40 ns for me).

**Comment by rgommers** [comment]
`# type: ignore` isn't great, it will just give an error on the next line that same variable is used again.

`typing.cast` is nice, that's basically the more-nicely-spelled version of `if typing.TYPE_CHECKING: assert isinstance(...)` - let's try that I'd say.

**Comment by KatiaSN602** [comment]
Wow! Thanks for the quick reply!

**Comment by KatiaSN602** [comment]
Another question: 
I want to move to a later version of PyTorch in my project (currently 1.7), couldn't move to 1.8 due to this issue.
In which version this fix will be available?
Thanks!

**Comment by ezyang** [comment]
bumping prio based on user activity
