### ISSUE TITLE
[bug] run test local

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#55882]
After #55753,

```
pytest test/test_ops.py 
======================================================================= test session starts ========================================================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/kshiteej/Pytorch/pytorch_fix_test, configfile: pytest.ini
plugins: hypothesis-5.38.1
collected 0 items                                                                                                                                                  

```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @VitalyFedyunin @walterddr

**Comment by imaginary-person** [comment]
@ngimel already has a PR open for it (#55880).

**Comment by kshitij12345** [comment]
Oh thanks. Didn't notice that!

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/pull/55880 is merged, so this should be addressed. Please reopen if it's not!

**Comment by walterddr** [comment]
yikes. my bad for not testing it thoroughly. adding a special test case to capture this in the future

**Comment by walterddr** [comment]
#55931 should prevent this from happening in the future
