### ISSUE TITLE
Multiprocessing start method error when model_zoo is imported

### ISSUE THREAD

**Issue by gliese581gg** [pytorch/pytorch#5589]
When I ran following code,

```python
import torch.utils.model_zoo as model_zoo
import torch.multiprocessing as mp

if __name__ == '__main__':
	mp.set_start_method('spawn')

```

I got 'RuntimeError: context has already been set'

Is it normal? How can I use both 'spawn' start method and model_zoo?

**Comment by apaszke** [comment]
This works just fine for me. Use the issue template to provide us additional information about your system config.

**Comment by jerett** [comment]
same problem
