### ISSUE TITLE
How should I warmup JIT properly ?

### ISSUE THREAD

**Issue by w1d2s** [pytorch/pytorch#55898]
Hi everyone, I am curious about how JIT's auto optimization works when it is related to tensor's shape? If my model have to deal with dynamic shape inputs ( for example dynamic sequence length and batch size in seq-2-seq models ) ,  how should I design dummy input shape for warmup ? Should I enumerate all possible shapes the model may encounter at real inference ? And how should I do when enumerate is impossible if good inference speed is still desired ? Thank you for your attention.

cc @gmagogsfm

**Comment by eellison** [comment]
We're working on the underlying issue, and we will add documentation for the next release. will post here when it is published.

**Comment by w1d2s** [comment]
> We're working on the underlying issue, and we will add documentation for the next release. will post here when it is published.

Thanks for attention.

**Comment by eellison** [comment]
Hi, JIT is in stable mode, we recommend moving to torch.compile. To warmup your jit model - run twice before expecting optimized serving.
