### ISSUE TITLE
RuntimeError: ProcessGroupNCCL does not support gather

### ISSUE THREAD

**Issue by eldarkurtic** [pytorch/pytorch#55893]
## 🐛 Bug

Calling `torch.distributed.gather` with `nccl` backend results with: `RuntimeError: ProcessGroupNCCL does not support gather`.

## To Reproduce

I can provide code to reproduce the issue, but I would first like to understand if `gather` is supported with `nccl` backend at all.
The documentation is a kind of confusing:
1. [The documentation for `torch.distributed.gather`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.gather) doesn't mention that it's not supported, like it's clearly mentioned for [`torch.distributed.gather_object`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.gather_object) so I've assumed it is.
2. [The table](https://pytorch.org/docs/stable/distributed.html) at the top of the documentation page says that `gather` is not supported with `nccl` backend.

cc @brianjo @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by zhaojuanmao** [comment]
right, nccl does not support gather yet. once nccl supports it, processGroupNCCL will add this support as well

**Comment by rohan-varma** [comment]
@zhaojuanmao I'm wondering if it's worth it to file an issue discussing implementing `gather` ourselves via send/recv?

**Comment by ppwwyyxx** [comment]
An easy workaround that I think torch.distributed could implement is to just use allgather (which NCCL supports) to implement gather, even though that's slower.
