### ISSUE TITLE
AssertionError: Requested Kineto profiling but Kineto is not available, make sure PyTorch is built with USE_KINETO=1

### ISSUE THREAD

**Issue by Aduersarius** [pytorch/pytorch#55892]
## 🐛 Bug
I'm trying new profiler, but it doesnt work, because torch.autograd.kineto_available() returns False

## To Reproduce

i'm just using basic syntax:

with torch.profiler.profile(
            schedule=torch.profiler.schedule(
                wait=2,
                warmup=2,
                active=6,
                repeat=1),
            on_trace_ready=torch.profiler.tensorboard_trace_handler(".\\runs"),) as p:
...
p.step()
etc..

## Full traceback

File "c:\Users\emire\vs_repositories\rl_bot\modules\agent.py", line 83, in rl_agent_train
    p.step()
  File "C:\Users\emire\AppData\Roaming\Python\Python37\site-packages\torch\profiler\profiler.py", line 259, in step
    self._start_warmup()
  File "C:\Users\emire\AppData\Roaming\Python\Python37\site-packages\torch\profiler\profiler.py", line 362, in _start_warmup
    use_kineto=True,
  File "C:\Users\emire\AppData\Roaming\Python\Python37\site-packages\torch\autograd\profiler.py", line 463, in __init__
    make sure PyTorch is built with USE_KINETO=1"""
AssertionError: Requested Kineto profiling but Kineto is not available,
                  make sure PyTorch is built with USE_KINETO=1

## Environment

```

 - PyTorch Version (e.g., 1.0): 1.8.1+cu111
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): dont remember, but something default here
 - Python version: 3.7.9
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: GTX970
 - Any other relevant information:

## Additional context
```
So how to deal with it? Should i somehow rebuild torch with USE_KINETO=1 (then how?) or there any other ways?

cc  @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @peterjc123 @mszhanyi @skyline75489

**Comment by malfet** [comment]
Removing `build` flag as kineto is not supported for Windows yet:
https://github.com/pytorch/pytorch/blob/5dba4ff786415973213f3c270a793698e635be1f/cmake/Dependencies.cmake#L1813-L1816

**Comment by ilia-cher** [comment]
Thanks for reporting, support for Windows is scheduled in 1.9
