### ISSUE TITLE
F.interpolate recompute_scale_factor doc is bad

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#55909]
## 📚 Documentation

The doc reads
> recompute_scale_factor (bool, optional) – recompute the scale_factor for use in the interpolation calculation. When scale_factor is passed as a parameter, it is used to compute the output_size. If recompute_scale_factor is False or not specified, the passed-in scale_factor will be used in the interpolation computation. Otherwise, a new scale_factor will be computed based on the output and input sizes for use in the interpolation computation (i.e. the computation will be identical to if the computed output_size were passed-in explicitly). Note that when scale_factor is floating-point, the recomputed scale_factor may differ from the one passed in due to rounding and precision issues.

I can't understand what it means after reading many times.  Some confusions: 
+ > When scale_factor is passed as a parameter, it is used to compute the output_size. 
   
  What does `parameter` mean? Like a trainable parameter?  If this just says that "if `scale_factor` is given, output size will be computed using it", then shouldn't this sentence be in `scale_factor` doc instead?. 

+ >  If recompute_scale_factor is False or not specified, the passed-in scale_factor will be used in the interpolation computation.

   This says that if `recompute_scale_factor=True`, `scale_factor` will *not* be used? How does that make sense?

+ > Otherwise, a new scale_factor will be computed based on the output and input sizes for use in the interpolation computation (i.e. the computation will be identical to if the computed output_size were passed-in explicitly).

   The above sentence just said that `scale_factor` will not be used then, but how  would you get the output size if that is the case? Does it mean that I should use `size` instead? 

Additionally, this arg doc is also bad
> scale_factor (float or Tuple[float]) – multiplier for spatial size. Has to match input size if it is a tuple.

should be "If it is a tuple, its size has to match input dimensions".

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by jbschlosser** [comment]
Thanks for reporting this, @SsnL. Definitely agree that these docs could use some improvements.
