### ISSUE TITLE
how to convert libtorch trained model to torch script model

### ISSUE THREAD

**Issue by WuLoing** [pytorch/pytorch#55914]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by jbschlosser** [comment]
As mentioned, please ask questions like this on the [PyTorch forums](https://discuss.pytorch.org/). That said, you may find this link useful: https://pytorch.org/tutorials/advanced/cpp_export.html
