### ISSUE TITLE
sparse.addmm on CUDA returns wrong result when beta is not zero or one

### ISSUE THREAD

**Issue by sorenrasmussenai** [pytorch/pytorch#55917]
## 🐛 Bug

`torch.sparse.addmm` returns a wrong result on CUDA whenever `beta` is not 0 or 1.
Results on CPU are correct.

## To Reproduce
Test function:
```
import torch

def test_addmm(m,n,p, alpha, beta):
    A = torch.rand(m,n)
    B = torch.rand(n,p)
    C = torch.rand(m,p)
    As = A.to_sparse()

    Y_dense_cpu  = torch.addmm(C, A,  B, beta=beta, alpha=alpha)
    Y_sparse_cpu = torch.addmm(C, As, B, beta=beta, alpha=alpha)
    Y_dense_gpu  = torch.addmm(C.cuda(), A.cuda(),  B.cuda(), beta=beta, alpha=alpha)
    Y_sparse_gpu = torch.sparse.addmm(C.cuda(), As.cuda(), B.cuda(), beta=beta, alpha=alpha) #Using torch.sparse.addmm here makes no difference

    mean_abs_err = lambda a,b: (a.cpu() - b.cpu()).abs().mean().item()
    all_equal = lambda a,b: (a.cpu() == b.cpu()).all().item()
    compare = lambda a,b: (all_equal(a,b), mean_abs_err(a,b))

    print(f"{alpha=} {beta=}")
    print("---------------------------------------------------------")
    print("Tensor 1     Tensor 2     : (All equal?, Mean abs. error)")
    print("---------------------------------------------------------")
    print("Y_dense_cpu, Y_sparse_cpu :", compare(Y_dense_cpu, Y_sparse_cpu))
    print("Y_dense_cpu, Y_dense_gpu  :", compare(Y_dense_cpu, Y_dense_gpu))
    print("Y_dense_gpu, Y_sparse_gpu :", compare(Y_dense_gpu, Y_sparse_gpu))
```
**Correct results with `beta==1` and `beta==0`.**
We se a minor difference between CPU and GPU, probably due to implementation differences.
```
>>> test_addmm(m=4,n=6,p=2, alpha=1.0, beta=1.0)
alpha=1.0 beta=1.0
---------------------------------------------------------
Tensor 1     Tensor 2     : (All equal?, Mean abs. error)
---------------------------------------------------------
Y_dense_cpu, Y_sparse_cpu : (True, 0.0)
Y_dense_cpu, Y_dense_gpu  : (False, 1.341104507446289e-07)
Y_dense_gpu, Y_sparse_gpu : (False, 2.9802322387695312e-08)
```

```
>>> test_addmm(m=4,n=6,p=2, alpha=1.0, beta=0.0)`
alpha=1.0 beta=0.0
---------------------------------------------------------
Tensor 1     Tensor 2     : (All equal?, Mean abs. error)
---------------------------------------------------------
Y_dense_cpu, Y_sparse_cpu : (True, 0.0)
Y_dense_cpu, Y_dense_gpu  : (False, 7.450580596923828e-08)
Y_dense_gpu, Y_sparse_gpu : (False, 5.960464477539063e-08)
```
**Wrong result:**
```
>>> test_addmm(m=4,n=6,p=2, alpha=1.0, beta=10.0)
alpha=1.0 beta=10.0
---------------------------------------------------------
Tensor 1     Tensor 2     : (All equal?, Mean abs. error)
---------------------------------------------------------
Y_dense_cpu, Y_sparse_cpu : (True, 0.0)
Y_dense_cpu, Y_dense_gpu  : (False, 3.5762786865234375e-07)
Y_dense_gpu, Y_sparse_gpu : (False, 47.474510192871094)
```
## Expected behavior

Equal results, within reasonable limits (like when `beta` is 0 or 1)

## Environment

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.1+cu111
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @aocsa @nikitaved @pearu @mruberry

## Edited:
Fixed minor error, not significant

**Comment by jbschlosser** [comment]
Replicated this on master.

I think there's a minor error in the second comparison of your test script, but it's irrelevant:
```python
print("Y_dense_cpu, Y_dense_gpu  :", compare(Y_dense_cpu, Y_dense_cpu))  # Comment doesn't match comparison
```

**Comment by sorenrasmussenai** [comment]
> I think there's a minor error in the second comparison of your test script, but it's irrelevant:

Fixed :)

**Comment by sorenrasmussenai** [comment]
@jbschlosser 
The perpetrator is [this line](https://github.com/pytorch/pytorch/blob/79857534213f26dd23dd0a1f590cf666180d230f/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L72).

The core functionality of `s_addmm_out_sparse_dense_cuda_worker` lies in `sparse::cuda::csrmm2`, which in turn calls `cusparseSpMM`. The functionality of `cusparseSpMM`  is essentially:

```
cusparseSpMM(sparse A,dense B, dense C, float alpha, float beta):
	C = beta*C + alpha*A@B
```

We want to compute `Y = beta*T + alpha*S@D` (with `S` sparse and `T,D` dense)
When `beta` is 0 or 1, the computation goes as follows:
```
if beta == 0:   r_.zero_()
elif beta == 1: r_.copy(T)
else:           r_ = beta*T

r__ = r;
cusparseSpMM(S,D,r__, alpha, beta)
r_.copy_(r__);
return r_
```

* When `beta == 0`: 
	* `r_ = 0`
	* `Y = 0*r_ + alpha*S@D = alpha*S@D` (Correct)
* When `beta == 1`
	* `r_ = T`
	* `Y = 1*r_ + alpha*S@D = T + alpha*S@D` (Correct)
* When `beta != {0,1}`:
	* `r_ = beta*T`
	* `Y = beta*r_ + alpha*S@D = beta*beta*T + alpha*S@D` (Incorrect)
	* Multiplication by `beta` happens twice.

That whole conditional block [(L65-L73)](https://github.com/pytorch/pytorch/blob/79857534213f26dd23dd0a1f590cf666180d230f/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L65) seems redundant to me.. Is this preprocessing necessary? I would assume that `cusparseSpMM` does the full computation anyway.
It seems that removing L65-L73 and replacing all occurrences of `r_` with `t_` in the following conditional [(L75-L81)](https://github.com/pytorch/pytorch/blob/79857534213f26dd23dd0a1f590cf666180d230f/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L75) makes the function do what we want.

**Comment by ngimel** [comment]
Thanks for the great analysis @sorenrasmussenai, you corrected suggestion looks right, also, copy in line 114 https://github.com/pytorch/pytorch/blame/79857534213f26dd23dd0a1f590cf666180d230f/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L114 seems unnecessary for the case where r_ == r__. Can you submit a PR doing this, and add the corresponding test?

**Comment by sorenrasmussenai** [comment]
Turns out we need to pre-zero `r_` when `beta==0` after all. It seems that cusparse does not do that for us, which causes `TestSparse.test_mv_cuda`, `TestSparse.test_dsmm_cuda` and `TestSparse.test_bmm_cuda` to fail if it's left out.

**Comment by ngimel** [comment]
Hm, do you have a link to a failure? That looks like  a cusparse bug that we need to send to nvidia

**Comment by sorenrasmussenai** [comment]
The functions simply produce wrong results without pre-zeroing.
Performance wise it makes sense that pre-zeroing is done manually, since it may already be done in some cases.
Unfortunately, I don't have the time to investigate this further.

**Comment by sorenrasmussenai** [comment]
@ngimel I submitted a pull request: [56160](https://github.com/pytorch/pytorch/pull/56160)
Some of the tests are failing, but that looks like an unrelated problem with CircleCI not being able to locate docker images.
