### ISSUE TITLE
Include directories for C++ project have changed from 1.7 to 1.8.1?

### ISSUE THREAD

**Issue by InfiniteLife** [pytorch/pytorch#56009]
I am on Windows 10, Visual Studio. I'm trying to transfer project which used 1.7 API to 1.8.1 API.

I used to have this directories telling compiler where to look for headers:

```
.\torch\csrc\api\include
.\torch\include
```
that was enough to find these files:
```
#include <ATen/ATen.h>
#include <torch/torch.h>
#include <torch/script.h>
```
Now I need to specify these:
```
.\torch\csrc\api\include   
.\                                     // for torch/script.h
.\aten\src                             // For Aten.h, it is only here
.\build_release\aten\src               // Functions.h, Core
.\build_release                        // For c10\macros\cmake_macros.h
```

Is it supposed to be like this? Or I doing something wrong? 

cc @yf225 @glaringlee @peterjc123 @mszhanyi @skyline75489 @nbcsm @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Can you outline in a bit more detail, how your build system is configured?
Is it CMake based, i.e. something along the lines of  https://pytorch.org/cppdocs/installing.html#minimal-example

From issue description it looks like you are building pytorch locally and then trying to use headers directly from the build folder, which is not guaranteed to be backward compatible (nor how it really supposed to be used)

**Comment by kit1980** [comment]
Closing as these versions are obsolete now.
