### ISSUE TITLE
.cfloat() and .cdouble() methods

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#56014]
We currently do not have these methods to cast a real tensor to a complex tensor. At the moment, the way to do this is the more verbose (and arguably more obscure)  `.type(torch.cfloat())`.

These methods would go in line with the existing `.bool()`, `.float()`, `.half()`, etc.

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by ezyang** [comment]
Yup, let's do it.
