### ISSUE TITLE
Out variant of torch.inner incorrectly broadcasts

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#56022]
## 🐛 Bug

Per title

Currently, we directly `copy_` the result into the output tensor.
https://github.com/pytorch/pytorch/blob/d490e0120f32dcbb8b23e11eebd638b96b4b0898/aten/src/ATen/native/Linear.cpp#L644
If the output tensor can be broadcasted from result, it would generate wrong output.

## To Reproduce

```py
>>> a = torch.randn(5)
>>> b = torch.randn(5)
>>> torch.inner(a, b)
tensor(-4.2595)
>>> c = torch.randn(2)
>>> torch.inner(a, b, out=c)
tensor([-4.2595, -4.2595])
```

## Expected
```py
>>> a = torch.randn(5)
>>> b = torch.randn(5)
>>> torch.inner(a, b)
tensor(-4.2595)
>>> c = torch.randn(2)
>>> torch.inner(a, b, out=c)  # c should be resized to shape([1])
tensor([-4.2595])
```

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @rgommers

**Comment by mruberry** [comment]
I tweaked the title slightly. Thanks for filing this issue, @ejguan!

**Comment by heitorschueroff** [comment]
Thanks for reporting this bug, I'll work on a fix.

**Comment by heitorschueroff** [comment]
@imaginary-person I picked up this issue since I last touched torch.inner but it seems like @mruberry had suggested you might want to do it. If so, let me know here and I can work with you in reviewing a PR to fix this.

**Comment by imaginary-person** [comment]
Hello @heitorschueroff, I apologize for my late response!
If this bug is to be resolved ASAP, please proceed with resolving it, as I won't be able to work on it today, but would only be able to start working on it tomorrow.
Thanks!

**Comment by heitorschueroff** [comment]
> Hello @heitorschueroff, I apologize for my late response!
> If this bug is to be resolved ASAP, please proceed with resolving it, as I won't be able to work on it today, but would only be able to start working on it tomorrow.
> Thanks!

This bug is not high priority, starting tomorrow is totally fine. I'll assign it to you then and I'll work with you to review and land the PR. Thank you for helping.
