### ISSUE TITLE
error: no template named 'hash'; did you mean '::std::hash'?

### ISSUE THREAD

**Issue by rainbow520lxr** [pytorch/pytorch#56020]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mruberry** [comment]
Hey @rainbow520lxr, would you open a new issue with more context so we can understand how this error occurred? For example, can you post the code used to produce the error?
