### ISSUE TITLE
Can the model quantified by qnnpack be inferred on the x86 platform?

### ISSUE THREAD

**Issue by sgl123github** [pytorch/pytorch#56028]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
yes we can but it might not get the same numerics, since fbgemm has some restrictions and you'll find we have reduce_range=True for fbgemm: https://github.com/pytorch/pytorch/blob/master/torch/quantization/qconfig.py#L98

also please use discussion forums for questions
