### ISSUE TITLE
  RuntimeError: Exporting the operator triu to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by mathmax12** [pytorch/pytorch#56061]
## 🐛 Bug

I am trying to export a model from PyTorch to onnx and got he following issue:

![image](https://user-images.githubusercontent.com/32367611/114774719-4f04d680-9d25-11eb-843b-20e0a003bd2e.png)

## To Reproduce

1.It's my own code and hard to reproduce it here

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by Benieq** [comment]
I reproduced this problem

**Comment by spandantiwari** [comment]
This is duplicate of https://github.com/pytorch/pytorch/issues/51851. I will close this one. Let's track this enhancement request on that issue. Thanks!
