### ISSUE TITLE
No Module named torchvision.transforms

### ISSUE THREAD

**Issue by TheOracle2** [pytorch/pytorch#56091]
## Issue description

After successfully installing Torch and it's associated packages, I found this error. I am using Miniconda (if that helps) and Torch seems to be working fine. I have tried re-installing torchvision but nothing works. Please help me. 
## Code example

``` # Imports
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.trasnforms as transforms

# Creating a NN
class NN(nn.Module, input_size, num_classes):
    def __init__(self):
        super(NN, self).__init__()
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)
    
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = NN(784, 10)
x = torch.randn(64, 784)
print(model(x).shape)
 ```

## The Error
Traceback (most recent call last):
  File "c:\Users\bala006\OneDrive - St John's Anglican College\Desktop\Personal\ML Stuff\PyTorhc\Random\NN Example.py", line 8, in <module>
    import torchvision.trasnforms as transforms
ModuleNotFoundError: No module named 'torchvision.trasnforms'
## System Info

- PyTorch 
- I installed pytorch using Pip
- OS: Windows 10
- PyTorch version: 1.8.1
- Python version: 3.8

All help appreciated. Thanks for helping a newbie!
```

**Comment by imaginary-person** [comment]
https://discuss.pytorch.org/t/modulenotfounderror-no-module-named-torchvision-transform-despite-being-installed/99136/5

**Comment by TheOracle2** [comment]
Hi mate, 
I've had a look but nothing works for me. I've tried reinstalling it even but to no avail...

**Comment by imaginary-person** [comment]
There's a typo in your code

`torchvision.trasnforms` should be `torchvision.transforms`.

**Comment by TheOracle2** [comment]
Answer. Reinstall Torchvision. Also, the answer is stupid. Really Stupid. Mega stupid. Have fun finding it. :). 

> There's a typo in your code
> 
> `torchvision.trasnforms` should be `torchvision.transforms`.

**Comment by mruberry** [comment]
Looks like this issue has been resolved; thanks for noticing the typo, @imaginary-person.

**Comment by Golden-direction** [comment]
我也是这个错误，我是conda环境，然后我安装了pip install torchtools.transforms，因为我用conda命令安装不上。但接着它又报了个错：ModuleNotFoundError: No module named 'torchtools.transforms'

**Comment by perva01** [comment]
windows下找到文件，
C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\basicsr\data\degradations.py
修改这行就行from torchvision.transforms._functional_tensor import rgb_to_grayscale #torchvision.transforms._functional_tensor
