### ISSUE TITLE
Feature request: Zoneout LSTM

### ISSUE THREAD

**Issue by Smerity** [pytorch/pytorch#561]
[Zoneout](https://arxiv.org/abs/1606.01305) is one method to perform recurrent dropout on the hidden state of an RNN and has been shown to work quite well on a variety of cases.

Implementing a zoneout LSTM, such as in [Chainer's implementation](https://github.com/pfnet/chainer/blob/master/chainer/links/connection/zoneoutlstm.py), requires reasonably trivial modifications to implement and would be a good early project for someone new to contributing to PyTorch. If no-one has started by the point I have free time I'll look at doing it myself :)

Note: other forms of recurrent dropout are also worth looking at but I feel zoneout is likely the most broadly applicable version.

**Comment by c0nn3r** [comment]
I'll look into this.

**Comment by ethancaballero** [comment]
@Smerity Did you ever finish Zoneout or Variational Dropout implementation?

**Comment by tomekkorbak** [comment]
any luck anyone? @Smerity @c0nn3r

**Comment by tomekkorbak** [comment]
Implemented in #4838 
cc @Smerity @c0nn3r

**Comment by soumith** [comment]
the method is a bit more niche, and we were waiting for it to pick up in popularity.
Considering it didn't, I'm going to close this Feature Request as `wontfix`, we dont want to increase the maintenance surface of core,
