### ISSUE TITLE
Samplers require only integers in example indices after Tensor+Variable merge

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5612]
[This line](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L120) used to read `batch.append(idx)` before the merge, and now reads `batch.append(int(idx))`

It breaks custom samplers that embed additional transformation parameters in the sampled "example index". In my case, an "example index" was a tuple containing a true example index, rescaling, flip parameters, object proposal indices etc. Then these parameters are applied to images and object proposals.

@colesbury

**Comment by fmassa** [comment]
One of the things that we can do is to add a `.tolist()` in [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L90). There might be other places where we might need a similar change though.

**Comment by vadimkantorov** [comment]
Could you expand? If I understand right, `tolist()` wouldn't cure the "example index" tuples not convertible to int.

**Comment by fmassa** [comment]
I was thinking that the `int(idx)` was added because, with tensors and variables being merged, indexing a 1d tensor now gives a 0d tensor (as done in the place I mentioned) and not a python number anymore.

And I have the impression that the `int(idx)` was added to fix a failing test somewhere. But now given that scalars that don't require grad can be automatically cast to `int`, maybe that cast is not necessary anymore?

**Comment by colesbury** [comment]
@fmassa, yes it was to fix a performance issue: Tensors (including 0d) are sent across processes differently from Python numbers. Python numbers are simply encode and written to the Queue/Pipe, which is very quick. For tensors, we `mmap` a shared memory page, copy the data to the shared memory, and then encode a handle to the Queue/Pipe. This has much higher overhead than the Python number encoding.

**Comment by colesbury** [comment]
@vadimkantorov I guess we can remove the `int()` call. We need to make sure that Sampler's iterators return Python numbers and not 0d tensors

**Comment by apaszke** [comment]
@colesbury can't we do this conditionally for tensors, and otherwise return the objects as they are?

**Comment by vadimkantorov** [comment]
fixing is at the moment in https://github.com/pytorch/pytorch/pull/6105

**Comment by vadimkantorov** [comment]
fixed in https://github.com/pytorch/pytorch/pull/8958
