### ISSUE TITLE
support_out for gradient operator.

### ISSUE THREAD

**Issue by iramazanli** [pytorch/pytorch#56131]
Currently gradient operator does not support out extension. It would be helpful to have this feature implemented.

**Comment by vadimkantorov** [comment]
This would also be useful for inplace gradient computation also in Reversible Net context @albanD

**Comment by albanD** [comment]
This is a duplicate of https://github.com/pytorch/pytorch/issues/29378
There is quite a bit of discussion there about why this is hard to do

Feel free to continue the discussion there.
