### ISSUE TITLE
how to RegisterPass for torch.jit.trace() 

### ISSUE THREAD

**Issue by Andrechang** [pytorch/pytorch#56149]
## ❓ Questions and Help

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

is there are new way to create a custom transformation pass in torchscript with torch1.8.0 ?

just like here: pytorch_compiler_tutorial/register.cpp at master · bwasti/pytorch_compiler_tutorial · GitHub 2

torch.jit.trace() doesnt call: RegisterPass pass anymore

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi @Andrechang ,

Could you describe your use case a bit more? `registerPass` is no longer supported, but we may have better options to offer if you can tell us a bit more about your exact use case. thanks.

**Comment by gmagogsfm** [comment]
AI on @eellison to find out another the other mechanism to register custom passes used by intel.

**Comment by eellison** [comment]
If you're asking about the tvm extension, it is a deprecated project and no longer supported.

**Comment by Andrechang** [comment]
isn't there anyway to run a custom graph pass with torchscript?

**Comment by Andrechang** [comment]
found solution here:
https://lernapparat.de/jit-runtime-overview/
