### ISSUE TITLE
torch.distributed.broadcast_object_list doesn't broadcast custom class object

### ISSUE THREAD

**Issue by eldarkurtic** [pytorch/pytorch#56142]
## 🐛 Bug

`torch.distributed.broadcast_object_list` seems like it is not broadcasting custom defined class objects.

## To Reproduce

```python
import os
import torch

class Dummy:
    def __init__(self):
        self.test_int = torch.distributed.get_rank()

def main():
    dummy = Dummy()

    print("Before broadcasting...")
    print(f"[RANK {torch.distributed.get_rank()}] test_int = {dummy.test_int}")

    torch.distributed.broadcast_object_list([dummy], src=0)

    print("After broadcasting...")
    print(f"[RANK {torch.distributed.get_rank()}] test_int = {dummy.test_int}")

if __name__ == "__main__":
    torch.distributed.init_process_group(backend='gloo', init_method='env://')
    main()
```

This example prints the following:
```shell
Before broadcasting...
[RANK 0] test_int = 0
Before broadcasting...
[RANK 1] test_int = 1

After broadcasting...
[RANK 0] test_int = 0
After broadcasting...
[RANK 1] test_int = 1
```
## Expected behavior

To see `[RANK 1] test_int = 0` after broadcasting call.

## Environment

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.13.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105

Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[conda] numpy                     1.19.4           py38hf0fd68c_1    conda-forge
[conda] torch                     1.8.1+cu111              pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by zhaojuanmao** [comment]
you are printing local dummy() object, not the object broadcast from rank 0. 

Try to revise codes like this: 

     if dist.get_rank() == 0:
          objects = [dummy()] 
     else:
         objects = [None]
     torch.distributed.broadcast_object_list(objects, src=0)

     print(objects)

**Comment by eldarkurtic** [comment]
Alright, thanks for the update. I've assumed that objects from `src` rank will populate local objects if called without creating new `objects = [None]`:
```python
torch.distributed.broadcast_object_list([dummy], src=0)
```
(according to this comment here: https://github.com/pytorch/pytorch/pull/43887#discussion_r480355409)

**Comment by lxysl** [comment]
I have the same issue with you. The key is to create a list variable before `dist.broadcast_object_list()` instead of directly passing in a list. This problem is kind of confusing and takes me two days to figure it out.
