### ISSUE TITLE
grad_fn disappear after passing torch.nn.Conv2d with in_channels of 1, on Apple M1

### ISSUE THREAD

**Issue by baowenxuan** [pytorch/pytorch#56145]
## 🐛 Bug

When we feed an input of shape `(batch_size, 1, H, W)` with `requires_grad=True` to `nn.Conv2d`, the output will have `requires_grad=False`. But when the `in_channels` is not 1, the output will be fine. 

## To Reproduce

```
import torch
x1 = torch.randn(1, 1, 3, 3, requires_grad=True)
conv1 = torch.nn.Conv2d(1, 1, 3)
y1 = conv1(x1)
print(y1, y1.requires_grad)
# tensor([[[[0.3465]]]]) False

x2 = torch.randn(1, 2, 3, 3, requires_grad=True)
conv2 = torch.nn.Conv2d(2, 1, 3)
y2 = conv2(x2)
print(y2, y2.requires_grad)
# tensor([[[[0.7109]]]], grad_fn=<ThnnConv2DBackward>) True
```

## Expected behavior

The output should also have `requires_grad=True`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.2 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[pip3] torchvision==0.2.2
[conda] numpy                     1.20.1           py38h9e6c65a_0    conda-forge
[conda] pytorch                   1.8.0           cpu_py38h179404b_0    conda-forge
[conda] torchvision               0.2.2                      py_3    pytorch

## Additional context

I believe this problem is related to #54136, and in #55804 it seems like you are fixing it. So please also test this. 

cc @malfet @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by malfet** [comment]
It happens because only on ARM `use_cpu_depthwise3x3_winograd ` can return true...
https://github.com/pytorch/pytorch/blob/1b87274460a24d20ce1c600adc0dc7e2598285bf/aten/src/ATen/native/Convolution.cpp#L140

**Comment by malfet** [comment]
Following obviously resolves the issue, but I'm not sure, if this is the right solution:
```
diff --git a/aten/src/ATen/native/Convolution.cpp b/aten/src/ATen/native/Convolution.cpp
index b77dc3ca69..3608ba1124 100644
--- a/aten/src/ATen/native/Convolution.cpp
+++ b/aten/src/ATen/native/Convolution.cpp
@@ -161,6 +161,7 @@ auto ConvParams::use_cpu_depthwise3x3_winograd(
              (bias.scalar_type() == at::kFloat))) &&
          !is_strided() &&
          !is_dilated() &&
+         !input.requires_grad() &&
          !transposed;
 #else
   return false;
```
