### ISSUE TITLE
Tracer vs eager mode difference on tensor.shape

### ISSUE THREAD

**Issue by shubhambhokare1** [pytorch/pytorch#56162]
## 🐛 Bug

In eager mode, shape values obtained from tensor.shape are python int, so there are treated as different values. However in tracing both are traced as tensors, and then they share same memory. This causes mismatch in final outputs

## To Reproduce

```
# Tracer vs Eager mode difference in tensor.shape
import torch
import onnxruntime

class Model(torch.nn.Module):
    def forward(self, hidden_states):
        batch_size, seq_length = hidden_states.shape[:2]
        real_seq_length = seq_length
        real_seq_length += 2                                            => real_seq_length and seq_legth should have different values
        return real_seq_length + seq_length


# Call export

# hidden_states is tensor of rank 2
hidden_states = torch.randn(2, 3, 5)
model = Model()

import io
onnx_io = io.BytesIO()
tracemodel = torch.jit.trace(model, (hidden_states, ))
torch.onnx.export(model, (hidden_states, ), onnx_io, verbose=True)

# Call onnxruntime runtime and compare outputs on dynamic inputs
ort_session = onnxruntime.InferenceSession(onnx_io.getvalue())

print(model(hidden_states))
print(tracemodel(hidden_states))
print(ort_session.run(None, {
                                ort_session.get_inputs()[0].name: hidden_states.numpy()
                            }))
```

## Expected behavior

**Output in eager mode**
8 (real_seq_length(=3) + seq_length(=5))

**Output in tracing mode**
Should be 8 but is 10 (real_seq_length(=5) + seq_length(=5)) as tensors share same memory

**Graph output on exporting ONNX graph**
```
graph(%0 : Float(2, 3, 5, strides=[15, 5, 1], requires_grad=0, device=cpu)):
  %1 : Long(3, strides=[1], device=cpu) = onnx::Shape(%0)
  %2 : Long(device=cpu) = onnx::Constant[value={1}]()
  %3 : Long(device=cpu) = onnx::Gather[axis=0](%1, %2) # test/onnx/test_m.py:38:0
  %4 : Long(requires_grad=0, device=cpu) = onnx::Constant[value={2}]()
  %5 : Long(requires_grad=0, device=cpu) = onnx::Add(%3, %4) # test/onnx/test_m.py:40:0
  %6 : Long(requires_grad=0, device=cpu) = onnx::Add(%5, %5) # test/onnx/test_m.py:41:0   ===> %5 proves that both seq_length and real_seq_length have same values/memory
  return (%6)
```

cc @gmagogsfm @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by gmagogsfm** [comment]
Thanks for reporting this issue, I think you analysis is correct. Converting and treating shape (int) to Tensor does have unintended effect.

Here is IR from `jit.trace`, it shows that real_seq_length and seq_length are treated as same value indeed:
```
graph(%self : __torch__.Model,
      %hidden_states : Float(2, 3, 5, strides=[15, 5, 1], requires_grad=0, device=cpu)):
  %7 : int = prim::Constant[value=1]() # trace_shape.py:6:0
  %8 : int = aten::size(%hidden_states, %7) # trace_shape.py:6:0
  %seq_length.1 : Long(device=cpu) = prim::NumToTensor(%8)
  %13 : Long(requires_grad=0, device=cpu) = prim::Constant[value={2}]() # trace_shape.py:8:0
  %14 : int = prim::Constant[value=1]() # trace_shape.py:8:0
  %seq_length : Long(requires_grad=0, device=cpu) = aten::add_(%seq_length.1, %13, %14) # trace_shape.py:8:0
  %16 : int = prim::Constant[value=1]() # trace_shape.py:9:0
  %17 : Long(requires_grad=0, device=cpu) = aten::add(%seq_length, %seq_length, %16) # trace_shape.py:9:0
  return (%17)
```

@jamesr66a Rumor says you are expert on `jit.trace`, any suggestions here?

**Comment by gmagogsfm** [comment]
Some possible action items:

1. Check why `jit.trace` sanity check doesn't detect this error.
2. Maybe we can do some post-processing after trace to rewrite patterns like %7 and %8 in my example from using TensorType to int type and getting rid of inplace updates.

If you need to be unblocked now, the immediate action is to not use augment assignment

`a += 2` -> `a = a + 2`

**Comment by jamesr66a** [comment]
> @jamesr66a Rumor says you are expert on jit.trace

oh no

> original issue

I think the tracer is stuck between a rock and a hard place in terms of capturing networks with shape expressions at all v.s. capturing corner cases like this correctly. I'm not sure if there's anything fundamental we can do in the tracer to alleviate this. The workaround @gmagogsfm proposed seems reasonable.
