### ISSUE TITLE
Move pad_sequence function to C++

### ISSUE THREAD

**Issue by sunshineatnoon** [pytorch/pytorch#56229]
## 🚀 Feature
Is it possible to get a C++ version of the `torch.nn.utils.pad_sequence` function?

## Motivation

The current `torch.nn.utils.pad_sequence`  function seems implemented by [Python](https://pytorch.org/docs/master/_modules/torch/nn/utils/rnn.html#pad_sequence) and is slow when applied on a large number of sequences, e.g, 0.06s for 4096 sequences.

## Pitch

Move the function to C++

## Alternatives
None

## Additional context
None

cc @VitalyFedyunin @ngimel

**Comment by eqy** [comment]
I'm curious what the best solution is considering there is C++ API version of [pad_sequence](https://github.com/pytorch/pytorch/blob/5044d9dc517dd3ad547334f26d102a9d454b8f59/torch/csrc/api/include/torch/nn/utils/rnn.h#L279) that likely removes much of the Python overhead? Is it still to move everything into a native function?

**Comment by venkateshtata** [comment]
Can I work on this as my first issue ? Any suggestions on where to start would be great.

**Comment by thomasjpfan** [comment]
Resolved in https://github.com/pytorch/pytorch/pull/57868
