### ISSUE TITLE
On CPU, addmm_() allows resizing the tensor it operates on

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#56233]
## 🐛 Bug

On CPU, `addmm_()` allows resizing the tensor it operates on.
The CUDA implementation doesn't exhibit this behavior.

## To Reproduce

1. Run the following code -
```
import torch
from torch.testing._internal.common_utils import make_tensor
a = make_tensor((1, ), device='cpu', dtype=torch.float32) 
b = make_tensor((2, 2), device='cpu', dtype=torch.float32) 
c = make_tensor((2, 3), device='cpu', dtype=torch.float32)
a.addmm_(b, c) 
```

2.  The following warning is displayed, but the operation succeeds -

> __main__:1: UserWarning: An output with one or more elements was resized since it had shape [1], which does not match the required output shape [2, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  pytorch/aten/src/ATen/native/Resize.cpp:23.)

## Expected behavior

A RuntimeError should be thrown, as is done by the CUDA implementation.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: tensors must be 2-D

## Environment

PyTorch version: 1.9.0a0+gitbd3c63a
Is debug build: False
CUDA used to build PyTorch: 11.2

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100S-PCIE-32GB
GPU 1: Tesla V100S-PCIE-32GB

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0a0+gitbd3c63a

## Additional context

This bug was discovered by the code added in #55771.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @VitalyFedyunin

**Comment by ngimel** [comment]
Ideally, addmm should be ported to structured, and the necessary size check added (see #55746), but adding a check to cpu implementation is also acceptable.

**Comment by imaginary-person** [comment]
Thanks, I'll try to port `addmm` to structured later today.

**Comment by imaginary-person** [comment]
Hello @ngimel, `addmm.out` also has the following dispatch entries in `native_functions.yaml`:

https://github.com/pytorch/pytorch/blob/7d1755915245d4260fc28f4615d21f0f9a754e0a/aten/src/ATen/native/native_functions.yaml#L4108-L4110

`addmm_` & `addmm` also have corresponding entries.

Please advise if it's possible to port `addmm` for CPU & CUDA to structured without porting these. Thanks!

**Comment by imaginary-person** [comment]
Should both CUDA & CPU implementations allow resizing the input tensor if it has 0 elements, or should it never be resized?
The warning says at `pytorch/aten/src/ATen/native/Resize.cpp:23` states `in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0)`.

Thanks!

**Comment by mruberry** [comment]
We do allow resizing out= tensors if they have zero elements, but I don't know if we considered inplace operations on tensors with zero elements. 

Are there inplace operations which are valid (and would resize the input tensor) if the input tensor has zero elements?

**Comment by ngimel** [comment]
We shouldn't allow resizing input tensor for inplace operations.

**Comment by imaginary-person** [comment]
@mruberry, I had thought that for `a.addmm_(b, c)`, the input tensor `a` with zero elements would be broadcastable with `b x c`, so the operation would be valid.

For instance, `a = torch.tensor([], dtype=torch.float64, device='cpu')`
`a.dim()` is 1 but `a.numel()` is 0.

**Comment by ngimel** [comment]
For other inplace ops, we don't resize `self` with zero elements.

**Comment by imaginary-person** [comment]
Thanks for the confirmation, @ngimel!
BTW, I'm having trouble porting `addmm` to structured, as the CPU implementation is asserting.
Can we fix this issue with #56452 for now? (Although this fix would be removed whenever `addmm` would be ported).
Thanks!

**Comment by ngimel** [comment]
Yes, fixing with #56452 is fine, can you take it out of draft so that I can land it?

**Comment by imaginary-person** [comment]
Thanks again, @ngimel!
I noticed that you were able to mark the PR as 'ready for review' and import it, but surprisingly, GitHub doesn't show that FB internal tests are running for it.

**Comment by imaginary-person** [comment]
Closing the issue, as #56452 has been merged.

**Comment by mruberry** [comment]
Nice work, @imaginary-person ;)

**Comment by imaginary-person** [comment]
Thanks, @mruberry! Couldn't port `addmm` to structured, though. 😞

**Comment by mruberry** [comment]
Let's celebrate the things we have.

How are things going, by the way, @imaginary-person ? Are there some systemic issues you've noticed? Is finding issues to work on easy enough? Are the skills required to fix an issue and the value of doing so clear? What are your recommendations, if any, for how we could make it easier for community members to engage?

**Comment by imaginary-person** [comment]
I think that on GitHub, PyTorch has the most engaging & the most helpful maintainers, and that community-engagement couldn't have been any better.

Thanks to you, finding issues to work on has been easy for me, and so has been working on them, since you provide all the necessary background info beforehand, and help me out whenever I'm stuck. :)

The only suggestion I could come up with is to consider having starter issues on JIT, FX, and Distributed more frequently. I might be wrong, but I think I've only seen one starter issue each on JIT & Distributed in the last 2 months.

Thank you, I'll submit a request to join the PyTorch Slack community.

**Comment by mruberry** [comment]
> I think that on GitHub, PyTorch has the most engaging & the most helpful maintainers, and that community-engagement couldn't have been any better.
> 
> Thanks to you, finding issues to work on has been easy for me, and so has been working on them, since you provide all the necessary background info beforehand, and help me out whenever I'm stuck. :)

That's great to hear! Keep letting us know what we can do to make the work compelling.
 
> The only suggestion I could come up with is to consider having starter issues on JIT, FX, and Distributed more frequently. I might be wrong, but I think I've only seen one starter issue each on JIT & Distributed in the last 2 months.

Thank you for this suggestion:

cc @jamesr66a @Chillee @suo @pritamdamania87 - maybe something to consider?

> Thank you, I'll submit a request to join the PyTorch Slack community.

Cool!

**Comment by suo** [comment]
Excellent idea! A few of us (@SplitInfinity and @gmagogsfm come to mind) have been discussing the exact same thing. We have quite a few "module: bootcamp" [issues](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+bootcamp%22+label%3A%22oncall%3A+jit%22) that could easily be made into good starter issues!

**Comment by pritamdamania87** [comment]
> The only suggestion I could come up with is to consider having starter issues on JIT, FX, and Distributed more frequently. I might be wrong, but I think I've only seen one starter issue each on JIT & Distributed in the last 2 months.

We do have a bunch of starter issues for Distributed [here](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3Apt_distributed_rampup+) and [here](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+bootcamp%22+label%3A%22oncall%3A+distributed%22).
