### ISSUE TITLE
Inconsistent naming convention in torch/nn/modules/module.py

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/pytorch#56243]
Some methods in [torch/nn/modules/module.py][1] that change `nn.Module` in-place **end with an underscore**, e.g.
https://github.com/pytorch/pytorch/blob/b405e2ce126d28e8f615c3f35d456af30c43fe9c/torch/nn/modules/module.py#L1614

while other methods that change ``nn.Module`` in-place **DO NOT** follow the above convention, e.g.,
https://github.com/pytorch/pytorch/blob/b405e2ce126d28e8f615c3f35d456af30c43fe9c/torch/nn/modules/module.py#L716

https://github.com/pytorch/pytorch/blob/b405e2ce126d28e8f615c3f35d456af30c43fe9c/torch/nn/modules/module.py#L652

https://github.com/pytorch/pytorch/blob/b405e2ce126d28e8f615c3f35d456af30c43fe9c/torch/nn/modules/module.py#L671

[1]: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py

cc @ezyang @gchanan @brianjo @mruberry @albanD @jbschlosser

**Comment by csukuangfj** [comment]
Also, some methods leave a note saying they modify the object in-place, while others don't.
E.g.,

https://github.com/pytorch/pytorch/blob/b405e2ce126d28e8f615c3f35d456af30c43fe9c/torch/nn/modules/module.py#L740-L741

**Comment by jbschlosser** [comment]
This is true and unfortunate. Since it would be very BC-breaking to rename these functions now, we'd accept a PR adding a consistent note in the docs for all mutating functions.
