### ISSUE TITLE
Mark Windows CI jobs that gather coverage with 'coverage' in their names

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#56264]
Currently, any sharded windows test in CI gathers coverage, but this is not made clear anywhere except in the code [here](https://github.com/pytorch/pytorch/blob/6332fd62552915f3c6c2be34b0b56b46fb3eafb8/.jenkins/pytorch/win-test.sh#L64).

Proposal:
1. The windows tests running coverage should be marked with `coverage` in their CI job name.
2. Full Windows coverage should be measured once. This might already be the case--I have not verified that it isn't.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
yup. i think marking one CI job as coverage, and export PYTORCH_COLLECT_COVERAGE only when test job name has `coverage` in it similar to the linux side sounds like a good idea.

**Comment by janeyx99** [comment]
We stopped running coverage on CI, this is no logner relevant
