### ISSUE TITLE
tensor.transpose and tensor.T should have "see also" references to each other.

### ISSUE THREAD

**Issue by yoderj** [pytorch/pytorch#56267]
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.transpose.html
and
https://pytorch.org/docs/stable/generated/torch.t.html
should have "see also" references to each other.

I'm willing to make a pull request if the community supports this idea.

cc @brianjo @mruberry

**Comment by ezyang** [comment]
SGTM

**Comment by yoderj** [comment]
Just an update: This is still on my radar.  I've done some preliminary reading of the source code for PyTorch and I think I have an idea what the edits I will make will be.  I expect to make the edits some time in the next two weeks.

**Comment by aflah02** [comment]
@yoderj Are you still working on this?

**Comment by mruberry** [comment]
@aflah02 You can submit a PR if you like, @aflah02. Our contribution guide doesn't allow "reserving" issues

**Comment by aflah02** [comment]
thanks @mruberry
