### ISSUE TITLE
AttributeError: 'Variable' object has no attribute 'MM'

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#5628]
- OS: Ubuntu: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)
- PyTorch version: 0.4.0a0+9ebfece
- How you installed PyTorch (conda, pip, source): Source
- Python version: Python 2.7
- CUDA/cuDNN version: Cuda 9, cuDNN v7
- GPU models and configuration: Tesla K80        
- GCC version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

A test script for reproducing the error message:

```
import torch
import torch.legacy.nn as nn
import torchvision
#from torch.legacy.nn import MM

C, H, W = 3, 64, 64
input = torch.randn(C, H, W)
output = torch.randn(C, C)

C, H, W = input.size(0), input.size(1), input.size(2)
x_flat = input.view(C, H * W)
output = output.resize_(C, C)
print(x_flat.t().type())
print(output.type())
output = output.MM(x_flat, x_flat.t())

#https://github.com/pytorch/pytorch/blob/45524ec33ce1bf75ece04d4f6eb939ba0c9469e9/torch/legacy/nn/MM.py
```

The error message: 

```
torch.FloatTensor
torch.FloatTensor
Traceback (most recent call last):
  File "t1.py", line 15, in <module>
    output = output.MM(x_flat, x_flat.t())
AttributeError: 'Variable' object has no attribute 'MM'
```

Am I doing something wrong here? Or did I find a bug? Everything I've tried results in the same error message.

**Comment by SsnL** [comment]
Why should variable has `MM`?

**Comment by ProGamerGov** [comment]
I think I may have confused the uppercase `MM` with the lowercase `mm`.

**Comment by ProGamerGov** [comment]
@SsnL I think I was confusing the uppercase `MM` with the lowercase `mm`.

     

I was trying to replicate this code which works in Lua with Torch7: 

` self.output:mm(x_flat, x_flat:t())`

But it seems that I get an error message: 

`self.output = self.output.mm(x_flat, x_flat.t())
`
```
self.output = self.output.mm(x_flat, x_flat.t())
TypeError: mm() takes 1 positional argument but 2 were given
```

**Comment by SsnL** [comment]
What does `self.output:mm(x_flat, x_flat:t())` do? `mm` should just to matrix multiplication between two matrices..

**Comment by ProGamerGov** [comment]
@SsnL 

https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchmmres-mat1-mat2

Both `torch.mm(M, x, y)`, and `M:mm(x, y)`, put the result in M. 

So I guess that: `self.output = torch.mm(x_flat, x_flat.t())` will work the same way?

**Comment by SsnL** [comment]
or use out= http://pytorch.org/docs/master/torch.html#torch.mm

**Comment by ProGamerGov** [comment]
@SsnL 

Trying to replicate: 

`  self.gradInput:resize(C, H * W):mm(gradOutput, x_flat)`

With: 

```
self.gradInput.resize_(C, H * W).mm(gradOutput, x_flat)
```

Or:

```
self.gradInput.resize_(C, H * W)

self.gradInput = mm(gradOutput, x_flat, out=self.gradInput)
```

Results in either:

```
    self.gradInput.resize_(C, H * W).mm(gradOutput, x_flat)
TypeError: mm() takes 1 positional argument but 2 were given
```

Or: 


```
    self.gradInput = torch.mm(gradOutput, x_flat) #, out=self.gradInput
RuntimeError: matrices expected, got 3D, 2D tensors at /home/ubuntu/pytorch/aten/src/TH/generic/THTensorMath.c:1944
```

The latter of which I can't seem to figure out how to solve.

**Comment by SsnL** [comment]
Either your `gradOutput` or your `x_flat` isn't a 2D matrix.

**Comment by ProGamerGov** [comment]
@SsnL I followed my `gradOutput` variable though all it's changes, and I discovered that I had made a typo/wrote the wrong variable name in one my steps. I then added a correction step to compensate for the mistaken variable, and that correction step caused `gradOutput` to change to a 3D matrix.

**Comment by ProGamerGov** [comment]
@SsnL Another quick question, it seems that I am having issues with the legacy lbfgs function and my feval function.

Lua:    ` return loss, grad:view(grad:nElement())`

Python: `return loss, grad.view(grad.nelement())`

My Python translation results in this error: 

```
    x, losses = optim.lbfgs(feval, img, optim_state)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/optim/lbfgs.py", line 197, in lbfgs
    x.add_(t, d)
RuntimeError: The expanded size of the tensor (64) must match the existing size (12288) at non-singleton dimension 2
```

Even just running,  `grad = grad.view(grad.nelement()` will get the error: 

```
RuntimeError: The expanded size of the tensor (64) must match the existing size (12288) at non-singleton dimension 2
```

Is there some difference between Torch7 and PyTorch here that I am missing?

**Comment by soumith** [comment]
@ProGamerGov pytorch has numpy-style broadcasting, while Lua doesn't. Maybe that's the issue you are running into.
