### ISSUE TITLE
Update docs for torch.triangular_solve to describe rectangular matrix behavior

### ISSUE THREAD

**Issue by trenta3** [pytorch/pytorch#56327]
## 🚀 Feature
Implement solving the system Ra = b where R is a rectangular upper triangular matrix.

## Motivation
Currently torch.triangular_solve called with nonsquare triangular matrices raises an error because the matrix is not square.
Trying to complete the matrix by filling entries with zeros to obtain a square triangular matrix does not help, because when the square matrix is singular, torch either raises an error (on CPU) or returns a vector with nans (on CUDA) [see #56326].

## Edit: Alternatives
I just realized that one can complete the diagonal of the expanded matrix with ones to make it invertible and then ignore the solutions in the resulting places.

Still it would be useful to implement it for non-square matrices because there are cases where one has a very disproportionate matrix and so much memory to hold the completed square matrix may not be available, nor the time needed for a full pass on the bigger matrix.

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by IvanYashchuk** [comment]
Hey @trenta3! Thank you for filing the feature request. Do you have a specific application for this kind of solver?

The linear algebra part of PyTorch can be thought of as a standard library and not every linear algebra-related operation fits there. Most of the operations are provided as higher-level interfaces to mathematical libraries implementing LAPACK API, for CUDA inputs it means that cuSOLVER or MAGMA libraries need to have the required functionality.

I'm not aware of specialized solvers for upper trapezoidal matrices. You could use decompositions that can be applied to general matrices: QR, SVD.

**Comment by nikitaved** [comment]
Hi, @trenta3 ! If your input matrix `R` is `m x n` and `m <= n`, let `k = min(m, n)`, then one of the solutions, if `R` does not have zeroes on the diagonal, is
```
x[:k] = torch.triangular_solve(b[:k], R[:k, :k])
x[k:] = 0
```
If `m > n`, then you can do the same, but you also have to check whether `b in range(R) or Rx == b` otherwise the system does not solutions.

**Comment by mruberry** [comment]
I also wonder if this is a case where the workaround is preferable and clearer to the user?

**Comment by trenta3** [comment]
Hi, thanks for the fast replies.
After a bit of thinking I agree that it is preferable to not implement the proposed change, but just let the user deal with extracting a submatrix and use it to solve the system.

I think however that in the documentation for this functionality should be included the fact that it can only be used on square invertible matrices and that for triangular matrix one can select an invertible submatrix.

**Comment by mruberry** [comment]
@Lezcano, who just updated our linalg documentation, what are your thoughts?

**Comment by Lezcano** [comment]
I strongly support the idea of adding bits and pieces of useful information in the notes section of the linear algebra functions. How to use functions that are designed for square matrices in the non-square case is a fantastic example of this.

We can add this once we go over all the linalg functions that we have in the `torch.` namespace. This probably would not be able to make it into 1.9, though.

**Comment by mruberry** [comment]
I modified the title of this issue to better reflect the docs update suggestion. Thanks @trenta3!
