### ISSUE TITLE
Client and Server fail on mixed endian machines

### ISSUE THREAD

**Issue by seelam** [pytorch/pytorch#5633]
We are trying to use use Pytorch master on a big endian machine and the workers on a little endian machines. When both master and workers are on the same platform, the below program works fine but it fails when they are on different platforms. We think there is a bug in the `dataChannel-->init()` method. 

Below is a sample master and worker program to reproduce the problem.

master.py

```
#!/usr/bin/env python3
import os
import torch
import torch.distributed as dist
dist.init_process_group(backend='tcp', rank=0, world_size=2)
print('Hello from process {} (out of {})!'.format(dist.get_rank(), dist.get_world_size()))
tensor=torch.IntTensor([0x1234])
print('Send ', tensor)
dist.send(tensor=tensor, dst=1)
```

worker.py

```
#!/usr/bin/env python3
import os
import torch
import torch.distributed as dist
dist.init_process_group(backend='tcp', rank=1, world_size=2)
print('Hello from process {} (out of {})!'.format(dist.get_rank(), dist.get_world_size()))
tensor=torch.IntTensor([0])
dist.recv(tensor=tensor, src=0)
print('Receive ', tensor)
```

Here is the error:

```
Traceback (most recent call last):
  File "./run-master.py", line 5, in <module>
    dist.init_process_group(backend='tcp', rank=0, world_size=2)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/distributed/__init__.py", line 95, in init_process_group
    group_name, rank)
RuntimeError: std::bad_alloc at /home/ubuntu/pytorch/torch/lib/THD/process_group/General.cpp:17
```

Trace of the General.cpp points to this code:
https://github.com/pytorch/pytorch/blob/master/torch/lib/THD/process_group/General.cpp#L17

Is this expected to work? Appreciate any pointers.

**Comment by apaszke** [comment]
No, our distributed modules assume fixed endianness in all machines. I don't think we'll be fixing that any time soon.

**Comment by pietern** [comment]
No plans to support mixed endianness indeed. Closing the issue.
