### ISSUE TITLE
Could you make activation parameter of nn.layer 

### ISSUE THREAD

**Issue by epsilon-deltta** [pytorch/pytorch#56345]
Now 
![image](https://user-images.githubusercontent.com/45354219/115166054-25b0c580-a0ec-11eb-9990-c5dbaced6f44.png)
how about changing like this
![image](https://user-images.githubusercontent.com/45354219/115166079-42e59400-a0ec-11eb-8663-8e4753acb544.png)

compared with keras 
![image](https://user-images.githubusercontent.com/45354219/115166140-77595000-a0ec-11eb-9da7-977af35eed12.png)

to add activation function is bothersome 

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Thanks for the suggestion @epsilon-deltta! I don't think the high update and maintenance costs required for this different syntax are worth it. It's simple enough to create a helper module / function that e.g. defines a `nn.Linear` module along with the appropriate activation module.

**Comment by epsilon-deltta** [comment]
thanks
