### ISSUE TITLE
Incorrect doc about the dtype for torch.randint

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/pytorch#56347]
See https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint

It says the following in the `note`:

https://github.com/pytorch/pytorch/blob/ce05b7a3244ae7a61e989c9cd4eabf6d668ecbb0/torch/_torch_docs.py#L7057-L7059

But it uses the following to generate the documentation for `dtype` **automatically**
https://github.com/pytorch/pytorch/blob/ce05b7a3244ae7a61e989c9cd4eabf6d668ecbb0/torch/_torch_docs.py#L7069

which gives
>dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).

It contradicts what the **note** describes.

cc @brianjo @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @csukuangfj! We would definitely accept a PR fixing this.

**Comment by bdhirsh** [comment]
reserving for onboarding
