### ISSUE TITLE
Python API in a machine consumable form

### ISSUE THREAD

**Issue by fridex** [pytorch/pytorch#56366]
## ❓ Questions and Help

I would like to ask if there is a way to consume Python API in a machine-readable way. I see Python API available in docs:

https://pytorch.org/docs/stable/torch.html

Is there a possibility to get all the supported symbols for specific PyTorch releases?

**Comment by skyline75489** [comment]
If you really want one, check this out: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml

**Comment by bdhirsh** [comment]
Hi @fridex, this question is probably more suitable for the [pytorch forum](https://discuss.pytorch.org) so I'm going to go ahead and close this issue.

That say, @skyline75489 is right; the Python API is generated directly off of [native_functions.yaml](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml).

If you build pytorch locally, you'll see the Python API files are generated in `torch/csrc/autograd/generated/` (take a look at any files that start with `python_`, e.g. `torch/csrc/autograd/generated/python_torch_functions.cpp`.

If you're curious, the Codegen that creates those files lives [here](https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_python_functions.py):
