### ISSUE TITLE
nn.Module.__call__ shouldn't have import statements inside

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#5636]
It's called all the time, and import statements are quite expensive.

**Comment by zou3519** [comment]
@apaszke I couldn't find any import statements in https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L365-L391 -- is this the module you were referring to?

**Comment by apaszke** [comment]
It's already been fixed and I just forgot to close the issue. Thanks for noticing that!
