### ISSUE TITLE
Modernize test-suite in sparse tensor CSR support

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56371]
Originally raised in https://github.com/pytorch/pytorch/pull/50937#discussion_r604348471

Affected code:
- https://github.com/pytorch/pytorch/blob/0e106fce9ceae146193f57192a6b7cba02013447/test/test_sparse_csr.py#L26
  Inefficient CSR sparse tensor creation.
- https://github.com/pytorch/pytorch/blob/0e106fce9ceae146193f57192a6b7cba02013447/test/test_sparse_csr.py#L19
  Avoid using numpy: https://github.com/pytorch/pytorch/pull/50937#discussion_r608327281

cc @aocsa @nikitaved @pearu @mruberry @VitalyFedyunin @walterddr

**Comment by aocsa** [comment]
I would like to take this task if no one is working on this. cc @pearu.

**Comment by aocsa** [comment]
Just for clarification, the following requests about testing listed here https://pearu.github.io/csr_tensor_support.html 

https://github.com/pytorch/pytorch/pull/50937#discussion_r604348471 - see modern COO testing
https://github.com/pytorch/pytorch/pull/50937#discussion_r608327057 - don’t set default_dtype_type
https://github.com/pytorch/pytorch/pull/50937#discussion_r608327057 - avoid using numpy
https://github.com/pytorch/pytorch/pull/50937#discussion_r608675701 - inefficient CSR samples

are being solved in PR #56392

cc @pearu, @v0dro

**Comment by pearu** [comment]
Closing via #56392
