### ISSUE TITLE
Cannot easily run single test from distributed/test_distributed_spawn

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56389]
Steps to reproduce:
1. Build PyTorch with CUDA, as per the CI configuration pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test2
2. Try to run a single test with `python test/run_test.py -i distributed/test_distributed_spawn -- TestDistBackendWithSpawn.test_DistributedDataParallel_non_default_stream`

Expected result: single test is run
Actual result: test suite says that this test doesn't exist

What is actually happening is the test runner is looping through all backends this tests should be run on, and tests are conditionally defined/undefined depending on the backend. So it hits a backend which doesn't define the test and it explodes. There needs to be a way to run a specific backend from run_test.py

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment]
A workaround would be to run the test as follows `BACKEND=nccl WORLD_SIZE=2 python test/distributed/test_distributed_spawn.py -k test_DistributedDataParallel_non_default_stream`

**Comment by pritamdamania87** [comment]
What is happening here is that `test/run_test.py` runs tests for all backends (nccl, gloo and test) and in this case this particular test doesn't run for the "test" backend. The workaround I posted above should work for debugging.
