### ISSUE TITLE
Tensor Factory Improvements List

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#5641]
- [x] Include equivalents of `np.empty` / `np.full` (PR: https://github.com/pytorch/pytorch/pull/5668)
- [x] Include size-based `new` factory methods (with the eventual goal of deprecating `Variable.new`).  These are: `Variable.new_empty`, `Variable.new_ones`, `Variable.new_zeros`, `Variable.new_full`
(PR: https://github.com/pytorch/pytorch/pull/5668)
- [x] `torch.tensor` and `Variable.new_tensor` should have first-class support for sparse. (PR: https://github.com/pytorch/pytorch/pull/5745)
- [x] Verify device / dtype are consistent (Issue: https://github.com/pytorch/pytorch/issues/5461).
- [x] `new_tensor` / `torch.tensor` should copy numpy inputs (PR: https://github.com/pytorch/pytorch/pull/5713)
- [x] `torch.tensor` should do float/int type inference.  (PR: https://github.com/pytorch/pytorch/pull/5997)

**Comment by SsnL** [comment]
Please also add documentation for `torch.empty` and `torch.full`.

**Comment by gchanan** [comment]
This is now complete.
