### ISSUE TITLE
Scatter only supports reduce kwarg on inplace operator.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#56463]
Currently, only `scatter_` supports the optional `reduce` argument. It feels like `scatter` (the "out-of-place" version) should also support it (at least, I see no reason why not), since their implementations call the inplace version (which makes the implementation painless).

https://github.com/pytorch/pytorch/blob/0ea4eb745b4764e14d10f541887a12beb9949227/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L1046-L1052

**Comment by heitorschueroff** [comment]
We would accept a PR adding this functionality.
