### ISSUE TITLE
About install pytorch with source.

### ISSUE THREAD

**Issue by cainiaoshidai** [pytorch/pytorch#56461]
When I used source code to compile and install pytorch, I encountered the following problems：

Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/repeated_field.cc.o
ninja: build stopped: subcommand failed.

The file of log is here.
[log.txt](https://github.com/pytorch/pytorch/files/6342122/log.txt)

Behavior

`conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses`

`conda install -c pytorch magma-cuda100`

`git clone --recursive https://github.com/pytorch/pytorch`
`cd pytorch`
`git submodule sync`
`git submodule update --init --recursive`

`export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
`python setup.py install`

Environment

- Anaconda3
- Python 3.6.10
- Cuda 10.0
- Cudnn 7.6.5
- Cmake 3.6.1

cc @malfet @seemethere @walterddr

**Comment by skyline75489** [comment]
Can you try build with `USE_CUDA=0`?

**Comment by cainiaoshidai** [comment]
> Can you try build with `USE_CUDA=0`?

I have try, but I get the same result. Just like before.

**Comment by skyline75489** [comment]
You need to clean everything before rebuilding. Try python setup.py clean. Then rebuild.

**Comment by cainiaoshidai** [comment]
> You need to clean everything before rebuilding. Try python setup.py clean. Then rebuild. 

I have tried too. And I have tried change the version of cmake. It does't work.

**Comment by skyline75489** [comment]
The log you pasted shows errors regarding NVCC, this sometimes happens with the system CUDA installation. 

If you disable CUDA, what is the error you’re getting?

**Comment by cainiaoshidai** [comment]
> The log you pasted shows errors regarding NVCC, this sometimes happens with the system CUDA installation. 
> 
> If you disable CUDA, what is the error you’re getting?

Ok, let me try it. Thank you.

**Comment by cainiaoshidai** [comment]
> > The log you pasted shows errors regarding NVCC, this sometimes happens with the system CUDA installation. 
> > 
> > If you disable CUDA, what is the error you’re getting?
> 
> Ok, let me try it. Thank you.

Hi, my gpu is tesla k40. So the key to my question is whether this gpu has only 3.5 computing power.

**Comment by skyline75489** [comment]
Please open another issue and provide as much as information as you can.

**Comment by cainiaoshidai** [comment]
> Please open another issue and provide as much as information as you can. 

Ok, thanks.

**Comment by cainiaoshidai** [comment]
Hi, 
Today, I reinstalled cuda10.0, and then compiled successfully after running `USE_CUDA=0 python setup.py install`.
But, this is only the cpu version, how can I get the gpu version of pytorch?

**Comment by skyline75489** [comment]
There are CUDA 10.2 and 11.1 version of official build. If you really want to compile it yourself, perhaps try CUDA 10.2 or 11.1

**Comment by seemethere** [comment]
> There are CUDA 10.2 and 11.1 version of official build. If you really want to compile it yourself, perhaps try CUDA 10.2 or 11.1

Yes, unfortunately we don’t guarantee that PyTorch will compile for CUDA versions outside of the official versions we currently support in our nightlies.

Is there a possibility that you can try this with a more recent version of CUDA?

**Comment by skyline75489** [comment]
Closed in favor of #56572
