### ISSUE TITLE
Inconsistent Behavior of `torch.nn.utils.rnn.pack_padded_sequence` among Diffrent Versions of PyTorch when `input` is on GPU

### ISSUE THREAD

**Issue by BorisPolonsky** [pytorch/pytorch#56462]
## 🐛 Bug

The behavior of `torch.nn.utils.rnn.pack_padded_sequence` is inconsistent over different versions of PyTorch (1.4, 1.5, 1.6, 1.7), when `input` is on `gpu`, the device requirement for `lengths` differs (e.g. accepts GPU for PyTorch v1.6 while in v1.7 `lengths` should be on CPU otherwise exception will be raised. This breaks code for multi-device training in my project as I update PyTorch. Please kindly stabilize the behavior of this API

## To Reproduce

1. Please kindly run code below in PyTorch v1.4, v1.5, v1.6, v1.7
```
import torch

gpu_device = torch.device("cuda:0")
batch_input = torch.zeros([3, 4]).to(gpu_device) # [batch_size, seq_length]
seq_length = torch.tensor([2, 1, 4])  # CPU by default

# Works with PyTorch 1.6, fails in PyTorch 1.7
torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length, batch_first=True, enforce_sorted=False)

# Works with PyTorch 1.7, fails in PyTorch 1.6
torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length.to(gpu_device), batch_first=True, enforce_sorted=False)
```

For example, in PyTorch 1.7.0, the following code raise an exception when lengths is on "GPU"
```
    torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length.to(gpu_device), batch_first=True, enforce_sorted=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```
## Expected behavior

The behavior of this API should be consistent among different versions. In case `input` is on a specific cuda device, lengths should consistently accept either a CPU tensor or a GPU tensor on the very same device, or both, for different versions of PyTorch.
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.7.0):
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): docker
 - Build command you used (if compiling from source):
 - Python version: 3.8 (64-bit runtime)
 - CUDA/cuDNN version: 11.0.221
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by humanzer0** [comment]
I would like to work on this.

**Comment by jbschlosser** [comment]
Behavior on master requires `lengths` to be a CPU tensor:
```python
import torch

gpu_device = torch.device("cuda:0")
batch_input = torch.zeros([3, 4]).to(gpu_device) # [batch_size, seq_length]
seq_length = torch.tensor([2, 1, 4])  # CPU by default

# Works
torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length, batch_first=True, enforce_sorted=False)

# Fails
torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length.to(gpu_device), batch_first=True, enforce_sorted=False)
```
```
Traceback (most recent call last):
  File ".../pack.py", line 11, in <module>
    torch.nn.utils.rnn.pack_padded_sequence(batch_input, seq_length.to(gpu_device), batch_first=True, enforce_sorted=False)
  File ".../pytorch/torch/nn/utils/rnn.py", line 245, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

From the 1.7.0 release notes:
"**the torch.nn.utils.pack_padded_sequence: remove hidden cross-device copy for lengths (#41984)**
In previous versions, when the lengths argument was a CUDA tensor, it would incorrectly be moved to the CPU silently.
This can lead to surprising performances and CPU/GPU sync when using CUDA so this has been removed.
You need to make sure that the provided lenghts is a CPU Tensor when it is provided as a Tensor."
