### ISSUE TITLE
how to restore a model's weight from jit.traced model file?

### ISSUE THREAD

**Issue by fortuneko** [pytorch/pytorch#56473]
Hi guys,
   i have a traced pt model file, now i need to use it restore a net instance like below
```py
traced_model = torch.jit.load('traced.pt')
state_dict = extract_state_dict(traced_model) #need to implement
model = construct_model(args)
model.load_state_dict(state_dict)
```
extract_state_dict is the function i want to know to implement,thanks

cc @gmagogsfm

**Comment by nikithamalgifb** [comment]
@fortuneko : You can use `traced_model.state_dict()` to get the state_dict()

**Comment by fortuneko** [comment]
@nikithamalgifb thanks ,it works
