### ISSUE TITLE
[feature request] Add C++ test framework for pure C++ autograd+jit tests

### ISSUE THREAD

**Issue by lantiga** [pytorch/pytorch#5648]
Now that #5356 has been merged, it's probably a good time to consider taking tests in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/test_jit.cpp and moving them under a proper C++ testing umbrella.

I have a branch where I ported tests in test_jit to Catch2 (https://github.com/catchorg/Catch2), but @goldsborough and @ezyang raised concerns about adding this dependency.

I'll be happy to move ahead as soon as we identify the best library for the job (Catch2 is kind of nice because it's small, widely used and header-only).

/cc @fmassa @apaszke

**Comment by apaszke** [comment]
I'm quite ok with Catch2. @goldsborough @ezyang what were your concerns?

**Comment by goldsborough** [comment]
We're good. Ed and I had just discussed that Catch2 would be the way to go

**Comment by apaszke** [comment]
(NB I haven't done any research on the topic, I only haven't realized any problems with Catch so far)

**Comment by goldsborough** [comment]
I know the guy who wrote it from the C++ community and he's a pretty good developer. Catch2 is also officially supported by Jetbrains for their IDEs so it's pretty solid I think!

Also, a nice thing about Catch is that they crazy magic to make assertions with binary operators work, i.e. you can `assert(x == y)` where in GTest you'd have to write `ASSERT_EQ(x, y)`

**Comment by lantiga** [comment]
Ok great! Should we add Catch2 as a submodule? In this case I'll probably need you to do it - not sure I can add submodules from a PR.

**Comment by apaszke** [comment]
While we're at it, there are also tests in ATen and adding it as a submodule in `torch/lib` wouldn't let us use it. It would be good to figure out a strategy to have Catch work both for ATen (including the standalone repo) and for PyTorch.

**Comment by goldsborough** [comment]
Yes agreed, ATen absolutely should use this. Its handrolled tests look a bit bare right now

**Comment by goldsborough** [comment]
@gchanan Here is a situation where moving autograd/ under the root pytorch folder might be beneficial: sharing dependencies

In general, maybe we should create a general `lib` folder under `pytorch`?

**Comment by lantiga** [comment]
The Catch2 devs recommend to just vendor Catch2 in repositories
https://github.com/catchorg/Catch2/blob/master/docs/build-systems.md#cmake

The alternative, also mentioned in that page, is to use CMake's ability to git clone dependencies using the ExternalProject machinery, but I honestly wouldn't go there.

**Comment by lantiga** [comment]
Just vendoring Catch2 under ATen would let us use it from autograd.
