### ISSUE TITLE
[torchdeploy] No easy way to force rebuild of local cpython copy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#56490]
While working on #56489 I needed to rebuild cpython to see if I have got everything I needed. Rerunning `setup.py develop --cmake` after changing what lib dependencies were available on my system was not sufficient to force a rebuild of cpython.

cc @malfet @seemethere @walterddr @wconstab

**Comment by wconstab** [comment]
@ezyang - I'm wondering if the first thing we should do is fail faster- detect if cypthon failed to build particular modules and raise an alarm.

To do this, we'd have to hardcode the list of expected modules, but we already are ([https://github.com/pytorch/pytorch/blob/master/torch/csrc/deploy/interpreter/interpreter_impl.cpp#L35](here)), and we should probably start by moving that hardcoding somewhere else and using it to autogenerate any downstream places that need it.

Alternatively, if it's desirable to support building deploy under more flexible sets of libraries, we could do the changes you suggest:  make it easier to force-rebuild cpython - but i'm a little concerned this would more often result in people building broken stacks by accident than supporting people doing something intentionally custom.

**Comment by ezyang** [comment]
I don't really care about this issue; really all I need is a comprehensive list of all the deps I need to install.

**Comment by ezyang** [comment]
It does raise my eyebrow when you're building CPython with support for, e.g., NIS
