### ISSUE TITLE
Optional constructor param to set embedding weights

### ISSUE THREAD

**Issue by dpressel** [pytorch/pytorch#565]
It would be nice if it was possible to pre-initialize the embedding weights with an existing Tensor.  For example, this is possible in Keras, using the optional "weights" parameter (which defaults to None) 

Looking at sparse.py in nn/modules It looks like this would be fairly straightforward to add this (though I assume one would want to validate the input):

```
    def __init__(self, num_embeddings, embedding_dim, padding_idx=None,
                 max_norm=None, norm_type=2, scale_grad_by_freq=False,
                 sparse=False, weight=None):
        super(Embedding, self).__init__()
        self.num_embeddings = num_embeddings
        self.embedding_dim = embedding_dim
        self.padding_idx = padding_idx
        self.max_norm = max_norm
        self.norm_type = norm_type
        self.scale_grad_by_freq = scale_grad_by_freq
        
        self.weight = Parameter(weight or torch.Tensor(num_embeddings, embedding_dim))
        self.sparse = sparse

        self.reset_parameters()
```

**Comment by apaszke** [comment]
You can just replace the weights data. PyTorch is fully imperative so you can mess around with things even after construction time. Just do this:
```python
emb = nn.Embedding(...) # construct embedding with desired parameters
emb.weight.data = preloaded_weights
```

**Comment by dpressel** [comment]
Sure, I can do this -- I've done similar in the Lua code in the past.  Was just hoping to avoid a large allocation that I'd subsequently clobber

**Comment by apaszke** [comment]
How about this:
```python
emb = nn.Embedding(...)
del emb.weight
preloaded_weights = ...
emb.weight = nn.Parameter(preloaded_weight)
```
The parameter will immediately get freed and the memory will be reused for `preloaded_weight`.

**Comment by dpressel** [comment]
Well yes, that would work, but then we are allocating + deallocating (and of course allocating a second representation after that).  I should be able to just sub-class to get what I want though, so NBD.

**Comment by apaszke** [comment]
Allocating isn't that expensive, you're not doing that in a very tight loop, right?

**Comment by dpressel** [comment]
Yes, probably not a big deal.  Thanks for the quick responses.

**Comment by ozancaglayan** [comment]
Any design rationale behind why the layer types in pytorch does not have a constructor argument as suggested to define the initialization algorithm?
