### ISSUE TITLE
Resolved: add torch.testing.assert_close()

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#56544]
Today PyTorch's test suite principally uses assertEqual(), a TestCase method, to compare tensors (and containers of tensors, scalars, and NumPy arrays).

https://github.com/pytorch/pytorch/blob/ea4af1511c695b4e90eb6edc520b234ea3c71c23/torch/testing/_internal/common_utils.py#L1229

Unfortunately, this method is imperfect:

- it's a method on PyTorch's TestCase, which can make using it to compare tensors in libraries built on PyTorch tricky, and in practice there's significant use of [torch.equal()](https://pytorch.org/docs/master/generated/torch.equal.html?highlight=equal#torch.equal) to compare tensors in library tests; torch.equal() only allows comparing two tensors for bitwise equality, however
- the `exact_device` kwarg, which requires devices match, is still set to False for backwards compatibility; allowing tensors on different devices to compare as equal has been the source of bugs in the past
- it's called "assertEqual," but by default it actually asserts "closeness" and not "equality"

To provide a tensor comparison function suitable for both PyTorch's test suite and the test suites of libraries built on PyTorch, this RFC proposes creating a new function, torch.testing.assert_close(), with the following signature:

```
# Proposed testing function signature
torch.testing.assert_close(actual, expected, *, msg=None, rtol=None, atol=None, equal_nan=True, check_device=True, check_dtype=True)

# Current assertEqual signature for comparison
torch.testing.TestCase.assertEqual(self, x, y, msg=None, *, rtol, atol, equal_nan=True, exact_device=False, exact_dtype=True)
```

The new signature and the current signature are very similar. Their differences are:

- the new function is named assert_close to more accurately reflect its behavior and not to conflict with NumPy's [testing.assert_equal](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_equal.html#numpy.testing.assert_equal) name
- msg is a kwarg-only argument
- "exact_device" and "exact_dtype" have been changed to "check_device" and "check_dtype" for consistency
- the default value for "exact_device" is changed to True (note this is a TODO for assertEqual())

The behavior of this new function will be almost identical to assertEquals' behavior, except for the different default values and possibly new features like improved support for error handling.

I'd like to further propose that if and when we're happy with testing.assert_close we replace uses of assertEqual() with it in our test suite. This will create a period of a little confusion where some tests use the newer assert_close and some tests use the older assertEqual(), but our test suite has gone through more significant revisions without issue, and even assertEqual's behavior has confusingly changed over time. In fact, there are still lingering remnants of those changes left in the codebase, like assertEqualIgnoreType().

cc @ngimel @ezyang @cpuhrsch @nairbv @anjali411 @mthrok @pmeier

**Comment by mthrok** [comment]
From user perspective, the API looks good. What is the expected behavior when comparing array-like objects? such as `torch.tensor([0]) == [0]`?

**Comment by mruberry** [comment]
> From user perspective, the API looks good. What is the expected behavior when comparing array-like objects? such as `torch.tensor([0]) == [0]`?

Great question! I propose we be as strict as possible and continue to declare objects of different types not equal or, more precisely, not close. So a list is never "close" to a tensor, nor would a scalar be "close" to a 0D tensor. 

Allowing these cross-type comparisons can be convenient, but as a reviewer every time this feature would be used I'd have to try to figure out what the actual type was, and readability of the test suite seems important. Supporting "tensor like" objects is also tricky when working on multiple devices. For example, is zero close to torch.tensor((0,) device='cuda')? Or is it only close if `check_device=False`?

**Comment by ngimel** [comment]
TestCase.assertEqual allows comparison of 0d tensors with numbers.

**Comment by mruberry** [comment]
> TestCase.assertEqual allows comparison of 0d tensors with numbers.

That's true, but it also defaults to exact_device=False. I'd still like to be a little stricter, and I think this is a good opportunity to make BC-breaking changes which have been challenging with assertEqual() because it's so widely used.

**Comment by NicolasHug** [comment]
Thanks for continuing this work!

I have a few questions:

- is there a plan for an additional `testing.assert_equal` function? I find it useful to compare int tensors which are quite frequent in torchvision. An "assert_close" would not reflect the semantic we want for integers.
- what is the status of the new utilities in `testing._assert` (e.g. `assert_tensors_close`): will they become user-facing too at some point?

**Comment by pmeier** [comment]
@NicolasHug 

> is there a plan for an additional `testing.assert_equal` function? I find it useful to compare int tensors which are quite frequent in torchvision. An "assert_close" would not reflect the semantic we want for integers.

It is already there (or will be when #55385 is landed). Plus, the `assert_close` function selects the default `rtol` / `atol` based in the input dtype. For all integers this is `rtol = atol = 0.0`. For now the feedback we got seems to be that users are fine with that and wouldn't have much use for `assert_equal`. 

> what is the status of the new utilities in `testing._assert` (e.g. `assert_tensors_close`): will they become user-facing too at some point?

Yes, the current plan is to get them in the upcoming 1.9 release in a prototype state. That means, they will probably not be included in the PyPI binaries, but should be accessible if you build from source or use the nightlies.

**Comment by NicolasHug** [comment]
> For now the feedback we got seems to be that users are fine with that and wouldn't have much use for assert_equal

I would definitely do ;). `assert_equal` is more explicit than `assert_close` when you know the tensors you're comparing are integers. It helps "documenting" the test in a way.

> Yes, the current plan is to get them in the upcoming 1.9 release in a prototype state

It seems that both `assert_tensors_close` and `assert_close` are for tensor comparison. Which one should users be using then?

**Comment by mruberry** [comment]
Hey @NicolasHug!

> * is there a plan for an additional `testing.assert_equal` function? I find it useful to compare int tensors which are quite frequent in torchvision. An "assert_close" would not reflect the semantic we want for integers.

Great question! I agree with you it can be a convenient sugar and improve readability to use a function like testing.assert_equal() vs something like testing.assert_close(). However the worst-case workaround would be calling testing.assert_close(..., atol=0, rtol=0) or defining `testing.assert_equal = partial(testing.assert_close(atol=0, rtol=0)`. 

But yes, I think we should consider creating a public testing.assert_equal(), too!

> * what is the status of the new utilities in `testing._assert` (e.g. `assert_tensors_close`): will they become user-facing too at some point?

Those are just helper functions we have no plans to publicize. 

> It seems that both assert_tensors_close and assert_close are for tensor comparison. Which one should users be using then?

There are some internal asserts, but just like our current compareTensors function they're just internal implementation details that we should try and keep hidden. This proposal is to just expose a testing.assert_close() function (as described above).

**Comment by antocuni** [comment]
> But yes, I think we should consider creating a public testing.assert_equal(), too!

what about providing an `assert_equal` which works *only* for integer types? I.e. if you try to call it with floats you get an error which suggests to use `assert_close` instead. If you *really, really* want to compare floats by strict equality, `assert_close(rtol=0, atol=0)` would probably be good enough, IMHO.

Also, I don't know if I am still on time to propose changes to the name or if it's too late, but I think we could also consider `assert_equal_approx` or `assert_approx_equal` instead of `assert_close`:

- **PRO**: it has a name which is closer to the intended semantics: most of the time we are comparing something which should be mathematically equal to something else, if it weren't for the approximation errors introduced by the computers
- **PRO**: it is more natural for people who are used to [pytest.approx](https://docs.pytest.org/en/stable/reference.html#pytest-approx). We could even think to write a plugin to allow using `pytest.approx` with pytorch tensors (and which would call `testing.assert_close/assert_equal_approx` under the hood)
- **CON**: it is longer to type

**Comment by nairbv** [comment]
> Also, I don't know if I am still on time to propose changes to the name or if it's too late, but I think we could also consider assert_equal_approx or assert_approx_equal instead of assert_close:

Another consideration is consistency with the numpy API. Numpy has a numpy.testing.assert_almost_equal (I think we have or had a similar function) but the semantics are different (decimal places of precision). We'd want to avoid confusion between these assertions. I think the assert_close name is coming from the relationship to torch.isclose/numpy.isclose.

**Comment by mruberry** [comment]
> > Also, I don't know if I am still on time to propose changes to the name or if it's too late, but I think we could also consider assert_equal_approx or assert_approx_equal instead of assert_close:

Plenty of time to propose changes.

> Another consideration is consistency with the numpy API. Numpy has a numpy.testing.assert_almost_equal (I think we have or had a similar function) but the semantics are different (decimal places of precision). We'd want to avoid confusion between these assertions. I think the assert_close name is coming from the relationship to torch.isclose/numpy.isclose.

Yep; I agree we don't want to use a numpy.testing name unless we implement the same function.

**Comment by imaginary-person** [comment]
A digression: Why do we use different values of `rtol` for BFloat16 in `precision` decorators in `OpInfo`s of various ops?
Some ops have it as 1e-2, and others have 5e-2, so please confirm if they're set individually for each operator
by testing initially with 1e-2, and using 5e-2 only if 1e-2 doesn't work out.

Some tests use custom values of `atol` & `rtol`. https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1144-L1149 has different sets of values of `atol` & `rtol`, which are used by `assertEqual`.

So, for testing, should we aim at uniformity of `atol` & `rtol` values for a dtype across the codebase (and diverge from default values only if they won't suffice)? Currently, this doesn't seem to be the case.

Thank you!

**Comment by mruberry** [comment]
> A digression: Why do we use different values of `rtol` for BFloat16 in `precision` decorators in `OpInfo`s of various ops?
> Some ops have it as 1e-2, and others have 5e-2, so please confirm if they're set individually for each operator
> by testing initially with 1e-2, and using 5e-2 only if 1e-2 doesn't work out.

They are set individually.

> Some tests use custom values of `atol` & `rtol`. https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1144-L1149 has different sets of values of `atol` & `rtol`, which are used by `assertEqual`.
> 
> So, for testing, should we aim at uniformity of `atol` & `rtol` values for a dtype across the codebase (and diverge from default values only if they won't suffice)? Currently, this doesn't seem to be the case.

No. The defaults are just that: defaults. Particular tests may require different values. For example, let's say that each bfloat16 operation had an absolute error of 1e-5 (I'm making this number up for illustration purposes) and we were doing "golden value" testing or "fixture-based" testing where we were comparing inputs to a known, mathematically validated output. If our computation has 5 bfloat16 operations and they were working properly then we could see an error of 5e-5. If, on the other hand, our computation was 30 bfloat16 operations we could see an error of 30e-5, and this is expected. So the latter test probably needs a different error bound.

Different tests also test different ranges of a function. Operations like sin and cos might be extremely precisely for denormal numbers  but relatively imprecise for values above 500, for example. So tests of larger values will likely need different error bounds than tests with smaller values.

**Comment by imaginary-person** [comment]
Thank you for the clarification, @mruberry! It was very helpful!

**Comment by mruberry** [comment]
Updating this to resolved. The function is now documented as PROTOTYPE here: https://pytorch.org/docs/master/testing.html?highlight=assert_close#torch.testing.assert_close. Note that, as a prototype, this function and the torch.testing module are very much subject to change. So we can continue to consider alternative names and additional functions, like `assert_equal`, functions from numpy.testing, and `assert_approx_equal`.

**Comment by NicolasHug** [comment]
We started to adopt `assert_close` in https://github.com/pytorch/vision/pull/3865 (still WIP) and here's some initial feedback which I hope is useful:

1. It's great! And well-documented, thanks a lot for all this work.
2. As mentioned above, an `assert_equal` util would be useful - we have to define it ourselves for now
3. We have to use `check_stride=False` in a lot of cases (27 times for now). Having different strides can come up easily when working with views and / or reshaped/re-aligned tensors, and we have a lot of that. Ultimately the strides have little to do with the equality of 2 arrays (less-so than say, their dtype at least), so perhaps we could consider changing the default to False? For ref, numpy doesn't check for stride equality:

```py
a = np.arange(10).reshape(2, 5)
b = np.asfortranarray(a)
np.testing.assert_allclose(a, b) # passes
a.strides, b.strides
# ((40, 8), (8, 16))
```

4. I know this has been proposed already, but I personally rely a lot on `np.testing.assert_allclose` ability to compare an array to a scalar. It's usually really obvious that what we're comparing to is a scalar, so I'm not sure there's much risk of missing some bugs by supporting that. I've used it a ton in other projects, and it's much more convenient than to have to create a similarly-shaped tensor with e.g. `full_like`. For example in the aforementioned PR we're porting:

```py
        self.assertTrue((result[:, :padding, :] - fill_v).abs().max() < eps)
        self.assertTrue((result[:, :, :padding] - fill_v).abs().max() < eps)
```

into

```py
        h_padded = result[:, :padding, :]
        w_padded = result[:, :, :padding]
        torch.testing.assert_close(h_padded, torch.full_like(h_padded, fill_value=fill_v), check_stride=False, rtol=0.0, atol=eps)
        torch.testing.assert_close(w_padded, torch.full_like(w_padded, fill_value=fill_v), check_stride=False, rtol=0.0, atol=eps)
```

where we need to use `full_like` and create temporary variables. Also note how we're forced to pass `check_stride=False` here, but that could be addressed by item 3. If we could compare to scalars we could just do

```py
        torch.testing.assert_close(result[:, :padding, :], fill_v, rtol=0.0, atol=eps)
        torch.testing.assert_close(result[:, :, :padding], fill_v, rtol=0.0, atol=eps)
```

which is much more natural to write and read IMHO.

**Comment by mruberry** [comment]
> We started to adopt `assert_close` in [pytorch/vision#3865](https://github.com/pytorch/vision/pull/3865) (still WIP) and here's some initial feedback which I hope is useful:

Thank you for the thoughtful feedback, @NicolasHug!

> 2. As mentioned above, an `assert_equal` util would be useful - we have to define it ourselves for now

I agree with you. How much pain do you think it is to define assert_equal yourself by partialing assert_close, however? Is that OK or would you expect other features of assert_equal? 

> 3. We have to use `check_stride=False` in a lot of cases (27 times for now). Having different strides can come up easily when working with views and / or reshaped/re-aligned tensors, and we have a lot of that. Ultimately the strides have little to do with the equality of 2 arrays (less-so than say, their dtype at least), so perhaps we could consider changing the default to False? For ref, numpy doesn't check for stride equality:

What would you think of defining your own assert_close (or whatever you'd like to call it) that is just a call to torch.testing.assert_close with the defaults you like? 

My concern with making the default less stringent is that torchvision won't be the only user of the function.

> 1. I know this has been proposed already, but I personally rely a lot on `np.testing.assert_allclose` ability to compare an array to a scalar. It's usually really obvious that what we're comparing to is a scalar, so I'm not sure there's much risk of missing some bugs by supporting that. I've used it a ton in other projects, and it's much more convenient than to have to create a similarly-shaped tensor with e.g. `full_like`. For example in the aforementioned PR we're porting:
> 
> ```python
>         self.assertTrue((result[:, :padding, :] - fill_v).abs().max() < eps)
>         self.assertTrue((result[:, :, :padding] - fill_v).abs().max() < eps)
> ```
> 
> into
> 
> ```python
>         h_padded = result[:, :padding, :]
>         w_padded = result[:, :, :padding]
>         torch.testing.assert_close(h_padded, torch.full_like(h_padded, fill_value=fill_v), check_stride=False, rtol=0.0, atol=eps)
>         torch.testing.assert_close(w_padded, torch.full_like(w_padded, fill_value=fill_v), check_stride=False, rtol=0.0, atol=eps)
> ```
> 
> where we need to use `full_like` and create temporary variables. Also note how we're forced to pass `check_stride=False` here, but that could be addressed by item 3. If we could compare to scalars we could just do
> 
> ```python
>         torch.testing.assert_close(result[:, :padding, :], fill_v, rtol=0.0, atol=eps)
>         torch.testing.assert_close(result[:, :, :padding], fill_v, rtol=0.0, atol=eps)
> ```
> 
> which is much more natural to write and read IMHO.

I agree there are definitely cases where this pattern is more natural. What would you think about a new kwarg that would allow these cross-type comparisons? If the previous approach of wrapping torch.testing.assert_close with your desired defaults is OK, then it could be defaulted to always allow such comparisons in torchvision?

Looking forward to hearing your thoughts on these proposals!

**Comment by antocuni** [comment]
>> I know this has been proposed already, but I personally rely a lot on np.testing.assert_allclose ability to compare an array to a scalar.

> I agree there are definitely cases where this pattern is more natural. What would you think about a new kwarg that would allow these cross-type comparisons?

an idea which came to my mind while reading this thread: what about the following:
```python
        torch.testing.assert_close(result[:, :padding, :], scalar=fill_v, rtol=0.0, atol=eps)
        torch.testing.assert_close(result[:, :, :padding], scalar=fill_v, rtol=0.0, atol=eps)
        # or maybe expected_scalar?
```
This makes very obvious what is going to happen and avoid to introduce subtle code which tries to guess what is the right way to convert `expected` into something which can be compared to `actual` ("In the face of ambiguity, refuse the temptation to guess", cit.)

**Comment by NicolasHug** [comment]
> How much pain do you think it is to define assert_equal yourself by partialing assert_close, however?

> What would you think of defining your own assert_close (or whatever you'd like to call it) that is just a call to torch.testing.assert_close with the defaults you like?

It's not too much pain, and I think this is what we'll end up doing. My gut feeling is that `assert_equal` and `check_stride=False` by default would be useful for most downstream projects, but I understand the decision to be as strict as possible by default.

> What would you think about a new kwarg that would allow these cross-type comparisons?

Yes that'd be great to have! I also find @antocuni 's suggestion above quite elegant.

----------

Another item that came to mind:

5. It's currently impossible to set `rtol` only or `atol` only. I found that a bit surprising considering that `np.testing.assert_allclose` doesn't have that constraint.  @pmeier pointed me to this comment in the code:

> We require both tolerance to be omitted or specified, because specifying only one might lead to surprising
 results. Imagine setting atol=0.0 and the tensors still match because rtol&gt;0.0

IMHO this one scenario is an argument towards having `assert_close` :), and setting `atol=0` without setting `rtol` is a clear mis-use anyway. Are there other potential surprising scenarios?

This constraint can be a bit awkward to deal with: imagine a test where we need to increase the `rtol` but we don't want/need  to touch `atol`. With the constraint, we need to look-up the current default for `atol` and hard-code it in the code. That default might change in the future, and we wouldn't benefit from that since we hardcoded it. Now imagine that this same test is run on 3 different dtypes: since the defaults are dtype-dependent, we now need to keep track of 3 defaults if we want to replicate the intended behavior.

**Comment by mruberry** [comment]
> This constraint can be a bit awkward to deal with: imagine a test where we need to increase the `rtol` but we don't want/need to touch `atol`. With the constraint, we need to look-up the current default for `atol` and hard-code it in the code. That default might change in the future, and we wouldn't benefit from that since we hardcoded it. Now imagine that this same test is run on 3 different dtypes: since the defaults are dtype-dependent, we now need to keep track of 3 defaults if we want to replicate the intended behavior.

That would be a pain, is there an example of a test like this we can point to?

@pmeier Seems like we should create a separate issue for adding a new kwarg that allows for cross-type comparisons?

**Comment by NicolasHug** [comment]
> That would be a pain, is there an example of a test like this we can point to?

Sure:

- In https://github.com/pytorch/vision/pull/3876/files#r636847866  we have to manually set `rtol=1e-5` to keep the value consistent to what it was prior to the change (namely, `torch.allclose`'s default). But ideally we would like to just rely on `assert_close`'s default and not have to worry about this. There are currently 7 occurrences of hardcoding `rtol=1e-5` in torchvision's code and most (if not all) come from the porting from `allclose` to `assert_close`
- In https://github.com/pytorch/vision/pull/3884/files#diff-1003f09123dbb6889695359d4e6671acb8e46ab7ff1c92bfe99061fae9531261R1466-R1468 we're manually setting `atol=1e-8` to keep the value  consistent with numpy's allclose, but here again we could just rely on `torch.testing.all_close`'s default ideally.

**Comment by nairbv** [comment]
Some historical context, if I can remember this correctly, that I think might be relevant. I think the comment in the code doesn't tell the whole story:

Here's the original PR that introduced atol/rtol for assertEqual: https://github.com/pytorch/pytorch/pull/34258

We initially only had prec (for precision) which meant atol, and didn't have rtol. Atol/prec had a (single) default (for all dtypes), which I believe was 1e-5. Atol was allowed as a positional arg (e.g. one could write `assertEqual(expected, actual, 0, message="the values didn't match!")`). 

When we first added rtol, in an earlier version of the PR I believe I had it set such that when `atol=0` the rtol would remain at the default non-zero value (which I think is what's being requested in this thread). There was an objection to that approach: it relaxed the constraint on existing tests that had been written as `assertEqual(expected, value, 0.0)`. I think this is what's really being referenced in the code comment:

> We require both tolerance to be omitted or specified, because specifying only one might lead to surprising
results. Imagine setting atol=0.0 and the tensors still match because rtol>0.0

In the case of `assertEqual(expected, value, 0.0)`, which had been written before rtol was available, if the tensors still match it would be surprising. I'm not sure if the current code even still allows positional atol, but we should probably get rid of that eventually if it does. There might be implications in xla as well.

Since some atol args were written as positional arguments, tracking all of them down and fixing them in pytorch core would have been tedious. At the time we reluctantly decided we were OK to enforce that when atol=0, and rtol isn't explicitly set, rtol is also 0. I don't think this is the ideal behavior, but to change it we probably need to audit the existing tests to ensure they would still be setting whatever tight tolerances were initially intended.

**Comment by pmeier** [comment]
Since we are designing a new API here, I don't see a reason to keep the behavior if it was only put in place for BC. We probably won't be able to remove `self.assertEqual` without quite some effort, so we will probably keep it and call `torch.testing.assert_close` from there. In such a scenario we could simply keep the check in `self.assertEqual` and use a more relaxed behavior in `torch.testing.assert_close`.

> I'm not sure if the current code even still allows positional atol, but we should probably get rid of that eventually if it does.

It does not:

https://github.com/pytorch/pytorch/blob/44c20ce676c6ca2a8b04af72c80c36698ee34d60/torch/testing/_internal/common_utils.py#L1261-L1263

**Comment by nairbv** [comment]
> Since we are designing a new API here...

There's something to be said for consistency but this plan sounds reasonable to me. We should probably clean up the assertEquals atol usage at some point to match the behavior proposed here.

> It does not:

That should make cleanup easier at least. At some point I think we'll just need to go through and replace all assertEqual calls that specify `atol=0` and no `rtol` to explicitly set `rtol=0`, then make the assertEqual behavior consistent with what's planned here.

**Comment by mruberry** [comment]
Closing this issue because torch.testing.assert_close has been added (and updated per this feedback) -- but we're still taking feature requests and suggestions because the torch.testing is still in a "prototype state"! Just file those requests/suggestions as new issues. Thanks for the feedback, all!

**Comment by zylo117** [comment]
2.2.0, though this script can not reproduce, layer norm with certain weight does produce wrong result in fp16. And torch.autocast to fp32 is not helping, I will have to manually cast the layer norm op and the input to fp32 and cast back to fp16 when calculation is done to get the correct result.
This must be a bug of either pytorch or cuda!!!
