### ISSUE TITLE
[BE] optimize hard-coded branch name in util scripts that might not work on release branch

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#56556]
There are a bunch of hard-coded master branch name in utility scripts used for CI. 

Here are the ones that potentially will be used in CI
* [.jenkins/pytorch/common_utils.sh](https://github.com/pytorch/pytorch/blob/a4626348bc85b6484d647ceb07298b3516e2a7b3/.jenkins/pytorch/common_utils.sh#L52-L58)
* [test/run_test.py](https://github.com/pytorch/pytorch/blob/a4626348bc85b6484d647ceb07298b3516e2a7b3/test/run_test.py#L411-L413)
* [tools/export_slow_tests.py](https://github.com/pytorch/pytorch/blob/a4626348bc85b6484d647ceb07298b3516e2a7b3/tools/export_slow_tests.py#L16)

These might be broken if run on release branch.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
This is no longer relevant, closing
