### ISSUE TITLE
Use `rg` for quick checks

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#56558]
The quick checks in `lint.yml` use `git grep` to search for things like newlines, trailing spaces, etc. 

https://github.com/pytorch/pytorch/blob/a4626348bc85b6484d647ceb07298b3516e2a7b3/.github/workflows/lint.yml#L48

We should change this to install [rg](https://github.com/BurntSushi/ripgrep) via `sudo apt install -y ripgrep` and use that instead. It's ever so slightly more ergonomic to use and provides about a 3x speedup over `git grep`

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
If we’re going to use `ripgrep` we should install it as a static binary that we control instead of using a package manager so we can have it be distro agnostic and have a guarantee that the download server won’t go down unexpectedly

**Comment by ezyang** [comment]
The line here takes 0.26s to run on my machine. You're going to spend more time apt installing rg...

**Comment by samestep** [comment]
I'd only be interested in making this change if it substantially reduces the time taken to run `make lint` or `make quicklint`.

**Comment by driazati** [comment]
Closing since  it's too low pri and dubious benefit
