### ISSUE TITLE
cannot inference on multi GPU?

### ISSUE THREAD

**Issue by pzz2011** [pytorch/pytorch#5656]
pytorch version 0.3.1
OS CenOS
CUDA Version 9.0.176
CUDNN 7
GPU:8  V100 16GB

THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
*** Error in `python': free(): invalid pointer: 0x00007f161ccfe780 ***

I wonder that why I cannot inference on multi-GPU....

opt = parser.parse_args()
cuda = opt.cuda

if cuda and not torch.cuda.is_available():
    raise Exception("No GPU found, please run without --cuda")

model = torch.load(opt.model)["model"].module

**Comment by soumith** [comment]
you are running out of memory in your script.
Without specifics we cannot treat this as a bug. Post more details at https://discuss.pytorch.org and we can try help you figure out why you are running out of memory.
