### ISSUE TITLE
Depthwise 1D convolution on text

### ISSUE THREAD

**Issue by DeweiHu66666** [pytorch/pytorch#56573]
Hi: )  I'm using 1D convolution on text. 
My input is [B, D*T, L], which are batch size, embedding dimension, target space, and input length; then I have a 1D convolution layer:  `layer = nn.Conv1d(D*T, num_filter_maps*T, kernel_size, groups=T)` As described in documentation of `nn.Conv1D`, there would be T different "conv blocks" stacked together. However, as in my project, I need to make all conv blocks share the same parameters. Could anyone please give me some help?

**Comment by ailzhang** [comment]
Hi, please post questions on forum instead, thanks!
