### ISSUE TITLE
`torch.cuda.current_device` returns wrong device when called over RPC

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#56588]
## 🐛 Bug

If a function uses `current_device`, and is called over RPC, then `current_device` seems to always return `0`.

## To Reproduce

The script below:

1. Defines a function `foo` that prints PID and `current_device`
2. Creates two workers, `worker0` and `worker1`, with ranks `0, 1`, respectively
3. Calls `torch.cuda.set_device(rank)` on each worker
4. Calls `foo` locally on each worker
5. Calls `foo` over RPC on each worker

The output of `foo` differs when called locally vs over RPC.

```python
import os
import torch
from torch import multiprocessing as mp
from torch.distributed import rpc

def foo(with_rpc=True):
    device = torch.cuda.current_device()
    prefix = 'with_rpc' if with_rpc else 'without_rpc'
    print(f'{prefix}: {os.getpid()=}, {device=}')

def worker0():
    rpc.init_rpc("worker0", rank=0, world_size=2)
    foo(with_rpc=False)
    rpc.remote("worker1", foo)
    rpc.shutdown()

def worker1():
    rpc.init_rpc("worker1", rank=1, world_size=2)
    foo(with_rpc=False)
    rpc.remote("worker0", foo)
    rpc.shutdown()

def run(rank):
    device = rank
    torch.cuda.set_device(rank)
    assert torch.cuda.current_device() == device
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    if rank == 0:
        worker0()
    else:
        worker1()


def main():
    mp.start_processes(run, nprocs=2, start_method='fork')


if __name__ == '__main__':
    main()

```

Output:
```
without_rpc: os.getpid()=28549, device=0
without_rpc: os.getpid()=28550, device=1
with_rpc: os.getpid()=28550, device=0
with_rpc: os.getpid()=28549, device=0
```
The third line should've printed `device=1`.

## Expected behavior
`current_device` should return the correct device, even over RPC.

## Environment

```
PyTorch version: 1.9.0.dev20210417
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 450.102.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210417
[pip3] torchaudio==0.9.0a0+c70dba4
[pip3] torchvision==0.10.0.dev20210419
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.9.0.dev20210417 py3.8_cuda11.1_cudnn8.0.5_0    pytorch-nightly
[conda] torchaudio                0.9.0.dev20210419            py38    pytorch-nightly
[conda] torchvision               0.10.0.dev20210419      py38_cu111    pytorch-nightly
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
The setting of `torch.cuda.current_device()` is thread local, see for example the output of this script:
```
import torch
from threading import Thread

def in_thread():
    print(torch.cuda.current_device())

torch.cuda.set_device(1)
assert torch.cuda.current_device() == 1
thr = Thread(target=in_thread, args=())
thr.start()
thr.join()
```

Since the python functions ran over RPC are run in a separate thread and the current_device for worker 1 is set in the main thread, it makes sense that the current_device is 0 on the separate thread. 

If you have a use case to use certain devices in RPC callbacks, the tensorpipe backend supports `device_maps` which can be used to configure this: https://pytorch.org/docs/stable/rpc.html#torch.distributed.rpc.TensorPipeRpcBackendOptions.set_device_map and tensors will automatically be on the appropriate devices in the RPC function.

**Comment by rafi-cohen** [comment]
Thanks for your reply.

> The setting of `torch.cuda.current_device()` is thread local

That explains it. Sorry for confusing RPC for causing this behavior.
Is there any way to get `current_device` to return the same value across all threads?


> If you have a use case to use certain devices in RPC callbacks, the tensorpipe backend supports `device_maps` which can be used to configure this: https://pytorch.org/docs/stable/rpc.html#torch.distributed.rpc.TensorPipeRpcBackendOptions.set_device_map and tensors will automatically be on the appropriate devices in the RPC function.

I'm aware of `device_maps`, however, it's not relevant in the specific use-case I have.

**Comment by pritamdamania87** [comment]
> Is there any way to get current_device to return the same value across all threads?

No, `current_device` is thread local and will be different for each thread.

> I'm aware of device_maps, however, it's not relevant in the specific use-case I have.

Could you elaborate a bit on your use case here? That might help in resolving the issue. One simple solution might be to have `foo()` take a device parameter and you manually call `set_device` each time inside foo() to ensure that logic runs on the appropriate device.

**Comment by rafi-cohen** [comment]
> Could you elaborate a bit on your use case here? That might help in resolving the issue. One simple solution might be to have `foo()` take a device parameter and you manually call `set_device` each time inside foo() to ensure that logic runs on the appropriate device.

I was trying to avoid having to pass a `device` parameter, but I guess I'll just settle for this solution.

Thank you both for your help!
