### ISSUE TITLE
`torch.set_num_threads()` causes DataLoader workers to be killed by segfault.

### ISSUE THREAD

**Issue by ClonedOne** [pytorch/pytorch#56615]
## 🐛 Bug

`torch.set_num_threads()` causes DataLoader workers to be killed by segfault.
```
RuntimeError: DataLoader worker (pid 26203) is killed by signal: Segmentation fault
```

## To Reproduce

This happens when the value passed to `torch.set_num_threads()` is >= 4. Also happens when the same value is passed to both `torch.set_num_threads()` and as a parameter to `DataLoader(..., num_workers=workers)`.

This notebook can be used to reproduce the issue: https://github.com/ClonedOne/exp_nbs/blob/master/dataloader_segfault.ipynb
The same repository also contains the numpy data files used.

Dataloader functions normally if I remove `torch.set_num_threads()`.

## Expected behavior

DataLoader object should load each batch without causing a segmentation fault.

## Environment

PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.10 (x86_64)
GCC version: (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] Could not collect

## Additional context

The issue also happened with:
torch==1.8.0+cpu
torchaudio==0.8.0
torchvision==0.9.0+cpu

**Comment by imaginary-person** [comment]
Duplicate of #54752. It has since been fixed & the fix would be present in a future release.

**Comment by ClonedOne** [comment]
Thank you, hadn't seen that. Closing.
