### ISSUE TITLE
new torch.profiler slow for large number of events?

### ISSUE THREAD

**Issue by victor-shepardson** [pytorch/pytorch#56623]
## 🐛 Bug

I am seeing the new `torch.profiler` lock up for an extended period at the end of profiling my very complex recurrent model. manually interrupting traces to the listcomp in line 72 of profiler.py:

https://github.com/pytorch/pytorch/blob/56b43f4fec1f76953f15a627694d4bba34588969/torch/autograd/profiler.py#L58-L74

which appears to be quadratic in the number of events. changing `to_delete` to be a set instead of a list seemed to resolve the issue for me.

## Environment

torch 1.8.1 with cuda, python 3.8.8, ubuntu 18.04 

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by ilia-cher** [comment]
That's a known issue scheduled to be fixed in 1.9, thanks for reporting!
