### ISSUE TITLE
Cleaner mechanism in the source-code to check if multiple tensors are on the same device

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#56632]
## 🚀 Feature (in source-code)
A cleaner abstraction in the source code to check if multiple tensors are on the same device.

## Motivation

Currently, [`checkAllSameGPU`](https://github.com/pytorch/pytorch/blob/eac082891f2f8d65381fcaad24b3bbab8fba0cc7/aten/src/ATen/TensorUtils.cpp#L130-L152) in `TensorUtils.h` allows to check if multiple tensors are on the same GPU.
But there isn't a similar mechanism to check if multiple tensors are on the same device, except for using
`TORCH_CHECK` statements. 

[`checkSameDevice`](https://github.com/pytorch/pytorch/blob/eac082891f2f8d65381fcaad24b3bbab8fba0cc7/aten/src/ATen/native/LinearAlgebraUtils.h#L485-L491) in `LinearAlgebraUtils.h` allows _neatly_ checking if two tensors,
(which are meant to be an input tensor and an output tensor) are on the same device.

## Pitch

Having a function named [`checkAllSameDevice`](https://github.com/pytorch/pytorch/blob/e16d9d8f2aaf5dd44c15f8b10755d2e91d344e35/aten/src/ATen/TensorUtils.cpp#L154-L164) that corresponds to `checkAllSameGPU`, but for all devices.

Pros: Won't have to duplicate similar `TORCH_CHECK`s.
Cons: Slower than corresponding `TORCH_CHECK` macros.

## Alternatives

`TORCH_CHECK` statements can be written, but they're probably not as good for readability & understandability, as say,
`checkAllSameGPU`, which can also avoid duplicating code, which's a bigger concern.

`checkSameDevice` in `LinearAlgebraUtils.h` can also be used multiple times wherever the header has been included, but perhaps a `TORCH_CHECK` would be better in that case.

## Additional context
An example of  `checkAllSameGPU` is:
```
  TensorArg args[]{{result, "out", 0}, {self, "self", 1}, {mat1, "mat1", 2}, {mat2, "mat2", 3}};
  checkAllSameGPU("addmm", args);
```

**Comment by ngimel** [comment]
We should avoid wrapping Tensor arguments in TensorArg for perf reasons (this bumps ref count), and all the mentioned functions act on TensorArgs.
