### ISSUE TITLE
torch.Size doesn't accept pytorch scalar

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#5663]
```
import torch

torch.Size([torch.arange(10).max()])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-55c7fb723da0> in <module>()
----> 1 torch.Size([torch.arange(10).max()])

TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'Variable')

```

Also did the tensor/variable merger mean everything is called 'Variable' now? I would think everything would be called 'Tensor'.

**Comment by zou3519** [comment]
@adamlerer everything should be called 'Tensor' now and nothing should be called 'Variable', so that should be fixed as well

**Comment by adamlerer** [comment]
Thanks @zou3519 , yes I've got it running with the workaround, just wanted to report this so it can be fixed.
