### ISSUE TITLE
DataParallel can't gather if scatter dimension is not zero and batch_size%num_devices!=0

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#5664]
This happened to me on branch 0.3.1, built from source with system NCCL 1.3.5, CUDA 9.1 and cuDNN 7.1. Tried on 3 GPUs with compute capability 3.0.
Error looks like this:
```
ValueError: gather got an input of invalid size: got 1x1, but expected 3x1
```
Here's the [stack trace](https://gist.github.com/VladislavZavadskyy/9e4fae4f14950b71316204ffb54a193e).

**Comment by fmassa** [comment]
Did you try modifying the `dim` [argument of `DataParallel` to be the dimension that you want to split](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/data_parallel.py#L71)?

**Comment by VladislavZavadskyy** [comment]
@fmassa That's exactly how I've got this issue, it works fine with the default dim. It's simple to work around in my case (by transposing for example), but it's still a bug.

**Comment by fmassa** [comment]
Maybe you could provide a minimum reproducible example (I believe it can be done in a few lines) to facilitate the identification of the problem?

**Comment by VladislavZavadskyy** [comment]
@fmassa Here you go:
```python
class SomeModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.cell = nn.GRUCell(10,10)
    
    def forward(self, x, batch_major):
        batch_dim = 1-batch_major
        h = Variable(torch.zeros(x.shape[batch_dim],10), requires_grad=False).cuda()
        for t in range(x.shape[1-batch_dim]):
            x_t = x[:,t] if batch_major else x[t]
            h = self.cell(x_t, h)
        return h

m = SomeModel()
m = nn.DataParallel(m, [0,1,2]).cuda()
data = Variable(torch.randn(11,11,10)).cuda()
m(data, True)
```
Works fine, but
```python
m = SomeModel()
m = nn.DataParallel(m, [0,1,2], dim=1).cuda()
data = Variable(torch.randn(11,11,10)).cuda()
m(data, False)
```
throws above mentioned error.


I was going to go with:
```python
m = nn.GRU(10,10)
m = torch.nn.DataParallel(m, [0,1,2]).cuda()
data = Variable(torch.randn(10,10,10)).cuda()
m(data)
```
but it [deserves](https://gist.github.com/VladislavZavadskyy/b223c1a704f067ea00f4397e308756a9) an issue of it's own (my guess it's due to cuDNN backend, fails even without DataParallel).

**Comment by ailzhang** [comment]
Hi @VladislavZavadskyy , I think I know why this didn't work. If you split the data in dim=1, the gather also happens in dim=1 here. https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/data_parallel.py#L113
So in your example, three tensor with shape (4,10), (4,10), (3,10) is designed for a gather in dim=0. You can tweak the shape a bit to make it work with dim=1.
