### ISSUE TITLE
pytorch.version

### ISSUE THREAD

**Issue by zeneofa** [pytorch/pytorch#5665]
When trying run a binary build, the setup cannot find tools/pytorch.version . This file is in previous version but not in master.

**Comment by zou3519** [comment]
Could you please copy and paste the exact error message you're getting?

**Comment by soumith** [comment]
I checked-in the file into master via https://github.com/pytorch/pytorch/commit/4b2d2789686ee150cce884cd3410defda340a8f7

There might be additional entries I have to make to the file on master, I'll verify it.
