### ISSUE TITLE
build break in vec256_test_all_types after MaxPool2d channels PR

### ISSUE THREAD

**Issue by dncliss** [pytorch/pytorch#56650]
## 🐛 Bug

The latest build of pytorch (on `ppc64le` platform at least) has a new build error when building the `vec256_test_all_types.cpp` file.  An error appears, as follows:
```[01m[K../aten/src/ATen/test/vec256_test_all_types.cpp:459:46:[m[K [01;31m[Kerror: [m[K‘[01m[Kclass at::vec256::{anonymous}::Vec256<double>[m[K’ has no member named ‘[01m[Kisnan[m[K’```

This appears to come from newly merged code added as part of PR #56361  -- line `459` of `vec256_test_all_types.cpp`

Build output can be seen from the ppc64le CI build as shown in this output: 
https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le-gpu/1086/console
(Lots of output; just search on the vec256_test_all_types file name to find above error).

## To Reproduce

1. Build the current master branch of pytorch on ppc64le platform. (result on other platforms, unknown.)
If not available, observe output as per CI build link provided above.

## Expected behavior

Build should complete successfully as usual.

## Environment

 - PyTorch Version (e.g., 1.0): current master branch
 - OS (e.g., Linux): Ubuntu 18.04 (probably not relevant to this error)
 - How you installed PyTorch: clone of github source master branch
 - Build command you used: commands can be seen in the referenced console output
 - Python version: 3.7 (but not relevant to this error)
 - CUDA/cuDNN version: 10.2 (but not relevant to this error)
 - GPU models and configuration: ppc64le docker container

## Additional context

Perhaps coincidence, but a similar error (different file, different symbol, but also in the `aten` code) came up in a build break
a day or two before this one, with a fix merged today. Might be worth a  peek just to compare the error and corresponding fix: https://github.com/pytorch/pytorch/pull/56486

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by malfet** [comment]
@dncliss those errors will keep popping up unless we can figure out how to enable some basic build sanity for PowerPC target. Are there cross-toolchains available?
