### ISSUE TITLE
Windows GPU testing is broken in CircleCI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#56654]
See:
https://app.circleci.com/pipelines/github/pytorch/pytorch/306591/workflows/2b2a8987-831c-4704-a888-b3c7c3ebe578/jobs/12703407
And "Re-run with SSH" functionality is broken as well, making it impossible to debug what is going on:
https://support.circleci.com/hc/en-us/requests/89455

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
This run has the exact same commit with the failed one, but it succeeded. Wonder if it's something in the builder repo.

https://app.circleci.com/pipelines/github/pytorch/pytorch/306591/workflows/2b2a8987-831c-4704-a888-b3c7c3ebe578/jobs/12661342

**Comment by peterjc123** [comment]
> This run has the exact same commit with the failed one, but it succeeded. Wonder if it's something in the builder repo.
> 
> https://app.circleci.com/pipelines/github/pytorch/pytorch/306591/workflows/2b2a8987-831c-4704-a888-b3c7c3ebe578/jobs/12661342

Hey, the test jobs with the prefix `pytorch_` in their name doesn't use anything in the builder repo.

**Comment by peterjc123** [comment]
[Here] (https://github.com/pytorch/pytorch/pull/56665#issuecomment-824947363) is my analysis. Looks like we should check the GPU driver installation for CUDA 10 jobs (Previously, we don't do that because they are properly installed) Or maybe we should open a ticket at the circleci side.

**Comment by malfet** [comment]
There are already a ticket against CircleCI, in the meantime I would like to understand why adding 3 min delay is becoming necessary? As @peterjc123 said, CUDA install should be blocking, shouldn't it?

**Comment by ezyang** [comment]
Current status: we're on a temporary release (but will get broken again soon), there's a fundamental issue that CircleCI needs to address

**Comment by malfet** [comment]
Closing, as our Windows CI have moved to GitHubAction/AWS where we have full control of installed version
