### ISSUE TITLE
sparse_csr_tensor segfaults when crow_indices or col_indices are non-tensors

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56687]
Reproducer (using current master):
```
>>> import torch
>>> crow_indices = [0, 2, 4]
>>> col_indices = [0, 1, 0, 1]
>>> values = [1, 2, 3, 4]
>>> torch.sparse_csr_tensor(torch.tensor(crow_indices, dtype=torch.int64), torch.tensor(col_indices, dtype=torch.int64), values, dtype=torch.double)
tensor(crow_indices=tensor([0, 2, 4]),
       col_indices=tensor([0, 1, 0, 1]),
       values=tensor([1., 2., 3., 4.]), size=(2, 2), nnz=4,
       dtype=torch.float64)
>>> torch.sparse_csr_tensor(crow_indices, col_indices, values, dtype=torch.double)
Segmentation fault (core dumped)
```

The crash likely happens when trying to access `dtype` attribute of a list object:
https://github.com/pytorch/pytorch/blob/81b59211d4b7b959ef65e91e4d0940c86c4273ce/torch/csrc/utils/tensor_new.cpp#L606-L611

cc @aocsa @nikitaved @pearu @mruberry @gchanan

**Comment by aocsa** [comment]
I am working with csr, let me fix this issue

**Comment by aocsa** [comment]
I already solved this issue here:   
https://github.com/pytorch/pytorch/pull/56561#discussion_r618423596

**Comment by aocsa** [comment]
This issue waqs solved here: https://github.com/pytorch/pytorch/pull/59010
