### ISSUE TITLE
counterpart  of numpy.argwhere in torch

### ISSUE THREAD

**Issue by JohnHerry** [pytorch/pytorch#56681]
## ❓ Questions and Help

Is there any operation to torch tensor get filtered by another tensor?
if the item in other tensor, keep it, else delete it.

eg.  assume the operation is named as “item_in”
```
data = torch.Tensor([9,8,7,6,5,4,3,2,1])
filter = torch.Tensor([1,2,15,23,99,100])
result, result_index = data.item_in(filter)
```

 then result = tensor([2,1]),  result_index = tensor([7,8]) because value 2, 1 in data are also in filter

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by ailzhang** [comment]
Please use the forum for questions, thanks!
