### ISSUE TITLE
Incorrect example output in sparse_csr_tensor doc-string

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56685]
The example output in
https://github.com/pytorch/pytorch/blob/81b59211d4b7b959ef65e91e4d0940c86c4273ce/torch/_torch_docs.py#L7916-L7925
is different from the actual output (using current pytorch master):
```
>>> crow_indices = [0, 2, 4]
>>> col_indices = [0, 1, 0, 1]
>>> values = [1, 2, 3, 4]
>>> torch.sparse_csr_tensor(torch.tensor(crow_indices, dtype=torch.int64), torch.tensor(col_indices, dtype=torch.int64), torch.tensor(values), dtype=torch.double)
tensor(crow_indices=tensor([0, 2, 4]),
       col_indices=tensor([0, 1, 0, 1]),
       values=tensor([1., 2., 3., 4.]), size=(2, 2), nnz=4,
       dtype=torch.float64)
```
Notice the lack of `layout` parameter in csr tensor repr result.

cc @brianjo @mruberry @aocsa @nikitaved @pearu

**Comment by mruberry** [comment]
We would definitely accept PRs correcting examples to reflect the current version of PyTorch!
