### ISSUE TITLE
DISABLED test_send_recv_autograd_profiler (__main__.TestMPIWithFork)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#56690]
https://app.circleci.com/pipelines/github/pytorch/pytorch/307565/workflows/009065dd-aa57-4752-918b-26c602d14a14/jobs/12712912

https://app.circleci.com/pipelines/github/pytorch/pytorch/307450/workflows/f4c86a1a-8ad1-4163-9630-355ec9dc97c5/jobs/12708855/steps

```
Apr 22 04:44:00 ======================================================================
Apr 22 04:44:00 FAIL [0.009s]: test_send_recv_autograd_profiler (__main__.TestMPIWithFork)
Apr 22 04:44:00 ----------------------------------------------------------------------
Apr 22 04:44:00 Traceback (most recent call last):
Apr 22 04:44:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 996, in test_send_recv_autograd_profiler
Apr 22 04:44:00     self._test_send_recv(enable_profiling=True)
Apr 22 04:44:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/distributed_test.py", line 981, in _test_send_recv
Apr 22 04:44:00     self.assertEqual(event_count, expected_event_count)
Apr 22 04:44:00   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1371, in assertEqual
Apr 22 04:44:00     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Apr 22 04:44:00 AssertionError: False is not true : Scalars failed to compare as equal! Comparing 1 and 2 gives a difference of 1, but the allowed difference with rtol=0 and atol=0 is only 0!
Apr 22 04:44:00 
Apr 22 04:44:00 ok (0.005s)
```

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment]
This block might be what's causing the profiling flakiness issues: https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler.py#L1254

**Comment by ilia-cher** [comment]
@rohan-varma this is the one that tests profiler over rpc? as discussed we'll remove this functionality, just to confirm

**Comment by rohan-varma** [comment]
@ilia-cher This particular test is actually different, it tests torch.distributed p2p APIs are profiled, it doesn't involve enabling the profiler remotely. The tests for that are in `rpc_test.py`.

**Comment by mrshenli** [comment]
Two more instances. Wondering why this issue didn't disable those tests though.

https://app.circleci.com/pipelines/github/pytorch/pytorch/311990/workflows/2b2fbb72-b613-4986-8842-eccd93e7cdae/jobs/12948992

https://app.circleci.com/pipelines/github/pytorch/pytorch/312185/workflows/1acc0928-0fb6-4472-b415-b324957d49da/jobs/12953722

**Comment by rohan-varma** [comment]
@mrshenli I have a fix for this at https://github.com/pytorch/pytorch/pull/56963

**Comment by rohan-varma** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/57253
