### ISSUE TITLE
Avoid unnecessary creation of tensors in SparseCsrTensorImpl::resize_and_clear_

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56696]
As in title. The issue raised in https://github.com/pytorch/pytorch/pull/50937#discussion_r603536011

Related code:
https://github.com/pytorch/pytorch/blob/76214bb4641fd75fe4ab0e87b05f90462de85fdc/aten/src/ATen/SparseCsrTensorImpl.cpp#L64-L70

cc @aocsa @nikitaved @pearu @mruberry

**Comment by aocsa** [comment]
I am working with csr, let me fix this issue too

**Comment by aocsa** [comment]
This issue was solved here: https://github.com/pytorch/pytorch/pull/59010
