### ISSUE TITLE
torch.distributed: Don't require receive buffers

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#5670]
Why can't the receiver construct receive buffers automatically if one is not provided? That's what we do for all other torch ops.

The sender should send the type and size anyway, so the receiver should be able to automatically create Tensors of the right size if none are provided.

I could implement this on top of the current torch.distributed, but then it would require two roundtrips instead of one.

**Comment by zou3519** [comment]
@adamlerer we're assigning this to you :)
