### ISSUE TITLE
quick-check didn't capture error until PR landed

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#56702]
Seems like quick-check didn't capture trailing whitespace in https://github.com/pytorch/pytorch/pull/55992 

linter passed in https://github.com/pytorch/pytorch/pull/55992/checks?check_run_id=2387172035
until it landed to master in https://github.com/pytorch/pytorch/runs/2409377011

**Comment by samestep** [comment]
Just checked; the reason is because the Facebook-internal diff [D27774396](https://www.internalfb.com/diff/D27774396) did not match the GitHub pull request.

**Comment by walterddr** [comment]
hmm. closing this and follow up internally instead

**Comment by Chillee** [comment]
@walterddr @samestep Huh, my bad. Are the quick-checks run by the external CI not run by the internal CI unless I re-export it?

**Comment by walterddr** [comment]
I dont think internal-CI has similar linter to OSS quick-check. 
That's why we are working on a github export rule to always block land dialog when internal diff and external PR doesn't match. --> which is what happened in this case: internal diff got updated to a new version, then merged to master; but it was never re-exported to PR
