### ISSUE TITLE
Element-wise max of two Tensors computes the wrong gradient in case of equality

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#56734]
It should get a similar treatment as the reduction version of max that evenly splits the gradients for all values that are equal to the maximum.

`min` most likely have the same issue.

Note that these are aliases and so they are actually defined as `maximum` and `minimum` in derivatives.yaml: https://github.com/pytorch/pytorch/blob/6c65ce8ee14faec577582ecd0e17ba436f32c8b3/tools/autograd/derivatives.yaml#L749-L751

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by jbschlosser** [comment]
Seems like the [`torch.amax()`]() docs are aware of this behavior:
```
amax/amin evenly distributes gradient between equal values, while max(dim)/min(dim) propagates gradient only to a single index in the source tensor.
```

**Comment by albanD** [comment]
It is expected for `max(dim)/min(dim)` to have this behavior.
But not for `max(other)/min(other)`.
