### ISSUE TITLE
Notify dev infra team on PR failures that aren't the author's fault

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#56745]
Fairly often, nonessential parts of CI on pull requests fail due to reasons that are not the fault of the PR author. One example is #55810, to which the eventual solution was just to modify the CI job to be very resilient to malformed inputs, and silently finish (succeeding rather than failing) if anything doesn't go as planned. Similar issues happen in the "Report results" step of our test jobs in CircleCI:

- https://app.circleci.com/pipelines/github/pytorch/pytorch/307388/workflows/a945940f-3325-43b3-bc14-c9f885b21f50/jobs/12705944

Allowing these jobs to fail like this creates a poor experience for PR authors, since it is effectively punishing them for the complexity that the dev infra team has created by writing things like `tools/print_test_stats.py`. On the other hand, simply adding a try-catch around these parts of CI isn't a great solution either, since that makes it much harder for the dev infra team to notice and debug these failures when they do occur.

I'm not sure of the best way to approach this in CircleCI, but for GitHub Actions workflows, I propose the following general strategy:

- Add error catching to the job (as we've done in #56071) so that it only fails when the PR author genuinely needs to take some action.
- When an error happens in some of the machinery of the job, set some flag (perhaps an environment variable).
- At the end of the job, check that flag to see if it's set, and if it is, add a comment to the pull request pinging @pytorch/pytorch-dev-infra with links to any important context.

That last step could be implemented as a custom Action that we share among many different jobs, to minimize boilerplate.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
Thanks for reporting the issue @samestep. this occurs to me randomly so I wasn't sure if the particular PR was to blame. I just kicked off a rerun in https://app.circleci.com/pipelines/github/pytorch/pytorch/307388/workflows/a945940f-3325-43b3-bc14-c9f885b21f50/jobs/12752844. But nevertheless it would e great to not report these back as failure on CI signal box

**Comment by walterddr** [comment]
Another example https://app.circleci.com/pipelines/github/pytorch/pytorch/307916/workflows/4144870c-d1cf-4567-a6f8-93bb436471a4/jobs/12732796

**Comment by samestep** [comment]
@walterddr Could you create a separate GitHub issue for that particular XML-parsing failure we've been seeing? It's a separate issue from the general problem of not making CI fail on dev infra issues.

**Comment by seemethere** [comment]
Perhaps this would be a feature request on either Dr. CI or hud.pytorch.org?

**Comment by bigfootjon** [comment]
I'd rather not stick this in Dr. CI. We don't retain logs for non-failed jobs due to scaling constraints, which is where I imagine the ENV variable would be set. We can look into this if necessary, but this is a very custom thing and it might be better to stick it in hud.pytorch.org or probot

**Comment by janeyx99** [comment]
This is something the dev infra team has been working towards with our efforts to improve stability and keep our trunk (master) CI green such as detecting flaky tests and notifying users about ci: sevs on the [HUD](https://hud.pytorch.org/ci/pytorch/pytorch/master). We have an on-call who looks out for flakiness and we are adding alerts to streamline that process. I think it is okay to close this issue and redirect to our investments tracked in https://github.com/pytorch/pytorch/issues/65439 and our general devX project [here](https://github.com/orgs/pytorch/projects/15/views/1?layout=board).
