### ISSUE TITLE
../torch/csrc/cuda/comm.cpp:18:20: fatal error: optional: No such file or directory

### ISSUE THREAD

**Issue by wwchung91** [pytorch/pytorch#56749]
## 🐛 Bug

../torch/csrc/cuda/comm.cpp:18:20: fatal error: optional: No such file or directory
Can't find optional in comm.cpp. 
I think there are two include statements. 
There is
 #include <c10/util/Optional.h>
and 
#include <Optional.h>

Can't find #include<Optional.h> 

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @seemethere @walterddr

**Comment by ezyang** [comment]
Looks like this file is incorrectly including optional even though it's not supposed to
