### ISSUE TITLE
torch.stack performance isn't good

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#56758]
## 🐛 Bug

torch.stack takes much more time than tf.stack

## To Reproduce

Run the attached side by side scripts in Linux.
The code doesn't use GPU.

## Expected behavior

For single operator, the performance shouldn't be much slower.

## Environment

In my machine, PT(1.8.1 ) script   takes 17.29 s, TF(2.4.1) script takes 8.65s

Collecting environment information...
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.15.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi

[stack_tf.py.txt](https://github.com/pytorch/pytorch/files/6362244/stack_tf.py.txt)
[stack_pt.py.txt](https://github.com/pytorch/pytorch/files/6362246/stack_pt.py.txt)

cc @VitalyFedyunin @ngimel

**Comment by mszhanyi** [comment]
I found this when investigating #55037

**Comment by ZailiWang** [comment]
I had a test on an old and new PyTorch versions on the same machine (Intel XEON Gold)
PyTorch 1.7.1: 6.5744 s
PyTorch 1.13.0: 0.2541 s
(BTW, TF 2.10.0 result on the same machine is 4.5311 s)

So stack op has been optimized in a recent PyTorch release and now outperformed TF.
