### ISSUE TITLE
Let RNN modules handle hidden_size = 0

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#56767]
## 🚀 Feature

Let [`RNNBase.reset_parameters`](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L194) and [`RNNCellBase.reset_parameters`](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py#L885) handle `hidden_size = 0`. Currently, they contain the line
```python3
stdv = 1.0 / math.sqrt(self.hidden_size)
```
which causes a `ZeroDivisionError`:
```python3
import torch

i_size = 10
h_size = 0
cell = torch.nn.GRUCell(i_size, h_size)

i = torch.rand(32, i_size)
h = torch.rand(32, h_size)
h_next = cell(i, h)
```
(Note that letting `i_size = 0` instead works fine.)

## Motivation

See #48152.

Example: Hyperparameters of a [PODMP](https://en.wikipedia.org/wiki/Partially_observable_Markov_decision_process) policy. Markovian (memoryless) policies are subsumed by `h_size = 0`. No additional refactoring or special casing required.

## Pitch

Change the above to something like
```python3
stdv = 1 / math.sqrt(self.hidden_size) if self.hidden_size > 0 else 0
```
as was done in #56505.

cc @zou3519

**Comment by cpuhrsch** [comment]
cc @jbschlosser
