### ISSUE TITLE
Activation doc image broken

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#5677]
e.g. http://pytorch.org/docs/master/nn.html#torch.nn.ELU

@pmitros

**Comment by pmitros** [comment]
Hmmm... It works fine locally. I have time to debug or help out over this weekend, but I'm not quite sure how. I don't really understand (or likely have access to) the deployment infrastructure which builds to pytorch.org. If you have any pointers, or know of a way I can do to help out, please let me know.

**Comment by vadimkantorov** [comment]
also issues with http://pytorch.org/docs/master/nn.html?highlight=shrink#torch.nn.functional.tanhshrink and http://pytorch.org/docs/master/nn.html?highlight=shrink#torch.nn.Softshrink https://github.com/pytorch/pytorch/issues/4819

**Comment by SsnL** [comment]
reopen as apparently it is still broken :/

**Comment by SsnL** [comment]
Fixed on master!
