### ISSUE TITLE
Failing test on arm64 version of macOS and python 3.9.4

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#56779]
This issue is to track all the failing tests and progress towards fixing them.

All the following tests need to be disabled from run_test.py for it to run to completion.
Note that some failures might be trivial issues or due to python / numpy version.

You can add your name next to any of these if you plan to work on fixing any of these tests.

- [x] test_binary_ufuncs (@albanD looking into it)
- [ ] test_cpp_api_parity
- [ ] test_cpp_extensions_jit
- [ ] test_dataloader
- [ ] test_datapipe
- [ ] distributions/test_constraints
- [ ] distributions/test_distributions
- [ ] test_expecttest
- [x] test_linalg ( https://github.com/pytorch/pytorch/pull/56847 should fix it and failure is not specific to M1)
- [x] test_nn
- [x] test_ops
- [ ] test_quantization (Should be fixed by #60079)
- [x] test_unary_ufuncs (Fixed by #59858, #59832 and #59361)
- [x] test_utils
- [ ] test_fx
- [x] test_functional_autograd_benchmark
- [ ] test_license
- [x] test_autograd
- [ ] distributed/pipeline/sync/skip/test_api
- [ ] distributed/pipeline/sync/skip/test_gpipe
- [ ] distributed/pipeline/sync/skip/test_inspect_skip_layout
- [ ] distributed/pipeline/sync/skip/test_leak
- [ ] distributed/pipeline/sync/skip/test_portal
- [ ] distributed/pipeline/sync/skip/test_stash_pop
- [ ] distributed/pipeline/sync/skip/test_tracker
- [ ] distributed/pipeline/sync/skip/test_verify_skippables
- [ ] distributed/pipeline/sync/test_balance
- [ ] distributed/pipeline/sync/test_bugs
- [ ] distributed/pipeline/sync/test_checkpoint
- [ ] distributed/pipeline/sync/test_copy
- [ ] distributed/pipeline/sync/test_deferred_batch_norm
- [ ] distributed/pipeline/sync/test_dependency
- [ ] distributed/pipeline/sync/test_inplace
- [ ] distributed/pipeline/sync/test_microbatch
- [ ] distributed/pipeline/sync/test_phony
- [ ] distributed/pipeline/sync/test_pipe
- [ ] distributed/pipeline/sync/test_pipeline
- [ ] distributed/pipeline/sync/test_stream
- [ ] distributed/pipeline/sync/test_transparency
- [ ] distributed/pipeline/sync/test_worker
- [ ] distributed/optim/test_zero_redundancy_optimizer

testing environment:
```
% python ../torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.9.0a0+git399b66c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.3 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.20.1

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0.dev0+1229.g36eb76c9d
[pip3] torch==1.9.0a0+gite3900d2
[conda] Could not collect
```

```
% python -m pip freeze
attrs==20.3.0
hypothesis==6.10.0
iniconfig==1.1.1
ninja==1.10.0.post2
numpy==1.21.0.dev0+1229.g36eb76c9d
packaging==20.9
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pytest==6.2.3
PyYAML==5.4.1
sortedcontainers==2.3.0
toml==0.10.2
-e git+git@github.com:pytorch/pytorch.git@e3900d2ba5c9f91a24a9ce34520794c8366d5c54#egg=torch
typing-extensions==3.7.4.3
```

cc @malfet

**Comment by malfet** [comment]
FYI @albanD `test_binary_ops` passes on my M1 after all fixes for test_unary_ops applied to the trunk

**Comment by lokinfey** [comment]
But We need to support GPU version in M1 machine

**Comment by albanD** [comment]
This is actually quite stale at this point. When we go back to this, we should open a new issue to track progress.
