### ISSUE TITLE
Support broadcasting for clip / clamp

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#56785]
## 🚀 Feature

The current implementation of `torch.clip` / `torch.clamp` only accepts scalars for `min` and `max` arguments. However, the NumPy versions of these functions support `ndarray` arguments for `min` and `max` when broadcastable with the input tensor.

The underlying implementation mimics `torch.min(torch.max(x, max_limit), min_limit)`, which supports broadcasting, so it would nice if `torch.clip` and `torch.clamp` supported this as well.

### Use Case

Consider an input tensor `x` of shape `... x d`, where `d` is the dimension of the input (`x` can be thought of as a batched input). Every dimension `i` in `{1 ,2 ... d}` has it's own bound constraint (`l_i <= x_i <= u_i`). To project this batched input to a feasible set defined by the bound constraints (a box in `d` dimensions), we could use the `torch.clip` functionality as `torch.clip(x, min=lower_bounds, max=upper_bounds)`, where `lower_bounds` and `upper_bounds` are `d` length vectors.

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
cc @peterbell10, who's updating clamp now

**Comment by vishwakftw** [comment]
Oh great, thanks for the update @mruberry and for implementing it @peterbell10 !
