### ISSUE TITLE
[numpy] BC-breaking floor_divide in np>=1.20.0 lets binary_ufuncs tests fail

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#56814]
## 🐛 Bug

Since `numpy>=1.20.0`, `np.floor_divide` returns now `Infs` for `np.floor_divide` instead of `Nan`s in previous versions.
[Numpy release notes](https://numpy.org/doc/stable/release/1.20.0-notes.html#changed-behavior-of-divmod-1-0-and-related-functions) explain these changes.

This lets a few `binary_ufuncs` tests fail, as PyTorch uses the "old" numpy behavior, i.e. returning `Nan`s.

In particular we've isolated these failing tests:
```python
test_div_rounding_nonfinite_cuda_bfloat16 (__main__.TestBinaryUfuncsCUDA)
test_div_rounding_nonfinite_cuda_float16 (__main__.TestBinaryUfuncsCUDA)
test_div_rounding_nonfinite_cuda_float32 (__main__.TestBinaryUfuncsCUDA)
test_div_rounding_nonfinite_cuda_float64 (__main__.TestBinaryUfuncsCUDA)
test_div_rounding_numpy_cuda_float16 (__main__.TestBinaryUfuncsCUDA)
```
which fail with:
```python
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.016 and atol=1e-05, found 8 element(s) (out of 100) whose difference(s) exceeded the margin of error (including 8 nan comparisons). The greatest difference was nan (nan vs. inf), which occurred at index (2, 0).
```

## To Reproduce

Install `numpy==1.20.1` and run:
```python
python test_binary_ufuncs.py -v -k test_div_rounding_nonfinite_cuda_bfloat16
```
In `numpy==1.19.2` the `expect` array contained:
```python
expect for <ufunc 'floor_divide'>: 
[[  1.  -1.   0.   0.  -1.   3.  -4.  nan  nan  nan]
 [ -1.   1.  -0.  -1.   0.  -4.   3.  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
 [  9. -10.   0.   1.  -1.  31. -32.  nan  nan  nan]
 [-10.   9.  -0.  -1.   1. -32.  31.  nan  nan  nan]
 [  0.  -1.   0.   0.  -1.   1.  -1.  nan  nan  nan]
 [ -1.   0.  -0.  -1.   0.  -1.   1.  nan  nan  nan]
 [  0.  -1.   0.   0.  -1.   0.  -1.  nan  nan  nan]
 [ -1.   0.  -0.  -1.   0.  -1.   0.  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]
```
while `numpy==1.20.1` uses:
```python
expect for <ufunc 'floor_divide'>: 
[[  1.  -1.   0.   0.  -1.   3.  -4.  nan  nan  nan]
 [ -1.   1.  -0.  -1.   0.  -4.   3.  nan  nan  nan]
 [ inf -inf  nan  inf -inf  inf -inf  inf -inf  nan]
 [  9. -10.   0.   1.  -1.  31. -32.  nan  nan  nan]
 [-10.   9.  -0.  -1.   1. -32.  31.  nan  nan  nan]
 [  0.  -1.   0.   0.  -1.   1.  -1.  nan  nan  nan]
 [ -1.   0.  -0.  -1.   0.  -1.   1.  nan  nan  nan]
 [  0.  -1.   0.   0.  -1.   0.  -1.  nan  nan  nan]
 [ -1.   0.  -0.  -1.   0.  -1.   0.  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]
```

Reproduced in source builds as well as the `1.8.1` binary using different numpy versions.

I'm not sure, if PyTorch should move to this BC-breaking behavior or work around this issue.

CC @mruberry 

Let me know, if you need more information. 

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
Thanks for filing this issue @ptrblck! @rgommers and I should review incorporating the latest NumPy changes.

I imagine we can just change the behavior of our division operators to account for this change without issue; users are not typically sensitive to how we handle extremal values like this.

Whether we fix this or not, however, we'll still need to update the tests to account for the NumPy version. Currently they can be skipped if the NumPy version is too high. If we update the division behavior then a new division reference will need to be developed to handle older NumPy versions, or the tests will need to be skipped on those older versions.

I think we would accept a PR updating the division behavior. We should be careful to update it across all the division operators for consistency.

**Comment by rgommers** [comment]
Cc @peterbell10 who has 4 PRs updating `floor_divide` open.
