### ISSUE TITLE
[numpy] TestFFT fails in np>=1.20.1 in `forward` mode

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#56820]
## 🐛 Bug

FFT tests start to fail in `numpy>=1.20.1` on CPU and CUDA.

In particular we've isolated these failing tests:
```python
test_reference_nd_fft_ifftn_cuda_complex64 (__main__.TestFFTCUDA)
test_reference_nd_fft_ifftn_cuda_float32 (__main__.TestFFTCUDA)
test_reference_nd_fft_irfftn_cuda_complex64 (__main__.TestFFTCUDA)
test_reference_nd_fft_irfftn_cuda_float32 (__main__.TestFFTCUDA)
```
which fail with small numerical errors:
```python
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the real part -0.5864181518554688 and -0.5864326355324252 gives a difference of 1.4483676956444924e-05, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 1.0762362426192154e-05!
```
using `numpy>=1.20.1`, while `numpy==1.19.2` lets these tests pass.
Note that the corresponding CPU tests also fail using the newer numpy version and work in the older one.

## To Reproduce

Install `numpy==1.20.1` and run:

```python
python test_spectral_ops.py -v -k test_reference_nd_fft_ifftn_cpu_complex64

======================================================================
FAIL: test_reference_nd_fft_ifftn_cpu_complex64 (__main__.TestFFTCPU)
----------------------------------------------------------------------
[...]
AssertionError: False is not true : Scalars failed to compare as equal! Comparing the imaginary part 1.1501693725585938 and 1.1501473133785112 gives a difference of 2.2059180082578678e-05, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 1.1495191507392065e-05!
```

We are currently unsure about the root cause, as nothing obvious points to this behavior in the [numpy release notes](https://numpy.org/doc/stable/release/1.20.0-notes.html).
We thought that a wrong `dtype` might be used:
```
The deprecation of numeric style type-codes np.dtype("Complex64") (with upper case spelling), is expired. "Complex64" corresponded to "complex128" and "Complex32" corresponded to "complex64".
```
but couldn't narrow it down to this usage so far.

We reproduced it on two different machines with source builds as well as the `1.8.1` binary and confirmed that `numpy==1.19.2` lets the test pass, while `numpy==1.20.1` fails it.

Let me know, if you need more information and a reproduction would be appreciated to confirm it on other machines.

cc @mruberry @peterbell10 @walterddr @rgommers @heitorschueroff

**Comment by ptrblck** [comment]
Update: I missed an important note:
Numpy might not have introduced larger numerical errors in these tests, but additional tests are used in `>=1.20.0` as described [here](https://github.com/pytorch/pytorch/blob/0424f6af9391857272b768e032e226629ff01762/test/test_spectral_ops.py#L254-L256):
```python
    def test_reference_nd(self, device, dtype, op):
        norm_modes = ((None, "forward", "backward", "ortho")
                      if LooseVersion(np.__version__) >= '1.20.0'
                      else (None, "ortho"))
```
The failures are caused by (at least) the usage of `mode="forward"` in some configs.
I'll update the title.

**Comment by mruberry** [comment]
@peterbell10 would you take a look? Maybe we need to adjust some tolerances?
