### ISSUE TITLE
torch.lstsq returns wrong tensor size

### ISSUE THREAD

**Issue by mlizhardy** [pytorch/pytorch#56833]
I have a A = 10 x 6  source tensor, and a b = 10 x 1 destination tensor.  
I want to solve for x such that Ax = b.  x should be a 6 x 1 tensor.

when I code:

```
import torch

A = torch.ones((10,6))
b = torch.ones((10,1))
M, _ = torch.lstsq(b, A)
print(M.shape)

```

prints: torch.Size([10, 1])

This is not how math works. How do I get the proper 6 x 1 output tensor?

**Comment by nailimixaM** [comment]
I believe the answer is in the [docs](https://pytorch.org/docs/stable/generated/torch.lstsq.html):  

In short, for mxn tensor A and mx1 tensor b, the returned tensor is max(m, n) x 1. For m>n as in your case, the first n elements of the returned tensor are what you expect, and the last m-n elements are the residual copied m-n times.

Code:
```
import torch

# Solve for x in Ax = b 
m = 10
n = 6
A = torch.ones((m,n))
b = torch.ones((m,1))
M, _ = torch.lstsq(b, A)
x = M[:n]
```

**Comment by mlizhardy** [comment]
thank you!
