### ISSUE TITLE
who can support MobileNetV2_1.4x weight, ShuffleNetV2_1.5x and ShuffleNetV2_2x ? 

### ISSUE THREAD

**Issue by xiaolangwork** [pytorch/pytorch#56858]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
- who can support MobileNetV2_1.4x weight, ShuffleNetV2_1.5x and ShuffleNetV2_2x ?  I haven't more GPUs, so I can't to training it. If you can provide it ,thank you very much.

**Comment by H-Huang** [comment]
Please post questions on discussion forum, thank you!
