### ISSUE TITLE
CSR invariant crow_indices[-1] == nnz is not forced by sparse_csr_tensor

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56856]
As in title. Here is a reproducer (using the current master branch):
```
>>> torch.sparse_csr_tensor(torch.tensor([0, 0, 0]), torch.tensor([1, 2, 0]), torch.tensor([1, 2, 3]))
tensor(crow_indices=tensor([0, 0, 0]),
       col_indices=tensor([1, 2, 0]),
       values=tensor([1, 2, 3]), size=(2, 3), nnz=3)
```
The expected behaviour is an exception because the CSR format invariant `crow_indices[-1] == nnz` is invalid in this example.

cc @aocsa @nikitaved @pearu @mruberry @gchanan

**Comment by mruberry** [comment]
We would definitely accept a PR fixing this

**Comment by pearu** [comment]
For the proof of the invariant, see https://github.com/pytorch/pytorch/pull/56392#discussion_r620042454

**Comment by aocsa** [comment]
This issue was solved here https://github.com/pytorch/pytorch/pull/59010
