### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by mgoliyad1** [pytorch/pytorch#56874]
## 🐛 Bug

Hi!
my GPU is Tesla K20 so I was told to build pytorch from source. I have followed all instructions but build failed.

Please find attached log file.
[log.txt](https://github.com/pytorch/pytorch/files/6370564/log.txt)

I tried CUDA 11.1 and 102 and got the same results. 

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows Server 2019 Standard
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.20.1

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla K20c
Nvidia driver version: 456.81
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           haa95532_296
[conda] mkl-include               2021.2.0           haa95532_296
[conda] mkl-service               2.3.0            py37h2bbff1b_1
[conda] mkl_fft                   1.3.0            py37h277e83a_2
[conda] mkl_random                1.2.1            py37hf11a4ad_2
[conda] numpy                     1.20.1           py37h34a8a5c_0
[conda] numpy-base                1.20.1           py37haf7ebc8_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1

**Comment by peterjc123** [comment]
@mgoliyad1 You are using a VS version that we don't currently support. Please try downgrading VS (uninstall the current one and re-install an older one) or installing an older mini-toolchain side by side. FYI, our CI uses VS 16.8.

**Comment by skyline75489** [comment]
See also: #54382

**Comment by mgoliyad1** [comment]
@peterjc123 Thanks a lot! I have downgraded to 16.7 and build worked.
