### ISSUE TITLE
Calculating gradient with frozen layers

### ISSUE THREAD

**Issue by scellat** [pytorch/pytorch#56876]
Hi,

I have trained a transformer model with some of the layers frozen. 
I used the following code to freeze the layers during training.

```
      for layer_idx in layer_indices:
          for param in list(transformer.encoder.layer[layer_idx].parameters()):
              param.requires_grad = False
```

Training runs fine and when I check the trained model object, the layers I freeze indeed shown as frozen. However, when I try to calculate the gradients with `torch.autograd.grad` during inference time, I get the following error:

`RuntimeError: One of the differentiated Tensors does not require grad
`

When I calculate the gradients without any freezing `torch.autograd.grad` function works just fine.

How do I go about calculating gradients when some of the layers are set to `requires_grad=False`?

**Comment by SsnL** [comment]
`. requires_grad` attributes affects what is tracked (and which intermediate result for backprop is stored) when **forwarding**. So you need to flip it on before **forwarding** if you want gradient wrt it. If you simply want your optimizer to ignore that layer, you can exclude it when creating the optimizer, or emptying the `.grad` attribute.

**Comment by scellat** [comment]
Thanks for the reply. Does that mean I can only calculate the gradients when the optimizer is set to ignore those layers? I have already trained the model, is there any way to bypass that?

**Comment by SsnL** [comment]
well.. you can flip the `.requires_grad` to be true again.

**Comment by scellat** [comment]
I had already tried that but that returns None for the gradients:/. Anyhow, thanks for the reply
