### ISSUE TITLE
caffe2_detectron_ops_gpu.dll makes import torch occur OSerror，[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mr0jue** [pytorch/pytorch#56884]
## To Reproduce
1. create conda virtual environment 
2. install pytorch via conda :
"conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge"
3. open jupyter notebook & "import torch"

Then, I got this
'''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\pt181\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading 
'''
refer to https://github.com/pytorch/pytorch/issues/46592. using WinDbg, I got this:
'''
......
0f98:07f0 @ 265789453 - LdrpSearchPath - ENTER: DLL name: cusolver64_11.dll
0f98:07f0 @ 265789453 - LdrpResolveDllName - ENTER: DLL name: C:\ProgramData\Anaconda3\envs\pt181\lib\site-packages\torch\lib\cusolver64_11.dll
0f98:28c8 @ 265789453 - LdrpProcessWork - ERROR: Unable to load DLL: "cublas64_11.dll", Parent Module: "C:\ProgramData\Anaconda3\envs\pt181\lib\site-packages\torch\lib\torch_cuda_cpp.dll", Status: 0xc000007b
ModLoad: 00007ffa`34660000 00007ffa`5dae9000   C:\ProgramData\Anaconda3\envs\pt181\Library\bin\cusolver64_11.dll
0f98:07f0 @ 265789453 - LdrpResolveDllName - RETURN: Status: 0xc0000135
0f98:07f0 @ 265789453 - LdrpResolveDllName - ENTER: DLL name: C:\ProgramData\Anaconda3\envs\pt181\cusolver64_11.dll
0f98:57e8 @ 265789453 - LdrpMinimalMapModule - RETURN: Status: 0x00000000
0f98:57e8 @ 265789453 - LdrpFindDllActivationContext - INFO: Probing for the manifest of DLL "C:\ProgramData\Anaconda3\envs\pt181\Library\bin\cusolver64_11.dll" failed with status 0xc000008a
0f98:07f0 @ 265789453 - LdrpResolveDllName - RETURN: Status: 0xc0000135
0f98:07f0 @ 265789453 - LdrpResolveDllName - ENTER: DLL name: C:\ProgramData\Anaconda3\envs\pt181\Library\bin\cusolver64_11.dll
0f98:57e8 @ 265789453 - LdrpProcessWork - ERROR: Unable to load DLL: "cusolver64_11.dll", Parent Module: "C:\ProgramData\Anaconda3\envs\pt181\lib\site-packages\torch\lib\torch_cuda_cpp.dll", Status: 0xc000007b
0f98:07f0 @ 265789453 - LdrpResolveDllName - RETURN: Status: 0x00000000
......
'''
--Only the Error section is pasted--
It looks like there are somthing wrong with cudatoolkit in my virtual environment.
BTW, I already have 'cublas64_11.dll' & 'cusolver64_11.dll' in 'C:\ProgramData\Anaconda3\pkgs\cudatoolkit-11.1.1-heb2d755_7\Library\bin' & 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin', Apparently, they didn't work, orz.
Then I uninstall and reinstall pytorch via conda. Also delete files or folders that begin with 'cudatoolkit '/'torch'/'pytorch'  in 'C:\ProgramData\Anaconda3\pkgs'. It didn't work.

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 466.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

In fact:
Python version: 3.7.9
PyTorch version: 1.8.1

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mr0jue** [comment]
I copied all the files in 'C:\ProgramData\Anaconda3\pkgs\cudatoolkit-11.1.1-heb2d755_7\Library\bin' to 'C:\ProgramData\Anaconda3\envs\pt181\Lib\site-packages\torch\lib', Then, the BUG was fixed.
I think there's a problem either the installation of cudatoolkit or the __init__.py file in Pytorch.

**Comment by peterjc123** [comment]
@mr0jue Have you checked the directories like `C:\ProgramData\Anaconda3\Library\bin` & `C:\ProgramData\Anaconda3\envs\pt181\Library\bin`? Normally, we won't check for the directories under `pkgs`.

**Comment by peterjc123** [comment]
Looking into the log, it seems that loading `C:\ProgramData\Anaconda3\envs\pt181\Library\bin\cusolver64_11.dll` throws the error "OSError: [WinError 193] %1 不是有效的 Win32 应用程序". So maybe this DLL is corrupted during installation. Does reinstalling the `cudatoolkit` package help?

**Comment by peterjc123** [comment]
I tried to reproduce the error but failed. Here is what I have done.
```py
conda create -n py37 python=3.7
conda activate py37
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
python -c "import torch"
```

**Comment by mr0jue** [comment]
> @mr0jue你检查过目录了吗？通常，我们不会检查目录下，因为它们只是安装缓存，而不是安装的缓存。`C:\ProgramData\Anaconda3\Library\bin``C:\ProgramData\Anaconda3\envs\pt181\Library\bin``pkgs`

Thank you for reply.
Yes, I known that, they are only the install cache. I deleted and redownloaded those '.tar.bz2' & '.conda' because I throught they may corrupted.
I have checked the directories,  'C:\ProgramData\Anaconda3\envs\pt181\lib\site-packages\torch\lib\' &
'C:\ProgramData\Anaconda3\envs\pt181\Library\bin' & 
'C:\ProgramData\Anaconda3\envs\pt181\', which were mentioned in WinDbg`s log. neither of them have cublas64_11.dll or cusolver64_11.dll or other DLLs related to cuda.
I tried again. Creating a new conda virtual env and install pytorch(py=3.7.10). The error dosen`t show again, every thing works fine.
 I`m bit confused about it. [doge]
BTW,in the same env,  it won`t raise any error when I run the code of pytorch`s '__init__.py' in jupyter notebook.

**Comment by peterjc123** [comment]
CUDA DLLs should exist in `C:\ProgramData\Anaconda3\envs\pt181\Library\bin` since I can see them in `[my conda root]\envs\py37\Library\bin`.

> BTW,in the same env, it won`t raise any error when I run the code of pytorch`s '**init**.py' in jupyter notebook.

That's pretty weird. If you still have the env, maybe you can share the logs of the DLL loading in jupyter notebook.

**Comment by mr0jue** [comment]
> CUDA DLLs should exist in `C:\ProgramData\Anaconda3\envs\pt181\Library\bin` since I can see them in `[my conda root]\envs\py37\Library\bin`. If you cannot see them, then it is actually using the one from your system installation.
> 
> > BTW,in the same env, it won`t raise any error when I run the code of pytorch`s '**init**.py' in jupyter notebook.
> 
> That's pretty weird. If you still have the env, maybe you can share the logs of the DLL loading in jupyter notebook.

Weird. I can't reproduce the bug anymore since I fixed it.
I remember that when I installed the environment where this bug occurred, the log flashed some information as if the installer did not have permission to modify the files.

**Comment by mr0jue** [comment]
I repeated all the steps to reproduce the bug.

1. conda create -n py37 python=3.7.9
2. conda activate py37
3. conda install ipykernel
4. python -m ipykernel install --name py37 --display-name "py37" 
5. pip install fuzzywuzzy==0.17.0 pytorch-pretrained-bert==0.6.2 tqdm==4.24.0 records
6. conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
7. open jupyter & import torch

Then I got this: 
'内核似乎挂掉了，它很快将自动重启。(Kernel Restarting The kernel appears to have died. It will restart automatically. )' & 'Key already registered with the same priority: GroupSpatialSoftmax'.
I think it was a conflict between the PIP install Torch (Rerequired by PyTorch-PreTrained-Bert) and the Conda install PyTorch.

So, I did the following:
1. pip unisntall torch 
2. conda unisntall pytorch 
3. conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
4. restart jupyter & import pytorch

Then I got this:
ImportError
...
	from numpy.core._multiarray_umath import (
		add_docstring, implement_array_function, _get_implementing_args)
ImportError: DLL load failed: 找不到指定的模块。

So, I did the following:
1. pip uninstall numpy
2. delete the folder: 'C:\ProgramData\Anaconda3\envs\py37\Lib\site-packages\numpy-1.20.2.dist-info'
3. pip install numpy
4. restart jupyter & import pytorch

Import successed
That's pretty weird. In the last time, it raise [WinError 193] .
I repeated all the steps (that I can remember) to reproduce the bug. I can't reproduce the bug anymore since I fixed it.

Conclusion: (most likely) 
1. there was a conflict between the PIP install Torch and the Conda install PyTorch.
2. the downloaded link is unstable and the downloaded installer is corrupt.

Pytorch is fine.
