### ISSUE TITLE
How do I convert the quantified model to onnx or ncnn？

### ISSUE THREAD

**Issue by fucker007** [pytorch/pytorch#56898]
### how to convert int8 model in pytorch to onnx. 
I train a model with quantization aware train in pytorch,  however I need use quantizated model to onnx, I have tried, but normal code is not work. Any bady can help me, thanks a lot.
@eklitzke @dreiss @huitseeker @jfsantos  bug for guidance

**Comment by H-Huang** [comment]
Can you try posting this question on the [PyTorch discussion forums](https://discuss.pytorch.org/), thank you!
