### ISSUE TITLE
Kineto dependency CUPTI detection should use standard cmake mechanisms

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#56890]
## 🐛 Bug

The kineto-dependency configuration does not use standard cmake facilities to find include and library for CUPTI but instead hardcodes a few paths. This means that as soon as the file location differs from what is hardcoded, finding cupti fails. This can happen when CUPTI is actually present and is even detected by the general cuda dependency.
(For obscure reason I have arch triples in the library path and CUPTI is in my CMAKE_INCLUDE_PATH but not in the location where the PyTorch Kineto build-configuration looks.)

Also, it seems that there may be cases where the kineto checks fail to override a .so that is found but a .a would be nicer (but I'm not exactly sure about it).

## The culprit

https://github.com/pytorch/pytorch/blob/e97c17afa0c52f32f151729864bec87de32d5a90/cmake/Dependencies.cmake#L1858-L1874

This probably would work better if it used find_path for the include and find_library for the library.

## To Reproduce

Try to build with kineto on Debian/Ubuntu with CUDA from Debian's non-free package repository.

## Expected behavior

The CMake mechanisms for include/library discovery should work, including to override locations (e.g. CMAKE_INCLUDE_PATH).

## Environment

PyTorch master, CUDA from Debian/Ubuntu-shipped packages.

cc @malfet @seemethere @walterddr @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by malfet** [comment]
@t-vi thank you for reporting. If you already have a fix in mind, please do not hesitate to turn it into PR.
@ilia-cher do you mind having a look?

**Comment by ngimel** [comment]
find_package(CUDA) sets CUDA_cupti_LIBRARY.

**Comment by ilia-cher** [comment]
Thanks for reporting, yes we should update to use the standard cmake utilities

**Comment by t-vi** [comment]
I think this is obsolete with #57789
