### ISSUE TITLE
Inconsistent reporting of layout in str result of COO and CSR tensors

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56906]
## Issue description

As in title.

## Code example

When using the current master:
```
>>> import torch
>>> t = torch.tensor([[0, 1, 0], [2, 0, 3]])
>>> t.to_sparse()
tensor(indices=tensor([[0, 1, 1],
                       [1, 0, 2]]),
       values=tensor([1, 2, 3]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)
>>> t.to_sparse_csr()
tensor(crow_indices=tensor([0, 1, 3]),
       col_indices=tensor([1, 0, 2]),
       values=tensor([1, 2, 3]), size=(2, 3), nnz=3)
```

Notice that the CSR tensor str output does not include `layout` value.
The issue is also related to https://github.com/pytorch/pytorch/issues/56685 .

## Discussion

Following COO tensor convention, the expected result would be:
```
>>> t.to_sparse_csr()
tensor(crow_indices=tensor([0, 1, 3]),
       col_indices=tensor([1, 0, 2]),
       values=tensor([1, 2, 3]),
       size=(2, 3), nnz=3, layout=torch.sparse_csr)
```
One might argue that the `layout` output is superfluous in the COO tensor str output:
- no layout is reported in strided tensor str output
- the layout is obvious from the output content: COO has indices/values, CSR has crow_indices/col_indices/values properties.

However, as witnessed in the case of COO and CSR tensors, some properties are shared (e.g. `values`) in between different layouts. Hence, there is a risk that the tensor layout (of some format to be introduced in future) cannot be derived from the str output. So, I would recommend always include the `layout` property in tensor str output, except for the strided tensor case (due to BC). What do you think?

cc @aocsa @nikitaved @pearu @mruberry

**Comment by mruberry** [comment]
Including the layout for sparse tensors seems OK, if not urgent.

**Comment by aocsa** [comment]
I agree with the idea of always include the layout property for the sparse tensor. If so, note that this issue is cover in this PR https://github.com/pytorch/pytorch/pull/56722

**Comment by gchanan** [comment]
Isn't the str (repr?) supposed to be executable code (or close to it?).

**Comment by pearu** [comment]
> Isn't the str (repr?) supposed to be executable code (or close to it?).

`str(obj)` output can be anything. Ideally, `repr(obj)` should give a string that can be evaluated (say, using `eval`) to an object that is equivalent to `obj`. Although, in practice, the ideal output of `repr` is rarely implemented for custom types, and almost never mapped through `eval/exec` to construct custom objects. I think any convention is ok, as long as it is used consistently.

@gchanan, are you saying that we should aim at an ideal `repr` output? For instance:
```
>>> t.to_sparse()
sparse_coo_tensor(indices=tensor([[0, 1, 1],
                                  [1, 0, 2]], dtype=int64),
                  values=tensor([1, 2, 3], dtype=int64),
                  size=(2, 3))
```
? Is so, I think this should be discussed in a separate issue because the question is about how much PyTorch should follow pure Python style in general and what deviations would be allowed.

**Comment by aocsa** [comment]
This issue was closed here: https://github.com/pytorch/pytorch/pull/59010
