### ISSUE TITLE
Forum cannot open.

### ISSUE THREAD

**Issue by LaiPiXiong** [pytorch/pytorch#5690]
Forum http://discuss.pytorch.org/ shows NOT FOUND. Any other Links?

**Comment by sonack** [comment]
@LaiPiXiong  I can open it

**Comment by LCAR979** [comment]
@LaiPiXiong The forum is blocked by GFW. @sonack. The website is working fine.

**Comment by LaiPiXiong** [comment]
@sonack @LCAR979 Oh, thanks a lot.
