### ISSUE TITLE
Exporting the operator outer to ONNX opset version 13 is not supported.

### ISSUE THREAD

**Issue by krishnanNuance** [pytorch/pytorch#56905]
## 🚀 Feature

Trying to export pytorch transformer based model to onnx. Currently the 'outer' operator is not supported. 

## Pitch

The operator 'outer' should be supported for onnx exportation.

## Additional context

I am currently using,
Torch Version: 1.8.1+cu102
ONNX Version: 1.9.0
Opset version : 13

I get the following error while exporting fairseq transformer XL model to onnx

```
opname = 'outer', domain = '', version = 13

    def get_registered_op(opname, domain, version):
        if domain is None or version is None:
            warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
        global _registry
        if not is_registered_op(opname, domain, version):
            msg = "Exporting the operator " + opname + " to ONNX opset version " + str(version) + " is not supported. "
            supported_version = get_op_supported_version(opname, domain, version)
            if supported_version is not None:
                msg += "Support for this operator was added in version " + str(supported_version) + ", try exporting with this version."
            else:
                msg += "Please feel free to request support or submit a pull request on PyTorch GitHub."
>           raise RuntimeError(msg)
E           RuntimeError: Exporting the operator outer to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

venv/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py:116: RuntimeError 
```

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment]
@krishnanNuance I think your CC list didn't work because you included it in the code block

**Comment by krishnanNuance** [comment]
> @krishnanNuance I think your CC list didn't work because you included it in the code block

Hi @garymm ,
I didn't complete get your point. Can you point me to the section of the code that needs to be adapted?

**Comment by garymm** [comment]
This is not code, but you included it in the code block:

`cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity`

So GitHub did not interpret it as mentioning users as you intended.

**Comment by krishnanNuance** [comment]
> This is not code, but you included it in the code block:
> 
> `cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity`
> 
> So GitHub did not interpret it as mentioning users as you intended.

ah ok! That wasn't me.. it was the pytorch bot.. I have corrected it.

**Comment by BowenBao** [comment]
@krishnanNuance outer should be supported via #54869, closing.
