### ISSUE TITLE
Could not find a version that satisfies the requirement torch==1.8.1+cu102

### ISSUE THREAD

**Issue by bbhxwl** [pytorch/pytorch#56917]
C:\Users\47013>pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu102
ERROR: No matching distribution found for torch==1.8.1+cu102

**Comment by skyline75489** [comment]
Unfortunately there's not `torch==1.8.1+cu102` for Python 3.5. You need at least Python 3.6.
