### ISSUE TITLE
Compiling Libtorch in Vs 2019？

### ISSUE THREAD

**Issue by Liangerty** [pytorch/pytorch#56913]
I've installed libtorch to help me run the model trained in my C++ code. But when I open a project just to try the library, the compilation breaks down. I wrote nothing in main function, the code is as follows:
`#include<torch/script.h>
int main() {}`
it reports several errors.
`1>C:\Program Files\Libtorch\Release\include\c10/util/ArrayRef.h(149): error : variable in constexpr function does not have automatic storage duration

1>      TORCH_CHECK(!empty(), "ArrayRef: attempted to access front() of empty list");
1>      ^
1>          detected during instantiation of "const T &c10::ArrayRef<T>::front() const [with T=at::Tensor]" at line 30 of "C:\Program Files\Libtorch\Release\include\ATen/DeviceGuard.h"`
Anyone may help me with it? It would help a lot. Thanks!

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
Are you using CMake? Also are you using C++14? You need to provide more information for us to help you.

**Comment by skyline75489** [comment]
I think PyTorch never really supports ICC. The only compiler supported on Windows is MSVC and the code is C++14 at the moment.

**Comment by Liangerty** [comment]
Yes, that's it! Thank you so much! Just turn the compiler into MSVC with C++14 and it works!
