### ISSUE TITLE
[feature request] incomplete cholesky factorization

### ISSUE THREAD

**Issue by rfeinman** [pytorch/pytorch#56920]
## 🚀 Feature
I would love to see an implementation of the _incomplete Cholesky_ factorization.

## Motivation

The incomplete Cholesky factorization has proved useful in a wide number of ML problems, especially those related to optimization (Nocedal and Wright, 2006). It's particularly useful as a preconditioner for iterative algorithms like conjugate gradient and Lanczos. 

LAPACK's _potrf_ returns incomplete factorizations; however, at the moment there is no way to access them in pytorch, since a runtime error is raised when info != 0. Even when cholesky is called as `torch.cholesky(A, out=L)`, the result does not populate into buffer `L`.

## Pitch

Perhaps it would make sense to follow scipy's schematic. Like pytorch, scipy's public-facing cholesky routines (`linalg.cholesky` and `linalg.cho_factor`) wrap _potrf_ and raise an error when info != 0. However, they also provide a means to call LAPACK directly via `linalg.get_lapack_funcs`. This gives added control to more advanced LAPACK users. Pytorch has a number of routines that call LAPACK directly, such as `orgqr` and `geqrf`, and perhaps it be possible to add one more for `potrf`.

Alternatively, another idea is to let the partial factorization populate into the buffer `L` when cholesky is called as `torch.cholesky(A, out=L)`. This might require some additional documentation about derivatives etc for the case of an incomplete factorization.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by IvanYashchuk** [comment]
Hi @rfeinman, thank you for filing this feature request! There is an ongoing PR https://github.com/pytorch/pytorch/pull/56724 that adds a variant that allows suppressing the error check.

**Comment by rfeinman** [comment]
@IvanYashchuk Thank you - this looks like just what I was hoping for!

**Comment by mruberry** [comment]
@rfeinman - think this issue can be closed now?

**Comment by rfeinman** [comment]
@mruberry yes, I think it can be closed. 

There is another form of "incomplete" factorization that is often used: the incomplete [LU/cholesky approximation](https://en.wikipedia.org/wiki/Incomplete_LU_factorization) for large sparse matrices. Implementing this in pytorch would involve a larger effort and should perhaps be saved for another time. The factorization is especially useful as a preconditioner for iterative linear solvers. Popular implementations are the [SuperLU package](https://portal.nersc.gov/project/sparse/superlu/) and the [MKL ILU](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/sparse-solver-routines/preconditioners-based-on-incomplete-lu-factorization-technique.html).

**Comment by mruberry** [comment]
> @mruberry yes, I think it can be closed.
> 
> There is another form of "incomplete" factorization that is often used: the incomplete [LU/cholesky approximation](https://en.wikipedia.org/wiki/Incomplete_LU_factorization) for large sparse matrices. Implementing this in pytorch would involve a larger effort and should perhaps be saved for another time. The factorization is especially useful as a preconditioner for iterative linear solvers. Popular implementations are the [SuperLU package](https://portal.nersc.gov/project/sparse/superlu/) and the [MKL ILU](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/sparse-solver-routines/preconditioners-based-on-incomplete-lu-factorization-technique.html).

Would you file a separate issue with some context requests that factorization so we don't forget about it?
