### ISSUE TITLE
Bazel build documentation

### ISSUE THREAD

**Issue by RajivKurian** [pytorch/pytorch#56940]
## 📚 Bazel build documentation

My personal experience so far:
I was able to build the torch target. I used the command ``bazel build --sandbox_debug //:torch`. It looks like I need python2 and python2-dev packages on Linux to build the torch target. I also needed to install typing_extensions (I did so via `pip3 install typing_extensions`) to get the Bazel torch target to build.

If I instead (of python2 and python2-dev) have python3 and python3-dev installed on my machine I get the following Bazel failure:
`ERROR: /tmp/rkurian/bazel_output/2af40001cd2685a48740cb2acea6f989/external/local_config_python/BUILD:67:8: Executing genrule @local_config_python//:python_include failed: (Exit 1): process-wrapper failed: error executing command 
  (cd /tmp/rkurian/bazel_output/2af40001cd2685a48740cb2acea6f989/sandbox/processwrapper-sandbox/3050/execroot/pytorch && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TMPDIR=/tmp \
  /tmp/rkurian/bazel_output/install/1a4a2fac02d50c77031d44c0d91b8920/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
cp -f "/usr/include/python2.7/Python-ast.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/Python-ast.h" && cp -f "/usr/include/python2.7/Python.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/Python.h" && cp -f "/usr/include/python2.7/abstract.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/abstract.h" && cp -f "/usr/include/python2.7/asdl.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/asdl.h" && cp -f "/usr/include/python2.7/ast.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/ast.h" && cp -f "/usr/include/python2.7/bitset.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/bitset.h" && cp -f "/usr/include/python2.7/boolobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/boolobject.h" && cp -f "/usr/include/python2.7/bufferobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/bufferobject.h" && cp -f "/usr/include/python2.7/bytearrayobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/bytearrayobject.h" && cp -f "/usr/include/python2.7/bytes_methods.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/bytes_methods.h" && cp -f "/usr/include/python2.7/bytesobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/bytesobject.h" && cp -f "/usr/include/python2.7/cStringIO.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/cStringIO.h" && cp -f "/usr/include/python2.7/cellobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/cellobject.h" && cp -f "/usr/include/python2.7/ceval.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/ceval.h" && cp -f "/usr/include/python2.7/classobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/classobject.h" && cp -f "/usr/include/python2.7/cobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/cobject.h" && cp -f "/usr/include/python2.7/code.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/code.h" && cp -f "/usr/include/python2.7/codecs.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/codecs.h" && cp -f "/usr/include/python2.7/compile.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/compile.h" && cp -f "/usr/include/python2.7/complexobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/complexobject.h" && cp -f "/usr/include/python2.7/datetime.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/datetime.h" && cp -f "/usr/include/python2.7/descrobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/descrobject.h" && cp -f "/usr/include/python2.7/dictobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/dictobject.h" && cp -f "/usr/include/python2.7/dtoa.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/dtoa.h" && cp -f "/usr/include/python2.7/enumobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/enumobject.h" && cp -f "/usr/include/python2.7/errcode.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/errcode.h" && cp -f "/usr/include/python2.7/eval.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/eval.h" && cp -f "/usr/include/python2.7/fileobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/fileobject.h" && cp -f "/usr/include/python2.7/floatobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/floatobject.h" && cp -f "/usr/include/python2.7/frameobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/frameobject.h" && cp -f "/usr/include/python2.7/funcobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/funcobject.h" && cp -f "/usr/include/python2.7/genobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/genobject.h" && cp -f "/usr/include/python2.7/graminit.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/graminit.h" && cp -f "/usr/include/python2.7/grammar.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/grammar.h" && cp -f "/usr/include/python2.7/import.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/import.h" && cp -f "/usr/include/python2.7/intobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/intobject.h" && cp -f "/usr/include/python2.7/intrcheck.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/intrcheck.h" && cp -f "/usr/include/python2.7/iterobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/iterobject.h" && cp -f "/usr/include/python2.7/listobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/listobject.h" && cp -f "/usr/include/python2.7/longintrepr.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/longintrepr.h" && cp -f "/usr/include/python2.7/longobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/longobject.h" && cp -f "/usr/include/python2.7/marshal.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/marshal.h" && cp -f "/usr/include/python2.7/memoryobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/memoryobject.h" && cp -f "/usr/include/python2.7/metagrammar.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/metagrammar.h" && cp -f "/usr/include/python2.7/methodobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/methodobject.h" && cp -f "/usr/include/python2.7/modsupport.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/modsupport.h" && cp -f "/usr/include/python2.7/moduleobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/moduleobject.h" && cp -f "/usr/include/python2.7/node.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/node.h" && cp -f "/usr/include/python2.7/object.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/object.h" && cp -f "/usr/include/python2.7/objimpl.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/objimpl.h" && cp -f "/usr/include/python2.7/opcode.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/opcode.h" && cp -f "/usr/include/python2.7/osdefs.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/osdefs.h" && cp -f "/usr/include/python2.7/parsetok.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/parsetok.h" && cp -f "/usr/include/python2.7/patchlevel.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/patchlevel.h" && cp -f "/usr/include/python2.7/pgen.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pgen.h" && cp -f "/usr/include/python2.7/pgenheaders.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pgenheaders.h" && cp -f "/usr/include/python2.7/py_curses.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/py_curses.h" && cp -f "/usr/include/python2.7/pyarena.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyarena.h" && cp -f "/usr/include/python2.7/pycapsule.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pycapsule.h" && cp -f "/usr/include/python2.7/pyconfig.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyconfig.h" && cp -f "/usr/include/python2.7/pyctype.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyctype.h" && cp -f "/usr/include/python2.7/pydebug.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pydebug.h" && cp -f "/usr/include/python2.7/pyerrors.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyerrors.h" && cp -f "/usr/include/python2.7/pyexpat.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyexpat.h" && cp -f "/usr/include/python2.7/pyfpe.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyfpe.h" && cp -f "/usr/include/python2.7/pygetopt.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pygetopt.h" && cp -f "/usr/include/python2.7/pymacconfig.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pymacconfig.h" && cp -f "/usr/include/python2.7/pymactoolbox.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pymactoolbox.h" && cp -f "/usr/include/python2.7/pymath.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pymath.h" && cp -f "/usr/include/python2.7/pymem.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pymem.h" && cp -f "/usr/include/python2.7/pyport.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pyport.h" && cp -f "/usr/include/python2.7/pystate.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pystate.h" && cp -f "/usr/include/python2.7/pystrcmp.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pystrcmp.h" && cp -f "/usr/include/python2.7/pystrtod.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pystrtod.h" && cp -f "/usr/include/python2.7/pythonrun.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pythonrun.h" && cp -f "/usr/include/python2.7/pythread.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/pythread.h" && cp -f "/usr/include/python2.7/rangeobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/rangeobject.h" && cp -f "/usr/include/python2.7/setobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/setobject.h" && cp -f "/usr/include/python2.7/sliceobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/sliceobject.h" && cp -f "/usr/include/python2.7/stringobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/stringobject.h" && cp -f "/usr/include/python2.7/structmember.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/structmember.h" && cp -f "/usr/include/python2.7/structseq.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/structseq.h" && cp -f "/usr/include/python2.7/symtable.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/symtable.h" && cp -f "/usr/include/python2.7/sysmodule.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/sysmodule.h" && cp -f "/usr/include/python2.7/timefuncs.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/timefuncs.h" && cp -f "/usr/include/python2.7/token.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/token.h" && cp -f "/usr/include/python2.7/traceback.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/traceback.h" && cp -f "/usr/include/python2.7/tupleobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/tupleobject.h" && cp -f "/usr/include/python2.7/ucnhash.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/ucnhash.h" && cp -f "/usr/include/python2.7/unicodeobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/unicodeobject.h" && cp -f "/usr/include/python2.7/warnings.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/warnings.h" && cp -f "/usr/include/python2.7/weakrefobject.h" "bazel-out/k8-fastbuild/bin/external/local_config_python/python_include/weakrefobject.h"
`
Looks like some script is searching specifically for the python2.7 headers when setting up the toolchain. Like I mentioned before, if I do have these headers in place (via the python2-dev package), I am able to successfully build the `torch` target.

However, once the Bazel build sets up the automatic python2 toolchain, it fails because `torch_python` requires python3. The failure happens when I build the torch_python target (via `bazel build --sandbox_debug //:torch_python`):
`In file included from ./torch/csrc/Device.h:3,
                 from bazel-out/k8-fastbuild/bin/torch/csrc/autograd/generated/python_special_functions.cpp:3:
./torch/csrc/python_headers.h:18:2: error: #error "Python 2 has reached end-of-life and is no longer supported by PyTorch."
   18 | #error "Python 2 has reached end-of-life and is no longer supported by PyTorch."
      |  ^~~~~
In file included from bazel-out/k8-fastbuild/bin/torch/csrc/autograd/generated/python_special_functions.cpp:5:
./torch/csrc/Exceptions.h:10:10: fatal error: pybind11/pybind11.h: No such file or directory
   10 | #include <pybind11/pybind11.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

It would be great to know if the Bazel build is maintained and if so what dependencies should be installed on the system to get the Bazel build to work. It would be great to be able to get the steps required to go from downloading the source code to getting `import torch` working in a python script - all with Bazel.

cc @malfet @seemethere @walterddr @brianjo @mruberry

**Comment by kit1980** [comment]
This issue is old and python2 should be completely out now. I can build with bazel on linux with python3 only. Closing this.
