### ISSUE TITLE
Inefficient conversion between COO and CSR formats

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#56959]
## Issue description

The efficient conversion between COO and CSR formats is important because constructing a sparse tensor is simplest when using COO format while many linear algebra operations involving matrix multiplications are considerably more efficient when using CSR format.

In theory, conversion between (2D coalesced) COO and CSR formats involves only the compression or decompression of row indices which are roughly O(nnz) operations while the column indices and element values are unchanged.

In pytorch, however, the conversion is complicated by the following constraints:
- COO indices must have dtype `torch.int64`.
- CSR crow_indices/col_indices can have dtype either `torch.int32` or `torch.int64`. The support for `torch.int32` is introduced to CSR to take advantage of (the most) efficient MKL matmul implementation that uses `int32` indices (pytorch supports MKL LP64 only).

Namely, when one wants to use MKL support for matmul, the most optimal dtype for crow_indices/col_indices would be `int32`. However, the conversion between the COO and CSR formats becomes more expensive because of the forced int32-int64 casting of both row and column indices.

The inefficiency of this is seen in https://github.com/pytorch/pytorch/pull/56392#discussion_r619278654 and https://github.com/pytorch/pytorch/pull/56392#discussion_r619602170 where several methods for sampling CSR and COO tensors are benchmarked (CPU only):
1. sampling a CSR tensor directly is about 4-9x more performant than sampling a COO tensor
2. sampling a CSR tensor from a COO tensor sample via `to_sparse_csr` method is about 60-280x slower than sampling a CSR tensor directly

## Discussion

Considering the low complexity of compression operation and the point 1 and 2, the slow-down factor of 60-280x from a COO->CSR conversion is too high, IMHO, and is likely caused by the int32-int64 casting operations and intermediate copies of tensors.

There appears to be no good dtype choice when a user application requires the usage of MKL for efficient matmul operations and conversions between the COO and CSR formats, at the same time. Unless:
- int32 indices support is implemented for COO format
- pytorch will support MKL ILP64 that allows using int64 indices in MKL routines
- more coding effort will be put to optimize `coo.to_sparse_csr` (and unimplemented `csr.to_sparse`) to take into account int32-int64 casting requirements.

The last option seems most doable but has the least potential to improve the COO-CSR conversion performance.
Any thoughts?

cc @aocsa @nikitaved @pearu @mruberry @gchanan

**Comment by aocsa** [comment]
I agree with the idea to add  int32 indices support to COO.  To support this, I was looking at the code, and not only int32 indices are required by MKL matmul implementation but also cuSparse. See the following cases: 

https://github.com/pytorch/pytorch/blob/f27513e9519085d08e7cf2a451aa7f0083f33bb3/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L61

https://github.com/pytorch/pytorch/blob/305abde976d232494c6b5252111ce15523511ffe/aten/src/ATen/native/sparse/cuda/SparseMatMul.cu#L662

Moreover, unlike MKL ILP64 for int64 indices, there are not cuSparse APIs for int64 indices.  IMO adding int32 support for CSR layout proved that there are no restrictions to add to COO layout too. 

The last proposal related to add more coding effort to optimize coo.to_sparse_csr, which might seem more practical at the beginning, it will always require intermediate copies of tensors, which in the case of CUDA in many cases is more expensive than run the CUDA kernel itself. cc @pearu, @mruberry

**Comment by pearu** [comment]
> The last proposal related to add more coding effort to optimize coo.to_sparse_csr, which might seem more practical at the beginning, it will always require intermediate copies of tensors, which in the case of CUDA in many cases is more expensive than run the CUDA kernel itself.

To avoid unnecessary copies, the conversion of COO-CSR indices should be treated as special operations that implement the compression-decompression and int32-int64 castings in a single loop. For instance, to convert CSR int32 indices to COO int64 indices, here is a prototype of the algorithm (using Python syntax but it should be implemented in C++):
```
def decompress(crow_indices, col_indices):
    assert crow_indices.dtype == int32 and col_indices.dtype == int32
    nrows = len(crow_indices) - 1
    nnz = len(col_indices)
    indices = zeros((2, nnz), dtype=int64)
    indices[1] = col_indices  # cast and copy
    n = 0
    n0 = crow_indices[0]
    for i in range(nrows):  # i is int64
        n1 = crow_indices[i+1]
        indices[0, n: n+n1-n0] = i  # use memset or fill
        n += n1-n0
        n0 = n1
    return indices

def compress(indices, nrows):
    assert indices.size[0] == 2 and indices.dtype == int64
    nnz = indices.size[1]
    crow_indices = zeros(nrows+1, dtype=int32)
    col_indices = empty(nnz, dtype=int32)
    col_indices[:] = indices[1]  # cast and copy
    last_index = 0
    k = 1
    for i in range(nnz):  # i is int32
        index = indices[0, i]
        # assuming coalesced COO
        for n in range(last_index, index):  # this loop is embarrassingly short, no longer than nrows for the worst case
            compressed[k] = i
            k += 1
        last_index = index
    return crow_indices, col_indices
```
where for efficient "cast and copy" one can introduce CUDA kernel that copies int32 or int64 tensor to int64 or int32 tensor, respectively.

**Comment by aocsa** [comment]
Sorry, I'm not sure if I get the idea, So let me ask again how we can avoid unnecessary copies because I think in the implementation of `sparse_sparse_matmul_cuda_kernel`
https://github.com/pytorch/pytorch/blob/305abde976d232494c6b5252111ce15523511ffe/aten/src/ATen/native/sparse/cuda/SparseMatMul.cu#L645
We are following somewhere these compression-decompression pattern and int32-int64 castings.

**compress**, lines 671:673
https://github.com/pytorch/pytorch/blob/305abde976d232494c6b5252111ce15523511ffe/aten/src/ATen/native/sparse/cuda/SparseMatMul.cu#L671

**decompress**, lines 728:756 
https://github.com/pytorch/pytorch/blob/305abde976d232494c6b5252111ce15523511ffe/aten/src/ATen/native/sparse/cuda/SparseMatMul.cu#L728

**Comment by pearu** [comment]
@aocsa , sparse_sparse_matmul_cuda_kernel is for COO and here the compression/decompression is an internal implementation detail.

I am thinking of a scenario where COO tensors are used for building sparse tensors from user data and CSR tensors are used as inputs to linalg algorithms, all that being under users' control. So, the user applications would transform COO tensors to CSR tensor if operations are applied that are known to be more efficient on CSR tensors than on COO tensors. The intermediate results would be kept in CSR format until one needs to perform operations where COO format would be more advantageous than CSR. Etc.

Notice that this is different from the use case of sparse_sparse_matmul_cuda_kernel where the user applications always operate with COO tensors while some operations (such as matmul) do the CSR conversions internally. The internal conversions can be avoided when operations are applied on tensors using the format that are known to be most suitable for particular operations. For instance, adding a new element to a CSR tensor would be very inefficient (one basically needs to reconstruct the whole tensor) while the same operations on a COO tensor can be very cheap.
