### ISSUE TITLE
one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 2]] is at version 1; expected version 0 instead?

### ISSUE THREAD

**Issue by pvsnp9** [pytorch/pytorch#56983]
I did use the  with torch.autograd.detect_anomaly, and received the error in following line of code

    h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul((r*h), Uh) + bh)

I have simplest GRU.

     def gru(x, h):

      outputs = []

      for sequence in x: # iterates over the sequences in each batch
          z = torch.sigmoid(torch.matmul(sequence, Wz) + torch.matmul(h, Uz) + bz)
          r = torch.sigmoid(torch.matmul(sequence, Wr) + torch.matmul(h, Ur) + br)
          h_tilde = torch.tanh(torch.matmul(sequence, Wh) + torch.matmul((r*h), Uh) + bh) 
          h = z * h + (1 - z) * h_tilde

          #Linear layer
          y_linear = torch.matmul(h, Wy) + by

          # Softmax activation function
          y_t = F.softmax(y_linear, dim=1)
          outputs.append(y_t)
      return torch.stack(outputs),h
    
The error occurred while loss.backward()
I could not find in_place operation in above code or am i missing something !! 

Full Error Message:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 2]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
