### ISSUE TITLE
CUDA memory type management in torch.jit

### ISSUE THREAD

**Issue by trenta3** [pytorch/pytorch#57007]
## 🚀 Feature
Add annotations to torch.jitted python code to allocate tensors in specific parts of CUDA memory (thread-local memory, block-shared memory, grid-global memory).

## Motivation
I need to write code computing matrix-vector product where the dimension of the matrix is very big 1M x 1M entries, but the matrix elements are easily computed "in-place" (i.e. they depend on a small amount of other data, for the sake of example let's say they depend on the matrix indices (i, j)).

I cannot store the full matrix since it is too large but i can do a tiled dot-product where submatrices are computed in-place and then multiplied with the vector. This is very easy to do with `torch.jit`, but unfortunately is 10x slower than using the pykeops package (which is especially suited for this task).

I don't know which kind of memory is allocated currently (or how the kind is chosen), nor this is documented under the jit documentation, but it would enable much more performant scripts if the user could specify the type of memory to use.
If this is already an available option, please document it.

## Pitch
Allow users to annotate variables to denote the place in CUDA memory where they have to be allocated.

cc @gmagogsfm

**Comment by tugsbayasgalan** [comment]
Hi, we would recommend looking into Numba since it has more configurations.

**Comment by SplitInfinity** [comment]
Another things you might consider using is NVRTC: https://github.com/salesforce/pytorch-qrnn/blob/daadb0f39a1811128df7eb03933f286aa5e319ed/torchqrnn/forget_mult.py#L10

**Comment by trenta3** [comment]
@tugsbayasgalan I looked into numba and it serves my usecase well enough.
But i'm having troubles in including the numba.cuda.jit ted computation in a backward pytorch pass.
Is there a way to seamlessy integrate numba computation with automatic gradients?

**Comment by trenta3** [comment]
I couldn't find any way to integrate numba computation with automatic gradients, so I ended up coding the backward pass as well.
Numba serves my use-case well enough so I will close this issue.

Of course feel free to reopen if you decide to actually implement CUDA memory type management inside torchscript.
