### ISSUE TITLE
torch_cpu.dll is very big : 197 MB. Is it possible to reduce its size ?

### ISSUE THREAD

**Issue by simonesneault** [pytorch/pytorch#57001]
Hello,
Currently when downloading libtorch 1.8.1 (libtorch-win-shared-with-deps-1.8.1+cpu.zip), torch_cpu.dll is about 197 MB which is quite huge.

I've tried to build libtorch from scratch, without coffee2 It is possible to save some MB but most of the size comes from MKL (100 MB from my test)

Is it possible to reduce the size of the library without loosing performances ?

Thanks

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
For the record, on Linux `libtorch_cpu.so` takes ~340MB.

**Comment by malfet** [comment]
One can slim down size of torch_cpu library by disabling some extra features, like `caffe2` you've already mentioned, distributed support, `onnx`, autograd, reduce number of supported datatypes and so on, use simpler (but slower) BLAS library.
But if you want all the features and maximum performance than no, there no trivial ways to reduce binary size.
