### ISSUE TITLE
Training a cascaded network using multi-GPUs

### ISSUE THREAD

**Issue by JohnnieXDU** [pytorch/pytorch#5703]
Im training a cascaded network, for simple example, Inputs -> Net1 -> mid results -> Net2 -> outputs.

For the reason that the cascaded network Net1+Net2 consuming GPU memory a lot, I can not train with a desired batch size. So i train the entire net(Net1+Net2) on multi GPUs.

But when i run the code, it fails with the following:

> RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCTensorMathBlas.cu:236

Besides, the code could  work when I replace the cascade network(Net1+Net2) to a single classification network(Vgg16).

The cascade net prototype is as follows:
```
class cascade_net(nn.Module):
    def __init__(self):
        super(cascade_net, self).__init__()
        self.net1 = vgg19_net()
        self.net2 = AttnLSTM_net()

    def forward(self, x):
        img_enc = self.net1(x)
        cur_outputs, (cur_h, cur_c) = self.net2([img_enc])
        return cur_outputs, (cur_h, cur_c)
```

**Comment by apaszke** [comment]
You need to send the outputs of net1 to a different device. PyTorch won’t do that for you. Change `self.net1(x)` to `self.net1(x).cuda(device_of_net2)`.

Also in the future use forums for questions. We only use GitHub issues for bug tracking

**Comment by JohnnieXDU** [comment]
Thanks a lot!
