### ISSUE TITLE
pytorch-cpu installs cudnn and cudatoolkit when using conda

### ISSUE THREAD

**Issue by sensharma** [pytorch/pytorch#5705]
Hi, when I install pytorch for CPU usage via conda (conda install -c soumith pytorch-cpu) it downloads and installs cudnn and cudatoolkit, which seems to be unnecessary for installation for a CPU version not using cuda. This is especially a problem when building docker images since I would like to keep them as light as possible. I cannot think of how that could be, but does the CPU version have any dependencies on cudnn and cudatoolkit? If not can these dependencies be removed for the cpu version?
Not sure if this is the correct place to bring this up. If not, happy to be pointed in the right direction.

**Comment by soumith** [comment]
can you use the commands on the website (i.e. use the `-c pytorch` channel).
The pytorch-cpu package has no declared dependency on cudatoolkit or cudnn. https://github.com/pytorch/builder/blob/master/conda/pytorch-cpu-0.3.1/meta.yaml#L18-L22

**Comment by lanpa** [comment]
@sensharma Maybe this is caused by torchvision. https://github.com/pytorch/vision/issues/390

**Comment by max-simon** [comment]
This is caused by torchvision. Installing pytorch alonge does not require 'cudatoolkit' or 'cudnn'.
How can one avoid this?

**Comment by simonm3** [comment]
I just conda installed pytorch-cpu==1.2 and it still adds cudatoolkit.

**Comment by soumith** [comment]
@simonm3 we changed the commands for cpu only install. see pytorch.org for updated command
