### ISSUE TITLE
Unable to trace RRef's when using torch.jit.script with remote functions.

### ISSUE THREAD

**Issue by anj-s** [pytorch/pytorch#57138]
## 🐛 Bug

One of the recommendations to improve performance when using rpc_async/rpc_sync was to use torch.jit.script to trace the function that was being run remotely. However this results in an error since we cannot trace RRefs and all function inputs are expected to be of type Tensor. 

How should one go about this? The only way to get a handle on the remote object is to pass the reference as once of the arguments to the rpc_async/rpc_sync calls. 

## To Reproduce
run the gist below with --use_torch_script flag
https://gist.github.com/anj-s/b2a68d7985dc7ebd8a6d95d7e7094170

Stack Trace:
```
Traceback (most recent call last):
  File "playground/herring/repro/repro_rpc_torch_script.py", line 12, in <module>
    class Server(object):
  File "playground/herring/repro/repro_rpc_torch_script.py", line 20, in Server
    def val(myobj_rref):
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/_script.py", line 1094, in script
    fn = torch._C._jit_script_compile(
RuntimeError:
'Tensor (inferred)' object has no attribute or method 'local_value'.:
  File "playground/herring/repro/repro_rpc_torch_script.py", line 21
    @torch.jit.script
    def val(myobj_rref):
        self = myobj_rref.local_value()
               ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        fut = torch.futures.Future()
        fut.set_result(self.value)
```

## Expected behavior

Recommendation for how we should use torch.jit.script with RRefs + remote functions. Specifically how can we get a handle on the remote object if we don't pass it as an argument to the function.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.9.0.dev20210428+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210428+cu111
[pip3] torchaudio==0.9.0.dev20210428
[pip3] torchtext==0.10.0a0+34ccda8
[pip3] torchvision==0.10.0.dev20210428+cu111
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0.dev20210428+cu111           <pip>
[conda] torchaudio                0.9.0.dev20210428           <pip>
[conda] torchtext                 0.10.0a0+34ccda8           <pip>
[conda] torchvision               0.10.0.dev20210428+cu111           <pip>

cc @gmagogsfm

**Comment by lw** [comment]
@wanchaol might know more about this?

**Comment by anj-s** [comment]
cc @msbaines

**Comment by wanchaol** [comment]
@anj-s by scripting this function, you should annotate your input arguments, otherwise torchscript will by default treat this argument as tensor, do it something like this:
```
    @torch.jit.script
    def val(myobj_rref: RRef[Tensor]):
```

**Comment by wanchaol** [comment]
@anj-s any updates? if it works for you, we can close this

**Comment by anj-s** [comment]
Sorry for the delayed response. 
I am running into a new error:

```
Traceback (most recent call last):
  File "examples/playground/herring/repro/repro_rpc_torch_script.py", line 12, in <module>
    class Server(object):
  File "examples/playground/herring/repro/repro_rpc_torch_script.py", line 20, in Server
    def val(myobj_rref: torch.distributed.rpc.RRef[torch.Tensor]):
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/_script.py", line 1094, in script
    fn = torch._C._jit_script_compile(
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/_script.py", line 1211, in _recursive_compile_class
    return _compile_and_register_class(obj, rcb, _qual_name)
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/_script.py", line 134, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/frontend.py", line 190, in get_jit_class_def
    methods = [get_jit_def(obj,
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/frontend.py", line 190, in <listcomp>
    methods = [get_jit_def(obj,
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/frontend.py", line 300, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/frontend.py", line 322, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name, pdt_arg_types)
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/jit/frontend.py", line 357, in build_param_list
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/private/home/anj/.conda/envs/test_clone/lib/python3.8/site-packages/torch/futures/__init__.py", line 26
    def __init__(self, *, devices: Optional[List[Union[int, str, torch.device]]] = None):
                                                                                   ~~~~ <--- HERE
        r"""
        Create an empty unset ``Future``. If the future is intended to hold
'__torch__.torch.jit.Future' is being compiled since it was called from 'val'
  File "examples/playground/herring/repro/repro_rpc_torch_script.py", line 22
    def val(myobj_rref: torch.distributed.rpc.RRef[torch.Tensor]):
        self = myobj_rref.local_value()
        fut = torch.futures.Future()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        fut.set_result(self.value)
        return fut
```

Followups:
* Should RRef[torch.Tensor] instead be RRef[Server]? 
* I tried using a Future that is a member of the instance instead of creating a new one but that failed as well.
* I tried returning just self.value but we expect a Future to be returned so that doesn't work as well.

**Comment by SplitInfinity** [comment]
I don't think you can create `torch.jit.Futures` in your own code; you need use `torch.jit.fork`, which returns a `Future`.

**Comment by lw** [comment]
@wanchaol This new error seems to be mentioning a kwargs-only argument I added to torch.futures.Future recently. I remember that JIT has some issues with keyword-only args, is there anything we should change/fix here?

**Comment by anj-s** [comment]
Thank you @SplitInfinity. That seems right. I used `torch.jit.fork` to return a Future to the caller. The one thing to keep in mind is that you will need to torch script the function that you are calling and the class whose function is passed to `torch.jit.fork`.

**Comment by Zalways** [comment]
hi i met similar problem when i try to scriping a torchscript model.

this is error info：
RuntimeError: 
'Tensor (inferred)' object has no attribute or method 'tensor'.:
  File "/root/autodl-tmp/project/deepsolo/adet/modeling/text_spotter_v1.py", line 43
    def forward(self, images):
        features = self.backbone(images.tensor)
                                 ~~~~~~~~~~~~~ <--- HERE
        # features = self.backbone(images)
        masks = self.mask_out_padding(

i''ll apreciate if you could help with my problem. @anj-s  @lw  @wanchaol
