### ISSUE TITLE
Profiling within a callback function does not raise an error but fails to execute a print statement

### ISSUE THREAD

**Issue by anj-s** [pytorch/pytorch#57172]
## 🐛 Bug

Using `torch.autograd.profiler` within a RPC callback function results in a couple of different behaviors that are confusing:
1. Fails to execute a print statement within the callback
2. Does not produce a profiler output file
3. Does not raise an error
4. I've also seen runs hang in certain setups that use a profiler in the callback function though I was not able to reproduce it in this small example.

Thank you @rohan-varma for helping me with this issue and suggesting using a wait() before profiling.

Related resource that I used along with Rohan's help to profile async RPCs:  https://pytorch.org/tutorials/recipes/distributed_rpc_profiling.html

## To Reproduce
Run the code in the following gist:
https://gist.github.com/anj-s/8b03b351414e1a59db151f1bda3c6436

## Expected behavior

A profiler output file or an error if profiling a callback function is not possible.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.9.0.dev20210428+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210428+cu111
[pip3] torchaudio==0.9.0.dev20210428
[pip3] torchtext==0.10.0a0+34ccda8
[pip3] torchvision==0.10.0.dev20210428+cu111
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0.dev20210428+cu111           <pip>
[conda] torchaudio                0.9.0.dev20210428           <pip>
[conda] torchtext                 0.10.0a0+34ccda8           <pip>
[conda] torchvision               0.10.0.dev20210428+cu111           <pip>

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by anj-s** [comment]
cc @mrshenli @msbaines

**Comment by mrzzd** [comment]
I wrapped "with" block (line 39) in your repro by a try-except, and I can see there is an exception: `TypeError: 'module' object is not callable`
But I can not find a module instance in the code.

**Comment by ilia-cher** [comment]
Thanks for reporting, we will be deprecating the experimental support of profiling of RPC calls (remote tasks) since 1.9 and will remove it in later releases. The recommendation is, if you also need to profile remote tasks, profile them explicitly inserting a profiling context in the remote task.

**Comment by rohan-varma** [comment]
@ilia-cher this repro indeed profiles remote task directly (ran over `callback_with_profiler`) and that is something we should support. The bug reported here doesn't seem to be about sending profile information over the wire. Should we reopen the issue?

**Comment by ilia-cher** [comment]
ok, might've missed that, reopening;

So, overall, profiler is not and should not be aware (at least at the moment) whether this is a remote task or not; the logic of profiler should not be affected by that.

The trace is not produced because it's completely empty (we should produce the file though, will follow up on empty traces).
As of why there's no output - maybe @rohan-varma can also weigh in here, profiler itself shouldn't interfere with python output or rpc futures.
I assume that distributed code happen to fail and consume the exception silently, when fut.wait() is called, cc @rohan-varma do you know why future's method might fail here? my only guess right now - it somehow breaks in "remote task profiling" logic
(and we plan to remove this logic)

**Comment by rohan-varma** [comment]
@anj-s I think there's a typo in the code, profiler should be invoked with

`with torch.autograd.profiler.profile(use_cuda=True)`, not `with torch.autograd.profiler(use_cuda=True)`. 

Also we should add a `wait` to `return_future.then` which helps raise the error @mrzzd mentioned.

With these 2 changes I'm able to get the profiler to work, although get another error when exporting trace:
```
RuntimeError: Got the following error when running the callback: ValueError: negat
ive seek position -1
```

this appears to be an edge case when we export trace but there is nothing in the trace. Adding some tensor operations seems to mitigate that. Here is an example that works for me: P411576109

**Comment by ilia-cher** [comment]
Thanks @rohan-varma ! Yes, this bug with empty trace will be fixed, will send a PR soon.

**Comment by anj-s** [comment]
@rohan-varma @ilia-cher thanks for taking a look! I double checked my code and i used the right API i.e torch.autograd.profiler.profile so it's a typo in the repro which also makes sense since I wasn't able to repro the hanging issue that I originally saw. There were definitely ops that were being executed so I did not run into the RuntimeError that you saw when using just print inside the function. 

Since it was a hanging issue I doubt the wait() will return. Feel free to close this issue and I'll reopen if I run into the hanging behavior again. Thanks!
