### ISSUE TITLE
Small bug in LPPool2d documentation

### ISSUE THREAD

**Issue by calvinleenyc** [pytorch/pytorch#5718]
The math rendering doesn't end where it should, making the text after it difficult to read:

http://pytorch.org/docs/master/nn.html#torch.nn.LPPool2d
<img width="719" alt="screen shot 2018-03-12 at 5 07 03 pm" src="https://user-images.githubusercontent.com/6576216/37309613-d339a60c-2617-11e8-80a9-96e7a7bc1e93.png">

**Comment by apaszke** [comment]
Thanks for the report! Would you be interested in submitting a PR that fixes it?

**Comment by calvinleenyc** [comment]
Sure, I can give it a try!

**Comment by vishwakftw** [comment]
@apaszke @calvinleenyc This is being fixed in this PR https://github.com/pytorch/pytorch/pull/5685.
