### ISSUE TITLE
PyTorch Installation for Windows using Conda gives unrecognized arguments:nvidia

### ISSUE THREAD

**Issue by iVishalr** [pytorch/pytorch#57242]
## 📚 Documentation

I was installing PyTorch with cudatoolkit 11.1 on Windows using Conda. 

The command  given in website,

`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch nvidia` 

when executed causes an error saying :

`conda-script.py: error: unrecognized arguments: nvidia`

![Capture](https://user-images.githubusercontent.com/42243737/116504464-f2cdb500-a8d5-11eb-8985-b5fcd6ede499.PNG)

A simple fix would be to include a `-c` before `nvidia` in the command makes it work.

![Capture1](https://user-images.githubusercontent.com/42243737/116504606-4b9d4d80-a8d6-11eb-943e-c8b938e11c16.PNG)

**Comment by skyline75489** [comment]
Yea, this is introduced by https://github.com/pytorch/pytorch.github.io/pull/688
