### ISSUE TITLE
Size overrides argument in "_like" tensor creation ops

### ISSUE THREAD

**Issue by charliebudd** [pytorch/pytorch#57269]
## 🚀 Feature
The ability to pass size overides to certain dimensions when creating new tensors using the "_like" functions. For example...

```
input_tensor = torch.ones(2, 3, 32, 32)
new_tensor = torch.zeros_like(input_tensor, overides=[(1, N)]) 
# new_tensor shape is (2, N, 32, 32)
```

## Motivation
I find the current situation a bit clunky as the new size N may be either smaller or larger than the current size of the target dimension leading to this....

```
new_tensor = torch.zeros_like(input_tensor.narrow(1, 0, 1).expand(-1, N, -1, -1))
```

This is worse when supporting tensors with an arbitrary number of trailing dimensions as you cannot make use of the expand function...

```
sizes = list(input_tensor.shape)
sizes[1] = N
new_tensor = torch.zeros(sizes, dtype=input_tensor.dtype, device=input_tensor.device)
```

## Pitch
Adding the above mentioned "overides" keyword argument into the "_like" tensor creation operations would, in my opinion, make the above situation much more fluent to write aswell as easier to read.

## Alternatives
See above examples, Im happy to hear if theres an easier way to acheive this functionality with the existing API.

## Additional context
N/A

cc @gchanan @mruberry

**Comment by gchanan** [comment]
you can use `input_tensor.new_zeros(size,...)`.

**Comment by charliebudd** [comment]
If you look at my second example you'll see thats what I have done. My argument is that this could be made into a snappy one liner with a very minor PR.

**Comment by charliebudd** [comment]
To further make my point, here is the c++ code for acheiving this in the manner you suggest...
```
    int dim = input_tensor.dim();
    long int* output_size = new long int[dim];
    memcpy(output_size, input_tensor.sizes().data(), dim * sizeof(long int));
    output_size[1] = N;
    torch::Tensor output_tensor = torch::zeros(
        c10::IntArrayRef(output_size, dim), 
        torch::dtype(input_tensor.dtype()).device(input_tensor.device())
    );
    delete output_size;
```
compared to my propsed operation...
```
output_tensor = torch::zeros_like(input_tensor, {py::make_tuple(1, N)});
```
