### ISSUE TITLE
`Warning: Leaking Caffe2 thread-pool after fork` when using `DataLoader` with `num_workers>0` and `pin_memory=True`

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#57273]
## 🐛 Bug

When using a `DataLoader` with `num_workers>0` and `pin_memory=True`, warnings trigger about `Leaking Caffe2 thread-pool after fork`. This warning shows multiple times, and populates the screen.
The warning doesn't trigger when either `num_workers=0` or `pin_memory=False`.

## To Reproduce

1. Run the following:
   ```python
    from torch.utils.data import DataLoader
    from torchvision.datasets import FakeData
    from torchvision.transforms import ToTensor
    
    
    def main():
        data = FakeData(transform=ToTensor())
        dataloader = DataLoader(data, num_workers=2, pin_memory=True)
        for e in range(1, 6):
            print(f'epoch {e}:')
            for _ in dataloader:
                pass
    
    
    if __name__ == '__main__':
        main()
    ```

### Output:
```
epoch 1:
epoch 2:
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 3:
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 4:
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 5:
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:88] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
```

## Expected behavior

No warnings

## Environment

```
PyTorch version: 1.9.0.dev20210428
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.9.0.dev20210428
[pip3] torchaudio==0.9.0a0+999026d
[pip3] torchvision==0.10.0.dev20210428
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py38h27cfd23_1
[conda] mkl_fft                   1.3.0            py38h42c9631_2
[conda] mkl_random                1.2.1            py38ha9443f7_2
[conda] numpy                     1.20.1           py38h93e21f0_0
[conda] numpy-base                1.20.1           py38h7d8b39e_0
[conda] pytorch                   1.9.0.dev20210428 py3.8_cuda11.1_cudnn8.0.5_0    pytorch-nightly
[conda] torchaudio                0.9.0.dev20210428            py38    pytorch-nightly
[conda] torchvision               0.10.0.dev20210428      py38_cu111    pytorch-nightly
```

## Additional context

It looks like this warning was introduced in https://github.com/pytorch/pytorch/pull/54895. I don't quite follow the details there, though.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by imaginary-person** [comment]
It's supposed to be normal behavior. The Caffe2 thread-pool is leaked & recreated in child processes after fork, in order to prevent a segfault, which otherwise occurs while handling data-structures pertaining to the Caffe2 thread-pool of the parent process, that no longer exists in the child process, which is single-threaded right after fork).

Perhaps, the warning message can be revised, so that it doesn't cause any confusion among users.

**Comment by xkszltl** [comment]
We're seeing the same issue.

After that PR (https://github.com/pytorch/pytorch/pull/54895), I got a lot of warnings in one of our project.
Looks like 4 warnings for each epoch, emitted within the same second.
My guess is it's from data loader restart.
Because for this specific case we have high epoch count with small dataset, it's flooding our log.
If this is expected, should we suppress if after certain times?

**Comment by imaginary-person** [comment]
`TORCH_WARN_ONCE` would've worked the same way as `TORCH_WARN` in #54895, as this warning is displayed only once per child process that leaks & rebuilds the Caffe2 thread-pool.

> If this is expected, should we suppress if after certain times?

If you're referring to filtering this warning in another project, then yes.
But if you're referring to suppressing this warning in the PyTorch source code, then it'd have to be removed.

**Comment by xkszltl** [comment]
If both fork from dataloader and this warning is normal behavior, I would say possible suppression options other than a complete removal are:
- Suppress directly from user side, e.g. inside dataloader.
- Use IPC-capable counter for that "ONCE", e.g. with mmap

**Comment by rafi-cohen** [comment]
I personally believe that if this is normal behaviour, then this warning should be removed.
This is a very basic use case in PyTorch, which, in my opinion, shouldn't trigger a warning unless something is wrong.

Also, I don't really understand the point of the warning. The Caffe2 thread-pool was leaked. Do I need to do anything about that? Should I even care?

**Comment by mansimane** [comment]
Hi, facing similar warning in latest 1.9 rc1. I tried suppressing the warning with -

1.  Launching script as `python -W ignore `
2. Filtering warnings as below 
```
import warnings
warnings.filterwarnings("ignore")
```

Both options do not seem to suppress the warning as it is from `cpp` module. Can someone suggest a way to suppress it without modifying the PyTorch code?

**Comment by Jeffrey-Ede** [comment]
I confirm OP's observation that the error messages disappear for pin_memory = False. Either way, the error messages do not seem to correspond to a meaningful problem for end-users. 

The warnings are very slightly different in a recent copy of the PyTorch 1.9 nightly preview. This is part of my error log:

[W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

**Comment by imaginary-person** [comment]
Hello @malfet, some users reported in this thread that they were misled by the warnings pertaining to leaking the Caffe2 thread-pool, and that they didn't find it to be useful.
Please confirm if it'd be okay to remove this warning. I can submit a PR to do so.
Thank you!

**Comment by ejguan** [comment]
Just wondering if lazy construct caffe2 threadpool can help to resolve this issue. When we call `set_num_thread`, just write the number to a global variable without creating the threadpool. In this case, does the `pin_memory_thread` have the COW problem?

**Comment by moskomule** [comment]
Hi, this problem still exists in v 1.9.

**Comment by tensorfoo** [comment]
Is there any downside to passing `pin_memory=False`? Is that what we're being told to do as a solution?

**Comment by LinxiFan** [comment]
Is there a way to suppress this? - That's all we users care at this point.

**Comment by imaginary-person** [comment]
> Just wondering if lazy construct caffe2 threadpool can help to resolve this issue. When we call `set_num_thread`, just write the number to a global variable without creating the threadpool. In this case, does the `pin_memory_thread` have the COW problem?

Hello @ejguan, when this warning was added, segfault had been happening even with `pin_memory=False`. eg 54752.
In that [issue](https://github.com/pytorch/pytorch/issues/54752#issue-841588402), `pin_memory` was implicitly False.
In fact, if you'd use this script, you'd still get a warning, even if you'd explicitly set `pin_memory` to `True` -

```
import torch

def main():
    torch.set_num_threads(4)

    dataloader = torch.utils.data.DataLoader([1, 2, 3], num_workers=1)
    iter(dataloader).next()

    return

if __name__ == '__main__':
    main()
```

**Comment by imaginary-person** [comment]
> Just wondering if lazy construct caffe2 threadpool can help to resolve this issue. When we call `set_num_thread`, just write the number to a global variable without creating the threadpool. In this case, does the `pin_memory_thread` have the COW problem?

@ejguan, one of the preconditions for this warning to be produced is that `torch.set_num_threads()` should've been called at least once by a script.
So, the following script would still produce a warning -
```
from torch.utils.data import DataLoader
import torch
torch.set_num_threads(4)

def main():
    dataloader = DataLoader([1,2,3,4], num_workers=1, pin_memory=False)
    for e in range(1, 6):
        print(f'epoch {e}:')
        for _ in dataloader:
            pass


if __name__ == '__main__':
     main()
```

I currently don't have TorchVision installed, but I suspect that `pin_memory_thread` calls `set_num_threads` at some point in @rafi-cohen's script. : 

https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/utils/data/_utils/pin_memory.py#L17-L21

**Comment by imaginary-person** [comment]
> In this case, does the `pin_memory_thread` have the COW problem?

I currently don't have TorchVision installed, but I suspect that `pin_memory_thread` calls `set_num_threads` at some point in @rafi-cohen's script. : 

https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/utils/data/_utils/pin_memory.py#L17-L21


@ejguan, if that'd turn out to be the case, then can we remove the warning from the C++ code, since users don't want to see it?

**Comment by imaginary-person** [comment]
@rafi-cohen @LinxiFan @moskomule @Jeffrey-Ede @mansimane 

I'm unable to reproduce the issue with @rafi-cohen's script, probably because this warning requires a `torch.set_num_threads()` invocation to have occurred first. (so I can reproduce the issue if I add a `torch.set_num_threads()` invocation to the script).
However, I tested with the current master branch of PyTorch & the current master branch of Vision.

Can you please confirm if you can reproduce this issue with this script in this issue?
Thank you!

**Comment by glenn-jocher** [comment]
This Warning is now appearing in the YOLOv5 (https://github.com/ultralytics/yolov5) Docker Image with PyTorch 1.9. To reproduce:
```bash
t=ultralytics/yolov5:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t
python train.py --epochs 3
```
<img width="1005" alt="Screenshot 2021-06-19 at 14 44 58" src="https://user-images.githubusercontent.com/26833433/122642919-27f3c800-d10d-11eb-9ccf-a3605b22e616.png">

**Comment by moskomule** [comment]
@imaginary-person Hi, I could reproduce @rafi-cohen's example by using `1.9.0-py3.9_cuda11.1_cudnn8.0.5_0` installed via conda on Ubuntu 20.04.

**Comment by imaginary-person** [comment]
Thanks for the info, @moskomule! It seems caffe2 pthreadpool already exists because of some dependency in the binary distribution, so `torch.set_num_threads()` invocation isn't required to reproduce the issue (as is otherwise the case when building from the master branch).

The same goes for YOLOv5 - `torch.set_num_threads()` invocation isn't required to reproduce the issue.

**Comment by moskomule** [comment]
Thanks. By the way, does it actually cause any memory leak?

**Comment by imaginary-person** [comment]
@moskomule, no, the warning was added after fixing a segfault. We are leaking the Caffe2 pthreadpool in child processes (workers), as child processes inherit its data structures from the parent process, but child processes are single-threaded, so they don't actually have those threads!

BTW, are you unable to reproduce the issue in this issue's script with `pin_memory=False`?
If so, I'd have to check why that happens. Thanks!

**Comment by moskomule** [comment]
@imaginary-person Hi, thanks for the explanation.

Yes, when `pin_memory=False`, the warning disappears.

**Comment by rafi-cohen** [comment]
> @rafi-cohen @LinxiFan @moskomule @Jeffrey-Ede @mansimane
> 
> I'm unable to reproduce the issue with @rafi-cohen's script, probably because this warning requires a `torch.set_num_threads()` invocation to have occurred first. (so I can reproduce the issue if I add a `torch.set_num_threads()` invocation to the script).
> However, I tested with the current master branch of PyTorch & the current master branch of Vision.
> 
> Can you please confirm if you can reproduce this issue with this script in this issue?
> Thank you!

I can confirm the script reproduces the warnings as-in (no need for `torch.set_num_threasd()`) with PyTorch 1.9.0 (py3.8_cuda11.1_cudnn8.0.5_0), running on Ubuntu 18.04.5 LTS


> are you unable to reproduce the issue in this issue's script with `pin_memory=False`?
> If so, I'd have to check why that happens. Thanks!

I noticed that if I first run the script with `pin_memory=True`, and then run it with `pin_memory=False` (on the same python instance), the warnings trigger in both cases. However, if I run a new python instance and run the script with `pin_memory=False`, there are no warnings.

<details>
  <summary>Output of running both options</summary>
  

```python
Python 3.8.10 (default, Jun  4 2021, 15:09:15)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.data import DataLoader
>>> from torchvision.datasets import FakeData
>>> from torchvision.transforms import ToTensor
>>>
>>>
>>> def main(pin_memory):
...     data = FakeData(transform=ToTensor())
...     dataloader = DataLoader(data, num_workers=2, pin_memory=pin_memory)
...     for e in range(1, 6):
...         print(f'epoch {e}:')
...         for _ in dataloader:
...             pass
...
>>> main(True)
epoch 1:
epoch 2:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 3:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 4:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 5:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
>>> main(False)
epoch 1:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 2:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 3:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 4:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
epoch 5:
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
>>>
```

</details>

<details>
  <summary>Output of running with `pin_memory=False` only</summary>
  

```python
Python 3.8.10 (default, Jun  4 2021, 15:09:15)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.data import DataLoader
>>> from torchvision.datasets import FakeData
>>> from torchvision.transforms import ToTensor
>>>
>>>
>>> def main(pin_memory):
...     data = FakeData(transform=ToTensor())
...     dataloader = DataLoader(data, num_workers=2, pin_memory=pin_memory)
...     for e in range(1, 6):
...         print(f'epoch {e}:')
...         for _ in dataloader:
...             pass
...
>>> main(False)
epoch 1:
epoch 2:
epoch 3:
epoch 4:
epoch 5:
>>>
```

</details>

**Comment by imaginary-person** [comment]
Thanks for the info, @rafi-cohen & @moskomule!
Yes, I was able to reproduce the issue with the Conda binary.

Basically, when `pin_memory` is `True`, a `torch.set_num_threads` call is made, which I could see with gdb (`at::set_num_threads`).
So, it seems that it'd be safe to disable the warning.

**Comment by joaqo** [comment]
Having the same issue, would appreciate a way to at least suppress the warning from user space it if it's not affecting training.

**Comment by jmarrietar** [comment]
This just happened to me, The Warning is very confusing from a user perspective.

**Comment by jfemiani** [comment]
Why is this closed? I did not see a solution and I am encountering this issue. Is it a duplicate?

**Comment by imaginary-person** [comment]
> Why is this closed? I did not see a solution and I am encountering this issue. Is it a duplicate?

The warning has been removed from the master branch & won't be present in PyTorch v1.10.

**Comment by lingan1996** [comment]
> > Why is this closed? I did not see a solution and I am encountering this issue. Is it a duplicate?
> 
> The warning has been removed from the master branch & won't be present in PyTorch v1.10.

This issue is still in PyTorch v1.9.0. Any solution to solve it?

**Comment by npuichigo** [comment]
Will PyTorch release a fix version like v1.9.1 to solve this?

**Comment by avijit9** [comment]
I am still experiencing the same issue!

**Comment by brian-zZZ** [comment]
SOS!!! Still encounter this issue, those warnings filled my logs, which is so annoying. Looking forward a easy solution for v.1.9.0

**Comment by imaginary-person** [comment]
> SOS!!! Still encounter this issue, those warnings filled my logs, which is so annoying. Looking forward a easy solution for v.1.9.0

How about building from source from the v1.9 release branch (https://github.com/pytorch/pytorch/tree/release/1.9), but also adding the modification from #60318?

**Comment by SeungjunNah** [comment]
@brian-zZZ 
I couldn't find any solution using the conda installation with stable versions.
I ended up building pytorch from the source after removing the line causing warning messages. (before it was fixed in master branch)
Maybe you can choose to use the nightly builds. 
I guess the update from [#60318](https://github.com/pytorch/pytorch/pull/60318) is reflected there.

**Comment by imaginary-person** [comment]
> Maybe you can choose to use the nightly builds.
> I guess the update from [#60318](https://github.com/pytorch/pytorch/pull/60318) is reflected there.

Yes, it is

**Comment by brian-zZZ** [comment]
> > SOS!!! Still encounter this issue, those warnings filled my logs, which is so annoying. Looking forward a easy solution for v.1.9.0
> 
> How about building from source from the v1.9 release branch (https://github.com/pytorch/pytorch/tree/release/1.9), but also adding the modification from #60318?

It works!! Really appreciate that!

**Comment by tensorfoo** [comment]
As a workout around, find where your logs go and tail -f the log file, it won't show the warnings.

**Comment by Maddy12** [comment]
Experiencing the issue as well when setting `fast_dev_run = 1`

**Comment by FrancescoSaverioZuppichini** [comment]
same

**Comment by Scass0807** [comment]
Same here. Need a way to suppress.

**Comment by Erotemic** [comment]
This is annoying enough that I hope the torch team seriously considers releasing a hotfix patch to 1.9 to suppress this warning.  That is, unless 1.10 would come out sooner than a hotfix could be done. 

If you guys are going to release 1.10 in the next 2 weeks, I'm fine to wait, but if it's going to take longer please consider releasing a patched version of 1.9 so I can see the text above my TQDM progress bars. I printed stuff out before the training loop for a reason. I want to see messages I printed, not "Leaking Caff2e2" warnings that I don't have any control over.

Or maybe provide a link to a pip install command for a release candidate for 1.10? My scrolling finger thanks you for any consideration that could be given to this issue.

**Comment by xkszltl** [comment]
> This is annoying enough that I hope the torch team seriously considers releasing a hotfix patch to 1.9 to suppress this warning. That is, unless 1.10 would come out sooner than a hotfix could be done.
> 
> If you guys are going to release 1.10 in the next 2 weeks, I'm fine to wait, but if it's going to take longer please consider releasing a patched version of 1.9 so I can see the text above my TQDM progress bars. I printed stuff out before the training loop for a reason. I want to see messages I printed, not "Leaking Caff2e2" warnings that I don't have any control over.
> 
> Or maybe provide a link to a pip install command for a release candidate for 1.10? My scrolling finger thanks you for any consideration that could be given to this issue.

If it's annoying enough, see if you can ask it to shut up with some glog env, e.g. `GLOG_minloglevel=2`. Not that this will disable `INFO` as well.

**Comment by Erotemic** [comment]
Setting `GLOG_minloglevel=2` didn't change the behavior. 
 
But piping stderr to null works!  Much better than the above tail workaround.

**Comment by jmskinner** [comment]
Confirming that this is still an issue an EXTREMELY annoying, also prohibitive to testing. Any idea if this could be a hot-fix?

**Comment by Bernd1969** [comment]
I can also confirm this. I use 6 worker threads to speed up my training and I get 6 red warnings for every epoch I train. thats about 30% of my output...
And why was this bug closed!? Its not fixed and there seems to be not even a valid workaround.
Pipeing stderror to dev/null is like "switch off your monitor, then you dont see it anymore", but not a solution.

**Comment by ejguan** [comment]
Can you try to use PyTorch nightly as the PR to disable the warning has landed into master branch? https://pytorch.org/get-started/locally/

**Comment by imaginary-person** [comment]
> And why was this bug closed!? Its not fixed and there seems to be not even a valid workaround.

The next PyTorch release wouldn't have this warning.

If it's not possible for you to use the nightly release (which has this warning disabled), is it possible for you to build from the 1.9 release branch, while also adding the change from #60318? Thanks

**Comment by Bernd1969** [comment]
This worked like a charm :)
> conda install pytorch -c pytorch-nighly
And yes, I will retry in a few days with stable build

**Comment by subhacom** [comment]
> 
> 
> I made:
> 
> > conda install pytorch -c pytorch-nightly
> 
> It looked like it worked, but the warning just came again :(
> I will retry in a few days with stable build
> Thx 4 fast support
> 
> P.S.: above command only updated the certificate of pytorch, but it seems it did not install anything.
> Do I need to start from scratch with my environment to actually get the nightly pytorch package? Or can I enforce the package change somehow?

This is still present in the nightly-build, even after `pip uninstall torch` followed by installing the nightly build using pip.

**Comment by ejguan** [comment]
@Bernd1969 @subhacom 
Can you use https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py to verify your environment?

**Comment by subhacom** [comment]
> 
> 
> @Bernd1969 @subhacom
> Can you use https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py to verify your environment?

My apologies for a false alarm. Upon running the script I realized that torch was still at version 1.9.0. Earlier I ran:

    pip uninstall torch
    pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html


And the installation messages look like this:

> 
> Successfully uninstalled torch-1.9.0+cu102
> Looking in links: https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
> Collecting torch
>   Downloading https://download.pytorch.org/whl/nightly/cu102/torch-1.10.0.dev20210819%2Bcu102-cp37-cp37m-linux_x86_64.whl (879.9 MB)
>      |██████████████████████████████▍ | 834.1 MB 1.4 MB/s eta 0:00:32tcmalloc: large alloc 1147494400 bytes == 0x55f3bf90c000 @  0x7fef8c5fd615 0x55f3bc70b02c 0x55f3bc7eb17a 0x55f3bc70de4d 0x55f3bc7ffc0d 0x55f3bc7820d8 0x55f3bc77cc35 0x55f3bc70f73a 0x55f3bc781f40 0x55f3bc77cc35 0x55f3bc70f73a 0x55f3bc77e93b 0x55f3bc800a56 0x55f3bc77dfb3 0x55f3bc800a56 0x55f3bc77dfb3 0x55f3bc800a56 0x55f3bc77dfb3 0x55f3bc70fb99 0x55f3bc752e79 0x55f3bc70e7b2 0x55f3bc781e65 0x55f3bc77cc35 0x55f3bc70f73a 0x55f3bc77e93b 0x55f3bc77cc35 0x55f3bc70f73a 0x55f3bc77db0e 0x55f3bc70f65a 0x55f3bc77dd67 0x55f3bc77cc35
>      |████████████████████████████████| 879.9 MB 14 kB/s 
> Requirement already satisfied: torchvision in /usr/local/lib/python3.7/dist-packages (0.10.0+cu102)
> Collecting torchaudio
>   Downloading https://download.pytorch.org/whl/nightly/torchaudio-0.10.0.dev20210819-cp37-cp37m-linux_x86_64.whl (2.0 MB)
>      |████████████████████████████████| 2.0 MB 155 kB/s 
> Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch) (3.7.4.3)
> Collecting torch
>   Downloading torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
>      |████████████████████████████████| 831.4 MB 2.9 kB/s 
> Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from torchvision) (1.19.5)
> Requirement already satisfied: pillow>=5.3.0 in /usr/local/lib/python3.7/dist-packages (from torchvision) (7.1.2)
> ...
> ...
> Installing collected packages: torch, torchaudio
> Successfully installed torch-1.9.0 torchaudio-0.9.0

So it appears that uninstalling just `torch` leaves `torchaudio` and` torchvision` in their older versions, and the `pip install ` reinstalls torch1.9.0 in order to satisfy their requirements.

Once I uninstalled all three, torch 1.10.0 installed properly, and now the warning is gone.

    pip uninstall torch torchvision torchaudio
    pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html

I suspect @Bernd1969 is experiencing the same with `conda`.

**Comment by Bernd1969** [comment]
Correct.  Subhacom's uninstall and reinstall also worked for me.
I had to use cu113 for my environment though.
And I now get another warning for every worker thread, but this seems to be a valid one that I can actually fix in my code :)

**Comment by stas00** [comment]
I'm too confirming that with today's nightly:
```
conda install -y pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly -c nvidia
```
the warnings are gone!

Thank you!

**Comment by imjiangjun** [comment]
Is there a way to suppress this before 1.9.1? My output is flooded with it. But I can't downgrade pytorch.

**Comment by xkszltl** [comment]
> Is there a way to suppress this before 1.9.1? My output is flooded with it. But I can't downgrade pytorch.

`2>/dev/null` if you're OK with it.

**Comment by 12194916** [comment]
> I confirm OP's observation that the error messages disappear for pin_memory = False. Either way, the error messages do not seem to correspond to a meaningful problem for end-users.
> 
> The warnings are very slightly different in a recent copy of the PyTorch 1.9 nightly preview. This is part of my error log:
> 
> [W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool) [W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool) [W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool) [W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool) [W pthreadpool-cpp.cc:99] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

Hi. Did changing yo "pin_memory=False" help to avoid this warning? I have the same issue.
