### ISSUE TITLE
layer identifier in powerSGD_hook

### ISSUE THREAD

**Issue by hamid-ramezani** [pytorch/pytorch#57284]
## ❓ Questions and Help

Hello everyone,

I'm looking for an identifier that specifies a neural net's layer in [this](https://github.com/pytorch/pytorch/blob/master/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py). 

Also, I would like to know if [this](https://github.com/pytorch/pytorch/blob/master/torch/distributed/algorithms/ddp_comm_hooks/powerSGD_hook.py#L364) loop iterates over all layers?  

@SciPioneer @mrshenli @SamuelMarks @samestep @ngimel @lw @izdeby 

Thanks a lot.

**Comment by seemethere** [comment]
I think this would be a better question for the forums

https://discuss.pytorch.org/

Closing, in favor of posting on the forums

**Comment by hamid-ramezani** [comment]
sure, I asked the question in the forum [here](https://discuss.pytorch.org/t/layer-identifier-in-powersgd-hook/119853/3), but I've not received a decent solution.
