### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by nikky4D** [pytorch/pytorch#57286]
## 🐛 Bug

<-- Conda install error with channel name nvidias. -->

## To Reproduce

1. New conda environment on windows environment
2. Do command: conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch nvidia
3. Error produced: usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: nvidia

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @brianjo @mruberry

**Comment by malfet** [comment]
Hmm, I believe the command should be `-c pytorch -c nvidia`

**Comment by malfet** [comment]
This should update the doc: https://github.com/pytorch/pytorch.github.io/pull/690

**Comment by seemethere** [comment]
Fixed by https://github.com/pytorch/pytorch.github.io/pull/690
