### ISSUE TITLE
I got an error like this.

### ISSUE THREAD

**Issue by lianzhibin** [pytorch/pytorch#5729]
Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/k/anaconda3/lib/python3.6/site-packages/torch/_utils.py'

**Comment by apaszke** [comment]
Please update the issue using the template that was provided (we need the system info) and describe when this error happens

**Comment by colesbury** [comment]
The `_rebuild_tensor_v2` is new in master. Most likely you're using an older version of PyTorch to open a file saved from a newer version.

Save files are backwards compatible: new versions of PyTorch can open old save files, but the reverse is not always true.

**Comment by soumith** [comment]
closing via @colesbury 's comment https://github.com/pytorch/pytorch/issues/5729#issuecomment-372828432

**Comment by hongge831** [comment]
@colesbury you are right

**Comment by HPL123** [comment]
@colesbury  How to solve this problem？

**Comment by jerpint** [comment]
@HPL123 why don't you just upgrade your pytorch distribution to 1.0.0?

**Comment by ghrua** [comment]
If you really want to save the model trianed by v1.0.0 and load it in previous pytorch version, you could using `numpy` as a middle layer. The value in state_dict is instance of `torch.Tensor`,  convert `tensor` to `numpy.array` while saving the model and convert it back using `torch.from_numpy(val)` while loading will solve this problem.
