### ISSUE TITLE
cuDNN detection failure at build time

### ISSUE THREAD

**Issue by thiell** [pytorch/pytorch#573]
We had a request from our users to install pytorch on our GPU cluster so I gave it a try and just compiled pytorch with CUDA 8.0.44 and cuDNN 5.1 within anaconda and during ./run_test.sh I can see the following:

```
~/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/__init__.py:60: UserWarning: cuDNN library has been detected, but your pytorch installation was compiled without support for it. You might want to rebuild pytorch, making sure the library is visible to the build system.
  warnings.warn("cuDNN library has been detected, but your pytorch "
```

I didn't change the environment between the build process and the tests, meaning the build scripts missed cuDNN detection. It is available in `$LD_LIBRARY_PATH` though and properly detected by other software installation on our cluster (we use lmod to manage the software environment).

So it looks like pytorch's cuDNN detection script `tools/setup_helpers/cudnn.py` doesn't care about the standard environment variables like `$LD_LIBRARY_PATH` or `$CPATH`, but simply uses the variables `$CUDNN_LIB_DIR` and `$CUDNN_INCLUDE_DIR` (or `$CUDA_HOME` but we don't install cuDNN in `CUDA_HOME`):

tools/setup_helpers/cudnn.py:
```python
    lib_paths = list(filter(bool, [
        os.getenv('CUDNN_LIB_DIR'),
        os.path.join(CUDA_HOME, 'lib'),
        os.path.join(CUDA_HOME, 'lib64'),
        '/usr/lib/x86_64-linux-gnu/',
    ]))
```

...

As a workaround, I will define these non-standard `$CUDNN_*` before building pytorch, but I wanted to let you know of the build issue.

**Comment by soumith** [comment]
thanks for letting us know, we'll add LD_LIBRARY_PATH to the detection paths.

**Comment by apaszke** [comment]
I don't think that's necessarily a build issue. As far as I remember popular build tools like CMake also ignore that variable. But I agree it can be convenient to search it too.

**Comment by apaszke** [comment]
We've decided that since no build tools take that flag into account (it's a run-time dynamic loader env variable), we're going to skip this improvement. Thanks for a suggestion though!

**Comment by thiell** [comment]
We also have `$LIBRARY_PATH` set to the current loaded environment paths for our librairies, like cuDNN. Would you consider checking this variable automatically? It is used by gcc for example, and also autotools IIRC.

https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html#Environment-Variables

**Comment by apaszke** [comment]
Ok, we can add support for `LIBRARY_PATH` and `CPATH`.

**Comment by thiell** [comment]
Thanks @apaszke!

**Comment by apaszke** [comment]
Added that to a PR (#593), so it should be in master soon.

**Comment by ngimel** [comment]
We have a CMake module to find Cudnn and download it if necessary https://github.com/NVIDIA/torch-cudnn/blob/cudnn-download/cmake/FindCUDNN.cmake.  (Caffe2 uses similar detection). Do you want to switch to something like that instead of https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cudnn.py ?

**Comment by apaszke** [comment]
@ngimel Thanks, but I don't think it'll help. We need a Python boolean in setup.py.
