### ISSUE TITLE
 UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.   input = module(input)

### ISSUE THREAD

**Issue by Blues5** [pytorch/pytorch#5733]
I'm trying to run this script translate_mm.py from https://github.com/iacercalixto/MultimodalNMT
 Error I'm getting-
home/k/old_MultimodalNMT/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
/home/k/anaconda3/lib/python3.5/site-packages/torch/nn/modules/container.py:67: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
Batch size > 1 not implemented! Falling back to batch_size = 1 ...
Building multi-modal model...
Loading model parameters.
PRED AVG SCORE: -0.4031, PRED PPL: 1.4965

print(torch.__version__)
0.3.0

**Comment by soumith** [comment]
it's not an error, it's a warning. and the message explains it pretty much.

**Comment by Blues5** [comment]
thanks for the response. I'm pretty new to this field, could you kindly tell if adding dim=X in the command MODEL_SNAPSHOT=IMGD_ADAM_acc_60.79_ppl_8.38_e4.pt
python translate_mm.py -src ~/exp/opennmt_imgd/data_multi30k/test2016.norm.tok.lc.bpe10000.en -model model_snapshots/${MODEL_SNAPSHOT} -path_to_test_img_feats ~/resources/multi30k/features/flickr30k_test_vgg19_bn_cnn_features.hdf5 -output model_snapshots/${MODEL_SNAPSHOT}.translations-test2016 should help?

**Comment by Crescentz** [comment]
File "translate_mm.py", line 69
    print "Batch size > 1 not implemented! Falling back to batch_size = 1 ..."
                                                                             ^
SyntaxError: Missing parentheses in call to 'print'

the same
