### ISSUE TITLE
TensorIteratorConfig: document that outputs must be added before inputs

### ISSUE THREAD

**Issue by shamanDevel** [pytorch/pytorch#57343]
### Issue Description

`at::TensorIteratorConfig` requires one to add first all outputs and only then all inputs
Wrong and will throw a confusing internal error in TensorIterator.cpp:

    auto iter = at::TensorIteratorConfig()
        .add_input(input1).add_input(input2).add_input(input3)
        .add_output(output1).add_output(output2)
        .build();

Correct:

    auto iter = at::TensorIteratorConfig()
        .add_output(output1).add_output(output2)
        .add_input(input1).add_input(input2).add_input(input3)
        .build();

This behavior, however, is not documented.

### Suggestions

- Add to the documentation in TensorIterator.h (at the top or before TensorIteratorConfig::add_output/add_input) the clause, that outputs have to be specified before inputs.
and/or
- Enhance the error message in https://github.com/pytorch/pytorch/blob/6032ea0313eedf239f7c70aae6a1e5252c77fa90/aten/src/ATen/TensorIterator.cpp#L22 to indicate that outputs have to be added before inputs.

cc @brianjo @mruberry

**Comment by mruberry** [comment]
We could always make our documentation better. This is probably a good opportunity to update and link the developer Wiki article on TensorIterator, too: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator.

**Comment by shamanDevel** [comment]
I'm still figuring out how to best propose changes for the Wiki (is there a contribution guide for the wiki?).
Until then, above is a short pull request that adds a few lines of documentation to TensorIterator.
I tried to stay consistent with the style of comments in the code.
