### ISSUE TITLE
Quantized module using prepare_qat_fx not picklable

### ISSUE THREAD

**Issue by kev-zheng** [pytorch/pytorch#57352]
## 🐛 Bug

A pytorch module passed through `prepare_qat_fx` is no longer picklable, due to [`_PartialWrapper`](https://github.com/pytorch/pytorch/blob/master/torch/quantization/observer.py#L26-L38).

This prevents usage of the `ddp_spawn` accelerator.

## To Reproduce

I modified this [tutorial](https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_module.html) example to run `prepare_qat_fx` and try to pickle it.

pytorch==1.8.1

```python
import torch
import pickle

from torch.quantization import get_default_qconfig
from torch.quantization.quantize_fx import prepare_qat_fx

class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Try to pickle quantized model
qconfig = get_default_qconfig("qnnpack")
qconfig_dict = {"": qconfig}

model = prepare_qat_fx(model, qconfig_dict)

pickle.dumps(model)
```

Running this file results in:
```
Traceback (most recent call last):
  File "torch_test.py", line 45, in <module>
    pickle.dumps(model)
AttributeError: Can't pickle local object '_with_args.<locals>._PartialWrapper'
```

## Expected behavior

Empty output; `pickle.dumps` should succeed

## Environment
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): OSX
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.10
 - CUDA/cuDNN version: cpu only
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
marking as high priority, the current behavior is not intuitive.  We should be able to either serialize qconfig directly or provide guidelines for an official workaround.
