### ISSUE TITLE
gpu memory not released after run `sudo kill [pytorch process id]`

### ISSUE THREAD

**Issue by Lmy0217** [pytorch/pytorch#5736]
Whenever I attempt to run the code `sudo kill [PyTorch process id]` to stop PyTorch process, I always find the GPU memory is not released.

![](https://user-images.githubusercontent.com/16065878/37334880-114926d6-26e8-11e8-97b5-0da1493e3ca5.png)

Environment details:
- OS: Ubuntu 17.10
- PyTorch version: 0.3.0
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.3
- CUDA/cuDNN version: 9.0/7.1
- GPU models and configuration: TITAN XP
- GCC version: 7.2.0

**Comment by albanD** [comment]
This is usually because some process are still alive. You can find them by doing `lsof /dev/nvidia0` and finding if any python process is listed there that should not be here. Then you can kill that process.

**Comment by alsrgv** [comment]
I second this issue.  I see this all the time with DataLoader that uses multiple processes.  Would be much better if those child processes handled signals that their parent died and terminated, too.

**Comment by soumith** [comment]
@apaszke @SsnL can we capture these signals in children and die?

**Comment by apaszke** [comment]
@soumith it's hard to tell. If you don't take any action then signals sent to the parent should also be delivered to children. This means that Python must somehow be overriding the signal handling, and it might be hard for us to revert this change without breaking other things. We could try though.

**Comment by SsnL** [comment]
@alsrgv @soumith Actually this is something that shouldn't happen often. We set on worker processes `daemon=True`, so if they are not blocked, they should exit when parent process exit... So I'm curious what @alsrgv 's setting is. Usually data loader workers shouldn't use cuda memory as well.

**Comment by apaszke** [comment]
Isn't `daemon=True` exactly the opposite (i.e. they are *not* supposed to die even if the parent does)?

**Comment by SsnL** [comment]
@apaszke Hmm Am I reading the python doc wrong?
 https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.daemon

**Comment by apaszke** [comment]
Huh, you're right!

**Comment by alsrgv** [comment]
I believe CUDA memory is pinned because I'm using `pin_memory=True`.  The processes which are left holding memory have just two threads looking like this, which looks very much like preprocessor thread:

```
(gdb) thread apply all bt

Thread 2 (Thread 0x7f266cfff700 (LWP 41632)):
#0  0x00007f270f1c8c8d in accept () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000005c2164 in ?? ()
#2  0x00000000004d34b7 in PyEval_EvalFrameEx ()
#3  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#4  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#5  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#6  0x00000000004ebff8 in ?? ()
#7  0x00000000004d03a1 in PyEval_EvalFrameEx ()
#8  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#9  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#10 0x00000000004ebff8 in ?? ()
#11 0x00000000005107f8 in ?? ()
#12 0x00000000004d881a in PyEval_CallObjectWithKeywords ()
#13 0x00000000005c1f32 in ?? ()
#14 0x00007f270f1c2064 in start_thread (arg=0x7f266cfff700) at pthread_create.c:309
#15 0x00007f270e5d462d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f270f5e5700 (LWP 41631)):
#0  0x00007f270f1c8a9d in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f2688f0e776 in ?? () from /home/asergeev/env-pytorch/lib/python2.7/lib-dynload/_multiprocessing.x86_64-linux-gnu.so
#2  0x00000000004cddf4 in PyEval_EvalFrameEx ()
#3  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#4  0x00000000004cc4f1 in PyEval_EvalCodeEx ()
#5  0x00000000004d3ce0 in PyEval_EvalFrameEx ()
#6  0x00000000004ebff8 in ?? ()
#7  0x00000000004d03a1 in PyEval_EvalFrameEx ()
#8  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#9  0x00000000004d2e77 in PyEval_EvalFrameEx ()
#10 0x00000000004ebff8 in ?? ()
#11 0x00000000005107f8 in ?? ()
#12 0x000000000050f479 in ?? ()
#13 0x00000000004be10b in ?? ()
#14 0x00000000004d3309 in PyEval_EvalFrameEx ()
#15 0x00000000004d2e77 in PyEval_EvalFrameEx ()
#16 0x00000000004ebff8 in ?? ()
#17 0x00000000005107f8 in ?? ()
#18 0x000000000050f863 in ?? ()
#19 0x00000000004be10b in ?? ()
#20 0x00000000004d3309 in PyEval_EvalFrameEx ()
#21 0x00000000004ebff8 in ?? ()
#22 0x00000000005107f8 in ?? ()
---Type <return> to continue, or q <return> to quit---
#23 0x00000000004b794e in PyObject_Call ()
#24 0x00000000005176f2 in ?? ()
#25 0x000000000053113c in ?? ()
#26 0x00000000004be025 in ?? ()
#27 0x00000000004d3309 in PyEval_EvalFrameEx ()
#28 0x00000000004cc4f1 in PyEval_EvalCodeEx ()
#29 0x00000000004d3ce0 in PyEval_EvalFrameEx ()
#30 0x00000000004cc4f1 in PyEval_EvalCodeEx ()
#31 0x000000000050a40f in ?? ()
#32 0x0000000000501a72 in PyRun_FileExFlags ()
#33 0x0000000000500187 in PyRun_SimpleFileExFlags ()
#34 0x000000000049b9fe in Py_Main ()
#35 0x00007f270e50db45 in __libc_start_main (main=0x49b490 <main>, argc=2, argv=0x7fff90e8bbd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff90e8bbc8)
    at libc-start.c:287
#36 0x000000000049b3bc in _start ()
(gdb)
```

I think the issue is that I'm working on C extension and in process of doing that are getting segfaults and are sometimes terminating script not very nicely (via -9).

All this prevent Python's `daemon` process handling.  I wrote a reproducer of my behavior with correct handling via polling `getppid()` - https://gist.github.com/alsrgv/b163c772edc76481ac2226833e08b21b.  Can this be integrated into preprocessing thread logic?
