### ISSUE TITLE
COO to CSR tensor conversion is slow

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#57381]
Originally raised in https://github.com/pytorch/pytorch/pull/50937#discussion_r604346660

The COO to CSR tensor conversion is implemented in
https://github.com/pytorch/pytorch/blob/3a777b67926c5f02bc287b25e572c521d6d11fb0/torch/_tensor.py#L928-L940
and it consists of two time-consuming parts:
- coalescing if the COO tensor is uncoaleasced
- row indices compression procedure

Indeed, taking a coalesced COO sample with `size=(1000, 1000)` and `nnz=500`, about 1.5% of the `to_sparse_csr` call time is spend in coalescing and 98% of the time in running the row indices compression loop.

The slowness of the row indices compression loop has two origins:
- it is implemented in Python
- it uses a suboptimal algorithm

Indeed, a sample of row indices with `size[0] == 1000` and `nnz=500`, a pure Python algorithm in
https://github.com/pearu/gcs/blob/b54ba0cba9c853b797274ef26b6c42386f2cafa3/gcs/storage.py#L24-L45
is about 3x faster than used in `to_sparse_csr`, and when applying `numba.njit` to the `compress_indices` function, about 83x speedup is achieved compared to `to_sparse_csr`.

The performance of COO to CSR tensor conversion can be improved by implementing a more efficient row indices compression algorithm (see `compress_indices` referenced above) in C++.

cc @VitalyFedyunin @ngimel @aocsa @nikitaved @pearu @mruberry

**Comment by ngimel** [comment]
How about using `torch.searchsorted` for this?

**Comment by pearu** [comment]
Use unsafe CSR constructor when it becomes available: https://github.com/pytorch/pytorch/pull/57274#discussion_r629580597

**Comment by pearu** [comment]
xref: [..conversion from COO to CSR is ridiculously slow on CUDA device.](https://github.com/pytorch/pytorch/issues/16187#issuecomment-869735963)

**Comment by pearu** [comment]
Since CSR `crow_indices` are always 1D, use `torch.bucketize` instead of `torch.searchsorted` for efficiency.

**Comment by cpuhrsch** [comment]
cc @rusty1s

**Comment by rusty1s** [comment]
I've done some benchmarking efforts and pushed them to the `torch-sparse` package, see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/benchmark/ptr2ind.py).

I compared the current PyTorch implementation, the `compressed_indices` implementation, a vectorized version using `bincount` and `cumsum`, and the dedicated implementation sitting in [`torch-sparse`](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/convert_cpu.cpp#L7-L35), using real-world sparse matrices:
```
citationCiteseer.mat: shape=(268495, 268495) nnz=2313294
========================================================
current:            9.76767897605896
compressed indices: 3.5093854665756226
vectorized:         0.0039603453445132535
torch-sparse:       0.001211377943671027
web-Stanford.mat: shape=(281903, 281903) nnz=2312497
====================================================
current:            9.746762037277222
compressed indices: 3.2903430461883545
vectorized:         0.0038891834196740326
torch-sparse:       0.0012816107621381125
StocF-1465.mat: shape=(1465137, 1465137) nnz=21005389
=====================================================
current:            84.82162189483643
compressed indices: 29.867455005645752
vectorized:         0.030471684715964578
torch-sparse:       0.007548295534574068
ldoor.mat: shape=(952203, 952203) nnz=42493817
==============================================
current:            169.77982473373413
compressed indices: 60.181442975997925
vectorized:         0.07296083975529326
torch-sparse:       0.014217141677032818
```

**Comment by pearu** [comment]
@rusty1s thanks for the benchmarks! A couple of notes. The benchmarks compare pure single-thread Python and parallel C++ implementations and the `1 000..10 000`-fold difference is not surprising.

If possible, could you also benchmark
- the different algorithms under the same implementation environment, that is, all in C++ using parallel_for
- using searchsorted/bucketize approach that could provide immediate CUDA backend support to COO->CSR conversion

**Comment by rusty1s** [comment]
The `torch-sparse` C++ implementation already implements the `compressed_indices` algorithms mentioned above. For the current COO2CSR PyTorch implementation, I don't think it's possible to make use of multi-threading at all.

I also updated the benchmark script to support both `searchsorted`/`bucketize` functions:
```
citationCiteseer.mat: shape=(268495, 268495) nnz=2313294
========================================================
torch-sparse: 0.00159161581043071
searchsorted: 0.005281335574898322
bucketize:    0.004996270923824101

web-Stanford.mat: shape=(281903, 281903) nnz=2312497
====================================================
torch-sparse: 0.001423873635250778
searchsorted: 0.0050520981201017745
bucketize:    0.00515870925077458

StocF-1465.mat: shape=(1465137, 1465137) nnz=21005389
=====================================================
torch-sparse: 0.011693406884915361
searchsorted: 0.03374433517456055
bucketize:    0.032992157496904075

ldoor.mat: shape=(952203, 952203) nnz=42493817
==============================================
torch-sparse: 0.017606527872488533
searchsorted: 0.030941883722941082
bucketize:    0.02959784530323638
```
Both are about 3 times slower than the current `torch-sparse` function (probably because of the extra `torch.arange` call?).

**Comment by pearu** [comment]
It sounds like torch-sparse C++/parallel_for implementation of the coo->csr operation is a way to go for CPU. Notice that this implementation needs a specialization for int64-COO -> int32-CSR because, in PyTorch, COO tensors use int64 indices while CSR tensors use int32 indices (because PyTorch is tied to LP64 MKL, and on CPU, MKL sparse tools are used for computations).
 
For indices stored on CUDA device, multiple choices are possible:
1. implement torch-sparse/compress_indices algorithm for CUDA
2. use bucketize for CUDA as a first instance when 1. is not available
3. copy indices to CPU, perform coo->csr operation using CPU method, copy crow_indices to CUDA as a first instance when 1. is not available.
4. anything else?

@rusty1s , what do you think?

**Comment by rusty1s** [comment]
I‘m in favor of option (1) or (2), and will work on that with @cpuhrsch.

**Comment by ngimel** [comment]
>For the current COO2CSR PyTorch implementation, I don't think it's possible to make use of multi-threading at all.

searchsorted/bucketize are dispatched to the same implementation, so it's not surprising that they produce similar results.
searchsorted/bucketize uses multithreading - it's doing independent binary searches for each element. Overhead from `arange` should be minimal (can be confirmed), so maybe the best thing is to add sequential implementation to searchsorted, so that all searchsorted usecases can benefit too, not just coo2csr?
