### ISSUE TITLE
[feature request][docs] Make highly visible distinction between master docs and stable docs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#5738]
Requested from here: https://discuss.pytorch.org/t/people-reading-master-docs/14847

I quote from jpeg729,
"Many, many questions on this forum come from people who have read the docs for the master branch and wonder why their code doesn’t work.

A little research reveals that the redirections are inconsistent. Maybe that is how so many people end up reading the master docs by mistake.

http://pytorch.org/docs -> http://pytorch.org/docs/0.3.1/
http://pytorch.org/docs/nn -> http://pytorch.org/docs/master/nn.html

Can I suggest that a little strategic renaming might go a long way? Namely this…

http://pytorch.org/docs/master/… -> http://pytorch.org/docs/dev/…

Can I also suggest adding to all pages of the master docs some sort of highly visible banner that says “dev version” next to a link to the docs for the latest stable version?"

**Comment by vadimkantorov** [comment]
would be good to also disable google indexing of very-very-old docs: https://github.com/pytorch/pytorch/issues/3428 in order to not fall in the pit of opencv

**Comment by jpeg729** [comment]
How about having urls of the form http://pytorch.org/docs/stable/...  ?

I would suggest that such links not redirect to http://pytorch.org/docs/0.3.whatever/..., and that such urls be the only documentation pages that google should reference.

That way both users and google will always see up to date docs of the latest stable release unless they actively search for a specific version.

Ideally there would also be a visible tag on each page to remind users which version is the stable version.
