### ISSUE TITLE
`coalesce` creates overflowed indices in large sparse COO tensors

### ISSUE THREAD

**Issue by francois-rozet** [pytorch/pytorch#57416]
## 🐛 Bug

In sparse COO tensors with high dimensionality (likely `numel > max int64`), coalescing introduces negative indices on CUDA. This results in unexpected behaviors later on. Especially, calling `to_dense` on sparse tensors with negative indices makes Python crash without error/warning.

This bug is **not** present on CPU, where `coalesce` works just fine.

## To Reproduce

```python
>>> import torch
>>> nnz = 1000
>>> indices = torch.randint(1000000, (4, nnz))
>>> indices.min()
    tensor(290)
>>> values = torch.rand(nnz)
>>> a = torch.sparse_coo_tensor(indices, values, (1000000,) * 4).coalesce()
>>> a.indices().min()  # works on CPU
    tensor(290)
>>> b = torch.sparse_coo_tensor(indices.cuda(), values.cuda(), a.shape).coalesce()
>>> b.indices().min()  # bugs on CUDA
    tensor(-996890, device='cuda:0')
```

## Expected behavior

Not introducing negative indices or warning the user that the dimensionality is too large. At the very least, `coalesce` should be consistent between CPU and CUDA.

## Environment

```
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 461.40
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.1
[pip3] torchist==0.1.4
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2021.2.0           haa95532_296
[conda] mkl-service               2.3.0            py39h2bbff1b_1
[conda] mkl_fft                   1.3.0            py39h277e83a_2
[conda] mkl_random                1.2.1            py39hf11a4ad_2
[conda] numpy                     1.20.1           py39h34a8a5c_0
[conda] numpy-base                1.20.1           py39haf7ebc8_0
[conda] pytorch                   1.8.1           py3.9_cuda10.2_cudnn7_0    pytorch
[conda] torchist                  0.1.4                    pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @aocsa @nikitaved @pearu @mruberry

**Comment by ngimel** [comment]
HIgh priority for silent wrong behavior and crashes

**Comment by pearu** [comment]
Changing
https://github.com/pytorch/pytorch/blob/52b389259c4324ab402c5c8abaf3629c48ea432e/aten/src/ATen/SparseTensorUtils.cpp#L42
to
```
.. indices.options().dtype(at::kLong).device(kCPU)); 
```
appears to fix this issue.

**Comment by francois-rozet** [comment]
Hello @pearu, reading the specification of the function I don't understand how you can prevent the indices to overflow. Especially, in the hereafter, loop `mult` can become larger than the limit of `int64_t`.

https://github.com/pytorch/pytorch/blob/52b389259c4324ab402c5c8abaf3629c48ea432e/aten/src/ATen/SparseTensorUtils.cpp#L34-L37

This is a problem as two different positions could be mapped to the same index when flattened (i.e. collisions). Ideally, `coalesce` should not rely on flattening the indices. I suppose it is necessary for some kind of sorting. If this is the case, sorting could be performed on the original indices instead. However, it will require a new "sort" that would compare indices like tuples are compared, i.e. `(1, 2, 3) < (1, 3, 3) == True`.

Alternatively, one could prevent the users to use such large shape.

**Comment by pearu** [comment]
@francois-rozet , indeed, this issue boils down to catching overflow in integer multiplication (and addition). Here's a small deterministic reproducer:
```
N = 100000
indices = torch.tensor([[N, N-1]]*4, dtype=torch.int64)
values = torch.tensor([1, 2])
s1 = torch.sparse_coo_tensor(indices, values, (N+1,) * 4).coalesce()
s2 = torch.sparse_coo_tensor(s1.indices().to(device="cuda"), s1.values().to(device="cuda"), s1.size()).coalesce()
assert (s1.indices() == s2.indices().cpu()).all()
```

**Comment by francois-rozet** [comment]
@pearu This commit resolves the problem of overflow. But it prevents the use of `coalesce` with large sparse tensors. Is there a plan to resolve that or the feature will be deprecated ?

**Comment by pearu** [comment]
> @pearu This commit resolves the problem of overflow. But it prevents the use of `coalesce` with large sparse tensors. Is there a plan to resolve that or the feature will be deprecated ?

This is a good question. The issue is not really about large sparse tensors but about the large size of tensor dimensions: the issue can be reproduced with a sparse tensor having only two elements. Also, the issue is not also about COO format that would be able to represent the problematic tensors without problems. The problem is in coalesce algorithm where sorting of indices requires reducing the indices to 1D indices. While this method is very efficient, it will restrict the size of sparse tensor dimensions because one needs to compute the corresponding strides.

There are at least two options.

1. Since the overflow can be predicted, implement a more general coalesce algorithm that can handle large dimensions when the overflow condition is met. The general algorithm will be less efficient but at least it will be usable for the given cases provided that `nnz` is not too large.

2. Construct COO tensor by avoiding coalescing. For that, provide sorted indices and values to `sparse_coo_tensor`, and use `_coalesce_` method to set coalesce flag True. For example:

```python
import torch
dtype = torch.double
device = 'cuda'
nnz = 6
N = 1000000
size = (N,) * 4

indices = torch.randint(N, (4, nnz))
values = torch.rand(nnz)

try:
    s1 = torch.sparse_coo_tensor(indices, values, size, device=device).coalesce()
except RuntimeError as msg:
    # assuming PR 57492
    print(f'failed to coalesce: {msg}')
else:
    print(s1)
    print("increase N to reproduce gh-57416")
    
ordering = torch.tensor(sorted(range(nnz), key=lambda i: tuple(indices[:, i])))
sorted_indices = torch.index_select(indices, 1, ordering)
sorted_values = torch.index_select(values, 0, ordering)
s2 = torch.sparse_coo_tensor(sorted_indices, sorted_values, size, device=device)._coalesced_(True)
print(s2)
```
outputs
```
failed to coalesce: flatten_indices: detected overflow in integer multiplication
tensor(indices=tensor([[178258, 191348, 213864, 537921, 752025, 875000],
                       [443014, 432689, 441252, 328507, 512408, 403736],
                       [ 94167, 885899, 219770, 839360,  36765, 156705],
                       [781265, 989762,  26835, 258886, 445059, 891790]]),
       values=tensor([0.7456, 0.1157, 0.7399, 0.5397, 0.5580, 0.7280]),
       device='cuda:0', size=(1000000, 1000000, 1000000, 1000000), nnz=6,
       layout=torch.sparse_coo)
```

**Comment by francois-rozet** [comment]
@pearu Large dimensionality is what I meant by large sparse tensors 😅 

The first solution (which I already mention [here](https://github.com/pytorch/pytorch/issues/57416#issuecomment-831489701)) seems more suitable, as the second one will prevent a lot of common operations (sums, products, ...).

By the way, I don't know how these operations are implemented, but they likely also use `flatten_indices` currently.

**Comment by pearu** [comment]
> @pearu Large dimensionality is what I meant by large sparse tensors 

Yes, this makes sense too :)

Although, large dimensionality does not necessarily mean large nnz which is often the parameter that determines if a sparse tensor is large or not in terms of memory consumption.

Currently, pytorch supports arbitrary tensor sizes provided that `product(<tensor shape>)` is less than max of int64.
What would be the typical dimensionality (the number of dimensions) and dimensions sizes in your applications?

> The first solution (which I already mention [here](https://github.com/pytorch/pytorch/issues/57416#issuecomment-831489701)) seems more suitable, as the second one will prevent a lot of common operations (sums, products, ...).
>
> By the way, I don't know how these operations are implemented, but they likely also use `flatten_indices` currently.

`flatten_indices` is an implementation detail, the question here is rather if the corresponding operations need to use `coalesce` or not.

**Comment by francois-rozet** [comment]
@pearu 

> `flatten_indices` is an implementation detail, the question here is rather if the corresponding operations need to use coalesce or not.

I don't think it is a detail. Element-wise multiplication doesn't need the tensors to be coalesced since multiplication is **distributive** with respect to summation. However, it does require to **compare** indices which is probably performed with (or like in) `flatten_indices` currently and, therefore, doesn't work for large-dimensionality sparse tensors.

What I want to say is that there is probably more than `coalesce` to modify if you want to support such dimensionality. I don't **need** PyTorch to support that for **my** applications, I already have a workaround.

By the way, `torch.unique` and `torch.unique_consecutive` already exists and are fairly similar to `coalesce` (minus the values). They can be an inspiration for it. If I knew how to edit the `C++` files, I would try a PR, but I don't unfortunately ...

**Comment by pearu** [comment]
For element-wise multiplication, `flatten_indices` is not required because the result is defined by element-wise multiplication of sparse tensor values while indices are kept fixed.

Actually, supporting large sparse tensors is already blocked by `numel` property, see https://github.com/pytorch/pytorch/issues/57542 .

**Comment by francois-rozet** [comment]
> For element-wise multiplication, flatten_indices is not required because the result is defined by element-wise multiplication of sparse tensor values while indices are kept fixed.

I don't think this is true. A quick proof that element-wise multiplication modifies the indices:

```python
>>> N, D = 1000000, 4
>>> indices = torch.tensor([[N - 1, N - 2]] * D).cuda()
>>> values = torch.tensor([1, 2]).cuda()
>>> arr = torch.sparse_coo_tensor(indices, values, (N,) * D)
>>> arr._indices()
tensor([[999999, 999998],
        [999999, 999998],
        [999999, 999998],
        [999999, 999998]], device='cuda:0')
>>> (arr * arr)._indices()
tensor([[     1,      2],
        [  3763,   3764],
        [205205, 205206],
        [896638, 896639]], device='cuda:0')
```

**Comment by pearu** [comment]
> > For element-wise multiplication, flatten_indices is not required because the result is defined by element-wise multiplication of sparse tensor values while indices are kept fixed.
> 
> I don't think this is true. A quick proof that element-wise multiplication modifies the indices:

No, it does not prove anything because the indices are just wrong due to the signed int overflow. Try smaller N, say, 100.

**Comment by pearu** [comment]
> > For element-wise multiplication, flatten_indices is not required because the result is defined by element-wise multiplication of sparse tensor values while indices are kept fixed.
> 
> I don't think this is true. 

Just to be clear: element-wise multiplication does not require `flatten_indices` in theory. However, it does not necessarily mean that the current implementation does not use `flatten_indices`, say, when coalescing the result (which would be another operation than mul).

**Comment by francois-rozet** [comment]
I never said that element-wise multiplication requires `flatten_indices`. I said 

> [element-wise multiplication] does require to compare indices which is probably performed with (or like in) `flatten_indices`

You **have to** compare indices in such element-wise operations, otherwise you will not be able to multiply the respective values together. And this comparison is probably performed on flattened indices currently (not necessarily obtained with `flatten_indices`). Once again,

> What I want to say is that there is probably more than `coalesce` to modify if you want to support such dimensionality.

**Comment by pearu** [comment]
> > [element-wise multiplication] does require to compare indices which is probably performed with (or like in) `flatten_indices`
> 
> You **have to** compare indices in such element-wise operations, otherwise you will not be able to multiply the respective values together. And this comparison is probably performed on flattened indices currently (not necessarily obtained with `flatten_indices`).

For element-wise multiplication, one needs an intersection of operands indices. In short, see the implementation:

https://github.com/pytorch/pytorch/blob/42d073a7e9b338ee3d9224d525ca0383b6272af9/aten/src/ATen/native/sparse/SparseTensorMath.cpp#L734

that shows that one needs to coalesce the operands before multiplying values..

> Once again,
> 
> > What I want to say is that there is probably more than `coalesce` to modify if you want to support such dimensionality.

Indeed, there is. Both `coalesce` and `numel` are the methods that block supporting large dimensions because both of these compute `product(size)` (or equivalent expressions containing products of dimensions, e.g. strides) which will overflow for large dimensions.
