### ISSUE TITLE
Subclassing torch.Tensor with __new__ fails due to a TypeError on latest nightly build for the past few days

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#57421]
## 🐛 Bug

Subclassing torch.Tensor with `__new__` fails due to a `TypeError` on the latest nightly builds, whereas it previously worked without issue.

## To Reproduce

Run this snippet of code:

```
import torch

class TestTensor(torch.Tensor):
    @staticmethod
    def __new__(
        cls,
        x,
        *args,
        **kwargs,
    ) -> torch.Tensor:
        return super().__new__(cls, x, *args, **kwargs)


x = torch.ones(5)
test_tensor = TestTensor(x)
```

And you'll recieve an error message like this:

```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-6-77d4002263e6> in <module>()
     13 
     14 x = torch.ones(5)
---> 15 test_tensor = TestTensor(x)

<ipython-input-6-77d4002263e6> in __new__(cls, x, *args, **kwargs)
      9         **kwargs,
     10     ) -> torch.Tensor:
---> 11         return super().__new__(cls, x, *args, **kwargs)
     12 
     13 

TypeError: object.__new__(TestTensor) is not safe, use Tensor.__new__()
```

Changing the `return super().__new__(cls, x, *args, **kwargs)` to `return torch.Tensor.__new__(cls, x, *args, **kwargs)` results in the exact same error message.

## Expected behavior

There should be no error message as it should be working like it was previously in Torch 1.8.1 and below.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0.dev20210501+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 11.0.221
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0.dev20210501+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.1
[pip3] torchvision==0.10.0.dev20210501+cu111
[conda] Could not collect
```

I think that the issue started on Torch version: `torch-1.9.0.dev20210429+cpu`, and I can confirm that it still exists as of `torch-1.9.0.dev20210502+cu111`, `torch-1.9.0.dev20210503`.

## Additional context

The issue started on the nightly builds at least 2 days ago, if that helps resolve things. 

It's been causing some of Captum's CircleCI tests to fail, and the tests show the first occurrence of the error on `torch-1.9.0.dev20210429+cpu`.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @hameerabbasi @rgommers @peterbell10

**Comment by ezyang** [comment]
This is due to either https://github.com/pytorch/pytorch/pull/56147 or https://github.com/pytorch/pytorch/pull/56150

**Comment by ezyang** [comment]
I think the problem is I'm not supposed to delete `tp_new` because that means the super() call doesn't work. Instead, I should just verify that the passed in class is a subclass, then this should work.
