### ISSUE TITLE
ConvTranspose config error in prepare API

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#57420]
## 🐛 Bug

As reported in https://discuss.pytorch.org/t/model-quantization-fails-but-the-network-architecture-looks-ok/119750, the quantization APIs throw an error even if the user specifies Quant Dequant modules around ConvTranspose modules in the network for per-channel qconfig. 
Ideally, we should throw an error only if the user tries to quantize ConvTranspose with per-channel and take the placement of Quant/Dequant into consideration. This can be done by throwing the error when the operator is called, for example.

Code triggering the error - https://github.com/pytorch/pytorch/blob/master/torch/quantization/qconfig.py#L133-L140

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
This is intended, if a user specifies a qconfig for ConvTranspose which is not going to work at runtime, we should throw an error as early as possible.  Your suggestion on the discuss thread of setting qconfig=None for these looks good to me.
 
I'm not sure if specifying quant/dequant around the module would help if qconfig != None, in Eager mode any module with a set qconfig and defined quantization swaps would be replaced.
