### ISSUE TITLE
test_eig_with_eigvec_cuda_float64 (TestTensorDeviceOpsCUDA) is failing intermittently on ROCm

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#57422]
https://github.com/pytorch/pytorch/blob/20085f6d2364c4acf526f4eb303b8623207f0d48/test/test_torch.py#L7884

Interestingly the OpInfo for eig and linalg.eig skips ROCm:

https://github.com/pytorch/pytorch/blob/4350d4af774fd5e6e8e6d1db5d2b30643907e0b8/torch/testing/_internal/common_methods_invocations.py#L5062

https://github.com/pytorch/pytorch/blob/4350d4af774fd5e6e8e6d1db5d2b30643907e0b8/torch/testing/_internal/common_methods_invocations.py#L4225

To resolve this issue, we should validate that we don't want to test eig on ROCm and, if we still don't, remove the redundant linear algebra entries from this test_torch.py test class (we can also take the opportunity to remove the linalg entries for other operations in this list),

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by mruberry** [comment]
Will be fixed by https://github.com/pytorch/pytorch/pull/56284

**Comment by IvanYashchuk** [comment]
The tests from `test_torch.py` are being removed in https://github.com/pytorch/pytorch/pull/56284.
As for the validness of skipping the ROCm build, I can build it later and see how MAGMA-based functions work and what skips we can avoid.
