### ISSUE TITLE
Various vector optimizations pushed for Intel CPUs cause lots of issues

### ISSUE THREAD

**Issue by phalexo** [pytorch/pytorch#57463]
## 🐛 Bug

[1541/5781] Building CXX object caffe2/CMakeFiles/vec256_test_all_types_DEFAULT.dir/__/aten/src/ATen/test/vec256_test_all_types.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 818, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/home/developer/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/developer/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/developer/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/developer/anaconda3/envs/pytorch/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.

## To Reproduce
Just trying to follow instructions from the PyTorch's build from source page causes the error and stops building.

The build process also has a serious issue assuming all the time that just because an installed gcc/g++ has a flag for a specific instruction set, that is the actual architecture. No! It should build either for a generic x86_64 or to actually test the CPU to figure out the architecture. I tried multiple versions of gcc and g++.

Third party codes cause all the problems and there is no clean way to turn things off.

1.
1.
1.

## Expected behavior
I expect it to use the openmpi that has been compiled for, installed on, and tested to work on my server. 

## Environment
Ubuntu, gcc-7, g++-7
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @malfet @seemethere @walterddr

**Comment by imaginary-person** [comment]
You're probably running out of memory. Your build process is using 32 workers.
How much RAM do you have? On a 32 core system, with `MAX_JOBS=32`, I've even seen PyTorch's build process sometimes having a peak memory utilization of 40+ GB!
Use the environment variable `MAX_JOBS` with a lower value.
For example, `MAX_JOBS=4 python setup.py install`.

**Comment by phalexo** [comment]
I have around 300GB. It was not RAM. After trying literally hundreds of
combos and tweaking cmake files, changing the loader and assembler from
version 24 to 26 did the trick.

**Comment by imaginary-person** [comment]
Ah, I just recollected that I had run into the [same issue](https://github.com/pytorch/pytorch/issues/52886) on a system with 384 GB RAM. The build had failed with the very same error! The issue was that I was running out of disk space (that was required for temporary space). I mounted an external drive & things worked fine.

So, I think that changing the assembler & loader might be more of a confounding factor here.

Anyway, I'm glad you were able to fix that problem, Please feel free to close this issue.
