### ISSUE TITLE
error: identifier "cusparseScsrmm2" is undefined

### ISSUE THREAD

**Issue by PKUFlyingPig** [pytorch/pytorch#57461]
## 🐛 Bug

I tried to build pytorch v1.3.0 from source with CUDA11. But during compiling, 'error: identifier "cusparseScsrmm2" is undefined' occurred.
## To Reproduce

1. conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
2. conda install -c pytorch magma-cuda110
3. git clone --recursive https://github.com/pytorch/pytorch
4. cd pytorch
5. git submodule sync
6. git submodule update --init --recursive 
7. export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
8. python setup.py install

--   USE_DISTRIBUTED       : ON
--     USE_MPI             : ON
--     USE_GLOO            : ON
--   BUILD_NAMEDTENSOR   : OFF
--   Public Dependencies  : Threads::Threads;caffe2::mkl;caffe2::mkldnn
--   Private Dependencies : qnnpack;pytorch_qnnpack;nnpack;cpuinfo;/usr/lib64/libnuma.so;fp16;/usr/local/lib/libmpi.so;gloo;aten_op_header_gen;foxi_loader;rt;gcc_s;gcc;dl
-- Configuring done
-- Generating done
-- Build files have been written to: /home/CORP.PKUSC.ORG/flyingpig/pytorch/build
[1/1636] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/torch_generated_SparseCUDABlas.cu.o
FAILED: caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/torch_generated_SparseCUDABlas.cu.o
cd /home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda && /home/CORP.PKUSC.ORG/flyingpig/anaconda3/envs/pipeswitch/bin/cmake -E make_directory /home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/. && /home/CORP.PKUSC.ORG/flyingpig/anaconda3/envs/pipeswitch/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/./torch_generated_SparseCUDABlas.cu.o -D generated_cubin_file:STRING=/home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/./torch_generated_SparseCUDABlas.cu.o.cubin.txt -P /home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/torch_generated_SparseCUDABlas.cu.o.Release.cmake
/home/CORP.PKUSC.ORG/flyingpig/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu(128): error: identifier "cusparseScsrmm2" is undefined

/home/CORP.PKUSC.ORG/flyingpig/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu(151): error: identifier "cusparseDcsrmm2" is undefined

2 errors detected in the compilation of "/home/CORP.PKUSC.ORG/flyingpig/pytorch/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu".
CMake Error at torch_generated_SparseCUDABlas.cu.o.Release.cmake:281 (message):
  Error generating file
  /home/CORP.PKUSC.ORG/flyingpig/pytorch/build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/./torch_generated_SparseCUDABlas.cu.o

[2/1636] Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/operators/torch_generated_cross_entropy_op.cu.o
In file included from /usr/local/cuda/include/cub/block/specializations/../../block/../util_arch.cuh:36:0,
                 from /usr/local/cuda/include/cub/block/specializations/../../block/../config.cuh:35,
                 from /usr/local/cuda/include/cub/block/specializations/../../block/block_raking_layout.cuh:37,
                 from /usr/local/cuda/include/cub/block/specializations/block_reduce_raking.cuh:36,

## Expected behavior

compile successfully
## Environment
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.7.1908 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB
GPU 4: Tesla V100-PCIE-16GB
GPU 5: Tesla V100-PCIE-16GB
GPU 6: Tesla V100-PCIE-16GB
GPU 7: Tesla V100-PCIE-16GB

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.7.5.0
/usr/lib64/libcudnn.so.8.0.5
/usr/lib64/libcudnn_adv_infer.so.8.0.5
/usr/lib64/libcudnn_adv_train.so.8.0.5
/usr/lib64/libcudnn_cnn_infer.so.8.0.5
/usr/lib64/libcudnn_cnn_train.so.8.0.5
/usr/lib64/libcudnn_ops_infer.so.8.0.5
/usr/lib64/libcudnn_ops_train.so.8.0.5

## Additional context

I read some other related issues, which said build from master may solve the problem. But due to my personal reason, I have to build the v1.3.0.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @aocsa @nikitaved @pearu @mruberry

**Comment by mruberry** [comment]
@aocsa and @pearu, looks like this function is deprecated and maybe removed in the latest cuSPARSE? We might need a version check to guard this. Would one of you two be able to take a look?

**Comment by malfet** [comment]
Does this failure reproduces if PyTorch-1.7 or later is used? (Please note, that CUDA-11 was not yet available when PyTorch-1.3 was released)

**Comment by aocsa** [comment]
> @aocsa and @pearu, looks like this function is deprecated and maybe removed in the latest cuSPARSE? We might need a version check to guard this. Would one of you two be able to take a look?

Sure I will look this.

**Comment by aocsa** [comment]
> PyTorch

That's true. PyTorch 1.3 don't support CUDA-11. CUDA-11 is supported since PyTorch-1.7. 

https://github.com/pytorch/pytorch/blob/de394b672d0346f2f387a8bb1a1280d5d2eaf9cb/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L12

I recompiled PyTorch-1.7 and the most recent version with CUDA-11. So  this issue can't be reproduced,  I think this issue can be closed.

**Comment by ezyang** [comment]
yeah, we're not going to fix this.
