### ISSUE TITLE
Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by HBolandi** [pytorch/pytorch#57473]
My code was working properly prior to adding the self attention layer. Then I replaced one of the deconv layers with self attention layer. The new code is working with dp but for ddp raised with error below:

"RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable)."

class multihead(nn.Module):
          def __init__(self, input_size, heads, dimension):
              super(multihead, self).__init__()
              self.h, self.d = heads, dimension
              self.lq = nn.Linear(input_size, self.h * self.d)
              self.lk = nn.Linear(input_size, self.h * self.d)
              self.lv = nn.Linear(input_size, self.h * self.d)
              self.fc = nn.Linear(self.h * self.d, self.d)
              self.softmax = nn.Softmax(dim=3)

    def forward(self, q, k, v):
              b, n_q, n_k, h, d = q.size(0), q.size(1), k.size(1), self.h, self.d
      
              q, k, v = self.lq(q), self.lk(k), self.lv(v)                    # b, n_*, h*d
              _q, _k, _v = map(lambda x: x.reshape(b, -1, h, d), [q, k, v])   # b, n_*, h, d
              qk = torch.einsum('bnhd,bmhd->bhnm', (q,k))                     # b, h, n_q, n_k
              att = self.softmax(qk / (self.d ** .5))                         # b, h, n_q, n_k
              att_out = torch.einsum('bhnm,bmhd->bnhd', (att,v))              # b, n_q, h, d
              return att_out    
    
    
class Model(pl.LightningModule):
        def __init__(self, num, kernel, num_filters, 
                     criterion = criterion, res = ResidualBlock, attn= multihead):
            super(Model, self).__init__()
          
        self.conv0 = nn.Sequential(
            nn.Conv2d(4, num_filters, kernel_size = kernel*3, 
                       padding = 4),
            nn.BatchNorm2d(num_filters),
            nn.ReLU(inplace=True))
                         
        self.conv1 = nn.Sequential(
            nn.Conv2d(num_filters, 32, kernel_size = kernel, 
                      stride=2, padding = 1),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True))
                           
        self.conv2 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size = kernel, stride=2, padding = 1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True))
                                  
        self.conv3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size = kernel, stride=2, padding = 1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True))        
                
        self.conv4 = nn.Sequential(
            nn.Conv2d(128, 256, kernel_size = kernel, stride=2, padding = 1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True))
                        
        self.conv5 = nn.Sequential(
            nn.Conv2d(256, 512, kernel_size = kernel, stride=2, padding = 1),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True))           
        
        self.conv6 = nn.Sequential(
            nn.Conv2d(512, 1024, kernel_size = kernel, stride=2, padding = 1),
            nn.BatchNorm2d(1024),
            nn.ReLU(inplace=True))
                        
        self.tsconv0 = nn.Sequential(
            nn.ConvTranspose2d(1024, 512, kernel_size = kernel, padding =2),
            nn.Upsample(size=(20,20), mode='bilinear', align_corners=True),
            nn.ReLU(inplace=True),
            nn.BatchNorm2d(512))
    
        self.attn=attn(20,2,10)
      
        self.tsconv2 = nn.Sequential(
            nn.ConvTranspose2d(512, 128, kernel_size = kernel, padding = 1),
            nn.Upsample(size=(75,75), mode='bilinear', align_corners=True),
            nn.ReLU(inplace=True),
            nn.BatchNorm2d(128))
        
        self.tsconv3 = nn.Sequential(
            nn.ConvTranspose2d(128, 64, kernel_size = kernel, padding = 1),
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.ReLU(inplace=True),
            nn.BatchNorm2d(64))
        
        self.tsconv4 = nn.Sequential(
            nn.ConvTranspose2d(64, 32, kernel_size = kernel, padding = 1),
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.ReLU(inplace=True),
            nn.BatchNorm2d(32))
        
        self.tsconv5 = nn.Sequential(
            nn.ConvTranspose2d(32, num_filters, kernel_size = kernel, padding = 1),
            nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True),
            nn.ReLU(inplace=True),
            nn.BatchNorm2d(num_filters))
        
        self.tsconv6 = nn.Sequential(
            nn.Conv2d(num_filters, 1, kernel_size = kernel*3, padding = 4, bias=True),
            nn.ReLU(inplace=True))
        
        self.num = num
        
        self.mseloss = nn.MSELoss(reduction='mean')
        self.l1loss = nn.L1Loss(reduction='mean')
        self.criterion = criterion                
        
    def forward(self, x):
        x = self.conv0(x)          #([12, 600, 600])
        x = self.conv1(x)         #([32, 300, 300])
        x = self.conv2(x)         #([64, 150, 150])
        x = self.conv3(x)          #([128, 75, 75])
        x = self.conv4(x)          #([256, 38, 38])
        x = self.conv5(x)          #([512, 19, 19])
        x = self.conv6(x)          #([1024, 10, 10])

        x = self.tsconv0(x)        #([512, 20, 20])
        a = self.attn(x, x, x)        #([256, 10, 10)
        x = a+x
        x = self.tsconv2(x)        #([128, 75, 75])
        x = self.tsconv3(x)        #([64, 150, 150])
        x = self.tsconv4(x)        #([32, 300, 300])
        x = self.tsconv5(x)        #([12, 600, 600])
        x = self.tsconv6(x)        #([1, 600, 600])
        return x

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 450.51.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.2.1
[pip3] pytorch-lightning-bolts==0.3.0
[pip3] torch==1.7.1
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl  
[conda] libblas                   3.8.0                    21_mkl    conda-forge
[conda] libcblas                  3.8.0                    21_mkl    conda-forge
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch-lightning         1.2.1                    pypi_0    pypi
[conda] pytorch-lightning-bolts   0.3.0                    pypi_0    pypi
[conda] torch                     1.7.1                    pypi_0    pypi
[conda] torchvision               0.8.2                    pypi_0    pypi

Error trace back:

Traceback (most recent call last):
  File "/home/exx/Documents/Hamed/Lab1528/Second Paper/6conv-3res-1024chanels-lighting-batch16-AllData-Damaged-self-att.py", line 380, in <module>
    trainer.fit(model)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 650, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 426, in optimizer_step
    model_ref.optimizer_step(
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1384, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 219, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 135, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 278, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 283, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 160, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/optim/adamw.py", line 65, in step
    loss = closure()
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 644, in train_step_and_backward_closure
    result = self.training_step_and_backward(
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 738, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 157, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 287, in training_step
    return self.model(*args, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/exx/anaconda3/envs/spyder-env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 606, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
Hey @HBolandi, could you please confirm the two potential causes listed in the error message are not relevant?

(1) passing the keyword argument find_unused_parameters=True to torch.nn.parallel.DistributedDataParallel; 
(2) making sure all forward function outputs participate in calculating loss.

I guess the (2) is not relevant as your `forward` function only returns a single tensor. 

I saw your module is inheriting from `pl.LightningModule`. Does this mean you won't call DDP ctor in your code and instead Lightning will create DDP instances for you?

**Comment by rohan-varma** [comment]
Thanks for the comments @mrshenli!

@HBolandi It looks like you're using PyTorch Lightning, would you be able to try passing `find_unused_parameters=True` to DDP (not sure what setting PL uses by default, but ideally it should be False, same as DDP). I believe PL has a notion of DDPPlugin that you can use to configure this - https://pytorch-lightning.readthedocs.io/en/latest/benchmarking/performance.html#when-using-ddp-set-find-unused-parameters-false

**Comment by HBolandi** [comment]
Thanks for the comments @mrshenli!, rohan-varma

I passed the "plugins=DDPPlugin(find_unused_parameters=True)" into pl.trainer() and worked.

**Comment by rohan-varma** [comment]
Sounds good! Closing this out
