### ISSUE TITLE
Tensor.flatten method signature has an extra "input" parameter

### ISSUE THREAD

**Issue by xfrenette** [pytorch/pytorch#57478]
## 📚 Documentation

The [`Tensor.flatten` documentation](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.flatten) lists `input` as the first parameter but this method doesn't accept this parameter. It looks like this method has (incorrectly) the same signature as [`torch.flatten()`](https://pytorch.org/docs/1.8.1/generated/torch.flatten.html#torch.flatten).

cc @brianjo @mruberry

**Comment by anjali411** [comment]
@xfrenette thanks for filing the issue! we'll accept a PR fixing this doc issue.
