### ISSUE TITLE
Profiler creates sequence numbers that are off by 1 between the forward and backwards pass

### ISSUE THREAD

**Issue by puririshi98** [pytorch/pytorch#57476]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/20074092/116919648-6d644080-ac06-11eb-9b2a-82dfa770962d.png)

As seen in this screenshot, the sequence number of 4 for the conv2D forward pass matches up to a sequence number of 5 for the backward pass. These numbers being off by 1 could make keeping track of forward and backward passes difficult in a much more complicated network. This bug was found while fixing another bug where aten kernels would not output the kernel name in the profiler:
https://github.com/pytorch/pytorch/pull/57407

## To Reproduce

1. Get version including previous bugfix: https://github.com/puririshi98/pytorch/tree/nvtxstringfix
2. Build from source
3.  bash runme_nvtx.sh (attached)

[Downloads.zip](https://github.com/pytorch/pytorch/files/6416678/Downloads.zip)

## Expected behavior
The sequence numbers should match exactly between the forward and backwards pass so that a user can match them easily for debugging purposes.

## Environment

 - PyTorch Version 1.9 from public master repo:
 - OS Linux:
 - PyTorch installed from source including change from the aforementioned PR: python3 setup.py develop
 - Python version: 3.8
 - CUDA/cuDNN version: 11.3

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by ngimel** [comment]
cc @ilia-cher

**Comment by sraikund16** [comment]
Closing as this is stale/not relevant
