### ISSUE TITLE
[package] os.path error

### ISSUE THREAD

**Issue by Lilyjjo** [pytorch/pytorch#57490]
## 🐛 Bug

Importing `os.path` causes `PackageImporter` to throw this error:
```
  File "/home/lillianjohnson/local/pytorch/torch/package/package_importer.py", line 377, in _find_and_load
    return self._do_find_and_load(name)
  File "/home/lillianjohnson/local/pytorch/torch/package/package_importer.py", line 365, in _do_find_and_load
    raise ModuleNotFoundError(msg, name=name) from None
ModuleNotFoundError: No module named 'os.path'; 'os' is not a package
```

## To Reproduce

Add this line to a module that is being imported, and then try to package an object that is dependent on the module:

```
import os.path
```

**Comment by Lilyjjo** [comment]
#53114 provides a solution to the issue, but I'm not sure if is the correct solution. 

The issue seems to be that even though `os` isn't a package, you can import `path` from `os` as if `os` is a package.
```
>>> import os.path
>>> os.__package__
''                                     # os is not a package
>>> import test.support
>>> test.__package__ 
'test'                                 # test is a package
>>> 
```

**Comment by Lilyjjo** [comment]
What is happening is that os.py module manipulates `sys.modules` with: '`sys.modules['os.path'] = path`' where `path` is a dynamically determined module, creating `path` as a module attribute on `os`. Our current code will throw an error on import because when processing statements like `import os.path` we check to make sure that parent modules like `os` are actually packages

**Comment by Lilyjjo** [comment]
Issue isn't reproducible on master; closing for now 😳🤨

**Comment by kyleung271** [comment]
@Lilyjjo 
In both 1.9.0 stable and 1.10.0 nightly with cuda 11.1, The os.path error bug appeared when both `import os` and `import os.path` are used.

[test.zip](https://github.com/pytorch/pytorch/files/6667896/test.zip)

**Comment by Lilyjjo** [comment]
@kyleung271 thank you for bringing this up! I can confirm it's reproducing again. I'll take a look

**Comment by Lilyjjo** [comment]
This issue can be reproduced with the following steps:
1.) Have a module (not a package!) perform the odd sys.modules reassignment to create a fake submodule
```
# module_not_a_package.py
import time as oops
import sys
sys.modules['module_not_a_package.oops'] = oops
```
2.) Have a module import both the module and the magic-fake submodule (same problem arises when imports occur across different modules)
```
# module.py
import torch
import module_not_a_package
import module_not_a_package.oops

class Module(torch.nn.Module):
    def forward(self):
        print(module_not_a_package.oops.time())
        return
```
3.) Extern the module and the submodule, the load_pickle call will fail 
```
# test script to run
import torch
import torch.package as package
from module import Module

model = Module()
model() # call works fine

with package.PackageExporter('test.zip', verbose=True) as exp:
    exp.extern(["sys", "module_not_a_package.**"]) # externs package
    exp.intern('**')
    exp.save_pickle("test", "test.pkl", model)

imp = package.PackageImporter('test.zip')
model_imported = imp.load_pickle("test", "test.pkl") # load breaks
model_imported()
```

This is due to how we're handling externed nodes in the PackageImporter. Other combinations of not externing both the module and fake submodule, externing neither module or fake submodule, and only importing either the module or fake submodule-- all of these either work or fail in the PackageExporter step (which is fine). What we do want to solve for is having the load_pickle break for this specific case outlined above, because that is annoying and projects will probably import both 'os' and 'os.path'.
