### ISSUE TITLE
torch.size for cfloat or cdouble

### ISSUE THREAD

**Issue by scaomath** [pytorch/pytorch#57518]
## 🚀 Feature
Add a switch in `size` function for complex tensors to return the dimension of real part and complex part as a stacked dimension.

## Motivation
Right using the old counting params snippet I have:
```python
x = nn.Parameter(torch.rand(3, 5, dtype=torch.cfloat))
n_params = sum([np.prod(p.size()) for p in x])
```
We will get 15. However, in training a single entry in `cfloat` or `cdouble` is treated as two degrees of freedom. This means that in `x` there are actually 30 parameters.

## Pitch
`x.size()` gives `(3, 5)`;  `x.size(return_couple=True)` gives `(3, 5, 2)`; `x.size(1, return_couple=True)` returns `(5, 2)`.

## Additional context
Thoughts?

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @albanD @jbschlosser

**Comment by anjali411** [comment]
I am not familiar with the `return_couple` argument. Parameters are a Tensor subclass, so I think the size should return the true size of the complex tensor. cc. @jbschlosser

**Comment by SsnL** [comment]
well, `x.numel() * (1 + x.is_complex())`? or you cam `x.view_as_complex` in forward.

**Comment by Lezcano** [comment]
A mathematical take on this:

Whenever you work with complex vector spaces (or complex geometric things) you have two notions of dimension: the real and the complex dimension often denoted as `dim_R` and `dim_C`. More formally, a complex vector space of (complex) dimension `n` is a real vector space of (real) dimension `2n` with some extra structure. 

@rgommers does numpy have anything like this? 

As such, I think it'd be reasonable to be able to express this mathematical notion in PyTorch. Now, it is not clear to me what would be a good API. Perhaps `x.size(real=True)`? I do not know. In any case, if anything like this goes in, the same should be added to `nelement()`, `numel()` and any other related alias that there might be.

**Comment by rgommers** [comment]
> @rgommers does numpy have anything like this?

No, an element is a single unit, no matter what dtype the array has. There are not only complex dtypes, but string, object, datetime, etc. dtypes. 

Special-casing syntax for complex dtypes seems weird to me, and `x.size(return_couple=True)` looks like just a verbose way of spelling `x.size() + (2,)`, so I'm -1 on this feature request.

**Comment by scaomath** [comment]
> well, `x.numel() * (1 + x.is_complex())`? or you cam `x.view_as_complex` in forward.

I will do this. Thanks for the comment.
