### ISSUE TITLE
AdaptiveMaxPool1d selecting incorrect values

### ISSUE THREAD

**Issue by sserr23** [pytorch/pytorch#5751]
Pytorch version: 0.2.0_4

When providing an output size n>1 as the parameter for AdaptiveMaxPool1d, it seems like the lowest value returned in each dimension (i.e., the nth largest value) is incorrect.

```import torch
b = torch.FloatTensor([i for i in range(30)]).view(3, 2, 5)
b = torch.autograd.Variable(b)
m2 = torch.nn.AdaptiveMaxPool1d(2)
m3 = torch.nn.AdaptiveMaxPool1d(3)

b
Variable containing:
(0 ,.,.) = 
   0   1   2   3   4
   5   6   7   8   9

(1 ,.,.) = 
  10  11  12  13  14
  15  16  17  18  19

(2 ,.,.) = 
  20  21  22  23  24
  25  26  27  28  29
[torch.FloatTensor of size 3x2x5]

m2(b)
Variable containing:
(0 ,.,.) = 
   2   4
   7   9

(1 ,.,.) = 
  12  14
  17  19

(2 ,.,.) = 
  22  24
  27  29
[torch.FloatTensor of size 3x2x2]

m3(b)
Variable containing:
(0 ,.,.) = 
   1   3   4
   6   8   9

(1 ,.,.) = 
  11  13  14
  16  18  19

(2 ,.,.) = 
  21  23  24
  26  28  29
[torch.FloatTensor of size 3x2x3]

```

**Comment by zou3519** [comment]
```
In [2]: b
Out[2]:

(0 ,.,.) =
   0   1   2   3   4
   5   6   7   8   9

(1 ,.,.) =
  10  11  12  13  14
  15  16  17  18  19

(2 ,.,.) =
  20  21  22  23  24
  25  26  27  28  29
[torch.FloatTensor of size (3,2,5)]
In [4]: m2(b)  # nn.AdaptiveMaxPool1d(output_size=2)
Out[4]:

(0 ,.,.) =
   2   4
   7   9

(1 ,.,.) =
  12  14
  17  19

(2 ,.,.) =
  22  24
  27  29
```
Why isn't this what you would expect? This is equivalent to doing `nn.MaxPool1d(3, ceil_mode=True)`

**Comment by sserr23** [comment]
If n is the parameter applied to AdaptiveMaxPool1d, wouldn't you expect AdaptiveMaxPool1d to select the n largest values in the last dimension, though?

**Comment by zou3519** [comment]
@sserr23 given the example above, could you let me know what you think the output should be please, so we're on the same page?

**Comment by sserr23** [comment]
I would think that in that example, the output ought to be 
```
(0 ,.,.) =
   3   4
   8   9

(1 ,.,.) =
  13  14
  18  19

(2 ,.,.) =
  23  24
  28  29
```

Thanks!

**Comment by zou3519** [comment]
`nn.AdaptiveMaxPool1d(output_size=2)` will do a MaxPool with some kernel_size and stride such that the output size (in this case, the last dimension) becomes 2. For the example:
```
(0 ,.,.) =
   0   1   2   3   4
   5   6   7   8   9

(1 ,.,.) =
  10  11  12  13  14
  15  16  17  18  19

(2 ,.,.) =
  20  21  22  23  24
  25  26  27  28  29
```
let's look at the slice `b[0][0] = [0   1   2   3   4]`. For a MaxPool applied to this to result in an output of size 2, we'd need a kernel of size 3 and stride 3. So the result becomes [max(0, 1, 2), max(3, 4, ??)] which is [2, 4].

I think if you want the behavior you're describing, `b.topk(2)` will do that.

**Comment by sserr23** [comment]
Ahhhh got it, thanks so much! I understand now.
