### ISSUE TITLE
If a transposed convolution layer takes in a 3 channel input and gives out a 2 channel output, how many kernels would it have and why?

### ISSUE THREAD

**Issue by Emmanuel357** [pytorch/pytorch#57539]
Isn't the tconv layer supposed to have 6 kernels divided into two? One three kernels for one channel, another three kernels for another channel making two channels because the tconv layer is to give out a two channel output? I'm I right or what?

**Comment by ngimel** [comment]
Please use forum discuss.pytorch.org for questions
