### ISSUE TITLE
[docs] attr rendering in F.kl_div

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#57538]
![image](https://user-images.githubusercontent.com/1041752/117000434-5ba39b80-ace1-11eb-87e6-913a9a88b1ac.png)

It would be nice to add GH action checking for absence of `:attr:`, as it often indicates a rendering typo

cc @brianjo @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @vadimkantorov

**Comment by vadimkantorov** [comment]
my pleasure :)
