### ISSUE TITLE
Cuda Dynamic Parallelism Support for building custom pytorch library

### ISSUE THREAD

**Issue by ajinkyaambatwar** [pytorch/pytorch#57543]
## 🚀 Feature
I am requesting to add a feature to torch cpp_extenstion to include cuda dynamic parallelism support while building. 

## Motivation

If I am having a global kernel call inside another a global kernel, I need to use ```-rdc=true``` flags for nvcc. That is possible while stand-alone execution of the code. 
I have a cuda script ```query_gpu.cu``` which invokes a ```__global__()``` kernel to perform certain oprations. Inside the kernel, another ```__global__()``` kernel needs to be called. If I build this using torch extension, I get the this error
```undefined symbol: __cudaRegisterLinkedBinary_<number>```

As per [this](https://stackoverflow.com/questions/22115197/dynamic-parallelism-undefined-reference-to-cudaregisterlinkedbinary-linking) stackoverflow answer and [this](https://discuss.pytorch.org/t/custom-cuda-extension-with-dynamic-parallelism/45000) pytorch disussion thread, we need an intermediate step to for device linking. This feature is currently not available in the default setup options for building cuda extensions.

## Pitch
For this, I request to introduce a clear setup for multiple ```nvcc``` command executions, just like one needed here, inside the setup options. Or simple a flag like ```dynamic_parallel=True``` which should be able to take care of everything.

cc @yf225 @glaringlee @ngimel

**Comment by nvcastet** [comment]
Cuda Dynamic Parallelism is one use case requiring relocatable device code linking.
Another use case is linking your `CUDAExtension` with a static library containing a device code API (e.g. NVSHMEM communication library), you will also need the extra device linking step.
As mentioned in this RFE, it would be great to be able to trigger this extra step from `CUDAExtension` with a flag.

**Comment by GostInShell** [comment]
Has this feature been incorporated yet to allow dynamic parallel programming in pytorch cuda extension? I am stilll getting `undefined symbol: __cudaRegisterLinkedBinary_` error. Can you provide a more detailed guidance on how to use it? Thanks a lot!
