### ISSUE TITLE
Update tech doc

### ISSUE THREAD

**Issue by atsigkas** [pytorch/pytorch#57545]
## 📚 Documentation
I already opened a pull request for updating the {pytorch/docs/source/**complex_numbers.rst**} file .
It is taking a lot of time before letting me do the final merge. 
Is it normal? 
The pull request is : #57540  

P.s. It's my first time trying to contribute to an open-source project of this size .

**Comment by mrshenli** [comment]
> It is taking a lot of time before letting me do the final merge.

Yep, each PR commit will launch 70+ CI containers to run tests, which usually will take 4+ hours (and will cost dollars :) ). 

I commented on #57540. When the comments are addressed, I will land that PR.
