### ISSUE TITLE
numel overflows silently on large sparse tensors 

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#57542]
As in title. Here's a reproducer (using the current master):
```
>>> torch.sparse_coo_tensor([[]]*4, [], (10000,)*4).numel()
10000000000000000
>>> torch.sparse_coo_tensor([[]]*4, [], (100000,)*4).numel()
7766279631452241920
```

The overflow is not silent in https://app.circleci.com/pipelines/github/pytorch/pytorch/315245/workflows/5572e810-d80a-44d0-8555-cabfc2caf637/jobs/13112422 that prevents testing the overflow error in https://github.com/pytorch/pytorch/pull/57492 .

Notice that COO sparse tensor construction always computes `numel` as `product(size)`: 
https://github.com/pytorch/pytorch/blob/dc49299078611543261949acfb1a7f1cc6e1392f/aten/src/ATen/SparseTensorImpl.h#L62

# Discussion

"[torch.numel returns the total number of elements in the input tensor](https://pytorch.org/docs/stable/generated/torch.numel.html?highlight=numel#torch.numel)". This definition makes certain sense for sparse tensors if the unspecified elements are interpreted as elements that have certain fill value, say, 0. However, in the masked semantics of sparse tensors, the total number of elements is the total number of specified elements (=nnz). So, there exists an interpretation-dependent ambiguity in the definition of `numel`.

For applications using sparse tensor, the current definition can be a hard restriction: one cannot define sparse tensors with `product(size) > max int64` because of undefined behavior in `numel`. See https://github.com/pytorch/pytorch/issues/57416 for examples.

Possible solutions:
1. Overflow in `numel` should trigger an exception.
2. To support sparse tensors with large dimensions, (i) re-define `numel` to be the number of specified elements (=nnz) ,or (ii) avoid computing `numel` (read: un-define `numel`) for sparse tensors. (BC warning).

I think 1 makes sense anyway. 2 would allow widening the application of sparse tensors to large masked tensor cases.

What do you think?

cc @aocsa @nikitaved @pearu @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mruberry** [comment]
Making numel() throw on overflow would be nice, but I'm concerned about the performance impact of detecting the overflow and throwing an error. @kurtamohler looked at the same or a similar issue previously, I think. We could hide the behavior behind a debug flag, but that seems like it would have niche appeal.

The semantics of numel on a sparse tensor is interesting. But you're right that any change would be BC-breaking. We should be very careful if we decide to do it. Keeping the semantics consistent with strided tensors (numel = the number of indexable elements?) seems OK.

**Comment by pearu** [comment]
> Making numel() throw on overflow would be nice, but I'm concerned about the performance impact of detecting the overflow and throwing an error. 

I think the impact to performance will be minimal because the result of `numel` computation is cached in `_numel` and it is updated only when the tensor size is changed.

Notice that detecting numel overflow is implemented in https://github.com/pytorch/pytorch/pull/57492

> The semantics of numel on a sparse tensor is interesting. But you're right that any change would be BC-breaking. We should be very careful if we decide to do it. Keeping the semantics consistent with strided tensors (numel = the number of indexable elements?) seems OK.

Yes, defining numel as the number of indexable elements makes sense. Suggestion: change

"torch.numel returns the total number of elements in the input tensor"

to

"torch.numel returns the total number of indexable elements in the input tensor"

that would clarify the definition of numel for sparse tensor users. Would the corresponding doc PR be acceptable, perhaps already in #57492?

**Comment by rohan-varma** [comment]
@mrshenli I noticed you added oncall: distributed, is this a distributed issue?

**Comment by kurtamohler** [comment]
FWIW #43755 is the PR I was working on to fix this, and @mruberry decided back then that we shouldn't do it

**Comment by pearu** [comment]
Here's a plan:
https://github.com/pytorch/pytorch/pull/57492#discussion_r626998860

**Comment by pearu** [comment]
Issue is resolved via https://github.com/pytorch/pytorch/issues/57416:
```python
>>> torch.sparse_coo_tensor([[]]*4, [], (100000,)*4).numel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: numel: integer multiplication overflow
```
