### ISSUE TITLE
Delete max_pool2d_with_indices_backward.grad_input?

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#57554]
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L8370

@zou3519 claims this (probably) isn't used anywhere.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by albanD** [comment]
Isn't that the `out=` variant of max_pool2d_with_indices_backward ? I guess the regular `max_pool2d_with_indices_backward` overload just calls into that same implementation anyways no?
