### ISSUE TITLE
torch.matmul() behavior doesn't match docs

### ISSUE THREAD

**Issue by li-roy** [pytorch/pytorch#5758]
On master, torch.matmul() doesn't accept an out arg, but the docs suggest that it should.

```
a = torch.LongTensor([3,4])
b = torch.LongTensor([4,5])
c = torch.LongTensor()
torch.matmul(a,b, out=c)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: matmul() got an unexpected keyword argument 'out'
```

**Comment by zou3519** [comment]
I don't know if it ever took a 'out' argument. If it never did, then my vote is to fix the docs and not add an 'out' keyword because those have strange resize semantics.

**Comment by fmassa** [comment]
It used to support an `out` argument, but this was recently removed I believe.

**Comment by gchanan** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/6961.
