### ISSUE TITLE
Problem in DataLoader (Solution in #4643 not solve it)

### ISSUE THREAD

**Issue by fanglue** [pytorch/pytorch#5761]
- OS: Ubuntu 16.04
- PyTorch version: torch-0.3.1-cp36-cp36-linux_x86_64.whl
- How you installed PyTorch (conda, pip, source): pip3 from the binary
- Python version: 3.6
- CUDA/cuDNN version: 9.1
- GPU models and configuration: GTX 1070 Ti

After install using the wheel file, I have changed the torch/utils/data/Dataloader.py according to the changes shown at https://github.com/pytorch/pytorch/pull/4643

But the same error still happen when I try the tutorial example to load image database:

Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x56090c8c7348>>
Traceback (most recent call last):
  File "/home/fanglue/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 375, in __del__
  File "/home/fanglue/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 361, in _shutdown_workers
  File "/home/fanglue/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 39, in _get_from_queue
  File "/usr/pkg/lib/python3.6/multiprocessing/queues.py", line 337, in get
ImportError: sys.meta_path is None, Python is likely shutting down

So could anyone help me on that? Or is there any other file I should modify to get it run?

**Comment by fanglue** [comment]
And, I am not sure how can I use the changes in torch/csrc/DataLoader.cpp, should I clone all the source code on GitHub and build the newest binary to fully fix this my problem?

**Comment by SsnL** [comment]
when does this error happen? is it happening when you exit python?

**Comment by shirishr** [comment]
@SsnL and @soumith,
I am running this:

python train.py --dataroot ./datasets/horse2zebra --name horse2zebra_cyclegan --model cycle_gan --no_dropout --loadSize 64 --nThreads 1

from 

https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix

The model is succefully created:
model [CycleGANModel] was created

I am on ubuntu 16.04, pytorch 3.1, cuda 9.0 and cuDnn 7.1

The error I get is traced below:
create web directory ./checkpoints/horse2zebra_cyclegan/web...
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    for i, data in enumerate(dataset):
  File "/home/sam/Documents/ComputerVision/pytorch-CycleGAN-and-pix2pix/data/custom_dataset_data_loader.py", line 44, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 275, in __next__
    idx, batch = self._get_batch()
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 254, in _get_batch
    return self.data_queue.get()
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self._reader.recv_bytes()
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/sam/anaconda3/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 175, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3792) is killed by signal: Illegal instruction.

**Comment by soumith** [comment]
@shirishr that error is because you are running it on a computer that is too old and does not have SSE4 instruction on CPU.

**Comment by SsnL** [comment]
@shirishr Also, it is more likely due to that your CPU doesn't support the operations done in the dataset.__getitem__.

**Comment by shirishr** [comment]
@SsnL & @soumith,

Some months ago I made it work in windows10 (I think)
The my windows machine crashed. So here I am. Sorry

Here is what I see in cat /proc/cpuinfo:

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 2
model name	: AMD FX(tm)-4300 Quad-Core Processor
stepping	: 0
microcode	: 0x600081c
cpu MHz		: 1400.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 16
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 **sse4_1 sse4_2** popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate retpoline retpoline_amd rsb_ctxsw vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips	: 7634.15
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

@SsnL how do I check if CPU support dataset.getitem?

**Comment by SsnL** [comment]
@shirishr run with `nThreads=0`

**Comment by shirishr** [comment]
tried it with nThreads=0
different error...
model [CycleGANModel] was created
create web directory ./checkpoints/horse2zebra_cyclegan/web...
Illegal instruction (core dumped)

**Comment by shirishr** [comment]
I see something I am uneasy about:
see bold below

CustomDatasetDataLoader
dataset [UnalignedDataset] was created
/home/sam/anaconda3/envs/my_torch/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
#training images = 1334
cycle_gan
**initialization method [normal]
initialization method [normal]
initialization method [normal]
initialization method [normal]**

**Comment by SsnL** [comment]
@shirishr No it's same error. We just wrap it in a nice way so you can see it even if it's in the workers. 

Isn't that expected? CycleGAN has four networks: D_X D_Y G F .

**Comment by SsnL** [comment]
@shirishr anyways, it confirms my hypothesis that your CPU doesn't support the operation in `dataset.__getitem__`.

**Comment by shirishr** [comment]
Oh... Can you suggest a workaround?

**Comment by SsnL** [comment]
@shirishr You can try to put debug statements in CycleGAN code and see which one isn't supported by your CPU (probably some PIL operations), and search for replacements. Sorry I don't have much else to offer.

**Comment by shirishr** [comment]
@SsnL 
Thank you sir !

**Comment by SsnL** [comment]
closed due to inactivity. feel free to reopen if you can reproduce with latest stable (0.4 at the moment of writing).

**Comment by shardullavekar** [comment]
Still can't get this to work.

https://stackoverflow.com/questions/53449927/runtimeerror-dataloader-worker-is-killed-by-signal-illegal-instruction

Please help.
