### ISSUE TITLE
Strange multiplication behavior

### ISSUE THREAD

**Issue by tejaskhot** [pytorch/pytorch#5763]
The following code gives two different outputs in two settings.

![Strange multiplication behavior](https://user-images.githubusercontent.com/6690052/37379625-bda87482-270a-11e8-9087-ee1ca6908cea.png)

Top window: independent IPython Console
Bottom window: at a breakpoint within a longer script I am using currently

The result in top window is correct (and same as numpy). I am using version `0.4.0a0+f8439c2` along with Python `3.6.4` though this does not seem to be an issue with the version.

**Comment by reynoldscem** [comment]
So I don't know if this info is meant to be more visible, but I think you are meant to include more information when reporting a bug:

https://github.com/pytorch/pytorch/blob/master/.github/ISSUE_TEMPLATE.md

I have also been getting strange behaviour with (scalar) multiplies, but this does not seem to be the same thing.

I could be wrong, but I think that those vectors are very nearly orthogonal, so you could just be getting rounding errors from the small dot product. One thing you could do is write some tests to see what context this happens in and try to rule out that possibility.
