### ISSUE TITLE
gradgradcheck fails if the function does not depend on the input

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#57649]
## 🐛 Bug

If one (or more) of the inputs to `gradgradcheck` has no dependency to the output, it raises an error.
This does not happen with `gradcheck` function.
This might sound silly (e.g. "why would you put unrelated input to gradgradcheck?"), but please take a look at the example below.

## To Reproduce

    import torch

    def fcn0(x, a, b):
        return (x * a) ** 2 + b

    def functional(fcninp, x, a, b):
        f = fcninp(x, a, b)
        return torch.autograd.grad(f, x, create_graph=True)[0]

    x = torch.tensor(1.0, dtype=torch.float64).requires_grad_()
    a = torch.tensor(1.0, dtype=torch.float64).requires_grad_()
    b = torch.tensor(1.0, dtype=torch.float64).requires_grad_()

    # success
    torch.autograd.gradgradcheck(functional, (fcn0, x, a, b.detach()))
    # fail
    torch.autograd.gradgradcheck(functional, (fcn0, x, a, b))

So, `functional` is a functional that takes a function and other parameters as its inputs, and returns the derivative of the function w.r.t. one of the inputs.
If the derivative of the function just happen to have no dependence to one of the parameters, then `gradgradcheck` raises an error.

## Expected behavior

`gradgradcheck` should not raise an error in the above case.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0.dev20210419
 - OS (e.g., Linux): WSL Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.5
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

`gradcheck` is fine if one of the inputs are unrelated to the output, e.g.

    import torch

    def fcn0(x, a):
        return x ** 2

    x = torch.tensor(1.0, dtype=torch.float64).requires_grad_()
    a = torch.tensor(1.0, dtype=torch.float64).requires_grad_()

    torch.autograd.gradcheck(fcn0, (x, a))  # returns True

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by mfkasim1** [comment]
No, this is the case where there is an unrelated input that requires gradient.

**Comment by mfkasim1** [comment]
Still fails.

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/mfkasim/anaconda3/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1212, in gradgradcheck
        return gradcheck(
      File "/home/mfkasim/anaconda3/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1088, in gradcheck
        return _gradcheck_helper(**args)
      File "/home/mfkasim/anaconda3/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1096, in _gradcheck_helper
        func_out = func(*tupled_inputs)
      File "/home/mfkasim/anaconda3/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 1209, in new_func
        grad_inputs = torch.autograd.grad(outputs, input_args, grad_outputs, create_graph=True)
      File "/home/mfkasim/anaconda3/envs/torchdev/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
        return Variable._execution_engine.run_backward(
    RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

The problem is this line:
https://github.com/pytorch/pytorch/blob/807bea1c4e6fdf896570f1fac83897cf42231f49/torch/autograd/gradcheck.py#L1209

Probably the fix is as simple as put `allow_unused=True`

**Comment by soulitzer** [comment]
Do we always want to allow unused though? Keeping this error might be a good sanity check for most cases. Maybe we could enable this with a flag

**Comment by soulitzer** [comment]
Oh I was thinking of something like:
```
def f(a, b, ..., z):
   computed_a = f1(a)
   computed_b = f2(b)
    ....
   computed_z = fn(z)
   return computed_a + .... + computed_y # user forgets to add computed_b
```
where the user just forgets to add something when they actually meant for that computation to be part of the graph
but I suppose they would eventually find out anyway when running `.grad`
