### ISSUE TITLE
With & without -O2 compilation optimization level, AVX512 Complex multiplication & division results aren't equal

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#57681]
## ❓ AVX512 Complex multiplication & division results aren't equal with & without -O2 compiler optimization level

While trying to unify `vec256` & a new [`vec512`](https://github.com/imaginary-person/pytorch-1/tree/only_vec/aten/src/ATen/cpu/vec/vec512) implementation (parallel to `vec256`) for vectorization of ATen kernels under `vec` in #56992,  4 [vectorization tests ](https://github.com/imaginary-person/pytorch-1/blob/only_vec/aten/src/ATen/test/vec_test_all_types.cpp) related to Complex multiplication & division are failing with the regular build, but are passing with the debug build (these builds require GCC 9 on CI). The [failures](https://gist.github.com/imaginary-person/4b37e8053c7fe67beea6faadf6cd4dd9) were unexpected because Complex (double/float) Multiplication & division have similar code for both [AVX2](https://github.com/pytorch/pytorch/blob/049152faa92d513b2121120e21e6b23cd07c2beb/aten/src/ATen/cpu/vec256/vec256_complex_double.h#L346-L372) & [AVX512](https://github.com/imaginary-person/pytorch-1/blob/e3125467dd682111d5e62a161deb97522a1909af/aten/src/ATen/cpu/vec/vec512/vec512_complex_double.h#L436-L464).

The [failing tests](https://gist.github.com/imaginary-person/4b37e8053c7fe67beea6faadf6cd4dd9) are:
```
[  FAILED  ] Arithmetics/2.Multiplication, where TypeParam = at::vec::(anonymous namespace)::Vectorize<c10::complex<float> >
[  FAILED  ] Arithmetics/2.Division, where TypeParam = at::vec::(anonymous namespace)::Vectorize<c10::complex<float> >
[  FAILED  ] Arithmetics/3.Multiplication, where TypeParam = at::vec::(anonymous namespace)::Vectorize<c10::complex<double> >
[  FAILED  ] Arithmetics/3.Division, where TypeParam = at::vec::(anonymous namespace)::Vectorize<c10::complex<double> >
```
 These [failures ](https://gist.github.com/imaginary-person/4b37e8053c7fe67beea6faadf6cd4dd9) are related to precision. For example,
```

[ RUN      ] Arithmetics/2.Multiplication
/external/pytorch_nightly/aten/src/ATen/test/vec_test_all_types.h:884: Failure
Expected equality of these values:
  nearlyEqual<UVT>(expArr[i], actArr[i], absErr)
    Which is: false
  true
-0.9598236083984375!=-0.959716796875
Failure Details:
mult "/external/pytorch_nightly/aten/src/ATen/test/vec_test_all_types.cpp":579
Test Seed to reproduce: 1620243645159770797
Arguments:
#        vec[(63,30.4131565), (48,63), (51,33.7197609), (40,47.1203003), (39.3313866,31), (76.8423386,51.8105431), (59.6820679,39.811985), (61,68.3005524)]
#        vec[(46,36.2208595), (61,66.424324), (41.4912567,62.782589), (63,-9.99999905), (40.7293129,34.3800278), (38.8900185,44.4420738), (29,69), (54,44.2286301)]
Expected:
#       vec[(1796.4093,3680.91943), (-1256.73242,7031.36768), (-0.959823608,4600.9873), (2991.20288,2568.57886), (536.159485,2614.82275), (685.832092,5429.9458), (-1016.24689,5272.61035), (273.160156,6386.17627)]
Actual:
#       vec[(1796.4093,3680.91943), (-1256.73242,7031.36768), (-0.959716797,4600.9873), (2991.20288,2568.57886), (536.159424,2614.82275), (685.832031,5429.9458), (-1016.24683,5272.61035), (273.160156,6386.17627)]
First mismatch Index: 2
[  FAILED  ] Arithmetics/2.Multiplication, where TypeParam = at::vec::(anonymous namespace)::Vectorize<c10::complex<float> > (22 ms)
```
<hr>

@jamesr66a @cpuhrsch @colesbury @VitalyFedyunin @malfet @ezyang @dylanbespalko @quickwritereader @xuhdev 

Do you have any insights into why such failures could be occurring, and how they can be fixed? Thank you!

**Comment by ezyang** [comment]
Could be some sort of fused-multiply-add problem

**Comment by kshitij12345** [comment]
I saw a similar problem recently, where gcc gave different results with optimization on and off. 
Are you using gcc? Could you also test with clang (clang was consistent with optimizations on and off)?

Reference to the finding: https://github.com/pytorch/pytorch/pull/56352#issuecomment-830573248 (has link to godbolt repro)

Also would be great if you can have a stand-alone repro (possibly in godbolt).

**Comment by imaginary-person** [comment]
Thanks for your response, @ezyang. But I'm using the `-mfma` flag as well. I built the regular build (on which these tests fail) with the `-g` flag. I just verified that both the multiplication & [the division assembly](https://gist.github.com/imaginary-person/f4e643388ed3f7cfdab5832dc2fa4da0) don't have any FMA instructions.

**Comment by imaginary-person** [comment]
Hey @kshitij12345, yes, I'm using GCC! Thank you for your advice!
If I relax tolerance, then AVX512 would produce different results than AVX2.

Do you know what's the root-cause, BTW?

**Comment by imaginary-person** [comment]
@ezyang, if I relax tolerance to pass tests for now, then if the PR would be merged, AVX512 might produce different results than AVX2! Would it be okay to allow such behavior, perhaps by having a disclaimer that results might differ across vectorization levels?

Meanwhile, I'll do some digging to check exactly when the results start to diverge, so as to pin-point the root-cause.
Thanks!

**Comment by ezyang** [comment]
> if I relax tolerance to pass tests for now, then if the PR would be merged, AVX512 might produce different results than AVX2! Would it be okay to allow such behavior, perhaps by having a disclaimer that results might differ across vectorization levels?

We don't guarantee that unvectorized and vectorized code runs the same way. So yes, this seems OK. (Although in an ideal world we'd know exactly *why* it has to be different in the two cases, and have agreed that it is different for a good reason)

**Comment by quickwritereader** [comment]
@imaginary-person complex vector multiplication and division are tested against local_multiply and local_divide which are implementation-based and mimic fp_contract of implemented vector codes.
could you check if you are testing against AVX ones

**Comment by imaginary-person** [comment]
Thank you for taking a look, @quickwritereader!
I removed AVX support from ATen in that draft PR.
`CPU_CAPABILITY_DEFAULT` in those lines is the unvectorized implementation.

AVX512 tests fail with the regular gcc build, but pass with a debug build.
BTW, For Complex multiplication & division in AVX512, I'm using AVX2 code for `hsub` & `hadd`,
as `_mm512_hsub_pd`, `_mm512_hadd_pd`, and their float counterparts don't exist.
I don't expect this to have affected the results, though, but I'll dig deeper just to be sure.

Please advise if one can expect AVX2 & AVX512 to produce the same results on Intel Skylake machines. Thanks!

**Comment by quickwritereader** [comment]
I believe it should be equal.

**Comment by quickwritereader** [comment]
could you check if it tests against hadd and hsub  in your code for local_multiply. [vec_test_all_types.h#L1167-L1193](https://github.com/imaginary-)person/pytorch-1/blob/only_vec/aten/src/ATen/test/vec_test_all_types.h#L1167-L1193

**Comment by imaginary-person** [comment]
> I believe it should be equal.

Thanks! I thought so too.
I'll prioritize finding the root-cause of the divergence.

> could you check if it tests against hadd and hsub in your code for local_multiply. [vec_test_all_types.h#L1167-L1193](https://github.com/imaginary-person/pytorch-1/blob/only_vec/aten/src/ATen/test/vec_test_all_types.h#L1167-L1193)

Yes, it does. The AVX512 code is based on the AVX2 code, which also uses `hsub` & `hadd`.
Surprisingly, the failures don't occur with gcc debug builds.
I think one naive approach would be to automate testing of custom builds, built by using a (maybe curated) subset of gcc flags that are different between `O0` & `O2`, so as to figure out which optimization resulted in the divergence. 😄

**Comment by imaginary-person** [comment]
> could you check if it tests against hadd and hsub in your code for local_multiply. [vec_test_all_types.h#L1167-L1193](https://github.com/imaginary-person/pytorch-1/blob/only_vec/aten/src/ATen/test/vec_test_all_types.h#L1167-L1193)

Sorry, @quickwritereader , I just checked & `local_multiply` for `TEST_AGAINST_DEFAULT` doesn't have `hsub` & `hadd`.
I'll check why tests for AVX2 have been passing, and why AVX512 tests pass for the debug build.
Thanks again! This was very helpful!

**Comment by quickwritereader** [comment]
I was not able to reproduce the expected value there. it gave the correct result even with -O3. 
could you add all flags and test it as well, and also you can compile on your pc.
[https://godbolt.org/z/PMofh15hM](https://godbolt.org/z/PMofh15hM)

**Comment by quickwritereader** [comment]
> > could you check if it tests against hadd and hsub in your code for local_multiply. [vec_test_all_types.h#L1167-L1193](https://github.com/imaginary-person/pytorch-1/blob/only_vec/aten/src/ATen/test/vec_test_all_types.h#L1167-L1193)
> 
> Sorry, @quickwritereader , I just checked & `local_multiply` for `TEST_AGAINST_DEFAULT` doesn't have the equivalent of `hsub` & `hadd`.
> I'll check why tests for AVX2 have been passing, and why AVX512 tests pass for the debug build.
> Thanks again! This was very helpful!

for AVX cases local_multiply should not choose TEST_AGAINST_DEFAULT. default there is std complex multiplication

**Comment by imaginary-person** [comment]
> for AVX cases local_multiply should not choose TEST_AGAINST_DEFAULT. default (TEST_AGAINST_DEFAULT) is std complex multiplication

Thanks. Yes, I commented last time when I had noticed that.
That would make sense, but I'm confused because, at first glance, it seems that the AVX2 implementation is also being compared against `TEST_AGAINST_DEFAULT` [in the master branch](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/test/vec256_test_all_types.h).

**Comment by quickwritereader** [comment]
I see. just add   && !defined(CPU_CAPABILITY_AVX512) there like this:
```
#if defined(CPU_CAPABILITY_DEFAULT) || defined(_MSC_VER)
#define TEST_AGAINST_DEFAULT 1
#elif !defined(CPU_CAPABILITY_AVX) &&  !defined(CPU_CAPABILITY_AVX2)  && !defined(CPU_CAPABILITY_AVX512) && !defined(CPU_CAPABILITY_VSX) 
#define TEST_AGAINST_DEFAULT 1
#else
#undef TEST_AGAINST_DEFAULT
#endif
```
or re-write that logic more clear way:

**Comment by imaginary-person** [comment]
@quickwritereader, this is so embarrassing!!! I had wrongly assumed that `CPU_CAPABILITY_DEFAULT` is always defined, unless a user uses the environment variable `ATEN_CPU_CAPABILITY` to set it to a particular value!

So, the issue was just that the testing for AVX512 was being done against the default implementation? 🤣 
Thanks to you, all tests pass now! 😄

**Comment by quickwritereader** [comment]
@imaginary-person . glad it solved your problem.  
c++ is a noisy language so no matter how one tries it's hard to write readable code.

**Comment by imaginary-person** [comment]
> c++ is a noisy language so no matter how one tries it's hard to write readable code.

Or rather CMake is hard to read for me.  😞
`CPU_CAPABILITY_DEFAULT`, etc are defined by CMake.
Thanks again for your help!
