### ISSUE TITLE
Freezing doesn't remove tuple operations

### ISSUE THREAD

**Issue by dreiss** [pytorch/pytorch#57698]
## 🐛 Bug

After freezing a traced model, I expect all unnecessary tuple operations to be removed, but some remain.

## To Reproduce

https://colab.research.google.com/gist/dreiss/0414c8e294e482e8a07f98990e7130fc/freezetuple.ipynb

## Expected behavior

No TupleConstruct and TupleUnpack nodes.

## Environment

See notebook.  It reproduces on nightly as well.

## Additional context

Freezing is an awesome feature of TorchScript!

cc @gmagogsfm

**Comment by eellison** [comment]
We just need to add a call to `LowerSimpleTuples` after the call here: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/freeze_module.cpp#L89.

**Comment by FloydHsiu** [comment]
Hi, I follow the suggestion from @eellison to change the code.
And build pytorch with my own computer.

Here is the result that run by pytorch I build.
https://colab.research.google.com/drive/11XFsz0eakL313HKBrRBvpGXH74Sh5Dl_

**Comment by nikithamalgifb** [comment]
@FloydHsiu : I have assigned you the issue. If you are not able to work on this any further please feel free to unassign the issue and add it back to the queue. Thanks again for your valuable contribution

**Comment by nivesh48** [comment]
Hey @nikithamalgifb, I'm interested to work on this.

**Comment by FloydHsiu** [comment]
Hi @nivesh48,
Sorry, I'm working on this issue now.

**Comment by nikithamalgifb** [comment]
@nivesh48 : Thank you for your interest but unfortunately, this is issue is already being worked on actively by @FloydHsiu . We have plenty of other similar issues where we would be very happy to get some help. Here is the link : https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee Feel free to look at them and let us know if you are interested in any or go ahead and comment on the available issue to claim the task.
