### ISSUE TITLE
Rollup: improve bfloat16 cuda support

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#57707]
Currently the following ops don't support bfloat16, according to OpInfo metadata (linalg and fft ops are filtered out):

acos
<s>angle</s>
asin
atan
atan2
<s>cdist</s> (cdist will have too much of a numerical error with bfloat16)
**ceil**
<s>complex</s> (bfloat16 not supported as base type for complex)
cosh
cummax
cummin
cumprod
**cumsum**
diag
<s>digamma</s> (no special functions support for bfloat16)
**dot** (needed for full matmul support)
erfc
<s>erfinv</s> precision too low
exp2
expm1
**floor**
frac
<s>frexp</s>
hypot
lerp
<s>lgamma</s>
logaddexp
logaddexp2
logcumsumexp
<s>mvlgamma</s> 
**nan_to_num**
nanquantile
<s>polar</s> no complex support
<s>polygamma</s> no special function support
quantile
roll
**round**
rsqrt
sin
sinc
sinh
**sort**
tan
<s>trace</s> linalg in general not supported, but trace is easy
trunc
<s>vdot</s> no complex support 
<s>view_as_complex</s> no complex support

That's 47 ops out of 172 non-fft non-linalg ops. We should add bfloat16 support to at least some of them. Most important operations are bold, least important (or don't make sense for bfloat16, e.g. `complex`, because bfloat16 is not supported for complex) are crossed out. 
Script to do most of the filtering:
```
import torch
from torch.testing._internal.common_methods_invocations import op_db
from torch.testing._internal.common_device_type import skipCUDAIfNoMagma
names = set()
names_no_bf16 = set()
for o in op_db:
    if ('linalg' not in o.name and 'fft' not in o.name):
        if (o.decorators is None or skipCUDAIfNoMagma not in o.decorators):
            names.add(o.name)
            if not torch.bfloat16 in o.dtypesIfCUDA and torch.float in o.dtypesIfCUDA:
                names_no_bf16.add(o.name)
for n in sorted(names_no_bf16):
    print(n)
print(len(names), len(names_no_bf16))
```
see #54794 for round, rsqrt and exp2

**Comment by imaginary-person** [comment]
`exp2` might not have good-enough precision on CUDA & CPU, or maybe tolerance needs to be adjusted for it. Things might've changed since I [last tested](https://app.circleci.com/pipelines/github/pytorch/pytorch/291458/workflows/8d7ed6c0-4095-44b8-a340-e7009724ae01/jobs/11880797/tests#failed-test-3), so I'll retest. Thanks!

**Comment by ngimel** [comment]
Tolerances generally need to be adjusted for bfloat16 tests, 7 bits of mantissa is just too little.

**Comment by ngimel** [comment]
Unfortunately `sort` is non-trivial to add, as `cub` doesn't support bfloat16 sort.

**Comment by ngimel** [comment]
Yeah, `quantile` and `nanquantile` depend on sort. cc @ptrblck for bfloat16 support on P100, my impression is that it should be supported.

**Comment by imaginary-person** [comment]
Thanks, I should probably create another issue for it, so that mruberry & anjali411 can also track it.

**Comment by imaginary-person** [comment]
Hello @ngimel, please confirm if an `atol` of 0.016 & `rtol` of 1e-5 would be fine for testing `BFloat16`:

I got these values from
https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1144-L1149.

Thanks!

**Comment by ngimel** [comment]
Yes, those values are fine!

**Comment by imaginary-person** [comment]
Hello @ngimel,

These PRs are ready for review -

Created #57907 for `lerp`,
#57905 for `hypot` & `atan2`,
#57916 for `roll` & `diag`
#57910 for `ceil`, `floor`, `frac`, `round` & `trunc`,
#57904 for  `cumsum`, `logcumsumexp`, `cumprod`, `cummin` & `cummax` ,
#57913 for `acos`, `asin`, `atan`, `cosh`, `sin`, `sinh`, `tan`, `sinc`, `exp2`, `erfc`, `expm1` & `rsqrt` (tests are still running because I removed `nan_to_num` today. `nan_to_num` for BFloat16 produces incorrect output for `inf` & `-inf`, so I'm not enabling it right now, but perhaps, it needs to be fixed).
Also created #57903 for `dot`, which also enabled `matmul` & `vdot` for BFloat16, perhaps because the sample inputs used use `dot` instead. Tests are currently running because the CI checks that ran last time couldn't auto-merge changes. I expect them to pass this time around.


This PR's windows build is failing -
#57908 for `logaddexp` & `logaddexp2`, but the Windows build is failing for it with error:
```
C:/Users/circleci/project/aten/src/ATen/native/cuda/LogAddExpKernel.cu(13): error: calling a
 __host__ function("isinf< ::c10::BFloat16> ") from 
a __host__ __device__ function("at::native::logaddexp_kernel_cuda(::at::TensorIteratorBase &)::[lambda() (instance 1)]::operator 
()() const::[lambda() (instance 6)]::operator ()() const::[lambda( ::c10::BFloat16,  ::c10::BFloat16) 
(instance 1)]::operator () const") is not allowed
```

Thank you!

**Comment by PeterL1n** [comment]
@imaginary-person 

Can anyone help enable `F.interpolate` and `F.grid_sample` for BFloat16 on Cuda? Bilinear upsampling is widely used in convolutional decoders. Not having them is a big blocker to actually use BFloat16 to train models.

**Comment by ngimel** [comment]
@PeterL1n, bfloat16 is not supported for convolutions, and that, arguably, is the biggest blocker for using BFloat16 in convolutional models. 
Would enabling `interpolate` and `grid_sample` still be interesting w/o convolution support?
cc @ptrblck on plans for bfloat16 support for convolutions.

**Comment by PeterL1n** [comment]
@ngimel 

Conv, ConvTranspose, AvgPool, and MaxPool already work on BFloat16! Backward works as well. So `interpolate` is the only blocker for me.

One thing to note is that BFloat16 uses Thnn convolution instead of CuDNN. Can CuDNN be enabled for convolutions?

**Comment by ngimel** [comment]
Conv and ConvTranspose don't work with bfloat16 with cudnn, native implementation is very slow.

**Comment by arogozhnikov** [comment]
I can confirm that in pytorch 1.10 conv models in bfloat16 are slower than in fp32

**Comment by jamaliki** [comment]
@ptrblck, @ngimel any updates on this? Not having interpolate in bfloat16 is a blocker for a project right now. Also, is it still the case that convs are slow in bfloat16?

**Comment by ptrblck** [comment]
Conv support in `bfloat16` should be enabled in the cuDNN v8 API via `export TORCH_CUDNN_V8_API_ENABLED=1`.
I don't know what the status of `bfloat16` for `interpolate/upsample`, but couldn't find a commit enabling it.

**Comment by jamaliki** [comment]
Am I correct that the only thing that needs to change is to change the files in aten/src/ATen/native/cuda/UpSample* in the same manner as https://github.com/pytorch/pytorch/pull/57904? Because I could do that.

**Comment by ngimel** [comment]
For interpolation operations backward, intrinsic bfloat16 atomic will have to be enabled (currently gpuAtomicAdd for bfloat16 calls into a very slow CAS-based implementation.
