### ISSUE TITLE
Does anyone know the source code of the conv2d calculation process in pytorch?

### ISSUE THREAD

**Issue by YZW-explorer** [pytorch/pytorch#57704]
Does anyone know the source code of the conv2d calculation process in pytorch?

**Comment by skyline75489** [comment]
You can use [PyTorch forum](https://discuss.pytorch.org/) for this type of questions. Github is for issues of PyTorch *itself*.

The underlying arithmetic code is actually from multiple backends (QNNPACK, XNNPACK, CUDA, Metal, etc). Simple [search for conv2d](https://github.com/pytorch/pytorch/search?p=1&q=conv2d) to have some basic idea about the implementation.
