### ISSUE TITLE
Error message:  Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation'

### ISSUE THREAD

**Issue by wwj1980** [pytorch/pytorch#57718]
When I run the program, an error message appears:
Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation'
How to solve it？
thanks

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

You should also attach more information about what you're doing and which version of pytorch you're using.
Thanks!
