### ISSUE TITLE
wav2vec 2.0 large model, torch.jit.trace problem

### ISSUE THREAD

**Issue by yuseungwoo** [pytorch/pytorch#57710]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

Now, I'm changing wav2vec 2.0 large model using torch.jit.trace

but 

wav2vec2_asr.py, 170 line,  torch.jit.trace(self.w2v_encoder, **kwargs) show below error
" TypeError: 'source' is an invalid keyword argument for this function"

But we can see print(kwargs['source']) normaly.

How i understand this phenomenon?

Thank you

<img width="1920" alt="스크린샷 2021-05-06 오후 2 57 21" src="https://user-images.githubusercontent.com/42972413/117248757-76aa1300-ae7b-11eb-98cc-a321f61599bb.png">

- [Discussion Forum](https://discuss.pytorch.org/)

cc @gmagogsfm

**Comment by yuseungwoo** [comment]
Can't redefine method: forward on class: __torch__.fairseq.models.wav2vec.wav2vec2.TransformerSentenceEncoderLayer
![Uploading 스크린샷 2021-05-09 오후 6.59.02.png…]()

**Comment by nikithamalgifb** [comment]
The error seems to indicate that the `forward` method is being redefined. Is it being redefined anywhere in `wav2vec2.py` or any other files being used here?

**Comment by nikithamalgifb** [comment]
@yuseungwoo , we have closed the issue for now since the original issue does not reflect the error that you are seeing. . Feel free to open a new issue when you have a reproducer available with the new `RuntimeError` msg.
