### ISSUE TITLE
torch.prod does not support automatic differentiation for outputs with complex dtype

### ISSUE THREAD

**Issue by chenhao1umbc** [pytorch/pytorch#57736]
## To Reproduce
a = torch.rand(5,5, dtype=torch.cfloat).requires_grad_()
b = a.prod()
b.backward()

RuntimeError: prod does not support automatic differentiation for outputs with complex dtype.

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano

**Comment by Lezcano** [comment]
This was added in https://github.com/pytorch/pytorch/pull/48125
