### ISSUE TITLE
Retiring ONNX Optimizer

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#57747]
We are trying to update the ONNX submodule to the latest ONNX release. As part of this release, ONNXOptimizer is being retired from ONNX core.
ONNXOptimizer is only used to import models in caffe2. Disabling the optimizer would results in Caffe2 failure to run the a number of models in unit tests. These failures happen because Caffe2 fails to support not-optimized models.

Possible solutions per discussions with @malfet :

- Add ONNXOptimizer as dependency (downside is that it depends on a fixed version of ONNX library and it is not regularly updated)
- Drop support of ONNX optimizer in C2 import path (downside is that some models can no longer be imported)
- Embed ONNX optimizer logic into ONNX importer in caffe2

cc @jspisak 
cc @houseroad @spandantiwari @BowenBao @neginraoof @SplitInfinity

**Comment by malfet** [comment]
Updated title and added triage review tag to discuss further.
Caffe2 support has been deprecated for a while, but there were no announcements about ONNX deprecations.

**Comment by neginraoof** [comment]
test_rnn_init_predict_split
test_word_language_model_RNN_TANH
test_avg_pool1D_ceil
test_avg_pool3D_ceil
test_lstm_constant_folding
test_pixel_shuffle
test_loop

+ 192 rnn tests: https://github.com/pytorch/pytorch/blob/ebd2c0a4ed73033a62b44198f369b7a682150d56/test/onnx/test_pytorch_onnx_caffe2.py#L2436

**Comment by malfet** [comment]
@neginraoof do they fail because they validate that optimizations are applied or because generated network are functionally incorrect?

**Comment by neginraoof** [comment]
The problem is not with the generated models, as the same tests pass with other backends and pass ONNX checker as well. 
But looks like Caffe2 is not inline with latest ONNX updates and could also fail to support more complex models.

**Comment by malfet** [comment]
ONNX Optimizer was removed per https://github.com/onnx/onnx/pull/2834

**Comment by malfet** [comment]
Discussed this issue during triage review: let's disable optimizer support as it is no longer supported.

**Comment by malfet** [comment]
@neginraoof should we close this issue?
