### ISSUE TITLE
[feature request] Be able to ask pytorchbot to rebase prs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#5775]
I think it would be nice if we could ask pytorchbot (very politely) to attempt to rebase a PR. If the rebase fails for some reason, ping someone (the PR's author? the user?), else pytorchbot updates your PR. (Can it do this?)

I see two potential use cases:
- Rebasing stale PRs of community contributors so they don't need to rebase their PRs to get them reviewed. I think this is useful, especially because pytorch moves very fast.
- Frequent devs might find this to be a nice convenience function.

**Comment by vishwakftw** [comment]
Another thing that could be suggested (I think this is not there) is that if the lint fails, then the other tests should abort.

**Comment by goldsborough** [comment]
Another reason why this is currently a good idea is that onnx-fb-universe tests merge with the HEAD of pytorch *at the time the PR is made*, i.e. *not the current, up-to-date HEAD*. Therefore when master happens to be in a bad state when a PR is made, a rebase must occur to make onnxbot happy. CC @bddppq who is fixing this

**Comment by ezyang** [comment]
Note that every time you do a CI test, it merges with master if it's clean. So it's mostly a function of how onnxbot works.

**Comment by soumith** [comment]
fixed now
