### ISSUE TITLE
Issues installing pytorch with conda

### ISSUE THREAD

**Issue by dpefkou** [pytorch/pytorch#57763]
I am trying to install pytorch with conda on a linux machine and running into the following problem. Adding additional channels to the search didn't help. Any advice? Thanks!

>> conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch --channel conda-forge --channel bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio
  - pytorch

Current channels:

  - https://conda.anaconda.org/pytorch/linux-ppc64le
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-ppc64le
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

cc @ezyang @seemethere @malfet @walterddr

**Comment by albanD** [comment]
Hi,

Have you tried using the command from `https://pytorch.org/get-started/locally/` (with no additional channel as they might conflict)?
Also you might want to try from a clean env to see if it is not due to a conflict with your current env?

**Comment by rgommers** [comment]
```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch --channel conda-forge --channel bioconda
```
solves almost instantly in a fresh env and the following condarc settings:
```
$ cat ~/.condarc
channel_priority: strict
unsatisfiable_hints: true
channels:
  - conda-forge
  - defaults
```
If you get a conflict, try setting `channel_priority: strict`.

Packaging all looks good here, and there was no follow-up on the question, so I'll close this.
