### ISSUE TITLE
torch.tensor / Tensor.new_tensor should be able to take data + sparse dtype

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#5777]
Where the data is the dense representation and it is converted to a sparse tensor.  This is useful for testing at a minimum.

In more detail: PyTorch has both "dense" (strided) and "sparse" (coordinate format) tensors (multi-dimensional arrays).

Dense tensors can be constructed from python data, other tensors, etc. using the `torch.tensor` method:
```
>>> tensor([[1., 2., 3., 4.], [5., 6., 7., 8.]], dtype=torch.float64)
>>> x
tensor([[1., 2., 3., 4.],
            [5., 6., 7., 8.]], dtype=torch.float64)
```

Sparse tensors can be constructed similarly:
```
>>> sx = torch.sparse_coo_tensor([[0,1,1],[2,0,2]], [3.,4.,5.], size=[2,4], dtype=torch.float64)
>>> sx
torch.sparse.DoubleTensor of size (2,4) with indices:
tensor([[0, 1, 1],
            [2, 0, 2]])
and values:
tensor([3., 4., 5.], dtype=torch.float64)
```

but you can't copy from dense to sparse:
```
>>> sx.copy_(x)
RuntimeError
```

and similarly you can't construct a sparse tensor from a dense representation (this would be useful for testing, since no one remembers the coo format).

CC @colesbury.

**Comment by apaszke** [comment]
omg this would be so useful. Debugging issues with sparse tensors is a nightmare

**Comment by gchanan** [comment]
Presumably this would involve fixing dense -> sparse copy (https://github.com/pytorch/pytorch/issues/8331 and https://github.com/pytorch/pytorch/issues/8330?) and then making sure these are hooked up to the proper tensor constructors (that currently live in `tensor_new.cpp`)

**Comment by goldsborough** [comment]
It would be nice if the person implementing this could then also add the `to(Layout)` overload to `at::Tensor`. There is already test code in `test/cpp/api/tensor.cpp` to test this, just needs to be uncommented once it works :)

**Comment by gchanan** [comment]
I should also note that we've gotten rid of `layout` in `torch.tensor`, `torch.new_tensor`, the only constructor for sparse dtypes currently is `sparse_coo_tensor`; we probably want another overload that takes a single dense representation.

**Comment by gchanan** [comment]
> It would be nice if the person implementing this could then also add the to(Layout) overload to at::Tensor. There is already test code in test/cpp/api/tensor.cpp to test this, just needs to be uncommented once it works :)

Yes, but we probably don't want to expose that until both dense -> sparse and sparse -> dense are working; I don't know if the later is working right now, but that may be a separate issue.
