### ISSUE TITLE
Really need the pytorch version 1.3.1 because a certain package I use is built on pytorch 1.3.1 . 

### ISSUE THREAD

**Issue by weirdscorpio** [pytorch/pytorch#57836]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by malfet** [comment]
All historical PyTorch builds are still available from https://download.pytorch.org/whl/torch_stable.html and https://pytorch.org/get-started/previous-versions/

If you can not download those, please do not hesitate to reopen the issue.
