### ISSUE TITLE
why circular padding can only wrap once???

### ISSUE THREAD

**Issue by amssljc** [pytorch/pytorch#57891]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
- 
is that reasonable? When i want to use convolution layers with circular padding with large padding size, i must call `pad` function several times, such as:
```
x = torch.rand(batchsize, channels, 10,10)
x = pad(x, padding=(10, 10, 10, 10), padding_mode='circular')
x = pad(x, padding=(5, 5, 5, 5), padding_mode='circular')
conv = Conv2d(10, 10, kernal_size=(3,3), padding=0, dilation=15)
x = conv(x)
```
But it can cause lots of problems in my downstream processing. What i want is just using like this:
```
x = torch.rand(batchsize, channels, 10,10)
conv = Conv2d(10, 10, kernel_size=(3,3), padding=15, dilation=15, padding_mode = 'circular')
x = conv(x)
```
which wiil cause:
```
AssertionError: Padding value causes wrapping around more than once.
```

I will appreciate a lot if you can reply me!

**Comment by ngimel** [comment]
Please ask questions on the the forum, discuss.pytorch.org
