### ISSUE TITLE
torch.poisson does not work with FloatTensor on master

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#5791]
- OS: Mac
- PyTorch version: master (commit `e40425f`)
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- GPU models and configuration: CPU
- GCC version (if compiling from source): clang

When upgrading to PyTorch master (https://github.com/uber/pyro/pull/890), we realized that `torch.poisson` no longer accepts a `FloatTensor`, but works with a `DoubleTensor`.

```
>>> import torch
>>> torch.poisson(torch.tensor([1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: expected scalar type Double but found Float

>>> torch.poisson(torch.DoubleTensor([1]))
 2
[torch.DoubleTensor of size (1,)]
```

cc. @apaszke

**Comment by zou3519** [comment]
I think I found the bug. Fix incoming soon.
