### ISSUE TITLE
[NNAPI]model conversion

### ISSUE THREAD

**Issue by zhao028** [pytorch/pytorch#57937]
`nnapi_model =torch.backends._nnapi.prepare.convert_model_to_nnapi(traced, input_tensor)`
The following error will occur when using this command to convert the model：
`TorchScript export failure: Unsupported node kind ('aten::slice') in node %95 : Tensor = aten::slice(%x.1, %93, %92, %91, %93), scope: __module.model.0 # ../models/common.py:93:0`

Is there a solution to the error that occurred when converting the model?

cc @gmagogsfm cc @iseeyuan

**Comment by nikithamalgifb** [comment]
Is there a small reproducer which we can look at?

**Comment by nikithamalgifb** [comment]
cc: @iseeyuan

**Comment by raziel** [comment]
Not all operators are supported in the NNAPI. In this case slice, hence the reported error.
So the solution in this case is to remove such dependency.
