### ISSUE TITLE
A bug on the document interpreter in `torch.autograd.profiler` help page

### ISSUE THREAD

**Issue by scaomath** [pytorch/pytorch#57956]
## 🐛 Bug
In 
https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.profile.key_averages
The help looks like the following
<img src="https://sites.wustl.edu/scao/files/2021/05/pytorch-help.png" width="600">
## Reason
In the help of the `group_by_input_shapes`
https://github.com/pytorch/pytorch/blob/b587354e4c88d01600ff5da917efa392bfec122e/torch/autograd/profiler.py#L275-L289
The interpreter apparently got confused by the newline + parenthesis in `(event name, input shapes)` and thinks it is a new argument, as normally after an arg there will be something like `(type, optional)`.

cc @brianjo @mruberry @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by ngimel** [comment]
Fixed on master https://pytorch.org/docs/master/generated/torch.autograd.profiler.profile.key_averages.html?highlight=key_averages#torch.autograd.profiler.profile.key_averages

**Comment by ilia-cher** [comment]
thanks for the fix!
