### ISSUE TITLE
RuntimeError: Exporting the operator index_add to ONNX opset version 11 is not supported.

### ISSUE THREAD

**Issue by francisvac** [pytorch/pytorch#57964]
## 🚀 Feature
Support for pytroch index add operator. 

https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_add_

## Motivation

Make it easier to convert pytorch models to onnx

## Pitch

Currently some manual coding required to support models with index add to onnx.

## Alternatives

NA

## Additional context

Convert to onnx to run on tensorrt

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
should be fixed by #57830

**Comment by francisvac** [comment]
Thank you for your PR!
