### ISSUE TITLE
[local linter] mypy_wrapper doesn't filter out distributed file

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#57967]
mypy_wrapper's logic for excluding files doesn't totally match up with mypy itself (though the file below isn't listed in `mypy.ini`'s `exclude`s, so who knows what's really going on)

```bash
# this fails (but shouldn't lint this file at all)
python tools/mypy_wrapper.py $(pwd)/torch/nn/parallel/distributed.py

# but this works
mypy --config mypy.ini 
```

**Comment by samestep** [comment]
Just tested this on commit c911c30520ed25e0f0adfde1ce5794f334512c95 and it's still happening, so it was not fixed by #57998.

**Comment by samestep** [comment]
Ahh I understand now: I was thinking that this was about `ignore_errors` (which `tools/mypy_wrapper.py` does _not_ need to handle), but it's actually about `exclude`, which we didn't have when I originally wrote our `mypy` wrapper, since it was added fairly recently in #55712.

**Comment by samestep** [comment]
I am a bit confused about what exactly is going on here, since `torch/nn/parallel/distributed.py` doesn't even match our current `exclude` regex:

https://github.com/pytorch/pytorch/blob/d09abf004cc16f8fd5f320e3d5d07c383c174ea7/mypy.ini#L46

**Comment by seemethere** [comment]
From triage meeting: solution should be a warning when mypy versions do not match

**Comment by samestep** [comment]
@seemethere that sounds like a different issue from what this thread is about?

**Comment by seemethere** [comment]
> @seemethere that sounds like a different issue from what this thread is about?

We've concluded that the original issue stems from a mismatch of `mypy` versions, which is why a suggestion to warn when mypy versions do not match

**Comment by samestep** [comment]
oh I see; but I thought [we already did that](https://github.com/pytorch/pytorch/blob/cae5ddc4274cac0fed0d14dd4bbd2c213a42659e/mypy_plugins/check_mypy_version.py)?

https://github.com/pytorch/pytorch/blob/cae5ddc4274cac0fed0d14dd4bbd2c213a42659e/mypy.ini#L5

https://github.com/pytorch/pytorch/blob/cae5ddc4274cac0fed0d14dd4bbd2c213a42659e/mypy-strict.ini#L10

**Comment by seemethere** [comment]
This has already been completed, going to close
