### ISSUE TITLE
nccl2 backend distributed package

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#5797]
Hi,
   I want to build pytorch from source with nccl2 backend for distributed training, I download the [nccl2](https://developer.nvidia.com/nccl/nccl-download), but I can not extract nccl.h file, has anyone encounted with this problem?

**Comment by ngimel** [comment]
You have to get a nccl-dev package e.g. from here http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64

**Comment by gmyofustc** [comment]
@ngimel It's realy nice of you, Thanks a lot
