### ISSUE TITLE
MaxUnpool2d breaks for certain shaped inputs

### ISSUE THREAD

**Issue by abeschneider** [pytorch/pytorch#580]
The given code:

```Python
import torch
from torch import nn
from torch.autograd import Variable

data = Variable(torch.rand(1, 3, 540, 960))

pool = nn.MaxPool2d(2, 2, return_indices=True)
unpool = nn.MaxUnpool2d(2, 2)

out, indices1 = pool(data)
out, indices2 = pool(out)
out, indices3 = pool(out)

out = unpool(out, indices3)
out = unpool(out, indices2) 
out = unpool(out, indices1)
```

produces the error: 
> RuntimeError: input and indices shapes do not match: input [1 x 3 x 134 x 240], indices [1 x 3 x 135 x 240] at /.../pytorch/torch/lib/THNN/generic/SpatialMaxUnpooling.c:66

But if I use a differently sized data (e.g. (1, 3, 480, 480)) it does not.

**edit**: Forgot to add, this is for the CPU. I haven't had a chance to test CUDA yet.

**Comment by soumith** [comment]
this is because MaxPool's downsampling is ambiguous in input shape (several input shapes can be mapped to the same output shape). 

That's why, we provide: `output_size` as the third optional argument to the call operator: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/pooling.py#L243
(i should document this).

You can do:

```
import torch
from torch import nn
from torch.autograd import Variable

data = Variable(torch.rand(1, 3, 540, 960))

pool = nn.MaxPool2d(2, 2, return_indices=True)
unpool = nn.MaxUnpool2d(2, 2)

out, indices1 = pool(data)
size1 = out.size()
out, indices2 = pool(out)
size2 = out.size()
out, indices3 = pool(out)
size3 = out.size()

out = unpool(out, indices3, output_size=size3)
out = unpool(out, indices2, output_size=size2) 
out = unpool(out, indices1, output_size=size1)
```

**Comment by abeschneider** [comment]
Awesome, thanks for the quick reply!

Added documentation and possibly a warning to unsuspecting users would be great.

Also, would it make sense to make `output_size` non-optional so this error can't occur?

**Comment by abeschneider** [comment]
Hmm. When I run your code I get the error:

> ValueError: invalid output_size "[67L, 120L]" (dim 0 must be between 132 and 136)

**Comment by soumith** [comment]
yea, my modified example was slightly wrong. Edited it now to be correct.

**Comment by apaszke** [comment]
It seems to be resolved, I'm closing the issue.

**Comment by YilinLiu97** [comment]
Hi all, I think I had similar error even when I have specified the output size:

RuntimeError: found an invalid max index 16321 (output volumes are of size 6x6x6) at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/THNN/generic/VolumetricMaxUnpooling.c:118

My code:
         size_1 = x.size()
        en_1 = self.encoder_1(x) 
        en1_maxpool,indices_1 = self.maxpool_1(en_1) 
      
        size_2 = en1_maxpool.size()
        en_2 = self.encoder_2(en1_maxpool) 
        en2_maxpool,indices_2 = self.maxpool_2(en_2)
       
        size_3 = en2_maxpool.size()
        en_3 = self.encoder_3(en2_maxpool) 
        en3_maxpool,indices_3 = self.maxpool_3(en_3)
      
        de_1 = self.decoder_1(en3_maxpool)
        de1_unpool = self.unpool_1(de_1, indices_3, output_size=size_3) #transfer of indices
        merge1_3 = torch.cat((de1_unpool,en_3), 1)

        de_2 = self.decoder_2(merge1_3)
        de2_unpool = self.unpool_2(de_2, indices_2, output_size=size_2) #transfer of indices
        merge2_2 = torch.cat((de2_unpool,en_2), 1)

        de_3 = self.decoder_3(merge2_2)
        de3_unpool = self.unpool_3(de_3, indices_1, output_size=size_1) #transfer of indices
        merge3_1 = torch.cat((de3_unpool,en_1), 1)
       
        
Thanks in advance!!
