### ISSUE TITLE
Aliasing violation in vec256 leads to misoptimization

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#58031]
## 🐛 Bug

At https://github.com/pytorch/pytorch/blob/43f6deb6e447aae9d2edbd9441043b03c6ff0992/aten/src/ATen/cpu/vec256/vec256_base.h#L706 an invalid reinterpret_cast is made: `reinterpret_cast<const intmax_t*>((const T*) a);`

This casts a pointer to `T` (e.g. `int32_t`) to an unrelated type which is according to the C++ standard undefined behavior.

In PyTorch 1.7.1 this codepath was used on e.g. POWER archs (no AVX) and did in fact lead to bugs when handling tensors of size of at least 16.

## To Reproduce

1. python -c 'import torch; print(torch.ones(16, dtype=torch.int32, device="cpu") & torch.ones(16, dtype=torch.int32, device="cpu"))'

Yields e.g.
```
tensor([18939904,     8192,        0,        0,        0,        0,        0,
               0, 18939904,     8192,        0,        0,        0,        0,
               0,        0], dtype=torch.int32)
```

## Expected behavior

Output is correct (all 1s)

## Environment

PyTorch 1.7.1 with GCC 10.2.0 on POWER9 (no CUDA)

## Additional context

The correct way here would be using e.g. memcpy or something like the new `std::bit_cast`

This is optimized just the same but does not invoke undefined behavior and hence is correct even on POWER. See https://godbolt.org/z/K9foc8Y11 for a comparison of optimization

I'd also suggest to check the remaining code base for similar issues. Bugs like this are very hard to diagnose as even unrelated changes could trigger or disable them and as seen in this case upgrading the compiler can make those issues into real bugs due to new or more aggressive optimizations

Edit: One could also use the `cast` implementation for Vec256: https://godbolt.org/z/n4554v9xb

cc @VitalyFedyunin

**Comment by mruberry** [comment]
Thank you for reporting this issue, @Flamefire; I think we would accept a fix for this

**Comment by casparvl** [comment]
I'm pretty sure this was fixed by https://github.com/pytorch/pytorch/pull/69619

**Comment by Flamefire** [comment]
Yes the bug is fixed, although the solution may not be optimal: https://github.com/pytorch/pytorch/pull/58132#issuecomment-1050967746
