### ISSUE TITLE
Support `__rmod__`

### ISSUE THREAD

**Issue by asi1024** [pytorch/pytorch#58035]
## 🚀 Feature
Support `aten::remainder` for Scalar x Tensor inputs (`aten::remainder(Scalar, Tensor)`), and `torch.Tensor.__rmod__`.
(cc: @mruberry, @rgommers, @emcastillo and @kmaehashi)

## Motivation and Pitch

To enhance the compatibility with NumPy’s interface (c.f. https://github.com/pytorch/pytorch/issues/38349).

```
>>> 5 % numpy.array([1, 2, 3, 4, 5])
array([0, 1, 2, 1, 0])
>>> 5 % torch.tensor([1, 2, 3, 4, 5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'int' and 'Tensor'
```

## References

* [NumPy numpy.remainder]https://numpy.org/doc/stable/reference/generated/numpy.remainder.html)
* [Python Array API: remainder(x1, x2, /)](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#remainder-x1-x2)
* [Python Array API: Reflected Operators](https://data-apis.org/array-api/latest/API_specification/array_object.html#reflected-operators)

**Comment by mruberry** [comment]
Thanks @asi1024; we would accept a PR implementing this functionality
