### ISSUE TITLE
Module's confusing message of AttributeError

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#58038]
```python
import torch.nn as nn

class A(nn.Module):
    @property
    def myprop(self):
        return self.asd

A().myprop
# AttributeError: 'A' object has no attribute 'myprop'
```

It should complain about inexistent attribute `asd`, and not `myprop`

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment]
Is this a duplicate of https://github.com/pytorch/pytorch/issues/49726 and https://github.com/pytorch/pytorch/issues/52664 ?

**Comment by vadimkantorov** [comment]
seems so!
