### ISSUE TITLE
aten::ops namespace with unambiguous function names

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#58044]
## 🚀 Feature

An autogenerated at::ops namespace that contains:
- all operators in function form
- each operator has a unique name (e.g., there are TWO different add functions instead of a single overloaded add).
- These unique names are generated by replacing the "." in the schema name with '_'. 
- These ops are regular C++ functions that directly call into the c++ operator.

So, for example, we'd have:
```
namespace at { namespace ops {

Tensor add_Tensor(const Tensor& a, const Tensor& b, const Scalar& c) {
    return at::add(a, b, c);
}
Tensor add_Scalar(const Tensor&, const Scalar&, const Scalar&);

// NB: add_ is method-only, but under at::ops it is a function
Tensor add__Tensor(Tensor&, const Tensor&, const Scalar&);

}}
```

## Motivation

Extension writers are frustrated by (1) needing to resolve overloads on functions and (2) needing to resolve overloads on method-only operators.

I've spent countless hours writing static_casts and trying to figure out the syntax of pointer-to-method and the type of pointer-to-method. For some more context, I work a lot with templates that look like the following:
```
template <typename F, F Func, typename... ExtraArgs>
std::tuple<Tensor,optional<int64_t>> binary_pointwise_batch_rule(
    const Tensor& tensor, optional<int64_t> tensor_batch_dim,
    const Tensor& other, optional<int64_t> other_batch_dim,
    ExtraArgs... extra_args) {
...
}
```
Ideally we would just pass `binary_pointwise_batch_rule<decltype(&at::ops::mul_Tensor), &at::ops::mul_Tensor)>,
but right now we have to explicitly spell out the type of at::ops::add_Tensor to get this to work because decltype on an overloaded function is ambiguous:
```
using TensorTensorType = Tensor (*)(const Tensor&, const Tensor&);
binary_pointwise_batch_rule<TensorTensorType, &at::mul>
```

Furthermore, debugging when overload resolution goes wrong is painful because the C++ compiler writes you a sonnet every time something goes wrong with template hackery.

## Additional context

I remember @ezyang mentioning something similar to this. Happy to code this up if we think it's valuable.

**Comment by ezyang** [comment]
Yes let's do it.

This biggest objection to this is one @gchanan put forward, which is that we want to avoid a magic munging scheme for concatenating function names and overloads together. This could be worked around with a simple macro, similar to how `TORCH_META_FUNC` is implemented.
