### ISSUE TITLE
[feature request] sparse tensor support for distributed collectives

### ISSUE THREAD

**Issue by 1013553207** [pytorch/pytorch#5805]
Collective functions like  all_reduce, broadcast, reduce, all_gather and so on don't not  support sparse tensors

**Comment by vince62s** [comment]
any update on this ?

**Comment by vince62s** [comment]
Not sure to understand your question, the initial post seems clear to me, no ?

**Comment by weiyangfb** [comment]
I see what you meant, so this is request to add torch.distributed.* ops for sparse tensor.

**Comment by 1013553207** [comment]
> @vince62s Sorry for missing your comment. Would you like to provide the dense counterpart ops that you want for sparse?

yes, thanks

**Comment by pietern** [comment]
Sparse allreduce for the Gloo backend was merged in #22036.

For other sparse collectives or support for other backends, issues can be added as needed.
