### ISSUE TITLE
[nnc] Fix tensor expression for gelu

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#58053]
NNC gelu sometimes produces inaccurate results (as discovered by internal testing).  Create a repro and revert #58027

**Comment by ZolotukhinM** [comment]
Is the conclusion here that the mismatch is only against MKLDNN and not against vanilla aten implementation? Should we close this issue?

**Comment by bertmaher** [comment]
Yeah this is a false alarm, matching aten is fine.
