### ISSUE TITLE
[feature request] method to dump a Variable's underlying computation graph

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#5806]
Is there any method to dump a Variable's underlying computation graph? This will be useful for debugging use.

For example, some people may be confused about whether Variable.clone() clones the computation graph or not. In this case, a dump of the graph would be useful.

**Comment by apaszke** [comment]
https://github.com/szagoruyko/pytorchviz

We're not planning to merge such features into the core just yet.

**Comment by CDLuminate** [comment]
Thanks for the link
