### ISSUE TITLE
python process cannot normally exit after calling methods of torch.cuda

### ISSUE THREAD

**Issue by m-Just** [pytorch/pytorch#5807]
After executing the following lines and sending EOF, the shell won't normally exit and becomes unresponsive. No errors or warnings, nothing. Scripts with these two lines won't exit either, seems the process is blocked somehow. Ctrl+c does not work and I can only terminate them by kill -9.
```
>>> import torch
>>> torch.cuda.is_available()
True
```
My training script without calling the methods of torch.cuda can execute and exit normally.

System information:
- OS: Linux
- PyTorch version: 0.3.0.post4
- Python version: 2.7.12
- CUDA/cuDNN version: 8.0.61/6.0.20
- GPU models and configuration: TITAN X (Pascal)

**Comment by colesbury** [comment]
Can you run:

```
strace python -c "import torch; torch.cuda.is_available()" 2>stderr.log
```

And post stderr.log (to a gist or something)

This will trace which system calls are being made. My suspicion is that CUDA is JIT-compiling the CUDA kernels. We try to avoid this by distributing kernels compiled for recent architectures (including Pascal), but it might not be fully working in 0.3.0.post4. JIT-compilation can be quite slow, especially if your nv cache directory (default: `~/.nv/ComputeCache`) is on network storage.

You may also want to try PyTorch 0.3.1

**Comment by m-Just** [comment]
Here is the error log:
https://gist.github.com/m-Just/345307faae918cbdf54eb2699db3449d

I noticed some initial calls tried to open the lib files of cudnn-5.1.10 and ended up with ENOENT, however I found my current cudnn version is actually 6.0.20 by `cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2`, which gives:
```
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 20
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
```

My system installed both torch and pytorch, as well as different versions of cudnn, so I thought it might be the wrong setting of environment variables, and then I found that
`LD_LIBRARY_PATH=/home/ryli/cudnn-5.1.10/lib64:/home/ryli/torch/install/lib`

Finally, I tried to figure out which version pytorch is using, and it becomes even stranger:
```
>>> import torch
>>> torch.backends.cudnn.version()
7003
```

I am new to pytorch. Why is it using a different version? Is it merely caused by the wrong path variable?

**Comment by soumith** [comment]
@m-Just pytorch ships with it's own copy of cudnn.
