### ISSUE TITLE
jit compilation errors out in pytorch 1.8.1+cu11.1 pip wheel

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#58101]
## 🐛 Bug

When jit-compiling cuda code, libnvrtc tries to dlopen libnvrtc-builtins.so.11.1, but our pip package comes with only libnvrtc-builtins.so

## To Reproduce
```
import torch

@torch.jit.script
def fn(x):
    return x*x + x -3

x=torch.randn(4, device="cuda")
for _ in range(10):
    fn(x)

```
errors out with 
```
RuntimeError: nvrtc: error: failed to open libnvrtc-builtins.so.11.1.
  Make sure that libnvrtc-builtins.so.11.1 is installed correctly.
```

The libraries that come with the wheel are 
`['libc10.so', 'libc10_cuda.so', 'libcaffe2_detectron_ops_gpu.so', 'libcaffe2_module_test_dynamic.so', 'libcaffe2_nvrtc.so', 'libcaffe2_observers.so', 'libshm.so', 'libtorch.so', 'libtorch_cpu.so', 'libtorch_cuda.so', 'libtorch_cuda_cpp.so', 'libtorch_cuda_cu.so', 'libtorch_global_deps.so', 'libtorch_python.so', 'libcudart-6d56b25a.so.11.0', 'libnvToolsExt-24de1d56.so.1', 'libnvrtc-3a20f2b6.so.11.1', 'libnvrtc-builtins.so', 'libgomp-7c85b1e2.so.1']`, note there's only `libnvrtc-builtins.so`

## Environment

Pytorch 1.8.1+cu11.1 wheel. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @ngimel @gmagogsfm

**Comment by malfet** [comment]
Search library name changed between 10.2 and 11.x:
11.2:
```
$ strace -eopenat python test.py 2>&1|grep nvrtc
openat(AT_FDCWD, "/usr/local/cuda/lib64/libnvrtc.so.11.2", O_RDONLY|O_CLOEXEC) = 22
openat(AT_FDCWD, "/usr/local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc-builtins.so.11.2", O_RDONLY|O_CLOEXEC) = 22
```
10.2:
```
$ strace -eopenat python test.py 2>&1|grep nvrtc
openat(AT_FDCWD, "/usr/local/lib64/python3.8/site-packages/torch/lib/libnvrtc.so.10.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/cuda-10.2/targets/x86_64-linux/lib/libnvrtc.so.10.2", O_RDONLY|O_CLOEXEC) = 22
openat(AT_FDCWD, "/usr/local/cuda-10.2/targets/x86_64-linux/lib/libnvrtc-builtins.so", O_RDONLY|O_CLOEXEC) = 22
```

**Comment by malfet** [comment]
https://github.com/pytorch/builder/commit/77896279ecb336a8930e5815fbaa68202b44ba44 should fix it

**Comment by malfet** [comment]
Fixed, and cherry-picked in https://github.com/pytorch/builder/commit/2820343c1e98fbd061ee0a6df38436ead9ed3ae2
