### ISSUE TITLE
Distributed communication never frees target memory

### ISSUE THREAD

**Issue by TSchmiedlechner** [pytorch/pytorch#5811]
While working with the distributed package (TCP backend), I noticed that the memory used to store the target tensors in is never released by the garbage collector. Consider the following minimal example that produces a memory leak (and ultimately a crash):

```python
def run(size):
    while True:
        values = torch.zeros(100, 100000)
        target = [torch.zeros(100, 100000)] * size
        dist.all_gather(tensor_list=target, tensor=values)
        time.sleep(1)
```
Obviously, this example is pretty extreme, but the issue is also reproducible for smaller data sizes and long-running processes. When `all_gather` is removed, the memory is freed as expected.

I generally would suppose that the garbage collector should release the memory after each iteration, or at least some time after each. However, I'm relatively new to Python and PyTorch, so this may be conceptually necessary or intended?

The easiest workaround is obviously to define the target tensors outside the loop.

Adding 
```python
del target
gc.collect()
```
does not solve the problem.

System information:
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6

Thanks for developing PyTorch, keep up the good work!

**Comment by apaszke** [comment]
Thanks for the report, we'll look into that. I'd only suggest switching to a different backend (e.g. gloo or MPI), because TCP is really nearly a debug-mode thing and will likely not get anywhere close to peak performance.

**Comment by ailzhang** [comment]
Hi @TSchmiedlechner , have you tried your script on the latese master branch?
I can repro this OOM on pytorch 0.3.1 but not on the master branch. The memory consumption is pretty stable on master branch. 
Could you also give it a try and confirm? Thanks!

**Comment by stgzr** [comment]
Maybe similar issue when using PyTorch v1.0 with gloo backend.
``` Python
# test.py
batch_size = 16
feat_dim = 2048
values = torch.FloatTensor(batch_size, feat_dim + 1)
tensor_list = [torch.FloatTensor(batch_size, feat_dim + 1) for _ in range(get_world_size())]
pid = os.getpid()
prev_mem = 0
for idx in range(10000):
  if idx % 20 == 0:
    cur_mem = (int(open('/proc/%s/statm' % pid, 'r').read().split()[1]) + 0.0) / 256
    add_mem = cur_mem - prev_mem
    prev_mem = cur_mem
    print "train iterations: %s, added mem: %s M" % (idx, add_mem)
  dist.all_gather(tensor_list=tensor_list, tensor=values)
```
> mpirun -n 7 test.py
...
train iterations: 5540, added mem: 8.765625 M
train iterations: 5540, added mem: 8.765625 M
train iterations: 5540, added mem: 9.0234375 M
train iterations: 5540, added mem: 8.765625 M
train iterations: 5540, added mem: 8.765625 M
train iterations: 5540, added mem: 8.5078125 M
train iterations: 5540, added mem: 8.765625 M
train iterations: 5560, added mem: 9.0234375 M
train iterations: 5560, added mem: 8.765625 M
train iterations: 5560, added mem: 8.5078125 M
train iterations: 5560, added mem: 8.765625 M
train iterations: 5560, added mem: 8.765625 M
train iterations: 5560, added mem: 8.765625 M
train iterations: 5560, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
train iterations: 5580, added mem: 8.765625 M
...

It would eat up CPU memories. But I don't know why.
