### ISSUE TITLE
Difference to numpy linspace with endpoint False

### ISSUE THREAD

**Issue by jumlauft** [pytorch/pytorch#58129]
## 🐛 Bug

I am trying to reproduce np.linspace() with endpoint=False with torch.linspace() but end up with numerical differences.

## To Reproduce

`np.linspace(0, 1, 10, endpoint=False) - torch.linspace(0, 1, 10+1).numpy()[:-1]`

## Expected behavior
I expect the difference to be zero and not around 10e-8. 
It would be usefule to also have a `endpoint `argument in pytorch
## Environment

 - PyTorch Version (e.g., 1.0):1.8.1+cu111
 - OS (e.g., Linux): LInux
 - How you installed PyTorch (`conda`, `pip`, source):  pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:11.1 

cc @mruberry @rgommers @heitorschueroff @gchanan

**Comment by mruberry** [comment]
Thanks for reporting this issue, @jumlauft. I wonder which computation is more accurate?

**Comment by rgommers** [comment]
This is not a bug, it's simply different default for dtype:
```python
In [3]: torch.linspace(0, 1, 10+1).numpy()[:-1]
Out[3]: array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9], dtype=float32)

In [4]: np.linspace(0, 1, 10, endpoint=False)
Out[4]: array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]: np.linspace(0, 1, 10, endpoint=False) - torch.linspace(0, 1, 10+1).numpy()[:-1]
Out[5]: 
array([ 0.00000000e+00, -1.49011611e-09, -2.98023223e-09, -1.19209289e-08,
       -5.96046446e-09,  0.00000000e+00, -2.38418578e-08,  1.19209290e-08,
       -1.19209289e-08,  2.38418579e-08])

In [6]: np.linspace(0, 1, 10, endpoint=False) - torch.linspace(0, 1, 10+1, dtype=torch.float64).numpy()[:-1]
Out[6]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

The differences are simply of order `float32.eps`. 

That said, adding an `endpoint=True` keyword is a good idea.

**Comment by jumlauft** [comment]
@rgommers : Thanks for making this clear. Very helpful!
