### ISSUE TITLE
Support `__rand__`, `__ror__` and `__rxor__`

### ISSUE THREAD

**Issue by asi1024** [pytorch/pytorch#58120]
## 🚀 Feature
Support `torch.Tensor.{__rand__, __ror__, __rxor__}`.
(cc: @mruberry, @rgommers, @emcastillo and @kmaehashi)

## Motivation and Pitch

To enhance the compatibility with NumPy’s interface (c.f. https://github.com/pytorch/pytorch/issues/38349).

```py
>>> 5 & numpy.array([1, 2, 3, 4, 5])
array([1, 0, 1, 4, 5])
>>> 5 & torch.tensor([1, 2, 3, 4, 5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for &: 'int' and 'Tensor'
```

## References

* [Python Array API: Reflected Operators](https://data-apis.org/array-api/latest/API_specification/array_object.html#reflected-operators)

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
Thanks @asi1024! I think we would accept PRs for reach of these functions.
