### ISSUE TITLE
Support `__rlshift__` and `__rrshift__`

### ISSUE THREAD

**Issue by asi1024** [pytorch/pytorch#58121]
## 🚀 Feature
Support `torch.Tensor.{__rlshift__, __rrshift__}`.
(cc: @mruberry, @rgommers, @emcastillo and @kmaehashi)

## Motivation and Pitch

To enhance the compatibility with NumPy’s interface (c.f. https://github.com/pytorch/pytorch/issues/38349).

```py
>>> 1 << numpy.array([1, 2, 3])
array([2, 4, 8])
>>> 1 << torch.tensor([1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for <<: 'int' and 'Tensor'
```

## References

* [Python Array API: Reflected Operators](https://data-apis.org/array-api/latest/API_specification/array_object.html#reflected-operators)

**Comment by mruberry** [comment]
Thanks @asi1024. I think we would accept PRs for each of these functions.

**Comment by asi1024** [comment]
@mruberry I'm planning to support also function interface, but NumPy has a different interface from what Python array API specifies. Which policy of interface should we follow? Or should we support both interfaces?

[Python Array API: bitwise_left_shift](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#bitwise-left-shift-x1-x2)
[NumPy API reference: numpy.left_shift](https://numpy.org/doc/stable/reference/generated/numpy.left_shift.html#:~:text=left_shift,-numpy.&text=Shift%20the%20bits%20of%20an,at%20the%20right%20of%20x1.)

**Comment by mruberry** [comment]
Hey @asi1024! Great question. We want to implement the Python Array API, but it's OK to have extra keyword arguments, like an out= parameter, that make the function more consistent with other PyTorch functions.

**Comment by asi1024** [comment]
My concern is the difference in function names. NumPy supports `left_shift` ufunc, but Python array API specifies `bitwise_left_shift` :cry:

**Comment by mruberry** [comment]
Let's ask @rgommers if the difference is intentional. In Python it's also "left shift," so I'm a little surprised the Python Array API differs from it. Maybe an oversight?

We can also alias `bitwise_left_shift` to `left_shift` in the future.

**Comment by rgommers** [comment]
Yes, this is on purpose, see comments in: https://github.com/data-apis/array-api/pull/54. NumPy was a bit inconsistent here, prepending `bitwise_` to the four other bit-wise functions but not left/right-shift. TensorFlow was more consistent, and the stdlib `operator` used yet again different names than NumPy, so the consensus was to go with a consistent `bitwise_` prepended set of names here.

**Comment by mruberry** [comment]
Note that PyTorch already has some shift functionality:

https://github.com/pytorch/pytorch/blob/c51abf8fcacddf2d1ab02e0742d5ebfc267d8221/aten/src/ATen/native/native_functions.yaml#L5696

but it doesn't appear to be documented.
