### ISSUE TITLE
Creating an nn.Module instance with a buffer inside the init function signature of another nn.Module and then moving the main module to CUDA results in a global CUDA device being set for internal nn.Module buffers for future module instances

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#58140]
## 🐛 Bug

As the title says, creating an nn.Module instance with a buffer inside the init function signature of another nn.Module and then moving the main module to CUDA results in a global CUDA device being set for internal nn.Module buffers for future module instances

I'm not 100% sure if I explained the issue correctly in the title, so hopefully it makes sense. If not, then the test code I provided demonstrates the issue.

## To Reproduce

Running the following snippet of code:

```
import torch
import torch.nn as nn

class Test1(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("test_tensor", torch.ones(5))

    def forward(self, x):
        return x * self.test_tensor

class Test2(nn.Module):
    def __init__(self, x, test1 = Test1()):
        super().__init__()
        self.test1 = test1
        x = self.test1(x)

    def forward(self, x):
        return self.test1(x)

t = Test2(torch.ones(5)).cuda()
t = Test2(torch.ones(5)).cuda()
```

Results in the following error:

```
RuntimeError                              Traceback (most recent call last)

<ipython-input-1-cbbb24881e67> in <module>()
     21 
     22 t = Test2(torch.ones(5)).cuda()
---> 23 t = Test2(torch.ones(5)).cuda()

2 frames

<ipython-input-1-cbbb24881e67> in __init__(self, x, test1)
     15         super().__init__()
     16         self.test1 = test1
---> 17         x = self.test1(x)
     18 
     19     def forward(self, x):

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

<ipython-input-1-cbbb24881e67> in forward(self, x)
      8 
      9     def forward(self, x):
---> 10         return x * self.test_tensor
     11 
     12 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

## Expected behavior

The second instance should not be on the GPU, just like the first instance. In the test code I provided, `Test1`'s buffer should be on the CPU device when `Test2()` is called for the second time, yet for some reason it's on the GPU device.

## Environment

```
PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1+cu101
[conda] Could not collect
```

The issue also occurs on Windows as well. When the test code is run on latest PyTorch nightly build: `1.9.0.dev20210512+cu111`, it crashes the Google Colab instance instead of showing any sort of error message.

## Additional context

It almost seems like some sort of global device variable for buffers is accidentally being set.

**Comment by BlackHC** [comment]
Don't use defaults like that in `def __init__(self, x, test1 = Test1()):`.

This creates a single instance that will be passed to future constructor calls as default. This is a well-known trap when using default parameters.

Try:
```
t = Test2(torch.ones(5), Test1()).cuda()
t = Test2(torch.ones(5), Test1()).cuda()
```
and your bug will vanish.

**Comment by ProGamerGov** [comment]
@BlackHC Ah, okay thanks for the help! I'll close this issue then as it's a programming mistake by me rather than PyTorch.

**Comment by agolynski** [comment]
> Don't use defaults like that in `def __init__(self, x, test1 = Test1()):`.
> 
> This creates a single instance that will be passed to future constructor calls as default. This is a well-known trap when using default parameters.
> 
> Try:
> 
> ```
> t = Test2(torch.ones(5), Test1()).cuda()
> t = Test2(torch.ones(5), Test1()).cuda()
> ```
> 
> and your bug will vanish.

Thank you!
