### ISSUE TITLE
[NNC] Methods for debugging

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#58180]
## 🚀 Feature

There aren't great ways to debug NNC in GDB currently. I tried `std::to_string` but it did not work. To debug I had to manually add in print statements and recompile, which slows down development. It would be nice if there were a `dump` method similar to JIT or LLVM IR.

**Comment by ZolotukhinM** [comment]
We have a bunch of methods for printing statements and expressions:
https://github.com/pytorch/pytorch/blob/8a45006765fe0a902cf5a369c8696235e93edbff/torch/csrc/jit/tensorexpr/ir_printer.h#L94-L101
as well as
https://github.com/pytorch/pytorch/blob/8a45006765fe0a902cf5a369c8696235e93edbff/torch/csrc/jit/tensorexpr/ir_printer.h#L113-L115

Have you tried them?

**Comment by bertmaher** [comment]
Funny, I always add prints and recompile.  I wonder how much time I'd save by using gdb...  Anyways I think this is a good task if the linked methods don't do the trick

**Comment by eellison** [comment]
Hmm @ZolotukhinM I tried `to_string` but for some reason it gave different output than printing. I'll try `print`, I think you have linked me to it before but i forgot about it..

**Comment by ZolotukhinM** [comment]
I think I also had some troubles invoking `to_string` from a debugger - maybe it couldn't resolve the overload correctly or something. `print` on the other hand usually works well (but sometimes you need to specify namespace for it, e.g. `tensorexpr::print`).

**Comment by ZolotukhinM** [comment]
I'll close this, but please feel free to re-open if you think there is still some actions to take here.
