### ISSUE TITLE
Crash in `torch.tensor(ndarray, dtype=torch.cuda.float32)`

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#5821]
- OS: Linux
- PyTorch version: 0.4.0a0+eeb90d9
- Python version: 3.5

The following segfaults:

```python
import torch
import numpy as np
data = np.array([1.0])
torch.tensor(data, dtype=torch.float32)
torch.tensor(data, dtype=torch.cuda.float32)
```

The first tensor call with `dtype=torch.float32` seems necessary to trigger the crash on the second line.

(Reported by @Balandat)

cc @gchanan

**Comment by robert-wagner** [comment]
Per #5850 this issue should be closed
