### ISSUE TITLE
[JIT] Dynamically sized for-loop not getting traced correctly

### ISSUE THREAD

**Issue by msieb1** [pytorch/pytorch#58225]
## 🐛 Bug

When tracing a for-loop whose number of iterations is dynamic, the tracing is faulty in the sense that it will always statically assume the size of the iterable during tracing. Neither iterating through the iterable itself nor doing something like `for i in range(x.size(0))` works. Is this intended, i.e., the only way to make this work is to decorate via `@torch.jit.script`?

## To Reproduce

Code to reproduce the behavior:

```
class Foo(nn.Module):
    def __init__(self, op):
        super().__init__()
        self._op = op
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self._op(x)
    
def loop(x):
    a = torch.tensor(0).type_as(x)
    for x_ in x:
        a = a + 1
    return a

# Evaluate the op
model = Foo(loop)
with torch.no_grad():
    traced_model = torch.jit.trace(model, torch.rand(20, 4, 4).cuda(), check_trace=True)

print(traced_model(torch.rand(5, 4, 4)))
>> tensor(20.)
```

## Expected behavior

I would expect the output print to be `tensor(5.)`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.0.dev20210110+cu110
 - OS (e.g., Linux): MacOs
 - Python version: 3.7.6
 - CUDA version: 11.0

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Unfortunately this is intended for `jit.trace`, which observes all Tensor operations implemented by PyTorch. Using `jit.script` would address this problem.
