### ISSUE TITLE
Cannot perform Forward pass on CPU libtorch

### ISSUE THREAD

**Issue by InfiniteLife** [pytorch/pytorch#58227]
Windows 10, CUDA 10.1, C++. 
I'v built libtorch 1.6.1 (Release and Debug) with GPU support on my machine. Forward pass on GPU works fine, but forward pass on CPU does not. Also I have no Debug info, although I'm building in Debug mode in Visual Studio. I have had debug info for other errors.

Program fails at this step:
`auto output = module.forward({batch}).toTuple();`
 
giving exception
`Access violation reading location 0x0000019F3B22C080`

and VS says source is not available:
![image](https://user-images.githubusercontent.com/7304884/118120844-3279be00-b3f9-11eb-8aef-ffa50c0432ab.png)

Call stack also wont provide any information except some disassembly addresses.

Not sure what the problem here.
Debug info for torch is apparently loaded:
![image](https://user-images.githubusercontent.com/7304884/118121401-1d515f00-b3fa-11eb-83ee-2dc796313c35.png)

cc @yf225 @glaringlee @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
Can you please share output of `python3 -mtorch.utils.collect_env` (or run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py directly) ?

Also 1.6.1 is an old version and people tend to only fix issues for the most recent versions

**Comment by InfiniteLife** [comment]
Here is the collected information. Although it is about torch installed with pip, not one I've built. There is also a problem that prebuilt distribution of libtorch wont run with CUDA on WIndows. That's why I have to build it. I might give it a try with 1.8.1 build, though it takes some time because building libtorch takes hours.
```

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.17.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] numpydoc==0.9.2
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py36hb782905_0
[conda] mkl_fft                   1.0.15           py36h14836fe_0
[conda] mkl_random                1.1.0            py36h675688f_0
[conda] numpy                     1.18.1           py36h93ca92e_0
[conda] numpy-base                1.18.1           py36hc3f5095_1
[conda] numpydoc                  0.9.2                      py_0
[conda] torch                     1.8.0a0                  pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1+cu111              pypi_0    pypi
```

**Comment by InfiniteLife** [comment]
Same problem with 1.8.1 build(Forward pass on GPU works)

**Comment by InfiniteLife** [comment]
Okay I found the issue. In the options in project I had to check Incremental LInking to Yes (it was NO). Idk how this affect build because they supposed to equivalent. And GPU build works fine with No.

**Comment by mszhanyi** [comment]
@InfiniteLife , Did you build it with Ninja or VS.

**Comment by vladimir-aubrecht** [comment]
From the discussion seems issue was solved and considering discussion is stale, closing issue. Please create new issue if more help is needed.
