### ISSUE TITLE
libtorch: Error when using torch::from_blob

### ISSUE THREAD

**Issue by TangToy** [pytorch/pytorch#58233]
I ran the codes as follows in VS2017:
`	float array[] = { 1, 2, 3, 4, 5 };
	auto options = torch::TensorOptions().dtype(torch::kFloat64);
	torch::Tensor tharray = torch::from_blob(array, { 5 }, options);`
And got the error:
![屏幕截图 2021-05-13 215823](https://user-images.githubusercontent.com/45865043/118136176-66bf9f80-b436-11eb-8173-6012f818ce89.png)
How to solve this problem?

cc @yf225 @glaringlee

**Comment by peterjc123** [comment]
float -> torch.kFloat32

**Comment by TangToy** [comment]
> float -> torch::kFloat32

Thanks, it works now!
