### ISSUE TITLE
Add support similar to `tf.images.resize_images`.

### ISSUE THREAD

**Issue by ndronen** [pytorch/pytorch#5823]
The approaches suggested in [this thread](https://discuss.pytorch.org/t/autogradable-image-resize/580) lack an appreciation for how just nice `tf.images.resize_images` is.  It is superior to what exists in PyTorch in that it is both backprop-able and supports resizing to arbitrary sizes. I've found this combination to be particularly valuable when training fullly-convolutional networks with input images with sizes that result in feature maps with sizes that are not divisible by two. The decoder of the FCN can be programmed much more nicely when a tensor resizing feature is available.

**Comment by soumith** [comment]
this should be done, indeed it's much more elegant to have a differentiable resize_images, and we can likely build it on top of `grid_sample` that we have.

**Comment by ailzhang** [comment]
We now have nn.functional.interpolate that does the same thing except for bicubic method. https://pytorch.org/docs/master/nn.html?highlight=interpolate#torch.nn.functional.interpolate
We have another issue for it open here. https://github.com/pytorch/pytorch/issues/918
We should add it to interpolate when it's done.
