### ISSUE TITLE
Numerically inconsistent of division between numpy and torch

### ISSUE THREAD

**Issue by zhiqwang** [pytorch/pytorch#58234]
## 🐛 Bug

In the docs of [torch.div](https://pytorch.org/docs/master/generated/torch.div.html#torch.div), I noticed that

> By default, this performs a “true” division like Python 3. See the `rounding_mode` argument for floor division.

But it seems that there are still some numerical inconsistencies of the division between Numpy and PyTorch.

## To Reproduce

```python
416 / 1080
0.3851851851851852

np.divide(416, 1080)
0.3851851851851852

torch.div(416, 1080).item()
0.385185182094574

torch.div(torch.tensor(416.0), 1080.0).item()
0.385185182094574

torch.div(416.0, 1080.0).item()
0.3851851851851852
```

## Expected behavior

Maybe the result of division should be equivalent to true division in Python (the `/` operator) and NumPy’s `np.true_divide`.

## Environment

 - PyTorch Version (e.g., 1.0): `1.9.0.dev20210512+cu102`
 - OS (e.g., Linux): `Ubuntu 18.04.3 LTS (x86_64)`
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):  `pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html`
 - Python version: `3.6`
 - CUDA/cuDNN version: `10.2.89`

cc @mruberry @rgommers @heitorschueroff

**Comment by eqy** [comment]
Might be a type promotion inconsistency e.g.,
```
>>> torch.div(float(416), float(1080)).item()
0.3851851851851852
```

**Comment by zhiqwang** [comment]
Hi @eqy , the following will also output 0.385185182094574, this may cause some trouble.

```
>>> torch.div(torch.tensor(416.0), torch.tensor(1080.0)).item()
0.385185182094574

>>> (torch.tensor(416.0) / torch.tensor(1080.0)).item()
0.385185182094574
```

**Comment by mruberry** [comment]
This is a little confusing and it's happening because PyTorch's default datatype is float32 while NumPy's is float64.

```
np.divide(416, 1080)
# 0.3851851851851852
torch.div(torch.tensor((416.), dtype=torch.double), torch.tensor(1080)).item()
# 0.3851851851851852
torch.div(torch.tensor((416.), dtype=torch.float), torch.tensor(1080)).item()
# 0.385185182094574
```

When performing the division with the same datatype the result is the same.
