### ISSUE TITLE
Support F.normalize on 1-dim tensors without explicit dim

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5825]
Should we reconsider https://github.com/pytorch/pytorch/issues/3385, now that tensors and variables are unified, and functional ops can be used not only in NN minibatch context (also, consistency)?

```python
import torch

torch.nn.functional.normalize(torch.rand(10))
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File ".../lib/python2.7/site-packages/torch/nn/functional.py", line 2103, in normalize
#    return input / input.norm(p, dim, True).clamp(min=eps).expand_as(input)
#RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

torch.nn.functional.softmax(torch.rand(10))
# 0.1199
# 0.0673
# 0.1099
# 0.1007
# 0.1251
# 0.1126
# 0.0849
# 0.0697
# 0.0813
# 0.1287
#[torch.FloatTensor of size (10,)]
```
on `0.4.0a0+7f864bb`.

**Comment by apaszke** [comment]
I'm a bit split on this one. On one hand it would be useful to have `normalize` work on arbitrary tensors, on the other hand adding support to 1D things to *some* functions only will make `functional` inconsistent

**Comment by vadimkantorov** [comment]
`normalize` already works on 1-dim, it's just that default `dim` is off for 1-dim tensors. making `dim = 0` or `dim=-1` for 1-dim tensors would solve this particular case.

IMO , it makes less confusion when things work on 1-dim (good for quick testing purposes) by default compared to when they don't, even if such support is added gradually (like it happened for negative dims), it saves boiler-plate.

**Comment by soumith** [comment]
torch.nn namespace is mini-batch only, for consistency. I think we should keep it that way (unless we make a full effort to allow non-minibatch).

**Comment by vadimkantorov** [comment]
many functions from `torch.nn` are useful in a general context too (at least normalize, softmax). in my opinion, the boundaries will become even more flaky, since tensors/variables are merged. some functions in `torch.*` are also supporting batch-mode like `b*` functions or matmul
