### ISSUE TITLE
UserWarning: tensor1/other is not broadcastable to self, but they have the same number of elements. Falling back to deprecated pointwise behavior

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#5826]
- OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)
- PyTorch version:  0.4.0a0+7f864bb (Source), and 0.3.1 (Pip).

- How you installed PyTorch (conda, pip, source): Both Pip and Source
- Python version: Python2 and Python3
- CUDA/cuDNN version: Cuda 9, cuDNN v7
- GPU models and configuration: Tesla K80        
- GCC version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)

When using the Pip version (Python2 & 3), I am getting these errors when using the `torch.legacy.optim` L-BFGS and Adam optimizers: 

Running optimization with ADAM:

```
/usr/local/lib/python2.7/dist-packages/torch/legacy/optim/adam.py:65: UserWarning: tensor1 is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  x.addcdiv_(-stepSize, state['m'], state['denom'])
```
 
Running optimization with L-BFGS:

```
('<optim.lbfgs>', 'creating recyclable direction/step/history buffers')
/usr/local/lib/python2.7/dist-packages/torch/legacy/optim/lbfgs.py:197: UserWarning: other is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  x.add_(t, d)
```

This is my feval function: 

```
num_calls = [0]
def feval(x):
  num_calls[0] += 1
  net.updateOutput(x.cuda())
  grad = net.updateGradInput(x.cuda(), dy.cuda())
  loss = 0
  for mod in content_losses:
    loss = loss + mod.loss
  for mod in style_losses:
    loss = loss + mod.loss
  return loss, grad.view(grad.nelement())
```

And this is how I run it: 

```
optim_state = None
if params.optimizer == 'lbfgs':
  optim_state = {
    "maxIter": params.num_iterations,
    "verbose": True,
    "tolX": -1,
    "tolFun": -1,
  }
  if params.lbfgs_num_correction > 0:
    optim_state.nCorrection = params.lbfgs_num_correction
elif params.optimizer == 'adam':
    optim_state = {
      "learningRate": params.learning_rate,
    }

# Run optimization.
if params.optimizer == 'lbfgs':
  print("Running optimization with L-BFGS")
  x, losses = optim.lbfgs(feval, img, optim_state)
elif params.optimizer == 'adam':
  print("Running optimization with ADAM")
  for t in xrange(params.num_iterations):
    x, losses = optim.adam(feval, img, optim_state)
```

If I run the above code with the latest Github version, I get this error which happens in a completely different area: 

```
Traceback (most recent call last):
  File "test2.py", line 124, in <module>
    net.updateOutput(content_image_caffe)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/Sequential.py", line 36, in updateOutput
    currentOutput = module.updateOutput(currentOutput)
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/SpatialConvolution.py", line 84, in updateOutput
    self._viewWeight()
  File "/usr/local/lib/python2.7/dist-packages/torch/legacy/nn/SpatialConvolution.py", line 75, in _viewWeight
    self.gradWeight = self.gradWeight.view(self.nOutputPlane, self.nInputPlane * self.kH * self.kW)
RuntimeError: invalid argument 2: size '[64 x 27]' is invalid for input with 0 elements at /home/ubuntu/pytorch/aten/src/TH/THStorage.c:41
```

So I am not sure if the above error is still related to the Pip issues, if something got changed/broken, etc...

**Comment by ProGamerGov** [comment]
These might be related: https://github.com/pytorch/pytorch/issues/3268
https://discuss.pytorch.org/t/userwarning-for-torch-load-state-dict/7424
https://discuss.pytorch.org/t/userwarning-after-upgrading/4990

**Comment by ailzhang** [comment]
Hi @ProGamerGov , the warning message means the two tensors associated with the operator has the same number of elements but not broadcastable. See [here](https://github.com/pytorch/pytorch/blob/ee1b7b50b39a8261f2b2ba2a95340f51de92ddbc/docs/source/notes/broadcasting.rst#L94) for more details. 
Looks like you are running into some shape specific issues, if you could provide you minimal repro script with fake input (random Tensor with the same shape), we can help on that.

**Comment by pltrdy** [comment]
Is there a way to get errors (+ trace) for such warnings? 

It may not be trivial to find which operation does this, and the warning does not provide the trace.
