### ISSUE TITLE
A weird possible bug about operator e.g. *=, +=.

### ISSUE THREAD

**Issue by tiger2017** [pytorch/pytorch#5828]
I found a weird bug when I used the operator e.g. *= or +=, I show the code and result as below:

```
aa = Variable(torch.FloatTensor([[1,2],[3,4]]))
bb = aa
bb = bb*2
print(bb)
print(aa)

cc = Variable(torch.FloatTensor([[1,2],[3,4]]))
dd = cc
dd *= 2
print(cc)
print(dd)
```
The results showed as below:
```
Variable containing:
 2  4
 6  8
[torch.FloatTensor of size 2x2]

Variable containing:
 1  2
 3  4
[torch.FloatTensor of size 2x2]

Variable containing:
 2  4
 6  8
[torch.FloatTensor of size 2x2]

Variable containing:
 2  4
 6  8
[torch.FloatTensor of size 2x2]
```
As you see, when I used bb=bb*2, aa was not be affected. However, if using dd *= 2, cc seems to point towards (share) the same address as cc, it is changed!
But! their respective previous line is the same! e.g. bb = aa and dd = cc. It seems that the *= operator changed the original deep copy to shallow copy! and The change was made after the copy line itself!

I am wondering if this is a bug. If it is, it is important since it affect the basic mathematic operations!
Generally, I thought that just use the built-in operation functions e.g. torch.add() is a good solution.

- OS: Mac OS X
- PyTorch version: 3.0
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: None
- GPU models and configuration: None
- GCC version (if compiling from source):

**Comment by vadimkantorov** [comment]
`dd *= 2` does the multiplication in-place, applied to `dd` and in turn to `cc`, since `dd` and `cc` are the same tensor.

Results seem to conform to existing semantics.

**Comment by tiger2017** [comment]
I thought you might misunderstand my question. I understand dd *= 2 is multiplication in-place, but how the value of dd transfer into cc? but if I used dd = dd * 2, the new values did not transfer to cc? There is no difference in the previous line: dd = cc and bb =aa.
BTW, in python (not pytorch Variable or Tensor), dd *= 2 and dd = dd * 2 both will not affect cc value.
Thank you.

**Comment by fmassa** [comment]
@tiger2017 when you do `dd == cc`, you have the exact same python object with a different name (so `dd is cc` returns `True`.
And Python numbers are immutable, so that's why you might see that it doesn't change with numbers. Try it with numpy arrays and you'll see that it behaves the same as in PyTorch.

**Comment by tiger2017** [comment]
@fmassa Thank you a lot. But can you explain why result showed bb did not equal to aa (the first half part of the code), as I used the same expression bb = aa? This confused me. obviously, if I type bb == aa to check, it would return False instead.

**Comment by fmassa** [comment]
when you do `bb = bb * 2`, you create a new tensor and assign it to name `bb`.
have a look:
```python
a = torch.rand(2)
print(id(a))
b = a
print(id(b))  # same as a !
b += 1
print(id(b))  # same as before
b = b + 1
print(id(b)) # different !
```

**Comment by tiger2017** [comment]
@fmassa Appreciate! You explanation is very clear!
BTW, so pytorch use += operator this way different from python own's? I try pure python again in same way like.
```
xx = 1
yy = xx
yy = yy + 1
print(xx)

mm = 1
zz = mm
zz += 1
print(mm)
```
the prints get both "1" for xx or mm.
Am I correct?

**Comment by fmassa** [comment]
@tiger2017 not really.
The difference is that torch tensors are mutable, while python numbers are immutable.
You can try the same using python lists (which are mutable) or numpy arrays (which are mutable as well).
```python
a = 1
print(id(a))  # something
a += 1
print(id(a))  # has changed!
```

Have a look at https://stackoverflow.com/questions/8056130/immutable-vs-mutable-types for more information about mutable / immutable types in python.

**Comment by tiger2017** [comment]
@fmassa really appreciate. That is a great help!
