### ISSUE TITLE
[Doc Bug] where is classmethod torch.nn.Embedding.from_pretrained?

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#5833]
There is a method to initialize Embedding from pretrained data (torch.Tensor).

http://pytorch.org/docs/master/nn.html

However that method does not exist in pytorch 0.3.1 .

If it was deprecated, what should I do to load pretrained word vectors such as torchtext.vocab.GloVe?

```python
import torch as th
emb = th.nn.Embedding(10, 20)
emb.weight[1] = 0 # ERROR
emb.weight.requires_grad = False
emb.weight[1] = 0 # still ERROR
```

error message:
```
RuntimeError: in-place operations can be only used on variables that don't share storage with any other variables, but detected that there are 2 objects sharing it
```

**Comment by CDLuminate** [comment]
`emb.weight.data[i] = xxx` works. Please fix the documentation ...

**Comment by soumith** [comment]
the method was introduced in master, and has not yet become part of a release.
