### ISSUE TITLE
Unclear documentation or unintended behaviour for Lazy modules

### ISSUE THREAD

**Issue by vballoli** [pytorch/pytorch#58350]
## 🐛 Bug

[Docs](https://pytorch.org/docs/stable/generated/torch.nn.LazyLinear.html#torch.nn.LazyLinear) mention that bias is initialized as `UninitializedParameter` but all the lazy modules have bias as a `Parameter`.
# # To Reproduce

```python
import torch

print(list(torch.nn.LazyLinear(10, 5).named_parameters()))

"""
[('weight', Uninitialized parameter), ('bias', Parameter containing:
tensor([ 0.0000e+00, -2.5244e-29, -9.3202e+27, -2.0005e+00,  1.1210e-44,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       requires_grad=True))]
"""

print(list(torch.nn.LazyConv2d(10, 5, 5).named_parameters()))

"""
[('weight', Uninitialized parameter), ('bias', Parameter containing:
tensor([ 0.0000e+00, -2.5244e-29, -9.3202e+27, -2.0005e+00,  1.1210e-44,
        -0.0000e+00,  0.0000e+00,  0.0000e+00,  3.5873e-43,  3.6013e-43],
       requires_grad=True))]
"""
```
## Expected behavior

Either bias should be an `Uninitialized parameter` or the docs should mention that bias is initialized before the weights.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gchanan** [comment]
@albanD

**Comment by albanD** [comment]
Hi,

This should already be fixed on master. Could you install the nightly version to confirm that?
Sorry for the confusion in the 1.8 doc.

**Comment by vballoli** [comment]
Yeah, it's fixed in the nightly version. Thanks a lot @albanD @gchanan !
