### ISSUE TITLE
Tensor subclass' type is not preserved in torch.autograd.Function

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#58369]
## 🐛 Bug

When an object of tensor's subclass is saved in `torch.autograd.Function` using `ctx.save_for_backward`, the type is not preserved in the backward method when accessing it with `ctx.saved_tensors`.

## To Reproduce

This is an example script to illustrate what I meant:

    import torch

    class SubTensor(torch.Tensor):
        pass

    a = SubTensor([2]).requires_grad_()
    b = torch.tensor(1.0).requires_grad_()

    class Fcn(torch.autograd.Function):
        @staticmethod
        def forward(ctx, a, b):
            ctx.save_for_backward(a, b)
            print("a in forward :", type(a))
            c = a * b
            return c
        @staticmethod
        def backward(ctx, grad_c):
            a, b = ctx.saved_tensors
            print("a in backward:", type(a))
            return b * grad_c, a * grad_c

    c = Fcn.apply(a, b)
    print("c            :", type(c))
    da, db = torch.autograd.grad(c, (a, b))
    print("da           :", type(da))
    print("db           :", type(db))

The script above prints:

    a in forward : <class '__main__.SubTensor'>
    c            : <class '__main__.SubTensor'>
    a in backward: <class 'torch.Tensor'>
    da           : <class '__main__.SubTensor'>
    db           : <class '__main__.SubTensor'>

When saved in forward method, the type of `a` is `SubTensor`. However, when accessed in backward, the type of `a` is `torch.Tensor`.

## Expected behavior

I'm not sure if this is what PyTorch's team expected, but I expect that the type of `a` should be preserved in the backward method.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0.dev20210516
 - OS (e.g., Linux): WSL on Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.5
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by nelhage** [comment]
I think this was previously reported as #47117!

**Comment by mfkasim1** [comment]
@nelhage thanks for the pointer. I'm closing this as a duplicate.
