### ISSUE TITLE
Support Mish() activation function.

### ISSUE THREAD

**Issue by SpongeBab** [pytorch/pytorch#58375]
## 🚀 Feature
Support Mish function.

## Motivation
Now mish is widely used by all kinds of object detection models,such as yolo,efficientdet...

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Thanks for the request! As you mentioned, this activation function is quite popular and I agree we should support it in PyTorch.

* [TensorFlow](https://www.tensorflow.org/addons/api_docs/python/tfa/activations/mish) has it
* [Papers with Code](https://paperswithcode.com/method/mish) lists several popular papers that use it
* The official [GitHub repo](https://github.com/digantamisra98/Mish) implementing it has 1.1k stars

Based on the above, I'd say that we would accept a PR implementing it.

**Comment by Adnios** [comment]
Hey. Is anyone working on this? I would like to have a try.

**Comment by jbschlosser** [comment]
@Adnios No one I'm aware of is working on this atm. Feel free to go for it!

**Comment by Adnios** [comment]
> @Adnios No one I'm aware of is working on this atm. Feel free to go for it!

Thanks for your reply. I am going to try to implement it. :)

**Comment by jbschlosser** [comment]
Added in #58648. Our plan is to sneak this into PyTorch 1.9 :)
