### ISSUE TITLE
On master branch, `test_lkj_cholesky_log_prob` fails on MacOS 10.13 with `ATEN_CPU_CAPABILITY=default`

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#58381]
## 🐛 Bug

`TestDistributionsCPU.test_lkj_cholesky_log_prob` fails on MacOS 10.13 when `ATEN_CPU_CAPABILITY=default`.

## To Reproduce

Steps to reproduce the behavior on CI:

1. In `pytorch/.jenkins/pytorch/macos-test.sh`, test with `ATEN_CPU_CAPABILITY=default`, as in #58379:
https://github.com/pytorch/pytorch/blob/deb75296aea03099c8b5cfa25c48526a7501da37/.jenkins/pytorch/macos-test.sh#L66
2. `pytorch_macos_10_13_py3_test` fails:
```
Traceback (most recent call last):
 File "distributions/test_distributions.py", line 2609, in test_lkj_cholesky_log_prob
   self.assertTrue(all([x == torch.tensor(0.5).log() for x in log_probs]))
AssertionError: False is not true
```

## Expected behavior
This test doesn't fail on Linux with `ATEN_CPU_CAPABILITY=default`, so it shouldn't fail on MacOS either.

## Environment

[CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/323106/workflows/ac459637-2af0-45fb-9260-8361e49029f9/jobs/13506746/steps)

I haven't been able to test it locally on either MacOS 10.13 or MacOS 10.15, as I don't currently have access to a Mac.

## Additional context

The MacOS VM for the CI check `pytorch_macos_10_13_py3_test` is run on a Xeon E5-2697 machine that only has AVX 1.0 support.
Since AVX 1.0 support would be disabled for ATen, this CI check would then (implicitly) run with `ATEN_CPU_CAPABILITY=default` anyway, so this test should be disabled for MacOS when AVX 1.0 support would be removed from ATen (if this issue won't be fixed until then).

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @VitalyFedyunin @walterddr

**Comment by malfet** [comment]
Can reproduce it locally using latest nightly:
```
ATEN_CPU_CAPABILITY=default python3 distributions/test_distributions.py -v -k test_lkj_cholesky_log_prob
```

**Comment by malfet** [comment]
Hmm, replacing `==` with `torch.allclose` fixes the issue (and difference if default codepath between computed distribution and the actual value is 1e-16 )
