### ISSUE TITLE
Improve error messages of `torch.testing.assert_close` in case of mismatching values

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#58383]
The current implementation of `torch.testing.assert_close` already does a good job at delivering information to the user in case of mismatching values. Still, I think they can be improved in multiple ways:

1. If a scalar (tensor) is compared, the error message currently looks like this:

    ```
    AssertionError: Tensors are not close!
    
    Mismatched elements: 1 / 1 (100.0%)
    Greatest absolute difference: 1.0 at 0 (up to 1e-05 allowed)
    Greatest relative difference: 0.5 at 0 (up to 1.3e-06 allowed)
    ```
    
    This can be improved in multiple ways:
    
    - The header should read "Scalars are not close!" to indicate that only a single value was involved in the comparison
    - The number of mismatched elements should be removed since it carries no information and always is `Mismatched elements: 1 / 1 (100.0%)`
    - The word "Greatest" should be removed from the reported absolute and relative differences, since there is only one difference each
    - The index should be removed since it carries no information and scalar tensors cannot accessed by index
    
    With these changes the error message could look like:
    
    ```
    AssertionError: Scalars are not close!
    
    Absolute difference: 1.0 at 0 (up to 1e-05 allowed)
    Relative difference: 0.5 at 0 (up to 1.3e-06 allowed)
    ```
2. The only differences between the messages for closeness and equality are that

    - the header reads "not close"  instead of "not equal" and
    - the allowed tolerances are appended to the differences.
    
    We could combine the two by making the message dependent on the value of the tolerances:
    - The header should read "equal" if `rtol == 0 and atol == 0` and
    - the allowed tolerance should only be added if `> 0`
    
    This would also allow us to make `assert_equal` a special case of `assert_close` (https://github.com/pytorch/pytorch/issues/56544#issuecomment-824003067) without further modification.
3. By default the numbers in the error message are formatted with the "General format" (`:g`). This might lead to diverging formats of two related numbers if they have different magnitudes:

    ```python
    abs_diff = 1e-4
    atol = 1e-5
    print(f"Absolute difference: {abs_diff} (up to {atol} allowed)")
    ```
    
    ```
    Absolute difference: 0.0001 (up to 1e-05 allowed)
    ```
    
    We should use a fixed number format, e.g, `:.2e` for floats and `:d` for integers.
4. Non-matching NaN's currently eliminate the difference information in the error message:

    ```
    a = torch.tensor(1.0, float("NaN"))
    b = torch.tensor(2.0, float("NaN"))
    torch.testing.assert_close(a, b)
    ```
    
    ```
    AssertionError: Tensors are not close!
    Mismatched elements: 2 / 2 (100.0%)
    Greatest absolute difference: nan at 1 (up to 1e-05 allowed)
    Greatest relative difference: nan at 1 (up to 1.3e-06 allowed)
    ```
    
    We should exclude NaN's from the difference calculation and for example add a line `Mismatched NaN's: ...` in case there are any.
5. `assert_close` allows to pass a callable as `msg` to construct an expressive error message. If a user just wants to add some information, for example the tested operator, it is currently impossible to do without losing all the benefits of our message generation. We should make our version public so others can build on top of it:
    
    ```python
    import torch.testing
    
    def my_msg(actual, expected, info):
        default_msg = torch.testing.default_mismatch_msg(actual, expected, info)
        return f"My important information: ... \n\n{default_msg}"
    
    torch.testing.assert_close(..., msg=my_msg)
    ```

**Comment by mruberry** [comment]
(1) sounds good

(2) with assert_equal not being public (yet?) I wouldn't bother with its behavior

(3) displaying the numbers consistently sounds good, we just need to be sure we're displaying the exact atol and rtol

(4) I would prefer we consider including the elements being compared (NaN vs. 5), (10 vs 3) and adding more language to clarify what "at X" means --- what's "X"? Maybe something like "at flattened index..."?

(5) Instead of publicizing how our error messages are generated what about adding an optional kwarg to also print the typical message even if a custom callable is provided?

**Comment by pmeier** [comment]
> (3) displaying the numbers consistently sounds good, we just need to be sure we're displaying the exact atol and rtol

What do you mean by "exact"? Not rounded? If that is the case the only option we have is to use `:f` as format, which is really cumbersome for very small tolerances (`1e-7` vs `0.0000001`).

> (4) I would prefer we consider including the elements being compared (NaN vs. 5), (10 vs 3)

True, with my suggestion we lose the ability to locate unmatched NaN's so maybe we can leave it as is. This is only confusing if we compare NaN to NaN without setting `equal_nan=True`. Maybe we can detect this case and raise a warning in the sense "We detected you are comparing NaN values in both inputs. Maybe you want equal_nan=True?"

I'm unhappy about adding the actual values to the message. Sure for 10 vs 3 it makes sense, but if we compare random values this adds basically nothing.

> adding more language to clarify what "at X" means --- what's "X"? Maybe something like "at flattened index..."?

Maybe "at index X"? The index is already unraveled at this point.

> (5) Instead of publicizing how our error messages are generated what about adding an optional kwarg to also print the typical message even if a custom callable is provided?

Not sure what you mean. Something like `msg_(pre|post)fix` that will be added to the default message? If yes, I'm not a fan: we already have quite a few kwargs and I don't want to make it more confusing. In that case I would rather leave it as is.

**Comment by pmeier** [comment]
> (2) with assert_equal not being public (yet?) I wouldn't bother with its behavior

This also applies to `assert_close` when used with integers. If we make `assert_equal` a special case of `assert_close`, we need a replacement for 

https://github.com/pytorch/pytorch/blob/821a97595b3b0f8b1777cdd90a639078249c1846/torch/testing/_asserts.py#L407-L410

since `_check_values_equal` would also be removed. Without the proposed change an error message for a failing integer comparison 

```python
torch.testing.assert_close(1, 2)
```

could look like

```
AssertionError: Tensors are not close!

Mismatched elements: 1 / 1 (100.0%)
Greatest absolute difference: 1 at 0 (up to 0.0 allowed)
Greatest relative difference: 0.5 at 0 (up to 0.0 allowed)
```

whereas before (or with the proposed change) it looks like

```
AssertionError: Tensors are not equal!

Mismatched elements: 1 / 1 (100.0%)
Greatest absolute difference: 1 at 0
Greatest relative difference: 0.5 at 0

```

**Comment by mruberry** [comment]
> > (2) with assert_equal not being public (yet?) I wouldn't bother with its behavior
> 
> This also applies to `assert_close` when used with integers. If we make `assert_equal` a special case of `assert_close`, we need a replacement for
> 
> https://github.com/pytorch/pytorch/blob/821a97595b3b0f8b1777cdd90a639078249c1846/torch/testing/_asserts.py#L407-L410
> 
> since `_check_values_equal` would also be removed. Without the proposed change an error message for a failing integer comparison
> 
> ```python
> torch.testing.assert_close(1, 2)
> ```
> 
> could look like
> 
> ```
> AssertionError: Tensors are not close!
> 
> Mismatched elements: 1 / 1 (100.0%)
> Greatest absolute difference: 1 at 0 (up to 0.0 allowed)
> Greatest relative difference: 0.5 at 0 (up to 0.0 allowed)
> ```
> 
> whereas before (or with the proposed change) it looks like
> 
> ```
> AssertionError: Tensors are not equal!
> 
> Mismatched elements: 1 / 1 (100.0%)
> Greatest absolute difference: 1 at 0
> Greatest relative difference: 0.5 at 0
> ```

I think the "close" with atol=rtol=0 is fine and wouldn't worry about improving this case.

**Comment by mruberry** [comment]
> > (3) displaying the numbers consistently sounds good, we just need to be sure we're displaying the exact atol and rtol
> 
> What do you mean by "exact"? Not rounded? If that is the case the only option we have is to use `:f` as format, which is really cumbersome for very small tolerances (`1e-7` vs `0.0000001`).

If a user specifies 1e-7 or .00041013939393 or whatever, it would be very confusing if we failed to display the number they provided properly and would likely be perceived as a bug in assert_close, because the message would be telling them that assert_close used a different number.

> > (4) I would prefer we consider including the elements being compared (NaN vs. 5), (10 vs 3)
> 
> True, with my suggestion we lose the ability to locate unmatched NaN's so maybe we can leave it as is. This is only confusing if we compare NaN to NaN without setting `equal_nan=True`. Maybe we can detect this case and raise a warning in the sense "We detected you are comparing NaN values in both inputs. Maybe you want equal_nan=True?"
> 
> I'm unhappy about adding the actual values to the message. Sure for 10 vs 3 it makes sense, but if we compare random values this adds basically nothing.

I don't know. I think it's nice to see the actual values (especially for cases like NaN vs 5) and not very cluttersome. A suggestion to set equal_nan=True when there are NaNs being compared and they're the cause of the failure seems OK, if you like.

> > adding more language to clarify what "at X" means --- what's "X"? Maybe something like "at flattened index..."?
> 
> Maybe "at index X"? The index is already unraveled at this point.

Right but users will be thinking of the original tensors, which might have some some shape like [5, 2, 16]. In that case they would expect an index to have 3 values.

> > > (5) Instead of publicizing how our error messages are generated what about adding an optional kwarg to also print the typical message even if a custom callable is provided?
> 
> Not sure what you mean. Something like `msg_(pre|post)fix` that will be added to the default message? If yes, I'm not a fan: we already have quite a few kwargs and I don't want to make it more confusing. In that case I would rather leave it as is.

OK; we could look at exposing the function that we use to generate our message, then, so callables passed to msg could call it.

**Comment by mruberry** [comment]
You're right, the index does look correct, my mistake.

I don't think we need to worry about BC issues since the function is still a prototype and expected to change.

As long as the constraint is that the complete number for rtol and atol is displayed then sure, we can format them however.

The use case for seeing the values is that while debugging it's often helpful to identify NaN vs INF as opposed to NaN vs a value like 5 quickly. I agree in general it's interesting to see both the input and outputs, which is why we have the custom callable error message.

**Comment by pmeier** [comment]
> I don't think we need to worry about BC issues since the function is still a prototype and expected to change.

IMO we shouldn't expose it in the first place, if we are not sure that we want to keep it that way. Of course things might change in the future, but if we aren't even sure now, I see no point.

> As long as the constraint is that the complete number for rtol and atol is displayed then sure, we can format them however.

By default even when specifying no precision, the number gets rounded:

```python
x = 0.123456789
print(f"{x:e}")
print(f"{x:f}")
print(f"{x:.9f}")
```

```
1.234568e-01
0.123457
0.123456789
```

So we would need some kind of logic to determine the precision and specify it.

IMO something like `:.2e` or `:.3e` is a good compromise. Do you really think there is a good use case for specifying the tolerance with more than three or four significant digits?

**Comment by pmeier** [comment]
> The use case for seeing the values is that while debugging it's often helpful to identify NaN vs INF as opposed to NaN vs a value like 5 quickly. I agree in general it's interesting to see both the input and outputs, which is why we have the custom callable error message.

What about optionally adding a line for a single mismatched NaN

```
Mismatched NaN: Inf vs. NaN at index (0, 1, 2)
```

or something similar for multiple occurences

```
Mismatched NaN's: 3, for example Inf vs. NaN at index (0, 1, 2)
```

**Comment by mruberry** [comment]
> > The use case for seeing the values is that while debugging it's often helpful to identify NaN vs INF as opposed to NaN vs a value like 5 quickly. I agree in general it's interesting to see both the input and outputs, which is why we have the custom callable error message.
> 
> What about optionally adding a line for a single mismatched NaN
> 
> ```
> Mismatched NaN: Inf vs. NaN at index (0, 1, 2)
> ```
> 
> or something similar for multiple occurences
> 
> ```
> Mismatched NaN's: 3, for example Inf vs. NaN at index (0, 1, 2)
> ```

I don't know, that seems like a lot of complexity without much benefit. 

As for precision, if print is called on a Python float I don't think it rounds?

**Comment by pmeier** [comment]
> > > The use case for seeing the values is that while debugging it's often helpful to identify NaN vs INF as opposed to NaN vs a value like 5 quickly. I agree in general it's interesting to see both the input and outputs, which is why we have the custom callable error message.
> > 
> > 
> > What about optionally adding a line for a single mismatched NaN
> > ```
> > Mismatched NaN: Inf vs. NaN at index (0, 1, 2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or something similar for multiple occurences
> > ```
> > Mismatched NaN's: 3, for example Inf vs. NaN at index (0, 1, 2)
> > ```
> 
> I don't know, that seems like a lot of complexity without much benefit.

We need a decision. Do we want to always print the mismatching values along their difference or do we want some special handling for NaN? I prefer the latter, but no strong opinion here.

> As for precision, if print is called on a Python float I don't think it rounds?

The value will be rounded. See https://github.com/pytorch/pytorch/issues/58383#issuecomment-846762569.
