### ISSUE TITLE
Flag to check if a Module is on CUDA similar to is_cuda for Tensors

### ISSUE THREAD

**Issue by napsternxg** [pytorch/pytorch#584]
When I have an object of a class which inherits from `nn.Module` is there anyway I can check if I the object is on cuda or not. We can do this for tensors by calling `var_name.is_cuda` however no such variable is available for modules. 

Furthermore, what is the suggested ways of quickly running the whole program on cuda instead of on GPU, or by default assign all Tensors on Cuda, for a given run. Something like a context manager would be really good.

**Comment by apaszke** [comment]
That sounds useful, we'll add the flag.

You could do that with `torch.set_default_tensor_type`, but it is a bad idea and is not recommended. We don't do that by default for a reason - it's very likely to slow down your script. Do simple work on CPU and transfer the data manually.

**Comment by colesbury** [comment]
I'm not so sure about this. Modules may have parameters on multiple devices or no parameters. A module `is_cuda()` method sounds fragile.

**Comment by napsternxg** [comment]
This is what prompted me to start this issue:


```python
import torch
from torch.autograd import Variable

class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.x2o = nn.Linear(input_size, output_size)
        
    def forward(self, X):
        return self.x2o(X)

batch = Variable(torch.randn(10,3))
target = Variable(torch.randn(10,1))

no_gpu_model = LinearRegression(input_size=3, output_size=1)

no_gpu_model.forward(batch).size()
# OUT: torch.Size([10, 1])

if torch.cuda.is_available():
    gpu_model = no_gpu_model.cuda()
    try:
        print(gpu_model.forward(batch))
    except TypeError as e:
        print(e) 
```

The above code prints the following error:

```
addmm_ received an invalid combination of arguments - got (int, int, torch.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (int, int, torch.FloatTensor, torch.cuda.FloatTensor)
 * (float beta, float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (int, int, torch.FloatTensor, torch.cuda.FloatTensor)
```

The reason some functionality will be required is in the case when someone explicitly sets a Module to run on cuda backend. In that case using this flag we can set all the input values also on cuda. Otherwise, there will be compatibility issues running the same code on CPU and GPU. 

The reason I was suggesting some explicit context manager is that in the context manager we can do a graceful fallback to CPU instead of giving this error. 

@apaszke I didn't know about `torch.set_default_tensor_type`. Might be useful in a python module (again I am thinking along the lines of context manager, so that one modules defaults don't spill to other code ). I think having everything of default type might not be a very good idea. But in that case, the user should have the freedom to choose, what types they want, dynamically, based on the available device.

**Comment by colesbury** [comment]
There's a simple solution that doesn't require `Module.is_cuda()`. Use whatever condition that decides if you move the model to the GPU to move the inputs:

```python
is_cuda = torch.cuda.is_available()
if is_cuda:
  model.cuda()
  batch = Variable(batch.data.cuda())
  target = Variable(target.data.cuda())
```

**Comment by apaszke** [comment]
Alternatively (assuming your model is on a single device):
```python
next(model.parameters()).is_cuda
```

**Comment by napsternxg** [comment]
Ok, based your suggestions, I have implemented the following:

```python
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.x2o = nn.Linear(input_size, output_size)
        
    def forward(self, X):
        if next(self.x2o.parameters()).is_cuda:
            if not X.is_cuda:
                X = X.cuda()
        return self.x2o(X)

batch = Variable(torch.randn(10,3))
target = Variable(torch.randn(10,1))

no_gpu_model = LinearRegression(input_size=3, output_size=1)
print("No GPU model: ", no_gpu_model.forward(batch).size())

if torch.cuda.is_available():
    gpu_model = no_gpu_model.cuda()
    try:
        print("GPU model: ", gpu_model.forward(batch.cuda()).size())
    except TypeError as e:
        print(e)   

"""
No GPU model:  torch.Size([10, 1])
GPU model:  torch.Size([10, 1])
"""
```

Will this be the correct way to go?

**Comment by apaszke** [comment]
Keep in mind that `.cuda()` works differently on modules than on tensors - instead of returning a copy with CUDA parameters, it mutates the object, replacing CPU parameters with GPU ones. So after `gpu_model = no_gpu_model.cuda()`, `gpu_model is no_gpu_model` is True, and parameters of `no_gpu_model` are on the GPU too.

Also, we tend not to embed the input transfer in the module, but put that logic in the training loop itself.

**Comment by apaszke** [comment]
But yeah, that will work

**Comment by napsternxg** [comment]
Ok thanks for explaining the cuda copy on modules. In that case there should be a clear error message if the module is called with a non-compatible Variable.

**Comment by apaszke** [comment]
Not sure what a non-compatible Variable. As Sam noted, there is nothing that can stop people from scattering parameters over all their devices, and in that case it is ambiguous what kind of Variables are non-compatible. For that reason we're not going to implement that. I'm closing the issue for now, if you have any further questions let's move on to the forums.
