### ISSUE TITLE
The computation results on RTX 3090 are totally different from others

### ISSUE THREAD

**Issue by Nyohohoho** [pytorch/pytorch#58434]
I have once reported the speed problem of RTX 3090 in #54408 
Thanks for everyone who gave me advices and reported the similar problem.

I am using the function which converts euler angles to rotation matrix (similar to [link](https://github.com/JiawangBian/SC-SfMLearner-Release/blob/master/inverse_warp.py#L77)).

I compared the computation results from the following settings:

- RTX 3090 + PyTorch 1.8.1 with CUDA 11.1
- GTX 1080 Ti + PyTorch 1.8.1 with CUDA 10.2
- PyTorch 1.8.1 (CPU mode)
- NumPy

The results from the last 3 were the same, whereas that from RTX 3090 were totally different.
I think I should also try 'GTX 1080 Ti + PyTorch 1.8.1 with CUDA 11.1', but I am sorry I have not.

cc @ngimel @zasdfgbnm @ptrblck

**Comment by ngimel** [comment]
This is likely due to tf32, you can turn it off if you need better accuracy https://pytorch.org/docs/stable/backends.html?highlight=tf32#torch.backends.cuda.matmul.allow_tf32

**Comment by Nyohohoho** [comment]
> This is likely due to tf32, you can turn it off if you need better accuracy https://pytorch.org/docs/stable/backends.html?highlight=tf32#torch.backends.cuda.matmul.allow_tf32

Thank you very much!
I have confirmed that your advice solved my problem.
