### ISSUE TITLE
[testing] `floating_types_and_half` and `all_types_and_half` not exported to public interface

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#58469]
Not present in the list below
https://github.com/pytorch/pytorch/blob/df44f015fe1403f0fea54b46736c07550bb85870/torch/testing/_core.py#L14-L37

Was this intended?

cc: @mruberry @pmeier

**Comment by pmeier** [comment]
@kshitij12345 I only included names there that were actually used somewhere in our test suite. If `floating_types_and_half` and `all_types_and_half` are not in there, it just means you are the first one to use them :wink: You can simply add them to the list.
