### ISSUE TITLE
how to convert scriptmodel to onnx?

### ISSUE THREAD

**Issue by williamlzw** [pytorch/pytorch#58460]
how to convert scriptmodel to onnx?
D:\Python\Python37\lib\site-packages\torch\onnx\utils.py:348: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
Exception occurred when processing textline: 1

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
Could you share the repro script? Please checkout e2e example for ONNX export. https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx

**Comment by BowenBao** [comment]
Closing. Feel free to leave additional comments or re-open.

**Comment by yanghailang** [comment]
Have you found a solution? I have the same quesion.
