### ISSUE TITLE
convert scriptmodel to onnx:ONNX export failed: Couldn't export operator aten::log_softmax

### ISSUE THREAD

**Issue by williamlzw** [pytorch/pytorch#58463]
ONNX export failed: Couldn't export operator aten::log_softmax
scriptmodelv1.6 ,pytorch1.8.1

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by jiafatom** [comment]
We support exporting aten::log_softmax, and 
have a unit test `pytest test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset12::test_logsoftmax_dtype` which runs successfully. Could you have a repro for this issue?
