### ISSUE TITLE
RuntimeError: Exporting the operator linspace to ONNX opset version 11 is not supported.

### ISSUE THREAD

**Issue by NoRealLogin** [pytorch/pytorch#58472]
## 🐛 Bug

RuntimeError: Exporting the operator linspace to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce

Try to export the Pytorch model from : 
https://github.com/TRI-ML/KP2D
to an ONNX model.

```
checkpoint = torch.load(model_path)
keypoint_net = KeypointNet(use_color=True, do_upsample=True, do_cross=True)
keypoint_net.load_state_dict(checkpoint['state_dict'])
keypoint_net = keypoint_net.cuda()
keypoint_net.eval()
dummy_input = torch.randn(1,3,224,338).cuda()
torch.onnx.export(keypoint_net,(dummy_input, ),'model.onnx', opset_version=11)
```

## Expected behavior

Want `torch.onnx.export(keypoint_net,(dummy_input, ),'model.onnx', opset_version=11)` to export correctly the model

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1+cu110
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: Geforce GTX Titan X

## Additional context

I tried on opset_version 9,11,12 and version 13 is not supported.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by shubhambhokare1** [comment]
PR #58854 should add support for export of linspace op
