### ISSUE TITLE
Segmentation Fault, 4939 bus error 

### ISSUE THREAD

**Issue by episodeyang** [pytorch/pytorch#5848]
# Silently fail with bus error without traceback

- OS: OSX 10.13.1
- PyTorch version: 0.4.0a (master)
- How you installed PyTorch (conda, pip, source): source, see script below
- Python version: 3.6.1
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- Xcode: Version 9.2 (9C40b)

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

```bash
$ python demo_network.py
    
    Data size: 30000
    [1]    4939 bus error  python demo_network.py
    Process finished with exit code 138 (interrupted by signal 10: SIGBUS)
```

```make
SHELL=/usr/local/bin/bash
CONDA_ENV=conda-env-name
CONDA_PATH=$(shell which anaconda)

#VERSION=2b4748011b5881583567bb166801ca6625f2fdda
VERSION=940a0ab67bc933b0d6c24540a9e3100d213eec49  # close to master 0.4.0a
install-pytorch-osx:
# installation instruction see: https://github.com/pytorch/pytorch#install-optional-dependencies
	source activate $(CONDA_ENV) && export CMAKE_PREFIX_PATH='$(CONDA_PATH)' && \
    yes | conda install numpy pyyaml setuptools cmake cffi typing && \
    git clone --recursive https://github.com/pytorch/pytorch && \
    cd pytorch && \
    git checkout $(VERSION) && \
    MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++ python setup.py install
	rm -rf ./pytorch

conda-create:
	conda env create -f environment.yml
conda-clone:
	conda env create --name $(ENV_NAME) --file environment.yml
conda-remove:
	conda env remove --name $(CONDA_ENV)


```

**Comment by goldsborough** [comment]
Thanks for reporting this! We're missing:
- Your `demo_network.py` script
- You running `gdb python`, `run demo_network.py`, `backtrace` and posting the stack (https://wiki.python.org/moin/DebuggingWithGdb)
