### ISSUE TITLE
Bug at the interaction of torch.no_grad() and torch.nn.parallel.data_parallel

### ISSUE THREAD

**Issue by aosokin** [pytorch/pytorch#5851]
- OS: ubuntu 16.04
- PyTorch version: 0.4.0a0+875925b
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.3
- CUDA/cuDNN version: v9.1, cudnn-9.1-linux-x64-v7
- GPU models and configuration: 4x Tesla M60
- GCC version (if compiling from source):  5.4.0

When using context torch.no_grad() on a model with data_parallel operation (same with torch.nn.DataParallel) on >1 GPU the flag requires_grad does not come back to True.
If only one GPU is used then everything works fine.

Script:
```python
import torch

data = torch.cuda.FloatTensor(64, 3, 100, 100)
net = torch.nn.Conv2d(3, 1, 3)
net.cuda()

gpus = [0, 1]

out_par = torch.nn.parallel.data_parallel(net, data, device_ids=gpus, output_device=0)
print('Should be True:', out_par.requires_grad)

with torch.no_grad():
    out_par = torch.nn.parallel.data_parallel(net, data, device_ids=gpus, output_device=0)
    print('Should be False:', out_par.requires_grad)

out_par = torch.nn.parallel.data_parallel(net, data, device_ids=gpus, output_device=0)
print('Should be True:', out_par.requires_grad)
```
On 2 GPUs, this outputs
```
Should be True: True
Should be False: False
Should be True: False
```
which is wrong in the last line. On 1 GPU (set `gpus = [0]`) the output is correct.

**Comment by soumith** [comment]
@colesbury is looking into it
