### ISSUE TITLE
Add hooks to SavedVariables

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#58512]
The goal of this tasks is to provide a convenient hook system for SavedVariables.

The hooks will be a pair of python functions:
- One that goes from the current Tensor to any python object
- A second that will be able to transform that python back into the original Tensor

These operations don't need to be differentiable and any gradient information on the returned Tensor will be overwritten to have proper history.

Implementation details:
- Write a generic c++ class and a python-specialized implementation to hold the hooks (similar to anomaly_mode.h/python_anomaly_mode.h)
- Write a python binding to be able to access the SavedVariable (via pybind like c10::InferenceMode) to be able to add such hook
- Update the SavedVariable to apply such hook (pre-processing when the hook is added and post-processing while unpacking)
  - Autograd property save needs to happen during pre-processing
  - The rewrapping of the returned Tensor should be very similar to the current unpack function
  - The user hooks should run in no-grad mode
  - Inplace tests don't need to happen
- Add the corresponding tests

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by Varal7** [comment]
Tracking the progress on this issue:

* #60551 
Provide bindings for the `SavedVariable` class (for custom functions only). The `SavedTensor` object can not be created from Python and currently does not expose any method.
Undefined behavior can arise if the user decides to keep a reference to this `SavedTensor` after the underlying `SavedVariable` has been freed.
* #60685
Expose a noop `register_hook` method on `SavedTensor`. The purpose of this PR is to test error messages when the API is used incorrectly.
* #60565
Same as the first PR  but for codegen functions.
* #60663
Saves the hooks as a field of `SavedVariable` with type `std::unique_ptr<SavedVariableHooks>`. The current behavior of `register_hook` is to call `unpack(pack(data))`. The purpose is to check that packing/unpacking works correctly without handling logic about metadata and grads.

TODO: 
* Add tests (including making sure that double-backward still works)
* Add docs (including warning about lifetime issue)
* Create issue regarding the lifetime issue with `SavedTensor` objects.
