### ISSUE TITLE
module 'torch' has no attribute 'version' on miniforge conda

### ISSUE THREAD

**Issue by japrogramer** [pytorch/pytorch#58528]
## 🐛 Bug
```
import torch
from torch.utils import cpp_extension
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-71826565c829> in <module>
----> 1 from torch.utils import cpp_extension

/opt/homebrew/Caskroom/miniforge/base/envs/cartoon/lib/python3.8/site-packages/torch/utils/cpp_extension.py in <module>
    157 IS_HIP_EXTENSION = True if ((ROCM_HOME is not None) and (torch.version.hip is not None)) else False
    158 ROCM_VERSION = None
--> 159 if torch.version.hip is not None:
    160     ROCM_VERSION = tuple(int(v) for v in torch.version.hip.split('.')[:2])
    161 

AttributeError: module 'torch' has no attribute 'version
```

```
conda install pytorch torchvision

pytorch                   1.8.0           cpu_py38hc43b888_1    conda-forge
torchvision               0.9.0           py38h4ddca67_0_cpu    conda-forge
Python 3.8.10

MacBook Pro (13-inch, M1, 2020) Apple M1

```

cc @ezyang @seemethere @malfet @walterddr

**Comment by malfet** [comment]
Thank you for reporting the issue. Can you please check if builds from `pytorch-nightly` channel work for you?

**Comment by japrogramer** [comment]
@malfet sure 

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



# All requested packages already installed.

**Comment by japrogramer** [comment]
@malfet I uninstalled the packages and tried again from nightly. It works the error went away.

**Comment by rgommers** [comment]
I cannot reproduce this with `cpu_py38hd248515_1` from `conda-forge` on Linux; it's probably specific to the macOS M1 build (which I can't test). Can you please report this on https://github.com/conda-forge/pytorch-cpu-feedstock/issues @japrogramer?

**Comment by IvanYashchuk** [comment]
I can't reproduce the error on the 13-inch MacBook Pro with M1. I've installed the same versions specified in the first post in a new Python 3.8 environment of a fresh install of miniforge and all imports work and the PyTorch installation is functional.

**Comment by rgommers** [comment]
Thanks Ivan! Should be all good then.
