### ISSUE TITLE
[BUG] PyTorch does not support creating FP16 arrays from numpy.

### ISSUE THREAD

**Issue by ddkang** [pytorch/pytorch#5853]
- OS: Ubuntu 16.04
- PyTorch version: 0.3
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version: 9.0, 7.0.5
- GPU models and configuration: P100
- GCC version (if compiling from source): N/A, installed via pip

I'm in a setting where my bottleneck is transferring data to the GPU, so I would like to send the data as FP16. However, the following script fails:
```
import numpy as np
import torch

data = np.zeros(100, dtype=np.float16)
inp = torch.from_numpy(data)
inp.cuda(async=True)
```
with the error `RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.`

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

**Comment by kohr-h** [comment]
This has long been solved, see #2953
