### ISSUE TITLE
Pt. 2 RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#58547]
## 🐛 Bug

`RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 
`

## To Reproduce

```
import torch

if __name__ == "__main__":
    a = torch.rand((36, 48, 48)).requires_grad_()
    a = torch.triu(a)
    a.any()
```

## Expected behavior

Not ask me to report a bug.

## Environment

```
Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.2.3 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: Could not collect

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1
[pip3] torchvision==0.9.1
[conda] Could not collect
```

## Additional context
I upgraded to 1.8.1 and [the earlier issue I raised](https://github.com/pytorch/pytorch/issues/57684) is fixed but this is still broken.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by albanD** [comment]
Thanks for the report and the small repro!
Indeed the formula for any should be updated to use `output_differentiability: [False]` instead of non implemented as the resulting dtype is not differentiable.

As a simple workaround for now, you can do `a.detach().any()` to avoid the failure.
