### ISSUE TITLE
torch.randperm given GPU random generator raise error

### ISSUE THREAD

**Issue by Fitz13009** [pytorch/pytorch#58545]
## To Reproduce

```
import torch
rng = torch.Generator(device="cuda")
torch.set_default_tensor_type('torch.cuda.FloatTensor')
torch.randint(low=0, high=10, size=(1,), generator=rng) # Works well
idx_pts = torch.randperm(n=50, generator=rng) # Fail and raise error
```

and will get an error:
`RuntimeError: Expected a 'cuda:0' generator device but found 'cuda'`

and even if I enforce the device to cuda, error still remains:
`idx_pts = torch.randperm(n=50, device='cuda', generator=rng)`

## Expected behavior

No error should raise, just like other random functions

## Environment
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.3
Libc version: glibc-2.31

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2060 SUPER
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py39h27cfd23_1  
[conda] mkl_fft                   1.3.0            py39h42c9631_2  
[conda] mkl_random                1.2.1            py39ha9443f7_2  
[conda] numpy                     1.20.1           py39h93e21f0_0  
[conda] numpy-base                1.20.1           py39h7d8b39e_0  
[conda] pytorch                   1.8.0           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.8.0                      py39    pytorch
[conda] torchvision               0.9.0                py39_cu102    pytorch

## Additional context

Looks like the hotfix in https://github.com/pytorch/pytorch/pull/47022#issue-511864943. enforces the device to cuda:0 and thus always raise error.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @pbelevich

**Comment by ezyang** [comment]
Don't do `torch.set_default_tensor_type('torch.cuda.FloatTensor')`, it's bad and doesn't work, like you've seen here :)

**Comment by Fitz13009** [comment]
Hi, 

Thanks for your reply. Could you please explain why it is bad and not recommended except for this bug?
I know my way is hacky and is different to the fashion. 

My motivation is just to globally set the default tensor type to GPU if cuda is available, then I can directly initialize a GPU tensor by `torch.Tensor([...])` without explicitly saying device is GPU or move it to GPU using `to()`. Since I have small networks and do not work on images or parallel loaders, it is quite convenient. 

Best

**Comment by ngimel** [comment]
@ezyang in this case error is not due to `set_default_tensor_type`, the following doesn't work also
```
import torch
rng = torch.Generator(device="cuda")
idx_pts = torch.randperm(n=50, generator=rng, device="cuda")
```

**Comment by jbschlosser** [comment]
Check here fails:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Randperm.cu#L50

```python
import torch
rng = torch.Generator(device="cuda")
idx_pts = torch.randperm(n=50, generator=rng, device="cuda")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda:0' generator device but found 'cuda'
```

**Comment by malfet** [comment]
Sounds like an easy lunch time fix.

**Comment by gchanan** [comment]
what's the fix? It's not obvious to me.  Presumably that specific check is just trying to check device types?  I don't know what the model is though, should Generators have full devices?

**Comment by jbschlosser** [comment]
Note that this *does* work:
```python
import torch
rng = torch.Generator(device="cuda:0")
idx_pts = torch.randperm(n=50, generator=rng, device="cuda")
```

**Comment by gchanan** [comment]
like, I guess the options are:

1. Generators always have a fully-specified device (as with Tensors)
2. Generators can have either a fully-specified or non-fully specified device
3. Generators only have non-fully specified devices

And then for the error checking, do we check:

A. Only device types
B. Exact devices

**Comment by ngimel** [comment]
Currently, everywhere except randperm we are checking device types only https://github.com/pytorch/pytorch/blob/8ae4d07dacd004948978cdc942db932f748b9c85/aten/src/ATen/Utils.h#L101
