### ISSUE TITLE
NumPy-like `from_buffer` for creating tensor without copying data.

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#58549]
## 🚀 Feature

Follow up from #47112 
A NumPy-like `from_buffer` function for creating a tensor without copying data. 

## Alternatives

Apparently, people were using `Storage.from_buffer` and passing it to the constructor instead. There are two problems with it, though:
- When the legacy constructor is deprecated, so will be the means to create a tensor from a `Storage` object.
- As far as I can tell, `Storage.from_buffer` does copy the data.

Code in [torchvision](https://github.com/pytorch/vision/blob/2c52d9f9e3a5ebb4513f1399ae5a84df140f5c96/torchvision/transforms/functional.py#L136):

```python
img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
```

That said, it's possible to do it through NumPy, by using the `torch.from_numpy` function.

cc @mruberry @rgommers @heitorschueroff @ezyang

**Comment by ailzhang** [comment]
Is torch.from_numpy sufficient? Could you elaborate on what additional features are proposed here? Thanks!

**Comment by mruberry** [comment]
I think it's numpy.frombuffer, right?

https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html?highlight=frombuffer#numpy.frombuffer

Yes, we would accept an analogue of numpy.frombuffer. It should accept tensor options like other tensor constructors (like device, for example). For consistency we should not support the `like` parameter.
