### ISSUE TITLE
[JIT] Concat QKV Linear Layers On Frozen Models

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#58628]
## 🚀 Feature

Continuing along the lines of https://github.com/pytorch/pytorch/issues/56385, Transformers are a very popular model and we should be working to make sure that we optimize them. 

A common pattern in transformers is to apply query, key, and value linear layers on the same input, where all three linear layers have the same size weights. 

If you check out the `Using TorchScript in Python` section [here](https://huggingface.co/transformers/serialization.html)

And then modify the final two lines to print: 
```
traced_model = torch.jit.trace(model, [tokens_tensor, segments_tensors])
frozen_model = torch.jit.freeze(traced_model.eval())
print(frozen_model.graph)
```

You should see a number of these patterns: 
```
  %input.29 : Tensor = aten::layer_norm(%input.27, %1478, %self.encoder.layer.0.output.LayerNorm.weight, %self.encoder.layer.0.output.LayerNorm.bias, %50, %51)
  %x.13 : Tensor = aten::linear(%input.29, %self.encoder.layer.1.attention.self.query.weight, %self.encoder.layer.1.attention.self.query.bias)
  %x.17 : Tensor = aten::linear(%input.29, %self.encoder.layer.1.attention.self.key.weight, %self.encoder.layer.1.attention.self.key.bias)
  %x.21 : Tensor = aten::linear(%input.29, %self.encoder.layer.1.attention.self.value.weight, %self.encoder.layer.1.attention.self.value.bias)
```

We can optimize this pattern by concatenating all of the respective weights/biases, and then chunk the output into three different tensors. 

The following micro-benchmark shows the speedup of this optimization for the input/weight sizes found in [this link](https://huggingface.co/transformers/serialization.html), and the matmul sizes mentioned for BERT by [this paper](https://cs.stanford.edu/~padon/taso-sosp19.pdf).  

```
import torch
import time
from itertools import product

inp_sizes = [
    ((1, 14, 768), (768, 768), (768,)),
    ((64, 1024), (4096, 1024), (4096,)),    
]


for device, sizes in product(["cpu", "cuda"], inp_sizes):
    inp = torch.rand(sizes[0]).to(device)
    weights = [torch.rand(sizes[1]).to(device) for _ in range(3)]
    biases = [torch.rand(sizes[2]).to(device) for _ in range(3)]
    
    warmup = 5
    outputs = [0 for _ in range(3)]
    def test():
        for i in range(3):
            outputs[i] = torch._C._nn.linear(inp, weights[i], biases[i])
    
    NITER = 15
    NWARMUP = 3

    def benchmark(func):
        torch.cuda.synchronize()
        for _ in range(NWARMUP):
            func()
        torch.cuda.synchronize()
        s = time.time()
        for _ in range(NITER):
            func()
            torch.cuda.synchronize()
        e = time.time()
        return (e - s) / NITER
    
    non_fused = benchmark(test)    
    weights = torch.cat(weights)
    biases = torch.cat(biases)
    outputs2 = []
    
    def fused():
        out = torch._C._nn.linear(inp, weights, biases)
        outputs2 = torch.chunk(out, 3)
        
    fused = benchmark(fused)
    for elem1, elem2 in zip(outputs, outputs2):
        torch.testing.assert_allclose(elem1, elem2)
        
    print("sizes", sizes, "device", device, "fused speedup", (non_fused - fused)/non_fused)
```

> sizes ((1, 14, 768), (768, 768), (768,)) device cpu fused speedup 0.29792242952151143
sizes ((64, 1024), (4096, 1024), (4096,)) device cpu fused speedup -0.041824412288446286
sizes ((1, 14, 768), (768, 768), (768,)) device cuda fused speedup 0.47636900704385365
sizes ((64, 1024), (4096, 1024), (4096,)) device cuda fused speedup 0.34117876531972297

As you can see, this optimization provides a very nice speedup on GPU, while being less clear for CPU. In this first version of the issue we will only implement it for GPU. 

We are going to want to add it as part of the frozen optimization pipeline. 

Potentially helpful links: [frozen optimizations](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/frozen_graph_optimizations.cpp#L15), [code inspecting constant tensor inputs](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/frozen_conv_folding.cpp#L64).  

In the future we could consider extending thiss type of concatenation and chunking pattern to other operators, and do light-weight autotuning to determine if it is profitable to do this on CPU (additionally, we would need to update our MKLDNN fusion pass to handle chunk if we add it to CPU).

**Comment by eellison** [comment]
@Lilyjjo no

**Comment by eellison** [comment]
in terms of starting this off: 


I would take a look at https://github.com/pytorch/pytorch/pull/58433. It's pretty similar to what we want to do - iterating through frozen model and make transformations on `aten::linear` layer only for GPU. 

Here, we are looking for adjacent `aten::linear` nodes, that all have the same input, and whose weights/biases are the same size. Once we have adjacent linear nodes that fit that condition, we're going to want to concat the weights/biases as in the microbenchmark, and insert a [Constant Chunk](https://github.com/pytorch/pytorch/blob/c371542efc31b1abfe6f388042aa3ab0cef935f2/torch/csrc/jit/passes/canonicalize_graph_fuser_ops.cpp#L74), replacing the original output values with the new Chunked outputs. 

[This](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/frozen_conv_folding.cpp#L640) is also a decent pass to look because it involves taking out constant tensors from node inputs, doing some tensor compute, and then rewriting the graph.

I would be sure to look at [Graph -> Type](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/OVERVIEW.md#graph) in the overview and more if you'd like.

**Comment by bertmaher** [comment]
Looks like a cool optimization opportunity!  Something I noticed -- and hopefully I did the math right -- is that I augmented this script to compute GFLOPS/s for each of these scenarios, and they're way under peak: https://gist.github.com/bertmaher/b6987cfa0018dd44c79041af186775f3

E.g., the fused version hits only 30 gflops on 1 cpu core (peak on this box should be about 200) and on the v100 gpu it hits 450 gflops (peak should be 16 *tflops*)

**Comment by eellison** [comment]
You can get another ~5-8% speedup on top of this speed up by computing the matmul as  (weights @inp.T).T

```
import torch
import time
from itertools import product

inp_sizes = [
    ((14, 768), (768, 768), (768,)),
    ((64, 1024), (4096, 1024), (4096,)),    
]


for device, sizes in product(["cpu", "cuda"], inp_sizes):
    inp = torch.rand(sizes[0]).to(device)
    weights = [torch.rand(sizes[1]).to(device) for _ in range(3)]
    biases = [torch.rand(sizes[2]).to(device) for _ in range(3)]
    
    warmup = 5
    outputs = [0 for _ in range(3)]
    def test():
        for i in range(3):
            outputs[i] = torch._C._nn.linear(inp, weights[i], biases[i])
    
    NITER = 40
    NWARMUP = 10

    def benchmark(func):
        torch.cuda.synchronize()
        for _ in range(NWARMUP):
            func()
            torch.cuda.synchronize()
        s = time.time()
        for _ in range(NITER):
            func()
            torch.cuda.synchronize()
        e = time.time()
        return (e - s) / NITER
    
    non_fused = benchmark(test)    
    weights = torch.cat(weights)
    biases = torch.cat(biases)
    outputs2 = []
    
    def fused():
        out = torch._C._nn.linear(inp, weights, biases)
        outputs2 = torch.chunk(out, 3)
        
    fused = benchmark(fused)
    for elem1, elem2 in zip(outputs, outputs2):
        torch.testing.assert_allclose(elem1, elem2)
        
    outputs3 = []
        
    def fused_transposed():
        out = (weights @ inp.T).T + biases
        outputs3 = torch.chunk(out, 3)

        
    print("sizes", sizes, "device", device, "fused speedup", (non_fused - fused)/non_fused)

    fused2 = benchmark(fused_transposed)
    for elem1, elem2 in zip(outputs2, outputs3):
        torch.testing.assert_allclose(elem1, elem2)

    print("sizes", sizes, "device", device, "fused transposed speedup", (non_fused - fused2)/non_fused)
```
> sizes ((14, 768), (768, 768), (768,)) device cpu fused speedup 0.16893732970027245
sizes ((14, 768), (768, 768), (768,)) device cpu fused transposed speedup 0.025431425976385025
sizes ((64, 1024), (4096, 1024), (4096,)) device cpu fused speedup 0.07100073891074105
sizes ((64, 1024), (4096, 1024), (4096,)) device cpu fused transposed speedup 0.297228711533725
sizes ((14, 768), (768, 768), (768,)) device cuda fused speedup 0.4371321792173204
sizes ((14, 768), (768, 768), (768,)) device cuda fused transposed speedup 0.5170325185789768
sizes ((64, 1024), (4096, 1024), (4096,)) device cuda fused speedup 0.3508417265321348
sizes ((64, 1024), (4096, 1024), (4096,)) device cuda fused transposed speedup 0.38721827130187836

but that's for another issue !

**Comment by Gamrix** [comment]
Is there any reason why we would want the weights to be the same size in order to do this optimization? Is there an expectation/concern that concatting different sized weights would cause a performance regression?

**Comment by eellison** [comment]
@Gamrix you can't concat differently sized tensors, see: https://pytorch.org/docs/stable/generated/torch.cat.html

> >>> torch.cat([torch.rand([2, 2]), torch.rand([4, 4])])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 0. Got 2 and 4 in dimension 1 (The offending index is 1)

**Comment by Gamrix** [comment]
However, you can do this: 
```
w1 = torch.rand([10, 5])
w2 = torch.rand([20, 5])
res = torch.cat([w1, w2], 0)
```

And the linear layer is valid as long as the 0th dimensions of the input and the weight are the same.

**Comment by eellison** [comment]
We are targeting a very specific model (which is everywhere these days). Generalizing the logic could be a good follow up but would complicate the optimization and we don't have a clear use of it. E.g., you can't use chunk anymore to get the output of the use of the concatted w1 and w2
