### ISSUE TITLE
`test/test_sparse_csr.py` is not run by CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#58632]
As it is not reference from any test file nor mentioned in `run_test.py`

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @aocsa @nikitaved @pearu @mruberry @VitalyFedyunin

**Comment by ezyang** [comment]
^- @cpuhrsch

**Comment by aocsa** [comment]
I'm checking if there is any test error in the CI in this PR https://github.com/pytorch/pytorch/pull/57274. I'm sure that I covered most of the cases for CPU/CUDA however If there is any I would like to solve there.

**Comment by walterddr** [comment]
#58666 should be ready for review. could you kindly take a look @aocsa. apparently one of the expected file changed drastically when I ran the test.

**Comment by aocsa** [comment]
sure.
