### ISSUE TITLE
[Question] How can I speed up "Non Zero" operation(TBB or OpenMP or oneAPI or IPEX)?

### ISSUE THREAD

**Issue by dedoogong** [pytorch/pytorch#58636]
## ❓ Questions and Help
Hi, my CNN is quite simple 6 Conv-BN-Relu stacked network and it should run on CPU. 

The main speed bottle neck is in "nonzero" op in the last. 
It takes almost 90% of the whole processing time, so I need to optimize this op more. 

I found torch uses OpenMP or TBB's "parallel for" and Intel and facebook collaborated to make a faster one called IPEX-pytorch(mabye it is out of box). 

Does anybody can tell me how to implement a faster NonZero op?

I tried Openvino and Onnxruntime. 

1. Openvino can optimize some ops with weight but it doesn't support Nonzero op.
2. Onnxruntime is almost same as torch's nonzero op.

Thank you!

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soulitzer** [comment]
please use https://discuss.pytorch.org/ for questions
