### ISSUE TITLE
Is there any way to init one CUDA context between sub-processes launched by mp.spawn.

### ISSUE THREAD

**Issue by xshaun** [pytorch/pytorch#58649]
## ❓ Questions and Help
I found every sub-process will initGlobalState in c10, even they use the same one underlying device. Thus we cannot invoke the same CUDA stream between different processes. Is there any to share CUDA context across many processes in python-level l. Thus, we can manage CUDA streams by ourselves across multiple processes. Thanks.

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soulitzer** [comment]
please use https://discuss.pytorch.org/ for questions
