### ISSUE TITLE
Issue to compile Pytorch from source on Apple M1

### ISSUE THREAD

**Issue by jplu** [pytorch/pytorch#58653]
## 🐛 Bug

The source compilation process fails.

## To Reproduce

1. git clone https://github.com/pytorch/pytorch
1. pip install -e .

## Error

```
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
    clang: error: unable to execute command: Segmentation fault: 11
    clang: error: clang frontend command failed due to signal (use -v to see invocation)
    Apple clang version 12.0.5 (clang-1205.0.22.9)
    Target: aarch64-apple-darwin20.4.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    clang: note: diagnostic msg:
    ********************

    PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
    Preprocessed source(s) and associated run script(s) are located at:
    clang: note: diagnostic msg: /var/folders/bm/n_g1y6f53j92v5fhwt_w70bm0000gn/T/sleefsimdsp-21c854.c
    clang: note: diagnostic msg: /var/folders/bm/n_g1y6f53j92v5fhwt_w70bm0000gn/T/sleefsimdsp-21c854.sh
    clang: note: diagnostic msg: Crash backtrace is located in
    clang: note: diagnostic msg: /Users/jplu/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
    clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
    clang: note: diagnostic msg:

    ********************
    make[2]: *** [sleef/src/libm/CMakeFiles/sleefsvenofma.dir/sleefsimdsp.c.o] Error 254
    make[1]: *** [sleef/src/libm/CMakeFiles/sleefsvenofma.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
.................
make: *** [all] Error 2
    Building wheel torch-1.9.0a0+git71f4c5c
    -- Building version 1.9.0a0+git71f4c5c
    cmake --build . --target install --config Release -- -j 8
```
## Expected behavior

A smooth compilation is expected.

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 11.3.1 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: version 3.20.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] # packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/pytorch:

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr

**Comment by malfet** [comment]
This only happens with clang-1205, which added support for SVE instructions for Linux ABI, which causes compiler to crash when SVE builtins are compiled on M1. You can workaround the issue by downgrading clang or compiling PyTorch with `DISABLE_SVE=ON` option. Will submit PR in a few that automatically passes that one to sleef

**Comment by malfet** [comment]
For posterity, here is the minimal repro of the crash:
```
// Compile me as
// clang -march=armv8-a+sve f32tos32.c
#include <arm_sve.h>

svint32_t f32_to_s32(svfloat32_t vf) {
  return __builtin_sve_reinterpret_s32_f32(vf);
}
```

**Comment by jplu** [comment]
Perfect! It works as expected now. Thanks a lot for your quick fix!!
