### ISSUE TITLE
SavedVariable default hooks

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#58659]
Add system to have default hooks for SavedVariable hooks (from https://github.com/pytorch/pytorch/issues/58512)

The goal of this issue is to:
- provide a single API that allows to register such default hook and remove it
- Update SavedVariable to honor these default hooks
- Add a context manager API on the python side: `with torch.autograd.graph.saved_variable_default_hook(pack, unpack)`

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by Varal7** [comment]
For context, this will facilitate things like #28997  and #57100.
