### ISSUE TITLE
Cannot insert a Tensor that requires grad as a constant when export to ONNX model

### ISSUE THREAD

**Issue by laurence-lin** [pytorch/pytorch#58652]
I have an pretrained pytorch model, and I attempt to combine some data transformation steps with the model inference, thus I create a pipeline class:

`
pre_model = alexnet() # here use alexnet as example for my pretrained model
class mypipeline(torch.nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, input_batch):
    input_batch = input_batch.cpu().detach().numpy()
    processed_data = process_for_model(input_batch)
    pre_model.eval()
    with torch.no_grad():
      output = pretrained_model(processed_data).cpu().detach().numpy().argmax()
      self.output = output
    return output`

However, when I'm trying to export to onnx:

`pipeline = mypipeline()
torch.onnx.export(pipeline,
         dummy_input,
         "model.onnx",
         verbose = False,        
        )`

It shows the error: `RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient`

The error occur in the line: ` output = pretrained_model(processed_data).cpu().detach().numpy().argmax()`
At first I suspect that using a pretrained model in a parent class inherited nn.Module is unavailable, but when I give a dummy input to the pipeline, it works fine and creates and output prediction. 

The problems just happens when exporting to ONNX.

Could anyone give me some tips of the problem? Thank you!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment]
hi @laurence-lin, a few things I have noted from your script
1. `pre_model` is not referenced anywhere else.
2. `input_batch`, and `output` are cast to `numpy`. PyTorch ONNX exporter exports PyTorch model to ONNX. Numpy functions/modules, such as `process_for_model` and `output.numpy().argmax()`, will not be captured in the ONNX model.
3. it is recommended to move `with torch.no_grad():` to outer scope, that wraps `torch.onnx.export` call.
4. it is recommended to invoke `model.eval()` before exporting that model.

You can find more details at https://pytorch.org/docs/stable/onnx.html

**Comment by laurence-lin** [comment]
> hi @laurence-lin, a few things I have noted from your script
> 
> 1. `pre_model` is not referenced anywhere else.
> 2. `input_batch`, and `output` are cast to `numpy`. PyTorch ONNX exporter exports PyTorch model to ONNX. Numpy functions/modules, such as `process_for_model` and `output.numpy().argmax()`, will not be captured in the ONNX model.

> 3. it is recommended to move `with torch.no_grad():` to outer scope, that wraps `torch.onnx.export` call.
> 4. it is recommended to invoke `model.eval()` before exporting that model.
> 
> You can find more details at https://pytorch.org/docs/stable/onnx.html


Thank you for response, I would modify according to your suggestions. For the 2. part, how could I include numpy in the ONNX model? It's required to use numpy array because I'm processing image data.

**Comment by BowenBao** [comment]
@laurence-lin, you will need to rewrite that part in pytorch, in order to include numpy computation in the exported ONNX model.

**Comment by BowenBao** [comment]
closing, feel free to reopen if there are more questions.
