### ISSUE TITLE
QNNPACK mean with keepdim doesn't work

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#58668]
## 🐛 Bug

```python
torch.backends.quantized.engine = 'qnnpack'
print(torch.backends.quantized.engine, torch.quantize_per_tensor(torch.randn(5, 5, 5, 5), scale=0.2, zero_point=0, dtype=torch.quint8).mean((2,3), keepdim=True).shape)
torch.backends.quantized.engine = 'fbgemm'
print(torch.backends.quantized.engine, torch.quantize_per_tensor(torch.randn(5, 5, 5, 5), scale=0.2, zero_point=0, dtype=torch.quint8).mean((2,3), keepdim=True).shape)
```
Gives the wrong shape (5, 5) for qnnpack and the right shape (5, 5, 1, 1) for fbgemm.

PyTorch master.

Credit to [Alexander Soare on the PyTorch forums](https://discuss.pytorch.org/t/torch-mean-keepdim-true-with-quint8-tensor-does-not-work-with-qnnpack-backend/121740) for finding and reporting this. Thank you, Alexander!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by kimishpatel** [comment]
Thanks for reporting this. I will take a look.
