### ISSUE TITLE
Conda Binary for Python 3.6 on Next Release

### ISSUE THREAD

**Issue by alexjc** [pytorch/pytorch#587]
Hi, I'm enjoying using the library very much so far. Thanks for all the productive work!

Since Python 3.6 is now released, `conda` will install that by default when you create a new environment.  However, there are no `pytorch` binaries for 3.6 yet (at least on MacOS), just 3.5.

With this being the recommended approach to install PyTorch binaries, it'd be great for the next release to support a 3.6 package too!

**Comment by soumith** [comment]
i'll be cutting a release late today, and will have a python 3.6 version indeed

**Comment by soumith** [comment]
new version 0.1.7 pushed out, website updated. Has 3.6 binaries.
