### ISSUE TITLE
Bug in test_port_already_in_use_on_server for servers with hostnames?

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#58716]
## 🐛 Bug

The get_socket_with_port() api gets a free port bound to the "localhost" interface. This is a loopback interface.

create_c10d_store() is being a passed a servername (socket.gethostname()), which returns "localhost" if no hostname is assigned.

If a hostname is assigned, then the that name is being passed to create_c10d_store(). The problem is this hostname is assigned an actual interface IP, instead of the loopback one.

Hence in this test, the original port blocked is on the localhost loopback interface, but the c10d_store is getting a port from a proper IP assigned interface.

Normally this would pass if the servers did not have any assigned hostname. Then get_host_name() would return "localhost".

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @arindamroy-eng 

## To Reproduce

1. <on a server with hostname assigned> `python3.6 distributed/elastic/utils/distributed_test.py -v DistributedUtilTest.test_port_already_in_use_on_server`

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 12.0.0 (/src/external/llvm-project/clang 91c055b1c52a830317cae78986d0d74e433864c6)
CMake version: version 3.19.6
Libc version: glibc-2.9

Python version: 3.6 (64-bit runtime)
Python platform: Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.8.1+rocm4.0.1
[pip3] torchvision==0.9.0a0+8fb5838
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py36he8ac12f_0
[conda] mkl_fft                   1.3.0            py36h54f3939_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.18.5           py36ha1c710e_0
[conda] numpy-base                1.18.5           py36hde5b4d6_0
[conda] torch                     1.8.1+rocm4.0.1          pypi_0    pypi
[conda] torchvision               0.9.0a0+8fb5838          pypi_0    pypi
```

**Comment by wanchaol** [comment]
cc @kiukchung

**Comment by kiukchung** [comment]
Thank you for reporting. Could you provide the failure stacktrace?

**Comment by arindamroy-eng** [comment]
==============================================================
FAIL: test_port_already_in_use_on_server (__main__.DistributedUtilTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "distributed/elastic/utils/distributed_test.py", line 114, in test_port_already_in_use_on_server
    timeout=1,
AssertionError: OSError not raised

----------------------------------------------------------------------

**Comment by kiukchung** [comment]
Could you confirm that the error still persists on the HEAD of the master branch? See: https://github.com/pytorch/pytorch/issues/60260

**Comment by arindamroy-eng** [comment]
It seems that @kiukchung as already provided fixes for the same:
git show 5a2f41a2dbe
commit 5a2f41a2dbe575ff7ff7066fe642fd53006f0f36
Author: Kiuk Chung <kiuk@fb.com>
Date:   Wed Jun 23 17:10:45 2021 -0700

    [torch/distributed.elastic] Fix utils.distributed_test.test_create_store_timeout_on_server to be dual-stack ip compatible (#60558)
    
    Summary:
    Pull Request resolved: https://github.com/pytorch/pytorch/pull/60558
    
    Fixes 1/2 flaky tests as described in: https://github.com/pytorch/pytorch/issues/60260
    
    `test_create_store_timeout_on_server` tests whether trying to create a `c10d::TCPStore` server on an already taken port actually fails with an `IOError`. Prior to this change the `utils.get_socket_with_port(
)` util method was used to synthetically reserve a port, then try creating the `TCPStore` on that port to validate the `IOError`. The issue with this is that on a dual stack ip setup, `get_socket_with_port()` (s
ince it uses `socket.AF_UNSPEC`) reserves an ipv6 port, while `TCPStore` will try binding to an ipv4 port, so an `IOError` is not observed.
    
    Changing the logic of the test to create two `TCPStore` servers. The first chooses a free port (by passing `server_port=0`) while the second tries to create a `TCPStore` server on the port that the first sto
re is already running on. This would induce an `IOError` on the second store's constructor.
    
    NOTE: this change does not solve another broader issue with `TCPStore` where the server and workers can listen and connect on ipv4 vs ipv6 when they are running on dual-stak ip hosts without ipv4 DNS entry a
nd/or a `/etc/gai.conf` specifying the preferred bind ordering. See: https://github.com/pytorch/pytorch/pull/49124
    
    Test Plan:

**Comment by jithunnair-amd** [comment]
Okay thanks, it seems the above fix resolved this issue. Closing
