### ISSUE TITLE
 Invalid device ordinal at torch/csrc/cuda/Module.cpp:88

### ISSUE THREAD

**Issue by Siignature** [pytorch/pytorch#5872]
Hello all, I'm having some troubles with the assignation of the GPU. The code is the following:

```
int(gpuid)
        if not hasattr(os.environ, 'CUDA_VISIBLE_DEVICES'):
            if gpuid == -1:
                gpuid = GPU.get_free_gpu(memory)
            torch.cuda.set_device(gpuid)
        else:
            gpuid = os.environ['CUDA_VISIBLE_DEVICES']

        logging.info('Using GPU {}'.format(gpuid))
```

And I obtain the next error:

> File "/data/segovia/WriterExperiment/utils.py", line 86, in set
    torch.cuda.set_device(gpuid)
  File "/caa/Homes01/segovia/.local/lib/python3.5/site-packages/torch/cuda/__init__.py", line 244, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:88

This is my GPU configuration:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 980     Off  | 00000000:01:00.0  On |                  N/A |
> | 30%   30C    P8    12W / 200W |     27MiB /  4035MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID  Type  Process name                               Usage      |
> |=============================================================================|
> |    0      1748    G   /usr/lib/xorg/Xorg                              24MiB |
> +-----------------------------------------------------------------------------+

Thanks in advance.

**Comment by apaszke** [comment]
GPUs are still numbered from 0 when you use CUDA_VISIBLE_DEVICES, it’s just that indices map to different devices
