### ISSUE TITLE
Python Array API: support constants

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#58739]
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/constants.html) four numeric constants:

- `e`
- `inf`
- `nan`
- `pi`

PyTorch currently supports none.

cc @mruberry @rgommers @pmeier

**Comment by mruberry** [comment]
We would accept a PR implementing this functionality. I suggest we just add these in Python for now.

Does PyTorch currently import Python's math package? If so, we can probably acquire them from it. If not, let's just add them explicitly.

**Comment by pmeier** [comment]
What is missing from the specification is, if the constants should be Python scalars or 0d tensors. @rgommers do you know more about this?

**Comment by rgommers** [comment]
It's should be a regular Python `float`. Clarified in the spec now.

**Comment by gxyd** [comment]
Hi, if noone is working on this, can I try to do this?

**Comment by jaiswalshash** [comment]
Hi, I'm new to OS can anyone help me to get a better insight into this issue?: Thank You.

**Comment by pmeier** [comment]
Hey @jaiswalshash, this issue is about adding four numerical constants to the `torch` namespace, since this is required by the array API. I'll explain a little, how I would go about it (that is, you can go about this totally different as long as the result is achieved). 

@gxyd wanted to work on this so I assigned him. Maybe he can give us a status update?

---

First, we can write a test to make sure that whatever we implement behaves actually like we want it. For example we might add a test case to `test/test_torch.py`:

```python
import math
import torch

class TestConstants(TestCase):
    def test_e(self):
        self.assertIsInstance(torch.e, float)
        torch.testing.assert_close(torch.e, math.e)

    def test_pi(self):
         ...
```

Note that these tests will fail until we actually implement the constants.

---

To actually have the constants under the `torch` namespace, we have two options:

1. Implement them directly in `torch/__init__.py` or
2. implement them somewhere else and import them in `torch/__init__.py`.

I would prefer option 2, but since there is already a lot of functionality in the `__init__.py`, option 1 might also be viable. For my example I'm going to use option 2.

Since https://github.com/pytorch/pytorch/issues/58739#issuecomment-851287664 clarified that the constants should be python `float`'s, the easiest solution is to simply import them from the builtin `math` library. For example we might add a `torch/_constants.py` module with

```python
from math import e, inf, nan, pi

__all__ = ["e", "inf", "nan", "pi"]
```

and import the constants in `torch/__init__.py` with

```python
from ._constants import *
```

After this our tests should pass and you are ready to send your PR. Although it is quite a read, I recommend https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md if you don't know how to do that.

**Comment by gxyd** [comment]
@jaiswalshash and @pmeier I wasn't able to make much progress on fixing this issue. @jaiswalshash , please go ahead if you want to take it up.

**Comment by jaiswalshash** [comment]
Sure, will try my best.

**Comment by praneethratna** [comment]
Hi , I'm new to open source contributing and this issue seemed a bit interesting to me , I have given a glance in the previous explaination by pmeier and can i work on this ?

**Comment by mruberry** [comment]
Sure; anyone can work on any issue.

**Comment by praneethratna** [comment]
Could you assign me to this issue? I'll start working on it

**Comment by mruberry** [comment]
You can just start working on it.

**Comment by mahgieeee** [comment]
@mruberry hi there! It is my first time contributing to open source project, may I also work on this issue? Can I comment if I have questions about this issue on here? Thanks!

**Comment by mruberry** [comment]
> @mruberry hi there! It is my first time contributing to open source project, may I also work on this issue? Can I comment if I have questions about this issue on here? Thanks!

Yes. If you look at the contributing guide you'll see that anyone can work on any issue

**Comment by mahgieeee** [comment]
@mruberry great thanks!

**Comment by pmeier** [comment]
@mahgieeee Thanks for the will to contribute! Just note that @praneethratna already has a PR up in #59910 to close this issue.

**Comment by mahgieeee** [comment]
@pmeier thank you so much for letting me know. No problem!
