### ISSUE TITLE
[feature request]Does all nn.functional support backprop?

### ISSUE THREAD

**Issue by JohnnieXDU** [pytorch/pytorch#5873]
I wonder that do all functions in `torch.nn.functional` support backprop?

For example, can the stacked structure `net1 -> midresults -> torch.nn.functional.bilinear -> net2 -> outputs` be correctly trained end-to-end?

By the way, forum `disscuss.pytorch.org` is unable to connect, how to deal with that?

**Comment by apaszke** [comment]
They do support differentiation. The correct forum link is discuss.pytorch.org and seems to work for me. There are known issues if you’re accessing it from China.
