### ISSUE TITLE
Remainder operator breaks with divisor above 2**48 

### ISSUE THREAD

**Issue by robert-wagner** [pytorch/pytorch#5875]
- OS: Ubuntu
- PyTorch version: 3.0cpu
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): N/A

The remainder operator called on LongTensors  return an incorrect value when the divisor is above 2**48. Rather than returning a positive number in the range [0,divisor], the remainder operation either returns the original number or the divisor plus the original number. This can be replicated with the following script

```
import torch
ds = torch.LongTensor([23500,4040,-10321])
q=2**48`
new_ds = torch.LongTensor([23500,4040,q-10321])
while (ds % q).equal(new_ds):
    q+=2**32
    new_ds = torch.LongTensor([23500,4040,q-10321])
```
When the script exits the loop new_ds will be a LongTensor with the incorrect value and q will be the divisor.

**Comment by zou3519** [comment]
Something might be overflowing. Leaving this here for my reference:
```
x = torch.tensor(23500, dtype=torch.int64)
q = 392486996410368
x % q  # Much larger than 23500
```

**Comment by robert-wagner** [comment]
Is the result of x % q equal to x+q in that example? That was one of the failure modes I observed

**Comment by zou3519** [comment]
Yes

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/5906
