### ISSUE TITLE
test_sparse_csr.test_sparse_csr_print test comparison is broken

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#58762]
Relates to #58666.
Currently test `test_sparse_csr_print` is using randomized test data and comparing against a static generated expect file. We should use either a static test data generator or uses a more flexible assert.

cc @aocsa @nikitaved @pearu @mruberry @VitalyFedyunin @walterddr

**Comment by aocsa** [comment]
This issue is solved here: https://github.com/pytorch/pytorch/pull/57274

**Comment by aocsa** [comment]
closed here https://github.com/pytorch/pytorch/pull/59010
