### ISSUE TITLE
[Bug / double free?] torch.nn.Upsample crashed while forwarding a Variable

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#5876]
```python
import torch as th
print(th.__version__)
x = th.autograd.Variable(th.rand(1, 3, 2, 2))
l = th.nn.Upsample(2)
print(l(x))
```

error message:
```
$ python3 x.py 
0.3.1
free(): invalid pointer
fish: “python3 x.py” terminated by signal SIGABRT (Abort)
```

**Comment by CDLuminate** [comment]
It seems to be my mistake regarding `scale_factor` as the first argument. At least the error message should be improved when the argument is problematic.

**Comment by soumith** [comment]
I'm using https://github.com/pytorch/pytorch/issues/5400 as the master issue to track the Invalid Free on error message, closing this issue in favor of #5400
