### ISSUE TITLE
torch.linalg.* might put the info tensor on CPU even for inputs on GPU

### ISSUE THREAD

**Issue by amathews-amd** [pytorch/pytorch#58769]
## 🐛 Bug

For instance, MAGMA build without cuSOLVER torch.linalg.inv_ex might put the info tensor on CPU even for inputs on GPU. Opening a bug report, since there are other sections in BatchLinearAlgebra.cu where tensors are moved to CPU, which needs re-evaluation. 

## To Reproduce

See https://github.com/pytorch/pytorch/blob/b0833533a779d656cd6e9f6d103956ff105e7ef5/aten/src/ATen/native/cuda/BatchLinearAlgebra.cu#L1417
See discussion at: 
https://github.com/pytorch/pytorch/commit/a49406b33136a8c12503d00b1410e5596e19aede#r50939460

## Error seen
was unskipping test_cond* for HIP and MAGMA, when this happened: 
=====================================================================
22:54:39 ERROR [0.065s]: test_cond_cuda_complex128 (main.TestLinalgCUDA)
22:54:39 ----------------------------------------------------------------------
22:54:39 Traceback (most recent call last):
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1033, in wrapper
22:54:39 method(*args, **kwargs)
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 297, in instantiated_test
22:54:39 raise rte
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 292, in instantiated_test
22:54:39 result = test_fn(self, *args)
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 617, in dep_fn
22:54:39 return fn(slf, device, *args, **kwargs)
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 617, in dep_fn
22:54:39 return fn(slf, device, *args, **kwargs)
22:54:39 File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 617, in dep_fn
22:54:39 return fn(slf, device, *args, **kwargs)
22:54:39 File "test_linalg.py", line 1576, in test_cond
22:54:39 run_test_case(input, p)
22:54:39 File "test_linalg.py", line 1560, in run_test_case
22:54:39 result = torch.linalg.cond(input, p)
22:54:39 RuntimeError: expected self and mask to be on the same device, but got mask on cpu and self on cuda:0
22:54:39

## Expected behavior

Removing info to CPU removed the issue for this case: 
https://github.com/pytorch/pytorch/pull/58232 

There seems to be other sections of code where tensors are moved explicitly to CPU. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
I'm a little confused about the issue described here, @amathews-amd.

Is this a user-facing issue or an internal issue with AMD support?

In particular, can a use call inv_ex and get back tensors on different devices?

**Comment by IvanYashchuk** [comment]
I compiled PyTorch without cuSOLVER. I see that the returned `info` tensor is on CPU device for the 2D CUDA input tensors (the behavior for the batched case is correct). Even though internally MAGMA requires this argument to reside in CPU memory, still in general we should return CUDA tensors for CUDA inputs. So it's a bug that needs to be fixed.

**Comment by mruberry** [comment]
> I compiled PyTorch without cuSOLVER. I see that the returned `info` tensor is on CPU device for the 2D CUDA input tensors (the behavior for the batched case is correct). Even though internally MAGMA requires this argument to reside in CPU memory, still in general we should return CUDA tensors for CUDA inputs. So it's a bug that needs to be fixed.

Agreed. Let's use this issue to track the bug.
