### ISSUE TITLE
Cannot backward on LSTM in evaluation mode on CUDA

### ISSUE THREAD

**Issue by daemon** [pytorch/pytorch#5878]
- use case: dynamic evaluation
- compiled from source 0.4.0, commit 5014adf
- CUDA 8.0.61

I'm not sure if this is a PyTorch issue or a cuDNN one: you can't call `backward` on an output produced by LSTMs on CUDA if the model is in evaluation mode. In other words, the following code snippet doesn't run:

```python
import torch
import torch.nn as nn
import torch.autograd as ag

model = nn.LSTM(1, 1, 1)
model.cuda()
x = ag.Variable(torch.ones(1, 1, 1).cuda())
label = ag.Variable(torch.zeros(1).long().cuda())

model.eval()
model.zero_grad()
y, _ = model(x)
loss = torch.nn.functional.nll_loss(y[0], label)
loss.backward()
```

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    loss.backward()
  File "/home/r33tang/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 120, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/r33tang/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 81, in backward
    variables, grad_variables, retain_graph, create_graph)
RuntimeError: backward_input can only be called in training mode
```

However, it works on my other machine as expected (commit c65bd66, 0.4.0), so this may suggest that PyTorch is not at fault.

**Comment by ezyang** [comment]
This is a cuDNN-ism; you can't backwards if you're not in training mode. Your other machine probably doesn't have cuDNN?

**Comment by daemon** [comment]
Ah okay, thanks.
