### ISSUE TITLE
libcudnn.so: file not recognized: File truncated

### ISSUE THREAD

**Issue by karandwivedi42** [pytorch/pytorch#588]
On installing from source (CUDA 8.0, CuDNN 5.1, Ubuntu 16.04, with MAGMA and all dependencies installed)

I get the following error on `python setup.py install`
```
/usr/local/cuda/lib64/libcudnn.so: file not recognized: File truncated
```
Note: `cuda` is a symlink to `cuda-8.0` and `lib64` is also a symlink to `targets/x86_64-linux/lib`.

**Comment by soumith** [comment]
@karandwivedi42 are you sure `/usr/local/cuda/lib64/libcudnn.so` is not a corrupted file? That's what all my googling points to

**Comment by karandwivedi42** [comment]
Replaced CuDNN 5.1 with CuDNN 5 and installation proceeds normally.

Solved for me.

**Comment by soumith** [comment]
i would check if the cudnn 5.1 downloaded is not corrupted. It works fine for all of us.
I'm closing the issue as there's no action item.

**Comment by JasenWangLab** [comment]
‘’‘dds
’‘’
