### ISSUE TITLE
nn.SmoothL1Loss does not  immediate raise an error when given wrong dtype

### ISSUE THREAD

**Issue by kaare-mikkelsen** [pytorch/pytorch#58816]
## 🐛 Bug

nn.SmoothL1Loss expects the targets to be of dtype torch.float32. However, if you, for instance, pass targets that are torch.int64, nn.SmoothL1Loss will not complain until until you call loss.backward(). At this point the error is tracked back to "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py" which does not make it immediately obvious that the error is actually caused in nn.SmoothL1Loss (especially because the dtype of the loss will still be torch.float32). 

It would be much better if nn.SmoothL1Loss would complain immediately when the wrong target dtype was received.

## To Reproduce

This is a copy-paste from the original forum post that led me to file this report:
```
class my_loss:

    def __init__(self,weights):
      self.weights=weights

      #age loss:
      self.L1=nn.SmoothL1Loss(reduction='mean',beta=0.05)

      #gender loss:
      self.CE=nn.CrossEntropyLoss(reduction='mean')

    def __call__(self,output,target):
      loss = self.weights[0]*self.L1(output[:,0],target[:,0])+self.weights[1]*self.CE(output[:,1:3],target[:,1])

      return loss

#testing:
it=iter(dataloaders_dict['train'])
X,y=it.next()

criterion = my_loss(weights=(1,1))

out=model_ft(X)
loss=criterion(out,y)
print(y.dtype)
print(X.dtype)
print(out.dtype)
print(loss.dtype)

loss.backward()
```

This returns:

```
torch.int64
torch.float32
torch.float32
torch.float32
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-88-fc96d4e3072b> in <module>()
     31 print(loss.dtype)
     32 
---> 33 loss.backward()

1 frames
/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    145     Variable._execution_engine.run_backward(
    146         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 147         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    148 
    149 

RuntimeError: Found dtype Long but expected Float
```

## Expected behavior

I expected either the loss.backward() to work,  or get an error message when the wrong targets were passed to nn.SmoothL1Loss. 

## Environment

I was working in google colab.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by zou3519** [comment]
I can reproduce this with
```
import torch
import torch.nn as nn
out = torch.randn(3, 4, requires_grad=True)
y = torch.randint(0, 10, (3, 4), dtype=torch.int64)
L1=nn.SmoothL1Loss(reduction='mean',beta=0.05)
loss = L1(out, y)
loss.backward()
```
