### ISSUE TITLE
died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by Icesource** [pytorch/pytorch#58817]
## 🐛 Bug

For #29889, I ran into the exact same problem even though I used python3.6. I could train for some epochs, and this error suddenly comes out.
The error occurred when I used DDP to perform NAS on FBNet based on ImageNet dataset. If I train on cifat10 or reduce the dataset, this error does not occur.  If the problem is insufficient GPU memory, why does it report an error after training 7 epochs?

## To Reproduce

1. Download ImageNet Dataset.
2. use DistributedDataParallel to train NAS on ImageNet dataset
```
Traceback (most recent call last):
  File "/media/HardDisk1/xxx/anaconda3/envs/torch-cuda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/HardDisk1/xxx/anaconda3/envs/torch-cuda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/HardDisk1/xxx/anaconda3/envs/torch-cuda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/media/HardDisk1/xxx/anaconda3/envs/torch-cuda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/media/HardDisk1/xxx/anaconda3/envs/torch-cuda/bin/python', '-u', 'search.py', '--local_rank=0', '--ngpus_per_node', '8', '--port', '4568', '--distributed', 'True', '--dataset', 'imagenet', '--search_space', 'OnlyConv', '--dataset_path', '/media/HardDisk1/jmlu/imagenet-mxnet/imagenet', '--pretrain_epoch', '30', '--load_epoch', '30', '--batch_size', '128', '--pretrain', '/media/HardDisk1/xxx/NAS/ckpt/imagenet_OnlyConv', '--gpu', '0,1,2,3,4,5,6,7']' died with <Signals.SIGSEGV: 11>.
```

## Environment

PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.2.5

Python version: 3.6 (64-bit runtime)
Python platform: Linux-4.4.0-151-generic-x86_64-with-debian-stretch-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp
GPU 4: TITAN Xp
GPU 5: TITAN Xp
GPU 6: TITAN Xp
GPU 7: TITAN Xp

Nvidia driver version: 430.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.6
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] linformer-pytorch==0.19.3
[pip3] numpy==1.19.5
[pip3] torch==1.4.0
[pip3] torchcontrib==0.0.2
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               8.0                           3    defaults
[conda] linformer-pytorch         0.19.3                   pypi_0    pypi
[conda] mkl                       2018.0.3                      1    defaults
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchcontrib              0.0.2                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by wanchaol** [comment]
@Icesource did you try upgrading to the pytorch 1.8 and see if the issue persist? seems like the original issue reporter fixed it by upgrading the python version, so would like to check if upgrading to the latest stable release fix your problem

**Comment by lxy1108** [comment]
hi, It seems that I have the same problem, did you solve the problem?

**Comment by ReAktx** [comment]
Hello all,
seems I have the same error on my srv can someone help me to solve this ?

**Comment by Xtscat** [comment]
Hello, I met the error when using accelerate to launch the program.
But it seems that I have solved it by set the num_workers in dataloader to 0.
