### ISSUE TITLE
GHA CI failure intermittently with "local git repository checkout dirty"

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#58867]
Examples:
on PR:
https://github.com/pytorch/pytorch/runs/2657351079
on Master:
https://github.com/pytorch/pytorch/runs/2653844255

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Raising the priority on this since Windows now only runs on GHA

**Comment by seemethere** [comment]
Solved with #59450
