### ISSUE TITLE
Dispatch to Python needs adjusting to work with torchdeploy

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#58864]
Without any extra work we are going to end up with an error like this when torchfunc lands to master:

```
terminate called after throwing an instance of 'c10::Error'                                                               
  what():  Tried to register multiple backend fallbacks for the same dispatch key FuncTorchPython; previous registration r
egistered at ../torch/csrc/autograd/python_variable.cpp:1472, new registration registered at ../torch/csrc/autograd/python
_variable.cpp:1472 
```

This is because there is only one implementation of FuncTorchPython which is allowed, but if you register it from Python bindings (which you must, because your plan is to call into Python) you will register once per torchdeploy.

I believe the correct fix is to register once in non-Python bindings, and use PyInterpreter to vcall into the correct Python interpreter to do the FuncTorch handling. Should be doable, just needs to be coded.

cc @hameerabbasi @rgommers @peterbell10 @wconstab @Chillee @zou3519

**Comment by zou3519** [comment]
Interesting, thanks for the heads up

> I believe the correct fix is to register once in non-Python bindings, and use PyInterpreter to vcall into the correct Python interpreter to do the FuncTorch handling. Should be doable, just needs to be coded.

Seems reasonable

**Comment by ezyang** [comment]
Similar problem caused https://github.com/pytorch/pytorch/pull/57397 to be reverted

**Comment by ezyang** [comment]
fixed!
