### ISSUE TITLE
[nnc] in-place stmt transformation in IRmutator 

### ISSUE THREAD

**Issue by huiguoo** [pytorch/pytorch#58870]
## 🐛 Bug

We use IR mutator to modify IR in transformations like IR simplification and LoopNest. In these transformations especially LoopNest, we'd like not to invalidate the stmt handle every time IR mutator is used. To achieve this, we should make the stmt transformations in IR mutator in-place.

- [ ] For-stmt @navahgar 
- [ ] Cond-stmt @huiguoo 
- [ ] Block-stmt

**Comment by navahgar** [comment]
This was done in https://github.com/pytorch/pytorch/pull/63246
