### ISSUE TITLE
[Mkldnn] Support Prelu operator

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#58896]
## 🚀 Feature
Add ability to convert PReLU operator to mkldnn.

## Motivation
It is a very common operator that is used in many repositories, especially for classification.

## Pitch

Push support through ideep (if required).

## Alternatives

A way to automatically convert to dense for the operator

## Additional context

On latest stable and nightly, an attempt to convert the model gets this error:

RuntimeError: Could not run 'aten::prelu' with arguments from the 'MkldnnCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::prelu' is only available for these backends: [CPU, CUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by gujinghui** [comment]
@jgong5 @EikanWang

**Comment by jingxu10** [comment]
Could you share more detailed info of your usage scenario?
Like what are input data sizes? Is _num_parameters_ of PRelu mostly set to 1 or number of channels?

**Comment by xsacha** [comment]
Hi, in my situation, it is applied after the batch norm with num_parameters=64

It is done like this: https://github.com/cavalleria/cavaface.pytorch/blob/master/backbone/resattnet.py#L201

**Comment by jingxu10** [comment]
Hi, thanks for the info. May I also know your batch size?

**Comment by xsacha** [comment]
Variable batch size because it is for inference but I try to make multiples of 4.

**Comment by jingxu10** [comment]
Well noted. Thanks.

**Comment by jingxu10** [comment]
@xsacha Please check https://github.com/pytorch/pytorch/pull/60427 for the PR for adding PReLU to PyTorch.
