### ISSUE TITLE
Documentation for custom DataLoader seems to be incorrect

### ISSUE THREAD

**Issue by alex4200** [pytorch/pytorch#58903]
## 📚 Documentation

I was trying to follow the tutorial on pytorch [HERE](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) but there seems to be a problem. 

In order to use a custom dataloader (named `training_data`) I also followed the instructions [HERE](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) and created a class that returns a dictionary 

`    {"image": image, "label": label}
`

as described in the documentation, where `image` is a tensor and `label` is an integer. 

I was using this object as follows in the training script:

    train_dataloader = DataLoader(training_data, batch_size=batch_size)

and use that `DataLoader` in the method `train` as described in the documentation [HERE](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) . 

However, when I call the training method for a batch
    train(train_dataloader, model, loss_fn, optimizer)

I always get an error

    Traceback (most recent call last):
      File "train_network.py", line 110, in <module>
        train(train_dataloader, model, loss_fn, optimizer)
      File "train_network.py", line 76, in train
        X, y = X.to(device), y.to(device)
    AttributeError: 'str' object has no attribute 'to'

It turns out, that the variable `y` always has the content `label`, which is the name of the key from the returned dictionary. 

However, when I changed the return method in the DataLoader to 

`
return image, label
`

that fixed the problem. 

Could it be the documentation for the DataLoader is incorrect? 

  [1]: https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
  [2]: https://pytorch.org/tutorials/beginner/basics/data_tutorial.html

cc @SsnL @VitalyFedyunin @ejguan @brianjo @mruberry

**Comment by ejguan** [comment]
Thanks for submitting the issue. Confirm doc is incorrect.
To incorporate with `{"image": image, "label": label}`, the example needs to be modified to:
```py
train_features, train_labels = next(iter(train_dataloader)).values()
```
I will fix it.
