### ISSUE TITLE
Pytorch 2.0 release

### ISSUE THREAD

**Issue by tejan-rgb** [pytorch/pytorch#58910]
## ❓ Question

Curious about the 2.0 release and when its going to happen?

**Comment by tejan-rgb** [comment]
Is there any date for when 2.0 is scheduled for release?

**Comment by imaginary-person** [comment]
It'd [probably be 90 days](https://github.com/pytorch/pytorch#releases-and-contributing) after the release of 1.9.0.

**Comment by surak** [comment]
Well, it's out, but there's no source tag

**Comment by nyngwang** [comment]
@surak So how to get it?

**Comment by surak** [comment]
> @surak So how to get it?

https://pytorch.org/get-started/pytorch-2.0/
