### ISSUE TITLE
grid_sampler_3d_cuda Function Error?

### ISSUE THREAD

**Issue by SuperPowerLF2** [pytorch/pytorch#58976]
## Issue description

GridSampler.cu  Line 760  "grid_sampler_3d_cuda" Function
Is it written wrong?

## Code example
GridSampler.cu
Line 760
    AT_DISPATCH_FLOATING_TYPES_AND_HALF(input.scalar_type(), "**grid_sampler_2d_cuda**", [&] {

## System Info

Download time 2021/5/25 13:28 version master(1.7.1? 1.8.0? I don't know)

**Comment by ngimel** [comment]
Thanks for reporting, it's a typo in the string used to create error message, so it doesn't affect normal operation. We'll accept a PR fixing this.
