### ISSUE TITLE
[help wanted] Reduce build verbosity to necessary minimum

### ISSUE THREAD

**Issue by singam-sanjay** [pytorch/pytorch#5898]
- OS: Ubuntu 16.04
- PyTorch version: master branch in Dec 2017
- How you installed PyTorch (conda, pip, source): local build
- Python version: 3.6
- GCC version (if compiling from source): 5.4.0

Is it possible to disable all messages (configuration settings, build commands, etc.) except error messages and the progress percentage during build ? There doesn't seem to be straight forward option of setting the verbosity level.

**Comment by apaszke** [comment]
Why would that be beneficial? You can always pipe the logs to /dev/null, but when they are verbose then at least they will give you an error message if they fail.

**Comment by ezyang** [comment]
I'm sure ninja/make have appropriate options to suppress the output. Happy to accept a PR that plumbs some sort of env var through to the underlying commands as necessary.

**Comment by ezyang** [comment]
ninja suppresses by default now
