### ISSUE TITLE
Get stuck while using pytorch.profiler

### ISSUE THREAD

**Issue by Rivendile** [pytorch/pytorch#58983]
## To Reproduce

I add the following code related to profiling in my code and the original code can be run successfully.

```
def trace_handler(prof):
    print(prof.key_averages().table(
        sort_by="self_cuda_time_total", row_limit=-1))
    prof.export_chrome_trace("./logs/test_trace_" + str(prof.step_num) + ".json")`

with torch.profiler.profile(
        schedule=torch.profiler.schedule(
            wait=0,
            warmup=0,
            active=10,
            repeat=0),
        on_trace_ready=trace_handler,
        record_shapes=True,
        profile_memory=True
    ) as prof:
      code_to_profile()
      prof.step()

```
But the code is stuck after 10 iterations, only the trace of step 0 is saved and no print. I tried this on a single GPU and on 8 GPUs with horovod, and both settings get similar situation. Is there any advice?

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:V100
 - Any other relevant information:

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by Rivendile** [comment]
I tried to change wait=2 and warmup=3, then it works. It seems that the parameters of schedule have some constraints. Perhaps these should be added in the documentation.

**Comment by liuyhlinux** [comment]
It seems deadlock with multi-processing training

**Comment by sraikund16** [comment]
Closing because stale and performance has changed significantly since
