### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jameschartouni** [pytorch/pytorch#5903]
When I try to execute the command 'docker build -t pytorch .'  to build a new image, I got this error: 

cees@cees1:~/pytorch$ docker build -t pytorch .
Sending build context to Docker daemon  134.1MB
Step 1/11 : FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> 3ada27a3ae03
Step 2/11 : RUN apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          vim          ca-certificates          libjpeg-dev          libpng-dev &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 136c8e439c45
Err:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
  Temporary failure resolving 'developer.download.nvidia.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:5 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
  Temporary failure resolving 'developer.download.nvidia.com'
Err:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/InRelease  Temporary failure resolving 'developer.download.nvidia.com'
W: Failed to fetch http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/InRelease  Temporary failure resolving 'developer.download.nvidia.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package cmake is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cmake' has no installation candidate
E: Unable to locate package git
E: Unable to locate package curl
E: Unable to locate package vim
E: Unable to locate package ca-certificates
E: Unable to locate package libjpeg-dev
E: Unable to locate package libpng-dev
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends          build-essential          cmake          git          curl          vim          ca-certificates          libjpeg-dev          libpng-dev &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

OS -Ubuntu 17.10
Recent source install
GCC 6 (but i've tried both 4.8 and 7)
GPU 1080ti 
PyTorch GitHub Issues Guidelines
Thanks!
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by apaszke** [comment]
Looks like your container can't access the internet. Try spinning the base one and seeing if you don't have a firewall blocking docker or sth like this

**Comment by jameschartouni** [comment]
I receive a similar error. I'll check with IT to see if the problem is with the network. Thanks!
