### ISSUE TITLE
Broken link for object detection instance segmentation (torchvision)

### ISSUE THREAD

**Issue by yassineAlouini** [pytorch/pytorch#59078]
## 📚 Documentation

It seems that the following link that can be reached from here (check the screenshot) is broken: 

- Page: https://pytorch.org/hub/pytorch_vision_fcn_resnet101/
- Broken link: https://pytorch.org/docs/stable/torchvision/models.html#object-detection-instance-segmentation-and-person-keypoint-detection
- Screenshot:

![documentation_pytorch](https://user-images.githubusercontent.com/8986994/119827950-fdda2c00-bef9-11eb-8012-dd648928bfe1.png)

cc @ailzhang @fmassa @vfdev-5 @pmeier

**Comment by pmeier** [comment]
@ailzhang this should be transferred to `pytorch/hub`, but I don't have permissions to do that. Fix is available at pytorch/hub#202.
