### ISSUE TITLE
Support UCS2 Python

### ISSUE THREAD

**Issue by angelleng** [pytorch/pytorch#591]
on linux, python-2.7, cuda-7.5, installed using pip. 

`import torch` it gives the error: 
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingleng/.local/lib/python2.7/site-packages/torch/__init__.py", line 45, in <module>
    from torch._C import *
ImportError: /home/jingleng/.local/lib/python2.7/site-packages/torch/_C.so: undefined symbol: PyUnicodeUCS4_AsUTF8String
```

**Comment by soumith** [comment]
this means that you have a UCS2 based python 2.7 installation (it's a version that sometimes we encounter . We dont build binaries for this python yet, I'll fix this in the next binary release later today.

**Comment by angelleng** [comment]
Cool thanks!

**Comment by soumith** [comment]
@angelleng i couldn't get this fixed in this release, will do in the next one. 
For now you have three options:
- install binaries via anaconda
- install from source
- install from docker

https://github.com/pytorch/pytorch#installation

Either will fix this.

**Comment by angelleng** [comment]
gotchu

**Comment by mrdrozdov** [comment]
Running into the same problem. @soumith did this ever get fixed?

**Comment by ml9951** [comment]
Also having this same problem.

**Comment by soumith** [comment]
we are closer to getting this fixed, but it's not fixed yet. I'm starting to do manylinux wheels, which will have this fixed.

**Comment by jdxyw** [comment]
Hellp, still has this problem, does it fix in 0.1.11-post5 version?

**Comment by Huarong** [comment]
still there in 0.1.12

**Comment by deartonym** [comment]
not solved, yet.

**Comment by chichivica** [comment]
build from source code with anaconda environment, python3, AMD vision, encountered same problem `undefined symbol: _ZN4thpp8THTensorIcEC1EP13THLongStorageS3_`

**Comment by soumith** [comment]
there are new commands at http://pytorch.org/ for python 2.7 wheels that give links to both UCS2 and UCS4 wheels.
