### ISSUE TITLE
Hermitian symmetric Fast Fourier Transform

### ISSUE THREAD

**Issue by eduardo4jesus** [pytorch/pytorch#59127]
## 🚀 Feature
I would be very helpful if we had an implementation of the HFFTN like we have for the [RFFTN](https://pytorch.org/docs/stable/fft.html#torch.fft.rfftn)

## Motivation

Currently, the [HFFT](https://pytorch.org/docs/stable/fft.html#torch.fft.hfft) only supports a single dimension.

## Pitch

Just like the `torch.fft.rfft`, It is desirable to have the following

- [x] ~`torch.fft.hfft`~ `Already present`
- [x] ~`torch.fft.ihfft`~ `Already present`
- [ ] `torch.fft.hfft2`
- [ ] `torch.fft.ihfft2`
- [ ] `torch.fft.hfftn`
- [ ] `torch.fft.ihfftn`

## Alternatives

I am currently checking [`Aten/native`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SpectralOps.cpp) so see if it is possible to have a `custom C++ extension` for it. But a nice python wrapper as for the `torch.fft.rfft` would be very very helpful.

cc @mruberry @peterbell10 @walterddr

**Comment by mruberry** [comment]
What do you think, @peterbell10?

**Comment by peterbell10** [comment]
This should be reasonably straight-forward. Although I wouldn't expect it to perform any better than `fftn` followed by `hfft`.

**Comment by eduardo4jesus** [comment]
@peterbell10, thanks for pointing that out.

Quick question about RFFT given the topic. Would there be a way to retrieve the Complex part of the output of the iRFFT?

**Comment by peterbell10** [comment]
The point of IRFFT is that the output is real-valued by construction, so there is no imaginary component.
