### ISSUE TITLE
Typo in current Doc pages

### ISSUE THREAD

**Issue by 0oshowero0** [pytorch/pytorch#59139]
## 📚 Documentation

In this page about reproducibility, [https://pytorch.org/docs/stable/notes/randomness.html](url)
I found an error in the second code block:
`inport random
random.seed(0)`
should be
`import random
random.seed(0)`

cc @brianjo @mruberry

**Comment by ngimel** [comment]
Thanks for reporting, we'll accept PR fixing this.

**Comment by bdhirsh** [comment]
reserving for onboarding

**Comment by msaroufim** [comment]
Looks like this was fixed

![Screen Shot 2021-08-12 at 5 20 01 PM](https://user-images.githubusercontent.com/3282513/129285965-136d9852-3f4c-40fa-b62e-677a6f738f80.png)
