### ISSUE TITLE
Creating optimizer before wrapping model in `DistributedDataParallel`

### ISSUE THREAD

**Issue by KickItLikeShika** [pytorch/pytorch#59147]
I'm wondering if this will work fine
```py
model = Net()
optimizer = Adam(model.parameters(), lr=0.01)
model = DistributedDataParallel(...)
# then continue training normally
```
We are trying to build a High-Level API for training PyTorch NNs, and we want to support DDP.
so the question is: Is the code above will work fine? or do we have to create the optimizer after wrapping the model in `DistributedDataParallel`?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by H-Huang** [comment]
The code above will work. Either order is fine.
