### ISSUE TITLE
optimizer.load_state_dict( )  UserWarning: optimizer contains a parameter group with duplicate parameters

### ISSUE THREAD

**Issue by Sixy1204** [pytorch/pytorch#59142]
hello,
When I load optimizer state from checkpoint dict to retrain model, it throws  UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error.
I save states as this:
<img width="406" alt="捕获" src="https://user-images.githubusercontent.com/36162926/119951424-84603d80-bfce-11eb-8275-d6ba54023392.PNG">
And load states like this:
<img width="516" alt="捕获1" src="https://user-images.githubusercontent.com/36162926/119951639-bd98ad80-bfce-11eb-9e9d-ad1666668c65.PNG">
<img width="551" alt="捕获" src="https://user-images.githubusercontent.com/36162926/119951673-c7221580-bfce-11eb-90db-336ee0c501ba.PNG">
It goes wrong when running the code and literally stop running progress.

Can anyone help me

**Comment by Radiantsunshine** [comment]
Hello, I also encountered this problem, how did you finally solve it?
Thank you!
