### ISSUE TITLE
nn.TransformerEncoderLayer mismatch on batch size dimension?

### ISSUE THREAD

**Issue by ed-winning** [pytorch/pytorch#59159]
## 🐛 Bug

In the forward function of nn.TransformerEncoderLayer, the input goes through MultiheadAttention, followed by Dropout, then LayerNorm. According to the documentation, the input-output shape of MultiheadAttention is (S, N, E) -> (T, N, E) where S is the source sequence length, L is the target sequence length, N is the batch size, E is the embedding dimension. The input-output shape of LayerNorm is (N, *) -> (N, *). Wouldn't this cause a problem because the batch size of the MultiheadAttention output is the second dimension, while LayerNorm expects the batch size to be in the first dimension? Or am I missing something? Thanks!

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org
