### ISSUE TITLE
Running some CI tests with `xlarge` `resource_class` VMs for testing AVX512 support

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#59166]
## 🚀 Feature

Currently, the Linux CI checks that are tests are run on `large` `resource_class` executors, which are run on machines that don't support AVX512. To test ATen AVX512 kernels, `xlarge` executors would be required, as these VMs are run on Intel Cascade Lake machines that support AVX512.

## Pitch

Some CI checks should be run on `xlarge` instances, which have AVX512 support. The number of CI tests running on `xlarge` instances can probably be limited in order to not vastly increase CI costs.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @ngimel @VitalyFedyunin

**Comment by ezyang** [comment]
cc @seemethere but my guess is this is not worth resolving until GitHub Actions migrations is complete.
