### ISSUE TITLE
In nightly, JIT Exceptions raised while scripting can't be properly caught by python, but they could be in stable 

### ISSUE THREAD

**Issue by IgnacioJPickering** [pytorch/pytorch#59169]
## 🐛 Bug

When raising an exception inside an `if torch.jit.is_scripting():` branch, the exception is raised but the program aborts without properly passing the exception to python, which means the exception can't be caught. In stable this works correctly.

## To Reproduce

Run the folllowing script:
```
 import torch                                                                                                                                                                           
  class Jittable(torch.nn.Module):                                                                                                                                                       
      def forward(self, x):                                                                                                                                                              
          if torch.jit.is_scripting():                                                                                                                                                   
              raise RuntimeError("Terminating from python")                                                                                                                              
          return x                                                                                                                                                                       
  m = torch.jit.script(Jittable())                                                                                                                                                       
  try:                                                                                                                                                                                   
      m(torch.empty(1))                                                                                                                                                                  
  except Exception:                                                                                                                                                                      
      pass   
```
This produces no output in stable, but in nightly you get the message:
```
terminate called after throwing an instance of 'torch::jit::JITException'
  what():  Terminating from python
```
## Expected behavior

This should produce no output, and the exception should be properly caught.

## Environment

Collecting environment information...
PyTorch version: 1.9.0.dev20210528+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7 (64-bit runtime)
Python platform: Linux-4.15.0-136-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 455.23.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.4
[pip] pytorch-ignite-nightly==20190514
[pip] torch==1.9.0.dev20210528+cu111
[pip] torch-nightly==1.1.0.dev20190514
[pip] torchaudio==0.9.0.dev20210510
[pip] torchvision==0.10.0.dev20210510
[conda] numpy                     1.19.4                   pypi_0    pypi
[conda] pytorch-ignite-nightly    20190514                 pypi_0    pypi
[conda] torch                     1.9.0.dev20210528+cu111          pypi_0    pypi
[conda] torch-nightly             1.1.0.dev20190514          pypi_0    pypi
[conda] torchani                  2.3.dev150+g995fc1c.d20210511           dev_0    <develop>
[conda] torchaudio                0.9.0.dev20210510          pypi_0    pypi
[conda] torchvision               0.10.0.dev20210510          pypi_0    pypi

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Sorry I can't repro with a build from source at HEAD. Could you try again (maybe with even newer nightly) to check if issue persists?

**Comment by IgnacioJPickering** [comment]
@gmagogsfm I checked and the issue persists for me, I also reproduced with a different system, here is the corresponding environment: 
```
Collecting environment information...
PyTorch version: 1.9.0.dev20210531+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.7 (Maipo) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8 (64-bit runtime)
Python platform: Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0.dev20210531+cu102
[pip3] torchaudio==0.9.0.dev20210531
[pip3] torchvision==0.11.0.dev20210531
[conda] numpy                     1.19.2                   pypi_0    pypi
[conda] torch                     1.9.0.dev20210531+cu102          pypi_0    pypi
[conda] torchaudio                0.9.0.dev20210531          pypi_0    pypi
[conda] torchvision               0.11.0.dev20210531          pypi_0    pypi
```

**Comment by IgnacioJPickering** [comment]
(this is `1.9.0.dev20210531` nightly, I'm not sure how far from HEAD this is)

**Comment by IgnacioJPickering** [comment]
In the current nightly this is working properly for me again.
