### ISSUE TITLE
type object 'Embedding' has no attribute 'from_pretrained'

### ISSUE THREAD

**Issue by yuhui-zh15** [pytorch/pytorch#5917]
- OS: Ubuntu 14.04 LTS
- PyTorch version: 0.4.0
- How you installed PyTorch (conda, pip, source): pip
- Python version: 2.7.6
- CUDA/cuDNN version: 8
- GPU models and configuration: Tesla K20
- GCC version (if compiling from source): 4.8.4

**Comment by yuhui-zh15** [comment]
emb.weight.data[i] = xxx works. Please fix the documentation ...

**Comment by fmassa** [comment]
The documentation is right, but you are checking the documentation from master, while your version should be older than that.
Also check https://github.com/pytorch/pytorch/pull/5350 and https://github.com/pytorch/pytorch/issues/5833
