### ISSUE TITLE
Can't Install torch 0.4.0 in Colab

### ISSUE THREAD

**Issue by Nitasophia** [pytorch/pytorch#59192]
When I install torch 0.4.0 in colab to use allennlp 0.5.0 i got this error.

`ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from allennlp) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==0.4.0`

Can anyone know to solve this problem?

cc @ezyang @seemethere @malfet @walterddr

**Comment by ngimel** [comment]
Have you tried commands listed here https://pytorch.org/get-started/previous-versions/#commands-for-versions--100-1?

**Comment by Nitasophia** [comment]
> 
> 
> Have you tried commands listed here https://pytorch.org/get-started/previous-versions/#commands-for-versions--100-1?

i switch to torch 0.4.1.post2. thanks
