### ISSUE TITLE
I got the error "couldn't find "libpytorch_jni.so"" when using pytorch Android

### ISSUE THREAD

**Issue by Hydralisk2333** [pytorch/pytorch#59190]
## Issue description

I successfully configured an application with pytorch Android a week ago, and then I found this error when I reinstalled the application today. I haven't changed any code, but it doesn't work normally. What is the problem?

## System Info

- PyTorch
- OS: Android
- PyTorch version:  org.pytorch:pytorch_android:1.9.0-SNAPSHOT
- Python version: 3.8

**Comment by cccclai** [comment]
Looks like you are using a nightly build. We are transitioning to use lite interpreter for Android, targeting smaller library size. Currently the new nightly build is using lite interpreter. The new library name is `libpytorch_jni_lite.so`. Can you try the following solution? 

To use lite interpreter, the model can be generated following the example:
```
import torch

model = torch.hub.load('pytorch/vision:v0.7.0', 'deeplabv3_resnet50', pretrained=True)
model.eval()

scripted_module = torch.jit.script(model)
# Export full jit version model (not compatible lite interpreter), leave it here for comparison
scripted_module.save("deeplabv3_scripted.pt")
# Export lite interpreter version model (compatible with lite interpreter)
scripted_module._save_for_lite_interpreter("deeplabv3_scripted.ptl")
```

To load the model:
```
import org.pytorch.LiteModuleLoader
...
mModule = LiteModuleLoader.load(MainActivity.assetFilePath(getApplicationContext(), "deeplabv3_scripted.ptl"));
...
```

This tutorial will be updated soon, but it can still be used as a reference now: https://pytorch.org/tutorials/prototype/lite_interpreter.html

If you prefer a more stable version (previous interpreter, `libpytorch_jni.so`), try the following version:
```
implementation 'org.pytorch:pytorch_android_torchvision:1.8.0'
```

**Comment by Hydralisk2333** [comment]
Thank you for your answer, the problem has been solved.

**Comment by Edward-YS** [comment]
> Thank you for your answer, the problem has been solved.

how do you solve at last?
