### ISSUE TITLE
Requesting implementation of transpose for sparse tensors

### ISSUE THREAD

**Issue by NeelMishra** [pytorch/pytorch#59197]
## 🚀 Feature

A functionality that can allow users to easily get a transpose of a sparse tensor eg, we can use .T method to get transpose of a matrix, but we cannot use the same for sparse tensors.

## Motivation
There are lot of missing functionality for sparse tensors, these tensors has an immense application in research development. Lot of command functionalities are missing like .squeeze(), and .T etc. This can help lot of researchers to develop sparse methods.

cc @aocsa @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by Lezcano** [comment]
`.mT` and `.mH`were added in https://github.com/pytorch/pytorch/pull/64179/ as shortcuts to transpose (and conj-transpose) tensors.

Note that `.T` works just as expected on matrices, but it has an odd behaviour (reverses the dimension sizes) on general tensors. As such, you should almost alway use `mT` and `mH` (matrix Transpose / conj Transpose).

Closing for now.

**Comment by Lezcano** [comment]
Note that https://github.com/pytorch/pytorch/issues/61059 tracks the progress `transpose` for CSR tensors.
