### ISSUE TITLE
Dead loop when use hook

### ISSUE THREAD

**Issue by wchen61** [pytorch/pytorch#59203]
## 🐛 Bug

There is a dead loop when use hook for some networks, for example, detectron.

## To Reproduce

1. register global hook
2. run the network
3. dead loop when backward hook

def global_forward_pre_hook(m, input):
    print("global forward pre hook", m._get_name())

def global_forward_hook(m, input, output):
    print("global forward hook", m._get_name())

def global_backward_hook(m, input, output):
    print("global backward hook", m._get_name())

 if __name__ == "__main__":
     args = default_argument_parser().parse_args()
     print("Command Line Args:", args)
    torch.nn.modules.module.register_module_forward_pre_hook(global_forward_pre_hook)
    torch.nn.modules.module.register_module_forward_hook(global_forward_hook)
    torch.nn.modules.module.register_module_full_backward_hook(global_backward_hook)

This is because, the input tensor will repeat it self in detectron
https://github.com/facebookresearch/detectron2/blob/master/detectron2/structures/boxes.py

## Expected behavior

Hook works properly

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment]
Hi,

I am a bit confused because this repro use the full backward hooks but the PR fixes some code in the old non-full backward hooks. Could you clarify that?

**Comment by wchen61** [comment]
> Hi,
> 
> I am a bit confused because this repro use the full backward hooks but the PR fixes some code in the old non-full backward hooks. Could you clarify that?

Yes.  I found this issue when use PyTorch 1.7, and this patch only fix the old hooks.
I will check if the latest full backward hooks works.
