### ISSUE TITLE
ReduceOps are breaking Pyro test

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#5921]
According to @fritzo here: https://github.com/pytorch/pytorch/pull/5776#issuecomment-374836063

> Hi all, we're seeing some Pyro [breakage](https://github.com/uber/pyro/issues/912) at this PR. Could anyone familiar with this PR help us out by suggesting what behaviors may have changed?

The failing tests in Pyro make heavy use of broadcasting and `.sum()` and `.sum(axis, keepdim=True)` with tensors of `.dim()` between 5-20. Glancing at this PR's diff my first guess is that some reduction code may have changed behavior. Note that the failures are often off by an order of magnitude, not merely LSB errors. I have been seeing the errors locally when building on OS X.

cc: @cpuhrsch

**Comment by cpuhrsch** [comment]
I found the bug, I'll send a patch soon.

**Comment by ezyang** [comment]
I merged Christian's fix, let us know if it's still broken.
