### ISSUE TITLE
ValueError: The value argument must be within the support

### ISSUE THREAD

**Issue by mmaaz60** [pytorch/pytorch#59228]
While calling `log_prob()`, I am getting the 'ValueError: The value argument must be within the support'.

PyTorch Version: 1.9.0.dev20210530

To reproduce, run

```
import numpy as np
import torch
import torch.distributions as distrib
import torch.distributions.transforms as transforms

x = np.linspace(-4, 4, 1000)
z = np.array(np.meshgrid(x, x)).transpose(1, 2, 0)
z = np.reshape(z, [z.shape[0] * z.shape[1], -1])

# Initial distribution
q0 = distrib.MultivariateNormal(torch.zeros(2), torch.eye(2))
# Defining Affine Transformation
f1 = transforms.ExpTransform()
# Transforming
q1 = distrib.TransformedDistribution(q0, f1)

q1.log_prob(torch.Tensor(z))
```

Any workaround would be appreciated. Thanks

cc @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by fritzo** [comment]
Hi @mmaax60, it looks like your distribution `q1` is a lognormal distribution with support the positive reals, whereas your `z` contains negative numbers.  Thus the `ValueError` is expected.  Did you mean to exponentiate your `z` before passing to `q1.log_prob(-)`?

**Comment by mmaaz60** [comment]
> Hi @mmaax60, it looks like your distribution `q1` is a lognormal distribution with support the positive reals, whereas your `z` contains negative numbers. Thus the `ValueError` is expected. Did you mean to exponentiate your `z` before passing to `q1.log_prob(-)`?

Hi @fritzo, thank you for pointing that out. In my application, I, in fact, need to take exponential after passing to `log_prob()` (e.g. `q1.log_prob(torch.Tensor(z)).exp()`). I was previously using PyTorch 1.7.0 and it was working fine. Moving to the latest PyTorch version gives this error.

It looks like the expected behaviour of `.log_prob()` changes in the latest release. Previously it was returning `None` for all negative inputs and now it's raising the error. I will update my codebase accordingly.

Thank you

**Comment by fritzo** [comment]
Hi @mmaaz60, the change in behavior from PyTorch 1.7 to 1.8 was that we turned on argument validation by default. You want to disable validation for a single distribution by passing `validate_args=False` to the constructor.
```py
q0 = distrib.MultivariateNormal(torch.zeros(2), torch.eye(2), validate_args=False)
q1 = distrib.TransformedDistribution(q0, f1, validate_args=False)
```
However distributions are not intended to handle values outside of their support, so I would recommend handling the invalid negative z's outside of your log normal distribution rather than relying on internal NAN behavior (which is subject to change).
