### ISSUE TITLE
Package pytorch conflicts when installing with conda

### ISSUE THREAD

**Issue by raphael10-collab** [pytorch/pytorch#59222]
I'm trying to install PyTorch through conda but I'm getting "conflict" errors:

  I first activated the conda virtualenvironment:

    (base) raphy@pc:~$ source activate pytorch_env

  Then, tried to install the packages:

    (pytorch_env) raphy@pc:~$ conda install -n pytorch_env pytorch torchvision torchaudio cpuonly -c pytorch
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: / 
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed                                                                                                                                                                                       
    
    UnsatisfiableError: The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    Package pytorch conflicts for:
    torchvision -> pytorch[version='1.1.*|1.2.0+cu92|1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0|>=1.0.0|>=0.4|>=0.3|1.7.1.*|1.3.1.*|1.2.0.*']
    torchaudio -> pytorch[version='1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0']
    pytorch
    
    Package six conflicts for:
    pytorch -> mkl-service[version='>=2,<3.0a0'] -> six
    torchvision -> six
    
    Package _libgcc_mutex conflicts for:
    torchvision -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
    pytorch -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
    python=3.9 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
    
    (pytorch_env) raphy@pc:~$ 

If I install it with pip3 it seems working fine:

    (pytorch_env) raphy@pc:~$ pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
    Looking in links: https://download.pytorch.org/whl/torch_stable.html
    Collecting torch==1.8.1+cpu
      Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp39-cp39-linux_x86_64.whl (169.1 MB)
         |████████████████████████████████| 169.1 MB 126 kB/s 
    Collecting torchvision==0.9.1+cpu
      Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp39-cp39-linux_x86_64.whl (13.3 MB)
         |████████████████████████████████| 13.3 MB 37.6 MB/s 
    Collecting torchaudio==0.8.1
      Downloading torchaudio-0.8.1-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
         |████████████████████████████████| 1.9 MB 14.3 MB/s 
    Requirement already satisfied: numpy in ./anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from torch==1.8.1+cpu) (1.20.1)
    Requirement already satisfied: typing-extensions in ./anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from torch==1.8.1+cpu) (3.7.4.3)
    Requirement already satisfied: pillow>=4.1.1 in ./anaconda3/envs/pytorch_env/lib/python3.9/site-packages (from torchvision==0.9.1+cpu) (8.2.0)
    Installing collected packages: torch, torchvision, torchaudio
      Attempting uninstall: torch
        Found existing installation: torch 1.8.1
        Uninstalling torch-1.8.1:
          Successfully uninstalled torch-1.8.1
    Successfully installed torch-1.8.1+cpu torchaudio-0.8.1 torchvision-0.9.1+cpu
    (pytorch_env) raphy@pc:~$ cd pythonMatters/
    (pytorch_env) raphy@pc:~/pythonMatters$ ls -lah
    total 12K
    drwxrwxr-x  2 raphy raphy 4,0K mag 31 16:54 .
    drwxr-xr-x 39 raphy raphy 4,0K mag 31 17:22 ..
    -rw-rw-r--  1 raphy raphy   44 mag 31 16:54 pytorch_verification.py
    (pytorch_env) raphy@pc:~/pythonMatters$ nano pytorch_verification.py 
    (pytorch_env) raphy@pc:~/pythonMatters$ python3 pytorch_verification.py 
    tensor([[0.3230, 0.9078, 0.4617],
            [0.8623, 0.9219, 0.2986],
            [0.1736, 0.4657, 0.5214],
            [0.8163, 0.1591, 0.7434],
            [0.1205, 0.6854, 0.3539]])
    (pytorch_env) raphy@pc:~/pythonMatters$ 

OS: Ubuntu 20.04 Desktop
python: Python 3.9.4
PyTorch Build: 1.8.1
conda 4.10.1

cc @ezyang @seemethere @malfet @walterddr

**Comment by sercharpak** [comment]
I can confirm I got a very similar thing with:

OS: Windows 10
Python: 3.9.5
Pytorch: 1.8.1+cu102
Conda: 4.10.1

`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for python torchvision:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 6/8 [00:03<00:00,  2.09it/s]/failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchaudio -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
  - torchvision -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
torchvision -> libpng -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.9 -> sqlite[version='>=3.33.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package vc conflicts for:
pytorch -> ninja -> vc[version='14.*|9.*']
torchvision -> jpeg[version='<=9b'] -> vc[version='14.*|9.*']
torchaudio -> numpy[version='>=1.11'] -> vc[version='14.*|9.*']
cudatoolkit=10.2 -> vc[version='>=14.1,<15.0a0']
pytorch -> vc[version='>=14.1,<15.0a0']
torchvision -> vc[version='>=14.1,<15.0a0']
python=3.9 -> vc[version='>=14.1,<15.0a0']
torchaudio -> vc[version='>=14.1,<15.0a0']

Package cudatoolkit conflicts for:
torchvision -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=10.2,<10.3|>=11.1,<11.2|>=11.0,<11.1|>=9.2,<9.3|>=9.0,<9.1']
torchvision -> pytorch[version='>=1.0.0'] -> cudatoolkit[version='>=8.0,<8.1']
torchaudio -> pytorch==1.8.1 -> cudatoolkit[version='>=10.1,<10.2|>=11.1,<11.2|>=10.2,<10.3|>=11.0,<11.1']
pytorch -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=11.1,<11.2|>=10.2,<10.3|>=11.0,<11.1|>=9.2,<9.3|>=9.0,<9.1|>=8.0,<8.1']

Package six conflicts for:
torchvision -> six
pytorch -> mkl-service[version='>=2,<3.0a0'] -> six

Package pytorch conflicts for:
torchaudio -> pytorch[version='1.6.0|1.7.0|1.7.1|1.8.0|1.8.1']
torchvision -> pytorch[version='1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0|>=1.0.0|>=0.4']

Package vs2015_runtime conflicts for:
cudatoolkit=10.2 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
cudatoolkit=10.2 -> vc[version='>=14.1,<15.0a0'] -> vs2015_runtime[version='>=14.15.26706|>=14.27.29016|>=14.16.27012']`

**Comment by rgommers** [comment]
These two issues look like they're not exactly the same. @sercharpak and @raphael10-collab, can you both confirm:
- that you're running this in empty (freshly created) conda envs?
- what you `~/.condarc` looks like
- if the problem goes away if you drop `torchvision` and/or `torchaudio` from the install command

**Comment by rgommers** [comment]
I tried the first issue, on Arch Linux (shouldn't work differently from Ubuntu):
```
conda create -n issue59222
conda activate issue59222
conda install pytorch torchvision torchaudio cpuonly -c pytorch
```
This works just fine for me. Solver result with `defaults` as the first channel in `.condarc`:

<details>

```
$ conda install pytorch torchvision torchaudio cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/rgommers/anaconda3/envs/issue59222

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    ca-certificates-2021.5.25  |       h06a4308_1         112 KB
    certifi-2021.5.30          |   py39h06a4308_0         139 KB
    cpuonly-1.0                |                0           2 KB  pytorch
    ffmpeg-4.3                 |       hf484d3e_0         9.9 MB  pytorch
    gmp-6.2.1                  |       h2531618_2         539 KB
    gnutls-3.6.15              |       he1e5248_0         1.0 MB
    lame-3.100                 |       h7b6447c_0         323 KB
    libiconv-1.15              |       h63c8f33_5         721 KB
    libidn2-2.3.1              |       h27cfd23_0          85 KB
    libtasn1-4.16.0            |       h27cfd23_0          58 KB
    libunistring-0.9.10        |       h27cfd23_0         536 KB
    libwebp-base-1.2.0         |       h27cfd23_0         437 KB
    mkl-service-2.3.0          |   py39h27cfd23_1          57 KB
    mkl_random-1.2.1           |   py39ha9443f7_2         310 KB
    nettle-3.7.2               |       hbbd107a_1         811 KB
    ninja-1.10.2               |       hff7bd54_1         1.4 MB
    openh264-2.1.0             |       hd408876_0         722 KB
    openssl-1.1.1k             |       h27cfd23_0         2.5 MB
    pip-21.1.1                 |   py39h06a4308_0         1.8 MB
    python-3.9.5               |       hdb3f193_3        18.1 MB
    pytorch-1.8.1              |      py3.9_cpu_0        66.0 MB  pytorch
    setuptools-52.0.0          |   py39h06a4308_0         724 KB
    six-1.15.0                 |   py39h06a4308_0          27 KB
    sqlite-3.35.4              |       hdfb4753_0         981 KB
    torchaudio-0.8.1           |             py39         4.4 MB  pytorch
    torchvision-0.9.1          |         py39_cpu         6.8 MB  pytorch
    tzdata-2020f               |       h52ac0ba_0         113 KB
    zstd-1.4.9                 |       haebb681_0         480 KB
    ------------------------------------------------------------
                                           Total:       119.0 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.5.25-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py39h06a4308_0
  cpuonly            pytorch/noarch::cpuonly-1.0-0
  ffmpeg             pytorch/linux-64::ffmpeg-4.3-hf484d3e_0
  freetype           pkgs/main/linux-64::freetype-2.10.4-h5ab3b9f_0
  gmp                pkgs/main/linux-64::gmp-6.2.1-h2531618_2
  gnutls             pkgs/main/linux-64::gnutls-3.6.15-he1e5248_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.2.0-h06a4308_610
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  lame               pkgs/main/linux-64::lame-3.100-h7b6447c_0
  lcms2              pkgs/main/linux-64::lcms2-2.12-h3be6417_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libiconv           pkgs/main/linux-64::libiconv-1.15-h63c8f33_5
  libidn2            pkgs/main/linux-64::libidn2-2.3.1-h27cfd23_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libtasn1           pkgs/main/linux-64::libtasn1-4.16.0-h27cfd23_0
  libtiff            pkgs/main/linux-64::libtiff-4.2.0-h85742a9_0
  libunistring       pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0
  libuv              pkgs/main/linux-64::libuv-1.40.0-h7b6447c_0
  libwebp-base       pkgs/main/linux-64::libwebp-base-1.2.0-h27cfd23_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.3-h2531618_0
  mkl                pkgs/main/linux-64::mkl-2021.2.0-h06a4308_296
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py39h27cfd23_1
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.0-py39h42c9631_2
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.1-py39ha9443f7_2
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  nettle             pkgs/main/linux-64::nettle-3.7.2-hbbd107a_1
  ninja              pkgs/main/linux-64::ninja-1.10.2-hff7bd54_1
  numpy              pkgs/main/linux-64::numpy-1.20.2-py39h2d18471_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.20.2-py39hfae3a4d_0
  olefile            pkgs/main/noarch::olefile-0.46-py_0
  openh264           pkgs/main/linux-64::openh264-2.1.0-hd408876_0
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pillow             pkgs/main/linux-64::pillow-8.2.0-py39he98fc37_0
  pip                pkgs/main/linux-64::pip-21.1.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.5-hdb3f193_3
  python_abi         conda-forge/linux-64::python_abi-3.9-1_cp39
  pytorch            pytorch/linux-64::pytorch-1.8.1-py3.9_cpu_0
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py39h06a4308_0
  six                pkgs/main/linux-64::six-1.15.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.35.4-hdfb4753_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  torchaudio         pytorch/linux-64::torchaudio-0.8.1-py39
  torchvision        pytorch/linux-64::torchvision-0.9.1-py39_cpu
  typing_extensions  pkgs/main/noarch::typing_extensions-3.7.4.3-pyha847dfd_0
  tzdata             pkgs/main/noarch::tzdata-2020f-h52ac0ba_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
  zstd               pkgs/main/linux-64::zstd-1.4.9-haebb681_0


Proceed ([y]/n)?
```

</details>


And output if I put `conda-forge` as the first channel:

<details>

```
$ conda install pytorch torchvision torchaudio cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/rgommers/anaconda3/envs/issue59222

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-1.0                |                0           2 KB  pytorch
    jbig-2.1                   |    h7f98852_2003          43 KB  conda-forge
    lerc-2.2.1                 |       h9c3ff4c_0         213 KB  conda-forge
    libdeflate-1.7             |       h7f98852_5          67 KB  conda-forge
    libtiff-4.3.0              |       hf544144_1         668 KB  conda-forge
    numpy-1.20.3               |   py38h9894fe3_1         5.8 MB  conda-forge
    pytorch-1.7.0              |      py3.8_cpu_0        59.5 MB  pytorch
    torchaudio-0.7.0           |             py38         9.9 MB  pytorch
    torchvision-0.8.1          |         py38_cpu        17.2 MB  pytorch
    typing_extensions-3.10.0.0 |     pyha770c72_0          28 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        93.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  blas               conda-forge/linux-64::blas-2.109-mkl
  blas-devel         conda-forge/linux-64::blas-devel-3.9.0-9_mkl
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.5.30-ha878542_0
  certifi            conda-forge/linux-64::certifi-2021.5.30-py38h578d9bd_0
  cpuonly            pytorch/noarch::cpuonly-1.0-0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  jbig               conda-forge/linux-64::jbig-2.1-h7f98852_2003
  jpeg               conda-forge/linux-64::jpeg-9d-h36c2ea0_0
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  lerc               conda-forge/linux-64::lerc-2.2.1-h9c3ff4c_0
  libblas            conda-forge/linux-64::libblas-3.9.0-9_mkl
  libcblas           conda-forge/linux-64::libcblas-3.9.0-9_mkl
  libdeflate         conda-forge/linux-64::libdeflate-1.7-h7f98852_5
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_19
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-hff62375_19
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-hff62375_19
  liblapack          conda-forge/linux-64::liblapack-3.9.0-9_mkl
  liblapacke         conda-forge/linux-64::liblapacke-3.9.0-9_mkl
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_19
  libtiff            conda-forge/linux-64::libtiff-4.3.0-hf544144_1
  libuv              conda-forge/linux-64::libuv-1.41.0-h7f98852_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.0-h7f98852_2
  llvm-openmp        conda-forge/linux-64::llvm-openmp-11.1.0-h4bd325d_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_0
  mkl                conda-forge/linux-64::mkl-2021.2.0-h726a3e6_389
  mkl-devel          conda-forge/linux-64::mkl-devel-2021.2.0-ha770c72_390
  mkl-include        conda-forge/linux-64::mkl-include-2021.2.0-h726a3e6_389
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  ninja              conda-forge/linux-64::ninja-1.10.2-h4bd325d_0
  numpy              conda-forge/linux-64::numpy-1.20.3-py38h9894fe3_1
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjpeg           conda-forge/linux-64::openjpeg-2.4.0-hb52868f_1
  openssl            conda-forge/linux-64::openssl-1.1.1k-h7f98852_0
  pillow             conda-forge/linux-64::pillow-8.2.0-py38ha0e1e83_1
  pip                conda-forge/noarch::pip-21.1.2-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.8.10-h49503c6_1_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytorch            pytorch/linux-64::pytorch-1.7.0-py3.8_cpu_0
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h578d9bd_3
  sqlite             conda-forge/linux-64::sqlite-3.35.5-h74cdb3f_0
  tbb                conda-forge/linux-64::tbb-2021.2.0-h4bd325d_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  torchaudio         pytorch/linux-64::torchaudio-0.7.0-py38
  torchvision        pytorch/linux-64::torchvision-0.8.1-py38_cpu
  typing_extensions  conda-forge/noarch::typing_extensions-3.10.0.0-pyha770c72_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010
  zstd               conda-forge/linux-64::zstd-1.5.0-ha95c52a_0


Proceed ([y]/n)?
```

</details>


Note that it is important to use a fresh conda env if you get a solver issue. Installing into an existing env with another set of packages in it can fail much more easily to yield a valid solver solution, and is in general not recommended.

I can't try the second issue because I don't have a Windows machine at hand.

**Comment by raphael10-collab** [comment]
I created a fresh conda virtual env just for pytorch:
    
    base) raphy@pc:~$ conda info --envs
    # conda environments:
    #
    base                  *  /home/raphy/anaconda3
    pytorch_env              /home/raphy/anaconda3/envs/pytorch_env
    
    (base) raphy@pc:~$ 

Strangely I do not have any ~/.condarc

I remember I had the same problem without installing torchvision and torchaudio

**Comment by rgommers** [comment]
Thanks for confirming @raphael10-collab. 

The weird thing is that there's no actual conflict in the reported conflicts:
```
Package pytorch conflicts for:
torchvision -> pytorch[version='1.1.*|1.2.0+cu92|1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0|>=1.0.0|>=0.4|>=0.3|1.7.1.*|1.3.1.*|1.2.0.*']
torchaudio -> pytorch[version='1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0']
pytorch

Package six conflicts for:
pytorch -> mkl-service[version='>=2,<3.0a0'] -> six
torchvision -> six

Package _libgcc_mutex conflicts for:
torchvision -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
pytorch -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python=3.9 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
```

This is all perfectly satisfiable. E.g., 2x `-> six` can never be a conflict.

@ilanschnell do you have any insights into what's going on here? Are the reported conflicts known to sometimes be incorrect? Any other suggestions to debug?

**Comment by ilanschnell** [comment]
I was able to run `conda install pytorch torchvision torchaudio cpuonly -c pytorch` in an empty environment.  Unlike what @rgommers is seeing, it created a Python 3.8 installation of the packages for me (using conda 4.10.1 on Linux).  Adding `python=3.9` to the above command also works fine for me.  My condarc file is:
```
channels:
  - conda-forge

channel_priority: strict
```
I found that conda's conflict reporting is often misleading, as "non-conflicts" get reported.  The way I usually find the root cause of a conflict is by successively reducing the packages to be installed.  I can't do this here, as I'm not seeing a conflict on my machine.  @raphael10-collab did you having any packages installed in the environment on which you ran the initial command?  Could it be that the problem has been resolved itself within the last two weels (because of newer upstream packages)?

**Comment by brando90** [comment]
I am also having this issue and I am unsure what to do. Any suggestions?

original post: https://stackoverflow.com/questions/68010933/unable-to-install-pytorch-on-mac-os-x-from-scratch-due-to-pytorch-package-confli

**Comment by rgommers** [comment]
@brando90 thanks for your input. Can you please add:

- whether or not you ran this in an empty environment?
- the output of `conda info` (in the environment where your install is failing)
- the output of running `conda install pytorch torchvision torchaudio -c pytorch`


> Why isn't that flag what the official installation on the website asks? It seems really odd that the official install would not work:

The conda `defaults` and `conda-forge` channels are not fully compatible, and it's better not to mix them. Until now, the `pytorch` channel has been compatible with `defaults`.

**Comment by edwardcodes** [comment]
> Adding the conda-forge channel worked.
> 
> ```
> conda install pytorch torchvision torchaudio -c pytorch -c conda-forge
> ```
> 
> Why isn't that flag what the official installation on the website asks? It seems really odd that the official install would not work:
> 
> ```
> conda install pytorch torchvision torchaudio -c pytorch
> ```
> 
> is there a reason why the conda-forge channel is not added to the official instructions?
> 
> solved here:
> 
> #59517

This actually worked for here. Thank you for the solution.

**Comment by Zwd798** [comment]
Can you just try using `pip install torch` ? Seems to work for me

**Comment by seemethere** [comment]
Hey everyone! Looks like this particular issue is a bit stale in terms of information. Going to close, feel free to re-open if feel as though your issue hasn't been resolved!

**Comment by A1exan10er** [comment]
I know this is already an old question. I still hope to provide my way to solve this problem since I met it today after I created a new virtual environment.

First, uninstall Python, because for me the incompatibility may be due to the latest Python version. 
Then, install a previous version of Python, for me it's 3.10.
After that, update Conda to its latest version (because mine was not the latest).
In the end, run the installation command of PyTorch with conda and the corresponding CUDA version (in my case 12.4) from the installation page.

Voilà, problem solved. 
Cheers! :100:
