### ISSUE TITLE
How can we solve the GIL problem in training reinforcement learning model?

### ISSUE THREAD

**Issue by guoyaohua** [pytorch/pytorch#59239]
How can we solve the GIL problem in training reinforcement learning model to make the CPU AND GPU reach full load?

multi-thread : Can not make cpu full load.
multi-processor: It's difficult to directly call model functions in other processes.

Using Jython or is there some other better way?

Thanks!

**Comment by guoyaohua** [comment]
Can we instantiate an object implemented by python (pytorch) in a JAVA program and call its internal methods, like optimize.step() etc.?

**Comment by jbschlosser** [comment]
Hey @guoyaohua! FYI a question like this is a better fit for the [PyTorch forums](https://discuss.pytorch.org/). I encourage you to post there instead :)

**Comment by saudet** [comment]
@guoyaohua Yes, it is possible, see https://github.com/bytedeco/javacpp-presets/discussions/1075.

/cc @guangster
