### ISSUE TITLE
Source build issue: Missing catch.hpp

### ISSUE THREAD

**Issue by malmaud** [pytorch/pytorch#5925]
Trying to build master (a3bd7b2), I'm seeing

```
.../pytorch/aten/src/ATen/test/basic.cpp:2:21: fatal error: catch.hpp: No such file or directory`
```

I tried `git submodule update` in `.../pytorch` to no avail.

**Comment by malmaud** [comment]
NM, also needed a `git submodule init`.

**Comment by ezyang** [comment]
Need a check to see if this is checkout in `setup.py`, like the others. Should be a simple patch.
