### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory when using loss function during my TRAIN loop.

### ISSUE THREAD

**Issue by BinbinBian** [pytorch/pytorch#5929]
Implementating of CVPR2017 paper "[A Hierarchical Approach for Generating Descriptive Image Paragraphs](http://openaccess.thecvf.com/content_cvpr_2017/papers/Krause_A_Hierarchical_Approach_CVPR_2017_paper.pdf)"

I can run my model on cpu well with batch size =8
but When I am trying to run my model on _multi GPU_(4 gpu devices), during the _TRAIN_  loop, when I call the loss function, it results in a out of memory error. 
Even I run the model with  a small batch_size =4, it run out of memory.

The train loop  code of the model I am running:

 def forward(self, image,  instrs_vec,reference_vec):
        # image: size=(batch,3,224,224)
        # instrs_vec: size=(batch,20,20)
        #S_max=N_max=20

        batch_size = image.size(0)
       
       #vgg16 encoder
        fc_features, att_features = self.Encoder(image,14)
      
        att_features = norm(att_features) #TODO
        sent_state = self.init_hidden(batch_size)
        word_log_softmax_outputs = []
        sent_logistic_outputs =[]
        for i in range(self.S_max):
            if i ==0:
                procedure = self.init_procedure(batch_size)  # (batch_size , 512)TODO
            else:
                procedure = self.get_procedure(pre_procedure_words,self.self_att_type)
            sent_output, sent_state = self.sent_core(procedure , fc_features, att_features, sent_state)
            topic = self.h2topic(sent_output)
            sent_logistic = F.log_softmax(self.sent_logistic(sent_output))
            sent_logistic_outputs.append(sent_logistic)
            pre_procedure_words_list = []
            word_state = (topic.unsqueeze(0),topic.unsqueeze(0))
            for j in range(self.N_max+2):
                if j == 0:
                    xt = topic
                else:
                    it = instrs_vec[:, i,j - 1].clone()
                    xt = self.embed(it)
                word_output, word_state = self.word_LSTM(xt.unsqueeze(0), word_state)
                word_logit = self.logit(self.dropout(word_output.squeeze(0)))  #TODO  DROPOUT?
                output = F.log_softmax(word_logit)
                if j>0:
                    word_log_softmax_outputs.append(output)
                pre_procedure_words_list.append(word_output.squeeze(0))
            pre_procedure_words = torch.stack(pre_procedure_words_list,1)
        word_log_softmax_outputs = torch.cat([_.unsqueeze(1) for _ in word_log_softmax_outputs], 1).contiguous()
        sent_logistic_outputs = torch.cat([_.unsqueeze(1) for _ in sent_logistic_outputs], 1).contiguous()
        return word_log_softmax_outputs,sent_logistic_outputs

 for i, data in enumerate(train_loader):
        if use_gpu:
            torch.cuda.synchronize()
        data_time.update(time.time() - end)
        tmp = [data[0], data[1], data[2], data[3], data[4], data[5], data[6]]
        if use_gpu:
            tmp = [Variable(_ ).cuda( ) for _ in tmp]
        else:
            tmp = [Variable(_ ) for _ in tmp]
        img, instrs_vec, instrs_mask, instrs_num, reference_vec, reference_mask, classes = tmp
        # compute output
        word_log_softmax_outputs, sent_logistic_outputs = model(img, instrs_vec, reference_vec)
        # compute loss
        wordRNN_loss = criterion[0](word_log_softmax_outputs, instrs_vec[:, :, 1:], instrs_mask[:, :, 1:])
        sentRNN_loss = criterion[1](sent_logistic_outputs, instrs_num)

        wordRNN_losses.update(wordRNN_loss.data[0], data[0].size(0))
        sentRNN_losses.update(sentRNN_loss.data[0], data[0].size(0))
        if opts.semantic_reg:  #TODO
            class_loss = criterion[2]
            # combined loss
            loss = sentRNN_loss * opts.lambda_sent + \
                   wordRNN_loss * opts.lambda_word + \
                   class_loss * opts.lambda_class
            # measure performance and record losses
            class_losses.update(class_loss.data[0], data[0].size(0))
        else:
            loss = sentRNN_loss * opts.lambda_sent + wordRNN_loss * opts.lambda_word
        # compute gradient and do Adam step
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

- OS:linux
- PyTorch version:0.3.1
- How you installed PyTorch (conda, pip, source):pip
- Python version:python2.7
- CUDA/cuDNN version:8
- GPU models and configuration: 
 -GPU :TITAN X

 **Error output:**

Traceback (most recent call last):
  File "train.v1.py", line 408, in <module>
    main()
  File "train.v1.py", line 176, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.v1.py", line 282, in train
    loss.backward()
  File "/home/bbbian/local/anaconda/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/bbbian/local/anaconda/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by BinbinBian** [comment]
@apaszke

**Comment by apaszke** [comment]
The error message is quite clear, so I don’t think there’s anything we can do here. If you suspect a memory leak please try to minimize the scripts so we can easily reproduce and debug it.
