### ISSUE TITLE
Create two distributed groups

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#59294]
Hi, everyone,
    dist.init_process_group() will initilize a default distributed process group among P0, P1, P2, P3. Now, I want to build a new process_group between P0, P5, but keep the former one unchanged. How can I do this?👀👀👀👀👀
(P0's rank=0)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by pritamdamania87** [comment]
You can use the [new_group](https://pytorch.org/docs/stable/distributed.html#torch.distributed.new_group) API.

**Comment by densechen** [comment]
👌🏻
