### ISSUE TITLE
Trying to understand nn.MultiheadAttention coming from Keras

### ISSUE THREAD

**Issue by jiwidi** [pytorch/pytorch#59295]
Hi!

I’m trying to understand the multiheadattention function at pytorch MultiheadAttention — PyTorch 1.8.1 documentation and if I can use it to compute the selfattention as it can be done in the keras implementation MultiHeadAttention layer

With Keras implementation I’m able to run selfattention over a 1D vector the following way:
```python
import tensorflow as tf

layer = tf.keras.layers.MultiHeadAttention(num_heads=2, key_dim=2)
input_tensor = tf.keras.Input(shape=[8, 16])
output_tensor = layer(input_tensor, input_tensor)
print(output_tensor.shape)
(None, 8, 16)
```
I’ve tried to do the same with the pytorch implementation but couldn’t make it work. Could be because of lacking knowledge of the Transformer implementation.

```python
import torch
import torch.nn as nn
multihead_attn = nn.MultiheadAttention(16, 8)
input_tensor = torch.zeros(8,60)
multihead_attn(input_tensor,input_tensor,input_tensor)
With error

-> 4624     tgt_len, bsz, embed_dim = query.size()
   4625     assert embed_dim == embed_dim_to_check
   4626     # allow MHA to have different sizes for the feature dimension
ValueError: not enough values to unpack (expected 3, got 2)
```

It seems the keras function does some work under the hood to make it easier for the user and perform self-attention when both Query and Value are similar. Is there a way to do the same with pytorch?

cc @zhangguanheng66

**Comment by dunky11** [comment]
Have you tried using input_tensor = torch.zeros(8, 10, 60)? Normally the shape for 1-d data is (batch_size, channels, timesteps)

**Comment by dunky11** [comment]
The reason you do attention is to make the timesteps influence each other. Im not 100% certain, but I don't think it makes sense to use attention for data which has no timestep dimension.

**Comment by dunky11** [comment]
When you do tf.keras.Input(shape=[8, 16]), you dont define the batch size. So the real input has to be of shape (batch_size, 8, 16). At https://www.tensorflow.org/api_docs/python/tf/keras/Input  is says:
shape: 

"A shape tuple (integers), not including the batch size. For instance,&nbsp;shape=(32,)&nbsp;indicates that the expected input will be batches of 32-dimensional vectors. Elements of this tuple can be None; 'None' elements represent dimensions where the shape is not known."

**Comment by jiwidi** [comment]
@dunky11 
Hi! First of all, thanks for the answers. I'm quite newbie to transformers so it may be that i'm missing something on my approach.

The reason I want to use transformer is to replicate/implement the model at https://arxiv.org/pdf/1905.06874.pdf
![image](https://user-images.githubusercontent.com/10882086/120527645-dd6b0f80-c3da-11eb-81ca-4e19c0e419dd.png)
This model is also implemented on keras [here](https://github.com/shenweichen/DeepCTR/blob/master/deepctr/models/bst.py)

There is a sequence of items that go through an embedding and are passed to the transformer layer. So thinking about the shape it wont be 1d but 2d. (Batch , N.items, Embedding Size) and you are right it doesn't make much sense to use it with 1D. Looking at nn.multiheadattention docs 
```
query: (L, N, E)(L,N,E) where L is the target sequence length, N is the batch size, E is the embedding dimension.

key: (S, N, E)(S,N,E) , where S is the source sequence length, N is the batch size, E is the embedding dimension.

value: (S, N, E)(S,N,E) where S is the source sequence length, N is the batch size, E is the embedding dimension.
```

I think I should be using something like this instead then?

```python

import torch
import torch.nn as nn
multihead_attn = nn.MultiheadAttention(64, 8)
input_tensor = torch.zeros(20, 8, 64)
out, weights = multihead_attn(input_tensor,input_tensor,input_tensor)
print(out.shape, weights.shape)
....
torch.Size([20, 8, 64]) torch.Size([8, 20, 20])

```

That actually does pass without errors. 

It makes more sense in my head now, does it check with you too?

**Comment by dunky11** [comment]
Yes, thats correct. I always think its quite weird that the batch_size is the second dimension, but I guess thats how its implemented :).  The good thing is that this way you don't have to reshape the tensor before before passing it into the FeedForward block, which are just two linear layers.

**Comment by dunky11** [comment]
I remember that this was a great article about Transformers https://jalammar.github.io/illustrated-transformer/.

**Comment by dunky11** [comment]
I don't know how much you want to implement yourself, however this thing:

![Screenshot from 2021-06-03 00-18-41](https://user-images.githubusercontent.com/35628149/120559447-541b0380-c401-11eb-8a67-e1e3a3d0a90a.png)

Is just a transformer encoder block and is already implemented in https://pytorch.org/docs/stable/generated/torch.nn.TransformerEncoderLayer.html

**Comment by jiwidi** [comment]
> I don't know how much you want to implement yourself, however this thing:
> 
> ![Screenshot from 2021-06-03 00-18-41](https://user-images.githubusercontent.com/35628149/120559447-541b0380-c401-11eb-8a67-e1e3a3d0a90a.png)
> 
> Is just a transformer encoder block and is already implemented in https://pytorch.org/docs/stable/generated/torch.nn.TransformerEncoderLayer.html

Yeah it seems that already has all the parts of the encoder they use in the paper. I found a keras implementation of the paper
```python
    # Transformer block.
    attention_output = layers.Dropout(dropout_rate)(attention_output)
    x1 = layers.Add()([transformer_features, attention_output])
    x1 = layers.LayerNormalization()(x1)
    x2 = layers.LeakyReLU()(x1)
    x2 = layers.Dense(units=x2.shape[-1])(x2)
    x2 = layers.Dropout(dropout_rate)(x2)
    transformer_features = layers.Add()([x1, x2])
    transformer_features = layers.LayerNormalization()(transformer_features)
    features = layers.Flatten()(transformer_features)
``` 

And this is exactly that transformer encoderlayer.

Thank you!
