### ISSUE TITLE
Getting Started Page for 1.8.1 and LibTorch for Windows

### ISSUE THREAD

**Issue by Dris101** [pytorch/pytorch#59300]
## Getting Started Page for 1.8.1 and LibTorch for Windows

[https://pytorch.org/get-started/locally/]() states that

> Windows stable binaries do not support Java, but nighty binaries do

I am using Stable 1.8.1 / Windows / LibTorch / C++/Java / CUDA 10.2 on Windows 10 with Java and it works for me. My experience was that the 1.7.x versions didn't work, but the nightlies of 1.8.0 started to work and now the release version seems fine, so perhaps the Getting Started page should be updated to reflect that if that is expected. I can provide more details of my usage if that would be helpful. The build hash of my LibTorch installation is 56b43f4fec1f76953f15a627694d4bba34588969

cc @yf225 @glaringlee @brianjo @mruberry

**Comment by peterjc123** [comment]
Fixes are proposed in pytorch/pytorch.github.io#729. Would you please take a look, @seemethere ?
