### ISSUE TITLE
torch.utils.data.DataLoader scans IterableDataset twice before it stops

### ISSUE THREAD

**Issue by wangkuiyi** [pytorch/pytorch#59312]
## 🐛 Bug

`torch.utils.data.DataLoader`, when works with a customized `torch.util.data.IterableDataset`, scans the dataset **twice**, as shown in my diff D28508287.

To make it easy to reproduce the problem, Shunting Zhang simplified the above diff into paste P415580779, which reveals that `torch.utils.data.DataLoader` doesn’t stop calling next after the IterableDataset raised StopIteration exception.

## To Reproduce

Please try the following customized IterableDataset with DataLoader.

```python
class CachingIterator:  # depends on CachedIterable so cannot be nested class.
    def __init__(self, ds: CachedIterable):
        self.ds = ds
        self.pos = -1
        self.raise_num = 0

    def __next__(self) -> Any:
        if self.raise_num == 1:
            self.raise_num == 2
            raise StopIteration

        if self.ds.itrt is not None:
            i = next(self.ds.itrt, None)
            if i is not None:
                self.ds.cache.append(i)
                return i
            else:
                print("CachingIterator stopes")
                self.ds.itrt = None  # notify CachedIterable.__iter__ to yield cache.
                self.raise_num += 1
                raise StopIteration
        else:
            if self.pos + 1 < len(self.ds.cache):
                self.pos = self.pos + 1
                return self.ds.cache[self.pos]
            else:
                raise StopIteration
```

## Additional context

@dzhulgakov identified the bug is due to that the fetcher doesn't remember it had encountered StopIteration. For details, please see his comment at https://fb.quip.com/nvyoAJgmzBzZ#PBKACAQVfEj

cc @VitalyFedyunin @ejguan @SsnL

**Comment by ejguan** [comment]
Nice catch!
