### ISSUE TITLE
build error: conflicting types for ‘cpuinfo_initialize’

### ISSUE THREAD

**Issue by thnkim** [pytorch/pytorch#5932]
I got the codes by 'git clone' and tried 'python setup.py install'. Then, I got the following error:

```
.../download/pytorch/aten/src/ATen/cpu/cpuinfo/src/init.c:22:18: error: conflicting types for ‘cpuinfo_initialize’
 bool CPUINFO_ABI cpuinfo_initialize(void) {
                  ^
In file included from .../download/pytorch/aten/src/ATen/cpu/cpuinfo/src/init.c:7:0:
.../anaconda3/include/cpuinfo.h:491:18: note: previous declaration of ‘cpuinfo_initialize’ was here
 void CPUINFO_ABI cpuinfo_initialize(void);
```

- OS: Ubuntu 16.04
- PyTorch version: 0.4  (e9f144b3e84f03d6a507faac40bdfce58b68c1fb)
- How you installed PyTorch (conda, pip, source): source ('git clone')
- Python version: Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19), [GCC 7.2.0] on linux
- CUDA/cuDNN version: CUDA 9.0, cuDNN 7.0.5
- GPU models and configuration: nVidia GTX 1080
- GCC version (if compiling from source): 5.4.0 20160609

**Comment by zou3519** [comment]
Does running `git submodule update --init` help?

cc @cpuhrsch may be able to help.

**Comment by Maratyszcza** [comment]
You have an older version of **cpuinfo** installed in `.../anaconda3/`, and its header is included instead of **cpuinfo** from PyTorch/ATen.

**Comment by thnkim** [comment]
I reinstalled Anaconda (downloaded it again from the website).
Then anaconda3/include/cpuinfo.h was removed (I don't know which old library used it), and everything is ok now.
Thank you.
