### ISSUE TITLE
torch.nn.LSTM does not document reverse weights for bidirectional LSTMs

### ISSUE THREAD

**Issue by calvinmccarter-at-lightmatter** [pytorch/pytorch#59332]
## 📚 Documentation

The "Variables" section of LSTM documentation (https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) is missing documentation of reverse weights for bidirectional LSTMs. Bidirectional LSTMs have the following additional undocumented variables:

- `weight_ih_l[k]_reverse` (in addition to `weight_ih_l[k]`)
- `weight_hh_l[k]_reverse` (in addition to `weight_hh_l[k]`)
- `bias_ih_l[k]_reverse` (in addition to `bias_ih_l[k]`)
- `bias_hh_l[k]_reverse` (in addition to `bias_hh_l[k]`)

cc @brianjo @mruberry @albanD @jbschlosser @zou3519

**Comment by jbschlosser** [comment]
Thanks for pointing this out! We'd accept a PR addressing this.
