### ISSUE TITLE
Linux CPU build script fails as MKL header files not found

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#5933]
We have been using the build script from #4178 to keep up to date with PyTorch master for Pyro CI testing. The script fails now with the following error, which blocks us from updating PyTorch. 

```
CMake Error at CMakeLists.txt:389 (MESSAGE):
  MKL header files not found.  If using conda, please run `conda install
  mkl-include`.  Otherwise, please make sure that CMake will search the
  directory containing the header files, e.g., by setting CMAKE_INCLUDE_PATH.
```

Could we update the build scripts to fix this issue? If there is an easy fix, I'll be happy to do so at our end and contribute the patch here. Possibly related: #5888

cc. @ezyang, @soumith

**Comment by neerajprad** [comment]
cc. @fritzo.

**Comment by neerajprad** [comment]
@SsnL, @soumith - I fixed the script at our end by installing mkl in the docker image first, and adding the header file locations to the cmake include path. The packages are quite big (~2.5 gigs) though, and it will be great if we can include this in the docker image itself.

**Comment by SsnL** [comment]
@neerajprad This error only happens if cmake finds mkl but not mkl headers. So installing the mkl binaries might not be needed as they should already be there.

**Comment by neerajprad** [comment]
> @neerajprad This error only happens if cmake finds mkl but not mkl headers.

The header files are unfortunately not there. I can see the following commands in the Dockerfile. So maybe we just need to copy the header files in the include directory and put them here?

```
# MKL
RUN mkdir -p /opt/intel/lib
COPY mkl_libs/libmkl_core.a /opt/intel/lib/libmkl_core.a
COPY mkl_libs/libmkl_gnu_thread.a /opt/intel/lib/libmkl_gnu_thread.a
COPY mkl_libs/libmkl_intel_lp64.a /opt/intel/lib/libmkl_intel_lp64.a
```

**Comment by SsnL** [comment]
Yes that probably can work. If not, make sure that crake searches the
directory.

**Comment by ezyang** [comment]
If you are not using conda, pip install mkl-devel gets you the headers. I haven't looked at your CI script. @SsnL can we add this to the error message?

**Comment by ezyang** [comment]
Fixed.

**Comment by matifali** [comment]
still same message after doing `pip install mkl-devel`
