### ISSUE TITLE
SWA with mixed-precision and distributed training

### ISSUE THREAD

**Issue by sayakpaul** [pytorch/pytorch#59363]
## 🐛 Bug

I am unable to update the batch norm statistics of an `swa_model` after training. My data loader does not outline the tesnors as expected by SWA. So, I am running a single forward pass with the `swa_model` on each of the elements present inside my data loader. Here's the minimal code:

```python
if rank == 0:
    for batch in train_loader: 
        image = batch['image'].cuda(rank, non_blocking=True)
        prediction = swa_model(image)
```

Please note that I am doing this along with distributed training and mixed-precision (`torch.cuda.amp`). 

## To Reproduce

`train()` is the launcher function I pass to `torch.multiprocessing.spawn()`. 

```python
def train(rank, num_epochs, world_size):
    init_process(rank, world_size)
    torch.manual_seed(0)
    
    model = create_model()
    torch.cuda.set_device(rank)
    model.cuda(rank)
    model = DistributedDataParallel(model, device_ids=[rank])
    swa_model = torch.optim.swa_utils.AveragedModel(model)

    learning_rate = 1e-3
    optimizer = torch.optim.Adam(model.parameters(), 
                             lr=learning_rate * world_size)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=20)
    swa_start = 10
    swa_scheduler = torch.optim.swa_utils.SWALR(optimizer, swa_lr=0.05)
    criteria = nn.CrossEntropyLoss()
    scaler = torch.cuda.amp.GradScaler(enabled=True)

    
    train_loader, val_loader = get_dataloader(rank, world_size)
    
    for epoch in range(num_epochs):
        model.train()
        for batch in train_loader:
            with torch.cuda.amp.autocast(enabled=True):
                image = batch['image'].cuda(rank, non_blocking=True)
                mask = batch['mask'].cuda(rank, non_blocking=True)
                
                pred = model(image)
                
                loss = criteria(pred, mask.unsqueeze(1))

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
            
        if epoch > swa_start:
            swa_model.update_parameters(model)
            swa_scheduler.step()
        else:
            scheduler.step()

    if rank == 0:
        for batch in train_loader: 
            image = batch['image'].cuda(rank, non_blocking=True)
            prediction = swa_model(image)
```
Here's the full error trace:

```
Traceback (most recent call last):
  File "starter.py", line 343, in <module>
    nprocs=WORLD_SIZE, join=True
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jupyter/Flood_Comp/starter.py", line 334, in train
    prediction = swa_model(image)
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/optim/swa_utils.py", line 101, in forward
    return self.module(*args, **kwargs)
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 610, in forward
    self._sync_params()
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 1048, in _sync_params
    authoritative_rank,
  File "/home/jupyter/.local/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 979, in _distributed_broadcast_coalesced
    self.process_group, tensors, buffer_size, authoritative_rank
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.138.0.33]:26791
```

## Expected behavior

The forward pass with the `swa_model` should work (?)

## Environment

* PyTorch 1.8.1
* GCP Compute Engine VM with `n1-standard-16` plugged to four V100s
* CUDA 11.0

cc @mcarilli @ptrblck @ngimel @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
cc @mcarilli 

Hey @sayakpaul, could you please help check if the failure still persist after removing AMP? It would help us narrow down the problem. Or, if you could share a self-contained repro, I can also help dig into that. Thanks!

**Comment by sayakpaul** [comment]
Sure. I will check this and will let you know. Thank you!

**Comment by sayakpaul** [comment]
@mrshenli I can confirm that the error still persists without AMP.

**Comment by mrshenli** [comment]
Hey @sayakpaul, thanks for confirming!

```python
    if rank == 0:
        for batch in train_loader: 
            image = batch['image'].cuda(rank, non_blocking=True)
            prediction = swa_model(image)
```

Does changing the above code to the following work? If not, could you please share a self-contained repro? Thanks!

```python
    if rank == 0:
        with torch.no_grad():
            for batch in train_loader: 
                image = batch['image'].cuda(rank, non_blocking=True)
                prediction = swa_model(image)
```

**Comment by sayakpaul** [comment]
That seems to have resolved the problem. Do you mind taking a look at [this gist](https://gist.github.com/sayakpaul/97e20e0a18a03f8c960b57a59188bd8b)? It's self-contained. It will help verify if it's implemented correctly and thereby helping the community. 

Also, what would be the suggested way to serialize the `swa_model`?

**Comment by mrshenli** [comment]
> Also, what would be the suggested way to serialize the swa_model?

We usually recommend serializing the local model (i.e., `ddp_module.module`) instead of the DDP module, and only do that on one rack (since all ranks see the same model). Later, when you need to re-construct the model, you can first load the local module checkpoint and then pass that to `DistributedDataParallel` ctor.

**Comment by mrshenli** [comment]
> Do you mind taking a look at this gist? 

Yep. I tried, but http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz is service unavailable currently. Will try again later. The code looks correct to me. 

```python
loss = losses.avg        
global_loss = global_meters_all_avg(rank, world_size, loss)         
if rank == 0:            
     print(f"Epoch: {epoch+1} Train Loss: {global_loss[0]:.3f}")
```

BTW, doing the above for every iteration can be slow, as collective comm can be one major source of delay for DDP training. If you just need that to print the global loss, you can try either 1) only doing that every N iterations or 2) and launch that right after the forward and make it async.

**Comment by sayakpaul** [comment]
@mrshenli could you provide minimal code examples for both the comments you made? Would be tremendously helpful.

**Comment by mrshenli** [comment]
> So, during loading (w.r.t the gist code), I could do something like:

Yep, this is correct:

> @mrshenli could you provide minimal code examples for both the comments you made? Would be tremendously helpful.

Sure

For 1):

```python
cnt += 1
if cnt == 10:
    loss = losses.avg        
    global_loss = global_meters_all_avg(rank, world_size, loss)         
    if rank == 0:            
        print(f"Epoch: {epoch+1} Train Loss: {global_loss[0]:.3f}")
```

For 2):

```python
    for epoch in range(num_epochs):
        losses = AvgMeter()
        
        if rank == 0:
            print("Rank: {}/{} Epoch: [{}/{}]".format(rank, world_size, epoch+1, num_epochs))
        
        model.train()
        for images, labels in train_loader:
            with torch.cuda.amp.autocast(enabled=True):
                images = images.cuda(rank, non_blocking=True)
                labels = labels.cuda(rank, non_blocking=True)
                
                pred = model(images)
                loss = criterion(pred, labels)

            global_loss = loss.avg.detach() # get a new tensor shares the storage and does not require grad
            # assuming loss.avg is a single tensor, launch async comm
            # this allows this comm to overlap with backward computation 
            work = dist.all_reduce(global_loss, async_op) 

            losses.update(loss.cpu().item(), images.size(0))
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
            
        if epoch > swa_start:
            swa_model.update_parameters(model)
            swa_scheduler.step()
        else:
            scheduler.step()
            
        if rank == 0:
            work.wait() # make sure the allreduce is done
            print(f"Epoch: {epoch+1} Train Loss: {global_loss[0]:.3f}")
```

**Comment by sayakpaul** [comment]
Thank you very much. I think having a Kaggle Kernel or a Colab Notebook with this gist might be very useful for the community. I will try to work on one and update it here. 

I am closing this issue for now since I don't have anything else. Appreciate your guidance :)

**Comment by mrshenli** [comment]
> Does the loss returned by criterion have an avg property? 

Oh I see. I was wrong. I was copying from the original code, and didn't notice the `avg` attribute wasn't available until `losses.update()`. In that case, the `all_reduce` should be launched after that. As long as the comm is launched before backward, it should help to overlap comm with comp. 

> Could you expand a bit more on this?

Sure, the `work` handle returned by asynchronous collective communications, can be treated as a Future object which represents the completion of the communication. With `async_op=True`, `all_reduce` will return immediately. And then we will need to wait on the returned `work` before using the allreduced tensor.

**Comment by sayakpaul** [comment]
Thank you!

> Oh I see. I was wrong. I was copying from the original code, and didn't notice the avg attribute wasn't available until losses.update(). In that case, the all_reduce should be launched after that. As long as the comm is launched before backward, it should help to overlap comm with comp.

So, should it be like this?

```python
 for epoch in range(num_epochs):
        losses = AvgMeter()
        
        if rank == 0:
            print("Rank: {}/{} Epoch: [{}/{}]".format(rank, world_size, epoch+1, num_epochs))
        
        model.train()
        for images, labels in train_loader:
            with torch.cuda.amp.autocast(enabled=True):
                images = images.cuda(rank, non_blocking=True)
                labels = labels.cuda(rank, non_blocking=True)
                
                pred = model(images)
                loss = criterion(pred, labels)

            losses.update(loss.cpu().detach().item(), images.size(0))
            global_loss = losses.avg  
            work = dist.all_reduce(global_loss, async_op=True) 
```

Sorry for the botheration but I just want to make sure I am getting this right.

**Comment by mrshenli** [comment]
> But I don't think all the batch-wise losses would available by this time. 

You mean the CUDA ops that compute the loss are pending? That should be fine, ProcessGroup will let the communication stream wait for the current stream before launching allreduce kernels.

**Comment by sayakpaul** [comment]
I mean will it account for correct epoch-wise loss calculation in the code I modified [here](https://github.com/pytorch/pytorch/issues/59363#issuecomment-856830441)?

**Comment by mrshenli** [comment]
> I mean will it account for correct epoch-wise loss calculation in the code I modified here?

Oh I see. I mis-read the code. If it's once per epoch (instead of per iteration), then there is no perf concerns at all.

**Comment by sayakpaul** [comment]
Got it now. Thank for being so patient with my questions :-)

**Comment by nsriniva03** [comment]
Do you have to use a swa scheduler ? Let's say you have a lr_scheduler that decays over time; can you just average out the models over the last few epochs/iterations using AverageModel. Every iteration the learning rate decreases by a small value.
