### ISSUE TITLE
`NotImplementedError` is not right Exception for `DataPipe.__len__`

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#59378]
## 🐛 Bug

Thanks to @pmeier, a bug of `IterDataPipe` was found. For each `IterDataPipe` class, we raise `NotImplementedError` in `__len__` in some cases such as `length` is -1 or prior `DataPipe` is not `Sized`.

When we apply `tqdm` to the `DataPipe` instance without explicit length, `len(dp)` will be called and the `NotImplementedError` will emit. So, we can never use `tqdm` for such kind of DataPipe. However,  we are actually expecting DataPipe with `NotImplementedError` as an infinite length. 

And, based on the definition of [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError), it's not an appropriate Exception since this exception normally raises from base class to enforce derived class implementing this method.

And, considering the implementation of `tqdm`, we should switch `NotImplementedError` to `TypeError`.
https://github.com/tqdm/tqdm/blob/05ad200df3ccbc21c5c840d064e619ec9838f902/tqdm/std.py#L983-L990

## To Reproduce

```py
>>> import tqdm
>>> class DP(IterDataPipe):
...     def __len__(self):
...         raise NotImplementedError
... 
>>> dp = DP()
>>> pbar = tqdm.tqdm(dp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erjia/tools/miniconda3/envs/pt/lib/python3.8/site-packages/tqdm/std.py", line 985, in __init__
    total = len(iterable)
  File "<stdin>", line 3, in __len__
NotImplementedError
```

## Expected behavior

By switching to `TypeError`, DataPipe works with `tqdm` correctly.
BTW, we should not create `__len__` at runtime since this method is attached to `class` object. When we change it, behavior of all instances will change. Any other suggestions to fix it are welcomed.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by SsnL** [comment]
see also 
https://github.com/pytorch/pytorch/blob/6620d7d688c9482a00b1a9827187f135b72b7862/torch/utils/data/sampler.py#L26-L51
