### ISSUE TITLE
RuntimeError: value cannot be converted to type uint8_t without overflow: 10000

### ISSUE THREAD

**Issue by Rokuki** [pytorch/pytorch#5938]
I am trying to run the [this code](https://github.com/yunjey/pytorch-tutorial/blob/4b67434961a64ba5e19e63d44f0b9979d2a9aa11/tutorials/01-basics/feedforward_neural_network/main-gpu.py).

The training progress is perfect，but the accuracy did not print out，and some error came out like this：
```
Epoch [5/5], Step [200/600], Loss: 0.0404
Epoch [5/5], Step [300/600], Loss: 0.0511
Epoch [5/5], Step [400/600], Loss: 0.0042
Epoch [5/5], Step [500/600], Loss: 0.0464
Epoch [5/5], Step [600/600], Loss: 0.1073
Traceback (most recent call last):
  File "fnn.py", line 84, in <module>
    print('Accuracy of the network on the 10000 test images: %d %%' % (100 * correct / total))
RuntimeError: value cannot be converted to type uint8_t without overflow: 10000
```
And the code is：

```
# Test the Model
correct = 0
total = 0
for images, labels in test_loader:
    images = Variable(images.view(-1, 28*28))
    outputs = net(images)
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum()

print('Accuracy of the network on the 10000 test images: %d %%' % (100 * correct / total))

```
I have tried it before with python3.5 on win10，it could ran perfectly，but somehow couldn't use the cuda，so i turn to the ubuntu，is it the python version problem？

- OS:ubuntu16.04
- PyTorch version:0.4.0a0+7cbbc0b
- How you installed PyTorch (conda, pip, source):source
- Python version:2.7
- CUDA/cuDNN version:9.0
- GCC version (if compiling from source):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

I know that this question shouldn't be asked here cause it is not the pytorch's issus, but i can't access the stackoverflow, it is slow on Chinese internet .So it will be very appericated if someone could help me with this.Thx

**Comment by SsnL** [comment]
yeah the tutorials needs to be updated. for now, you can try this:
```
correct += (predicted == labels).sum().item()
```

**Comment by Rokuki** [comment]
@SsnL I have tried this and I got Accuracy =1% , which is confuse me...

**Comment by Rokuki** [comment]
@SsnL it works！thanks a lot

**Comment by SsnL** [comment]
`(predicted == labels).sum()` is a uint8 tensor. `correct / total` can't be represented as an uint8. so you need to get the python number.
