### ISSUE TITLE
Add dynamic sharding for Github Actions workflows

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#59401]
We have the concept of sharding of tests for specific build configurations within CircleCI and we'd like to have the same concept within Github Actions.

For sharding I can envision us enabling sharding with Github Actions by utilizing dynamic matrix values to create multiple test jobs that will act as shards. An example of dynamic matrix values can be found here:
https://github.com/pytorch/pytorch/blob/e66015dadf135f6e1cda69d80883505807b1bbed/.github/workflows/build_linux_conda.yml#L10-L33

# How would this work?
1. Create a job as depenendcy to the `test` job that generates a json blob (probably through a python script)
2. Use that json blob as an input into the `test` job as a matrix value

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
This is done now that:
https://github.com/pytorch/pytorch/pull/60124 &
https://github.com/pytorch/pytorch/pull/59970
are merged
