### ISSUE TITLE
Core dump after torch.permute with negative index

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#5943]
I got core dump which killed my script / jupyter kernel ([traceback](https://gist.github.com/fehiepsi/464374ad7661401321b04b6ea73177e5)). I used pytorch master (commit `e9f144`)

After investigating, I can reproduce its behavior with the following simple script:
```
import torch

u = torch.zeros((3, 3), requires_grad=True)
v = u.permute(-1, -2)  # (1, 0) here is fine
v.sum().backward()
```
After knowing the reason, I can fix my script by using non-negative indices. If this behavior is expected, I will close this issue. :)

cc @apaszke

**Comment by zou3519** [comment]
@fehiepsi what exactly is the error message you're getting? I'm getting the following on master, and want to make sure you have the same problem:
```
>>> import torch
>>>
>>> u = torch.zeros((3, 3), requires_grad=True)
>>> v = u.permute(-1, -2)  # (1, 0) here is fine
>>> v.sum().backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rzou/pytorch/pytorch/torch/autograd/variable.py", line 120, in bac
kward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/rzou/pytorch/pytorch/torch/autograd/__init__.py", line 87, in back
ward
    tensors, grad_tensors, retain_graph, create_graph)
RuntimeError: repeated dim in permute
```

**Comment by fehiepsi** [comment]
I make a `permute.py` script with the above code, and run `python permute.py`, and get [this lengthy error](https://gist.github.com/fehiepsi/caf573fea553dc9a442b6efee52dfc49).
If I run it in ipython or jupyter, the kernel died.
Here is the [traceback](https://gist.github.com/fehiepsi/464374ad7661401321b04b6ea73177e5) for `python permute.py`

**Comment by zou3519** [comment]
Ah okay, thank you for the tracebacks. The root cause should be the same: a std::vector is being indexed with negative numbers in the backward pass. Fix incoming.
