### ISSUE TITLE
I cannot initialize Tensor. (They will become torch.autograd.variable.Variable)

### ISSUE THREAD

**Issue by Alexpon** [pytorch/pytorch#5944]
- OS: Linux
- PyTorch version: torch-0.4.0a0+a58f2d2
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.5.2
- CUDA/cuDNN version: 9.0

Following code for reproducing:

ipdb> torch.FloatTensor([0])  
 0 
[torch.FloatTensor of size (1,)]

ipdb> type(torch.FloatTensor([0])) 
<class 'torch.autograd.variable.Variable'>

**Comment by karandwivedi42** [comment]
See https://github.com/pytorch/pytorch/pull/5225

**Comment by Alexpon** [comment]
@karandwivedi42  Thanks a lot!

**Comment by Alexpon** [comment]
Another question.
How can I get the value from Variable? 
From #2633 -- "Variable.data accessor will be deprecated"
So I cannot get value directly variable.data[0] or variable.data.float()

**Comment by apaszke** [comment]
You can call `.item()` or `float(tensor)`
