### ISSUE TITLE
Error importing torchvision

### ISSUE THREAD

**Issue by abhinavvs** [pytorch/pytorch#5947]
I get the following error when I run `import torchvision` to import the package:

> `Traceback (most recent call last):`
>
>  File `"<ipython-input-19-3f9cdacf92f1>"`, line 1, in <module>
>    `import torchvision`
>
> `ImportError: No module named torchvision`

I installed pytorch and torchvision together using `conda` by following the instructions on http://pytorch.org/ using the command: `conda install pytorch torchvision -c pytorch`. I am able to import pytorch (using the command: `import torch`) but not the torchvision package. I am using Python 2.7 on a Mac OSX. 

Not sure what has gone wrong.! Any help would be much appreciated

**Comment by ezyang** [comment]
Double check and make sure you are actually running the correct python for conda. Try making a fresh conda environment, activate it and reinstall the packages.
