### ISSUE TITLE
replace platform specific CI environment variables with generic ones

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#59478]
Per: https://github.com/pytorch/pytorch/pull/58341#discussion_r645763544
We have many CI environment variables used that are specific to platforms. these could be pre-set environment variables provided by the venders. 

This posts challenge when migrating between circle to gha. here are a list of env vars we should make platform independent changes. namely all `CIRCLECI_*` [built-in](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) environment variable

changing env var usage for scripts in:
  - [ ] tools/
  - [ ] .jenkins/
  - [ ] .circleci/scripts

and platform specific env-var to generic env-var conversion for CI configurations in:
  - [ ] .github/**
  - [ ] .circleci/**

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Talked it over in our sync up this morning, we should probably create translation scripts to translate environment variables from any CI platform to a set of common environment variables we can absolutely depend on
