### ISSUE TITLE
PyTorch Windows LSTM NameError: name ‘fn’ not defined 

### ISSUE THREAD

**Issue by tappan-ajmera** [pytorch/pytorch#5948]
Hi,

I installed PyTorch on Windows following the Easy Install steps on https://github.com/peterjc123/pytorch-scripts
It works fine but when I am trying to use LSTM, it fails with NameError: name ‘fn’ is not defined.
I checked issues section of PyTorch https://github.com/pytorch/pytorch/issues/52111 and I understand that the bug is fixed in the master branch.

I have no clue how to build PyTorch from master branch on Windows for GPU version. I am new to this.
I am using Anaconda environment.

Any suggestions will be helpful. I am stuck!

Thanks in advance.

OS: Windows 10
PyTorch version: 0.3.1
How you installed PyTorch (conda, pip, source): conda install -c peterjc123 pytorch cuda90
Python version: 3.5
CUDA/cuDNN version: 9
GPU models and configuration: NVIDIA GTX 1060

**Comment by peterjc123** [comment]
There's also compiling tutorials on that [repo](https://github.com/peterjc123/pytorch-scripts`).

**Comment by apaszke** [comment]
It’s a big that’s been fixed in master. We don’t have official binaries for Windows just yet so you’ll probably need to build from source.
