### ISSUE TITLE
Bug Report re-initializing weights after layer initialization 

### ISSUE THREAD

**Issue by devansh20la** [pytorch/pytorch#5949]
```
x = Variable( torch.randn(1,10))
layer = nn.Linear(10,10,bias=False)
layer.weight.data = torch.randn(100,100)
```
Why is this allowed? considering the fact that it changes the entire layer 

```
print(layer)
Linear(in_features=10, out_features=10, bias=False) 

```

```
x = torch.randn(1,10)
layer(Variable(x))
```
This gives a dimension mismatch error

**Comment by apaszke** [comment]
Here's one reason: people sometimes want to e.g. enlarge the output size, and this allows them to replace the weights. You can always add an assert that the weights you assign have the same shape if you want to be safe. Thanks for the suggestion, but closing as wontfix.
