### ISSUE TITLE
segfault when torch is imported before scipy.ndimage

### ISSUE THREAD

**Issue by thuyen** [pytorch/pytorch#595]
The following will give segfault on `ubuntu/python 2.7`
````python
import torch
import scipy.ndimage
````
This works just fine: 
````python
import scipy.ndimage
import torch
````

**Comment by apaszke** [comment]
Can't reproduce. Can you run it in gdb?
```
gdb python
> r
# now python will launch
>>> import torch
>>> import scipy.image
# it should stop because of the segfault
> bt
# paste the output in the comments
```

**Comment by thuyen** [comment]
It's weird, it's showing something from `numpy`, but no error working with `numpy` sofar. 
This is fresh virtual environment, everything is installed with `pip`. 

OS: `Linux 4.4.0-51-generic #72~14.04.1-Ubuntu SMP Thu Nov 24 19:22:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Python `2.7.6`, numpy `1.12.0`, scipy `0.18.1`

Output from `gdb`:
````
Program received signal SIGSEGV, Segmentation fault.
0x00007fffd6888fc0 in PyArray_API () from /home/thuyen/.virtualenvs/torch/local/lib/python2.7/site-packages/numpy/core/multiarray.so
````

**Comment by apaszke** [comment]
Can't reproduce even on ubuntu 14.04 on python 2.7.

**Comment by thuyen** [comment]
Maybe there's something wrong with my `numpy`. I am closing this then. 
Thanks!
