### ISSUE TITLE
Wrong behavior of torch.arange

### ISSUE THREAD

**Issue by rotabulo** [pytorch/pytorch#5950]
I noticed that `torch.arange` deliver results that disagree with the provided documentation.
Specifically, the values should belong to the interval `[start,end)`, but sometimes `end` is included, and sometimes it is not.
For instance
`torch.arange(0,1,0.5)` delivers the correct result `[0,0.5]`
while 
`torch.arange(0,1,0.2)` delivers the wrong result [0, 0.2, 0.4, 0.6, 0.8, 1.0]

Tested on pytorch version 0.3.1

**Comment by SsnL** [comment]
Fixed on master
