### ISSUE TITLE
irfft2  size issue for PyTorch 1.8.1

### ISSUE THREAD

**Issue by yihuajack** [pytorch/pytorch#59514]
## 📚 Documentation

In the example of `torch.fft.irfft2` https://pytorch.org/docs/stable/fft.html?highlight=irfft#torch.fft.irfft2
```
>>> t = torch.rand(10, 9)
>>> T = torch.fft.rfft2(t)
>>> torch.fft.irfft2(T).size()
```
The doc says that the output is
> torch.Size([10, 10])

However, as I tried on my Linux with Python 3.8.5 PyTorch 1.8.1, the output is repeatedly
> torch.Size([10, 8])

However, for other examples there are no differences. I don't know how the output is round-tripped.

cc @brianjo @mruberry @peterbell10 @walterddr

**Comment by mruberry** [comment]
@peterbell10, what are your thoughts?

**Comment by peterbell10** [comment]
The function behaves in line with NumPy. It's the example that's incorrect here.
