### ISSUE TITLE
Mutable add with indexing does not act as the scatter add.

### ISSUE THREAD

**Issue by mrakgr** [pytorch/pytorch#59511]
## To Reproduce

```py
import torch
q = torch.zeros(5)
w = torch.rand(4)
e = torch.tensor([1,1,1,1])
q[e] += w
```
```
>>> import torch
>>> w = torch.rand(4)
>>> e = torch.tensor([1,1,1,1])
>>> q[e] += w
>>> w
tensor([0.2019, 0.6139, 0.7754, 0.0676])
>>> q
tensor([0.0000, 0.0676, 0.0000, 0.0000, 0.0000])
```

## Expected behavior

```py
>>> torch.scatter_add(q,0,e,w)
tensor([0.0000, 1.7265, 0.0000, 0.0000, 0.0000])
```

## Environment

PyTorch version: 1.7.1
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 456.71
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h74a9793_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38hb782905_0
[conda] mkl_fft                   1.2.0            py38h45dec08_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.7.1           py3.8_cuda110_cudnn8_0    pytorch
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.2.1                      py_2    soumith

**Comment by mrakgr** [comment]
It might have been better to name the title 'Mutable add with indexing does not act as the index_add_.'
` Here is an example that show the problem that arises when indexing into a tensor's rows.

```py
import torch
q = torch.zeros(5,5)
w = torch.rand(4,5)
e = torch.tensor([1,1,2,2])
q[e,:] += w
q
w
```
```
>>> import torch
>>> q = torch.zeros(3,5)
>>> w = torch.rand(4,5)
>>> e = torch.tensor([1,1,2,2])
>>> q[e,:] += w
>>> print(q)
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3430, 0.5353, 0.4048, 0.1445, 0.1849],
        [0.0996, 0.8989, 0.2920, 0.4798, 0.0945]])
>>> print(w)
tensor([[0.9075, 0.3436, 0.6350, 0.8430, 0.8002],
        [0.3430, 0.5353, 0.4048, 0.1445, 0.1849],
        [0.6752, 0.7003, 0.7980, 0.0856, 0.2408],
        [0.0996, 0.8989, 0.2920, 0.4798, 0.0945]])
```

Note how it just sets the tensor to first and second row of `e` rather than adding them in turn. Here is what should be the expected result.

```py
import torch
q = torch.zeros(3,5)
w = torch.rand(4,5)
e = torch.tensor([1,1,2,2])
print(q.index_add_(0,e,w))
print(w)
```
```
>>> import torch
>>> q = torch.zeros(3,5)
>>> w = torch.rand(4,5)
>>> e = torch.tensor([1,1,2,2])
>>> print(q.index_add_(0,e,w))
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.4533, 0.2823, 0.9815, 1.6732, 1.0991],
        [1.0203, 1.9389, 1.3240, 1.1337, 1.2825]])
>>> print(w)
tensor([[0.5623, 0.1057, 0.6262, 0.6890, 0.7029],
        [0.8910, 0.1767, 0.3553, 0.9842, 0.3962],
        [0.4077, 0.9650, 0.8941, 0.7104, 0.8916],
        [0.6126, 0.9739, 0.4299, 0.4232, 0.3908]])
```

**Comment by ngimel** [comment]
This behavior is consistent with numpy
