### ISSUE TITLE
pytorch conflicts with newly created conda environment

### ISSUE THREAD

**Issue by FlameSky-S** [pytorch/pytorch#59517]
## 🐛 Bug

Installing pytorch using `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia` reports package confilts. The conda env is created with `conda create --name test python=3.9`. The list of packages initially installed is as follows:
```text
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2021.5.25            h06a4308_1    defaults
certifi                   2021.5.30        py39h06a4308_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.1.1           py39h06a4308_0    defaults
python                    3.9.5                hdb3f193_3    defaults
readline                  8.1                  h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
sqlite                    3.35.4               hdfb4753_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

The confilts are: 
```text
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
pytorch -> libgcc-ng[version='>=5.4.0|>=7.3.0']
torchvision -> cudatoolkit[version='>=11.1,<11.2'] -> libgcc-ng[version='>=7.2.0|>=9.3.0']
pytorch -> cudatoolkit[version='>=11.1,<11.2'] -> libgcc-ng[version='>=7.2.0|>=9.3.0']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.9 -> libgcc-ng[version='>=7.3.0']
torchvision -> libgcc-ng[version='>=5.4.0|>=7.3.0']
torchaudio -> numpy[version='>=1.11'] -> libgcc-ng[version='>=5.4.0|>=7.2.0|>=7.3.0']
cudatoolkit=11.1 -> libgcc-ng[version='>=7.3.0|>=9.3.0']

Package _libgcc_mutex conflicts for:
cudatoolkit=11.1 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python=3.9 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
pytorch -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
torchvision -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package libstdcxx-ng conflicts for:
pytorch -> cudatoolkit[version='>=11.1,<11.2'] -> libstdcxx-ng[version='>=7.2.0|>=9.3.0']
pytorch -> libstdcxx-ng[version='>=5.4.0|>=7.3.0']

Package nccl conflicts for:
pytorch -> nccl[version='<2']
torchvision -> pytorch[version='>=0.4'] -> nccl[version='<2']

Package pytorch conflicts for:
torchvision -> pytorch[version='1.1.*|1.2.0+cu92|1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0|>=1.0.0|>=0.4|>=0.3|1.7.1.*|1.3.1.*|1.2.0.*']
torchaudio -> pytorch[version='1.2.0|1.3.0|1.3.1|1.4.0|1.5.0|1.5.1|1.6.0|1.7.0|1.7.1|1.8.0|1.8.1|>=1.1.0']
pytorch

Package cudatoolkit conflicts for:
torchaudio -> pytorch==1.8.1 -> cudatoolkit[version='10.0.*|>=10.0,<10.1|>=10.1,<10.2|>=11.1,<11.2|>=10.2,<10.3|>=11.0,<11.1|>=9.2,<9.3|>=10.1.243,<10.2.0a0|>=9.2,<9.3.0a0|>=10.0.130,<10.1.0a0|9.2.*|>=9.0,<9.1|>=9.0,<9.1.0a0']
torchvision -> pytorch==1.4.0 -> cudatoolkit[version='10.0.*|>=10.1.243,<10.2.0a0|9.2.*|>=8.0,<8.1|>=8.0,<8.1.0a0|8.*|9.*|9.0.*|8.0.*|7.5.*']
cudatoolkit=11.1
torchvision -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=11.1,<11.2|>=10.2,<10.3|>=11.0,<11.1|>=9.2,<9.3|>=9.0,<9.1|>=10.0.130,<10.1.0a0|>=9.2,<9.3.0a0|>=9.0,<9.1.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - cudatoolkit=11.1 -> __glibc[version='>=2.17,<3.0.a0']
  - torchvision -> cudatoolkit[version='>=11.1,<11.2'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.31
```

If a conda env is created with no python packages pre-installed, pytorch will install correctly with python version 3.8.10. However, I want to use the newest python 3.9.

## To Reproduce

1. create conda env with `conda create --name test python=3.9`
2. install pytorch with `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia`

## Expected behavior

pytorch successfully installed without error. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Trying to install 1.8.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): Installation failed
 - Build command you used (if compiling from source): N/A
 - Python version: 3.9.5/3.9.2 both failed
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: RTX3090
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr

**Comment by brando90** [comment]
I am also getting something similar to this...is it due to python 3.9? did you fix this?

https://stackoverflow.com/questions/68010933/unable-to-install-pytorch-on-mac-os-x-from-scratch-due-to-pytorch-package-confli

**Comment by cdeepali** [comment]
This is happening so because `torchaudio` requires `python_abi` which is not available on defaults channel. 
It is available on `conda-forge` though.

The following works:
```
$ conda create --name test python=3.9
$ conda install pytorch torchvision cudatoolkit=11.1 -c pytorch -c nvidia
$ conda install torchaudio -c pytorch -c conda-forge
```

**Comment by brando90** [comment]
Adding the conda-forge channel worked. 
```
conda install pytorch torchvision torchaudio -c pytorch -c conda-forge
```
Why isn't that flag what the official installation on the website asks? It seems really odd that the official install would not work:
```
conda install pytorch torchvision torchaudio -c pytorch
```
is there a reason why the conda-forge channel is not added to the official instructions?

**Comment by cdeepali** [comment]
Yeah, currently the official documentation mentions about using `conda-forge` channel for `CUDA 11.1` only. 

```
NOTE: 'conda-forge' channel is required for cudatoolkit 11.1
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
```

But documentation needs to be updated about `conda-forge` for `py39` as well.

**Comment by seemethere** [comment]
> Yeah, currently the official documentation mentions about using `conda-forge` channel for `CUDA 11.1` only.
> 
> ```
> NOTE: 'conda-forge' channel is required for cudatoolkit 11.1
> conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
> ```
> 
> But documentation needs to be updated about `conda-forge` for `py39` as well.

For linux you can also use the `nvidia` channel to grab `cudatoolkit=11.1` but we've been noticing issues with `torchvision` on python 3.9 (see, https://github.com/pytorch/vision/issues/4076)

**Comment by patrikhuber** [comment]
I have also encountered this today on a fresh conda install, using python 3.9 on Windows, the official installation line `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch` from https://pytorch.org/get-started/locally/ produced the already-posted errors, which was quite confusing.

**Comment by FlameSky-S** [comment]
The problem no longer exists.
