### ISSUE TITLE
Slicing a Subset initialised with a Subset gives error

### ISSUE THREAD

**Issue by TJ-coding** [pytorch/pytorch#59512]
## 🚀 Feature

Sliceable Subset of a Subset

## Motivation
Taking a slice of a subset initialized with a dataset:
```
from torch.utils.data import TensorDataset, Subset
dataset = TensorDataset(torch.tensor([1, 2, 3]))
subset_of_dataset = Subset(dataset , list(range(3)))
print(subset_of_dataset[:])
```
Gives:
```
(tensor([1, 2, 3]),)
```
However, taking a slice of a subset initialized with a subset:
```
from torch.utils.data import TensorDataset, Subset
dataset = TensorDataset(torch.tensor([1, 2, 3]))
subset_of_dataset = Subset(dataset , list(range(3)))
subset_of_subset =  Subset(subset_of_dataset , list(range(3)))
print(subset_of_subset[:])
```
Gives
```
TypeError: list indices must be integers or slices, not list
```
Even though, it can be indexed:
```
from torch.utils.data import TensorDataset, Subset
dataset = TensorDataset(torch.tensor([1, 2, 3]))
subset_of_dataset = Subset(dataset , list(range(3)))
subset_of_subset =  Subset(subset_of_dataset , list(range(3)))
print(subset_of_subset[0])
```
Giving:
```
(tensor(1),)
```
I found this problem when I was working on a real world problem. I had to create a subset of a subset when I had to split a dataset into train and test set with Subset, then further split the train set into train set and validation using torch.utils.data.random_split. This resulted in a Subset of a Subset and gave error when I needed to slice them.

## Pitch

I want to fix / add a new feature that allows slicing of a Subset initialized with a Subset.
I am raising this as a new feature and not a fix since the documentation does not state that you can initialise a Subset with a Subset.

## Additional context

Subset class have two attributes, dataset and indices. The reason why the bug occur is because the dataset can be indexed by a list where as the indices when stored as a list can not be indexed by a list. The issue can be resolved either by stating that the index given in initialisation should be an Integer Tensor rather than a sequence or alternatively, the Class can be changed so that the indices are stored as an Integer Tensor on initialisation.

cc @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Can you do it using `random_split` twice?
```py
train, test = random_split(ds, [100, 10])
train, val = random_split(train, [90, 10])
```
And, if we want slicing supported, we need to have all Dataset supported.

**Comment by TJ-coding** [comment]
Given that you need to slice a SubSet initialised with a SubSet, there are three workarounds that I can think of:
E.g. 
```
d = TensorDataset(torch.tensor([1, 2, 3]), torch.tensor([1, 1, 0]))
s_of_d = Subset(d, list(range(3)))
s_of_s =  Subset(s_of_d , list(range(3)))
```
1. Change the indices of a subset into an integer Tensor or an Integer numpy array
```
s_of_d.indices = torch.LongTensor(s_of_s.indices)
label_frequency = np.bincount(s_of_s[:][-1])
```
2.  Use a for loop
```
label_frequency = np.bincount([i[-1] for i in s_of_s])
```
3. Apply the indices of the subset on the original dataset
```
label_frequency = np.bincount(d[s_of_s.indices][-1])
```
---
But to me, none of the above solutions are as elegant nor pythonic as just a simple slice, especially when it can be done for a Subset initialized with a Dataset. It also kind of feels inconsistent:
```
label_frequency = np.bincount(s_of_d[:][-1])
```

**Comment by ejguan** [comment]
Thanks for providing detailed information about your use case.

Just want to make sure you understand that the following code is working because `TensorDataset` supports slicing or list of indexes as argument for `__getitem__`. And, this behavior may not be expected for other `Dataset` classes.
```py
dataset = TensorDataset(torch.tensor([1, 2, 3]))
train, test = random_split(dataset ,  [2,1])
print(train[:])    # Can be sliced
``` 
If your real DataSet doesn't support them, you may encounter the issue that slicing or indexing by a list of integer for your Dataset instance doesn't work.

But, you are right about consistent behavior for `Subset`. We should make `Subset` pass the list of indexes to `self.dataset` and let `self.dataset` to decide if the list or slice is acceptable.
