### ISSUE TITLE
PyTorch's expansion of the term "CDF" seems to be non-standard

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#59516]
## 🐛 Bug

PyToch docstrings in torch.distributions expand CDF in a nonstandard way. For example, `Distribution.cdf` is described as
>        Returns the cumulative density/mass function evaluated at  `value`.

similar for `Distribution.icdf`.

I would propose to use the common mathematical name [cumulative **distribution** function](https://en.wikipedia.org/wiki/Cumulative_distribution_function) instead.

I could submit a PR, but I wanted to check here first, given that for all the lawyering that the docstrings are subjected to, noone seemed to have objected to this one... until today, that is. :wink: 

cc @fritzo @neerajprad @alicanb @nikitaved @brianjo @mruberry

**Comment by fritzo** [comment]
SGTM, thanks for fixing idiosyncrasies
