### ISSUE TITLE
SPIR-V codegen fails when building on Windows with Vulkan

### ISSUE THREAD

**Issue by ahirner** [pytorch/pytorch#59519]
## To Reproduce

1. Install `VULKAN_SDK` `1.2.176.1`
2. Install `miniconda` `3.8.10`
3. Install build deps `conda install -y astunparse numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses`
4. clone commit `1d9c1c` and `cd  pytorch`
5. build wheel:
```pwsh
$env:USE_VULKAN=1
$env:USE_VULKAN_WRAPPER=0
python setup.py bdist_wheel
```

Build errors because `tools` module is missing. It seems `pytorch` is not added to `PYTHONPATH` in [VulkanCodegen.cmake ](https://github.com/pytorch/pytorch/blob/master/cmake/VulkanCodegen.cmake#L58).
```
Traceback (most recent call last):
  File "D:/a/pytorch-etna/pytorch-etna/pytorch/cmake/../aten/src/ATen/gen_vulkan_spv.py", line 8, in <module>
    from tools.codegen.code_template import CodeTemplate
ModuleNotFoundError: No module named 'tools'
CMake Error at cmake/VulkanCodegen.cmake:72 (message):
  Failed to gen spv.h and spv.cpp with precompiled shaders for Vulkan backend
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:6 (include)
``` 

Build summary:
```
-- ******** Summary ********
--   CMake version         : 3.19.6
--   CMake command         : C:/Miniconda/envs/test/Library/bin/cmake.exe
--   System                : Windows
--   C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe
--   C++ compiler version  : 19.29.30037.0
--   CXX flags             : /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental
--   Build type            : Release
--   Compile definitions   : WIN32_LEAN_AND_MEAN;ONNX_ML=1;ONNXIFI_ENABLE_EXT=1
--   CMAKE_PREFIX_PATH     : C:\Miniconda\envs\test\Lib\site-packages
--   CMAKE_INSTALL_PREFIX  : D:/a/pytorch-etna/pytorch-etna/pytorch/torch
--   CMAKE_MODULE_PATH     : D:/a/pytorch-etna/pytorch-etna/pytorch/cmake/Modules;D:/a/pytorch-etna/pytorch-etna/pytorch/cmake/public/../Modules_CUDA_fix
```

## Expected behavior

Build succeeds.

## Environment
```
OS: Microsoft Windows Server 2019 Datacenter
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.8 (64-bit runtime)
Python platform: Windows-10-10.0.17763-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           haa95532_296  
[conda] mkl-include               2021.2.0           haa95532_296  
[conda] mkl-service               2.3.0            py38h2bbff1b_1  
[conda] mkl_fft                   1.3.0            py38h277e83a_2  
[conda] mkl_random                1.2.1            py38hf11a4ad_2  
[conda] numpy                     1.20.2           py38ha4e8547_0  
[conda] numpy-base                1.20.2           py38hc2deb75_0
```

This is on a `windows-2019` github action runner.  The equivalent error happens on a `Windows 10 Pro` desktop.

## Additional context

This issue seems to be a subset or specific version of #55879.

cc @malfet @seemethere @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
For this particular issue, please see `VulkanCodegen.cmake` in https://github.com/pytorch/pytorch/compare/master...skyline75489:chesterliu/dev/vulkan-on-win?expand=1

**Comment by ahirner** [comment]
Thanks @skyline75489 , can confirm it's the path separator. Although I didn't make it through the entire build, I guess it's good for a tiny PR.

**Comment by ahirner** [comment]
@skyline75489 , I [incorporated](https://github.com/pytorch/pytorch/compare/master...ahirner:vulkan-on-win?expand=1) more of your changes on top of master.

I'm wondering about changes in `flat_hash_map.h`. No matter if `sherwood_v3_table` 's move constructor is explicit or not, I'm running into:
```
..\c10/util/flat_hash_map.h(872): error C2664: 'size_t at::native::vulkan::api::Pipeline::Factory::Hasher::operator ()(const at::native::vulkan::api::Pipeline::Factory::Descriptor &) const': cannot convert argument 1 from 'const U' to 'const at::native::vulkan::api::Pipeline::Factory::Descriptor &'
```
[10_Build PyTorch.txt](https://github.com/pytorch/pytorch/files/6642397/10_Build.PyTorch.txt)


Did you hit a similar problem or did the change solve anything for you?

**Comment by skyline75489** [comment]
@ahirner you need to use /permissive for that file. Or change the name “Hasher” is the template to something else to avoid the compilation error.

**Comment by ahirner** [comment]
Finally got it to compile. It needed a larger machine than github action runners. 
Gonna PR thanks to @skyline75489

**Comment by Blackhex** [comment]
@malfet The issue seems to be resolved. Is there anythign we can do more or can we close it?
