### ISSUE TITLE
error when enable dataparallel

### ISSUE THREAD

**Issue by patkinm** [pytorch/pytorch#5957]
When enable DataParallel on resnet34 from https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
faced with error:
```
****************************************************************************
* hwloc has encountered what looks like an error from the operating system.
*
* object (L3 cpuset 0x00060060) intersection without inclusion!
* Error occurred in topology.c line 870
*
* Please report this error message to the hwloc user's mailing list,
* along with the output from the hwloc-gather-topology.sh script.
****************************************************************************
```
- ubuntu server 16.04 processor AMD AMD Ryzen™ Threadripper™ 1920X (!)
- pytorch 0.3.1b0+2b47480
- from source
- CUDA 9.1 cudnn 7
- Nvidia 1080Ti
- gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by zou3519** [comment]
Could you please provide a script that reproduces that error?

In addition, I'm not sure what hwloc is, but have you reported the error message to their mailing list?
