### ISSUE TITLE
Linking Error:  relocation R_X86_64_32 against `cpuinfo_x86_linux_init' can not be used when making a shared object

### ISSUE THREAD

**Issue by StatML** [pytorch/pytorch#5959]
- OS: Ubuntu 16.04.2
- PyTorch version: a3bd7b2..e3e0c34
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.5.2
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): 5.4.0

> [ 87%] Linking CXX shared library libATen.so
> /usr/bin/ld: /usr/local/lib/libcpuinfo.a(init.c.o): relocation R_X86_64_32 against `cpuinfo_x86_linux_init' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libcpuinfo.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> src/ATen/CMakeFiles/ATen.dir/build.make:2039: recipe for target 'src/ATen/libATen.so.1' failed
> make[2]: *** [src/ATen/libATen.so.1] Error 1
> CMakeFiles/Makefile2:179: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
> make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by ezyang** [comment]
Cc @cpuhrsch

**Comment by cpuhrsch** [comment]
Has cpuinfo been installed somewhere else? PyTorch might pick up a cpuinfo install outside from the submodule. If you’re compiling from source try updating the submodules.

**Comment by apaszke** [comment]
Can we put the submodule path before system library dirs? That would make the build process simpler

**Comment by cpuhrsch** [comment]
The most recent version of cpuinfo should fix this. We have to update the submodule.

**Comment by StatML** [comment]
Hi  @apaszke @cpuhrsch Thanks a lot for your help! I deleted `/usr/local/lib/libcpuinfo.a` and updated the submodule, then the issue was fixed! :)
