### ISSUE TITLE
Where is libtorch archive???

### ISSUE THREAD

**Issue by blackCmd** [pytorch/pytorch#59607]
Where is libtorch archive???

I can't find libtorch 1.6.0..

**Comment by jbschlosser** [comment]
Try this: https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip

**Comment by blackCmd** [comment]
> Try this: https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip

It is only libtorch 1.6.0 cpu version

**Comment by seemethere** [comment]
You can actually access other types like so: where `EXEC_TYPE=cu92` or any other CUDA version we supported for 1.6.0


`https://download.pytorch.org/libtorch/${EXEC_TYPE}/libtorch-shared-with-deps-1.6.0%2B${EXEC_TYPE}.zip`

**Comment by SC-One** [comment]
I want to download `libtorch 1.9` with cuda one version of  `(11.2 = version = 11.5)` or other versions, but I don't know which version of cuda is available for specific torch, so I want the full list of the repos.
How can I access the list?
Thanks.
