### ISSUE TITLE
src/tcmalloc.cc:278] Attempt to free invalid pointer 0x7fc84f022d40 

### ISSUE THREAD

**Issue by dodler** [pytorch/pytorch#5961]
Hi I have ubuntu 16 04
torchvision (0.2.0)
torch (0.3.1)
python 3.6
installed via pip
cuda 8.0
2xk80

I'm trying to do DataParallel over my model,
but this error occures during forward pass 
however if i disable upsample and sigmoid all is working clearly. 

how i init parallel model
`    net = nn.DataParallel(UNet(3, 1).cuda())
`
model forward

` x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)
        x5 = self.down4(x4)
        x = self.up1(x5, x4)
        x = self.up2(x, x3)
        x = self.up3(x, x2)
        x = self.up4(x, x1)
        x = self.outc(x)
        x = self.upsample(x)
        x = self.sigmoid(x)
        return x
`

failes here
`            probs = net(X)
`

however it's all working fine without upsample and sigmoid
am i doing something wrong?

thanks in advance

**Comment by lwye** [comment]
I also came across this problem under the same condition except installing pytorch with anaconda.
My problem occurred when forwarding nn.LSTMCell with cuda(). The cpu mode can work fine.

Is there any solution?

**Comment by ailzhang** [comment]
Hi @lwye  @dodler , could any of you provide an minimal repro example? We can look into it.

**Comment by ezyang** [comment]
Guessing whatever it is, we've fixed it in the meantime. If you have a repro on recent version of PyTorch please feel free to reopen.
