### ISSUE TITLE
inference_mode causes segfault

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#59614]
## To Reproduce

1. Create new, empty conda environment
2. Run ```conda install pytorch cpuonly -c pytorch-nightly```

Run
```
import torch
with torch.inference_mode():
    torch.nn.Linear(9, 64)
```
which results in a segmentation fault.

When run outside of inference_mode context the code succeeds

```
import torch
torch.nn.Linear(9, 64)
```

## Expected behavior

Don't segfault.

## Environment

$ python collect_env.py
/fsx/users/cpuhrsch/conda/envs/nightly20210607/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623049563538/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Collecting environment information...

CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.27

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.4.0-1041-aws-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] torch==1.10.0.dev20210607
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2021.2.0           h06a4308_296
[conda] pytorch                   1.10.0.dev20210607     py3.9_cpu_0  [cpuonly]  pytorch-nightly

## Additional context

I used git's bisect functionality and narrowed it down to https://github.com/pytorch/pytorch/pull/56017
I also confirmed the segfault on a recent (1.10.0.dev20210607-py3.8_0) on my macbook.
I can provide a backtrace if needed, but this should be easily reproduced given the brevity of the snippet, if this bug is legitimate.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7

**Comment by ezyang** [comment]
On the following dev build of PyTorch I did not get any segfault with the minimal repro:

```
Collecting environment information...
PyTorch version: 1.9.0a0+gitcda2fa5
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: 11.0.0 (Red Hat 11.0.0-1.module_el8.4.0+587+5187cac0)
CMake version: version 3.14.0
Libc version: glibc-2.28

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.2.9-240_fbk16_hardened_4245_g53e65cc15fc6-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
    
Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.9.0a0+gitcc7a1e2
```

**Comment by ezyang** [comment]
Repros on Python 3.6.10 though
