### ISSUE TITLE
Bug in torch.quantization.convert (custom mapping) + fix suggestion

### ISSUE THREAD

**Issue by Sonderfall** [pytorch/pytorch#59630]
## 🐛 Bug

The function torch.quantization.convert(model, inplace, custom_mapping) has a bug regarding the custom_mapping management. Indeed, the mapping dict is not well transmitted during the recursive call.

See **Additional context** section for bug localization.

## To Reproduce

1. have a quantizable model
2. `custom_f2o_mapping = {
       "float_to_observed_custom_module_class":{MyCustomLayer : MyObsCustomLayer}
 }`
3. torch.quantization.prepare(model, inplace, prepare_custom_config_dict=custom_f2o_mapping)
4. create a custom mapping like :
`custom_o2q_mapping = {
        "observed_to_quantized_custom_module_class": {MyObsCustomLayer : MyQuantCustomLayer},
    }`
5. call torch.quantization.convert(model, inplace, convert_custom_config_dict=custom_o2q_mapping)
6. the resulting model will keep the MyObsCustomLayer layer ! That is wrong !

## Expected behavior

Every layer matching with the MyObsCustomLayer type should be swapped to a MyQuantCustomLayer type layer

## Environment

 - PyTorch Version : 1.8.1
 - OS : Ubuntu 20.04.2 LTS
 - Pip installation
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 
## Additional context

The error is well identified :
Go at torch/quantization/quantize.py, line 508
` _convert(mod, mapping, True, custom_module_class_mapping)`

Replace with :
`_convert(mod, mapping, True, convert_custom_config_dict)`

And it will fix the bug.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
This is fixed by: https://github.com/pytorch/pytorch/pull/59571, feel free to reopen if the issue persists
