### ISSUE TITLE
trorch.save

### ISSUE THREAD

**Issue by ljc19940403** [pytorch/pytorch#59631]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
When I save the entire model, but I don't want to expose the network code, but others can deduce that.
My tests had to include code for the network structure, which confused me.
Looking forward to your reply.

**Comment by jbschlosser** [comment]
Hey @ljc19940403, please post questions like this on the [PyTorch forums](https://discuss.pytorch.org/) as it's more likely you will get help there.
