### ISSUE TITLE
unexpected sum() of bytetensor

### ISSUE THREAD

**Issue by QIU-Shuo** [pytorch/pytorch#5966]
when use:
torch.eye(4, 4).byte().cuda().repeat(64, 1, 1).sum()
Returns
 0
[torch.cuda.ByteTensor of size () (GPU 0)]

Similarly, 
torch.eye(5, 5).byte().cuda().repeat(64, 1, 1).sum()
 64
[torch.cuda.ByteTensor of size () (GPU 0)]

torch.eye(10, 10).byte().cuda().repeat(64, 1, 1).sum()
 128
[torch.cuda.ByteTensor of size () (GPU 0)]

torch.eye(10, 10).byte().cuda().repeat(64, 1, 1)[0:20].sum()
 200
[torch.cuda.ByteTensor of size () (GPU 0)]

When submitting a bug report, please include the following information (where relevant):
- OS: Ubuntu 17.10
- PyTorch version: 0.4.0a0+7588893
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.3
- CUDA/cuDNN version: 8.0.61/7101
- GPU models and configuration: GTX 1080TI
- GCC version (if compiling from source): 4.8.5

**Comment by apaszke** [comment]
I think we're planning to fix this one soon. Is that correct @gchanan?

**Comment by ngimel** [comment]
That's a regression, BTW, it used to work correctly pre-tensor-variable merge and scalars.

**Comment by apaszke** [comment]
Only if you had a tensor, so I’d say it has always been half broken

**Comment by ragulpr** [comment]
For reference, in 3.0.post4

In [33]: z.sum()
Out[33]: 1000

In [34]: z = torch.ones(1000,10)>0

In [35]: z
Out[35]: 

    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
       ...          ⋱          ...       
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
[torch.ByteTensor of size 1000x10]

In [36]: z.sum()
Out[36]: 10000

In [37]: z.sum(0)
Out[37]: 

 232
 232
 232
 232
 232
 232
 232
 232
 232
 232
[torch.ByteTensor of size 10]

In [38]: torch.__version__
Out[38]: '0.3.0.post4'

**Comment by ngimel** [comment]
Yes, sum over dimensions has always been broken, sum over the whole tensor was ok, sum over variable was not (I'm not sure about the last one, but @apaszke says so)

**Comment by gchanan** [comment]
This has been fixed.
