### ISSUE TITLE
Building without LAPACK causes tests to fail

### ISSUE THREAD

**Issue by Varal7** [pytorch/pytorch#59662]
## 🐛 Bug

When pytorch is built without LAPACK, tests that require LAPACK will fail.
We have the `skipIfNoLapack` that allows for skipping those tests but not all tests are decorated.

## To Reproduce

1. Uninstall LAPACK
1. Build from source
1. `python test/run_test.py`

For example, from `test_ops.py`, the following tests fail:

```
ERROR: test_conj_view_linalg_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_conj_view_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_out_linalg_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_out_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_eager_linalg_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_eager_linalg_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_eager_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_eager_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_jit_linalg_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_jit_linalg_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_jit_svd_meta_complex64 (__main__.TestCommonMETA)
ERROR: test_variant_consistency_jit_svd_meta_float32 (__main__.TestCommonMETA)
ERROR: test_fn_grad_linalg_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_fn_grad_linalg_svd_meta_float64 (__main__.TestGradientsMETA)
ERROR: test_fn_grad_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_fn_grad_svd_meta_float64 (__main__.TestGradientsMETA)
ERROR: test_fn_gradgrad_linalg_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_fn_gradgrad_linalg_svd_meta_float64 (__main__.TestGradientsMETA)
ERROR: test_fn_gradgrad_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_fn_gradgrad_svd_meta_float64 (__main__.TestGradientsMETA)
ERROR: test_forward_mode_AD_linalg_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_forward_mode_AD_linalg_svd_meta_float64 (__main__.TestGradientsMETA)
ERROR: test_forward_mode_AD_svd_meta_complex128 (__main__.TestGradientsMETA)
ERROR: test_forward_mode_AD_svd_meta_float64 (__main__.TestGradientsMETA)
```

## Expected behavior

Tests pass

## Environment
Collecting environment information...
PyTorch version: 1.10.0a0+gite70baf6
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: 9.0.20190721
CMake version: version 3.18.2
Libc version: glibc-2.28

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.2.9-229_fbk15_hardened_4185_g357f49b36602-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] Could not collect
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch-sphinx-theme      0.0.24                    dev_0    <develop>
[conda] torch                     1.10.0a0+git77dde35           dev_0    <develop>

## Additional context

N/A

cc @mruberry @VitalyFedyunin @walterddr @jianyuh @nikitaved @pearu @heitorschueroff @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
Thank you for reporting this issue @Varal7, we'll take a look.

**Comment by IvanYashchuk** [comment]
The tests are failing for the Meta device because the inputs are generated using 'cpu' device first and then transferred to the desired device.
