### ISSUE TITLE
Make some stuff from test/common.py part of lib?

### ISSUE THREAD

**Issue by lucasb-eyer** [pytorch/pytorch#5970]
Some code in [test/common.py](https://github.com/pytorch/pytorch/blob/master/test/common.py) is very useful for writing test for my own high-level pytorch code, especially `TestCase`. But I cannot use it as a library user. It would be nice to have proper testing support as part of PyTorch, it would probably amount to moving some of these into [torch/testing/..](https://github.com/pytorch/pytorch/tree/master/torch/testing).

If it has any significance, tensorflow has proper testing support as part of the library [here](https://www.tensorflow.org/api_guides/python/test).

**Comment by ezyang** [comment]
Yes, I think this is a good idea. Not everything should go in PyTorch but some of it's useful.

The main problem is people are going to want to bikeshed the APIs if you do this. Probably best to tackle things one at a time, for the things that you really, really want.

**Comment by ezyang** [comment]
Most of the stuff now lives in `torch/testing/_internal`.
