### ISSUE TITLE
Windows Azure multi-gpu tests are failing in CircleCI

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#59724]
Logs for the failures look like:
```
...
Submitting build for branch: refs/heads/master
Commit SHA1:  68f74966fcf4c763bd2726e374469b7d9340d537
Submitted bulid: 158497
Bulid URL: https://aiinfra.visualstudio.com/0628bce4-2d33-499e-bac5-530e12db160f/_apis/build/Builds/158497
Waiting for run to start: 158497
Waiting for run to start: 158497
Bulid started:  158497
Bulid status: completed
Bulid result: failed
Retrying... remaining attempt: 1
Submitting build for branch: refs/heads/master
Commit SHA1:  68f74966fcf4c763bd2726e374469b7d9340d537
Submitted bulid: 158498
Bulid URL: https://aiinfra.visualstudio.com/0628bce4-2d33-499e-bac5-530e12db160f/_apis/build/Builds/158498
Waiting for run to start: 158498
Waiting for run to start: 158498
Bulid started:  158498
Bulid status: completed
Bulid result: failed
No more chance to retry. Giving up.
```

see: https://app.circleci.com/pipelines/github/pytorch/pytorch/333280/workflows/2ca83025-8806-4ece-82e9-b4cf78ca09d6/jobs/14012483

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
@seemethere do you mind disabling them in the interim?

**Comment by seemethere** [comment]
> @seemethere do you mind disabling them in the interim?

Done in https://github.com/pytorch/pytorch/pull/59725

**Comment by samestep** [comment]
Possibly caused by https://github.com/pytorch/pytorch/pull/58778?

**Comment by seemethere** [comment]
> Possibly caused by #58778?

I don't think so since the job is triggering, it's failing when attempting to submit a build to azure pipelines

**Comment by seemethere** [comment]
Also doesn't appear as though I have access to the build logs to be able to debug this further,

<img width="1080" alt="Screen Shot 2021-06-09 at 11 35 45 AM" src="https://user-images.githubusercontent.com/1700823/121409931-e39b4780-c916-11eb-8ce8-47e11152eca8.png">

**Comment by seemethere** [comment]
Closing because we already disabled these tests
