### ISSUE TITLE
symeig NaNs in eigenvectors

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#59720]
It may be expected (maybe if matrix is not very symmetric?), but it should be warned in the docs:
```python
import torch
a = torch.load('symeigbug.pt')
print(a.symeig(eigenvectors = True)[1].isnan().any())
# tensor(True)
```
[symeigbug.pt.zip](https://github.com/pytorch/pytorch/files/6625617/symeigbug.pt.zip)

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by IvanYashchuk** [comment]
Hey, Vadim! Thank you for reporting this issue! Your matrix seems to be symmetric, but the problem with the input is that the diagonal entries are all zero, with a few elements that are small, and many off-diagonal elements that are not zero are very close to be zero, they are smaller than `torch.finfo(torch.float32).eps`.
PyTorch calls LAPACK's `syevd` function internally and I think it should work with hollow symmetric matrices, but this particular input is very ill-conditioned.

`a.symeig(eigenvectors=True, upper=True)` doesn't raise error, returns the result with a few NaNs.
`a.symeig(eigenvectors=True, upper=False)` raises an error
```python
RuntimeError: symeig_cpu: For batch 0: the algorithm failed to converge; 80 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```
`torch.linalg.eigh(a, UPLO='U')` doesn't raise error, returns the result with a few NaNs.
`torch.linalg.eigh(a, UPLO='L')` raises an error, but the error message is wrong:
```python
RuntimeError: torch.linalg.eigh: For batch 0: U(27920,27920) is zero, singular U.
```
`torch.linalg.eigh(a.squeeze(0), UPLO='L')` raises an error with the following message:
```python
RuntimeError: torch.linalg.eigh: the algorithm failed to converge; 27920 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.
```
[According to MKL documentation](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines/lapack-least-squares-and-eigenvalue-problem-driver-routines/symmetric-eigenvalue-problems-lapack-driver-routines/syevd.html), the message should be "the algorithm failed to compute an eigenvalue while working on the submatrix lying in rows and columns info/(n+1) through mod(info,n+1)."

Transferring the input to CUDA and calling `symeig` also produces NaNs, MAGMA library is used as a backend which itself for such small input dispatches parts of the computation to LAPACK.
Calling `torch.linalg.eigh` for this input on CUDA doesn't produce NaNs and everything works, this code path uses cuSOLVER library.

**Comment by vadimkantorov** [comment]
Somehow no warnings got printed for this input. I think PyTorch docs should mention all these details (even if it eats the warnings), many new users lack knowledge on constraints on various solvers and their limitations wrt ill-conditioned matrices

**Comment by vadimkantorov** [comment]
E.g. maybe have a section on ill-conditioned input behavior and what types of input are considered ill-conditioned for this particular function

**Comment by vadimkantorov** [comment]
Also, I think producing NaNs by default is a not very good behavior by default (although there is the same problem in ctc_loss). A good way may be `eigh(..., error_out = False)` (or sth like that), especially if checking for this does not add a perf hit...

**Comment by Lezcano** [comment]
That is completely true @vadimkantorov !  These iterative algorithms can fail when for matrices with very small eigengap (\min_{i,j} \lambda_i - \lambda_j). We should definitely report that in the documentation.

**Comment by vadimkantorov** [comment]
And maybe report that failure corresponds to silent production of NaNs, otherwise "failure to converge" or "fail" is quite vague for non-specialist in numerical linear algebra...

**Comment by vadimkantorov** [comment]
A typical usecase is to produce some laplacian, and then do symeig, and with bad hyper-params it's very easy to get an ill-conditioned laplacian, to mentioning these in documentation should be welcomed :)

**Comment by vadimkantorov** [comment]
Maybe even having tests for specific degenerate-cases would be good, and then one can even link to the test source code from the documentation
