### ISSUE TITLE
Windows build logs are 7M a pop

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#5973]
That's pretty big! In contrast, an OS X build log is only 1.3M. Is there a reason they have to be this big?

CC @peterjc123 @yf225

**Comment by apaszke** [comment]
My guess is that it's because of warnings. I remember having to get through thousands of them when looking for the error that failed the build.

**Comment by peterjc123** [comment]
Yes, the major part of them are warnings. And some of them is not fixable. We can hide them using some flags on the compilers.

**Comment by peterjc123** [comment]
The reduced log size after PR #6001 is about 1.2M.
