### ISSUE TITLE
[package] Reintroduce save_source_file API to PackageExporter

### ISSUE THREAD

**Issue by SplitInfinity** [pytorch/pytorch#59737]
#57340 removed the `save_source_file` on `PackageExporter`; we want to add it back.

cc @ezyang

**Comment by bdhirsh** [comment]
Maybe we should add a `module: torch package` GitHub label?

**Comment by SplitInfinity** [comment]
Forgot to mark as triaged, sorry for the trouble everyone.

**Comment by suo** [comment]
https://github.com/pytorch/pytorch/pull/59962
