### ISSUE TITLE
Pytorch is not printing "variable containing:" as it used to before

### ISSUE THREAD

**Issue by svd3** [pytorch/pytorch#5975]
Yesterday I upgraded my pytorch to master, and it has stopped printing the "variable containing:" tag it used to before when you print a variable. I'm attaching a snapshot of my terminal window.
Earlier it used to do
```
a = Variable(torch.zeros(2))
print(a)
# earlier printed
# Variable containing:
# 0
# 0
#[torch.FloatTensor of size (2,)]
```
<img width="559" alt="screen shot 2018-03-23 at 5 30 35 pm" src="https://user-images.githubusercontent.com/25108784/37855980-f89e8920-2ebf-11e8-9ebd-fb1da8255dd0.png">

**Comment by zou3519** [comment]
This is intended behavior: Variables and Tensors are now the same thing!
