### ISSUE TITLE
On Rocm, hasPrimaryContext wrongly identifies what devices have been used

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#59750]
**Whoever ends up closing this issue, please ping me or @ngimel to handle the "TODO: Remove ROCM-specific behavior..." in torch/csrc/autograd/engine.cpp.**

----------------------------------------

This isn't a bug in Pytorch's usage of rocm or cuda, but a quirk of rocm's context tracking that affects Pytorch.

The symptoms are pretty simple. On "actual cuda" we see correct behavior:
```python
>>> a = torch.randn(10).cuda(1)
>>> torch._C._cuda_hasPrimaryContext(1)
True
>>> torch._C._cuda_hasPrimaryContext(0)
False
```

On Rocm @amathews-amd reports
```python
>>> a = torch.randn(10).cuda(1)
>>> torch._C._cuda_hasPrimaryContext(1)
False
>>> torch._C._cuda_hasPrimaryContext(0)
True
```

The rocm example's behavior is strange from an API standpoint, and @jithunnair-amd says he'd like the behaviors of rocm and cuda to align.  Filing so we don't forget to track rocm's status.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport , feel free to edit if this is inaccurate or needs more detail.

**Comment by amathews-amd** [comment]
- Internal ticket: https://ontrack-internal.amd.com/browse/SWDEV-290298 
- Found during PR : https://github.com/pytorch/pytorch/pull/57833 
- Advised @mcarilli  to do aggressive stashing on HIP at https://github.com/pytorch/pytorch/pull/57833/files#diff-c66dfeac2a2da1867233047ec413c7e625644c672d7b38b8ec982f5605923c64R1245 
- Need to fix aggressive stashing once internal ticket is resolved or new functionality is exposed

**Comment by jithunnair-amd** [comment]
@mcarilli @ngimel Hi, we are testing out the fix in ROCm stack for this issue. We'd like to remove the workaround locally and run the appropriate unit tests to confirm the behaviour is correct. Would you be able to point us to the relevant unit test(s) to run to verify the fix on our end?
cc @amathews-amd

**Comment by amathews-amd** [comment]
This issue is already fixed. Please close.

**Comment by jithunnair-amd** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/71146
