### ISSUE TITLE
AttributeError: 'Comment' object has no attribute '_post'

### ISSUE THREAD

**Issue by XuyangPan** [pytorch/pytorch#59777]
## ❓ Questions and Help

I'm using PyTorch 1.6.0 and Python 3.8.3 on Linux/Ubuntu.

I want to read trained model using the command torch.load('*.pth'),  but got the following error :
AttributeError: 'Comment' object has no attribute '_post'

![image](https://user-images.githubusercontent.com/39898699/121476406-33ead600-c9f9-11eb-835f-9a2ec4bf4cb0.png)

cc @mruberry

**Comment by mruberry** [comment]
Hi @XuyangPan, I'm sorry you're having an issue loading a trained model. Do you have a small sample program that we can review which demonstrates this issue? 

AttributeErrors while pickling/unpickling are common and often the result of an error in the program.

**Comment by XuyangPan** [comment]
The problems has been solved.  
Many thanks to you!

**Comment by marksboy** [comment]
> 

Hello, Xuyang. I faced the same issue. May I ask you how you did to solve this problem? 
Thank you.
