### ISSUE TITLE
Efficient mm / mv operations on transposed / conjugated matrices / batches of matrices

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#59785]
At the moment, when we have a non-contiguous matrix of batch of matrices, we instantiate a contiguous copy of it before passing it to BLAS. We can do better as BLAS / LAPACK have flags for the cases when a matrix is transposed / conjugate transposed (see [here](https://www.netlib.org/lapack/explore-html/d6/d30/group__single__blas__level2_gafc92361b74c6d41c7e5afa0aa5d13ec9.html#gafc92361b74c6d41c7e5afa0aa5d13ec9)).

Given the recent work by @anjali411 on conjugate views, we do have a flag that is set whenever a tensor is conjugated. We could add a flag to `is_contiguous` or implement a new function `is_fortran_contiguous` (or `is_column_major_contiguous`? name under discussion).

After that, the plan would be to use all these tools to dispatch the correct flag to each BLAS routine. Note that all this handling would be transparent to the user. The user would just call `matmul` or `@`  and everything would be dispatched correctly automagically.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @anjali411

**Comment by vadimkantorov** [comment]
Isn't similar information contained in memory_format? (and in stateless case it can be deduced from strides, right?)

**Comment by Lezcano** [comment]
What do you mean by "similar information"? And yes, `is_fortran_contiguous` would just swap the last two strides and call `geometry_is_contiguous`.

**Comment by vadimkantorov** [comment]
I mean, I thought that memory_format was sufficient for deducing transposed/not-transposed calls...

**Comment by IvanYashchuk** [comment]
In code that works with LAPACK, it's checked whether the last two dimensions are stored in column-major order. The real Fortran-contiguous array would have the first two dimensions for matrices and the last dimensions for batches (see Julia).
There is no memory_format implemented for neither Fortran-contiguity nor C-contiguous batch + F-contiguous matrices. That's something to improve.

**Comment by vadimkantorov** [comment]
I also have a feeling that memory_format semantics is fusing two different things: 1) actual memory layout, 2) desire for getting output with the same layout

It also seems that the enum (as opposed to a check that would return a bit-field-like result) doesn't scale, hence necessity for channels_last_3d.

Also, there may be use for your new check for `conv_tbc` op (as opposed to channels_last conv_btc)

**Comment by ngimel** [comment]
Related #51750. In most cases, when blas can handle the transpose, we don't call `contiguous` for mm/mv operations, the exception being some batched operations with multiple batch dimensions (because blas can't handle that out of the box), however, I think we do materialize conjugate inputs where we don't need to. Lapack operations are a different matter, but they do expect fortran contiguous inputs, so there's not a lot we can do there.

**Comment by hadaev8** [comment]
@vadimkantorov 
I found this issue because searched by conv_btc
Is conv_btc is something real?

**Comment by vadimkantorov** [comment]
conv_tbc is real, conv_btc is not (but one could also imagine it)
