### ISSUE TITLE
TCPStoreTest.testWatchKeyCallbackWithPrefix Stuck in CI

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#59797]
https://app.circleci.com/pipelines/github/pytorch/pytorch/333644/workflows/97fe57bb-16ac-4234-a86d-88b62153a2c3/jobs/14027443

```
Jun 10 02:27:50 [ RUN      ] TCPStoreTest.testWatchKeyCallbackWithPrefix

Too long with no output (exceeded 1h30m0s): context deadline exceeded
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
cc @H-Huang

**Comment by rohan-varma** [comment]
dup of https://github.com/pytorch/pytorch/issues/61671
