### ISSUE TITLE
[clang-tidy] Host binaries in S3

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#59815]
clang-tidy is the last big missing piece of #55847, to enable it we need a way for devs to easily grab the specific version of clang-tidy we use in CI (with our custom checks and all). We could store these binaries in S3 for Linux / Mac once we have the build going and change `make setup_lint` to download and install them.

It'd also be nice for clang-tidy to be a statically built binary just so we can be sure that once downloaded onto the right OS/arch it can be run without issue (so long as the binary size is reasonable). LLVM builds clang-tidy dynamically by default and there doesn't seem to be a simple way to turn on a static build so this is something we'll have to figure out. Once that's done we can build statically in the clang-tidy Docker image and `docker cp` it out and upload to S3.

**Comment by zhouzhuojie** [comment]
when we run clang-tidy locally, instead of the static binary, can we just use docker run and mount a volume of the current code instead? Looks like that can be even closer to what the CI is running

**Comment by samestep** [comment]
> when we run clang-tidy locally, instead of the static binary, can we just use docker run and mount a volume of the current code instead? Looks like that can be even closer to what the CI is running

@zhouzhuojie I'm sure you've already seen this, but I believe https://github.com/pytorch/pytorch/issues/55847#issuecomment-859942197 applies here as well.

**Comment by driazati** [comment]
this is done now and hooked up to the tooling
