### ISSUE TITLE
In input_buffer.cpp, accumulate uses storage().use_count()

### ISSUE THREAD

**Issue by Varal7** [pytorch/pytorch#59828]
## 🐛 Bug

In `accumulate` https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/input_buffer.cpp#L23, the check whether it is safe to do addition in place uses `var.storage().use_count()`, but we (also?) need to check whether `var.use_count() == 1`.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano

**Comment by ezyang** [comment]
Yes I think I agree. Send us a PR.

**Comment by soulitzer** [comment]
Looks like there is already one

**Comment by albanD** [comment]
Yes this is already fixing this: https://github.com/pytorch/pytorch/pull/59817
