### ISSUE TITLE
Disable cuDNN persistent RNN on A30

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#59829]
There seems to be an issue (similar to #49534) on A30 due to cuDNN persistent RNN algos depending on specific hardware capabilities. For now, it seems a reasonable approach is to simply tack on another check in RNN.cpp : https://github.com/eqy/pytorch/blob/4a67e884df253d6ab2345e3da474a7469d17ec40/aten/src/ATen/native/cudnn/RNN.cpp.

The long term solution is to wait for cuDNN to implement hardware identification/dispatching for algos on these cases.

CC @ptrblck @xwang233 @ngimel 

cc @csarofeen @ptrblck @xwang233

**Comment by ptrblck** [comment]
A workaround would also be to check the SM count and let other sm_80 devices such as A100 use the persistent RNN algos as:
```
} else if (prop->major >= 8 && prop->multiProcessorCount >= 98) {
```
This was tested on an A100 directly as well as in "full MIG mode" (which is why the sm_count is checked for >=98).

**Comment by ngimel** [comment]
Sure, please submit a PR with the fix!
