### ISSUE TITLE
[RFC] PyTorch Training and Inference for Sparse Models

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#59835]
## 🚀 Feature
---

In this doc we are requesting comments for the implementation of the sparsification flow as part of architecture optimization namespace (`torch.ao`)

with: @raghuramank100 @dskhudia @kimishpatel @kazhou

# Motivation

We present a workflow for training/preparing sparse models and mapping them into efficient kernels for fast inference. This workflow aims to be flexible (i.e you can customize how you want to train a sparse model) and composable (sparsity can plug and play with existing training and with quantization). We are looking for feedback on 

1. Is this workflow suitable for your needs? 
2. Is this sufficient for creating sparse and quantized models?
3. Are the operators that we plan to support a good match for what you need?

This document describes the flow for the fast inference using sparse kernels in pytorch. This is motivated by:

1. Sparsity is a well known technique that can provide significant speedup during inference on server, mobile and GPUs (A100) with kernels optimized for sparsity.
2. Tensorflow supports sparsity: TF[ training support](https://blog.tensorflow.org/2019/05/tf-model-optimization-toolkit-pruning-API.html), with sparse fp32 and quantized inference support for mobile in TFLite 
3. Custom hardware support for sparsity is expanding.
4. Internal experiments on NLP and recommendation models show the benefits of sparsity for faster inference, with kernel level speedups of up to 2x on mobile devices with 75% sparsity. For actual models, the speedups observed are on the order of 20%.

## Goals

The main purpose of this document is to describe the workflow for users to be able to train models with weight sparsity and obtain fast inference with optimized kernels. Specifically, we will describe:

1. User facing APIs supporting end to end workflow for training and inference with sparse models.
2. APIs and kernels for faster inference and compressed model sizes.
3. Integration of sparsity with pytorch stack

Note that while the training APIs for sparsity are general and support flexible sparsity patterns for weights, the inference kernels are optimized for specific block sparsity patterns.

# Sparsity Stack Overview

![image](https://user-images.githubusercontent.com/4216323/121599675-4284bd80-c9f8-11eb-8415-080ab525d9a0.png)

Vertically, the sparsity framework is split into python and c++. Most of the Python code is user-facing API, while the C++ code the kernels and ops.  Note that currently, sparse operations specified here are supported only for sparse weights and dense activations. We do not support sparse activations. 

## User Facing APIs

There are three user facing APIs for sparsity:

*   **torch.ao.sparsity** -- model transformation utilities
    *   **torch.ao.sparsity.sparsifier** -- Primary class for model transformation
    *   **torch.ao.sparsity.scheduler** -- Class for modifying the Sparsifier configuration during training
*   **torch.ao.nn.sparse** -- subclasses of `nn.Module`[Support sparse inference]
    *   Linear -- Sparse Weights and Dense Activations, all in fp32
    *   ConvXd -- TBD
*   **torch.ao.nn.sparse.quantized**
    *   Linear -- Sparse and quantized weights with quantized activations
    *   ConvXd
*   **torch.ao.nn.sparsity** -- subclasses of `nn.Module`[Support sparsity workflow]
    *   fakeSparse -- Fake sparsity module for modeling sparsity during training
*   **torch.ao.nn.sparse.functional** -- stateless implementations of the sparse layers

### Sparsifier Design

In the simplest case, invoking sparsity is as simple as:

```python
Model = myModelClass()
sparsity_config = [{'module' :...}, {'module' :...}]

# Create the sparsifier and specify which modules get sparsified
sparsifier = TheSparsifierClass(sparsity_config)
# Prepare the model, insert fake-sparse ops for training
sparsifier.prepare(model)
def train_one_epoch(...):
    for input, target in dataset:
       optimizer.zero_grad()
       output = model(input)
       loss = loss_fn(output, target)
       loss.backward()
       optimizer.step()
       # Update masks
       sparsifier.step()

for epoch in range(num_epochs):
   train_one_epoch()

# Finally, when training is done, convert for inference with sparse kernels
sparsifier.convert(model)
```

Broadly, the design for sparsity follows the implementation of optimizers in pytorch. This is because:

1. Sparsity operates only on weights of a model, just like optimizers.
2. In contrast to quantization, sparsity mask calculation may not be local. Having a single sparsifier object allows for global information to be used for sparsity mask calculation.
3. Sparsity mask computation can depend on both gradients and weights. 

### Sparsifier Requirements

1. **Composable** support for sparsity: Models can be sparsified with or without quantization. 
2. **Configurable** support: Granularity of sparsity, sparsity level, metrics to determine how weights are sparsified needs to be user configurable with good defaults
3. **Training-Aware/Post Training support**: Sparsity needs to be supported for both post training and training modes, with the expectation that training is typically needed for acceptable accuracy tradeoff.
4. **Local/Global Sparsity Support:** The level of sparsity in a tensor can depend on local statistics (i.e the tensor itself or activations that operate on the tensor) or global statistics (tensors anywhere in the network) or gradients.
5. **Eager and FX support:** Support for sparsity in both eager and FX workflows.

### Design Choices

There are multiple design choices that a user faces during the sparsity studies. As a platform, we will provide support for the following options

Option | Supported Design Choices
-- | --
Sparsity Granularity (Training) | <li>Arbitrary</li><li>2:4 structured-sparse</li>
Sparsity Granularity (Inference) | <li>1x4 for x86 CPU</li><li>1x4, 8x1 for mobile</li><li>2:4 structured-sparse for GPU (s.a. NVidia A100 sparsity)</li>
Sparse Matrix Update Scheme | <li>In-place</li><li>Non in-place (Out of place)</li>
Sparsification Scope | <li>Local</li><li>Global</li>
Tensors used for mask calculation | <li>Weights</li><li>Gradients</li><li>Activations*</li>

_* The sparsification targets are always the weights, meaning during the inference only the weights are sparsified._

In addition to the options above, we support the sparsity **scheduler**, which makes sure the sparsity mask updates/calculations are flexible.

#### Granularity

*   Granularity of sparsity (block size) is dictated mainly by the underlying hardware on which inference is performed. Our goal is to make this completely flexible for training. For inference we plan to support:
    *   1 x 4 [out features/channels, in features/channels] for x86 CPU. Any multiple of 1 x 4 in either or both dimensions, for example, 2 x 4 or 1 x 8 or 2 x 8, will also work. 
    *   8x1 for ARM CPU
*   For the NVidia Sparsity support, granularity m:n means “m out of n elements in a tensor row are set to zero”. Specifically for A100 devices, it is 2 out 4.

#### Sparse Matrix Update

*   In-place option updates the sparse tensor by performing <img src="https://render.githubusercontent.com/render/math?math=W=W\cdot Mask">, where  <img src="https://render.githubusercontent.com/render/math?math=W"> is the tensor to be updated, and the <img src="https://render.githubusercontent.com/render/math?math=Mask"> is the sparsity mask. Once the tensor <img src="https://render.githubusercontent.com/render/math?math=W"> is updated, the sparse values are zeroed-out.
    *   **Pros**: Requires only one copy of the sparse tensor to be stored (+ mask)
    *   **Cons**: Once a mask is applied to a weight, it is zeroed out, all past history is lost. These weights cannot regrow.
*   Non in-place updates don't modify the tensor directly, but perform the following:
    <img src="https://render.githubusercontent.com/render/math?math=W'=W\cdot Mask">
    <img src="https://render.githubusercontent.com/render/math?math=dW'=dW\cdot Mask">

    *   **Pros**: The original tensor is preserved (the masked elements are not updated via backprop). Weights can regrow if the mask changes. 
    *   **Cons**: In addition to the unmasked weights (W), the masked weights (W’) are computed and resident in memory for forward/backward computations.

#### Sparsification Scope

The sparsification scope identifies the scope in which the mask is computed.

*   **Local scope** implies that the sparsity mask is only computed with respect to the layer statistics.
    *   **Pros**: Simple mask computing
    *   **Cons**: Potentially sub-optimal accuracy vs sparsity tradeoff. 
*   **Global scope** means that the sparsity statistics are not bounded by a single layer, but can span over multiple layers if needed.
    *   **Pros**: No need for per-layer thresholds. The tensor statistics is shared across layers, and normalization is used across layers to allow for it.
    *   **Cons**: Increased complexity when computing the masks.

#### Tensors used for mask calculation

 For sparsity, we need to compute an importance score for every connection, i.e weight in the model.

*   **Weights**:  Use weight magnitude as a metric to determine which weights can be sparsified. This method is the simplest for inference as the weight tensors are constant.
*   **Gradients**: Compute importance based on both weights and gradient norms.
*   **Activations**: In some research papers, the norm of the activations that are applied with the weight of interest are used to compute the importance score.

For all training workflows, users can invoke sparsity and control mask calculation at different epochs.

### How to use a sparsifier

To use `torch.ao.sparsity` you have to construct a sparsifier object that will hold the current state and will update the mask and the parameters (weights).

#### Constructing

To construct a sparsifier you have to give it the parameters that will be sparsified. You also might want to give it the sparsification parameters, such as block pattern, update scheme, etc.

For example, the simplest way to use a sparsifier is shown below. _Note: `TheSparsifierClass` is just an example name. See the "Algorithms" section for real sparsifiers._

```python
# Use the sparsifier with the predefined config
sparsity_config = [
  {'module': model.linear1, 'sparsity_level': 0.8, 'sparsity_pattern': [1, 4], 'zeros_per_block': 4, 'inplace': True},
  {'module': model.linear2, 'sparsity_level': 0.7, 'sparsity_pattern': [2, 4], 'zeros_per_block': 4, 'inplace': True},
]
sparsifier = TheSparsifierClass(sparsity_config)
```

```python
# Use the sparsifier with default arguments
sparsity_config = [
  {'module': model.linear1, 'sparsity_level': 0.8, 'sparsity_pattern': [1, 4], 'zeros_per_block': 4, 'inplace': True},
  {'module': model.linear2},
]
sparsifier = TheSparsifierClass(sparsity_config, sparsity_level=0.7, sparsity_pattern=[2, 4], zeros_per_block=4, inplace=True)
```

The exact arguments for the sparsifier will be defined by specific implementation of the different sparsifiers. The arguments in the example above would represent the following:

*   `sparsity_level`: Target level of sparsity that needs to be achieved. 
*   `sparsity_pattern`: The shape of the sparse block
*   `zeros_per_block`: Number of zeros per sparse block.
*   `inplace`: Inplace weight updates, without saving an auxiliary data structure for the mask

#### Sparsifier Config

The configuration of the sparsifier is provided as a list, with each element representing the configuration for a specific module. The elements in the list could be:

1. torch module (instance of torch layer): The sparsification arguments will be inferred from the default arguments
2. Dict: This might include the sparsification parameters that apply to this module only. Note: the dicts MUST have a ‘module’ key that map to the layer that will be sparsified.

```python
sparsity_config = [
    model.linear1,               # Will use default sparsity parameters
    model.linear2,               # Will use default sparsity parameters
    {'module': model.linear3},   # Will use default sparsity parameters
    {'module': model.linear4,
     'sparsity_level': 0.9,
     'sparsity_pattern': [1, 4],
     'zeros_per_block': 4},
]
sparsifier = TheSparsifierClass(sparsity_config,
                                sparsity_level=0.7,
                                sparsity_pattern=(1, 8),
                                zeros_per_block=4)
```

#### Preparing a model

The first step for sparsifying the model is to insert operations for masking the weights of the model. This is done by the prepare step. 

If the sparsifier implementation requires keeping the unmasked weights, masked weights are computed from the original weights and the mask. If not, the weights are used as is without any modifications. After this step the forward and backward passes include the effect of sparsity in computations. 

```python
model = TheModelClass()
sparsifier = TheSparsifierClass(sparsity_config, sparsity_level=0.99) # Change this part
sparsifier.prepare(model)
optimizer = TheOptimizerClass(model.parameters(), lr=1e-3)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
    sparsifier.step()
```

#### Taking a sparsification step

All sparsifiers implement a `step()` method that updates the mask with the logic being determined by the sparsifier implementation. The step method does the following:

1. Computes the mask for the weights
2. If the weights are updated in-place, i.e the masked elements of the weight matrix are zeroed out, this method also applies the mask to the weights.

```python
optimizer = TheOptimizerClass(model.parameters(), lr=1e-3)
sparsifier = TheSparsifierClass(sparsity_config, sparsity_level=0.99)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
    sparsifier.step()
```

**NOTE:** The optimizer `step()` method has to be called before the sparsifier `step()`. This ensures that in-case weights are updated in-place, masked weights do not re-grow due to gradient accumulation.

#### Converting the model

The model conversion is the last step, and is done using the sparsifier instance.

```python
from torch.ao.sparsity import convert
sparse_model = sparsifier.convert(model)
```

Convert replaces the floating point operators with the sparsified operators. In addition, convert applies the mask to the dense weights and packs them as required by sparse kernels for efficient inference. Note that depending on the sparsity level, convert can choose to use dense kernels if no speedup is expected.

#### Saving/Loading a sparsifier 

The sparsifier can be saved and loaded using the `state_dict`. Analogous to optimizers, sparsifier state dict only contains parameters relevant to the sparsifier. Weights and masks are part of the model and are stored as part of the model state dict.

Notice that because the `model.linear2` had the parameters set explicitly, we also save the parameters separately.

To save/load the sparsifier you can use `torch.save` and `torch.load`:

```python
torch.save({
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'sparsifier_state_dict': sparsifier.state_dict(),
    'loss': loss,
    ...}, PATH)

model = TheModelClass(*args, **kwargs)
optimizer = TheOptimizerClass(*args, **kwargs)
sparsifier = TheSparsifierClass(*args, **kwargs)

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
sparsifier.load_state_dict(checkpoint['sparsifier_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']
```

### Writing your own sparsifier

To write a custom sparsifier one could inherit from the `BaseSparsifier` and implement some of the methods. For example, if implementing a sparsifier that computes the mask depending on some predefined threshold:

```python
class HardThresholdSparsifier(torch.ao.sparsity.Sparsifier):
    def __init__(self, threshold, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.threshold = threshold

    def update_mask(self, group):
        mask = group['mask']
        weight = group['param']
        mask[weight < self.threshold] = 0
        group['mask'] = mask

    def step(self):
        if self.enable_mask_update:
            for group in self.module_groups:
                self.update_mask(group)
        super().step()
```

It is the responsibility of the base class to call the `self.update_mask` when appropriate.

### Scheduler

The sparsity scheduler is used to control the update of the sparsification parameters. The scheduler would control:

*   Sparsity threshold levels
*   Frequency of mask calculation
*   Frequency of mask update to weights

For example

```python
optimizer = TheOptimizerClass(model.parameters(), lr=1e-3)
sparsifier = TheSparsifierClass(per_module_config)
sp_scheduler = TheSchedulerClass(sparsifier, init_sr=0.1, goal_sr=0.99, last_epoch=-1)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, ...)

for epoch in range(EPOCHS):
    for input, target in dataset:
        optimizer.zero_grad()
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()
        sparsifier.step()

    sp_scheduler.step()
    lr_scheduler.step()
```

Notice in the example above the sparsity level will be controlled by the scheduler.

#### Writing your own scheduler

To write a custom sparsity scheduler, one must inherit from the `BaseScheduler`, and implement the `get_sl` method

```python
class LinearIncrementScheduler(torch.ao.sparsity.Scheduler):
    """Increments the level of sparsity until reached a max"""
    def __init__(self, increment, max_sparsity=1.0, *args, **kwargs):
        super().__init__(self, *args, **kwargs)
        self.increment = increment
        self.max_sparsity = max_sparsity

        self.increment = [self.increment] * len(self.sparsifier.module_groups)
        self.sparsity_levels = self.base_sl

    def get_sl(self):
        super().step()  # Call this to increment counters. No scheduling is done in the base class
        for idx in range(len(self.increment)):
            self.sparsity_levels[idx] += self.increment
            self.sparsity_levels[idx] = min(self.sparsity_levels[idx], self.max_sparsity)
        return self.sparsity_levels
```

The example above shows the scheduler incrementing the level of sparsity at every call to the `step`. Notice that the only method that needs to be implemented is the `get_sl` which returns a list of floats representing the new level of sparsity.

### Sparsity Workflows with Quantization

So far, we looked at sparsity in isolation.  Here we look at how the sparsity flow can be combined with the quantization. Refer to the examples below

#### Post Training Sparsity and Quantization

In this simplest case, the model is sparsified and quantized post training. Note that the sparsifier is first applied to the model. This is needed to ensure that the dynamic ranges for activations are estimated correctly for quantization. Also note that the convert method for the sparsifier will convert modules to the required kernels based on user configuration: sparse, sparse+quantized or quantized.

```python
model.qconfig = tq.default_qconfig
sparsifier = TheSparsifierClass(per_module_config)
sparsifier.prepare(model)
# We want to call the sparsifier first, so that quantized model is calibrated correctly
sparsifier.step()

# Now we can prepare, calibrate, and convert
prep_model = tq.prepare(model)
prep_model(calibration_data)

# The sparsifier is aware of the quantization kernel, and decides which layers use what backend [Sparse/Quantized/Sparse + Quantized]
converted_model = sparsifier.convert(prep_model) 
```

#### QAT + Sparsity

Similarly, for quantization and sparsity aware training, we first insert fake-quants to model quantization during training. This is followed by the sparsifier prepare call, which inserts fake-sparse operators. The recommended sequence is to have fake-sparse operators precede fake-quantization operators and that is achieved by the sequence below:

```python
sparsifier = TheSparsifierClass(per_module_config, target_ratio=0.1, block_pattern=[1, 4], local=True)
model = sparsifier.prepare(model)
model = tq.prepare_qat(model, qconfig_dict)
# Sparsifiers prepare function inserts fake-quant+fake-sparse operators to the weights
# Fake Quant + Fake Sparse operations are also fused.
for epoch in range(EPOCHS):
    for input, target in dataset:
        optimizer.zero_grad()
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()
        sparsifier.step()
# Similar to PTQ flow, a single call to convert is all that is needed.
sparsifier.convert(prep_model)
```

## Backend

We plan to create ops in the separate name-spaces **_torch.ops.sparse and torch.ops.sparse_quantized._** The operators here are not user facing and are accessed via modules. 

We plan to start by supporting sparsity for server (x86) and mobile (ARM) CPU backends.  At a later point, we may support GPU inference too. We plan to support both fp32 sparsity and quantized sparsity kernels, with priority given to quantized sparse kernels as they provide the most speedup. This requires interfacing with three different backend libraries: QNNPACK (ARM, quantized), XNNPACK (ARM float), FBGEMM (x86- float and quantized)

### Supported sparsity patterns

If there are multiple patterns that are supported, we should be able to dispatch based on the current level. Note that what is listed here is the smallest granularity of sparsity that is supported. Any multiple of the pattern size here will also work.

Pattern | FBGEMM (fp32) | FBGEMM (quantized) | QNNPACK (quantized) | XNNPACK (fp32)
-- | -- | -- | -- | --
1x1n | YES | &nbsp; | &nbsp; | &nbsp;
1 x 4n | &nbsp; | YES | YES | YES
8n x 1 | &nbsp; | &nbsp; | YES | NO
16n x 1 | &nbsp; | &nbsp; | &nbsp; | YES

##### FBGEMM Sparsity Support

We have implemented sparse-matrix dense-matrix multiplication (SpMM) kernels for both 32-bit floating-point (FP32) data type and 8-bit integer (INT8) computation for serving pruned models efficiently on x86-64 CPUs in the FBGEMM library. For the tested matrix multiplication shapes, with an 80% sparsity in the weight matrix, the SpMM kernels can improve the computation performance by 1.08~7.06x and 1.78~15.65x for FP32 and INT8, respectively. These shapes are gathered from various models used in production. An optimized INT8 sparse-matrix dense-vector multiplication (SpMV) is also implemented and achieves 1.62~3.10x speedup on the tested shapes. 

SpMM and SpMV kernels both worked on packed weight data. Since weight is constant during inference, we can pack it once and use it multiple times thus allowing us to perform optimized compute. For packing the data, we use a variation on the popular sparse matrix format called Compressed Sparse Row (CSR). We use Tiled Block CSR format for packing the weight matrix. Main improvement over CSR is storing non-zero block indices instead of each non-zero element index and tiling in one of the matrix dimensions for efficient cpu cache use during computation. 

Main restriction on sparsity granularity comes from the use of vector instruction VPMADDUBSW on current generation of processors (up to Skylake microarchitecture) and VPDPBUSDS instruction on recently released and upcoming generation of processors (Cascade Lake onwards) [8]. These instructions work on int8 data and do horizontal operations on the SIMD vectors in groups of 4. Hence, the restrictions on sparsity granularity to be 4 in input features dimension.

##### QNNPACK Sparsity support:

At the moment qnnpack support dynamically quantized sparse linear operator. Supported sparsity pattern is 8x1 and 1x4. Operator does weight prepacking in block CSR format much like FBGEMM. Expected activation format is batch x output_features. Internally, operator prepacks activation in custom format such that 8 rows of activations are transposed and packed together. Specific packing format, for 8x1 sparsity, is N/8,C/4,4c,8n, where N/n=batch dimension and C/c= output features dimension.

At 70% sparsity, for 1x4 sparsity we observed speedup of about 60% speedup. At same sparsity level for 8x1 pattern we observed about 3x speedup. Benchmarking was done for various shapes we had observed in the models of interest where batch size was relatively small.

# Prioritization

1. Support for sparse kernels with static and dynamic quantization, no fp32 sparsity support.
2. Support for local sparsity first.
3. Support for sparsity with quantization aware training.

# References

1. The State of Sparsity in Deep Neural Networks, Trevor Gale, Erich Elsen, Sara Hooker[ https://arxiv.org/pdf/1902.09574.pdf](https://arxiv.org/pdf/1902.09574.pdf)
2. What is the state of neural network pruning?[ Davis Blalock](https://arxiv.org/search/cs?searchtype=author&query=Blalock%2C+D),[ Jose Javier Gonzalez Ortiz](https://arxiv.org/search/cs?searchtype=author&query=Ortiz%2C+J+J+G),[ Jonathan Frankle](https://arxiv.org/search/cs?searchtype=author&query=Frankle%2C+J),[ John Guttag https://arxiv.org/abs/2003.03033](https://arxiv.org/search/cs?searchtype=author&query=Guttag%2C+J)
3. To prune, or not to prune: exploring the efficacy of pruning for model compression, Suyug Gupta,[ https://arxiv.org/pdf/1710.01878.pdf](https://arxiv.org/pdf/1710.01878.pdf)

cc @brianjo @mruberry @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by mruberry** [comment]
cc @cpuhrsch

**Comment by jianyuh** [comment]
This is awesome!
- Do you have the rough timeline on adding this support?
- For the potential GPU inference support, how will this proposal interact with the sparsity support provided by TensorRT 8.0?

cc @jiecaoyu @jspark1105 .

**Comment by z-a-f** [comment]
>     * Do you have the rough timeline on adding this support?
Hopefully will land asap: https://github.com/pytorch/pytorch/pull/59771

>     * For the potential GPU inference support, how will this proposal interact with the sparsity support provided by TensorRT 8.0?
We will add support nVidia-style sparsity, that is the 2-out-of-4 50% block sparsity.

**Comment by HDCharles** [comment]
@jcaip is this workstream complete or are there new updates?
