### ISSUE TITLE
Mnist did not operate at GPU MODE with libtorch1.8.1+CUDA11.1+RTX3090 in Win10

### ISSUE THREAD

**Issue by yoshihingis** [pytorch/pytorch#59845]
## 🐛 Bug

Mnist did not operate at GPU MODE with libtorch1.8.1+CUDA11.1+RTX3090 in Win10

## To Reproduce

1.I downloaded libtorch-win-shared-with-deps-1.8.1+cu111.zip and unzipped it.
2. I made the project file with libtorch1.8.1 and CUDA11.1 and Visual Studio2019.
3. I linked libs at additional dependency libs 
     c10.lib  ,c10_cuda.lib,torch.lib,torch_cpu.lib,torch_cuda.lib,
    -INCLUDE:?warp_size@cuda@at@@YAHXZ.

4.I built it ,But Link error was did as below 
![スクリーンショット (4)](https://user-images.githubusercontent.com/18341725/121612836-32bbb680-ca96-11eb-93a4-6c8ba8dc68a7.png)
 
5.So I deleted  -INCLUDE:?warp_size@cuda@at@@YAHXZ from VS2019.
   I could build exe file ,but the mnist did at CPU mode ,not at GPU mode as blow.
![スクリーンショット (5)](https://user-images.githubusercontent.com/18341725/121613064-abbb0e00-ca96-11eb-8a50-cd2c9bf013c6.png)
![mnist_cpu](https://user-images.githubusercontent.com/18341725/121613072-aeb5fe80-ca96-11eb-9ae4-4422ae794fae.jpg)

## Expected behavior
 1. I want to to operate the mnist at GPU mode.
 2. Is the Link -INCLUDE:?warp_size@cuda@at@@YAHXZ. not need ?
 3.  I found URL  https://github.com/pytorch/pytorch/issues/54131.
      I added the LINK  /INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z 
    But Link error were did as below.
![スクリーンショット (3)](https://user-images.githubusercontent.com/18341725/121613469-8549a280-ca97-11eb-9dc9-e65f43cfe4ed.png)

## Environment
Visual Studio Community2019 16.10.1
Windows10 Pro build 21H1
GPU: ZOTRAC Geforce-RTX3090
GPU driver :Geforce GamReady driver 466.77
Cuda11.1-45681-win.exe (installed)
Libtorch1.8.1   libtorch-win-shared-with-deps-1.8.1+cu111.zip
mnist.cpp (it was downloaded from https://github.com/pytorch/examples/tree/master/cpp/mnist)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
Have you tried use the library with CMake? There's a `CMakeLists.txt` right at the example mnist page you posted.

**Comment by mszhanyi** [comment]
@yoshihingis please refer https://github.com/pytorch/pytorch/issues/54131#issuecomment-800904255 if you are using visual studio to construct your project. The link option has changed since cuda11.1.
It won't be an issue if you could use CMake

**Comment by yoshihingis** [comment]
Dear skyline75489

Thank you for your advice.

I made VS19 project by using the CMake .

I added  the libs at Link as below.
Libtorch1.8.1's mnist operated by GPU Mode.

c10.lib
c10_cuda.lib
torch.lib
torch_cpu.lib
torch_cuda.lib
torch_cuda_cu.lib
torch_cuda_cpp.lib
-INCLUDE:?warp_size@cuda@at@@YAHXZ
-INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z
