### ISSUE TITLE
Incremental build isn't supported on Windows in fact.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#59859]
## 🐛 Bug

Build Source code with ninja is officially supported. 
But due to Ninja issue https://github.com/ninja-build/ninja/issues/1976, the incremental build isn't supported on Windows.
So, it rebuilds all code in fact if we rerun ` python setup.py install ` on Windows

So far, we can use sccache to accelerate the rebuild.
With nothing changed, it still takes 7 minutes to rerun` python setup.py install ` for CPU build on SSD 
For HDD, it takes about 20 minutes

## To Reproduce

1. clone pytorch source code on windows
2. build it
3. rerun 'python setup.py install' to rebuild.

## Expected behavior
The edit and compile cycle on windows doesn't take so much time.
For small change in leaf node, rebuild should be finished as soon as Linux.

## Additional context
From the exception message in #59688, I think the root cause is that ninja fails to parse Visual C++ compiler option when rebuilding.

cc @malfet @seemethere @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by peterjc123** [comment]
Looking into the ninja_deps uploaded by @mszhanyi, isn't it just because Ninja fails to detect the dependencies for the objects generated by the RC compiler since it doesn't support `/showIncludes`? So, the possible actions for this problem are:
1. Provide the option `/showIncludes` for the RC compiler at the MSFT side
2. Ignore RC file dep generation at the Ninja side
3. Filter unintended options in the dep file at the PyTorch side

**Comment by peterjc123** [comment]
I figured out that by using `set(CMAKE_NINJA_CMCLDEPS_RC OFF)` in CMake, it defers the RC stuffs to the RC compiler instead of writing them into the ninja rules, thus should fix the problem.

**Comment by mszhanyi** [comment]
I just want to know more details. [grpc](https://github.com/grpc/grpc) has protobuf submodule too, it uses cmake+ninja too.
Do you know why it can rebuild on Windows without  `set(CMAKE_NINJA_CMCLDEPS_RC OFF)`

**Comment by peterjc123** [comment]
> I just want to know more details. [grpc](https://github.com/grpc/grpc) has protobuf submodule too, it uses cmake+ninja too.
> Do you know why it can rebuild on Windows without `set(CMAKE_NINJA_CMCLDEPS_RC OFF)`

I will have a try on grpc when I have time.
