### ISSUE TITLE
pytorch1.6 can not use torch.jit.load() to load model which save in pytorch1.7 

### ISSUE THREAD

**Issue by Feywell** [pytorch/pytorch#59866]
## To Reproduce

1. use torch.jit.save() a pt model in pytorch1.7 (which model use ConvTranspose2d)
2. use torch.jit.load() the model.

The erro messages:
> 
>   cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
> RuntimeError: 
> 
> aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
> Expected at most 12 arguments but found 13 positional arguments.
> :

> Serialized   File "code/__torch__/torch/nn/modules/conv.py", line 11
>     argument_1: Tensor) -> Tensor:
>     _0 = self.bias
>     input = torch._convolution(argument_1, self.weight, _0, [1, 1], [0, 0], [1, 1], False, [0, 0], 1, False, False, True, True)
>             ~~~~~~~~~~~~~~~~~~ <--- HERE
>     return input
> class ConvTranspose2d(Module):

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: python3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 
 - Any other relevant information:

## Additional context

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi Feywell, 

This is a known issue that has been fixed in 1.9. Unfortunately, the fix cannot be backported to 1.6 or 1.7. Please upgrade PyTorch to resolve this issue.
