### ISSUE TITLE
about the weight of BCEloss

### ISSUE THREAD

**Issue by wangwang110** [pytorch/pytorch#59862]
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.nn.BCELoss.html#torch.nn.BCELoss

![image](https://user-images.githubusercontent.com/21475557/121630507-de253500-caaf-11eb-95ba-f3930d0328cb.png)

why the weight has a subscript n， different sample has different weight？？

**Comment by prats0599** [comment]
The weight parameter is used to assign class weights. Its used when you have imbalanced classes. See more [here](https://stackoverflow.com/questions/50248029/in-pytorch-how-to-use-the-weight-parameter-in-f-cross-entropy) and [here](https://stackoverflow.com/questions/44716150/how-can-i-assign-a-class-weight-in-keras-in-a-simple-way/44721883).

**Comment by wangwang110** [comment]
thank you for your reply.   so what is different between weight and pos_weightin `torch.nn.BCEWithLogitsLoss(weight=None, size_average=None, reduce=None, reduction='mean', pos_weight=None)`

**Comment by ezyang** [comment]
Ask questions like this at https://discuss.pytorch.org/
