### ISSUE TITLE
Bitwise shifts should retain the same dtype as the first input

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#59867]
The array API specification stipulates that [`bitwise_left_shift`](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#id29) and [`bitwise_left_shift`](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html#id35) (which don't exist yet (see #58742) but their magics `__lshift__` and `__rshift__` do) do not participate in the default type promotion, but rather retain the `dtype` of the first input. PyTorch performs the standard type promotion.

```python
>>> x1 = torch.tensor([0, 1], dtype=torch.uint8)
>>> x2 = torch.tensor([0, 1], dtype=torch.int8)
>>> (x1 << x2).dtype, x1.dtype
(torch.int16, torch.uint8)
>>> (x2 << x1).dtype, x2.dtype
(torch.int16, torch.int8)
>>> (x1 >> x2).dtype, x1.dtype
(torch.int16, torch.uint8)
>>> (x2 >> x1).dtype, x2.dtype
(torch.int16, torch.int8)
```

cc @mruberry @rgommers @pmeier @asmeurer @leofang @nairbv

**Comment by rgommers** [comment]
NumPy does the same as PyTorch here:
```python
>>> x1 = np.array([0, 1], dtype=np.uint8)
>>> x2 = np.array([0, 1], dtype=np.int8)
>>> (x1 << x2).dtype, x1.dtype
(dtype('int16'), dtype('uint8'))
```

Perhaps the specification is incorrect. I don't see a review comment on it in https://github.com/data-apis/array-api/pull/54, and `bitwise_xor` does do the regular type promotion. @kgryte do you remember why there's this discrepancy?

**Comment by mruberry** [comment]
Following up on @rgommers's comment above: it's important that type promotion be applied consistently. There are already several type promotion variants, including binary elementwise functions that always map to bool (like the comparison operators) and binary elementwise operations that always promote to float (like atan2 and true_divide), but I don't want to create another class of type promotion that biases towards the dtype of the first element. What if that first element is a scalar? Type promotion is already complicated enough.

**Comment by kgryte** [comment]
There is a PR open on the array API to update the current guidance for bitwise shift operations: https://github.com/data-apis/array-api/pull/201

**Comment by rgommers** [comment]
This is solved in the specification now. The new text is _"an array containing the element-wise results. The returned array must have a data type determined by Type Promotion Rules ."_ Which is consistent with PyTorch's current behavior.
