### ISSUE TITLE
How to export a model with nn.Module in for loop to onnx?

### ISSUE THREAD

**Issue by JaheimLee** [pytorch/pytorch#59870]
Bellow is a demo code:
```
class Demo(nn.Module):
    def __init__(self, hidden_size, max_span_len):
        super().__init__()
        self.max_span_len = max_span_len
        self.fc = nn.Linear(hidden_size * 2, hidden_size)

    def forward(self, seq_hiddens):
        '''
        seq_hiddens: (batch_size, seq_len, hidden_size)
        '''
        seq_len = seq_hiddens.size()[1]

        hiddens_list = []
        for ind in range(seq_len):
            hidden_each_step = seq_hiddens[:, ind, :]
            a = seq_hiddens[:, ind:ind + self.max_span_len, :]
            b = hidden_each_step[:, None, :].repeat(1, a.shape[1], 1)  
            
            tmp = torch.cat([a, b], dim=-1)
            tmp = torch.tanh(self.fc(tmp))
            hiddens_list.append(tmp)

        output = torch.cat(hiddens_list, dim = 1)
        return output

```
How to expot it to onnx? I need the fc Layer in for loop. Script function seems not work.
Thanks!!!

cc @garymm @BowenBao @neginraoof

**Comment by garymm** [comment]
You'll need to use torch.jit.script to preserve the control flow.

Please provide the error message when doing something like:

```python
scripted = torch.jit.script(Demo(hidden_size, max_span_len))
example_inputs = ...
example_outputs = scripted(example_inputs)
torch.onnx.export(scripted, example_inputs, example_outputs=example_outputs)
```

**Comment by JaheimLee** [comment]
> You'll need to use torch.jit.script to preserve the control flow.
> 
> Please provide the error message when doing something like:
> 
> ```python
> scripted = torch.jit.script(Demo(hidden_size, max_span_len))
> example_inputs = ...
> example_outputs = scripted(example_inputs)
> torch.onnx.export(scripted, example_inputs, example_outputs=example_outputs)
> ```

Finally, I find it's the same problem as [issue 54203](https://github.com/pytorch/pytorch/issues/54203). The Demo model is a part of my 'Full model'. And I also do `torch.jit.script(Demo(hidden_size, max_span_len))` in Full model's __init__ function. When using `torch.onnx.export`, the same error occurs!

**Comment by garymm** [comment]
IIUC, this is the same issue as #54203, so closing
