### ISSUE TITLE
"Address already in use" when migrating to use elastic launch

### ISSUE THREAD

**Issue by pengwa** [pytorch/pytorch#59872]
## To Reproduce

1. Use Megatron-LM to train a gpt2 model with 2 gpus. Here is my command: 

```
GPUS_PER_NODE=2
# Change for multinode config
MASTER_ADDR=localhost
MASTER_PORT=7770
NNODES=1
NODE_RANK=0
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))


CHECKPOINT_PATH=checkpoints/gpt2_345m
VOCAB_FILE=gpt2-vocab.json
MERGE_FILE=gpt2-merges.txt
DATA_PATH=test_data/my-gpt2_text_document

DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --master_addr $MASTER_ADDR --master_port $MASTER_PORT" # --standalone"
export NCCL_DEBUG=INFO
python -m torch.distributed.elastic_launch $DISTRIBUTED_ARGS \
       ../pretrain_gpt.py \
       --tensor-model-parallel-size 1 \
       --pipeline-model-parallel-size 1 \
       --num-layers 2 \
       --hidden-size 1024 \
       --num-attention-heads 16 \
       --micro-batch-size 4 \
       --global-batch-size 16 \
       --seq-length 1024 \
       --max-position-embeddings 1024 \
       --train-iters 8 \
       --lr-decay-iters 320000 \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH \
       --vocab-file $VOCAB_FILE \
       --merge-file $MERGE_FILE \
       --data-impl mmap \
       --split 949,50,1 \
       --distributed-backend nccl \
       --lr 0.00015 \
       --lr-decay-style cosine \
       --min-lr 1.0e-5 \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --lr-warmup-fraction .01 \
       --log-interval 100 \
       --save-interval 10000 \
       --eval-interval 1000 \
       --eval-iters 10 \
```

1. Using earlier PyTorch, it could run successfully. 
2. But with a PyTorch of commit (f46014f9abc7fad0dfd9a46de8444e74f868f4c3) it throw this error:

> 
> Traceback (most recent call last):
>   File "../pretrain_gpt.py", line 129, in <module>
>     args_defaults={'tokenizer_type': 'GPT2BPETokenizer'})
>   File "/home/pengwa/dev/Megatron-LM/megatron/training.py", line 95, in pretrain
>     args_defaults=args_defaults)
>   File "/home/pengwa/dev/Megatron-LM/megatron/initialize.py", line 78, in initialize_megatron
>     finish_mpu_init()
>   File "/home/pengwa/dev/Megatron-LM/megatron/initialize.py", line 59, in finish_mpu_init
>     _initialize_distributed()
>   File "/home/pengwa/dev/Megatron-LM/megatron/initialize.py", line 186, in _initialize_distributed
>     init_method=init_method)
>   File "/home/pengwa/dev/pytorch/torch/distributed/distributed_c10d.py", line 516, in init_process_group
>     store, rank, world_size = next(rendezvous_iterator)
>   File "/home/pengwa/dev/pytorch/torch/distributed/rendezvous.py", line 146, in _tcp_rendezvous_handler
>     store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
> **RuntimeError: Address already in use**

## Expected behavior

The same distributed training command should work even after the torch.distributed.launch is updated to torch.distributed.elastic_launch. 

## Environment

Collecting environment information...
PyTorch version: 1.9.0a0+git2b19e2c
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.10

Python version: 3.7 (64-bit runtime)
Python platform: Linux-5.0.0-1032-azure-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.18.5
[pip] torch==1.9.0a0+git2b19e2c
[pip] torch-tb-profiler==0.2.0rc3
[pip] torchaudio==0.9.0.dev20210312
[pip] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he8ac12f_0
[conda] mkl_fft                   1.3.0            py37h54f3939_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] torch                     1.9.0a0+git2b19e2c           dev_0    <develop>
[conda] torch-tb-profiler         0.2.0rc3                 pypi_0    pypi
[conda] torchaudio                0.9.0.dev20210312          pypi_0    pypi
[conda] torchvision               0.9.0                    pypi_0    pypi

## Additional context

I investigated a bit, find 
https://github.com/pytorch/pytorch/blob/c9e4d1372fdbbbd908661a61de9a68e0044a0a1d/torch/distributed/run.py#L496

The master_addr/master_port I intend to pass to init_process_group is used as rdzv endpoint service by default. (without --standalone flag). 

**_Once I added --standalone, the program can proceed further, but will hang wat the step of init_process_group._** 
Do you have any insights about where it goes wrong? All suggestions to get it run successfully are greatly appreciated. 

Another thing I would suggest is, could you please provide some steps to start a etcd service, which is used for multiple node training. I might be one of those guys not familar with etcd setup., migrating original torch.distributed.launcher experiences. 

Thanks a lot for the help. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by cbalioglu** [comment]
With PyTorch v1.9 we introduced a new rendezvous implementation based on C10d that does not require etcd.

Having said that the correct way to initiate an elastic job is described [here](https://pytorch.org/docs/1.9.0/elastic/quickstart.html). Note that MASTER_ADDR, MASTER_PORT, NNODES, NODE_RANK, and WORLD_SIZE will be set by the launcher script for you.

```
python -m torch.distributed.run\
        --nnodes=1\
        --nproc_per_node=$GPUS_PER_NODE\
        --rdzv_backend=c10d\
        --rdzv_endpoint=localhost\
        ../pretrain_gpt.py\
        <your_script_arguments>
```

Let me know if you still have trouble running your job when using `torch.distributed.run`.

**Comment by pengwa** [comment]
> With PyTorch v1.9 we introduced a new rendezvous implementation based on C10d that does not require etcd.
> 
> Having said that the correct way to initiate an elastic job is described [here](https://pytorch.org/docs/1.9.0/elastic/quickstart.html). Note that MASTER_ADDR, MASTER_PORT, NNODES, NODE_RANK, and WORLD_SIZE will be set by the launcher script for you.
> 
> ```
> python -m torch.distributed.run\
>         --nnodes=1\
>         --nproc_per_node=$GPUS_PER_NODE\
>         --rdzv_backend=c10d\
>         --rdzv_endpoint=localhost\
>         ../pretrain_gpt.py\
>         <your_script_arguments>
> ```
> 
> Let me know if you still have trouble running your job when using `torch.distributed.run`.

Thanks a lot @cbalioglu , I tried your solution, and the program can proceed further, but will hang wat the step of init_process_group. Do you have any idea whether it could go wrong?

**Comment by kiukchung** [comment]
closing since no response, feel free to reopen.
