### ISSUE TITLE
Figure out why the clang-tidy job in lint.yml failed to login ghcr.io occasionally

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#59879]
Example

![image](https://user-images.githubusercontent.com/658840/121723988-0f940580-ca9c-11eb-9c8d-1a15a8460516.png)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by bdhirsh** [comment]
if it's helpful, link to the failed run: https://github.com/pytorch/pytorch/pull/59115/checks?check_run_id=2803504577

**Comment by seemethere** [comment]
Maybe it'd be better to just move these to S3?

S3 for us has proven to be the most reliable

**Comment by driazati** [comment]
If we move lint to our runners in EC2 logging/running from ECR should be straightforward right? Along with @1ntEgr8 we're trying to get a static build of clang-tidy working (and stored in S3, see #59815), so maybe we could use that instead of the docker image

**Comment by zhouzhuojie** [comment]
ghcr gives better public access, and it should be natively supported from github action, though from this issue I'm not sure how the login permission kicks in.

ECR or S3 requires either we open the public access or constraining the access to who has the aws api token.
Docker hub has a free tier docker pull rate limiting.

**Comment by seemethere** [comment]
> If we move lint to our runners in EC2 logging/running from ECR should be straightforward right? Along with @1ntEgr8 we're trying to get a static build of clang-tidy working (and stored in S3, see #59815), so maybe we could use that instead of the docker image

Somewhat straightforward, we'd still have to have the auth step to do the actual log in since the EC2 runners don't automatically do that, but maybe they should?

**Comment by zhouzhuojie** [comment]
Didn't see similar issues recently, seemingly a transient infrastructure failure from the GHA side, and they've been improving recently. Notice that the chance of getting random failures and missing logs of GHA steps are dropping.
