### ISSUE TITLE
Expose findDanglingImpls to Python

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#59885]
https://github.com/pytorch/pytorch/pull/46484/ is cool but it is not accessible from Python, which means you can't easily use it to test if backend extensions have dangling impls. A way to call it from Python would help a bit. Put the binding in torch/csrc/utils/python_dispatch.cpp Ideally it would be easy to get the (1) name of dangling impls and (2) filename/lineno where the dangling impl occurred.

**Comment by ezyang** [comment]
cc @bdhirsh, maybe this is good bootcamp task

**Comment by alanwaketan** [comment]
Taking this as a bootcamp task.

**Comment by alanwaketan** [comment]
Have a couple of question:
1. Can I have instructions on how to run tests within the test_dispatch.py? I know how to run cpp tests in the codebase but not Python ones.
2. Since the `Dispatcher::singleton().findDanglingImpls()` returns `std::vector<c10::OperatorHandle>`, should I just return the above vector directly to the Python layer? I'm not sure if we have already had bindings for OperatorHandle.

**Comment by alanwaketan** [comment]
> 1. Can I have instructions on how to run tests within the test_dispatch.py? I know how to run cpp tests in the codebase but not Python ones.

Figured that out: `buck test //caffe2/test:others -- test_defaultbackend_autogradcpu`.

**Comment by ezyang** [comment]
> Can I have instructions on how to run tests within the test_dispatch.py? I know how to run cpp tests in the codebase but not Python ones.

In an open source build can do `python test/test_dispatch.py`

> Since the Dispatcher::singleton().findDanglingImpls() returns std::vector<c10::OperatorHandle>, should I just return the above vector directly to the Python layer? I'm not sure if we have already had bindings for OperatorHandle.

Nope there are no bindings, and probably don't want to actually directly bind OperatorHandle as it wasn't designed for Python binding (unless... you really want to?) See original:

> Ideally it would be easy to get the (1) name of dangling impls and (2) filename/lineno where the dangling impl occurred.

**Comment by alanwaketan** [comment]
> > Can I have instructions on how to run tests within the test_dispatch.py? I know how to run cpp tests in the codebase but not Python ones.
> 
> In an open source build can do `python test/test_dispatch.py`

Bookmarked. Will use this instead once I will be able to develop on OSS.

> 
> > Since the Dispatcher::singleton().findDanglingImpls() returns std::vectorc10::OperatorHandle, should I just return the above vector directly to the Python layer? I'm not sure if we have already had bindings for OperatorHandle.
> 
> Nope there are no bindings, and probably don't want to actually directly bind OperatorHandle as it wasn't designed for Python binding (unless... you really want to?) See original:
> 
> > Ideally it would be easy to get the (1) name of dangling impls and (2) filename/lineno where the dangling impl occurred.

I have used `OperatorHandle.dumpState` for the info. I believe it should have all the information.

**Comment by alanwaketan** [comment]
Closed this as the corresponding PR is merged.
