### ISSUE TITLE
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\Mohamed\anaconda3\envs\3days\lib\site-packages\torch\lib\caffe2_module_test_dynamic.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by Mohamed9555** [pytorch/pytorch#59904]
it was working when I was trying to run on cpu after installing cuda It doesn't work on cpu or gpu and gives me this error.
Environment
PyTorch Version (e.g., 1.0): master
OS (e.g., Linux): Windows 10
How you installed PyTorch (conda, pip, source): source
Python version: 3.8
CUDA/cuDNN version: 11.3
GPU models and configuration:
Any other relevant information: VS 2017
![Screenshot (391)](https://user-images.githubusercontent.com/20893865/121760501-701e5380-cb2b-11eb-9b21-7adcb4d51a78.png)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
What is the size of your memory & paging file? The error message is pretty clear.
