### ISSUE TITLE
Full Backward Hooks get applied even when grad is disabled

### ISSUE THREAD

**Issue by Nicholasjoseph1994** [pytorch/pytorch#59901]
## 🐛 Bug

When full_backward_hooks are registered, they are applied to the modules even in the case of torch.no_grad being disabled. This leads to an error here:
```
> /root/miniconda3/lib/python3.8/site-packages/torch/utils/hooks.py(141)_apply_on_tensors()
    140         grad_fn = new_tensors[0].grad_fn
--> 141         if not grad_fn.name() == "BackwardHookFunctionBackward":
    142             raise RuntimeError("Error while setting up backward hooks. Please open "
```

```
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 884, in _call_impl
    input = bw_hook.setup_input_hook(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/hooks.py", line 158, in setup_input_hook
    res, input_idx = self._apply_on_tensors(fn, args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/hooks.py", line 141, in _apply_on_tensors
    if not grad_fn.name() == "BackwardHookFunctionBackward":
AttributeError: 'NoneType' object has no attribute 'name'
```
## To Reproduce

Add a full_backward_hook to a torch module
Run it with `@torch.no_grad`

## Expected behavior
Nothing should happen with no_grad enabled because there is no backward pass, but it shouldn't give an error. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

I think this can be fixed by changing line 882 in nn.modules.module.py to
`         if len(full_backward_hooks) > 0 and torch.is_grad_enabled():`

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @mruberry @jbschlosser

**Comment by rodrigoberriel** [comment]
After https://github.com/pytorch/pytorch/commit/8b12c8e8b3f45faaf4345bb0639375b531839fc4, this issue now throws:

https://github.com/pytorch/pytorch/blob/6eafe7f15e264e1f163ccf53b3ef9c5306335945/torch/utils/hooks.py#L177-L178

To get this error, I'm using the following code (modified from Issue #57944):

```python
import torch
from torch import nn, Tensor
from torch.autograd import Variable


class MultiplyModule(nn.Module):
    def forward(self, x1, x2):
        return x1 * x2


t1 = Variable(Tensor([3]), requires_grad=False)
t2 = Variable(Tensor([5]), requires_grad=True)

add_module = MultiplyModule()
add_module.register_full_backward_hook(lambda m, x, y: print('In backward hook', x, y))

with torch.no_grad():
    t3 = add_module(t1, t2)
t3.backward()
```

I guess we could fix that by adding a `torch.is_grad_enabled()` [here](https://github.com/pytorch/pytorch/blob/d37c02be08dfc022daf2ee1ddeda2a37b4551cac/torch/nn/modules/module.py#L1116-L1118):

```python
if full_backward_hooks and torch.is_grad_enabled():
   # ...
```
If that is a good solution, I could send a PR. Additionally, should we do the same for [`non_full_backward_hooks`](https://github.com/pytorch/pytorch/blob/d37c02be08dfc022daf2ee1ddeda2a37b4551cac/torch/nn/modules/module.py#L1131-L1144)?

**Comment by albanD** [comment]
That would fix the no grad mode case but will still fail if the forward is non-differentiable.
I guess we can just do nothing if there is no grad_fn we can find and that will solve both of these problems.

**Comment by rodrigoberriel** [comment]
@albanD I thought so too, but non-differentiable functions will return an output with `.requires_grad=False` (and `.grad_fn=None`) that will be caught by

https://github.com/pytorch/pytorch/blob/992dad18552883224016d53429c48f2e932651cf/torch/utils/hooks.py#L126-L134

and nothing will happen (which is what we want, isn't it?) until `.backward()` is called. Then, following error is thrown:

```
Traceback (most recent call last):
  File "/myuser/pytorch-dev/backward.py", line 18, in <module>
    t3.backward()
  File "/myuser/miniconda3/envs/pytorch-dev/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/myuser/miniconda3/envs/pytorch-dev/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

which is not related to the backward hook. So, we only need to worry about the no grad mode case for now, is that correct?

There is one difference, though: in the non-differentiable case, the hook will at least be registered for the input (it won't run, because backwards will fail).

If routing both cases to the `if not requires_grad` condition is preferable, we could:
1. initialize `requires_grad = torch.is_grad_enabled()` in the code above, or
2. if (1) is confusing, we could instead add a `requires_grad &= torch.is_grad_enabled()` after the `for` loop.

Let me know what you think.

---

BTW, I tested the non-differentiable forward using the code below:

```python
import torch


class ArgMax(torch.nn.Module):
    def forward(self, x):
        return torch.argmax(x)


x = torch.rand((2, 3), requires_grad=True)

m = ArgMax()
m.register_full_backward_hook(lambda m, x, y: print('In backward hook', x, y))

t = m(x)
t.backward()
```

**Comment by albanD** [comment]
Hi,

Yes that sounds good. I think the simplest change is
https://github.com/pytorch/pytorch/blob/88032d894311e5c0aed8bbc21a4306bc6be4af82/torch/utils/hooks.py#L133

To check if grad mode is disabled.

Could you send a PR for that?

**Comment by rodrigoberriel** [comment]
@albanD Done.
