### ISSUE TITLE
use_external_data_format=True not working when exporting model > 2gb 

### ISSUE THREAD

**Issue by 24hours** [pytorch/pytorch#59906]
## 🐛 Bug

`torch.onnx.export` always crash when exporting model larger than 2gb regardless of `use_external_data_format` flag value. 

## To Reproduce

import torch
import torch.nn as nn

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.w = nn.Parameter(torch.zeros(550, 550, 64, 64))

    def forward(self, img):
        return torch.sum(self.w) + torch.sum(img)

model = M()
img = torch.zeros(1, 2, 3)

torch.onnx.export(
    model, 
    img,
    "example.onnx",
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
    use_external_data_format=True
)

```
Traceback (most recent call last):
  File "export_test.py", line 21, in <module>
    use_external_data_format=True
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 468, in _model_to_graph
    module=module)
  File "/home/yklee/anaconda3/envs/ddl/lib/python3.7/site-packages/torch/onnx/utils.py", line 230, in _optimize_graph
    torch._C._jit_pass_onnx_graph_shape_type_inference(graph, params_dict, _export_onnx_opset_version)
RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.
```

## Expected behavior

model should export successfully. 

## Environment
Collecting environment information...
PyTorch version: 1.8.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7 (64-bit runtime)
Python platform: Linux-4.15.0-144-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchvision==0.2.2.post3
[conda] efficientnet-pytorch      0.6.3                     <pip>
[conda] numpy                     1.20.3                    <pip>
[conda] numpy                     1.20.2                    <pip>
[conda] pytorch-lightning         1.3.2                     <pip>
[conda] pytorch-lightning         1.1.1                     <pip>
[conda] segmentation-models-pytorch 0.1.0                     <pip>
[conda] torch                     1.8.1+cpu                 <pip>
[conda] torchaudio                0.8.1                     <pip>
[conda] torchmetrics              0.3.2                     <pip>
[conda] torchvision               0.9.1+cpu                 <pip>

cc @garymm @BowenBao @neginraoof

**Comment by BowenBao** [comment]
Thanks for reporting, #59320 should fix this. It should soon be in master.

**Comment by 24hours** [comment]
Hi, I verified that it fixed in nightly build
