### ISSUE TITLE
Quantization support for torch.index_select

### ISSUE THREAD

**Issue by tbpangolin** [pytorch/pytorch#59928]
## 🚀 Feature
Support torch.index_select on 'QuantizedCPU' backend

## Motivation
I'm trying to quantize a model, and there is a step that slices tensor based on indices along the batch (for separate processing).

I can use `torch.index_select` for this purpose, like:
`kept_x = torch.index_select(x, dim=0, index=torch.tensor(indices))`

But if x is a quantized tensor, this will run into an error:
> RuntimeError: Could not run 'aten::index_select' with arguments from the 'QuantizedCPU' backend.

## Pitch

Support torch.index_select on 'QuantizedCPU' backend, so there's no need to add dequant/quant simply for indexing a quantized tensor. And I assume indexing an int8 tensor might be faster than a fp32 tensor.

## Alternatives
I can make it work in this way:

`x = self.dequant(x)`
`kept_x = torch.index_select(x, dim=0, index=torch.tensor(indices))`
`kept_x = self.quant(kept_x)`

But this is unnecessarily slow due to the extra dequant/quant step. Here is a chrome trace:
![Screen Shot 2021-06-13 at 5 47 56 PM](https://user-images.githubusercontent.com/13760630/121827050-8c2b0d80-cc6f-11eb-8713-d52f6ac7a297.png)

## Additional context
Another option is instead of using `torch.index_select`, I can directly use the select operator like:
`kept_x = x[indices]`

This doesn't need explicit dequant and quant and model can be quantized successfully.
However, when inspecting the chrome trace of the model, I can see at the indexing step, the model is still silently dequant before index, and the overall running time is slightly longer:
![Screen Shot 2021-06-13 at 5 49 32 PM](https://user-images.githubusercontent.com/13760630/121827143-da401100-cc6f-11eb-9be2-66c11519a25f.png)

cc. @jerryzh168 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @Varal7 @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
This is now supported
