### ISSUE TITLE
protobuf compatibility error

### ISSUE THREAD

**Issue by habibcomsats** [pytorch/pytorch#59924]
## 🐛 Protocol buffers library mismatch.

I am using latest protocol buffer compiler for client/server communication and I want to add pytorch on the client side with local visualization using tensorboard. I have raised the issue with google's developers and they resolved the issue from their side. A fresh build of pytorch (torchvision) with latest version of tensorboard can resolve this issue. 

## To Reproduce

https://github.com/tensorflow/tensorboard/issues/5044

[libprotobuf FATAL google/protobuf/stubs/common.cc:87]

This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.16.0). Contact the program author for an update.

If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.

(Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)

terminate called after throwing an instance of 'google::protobuf::FatalException' what():

This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.16.0).
Contact the program author for an update.

If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.

(Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)

Aborted (core dumped)

I want to run official mnist example using latest tensorboard.

## Environment
Linux (Ubunutu 20)
Python 3.9
Pytorch 1.8.1
CUDA 11.1

**Comment by rgommers** [comment]
This was solved last year, so I'll close this.
