### ISSUE TITLE
If I only have the model of PyTorch and don't know the dimension of the input, how to convert it to onnx?

### ISSUE THREAD

**Issue by Wendy-liu17** [pytorch/pytorch#59933]
### Question

I have a series of PyTorch trained models, such as "model.pth", but I don't know the input dimensions of the model.
For instance, in the following function: torch.onnx.export(model, args, f, export_params=True, verbose=False, training=False, input_names=None, output_names=None).
I don't know the "args" of the function. How do I define it by just having the model file such as "model.pth"?

**Comment by soulitzer** [comment]
Issues are for bugs and features only. Please use the forum https://discuss.pytorch.org/ for questions.
