### ISSUE TITLE
Pretrained Model Loading Error

### ISSUE THREAD

**Issue by herleeyandi** [pytorch/pytorch#5994]
Hello I am using:
- OS: Ubuntu 16
- PyTorch version: 0.3.1post2
- Installed using Anaconda
- Python version: 3.6.4
- CUDA/cuDNN version: 8.0
- GPU models and configuration:NVIDIA gtx980tI
While executing this to load pretrained model.
`model = torch.load("./model/my_pretrained.pth")["model"]`
Here is the error:
```

> ~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
>     259         f = open(f, 'rb')
>     260     try:
> --> 261         return _load(f, map_location, pickle_module)
>     262     finally:
>     263         if new_fd:
> 
> ~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
>     407     unpickler = pickle_module.Unpickler(f)
>     408     unpickler.persistent_load = persistent_load
> --> 409     result = unpickler.load()
>     410 
>     411     deserialized_storage_keys = pickle_module.load(f)
> 
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 918: ordinal not in range(128)
> 

```

**Comment by apaszke** [comment]
Did you save the model on the same computer?

**Comment by herleeyandi** [comment]
@apaszke No, someone said maybe because the saved model is in pytorch python2 and now I am using pytorch in python 3. That make sense because I update my system to python 3 and I trained the model in python 2. So can we convert the model?
I am sorry I just see the sugesstion in [here](https://discuss.pytorch.org/t/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-918-ordinal-not-in-range-128/15356/2)

**Comment by apaszke** [comment]
Hmm it looks like there really are some issues with files pickled from Python 2 and loaded in Python 3. See e.g. [this SO thread](https://stackoverflow.com/questions/11305790/pickle-incompatibility-of-numpy-arrays-between-python-2-and-3).

**Comment by fmassa** [comment]
If you were to load the file using pickle alone, I'd suggest trying to load it using `encoding='latin1'` for example.
```python
with open(myfile, 'rb') as f:
    data = pickle.load(f, encoding='latin1')
```
This has solved issues for me when deserializing some pickle files saved on python2 and loaded on python3. But to make it work out-of-the-box on `torch.load` might require extending the API.

**Comment by soumith** [comment]
closed via @fmassa 's comment
