### ISSUE TITLE
cuda Runtime error on google colab

### ISSUE THREAD

**Issue by rahul-iyer** [pytorch/pytorch#5995]
This code worked yesterday and I couldn't figure out what's the problem.

This is my model 
`class RNNModel(nn.Module):
    def __init__(self, ntoken, ninp,
                 nhid, nlayers, bsz,
                 dropout=0.5):
        super(RNNModel, self).__init__()
        self.nhid, self.nlayers, self.bsz = nhid, nlayers, bsz
        self.drop = nn.Dropout(dropout)
        self.encoder = nn.Embedding(ntoken, ninp)
        self.rnn = nn.LSTM(ninp, nhid, nlayers, dropout=dropout)
        self.decoder = nn.Linear(nhid, 4)
        self.softmax = nn.Softmax(dim = 1)
        self.init_weights()
        self.hidden = self.init_hidden()
    def init_weights(self):
        initrange = 0.1
        self.encoder.weight.data.uniform_(-initrange, initrange)
        self.decoder.bias.data.fill_(0)
        self.decoder.weight.data.uniform_(-initrange, initrange)

    def forward(self, input):
        emb = self.drop(self.encoder(input))
        output, self.hidden = self.rnn(emb, self.hidden)
        decoded = self.softmax(self.decoder(output[-1]))
        return decoded

    def init_hidden(self):
        weight = next(self.parameters()).data
        x = Variable(torch.zeros(self.nlayers, self.bsz, self.nhid))
        y = Variable(torch.zeros(self.nlayers, self.bsz, self.nhid))
        x = x.cuda()
        y = y.cuda()
        return (x, y)
    
    def reset_history(self):
        self.hidden = tuple(Variable(v.data) for v in self.hidden)`

This is what I run
`model = RNNModel(weight_matrix.size(0),
                 weight_matrix.size(1), 200, 1, 32)`

Error 

`
RuntimeError                              Traceback (most recent call last)
<ipython-input-219-1eb91912d235> in <module>()
      1 model = RNNModel(weight_matrix.size(0),
----> 2                  weight_matrix.size(1), 200, 1, 32)

<ipython-input-217-8f7d5937ee65> in __init__(self, ntoken, ninp, nhid, nlayers, bsz, dropout)
     11         self.softmax = nn.Softmax(dim = 1)
     12         self.init_weights()
---> 13         self.hidden = self.init_hidden()
     14 
     15 

<ipython-input-217-8f7d5937ee65> in init_hidden(self)
     33         x = Variable(torch.zeros(self.nlayers, self.bsz, self.nhid))
     34         y = Variable(torch.zeros(self.nlayers, self.bsz, self.nhid))
---> 35         x = x.cuda()
     36         y = y.cuda()
     37         return (x, y)

/usr/local/lib/python3.6/dist-packages/torch/autograd/variable.py in cuda(self, device, async)
    296 
    297     def cuda(self, device=None, async=False):
--> 298         return CudaTransfer.apply(self, device, async)
    299 
    300     def cpu(self):

/usr/local/lib/python3.6/dist-packages/torch/autograd/_functions/tensor.py in forward(ctx, i, device, async)
    199             return i.cuda(device, async=async)
    200         else:
--> 201             return i.cuda(async=async)
    202 
    203     @staticmethod

/usr/local/lib/python3.6/dist-packages/torch/_utils.py in _cuda(self, device, async)
     67         else:
     68             new_type = getattr(torch.cuda, self.__class__.__name__)
---> 69             return new_type(self.size()).copy_(self, async)
     70 
     71 
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:20`

**Comment by apaszke** [comment]
You likely have some out of bound indices. If you think it's a bug in PyTorch please try to give us a minimal script (<100 lines) that we could run and that would reproduce the error.
