### ISSUE TITLE
Make to_dense() a no-op for non-sparse Tensors

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#59958]
As of today, calling to_dense() on a strided Tensor raises an error
Similarly, calling to_sparse() on a sparse Tensor raises an error.

It would be nice to make these no-ops instead of errors to simplify user code.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by pearu** [comment]
Perhaps OT: similarly, we have `.is_sparse` for checking COO layout, `.is_sparse_coo` for checking CSR layout, but no `.is_strided` for checking strided layout (instead, we'll use `.layout == torch.strided`). It would be nice to use the same idiom for checking layouts.

**Comment by pearu** [comment]
What would be the semantics of `to_dense`? Options:
1. copy a tensor with an arbitrary layout to a tensor with strided layout
2. copy a tensor with an arbitrary non-strided layout to a tensor with strided layout, return a view of the tensor (be it contiguous or non-contiguous) if it already has strided layout.
3. an alternative approach would be to support `layout` parameter in `to` method and retire `to_dense`, `to_sparse`, and `to_sparse_csr` methods.

**Comment by cpuhrsch** [comment]
I'd go with Option 2.

Add a new kernel registered under the ```CompositeExplicitAutograd ``` key (since to_dense has a to_dense_backward) and return the input unchanged (view) if it already is Layout::Strided, throw otherwise.
