### ISSUE TITLE
 only lowercase letters a-z allowed as indices in torch.einsum?

### ISSUE THREAD

**Issue by pengfzhou** [pytorch/pytorch#59969]
## 🚀 Feature

i want more indices other than only lowercase letters a-z allowed in torch.einsum
## Motivation
when i do tensor cotraction, i don't want to repeatedly reshape the tensors to ensure that  indices are  limited in lowercase letters a-z. thanks! 

cc @heitorschueroff

**Comment by heitorschueroff** [comment]
@pengfzhou We've added support for uppercase letters as well in https://github.com/pytorch/pytorch/pull/56475. Does that suffice for your use case, or would you want even more possible subscripts?

**Comment by pengfzhou** [comment]
Thanks,it sloved my case, but I suggest than you can implement more possible subscripts like numpy.

**Comment by heitorschueroff** [comment]
@pengfzhou NumPy also only supports [A-Za-z] and in the sublist format they support [0, 52) as indices. But I took note of your request and will consider for future implementations of `torch.einsum`. Closing this issue for now.
