### ISSUE TITLE
torch.get/set_rng_state only handles cpu

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#59974]
This behavior is kinda expected since we also have `torch.cuda.get/set_rng_state` but api `torch.manual_seed`(defined in the same file https://github.com/pytorch/pytorch/blob/master/torch/random.py#L22)  handles both cpu & cuda. 
We should at least improve our documentation for `torch.get/set_rng_state` to tell users it only supports cpu, and if they want cuda as well they need to use `manual_seed`. 
```
[15]
import torch
s0 = torch.get_rng_state()
torch.set_rng_state(s0)
torch.randn(5, device='cpu')

tensor([-0.3407,  0.1835,  0.6271,  0.5801, -1.2006])
[17]
torch.set_rng_state(s0)
torch.randn(5, device='cpu')


tensor([-0.3407,  0.1835,  0.6271,  0.5801, -1.2006])
[21]
torch.set_rng_state(s0)
torch.randn(5, device='cuda')



tensor([-0.2259, -0.1659,  1.6437,  0.2440, -1.2208], device='cuda:0')
[20]
torch.set_rng_state(s0)
torch.randn(5, device='cuda')
tensor([-0.3669, -1.0622, -0.6299,  1.8582,  0.5537], device='cuda:0')
```
cc: @roosephu who reported the issue to me. 

cc @brianjo @mruberry @pbelevich

**Comment by bdhirsh** [comment]
reserving for onboarding
