### ISSUE TITLE
Allow params to be an iterable of dicts in ZeroRedundancyOptimizer

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#59973]
## 🚀 Feature
Allow the input argument `params` to `ZeroRedundancyOptimizer` be an iterable of `dict`s.

## Motivation
In the normal `Optimizer` implementation, the input argument `params` can be either an iterable of `torch.Tensor`s or an iterable of `dict`s (see [here](https://github.com/pytorch/pytorch/blob/ef13341a8d1128a5fbd54716c89358cbd20c0a1d/torch/optim/optimizer.py#L27)). The latter form is for initializing the optimizer with multiple parameter groups to begin. The current `ZeroRedundancyOptimizer` implementation only supports `params` as an iterable of `torch.Tensor`s.

## Pitch
We should add support for `params` as an iterable of `dict`s. Otherwise, the `ZeroRedundancyOptimizer` must be initialized with only a single parameter group, and the user must call `add_param_group()` for each additional parameter group. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by Kyeongpil** [comment]
Hi, I'm facing a problem related to this issue.
I want to input parameter groups into ZeroRedundancyOptimizer like:
```
no_decay = ["bias", "LayerNorm.weight"]
optimizer_parameters = [
    {
        "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
        "weight_decay": config.train.weight_decay_ratio,
    },
    {
        "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
        "weight_decay": 0.0,
    },
]
optimizer = ZeroRedundancyOptimizer(
    model.parameters(),
    optimizer_class=AdamW,
    parameters_as_bucket_view=True,
    lr=config.train.learning_rate,
    betas=(config.train.adam_beta1, config.train.adam_beta2),
    eps=config.train.adam_epsilon,
)
```

Is there any progress on this issue? Or how can I input as an Iterable of Dict-like parameters?

**Comment by andwgu** [comment]
I think the workaround is to pass one of the `param_group`s through the constructor and to use `ZeroRedundancyOptimizer`'s `add_param_group()` method for the other `param_group`. The following pseudocode is off the top of my head since I do not have the ability to reproduce the code right now:
```
# Construct the list of parameters to pass into the ZeRO constructor
decay_parameters = [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)]
# Construct a separate `param_group` to pass into `add_param_group()`
no_decay_parameters = {
    "params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)],
    "weight_decay": 0.0,
}
optimizer = ZeroRedundancyOptimizer(
    decay_parameters,
    optimizer_class=AdamW,
    parameters_as_bucket_view=True,
    lr=config.train.learning_rate,
    betas=(config.train.adam_beta1, config.train.adam_beta2),
    eps=config.train.adam_epsilon,
    weight_decay=config.train.weight_decay_ratio,
)
optimizer.add_param_group(no_decay_parameters)  # must be called on all workers
```
Let me know if this works or if there are any further issues!

**Comment by Kyeongpil** [comment]
@andwgu Thank you for your considerate answer!
I tested your proposed code, and there seems to be no error :) Thank you!

**Comment by Liyang90** [comment]
+1 for this feature. fairscale's OSS seems to accept param groups dictionary as `params` input, so it would be nice to have it in PyTorch as well.

**Comment by awgu** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/72578.

Let me know if there are any issues.

**Comment by awgu** [comment]
Re-landed: https://github.com/pytorch/pytorch/pull/72932
