### ISSUE TITLE
`OMP_NUM_THREADS` doesn't work as intended in some cases 

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60000]
## 🐛 Bug

If PyTorch is built with `MKL`, `OMP_NUM_THREADS` doesn't set the desired number of OpenMP threads if a value greater than half the number of available cores is provided (which can be useful if HyperThreading is off, as all the available cores are physical cores in that case).

## To Reproduce

1. Clone the current master branch
2. Build PyTorch with both `numpy` & `mkl`.
3. Create a Python file with this snippet -
```
import torch
print(torch.get_num_threads())
```
4. Run this Python script with `OMP_NUM_THREADS=x python filename.py` where x is a number greater than half the number of available cores. Using `MKL_NUM_THREADS=x` doesn't make a difference either.
5. The output is not the desired output. This means users might get misled into believing that `OMP_NUM_THREADS` had set the desired number of threads.

## Expected behavior

Using `torch.set_num_threads()` doesn't cause this issue, but the environment variable `OMP_NUM_THREADS` should have behaved in a similar manner.

## Environment

Master Branch's source

PyTorch version: 1.10.0a0+gitc645d39
Is debug build: False

OS: Ubuntu 18.04.1 LTS (x86_64) & Ubuntu 20.04 LTS (x86_64)
GCC version:  7.5.0 & 9.3.0
CMake version: version 3.10.2 & 3.16.3
Libc version: glibc-2.25 & Libc version: glibc-2.31

Python version: 3.6 (64-bit runtime) & 3.8
Python platform: Linux-4.15.0-137-generic-x86_64-with-Ubuntu-18.04-bionic  & Linux-5.4.0-67-generic-x86_64-with-glibc2.29

Versions of relevant libraries:
[pip3] numpy==1.19.5 & 1.20.3 & even without numpy
MKL - [2020.4.304-2](https://launchpad.net/ubuntu/+source/intel-mkl/2020.4.304-2)
OpenMP - libgomp

## Additional context
Maybe this behavior is already known but I couldn't find related info.

cc @brianjo @mruberry

**Comment by ezyang** [comment]
I'm not sure if I understand this bug report correctly, but I'm not sure what we can do in this situation: OMP_NUM_THREADS isn't our env var, and we shouldn't be monkeying around with it ourselves as PyTorch.

**Comment by imaginary-person** [comment]
@ezyang, on a 32 physical core (64 logical cores) machine, if I turn off HyperThreading to have 32 logical cores that correspond to the physical cores, then using `OMP_NUM_THREADS=32` results in `torch.get_num_threads()` outputting 16, instead of 32.
Using `MKL_NUM_THREADS` doesn't help in this case either.

But if I were to use `OMP_NUM_THREADS=x` where `x` is less than 16 (when the number of logical cores is 32), then `torch.get_num_threads()` outputs the correct number of threads, indicating that `OMP_NUM_THREADS` works in this case.

Maybe this behavior can be [documented here](https://github.com/pytorch/pytorch/blob/master/docs/source/notes/cpu_threading_torchscript_inference.rst#runtime-api).

**Comment by ezyang** [comment]
Yeah, I'm all for documenting this quirk. Ideally, we'd find out exactly what interaction is causing this to happen, and maybe it is something we can fix. But if it's like, yeah, numpy using OpenBLAS using openmp causing threads to not be available, well, sorry, there's not much we can do about it.

**Comment by imaginary-person** [comment]
I compiled PyTorch without `numpy`, but with MKL, and encountered the same issue.
So, I was wrong about `numpy` being a factor.

**Comment by raven38** [comment]
**I checked a behaivior of `Openmp` and `MKL`
  I run all scripts on a machine with 10 physical cores.
  
  ```python
  import omp_thread_count
  omp_thread_count.get_thread_count()
  ```
  
  Running this script with `OMP_NUM_THREADS=100 python filename.py` outputs `100` which is expected behavior.
  
  ```python
  import mkl
  mkl.get_max_threads()
  ```
  
  Running this script with `MKL_NUM_THREADS=100 python filename.py` outputs `10` which is not expected behavior.
  
  
  ```python
  import mkl
  mkl.set_num_threads(100)
  mkl.get_max_threads()
  ```
  
  Running this script with `python filename.py` outputs `10` which is not expected behavior.
  
  The above behaviors show that the `OpenMP` works well and `MKL` doesn't work.
  
```python
import mkl
mkl.set_num_threads(20)
mkl.set_dynamic(False)
mkl.get_max_threads()
```

Running this script with `python filename.py` outputs `20` which is expected behavior.


```python
import mkl
mkl.set_num_threads(20)
mkl.get_max_threads()
```

Running this script with `MKL_DYNAMIC=FALSE MKL_NUM_THREADS=20 python filename.py` outputs `20` which is expected behavior.

```python
import torch
print(torch.get_num_threads())
```


Running this script with `MKL_DYNAMIC=FALSE MKL_NUM_THREADS=20 python filename.py` outputs `20` which is expected behavior.
'MKL_DYNAMIC=FALSE OMP_NUM_THREADS=20 python filename.py` also works well.

This is because `mkl.set_dynamic(False)` is called in `torch.set_num_threads`.

https://github.com/pytorch/pytorch/blob/cac9ae1506feabfc87d37a208b3d39ed46c59483/aten/src/ATen/ParallelOpenMP.cpp#L44-L65

Does your question solve?

**Comment by imaginary-person** [comment]
Thanks a lot for your help, @raven38! I wasn't aware of the significance of `MKL_SET_DYNAMIC` earlier.

> 'MKL_DYNAMIC=FALSE OMP_NUM_THREADS=20 python filename.py` also works well.
> This is because mkl.set_dynamic(False) is called in torch.set_num_threads.

No, this behavior isn't related to `torch.set_num_threads()`, but the Intel website explains why
a) `torch.set_num_threads()` and
b) [`MKL_DYNAMIC=FALSE OMP_NUM_THREADS=x`](https://software.intel.com/content/www/us/en/develop/documentation/onemkl-linux-developer-guide/top/managing-performance-and-memory/improving-performance-with-threading/using-additional-threading-control/mkl-dynamic.html) work as intended -

> The default value of MKL_DYNAMIC is TRUE, regardless of OMP_DYNAMIC, whose default value may be FALSE.
> When MKL_DYNAMIC is TRUE, Intel® oneAPI Math Kernel Library may use fewer OpenMP threads than the maximum number you specify.
> For example, MKL_DYNAMIC set to TRUE enables optimal choice of the number of threads in the following cases:
> If the requested number of threads exceeds the number of physical cores (perhaps because of using the Intel® Hyper-Threading Technology), Intel® oneAPI Math Kernel Library scales down the number of OpenMP threads to the number of physical cores.

@ezyang, perhaps, this detail about `MKL_DYNAMIC` can be added to https://github.com/pytorch/pytorch/blob/master/docs/source/notes/cpu_threading_torchscript_inference.rst#runtime-api. Or maybe folks googling for this behavior would be able to find this thread anyway. Thanks!

**Comment by imaginary-person** [comment]
Closing this issue, as it pertains to MKL specifics, rather than PyTorch.
