### ISSUE TITLE
Compilation issue with CUDA 92

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#60016]
## 🐛 Bug

Compile Failure with cuda 92

## To Reproduce

Compile PyTorch with CUDA92 `USE_CUDA=1 USE_NCCL=0 USE_DISTRIBUTED=0 python setup.py develop`
```
/home/erjia/workspace/pytorch_dev/typing/c10/util/Optional.h(641): error: identifier "setInitialized" is undefined

1 error detected in the compilation of "/tmp/tmpxft_000705f0_00000000-6_THCTensorMathPointwiseHalf.cpp1.ii".
CMake Error at torch_cuda_generated_THCTensorMathPointwiseHalf.cu.o.Release.cmake:281 (message):
    Error generating file
    /home/erjia/workspace/pytorch_dev/typing/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMathPointwiseHalf.cu.o
```
## Expected behavior

No Error

## Environment

Collecting environment information...
PyTorch version: 1.10.0a0+git1fc3576
Is debug build: False
CUDA used to build PyTorch: 9.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.17

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.2.9-229_fbk15_hardened_4185_g357f49b36602-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 450.80.02
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A

## Additional context

Possibly due to the change in the PR (https://github.com/pytorch/pytorch/pull/59333)

Fix in https://github.com/pytorch/pytorch/pull/60017

cc @malfet @seemethere @walterddr @ngimel

**Comment by malfet** [comment]
Please note, that CUDA-9.2 is not officially supported in trunk, so any fixes are likely to regress

**Comment by ejguan** [comment]
@malfet 
Yeah, that makes sense. I also have to disable NCCL and distributed to make CUDA 9 being able to be compiled with CUDA 9.
I was thinking something have already been introduced to handle CUDA92. So, why don't we adapt new feature to support it.
https://github.com/pytorch/pytorch/blob/a120a12ab4d5b355e212fcc4c1f13f309792297e/c10/util/Optional.h#L502-L504

**Comment by seemethere** [comment]
> 
> 
> @malfet
> Yeah, that makes sense. I also have to disable NCCL and distributed to make PyTorch compiled with CUDA 9.
> I was thinking something have already been introduced to handle CUDA92. So, why don't we adapt new feature to support it.
> 
> https://github.com/pytorch/pytorch/blob/a120a12ab4d5b355e212fcc4c1f13f309792297e/c10/util/Optional.h#L502-L504

Pull requests would definitely be accepted to add this functionality!
