### ISSUE TITLE
RTX3060,LibTorch1.8.1 can't use cuda in win10

### ISSUE THREAD

**Issue by cvJie** [pytorch/pytorch#60011]
win10 , VS2019
nvidia driver:466.77, 
nvidia GeForce RTX3060,
LibTorch 1.8.1
cuda 11.1
cudnn 8.1.1

code as:
   torch::cuda::is_available() ==False
   torch::cuda::cudnn_is_available==False

but ,I need it all True.
thanks

cc @ngimel @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by skyline75489** [comment]
What is the libtorch version you use? What is the exact code you use?

**Comment by cvJie** [comment]
solved
