### ISSUE TITLE
Torch.onnx.export can not export onnx model 

### ISSUE THREAD

**Issue by huyhoangle86** [pytorch/pytorch#60013]
Hi , I’m trying to export my trained model that in .pt format to ONNX but after I execute the script the program output bunch of logging stuff like in the pic below and the converted onnx format seems not appear in my local disk I don’t know what I got wrong here?

![image](https://user-images.githubusercontent.com/42195775/122040722-5cf8d580-ce02-11eb-9f00-6f5eaa9d5b42.png)

cc @garymm @BowenBao @neginraoof

**Comment by ezyang** [comment]
This looks OK. Are you sure you are checking the right directory for the output? Try passing an absolute filepath instead.

**Comment by huyhoangle86** [comment]
@ezyang  I did try to give it absolute path but no luck :/

**Comment by BowenBao** [comment]
@huyhoangle86  could you paste/inspect the complete output log? In case there is an error during export.

**Comment by huyhoangle86** [comment]
@BowenBao  actually I'm out of ideas, I converted .pt to .weights in darknet and from that I convert to onnx.
And do you kno how do I inference Onnx model ?

**Comment by BowenBao** [comment]
closing. Feel free to follow-up and ask for reopen if the issue persists.
