### ISSUE TITLE
numpy scala + cuda tensor -> non-cuda tensor

### ISSUE THREAD

**Issue by jh-jeong** [pytorch/pytorch#6003]
- OS: Linux (Ubuntu 16.04)
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 8.0 / 7
- GPU models and configuration: TITAN X (Pascal) x 8
- GCC version (if compiling from source): 5.4.0

Hi, 
If we add scala to a cuda tensor, we typically expect a new cuda tensor on the same device:
```
>> torch.rand(5).cuda() + math.log(2)

 1.6099
 0.9674
 0.9591
 0.7931
 1.1470
[torch.cuda.FloatTensor of size 5 (GPU 0)]

>> math.log(2) + torch.rand(5).cuda()

 0.7929
 1.1955
 0.7734
 0.9757
 1.0324
[torch.cuda.FloatTensor of size 5 (GPU 0)]
```

But with numpy scala, the things behave differently: 
```
>> torch.rand(5).cuda() + math.log(2)

 1.6099
 0.9674
 0.9591
 0.7931
 1.1470
[torch.cuda.FloatTensor of size 5 (GPU 0)]

>> np.log(2) + torch.rand(5).cuda()

 1.5042
 1.6458
 0.8886
 1.3921
 0.9682
[torch.FloatTensor of size 5]
```

As we can see, the last line returned a non-cuda tensor, which seems to be inconsistent with the other equivalent lines. Is that an intended behavior?

**Comment by zou3519** [comment]
@5864 may or may not fix this.

**Comment by fmassa** [comment]
This has been fixed in master
```
np.log(2) + torch.rand(5).cuda()
> tensor([0.7561, 1.3810, 1.3874, 0.8049, 1.3309], device='cuda:0')
```
