### ISSUE TITLE
Switch autograd::Function's apply to pass tensors by value using rvalue references, and make sure all tensor lists get moved into it. 

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#6006]
Why? Large operators like those generated by the interpreter need to incrementally release tensors when they run, but they can only do this if they own the only reference to that tensor. Currently we pass the input tensors by const reference, so they cannot be release until the end of an op.

Copying the input list will be necessary when there are hooks but this is the rare case, and the copy is relatively cheap. 

```
// previous
tensor_list apply(const tensor_list& inputs) ...

// after
tensor_list apply(tensor_list&& inputs)...
```

**Comment by ezyang** [comment]
@zdevito Do you know if this bug is still valid?

**Comment by eellison** [comment]
As far as I can tell this has been fixed::

```
virtual variable_list apply(variable_list&& inputs) = 0;
```
