### ISSUE TITLE
Source of `torch.testing.assert_close` reaches a dead end

### ISSUE THREAD

**Issue by simaki** [pytorch/pytorch#60072]
## 📚 Documentation

When I click "[SOURCE]" in PyTorch 1.9.0 documentation of [`torch.testing.assert_close`](https://pytorch.org/docs/stable/testing.html), it reaches a dead end. The URL is https://pytorch.org/docs/stable/_modules/torch/testing/_asserts.html#assert_close .

I suppose this is a minor issue, but let you know just in case.

<img width="874" alt="Screen Shot 2021-06-16 at 14 04 08" src="https://user-images.githubusercontent.com/24503967/122160916-b8cb6900-ceab-11eb-8398-6c4e2e8d57e4.png">

<img width="1576" alt="Screen Shot 2021-06-16 at 14 05 52" src="https://user-images.githubusercontent.com/24503967/122161044-f6c88d00-ceab-11eb-9894-0fa2b554cef3.png">

cc @brianjo @mruberry

**Comment by malfet** [comment]
The file exists in the repo https://github.com/pytorch/pytorch.github.io/blob/site/docs/1.9.0/_modules/torch/testing/_asserts.html
But looks like it was not deployed for some reason

**Comment by malfet** [comment]
Entire `_modues/torch/jit` is also missing from the deployed website

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/pytorch.github.io/commit/5a2028452f93fdc5e44a65e761e03ed658048336 and https://github.com/pytorch/pytorch.github.io/commit/82eaa25adc292d81414e2bd33e95466c52e78dea

**Comment by brianjo** [comment]
That usually happens when we forget to add a .nojekyll file to the folder. Thanks for the report and fix.
