### ISSUE TITLE
Interference between different communication groups?

### ISSUE THREAD

**Issue by lhb8125** [pytorch/pytorch#60071]
### If I launch multiple collective operations with multi communication groups, the performance will be impacted.

- Hardware: two nodes with eight gpus
- Setup: group0(node0_gpu0, node1_gpu0), group1(node0_gpu1, node1_gpu1), ...
- Collective operation: Allreduce
- Expected results: Same bandwidth with the network
- Actual results: The bandwidth decreases as the count of groups increases.

Here is the code snippets:
```
def run(comm_group, args):
    """ Distributed function to be implemented later. """
    tensor = torch.ones(args.message_size).cuda()
    for i in range(200):
        dist.all_reduce(tensor, op=dist.ReduceOp.SUM, group=comm_group)
        torch.cuda.synchronize()
    start = torch.cuda.Event(enable_timing=True)
    end   = torch.cuda.Event(enable_timing=True)
    tensor = torch.ones(args.message_size).cuda()
    tensor = tensor * args.rank
    torch.distributed.barrier(comm_group)
    start.record()
    dist.all_reduce(tensor, op=dist.ReduceOp.SUM, group=comm_group)
    end.record()
    torch.cuda.synchronize()
    t = start.elapsed_time(end)
    print('Rank '+str(args.rank)+' has data '+str(tensor[0])+' time cost '+str(t)+' bandwidth '+str(args.message_size*4/t/1000/1000), flush=True)
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by gcramer23** [comment]
Hi @lhb8125, can you post the results of running the collect environment script?

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py

Also, post the results showing that the bandwidth is decreasing as the count of groups increases.

**Comment by pritamdamania87** [comment]
@lhb8125 Could you share which communication backend you are using? Note that using multiple ProcessGroups with NCCL is not safe: https://pytorch.org/docs/stable/distributed.html#torch.distributed.new_group

**Comment by lhb8125** [comment]
Thanks for your reply, now I found the problem, which was caused by a previous NCCL version.
When I launch multiple communicators, they could choose the same network port, which cause the decrease of bandwidth.

**Comment by gcramer23** [comment]
I am closing the issue because lhb8125 identified the problem.
