### ISSUE TITLE
quantize_per_tensor returns inconsistent results on ARM for quint8

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#60077]
## 🐛 Bug

`quantize_per_tensor` returns tensor filled with different values while quantizing `torch.ones(10) * 2**32`:
```
$ python3 -c "import torch;print(torch.torch.quantize_per_tensor(torch.ones(10) * 2**32, 0.5, 1, torch.quint8))" 
tensor([127.0000, 127.0000, 127.0000, 127.0000, 127.0000, 127.0000, 127.0000,
        127.0000,  -0.5000,  -0.5000], size=(10,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=1)
```

This happens because of the integer overflow here:
https://github.com/pytorch/pytorch/blob/9fbbab88da8c1affa0fe6f71ea0951a549f7751c/aten/src/ATen/native/quantized/affine_quantizer_base.cpp#L124

## Expected behavior
```
$ python3 -c "import torch;print(torch.torch.quantize_per_tensor(torch.ones(10) * 2**32, 0.5, 1, torch.quint8))" 
tensor([127., 127., 127., 127., 127., 127., 127., 127., 127., 127.],
       size=(10,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.5, zero_point=1)
```

cc @malfet @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Thanks for the upcoming fix - assigning to you!
