### ISSUE TITLE
Profiler does not contain NCCL kernel

### ISSUE THREAD

**Issue by Rivendile** [pytorch/pytorch#60084]
## To Reproduce

1. I use pytorch.profiler to profile a horovod distributed training using pytorch 1.9.0 as follows. But there is no nccl kernel and streams other than the default one, 7.
```
    with torch.profiler.profile(
        schedule=torch.profiler.schedule(
            wait=1,
            warmup=2,
            active=7),
        on_trace_ready=torch.profiler.tensorboard_trace_handler('./logs'),
        record_shapes=True
    ) as prof:
        training code
        prof.step()
```
The profiling results are correct when I change the pytorch version from 1.9.0 to 1.8.1, though the speed of pytorch.profiler in 1.8.1 is extremely slow.

## Environment
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.28

Python version: 3.7 (64-bit runtime)
Python platform: Linux-4.19.117.bsk.6-amd64-x86_64-with-debian-10.9
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect

Any suggestions?

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by gdankel** [comment]
@Rivendile Thanks for reporting. We'll look into it.

**Comment by Rivendile** [comment]
Besides, could you please tell me what the Wall Duration and self time means in traces? It seems that the Wall Duration is the call time of kernel in streams for distributed training. Is this right?

**Comment by gaoteng-git** [comment]
> Besides, could you please tell me what the Wall Duration and self time means in traces? It seems that the Wall Duration is the call time of kernel in streams for distributed training. Is this right?
Which "Wall Duration" do you mean? If using [Tensorboard plugin](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html?highlight=tensorboard) to see profiled result, in operator view's table, "Device Self Duration" is sum of all kernels' execution time, and these kernels are  launched **directly** by this operator, the kernels that launched by this op's children operators are not counted. "Device Total Duration" count this op its self and all children operators launched kernels time.
The detailed readme is [here](https://github.com/pytorch/kineto/tree/master/tb_plugin).

![image](https://user-images.githubusercontent.com/10429114/124071079-6c6a5680-da71-11eb-82bf-26c3d2c5a303.png)

**Comment by sraikund16** [comment]
<img width="1371" alt="Screenshot 2024-05-02 at 12 56 24 PM" src="https://github.com/pytorch/pytorch/assets/57577085/2c8f2a05-1281-4616-9e26-952f4bb325a5">
It looks like this issue has gone stale and is no longer relevant
