### ISSUE TITLE
`torch.jit.isinstance` doesn't account for tuple literals in eager mode

### ISSUE THREAD

**Issue by ansley** [pytorch/pytorch#60095]
## 🐛 Bug

In Python, `isinstance` can be used with a single element or a tuple of elements. `torch.jit.isinstance` doesn't consider the case that we want to compare against a tuple of elements.

## Example

```python
import torch
from typing import List

def fn(x: int):
    if torch.jit.isinstance(x, (List[str], str)):
        z = x + "bar"
        return z
    else:
        return "baz"
```

The above example errors out with:
```
Traceback (most recent call last):
  File "test/tinytest.py", line 11, in <module>
    print(fn(1))
  File "test/tinytest.py", line 5, in fn
    if torch.jit.isinstance(x, (List[str], str)):
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/__init__.py", line 185, in isinstance
    return _isinstance(obj, target_type)
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/_jit_internal.py", line 1145, in _isinstance
    return isinstance(obj, target_type)
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/home/ansley/local/miniconda3/envs/pytorch/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

Note that this is only a problem in eager (Python) mode. If you run it in script (`torch.jit.script`) mode, it will be fine.

## Notes

This would be a nice introduction to the PyTorch codebase. I'm writing notes here with the idea that this would be an OSS project or a Bootcamp task.

Our implementation of `torch.jit.isinstance` is at `torch/_jit_internal.py:_isinstance`. In `_isinstance`, if `target_type` is a tuple literal, the logic falls through to the line `return isinstance(obj, target_type)`, which fails for "subscripted generics". A "subscripted generic" is a type annotation that has other types inside it, e.g. `List[int]`, `Dict[str, int]`, `Optional[int]`. (Some examples of types that are NOT subscripted generics are `int`, `str`, etc.)

What we want to do is: Check if current element is a tuple literal containing types. If we do have a tuple literal, try calling `_isinstance` on all types in the tuple. If any of the elements in the tuple are subtypes of the current element, return `true`, else return `false`.

I haven't coded this up myself. If my suggested algorithm breaks everything and you want to yell at me, reach out at `ansley@fb.com`

cc @gmagogsfm

**Comment by karolsputo** [comment]
I'll take a stab at it

**Comment by karolsputo** [comment]
@ansley I've posted a PR following your proposed solution that might solve this, but after some analysis I've found that this is a bit tricky and might cause problems across python versions.

Some perhaps useful discussion:
https://stackoverflow.com/questions/53854463/python-3-7-check-if-type-annotation-is-subclass-of-generic
and interesting implementations:
https://github.com/ilevkivskyi/typing_inspect

I'm not quite sure what is the desired behaviour, but I think it works now. 

Here is a combination of some inputs and their outcomes 
```
(List[str], str) -> False
(List[str], (List[int], str), str -> False
(List[str], (int, str), str) -> True
```
