### ISSUE TITLE
How to install torchaudio on Mac M1 ARM?

### ISSUE THREAD

**Issue by suissemaxx** [pytorch/pytorch#60115]
`torchaudio` doesn't seem to be available for Mac M1. 

If I run `conda install pytorch torchvision torchaudio -c pytorch` (as described on pytorch's main page) I get this error message:

```
PackagesNotFoundError: The following packages are not available from current channels:
  - torchaudio 
```
If I run the command without `torchaudio` everything installs fine.

How can I fix this and install torchaudio too? 

If it isn't available (yet) – do you have any plans to release it too?

Thanks in advance for your help! And I apologize in advance if I don't see the forest for the trees and overlooked sth. obvious.

**Comment by H-Huang** [comment]
Hi, this issue is being tracked on the torchaudio repository, https://github.com/pytorch/audio/issues/1573, please add input there.
