### ISSUE TITLE
[JIT] Implement derivatives for all point-wise operaters

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#6012]
Point-wise operators are those that are considered fusible by the JIT.

Why? We can't do most optimizations for operators without derivatives and shape analysis, but by implementing just these operators, we enable most things to work.

What are point-wise?
torch/csrc/jit/passes/graph_fuser.cpp

Where are derivative patterns added?
torch/csrc/jit/autodiff.cpp

How do I test this?
testADFormulas in torch/csrc/jit/test_jit.cpp

**Comment by zdevito** [comment]
@bddppq

**Comment by vishwakftw** [comment]
Is this issue taken and currently under development?

I would like to take it up if otherwise. Thanks.

**Comment by apaszke** [comment]
I think this is currently assigned to @bddppq.

**Comment by eellison** [comment]
I believe this has been fixed through symbolic_script.cpp.
