### ISSUE TITLE
pytorch 1.9 wont appears to install on conda

### ISSUE THREAD

**Issue by seyeeet** [pytorch/pytorch#60126]
## 🐛 Bug

I just instlled anaconda and I tried to install pytorch 1.9 for cuda 10.2.
But it suggest me to install pytorch 1.7
I tried to do  
`conda install pytorch=1.9.0  torchvision torchaudio cudatoolkit=10.2 -c pytorch`
but  it still does not work.

## To Reproduce
just create a new env and try to install pytorch from conda

## Expected behavior
Instead of showing pytorch 1.9 it is suggesting to install 1.7

## Environment

 - PyTorch Version (e.g., 1.0): trying to install 1.9
 - OS (e.g., Linux):Linux
 - How you installed PyTorch (`conda`, `pip`, source): want to use conda/anaconda
 - Build command you used (if compiling from source):
 - Python version: 3.6.6 (but open to upgrade it if needed)
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Titan

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.6.1810 (Core)  (x86_64)
GCC version: (GCC) 8.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.9

Python version: 3.6 (64-bit runtime)
Python platform: Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py36h90e4bf4_5
[conda] mkl_fft                   1.0.4            py36h4414c95_1
[conda] mkl_random                1.0.1            py36h4414c95_1
[conda] numpy                     1.15.1           py36h3b04361_0
[conda] numpy-base                1.15.1           py36h81de0dd_0
[conda] numpydoc                  0.8.0                    py36_0
```

```
(pytorch1.9) [seyeeet@home~]$ conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/anaconda3/envs/pytorch1.9

  added / updated specs:
    - cudatoolkit=10.2
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.2.89        |       hfd86e86_1       365.1 MB
    dataclasses-0.8            |     pyh4f3eec9_6          22 KB
    ninja-1.10.2               |       hff7bd54_1         1.4 MB
    pytorch-1.7.1              |py3.6_cuda10.2.89_cudnn7.6.5_0       575.6 MB  pytorch
    torchaudio-0.7.2           |             py36         9.8 MB  pytorch
    torchvision-0.8.2          |       py36_cu102        17.8 MB  pytorch
    ------------------------------------------------------------
                                           Total:       969.8 MB
```

**Comment by seyeeet** [comment]
as I mentioned above I could not install it when I did 
`conda install pytorch=1.9.0 torchvision torchaudio cudatoolkit=10.2 -c pytorch`

but it seems like it is working if I do the steps separately, meaning that:
- `conda install cudatoolkit=10.2 -c pytorch`
- `conda install --insecure pytorch -c pytorch`
`conda install --insecure  torchvision torchaudio  -c pytorch`

**Comment by brando90** [comment]
> as I mentioned above I could not install it when I did
> `conda install pytorch=1.9.0 torchvision torchaudio cudatoolkit=10.2 -c pytorch`
> 
> but it seems like it is working if I do the steps separately, meaning that:
> 
> * `conda install cudatoolkit=10.2 -c pytorch`
> * `conda install --insecure pytorch -c pytorch`
>   `conda install --insecure  torchvision torchaudio  -c pytorch`

I doubt this did what you expected (install 1.9). For me removing the strict requirement for 1.9 automatically install 1.8 for some reason. Can you print what version you actually installed?

**Comment by brando90** [comment]
why not try pip?

```
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

perhaps that works...

**Comment by brando90** [comment]
```
Successfully installed numpy-1.21.2 pillow-8.3.2 torch-1.9.0+cu111 torchaudio-0.9.0 torchvision-0.10.0+cu111 typing-extensions-3.10.0.2
(metalearning2) miranda9~/automl-meta-learning $ pip list | grep torch
torch             1.9.0+cu111
torchaudio        0.9.0
torchvision       0.10.0+cu111
```

**Comment by JulesVerny** [comment]
If I attempt to install pytorch on Windows via Conda, it will only install pytorch 1.6.0 (CPU).
conda install -c conda-forge pytorch only offer pytorch 1.6.0 (CPU)

I cannot get pytorch 1.9.1 to install on Windows within a Conda environment, or for pytorch to recognise CUDA 11 enabled device.  Pip install are no better.

**Comment by acb08** [comment]
I am having the same issue that JulesVerny mentions. Specifically, I used `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
`, and the installation looked like it went successfully. When I try to update my version within an environment, though, the latest version showing up in Anaconda is 1.6. I've done the simple stuff like closing/reopening my IDE and anaconda and restarting.
