### ISSUE TITLE
[CI stats] sharded test skew in test1/2 

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#60136]
Currently the test1/2 are skewed because of the fact that distributed/* tests are not ran just once but they are reported as if they are ran just once. 

This is because:
https://github.com/pytorch/pytorch/blob/5f017e91b890c897107e2a479d274fcda5a3024b/test/run_test.py#L669

runs against different backends (mpi, gloo, nccl) and whether init files is provided (e.g. one test file were invoked 6 times at maximum)

We should either 
1. collect the total runtime across all combination of distributed/test_[spawn/fork].*
2. just dont count distributed/test_[spawn/fork] during shard compute

CC @janeyx99 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by walterddr** [comment]
also question, do we really need to run all 6 combination during CI for PR? cc @mruberry

**Comment by mruberry** [comment]
> also question, do we really need to run all 6 combination during CI for PR? cc @mruberry

We should ask someone from the distributed team. I'd actually like to consider moving distributed and RPC tests to their own jobs. They're very flaky.

**Comment by walterddr** [comment]
This is fixed by #60206. specifically, see:
https://app.circleci.com/pipelines/github/pytorch/pytorch/339308/workflows/261d5f9e-ed64-444f-a9ce-ff98a06d2daf/jobs/14262098 vs
https://app.circleci.com/pipelines/github/pytorch/pytorch/339308/workflows/261d5f9e-ed64-444f-a9ce-ff98a06d2daf/jobs/14262097
