### ISSUE TITLE
DISABLED test_ddp_logging_data_cpu (__main__.TestDistBackendWithFork)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#60130]
## 🐛 Bug

Example failures:
https://app.circleci.com/pipelines/github/pytorch/pytorch/337673/workflows/db188d30-2c92-4faf-ac2a-e90b70d1e8c2/jobs/14187632
https://app.circleci.com/pipelines/github/pytorch/pytorch/337701/workflows/6e6161a7-7346-403a-a458-97f5e7970279/jobs/14188746
https://app.circleci.com/pipelines/github/pytorch/pytorch/337710/workflows/3f835c0e-ad07-45fd-9ede-dec90c043bb3/jobs/14188742

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
cc @zhaojuanmao

**Comment by imaginary-person** [comment]
The title says that this test has been disabled, but it's still enabled.

**Comment by zhaojuanmao** [comment]
the error does not show a flakiness, but some deterministic error. does it happen in Master?

**Comment by imaginary-person** [comment]
In #56992, it occurred in 2 CI checks. That draft PR has PRs from the master branch upto #60048, which was merged 4 hours ago.

**Comment by rohan-varma** [comment]
@imaginary-person I think that's the spawn version of the test, will send an issue to disable that as well.

**Comment by imaginary-person** [comment]
Oops, sorry! You're right.

**Comment by ezyang** [comment]
another failure https://app.circleci.com/pipelines/github/pytorch/pytorch/337678/workflows/9902a2d4-44b8-469a-bebc-468a1f5d0335/jobs/14187682

**Comment by zhaojuanmao** [comment]
tried to run 100 times locally and can not reproduce it

**Comment by zhaojuanmao** [comment]
closing it as it can not be reproduced locally, will see whether there is flakiness
