### ISSUE TITLE
DISABLED test_ddp_logging_data_cpu (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#60140]
## 🐛 Bug

see https://github.com/pytorch/pytorch/issues/60130

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by zhaojuanmao** [comment]
can not reproduce locally, closing it for now, will debug if flakiness is found again
