### ISSUE TITLE
Using Libtorch and ROS together causes library error

### ISSUE THREAD

**Issue by Pyrojambo** [pytorch/pytorch#60178]
## 🐛 Bug

When attempting to link the torch headers to a ROS (Robot Operating System) C++ executable, the torch libraries seem to remove the ROS libraries that I attempt to link. This causes undefined references to ROS functions such as `ros::init()` and `ros::NodeHandle::NodeHandle()`.

## To Reproduce

1. Install ROS Melodic
1. Install libtorch or build pytorch from source
1. Include torch in a ROS node and link libraries to the ROS executable. I have a basic example here [torch_ros_test repo](https://github.com/Pyrojambo/torch_ros_test) that can be used
2. Build ROS node with `catkin_make`

This gives an error similar to:
```
[100%] Linking CXX executable /home/james/Documents/catkin_ws/devel/lib/torch_ros/torch_ros
CMakeFiles/torch_ros.dir/src/torch_ros.cpp.o: In function `TorchRos::TorchRos()':
/home/james/Documents/catkin_ws/src/torch_ros/src/torch_ros.cpp:3: undefined reference to `ros::NodeHandle::NodeHandle(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
CMakeFiles/torch_ros.dir/src/torch_ros.cpp.o: In function `main':
/home/james/Documents/catkin_ws/src/torch_ros/src/torch_ros.cpp:10: undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
collect2: error: ld returned 1 exit status
torch_ros/CMakeFiles/torch_ros.dir/build.make:129: recipe for target '/home/james/Documents/catkin_ws/devel/lib/torch_ros/torch_ros' failed
make[2]: *** [/home/james/Documents/catkin_ws/devel/lib/torch_ros/torch_ros] Error 1
CMakeFiles/Makefile2:8630: recipe for target 'torch_ros/CMakeFiles/torch_ros.dir/all' failed
make[1]: *** [torch_ros/CMakeFiles/torch_ros.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j 12" failed
```

## Expected behavior

If the [line in CMakeLists.txt](https://github.com/Pyrojambo/torch_ros_test/blob/35ebf3cef0292f830ebf1d3b698cc274574e73b8/CMakeLists.txt#L41) linking the torch libraries to the executable is commented out, it will build with no errors. The same would be expected when it is uncommented, but as soon as the libraries are linked it fails

## Environment
 - PyTorch Version (e.g., 1.0): 1.9.0 (but 1.8.0 and 1.8.1 both do the same)
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): Tried both ABI versions libtorch download, and built from source
 - Build command you used (if compiling from source): cmake
 - Python version: 3.6.9 and 2.7.17
 - CUDA/cuDNN version: 10.2 / v8.2.0
 - GPU models and configuration: Nvidia GeForce RTX 3060 Laptop
 - Any other relevant information: ROS Melodic

## Additional context

I've seen the same sort of issue raised before but the issues are either closed or stale without a resolution. [Downgraded torch version](https://github.com/pytorch/pytorch/issues/49450), [unsolved](https://github.com/pytorch/pytorch/issues/22197).

I cannot use an earlier version of Pytorch as I need features that were added in 1.8.0

cc @malfet @seemethere @walterddr

**Comment by Pyrojambo** [comment]
I removed any trace of pytorch and libtorch from machine and built again from source. It worked that time, so it may have just been a left over reference to the pre-built libtorch libraries

**Comment by fettahyildizz** [comment]
@Pyrojambo Could you please elaborate the steps? Which version of libtorch and pytorch you build from source? I'm having same issue.

**Comment by Cfisher-T** [comment]
Have you solved it yet? I have been troubled by this question for a long time and hope to receive your reply.
