### ISSUE TITLE
[ppc64le] test_dim_reduction fails on ppc64le

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#6018]
hi ,  I am seeing the following on ppc64le with GPU.

I think this was due to ATen ReduceOps (#5776)   or  

FAIL: test_dim_reduction (test_torch.TestTorch)

Traceback (most recent call last):
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/test_torch.py", line 543, in test_dim_reduction
    self._test_dim_reduction(self, lambda t: t)
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/test_torch.py", line 444, in _test_dim_reduction
    self.assertEqual(x.sum().item(), 16)
  File "/home/freddie/builder/jenkins/pytorch/pytorch/test/common.py", line 271, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 1 not less than or equal to 1e-05 :

----------------------------------------------------------------------
Ran 1 test in 0.005s

**Comment by goldsborough** [comment]
CC @cpuhrsch

**Comment by cpuhrsch** [comment]
Try rebasing and rebuilding if you haven’t already. We fixed a similar issue recently.

**Comment by avmgithub** [comment]
@cpuhrsch  the latest one I pulled was a5891800217f9d0fd712e48e6d180c4e6409cb3f ,  it still has the problem

**Comment by avmgithub** [comment]
@cpuhrsch if it helps the test is failing when the test is using torch.ByteTensor in https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L444

**Comment by cpuhrsch** [comment]
@avmgithub yes that helps a lot. This happens presumably because the test basses "-1" to ByteTensor as part of the example.

**Comment by avmgithub** [comment]
closing , fixed
