### ISSUE TITLE
Docs of torch.Tensor.permute refer to docs of torch.permute for which do not exist

### ISSUE THREAD

**Issue by Haydnspass** [pytorch/pytorch#60181]
## 📚 Documentation

Docs of torch.Tensor.permute refer to docs of torch.permute for which do not exist
Functional implementation is present though.

https://pytorch.org/docs/stable/generated/torch.Tensor.permute.html?highlight=torch%20permute#torch.Tensor.permute

cc @brianjo @mruberry

**Comment by zou3519** [comment]
@Haydnspass please feel free to submit a fix for this if you are up for it
