### ISSUE TITLE
Pytorch 1.9 Profiler generate invalid separator path inside JSON using tensorboard_trace_handler.

### ISSUE THREAD

**Issue by BurguerJohn** [pytorch/pytorch#60187]
## 🐛 Bug

On windows, tensorboard_trace_handler use the separador \  in the file path instead of / or \\\ breaking the json file.

## To Reproduce

1. Setup the Profiler. Example:
`with torch.profiler.profile(
    activities=[
        torch.profiler.ProfilerActivity.CPU,
        torch.profiler.ProfilerActivity.CUDA],
    schedule=torch.profiler.schedule(
        wait=2,
        warmup=3,
        active=6),
    on_trace_ready=torch.profiler.tensorboard_trace_handler('./result', worker_name='worker0'),
    record_shapes=True,
    profile_memory=True,
    with_stack=True
  ) as p:`

2. Use Kineto to try to profile the file `tensorboard --logdir=./result`
3. It throw the error on windows: `json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 371)`

## Expected behavior

To escape the separator correctly on the json file. Ex: \\\

## Environment

```
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.3.5
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.3.2
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @peterjc123 @mszhanyi @skyline75489

**Comment by zou3519** [comment]
Seems high pri that the profiler doesn't work on windows, but I'm not sure if this is something we support

**Comment by BurguerJohn** [comment]
No problem, is a easy enough fix by hand. Just replace \ to \\\ and it works

**Comment by gchanan** [comment]
this should be under visualization not profiler?

**Comment by gdankel** [comment]
@BurguerJohn can you please attach the beginning of the json file as well (including the bad line).

**Comment by BurguerJohn** [comment]
[worker0.1624305603818.pt.trace.zip](https://github.com/pytorch/pytorch/files/6689195/worker0.1624305603818.pt.trace.zip)
@gdankel Here is the file (had to zip it) generated from the code:

```
from torch.profiler import profile
    with torch.profiler.profile(
      activities=[
          torch.profiler.ProfilerActivity.CPU,
          torch.profiler.ProfilerActivity.CUDA],
      schedule=torch.profiler.schedule(
        wait=1,
        warmup=1,
        active=2),
      on_trace_ready=torch.profiler.tensorboard_trace_handler('./result', worker_name='worker0'),
      record_shapes=True,
      profile_memory=True,
      with_stack=True
    ) as p:
      for _ in range(0, 2):
        a = numpy.array([1, 2, 3])
        t = torch.from_numpy(a)
        p.step()
```

Using the command `tensorboard --logdir=./result` it generate the error `json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 368)`

**Comment by gdankel** [comment]
Thanks for the trace - OK so this is with callstacks enabled, makes sense. We will look at where best to address this. cc @guotuofeng

**Comment by guotuofeng** [comment]
@gdankel, it seems that we need escape the backward slash into double backward slash or forward slash when generating the call stack.

**Comment by gdankel** [comment]
Yes that's the logical place. Alternatively we can do it for all strings when writing to json. There may be other chars that need escaping too.
Or we can adopt a public json package which presumably guarantees valid json.

**Comment by guotuofeng** [comment]
PR https://github.com/pytorch/pytorch/pull/60842 replace the "\\" to "/". It should fix this bug.
