### ISSUE TITLE
torch.vander() does not support autograd

### ISSUE THREAD

**Issue by p-patil** [pytorch/pytorch#60197]
## 🐛 Bug

When the computation graph involves `torch.vander()`, gradients are unable to flow through this operation, causing autograd to crash.

## To Reproduce

```
import torch
x = torch.tensor([1.0, 2.0], requires_grad=True)  # Dummy input
v = torch.vander(x, N=4, increasing=True)
loss = v.sum()
loss.backward()
```
This code crashes with the error:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 3]], which is output 0 of SliceBackward, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

In contrast, this equivalent code works as expected:
```
import torch
x = torch.tensor([1.0, 2.0], requires_grad=True)  # Dummy input
v = torch.stack([x**0, x, x**2, x**3], dim=1)
loss = v.sum()
loss.backward()
```

## Environment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: 11.1.0
CMake version: version 3.20.2
Libc version: glibc-2.33

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.12.6-arch1-1-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] torch==1.9.0
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by zou3519** [comment]
Is this supposed to be differentiable? if so, we probably just need to rewrite the implementation of vander to support autograd

**Comment by nikitaved** [comment]
Yes, the entries of the Vandermond matrix are polynomials of the input entries, so we can implement backward for it.

**Comment by ezyang** [comment]
cc @jessebrizzi

**Comment by neithen-Lu** [comment]
Hi! Any updates on the vander issue? We tested the vander function recently and still find the exact same error message.

**Comment by Lezcano** [comment]
Sorry, I completely missed this one! I will put up an implementation soon :)
