### ISSUE TITLE
ROCm: test_torch.py test_masked_scatter_large_tensor failed

### ISSUE THREAD

**Issue by jaglinux** [pytorch/pytorch#60190]
python3.6 test/test_torch.py TestTorchDeviceTypeCUDA.test_masked_scatter_large_tensor_cuda -v

test_masked_scatter_large_tensor_cuda (__main__.TestTorchDeviceTypeCUDA) ...
/home/pytorch/aten/src/ATen/native/hip/IndexKernel.hip:373: masked_scatter_size_check: Device-side assertion `*totalElements <= srcSize' failed.
:0:rocdevice.cpp            :2502: 834917584587 us: Device::callbackQueue aborting with error : HSA_STATUS_ERROR_EXCEPTION: An HSAIL operation resulted in a hardware exception. code: 0x1016
Aborted (core dumped)

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jaglinux** [comment]
@arindamroy-eng @jithunnair-amd

**Comment by jaglinux** [comment]
Printing the variables in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/IndexKernel.cu#L369
*totalElements is 281471681560578 and srcSize is 2147483649 (and hence the kernel assert)

**Comment by jaglinux** [comment]
The test case https://github.com/pytorch/pytorch/pull/58865 was added recently through https://github.com/pytorch/pytorch/pull/58865

**Comment by jithunnair-amd** [comment]
Issue seems to be related to hipcub. AMD internal JIRA to track the issue: https://ontrack-internal.amd.com/browse/SWDEV-290458
