### ISSUE TITLE
[torch.profiler] non-context manager use

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60238]
## 🚀 Feature

I need to embed the profiler around a huge training loop and to make it optional. So context manager isn't a good option here. And there are already some 5 indentation levels for the code to be wrapped, so for the sake of readability I'd rather not use some noop context manager.

Would it be possible to expose the enter/exit API as public (probably as start/stop) so that one could do:
```
if profile_enable:
    p = profiler.start()
normal multi-line code here
if profile_enable:
    p.stop()
```

Thank you!

@gaoteng-git 

cc @ilia-cher @gdankel @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by guotuofeng** [comment]
we will add non-context manager support in next release.

**Comment by guotuofeng** [comment]
we will close this issue since it is tracked in kineto repo.
