### ISSUE TITLE
dispatch order for custom ops

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/pytorch#60255]
## Summary

For aten ops, we know "AutoCast"'s  priority is higher than "Tracer".
But for custom ops, "Tracer" will get the highest priority.

## Consequence

The dtype cast under "autocast" context cannot be recorded on graph.

## Example

Suppose we have custom functions below (just return the first input of it)

```
at::Tensor AtenIpexTypeExt::my_custom_op(
    const at::Tensor &input1, 
    const at::Tensor &input2) {
  return input1;
}

static auto dispatch = torch::RegisterOperators()
        .op("torch_ipex::my_custom_op", &torch_ipex::my_custom_op);
}
```

We register an auto-cast function for this custom op to convert the inputs (like convert to at::BFloat16)

```
at::Tensor AtenIpexTypeExt::my_custom_op(
    const at::Tensor &input1, 
    const at::Tensor &input2) {
  c10::impl::ExcludeDispatchKeyGuard no_autocastCPU(DispatchKey::AutocastCPU);
  static auto op = torch::Dispatcher::singleton()
    .findSchemaOrThrow("torch_ipex::my_custom_op", "")
    .typed<decltype(my_custom_op)>();
  auto target_type = get_autocast_dtype();
  auto casted_i1 = cpu_cached_cast(target_type, input1);
  auto casted_i2 = cpu_cached_cast(target_type, input2);
  return op.call(casted_i1, casted_i2);
}

TORCH_LIBRARY_IMPL(torch_ipex, AutocastCPU, m){
  m.impl("my_custom_op", torch_ipex::autocast::my_custom_op);
}
```

And if we run trace under amp context

```
input1 = torch.rand(3,3)
input2 = torch.rand(3,3)

class M(nn.Module):
    def __init__(self):
        super(M, self).__init__()

    def forward(self, x1, x2):
        return torch.ops.torch_ipex.my_custom_op(x1,x2)

my_custom_mod = M()

with AMP_ENABLED, torch.no_grad():
    traced= torch.jit.trace(my_custom_mod, [input1, input2])

print(traced.graph)

```

The "to" in autocast function will not be recorded on graph:

```
graph(%self : __torch__.M,
      %x1 : Float(3, 3, strides=[3, 1], requires_grad=0, device=cpu),
      %x2 : Float(3, 3, strides=[3, 1], requires_grad=0, device=cpu)):
  %5 : BFloat16(3, 3, strides=[3, 1], requires_grad=0, device=cpu) = torch_ipex::my_custom_op(%x1, %x2) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  return (%5)
```

## Expected result:
After using the workaround in https://github.com/pytorch/pytorch/pull/60251

Will get expect result (which "to" is also showed on graph)

```
graph(%self : __torch__.M,
      %x1 : Float(3, 3, strides=[3, 1], requires_grad=0, device=cpu),
      %x2 : Float(3, 3, strides=[3, 1], requires_grad=0, device=cpu)):
  %5 : int = prim::Constant[value=15]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %6 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %7 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %8 : NoneType = prim::Constant()
  %9 : BFloat16(3, 3, strides=[3, 1], requires_grad=0, device=cpu) = aten::to(%x1, %5, %6, %7, %8) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %10 : int = prim::Constant[value=15]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %11 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %12 : bool = prim::Constant[value=0]() # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %13 : NoneType = prim::Constant()
  %14 : BFloat16(3, 3, strides=[3, 1], requires_grad=0, device=cpu) = aten::to(%x2, %10, %11, %12, %13) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  %15 : BFloat16(3, 3, strides=[3, 1], requires_grad=0, device=cpu) = torch_ipex::my_custom_op(%9, %14) # /home/haozhezh/cpu-device/frameworks.ai.pytorch.ipex-cpu/test_custom.py:13:0
  return (%15) 
```

**Comment by zhuhaozhe** [comment]
Hi, @jgong5 @leslie-fang-intel.

For custom ops will first "trace" then "dispatch according by dispatch key"
I have add an simple case to explain consequence.

**Comment by jgong5** [comment]
Hi @ezyang : we wanted to generate a tracing graph under autocast with some custom ops, but we failed to get the type casting nodes in the resulting graph as expected due to the dispatching logic. Is it a known issue? Any suggestions? Thanks. Also copy @ailzhang

**Comment by ezyang** [comment]
Oh, I have a sneaking suspicion this is because we never implement tracing as a boxed fallback, cc @bdhirsh

**Comment by ailzhang** [comment]
@ezyang Did you mean that if we implement tracing as boxed fallback, custom ops and native ops can be universally handled there instead of being codegen-ed (thus no support for custom ops now)?

**Comment by ezyang** [comment]
So the problem is that custom ops ARE supported for tracing, but it's done "above" the dispatcher (in the parsing code that takes Python objects to IValues). This causes the ordering problem when you want to see the trace below AMP.

**Comment by jgong5** [comment]
> So the problem is that custom ops ARE supported for tracing, but it's done "above" the dispatcher (in the parsing code that takes Python objects to IValues). This causes the ordering problem when you want to see the trace below AMP.

That's correct. The Autocast key is supposed to have a higher priority than tracing. It is true and expected for the proper ATen ops but not for custom ops.
