### ISSUE TITLE
Libtorch cpp to use with visual studio 2015

### ISSUE THREAD

**Issue by SylvainArd** [pytorch/pytorch#60257]
Hello all !
I want the libtorch cpp (not python) version to compile with Visual Studio 2015. I can’t find that, could you help me please ?
Thank you
Best regards

**Comment by skyline75489** [comment]
I think you'll need old version, for example 1.6.0. Check out #59607

**Comment by SylvainArd** [comment]
your link is for linux !

**Comment by SylvainArd** [comment]
and I want to be sure of the version, what versions are compatibles with VS2015 ?

**Comment by skyline75489** [comment]
Sure, the windows link is just changing `libtorch` to `libtorch-win`. For example: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.6.0%2Bcpu.zip

**Comment by SylvainArd** [comment]
and you're sure that the 1.6 is compatbible with vs2015 ?

**Comment by SylvainArd** [comment]
no 1.6 is only compatible with vs2017

**Comment by SylvainArd** [comment]
I don't want to test versions one by one

**Comment by skyline75489** [comment]
Runtime-wise, VS2015 - VS2019 share the same VCRedist so the DLLs should load without issue. But compilation-wise, you may need go to back more versions and probably having issues that we can't really help.

You see, the PyTorch Windows support was added in version 0.3 at the the year of 2018 (see https://github.com/pytorch/pytorch/issues/494#issuecomment-350527200) when I think VS 2017 is the mainstream version of VS. This should give you some basic idea how old VS 2015 is.

**Comment by SylvainArd** [comment]
OK thank you in fact I try to compile an old source linux code on Windows
but some parts were only compatibles with VS2015 and it need libtorch, I
will try to upgrade the code tio vs2019
Sylvain Ard
0549507724
0778380991
***@***.***
http://sylvain-ard.fr
Entreprise individuelle SIRET : 80079243400022
Appt 26 Bât A Résidence Le Patio
83 rue de la Bugellerie
86000 Poitiers


Le ven. 18 juin 2021 à 12:23, Chester Liu ***@***.***> a
écrit :

**Comment by gchanan** [comment]
“Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/”
