### ISSUE TITLE
Improved documentation of distributed launch utility

### ISSUE THREAD

**Issue by moskomule** [pytorch/pytorch#60262]
## 📚 Documentation

Hi, thank you for maintaining and developing PyTorch!

When I updated PyTorch to v1.9 and ran a distributed training using `torch.distributed.launch`, I got the following warning.

```
The module torch.distributed.launch is deprecated and going to be removed in future. Migrate to torch.distributed.run
```

The documentation (https://pytorch.org/docs/stable/distributed.html?highlight=distributed#launch-utility) says the launch utility is still `torch.distributed.launch`. It would be great if the documentation introduces https://pytorch.org/docs/stable/elastic/run.html. 

cc @brianjo @mruberry @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by kiukchung** [comment]
Thanks for reporting! We are aware of this confusing doc issue and are actively working on remediating it. Please track our progress in https://github.com/pytorch/pytorch/issues/60754. Closing in favor of 60754.
