### ISSUE TITLE
Python interface for TensorUtils.h check* functions

### ISSUE THREAD

**Issue by sdrobert** [pytorch/pytorch#60271]
## 🚀 Feature
Provide a python interface for the `check*` functions from `aten/src/ATen/TensorUtils.h`. e.g.

``` python
torch.utils.check.check_dim(__func__, (tensor, 'name', pos), 3)
```

## Motivation

Designing reusable, robust, custom `torch.nn.Module`, `torch.autograd.Function`, or simple functions can involve lots of boilerplate for things like checking the dimensions of tensors, size of tensors, and their devices. Rewriting this code is tedious, bloats code, and can lead to non-standardized error messages.

## Pitch

With the possible exception of how to handle `at::TensorArgs` objects, exposing the utilities already found in `TensorUtils.h` to the python interface should not take much development effort and almost no upkeep. Ideally they are directly accessed through pybind11, but they can also be easily recreated in pure python. Hopefully providing such functionality will not only save time for independent developers like myself, but for the core team as well.

## Alternatives

Copy-pasting the same code over and over again.

## Additional context

N/A

Thanks very much for your time.

**Comment by gchanan** [comment]
CC @ezyang

**Comment by ezyang** [comment]
I'm a bit ambivalent about directly binding the C++ implementations to Python: the C++ implementations are definitely a product of "how to implement reasonable C++ error reporting in C++" and have a lot of affordances that are unnecessary or don't make sense in Python (e.g., `__file__` reporting: you don't need that because a Python backtrace automatically comes with that information). I've also wanted to rip out replace all of these APIs with https://github.com/pytorch/pytorch/issues/37160 so there's that.

A reimplementation in Python might be OK. I suppose the main problem is bikeshedding the exact API to let people use. I might suggest you try making a little package (torchcheck) with a bunch of pure Python helpers along these lines and iterate on the API with some early users.

**Comment by sdrobert** [comment]
Thank you for your time in responding! I appreciate it.

I see where you're coming from with regards to porting TensorUtils.h. I can also write a bunch of those pure python helpers in a PR or something.

However, I'm worried that, were I to build my own package and iterate with early users as you say, it would rely on people actually using the package. I can't imagine someone searching out a separate package to systematize their error reporting. In addition, even if the API was refined, there's no guarantee that some dev wouldn't want to completely change things to better fit the PyTorch vision when I posted the PR.

With respect to bikeshedding, all I'd ask: is what motivations for the C++ interface warranted spending time refining runtime error checking that wouldn't also apply to Python?

In any event, I understand if this is more work than you think it is worth and thank you nonetheless for spending the time.

**Comment by ezyang** [comment]
> With respect to bikeshedding, all I'd ask: is what motivations for the C++ interface warranted spending time refining runtime error checking that wouldn't also apply to Python?

Yeah, there are a few of these (apply in C++ but not in Python):

* The error checking is typically for kernels (the stuff that is actually doing the honest for goodness computation), and kernels can only really be written in C++ for efficiency reasons.
* C++ stack traces are much less meaningful and you cannot as easily printf debug, so we have to report much more information eagerly (whereas in Python you can just edit the file to get any extra info you might need)
* Python has more expressivity, so stuff that would be a bunch of lines in C++ can be compactly written in one line in Python. (But I acknowledge that having these checks in a library can still be helpful).

> In any event, I understand if this is more work than you think it is worth and thank you nonetheless for spending the time.

I don't want to say never, but to put it in core is to commit to the API forever and I don't (personally) want to spend the time to get it all the way there XD. If you want to put up a researched proposal at https://github.com/pytorch/rfcs/ and drive the process of getting consensus that we like it, that would probably be a recipe to getting their eventually. But this is time consuming, and not guaranteed to succeed, and I also want to respect your time as well!

**Comment by sdrobert** [comment]
Fair enough. Sounds like a bigger hassle than I'd hoped, so I'll close this issue. Thanks again!
