### ISSUE TITLE
clamp is missing kwarg out

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#6028]
In PyTorch master:

```python
import torch
x = torch.randn(3, 3)
y = torch.empty_like(x)
torch.clamp(x, min=0, out=y)
```

```
TypeError: clamp() got an unexpected keyword argument 'out'
```

**Comment by Teaonly** [comment]
https://github.com/pytorch/pytorch/pull/6418 

Added clamp's output support in pre-template code.

**Comment by Teaonly** [comment]
'''
In [1]: import torch
   ...: x = torch.randn(3, 3)
   ...: y = torch.empty_like(x)
   ...: torch.clamp(x, min=0, out=y)
   ...:
Out[1]:

 2.4818  0.0000  0.0000
 1.7294  3.2200  0.0000
 0.0000  0.6117  1.4733
[torch.FloatTensor of size (3,3)]

In [2]: x
Out[2]:

 2.4818 -1.0297 -1.7378
 1.7294  3.2200 -0.6991
-0.4814  0.6117  1.4733
[torch.FloatTensor of size (3,3)]

In [3]: y
Out[3]:

 2.4818  0.0000  0.0000
 1.7294  3.2200  0.0000
 0.0000  0.6117  1.4733
[torch.FloatTensor of size (3,3)]
'''
