### ISSUE TITLE
torch.topk sorted does not work

### ISSUE THREAD

**Issue by Felix-Petersen** [pytorch/pytorch#60300]
## 🐛 Bug

The torch.topk sorted argument does not work.

## To Reproduce

```python
>>> import torch
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x10f0cc6b0>
>>> a = torch.randperm(10)
>>> a
tensor([4, 1, 7, 5, 3, 9, 0, 8, 6, 2])
>>> torch.topk(a, k=3, sorted=False)
torch.return_types.topk(
values=tensor([9, 8, 7]),
indices=tensor([5, 7, 2]))
>>> torch.topk(a, k=3, sorted=True)
torch.return_types.topk(
values=tensor([9, 8, 7]),
indices=tensor([5, 7, 2]))
```

## Expected behavior

I expected that `sorted=False` controls whether to return the elements in sorted order as stated in the docs.

## Environment

Tested on Pytorch 1.8.0 and 1.9.0 on MacOS via pip.

**Comment by DamonDeng** [comment]
I guess your expectation is returning topk elements in original order.

If that is what you want, setting "sorted" parameter to False doesn't help. As the doc does not guarantee it. The following is quoted from the doc:
"The boolean option sorted if True, will make sure that the returned k elements are themselves sorted"

That means setting "sorted" to True will make sure the return values are sorted, while setting "sorted" to False..... you don't know what will happen to the order of the return values.

If you look into the implementation of Tensor.topk(),  in "topk_impl_loop()" of "SortingUtils.h", you can find that the underlying code call `std::partial_sort` or `std::nth_element` to find the topk elements, neither of them can make sure that the topk values are in original order.

And I think it is wise to avoid any additional sorting task in underlying implementation.

To achieve your target (if what I guessed is right), maybe additional sorting of the return indices can help, like the following code segment:

  values, indices = torch.topk(a, k=3, sorted=False)
  
  _, value_positions = torch.sort(indices)
  
  values_in_original_order = values.index_select(0, value_positions)

**Comment by Felix-Petersen** [comment]
In my cases, there was no difference between `sorted=True` and `sorted=False`. Is there an example where the output differs? 

Otherwise, I suggest deprecating the argument as it does not make sense to have an argument that does not have any effect although implying that it would do something. While it is not explicitly stated, `sorted=False` implicitly implies that it preserves the order, which can easily case confusion.

**Comment by DamonDeng** [comment]
If you want to see the difference between `sorted=True` and `sorted=False`, make the size of input tensor larger and make the k large enough (k*64 > n).

Please refer to the following sample:

    import torch
    torch.manual_seed(0)
    k_number = 20
    
    a = torch.randperm((k_number - 1 ) * 64)
    
    print (a)
    print (torch.topk(a, k=k_number, sorted=False))
    print (torch.topk(a, k=k_number, sorted=True))

I do not agree with the suggestion about "deprecating the argument", as the `sorted=True` does do something to sort the output values. If you set the argument `sorted=False`, the underlying code will save the time to sort output values. Although setting `sorted=False` does not keep the original order as you expect, it does help high level programers to save some time.

To avoid confusion, I think that we should state in the doc explicitly that the order of return elements is "undefined" if `sorted` is set to `False`.

**Comment by Felix-Petersen** [comment]
Thanks.

I agree. My suggestion for "otherwise" was just for the case that there actually is not a difference. But as you pointed out, there is a difference, and it makes sense.

**Comment by anjali411** [comment]
closing this issue as the issue seems resolved

**Comment by DamonDeng** [comment]
@anjali411 , is there any place we can add a //todo suggestion to update the doc to make it more clear?
