### ISSUE TITLE
User-defined preferred BLAS backend of choice not respected

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#60328]
## 🐛 Bug

When I build PyTorch and specify `BLAS=OpenBLAS`, CMake picks up my BLAS installation:
```
-- Trying to find preferred BLAS backend of choice: OpenBLAS
-- Found OpenBLAS libraries: /home/t-astewart/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openblas-0.3.15-oqbdvprnws5d63wrdu54x2gv6l3rbbpc/lib/libopenblas.so
-- Found OpenBLAS include: /home/t-astewart/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openblas-0.3.15-oqbdvprnws5d63wrdu54x2gv6l3rbbpc/include
```
but later during CMake configuration it switches to MKL:
```
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
...
--   USE_BLAS              : 1
--     BLAS                : mkl
--   USE_LAPACK            : 1
--     LAPACK              : mkl
```

## To Reproduce

1. Set `BLAS=OpenBLAS`
1. `python setup.py install`

## Expected behavior

I would expect CMake to fail if it can't find my OpenBLAS installation, and I definitely wouldn't expect it to switch after it does find OpenBLAS.

## Environment

 - PyTorch Version: 1.9.0
 - OS: Linux (Ubuntu 18.04)
 - How you installed PyTorch: `spack`
 - Build command you used: `python setup.py install`
 - Python version: 3.8.10
 - CUDA/cuDNN version: 10.1.243/8.0.5.39
 - GPU models and configuration: K80 (sm_37)

## Additional context

* [build log](https://github.com/pytorch/pytorch/files/6680984/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/6680986/spack-build-env.txt)

cc @malfet @seemethere @walterddr

**Comment by cdeepali** [comment]
I'd suggest to retry with `USE_MKLDNN=0` along with `BLAS=OpenBLAS`.

**Comment by cdeepali** [comment]
I think I replied too early on this. 

On checking further it looks like that we need to set `WITH_BLAS` option as it is used in https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindBLAS.cmake#L98

Please use code from PR - https://github.com/pytorch/pytorch/pull/59220 to supply `WITH_BLAS` from environment.

**Comment by adamjstewart** [comment]
Yes, #59220 fixes my issue, thanks for the help!
