### ISSUE TITLE
how could I get pytorch0.4 for maskrcnn. i want to deal 0dim

### ISSUE THREAD

**Issue by huanglin6385** [pytorch/pytorch#6034]
pytorch 0.3 can't deal 0 dim 
i can't find 0.4
can u help me?

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by zou3519** [comment]
You can build from source: https://github.com/pytorch/pytorch#from-source

**Comment by huanglin6385** [comment]
@zou3519 
sorry 
i can't find 0.4
it's not open?

**Comment by SsnL** [comment]
Are you saying that you can't open the link? You can just look at this repo's README.

**Comment by huanglin6385** [comment]
@SsnL 
master's version is 0.4？

**Comment by fmassa** [comment]
@huanglin6385 yes, but you need to compile from source
