### ISSUE TITLE
Some Logic Error with New Group?

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#60356]
PyTorch provides the following function to build a new backend among some processes in the world group:
https://github.com/pytorch/pytorch/blob/5ff407df675b3f178080f56abc86442da428370f/torch/distributed/distributed_c10d.py#L2701
In the returned sub_pg, the rank will be re-arranged, which means if you build a new process group among p1, p4, p6, now, the returned one will have p0 (p1 in the world), p1 (p4 in the world), p2 (p6 in the world). 
This is reasonable, for that once we build a new process group, we can only pay attention to the rank in the group itself, and do not worry about the original rank. 
However, there is something puzzling here:
https://github.com/pytorch/pytorch/blob/5ff407df675b3f178080f56abc86442da428370f/torch/distributed/distributed_c10d.py#L2126

The function call get_rank will always return the rank in the world process,
https://github.com/pytorch/pytorch/blob/5ff407df675b3f178080f56abc86442da428370f/torch/distributed/distributed_c10d.py#L2156

So, my_rank here is the rank in the world process group.
In most cases, it is ok. But If we now pass a sub_pg to those functions, it seems bad.

In order to keep up with my_rank in the world process group, here will convert the dst rank to the world one. 

https://github.com/pytorch/pytorch/blob/5ff407df675b3f178080f56abc86442da428370f/torch/distributed/distributed_c10d.py#L2168

And, then the operation will be operated on world rank with the local sub_pg!!!

https://github.com/pytorch/pytorch/blob/5ff407df675b3f178080f56abc86442da428370f/torch/distributed/distributed_c10d.py#L2170

As mentioned before, in sub_pg, there is no notation about world rank, but here pass the world rank instead of local one, why?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
cc @agolynski

**Comment by pritamdamania87** [comment]
> In order to keep up with my_rank in the world process group, here will convert the dst rank to the world one.

`_get_group_rank` actually does the reverse, it converts the world rank to the local one and then the local rank is used in the gather call with the sub_pg.

Given that is the main concern here that we provide a sub_pg to gather but still need to provide the global rank as `dst`?

**Comment by densechen** [comment]
@pritamdamania87 I made a mistake! I  mixed `_get_group_ranl` and `_get_global_rank`.
That is right.
