### ISSUE TITLE
test_old_models_bc is flaky

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#60354]
It can be seen failing erroneously on both [pytorch_linux_xenial_py3_6_gcc5_4_jit_legacy_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/339357/workflows/c9bd7d31-234a-4b6d-aa51-232f32c4c327/jobs/14264299) and [pytorch_linux_xenial_py3_6_gcc5_4_test](https://app.circleci.com/pipelines/github/pytorch/pytorch/339357/workflows/c9bd7d31-234a-4b6d-aa51-232f32c4c327/jobs/14264297). 

OSS CI test signal is one of our top better engineering priorities for H2 2021, so we should fix this test, disable it, or consider moving it to a separate "flaky test" job.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @gmagogsfm

**Comment by nikithamalgifb** [comment]
@mruberry : Do you know how often this has failed in the last month/week? Also, i have observed few tests fail due to infrastructure issues , which seem to go away after re-run? Are these tests failing due to similar issues? I would be happy to help and investigate this further.

**Comment by mruberry** [comment]
> @mruberry : Do you know how often this has failed in the last month/week? Also, i have observed few tests fail due to infrastructure issues , which seem to go away after re-run? Are these tests failing due to similar issues? I would be happy to help and investigate this further.

I'm not sure the source of the flakiness. In the current HUD CI the failure rate is 3.5% on pytorch_linux_xenial_py3_6_gcc5_4_jit_legacy_test. Which is a lot. The failure rate for pytorch_linux_xenial_py3_6_gcc5_4_test seems comparable but I didn't look as thoroughly.
