### ISSUE TITLE
pytorch_linux_backward_compatibility_check_test is flaky

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#60355]
See [this](https://app.circleci.com/pipelines/github/pytorch/pytorch/339357/workflows/c9bd7d31-234a-4b6d-aa51-232f32c4c327/jobs/14264294) recent failure that was reported in HUD CI on https://github.com/pytorch/pytorch/pull/59148.

We may want to consider radically changing how do we BC (and FC) testing, too, because currently many BC/FC requirements are simply not tested for.

cc @ezyang @gchanan @zou3519 @kadeng @ZainRizvi @bdhirsh @jbschlosser @anjali411 @mruberry @VitalyFedyunin @walterddr

**Comment by anjali411** [comment]
> because currently many BC/FC requirements are simply not tested for.

for example?

**Comment by mruberry** [comment]
> > because currently many BC/FC requirements are simply not tested for.
> 
> for example?

S236314 (FB-only link, sorry) happened because a new function was called from an existing module.

**Comment by ZainRizvi** [comment]
Closing since this is 2 yrs old and we've made many BC compat improvements since then. Please reopen if it's still an issue
