### ISSUE TITLE
INTERNAL_ASSERT failed

### ISSUE THREAD

**Issue by VRehnberg** [pytorch/pytorch#60365]
## 🐛 Bug

RuntimeError: batched == nullptrINTERNAL ASSERT FAILED at "/tmp/pip-req-build-ym9h0m9k/functorch/csrc/DynamicLayer.cpp":250, please report a bug to PyTorch. 

## To Reproduce

1.Run the following:
```python
import torch
from functorch import vmap

b, n, m = 3, 7, 2
x = torch.rand(b, n)
partition = torch.rand(n, m) > 0.5
vmap(lambda mask: x[:, mask].sum(-1))(partition)
```

## Environment

Collecting environment information...
PyTorch version: 1.10.0.dev20210621+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] functorch==0.0.1a0+9d091e6
[pip3] numpy==1.20.3
[pip3] torch==1.10.0.dev20210621+cpu
[conda] functorch                 0.0.1a0+9d091e6          pypi_0    pypi
[conda] numpy                     1.20.3           py39hdbf815f_1    conda-forge
[conda] torch                     1.10.0.dev20210621+cpu          pypi_0    pypi

## Additional context

It might be a problem caused by facebookresearch/functorch but it said to report to PyTorch so we did.

**Comment by anjali411** [comment]
@VRehnberg can you add a min reproducible code sample in the issue? I am not able to load the Jupyter notebook (that you linked) on github.

**Comment by VRehnberg** [comment]
Oops, I hadn't pushed the .py file. But I'll write a MWE as well.

**Comment by VRehnberg** [comment]
@anjali411 added a minimum reproducible code sample and edited it in to the issue.

**Comment by gchanan** [comment]
are you using functorch?

CC @zou3519.

**Comment by zou3519** [comment]
This issue should go on the functorch issue tracker. Let me see if I can transfer it. It ended up here because TORCH_INTERNAL_ASSERT asks the user to file an issue to PyTorch

**Comment by zou3519** [comment]
I'm unable to transfer the issue, but I opened a new one over at https://github.com/facebookresearch/functorch/issues/59.

@VRehnberg we'd be happy to help you -- let's migrate the discussion to https://github.com/facebookresearch/functorch/issues/59
