### ISSUE TITLE
torch.sum() returns different result on different device

### ISSUE THREAD

**Issue by litianqi715** [pytorch/pytorch#60367]
## To Reproduce

import torch
bb=torch.rand([6,4,224,224])
print(bb.sum(), bb.cuda(1).sum(), bb.numpy().sum())

## Expected behavior

I expect the sum result of float32 tensor is the same on cpu and gpu, at least in the first 6 digits. But I found that the sum result  on gpu is often different with that of  cpu or numpy. Even on different generation of graphics card, such as 3060 and 2070super, the sum result of the same tensor is often different.

## Environment

Collecting environment information...
PyTorch version: 1.7.0+cu110
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.2 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.17

Python version: 3.6 (64-bit runtime)
Python platform: Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2070 SUPER
GPU 1: NVIDIA GeForce RTX 2070 SUPER

Nvidia driver version: 465.31
cuDNN version: Could not collect, but give 8004 in torch.backends.cudnn.version()
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.0+cu110
[pip3] torchvision==0.8.0
[conda] Could not collect

## Additional context

I also found that sometimes, convolution result of the same tensor is different on 3060 and 2070super. At the end of the analysis pipeline, the accumulation of this little different can be big, and damage the analysis result on the macro scale.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @heitorschueroff

**Comment by litianqi715** [comment]
> Tried this, but I got the same results. The sums were equal. I'm not sure why you are facing this but try running it again on a clean slate.

sorry I forgot to upload the image. This seems to be random, sometimes the result is equal but other times there can be a significant diff. I have repeated this behaviour several times.

the nvidia driver, cuda, torch have been re-installed several times on different machines, too.

![demo](https://user-images.githubusercontent.com/5851529/122854259-05002880-d346-11eb-9257-1fd4980ee2b3.jpg)

**Comment by emcastillo** [comment]
This looks like precision errors due to using `float32`, I can reproduce it with `torch.float32` but with `float64` seems stable enough.

**Comment by litianqi715** [comment]
> This looks like precision errors due to using `float32`, I can reproduce it with `torch.float32` but with `float64` seems stable enough.

float64 indeed can eliminate the diff. The problem is, when using float32, after the sequenced pipeline, for example, 4 model modules, the accumulated errors can be big. I have located medical image vessel segments diff in my code. 

I wonder why the 2nd decimal places is different in float32. I recall float32 can process 7th decimal precision.

**Comment by ngimel** [comment]
This is expected due to accumulated error of fp operations. There are 6 significant digits matching, hard to expect better for a large reductions. Bitwise reproducibility between different devices is not guaranteed and is impossible to achieve in practice without completely sacrificing performance.

**Comment by litianqi715** [comment]
Thanks
