### ISSUE TITLE
[feature request] DataLoaders for Video Datasets

### ISSUE THREAD

**Issue by Naman-ntc** [pytorch/pytorch#6036]
In my opinion adding a dataloader for video data-sets would be a nice idea. Looking at deep learning success currently, in future more and more emphasis would be on video data-sets/ understanding videos.
The other day I needed to load NTU RGB Video Dataset and I needed to write opencv scripts for loading the avi files and would haver loved some inbuilt dataloader.
What are your views on it?

**Comment by soumith** [comment]
NVIDIA just released NVVL, a high-performance data loading for videos with PyTorch integration (see pytorch/ folder which provides DataLoader interface): https://github.com/NVIDIA/nvvl

**Comment by wvinzh** [comment]
But the NVVL doesn't support multi resolution videos, that means the input videos must be in the same size.
