### ISSUE TITLE
ROCM CI test timeout failures

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#60377]
The ROCM tests`linux-bionic-rocm4.2-py3.6-test1` and `linux-bionic-rocm4.2-py3.6-test2` are currently failing on master pretty frequently due to passing the 210 minute timeout.

#60170, #601769 and #60168 seem like likely culprits since the failures started happening more frequently after they landed, but it looks like the tests were pretty close to the timeout limit before that too - example timeout on master from before those PR's landed: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test1/3259//console

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jeffdaily** [comment]
Merged https://github.com/pytorch/ossci-job-dsl/pull/105.  

But jenkins seed job failed due to https://github.com/pytorch/ossci-job-dsl/pull/104 and we didn't catch it until now.  

Fixed with https://github.com/pytorch/ossci-job-dsl/pull/107.

**Comment by jeffdaily** [comment]
Please review https://github.com/pytorch/pytorch/pull/60409 urgently, to restore ROCm CI.
