### ISSUE TITLE
[ONNX]A couple of exporter limitations when exporting a longformer model

### ISSUE THREAD

**Issue by wangyems** [pytorch/pytorch#60391]
## 🐛 Bug

All of the following issues have work arounds, but listed for potential improvements.

1
Pytorch code:
sentence_tensors = torch.split(sample_tensor, sentence_length_list)[:-1]
translates to
onnx::SplitToSequence -> onnx::Slice

Currently Slice only supports Tensor type in ORT. This gap could be filled by supporting seq(tensor) in Slice. But wondering if it’s better to translate it to a new Op like SequenceSlice since it only uses subset of Slice parameters?

2
There is a piece of code that reassigns the value in an array in python
    if final_shape[dim] < len:
        final_shape[dim] = len - final_shape[dim]
This reassigning does not reflect in onnx but keep the original value. It causes core dump in runtime sometimes and hard to debug

3
attn_output[is_index_global_attn_nonzero[::-1]] = nonzero_global_attn_output.view(
                len(is_local_index_global_attn_nonzero[0]), -1
            )
In onnx, the len() is hardcode with the compile time value. Might be better to translate to onnx::Shape 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.20.3
Libc version: glibc-2.23

Python version: 3.8 (64-bit runtime)
Python platform: Linux-4.15.0-1103-azure-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1
[pip3] torchvision==0.6.0+cu101
[conda] numpy                     1.20.1                   pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi

## Additional context

cc @garymm @BowenBao @neginraoof

**Comment by garymm** [comment]
@wangyems Please split this up into separate issues with clear (ideally small) repro instructions for each issue.

I tried reproducing the first case you mentioned and I couldn't.

(Also if you want to save us a step of copying from GitHub, please file the issue in Azure DevOps under Vienna\ONNX Runtime\Shared Core\Converters\PyTorch and tag me)
