### ISSUE TITLE
[FR] Module.register_module alias for add_module

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#60397]
## 🚀 Feature

Can we add an alias for `Module.add_module` as `Module.register_module`? We register buffer/parameters with `Module.register_X`.

cc @albanD @mruberry @jbschlosser

**Comment by VitalyFedyunin** [comment]
Makes sense for me, but require second opinion.

**Comment by ezyang** [comment]
sure

**Comment by ngimel** [comment]
We'll accept a PR implementing this feature
