### ISSUE TITLE
Slicing tensors with negative steps

### ISSUE THREAD

**Issue by MaximumEntropy** [pytorch/pytorch#604]
It'd be nice to be able to slice tensors using a negative step such as tensor[::-1] or tenso[:, ::-1, :] like what is possible with numpy or theano. It'll make implementing things like bidirectional RNNs (without using the inbuilt RNN modules) simpler.

**Comment by fmassa** [comment]
Allowing negative strides is already being tracked in https://github.com/pytorch/pytorch/issues/229

**Comment by apaszke** [comment]
I agree, but our C backends will require a few, possibly nontrivial, changes. I'm closing this since it's a duplicate.

**Comment by MaximumEntropy** [comment]
Oops I didn't look carefully enough apparently. Apologies.

**Comment by el3ment** [comment]
@apaszke I think this issue should be reopened. `torch.flip` isn't quite the same thing as negative striding or negative stepping -- torch.flip produces an (efficient) copy, but negative striding wouldn't need to perform a copy at all.

**Comment by soumith** [comment]
@el3ment while what you say is absolutely correct, I dont think we are planning to support negative striding anytime in the near / far future (if ever). It requires rethinking our internals and is a huge undertaking, for what we see as small perceived benefit. cc: @ezyang to double-check that our new C10 Tensor design is not incorporating negative strides.

**Comment by ezyang** [comment]
We were originally thinking that when we looked into changing TH's size/stride semantics, it might be "easy" to also make things work with negative strides, but we ended up using all our engineering budget just on making zero-size dims and scalars work correctly.
