### ISSUE TITLE
Pytorch corrupting Numpy after importing

### ISSUE THREAD

**Issue by denkorzh** [pytorch/pytorch#6040]
- OS: Ubuntu 16.04 4.10.0-35-generic #39~16.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.3
- Numpy version 1.13.3

I've noticed that importing torch corrupts numpy behaviour.
Running the following script without importing torch I two zeros printed.

```python
import numpy as np
# import torch

np.random.seed(0)
size = 1000
a = np.random.rand(size, size)
b = np.random.rand(size, size)

print(np.abs(a@b - a@b).max())
print(np.abs(a@b - np.dot(a, b)).max())
```
But when the second line is uncommented I get approximately `214.31` and `424.66` from the two `print` calls respectively.

**Comment by albanD** [comment]
Can't reproduce, I get 0 with:

OS: Ubuntu 14.04
PyTorch version: master
Python version: 2.7
Numpy version 1.14.2

**Comment by arogozhnikov** [comment]
Get two zeros too. 
Ubuntu 16.04
PyTorch: master
Python 3.6
Numpy: 1.13.3

@denkorzh  Could you please show your blas linkage in numpy:
```python
>>>import numpy as np
>>>np.__config__.show()
```

It also worth checking that it is not changed after importing torch.

**Comment by gchanan** [comment]
this looks old enough that I'm going to close -- we've fixed a number of these issues too.

**Comment by PierreId** [comment]
I have the exact same problem, though I cannot repoduce it with the code from @denkorzh

Here is some code that gives bad/corrupted values:
```
import torch
import numpy as np

np.__config__.show()

values = np.random.rand(5000,500)
normalized_values = values / np.linalg.norm(values, 2, axis=1, keepdims=True)
result = np.dot(normalized_values,np.transpose(normalized_values))
np.testing.assert_almost_equal(np.diag(result), 1.)
```
Output:
```
Mismatch: 100%
Max absolute difference: 4.77704257
Max relative difference: 4.77704257
 x: array([5.2056614, 5.2530907, 4.9709276, ..., 5.4021891, 5.2522141,
       5.29231  ])
 y: array(1.)
```
If I comment the "import torch" line or put it after "import numpy", the diagonal is back to its right value : 1.

I could reproduce it with Pytorch 1.5.1/1.6.0 on Ubuntu 16.04.4/18.04.4, with same Python installed on it and this Numpy (1.17.4) config : 
```
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/python-3.7.5/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/python-3.7.5/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/python-3.7.5/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/python-3.7.5/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/python-3.7.5/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/python-3.7.5/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/python-3.7.5/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include', '/opt/python-3.7.5/include']
```
I could NOT reproduce it : 
- with Pytorch 1.4.0
- if I reinstall the exact same Numpy (1.17.4) in a virtualenv and MKL is not available anymore
