### ISSUE TITLE
[FX] getattr default not respected after symbolic_trace

### ISSUE THREAD

**Issue by jfix71** [pytorch/pytorch#60417]
## 🐛 Bug

Is during symbolic tracing a builtin.getattr is traced and it uses a default value, that default value is lost.

## To Reproduce

```
import torch
import torch.nn as nn
from torch.fx import symbolic_trace

class TestModule(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a: torch.Tensor) -> torch.Size:
        return getattr(a, "nonexistent_attr", torch.Size([1,2]))

m = TestModule()
traced = symbolic_trace(m)

# WRONG: AttributeError: 'Tensor' object has no attribute 'nonexistent_attr'
# traced(torch.rand(3, 4))

print(traced.graph)
"""
graph():
    %a : torch.Tensor [#users=1] = placeholder[target=a]
    %getattr_1 : [#users=1] = call_function[target=builtins.getattr](args = (%a, nonexistent_attr), kwargs = {})
    return getattr_1
"""
```

## Expected behavior

If you inspect `traced.graph` you'll notice that no default value for getattr is provided, although it should be `torch.Size([1, 2])`. When you run the traced module you will encounter an exception about `a` not having `nonexistent_attr`, which should not be thrown because the default value to return instead be returned/should prevent the exception.

**Comment by jamesr66a** [comment]
Hm I'm not actually sure if it's possible to intercept the default behavior here. `getattr` is implemented as this C builtin function: https://github.com/python/cpython/blob/9af34c935185eca497617a216d141c72ffaeae9c/Python/bltinmodule.c#L1108 and the path that handles default values is entirely contained within that implementation; the default value is not visible in the dispatch implementation here https://github.com/python/cpython/blob/0fd27375cabd12e68a2f12cfeca11a2d5043429e/Objects/object.c#L944 which eventually delegates down into the object's `__getattr__` method

Potentially we could fix this externally by patching `builtins.getattr` during trace timeand installing the logic that way.
