### ISSUE TITLE
A100 is slower than 1080ti. +) How can I change the cudnn version in pytorch?

### ISSUE THREAD

**Issue by seorim0** [pytorch/pytorch#60434]
First I found out that the A100 supports:   
- cuda 11.0   
- nvidia driver 450   

So, when using the A100, I adjusted the environment as follows.   
- cuda 11.0   
- cudnn 8005
- nvidia driver 450 (more detailed, 450.119.04)    
- pytorch 1.8.0   

using,   
`pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
`

However, the time for training my model takes too long.    
For example, the model used in the experiment is a complex model with a size of 7.2M.  
When using the 1080ti, it took 1600 seconds for 1 epoch (18,480 data), but it takes 2000 seconds with the A100.

I doubt if this is a cudnn version problem, and I want to change cudnn to 8.0.2 or 8.0.3.

How can I change only the cudnn version in pytorch?   
Or is there any other solution to this problem?

cc @csarofeen @ptrblck @xwang233 @VitalyFedyunin @ngimel @heitorschueroff

**Comment by eqy** [comment]
It can be a bit tricky to reconcile the actual cuDNN version being used by PyTorch pip install with a user-installed version on the system. Does `torch.backends.cudnn.version()` also say 8005?

Have you also tried using `torch.backends.cudnn.benchmark = True`? It may be that the workload here is improperly handled by the current heuristics.

**Comment by mrshenli** [comment]
Hey @seorim0, just FYI, we usually use [the forum](https://discuss.pytorch.org/) for questions and github issues for bug reports and feature requests.

**Comment by seorim0** [comment]
> It can be a bit tricky to reconcile the actual cuDNN version being used by PyTorch pip install with a user-installed version on the system. Does `torch.backends.cudnn.version()` also say 8005?
> 
> Have you also tried using `torch.backends.cudnn.benchmark = True`? It may be that the workload here is improperly handled by the current heuristics.

Yeah, I checked the cuDNN version through `torch.backends.cudnn.version()`.   
And I've  tried `torch.backends.cudnn.benchmark = True` before, but the speed was more slower.

**Comment by seorim0** [comment]
> Hey @seorim0, just FYI, we usually use [the forum](https://discuss.pytorch.org/) for questions and github issues for bug reports and feature requests.

Oh, I see. Thank you!

**Comment by xwang233** [comment]
This is likely the dynamic linking issue on Ampere GPUs in 1.8.1. You can try the 1.9 release which fixed this problem.

**Comment by xiaohu2015** [comment]
@seorim0 Hi, have you get out of this thouble? I also have this problem.

**Comment by seorim0** [comment]
> @seorim0 Hi, have you get out of this thouble? I also have this problem.

Sorry for the late reply.
Yes, I solved it. I changed the version of CUDA 11.0 to 11.1 and the version of pytorch from 1.8.0 to 1.9.0. Then I can get a reasonable training time with A100.
