### ISSUE TITLE
it seems n_heads is not handled correctly in nn.MultiheadAttention

### ISSUE THREAD

**Issue by bosskwei** [pytorch/pytorch#60445]
+ PyTorch impl: [L921](https://github.com/pytorch/pytorch/blob/release/1.9/torch/nn/modules/activation.py#L921)
```
self.head_dim = embed_dim // num_heads
...
self.q_proj_weight = Parameter(torch.empty((embed_dim, embed_dim), **factory_kwargs))
```

+ According to original paper:
  + Instead of performing a single attention function with d model -dimensional keys, values and queries, we found it beneficial to **linearly project the queries, keys and values h times with different, learned linear projections** to d_k, d_k and d_v dimensions, respectively.
  + On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding d_v-dimensional output values. These are concatenated and once again projected, resulting in the final values, as depicted in Figure 2
+ Expect impl:
```
self.linear_q = nn.Linear(embed_dim,  embed_dim * n_head)
```

cc @albanD @mruberry @jbschlosser @bhosmer @cpuhrsch

**Comment by bosskwei** [comment]
## Update: correct and simplest MTA may look like this
```Python
class MultiheadAttention(nn.Module):
    def __init__(self, d_model, n_heads, d_k, d_v):
        nn.Module.__init__(self)
        #
        self.d_model = d_model
        self.n_heads = n_heads
        self.d_k = d_k
        self.d_v = d_v
        #
        self.linear_q = nn.Linear(d_model, n_heads * d_k)
        self.linear_k = nn.Linear(d_model, n_heads * d_k)
        self.linear_v = nn.Linear(d_model, n_heads * d_v)
        self.attn_fn = DotProductAttention(float(d_k) ** -0.5)
        self.linear_fc = nn.Linear(n_heads * d_v, d_model)
```

**Comment by aadeg** [comment]
I've the same issue. I'm converting a Keras model in Pytorch and I found your exact same problem. The MultiHeadAttention in Keras is implemented as you described.

**Comment by jbschlosser** [comment]
As a simple workaround, couldn't you pass `embed_dim * num_heads` as the `embed_dim`? When it is divided amongst the heads, it should result in what you want.

**Comment by aadeg** [comment]
@bosskwei 
>     * PyTorch impl: [L921](https://github.com/pytorch/pytorch/blob/release/1.9/torch/nn/modules/activation.py#L921)
> 

I think this line came up from the following highlighted paragraph of the original paper (Attention Is All You Need, p. 5):

![photo_2021-06-23_16-37-28](https://user-images.githubusercontent.com/6524326/123116588-5214f500-d441-11eb-9ee3-c74cb35d90fa.jpg)

The `d_model / h` quantity should be the `head_dim` defined at line [L921](https://github.com/pytorch/pytorch/blob/release/1.9/torch/nn/modules/activation.py#L921).

In the paragraph the authors of the paper define **their** hyper-parameters, but choosing `head_dim = d_model / h` it's simply one choice. \
As stated in this [StackOverflow question](https://stackoverflow.com/questions/66389707/why-embed-dimemsion-must-be-divisible-by-num-of-heads-in-multiheadattention), there's no reason in forcing the `embed_dim` to be divisible by the `num_heads` (for all the math have a look to the SO question).

**Comment by bosskwei** [comment]
@aadeg you are right, seems torch followed the rule that d_model divided by num_heads, but most time when d_model == num_embedding, it looks like single attention head only learned a subfeature from embedding, and increase num_heads may not improve the attention performance
