### ISSUE TITLE
Nightly builds: CMake error "Imported target "torch" includes non-existent path"

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#60485]
## 🐛 Bug

I have started seeing the following CMake error with the nightly builds. The last working version is `torch==1.10.0.dev20210617+cpu`. I have tested up through `torch==1.10.0.dev20210622+cpu`. My downstream project is [mlir-npcomp](https://github.com/llvm/mlir-npcomp)

This is the error log from CMake.
```
CMake Error in frontends/pytorch/csrc/CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "/pytorch/torch/lib"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

## To Reproduce

1. Install PyTorch with `python3 -m pip install --upgrade --pre 'torch==1.10.0.dev20210622+cpu' 'torchvision==0.11.0.dev20210622+cpu' -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`
1. Follow "Common prep" and "PyTorch Frontend" setup instructions here: https://github.com/llvm/mlir-npcomp

I debugged this a little, but ran into a dead end. I printed out the value of `INTERFACE_INCLUDE_DIRECTORIES` on the target `torch` as follows:
```
get_target_property(VAR torch INTERFACE_INCLUDE_DIRECTORIES)
message(WARNING "INTERFACE_INCLUDE_DIRECTORIES: ${VAR}")
```

And I got the following result:
```
/usr/local/google/home/silvasean/.local/lib/python3.9/site-packages/torch/include;/usr/local/google/home/silvasean/.local/lib/python3.9/site-packages/torch/include/torch/csrc/api/include
```
Which looks to be as intended from [here in the TorchConfig.cmake.in](https://github.com/pytorch/pytorch/blob/0c916c8a4e94c50ae65c2acdfed348cb94bd26de/cmake/TorchConfig.cmake.in#L56) and it is later assigned to [`INTERFACE_INCLUDE_DIRECTORIES` here](https://github.com/pytorch/pytorch/blob/0c916c8a4e94c50ae65c2acdfed348cb94bd26de/cmake/TorchConfig.cmake.in#L183).

I cannot find where the `/pytorch/torch/lib` is coming from (it looks like there is an unexpanded variable at the front there, but that's not immediately useful)

## Expected behavior

No error, configure completes successfully.

## Environment

```
Collecting environment information...
PyTorch version: 1.10.0.dev20210622+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 10.2.1-6+build2) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.10.28-1rodete2-amd64-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro P5000
Nvidia driver version: 460.56
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0.dev20210622+cpu
[pip3] torchvision==0.11.0.dev20210622+cpu
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] numpydoc                  1.1.0                      py_0  
[conda] pytorch                   1.6.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.7.0                py38_cu101    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Is likely to be fixed by https://github.com/pytorch/pytorch/pull/60493

**Comment by silvasean** [comment]
Thanks, this seems resolved now.

**Comment by silvasean** [comment]
I'm hitting a very similar issue which started happening in the last day.

```
CMake Error in frontends/pytorch/csrc/CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "/usr/local/include/breakpad"

  in its INTERFACE_INCLUDE_DIRECTORIES. 
```

**Comment by silvasean** [comment]
This is for PyTorch installed as
```
python3 -m pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

**Comment by silvasean** [comment]
Ok, will do!
