### ISSUE TITLE
searchsorted produces incorrect output if out is given explicitly and not contiguous

### ISSUE THREAD

**Issue by ozars** [pytorch/pytorch#60492]
## 🐛 Bug

`torch.searchsorted` has an `out` parameter but it assumes it is contiguous. Otherwise an incorrect result is produced without any warnings.

## To Reproduce

```python
import torch
device = torch.device("cpu")
# device = torch.device("cuda")

x = torch.arange(10, device=device)
ind = torch.arange(3, 8, device=device)
tmp = torch.zeros(5, 2, device=device, dtype=ind.dtype)
out = tmp[:, 0]

torch.searchsorted(x, ind, out=out)
print(out)
print(tmp)
```

CPU output:
```
tensor([3, 5, 7, 0, 0])
tensor([[3, 4],
        [5, 6],
        [7, 0],
        [0, 0],
        [0, 0]])
```

CUDA output:
```
tensor([3, 5, 7, 0, 0], device='cuda:0')
tensor([[3, 4],
        [5, 6],
        [7, 0],
        [0, 0],
        [0, 0]], device='cuda:0')
```

## Expected behavior

It can print a warning, raise an exception, convert `out` to a contiguous tensor or consider its strides. Not really sure. This behavior can be noted in docs.

## Environment

python 3.8.8
pytorch 1.8.1
cudatoolkit 11.1.1
via conda

cc @heitorschueroff

**Comment by mrshenli** [comment]
adding "triage review" to discuss whether this needs a fix

**Comment by emcastillo** [comment]
Sorry, I took the liberty of submit a PR for this 😅 #60508
