### ISSUE TITLE
[torchscript] @ op not supported

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#6049]
Repro. Fails with not-so-readable error message
```
import torch
@torch.jit.script
def mm(x, y):
    return x @ y

x = torch.randn(4, 3)
y = torch.randn(3, 2)
mm(x, y)
```
[Traceback](https://gist.github.com/zou3519/052b8998108c4bc0fe0e7c85c6f5758e)

We should either support it or ask people to use `torch.mm`

cc @zdevito

I'll try to take a stab at this sometime if this is the correct diagnosis

**Comment by apaszke** [comment]
Uh, I think the last function should have been `make_raw_range` instead of `make_range`
