### ISSUE TITLE
Unnecessary operators in torch.tensor.repeat ONNX conversion

### ISSUE THREAD

**Issue by skottmckay** [pytorch/pytorch#60496]
## 🐛 Bug

The ONNX conversion of torch.tensor.repeat creates a shape containing just 1's and calls Expand with that. As Expand broadcasts it's valid to provide 1's in the shape, but as all the values are 1's it won't actually change anything will it? Unless I'm missing something it's the following Tile calls that really does the repeat, but that could be used directly.

https://github.com/pytorch/pytorch/blob/fca931d18131d313adbf6d53ccc0a9401e7851e8/torch/onnx/symbolic_opset9.py#L2043-L2044

## To Reproduce

Convert model with torch.tensor.repeat

## Expected behavior

Not include unnecessary operators in conversion.

## Environment

Looking at model converted to ONNX from pytorch by external party.

cc @garymm @BowenBao @neginraoof

**Comment by garymm** [comment]
Tracked internally by [AB#1243156](https://msdata.visualstudio.com/Vienna/_workitems/edit/1243156)

**Comment by neginraoof** [comment]
So torch repeat op first broadcasts the input to the match the rank of the requested shape, and then repeats the tensor.
So if the input has shape (3, ) and repeat size is (4, 6),
Now to apply the broadcasting, the symbolic creates:
shape_ = (1, 1)
output of the Expand has shape: (1, 3)

Note the onnx::Expand spec: Dimensions are right alignment; Two corresponding dimension must have the same value, or one of them is equal to 1.
