### ISSUE TITLE
Spurious failure reported by a GHA workflow

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60506]
## 🐛 Bug

In #56992, I added a GHA workflow for `pytorch-linux-bionic-py3.8-gcc9-coverage` using `.github/scripts/generate_ci_workflows.py`.
[` (pytorch-linux-bionic-py3.8-gcc9-coverage) / render_test_results`](https://github.com/pytorch/pytorch/runs/2890133876) reports a failure that didn't occur in either of the two tests that ran in the workflow -

```
2021-06-22T23:49:38.6203878Z 🚨 ERROR: TestNN.test_softmax_cpu
2021-06-22T23:49:38.6716537Z 
2021-06-22T23:49:38.6719393Z Traceback (most recent call last):
2021-06-22T23:49:38.6721857Z   File "test_nn.py", line 10509, in test_softmax_cpu
2021-06-22T23:49:38.6723613Z     out = F.softmax(input, dim=-1)
2021-06-22T23:49:38.6725514Z   File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1679, in softmax
2021-06-22T23:49:38.6726917Z     ret = input.softmax(dim)
2021-06-22T23:49:38.6728554Z RuntimeError: "softmax_lastdim_kernel_impl" not implemented for 'BFloat16
```

This test actually passes in the workflow, and this error can't occur as the PR enables `softmax_lastdim_kernel_impl` for `BFloat16`.
This failure didn't occur on CircleCI (it didn't occur in GHA either, but has been reported in the CI check ` (pytorch-linux-bionic-py3.8-gcc9-coverage) / render_test_results`).

## Expected behavior

Spurious failures should not be reported by GHA.

## Environment

[CI](https://github.com/pytorch/pytorch/runs/2890133876)

## Additional context

Maybe I was supposed to use `num_shards=1`, but that wouldn't have caused this failure.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @albanD @mruberry @jbschlosser @VitalyFedyunin @zhaojuanmao @janeyx99

**Comment by imaginary-person** [comment]
Hello @mrshenli, this failure isn't related to `nn tests` per se - it didn't actually occur in the two tests for `pytorch-linux-bionic-py3.8-gcc9-coverage`, but has been reported in another CI check `pytorch-linux-bionic-py3.8-gcc9-coverage) / render_test_results`.

Basically, currently, `pytorch-linux-bionic-py3.8-gcc9-coverage` build & tests are run on CircleCI runners on the master branch, as it hasn't been migrated to GHA yet. However, in this PR, I added a GHA workflow for it, which is reporting a spurious failure (the test reported as having been failed actually passes in the logs).

Thank you!

**Comment by mruberry** [comment]
cc @seemethere @samestep

Also: maybe a label for github actions would be useful?

**Comment by samestep** [comment]
> Also: maybe a label for github actions would be useful?

@mruberry Do you mean the `module: ci` label? I could remove the `module: nn` and `module: tests` labels and add that one if that makes sense here.

**Comment by seemethere** [comment]
This might actually be a false positive, we had noticed reports of artifacts carrying over from one build to another since our runners are atm not yet ephemeral (waiting on https://github.com/actions/runner/pull/660)

Perhaps a better cleanup step is in order so that we for sure have removed all of the previous build artifacts

**Comment by imaginary-person** [comment]
Thanks for the clarification!
