### ISSUE TITLE
ImportError: cannot import name 'zero_gradients' from 'torch.autograd.gradcheck' 

### ISSUE THREAD

**Issue by Topology1225** [pytorch/pytorch#60523]
## ❓ Questions and Help

I updated my `pytorch` by 
```bash
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

but I got the next error message, 
```bash
ImportError: cannot import name 'zero_gradients' from 'torch.autograd.gradcheck' 
```

Where is the `zero_gradients` method ?
 
## See also
https://pytorch.org/get-started/locally/

**Comment by VitalyFedyunin** [comment]
Hello! It is better to ask such kind of questions at https://discuss.pytorch.org/ I will close this issue, feel free to reopen it if you think that you need to report a bug or make feature proposal. Thanks.
