### ISSUE TITLE
`torch.isclose` should work with bool tensors

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#60533]
## 🚀 Feature

`torch.isclose` should work with bool tensors. 

## Motivation

```python
>>> t = torch.tensor(True)
>>> torch.isclose(t, t)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

Although it makes little sense to compare bool tensors for closeness, `torch.isclose` is used as the underlying comparison mechanism in `torch.testing.assert_close`. As such it will be hit by all dtypes and should work out of the box.

## Pitch

Instead of comparing the tensors in their native dtypes, we could simply upcast to the most precise dtype of the respective category, including bool in the integral category. This (or something similar) is already done for uint8:

```python
>>> input = torch.tensor(0, dtype=torch.uint8)
>>> other = torch.tensor(1, dtype=torch.uint8)
>>> rtol = 0
>>> atol = 2
>>> torch.isclose(input, other, atol=2, rtol=0)
tensor(True)
>>> abs(input - other) <= atol + rtol * abs(other)  # 255 <= 2
tensor(False)
``` 

## Alternatives

If we decide to not support this use case, we should emit a more expressive error message. Plus, we need to special case bool tensors in `torch.testing.assert_close`

## Additional context

- This was detected while trying to use `torch.testing.assert_close` for the internal test suite in #58981.
- Although the docs are not clear about this (numpy/numpy#19309), `np.isclose` accepts bool arrays and treats them the way pitched above.

cc @izdeby

**Comment by ezyang** [comment]
Yeah, supporting this seems fine, and will degenerate to equality.

**Comment by DamonDeng** [comment]
@ezyang, Anyone working on this?

I looked into the issue and related code, I think we can add some lines of code after the following code,  to check whether the input tensor is bool, and then `return close` if it is.

https://github.com/pytorch/pytorch/blob/864dcbb2cc65352a9ba260c3cf05ee30f4bcc23d/aten/src/ATen/native/TensorCompare.cpp#L98-L103

The simple solution I can think of to check the type of tensor is calling `self.is_bool()`, while I found that `is_bool()` is not implemented yet. There is `is_floating_point()`, and there is `is_complex()`. And one issue was created requesting `is_integer()`

Do you think we need to create a new issue requesting `is_bool()` and then make a PR to address it?

**Comment by pmeier** [comment]
> Anyone working on this?

There is #61271 that seems to close this. cc @Kiyosora

**Comment by Kiyosora** [comment]
@pmeier @DamonDeng I'm sorry that I didn't link my PR here timely. Maybe the solution mentioned in Pitch is more appropriate, since in `numpy.isclose`, the Boolean type tensors would not compared according to the native dtype, So I think upcasting the boolean tensor and bringing in atol and rtol for calculation would make the result more closer to numpy.
```
>>> np.isclose(True, False)
False
>>> np.isclose(True, False, atol=2, rtol=0)
True

>>> input = torch.tensor(True)
>>> other = torch.tensor(False)
>>> torch.isclose(input, other)
tensor(False)
>>> torch.isclose(input, other, atol=2, rtol=0)
tensor(True)
```
