### ISSUE TITLE
`torch.linalg.eigh` is much slower than `torch.linalg.svd` on GPU

### ISSUE THREAD

**Issue by mzhaoshuai** [pytorch/pytorch#60537]
I try to find eigenvectors and eigenvalues of a real symmetric matrix.
1. I can use `torch.linalg.eigh`
2. As it is a real symmetric matrix, singular vectors are the same as eigenvectors.
Howevevr, `torch.linalg.eigh` is much slower than `torch.linalg.svd`.

## Environment
* Ubuntu 18.04, Driver Version: 465.19.01    CUDA Version: 11.3
* Pytorch-1.8.1

## code snippet

```
def svd_test():
	batch = 1000
	a = torch.randint(high=1000, size=(batch, 4, 4)).float().cuda()
	b = torch.randint(high=1000, size=(batch, 4, 4)).float().cuda()
	# warm up
	N = torch.matmul(a, b.transpose(1, 2))	
	XXT = torch.bmm(a, a.transpose(-2, -1))
	
	# symeig
	torch.cuda.synchronize()
	start = time.time()

	for i in range(10):
		S_R, U_R = torch.linalg.eigh(XXT, UPLO='U')
		U = torch.flip(U_R, dims=[-1])

	torch.cuda.synchronize()
	end = time.time()


	print("torch.linalg.eigh", end - start)
	print("max_mem", torch.cuda.max_memory_allocated())


	# svd
	torch.cuda.synchronize()
	start = time.time()

	for i in range(10):
		U1, S, VH = torch.linalg.svd(XXT, full_matrices=False)

	torch.cuda.synchronize()
	end = time.time()

	print("torch.linalg.svd", end - start)
	print("max_mem", torch.cuda.max_memory_allocated())


	# torch.symeig
	torch.cuda.synchronize()
	start = time.time()

	for i in range(10):
		S_R, U_R = torch.linalg.eigh(XXT, UPLO='U')
		U = torch.flip(U_R, dims=[-1])

	torch.cuda.synchronize()
	end = time.time()


	print("torch.linalg.eigh", end - start)
	print("max_mem", torch.cuda.max_memory_allocated())
```

## results
```
torch.linalg.eigh 7.9742112159729
max_mem 480768
torch.linalg.svd 0.4020235538482666
max_mem 761344
torch.linalg.eigh 13.513270854949951
max_mem 761344
```

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @VitalyFedyunin

**Comment by xwang233** [comment]
Thanks for the report. You may try torch 1.9 release and see if you get better performance since `eigh` was updated with faster cusolver path in 1.9 development.

**Comment by mzhaoshuai** [comment]
> Thanks for the report. You may try torch 1.9 release and see if you get better performance since `eigh` was updated with faster cusolver path in 1.9 development.

Thanks for reply.
I tried the same code with PyTorch-1.9.0 official docker image.
```
docker pull pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
```
The results are:

```
1st run

torch.linalg.eigh 0.7880902290344238
max_mem 555520
torch.linalg.svd 0.01916646957397461
max_mem 697344
torch.linalg.eigh 0.6080994606018066
max_mem 763904
```

```
2nd run

torch.linalg.eigh 0.7879993915557861
max_mem 555520
torch.linalg.svd 0.01896810531616211
max_mem 697344
torch.linalg.eigh 0.6116993427276611
max_mem 763904
```

`torch.linalg.eigh` in PyTorch-1.9.0 is faster than that in PyTorch-1.8.0, but it still slower than `torch.linalg.svd`.
The device is the same, i.e., `NVIDIA Quadro P6000`.
It seems that `torch.linalg.svd` is also optimized.

**Comment by xwang233** [comment]
> It seems that torch.linalg.svd is also optimized.

That's right. For the problem size of 1000 x 4x4 matrices, an efficient batched algorithm is used for SVD. However, for symmetric eigenvalue decomposition, we currently have to use a for-loop based algorithm for all single matrix because there was a known numerical issue on the batched algorithm. 

We plan to update the code and use the more efficient batched algorithm for symmetric eigenvalue decomposition soon. Stay tuned! 😄

**Comment by mzhaoshuai** [comment]
Thx for reply 😄.

**Comment by yftah89** [comment]
Hi everyone, I'm interested in calculating torch.linalg.eigh on a large matrix, and it takes a lot of time, did you by any chance make some progress with this subject?
Thank you for your great API. 
@xwang233

**Comment by xwang233** [comment]
We have those features (batched `torch.linalg.eigh` on GPU) enabled in pytorch built with the latest cuda 11.5 version. Try a nightly pip wheel with
```
pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/cu115/torch_nightly.html
```

**Comment by yftah89** [comment]
I will, thank you for your fast reply :)
