### ISSUE TITLE
Is PyTorch v1.0.0 available for aarch64 (for NVIDIA Jetson devices) in this repo?

### ISSUE THREAD

**Issue by VAIBHAVPATEL97** [pytorch/pytorch#60545]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Hello,
I wanted to install PyTorch v1.0.0. on my NVIDIA Jetson board. I know this version is very old but by any chance, it is available in this repo. Even building from the source works for me. I dig into the repo but I wasn't able to find this version of PyTorch so wanted to confirm. Thanks in advance.

**Comment by VitalyFedyunin** [comment]
No, we are not providing any official Jetson builds. I advice to look for NVidia's distributions.
