### ISSUE TITLE
What does "build from source" mean? 

### ISSUE THREAD

**Issue by dkobayas-cyber** [pytorch/pytorch#60542]
In this post #31285, @peterjc123 repeatedly mentions that we need to "build from source" to circumvent the CUDA error due to the too-old GPU. I'm afraid that I'm not exactly sure what I am supposed to do. Could anyone explain a little bit further about this? 

Note: 
I'm using NVIDIA Tesla K20 with CC = 3.5 (< 3.7), which is not supported by the newest PyTorch version.

**Comment by sawradip** [comment]
I think [this](https://github.com/pytorch/pytorch#from-source) might be helpful.
