### ISSUE TITLE
Better debug info from C++

### ISSUE THREAD

**Issue by goldsborough** [pytorch/pytorch#6055]
### Problem Description

The autograd engine launches 1 + #gpus threads to execute functions. This has the downside that when an exception gets thrown in any of the functions running in one of these threads, we currently have to catch that exception and rethrow it from the main thread. The unfortunate consequence of this is that all stack traces point back to [the line where the exception is rethrown](https://github.com/pytorch/pytorch/blob/b37aa2bf0e1d0fc62a7a924c0b50fe06870c1bce/torch/csrc/autograd/engine.cpp#L358).

### Possible Solutions

1. Change the autograd engine to have a mode where it executes all tasks on the main thread,
2. Use custom exception objects everywhere and capture either:
    1. The `__LINE__` and `__FILE__` info or,
    2. The full call stack (likely preferred) using [the kernel's relevant facilities for this](http://man7.org/linux/man-pages/man3/backtrace.3.html)
3. Tell people to use `catch throw`

### Goal

In the end, the experience should really be as smooth as possible for the end user. `catch throw` will work most of the time, but people might not know about it or it may not help with debugging. Having to change the autograd execution and re-run the graph is a bit annoying. Giving the full call stack in the exception is likely the most user-friendly option, but `__LINE__` et al. is a good start.

CC @ebetica

**Comment by ebetica** [comment]
Is it possible to easily build in relwithdebinfo mode as well? It's hard to be in debug all the time for some really hard to chase  errors that pop up 1 hour into your training, and debug makes that 3+ hours.

**Comment by goldsborough** [comment]
You mean something like `@mode/dbgo`? If you need it from Python, we'd have to hack `setup.py` somehow I think. For C++ only, maybe https://github.com/pytorch/pytorch/blob/master/tools/cpp_build/libtorch/CMakeLists.txt can be changed?

**Comment by ebetica** [comment]
I just mean adding a third option to this:

https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.sh#L146

where we use relwithdebinfo instead of release or debug.

**Comment by goldsborough** [comment]
I'll look into that. It's a bit separate to this specific issue
