### ISSUE TITLE
PyTorch does not work with CUDA 9.1 if built from source using Docker

### ISSUE THREAD

**Issue by Amir-Arsalan** [pytorch/pytorch#6056]
I am compiling PyTorch from source using Docker. I replaced `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` with `nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04` but after compilation `torch.version.cuda` and `torch.cuda.get_device_name(0)` give me error. If I build with CUDA 9 things are fine.

**Comment by CDLuminate** [comment]
Could you please paste the error message here?

**Comment by Amir-Arsalan** [comment]
@CDLuminate Sorry I immediately removed that compilation and re-compiled the code with `CUDA 9.0`. I should have copied the errors here. The errors were basically saying that CUDA was not found or the GPU was not found.

**Comment by CDLuminate** [comment]
That sounds like a driver problem or alike. Anyway this issue seems not reproducible.

**Comment by Amir-Arsalan** [comment]
@CDLuminate Did you try compiling PyTorch using Docker? I simply replaced those lines in the Docker file.

**Comment by ezyang** [comment]
Can you post the exact commands you used to (1) build the image and (2) run it? Are you sure the driver version on your host system is recent enough to support CUDA 9.1?

**Comment by ruotianluo** [comment]
Did you change https://github.com/pytorch/pytorch/blob/master/docker/pytorch/Dockerfile#L20?

**Comment by Amir-Arsalan** [comment]
@ezyang What is the minimum driver version required for CUDA 9.1? Mine is `384.111`. I did not use the Docker file that you have created. I build a Singularity container and pull the NVIDIA's Docker image for CUDA 9.1. Here's how I build the Singularity image:

```
BootStrap: docker
From: nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         make \
         gcc \
         g++ \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \
         python3 \
         python3-pip \
         libjpeg-dev \
         libpng-dev \
         python3-setuptools

pip3 install --upgrade pip
pip3 install -U setuptools
pip3 install scipy \
                  numpy \
                  matplotlib \
                  mkl \
                  mkl-devel \
                  cffi \
                  Pillow
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
python3 setup.py install
```

**Comment by soumith** [comment]
I believe 9.1 requires 385+

**Comment by Amir-Arsalan** [comment]
@soumith Ah I see. That could be why then. I have to ask the people to upgrade the Driver version on our clusters. Will give you update once they do it.
