### ISSUE TITLE
request to clarify `set_default_dtype` docs

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60560]
## 📚 Documentation

As discussed on slack  `set_default_dtype` could be a little bit more explicit on what dtypes it accepts. Since the function name doesn't imply that it has to be floating. And when one tries to use a non-float type it fails, saying that it has to be floating.

Perhaps the docs could include: this function accepts only floating point dtype?

The doc does say "Sets the default floating point dtype to d", and "d (torch.dtype) – the floating point dtype to make the default", which makes sense once you understand that it's not `set_default_dtype` but really `set_default_floating_dtype`.

Which also means that the only way one could load a model in a non-float dtype, is to first do it in float and then manually convert it to another type.

Also it might be helpful to add that one could use `dtype.is_floating_point` test to check if the incoming dtype is of the right type.

Thank you.

@mruberry 

cc @brianjo @mruberry

**Comment by mruberry** [comment]
cc @jbschlosser, too, to consider the model-loading aspect of this issue

Thanks for the suggestion, @stas00. The docs could definitely be clearer about PyTorch's default dtypes and how to set them (or not).
