### ISSUE TITLE
init_rpc fails after setting CUDA_VISIBLE_DEVICES env var to ""

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#60578]
IIUC, either TensorPipe or TensorPIpeAgent needs to detect CUDA runtime availability.

### Repro

```python
import os
import torch
import torch.multiprocessing as mp
import torch.distributed.rpc as rpc


if __name__ == "__main__":
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '9867'
    os.environ["CUDA_VISIBLE_DEVICES"] = ""
    rpc.init_rpc("0",
                 rank=0,
                 world_size = 1,
                 backend=rpc.BackendType.TENSORPIPE,
                 rpc_backend_options=rpc.TensorPipeRpcBackendOptions(rpc_timeout=6000,
                                                                     init_method='env://')
                 )

    rpc.shutdown()

```

```
RuntimeError: In create at tensorpipe/common/cuda_lib.h:117 "lib.init(0)(100) CUDA_ERROR_NO_DEVICE (no CUDA-capable device is detected)"
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @lw @beauby @agolynski @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by lw** [comment]
Also tracked in https://github.com/pytorch/tensorpipe/issues/393.

**Comment by lw** [comment]
In short: TensorPipe gets confused if you use a CUDA build of PyTorch on a machine which has the CUDA driver installed and loaded but where there are no GPUs actually available.
