### ISSUE TITLE
nn.GLU is missing from the docs

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#60570]
## 📚 Documentation

The module form of `nn.GLU` is missing from the [torch.nn docs](https://pytorch.org/docs/stable/nn.html) (the [functional form](https://pytorch.org/docs/stable/generated/torch.nn.functional.glu.html) is in the docs).

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by sawrablog** [comment]
I would like to add this to the docs. 
(As this is my first time contributing here, should I wait until confirmation from the maintainers, before starting work?)

**Comment by sawradip** [comment]
I would like to add this to the docs under [non-linear activations](https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity).

**Comment by jbschlosser** [comment]
Fixed in #60590
