### ISSUE TITLE
[CI] Report wall-time and execution time stats from build/test stages

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#60591]
Currently we report 
1. wall-time for CI builds
2. python execution time for CI tests

we should report both the wall-time and execution-time in both cases because 
- [ ] build execution time, 
b/c wall-time includes checkout and other steps and it doesn't reflex the actual compile execution
- [ ] wall time for test runs,
b/c execution time of CI tests are reported in test cases level and thus doesn't account for other times (also sometimes we under reported due to duplicate test cases)

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
If possible, you should get fine grained time for individual gcc invocations, because the timings will vary wildly depending on if you get a hit on sccache or not, and the easiest way to reduce noise here is to record these separately.
