### ISSUE TITLE
CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

### ISSUE THREAD

**Issue by surya-narayanan** [pytorch/pytorch#60600]
Still getting this issue. 

Image: output of apt-get install nvidia-modprobe

<img width="476" alt="image" src="https://user-images.githubusercontent.com/17240858/123174917-c0ec5100-d435-11eb-86c9-3ef0c756f7df.png">

----

Image: output of nvidia-smi

<img width="562" alt="image" src="https://user-images.githubusercontent.com/17240858/123174828-9ef2ce80-d435-11eb-8d81-d85ecb218f7e.png">

---
Image: nvcc -V

<img width="378" alt="image" src="https://user-images.githubusercontent.com/17240858/123174852-a914cd00-d435-11eb-8d2f-bd1fdfcd1070.png">

---

Image: failing .cuda() test

<img width="575" alt="image" src="https://user-images.githubusercontent.com/17240858/123174876-b2059e80-d435-11eb-8a7b-bd70d65357c4.png">

---

Update 1 - torch.version.cuda  returns '11.1' but I have version compatibility with 11.0. 

---

Update 2 - Created an environment with torch to be compatible with 11.0. 

torch.version.cuda now returns 11.0 but error still persists.

_Originally posted by @surya-narayanan in https://github.com/pytorch/pytorch/issues/49081#issuecomment-867195773_

cc @ngimel

**Comment by VitalyFedyunin** [comment]
Hello!

Could you please copy-paste error texts and traces instead of attaching screenshots.

Thanks

**Comment by surya-narayanan** [comment]
Sure, hope the formatting comes out right

1. Output of nvidia-smi
Surya@instance-1:~$ nvidia-smi
Thu Jun 24 14:14:41 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    37W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

---

output of nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

---

output of torch.cuda.version

>>> torch.version.cuda
'11.0'

---
Error:

>>> torch.rand(1).cuda()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/torch/lib/python3.9/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

---

Notes: 

I did not install any driver manually or fail to restart after installing a driver manually if I did.

**Comment by marijnl** [comment]
I ran into the same problem with cuda 11.1 with debian 10 on GPC 
First uninstalling the cuda driver and then installing cuda 11.3 helped me solve it

```bash
# uninstall cuda 11.1
sudo nvidia-installer --uninstall

# install cuda 11.3 for debian 10
# you might need to match your distribution https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=10&target_type=deb_local

wget https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda-repo-debian10-11-3-local_11.3.1-465.19.01-1_amd64.deb
sudo dpkg -i cuda-repo-debian10-11-3-local_11.3.1-465.19.01-1_amd64.deb
sudo apt-key add /var/cuda-repo-debian10-11-3-local/7fa2af80.pub
sudo add-apt-repository contrib
sudo apt-get update
sudo apt-get -y install cuda
```

**Comment by paapu88** [comment]
I got the same error, rebooting my gpu-laptop solved the issue.
I have pytorch 1.13 (torch==1.13.1+cu116)  in ubuntu 22.04 and:
nvidia-smi
Mon Dec 26 11:25:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |

Terveisin, Markus

**Comment by dt1729** [comment]
Rebooting works for me as well, the only issue was I didn't have cuda library with NVCC.

**Comment by cesarhcq** [comment]
> I got the same error, rebooting my gpu-laptop solved the issue. I have pytorch 1.13 (torch==1.13.1+cu116) in ubuntu 22.04 and: nvidia-smi Mon Dec 26 11:25:12 2022 +-----------------------------------------------------------------------------+ | NVIDIA-SMI 510.108.03 Driver Version: 510.108.03 CUDA Version: 11.6 |
> 
> Terveisin, Markus

It solve my issue. Thanks
