### ISSUE TITLE
UserWarning: invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by ll490187880** [pytorch/pytorch#6061]
When I installed  the newest version of pytorch with source code ,I got the error :

UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  train_loss += loss.data[0]
Traceback (most recent call last):......................... 10/2984   Step: 61ms | Tot: 2s170ms | Loss:  File "testgn.py", line 267, in <module>
    train(epoch)
  File "testgn.py", line 199, in train
    % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))
RuntimeError: value cannot be converted to type uint8_t without overflow: 264

By the way,the code runs well on the pytorch installed by conda.

**Comment by qinduanyinghua** [comment]
I think you need solve the problem of the type of correct, I believe that the type of correct you get is 'byteTensor'.

**Comment by qinduanyinghua** [comment]
I'm sorry to hear that, I've had this problem before, I hope my idea can help you.

**Comment by vishwakftw** [comment]
You might have to change `loss.data[0]` to `loss.item()` as indicated in the error message.

**Comment by ezyang** [comment]
Yes, this is a side effect of Variable/Tensor merge. Follow the error message (or cast it explicitly to a float with `float(loss)`

**Comment by biswajitcsecu** [comment]
/home/kerax/usys/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
/home/kerax/usys/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:32: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number

Iter: 0, D: 1.351, G:0.6499

**Comment by AbdelnasserMostafa** [comment]
I got the same error but fixed it with loss.item() as [vishwakftw] mentioned above.  Thank you

**Comment by hierarchyJK** [comment]
Thank for [vishwakftw], this is the pytorch'version problem

**Comment by Niraj-Lunavat** [comment]
I am getting this error, does anyone knows how to solve it, Thanks in advance!

----------------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)

<ipython-input-9-0b14f60ff857> in <module>()
     21 save_file_name = 'jigsaw_cifar100_e{}_s{}.pk'.format(n_epochs, sinkhorn_iter)
     22 history = train_model(model, criterion, optimizer, train_loader, validation_loader,
---> 23                       n_epochs=n_epochs, save_file_name=save_file_name)
     24 

<ipython-input-8-08d74cbc7470> in train_model(model, criterion, optimizer, train_loader, validation_loader, n_epochs, save_file_name)
     38                 optimizer.zero_grad()
     39                 outputs = model(x_in)
---> 40                 n_correct_pred += compute_acc(vecmat2perm2x2(outputs), perms, False).data[0]
     41                 loss = criterion(outputs, y_in)
     42                 loss.backward()

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by Niraj-Lunavat** [comment]
I am getting this error, does anyone knows how to  solve it, Thanks in advance!

----------------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)

<ipython-input-9-0b14f60ff857> in <module>()
     21 save_file_name = 'jigsaw_cifar100_e{}_s{}.pk'.format(n_epochs, sinkhorn_iter)
     22 history = train_model(model, criterion, optimizer, train_loader, validation_loader,
---> 23                       n_epochs=n_epochs, save_file_name=save_file_name)
     24 

<ipython-input-8-08d74cbc7470> in train_model(model, criterion, optimizer, train_loader, validation_loader, n_epochs, save_file_name)
     38                 optimizer.zero_grad()
     39                 outputs = model(x_in)
---> 40                 n_correct_pred += compute_acc(vecmat2perm2x2(outputs), perms, False).data[0]
     41                 loss = criterion(outputs, y_in)
     42                 loss.backward()

IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by ezyang** [comment]
Follow the instructions in the error message
