### ISSUE TITLE
How to checkout 1.8.1 release

### ISSUE THREAD

**Issue by beew** [pytorch/pytorch#60625]
I am trying to compile pytorch 1.8.1 release from source but not sure which branch to checkout, as there is no 1.8.1 and the 1.8.0 branches seem to be rc1 or rc2. 

so for example

```
git checkout -b  remotes/origin/lts/release/1.8

git describe --tags
```

returns

v1.8.0-rc1-4570-g80f40b172f

So how to get 1.8.1? I know the release tarballs don't work

**Comment by cdeepali** [comment]
`git checkout v1.8.1`

**Comment by beew** [comment]
> `git checkout v1.8.1`
Yes, I did that and 
git describe --tags

returns

v1.8.0-rc1-4570-g80f40b172f

**Comment by albanD** [comment]
After doing the checkout, I get
```
$ git describe --tags
v1.8.1
```

Make sure you fetch the latest version from github?

**Comment by beew** [comment]
> After doing the checkout, I get
> 
> ```
> $ git describe --tags
> v1.8.1
> ```
> 
> Make sure you fetch the latest version from github?

I cloned the git repository. Will delete the whole thing and try again.
