### ISSUE TITLE
Could not fine the python interface for SpatialDepthwiseConvolution

### ISSUE THREAD

**Issue by back2yes** [pytorch/pytorch#6063]
Hi, I need to implement a convolution layer with cuda in a sliding window fashion (rather than using im2col and apply matrix multiplication.) I read the code in pytorch sources here: https://github.com/pytorch/pytorch/blob/master/aten/src/THCUNN/SpatialDepthwiseConvolution.cu. However I did not find its interface that I can invoke in python. I have also looked for it in the legacy interface, it was not there either. Where did it go?

Thanks in advance.

**Comment by apaszke** [comment]
You're looking for the `groups` argument in [Conv2d](http://pytorch.org/docs/0.3.1/nn.html?highlight=conv2d#torch.nn.Conv2d).

**Comment by fmassa** [comment]
@back2yes as @apaszke said, just use `nn.Conv2d` and the depthwise path will be activated in [the following cases](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Convolution.cpp#L151-L156)
