### ISSUE TITLE
Error in the PyTorch GRU Doc Page

### ISSUE THREAD

**Issue by abedshantti** [pytorch/pytorch#60645]
## 📚 Documentation

I have noticed that there is an error in the docs for the GRU layer.: https://pytorch.org/docs/stable/generated/torch.nn.GRU.html

Shouldn’t the hidden layer in the 4th line of the definition be presented as:

`h(t) = ( (1 - z(t) ) * h(t-1) ) + ( z(t) * n(t) )`

instead of the : `h(t) = ( (1 - z(t) ) * n(t) ) + ( z(t) * h(t-1) )` currently written in the docs?

Here is the architecture of the GRU layer:
https://gist.github.com/sey-kh/34cd13a4139b30776ff697b431c3c370

cc @brianjo @mruberry @albanD @jbschlosser @zou3519

**Comment by Bharat123rox** [comment]
I  have not been able to find the original implementation in Pytorch, however,
The existing equation/formulation is correct according to equation (7) in the original paper:
https://arxiv.org/pdf/1406.1078.pdf
(Learning Phrase Representations using RNN Encoder-Decoder for Statistical Machine Translation by KyungHyun Cho et. al)

{Replacing `n(t)` by `h~(t)` from the original paper}

**Comment by abedshantti** [comment]
> I have not been able to find the original implementation in Pytorch, however,
> The existing equation/formulation is correct according to equation (7) in the original paper:
> https://arxiv.org/pdf/1406.1078.pdf
> (Learning Phrase Representations using RNN Encoder-Decoder for Statistical Machine Translation by KyungHyun Cho et. al)
> 
> {Replacing `n(t)` by `h~(t)` from the original paper}

Ok this is strange since almost every other source, apart from the original paper, construct the equation as the one I linked. 

The formulation of `h(t)` according to equation (5) have the terms reversed in this paper (some of these authors were also the authors of the original paper):

https://arxiv.org/pdf/1412.3555.pdf
(Empirical Evaluation of Gated Recurrent Neural Networks on Sequence Modeling by Chung, Gulcehre, Cho and Bengio).

So now I am genuinely confused about the correct implementation.

**Comment by Bharat123rox** [comment]
I agree, this is now more confusing

I tracked down the source of the image in the Github gist to: https://colah.github.io/posts/2015-08-Understanding-LSTMs/
and I have emailed the author of that blog also regarding the discrepancy

Also, if you see this blog post: https://towardsdatascience.com/understanding-gru-networks-2ef37df6c9be
(Section 4. Final memory at current time step) it goes by the original paper implementation again!

My educated guess is that the emphasis is on the basic idea, that it is a linear interpolation controlled the update gate `z(t)` between the new state `n(t)` and old state `h(t-1)` that still holds in both cases, 
but it may vary depending on the definition of the update gate itself

**Comment by abedshantti** [comment]
Thanks for following up on this and contacting the blog authors. I can mark this issue as closed.
