### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory when putting tensor in multiprocessing queue

### ISSUE THREAD

**Issue by lematt1991** [pytorch/pytorch#60654]
## 🐛 Bug

I have a script that creates a bunch of workers who then store some results (pytorch tensors) in a multiprocessing queue.  This ends up raising the following error: `FileNotFoundError: [Errno 2] No such file or directory`.  However, if I instead convert the tensor to a numpy array before putting in the queue, everything works fine.

## To Reproduce

```Python
from torch import multiprocessing as mp
import torch

def f(q):
    x = torch.rand(5, 5)
    q.put(x)  # <---- Change this to `q.put(x.numpy())` to fix
    q.close()
    q.join_thread()


if __name__ == '__main__':
    mp.set_start_method('spawn')
    nworkers = 5
    q = mp.Queue()
    workers = [mp.Process(target=f, args=(q,)) for _ in range(nworkers)]
    [w.start() for w in workers]

    for _  in range(nworkers):
        x = q.get()
        print(x)

    [w.join() for w in workers]
```

1. Run the above script to show error
2. Change `q.put(x)` to `q.put(x.numpy())` to resolve error

## Expected behavior
No error

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.2.2
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.20.3           py38h9894fe3_0    conda-forge
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by DamonDeng** [comment]
Seems that you are not following the best practices of sending Tensor in Queue. In short, you need to setup an event to ask sub process to wait for main process to read the queue.

Please refer to the following link for more information:
https://discuss.pytorch.org/t/tensors-as-items-in-multiprocessing-queue/411

And the following is the sample code I modified, which works well:

    from torch import multiprocessing as mp
    import torch
    
    def f(q, evt):
        x = torch.rand(5, 5)
        q.put(x)  # <---- Change this to `q.put(x.numpy())` to fix
        evt.wait()
    #     q.close()
    #     q.join_thread()
    
    
    if __name__ == '__main__':
        mp.set_start_method('spawn')
        nworkers = 5
        
        evt = mp.Event()
        
        q = mp.Queue()
        workers = [mp.Process(target=f, args=(q,evt,)) for _ in range(nworkers)]
        [w.start() for w in workers]
    
        for _  in range(nworkers):
            x = q.get()
            print(x)
            
        evt.set()
        
        [w.join() for w in workers]

**Comment by lematt1991** [comment]
Thanks for the pointer @DamonDeng, wasn't aware of this!

**Comment by loretoparisi** [comment]
I had the same issue and solved in fact setting `model(x).cpu().numpy()`

```python
import torch
import torch.multiprocessing as mp
from torchvision.models import AlexNet
import multiprocessing

def infer(rank, task_queue, result_queue, num_gpus):
    """Each subprocess will run this function on a different GPU indicated by `rank`."""
    model = AlexNet()
    device = torch.device(f"cuda:{rank % num_gpus}")
    model.to(device)
    while True:
        task = task_queue.get()
        if task is None:  # Check for sentinel value
            break
        task_index, a, b = task  # Unpack the task
        x = a + b
        x = x.to(device)
        with torch.no_grad():
            # LP: see https://github.com/pytorch/pytorch/issues/60654
            output = model(x).cpu().numpy()  # Detach the output from the computation graph and move to CPU
            result_queue.put((task_index, rank, output))  # Store the result in the result queue with task index
            del a, b  # free memory
            print(f"Inference on process {rank}, using GPU {rank % num_gpus}")

def main(num_processes, num_gpus):
    
    task_queue = mp.Queue()
    result_queue = mp.Queue()  # Queue to collect results
    processes = []
    for rank in range(num_processes):
        p = mp.Process(target=infer, args=(rank, task_queue, result_queue, num_gpus))
        p.start()
        processes.append(p)
    
    for task_index in range(10):
        a = torch.randn(1, 3, 224, 224)
        b = torch.randn(1, 3, 224, 224)
        task_queue.put((task_index, a, b))
    
    for _ in range(num_processes):
        # # sentinel value to signal subprocesses to exit
        task_queue.put(None)  # Only None to match the expected number of arguments
    
    for p in processes:
        p.join()  # wait for all subprocesses to finish
        
    # Now collect and print all the results from the result queue
    results = []
    while not result_queue.empty():
        task_index, rank, result = result_queue.get()
        results.append((task_index, rank, result))
    
    # Sort results by task index to maintain the original order
    results.sort(key=lambda x: x[0])
    
    for task_index, rank, result in results:
        print(f"Result from task {task_index}, process {rank}: {result.size}")

if __name__ == "__main__":
    # LP: Ensures the spawn start method is used, which is safer for CUDA operations in multiprocessing.
    mp.set_start_method('spawn', force=True)
    # Number of subprocesses, adjust according to your needs
    num_processes = 4
    # you may want to use
    # num_processes = multiprocessing.cpu_count()
    num_gpus = torch.cuda.device_count()  # Automatically get the number of GPUs available
    main(num_processes, num_gpus)
```
