### ISSUE TITLE
Inconsistency Between the Return Value of torch.nonzero() and the Indexing Standard for 1D tensors

### ISSUE THREAD

**Issue by roeemz** [pytorch/pytorch#6065]
- OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)
- PyTorch version: 0.3.1.post2
- How you installed PyTorch (conda, pip, source): conda
- Python version: Python 3.6.4
- CUDA/cuDNN version: Cuda compilation tools, release 8.0, V8.0.61
- GPU models and configuration: 2 1080 Ti
- GCC version (if compiling from source): n/a

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible:

import torch

inp = torch.rand(5)
idx = inp.nonzero()

#only works like this:
print(inp[idx.view(-1)])
#doesn't work like this:
print(inp[idx])

- Error messages and/or stack traces of the bug

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Indexing a Tensor with a torch.LongTensor triggers index_select semantics, and thus we expect a vector, but the indexing Tensor passed has 2 dimensions

- Context around what you are trying to do

trying to access indices returned by "torch.nonzero()"

[index_bug_pytorch.zip](https://github.com/pytorch/pytorch/files/1854947/index_bug_pytorch.zip)

**Comment by fmassa** [comment]
I wouldn't say this is a bug, but instead a legacy behavior that I'd rather see it changed.
This issue discuss it a bit more https://github.com/pytorch/pytorch/issues/1834#issuecomment-337303630

**Comment by apaszke** [comment]
Let's keep the discussion in that issue then
