### ISSUE TITLE
[Question] why libATen.so is not a symlink to libATen.so.1 ?

### ISSUE THREAD

**Issue by leomao** [pytorch/pytorch#6066]
I found that `libATen.so` is identical to `libATen.so.1` in torch/lib.  It seems that it should be a symlink?

- OS: Arch Linux
- PyTorch version: master
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6
- CUDA/cuDNN version: 9.1/7.1.1
- GCC version (if compiling from source): 5.5.0

**Comment by ezyang** [comment]
Context: https://github.com/pytorch/pytorch/pull/4820

There's a follow up patch to be done here but I haven't written it yet.
