### ISSUE TITLE
cuda() takes a very long time.

### ISSUE THREAD

**Issue by Mabinogiysk** [pytorch/pytorch#6067]
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda install pytorch torchvision
- Python version: 3.6
- CUDA/cuDNN version: cuda8.0
- GPU models and configuration: GTX1060
- GCC version (if compiling from source): g++-4.9

This is just a feedback. I fixed it with pip install.

cc @ngimel

**Comment by shagunsodhani** [comment]
Hey @Mabinogiysk Could you add a minimal example that we could run on our end.
