### ISSUE TITLE
LSTM output dimensions

### ISSUE THREAD

**Issue by emanjavacas** [pytorch/pytorch#607]
According to the docs nn.LSTM outputs:

```
output : A (seq_len x batch x hidden_size) tensor containing the output features (h_t) from the last layer of the RNN, for each t
h_n : A (num_layers x batch x hidden_size) tensor containing the hidden state for t=seq_len
c_n : A (num_layers x batch x hidden_size) tensor containing the cell state for t=seq_len
```

However, if the LSTM is initialized as a bidirectional LSTM what you get is:

```
output : A (seq_len x batch x hidden_size * num_directions) tensor containing the output features (h_t) from the last layer of the RNN, for each t
h_n : A (num_layers * num_directions x batch x hidden_size) tensor containing the hidden state for t=seq_len
c_n : A (num_layers * num_directions x batch x hidden_size) tensor containing the cell state for t=seq_len
```

It'd be nice to make this explicit in the docs.
Also, I was wondering if the default concatenatin behaviour can be tweaked (to merging, for instance)?
These would all be nice features to have.

**Comment by apaszke** [comment]
Yes, this will need to be fixed. Thanks!

Can you elaborate how merging is different from concatenation?

**Comment by emanjavacas** [comment]
Ah yeh, I mean using a different merge function like for instance addition.

**Comment by apaszke** [comment]
Ah I see. I think there's no good way to do that. For example when you use CUDA we'll use cuDNN that requires the output to be a big tensor, and it will fill it in parallel, as it computes multiple steps at a time. So we'd have to do the sum in a different op anyway, but it's the same as if you did it yourself.

**Comment by emanjavacas** [comment]
I see. I am not sure about the philosophy behind pytorch (is it more oriented towards research/academy, does it prioritize simplicity vs. batteries-included APIs? etc.), but I could imagine it being handy to have different standard options pre-implemented in the python API - the way, for instance, Lasagne, does. That'd be very convenient for people working in research, where you would like to quickly check some variations on the implementation. In this case, it could then be mentioned that using this particular merge function would result in a slower model when running on the GPU (if I understand correctly).

Of course, this is just my two pennies; that is, input from the API user perspective.

**Comment by SeanNaren** [comment]
The way I handle this is by making each RNN layer of size 1, and using this after each BRNN:

```python
 # (TxNxD*2) -> (TxNxD) by sum
if self.bidirectional:
     x = x.view(x.size(0), x.size(1), 2, -1).sum(2).view(x.size(0), x.size(1), -1) 
```
Not as simple as just taking the output of the BRNN but hopefully that helps...

**Comment by apaszke** [comment]
At this point want to keep the APIs as simple as possible. This often doesn't limit their flexibility and makes it easier for people to learn the framework. Also, if we introduce functions/arguments that are not going to be very useful it might be hard to deprecate and remove them later, so it has to be done with care.

For example, adding the hidden states is only a matter of calling one method on the output, so I don't think it's worth extending the API. You can add it in as many characters, as it would take you to specify a different merge mode, and it will be immediately clear what you wanted to do.
