### ISSUE TITLE
the output of ONNX is different from the pth's output

### ISSUE THREAD

**Issue by lucky-xu-1994** [pytorch/pytorch#60712]
1. I want to convert the pth to ONNX , the project I worked with is aliyun/conditional-lane-detection.

the model build like this.
a. in condlanenet.py
![image](https://user-images.githubusercontent.com/57120921/123360696-53a8ff00-d5a0-11eb-8279-a62ab2830d5a.png)
b. in condlanenet_head.py
![image](https://user-images.githubusercontent.com/57120921/123360657-4429b600-d5a0-11eb-9663-21a84adf86ae.png)
![image](https://user-images.githubusercontent.com/57120921/123360740-66bbcf00-d5a0-11eb-8ce4-fbbab7967a62.png)
2. Use the following code to convert.
![image](https://user-images.githubusercontent.com/57120921/123360805-83f09d80-d5a0-11eb-8bf0-bd249610a774.png)
and problem is that, it only converts to the line 417 at condlanenet_head.py, and then output the pres.
![image](https://user-images.githubusercontent.com/57120921/123360848-94a11380-d5a0-11eb-86b5-b68268a7e108.png)
Have anyone experienced the same problem? please give me some advise! thank you!

cc @garymm @BowenBao @neginraoof

**Comment by BowenBao** [comment]
In order to capture controlflow (if, for loops) correctly, you need to first script the model before calling onnx export. Please check https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting for more info.

**Comment by lucky-xu-1994** [comment]
> In order to capture controlflow (if, for loops) correctly, you need to first script the model before calling onnx export. Please check https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting for more info.

thank you for your help, I've found the problem. The model I script has unsupported ops. such as
![image](https://user-images.githubusercontent.com/57120921/123498692-2cb40100-d664-11eb-9471-e26d19c638fb.png)
![image](https://user-images.githubusercontent.com/57120921/123498702-40f7fe00-d664-11eb-9200-4dabce9deda6.png)
Thank you anyway!

**Comment by lucky-xu-1994** [comment]
> In order to capture controlflow (if, for loops) correctly, you need to first script the model before calling onnx export. Please check https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting for more info.

thank you for your help, I've found the problem. The model I script has unsupported ops. such as
![image](https://user-images.githubusercontent.com/57120921/123498692-2cb40100-d664-11eb-9471-e26d19c638fb.png)
![image](https://user-images.githubusercontent.com/57120921/123498702-40f7fe00-d664-11eb-9200-4dabce9deda6.png)
Thank you anyway!

**Comment by garymm** [comment]
Closing due to lack of reply from the creator. If this is still an issue in the latest nightly PyTorch, please open a new issue with clear repro instructions.
