### ISSUE TITLE
`TensorPipeJitRpcTestWithSpawn.test_call_fork_in_jit_with_profiling` is failing on the master branch

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60713]
## 🐛 Bug

`TensorPipeJitRpcTestWithSpawn.test_call_fork_in_jit_with_profiling` seems to be consistency failing on the master branch.

## To Reproduce

[CI of a PR merged with the master branch](https://app.circleci.com/pipelines/github/pytorch/pytorch/341741/workflows/d31d2c4d-4994-4fb2-871a-a24f13a9319c/jobs/14382268/tests#failed-test-0) & [CI of a PR that hasn't been merged yet](https://app.circleci.com/pipelines/github/pytorch/pytorch/341748/workflows/267ad0d5-0aa5-4144-922a-ec957a533e73/jobs/14382878).

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 399, in wrapper
    self._join_processes(fn)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 606, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 655, in _check_return_codes
    self.assertEqual(
  File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1507, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing -6 and 0 gives a difference of 6, but the allowed difference with rtol=0 and atol=0 is only 0!
Expect process 2 exit code to match Process 0 exit code of 0, but got -6
```

## Expected behavior

This test should pass.

## Environment

CI (`pytorch_linux_bionic_py3_8_gcc9_coverage_test2`)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @gmagogsfm

**Comment by ansley** [comment]
Thanks for letting us know! The engineers who maintain these tests are looking into the failure, so I'm going to close the issue for now
