### ISSUE TITLE
`test_reference_numerics_hard_polygamma_polygamma_n_2_cpu_bfloat16` is failing on `pytorch_linux_xenial_py3_clang5_asan_test2`

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/pytorch#60722]
## 🐛 Bug

In the CI check `pytorch_linux_xenial_py3_clang5_asan_test2`,, `TestUnaryUfuncsCPU.test_reference_numerics_hard_polygamma_polygamma_n_2_cpu_bfloat16` is failing on the master branch.

#60444 has since been reverted, so this test isn't being run.

## To Reproduce

[Merged PRs on the master branch](https://app.circleci.com/pipelines/github/pytorch/pytorch/341815/workflows/b301f582-2e7d-471f-88ad-6380ee5a79bf/jobs/14384401)

```
var/lib/jenkins/workspace/aten/src/ATen/native/Math.h:217:17: runtime error: division by zero
#0 0x7f6ac68f28dc in void c10::function_ref<void (char**, long const*, long, long)>::callback_fn<auto at::TensorIteratorBase::loop_2d_from_1d<void at::native::(anonymous namespace)::cpu_kernel<at::native::AVX2::polygamma_kernel(at::TensorIteratorBase&, long)::$_24::operator()() const::{lambda()#6}::operator()() const::{lambda(c10::BFloat16)#1}>(at::TensorIteratorBase&, at::native::AVX2::polygamma_kernel(at::TensorIteratorBase&, long)::$_24::operator()() const::{lambda()#6}::operator()() const::{lambda(c10::BFloat16)#1}&&, long)::{lambda(char**, long const*, long)#1}>({lambda(c10::BFloat16)#1} const&)::{lambda(char**, long const*, long, long)#1}>(long, char**, long const*, long, long) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0x18ea38dc)
#1 0x7f6abb204af0 in at::internal::serial_for_each(c10::ArrayRef<long>, c10::ArrayRef<long>, char**, unsigned long, c10::function_ref<void (char**, long const*, long, long)>, at::Range) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xd7b5af0)
#2 0x7f6abb1ed742 in at::TensorIteratorBase::serial_for_each(c10::function_ref<void (char**, long const*, long, long)>, at::Range) const (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xd79e742)
#3 0x7f6abb1ecbca in at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xd79dbca)
#4 0x7f6ac68ef64d in at::native::AVX2::polygamma_kernel(at::TensorIteratorBase&, long) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0x18ea064d)
#5 0x7f6abb8871f9 in at::native::structured_polygamma_out::impl(long, at::Tensor const&, at::Tensor const&) (/opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so+0xde381f9)
```

## Expected behavior

This test should pass.

## Environment

[CI](https://app.circleci.com/pipelines/github/pytorch/pytorch/341815/workflows/b301f582-2e7d-471f-88ad-6380ee5a79bf/jobs/14384401)

**Comment by imaginary-person** [comment]
Hello @albanD, please note that the CI check on which this test fails doesn't run with all PRs on the master branch.

**Comment by albanD** [comment]
cc @seemethere is that behavior of not running on all master commits expected?

**Comment by imaginary-person** [comment]
Sorry for the confusion, @albanD! I was wrong about it not being run with all CI runs.

**Comment by imaginary-person** [comment]
The test isn't failing now because it's not currently being run, [as #60444 was reverted](https://github.com/pytorch/pytorch/commit/561132f90228a6c92fd6d13ededdf2006f20e769#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144), because this test was failing on master.

The fix is correct, though.

**Comment by albanD** [comment]
Should we close this issue then?
We just need to make sure we don;t break master when relanding 60444 ?
