### ISSUE TITLE
Unable to import torch 1.9.0 version -> NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by rahul-raj** [pytorch/pytorch#60734]
## To Reproduce

1.  Install torch version 1.9.0
2.  Just open a jupyter notebook and import torch there.

This error happens only when I change torch version from 1.4.0 to 1.9.0. No such issues with torch 1.4.0 version. 

```
---> 22 import torch
     23 from tqdm import tqdm
     24 from attrdict import AttrDict

/python/PROJ/torch/1.9.0-py37/exec/lib/torch/__init__.py in <module>()
    227 
    228 
--> 229 __all__ += [name for name in dir(_C)
    230             if name[0] != '_' and
    231             not name.endswith('Base')]

NameError: name '_C' is not defined
```

## Expected behavior

Should be able to import without any error. 

## Environment

 - PyTorch Version - 1.9.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): Using pip 
 - Build command you used (if compiling from source): 
 - Python version: 3.7.1
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: NA

cc @malfet @seemethere @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mszhanyi** [comment]
I don't reproduct it. Did you install the torch in a clean virtual environment?

**Comment by malfet** [comment]
Does import command works for regular python runtime? (I.e. would something like `python3 -c "import torch"` work if executed from command prompt?)
Perhaps jupyter is based on different runtime than the one PyTorch was installed into.

**Comment by vladimir-aubrecht** [comment]
Could not reproduce with latest stack and considering discussion is stale, I am closing this issue. In case issue persist with latest stack, please create new issue.
