### ISSUE TITLE
IN_PULL_REQUEST env var might not be set correctly on CircleCI

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#60746]
This bug is some what related to #60111

Essentially, there are several interesting issues
1. discrepancy of the env var setting:
  - in .jenkins/pytorch/macos-test.sh
`IN_PULL_REQUEST=${CIRCLE_PULL_REQUEST:-${GITHUB_HEAD_REF:-}}`
  - but in other .jenkins/**/*test.sh
`IN_PULL_REQUEST=${CIRCLE_PULL_REQUEST:-}` 

2. `CIRCLE_PULL_REQUEST` is not consistently set, whether this [built-in env var](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) exists depends on:
- whether ghstack is used (well in fact depend on whether the PR is coming from pytorch/pytorch repo or a fork) see: 
  - #60742 and 
  - #60694, 
- whether any additional github label is used (e.g. did pytorch/probot make some changes)
- whether the circleci uses a fake branch name with the /head suffix or not see: 
  - https://app.circleci.com/pipelines/github/pytorch/pytorch?branch=pull%2F60696%2Fhead vs 
  - https://app.circleci.com/pipelines/github/pytorch/pytorch?branch=pull%2F60696

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @albanD who noticed this first. 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
As a follow up to this it'd probably be good to submit an experimental PR to judge what environment variables we're receiving from CircleCI workflows submitted using the standard `push` event vs. workflows submitted using the `pytorch-probot` triggering

**Comment by ezyang** [comment]
BTW, if you are depending on very detailed differences in how CircleCI (or any other third party platform) behave under different conditions, it may be worth writing a test suite (for the third party!) so you can also tell when any of this changes :)

**Comment by seemethere** [comment]
Might not be very useful since we're moving away from CircleCI

**Comment by malfet** [comment]
Plus one, CircleCI workflows are gone, closing
