### ISSUE TITLE
[jit][script] differentiating tensor.chunk gives error

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#6075]
Repro:
```

import torch
@torch.jit.script
def halve(input):
    x, y = input.chunk(2, 1)
    return x, y

input = torch.tensor(torch.arange(0, 10).view(5, -1), requires_grad=True)
halve(input)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-6a7415060fdf> in <module>()
      6
      7 input = torch.tensor(torch.arange(0, 10).view(5, -1), requires_grad=True)
----> 8 halve(input)

RuntimeError: torch/csrc/jit/autodiff.cpp:194: createZerosLike: can't allocate zero gradient for a va
lue without a type
```
From some time in gdb, my guess is that it's trying to allocate a zero gradient for the integer inputs to `chunk` but I'm not sure.

cc @zdevito

**Comment by zou3519** [comment]
Edit: the above guess was incorrect.

It looks like `torch.chunk`'s outputs have `DynamicType`(because their shape depends on the inputs) and 
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/autodiff.cpp#L267-L276
attempts to create zeros like each output but can't because it doesn't have shape information

**Comment by apaszke** [comment]
Yep, looks like it fails for the exact same reason as #6139 (integral inputs to an unsupported op in shape inference)

**Comment by zou3519** [comment]
Not sure which PR did it, but this appears to be supported now
