### ISSUE TITLE
[torch.profiler] double counting CUDA wrapper self-cuda-time

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60783]
## 🐛 Bug

As discussed with @ngimel on torch slack, CUDA wrappers incorrectly report self-cuda-time - should be 0 or close to 0, but instead they are reporting total-cuda-time.

## To Reproduce

```
import torch
from torch import nn
from torch.profiler import profile, record_function, ProfilerActivity
scores = torch.rand(16,8,512,512).half().cuda()
with torch.profiler.profile(activities=[ProfilerActivity.CUDA, ProfilerActivity.CPU], record_shapes=False) as prof:
     with record_function("auto_dtype"):
         for i in range(100):
             attn_weights = nn.functional.softmax(scores.float(), dim=-1, dtype=scores.dtype)
print(prof.key_averages().table(sort_by="cuda_time_total"))
```

```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                             auto_dtype         2.38%       1.770ms        28.61%      21.270ms      21.270ms       0.000us         0.00%      71.268ms      71.268ms             1  
                                               aten::to         7.49%       5.567ms        19.61%      14.582ms      72.910us       0.000us         0.00%      53.154ms     265.770us           200  
                                            aten::copy_         3.49%       2.596ms         7.22%       5.366ms      26.830us      53.154ms        74.58%      53.154ms     265.770us           200  
                                          aten::softmax         1.45%       1.076ms        13.04%       9.693ms      96.930us       0.000us         0.00%      44.059ms     440.590us           100  
void at::native::unrolled_elementwise_kernel<at::nat...         0.00%       0.000us         0.00%       0.000us       0.000us      27.209ms        38.18%      27.209ms     272.090us           100  
void at::native::unrolled_elementwise_kernel<at::nat...         0.00%       0.000us         0.00%       0.000us       0.000us      25.945ms        36.40%      25.945ms     259.450us           100  
                                         aten::_softmax         1.97%       1.466ms         5.16%       3.839ms      38.390us      18.114ms        25.42%      18.114ms     181.140us           100  
void (anonymous namespace)::softmax_warp_forward<c10...         0.00%       0.000us         0.00%       0.000us       0.000us      18.114ms        25.42%      18.114ms     181.140us           100  
                                            aten::zeros         0.04%      29.000us         0.07%      55.000us      55.000us       0.000us         0.00%       0.000us       0.000us             1  
                                            aten::empty         1.15%     855.000us         1.15%     855.000us       8.382us       0.000us         0.00%       0.000us       0.000us           102  
                                            aten::zero_         0.00%       3.000us         0.00%       3.000us       3.000us       0.000us         0.00%       0.000us       0.000us             1  
                                    aten::empty_strided         4.91%       3.649ms         4.91%       3.649ms      18.245us       0.000us         0.00%       0.000us       0.000us           200  
                                       cudaLaunchKernel         5.31%       3.947ms         5.31%       3.947ms      13.157us       0.000us         0.00%       0.000us       0.000us           300  
                                       aten::empty_like         0.49%     367.000us         1.61%       1.196ms      11.960us       0.000us         0.00%       0.000us       0.000us           100  
                                  cudaDeviceSynchronize        71.32%      53.030ms        71.32%      53.030ms      53.030ms       0.000us         0.00%       0.000us       0.000us             1  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 74.355ms
Self CUDA time total: 71.268ms

```

Here:

* aten::_softmax => void (anonymous namespace)::softmax_warp_forward<c10.. for 18ms
* aten::copy_  => 2 different void at::native::unrolled_elementwise_kernel for a total of 53ms

So the final report of Self CUDA time total 72ms is correct. ~(18+53)

But the results table doesn't report  Self CUDA  correctly for functions that call kernels.
It should be (I rounded ms for simplicity)

```
Name                   Self CUDA | CUDA total
aten::_softmax       | 0         | 18ms
softmax_warp_forward | 18ms      | 18ms

aten::copy_          | 0         | 53ms
at::native::unrolled1| 27ms      | 27ms
at::native::unrolled1| 26ms      | 26ms
````

now we can see which functions actually did the work.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-tb-profiler         0.2.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```

cc @ilia-cher @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by gaoteng-git** [comment]
@stas00 The "softmax_warp_forward" is a CUDA kernel. Now the CUDA time will be counted twice, one is the kernel self, one is its launched operator. 
So I think it's not a bug, it's by design.
![image](https://user-images.githubusercontent.com/10429114/123760309-4c148d80-d8f3-11eb-9f41-91a8fe918b3d.png)

**Comment by stas00** [comment]
This is correct, the problem is not there. 

The problem is 
1. `aten::_softmax` reporting the CUDA time of "softmax_warp_forward"
2. `aten::copy_  `  reporting CUDA time for 2 `at::native::unrolled1...` kernels.

and both should be 0 or close to.

**Comment by gaoteng-git** [comment]
@stas00 the at::native::unrolled is also CUDA kernel, which is launched by CPU side operator aten::copy_.
![image](https://user-images.githubusercontent.com/10429114/123898294-a830ed80-d997-11eb-8de1-22981765b37e.png)
I get your point, you suggest to make all operators' "Self CUDA" time to 0, right?
The current design shows bottom level operator "Self CUDA" with the kernels it directly launchs. And it is consistent with current tensorboard plugin's operator view:
![image](https://user-images.githubusercontent.com/10429114/123898742-74a29300-d998-11eb-83f3-10e3d95a6458.png)

I accept that current CLI table seems confusing. Because summing up all rows' "Self CUDA" is better than total CUDA time. Right?
Maybe separating the current CLI table into 2 tables is better for user to see? One includes all operators, the other includes all kernels.

**Comment by gaoteng-git** [comment]
@gdankel @ilia-cher What's your opinion on this? I suppose that the CLI table will be deprecated in some future day. So is it necessary to upgrade it?

**Comment by stas00** [comment]
> Because summing up all rows' "Self CUDA" is bigger than total CUDA time. Right?

That's correct. The "Self CUDA" of CPU wrappers should be ~0, because they don't run on CUDA, but kernels they call do.

> Maybe separating the current CLI table into 2 tables is better for user to see?

Please don't. It's not better.

The problem is that the profiler doesn't have any practical guides for doing useful profiling and diagnostics work, and then it's unclear why would a user want numbers to add up. It's already much more difficult to work with due to cpu and gpu, as compared to a normal profiler, so please don't make it more difficult than it is already.

Let's do a guide to using the profiler to solve actual problems, and then it'll become very clear what's useful and what's lacking.

> I suppose that the CLI table will be deprecated in some future day

I hope you don't deprecate it, since the fancy UI tables are fancy, but are very difficult to work with when one needs to trace slow downs and comparing several outputs.

And yes, I now know I can implemented my own CLI table, but why kill a useful tool.

And I also hear that you'd rather not waste precious resources on potentially little use. My take is that the use is low because it's hard to use.

**Comment by gaoteng-git** [comment]
Got it. Enriching the guide is necessary.

**Comment by ngimel** [comment]
I agree with @stas00, we should not deprecate CLI table because it is quite useful, and GUI tools are not always practical to use, and we also should not split it in 2.
