### ISSUE TITLE
NaN problem for warpctc_pytorch.CTCLoss (and inconsistency between GPU and CPU)

### ISSUE THREAD

**Issue by SuperIRabbit** [pytorch/pytorch#60797]
When training a model using warpctc_pytorch.CTCLoss, we got the NaN loss from time to time, so I decided to log the input causing such cases, and was able to reproduce some weird behavior between the GPU and CPU versions. Here's an example that runs through the following test cases (on a gpu server):
Case 1a: constant input showing that the CPU version works
Case 1b (1): constant input showing that the GPU version works
Case 2a: loading the input (that led to NaN loss on GPU) using CPU map_location, and it returns the (presumably) correct value (0.8019)
Case 1b (2): constant input showing that the GPU version still works
Case 2b: loading the input (that led to NaN loss on GPU) directly (onto GPU), and it returns 0 loss ?!
Case 1b (3): trying to test the constant input again, but now the cuda is down with message "CUDA error: an illegal memory access was encountered"

```
import torch
from torch import nn
from warpctc_pytorch import CTCLoss
```
```
criterion_seq_decoder = CTCLoss()
```
```
# Case 1a: all ones, CPU
preds = torch.ones([32, 2, 211])
flatten_targets = torch.ones([41], dtype=torch.int32)
preds_size = torch.ones([32, 32], dtype=torch.int32)
length_for_loss = torch.ones([9, 32], dtype=torch.int32)
```
```
criterion_seq_decoder(
    preds, flatten_targets, preds_size, length_for_loss
)
```
tensor([10.7037])
```
# Case 1b: all ones, GPU
preds = torch.ones([32, 2, 211]).cuda()
flatten_targets = torch.ones([41], dtype=torch.int32)
preds_size = torch.ones([32, 32], dtype=torch.int32)
length_for_loss = torch.ones([9, 32], dtype=torch.int32)
```
```
criterion_seq_decoder(
    preds, flatten_targets, preds_size, length_for_loss
)
```
tensor([10.7037])
```
# Case 2a, loading input that led to NaN loss on GPU using CPU map_location
with open("dbg_ctc_th.pt", "rb") as buffer:
    dbg_info = torch.load(buffer, map_location=torch.device('cpu'))
```
```
dbg_info
```
{'preds': tensor([[[15.0986,  1.8929,  3.5891,  ..., -2.1942, -1.2969, -1.5835],
          [ 5.6930,  8.1056,  2.2196,  ..., -3.0562, -2.7510, -2.7415]],
         [[15.4319,  2.4563,  3.8988,  ..., -2.1413, -1.2563, -1.6718],
          [10.1033,  6.2490,  2.9085,  ..., -2.9902, -2.7306, -3.4103]],
         [[14.9405,  2.5963,  3.6762,  ..., -2.2741, -1.2802, -1.6602],
          [ 8.2425,  3.3113,  3.6833,  ..., -3.3457, -3.5685, -2.5054]],
         ...,
         [[10.4214,  2.3318,  2.2365,  ..., -1.7694, -1.7168, -1.9450],
          [ 6.6448,  6.7991,  2.8149,  ..., -1.9615, -2.0947, -1.8070]],
         [[19.0044,  3.0739,  4.6395,  ..., -2.3479, -1.7873, -2.0688],
          [ 6.4414,  6.7229,  4.4431,  ..., -2.0557, -2.6084, -2.1918]],
         [[17.1121,  4.2718,  4.2040,  ..., -2.1180, -1.9417, -1.7361],
          [ 6.9267,  7.2849,  5.9429,  ..., -1.9777, -2.6550, -2.5887]]],
        requires_grad=True),
 'flatten_targets': tensor([12, 38, 14, 18, 14, 29, 34,  6,  9, 16,  7, 28, 30,  2, 30, 38, 15,  5,
         23, 23,  6,  3, 37, 34,  3, 31,  6,  9,  7, 14, 38, 10, 22, 49, 10,  6,
          9, 12, 38,  6, 27], dtype=torch.int32),
 'preds_size': tensor([32, 32], dtype=torch.int32),
 'length_for_loss': tensor([ 9, 32], dtype=torch.int32)}
```
preds = dbg_info['preds']
flatten_targets = dbg_info['flatten_targets']
preds_size = dbg_info['preds_size']
length_for_loss = dbg_info['length_for_loss']
```
```
# The CPU version for this input seems to be working
criterion_seq_decoder(
    preds, flatten_targets, preds_size, length_for_loss
)
```
tensor([0.8019], grad_fn=<_CTCBackward>)
```
# Rerun Case 1b: all ones, GPU, to show that cuda is still working
preds = torch.ones([32, 2, 211]).cuda()
flatten_targets = torch.ones([41], dtype=torch.int32)
preds_size = torch.ones([32, 32], dtype=torch.int32)
length_for_loss = torch.ones([9, 32], dtype=torch.int32)
```
```
criterion_seq_decoder(
    preds, flatten_targets, preds_size, length_for_loss
)
```
tensor([10.7037])
```
# Case 2b, loading input that led to NaN loss on GPU
with open("dbg_ctc_th.pt", "rb") as buffer:
    dbg_info = torch.load(buffer)
```
```
dbg_info
```
{'preds': tensor([[[15.0986,  1.8929,  3.5891,  ..., -2.1942, -1.2969, -1.5835],
          [ 5.6930,  8.1056,  2.2196,  ..., -3.0562, -2.7510, -2.7415]],
         [[15.4319,  2.4563,  3.8988,  ..., -2.1413, -1.2563, -1.6718],
          [10.1033,  6.2490,  2.9085,  ..., -2.9902, -2.7306, -3.4103]],
         [[14.9405,  2.5963,  3.6762,  ..., -2.2741, -1.2802, -1.6602],
          [ 8.2425,  3.3113,  3.6833,  ..., -3.3457, -3.5685, -2.5054]],
         ...,
         [[10.4214,  2.3318,  2.2365,  ..., -1.7694, -1.7168, -1.9450],
          [ 6.6448,  6.7991,  2.8149,  ..., -1.9615, -2.0947, -1.8070]],
         [[19.0044,  3.0739,  4.6395,  ..., -2.3479, -1.7873, -2.0688],
          [ 6.4414,  6.7229,  4.4431,  ..., -2.0557, -2.6084, -2.1918]],
         [[17.1121,  4.2718,  4.2040,  ..., -2.1180, -1.9417, -1.7361],
          [ 6.9267,  7.2849,  5.9429,  ..., -1.9777, -2.6550, -2.5887]]],
        device='cuda:1', requires_grad=True),
 'flatten_targets': tensor([12, 38, 14, 18, 14, 29, 34,  6,  9, 16,  7, 28, 30,  2, 30, 38, 15,  5,
         23, 23,  6,  3, 37, 34,  3, 31,  6,  9,  7, 14, 38, 10, 22, 49, 10,  6,
          9, 12, 38,  6, 27], dtype=torch.int32),
 'preds_size': tensor([32, 32], dtype=torch.int32),
 'length_for_loss': tensor([ 9, 32], dtype=torch.int32)}
```
preds = dbg_info['preds']
flatten_targets = dbg_info['flatten_targets']
preds_size = dbg_info['preds_size']
length_for_loss = dbg_info['length_for_loss']
```
```
# The loss becomes 0 here, different from the CPU version!
criterion_seq_decoder(
    preds, flatten_targets, preds_size, length_for_loss
)
```
tensor([0.], grad_fn=<_CTCBackward>)
```
# Rerun Case 1b: all ones, GPU, to show that cuda stops working
preds = torch.ones([32, 2, 211]).cuda()
flatten_targets = torch.ones([41], dtype=torch.int32)
preds_size = torch.ones([32, 32], dtype=torch.int32)
length_for_loss = torch.ones([9, 32], dtype=torch.int32)
```
CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-3890331953ba> in <module>
      1 # Rerun Case 1b: all ones, GPU, to show that cuda stops working
----> 2 preds = torch.ones([32, 2, 211]).cuda()
      3 flatten_targets = torch.ones([41], dtype=torch.int32)
      4 preds_size = torch.ones([32, 32], dtype=torch.int32)
      5 length_for_loss = torch.ones([9, 32], dtype=torch.int32)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Here's the zip file containing the dbg_ctc_th.pt file used in the commands above for debugging:
[dbg_ctc_th.zip](https://github.com/pytorch/pytorch/files/6719258/dbg_ctc_th.zip)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by ngimel** [comment]
This looks like warpctc_pytorch issue, please file it on their github.
