### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 3, 128, 128]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by ParnaChowdhury** [pytorch/pytorch#60826]
## Issue description
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1, 3, 128, 128]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

This error is happening on running .backward() function

You can detect anomaly by using the above function, but here this tensor has to be removed/detached using .detach function for the error to go. This increases the training time and also as a tensor is detached from the computation graph, we don't know if backpropagation is happening correctly or not.

## Code example

![image](https://user-images.githubusercontent.com/69461088/123528031-0d6bb100-d702-11eb-8393-71eae9005964.png)

**Comment by jbschlosser** [comment]
Hey @ParnaChowdhury, this question looks like a better fit for the [PyTorch forums](https://discuss.pytorch.org/).
