### ISSUE TITLE
torch.sum(x, dim=()) inconsistent with documentation and numpy.sum(x, axis=())

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#60845]
## 🐛 Bug

According to the documentation of [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html)

> dim (int or tuple of python:ints) – the dimension or dimensions to reduce.

However, this is not true for `dim=()`, which causes torch to reduce **all** dimensions.

## To Reproduce

```python
import torch
a = torch.randn(3,4,5)
b = torch.sum(a, dim=())
assert a.shape == b.shape   # raises assertion error
```

## Expected behavior

When calling `torch.sum` with `dim=()` - which is a `tuple[int, ...]` -  no reduction should take place, i.e. the operation should collapse to an identity function. This is the default behaviour in `numpy` when specifying `axis=()`:

```python
import numpy
a = numpy.random.randn(3,4,5)
b = numpy.sum(a, axis=())
assert a.shape == b.shape   # passes
```
In `numpy`'s case, reduction over all axes is triggered by `axis=None`, the default value. However, calling `torch.sum` with `dim=None` only results in

```
RuntimeError: Please look up dimensions by name, got: name = None.
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - Python version: 3.9.5

cc @brianjo @mruberry @rgommers @heitorschueroff

**Comment by rgommers** [comment]
Thanks for the report @randolf-scholz. This is a known issue I believe which is complicated to fix, see gh-29137.

**Comment by randolf-scholz** [comment]
Oh OK, sorry for posting a duplicate.

**Comment by rgommers** [comment]
No worries at all!
