### ISSUE TITLE
Addition assignment with tensors "fails" when multiple values are to be added to one location

### ISSUE THREAD

**Issue by adityaradk** [pytorch/pytorch#60846]
Consider the following code snippet:

```python
a = torch.zeros((4, 6))
b = torch.tensor([1, 3, 5])
indices = [[0, 0, 1], [0, 0, 1]]
a[indices] += b
```

Here, we have values from a tensor `b` being added and assigned to specific indices in tensor `a`. Note that, in this case, two values (`1` and `3`) are being added and assigned to a single index in `a` (specifically `a[0, 0]`). As a result, `a` is now:

```python
tensor([[3., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
```

This behavior makes sense, given that the following assignment will yield the same result:

```python
a[indices] = b
```

However, for the purposes of addition assignment (`+=`), does it not make more sense for *both* values to be added to the same location instead of the last value overwriting it? In other words, shouldn't the resultant of `a[indices] += b` be:

```python
tensor([[4., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
```

In the above, both `b[0]` and `b[1]` are aggregately added to `a[0, 0]` instead of the latter overwriting the former.

I encountered this problem recently myself, and it was difficult to come up with even a somewhat reasonable workaround. Ideas included adding all the values in `b` that had the same target index in `a`, explicit looping, and more, but I finally settled with this approach with the help of Discord user Et#5175:

```python
c = torch.zeros((4, 6, 3))
c[[0, 0, 1], [0, 0, 1], torch.arange(3)] += b
a += c.sum(axis=2)
```

This approach still wastes memory and is slower than it has to be.

While I may not be aware of more complex reasons to not alter this behavior of the addition assignment operator, wouldn't a dedicated operation designed to efficiently handle scenarios like this be useful?

**Comment by jbschlosser** [comment]
Thanks for the suggestion, @adityaradk! Note that the current behavior in PyTorch matches that of numpy, so I don't think we'd want to change it:
```python
>>> import numpy as np
>>> a = np.zeros((4, 6))
>>> b = np.array([1, 3, 5])
>>> indices = [[0, 0, 1], [0, 0, 1]]
>>> a[indices] += b
>>> a
array([[3., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

Whether or not we want to support this through a dedicated operation / flag is a separate discussion. cc @mruberry

**Comment by mruberry** [comment]
We could better document what happens when multiple tensor indices are assigned to simultaneously, or how "overlapping" tensors with multiple indices referencing the same element work. I think currently the behavior is undefined but we don't explain this prominently.

**Comment by ngimel** [comment]
Closing, as behavior matches numpy. To perform this operation in one go, use `torch.index_put_` with `accum=True`
