### ISSUE TITLE
Typo in RuntimeError message

### ISSUE THREAD

**Issue by ArthurConmy** [pytorch/pytorch#60864]
## 📚 Documentation

See https://github.com/pytorch/pytorch/blob/20085f6d2364c4acf526f4eb303b8623207f0d48/aten/src/ATen/core/adaption.cpp#L10 : 'arugment' rather than argument.

cc @brianjo @mruberry

**Comment by mruberry** [comment]
cc @wenleix

**Comment by kit1980** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/61459
