### ISSUE TITLE
Why does multinomial distribution in pytorch not implement the entropy function?

### ISSUE THREAD

**Issue by rhelpacc** [pytorch/pytorch#60866]
### The call of entropy function on multinomail distribution raises an NotImplemented exception

I am wondering why the multinomial distribution entropy is not implemented. Is it to be expected or it cannot be implemented? A good scenario is for example my network in an RL algo produces N of k-class actions. I.e. probs argument is an Nxk tensor. Let's say that total_count is fixed. 

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by jbschlosser** [comment]
Thanks for the report! [Wikipedia](https://en.wikipedia.org/wiki/Multinomial_distribution) gives a formula for entropy of the multinomial distribution, so it appears possible to compute.

**Comment by rhelpacc** [comment]
Hi. I am aware of how to compute entropy on the multinomial distribution.But I am wondering if pytorch is going to have that implemented in the next coming release?

**Comment by fritzo** [comment]
@rhelpacc we welcome contributions 😄  It should be an easy few lines to implement `.entropy()`.

**Comment by devpramod** [comment]
@fritzo I'm familiar with multinomial distributions and vectorization, can I explore this?

**Comment by fritzo** [comment]
@devpramod absolutely! If you can implement the math, it should only be a few lines of change.

**Comment by devpramod** [comment]
@fritzo great! Do I need to be assigned this issue? or I just open a new PR?

**Comment by fritzo** [comment]
@devpramod Just open a PR and reference this issue in the pr description
