### ISSUE TITLE
Fail to build in mac os. 

### ISSUE THREAD

**Issue by zhengqinwen95** [pytorch/pytorch#60860]
## ❓ Questions and Help
I compile pytorch 1.8.1 from source code, follow tutorial step by step, but when I run MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install, I got error: 

![image](https://user-images.githubusercontent.com/82742349/123633318-a1955f80-d84b-11eb-8ac5-56e9af70b94c.png)

Could someone help me to solve it? 
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by jbschlosser** [comment]
Hey @zhengqinwen95, it looks like your installed version of protobuf is too old- have you tried updating it?

FYI a question like this is a better fit for the [PyTorch forums](https://discuss.pytorch.org/)- you are more likely to get assistance there.
