### ISSUE TITLE
__radd__ for torch.utils.data.Dataset

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#6087]
Existing `__add__` is not enough for usage as in:
```python
sum(dataset.get_subset(subset_name) for subset_name in ['train', 'val'])
# TypeError: unsupported operand type(s) for +: 'int' and 'Subset'`)
```
(In practice I want to pull subset names dynamically by splitting a string by underscore)

`__radd__` seems to [fix this](https://stackoverflow.com/questions/1218710/pythons-sum-and-non-integer-values)

**Comment by apaszke** [comment]
`__radd__` won't fix this at all. We never want to allow doing `0 + Dataset`, that makes no sense. `sum` takes an optional argument which is the initial value of the reduction. You can make that the first subset of your list.

Also, in your example you could just do `dataset.get_subset('train') + dataset.get_subset('val')`

**Comment by apaszke** [comment]
If you have a dynamically generated list then try this:
```python
dset_names = ...
sum(dataset.get_subset(name) for name in dset_names[1:], dataset.get_subset(dset_names[0]))
```

**Comment by vadimkantorov** [comment]
`reduce(torch.utils.data.dataset.Subset.__add__, dataset.get_subset(subset_name) for subset_name in ['train', 'val'])` also works. Thanks!
