### ISSUE TITLE
gradcheck and gradgradcheck are not well documented

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#6090]
Cannot find the docs on website

**Comment by SsnL** [comment]
well apparently gradgradcheck isn't exposed.

**Comment by albanD** [comment]
`gradcheck` is only mentionned in the extending section [here](https://pytorch.org/docs/stable/notes/extending.html#extending-torch-autograd).
And `gradgradcheck` is only exposed via `torch.autograd.gradcheck.gradgradcheck`.
