### ISSUE TITLE
py:class reference target not found: torch.utils.data.dataset.Dataset

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#60979]
## 📚 Documentation

I have a project that uses PyTorch. When creating my own documentation, I'm using [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) to automatically link to the PyTorch documentation like so:
```python
intersphinx_mapping = {                                                                  
    "python": ("https://docs.python.org/3", None),                                       
    "torch": ("https://pytorch.org/docs/stable", None),                                  
}  
```
When I build my project documentation with nitpick mode enabled, sphinx warns that it can't find certain class definitions:
```
foo.py:docstring of foo.Foo:1: WARNING: py:class reference target not found: torch.utils.data.dataset.Dataset
foo.py:docstring of foo.Bar:1: WARNING: py:class reference target not found: torch.nn.modules.module.Module
```
This usually implies that there is something wrong with the `objects.inv` file available at https://pytorch.org/docs/stable/objects.inv

I could create my own `objects.inv` for local use, but it would quickly become out-of-date. Any idea how we can fix this in master?

**Comment by mruberry** [comment]
Any ideas, @brianjo?

**Comment by brianjo** [comment]
Could be the version of PyTorch we're built with? I'll check it tomorrow when I get a chance. Thanks!

**Comment by adamjstewart** [comment]
I'm guessing this is related to import aliases, I opened a StackOverflow question for a very similar issue I was seeing in torchvision: https://stackoverflow.com/questions/68186141/how-to-handle-class-import-aliases-in-sphinx-autodoc

**Comment by ydcjeff** [comment]
A workaround would be to use `torch.utils.data.Dataset`, not `torch.utils.data.dataset.Dataset`.

**Comment by adamjstewart** [comment]
I am using `torch.utils.data.Dataset`, the problem is that Sphinx resolves this to the full path but then can't find the API docs for the full path.

**Comment by adamjstewart** [comment]
Found a solution in https://stackoverflow.com/questions/40018681, if you want I can submit a PR to set the `__module__` attribute of `Dataset` and `Module`. Not sure what other classes this might affect.

**Comment by ydcjeff** [comment]
@adamjstewart As a reference, here are [some classes that intersphinx resolves to full module path which does not exist in the pytorch docs](https://github.com/pytorch/ignite/blob/4ace16206c22fc98b8578f71f840c6bad901382f/docs/source/conf.py#L333-L339).

**Comment by adamjstewart** [comment]
Perfect, I'll add those to my PR
