### ISSUE TITLE
Distributed training over multiple node with file initialisation

### ISSUE THREAD

**Issue by Jeffery4000** [pytorch/pytorch#6099]
Hi, I am trying to launch a distribute training over two node with the example of imaganet.
The share drive are able to access by both node and ssh-key-pair is created.

Share folder path: /home/test_share/

Launching job by command below:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --a resnet50 -j 15 --epochs 1 -b 100 /home/imagenet_2012 --dist-url file:///home/test_share/ --world-size 2`

But it given an error showing below, i assume that it was not able to access the folder but why??:
```
Traceback (most recent call last):
  File "main.py", line 315, in <module>
    main()
  File "main.py", line 70, in main
    world_size=args.world_size)
  File "/usr/local/lib/python2.7/dist-packages/torch/distributed/__init__.py", line 49, in init_process_group
    group_name, rank)
RuntimeError: cannot access '/home/test_share' file: Unknown error -1 at /pytorch/torch/lib/THD/process_group/General.cpp:17
```

When I try using tcp initialisation, it just hang at:
`creating model 'resnet50'`

**Comment by Jeffery4000** [comment]
this the new error I am getting with tcp initialisation
```
=> creating model 'resnet50'
Traceback (most recent call last):
  File "main.py", line 315, in <module>
    main()
  File "main.py", line 88, in main
    model = torch.nn.parallel.DistributedDataParallel(model)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 128, in __init__
    self.broadcast_bucket_size)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 245, in _dist_broadcast_coalesced
    dist.broadcast(flat_tensors, 0)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 277, in broadcast
    return torch._C._dist_broadcast(tensor, src, group)
RuntimeError: [enforce fail at /root/pytorch/torch/lib/gloo/gloo/transport/ibverbs/buffer.cc:57] mr_ != nullptr. ibv_reg_mr: Cannot allocate memory (did you run into the locked memory limit?)

```

**Comment by apaszke** [comment]
Are you sure that `/home/test_share` is writeable by you? `/home` is usually writeable only by the super user. Try something like `/home/<your username>/test_share`, or the multicast initialization

**Comment by Jeffery4000** [comment]
Hi @apaszke, Im sure the directory is writeable for me since Im using a root user on both node. With multicast initialization, I'm getting the error showing above which I believe that it can't allocate memory to GPU but doesn't know why. 

When there was handshake between two node, both node start creating resnet50 model and allocate the model to the GPU memory. After 300~400 MiB being fetch to GPUs, it prompt the error message above and I'm sure the batch size i set is not too large for a 12GB GPUs.

**Comment by Jeffery4000** [comment]
Hi @apaszke , i try to recompile from source with and it shows the following error:

`WITH_GLOO_IBVERBS=1 WITH_DISTRIBUTED=1 WITH_CUDNN=1 WITH_CUDA=1 WITH_NCCL=1 CUDA_HOME=/usr/local/cuda-8.0/ python setup.py install`

```
running build_ext
-- Building with NumPy bindings
-- Detected cuDNN at /usr/lib/x86_64-linux-gnu/libcudnn.so.6, /usr/include/
-- Detected CUDA at /usr/local/cuda-8.0/
-- Using system provided NCCL library at /usr/lib/x86_64-linux-gnu/libnccl.so.2.1.2, /usr/include
-- Building with distributed package 
/root/pytorch/torch/_thnn/utils.py:1: RuntimeWarning: Parent module 'torch._thnn' not found while handling absolute import
  import os
/root/pytorch/torch/_thnn/utils.py:2: RuntimeWarning: Parent module 'torch._thnn' not found while handling absolute import
  import itertools
/root/pytorch/torch/_thnn/utils.py:3: RuntimeWarning: Parent module 'torch._thnn' not found while handling absolute import
  import importlib
Skipped writing torch/csrc/nn/THNN.cpp
Skipped writing torch/csrc/nn/THCUNN.cpp
Skipped writing torch/csrc/autograd/generated/VariableType.h
Skipped writing torch/csrc/autograd/generated/VariableType.cpp
Skipped writing torch/csrc/autograd/generated/Functions.h
Skipped writing torch/csrc/autograd/generated/Functions.cpp
Skipped writing torch/csrc/autograd/generated/python_functions.h
Skipped writing torch/csrc/autograd/generated/python_functions.cpp
Skipped writing torch/csrc/autograd/generated/python_variable_methods.cpp
Skipped writing torch/csrc/autograd/generated/python_variable_methods_dispatch.h
Skipped writing torch/csrc/autograd/generated/python_torch_functions.cpp
Skipped writing torch/csrc/autograd/generated/python_torch_functions_dispatch.h
Skipped writing torch/csrc/autograd/generated/python_nn_functions.cpp
Skipped writing torch/csrc/autograd/generated/python_nn_functions.h
Skipped writing torch/csrc/autograd/generated/python_nn_functions_dispatch.h
Skipped writing torch/csrc/jit/generated/aten_dispatch.h
Skipped writing torch/csrc/jit/generated/aten_dispatch.cpp
Skipped writing torch/csrc/jit/generated/aten_interned_strings.h
```

**Comment by apaszke** [comment]
It's a warning, not an error. You can ignore them.

**Comment by ailzhang** [comment]
@Jeffery4000 A quick question, have you tried using gloo but without ibverbs? What does that say?

**Comment by ailzhang** [comment]
And what's the output of your `ulimit -l`?

**Comment by ailzhang** [comment]
Hi @Jeffery4000 , if you have a Mellanox card, please give this a try to increase your registered memory size and let us know if that works. https://community.mellanox.com/docs/DOC-1120

**Comment by Jeffery4000** [comment]
Hi @ailzhang , thanks for your reply. Output of my `ulimit -l` is 64. May i know how do I run goo without ibverbs, I'm new to this.

**Comment by ailzhang** [comment]
You can rebuild with WITH_GLOO_IBVERBS=0, that will allow you to use Gloo with Ethernet link.
Also could you let us know what's the output of 'ibstat'?

**Comment by Jeffery4000** [comment]
Will try again tonight. 

Output of 'instate':

```
CA 'mlx4_0'
	CA type: MT4099
	Number of ports: 2
	Firmware version: 2.42.5000
	Hardware version: 0
	Node GUID: 0xe41d2d0300790b80
	System image GUID: 0xe41d2d0300790b83
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 56
		Base lid: 2
		LMC: 0
		SM lid: 1
		Capability mask: 0x02594868
		Port GUID: 0xe41d2d0300790b81
		Link layer: InfiniBand
	Port 2:
		State: Down
		Physical state: Polling
		Rate: 10
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x02594868
		Port GUID: 0xe41d2d0300790b82
		Link layer: InfiniBand
CA 'mlx4_1'
	CA type: MT4099
	Number of ports: 1
	Firmware version: 2.42.5000
	Hardware version: 0
	Node GUID: 0x248a070300bf0580
	System image GUID: 0x248a070300bf0580
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 10
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x04010000
		Port GUID: 0x268a07fffebf0580
		Link layer: Ethernet
CA 'mlx4_2'
	CA type: MT4099
	Number of ports: 2
	Firmware version: 2.42.5000
	Hardware version: 0
	Node GUID: 0xe41d2d0300790be0
	System image GUID: 0xe41d2d0300790be3
	Port 1:
		State: Active
		Physical state: LinkUp
		Rate: 56
		Base lid: 3
		LMC: 0
		SM lid: 1
		Capability mask: 0x02594868
		Port GUID: 0xe41d2d0300790be1
		Link layer: InfiniBand
	Port 2:
		State: Down
		Physical state: Polling
		Rate: 10
		Base lid: 0
		LMC: 0
		SM lid: 0
		Capability mask: 0x02594868
		Port GUID: 0xe41d2d0300790be2
		Link layer: InfiniBand
```

**Comment by ailzhang** [comment]
@Jeffery4000 Yea looks like you have the mlx4 driver, the link in my comment should work for you. Could you also check the parameters in the setting(path is shown in the link)? Increasing that number might help in your case.

**Comment by Jeffery4000** [comment]
@ailzhang When I try to follow the steps on the link you provided, there was no file call log_num_mtt, while log_mtts_per_seg shows '3'.

recompile with WITH_GLOO_IBVERBS=0 works, will update again once the benchmark is done. But still hope it can work on IB to see whether there are any bottleneck issue on ethernet.

**Comment by ailzhang** [comment]
Hi @Jeffery4000 , it's possible that the IB register memory is not setup correctly in your system.
If you would like more support on this, we need to know
- os system version
- physical RAM
- all parameters inside the /sys/module/mlx4_core/ folder.
Mlx4 allows users to customize the register memory based on their need, so it's likely that's too small in your system. Since we don't have access to your environment, it's good to consult your system admin to change the register memory setting for IB.

**Comment by ailzhang** [comment]
Also @Jeffery4000 could you check if there's anything related to this in dmesg?

**Comment by ailzhang** [comment]
@Jeffery4000 Also according to the code here, you are hitting locked memory limit. Good to set your ulimit -l to unlimited (that's also what we have in our environment) and retry. https://access.redhat.com/solutions/61334

**Comment by soumith** [comment]
closed via @ailzhang 's comment https://github.com/pytorch/pytorch/issues/6099#issuecomment-378320569 as a system configuration issue
