### ISSUE TITLE
RuntimeError: s_iter != stack.end() INTERNAL ASSERT FAILED at "..\\torch\\csrc\\jit\\python\\script_init.cpp":448, please report a bug to PyTorch.

### ISSUE THREAD

**Issue by lonngxiang** [pytorch/pytorch#61033]
## To Reproduce

run ：torch.onnx.export(model,text1, "111.onnx")

cc @BowenBao @neginraoof

**Comment by gmagogsfm** [comment]
Hi lonngxiang,

Could you provide content of `model` and `text1` so that this issue can be looked at? Thanks!
