### ISSUE TITLE
RuntimeError: Expected tensor's dynamic type to be Variable, not Tensor

### ISSUE THREAD

**Issue by back2yes** [pytorch/pytorch#6103]
I am writing an cpp extension, where I need to create a new variable within the cpp function.

This is my code here:
```
#include <torch/torch.h>
#include <vector>
using namespace at;
Tensor foo()
{
    Tensor a = ones(CPU(kFloat), {3, 4});
    return a;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m)
{
    m.def("foo", &foo, "foo");
}
```

However it does not work as I expected, but raise a Runtime error:
```
RuntimeError: Expected tensor's dynamic type to be Variable, not Tensor
```

I guess the problem is I with my code, rather than the framework. Could anyone help me with this? Thanks in advance.

**Comment by apaszke** [comment]
@goldsborough do we have a way to create Variables out of Tensors in C++, or do we only allow using the `torch::` constructors (we don't have `ones` there I think)?

**Comment by goldsborough** [comment]
There's an example of using `ones` right here https://github.com/pytorch/pytorch/blob/master/test/cpp_extensions/extension.cpp#L9

You want `at::ones(torch::CPU(at::kFloat), {3, 4});`

**Comment by goldsborough** [comment]
@apaszke let's create a `cpp-extensions` label on GitHub then I can watch our for issues with that label

**Comment by apaszke** [comment]
Here you go!

**Comment by back2yes** [comment]
@apaszke @goldsborough 
Thanks a lot, totally solved it!

**Comment by varunagrawal** [comment]
Note that this should now be `at::ones(at::CPU(at::kFloat), {3, 4});`

@goldsborough @apaszke we really need ATen docs and stability. :slightly_smiling_face:

**Comment by andyljones** [comment]
If you're using PyTorch for some unusual purpose and you think you do actually want Tensors flying around rather than Variables, you can hold off the conversion until immediately before returning the Tensor through PyBind, using
```cpp
#include <torch/csrc/autograd/variable.h>
// 
// ...
//
return torch::autograd::make_variable(t);
```
to make the conversion.

(My use case is that nvcc compiles my kernels much faster if they only include ATen.h rather than the torch headers)
