### ISSUE TITLE
Torchvision binary wheel building is broken

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch#61036]
Looks like https://github.com/pytorch/pytorch/pull/59665 broke some of torchvision's jobs which are now failling with

```
  File "/opt/python/cp36-cp36m/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 776, in _check_cuda_version
    if cuda_ver.major != torch_cuda_version.major:  # type: ignore[attr-defined]
AttributeError: 'Version' object has no attribute 'major'
```

see e.g.: https://app.circleci.com/pipelines/github/pytorch/vision/9349/workflows/769175ff-6f3b-4298-b6ab-e85d44cc54be/jobs/686628

CC @andfoy 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @yf225 @glaringlee @fmassa @vfdev-5 @pmeier

**Comment by rgommers** [comment]
Too old `setuptools` version, the `.major` attribute came in in `49.6.0` (says https://github.com/spyder-ide/spyder/pull/15886).

@andfoy that seems too recent to require, and distros may not have it. I think you need to change that in a way so it works with any `setuptools` version.

FYI @ezyang who landed this - it's going to break elsewhere too.

**Comment by andfoy** [comment]
I think I'll resort to doing manual parsing here, thanks for the explanation @rgommers
