### ISSUE TITLE
Allow torch.testing.assert_close to compare None to None

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch#61035]
## 🚀 Feature

The new `torch.testing.assert_close` does not allow None to None comparison. It'd be cool if it did :)

For ref, this passes:
```py
np.testing.assert_array_equal(None, None)
```

A sensible behavior IMHO would be that `assert_close(None, x)` passes **if and only if** `x is None`. (numpy will allow `x` to be e.g. an empty list, but I'm not sure pytorch should follow this)

## Motivation

Some of torchvision models output tuples, for example `googlenet` outputs

```py
GoogLeNetOutputs = namedtuple('GoogLeNetOutputs', ['logits', 'aux_logits2', 'aux_logits1'])
```

Depending on the constructor parameters, the output `aux_logits` can be None.

The fact that  `torch.testing.assert_close` doesn't allow None comparison makes it impossible for us to use it directly on the models output.

## Alternatives

Currently, we workaround this in our [tests](https://github.com/pytorch/vision/blob/master/test/test_models.py#L109-L116) with:

```py
        try:
            torch.testing.assert_close(results, results_from_imported, atol=tol, rtol=tol)
        except torch.testing._asserts.UsageError:
            # custom check for the models that return named tuples:
            # we compare field by field while ignoring None as assert_close can't handle None
            for a, b in zip(results, results_from_imported):
                if a is not None:
                    torch.testing.assert_close(a, b, atol=tol, rtol=tol)
```

CC @pmeier @mruberry :)

**Comment by mruberry** [comment]
Thanks for the suggestion @NicolasHug! Allowing None to be close to None (and nothing else) seems OK to me. @pmeier?

I suppose we should fail if someone tries to convert None to a tensor, however, or compare it with anything but another None.

**Comment by pmeier** [comment]
> I suppose we should fail if someone tries to convert None to a tensor, however, or compare it with anything but another None.

Agreed. We need to make `None` vs. `None` a special case. It will make the implementation a little awkward, because right now the implementation assumes everything is a tensor after the input parsing and builds everything after it on that assumption.

My first thought was to convert `None` to `torch.tensor(torch.nan)` since `None` is "not a number". This has the advantage (or disadvantage depending on perspective) of being able to allow / disallow these comparisons with the `equal_nan` kwarg. On the other hand that would also allow stuff like `assert_close(None, float("NaN"), equal_nan=True)` which could be quite confusing. Note that such a comparison would only be able for scalars, since it is impossible to have a tensor with `None` in it.

`numpy` converts None to an `object` `dtype`, which are not supported by their test infrastructure:

```python
>>> a = numpy.array(None)
>>> a
array(None, dtype=object)
>>> numpy.testing.assert_allclose(a, a)
...
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Thoughts?

**Comment by NicolasHug** [comment]
I feel like mixing the semantics of None with those of NaN could be confusing and unexpected. If None is supported via NaN, in our testing code mentioned above we would have to use

```py
assert_close(model_output, expected_model_output, equal_nan=True)
```

when in reality a) there are no NaNs in the results, but the code suggests there are, and b) should there be NaNs, we would definitely want an error in this case, but it would not be raised.

> It will make the implementation a little awkward, because right now the implementation assumes everything is a tensor after the input parsing and builds everything after it on that assumption

That's a fair point, IMHO it's perfectly reasonable to not implement something if it's going to make the code look like spaghetti

**Comment by pmeier** [comment]
> b) should there be NaNs, we would definitely want an error in this case, but it would not be raised.

`assert_close` would only raise an error in case there is a mismatching `NaN` somewhere. So if you can guarantee that there is no NaN in `expected_model_output`, `assert_close(model_output, expected_model_output, equal_nan=True)
` will still raise if `model_output` contains NaN's.

But I get your point.

**Comment by mruberry** [comment]
Sounds like we all agree that None should not be interpreted opportunistically as NaN.
