### ISSUE TITLE
Unify tensor quantization algorithm for x86 and arm

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#61047]
Namely, to prevent overflows, zero_point should be added before value is cast to integral or as following comment suggests even before it is rounded
https://github.com/pytorch/pytorch/blob/0b8a7daa2a7e765270b85234b868b5897a9822bb/aten/src/ATen/native/quantized/cpu/kernels/QuantizedOpKernels.cpp#L2469

But quantize_tensor_arm and quantize_val_arm are adding it after value was scaled, rounded and cast to integral type, see below:
https://github.com/pytorch/pytorch/blob/0b8a7daa2a7e765270b85234b868b5897a9822bb/aten/src/ATen/native/quantized/affine_quantizer_base.cpp#L124
vs
https://github.com/pytorch/pytorch/blob/0b8a7daa2a7e765270b85234b868b5897a9822bb/aten/src/ATen/native/quantized/affine_quantizer_base.cpp#L111

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by malfet** [comment]
@vkuzo not sure, why you've closed the issue, as inconsistency still exists in codebase, especially in vectorized variants of vector quantization.

**Comment by supriyar** [comment]
old issue, not sure if it is still relevant but adding the mobile team for more context on the quantization formula for ARM
