### ISSUE TITLE
ConcatDataset cannot work with DataLoader properly

### ISSUE THREAD

**Issue by SilenceX12138** [pytorch/pytorch#61089]
## 🐛 Bug

When concatenating two different types of datasets and loading the combination again, the dataloader cannot be iterated properly.

## To Reproduce

The reproduction can be done below.

```python
import torch
from PIL import Image
from torch.utils.data import ConcatDataset, TensorDataset
from torchvision.datasets import DatasetFolder
from torchvision.transforms import transforms
from tqdm.auto import tqdm
from torch.utils.data import DataLoader

train_tfm = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(
        (0.1307, ),
        (0.3081, )),  # normalize should be executed after ToTensor()
])


def load_img(x):
    return Image.open(x)


label_set = DatasetFolder("./data/training/labeled",
                          loader=load_img,
                          extensions="jpg",
                          transform=train_tfm)

test_img = torch.ones(1000, 3, 128, 128)
test_label = torch.ones(1000)
test_set = TensorDataset(test_img, test_label)

concat_set = ConcatDataset([label_set, test_set])

train_loader = DataLoader(concat_set, batch_size=128, shuffle=True)
for batch in train_loader:
    img, label = batch
    print(label.shape)

```

1. The dataset is too big to be uploaded, so I'd put a directory tree here.
![image](https://user-images.githubusercontent.com/47887520/124050295-dde3de00-da4c-11eb-8e8e-d4ac9613985e.png)
2. run the code and the error will appear like below.
```shell
Traceback (most recent call last):
  File "xxx\Desktop\test\3-semi-supervised\test.py", line 34, in <module>    for batch in train_loader:
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\_utils\collate.py", line 86, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\_utils\collate.py", line 86, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "xxx\Python\Python38\lib\site-packages\torch\utils\data\_utils\collate.py", line 58, in default_collate
    return torch.stack(batch, 0, out=out)
TypeError: expected Tensor as element 1 in argument 0, but got int
```
3. After some investigation, I found the problem may be concered with the way different datasets are split into batches, so I add this line in `xxx\Python\Python38\lib\site-packages\torch\utils\data\_utils\collate.py` function `default_collate` like below. **It can work properly on my PC then, but as for other platforms like CoLab, em...**

```python
if isinstance(elem, torch.Tensor):
        out = None
        if torch.utils.data.get_worker_info() is not None:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum([x.numel() for x in batch])
            storage = elem.storage()._new_shared(numel)
            out = elem.new(storage)
        # ADD THIS LINE BELOW
        batch = [torch.tensor(data).long() if type(data) is not torch.Tensor else data.long() for data in batch]            
        return torch.stack(batch, 0, out=out)
```

## Expected behavior

Error message is listed above.

## Environment

PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0      
Clang version: 10.0.0
CMake version: version 3.19.0-rc3
Libc version: N/A

Python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: GPU 0: GeForce MX250
Nvidia driver version: 451.67
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.7.post0
[pip3] torch==1.7.1+cu110
[pip3] torchaudio==0.7.2
[pip3] torchmetrics==0.3.2
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.2+cu110
[conda] Could not collect

**Comment by ejguan** [comment]
Hey @SilenceX12138,

IIUC, the type of your `label_set` (integer as label) and `test_set` (tensor as label) are different. Then, it's not possible to concat them together as a tensor.
You can either use your own `collate_fn` as the argument of DataLoader, or write custom `TestDataset` to return image and label with the corresponding type of `DatasetFolder`. Your use case is too specific to be included into `default_collate_fn`.
I am closing the issue, as you have already had a solution. Feel free to reopen it if needed. And, feel free to discuss use case in PyTorch Forum (https://discuss.pytorch.org/). Thank you.
