### ISSUE TITLE
ERROR: torch.nn.functional.binary_cross_entropy and torch.nn.BCELoss are unsafe to autocast. 

### ISSUE THREAD

**Issue by johnson-magic** [pytorch/pytorch#61098]
when amp is used, it reports this issue "ERROR: torch.nn.functional.binary_cross_entropy and torch.nn.BCELoss are unsafe to autocast. ", why ?

**Comment by VitalyFedyunin** [comment]
Hello! 

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
