### ISSUE TITLE
backward propagation of conv2d

### ISSUE THREAD

**Issue by xjhcassy** [pytorch/pytorch#61100]
## ❓ Questions and Help

In the C++ implementation of SpatialConvolutionMM.cu, in function THNN_(SpatialConvolutionMM_updateGradInput), it just use the transpose of weight matrix to compute, not doing rotating 180°, or I just didn't find the place. Please answer me about the questions. Thank you very much.

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
