### ISSUE TITLE
Warning for torch.log(<tensor with at least one negative value>)

### ISSUE THREAD

**Issue by patel-zeel** [pytorch/pytorch#61118]
## 🚀 Feature

It would be a developer-friendly feature to add a warning when log encounters negative values.

## Motivation

I spent the last 3 hours figuring out why I am getting NaN values. This could have been the case for more people too.

## Pitch

```
>>> torch.log(torch.tensor(-1))
RunTimeWarning: negative value encountered in log
tensor(nan)
```
## Alternatives

I won't mind if an error is thrown instead of a warning.

**Comment by VitalyFedyunin** [comment]
This additional input check will impact performance, need to decide if we want to implement it.

**Comment by soulitzer** [comment]
Closing because this wouldn't be performant. Though there are some cases where we do check.
@vitaly-fedyunin : should there be a debug mode feature?
