### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [pytorch/pytorch#61128]
Hey there,

As there isn't a `SECURITY.md` with an email on your repository, I am unsure how to contact you regarding a potential security issue.

Would you kindly add a `SECURITY.md` file with an e-mail to your repository? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this as the best way to ensure security issues are responsibly disclosed, and it would massively help security researchers get in touch next time.

Thank you so much and I look forward to hearing from you!

**Comment by VitalyFedyunin** [comment]
CC @soumith @gchanan

**Comment by gchanan** [comment]
@jspisak

**Comment by jspisak** [comment]
thanks @zidingz - i'd be happy to put up a PR to get this addressed. Appreciate you bringing this to our attention..

**Comment by zidingz** [comment]
Thanks everyone!

**Comment by gchanan** [comment]
There is now https://github.com/pytorch/pytorch/blob/master/SECURITY.md, closing as completed.
