### ISSUE TITLE
[Bug] TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sainatarajan** [pytorch/pytorch#61125]
## 🐛 Bug

Unable to perform torchvision transform on an image.

## To Reproduce

```python
import torch
import torchvision.transforms as T

from PIL import Image

transforms = T.Compose([
    T.Resize(size=224),
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

img = Image.open(path_to_image).convert('RGB')
data = transforms(img)
```

## Expected behavior

The code should have successfully run and the image should've been transformed.

## Environment

```
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3060
Nvidia driver version: 460.84
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.9.0+cu111
[pip3] torch-geometric==1.7.2
[pip3] torch-scatter==2.0.7
[pip3] torch-sparse==0.6.10
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-geometric           1.7.2                    pypi_0    pypi
[conda] torch-scatter             2.0.7                    pypi_0    pypi
[conda] torch-sparse              0.6.10                   pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```

## Additional context

Stack trace:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    data = transforms(img)
  File "/home/snatarajan/anaconda3/envs/dl3d/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/home/snatarajan/anaconda3/envs/dl3d/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 97, in __call__
    return F.to_tensor(pic)
  File "/home/snatarajan/anaconda3/envs/dl3d/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 129, in to_tensor
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True)
TypeError: __array__() takes 1 positional argument but 2 were given
```

cc @fmassa @vfdev-5 @pmeier

**Comment by artemisart** [comment]
We have the same issue on numpy 1.20 and 1.21, had to downgrade to torch 1.8.1 torchvision 0.9.1

**Comment by xwang233** [comment]
Interesting, I also started seeing this error since last night.

**Comment by xwang233** [comment]
I did some debug. I think the problem comes from pypi Pillow 8.2.0 -> 8.3.0 update from June 30, 2021. Downgrading with

```
pip install pillow==8.2.0
```

may resolve the issue.

cc @ptrblck

**Comment by ptrblck** [comment]
@t-vi has a pending fix for this issue: https://github.com/python-pillow/Pillow/pull/5572

**Comment by plaban1981** [comment]
Requirement already satisfied: pillow==8.2.0 in /usr/local/lib/python3.7/dist-packages (8.2.0), Have already the same version , but still encounter the same error

**Comment by t-vi** [comment]
@plaban1981 Pillow 8.2 doesn't define `__array__`, so it is very improbable that you have the error with that version. I would advise `print(PIL.Image)` and compare the path there with your installation.
One thing to look out for is having multiple versions of pillow on the search path, a typical thing to shoot yourself in the foot with is 1) `pip install pillow` 2) `sudo pip install pillow==8.2.0`. This will give you pillow 8.2 for root and all users except the one where you did 1) and the most recent version for that user.

**Comment by plaban1981** [comment]
Hi @t-vi 

sudo pip install pillow==8.2.0 worked
Thanks,

**Comment by deutschmn** [comment]
Seems to be fixed with pillow release [8.3.1](https://github.com/python-pillow/Pillow/releases/tag/8.3.1) that merged PR [#5572](https://github.com/python-pillow/Pillow/pull/5572) 🎉

**Comment by artemisart** [comment]
Yes this can be closed

**Comment by vfdev-5** [comment]
Let's close it. Feel free to reopen if needed
