### ISSUE TITLE
Sequential inference of multiple models in a memory limited deployment environment

### ISSUE THREAD

**Issue by veritas9872** [pytorch/pytorch#61202]
## 🚀 Feature

Please refer to the forum link below for my initial question. 
https://discuss.pytorch.org/t/sequential-inference-of-multiple-models-in-a-memory-limited-environment/125517

I would like to request a feature to allow multiple models to be used on the same data while only using the minimum amount of memory necessary for running each model without having to load all the models to CPU and GPU memory. This feature is important for deployment and I believe that TorchScript should have this feature.

## Motivation

In deployment situations, we sometimes find it necessary to apply multiple models on the same data. The first model might be a style transfer network for converting the scene to a reference style, the second may be a detection network for vehicles within the style-transferred image, and the third network may be a classification network for an ROI extracted by the detection network. While the example given above is fictitious, *the problem of applying multiple models to the same data occurs frequently in deployment*.

However, if the size of each model is large and there are many models, it becomes impossible to load all the necessary models in memory. Assuming that each model has 1GB of parameters and that there are 20 separate models, it becomes necessary to load 20GB to RAM, which may be larger than the allocated hardware can manage.

Currently, Tensorflow graph mode manages the necessary memory automatically so that only the minimum necessary host and device memory are allocated during inference. This means that even if 20 models are being used, only the necessary models are actually loaded from disk to memory in RAM and GPU. Also, the next necessary model is loaded from disk to GPU while the previous model is still performing calculations on GPU, which removes latency,

It is possible to do this in Python as well by manually scheduling the process. However, loading the next model and transferring to GPU while the current model is executing in Python may be inefficient since the GPU calculations may be finished before the next model is sent to GPU. Using multi-threading is impossible due to the GIL and using multi-processing is error-prone.

Another alternative would be to merge the models to perform multi-task prediction and use techniques such as knowledge distillation to reduce model size. However, having separate models often has higher performance and provides modularity in execution. Also, even if smaller models are created, having to make space for all models is problematic.

## Pitch

Currently, TorchScript is focused on deploying a single model on a stream of data. However, I believe that many deployment scenarios involve applying multiple models on any single input, which is why I request this feature. I am aware that this would take much effort to implement. Also, I do not think that this feature is necessary for dynamic execution. 

## Alternatives

Using the C++ API?

cc @gmagogsfm

**Comment by nikithamalgifb** [comment]
@gmagogsfm , @suo : Do you guys have inputs on this feature request?

**Comment by veritas9872** [comment]
@nikithamalgifb @gmagogsfm @suo To be more precise, I would like to request the "peak memory use" optimization already available in Tensorflow https://www.tensorflow.org/guide/graph_optimization in TorchScript for both GPU memory and RAM memory.
This would be an invaluable addition for deployment with PyTorch.

**Comment by veritas9872** [comment]
After some thought, I have concluded that it is probably best to rely on the swap memory provided by the operating system than using a custom solution. I hope this works out for other users as well.
