### ISSUE TITLE
MISCONFIGURED JENKINS INSTANCES

### ISSUE THREAD

**Issue by vitor419** [pytorch/pytorch#61209]
## 🐛 Bug

It looks like an instance of jenkins is running on server 35.172.185.2, and anyone can log into it using their github account, I was able to access it with my github account.
(If this is the expected result, then I'm sorry).
## To Reproduce

1. Go 35.172.185.2/jenkins/ or ci.pytorch.org/jenkins/
1. Login with Github

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
This is expected, only users with specific permissions will actually be able to do anything on this server.
