### ISSUE TITLE
Document torch.Size and its methods (like torch.Size.numel)

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#61231]
## 📚 Documentation

I see `torch.Size` and `torch.Size.numel` are undocumented. This issue is a request to document them, since I have a situation where I only have `tensor.Size` and I'm not sure if I can reliably use `shape.numel()`, hence the uncertainly.

Thank you!

cc @brianjo @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue (and so many other great issues, @stas00). It'd be great to update the docs to clarify this behavior and we would accept a PR fixing this.

**Comment by stas00** [comment]
So would it be the correct solution to add to https://pytorch.org/docs/stable/generated/torch.numel.html that it also accepts `torch.Size` as a valid input type?

**Comment by mruberry** [comment]
> So would it be the correct solution to add to https://pytorch.org/docs/stable/generated/torch.numel.html that it also accepts `torch.Size` as a valid input type?

I think so, yes.

**Comment by stas00** [comment]
Thank you for validating that, @mruberry. Here is the PR: https://github.com/pytorch/pytorch/pull/61714

**Comment by mruberry** [comment]
I was mistaken about this and misinformed @stas00 on what approach we should take to resolve this issue. I have since updated the issue summary to more clearly reflect what @stas00 and I thought would be the correct approach.
