### ISSUE TITLE
Help, nn.functional.interpolate make no sense at image resizing

### ISSUE THREAD

**Issue by SungmanHong** [pytorch/pytorch#61247]
## ❓ Questions and Help

Hi, I have image that is represented as torch tensor named frame
that have dimension of **1(batch) x 3(RGB) x 540(height) x 960(width).**

and I just resized the tensor as

`frame = F.interpolate(frame), size=(540, 960), mode='bilinear', align_corners=True)`

Actually, the size is not CHANGED, but the result that is saved by PNG format is very weird...

Here is my orgin image of tensor :
[https://i.imgur.com/RW7UHWs_d.webp?maxwidth=760&fidelity=grand](url)

Here is my interpolated image of tensor :
[https://i.imgur.com/frozsKp_d.webp?maxwidth=760&fidelity=grand](url)

I saved tensor as image as follows.
```

from torchvision.utils import save_image
save_image(frame, 'debug.png')
```

How can I resize the video tensor normally?
Thanks.

**Comment by malfet** [comment]
I suspect you want to use https://pytorch.org/vision/stable/transforms.html#torchvision.transforms.Resize to resize images.
And please use https://discuss.pytorch.org/ to ask questions about PyTorch APIs
Do not hesitate to open a new issue if you believe that torch.nn.functional.interpolate does not  work as documented.
