### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DoubleTensorBase'

### ISSUE THREAD

**Issue by lcctju** [pytorch/pytorch#6125]
- OS: Ubuntu 16.04
- PyTorch version: torch-0.4.0a0+60a16e5
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- CUDA/cuDNN version: 8.0
- GPU models and configuration: GeForce GTX 1080 Ti
- GCC version (if compiling from source): 5.4.0

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import models
  File "/home/lcc/rnncode/deephawkes/mydeephawkes/models/__init__.py", line 3, in <module>
    from .BasicModule import BasicModule
  File "/home/lcc/rnncode/deephawkes/mydeephawkes/models/BasicModule.py", line 3, in <module>
    import torch
  File "/home/lcc/anaconda2/lib/python2.7/site-packages/torch/__init__.py", line 158, in <module>
    class DoubleTensor(_C.DoubleTensorBase, _TensorBase):
AttributeError: 'module' object has no attribute 'DoubleTensorBase'

codes：
# -*- coding: utf-8 -*-

import torch
import time

class BasicModule(torch.nn.Module):

    def __init__(self):
        super(BasicModule, self).__init__()
        self.model_name=str(type(self))  # model name

    def load(self, path):

        self.load_state_dict(torch.load(path))

    def save(self, name=None):

        prefix = 'checkpoints/'
        if name is None:
            name = prefix + self.model_name + '_'
            name = time.strftime(name + '%m%d_%H:%M:%S.pth')
        else:
            name = prefix + self.model_name + '_' + name + '.pth'
        torch.save(self.state_dict(), name)
        return name

**Comment by apaszke** [comment]
Please use the issue template to provide information we'll need to resolve your issue. We can't do anything until we have it.

**Comment by MoonBunnyZZZ** [comment]
- PyTorch or Caffe2:PyTorch
- OS:Ubuntu16.04LTS
- PyTorch version:0.3.1
- How you installed PyTorch (conda, pip, source):conda install pytorch-cpu torchvision -c pytorch
- Python version:3.6/2.7

I install pytorch by conda in a virtual environment.
When I try to use the utils.data module,The error was got :
>>> import torch as tc
>>> a=tc.utils.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.utils' has no attribute 'data'
I tesedt both python 3.6 and python 2.7.  Same error  occur. 
@apaszke @eklitzke @jfsantos @kashif

**Comment by apaszke** [comment]
We don’t import the utils module by default. You need to `import torch.utils.data`
