### ISSUE TITLE
torch.linalg.eig() doesn't handle NaNs

### ISSUE THREAD

**Issue by jonasjuerss** [pytorch/pytorch#61251]
## 🐛 Bug
This is a followup to https://github.com/pytorch/pytorch/issues/37499. As it was decided to handle NaNs in `x.eig()` for a tensor `x` there, I suppose they should also be handled for `torch.linalg.eig(x)`.

### To reproduce
```
import torch
import numpy as np
A = np.nan * torch.ones((3,3))
torch.linalg.eig(A)
```
This currently gives:
```
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
### Environment
 - PyTorch Version: 1.9.0+cu102
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.7
 - CUDA/cuDNN version: 10.2

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by jamaliki** [comment]
I would love to help here as my first contribution if I can get some guidance.

**Comment by malfet** [comment]
I could not reproduce the crash on Mac, but only when code is compiled with MKL:
```
% python -c "import torch;print(torch.__version__);print(torch.linalg.eig(float('nan') * torch.ones(3, 3)))" 
1.10.0a0+git1f03965
** On entry to SGEBAL, parameter number  3 had an illegal value
** On entry to SGEHRD, parameter number  2 had an illegal value
** On entry to SORGHR, parameter number  2 had an illegal value
** On entry to SHSEQR, parameter number  4 had an illegal value
** On entry to SGEBAK, parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: torch.linalg.eig: Argument 4 has illegal value
%%  /usr/bin/python3 -c "import torch;print(torch.__version__);print(torch.linalg.eig(float('nan') * torch.ones(3, 3)))"
1.9.0
** On entry to SGEBAL, parameter number  3 had an illegal value
** On entry to SGEHRD, parameter number  2 had an illegal value
** On entry to SORGHR, parameter number  2 had an illegal value
** On entry to SHSEQR, parameter number  4 had an illegal value
** On entry to SGEBAK, parameter number  4 had an illegal value
Python(31967,0x102a97d40) malloc: Incorrect checksum for freed object 0x13af07e18: probably modified after being freed.
Corrupt value: 0xffc000007fc00000
Python(31967,0x102a97d40) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      /usr/bin/python3 -c 
```

**Comment by IvanYashchuk** [comment]
[Balancing routines in LAPACK](https://www.netlib.org/lapack/lug/node51.html) (used inside eigenvalues solvers) do not work well with NaNs or Infs.
Reference LAPACK implementation has checks for NaN and _may_ exit correctly
https://github.com/Reference-LAPACK/lapack/blob/77a0ceb6c9a3c757e7039027f1f324e2811e6ee0/SRC/sgebal.f#L345-L351
But I compiled PyTorch with lapack=netlib and lapack=openblas (both use reference lapack implementation) from conda-forge and the program just hangs on invalid inputs.
PyTorch compiled with MKL segfaults.

[MKL recommends](https://software.intel.com/sites/products/documentation/doclib/mkl_sa/11/mkl_lapack_examples/lapackro2.htm) testing input for NaN and Inf:
> The standard LAPACK functions do not check the input data (matrices) for IEEE 754 floating point INFs or NANS. INFs and NANs will propagate through the computations and may cause unexpected results or instabilities. It is the user's responsibility to ensure that the input data do not contain INFs nor NaNs.
The LAPACKE (C interfaces to LAPACK) functions do check for NaNs in the input data (matrices) , and an error code is returned if a NAN is found.

eig, eigvals are the only problematic functions causing crash, other functions from torch.linalg either propagate nan, or raise an error from LAPACK.

SciPy's linalg functions have a flag `check_finite=True` that by default checks inputs for NaNs or Infs and raises an error.  With `check_finite=False` no check is performed.

To avoid crashes or freezes immediate possible fixes:

1. Add a check for NaNs and Infs in the beginning of `linalg_eig_out`, `linalg_eigvals_out` in `aten/src/ATen/native/BatchLinearAlgebra.cpp`.
  It would raise an error if at least one element of any matrix in the batched input is not finite.
  This behavior would be similar to other linalg functions that raise an error.
2. In `apply_linalg_eig` from `aten/src/ATen/native/BatchLinearAlgebraKernel.cpp` check for NaNs or Infs per each matrix in the batch. If NaN or Inf element is present in the matrix skip calling `lapackEig` in the for loop for that matrix and fill the output with NaN/Inf instead.
  Do the same for `apply_linalg_eig` from `aten/src/ATen/native/cuda/BatchLinearAlgebra.cu`.
  This would enable correct computations for matrices in the batch that have finite elements.

@mruberry, what do you think is a better option? I lean towards propagating NaNs or Infs without raising an error.

**Comment by IvanYashchuk** [comment]
@jamaliki, thank you for your interest in contibuting to PyTorch! Do have experience building PyTorch from source? Here are the instructions https://github.com/pytorch/pytorch#from-source

For fixing this problem I think CPU only build is sufficient and it is faster to build. If you prefer to use conda for development work, you can use [this environment file](https://github.com/Quansight/pearu-sandbox/blob/master/conda-envs/pytorch-cuda-dev.yaml). Then compile PyTorch with `DEBUG=1 USE_CUDA=0 python setup.py develop`. LAPACK should be picked up automatically from conda environment, but please check the logs in the beginning of the compilation for the following lines:
```
--   USE_BLAS              : 1
--     BLAS                : mkl
--   USE_LAPACK            : 1
--     LAPACK              : mkl
```
In addition to proposed fixes in my previous message, the pull request would need a test with a link to this issue. The test should be added to `test/test_linalg.py` file.

**Comment by malfet** [comment]
Both MKL and OpenBLAS implement [LAPACKE_get_nancheck](https://www.netlib.org/lapack/explore-html/d2/db1/lapacke__nancheck_8c_a8e1f1fb0ed6d571c26e80242572be8e2.html) but it still causes hard crash when MKL is used and seems to be missing in MacOS LAPACK implementation

**Comment by jamaliki** [comment]
@malfet so then it would make sense to handle this on the torch side right

**Comment by malfet** [comment]
@jamaliki yes, essentially it would be great to introduce a context manager, that could be used to enable/disable nanchecks, i.e. to have something like:
```
with torch.linalg.nancheck(Flase):
  # This will run faster but might crash
   torch.linalg.eig(torch.linalg.eig(float('nan') * torch.ones(3, 3)))
```

**Comment by jamaliki** [comment]
@malfet Interesting, is there an example of doing this through the C++ API? I'm assuming the C++ code will see a flag set or something and only check for NaNs then?

**Comment by malfet** [comment]
Sample below reproduces that crash if MKL-2020 is used as LAPACK backend even when nancheck is set to true:
```
// Compile me as
// gcc foo.c -lmkl_lapack95_lp64 -lmkl_blas95_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm -L/home/conda/miniconda3/lib/
#include <stdio.h>
#include <math.h>

void sgeev_(char *jobvl, char *jobvr, int *n, float *a, int *lda, float *wr, float *wi, float* vl, int *ldvl, float *vr, int *ldvr, float *work, int *lwork, int *info);

int main(void) {
  char jobvl = 'N';
  char jobvr = 'V';
  int n = 3;
  float a[9];
  int lda = 3;
  float w[6];
  float* vl = 0;
  int ldvl = 1;
  float vr[9];
  int ldvr = 3;
  float work[102];
  int lwork = 102;
  int info[3];

  float *wr = w;
  float *wi = w + n;

  for(int i = 0; i < 9; ++i) {
      a[i] = NAN;
  }
  sgeev_(&jobvl, &jobvr, &n, a, &lda, wr, wi, vl, &ldvl, vr, &ldvr, work, &lwork, info);
  printf("info[0]=%d\n", info[0]);
  return 0;
}
```

```
$ LD_LIBRARY_PATH=~/miniconda3/lib lldb ./a.out 
(lldb) target create "./a.out"
Current executable set to '/home/conda/a.out' (x86_64).
(lldb) r
Process 3057295 launched: '/home/conda/a.out' (x86_64)

Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Process 3057295 stopped
* thread #1, name = 'a.out', stop reason = signal SIGSEGV: invalid address (fault address: 0x7ffffffff000)
    frame #0: 0x00007ffff1b92932 libmkl_core.so`mkl_lapack_sgehrd + 386
libmkl_core.so`mkl_lapack_sgehrd:
->  0x7ffff1b92932 <+386>: movups %xmm0, 0x10(%rbp,%rcx,4)
    0x7ffff1b92937 <+391>: addq   $0x8, %rcx
    0x7ffff1b9293b <+395>: cmpq   %rdi, %rcx
    0x7ffff1b9293e <+398>: jb     0x7ffff1b9292d            ; <+381>
(lldb) p (int)LAPACKE_get_nancheck()
(int) $0 = 1

```

**Comment by jamaliki** [comment]
@malfet Oh I see, what I was asking was if there is any example in the pytorch codebase of passing the status of a python context manager like `torch.linalg.nancheck(False)` to, for example, the C++ code in `aten/src/ATen/native/BatchLinearAlgebraKernel.cpp` such that if `nancheck` is true, I can add a check in `aten/src/ATen/native/BatchLinearAlgebraKernel.cpp` to fill with nans, otherwise just run normally.

**Comment by IvanYashchuk** [comment]
> Both MKL and OpenBLAS implement [LAPACKE_get_nancheck](https://www.netlib.org/lapack/explore-html/d2/db1/lapacke__nancheck_8c_a8e1f1fb0ed6d571c26e80242572be8e2.html) but it still causes hard crash when MKL is used and seems to be missing in MacOS LAPACK implementation

@malfet, yes there are nan checks in LAPACKE (C wrapper of Fortran LAPACK). But we don't use that wrapper, we use Fortran LAPACK library and in your snippet also Fortran LAPACK is used (`sgeev_` vs `LAPACKE_sgeev`).
