### ISSUE TITLE
Problem of combining nn.functional, vmap and __torch_function__

### ISSUE THREAD

**Issue by xidulu** [pytorch/pytorch#61279]
Hi there

I was using the nightly version of torch and I was trying to use neural network functional api together with vmap and __torch_function__, however, there is an exception raised

Code for reproduce:
```python
import torch
from torch import vmap
import torch.nn.functional as F

class vmapTensor(torch.Tensor):
    @classmethod
    def __torch_function__(cls, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}
        if func == F.linear:
            func = vmap(func, (0, 0), 0)
        return super().__torch_function__(func, types, args, kwargs)

x = vmapTensor(torch.randn(10, 5, 10))
W = vmapTensor(torch.randn(10, 5, 10))

print(F.linear(x, W))
```

The error message says:
```python
Traceback (most recent call last):
  File "/Users/admin/Program/tpp/test2.py", line 39, in <module>
    print(F.linear(x, W))
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1846, in linear
    return handle_torch_function(linear, (input, weight), input, weight, bias=bias)
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/torch/overrides.py", line 1314, in handle_torch_function
    result = overloaded_arg.__torch_function__(public_api, types, args, kwargs)
  File "/Users/admin/Program/tpp/test2.py", line 33, in __torch_function__
    return super().__torch_function__(func, types, args, kwargs)
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/torch/_tensor.py", line 1023, in __torch_function__
    ret = func(*args, **kwargs)
TypeError: wrapped() got an unexpected keyword argument 'bias'
```

**Comment by gchanan** [comment]
@zou3519

**Comment by zou3519** [comment]
The issue happens because:
1. IIRC torch_function makes F.linear pass bias as a keyword arg instead of positional 
2. vmap doesn't handle kwargs correctly

@xidulu we've moved vmap development over to functorch (https://github.com/facebookresearch/functorch). You can install functorch alongside the latest nightly of PyTorch and `from functorch import vmap`. It looks like functorch's vmap does support kwargs so this problem should be resolved by installing functorch.

**Comment by xidulu** [comment]
@zou3519 
Thanks a lot! Using functorch indeed solves the question.

The entire functorch project is looking very exciting and promising.

**Comment by zou3519** [comment]
@xidulu the project is still in the early stages so if you have any feedback please open us an issue over at our [github](https://github.com/facebookresearch/functorch). 

If you have the time, could you tell us a bit more about your use case?

**Comment by xidulu** [comment]
> @xidulu the project is still in the early stages so if you have any feedback please open us an issue over at our [github](https://github.com/facebookresearch/functorch).
> 
> If you have the time, could you tell us a bit more about your use case?

Hi @zou3519 

Our use case uses vmap and named tensor together.

To be more specific, we are constructing a type of tensor that performs cartesian product like computation for arbitary operators, e.g.
```python
x = MagicTensor(torch.ones(3,4)).refine_names('A', 'B')
y = MagicTensor(torch.ones(4,5)).refine_names('B', 'C')
```

We would expect `x + y`  to have shape `(3,4,5)` and name `('A', 'B', 'C')`. 

Our use case involves vmap over multiple axes and named dimensions. However, the current implementation does not support both. So our current work around would first remove names and squeeze multiple dimensions into one giant dimension before feeding the input into vmap function. After we acquire the output, we would unsqueeze the dimensions and put names back.

Our current implementation works perfectly well but I would say something like Jax's new xmap feature is more naturally suitable for our use case (https://jax.readthedocs.io/en/latest/jax.experimental.maps.html) which could make our implementation neater and more efficient.

**Comment by zou3519** [comment]
Thanks xidulu! There were some other users who wanted something like namedtensor-like behavior with vmap. Also cc @Chillee
