### ISSUE TITLE
ConcatDataset does not support slices: implement ConcatTensorDataset

### ISSUE THREAD

**Issue by johann-petrak** [pytorch/pytorch#61273]
Currently the following will throw an exception "TypeError: '<' not supported between instances of 'slice' and 'int'"

```
import torch
from torch.utils.data import TensorDataset, ConcatDataset

ds = ConcatDataset([TensorDataset(torch.randn(3,2,3)), TensorDataset(torch.randn(7,2,3))])

slice = ds[2:6]
```

There is probably no good way to generalize the semantics of slices to all possible ConcatDataset types, but since the most common situation is probably to have a ConcatDataset of TensorDataset instances, it would be useful to have a ConcatTensorDataset class which supports slices. This class would return a tuple with tensors which basically recreate the tensors from which the concat dataset was created, limited to the given indices for the first dimension.

Related: https://github.com/pytorch/text/issues/1030

cc @VitalyFedyunin @ejguan

**Comment by johann-petrak** [comment]
Why this could be useful: the ability to create tensors from slices and index lists makes it much easier to do things like stratified dev sets, stratified batches, select instances for multitask training batches etc.

**Comment by johann-petrak** [comment]
Closing since there is no interest.

**Comment by AliyaDav** [comment]
I agree. Is there a workaround for that now? I need to get tensors from combined dataset, but without slices the only way to do that is going through a loop, concatinating and then reshaping to the size needed, which is totally inefficient.

**Comment by johann-petrak** [comment]
@AliyaDav  see the related PR and code which I provided, perhaps it is useful to you: https://github.com/johann-petrak/pytorch/commit/eb70e81e31508c383bdc17059ddb532a6b40468c
This PR was not accepted for some reason and I think the problem is still unsolved in the current version but I did not check for a while now.
