### ISSUE TITLE
`tensor` in `container-of-tensors` should never throw

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#61303]
Consider following example:
 % /usr/bin/python3 -c "import torch;print(torch.ones(3, 4) in [torch.ones(2, 3), torch.ones(4, 5)])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

My mental model says that `__contains__` should never raise, but that might require changes to how `__eq__` behaves for tensors of different sizes/on different devices.

cc @mruberry @rgommers @heitorschueroff

**Comment by gchanan** [comment]
NumPy equivalent:
```
>>> np.ones((3, 4)) in [np.ones((2, 3)), np.ones((4, 5))]
__main__:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
False
```

**Comment by soulitzer** [comment]
@mruberry Theres no sensible result, so should always error. But there are bc-breaking concerns

**Comment by ezyang** [comment]
We can't fix this as it would be BC breaking
