### ISSUE TITLE
Build picks up wrong copy of mkl when multiple available

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6131]
@aosokin reports from https://github.com/pytorch/pytorch/issues/6068#issuecomment-377226963

There might be another related issue with dependencies.
When doing import torch from an anaconda env pytorch uses mkl (libmkl_gf_lp64.so) installed in anaconda root.
Consequently, if the root and the env have different versions (in my case the root had 2018.0.1 and the env had 2018.0.2-1) I was getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aosokin/local/software/anaconda3/envs/pytorch-master/lib/python3.6/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
ImportError: /home/aosokin/local/software/anaconda3/lib/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_ao_zgetrf
```

Updating mkl in anaconda root to 2018.0.2-1 solved the problem.

**Comment by davidbau** [comment]
I found that setting the `MKLROOT` environment variable to point to the local conda environment directory fixes the issue.

```
MKLROOT="${HOME}/.conda/envs/${ENV_NAME}/" \
MAX_JOBS=12 \
python setup.py install
```

**Comment by malbergo** [comment]
@davidbau I'm having the same issue on Ubuntu 16.04. Where did you right that MKLROOT line? In file? 

Thanks

**Comment by shianiawhite** [comment]
I'm also running into this issue even after specifying `MKLROOT` as my Conda environment directory. Might I be missing something else?

**Comment by sumrania** [comment]
I downgraded mkl to 2018.0.1 by using `conda install mkl=2018.0.1` and it worked.
