### ISSUE TITLE
libtorch fp16 MALFORMED INPUT error

### ISSUE THREAD

**Issue by tianyu06030020** [pytorch/pytorch#61336]
hi, my env is:
pytorch:1.7.1
libtorch:1.9.0
cuda:11.1
cudnn:8.2.1

i successfully transformed pytorch model to .pt by trace。and when i use libtorch fp32 and fp16, i works well, but if added snipped code:
![选区_046](https://user-images.githubusercontent.com/9124519/124715647-ce293580-df35-11eb-92cd-bc61b0103a42.png)

in mode fp32 also well, but fp16 give following error:

![选区_045](https://user-images.githubusercontent.com/9124519/124715564-bb166580-df35-11eb-922b-c5cc7edeb0ac.png)

my code is:
![选区_049](https://user-images.githubusercontent.com/9124519/124716126-4abc1400-df36-11eb-9eae-8fa1f525bdd6.png)
![选区_048](https://user-images.githubusercontent.com/9124519/124715871-06307880-df36-11eb-879f-71e7d73adf32.png)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @gmagogsfm

**Comment by ngimel** [comment]
related #61382

**Comment by gmagogsfm** [comment]
@ZolotukhinM Same for this issue.

**Comment by ZolotukhinM** [comment]
This looks like a bug in how half dtype is handled in NNC fuser. While we're looking at it, you could turn it off by calling
```cpp
overrideCanFuseOnGPU(false);
```

**Comment by tianyu06030020** [comment]
> This looks like a bug in how half dtype is handled in NNC fuser. While we're looking at it, you could turn it off by calling
> 
> ```c++
> overrideCanFuseOnGPU(false);
> ```

**Comment by tianyu06030020** [comment]
> > This looks like a bug in how half dtype is handled in NNC fuser. While we're looking at it, you could turn it off by calling
> > ```c++
> > overrideCanFuseOnGPU(false);
> > ```

thx for your reply and looking forward to this bug fixed.

when i try the method you mentioned, i find this function most likely defined in the file: but i can not find the definition of this function from my downloaded libtorch(1.9.0),

**Comment by tianyu06030020** [comment]
> This looks like a bug in how half dtype is handled in NNC fuser. While we're looking at it, you could turn it off by calling
> 
> ```c++
> overrideCanFuseOnGPU(false);
> ```

hi @ZolotukhinM, thx for your reply, when i tried your method mentioned above, i can not find the definition about this function in libtorch, and when googled, mostly says it's in the pytorch/torch/csrc/jit/codegen/fuser/interface.cpp not in libtorch, my libtorch'jit dir structure looks like this, doesn't has codegen dir:

![选区_050](https://user-images.githubusercontent.com/9124519/125383517-1a5af680-e3ca-11eb-89e4-30738c2b803d.png)

**Comment by ZolotukhinM** [comment]
That's the right one, and it should be there in 1.7 too:
https://github.com/pytorch/pytorch/blob/1.7/torch/csrc/jit/codegen/fuser/interface.h#L35-L36

What version of pytorch are you looking at?

Btw, the method lives in `torch::jit::` namespace, so please also make sure not to forget adding this - sorry that I didn't mention that in the original comment.

**Comment by ZolotukhinM** [comment]
This should be fixed by #61569. It will probably not be cherry-picked to 1.7, but if you use a nightly build or the next release, it should work. Please reach out if you need more help!

**Comment by tianyu06030020** [comment]
> This should be fixed by #61569. It will probably not be cherry-picked to 1.7, but if you use a nightly build or the next release, it should work. Please reach out if you need more help!

Ok, thanks a lot, I am looking forward to the next release.

**Comment by tianyu06030020** [comment]
> This should be fixed by #61569. It will probably not be cherry-picked to 1.7, but if you use a nightly build or the next release, it should work. Please reach out if you need more help!

I'm sorry, my pytorch version is 1.9.0, If I use libtorch1.9.0 downloaded from pytorch offical website,  the same error occured, and I cannot find interface.h。
