### ISSUE TITLE
QNNPACK build error: can't convert between vector values of different size

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#61352]
## 🐛 Bug

When I try to build the master branch of PyTorch or try to directly build QNNPACK, I see the following build error:
```
[63/5822] Building C object confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/sgemm/6x8-psimd.c.o
FAILED: confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/sgemm/6x8-psimd.c.o
/mnt/a/u/sciteam/stewart1/spack/lib/spack/env/gcc/gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DTH_BLAS_MKL -I../third_party/QNNPACK/include -I../third_party/QNNPACK/src -I../third_party/cpuinfo/deps/clog/include -I../third_party/cpuinfo/include -I../third_party/FXdiv/include -I../third_party/psimd/include -I../third_party/FP16/include -isystem /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/protobuf-3.12.2-6pj5yoxatslaphjmwd5zl573rriwehew/include -isystem /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/intel-mkl-2020.4.304-2nb3pmft6rc44rayjhltqe3u3elzvczm/compilers_and_libraries_2020.4.304/linux/mkl/include -O3 -DNDEBUG -fPIC -Wno-deprecated-declarations -std=gnu99  -O2 -MD -MT confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/sgemm/6x8-psimd.c.o -MF confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/sgemm/6x8-psimd.c.o.d -o confu-deps/QNNPACK/CMakeFiles/qnnpack.dir/src/sgemm/6x8-psimd.c.o -c ../third_party/QNNPACK/src/sgemm/6x8-psimd.c
In file included from ../third_party/QNNPACK/src/sgemm/6x8-psimd.c:9:0:
../third_party/psimd/include/psimd.h: In function 'psimd_qfma_f32':
../third_party/psimd/include/psimd.h:669:23: warning: implicit declaration of function '_mm_macc_ps' [-Wimplicit-function-declaration]
    return (psimd_f32) _mm_macc_ps((__m128) b, (__m128) c, (__m128) a);
                       ^
../third_party/psimd/include/psimd.h:669:4: error: can't convert between vector values of different size
    return (psimd_f32) _mm_macc_ps((__m128) b, (__m128) c, (__m128) a);
    ^
ninja: build stopped: subcommand failed.
```

## To Reproduce

1. `git clone https://github.com/spack/spack.git`
2. `. spack/share/spack/setup-env.sh`
3.  `spack install py-torch`

Of course, this can also be reproduced from source by setting a million environment variables. See the build log/env below for the exact set of commands Spack runs.

## Expected behavior

I would expect PyTorch to build successfully.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Cray CNL5
 - How you installed PyTorch (`conda`, `pip`, source): `spack`
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.11
 - CUDA/cuDNN version: 9.1.85/7.1.3
 - GPU models and configuration: K40 (sm_3.5)

## Additional context

These logs may help:

* [build log](https://github.com/pytorch/pytorch/files/6778497/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/6778499/spack-build-env.txt)

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
The real culprit here is:
```
../third_party/psimd/include/psimd.h:669:23: warning: implicit declaration of function '_mm_macc_ps' [-Wimplicit-function-declaration]
    return (psimd_f32) _mm_macc_ps((__m128) b, (__m128) c, (__m128) a);
```
This intrinsic should have been defined  in https://github.com/gcc-mirror/gcc/blob/releases/gcc-5.3.0/gcc/config/i386/fma4intrin.h
Can you check if this definition is present in your compiler?  Also please note, that oldest compiler PyTorch master is tested against is gcc-5.4, while from the build-env it looks like you are using gcc-5.3. Can you perhaps update the compiler?

**Comment by adamjstewart** [comment]
I'm not a C/C++ expert... how do I check if that intrinsic is defined?

I can try using a newer GCC, although I can't use anything newer than GCC 5 due to an ancient version of CUDA on this ancient system. Let me try GCC 5.5.

**Comment by adamjstewart** [comment]
Tried with GCC 5.5.0 and I still see the same issue.

**Comment by adamjstewart** [comment]
This bug report is ancient and the system on which it occurred no longer exists. If no one else has encountered this issue, I think it can be closed.
