### ISSUE TITLE
TensorPipe: build error: 'CU_POINTER_ATTRIBUTE_DEVICE_ORDINAL' was not declared in this scope

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#61362]
## 🐛 Bug

When trying to build the master branch of PyTorch, I see the following build error:
```
In file included from ../third_party/tensorpipe/tensorpipe/common/cuda.h:21:0,
                 from ../third_party/tensorpipe/tensorpipe/common/cuda_buffer.cc:11:
../third_party/tensorpipe/tensorpipe/common/cuda.h: In function 'int tensorpipe::cudaDeviceForPointer(const tensorpipe::CudaLib&, const void*)':
../third_party/tensorpipe/tensorpipe/common/cuda.h:161:11: error: 'CU_POINTER_ATTRIBUTE_DEVICE_ORDINAL' was not declared in this scope
           CU_POINTER_ATTRIBUTE_DEVICE_ORDINAL,
           ^
../third_party/tensorpipe/tensorpipe/common/cuda_lib.h:20:23: note: in definition of macro 'TP_CUDA_DRIVER_CHECK'
     CUresult error = (a);                                                 \
                       ^
ninja: build stopped: subcommand failed.
```

## To Reproduce

1. `git clone https://github.com/spack/spack.git`
1. `. spack/share/spack/setup-env.sh`
1. `spack install py-torch`

## Expected behavior

I would expect PyTorch to build without issue. If I install TensorPipe separately, it builds without issue. If PyTorch allowed me to use an externally installed TensorPipe this wouldn't be an issue.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Cray CNL5
 - How you installed PyTorch (`conda`, `pip`, source): `spack`
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.11
 - CUDA/cuDNN version: 9.1.85/7.1.3
 - GPU models and configuration: K40 (sm_3.5)

## Additional context

These logs may help:

* [build log](https://github.com/pytorch/pytorch/files/6779186/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/6779187/spack-build-env.txt)

cc @osalpekar @jiayisuse @lw @beauby @pritamdamania87 @mrshenli @jjlilley @gqchen @rohan-varma @pietern @zhaojuanmao @satgera @aazzolini @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
cc @lw Would you be the right person to look into this issue?

**Comment by lw** [comment]
You're building with CUDA 9.1. TensorPipe uses that option which was introduced in CUDA 9.2. I think these days PyTorch only supports CUDA 10.2 or newer, so I think it would be best if you managed to upgrade CUDA.

**Comment by adamjstewart** [comment]
> I think these days PyTorch only supports CUDA 10.2 or newer

According to https://github.com/pytorch/pytorch/blob/master/cmake/public/cuda.cmake#L42, PyTorch still supports CUDA 9+. Is this wrong? I don't see anywhere else where a minimum CUDA version is defined.

> I think it would be best if you managed to upgrade CUDA

I can ask our sys admins, but it's generally pretty hard to upgrade CUDA on a supercomputer.

**Comment by lw** [comment]
> Is this wrong?

I'm asking around to double-check, I'll let you know.

> I can ask our sys admins, but it's generally pretty hard to upgrade CUDA on a supercomputer.

I think a more recent version of the CUDA runtime can be installed using conda, or anyway without requiring root permissions. (Unless upgrading the runtime also requires upgrading the driver, though I don't know what version of the driver you have).

**Comment by adamjstewart** [comment]
Yes, I think the issue is that I can upgrade the runtime easily but that requires an upgrade to the drivers. Checking with our sys admins.

**Comment by lw** [comment]
So in truth we're not exactly tracking what version is the strict minimum supported, but for certain we don't support anything older than 9.2, because in https://github.com/pytorch/pytorch/pull/36848 we removed workaround for pre-9.2. Hence I'm in fact updating that error message you pointed to in https://github.com/pytorch/pytorch/pull/61462. I hope you managed to get CUDA updated...

**Comment by adamjstewart** [comment]
Okay, I spoke with our sys admins and it sounds like they aren't able to upgrade the CUDA runtime without also upgrading the drivers, hardware, and glibc, so it isn't going to happen.

As much as I would love for PyTorch to continue to support ancient versions of CUDA, I realize that it would introduce a significant maintenance overhead and isn't going to happen. I may try to reverse the patch from #36848 and apply it locally, or I may just stop using this supercomputer.

Thanks for pointing me in the right direction and upgrading CMake to check for the right CUDA version! I think this issue can be closed now.
