### ISSUE TITLE
Consolidate and pin Python dependencies in CI

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#61375]
This issue describes a problem with Python dependencies and a potential solution. The goal is to start a discussion to decide whether (and if so, how) to resolve this problem; that may end up being via the proposal below or via a different approach.

# Problem

Currently, we use many different Python dependencies (primarily installed via `pip` or `conda`) for many different jobs in CI. These dependencies are spread all across the repository (the following list probably isn't comprehensive):

- `.circleci/`
  - [`docker/common/install_conda.sh`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.circleci/docker/common/install_conda.sh#L64-L137)
  - `verbatim-sources/job-specs/`
    - [`job-specs-custom.yml`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.circleci/verbatim-sources/job-specs/job-specs-custom.yml)
    - [`pytorch-job-specs.yml`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml)
- `.github/`
  - `templates/`
    - [`linux_ci_workflow.yml.j2`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.github/templates/linux_ci_workflow.yml.j2)
    - [`windows_ci_workflow.yml.j2`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.github/templates/windows_ci_workflow.yml.j2)
  - `workflows/`
    - [`lint.yml`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.github/workflows/lint.yml)
    - [`test_tools.yml`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.github/workflows/test_tools.yml#L22-L29)
- `.jenkins/pytorch/`
  - `win-test-helpers/`
    - [`build_pytorch.bat`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.jenkins/pytorch/win-test-helpers/build_pytorch.bat#L24-L25)
    - [`setup_pytorch_env.bat`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.jenkins/pytorch/win-test-helpers/setup_pytorch_env.bat#L22-L48)
  - [`macos-test.sh`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/.jenkins/pytorch/macos-test.sh#L9-L13)
- [`Makefile`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/Makefile#L52-L73)
- [`requirements-flake8.txt`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/requirements-flake8.txt)
- [`requirements.txt`](https://github.com/pytorch/pytorch/blob/1262b2c4c6d5406fc48a82a6be78ad43f7d7d1d4/requirements.txt)

This makes it very difficult to correctly add new Python dependencies that are used in CI, such as #60658.

Furthermore, some of these dependencies are pinned to specific versions, but others are not. This sometimes causes CI to break when dependencies are upgraded: for instance, see #60472 which pinned `numpy` to version 1.20 to fix our `mypy` lint. Notice that that PR only pins `mypy` in one place and nowhere else, compounding the fragmentation (as an aside, notice in that multiple `numpy` versions are already pinned in the section of `install_conda.sh` linked above).

In addition to complicating CI, this also makes local development more difficult. For example, after #60658 was merged, several PyTorch developers ran into errors when running tests locally because they did not have `expecttest` installed on their development machines. There is no automated system in place to help PyTorch developers ensure that they have all the Python packages they need to do their work.

# Proposal

The draft PR #60697 prototypes the following approach:

- Add a `requirements-dev.in` file which includes (via `-r`) our existing top-level `requirements*.txt` files, and also specifies several other dependencies which we currently use in CI but only buried inside of scripts.
- Use [`pip-compile`](https://github.com/jazzband/pip-tools) to automatically generate a `.circleci/docker/requirements.txt` file from that `requirements-dev.in` file, which pins everything
- Use a GitHub Actions job to run `pip-compile` to make sure `.circleci/docker/requirements.txt` stays up to date. This doesn't update pinned dependencies; it only ensures that the generated file reflects the `requirements-dev.in` file it's generated from.
- Wherever possible, replace hardcoded `pip install` (or even `conda install`) commands with `pip install -r .circleci/docker/requirements.txt`.
- Use a separate GitHub Actions job to submit PRs to bump pinned dependencies in `.circleci/docker/requirements.txt` via `pip-compile --upgrade`.

This has a few downsides/caveats:

- From initial experiments, it seems to take up to a minute to run `pip install -r .circleci/docker/requirements.txt` in GitHub Actions. This isn't great compared to our previous approach to install specific packages (which would only take a few seconds), but it's also not terrible.
- Reviewing the autogenerated `pip-compile --upgrade` PRs could be tedious.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by zhouzhuojie** [comment]
Great effort on consolidating the Python dependencies! LGTM.

Ideally local and ci should run the same dependencies for better reproducibility. Since the team is restructuring the entrypoints of CI, do you think we can use a neutral folder like `./tools/ci` or `./ci` for the common things like `.circleci/docker/requirements.txt` and `requirements-dev.in`?

Or, the root directory also works, if we name it like

```
- requirements.txt     # runtime install_requires are taken care by setup.py, this is purely for dev, should we combine these two?   
- requirements-dev.txt # refactor the flake8 one to requirements-dev.in, this file can be set as the generated output location from pip-compile
```

**Comment by samestep** [comment]
@zhouzhuojie Good questions; the reason I was suggesting to put the `pip-compile`-generated `requirements.txt` in `.circleci/docker/` is because our current Docker logic uses `git rev-parse HEAD:.circleci/docker` to tag images, so the if we use that file when building our Docker images, it needs to be inside that directory.

**Comment by janeyx99** [comment]
Further progress now tracked in #72556 and #72558
