### ISSUE TITLE
Compilation error when attempting to install from source.

### ISSUE THREAD

**Issue by spott** [pytorch/pytorch#6137]
- OS: Ubuntu 16.10
- PyTorch version: 0.4.xxx (git master)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.3
- CUDA/cuDNN version: 9.1
- GPU models and configuration: GTX 1060 6gb
- GCC version (if compiling from source): 6.4.0-8ubuntu1

Compile log is at: https://gist.github.com/spott/4a893ba403bbbfd65e094e41d9963001

It seems to be choking on some stdlib stuff... 

I'm attempting to install without anaconda, which might be part of the issue.

**Comment by avocadochicken** [comment]
I think this was one the the errors I also had, while compiling. This solution (using gcc 4.8) worked for me:
https://medium.com/@Inoryy/compiling-pytorch-4-0-on-ubuntu-17-10-with-cuda-9-0-and-python-3-6-6769a0df56d5
