### ISSUE TITLE
Execution time of load_state_dict

### ISSUE THREAD

**Issue by noilreed** [pytorch/pytorch#61398]
I'm refactoring a model from older torch version (v0.3.1) to newer version (v1.9.0). After that I realized the training time gets very slow. The problem is in `nn.module.load_state_dict`. 
The change happens in #6639, the old code is understandable but new code becomes fancy (I haven't fully understand how does it work) and there is a recursion call in it. Looks like the recursion call is making my model loading parameters 200x slower. The problem is my model have to load parameter for every training step, that's why it becomes slower. 
Therefore:
1. Is it safe to just temporarily copy and use old load_state_dict in newer version? I'm trying to do that, the training speed returns to normal (actually even faster), their results are exactly the same, and no problem occurs so far.
2. Is it safe to request to refine current code in terms of execution time, or implement a alternative lightweight version of `load_state_dict`? I think there must be people who have same problem as me.
Thanks!

cc @albanD @mruberry @jbschlosser @VitalyFedyunin @ngimel @heitorschueroff

**Comment by xsacha** [comment]
load_state_dict will be loading all the weights, usually from a file you just loaded. Doesn't sound like something you'd ever want to do more than once.
If your model is doing this at every training step, that sounds like the wrong thing to do. It should be done once at startup.

**Comment by noil-reed** [comment]
> load_state_dict will be loading all the weights, usually from a file you just loaded. Doesn't sound like something you'd ever want to do more than once.
> If your model is doing this at every training step, that sounds like the wrong thing to do. It should be done once at startup.

Generally people don't need it for sure, it's in some tricky model however, especially when you do bilevel optimization (which my research heavily depends on). Whoever interested in autoML and NAS could check [this work](https://arxiv.org/pdf/1806.09055.pdf). The tricky part is for every training step, it approximates a hessian calculation of parameters by fine-operating and reassigning every parameter to a dummy model. I do think it is a very elegant implementation. :) [[The code I mentioned]](https://github.com/quark0/darts/blob/f276dd346a09ae3160f8e3aca5c7b193fda1da37/cnn/architect.py#L61)

**Comment by xsacha** [comment]
So instead of doing that load_state_dict, you could just clone the self.model and then modify its parameters in-place. This would likely achieve what you want much faster.

**Comment by mruberry** [comment]
Thank you for filing this issue, @noil-reed. Sorry to hear the performance of `load_state_dict` is slowing you down.

Implementing an alternative, like the one suggested by @xsacha, sounds like a good idea for now, especially since we can no longer modify the 1.9 release and `load_state_dict` isn't really designed to do what you're doing. A custom solution may be more elegant.
