### ISSUE TITLE
 `isclose` gives false positives for large integers.

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#61412]
## 🐛 Bug

`isclose` gives false positives for large integers.

## To Reproduce

```python
>>> a = torch.tensor(140499600015872)
>>> b = torch.tensor(140499600015360)
>>> a == b
tensor(False)
>>> abs(a - b) <= 0
tensor(False)
>>> torch.isclose(a, b, atol=0, rtol=0)
tensor(True)
```

## Expected behavior

`a` and `b` should not be considered close.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by mruberry** [comment]
Great catch, @pmeier. We would accept a fix for this. I think the current algorithm can bias towards correctness over performance more with a little extra casting logic and possibly an atol=rtol=0 special case.
