### ISSUE TITLE
No-op full backward hooks modify the input

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#61446]
## 🐛 Bug

As of `torch==1.8.0` `torch.nn.Module.register_backward_hook` is deprecated in favor of `torch.nn.Module.register_full_backward_hook`. In case of a no-op hook,  i.e. one that does not modify the gradient in any way, the full backward hook still modifies the input in case it requires a gradient.

## To Reproduce

Registering a no-op backward hook on an `nn.Module` leaves the input as is:

```python
import torch
from torch import nn

input_without_grad = torch.rand(())
input_with_grad = input_without_grad.clone().requires_grad_(True)


class ModuleWithBackwardHook(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_backward_hook(lambda *args: None)

    def forward(self, input):
        return input


module_with_backward_hook = ModuleWithBackwardHook()
assert (
    module_with_backward_hook(input_without_grad) is input_without_grad
), "Module with backward hook modifies a input without grad"
assert (
    module_with_backward_hook(input_with_grad) is input_with_grad
), "Module with backward hook modifies a input with grad"
```

By registering a no-op full backward hook, the input is modified in case it requires a gradient:

```python
class ModuleWithFullBackwardHook(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_full_backward_hook(lambda *args: None)

    def forward(self, input):
        return input


module_with_full_backward_hook = ModuleWithFullBackwardHook()
assert (
    module_with_full_backward_hook(input_without_grad) is input_without_grad
), "Module with full backward hook modifies a input without grad"
assert (
    module_with_full_backward_hook(input_with_grad) is input_with_grad
), "Module with full backward hook modifies a input with grad"
```

```
AssertionError: Module with full backward hook modifies a input with grad
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @brianjo @mruberry @jbschlosser

**Comment by albanD** [comment]
Hi,

I'm afraid this is expected behavior. We have to intercept these inputs to be able to report the gradients properly. Note that we do the same for the outputs.

Do you think we should mention that this happens in the doc?

**Comment by pmeier** [comment]
I was using the input as a key in some internal caching. This behavior was broken by updating from a backward hook to a full backward hook since I never get the same input, i.e. its hash, twice in the forward call. 

> Do you think we should mention that this happens in the doc?

I think it should go into the documentation of `register_backward_hook` to tell someone who is upgrading that this is happening. Would have saved me a couple of hours of debugging.
