### ISSUE TITLE
Shall the model be released before repeated loading of the script.pt file in C++ API?

### ISSUE THREAD

**Issue by davidten0921** [pytorch/pytorch#61448]
## ❓ Questions and Help
I'm using the Torch C++ API according to the instruction [here](https://pytorch.org/tutorials/advanced/cpp_export.html).
I have a question that if the model is once loaded with a script.pt file and I need to load another one into the same model,
should I operate the model release process to avoid memory leak? 

 `module = torch::jit::load(argv[1]);`

I found no similar issue around.
And I checked the sub functions and no release related function listed.
So it means that the model will automatically release old setting and get new settings right ?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by soulitzer** [comment]
Please use the [forum](https://discuss.pytorch.org/) for questions. Use issues only for feature requests and bug reports
