### ISSUE TITLE
no "arugment"

### ISSUE THREAD

**Issue by saluto** [pytorch/pytorch#61455]
I found a bug [here](https://github.com/pytorch/pytorch/blob/20085f6d2364c4acf526f4eb303b8623207f0d48/aten/src/ATen/core/adaption.cpp#L10), where it says "arugment" instead of "argument".

This severely hinders the use of PyTorch and must be fixed ASAP!! It broke our high availability production system. We already lost multiple big enterprise customers because of you! For sure there are many more people complaining about this tremendous bug. For such a pricey product I expect much better QC. This is unaccpetable!!!
/s

**Comment by samestep** [comment]
lol nice
