### ISSUE TITLE
Replace Xenial with Bionic

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#61460]
Ubuntu 16.04 Xenial reached its end-of-life in April 2021, so we should start migrating from it to Ubuntu 18.04 Bionic or newer. Existing uses of Xenial in this repo can be found with the following command:
```sh
git --no-pager grep -InP '16.?04|xenial' -- .
```
Similar changes also need to be made in [pytorch/builder](https://github.com/pytorch/builder).

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra @walterddr

**Comment by seemethere** [comment]
Assigning myself as well to look over `pytorch/builder`

**Comment by seemethere** [comment]
Not needed for 1.10, but we should get this done ASAP

**Comment by seemethere** [comment]
We're getting closer to April 2021 so marking this as https://github.com/pytorch/pytorch/labels/high%20priority

**Comment by kit1980** [comment]
PRs to migrate off Xenial (to Focal) started to merge:
https://github.com/pytorch/pytorch/pull/77700

**Comment by ZainRizvi** [comment]
Both nightly nor trunk have now been upgraded
