### ISSUE TITLE
Bazel - Pybind - Pytorch - Undefined Symbol 

### ISSUE THREAD

**Issue by yaadhavraajagility** [pytorch/pytorch#61482]
Attempting to write a toy example with Bazel, Pybind, Pytorch/Libtorch fails with the following error on import of the custom library. This setup works fine with Cmake, but attempting to port that over to Bazel, I think i might be missing some step?
```
import libTest
undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE
```

The Bazel WORKSPACE:
```
http_archive(
    name = "pytorch_cpu",
    build_file = "//tools:pytorch_cpu.BUILD",
    sha256 = "6b99edc046f37ad37a3b04dc86663895f10c362af09fdd10884f30360d0ba023",
    urls = [
        "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcpu.zip"
    ],
)
```
The Bazel Build file
```
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pytorch_cpu",
    includes = ["libtorch/include/torch/csrc/api/include", "libtorch/include"],
    hdrs = glob([
      "libtorch/include/**"
    ]),
    srcs = glob([
      "libtorch/lib/*",
    ]),
)
```
And the toy example in Pybind
```
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/numpy.h>
#include <pybind11/pytypes.h>


#include <torch/torch.h>
#include <torch/csrc/utils/pybind.h>


namespace py = pybind11;

torch::Tensor myUsefulMethod() 
{
  return torch::zeros({62,1});
}

PYBIND11_MODULE(libTest, m) {

  m.def("myUsefulMethod", &myUsefulMethod, "myUsefulMethod");

  #ifdef VERSION_INFO
    m.attr("__version__") = VERSION_INFO;
  #else
    m.attr("__version__") = "dev";
  #endif
}

#endif
```
built as 
```
cc_library(
    name = "Test",
    srcs = ["Test.cpp"],
    deps = [
        "@pybind11",
        "@pytorch_cpu"
    ],
)
```

What might be the issue here? This setup seems to work fine in Cmake, but gives the undefined tensor impl error in my bazel setup. Just to note, Libtorch 1.9 binaries were pulled from that above link and pytorch 1.9 installed in it's own pyenv using the default pip install instructions. But they are certainly the same version 

cc @malfet @seemethere @walterddr @yf225 @glaringlee @zou3519

**Comment by malfet** [comment]
Please run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py and share its output here (namely what is the compiler/linker versions you are using)

Sounds similar to https://github.com/pytorch/pytorch/issues/60341 (when older linkers fail to trace transitive dependencies)

**Comment by yaadhavraajagility** [comment]
Resolved. Turns out you need to add 'linkshared=True' and compile it as a binary
