### ISSUE TITLE
Inplace ReLU incompatible with backward hook

### ISSUE THREAD

**Issue by frgfm** [pytorch/pytorch#61519]
## 🐛 Inplace RELU issues with backward hooks

Hello there :wave: 

I encountered a bug I cannot manage to handle with in place ReLUs. In a project of [mine](https://github.com/frgfm/torch-cam/issues/72), I use backward hooks to get intermediate feature maps and gradients. It used to be working fine up until a few versions ago where densenet was throwing warnings caused by the in place relu over here: https://github.com/pytorch/vision/blob/master/torchvision/models/densenet.py#L217

I updated my torch/torchvision versions recently and now it has turned into an error. I tried on my end and was able to reproduce the bug with a simple sequential that includes an in place ReLU. I have no clue how to get around this, anyone got an idea? The strange thing is that the gradient flows back properly, it's just the backward hook that throws the error.

I had initially opened https://github.com/pytorch/vision/issues/4164 thinking the issue was with densenet, but seeing how I was able to reproduce this with a simple sequential, I think the root problem is with PyTorch actually!

Happy to help solving this, thanks in advance!

## To Reproduce

```python
import torch
from torch import nn
# Get the model
mod = nn.Sequential(nn.Conv2d(3, 8, 3, padding=1), nn.ReLU(), nn.Conv2d(8, 8, 3, padding=1), nn.ReLU(inplace=True))
# Hook a module before the in place ReLU
def hook_g(m, input, output): print(input.shape)
mod[2].register_full_backward_hook(hook_g)
# Inference
out = mod(torch.rand((1, 3, 224, 224)))
```

yields:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-d15e02b5edd3> in <module>
----> 1 out = mod(torch.rand((1, 3, 224, 224)))

~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    137     def forward(self, input):
    138         for module in self:
--> 139             input = module(input)
    140         return input
    141 

~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/miniconda3/lib/python3.8/site-packages/torch/nn/modules/activation.py in forward(self, input)
    100 
    101     def forward(self, input: Tensor) -> Tensor:
--> 102         return F.relu(input, inplace=self.inplace)
    103 
    104     def extra_repr(self) -> str:

~/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py in relu(input, inplace)
   1294         return handle_torch_function(relu, (input,), input, inplace=inplace)
   1295     if inplace:
-> 1296         result = torch.relu_(input)
   1297     else:
   1298         result = torch.relu(input)

RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.
```

## Expected behavior

It used to be throwing a warning but this is now causing an error, and I'm unsure how to get around this.

## Environment

 - PyTorch / torchvision Version: 1.9.0 / 0.10.0
 - OS: Ubuntu 20.04.2 LTS (x86_64)
 - How you installed PyTorch / torchvision: conda
 - Python version: 3.8 (64-bit runtime)
 - CUDA/cuDNN version: 11.2.152 (cuDNN 8.2.0)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser

**Comment by soulitzer** [comment]
This is currently expected because registering a full backward hook attaches a dummy custom function that returns a view and in-place operations aren't allowed on views created in custom functions. 

But it seems bad that registering a hook breaks existing behavior. What if we had some kind of `ctx._unsafe_allow_inplace` @albanD?

**Comment by albanD** [comment]
This is an expected limitation I'm afraid.
We don't actually want to allow this because here you actually modify the input inplace, so it is unclear what the grad_input given to the hook should be. Should it be the value before or after?

**Comment by frgfm** [comment]
@albanD I fully agree. Here I'm more trying to get how to obtain back the previous behaviour, the same code snippet with the legacy `register_backward_hook` is working (throwing the warning to use the new version but that's it).

Do you suggest using the legacy version? (but I guess this will be deprecated soon) Or perhaps, we could specify whether we want the value before or after in the new version?

**Comment by albanD** [comment]
> Here I'm more trying to get how to obtain back the previous behaviour

I'm not sure what the legacy hooks were returning in this case... But most likely not what you expect :D 

If you just want the gradient of the output of the relu, I would actually recommend using a Tensor hook directly on that output. So that you won't have this issue for the grad input that you don't care about.
Note that such Tensor hook can be installed from within a Module forward hook to make it easy to write before-hand.

**Comment by albanD** [comment]
What I meant is that if you have access to the Tensor, you can use a Tensor hook:
```python
# This one will be called during the backward
def tensor_hook(grad): print(grad.size())

# Register this wherever you have access to the Tensor for which you want to print the gradients
your_tensor.register_hook(tensor_hook)
```

If you want to still use your Sequential Module and don't have access to the Tensor directly, you can get it via a forward hook:
```python
# This one will be called during the backward
def tensor_hook(grad): print(grad.size())

# This one will be called during the forward
def fw_hook(mod, input, output):
    output.register_hook(tensor_hook)

# Register this at the same place where you used to register the backward hook
mod[2].register_forward_hook(fw_hook)
```

**Comment by frgfm** [comment]
Thank you so much @albanD :pray: 
You just opened another realm of possibilities for me haha

It actually makes me wonder why using `register_full_backward_hook` instead of this trick :)

**Comment by qq-me** [comment]
so it looks like register_backward_hook works fine while register_full_backward_hook doesn't. However it says 
```
UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes
```
I don't really know what that means but I hope they don't remove register_backward_hook  too soon because it seems like that works fine so far
