### ISSUE TITLE
ONNX export models with Map (and Sequence) input types

### ISSUE THREAD

**Issue by david-macleod** [pytorch/pytorch#61517]
## 🚀 Feature
Proposal to allow `Dict[str, Tensor]` as an input/output type when exporting torchscript models to ONNX.

## Motivation

Both [ONNX](https://github.com/onnx/onnx/blob/master/docs/IR.md#input--output-data-types) and [onnxruntime](https://github.com/microsoft/onnxruntime/blob/d8f3e46d458397b3fb335477d3efc91e22e160d8/onnxruntime/test/shared_lib/test_nontensor_types.cc#L28-L65) support non-tensor inputs/outputs i.e. Sequences and Maps, it would be very useful if PyTorch could export models which utilized this.

ONNX models are completely stateless in inference mode, this means that any state which _could_ have been updated in a torchscript model using setattr/getattr, instead needs to be passed through the model explicitly as an an additional input/output. In complex scenarios where state consists of many tensors of various shapes/sizes, managing this could be made much simpler if the state could be contained as a Map/Dict object.

## Alternatives

- Having many variables representing inputs/outputs of a model, although this quickly becomes unmanageable
- Another alternative is to trace the model which allows dictionary of inputs, by implicitly mapping them to separate inputs of the ONNX graph at export time, but then we still have to deal with many discrete inputs to the session at runtime, and lose the flow control with scripting provides us.

## Additional context

Is this feature currently on the ONNX roadmap, and if not, what are the potential blockers for someone that might want to look into implementing this?

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment]
@david-macleod thank you for the proposal. Do you have a model example demonstrating the importance of statefulness even for inference only?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.

**Comment by mlinxiang** [comment]
has the same need, when i do research in speec recognition use rnn-t arch, when deploy online this need streaming decode wav, so we need to cache the previous wav state which had compute before, the cache structure is dict[str, tensor] or [str, dict[str, tensor]], if this feature not support, we need to flatten all params as input and output

**Comment by garymm** [comment]
Are there any ONNX ops that support map types? I looked briefly and didn't see it. If not, then that needs to be added to the ONNX standard before the exporter can do anything with it.

**Comment by mlinxiang** [comment]
> Are there any ONNX ops that support map types? I looked briefly and didn't see it. If not, then that needs to be added to the ONNX standard before the exporter can do anything with it.

ONNX has support Seq and Map structure as desc [https://github.com/onnx/onnx/blob/main/docs/IR.md](url)
![image](https://user-images.githubusercontent.com/6283983/155910323-4346b27b-8b75-4b29-b215-e0b07bcb175a.png)

**Comment by thiagocrepaldi** [comment]
> > Are there any ONNX ops that support map types? I looked briefly and didn't see it. If not, then that needs to be added to the ONNX standard before the exporter can do anything with it.
> 
> ONNX has support Seq and Map structure as desc [https://github.com/onnx/onnx/blob/main/docs/IR.md](url) ![image](https://user-images.githubusercontent.com/6283983/155910323-4346b27b-8b75-4b29-b215-e0b07bcb175a.png)

Yes, maps are on the ONNX spec. The question is whether there is any standard ONNX operator that actual makes use of such construct. If there is and they are important for the community, we can try to prioritize it over current roadmap

**Comment by mlinxiang** [comment]
i think my question is focus on the export interface but not ONNX operator, as now torch.onnx.export parameters only support tensor or  tuple tensor, which is very limited for stateful scenes such as seq2seq model which need cache previous result of chunk input

**Comment by garymm** [comment]
@thiagocrepaldi that's not accurate. The position of the dict arg shouldn't matter.
But the caveats in the first link are relevant here: 

> Any computation that depends on the value of a dict or a str input will be replaced with the constant value seen during the one traced execution.
