### ISSUE TITLE
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":518, please report a bug to PyTorch. 18118 not in scope

### ISSUE THREAD

**Issue by cguagliano-lm** [pytorch/pytorch#61543]
## 🐛 Bug

```
RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":518, please report a bug to PyTorch. 18118 not in scope
```

While exporting a model from PyTorch to ONNX, the above error is thrown.  

I am trying to convert the model from PyTorch --> ONNX --> TensorRT.  As a side note, the model is capable of being torchscripted via tracing _and_ scripting (using `torch.jit.script` and `torch.jit.trace`) so I do not believe the issue occurs during the torchscript call within `torch.onnx.export`.

## To Reproduce

1. Using rwightman-efficientdet repo: https://github.com/rwightman/efficientdet-pytorch/tree/master/
1. Run 
```
import torch
from effdet import create_model

with set_layer_config(scriptable=True):
      model = create_model(
                      'tf_efficientdet_d4',
                      bench_task='predict',
                      ...,
                  )
model = model.cuda()
model = model.eval()
model.model.toggle_head_bn_level_first() # must toggle heads to make torchscript happy
input_img = torch.rand([1, 3, 1024, 1024])
torch.onnx.export(model, # model
                  input_img,  # input (can be a tuple of multiple inputs)
                  "effdet.onnx", # filepath
                  export_params=True, # store weights in ONNX file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                 )
```
results in the below stack trace:
```
-----------------------------------------------------------------------
RuntimeError                          Traceback (most recent call last)
<ipython-input-8-28a9f16721c5> in <module>
----> 1 torch.onnx.export(model, # model
      2                   input_img,  # input (can be a tuple of multiple inputs)
      3                   "effdet.onnx", # filepath
      4                   export_params=True, # store weights in ONNX file
      5                   opset_version=11,          # the ONNX version to export the model to

/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
    269 
    270     from torch.onnx import utils
--> 271     return utils.export(model, args, f, export_params, verbose, training,
    272                         input_names, output_names, aten, export_raw_ir,
    273                         operator_export_type, opset_version, _retain_param_name,

/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     86         else:
     87             operator_export_type = OperatorExportTypes.ONNX
---> 88     _export(model, args, f, export_params, verbose, training, input_names, output_names,
     89             operator_export_type=operator_export_type, opset_version=opset_version,
     90             _retain_param_name=_retain_param_name, do_constant_folding=do_constant_folding,

/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, enable_onnx_checker, use_external_data_format, onnx_shape_inference, use_new_jit_passes)
    689 
    690             graph, params_dict, torch_out = \
--> 691                 _model_to_graph(model, args, verbose, input_names,
    692                                 output_names, operator_export_type,
    693                                 example_outputs, _retain_param_name,

/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, example_outputs, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, use_new_jit_passes, dynamic_axes)
    458     params_dict = _get_named_param_dict(graph, params)
    459 
--> 460     graph = _optimize_graph(graph, operator_export_type,
    461                             _disable_torch_constant_prop=_disable_torch_constant_prop,
    462                             fixed_batch_size=fixed_batch_size, params_dict=params_dict,

/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict, use_new_jit_passes, dynamic_axes, input_names, module)
    172 
    173         # onnx does not support tuples, so try to remove them
--> 174         torch._C._jit_pass_lint(graph)
    175 
    176         # onnx only supports tensors, but 1 / 2 = 0.5 and tensor(1) / tensor(2) = 0

RuntimeError: 0 INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":518, please report a bug to PyTorch. 18118 not in scope
```

## Expected behavior

Export model to .onnx file.  To confirm my environment and installs were working, I successfully exported a simple resnet:
```
# Test with resnet
import torchvision
import torch

resnet = torchvision.models.resnet18()
resnet.to(0)

torch.onnx.export(resnet, # model
                  input_img, # input (can be a tuple of multiple inputs)
                  "resnet.onnx", # filepath
                  export_params=True) # stored weights in ONNX file
```
successfully exports `resnet.onnx`

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0a0+df837d0
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.19.6

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.181.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] nvidia-dlprof-pytorch-nvtx==1.0.0
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.9.0a0+df837d0
[pip3] torchtext==0.9.0a0
[pip3] torchvision==0.9.0a0
[pip3] trtorch==0.4.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.19.2           py38h6163131_0  
[conda] numpy-base                1.19.2           py38h75fe3a5_0  
[conda] nvidia-dlprof-pytorch-nvtx 1.0.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.0                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.9.0a0+df837d0          pypi_0    pypi
[conda] torchtext                 0.9.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0                  pypi_0    pypi
[conda] trtorch                   0.4.0a0                  pypi_0    pypi
```

## Additional context

If it helps, I am using the NVIDIA trtorch container built from [Dockerfile.21.03](https://github.com/NVIDIA/TRTorch/blob/master/docker/Dockerfile.21.03).  As an aside - converting Torchscript --> TensorRT using TRTorch did not work, either.

cc @BowenBao @neginraoof @gmagogsfm

**Comment by tugsbayasgalan** [comment]
@SplitInfinity  do you know anyone who can help look at this?

**Comment by sudeepf** [comment]
+1, 
Facing similar issue here with error 
``RuntimeError: outputs_[i]->uses().empty() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/ir.cpp":1172, please report a bug to PyTorch. ``
When trying to test resnet18().

**Comment by SplitInfinity** [comment]
cc: @BowenBao

**Comment by BowenBao** [comment]
hi @cguagliano-lm , I could not repro this error on latest PyTorch, could you try upgrading your PyTorch version? On latest PyTorch I observe the error `"_is" operator is not supported `. This is related to exporting optional values, and we are currently working on it.

**Comment by cguagliano-lm** [comment]
> hi @cguagliano-lm , I could not repro this error on latest PyTorch, could you try upgrading your PyTorch version? On latest PyTorch I observe the error `"_is" operator is not supported `. This is related to exporting optional values, and we are currently working on it.

thanks for taking a look at this, @BowenBao.  

I was under the impression that 1.9.0 was the latest stable release.  Which version do you suggest upgrading to?

**Comment by BowenBao** [comment]
@cguagliano-lm PyTorch nightly. However please note that the `_is` operator issue is currently still open. 
You may try to workaround it by changing the model code on https://github.com/rwightman/efficientdet-pytorch/blob/b3dcb20e45a4d5e3ad35146a9723de2d41aae999/effdet/bench.py#L60, restricting `img_scale` and `img_size` to be required `torch.Tensor` arguments, instead of `Optional[torch.Tensor]` with default `None`.

**Comment by momstouch** [comment]
> @cguagliano-lm PyTorch nightly. However please note that the `_is` operator issue is currently still open.
> You may try to workaround it by changing the model code on https://github.com/rwightman/efficientdet-pytorch/blob/b3dcb20e45a4d5e3ad35146a9723de2d41aae999/effdet/bench.py#L60, restricting `img_scale` and `img_size` to be required `torch.Tensor` arguments, instead of `Optional[torch.Tensor]` with default `None`.

Hi, I'm trying to export some model (https://github.com/ming024/FastSpeech2) to onnx, and I got the same problem. And mine is:

`/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/tensor.py:587: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  warnings.warn('Iterating over a tensor might cause the trace to be incorrect. '
Traceback (most recent call last):
  File "torch2lite.py", line 195, in <module>
    torch.onnx.export(
  File "/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/onnx/utils.py", line 691, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/onnx/utils.py", line 460, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/hangil.jeong/miniconda3/envs/torch2tf/lib/python3.8/site-packages/torch/onnx/utils.py", line 174, in _optimize_graph
    torch._C._jit_pass_lint(graph)
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/ir.cpp":518, please report a bug to PyTorch. 8120 not in scope`

I have added  "@torch.jit.script" on the top of two of functions. Do I just look at these functions?

**Comment by BowenBao** [comment]
@momstouch please also try pytorch nightly. If it does not resolve the above issue, please share a sample repro script.

**Comment by garymm** [comment]
Closing due to lack of reply. If this is still an issue in the latest PyTorch nightly, please open a new issue with clear repro instructions.
