### ISSUE TITLE
TypeError: __init__() should return None, not 'int' in validation Dataset

### ISSUE THREAD

**Issue by H-B-L** [pytorch/pytorch#61541]
My cnn model is working perfectly without data augmentation, Then I need to  add data augmentation using transformers in cnn model but got the error below: 

 "val_dataset = dataset(self.num, self.transform, is_train=False)       
TypeError: __init__() should return None, not 'int'  "

The Dateset class and transformer I am using is as below:

    transform= transforms.Compose([
                torchvision.transforms.RandomAffine(degrees=(-20,20),
                translate=(0.1,0.1),
                scale=(0.8,1.2)),
                transforms.Normalize([0.485], [0.229])])     
    
    class dataset(Dataset):
        def __init__(self, num, transform, path0=os.getcwd(), train_ratio = 0.8, 
                     is_train=True, loader=loader):

        self.train_list, self.test_list = train_test_split(np.arange(num), 
                                                           train_size=train_ratio, 
                                                           random_state=42)
        self.is_train = is_train
        self.loader = loader
        self.transform = transform
        
        if self.is_train is True:
            return len(self.train_list)
        else:
            return len(self.test_list)
    
    def __getitem__(self, idx):
        if self.is_train is True:
            fidx = self.train_list[idx]
            train_image = self.loader(fidx, 'img')
            train_mat = self.loader(fidx, 'mat')
            train_mask_geo = self.loader(fidx, 'mask_geo')
            train_mask_crack = self.loader(fidx, 'mask_crack')           
            
            if self.transform:
                train_image = self.transform(train_image)
                print(type(train_image))
                train_mask_geo = self.transform(train_mask_geo)
                train_mask_crack = self.transform(train_mask_crack)
                                
            return train_image,train_mat,train_mask_geo,train_mask_crack
        
        else:
            fidx = self.test_list[idx]
            test_image = self.loader(fidx, 'img')
            test_mat = self.loader(fidx, 'mat')
            test_mask_geo = self.loader(fidx, 'mask_geo')
            test_mask_crack = self.loader(fidx, 'mask_crack') 
            if self.transform:
                test_image = self.transform(test_image,)
                print(type(test_image))
                test_mask_geo = self.transform(test_mask_geo)
                test_mask_crack = self.transform(test_mask_crack)

            return test_image, test_mat, test_mask_geo, test_mask_crack
 
     def train_dataloader(self):
            train_dataset = dataset(self.num, self.transform, is_train=True)
            train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                              num_workers=num_workers, pin_memory=True) 
            return train_loader
      
    def val_dataloader(self):
        val_dataset = dataset(self.num, self.transform, is_train=False)       
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False,
                          num_workers=num_workers, pin_memory=True) 
        return val_loader
       

cc @SsnL @VitalyFedyunin @ejguan

**Comment by heitorschueroff** [comment]
the __init__() function should return nothing but you are returning the length of the list. If you are trying to access the length of the list, could you do that via a method in your dataset class?

**Comment by malfet** [comment]
Closing, as this does not look like a bug in PyTorch, but rather a mis-use of  Python data model.
For example, following code raises the same runtime error:
```
class Bar:
    def __init__(self, bar):
        self.bar = bar
        return bar

if __name__ == "__main__":
    x = Bar(5)
```
```
% python3 bar.py
Traceback (most recent call last):
  File "bar.py", line 7, in <module>
    x = Bar(5)
TypeError: __init__() should return None, not 'int'
```
