### ISSUE TITLE
`clang-tidy` job doesn't print errors

### ISSUE THREAD

**Issue by 1ntEgr8** [pytorch/pytorch#61563]
GHA stops on the first command that returns a non-zero exit code. 

If there is a clang-tidy warning, the script raises a RuntimeError (which causes it to return a non-zero exit code). Since the redirection is only for stdout, the python stacktrace is printed and execution is stopped.

Example:
https://github.com/pytorch/pytorch/pull/53180/checks?check_run_id=3051594542

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Should be fixed, closing
