### ISSUE TITLE
Sums of ByteTensor Variables are bytes.

### ISSUE THREAD

**Issue by spott** [pytorch/pytorch#6157]
This is incredibly unexpected behavior that should have a warning or throw an error:

```
var1 = Variable(torch.from_numpy(np.ones(300))).long()
var2 = Variable(torch.from_numpy(np.ones(300))).long()
count = (var1 == var2).sum()
print(count)
```
prints:
```
Variable containing:
 44
[torch.ByteTensor of size 1 (GPU 0)]
```

It should have the value "300".

This is on pytorch 3.1, in python 3.6.  It happens if the variables are cuda variables or not.  It *does not* happen with tensors, just with variables.

**Comment by ezyang** [comment]
Yep, we're working on it. See #5966
