### ISSUE TITLE
Can't set deterministic=True  in torch.bmm() in Torch 1.9.0 with Cuda 11.1 and A100 GPU

### ISSUE THREAD

**Issue by lcrun** [pytorch/pytorch#61571]
I want to enable deterministic=True  in 

    out = torch.bmm(reshaped_x, self.weight1, deterministic=True)

But got :   **TypeError: bmm() got an unexpected keyword argument 'deterministic'**

## Code example

 _out = torch.bmm(reshaped_x, self.weight1, deterministic=True)_

## System Info

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

root@d93c8a2d8eae:/tmp# python collect_env.py
Collecting environment information...
PyTorch version: 1.9.0a0+git4f50fdc
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.27

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.0a0+git4f50fdc
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.9.0a0+git4f50fdc          pypi_0    pypi
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.9.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

**Comment by ngimel** [comment]
cc @kurtamohler, looking at native_functions.yaml it doesn't look like `deterministic` algo is really supported for `bmm`, it's only supported for `_bmm`

**Comment by kurtamohler** [comment]
That's my mistake. I'll remove the mention of the `deterministic` argument from the `torch.bmm` documentation.

@lcrun, you can set `torch.use_deterministic_algorithms(True)` before your bmm call to use the deterministic implementation.

@ngimel I wonder if we should remove `_bmm`. The only reason it was added was to offer the deterministic implementation, before we had torch.use_deterministic_algorithms.

**Comment by ngimel** [comment]
@kurtamohler yes, removing `_bmm` sounds like a good idea, we don't have `deterministic` kwarg for other functions, so `bmm` should not be different.

**Comment by lcrun** [comment]
Thank you @kurtamohler.  But seems torch.bmm() has no deterministic implement for the **CUDA** backend :
I tried:

**1. _bmm(a, b, deterministic=True)**
But got: 
_[1,2]<stderr>:RuntimeError: Could not run 'aten::_bmm' with arguments from the '**CUDA**' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_bmm' is only available for these backends: [SparseCUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].


**2. torch.use_deterministic_algorithms(True)**
But got: 
_:RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation._

**Comment by kurtamohler** [comment]
@Icrun, interesting thank you for the info! Could you please post a minimal reproducer script here? It's hard for me to help debug without that.

I tried the following, with both CUDA dense-dense and CUDA sparse-dense, and I did not get a nondeterministic error:

```python
import torch
torch.use_deterministic_algorithms(True)
a = torch.randn(10, 10, 10).cuda()
b = torch.randn(10, 10, 10).cuda()
c = torch.bmm(a, b)
d = torch.bmm(a.to_sparse(), b)
```

I also tried to find a `scatter_add` call within the `bmm` code and didn't find one, and it doesn't seem like a `scatter_add` call would be necessary within `bmm`. However, just because I didn't see it, that doesn't mean it isn't there.

Is it possible that the `scatter_add_cuda_kernel` nondeterministic error is coming from a different function call in your script, not from `bmm`? Are you calling `scatter_add` directly in your script? You could try turning off the deterministic algorithms flag after the `bmm` call to find out, like this:

```python
...
torch.use_deterministic_algorithms(True)
out = torch.bmm(reshaped_x, self.weight1)
torch.use_deterministic_algorithms(False)
...
```

**Comment by ngimel** [comment]
For `bmm` calls on cuda versions >=10.2 non-deterministic error is thrown, but error message provides instructions on how to enable deterministic implementation (you have to set env variables to control cublas behavior).

**Comment by kurtamohler** [comment]
@ngimel, that's right. However, just to clarify, the error @Icrun posted above is different from the cublas one

**Comment by kurtamohler** [comment]
I'm reopening this since Icrun's issue still has some unanswered questions

**Comment by luckywyy** [comment]
If I don't want this "nottorch.use_deterministic_algorithms(True)", what can I do?
