### ISSUE TITLE
Bfloat16 build errors on pp64le in vec_test_all_types.cpp

### ISSUE THREAD

**Issue by dncliss** [pytorch/pytorch#61575]
## 🐛 Bug

The pytorch build on platform `ppc64le` began failing a couple weeks back, and the failure has persisted. The failure
occurs when the build reaches file `aten/src/ATen/test/vec_test_all_types.cpp` and the nature of the failure is
that multiple errors are referenced back to `functional_bfloat16.h` regarding "...no arguments... that depend on a template parameter ..." -- in fact, for more context it is best to refer to the full output of a build on that platform from the nightly CI builds at OSUOSL.  An example build can be seen here, at this page: https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le-gpu/1169/console

One of many such errors reads as such:
```
[01m[K../aten/src/ATen/cpu/vec/vec256/functional_bfloat16.h:[m[K In function ‘[01m[Kc10::BFloat16 at::vec::reduce_all(const Op&, const c10::BFloat16*, int64_t)[m[K’:
[01m[K../aten/src/ATen/cpu/vec/vec256/functional_bfloat16.h:47:40:[m[K [01;31m[Kerror: [m[Kthere are no arguments to ‘[01m[Kconvert_bfloat16_float[m[K’ that depend on a template parameter, so a declaration of ‘[01m[Kconvert_bfloat16_float[m[K’ must be available [[01;31m[K-fpermissive[m[K]
     std::tie(data_fvec0, data_fvec1) = [01;31m[Kconvert_bfloat16_float[m[K(data_bvec);
                                        [01;31m[K^~~~~~~~~~~~~~~~~~~~~~[m[K
```

## To Reproduce

Build pytorch on ppc64le, or review the nightly CI builds as seen at powerai.osuosl.org.

## Expected behavior
The build should proceed cleanly to completion, as it had been until a couple weeks ago. NOTE: the builds
had been clean before the inclusion of the apparent injecting PR, which appears to have caused the failures
to start:  https://github.com/pytorch/pytorch/pull/55202

## Environment

PPC64LE, on Ubuntu Linux: see output data from any recent CI runs at https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le-gpu/
 (...such as the latest at this writing...):
https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le-gpu/1169/console

 

cc @malfet @seemethere @walterddr @yf225 @glaringlee

**Comment by malfet** [comment]
Unless PowerPC builds can somehow be enabled on PR, such issues will keep popping up.
