### ISSUE TITLE
torch.linalg.cholesky fails for some PSD matrices

### ISSUE THREAD

**Issue by jameschapman19** [pytorch/pytorch#61581]
## 🐛 Bug

torch.linalg.cholesky produces the error:

RuntimeError: torch.linalg.cholesky: U(244,244) is zero, singular U. For certain inputs which are not singular. It seems to relate to inconsistencies between torch.linalg.eigvalsh and np.linalg.eigvalsh (I have highlighted these in the reproducing script.

[issue_array.zip](https://github.com/pytorch/pytorch/files/6809568/issue_array.zip)

## To Reproduce

Use attached code

```
import torch
import numpy as np
from numpy.testing import assert_array_equal

M = np.load('issue_array.npy')

assert_array_equal(M,M.T), "Not Symmetric"

numpy_eigvals = np.linalg.eigvalsh(M)
print(f"Numpy: 5 smallest eigenvalues {np.partition(numpy_eigvals, 5)[:5]}")
numpy_svd = np.linalg.svd(M)[1]
print(f"Numpy: 5 smallest singular values {np.partition(numpy_svd, 5)[:5]}")
numpy_chol = np.linalg.cholesky(M)

M = torch.tensor(M)
torch_eigvals = torch.linalg.eigvalsh(M)
print(f"Torch: 5 smallest eigenvalues {np.partition(torch_eigvals.numpy(), 5)[:5]}")
torch_svd = torch.linalg.svdvals(M)
print(f"Torch: 5 smallest singular values {np.partition(torch_svd.numpy(), 5)[:5]}")
torch_chol = torch.linalg.cholesky(M)
```

## Expected behavior

Expect no error. Matrix is PSD so has a cholesky decomposition.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version : 1.9.0
 - OS : Windows
 - How you installed PyTorch : pip
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration:
 - Any other relevant information:

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by jameschapman19** [comment]
Could also be viewed as just np.linalg.eigvalsh() inconsistent with torch.linalg.eigvalsh()

**Comment by xwang233** [comment]
```python
Numpy: 5 smallest eigenvalues [0.0304075  0.03341552 0.03688819 0.03782178 0.03933585]
Numpy: 5 largest eigenvalues [8.5137604e+02 2.1137925e+03 3.2010125e+03 3.4950852e+04 4.6525870e+06]
Numpy: 5 smallest singular values [0.0304075  0.03341552 0.03782178 0.03688819 0.03933585]
Numpy: 5 largest singular values [3.2043192e+02 8.5137604e+02 2.1137925e+03 3.2010125e+03 4.6525870e+06]
torch.float32
cpu
Torch: 5 smallest eigenvalues tensor([-0.1470, -0.0201,  0.0746,  0.0908,  0.0936])
Torch: 5 largest eigenvalues tensor([8.5139e+02, 2.1138e+03, 3.2011e+03, 3.4951e+04, 4.6526e+06])
Torch: 5 smallest singular values [0.01554988 0.05605506 0.06259368 0.0717091  0.08598142]
Torch: 5 largest singular values [8.5137653e+02 2.1137915e+03 3.2010142e+03 3.4950871e+04 4.6525850e+06]
Traceback (most recent call last):
  File "/xxx/61581.py", line 37, in <module>
    torch_chol = torch.linalg.cholesky(M)
RuntimeError: torch.linalg.cholesky: U(252,252) is zero, singular U.
```

To me, this seems like an ill-conditioned matrix, and linear algebra algorithms are unstable. If you try double precision, you would get accurate eigenvalues and Cholesky decomposition results.

**Comment by jameschapman19** [comment]
Thanks for your response. Makes total sense - the context of the problem is trying to add a small amount of (tikhonov) regularization to make cholesky stable so aware of the stability problem just my fix was mixing precisions as you say. With double precision numpy==pytorch. Feel free to close.
