### ISSUE TITLE
[Meta] PyTorch GitHub Action migration issues

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#61604]
This meta is to track any missing features/flakiness associated with GitHub Action workflows in PyTorch CI

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
For example, can better information on what have failed been surfaced from https://github.com/pytorch/pytorch/pull/61484/checks?check_run_id=3053054231

**Comment by samestep** [comment]
See also #57686.

**Comment by malfet** [comment]
Another interesting failure with no good info to debug it: https://github.com/pytorch/pytorch/runs/3117720511

**Comment by malfet** [comment]
One more thing: clang-tidy step is mentioned twice in this run https://github.com/pytorch/pytorch/pull/62008/checks?check_run_id=3137995812 (attaching screenshot just in case)
<img width="844" alt="Screen Shot 2021-07-22 at 1 56 22 PM" src="https://user-images.githubusercontent.com/2453524/126708505-86f311ca-26db-49a9-8af3-77a984be4bf7.png">

**Comment by malfet** [comment]
Again, not many signal on how to debug something like that: https://github.com/pytorch/pytorch/runs/3186552523

**Comment by driazati** [comment]
> One more thing: clang-tidy step is mentioned twice in this run https://github.com/pytorch/pytorch/pull/62008/checks?check_run_id=3137995812 (attaching screenshot just in case)
> <img alt="Screen Shot 2021-07-22 at 1 56 22 PM" width="844" src="https://user-images.githubusercontent.com/2453524/126708505-86f311ca-26db-49a9-8af3-77a984be4bf7.png">

This is expected, we have a separate step for PRs vs master (we could/should merge them and move the `if`s into bash): https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml#L344-L358

**Comment by mruberry** [comment]
Another infra failure: https://github.com/pytorch/pytorch/pull/63841/checks?check_run_id=3459187242.

**Comment by malfet** [comment]
Moved from https://github.com/pytorch/pytorch/issues/57686 by @suo:

Seems to be a GHA infra failure: https://github.com/pytorch/pytorch/runs/3507620758

Looks like GHA infra failure: https://github.com/pytorch/pytorch/runs/3499529304

**Comment by malfet** [comment]
A number of issues with windows build logging (reference example https://github.com/pytorch/pytorch/pull/63918/checks?check_run_id=3424926066)
1. Logs start at the beginning. Failures are always at the bottom. Can we start at the bottom?
2. Logs are truncated at some point. Since failures are always at the bottom, this eliminates any information about the job failure from the main web UI. Can we truncate the beginning instead of end (basically run `tail` instead of `head` on the log)?
3. (nit) the message that tells me to download the full log at the bottom contains a gear symbol that doesn't exist on the web page.
4. (serious) when I download the raw log with "view raw logs"—*this log is truncated as well*. This is a serious issue as it eliminates the signal entirely from any easily accessible place. I can download all artifacts, unzip, and root around, but this is a faintly ridiculous thing to have to do to see my build failures.Logs start at the beginning. Failures are always at the bottom. Can we start at the bottom?
Logs are truncated at some point. Since failures are always at the bottom, this eliminates any information about the job failure from the main web UI. Can we truncate the beginning instead of end (basically run tail instead of head on the log)?
(nit) the message that tells me to download the full log at the bottom contains a gear symbol that doesn't exist on the web page.
(serious) when I download the raw log with "view raw logs"—this log is truncated as well. This is a serious issue as it eliminates the signal entirely from any easily accessible place. I can download all artifacts, unzip, and root around, but this is a faintly ridiculous thing to have to do to see my build failures.

--
Moved @suo comment from #57686 to here

**Comment by seemethere** [comment]
Migration has been mostly completed, this issue is not relevant anymore. Closing.
