### ISSUE TITLE
Add option to build without catch2 / fix catch2 build errors on Windows

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6162]
https://github.com/pytorch/pytorch/issues/494#issuecomment-375521846 suggests that (1) we always build with catch, even when you aren't interested in testing, and (2) there might be some situations where catch2 does not compile correctly on Windows. It should be possible to build without catch.

**Comment by peterjc123** [comment]
Where is the catch2 source files included in build? ATen? or any submodule?

**Comment by ezyang** [comment]
we don't use catch anymore, we use gtest
