### ISSUE TITLE
Build error: undefined reference to `benchmark::Shutdown()' 

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#61624]
## 🐛 Bug

I'm trying to install PyTorch but it fails with a build error.

## To Reproduce

1. `git clone https://github.com/spack/spack.git`
1. `. spack/share/spack/setup-env.sh`
1. `spack install py-torch`

The resulting error message is:
```
[3038/5601] Linking CXX executable bin/c10_intrusive_ptr_benchmark
FAILED: bin/c10_intrusive_ptr_benchmark
: && /mnt/a/u/sciteam/stewart1/spack/lib/spack/env/gcc/g++ -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -O3 -DNDEBUG -DNDEBUG -rdynamic c10/benchmark/CMakeFiles/c10_intrusive_ptr_benchmark.dir/intrusive_ptr_benchmark.cpp.o -o bin/c10_intrusive_ptr_benchmark  -Wl,-rpath,/mnt/c/scratch/sciteam/stewart1/spack-stage-py-torch-master-xyty4kb5y77vp57r5d3lxm3zjv56wgzn/spack-src/build/lib:/mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.5.0/pthreadpool-master-wuht5mcrmbun3aqsg5bnxpfjmyfndld3/lib64:  lib/libc10.so  /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.5.0/pthreadpool-master-wuht5mcrmbun3aqsg5bnxpfjmyfndld3/lib64/libbenchmark.so && :
c10/benchmark/CMakeFiles/c10_intrusive_ptr_benchmark.dir/intrusive_ptr_benchmark.cpp.o: In function `main':
intrusive_ptr_benchmark.cpp:(.text.startup+0x31): undefined reference to `benchmark::Shutdown()'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

## Expected behavior

I would expect the installation to succeed.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Cray CNL5
 - How you installed PyTorch (`conda`, `pip`, source): `spack`
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.8.11
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

## Additional context

Here are the appropriate build logs:

* [build log](https://github.com/pytorch/pytorch/files/6813104/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/6813105/spack-build-env.txt)

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
There are two issues here:
- linker error 
- one doesn't have to build C++ test to install PyTorch

**Comment by adamjstewart** [comment]
@malfet aren't these tests disabled by default?
```cmake
option(BUILD_TEST "Build C++ test binaries (need gtest and gbenchmark)" OFF)
```
I could try explicitly disabling them.

**Comment by adamjstewart** [comment]
Explicitly disabling `BUILD_TEST` seems to get me past this build error, thanks for the suggestion! Of course, it would be good to get to the bottom of this build error, so I'll leave this open for now.

**Comment by adamjstewart** [comment]
This is very out-of-date and I haven't encountered this issue on any modern system, I think we can close this.
