### ISSUE TITLE
fake_quantize_per_channel_affine backward error

### ISSUE THREAD

**Issue by KeyKy** [pytorch/pytorch#61625]
pytorch commid id: ad7d208ba5f2c5614679a7999918b75ae74530e9

torch.fake_quantize_per_channel_affine can not accumulate gradient in LSTM. After i use with torch.autograd.set_detect_anomaly(True):, i get the follow error:

```
File "lib/python3.6/site-packages/torch/quantization/fake_quantize.py", line 144, in forward

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1024]] is at version 27; expected version 26 instead. 
Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

LSTM is a recurrent network, when forward, torch.fake_quantize_per_channel_affine will run multiple times.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by KeyKy** [comment]
a simple code to reproduce the error:

```
weight_fq = qconfig.weight()
weight = torch.rand(1024, 512)
weight = Variable(weight, requires_grad=True)
o0 = weight_fq(weight)
o1 = weight_fq(weight)
o2 = weight_fq(weight)
o = o0 + o1 + o2
o.sum().backward()
```

**Comment by supriyar** [comment]
Hi @KeyKy 
We've made some changes to the fake_quantize functions since ad7d208 so they should work better with autograd. I tried with the latest pytorch nightly and this issue doesn't exist anymore.

Closing the issue out since it works in latest pytorch release, please let me know if there is anything I missed!
