### ISSUE TITLE
[feature request] `torch.dumps` and `torch.loads`

### ISSUE THREAD

**Issue by samuela** [pytorch/pytorch#6163]
So pytorch currently offers

```python
torch.save(the_model, PATH)
the_model = torch.load(PATH)
```

and these are nice but a lot of standard pickling and serialization libraries feature functions `dumps()` and `loads()` (eg https://docs.python.org/3/library/pickle.html#pickle.dumps and https://docs.python.org/3/library/pickle.html#pickle.loads) which offer the ability to serialize the data into a bytes object instead of directly to a file. This can be handy in a number of situations, esp. if you have some other storage system that you want to utilize, or send them over the network, etc.

**Comment by apaszke** [comment]
```python3
buffer = io.BytesIO()
torch.save(the_model, buffer)
the_model = torch.load(buffer)
```

**Comment by samuela** [comment]
@apaszke I'm not having luck with that.

```python
import torch
from torch.autograd import Variable

import io

torch.manual_seed(0)
v = Variable(torch.randn(3))
print(v)

buffer = io.BytesIO()
torch.save(v, buffer)
print(buffer)
print(torch.load(buffer))
```

gives me 
```
Variable containing:
 1.5410
-0.2934
-2.1788
[torch.FloatTensor of size 3]

Traceback (most recent call last):
  File "test_torch_save.py", line 11, in <module>
    torch.save(v, buffer)
  File "/Users/samuelainsworth/Development/babar/venv/lib/python3.6/site-packages/torch/serialization.py", line 134, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/samuelainsworth/Development/babar/venv/lib/python3.6/site-packages/torch/serialization.py", line 116, in _with_file_like
    return body(f)
  File "/Users/samuelainsworth/Development/babar/venv/lib/python3.6/site-packages/torch/serialization.py", line 134, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/samuelainsworth/Development/babar/venv/lib/python3.6/site-packages/torch/serialization.py", line 203, in _save
    serialized_storages[key]._write_file(f)
RuntimeError: _write_file couldn't retrieve a file descriptor from given object
```

**Comment by apaszke** [comment]
It's been added lately, so you need to install from source to use this feature

**Comment by samuela** [comment]
Also, I'm a little confused about the exact semantics of `torch.save()` and `torch.load()`. Do they operate properly on pytorch objects nested in other data structures? Eg. will

```python
torch.save([pytorch_model1, pytorch_model2, {'asdf': pytorch_model3}], PATH)
stuff = torch.load(PATH)
```

work correctly?

**Comment by samuela** [comment]
@apaszke Ah ok, so this will be in version 0.4 I guess? What's the current timeline for that release?

**Comment by apaszke** [comment]
We’re trying to release it ASAP but there are still a few outstanding issues
