### ISSUE TITLE
Move `lu`, `lu_solve`, and `lu_unpack` into `torch.linalg`

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#61657]
The plan to move these is to follow [scipy's API](https://docs.scipy.org/doc/scipy/reference/linalg.html#decompositions)

For `torch.lu`, we would like to split it into `torch.linalg.lu_factor` and `torch.linalg.lu_factor_ex` (the former implemented as a call to the latter) with the following signatures:
```python
def lu_factor(Tensor A, *, pivot: bool = True, out=None) -> (Tensor lu_factor, Tensor lu_pivots)
def lu_factor_ex(Tensor A, *, pivot: bool = True, check_errors=False, out=None) -> (lu (Tensor lu_factor, Tensor lu_pivots), Tensor info)
```
If `pivot=False`, `lu_pivots` should be an empty tensor.

For `torch.lu_unpack`, we want to combine it with `torch.linalg.lu_factor` and have it as `torch.linalg.lu` with signature
```python
def lu(Tensor A, *, pivot: bool = True, out=None) -> (Tensor P, Tensor L, Tensor U)
```
where `pivot` controls whether we perform an LU with partial pivoting or not. If `pivot=False`, `P` should be an empty tensor.

For `solve_lu`, we want to update it to have signature
```python
def solve_lu(A_lu: (Tensor, Tensor), B: Tensor, *, left: bool = True, adjoint: bool = False) -> Tensor
```
Adjoint will dispatch to `trans='T'` or `trans='C'`depending on the dtype. The `side` should be implemented transposing the inputs and output. If `left=False` and `adjoint=True`, then this is equivalent to solving for `A.conj()`. This is fine, because the LU decomposition of a conjugate matrix is given by conjugating the `lu_factor` matrix.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
FWIW, lu_unpack is backward compatible, lu is waiting to get reviewed/merged, and lu_solve is on its way.
