### ISSUE TITLE
3D loss from Fully Convolution Network (for Segmentation) backward error

### ISSUE THREAD

**Issue by Shaunlipy** [pytorch/pytorch#6166]
Hi, I'm using LogSoftmax(dim=1) for 4D input (batch_size, num_classes, height, width), and with NLLLoss, and generated a 3D tensor.

But when calling loss.backward(), I got error:
''
RuntimeError: grad can be implicitly created only for scalar outputs
''
from the line loss.backward().

Can anyone help?

logsoftmax = nn.LogSoftmax(dim=1).cuda()
criterion = torch.nn.NLLLoss(reduce = False).cuda()

outputs = logsoftmax(outputs)
loss = criterion(outputs, labels)
loss.backward()
 
Thanks.

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2:
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by soumith** [comment]
please use https://discuss.pytorch.org to post questions
